yaze: yaze::editor::ManualObjectRenderer Class Reference
yaze::editor::ManualObjectRenderer Class Reference
Manual object renderer for debugging and testing basic object rendering.
#include <manual_object_renderer.h>
Public Member Functions
ManualObjectRenderer (gui::Canvas *canvas, Rom *rom)
absl::Status RenderSimpleBlock (uint16_t object_id, int x, int y, const gfx::SnesPalette &palette)
Render a simple solid block object manually.
void RenderTestPattern (int x, int y, int width, int height, uint8_t color_index)
Render a test pattern to verify graphics pipeline.
void DebugGraphicsSheet (int sheet_index)
Debug graphics sheet loading and display info.
void TestPaletteRendering (int x, int y)
Test palette rendering with different colors.
std::unique_ptr< gfx::Bitmap > CreateSimpleTile (uint16_t tile_id, const gfx::SnesPalette &palette)
Create a simple 16x16 tile manually.
Private Member Functions
std::vector< uint8_t > CreateSolidTile (uint8_t color_index)
std::vector< uint8_t > CreatePatternTile (uint8_t pattern_type, uint8_t color_index)
void LogGraphicsInfo (int sheet_index)
void LogPaletteInfo (const gfx::SnesPalette &palette)
Private Attributes
gui::Canvas * canvas_
Rom * rom_
Detailed Description
Manual object renderer for debugging and testing basic object rendering.
This class provides simple, manual rendering of basic dungeon objects to help debug the graphics pipeline and understand object data structures.
Features:
Manual tile creation for simple objects
Direct graphics sheet access
Palette debugging and testing
Simple pattern rendering (solid blocks, lines, etc.)
Definition at line 27 of file manual_object_renderer.h.
Constructor & Destructor Documentation
ManualObjectRenderer()
yaze::editor::ManualObjectRenderer::ManualObjectRenderer (gui::Canvas * canvas, Rom * rom) explicit
Definition at line 12 of file manual_object_renderer.cc.
Member Function Documentation
RenderSimpleBlock()
absl::Status yaze::editor::ManualObjectRenderer::RenderSimpleBlock (uint16_t object_id, int x, int y, const gfx::SnesPalette & palette)
Render a simple solid block object manually.
Parameters
object_id Object ID to render
x X position in pixels
y Y position in pixels
palette Current palette to use
Returns
Status of the rendering operation
Definition at line 15 of file manual_object_renderer.cc.
References canvas_, CreateSimpleTile(), yaze::gui::Canvas::DrawBitmap(), and rom_.
RenderTestPattern()
void yaze::editor::ManualObjectRenderer::RenderTestPattern (int x, int y, int width, int height, uint8_t color_index)
Render a test pattern to verify graphics pipeline.
Parameters
x X position in pixels
y Y position in pixels
width Width in pixels
height Height in pixels
color_index Color index to use
Definition at line 35 of file manual_object_renderer.cc.
References canvas_.
Referenced by TestPaletteRendering().
DebugGraphicsSheet()
void yaze::editor::ManualObjectRenderer::DebugGraphicsSheet (int sheet_index)
Debug graphics sheet loading and display info.
Parameters
sheet_index Graphics sheet index to examine
Definition at line 59 of file manual_object_renderer.cc.
References yaze::gfx::Arena::Get(), and rom_.
TestPaletteRendering()
void yaze::editor::ManualObjectRenderer::TestPaletteRendering (int x, int y)
Test palette rendering with different colors.
Parameters
x X position in pixels
y Y position in pixels
Definition at line 81 of file manual_object_renderer.cc.
References RenderTestPattern().
CreateSimpleTile()
std::unique_ptr< gfx::Bitmap > yaze::editor::ManualObjectRenderer::CreateSimpleTile (uint16_t tile_id, const gfx::SnesPalette & palette)
Create a simple 16x16 tile manually.
Parameters
tile_id Tile ID to create
palette Palette to apply
Returns
Created bitmap
Definition at line 92 of file manual_object_renderer.cc.
References CreateSolidTile().
Referenced by RenderSimpleBlock().
CreateSolidTile()
std::vector< uint8_t > yaze::editor::ManualObjectRenderer::CreateSolidTile (uint8_t color_index) private
Definition at line 121 of file manual_object_renderer.cc.
Referenced by CreateSimpleTile().
CreatePatternTile()
std::vector< uint8_t > yaze::editor::ManualObjectRenderer::CreatePatternTile (uint8_t pattern_type, uint8_t color_index) private
Definition at line 126 of file manual_object_renderer.cc.
LogGraphicsInfo()
void yaze::editor::ManualObjectRenderer::LogGraphicsInfo (int sheet_index) private
LogPaletteInfo()
void yaze::editor::ManualObjectRenderer::LogPaletteInfo (const gfx::SnesPalette & palette) private
Member Data Documentation
canvas_
gui::Canvas* yaze::editor::ManualObjectRenderer::canvas_ private
Definition at line 75 of file manual_object_renderer.h.
Referenced by RenderSimpleBlock(), and RenderTestPattern().
rom_
Rom* yaze::editor::ManualObjectRenderer::rom_ private
Definition at line 76 of file manual_object_renderer.h.
Referenced by DebugGraphicsSheet(), and RenderSimpleBlock().
The documentation for this class was generated from the following files:
src/app/editor/dungeon/manual_object_renderer.h
src/app/editor/dungeon/manual_object_renderer.cc