yaze: yaze::cli::agent::anonymous_namespace{conversation_test.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{conversation_test.cc} Namespace Reference
Classes
struct ConversationTestCase
Functions
absl::Status LoadRomForAgent (Rom &rom)
std::vector< ConversationTestCase > GetDefaultTestCases ()
void PrintTestHeader (const ConversationTestCase &test_case)
void PrintUserPrompt (const std::string &prompt)
void PrintAgentResponse (const ChatMessage &response, bool verbose)
bool ValidateResponse (const ChatMessage &response, const ConversationTestCase &test_case)
absl::Status RunTestCase (const ConversationTestCase &test_case, ConversationalAgentService &service, bool verbose)
absl::Status LoadTestCasesFromFile (const std::string &file_path, std::vector< ConversationTestCase > *test_cases)
Function Documentation
LoadRomForAgent()
absl::Status yaze::cli::agent::anonymous_namespace{conversation_test.cc}::LoadRomForAgent (Rom & rom)
Definition at line 26 of file conversation_test.cc.
References yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), and LoadRomForAgent().
Referenced by LoadRomForAgent().
GetDefaultTestCases()
std::vector< ConversationTestCase > yaze::cli::agent::anonymous_namespace{conversation_test.cc}::GetDefaultTestCases ()
Definition at line 56 of file conversation_test.cc.
References GetDefaultTestCases().
Referenced by GetDefaultTestCases().
PrintTestHeader()
void yaze::cli::agent::anonymous_namespace{conversation_test.cc}::PrintTestHeader (const ConversationTestCase & test_case)
Definition at line 128 of file conversation_test.cc.
References yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::description, yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::name, and PrintTestHeader().
Referenced by PrintTestHeader(), and RunTestCase().
PrintUserPrompt()
void yaze::cli::agent::anonymous_namespace{conversation_test.cc}::PrintUserPrompt (const std::string & prompt)
Definition at line 135 of file conversation_test.cc.
References PrintUserPrompt().
Referenced by PrintUserPrompt(), and RunTestCase().
PrintAgentResponse()
void yaze::cli::agent::anonymous_namespace{conversation_test.cc}::PrintAgentResponse (const ChatMessage & response, bool verbose)
Definition at line 139 of file conversation_test.cc.
References yaze::cli::agent::ChatMessage::json_pretty, yaze::cli::agent::ChatMessage::message, PrintAgentResponse(), and yaze::cli::agent::ChatMessage::table_data.
Referenced by PrintAgentResponse(), and RunTestCase().
ValidateResponse()
bool yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ValidateResponse (const ChatMessage & response, const ConversationTestCase & test_case)
Definition at line 201 of file conversation_test.cc.
References yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::expect_commands, yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::expect_tool_calls, yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::expected_keywords, yaze::cli::agent::ChatMessage::message, yaze::cli::agent::ChatMessage::table_data, and ValidateResponse().
Referenced by RunTestCase(), and ValidateResponse().
RunTestCase()
absl::Status yaze::cli::agent::anonymous_namespace{conversation_test.cc}::RunTestCase (const ConversationTestCase & test_case, ConversationalAgentService & service, bool verbose)
Definition at line 232 of file conversation_test.cc.
References yaze::cli::agent::ConversationalAgentService::GetHistory(), yaze::cli::agent::ChatMessage::kUser, yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::name, PrintAgentResponse(), PrintTestHeader(), PrintUserPrompt(), yaze::cli::agent::ConversationalAgentService::ResetConversation(), RunTestCase(), yaze::cli::agent::ConversationalAgentService::SendMessage(), yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::user_prompts, and ValidateResponse().
Referenced by RunTestCase().
LoadTestCasesFromFile()
absl::Status yaze::cli::agent::anonymous_namespace{conversation_test.cc}::LoadTestCasesFromFile (const std::string & file_path, std::vector< ConversationTestCase > * test_cases)
Definition at line 281 of file conversation_test.cc.
References yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::description, yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::expect_commands, yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::expect_tool_calls, yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::expected_keywords, LoadTestCasesFromFile(), yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::name, and yaze::cli::agent::anonymous_namespace{conversation_test.cc}::ConversationTestCase::user_prompts.
Referenced by LoadTestCasesFromFile().