yaze: yaze::cli::agent::anonymous_namespace{palette_commands.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{palette_commands.cc} Namespace Reference
Classes
struct RGB
Functions
RGB SnesColorToRGB (uint16_t snes_color)
uint16_t RGBToSnesColor (uint8_t r, uint8_t g, uint8_t b)
absl::StatusOr< RGB > ParseHexColor (const std::string &str)
std::string FormatColor (uint16_t snes_color, const std::string &format)
Function Documentation
SnesColorToRGB()
RGB yaze::cli::agent::anonymous_namespace{palette_commands.cc}::SnesColorToRGB (uint16_t snes_color)
Definition at line 25 of file palette_commands.cc.
References SnesColorToRGB().
Referenced by FormatColor(), and SnesColorToRGB().
RGBToSnesColor()
uint16_t yaze::cli::agent::anonymous_namespace{palette_commands.cc}::RGBToSnesColor (uint8_t r, uint8_t g, uint8_t b)
Definition at line 34 of file palette_commands.cc.
References RGBToSnesColor().
Referenced by RGBToSnesColor().
ParseHexColor()
absl::StatusOr< RGB > yaze::cli::agent::anonymous_namespace{palette_commands.cc}::ParseHexColor (const std::string & str)
Definition at line 39 of file palette_commands.cc.
References yaze::cli::agent::anonymous_namespace{palette_commands.cc}::RGB::b, yaze::cli::agent::anonymous_namespace{palette_commands.cc}::RGB::g, ParseHexColor(), and yaze::cli::agent::anonymous_namespace{palette_commands.cc}::RGB::r.
Referenced by ParseHexColor().
FormatColor()
std::string yaze::cli::agent::anonymous_namespace{palette_commands.cc}::FormatColor (uint16_t snes_color, const std::string & format)
Definition at line 64 of file palette_commands.cc.
References yaze::cli::agent::anonymous_namespace{palette_commands.cc}::RGB::b, FormatColor(), yaze::cli::agent::anonymous_namespace{palette_commands.cc}::RGB::g, yaze::cli::agent::anonymous_namespace{palette_commands.cc}::RGB::r, and SnesColorToRGB().
Referenced by FormatColor().