yaze: yaze::editor::GraphicsEditor Class Reference
yaze::editor::GraphicsEditor Class Reference
Allows the user to edit graphics sheets from the game or view prototype graphics.
#include <graphics_editor.h>
Public Member Functions
GraphicsEditor (Rom *rom=nullptr)
void Initialize () override
absl::Status Load () override
absl::Status Save () override
absl::Status Update () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
void set_rom (Rom *rom)
Rom * rom () const
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Clear ()
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
virtual bool IsRomLoaded () const
virtual std::string GetRomStatus () const
Private Types
enum class GfxEditMode { kSelect , kPencil , kFill }
Private Member Functions
absl::Status UpdateGfxEdit ()
absl::Status UpdateGfxSheetList ()
absl::Status UpdateGfxTabView ()
absl::Status UpdatePaletteColumn ()
void DrawGfxEditToolset ()
Draw the graphics editing toolset with enhanced ROM hacking features.
absl::Status UpdateLinkGfxView ()
absl::Status UpdateScadView ()
absl::Status DrawCgxImport ()
absl::Status DrawScrImport ()
absl::Status DrawFileImport ()
absl::Status DrawObjImport ()
absl::Status DrawTilemapImport ()
absl::Status DrawToolset ()
absl::Status DrawPaletteControls ()
absl::Status DrawClipboardImport ()
absl::Status DrawExperimentalFeatures ()
absl::Status DrawMemoryEditor ()
absl::Status DecompressImportData (int size)
absl::Status DecompressSuperDonkey ()
Private Attributes
ImVec4 current_color_
uint16_t current_sheet_ = 0
uint8_t tile_size_ = 0x01
std::set< uint16_t > open_sheets_
std::set< uint16_t > child_window_sheets_
std::stack< uint16_t > release_queue_
uint64_t edit_palette_group_name_index_ = 0
uint64_t edit_palette_group_index_ = 0
uint64_t edit_palette_index_ = 0
uint64_t edit_palette_sub_index_ = 0
float sheet_scale_ = 2.0f
float current_scale_ = 4.0f
int current_palette_ = 0
uint64_t current_offset_ = 0
uint64_t current_size_ = 0
uint64_t current_palette_index_ = 0
int current_bpp_ = 0
int scr_mod_value_ = 0
uint64_t num_sheets_to_load_ = 1
uint64_t bin_size_ = 0
uint64_t clipboard_offset_ = 0
uint64_t clipboard_size_ = 0
bool refresh_graphics_ = false
bool open_memory_editor_ = false
bool gfx_loaded_ = false
bool is_open_ = false
bool super_donkey_ = false
bool col_file_ = false
bool cgx_loaded_ = false
bool scr_loaded_ = false
bool obj_loaded_ = false
bool tilemap_loaded_ = false
std::string file_path_ = ""
std::string col_file_path_ = ""
std::string col_file_name_ = ""
std::string cgx_file_path_ = ""
std::string cgx_file_name_ = ""
std::string scr_file_path_ = ""
std::string scr_file_name_ = ""
std::string obj_file_path_ = ""
std::string tilemap_file_path_ = ""
std::string tilemap_file_name_ = ""
gui::GfxSheetAssetBrowser asset_browser_
GfxEditMode gfx_edit_mode_ = GfxEditMode::kSelect
Rom temp_rom_
Rom tilemap_rom_
zelda3::Overworld overworld_ {&temp_rom_}
MemoryEditor cgx_memory_editor_
MemoryEditor col_memory_editor_
PaletteEditor palette_editor_
std::vector< uint8_t > import_data_
std::vector< uint8_t > graphics_buffer_
std::vector< uint8_t > decoded_cgx_
std::vector< uint8_t > cgx_data_
std::vector< uint8_t > extra_cgx_data_
std::vector< SDL_Color > decoded_col_
std::vector< uint8_t > scr_data_
std::vector< uint8_t > decoded_scr_data_
gfx::Bitmap cgx_bitmap_
gfx::Bitmap scr_bitmap_
gfx::Bitmap bin_bitmap_
gfx::Bitmap link_full_sheet_
std::array< gfx::Bitmap, kNumGfxSheets > gfx_sheets_
std::array< gfx::Bitmap, kNumLinkSheets > link_sheets_
gfx::PaletteGroup col_file_palette_group_
gfx::SnesPalette z3_rom_palette_
gfx::SnesPalette col_file_palette_
gfx::SnesPalette link_palette_
gui::Canvas import_canvas_
gui::Canvas scr_canvas_
gui::Canvas super_donkey_canvas_
gui::Canvas graphics_bin_canvas_
gui::Canvas current_sheet_canvas_
gui::Canvas link_canvas_
absl::Status status_
Rom * rom_
Additional Inherited Members
Protected Member Functions inherited from yaze::editor::Editor
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Detailed Description
Allows the user to edit graphics sheets from the game or view prototype graphics.
The GraphicsEditor class is responsible for providing functionality to edit graphics sheets from the game or view prototype graphics of Link to the Past from the CGX, SCR, and OBJ formats. It provides various methods to update different components of the graphics editor, such as the graphics edit tab, link graphics view, and prototype graphics viewer. It also includes import functions for different file formats, as well as other utility functions for drawing toolsets, palette controls, clipboard imports, experimental features, and memory editor.
Definition at line 57 of file graphics_editor.h.
Member Enumeration Documentation
GfxEditMode
enum class yaze::editor::GraphicsEditor::GfxEditMode strong private
Enumerator
kSelect
kPencil
kFill
Definition at line 81 of file graphics_editor.h.
Constructor & Destructor Documentation
GraphicsEditor()
yaze::editor::GraphicsEditor::GraphicsEditor (Rom * rom = nullptr) inline explicit
Definition at line 59 of file graphics_editor.h.
References yaze::editor::kGraphics, and yaze::editor::Editor::type_.
Member Function Documentation
Initialize()
void yaze::editor::GraphicsEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 45 of file graphics_editor.cc.
Load()
absl::Status yaze::editor::GraphicsEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 47 of file graphics_editor.cc.
Save()
absl::Status yaze::editor::GraphicsEditor::Save () inline override virtual
Implements yaze::editor::Editor.
Definition at line 65 of file graphics_editor.h.
Update()
absl::Status yaze::editor::GraphicsEditor::Update () override virtual
Implements yaze::editor::Editor.
Definition at line 49 of file graphics_editor.cc.
References asset_browser_, CLEAR_AND_RETURN_STATUS, yaze::gui::GfxSheetAssetBrowser::Draw(), yaze::gfx::Arena::Get(), yaze::gui::GfxSheetAssetBrowser::Initialize(), yaze::gui::GfxSheetAssetBrowser::Initialized, status_, UpdateGfxEdit(), UpdateLinkGfxView(), and UpdateScadView().
Cut()
absl::Status yaze::editor::GraphicsEditor::Cut () inline override virtual
Implements yaze::editor::Editor.
Definition at line 67 of file graphics_editor.h.
Copy()
absl::Status yaze::editor::GraphicsEditor::Copy () inline override virtual
Implements yaze::editor::Editor.
Definition at line 68 of file graphics_editor.h.
Paste()
absl::Status yaze::editor::GraphicsEditor::Paste () inline override virtual
Implements yaze::editor::Editor.
Definition at line 69 of file graphics_editor.h.
Undo()
absl::Status yaze::editor::GraphicsEditor::Undo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 70 of file graphics_editor.h.
Redo()
absl::Status yaze::editor::GraphicsEditor::Redo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 71 of file graphics_editor.h.
Find()
absl::Status yaze::editor::GraphicsEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 72 of file graphics_editor.h.
set_rom()
void yaze::editor::GraphicsEditor::set_rom (Rom * rom) inline
Definition at line 75 of file graphics_editor.h.
References rom(), and rom_.
rom()
Rom * yaze::editor::GraphicsEditor::rom () const inline
Definition at line 78 of file graphics_editor.h.
References rom_.
Referenced by DecompressImportData(), DecompressSuperDonkey(), DrawPaletteControls(), set_rom(), UpdateGfxEdit(), UpdateLinkGfxView(), and UpdatePaletteColumn().
UpdateGfxEdit()
absl::Status yaze::editor::GraphicsEditor::UpdateGfxEdit () private
Definition at line 67 of file graphics_editor.cc.
References DrawGfxEditToolset(), yaze::editor::kGfxEditTableFlags, rom(), status_, UpdateGfxSheetList(), UpdateGfxTabView(), and UpdatePaletteColumn().
Referenced by Update().
UpdateGfxSheetList()
absl::Status yaze::editor::GraphicsEditor::UpdateGfxSheetList () private
Todo:
Update the interaction for multi select on sheets
Definition at line 202 of file graphics_editor.cc.
References current_sheet_, yaze::gui::Canvas::draw_list(), yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::gfx::Arena::Get(), yaze::gfx::Arena::gfx_sheets(), graphics_bin_canvas_, yaze::kNumGfxSheets, open_sheets_, sheet_scale_, and yaze::gui::Canvas::zero_point().
Referenced by UpdateGfxEdit().
UpdateGfxTabView()
absl::Status yaze::editor::GraphicsEditor::UpdateGfxTabView () private
Definition at line 275 of file graphics_editor.cc.
References yaze::editor::Editor::active(), child_window_sheets_, current_color_, current_scale_, current_sheet_, current_sheet_canvas_, yaze::gui::Canvas::DrawTileOnBitmap(), yaze::core::Renderer::Get(), yaze::gfx::Arena::Get(), ICON_MD_ADD, yaze::gfx::Arena::mutable_gfx_sheets(), open_sheets_, yaze::gfx::Arena::ProcessBatchTextureUpdates(), yaze::gfx::Bitmap::QueueTextureUpdate(), release_queue_, yaze::core::Renderer::renderer(), tile_size_, and yaze::gui::Canvas::UpdateColorPainter().
Referenced by UpdateGfxEdit().
UpdatePaletteColumn()
absl::Status yaze::editor::GraphicsEditor::UpdatePaletteColumn () private
Definition at line 378 of file graphics_editor.cc.
References current_sheet_, edit_palette_group_name_index_, edit_palette_index_, edit_palette_sub_index_, yaze::core::Renderer::Get(), yaze::gfx::Arena::Get(), yaze::gui::InputHex(), yaze::gfx::kPaletteGroupAddressesKeys, yaze::gfx::Arena::mutable_gfx_sheets(), open_sheets_, yaze::Rom::palette_group(), refresh_graphics_, rom(), yaze::gui::SelectablePalettePipeline(), yaze::gui::TextWithSeparators(), and yaze::core::Renderer::UpdateBitmap().
Referenced by UpdateGfxEdit().
DrawGfxEditToolset()
void yaze::editor::GraphicsEditor::DrawGfxEditToolset () private
Draw the graphics editing toolset with enhanced ROM hacking features.
Enhanced Features:
Multi-tool selection for different editing modes
Real-time zoom controls for precise pixel editing
Sheet copy/paste operations for ROM graphics management
Color picker integration with SNES palette system
Tile size controls for 8x8 and 16x16 SNES tiles
Performance Notes:
Toolset updates are batched to minimize ImGui overhead
Color buttons use cached palette data for fast rendering
Zoom controls update canvas scaling without full redraw
Definition at line 112 of file graphics_editor.cc.
References current_color_, current_scale_, current_sheet_, yaze::gfx::Arena::Get(), gfx_edit_mode_, yaze::gfx::Arena::gfx_sheets(), HOVER_HINT, ICON_MD_CONTENT_COPY, ICON_MD_CONTENT_PASTE, ICON_MD_DRAW, ICON_MD_FORMAT_COLOR_FILL, ICON_MD_SELECT_ALL, ICON_MD_ZOOM_IN, ICON_MD_ZOOM_OUT, yaze::gui::InputHexByte(), kFill, kPencil, kSelect, status_, and tile_size_.
Referenced by UpdateGfxEdit().
UpdateLinkGfxView()
absl::Status yaze::editor::GraphicsEditor::UpdateLinkGfxView () private
Definition at line 407 of file graphics_editor.cc.
References ASSIGN_OR_RETURN, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), END_TAB_ITEM, yaze::editor::kGfxEditTableFlags, yaze::gfx::kTilesheetHeight, link_canvas_, link_sheets_, yaze::LoadLinkGraphics(), rom(), and TAB_ITEM.
Referenced by Update().
UpdateScadView()
absl::Status yaze::editor::GraphicsEditor::UpdateScadView () private
Todo:
Implement the Super Donkey 1 graphics decompression
Definition at line 455 of file graphics_editor.cc.
References BEGIN_TABLE, bin_bitmap_, yaze::gui::BitmapCanvasPipeline(), cgx_bitmap_, cgx_loaded_, col_file_, DrawCgxImport(), DrawClipboardImport(), DrawExperimentalFeatures(), DrawFileImport(), DrawMemoryEditor(), DrawPaletteControls(), DrawScrImport(), DrawToolset(), END_TAB_ITEM, END_TABLE, gfx_loaded_, import_canvas_, NEXT_COLUMN, open_memory_editor_, RETURN_IF_ERROR, scr_bitmap_, scr_canvas_, scr_loaded_, SETUP_COLUMN, status_, super_donkey_, TAB_ITEM, and TABLE_HEADERS.
Referenced by Update().
DrawCgxImport()
absl::Status yaze::editor::GraphicsEditor::DrawCgxImport () private
Definition at line 544 of file graphics_editor.cc.
References cgx_bitmap_, cgx_data_, cgx_file_name_, cgx_file_path_, cgx_loaded_, col_file_, yaze::gfx::Bitmap::Create(), current_bpp_, decoded_cgx_, decoded_col_, extra_cgx_data_, yaze::core::Renderer::Get(), is_open_, yaze::gfx::LoadCgx(), yaze::core::Renderer::RenderBitmap(), yaze::gfx::Bitmap::SetPalette(), yaze::util::FileDialogWrapper::ShowOpenFileDialog(), status_, and yaze::gui::TextWithSeparators().
Referenced by UpdateScadView().
DrawScrImport()
absl::Status yaze::editor::GraphicsEditor::DrawScrImport () private
Definition at line 577 of file graphics_editor.cc.
References yaze::gfx::Bitmap::Create(), current_bpp_, decoded_cgx_, decoded_col_, decoded_scr_data_, yaze::gfx::DrawScrWithCgx(), yaze::core::Renderer::Get(), is_open_, yaze::gfx::LoadScr(), yaze::core::Renderer::RenderBitmap(), scr_bitmap_, scr_data_, scr_file_name_, scr_file_path_, scr_loaded_, scr_mod_value_, yaze::gfx::Bitmap::SetPalette(), yaze::util::FileDialogWrapper::ShowOpenFileDialog(), and status_.
Referenced by UpdateScadView().
DrawFileImport()
absl::Status yaze::editor::GraphicsEditor::DrawFileImport () private
Definition at line 696 of file graphics_editor.cc.
References bin_size_, current_offset_, DecompressImportData(), file_path_, HOVER_HINT, yaze::gui::InputHex(), is_open_, yaze::Rom::LoadFromFile(), RETURN_IF_ERROR, yaze::util::FileDialogWrapper::ShowOpenFileDialog(), status_, temp_rom_, and yaze::gui::TextWithSeparators().
Referenced by UpdateScadView().
DrawObjImport()
absl::Status yaze::editor::GraphicsEditor::DrawObjImport () private
Definition at line 655 of file graphics_editor.cc.
References HOVER_HINT, is_open_, yaze::Rom::LoadFromFile(), obj_file_path_, obj_loaded_, yaze::util::FileDialogWrapper::ShowOpenFileDialog(), status_, temp_rom_, and yaze::gui::TextWithSeparators().
DrawTilemapImport()
absl::Status yaze::editor::GraphicsEditor::DrawTilemapImport () private
Definition at line 673 of file graphics_editor.cc.
References yaze::Rom::data(), yaze::gfx::lc_lz2::DecompressV2(), HOVER_HINT, is_open_, yaze::gfx::lc_lz2::kNintendoMode1, yaze::Rom::LoadFromFile(), yaze::util::FileDialogWrapper::ShowOpenFileDialog(), status_, yaze::gui::TextWithSeparators(), tilemap_file_path_, tilemap_loaded_, and tilemap_rom_.
DrawToolset()
absl::Status yaze::editor::GraphicsEditor::DrawToolset () private
Definition at line 520 of file graphics_editor.cc.
References ICON_MD_MEMORY, and open_memory_editor_.
Referenced by UpdateScadView().
DrawPaletteControls()
absl::Status yaze::editor::GraphicsEditor::DrawPaletteControls () private
Definition at line 607 of file graphics_editor.cc.
References yaze::gfx::PaletteGroup::clear(), col_file_, col_file_name_, col_file_palette_, col_file_palette_group_, col_file_path_, yaze::gfx::CreatePaletteGroupFromColFile(), current_palette_, current_palette_index_, yaze::gfx::DecodeColFile(), decoded_col_, yaze::gfx::GetColFileData(), HOVER_HINT, yaze::gui::InputHex(), is_open_, yaze::gfx::kPaletteGroupAddressesKeys, yaze::Rom::LoadFromFile(), yaze::Rom::mutable_data(), refresh_graphics_, rom(), yaze::gui::SelectablePalettePipeline(), yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::gfx::SnesPalette::size(), yaze::gfx::PaletteGroup::size(), status_, temp_rom_, and yaze::gui::TextWithSeparators().
Referenced by UpdateScadView().
DrawClipboardImport()
absl::Status yaze::editor::GraphicsEditor::DrawClipboardImport () private
Definition at line 728 of file graphics_editor.cc.
References clipboard_offset_, clipboard_size_, DecompressImportData(), yaze::gui::InputHex(), yaze::Rom::is_loaded(), is_open_, yaze::Rom::LoadFromData(), num_sheets_to_load_, open_memory_editor_, status_, temp_rom_, and yaze::gui::TextWithSeparators().
Referenced by UpdateScadView().
DrawExperimentalFeatures()
absl::Status yaze::editor::GraphicsEditor::DrawExperimentalFeatures () private
Definition at line 758 of file graphics_editor.cc.
References DecompressSuperDonkey(), file_path_, RETURN_IF_ERROR, and yaze::gui::TextWithSeparators().
Referenced by UpdateScadView().
DrawMemoryEditor()
absl::Status yaze::editor::GraphicsEditor::DrawMemoryEditor () private
Definition at line 774 of file graphics_editor.cc.
References is_open_, yaze::Rom::mutable_data(), yaze::Rom::size(), and temp_rom_.
Referenced by UpdateScadView().
DecompressImportData()
absl::Status yaze::editor::GraphicsEditor::DecompressImportData (int size) private
Definition at line 784 of file graphics_editor.cc.
References ASSIGN_OR_RETURN, bin_bitmap_, col_file_, col_file_palette_, yaze::gfx::Bitmap::Create(), current_offset_, current_palette_, yaze::Rom::data(), yaze::gfx::lc_lz2::DecompressV2(), yaze::core::Renderer::Get(), gfx_loaded_, import_data_, yaze::gfx::kTilesheetDepth, yaze::gfx::kTilesheetWidth, yaze::Rom::palette_group(), yaze::core::Renderer::RenderBitmap(), rom(), yaze::gfx::Bitmap::SetPalette(), yaze::gfx::SnesTo8bppSheet(), temp_rom_, and z3_rom_palette_.
Referenced by DrawClipboardImport(), and DrawFileImport().
DecompressSuperDonkey()
absl::Status yaze::editor::GraphicsEditor::DecompressSuperDonkey () private
Definition at line 808 of file graphics_editor.cc.
References ASSIGN_OR_RETURN, col_file_, col_file_palette_group_, current_palette_, current_palette_index_, yaze::Rom::data(), yaze::gfx::lc_lz2::DecompressV2(), yaze::core::Renderer::Get(), gfx_sheets_, yaze::gfx::kPaletteGroupAddressesKeys, yaze::editor::kSuperDonkeySprites, yaze::editor::kSuperDonkeyTiles, yaze::gfx::kTilesheetDepth, yaze::gfx::kTilesheetHeight, yaze::gfx::kTilesheetWidth, num_sheets_to_load_, yaze::Rom::palette_group(), yaze::core::Renderer::RenderBitmap(), rom(), yaze::gfx::SnesTo8bppSheet(), super_donkey_, temp_rom_, and z3_rom_palette_.
Referenced by DrawExperimentalFeatures().
Member Data Documentation
current_color_
ImVec4 yaze::editor::GraphicsEditor::current_color_ private
Definition at line 118 of file graphics_editor.h.
Referenced by DrawGfxEditToolset(), and UpdateGfxTabView().
current_sheet_
uint16_t yaze::editor::GraphicsEditor::current_sheet_ = 0 private
Definition at line 119 of file graphics_editor.h.
Referenced by DrawGfxEditToolset(), UpdateGfxSheetList(), UpdateGfxTabView(), and UpdatePaletteColumn().
tile_size_
uint8_t yaze::editor::GraphicsEditor::tile_size_ = 0x01 private
Definition at line 120 of file graphics_editor.h.
Referenced by DrawGfxEditToolset(), and UpdateGfxTabView().
open_sheets_
std::set<uint16_t> yaze::editor::GraphicsEditor::open_sheets_ private
Definition at line 121 of file graphics_editor.h.
Referenced by UpdateGfxSheetList(), UpdateGfxTabView(), and UpdatePaletteColumn().
child_window_sheets_
std::set<uint16_t> yaze::editor::GraphicsEditor::child_window_sheets_ private
Definition at line 122 of file graphics_editor.h.
Referenced by UpdateGfxTabView().
release_queue_
std::stack<uint16_t> yaze::editor::GraphicsEditor::release_queue_ private
Definition at line 123 of file graphics_editor.h.
Referenced by UpdateGfxTabView().
edit_palette_group_name_index_
uint64_t yaze::editor::GraphicsEditor::edit_palette_group_name_index_ = 0 private
Definition at line 124 of file graphics_editor.h.
Referenced by UpdatePaletteColumn().
edit_palette_group_index_
uint64_t yaze::editor::GraphicsEditor::edit_palette_group_index_ = 0 private
Definition at line 125 of file graphics_editor.h.
edit_palette_index_
uint64_t yaze::editor::GraphicsEditor::edit_palette_index_ = 0 private
Definition at line 126 of file graphics_editor.h.
Referenced by UpdatePaletteColumn().
edit_palette_sub_index_
uint64_t yaze::editor::GraphicsEditor::edit_palette_sub_index_ = 0 private
Definition at line 127 of file graphics_editor.h.
Referenced by UpdatePaletteColumn().
sheet_scale_
float yaze::editor::GraphicsEditor::sheet_scale_ = 2.0f private
Definition at line 128 of file graphics_editor.h.
Referenced by UpdateGfxSheetList().
current_scale_
float yaze::editor::GraphicsEditor::current_scale_ = 4.0f private
Definition at line 129 of file graphics_editor.h.
Referenced by DrawGfxEditToolset(), and UpdateGfxTabView().
current_palette_
int yaze::editor::GraphicsEditor::current_palette_ = 0 private
Definition at line 132 of file graphics_editor.h.
Referenced by DecompressImportData(), DecompressSuperDonkey(), and DrawPaletteControls().
current_offset_
uint64_t yaze::editor::GraphicsEditor::current_offset_ = 0 private
Definition at line 133 of file graphics_editor.h.
Referenced by DecompressImportData(), and DrawFileImport().
current_size_
uint64_t yaze::editor::GraphicsEditor::current_size_ = 0 private
Definition at line 134 of file graphics_editor.h.
current_palette_index_
uint64_t yaze::editor::GraphicsEditor::current_palette_index_ = 0 private
Definition at line 135 of file graphics_editor.h.
Referenced by DecompressSuperDonkey(), and DrawPaletteControls().
current_bpp_
int yaze::editor::GraphicsEditor::current_bpp_ = 0 private
Definition at line 136 of file graphics_editor.h.
Referenced by DrawCgxImport(), and DrawScrImport().
scr_mod_value_
int yaze::editor::GraphicsEditor::scr_mod_value_ = 0 private
Definition at line 137 of file graphics_editor.h.
Referenced by DrawScrImport().
num_sheets_to_load_
uint64_t yaze::editor::GraphicsEditor::num_sheets_to_load_ = 1 private
Definition at line 139 of file graphics_editor.h.
Referenced by DecompressSuperDonkey(), and DrawClipboardImport().
bin_size_
uint64_t yaze::editor::GraphicsEditor::bin_size_ = 0 private
Definition at line 140 of file graphics_editor.h.
Referenced by DrawFileImport().
clipboard_offset_
uint64_t yaze::editor::GraphicsEditor::clipboard_offset_ = 0 private
Definition at line 141 of file graphics_editor.h.
Referenced by DrawClipboardImport().
clipboard_size_
uint64_t yaze::editor::GraphicsEditor::clipboard_size_ = 0 private
Definition at line 142 of file graphics_editor.h.
Referenced by DrawClipboardImport().
refresh_graphics_
bool yaze::editor::GraphicsEditor::refresh_graphics_ = false private
Definition at line 144 of file graphics_editor.h.
Referenced by DrawPaletteControls(), and UpdatePaletteColumn().
open_memory_editor_
bool yaze::editor::GraphicsEditor::open_memory_editor_ = false private
Definition at line 145 of file graphics_editor.h.
Referenced by DrawClipboardImport(), DrawToolset(), and UpdateScadView().
gfx_loaded_
bool yaze::editor::GraphicsEditor::gfx_loaded_ = false private
Definition at line 146 of file graphics_editor.h.
Referenced by DecompressImportData(), and UpdateScadView().
is_open_
bool yaze::editor::GraphicsEditor::is_open_ = false private
Definition at line 147 of file graphics_editor.h.
Referenced by DrawCgxImport(), DrawClipboardImport(), DrawFileImport(), DrawMemoryEditor(), DrawObjImport(), DrawPaletteControls(), DrawScrImport(), and DrawTilemapImport().
super_donkey_
bool yaze::editor::GraphicsEditor::super_donkey_ = false private
Definition at line 148 of file graphics_editor.h.
Referenced by DecompressSuperDonkey(), and UpdateScadView().
col_file_
bool yaze::editor::GraphicsEditor::col_file_ = false private
Definition at line 149 of file graphics_editor.h.
Referenced by DecompressImportData(), DecompressSuperDonkey(), DrawCgxImport(), DrawPaletteControls(), and UpdateScadView().
cgx_loaded_
bool yaze::editor::GraphicsEditor::cgx_loaded_ = false private
Definition at line 150 of file graphics_editor.h.
Referenced by DrawCgxImport(), and UpdateScadView().
scr_loaded_
bool yaze::editor::GraphicsEditor::scr_loaded_ = false private
Definition at line 151 of file graphics_editor.h.
Referenced by DrawScrImport(), and UpdateScadView().
obj_loaded_
bool yaze::editor::GraphicsEditor::obj_loaded_ = false private
Definition at line 152 of file graphics_editor.h.
Referenced by DrawObjImport().
tilemap_loaded_
bool yaze::editor::GraphicsEditor::tilemap_loaded_ = false private
Definition at line 153 of file graphics_editor.h.
Referenced by DrawTilemapImport().
file_path_
std::string yaze::editor::GraphicsEditor::file_path_ = "" private
Definition at line 155 of file graphics_editor.h.
Referenced by DrawExperimentalFeatures(), and DrawFileImport().
col_file_path_
std::string yaze::editor::GraphicsEditor::col_file_path_ = "" private
Definition at line 156 of file graphics_editor.h.
Referenced by DrawPaletteControls().
col_file_name_
std::string yaze::editor::GraphicsEditor::col_file_name_ = "" private
Definition at line 157 of file graphics_editor.h.
Referenced by DrawPaletteControls().
cgx_file_path_
std::string yaze::editor::GraphicsEditor::cgx_file_path_ = "" private
Definition at line 158 of file graphics_editor.h.
Referenced by DrawCgxImport().
cgx_file_name_
std::string yaze::editor::GraphicsEditor::cgx_file_name_ = "" private
Definition at line 159 of file graphics_editor.h.
Referenced by DrawCgxImport().
scr_file_path_
std::string yaze::editor::GraphicsEditor::scr_file_path_ = "" private
Definition at line 160 of file graphics_editor.h.
Referenced by DrawScrImport().
scr_file_name_
std::string yaze::editor::GraphicsEditor::scr_file_name_ = "" private
Definition at line 161 of file graphics_editor.h.
Referenced by DrawScrImport().
obj_file_path_
std::string yaze::editor::GraphicsEditor::obj_file_path_ = "" private
Definition at line 162 of file graphics_editor.h.
Referenced by DrawObjImport().
tilemap_file_path_
std::string yaze::editor::GraphicsEditor::tilemap_file_path_ = "" private
Definition at line 163 of file graphics_editor.h.
Referenced by DrawTilemapImport().
tilemap_file_name_
std::string yaze::editor::GraphicsEditor::tilemap_file_name_ = "" private
Definition at line 164 of file graphics_editor.h.
asset_browser_
gui::GfxSheetAssetBrowser yaze::editor::GraphicsEditor::asset_browser_ private
Definition at line 166 of file graphics_editor.h.
Referenced by Update().
gfx_edit_mode_
GfxEditMode yaze::editor::GraphicsEditor::gfx_edit_mode_ = GfxEditMode::kSelect private
Definition at line 168 of file graphics_editor.h.
Referenced by DrawGfxEditToolset().
temp_rom_
Rom yaze::editor::GraphicsEditor::temp_rom_ private
Definition at line 170 of file graphics_editor.h.
Referenced by DecompressImportData(), DecompressSuperDonkey(), DrawClipboardImport(), DrawFileImport(), DrawMemoryEditor(), DrawObjImport(), and DrawPaletteControls().
tilemap_rom_
Rom yaze::editor::GraphicsEditor::tilemap_rom_ private
Definition at line 171 of file graphics_editor.h.
Referenced by DrawTilemapImport().
overworld_
zelda3::Overworld yaze::editor::GraphicsEditor::overworld_ {&temp_rom_} private
Definition at line 172 of file graphics_editor.h.
cgx_memory_editor_
MemoryEditor yaze::editor::GraphicsEditor::cgx_memory_editor_ private
Definition at line 173 of file graphics_editor.h.
col_memory_editor_
MemoryEditor yaze::editor::GraphicsEditor::col_memory_editor_ private
Definition at line 174 of file graphics_editor.h.
palette_editor_
PaletteEditor yaze::editor::GraphicsEditor::palette_editor_ private
Definition at line 175 of file graphics_editor.h.
import_data_
std::vector<uint8_t> yaze::editor::GraphicsEditor::import_data_ private
Definition at line 176 of file graphics_editor.h.
Referenced by DecompressImportData().
graphics_buffer_
std::vector<uint8_t> yaze::editor::GraphicsEditor::graphics_buffer_ private
Definition at line 177 of file graphics_editor.h.
decoded_cgx_
std::vector<uint8_t> yaze::editor::GraphicsEditor::decoded_cgx_ private
Definition at line 178 of file graphics_editor.h.
Referenced by DrawCgxImport(), and DrawScrImport().
cgx_data_
std::vector<uint8_t> yaze::editor::GraphicsEditor::cgx_data_ private
Definition at line 179 of file graphics_editor.h.
Referenced by DrawCgxImport().
extra_cgx_data_
std::vector<uint8_t> yaze::editor::GraphicsEditor::extra_cgx_data_ private
Definition at line 180 of file graphics_editor.h.
Referenced by DrawCgxImport().
decoded_col_
std::vector<SDL_Color> yaze::editor::GraphicsEditor::decoded_col_ private
Definition at line 181 of file graphics_editor.h.
Referenced by DrawCgxImport(), DrawPaletteControls(), and DrawScrImport().
scr_data_
std::vector<uint8_t> yaze::editor::GraphicsEditor::scr_data_ private
Definition at line 182 of file graphics_editor.h.
Referenced by DrawScrImport().
decoded_scr_data_
std::vector<uint8_t> yaze::editor::GraphicsEditor::decoded_scr_data_ private
Definition at line 183 of file graphics_editor.h.
Referenced by DrawScrImport().
cgx_bitmap_
gfx::Bitmap yaze::editor::GraphicsEditor::cgx_bitmap_ private
Definition at line 184 of file graphics_editor.h.
Referenced by DrawCgxImport(), and UpdateScadView().
scr_bitmap_
gfx::Bitmap yaze::editor::GraphicsEditor::scr_bitmap_ private
Definition at line 185 of file graphics_editor.h.
Referenced by DrawScrImport(), and UpdateScadView().
bin_bitmap_
gfx::Bitmap yaze::editor::GraphicsEditor::bin_bitmap_ private
Definition at line 186 of file graphics_editor.h.
Referenced by DecompressImportData(), and UpdateScadView().
link_full_sheet_
gfx::Bitmap yaze::editor::GraphicsEditor::link_full_sheet_ private
Definition at line 187 of file graphics_editor.h.
gfx_sheets_
std::array<gfx::Bitmap, kNumGfxSheets> yaze::editor::GraphicsEditor::gfx_sheets_ private
Definition at line 188 of file graphics_editor.h.
Referenced by DecompressSuperDonkey().
link_sheets_
std::array<gfx::Bitmap, kNumLinkSheets> yaze::editor::GraphicsEditor::link_sheets_ private
Definition at line 189 of file graphics_editor.h.
Referenced by UpdateLinkGfxView().
col_file_palette_group_
gfx::PaletteGroup yaze::editor::GraphicsEditor::col_file_palette_group_ private
Definition at line 191 of file graphics_editor.h.
Referenced by DecompressSuperDonkey(), and DrawPaletteControls().
z3_rom_palette_
gfx::SnesPalette yaze::editor::GraphicsEditor::z3_rom_palette_ private
Definition at line 192 of file graphics_editor.h.
Referenced by DecompressImportData(), and DecompressSuperDonkey().
col_file_palette_
gfx::SnesPalette yaze::editor::GraphicsEditor::col_file_palette_ private
Definition at line 193 of file graphics_editor.h.
Referenced by DecompressImportData(), and DrawPaletteControls().
link_palette_
gfx::SnesPalette yaze::editor::GraphicsEditor::link_palette_ private
Definition at line 194 of file graphics_editor.h.
import_canvas_
gui::Canvas yaze::editor::GraphicsEditor::import_canvas_ private
Definition at line 195 of file graphics_editor.h.
Referenced by UpdateScadView().
scr_canvas_
gui::Canvas yaze::editor::GraphicsEditor::scr_canvas_ private
Definition at line 196 of file graphics_editor.h.
Referenced by UpdateScadView().
super_donkey_canvas_
gui::Canvas yaze::editor::GraphicsEditor::super_donkey_canvas_ private
Definition at line 197 of file graphics_editor.h.
graphics_bin_canvas_
gui::Canvas yaze::editor::GraphicsEditor::graphics_bin_canvas_ private
Definition at line 198 of file graphics_editor.h.
Referenced by UpdateGfxSheetList().
current_sheet_canvas_
gui::Canvas yaze::editor::GraphicsEditor::current_sheet_canvas_ private
Initial value:
{"CurrentSheetCanvas", ImVec2(0x80, 0x20),
                                    gui::CanvasGridSize::k8x8}
Definition at line 199 of file graphics_editor.h.
Referenced by UpdateGfxTabView().
link_canvas_
gui::Canvas yaze::editor::GraphicsEditor::link_canvas_ private
Initial value:
{
      "LinkCanvas",
      ImVec2(gfx::kTilesheetWidth * 4, gfx::kTilesheetHeight * 0x10 * 4),
      gui::CanvasGridSize::k16x16}
Definition at line 201 of file graphics_editor.h.
Referenced by UpdateLinkGfxView().
status_
absl::Status yaze::editor::GraphicsEditor::status_ private
Definition at line 205 of file graphics_editor.h.
Referenced by DrawCgxImport(), DrawClipboardImport(), DrawFileImport(), DrawGfxEditToolset(), DrawObjImport(), DrawPaletteControls(), DrawScrImport(), DrawTilemapImport(), Update(), UpdateGfxEdit(), and UpdateScadView().
rom_
Rom* yaze::editor::GraphicsEditor::rom_ private
Definition at line 207 of file graphics_editor.h.
Referenced by rom(), and set_rom().
The documentation for this class was generated from the following files:
src/app/editor/graphics/graphics_editor.h
src/app/editor/graphics/graphics_editor.cc