yaze: yaze::test::ZSCustomOverworldTestSuite Class Reference
yaze::test::ZSCustomOverworldTestSuite Class Reference
ZSCustomOverworld upgrade testing suite.
#include <zscustomoverworld_test_suite.h>
Public Member Functions
ZSCustomOverworldTestSuite ()=default
~ZSCustomOverworldTestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Private Member Functions
void InitializeVersionData ()
void AddSkippedTest (TestResults &results, const std::string &test_name, const std::string &reason)
absl::Status ApplyVersionPatch (Rom &rom, const std::string &version)
bool ValidateVersionAddresses (Rom &rom, const std::string &version)
void RunVanillaBaselineTest (TestResults &results, Rom *rom)
void RunV2UpgradeTest (TestResults &results, Rom *rom)
void RunV3UpgradeTest (TestResults &results, Rom *rom)
void RunAddressValidationTest (TestResults &results, Rom *rom)
void RunFeatureToggleTest (TestResults &results, Rom *rom)
void RunDataIntegrityTest (TestResults &results, Rom *rom)
Private Attributes
bool test_vanilla_baseline_ = true
bool test_v2_upgrade_ = true
bool test_v3_upgrade_ = true
bool test_address_validation_ = true
bool test_feature_toggle_ = true
bool test_data_integrity_ = true
std::map< std::string, std::pair< uint32_t, uint8_t > > vanilla_data_
std::map< std::string, std::pair< uint32_t, uint8_t > > v2_data_
std::map< std::string, std::pair< uint32_t, uint8_t > > v3_data_
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
ZSCustomOverworld upgrade testing suite.
This test suite validates ZSCustomOverworld version upgrades:
Vanilla -> v2 -> v3 upgrade path testing
Address validation for each version
Feature enablement/disablement testing
Data integrity validation during upgrades
Save compatibility between versions
Definition at line 25 of file zscustomoverworld_test_suite.h.
Constructor & Destructor Documentation
ZSCustomOverworldTestSuite()
yaze::test::ZSCustomOverworldTestSuite::ZSCustomOverworldTestSuite () default
~ZSCustomOverworldTestSuite()
yaze::test::ZSCustomOverworldTestSuite::~ZSCustomOverworldTestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::ZSCustomOverworldTestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 30 of file zscustomoverworld_test_suite.h.
Referenced by AddSkippedTest(), RunAddressValidationTest(), RunDataIntegrityTest(), RunFeatureToggleTest(), RunV2UpgradeTest(), RunV3UpgradeTest(), and RunVanillaBaselineTest().
GetCategory()
TestCategory yaze::test::ZSCustomOverworldTestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 31 of file zscustomoverworld_test_suite.h.
References yaze::test::kIntegration.
Referenced by AddSkippedTest(), RunAddressValidationTest(), RunDataIntegrityTest(), RunFeatureToggleTest(), RunV2UpgradeTest(), RunV3UpgradeTest(), and RunVanillaBaselineTest().
RunTests()
absl::Status yaze::test::ZSCustomOverworldTestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 33 of file zscustomoverworld_test_suite.h.
References AddSkippedTest(), yaze::test::TestManager::Get(), yaze::test::TestManager::GetCurrentRom(), InitializeVersionData(), yaze::Rom::is_loaded(), RunAddressValidationTest(), RunDataIntegrityTest(), RunFeatureToggleTest(), RunV2UpgradeTest(), RunV3UpgradeTest(), RunVanillaBaselineTest(), test_address_validation_, test_data_integrity_, test_feature_toggle_, test_v2_upgrade_, test_v3_upgrade_, and test_vanilla_baseline_.
DrawConfiguration()
void yaze::test::ZSCustomOverworldTestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 73 of file zscustomoverworld_test_suite.h.
References yaze::test::TestManager::Get(), yaze::test::TestManager::GetCurrentRom(), ICON_MD_CHECK_CIRCLE, ICON_MD_UPGRADE, ICON_MD_WARNING, yaze::Rom::is_loaded(), yaze::Rom::ReadByte(), test_address_validation_, test_data_integrity_, test_feature_toggle_, test_v2_upgrade_, test_v3_upgrade_, test_vanilla_baseline_, and yaze::Rom::title().
InitializeVersionData()
void yaze::test::ZSCustomOverworldTestSuite::InitializeVersionData () inline private
Definition at line 115 of file zscustomoverworld_test_suite.h.
References v2_data_, v3_data_, and vanilla_data_.
Referenced by RunTests().
AddSkippedTest()
void yaze::test::ZSCustomOverworldTestSuite::AddSkippedTest (TestResults & results, const std::string & test_name, const std::string & reason) inline private
Definition at line 147 of file zscustomoverworld_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kSkipped, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
ApplyVersionPatch()
absl::Status yaze::test::ZSCustomOverworldTestSuite::ApplyVersionPatch (Rom & rom, const std::string & version) inline private
Definition at line 159 of file zscustomoverworld_test_suite.h.
References RETURN_IF_ERROR, v2_data_, v3_data_, vanilla_data_, and yaze::Rom::WriteByte().
Referenced by RunAddressValidationTest(), RunDataIntegrityTest(), RunFeatureToggleTest(), RunV2UpgradeTest(), and RunV3UpgradeTest().
ValidateVersionAddresses()
bool yaze::test::ZSCustomOverworldTestSuite::ValidateVersionAddresses (Rom & rom, const std::string & version) inline private
Definition at line 189 of file zscustomoverworld_test_suite.h.
References yaze::Rom::ReadByte(), v2_data_, v3_data_, and vanilla_data_.
Referenced by RunAddressValidationTest(), RunV2UpgradeTest(), RunV3UpgradeTest(), and RunVanillaBaselineTest().
RunVanillaBaselineTest()
void yaze::test::ZSCustomOverworldTestSuite::RunVanillaBaselineTest (TestResults & results, Rom * rom) inline private
Definition at line 207 of file zscustomoverworld_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and ValidateVersionAddresses().
Referenced by RunTests().
RunV2UpgradeTest()
void yaze::test::ZSCustomOverworldTestSuite::RunV2UpgradeTest (TestResults & results, Rom * rom) inline private
Definition at line 259 of file zscustomoverworld_test_suite.h.
References yaze::test::TestResults::AddResult(), ApplyVersionPatch(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and ValidateVersionAddresses().
Referenced by RunTests().
RunV3UpgradeTest()
void yaze::test::ZSCustomOverworldTestSuite::RunV3UpgradeTest (TestResults & results, Rom * rom) inline private
Definition at line 314 of file zscustomoverworld_test_suite.h.
References yaze::test::TestResults::AddResult(), ApplyVersionPatch(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and ValidateVersionAddresses().
Referenced by RunTests().
RunAddressValidationTest()
void yaze::test::ZSCustomOverworldTestSuite::RunAddressValidationTest (TestResults & results, Rom * rom) inline private
Definition at line 369 of file zscustomoverworld_test_suite.h.
References yaze::test::TestResults::AddResult(), ApplyVersionPatch(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and ValidateVersionAddresses().
Referenced by RunTests().
RunFeatureToggleTest()
void yaze::test::ZSCustomOverworldTestSuite::RunFeatureToggleTest (TestResults & results, Rom * rom) inline private
Definition at line 422 of file zscustomoverworld_test_suite.h.
References yaze::test::TestResults::AddResult(), ApplyVersionPatch(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and yaze::Rom::WriteByte().
Referenced by RunTests().
RunDataIntegrityTest()
void yaze::test::ZSCustomOverworldTestSuite::RunDataIntegrityTest (TestResults & results, Rom * rom) inline private
Definition at line 495 of file zscustomoverworld_test_suite.h.
References yaze::test::TestResults::AddResult(), ApplyVersionPatch(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
Member Data Documentation
test_vanilla_baseline_
bool yaze::test::ZSCustomOverworldTestSuite::test_vanilla_baseline_ = true private
Definition at line 575 of file zscustomoverworld_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_v2_upgrade_
bool yaze::test::ZSCustomOverworldTestSuite::test_v2_upgrade_ = true private
Definition at line 576 of file zscustomoverworld_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_v3_upgrade_
bool yaze::test::ZSCustomOverworldTestSuite::test_v3_upgrade_ = true private
Definition at line 577 of file zscustomoverworld_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_address_validation_
bool yaze::test::ZSCustomOverworldTestSuite::test_address_validation_ = true private
Definition at line 578 of file zscustomoverworld_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_feature_toggle_
bool yaze::test::ZSCustomOverworldTestSuite::test_feature_toggle_ = true private
Definition at line 579 of file zscustomoverworld_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_data_integrity_
bool yaze::test::ZSCustomOverworldTestSuite::test_data_integrity_ = true private
Definition at line 580 of file zscustomoverworld_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
vanilla_data_
std::map<std::string, std::pair<uint32_t, uint8_t> > yaze::test::ZSCustomOverworldTestSuite::vanilla_data_ private
Definition at line 583 of file zscustomoverworld_test_suite.h.
Referenced by ApplyVersionPatch(), InitializeVersionData(), and ValidateVersionAddresses().
v2_data_
std::map<std::string, std::pair<uint32_t, uint8_t> > yaze::test::ZSCustomOverworldTestSuite::v2_data_ private
Definition at line 584 of file zscustomoverworld_test_suite.h.
Referenced by ApplyVersionPatch(), InitializeVersionData(), and ValidateVersionAddresses().
v3_data_
std::map<std::string, std::pair<uint32_t, uint8_t> > yaze::test::ZSCustomOverworldTestSuite::v3_data_ private
Definition at line 585 of file zscustomoverworld_test_suite.h.
Referenced by ApplyVersionPatch(), InitializeVersionData(), and ValidateVersionAddresses().
The documentation for this class was generated from the following file:
src/app/test/zscustomoverworld_test_suite.h