yaze: yaze::util::PlatformPaths Class Reference
yaze::util::PlatformPaths Class Reference
Cross-platform utilities for file system paths.
#include <platform_paths.h>
Static Public Member Functions
static std::filesystem::path GetHomeDirectory ()
Get the user's home directory in a cross-platform way.
static absl::StatusOr< std::filesystem::path > GetAppDataDirectory ()
Get application data directory for YAZE.
static absl::StatusOr< std::filesystem::path > GetAppDataSubdirectory (const std::string &subdir)
Get a subdirectory within the app data folder.
static absl::Status EnsureDirectoryExists (const std::filesystem::path &path)
Ensure a directory exists, creating it if necessary.
static bool Exists (const std::filesystem::path &path)
Check if a file or directory exists.
static absl::StatusOr< std::filesystem::path > GetTempDirectory ()
Get a temporary directory for the application.
static std::string NormalizePathForDisplay (const std::filesystem::path &path)
Normalize path separators for display.
static std::string ToNativePath (const std::filesystem::path &path)
Convert path to native format.
Detailed Description
Cross-platform utilities for file system paths.
Provides consistent, platform-independent file and directory operations that work correctly on Windows (MSVC), macOS, and Linux.
Definition at line 18 of file platform_paths.h.
Member Function Documentation
GetHomeDirectory()
std::filesystem::path yaze::util::PlatformPaths::GetHomeDirectory () static
Get the user's home directory in a cross-platform way.
Windows: Uses USERPROFILE environment variable
Unix/macOS: Uses HOME environment variable
Fallback: Returns current directory
Returns
Path to user's home directory, or "." if not available
Definition at line 19 of file platform_paths.cc.
Referenced by GetAppDataDirectory().
GetAppDataDirectory()
absl::StatusOr< std::filesystem::path > yaze::util::PlatformPaths::GetAppDataDirectory () static
Get application data directory for YAZE.
Creates the directory if it doesn't exist.
Windows: USERPROFILE%.yaze
Unix/macOS: $HOME/.yaze
Returns
StatusOr with path to data directory
Definition at line 54 of file platform_paths.cc.
References EnsureDirectoryExists(), and GetHomeDirectory().
Referenced by GetAppDataSubdirectory().
GetAppDataSubdirectory()
absl::StatusOr< std::filesystem::path > yaze::util::PlatformPaths::GetAppDataSubdirectory (const std::string & subdir) static
Get a subdirectory within the app data folder.
Creates the directory if it doesn't exist.
Parameters
subdir Subdirectory name (e.g., "agent", "cache", "logs")
Returns
StatusOr with path to subdirectory
Definition at line 66 of file platform_paths.cc.
References EnsureDirectoryExists(), and GetAppDataDirectory().
Referenced by yaze::cli::agent::LearnedKnowledgeService::LearnedKnowledgeService(), and yaze::cli::agent::TodoManager::TodoManager().
EnsureDirectoryExists()
absl::Status yaze::util::PlatformPaths::EnsureDirectoryExists (const std::filesystem::path & path) static
Ensure a directory exists, creating it if necessary.
Uses std::filesystem::create_directories which works cross-platform.
Parameters
path Directory path to create
Returns
OK if directory exists or was created successfully
Definition at line 83 of file platform_paths.cc.
References Exists().
Referenced by GetAppDataDirectory(), GetAppDataSubdirectory(), GetTempDirectory(), yaze::cli::agent::LearnedKnowledgeService::Initialize(), and yaze::cli::agent::TodoManager::Initialize().
Exists()
bool yaze::util::PlatformPaths::Exists (const std::filesystem::path & path) static
Check if a file or directory exists.
Parameters
path Path to check
Returns
true if exists, false otherwise
Definition at line 101 of file platform_paths.cc.
Referenced by EnsureDirectoryExists(), yaze::cli::agent::anonymous_namespace{learned_knowledge_service.cc}::FileExists(), and yaze::cli::agent::TodoManager::Initialize().
GetTempDirectory()
absl::StatusOr< std::filesystem::path > yaze::util::PlatformPaths::GetTempDirectory () static
Get a temporary directory for the application.
Windows: TEMP%\yaze
Unix: /tmp/yaze or $TMPDIR/yaze
Returns
StatusOr with path to temp directory
Definition at line 107 of file platform_paths.cc.
References EnsureDirectoryExists().
NormalizePathForDisplay()
std::string yaze::util::PlatformPaths::NormalizePathForDisplay (const std::filesystem::path & path) static
Normalize path separators for display.
Converts all path separators to forward slashes for consistent output in logs and UI (forward slashes work on all platforms).
Parameters
path Path to normalize
Returns
Normalized path string
Definition at line 126 of file platform_paths.cc.
ToNativePath()
std::string yaze::util::PlatformPaths::ToNativePath (const std::filesystem::path & path) static
Convert path to native format.
Ensures path uses the correct separator for the current platform.
Parameters
path Path to convert
Returns
Native path string
Definition at line 134 of file platform_paths.cc.
The documentation for this class was generated from the following files:
src/util/platform_paths.h
src/util/platform_paths.cc