yaze: anonymous_namespace{agent_chat_widget.cc} Namespace Reference
anonymous_namespace{agent_chat_widget.cc} Namespace Reference
Functions
std::filesystem::path ExpandUserPath (std::string path)
std::filesystem::path ResolveHistoryPath (const std::string &session_id="")
void RenderTable (const ChatMessage::TableData &table_data)
Variables
const ImVec4 kUserColor = ImVec4(0.88f, 0.76f, 0.36f, 1.0f)
const ImVec4 kAgentColor = ImVec4(0.56f, 0.82f, 0.62f, 1.0f)
const ImVec4 kJsonTextColor = ImVec4(0.78f, 0.83f, 0.90f, 1.0f)
const ImVec4 kProposalPanelColor = ImVec4(0.20f, 0.35f, 0.20f, 0.35f)
Function Documentation
ExpandUserPath()
std::filesystem::path anonymous_namespace{agent_chat_widget.cc}::ExpandUserPath (std::string path)
Definition at line 33 of file agent_chat_widget.cc.
Referenced by ResolveHistoryPath().
ResolveHistoryPath()
std::filesystem::path anonymous_namespace{agent_chat_widget.cc}::ResolveHistoryPath (const std::string & session_id = "")
Definition at line 48 of file agent_chat_widget.cc.
References ExpandUserPath(), and yaze::core::GetConfigDirectory().
RenderTable()
void anonymous_namespace{agent_chat_widget.cc}::RenderTable (const ChatMessage::TableData & table_data)
Definition at line 64 of file agent_chat_widget.cc.
References yaze::cli::agent::ChatMessage::TableData::headers, and yaze::cli::agent::ChatMessage::TableData::rows.
Variable Documentation
kUserColor
const ImVec4 anonymous_namespace{agent_chat_widget.cc}::kUserColor = ImVec4(0.88f, 0.76f, 0.36f, 1.0f)
Definition at line 28 of file agent_chat_widget.cc.
kAgentColor
const ImVec4 anonymous_namespace{agent_chat_widget.cc}::kAgentColor = ImVec4(0.56f, 0.82f, 0.62f, 1.0f)
Definition at line 29 of file agent_chat_widget.cc.
kJsonTextColor
const ImVec4 anonymous_namespace{agent_chat_widget.cc}::kJsonTextColor = ImVec4(0.78f, 0.83f, 0.90f, 1.0f)
Definition at line 30 of file agent_chat_widget.cc.
kProposalPanelColor
const ImVec4 anonymous_namespace{agent_chat_widget.cc}::kProposalPanelColor = ImVec4(0.20f, 0.35f, 0.20f, 0.35f)
Definition at line 31 of file agent_chat_widget.cc.