yaze: yaze::editor::AgentUI Namespace Reference
yaze::editor::AgentUI Namespace Reference
Enumerations
enum class ButtonColor {
Success , Warning , Error , Info ,
Default
}
Functions
const AgentUITheme & GetTheme ()
void RefreshTheme ()
void PushPanelStyle ()
void PopPanelStyle ()
void RenderSectionHeader (const char *icon, const char *label, const ImVec4 &color)
void RenderStatusIndicator (const char *label, bool active)
void RenderProviderBadge (const char *provider)
void StatusBadge (const char *text, ButtonColor color)
void VerticalSpacing (float amount)
void HorizontalSpacing (float amount)
bool StyledButton (const char *label, const ImVec4 &color, const ImVec2 &size)
bool IconButton (const char *icon, const char *tooltip)
Enumeration Type Documentation
ButtonColor
enum class yaze::editor::AgentUI::ButtonColor strong
Enumerator
Success
Warning
Error
Info
Default
Definition at line 87 of file agent_ui_theme.h.
Function Documentation
GetTheme()
const AgentUITheme & yaze::editor::AgentUI::GetTheme ()
Definition at line 86 of file agent_ui_theme.cc.
References RefreshTheme().
Referenced by yaze::editor::AgentChatHistoryPopup::Draw(), yaze::editor::AgentChatHistoryPopup::DrawHeader(), PushPanelStyle(), yaze::editor::AgentChatWidget::RenderAgentConfigPanel(), yaze::editor::AgentChatWidget::RenderAutomationPanel(), yaze::editor::AgentChatWidget::RenderHistory(), yaze::editor::AgentChatWidget::RenderInputBox(), yaze::editor::AgentChatWidget::RenderMessage(), yaze::editor::AgentChatWidget::RenderMultimodalPanel(), yaze::editor::AgentChatWidget::RenderProposalQuickActions(), RenderProviderBadge(), yaze::editor::AgentChatWidget::RenderScreenshotPreview(), RenderStatusIndicator(), and StatusBadge().
RefreshTheme()
void yaze::editor::AgentUI::RefreshTheme ()
Definition at line 93 of file agent_ui_theme.cc.
References yaze::editor::AgentUITheme::FromCurrentTheme().
Referenced by GetTheme().
PushPanelStyle()
void yaze::editor::AgentUI::PushPanelStyle ()
Definition at line 98 of file agent_ui_theme.cc.
References GetTheme().
Referenced by yaze::editor::AgentChatWidget::RenderAutomationPanel(), and yaze::editor::AgentChatWidget::RenderMultimodalPanel().
PopPanelStyle()
void yaze::editor::AgentUI::PopPanelStyle ()
Definition at line 105 of file agent_ui_theme.cc.
Referenced by yaze::editor::AgentChatWidget::RenderAutomationPanel(), and yaze::editor::AgentChatWidget::RenderMultimodalPanel().
RenderSectionHeader()
void yaze::editor::AgentUI::RenderSectionHeader (const char * icon, const char * label, const ImVec4 & color)
Definition at line 110 of file agent_ui_theme.cc.
Referenced by yaze::editor::AgentChatWidget::RenderAgentConfigPanel(), and yaze::editor::AgentChatWidget::RenderMultimodalPanel().
RenderStatusIndicator()
void yaze::editor::AgentUI::RenderStatusIndicator (const char * label, bool active)
Definition at line 115 of file agent_ui_theme.cc.
References GetTheme().
RenderProviderBadge()
void yaze::editor::AgentUI::RenderProviderBadge (const char * provider)
Definition at line 132 of file agent_ui_theme.cc.
References GetTheme().
StatusBadge()
void yaze::editor::AgentUI::StatusBadge (const char * text, ButtonColor color)
Definition at line 152 of file agent_ui_theme.cc.
References Error, GetTheme(), Info, Success, and Warning.
VerticalSpacing()
void yaze::editor::AgentUI::VerticalSpacing (float amount)
Definition at line 172 of file agent_ui_theme.cc.
HorizontalSpacing()
void yaze::editor::AgentUI::HorizontalSpacing (float amount)
Definition at line 176 of file agent_ui_theme.cc.
StyledButton()
bool yaze::editor::AgentUI::StyledButton (const char * label, const ImVec4 & color, const ImVec2 & size)
Definition at line 181 of file agent_ui_theme.cc.
IconButton()
bool yaze::editor::AgentUI::IconButton (const char * icon, const char * tooltip)
Definition at line 197 of file agent_ui_theme.cc.