yaze: yaze::cli::agent::anonymous_namespace{simple_chat_session.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{simple_chat_session.cc} Namespace Reference
Functions
std::string EscapeJsonString (absl::string_view input)
std::string QuoteJson (absl::string_view value)
std::string TableToJson (const ChatMessage::TableData &table)
std::string MetricsToJson (const ChatMessage::SessionMetrics &metrics)
std::string MessageToJson (const ChatMessage &msg, bool show_timestamp)
void PrintMarkdownTable (const ChatMessage::TableData &table)
void PrintMarkdownMetrics (const ChatMessage::SessionMetrics &metrics)
std::string SessionMetricsToJson (const ChatMessage::SessionMetrics &metrics)
Function Documentation
EscapeJsonString()
std::string yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::EscapeJsonString (absl::string_view input)
Definition at line 35 of file simple_chat_session.cc.
QuoteJson()
std::string yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::QuoteJson (absl::string_view value)
Definition at line 76 of file simple_chat_session.cc.
References QuoteJson().
Referenced by MessageToJson(), QuoteJson(), and TableToJson().
TableToJson()
std::string yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::TableToJson (const ChatMessage::TableData & table)
Definition at line 80 of file simple_chat_session.cc.
References yaze::cli::agent::ChatMessage::TableData::headers, QuoteJson(), yaze::cli::agent::ChatMessage::TableData::rows, and TableToJson().
Referenced by MessageToJson(), and TableToJson().
MetricsToJson()
std::string yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::MetricsToJson (const ChatMessage::SessionMetrics & metrics)
Definition at line 104 of file simple_chat_session.cc.
References yaze::cli::agent::ChatMessage::SessionMetrics::average_latency_seconds, MetricsToJson(), yaze::cli::agent::ChatMessage::SessionMetrics::total_agent_messages, yaze::cli::agent::ChatMessage::SessionMetrics::total_commands, yaze::cli::agent::ChatMessage::SessionMetrics::total_elapsed_seconds, yaze::cli::agent::ChatMessage::SessionMetrics::total_proposals, yaze::cli::agent::ChatMessage::SessionMetrics::total_tool_calls, yaze::cli::agent::ChatMessage::SessionMetrics::total_user_messages, and yaze::cli::agent::ChatMessage::SessionMetrics::turn_index.
Referenced by MessageToJson(), MetricsToJson(), and SessionMetricsToJson().
MessageToJson()
std::string yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::MessageToJson (const ChatMessage & msg, bool show_timestamp)
Definition at line 116 of file simple_chat_session.cc.
References yaze::cli::agent::ChatMessage::json_pretty, yaze::cli::agent::ChatMessage::kUser, yaze::cli::agent::ChatMessage::message, MessageToJson(), yaze::cli::agent::ChatMessage::metrics, MetricsToJson(), QuoteJson(), yaze::cli::agent::ChatMessage::sender, yaze::cli::agent::ChatMessage::table_data, TableToJson(), and yaze::cli::agent::ChatMessage::timestamp.
Referenced by MessageToJson().
PrintMarkdownTable()
void yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::PrintMarkdownTable (const ChatMessage::TableData & table)
Definition at line 150 of file simple_chat_session.cc.
References yaze::cli::agent::ChatMessage::TableData::headers, PrintMarkdownTable(), and yaze::cli::agent::ChatMessage::TableData::rows.
Referenced by PrintMarkdownTable().
PrintMarkdownMetrics()
void yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::PrintMarkdownMetrics (const ChatMessage::SessionMetrics & metrics)
Definition at line 177 of file simple_chat_session.cc.
References yaze::cli::agent::ChatMessage::SessionMetrics::average_latency_seconds, PrintMarkdownMetrics(), yaze::cli::agent::ChatMessage::SessionMetrics::total_agent_messages, yaze::cli::agent::ChatMessage::SessionMetrics::total_commands, yaze::cli::agent::ChatMessage::SessionMetrics::total_elapsed_seconds, yaze::cli::agent::ChatMessage::SessionMetrics::total_proposals, yaze::cli::agent::ChatMessage::SessionMetrics::total_tool_calls, yaze::cli::agent::ChatMessage::SessionMetrics::total_user_messages, and yaze::cli::agent::ChatMessage::SessionMetrics::turn_index.
Referenced by PrintMarkdownMetrics().
SessionMetricsToJson()
std::string yaze::cli::agent::anonymous_namespace{simple_chat_session.cc}::SessionMetricsToJson (const ChatMessage::SessionMetrics & metrics)
Definition at line 191 of file simple_chat_session.cc.
References MetricsToJson(), and SessionMetricsToJson().
Referenced by SessionMetricsToJson().