yaze: yaze::test::RomDependentTest Class Reference
yaze::test::RomDependentTest Class Reference
Test fixture for ROM-dependent tests.
#include <test_utils.h>
Protected Member Functions
void SetUp () override
Protected Attributes
std::vector< uint8_t > test_rom_
Detailed Description
Test fixture for ROM-dependent tests.
Definition at line 179 of file test_utils.h.
Member Function Documentation
SetUp()
void yaze::test::RomDependentTest::SetUp () inline override protected
Definition at line 181 of file test_utils.h.
References yaze::test::TestRomManager::LoadTestRom(), yaze::test::TestRomManager::SkipIfRomTestingDisabled(), and test_rom_.
Referenced by yaze::test::integration::AsarRomIntegrationTest::SetUp().
Member Data Documentation
test_rom_
std::vector<uint8_t> yaze::test::RomDependentTest::test_rom_ protected
Definition at line 187 of file test_utils.h.
Referenced by SetUp().
The documentation for this class was generated from the following file:
test/test_utils.h