yaze: yaze::cli::Palette Class Reference
yaze::cli::Palette Class Reference
#include <z3ed.h>
Public Member Functions
Palette ()
absl::Status Run (const std::vector< std::string > &arg_vec) override
void RunTUI (ftxui::ScreenInteractive &screen) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
Rom rom_
Detailed Description
Definition at line 71 of file z3ed.h.
Constructor & Destructor Documentation
Palette()
yaze::cli::Palette::Palette ()
Definition at line 14 of file palette.cc.
Member Function Documentation
Run()
absl::Status yaze::cli::Palette::Run (const std::vector< std::string > & arg_vec) override virtual
Implements yaze::cli::CommandHandler.
Definition at line 16 of file palette.cc.
References yaze::cli::PaletteExport::Run(), and yaze::cli::PaletteImport::Run().
Referenced by yaze::cli::ModernCLI::HandlePaletteCommand().
RunTUI()
void yaze::cli::Palette::RunTUI (ftxui::ScreenInteractive & screen) override virtual
Todo:
Implement palette editor TUI
Reimplemented from yaze::cli::CommandHandler.
Definition at line 35 of file palette.cc.
The documentation for this class was generated from the following files:
src/cli/z3ed.h
src/cli/handlers/palette.cc