yaze: src/emu_test.cc File Reference
emu_test.cc File Reference
#include <SDL.h>
#include <cstdint>
#include <cstdio>
#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include "absl/flags/flag.h"
#include "absl/flags/parse.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "app/emu/snes.h"
#include "util/log.h"
Classes
class yaze::emu::test::HeadlessEmulator
Namespaces
namespace yaze
Main namespace for the application.
namespace yaze::emu
SNES Emulation and debugging tools.
namespace yaze::emu::test
Functions
ABSL_FLAG (std::string, rom, "", "Path to ROM file to test")
ABSL_FLAG (int, max_frames, 60, "Maximum frames to run (0 = infinite)")
ABSL_FLAG (int, log_interval, 10, "Log APU state every N frames")
ABSL_FLAG (bool, dump_audio, false, "Dump audio output to WAV file")
ABSL_FLAG (std::string, audio_file, "apu_test.wav", "Audio dump filename")
ABSL_FLAG (bool, verbose, false, "Enable verbose logging")
ABSL_FLAG (bool, trace_apu, false, "Enable detailed APU instruction tracing")
int main (int argc, char **argv)
Function Documentation
ABSL_FLAG() [1/7]
ABSL_FLAG (std::string , rom , "" , "Path to ROM file to test")
ABSL_FLAG() [2/7]
ABSL_FLAG (int , max_frames , 60 , "Maximum frames to run (0 = infinite)")
ABSL_FLAG() [3/7]
ABSL_FLAG (int , log_interval , 10 , "Log APU state every N frames")
ABSL_FLAG() [4/7]
ABSL_FLAG (bool , dump_audio , false , "Dump audio output to WAV file")
ABSL_FLAG() [5/7]
ABSL_FLAG (std::string , audio_file , "apu_test.wav" , "Audio dump filename")
ABSL_FLAG() [6/7]
ABSL_FLAG (bool , verbose , false , "Enable verbose logging")
ABSL_FLAG() [7/7]
ABSL_FLAG (bool , trace_apu , false , "Enable detailed APU instruction tracing")
main()
int main (int argc, char ** argv)
Definition at line 206 of file emu_test.cc.
References yaze::emu::Snes::apu(), yaze::emu::Snes::cpu(), yaze::emu::test::HeadlessEmulator::Init(), yaze::emu::Snes::Init(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), yaze::emu::Snes::loadState(), yaze::emu::Snes::memory(), yaze::emu::Snes::RunFrame(), yaze::emu::test::HeadlessEmulator::RunFrames(), yaze::emu::Snes::saveState(), yaze::emu::Snes::SetPixels(), yaze::emu::Snes::SetSamples(), yaze::Rom::size(), and yaze::Rom::vector().