yaze: extract_changelog Namespace Reference
extract_changelog Namespace Reference
Functions
extract_version_changelog (version_num, changelog_file)
main ()
Detailed Description
Extract changelog section for a specific version from docs/C1-changelog.md
Usage: python3 extract_changelog.py <version>
Example: python3 extract_changelog.py 0.3.0
Function Documentation
extract_version_changelog()
extract_changelog.extract_version_changelog (version_num, changelog_file)
Extract changelog section for specific version
Definition at line 12 of file extract_changelog.py.
Referenced by main().
main()
extract_changelog.main ()
Definition at line 44 of file extract_changelog.py.
References extract_version_changelog(), and main().
Referenced by main().