yaze: yaze::editor::AgentChatWidget::MultimodalCallbacks Struct Reference
yaze::editor::AgentChatWidget::MultimodalCallbacks Struct Reference
#include <agent_chat_widget.h>
Public Attributes
std::function< absl::Status(std::filesystem::path *)> capture_snapshot
std::function< absl::Status(const std::filesystem::path &, const std::string &)> send_to_gemini
Detailed Description
Definition at line 65 of file agent_chat_widget.h.
Member Data Documentation
capture_snapshot
std::function<absl::Status(std::filesystem::path*)> yaze::editor::AgentChatWidget::MultimodalCallbacks::capture_snapshot
Definition at line 66 of file agent_chat_widget.h.
Referenced by yaze::editor::AgentChatWidget::CaptureSelectedRegion(), yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderInputBox(), yaze::editor::AgentChatWidget::RenderMultimodalPanel(), and yaze::editor::AgentChatWidget::SetChatHistoryPopup().
send_to_gemini
std::function<absl::Status(const std::filesystem::path&, const std::string&)> yaze::editor::AgentChatWidget::MultimodalCallbacks::send_to_gemini
Definition at line 67 of file agent_chat_widget.h.
Referenced by yaze::editor::AgentChatWidget::CaptureSelectedRegion(), yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderInputBox(), and yaze::editor::AgentChatWidget::RenderMultimodalPanel().
The documentation for this struct was generated from the following file:
src/app/editor/agent/agent_chat_widget.h