yaze: yaze::gfx::GraphicsOptimizationBenchmarks Class Reference
yaze::gfx::GraphicsOptimizationBenchmarks Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
std::vector< uint8_t > CreateTestBitmapData (int width, int height)
SnesPalette CreateTestPalette ()
Detailed Description
Definition at line 16 of file gfx_optimization_benchmarks.cc.
Member Function Documentation
SetUp()
void yaze::gfx::GraphicsOptimizationBenchmarks::SetUp () inline override protected
Definition at line 18 of file gfx_optimization_benchmarks.cc.
References yaze::gfx::PerformanceProfiler::Clear(), yaze::gfx::Arena::Get(), yaze::gfx::MemoryPool::Get(), and yaze::gfx::PerformanceProfiler::Get().
TearDown()
void yaze::gfx::GraphicsOptimizationBenchmarks::TearDown () inline override protected
Definition at line 25 of file gfx_optimization_benchmarks.cc.
References yaze::gfx::PerformanceProfiler::Clear(), and yaze::gfx::PerformanceProfiler::Get().
CreateTestBitmapData()
std::vector< uint8_t > yaze::gfx::GraphicsOptimizationBenchmarks::CreateTestBitmapData (int width, int height) inline protected
Definition at line 31 of file gfx_optimization_benchmarks.cc.
CreateTestPalette()
SnesPalette yaze::gfx::GraphicsOptimizationBenchmarks::CreateTestPalette () inline protected
Definition at line 43 of file gfx_optimization_benchmarks.cc.
References yaze::gfx::SnesPalette::AddColor().
The documentation for this class was generated from the following file:
test/benchmarks/gfx_optimization_benchmarks.cc