yaze: yaze::agent::AgentControlServer Class Reference
yaze::agent::AgentControlServer Class Reference
#include <agent_control_server.h>
Public Member Functions
AgentControlServer (yaze::emu::Emulator *emulator)
~AgentControlServer ()
void Start ()
void Stop ()
Private Member Functions
void Run ()
Private Attributes
yaze::emu::Emulator * emulator_
std::unique_ptr< grpc::Server > server_
std::thread server_thread_
Detailed Description
Definition at line 16 of file agent_control_server.h.
Constructor & Destructor Documentation
AgentControlServer()
yaze::agent::AgentControlServer::AgentControlServer (yaze::emu::Emulator * emulator)
Definition at line 9 of file agent_control_server.cc.
~AgentControlServer()
yaze::agent::AgentControlServer::~AgentControlServer ()
Definition at line 12 of file agent_control_server.cc.
References Stop().
Member Function Documentation
Start()
void yaze::agent::AgentControlServer::Start ()
Definition at line 16 of file agent_control_server.cc.
References Run(), and server_thread_.
Stop()
void yaze::agent::AgentControlServer::Stop ()
Definition at line 20 of file agent_control_server.cc.
References server_, and server_thread_.
Referenced by ~AgentControlServer().
Run()
void yaze::agent::AgentControlServer::Run () private
Definition at line 29 of file agent_control_server.cc.
References emulator_, and server_.
Referenced by Start().
Member Data Documentation
emulator_
yaze::emu::Emulator* yaze::agent::AgentControlServer::emulator_ private
Definition at line 27 of file agent_control_server.h.
Referenced by Run().
server_
std::unique_ptr<grpc::Server> yaze::agent::AgentControlServer::server_ private
Definition at line 28 of file agent_control_server.h.
Referenced by Run(), and Stop().
server_thread_
std::thread yaze::agent::AgentControlServer::server_thread_ private
Definition at line 29 of file agent_control_server.h.
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
src/cli/service/agent/agent_control_server.h
src/cli/service/agent/agent_control_server.cc