yaze: yaze::emu::input::SDL2InputBackend Class Reference
yaze::emu::input::SDL2InputBackend Class Reference
SDL2 input backend implementation.
Public Member Functions
SDL2InputBackend ()=default
~SDL2InputBackend () override
bool Initialize (const InputConfig &config) override
Initialize the input backend.
void Shutdown () override
Shutdown the input backend.
ControllerState Poll (int player) override
Poll current input state (call every frame)
void ProcessEvent (void *event) override
Process platform-specific events (optional)
InputConfig GetConfig () const override
Get current configuration.
void SetConfig (const InputConfig &config) override
Update configuration (hot-reload)
std::string GetBackendName () const override
Get backend name for debugging.
bool IsInitialized () const override
Check if backend is initialized.
Public Member Functions inherited from yaze::emu::input::IInputBackend
virtual ~IInputBackend ()=default
Private Member Functions
void UpdateEventState (int keycode, bool pressed)
Private Attributes
InputConfig config_
bool initialized_ = false
ControllerState event_state_
Detailed Description
SDL2 input backend implementation.
Definition at line 13 of file input_backend.cc.
Constructor & Destructor Documentation
SDL2InputBackend()
yaze::emu::input::SDL2InputBackend::SDL2InputBackend () default
~SDL2InputBackend()
yaze::emu::input::SDL2InputBackend::~SDL2InputBackend () inline override
Definition at line 16 of file input_backend.cc.
References Shutdown().
Member Function Documentation
Initialize()
bool yaze::emu::input::SDL2InputBackend::Initialize (const InputConfig & config) inline override virtual
Initialize the input backend.
Implements yaze::emu::input::IInputBackend.
Definition at line 18 of file input_backend.cc.
References config_, initialized_, yaze::emu::input::InputConfig::key_a, yaze::emu::input::InputConfig::key_b, yaze::emu::input::InputConfig::key_down, yaze::emu::input::InputConfig::key_l, yaze::emu::input::InputConfig::key_left, yaze::emu::input::InputConfig::key_r, yaze::emu::input::InputConfig::key_right, yaze::emu::input::InputConfig::key_select, yaze::emu::input::InputConfig::key_start, yaze::emu::input::InputConfig::key_up, yaze::emu::input::InputConfig::key_x, yaze::emu::input::InputConfig::key_y, LOG_INFO, and LOG_WARN.
Shutdown()
void yaze::emu::input::SDL2InputBackend::Shutdown () inline override virtual
Shutdown the input backend.
Implements yaze::emu::input::IInputBackend.
Definition at line 47 of file input_backend.cc.
References initialized_, and LOG_INFO.
Referenced by ~SDL2InputBackend().
Poll()
ControllerState yaze::emu::input::SDL2InputBackend::Poll (int player) inline override virtual
Poll current input state (call every frame)
Parameters
player Player number (1-4)
Returns
Current controller state
Todo:
Add gamepad support
Implements yaze::emu::input::IInputBackend.
Definition at line 54 of file input_backend.cc.
References yaze::emu::input::A, yaze::emu::input::B, config_, yaze::emu::input::InputConfig::continuous_polling, yaze::emu::input::DOWN, event_state_, initialized_, yaze::emu::input::InputConfig::key_a, yaze::emu::input::InputConfig::key_b, yaze::emu::input::InputConfig::key_down, yaze::emu::input::InputConfig::key_l, yaze::emu::input::InputConfig::key_left, yaze::emu::input::InputConfig::key_r, yaze::emu::input::InputConfig::key_right, yaze::emu::input::InputConfig::key_select, yaze::emu::input::InputConfig::key_start, yaze::emu::input::InputConfig::key_up, yaze::emu::input::InputConfig::key_x, yaze::emu::input::InputConfig::key_y, yaze::emu::input::L, yaze::emu::input::LEFT, yaze::emu::input::R, yaze::emu::input::RIGHT, yaze::emu::input::SELECT, yaze::emu::input::ControllerState::SetButton(), yaze::emu::input::START, yaze::emu::input::UP, yaze::emu::input::X, and yaze::emu::input::Y.
ProcessEvent()
void yaze::emu::input::SDL2InputBackend::ProcessEvent (void * event) inline override virtual
Process platform-specific events (optional)
Parameters
event Platform-specific event data (e.g., SDL_Event*)
Todo:
Handle gamepad events
Implements yaze::emu::input::IInputBackend.
Definition at line 87 of file input_backend.cc.
References initialized_, and UpdateEventState().
GetConfig()
InputConfig yaze::emu::input::SDL2InputBackend::GetConfig () const inline override virtual
Get current configuration.
Implements yaze::emu::input::IInputBackend.
Definition at line 102 of file input_backend.cc.
References config_.
SetConfig()
void yaze::emu::input::SDL2InputBackend::SetConfig (const InputConfig & config) inline override virtual
Update configuration (hot-reload)
Implements yaze::emu::input::IInputBackend.
Definition at line 104 of file input_backend.cc.
References config_.
GetBackendName()
std::string yaze::emu::input::SDL2InputBackend::GetBackendName () const inline override virtual
Get backend name for debugging.
Implements yaze::emu::input::IInputBackend.
Definition at line 108 of file input_backend.cc.
IsInitialized()
bool yaze::emu::input::SDL2InputBackend::IsInitialized () const inline override virtual
Check if backend is initialized.
Implements yaze::emu::input::IInputBackend.
Definition at line 110 of file input_backend.cc.
References initialized_.
UpdateEventState()
void yaze::emu::input::SDL2InputBackend::UpdateEventState (int keycode, bool pressed) inline private
Definition at line 113 of file input_backend.cc.
References yaze::emu::input::A, yaze::emu::input::B, config_, yaze::emu::input::DOWN, event_state_, yaze::emu::input::InputConfig::key_a, yaze::emu::input::InputConfig::key_b, yaze::emu::input::InputConfig::key_down, yaze::emu::input::InputConfig::key_l, yaze::emu::input::InputConfig::key_left, yaze::emu::input::InputConfig::key_r, yaze::emu::input::InputConfig::key_right, yaze::emu::input::InputConfig::key_select, yaze::emu::input::InputConfig::key_start, yaze::emu::input::InputConfig::key_up, yaze::emu::input::InputConfig::key_x, yaze::emu::input::InputConfig::key_y, yaze::emu::input::L, yaze::emu::input::LEFT, yaze::emu::input::R, yaze::emu::input::RIGHT, yaze::emu::input::SELECT, yaze::emu::input::ControllerState::SetButton(), yaze::emu::input::START, yaze::emu::input::UP, yaze::emu::input::X, and yaze::emu::input::Y.
Referenced by ProcessEvent().
Member Data Documentation
config_
InputConfig yaze::emu::input::SDL2InputBackend::config_ private
Definition at line 129 of file input_backend.cc.
Referenced by GetConfig(), Initialize(), Poll(), SetConfig(), and UpdateEventState().
initialized_
bool yaze::emu::input::SDL2InputBackend::initialized_ = false private
Definition at line 130 of file input_backend.cc.
Referenced by Initialize(), IsInitialized(), Poll(), ProcessEvent(), and Shutdown().
event_state_
ControllerState yaze::emu::input::SDL2InputBackend::event_state_ private
Definition at line 131 of file input_backend.cc.
Referenced by Poll(), and UpdateEventState().
The documentation for this class was generated from the following file:
src/app/emu/input/input_backend.cc