yaze: yaze::cli::handlers::HexSearchCommandHandler Class Reference
yaze::cli::handlers::HexSearchCommandHandler Class Reference
Command handler for searching hex patterns in ROM.
#include <hex_commands.h>
Public Member Functions
std::string GetName () const
Get the command name.
std::string GetDescription () const
std::string GetUsage () const
Get the command usage string.
absl::Status ValidateArgs (const resources::ArgumentParser &parser) override
Validate command arguments.
absl::Status Execute (Rom *rom, const resources::ArgumentParser &parser, resources::OutputFormatter &formatter) override
Execute the command business logic.
Public Member Functions inherited from yaze::cli::resources::CommandHandler
virtual ~CommandHandler ()=default
absl::Status Run (const std::vector< std::string > &args, Rom *rom_context)
Execute the command.
virtual Descriptor Describe () const
Provide metadata for TUI/help summaries.
Additional Inherited Members
Protected Member Functions inherited from yaze::cli::resources::CommandHandler
virtual bool RequiresLabels () const
Check if the command requires ROM labels.
virtual std::string GetDefaultFormat () const
Get the default output format ("json" or "text")
virtual std::string GetOutputTitle () const
Get the output title for formatting.
Detailed Description
Command handler for searching hex patterns in ROM.
Definition at line 55 of file hex_commands.h.
Member Function Documentation
GetName()
std::string yaze::cli::handlers::HexSearchCommandHandler::GetName () const inline virtual
Get the command name.
Override this to provide a unique identifier for the command. This is used for command registration and lookup.
Implements yaze::cli::resources::CommandHandler.
Definition at line 57 of file hex_commands.h.
GetDescription()
std::string yaze::cli::handlers::HexSearchCommandHandler::GetDescription () const inline
Definition at line 58 of file hex_commands.h.
GetUsage()
std::string yaze::cli::handlers::HexSearchCommandHandler::GetUsage () const inline virtual
Get the command usage string.
Implements yaze::cli::resources::CommandHandler.
Definition at line 61 of file hex_commands.h.
ValidateArgs()
absl::Status yaze::cli::handlers::HexSearchCommandHandler::ValidateArgs (const resources::ArgumentParser & parser) inline override virtual
Validate command arguments.
Override this to check required arguments and perform custom validation. Called before Execute().
Implements yaze::cli::resources::CommandHandler.
Definition at line 65 of file hex_commands.h.
References yaze::cli::resources::ArgumentParser::RequireArgs().
Execute()
absl::Status yaze::cli::handlers::HexSearchCommandHandler::Execute (Rom * rom, const resources::ArgumentParser & parser, resources::OutputFormatter & formatter) override virtual
Execute the command business logic.
Override this to implement command-specific functionality. The ROM is guaranteed to be loaded and labels initialized.
Implements yaze::cli::resources::CommandHandler.
Definition at line 126 of file hex_commands.cc.
References yaze::cli::resources::OutputFormatter::AddArrayItem(), yaze::cli::resources::OutputFormatter::AddField(), yaze::cli::resources::OutputFormatter::AddHexField(), yaze::cli::resources::OutputFormatter::BeginArray(), yaze::cli::resources::OutputFormatter::BeginObject(), yaze::Rom::data(), yaze::cli::resources::OutputFormatter::EndArray(), yaze::cli::resources::OutputFormatter::EndObject(), yaze::cli::resources::ArgumentParser::GetString(), and yaze::Rom::size().
The documentation for this class was generated from the following files:
src/cli/handlers/graphics/hex_commands.h
src/cli/handlers/graphics/hex_commands.cc