yaze: yaze::editor::ToastManager Class Reference
yaze::editor::ToastManager Class Reference
#include <toast_manager.h>
Public Member Functions
void Show (const std::string &message, ToastType type=ToastType::kInfo, float ttl_seconds=3.0f)
void Draw ()
Private Attributes
std::deque< Toast > toasts_
Detailed Description
Definition at line 25 of file toast_manager.h.
Member Function Documentation
Show()
void yaze::editor::ToastManager::Show (const std::string & message, ToastType type = ToastType::kInfo, float ttl_seconds = 3.0f) inline
Definition at line 27 of file toast_manager.h.
References toasts_.
Referenced by yaze::editor::AgentChatWidget::BeginRegionSelection(), yaze::editor::AgentChatWidget::CaptureSelectedRegion(), yaze::editor::AgentChatHistoryPopup::ClearHistory(), yaze::editor::WorkspaceManager::CloseAllFloatingWindows(), yaze::editor::SessionCoordinator::CloseSession(), yaze::editor::RomFileManager::CreateBackup(), yaze::editor::ProjectManager::CreateFromTemplate(), yaze::editor::ProjectManager::CreateNewProject(), yaze::editor::EditorManager::CreateNewSession(), yaze::editor::AgentChatWidget::Draw(), yaze::editor::ProjectFileEditor::Draw(), yaze::editor::AgentEditor::DrawBotProfilesPanel(), yaze::editor::AgentEditor::DrawChatHistoryViewer(), yaze::editor::AgentEditor::DrawCommonTilesEditor(), yaze::editor::AgentEditor::DrawConfigurationPanel(), yaze::editor::AgentEditor::DrawDashboard(), yaze::editor::UICoordinator::DrawGlobalSearch(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::AgentEditor::DrawNewPromptCreator(), yaze::editor::AgentEditor::DrawPromptEditorPanel(), yaze::editor::AgentChatHistoryPopup::DrawQuickActions(), yaze::editor::UICoordinator::DrawWorkspacePresetDialogs(), yaze::editor::EditorManager::DuplicateCurrentSession(), yaze::editor::AgentChatWidget::EnsureHistoryLoaded(), yaze::editor::WorkspaceManager::ExecuteWorkspaceCommand(), yaze::editor::AgentChatHistoryPopup::ExportHistory(), yaze::editor::ProjectManager::ExportProject(), yaze::editor::AgentChatWidget::HandleAgentResponse(), yaze::editor::AgentChatWidget::HandleRegionSelection(), yaze::editor::WorkspaceManager::HideAllWindows(), yaze::editor::AgentEditor::HostSession(), yaze::editor::EditorManager::ImportProject(), yaze::editor::ProjectManager::ImportProject(), yaze::editor::EditorManager::Initialize(), yaze::editor::AgentEditor::JoinSession(), yaze::editor::AgentEditor::LeaveSession(), yaze::editor::WorkspaceManager::LoadDesignerLayout(), yaze::editor::WorkspaceManager::LoadDeveloperLayout(), yaze::editor::WorkspaceManager::LoadModderLayout(), yaze::editor::ProjectManager::LoadProjectFromFile(), yaze::editor::EditorManager::LoadRom(), yaze::editor::RomFileManager::LoadRomFromFile(), yaze::editor::AgentChatWidget::LoadScreenshotPreview(), yaze::editor::WorkspaceManager::LoadWorkspaceLayout(), yaze::editor::WorkspaceManager::LoadWorkspacePreset(), yaze::editor::WorkspaceManager::MaximizeCurrentWindow(), yaze::editor::AgentChatHistoryPopup::NotifyNewMessage(), yaze::editor::AgentChatWidget::NotifyProposalCreated(), yaze::editor::MenuOrchestrator::OnCheckRomVersion(), yaze::editor::MenuOrchestrator::OnCopy(), yaze::editor::MenuOrchestrator::OnCreateBackup(), yaze::editor::MenuOrchestrator::OnCreateProject(), yaze::editor::MenuOrchestrator::OnCut(), yaze::editor::MenuOrchestrator::OnFind(), yaze::editor::MenuOrchestrator::OnLoadAsmFile(), yaze::editor::MenuOrchestrator::OnOpenProject(), yaze::editor::MenuOrchestrator::OnOpenRom(), yaze::editor::MenuOrchestrator::OnPaste(), yaze::editor::MenuOrchestrator::OnRedo(), yaze::editor::MenuOrchestrator::OnRunDataIntegrityCheck(), yaze::editor::MenuOrchestrator::OnSaveProject(), yaze::editor::MenuOrchestrator::OnSaveProjectAs(), yaze::editor::MenuOrchestrator::OnSaveRom(), yaze::editor::MenuOrchestrator::OnShowLayoutPresets(), yaze::editor::MenuOrchestrator::OnShowSessionManager(), yaze::editor::MenuOrchestrator::OnTestSaveLoad(), yaze::editor::MenuOrchestrator::OnToggleAsarPatch(), yaze::editor::MenuOrchestrator::OnToggleCustomLoading(), yaze::editor::MenuOrchestrator::OnUndo(), yaze::editor::MenuOrchestrator::OnUpgradeRom(), yaze::editor::MenuOrchestrator::OnValidateRom(), yaze::editor::AgentChatWidget::OpenFileInEditor(), yaze::editor::EditorManager::OpenProject(), yaze::editor::AgentChatWidget::PersistHistory(), yaze::editor::AgentChatWidget::PollAutomationStatus(), yaze::editor::AgentChatWidget::PollSharedHistory(), yaze::editor::AgentChatWidget::RefreshCollaboration(), yaze::editor::AgentChatWidget::RenderCollaborationPanel(), yaze::editor::AgentChatWidget::RenderFileEditorTabs(), yaze::editor::AgentChatWidget::RenderInputBox(), yaze::editor::AgentChatWidget::RenderMessage(), yaze::editor::AgentChatWidget::RenderMultimodalPanel(), yaze::editor::AgentChatWidget::RenderProposalQuickActions(), yaze::editor::AgentChatWidget::RenderRomSyncPanel(), yaze::editor::AgentChatWidget::RenderSnapshotPreviewPanel(), yaze::editor::AgentChatWidget::RenderSystemPromptEditor(), yaze::editor::AgentChatWidget::RenderZ3EDCommandPanel(), yaze::editor::EditorManager::RepairCurrentProject(), yaze::editor::ProjectManager::RepairCurrentProject(), yaze::editor::WorkspaceManager::ResetWorkspaceLayout(), yaze::editor::WorkspaceManager::RestoreAllWindows(), yaze::editor::EditorManager::SaveProjectAs(), yaze::editor::ProjectManager::SaveProjectToFile(), yaze::editor::RomFileManager::SaveRom(), yaze::editor::RomFileManager::SaveRomAs(), yaze::editor::WorkspaceManager::SaveWorkspaceLayout(), yaze::editor::WorkspaceManager::SaveWorkspacePreset(), yaze::editor::AgentChatHistoryPopup::SendMessage(), yaze::editor::AgentChatWidget::SetChatHistoryPopup(), yaze::editor::AgentChatWidget::SetLastPlanSummary(), yaze::editor::AgentChatWidget::SetRomContext(), yaze::editor::WorkspaceManager::ShowAllWindows(), yaze::editor::SessionCoordinator::ShowSessionLimitWarning(), yaze::editor::SessionCoordinator::ShowSessionOperationResult(), yaze::editor::AgentChatWidget::SwitchToLocalHistory(), yaze::editor::AgentChatWidget::SwitchToSharedHistory(), yaze::editor::EditorManager::Update(), yaze::editor::AgentChatWidget::UpdateAgentConfig(), yaze::editor::ProjectFileEditor::ValidateContent(), yaze::editor::ProjectManager::ValidateProject(), and yaze::editor::RomFileManager::ValidateRom().
Draw()
void yaze::editor::ToastManager::Draw () inline
Definition at line 32 of file toast_manager.h.
References yaze::editor::kError, yaze::editor::kInfo, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::Toast::message, toasts_, yaze::editor::Toast::ttl_seconds, and yaze::editor::Toast::type.
Referenced by yaze::editor::EditorManager::Update().
Member Data Documentation
toasts_
std::deque<Toast> yaze::editor::ToastManager::toasts_ private
Definition at line 73 of file toast_manager.h.
Referenced by Draw(), and Show().
The documentation for this class was generated from the following file:
src/app/editor/system/toast_manager.h