yaze: yaze::editor::AgentCollaborationCoordinator Class Reference
yaze::editor::AgentCollaborationCoordinator Class Reference
#include <agent_collaboration_coordinator.h>
Classes
struct SessionFileData
struct SessionInfo
Public Member Functions
AgentCollaborationCoordinator ()
absl::StatusOr< SessionInfo > HostSession (const std::string &session_name)
absl::StatusOr< SessionInfo > JoinSession (const std::string &session_code)
absl::Status LeaveSession ()
absl::StatusOr< SessionInfo > RefreshSession ()
bool active () const
const std::string & session_id () const
const std::string & session_name () const
Private Member Functions
absl::Status EnsureDirectory () const
std::string LocalUserName () const
std::string NormalizeSessionCode (const std::string &input) const
std::string GenerateSessionCode () const
std::filesystem::path SessionsDirectory () const
std::filesystem::path SessionFilePath (const std::string &code) const
absl::StatusOr< SessionFileData > LoadSessionFile (const std::filesystem::path &path) const
absl::Status WriteSessionFile (const std::filesystem::path &path, const SessionFileData &data) const
Private Attributes
bool active_ = false
bool hosting_ = false
std::string session_id_
std::string session_name_
std::string local_user_
Detailed Description
Definition at line 18 of file agent_collaboration_coordinator.h.
Constructor & Destructor Documentation
AgentCollaborationCoordinator()
yaze::editor::AgentCollaborationCoordinator::AgentCollaborationCoordinator ()
Definition at line 49 of file agent_collaboration_coordinator.cc.
Member Function Documentation
HostSession()
absl::StatusOr< AgentCollaborationCoordinator::SessionInfo > yaze::editor::AgentCollaborationCoordinator::HostSession (const std::string & session_name)
Definition at line 53 of file agent_collaboration_coordinator.cc.
References active_, EnsureDirectory(), GenerateSessionCode(), yaze::editor::AgentCollaborationCoordinator::SessionFileData::host, hosting_, local_user_, yaze::editor::AgentCollaborationCoordinator::SessionInfo::participants, yaze::editor::AgentCollaborationCoordinator::SessionFileData::participants, RETURN_IF_ERROR, yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_code, yaze::editor::AgentCollaborationCoordinator::SessionInfo::session_id, session_id_, yaze::editor::AgentCollaborationCoordinator::SessionInfo::session_name, session_name(), yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_name, session_name_, SessionFilePath(), and WriteSessionFile().
JoinSession()
absl::StatusOr< AgentCollaborationCoordinator::SessionInfo > yaze::editor::AgentCollaborationCoordinator::JoinSession (const std::string & session_code)
Definition at line 95 of file agent_collaboration_coordinator.cc.
References active_, ASSIGN_OR_RETURN, EnsureDirectory(), hosting_, LoadSessionFile(), local_user_, NormalizeSessionCode(), yaze::editor::AgentCollaborationCoordinator::SessionInfo::participants, yaze::editor::AgentCollaborationCoordinator::SessionFileData::participants, RETURN_IF_ERROR, yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_code, yaze::editor::AgentCollaborationCoordinator::SessionInfo::session_id, session_id_, yaze::editor::AgentCollaborationCoordinator::SessionInfo::session_name, yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_name, session_name_, SessionFilePath(), and WriteSessionFile().
LeaveSession()
absl::Status yaze::editor::AgentCollaborationCoordinator::LeaveSession ()
Definition at line 125 of file agent_collaboration_coordinator.cc.
References active_, hosting_, LoadSessionFile(), local_user_, yaze::editor::AgentCollaborationCoordinator::SessionFileData::participants, session_id_, session_name_, SessionFilePath(), and WriteSessionFile().
RefreshSession()
absl::StatusOr< AgentCollaborationCoordinator::SessionInfo > yaze::editor::AgentCollaborationCoordinator::RefreshSession ()
Definition at line 173 of file agent_collaboration_coordinator.cc.
References active_, hosting_, LoadSessionFile(), yaze::editor::AgentCollaborationCoordinator::SessionInfo::participants, yaze::editor::AgentCollaborationCoordinator::SessionFileData::participants, yaze::editor::AgentCollaborationCoordinator::SessionInfo::session_id, session_id_, yaze::editor::AgentCollaborationCoordinator::SessionInfo::session_name, yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_name, session_name_, and SessionFilePath().
active()
bool yaze::editor::AgentCollaborationCoordinator::active () const inline
Definition at line 33 of file agent_collaboration_coordinator.h.
References active_.
session_id()
const std::string & yaze::editor::AgentCollaborationCoordinator::session_id () const inline
Definition at line 34 of file agent_collaboration_coordinator.h.
References session_id_.
session_name()
const std::string & yaze::editor::AgentCollaborationCoordinator::session_name () const inline
Definition at line 35 of file agent_collaboration_coordinator.h.
References session_name_.
Referenced by HostSession().
EnsureDirectory()
absl::Status yaze::editor::AgentCollaborationCoordinator::EnsureDirectory () const private
Definition at line 200 of file agent_collaboration_coordinator.cc.
References SessionsDirectory().
Referenced by HostSession(), and JoinSession().
LocalUserName()
std::string yaze::editor::AgentCollaborationCoordinator::LocalUserName () const private
Definition at line 210 of file agent_collaboration_coordinator.cc.
NormalizeSessionCode()
std::string yaze::editor::AgentCollaborationCoordinator::NormalizeSessionCode (const std::string & input) const private
Definition at line 232 of file agent_collaboration_coordinator.cc.
Referenced by JoinSession(), and LoadSessionFile().
GenerateSessionCode()
std::string yaze::editor::AgentCollaborationCoordinator::GenerateSessionCode () const private
Definition at line 249 of file agent_collaboration_coordinator.cc.
Referenced by HostSession().
SessionsDirectory()
std::filesystem::path yaze::editor::AgentCollaborationCoordinator::SessionsDirectory () const private
Definition at line 261 of file agent_collaboration_coordinator.cc.
References yaze::core::GetConfigDirectory().
Referenced by EnsureDirectory(), and SessionFilePath().
SessionFilePath()
std::filesystem::path yaze::editor::AgentCollaborationCoordinator::SessionFilePath (const std::string & code) const private
Definition at line 269 of file agent_collaboration_coordinator.cc.
References SessionsDirectory().
Referenced by HostSession(), JoinSession(), LeaveSession(), and RefreshSession().
LoadSessionFile()
absl::StatusOr< AgentCollaborationCoordinator::SessionFileData > yaze::editor::AgentCollaborationCoordinator::LoadSessionFile (const std::filesystem::path & path) const private
Definition at line 275 of file agent_collaboration_coordinator.cc.
References yaze::editor::AgentCollaborationCoordinator::SessionFileData::host, NormalizeSessionCode(), yaze::editor::AgentCollaborationCoordinator::SessionFileData::participants, yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_code, and yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_name.
Referenced by JoinSession(), LeaveSession(), and RefreshSession().
WriteSessionFile()
absl::Status yaze::editor::AgentCollaborationCoordinator::WriteSessionFile (const std::filesystem::path & path, const SessionFileData & data) const private
Definition at line 326 of file agent_collaboration_coordinator.cc.
References yaze::editor::AgentCollaborationCoordinator::SessionFileData::host, yaze::editor::AgentCollaborationCoordinator::SessionFileData::participants, yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_code, and yaze::editor::AgentCollaborationCoordinator::SessionFileData::session_name.
Referenced by HostSession(), JoinSession(), and LeaveSession().
Member Data Documentation
active_
bool yaze::editor::AgentCollaborationCoordinator::active_ = false private
Definition at line 56 of file agent_collaboration_coordinator.h.
Referenced by active(), HostSession(), JoinSession(), LeaveSession(), and RefreshSession().
hosting_
bool yaze::editor::AgentCollaborationCoordinator::hosting_ = false private
Definition at line 57 of file agent_collaboration_coordinator.h.
Referenced by HostSession(), JoinSession(), LeaveSession(), and RefreshSession().
session_id_
std::string yaze::editor::AgentCollaborationCoordinator::session_id_ private
Definition at line 58 of file agent_collaboration_coordinator.h.
Referenced by HostSession(), JoinSession(), LeaveSession(), RefreshSession(), and session_id().
session_name_
std::string yaze::editor::AgentCollaborationCoordinator::session_name_ private
Definition at line 59 of file agent_collaboration_coordinator.h.
Referenced by HostSession(), JoinSession(), LeaveSession(), RefreshSession(), and session_name().
local_user_
std::string yaze::editor::AgentCollaborationCoordinator::local_user_ private
Definition at line 60 of file agent_collaboration_coordinator.h.
Referenced by HostSession(), JoinSession(), and LeaveSession().
The documentation for this class was generated from the following files:
src/app/editor/agent/agent_collaboration_coordinator.h
src/app/editor/agent/agent_collaboration_coordinator.cc