yaze: yaze::cli::agent::anonymous_namespace{tool_dispatcher.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{tool_dispatcher.cc} Namespace Reference
Functions
ToolCallType GetToolCallType (const std::string &tool_name)
std::unique_ptr< resources::CommandHandler > CreateHandler (ToolCallType type)
std::vector< std::string > ConvertArgsToVector (const std::map< std::string, std::string > &args)
Function Documentation
GetToolCallType()
ToolCallType yaze::cli::agent::anonymous_namespace{tool_dispatcher.cc}::GetToolCallType (const std::string & tool_name)
Definition at line 31 of file tool_dispatcher.cc.
References GetToolCallType(), yaze::cli::agent::kDialogueList, yaze::cli::agent::kDialogueRead, yaze::cli::agent::kDialogueSearch, yaze::cli::agent::kDungeonDescribeRoom, yaze::cli::agent::kDungeonExportRoom, yaze::cli::agent::kDungeonGetRoomTiles, yaze::cli::agent::kDungeonListObjects, yaze::cli::agent::kDungeonListSprites, yaze::cli::agent::kDungeonSetRoomProperty, yaze::cli::agent::kEmulatorClearBreakpoint, yaze::cli::agent::kEmulatorGetMetrics, yaze::cli::agent::kEmulatorGetRegisters, yaze::cli::agent::kEmulatorGetState, yaze::cli::agent::kEmulatorListBreakpoints, yaze::cli::agent::kEmulatorPause, yaze::cli::agent::kEmulatorReadMemory, yaze::cli::agent::kEmulatorReset, yaze::cli::agent::kEmulatorRun, yaze::cli::agent::kEmulatorSetBreakpoint, yaze::cli::agent::kEmulatorStep, yaze::cli::agent::kEmulatorWriteMemory, yaze::cli::agent::kGuiClick, yaze::cli::agent::kGuiDiscover, yaze::cli::agent::kGuiPlaceTile, yaze::cli::agent::kGuiScreenshot, yaze::cli::agent::kMessageList, yaze::cli::agent::kMessageRead, yaze::cli::agent::kMessageSearch, yaze::cli::agent::kMusicInfo, yaze::cli::agent::kMusicList, yaze::cli::agent::kMusicTracks, yaze::cli::agent::kOverworldDescribeMap, yaze::cli::agent::kOverworldFindTile, yaze::cli::agent::kOverworldGetEntrance, yaze::cli::agent::kOverworldListSprites, yaze::cli::agent::kOverworldListWarps, yaze::cli::agent::kOverworldTileStats, yaze::cli::agent::kResourceList, yaze::cli::agent::kResourceSearch, yaze::cli::agent::kSpriteList, yaze::cli::agent::kSpritePalette, yaze::cli::agent::kSpriteProperties, and yaze::cli::agent::kUnknown.
Referenced by GetToolCallType().
CreateHandler()
std::unique_ptr< resources::CommandHandler > yaze::cli::agent::anonymous_namespace{tool_dispatcher.cc}::CreateHandler (ToolCallType type)
Definition at line 94 of file tool_dispatcher.cc.
References CreateHandler(), yaze::cli::agent::kDialogueList, yaze::cli::agent::kDialogueRead, yaze::cli::agent::kDialogueSearch, yaze::cli::agent::kDungeonDescribeRoom, yaze::cli::agent::kDungeonExportRoom, yaze::cli::agent::kDungeonGetRoomTiles, yaze::cli::agent::kDungeonListObjects, yaze::cli::agent::kDungeonListSprites, yaze::cli::agent::kDungeonSetRoomProperty, yaze::cli::agent::kEmulatorClearBreakpoint, yaze::cli::agent::kEmulatorGetMetrics, yaze::cli::agent::kEmulatorGetRegisters, yaze::cli::agent::kEmulatorGetState, yaze::cli::agent::kEmulatorListBreakpoints, yaze::cli::agent::kEmulatorPause, yaze::cli::agent::kEmulatorReadMemory, yaze::cli::agent::kEmulatorReset, yaze::cli::agent::kEmulatorRun, yaze::cli::agent::kEmulatorSetBreakpoint, yaze::cli::agent::kEmulatorStep, yaze::cli::agent::kEmulatorWriteMemory, yaze::cli::agent::kGuiClick, yaze::cli::agent::kGuiDiscover, yaze::cli::agent::kGuiPlaceTile, yaze::cli::agent::kGuiScreenshot, yaze::cli::agent::kMessageList, yaze::cli::agent::kMessageRead, yaze::cli::agent::kMessageSearch, yaze::cli::agent::kMusicInfo, yaze::cli::agent::kMusicList, yaze::cli::agent::kMusicTracks, yaze::cli::agent::kOverworldDescribeMap, yaze::cli::agent::kOverworldFindTile, yaze::cli::agent::kOverworldGetEntrance, yaze::cli::agent::kOverworldListSprites, yaze::cli::agent::kOverworldListWarps, yaze::cli::agent::kOverworldTileStats, yaze::cli::agent::kResourceList, yaze::cli::agent::kResourceSearch, yaze::cli::agent::kSpriteList, yaze::cli::agent::kSpritePalette, and yaze::cli::agent::kSpriteProperties.
Referenced by CreateHandler().
ConvertArgsToVector()
std::vector< std::string > yaze::cli::agent::anonymous_namespace{tool_dispatcher.cc}::ConvertArgsToVector (const std::map< std::string, std::string > & args)
Definition at line 206 of file tool_dispatcher.cc.
References ConvertArgsToVector().
Referenced by ConvertArgsToVector().