yaze: TextEditor Class Reference
TextEditor Class Reference
#include <text_editor.h>
Classes
struct Breakpoint
struct Coordinates
struct EditorState
struct Glyph
struct Identifier
struct LanguageDefinition
class UndoRecord
Public Types
enum class PaletteIndex {
Default , Keyword , Number , String ,
CharLiteral , Punctuation , Preprocessor , Identifier ,
KnownIdentifier , PreprocIdentifier , Comment , MultiLineComment ,
Background , Cursor , Selection , ErrorMarker ,
Breakpoint , LineNumber , CurrentLineFill , CurrentLineFillInactive ,
CurrentLineEdge , Max
}
enum class SelectionMode { Normal , Word , Line }
typedef std::string String
typedef std::unordered_map< std::string, Identifier > Identifiers
typedef std::unordered_set< std::string > Keywords
typedef std::map< int, std::string > ErrorMarkers
typedef std::unordered_set< int > Breakpoints
typedef std::array< ImU32,(unsigned) PaletteIndex::Max > Palette
typedef uint8_t Char
typedef std::vector< Glyph > Line
typedef std::vector< Line > Lines
Public Member Functions
TextEditor ()
~TextEditor ()
void SetLanguageDefinition (const LanguageDefinition &aLanguageDef)
const LanguageDefinition & GetLanguageDefinition () const
const Palette & GetPalette () const
void SetPalette (const Palette &aValue)
void SetErrorMarkers (const ErrorMarkers &aMarkers)
void SetBreakpoints (const Breakpoints &aMarkers)
void Render (const char *aTitle, const ImVec2 &aSize=ImVec2(), bool aBorder=false)
void SetText (const std::string &aText)
std::string GetText () const
void SetTextLines (const std::vector< std::string > &aLines)
std::vector< std::string > GetTextLines () const
std::string GetSelectedText () const
std::string GetCurrentLineText () const
int GetTotalLines () const
bool IsOverwrite () const
void SetReadOnly (bool aValue)
bool IsReadOnly () const
bool IsTextChanged () const
bool IsCursorPositionChanged () const
bool IsColorizerEnabled () const
void SetColorizerEnable (bool aValue)
Coordinates GetCursorPosition () const
void SetCursorPosition (const Coordinates &aPosition)
void SetHandleMouseInputs (bool aValue)
bool IsHandleMouseInputsEnabled () const
void SetHandleKeyboardInputs (bool aValue)
bool IsHandleKeyboardInputsEnabled () const
void SetImGuiChildIgnored (bool aValue)
bool IsImGuiChildIgnored () const
void SetShowWhitespaces (bool aValue)
bool IsShowingWhitespaces () const
void SetTabSize (int aValue)
int GetTabSize () const
void InsertText (const std::string &aValue)
void InsertText (const char *aValue)
void MoveUp (int aAmount=1, bool aSelect=false)
void MoveDown (int aAmount=1, bool aSelect=false)
void MoveLeft (int aAmount=1, bool aSelect=false, bool aWordMode=false)
void MoveRight (int aAmount=1, bool aSelect=false, bool aWordMode=false)
void MoveTop (bool aSelect=false)
void MoveBottom (bool aSelect=false)
void MoveHome (bool aSelect=false)
void MoveEnd (bool aSelect=false)
void SetSelectionStart (const Coordinates &aPosition)
void SetSelectionEnd (const Coordinates &aPosition)
void SetSelection (const Coordinates &aStart, const Coordinates &aEnd, SelectionMode aMode=SelectionMode::Normal)
void SelectWordUnderCursor ()
void SelectAll ()
bool HasSelection () const
void Copy ()
void Cut ()
void Paste ()
void Delete ()
bool CanUndo () const
bool CanRedo () const
void Undo (int aSteps=1)
void Redo (int aSteps=1)
Static Public Member Functions
static const Palette & GetDarkPalette ()
static const Palette & GetLightPalette ()
static const Palette & GetRetroBluePalette ()
Private Types
typedef std::vector< std::pair< std::regex, PaletteIndex > > RegexList
typedef std::vector< UndoRecord > UndoBuffer
Private Member Functions
void ProcessInputs ()
void Colorize (int aFromLine=0, int aCount=-1)
void ColorizeRange (int aFromLine=0, int aToLine=0)
void ColorizeInternal ()
float TextDistanceToLineStart (const Coordinates &aFrom) const
void EnsureCursorVisible ()
int GetPageSize () const
std::string GetText (const Coordinates &aStart, const Coordinates &aEnd) const
Coordinates GetActualCursorCoordinates () const
Coordinates SanitizeCoordinates (const Coordinates &aValue) const
void Advance (Coordinates &aCoordinates) const
void DeleteRange (const Coordinates &aStart, const Coordinates &aEnd)
int InsertTextAt (Coordinates &aWhere, const char *aValue)
void AddUndo (UndoRecord &aValue)
Coordinates ScreenPosToCoordinates (const ImVec2 &aPosition) const
Coordinates FindWordStart (const Coordinates &aFrom) const
Coordinates FindWordEnd (const Coordinates &aFrom) const
Coordinates FindNextWord (const Coordinates &aFrom) const
int GetCharacterIndex (const Coordinates &aCoordinates) const
int GetCharacterColumn (int aLine, int aIndex) const
int GetLineCharacterCount (int aLine) const
int GetLineMaxColumn (int aLine) const
bool IsOnWordBoundary (const Coordinates &aAt) const
void RemoveLine (int aStart, int aEnd)
void RemoveLine (int aIndex)
Line & InsertLine (int aIndex)
void EnterCharacter (ImWchar aChar, bool aShift)
void Backspace ()
void DeleteSelection ()
std::string GetWordUnderCursor () const
std::string GetWordAt (const Coordinates &aCoords) const
ImU32 GetGlyphColor (const Glyph &aGlyph) const
void HandleKeyboardInputs ()
void HandleMouseInputs ()
void Render ()
Private Attributes
float mLineSpacing
Lines mLines
EditorState mState
UndoBuffer mUndoBuffer
int mUndoIndex
int mTabSize
bool mOverwrite
bool mReadOnly
bool mWithinRender
bool mScrollToCursor
bool mScrollToTop
bool mTextChanged
bool mColorizerEnabled
float mTextStart
int mLeftMargin
bool mCursorPositionChanged
int mColorRangeMin
int mColorRangeMax
SelectionMode mSelectionMode
bool mHandleKeyboardInputs
bool mHandleMouseInputs
bool mIgnoreImGuiChild
bool mShowWhitespaces
Palette mPaletteBase
Palette mPalette
LanguageDefinition mLanguageDefinition
RegexList mRegexList
bool mCheckComments
Breakpoints mBreakpoints
ErrorMarkers mErrorMarkers
ImVec2 mCharAdvance
Coordinates mInteractiveStart
Coordinates mInteractiveEnd
std::string mLineBuffer
uint64_t mStartTime
float mLastClick
Detailed Description
Definition at line 17 of file text_editor.h.
Member Typedef Documentation
String
typedef std::string TextEditor::String
Definition at line 108 of file text_editor.h.
Identifiers
typedef std::unordered_map<std::string, Identifier> TextEditor::Identifiers
Definition at line 109 of file text_editor.h.
Keywords
typedef std::unordered_set<std::string> TextEditor::Keywords
Definition at line 110 of file text_editor.h.
ErrorMarkers
typedef std::map<int, std::string> TextEditor::ErrorMarkers
Definition at line 111 of file text_editor.h.
Breakpoints
typedef std::unordered_set<int> TextEditor::Breakpoints
Definition at line 112 of file text_editor.h.
Palette
typedef std::array<ImU32, (unsigned)PaletteIndex::Max> TextEditor::Palette
Definition at line 113 of file text_editor.h.
Char
typedef uint8_t TextEditor::Char
Definition at line 114 of file text_editor.h.
Line
typedef std::vector<Glyph> TextEditor::Line
Definition at line 131 of file text_editor.h.
Lines
typedef std::vector<Line> TextEditor::Lines
Definition at line 132 of file text_editor.h.
RegexList
typedef std::vector<std::pair<std::regex, PaletteIndex> > TextEditor::RegexList private
Definition at line 268 of file text_editor.h.
UndoBuffer
typedef std::vector<UndoRecord> TextEditor::UndoBuffer private
Definition at line 307 of file text_editor.h.
Member Enumeration Documentation
PaletteIndex
enum class TextEditor::PaletteIndex strong
Enumerator
Default
Keyword
Number
String
CharLiteral
Punctuation
Preprocessor
Identifier
KnownIdentifier
PreprocIdentifier
Comment
MultiLineComment
Background
Cursor
Selection
ErrorMarker
Breakpoint
LineNumber
CurrentLineFill
CurrentLineFillInactive
CurrentLineEdge
Max
Definition at line 19 of file text_editor.h.
SelectionMode
enum class TextEditor::SelectionMode strong
Enumerator
Normal
Word
Line
Definition at line 44 of file text_editor.h.
Constructor & Destructor Documentation
TextEditor()
TextEditor::TextEditor ()
Definition at line 24 of file text_editor.cc.
References GetDarkPalette(), TextEditor::LanguageDefinition::HLSL(), mLines, SetLanguageDefinition(), and SetPalette().
~TextEditor()
TextEditor::~TextEditor ()
Definition at line 55 of file text_editor.cc.
Member Function Documentation
SetLanguageDefinition()
void TextEditor::SetLanguageDefinition (const LanguageDefinition & aLanguageDef)
Definition at line 57 of file text_editor.cc.
References Colorize(), mLanguageDefinition, mRegexList, and TextEditor::LanguageDefinition::mTokenRegexStrings.
Referenced by yaze::editor::AssemblyEditor::AssemblyEditor(), yaze::editor::AgentChatWidget::CreateNewFileInEditor(), yaze::editor::AgentChatWidget::LoadAgentSettingsFromProject(), yaze::editor::AgentChatWidget::OpenFileInEditor(), yaze::editor::ProjectFileEditor::ProjectFileEditor(), yaze::editor::AgentChatWidget::RenderSystemPromptEditor(), and TextEditor().
GetLanguageDefinition()
const LanguageDefinition & TextEditor::GetLanguageDefinition () const inline
Definition at line 175 of file text_editor.h.
References mLanguageDefinition.
Referenced by yaze::editor::AssemblyEditor::DrawFileTabView(), yaze::editor::AssemblyEditor::InlineUpdate(), yaze::editor::AssemblyEditor::Update(), and yaze::editor::AssemblyEditor::UpdateCodeView().
GetPalette()
const Palette & TextEditor::GetPalette () const inline
Definition at line 179 of file text_editor.h.
References mPaletteBase.
SetPalette()
void TextEditor::SetPalette (const Palette & aValue)
Definition at line 68 of file text_editor.cc.
References mPaletteBase.
Referenced by yaze::editor::AssemblyEditor::AssemblyEditor(), and TextEditor().
SetErrorMarkers()
void TextEditor::SetErrorMarkers (const ErrorMarkers & aMarkers) inline
Definition at line 182 of file text_editor.h.
References mErrorMarkers.
SetBreakpoints()
void TextEditor::SetBreakpoints (const Breakpoints & aMarkers) inline
Definition at line 185 of file text_editor.h.
References mBreakpoints.
Render() [1/2]
void TextEditor::Render (const char * aTitle, const ImVec2 & aSize = ImVec2(), bool aBorder = false)
Definition at line 1052 of file text_editor.cc.
References Background, ColorizeInternal(), HandleKeyboardInputs(), HandleMouseInputs(), mCursorPositionChanged, mHandleKeyboardInputs, mHandleMouseInputs, mIgnoreImGuiChild, mPalette, mTextChanged, mWithinRender, and Render().
Referenced by yaze::editor::ProjectFileEditor::Draw(), yaze::editor::AssemblyEditor::InlineUpdate(), yaze::editor::AssemblyEditor::Update(), and yaze::editor::AssemblyEditor::UpdateCodeView().
SetText()
void TextEditor::SetText (const std::string & aText)
Definition at line 1085 of file text_editor.cc.
References Colorize(), Default, mLines, mScrollToTop, mTextChanged, mUndoBuffer, and mUndoIndex.
Referenced by yaze::editor::AssemblyEditor::DrawFileTabView(), yaze::editor::AgentChatWidget::LoadAgentSettingsFromProject(), yaze::editor::ProjectFileEditor::LoadFile(), yaze::editor::ProjectFileEditor::NewFile(), yaze::editor::AgentChatWidget::OpenFileInEditor(), yaze::editor::AgentChatWidget::RenderSystemPromptEditor(), and yaze::editor::AssemblyEditor::SetEditorText().
GetText() [1/2]
std::string TextEditor::GetText () const
Definition at line 1888 of file text_editor.cc.
References GetText(), and mLines.
Referenced by Delete(), EnterCharacter(), GetCurrentLineText(), GetSelectedText(), GetText(), yaze::editor::ProjectFileEditor::SaveFileAs(), and yaze::editor::ProjectFileEditor::ValidateContent().
SetTextLines()
void TextEditor::SetTextLines (const std::vector< std::string > & aLines)
Definition at line 1107 of file text_editor.cc.
References Colorize(), Default, mLines, mScrollToTop, mTextChanged, mUndoBuffer, and mUndoIndex.
GetTextLines()
std::vector< std::string > TextEditor::GetTextLines () const
Definition at line 1892 of file text_editor.cc.
References mLines.
GetSelectedText()
std::string TextEditor::GetSelectedText () const
Definition at line 1910 of file text_editor.cc.
References GetText(), TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, and mState.
Referenced by Backspace(), Copy(), Cut(), Delete(), EnterCharacter(), and Paste().
GetCurrentLineText()
std::string TextEditor::GetCurrentLineText () const
Definition at line 1914 of file text_editor.cc.
References GetLineMaxColumn(), GetText(), TextEditor::EditorState::mCursorPosition, TextEditor::Coordinates::mLine, and mState.
GetTotalLines()
int TextEditor::GetTotalLines () const inline
Definition at line 198 of file text_editor.h.
References mLines.
Referenced by yaze::editor::AssemblyEditor::DrawFileTabView(), yaze::editor::AssemblyEditor::InlineUpdate(), yaze::editor::AssemblyEditor::Update(), and yaze::editor::AssemblyEditor::UpdateCodeView().
IsOverwrite()
bool TextEditor::IsOverwrite () const inline
Definition at line 199 of file text_editor.h.
References mOverwrite.
Referenced by yaze::editor::AssemblyEditor::DrawFileTabView(), yaze::editor::AssemblyEditor::InlineUpdate(), yaze::editor::AssemblyEditor::Update(), and yaze::editor::AssemblyEditor::UpdateCodeView().
SetReadOnly()
void TextEditor::SetReadOnly (bool aValue)
Definition at line 1291 of file text_editor.cc.
References mReadOnly.
IsReadOnly()
bool TextEditor::IsReadOnly () const inline
Definition at line 202 of file text_editor.h.
References mReadOnly.
Referenced by Cut(), HandleKeyboardInputs(), and Paste().
IsTextChanged()
bool TextEditor::IsTextChanged () const inline
Definition at line 203 of file text_editor.h.
References mTextChanged.
Referenced by yaze::editor::ProjectFileEditor::IsModified().
IsCursorPositionChanged()
bool TextEditor::IsCursorPositionChanged () const inline
Definition at line 204 of file text_editor.h.
References mCursorPositionChanged.
IsColorizerEnabled()
bool TextEditor::IsColorizerEnabled () const inline
Definition at line 206 of file text_editor.h.
References mColorizerEnabled.
SetColorizerEnable()
void TextEditor::SetColorizerEnable (bool aValue)
Definition at line 1293 of file text_editor.cc.
References mColorizerEnabled.
GetCursorPosition()
Coordinates TextEditor::GetCursorPosition () const inline
Definition at line 209 of file text_editor.h.
References GetActualCursorCoordinates().
Referenced by yaze::editor::AssemblyEditor::DrawFileTabView(), GetWordUnderCursor(), yaze::editor::AssemblyEditor::InlineUpdate(), SelectWordUnderCursor(), yaze::editor::AssemblyEditor::Update(), and yaze::editor::AssemblyEditor::UpdateCodeView().
SetCursorPosition()
void TextEditor::SetCursorPosition (const Coordinates & aPosition)
Definition at line 1295 of file text_editor.cc.
References EnsureCursorVisible(), TextEditor::EditorState::mCursorPosition, mCursorPositionChanged, and mState.
Referenced by Backspace(), Delete(), DeleteSelection(), EnterCharacter(), InsertText(), MoveEnd(), MoveHome(), and MoveTop().
SetHandleMouseInputs()
void TextEditor::SetHandleMouseInputs (bool aValue) inline
Definition at line 212 of file text_editor.h.
References mHandleMouseInputs.
IsHandleMouseInputsEnabled()
bool TextEditor::IsHandleMouseInputsEnabled () const inline
Definition at line 213 of file text_editor.h.
References mHandleKeyboardInputs.
SetHandleKeyboardInputs()
void TextEditor::SetHandleKeyboardInputs (bool aValue) inline
Definition at line 217 of file text_editor.h.
References mHandleKeyboardInputs.
IsHandleKeyboardInputsEnabled()
bool TextEditor::IsHandleKeyboardInputsEnabled () const inline
Definition at line 220 of file text_editor.h.
References mHandleKeyboardInputs.
SetImGuiChildIgnored()
void TextEditor::SetImGuiChildIgnored (bool aValue) inline
Definition at line 224 of file text_editor.h.
References mIgnoreImGuiChild.
IsImGuiChildIgnored()
bool TextEditor::IsImGuiChildIgnored () const inline
Definition at line 225 of file text_editor.h.
References mIgnoreImGuiChild.
SetShowWhitespaces()
void TextEditor::SetShowWhitespaces (bool aValue) inline
Definition at line 227 of file text_editor.h.
References mShowWhitespaces.
Referenced by yaze::editor::AssemblyEditor::AssemblyEditor(), and yaze::editor::ProjectFileEditor::ProjectFileEditor().
IsShowingWhitespaces()
bool TextEditor::IsShowingWhitespaces () const inline
Definition at line 228 of file text_editor.h.
References mShowWhitespaces.
SetTabSize()
void TextEditor::SetTabSize (int aValue)
Definition at line 1351 of file text_editor.cc.
References mTabSize.
Referenced by yaze::editor::ProjectFileEditor::ProjectFileEditor().
GetTabSize()
int TextEditor::GetTabSize () const inline
Definition at line 231 of file text_editor.h.
References mTabSize.
InsertText() [1/2]
void TextEditor::InsertText (const std::string & aValue)
Definition at line 1355 of file text_editor.cc.
References InsertText().
Referenced by InsertText(), and Paste().
InsertText() [2/2]
void TextEditor::InsertText (const char * aValue)
Definition at line 1359 of file text_editor.cc.
References Colorize(), GetActualCursorCoordinates(), InsertTextAt(), TextEditor::EditorState::mSelectionStart, mState, SetCursorPosition(), and SetSelection().
MoveUp()
void TextEditor::MoveUp (int aAmount = 1, bool aSelect = false)
Definition at line 1385 of file text_editor.cc.
References EnsureCursorVisible(), TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, TextEditor::Coordinates::mLine, mState, and SetSelection().
Referenced by HandleKeyboardInputs().
MoveDown()
void TextEditor::MoveDown (int aAmount = 1, bool aSelect = false)
Definition at line 1407 of file text_editor.cc.
References EnsureCursorVisible(), TextEditor::Coordinates::mColumn, TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, TextEditor::Coordinates::mLine, mLines, mState, and SetSelection().
Referenced by HandleKeyboardInputs().
MoveLeft()
void TextEditor::MoveLeft (int aAmount = 1, bool aSelect = false, bool aWordMode = false)
Definition at line 1434 of file text_editor.cc.
References EnsureCursorVisible(), FindWordStart(), GetActualCursorCoordinates(), GetCharacterColumn(), GetCharacterIndex(), TextEditor::Coordinates::mColumn, TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, TextEditor::Coordinates::mLine, mLines, mState, Normal, SetSelection(), and Word.
Referenced by HandleKeyboardInputs().
MoveRight()
void TextEditor::MoveRight (int aAmount = 1, bool aSelect = false, bool aWordMode = false)
Definition at line 1490 of file text_editor.cc.
References EnsureCursorVisible(), FindNextWord(), GetCharacterColumn(), GetCharacterIndex(), TextEditor::Coordinates::mColumn, TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, TextEditor::Coordinates::mLine, mLines, mState, Normal, SanitizeCoordinates(), SetSelection(), and Word.
Referenced by HandleKeyboardInputs().
MoveTop()
void TextEditor::MoveTop (bool aSelect = false)
Definition at line 1535 of file text_editor.cc.
References TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, mState, SetCursorPosition(), and SetSelection().
Referenced by HandleKeyboardInputs().
MoveBottom()
void TextEditor::MoveBottom (bool aSelect = false)
Referenced by HandleKeyboardInputs().
MoveHome()
void TextEditor::MoveHome (bool aSelect = false)
Definition at line 1561 of file text_editor.cc.
References TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, TextEditor::Coordinates::mLine, mState, SetCursorPosition(), and SetSelection().
Referenced by HandleKeyboardInputs().
MoveEnd()
void TextEditor::MoveEnd (bool aSelect = false)
Definition at line 1581 of file text_editor.cc.
References GetLineMaxColumn(), TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, TextEditor::Coordinates::mLine, mState, SetCursorPosition(), and SetSelection().
Referenced by HandleKeyboardInputs().
SetSelectionStart()
void TextEditor::SetSelectionStart (const Coordinates & aPosition)
Definition at line 1303 of file text_editor.cc.
References TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mState, and SanitizeCoordinates().
SetSelectionEnd()
void TextEditor::SetSelectionEnd (const Coordinates & aPosition)
Definition at line 1309 of file text_editor.cc.
References TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mState, and SanitizeCoordinates().
SetSelection()
void TextEditor::SetSelection (const Coordinates & aStart, const Coordinates & aEnd, SelectionMode aMode = SelectionMode::Normal)
Definition at line 1315 of file text_editor.cc.
References FindWordEnd(), FindWordStart(), GetLineMaxColumn(), IsOnWordBoundary(), Line, mCursorPositionChanged, TextEditor::Coordinates::mLine, mLines, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mState, Normal, SanitizeCoordinates(), and Word.
Referenced by DeleteSelection(), HandleMouseInputs(), InsertText(), MoveDown(), MoveEnd(), MoveHome(), MoveLeft(), MoveRight(), MoveTop(), MoveUp(), SelectAll(), and SelectWordUnderCursor().
SelectWordUnderCursor()
void TextEditor::SelectWordUnderCursor ()
Definition at line 1721 of file text_editor.cc.
References FindWordEnd(), FindWordStart(), GetCursorPosition(), and SetSelection().
SelectAll()
void TextEditor::SelectAll ()
Definition at line 1726 of file text_editor.cc.
References mLines, and SetSelection().
Referenced by HandleKeyboardInputs().
HasSelection()
bool TextEditor::HasSelection () const
Definition at line 1730 of file text_editor.cc.
References TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, and mState.
Referenced by Backspace(), Copy(), Cut(), Delete(), EnterCharacter(), Paste(), and Render().
Copy()
void TextEditor::Copy ()
Definition at line 1734 of file text_editor.cc.
References GetActualCursorCoordinates(), GetSelectedText(), HasSelection(), TextEditor::Coordinates::mLine, and mLines.
Referenced by yaze::editor::AssemblyEditor::Copy(), Cut(), yaze::editor::AssemblyEditor::DrawEditMenu(), and HandleKeyboardInputs().
Cut()
void TextEditor::Cut ()
Definition at line 1747 of file text_editor.cc.
References AddUndo(), Copy(), DeleteSelection(), GetSelectedText(), HasSelection(), IsReadOnly(), TextEditor::UndoRecord::mAfter, TextEditor::UndoRecord::mBefore, TextEditor::UndoRecord::mRemoved, TextEditor::UndoRecord::mRemovedEnd, TextEditor::UndoRecord::mRemovedStart, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, and mState.
Referenced by yaze::editor::AssemblyEditor::Cut(), yaze::editor::AssemblyEditor::DrawEditMenu(), and HandleKeyboardInputs().
Paste()
void TextEditor::Paste ()
Definition at line 1767 of file text_editor.cc.
References AddUndo(), DeleteSelection(), GetActualCursorCoordinates(), GetSelectedText(), HasSelection(), InsertText(), IsReadOnly(), TextEditor::UndoRecord::mAdded, TextEditor::UndoRecord::mAddedEnd, TextEditor::UndoRecord::mAddedStart, TextEditor::UndoRecord::mAfter, TextEditor::UndoRecord::mBefore, TextEditor::UndoRecord::mRemoved, TextEditor::UndoRecord::mRemovedEnd, TextEditor::UndoRecord::mRemovedStart, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, and mState.
Referenced by yaze::editor::AssemblyEditor::DrawEditMenu(), HandleKeyboardInputs(), and yaze::editor::AssemblyEditor::Paste().
Delete()
void TextEditor::Delete ()
Definition at line 1602 of file text_editor.cc.
References AddUndo(), Advance(), Colorize(), DeleteSelection(), GetActualCursorCoordinates(), GetCharacterIndex(), GetLineMaxColumn(), GetSelectedText(), GetText(), HasSelection(), TextEditor::UndoRecord::mAfter, TextEditor::UndoRecord::mBefore, TextEditor::Coordinates::mColumn, mLines, mReadOnly, TextEditor::UndoRecord::mRemoved, TextEditor::UndoRecord::mRemovedEnd, TextEditor::UndoRecord::mRemovedStart, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mState, mTextChanged, RemoveLine(), and SetCursorPosition().
Referenced by HandleKeyboardInputs().
CanUndo()
bool TextEditor::CanUndo () const
Definition at line 1793 of file text_editor.cc.
References mReadOnly, and mUndoIndex.
Referenced by yaze::editor::AssemblyEditor::DrawFileTabView(), yaze::editor::AssemblyEditor::InlineUpdate(), Undo(), yaze::editor::AssemblyEditor::Update(), and yaze::editor::AssemblyEditor::UpdateCodeView().
CanRedo()
bool TextEditor::CanRedo () const
Definition at line 1795 of file text_editor.cc.
References mReadOnly, mUndoBuffer, and mUndoIndex.
Referenced by Redo().
Undo()
void TextEditor::Undo (int aSteps = 1)
Definition at line 1799 of file text_editor.cc.
References CanUndo(), mUndoBuffer, and mUndoIndex.
Referenced by yaze::editor::AssemblyEditor::DrawEditMenu(), HandleKeyboardInputs(), and yaze::editor::AssemblyEditor::Undo().
Redo()
void TextEditor::Redo (int aSteps = 1)
Definition at line 1803 of file text_editor.cc.
References CanRedo(), mUndoBuffer, and mUndoIndex.
Referenced by yaze::editor::AssemblyEditor::DrawEditMenu(), HandleKeyboardInputs(), and yaze::editor::AssemblyEditor::Redo().
GetDarkPalette()
const TextEditor::Palette & TextEditor::GetDarkPalette () static
Definition at line 1807 of file text_editor.cc.
Referenced by yaze::editor::AssemblyEditor::AssemblyEditor(), and TextEditor().
GetLightPalette()
const TextEditor::Palette & TextEditor::GetLightPalette () static
Definition at line 1834 of file text_editor.cc.
GetRetroBluePalette()
const TextEditor::Palette & TextEditor::GetRetroBluePalette () static
Definition at line 1861 of file text_editor.cc.
ProcessInputs()
void TextEditor::ProcessInputs () private
Definition at line 1920 of file text_editor.cc.
Colorize()
void TextEditor::Colorize (int aFromLine = 0, int aCount = -1) private
Definition at line 1922 of file text_editor.cc.
References mCheckComments, mColorRangeMax, mColorRangeMin, and mLines.
Referenced by Backspace(), Delete(), DeleteSelection(), EnterCharacter(), InsertText(), TextEditor::UndoRecord::Redo(), SetLanguageDefinition(), SetText(), SetTextLines(), and TextEditor::UndoRecord::Undo().
ColorizeRange()
void TextEditor::ColorizeRange (int aFromLine = 0, int aToLine = 0) private
Definition at line 1932 of file text_editor.cc.
References Default, Identifier, Keyword, KnownIdentifier, TextEditor::LanguageDefinition::mCaseSensitive, TextEditor::LanguageDefinition::mIdentifiers, TextEditor::LanguageDefinition::mKeywords, mLanguageDefinition, mLines, TextEditor::LanguageDefinition::mPreprocIdentifiers, mRegexList, TextEditor::LanguageDefinition::mTokenize, and PreprocIdentifier.
Referenced by ColorizeInternal().
ColorizeInternal()
void TextEditor::ColorizeInternal () private
Definition at line 2024 of file text_editor.cc.
References ColorizeRange(), equals(), mCheckComments, mColorizerEnabled, mColorRangeMax, mColorRangeMin, TextEditor::LanguageDefinition::mCommentEnd, TextEditor::LanguageDefinition::mCommentStart, mLanguageDefinition, mLines, TextEditor::LanguageDefinition::mPreprocChar, TextEditor::LanguageDefinition::mSingleLineComment, and TextEditor::LanguageDefinition::mTokenize.
Referenced by Render().
TextDistanceToLineStart()
float TextEditor::TextDistanceToLineStart (const Coordinates & aFrom) const private
Definition at line 2155 of file text_editor.cc.
References GetCharacterIndex(), TextEditor::Coordinates::mLine, mLines, and mTabSize.
Referenced by EnsureCursorVisible(), and Render().
EnsureCursorVisible()
void TextEditor::EnsureCursorVisible () private
Definition at line 2187 of file text_editor.cc.
References GetActualCursorCoordinates(), mCharAdvance, mScrollToCursor, mTextStart, mWithinRender, and TextDistanceToLineStart().
Referenced by Backspace(), EnterCharacter(), MoveDown(), MoveLeft(), MoveRight(), MoveUp(), TextEditor::UndoRecord::Redo(), Render(), SetCursorPosition(), and TextEditor::UndoRecord::Undo().
GetPageSize()
int TextEditor::GetPageSize () const private
Definition at line 2219 of file text_editor.cc.
References mCharAdvance.
Referenced by HandleKeyboardInputs().
GetText() [2/2]
std::string TextEditor::GetText (const Coordinates & aStart, const Coordinates & aEnd) const private
Definition at line 70 of file text_editor.cc.
References GetCharacterIndex(), TextEditor::Coordinates::mLine, and mLines.
GetActualCursorCoordinates()
TextEditor::Coordinates TextEditor::GetActualCursorCoordinates () const private
Definition at line 101 of file text_editor.cc.
References TextEditor::EditorState::mCursorPosition, mState, and SanitizeCoordinates().
Referenced by Backspace(), Copy(), Delete(), EnsureCursorVisible(), EnterCharacter(), GetCursorPosition(), InsertText(), MoveLeft(), and Paste().
SanitizeCoordinates()
TextEditor::Coordinates TextEditor::SanitizeCoordinates (const Coordinates & aValue) const private
Definition at line 105 of file text_editor.cc.
References GetLineMaxColumn(), TextEditor::Coordinates::mColumn, TextEditor::Coordinates::mLine, and mLines.
Referenced by GetActualCursorCoordinates(), MoveRight(), ScreenPosToCoordinates(), SetSelection(), SetSelectionEnd(), and SetSelectionStart().
Advance()
void TextEditor::Advance (Coordinates & aCoordinates) const private
Definition at line 172 of file text_editor.cc.
References GetCharacterColumn(), GetCharacterIndex(), TextEditor::Coordinates::mColumn, TextEditor::Coordinates::mLine, and mLines.
Referenced by Backspace(), and Delete().
DeleteRange()
void TextEditor::DeleteRange (const Coordinates & aStart, const Coordinates & aEnd) private
Definition at line 188 of file text_editor.cc.
References GetCharacterIndex(), GetLineMaxColumn(), TextEditor::Coordinates::mColumn, TextEditor::Coordinates::mLine, mLines, mReadOnly, mTextChanged, and RemoveLine().
Referenced by DeleteSelection(), TextEditor::UndoRecord::Redo(), and TextEditor::UndoRecord::Undo().
InsertTextAt()
int TextEditor::InsertTextAt (Coordinates & aWhere, const char * aValue) private
Definition at line 224 of file text_editor.cc.
References Default, GetCharacterIndex(), InsertLine(), TextEditor::Coordinates::mColumn, TextEditor::Coordinates::mLine, mLines, mReadOnly, and mTextChanged.
Referenced by InsertText(), TextEditor::UndoRecord::Redo(), and TextEditor::UndoRecord::Undo().
AddUndo()
void TextEditor::AddUndo (UndoRecord & aValue) private
Definition at line 265 of file text_editor.cc.
References mReadOnly, mUndoBuffer, and mUndoIndex.
Referenced by Backspace(), Cut(), Delete(), EnterCharacter(), and Paste().
ScreenPosToCoordinates()
TextEditor::Coordinates TextEditor::ScreenPosToCoordinates (const ImVec2 & aPosition) const private
Definition at line 283 of file text_editor.cc.
References mCharAdvance, mLines, mTabSize, mTextStart, and SanitizeCoordinates().
Referenced by HandleMouseInputs(), and Render().
FindWordStart()
TextEditor::Coordinates TextEditor::FindWordStart (const Coordinates & aFrom) const private
Definition at line 335 of file text_editor.cc.
References GetCharacterColumn(), GetCharacterIndex(), TextEditor::Coordinates::mLine, and mLines.
Referenced by GetWordAt(), MoveLeft(), SelectWordUnderCursor(), and SetSelection().
FindWordEnd()
TextEditor::Coordinates TextEditor::FindWordEnd (const Coordinates & aFrom) const private
Definition at line 363 of file text_editor.cc.
References GetCharacterColumn(), GetCharacterIndex(), TextEditor::Coordinates::mLine, and mLines.
Referenced by GetWordAt(), SelectWordUnderCursor(), and SetSelection().
FindNextWord()
TextEditor::Coordinates TextEditor::FindNextWord (const Coordinates & aFrom) const private
Definition at line 391 of file text_editor.cc.
References GetCharacterColumn(), GetCharacterIndex(), GetLineMaxColumn(), TextEditor::Coordinates::mLine, and mLines.
Referenced by MoveRight().
GetCharacterIndex()
int TextEditor::GetCharacterIndex (const Coordinates & aCoordinates) const private
Definition at line 433 of file text_editor.cc.
References TextEditor::Coordinates::mColumn, TextEditor::Coordinates::mLine, mLines, and mTabSize.
Referenced by Advance(), Backspace(), Delete(), DeleteRange(), EnterCharacter(), FindNextWord(), FindWordEnd(), FindWordStart(), GetText(), GetWordAt(), InsertTextAt(), IsOnWordBoundary(), MoveLeft(), MoveRight(), Render(), and TextDistanceToLineStart().
GetCharacterColumn()
int TextEditor::GetCharacterColumn (int aLine, int aIndex) const private
Definition at line 448 of file text_editor.cc.
References mLines, and mTabSize.
Referenced by Advance(), EnterCharacter(), FindNextWord(), FindWordEnd(), FindWordStart(), MoveLeft(), and MoveRight().
GetLineCharacterCount()
int TextEditor::GetLineCharacterCount (int aLine) const private
Definition at line 464 of file text_editor.cc.
References mLines.
GetLineMaxColumn()
int TextEditor::GetLineMaxColumn (int aLine) const private
Definition at line 472 of file text_editor.cc.
References mLines, and mTabSize.
Referenced by Backspace(), Delete(), DeleteRange(), EnterCharacter(), FindNextWord(), GetCurrentLineText(), MoveEnd(), Render(), SanitizeCoordinates(), and SetSelection().
IsOnWordBoundary()
bool TextEditor::IsOnWordBoundary (const Coordinates & aAt) const private
Definition at line 487 of file text_editor.cc.
References GetCharacterIndex(), mColorizerEnabled, TextEditor::Coordinates::mColumn, TextEditor::Coordinates::mLine, and mLines.
Referenced by SetSelection().
RemoveLine() [1/2]
void TextEditor::RemoveLine (int aStart, int aEnd) private
Definition at line 500 of file text_editor.cc.
References mBreakpoints, mErrorMarkers, mLines, mReadOnly, and mTextChanged.
Referenced by Backspace(), Delete(), and DeleteRange().
RemoveLine() [2/2]
void TextEditor::RemoveLine (int aIndex) private
Definition at line 527 of file text_editor.cc.
References mBreakpoints, mErrorMarkers, mLines, mReadOnly, and mTextChanged.
InsertLine()
TextEditor::Line & TextEditor::InsertLine (int aIndex) private
Definition at line 553 of file text_editor.cc.
References mBreakpoints, mErrorMarkers, mLines, and mReadOnly.
Referenced by EnterCharacter(), and InsertTextAt().
EnterCharacter()
void TextEditor::EnterCharacter (ImWchar aChar, bool aShift) private
Definition at line 1133 of file text_editor.cc.
References AddUndo(), Background, Colorize(), Default, DeleteSelection(), EnsureCursorVisible(), GetActualCursorCoordinates(), GetCharacterColumn(), GetCharacterIndex(), GetLineMaxColumn(), GetSelectedText(), GetText(), HasSelection(), InsertLine(), TextEditor::UndoRecord::mAdded, TextEditor::UndoRecord::mAddedEnd, TextEditor::UndoRecord::mAddedStart, TextEditor::UndoRecord::mAfter, TextEditor::LanguageDefinition::mAutoIndentation, TextEditor::UndoRecord::mBefore, TextEditor::EditorState::mCursorPosition, mLanguageDefinition, TextEditor::Coordinates::mLine, mLines, mOverwrite, mReadOnly, TextEditor::UndoRecord::mRemoved, TextEditor::UndoRecord::mRemovedEnd, TextEditor::UndoRecord::mRemovedStart, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mState, mTabSize, mTextChanged, and SetCursorPosition().
Referenced by HandleKeyboardInputs().
Backspace()
void TextEditor::Backspace () private
Definition at line 1651 of file text_editor.cc.
References AddUndo(), Advance(), Colorize(), DeleteSelection(), EnsureCursorVisible(), GetActualCursorCoordinates(), GetCharacterIndex(), GetLineMaxColumn(), GetSelectedText(), HasSelection(), TextEditor::UndoRecord::mAfter, TextEditor::UndoRecord::mBefore, TextEditor::Coordinates::mColumn, TextEditor::EditorState::mCursorPosition, mErrorMarkers, TextEditor::Coordinates::mLine, mLines, mReadOnly, TextEditor::UndoRecord::mRemoved, TextEditor::UndoRecord::mRemovedEnd, TextEditor::UndoRecord::mRemovedStart, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mState, mTextChanged, RemoveLine(), and SetCursorPosition().
Referenced by HandleKeyboardInputs().
DeleteSelection()
void TextEditor::DeleteSelection () private
Definition at line 1373 of file text_editor.cc.
References Colorize(), DeleteRange(), TextEditor::Coordinates::mLine, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mState, SetCursorPosition(), and SetSelection().
Referenced by Backspace(), Cut(), Delete(), EnterCharacter(), and Paste().
GetWordUnderCursor()
std::string TextEditor::GetWordUnderCursor () const private
Definition at line 571 of file text_editor.cc.
References GetCursorPosition(), and GetWordAt().
GetWordAt()
std::string TextEditor::GetWordAt (const Coordinates & aCoords) const private
Definition at line 576 of file text_editor.cc.
References FindWordEnd(), FindWordStart(), GetCharacterIndex(), TextEditor::Coordinates::mLine, and mLines.
Referenced by GetWordUnderCursor(), and Render().
GetGlyphColor()
ImU32 TextEditor::GetGlyphColor (const Glyph & aGlyph) const private
Definition at line 591 of file text_editor.cc.
References Comment, Default, TextEditor::Glyph::mColorIndex, mColorizerEnabled, TextEditor::Glyph::mComment, TextEditor::Glyph::mMultiLineComment, mPalette, TextEditor::Glyph::mPreprocessor, MultiLineComment, and Preprocessor.
Referenced by Render().
HandleKeyboardInputs()
void TextEditor::HandleKeyboardInputs () private
Definition at line 608 of file text_editor.cc.
References Backspace(), Copy(), Cut(), Delete(), EnterCharacter(), GetPageSize(), IsReadOnly(), MoveBottom(), MoveDown(), MoveEnd(), MoveHome(), MoveLeft(), MoveRight(), mOverwrite, MoveTop(), MoveUp(), Paste(), Redo(), SelectAll(), and Undo().
Referenced by Render().
HandleMouseInputs()
void TextEditor::HandleMouseInputs () private
Definition at line 692 of file text_editor.cc.
References Line, TextEditor::EditorState::mCursorPosition, mInteractiveEnd, mInteractiveStart, mLastClick, mSelectionMode, mState, Normal, ScreenPosToCoordinates(), SetSelection(), and Word.
Referenced by Render().
Render() [2/2]
void TextEditor::Render () private
Definition at line 765 of file text_editor.cc.
References Breakpoint, CurrentLineEdge, CurrentLineFill, CurrentLineFillInactive, Cursor, Default, EnsureCursorVisible(), ErrorMarker, GetCharacterIndex(), GetGlyphColor(), GetLineMaxColumn(), GetWordAt(), HasSelection(), LineNumber, Max, mBreakpoints, mCharAdvance, TextEditor::EditorState::mCursorPosition, mErrorMarkers, TextEditor::LanguageDefinition::mIdentifiers, mLanguageDefinition, mLeftMargin, TextEditor::Coordinates::mLine, mLineBuffer, mLines, mLineSpacing, mOverwrite, mPalette, mPaletteBase, TextEditor::LanguageDefinition::mPreprocIdentifiers, mScrollToCursor, mScrollToTop, TextEditor::EditorState::mSelectionEnd, TextEditor::EditorState::mSelectionStart, mShowWhitespaces, mStartTime, mState, mTabSize, mTextStart, ScreenPosToCoordinates(), Selection, and TextDistanceToLineStart().
Referenced by Render().
Member Data Documentation
mLineSpacing
float TextEditor::mLineSpacing private
Definition at line 346 of file text_editor.h.
Referenced by Render().
mLines
Lines TextEditor::mLines private
Definition at line 347 of file text_editor.h.
Referenced by Advance(), Backspace(), Colorize(), ColorizeInternal(), ColorizeRange(), Copy(), Delete(), DeleteRange(), EnterCharacter(), FindNextWord(), FindWordEnd(), FindWordStart(), GetCharacterColumn(), GetCharacterIndex(), GetLineCharacterCount(), GetLineMaxColumn(), GetText(), GetText(), GetTextLines(), GetTotalLines(), GetWordAt(), InsertLine(), InsertTextAt(), IsOnWordBoundary(), MoveDown(), MoveLeft(), MoveRight(), RemoveLine(), RemoveLine(), Render(), SanitizeCoordinates(), ScreenPosToCoordinates(), SelectAll(), SetSelection(), SetText(), SetTextLines(), TextDistanceToLineStart(), and TextEditor().
mState
EditorState TextEditor::mState private
Definition at line 348 of file text_editor.h.
Referenced by Backspace(), Cut(), Delete(), DeleteSelection(), EnterCharacter(), GetActualCursorCoordinates(), GetCurrentLineText(), GetSelectedText(), HandleMouseInputs(), HasSelection(), InsertText(), MoveDown(), MoveEnd(), MoveHome(), MoveLeft(), MoveRight(), MoveTop(), MoveUp(), Paste(), TextEditor::UndoRecord::Redo(), Render(), SetCursorPosition(), SetSelection(), SetSelectionEnd(), SetSelectionStart(), and TextEditor::UndoRecord::Undo().
mUndoBuffer
UndoBuffer TextEditor::mUndoBuffer private
Definition at line 349 of file text_editor.h.
Referenced by AddUndo(), CanRedo(), Redo(), SetText(), SetTextLines(), and Undo().
mUndoIndex
int TextEditor::mUndoIndex private
Definition at line 350 of file text_editor.h.
Referenced by AddUndo(), CanRedo(), CanUndo(), Redo(), SetText(), SetTextLines(), and Undo().
mTabSize
int TextEditor::mTabSize private
Definition at line 352 of file text_editor.h.
Referenced by EnterCharacter(), GetCharacterColumn(), GetCharacterIndex(), GetLineMaxColumn(), GetTabSize(), Render(), ScreenPosToCoordinates(), SetTabSize(), and TextDistanceToLineStart().
mOverwrite
bool TextEditor::mOverwrite private
Definition at line 353 of file text_editor.h.
Referenced by EnterCharacter(), HandleKeyboardInputs(), IsOverwrite(), and Render().
mReadOnly
bool TextEditor::mReadOnly private
Definition at line 354 of file text_editor.h.
Referenced by AddUndo(), Backspace(), CanRedo(), CanUndo(), Delete(), DeleteRange(), EnterCharacter(), InsertLine(), InsertTextAt(), IsReadOnly(), RemoveLine(), RemoveLine(), and SetReadOnly().
mWithinRender
bool TextEditor::mWithinRender private
Definition at line 355 of file text_editor.h.
Referenced by EnsureCursorVisible(), and Render().
mScrollToCursor
bool TextEditor::mScrollToCursor private
Definition at line 356 of file text_editor.h.
Referenced by EnsureCursorVisible(), and Render().
mScrollToTop
bool TextEditor::mScrollToTop private
Definition at line 357 of file text_editor.h.
Referenced by Render(), SetText(), and SetTextLines().
mTextChanged
bool TextEditor::mTextChanged private
Definition at line 358 of file text_editor.h.
Referenced by Backspace(), Delete(), DeleteRange(), EnterCharacter(), InsertTextAt(), IsTextChanged(), RemoveLine(), RemoveLine(), Render(), SetText(), and SetTextLines().
mColorizerEnabled
bool TextEditor::mColorizerEnabled private
Definition at line 359 of file text_editor.h.
Referenced by ColorizeInternal(), GetGlyphColor(), IsColorizerEnabled(), IsOnWordBoundary(), and SetColorizerEnable().
mTextStart
float TextEditor::mTextStart private
Definition at line 360 of file text_editor.h.
Referenced by EnsureCursorVisible(), Render(), and ScreenPosToCoordinates().
mLeftMargin
int TextEditor::mLeftMargin private
Definition at line 362 of file text_editor.h.
Referenced by Render().
mCursorPositionChanged
bool TextEditor::mCursorPositionChanged private
Definition at line 363 of file text_editor.h.
Referenced by IsCursorPositionChanged(), Render(), SetCursorPosition(), and SetSelection().
mColorRangeMin
int TextEditor::mColorRangeMin private
Definition at line 364 of file text_editor.h.
Referenced by Colorize(), and ColorizeInternal().
mColorRangeMax
int TextEditor::mColorRangeMax private
Definition at line 364 of file text_editor.h.
Referenced by Colorize(), and ColorizeInternal().
mSelectionMode
SelectionMode TextEditor::mSelectionMode private
Definition at line 365 of file text_editor.h.
Referenced by HandleMouseInputs().
mHandleKeyboardInputs
bool TextEditor::mHandleKeyboardInputs private
Definition at line 366 of file text_editor.h.
Referenced by IsHandleKeyboardInputsEnabled(), IsHandleMouseInputsEnabled(), Render(), and SetHandleKeyboardInputs().
mHandleMouseInputs
bool TextEditor::mHandleMouseInputs private
Definition at line 367 of file text_editor.h.
Referenced by Render(), and SetHandleMouseInputs().
mIgnoreImGuiChild
bool TextEditor::mIgnoreImGuiChild private
Definition at line 368 of file text_editor.h.
Referenced by IsImGuiChildIgnored(), Render(), and SetImGuiChildIgnored().
mShowWhitespaces
bool TextEditor::mShowWhitespaces private
Definition at line 369 of file text_editor.h.
Referenced by IsShowingWhitespaces(), Render(), and SetShowWhitespaces().
mPaletteBase
Palette TextEditor::mPaletteBase private
Definition at line 371 of file text_editor.h.
Referenced by GetPalette(), Render(), and SetPalette().
mPalette
Palette TextEditor::mPalette private
Definition at line 372 of file text_editor.h.
Referenced by GetGlyphColor(), Render(), and Render().
mLanguageDefinition
LanguageDefinition TextEditor::mLanguageDefinition private
Definition at line 373 of file text_editor.h.
Referenced by ColorizeInternal(), ColorizeRange(), EnterCharacter(), GetLanguageDefinition(), Render(), and SetLanguageDefinition().
mRegexList
RegexList TextEditor::mRegexList private
Definition at line 374 of file text_editor.h.
Referenced by ColorizeRange(), and SetLanguageDefinition().
mCheckComments
bool TextEditor::mCheckComments private
Definition at line 376 of file text_editor.h.
Referenced by Colorize(), and ColorizeInternal().
mBreakpoints
Breakpoints TextEditor::mBreakpoints private
Definition at line 377 of file text_editor.h.
Referenced by InsertLine(), RemoveLine(), RemoveLine(), Render(), and SetBreakpoints().
mErrorMarkers
ErrorMarkers TextEditor::mErrorMarkers private
Definition at line 378 of file text_editor.h.
Referenced by Backspace(), InsertLine(), RemoveLine(), RemoveLine(), Render(), and SetErrorMarkers().
mCharAdvance
ImVec2 TextEditor::mCharAdvance private
Definition at line 379 of file text_editor.h.
Referenced by EnsureCursorVisible(), GetPageSize(), Render(), and ScreenPosToCoordinates().
mInteractiveStart
Coordinates TextEditor::mInteractiveStart private
Definition at line 380 of file text_editor.h.
Referenced by HandleMouseInputs(), MoveDown(), MoveEnd(), MoveHome(), MoveLeft(), MoveRight(), MoveTop(), and MoveUp().
mInteractiveEnd
Coordinates TextEditor::mInteractiveEnd private
Definition at line 380 of file text_editor.h.
Referenced by HandleMouseInputs(), MoveDown(), MoveEnd(), MoveHome(), MoveLeft(), MoveRight(), MoveTop(), and MoveUp().
mLineBuffer
std::string TextEditor::mLineBuffer private
Definition at line 381 of file text_editor.h.
Referenced by Render().
mStartTime
uint64_t TextEditor::mStartTime private
Definition at line 382 of file text_editor.h.
Referenced by Render().
mLastClick
float TextEditor::mLastClick private
Definition at line 384 of file text_editor.h.
Referenced by HandleMouseInputs().
The documentation for this class was generated from the following files:
src/app/gui/modules/text_editor.h
src/app/gui/modules/text_editor.cc