yaze: yaze::cli::agent::SimpleChatSession Class Reference
yaze::cli::agent::SimpleChatSession Class Reference
Simple text-based chat session for AI agent interaction.
#include <simple_chat_session.h>
Public Member Functions
SimpleChatSession ()
void SetRomContext (Rom *rom)
void SetConfig (const AgentConfig &config)
absl::Status SendAndWaitForResponse (const std::string &message, std::string *response_out=nullptr)
absl::Status RunInteractive ()
absl::Status RunBatch (const std::string &input_file)
const std::vector< ChatMessage > & GetHistory () const
void Reset ()
Private Member Functions
void PrintMessage (const ChatMessage &msg, bool show_timestamp=false)
void PrintTable (const ChatMessage::TableData &table)
Private Attributes
ConversationalAgentService agent_service_
AgentConfig config_
Detailed Description
Simple text-based chat session for AI agent interaction.
Provides a basic REPL-style interface without FTXUI dependencies, suitable for automated testing and AI agent interactions.
Supports multiple input modes:
Interactive REPL (default when stdin is a TTY)
Piped input (reads lines from stdin)
Batch file (reads lines from file)
Single message (programmatic use)
Definition at line 30 of file simple_chat_session.h.
Constructor & Destructor Documentation
SimpleChatSession()
yaze::cli::agent::SimpleChatSession::SimpleChatSession () default
Member Function Documentation
SetRomContext()
void yaze::cli::agent::SimpleChatSession::SetRomContext (Rom * rom)
Definition at line 29 of file simple_chat_session.cc.
References agent_service_, and yaze::cli::agent::ConversationalAgentService::SetRomContext().
Referenced by yaze::cli::agent::HandleSimpleChatCommand().
SetConfig()
void yaze::cli::agent::SimpleChatSession::SetConfig (const AgentConfig & config) inline
Definition at line 38 of file simple_chat_session.h.
References agent_service_, config_, and yaze::cli::agent::ConversationalAgentService::SetConfig().
Referenced by yaze::cli::agent::HandleSimpleChatCommand().
SendAndWaitForResponse()
absl::Status yaze::cli::agent::SimpleChatSession::SendAndWaitForResponse (const std::string & message, std::string * response_out = nullptr)
Definition at line 307 of file simple_chat_session.cc.
References agent_service_, and yaze::cli::agent::ConversationalAgentService::SendMessage().
Referenced by yaze::cli::agent::HandleSimpleChatCommand().
RunInteractive()
absl::Status yaze::cli::agent::SimpleChatSession::RunInteractive ()
Definition at line 323 of file simple_chat_session.cc.
References agent_service_, config_, yaze::cli::agent::ConversationalAgentService::GetMetrics(), yaze::cli::agent::kCompact, yaze::cli::agent::kFriendly, yaze::cli::agent::kJson, yaze::cli::agent::kMarkdown, yaze::cli::agent::AgentConfig::output_format, PrintMessage(), Reset(), yaze::cli::agent::ConversationalAgentService::SendMessage(), and yaze::cli::agent::ChatMessage::SessionMetrics::turn_index.
Referenced by yaze::cli::agent::HandleSimpleChatCommand().
RunBatch()
absl::Status yaze::cli::agent::SimpleChatSession::RunBatch (const std::string & input_file)
Definition at line 420 of file simple_chat_session.cc.
References agent_service_, config_, yaze::cli::agent::ConversationalAgentService::GetMetrics(), yaze::cli::agent::kCompact, yaze::cli::agent::kFriendly, yaze::cli::agent::kJson, yaze::cli::agent::kMarkdown, yaze::cli::agent::AgentConfig::output_format, PrintMessage(), yaze::cli::agent::ConversationalAgentService::SendMessage(), and yaze::cli::agent::ChatMessage::SessionMetrics::turn_index.
GetHistory()
const std::vector< ChatMessage > & yaze::cli::agent::SimpleChatSession::GetHistory () const inline
Definition at line 55 of file simple_chat_session.h.
References agent_service_, and yaze::cli::agent::ConversationalAgentService::GetHistory().
Reset()
void yaze::cli::agent::SimpleChatSession::Reset () inline
Definition at line 60 of file simple_chat_session.h.
References agent_service_, and yaze::cli::agent::ConversationalAgentService::ResetConversation().
Referenced by RunInteractive().
PrintMessage()
void yaze::cli::agent::SimpleChatSession::PrintMessage (const ChatMessage & msg, bool show_timestamp = false) private
Definition at line 233 of file simple_chat_session.cc.
References config_, yaze::cli::agent::ChatMessage::json_pretty, yaze::cli::agent::kCompact, yaze::cli::agent::kFriendly, yaze::cli::agent::kJson, yaze::cli::agent::kMarkdown, yaze::cli::agent::ChatMessage::kUser, yaze::cli::agent::ChatMessage::message, yaze::cli::agent::ChatMessage::metrics, yaze::cli::agent::AgentConfig::output_format, PrintTable(), yaze::cli::agent::ChatMessage::sender, yaze::cli::agent::ChatMessage::table_data, and yaze::cli::agent::ChatMessage::timestamp.
Referenced by RunBatch(), and RunInteractive().
PrintTable()
void yaze::cli::agent::SimpleChatSession::PrintTable (const ChatMessage::TableData & table) private
Definition at line 197 of file simple_chat_session.cc.
References yaze::cli::agent::ChatMessage::TableData::headers, and yaze::cli::agent::ChatMessage::TableData::rows.
Referenced by PrintMessage().
Member Data Documentation
agent_service_
ConversationalAgentService yaze::cli::agent::SimpleChatSession::agent_service_ private
Definition at line 68 of file simple_chat_session.h.
Referenced by GetHistory(), Reset(), RunBatch(), RunInteractive(), SendAndWaitForResponse(), SetConfig(), and SetRomContext().
config_
AgentConfig yaze::cli::agent::SimpleChatSession::config_ private
Definition at line 69 of file simple_chat_session.h.
Referenced by PrintMessage(), RunBatch(), RunInteractive(), and SetConfig().
The documentation for this class was generated from the following files:
src/cli/service/agent/simple_chat_session.h
src/cli/service/agent/simple_chat_session.cc