yaze: yaze::editor::Editor Class Reference
yaze::editor::Editor Class Reference abstract
Interface for editor classes.
#include <editor.h>
Inherited by yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::SettingsEditor, yaze::editor::SpriteEditor, and yaze::test::TestEditor.
Public Member Functions
Editor ()=default
virtual ~Editor ()=default
virtual void Initialize ()=0
virtual absl::Status Load ()=0
virtual absl::Status Save ()=0
virtual absl::Status Update ()=0
virtual absl::Status Cut ()=0
virtual absl::Status Copy ()=0
virtual absl::Status Paste ()=0
virtual absl::Status Undo ()=0
virtual absl::Status Redo ()=0
virtual absl::Status Find ()=0
virtual absl::Status Clear ()
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
virtual bool IsRomLoaded () const
virtual std::string GetRomStatus () const
Protected Member Functions
std::string MakeCardTitle (const std::string &base_title) const
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Detailed Description
Interface for editor classes.
Provides basic editing operations that each editor should implement.
Definition at line 80 of file editor.h.
Constructor & Destructor Documentation
Editor()
yaze::editor::Editor::Editor () default
~Editor()
virtual yaze::editor::Editor::~Editor () virtual default
Member Function Documentation
Initialize()
virtual void yaze::editor::Editor::Initialize () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::test::EditorIntegrationTest::TestEditorInitialize().
Load()
virtual absl::Status yaze::editor::Editor::Load () pure virtual
Implemented in yaze::editor::DungeonEditorV2, yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::test::EditorIntegrationTest::TestEditorLoad().
Save()
virtual absl::Status yaze::editor::Editor::Save () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::test::EditorIntegrationTest::TestEditorSave().
Update()
virtual absl::Status yaze::editor::Editor::Update () pure virtual
Implemented in yaze::editor::OverworldEditor, yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::test::EditorIntegrationTest::TestEditorUpdate().
Cut()
virtual absl::Status yaze::editor::Editor::Cut () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::Initialize(), and yaze::test::EditorIntegrationTest::TestEditorCut().
Copy()
virtual absl::Status yaze::editor::Editor::Copy () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::Initialize(), and yaze::test::EditorIntegrationTest::TestEditorCopy().
Paste()
virtual absl::Status yaze::editor::Editor::Paste () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::Initialize(), and yaze::test::EditorIntegrationTest::TestEditorPaste().
Undo()
virtual absl::Status yaze::editor::Editor::Undo () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::Initialize(), and yaze::test::EditorIntegrationTest::TestEditorUndo().
Redo()
virtual absl::Status yaze::editor::Editor::Redo () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::Initialize(), and yaze::test::EditorIntegrationTest::TestEditorRedo().
Find()
virtual absl::Status yaze::editor::Editor::Find () pure virtual
Implemented in yaze::editor::AgentEditor, yaze::editor::AssemblyEditor, yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::GraphicsEditor, yaze::editor::PaletteEditor, yaze::editor::ScreenEditor, yaze::editor::MessageEditor, yaze::editor::MusicEditor, yaze::editor::OverworldEditor, yaze::editor::SpriteEditor, yaze::editor::SettingsEditor, and yaze::test::TestEditor.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::Initialize(), and yaze::test::EditorIntegrationTest::TestEditorFind().
Clear()
virtual absl::Status yaze::editor::Editor::Clear () inline virtual
Reimplemented in yaze::editor::OverworldEditor.
Definition at line 106 of file editor.h.
Referenced by yaze::test::EditorIntegrationTest::TestEditorClear().
type()
EditorType yaze::editor::Editor::type () const inline
Definition at line 108 of file editor.h.
References type_.
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
set_context()
void yaze::editor::Editor::set_context (EditorContext * context) inline
Definition at line 110 of file editor.h.
References context_.
active()
bool * yaze::editor::Editor::active () inline
Definition at line 112 of file editor.h.
References active_.
Referenced by set_active(), yaze::editor::AgentEditor::SetChatActive(), and yaze::editor::GraphicsEditor::UpdateGfxTabView().
set_active()
void yaze::editor::Editor::set_active (bool active) inline
Definition at line 113 of file editor.h.
References active(), and active_.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::Initialize(), yaze::editor::EditorManager::LoadDesignerLayout(), yaze::editor::EditorManager::LoadDeveloperLayout(), yaze::editor::EditorManager::LoadModderLayout(), and yaze::editor::EditorManager::Update().
IsRomLoaded()
virtual bool yaze::editor::Editor::IsRomLoaded () const inline virtual
Reimplemented in yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, yaze::editor::OverworldEditor, and yaze::editor::SettingsEditor.
Definition at line 116 of file editor.h.
Referenced by SafeRomAccess().
GetRomStatus()
virtual std::string yaze::editor::Editor::GetRomStatus () const inline virtual
Reimplemented in yaze::editor::DungeonEditor, yaze::editor::DungeonEditorV2, and yaze::editor::OverworldEditor.
Definition at line 117 of file editor.h.
MakeCardTitle()
std::string yaze::editor::Editor::MakeCardTitle (const std::string & base_title) const inline protected
Definition at line 125 of file editor.h.
References context_, and yaze::editor::EditorContext::session_id.
Referenced by yaze::editor::DungeonEditorV2::DrawEntrancesListCard(), yaze::editor::DungeonEditorV2::DrawLayout(), yaze::editor::DungeonEditorV2::DrawRoomGraphicsCard(), yaze::editor::DungeonEditorV2::DrawRoomMatrixCard(), yaze::editor::DungeonEditorV2::DrawRoomsListCard(), yaze::editor::OverworldEditor::Update(), yaze::editor::GraphicsEditor::Update(), yaze::editor::ScreenEditor::Update(), yaze::editor::SpriteEditor::Update(), and yaze::editor::AssemblyEditor::UpdateCodeView().
SafeRomAccess()
template<typename T > absl::StatusOr< T > yaze::editor::Editor::SafeRomAccess (std::function< T()> accessor, const std::string & operation = "") const inline protected
Definition at line 134 of file editor.h.
References IsRomLoaded().
Member Data Documentation
active_
bool yaze::editor::Editor::active_ = false protected
Definition at line 120 of file editor.h.
Referenced by active(), yaze::editor::AgentEditor::DrawDashboard(), set_active(), and yaze::editor::AgentEditor::Update().
type_
EditorType yaze::editor::Editor::type_ protected
Definition at line 121 of file editor.h.
Referenced by yaze::editor::AgentEditor::AgentEditor(), yaze::editor::AssemblyEditor::AssemblyEditor(), yaze::editor::DungeonEditor::DungeonEditor(), yaze::editor::DungeonEditorV2::DungeonEditorV2(), yaze::editor::GraphicsEditor::GraphicsEditor(), yaze::editor::MessageEditor::MessageEditor(), yaze::editor::MusicEditor::MusicEditor(), yaze::editor::OverworldEditor::OverworldEditor(), yaze::editor::PaletteEditor::PaletteEditor(), yaze::editor::ScreenEditor::ScreenEditor(), yaze::editor::SettingsEditor::SettingsEditor(), yaze::editor::SpriteEditor::SpriteEditor(), and type().
context_
EditorContext* yaze::editor::Editor::context_ = nullptr protected
Definition at line 122 of file editor.h.
Referenced by yaze::editor::OverworldEditor::Copy(), yaze::editor::MessageEditor::DrawExpandedMessageSettings(), yaze::editor::OverworldEditor::DrawScratchSpace(), yaze::editor::OverworldEditor::DrawScratchSpacePattern(), MakeCardTitle(), yaze::editor::OverworldEditor::Paste(), and set_context().
The documentation for this class was generated from the following file:
src/app/editor/editor.h