yaze: yaze::editor::MusicEditor Class Reference
yaze::editor::MusicEditor Class Reference
A class for editing music data in a Rom.
#include <music_editor.h>
Public Member Functions
MusicEditor (Rom *rom=nullptr)
void Initialize () override
absl::Status Load () override
absl::Status Save () override
absl::Status Update () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
void set_rom (Rom *rom)
Rom * rom () const
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Clear ()
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
virtual bool IsRomLoaded () const
virtual std::string GetRomStatus () const
Private Member Functions
void DrawTrackerView ()
void DrawInstrumentEditor ()
void DrawSampleEditor ()
void DrawToolset ()
void StartPlayback ()
void StopPlayback ()
void UpdatePlayback ()
Private Attributes
AssemblyEditor assembly_editor_
zelda3::music::Tracker music_tracker_
int current_song_index_ = 0
int current_pattern_index_ = 0
int current_channel_index_ = 0
bool is_playing_ = false
std::vector< bool > channel_muted_ = std::vector<bool>(8, false)
std::vector< bool > channel_soloed_ = std::vector<bool>(8, false)
std::vector< std::string > song_names_
ImGuiTableFlags music_editor_flags_
ImGuiTableFlags toolset_table_flags_
Rom * rom_
Additional Inherited Members
Protected Member Functions inherited from yaze::editor::Editor
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Detailed Description
A class for editing music data in a Rom.
Definition at line 58 of file music_editor.h.
Constructor & Destructor Documentation
MusicEditor()
yaze::editor::MusicEditor::MusicEditor (Rom * rom = nullptr) inline explicit
Definition at line 60 of file music_editor.h.
References yaze::editor::kMusic, and yaze::editor::Editor::type_.
Member Function Documentation
Initialize()
void yaze::editor::MusicEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 13 of file music_editor.cc.
Load()
absl::Status yaze::editor::MusicEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 15 of file music_editor.cc.
Referenced by yaze::editor::EditorManager::LoadAssets().
Save()
absl::Status yaze::editor::MusicEditor::Save () inline override virtual
Implements yaze::editor::Editor.
Definition at line 66 of file music_editor.h.
Update()
absl::Status yaze::editor::MusicEditor::Update () override virtual
Todo:
Add music channel view
Implements yaze::editor::Editor.
Definition at line 20 of file music_editor.cc.
References assembly_editor_, DrawToolset(), yaze::editor::AssemblyEditor::InlineUpdate(), and music_editor_flags_.
Cut()
absl::Status yaze::editor::MusicEditor::Cut () inline override virtual
Implements yaze::editor::Editor.
Definition at line 68 of file music_editor.h.
Copy()
absl::Status yaze::editor::MusicEditor::Copy () inline override virtual
Implements yaze::editor::Editor.
Definition at line 69 of file music_editor.h.
Paste()
absl::Status yaze::editor::MusicEditor::Paste () inline override virtual
Implements yaze::editor::Editor.
Definition at line 70 of file music_editor.h.
Undo()
absl::Status yaze::editor::MusicEditor::Undo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 71 of file music_editor.h.
Redo()
absl::Status yaze::editor::MusicEditor::Redo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 72 of file music_editor.h.
Find()
absl::Status yaze::editor::MusicEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 73 of file music_editor.h.
set_rom()
void yaze::editor::MusicEditor::set_rom (Rom * rom) inline
Definition at line 76 of file music_editor.h.
References rom(), and rom_.
rom()
Rom * yaze::editor::MusicEditor::rom () const inline
Definition at line 79 of file music_editor.h.
References rom_.
Referenced by DrawToolset(), and set_rom().
DrawTrackerView()
void yaze::editor::MusicEditor::DrawTrackerView () private
DrawInstrumentEditor()
void yaze::editor::MusicEditor::DrawInstrumentEditor () private
DrawSampleEditor()
void yaze::editor::MusicEditor::DrawSampleEditor () private
DrawToolset()
void yaze::editor::MusicEditor::DrawToolset () private
Definition at line 147 of file music_editor.cc.
References ICON_MD_ACCESS_TIME, ICON_MD_FAST_FORWARD, ICON_MD_FAST_REWIND, ICON_MD_PLAY_ARROW, ICON_MD_STOP, ICON_MD_VOLUME_UP, yaze::gui::ItemLabel(), yaze::zelda3::music::Tracker::LoadSongs(), music_tracker_, rom(), and toolset_table_flags_.
Referenced by Update().
StartPlayback()
void yaze::editor::MusicEditor::StartPlayback () private
StopPlayback()
void yaze::editor::MusicEditor::StopPlayback () private
UpdatePlayback()
void yaze::editor::MusicEditor::UpdatePlayback () private
Member Data Documentation
assembly_editor_
AssemblyEditor yaze::editor::MusicEditor::assembly_editor_ private
Definition at line 93 of file music_editor.h.
Referenced by Update().
music_tracker_
zelda3::music::Tracker yaze::editor::MusicEditor::music_tracker_ private
Definition at line 94 of file music_editor.h.
Referenced by DrawToolset().
current_song_index_
int yaze::editor::MusicEditor::current_song_index_ = 0 private
Definition at line 98 of file music_editor.h.
current_pattern_index_
int yaze::editor::MusicEditor::current_pattern_index_ = 0 private
Definition at line 99 of file music_editor.h.
current_channel_index_
int yaze::editor::MusicEditor::current_channel_index_ = 0 private
Definition at line 100 of file music_editor.h.
is_playing_
bool yaze::editor::MusicEditor::is_playing_ = false private
Definition at line 101 of file music_editor.h.
channel_muted_
std::vector<bool> yaze::editor::MusicEditor::channel_muted_ = std::vector<bool>(8, false) private
Definition at line 102 of file music_editor.h.
channel_soloed_
std::vector<bool> yaze::editor::MusicEditor::channel_soloed_ = std::vector<bool>(8, false) private
Definition at line 103 of file music_editor.h.
song_names_
std::vector<std::string> yaze::editor::MusicEditor::song_names_ private
Definition at line 104 of file music_editor.h.
music_editor_flags_
ImGuiTableFlags yaze::editor::MusicEditor::music_editor_flags_ private
Initial value:
=
      ImGuiTableFlags_Resizable | ImGuiTableFlags_BordersOuter |
      ImGuiTableFlags_BordersV | ImGuiTableFlags_SizingFixedFit
Definition at line 106 of file music_editor.h.
Referenced by Update().
toolset_table_flags_
ImGuiTableFlags yaze::editor::MusicEditor::toolset_table_flags_ private
Initial value:
=
      ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_BordersOuter |
      ImGuiTableFlags_BordersV | ImGuiTableFlags_PadOuterX
Definition at line 110 of file music_editor.h.
Referenced by DrawToolset().
rom_
Rom* yaze::editor::MusicEditor::rom_ private
Definition at line 114 of file music_editor.h.
Referenced by rom(), and set_rom().
The documentation for this class was generated from the following files:
src/app/editor/music/music_editor.h
src/app/editor/music/music_editor.cc