yaze: yaze::cli::anonymous_namespace{agent.cc} Namespace Reference
yaze::cli::anonymous_namespace{agent.cc} Namespace Reference
Classes
struct DescribeOptions
Functions
std::string FormatOptionalTime (const std::optional< absl::Time > &time)
std::string TestRunStatusToString (TestRunStatus status)
bool IsTerminalStatus (TestRunStatus status)
std::optional< TestRunStatus > ParseStatusFilter (absl::string_view value)
std::string HarnessAddress (const std::string &host, int port)
std::string JsonEscape (absl::string_view value)
std::string YamlQuote (absl::string_view value)
absl::StatusOr< DescribeOptions > ParseDescribeArgs (const std::vector< std::string > &args)
absl::Status HandleRunCommand (const std::vector< std::string > &arg_vec, Rom &rom)
absl::Status HandlePlanCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleDiffCommand (Rom &rom, const std::vector< std::string > &args)
absl::Status HandleTestRunCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestStatusCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestListCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestResultsCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleLearnCommand ()
absl::Status HandleListCommand ()
absl::Status HandleCommitCommand (Rom &rom)
absl::Status HandleRevertCommand (Rom &rom)
absl::Status HandleDescribeCommand (const std::vector< std::string > &arg_vec)
Function Documentation
FormatOptionalTime()
std::string yaze::cli::anonymous_namespace{agent.cc}::FormatOptionalTime (const std::optional< absl::Time > & time)
Definition at line 58 of file agent.cc.
References FormatOptionalTime().
Referenced by FormatOptionalTime(), HandleTestListCommand(), HandleTestResultsCommand(), and HandleTestStatusCommand().
TestRunStatusToString()
std::string yaze::cli::anonymous_namespace{agent.cc}::TestRunStatusToString (TestRunStatus status)
Definition at line 65 of file agent.cc.
References yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kQueued, yaze::cli::kRunning, yaze::cli::kTimeout, yaze::cli::kUnknown, and TestRunStatusToString().
Referenced by HandleTestListCommand(), HandleTestStatusCommand(), and TestRunStatusToString().
IsTerminalStatus()
bool yaze::cli::anonymous_namespace{agent.cc}::IsTerminalStatus (TestRunStatus status)
Definition at line 83 of file agent.cc.
References IsTerminalStatus(), yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kQueued, yaze::cli::kRunning, yaze::cli::kTimeout, and yaze::cli::kUnknown.
Referenced by HandleTestStatusCommand(), and IsTerminalStatus().
ParseStatusFilter()
std::optional< TestRunStatus > yaze::cli::anonymous_namespace{agent.cc}::ParseStatusFilter (absl::string_view value)
Definition at line 97 of file agent.cc.
References yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kQueued, yaze::cli::kRunning, yaze::cli::kTimeout, yaze::cli::kUnknown, and ParseStatusFilter().
Referenced by HandleTestListCommand(), and ParseStatusFilter().
HarnessAddress()
std::string yaze::cli::anonymous_namespace{agent.cc}::HarnessAddress (const std::string & host, int port)
Definition at line 108 of file agent.cc.
References HarnessAddress().
Referenced by HandleTestListCommand(), HandleTestResultsCommand(), HandleTestRunCommand(), HandleTestStatusCommand(), and HarnessAddress().
JsonEscape()
std::string yaze::cli::anonymous_namespace{agent.cc}::JsonEscape (absl::string_view value)
Definition at line 112 of file agent.cc.
References JsonEscape().
Referenced by HandleTestResultsCommand(), and JsonEscape().
YamlQuote()
std::string yaze::cli::anonymous_namespace{agent.cc}::YamlQuote (absl::string_view value)
Definition at line 149 of file agent.cc.
References YamlQuote().
Referenced by HandleTestResultsCommand(), and YamlQuote().
ParseDescribeArgs()
absl::StatusOr< DescribeOptions > yaze::cli::anonymous_namespace{agent.cc}::ParseDescribeArgs (const std::vector< std::string > & args)
Definition at line 155 of file agent.cc.
References ASSIGN_OR_RETURN, yaze::cli::anonymous_namespace{agent.cc}::DescribeOptions::format, yaze::cli::anonymous_namespace{agent.cc}::DescribeOptions::last_updated, yaze::cli::anonymous_namespace{agent.cc}::DescribeOptions::output_path, ParseDescribeArgs(), yaze::cli::anonymous_namespace{agent.cc}::DescribeOptions::resource, and yaze::cli::anonymous_namespace{agent.cc}::DescribeOptions::version.
Referenced by HandleDescribeCommand(), and ParseDescribeArgs().
HandleRunCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleRunCommand (const std::vector< std::string > & arg_vec, Rom & rom)
Definition at line 211 of file agent.cc.
References yaze::cli::ModernCLI::commands_, yaze::cli::ProposalRegistry::CreateProposal(), yaze::cli::RomSandboxManager::CreateSandbox(), yaze::cli::MockAIService::GetCommands(), HandleRunCommand(), yaze::cli::ProposalRegistry::Instance(), yaze::cli::RomSandboxManager::Instance(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), and RETURN_IF_ERROR.
Referenced by HandleRunCommand().
HandlePlanCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandlePlanCommand (const std::vector< std::string > & arg_vec)
Definition at line 321 of file agent.cc.
References yaze::cli::MockAIService::GetCommands(), and HandlePlanCommand().
Referenced by HandlePlanCommand().
HandleDiffCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleDiffCommand (Rom & rom, const std::vector< std::string > & args)
Definition at line 340 of file agent.cc.
References yaze::cli::RomSandboxManager::ActiveSandbox(), yaze::Rom::filename(), HandleDiffCommand(), yaze::cli::ProposalRegistry::Instance(), yaze::cli::RomSandboxManager::Instance(), yaze::Rom::is_loaded(), yaze::cli::ProposalRegistry::kAccepted, yaze::cli::ProposalRegistry::kPending, yaze::cli::ProposalRegistry::kRejected, and yaze::cli::RomDiff::Run().
Referenced by HandleDiffCommand().
HandleTestRunCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleTestRunCommand (const std::vector< std::string > & arg_vec)
Definition at line 457 of file agent.cc.
References yaze::cli::GuiAutomationClient::Assert(), yaze::cli::GuiAutomationClient::Click(), yaze::cli::GuiAutomationClient::Connect(), yaze::cli::TestWorkflowGenerator::GenerateWorkflow(), HandleTestRunCommand(), HarnessAddress(), yaze::cli::kAssert, yaze::cli::kClick, yaze::cli::kScreenshot, yaze::cli::kType, yaze::cli::kWait, yaze::cli::GuiAutomationClient::Screenshot(), yaze::cli::GuiAutomationClient::Type(), and yaze::cli::GuiAutomationClient::Wait().
Referenced by HandleTestCommand(), and HandleTestRunCommand().
HandleTestStatusCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleTestStatusCommand (const std::vector< std::string > & arg_vec)
Definition at line 605 of file agent.cc.
References ASSIGN_OR_RETURN, yaze::cli::GuiAutomationClient::Connect(), FormatOptionalTime(), yaze::cli::GuiAutomationClient::GetTestStatus(), HandleTestStatusCommand(), HarnessAddress(), IsTerminalStatus(), RETURN_IF_ERROR, and TestRunStatusToString().
Referenced by HandleTestCommand(), and HandleTestStatusCommand().
HandleTestListCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleTestListCommand (const std::vector< std::string > & arg_vec)
Definition at line 699 of file agent.cc.
References ASSIGN_OR_RETURN, yaze::cli::GuiAutomationClient::Connect(), FormatOptionalTime(), yaze::cli::GuiAutomationClient::GetTestStatus(), HandleTestListCommand(), HarnessAddress(), yaze::cli::GuiAutomationClient::ListTests(), ParseStatusFilter(), RETURN_IF_ERROR, and TestRunStatusToString().
Referenced by HandleTestCommand(), and HandleTestListCommand().
HandleTestResultsCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleTestResultsCommand (const std::vector< std::string > & arg_vec)
Definition at line 847 of file agent.cc.
References ASSIGN_OR_RETURN, yaze::cli::GuiAutomationClient::Connect(), FormatOptionalTime(), yaze::cli::GuiAutomationClient::GetTestResults(), HandleTestResultsCommand(), HarnessAddress(), JsonEscape(), RETURN_IF_ERROR, and YamlQuote().
Referenced by HandleTestCommand(), and HandleTestResultsCommand().
HandleTestCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleTestCommand (const std::vector< std::string > & arg_vec)
Definition at line 1035 of file agent.cc.
References HandleTestCommand(), HandleTestListCommand(), HandleTestResultsCommand(), HandleTestRunCommand(), and HandleTestStatusCommand().
Referenced by HandleTestCommand().
HandleLearnCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleLearnCommand ()
Definition at line 1054 of file agent.cc.
References HandleLearnCommand().
Referenced by HandleLearnCommand().
HandleListCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleListCommand ()
Definition at line 1059 of file agent.cc.
References HandleListCommand(), yaze::cli::ProposalRegistry::Instance(), yaze::cli::ProposalRegistry::kAccepted, yaze::cli::ProposalRegistry::kPending, and yaze::cli::ProposalRegistry::kRejected.
Referenced by HandleListCommand().
HandleCommitCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleCommitCommand (Rom & rom)
Definition at line 1099 of file agent.cc.
References HandleCommitCommand(), yaze::Rom::is_loaded(), and yaze::Rom::SaveToFile().
Referenced by HandleCommitCommand().
HandleRevertCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleRevertCommand (Rom & rom)
Definition at line 1112 of file agent.cc.
References yaze::Rom::filename(), HandleRevertCommand(), yaze::Rom::is_loaded(), and yaze::Rom::LoadFromFile().
Referenced by HandleRevertCommand().
HandleDescribeCommand()
absl::Status yaze::cli::anonymous_namespace{agent.cc}::HandleDescribeCommand (const std::vector< std::string > & arg_vec)
Definition at line 1125 of file agent.cc.
References ASSIGN_OR_RETURN, HandleDescribeCommand(), yaze::cli::ResourceCatalog::Instance(), and ParseDescribeArgs().
Referenced by HandleDescribeCommand().