yaze: yaze::cli::agent::EnhancedTUI Class Reference
yaze::cli::agent::EnhancedTUI Class Reference
Enhanced Terminal User Interface for z3ed CLI.
#include <enhanced_tui.h>
Classes
struct Layout
Public Member Functions
EnhancedTUI (const TUIConfig &config=TUIConfig{})
~EnhancedTUI ()
absl::Status Initialize ()
void Shutdown ()
void SetRomContext (Rom *rom)
absl::Status Run ()
void DisplayMessage (const std::string &message, const std::string &sender="User", bool is_error=false)
void DisplayToolOutput (const std::string &output, const std::string &tool_name)
void DisplaySuggestions (const std::vector< std::string > &suggestions)
void UpdateStatusBar (const std::string &status)
void ShowHelp (const std::string &command)
void RegisterCommand (const std::string &name, std::function< absl::Status(const std::vector< std::string > &)> handler, const std::string &description="")
const TUIConfig & GetConfig () const
void SetConfig (const TUIConfig &config)
Private Member Functions
void SetupTerminal ()
void RestoreTerminal ()
void ClearScreen ()
void RefreshDisplay ()
void CalculateLayout ()
void DrawHeader ()
void DrawCommandPalette ()
void DrawChatArea ()
void DrawToolOutput ()
void DrawStatusBar ()
void DrawSidebar ()
void DrawHelpPanel ()
absl::Status HandleInput ()
void HandleKeyPress (int key)
void HandleMouseEvent (int x, int y, int button)
void HandleNormalKey (int key)
void HandleCommandPaletteKey (int key)
void UpdatePaletteMatches ()
absl::Status ProcessCommand (const std::string &input)
std::vector< std::string > GetCommandSuggestions (const std::string &partial)
void ExecuteCommand (const std::string &command, const std::vector< std::string > &args)
TUIStyle GetStyle (TUIComponent component) const
std::string ApplyStyle (const std::string &text, const TUIStyle &style) const
void LoadTheme (TUITheme theme)
std::string FormatTimestamp () const
std::string TruncateText (const std::string &text, int max_width) const
std::vector< std::string > WrapText (const std::string &text, int width) const
Private Attributes
TUIConfig config_
Rom * rom_context_ = nullptr
int terminal_width_ = 80
int terminal_height_ = 24
bool terminal_initialized_ = false
struct yaze::cli::agent::EnhancedTUI::Layout layout_
std::string current_input_
std::vector< std::string > command_history_
std::vector< std::string > output_history_
std::map< std::string, std::function< absl::Status(const std::vector< std::string > &)> > commands_
std::map< std::string, std::string > command_descriptions_
std::map< TUIComponent, TUIStyle > styles_
std::map< TUITheme, std::map< TUIComponent, TUIStyle > > themes_
int cursor_x_ = 0
int cursor_y_ = 0
bool in_command_palette_ = false
std::string palette_filter_
std::vector< std::string > palette_matches_
int palette_selection_ = 0
Detailed Description
Enhanced Terminal User Interface for z3ed CLI.
Provides a modern, feature-rich TUI with:
Multi-panel layout with resizable components
Syntax highlighting for code and JSON
Fuzzy search and autocomplete
Command palette with shortcuts
Rich output formatting with colors and tables
Mouse support (optional)
Customizable themes
Real-time command suggestions
History navigation and search
Tool output integration
Context-sensitive help
Definition at line 99 of file enhanced_tui.h.
Constructor & Destructor Documentation
EnhancedTUI()
yaze::cli::agent::EnhancedTUI::EnhancedTUI (const TUIConfig & config = TUIConfig{}) explicit
Definition at line 137 of file enhanced_tui.cc.
References config_, LoadTheme(), and yaze::cli::agent::TUIConfig::theme.
~EnhancedTUI()
yaze::cli::agent::EnhancedTUI::~EnhancedTUI ()
Definition at line 141 of file enhanced_tui.cc.
References Shutdown().
Member Function Documentation
Initialize()
absl::Status yaze::cli::agent::EnhancedTUI::Initialize ()
Definition at line 145 of file enhanced_tui.cc.
References CalculateLayout(), SetupTerminal(), terminal_height_, terminal_initialized_, and terminal_width_.
Referenced by Run().
Shutdown()
void yaze::cli::agent::EnhancedTUI::Shutdown ()
Definition at line 163 of file enhanced_tui.cc.
References RestoreTerminal(), and terminal_initialized_.
Referenced by ~EnhancedTUI().
SetRomContext()
void yaze::cli::agent::EnhancedTUI::SetRomContext (Rom * rom)
Definition at line 172 of file enhanced_tui.cc.
References rom_context_.
Run()
absl::Status yaze::cli::agent::EnhancedTUI::Run ()
Definition at line 176 of file enhanced_tui.cc.
References ClearScreen(), HandleInput(), Initialize(), RefreshDisplay(), and RETURN_IF_ERROR.
DisplayMessage()
void yaze::cli::agent::EnhancedTUI::DisplayMessage (const std::string & message, const std::string & sender = "User", bool is_error = false)
Definition at line 190 of file enhanced_tui.cc.
References config_, FormatTimestamp(), yaze::cli::agent::TUIConfig::max_output_lines, and output_history_.
Referenced by ProcessCommand().
DisplayToolOutput()
void yaze::cli::agent::EnhancedTUI::DisplayToolOutput (const std::string & output, const std::string & tool_name)
Definition at line 218 of file enhanced_tui.cc.
References FormatTimestamp(), and output_history_.
Referenced by yaze::cli::agent::TUICommandHandler::DisplayRichOutput().
DisplaySuggestions()
void yaze::cli::agent::EnhancedTUI::DisplaySuggestions (const std::vector< std::string > & suggestions)
Definition at line 231 of file enhanced_tui.cc.
References output_history_.
UpdateStatusBar()
void yaze::cli::agent::EnhancedTUI::UpdateStatusBar (const std::string & status)
Definition at line 249 of file enhanced_tui.cc.
Referenced by yaze::cli::agent::TUICommandHandler::DisplayProgress().
ShowHelp()
void yaze::cli::agent::EnhancedTUI::ShowHelp (const std::string & command)
Definition at line 254 of file enhanced_tui.cc.
References command_descriptions_, commands_, and output_history_.
RegisterCommand()
void yaze::cli::agent::EnhancedTUI::RegisterCommand (const std::string & name, std::function< absl::Status(const std::vector< std::string > &)> handler, const std::string & description = "")
Definition at line 271 of file enhanced_tui.cc.
References command_descriptions_, and commands_.
GetConfig()
const TUIConfig & yaze::cli::agent::EnhancedTUI::GetConfig () const inline
Definition at line 140 of file enhanced_tui.h.
References config_.
SetConfig()
void yaze::cli::agent::EnhancedTUI::SetConfig (const TUIConfig & config)
Definition at line 278 of file enhanced_tui.cc.
References CalculateLayout(), config_, LoadTheme(), and yaze::cli::agent::TUIConfig::theme.
SetupTerminal()
void yaze::cli::agent::EnhancedTUI::SetupTerminal () private
Definition at line 284 of file enhanced_tui.cc.
Referenced by Initialize().
RestoreTerminal()
void yaze::cli::agent::EnhancedTUI::RestoreTerminal () private
Definition at line 289 of file enhanced_tui.cc.
Referenced by Shutdown().
ClearScreen()
void yaze::cli::agent::EnhancedTUI::ClearScreen () private
Definition at line 294 of file enhanced_tui.cc.
Referenced by Run().
RefreshDisplay()
void yaze::cli::agent::EnhancedTUI::RefreshDisplay () private
Definition at line 299 of file enhanced_tui.cc.
References DrawChatArea(), DrawCommandPalette(), DrawHeader(), DrawSidebar(), DrawStatusBar(), and DrawToolOutput().
Referenced by Run().
CalculateLayout()
void yaze::cli::agent::EnhancedTUI::CalculateLayout () private
Definition at line 312 of file enhanced_tui.cc.
References yaze::cli::agent::EnhancedTUI::Layout::chat_height, yaze::cli::agent::EnhancedTUI::Layout::header_height, yaze::cli::agent::EnhancedTUI::Layout::help_width, layout_, yaze::cli::agent::EnhancedTUI::Layout::sidebar_width, yaze::cli::agent::EnhancedTUI::Layout::status_height, terminal_height_, terminal_width_, and yaze::cli::agent::EnhancedTUI::Layout::tool_height.
Referenced by Initialize(), and SetConfig().
DrawHeader()
void yaze::cli::agent::EnhancedTUI::DrawHeader () private
Definition at line 321 of file enhanced_tui.cc.
References ApplyStyle(), config_, GetStyle(), yaze::cli::agent::kHeader, rom_context_, terminal_width_, yaze::cli::agent::TUIConfig::theme, and yaze::cli::agent::TUIThemeToString().
Referenced by RefreshDisplay().
DrawCommandPalette()
void yaze::cli::agent::EnhancedTUI::DrawCommandPalette () private
Definition at line 343 of file enhanced_tui.cc.
References ApplyStyle(), GetStyle(), in_command_palette_, yaze::cli::agent::kCommandPalette, palette_filter_, palette_matches_, and palette_selection_.
Referenced by RefreshDisplay().
DrawChatArea()
void yaze::cli::agent::EnhancedTUI::DrawChatArea () private
Definition at line 365 of file enhanced_tui.cc.
References ApplyStyle(), yaze::cli::agent::EnhancedTUI::Layout::chat_height, config_, current_input_, GetStyle(), yaze::cli::agent::EnhancedTUI::Layout::header_height, yaze::cli::agent::kChatArea, layout_, output_history_, yaze::cli::agent::TUIConfig::prompt_style, yaze::cli::agent::EnhancedTUI::Layout::sidebar_width, terminal_width_, and TruncateText().
Referenced by RefreshDisplay().
DrawToolOutput()
void yaze::cli::agent::EnhancedTUI::DrawToolOutput () private
Definition at line 393 of file enhanced_tui.cc.
Referenced by RefreshDisplay().
DrawStatusBar()
void yaze::cli::agent::EnhancedTUI::DrawStatusBar () private
Definition at line 398 of file enhanced_tui.cc.
References ApplyStyle(), command_history_, commands_, GetStyle(), in_command_palette_, yaze::cli::agent::kStatusBar, terminal_height_, and terminal_width_.
Referenced by RefreshDisplay().
DrawSidebar()
void yaze::cli::agent::EnhancedTUI::DrawSidebar () private
Definition at line 418 of file enhanced_tui.cc.
References ApplyStyle(), GetStyle(), yaze::cli::agent::EnhancedTUI::Layout::header_height, yaze::cli::agent::kSidebar, layout_, rom_context_, yaze::cli::agent::EnhancedTUI::Layout::sidebar_width, yaze::Rom::size(), and terminal_width_.
Referenced by RefreshDisplay().
DrawHelpPanel()
void yaze::cli::agent::EnhancedTUI::DrawHelpPanel () private
HandleInput()
absl::Status yaze::cli::agent::EnhancedTUI::HandleInput () private
Definition at line 447 of file enhanced_tui.cc.
References HandleKeyPress().
Referenced by Run().
HandleKeyPress()
void yaze::cli::agent::EnhancedTUI::HandleKeyPress (int key) private
Definition at line 455 of file enhanced_tui.cc.
References HandleCommandPaletteKey(), HandleNormalKey(), and in_command_palette_.
Referenced by HandleInput().
HandleMouseEvent()
void yaze::cli::agent::EnhancedTUI::HandleMouseEvent (int x, int y, int button) private
HandleNormalKey()
void yaze::cli::agent::EnhancedTUI::HandleNormalKey (int key) private
Definition at line 463 of file enhanced_tui.cc.
References command_history_, config_, current_input_, yaze::cli::agent::TUIConfig::enable_autocomplete, GetCommandSuggestions(), and ProcessCommand().
Referenced by HandleKeyPress().
HandleCommandPaletteKey()
void yaze::cli::agent::EnhancedTUI::HandleCommandPaletteKey (int key) private
Definition at line 500 of file enhanced_tui.cc.
References current_input_, in_command_palette_, palette_filter_, palette_matches_, palette_selection_, and UpdatePaletteMatches().
Referenced by HandleKeyPress().
UpdatePaletteMatches()
void yaze::cli::agent::EnhancedTUI::UpdatePaletteMatches () private
Definition at line 541 of file enhanced_tui.cc.
References commands_, palette_filter_, palette_matches_, and palette_selection_.
Referenced by HandleCommandPaletteKey().
ProcessCommand()
absl::Status yaze::cli::agent::EnhancedTUI::ProcessCommand (const std::string & input) private
Definition at line 554 of file enhanced_tui.cc.
References commands_, and DisplayMessage().
Referenced by HandleNormalKey().
GetCommandSuggestions()
std::vector< std::string > yaze::cli::agent::EnhancedTUI::GetCommandSuggestions (const std::string & partial) private
Definition at line 571 of file enhanced_tui.cc.
References commands_.
Referenced by HandleNormalKey().
ExecuteCommand()
void yaze::cli::agent::EnhancedTUI::ExecuteCommand (const std::string & command, const std::vector< std::string > & args) private
References GetStyle().
GetStyle()
TUIStyle yaze::cli::agent::EnhancedTUI::GetStyle (TUIComponent component) const private
Definition at line 584 of file enhanced_tui.cc.
References styles_.
Referenced by DrawChatArea(), DrawCommandPalette(), DrawHeader(), DrawSidebar(), DrawStatusBar(), and ExecuteCommand().
ApplyStyle()
std::string yaze::cli::agent::EnhancedTUI::ApplyStyle (const std::string & text, const TUIStyle & style) const private
Definition at line 594 of file enhanced_tui.cc.
References yaze::cli::agent::TUIStyle::background_color, yaze::cli::agent::TUIStyle::bold, yaze::cli::agent::TUIStyle::foreground_color, yaze::cli::agent::TUIStyle::italic, and yaze::cli::agent::TUIStyle::underline.
Referenced by DrawChatArea(), DrawCommandPalette(), DrawHeader(), DrawSidebar(), and DrawStatusBar().
LoadTheme()
void yaze::cli::agent::EnhancedTUI::LoadTheme (TUITheme theme) private
Definition at line 623 of file enhanced_tui.cc.
References yaze::cli::agent::kChatArea, yaze::cli::agent::kDark, yaze::cli::agent::kDefault, yaze::cli::agent::kHeader, yaze::cli::agent::kSidebar, yaze::cli::agent::kStatusBar, yaze::cli::agent::kZelda, LoadTheme(), and styles_.
Referenced by EnhancedTUI(), LoadTheme(), and SetConfig().
FormatTimestamp()
std::string yaze::cli::agent::EnhancedTUI::FormatTimestamp () const private
Definition at line 652 of file enhanced_tui.cc.
References config_, and yaze::cli::agent::TUIConfig::show_timestamps.
Referenced by DisplayMessage(), and DisplayToolOutput().
TruncateText()
std::string yaze::cli::agent::EnhancedTUI::TruncateText (const std::string & text, int max_width) const private
Definition at line 665 of file enhanced_tui.cc.
Referenced by DrawChatArea().
WrapText()
std::vector< std::string > yaze::cli::agent::EnhancedTUI::WrapText (const std::string & text, int width) const private
Definition at line 673 of file enhanced_tui.cc.
Member Data Documentation
config_
TUIConfig yaze::cli::agent::EnhancedTUI::config_ private
Definition at line 185 of file enhanced_tui.h.
Referenced by DisplayMessage(), DrawChatArea(), DrawHeader(), EnhancedTUI(), FormatTimestamp(), GetConfig(), HandleNormalKey(), and SetConfig().
rom_context_
Rom* yaze::cli::agent::EnhancedTUI::rom_context_ = nullptr private
Definition at line 186 of file enhanced_tui.h.
Referenced by DrawHeader(), DrawSidebar(), and SetRomContext().
terminal_width_
int yaze::cli::agent::EnhancedTUI::terminal_width_ = 80 private
Definition at line 189 of file enhanced_tui.h.
Referenced by CalculateLayout(), DrawChatArea(), DrawHeader(), DrawSidebar(), DrawStatusBar(), and Initialize().
terminal_height_
int yaze::cli::agent::EnhancedTUI::terminal_height_ = 24 private
Definition at line 190 of file enhanced_tui.h.
Referenced by CalculateLayout(), DrawStatusBar(), and Initialize().
terminal_initialized_
bool yaze::cli::agent::EnhancedTUI::terminal_initialized_ = false private
Definition at line 191 of file enhanced_tui.h.
Referenced by Initialize(), and Shutdown().
layout_
struct yaze::cli::agent::EnhancedTUI::Layout yaze::cli::agent::EnhancedTUI::layout_ private
Referenced by CalculateLayout(), DrawChatArea(), and DrawSidebar().
current_input_
std::string yaze::cli::agent::EnhancedTUI::current_input_ private
Definition at line 204 of file enhanced_tui.h.
Referenced by DrawChatArea(), HandleCommandPaletteKey(), and HandleNormalKey().
command_history_
std::vector<std::string> yaze::cli::agent::EnhancedTUI::command_history_ private
Definition at line 205 of file enhanced_tui.h.
Referenced by DrawStatusBar(), and HandleNormalKey().
output_history_
std::vector<std::string> yaze::cli::agent::EnhancedTUI::output_history_ private
Definition at line 206 of file enhanced_tui.h.
Referenced by DisplayMessage(), DisplaySuggestions(), DisplayToolOutput(), DrawChatArea(), and ShowHelp().
commands_
std::map<std::string, std::function<absl::Status(const std::vector<std::string>&)> > yaze::cli::agent::EnhancedTUI::commands_ private
Definition at line 207 of file enhanced_tui.h.
Referenced by DrawStatusBar(), GetCommandSuggestions(), ProcessCommand(), RegisterCommand(), ShowHelp(), and UpdatePaletteMatches().
command_descriptions_
std::map<std::string, std::string> yaze::cli::agent::EnhancedTUI::command_descriptions_ private
Definition at line 208 of file enhanced_tui.h.
Referenced by RegisterCommand(), and ShowHelp().
styles_
std::map<TUIComponent, TUIStyle> yaze::cli::agent::EnhancedTUI::styles_ private
Definition at line 211 of file enhanced_tui.h.
Referenced by GetStyle(), and LoadTheme().
themes_
std::map<TUITheme, std::map<TUIComponent, TUIStyle> > yaze::cli::agent::EnhancedTUI::themes_ private
Definition at line 212 of file enhanced_tui.h.
cursor_x_
int yaze::cli::agent::EnhancedTUI::cursor_x_ = 0 private
Definition at line 215 of file enhanced_tui.h.
cursor_y_
int yaze::cli::agent::EnhancedTUI::cursor_y_ = 0 private
Definition at line 216 of file enhanced_tui.h.
in_command_palette_
bool yaze::cli::agent::EnhancedTUI::in_command_palette_ = false private
Definition at line 217 of file enhanced_tui.h.
Referenced by DrawCommandPalette(), DrawStatusBar(), HandleCommandPaletteKey(), and HandleKeyPress().
palette_filter_
std::string yaze::cli::agent::EnhancedTUI::palette_filter_ private
Definition at line 218 of file enhanced_tui.h.
Referenced by DrawCommandPalette(), HandleCommandPaletteKey(), and UpdatePaletteMatches().
palette_matches_
std::vector<std::string> yaze::cli::agent::EnhancedTUI::palette_matches_ private
Definition at line 219 of file enhanced_tui.h.
Referenced by DrawCommandPalette(), HandleCommandPaletteKey(), and UpdatePaletteMatches().
palette_selection_
int yaze::cli::agent::EnhancedTUI::palette_selection_ = 0 private
Definition at line 220 of file enhanced_tui.h.
Referenced by DrawCommandPalette(), HandleCommandPaletteKey(), and UpdatePaletteMatches().
The documentation for this class was generated from the following files:
src/cli/service/agent/enhanced_tui.h
src/cli/service/agent/enhanced_tui.cc