yaze: yaze::emu::Spc700 Class Reference
yaze::emu::Spc700 Class Reference
The Spc700 class represents the SPC700 processor.
#include <spc700.h>
Classes
struct Flags
Public Member Functions
Spc700 (ApuCallbacks &callbacks)
uint8_t FlagsToByte (Flags flags)
Flags ByteToFlags (uint8_t byte)
void Reset (bool hard=false)
void RunOpcode ()
int GetLastOpcodeCycles () const
void ExecuteInstructions (uint8_t opcode)
void LogInstruction (uint16_t initial_pc, uint8_t opcode)
uint8_t read (uint16_t address)
uint16_t read_word (uint16_t address)
uint8_t ReadOpcode ()
uint16_t ReadOpcodeWord ()
void DoBranch (uint8_t value, bool check)
void write (uint16_t address, uint8_t value)
void push_byte (uint8_t value)
void push_word (uint16_t value)
uint8_t pull_byte ()
uint16_t pull_word ()
uint16_t imm ()
uint8_t dp ()
uint16_t dpx ()
uint8_t get_dp_addr ()
uint8_t abs_bit (uint16_t *adr)
uint16_t dp_dp (uint8_t *src)
uint16_t ind ()
uint16_t ind_ind (uint8_t *srcVal)
uint16_t dp_word (uint16_t *low)
uint16_t ind_p ()
uint16_t abs_x ()
uint16_t abs_y ()
uint16_t idx ()
uint16_t idy ()
uint16_t dp_y ()
uint16_t dp_imm (uint8_t *srcVal)
uint16_t abs ()
int8_t rel ()
uint8_t dp_plus_x ()
uint8_t dp_plus_y ()
uint16_t dp_plus_x_indirect ()
uint16_t dp_indirect_plus_y ()
uint8_t i ()
uint8_t i_postinc ()
uint16_t addr_plus_i ()
uint16_t addr_plus_i_indexed ()
void MOV (uint16_t adr)
void MOV_ADDR (uint16_t address, uint8_t operand)
void MOVY (uint16_t adr)
void MOVX (uint16_t adr)
void MOVS (uint16_t adr)
void MOVSX (uint16_t adr)
void MOVSY (uint16_t adr)
void ADC (uint16_t adr)
void ADCM (uint16_t &dest, uint8_t operand)
void SBC (uint16_t adr)
void SBCM (uint16_t &dest, uint8_t operand)
void CMP (uint16_t adr)
void CMPX (uint16_t adr)
void CMPM (uint16_t dst, uint8_t value)
void CMPY (uint16_t adr)
void AND (uint16_t adr)
void ANDM (uint16_t dest, uint8_t operand)
void OR (uint16_t adr)
void ORM (uint16_t dest, uint8_t operand)
void EOR (uint16_t adr)
void EORM (uint16_t dest, uint8_t operand)
void ASL (uint16_t operand)
void LSR (uint16_t adr)
void ROL (uint16_t operand)
void ROR (uint16_t adr)
void XCN (uint8_t operand, bool isImmediate=false)
void INC (uint16_t adr)
void DEC (uint16_t operand)
void MOVW (uint16_t &dest, uint16_t operand)
void INCW (uint16_t &operand)
void DECW (uint16_t &operand)
void ADDW (uint16_t &dest, uint16_t operand)
void SUBW (uint16_t &dest, uint16_t operand)
void CMPW (uint16_t operand)
void MUL (uint8_t operand)
void DIV (uint8_t operand)
void BRA (int8_t offset)
void BEQ (int8_t offset)
void BNE (int8_t offset)
void BCS (int8_t offset)
void BCC (int8_t offset)
void BVS (int8_t offset)
void BVC (int8_t offset)
void BMI (int8_t offset)
void BPL (int8_t offset)
void BBS (uint8_t bit, uint8_t operand)
void BBC (uint8_t bit, uint8_t operand)
void JMP (uint16_t address)
void CALL (uint16_t address)
void PCALL (uint8_t offset)
void TCALL (uint8_t offset)
void BRK ()
void RET ()
void RETI ()
void PUSH (uint8_t operand)
void POP (uint8_t &operand)
void SET1 (uint8_t bit, uint8_t &operand)
void CLR1 (uint8_t bit, uint8_t &operand)
void TSET1 (uint8_t bit, uint8_t &operand)
void TCLR1 (uint8_t bit, uint8_t &operand)
void AND1 (uint8_t bit, uint8_t &operand)
void OR1 (uint8_t bit, uint8_t &operand)
void EOR1 (uint8_t bit, uint8_t &operand)
void NOT1 (uint8_t bit, uint8_t &operand)
void MOV1 (uint8_t bit, uint8_t &operand)
void CLRC ()
void SETC ()
void NOTC ()
void CLRV ()
void CLRP ()
void SETP ()
void EI ()
void DI ()
void NOP ()
void SLEEP ()
void STOP ()
Public Attributes
uint8_t A = 0x00
uint8_t X = 0x00
uint8_t Y = 0x00
uint16_t YA = 0x00
uint16_t PC = 0xFFC0
uint8_t SP = 0x00
Flags PSW
Private Attributes
ApuCallbacks callbacks_
std::vector< std::string > log_
bool stopped_
bool reset_wanted_
uint8_t opcode
uint32_t step = 0
uint32_t bstep
uint16_t adr
uint16_t adr1
uint8_t dat
uint16_t dat16
uint8_t param
int last_opcode_cycles_ = 0
const uint8_t ipl_rom_ [64]
Detailed Description
The Spc700 class represents the SPC700 processor.
The Spc700 class provides the functionality to execute instructions, read and write memory, and handle various addressing modes. It also contains registers and flags specific to the SPC700.
Note
This class assumes the existence of an AudioRam object for memory access.
Definition at line 69 of file spc700.h.
Constructor & Destructor Documentation
Spc700()
yaze::emu::Spc700::Spc700 (ApuCallbacks & callbacks) inline explicit
Definition at line 98 of file spc700.h.
Member Function Documentation
FlagsToByte()
uint8_t yaze::emu::Spc700::FlagsToByte (Flags flags) inline
Definition at line 120 of file spc700.h.
References yaze::emu::Spc700::Flags::B, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::H, yaze::emu::Spc700::Flags::I, yaze::emu::Spc700::Flags::N, yaze::emu::Spc700::Flags::P, yaze::emu::Spc700::Flags::V, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ByteToFlags()
Flags yaze::emu::Spc700::ByteToFlags (uint8_t byte) inline
Definition at line 125 of file spc700.h.
References yaze::emu::Spc700::Flags::B, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::H, yaze::emu::Spc700::Flags::I, yaze::emu::Spc700::Flags::N, yaze::emu::Spc700::Flags::P, yaze::emu::Spc700::Flags::V, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions(), and Reset().
Reset()
void yaze::emu::Spc700::Reset (bool hard = false)
Definition at line 16 of file spc700.cc.
References A, ByteToFlags(), PC, PSW, reset_wanted_, SP, step, stopped_, X, and Y.
Referenced by yaze::emu::Apu::Reset().
RunOpcode()
void yaze::emu::Spc700::RunOpcode ()
Definition at line 30 of file spc700.cc.
References A, bstep, callbacks_, ExecuteInstructions(), yaze::core::FeatureFlags::get(), yaze::emu::Spc700::Flags::I, yaze::emu::ApuCallbacks::idle, last_opcode_cycles_, LOG_INFO, LogInstruction(), opcode, PC, PSW, yaze::emu::ApuCallbacks::read, read(), read_word(), ReadOpcode(), reset_wanted_, SP, yaze::emu::spc700_cycles, step, stopped_, and Y.
Referenced by yaze::emu::Apu::RunCycles().
GetLastOpcodeCycles()
int yaze::emu::Spc700::GetLastOpcodeCycles () const inline
Definition at line 143 of file spc700.h.
References last_opcode_cycles_.
Referenced by yaze::emu::Apu::RunCycles().
ExecuteInstructions()
void yaze::emu::Spc700::ExecuteInstructions (uint8_t opcode)
Definition at line 115 of file spc700.cc.
References A, abs(), abs_bit(), abs_x(), abs_y(), ADC(), ADCM(), adr, AND(), ANDM(), ASL(), yaze::emu::Spc700::Flags::B, bstep, ByteToFlags(), yaze::emu::Spc700::Flags::C, callbacks_, CMP(), CMPM(), CMPX(), CMPY(), dat, DEC(), DoBranch(), dp(), dp_dp(), dp_imm(), dp_word(), dp_y(), dpx(), EOR(), EORM(), FlagsToByte(), yaze::emu::Spc700::Flags::H, yaze::emu::Spc700::Flags::I, i(), yaze::emu::ApuCallbacks::idle, idx(), idy(), imm(), INC(), ind(), ind_ind(), ind_p(), LOG_INFO, LOG_WARN, LSR(), MOV(), MOVS(), MOVSX(), MOVSY(), MOVX(), MOVY(), yaze::emu::Spc700::Flags::N, opcode, OR(), ORM(), yaze::emu::Spc700::Flags::P, PC, PSW, pull_byte(), pull_word(), push_byte(), push_word(), read(), read_word(), ReadOpcode(), ReadOpcodeWord(), ROL(), ROR(), SBC(), SBCM(), SP, step, stopped_, yaze::emu::Spc700::Flags::V, write(), X, Y, and yaze::emu::Spc700::Flags::Z.
Referenced by RunOpcode().
LogInstruction()
void yaze::emu::Spc700::LogInstruction (uint16_t initial_pc, uint8_t opcode)
Definition at line 1369 of file spc700.cc.
References A, yaze::util::LogManager::instance(), yaze::util::LogManager::log(), opcode, spc_opcode_map, X, Y, and yaze::util::YAZE_DEBUG.
Referenced by RunOpcode().
read()
uint8_t yaze::emu::Spc700::read (uint16_t address) inline
Definition at line 149 of file spc700.h.
References callbacks_, and yaze::emu::ApuCallbacks::read.
Referenced by ADC(), ADCM(), addr_plus_i(), addr_plus_i_indexed(), AND(), ANDM(), ASL(), CMP(), CMPM(), CMPX(), CMPY(), DEC(), dp_dp(), dp_plus_x(), dp_plus_y(), EOR(), EORM(), ExecuteInstructions(), i(), i_postinc(), INC(), ind(), ind_ind(), ind_p(), LSR(), MOV(), MOVS(), MOVSX(), MOVSY(), MOVX(), MOVY(), OR(), ORM(), POP(), pull_byte(), rel(), RET(), RETI(), ROL(), ROR(), RunOpcode(), SBC(), and SBCM().
read_word()
uint16_t yaze::emu::Spc700::read_word (uint16_t address) inline
Definition at line 151 of file spc700.h.
References callbacks_, and yaze::emu::ApuCallbacks::read.
Referenced by dp_indirect_plus_y(), dp_plus_x_indirect(), ExecuteInstructions(), idx(), idy(), yaze::emu::Apu::Reset(), and RunOpcode().
ReadOpcode()
uint8_t yaze::emu::Spc700::ReadOpcode () inline
Definition at line 158 of file spc700.h.
References callbacks_, opcode, PC, and yaze::emu::ApuCallbacks::read.
Referenced by dp(), dp_dp(), dp_imm(), dp_word(), dp_y(), dpx(), ExecuteInstructions(), idx(), idy(), ReadOpcodeWord(), and RunOpcode().
ReadOpcodeWord()
uint16_t yaze::emu::Spc700::ReadOpcodeWord () inline
Definition at line 163 of file spc700.h.
References ReadOpcode().
Referenced by abs(), abs_bit(), abs_x(), abs_y(), and ExecuteInstructions().
DoBranch()
void yaze::emu::Spc700::DoBranch (uint8_t value, bool check) inline
Definition at line 169 of file spc700.h.
References callbacks_, yaze::emu::ApuCallbacks::idle, and PC.
Referenced by ExecuteInstructions().
write()
void yaze::emu::Spc700::write (uint16_t address, uint8_t value) inline
Definition at line 179 of file spc700.h.
References callbacks_, and yaze::emu::ApuCallbacks::write.
Referenced by ADCM(), ANDM(), ASL(), BRK(), CALL(), DEC(), EORM(), ExecuteInstructions(), INC(), LSR(), MOV_ADDR(), MOVS(), MOVSX(), MOVSY(), ORM(), PCALL(), PUSH(), ROL(), ROR(), SBCM(), and TCALL().
push_byte()
void yaze::emu::Spc700::push_byte (uint8_t value) inline
Definition at line 183 of file spc700.h.
References callbacks_, SP, and yaze::emu::ApuCallbacks::write.
Referenced by ExecuteInstructions(), and push_word().
push_word()
void yaze::emu::Spc700::push_word (uint16_t value) inline
Definition at line 188 of file spc700.h.
References push_byte().
Referenced by ExecuteInstructions().
pull_byte()
uint8_t yaze::emu::Spc700::pull_byte () inline
Definition at line 193 of file spc700.h.
References read(), and SP.
Referenced by ExecuteInstructions(), and pull_word().
pull_word()
uint16_t yaze::emu::Spc700::pull_word () inline
Definition at line 198 of file spc700.h.
References pull_byte().
Referenced by ExecuteInstructions().
imm()
uint16_t yaze::emu::Spc700::imm ()
Definition at line 79 of file addressing.cc.
References PC.
Referenced by ExecuteInstructions(), and XCN().
dp()
uint8_t yaze::emu::Spc700::dp ()
Definition at line 82 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PSW, and ReadOpcode().
Referenced by ExecuteInstructions().
dpx()
uint16_t yaze::emu::Spc700::dpx ()
Definition at line 19 of file addressing.cc.
References callbacks_, yaze::emu::ApuCallbacks::idle, yaze::emu::Spc700::Flags::P, PSW, ReadOpcode(), and X.
Referenced by ExecuteInstructions().
get_dp_addr()
uint8_t yaze::emu::Spc700::get_dp_addr ()
abs_bit()
uint8_t yaze::emu::Spc700::abs_bit (uint16_t * adr)
Definition at line 61 of file addressing.cc.
References adr, and ReadOpcodeWord().
Referenced by ExecuteInstructions().
dp_dp()
uint16_t yaze::emu::Spc700::dp_dp (uint8_t * src)
Definition at line 114 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PSW, read(), and ReadOpcode().
Referenced by ExecuteInstructions().
ind()
uint16_t yaze::emu::Spc700::ind ()
Definition at line 8 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PC, PSW, read(), and X.
Referenced by ExecuteInstructions().
ind_ind()
uint16_t yaze::emu::Spc700::ind_ind (uint8_t * srcVal)
Definition at line 55 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PC, PSW, read(), X, and Y.
Referenced by ExecuteInstructions().
dp_word()
uint16_t yaze::emu::Spc700::dp_word (uint16_t * low)
Definition at line 67 of file addressing.cc.
References adr, yaze::emu::Spc700::Flags::P, PSW, and ReadOpcode().
Referenced by ExecuteInstructions().
ind_p()
uint16_t yaze::emu::Spc700::ind_p ()
Definition at line 73 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PC, PSW, read(), and X.
Referenced by ExecuteInstructions().
abs_x()
uint16_t yaze::emu::Spc700::abs_x ()
Definition at line 31 of file addressing.cc.
References callbacks_, yaze::emu::ApuCallbacks::idle, ReadOpcodeWord(), and X.
Referenced by ExecuteInstructions().
abs_y()
uint16_t yaze::emu::Spc700::abs_y ()
Definition at line 37 of file addressing.cc.
References callbacks_, yaze::emu::ApuCallbacks::idle, ReadOpcodeWord(), and Y.
Referenced by ExecuteInstructions().
idx()
uint16_t yaze::emu::Spc700::idx ()
Definition at line 13 of file addressing.cc.
References callbacks_, yaze::emu::ApuCallbacks::idle, yaze::emu::Spc700::Flags::P, PSW, read_word(), ReadOpcode(), and X.
Referenced by ExecuteInstructions().
idy()
uint16_t yaze::emu::Spc700::idy ()
Definition at line 43 of file addressing.cc.
References adr, callbacks_, yaze::emu::ApuCallbacks::idle, yaze::emu::Spc700::Flags::P, PSW, read_word(), ReadOpcode(), and Y.
Referenced by ExecuteInstructions().
dp_y()
uint16_t yaze::emu::Spc700::dp_y ()
Definition at line 25 of file addressing.cc.
References callbacks_, yaze::emu::ApuCallbacks::idle, yaze::emu::Spc700::Flags::P, PSW, ReadOpcode(), and Y.
Referenced by ExecuteInstructions().
dp_imm()
uint16_t yaze::emu::Spc700::dp_imm (uint8_t * srcVal)
Definition at line 50 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PSW, and ReadOpcode().
Referenced by ExecuteInstructions().
abs()
uint16_t yaze::emu::Spc700::abs ()
Definition at line 119 of file addressing.cc.
References ReadOpcodeWord().
Referenced by ExecuteInstructions().
rel()
int8_t yaze::emu::Spc700::rel ()
Definition at line 121 of file addressing.cc.
References PC, and read().
Referenced by BBC(), and BBS().
dp_plus_x()
uint8_t yaze::emu::Spc700::dp_plus_x ()
Definition at line 87 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PC, PSW, read(), and X.
dp_plus_y()
uint8_t yaze::emu::Spc700::dp_plus_y ()
Definition at line 94 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PC, PSW, read(), and Y.
dp_plus_x_indirect()
uint16_t yaze::emu::Spc700::dp_plus_x_indirect ()
Definition at line 101 of file addressing.cc.
References PC, read_word(), and X.
dp_indirect_plus_y()
uint16_t yaze::emu::Spc700::dp_indirect_plus_y ()
Definition at line 108 of file addressing.cc.
References PC, read_word(), and Y.
i()
uint8_t yaze::emu::Spc700::i ()
Definition at line 126 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PSW, read(), and X.
Referenced by ExecuteInstructions().
i_postinc()
uint8_t yaze::emu::Spc700::i_postinc ()
Definition at line 128 of file addressing.cc.
References yaze::emu::Spc700::Flags::P, PSW, read(), and X.
addr_plus_i()
uint16_t yaze::emu::Spc700::addr_plus_i ()
Definition at line 134 of file addressing.cc.
References PC, read(), and X.
addr_plus_i_indexed()
uint16_t yaze::emu::Spc700::addr_plus_i_indexed ()
Definition at line 140 of file addressing.cc.
References PC, read(), and X.
MOV()
void yaze::emu::Spc700::MOV (uint16_t adr)
Definition at line 53 of file instructions.cc.
References A, adr, yaze::emu::Spc700::Flags::N, PSW, read(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOV_ADDR()
void yaze::emu::Spc700::MOV_ADDR (uint16_t address, uint8_t operand)
Definition at line 59 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, write(), and yaze::emu::Spc700::Flags::Z.
MOVY()
void yaze::emu::Spc700::MOVY (uint16_t adr)
Definition at line 15 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::N, PSW, read(), Y, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOVX()
void yaze::emu::Spc700::MOVX (uint16_t adr)
Definition at line 9 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::N, PSW, read(), X, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOVS()
void yaze::emu::Spc700::MOVS (uint16_t adr)
Definition at line 21 of file instructions.cc.
References A, adr, bstep, LOG_INFO, read(), and write().
Referenced by ExecuteInstructions().
MOVSX()
void yaze::emu::Spc700::MOVSX (uint16_t adr)
Definition at line 39 of file instructions.cc.
References adr, bstep, read(), write(), and X.
Referenced by ExecuteInstructions().
MOVSY()
void yaze::emu::Spc700::MOVSY (uint16_t adr)
Definition at line 46 of file instructions.cc.
References adr, bstep, read(), write(), and Y.
Referenced by ExecuteInstructions().
ADC()
void yaze::emu::Spc700::ADC (uint16_t adr)
Definition at line 65 of file instructions.cc.
References A, adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::H, yaze::emu::Spc700::Flags::N, PSW, read(), yaze::emu::Spc700::Flags::V, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ADCM()
void yaze::emu::Spc700::ADCM (uint16_t & dest, uint8_t operand)
Definition at line 76 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::H, yaze::emu::Spc700::Flags::N, PSW, read(), yaze::emu::Spc700::Flags::V, write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
SBC()
void yaze::emu::Spc700::SBC (uint16_t adr)
Definition at line 88 of file instructions.cc.
References A, adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::H, yaze::emu::Spc700::Flags::N, PSW, read(), yaze::emu::Spc700::Flags::V, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
SBCM()
void yaze::emu::Spc700::SBCM (uint16_t & dest, uint8_t operand)
Definition at line 99 of file instructions.cc.
References A, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::H, yaze::emu::Spc700::Flags::N, PSW, read(), yaze::emu::Spc700::Flags::V, write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMP()
void yaze::emu::Spc700::CMP (uint16_t adr)
Definition at line 137 of file instructions.cc.
References A, adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, read(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMPX()
void yaze::emu::Spc700::CMPX (uint16_t adr)
Definition at line 112 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, read(), X, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMPM()
void yaze::emu::Spc700::CMPM (uint16_t dst, uint8_t value)
Definition at line 128 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, callbacks_, yaze::emu::ApuCallbacks::idle, yaze::emu::Spc700::Flags::N, PSW, read(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMPY()
void yaze::emu::Spc700::CMPY (uint16_t adr)
Definition at line 120 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, read(), Y, and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
AND()
void yaze::emu::Spc700::AND (uint16_t adr)
Definition at line 145 of file instructions.cc.
References A, adr, yaze::emu::Spc700::Flags::N, PSW, read(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ANDM()
void yaze::emu::Spc700::ANDM (uint16_t dest, uint8_t operand)
Definition at line 151 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
OR()
void yaze::emu::Spc700::OR (uint16_t adr)
Definition at line 158 of file instructions.cc.
References A, adr, yaze::emu::Spc700::Flags::N, PSW, read(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ORM()
void yaze::emu::Spc700::ORM (uint16_t dest, uint8_t operand)
Definition at line 164 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
EOR()
void yaze::emu::Spc700::EOR (uint16_t adr)
Definition at line 171 of file instructions.cc.
References A, adr, yaze::emu::Spc700::Flags::N, PSW, read(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
EORM()
void yaze::emu::Spc700::EORM (uint16_t dest, uint8_t operand)
Definition at line 177 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ASL()
void yaze::emu::Spc700::ASL (uint16_t operand)
Definition at line 184 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
LSR()
void yaze::emu::Spc700::LSR (uint16_t adr)
Definition at line 193 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ROL()
void yaze::emu::Spc700::ROL (uint16_t operand)
Definition at line 212 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ROR()
void yaze::emu::Spc700::ROR (uint16_t adr)
Definition at line 202 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
XCN()
void yaze::emu::Spc700::XCN (uint8_t operand, bool isImmediate = false)
Definition at line 223 of file instructions.cc.
References imm(), yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
INC()
void yaze::emu::Spc700::INC (uint16_t adr)
Definition at line 231 of file instructions.cc.
References adr, yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
DEC()
void yaze::emu::Spc700::DEC (uint16_t operand)
Definition at line 238 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, read(), write(), and yaze::emu::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOVW()
void yaze::emu::Spc700::MOVW (uint16_t & dest, uint16_t operand)
Definition at line 245 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
INCW()
void yaze::emu::Spc700::INCW (uint16_t & operand)
Definition at line 251 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
DECW()
void yaze::emu::Spc700::DECW (uint16_t & operand)
Definition at line 257 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
ADDW()
void yaze::emu::Spc700::ADDW (uint16_t & dest, uint16_t operand)
Definition at line 263 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, yaze::emu::Spc700::Flags::V, and yaze::emu::Spc700::Flags::Z.
SUBW()
void yaze::emu::Spc700::SUBW (uint16_t & dest, uint16_t operand)
Definition at line 272 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, yaze::emu::Spc700::Flags::V, and yaze::emu::Spc700::Flags::Z.
CMPW()
void yaze::emu::Spc700::CMPW (uint16_t operand)
Definition at line 281 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, yaze::emu::Spc700::Flags::N, PSW, YA, and yaze::emu::Spc700::Flags::Z.
MUL()
void yaze::emu::Spc700::MUL (uint8_t operand)
Definition at line 288 of file instructions.cc.
References A, yaze::emu::Spc700::Flags::N, PSW, YA, and yaze::emu::Spc700::Flags::Z.
DIV()
void yaze::emu::Spc700::DIV (uint8_t operand)
Definition at line 295 of file instructions.cc.
References A, yaze::emu::Spc700::Flags::N, PSW, Y, and yaze::emu::Spc700::Flags::Z.
BRA()
void yaze::emu::Spc700::BRA (int8_t offset)
Definition at line 308 of file instructions.cc.
References PC.
BEQ()
void yaze::emu::Spc700::BEQ (int8_t offset)
Definition at line 310 of file instructions.cc.
References PC, PSW, and yaze::emu::Spc700::Flags::Z.
BNE()
void yaze::emu::Spc700::BNE (int8_t offset)
Definition at line 316 of file instructions.cc.
References PC, PSW, and yaze::emu::Spc700::Flags::Z.
BCS()
void yaze::emu::Spc700::BCS (int8_t offset)
Definition at line 322 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, PC, and PSW.
BCC()
void yaze::emu::Spc700::BCC (int8_t offset)
Definition at line 328 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, PC, and PSW.
BVS()
void yaze::emu::Spc700::BVS (int8_t offset)
Definition at line 334 of file instructions.cc.
References PC, PSW, and yaze::emu::Spc700::Flags::V.
BVC()
void yaze::emu::Spc700::BVC (int8_t offset)
Definition at line 340 of file instructions.cc.
References PC, PSW, and yaze::emu::Spc700::Flags::V.
BMI()
void yaze::emu::Spc700::BMI (int8_t offset)
Definition at line 346 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PC, and PSW.
BPL()
void yaze::emu::Spc700::BPL (int8_t offset)
Definition at line 352 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PC, and PSW.
BBS()
void yaze::emu::Spc700::BBS (uint8_t bit, uint8_t operand)
Definition at line 358 of file instructions.cc.
References PC, and rel().
BBC()
void yaze::emu::Spc700::BBC (uint8_t bit, uint8_t operand)
Definition at line 364 of file instructions.cc.
References PC, and rel().
JMP()
void yaze::emu::Spc700::JMP (uint16_t address)
Definition at line 372 of file instructions.cc.
References PC.
CALL()
void yaze::emu::Spc700::CALL (uint16_t address)
Definition at line 374 of file instructions.cc.
References PC, SP, and write().
PCALL()
void yaze::emu::Spc700::PCALL (uint8_t offset)
Definition at line 382 of file instructions.cc.
References PC, SP, and write().
TCALL()
void yaze::emu::Spc700::TCALL (uint8_t offset)
Definition at line 390 of file instructions.cc.
References PC, SP, and write().
BRK()
void yaze::emu::Spc700::BRK ()
Definition at line 398 of file instructions.cc.
References PC, SP, and write().
RET()
void yaze::emu::Spc700::RET ()
Definition at line 406 of file instructions.cc.
References PC, read(), and SP.
RETI()
void yaze::emu::Spc700::RETI ()
Definition at line 412 of file instructions.cc.
References yaze::emu::Spc700::Flags::I, PC, PSW, read(), and SP.
PUSH()
void yaze::emu::Spc700::PUSH (uint8_t operand)
Definition at line 419 of file instructions.cc.
References SP, and write().
POP()
void yaze::emu::Spc700::POP (uint8_t & operand)
Definition at line 424 of file instructions.cc.
References read(), and SP.
SET1()
void yaze::emu::Spc700::SET1 (uint8_t bit, uint8_t & operand)
Definition at line 429 of file instructions.cc.
CLR1()
void yaze::emu::Spc700::CLR1 (uint8_t bit, uint8_t & operand)
Definition at line 431 of file instructions.cc.
TSET1()
void yaze::emu::Spc700::TSET1 (uint8_t bit, uint8_t & operand)
Definition at line 433 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, and PSW.
TCLR1()
void yaze::emu::Spc700::TCLR1 (uint8_t bit, uint8_t & operand)
Definition at line 438 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, and PSW.
AND1()
void yaze::emu::Spc700::AND1 (uint8_t bit, uint8_t & operand)
Definition at line 443 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
OR1()
void yaze::emu::Spc700::OR1 (uint8_t bit, uint8_t & operand)
Definition at line 449 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
EOR1()
void yaze::emu::Spc700::EOR1 (uint8_t bit, uint8_t & operand)
Definition at line 455 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
NOT1()
void yaze::emu::Spc700::NOT1 (uint8_t bit, uint8_t & operand)
Definition at line 461 of file instructions.cc.
References yaze::emu::Spc700::Flags::N, PSW, and yaze::emu::Spc700::Flags::Z.
MOV1()
void yaze::emu::Spc700::MOV1 (uint8_t bit, uint8_t & operand)
Definition at line 467 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, and PSW.
CLRC()
void yaze::emu::Spc700::CLRC ()
Definition at line 472 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, and PSW.
SETC()
void yaze::emu::Spc700::SETC ()
Definition at line 474 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, and PSW.
NOTC()
void yaze::emu::Spc700::NOTC ()
Definition at line 476 of file instructions.cc.
References yaze::emu::Spc700::Flags::C, and PSW.
CLRV()
void yaze::emu::Spc700::CLRV ()
Definition at line 478 of file instructions.cc.
References PSW, and yaze::emu::Spc700::Flags::V.
CLRP()
void yaze::emu::Spc700::CLRP ()
Definition at line 480 of file instructions.cc.
References yaze::emu::Spc700::Flags::P, and PSW.
SETP()
void yaze::emu::Spc700::SETP ()
Definition at line 482 of file instructions.cc.
References yaze::emu::Spc700::Flags::P, and PSW.
EI()
void yaze::emu::Spc700::EI ()
Definition at line 484 of file instructions.cc.
References yaze::emu::Spc700::Flags::I, and PSW.
DI()
void yaze::emu::Spc700::DI ()
Definition at line 486 of file instructions.cc.
References yaze::emu::Spc700::Flags::I, and PSW.
NOP()
void yaze::emu::Spc700::NOP ()
Definition at line 488 of file instructions.cc.
References PC.
SLEEP()
void yaze::emu::Spc700::SLEEP ()
Definition at line 490 of file instructions.cc.
STOP()
void yaze::emu::Spc700::STOP ()
Definition at line 492 of file instructions.cc.
Member Data Documentation
callbacks_
ApuCallbacks yaze::emu::Spc700::callbacks_ private
Definition at line 71 of file spc700.h.
Referenced by abs_x(), abs_y(), CMPM(), DoBranch(), dp_y(), dpx(), ExecuteInstructions(), idx(), idy(), push_byte(), read(), read_word(), ReadOpcode(), RunOpcode(), and write().
log_
std::vector<std::string> yaze::emu::Spc700::log_ private
Definition at line 72 of file spc700.h.
stopped_
bool yaze::emu::Spc700::stopped_ private
Definition at line 74 of file spc700.h.
Referenced by ExecuteInstructions(), Reset(), and RunOpcode().
reset_wanted_
bool yaze::emu::Spc700::reset_wanted_ private
Definition at line 75 of file spc700.h.
Referenced by Reset(), and RunOpcode().
opcode
uint8_t yaze::emu::Spc700::opcode private
Definition at line 77 of file spc700.h.
Referenced by ExecuteInstructions(), LogInstruction(), ReadOpcode(), and RunOpcode().
step
uint32_t yaze::emu::Spc700::step = 0 private
Definition at line 78 of file spc700.h.
Referenced by ExecuteInstructions(), Reset(), and RunOpcode().
bstep
uint32_t yaze::emu::Spc700::bstep private
Definition at line 79 of file spc700.h.
Referenced by ExecuteInstructions(), MOVS(), MOVSX(), MOVSY(), and RunOpcode().
adr
uint16_t yaze::emu::Spc700::adr private
Definition at line 80 of file spc700.h.
Referenced by abs_bit(), ADC(), AND(), CMP(), CMPX(), CMPY(), dp_word(), EOR(), ExecuteInstructions(), idy(), INC(), LSR(), MOV(), MOVS(), MOVSX(), MOVSY(), MOVX(), MOVY(), OR(), ROL(), ROR(), and SBC().
adr1
uint16_t yaze::emu::Spc700::adr1 private
Definition at line 81 of file spc700.h.
dat
uint8_t yaze::emu::Spc700::dat private
Definition at line 82 of file spc700.h.
Referenced by ExecuteInstructions().
dat16
uint16_t yaze::emu::Spc700::dat16 private
Definition at line 83 of file spc700.h.
param
uint8_t yaze::emu::Spc700::param private
Definition at line 84 of file spc700.h.
last_opcode_cycles_
int yaze::emu::Spc700::last_opcode_cycles_ = 0 private
Definition at line 87 of file spc700.h.
Referenced by GetLastOpcodeCycles(), and RunOpcode().
ipl_rom_
const uint8_t yaze::emu::Spc700::ipl_rom_[64] private
Initial value:
{
      0xCD, 0xEF, 0xBD, 0xE8, 0x00, 0xC6, 0x1D, 0xD0, 0xFC, 0x8F, 0xAA,
      0xF4, 0x8F, 0xBB, 0xF5, 0x78, 0xCC, 0xF4, 0xD0, 0xFB, 0x2F, 0x19,
      0xEB, 0xF4, 0xD0, 0xFC, 0x7E, 0xF4, 0xD0, 0x0B, 0xE4, 0xF5, 0xCB,
      0xF4, 0xD7, 0x00, 0xFC, 0xD0, 0xF3, 0xAB, 0x01, 0x10, 0xEF, 0x7E,
      0xF4, 0x10, 0xEB, 0xBA, 0xF6, 0xDA, 0x00, 0xBA, 0xF4, 0xC4, 0xF4,
      0xDD, 0x5D, 0xD0, 0xDB, 0x1F, 0x00, 0x00, 0xC0, 0xFF}
Definition at line 89 of file spc700.h.
A
uint8_t yaze::emu::Spc700::A = 0x00
Definition at line 101 of file spc700.h.
Referenced by ADC(), AND(), CMP(), DIV(), EOR(), ExecuteInstructions(), LogInstruction(), MOV(), MOVS(), MUL(), OR(), Reset(), RunOpcode(), SBC(), and SBCM().
X
uint8_t yaze::emu::Spc700::X = 0x00
Definition at line 102 of file spc700.h.
Referenced by abs_x(), addr_plus_i(), addr_plus_i_indexed(), CMPX(), dp_plus_x(), dp_plus_x_indirect(), dpx(), ExecuteInstructions(), i(), i_postinc(), idx(), ind(), ind_ind(), ind_p(), LogInstruction(), MOVSX(), MOVX(), and Reset().
Y
uint8_t yaze::emu::Spc700::Y = 0x00
Definition at line 103 of file spc700.h.
Referenced by abs_y(), CMPY(), DIV(), dp_indirect_plus_y(), dp_plus_y(), dp_y(), ExecuteInstructions(), idy(), ind_ind(), LogInstruction(), MOVSY(), MOVY(), Reset(), and RunOpcode().
YA
uint16_t yaze::emu::Spc700::YA = 0x00
Definition at line 104 of file spc700.h.
Referenced by CMPW(), and MUL().
PC
uint16_t yaze::emu::Spc700::PC = 0xFFC0
Definition at line 105 of file spc700.h.
Referenced by addr_plus_i(), addr_plus_i_indexed(), BBC(), BBS(), BCC(), BCS(), BEQ(), BMI(), BNE(), BPL(), BRA(), BRK(), BVC(), BVS(), CALL(), DoBranch(), dp_indirect_plus_y(), dp_plus_x(), dp_plus_x_indirect(), dp_plus_y(), ExecuteInstructions(), imm(), ind(), ind_ind(), ind_p(), JMP(), NOP(), PCALL(), yaze::emu::Apu::Read(), ReadOpcode(), rel(), Reset(), RET(), RETI(), yaze::emu::Apu::RunCycles(), RunOpcode(), TCALL(), and yaze::emu::Apu::Write().
SP
uint8_t yaze::emu::Spc700::SP = 0x00
Definition at line 106 of file spc700.h.
Referenced by BRK(), CALL(), ExecuteInstructions(), PCALL(), POP(), pull_byte(), PUSH(), push_byte(), Reset(), RET(), RETI(), RunOpcode(), and TCALL().
PSW
Flags yaze::emu::Spc700::PSW
Definition at line 118 of file spc700.h.
Referenced by ADC(), ADCM(), ADDW(), AND(), AND1(), ANDM(), ASL(), BCC(), BCS(), BEQ(), BMI(), BNE(), BPL(), BVC(), BVS(), CLRC(), CLRP(), CLRV(), CMP(), CMPM(), CMPW(), CMPX(), CMPY(), DEC(), DECW(), DI(), DIV(), dp(), dp_dp(), dp_imm(), dp_plus_x(), dp_plus_y(), dp_word(), dp_y(), dpx(), EI(), EOR(), EOR1(), EORM(), ExecuteInstructions(), i(), i_postinc(), idx(), idy(), INC(), INCW(), ind(), ind_ind(), ind_p(), LSR(), MOV(), MOV1(), MOV_ADDR(), MOVW(), MOVX(), MOVY(), MUL(), NOT1(), NOTC(), OR(), OR1(), ORM(), Reset(), RETI(), ROL(), ROR(), RunOpcode(), SBC(), SBCM(), SETC(), SETP(), SUBW(), TCLR1(), TSET1(), and XCN().
The documentation for this class was generated from the following files:
src/app/emu/audio/spc700.h
src/app/emu/audio/internal/addressing.cc
src/app/emu/audio/internal/instructions.cc
src/app/emu/audio/spc700.cc