yaze: test/test_conversation_minimal.cc File Reference
test_conversation_minimal.cc File Reference
#include <iostream>
#include "cli/service/ai/service_factory.h"
#include "cli/service/agent/conversational_agent_service.h"
#include "app/rom.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 10 of file test_conversation_minimal.cc.
References yaze::cli::CreateAIService(), and yaze::cli::agent::ConversationalAgentService::SetRomContext().
Referenced by yaze::zelda3::OverworldMap::LoadPalette(), and yaze::zelda3::palette_internal::SetColorsPalette().