yaze: yaze::emu::ui Namespace Reference
yaze::emu::ui Namespace Reference
Namespaces
namespace anonymous_namespace{debugger_ui.cc}
namespace anonymous_namespace{emulator_ui.cc}
Functions
void RenderModernCpuDebugger (Emulator *emu)
Modern CPU debugger with registers, flags, and controls.
void RenderBreakpointList (Emulator *emu)
Breakpoint list and management.
void RenderMemoryViewer (Emulator *emu)
Memory viewer/editor.
void RenderCpuInstructionLog (Emulator *emu, uint32_t log_size)
CPU instruction log (legacy, prefer DisassemblyViewer)
void RenderApuDebugger (Emulator *emu)
APU/Audio debugger with handshake tracker.
void RenderAIAgentPanel (Emulator *emu)
AI Agent panel for automated testing/gameplay.
void RenderNavBar (Emulator *emu)
Navigation bar with play/pause, step, reset controls.
void RenderSnesPpu (Emulator *emu)
SNES PPU output display.
void RenderPerformanceMonitor (Emulator *emu)
Performance metrics (FPS, frame time, audio status)
void RenderEmulatorInterface (Emulator *emu)
Main emulator UI interface - renders the emulator window.
void RenderKeyboardConfig (input::InputManager *manager)
Render keyboard configuration UI.
Function Documentation
RenderModernCpuDebugger()
void yaze::emu::ui::RenderModernCpuDebugger (Emulator * emu)
Modern CPU debugger with registers, flags, and controls.
Definition at line 31 of file debugger_ui.cc.
References yaze::emu::Emulator::ClearAllBreakpoints(), yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), yaze::emu::Emulator::GetBreakpoints(), ICON_MD_ADD, ICON_MD_CHECK_BOX, ICON_MD_CHECK_BOX_OUTLINE_BLANK, ICON_MD_CLEAR_ALL, ICON_MD_DELETE, ICON_MD_DEVELOPER_BOARD, ICON_MD_FAST_FORWARD, ICON_MD_FLAG, ICON_MD_MEMORY, ICON_MD_SETTINGS, ICON_MD_SKIP_NEXT, ICON_MD_STOP, ICON_MD_STOP_CIRCLE, yaze::emu::Emulator::set_running(), yaze::emu::Emulator::SetBreakpoint(), and yaze::emu::Emulator::snes().
RenderBreakpointList()
void yaze::emu::ui::RenderBreakpointList (Emulator * emu)
Breakpoint list and management.
Definition at line 216 of file debugger_ui.cc.
References yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), yaze::emu::Emulator::GetBreakpoints(), ICON_MD_DELETE, ICON_MD_INFO, ICON_MD_STOP, ICON_MD_STOP_CIRCLE, ICON_MD_TAG, and yaze::emu::Emulator::snes().
Referenced by yaze::emu::Emulator::RenderBreakpointList().
RenderMemoryViewer()
void yaze::emu::ui::RenderMemoryViewer (Emulator * emu)
Memory viewer/editor.
Definition at line 269 of file debugger_ui.cc.
References yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), ICON_MD_MAP, ICON_MD_STORAGE, and yaze::emu::Emulator::snes().
Referenced by yaze::emu::Emulator::RenderMemoryViewer().
RenderCpuInstructionLog()
void yaze::emu::ui::RenderCpuInstructionLog (Emulator * emu, uint32_t log_size)
CPU instruction log (legacy, prefer DisassemblyViewer)
Todo:
Open disassembly viewer window
Definition at line 305 of file debugger_ui.cc.
References yaze::gui::ConvertColorToImVec4(), yaze::emu::Emulator::disassembly_viewer(), yaze::gui::ThemeManager::Get(), yaze::emu::debug::DisassemblyViewer::GetInstructionCount(), ICON_MD_INFO, ICON_MD_OPEN_IN_NEW, ICON_MD_WARNING, and yaze::emu::debug::DisassemblyViewer::IsRecording().
Referenced by yaze::emu::Emulator::RenderCpuInstructionLog().
RenderApuDebugger()
void yaze::emu::ui::RenderApuDebugger (Emulator * emu)
APU/Audio debugger with handshake tracker.
Definition at line 336 of file debugger_ui.cc.
References yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), ICON_MD_ARROW_BACK, ICON_MD_ARROW_FORWARD, ICON_MD_BUILD, ICON_MD_CHECK_CIRCLE, ICON_MD_CLEAR_ALL, ICON_MD_CLOUD_UPLOAD, ICON_MD_EDIT, ICON_MD_ERROR, ICON_MD_HANDSHAKE, ICON_MD_HOURGLASS_EMPTY, ICON_MD_INFO, ICON_MD_LINK, ICON_MD_LIST, ICON_MD_MUSIC_NOTE, ICON_MD_PENDING, ICON_MD_PLAY_CIRCLE, ICON_MD_RESTART_ALT, ICON_MD_SEND, ICON_MD_SETTINGS, ICON_MD_SETTINGS_INPUT_COMPONENT, ICON_MD_SYNC, ICON_MD_WARNING, LOG_INFO, and yaze::emu::Emulator::snes().
Referenced by yaze::emu::Emulator::RenderApuDebugger().
RenderAIAgentPanel()
void yaze::emu::ui::RenderAIAgentPanel (Emulator * emu)
AI Agent panel for automated testing/gameplay.
Todo:
Start agent
Todo:
Stop agent
Definition at line 539 of file debugger_ui.cc.
References yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), yaze::emu::Emulator::GetMetrics(), ICON_MD_CHECK_CIRCLE, ICON_MD_DATA_OBJECT, ICON_MD_ERROR, ICON_MD_PLAY_ARROW, ICON_MD_PLAY_CIRCLE, ICON_MD_SMART_TOY, ICON_MD_STOP, and yaze::emu::Emulator::IsEmulatorReady().
Referenced by yaze::emu::Emulator::RenderAIAgentPanel().
RenderNavBar()
void yaze::emu::ui::RenderNavBar (Emulator * emu)
Navigation bar with play/pause, step, reset controls.
Definition at line 38 of file emulator_ui.cc.
References yaze::emu::Emulator::audio_backend(), yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), yaze::emu::audio::IAudioBackend::GetBackendName(), yaze::emu::Emulator::GetCurrentFPS(), yaze::emu::audio::IAudioBackend::GetStatus(), ICON_MD_BUG_REPORT, ICON_MD_FAST_FORWARD, ICON_MD_PAUSE, ICON_MD_PLAY_ARROW, ICON_MD_RESTART_ALT, ICON_MD_SKIP_NEXT, ICON_MD_SPEED, ICON_MD_VOLUME_OFF, ICON_MD_VOLUME_UP, yaze::emu::Emulator::is_debugging(), yaze::emu::audio::AudioStatus::is_playing, LOG_INFO, yaze::emu::Emulator::running(), yaze::emu::Emulator::set_debugging(), yaze::emu::Emulator::set_running(), and yaze::emu::Emulator::snes().
Referenced by RenderEmulatorInterface(), and yaze::emu::Emulator::RenderNavBar().
RenderSnesPpu()
void yaze::emu::ui::RenderSnesPpu (Emulator * emu)
SNES PPU output display.
Definition at line 169 of file emulator_ui.cc.
References yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), ICON_MD_VIDEOGAME_ASSET, yaze::emu::Emulator::is_snes_initialized(), and yaze::emu::Emulator::ppu_texture().
Referenced by RenderEmulatorInterface(), and yaze::emu::Emulator::RenderSnesPpu().
RenderPerformanceMonitor()
void yaze::emu::ui::RenderPerformanceMonitor (Emulator * emu)
Performance metrics (FPS, frame time, audio status)
Todo:
Add FPS graph with ImPlot
Definition at line 215 of file emulator_ui.cc.
References yaze::emu::Emulator::audio_backend(), yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), yaze::emu::audio::IAudioBackend::GetBackendName(), yaze::emu::Emulator::GetMetrics(), yaze::emu::audio::IAudioBackend::GetStatus(), ICON_MD_AUDIOTRACK, ICON_MD_MEMORY, ICON_MD_SHOW_CHART, ICON_MD_SPEED, and yaze::emu::Emulator::snes().
Referenced by yaze::emu::Emulator::RenderPerformanceMonitor().
RenderEmulatorInterface()
void yaze::emu::ui::RenderEmulatorInterface (Emulator * emu)
Main emulator UI interface - renders the emulator window.
Definition at line 260 of file emulator_ui.cc.
References yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), RenderNavBar(), and RenderSnesPpu().
RenderKeyboardConfig()
void yaze::emu::ui::RenderKeyboardConfig (input::InputManager * manager)
Render keyboard configuration UI.
Parameters
manager InputManager to configure
Definition at line 11 of file input_handler.cc.
References yaze::emu::input::InputManager::backend(), yaze::emu::input::IInputBackend::GetBackendName(), yaze::emu::input::InputManager::GetConfig(), ICON_MD_INFO, and yaze::emu::input::InputManager::SetConfig().
Referenced by yaze::emu::Emulator::RenderKeyboardConfig().