yaze: yaze::cli::Agent Class Reference
yaze::cli::Agent Class Reference
#include <z3ed.h>
Public Member Functions
absl::Status Run (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
virtual void RunTUI (ftxui::ScreenInteractive &screen)
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
Rom rom_
Detailed Description
Definition at line 135 of file z3ed.h.
Member Function Documentation
Run()
absl::Status yaze::cli::Agent::Run (const std::vector< std::string > & arg_vec) override virtual
Implements yaze::cli::CommandHandler.
Definition at line 85 of file agent.cc.
References yaze::cli::agent::HandleAcceptCommand(), yaze::cli::agent::HandleChatCommand(), yaze::cli::agent::HandleCommitCommand(), yaze::cli::agent::HandleDescribeCommand(), yaze::cli::agent::HandleDiffCommand(), yaze::cli::agent::HandleDungeonDescribeRoomCommand(), yaze::cli::agent::HandleDungeonListSpritesCommand(), yaze::cli::agent::HandleGuiCommand(), yaze::cli::agent::HandleHexRead(), yaze::cli::agent::HandleHexSearch(), yaze::cli::agent::HandleHexWrite(), yaze::cli::agent::HandleLearnCommand(), yaze::cli::agent::HandleListCommand(), yaze::cli::agent::HandleOverworldDescribeMapCommand(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandlePaletteAnalyze(), yaze::cli::agent::HandlePaletteGetColors(), yaze::cli::agent::HandlePaletteSetColor(), yaze::cli::agent::HandlePlanCommand(), yaze::cli::agent::HandleResourceListCommand(), yaze::cli::agent::HandleResourceSearchCommand(), yaze::cli::agent::HandleRevertCommand(), yaze::cli::agent::HandleRunCommand(), yaze::cli::agent::HandleSimpleChatCommand(), yaze::cli::agent::HandleTestCommand(), yaze::cli::agent::HandleTestConversationCommand(), yaze::cli::handlers::HandleTodoCommand(), and yaze::cli::CommandHandler::rom_.
Referenced by yaze::cli::ModernCLI::HandleAgentCommand().
The documentation for this class was generated from the following files:
src/cli/z3ed.h
src/cli/handlers/agent.cc