var annotated_dup =
[
    [ "anonymous_namespace{cli_main.cc}", "da/dfe/namespaceanonymous__namespace_02cli__main_8cc_03.html", [
      [ "ParsedGlobals", "da/dbb/structanonymous__namespace_02cli__main_8cc_03_1_1ParsedGlobals.html", "da/dbb/structanonymous__namespace_02cli__main_8cc_03_1_1ParsedGlobals" ]
    ] ],
    [ "build_cleaner", "db/d7d/namespacebuild__cleaner.html", [
      [ "CMakeSourceBlock", "db/d75/classbuild__cleaner_1_1CMakeSourceBlock.html", null ],
      [ "DirectorySpec", "dc/d1c/classbuild__cleaner_1_1DirectorySpec.html", "dc/d1c/classbuild__cleaner_1_1DirectorySpec" ]
    ] ],
    [ "yaze", "dc/d46/namespaceyaze.html", [
      [ "cli", "dd/d63/namespaceyaze_1_1cli.html", [
        [ "agent", "d8/dd3/namespaceyaze_1_1cli_1_1agent.html", [
          [ "anonymous_namespace{conversation_test.cc}", "d0/d0b/namespaceyaze_1_1cli_1_1agent_1_1anonymous__namespace_02conversation__test_8cc_03.html", [
            [ "ConversationTestCase", "da/d74/structyaze_1_1cli_1_1agent_1_1anonymous__namespace_02conversation__test_8cc_03_1_1ConversationTestCase.html", "da/d74/structyaze_1_1cli_1_1agent_1_1anonymous__namespace_02conversation__test_8cc_03_1_1ConversationTestCase" ]
          ] ],
          [ "anonymous_namespace{general_commands.cc}", "d1/ddf/namespaceyaze_1_1cli_1_1agent_1_1anonymous__namespace_02general__commands_8cc_03.html", [
            [ "DescribeOptions", "d9/d7e/structyaze_1_1cli_1_1agent_1_1anonymous__namespace_02general__commands_8cc_03_1_1DescribeOptions.html", "d9/d7e/structyaze_1_1cli_1_1agent_1_1anonymous__namespace_02general__commands_8cc_03_1_1DescribeOptions" ]
          ] ],
          [ "anonymous_namespace{palette_commands.cc}", "d0/d09/namespaceyaze_1_1cli_1_1agent_1_1anonymous__namespace_02palette__commands_8cc_03.html", [
            [ "RGB", "d4/d24/structyaze_1_1cli_1_1agent_1_1anonymous__namespace_02palette__commands_8cc_03_1_1RGB.html", "d4/d24/structyaze_1_1cli_1_1agent_1_1anonymous__namespace_02palette__commands_8cc_03_1_1RGB" ]
          ] ],
          [ "AdvancedRouter", "d8/d4e/classyaze_1_1cli_1_1agent_1_1AdvancedRouter.html", "d8/d4e/classyaze_1_1cli_1_1agent_1_1AdvancedRouter" ],
          [ "AgentConfig", "d8/db1/structyaze_1_1cli_1_1agent_1_1AgentConfig.html", "d8/db1/structyaze_1_1cli_1_1agent_1_1AgentConfig" ],
          [ "AgentPretraining", "d7/d62/classyaze_1_1cli_1_1agent_1_1AgentPretraining.html", "d7/d62/classyaze_1_1cli_1_1agent_1_1AgentPretraining" ],
          [ "ChatMessage", "d4/dd2/structyaze_1_1cli_1_1agent_1_1ChatMessage.html", "d4/dd2/structyaze_1_1cli_1_1agent_1_1ChatMessage" ],
          [ "ConversationalAgentService", "d6/df5/classyaze_1_1cli_1_1agent_1_1ConversationalAgentService.html", "d6/df5/classyaze_1_1cli_1_1agent_1_1ConversationalAgentService" ],
          [ "LearnedKnowledgeService", "d1/d0f/classyaze_1_1cli_1_1agent_1_1LearnedKnowledgeService.html", "d1/d0f/classyaze_1_1cli_1_1agent_1_1LearnedKnowledgeService" ],
          [ "PromptManager", "d4/d79/classyaze_1_1cli_1_1agent_1_1PromptManager.html", null ],
          [ "ProposalCreationRequest", "d6/d99/structyaze_1_1cli_1_1agent_1_1ProposalCreationRequest.html", "d6/d99/structyaze_1_1cli_1_1agent_1_1ProposalCreationRequest" ],
          [ "ProposalCreationResult", "d9/dce/structyaze_1_1cli_1_1agent_1_1ProposalCreationResult.html", "d9/dce/structyaze_1_1cli_1_1agent_1_1ProposalCreationResult" ],
          [ "SimpleChatSession", "db/dbd/classyaze_1_1cli_1_1agent_1_1SimpleChatSession.html", "db/dbd/classyaze_1_1cli_1_1agent_1_1SimpleChatSession" ],
          [ "TodoItem", "d0/d0e/structyaze_1_1cli_1_1agent_1_1TodoItem.html", "d0/d0e/structyaze_1_1cli_1_1agent_1_1TodoItem" ],
          [ "TodoManager", "df/dc2/classyaze_1_1cli_1_1agent_1_1TodoManager.html", "df/dc2/classyaze_1_1cli_1_1agent_1_1TodoManager" ],
          [ "ToolDispatcher", "d0/d4a/classyaze_1_1cli_1_1agent_1_1ToolDispatcher.html", "d0/d4a/classyaze_1_1cli_1_1agent_1_1ToolDispatcher" ],
          [ "VimMode", "d9/dd2/classyaze_1_1cli_1_1agent_1_1VimMode.html", "d9/dd2/classyaze_1_1cli_1_1agent_1_1VimMode" ]
        ] ],
        [ "ai", "d8/d4c/namespaceyaze_1_1cli_1_1ai.html", [
          [ "anonymous_namespace{ai_gui_controller_test.cc}", "df/d37/namespaceyaze_1_1cli_1_1ai_1_1anonymous__namespace_02ai__gui__controller__test_8cc_03.html", [
            [ "AIGUIControllerTest", "d6/d41/classyaze_1_1cli_1_1ai_1_1anonymous__namespace_02ai__gui__controller__test_8cc_03_1_1AIGUIControllerTest.html", "d6/d41/classyaze_1_1cli_1_1ai_1_1anonymous__namespace_02ai__gui__controller__test_8cc_03_1_1AIGUIControllerTest" ],
            [ "MockGuiAutomationClient", "d9/d8f/classyaze_1_1cli_1_1ai_1_1anonymous__namespace_02ai__gui__controller__test_8cc_03_1_1MockGuiAutomationClient.html", "d9/d8f/classyaze_1_1cli_1_1ai_1_1anonymous__namespace_02ai__gui__controller__test_8cc_03_1_1MockGuiAutomationClient" ]
          ] ],
          [ "ActionRefinement", "d4/d66/structyaze_1_1cli_1_1ai_1_1ActionRefinement.html", "d4/d66/structyaze_1_1cli_1_1ai_1_1ActionRefinement" ],
          [ "AIAction", "d3/d8b/structyaze_1_1cli_1_1ai_1_1AIAction.html", "d3/d8b/structyaze_1_1cli_1_1ai_1_1AIAction" ],
          [ "AIActionParser", "df/def/classyaze_1_1cli_1_1ai_1_1AIActionParser.html", null ],
          [ "AIGUIController", "d0/da5/classyaze_1_1cli_1_1ai_1_1AIGUIController.html", "d0/da5/classyaze_1_1cli_1_1ai_1_1AIGUIController" ],
          [ "ControlLoopConfig", "d2/d73/structyaze_1_1cli_1_1ai_1_1ControlLoopConfig.html", "d2/d73/structyaze_1_1cli_1_1ai_1_1ControlLoopConfig" ],
          [ "ControlResult", "d0/dfd/structyaze_1_1cli_1_1ai_1_1ControlResult.html", "d0/dfd/structyaze_1_1cli_1_1ai_1_1ControlResult" ],
          [ "VisionActionRefiner", "df/dcb/classyaze_1_1cli_1_1ai_1_1VisionActionRefiner.html", "df/dcb/classyaze_1_1cli_1_1ai_1_1VisionActionRefiner" ],
          [ "VisionAnalysisResult", "d2/d07/structyaze_1_1cli_1_1ai_1_1VisionAnalysisResult.html", "d2/d07/structyaze_1_1cli_1_1ai_1_1VisionAnalysisResult" ]
        ] ],
        [ "anonymous_namespace{tile16_proposal_generator_test.cc}", "d6/d5e/namespaceyaze_1_1cli_1_1anonymous__namespace_02tile16__proposal__generator__test_8cc_03.html", [
          [ "Tile16ProposalGeneratorTest", "d9/d88/classyaze_1_1cli_1_1anonymous__namespace_02tile16__proposal__generator__test_8cc_03_1_1Tile16ProposalGeneratorTest.html", "d9/d88/classyaze_1_1cli_1_1anonymous__namespace_02tile16__proposal__generator__test_8cc_03_1_1Tile16ProposalGeneratorTest" ]
        ] ],
        [ "gui", "d9/db5/namespaceyaze_1_1cli_1_1gui.html", [
          [ "GuiActionGenerator", "df/d9d/classyaze_1_1cli_1_1gui_1_1GuiActionGenerator.html", "df/d9d/classyaze_1_1cli_1_1gui_1_1GuiActionGenerator" ]
        ] ],
        [ "net", "d3/dc3/namespaceyaze_1_1cli_1_1net.html", [
          [ "Z3edNetworkClient", "da/dfb/classyaze_1_1cli_1_1net_1_1Z3edNetworkClient.html", "da/dfb/classyaze_1_1cli_1_1net_1_1Z3edNetworkClient" ]
        ] ],
        [ "overworld", "d5/d93/namespaceyaze_1_1cli_1_1overworld.html", [
          [ "EntranceDetails", "d9/df8/structyaze_1_1cli_1_1overworld_1_1EntranceDetails.html", "d9/df8/structyaze_1_1cli_1_1overworld_1_1EntranceDetails" ],
          [ "MapSummary", "dd/d26/structyaze_1_1cli_1_1overworld_1_1MapSummary.html", "dd/d26/structyaze_1_1cli_1_1overworld_1_1MapSummary" ],
          [ "OverworldSprite", "d0/d4c/structyaze_1_1cli_1_1overworld_1_1OverworldSprite.html", "d0/d4c/structyaze_1_1cli_1_1overworld_1_1OverworldSprite" ],
          [ "SpriteQuery", "d7/dd9/structyaze_1_1cli_1_1overworld_1_1SpriteQuery.html", "d7/dd9/structyaze_1_1cli_1_1overworld_1_1SpriteQuery" ],
          [ "TileMatch", "dd/d10/structyaze_1_1cli_1_1overworld_1_1TileMatch.html", "dd/d10/structyaze_1_1cli_1_1overworld_1_1TileMatch" ],
          [ "TileSearchOptions", "da/d5b/structyaze_1_1cli_1_1overworld_1_1TileSearchOptions.html", "da/d5b/structyaze_1_1cli_1_1overworld_1_1TileSearchOptions" ],
          [ "TileStatistics", "de/d83/structyaze_1_1cli_1_1overworld_1_1TileStatistics.html", "de/d83/structyaze_1_1cli_1_1overworld_1_1TileStatistics" ],
          [ "WarpEntry", "d1/d67/structyaze_1_1cli_1_1overworld_1_1WarpEntry.html", "d1/d67/structyaze_1_1cli_1_1overworld_1_1WarpEntry" ],
          [ "WarpQuery", "d0/dcb/structyaze_1_1cli_1_1overworld_1_1WarpQuery.html", "d0/dcb/structyaze_1_1cli_1_1overworld_1_1WarpQuery" ]
        ] ],
        [ "tui", "da/d0b/namespaceyaze_1_1cli_1_1tui.html", [
          [ "ChatTUI", "d9/dad/classyaze_1_1cli_1_1tui_1_1ChatTUI.html", "d9/dad/classyaze_1_1cli_1_1tui_1_1ChatTUI" ]
        ] ],
        [ "util", "d1/d87/namespaceyaze_1_1cli_1_1util.html", [
          [ "LoadingIndicator", "d8/d03/classyaze_1_1cli_1_1util_1_1LoadingIndicator.html", "d8/d03/classyaze_1_1cli_1_1util_1_1LoadingIndicator" ]
        ] ],
        [ "Agent", "d9/dee/classyaze_1_1cli_1_1Agent.html", "d9/dee/classyaze_1_1cli_1_1Agent" ],
        [ "AgentResponse", "db/d5f/structyaze_1_1cli_1_1AgentResponse.html", "db/d5f/structyaze_1_1cli_1_1AgentResponse" ],
        [ "AIService", "d2/d2a/classyaze_1_1cli_1_1AIService.html", "d2/d2a/classyaze_1_1cli_1_1AIService" ],
        [ "AIServiceConfig", "dd/dd2/structyaze_1_1cli_1_1AIServiceConfig.html", "dd/dd2/structyaze_1_1cli_1_1AIServiceConfig" ],
        [ "ApplyPatch", "dd/d64/classyaze_1_1cli_1_1ApplyPatch.html", "dd/d64/classyaze_1_1cli_1_1ApplyPatch" ],
        [ "AsarPatch", "d7/d3f/classyaze_1_1cli_1_1AsarPatch.html", "d7/d3f/classyaze_1_1cli_1_1AsarPatch" ],
        [ "AsarPatchComponent", "d2/d2b/classyaze_1_1cli_1_1AsarPatchComponent.html", "d2/d2b/classyaze_1_1cli_1_1AsarPatchComponent" ],
        [ "AssertionOutcome", "d4/dae/structyaze_1_1cli_1_1AssertionOutcome.html", "d4/dae/structyaze_1_1cli_1_1AssertionOutcome" ],
        [ "AutocompleteEngine", "da/d90/classyaze_1_1cli_1_1AutocompleteEngine.html", "da/d90/classyaze_1_1cli_1_1AutocompleteEngine" ],
        [ "AutomationResult", "d4/daf/structyaze_1_1cli_1_1AutomationResult.html", "d4/daf/structyaze_1_1cli_1_1AutomationResult" ],
        [ "Backup", "d5/d4f/classyaze_1_1cli_1_1Backup.html", "d5/d4f/classyaze_1_1cli_1_1Backup" ],
        [ "CommandHandler", "dd/d80/classyaze_1_1cli_1_1CommandHandler.html", "dd/d80/classyaze_1_1cli_1_1CommandHandler" ],
        [ "CommandInfo", "dd/d22/structyaze_1_1cli_1_1CommandInfo.html", "dd/d22/structyaze_1_1cli_1_1CommandInfo" ],
        [ "CommandPalette", "d7/d60/classyaze_1_1cli_1_1CommandPalette.html", "d7/d60/classyaze_1_1cli_1_1CommandPalette" ],
        [ "CommandPaletteComponent", "dc/d14/classyaze_1_1cli_1_1CommandPaletteComponent.html", "dc/d14/classyaze_1_1cli_1_1CommandPaletteComponent" ],
        [ "Compress", "de/d92/classyaze_1_1cli_1_1Compress.html", "de/d92/classyaze_1_1cli_1_1Compress" ],
        [ "Context", "d0/d13/structyaze_1_1cli_1_1Context.html", "d0/d13/structyaze_1_1cli_1_1Context" ],
        [ "CreatePatch", "d7/d65/classyaze_1_1cli_1_1CreatePatch.html", "d7/d65/classyaze_1_1cli_1_1CreatePatch" ],
        [ "Decompress", "dc/db3/classyaze_1_1cli_1_1Decompress.html", "dc/db3/classyaze_1_1cli_1_1Decompress" ],
        [ "DiscoveredWindowInfo", "d9/d5d/structyaze_1_1cli_1_1DiscoveredWindowInfo.html", "d9/d5d/structyaze_1_1cli_1_1DiscoveredWindowInfo" ],
        [ "DiscoverWidgetsQuery", "d1/d3b/structyaze_1_1cli_1_1DiscoverWidgetsQuery.html", "d1/d3b/structyaze_1_1cli_1_1DiscoverWidgetsQuery" ],
        [ "DiscoverWidgetsResult", "dc/d5a/structyaze_1_1cli_1_1DiscoverWidgetsResult.html", "dc/d5a/structyaze_1_1cli_1_1DiscoverWidgetsResult" ],
        [ "DungeonExport", "d7/dc5/classyaze_1_1cli_1_1DungeonExport.html", "d7/dc5/classyaze_1_1cli_1_1DungeonExport" ],
        [ "DungeonListObjects", "da/dc4/classyaze_1_1cli_1_1DungeonListObjects.html", "da/dc4/classyaze_1_1cli_1_1DungeonListObjects" ],
        [ "EnhancedChatComponent", "d6/d00/classyaze_1_1cli_1_1EnhancedChatComponent.html", "d6/d00/classyaze_1_1cli_1_1EnhancedChatComponent" ],
        [ "EnhancedStatusPanel", "d1/d6e/classyaze_1_1cli_1_1EnhancedStatusPanel.html", "d1/d6e/classyaze_1_1cli_1_1EnhancedStatusPanel" ],
        [ "Expand", "d7/d30/classyaze_1_1cli_1_1Expand.html", "d7/d30/classyaze_1_1cli_1_1Expand" ],
        [ "FewShotExample", "db/de0/structyaze_1_1cli_1_1FewShotExample.html", "db/de0/structyaze_1_1cli_1_1FewShotExample" ],
        [ "GeminiAIService", "db/d2d/classyaze_1_1cli_1_1GeminiAIService.html", "db/d2d/classyaze_1_1cli_1_1GeminiAIService" ],
        [ "GeminiConfig", "dc/d0c/structyaze_1_1cli_1_1GeminiConfig.html", "dc/d0c/structyaze_1_1cli_1_1GeminiConfig" ],
        [ "GfxExport", "dd/d8b/classyaze_1_1cli_1_1GfxExport.html", "dd/d8b/classyaze_1_1cli_1_1GfxExport" ],
        [ "GfxImport", "d2/d55/classyaze_1_1cli_1_1GfxImport.html", "d2/d55/classyaze_1_1cli_1_1GfxImport" ],
        [ "GuiAutomationClient", "d2/d67/classyaze_1_1cli_1_1GuiAutomationClient.html", "d2/d67/classyaze_1_1cli_1_1GuiAutomationClient" ],
        [ "HarnessTestSummary", "db/d43/structyaze_1_1cli_1_1HarnessTestSummary.html", "db/d43/structyaze_1_1cli_1_1HarnessTestSummary" ],
        [ "LayoutConfig", "d8/d47/structyaze_1_1cli_1_1LayoutConfig.html", "d8/d47/structyaze_1_1cli_1_1LayoutConfig" ],
        [ "ListTestsResult", "d7/dce/structyaze_1_1cli_1_1ListTestsResult.html", "d7/dce/structyaze_1_1cli_1_1ListTestsResult" ],
        [ "MockAIService", "df/d18/classyaze_1_1cli_1_1MockAIService.html", "df/d18/classyaze_1_1cli_1_1MockAIService" ],
        [ "ModernCLI", "df/db9/classyaze_1_1cli_1_1ModernCLI.html", "df/db9/classyaze_1_1cli_1_1ModernCLI" ],
        [ "OllamaAIService", "dc/d1d/classyaze_1_1cli_1_1OllamaAIService.html", "dc/d1d/classyaze_1_1cli_1_1OllamaAIService" ],
        [ "OllamaConfig", "d0/d3d/structyaze_1_1cli_1_1OllamaConfig.html", "d0/d3d/structyaze_1_1cli_1_1OllamaConfig" ],
        [ "Open", "de/d8f/classyaze_1_1cli_1_1Open.html", "de/d8f/classyaze_1_1cli_1_1Open" ],
        [ "OverworldDescribeMap", "d6/dbf/classyaze_1_1cli_1_1OverworldDescribeMap.html", "d6/dbf/classyaze_1_1cli_1_1OverworldDescribeMap" ],
        [ "OverworldFindTile", "d0/d1b/classyaze_1_1cli_1_1OverworldFindTile.html", "d0/d1b/classyaze_1_1cli_1_1OverworldFindTile" ],
        [ "OverworldGetTile", "d7/d09/classyaze_1_1cli_1_1OverworldGetTile.html", "d7/d09/classyaze_1_1cli_1_1OverworldGetTile" ],
        [ "OverworldGetVisibleRegion", "d5/d0f/classyaze_1_1cli_1_1OverworldGetVisibleRegion.html", "d5/d0f/classyaze_1_1cli_1_1OverworldGetVisibleRegion" ],
        [ "OverworldListWarps", "d7/d5d/classyaze_1_1cli_1_1OverworldListWarps.html", "d7/d5d/classyaze_1_1cli_1_1OverworldListWarps" ],
        [ "OverworldScrollTo", "d4/de8/classyaze_1_1cli_1_1OverworldScrollTo.html", "d4/de8/classyaze_1_1cli_1_1OverworldScrollTo" ],
        [ "OverworldSelectRect", "db/dd0/classyaze_1_1cli_1_1OverworldSelectRect.html", "db/dd0/classyaze_1_1cli_1_1OverworldSelectRect" ],
        [ "OverworldSetTile", "da/d7a/classyaze_1_1cli_1_1OverworldSetTile.html", "da/d7a/classyaze_1_1cli_1_1OverworldSetTile" ],
        [ "OverworldSetZoom", "db/d5a/classyaze_1_1cli_1_1OverworldSetZoom.html", "db/d5a/classyaze_1_1cli_1_1OverworldSetZoom" ],
        [ "Palette", "d3/d6c/classyaze_1_1cli_1_1Palette.html", "d3/d6c/classyaze_1_1cli_1_1Palette" ],
        [ "PaletteEditorComponent", "d8/d3c/classyaze_1_1cli_1_1PaletteEditorComponent.html", "d8/d3c/classyaze_1_1cli_1_1PaletteEditorComponent" ],
        [ "PaletteExport", "da/d77/classyaze_1_1cli_1_1PaletteExport.html", "da/d77/classyaze_1_1cli_1_1PaletteExport" ],
        [ "PaletteImport", "d7/d47/classyaze_1_1cli_1_1PaletteImport.html", "d7/d47/classyaze_1_1cli_1_1PaletteImport" ],
        [ "PanelState", "d6/d99/structyaze_1_1cli_1_1PanelState.html", "d6/d99/structyaze_1_1cli_1_1PanelState" ],
        [ "PcToSnesCommand", "dd/d06/classyaze_1_1cli_1_1PcToSnesCommand.html", "dd/d06/classyaze_1_1cli_1_1PcToSnesCommand" ],
        [ "PolicyEvaluator", "d5/d67/classyaze_1_1cli_1_1PolicyEvaluator.html", "d5/d67/classyaze_1_1cli_1_1PolicyEvaluator" ],
        [ "PolicyResult", "da/d57/structyaze_1_1cli_1_1PolicyResult.html", "da/d57/structyaze_1_1cli_1_1PolicyResult" ],
        [ "PolicyViolation", "d2/d16/structyaze_1_1cli_1_1PolicyViolation.html", "d2/d16/structyaze_1_1cli_1_1PolicyViolation" ],
        [ "ProjectBuild", "d4/d4b/classyaze_1_1cli_1_1ProjectBuild.html", "d4/d4b/classyaze_1_1cli_1_1ProjectBuild" ],
        [ "ProjectInit", "d9/d3b/classyaze_1_1cli_1_1ProjectInit.html", "d9/d3b/classyaze_1_1cli_1_1ProjectInit" ],
        [ "PromptBuilder", "d2/d20/classyaze_1_1cli_1_1PromptBuilder.html", "d2/d20/classyaze_1_1cli_1_1PromptBuilder" ],
        [ "ProposalRegistry", "de/dd4/classyaze_1_1cli_1_1ProposalRegistry.html", "de/dd4/classyaze_1_1cli_1_1ProposalRegistry" ],
        [ "ReadFromRom", "d1/d72/classyaze_1_1cli_1_1ReadFromRom.html", "d1/d72/classyaze_1_1cli_1_1ReadFromRom" ],
        [ "ReplayTestResult", "dc/d57/structyaze_1_1cli_1_1ReplayTestResult.html", "dc/d57/structyaze_1_1cli_1_1ReplayTestResult" ],
        [ "ResourceAction", "dc/d64/structyaze_1_1cli_1_1ResourceAction.html", "dc/d64/structyaze_1_1cli_1_1ResourceAction" ],
        [ "ResourceArgument", "da/dc6/structyaze_1_1cli_1_1ResourceArgument.html", "da/dc6/structyaze_1_1cli_1_1ResourceArgument" ],
        [ "ResourceCatalog", "d4/d02/classyaze_1_1cli_1_1ResourceCatalog.html", "d4/d02/classyaze_1_1cli_1_1ResourceCatalog" ],
        [ "ResourceContextBuilder", "de/d71/classyaze_1_1cli_1_1ResourceContextBuilder.html", "de/d71/classyaze_1_1cli_1_1ResourceContextBuilder" ],
        [ "ResourceSchema", "d8/d29/structyaze_1_1cli_1_1ResourceSchema.html", "d8/d29/structyaze_1_1cli_1_1ResourceSchema" ],
        [ "RomContext", "d4/d2e/structyaze_1_1cli_1_1RomContext.html", "d4/d2e/structyaze_1_1cli_1_1RomContext" ],
        [ "RomDiff", "d1/d9c/classyaze_1_1cli_1_1RomDiff.html", "d1/d9c/classyaze_1_1cli_1_1RomDiff" ],
        [ "RomGenerateGolden", "d2/d4a/classyaze_1_1cli_1_1RomGenerateGolden.html", "d2/d4a/classyaze_1_1cli_1_1RomGenerateGolden" ],
        [ "RomInfo", "d2/de6/classyaze_1_1cli_1_1RomInfo.html", "d2/de6/classyaze_1_1cli_1_1RomInfo" ],
        [ "RomSandboxManager", "d5/dbc/classyaze_1_1cli_1_1RomSandboxManager.html", "d5/dbc/classyaze_1_1cli_1_1RomSandboxManager" ],
        [ "RomValidate", "d6/d8e/classyaze_1_1cli_1_1RomValidate.html", "d6/d8e/classyaze_1_1cli_1_1RomValidate" ],
        [ "SnesToPcCommand", "d9/d12/classyaze_1_1cli_1_1SnesToPcCommand.html", "d9/d12/classyaze_1_1cli_1_1SnesToPcCommand" ],
        [ "SpriteCreate", "da/d30/classyaze_1_1cli_1_1SpriteCreate.html", "da/d30/classyaze_1_1cli_1_1SpriteCreate" ],
        [ "StartRecordingResult", "d1/de8/structyaze_1_1cli_1_1StartRecordingResult.html", "d1/de8/structyaze_1_1cli_1_1StartRecordingResult" ],
        [ "StopRecordingResult", "db/de2/structyaze_1_1cli_1_1StopRecordingResult.html", "db/de2/structyaze_1_1cli_1_1StopRecordingResult" ],
        [ "Suggestion", "d6/d3a/structyaze_1_1cli_1_1Suggestion.html", "d6/d3a/structyaze_1_1cli_1_1Suggestion" ],
        [ "TestCaseDefinition", "d1/df7/structyaze_1_1cli_1_1TestCaseDefinition.html", "d1/df7/structyaze_1_1cli_1_1TestCaseDefinition" ],
        [ "TestCaseRunResult", "dd/d80/structyaze_1_1cli_1_1TestCaseRunResult.html", "dd/d80/structyaze_1_1cli_1_1TestCaseRunResult" ],
        [ "TestGroupDefinition", "dd/d7e/structyaze_1_1cli_1_1TestGroupDefinition.html", "dd/d7e/structyaze_1_1cli_1_1TestGroupDefinition" ],
        [ "TestResultDetails", "d4/db9/structyaze_1_1cli_1_1TestResultDetails.html", "d4/db9/structyaze_1_1cli_1_1TestResultDetails" ],
        [ "TestStatusDetails", "dd/d5e/structyaze_1_1cli_1_1TestStatusDetails.html", "dd/d5e/structyaze_1_1cli_1_1TestStatusDetails" ],
        [ "TestStep", "d6/d4b/structyaze_1_1cli_1_1TestStep.html", "d6/d4b/structyaze_1_1cli_1_1TestStep" ],
        [ "TestSuiteConfig", "de/d77/structyaze_1_1cli_1_1TestSuiteConfig.html", "de/d77/structyaze_1_1cli_1_1TestSuiteConfig" ],
        [ "TestSuiteDefinition", "de/d68/structyaze_1_1cli_1_1TestSuiteDefinition.html", "de/d68/structyaze_1_1cli_1_1TestSuiteDefinition" ],
        [ "TestSuiteRunSummary", "d1/d9d/structyaze_1_1cli_1_1TestSuiteRunSummary.html", "d1/d9d/structyaze_1_1cli_1_1TestSuiteRunSummary" ],
        [ "TestWorkflow", "de/d85/structyaze_1_1cli_1_1TestWorkflow.html", "de/d85/structyaze_1_1cli_1_1TestWorkflow" ],
        [ "TestWorkflowGenerator", "de/da1/classyaze_1_1cli_1_1TestWorkflowGenerator.html", "de/da1/classyaze_1_1cli_1_1TestWorkflowGenerator" ],
        [ "Tile16Change", "d6/d52/structyaze_1_1cli_1_1Tile16Change.html", "d6/d52/structyaze_1_1cli_1_1Tile16Change" ],
        [ "Tile16Proposal", "d8/d1c/structyaze_1_1cli_1_1Tile16Proposal.html", "d8/d1c/structyaze_1_1cli_1_1Tile16Proposal" ],
        [ "Tile16ProposalGenerator", "d4/d53/classyaze_1_1cli_1_1Tile16ProposalGenerator.html", "d4/d53/classyaze_1_1cli_1_1Tile16ProposalGenerator" ],
        [ "Tile16Transfer", "d8/d7c/classyaze_1_1cli_1_1Tile16Transfer.html", "d8/d7c/classyaze_1_1cli_1_1Tile16Transfer" ],
        [ "ToolArgument", "d6/d40/structyaze_1_1cli_1_1ToolArgument.html", "d6/d40/structyaze_1_1cli_1_1ToolArgument" ],
        [ "ToolCall", "df/d6e/structyaze_1_1cli_1_1ToolCall.html", "df/d6e/structyaze_1_1cli_1_1ToolCall" ],
        [ "ToolSpecification", "d5/dcb/structyaze_1_1cli_1_1ToolSpecification.html", "d5/dcb/structyaze_1_1cli_1_1ToolSpecification" ],
        [ "TuiComponent", "dc/d6b/classyaze_1_1cli_1_1TuiComponent.html", "dc/d6b/classyaze_1_1cli_1_1TuiComponent" ],
        [ "UnifiedLayout", "db/d23/classyaze_1_1cli_1_1UnifiedLayout.html", "db/d23/classyaze_1_1cli_1_1UnifiedLayout" ],
        [ "WidgetBoundingBox", "d7/d72/structyaze_1_1cli_1_1WidgetBoundingBox.html", "d7/d72/structyaze_1_1cli_1_1WidgetBoundingBox" ],
        [ "WidgetDescriptor", "d0/d85/structyaze_1_1cli_1_1WidgetDescriptor.html", "d0/d85/structyaze_1_1cli_1_1WidgetDescriptor" ]
      ] ],
      [ "core", "db/d33/namespaceyaze_1_1core.html", [
        [ "anonymous_namespace{asar_wrapper_test.cc}", "da/d36/namespaceyaze_1_1core_1_1anonymous__namespace_02asar__wrapper__test_8cc_03.html", [
          [ "AsarWrapperTest", "da/d84/classyaze_1_1core_1_1anonymous__namespace_02asar__wrapper__test_8cc_03_1_1AsarWrapperTest.html", "da/d84/classyaze_1_1core_1_1anonymous__namespace_02asar__wrapper__test_8cc_03_1_1AsarWrapperTest" ]
        ] ],
        [ "AsarPatchResult", "de/d0c/structyaze_1_1core_1_1AsarPatchResult.html", "de/d0c/structyaze_1_1core_1_1AsarPatchResult" ],
        [ "AsarSymbol", "de/da4/structyaze_1_1core_1_1AsarSymbol.html", "de/da4/structyaze_1_1core_1_1AsarSymbol" ],
        [ "AsarWrapper", "da/dd2/classyaze_1_1core_1_1AsarWrapper.html", "da/dd2/classyaze_1_1core_1_1AsarWrapper" ],
        [ "Controller", "d4/d84/classyaze_1_1core_1_1Controller.html", "d4/d84/classyaze_1_1core_1_1Controller" ],
        [ "FeatureFlags", "d8/d3f/classyaze_1_1core_1_1FeatureFlags.html", "d8/d3f/classyaze_1_1core_1_1FeatureFlags" ],
        [ "ProjectManager", "d9/d7f/classyaze_1_1core_1_1ProjectManager.html", "d9/d7f/classyaze_1_1core_1_1ProjectManager" ],
        [ "ProjectMetadata", "d8/d0c/structyaze_1_1core_1_1ProjectMetadata.html", "d8/d0c/structyaze_1_1core_1_1ProjectMetadata" ],
        [ "RecentFilesManager", "d8/d4b/classyaze_1_1core_1_1RecentFilesManager.html", "d8/d4b/classyaze_1_1core_1_1RecentFilesManager" ],
        [ "ResourceLabelManager", "d8/d4d/structyaze_1_1core_1_1ResourceLabelManager.html", "d8/d4d/structyaze_1_1core_1_1ResourceLabelManager" ],
        [ "TimingManager", "d5/d77/classyaze_1_1core_1_1TimingManager.html", "d5/d77/classyaze_1_1core_1_1TimingManager" ],
        [ "WidgetState", "d1/d17/structyaze_1_1core_1_1WidgetState.html", "d1/d17/structyaze_1_1core_1_1WidgetState" ],
        [ "Window", "de/d86/structyaze_1_1core_1_1Window.html", "de/d86/structyaze_1_1core_1_1Window" ],
        [ "WorkspaceSettings", "d1/def/structyaze_1_1core_1_1WorkspaceSettings.html", "d1/def/structyaze_1_1core_1_1WorkspaceSettings" ],
        [ "YazeProject", "da/d5e/structyaze_1_1core_1_1YazeProject.html", "da/d5e/structyaze_1_1core_1_1YazeProject" ]
      ] ],
      [ "editor", "d1/d3e/namespaceyaze_1_1editor.html", [
        [ "palette_internal", "d9/d8b/namespaceyaze_1_1editor_1_1palette__internal.html", [
          [ "PaletteChange", "dc/dc6/structyaze_1_1editor_1_1palette__internal_1_1PaletteChange.html", "dc/dc6/structyaze_1_1editor_1_1palette__internal_1_1PaletteChange" ],
          [ "PaletteEditorHistory", "dc/d39/classyaze_1_1editor_1_1palette__internal_1_1PaletteEditorHistory.html", "dc/d39/classyaze_1_1editor_1_1palette__internal_1_1PaletteEditorHistory" ]
        ] ],
        [ "test", "d1/dac/namespaceyaze_1_1editor_1_1test.html", [
          [ "Tile16EditorIntegrationTest", "d8/d78/classyaze_1_1editor_1_1test_1_1Tile16EditorIntegrationTest.html", "d8/d78/classyaze_1_1editor_1_1test_1_1Tile16EditorIntegrationTest" ]
        ] ],
        [ "zsprite", "d8/d17/namespaceyaze_1_1editor_1_1zsprite.html", [
          [ "AnimationGroup", "dc/d2c/structyaze_1_1editor_1_1zsprite_1_1AnimationGroup.html", "dc/d2c/structyaze_1_1editor_1_1zsprite_1_1AnimationGroup" ],
          [ "OamTile", "dd/d2f/structyaze_1_1editor_1_1zsprite_1_1OamTile.html", "dd/d2f/structyaze_1_1editor_1_1zsprite_1_1OamTile" ],
          [ "SpriteProperty", "d9/d26/structyaze_1_1editor_1_1zsprite_1_1SpriteProperty.html", "d9/d26/structyaze_1_1editor_1_1zsprite_1_1SpriteProperty" ],
          [ "SubEditor", "de/d9d/structyaze_1_1editor_1_1zsprite_1_1SubEditor.html", "de/d9d/structyaze_1_1editor_1_1zsprite_1_1SubEditor" ],
          [ "UserRoutine", "da/d81/structyaze_1_1editor_1_1zsprite_1_1UserRoutine.html", "da/d81/structyaze_1_1editor_1_1zsprite_1_1UserRoutine" ],
          [ "ZSprite", "df/d41/structyaze_1_1editor_1_1zsprite_1_1ZSprite.html", "df/d41/structyaze_1_1editor_1_1zsprite_1_1ZSprite" ]
        ] ],
        [ "AgentChatHistoryCodec", "d5/dfa/classyaze_1_1editor_1_1AgentChatHistoryCodec.html", "d5/dfa/classyaze_1_1editor_1_1AgentChatHistoryCodec" ],
        [ "AgentChatHistoryPopup", "d2/d4e/classyaze_1_1editor_1_1AgentChatHistoryPopup.html", "d2/d4e/classyaze_1_1editor_1_1AgentChatHistoryPopup" ],
        [ "AgentChatWidget", "d9/d2b/classyaze_1_1editor_1_1AgentChatWidget.html", "d9/d2b/classyaze_1_1editor_1_1AgentChatWidget" ],
        [ "AgentCollaborationCoordinator", "d3/d4f/classyaze_1_1editor_1_1AgentCollaborationCoordinator.html", "d3/d4f/classyaze_1_1editor_1_1AgentCollaborationCoordinator" ],
        [ "AgentEditor", "d6/d0d/classyaze_1_1editor_1_1AgentEditor.html", "d6/d0d/classyaze_1_1editor_1_1AgentEditor" ],
        [ "AgentUITheme", "db/d3d/structyaze_1_1editor_1_1AgentUITheme.html", "db/d3d/structyaze_1_1editor_1_1AgentUITheme" ],
        [ "AssemblyEditor", "d4/d45/classyaze_1_1editor_1_1AssemblyEditor.html", "d4/d45/classyaze_1_1editor_1_1AssemblyEditor" ],
        [ "CommandEntry", "dd/dee/structyaze_1_1editor_1_1CommandEntry.html", "dd/dee/structyaze_1_1editor_1_1CommandEntry" ],
        [ "CommandManager", "d3/d8a/classyaze_1_1editor_1_1CommandManager.html", "d3/d8a/classyaze_1_1editor_1_1CommandManager" ],
        [ "CommandPalette", "df/db6/classyaze_1_1editor_1_1CommandPalette.html", "df/db6/classyaze_1_1editor_1_1CommandPalette" ],
        [ "DictionaryEntry", "d7/dca/structyaze_1_1editor_1_1DictionaryEntry.html", "d7/dca/structyaze_1_1editor_1_1DictionaryEntry" ],
        [ "DungeonCanvasViewer", "d2/de7/classyaze_1_1editor_1_1DungeonCanvasViewer.html", "d2/de7/classyaze_1_1editor_1_1DungeonCanvasViewer" ],
        [ "DungeonEditorV2", "da/d45/classyaze_1_1editor_1_1DungeonEditorV2.html", "da/d45/classyaze_1_1editor_1_1DungeonEditorV2" ],
        [ "DungeonObjectInteraction", "d1/d22/classyaze_1_1editor_1_1DungeonObjectInteraction.html", "d1/d22/classyaze_1_1editor_1_1DungeonObjectInteraction" ],
        [ "DungeonObjectSelector", "dc/d4f/classyaze_1_1editor_1_1DungeonObjectSelector.html", "dc/d4f/classyaze_1_1editor_1_1DungeonObjectSelector" ],
        [ "DungeonRoomLoader", "d6/d60/classyaze_1_1editor_1_1DungeonRoomLoader.html", "d6/d60/classyaze_1_1editor_1_1DungeonRoomLoader" ],
        [ "DungeonRoomSelector", "db/de8/classyaze_1_1editor_1_1DungeonRoomSelector.html", "db/de8/classyaze_1_1editor_1_1DungeonRoomSelector" ],
        [ "DungeonToolset", "db/d00/classyaze_1_1editor_1_1DungeonToolset.html", "db/d00/classyaze_1_1editor_1_1DungeonToolset" ],
        [ "DungeonUsageTracker", "dd/d4b/classyaze_1_1editor_1_1DungeonUsageTracker.html", "dd/d4b/classyaze_1_1editor_1_1DungeonUsageTracker" ],
        [ "Editor", "d3/d9f/classyaze_1_1editor_1_1Editor.html", "d3/d9f/classyaze_1_1editor_1_1Editor" ],
        [ "EditorContext", "dc/d69/structyaze_1_1editor_1_1EditorContext.html", "dc/d69/structyaze_1_1editor_1_1EditorContext" ],
        [ "EditorInfo", "d1/dc6/structyaze_1_1editor_1_1EditorInfo.html", "d1/dc6/structyaze_1_1editor_1_1EditorInfo" ],
        [ "EditorManager", "dd/d12/classyaze_1_1editor_1_1EditorManager.html", "dd/d12/classyaze_1_1editor_1_1EditorManager" ],
        [ "EditorSelectionDialog", "d9/da8/classyaze_1_1editor_1_1EditorSelectionDialog.html", "d9/da8/classyaze_1_1editor_1_1EditorSelectionDialog" ],
        [ "EditorSet", "d3/d21/classyaze_1_1editor_1_1EditorSet.html", "d3/d21/classyaze_1_1editor_1_1EditorSet" ],
        [ "ExampleAppPropertyEditor", "de/d7d/structyaze_1_1editor_1_1ExampleAppPropertyEditor.html", "de/d7d/structyaze_1_1editor_1_1ExampleAppPropertyEditor" ],
        [ "ExampleMemberInfo", "d5/db2/structyaze_1_1editor_1_1ExampleMemberInfo.html", "d5/db2/structyaze_1_1editor_1_1ExampleMemberInfo" ],
        [ "ExampleTreeNode", "d8/d9f/structyaze_1_1editor_1_1ExampleTreeNode.html", "d8/d9f/structyaze_1_1editor_1_1ExampleTreeNode" ],
        [ "ExtensionManager", "d8/d45/classyaze_1_1editor_1_1ExtensionManager.html", "d8/d45/classyaze_1_1editor_1_1ExtensionManager" ],
        [ "FolderItem", "da/d6e/structyaze_1_1editor_1_1FolderItem.html", "da/d6e/structyaze_1_1editor_1_1FolderItem" ],
        [ "GfxGroupEditor", "db/d71/classyaze_1_1editor_1_1GfxGroupEditor.html", "db/d71/classyaze_1_1editor_1_1GfxGroupEditor" ],
        [ "GraphicsEditor", "dc/d31/classyaze_1_1editor_1_1GraphicsEditor.html", "dc/d31/classyaze_1_1editor_1_1GraphicsEditor" ],
        [ "HistoryManager", "d9/d6c/classyaze_1_1editor_1_1HistoryManager.html", "d9/d6c/classyaze_1_1editor_1_1HistoryManager" ],
        [ "MapPropertiesSystem", "d6/d3c/classyaze_1_1editor_1_1MapPropertiesSystem.html", "d6/d3c/classyaze_1_1editor_1_1MapPropertiesSystem" ],
        [ "MemoryEditorWithDiffChecker", "d6/d9a/structyaze_1_1editor_1_1MemoryEditorWithDiffChecker.html", "d6/d9a/structyaze_1_1editor_1_1MemoryEditorWithDiffChecker" ],
        [ "MenuBuilder", "d7/d73/classyaze_1_1editor_1_1MenuBuilder.html", "d7/d73/classyaze_1_1editor_1_1MenuBuilder" ],
        [ "MenuManager", "df/d00/classyaze_1_1editor_1_1MenuManager.html", "df/d00/classyaze_1_1editor_1_1MenuManager" ],
        [ "MessageData", "d3/d89/structyaze_1_1editor_1_1MessageData.html", "d3/d89/structyaze_1_1editor_1_1MessageData" ],
        [ "MessageEditor", "d3/d6c/classyaze_1_1editor_1_1MessageEditor.html", "d3/d6c/classyaze_1_1editor_1_1MessageEditor" ],
        [ "MessagePreview", "dc/dd1/structyaze_1_1editor_1_1MessagePreview.html", "dc/dd1/structyaze_1_1editor_1_1MessagePreview" ],
        [ "MusicEditor", "db/d9a/classyaze_1_1editor_1_1MusicEditor.html", "db/d9a/classyaze_1_1editor_1_1MusicEditor" ],
        [ "ObjectEditorCard", "dc/dfc/classyaze_1_1editor_1_1ObjectEditorCard.html", "dc/dfc/classyaze_1_1editor_1_1ObjectEditorCard" ],
        [ "OverworldEditor", "d3/d44/classyaze_1_1editor_1_1OverworldEditor.html", "d3/d44/classyaze_1_1editor_1_1OverworldEditor" ],
        [ "OverworldEntityRenderer", "d8/d43/classyaze_1_1editor_1_1OverworldEntityRenderer.html", "d8/d43/classyaze_1_1editor_1_1OverworldEntityRenderer" ],
        [ "PaletteEditor", "d2/d46/classyaze_1_1editor_1_1PaletteEditor.html", "d2/d46/classyaze_1_1editor_1_1PaletteEditor" ],
        [ "ParsedElement", "da/d5e/structyaze_1_1editor_1_1ParsedElement.html", "da/d5e/structyaze_1_1editor_1_1ParsedElement" ],
        [ "PopupManager", "d3/d8d/classyaze_1_1editor_1_1PopupManager.html", "d3/d8d/classyaze_1_1editor_1_1PopupManager" ],
        [ "PopupParams", "df/dc2/structyaze_1_1editor_1_1PopupParams.html", "df/dc2/structyaze_1_1editor_1_1PopupParams" ],
        [ "ProjectFileEditor", "d8/ddf/classyaze_1_1editor_1_1ProjectFileEditor.html", "d8/ddf/classyaze_1_1editor_1_1ProjectFileEditor" ],
        [ "ProposalDrawer", "dd/dcc/classyaze_1_1editor_1_1ProposalDrawer.html", "dd/dcc/classyaze_1_1editor_1_1ProposalDrawer" ],
        [ "RecentProject", "d6/d7f/structyaze_1_1editor_1_1RecentProject.html", "d6/d7f/structyaze_1_1editor_1_1RecentProject" ],
        [ "ScreenEditor", "db/dcc/classyaze_1_1editor_1_1ScreenEditor.html", "db/dcc/classyaze_1_1editor_1_1ScreenEditor" ],
        [ "SettingsEditor", "dd/d00/classyaze_1_1editor_1_1SettingsEditor.html", "dd/d00/classyaze_1_1editor_1_1SettingsEditor" ],
        [ "Shortcut", "d5/d87/structyaze_1_1editor_1_1Shortcut.html", "d5/d87/structyaze_1_1editor_1_1Shortcut" ],
        [ "ShortcutManager", "d7/d84/classyaze_1_1editor_1_1ShortcutManager.html", "d7/d84/classyaze_1_1editor_1_1ShortcutManager" ],
        [ "SpriteEditor", "de/d76/classyaze_1_1editor_1_1SpriteEditor.html", "de/d76/classyaze_1_1editor_1_1SpriteEditor" ],
        [ "SpriteItem", "da/da6/structyaze_1_1editor_1_1SpriteItem.html", "da/da6/structyaze_1_1editor_1_1SpriteItem" ],
        [ "TextElement", "d8/dbd/structyaze_1_1editor_1_1TextElement.html", "d8/dbd/structyaze_1_1editor_1_1TextElement" ],
        [ "Tile16Editor", "db/d82/classyaze_1_1editor_1_1Tile16Editor.html", "db/d82/classyaze_1_1editor_1_1Tile16Editor" ],
        [ "Toast", "d2/d11/structyaze_1_1editor_1_1Toast.html", "d2/d11/structyaze_1_1editor_1_1Toast" ],
        [ "ToastManager", "d7/d92/classyaze_1_1editor_1_1ToastManager.html", "d7/d92/classyaze_1_1editor_1_1ToastManager" ],
        [ "UserSettings", "d8/d46/classyaze_1_1editor_1_1UserSettings.html", "d8/d46/classyaze_1_1editor_1_1UserSettings" ],
        [ "WelcomeScreen", "dc/daa/classyaze_1_1editor_1_1WelcomeScreen.html", "dc/daa/classyaze_1_1editor_1_1WelcomeScreen" ],
        [ "WorkspaceManager", "d9/d66/classyaze_1_1editor_1_1WorkspaceManager.html", "d9/d66/classyaze_1_1editor_1_1WorkspaceManager" ]
      ] ],
      [ "emu", "d6/d20/namespaceyaze_1_1emu.html", [
        [ "audio", "d2/dc8/namespaceyaze_1_1emu_1_1audio.html", [
          [ "AudioBackendFactory", "d9/d2b/classyaze_1_1emu_1_1audio_1_1AudioBackendFactory.html", "d9/d2b/classyaze_1_1emu_1_1audio_1_1AudioBackendFactory" ],
          [ "AudioConfig", "d1/da4/structyaze_1_1emu_1_1audio_1_1AudioConfig.html", "d1/da4/structyaze_1_1emu_1_1audio_1_1AudioConfig" ],
          [ "AudioStatus", "d5/dd6/structyaze_1_1emu_1_1audio_1_1AudioStatus.html", "d5/dd6/structyaze_1_1emu_1_1audio_1_1AudioStatus" ],
          [ "IAudioBackend", "d2/d50/classyaze_1_1emu_1_1audio_1_1IAudioBackend.html", "d2/d50/classyaze_1_1emu_1_1audio_1_1IAudioBackend" ],
          [ "SDL2AudioBackend", "d3/d03/classyaze_1_1emu_1_1audio_1_1SDL2AudioBackend.html", "d3/d03/classyaze_1_1emu_1_1audio_1_1SDL2AudioBackend" ]
        ] ],
        [ "debug", "d9/dd4/namespaceyaze_1_1emu_1_1debug.html", [
          [ "ApuHandshakeTracker", "db/dbe/classyaze_1_1emu_1_1debug_1_1ApuHandshakeTracker.html", "db/dbe/classyaze_1_1emu_1_1debug_1_1ApuHandshakeTracker" ],
          [ "DisassemblyEntry", "d1/df8/structyaze_1_1emu_1_1debug_1_1DisassemblyEntry.html", "d1/df8/structyaze_1_1emu_1_1debug_1_1DisassemblyEntry" ],
          [ "DisassemblyViewer", "d8/d31/classyaze_1_1emu_1_1debug_1_1DisassemblyViewer.html", "d8/d31/classyaze_1_1emu_1_1debug_1_1DisassemblyViewer" ]
        ] ],
        [ "input", "d5/df0/namespaceyaze_1_1emu_1_1input.html", [
          [ "ControllerState", "df/d22/structyaze_1_1emu_1_1input_1_1ControllerState.html", "df/d22/structyaze_1_1emu_1_1input_1_1ControllerState" ],
          [ "IInputBackend", "d9/d6f/classyaze_1_1emu_1_1input_1_1IInputBackend.html", "d9/d6f/classyaze_1_1emu_1_1input_1_1IInputBackend" ],
          [ "InputBackendFactory", "d1/de9/classyaze_1_1emu_1_1input_1_1InputBackendFactory.html", "d1/de9/classyaze_1_1emu_1_1input_1_1InputBackendFactory" ],
          [ "InputConfig", "de/d9a/structyaze_1_1emu_1_1input_1_1InputConfig.html", "de/d9a/structyaze_1_1emu_1_1input_1_1InputConfig" ],
          [ "InputManager", "de/d91/classyaze_1_1emu_1_1input_1_1InputManager.html", "de/d91/classyaze_1_1emu_1_1input_1_1InputManager" ],
          [ "NullInputBackend", "d2/d2c/classyaze_1_1emu_1_1input_1_1NullInputBackend.html", "d2/d2c/classyaze_1_1emu_1_1input_1_1NullInputBackend" ],
          [ "SDL2InputBackend", "df/dd3/classyaze_1_1emu_1_1input_1_1SDL2InputBackend.html", "df/dd3/classyaze_1_1emu_1_1input_1_1SDL2InputBackend" ]
        ] ],
        [ "Apu", "d7/da7/classyaze_1_1emu_1_1Apu.html", "d7/da7/classyaze_1_1emu_1_1Apu" ],
        [ "ApuCallbacks", "df/d64/structyaze_1_1emu_1_1ApuCallbacks.html", "df/d64/structyaze_1_1emu_1_1ApuCallbacks" ],
        [ "ApuDspTest", "d2/d3e/classyaze_1_1emu_1_1ApuDspTest.html", "d2/d3e/classyaze_1_1emu_1_1ApuDspTest" ],
        [ "ApuIplHandshakeTest", "da/d87/classyaze_1_1emu_1_1ApuIplHandshakeTest.html", "da/d87/classyaze_1_1emu_1_1ApuIplHandshakeTest" ],
        [ "AsmParser", "da/dbc/classyaze_1_1emu_1_1AsmParser.html", "da/dbc/classyaze_1_1emu_1_1AsmParser" ],
        [ "AudioRam", "db/dc9/classyaze_1_1emu_1_1AudioRam.html", "db/dc9/classyaze_1_1emu_1_1AudioRam" ],
        [ "AudioRamImpl", "d5/da7/classyaze_1_1emu_1_1AudioRamImpl.html", "d5/da7/classyaze_1_1emu_1_1AudioRamImpl" ],
        [ "BackgroundLayer", "d1/dc4/structyaze_1_1emu_1_1BackgroundLayer.html", "d1/dc4/structyaze_1_1emu_1_1BackgroundLayer" ],
        [ "BGHOFS", "d1/d74/structyaze_1_1emu_1_1BGHOFS.html", "d1/d74/structyaze_1_1emu_1_1BGHOFS" ],
        [ "BgLayer", "dd/db7/structyaze_1_1emu_1_1BgLayer.html", "dd/db7/structyaze_1_1emu_1_1BgLayer" ],
        [ "BGMODE", "d2/dc6/structyaze_1_1emu_1_1BGMODE.html", "d2/dc6/structyaze_1_1emu_1_1BGMODE" ],
        [ "BGNBA", "da/d26/structyaze_1_1emu_1_1BGNBA.html", "da/d26/structyaze_1_1emu_1_1BGNBA" ],
        [ "BGSC", "d2/d99/structyaze_1_1emu_1_1BGSC.html", "d2/d99/structyaze_1_1emu_1_1BGSC" ],
        [ "BGVOFS", "d0/dd5/structyaze_1_1emu_1_1BGVOFS.html", "d0/dd5/structyaze_1_1emu_1_1BGVOFS" ],
        [ "BreakpointManager", "d9/ded/classyaze_1_1emu_1_1BreakpointManager.html", "d9/ded/classyaze_1_1emu_1_1BreakpointManager" ],
        [ "CGADD", "d0/d4e/structyaze_1_1emu_1_1CGADD.html", "d0/d4e/structyaze_1_1emu_1_1CGADD" ],
        [ "CGADSUB", "d2/d1a/structyaze_1_1emu_1_1CGADSUB.html", "d2/d1a/structyaze_1_1emu_1_1CGADSUB" ],
        [ "CGDATA", "de/da2/structyaze_1_1emu_1_1CGDATA.html", "de/da2/structyaze_1_1emu_1_1CGDATA" ],
        [ "CGDATAREAD", "da/d49/structyaze_1_1emu_1_1CGDATAREAD.html", "da/d49/structyaze_1_1emu_1_1CGDATAREAD" ],
        [ "CGWSEL", "d4/dda/structyaze_1_1emu_1_1CGWSEL.html", "d4/dda/structyaze_1_1emu_1_1CGWSEL" ],
        [ "CharacterLocation", "d7/d8d/structyaze_1_1emu_1_1CharacterLocation.html", "d7/d8d/structyaze_1_1emu_1_1CharacterLocation" ],
        [ "COLDATA", "d9/dd1/structyaze_1_1emu_1_1COLDATA.html", "d9/dd1/structyaze_1_1emu_1_1COLDATA" ],
        [ "Color", "d8/d72/structyaze_1_1emu_1_1Color.html", "d8/d72/structyaze_1_1emu_1_1Color" ],
        [ "CounterIrqNmiRegisters", "d2/d03/structyaze_1_1emu_1_1CounterIrqNmiRegisters.html", "d2/d03/structyaze_1_1emu_1_1CounterIrqNmiRegisters" ],
        [ "Cpu", "dc/df4/classyaze_1_1emu_1_1Cpu.html", "dc/df4/classyaze_1_1emu_1_1Cpu" ],
        [ "CpuCallbacks", "d0/d63/structyaze_1_1emu_1_1CpuCallbacks.html", "d0/d63/structyaze_1_1emu_1_1CpuCallbacks" ],
        [ "DmaChannel", "d0/d16/structyaze_1_1emu_1_1DmaChannel.html", "d0/d16/structyaze_1_1emu_1_1DmaChannel" ],
        [ "DmaRegisters", "d9/d21/structyaze_1_1emu_1_1DmaRegisters.html", "d9/d21/structyaze_1_1emu_1_1DmaRegisters" ],
        [ "Dsp", "dc/d01/classyaze_1_1emu_1_1Dsp.html", "dc/d01/classyaze_1_1emu_1_1Dsp" ],
        [ "DspChannel", "d5/da0/structyaze_1_1emu_1_1DspChannel.html", "d5/da0/structyaze_1_1emu_1_1DspChannel" ],
        [ "Emulator", "d0/dbd/classyaze_1_1emu_1_1Emulator.html", "d0/dbd/classyaze_1_1emu_1_1Emulator" ],
        [ "INIDISP", "d8/d31/structyaze_1_1emu_1_1INIDISP.html", "d8/d31/structyaze_1_1emu_1_1INIDISP" ],
        [ "Input", "d8/db7/structyaze_1_1emu_1_1Input.html", "d8/db7/structyaze_1_1emu_1_1Input" ],
        [ "InstructionEntry", "d2/def/classyaze_1_1emu_1_1InstructionEntry.html", "d2/def/classyaze_1_1emu_1_1InstructionEntry" ],
        [ "JoypadRegisters", "d3/d00/structyaze_1_1emu_1_1JoypadRegisters.html", "d3/d00/structyaze_1_1emu_1_1JoypadRegisters" ],
        [ "Layer", "d9/de3/structyaze_1_1emu_1_1Layer.html", "d9/de3/structyaze_1_1emu_1_1Layer" ],
        [ "M7A", "d9/d5a/structyaze_1_1emu_1_1M7A.html", "d9/d5a/structyaze_1_1emu_1_1M7A" ],
        [ "M7B", "db/d53/structyaze_1_1emu_1_1M7B.html", "db/d53/structyaze_1_1emu_1_1M7B" ],
        [ "M7C", "d5/d84/structyaze_1_1emu_1_1M7C.html", "d5/d84/structyaze_1_1emu_1_1M7C" ],
        [ "M7D", "d3/d77/structyaze_1_1emu_1_1M7D.html", "d3/d77/structyaze_1_1emu_1_1M7D" ],
        [ "M7SEL", "dd/d33/structyaze_1_1emu_1_1M7SEL.html", "dd/d33/structyaze_1_1emu_1_1M7SEL" ],
        [ "M7X", "d1/d12/structyaze_1_1emu_1_1M7X.html", "d1/d12/structyaze_1_1emu_1_1M7X" ],
        [ "M7Y", "db/dd1/structyaze_1_1emu_1_1M7Y.html", "db/dd1/structyaze_1_1emu_1_1M7Y" ],
        [ "MainSubScreenDesignation", "d6/df6/structyaze_1_1emu_1_1MainSubScreenDesignation.html", "d6/df6/structyaze_1_1emu_1_1MainSubScreenDesignation" ],
        [ "MaskLogicSettings", "d9/d57/structyaze_1_1emu_1_1MaskLogicSettings.html", "d9/d57/structyaze_1_1emu_1_1MaskLogicSettings" ],
        [ "Memory", "d2/d5e/classyaze_1_1emu_1_1Memory.html", "d2/d5e/classyaze_1_1emu_1_1Memory" ],
        [ "MemoryImpl", "de/d0f/classyaze_1_1emu_1_1MemoryImpl.html", "de/d0f/classyaze_1_1emu_1_1MemoryImpl" ],
        [ "MnemonicMode", "d6/da6/structyaze_1_1emu_1_1MnemonicMode.html", "d6/da6/structyaze_1_1emu_1_1MnemonicMode" ],
        [ "MnemonicModeHash", "db/db3/structyaze_1_1emu_1_1MnemonicModeHash.html", "db/db3/structyaze_1_1emu_1_1MnemonicModeHash" ],
        [ "MockMemory", "db/da4/classyaze_1_1emu_1_1MockMemory.html", "db/da4/classyaze_1_1emu_1_1MockMemory" ],
        [ "Mosaic", "d0/d48/structyaze_1_1emu_1_1Mosaic.html", "d0/d48/structyaze_1_1emu_1_1Mosaic" ],
        [ "MPYH", "d6/d63/structyaze_1_1emu_1_1MPYH.html", "d6/d63/structyaze_1_1emu_1_1MPYH" ],
        [ "MPYL", "d4/dae/structyaze_1_1emu_1_1MPYL.html", "d4/dae/structyaze_1_1emu_1_1MPYL" ],
        [ "MPYM", "d0/d95/structyaze_1_1emu_1_1MPYM.html", "d0/d95/structyaze_1_1emu_1_1MPYM" ],
        [ "OAMADDH", "d1/d33/structyaze_1_1emu_1_1OAMADDH.html", "d1/d33/structyaze_1_1emu_1_1OAMADDH" ],
        [ "OAMADDL", "d6/df2/structyaze_1_1emu_1_1OAMADDL.html", "d6/df2/structyaze_1_1emu_1_1OAMADDL" ],
        [ "OAMAddress", "d6/df1/structyaze_1_1emu_1_1OAMAddress.html", "d6/df1/structyaze_1_1emu_1_1OAMAddress" ],
        [ "OAMDATA", "d3/dab/structyaze_1_1emu_1_1OAMDATA.html", "d3/dab/structyaze_1_1emu_1_1OAMDATA" ],
        [ "OAMDATAREAD", "d9/d6e/structyaze_1_1emu_1_1OAMDATAREAD.html", "d9/d6e/structyaze_1_1emu_1_1OAMDATAREAD" ],
        [ "OAMSize", "dd/dec/structyaze_1_1emu_1_1OAMSize.html", "dd/dec/structyaze_1_1emu_1_1OAMSize" ],
        [ "OBJSEL", "d7/df6/structyaze_1_1emu_1_1OBJSEL.html", "d7/df6/structyaze_1_1emu_1_1OBJSEL" ],
        [ "OPHCT", "d2/d4f/structyaze_1_1emu_1_1OPHCT.html", "d2/d4f/structyaze_1_1emu_1_1OPHCT" ],
        [ "OPVCT", "d6/d84/structyaze_1_1emu_1_1OPVCT.html", "d6/d84/structyaze_1_1emu_1_1OPVCT" ],
        [ "Ppu", "d3/ded/classyaze_1_1emu_1_1Ppu.html", "d3/ded/classyaze_1_1emu_1_1Ppu" ],
        [ "PpuInterface", "d4/d7c/classyaze_1_1emu_1_1PpuInterface.html", "d4/d7c/classyaze_1_1emu_1_1PpuInterface" ],
        [ "ScreenDisplay", "dc/d5d/structyaze_1_1emu_1_1ScreenDisplay.html", "dc/d5d/structyaze_1_1emu_1_1ScreenDisplay" ],
        [ "ScreenMode", "d3/d33/structyaze_1_1emu_1_1ScreenMode.html", "d3/d33/structyaze_1_1emu_1_1ScreenMode" ],
        [ "ScrollRegister", "d2/d09/structyaze_1_1emu_1_1ScrollRegister.html", "d2/d09/structyaze_1_1emu_1_1ScrollRegister" ],
        [ "SETINI", "da/dd7/structyaze_1_1emu_1_1SETINI.html", "da/dd7/structyaze_1_1emu_1_1SETINI" ],
        [ "SLHV", "de/d3d/structyaze_1_1emu_1_1SLHV.html", "de/d3d/structyaze_1_1emu_1_1SLHV" ],
        [ "Snes", "d3/d15/classyaze_1_1emu_1_1Snes.html", "d3/d15/classyaze_1_1emu_1_1Snes" ],
        [ "Spc700", "d2/d07/classyaze_1_1emu_1_1Spc700.html", "d2/d07/classyaze_1_1emu_1_1Spc700" ],
        [ "SpriteAttributes", "de/d3e/structyaze_1_1emu_1_1SpriteAttributes.html", "de/d3e/structyaze_1_1emu_1_1SpriteAttributes" ],
        [ "STAT77", "d6/d9f/structyaze_1_1emu_1_1STAT77.html", "d6/d9f/structyaze_1_1emu_1_1STAT77" ],
        [ "STAT78", "d1/d5e/structyaze_1_1emu_1_1STAT78.html", "d1/d5e/structyaze_1_1emu_1_1STAT78" ],
        [ "Tile", "d1/d60/structyaze_1_1emu_1_1Tile.html", "d1/d60/structyaze_1_1emu_1_1Tile" ],
        [ "Tilemap", "de/d07/structyaze_1_1emu_1_1Tilemap.html", "de/d07/structyaze_1_1emu_1_1Tilemap" ],
        [ "TilemapEntry", "d1/d04/structyaze_1_1emu_1_1TilemapEntry.html", "d1/d04/structyaze_1_1emu_1_1TilemapEntry" ],
        [ "TileMapLocation", "dd/da8/structyaze_1_1emu_1_1TileMapLocation.html", "dd/da8/structyaze_1_1emu_1_1TileMapLocation" ],
        [ "Timer", "d0/d1e/structyaze_1_1emu_1_1Timer.html", "d0/d1e/structyaze_1_1emu_1_1Timer" ],
        [ "TM", "d5/db4/structyaze_1_1emu_1_1TM.html", "d5/db4/structyaze_1_1emu_1_1TM" ],
        [ "TMW", "d5/dd1/structyaze_1_1emu_1_1TMW.html", "d5/dd1/structyaze_1_1emu_1_1TMW" ],
        [ "TS", "da/db1/structyaze_1_1emu_1_1TS.html", "da/db1/structyaze_1_1emu_1_1TS" ],
        [ "TSW", "d2/de5/structyaze_1_1emu_1_1TSW.html", "d2/de5/structyaze_1_1emu_1_1TSW" ],
        [ "VideoPortControl", "da/dbf/structyaze_1_1emu_1_1VideoPortControl.html", "da/dbf/structyaze_1_1emu_1_1VideoPortControl" ],
        [ "VMADDH", "dc/da6/structyaze_1_1emu_1_1VMADDH.html", "dc/da6/structyaze_1_1emu_1_1VMADDH" ],
        [ "VMADDL", "db/da1/structyaze_1_1emu_1_1VMADDL.html", "db/da1/structyaze_1_1emu_1_1VMADDL" ],
        [ "VMAIN", "d5/dcb/structyaze_1_1emu_1_1VMAIN.html", "d5/dcb/structyaze_1_1emu_1_1VMAIN" ],
        [ "VMDATA", "d5/d94/structyaze_1_1emu_1_1VMDATA.html", "d5/d94/structyaze_1_1emu_1_1VMDATA" ],
        [ "VMDATAHREAD", "d3/d3e/structyaze_1_1emu_1_1VMDATAHREAD.html", "d3/d3e/structyaze_1_1emu_1_1VMDATAHREAD" ],
        [ "VMDATALREAD", "db/d62/structyaze_1_1emu_1_1VMDATALREAD.html", "db/d62/structyaze_1_1emu_1_1VMDATALREAD" ],
        [ "W12SEL", "d0/d7a/structyaze_1_1emu_1_1W12SEL.html", "d0/d7a/structyaze_1_1emu_1_1W12SEL" ],
        [ "W34SEL", "d4/dd2/structyaze_1_1emu_1_1W34SEL.html", "d4/dd2/structyaze_1_1emu_1_1W34SEL" ],
        [ "WatchpointManager", "d7/d17/classyaze_1_1emu_1_1WatchpointManager.html", "d7/d17/classyaze_1_1emu_1_1WatchpointManager" ],
        [ "WBGLOG", "d4/d87/structyaze_1_1emu_1_1WBGLOG.html", "d4/d87/structyaze_1_1emu_1_1WBGLOG" ],
        [ "WH0", "de/ded/structyaze_1_1emu_1_1WH0.html", "de/ded/structyaze_1_1emu_1_1WH0" ],
        [ "WH1", "dc/d07/structyaze_1_1emu_1_1WH1.html", "dc/d07/structyaze_1_1emu_1_1WH1" ],
        [ "WH2", "d5/d5b/structyaze_1_1emu_1_1WH2.html", "d5/d5b/structyaze_1_1emu_1_1WH2" ],
        [ "WH3", "dd/dac/structyaze_1_1emu_1_1WH3.html", "dd/dac/structyaze_1_1emu_1_1WH3" ],
        [ "WindowLayer", "d2/def/structyaze_1_1emu_1_1WindowLayer.html", "d2/def/structyaze_1_1emu_1_1WindowLayer" ],
        [ "WindowMaskSettings", "dc/d4c/structyaze_1_1emu_1_1WindowMaskSettings.html", "dc/d4c/structyaze_1_1emu_1_1WindowMaskSettings" ],
        [ "WindowMaskSettings2", "d7/ddf/structyaze_1_1emu_1_1WindowMaskSettings2.html", "d7/ddf/structyaze_1_1emu_1_1WindowMaskSettings2" ],
        [ "WindowPosition", "df/d39/structyaze_1_1emu_1_1WindowPosition.html", "df/d39/structyaze_1_1emu_1_1WindowPosition" ],
        [ "WOBJLOG", "d4/dd5/structyaze_1_1emu_1_1WOBJLOG.html", "d4/dd5/structyaze_1_1emu_1_1WOBJLOG" ],
        [ "WOBJSEL", "d6/d04/structyaze_1_1emu_1_1WOBJSEL.html", "d6/d04/structyaze_1_1emu_1_1WOBJSEL" ],
        [ "WramAccessRegisters", "d3/d92/structyaze_1_1emu_1_1WramAccessRegisters.html", "d3/d92/structyaze_1_1emu_1_1WramAccessRegisters" ]
      ] ],
      [ "gfx", "d0/d27/namespaceyaze_1_1gfx.html", [
        [ "lc_lz2", "d1/d4b/namespaceyaze_1_1gfx_1_1lc__lz2.html", [
          [ "CompressionCommand", "d6/db2/structyaze_1_1gfx_1_1lc__lz2_1_1CompressionCommand.html", "d6/db2/structyaze_1_1gfx_1_1lc__lz2_1_1CompressionCommand" ],
          [ "CompressionContext", "d3/da7/structyaze_1_1gfx_1_1lc__lz2_1_1CompressionContext.html", "d3/da7/structyaze_1_1gfx_1_1lc__lz2_1_1CompressionContext" ],
          [ "CompressionPiece", "d5/d61/structyaze_1_1gfx_1_1lc__lz2_1_1CompressionPiece.html", "d5/d61/structyaze_1_1gfx_1_1lc__lz2_1_1CompressionPiece" ]
        ] ],
        [ "Arena", "d4/de6/classyaze_1_1gfx_1_1Arena.html", "d4/de6/classyaze_1_1gfx_1_1Arena" ],
        [ "AtlasRenderer", "d8/d6e/classyaze_1_1gfx_1_1AtlasRenderer.html", "d8/d6e/classyaze_1_1gfx_1_1AtlasRenderer" ],
        [ "AtlasStats", "d2/dea/structyaze_1_1gfx_1_1AtlasStats.html", "d2/dea/structyaze_1_1gfx_1_1AtlasStats" ],
        [ "BackgroundBuffer", "dd/dac/classyaze_1_1gfx_1_1BackgroundBuffer.html", "dd/dac/classyaze_1_1gfx_1_1BackgroundBuffer" ],
        [ "Bitmap", "df/d0e/classyaze_1_1gfx_1_1Bitmap.html", "df/d0e/classyaze_1_1gfx_1_1Bitmap" ],
        [ "BitmapError", "df/d71/classyaze_1_1gfx_1_1BitmapError.html", null ],
        [ "BppConversionScope", "d8/d44/classyaze_1_1gfx_1_1BppConversionScope.html", "d8/d44/classyaze_1_1gfx_1_1BppConversionScope" ],
        [ "BppFormatInfo", "da/dec/structyaze_1_1gfx_1_1BppFormatInfo.html", "da/dec/structyaze_1_1gfx_1_1BppFormatInfo" ],
        [ "BppFormatManager", "d0/d5c/classyaze_1_1gfx_1_1BppFormatManager.html", "d0/d5c/classyaze_1_1gfx_1_1BppFormatManager" ],
        [ "CgxHeader", "d3/d93/structyaze_1_1gfx_1_1CgxHeader.html", "d3/d93/structyaze_1_1gfx_1_1CgxHeader" ],
        [ "GfxContext", "d5/d28/classyaze_1_1gfx_1_1GfxContext.html", null ],
        [ "GraphicsBuffer", "d5/d3c/classyaze_1_1gfx_1_1GraphicsBuffer.html", "d5/d3c/classyaze_1_1gfx_1_1GraphicsBuffer" ],
        [ "GraphicsOptimizationBenchmarks", "de/d35/classyaze_1_1gfx_1_1GraphicsOptimizationBenchmarks.html", "de/d35/classyaze_1_1gfx_1_1GraphicsOptimizationBenchmarks" ],
        [ "GraphicsOptimizationScope", "d6/dcc/classyaze_1_1gfx_1_1GraphicsOptimizationScope.html", "d6/dcc/classyaze_1_1gfx_1_1GraphicsOptimizationScope" ],
        [ "GraphicsOptimizer", "d3/d19/classyaze_1_1gfx_1_1GraphicsOptimizer.html", "d3/d19/classyaze_1_1gfx_1_1GraphicsOptimizer" ],
        [ "GraphicsSheetAnalysis", "d3/df6/structyaze_1_1gfx_1_1GraphicsSheetAnalysis.html", "d3/df6/structyaze_1_1gfx_1_1GraphicsSheetAnalysis" ],
        [ "IRenderer", "d0/dca/classyaze_1_1gfx_1_1IRenderer.html", "d0/dca/classyaze_1_1gfx_1_1IRenderer" ],
        [ "MemoryPool", "dc/d55/classyaze_1_1gfx_1_1MemoryPool.html", "dc/d55/classyaze_1_1gfx_1_1MemoryPool" ],
        [ "OamTile", "df/da2/classyaze_1_1gfx_1_1OamTile.html", "df/da2/classyaze_1_1gfx_1_1OamTile" ],
        [ "OptimizationResult", "d6/d5e/structyaze_1_1gfx_1_1OptimizationResult.html", "d6/d5e/structyaze_1_1gfx_1_1OptimizationResult" ],
        [ "Pair", "de/ddb/structyaze_1_1gfx_1_1Pair.html", "de/ddb/structyaze_1_1gfx_1_1Pair" ],
        [ "PaletteGroup", "d1/dec/structyaze_1_1gfx_1_1PaletteGroup.html", "d1/dec/structyaze_1_1gfx_1_1PaletteGroup" ],
        [ "PaletteGroupMap", "d7/dcc/structyaze_1_1gfx_1_1PaletteGroupMap.html", "d7/dcc/structyaze_1_1gfx_1_1PaletteGroupMap" ],
        [ "Paletteset", "d9/dee/structyaze_1_1gfx_1_1Paletteset.html", "d9/dee/structyaze_1_1gfx_1_1Paletteset" ],
        [ "PerformanceDashboard", "d4/d6f/classyaze_1_1gfx_1_1PerformanceDashboard.html", "d4/d6f/classyaze_1_1gfx_1_1PerformanceDashboard" ],
        [ "PerformanceProfiler", "d4/d0a/classyaze_1_1gfx_1_1PerformanceProfiler.html", "d4/d0a/classyaze_1_1gfx_1_1PerformanceProfiler" ],
        [ "PerformanceSummary", "d1/de2/structyaze_1_1gfx_1_1PerformanceSummary.html", "d1/de2/structyaze_1_1gfx_1_1PerformanceSummary" ],
        [ "PoolAllocator", "d5/d46/classyaze_1_1gfx_1_1PoolAllocator.html", "d5/d46/classyaze_1_1gfx_1_1PoolAllocator" ],
        [ "RenderCommand", "d8/de1/structyaze_1_1gfx_1_1RenderCommand.html", "d8/de1/structyaze_1_1gfx_1_1RenderCommand" ],
        [ "ScopedTimer", "d7/ddb/classyaze_1_1gfx_1_1ScopedTimer.html", "d7/ddb/classyaze_1_1gfx_1_1ScopedTimer" ],
        [ "SDL2Renderer", "d9/dfe/classyaze_1_1gfx_1_1SDL2Renderer.html", "d9/dfe/classyaze_1_1gfx_1_1SDL2Renderer" ],
        [ "SheetOptimizationData", "d8/d7c/structyaze_1_1gfx_1_1SheetOptimizationData.html", "d8/d7c/structyaze_1_1gfx_1_1SheetOptimizationData" ],
        [ "SnesColor", "d5/d31/classyaze_1_1gfx_1_1SnesColor.html", "d5/d31/classyaze_1_1gfx_1_1SnesColor" ],
        [ "SnesPalette", "da/d68/classyaze_1_1gfx_1_1SnesPalette.html", "da/d68/classyaze_1_1gfx_1_1SnesPalette" ],
        [ "TextureAtlas", "de/d9a/classyaze_1_1gfx_1_1TextureAtlas.html", "de/d9a/classyaze_1_1gfx_1_1TextureAtlas" ],
        [ "Tile16", "d1/dae/classyaze_1_1gfx_1_1Tile16.html", "d1/dae/classyaze_1_1gfx_1_1Tile16" ],
        [ "Tile32", "d7/d83/classyaze_1_1gfx_1_1Tile32.html", "d7/d83/classyaze_1_1gfx_1_1Tile32" ],
        [ "TileCache", "d6/db0/structyaze_1_1gfx_1_1TileCache.html", "d6/db0/structyaze_1_1gfx_1_1TileCache" ],
        [ "TileInfo", "d3/de4/classyaze_1_1gfx_1_1TileInfo.html", "d3/de4/classyaze_1_1gfx_1_1TileInfo" ],
        [ "Tilemap", "db/d0a/structyaze_1_1gfx_1_1Tilemap.html", "db/d0a/structyaze_1_1gfx_1_1Tilemap" ]
      ] ],
      [ "gui", "d3/dbf/namespaceyaze_1_1gui.html", [
        [ "canvas", "db/dc3/namespaceyaze_1_1gui_1_1canvas.html", [
          [ "BppConversionOptions", "d4/d68/structyaze_1_1gui_1_1canvas_1_1BppConversionOptions.html", "d4/d68/structyaze_1_1gui_1_1canvas_1_1BppConversionOptions" ],
          [ "CanvasConfig", "d3/d8f/structyaze_1_1gui_1_1canvas_1_1CanvasConfig.html", "d3/d8f/structyaze_1_1gui_1_1canvas_1_1CanvasConfig" ],
          [ "CanvasContextMenu", "dd/ddf/classyaze_1_1gui_1_1canvas_1_1CanvasContextMenu.html", "dd/ddf/classyaze_1_1gui_1_1canvas_1_1CanvasContextMenu" ],
          [ "CanvasInteractionHandler", "dd/d71/classyaze_1_1gui_1_1canvas_1_1CanvasInteractionHandler.html", "dd/d71/classyaze_1_1gui_1_1canvas_1_1CanvasInteractionHandler" ],
          [ "CanvasModals", "d5/dd8/classyaze_1_1gui_1_1canvas_1_1CanvasModals.html", "d5/dd8/classyaze_1_1gui_1_1canvas_1_1CanvasModals" ],
          [ "CanvasPerformanceIntegration", "d6/dcb/classyaze_1_1gui_1_1canvas_1_1CanvasPerformanceIntegration.html", "d6/dcb/classyaze_1_1gui_1_1canvas_1_1CanvasPerformanceIntegration" ],
          [ "CanvasPerformanceManager", "df/db7/classyaze_1_1gui_1_1canvas_1_1CanvasPerformanceManager.html", "df/db7/classyaze_1_1gui_1_1canvas_1_1CanvasPerformanceManager" ],
          [ "CanvasPerformanceMetrics", "d3/d30/structyaze_1_1gui_1_1canvas_1_1CanvasPerformanceMetrics.html", "d3/d30/structyaze_1_1gui_1_1canvas_1_1CanvasPerformanceMetrics" ],
          [ "CanvasUsageManager", "d4/da1/classyaze_1_1gui_1_1canvas_1_1CanvasUsageManager.html", "d4/da1/classyaze_1_1gui_1_1canvas_1_1CanvasUsageManager" ],
          [ "CanvasUsageStats", "d8/da5/structyaze_1_1gui_1_1canvas_1_1CanvasUsageStats.html", "d8/da5/structyaze_1_1gui_1_1canvas_1_1CanvasUsageStats" ],
          [ "CanvasUsageTracker", "d7/d4d/classyaze_1_1gui_1_1canvas_1_1CanvasUsageTracker.html", "d7/d4d/classyaze_1_1gui_1_1canvas_1_1CanvasUsageTracker" ],
          [ "ColorAnalysisOptions", "d8/de6/structyaze_1_1gui_1_1canvas_1_1ColorAnalysisOptions.html", "d8/de6/structyaze_1_1gui_1_1canvas_1_1ColorAnalysisOptions" ],
          [ "PaletteEditorOptions", "df/de1/structyaze_1_1gui_1_1canvas_1_1PaletteEditorOptions.html", "df/de1/structyaze_1_1gui_1_1canvas_1_1PaletteEditorOptions" ],
          [ "PerformanceOptions", "d0/d59/structyaze_1_1gui_1_1canvas_1_1PerformanceOptions.html", "d0/d59/structyaze_1_1gui_1_1canvas_1_1PerformanceOptions" ],
          [ "TileInteractionResult", "d4/d9c/structyaze_1_1gui_1_1canvas_1_1TileInteractionResult.html", "d4/d9c/structyaze_1_1gui_1_1canvas_1_1TileInteractionResult" ]
        ] ],
        [ "CanvasUtils", "d5/d08/namespaceyaze_1_1gui_1_1CanvasUtils.html", [
          [ "CanvasRenderContext", "d5/d10/structyaze_1_1gui_1_1CanvasUtils_1_1CanvasRenderContext.html", "d5/d10/structyaze_1_1gui_1_1CanvasUtils_1_1CanvasRenderContext" ]
        ] ],
        [ "AgentChatWidget", "dc/d1f/classyaze_1_1gui_1_1AgentChatWidget.html", "dc/d1f/classyaze_1_1gui_1_1AgentChatWidget" ],
        [ "AssetObject", "d5/d23/structyaze_1_1gui_1_1AssetObject.html", "d5/d23/structyaze_1_1gui_1_1AssetObject" ],
        [ "AutoWidgetScope", "db/d2c/classyaze_1_1gui_1_1AutoWidgetScope.html", "db/d2c/classyaze_1_1gui_1_1AutoWidgetScope" ],
        [ "BackgroundRenderer", "d5/dc2/classyaze_1_1gui_1_1BackgroundRenderer.html", "d5/dc2/classyaze_1_1gui_1_1BackgroundRenderer" ],
        [ "BppComparisonTool", "d3/d1a/classyaze_1_1gui_1_1BppComparisonTool.html", "d3/d1a/classyaze_1_1gui_1_1BppComparisonTool" ],
        [ "BppConversionDialog", "db/d56/classyaze_1_1gui_1_1BppConversionDialog.html", "db/d56/classyaze_1_1gui_1_1BppConversionDialog" ],
        [ "BppFormatUI", "d2/dc2/classyaze_1_1gui_1_1BppFormatUI.html", "d2/dc2/classyaze_1_1gui_1_1BppFormatUI" ],
        [ "Canvas", "da/d2c/classyaze_1_1gui_1_1Canvas.html", "da/d2c/classyaze_1_1gui_1_1Canvas" ],
        [ "CanvasAutomationAPI", "dd/de4/classyaze_1_1gui_1_1CanvasAutomationAPI.html", "dd/de4/classyaze_1_1gui_1_1CanvasAutomationAPI" ],
        [ "CanvasConfig", "da/d7f/structyaze_1_1gui_1_1CanvasConfig.html", "da/d7f/structyaze_1_1gui_1_1CanvasConfig" ],
        [ "CanvasContextMenuItem", "d2/d60/structyaze_1_1gui_1_1CanvasContextMenuItem.html", "d2/d60/structyaze_1_1gui_1_1CanvasContextMenuItem" ],
        [ "CanvasPaletteManager", "da/d4e/structyaze_1_1gui_1_1CanvasPaletteManager.html", "da/d4e/structyaze_1_1gui_1_1CanvasPaletteManager" ],
        [ "CanvasSelection", "d7/d02/structyaze_1_1gui_1_1CanvasSelection.html", "d7/d02/structyaze_1_1gui_1_1CanvasSelection" ],
        [ "CardInfo", "de/d2b/structyaze_1_1gui_1_1CardInfo.html", "de/d2b/structyaze_1_1gui_1_1CardInfo" ],
        [ "CardRegistration", "dd/d36/classyaze_1_1gui_1_1CardRegistration.html", "dd/d36/classyaze_1_1gui_1_1CardRegistration" ],
        [ "CollaborationPanel", "d3/dad/classyaze_1_1gui_1_1CollaborationPanel.html", "d3/dad/classyaze_1_1gui_1_1CollaborationPanel" ],
        [ "Color", "d4/dca/structyaze_1_1gui_1_1Color.html", "d4/dca/structyaze_1_1gui_1_1Color" ],
        [ "DockSpaceRenderer", "d9/d95/classyaze_1_1gui_1_1DockSpaceRenderer.html", null ],
        [ "DungeonAsset", "d6/d87/structyaze_1_1gui_1_1DungeonAsset.html", "d6/d87/structyaze_1_1gui_1_1DungeonAsset" ],
        [ "DungeonObjectEmulatorPreview", "d9/d71/classyaze_1_1gui_1_1DungeonObjectEmulatorPreview.html", "d9/d71/classyaze_1_1gui_1_1DungeonObjectEmulatorPreview" ],
        [ "EditorCard", "d4/d96/classyaze_1_1gui_1_1EditorCard.html", "d4/d96/classyaze_1_1gui_1_1EditorCard" ],
        [ "EditorCardManager", "d1/dea/classyaze_1_1gui_1_1EditorCardManager.html", "d1/dea/classyaze_1_1gui_1_1EditorCardManager" ],
        [ "EditorLayout", "d8/db6/classyaze_1_1gui_1_1EditorLayout.html", "d8/db6/classyaze_1_1gui_1_1EditorLayout" ],
        [ "EnhancedTheme", "d2/dfe/structyaze_1_1gui_1_1EnhancedTheme.html", "d2/dfe/structyaze_1_1gui_1_1EnhancedTheme" ],
        [ "ExampleSelectionWithDeletion", "d4/d4b/structyaze_1_1gui_1_1ExampleSelectionWithDeletion.html", "d4/d4b/structyaze_1_1gui_1_1ExampleSelectionWithDeletion" ],
        [ "FlagsMenu", "d0/df3/structyaze_1_1gui_1_1FlagsMenu.html", "d0/df3/structyaze_1_1gui_1_1FlagsMenu" ],
        [ "GfxSheetAssetBrowser", "dd/d44/structyaze_1_1gui_1_1GfxSheetAssetBrowser.html", "dd/d44/structyaze_1_1gui_1_1GfxSheetAssetBrowser" ],
        [ "MultiSelect", "d2/d39/classyaze_1_1gui_1_1MultiSelect.html", "d2/d39/classyaze_1_1gui_1_1MultiSelect" ],
        [ "OverworldAsset", "d7/d14/structyaze_1_1gui_1_1OverworldAsset.html", "d7/d14/structyaze_1_1gui_1_1OverworldAsset" ],
        [ "PaletteEditorWidget", "d9/df4/classyaze_1_1gui_1_1PaletteEditorWidget.html", "d9/df4/classyaze_1_1gui_1_1PaletteEditorWidget" ],
        [ "PaletteWidget", "d9/d7f/classyaze_1_1gui_1_1PaletteWidget.html", "d9/d7f/classyaze_1_1gui_1_1PaletteWidget" ],
        [ "ProposalEntry", "d9/d76/structyaze_1_1gui_1_1ProposalEntry.html", "d9/d76/structyaze_1_1gui_1_1ProposalEntry" ],
        [ "RomSyncEntry", "d0/d46/structyaze_1_1gui_1_1RomSyncEntry.html", "d0/d46/structyaze_1_1gui_1_1RomSyncEntry" ],
        [ "ScopedCanvas", "da/dbd/classyaze_1_1gui_1_1ScopedCanvas.html", "da/dbd/classyaze_1_1gui_1_1ScopedCanvas" ],
        [ "SnapshotEntry", "d5/d1c/structyaze_1_1gui_1_1SnapshotEntry.html", "d5/d1c/structyaze_1_1gui_1_1SnapshotEntry" ],
        [ "SpriteAsset", "d5/d30/structyaze_1_1gui_1_1SpriteAsset.html", "d5/d30/structyaze_1_1gui_1_1SpriteAsset" ],
        [ "Table", "d8/d52/structyaze_1_1gui_1_1Table.html", "d8/d52/structyaze_1_1gui_1_1Table" ],
        [ "TextBox", "d5/d66/structyaze_1_1gui_1_1TextBox.html", "d5/d66/structyaze_1_1gui_1_1TextBox" ],
        [ "ThemeManager", "d3/d27/classyaze_1_1gui_1_1ThemeManager.html", "d3/d27/classyaze_1_1gui_1_1ThemeManager" ],
        [ "TileSelectorWidget", "d7/dd7/classyaze_1_1gui_1_1TileSelectorWidget.html", "d7/dd7/classyaze_1_1gui_1_1TileSelectorWidget" ],
        [ "Toolset", "d7/dcb/classyaze_1_1gui_1_1Toolset.html", "d7/dcb/classyaze_1_1gui_1_1Toolset" ],
        [ "UnsortedAsset", "d5/dc4/structyaze_1_1gui_1_1UnsortedAsset.html", "d5/dc4/structyaze_1_1gui_1_1UnsortedAsset" ],
        [ "WidgetIdRegistry", "d9/dfe/classyaze_1_1gui_1_1WidgetIdRegistry.html", "d9/dfe/classyaze_1_1gui_1_1WidgetIdRegistry" ],
        [ "WidgetIdScope", "d8/dd5/classyaze_1_1gui_1_1WidgetIdScope.html", "d8/dd5/classyaze_1_1gui_1_1WidgetIdScope" ],
        [ "WidgetMeasurement", "d4/d03/classyaze_1_1gui_1_1WidgetMeasurement.html", "d4/d03/classyaze_1_1gui_1_1WidgetMeasurement" ],
        [ "WidgetMetrics", "d6/d47/structyaze_1_1gui_1_1WidgetMetrics.html", "d6/d47/structyaze_1_1gui_1_1WidgetMetrics" ]
      ] ],
      [ "net", "dd/d43/namespaceyaze_1_1net.html", [
        [ "CollaborationService", "d6/dfb/classyaze_1_1net_1_1CollaborationService.html", "d6/dfb/classyaze_1_1net_1_1CollaborationService" ],
        [ "ProposalApprovalManager", "d8/d96/classyaze_1_1net_1_1ProposalApprovalManager.html", "d8/d96/classyaze_1_1net_1_1ProposalApprovalManager" ],
        [ "RomSnapshot", "d2/df1/structyaze_1_1net_1_1RomSnapshot.html", "d2/df1/structyaze_1_1net_1_1RomSnapshot" ],
        [ "RomVersionManager", "d6/d28/classyaze_1_1net_1_1RomVersionManager.html", "d6/d28/classyaze_1_1net_1_1RomVersionManager" ],
        [ "SessionInfo", "de/d42/structyaze_1_1net_1_1SessionInfo.html", "de/d42/structyaze_1_1net_1_1SessionInfo" ],
        [ "VersionDiff", "d0/dd8/structyaze_1_1net_1_1VersionDiff.html", "d0/dd8/structyaze_1_1net_1_1VersionDiff" ],
        [ "WebSocketClient", "da/dae/classyaze_1_1net_1_1WebSocketClient.html", "da/dae/classyaze_1_1net_1_1WebSocketClient" ]
      ] ],
      [ "test", "d4/d0a/namespaceyaze_1_1test.html", [
        [ "anonymous_namespace{widget_discovery_service.cc}", "d3/d52/namespaceyaze_1_1test_1_1anonymous__namespace_02widget__discovery__service_8cc_03.html", [
          [ "WindowEntry", "d3/d85/structyaze_1_1test_1_1anonymous__namespace_02widget__discovery__service_8cc_03_1_1WindowEntry.html", "d3/d85/structyaze_1_1test_1_1anonymous__namespace_02widget__discovery__service_8cc_03_1_1WindowEntry" ]
        ] ],
        [ "integration", "d3/dec/namespaceyaze_1_1test_1_1integration.html", [
          [ "AsarIntegrationTest", "da/d22/classyaze_1_1test_1_1integration_1_1AsarIntegrationTest.html", "da/d22/classyaze_1_1test_1_1integration_1_1AsarIntegrationTest" ],
          [ "AsarRomIntegrationTest", "db/d76/classyaze_1_1test_1_1integration_1_1AsarRomIntegrationTest.html", "db/d76/classyaze_1_1test_1_1integration_1_1AsarRomIntegrationTest" ]
        ] ],
        [ "AITilePlacementTest", "d0/d89/classyaze_1_1test_1_1AITilePlacementTest.html", "d0/d89/classyaze_1_1test_1_1AITilePlacementTest" ],
        [ "ArenaTestSuite", "dc/de0/classyaze_1_1test_1_1ArenaTestSuite.html", "dc/de0/classyaze_1_1test_1_1ArenaTestSuite" ],
        [ "CanvasAutomationAPITest", "dc/d2a/classyaze_1_1test_1_1CanvasAutomationAPITest.html", "dc/d2a/classyaze_1_1test_1_1CanvasAutomationAPITest" ],
        [ "DungeonEditorIntegrationTest", "d7/dd7/classyaze_1_1test_1_1DungeonEditorIntegrationTest.html", "d7/dd7/classyaze_1_1test_1_1DungeonEditorIntegrationTest" ],
        [ "DungeonEditorV2IntegrationTest", "d3/d0a/classyaze_1_1test_1_1DungeonEditorV2IntegrationTest.html", "d3/d0a/classyaze_1_1test_1_1DungeonEditorV2IntegrationTest" ],
        [ "DungeonObjectRenderingE2ETests", "d0/dc7/classyaze_1_1test_1_1DungeonObjectRenderingE2ETests.html", "d0/dc7/classyaze_1_1test_1_1DungeonObjectRenderingE2ETests" ],
        [ "DungeonObjectRenderingTests", "dd/d40/classyaze_1_1test_1_1DungeonObjectRenderingTests.html", "dd/d40/classyaze_1_1test_1_1DungeonObjectRenderingTests" ],
        [ "DungeonRoomTest", "d6/d4f/classyaze_1_1test_1_1DungeonRoomTest.html", "d6/d4f/classyaze_1_1test_1_1DungeonRoomTest" ],
        [ "E2ERomDependentTest", "dd/dfa/classyaze_1_1test_1_1E2ERomDependentTest.html", "dd/dfa/classyaze_1_1test_1_1E2ERomDependentTest" ],
        [ "E2ETestSuite", "d0/d20/classyaze_1_1test_1_1E2ETestSuite.html", "d0/d20/classyaze_1_1test_1_1E2ETestSuite" ],
        [ "EditorIntegrationTest", "dd/d13/classyaze_1_1test_1_1EditorIntegrationTest.html", "dd/d13/classyaze_1_1test_1_1EditorIntegrationTest" ],
        [ "EmulatorTestSuite", "de/d0a/classyaze_1_1test_1_1EmulatorTestSuite.html", "de/d0a/classyaze_1_1test_1_1EmulatorTestSuite" ],
        [ "GeminiVisionTest", "d3/ddd/classyaze_1_1test_1_1GeminiVisionTest.html", "d3/ddd/classyaze_1_1test_1_1GeminiVisionTest" ],
        [ "IntegratedTestSuite", "d4/d70/classyaze_1_1test_1_1IntegratedTestSuite.html", "d4/d70/classyaze_1_1test_1_1IntegratedTestSuite" ],
        [ "MessageRomTest", "d2/df4/classyaze_1_1test_1_1MessageRomTest.html", "d2/df4/classyaze_1_1test_1_1MessageRomTest" ],
        [ "MockRom", "df/df5/classyaze_1_1test_1_1MockRom.html", "df/df5/classyaze_1_1test_1_1MockRom" ],
        [ "ObjectParserStructsTest", "db/d4a/classyaze_1_1test_1_1ObjectParserStructsTest.html", "db/d4a/classyaze_1_1test_1_1ObjectParserStructsTest" ],
        [ "ObjectParserTest", "d4/d80/classyaze_1_1test_1_1ObjectParserTest.html", "d4/d80/classyaze_1_1test_1_1ObjectParserTest" ],
        [ "OverworldE2ETest", "d0/ded/classyaze_1_1test_1_1OverworldE2ETest.html", "d0/ded/classyaze_1_1test_1_1OverworldE2ETest" ],
        [ "PerformanceTestSuite", "dd/de3/classyaze_1_1test_1_1PerformanceTestSuite.html", "dd/de3/classyaze_1_1test_1_1PerformanceTestSuite" ],
        [ "ResourceStats", "d3/db6/structyaze_1_1test_1_1ResourceStats.html", "d3/db6/structyaze_1_1test_1_1ResourceStats" ],
        [ "RomDependentTest", "d2/de4/classyaze_1_1test_1_1RomDependentTest.html", "d2/de4/classyaze_1_1test_1_1RomDependentTest" ],
        [ "RomDependentTestSuite", "d5/dd0/classyaze_1_1test_1_1RomDependentTestSuite.html", "d5/dd0/classyaze_1_1test_1_1RomDependentTestSuite" ],
        [ "RomTest", "d5/d1b/classyaze_1_1test_1_1RomTest.html", "d5/d1b/classyaze_1_1test_1_1RomTest" ],
        [ "SpriteBuilderTest", "d6/def/classyaze_1_1test_1_1SpriteBuilderTest.html", "d6/def/classyaze_1_1test_1_1SpriteBuilderTest" ],
        [ "TestConfig", "d6/d92/structyaze_1_1test_1_1TestConfig.html", "d6/d92/structyaze_1_1test_1_1TestConfig" ],
        [ "TestDungeonObjects", "d9/dd3/classyaze_1_1test_1_1TestDungeonObjects.html", "d9/dd3/classyaze_1_1test_1_1TestDungeonObjects" ],
        [ "TestEditor", "d0/ddd/classyaze_1_1test_1_1TestEditor.html", "d0/ddd/classyaze_1_1test_1_1TestEditor" ],
        [ "TestManager", "da/d3e/classyaze_1_1test_1_1TestManager.html", "da/d3e/classyaze_1_1test_1_1TestManager" ],
        [ "TestRecorder", "d2/def/classyaze_1_1test_1_1TestRecorder.html", "d2/def/classyaze_1_1test_1_1TestRecorder" ],
        [ "TestResult", "d9/d97/structyaze_1_1test_1_1TestResult.html", "d9/d97/structyaze_1_1test_1_1TestResult" ],
        [ "TestResults", "d2/d60/structyaze_1_1test_1_1TestResults.html", "d2/d60/structyaze_1_1test_1_1TestResults" ],
        [ "TestRomManager", "dd/d7e/classyaze_1_1test_1_1TestRomManager.html", "dd/d7e/classyaze_1_1test_1_1TestRomManager" ],
        [ "TestScript", "dc/d21/structyaze_1_1test_1_1TestScript.html", "dc/d21/structyaze_1_1test_1_1TestScript" ],
        [ "TestScriptParser", "d9/d12/classyaze_1_1test_1_1TestScriptParser.html", null ],
        [ "TestScriptStep", "d1/deb/structyaze_1_1test_1_1TestScriptStep.html", "d1/deb/structyaze_1_1test_1_1TestScriptStep" ],
        [ "TestSuite", "d1/de0/classyaze_1_1test_1_1TestSuite.html", "d1/de0/classyaze_1_1test_1_1TestSuite" ],
        [ "TileSelectorWidgetTest", "d3/d56/classyaze_1_1test_1_1TileSelectorWidgetTest.html", "d3/d56/classyaze_1_1test_1_1TileSelectorWidgetTest" ],
        [ "UITestSuite", "df/d1d/classyaze_1_1test_1_1UITestSuite.html", "df/d1d/classyaze_1_1test_1_1UITestSuite" ],
        [ "UnitTestSuite", "d0/d9d/classyaze_1_1test_1_1UnitTestSuite.html", "d0/d9d/classyaze_1_1test_1_1UnitTestSuite" ],
        [ "WidgetDiscoveryService", "dd/dc0/classyaze_1_1test_1_1WidgetDiscoveryService.html", "dd/dc0/classyaze_1_1test_1_1WidgetDiscoveryService" ],
        [ "ZSCustomOverworldTestSuite", "dc/dae/classyaze_1_1test_1_1ZSCustomOverworldTestSuite.html", "dc/dae/classyaze_1_1test_1_1ZSCustomOverworldTestSuite" ],
        [ "ZSCustomOverworldUpgradeTest", "d1/de2/classyaze_1_1test_1_1ZSCustomOverworldUpgradeTest.html", "d1/de2/classyaze_1_1test_1_1ZSCustomOverworldUpgradeTest" ]
      ] ],
      [ "util", "d4/de1/namespaceyaze_1_1util.html", [
        [ "FileDialogWrapper", "d2/d3f/classyaze_1_1util_1_1FileDialogWrapper.html", null ],
        [ "Flag", "d7/dc5/classyaze_1_1util_1_1Flag.html", "d7/dc5/classyaze_1_1util_1_1Flag" ],
        [ "FlagParser", "d1/d71/classyaze_1_1util_1_1FlagParser.html", "d1/d71/classyaze_1_1util_1_1FlagParser" ],
        [ "FlagRegistry", "d5/d1f/classyaze_1_1util_1_1FlagRegistry.html", "d5/d1f/classyaze_1_1util_1_1FlagRegistry" ],
        [ "HexStringParams", "da/df6/structyaze_1_1util_1_1HexStringParams.html", "da/df6/structyaze_1_1util_1_1HexStringParams" ],
        [ "IFlag", "d7/df7/classyaze_1_1util_1_1IFlag.html", "d7/df7/classyaze_1_1util_1_1IFlag" ],
        [ "LogManager", "d1/d42/classyaze_1_1util_1_1LogManager.html", "d1/d42/classyaze_1_1util_1_1LogManager" ],
        [ "NotifyValue", "de/d82/classyaze_1_1util_1_1NotifyValue.html", "de/d82/classyaze_1_1util_1_1NotifyValue" ],
        [ "PlatformPaths", "db/dd8/classyaze_1_1util_1_1PlatformPaths.html", null ],
        [ "SDL_Deleter", "db/d66/structyaze_1_1util_1_1SDL__Deleter.html", "db/d66/structyaze_1_1util_1_1SDL__Deleter" ],
        [ "SDL_Surface_Deleter", "df/d22/structyaze_1_1util_1_1SDL__Surface__Deleter.html", "df/d22/structyaze_1_1util_1_1SDL__Surface__Deleter" ],
        [ "SDL_Texture_Deleter", "db/dac/structyaze_1_1util_1_1SDL__Texture__Deleter.html", "db/dac/structyaze_1_1util_1_1SDL__Texture__Deleter" ]
      ] ],
      [ "zelda3", "d5/d1f/namespaceyaze_1_1zelda3.html", [
        [ "anonymous_namespace{room_object.cc}", "d5/da6/namespaceyaze_1_1zelda3_1_1anonymous__namespace_02room__object_8cc_03.html", [
          [ "SubtypeTableInfo", "d2/d79/structyaze_1_1zelda3_1_1anonymous__namespace_02room__object_8cc_03_1_1SubtypeTableInfo.html", "d2/d79/structyaze_1_1zelda3_1_1anonymous__namespace_02room__object_8cc_03_1_1SubtypeTableInfo" ]
        ] ],
        [ "EntranceTypes", "dc/dcb/namespaceyaze_1_1zelda3_1_1EntranceTypes.html", [
          [ "EntranceInfo", "dc/dfb/structyaze_1_1zelda3_1_1EntranceTypes_1_1EntranceInfo.html", "dc/dfb/structyaze_1_1zelda3_1_1EntranceTypes_1_1EntranceInfo" ]
        ] ],
        [ "ItemTypes", "da/d9f/namespaceyaze_1_1zelda3_1_1ItemTypes.html", [
          [ "ItemInfo", "d8/d57/structyaze_1_1zelda3_1_1ItemTypes_1_1ItemInfo.html", "d8/d57/structyaze_1_1zelda3_1_1ItemTypes_1_1ItemInfo" ]
        ] ],
        [ "music", "d7/d68/namespaceyaze_1_1zelda3_1_1music.html", [
          [ "SampleEdit", "d4/d72/structyaze_1_1zelda3_1_1music_1_1SampleEdit.html", "d4/d72/structyaze_1_1zelda3_1_1music_1_1SampleEdit" ],
          [ "Song", "d2/dd4/structyaze_1_1zelda3_1_1music_1_1Song.html", "d2/dd4/structyaze_1_1zelda3_1_1music_1_1Song" ],
          [ "SongPart", "d0/dd6/structyaze_1_1zelda3_1_1music_1_1SongPart.html", "d0/dd6/structyaze_1_1zelda3_1_1music_1_1SongPart" ],
          [ "SongRange", "d5/d60/structyaze_1_1zelda3_1_1music_1_1SongRange.html", "d5/d60/structyaze_1_1zelda3_1_1music_1_1SongRange" ],
          [ "SongSpcBlock", "d3/d90/structyaze_1_1zelda3_1_1music_1_1SongSpcBlock.html", "d3/d90/structyaze_1_1zelda3_1_1music_1_1SongSpcBlock" ],
          [ "SpcCommand", "d9/d46/structyaze_1_1zelda3_1_1music_1_1SpcCommand.html", "d9/d46/structyaze_1_1zelda3_1_1music_1_1SpcCommand" ],
          [ "Tracker", "d8/dd6/classyaze_1_1zelda3_1_1music_1_1Tracker.html", "d8/dd6/classyaze_1_1zelda3_1_1music_1_1Tracker" ],
          [ "ZeldaInstrument", "d3/dae/structyaze_1_1zelda3_1_1music_1_1ZeldaInstrument.html", "d3/dae/structyaze_1_1zelda3_1_1music_1_1ZeldaInstrument" ],
          [ "ZeldaSfxInstrument", "db/d2e/structyaze_1_1zelda3_1_1music_1_1ZeldaSfxInstrument.html", "db/d2e/structyaze_1_1zelda3_1_1music_1_1ZeldaSfxInstrument" ],
          [ "ZeldaWave", "df/d2f/structyaze_1_1zelda3_1_1music_1_1ZeldaWave.html", "df/d2f/structyaze_1_1zelda3_1_1music_1_1ZeldaWave" ]
        ] ],
        [ "ObjectCategories", "d0/d1c/namespaceyaze_1_1zelda3_1_1ObjectCategories.html", [
          [ "ObjectCategory", "da/d2d/structyaze_1_1zelda3_1_1ObjectCategories_1_1ObjectCategory.html", "da/d2d/structyaze_1_1zelda3_1_1ObjectCategories_1_1ObjectCategory" ],
          [ "ObjectInfo", "da/d35/structyaze_1_1zelda3_1_1ObjectCategories_1_1ObjectInfo.html", "da/d35/structyaze_1_1zelda3_1_1ObjectCategories_1_1ObjectInfo" ]
        ] ],
        [ "SpriteTypes", "d1/d1c/namespaceyaze_1_1zelda3_1_1SpriteTypes.html", [
          [ "SpriteInfo", "dc/ded/structyaze_1_1zelda3_1_1SpriteTypes_1_1SpriteInfo.html", "dc/ded/structyaze_1_1zelda3_1_1SpriteTypes_1_1SpriteInfo" ]
        ] ],
        [ "test", "df/dfe/namespaceyaze_1_1zelda3_1_1test.html", [
          [ "RoomIntegrationTest", "df/d80/classyaze_1_1zelda3_1_1test_1_1RoomIntegrationTest.html", "df/d80/classyaze_1_1zelda3_1_1test_1_1RoomIntegrationTest" ],
          [ "RoomManipulationTest", "d7/dc3/classyaze_1_1zelda3_1_1test_1_1RoomManipulationTest.html", "d7/dc3/classyaze_1_1zelda3_1_1test_1_1RoomManipulationTest" ]
        ] ],
        [ "DungeonEditorSystem", "d7/d61/classyaze_1_1zelda3_1_1DungeonEditorSystem.html", "d7/d61/classyaze_1_1zelda3_1_1DungeonEditorSystem" ],
        [ "DungeonEditorSystemIntegrationTest", "dd/d59/classyaze_1_1zelda3_1_1DungeonEditorSystemIntegrationTest.html", "dd/d59/classyaze_1_1zelda3_1_1DungeonEditorSystemIntegrationTest" ],
        [ "DungeonMap", "d0/d10/structyaze_1_1zelda3_1_1DungeonMap.html", "d0/d10/structyaze_1_1zelda3_1_1DungeonMap" ],
        [ "DungeonObjectEditor", "de/de7/classyaze_1_1zelda3_1_1DungeonObjectEditor.html", "de/de7/classyaze_1_1zelda3_1_1DungeonObjectEditor" ],
        [ "DungeonRenderingIntegrationTest", "d2/dd6/classyaze_1_1zelda3_1_1DungeonRenderingIntegrationTest.html", "d2/dd6/classyaze_1_1zelda3_1_1DungeonRenderingIntegrationTest" ],
        [ "GameEntity", "d3/d9d/classyaze_1_1zelda3_1_1GameEntity.html", "d3/d9d/classyaze_1_1zelda3_1_1GameEntity" ],
        [ "Inventory", "d6/d3c/classyaze_1_1zelda3_1_1Inventory.html", "d6/d3c/classyaze_1_1zelda3_1_1Inventory" ],
        [ "LayerMergeType", "d3/d1e/structyaze_1_1zelda3_1_1LayerMergeType.html", "d3/d1e/structyaze_1_1zelda3_1_1LayerMergeType" ],
        [ "MouseConfig", "dd/d3f/structyaze_1_1zelda3_1_1MouseConfig.html", "dd/d3f/structyaze_1_1zelda3_1_1MouseConfig" ],
        [ "ObjectDrawer", "d8/d17/classyaze_1_1zelda3_1_1ObjectDrawer.html", "d8/d17/classyaze_1_1zelda3_1_1ObjectDrawer" ],
        [ "ObjectDrawInfo", "d0/d01/structyaze_1_1zelda3_1_1ObjectDrawInfo.html", "d0/d01/structyaze_1_1zelda3_1_1ObjectDrawInfo" ],
        [ "ObjectParser", "d8/ddf/classyaze_1_1zelda3_1_1ObjectParser.html", "d8/ddf/classyaze_1_1zelda3_1_1ObjectParser" ],
        [ "ObjectRenderingTest", "d9/db6/classyaze_1_1zelda3_1_1ObjectRenderingTest.html", "d9/db6/classyaze_1_1zelda3_1_1ObjectRenderingTest" ],
        [ "ObjectRoutineInfo", "dc/d8c/structyaze_1_1zelda3_1_1ObjectRoutineInfo.html", "dc/d8c/structyaze_1_1zelda3_1_1ObjectRoutineInfo" ],
        [ "ObjectSizeInfo", "da/d08/structyaze_1_1zelda3_1_1ObjectSizeInfo.html", "da/d08/structyaze_1_1zelda3_1_1ObjectSizeInfo" ],
        [ "ObjectSubtypeInfo", "de/d8f/structyaze_1_1zelda3_1_1ObjectSubtypeInfo.html", "de/d8f/structyaze_1_1zelda3_1_1ObjectSubtypeInfo" ],
        [ "Overworld", "d9/dc5/classyaze_1_1zelda3_1_1Overworld.html", "d9/dc5/classyaze_1_1zelda3_1_1Overworld" ],
        [ "OverworldEntrance", "d3/d5a/classyaze_1_1zelda3_1_1OverworldEntrance.html", "d3/d5a/classyaze_1_1zelda3_1_1OverworldEntrance" ],
        [ "OverworldEntranceTileTypes", "df/d0c/structyaze_1_1zelda3_1_1OverworldEntranceTileTypes.html", "df/d0c/structyaze_1_1zelda3_1_1OverworldEntranceTileTypes" ],
        [ "OverworldExit", "d6/d2f/classyaze_1_1zelda3_1_1OverworldExit.html", "d6/d2f/classyaze_1_1zelda3_1_1OverworldExit" ],
        [ "OverworldIntegrationTest", "df/dff/classyaze_1_1zelda3_1_1OverworldIntegrationTest.html", "df/dff/classyaze_1_1zelda3_1_1OverworldIntegrationTest" ],
        [ "OverworldItem", "d1/d26/classyaze_1_1zelda3_1_1OverworldItem.html", "d1/d26/classyaze_1_1zelda3_1_1OverworldItem" ],
        [ "OverworldMap", "d9/dcc/classyaze_1_1zelda3_1_1OverworldMap.html", "d9/dcc/classyaze_1_1zelda3_1_1OverworldMap" ],
        [ "OverworldMapTiles", "da/d54/structyaze_1_1zelda3_1_1OverworldMapTiles.html", "da/d54/structyaze_1_1zelda3_1_1OverworldMapTiles" ],
        [ "OverworldTest", "d3/ddf/classyaze_1_1zelda3_1_1OverworldTest.html", "d3/ddf/classyaze_1_1zelda3_1_1OverworldTest" ],
        [ "Room", "d7/df6/classyaze_1_1zelda3_1_1Room.html", "d7/df6/classyaze_1_1zelda3_1_1Room" ],
        [ "RoomEntrance", "d8/d1e/classyaze_1_1zelda3_1_1RoomEntrance.html", "d8/d1e/classyaze_1_1zelda3_1_1RoomEntrance" ],
        [ "RoomLayout", "d9/d70/classyaze_1_1zelda3_1_1RoomLayout.html", "d9/d70/classyaze_1_1zelda3_1_1RoomLayout" ],
        [ "RoomObject", "d3/d6a/classyaze_1_1zelda3_1_1RoomObject.html", "d3/d6a/classyaze_1_1zelda3_1_1RoomObject" ],
        [ "RoomSize", "d6/df8/structyaze_1_1zelda3_1_1RoomSize.html", "d6/df8/structyaze_1_1zelda3_1_1RoomSize" ],
        [ "ScrollWheelConfig", "da/dfb/structyaze_1_1zelda3_1_1ScrollWheelConfig.html", "da/dfb/structyaze_1_1zelda3_1_1ScrollWheelConfig" ],
        [ "Sprite", "d6/db1/classyaze_1_1zelda3_1_1Sprite.html", "d6/db1/classyaze_1_1zelda3_1_1Sprite" ],
        [ "SpriteAction", "d3/da6/classyaze_1_1zelda3_1_1SpriteAction.html", "d3/da6/classyaze_1_1zelda3_1_1SpriteAction" ],
        [ "SpriteBuilder", "d4/d57/classyaze_1_1zelda3_1_1SpriteBuilder.html", "d4/d57/classyaze_1_1zelda3_1_1SpriteBuilder" ],
        [ "SpriteInstruction", "d3/d60/classyaze_1_1zelda3_1_1SpriteInstruction.html", "d3/d60/classyaze_1_1zelda3_1_1SpriteInstruction" ],
        [ "SpritePositionTest", "db/ddc/classyaze_1_1zelda3_1_1SpritePositionTest.html", "db/ddc/classyaze_1_1zelda3_1_1SpritePositionTest" ],
        [ "TitleScreen", "d6/d2e/classyaze_1_1zelda3_1_1TitleScreen.html", "d6/d2e/classyaze_1_1zelda3_1_1TitleScreen" ],
        [ "Zelda3Labels", "d4/d42/structyaze_1_1zelda3_1_1Zelda3Labels.html", null ]
      ] ],
      [ "AssetLoader", "d9/d56/classyaze_1_1AssetLoader.html", null ],
      [ "FontConfig", "db/d0d/structyaze_1_1FontConfig.html", "db/d0d/structyaze_1_1FontConfig" ],
      [ "FontState", "d3/dba/structyaze_1_1FontState.html", "d3/dba/structyaze_1_1FontState" ],
      [ "Rom", "d6/d30/classyaze_1_1Rom.html", "d6/d30/classyaze_1_1Rom" ],
      [ "RomLoadOptions", "db/d22/structyaze_1_1RomLoadOptions.html", "db/d22/structyaze_1_1RomLoadOptions" ],
      [ "Transaction", "df/d26/classyaze_1_1Transaction.html", "df/d26/classyaze_1_1Transaction" ]
    ] ],
    [ "AppDelegate", "d3/d3e/classAppDelegate.html", null ],
    [ "AppViewController", "d1/de7/classAppViewController.html", null ],
    [ "chest", "d4/d5f/structchest.html", "d4/d5f/structchest" ],
    [ "chest_data", "d7/d34/structchest__data.html", "d7/d34/structchest__data" ],
    [ "destination", "d0/dd9/structdestination.html", "d0/dd9/structdestination" ],
    [ "dungeon_sprite", "d2/d04/structdungeon__sprite.html", "d2/d04/structdungeon__sprite" ],
    [ "DungeonTestHarness", "d7/d0f/classDungeonTestHarness.html", "d7/d0f/classDungeonTestHarness" ],
    [ "object_door", "d6/d61/structobject__door.html", "d6/d61/structobject__door" ],
    [ "overloaded", "d9/d94/structoverloaded.html", null ],
    [ "OverworldGoldenDataExtractor", "d8/ddf/classOverworldGoldenDataExtractor.html", "d8/ddf/classOverworldGoldenDataExtractor" ],
    [ "ROMPatchUtility", "db/d1c/classROMPatchUtility.html", null ],
    [ "snes_color", "df/d71/structsnes__color.html", "df/d71/structsnes__color" ],
    [ "snes_palette", "d0/dad/structsnes__palette.html", "d0/dad/structsnes__palette" ],
    [ "snes_tile16", "d7/d54/structsnes__tile16.html", "d7/d54/structsnes__tile16" ],
    [ "snes_tile32", "dc/d59/structsnes__tile32.html", "dc/d59/structsnes__tile32" ],
    [ "snes_tile8", "db/d30/structsnes__tile8.html", "db/d30/structsnes__tile8" ],
    [ "snes_tile_info", "dc/d98/structsnes__tile__info.html", "dc/d98/structsnes__tile__info" ],
    [ "staircase", "d3/d12/structstaircase.html", "d3/d12/structstaircase" ],
    [ "TextEditor", "d0/d28/classTextEditor.html", "d0/d28/classTextEditor" ],
    [ "yaze_bitmap", "dd/dd1/structyaze__bitmap.html", "dd/dd1/structyaze__bitmap" ],
    [ "yaze_editor_context", "d0/d78/structyaze__editor__context.html", "d0/d78/structyaze__editor__context" ],
    [ "yaze_extension", "da/d74/structyaze__extension.html", "da/d74/structyaze__extension" ],
    [ "zelda3_dungeon_room", "de/d5e/structzelda3__dungeon__room.html", "de/d5e/structzelda3__dungeon__room" ],
    [ "zelda3_message", "dd/dde/structzelda3__message.html", "dd/dde/structzelda3__message" ],
    [ "zelda3_overworld", "d4/dbf/structzelda3__overworld.html", "d4/dbf/structzelda3__overworld" ],
    [ "zelda3_overworld_map", "da/d93/structzelda3__overworld__map.html", "da/d93/structzelda3__overworld__map" ],
    [ "zelda3_rom", "de/dad/structzelda3__rom.html", "de/dad/structzelda3__rom" ],
    [ "zelda3_version_pointers", "de/d0d/structzelda3__version__pointers.html", "de/d0d/structzelda3__version__pointers" ]
];