yaze: src/app/yaze.cc File Reference
yaze.cc File Reference
#include "absl/debugging/failure_signal_handler.h"
#include "absl/debugging/symbolize.h"
#include "app/core/controller.h"
Namespaces
namespace yaze::app
Main namespace for the ImGui application.
Functions
int main (int argc, char **argv)
Main entry point for the application.
Function Documentation
main()
int main (int argc, char ** argv)
Main entry point for the application.
Definition at line 20 of file yaze.cc.
References yaze::app::core::Controller::DoRender(), EXIT_IF_ERROR, yaze::app::emu::SNES::Init(), yaze::app::Rom::is_loaded(), yaze::app::core::Controller::IsActive(), yaze::app::Rom::LoadFromFile(), yaze::app::emu::SNES::Memory(), yaze::app::core::Controller::OnEntry(), yaze::app::core::Controller::OnExit(), yaze::app::core::Controller::OnInput(), yaze::app::core::Controller::OnLoad(), yaze::app::emu::SNES::RunFrame(), yaze::app::emu::SNES::SetPixels(), yaze::app::emu::SNES::SetSamples(), and yaze::app::Rom::vector().
Referenced by yaze::app::zelda3::overworld::OverworldMap::LoadPalette(), and yaze::app::zelda3::overworld::palette_internal::SetColorsPalette().