yaze: yaze::app::editor::EditorManager Class Reference
yaze::app::editor::EditorManager Class Reference
The EditorManager controls the main editor window and manages the various editor classes.
#include <editor_manager.h>
Public Member Functions
EditorManager ()
void SetupScreen (std::string filename="")
absl::Status Update ()
auto emulator () -> emu::Emulator &
auto quit ()
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
std::string Serialize () const
Private Member Functions
void ManageActiveEditors ()
absl::Status DrawDynamicLayout ()
void ManageKeyboardShortcuts ()
void InitializeCommands ()
void DrawStatusPopup ()
void DrawAboutPopup ()
void DrawInfoPopup ()
void DrawYazeMenu ()
void DrawYazeMenuBar ()
void LoadRom ()
void SaveRom ()
void OpenRomOrProject (const std::string &filename)
absl::Status OpenProject ()
Private Attributes
bool quit_ = false
bool about_ = false
bool rom_info_ = false
bool backup_rom_ = false
bool save_new_auto_ = true
bool show_status_ = false
bool rom_assets_loaded_ = false
bool dynamic_layout_ = false
absl::Status status_
emu::Emulator emulator_
std::vector< Editor * > active_editors_
std::vector< EditorLayoutParams > active_layouts_
Project current_project_
CommandManager command_manager_
ConstantManager constant_manager_
ExtensionManager extension_manager_
Editor * current_editor_ = nullptr
EditorLayoutParams root_layout_
AssemblyEditor assembly_editor_
DungeonEditor dungeon_editor_
GraphicsEditor graphics_editor_
MusicEditor music_editor_
OverworldEditor overworld_editor_
PaletteEditor palette_editor_
ScreenEditor screen_editor_
SpriteEditor sprite_editor_
SettingsEditor settings_editor_
MessageEditor message_editor_
MemoryEditorWithDiffChecker memory_editor_
yaze_editor_context editor_context_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
The EditorManager controls the main editor window and manages the various editor classes.
This class inherits from SharedRom and ExperimentFlags, and provides functionality for setting up the screen, updating the editor, and shutting down the editor. It also includes methods for drawing various menus and popups, saving the Rom, and managing editor-specific flags.
The EditorManager class contains instances of various editor classes such as AssemblyEditor, DungeonEditor, GraphicsEditor, MusicEditor, OverworldEditor, PaletteEditor, ScreenEditor, and SpriteEditor. The current_editor_ member variable points to the currently active editor in the tab view.
Note
This class assumes the presence of an SDL_Renderer object for rendering graphics.
Definition at line 49 of file editor_manager.h.
Constructor & Destructor Documentation
EditorManager()
yaze::app::editor::EditorManager::EditorManager () inline
Definition at line 51 of file editor_manager.h.
References active_editors_, current_editor_, dungeon_editor_, graphics_editor_, message_editor_, overworld_editor_, palette_editor_, screen_editor_, and sprite_editor_.
Member Function Documentation
SetupScreen()
void yaze::app::editor::EditorManager::SetupScreen (std::string filename = "")
Definition at line 52 of file editor_manager.cc.
References yaze::app::editor::OverworldEditor::InitializeZeml(), overworld_editor_, PRINT_IF_ERROR, and yaze::app::SharedRom::rom().
Referenced by yaze::app::core::Controller::OnEntry(), and yaze::app::core::Controller::SetupScreen().
Update()
absl::Status yaze::app::editor::EditorManager::Update ()
Definition at line 59 of file editor_manager.cc.
References DrawAboutPopup(), DrawDynamicLayout(), DrawInfoPopup(), DrawStatusPopup(), DrawYazeMenu(), dynamic_layout_, yaze::app::editor::OverworldEditor::LoadGraphics(), ManageActiveEditors(), ManageKeyboardShortcuts(), overworld_editor_, RETURN_IF_ERROR, yaze::app::SharedRom::rom(), and rom_assets_loaded_.
Referenced by yaze::app::core::Controller::OnLoad().
emulator()
auto yaze::app::editor::EditorManager::emulator () -> emu::Emulator & inline
Definition at line 65 of file editor_manager.h.
References emulator_.
Referenced by yaze::app::core::Controller::LoadAudioDevice().
quit()
auto yaze::app::editor::EditorManager::quit () inline
Definition at line 66 of file editor_manager.h.
References quit_.
Referenced by yaze::app::core::Controller::OnLoad().
ManageActiveEditors()
void yaze::app::editor::EditorManager::ManageActiveEditors () private
Definition at line 83 of file editor_manager.cc.
References active_editors_, yaze::app::editor::DungeonEditor::add_room(), assembly_editor_, current_editor_, dungeon_editor_, graphics_editor_, ICON_MD_ADD, yaze::app::editor::OverworldEditor::jump_to_tab(), yaze::app::editor::OverworldEditor::jump_to_tab_, yaze::app::editor::kAssembly, yaze::app::editor::kDungeon, yaze::app::editor::kGraphics, yaze::app::editor::kMessage, yaze::app::editor::kMusic, yaze::app::editor::kOverworld, yaze::app::editor::kPalette, yaze::app::editor::kScreen, yaze::app::editor::kSettings, yaze::app::editor::kSprite, message_editor_, music_editor_, overworld_editor_, palette_editor_, screen_editor_, settings_editor_, sprite_editor_, status_, yaze::app::editor::DungeonEditor::Update(), yaze::app::editor::GraphicsEditor::Update(), yaze::app::editor::MessageEditor::Update(), yaze::app::editor::MusicEditor::Update(), yaze::app::editor::OverworldEditor::Update(), yaze::app::editor::PaletteEditor::Update(), yaze::app::editor::ScreenEditor::Update(), yaze::app::editor::SettingsEditor::Update(), yaze::app::editor::SpriteEditor::Update(), and yaze::app::editor::AssemblyEditor::UpdateCodeView().
Referenced by Update().
DrawDynamicLayout()
absl::Status yaze::app::editor::EditorManager::DrawDynamicLayout () private
Definition at line 246 of file editor_manager.cc.
References yaze::app::editor::DrawEditor(), and root_layout_.
Referenced by Update().
ManageKeyboardShortcuts()
void yaze::app::editor::EditorManager::ManageKeyboardShortcuts () private
Definition at line 253 of file editor_manager.cc.
References about_, command_manager_, yaze::app::editor::Editor::Copy(), current_editor_, yaze::app::editor::Editor::Cut(), yaze::app::editor::Editor::Find(), yaze::app::RecentFilesManager::GetRecentFiles(), yaze::app::RecentFilesManager::Load(), LoadRom(), OpenRomOrProject(), yaze::app::editor::Editor::Paste(), quit_, yaze::app::editor::Editor::Redo(), SaveRom(), yaze::app::editor::CommandManager::ShowWhichKey(), status_, and yaze::app::editor::Editor::Undo().
Referenced by Update().
InitializeCommands()
void yaze::app::editor::EditorManager::InitializeCommands () private
Definition at line 312 of file editor_manager.cc.
References assembly_editor_, command_manager_, dungeon_editor_, yaze::app::editor::EditorLayoutParams::editor, graphics_editor_, yaze::app::editor::EditorLayoutParams::h_split, message_editor_, music_editor_, overworld_editor_, palette_editor_, yaze::app::editor::CommandManager::RegisterPrefix(), yaze::app::editor::CommandManager::RegisterSubcommand(), root_layout_, screen_editor_, settings_editor_, sprite_editor_, and yaze::app::editor::EditorLayoutParams::v_split.
DrawStatusPopup()
void yaze::app::editor::EditorManager::DrawStatusPopup () private
Definition at line 386 of file editor_manager.cc.
References ICON_MD_CONTENT_COPY, ICON_MD_ERROR, yaze::app::gui::kDefaultModalSize, show_status_, and status_.
Referenced by Update().
DrawAboutPopup()
void yaze::app::editor::EditorManager::DrawAboutPopup () private
Definition at line 414 of file editor_manager.cc.
References about_, yaze::app::gui::kDefaultModalSize, and yaze::app::core::kYazeVersion.
Referenced by Update().
DrawInfoPopup()
void yaze::app::editor::EditorManager::DrawInfoPopup () private
Definition at line 431 of file editor_manager.cc.
References yaze::app::gui::kDefaultModalSize, yaze::app::SharedRom::rom(), rom_info_, and yaze::app::core::UppercaseHexLongLong().
Referenced by Update().
DrawYazeMenu()
void yaze::app::editor::EditorManager::DrawYazeMenu () private
Definition at line 447 of file editor_manager.cc.
References yaze::app::gui::DrawDisplaySettings(), DrawYazeMenuBar(), ICON_MD_DISPLAY_SETTINGS, and yaze::app::core::kYazeVersion.
Referenced by Update().
DrawYazeMenuBar()
void yaze::app::editor::EditorManager::DrawYazeMenuBar () private
Definition at line 470 of file editor_manager.cc.
References about_, assembly_editor_, backup_rom_, yaze::app::Project::code_folder_, yaze::app::editor::Editor::Copy(), yaze::app::Project::Create(), current_editor_, current_project_, yaze::app::editor::Editor::Cut(), yaze::app::editor::FlagsMenu::Draw(), dynamic_layout_, emulator_, yaze::app::Project::filepath, yaze::app::editor::Editor::Find(), yaze::app::RecentFilesManager::GetRecentFiles(), yaze::app::gui::kDefaultModalSize, yaze::app::Project::labels_filename_, yaze::app::RecentFilesManager::Load(), LoadRom(), memory_editor_, MENU_ITEM, MENU_ITEM2, yaze::app::Project::name, yaze::app::Project::Open(), OpenProject(), OpenRomOrProject(), palette_editor_, yaze::app::editor::Editor::Paste(), yaze::app::Project::project_opened_, quit_, yaze::app::editor::Editor::Redo(), yaze::app::SharedRom::rom(), rom_assets_loaded_, yaze::app::Project::rom_filename_, rom_info_, yaze::app::emu::Emulator::Run(), yaze::app::Project::Save(), save_new_auto_, SaveRom(), yaze::app::core::FileDialogWrapper::ShowOpenFileDialog(), yaze::app::core::FileDialogWrapper::ShowOpenFolderDialog(), status_, yaze::app::editor::Editor::Undo(), yaze::app::editor::AssemblyEditor::Update(), yaze::app::editor::MemoryEditorWithDiffChecker::Update(), and yaze::app::editor::PaletteEditor::Update().
Referenced by DrawYazeMenu().
LoadRom()
void yaze::app::editor::EditorManager::LoadRom () private
Definition at line 762 of file editor_manager.cc.
References yaze::app::RecentFilesManager::AddFile(), yaze::app::RecentFilesManager::Load(), yaze::app::SharedRom::rom(), yaze::app::RecentFilesManager::Save(), and yaze::app::core::FileDialogWrapper::ShowOpenFileDialog().
Referenced by DrawYazeMenuBar(), and ManageKeyboardShortcuts().
SaveRom()
void yaze::app::editor::EditorManager::SaveRom () private
Definition at line 773 of file editor_manager.cc.
References backup_rom_, yaze::app::core::ExperimentFlags::flags(), overworld_editor_, RETURN_VOID_IF_ERROR, yaze::app::SharedRom::rom(), yaze::app::editor::OverworldEditor::Save(), save_new_auto_, yaze::app::editor::ScreenEditor::SaveDungeonMaps(), screen_editor_, and status_.
Referenced by DrawYazeMenuBar(), and ManageKeyboardShortcuts().
OpenRomOrProject()
void yaze::app::editor::EditorManager::OpenRomOrProject (const std::string & filename) private
Definition at line 785 of file editor_manager.cc.
References current_project_, yaze::app::Project::Open(), OpenProject(), yaze::app::SharedRom::rom(), and status_.
Referenced by DrawYazeMenuBar(), and ManageKeyboardShortcuts().
OpenProject()
absl::Status yaze::app::editor::EditorManager::OpenProject () private
Definition at line 796 of file editor_manager.cc.
References yaze::app::RecentFilesManager::AddFile(), assembly_editor_, yaze::app::Project::code_folder_, current_project_, yaze::app::Project::filepath, yaze::app::Project::labels_filename_, yaze::app::RecentFilesManager::Load(), yaze::app::Project::name, yaze::app::editor::AssemblyEditor::OpenFolder(), yaze::app::Project::project_opened_, RETURN_IF_ERROR, yaze::app::SharedRom::rom(), yaze::app::Project::rom_filename_, and yaze::app::RecentFilesManager::Save().
Referenced by DrawYazeMenuBar(), and OpenRomOrProject().
Member Data Documentation
quit_
bool yaze::app::editor::EditorManager::quit_ = false private
Definition at line 88 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), ManageKeyboardShortcuts(), and quit().
about_
bool yaze::app::editor::EditorManager::about_ = false private
Definition at line 89 of file editor_manager.h.
Referenced by DrawAboutPopup(), DrawYazeMenuBar(), and ManageKeyboardShortcuts().
rom_info_
bool yaze::app::editor::EditorManager::rom_info_ = false private
Definition at line 90 of file editor_manager.h.
Referenced by DrawInfoPopup(), and DrawYazeMenuBar().
backup_rom_
bool yaze::app::editor::EditorManager::backup_rom_ = false private
Definition at line 91 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), and SaveRom().
save_new_auto_
bool yaze::app::editor::EditorManager::save_new_auto_ = true private
Definition at line 92 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), and SaveRom().
show_status_
bool yaze::app::editor::EditorManager::show_status_ = false private
Definition at line 93 of file editor_manager.h.
Referenced by DrawStatusPopup().
rom_assets_loaded_
bool yaze::app::editor::EditorManager::rom_assets_loaded_ = false private
Definition at line 94 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), and Update().
dynamic_layout_
bool yaze::app::editor::EditorManager::dynamic_layout_ = false private
Definition at line 95 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), and Update().
status_
absl::Status yaze::app::editor::EditorManager::status_ private
Definition at line 97 of file editor_manager.h.
Referenced by DrawStatusPopup(), DrawYazeMenuBar(), ManageActiveEditors(), ManageKeyboardShortcuts(), OpenRomOrProject(), and SaveRom().
emulator_
emu::Emulator yaze::app::editor::EditorManager::emulator_ private
Definition at line 99 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), and emulator().
active_editors_
std::vector<Editor *> yaze::app::editor::EditorManager::active_editors_ private
Definition at line 101 of file editor_manager.h.
Referenced by EditorManager(), and ManageActiveEditors().
active_layouts_
std::vector<EditorLayoutParams> yaze::app::editor::EditorManager::active_layouts_ private
Definition at line 102 of file editor_manager.h.
current_project_
Project yaze::app::editor::EditorManager::current_project_ private
Definition at line 104 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), OpenProject(), and OpenRomOrProject().
command_manager_
CommandManager yaze::app::editor::EditorManager::command_manager_ private
Definition at line 105 of file editor_manager.h.
Referenced by InitializeCommands(), and ManageKeyboardShortcuts().
constant_manager_
ConstantManager yaze::app::editor::EditorManager::constant_manager_ private
Definition at line 106 of file editor_manager.h.
extension_manager_
ExtensionManager yaze::app::editor::EditorManager::extension_manager_ private
Definition at line 107 of file editor_manager.h.
current_editor_
Editor* yaze::app::editor::EditorManager::current_editor_ = nullptr private
Definition at line 109 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), EditorManager(), ManageActiveEditors(), and ManageKeyboardShortcuts().
root_layout_
EditorLayoutParams yaze::app::editor::EditorManager::root_layout_ private
Definition at line 110 of file editor_manager.h.
Referenced by DrawDynamicLayout(), and InitializeCommands().
assembly_editor_
AssemblyEditor yaze::app::editor::EditorManager::assembly_editor_ private
Definition at line 111 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), InitializeCommands(), ManageActiveEditors(), and OpenProject().
dungeon_editor_
DungeonEditor yaze::app::editor::EditorManager::dungeon_editor_ private
Definition at line 112 of file editor_manager.h.
Referenced by EditorManager(), InitializeCommands(), and ManageActiveEditors().
graphics_editor_
GraphicsEditor yaze::app::editor::EditorManager::graphics_editor_ private
Definition at line 113 of file editor_manager.h.
Referenced by EditorManager(), InitializeCommands(), and ManageActiveEditors().
music_editor_
MusicEditor yaze::app::editor::EditorManager::music_editor_ private
Definition at line 114 of file editor_manager.h.
Referenced by InitializeCommands(), and ManageActiveEditors().
overworld_editor_
OverworldEditor yaze::app::editor::EditorManager::overworld_editor_ private
Definition at line 115 of file editor_manager.h.
Referenced by EditorManager(), InitializeCommands(), ManageActiveEditors(), SaveRom(), SetupScreen(), and Update().
palette_editor_
PaletteEditor yaze::app::editor::EditorManager::palette_editor_ private
Definition at line 116 of file editor_manager.h.
Referenced by DrawYazeMenuBar(), EditorManager(), InitializeCommands(), and ManageActiveEditors().
screen_editor_
ScreenEditor yaze::app::editor::EditorManager::screen_editor_ private
Definition at line 117 of file editor_manager.h.
Referenced by EditorManager(), InitializeCommands(), ManageActiveEditors(), and SaveRom().
sprite_editor_
SpriteEditor yaze::app::editor::EditorManager::sprite_editor_ private
Definition at line 118 of file editor_manager.h.
Referenced by EditorManager(), InitializeCommands(), and ManageActiveEditors().
settings_editor_
SettingsEditor yaze::app::editor::EditorManager::settings_editor_ private
Definition at line 119 of file editor_manager.h.
Referenced by InitializeCommands(), and ManageActiveEditors().
message_editor_
MessageEditor yaze::app::editor::EditorManager::message_editor_ private
Definition at line 120 of file editor_manager.h.
Referenced by EditorManager(), InitializeCommands(), and ManageActiveEditors().
memory_editor_
MemoryEditorWithDiffChecker yaze::app::editor::EditorManager::memory_editor_ private
Definition at line 121 of file editor_manager.h.
Referenced by DrawYazeMenuBar().
editor_context_
yaze_editor_context yaze::app::editor::EditorManager::editor_context_ private
Definition at line 123 of file editor_manager.h.
The documentation for this class was generated from the following files:
src/app/editor/editor_manager.h
src/app/editor/editor_manager.cc