yaze: yaze::test::DungeonEditorIntegrationTest Class Reference
yaze::test::DungeonEditorIntegrationTest Class Reference
Integration test framework for dungeon editor components.
#include <dungeon_editor_test.h>
Protected Member Functions
void SetUp () override
void TearDown () override
absl::Status CreateMockRom ()
absl::Status LoadTestRoomData ()
absl::Status TestObjectParsing ()
absl::Status TestObjectRendering ()
absl::Status TestRoomGraphics ()
absl::Status TestPaletteHandling ()
std::vector< uint8_t > GenerateMockRoomHeader (int room_id)
std::vector< uint8_t > GenerateMockObjectData ()
std::vector< uint8_t > GenerateMockGraphicsData ()
Protected Attributes
std::unique_ptr< Rom > mock_rom_
std::unique_ptr< editor::DungeonEditor > dungeon_editor_
Static Protected Attributes
static constexpr int kTestRoomId = 0x01
static constexpr int kTestObjectId = 0x10
static constexpr size_t kMockRomSize = 0x200000
Detailed Description
Integration test framework for dungeon editor components.
This class provides a comprehensive testing framework for the dungeon editor, allowing modular testing of individual components and their interactions.
Definition at line 21 of file dungeon_editor_test.h.
Member Function Documentation
SetUp()
void yaze::test::DungeonEditorIntegrationTest::SetUp () override protected
Definition at line 13 of file dungeon_editor_test.cc.
References CreateMockRom(), dungeon_editor_, LoadTestRoomData(), and mock_rom_.
TearDown()
void yaze::test::DungeonEditorIntegrationTest::TearDown () override protected
Definition at line 21 of file dungeon_editor_test.cc.
References dungeon_editor_, and mock_rom_.
CreateMockRom()
absl::Status yaze::test::DungeonEditorIntegrationTest::CreateMockRom () protected
Definition at line 26 of file dungeon_editor_test.cc.
References kMockRomSize, mock_rom_, and yaze::test::MockRom::SetMockData().
Referenced by SetUp().
LoadTestRoomData()
absl::Status yaze::test::DungeonEditorIntegrationTest::LoadTestRoomData () protected
Definition at line 59 of file dungeon_editor_test.cc.
References GenerateMockGraphicsData(), GenerateMockObjectData(), GenerateMockRoomHeader(), kTestObjectId, kTestRoomId, mock_rom_, yaze::test::MockRom::SetMockObjectData(), and yaze::test::MockRom::SetMockRoomData().
Referenced by SetUp().
TestObjectParsing()
absl::Status yaze::test::DungeonEditorIntegrationTest::TestObjectParsing () protected
Definition at line 71 of file dungeon_editor_test.cc.
References kTestRoomId, yaze::zelda3::LoadRoomFromRom(), and mock_rom_.
TestObjectRendering()
absl::Status yaze::test::DungeonEditorIntegrationTest::TestObjectRendering () protected
Definition at line 94 of file dungeon_editor_test.cc.
References kTestRoomId, yaze::zelda3::LoadRoomFromRom(), and mock_rom_.
TestRoomGraphics()
absl::Status yaze::test::DungeonEditorIntegrationTest::TestRoomGraphics () protected
Definition at line 112 of file dungeon_editor_test.cc.
References kTestRoomId, yaze::zelda3::LoadRoomFromRom(), and mock_rom_.
TestPaletteHandling()
absl::Status yaze::test::DungeonEditorIntegrationTest::TestPaletteHandling () protected
Definition at line 126 of file dungeon_editor_test.cc.
References kTestRoomId, yaze::zelda3::LoadRoomFromRom(), and mock_rom_.
GenerateMockRoomHeader()
std::vector< uint8_t > yaze::test::DungeonEditorIntegrationTest::GenerateMockRoomHeader (int room_id) protected
Definition at line 137 of file dungeon_editor_test.cc.
Referenced by LoadTestRoomData().
GenerateMockObjectData()
std::vector< uint8_t > yaze::test::DungeonEditorIntegrationTest::GenerateMockObjectData () protected
Definition at line 159 of file dungeon_editor_test.cc.
Referenced by LoadTestRoomData().
GenerateMockGraphicsData()
std::vector< uint8_t > yaze::test::DungeonEditorIntegrationTest::GenerateMockGraphicsData () protected
Definition at line 178 of file dungeon_editor_test.cc.
Referenced by LoadTestRoomData().
Member Data Documentation
mock_rom_
std::unique_ptr<Rom> yaze::test::DungeonEditorIntegrationTest::mock_rom_ protected
Definition at line 41 of file dungeon_editor_test.h.
Referenced by CreateMockRom(), LoadTestRoomData(), SetUp(), TearDown(), TestObjectParsing(), TestObjectRendering(), TestPaletteHandling(), and TestRoomGraphics().
dungeon_editor_
std::unique_ptr<editor::DungeonEditor> yaze::test::DungeonEditorIntegrationTest::dungeon_editor_ protected
Definition at line 42 of file dungeon_editor_test.h.
Referenced by SetUp(), and TearDown().
kTestRoomId
int yaze::test::DungeonEditorIntegrationTest::kTestRoomId = 0x01 static constexpr protected
Definition at line 45 of file dungeon_editor_test.h.
Referenced by LoadTestRoomData(), TestObjectParsing(), TestObjectRendering(), TestPaletteHandling(), and TestRoomGraphics().
kTestObjectId
int yaze::test::DungeonEditorIntegrationTest::kTestObjectId = 0x10 static constexpr protected
Definition at line 46 of file dungeon_editor_test.h.
Referenced by LoadTestRoomData().
kMockRomSize
size_t yaze::test::DungeonEditorIntegrationTest::kMockRomSize = 0x200000 static constexpr protected
Definition at line 47 of file dungeon_editor_test.h.
Referenced by CreateMockRom().
The documentation for this class was generated from the following files:
test/integration/dungeon_editor_test.h
test/integration/dungeon_editor_test.cc