yaze: yaze::app::editor::PaletteEditor Class Reference
yaze::app::editor::PaletteEditor Class Reference
Allows the user to view and edit in game palettes.
#include <palette_editor.h>
Public Member Functions
PaletteEditor ()
absl::Status Update () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
void DisplayCategoryTable ()
absl::Status EditColorInPalette (gfx::SnesPalette &palette, int index)
absl::Status ResetColorToOriginal (gfx::SnesPalette &palette, int index, const gfx::SnesPalette &originalPalette)
absl::Status DrawPaletteGroup (int category, bool right_side=false)
void DrawCustomPalette ()
void DrawModifiedColors ()
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Public Member Functions inherited from yaze::app::editor::Editor
Editor ()=default
virtual ~Editor ()=default
EditorType type () const
Private Member Functions
absl::Status HandleColorPopup (gfx::SnesPalette &palette, int i, int j, int n)
Private Attributes
absl::Status status_
gfx::SnesColor current_color_
GfxGroupEditor gfx_group_editor_
std::vector< gfx::SnesColor > custom_palette_
ImVec4 saved_palette_ [256] = {}
palette_internal::PaletteEditorHistory history_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Protected Attributes inherited from yaze::app::editor::Editor
EditorType type_
Detailed Description
Allows the user to view and edit in game palettes.
Definition at line 77 of file palette_editor.h.
Constructor & Destructor Documentation
PaletteEditor()
yaze::app::editor::PaletteEditor::PaletteEditor () inline
Definition at line 79 of file palette_editor.h.
References custom_palette_, yaze::app::editor::kPalette, and yaze::app::editor::Editor::type_.
Member Function Documentation
Update()
absl::Status yaze::app::editor::PaletteEditor::Update () override virtual
Implements yaze::app::editor::Editor.
Definition at line 175 of file palette_editor.cc.
References CLEAR_AND_RETURN_STATUS, current_color_, DisplayCategoryTable(), DrawCustomPalette(), DrawModifiedColors(), yaze::app::editor::GfxGroupEditor::DrawPaletteViewer(), gfx_group_editor_, yaze::app::gfx::kNumPalettes, yaze::app::editor::kPaletteTableFlags, yaze::app::SharedRom::rom(), yaze::app::gui::SnesColorEdit4(), and status_.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageActiveEditors().
Cut()
absl::Status yaze::app::editor::PaletteEditor::Cut () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 86 of file palette_editor.h.
Copy()
absl::Status yaze::app::editor::PaletteEditor::Copy () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 87 of file palette_editor.h.
Paste()
absl::Status yaze::app::editor::PaletteEditor::Paste () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 88 of file palette_editor.h.
Undo()
absl::Status yaze::app::editor::PaletteEditor::Undo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 89 of file palette_editor.h.
Redo()
absl::Status yaze::app::editor::PaletteEditor::Redo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 90 of file palette_editor.h.
Find()
absl::Status yaze::app::editor::PaletteEditor::Find () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 91 of file palette_editor.h.
DisplayCategoryTable()
void yaze::app::editor::PaletteEditor::DisplayCategoryTable ()
Definition at line 261 of file palette_editor.cc.
References yaze::app::gui::BeginChildWithScrollbar(), DrawPaletteGroup(), yaze::app::gfx::kAreaColors, yaze::app::gfx::kClothes, yaze::app::gfx::kCrystal, yaze::app::gfx::kDungeonMap, yaze::app::gfx::kDungeons, yaze::app::gfx::kGlobalSprites, yaze::app::gfx::kShield, yaze::app::gfx::kSpritesAux1, yaze::app::gfx::kSpritesAux2, yaze::app::gfx::kSpritesAux3, yaze::app::gfx::kSword, yaze::app::gfx::kTriforce, yaze::app::gfx::kWorldColors, yaze::app::gfx::kWorldMap, and status_.
Referenced by Update().
EditColorInPalette()
absl::Status yaze::app::editor::PaletteEditor::EditColorInPalette (gfx::SnesPalette & palette, int index)
Definition at line 447 of file palette_editor.cc.
References ASSIGN_OR_RETURN, yaze::app::gfx::SnesPalette::GetColor(), and yaze::app::gfx::SnesPalette::size().
ResetColorToOriginal()
absl::Status yaze::app::editor::PaletteEditor::ResetColorToOriginal (gfx::SnesPalette & palette, int index, const gfx::SnesPalette & originalPalette)
Definition at line 463 of file palette_editor.cc.
References ASSIGN_OR_RETURN, yaze::app::gfx::SnesPalette::GetColor(), and yaze::app::gfx::SnesPalette::size().
DrawPaletteGroup()
absl::Status yaze::app::editor::PaletteEditor::DrawPaletteGroup (int category, bool right_side = false)
Definition at line 345 of file palette_editor.cc.
References ASSIGN_OR_RETURN, current_color_, yaze::app::gfx::SnesPalette::GetColor(), HandleColorPopup(), yaze::app::editor::kPalNoAlpha, yaze::app::gfx::SnesPalette::mutable_color(), yaze::app::gfx::PaletteGroup::mutable_palette(), RETURN_IF_ERROR, yaze::app::SharedRom::rom(), yaze::app::gfx::PaletteGroup::size(), yaze::app::gfx::SnesPalette::size(), and yaze::app::gui::SnesColorButton().
Referenced by DisplayCategoryTable().
DrawCustomPalette()
void yaze::app::editor::PaletteEditor::DrawCustomPalette ()
Definition at line 224 of file palette_editor.cc.
References custom_palette_, and yaze::app::gui::SnesColorEdit4().
Referenced by Update().
DrawModifiedColors()
void yaze::app::editor::PaletteEditor::DrawModifiedColors ()
Definition at line 391 of file palette_editor.cc.
References yaze::app::editor::palette_internal::PaletteEditorHistory::GetModifiedColor(), yaze::app::editor::palette_internal::PaletteEditorHistory::GetOriginalColor(), history_, yaze::app::editor::palette_internal::PaletteEditorHistory::size(), and yaze::app::gui::SnesColorEdit4().
Referenced by Update().
HandleColorPopup()
absl::Status yaze::app::editor::PaletteEditor::HandleColorPopup (gfx::SnesPalette & palette, int i, int j, int n) private
Definition at line 407 of file palette_editor.cc.
References yaze::app::gfx::ConvertRGBtoSNES(), F32_TO_INT8_SAT, history_, yaze::app::editor::kColorPopupFlags, yaze::app::editor::palette_internal::PaletteEditorHistory::RecordChange(), yaze::app::gui::SnesColorEdit4(), and yaze::app::gfx::ToFloatArray().
Referenced by DrawPaletteGroup().
Member Data Documentation
status_
absl::Status yaze::app::editor::PaletteEditor::status_ private
Definition at line 107 of file palette_editor.h.
Referenced by DisplayCategoryTable(), and Update().
current_color_
gfx::SnesColor yaze::app::editor::PaletteEditor::current_color_ private
Definition at line 108 of file palette_editor.h.
Referenced by DrawPaletteGroup(), and Update().
gfx_group_editor_
GfxGroupEditor yaze::app::editor::PaletteEditor::gfx_group_editor_ private
Definition at line 110 of file palette_editor.h.
Referenced by Update().
custom_palette_
std::vector<gfx::SnesColor> yaze::app::editor::PaletteEditor::custom_palette_ private
Definition at line 112 of file palette_editor.h.
Referenced by DrawCustomPalette(), and PaletteEditor().
saved_palette_
ImVec4 yaze::app::editor::PaletteEditor::saved_palette_[256] = {} private
Definition at line 114 of file palette_editor.h.
history_
palette_internal::PaletteEditorHistory yaze::app::editor::PaletteEditor::history_ private
Definition at line 116 of file palette_editor.h.
Referenced by DrawModifiedColors(), and HandleColorPopup().
The documentation for this class was generated from the following files:
src/app/editor/graphics/palette_editor.h
src/app/editor/graphics/palette_editor.cc