yaze: yaze::core::FileDialogWrapper Class Reference
yaze::core::FileDialogWrapper Class Reference
#include <file_dialog.h>
Static Public Member Functions
static std::string ShowOpenFileDialog ()
ShowOpenFileDialog opens a file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
static std::string ShowOpenFolderDialog ()
ShowOpenFolderDialog opens a file dialog and returns the selected folder path. Uses global feature flag to choose implementation.
static std::string ShowSaveFileDialog (const std::string &default_name="", const std::string &default_extension="")
ShowSaveFileDialog opens a save file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
static std::string ShowOpenFileDialogNFD ()
static std::string ShowOpenFileDialogBespoke ()
static std::string ShowSaveFileDialogNFD (const std::string &default_name="", const std::string &default_extension="")
static std::string ShowSaveFileDialogBespoke (const std::string &default_name="", const std::string &default_extension="")
static std::string ShowOpenFolderDialogNFD ()
static std::string ShowOpenFolderDialogBespoke ()
static std::vector< std::string > GetSubdirectoriesInFolder (const std::string &folder_path)
static std::vector< std::string > GetFilesInFolder (const std::string &folder_path)
Detailed Description
Definition at line 10 of file file_dialog.h.
Member Function Documentation
ShowOpenFileDialog()
static std::string yaze::core::FileDialogWrapper::ShowOpenFileDialog () static
ShowOpenFileDialog opens a file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
Referenced by yaze::editor::GraphicsEditor::DrawCgxImport(), yaze::editor::SpriteEditor::DrawCustomSpritesMetadata(), yaze::editor::MessageEditor::DrawExpandedMessageSettings(), yaze::editor::GraphicsEditor::DrawFileImport(), yaze::editor::AssemblyEditor::DrawFileMenu(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::GraphicsEditor::DrawObjImport(), yaze::editor::GraphicsEditor::DrawPaletteControls(), yaze::editor::GraphicsEditor::DrawScrImport(), yaze::test::TestManager::DrawTestDashboard(), yaze::editor::GraphicsEditor::DrawTilemapImport(), yaze::editor::EditorManager::DrawWelcomeScreen(), yaze::editor::ScreenEditor::LoadBinaryGfx(), yaze::zelda3::LoadDungeonMapGfxFromBinary(), yaze::editor::EditorManager::LoadRom(), yaze::editor::EditorManager::OpenProject(), yaze::emu::Emulator::RenderNavBar(), yaze::gui::ThemeManager::ShowSimpleThemeEditor(), yaze::gui::ThemeManager::ShowThemeSelector(), and yaze::editor::MemoryEditorWithDiffChecker::Update().
ShowOpenFolderDialog()
static std::string yaze::core::FileDialogWrapper::ShowOpenFolderDialog () static
ShowOpenFolderDialog opens a file dialog and returns the selected folder path. Uses global feature flag to choose implementation.
Referenced by yaze::editor::EditorManager::CreateNewProject(), yaze::editor::EditorManager::DrawMenuBar(), and yaze::editor::AssemblyEditor::UpdateCodeView().
ShowSaveFileDialog()
static std::string yaze::core::FileDialogWrapper::ShowSaveFileDialog (const std::string & default_name = "", const std::string & default_extension = "") static
ShowSaveFileDialog opens a save file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
Referenced by yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::EditorManager::SaveProjectAs(), and yaze::gui::ThemeManager::ShowSimpleThemeEditor().
ShowOpenFileDialogNFD()
static std::string yaze::core::FileDialogWrapper::ShowOpenFileDialogNFD () static
Referenced by yaze::test::TestManager::DrawTestDashboard().
ShowOpenFileDialogBespoke()
static std::string yaze::core::FileDialogWrapper::ShowOpenFileDialogBespoke () static
Referenced by yaze::test::TestManager::DrawTestDashboard().
ShowSaveFileDialogNFD()
static std::string yaze::core::FileDialogWrapper::ShowSaveFileDialogNFD (const std::string & default_name = "", const std::string & default_extension = "") static
ShowSaveFileDialogBespoke()
static std::string yaze::core::FileDialogWrapper::ShowSaveFileDialogBespoke (const std::string & default_name = "", const std::string & default_extension = "") static
ShowOpenFolderDialogNFD()
static std::string yaze::core::FileDialogWrapper::ShowOpenFolderDialogNFD () static
ShowOpenFolderDialogBespoke()
static std::string yaze::core::FileDialogWrapper::ShowOpenFolderDialogBespoke () static
GetSubdirectoriesInFolder()
static std::vector< std::string > yaze::core::FileDialogWrapper::GetSubdirectoriesInFolder (const std::string & folder_path) static
Referenced by yaze::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
GetFilesInFolder()
static std::vector< std::string > yaze::core::FileDialogWrapper::GetFilesInFolder (const std::string & folder_path) static
Referenced by yaze::gui::ThemeManager::DiscoverAvailableThemeFiles(), and yaze::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
The documentation for this class was generated from the following file:
src/app/core/platform/file_dialog.h