yaze: yaze::util::FlagParser Class Reference
yaze::util::FlagParser Class Reference
#include <flag.h>
Public Member Functions
FlagParser (FlagRegistry *registry)
void Parse (int argc, char **argv)
void Parse (std::vector< std::string > *tokens)
Private Member Functions
bool ExtractFlagAndValue (const std::string &token, std::string *flag_name, std::string *value_string)
bool ExtractFlag (const std::string &token, std::string *flag_name)
Private Attributes
FlagRegistry * registry_
Detailed Description
Definition at line 114 of file flag.h.
Constructor & Destructor Documentation
FlagParser()
yaze::util::FlagParser::FlagParser (FlagRegistry * registry) inline explicit
Definition at line 116 of file flag.h.
Member Function Documentation
Parse() [1/2]
void yaze::util::FlagParser::Parse (int argc, char ** argv) inline
Definition at line 119 of file flag.h.
References Parse().
Referenced by main(), main(), Parse(), and yaze_app_main().
Parse() [2/2]
void yaze::util::FlagParser::Parse (std::vector< std::string > * tokens)
Definition at line 10 of file flag.cc.
References yaze::util::FlagRegistry::AllFlags(), ExtractFlag(), ExtractFlagAndValue(), yaze::util::FlagRegistry::GetFlag(), yaze::util::global_flag_registry(), yaze::util::IFlag::ParseValue(), registry_, YAZE_VERSION_MAJOR, YAZE_VERSION_MINOR, and YAZE_VERSION_PATCH.
ExtractFlagAndValue()
bool yaze::util::FlagParser::ExtractFlagAndValue (const std::string & token, std::string * flag_name, std::string * value_string) private
Definition at line 75 of file flag.cc.
Referenced by Parse().
ExtractFlag()
bool yaze::util::FlagParser::ExtractFlag (const std::string & token, std::string * flag_name) private
Definition at line 87 of file flag.cc.
Referenced by Parse().
Member Data Documentation
registry_
FlagRegistry* yaze::util::FlagParser::registry_ private
Definition at line 133 of file flag.h.
Referenced by Parse().
The documentation for this class was generated from the following files:
src/util/flag.h
src/util/flag.cc