yaze: yaze::app::emu::ClockImpl Class Reference
yaze::app::emu::ClockImpl Class Reference
#include <clock.h>
Public Member Functions
ClockImpl ()=default
virtual ~ClockImpl ()=default
void UpdateCycleCount (double deltaTime)
void Cycle ()
void UpdateClock (double delta) override
void ResetAccumulatedTime () override
unsigned long long GetCycleCount () const override
float GetFrequency () const override
void SetFrequency (float new_frequency) override
Public Member Functions inherited from yaze::app::emu::Clock
virtual ~Clock ()=default
Private Attributes
uint64_t cycle = 0
float frequency = 0.0
unsigned long long cycleCount = 0
double accumulatedTime = 0.0
Detailed Description
Definition at line 20 of file clock.h.
Constructor & Destructor Documentation
ClockImpl()
yaze::app::emu::ClockImpl::ClockImpl () default
~ClockImpl()
virtual yaze::app::emu::ClockImpl::~ClockImpl () virtual default
Member Function Documentation
UpdateCycleCount()
void yaze::app::emu::ClockImpl::UpdateCycleCount (double deltaTime) inline
Definition at line 25 of file clock.h.
References accumulatedTime, Cycle(), and frequency.
Referenced by UpdateClock().
Cycle()
void yaze::app::emu::ClockImpl::Cycle () inline
Definition at line 35 of file clock.h.
References cycle, and cycleCount.
Referenced by UpdateCycleCount().
UpdateClock()
void yaze::app::emu::ClockImpl::UpdateClock (double delta) inline override virtual
Implements yaze::app::emu::Clock.
Definition at line 40 of file clock.h.
References ResetAccumulatedTime(), and UpdateCycleCount().
ResetAccumulatedTime()
void yaze::app::emu::ClockImpl::ResetAccumulatedTime () inline override virtual
Implements yaze::app::emu::Clock.
Definition at line 45 of file clock.h.
References accumulatedTime.
Referenced by UpdateClock().
GetCycleCount()
unsigned long long yaze::app::emu::ClockImpl::GetCycleCount () const inline override virtual
Implements yaze::app::emu::Clock.
Definition at line 46 of file clock.h.
References cycleCount.
GetFrequency()
float yaze::app::emu::ClockImpl::GetFrequency () const inline override virtual
Implements yaze::app::emu::Clock.
Definition at line 47 of file clock.h.
References frequency.
SetFrequency()
void yaze::app::emu::ClockImpl::SetFrequency (float new_frequency) inline override virtual
Implements yaze::app::emu::Clock.
Definition at line 48 of file clock.h.
References frequency.
Member Data Documentation
cycle
uint64_t yaze::app::emu::ClockImpl::cycle = 0 private
Definition at line 53 of file clock.h.
Referenced by Cycle().
frequency
float yaze::app::emu::ClockImpl::frequency = 0.0 private
Definition at line 54 of file clock.h.
Referenced by GetFrequency(), SetFrequency(), and UpdateCycleCount().
cycleCount
unsigned long long yaze::app::emu::ClockImpl::cycleCount = 0 private
Definition at line 55 of file clock.h.
Referenced by Cycle(), and GetCycleCount().
accumulatedTime
double yaze::app::emu::ClockImpl::accumulatedTime = 0.0 private
Definition at line 56 of file clock.h.
Referenced by ResetAccumulatedTime(), and UpdateCycleCount().
The documentation for this class was generated from the following file:
src/app/emu/cpu/clock.h