yaze: yaze::app::emu::audio::Apu Class Reference
yaze::app::emu::audio::Apu Class Reference
The Apu class represents the Audio Processing Unit (APU) of a system.
#include <apu.h>
Public Member Functions
Apu (MemoryImpl &memory, AudioRam &aram, Clock &clock)
void Init ()
void Reset ()
void Update ()
void Notify (uint32_t address, uint16_t data) override
void ProcessSamples ()
uint8_t FetchSampleForVoice (uint8_t voice_num)
uint16_t CalculateAddressForVoice (uint8_t voice_num)
int16_t GetNextSample ()
void Initialize ()
void SignalReady ()
void WriteToPort (uint8_t portNum, uint8_t value)
void UpdateClock (int delta_time)
uint8_t FetchSampleFromRam (uint16_t address) const
void PushToAudioBuffer (int16_t sample)
const std::vector< int16_t > & GetAudioSamples () const
Public Member Functions inherited from yaze::app::emu::memory::Observer
virtual ~Observer ()=default
Private Member Functions
void UpdateChannelSettings ()
int16_t GenerateSample (int channel)
void ApplyEnvelope (int channel)
uint8_t ReadDspMemory (uint16_t address)
void WriteDspMemory (uint16_t address, uint8_t value)
Private Attributes
uint8_t ports_ [4] = {0}
AudioRam & aram_
Clock & clock_
MemoryImpl & memory_
DigitalSignalProcessor dsp_
Spc700 spc700_ {aram_}
std::vector< int16_t > audio_samples_
std::function< void()> ready_callback_
Static Private Attributes
static const uint8_t READY_SIGNAL_0 = 0xAA
static const uint8_t READY_SIGNAL_1 = 0xBB
static const uint8_t BEGIN_SIGNAL = 0xCC
Detailed Description
The Apu class represents the Audio Processing Unit (APU) of a system.
The Apu class is responsible for generating audio samples and managing the APU state. It interacts with the Memory, AudioRam, and Clock classes to read/write data and update the clock. The class also implements the Observer interface to receive notifications from the system.
IPL ROM Info
64 kilobytes of RAM are mapped across the 16-bit memory space of the SPC-700. Some regions of this space are overlaid with special hardware functions.
Range Note
$0000-00EF Zero Page RAM $00F0-00FF Sound CPU Registers $0100-01FF Stack Page RAM $0200-FFBF RAM $FFC0-FFFF IPL ROM or RAM
The region at $FFC0-FFFF will normally read from the 64-byte IPL ROM, but the underlying RAM can always be written to, and the high bit of the Control register $F1 can be cleared to unmap the IPL ROM and allow read access to this RAM.
Constructor & Destructor Documentation
Apu()
yaze::app::emu::audio::Apu::Apu (MemoryImpl & memory, AudioRam & aram, Clock & clock) inline
Member Function Documentation
Init()
void yaze::app::emu::audio::Apu::Init ()
References clock_, dsp_, FetchSampleFromRam(), yaze::app::emu::audio::kApuClockSpeed, PushToAudioBuffer(), yaze::app::emu::Clock::SetFrequency(), yaze::app::emu::audio::DigitalSignalProcessor::SetSampleFetcher(), and yaze::app::emu::audio::DigitalSignalProcessor::SetSamplePusher().
Referenced by yaze::app::emu::SNES::Init().
Reset()
void yaze::app::emu::audio::Apu::Reset ()
References clock_, dsp_, yaze::app::emu::audio::DigitalSignalProcessor::Reset(), yaze::app::emu::audio::Spc700::Reset(), yaze::app::emu::Clock::ResetAccumulatedTime(), and spc700_.
Update()
void yaze::app::emu::audio::Apu::Update ()
References clock_, yaze::app::emu::audio::Spc700::ExecuteInstructions(), yaze::app::emu::Clock::GetCycleCount(), yaze::app::emu::audio::Spc700::PC, ProcessSamples(), yaze::app::emu::audio::Spc700::read(), spc700_, and UpdateChannelSettings().
Referenced by yaze::app::emu::SNES::Run(), and yaze::app::emu::SNES::StepRun().
Notify()
void yaze::app::emu::audio::Apu::Notify (uint32_t address, uint16_t data) override virtual
Todo
Handle data byte transfer here
Todo
Handle the setup of destination address
Todo
Handle additional communication/commands
Implements yaze::app::emu::memory::Observer.
References ports_, SignalReady(), spc700_, and yaze::app::emu::audio::Spc700::write().
ProcessSamples()
void yaze::app::emu::audio::Apu::ProcessSamples ()
References audio_samples_, dsp_, FetchSampleForVoice(), and yaze::app::emu::audio::DigitalSignalProcessor::ProcessSample().
Referenced by Update().
FetchSampleForVoice()
uint8_t yaze::app::emu::audio::Apu::FetchSampleForVoice (uint8_t voice_num)
References aram_, CalculateAddressForVoice(), and yaze::app::emu::audio::AudioRam::read().
Referenced by ProcessSamples().
CalculateAddressForVoice()
uint16_t yaze::app::emu::audio::Apu::CalculateAddressForVoice (uint8_t voice_num)
Todo
Calculate the address for the specified voice
Referenced by FetchSampleForVoice().
GetNextSample()
int16_t yaze::app::emu::audio::Apu::GetNextSample ()
Todo
Return the last sample instead of 0.
References audio_samples_.
Referenced by yaze::app::emu::anonymous_namespace{snes.cc}::audio_callback().
Initialize()
void yaze::app::emu::audio::Apu::Initialize () inline
References dsp_, yaze::app::emu::audio::DigitalSignalProcessor::Reset(), yaze::app::emu::audio::Spc700::Reset(), SignalReady(), and spc700_.
SignalReady()
void yaze::app::emu::audio::Apu::SignalReady () inline
References memory_, READY_SIGNAL_0, READY_SIGNAL_1, and yaze::app::emu::memory::MemoryImpl::WriteByte().
Referenced by Initialize(), and Notify().
WriteToPort()
void yaze::app::emu::audio::Apu::WriteToPort (uint8_t portNum, uint8_t value) inline
References memory_, ports_, and yaze::app::emu::memory::MemoryImpl::WriteByte().
UpdateClock()
void yaze::app::emu::audio::Apu::UpdateClock (int delta_time) inline
References clock_, and yaze::app::emu::Clock::UpdateClock().
Referenced by yaze::app::emu::SNES::Run(), and yaze::app::emu::SNES::StepRun().
FetchSampleFromRam()
uint8_t yaze::app::emu::audio::Apu::FetchSampleFromRam (uint16_t address) const inline
References aram_, and yaze::app::emu::audio::AudioRam::read().
Referenced by Init().
PushToAudioBuffer()
void yaze::app::emu::audio::Apu::PushToAudioBuffer (int16_t sample) inline
References audio_samples_.
Referenced by Init().
GetAudioSamples()
const std::vector< int16_t > & yaze::app::emu::audio::Apu::GetAudioSamples () const
References audio_samples_.
UpdateChannelSettings()
void yaze::app::emu::audio::Apu::UpdateChannelSettings () private
Todo
Implement this method to update the channel settings.
Referenced by Update().
GenerateSample()
int16_t yaze::app::emu::audio::Apu::GenerateSample (int channel) private
Todo
Implement this method to generate a sample for the specified channel.
ApplyEnvelope()
void yaze::app::emu::audio::Apu::ApplyEnvelope (int channel) private
Todo
Implement this method to apply an envelope to the specified channel.
ReadDspMemory()
uint8_t yaze::app::emu::audio::Apu::ReadDspMemory (uint16_t address) private
References dsp_, and yaze::app::emu::audio::DigitalSignalProcessor::ReadGlobalReg().
WriteDspMemory()
void yaze::app::emu::audio::Apu::WriteDspMemory (uint16_t address, uint8_t value) private
References dsp_, and yaze::app::emu::audio::DigitalSignalProcessor::WriteGlobalReg().
Member Data Documentation
READY_SIGNAL_0
const uint8_t yaze::app::emu::audio::Apu::READY_SIGNAL_0 = 0xAA static private
Referenced by SignalReady().
READY_SIGNAL_1
const uint8_t yaze::app::emu::audio::Apu::READY_SIGNAL_1 = 0xBB static private
Referenced by SignalReady().
BEGIN_SIGNAL
const uint8_t yaze::app::emu::audio::Apu::BEGIN_SIGNAL = 0xCC static private
ports_
uint8_t yaze::app::emu::audio::Apu::ports_[4] = {0} private
Referenced by Notify(), and WriteToPort().
aram_
AudioRam& yaze::app::emu::audio::Apu::aram_ private
Referenced by FetchSampleForVoice(), and FetchSampleFromRam().
clock_
Clock& yaze::app::emu::audio::Apu::clock_ private
Referenced by Init(), Reset(), Update(), and UpdateClock().
memory_
MemoryImpl& yaze::app::emu::audio::Apu::memory_ private
Referenced by SignalReady(), and WriteToPort().
dsp_
DigitalSignalProcessor yaze::app::emu::audio::Apu::dsp_ private
Referenced by Init(), Initialize(), ProcessSamples(), ReadDspMemory(), Reset(), and WriteDspMemory().
spc700_
Spc700 yaze::app::emu::audio::Apu::spc700_ {aram_} private
Referenced by Initialize(), Notify(), Reset(), and Update().
audio_samples_
std::vector<int16_t> yaze::app::emu::audio::Apu::audio_samples_ private
Referenced by GetAudioSamples(), GetNextSample(), ProcessSamples(), and PushToAudioBuffer().
ready_callback_
std::function<void()> yaze::app::emu::audio::Apu::ready_callback_ private
The documentation for this class was generated from the following files:
src/app/emu/audio/apu.h
src/app/emu/audio/apu.cc