yaze: yaze::app::editor::MessageEditor Class Reference
yaze::app::editor::MessageEditor Class Reference
#include <message_editor.h>
Classes
struct DictionaryEntry
struct TextBox
Public Member Functions
MessageEditor ()
absl::Status Initialize ()
absl::Status Update () override
void DrawMessageList ()
void DrawCurrentMessage ()
void DrawTextCommands ()
void ReadAllTextData ()
void BuildDictionaryEntries ()
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
absl::Status Save ()
void Delete ()
void SelectAll ()
TextElement FindMatchingCommand (uint8_t byte)
TextElement FindMatchingSpecial (uint8_t value)
std::string ParseTextDataByte (uint8_t value)
DictionaryEntry GetDictionaryFromID (uint8_t value)
void DrawTileToPreview (int x, int y, int srcx, int srcy, int pal, int sizex=1, int sizey=1)
void DrawCharacterToPreview (char c)
void DrawCharacterToPreview (const std::vector< uint8_t > &text)
void DrawStringToPreview (std::string str)
void DrawMessagePreview ()
std::string DisplayTextOverflowError (int pos, bool bank)
void InsertCommandButton_Click_1 ()
void InsertSpecialButton_Click ()
void InsertSelectedText (std::string str)
Public Member Functions inherited from yaze::app::editor::Editor
Editor ()=default
virtual ~Editor ()=default
EditorType type () const
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Static Public Member Functions
static std::vector< uint8_t > ParseMessageToData (std::string str)
static ParsedElement FindMatchingElement (std::string str)
static uint8_t FindDictionaryEntry (uint8_t value)
static uint8_t FindMatchingCharacter (char value)
Static Public Attributes
static const std::vector< DictionaryEntry > AllDicts
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Private Attributes
bool skip_next = false
bool from_form = false
bool data_loaded_ = false
int text_line_ = 0
int text_position_ = 0
int shown_lines_ = 0
int selected_tile = 0
int current_message_id_ = 0
uint8_t width_array [100]
std::string search_text_ = ""
std::vector< MessageData > list_of_texts_
std::vector< MessageData > displayed_messages_
std::vector< std::string > parsed_messages_
MessageData current_message_
Bytes font_gfx16_data_
Bytes current_font_gfx16_data_
gfx::Bitmap font_gfx_bitmap_
gfx::Bitmap current_font_gfx16_bitmap_
gui::Canvas font_gfx_canvas_ {"##FontGfxCanvas", ImVec2(128, 128)}
gui::Canvas current_font_gfx16_canvas_
gfx::SnesPalette font_preview_colors_
TextBox message_text_box_
Additional Inherited Members
Protected Attributes inherited from yaze::app::editor::Editor
EditorType type_
Detailed Description
Definition at line 119 of file message_editor.h.
Constructor & Destructor Documentation
MessageEditor()
yaze::app::editor::MessageEditor::MessageEditor () inline
Definition at line 121 of file message_editor.h.
References yaze::app::editor::kMessage, and yaze::app::editor::Editor::type_.
Member Function Documentation
Initialize()
absl::Status yaze::app::editor::MessageEditor::Initialize ()
Definition at line 50 of file message_editor.cc.
References yaze::app::gfx::SnesPalette::AddColor(), BuildDictionaryEntries(), current_font_gfx16_bitmap_, current_font_gfx16_data_, yaze::app::editor::DICTOFF, displayed_messages_, DrawMessagePreview(), yaze::app::editor::TextElement::Empty(), FindMatchingCommand(), font_gfx16_data_, font_gfx_bitmap_, font_preview_colors_, yaze::app::editor::TextElement::GenericToken, GetDictionaryFromID(), yaze::app::core::Renderer::GetInstance(), yaze::app::editor::TextElement::ID, yaze::app::editor::kCharactersWidth, yaze::app::editor::kGfxFont, yaze::app::editor::kLine2, yaze::app::editor::kLine3, yaze::app::editor::kScrollVertical, list_of_texts_, yaze::app::gfx::SnesPalette::mutable_color(), yaze::app::gfx::Bitmap::mutable_palette(), yaze::app::gfx::Bitmap::palette(), parsed_messages_, ReadAllTextData(), RETURN_IF_ERROR, yaze::app::SharedRom::rom(), yaze::app::gfx::SnesPalette::size(), yaze::app::gfx::SnesTo8bppSheet(), and width_array.
Referenced by Update().
Update()
absl::Status yaze::app::editor::MessageEditor::Update () override virtual
Implements yaze::app::editor::Editor.
Definition at line 131 of file message_editor.cc.
References current_message_, data_loaded_, DrawCurrentMessage(), DrawMessageList(), DrawTextCommands(), Initialize(), list_of_texts_, RETURN_IF_ERROR, and yaze::app::SharedRom::rom().
Referenced by yaze::app::editor::EditorManager::ManageActiveEditors().
DrawMessageList()
void yaze::app::editor::MessageEditor::DrawMessageList ()
Definition at line 161 of file message_editor.cc.
References current_message_, displayed_messages_, DrawMessagePreview(), list_of_texts_, parsed_messages_, search_text_, yaze::app::core::UppercaseHexLong(), and yaze::app::core::UppercaseHexWord().
Referenced by Update().
DrawCurrentMessage()
void yaze::app::editor::MessageEditor::DrawCurrentMessage ()
Definition at line 202 of file message_editor.cc.
References yaze::app::gui::BeginPadding(), current_font_gfx16_bitmap_, current_font_gfx16_canvas_, current_message_, yaze::app::editor::MessageData::Data, yaze::app::gui::Canvas::DrawBackground(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawContextMenu(), yaze::app::gui::Canvas::DrawGrid(), DrawMessagePreview(), yaze::app::gui::Canvas::DrawOverlay(), yaze::app::gui::EndPadding(), font_gfx_bitmap_, font_gfx_canvas_, yaze::app::core::Renderer::GetInstance(), yaze::app::editor::MessageData::ID, message_text_box_, parsed_messages_, ParseMessageToData(), yaze::app::editor::MessageEditor::TextBox::text, and yaze::app::core::Renderer::UpdateBitmap().
Referenced by Update().
DrawTextCommands()
void yaze::app::editor::MessageEditor::DrawTextCommands ()
Definition at line 240 of file message_editor.cc.
Referenced by Update().
ReadAllTextData()
void yaze::app::editor::MessageEditor::ReadAllTextData ()
Definition at line 281 of file message_editor.cc.
References yaze::app::editor::BANKToken, yaze::app::editor::DICTIONARYTOKEN, yaze::app::editor::TextElement::Empty(), FindDictionaryEntry(), FindMatchingCommand(), FindMatchingSpecial(), yaze::app::core::Get24LocalFromPC(), yaze::app::editor::TextElement::GetParameterizedToken(), yaze::app::editor::TextElement::HasArgument, yaze::app::editor::kPointersDictionaries, yaze::app::editor::kTextData, yaze::app::editor::kTextData2, list_of_texts_, yaze::app::editor::MESSAGETERMINATOR, ParseTextDataByte(), yaze::app::SharedRom::rom(), yaze::app::editor::TextElement::Token, and yaze::app::core::UppercaseHexWord().
Referenced by Initialize().
BuildDictionaryEntries()
void yaze::app::editor::MessageEditor::BuildDictionaryEntries ()
Definition at line 254 of file message_editor.cc.
References yaze::app::editor::kNumDictionaryEntries, yaze::app::editor::kPointersDictionaries, yaze::app::editor::kTextData, ParseTextDataByte(), yaze::app::SharedRom::rom(), and yaze::app::core::SnesToPc().
Referenced by Initialize().
Cut()
absl::Status yaze::app::editor::MessageEditor::Cut () override virtual
Implements yaze::app::editor::Editor.
Definition at line 642 of file message_editor.cc.
References yaze::app::editor::MessageEditor::TextBox::Cut(), message_text_box_, and yaze::app::editor::MessageEditor::TextBox::text.
Copy()
absl::Status yaze::app::editor::MessageEditor::Copy () override virtual
Implements yaze::app::editor::Editor.
Definition at line 660 of file message_editor.cc.
References yaze::app::editor::MessageEditor::TextBox::Copy(), message_text_box_, and yaze::app::editor::MessageEditor::TextBox::selection_length.
Paste()
absl::Status yaze::app::editor::MessageEditor::Paste () override virtual
Implements yaze::app::editor::Editor.
Definition at line 651 of file message_editor.cc.
References message_text_box_, and yaze::app::editor::MessageEditor::TextBox::Paste().
Undo()
absl::Status yaze::app::editor::MessageEditor::Undo () override virtual
Implements yaze::app::editor::Editor.
Definition at line 669 of file message_editor.cc.
References yaze::app::editor::MessageEditor::TextBox::can_undo, yaze::app::editor::MessageEditor::TextBox::clearUndo(), message_text_box_, and yaze::app::editor::MessageEditor::TextBox::Undo().
Redo()
absl::Status yaze::app::editor::MessageEditor::Redo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 136 of file message_editor.h.
Find()
absl::Status yaze::app::editor::MessageEditor::Find () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 139 of file message_editor.h.
Save()
absl::Status yaze::app::editor::MessageEditor::Save ()
Definition at line 681 of file message_editor.cc.
References DisplayTextOverflowError(), yaze::app::editor::kBlockTerminator, yaze::app::editor::kCharactersWidth, yaze::app::editor::kTextData, yaze::app::editor::kTextData2, yaze::app::editor::kTextData2End, yaze::app::editor::kTextDataEnd, list_of_texts_, yaze::app::editor::MESSAGETERMINATOR, RETURN_IF_ERROR, yaze::app::SharedRom::rom(), and width_array.
Delete()
void yaze::app::editor::MessageEditor::Delete ()
Definition at line 763 of file message_editor.cc.
References yaze::app::editor::MessageEditor::TextBox::clear(), message_text_box_, and yaze::app::editor::MessageEditor::TextBox::selection_length.
SelectAll()
void yaze::app::editor::MessageEditor::SelectAll ()
Definition at line 771 of file message_editor.cc.
References yaze::app::editor::MessageEditor::TextBox::Focus(), message_text_box_, yaze::app::editor::MessageEditor::TextBox::SelectAll(), and yaze::app::editor::MessageEditor::TextBox::selection_length.
FindMatchingCommand()
TextElement yaze::app::editor::MessageEditor::FindMatchingCommand (uint8_t byte)
Definition at line 380 of file message_editor.cc.
Referenced by Initialize(), ParseTextDataByte(), and ReadAllTextData().
FindMatchingSpecial()
TextElement yaze::app::editor::MessageEditor::FindMatchingSpecial (uint8_t value)
Definition at line 390 of file message_editor.cc.
Referenced by ParseTextDataByte(), and ReadAllTextData().
ParseTextDataByte()
std::string yaze::app::editor::MessageEditor::ParseTextDataByte (uint8_t value)
Definition at line 510 of file message_editor.cc.
References yaze::app::editor::DICTIONARYTOKEN, yaze::app::editor::TextElement::Empty(), FindDictionaryEntry(), FindMatchingCommand(), FindMatchingSpecial(), and yaze::app::editor::TextElement::GenericToken.
Referenced by BuildDictionaryEntries(), and ReadAllTextData().
ParseMessageToData()
std::vector< uint8_t > yaze::app::editor::MessageEditor::ParseMessageToData (std::string str) static
Definition at line 438 of file message_editor.cc.
References yaze::app::editor::ParsedElement::Active, yaze::app::editor::DICTIONARYTOKEN, FindMatchingCharacter(), FindMatchingElement(), yaze::app::editor::TextElement::HasArgument, yaze::app::editor::TextElement::ID, yaze::app::editor::ParsedElement::Parent, and yaze::app::editor::ParsedElement::Value.
Referenced by yaze::app::editor::MessageEditor::DictionaryEntry::DictionaryEntry(), and DrawCurrentMessage().
FindMatchingElement()
ParsedElement yaze::app::editor::MessageEditor::FindMatchingElement (std::string str) static
Definition at line 402 of file message_editor.cc.
References yaze::app::editor::DICTIONARYTOKEN, and yaze::app::editor::DICTOFF.
Referenced by ParseMessageToData().
GetDictionaryFromID()
MessageEditor::DictionaryEntry yaze::app::editor::MessageEditor::GetDictionaryFromID (uint8_t value)
Definition at line 485 of file message_editor.cc.
Referenced by DrawCharacterToPreview(), and Initialize().
FindDictionaryEntry()
uint8_t yaze::app::editor::MessageEditor::FindDictionaryEntry (uint8_t value) static
Definition at line 493 of file message_editor.cc.
References yaze::app::editor::DICTOFF.
Referenced by ParseTextDataByte(), and ReadAllTextData().
FindMatchingCharacter()
uint8_t yaze::app::editor::MessageEditor::FindMatchingCharacter (char value) static
Definition at line 501 of file message_editor.cc.
Referenced by DrawCharacterToPreview(), and ParseMessageToData().
DrawTileToPreview()
void yaze::app::editor::MessageEditor::DrawTileToPreview (int x, int y, int srcx, int srcy, int pal, int sizex = 1, int sizey = 1)
Definition at line 539 of file message_editor.cc.
References current_font_gfx16_data_, and font_gfx16_data_.
Referenced by DrawCharacterToPreview().
DrawCharacterToPreview() [1/2]
void yaze::app::editor::MessageEditor::DrawCharacterToPreview (char c)
Definition at line 574 of file message_editor.cc.
References DrawCharacterToPreview(), and FindMatchingCharacter().
Referenced by DrawCharacterToPreview(), DrawCharacterToPreview(), DrawMessagePreview(), and DrawStringToPreview().
DrawCharacterToPreview() [2/2]
void yaze::app::editor::MessageEditor::DrawCharacterToPreview (const std::vector< uint8_t > & text)
Definition at line 578 of file message_editor.cc.
References yaze::app::editor::DICTOFF, DrawCharacterToPreview(), DrawStringToPreview(), DrawTileToPreview(), GetDictionaryFromID(), yaze::app::editor::kLine1, yaze::app::editor::kLine2, yaze::app::editor::kLine3, yaze::app::editor::kScrollVertical, skip_next, text_line_, text_position_, and width_array.
DrawStringToPreview()
void yaze::app::editor::MessageEditor::DrawStringToPreview (std::string str)
Definition at line 568 of file message_editor.cc.
References DrawCharacterToPreview().
Referenced by DrawCharacterToPreview().
DrawMessagePreview()
void yaze::app::editor::MessageEditor::DrawMessagePreview ()
Definition at line 631 of file message_editor.cc.
References current_font_gfx16_data_, current_message_, yaze::app::editor::MessageData::Data, DrawCharacterToPreview(), shown_lines_, text_line_, and text_position_.
Referenced by DrawCurrentMessage(), DrawMessageList(), and Initialize().
DisplayTextOverflowError()
std::string yaze::app::editor::MessageEditor::DisplayTextOverflowError (int pos, bool bank)
Definition at line 726 of file message_editor.cc.
References yaze::app::editor::kTextData, yaze::app::editor::kTextData2, yaze::app::editor::kTextData2End, and yaze::app::editor::kTextDataEnd.
Referenced by Save().
InsertCommandButton_Click_1()
void yaze::app::editor::MessageEditor::InsertCommandButton_Click_1 ()
Definition at line 741 of file message_editor.cc.
InsertSpecialButton_Click()
void yaze::app::editor::MessageEditor::InsertSpecialButton_Click ()
Definition at line 749 of file message_editor.cc.
InsertSelectedText()
void yaze::app::editor::MessageEditor::InsertSelectedText (std::string str)
Definition at line 754 of file message_editor.cc.
References yaze::app::editor::MessageEditor::TextBox::Focus(), from_form, message_text_box_, and yaze::app::editor::MessageEditor::TextBox::selection_start.
Member Data Documentation
AllDicts
const std::vector<DictionaryEntry> yaze::app::editor::MessageEditor::AllDicts static
Definition at line 196 of file message_editor.h.
skip_next
bool yaze::app::editor::MessageEditor::skip_next = false private
Definition at line 199 of file message_editor.h.
Referenced by DrawCharacterToPreview().
from_form
bool yaze::app::editor::MessageEditor::from_form = false private
Definition at line 200 of file message_editor.h.
Referenced by InsertSelectedText().
data_loaded_
bool yaze::app::editor::MessageEditor::data_loaded_ = false private
Definition at line 201 of file message_editor.h.
Referenced by Update().
text_line_
int yaze::app::editor::MessageEditor::text_line_ = 0 private
Definition at line 203 of file message_editor.h.
Referenced by DrawCharacterToPreview(), and DrawMessagePreview().
text_position_
int yaze::app::editor::MessageEditor::text_position_ = 0 private
Definition at line 204 of file message_editor.h.
Referenced by DrawCharacterToPreview(), and DrawMessagePreview().
shown_lines_
int yaze::app::editor::MessageEditor::shown_lines_ = 0 private
Definition at line 205 of file message_editor.h.
Referenced by DrawMessagePreview().
selected_tile
int yaze::app::editor::MessageEditor::selected_tile = 0 private
Definition at line 206 of file message_editor.h.
current_message_id_
int yaze::app::editor::MessageEditor::current_message_id_ = 0 private
Definition at line 207 of file message_editor.h.
width_array
uint8_t yaze::app::editor::MessageEditor::width_array[100] private
Definition at line 209 of file message_editor.h.
Referenced by DrawCharacterToPreview(), Initialize(), and Save().
search_text_
std::string yaze::app::editor::MessageEditor::search_text_ = "" private
Definition at line 211 of file message_editor.h.
Referenced by DrawMessageList().
list_of_texts_
std::vector<MessageData> yaze::app::editor::MessageEditor::list_of_texts_ private
Definition at line 213 of file message_editor.h.
Referenced by DrawMessageList(), Initialize(), ReadAllTextData(), Save(), and Update().
displayed_messages_
std::vector<MessageData> yaze::app::editor::MessageEditor::displayed_messages_ private
Definition at line 214 of file message_editor.h.
Referenced by DrawMessageList(), and Initialize().
parsed_messages_
std::vector<std::string> yaze::app::editor::MessageEditor::parsed_messages_ private
Definition at line 215 of file message_editor.h.
Referenced by DrawCurrentMessage(), DrawMessageList(), and Initialize().
current_message_
MessageData yaze::app::editor::MessageEditor::current_message_ private
Definition at line 217 of file message_editor.h.
Referenced by DrawCurrentMessage(), DrawMessageList(), DrawMessagePreview(), and Update().
font_gfx16_data_
Bytes yaze::app::editor::MessageEditor::font_gfx16_data_ private
Definition at line 219 of file message_editor.h.
Referenced by DrawTileToPreview(), and Initialize().
current_font_gfx16_data_
Bytes yaze::app::editor::MessageEditor::current_font_gfx16_data_ private
Definition at line 220 of file message_editor.h.
Referenced by DrawMessagePreview(), DrawTileToPreview(), and Initialize().
font_gfx_bitmap_
gfx::Bitmap yaze::app::editor::MessageEditor::font_gfx_bitmap_ private
Definition at line 222 of file message_editor.h.
Referenced by DrawCurrentMessage(), and Initialize().
current_font_gfx16_bitmap_
gfx::Bitmap yaze::app::editor::MessageEditor::current_font_gfx16_bitmap_ private
Definition at line 223 of file message_editor.h.
Referenced by DrawCurrentMessage(), and Initialize().
font_gfx_canvas_
gui::Canvas yaze::app::editor::MessageEditor::font_gfx_canvas_ {"##FontGfxCanvas", ImVec2(128, 128)} private
Definition at line 225 of file message_editor.h.
Referenced by DrawCurrentMessage().
current_font_gfx16_canvas_
gui::Canvas yaze::app::editor::MessageEditor::current_font_gfx16_canvas_ private
Initial value:
{"##CurrentMessageGfx",
                                         ImVec2(172, 4096)}
Definition at line 226 of file message_editor.h.
Referenced by DrawCurrentMessage().
font_preview_colors_
gfx::SnesPalette yaze::app::editor::MessageEditor::font_preview_colors_ private
Definition at line 229 of file message_editor.h.
Referenced by Initialize().
message_text_box_
TextBox yaze::app::editor::MessageEditor::message_text_box_ private
Definition at line 286 of file message_editor.h.
Referenced by Copy(), Cut(), Delete(), DrawCurrentMessage(), InsertSelectedText(), Paste(), SelectAll(), and Undo().
The documentation for this class was generated from the following files:
src/app/editor/message/message_editor.h
src/app/editor/message/message_editor.cc