yaze: yaze::emu::AsmParser Class Reference
yaze::emu::AsmParser Class Reference
#include <asm_parser.h>
Public Member Functions
std::vector< uint8_t > Parse (const std::string &instruction)
std::vector< std::string > Tokenize (const std::string &instruction)
Private Member Functions
void AppendOperandBytes (std::vector< uint8_t > &bytes, const std::string &operand, const AddressingMode &addressing_mode)
AddressingMode DetermineMode (const std::vector< std::string > &tokens)
bool TryParseByte (const std::string &str, uint8_t &value)
bool TryParseHex (const std::string &str, uint32_t &value)
void CreateInternalOpcodeMap ()
Private Attributes
std::unordered_map< MnemonicMode, uint8_t, MnemonicModeHash > mnemonic_to_opcode_
Detailed Description
Definition at line 64 of file asm_parser.h.
Member Function Documentation
Parse()
std::vector< uint8_t > yaze::emu::AsmParser::Parse (const std::string & instruction) inline
Definition at line 66 of file asm_parser.h.
References AppendOperandBytes(), CreateInternalOpcodeMap(), DetermineMode(), mnemonic_to_opcode_, and Tokenize().
Referenced by yaze::test::TEST_F().
Tokenize()
std::vector< std::string > yaze::emu::AsmParser::Tokenize (const std::string & instruction) inline
Definition at line 135 of file asm_parser.h.
Referenced by Parse(), yaze::test::TEST_F(), and yaze::test::TEST_F().
AppendOperandBytes()
void yaze::emu::AsmParser::AppendOperandBytes (std::vector< uint8_t > & bytes, const std::string & operand, const AddressingMode & addressing_mode) inline private
Definition at line 150 of file asm_parser.h.
References yaze::emu::kAbsolute, yaze::emu::kAbsoluteLong, yaze::emu::kImmediate, and yaze::emu::kImplied.
Referenced by Parse().
DetermineMode()
AddressingMode yaze::emu::AsmParser::DetermineMode (const std::vector< std::string > & tokens) inline private
Definition at line 183 of file asm_parser.h.
References yaze::emu::kAbsolute, yaze::emu::kAbsoluteLong, yaze::emu::kImmediate, and yaze::emu::kImplied.
Referenced by Parse().
TryParseByte()
bool yaze::emu::AsmParser::TryParseByte (const std::string & str, uint8_t & value) inline private
Definition at line 196 of file asm_parser.h.
TryParseHex()
bool yaze::emu::AsmParser::TryParseHex (const std::string & str, uint32_t & value) inline private
Definition at line 205 of file asm_parser.h.
CreateInternalOpcodeMap()
void yaze::emu::AsmParser::CreateInternalOpcodeMap () inline private
Definition at line 214 of file asm_parser.h.
References yaze::emu::kAbsolute, yaze::emu::kAbsoluteIndexedX, yaze::emu::kAbsoluteIndexedY, yaze::emu::kAbsoluteIndirect, yaze::emu::kAccumulator, yaze::emu::kDirectPage, yaze::emu::kDirectPageIndexedX, yaze::emu::kDirectPageIndexedY, yaze::emu::kDirectPageIndirect, yaze::emu::kDirectPageIndirectIndexedY, yaze::emu::kImmediate, yaze::emu::kImplied, yaze::emu::kProgramCounterRelative, yaze::emu::kProgramCounterRelativeLong, yaze::emu::kStackRelative, yaze::emu::kStackRelativeIndirectIndexedY, and mnemonic_to_opcode_.
Referenced by Parse().
Member Data Documentation
mnemonic_to_opcode_
std::unordered_map<MnemonicMode, uint8_t, MnemonicModeHash> yaze::emu::AsmParser::mnemonic_to_opcode_ private
Definition at line 439 of file asm_parser.h.
Referenced by CreateInternalOpcodeMap(), and Parse().
The documentation for this class was generated from the following file:
src/app/emu/memory/asm_parser.h