yaze: yaze::app::editor::MusicEditor Class Reference
yaze::app::editor::MusicEditor Class Reference
A class for editing music data in a Rom.
#include <music_editor.h>
Public Member Functions
MusicEditor ()
absl::Status Update () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Find () override
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Public Member Functions inherited from yaze::app::editor::Editor
Editor ()=default
virtual ~Editor ()=default
EditorType type () const
Private Member Functions
void DrawChannels ()
void DrawPianoStaff ()
void DrawPianoRoll ()
void DrawSongToolset ()
void DrawToolset ()
Private Attributes
zelda3::music::Tracker music_tracker_
AssemblyEditor assembly_editor_
ImGuiTableFlags toolset_table_flags_ = ImGuiTableFlags_SizingFixedFit
ImGuiTableFlags music_editor_flags_
ImGuiTableFlags channel_table_flags_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Protected Attributes inherited from yaze::app::editor::Editor
EditorType type_
Detailed Description
A class for editing music data in a Rom.
Definition at line 62 of file music_editor.h.
Constructor & Destructor Documentation
MusicEditor()
yaze::app::editor::MusicEditor::MusicEditor () inline
Definition at line 64 of file music_editor.h.
References yaze::app::editor::kMusic, and yaze::app::editor::Editor::type_.
Member Function Documentation
Update()
absl::Status yaze::app::editor::MusicEditor::Update () override virtual
Implements yaze::app::editor::Editor.
Definition at line 15 of file music_editor.cc.
References assembly_editor_, DrawChannels(), DrawPianoRoll(), DrawToolset(), yaze::app::editor::AssemblyEditor::InlineUpdate(), and music_editor_flags_.
Referenced by yaze::app::editor::EditorManager::ManageActiveEditors().
Undo()
absl::Status yaze::app::editor::MusicEditor::Undo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 68 of file music_editor.h.
Redo()
absl::Status yaze::app::editor::MusicEditor::Redo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 69 of file music_editor.h.
Cut()
absl::Status yaze::app::editor::MusicEditor::Cut () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 70 of file music_editor.h.
Copy()
absl::Status yaze::app::editor::MusicEditor::Copy () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 71 of file music_editor.h.
Paste()
absl::Status yaze::app::editor::MusicEditor::Paste () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 72 of file music_editor.h.
Find()
absl::Status yaze::app::editor::MusicEditor::Find () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 73 of file music_editor.h.
DrawChannels()
void yaze::app::editor::MusicEditor::DrawChannels () private
Definition at line 37 of file music_editor.cc.
References DrawPianoStaff().
Referenced by Update().
DrawPianoStaff()
void yaze::app::editor::MusicEditor::DrawPianoStaff () private
Definition at line 52 of file music_editor.cc.
Referenced by DrawChannels().
DrawPianoRoll()
void yaze::app::editor::MusicEditor::DrawPianoRoll () private
Definition at line 90 of file music_editor.cc.
Referenced by Update().
DrawSongToolset()
void yaze::app::editor::MusicEditor::DrawSongToolset () private
Definition at line 154 of file music_editor.cc.
References toolset_table_flags_.
DrawToolset()
void yaze::app::editor::MusicEditor::DrawToolset () private
Definition at line 166 of file music_editor.cc.
References BUTTON_COLUMN, ICON_MD_ACCESS_TIME, ICON_MD_FAST_FORWARD, ICON_MD_FAST_REWIND, ICON_MD_PLAY_ARROW, ICON_MD_STOP, ICON_MD_VOLUME_UP, yaze::app::gui::ItemLabel(), yaze::app::zelda3::music::Tracker::LoadSongs(), music_tracker_, yaze::app::SharedRom::rom(), and toolset_table_flags_.
Referenced by Update().
Member Data Documentation
music_tracker_
zelda3::music::Tracker yaze::app::editor::MusicEditor::music_tracker_ private
Definition at line 82 of file music_editor.h.
Referenced by DrawToolset().
assembly_editor_
AssemblyEditor yaze::app::editor::MusicEditor::assembly_editor_ private
Definition at line 86 of file music_editor.h.
Referenced by Update().
toolset_table_flags_
ImGuiTableFlags yaze::app::editor::MusicEditor::toolset_table_flags_ = ImGuiTableFlags_SizingFixedFit private
Definition at line 87 of file music_editor.h.
Referenced by DrawSongToolset(), and DrawToolset().
music_editor_flags_
ImGuiTableFlags yaze::app::editor::MusicEditor::music_editor_flags_ private
Initial value:
= ImGuiTableFlags_SizingFixedFit |
                                        ImGuiTableFlags_Resizable |
                                        ImGuiTableFlags_Reorderable
Definition at line 88 of file music_editor.h.
Referenced by Update().
channel_table_flags_
ImGuiTableFlags yaze::app::editor::MusicEditor::channel_table_flags_ private
Initial value:
=
      ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
      ImGuiTableFlags_Hideable | ImGuiTableFlags_Sortable |
      ImGuiTableFlags_SortMulti | ImGuiTableFlags_RowBg |
      ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersV |
      ImGuiTableFlags_NoBordersInBody | ImGuiTableFlags_ScrollY
Definition at line 92 of file music_editor.h.
The documentation for this class was generated from the following files:
src/app/editor/music/music_editor.h
src/app/editor/music/music_editor.cc