yaze: yaze::test::UITestSuite Class Reference
yaze::test::UITestSuite Class Reference
#include <integrated_test_suite.h>
Public Member Functions
UITestSuite ()=default
~UITestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
Definition at line 431 of file integrated_test_suite.h.
Constructor & Destructor Documentation
UITestSuite()
yaze::test::UITestSuite::UITestSuite () default
~UITestSuite()
yaze::test::UITestSuite::~UITestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::UITestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 436 of file integrated_test_suite.h.
Referenced by RunTests().
GetCategory()
TestCategory yaze::test::UITestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 437 of file integrated_test_suite.h.
References yaze::test::kUI.
Referenced by RunTests().
RunTests()
absl::Status yaze::test::UITestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 439 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kSkipped, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
DrawConfiguration()
void yaze::test::UITestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 459 of file integrated_test_suite.h.
The documentation for this class was generated from the following file:
src/app/test/integrated_test_suite.h