yaze: yaze::zelda3::SpriteAction Class Reference
yaze::zelda3::SpriteAction Class Reference
#include <sprite_builder.h>
Public Member Functions
SpriteAction & AddInstruction (const SpriteInstruction &instruction)
SpriteAction & AddCustomInstruction (const std::string &asmCode)
SpriteAction & SetNextAction (const std::string &nextActionName)
std::string GetConfiguration () const
Static Public Member Functions
static SpriteAction Create (const std::string &actionName)
static SpriteAction Create ()
Private Attributes
std::string name
std::vector< std::string > instructions
std::string nextAction
Detailed Description
Definition at line 37 of file sprite_builder.h.
Member Function Documentation
Create() [1/2]
SpriteAction yaze::zelda3::SpriteAction::Create (const std::string & actionName) static
Definition at line 65 of file sprite_builder.cc.
Create() [2/2]
SpriteAction yaze::zelda3::SpriteAction::Create () static
Definition at line 71 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
AddInstruction()
SpriteAction & yaze::zelda3::SpriteAction::AddInstruction (const SpriteInstruction & instruction)
Definition at line 77 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
AddCustomInstruction()
SpriteAction & yaze::zelda3::SpriteAction::AddCustomInstruction (const std::string & asmCode)
Definition at line 82 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
SetNextAction()
SpriteAction & yaze::zelda3::SpriteAction::SetNextAction (const std::string & nextActionName)
Definition at line 86 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
GetConfiguration()
std::string yaze::zelda3::SpriteAction::GetConfiguration () const
Definition at line 90 of file sprite_builder.cc.
Member Data Documentation
name
std::string yaze::zelda3::SpriteAction::name private
Definition at line 58 of file sprite_builder.h.
instructions
std::vector<std::string> yaze::zelda3::SpriteAction::instructions private
Definition at line 59 of file sprite_builder.h.
nextAction
std::string yaze::zelda3::SpriteAction::nextAction private
Definition at line 60 of file sprite_builder.h.
The documentation for this class was generated from the following files:
src/app/zelda3/sprite/sprite_builder.h
src/app/zelda3/sprite/sprite_builder.cc