yaze: yaze::editor::OverworldEditorManager Class Reference
yaze::editor::OverworldEditorManager Class Reference
Manages the complex overworld editor functionality and v3 features.
#include <overworld_editor_manager.h>
Public Member Functions
OverworldEditorManager (zelda3::Overworld *overworld, Rom *rom, OverworldEditor *editor=nullptr)
void SetEditorContext (OverworldEditor *editor)
absl::Status DrawV3SettingsPanel ()
absl::Status DrawCustomOverworldSettings ()
absl::Status DrawAreaSpecificSettings ()
absl::Status DrawTransitionSettings ()
absl::Status DrawOverlaySettings ()
absl::Status DrawMapPropertiesTable ()
absl::Status DrawUnifiedSettingsTable ()
absl::Status DrawToolsetInSettings ()
absl::Status DrawAreaSizeControls ()
absl::Status DrawMosaicControls ()
absl::Status DrawPaletteControls ()
absl::Status DrawGfxGroupControls ()
absl::Status SaveCustomOverworldData ()
absl::Status LoadCustomOverworldData ()
absl::Status ApplyCustomOverworldASM ()
absl::Status HandleCanvasSelectionTransfer ()
absl::Status TransferOverworldSelectionToScratch ()
absl::Status TransferScratchSelectionToOverworld ()
bool ValidateV3Compatibility ()
bool CheckCustomASMApplied ()
uint8_t GetCustomASMVersion ()
auto enable_area_specific_bg () const
auto enable_main_palette () const
auto enable_mosaic () const
auto enable_gfx_groups () const
auto enable_subscreen_overlay () const
auto enable_animated_gfx () const
void set_enable_area_specific_bg (bool value)
void set_enable_main_palette (bool value)
void set_enable_mosaic (bool value)
void set_enable_gfx_groups (bool value)
void set_enable_subscreen_overlay (bool value)
void set_enable_animated_gfx (bool value)
Private Member Functions
absl::Status DrawBooleanSetting (const char *label, bool *setting, const char *help_text=nullptr)
absl::Status DrawColorPicker (const char *label, uint16_t *color)
absl::Status DrawOverlaySetting (const char *label, uint16_t *overlay)
absl::Status DrawGfxGroupSetting (const char *label, uint8_t *gfx_id, int max_value=255)
Private Attributes
zelda3::Overworld * overworld_
Rom * rom_
OverworldEditor * editor_
bool enable_area_specific_bg_ = false
bool enable_main_palette_ = false
bool enable_mosaic_ = false
bool enable_gfx_groups_ = false
bool enable_subscreen_overlay_ = false
bool enable_animated_gfx_ = false
int current_map_index_ = 0
Detailed Description
Manages the complex overworld editor functionality and v3 features.
This class separates the complex overworld editing functionality from the main OverworldEditor class to improve maintainability and organization, especially for ZSCustomOverworld v3 features.
Definition at line 27 of file overworld_editor_manager.h.
Constructor & Destructor Documentation
OverworldEditorManager()
yaze::editor::OverworldEditorManager::OverworldEditorManager (zelda3::Overworld * overworld, Rom * rom, OverworldEditor * editor = nullptr) inline
Definition at line 29 of file overworld_editor_manager.h.
Member Function Documentation
SetEditorContext()
void yaze::editor::OverworldEditorManager::SetEditorContext (OverworldEditor * editor) inline
Definition at line 34 of file overworld_editor_manager.h.
References editor_.
DrawV3SettingsPanel()
absl::Status yaze::editor::OverworldEditorManager::DrawV3SettingsPanel ()
Definition at line 14 of file overworld_editor_manager.cc.
References DrawAreaSpecificSettings(), DrawCustomOverworldSettings(), DrawOverlaySettings(), DrawTransitionSettings(), GetCustomASMVersion(), and RETURN_IF_ERROR.
DrawCustomOverworldSettings()
absl::Status yaze::editor::OverworldEditorManager::DrawCustomOverworldSettings ()
Definition at line 41 of file overworld_editor_manager.cc.
References ApplyCustomOverworldASM(), DrawBooleanSetting(), enable_animated_gfx_, enable_area_specific_bg_, enable_gfx_groups_, enable_main_palette_, enable_mosaic_, enable_subscreen_overlay_, HOVER_HINT, and RETURN_IF_ERROR.
Referenced by DrawV3SettingsPanel().
DrawAreaSpecificSettings()
absl::Status yaze::editor::OverworldEditorManager::DrawAreaSpecificSettings ()
Definition at line 80 of file overworld_editor_manager.cc.
References current_map_index_, DrawAreaSizeControls(), DrawColorPicker(), DrawGfxGroupControls(), DrawGfxGroupSetting(), DrawMosaicControls(), DrawOverlaySetting(), enable_animated_gfx_, enable_area_specific_bg_, enable_gfx_groups_, enable_main_palette_, enable_mosaic_, enable_subscreen_overlay_, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::mutable_overworld_map(), overworld_, and RETURN_IF_ERROR.
Referenced by DrawV3SettingsPanel().
DrawTransitionSettings()
absl::Status yaze::editor::OverworldEditorManager::DrawTransitionSettings ()
Definition at line 189 of file overworld_editor_manager.cc.
References GetCustomASMVersion().
Referenced by DrawV3SettingsPanel().
DrawOverlaySettings()
absl::Status yaze::editor::OverworldEditorManager::DrawOverlaySettings ()
Definition at line 205 of file overworld_editor_manager.cc.
References current_map_index_, yaze::zelda3::Overworld::mutable_overworld_map(), and overworld_.
Referenced by DrawV3SettingsPanel().
DrawMapPropertiesTable()
absl::Status yaze::editor::OverworldEditorManager::DrawMapPropertiesTable ()
DrawUnifiedSettingsTable()
absl::Status yaze::editor::OverworldEditorManager::DrawUnifiedSettingsTable ()
Definition at line 283 of file overworld_editor_manager.cc.
References DrawToolsetInSettings(), GetCustomASMVersion(), ICON_MD_BUILD, ICON_MD_EXTENSION, ICON_MD_IMAGE, ICON_MD_MAP, ICON_MD_NEW_RELEASES, ICON_MD_PALETTE, ICON_MD_PUBLIC, ICON_MD_SETTINGS, ICON_MD_TUNE, ICON_MD_UPGRADE, and RETURN_IF_ERROR.
DrawToolsetInSettings()
absl::Status yaze::editor::OverworldEditorManager::DrawToolsetInSettings ()
Definition at line 348 of file overworld_editor_manager.cc.
References HOVER_HINT, ICON_MD_ADD_LOCATION, ICON_MD_DOOR_BACK, ICON_MD_DOOR_FRONT, ICON_MD_DRAW, ICON_MD_GRASS, ICON_MD_MUSIC_NOTE, ICON_MD_PAN_TOOL_ALT, and ICON_MD_PEST_CONTROL_RODENT.
Referenced by DrawUnifiedSettingsTable().
DrawAreaSizeControls()
absl::Status yaze::editor::OverworldEditorManager::DrawAreaSizeControls ()
Definition at line 134 of file overworld_editor_manager.cc.
References current_map_index_, yaze::zelda3::Overworld::mutable_overworld_map(), and overworld_.
Referenced by DrawAreaSpecificSettings().
DrawMosaicControls()
absl::Status yaze::editor::OverworldEditorManager::DrawMosaicControls ()
Definition at line 147 of file overworld_editor_manager.cc.
References current_map_index_, yaze::zelda3::Overworld::mutable_overworld_map(), and overworld_.
Referenced by DrawAreaSpecificSettings().
DrawPaletteControls()
absl::Status yaze::editor::OverworldEditorManager::DrawPaletteControls ()
DrawGfxGroupControls()
absl::Status yaze::editor::OverworldEditorManager::DrawGfxGroupControls ()
Definition at line 174 of file overworld_editor_manager.cc.
References current_map_index_, DrawGfxGroupSetting(), yaze::zelda3::Overworld::mutable_overworld_map(), overworld_, and RETURN_IF_ERROR.
Referenced by DrawAreaSpecificSettings().
SaveCustomOverworldData()
absl::Status yaze::editor::OverworldEditorManager::SaveCustomOverworldData ()
LoadCustomOverworldData()
absl::Status yaze::editor::OverworldEditorManager::LoadCustomOverworldData ()
ApplyCustomOverworldASM()
absl::Status yaze::editor::OverworldEditorManager::ApplyCustomOverworldASM ()
Definition at line 224 of file overworld_editor_manager.cc.
References enable_animated_gfx_, enable_area_specific_bg_, enable_gfx_groups_, enable_main_palette_, enable_mosaic_, enable_subscreen_overlay_, overworld_, and yaze::zelda3::Overworld::SaveCustomOverworldASM().
Referenced by DrawCustomOverworldSettings().
HandleCanvasSelectionTransfer()
absl::Status yaze::editor::OverworldEditorManager::HandleCanvasSelectionTransfer ()
Definition at line 404 of file overworld_editor_manager.cc.
TransferOverworldSelectionToScratch()
absl::Status yaze::editor::OverworldEditorManager::TransferOverworldSelectionToScratch ()
Definition at line 410 of file overworld_editor_manager.cc.
TransferScratchSelectionToOverworld()
absl::Status yaze::editor::OverworldEditorManager::TransferScratchSelectionToOverworld ()
Definition at line 416 of file overworld_editor_manager.cc.
ValidateV3Compatibility()
bool yaze::editor::OverworldEditorManager::ValidateV3Compatibility ()
Definition at line 230 of file overworld_editor_manager.cc.
References GetCustomASMVersion().
CheckCustomASMApplied()
bool yaze::editor::OverworldEditorManager::CheckCustomASMApplied ()
Definition at line 235 of file overworld_editor_manager.cc.
References GetCustomASMVersion().
GetCustomASMVersion()
uint8_t yaze::editor::OverworldEditorManager::GetCustomASMVersion ()
Definition at line 240 of file overworld_editor_manager.cc.
References yaze::zelda3::OverworldCustomASMHasBeenApplied, and rom_.
Referenced by CheckCustomASMApplied(), DrawTransitionSettings(), DrawUnifiedSettingsTable(), DrawV3SettingsPanel(), and ValidateV3Compatibility().
enable_area_specific_bg()
auto yaze::editor::OverworldEditorManager::enable_area_specific_bg () const inline
Definition at line 68 of file overworld_editor_manager.h.
References enable_area_specific_bg_.
enable_main_palette()
auto yaze::editor::OverworldEditorManager::enable_main_palette () const inline
Definition at line 69 of file overworld_editor_manager.h.
References enable_main_palette_.
enable_mosaic()
auto yaze::editor::OverworldEditorManager::enable_mosaic () const inline
Definition at line 70 of file overworld_editor_manager.h.
References enable_mosaic_.
enable_gfx_groups()
auto yaze::editor::OverworldEditorManager::enable_gfx_groups () const inline
Definition at line 71 of file overworld_editor_manager.h.
References enable_gfx_groups_.
enable_subscreen_overlay()
auto yaze::editor::OverworldEditorManager::enable_subscreen_overlay () const inline
Definition at line 72 of file overworld_editor_manager.h.
References enable_subscreen_overlay_.
enable_animated_gfx()
auto yaze::editor::OverworldEditorManager::enable_animated_gfx () const inline
Definition at line 73 of file overworld_editor_manager.h.
References enable_animated_gfx_.
set_enable_area_specific_bg()
void yaze::editor::OverworldEditorManager::set_enable_area_specific_bg (bool value) inline
Definition at line 75 of file overworld_editor_manager.h.
References enable_area_specific_bg_.
set_enable_main_palette()
void yaze::editor::OverworldEditorManager::set_enable_main_palette (bool value) inline
Definition at line 76 of file overworld_editor_manager.h.
References enable_main_palette_.
set_enable_mosaic()
void yaze::editor::OverworldEditorManager::set_enable_mosaic (bool value) inline
Definition at line 77 of file overworld_editor_manager.h.
References enable_mosaic_.
set_enable_gfx_groups()
void yaze::editor::OverworldEditorManager::set_enable_gfx_groups (bool value) inline
Definition at line 78 of file overworld_editor_manager.h.
References enable_gfx_groups_.
set_enable_subscreen_overlay()
void yaze::editor::OverworldEditorManager::set_enable_subscreen_overlay (bool value) inline
Definition at line 79 of file overworld_editor_manager.h.
References enable_subscreen_overlay_.
set_enable_animated_gfx()
void yaze::editor::OverworldEditorManager::set_enable_animated_gfx (bool value) inline
Definition at line 80 of file overworld_editor_manager.h.
References enable_animated_gfx_.
DrawBooleanSetting()
absl::Status yaze::editor::OverworldEditorManager::DrawBooleanSetting (const char * label, bool * setting, const char * help_text = nullptr) private
Definition at line 244 of file overworld_editor_manager.cc.
Referenced by DrawCustomOverworldSettings().
DrawColorPicker()
absl::Status yaze::editor::OverworldEditorManager::DrawColorPicker (const char * label, uint16_t * color) private
Definition at line 253 of file overworld_editor_manager.cc.
References yaze::gfx::SnesColor::set_rgb(), and yaze::gfx::SnesColor::snes().
Referenced by DrawAreaSpecificSettings().
DrawOverlaySetting()
absl::Status yaze::editor::OverworldEditorManager::DrawOverlaySetting (const char * label, uint16_t * overlay) private
Definition at line 266 of file overworld_editor_manager.cc.
Referenced by DrawAreaSpecificSettings().
DrawGfxGroupSetting()
absl::Status yaze::editor::OverworldEditorManager::DrawGfxGroupSetting (const char * label, uint8_t * gfx_id, int max_value = 255) private
Definition at line 274 of file overworld_editor_manager.cc.
Referenced by DrawAreaSpecificSettings(), and DrawGfxGroupControls().
Member Data Documentation
overworld_
zelda3::Overworld* yaze::editor::OverworldEditorManager::overworld_ private
Definition at line 83 of file overworld_editor_manager.h.
Referenced by ApplyCustomOverworldASM(), DrawAreaSizeControls(), DrawAreaSpecificSettings(), DrawGfxGroupControls(), DrawMosaicControls(), and DrawOverlaySettings().
rom_
Rom* yaze::editor::OverworldEditorManager::rom_ private
Definition at line 84 of file overworld_editor_manager.h.
Referenced by GetCustomASMVersion().
editor_
OverworldEditor* yaze::editor::OverworldEditorManager::editor_ private
Definition at line 85 of file overworld_editor_manager.h.
Referenced by SetEditorContext().
enable_area_specific_bg_
bool yaze::editor::OverworldEditorManager::enable_area_specific_bg_ = false private
Definition at line 88 of file overworld_editor_manager.h.
Referenced by ApplyCustomOverworldASM(), DrawAreaSpecificSettings(), DrawCustomOverworldSettings(), enable_area_specific_bg(), and set_enable_area_specific_bg().
enable_main_palette_
bool yaze::editor::OverworldEditorManager::enable_main_palette_ = false private
Definition at line 89 of file overworld_editor_manager.h.
Referenced by ApplyCustomOverworldASM(), DrawAreaSpecificSettings(), DrawCustomOverworldSettings(), enable_main_palette(), and set_enable_main_palette().
enable_mosaic_
bool yaze::editor::OverworldEditorManager::enable_mosaic_ = false private
Definition at line 90 of file overworld_editor_manager.h.
Referenced by ApplyCustomOverworldASM(), DrawAreaSpecificSettings(), DrawCustomOverworldSettings(), enable_mosaic(), and set_enable_mosaic().
enable_gfx_groups_
bool yaze::editor::OverworldEditorManager::enable_gfx_groups_ = false private
Definition at line 91 of file overworld_editor_manager.h.
Referenced by ApplyCustomOverworldASM(), DrawAreaSpecificSettings(), DrawCustomOverworldSettings(), enable_gfx_groups(), and set_enable_gfx_groups().
enable_subscreen_overlay_
bool yaze::editor::OverworldEditorManager::enable_subscreen_overlay_ = false private
Definition at line 92 of file overworld_editor_manager.h.
Referenced by ApplyCustomOverworldASM(), DrawAreaSpecificSettings(), DrawCustomOverworldSettings(), enable_subscreen_overlay(), and set_enable_subscreen_overlay().
enable_animated_gfx_
bool yaze::editor::OverworldEditorManager::enable_animated_gfx_ = false private
Definition at line 93 of file overworld_editor_manager.h.
Referenced by ApplyCustomOverworldASM(), DrawAreaSpecificSettings(), DrawCustomOverworldSettings(), enable_animated_gfx(), and set_enable_animated_gfx().
current_map_index_
int yaze::editor::OverworldEditorManager::current_map_index_ = 0 private
Definition at line 96 of file overworld_editor_manager.h.
Referenced by DrawAreaSizeControls(), DrawAreaSpecificSettings(), DrawGfxGroupControls(), DrawMosaicControls(), and DrawOverlaySettings().
The documentation for this class was generated from the following files:
src/app/editor/overworld/overworld_editor_manager.h
src/app/editor/overworld/overworld_editor_manager.cc