yaze: yaze::core::NotifyValue< T > Class Template Reference
yaze::core::NotifyValue< T > Class Template Reference
A class to manage a value that can be modified and notify when it changes.
#include <common.h>
Public Member Functions
NotifyValue ()
NotifyValue (const T &value)
void set (const T &value)
const T & get ()
T & mutable_get ()
void apply_changes ()
void operator= (const T &value)
operator T ()
bool modified () const
Private Attributes
T value_
bool modified_
T temp_value_
Detailed Description
template<typename T>
class yaze::core::NotifyValue< T >
A class to manage a value that can be modified and notify when it changes.
Definition at line 166 of file common.h.
Constructor & Destructor Documentation
NotifyValue() [1/2]
template<typename T > yaze::core::NotifyValue< T >::NotifyValue () inline
Definition at line 168 of file common.h.
NotifyValue() [2/2]
template<typename T > yaze::core::NotifyValue< T >::NotifyValue (const T & value) inline
Definition at line 169 of file common.h.
Member Function Documentation
set()
template<typename T > void yaze::core::NotifyValue< T >::set (const T & value) inline
Definition at line 172 of file common.h.
References yaze::core::NotifyValue< T >::modified_, and yaze::core::NotifyValue< T >::value_.
Referenced by yaze::core::NotifyValue< T >::operator=().
get()
template<typename T > const T & yaze::core::NotifyValue< T >::get () inline
Definition at line 177 of file common.h.
References yaze::core::NotifyValue< T >::modified_, and yaze::core::NotifyValue< T >::value_.
Referenced by yaze::editor::Tile16Editor::DrawTileEditControls(), yaze::core::NotifyValue< T >::operator T(), and yaze::editor::Tile16Editor::UpdateBlockset().
mutable_get()
template<typename T > T & yaze::core::NotifyValue< T >::mutable_get () inline
Definition at line 182 of file common.h.
References yaze::core::NotifyValue< T >::modified_, yaze::core::NotifyValue< T >::temp_value_, and yaze::core::NotifyValue< T >::value_.
Referenced by yaze::editor::Tile16Editor::DrawTileEditControls(), and yaze::editor::Tile16Editor::UpdateBlockset().
apply_changes()
template<typename T > void yaze::core::NotifyValue< T >::apply_changes () inline
Definition at line 188 of file common.h.
References yaze::core::NotifyValue< T >::modified_, yaze::core::NotifyValue< T >::temp_value_, and yaze::core::NotifyValue< T >::value_.
Referenced by yaze::editor::Tile16Editor::DrawTileEditControls(), and yaze::editor::Tile16Editor::UpdateBlockset().
operator=()
template<typename T > void yaze::core::NotifyValue< T >::operator= (const T & value) inline
Definition at line 195 of file common.h.
References yaze::core::NotifyValue< T >::set().
operator T()
template<typename T > yaze::core::NotifyValue< T >::operator T () inline
Definition at line 196 of file common.h.
References yaze::core::NotifyValue< T >::get().
modified()
template<typename T > bool yaze::core::NotifyValue< T >::modified () const inline
Definition at line 198 of file common.h.
References yaze::core::NotifyValue< T >::modified_.
Referenced by yaze::editor::Tile16Editor::DrawTileEditControls(), and yaze::editor::Tile16Editor::UpdateBlockset().
Member Data Documentation
value_
template<typename T > T yaze::core::NotifyValue< T >::value_ private
Definition at line 201 of file common.h.
Referenced by yaze::core::NotifyValue< T >::apply_changes(), yaze::core::NotifyValue< T >::get(), yaze::core::NotifyValue< T >::mutable_get(), and yaze::core::NotifyValue< T >::set().
modified_
template<typename T > bool yaze::core::NotifyValue< T >::modified_ private
Definition at line 202 of file common.h.
Referenced by yaze::core::NotifyValue< T >::apply_changes(), yaze::core::NotifyValue< T >::get(), yaze::core::NotifyValue< T >::modified(), yaze::core::NotifyValue< T >::mutable_get(), and yaze::core::NotifyValue< T >::set().
temp_value_
template<typename T > T yaze::core::NotifyValue< T >::temp_value_ private
Definition at line 203 of file common.h.
Referenced by yaze::core::NotifyValue< T >::apply_changes(), and yaze::core::NotifyValue< T >::mutable_get().
The documentation for this class was generated from the following file:
src/app/core/common.h