yaze: yaze::test::PerformanceTestSuite Class Reference
yaze::test::PerformanceTestSuite Class Reference
#include <integrated_test_suite.h>
Public Member Functions
PerformanceTestSuite ()=default
~PerformanceTestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Private Member Functions
void RunFrameRateTest (TestResults &results)
void RunMemoryUsageTest (TestResults &results)
void RunResourceLeakTest (TestResults &results)
Private Attributes
bool test_arena_ = true
bool test_rom_ = true
bool test_graphics_ = true
int sample_duration_secs_ = 5
float target_fps_ = 30.0f
int max_memory_mb_ = 100
char test_rom_path_ [256] = "zelda3.sfc"
bool skip_missing_rom_ = true
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
Definition at line 259 of file integrated_test_suite.h.
Constructor & Destructor Documentation
PerformanceTestSuite()
yaze::test::PerformanceTestSuite::PerformanceTestSuite () default
~PerformanceTestSuite()
yaze::test::PerformanceTestSuite::~PerformanceTestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::PerformanceTestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 264 of file integrated_test_suite.h.
Referenced by RunFrameRateTest(), RunMemoryUsageTest(), and RunResourceLeakTest().
GetCategory()
TestCategory yaze::test::PerformanceTestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 265 of file integrated_test_suite.h.
References yaze::test::kPerformance.
Referenced by RunFrameRateTest(), RunMemoryUsageTest(), and RunResourceLeakTest().
RunTests()
absl::Status yaze::test::PerformanceTestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 267 of file integrated_test_suite.h.
References RunFrameRateTest(), RunMemoryUsageTest(), and RunResourceLeakTest().
DrawConfiguration()
void yaze::test::PerformanceTestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 275 of file integrated_test_suite.h.
References max_memory_mb_, sample_duration_secs_, and target_fps_.
RunFrameRateTest()
void yaze::test::PerformanceTestSuite::RunFrameRateTest (TestResults & results) inline private
Definition at line 283 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, target_fps_, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunMemoryUsageTest()
void yaze::test::PerformanceTestSuite::RunMemoryUsageTest (TestResults & results) inline private
Definition at line 320 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, max_memory_mb_, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunResourceLeakTest()
void yaze::test::PerformanceTestSuite::RunResourceLeakTest (TestResults & results) inline private
Definition at line 364 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
Member Data Documentation
test_arena_
bool yaze::test::PerformanceTestSuite::test_arena_ = true private
Definition at line 420 of file integrated_test_suite.h.
test_rom_
bool yaze::test::PerformanceTestSuite::test_rom_ = true private
Definition at line 421 of file integrated_test_suite.h.
test_graphics_
bool yaze::test::PerformanceTestSuite::test_graphics_ = true private
Definition at line 422 of file integrated_test_suite.h.
sample_duration_secs_
int yaze::test::PerformanceTestSuite::sample_duration_secs_ = 5 private
Definition at line 423 of file integrated_test_suite.h.
Referenced by DrawConfiguration().
target_fps_
float yaze::test::PerformanceTestSuite::target_fps_ = 30.0f private
Definition at line 424 of file integrated_test_suite.h.
Referenced by DrawConfiguration(), and RunFrameRateTest().
max_memory_mb_
int yaze::test::PerformanceTestSuite::max_memory_mb_ = 100 private
Definition at line 425 of file integrated_test_suite.h.
Referenced by DrawConfiguration(), and RunMemoryUsageTest().
test_rom_path_
char yaze::test::PerformanceTestSuite::test_rom_path_[256] = "zelda3.sfc" private
Definition at line 426 of file integrated_test_suite.h.
skip_missing_rom_
bool yaze::test::PerformanceTestSuite::skip_missing_rom_ = true private
Definition at line 427 of file integrated_test_suite.h.
The documentation for this class was generated from the following file:
src/app/test/integrated_test_suite.h