yaze: yaze::app::editor::MasterEditor Class Reference
yaze::app::editor::MasterEditor Class Reference
The MasterEditor class represents the main editor for a Rom in the Yaze application.
#include <master_editor.h>
Public Member Functions
MasterEditor ()
void SetupScreen (std::string filename="")
absl::Status Update ()
auto emulator () -> emu::Emulator &
auto quit ()
auto overworld_editor () -> OverworldEditor &
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
Private Member Functions
void ManageActiveEditors ()
void ManageKeyboardShortcuts ()
void OpenRomOrProject (const std::string &filename)
void DrawFileDialog ()
void DrawStatusPopup ()
void DrawAboutPopup ()
void DrawInfoPopup ()
void DrawYazeMenu ()
void DrawFileMenu ()
void DrawEditMenu ()
void DrawViewMenu ()
void DrawTestMenu ()
void DrawProjectMenu ()
void DrawHelpMenu ()
void LoadRom ()
void SaveRom ()
absl::Status OpenProject ()
Private Attributes
bool quit_ = false
bool about_ = false
bool rom_info_ = false
bool backup_rom_ = false
bool save_new_auto_ = true
bool show_status_ = false
bool rom_assets_loaded_ = false
absl::Status status_
absl::Status prev_status_
emu::Emulator emulator_
Project current_project_
AssemblyEditor assembly_editor_
DungeonEditor dungeon_editor_
GraphicsEditor graphics_editor_
MusicEditor music_editor_
OverworldEditor overworld_editor_
PaletteEditor palette_editor_
ScreenEditor screen_editor_
SpriteEditor sprite_editor_
SettingsEditor settings_editor_
MessageEditor message_editor_
MemoryEditorWithDiffChecker memory_editor_
ImVector< int > active_tabs_
std::vector< Editor * > active_editors_
Editor * current_editor_ = nullptr
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Static Protected Attributes inherited from yaze::app::editor::context::GfxContext
static std::unordered_map< uint8_t, gfx::Paletteset > palettesets_
Detailed Description
The MasterEditor class represents the main editor for a Rom in the Yaze application.
This class inherits from SharedRom, GfxContext, and ExperimentFlags, and provides functionality for setting up the screen, updating the editor, and shutting down the editor. It also includes methods for drawing various menus and popups, saving the Rom, and managing editor-specific flags.
The MasterEditor class contains instances of various editor classes such as AssemblyEditor, DungeonEditor, GraphicsEditor, MusicEditor, OverworldEditor, PaletteEditor, ScreenEditor, and SpriteEditor. The current_editor_ member variable points to the currently active editor in the tab view.
Note
This class assumes the presence of an SDL_Renderer object for rendering graphics.
Definition at line 57 of file master_editor.h.
Constructor & Destructor Documentation
MasterEditor()
yaze::app::editor::MasterEditor::MasterEditor () inline
Definition at line 61 of file master_editor.h.
References active_editors_, current_editor_, dungeon_editor_, graphics_editor_, message_editor_, overworld_editor_, palette_editor_, and sprite_editor_.
Member Function Documentation
SetupScreen()
void yaze::app::editor::MasterEditor::SetupScreen (std::string filename = "")
Definition at line 61 of file master_editor.cc.
References yaze::app::editor::OverworldEditor::InitializeZeml(), overworld_editor_, PRINT_IF_ERROR, and yaze::app::SharedRom::rom().
Referenced by yaze::app::core::Controller::OnEntry(), and yaze::app::core::Controller::SetupScreen().
Update()
absl::Status yaze::app::editor::MasterEditor::Update ()
Definition at line 68 of file master_editor.cc.
References DrawAboutPopup(), DrawFileDialog(), DrawInfoPopup(), DrawStatusPopup(), DrawYazeMenu(), yaze::app::editor::OverworldEditor::LoadGraphics(), ManageActiveEditors(), ManageKeyboardShortcuts(), overworld_editor_, RETURN_IF_ERROR, yaze::app::SharedRom::rom(), and rom_assets_loaded_.
Referenced by yaze::app::core::Controller::OnLoad().
emulator()
auto yaze::app::editor::MasterEditor::emulator () -> emu::Emulator& inline
Definition at line 74 of file master_editor.h.
References emulator_.
Referenced by yaze::app::core::anonymous_namespace{controller.cc}::HandleKeyDown(), yaze::app::core::anonymous_namespace{controller.cc}::HandleKeyUp(), yaze::app::core::Controller::LoadAudioDevice(), and yaze::app::core::Controller::OnEntry().
quit()
auto yaze::app::editor::MasterEditor::quit () inline
Definition at line 75 of file master_editor.h.
References quit_.
Referenced by yaze::app::core::Controller::OnLoad().
overworld_editor()
auto yaze::app::editor::MasterEditor::overworld_editor () -> OverworldEditor& inline
Definition at line 76 of file master_editor.h.
References overworld_editor_.
ManageActiveEditors()
void yaze::app::editor::MasterEditor::ManageActiveEditors () private
Definition at line 90 of file master_editor.cc.
References active_editors_, yaze::app::editor::DungeonEditor::add_room(), assembly_editor_, current_editor_, dungeon_editor_, graphics_editor_, ICON_MD_ADD, yaze::app::editor::OverworldEditor::jump_to_tab(), yaze::app::editor::OverworldEditor::jump_to_tab_, yaze::app::editor::kAssembly, yaze::app::editor::kDungeon, yaze::app::editor::kGraphics, yaze::app::editor::kMessage, yaze::app::editor::kMusic, yaze::app::editor::kOverworld, yaze::app::editor::kPalette, yaze::app::editor::kScreen, yaze::app::editor::kSettings, yaze::app::editor::kSprite, message_editor_, music_editor_, overworld_editor_, palette_editor_, screen_editor_, settings_editor_, sprite_editor_, status_, yaze::app::editor::DungeonEditor::Update(), yaze::app::editor::GraphicsEditor::Update(), yaze::app::editor::MessageEditor::Update(), yaze::app::editor::MusicEditor::Update(), yaze::app::editor::OverworldEditor::Update(), yaze::app::editor::PaletteEditor::Update(), yaze::app::editor::ScreenEditor::Update(), yaze::app::editor::SettingsEditor::Update(), yaze::app::editor::SpriteEditor::Update(), and yaze::app::editor::AssemblyEditor::UpdateCodeView().
Referenced by Update().
ManageKeyboardShortcuts()
void yaze::app::editor::MasterEditor::ManageKeyboardShortcuts () private
Definition at line 253 of file master_editor.cc.
References about_, yaze::app::editor::Editor::Copy(), current_editor_, yaze::app::editor::Editor::Cut(), yaze::app::editor::Editor::Find(), yaze::app::editor::RecentFilesManager::GetRecentFiles(), yaze::app::editor::RecentFilesManager::Load(), LoadRom(), OpenRomOrProject(), yaze::app::editor::Editor::Paste(), quit_, yaze::app::editor::Editor::Redo(), SaveRom(), status_, and yaze::app::editor::Editor::Undo().
Referenced by Update().
OpenRomOrProject()
void yaze::app::editor::MasterEditor::OpenRomOrProject (const std::string & filename) private
Definition at line 433 of file master_editor.cc.
References current_project_, yaze::app::Project::Open(), OpenProject(), yaze::app::SharedRom::rom(), and status_.
Referenced by DrawFileMenu(), and ManageKeyboardShortcuts().
DrawFileDialog()
void yaze::app::editor::MasterEditor::DrawFileDialog () private
Definition at line 311 of file master_editor.cc.
References yaze::app::editor::RecentFilesManager::AddFile(), yaze::app::gui::FileDialogPipeline(), yaze::app::editor::RecentFilesManager::Load(), yaze::app::SharedRom::rom(), yaze::app::editor::RecentFilesManager::Save(), and status_.
Referenced by Update().
DrawStatusPopup()
void yaze::app::editor::MasterEditor::DrawStatusPopup () private
Definition at line 328 of file master_editor.cc.
References ICON_MD_CONTENT_COPY, ICON_MD_ERROR, yaze::app::gui::kDefaultModalSize, prev_status_, show_status_, and status_.
Referenced by Update().
DrawAboutPopup()
void yaze::app::editor::MasterEditor::DrawAboutPopup () private
Definition at line 356 of file master_editor.cc.
References about_, yaze::app::gui::kDefaultModalSize, and yaze::app::core::kYazeVersion.
Referenced by Update().
DrawInfoPopup()
void yaze::app::editor::MasterEditor::DrawInfoPopup () private
Definition at line 373 of file master_editor.cc.
References yaze::app::gui::kDefaultModalSize, yaze::app::SharedRom::rom(), and rom_info_.
Referenced by Update().
DrawYazeMenu()
void yaze::app::editor::MasterEditor::DrawYazeMenu () private
Definition at line 389 of file master_editor.cc.
References yaze::app::gui::DrawDisplaySettings(), DrawEditMenu(), DrawFileMenu(), DrawHelpMenu(), DrawProjectMenu(), DrawTestMenu(), DrawViewMenu(), ICON_MD_DISPLAY_SETTINGS, ICON_MD_TERMINAL, and yaze::app::core::kYazeVersion.
Referenced by Update().
DrawFileMenu()
void yaze::app::editor::MasterEditor::DrawFileMenu () private
Definition at line 444 of file master_editor.cc.
References backup_rom_, yaze::app::Project::code_folder_, yaze::app::Project::Create(), current_project_, yaze::app::editor::FlagsMenu::Draw(), yaze::app::Project::filepath, yaze::app::editor::RecentFilesManager::GetRecentFiles(), yaze::app::gui::kDefaultModalSize, yaze::app::Project::labels_filename_, yaze::app::editor::RecentFilesManager::Load(), LoadRom(), MENU_ITEM, MENU_ITEM2, yaze::app::Project::Open(), OpenProject(), OpenRomOrProject(), quit_, yaze::app::SharedRom::rom(), rom_assets_loaded_, yaze::app::Project::rom_filename_, yaze::app::Project::Save(), save_new_auto_, SaveRom(), and status_.
Referenced by DrawYazeMenu().
DrawEditMenu()
void yaze::app::editor::MasterEditor::DrawEditMenu () private
Definition at line 583 of file master_editor.cc.
References yaze::app::editor::Editor::Copy(), current_editor_, yaze::app::editor::Editor::Cut(), MENU_ITEM2, yaze::app::editor::Editor::Paste(), yaze::app::editor::Editor::Redo(), status_, and yaze::app::editor::Editor::Undo().
Referenced by DrawYazeMenu().
DrawViewMenu()
void yaze::app::editor::MasterEditor::DrawViewMenu () private
Definition at line 597 of file master_editor.cc.
References assembly_editor_, emulator_, memory_editor_, MENU_ITEM, palette_editor_, rom_info_, yaze::app::emu::Emulator::Run(), status_, yaze::app::editor::AssemblyEditor::Update(), yaze::app::editor::MemoryEditorWithDiffChecker::Update(), and yaze::app::editor::PaletteEditor::Update().
Referenced by DrawYazeMenu().
DrawTestMenu()
void yaze::app::editor::MasterEditor::DrawTestMenu () private
Definition at line 648 of file master_editor.cc.
Referenced by DrawYazeMenu().
DrawProjectMenu()
void yaze::app::editor::MasterEditor::DrawProjectMenu () private
Definition at line 657 of file master_editor.cc.
References yaze::app::Project::code_folder_, current_project_, yaze::app::Project::labels_filename_, yaze::app::Project::name, yaze::app::Project::project_opened_, yaze::app::SharedRom::rom(), and yaze::app::Project::rom_filename_.
Referenced by DrawYazeMenu().
DrawHelpMenu()
void yaze::app::editor::MasterEditor::DrawHelpMenu () private
Definition at line 681 of file master_editor.cc.
References about_, and yaze::app::gui::kDefaultModalSize.
Referenced by DrawYazeMenu().
LoadRom()
void yaze::app::editor::MasterEditor::LoadRom () private
Definition at line 765 of file master_editor.cc.
References yaze::app::editor::RecentFilesManager::AddFile(), yaze::app::core::ExperimentFlags::flags(), yaze::app::editor::RecentFilesManager::Load(), PRINT_IF_ERROR, yaze::app::SharedRom::rom(), and yaze::app::editor::RecentFilesManager::Save().
Referenced by DrawFileMenu(), and ManageKeyboardShortcuts().
SaveRom()
void yaze::app::editor::MasterEditor::SaveRom () private
Definition at line 779 of file master_editor.cc.
References backup_rom_, yaze::app::core::ExperimentFlags::flags(), yaze::app::editor::OverworldEditor::overworld(), overworld_editor_, RETURN_VOID_IF_ERROR, yaze::app::SharedRom::rom(), save_new_auto_, yaze::app::editor::ScreenEditor::SaveDungeonMaps(), screen_editor_, and status_.
Referenced by DrawFileMenu(), and ManageKeyboardShortcuts().
OpenProject()
absl::Status yaze::app::editor::MasterEditor::OpenProject () private
Definition at line 814 of file master_editor.cc.
References yaze::app::editor::RecentFilesManager::AddFile(), assembly_editor_, yaze::app::Project::code_folder_, current_project_, yaze::app::Project::filepath, yaze::app::Project::labels_filename_, yaze::app::editor::RecentFilesManager::Load(), yaze::app::Project::name, yaze::app::editor::AssemblyEditor::OpenFolder(), yaze::app::Project::project_opened_, RETURN_IF_ERROR, yaze::app::SharedRom::rom(), yaze::app::Project::rom_filename_, and yaze::app::editor::RecentFilesManager::Save().
Referenced by DrawFileMenu(), and OpenRomOrProject().
Member Data Documentation
quit_
bool yaze::app::editor::MasterEditor::quit_ = false private
Definition at line 101 of file master_editor.h.
Referenced by DrawFileMenu(), ManageKeyboardShortcuts(), and quit().
about_
bool yaze::app::editor::MasterEditor::about_ = false private
Definition at line 102 of file master_editor.h.
Referenced by DrawAboutPopup(), DrawHelpMenu(), and ManageKeyboardShortcuts().
rom_info_
bool yaze::app::editor::MasterEditor::rom_info_ = false private
Definition at line 103 of file master_editor.h.
Referenced by DrawInfoPopup(), and DrawViewMenu().
backup_rom_
bool yaze::app::editor::MasterEditor::backup_rom_ = false private
Definition at line 104 of file master_editor.h.
Referenced by DrawFileMenu(), and SaveRom().
save_new_auto_
bool yaze::app::editor::MasterEditor::save_new_auto_ = true private
Definition at line 105 of file master_editor.h.
Referenced by DrawFileMenu(), and SaveRom().
show_status_
bool yaze::app::editor::MasterEditor::show_status_ = false private
Definition at line 106 of file master_editor.h.
Referenced by DrawStatusPopup().
rom_assets_loaded_
bool yaze::app::editor::MasterEditor::rom_assets_loaded_ = false private
Definition at line 107 of file master_editor.h.
Referenced by DrawFileMenu(), and Update().
status_
absl::Status yaze::app::editor::MasterEditor::status_ private
Definition at line 109 of file master_editor.h.
Referenced by DrawEditMenu(), DrawFileDialog(), DrawFileMenu(), DrawStatusPopup(), DrawViewMenu(), ManageActiveEditors(), ManageKeyboardShortcuts(), OpenRomOrProject(), and SaveRom().
prev_status_
absl::Status yaze::app::editor::MasterEditor::prev_status_ private
Definition at line 110 of file master_editor.h.
Referenced by DrawStatusPopup().
emulator_
emu::Emulator yaze::app::editor::MasterEditor::emulator_ private
Definition at line 112 of file master_editor.h.
Referenced by DrawViewMenu(), and emulator().
current_project_
Project yaze::app::editor::MasterEditor::current_project_ private
Definition at line 114 of file master_editor.h.
Referenced by DrawFileMenu(), DrawProjectMenu(), OpenProject(), and OpenRomOrProject().
assembly_editor_
AssemblyEditor yaze::app::editor::MasterEditor::assembly_editor_ private
Definition at line 116 of file master_editor.h.
Referenced by DrawViewMenu(), ManageActiveEditors(), and OpenProject().
dungeon_editor_
DungeonEditor yaze::app::editor::MasterEditor::dungeon_editor_ private
Definition at line 117 of file master_editor.h.
Referenced by ManageActiveEditors(), and MasterEditor().
graphics_editor_
GraphicsEditor yaze::app::editor::MasterEditor::graphics_editor_ private
Definition at line 118 of file master_editor.h.
Referenced by ManageActiveEditors(), and MasterEditor().
music_editor_
MusicEditor yaze::app::editor::MasterEditor::music_editor_ private
Definition at line 119 of file master_editor.h.
Referenced by ManageActiveEditors().
overworld_editor_
OverworldEditor yaze::app::editor::MasterEditor::overworld_editor_ private
Definition at line 120 of file master_editor.h.
Referenced by ManageActiveEditors(), MasterEditor(), overworld_editor(), SaveRom(), SetupScreen(), and Update().
palette_editor_
PaletteEditor yaze::app::editor::MasterEditor::palette_editor_ private
Definition at line 121 of file master_editor.h.
Referenced by DrawViewMenu(), ManageActiveEditors(), and MasterEditor().
screen_editor_
ScreenEditor yaze::app::editor::MasterEditor::screen_editor_ private
Definition at line 122 of file master_editor.h.
Referenced by ManageActiveEditors(), and SaveRom().
sprite_editor_
SpriteEditor yaze::app::editor::MasterEditor::sprite_editor_ private
Definition at line 123 of file master_editor.h.
Referenced by ManageActiveEditors(), and MasterEditor().
settings_editor_
SettingsEditor yaze::app::editor::MasterEditor::settings_editor_ private
Definition at line 124 of file master_editor.h.
Referenced by ManageActiveEditors().
message_editor_
MessageEditor yaze::app::editor::MasterEditor::message_editor_ private
Definition at line 125 of file master_editor.h.
Referenced by ManageActiveEditors(), and MasterEditor().
memory_editor_
MemoryEditorWithDiffChecker yaze::app::editor::MasterEditor::memory_editor_ private
Definition at line 126 of file master_editor.h.
Referenced by DrawViewMenu().
active_tabs_
ImVector<int> yaze::app::editor::MasterEditor::active_tabs_ private
Definition at line 128 of file master_editor.h.
active_editors_
std::vector<Editor*> yaze::app::editor::MasterEditor::active_editors_ private
Definition at line 129 of file master_editor.h.
Referenced by ManageActiveEditors(), and MasterEditor().
current_editor_
Editor* yaze::app::editor::MasterEditor::current_editor_ = nullptr private
Definition at line 130 of file master_editor.h.
Referenced by DrawEditMenu(), ManageActiveEditors(), ManageKeyboardShortcuts(), and MasterEditor().
The documentation for this class was generated from the following files:
src/app/editor/master_editor.h
src/app/editor/master_editor.cc