yaze: yaze::zelda3::Subtype2 Class Reference
yaze::zelda3::Subtype2 Class Reference
#include <room_object.h>
Public Member Functions
Subtype2 (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer)
void Draw (std::vector< uint8_t > &current_gfx16, std::vector< uint8_t > &tiles_bg1_buffer, std::vector< uint8_t > &tiles_bg2_buffer)
Public Member Functions inherited from yaze::zelda3::RoomObject
RoomObject (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer=0)
void set_rom (Rom *rom)
auto rom ()
auto mutable_rom ()
void EnsureTilesLoaded ()
absl::Status LoadTilesWithParser ()
const std::vector< gfx::Tile16 > & tiles () const
std::vector< gfx::Tile16 > & mutable_tiles ()
absl::StatusOr< std::span< const gfx::Tile16 > > GetTiles () const
absl::StatusOr< const gfx::Tile16 * > GetTile (int index) const
int GetTileCount () const
void AddTiles (int nbr, int pos)
void DrawTile (gfx::Tile16 t, int xx, int yy, std::vector< uint8_t > &current_gfx16, std::vector< uint8_t > &tiles_bg1_buffer, std::vector< uint8_t > &tiles_bg2_buffer, uint16_t tile_under=0xFFFF)
auto options () const
void set_options (ObjectOption options)
Public Attributes
std::string name
bool all_bgs
Sorting sort
Public Attributes inherited from yaze::zelda3::RoomObject
bool all_bgs_ = false
bool lit_ = false
int16_t id_
uint8_t x_
uint8_t y_
uint8_t size_
uint8_t nx_
uint8_t ny_
uint8_t ox_
uint8_t oy_
uint8_t z_ = 0
uint8_t previous_size_ = 0
uint8_t size_x_bits_ = 0
uint8_t size_y_bits_ = 0
int width_
int height_
int offset_x_ = 0
int offset_y_ = 0
std::string name_
std::vector< uint8_t > preview_object_data_
std::vector< gfx::Tile16 > tiles_
bool tiles_loaded_ = false
int tile_count_ = 0
int tile_data_ptr_ = -1
LayerType layer_
ObjectOption options_ = ObjectOption::Nothing
Rom * rom_
Additional Inherited Members
Public Types inherited from yaze::zelda3::RoomObject
enum LayerType { BG1 = 0 , BG2 = 1 , BG3 = 2 }
Detailed Description
Definition at line 195 of file room_object.h.
Constructor & Destructor Documentation
Subtype2()
yaze::zelda3::Subtype2::Subtype2 (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer) inline
Definition at line 201 of file room_object.h.
References yaze::zelda3::RoomObject::AddTiles(), yaze::zelda3::Horizontal, yaze::zelda3::kRoomObjectSubtype2, yaze::zelda3::kRoomObjectTileAddress, yaze::zelda3::RoomObject::rom(), yaze::zelda3::RoomObject::RoomObject(), sort, and yaze::zelda3::Wall.
Member Function Documentation
Draw()
void yaze::zelda3::Subtype2::Draw (std::vector< uint8_t > & current_gfx16, std::vector< uint8_t > & tiles_bg1_buffer, std::vector< uint8_t > & tiles_bg2_buffer) inline
Definition at line 212 of file room_object.h.
References yaze::zelda3::RoomObject::DrawTile(), yaze::zelda3::RoomObject::tiles_, yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Member Data Documentation
name
std::string yaze::zelda3::Subtype2::name
Definition at line 197 of file room_object.h.
all_bgs
bool yaze::zelda3::Subtype2::all_bgs
Definition at line 198 of file room_object.h.
sort
Sorting yaze::zelda3::Subtype2::sort
Definition at line 199 of file room_object.h.
Referenced by Subtype2().
The documentation for this class was generated from the following file:
src/app/zelda3/dungeon/room_object.h