yaze: yaze::emu::Cpu Class Reference
yaze::emu::Cpu Class Reference
#include <cpu.h>
Public Types
enum class AccessType { Control , Data }
Public Member Functions
Cpu (Memory &mem, Clock &vclock, CpuCallbacks &callbacks)
void Reset (bool hard=false)
void RunOpcode ()
void ExecuteInstruction (uint8_t opcode)
void LogInstructions (uint16_t PC, uint8_t opcode, uint16_t operand, bool immediate, bool accumulator_mode)
void UpdatePC (uint8_t instruction_length)
void UpdateClock (int delta_time)
void SetIrq (bool state)
void Nmi ()
uint8_t GetInstructionLength (uint8_t opcode)
void DoInterrupt ()
void SetFlags (uint8_t val)
void SetZN (uint16_t value, bool byte)
bool m ()
bool xf ()
int GetAccumulatorSize () const
int GetIndexSize () const
void SetAccumulatorSize (bool set)
void SetIndexSize (bool set)
void SetNegativeFlag (bool set)
void SetOverflowFlag (bool set)
void SetBreakFlag (bool set)
void SetDecimalFlag (bool set)
void SetInterruptFlag (bool set)
void SetZeroFlag (bool set)
void SetCarryFlag (bool set)
bool GetNegativeFlag () const
bool GetOverflowFlag () const
bool GetBreakFlag () const
bool GetDecimalFlag () const
bool GetInterruptFlag () const
bool GetZeroFlag () const
bool GetCarryFlag () const
uint8_t ReadOpcode ()
uint16_t ReadOpcodeWord (bool int_check=false)
uint8_t ReadByte (uint32_t address)
uint16_t ReadWord (uint32_t address, uint32_t address_high, bool int_check=false)
uint32_t ReadWordLong (uint32_t address)
void WriteByte (uint32_t address, uint8_t value)
void WriteWord (uint32_t address, uint32_t address_high, uint16_t value, bool reversed=false, bool int_check=false)
void WriteLong (uint32_t address, uint32_t value)
void PushByte (uint8_t value)
void PushWord (uint16_t value, bool int_check=false)
void PushLong (uint32_t value)
uint8_t PopByte ()
uint16_t PopWord (bool int_check=false)
uint32_t PopLong ()
void DoBranch (bool check)
void set_int_delay (bool delay)
uint32_t Absolute (uint32_t *low)
uint32_t AbsoluteIndexedX ()
uint32_t AdrAbx (uint32_t *low, bool write)
uint32_t AbsoluteIndexedY ()
uint32_t AdrAby (uint32_t *low, bool write)
void AdrImp ()
uint32_t AdrIdx (uint32_t *low)
uint32_t AdrIdp (uint32_t *low)
uint32_t AdrIdy (uint32_t *low, bool write)
uint32_t AdrIdl (uint32_t *low)
uint32_t AdrIly (uint32_t *low)
uint32_t AdrIsy (uint32_t *low)
uint32_t Immediate (uint32_t *low, bool xFlag)
uint16_t AbsoluteIndexedIndirect ()
uint16_t AbsoluteIndirect ()
uint32_t AbsoluteIndirectLong ()
uint32_t AbsoluteLong ()
uint32_t AdrAbl (uint32_t *low)
uint32_t AbsoluteLongIndexedX ()
uint32_t AdrAlx (uint32_t *low)
void BlockMove (uint16_t source, uint16_t dest, uint16_t length)
uint16_t DirectPage ()
uint32_t AdrDp (uint32_t *low)
uint16_t DirectPageIndexedX ()
uint32_t AdrDpx (uint32_t *low)
uint16_t DirectPageIndexedY ()
uint32_t AdrDpy (uint32_t *low)
uint16_t DirectPageIndexedIndirectX ()
uint16_t DirectPageIndirect ()
uint32_t DirectPageIndirectLong ()
uint16_t DirectPageIndirectIndexedY ()
uint32_t DirectPageIndirectLongIndexedY ()
uint16_t Immediate (bool index_size=false)
uint16_t StackRelative ()
uint32_t AdrSr (uint32_t *low)
uint32_t StackRelativeIndirectIndexedY ()
void ADC (uint16_t operand)
void AND (uint32_t address, bool immediate=false)
void ANDAbsoluteLong (uint32_t address)
void ASL (uint16_t address)
void BCC (int8_t offset)
void BCS (int8_t offset)
void BEQ (int8_t offset)
void BIT (uint16_t address)
void BMI (int8_t offset)
void BNE (int8_t offset)
void BPL (int8_t offset)
void BRA (int8_t offset)
void BRK ()
void BRL (int16_t offset)
void BVC (int8_t offset)
void BVS (int8_t offset)
void CLC ()
void CLD ()
void CLI ()
void CLV ()
void CMP (uint32_t address, bool immediate=false)
void COP ()
void CPX (uint32_t address, bool immediate=false)
void CPY (uint32_t address, bool immediate=false)
void DEC (uint32_t address, bool accumulator=false)
void DEX ()
void DEY ()
void EOR (uint32_t address, bool immediate=false)
void INC (uint32_t address, bool accumulator=false)
void INX ()
void INY ()
void JMP (uint16_t address)
void JML (uint16_t address)
void JSR (uint16_t address)
void JSL (uint16_t address)
void LDA (uint16_t address, bool immediate=false, bool direct_page=false, bool data_bank=false)
void LDX (uint16_t address, bool immediate=false)
void LDY (uint16_t address, bool immediate=false)
void LSR (uint16_t address, bool accumulator=false)
void MVN ()
void MVP ()
void NOP ()
void ORA (uint32_t low, uint32_t high)
void PEA ()
void PEI ()
void PER ()
void PHA ()
void PHB ()
void PHD ()
void PHK ()
void PHP ()
void PHX ()
void PHY ()
void PLA ()
void PLB ()
void PLD ()
void PLP ()
void PLX ()
void PLY ()
void REP ()
void ROL (uint32_t address, bool accumulator=false)
void ROR (uint32_t address, bool accumulator=false)
void RTI ()
void RTL ()
void RTS ()
void SBC (uint32_t operand, bool immediate=false)
void SEC ()
void SED ()
void SEI ()
void SEP ()
void STA (uint32_t address)
void STP ()
void STX (uint16_t address)
void STY (uint16_t address)
void STZ (uint16_t address)
void TAX ()
void TAY ()
void TCD ()
void TCS ()
void TDC ()
void TRB (uint16_t address)
void TSB (uint16_t address)
void TSC ()
void TSX ()
void TXA ()
void TXS ()
void TXY ()
void TYA ()
void TYX ()
void WAI ()
void WDM ()
void XBA ()
void XCE ()
void And (uint32_t low, uint32_t high)
void Eor (uint32_t low, uint32_t high)
void Adc (uint32_t low, uint32_t high)
void Sbc (uint32_t low, uint32_t high)
void Cmp (uint32_t low, uint32_t high)
void Cpx (uint32_t low, uint32_t high)
void Cpy (uint32_t low, uint32_t high)
void Bit (uint32_t low, uint32_t high)
void Lda (uint32_t low, uint32_t high)
void Ldx (uint32_t low, uint32_t high)
void Ldy (uint32_t low, uint32_t high)
void Sta (uint32_t low, uint32_t high)
void Stx (uint32_t low, uint32_t high)
void Sty (uint32_t low, uint32_t high)
void Stz (uint32_t low, uint32_t high)
void Ror (uint32_t low, uint32_t high)
void Rol (uint32_t low, uint32_t high)
void Lsr (uint32_t low, uint32_t high)
void Asl (uint32_t low, uint32_t high)
void Inc (uint32_t low, uint32_t high)
void Dec (uint32_t low, uint32_t high)
void Tsb (uint32_t low, uint32_t high)
void Trb (uint32_t low, uint32_t high)
uint16_t SP () const
void SetSP (uint16_t value)
bool IsBreakpoint (uint32_t address)
void SetBreakpoint (uint32_t address)
void ClearBreakpoint (uint32_t address)
void ClearBreakpoints ()
auto GetBreakpoints ()
void CheckInt ()
auto mutable_log_instructions () -> bool *
Public Attributes
std::vector< uint32_t > breakpoints_
std::vector< InstructionEntry > instruction_log_
uint16_t A = 0
uint16_t X = 0
uint16_t Y = 0
uint16_t D = 0
uint8_t DB = 0
uint8_t PB = 0
uint16_t PC = 0
uint8_t E = 1
uint8_t status = 0b00110000
Private Member Functions
void compare (uint16_t register_value, uint16_t memory_value)
void SetFlag (uint8_t mask, bool set)
bool GetFlag (uint8_t mask) const
Private Attributes
bool log_instructions_ = false
bool waiting_ = false
bool stopped_ = false
bool irq_wanted_ = false
bool nmi_wanted_ = false
bool reset_wanted_ = false
bool int_wanted_ = false
bool int_delay_ = false
CpuCallbacks callbacks_
Memory & memory
Clock & clock
Detailed Description
Definition at line 37 of file cpu.h.
Member Enumeration Documentation
AccessType
enum class yaze::emu::Cpu::AccessType strong
Enumerator
Control
Data
Definition at line 146 of file cpu.h.
Constructor & Destructor Documentation
Cpu()
yaze::emu::Cpu::Cpu (Memory & mem, Clock & vclock, CpuCallbacks & callbacks) inline explicit
Definition at line 39 of file cpu.h.
Member Function Documentation
Reset()
void yaze::emu::Cpu::Reset (bool hard = false)
Definition at line 14 of file cpu.cc.
References A, D, DB, E, int_delay_, int_wanted_, irq_wanted_, nmi_wanted_, PB, PC, reset_wanted_, status, stopped_, waiting_, X, and Y.
Referenced by yaze::emu::Snes::Reset().
RunOpcode()
void yaze::emu::Cpu::RunOpcode ()
Definition at line 36 of file cpu.cc.
References callbacks_, CheckInt(), DoInterrupt(), E, ExecuteInstruction(), yaze::emu::CpuCallbacks::idle, int_wanted_, irq_wanted_, nmi_wanted_, PB, PC, ReadByte(), ReadOpcode(), ReadWord(), reset_wanted_, SetDecimalFlag(), SetFlags(), SetInterruptFlag(), SetSP(), SP(), status, stopped_, and waiting_.
Referenced by yaze::emu::Snes::RunFrame().
ExecuteInstruction()
void yaze::emu::Cpu::ExecuteInstruction (uint8_t opcode)
Definition at line 103 of file cpu.cc.
References A, Absolute(), Adc(), AdrAbl(), AdrAbx(), AdrAby(), AdrAlx(), AdrDp(), AdrDpx(), AdrDpy(), AdrIdl(), AdrIdp(), AdrIdx(), AdrIdy(), AdrIly(), AdrImp(), AdrIsy(), AdrSr(), And(), Asl(), Bit(), callbacks_, CheckInt(), Cmp(), Cpx(), Cpy(), D, DB, Dec(), DoBranch(), E, Eor(), GetAccumulatorSize(), GetCarryFlag(), GetIndexSize(), GetNegativeFlag(), GetOverflowFlag(), GetZeroFlag(), yaze::emu::CpuCallbacks::idle, Immediate(), Inc(), Lda(), Ldx(), Ldy(), log_instructions_, LogInstructions(), Lsr(), ORA(), PB, PC, PopByte(), PopWord(), PushByte(), PushWord(), ReadByte(), ReadOpcode(), ReadOpcodeWord(), ReadWord(), Rol(), Ror(), Sbc(), SetCarryFlag(), SetDecimalFlag(), SetFlags(), SetInterruptFlag(), SetOverflowFlag(), SetSP(), SetZeroFlag(), SetZN(), SP(), Sta(), status, stopped_, Stx(), Sty(), Stz(), Trb(), Tsb(), waiting_, WriteByte(), X, and Y.
Referenced by yaze::zelda3::DungeonObjectRenderer::RenderObject(), and RunOpcode().
LogInstructions()
void yaze::emu::Cpu::LogInstructions (uint16_t PC, uint8_t opcode, uint16_t operand, bool immediate, bool accumulator_mode)
Definition at line 1804 of file cpu.cc.
References A, D, DB, yaze::core::ExperimentFlags::get(), instruction_log_, opcode_to_mnemonic, PB, PC, SP(), status, X, and Y.
Referenced by ExecuteInstruction().
UpdatePC()
void yaze::emu::Cpu::UpdatePC (uint8_t instruction_length) inline
Definition at line 49 of file cpu.h.
References PC.
UpdateClock()
void yaze::emu::Cpu::UpdateClock (int delta_time) inline
Definition at line 50 of file cpu.h.
References clock, and yaze::emu::Clock::UpdateClock().
SetIrq()
void yaze::emu::Cpu::SetIrq (bool state) inline
Definition at line 52 of file cpu.h.
References irq_wanted_.
Referenced by yaze::emu::Snes::ReadReg(), yaze::emu::Snes::RunCycle(), and yaze::emu::Snes::WriteReg().
Nmi()
void yaze::emu::Cpu::Nmi () inline
Definition at line 53 of file cpu.h.
References nmi_wanted_.
Referenced by yaze::emu::Snes::RunCycle(), and yaze::emu::Snes::WriteReg().
GetInstructionLength()
uint8_t yaze::emu::Cpu::GetInstructionLength (uint8_t opcode)
DoInterrupt()
void yaze::emu::Cpu::DoInterrupt ()
Definition at line 86 of file cpu.cc.
References callbacks_, yaze::emu::CpuCallbacks::idle, int_wanted_, nmi_wanted_, PB, PC, PushByte(), PushWord(), ReadWord(), SetDecimalFlag(), SetInterruptFlag(), and status.
Referenced by RunOpcode().
SetFlags()
void yaze::emu::Cpu::SetFlags (uint8_t val) inline
Definition at line 97 of file cpu.h.
References E, GetIndexSize(), SetAccumulatorSize(), SetIndexSize(), SetSP(), SP(), status, X, and Y.
Referenced by ExecuteInstruction(), and RunOpcode().
SetZN()
void yaze::emu::Cpu::SetZN (uint16_t value, bool byte) inline
Definition at line 110 of file cpu.h.
References SetNegativeFlag(), and SetZeroFlag().
Referenced by Adc(), And(), Asl(), Cmp(), Cpx(), Cpy(), Dec(), Eor(), ExecuteInstruction(), Inc(), Lda(), Ldx(), Ldy(), Lsr(), Rol(), Ror(), and Sbc().
m()
bool yaze::emu::Cpu::m () inline
Definition at line 121 of file cpu.h.
References GetAccumulatorSize().
xf()
bool yaze::emu::Cpu::xf () inline
Definition at line 122 of file cpu.h.
References GetIndexSize().
GetAccumulatorSize()
int yaze::emu::Cpu::GetAccumulatorSize () const inline
Definition at line 123 of file cpu.h.
References status.
Referenced by Adc(), And(), Asl(), Bit(), Cmp(), Dec(), DirectPageIndexedX(), DirectPageIndirectLongIndexedY(), Eor(), ExecuteInstruction(), Immediate(), Inc(), Lda(), Lsr(), m(), ORA(), Rol(), Ror(), Sbc(), Sta(), Stz(), Trb(), and Tsb().
GetIndexSize()
int yaze::emu::Cpu::GetIndexSize () const inline
Definition at line 124 of file cpu.h.
References status.
Referenced by AdrAbx(), AdrAby(), AdrIdy(), compare(), Cpx(), Cpy(), ExecuteInstruction(), Immediate(), Ldx(), Ldy(), SetFlags(), Stx(), Sty(), and xf().
SetAccumulatorSize()
void yaze::emu::Cpu::SetAccumulatorSize (bool set) inline
Definition at line 125 of file cpu.h.
References SetFlag().
Referenced by yaze::zelda3::DungeonObjectRenderer::ConfigureObject(), and SetFlags().
SetIndexSize()
void yaze::emu::Cpu::SetIndexSize (bool set) inline
Definition at line 126 of file cpu.h.
References SetFlag().
Referenced by yaze::zelda3::DungeonObjectRenderer::ConfigureObject(), and SetFlags().
SetNegativeFlag()
void yaze::emu::Cpu::SetNegativeFlag (bool set) inline
Definition at line 129 of file cpu.h.
References SetFlag().
Referenced by Bit(), compare(), ORA(), and SetZN().
SetOverflowFlag()
void yaze::emu::Cpu::SetOverflowFlag (bool set) inline
Definition at line 130 of file cpu.h.
References SetFlag().
Referenced by Adc(), Bit(), ExecuteInstruction(), and Sbc().
SetBreakFlag()
void yaze::emu::Cpu::SetBreakFlag (bool set) inline
Definition at line 131 of file cpu.h.
References SetFlag().
SetDecimalFlag()
void yaze::emu::Cpu::SetDecimalFlag (bool set) inline
Definition at line 132 of file cpu.h.
References SetFlag().
Referenced by DoInterrupt(), ExecuteInstruction(), and RunOpcode().
SetInterruptFlag()
void yaze::emu::Cpu::SetInterruptFlag (bool set) inline
Definition at line 133 of file cpu.h.
References SetFlag().
Referenced by DoInterrupt(), ExecuteInstruction(), and RunOpcode().
SetZeroFlag()
void yaze::emu::Cpu::SetZeroFlag (bool set) inline
Definition at line 134 of file cpu.h.
References SetFlag().
Referenced by Bit(), compare(), ExecuteInstruction(), ORA(), SetZN(), Trb(), and Tsb().
SetCarryFlag()
void yaze::emu::Cpu::SetCarryFlag (bool set) inline
Definition at line 135 of file cpu.h.
References SetFlag().
Referenced by Adc(), Asl(), Cmp(), compare(), Cpx(), Cpy(), ExecuteInstruction(), Lsr(), Rol(), Ror(), and Sbc().
GetNegativeFlag()
bool yaze::emu::Cpu::GetNegativeFlag () const inline
Definition at line 138 of file cpu.h.
References GetFlag().
Referenced by ExecuteInstruction().
GetOverflowFlag()
bool yaze::emu::Cpu::GetOverflowFlag () const inline
Definition at line 139 of file cpu.h.
References GetFlag().
Referenced by ExecuteInstruction().
GetBreakFlag()
bool yaze::emu::Cpu::GetBreakFlag () const inline
Definition at line 140 of file cpu.h.
References GetFlag().
GetDecimalFlag()
bool yaze::emu::Cpu::GetDecimalFlag () const inline
Definition at line 141 of file cpu.h.
References GetFlag().
Referenced by Adc(), and Sbc().
GetInterruptFlag()
bool yaze::emu::Cpu::GetInterruptFlag () const inline
Definition at line 142 of file cpu.h.
References GetFlag().
Referenced by CheckInt().
GetZeroFlag()
bool yaze::emu::Cpu::GetZeroFlag () const inline
Definition at line 143 of file cpu.h.
References GetFlag().
Referenced by ExecuteInstruction().
GetCarryFlag()
bool yaze::emu::Cpu::GetCarryFlag () const inline
Definition at line 144 of file cpu.h.
References GetFlag().
Referenced by Adc(), ExecuteInstruction(), Rol(), Ror(), and Sbc().
ReadOpcode()
uint8_t yaze::emu::Cpu::ReadOpcode () inline
Definition at line 148 of file cpu.h.
References PB, PC, and ReadByte().
Referenced by AdrAbl(), AdrAlx(), AdrDp(), AdrDpx(), AdrDpy(), AdrIdl(), AdrIdp(), AdrIdx(), AdrIdy(), AdrIly(), AdrIsy(), AdrSr(), DirectPage(), DirectPageIndexedX(), DirectPageIndexedY(), DirectPageIndirectLong(), DirectPageIndirectLongIndexedY(), DoBranch(), ExecuteInstruction(), ReadOpcodeWord(), RunOpcode(), and StackRelative().
ReadOpcodeWord()
uint16_t yaze::emu::Cpu::ReadOpcodeWord (bool int_check = false) inline
Definition at line 150 of file cpu.h.
References CheckInt(), and ReadOpcode().
Referenced by Absolute(), AdrAbl(), AdrAbx(), AdrAby(), AdrAlx(), and ExecuteInstruction().
ReadByte()
uint8_t yaze::emu::Cpu::ReadByte (uint32_t address) inline
Definition at line 157 of file cpu.h.
References callbacks_, and yaze::emu::CpuCallbacks::read_byte.
Referenced by Adc(), AdrIdl(), AdrIly(), AdrImp(), And(), Asl(), Bit(), Cmp(), Cpx(), Cpy(), Dec(), Eor(), ExecuteInstruction(), Inc(), Lda(), Ldx(), Ldy(), Lsr(), ORA(), PopByte(), ReadOpcode(), ReadWord(), ReadWordLong(), yaze::zelda3::DungeonObjectRenderer::RenderObject(), Rol(), Ror(), RunOpcode(), Sbc(), Trb(), and Tsb().
ReadWord()
uint16_t yaze::emu::Cpu::ReadWord (uint32_t address, uint32_t address_high, bool int_check = false) inline
Definition at line 158 of file cpu.h.
References CheckInt(), and ReadByte().
Referenced by Adc(), AdrIdl(), AdrIdp(), AdrIdx(), AdrIdy(), AdrIly(), AdrIsy(), And(), Asl(), Bit(), Cmp(), Cpx(), Cpy(), Dec(), DoInterrupt(), Eor(), ExecuteInstruction(), Inc(), Lda(), Ldx(), Ldy(), Lsr(), ORA(), Rol(), Ror(), RunOpcode(), Sbc(), Trb(), and Tsb().
ReadWordLong()
uint32_t yaze::emu::Cpu::ReadWordLong (uint32_t address) inline
Definition at line 165 of file cpu.h.
References ReadByte().
Referenced by DirectPageIndirectLong(), and DirectPageIndirectLongIndexedY().
WriteByte()
void yaze::emu::Cpu::WriteByte (uint32_t address, uint8_t value) inline
Definition at line 172 of file cpu.h.
References callbacks_, and yaze::emu::CpuCallbacks::write_byte.
Referenced by Asl(), Dec(), ExecuteInstruction(), Inc(), Lsr(), Rol(), Ror(), Sta(), Stx(), Sty(), Stz(), Trb(), and Tsb().
WriteWord()
void yaze::emu::Cpu::WriteWord (uint32_t address, uint32_t address_high, uint16_t value, bool reversed = false, bool int_check = false) inline
Definition at line 176 of file cpu.h.
References callbacks_, CheckInt(), and yaze::emu::CpuCallbacks::write_byte.
Referenced by Asl(), Dec(), Inc(), Lsr(), Rol(), Ror(), Sta(), Stx(), Sty(), Stz(), Trb(), and Tsb().
WriteLong()
void yaze::emu::Cpu::WriteLong (uint32_t address, uint32_t value) inline
Definition at line 188 of file cpu.h.
References callbacks_, and yaze::emu::CpuCallbacks::write_byte.
Referenced by yaze::zelda3::DungeonObjectRenderer::ConfigureObject().
PushByte()
void yaze::emu::Cpu::PushByte (uint8_t value) inline
Definition at line 194 of file cpu.h.
References callbacks_, E, SetSP(), SP(), and yaze::emu::CpuCallbacks::write_byte.
Referenced by DoInterrupt(), ExecuteInstruction(), PushLong(), and PushWord().
PushWord()
void yaze::emu::Cpu::PushWord (uint16_t value, bool int_check = false) inline
Definition at line 199 of file cpu.h.
References CheckInt(), and PushByte().
Referenced by DoInterrupt(), ExecuteInstruction(), and PushLong().
PushLong()
void yaze::emu::Cpu::PushLong (uint32_t value) inline
Definition at line 204 of file cpu.h.
References PushByte(), and PushWord().
Referenced by yaze::zelda3::DungeonObjectRenderer::RenderObject().
PopByte()
uint8_t yaze::emu::Cpu::PopByte () inline
Definition at line 209 of file cpu.h.
References E, ReadByte(), SetSP(), and SP().
Referenced by ExecuteInstruction(), PopLong(), and PopWord().
PopWord()
uint16_t yaze::emu::Cpu::PopWord (bool int_check = false) inline
Definition at line 214 of file cpu.h.
References CheckInt(), and PopByte().
Referenced by ExecuteInstruction(), and PopLong().
PopLong()
uint32_t yaze::emu::Cpu::PopLong () inline
Definition at line 219 of file cpu.h.
References PopByte(), and PopWord().
DoBranch()
void yaze::emu::Cpu::DoBranch (bool check) inline
Definition at line 225 of file cpu.h.
References callbacks_, CheckInt(), yaze::emu::CpuCallbacks::idle, PC, and ReadOpcode().
Referenced by ExecuteInstruction().
set_int_delay()
void yaze::emu::Cpu::set_int_delay (bool delay) inline
Definition at line 235 of file cpu.h.
References int_delay_.
Referenced by yaze::emu::Snes::CpuIdle(), yaze::emu::Snes::CpuRead(), yaze::emu::Snes::CpuWrite(), and yaze::emu::Snes::WriteReg().
Absolute()
uint32_t yaze::emu::Cpu::Absolute (uint32_t * low)
Definition at line 97 of file addressing.cc.
References DB, and ReadOpcodeWord().
Referenced by ExecuteInstruction().
AbsoluteIndexedX()
uint32_t yaze::emu::Cpu::AbsoluteIndexedX ()
AdrAbx()
uint32_t yaze::emu::Cpu::AdrAbx (uint32_t * low, bool write)
Definition at line 103 of file addressing.cc.
References callbacks_, DB, GetIndexSize(), yaze::emu::CpuCallbacks::idle, ReadOpcodeWord(), and X.
Referenced by ExecuteInstruction().
AbsoluteIndexedY()
uint32_t yaze::emu::Cpu::AbsoluteIndexedY ()
AdrAby()
uint32_t yaze::emu::Cpu::AdrAby (uint32_t * low, bool write)
Definition at line 112 of file addressing.cc.
References callbacks_, DB, GetIndexSize(), yaze::emu::CpuCallbacks::idle, ReadOpcodeWord(), and Y.
Referenced by ExecuteInstruction().
AdrImp()
void yaze::emu::Cpu::AdrImp ()
Definition at line 6 of file addressing.cc.
References callbacks_, CheckInt(), yaze::emu::CpuCallbacks::idle, int_wanted_, PB, PC, and ReadByte().
Referenced by ExecuteInstruction().
AdrIdx()
uint32_t yaze::emu::Cpu::AdrIdx (uint32_t * low)
Definition at line 158 of file addressing.cc.
References callbacks_, D, DB, yaze::emu::CpuCallbacks::idle, ReadOpcode(), ReadWord(), and X.
Referenced by ExecuteInstruction().
AdrIdp()
uint32_t yaze::emu::Cpu::AdrIdp (uint32_t * low)
Definition at line 44 of file addressing.cc.
References callbacks_, D, DB, yaze::emu::CpuCallbacks::idle, ReadOpcode(), and ReadWord().
Referenced by ExecuteInstruction().
AdrIdy()
uint32_t yaze::emu::Cpu::AdrIdy (uint32_t * low, bool write)
Definition at line 52 of file addressing.cc.
References callbacks_, D, DB, GetIndexSize(), yaze::emu::CpuCallbacks::idle, ReadOpcode(), ReadWord(), and Y.
Referenced by ExecuteInstruction().
AdrIdl()
uint32_t yaze::emu::Cpu::AdrIdl (uint32_t * low)
Definition at line 63 of file addressing.cc.
References callbacks_, D, yaze::emu::CpuCallbacks::idle, ReadByte(), ReadOpcode(), and ReadWord().
Referenced by ExecuteInstruction().
AdrIly()
uint32_t yaze::emu::Cpu::AdrIly (uint32_t * low)
Definition at line 72 of file addressing.cc.
References callbacks_, D, yaze::emu::CpuCallbacks::idle, ReadByte(), ReadOpcode(), ReadWord(), and Y.
Referenced by ExecuteInstruction().
AdrIsy()
uint32_t yaze::emu::Cpu::AdrIsy (uint32_t * low)
Definition at line 88 of file addressing.cc.
References callbacks_, DB, yaze::emu::CpuCallbacks::idle, ReadOpcode(), ReadWord(), SP(), and Y.
Referenced by ExecuteInstruction().
Immediate() [1/2]
uint32_t yaze::emu::Cpu::Immediate (uint32_t * low, bool xFlag)
Definition at line 18 of file addressing.cc.
References GetAccumulatorSize(), GetIndexSize(), PB, and PC.
Referenced by ExecuteInstruction().
AbsoluteIndexedIndirect()
uint16_t yaze::emu::Cpu::AbsoluteIndexedIndirect ()
AbsoluteIndirect()
uint16_t yaze::emu::Cpu::AbsoluteIndirect ()
AbsoluteIndirectLong()
uint32_t yaze::emu::Cpu::AbsoluteIndirectLong ()
AbsoluteLong()
uint32_t yaze::emu::Cpu::AbsoluteLong ()
AdrAbl()
uint32_t yaze::emu::Cpu::AdrAbl (uint32_t * low)
Definition at line 121 of file addressing.cc.
References ReadOpcode(), and ReadOpcodeWord().
Referenced by ExecuteInstruction().
AbsoluteLongIndexedX()
uint32_t yaze::emu::Cpu::AbsoluteLongIndexedX ()
AdrAlx()
uint32_t yaze::emu::Cpu::AdrAlx (uint32_t * low)
Definition at line 128 of file addressing.cc.
References ReadOpcode(), ReadOpcodeWord(), and X.
Referenced by ExecuteInstruction().
BlockMove()
void yaze::emu::Cpu::BlockMove (uint16_t source, uint16_t dest, uint16_t length)
DirectPage()
uint16_t yaze::emu::Cpu::DirectPage ()
Definition at line 142 of file addressing.cc.
References D, and ReadOpcode().
AdrDp()
uint32_t yaze::emu::Cpu::AdrDp (uint32_t * low)
Definition at line 135 of file addressing.cc.
References callbacks_, D, yaze::emu::CpuCallbacks::idle, and ReadOpcode().
Referenced by ExecuteInstruction().
DirectPageIndexedX()
uint16_t yaze::emu::Cpu::DirectPageIndexedX ()
Definition at line 147 of file addressing.cc.
References D, GetAccumulatorSize(), ReadOpcode(), and X.
AdrDpx()
uint32_t yaze::emu::Cpu::AdrDpx (uint32_t * low)
Definition at line 28 of file addressing.cc.
References callbacks_, D, yaze::emu::CpuCallbacks::idle, ReadOpcode(), and X.
Referenced by ExecuteInstruction().
DirectPageIndexedY()
uint16_t yaze::emu::Cpu::DirectPageIndexedY ()
Definition at line 153 of file addressing.cc.
References ReadOpcode(), and Y.
AdrDpy()
uint32_t yaze::emu::Cpu::AdrDpy (uint32_t * low)
Definition at line 36 of file addressing.cc.
References callbacks_, D, yaze::emu::CpuCallbacks::idle, ReadOpcode(), and Y.
Referenced by ExecuteInstruction().
DirectPageIndexedIndirectX()
uint16_t yaze::emu::Cpu::DirectPageIndexedIndirectX ()
DirectPageIndirect()
uint16_t yaze::emu::Cpu::DirectPageIndirect ()
DirectPageIndirectLong()
uint32_t yaze::emu::Cpu::DirectPageIndirectLong ()
Definition at line 167 of file addressing.cc.
References D, ReadOpcode(), and ReadWordLong().
DirectPageIndirectIndexedY()
uint16_t yaze::emu::Cpu::DirectPageIndirectIndexedY ()
DirectPageIndirectLongIndexedY()
uint32_t yaze::emu::Cpu::DirectPageIndirectLongIndexedY ()
Definition at line 173 of file addressing.cc.
References D, GetAccumulatorSize(), ReadOpcode(), ReadWordLong(), and Y.
Immediate() [2/2]
uint16_t yaze::emu::Cpu::Immediate (bool index_size = false)
StackRelative()
uint16_t yaze::emu::Cpu::StackRelative ()
Definition at line 181 of file addressing.cc.
References ReadOpcode(), and SP().
AdrSr()
uint32_t yaze::emu::Cpu::AdrSr (uint32_t * low)
Definition at line 81 of file addressing.cc.
References callbacks_, yaze::emu::CpuCallbacks::idle, ReadOpcode(), and SP().
Referenced by ExecuteInstruction().
StackRelativeIndirectIndexedY()
uint32_t yaze::emu::Cpu::StackRelativeIndirectIndexedY ()
ADC()
void yaze::emu::Cpu::ADC (uint16_t operand)
AND()
void yaze::emu::Cpu::AND (uint32_t address, bool immediate = false)
ANDAbsoluteLong()
void yaze::emu::Cpu::ANDAbsoluteLong (uint32_t address)
ASL()
void yaze::emu::Cpu::ASL (uint16_t address)
BCC()
void yaze::emu::Cpu::BCC (int8_t offset)
BCS()
void yaze::emu::Cpu::BCS (int8_t offset)
BEQ()
void yaze::emu::Cpu::BEQ (int8_t offset)
BIT()
void yaze::emu::Cpu::BIT (uint16_t address)
BMI()
void yaze::emu::Cpu::BMI (int8_t offset)
BNE()
void yaze::emu::Cpu::BNE (int8_t offset)
BPL()
void yaze::emu::Cpu::BPL (int8_t offset)
BRA()
void yaze::emu::Cpu::BRA (int8_t offset)
BRK()
void yaze::emu::Cpu::BRK ()
BRL()
void yaze::emu::Cpu::BRL (int16_t offset)
BVC()
void yaze::emu::Cpu::BVC (int8_t offset)
BVS()
void yaze::emu::Cpu::BVS (int8_t offset)
CLC()
void yaze::emu::Cpu::CLC ()
CLD()
void yaze::emu::Cpu::CLD ()
CLI()
void yaze::emu::Cpu::CLI ()
CLV()
void yaze::emu::Cpu::CLV ()
CMP()
void yaze::emu::Cpu::CMP (uint32_t address, bool immediate = false)
COP()
void yaze::emu::Cpu::COP ()
CPX()
void yaze::emu::Cpu::CPX (uint32_t address, bool immediate = false)
CPY()
void yaze::emu::Cpu::CPY (uint32_t address, bool immediate = false)
DEC()
void yaze::emu::Cpu::DEC (uint32_t address, bool accumulator = false)
DEX()
void yaze::emu::Cpu::DEX ()
DEY()
void yaze::emu::Cpu::DEY ()
EOR()
void yaze::emu::Cpu::EOR (uint32_t address, bool immediate = false)
INC()
void yaze::emu::Cpu::INC (uint32_t address, bool accumulator = false)
INX()
void yaze::emu::Cpu::INX ()
INY()
void yaze::emu::Cpu::INY ()
JMP()
void yaze::emu::Cpu::JMP (uint16_t address)
JML()
void yaze::emu::Cpu::JML (uint16_t address)
JSR()
void yaze::emu::Cpu::JSR (uint16_t address)
JSL()
void yaze::emu::Cpu::JSL (uint16_t address)
LDA()
void yaze::emu::Cpu::LDA (uint16_t address, bool immediate = false, bool direct_page = false, bool data_bank = false)
LDX()
void yaze::emu::Cpu::LDX (uint16_t address, bool immediate = false)
LDY()
void yaze::emu::Cpu::LDY (uint16_t address, bool immediate = false)
LSR()
void yaze::emu::Cpu::LSR (uint16_t address, bool accumulator = false)
MVN()
void yaze::emu::Cpu::MVN ()
MVP()
void yaze::emu::Cpu::MVP ()
NOP()
void yaze::emu::Cpu::NOP ()
ORA()
void yaze::emu::Cpu::ORA (uint32_t low, uint32_t high)
Definition at line 384 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
PEA()
void yaze::emu::Cpu::PEA ()
PEI()
void yaze::emu::Cpu::PEI ()
PER()
void yaze::emu::Cpu::PER ()
PHA()
void yaze::emu::Cpu::PHA ()
PHB()
void yaze::emu::Cpu::PHB ()
PHD()
void yaze::emu::Cpu::PHD ()
PHK()
void yaze::emu::Cpu::PHK ()
PHP()
void yaze::emu::Cpu::PHP ()
PHX()
void yaze::emu::Cpu::PHX ()
PHY()
void yaze::emu::Cpu::PHY ()
PLA()
void yaze::emu::Cpu::PLA ()
PLB()
void yaze::emu::Cpu::PLB ()
PLD()
void yaze::emu::Cpu::PLD ()
PLP()
void yaze::emu::Cpu::PLP ()
PLX()
void yaze::emu::Cpu::PLX ()
PLY()
void yaze::emu::Cpu::PLY ()
REP()
void yaze::emu::Cpu::REP ()
ROL()
void yaze::emu::Cpu::ROL (uint32_t address, bool accumulator = false)
ROR()
void yaze::emu::Cpu::ROR (uint32_t address, bool accumulator = false)
RTI()
void yaze::emu::Cpu::RTI ()
RTL()
void yaze::emu::Cpu::RTL ()
RTS()
void yaze::emu::Cpu::RTS ()
SBC()
void yaze::emu::Cpu::SBC (uint32_t operand, bool immediate = false)
SEC()
void yaze::emu::Cpu::SEC ()
SED()
void yaze::emu::Cpu::SED ()
SEI()
void yaze::emu::Cpu::SEI ()
SEP()
void yaze::emu::Cpu::SEP ()
STA()
void yaze::emu::Cpu::STA (uint32_t address)
STP()
void yaze::emu::Cpu::STP ()
STX()
void yaze::emu::Cpu::STX (uint16_t address)
STY()
void yaze::emu::Cpu::STY (uint16_t address)
STZ()
void yaze::emu::Cpu::STZ (uint16_t address)
TAX()
void yaze::emu::Cpu::TAX ()
TAY()
void yaze::emu::Cpu::TAY ()
TCD()
void yaze::emu::Cpu::TCD ()
TCS()
void yaze::emu::Cpu::TCS ()
TDC()
void yaze::emu::Cpu::TDC ()
TRB()
void yaze::emu::Cpu::TRB (uint16_t address)
TSB()
void yaze::emu::Cpu::TSB (uint16_t address)
TSC()
void yaze::emu::Cpu::TSC ()
TSX()
void yaze::emu::Cpu::TSX ()
TXA()
void yaze::emu::Cpu::TXA ()
TXS()
void yaze::emu::Cpu::TXS ()
TXY()
void yaze::emu::Cpu::TXY ()
TYA()
void yaze::emu::Cpu::TYA ()
TYX()
void yaze::emu::Cpu::TYX ()
WAI()
void yaze::emu::Cpu::WAI ()
WDM()
void yaze::emu::Cpu::WDM ()
XBA()
void yaze::emu::Cpu::XBA ()
XCE()
void yaze::emu::Cpu::XCE ()
And()
void yaze::emu::Cpu::And (uint32_t low, uint32_t high)
65816 Instruction Set
Definition at line 14 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), and SetZN().
Referenced by ExecuteInstruction().
Eor()
void yaze::emu::Cpu::Eor (uint32_t low, uint32_t high)
Definition at line 26 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), and SetZN().
Referenced by ExecuteInstruction().
Adc()
void yaze::emu::Cpu::Adc (uint32_t low, uint32_t high)
Definition at line 38 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), GetDecimalFlag(), ReadByte(), ReadWord(), SetCarryFlag(), SetOverflowFlag(), and SetZN().
Referenced by ExecuteInstruction().
Sbc()
void yaze::emu::Cpu::Sbc (uint32_t low, uint32_t high)
Definition at line 78 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), GetDecimalFlag(), ReadByte(), ReadWord(), SetCarryFlag(), SetOverflowFlag(), and SetZN().
Referenced by ExecuteInstruction().
Cmp()
void yaze::emu::Cpu::Cmp (uint32_t low, uint32_t high)
Definition at line 122 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), SetCarryFlag(), and SetZN().
Referenced by ExecuteInstruction().
Cpx()
void yaze::emu::Cpu::Cpx (uint32_t low, uint32_t high)
Definition at line 137 of file instructions.cc.
References CheckInt(), GetIndexSize(), ReadByte(), ReadWord(), SetCarryFlag(), SetZN(), and X.
Referenced by ExecuteInstruction().
Cpy()
void yaze::emu::Cpu::Cpy (uint32_t low, uint32_t high)
Definition at line 152 of file instructions.cc.
References CheckInt(), GetIndexSize(), ReadByte(), ReadWord(), SetCarryFlag(), SetZN(), and Y.
Referenced by ExecuteInstruction().
Bit()
void yaze::emu::Cpu::Bit (uint32_t low, uint32_t high)
Definition at line 167 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), SetNegativeFlag(), SetOverflowFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
Lda()
void yaze::emu::Cpu::Lda (uint32_t low, uint32_t high)
Definition at line 184 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), and SetZN().
Referenced by ExecuteInstruction().
Ldx()
void yaze::emu::Cpu::Ldx (uint32_t low, uint32_t high)
Definition at line 194 of file instructions.cc.
References CheckInt(), GetIndexSize(), ReadByte(), ReadWord(), SetZN(), and X.
Referenced by ExecuteInstruction().
Ldy()
void yaze::emu::Cpu::Ldy (uint32_t low, uint32_t high)
Definition at line 204 of file instructions.cc.
References CheckInt(), GetIndexSize(), ReadByte(), ReadWord(), SetZN(), and Y.
Referenced by ExecuteInstruction().
Sta()
void yaze::emu::Cpu::Sta (uint32_t low, uint32_t high)
Definition at line 214 of file instructions.cc.
References A, CheckInt(), GetAccumulatorSize(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Stx()
void yaze::emu::Cpu::Stx (uint32_t low, uint32_t high)
Definition at line 223 of file instructions.cc.
References CheckInt(), GetIndexSize(), WriteByte(), WriteWord(), and X.
Referenced by ExecuteInstruction().
Sty()
void yaze::emu::Cpu::Sty (uint32_t low, uint32_t high)
Definition at line 232 of file instructions.cc.
References CheckInt(), GetIndexSize(), WriteByte(), WriteWord(), and Y.
Referenced by ExecuteInstruction().
Stz()
void yaze::emu::Cpu::Stz (uint32_t low, uint32_t high)
Definition at line 241 of file instructions.cc.
References CheckInt(), GetAccumulatorSize(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Ror()
void yaze::emu::Cpu::Ror (uint32_t low, uint32_t high)
Definition at line 250 of file instructions.cc.
References callbacks_, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetZN(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Rol()
void yaze::emu::Cpu::Rol (uint32_t low, uint32_t high)
Definition at line 271 of file instructions.cc.
References callbacks_, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetZN(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Lsr()
void yaze::emu::Cpu::Lsr (uint32_t low, uint32_t high)
Definition at line 288 of file instructions.cc.
References callbacks_, CheckInt(), GetAccumulatorSize(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetZN(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Asl()
void yaze::emu::Cpu::Asl (uint32_t low, uint32_t high)
Definition at line 307 of file instructions.cc.
References callbacks_, CheckInt(), GetAccumulatorSize(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetZN(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Inc()
void yaze::emu::Cpu::Inc (uint32_t low, uint32_t high)
Definition at line 324 of file instructions.cc.
References callbacks_, CheckInt(), GetAccumulatorSize(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetZN(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Dec()
void yaze::emu::Cpu::Dec (uint32_t low, uint32_t high)
Definition at line 339 of file instructions.cc.
References callbacks_, CheckInt(), GetAccumulatorSize(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetZN(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Tsb()
void yaze::emu::Cpu::Tsb (uint32_t low, uint32_t high)
Definition at line 354 of file instructions.cc.
References A, callbacks_, CheckInt(), GetAccumulatorSize(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
Trb()
void yaze::emu::Cpu::Trb (uint32_t low, uint32_t high)
Definition at line 369 of file instructions.cc.
References A, callbacks_, CheckInt(), GetAccumulatorSize(), yaze::emu::CpuCallbacks::idle, ReadByte(), ReadWord(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
SP()
uint16_t yaze::emu::Cpu::SP () const inline
Definition at line 728 of file cpu.h.
References memory, and yaze::emu::Memory::SP().
Referenced by AdrIsy(), AdrSr(), ExecuteInstruction(), LogInstructions(), PopByte(), PushByte(), RunOpcode(), SetFlags(), and StackRelative().
SetSP()
void yaze::emu::Cpu::SetSP (uint16_t value) inline
Definition at line 729 of file cpu.h.
References memory, and yaze::emu::Memory::SetSP().
Referenced by ExecuteInstruction(), PopByte(), PushByte(), RunOpcode(), and SetFlags().
IsBreakpoint()
bool yaze::emu::Cpu::IsBreakpoint (uint32_t address) inline
Definition at line 731 of file cpu.h.
References breakpoints_.
SetBreakpoint()
void yaze::emu::Cpu::SetBreakpoint (uint32_t address) inline
Definition at line 735 of file cpu.h.
References breakpoints_.
ClearBreakpoint()
void yaze::emu::Cpu::ClearBreakpoint (uint32_t address) inline
Definition at line 736 of file cpu.h.
References breakpoints_.
ClearBreakpoints()
void yaze::emu::Cpu::ClearBreakpoints () inline
Definition at line 741 of file cpu.h.
References breakpoints_.
GetBreakpoints()
auto yaze::emu::Cpu::GetBreakpoints () inline
Definition at line 745 of file cpu.h.
References breakpoints_.
CheckInt()
void yaze::emu::Cpu::CheckInt () inline
Definition at line 747 of file cpu.h.
References GetInterruptFlag(), int_delay_, int_wanted_, irq_wanted_, and nmi_wanted_.
Referenced by Adc(), AdrImp(), And(), Asl(), Bit(), Cmp(), Cpx(), Cpy(), Dec(), DoBranch(), Eor(), ExecuteInstruction(), Inc(), Lda(), Ldx(), Ldy(), Lsr(), ORA(), PopWord(), PushWord(), ReadOpcodeWord(), ReadWord(), Rol(), Ror(), RunOpcode(), Sbc(), Sta(), Stx(), Sty(), Stz(), Trb(), Tsb(), and WriteWord().
mutable_log_instructions()
auto yaze::emu::Cpu::mutable_log_instructions () -> bool* inline
Definition at line 753 of file cpu.h.
References log_instructions_.
compare()
void yaze::emu::Cpu::compare (uint16_t register_value, uint16_t memory_value) inline private
Definition at line 756 of file cpu.h.
References GetIndexSize(), SetCarryFlag(), SetNegativeFlag(), and SetZeroFlag().
SetFlag()
void yaze::emu::Cpu::SetFlag (uint8_t mask, bool set) inline private
Definition at line 773 of file cpu.h.
References status.
Referenced by SetAccumulatorSize(), SetBreakFlag(), SetCarryFlag(), SetDecimalFlag(), SetIndexSize(), SetInterruptFlag(), SetNegativeFlag(), SetOverflowFlag(), and SetZeroFlag().
GetFlag()
bool yaze::emu::Cpu::GetFlag (uint8_t mask) const inline private
Definition at line 781 of file cpu.h.
References status.
Referenced by GetBreakFlag(), GetCarryFlag(), GetDecimalFlag(), GetInterruptFlag(), GetNegativeFlag(), GetOverflowFlag(), and GetZeroFlag().
Member Data Documentation
breakpoints_
std::vector<uint32_t> yaze::emu::Cpu::breakpoints_
Definition at line 57 of file cpu.h.
Referenced by ClearBreakpoint(), ClearBreakpoints(), GetBreakpoints(), IsBreakpoint(), and SetBreakpoint().
instruction_log_
std::vector<InstructionEntry> yaze::emu::Cpu::instruction_log_
Definition at line 58 of file cpu.h.
Referenced by LogInstructions().
A
uint16_t yaze::emu::Cpu::A = 0
Definition at line 75 of file cpu.h.
Referenced by Adc(), And(), Bit(), Cmp(), yaze::zelda3::DungeonObjectRenderer::ConfigureObject(), Eor(), ExecuteInstruction(), Lda(), LogInstructions(), ORA(), Reset(), Sbc(), Sta(), Trb(), and Tsb().
X
uint16_t yaze::emu::Cpu::X = 0
Definition at line 76 of file cpu.h.
Referenced by AdrAbx(), AdrAlx(), AdrDpx(), AdrIdx(), yaze::zelda3::DungeonObjectRenderer::ConfigureObject(), Cpx(), DirectPageIndexedX(), ExecuteInstruction(), Ldx(), LogInstructions(), Reset(), SetFlags(), and Stx().
Y
uint16_t yaze::emu::Cpu::Y = 0
Definition at line 77 of file cpu.h.
Referenced by AdrAby(), AdrDpy(), AdrIdy(), AdrIly(), AdrIsy(), Cpy(), DirectPageIndexedY(), DirectPageIndirectLongIndexedY(), ExecuteInstruction(), Ldy(), LogInstructions(), Reset(), SetFlags(), and Sty().
D
uint16_t yaze::emu::Cpu::D = 0
Definition at line 78 of file cpu.h.
Referenced by AdrDp(), AdrDpx(), AdrDpy(), AdrIdl(), AdrIdp(), AdrIdx(), AdrIdy(), AdrIly(), DirectPage(), DirectPageIndexedX(), DirectPageIndirectLong(), DirectPageIndirectLongIndexedY(), ExecuteInstruction(), LogInstructions(), and Reset().
DB
uint8_t yaze::emu::Cpu::DB = 0
Definition at line 79 of file cpu.h.
Referenced by Absolute(), AdrAbx(), AdrAby(), AdrIdp(), AdrIdx(), AdrIdy(), AdrIsy(), yaze::zelda3::DungeonObjectRenderer::ConfigureObject(), ExecuteInstruction(), LogInstructions(), and Reset().
PB
uint8_t yaze::emu::Cpu::PB = 0
Definition at line 80 of file cpu.h.
Referenced by AdrImp(), DoInterrupt(), ExecuteInstruction(), Immediate(), LogInstructions(), ReadOpcode(), yaze::zelda3::DungeonObjectRenderer::RenderObject(), Reset(), and RunOpcode().
PC
uint16_t yaze::emu::Cpu::PC = 0
Definition at line 81 of file cpu.h.
Referenced by AdrImp(), DoBranch(), DoInterrupt(), ExecuteInstruction(), Immediate(), LogInstructions(), ReadOpcode(), yaze::zelda3::DungeonObjectRenderer::RenderObject(), Reset(), RunOpcode(), and UpdatePC().
E
uint8_t yaze::emu::Cpu::E = 1
Definition at line 82 of file cpu.h.
Referenced by ExecuteInstruction(), PopByte(), PushByte(), Reset(), RunOpcode(), and SetFlags().
status
uint8_t yaze::emu::Cpu::status = 0b00110000
Definition at line 83 of file cpu.h.
Referenced by DoInterrupt(), ExecuteInstruction(), GetAccumulatorSize(), GetFlag(), GetIndexSize(), LogInstructions(), Reset(), RunOpcode(), SetFlag(), and SetFlags().
log_instructions_
bool yaze::emu::Cpu::log_instructions_ = false private
Definition at line 783 of file cpu.h.
Referenced by ExecuteInstruction(), and mutable_log_instructions().
waiting_
bool yaze::emu::Cpu::waiting_ = false private
Definition at line 785 of file cpu.h.
Referenced by ExecuteInstruction(), Reset(), and RunOpcode().
stopped_
bool yaze::emu::Cpu::stopped_ = false private
Definition at line 786 of file cpu.h.
Referenced by ExecuteInstruction(), Reset(), and RunOpcode().
irq_wanted_
bool yaze::emu::Cpu::irq_wanted_ = false private
Definition at line 788 of file cpu.h.
Referenced by CheckInt(), Reset(), RunOpcode(), and SetIrq().
nmi_wanted_
bool yaze::emu::Cpu::nmi_wanted_ = false private
Definition at line 789 of file cpu.h.
Referenced by CheckInt(), DoInterrupt(), Nmi(), Reset(), and RunOpcode().
reset_wanted_
bool yaze::emu::Cpu::reset_wanted_ = false private
Definition at line 790 of file cpu.h.
Referenced by Reset(), and RunOpcode().
int_wanted_
bool yaze::emu::Cpu::int_wanted_ = false private
Definition at line 791 of file cpu.h.
Referenced by AdrImp(), CheckInt(), DoInterrupt(), Reset(), and RunOpcode().
int_delay_
bool yaze::emu::Cpu::int_delay_ = false private
Definition at line 792 of file cpu.h.
Referenced by CheckInt(), Reset(), and set_int_delay().
callbacks_
CpuCallbacks yaze::emu::Cpu::callbacks_ private
Definition at line 794 of file cpu.h.
Referenced by AdrAbx(), AdrAby(), AdrDp(), AdrDpx(), AdrDpy(), AdrIdl(), AdrIdp(), AdrIdx(), AdrIdy(), AdrIly(), AdrImp(), AdrIsy(), AdrSr(), Asl(), Dec(), DoBranch(), DoInterrupt(), ExecuteInstruction(), Inc(), Lsr(), PushByte(), ReadByte(), Rol(), Ror(), RunOpcode(), Trb(), Tsb(), WriteByte(), WriteLong(), and WriteWord().
memory
Memory& yaze::emu::Cpu::memory private
Definition at line 795 of file cpu.h.
Referenced by SetSP(), and SP().
clock
Clock& yaze::emu::Cpu::clock private
Definition at line 796 of file cpu.h.
Referenced by UpdateClock().
The documentation for this class was generated from the following files:
src/app/emu/cpu/cpu.h
src/app/emu/cpu/cpu.cc
src/app/emu/cpu/internal/addressing.cc
src/app/emu/cpu/internal/instructions.cc