yaze: yaze::app::emu::memory::MemoryImpl Class Reference
yaze::app::emu::memory::MemoryImpl Class Reference
Implementation of the Memory interface for emulating memory in a SNES system.
#include <memory.h>
Public Member Functions
void Initialize (const std::vector< uint8_t > &romData, bool verbose=false)
uint16_t GetHeaderOffset ()
memory::RomInfo ReadRomHeader ()
uint8_t cart_read (uint8_t bank, uint16_t adr)
void cart_write (uint8_t bank, uint16_t adr, uint8_t val)
uint8_t cart_readLorom (uint8_t bank, uint16_t adr)
void cart_writeLorom (uint8_t bank, uint16_t adr, uint8_t val)
uint8_t cart_readHirom (uint8_t bank, uint16_t adr)
uint8_t cart_readExHirom (uint8_t bank, uint16_t adr)
void cart_writeHirom (uint8_t bank, uint16_t adr, uint8_t val)
uint8_t ReadByte (uint32_t address) const override
uint16_t ReadWord (uint32_t address) const override
uint32_t ReadWordLong (uint32_t address) const override
std::vector< uint8_t > ReadByteVector (uint32_t address, uint16_t length) const override
void WriteByte (uint32_t address, uint8_t value) override
void WriteWord (uint32_t address, uint16_t value) override
void WriteLong (uint32_t address, uint32_t value) override
void PushByte (uint8_t value) override
uint8_t PopByte () override
void PushWord (uint16_t value) override
uint16_t PopWord () override
void PushLong (uint32_t value) override
uint32_t PopLong () override
uint16_t SP () const override
void SetSP (uint16_t value) override
void ClearMemory () override
uint8_t at (int i) const override
uint8_t operator[] (int i) const override
auto size () const
auto begin () const
auto end () const
auto data () const
void set_open_bus (uint8_t value) override
auto open_bus () const -> uint8_t override
auto hdma_init_requested () const -> bool override
auto hdma_run_requested () const -> bool override
void init_hdma_request () override
void run_hdma_request () override
void set_hdma_run_requested (bool value) override
void set_hdma_init_requested (bool value) override
void set_pal_timing (bool value) override
void set_h_pos (uint16_t value) override
void set_v_pos (uint16_t value) override
auto h_pos () const -> uint16_t override
auto v_pos () const -> uint16_t override
auto pal_timing () const -> bool override
auto dma_state () -> uint8_t &
void set_dma_state (uint8_t value)
auto dma_channels () -> DmaChannel *
Public Member Functions inherited from yaze::app::emu::memory::Memory
virtual ~Memory ()=default
Public Attributes
uint32_t romSize
uint32_t sramSize
std::vector< uint8_t > rom_
std::vector< uint8_t > ram_
Private Member Functions
uint32_t GetMappedAddress (uint32_t address) const
Private Attributes
bool verbose_ = false
bool hdma_run_requested_ = false
bool hdma_init_requested_ = false
bool pal_timing_ = false
uint16_t h_pos_ = 0
uint16_t v_pos_ = 0
uint8_t dma_state_ = 0
DmaChannel channel [8]
uint8_t open_bus_ = 0
uint16_t SP_ = 0x01FF
uint8_t type_
std::vector< uint8_t > memory_
Additional Inherited Members
Protected Member Functions inherited from yaze::app::emu::Loggable
virtual ~Loggable ()=default
virtual void LogMessage (const std::string &message)
Protected Attributes inherited from yaze::app::emu::Loggable
Logger & logger_ = Logger::GetInstance()
Detailed Description
Implementation of the Memory interface for emulating memory in a SNES system.
Member Function Documentation
Initialize()
void yaze::app::emu::memory::MemoryImpl::Initialize (const std::vector< uint8_t > & romData, bool verbose = false)
References memory_, rom_, romSize, sramSize, and verbose_.
Referenced by yaze::app::emu::SNES::Init(), and yaze::app::zelda3::dungeon::DungeonObjectRenderer::LoadObject().
GetHeaderOffset()
uint16_t yaze::app::emu::memory::MemoryImpl::GetHeaderOffset () inline
Referenced by ReadRomHeader().
ReadRomHeader()
memory::RomInfo yaze::app::emu::memory::MemoryImpl::ReadRomHeader ()
References yaze::app::emu::memory::RomInfo::bankSize, yaze::app::emu::memory::RomInfo::checksum, yaze::app::emu::memory::RomInfo::checksumComplement, yaze::app::emu::memory::RomInfo::countryCode, GetHeaderOffset(), yaze::app::emu::memory::RomInfo::license, yaze::app::emu::memory::RomInfo::nmiVblVector, ReadByte(), ReadWord(), yaze::app::emu::memory::RomInfo::resetVector, yaze::app::emu::memory::RomInfo::romSize, yaze::app::emu::memory::RomInfo::romSpeed, yaze::app::emu::memory::RomInfo::romType, yaze::app::emu::memory::RomInfo::sramSize, yaze::app::emu::memory::RomInfo::title, and yaze::app::emu::memory::RomInfo::version.
cart_read()
uint8_t yaze::app::emu::memory::MemoryImpl::cart_read (uint8_t bank, uint16_t adr)
References cart_readExHirom(), cart_readHirom(), cart_readLorom(), open_bus_, and type_.
Referenced by yaze::app::emu::SNES::Rread().
cart_write()
void yaze::app::emu::memory::MemoryImpl::cart_write (uint8_t bank, uint16_t adr, uint8_t val)
References cart_writeHirom(), cart_writeLorom(), and type_.
Referenced by yaze::app::emu::SNES::Write().
cart_readLorom()
uint8_t yaze::app::emu::memory::MemoryImpl::cart_readLorom (uint8_t bank, uint16_t adr)
References open_bus_, ram_, rom_, romSize, and sramSize.
Referenced by cart_read().
cart_writeLorom()
void yaze::app::emu::memory::MemoryImpl::cart_writeLorom (uint8_t bank, uint16_t adr, uint8_t val)
References ram_, and sramSize.
Referenced by cart_write().
cart_readHirom()
uint8_t yaze::app::emu::memory::MemoryImpl::cart_readHirom (uint8_t bank, uint16_t adr)
References open_bus_, ram_, rom_, romSize, and sramSize.
Referenced by cart_read().
cart_readExHirom()
uint8_t yaze::app::emu::memory::MemoryImpl::cart_readExHirom (uint8_t bank, uint16_t adr)
References open_bus_, ram_, rom_, romSize, and sramSize.
Referenced by cart_read().
cart_writeHirom()
void yaze::app::emu::memory::MemoryImpl::cart_writeHirom (uint8_t bank, uint16_t adr, uint8_t val)
References ram_, and sramSize.
Referenced by cart_write().
ReadByte()
uint8_t yaze::app::emu::memory::MemoryImpl::ReadByte (uint32_t address) const inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by ReadRomHeader().
ReadWord()
uint16_t yaze::app::emu::memory::MemoryImpl::ReadWord (uint32_t address) const inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by ReadRomHeader(), and yaze::app::zelda3::dungeon::DungeonObjectRenderer::UpdateObjectBitmap().
ReadWordLong()
uint32_t yaze::app::emu::memory::MemoryImpl::ReadWordLong (uint32_t address) const inline override virtual
Implements yaze::app::emu::memory::Memory.
ReadByteVector()
std::vector< uint8_t > yaze::app::emu::memory::MemoryImpl::ReadByteVector (uint32_t address, uint16_t length) const inline override virtual
Implements yaze::app::emu::memory::Memory.
WriteByte()
void yaze::app::emu::memory::MemoryImpl::WriteByte (uint32_t address, uint8_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::Init().
WriteWord()
void yaze::app::emu::memory::MemoryImpl::WriteWord (uint32_t address, uint16_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
WriteLong()
void yaze::app::emu::memory::MemoryImpl::WriteLong (uint32_t address, uint32_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
PushByte()
void yaze::app::emu::memory::MemoryImpl::PushByte (uint8_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
PopByte()
uint8_t yaze::app::emu::memory::MemoryImpl::PopByte () inline override virtual
Implements yaze::app::emu::memory::Memory.
PushWord()
void yaze::app::emu::memory::MemoryImpl::PushWord (uint16_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
References yaze::app::emu::memory::Memory::PushByte().
PopWord()
uint16_t yaze::app::emu::memory::MemoryImpl::PopWord () inline override virtual
Implements yaze::app::emu::memory::Memory.
References yaze::app::emu::memory::Memory::PopByte().
PushLong()
void yaze::app::emu::memory::MemoryImpl::PushLong (uint32_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
References yaze::app::emu::memory::Memory::PushByte().
PopLong()
uint32_t yaze::app::emu::memory::MemoryImpl::PopLong () inline override virtual
Implements yaze::app::emu::memory::Memory.
References yaze::app::emu::memory::Memory::PopByte().
SP()
uint16_t yaze::app::emu::memory::MemoryImpl::SP () const inline override virtual
Implements yaze::app::emu::memory::Memory.
SetSP()
void yaze::app::emu::memory::MemoryImpl::SetSP (uint16_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
ClearMemory()
void yaze::app::emu::memory::MemoryImpl::ClearMemory () inline override virtual
Implements yaze::app::emu::memory::Memory.
at()
uint8_t yaze::app::emu::memory::MemoryImpl::at (int i) const inline override virtual
Implements yaze::app::emu::memory::Memory.
operator[]()
uint8_t yaze::app::emu::memory::MemoryImpl::operator[] (int i) const inline override virtual
Implements yaze::app::emu::memory::Memory.
size()
auto yaze::app::emu::memory::MemoryImpl::size () const inline
begin()
auto yaze::app::emu::memory::MemoryImpl::begin () const inline
end()
auto yaze::app::emu::memory::MemoryImpl::end () const inline
data()
auto yaze::app::emu::memory::MemoryImpl::data () const inline
set_open_bus()
void yaze::app::emu::memory::MemoryImpl::set_open_bus (uint8_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::Read(), yaze::app::emu::SNES::Reset(), and yaze::app::emu::SNES::Write().
open_bus()
auto yaze::app::emu::memory::MemoryImpl::open_bus () const -> uint8_t inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::memory::dma::Read(), yaze::app::emu::SNES::ReadBBus(), yaze::app::emu::SNES::ReadReg(), yaze::app::emu::SNES::Rread(), and yaze::app::emu::memory::dma::TransferByte().
hdma_init_requested()
auto yaze::app::emu::memory::MemoryImpl::hdma_init_requested () const -> bool inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::memory::dma::HandleDma(), and yaze::app::emu::memory::dma::WaitCycle().
hdma_run_requested()
auto yaze::app::emu::memory::MemoryImpl::hdma_run_requested () const -> bool inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::memory::dma::HandleDma(), and yaze::app::emu::memory::dma::WaitCycle().
init_hdma_request()
void yaze::app::emu::memory::MemoryImpl::init_hdma_request () inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::RunCycle().
run_hdma_request()
void yaze::app::emu::memory::MemoryImpl::run_hdma_request () inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::RunCycle().
set_hdma_run_requested()
void yaze::app::emu::memory::MemoryImpl::set_hdma_run_requested (bool value) inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::memory::dma::DoHdma().
set_hdma_init_requested()
void yaze::app::emu::memory::MemoryImpl::set_hdma_init_requested (bool value) inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::memory::dma::InitHdma().
set_pal_timing()
void yaze::app::emu::memory::MemoryImpl::set_pal_timing (bool value) inline override virtual
Implements yaze::app::emu::memory::Memory.
set_h_pos()
void yaze::app::emu::memory::MemoryImpl::set_h_pos (uint16_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::Reset(), and yaze::app::emu::SNES::RunCycle().
set_v_pos()
void yaze::app::emu::memory::MemoryImpl::set_v_pos (uint16_t value) inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::Reset(), and yaze::app::emu::SNES::RunCycle().
h_pos()
auto yaze::app::emu::memory::MemoryImpl::h_pos () const -> uint16_t inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::ReadReg(), yaze::app::emu::SNES::RunCycle(), and yaze::app::emu::SNES::RunCycles().
v_pos()
auto yaze::app::emu::memory::MemoryImpl::v_pos () const -> uint16_t inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::RunCycle().
pal_timing()
auto yaze::app::emu::memory::MemoryImpl::pal_timing () const -> bool inline override virtual
Implements yaze::app::emu::memory::Memory.
Referenced by yaze::app::emu::SNES::RunCycle(), and yaze::app::emu::SNES::SetSamples().
dma_state()
auto yaze::app::emu::memory::MemoryImpl::dma_state () -> uint8_t& inline
Referenced by yaze::app::emu::memory::dma::HandleDma().
set_dma_state()
void yaze::app::emu::memory::MemoryImpl::set_dma_state (uint8_t value) inline
Referenced by yaze::app::emu::memory::dma::HandleDma(), and yaze::app::emu::memory::dma::StartDma().
dma_channels()
auto yaze::app::emu::memory::MemoryImpl::dma_channels () -> DmaChannel* inline
Referenced by yaze::app::emu::memory::dma::DoDma(), yaze::app::emu::memory::dma::DoHdma(), yaze::app::emu::memory::dma::InitHdma(), yaze::app::emu::memory::dma::Read(), yaze::app::emu::memory::dma::StartDma(), and yaze::app::emu::memory::dma::Write().
GetMappedAddress()
uint32_t yaze::app::emu::memory::MemoryImpl::GetMappedAddress (uint32_t address) const private
Member Data Documentation
romSize
uint32_t yaze::app::emu::memory::MemoryImpl::romSize
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), and Initialize().
sramSize
uint32_t yaze::app::emu::memory::MemoryImpl::sramSize
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), cart_writeHirom(), cart_writeLorom(), and Initialize().
rom_
std::vector<uint8_t> yaze::app::emu::memory::MemoryImpl::rom_
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), and Initialize().
ram_
std::vector<uint8_t> yaze::app::emu::memory::MemoryImpl::ram_
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), cart_writeHirom(), and cart_writeLorom().
verbose_
bool yaze::app::emu::memory::MemoryImpl::verbose_ = false private
Referenced by Initialize().
hdma_run_requested_
bool yaze::app::emu::memory::MemoryImpl::hdma_run_requested_ = false private
hdma_init_requested_
bool yaze::app::emu::memory::MemoryImpl::hdma_init_requested_ = false private
pal_timing_
bool yaze::app::emu::memory::MemoryImpl::pal_timing_ = false private
h_pos_
uint16_t yaze::app::emu::memory::MemoryImpl::h_pos_ = 0 private
v_pos_
uint16_t yaze::app::emu::memory::MemoryImpl::v_pos_ = 0 private
dma_state_
uint8_t yaze::app::emu::memory::MemoryImpl::dma_state_ = 0 private
channel
DmaChannel yaze::app::emu::memory::MemoryImpl::channel[8] private
open_bus_
uint8_t yaze::app::emu::memory::MemoryImpl::open_bus_ = 0 private
Referenced by cart_read(), cart_readExHirom(), cart_readHirom(), and cart_readLorom().
SP_
uint16_t yaze::app::emu::memory::MemoryImpl::SP_ = 0x01FF private
type_
uint8_t yaze::app::emu::memory::MemoryImpl::type_ private
Referenced by cart_read(), and cart_write().
memory_
std::vector<uint8_t> yaze::app::emu::memory::MemoryImpl::memory_ private
Referenced by Initialize().
The documentation for this class was generated from the following files:
src/app/emu/memory/memory.h
src/app/emu/memory/memory.cc