yaze: yaze::emu::audio::Apu Class Reference
yaze::emu::audio::Apu Class Reference
The Apu class represents the Audio Processing Unit (APU) of a system.
#include <apu.h>
Public Member Functions
Apu (MemoryImpl &memory)
void Init ()
void Reset ()
void RunCycles (uint64_t cycles)
uint8_t SpcRead (uint16_t address)
void SpcWrite (uint16_t address, uint8_t data)
void SpcIdle (bool waiting)
void Cycle ()
uint8_t Read (uint16_t address)
void Write (uint16_t address, uint8_t data)
auto dsp () -> Dsp &
auto spc700 () -> Spc700 &
Public Attributes
std::array< uint8_t, 6 > in_ports_
std::array< uint8_t, 4 > out_ports_
std::vector< uint8_t > ram = std::vector<uint8_t>(0x10000, 0)
Private Attributes
bool rom_readable_ = false
uint8_t dsp_adr_ = 0
uint32_t cycles_ = 0
MemoryImpl & memory_
std::array< Timer, 3 > timer_
ApuCallbacks callbacks_
Dsp dsp_ {ram}
Spc700 spc700_ {callbacks_}
Detailed Description
The Apu class represents the Audio Processing Unit (APU) of a system.
The Apu class is responsible for generating audio samples and managing the APU state. It interacts with the Memory, AudioRam, and Clock classes to read/write data and update the clock. The class also implements the Observer interface to receive notifications from the system.
IPL ROM Info
64 kilobytes of RAM are mapped across the 16-bit memory space of the SPC-700. Some regions of this space are overlaid with special hardware functions.
Range Note
$0000-00EF Zero Page RAM $00F0-00FF Sound CPU Registers $0100-01FF Stack Page RAM $0200-FFBF RAM $FFC0-FFFF IPL ROM or RAM
The region at $FFC0-FFFF will normally read from the 64-byte IPL ROM, but the underlying RAM can always be written to, and the high bit of the Control register $F1 can be cleared to unmap the IPL ROM and allow read access to this RAM.
Definition at line 52 of file apu.h.
Constructor & Destructor Documentation
Apu()
yaze::emu::audio::Apu::Apu (MemoryImpl & memory) inline
Definition at line 54 of file apu.h.
Member Function Documentation
Init()
void yaze::emu::audio::Apu::Init ()
Definition at line 30 of file apu.cc.
References ram.
Referenced by yaze::emu::SNES::Init().
Reset()
void yaze::emu::audio::Apu::Reset ()
Definition at line 41 of file apu.cc.
References cycles_, dsp_, dsp_adr_, in_ports_, out_ports_, ram, yaze::emu::audio::Dsp::Reset(), yaze::emu::audio::Spc700::Reset(), rom_readable_, spc700_, and timer_.
Referenced by yaze::emu::SNES::Reset().
RunCycles()
void yaze::emu::audio::Apu::RunCycles (uint64_t cycles)
Definition at line 65 of file apu.cc.
References cycles_, memory_, yaze::emu::memory::MemoryImpl::pal_timing(), yaze::emu::audio::Spc700::RunOpcode(), and spc700_.
Referenced by yaze::emu::SNES::CatchUpApu().
SpcRead()
uint8_t yaze::emu::audio::Apu::SpcRead (uint16_t address)
Definition at line 191 of file apu.cc.
References Cycle(), and Read().
SpcWrite()
void yaze::emu::audio::Apu::SpcWrite (uint16_t address, uint8_t data)
Definition at line 196 of file apu.cc.
References Cycle(), and Write().
SpcIdle()
void yaze::emu::audio::Apu::SpcIdle (bool waiting)
Definition at line 201 of file apu.cc.
References Cycle().
Cycle()
void yaze::emu::audio::Apu::Cycle ()
Definition at line 75 of file apu.cc.
References yaze::emu::audio::Dsp::Cycle(), cycles_, dsp_, and timer_.
Referenced by SpcIdle(), SpcRead(), and SpcWrite().
Read()
uint8_t yaze::emu::audio::Apu::Read (uint16_t address)
Definition at line 100 of file apu.cc.
References dsp_, dsp_adr_, in_ports_, ram, yaze::emu::audio::Dsp::Read(), rom_readable_, and timer_.
Referenced by SpcRead().
Write()
void yaze::emu::audio::Apu::Write (uint16_t address, uint8_t data)
Definition at line 137 of file apu.cc.
References dsp_, dsp_adr_, in_ports_, out_ports_, ram, rom_readable_, timer_, and yaze::emu::audio::Dsp::Write().
Referenced by SpcWrite().
dsp()
auto yaze::emu::audio::Apu::dsp () -> Dsp & inline
Definition at line 69 of file apu.h.
References dsp_.
Referenced by yaze::emu::SNES::RunCycle(), and yaze::emu::SNES::SetSamples().
spc700()
auto yaze::emu::audio::Apu::spc700 () -> Spc700 & inline
Definition at line 70 of file apu.h.
References spc700_.
Member Data Documentation
in_ports_
std::array<uint8_t, 6> yaze::emu::audio::Apu::in_ports_
Definition at line 73 of file apu.h.
Referenced by Read(), Reset(), Write(), and yaze::emu::SNES::WriteBBus().
out_ports_
std::array<uint8_t, 4> yaze::emu::audio::Apu::out_ports_
Definition at line 74 of file apu.h.
Referenced by yaze::emu::SNES::ReadBBus(), Reset(), and Write().
ram
std::vector<uint8_t> yaze::emu::audio::Apu::ram = std::vector<uint8_t>(0x10000, 0)
Definition at line 75 of file apu.h.
Referenced by Init(), Read(), Reset(), and Write().
rom_readable_
bool yaze::emu::audio::Apu::rom_readable_ = false private
Definition at line 78 of file apu.h.
Referenced by Read(), Reset(), and Write().
dsp_adr_
uint8_t yaze::emu::audio::Apu::dsp_adr_ = 0 private
Definition at line 80 of file apu.h.
Referenced by Read(), Reset(), and Write().
cycles_
uint32_t yaze::emu::audio::Apu::cycles_ = 0 private
Definition at line 81 of file apu.h.
Referenced by Cycle(), Reset(), and RunCycles().
memory_
MemoryImpl& yaze::emu::audio::Apu::memory_ private
Definition at line 83 of file apu.h.
Referenced by RunCycles().
timer_
std::array<Timer, 3> yaze::emu::audio::Apu::timer_ private
Definition at line 84 of file apu.h.
Referenced by Cycle(), Read(), Reset(), and Write().
callbacks_
ApuCallbacks yaze::emu::audio::Apu::callbacks_ private
Initial value:
= {
      [&](uint16_t adr, uint8_t val) { SpcWrite(adr, val); },
      [&](uint16_t adr) { return SpcRead(adr); },
      [&](bool waiting) { SpcIdle(waiting); },
  }
Definition at line 86 of file apu.h.
dsp_
Dsp yaze::emu::audio::Apu::dsp_ {ram} private
Definition at line 91 of file apu.h.
Referenced by Cycle(), dsp(), Read(), Reset(), and Write().
spc700_
Spc700 yaze::emu::audio::Apu::spc700_ {callbacks_} private
Definition at line 92 of file apu.h.
Referenced by Reset(), RunCycles(), and spc700().
The documentation for this class was generated from the following files:
src/app/emu/audio/apu.h
src/app/emu/audio/apu.cc