yaze: yaze::test::RomDependentTestSuite Class Reference
yaze::test::RomDependentTestSuite Class Reference
#include <rom_dependent_test_suite.h>
Public Member Functions
RomDependentTestSuite ()=default
~RomDependentTestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Private Member Functions
void AddSkippedTest (TestResults &results, const std::string &test_name, const std::string &reason)
void RunRomHeaderValidationTest (TestResults &results, Rom *rom)
void RunRomDataAccessTest (TestResults &results, Rom *rom)
void RunRomGraphicsExtractionTest (TestResults &results, Rom *rom)
void RunRomOverworldLoadingTest (TestResults &results, Rom *rom)
void RunRomSpriteDataTest (TestResults &results, Rom *rom)
void RunRomMusicDataTest (TestResults &results, Rom *rom)
void RunTile16EditorTest (TestResults &results, Rom *rom)
void RunComprehensiveSaveTest (TestResults &results, Rom *rom)
Private Attributes
bool test_header_validation_ = true
bool test_data_access_ = true
bool test_graphics_extraction_ = true
bool test_overworld_loading_ = true
bool test_tile16_editor_ = true
bool test_comprehensive_save_ = true
bool test_advanced_features_ = false
bool test_sprite_data_ = false
bool test_music_data_ = false
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
Definition at line 18 of file rom_dependent_test_suite.h.
Constructor & Destructor Documentation
RomDependentTestSuite()
yaze::test::RomDependentTestSuite::RomDependentTestSuite () default
~RomDependentTestSuite()
yaze::test::RomDependentTestSuite::~RomDependentTestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::RomDependentTestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 23 of file rom_dependent_test_suite.h.
Referenced by AddSkippedTest(), RunComprehensiveSaveTest(), RunRomDataAccessTest(), RunRomGraphicsExtractionTest(), RunRomHeaderValidationTest(), RunRomMusicDataTest(), RunRomOverworldLoadingTest(), RunRomSpriteDataTest(), RunTests(), and RunTile16EditorTest().
GetCategory()
TestCategory yaze::test::RomDependentTestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 24 of file rom_dependent_test_suite.h.
References yaze::test::kIntegration.
Referenced by AddSkippedTest(), RunComprehensiveSaveTest(), RunRomDataAccessTest(), RunRomGraphicsExtractionTest(), RunRomHeaderValidationTest(), RunRomMusicDataTest(), RunRomOverworldLoadingTest(), RunRomSpriteDataTest(), RunTests(), and RunTile16EditorTest().
RunTests()
absl::Status yaze::test::RomDependentTestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 26 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), AddSkippedTest(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), yaze::test::TestManager::GetCurrentRom(), GetName(), yaze::Rom::is_loaded(), yaze::test::kPassed, yaze::test::kSkipped, yaze::test::TestResult::name, RunComprehensiveSaveTest(), RunRomDataAccessTest(), RunRomGraphicsExtractionTest(), RunRomHeaderValidationTest(), RunRomMusicDataTest(), RunRomOverworldLoadingTest(), RunRomSpriteDataTest(), RunTile16EditorTest(), yaze::Rom::size(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_advanced_features_, yaze::test::TestResult::timestamp, and yaze::Rom::title().
DrawConfiguration()
void yaze::test::RomDependentTestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 106 of file rom_dependent_test_suite.h.
References yaze::Rom::filename(), yaze::test::TestManager::Get(), yaze::test::TestManager::GetCurrentRom(), ICON_MD_CHECK_CIRCLE, ICON_MD_STORAGE, ICON_MD_WARNING, yaze::Rom::is_loaded(), yaze::Rom::size(), test_advanced_features_, test_data_access_, test_graphics_extraction_, test_header_validation_, test_music_data_, test_overworld_loading_, test_sprite_data_, and yaze::Rom::title().
AddSkippedTest()
void yaze::test::RomDependentTestSuite::AddSkippedTest (TestResults & results, const std::string & test_name, const std::string & reason) inline private
Definition at line 139 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kSkipped, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunRomHeaderValidationTest()
void yaze::test::RomDependentTestSuite::RunRomHeaderValidationTest (TestResults & results, Rom * rom) inline private
Definition at line 151 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::kSkipped, yaze::test::TestResult::name, yaze::Rom::size(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_header_validation_, yaze::test::TestResult::timestamp, and yaze::Rom::title().
Referenced by RunTests().
RunRomDataAccessTest()
void yaze::test::RomDependentTestSuite::RunRomDataAccessTest (TestResults & results, Rom * rom) inline private
Definition at line 194 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::kSkipped, yaze::test::TestResult::name, yaze::Rom::ReadByte(), yaze::Rom::ReadWord(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_data_access_, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunRomGraphicsExtractionTest()
void yaze::test::RomDependentTestSuite::RunRomGraphicsExtractionTest (TestResults & results, Rom * rom) inline private
Definition at line 245 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::kSkipped, yaze::LoadAllGraphicsData(), yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_graphics_extraction_, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunRomOverworldLoadingTest()
void yaze::test::RomDependentTestSuite::RunRomOverworldLoadingTest (TestResults & results, Rom * rom) inline private
Definition at line 291 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::kSkipped, yaze::zelda3::Overworld::Load(), yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_overworld_loading_, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunRomSpriteDataTest()
void yaze::test::RomDependentTestSuite::RunRomSpriteDataTest (TestResults & results, Rom * rom) inline private
Definition at line 328 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kSkipped, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_sprite_data_, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunRomMusicDataTest()
void yaze::test::RomDependentTestSuite::RunRomMusicDataTest (TestResults & results, Rom * rom) inline private
Definition at line 359 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kSkipped, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_music_data_, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunTile16EditorTest()
void yaze::test::RomDependentTestSuite::RunTile16EditorTest (TestResults & results, Rom * rom) inline private
Definition at line 390 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::gfx::Bitmap::Create(), yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::editor::Tile16Editor::Initialize(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::kSkipped, yaze::test::TestResult::name, yaze::Rom::palette_group(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::gfx::Bitmap::SetPalette(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and yaze::Rom::title().
Referenced by RunTests().
RunComprehensiveSaveTest()
void yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest (TestResults & results, Rom * rom) inline private
Definition at line 455 of file rom_dependent_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::Rom::SaveSettings::backup, yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::Rom::SaveSettings::filename, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::zelda3::Overworld::Load(), yaze::zelda3::Overworld::mutable_overworld_map(), yaze::test::TestResult::name, yaze::Rom::SaveSettings::save_new, yaze::zelda3::Overworld::SaveMapProperties(), yaze::zelda3::Overworld::SaveOverworldMaps(), yaze::Rom::SaveToFile(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and yaze::Rom::title().
Referenced by RunTests().
Member Data Documentation
test_header_validation_
bool yaze::test::RomDependentTestSuite::test_header_validation_ = true private
Definition at line 530 of file rom_dependent_test_suite.h.
Referenced by DrawConfiguration(), and RunRomHeaderValidationTest().
test_data_access_
bool yaze::test::RomDependentTestSuite::test_data_access_ = true private
Definition at line 531 of file rom_dependent_test_suite.h.
Referenced by DrawConfiguration(), and RunRomDataAccessTest().
test_graphics_extraction_
bool yaze::test::RomDependentTestSuite::test_graphics_extraction_ = true private
Definition at line 532 of file rom_dependent_test_suite.h.
Referenced by DrawConfiguration(), and RunRomGraphicsExtractionTest().
test_overworld_loading_
bool yaze::test::RomDependentTestSuite::test_overworld_loading_ = true private
Definition at line 533 of file rom_dependent_test_suite.h.
Referenced by DrawConfiguration(), and RunRomOverworldLoadingTest().
test_tile16_editor_
bool yaze::test::RomDependentTestSuite::test_tile16_editor_ = true private
Definition at line 534 of file rom_dependent_test_suite.h.
test_comprehensive_save_
bool yaze::test::RomDependentTestSuite::test_comprehensive_save_ = true private
Definition at line 535 of file rom_dependent_test_suite.h.
test_advanced_features_
bool yaze::test::RomDependentTestSuite::test_advanced_features_ = false private
Definition at line 536 of file rom_dependent_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_sprite_data_
bool yaze::test::RomDependentTestSuite::test_sprite_data_ = false private
Definition at line 537 of file rom_dependent_test_suite.h.
Referenced by DrawConfiguration(), and RunRomSpriteDataTest().
test_music_data_
bool yaze::test::RomDependentTestSuite::test_music_data_ = false private
Definition at line 538 of file rom_dependent_test_suite.h.
Referenced by DrawConfiguration(), and RunRomMusicDataTest().
The documentation for this class was generated from the following file:
src/app/test/rom_dependent_test_suite.h