yaze: yaze::app::editor::GfxGroupEditor Class Reference
yaze::app::editor::GfxGroupEditor Class Reference
Manage graphics group configurations in a Rom.
#include <gfx_group_editor.h>
Public Member Functions
absl::Status Update ()
void DrawBlocksetViewer (bool sheet_only=false)
void DrawRoomsetViewer ()
void DrawSpritesetViewer (bool sheet_only=false)
void DrawPaletteViewer ()
void SetSelectedBlockset (uint8_t blockset)
void SetSelectedRoomset (uint8_t roomset)
void SetSelectedSpriteset (uint8_t spriteset)
void InitBlockset (gfx::Bitmap *tile16_blockset)
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Private Attributes
int preview_palette_id_ = 0
int last_sheet_id_ = 0
uint8_t selected_blockset_ = 0
uint8_t selected_roomset_ = 0
uint8_t selected_spriteset_ = 0
uint8_t selected_paletteset_ = 0
PaletteEditor palette_editor_
gui::Canvas blockset_canvas_
gui::Canvas roomset_canvas_
gui::Canvas spriteset_canvas_
gfx::SnesPalette palette_
gfx::PaletteGroup palette_group_
gfx::Bitmap * tile16_blockset_bmp_
std::vector< Bytes > tile16_individual_data_
std::vector< gfx::Bitmap > tile16_individual_
gui::BitmapViewer gfx_group_viewer_
zelda3::overworld::Overworld overworld_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
Manage graphics group configurations in a Rom.
Member Function Documentation
Update()
absl::Status yaze::app::editor::GfxGroupEditor::Update ()
References DrawBlocksetViewer(), DrawPaletteViewer(), DrawRoomsetViewer(), DrawSpritesetViewer(), yaze::app::gui::InputHexByte(), yaze::app::SharedRom::rom(), selected_blockset_, selected_paletteset_, selected_roomset_, and selected_spriteset_.
DrawBlocksetViewer()
void yaze::app::editor::GfxGroupEditor::DrawBlocksetViewer (bool sheet_only = false)
References yaze::app::gui::BitmapCanvasPipeline(), blockset_canvas_, yaze::app::gui::InputHexByte(), yaze::app::SharedRom::rom(), and selected_blockset_.
Referenced by yaze::app::editor::DungeonEditor::DrawUsageStats(), and Update().
DrawRoomsetViewer()
void yaze::app::editor::GfxGroupEditor::DrawRoomsetViewer ()
References yaze::app::gui::BitmapCanvasPipeline(), yaze::app::gui::InputHexByte(), yaze::app::SharedRom::rom(), roomset_canvas_, and selected_roomset_.
Referenced by Update().
DrawSpritesetViewer()
void yaze::app::editor::GfxGroupEditor::DrawSpritesetViewer (bool sheet_only = false)
References yaze::app::gui::BitmapCanvasPipeline(), yaze::app::gui::InputHexByte(), yaze::app::SharedRom::rom(), selected_spriteset_, and spriteset_canvas_.
Referenced by yaze::app::editor::DungeonEditor::DrawUsageStats(), and Update().
DrawPaletteViewer()
void yaze::app::editor::GfxGroupEditor::DrawPaletteViewer ()
References yaze::app::gui::InputHexByte(), yaze::app::SharedRom::rom(), and selected_paletteset_.
Referenced by Update().
SetSelectedBlockset()
void yaze::app::editor::GfxGroupEditor::SetSelectedBlockset (uint8_t blockset) inline
References selected_blockset_.
Referenced by yaze::app::editor::DungeonEditor::DrawUsageStats().
SetSelectedRoomset()
void yaze::app::editor::GfxGroupEditor::SetSelectedRoomset (uint8_t roomset) inline
References selected_roomset_.
SetSelectedSpriteset()
void yaze::app::editor::GfxGroupEditor::SetSelectedSpriteset (uint8_t spriteset) inline
References selected_spriteset_.
Referenced by yaze::app::editor::DungeonEditor::DrawUsageStats().
InitBlockset()
void yaze::app::editor::GfxGroupEditor::InitBlockset (gfx::Bitmap * tile16_blockset) inline
References tile16_blockset_bmp_.
Member Data Documentation
preview_palette_id_
int yaze::app::editor::GfxGroupEditor::preview_palette_id_ = 0 private
last_sheet_id_
int yaze::app::editor::GfxGroupEditor::last_sheet_id_ = 0 private
selected_blockset_
uint8_t yaze::app::editor::GfxGroupEditor::selected_blockset_ = 0 private
Referenced by DrawBlocksetViewer(), SetSelectedBlockset(), and Update().
selected_roomset_
uint8_t yaze::app::editor::GfxGroupEditor::selected_roomset_ = 0 private
Referenced by DrawRoomsetViewer(), SetSelectedRoomset(), and Update().
selected_spriteset_
uint8_t yaze::app::editor::GfxGroupEditor::selected_spriteset_ = 0 private
Referenced by DrawSpritesetViewer(), SetSelectedSpriteset(), and Update().
selected_paletteset_
uint8_t yaze::app::editor::GfxGroupEditor::selected_paletteset_ = 0 private
Referenced by DrawPaletteViewer(), and Update().
palette_editor_
PaletteEditor yaze::app::editor::GfxGroupEditor::palette_editor_ private
blockset_canvas_
gui::Canvas yaze::app::editor::GfxGroupEditor::blockset_canvas_ private
Referenced by DrawBlocksetViewer().
roomset_canvas_
gui::Canvas yaze::app::editor::GfxGroupEditor::roomset_canvas_ private
Referenced by DrawRoomsetViewer().
spriteset_canvas_
gui::Canvas yaze::app::editor::GfxGroupEditor::spriteset_canvas_ private
Referenced by DrawSpritesetViewer().
palette_
gfx::SnesPalette yaze::app::editor::GfxGroupEditor::palette_ private
palette_group_
gfx::PaletteGroup yaze::app::editor::GfxGroupEditor::palette_group_ private
tile16_blockset_bmp_
gfx::Bitmap* yaze::app::editor::GfxGroupEditor::tile16_blockset_bmp_ private
Referenced by InitBlockset().
tile16_individual_data_
std::vector<Bytes> yaze::app::editor::GfxGroupEditor::tile16_individual_data_ private
tile16_individual_
std::vector<gfx::Bitmap> yaze::app::editor::GfxGroupEditor::tile16_individual_ private
gfx_group_viewer_
gui::BitmapViewer yaze::app::editor::GfxGroupEditor::gfx_group_viewer_ private
overworld_
zelda3::overworld::Overworld yaze::app::editor::GfxGroupEditor::overworld_ private
The documentation for this class was generated from the following files:
src/app/editor/modules/gfx_group_editor.h
src/app/editor/modules/gfx_group_editor.cc