yaze: yaze::Renderer Class Reference
yaze::Renderer Class Reference
The Renderer class represents the renderer for the Yaze application.
#include <window.h>
Public Member Functions
absl::Status CreateRenderer (SDL_Window *window)
auto renderer () -> SDL_Renderer *
void RenderBitmap (gfx::Bitmap *bitmap)
void UpdateBitmap (gfx::Bitmap *bitmap)
void CreateAndRenderBitmap (int width, int height, int depth, const std::vector< uint8_t > &data, gfx::Bitmap &bitmap, gfx::SnesPalette &palette)
void Clear ()
void Present ()
Static Public Member Functions
static Renderer & Get ()
Private Member Functions
Renderer ()=default
Renderer (const Renderer &)=delete
Renderer & operator= (const Renderer &)=delete
Private Attributes
std::unique_ptr< SDL_Renderer, SDL_Deleter > renderer_
Detailed Description
The Renderer class represents the renderer for the Yaze application.
This class is a singleton that provides functionality for creating and rendering bitmaps to the screen. It also includes methods for updating bitmaps on the screen.
Definition at line 35 of file window.h.
Constructor & Destructor Documentation
Renderer() [1/2]
yaze::core::Renderer::Renderer () private default
Renderer() [2/2]
yaze::core::Renderer::Renderer (const Renderer &) private delete
Member Function Documentation
Get()
static Renderer & yaze::core::Renderer::Get () inline static
Definition at line 37 of file window.h.
Referenced by yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::LoadAllGraphicsData(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::LoadLinkGraphics(), yaze::editor::OverworldEditor::LoadSpriteGraphics(), and yaze::editor::OverworldEditor::RefreshOverworldMap().
CreateRenderer()
absl::Status yaze::core::Renderer::CreateRenderer (SDL_Window * window) inline
Definition at line 42 of file window.h.
renderer()
auto yaze::core::Renderer::renderer () -> SDL_Renderer * inline
Definition at line 54 of file window.h.
RenderBitmap()
void yaze::core::Renderer::RenderBitmap (gfx::Bitmap * bitmap) inline
Definition at line 56 of file window.h.
UpdateBitmap()
void yaze::core::Renderer::UpdateBitmap (gfx::Bitmap * bitmap) inline
Definition at line 60 of file window.h.
CreateAndRenderBitmap()
void yaze::core::Renderer::CreateAndRenderBitmap (int width, int height, int depth, const std::vector< uint8_t > & data, gfx::Bitmap & bitmap, gfx::SnesPalette & palette) inline
Definition at line 64 of file window.h.
Clear()
void yaze::core::Renderer::Clear () inline
Definition at line 72 of file window.h.
Present()
void yaze::core::Renderer::Present () inline
Definition at line 77 of file window.h.
operator=()
Renderer & yaze::core::Renderer::operator= (const Renderer &) private delete
Member Data Documentation
renderer_
std::unique_ptr<SDL_Renderer, SDL_Deleter> yaze::core::Renderer::renderer_ private
Definition at line 82 of file window.h.
The documentation for this class was generated from the following file:
src/app/core/window.h