yaze: yaze::RecentFilesManager Class Reference
yaze::RecentFilesManager Class Reference
#include <project.h>
Public Member Functions
RecentFilesManager ()
RecentFilesManager (const std::string &filename)
void AddFile (const std::string &file_path)
void Save ()
void Load ()
const std::vector< std::string > & GetRecentFiles () const
Private Attributes
std::string filename_
std::vector< std::string > recent_files_
Detailed Description
Definition at line 83 of file project.h.
Constructor & Destructor Documentation
RecentFilesManager() [1/2]
yaze::RecentFilesManager::RecentFilesManager () inline
Definition at line 85 of file project.h.
References yaze::kRecentFilesFilename, and RecentFilesManager().
Referenced by RecentFilesManager().
RecentFilesManager() [2/2]
yaze::RecentFilesManager::RecentFilesManager (const std::string & filename) inline
Definition at line 86 of file project.h.
References filename_.
Member Function Documentation
AddFile()
void yaze::RecentFilesManager::AddFile (const std::string & file_path) inline
Definition at line 88 of file project.h.
References recent_files_.
Referenced by yaze::editor::EditorManager::LoadRom(), and yaze::editor::EditorManager::OpenProject().
Save()
void yaze::RecentFilesManager::Save () inline
Definition at line 96 of file project.h.
References filename_, and recent_files_.
Referenced by yaze::editor::EditorManager::LoadRom(), and yaze::editor::EditorManager::OpenProject().
Load()
void yaze::RecentFilesManager::Load () inline
Definition at line 107 of file project.h.
References filename_, and recent_files_.
Referenced by yaze::editor::EditorManager::DrawMenuContent(), yaze::editor::EditorManager::Initialize(), yaze::editor::EditorManager::LoadRom(), yaze::editor::EditorManager::ManageKeyboardShortcuts(), and yaze::editor::EditorManager::OpenProject().
GetRecentFiles()
const std::vector< std::string > & yaze::RecentFilesManager::GetRecentFiles () const inline
Definition at line 122 of file project.h.
References recent_files_.
Referenced by yaze::editor::EditorManager::DrawMenuContent(), yaze::editor::EditorManager::Initialize(), and yaze::editor::EditorManager::ManageKeyboardShortcuts().
Member Data Documentation
filename_
std::string yaze::RecentFilesManager::filename_ private
Definition at line 127 of file project.h.
Referenced by Load(), RecentFilesManager(), and Save().
recent_files_
std::vector<std::string> yaze::RecentFilesManager::recent_files_ private
Definition at line 128 of file project.h.
Referenced by AddFile(), GetRecentFiles(), Load(), and Save().
The documentation for this class was generated from the following file:
src/app/core/project.h