yaze: yaze::cli::ApplyPatch Class Reference
yaze::cli::ApplyPatch Class Reference
#include <command_handler.h>
Public Member Functions
absl::Status handle (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
app::Rom rom_
Detailed Description
Definition at line 63 of file command_handler.h.
Member Function Documentation
handle()
absl::Status yaze::cli::ApplyPatch::handle (const std::vector< std::string > & arg_vec) inline override virtual
Implements yaze::cli::CommandHandler.
Definition at line 65 of file command_handler.h.
References yaze::app::core::ApplyBpsPatch(), yaze::app::Rom::LoadFromFile(), RETURN_IF_ERROR, yaze::cli::CommandHandler::rom_, yaze::app::Rom::size(), and yaze::app::Rom::vector().
The documentation for this class was generated from the following file:
src/cli/command_handler.h