yaze: yaze::editor::MessageEditor Class Reference
yaze::editor::MessageEditor Class Reference
#include <message_editor.h>
Classes
struct TextBox
Public Member Functions
MessageEditor ()
absl::Status Initialize ()
absl::Status Update () override
void DrawMessageList ()
void DrawCurrentMessage ()
void DrawTextCommands ()
void DrawDictionary ()
void ReadAllTextDataV2 ()
void ReadAllTextData ()
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
absl::Status Save ()
void Delete ()
void SelectAll ()
DictionaryEntry GetDictionaryFromID (uint8_t value)
void DrawTileToPreview (int x, int y, int srcx, int srcy, int pal, int sizex=1, int sizey=1)
void DrawCharacterToPreview (char c)
void DrawCharacterToPreview (const std::vector< uint8_t > &text)
void DrawStringToPreview (std::string str)
void DrawMessagePreview ()
std::string DisplayTextOverflowError (int pos, bool bank)
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
EditorType type () const
Public Member Functions inherited from yaze::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Private Attributes
bool skip_next = false
bool data_loaded_ = false
int text_line_ = 0
int text_position_ = 0
int shown_lines_ = 0
uint8_t width_array [kWidthArraySize]
std::string search_text_ = ""
std::vector< uint8_t > font_gfx16_data_
std::vector< uint8_t > current_font_gfx16_data_
std::vector< std::string > parsed_messages_
std::vector< MessageData > list_of_texts_
std::vector< DictionaryEntry > all_dictionaries_
MessageData current_message_
gfx::Bitmap font_gfx_bitmap_
gfx::Bitmap current_font_gfx16_bitmap_
gfx::SnesPalette font_preview_colors_
gui::Canvas font_gfx_canvas_ {"##FontGfxCanvas", ImVec2(128, 128)}
gui::Canvas current_font_gfx16_canvas_
TextBox message_text_box_
Additional Inherited Members
Static Public Attributes inherited from yaze::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Protected Attributes inherited from yaze::editor::Editor
EditorType type_
EditorContext context_
Detailed Description
Definition at line 38 of file message_editor.h.
Constructor & Destructor Documentation
MessageEditor()
yaze::editor::MessageEditor::MessageEditor () inline
Definition at line 40 of file message_editor.h.
References yaze::editor::kMessage, and yaze::editor::Editor::type_.
Member Function Documentation
Initialize()
absl::Status yaze::editor::MessageEditor::Initialize ()
Definition at line 47 of file message_editor.cc.
References yaze::gfx::SnesPalette::AddColor(), all_dictionaries_, yaze::editor::BuildDictionaryEntries(), current_font_gfx16_bitmap_, current_font_gfx16_data_, yaze::editor::DICTOFF, DrawMessagePreview(), yaze::editor::TextElement::Empty(), yaze::editor::FindMatchingCommand(), font_gfx16_data_, font_gfx_bitmap_, font_preview_colors_, yaze::editor::TextElement::GenericToken, GetDictionaryFromID(), yaze::core::Renderer::GetInstance(), yaze::editor::TextElement::ID, yaze::editor::kCharactersWidth, yaze::editor::kCurrentMessageHeight, yaze::editor::kCurrentMessageWidth, yaze::editor::kFontGfxMessageDepth, yaze::editor::kFontGfxMessageSize, yaze::editor::kGfxFont, yaze::editor::kLine2, yaze::editor::kLine3, yaze::editor::kScrollVertical, yaze::editor::kWidthArraySize, list_of_texts_, yaze::gfx::SnesPalette::mutable_color(), yaze::gfx::Bitmap::mutable_palette(), yaze::gfx::Bitmap::palette(), parsed_messages_, ReadAllTextDataV2(), RETURN_IF_ERROR, yaze::SharedRom::rom(), yaze::gfx::SnesPalette::size(), yaze::gfx::SnesTo8bppSheet(), yaze::core::UppercaseHexLong(), and width_array.
Referenced by Update().
Update()
absl::Status yaze::editor::MessageEditor::Update () override virtual
Implements yaze::editor::Editor.
Definition at line 131 of file message_editor.cc.
References current_message_, data_loaded_, DrawCurrentMessage(), DrawDictionary(), DrawMessageList(), DrawTextCommands(), Initialize(), yaze::editor::kDictTableFlags, list_of_texts_, RETURN_IF_ERROR, and yaze::SharedRom::rom().
Referenced by yaze::editor::EditorManager::ManageActiveEditors().
DrawMessageList()
void yaze::editor::MessageEditor::DrawMessageList ()
Definition at line 164 of file message_editor.cc.
References current_message_, DrawMessagePreview(), yaze::editor::kMessageTableFlags, list_of_texts_, parsed_messages_, yaze::core::UppercaseHexLong(), and yaze::core::UppercaseHexWord().
Referenced by Update().
DrawCurrentMessage()
void yaze::editor::MessageEditor::DrawCurrentMessage ()
Definition at line 194 of file message_editor.cc.
References yaze::gui::BeginPadding(), current_font_gfx16_bitmap_, current_font_gfx16_canvas_, current_message_, yaze::editor::MessageData::Data, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), DrawMessagePreview(), yaze::gui::Canvas::DrawOverlay(), yaze::gui::EndPadding(), font_gfx_bitmap_, font_gfx_canvas_, yaze::core::Renderer::GetInstance(), yaze::editor::MessageData::ID, message_text_box_, parsed_messages_, yaze::editor::ParseMessageToData(), yaze::editor::MessageEditor::TextBox::text, and yaze::core::Renderer::UpdateBitmap().
Referenced by Update().
DrawTextCommands()
void yaze::editor::MessageEditor::DrawTextCommands ()
Definition at line 232 of file message_editor.cc.
Referenced by Update().
DrawDictionary()
void yaze::editor::MessageEditor::DrawDictionary ()
Definition at line 246 of file message_editor.cc.
References all_dictionaries_, yaze::editor::kDictTableFlags, and yaze::core::UppercaseHexWord().
Referenced by Update().
ReadAllTextDataV2()
void yaze::editor::MessageEditor::ReadAllTextDataV2 ()
Todo
Fix the command parsing.
Definition at line 267 of file message_editor.cc.
References yaze::editor::BANKToken, yaze::editor::DICTIONARYTOKEN, yaze::editor::TextElement::Empty(), yaze::editor::FindDictionaryEntry(), yaze::editor::FindMatchingCommand(), yaze::editor::FindMatchingSpecial(), yaze::core::Get24LocalFromPC(), yaze::editor::TextElement::GetParameterizedToken(), yaze::editor::TextElement::HasArgument, yaze::editor::kMessageTerminator, yaze::editor::kPointersDictionaries, yaze::editor::kTextData, yaze::editor::kTextData2, list_of_texts_, yaze::editor::ParseTextDataByte(), yaze::SharedRom::rom(), yaze::editor::TextElement::Token, and yaze::core::UppercaseHexWord().
Referenced by Initialize().
ReadAllTextData()
void yaze::editor::MessageEditor::ReadAllTextData ()
Definition at line 363 of file message_editor.cc.
References yaze::editor::BANKToken, yaze::editor::DICTIONARYTOKEN, yaze::editor::TextElement::Empty(), yaze::editor::FindDictionaryEntry(), yaze::editor::FindMatchingCommand(), yaze::editor::FindMatchingSpecial(), yaze::core::Get24LocalFromPC(), yaze::editor::TextElement::GetParameterizedToken(), yaze::editor::TextElement::HasArgument, yaze::editor::kMessageTerminator, yaze::editor::kPointersDictionaries, yaze::editor::kTextData, yaze::editor::kTextData2, list_of_texts_, yaze::editor::ParseTextDataByte(), yaze::SharedRom::rom(), yaze::editor::TextElement::Token, and yaze::core::UppercaseHexWord().
Cut()
absl::Status yaze::editor::MessageEditor::Cut () override virtual
Implements yaze::editor::Editor.
Definition at line 586 of file message_editor.cc.
References yaze::editor::MessageEditor::TextBox::Cut(), message_text_box_, and yaze::editor::MessageEditor::TextBox::text.
Copy()
absl::Status yaze::editor::MessageEditor::Copy () override virtual
Implements yaze::editor::Editor.
Definition at line 604 of file message_editor.cc.
References yaze::editor::MessageEditor::TextBox::Copy(), message_text_box_, and yaze::editor::MessageEditor::TextBox::selection_length.
Paste()
absl::Status yaze::editor::MessageEditor::Paste () override virtual
Implements yaze::editor::Editor.
Definition at line 595 of file message_editor.cc.
References message_text_box_, and yaze::editor::MessageEditor::TextBox::Paste().
Undo()
absl::Status yaze::editor::MessageEditor::Undo () override virtual
Implements yaze::editor::Editor.
Definition at line 613 of file message_editor.cc.
References yaze::editor::MessageEditor::TextBox::can_undo, yaze::editor::MessageEditor::TextBox::clearUndo(), message_text_box_, and yaze::editor::MessageEditor::TextBox::Undo().
Redo()
absl::Status yaze::editor::MessageEditor::Redo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 56 of file message_editor.h.
Find()
absl::Status yaze::editor::MessageEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 59 of file message_editor.h.
Save()
absl::Status yaze::editor::MessageEditor::Save ()
Definition at line 625 of file message_editor.cc.
References DisplayTextOverflowError(), yaze::editor::kBlockTerminator, yaze::editor::kCharactersWidth, yaze::editor::kMessageTerminator, yaze::editor::kTextData, yaze::editor::kTextData2, yaze::editor::kTextData2End, yaze::editor::kTextDataEnd, list_of_texts_, RETURN_IF_ERROR, yaze::SharedRom::rom(), and width_array.
Delete()
void yaze::editor::MessageEditor::Delete ()
Definition at line 683 of file message_editor.cc.
References yaze::editor::MessageEditor::TextBox::clear(), message_text_box_, and yaze::editor::MessageEditor::TextBox::selection_length.
SelectAll()
void yaze::editor::MessageEditor::SelectAll ()
Definition at line 691 of file message_editor.cc.
References yaze::editor::MessageEditor::TextBox::Focus(), message_text_box_, yaze::editor::MessageEditor::TextBox::SelectAll(), and yaze::editor::MessageEditor::TextBox::selection_length.
GetDictionaryFromID()
DictionaryEntry yaze::editor::MessageEditor::GetDictionaryFromID (uint8_t value)
Definition at line 473 of file message_editor.cc.
References all_dictionaries_.
Referenced by DrawCharacterToPreview(), and Initialize().
DrawTileToPreview()
void yaze::editor::MessageEditor::DrawTileToPreview (int x, int y, int srcx, int srcy, int pal, int sizex = 1, int sizey = 1)
Definition at line 480 of file message_editor.cc.
References current_font_gfx16_data_, and font_gfx16_data_.
Referenced by DrawCharacterToPreview().
DrawCharacterToPreview() [1/2]
void yaze::editor::MessageEditor::DrawCharacterToPreview (char c)
Definition at line 518 of file message_editor.cc.
References DrawCharacterToPreview(), and yaze::editor::FindMatchingCharacter().
Referenced by DrawCharacterToPreview(), DrawCharacterToPreview(), DrawMessagePreview(), and DrawStringToPreview().
DrawCharacterToPreview() [2/2]
void yaze::editor::MessageEditor::DrawCharacterToPreview (const std::vector< uint8_t > & text)
Definition at line 522 of file message_editor.cc.
References yaze::editor::DICTOFF, DrawCharacterToPreview(), DrawStringToPreview(), DrawTileToPreview(), GetDictionaryFromID(), yaze::editor::kLine1, yaze::editor::kLine2, yaze::editor::kLine3, yaze::editor::kScrollVertical, skip_next, text_line_, text_position_, and width_array.
DrawStringToPreview()
void yaze::editor::MessageEditor::DrawStringToPreview (std::string str)
Definition at line 512 of file message_editor.cc.
References DrawCharacterToPreview().
Referenced by DrawCharacterToPreview().
DrawMessagePreview()
void yaze::editor::MessageEditor::DrawMessagePreview ()
Definition at line 575 of file message_editor.cc.
References current_font_gfx16_data_, current_message_, yaze::editor::MessageData::Data, DrawCharacterToPreview(), shown_lines_, text_line_, and text_position_.
Referenced by DrawCurrentMessage(), DrawMessageList(), and Initialize().
DisplayTextOverflowError()
std::string yaze::editor::MessageEditor::DisplayTextOverflowError (int pos, bool bank)
Definition at line 670 of file message_editor.cc.
References yaze::editor::kTextData, yaze::editor::kTextData2, yaze::editor::kTextData2End, and yaze::editor::kTextDataEnd.
Referenced by Save().
Member Data Documentation
skip_next
bool yaze::editor::MessageEditor::skip_next = false private
Definition at line 77 of file message_editor.h.
Referenced by DrawCharacterToPreview().
data_loaded_
bool yaze::editor::MessageEditor::data_loaded_ = false private
Definition at line 78 of file message_editor.h.
Referenced by Update().
text_line_
int yaze::editor::MessageEditor::text_line_ = 0 private
Definition at line 80 of file message_editor.h.
Referenced by DrawCharacterToPreview(), and DrawMessagePreview().
text_position_
int yaze::editor::MessageEditor::text_position_ = 0 private
Definition at line 81 of file message_editor.h.
Referenced by DrawCharacterToPreview(), and DrawMessagePreview().
shown_lines_
int yaze::editor::MessageEditor::shown_lines_ = 0 private
Definition at line 82 of file message_editor.h.
Referenced by DrawMessagePreview().
width_array
uint8_t yaze::editor::MessageEditor::width_array[kWidthArraySize] private
Definition at line 84 of file message_editor.h.
Referenced by DrawCharacterToPreview(), Initialize(), and Save().
search_text_
std::string yaze::editor::MessageEditor::search_text_ = "" private
Definition at line 86 of file message_editor.h.
font_gfx16_data_
std::vector<uint8_t> yaze::editor::MessageEditor::font_gfx16_data_ private
Definition at line 88 of file message_editor.h.
Referenced by DrawTileToPreview(), and Initialize().
current_font_gfx16_data_
std::vector<uint8_t> yaze::editor::MessageEditor::current_font_gfx16_data_ private
Definition at line 89 of file message_editor.h.
Referenced by DrawMessagePreview(), DrawTileToPreview(), and Initialize().
parsed_messages_
std::vector<std::string> yaze::editor::MessageEditor::parsed_messages_ private
Definition at line 90 of file message_editor.h.
Referenced by DrawCurrentMessage(), DrawMessageList(), and Initialize().
list_of_texts_
std::vector<MessageData> yaze::editor::MessageEditor::list_of_texts_ private
Definition at line 92 of file message_editor.h.
Referenced by DrawMessageList(), Initialize(), ReadAllTextData(), ReadAllTextDataV2(), Save(), and Update().
all_dictionaries_
std::vector<DictionaryEntry> yaze::editor::MessageEditor::all_dictionaries_ private
Definition at line 94 of file message_editor.h.
Referenced by DrawDictionary(), GetDictionaryFromID(), and Initialize().
current_message_
MessageData yaze::editor::MessageEditor::current_message_ private
Definition at line 96 of file message_editor.h.
Referenced by DrawCurrentMessage(), DrawMessageList(), DrawMessagePreview(), and Update().
font_gfx_bitmap_
gfx::Bitmap yaze::editor::MessageEditor::font_gfx_bitmap_ private
Definition at line 98 of file message_editor.h.
Referenced by DrawCurrentMessage(), and Initialize().
current_font_gfx16_bitmap_
gfx::Bitmap yaze::editor::MessageEditor::current_font_gfx16_bitmap_ private
Definition at line 99 of file message_editor.h.
Referenced by DrawCurrentMessage(), and Initialize().
font_preview_colors_
gfx::SnesPalette yaze::editor::MessageEditor::font_preview_colors_ private
Definition at line 100 of file message_editor.h.
Referenced by Initialize().
font_gfx_canvas_
gui::Canvas yaze::editor::MessageEditor::font_gfx_canvas_ {"##FontGfxCanvas", ImVec2(128, 128)} private
Definition at line 102 of file message_editor.h.
Referenced by DrawCurrentMessage().
current_font_gfx16_canvas_
gui::Canvas yaze::editor::MessageEditor::current_font_gfx16_canvas_ private
Initial value:
{"##CurrentMessageGfx",
                                         ImVec2(172, 4096)}
Definition at line 103 of file message_editor.h.
Referenced by DrawCurrentMessage().
message_text_box_
TextBox yaze::editor::MessageEditor::message_text_box_ private
Definition at line 161 of file message_editor.h.
Referenced by Copy(), Cut(), Delete(), DrawCurrentMessage(), Paste(), SelectAll(), and Undo().
The documentation for this class was generated from the following files:
src/app/editor/message/message_editor.h
src/app/editor/message/message_editor.cc