yaze: yaze::app::Rom Class Reference
yaze::app::Rom Class Reference
The ROM class is used to load, save, and modify ROM data.
#include <rom.h>
Classes
struct WriteAction
Public Member Functions
absl::StatusOr< Bytes > Load2BppGraphics ()
Loads 2bpp graphics from ROM data.
absl::Status LoadLinkGraphics ()
Loads the players 4bpp graphics sheet from ROM data.
absl::Status LoadAllGraphicsData ()
This function iterates over all graphics sheets in the ROM and loads them into memory. Depending on the sheet's index, it may be uncompressed or compressed using the LC-LZ2 algorithm. The uncompressed sheets are 3 bits per pixel (BPP), while the compressed sheets are 4 BPP. The loaded graphics data is converted to 8 BPP and stored in a bitmap.
absl::Status LoadAllPalettes ()
Loads all the palettes for the game.
absl::Status LoadFromFile (const absl::string_view &filename, bool z3_load=true)
absl::Status LoadFromPointer (uchar *data, size_t length)
absl::Status LoadFromBytes (const Bytes &data)
absl::Status SaveToFile (bool backup, bool save_new=false, std::string filename="")
Saves the ROM data to a file.
absl::Status SavePalette (int index, const std::string &group_name, gfx::SnesPalette &palette)
absl::Status SaveAllPalettes ()
Saves all palettes in the ROM.
absl::Status UpdatePaletteColor (const std::string &group_name, size_t palette_index, size_t colorIndex, const gfx::SnesColor &newColor)
Updates a color in a specified palette group.
absl::StatusOr< uint8_t > ReadByte (int offset)
absl::StatusOr< uint16_t > ReadWord (int offset)
uint16_t toint16 (int offset)
absl::StatusOr< uint32_t > ReadLong (int offset)
absl::StatusOr< std::vector< uint8_t > > ReadByteVector (uint32_t offset, uint32_t length)
absl::StatusOr< gfx::Tile16 > ReadTile16 (uint32_t tile16_id)
absl::Status WriteTile16 (int tile16_id, const gfx::Tile16 &tile)
absl::Status Write (int addr, int value)
absl::Status WriteByte (int addr, uint8_t value)
absl::Status WriteWord (int addr, uint16_t value)
absl::Status WriteShort (int addr, uint16_t value)
absl::Status WriteLong (uint32_t addr, uint32_t value)
absl::Status WriteVector (int addr, std::vector< uint8_t > data)
absl::Status WriteColor (uint32_t address, const gfx::SnesColor &color)
template<typename... Args>
absl::Status WriteTransaction (Args... args)
template<typename T , typename... Args>
absl::Status ReadTransaction (T &var, int address, Args &&... args)
void Expand (int size)
absl::Status Reload ()
absl::Status Close ()
void QueueChanges (std::function< void()> const &function)
VersionConstants version_constants () const
int GetGraphicsAddress (const uchar *data, uint8_t addr) const
auto palette_group ()
auto mutable_palette_group ()
auto dungeon_palette (int i)
auto mutable_dungeon_palette (int i)
Bytes graphics_buffer () const
gfx::BitmapTable graphics_bin () const
gfx::Bitmap * mutable_graphics_sheet (int index)
auto bitmap_manager ()
auto mutable_bitmap_manager ()
auto link_graphics ()
auto title () const
auto size () const
auto begin ()
auto end ()
auto data ()
auto push_back (uint8_t byte)
auto vector () const
auto filename () const
auto is_loaded () const
auto version () const
uint8_t & operator[] (int i)
uint8_t & operator+ (int i)
const uint8_t * operator& ()
void SetupRenderer (std::shared_ptr< SDL_Renderer > renderer)
absl::Status CreateAndRenderBitmap (int width, int height, int depth, const Bytes &data, gfx::Bitmap &bitmap, gfx::SnesPalette &palette)
void RenderBitmap (gfx::Bitmap *bitmap)
Used to render a bitmap to the screen.
void UpdateBitmap (gfx::Bitmap *bitmap, bool use_sdl_update=false)
Used to update a bitmap on the screen.
void LoadGfxGroups ()
bool SaveGroupsToROM ()
auto resource_label ()
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
Public Attributes
std::vector< std::vector< uint8_t > > main_blockset_ids
std::vector< std::vector< uint8_t > > room_blockset_ids
std::vector< std::vector< uint8_t > > spriteset_ids
std::vector< std::vector< uint8_t > > paletteset_ids
Private Member Functions
absl::Status WriteHelper (const WriteAction &action)
template<typename T >
absl::Status ReadHelper (T &var, int address)
Private Attributes
long size_ = 0
bool is_loaded_ = false
bool has_header_ = false
uchar title_ [21] = "ROM Not Loaded"
std::string filename_
Bytes rom_data_
Bytes graphics_buffer_
Z3_Version version_ = Z3_Version::US
gfx::BitmapTable graphics_bin_
gfx::BitmapManager graphics_manager_
gfx::BitmapTable link_graphics_
gfx::SnesPalette link_palette_
gfx::PaletteGroupMap palette_groups_
core::ResourceLabelManager resource_label_manager_
std::stack< std::function< void()> > changes_
std::shared_ptr< SDL_Renderer > renderer_
Detailed Description
The ROM class is used to load, save, and modify ROM data.
Member Function Documentation
Load2BppGraphics()
absl::StatusOr< Bytes > yaze::app::Rom::Load2BppGraphics ()
Loads 2bpp graphics from ROM data.
This function loads 2bpp graphics from ROM data by iterating over a list of sheet IDs, decompressing the sheet data, converting it to 8bpp format, and appending the converted sheet data to a byte vector.
References ASSIGN_OR_RETURN, data(), yaze::app::gfx::lc_lz2::DecompressV2(), GetGraphicsAddress(), yaze::app::gfx::SnesTo8bppSheet(), and vector().
LoadLinkGraphics()
absl::Status yaze::app::Rom::LoadLinkGraphics ()
Loads the players 4bpp graphics sheet from ROM data.
References yaze::app::gfx::PaletteGroupMap::armors, ASSIGN_OR_RETURN, yaze::app::gfx::Convert4bppTo3bpp(), yaze::app::core::kTilesheetDepth, yaze::app::core::kTilesheetHeight, yaze::app::core::kTilesheetWidth, link_graphics_, link_palette_, palette_groups_, ReadByteVector(), RenderBitmap(), RETURN_IF_ERROR, yaze::app::gfx::SnesTo8bppSheet(), and vector().
LoadAllGraphicsData()
absl::Status yaze::app::Rom::LoadAllGraphicsData ()
This function iterates over all graphics sheets in the ROM and loads them into memory. Depending on the sheet's index, it may be uncompressed or compressed using the LC-LZ2 algorithm. The uncompressed sheets are 3 bits per pixel (BPP), while the compressed sheets are 4 BPP. The loaded graphics data is converted to 8 BPP and stored in a bitmap.
The graphics sheets are divided into the following ranges:
Range Compression Type Decompressed Size Number of Chars
0-112 Compressed 3bpp BGR 0x600 chars Decompressed each
113-114 Compressed 2bpp 0x800 chars Decompressed each
115-126 Uncompressed 3bpp sprites 0x600 chars Each
127-217 Compressed 3bpp sprites 0x600 chars Decompressed each
218-222 Compressed 2bpp 0x800 chars Decompressed each
References ASSIGN_OR_RETURN, data(), yaze::app::gfx::lc_lz2::DecompressV2(), yaze::app::gfx::PaletteGroupMap::dungeon_main, yaze::app::core::ExperimentFlags::flags(), GetGraphicsAddress(), yaze::app::gfx::PaletteGroupMap::global_sprites, graphics_bin_, graphics_buffer_, graphics_manager_, yaze::app::core::kTilesheetDepth, yaze::app::core::kTilesheetHeight, yaze::app::core::kTilesheetWidth, yaze::app::gfx::BitmapManager::LoadBitmap(), palette_groups_, renderer_, RETURN_IF_ERROR, rom_data_, size(), yaze::app::gfx::SnesTo8bppSheet(), yaze::app::core::Uncompressed3BPPSize, and vector().
Referenced by yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
LoadAllPalettes()
absl::Status yaze::app::Rom::LoadAllPalettes ()
Loads all the palettes for the game.
This function loads all the palettes for the game, including overworld, HUD, armor, swords, shields, sprites, dungeon, grass, and 3D object palettes. It also adds the loaded palettes to their respective palette groups.
References yaze::app::palette_group_internal::Load3DObjectPalettes(), yaze::app::palette_group_internal::LoadArmorPalettes(), yaze::app::palette_group_internal::LoadDungeonMainPalettes(), yaze::app::palette_group_internal::LoadGlobalSpritePalettes(), yaze::app::palette_group_internal::LoadGrassColors(), yaze::app::palette_group_internal::LoadHUDPalettes(), yaze::app::palette_group_internal::LoadOverworldAnimatedPalettes(), yaze::app::palette_group_internal::LoadOverworldAuxiliaryPalettes(), yaze::app::palette_group_internal::LoadOverworldMainPalettes(), yaze::app::palette_group_internal::LoadOverworldMiniMapPalettes(), yaze::app::palette_group_internal::LoadShieldPalettes(), yaze::app::palette_group_internal::LoadSpriteAux1Palettes(), yaze::app::palette_group_internal::LoadSpriteAux2Palettes(), yaze::app::palette_group_internal::LoadSpriteAux3Palettes(), yaze::app::palette_group_internal::LoadSwordPalettes(), palette_groups_, RETURN_IF_ERROR, and rom_data_.
Referenced by LoadFromFile().
LoadFromFile()
absl::Status yaze::app::Rom::LoadFromFile (const absl::string_view & filename, bool z3_load = true)
Load ROM data from a file.
Parameters
filename The name of the file to load.
z3_load Whether to load data specific to Zelda 3.
References filename(), filename_, has_header_, is_loaded_, yaze::app::JP, LoadAllPalettes(), LoadGfxGroups(), yaze::app::core::ResourceLabelManager::LoadLabels(), resource_label_manager_, RETURN_IF_ERROR, rom_data_, size_, title_, yaze::app::US, vector(), and version_.
Referenced by yaze::app::editor::GraphicsEditor::DrawFileImport(), yaze::app::editor::GraphicsEditor::DrawObjImport(), yaze::app::editor::GraphicsEditor::DrawPaletteControls(), yaze::app::editor::GraphicsEditor::DrawTilemapImport(), yaze::app::editor::MasterEditor::DrawViewMenu(), yaze::cli::ApplyPatch::handle(), yaze::cli::Open::handle(), yaze::cli::Backup::handle(), yaze::cli::ReadFromRom::handle(), yaze::cli::Tile16Transfer::handle(), yaze::cli::Expand::handle(), yaze::cli::Emulator::handle(), Reload(), and yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
LoadFromPointer()
absl::Status yaze::app::Rom::LoadFromPointer (uchar * data, size_t length)
References data(), and rom_data_.
Referenced by yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectCompressOk(), and yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectDecompressOk().
LoadFromBytes()
absl::Status yaze::app::Rom::LoadFromBytes (const Bytes & data)
References data(), is_loaded_, rom_data_, and size_.
Referenced by yaze::app::editor::GraphicsEditor::DrawClipboardImport(), yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk(), yaze::app::gfx::lc_lz2::ValidateCompressionResult(), and yaze::app::gfx::lc_lz2::ValidateCompressionResultV3().
SaveToFile()
absl::Status yaze::app::Rom::SaveToFile (bool backup, bool save_new = false, std::string filename = "")
Saves the ROM data to a file.
Parameters
backup If true, creates a backup file with timestamp in its name
filename The name of the file to save the ROM data to
Returns
absl::Status Returns an OK status if the save was successful, otherwise returns an error status
References filename(), filename_, yaze::app::core::ExperimentFlags::flags(), rom_data_, SaveAllPalettes(), and vector().
Referenced by yaze::cli::Backup::handle(), and yaze::cli::Tile16Transfer::handle().
SavePalette()
absl::Status yaze::app::Rom::SavePalette (int index, const std::string & group_name, gfx::SnesPalette & palette)
Saves the given palette to the ROM if any of its colors have been modified.
Parameters
index The index of the palette to save.
group_name The name of the group containing the palette.
palette The palette to save.
References yaze::app::gfx::GetPaletteAddress(), RETURN_IF_ERROR, yaze::app::gfx::SnesPalette::size(), vector(), and WriteColor().
Referenced by SaveAllPalettes().
SaveAllPalettes()
absl::Status yaze::app::Rom::SaveAllPalettes ()
Saves all palettes in the ROM.
This function iterates through all palette groups and all palettes in each group, and saves each palette using the SavePalette() function.
References yaze::app::gfx::PaletteGroupMap::for_each(), palette_groups_, SavePalette(), and vector().
Referenced by SaveToFile().
UpdatePaletteColor()
absl::Status yaze::app::Rom::UpdatePaletteColor (const std::string & group_name, size_t palette_index, size_t colorIndex, const gfx::SnesColor & newColor)
Updates a color in a specified palette group.
This function updates the color at the specified colorIndex in the palette at palette_index within the palette group with the given group_name. If the group, palette, or color indices are invalid, an error is returned.
Parameters
group_name The name of the palette group to update.
palette_index The index of the palette within the group to update.
colorIndex The index of the color within the palette to update.
newColor The new color value to set.
Returns
An absl::Status indicating whether the update was successful. Returns absl::OkStatus() if successful, or an error status if the group, palette, or color indices are invalid.
ReadByte()
absl::StatusOr< uint8_t > yaze::app::Rom::ReadByte (int offset) inline
References rom_data_.
Referenced by yaze::cli::ReadFromRom::handle(), and ReadHelper().
ReadWord()
absl::StatusOr< uint16_t > yaze::app::Rom::ReadWord (int offset) inline
References rom_data_, and vector().
Referenced by yaze::app::editor::context::EntranceContext::LoadEntranceTileTypes(), ReadHelper(), and ReadTile16().
toint16()
uint16_t yaze::app::Rom::toint16 (int offset) inline
References rom_data_, and vector().
Referenced by yaze::app::zelda3::overworld::OverworldMap::LoadAreaInfo().
ReadLong()
absl::StatusOr< uint32_t > yaze::app::Rom::ReadLong (int offset) inline
References rom_data_, and vector().
ReadByteVector()
absl::StatusOr< std::vector< uint8_t > > yaze::app::Rom::ReadByteVector (uint32_t offset, uint32_t length) inline
References rom_data_, and vector().
Referenced by yaze::cli::ReadFromRom::handle(), LoadLinkGraphics(), and ReadHelper().
ReadTile16()
absl::StatusOr< gfx::Tile16 > yaze::app::Rom::ReadTile16 (uint32_t tile16_id) inline
References ASSIGN_OR_RETURN, ReadWord(), yaze::app::gfx::Tile16::tile0_, vector(), and yaze::app::gfx::WordToTileInfo().
Referenced by yaze::cli::Tile16Transfer::handle().
WriteTile16()
absl::Status yaze::app::Rom::WriteTile16 (int tile16_id, const gfx::Tile16 & tile) inline
References RETURN_IF_ERROR, yaze::app::gfx::Tile16::tile0_, yaze::app::gfx::Tile16::tile1_, yaze::app::gfx::Tile16::tile2_, yaze::app::gfx::Tile16::tile3_, yaze::app::gfx::TileInfoToWord(), vector(), and WriteShort().
Referenced by yaze::cli::Tile16Transfer::handle().
Write()
absl::Status yaze::app::Rom::Write (int addr, int value) inline
References rom_data_, and vector().
Referenced by yaze::app::zelda3::dungeon::RoomEntrance::Save(), and WriteHelper().
WriteByte()
absl::Status yaze::app::Rom::WriteByte (int addr, uint8_t value) inline
References data(), yaze::app::core::Logger::log(), rom_data_, yaze::app::core::UppercaseHexByte(), and vector().
WriteWord()
absl::Status yaze::app::Rom::WriteWord (int addr, uint16_t value) inline
References yaze::app::core::Logger::log(), rom_data_, yaze::app::core::UppercaseHexWord(), and vector().
WriteShort()
absl::Status yaze::app::Rom::WriteShort (int addr, uint16_t value) inline
References yaze::app::core::Logger::log(), rom_data_, yaze::app::core::UppercaseHexWord(), and vector().
Referenced by yaze::app::zelda3::dungeon::RoomEntrance::Save(), WriteColor(), WriteHelper(), and WriteTile16().
WriteLong()
absl::Status yaze::app::Rom::WriteLong (uint32_t addr, uint32_t value) inline
References yaze::app::core::Logger::log(), rom_data_, yaze::app::core::UppercaseHexLong(), and vector().
WriteVector()
absl::Status yaze::app::Rom::WriteVector (int addr, std::vector< uint8_t > data) inline
References data(), yaze::app::core::Logger::log(), rom_data_, yaze::app::core::UppercaseHexByte(), and vector().
Referenced by WriteHelper().
WriteColor()
absl::Status yaze::app::Rom::WriteColor (uint32_t address, const gfx::SnesColor & color) inline
References yaze::app::core::Logger::log(), yaze::app::core::UppercaseHexWord(), vector(), and WriteShort().
Referenced by SavePalette(), and WriteHelper().
WriteTransaction()
template<typename... Args> absl::Status yaze::app::Rom::WriteTransaction (Args... args) inline
References vector(), and WriteHelper().
ReadTransaction()
template<typename T , typename... Args> absl::Status yaze::app::Rom::ReadTransaction (T & var, int address, Args &&... args) inline
References ReadTransaction(), and vector().
Referenced by ReadTransaction().
Expand()
void yaze::app::Rom::Expand (int size) inline
References rom_data_, size(), and size_.
Referenced by yaze::cli::Expand::handle().
Reload()
absl::Status yaze::app::Rom::Reload () inline
References filename_, and LoadFromFile().
Close()
absl::Status yaze::app::Rom::Close () inline
References is_loaded_, rom_data_, and size_.
QueueChanges()
void yaze::app::Rom::QueueChanges (std::function< void()> const & function) inline
References changes_, and vector().
version_constants()
VersionConstants yaze::app::Rom::version_constants () const inline
References version_.
Referenced by GetGraphicsAddress(), yaze::app::zelda3::overworld::OverworldMap::GetPalette(), yaze::app::zelda3::overworld::OverworldMap::LoadAreaGraphicsBlocksets(), LoadGfxGroups(), yaze::app::zelda3::overworld::OverworldMap::LoadMainBlocksets(), yaze::app::zelda3::overworld::OverworldMap::LoadPalette(), yaze::app::zelda3::overworld::OverworldMap::LoadSpritesBlocksets(), and SaveGroupsToROM().
GetGraphicsAddress()
int yaze::app::Rom::GetGraphicsAddress (const uchar * data, uint8_t addr) const inline
References data(), yaze::app::VersionConstants::kOverworldGfxPtr1, yaze::app::VersionConstants::kOverworldGfxPtr2, yaze::app::VersionConstants::kOverworldGfxPtr3, yaze::app::core::SnesToPc(), vector(), and version_constants().
Referenced by Load2BppGraphics(), and LoadAllGraphicsData().
palette_group()
auto yaze::app::Rom::palette_group () inline
References palette_groups_.
Referenced by yaze::app::zelda3::overworld::OverworldMap::LoadPalette(), and yaze::app::zelda3::overworld::palette_internal::SetColorsPalette().
mutable_palette_group()
auto yaze::app::Rom::mutable_palette_group () inline
References palette_groups_.
dungeon_palette()
auto yaze::app::Rom::dungeon_palette (int i) inline
References yaze::app::gfx::PaletteGroupMap::dungeon_main, and palette_groups_.
mutable_dungeon_palette()
auto yaze::app::Rom::mutable_dungeon_palette (int i) inline
References yaze::app::gfx::PaletteGroupMap::dungeon_main, yaze::app::gfx::PaletteGroup::mutable_palette(), and palette_groups_.
graphics_buffer()
Bytes yaze::app::Rom::graphics_buffer () const inline
References graphics_buffer_.
Referenced by yaze::app::zelda3::overworld::OverworldMap::BuildTileset().
graphics_bin()
gfx::BitmapTable yaze::app::Rom::graphics_bin () const inline
References graphics_bin_.
Referenced by yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
mutable_graphics_sheet()
gfx::Bitmap * yaze::app::Rom::mutable_graphics_sheet (int index) inline
References yaze::app::gfx::Bitmap::at(), and graphics_bin_.
bitmap_manager()
auto yaze::app::Rom::bitmap_manager () inline
References graphics_manager_.
mutable_bitmap_manager()
auto yaze::app::Rom::mutable_bitmap_manager () inline
References graphics_manager_.
link_graphics()
auto yaze::app::Rom::link_graphics () inline
References link_graphics_.
title()
auto yaze::app::Rom::title () const inline
References title_.
Referenced by yaze::cli::Open::handle().
size()
auto yaze::app::Rom::size () const inline
References size_.
Referenced by yaze::app::editor::GraphicsEditor::DrawMemoryEditor(), yaze::app::editor::MasterEditor::DrawViewMenu(), Expand(), yaze::cli::ApplyPatch::handle(), yaze::cli::Open::handle(), LoadAllGraphicsData(), yaze::app::gfx::lc_lz2::ValidateCompressionResult(), and yaze::app::gfx::lc_lz2::ValidateCompressionResultV3().
begin()
auto yaze::app::Rom::begin () inline
References rom_data_.
Referenced by yaze::app::gfx::lc_lz2::ValidateCompressionResult(), and yaze::app::gfx::lc_lz2::ValidateCompressionResultV3().
end()
auto yaze::app::Rom::end () inline
References rom_data_.
data()
auto yaze::app::Rom::data () inline
References rom_data_.
Referenced by CreateAndRenderBitmap(), yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::editor::GraphicsEditor::DrawMemoryEditor(), yaze::app::editor::GraphicsEditor::DrawPaletteControls(), yaze::app::editor::GraphicsEditor::DrawTilemapImport(), yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk(), yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectDecompressOk(), GetGraphicsAddress(), yaze::app::zelda3::music::Tracker::GetSPCAddr(), Load2BppGraphics(), LoadAllGraphicsData(), yaze::app::zelda3::overworld::Overworld::LoadExits(), LoadFromBytes(), LoadFromPointer(), yaze::app::zelda3::music::Tracker::LoadSongs(), yaze::app::zelda3::music::Tracker::SaveSongs(), yaze::app::gfx::lc_lz2::ValidateCompressionResult(), yaze::app::gfx::lc_lz2::ValidateCompressionResultV3(), WriteByte(), yaze::app::zelda3::music::Tracker::WriteSPCData(), and WriteVector().
push_back()
auto yaze::app::Rom::push_back (uint8_t byte) inline
References rom_data_.
vector()
auto yaze::app::Rom::vector () const inline
References rom_data_.
Referenced by yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectCompressOk(), GetGraphicsAddress(), yaze::cli::ApplyPatch::handle(), Load2BppGraphics(), LoadAllGraphicsData(), LoadFromFile(), LoadGfxGroups(), LoadLinkGraphics(), QueueChanges(), ReadByteVector(), ReadHelper(), ReadLong(), ReadTile16(), ReadTransaction(), ReadWord(), SaveAllPalettes(), SaveGroupsToROM(), SavePalette(), SaveToFile(), yaze::app::emu::SNES::SetupMemory(), SetupRenderer(), toint16(), UpdateBitmap(), Write(), WriteByte(), WriteColor(), WriteHelper(), WriteLong(), WriteShort(), WriteTile16(), WriteTransaction(), WriteVector(), and WriteWord().
filename()
auto yaze::app::Rom::filename () const inline
References filename_.
Referenced by yaze::app::editor::MasterEditor::DrawViewMenu(), LoadFromFile(), and SaveToFile().
is_loaded()
auto yaze::app::Rom::is_loaded () const inline
References is_loaded_.
Referenced by yaze::app::editor::GraphicsEditor::DrawClipboardImport().
version()
auto yaze::app::Rom::version () const inline
References version_.
operator[]()
uint8_t & yaze::app::Rom::operator[] (int i) inline
References rom_data_, and size_.
operator+()
uint8_t & yaze::app::Rom::operator+ (int i) inline
References rom_data_, and size_.
operator&()
const uint8_t * yaze::app::Rom::operator& () inline
References rom_data_.
SetupRenderer()
void yaze::app::Rom::SetupRenderer (std::shared_ptr< SDL_Renderer > renderer) inline
References renderer_, and vector().
CreateAndRenderBitmap()
absl::Status yaze::app::Rom::CreateAndRenderBitmap (int width, int height, int depth, const Bytes & data, gfx::Bitmap & bitmap, gfx::SnesPalette & palette) inline
References yaze::app::gfx::Bitmap::ApplyPalette(), yaze::app::gfx::Bitmap::Create(), data(), RenderBitmap(), and RETURN_IF_ERROR.
RenderBitmap()
void yaze::app::Rom::RenderBitmap (gfx::Bitmap * bitmap) inline
Used to render a bitmap to the screen.
References yaze::app::gfx::Bitmap::CreateTexture(), yaze::app::core::ExperimentFlags::flags(), and renderer_.
Referenced by CreateAndRenderBitmap(), and LoadLinkGraphics().
UpdateBitmap()
void yaze::app::Rom::UpdateBitmap (gfx::Bitmap * bitmap, bool use_sdl_update = false) inline
Used to update a bitmap on the screen.
References yaze::app::core::ExperimentFlags::flags(), renderer_, yaze::app::gfx::Bitmap::UpdateTexture(), and vector().
LoadGfxGroups()
void yaze::app::Rom::LoadGfxGroups () inline
References yaze::app::core::entrance_gfx_group, yaze::app::VersionConstants::kDungeonPalettesGroups, yaze::app::kGfxGroupsPointer, yaze::app::VersionConstants::kSpriteBlocksetPointer, main_blockset_ids, paletteset_ids, rom_data_, room_blockset_ids, yaze::app::core::SnesToPc(), spriteset_ids, vector(), and version_constants().
Referenced by LoadFromFile().
SaveGroupsToROM()
bool yaze::app::Rom::SaveGroupsToROM () inline
References yaze::app::core::entrance_gfx_group, yaze::app::VersionConstants::kDungeonPalettesGroups, yaze::app::kGfxGroupsPointer, yaze::app::VersionConstants::kSpriteBlocksetPointer, main_blockset_ids, paletteset_ids, rom_data_, room_blockset_ids, yaze::app::core::SnesToPc(), spriteset_ids, vector(), and version_constants().
resource_label()
auto yaze::app::Rom::resource_label () inline
References resource_label_manager_.
WriteHelper()
absl::Status yaze::app::Rom::WriteHelper (const WriteAction & action) inline private
References vector(), Write(), WriteColor(), WriteShort(), and WriteVector().
Referenced by WriteTransaction().
ReadHelper()
template<typename T > absl::Status yaze::app::Rom::ReadHelper (T & var, int address) inline private
References ASSIGN_OR_RETURN, ReadByte(), ReadByteVector(), ReadWord(), and vector().
Member Data Documentation
main_blockset_ids
std::vector<std::vector<uint8_t> > yaze::app::Rom::main_blockset_ids
Referenced by LoadGfxGroups(), and SaveGroupsToROM().
room_blockset_ids
std::vector<std::vector<uint8_t> > yaze::app::Rom::room_blockset_ids
Referenced by LoadGfxGroups(), and SaveGroupsToROM().
spriteset_ids
std::vector<std::vector<uint8_t> > yaze::app::Rom::spriteset_ids
Referenced by LoadGfxGroups(), and SaveGroupsToROM().
paletteset_ids
std::vector<std::vector<uint8_t> > yaze::app::Rom::paletteset_ids
Referenced by LoadGfxGroups(), and SaveGroupsToROM().
size_
long yaze::app::Rom::size_ = 0 private
Referenced by Close(), Expand(), LoadFromBytes(), LoadFromFile(), operator+(), operator[](), and size().
is_loaded_
bool yaze::app::Rom::is_loaded_ = false private
Referenced by Close(), is_loaded(), LoadFromBytes(), and LoadFromFile().
has_header_
bool yaze::app::Rom::has_header_ = false private
Referenced by LoadFromFile().
title_
uchar yaze::app::Rom::title_[21] = "ROM Not Loaded" private
Referenced by LoadFromFile(), and title().
filename_
std::string yaze::app::Rom::filename_ private
Referenced by filename(), LoadFromFile(), Reload(), and SaveToFile().
rom_data_
Bytes yaze::app::Rom::rom_data_ private
Referenced by begin(), Close(), data(), end(), Expand(), LoadAllGraphicsData(), LoadAllPalettes(), LoadFromBytes(), LoadFromFile(), LoadFromPointer(), LoadGfxGroups(), operator&(), operator+(), operator[](), push_back(), ReadByte(), ReadByteVector(), ReadLong(), ReadWord(), SaveGroupsToROM(), SaveToFile(), toint16(), vector(), Write(), WriteByte(), WriteLong(), WriteShort(), WriteVector(), and WriteWord().
graphics_buffer_
Bytes yaze::app::Rom::graphics_buffer_ private
Referenced by graphics_buffer(), and LoadAllGraphicsData().
version_
Z3_Version yaze::app::Rom::version_ = Z3_Version::US private
Referenced by LoadFromFile(), version(), and version_constants().
graphics_bin_
gfx::BitmapTable yaze::app::Rom::graphics_bin_ private
Referenced by graphics_bin(), LoadAllGraphicsData(), and mutable_graphics_sheet().
graphics_manager_
gfx::BitmapManager yaze::app::Rom::graphics_manager_ private
Referenced by bitmap_manager(), LoadAllGraphicsData(), and mutable_bitmap_manager().
link_graphics_
gfx::BitmapTable yaze::app::Rom::link_graphics_ private
Referenced by link_graphics(), and LoadLinkGraphics().
link_palette_
gfx::SnesPalette yaze::app::Rom::link_palette_ private
Referenced by LoadLinkGraphics().
palette_groups_
gfx::PaletteGroupMap yaze::app::Rom::palette_groups_ private
Referenced by dungeon_palette(), LoadAllGraphicsData(), LoadAllPalettes(), LoadLinkGraphics(), mutable_dungeon_palette(), mutable_palette_group(), palette_group(), and SaveAllPalettes().
resource_label_manager_
core::ResourceLabelManager yaze::app::Rom::resource_label_manager_ private
Referenced by LoadFromFile(), and resource_label().
changes_
std::stack<std::function<void()> > yaze::app::Rom::changes_ private
Referenced by QueueChanges().
renderer_
std::shared_ptr<SDL_Renderer> yaze::app::Rom::renderer_ private
Referenced by LoadAllGraphicsData(), RenderBitmap(), SetupRenderer(), and UpdateBitmap().
The documentation for this class was generated from the following files:
src/app/rom.h
src/app/rom.cc