yaze: yaze::app::emu::audio::AudioRam Class Reference
yaze::app::emu::audio::AudioRam Class Reference abstract
AudioRam is an interface for the Audio RAM used by the SPC700.
#include <spc700.h>
Public Member Functions
virtual ~AudioRam ()=default
virtual void reset ()=0
virtual uint8_t read (uint16_t address) const =0
virtual uint8_t & mutable_read (uint16_t address)=0
virtual void write (uint16_t address, uint8_t value)=0
Detailed Description
AudioRam is an interface for the Audio RAM used by the SPC700.
Constructor & Destructor Documentation
~AudioRam()
virtual yaze::app::emu::audio::AudioRam::~AudioRam () virtual default
Member Function Documentation
reset()
virtual void yaze::app::emu::audio::AudioRam::reset () pure virtual
Implemented in yaze::app::emu::audio::AudioRamImpl.
Referenced by yaze::app::emu::audio::Spc700::Reset(), and yaze_test::emu_test::MockAudioRam::SetUp().
read()
virtual uint8_t yaze::app::emu::audio::AudioRam::read (uint16_t address) const pure virtual
Implemented in yaze::app::emu::audio::AudioRamImpl.
Referenced by yaze::app::emu::audio::Apu::FetchSampleForVoice(), yaze::app::emu::audio::Apu::FetchSampleFromRam(), yaze::app::emu::audio::Spc700::read(), yaze::app::emu::audio::Spc700::read_16(), and yaze_test::emu_test::MockAudioRam::SetUp().
mutable_read()
virtual uint8_t & yaze::app::emu::audio::AudioRam::mutable_read (uint16_t address) pure virtual
Implemented in yaze::app::emu::audio::AudioRamImpl.
Referenced by yaze::app::emu::audio::Spc700::mutable_read(), yaze::app::emu::audio::Spc700::mutable_read_16(), and yaze_test::emu_test::MockAudioRam::SetUp().
write()
virtual void yaze::app::emu::audio::AudioRam::write (uint16_t address, uint8_t value) pure virtual
Implemented in yaze::app::emu::audio::AudioRamImpl.
Referenced by yaze_test::emu_test::MockAudioRam::SetUp(), and yaze::app::emu::audio::Spc700::write().
The documentation for this class was generated from the following file:
src/app/emu/audio/spc700.h