yaze: yaze::core::ScopedTimer Class Reference
yaze::core::ScopedTimer Class Reference
RAII timer that automatically records operation duration.
#include <performance_monitor.h>
Public Member Functions
ScopedTimer (const std::string &operation_name)
~ScopedTimer ()
Private Attributes
std::string operation_name_
bool enabled_
Detailed Description
RAII timer that automatically records operation duration.
Usage: { ScopedTimer timer("operation_name"); // ... do work ... } // Timer automatically stops and records duration
Definition at line 105 of file performance_monitor.h.
Constructor & Destructor Documentation
ScopedTimer()
yaze::core::ScopedTimer::ScopedTimer (const std::string & operation_name) explicit
Definition at line 89 of file performance_monitor.cc.
References enabled_, yaze::core::PerformanceMonitor::Get(), operation_name_, and yaze::core::PerformanceMonitor::StartTimer().
~ScopedTimer()
yaze::core::ScopedTimer::~ScopedTimer ()
Definition at line 96 of file performance_monitor.cc.
References enabled_, yaze::core::PerformanceMonitor::EndTimer(), yaze::core::PerformanceMonitor::Get(), and operation_name_.
Member Data Documentation
operation_name_
std::string yaze::core::ScopedTimer::operation_name_ private
Definition at line 111 of file performance_monitor.h.
Referenced by ScopedTimer(), and ~ScopedTimer().
enabled_
bool yaze::core::ScopedTimer::enabled_ private
Definition at line 112 of file performance_monitor.h.
Referenced by ScopedTimer(), and ~ScopedTimer().
The documentation for this class was generated from the following files:
src/app/core/performance_monitor.h
src/app/core/performance_monitor.cc