yaze: yaze::cli::Tile16Transfer Class Reference
yaze::cli::Tile16Transfer Class Reference
Transfer tile 16 data from one Rom to another.
#include <command_handler.h>
Public Member Functions
absl::Status handle (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
app::Rom rom_
Detailed Description
Transfer tile 16 data from one Rom to another.
Parameters
arg_vec -t <src_rom> <dest_rom> "<tile32_id_list:csv>"
Returns
absl::Status
Definition at line 297 of file command_handler.h.
Member Function Documentation
handle()
absl::Status yaze::cli::Tile16Transfer::handle (const std::vector< std::string > & arg_vec) override virtual
Implements yaze::cli::CommandHandler.
Definition at line 16 of file command_handler.cc.
References ASSIGN_OR_RETURN, yaze::app::Rom::LoadFromFile(), yaze::app::Rom::ReadTile16(), RETURN_IF_ERROR, yaze::cli::CommandHandler::rom_, yaze::app::Rom::SaveToFile(), and yaze::app::Rom::WriteTile16().
The documentation for this class was generated from the following files:
src/cli/command_handler.h
src/cli/command_handler.cc