yaze: yaze::app::zelda3::Inventory Class Reference
yaze::app::zelda3::Inventory Class Reference
#include <inventory.h>
Public Member Functions
auto Bitmap () const
auto Tilesheet () const
auto Palette () const
void Create ()
Public Member Functions inherited from yaze::app::SharedROM
SharedROM ()=default
virtual ~SharedROM ()=default
std::shared_ptr< ROM > shared_rom ()
auto rom ()
Private Member Functions
absl::Status BuildTileset ()
Private Attributes
Bytes data_
gfx::Bitmap bitmap_
Bytes tilesheets_
Bytes test_
gfx::Bitmap tilesheets_bmp_
gfx::SnesPalette palette_
gui::Canvas canvas_
std::vector< gfx::TileInfo > tiles_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedROM
static std::shared_ptr< ROM > shared_rom_ = nullptr
Member Function Documentation
Bitmap()
auto yaze::app::zelda3::Inventory::Bitmap () const inline
References bitmap_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
BuildTileset()
absl::Status yaze::app::zelda3::Inventory::BuildTileset () private
References yaze::app::gfx::Bitmap::ApplyPalette(), ASSIGN_OR_RETURN, yaze::app::gfx::Bitmap::Create(), palette_, yaze::app::SharedROM::rom(), test_, tilesheets_, and tilesheets_bmp_.
Referenced by Create().
Create()
void yaze::app::zelda3::Inventory::Create ()
References yaze::app::gfx::Bitmap::ApplyPalette(), bitmap_, BuildTileset(), yaze::app::gfx::Bitmap::Create(), data_, yaze::app::gfx::GetTilesInfo(), yaze::app::zelda3::kBowItemPos, palette_, PRINT_IF_ERROR, yaze::app::SharedROM::rom(), test_, and tiles_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
Palette()
auto yaze::app::zelda3::Inventory::Palette () const inline
References palette_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
Tilesheet()
auto yaze::app::zelda3::Inventory::Tilesheet () const inline
References tilesheets_bmp_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
Member Data Documentation
bitmap_
gfx::Bitmap yaze::app::zelda3::Inventory::bitmap_ private
Referenced by Bitmap(), and Create().
canvas_
gui::Canvas yaze::app::zelda3::Inventory::canvas_ private
data_
Bytes yaze::app::zelda3::Inventory::data_ private
Referenced by Create().
palette_
gfx::SnesPalette yaze::app::zelda3::Inventory::palette_ private
Referenced by BuildTileset(), Create(), and Palette().
test_
Bytes yaze::app::zelda3::Inventory::test_ private
Referenced by BuildTileset(), and Create().
tiles_
std::vector<gfx::TileInfo> yaze::app::zelda3::Inventory::tiles_ private
Referenced by Create().
tilesheets_
Bytes yaze::app::zelda3::Inventory::tilesheets_ private
Referenced by BuildTileset().
tilesheets_bmp_
gfx::Bitmap yaze::app::zelda3::Inventory::tilesheets_bmp_ private
Referenced by BuildTileset(), and Tilesheet().
The documentation for this class was generated from the following files:
src/app/zelda3/screen/inventory.h
src/app/zelda3/screen/inventory.cc