yaze: yaze::app::zelda3::SpriteInstruction Class Reference
yaze::app::zelda3::SpriteInstruction Class Reference
#include <sprite_builder.h>
Public Member Functions
std::string GetConfiguration () const
void SetConfiguration (const std::string &instruction)
Static Public Member Functions
static SpriteInstruction PlayAnimation (int startFrame, int endFrame, int speed)
static SpriteInstruction ApplySpeedTowardsPlayer (int speed)
static SpriteInstruction CheckDamageFromPlayer ()
static SpriteInstruction MoveXyz ()
static SpriteInstruction BounceFromTileCollision ()
static SpriteInstruction SetTimer (int timerId, int value)
static SpriteInstruction BehaveAsBarrier ()
static SpriteInstruction JumpToFunction (const std::string &functionName)
static SpriteInstruction Custom (const std::string &asmCode)
Private Attributes
std::string instruction_
Detailed Description
Definition at line 12 of file sprite_builder.h.
Member Function Documentation
PlayAnimation()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::PlayAnimation (int startFrame, int endFrame, int speed) static
Definition at line 95 of file sprite_builder.cc.
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
ApplySpeedTowardsPlayer()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::ApplySpeedTowardsPlayer (int speed) static
Definition at line 102 of file sprite_builder.cc.
References SetConfiguration().
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
CheckDamageFromPlayer()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::CheckDamageFromPlayer () static
Definition at line 108 of file sprite_builder.cc.
MoveXyz()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::MoveXyz () static
Definition at line 114 of file sprite_builder.cc.
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
BounceFromTileCollision()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::BounceFromTileCollision () static
Definition at line 120 of file sprite_builder.cc.
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
SetTimer()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::SetTimer (int timerId, int value) static
Definition at line 126 of file sprite_builder.cc.
BehaveAsBarrier()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::BehaveAsBarrier () static
Definition at line 138 of file sprite_builder.cc.
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
JumpToFunction()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::JumpToFunction (const std::string & functionName) static
Definition at line 144 of file sprite_builder.cc.
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
Custom()
SpriteInstruction yaze::app::zelda3::SpriteInstruction::Custom (const std::string & asmCode) static
Definition at line 132 of file sprite_builder.cc.
GetConfiguration()
std::string yaze::app::zelda3::SpriteInstruction::GetConfiguration () const inline
Definition at line 29 of file sprite_builder.h.
References instruction_.
SetConfiguration()
void yaze::app::zelda3::SpriteInstruction::SetConfiguration (const std::string & instruction) inline
Definition at line 30 of file sprite_builder.h.
References instruction_.
Referenced by ApplySpeedTowardsPlayer().
Member Data Documentation
instruction_
std::string yaze::app::zelda3::SpriteInstruction::instruction_ private
Definition at line 35 of file sprite_builder.h.
Referenced by GetConfiguration(), and SetConfiguration().
The documentation for this class was generated from the following files:
src/app/zelda3/sprite/sprite_builder.h
src/app/zelda3/sprite/sprite_builder.cc