yaze: yaze::app::zelda3::screen::TitleScreen Class Reference
yaze::app::zelda3::screen::TitleScreen Class Reference
#include <title_screen.h>
Public Member Functions
void Create ()
Private Member Functions
void BuildTileset ()
void LoadTitleScreen ()
Private Attributes
int sword_x_ = 0
int mx_click_ = 0
int my_click_ = 0
int mx_dist_ = 0
int my_dist_ = 0
int last_x_ = 0
int last_y_ = 0
int x_in_ = 0
int y_in_ = 0
int dungmap_selected_tile_ = 0
int dungmap_selected_ = 0
int selected_palette_ = 0
int total_floors_ = 0
int current_floor_ = 0
int num_basement_ = 0
int num_floor_ = 0
int selected_map_tile = 0
int current_floor_rooms
int current_floor_gfx
int copied_data_rooms
int copied_data_gfx
int pal_selected_
int addresses [7]
int addressesgfx [7]
ushort bossRoom = 0x000F
ushort selected_tile = 0
ushort tilesBG1Buffer [0x1000]
ushort tilesBG2Buffer [0x1000]
uchar mapdata
uchar dwmapdata
bool mDown = false
bool swordSelected = false
bool darkWorld = false
bool currentDungeonChanged = false
bool editedFromEditor = false
bool mouseDown = false
bool mdown = false
Rom rom_
gfx::OamTile oam_data [10]
gfx::OamTile selected_oam_tile
gfx::OamTile last_selected_oam_tile
gfx::Bitmap tilesBG1Bitmap
gfx::Bitmap tilesBG2Bitmap
gfx::Bitmap oamBGBitmap
gfx::Bitmap tiles8Bitmap
Member Function Documentation
Create()
void yaze::app::zelda3::screen::TitleScreen::Create ()
References BuildTileset(), yaze::app::gfx::Bitmap::Create(), LoadTitleScreen(), oamBGBitmap, tiles8Bitmap, tilesBG1Bitmap, and tilesBG2Bitmap.
BuildTileset()
void yaze::app::zelda3::screen::TitleScreen::BuildTileset () private
Todo
get the gfx from the GFX class rather than the rom.
References yaze::app::gfx::Bitmap::mutable_data(), and tiles8Bitmap.
Referenced by Create().
LoadTitleScreen()
void yaze::app::zelda3::screen::TitleScreen::LoadTitleScreen () private
References pal_selected_, rom_, yaze::app::core::SnesToPc(), tilesBG1Buffer, and tilesBG2Buffer.
Referenced by Create().
Member Data Documentation
sword_x_
int yaze::app::zelda3::screen::TitleScreen::sword_x_ = 0 private
mx_click_
int yaze::app::zelda3::screen::TitleScreen::mx_click_ = 0 private
my_click_
int yaze::app::zelda3::screen::TitleScreen::my_click_ = 0 private
mx_dist_
int yaze::app::zelda3::screen::TitleScreen::mx_dist_ = 0 private
my_dist_
int yaze::app::zelda3::screen::TitleScreen::my_dist_ = 0 private
last_x_
int yaze::app::zelda3::screen::TitleScreen::last_x_ = 0 private
last_y_
int yaze::app::zelda3::screen::TitleScreen::last_y_ = 0 private
x_in_
int yaze::app::zelda3::screen::TitleScreen::x_in_ = 0 private
y_in_
int yaze::app::zelda3::screen::TitleScreen::y_in_ = 0 private
dungmap_selected_tile_
int yaze::app::zelda3::screen::TitleScreen::dungmap_selected_tile_ = 0 private
dungmap_selected_
int yaze::app::zelda3::screen::TitleScreen::dungmap_selected_ = 0 private
selected_palette_
int yaze::app::zelda3::screen::TitleScreen::selected_palette_ = 0 private
total_floors_
int yaze::app::zelda3::screen::TitleScreen::total_floors_ = 0 private
current_floor_
int yaze::app::zelda3::screen::TitleScreen::current_floor_ = 0 private
num_basement_
int yaze::app::zelda3::screen::TitleScreen::num_basement_ = 0 private
num_floor_
int yaze::app::zelda3::screen::TitleScreen::num_floor_ = 0 private
selected_map_tile
int yaze::app::zelda3::screen::TitleScreen::selected_map_tile = 0 private
current_floor_rooms
int yaze::app::zelda3::screen::TitleScreen::current_floor_rooms private
current_floor_gfx
int yaze::app::zelda3::screen::TitleScreen::current_floor_gfx private
copied_data_rooms
int yaze::app::zelda3::screen::TitleScreen::copied_data_rooms private
copied_data_gfx
int yaze::app::zelda3::screen::TitleScreen::copied_data_gfx private
pal_selected_
int yaze::app::zelda3::screen::TitleScreen::pal_selected_ private
Referenced by LoadTitleScreen().
addresses
int yaze::app::zelda3::screen::TitleScreen::addresses[7] private
Initial value:
= {0x53de4, 0x53e2c, 0x53e08, 0x53e50,
                      0x53e74, 0x53e98, 0x53ebc}
addressesgfx
int yaze::app::zelda3::screen::TitleScreen::addressesgfx[7] private
Initial value:
= {0x53ee0, 0x53f04, 0x53ef2, 0x53f16,
                         0x53f28, 0x53f3a, 0x53f4c}
bossRoom
ushort yaze::app::zelda3::screen::TitleScreen::bossRoom = 0x000F private
selected_tile
ushort yaze::app::zelda3::screen::TitleScreen::selected_tile = 0 private
tilesBG1Buffer
ushort yaze::app::zelda3::screen::TitleScreen::tilesBG1Buffer[0x1000] private
Referenced by LoadTitleScreen().
tilesBG2Buffer
ushort yaze::app::zelda3::screen::TitleScreen::tilesBG2Buffer[0x1000] private
Referenced by LoadTitleScreen().
mapdata
uchar yaze::app::zelda3::screen::TitleScreen::mapdata private
dwmapdata
uchar yaze::app::zelda3::screen::TitleScreen::dwmapdata private
mDown
bool yaze::app::zelda3::screen::TitleScreen::mDown = false private
swordSelected
bool yaze::app::zelda3::screen::TitleScreen::swordSelected = false private
darkWorld
bool yaze::app::zelda3::screen::TitleScreen::darkWorld = false private
currentDungeonChanged
bool yaze::app::zelda3::screen::TitleScreen::currentDungeonChanged = false private
editedFromEditor
bool yaze::app::zelda3::screen::TitleScreen::editedFromEditor = false private
mouseDown
bool yaze::app::zelda3::screen::TitleScreen::mouseDown = false private
mdown
bool yaze::app::zelda3::screen::TitleScreen::mdown = false private
rom_
Rom yaze::app::zelda3::screen::TitleScreen::rom_ private
Referenced by LoadTitleScreen().
oam_data
gfx::OamTile yaze::app::zelda3::screen::TitleScreen::oam_data[10] private
selected_oam_tile
gfx::OamTile yaze::app::zelda3::screen::TitleScreen::selected_oam_tile private
last_selected_oam_tile
gfx::OamTile yaze::app::zelda3::screen::TitleScreen::last_selected_oam_tile private
tilesBG1Bitmap
gfx::Bitmap yaze::app::zelda3::screen::TitleScreen::tilesBG1Bitmap private
Referenced by Create().
tilesBG2Bitmap
gfx::Bitmap yaze::app::zelda3::screen::TitleScreen::tilesBG2Bitmap private
Referenced by Create().
oamBGBitmap
gfx::Bitmap yaze::app::zelda3::screen::TitleScreen::oamBGBitmap private
Referenced by Create().
tiles8Bitmap
gfx::Bitmap yaze::app::zelda3::screen::TitleScreen::tiles8Bitmap private
Referenced by BuildTileset(), and Create().
The documentation for this class was generated from the following files:
src/app/zelda3/screen/title_screen.h
src/app/zelda3/screen/title_screen.cc