yaze: yaze::editor::Renderer Class Reference
yaze::editor::Renderer Class Reference
The Renderer class represents the renderer for the Yaze application.
#include <renderer.h>
Public Member Functions
absl::Status CreateRenderer (SDL_Window *window)
auto renderer () -> SDL_Renderer *
void RenderBitmap (gfx::Bitmap *bitmap)
Used to render a bitmap to the screen.
void UpdateBitmap (gfx::Bitmap *bitmap)
Used to update a bitmap on the screen.
void CreateAndRenderBitmap (int width, int height, int depth, const std::vector< uint8_t > &data, gfx::Bitmap &bitmap, gfx::SnesPalette &palette)
Static Public Member Functions
static Renderer & GetInstance ()
Private Member Functions
Renderer ()=default
Renderer (const Renderer &)=delete
Renderer & operator= (const Renderer &)=delete
Private Attributes
std::unique_ptr< SDL_Renderer, SDL_Deleter > renderer_
Detailed Description
The Renderer class represents the renderer for the Yaze application.
This class is a singleton that provides functionality for creating and rendering bitmaps to the screen. It also includes methods for updating bitmaps on the screen.
Definition at line 24 of file renderer.h.
Constructor & Destructor Documentation
Renderer() [1/2]
yaze::core::Renderer::Renderer () private default
Renderer() [2/2]
yaze::core::Renderer::Renderer (const Renderer &) private delete
Member Function Documentation
GetInstance()
static Renderer & yaze::core::Renderer::GetInstance () inline static
Definition at line 26 of file renderer.h.
Referenced by yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::GraphicsEditor::DecompressImportData(), yaze::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::GraphicsEditor::DrawCgxImport(), yaze::editor::MessageEditor::DrawCurrentMessage(), yaze::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::editor::ScreenEditor::DrawDungeonMapsRoomGfx(), yaze::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::editor::GraphicsEditor::DrawGfxEditToolset(), yaze::editor::DungeonEditor::DrawObjectRenderer(), yaze::editor::GraphicsEditor::DrawScrImport(), yaze::editor::Tile16Editor::DrawTileEditControls(), yaze::editor::MessageEditor::Initialize(), yaze::editor::ScreenEditor::LoadBinaryGfx(), yaze::editor::ScreenEditor::LoadDungeonMapTile16(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldEditor::LoadSpriteGraphics(), yaze::editor::Tile16Editor::LoadTile8(), yaze::editor::DungeonEditor::RefreshGraphics(), yaze::editor::OverworldEditor::RefreshOverworldMap(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::editor::Tile16Editor::UpdateBlockset(), yaze::editor::GraphicsEditor::UpdateGfxTabView(), yaze::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::editor::Tile16Editor::UpdateTile16Edit(), and yaze::editor::Tile16Editor::UpdateTransferTileCanvas().
CreateRenderer()
absl::Status yaze::core::Renderer::CreateRenderer (SDL_Window * window) inline
Definition at line 31 of file renderer.h.
renderer()
auto yaze::core::Renderer::renderer () -> SDL_Renderer * inline
Definition at line 43 of file renderer.h.
RenderBitmap()
void yaze::core::Renderer::RenderBitmap (gfx::Bitmap * bitmap) inline
Used to render a bitmap to the screen.
Definition at line 48 of file renderer.h.
UpdateBitmap()
void yaze::core::Renderer::UpdateBitmap (gfx::Bitmap * bitmap) inline
Used to update a bitmap on the screen.
Definition at line 55 of file renderer.h.
CreateAndRenderBitmap()
void yaze::core::Renderer::CreateAndRenderBitmap (int width, int height, int depth, const std::vector< uint8_t > & data, gfx::Bitmap & bitmap, gfx::SnesPalette & palette) inline
Definition at line 59 of file renderer.h.
operator=()
Renderer & yaze::core::Renderer::operator= (const Renderer &) private delete
Member Data Documentation
renderer_
std::unique_ptr<SDL_Renderer, SDL_Deleter> yaze::core::Renderer::renderer_ private
Definition at line 72 of file renderer.h.
The documentation for this class was generated from the following file:
src/app/core/platform/renderer.h