yaze: yaze::app::emu::video::Ppu Class Reference
yaze::app::emu::video::Ppu Class Reference
#include <ppu.h>
Public Member Functions
Ppu (memory::Memory &memory, Clock &clock)
void Init ()
void Reset ()
void Update ()
void UpdateClock (double delta_time)
void UpdateInternalState (int cycles)
void RenderScanline ()
void Notify (uint32_t address, uint8_t data) override
const std::vector< uint8_t > & GetFrameBuffer () const
auto GetScreen () const
Public Member Functions inherited from yaze::app::emu::memory::Observer
virtual ~Observer ()=default
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Private Member Functions
void UpdateModeSettings ()
void UpdateTileData ()
void UpdateTileMapData ()
void RenderBackground (int layer)
void RenderSprites ()
void UpdatePaletteData ()
void ApplyEffects ()
void ComposeLayers ()
void DisplayFrameBuffer ()
Private Attributes
Memory & memory_
Clock & clock_
OAMSize oam_size_
OAMAddress oam_address_
Mosaic mosaic_
std::array< BGSC, 4 > bgsc_
std::array< BGNBA, 4 > bgnba_
std::array< BGHOFS, 4 > bghofs_
std::array< BGVOFS, 4 > bgvofs_
struct VMAIN vmain_
struct VMADDL vmaddl_
struct VMADDH vmaddh_
struct M7SEL m7sel_
struct M7A m7a_
struct M7B m7b_
struct M7C m7c_
struct M7D m7d_
struct M7X m7x_
struct M7Y m7y_
struct CGADD cgadd_
struct CGDATA cgdata_
struct W12SEL w12sel_
struct W34SEL w34sel_
struct WOBJSEL wobjsel_
struct WH0 wh0_
struct WH1 wh1_
struct WH2 wh2_
struct WH3 wh3_
struct WBGLOG wbglog_
struct WOBJLOG wobjlog_
struct TM tm_
struct TS ts_
struct TSW tsw_
struct TMW tmw_
struct SETINI setini_
Tilemap tilemap_
BackgroundMode bg_mode_
std::array< BackgroundLayer, 4 > bg_layers_
std::vector< SpriteAttributes > sprites_
std::vector< uint8_t > tile_data_
std::vector< uint8_t > frame_buffer_
std::shared_ptr< gfx::Bitmap > screen_
uint16_t tile_data_size_
uint16_t vram_base_address_
uint16_t tilemap_base_address_
uint16_t screen_brightness_ = 0x00
bool enable_forced_blanking_ = false
int cycle_count_ = 0
int current_scanline_ = 0
const int cyclesPerScanline = 341
const int totalScanlines = 262
const int visibleScanlines = 224
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Constructor & Destructor Documentation
Ppu()
yaze::app::emu::video::Ppu::Ppu (memory::Memory & memory, Clock & clock) inline
Member Function Documentation
Init()
void yaze::app::emu::video::Ppu::Init () inline
References clock_, frame_buffer_, yaze::app::emu::video::kPpuClockSpeed, screen_, and yaze::app::emu::Clock::SetFrequency().
Referenced by yaze::app::emu::SNES::Init().
Reset()
void yaze::app::emu::video::Ppu::Reset () inline
References frame_buffer_.
Update()
void yaze::app::emu::video::Ppu::Update ()
References clock_, current_scanline_, yaze::app::emu::Clock::GetCycleCount(), RenderScanline(), UpdateInternalState(), and visibleScanlines.
Referenced by yaze::app::emu::SNES::Run(), and yaze::app::emu::SNES::StepRun().
UpdateClock()
void yaze::app::emu::video::Ppu::UpdateClock (double delta_time) inline
References clock_, and yaze::app::emu::Clock::UpdateClock().
Referenced by yaze::app::emu::SNES::Run(), and yaze::app::emu::SNES::StepRun().
UpdateInternalState()
void yaze::app::emu::video::Ppu::UpdateInternalState (int cycles)
References current_scanline_, cycle_count_, cyclesPerScanline, and totalScanlines.
Referenced by Update().
RenderScanline()
void yaze::app::emu::video::Ppu::RenderScanline ()
References ApplyEffects(), ComposeLayers(), DisplayFrameBuffer(), frame_buffer_, RenderBackground(), RenderSprites(), UpdatePaletteData(), and UpdateTileMapData().
Referenced by Update().
Notify()
void yaze::app::emu::video::Ppu::Notify (uint32_t address, uint8_t data) override virtual
Implements yaze::app::emu::memory::Observer.
References yaze::app::emu::video::PpuRegisters::CGADD::address, yaze::app::emu::video::PpuRegisters::VMADDH::address_high, yaze::app::emu::video::PpuRegisters::VMAIN::address_increment_mode, yaze::app::emu::video::PpuRegisters::VMADDL::address_low, yaze::app::emu::video::OAMSize::base_selection, yaze::app::emu::video::PpuRegisters::BG12NBA, yaze::app::emu::video::PpuRegisters::BG1HOFS, yaze::app::emu::video::PpuRegisters::BG1SC, yaze::app::emu::video::PpuRegisters::BG1VOFS, yaze::app::emu::video::PpuRegisters::BG2HOFS, yaze::app::emu::video::PpuRegisters::BG2SC, yaze::app::emu::video::PpuRegisters::BG2VOFS, yaze::app::emu::video::PpuRegisters::BG34NBA, yaze::app::emu::video::PpuRegisters::BG3HOFS, yaze::app::emu::video::PpuRegisters::BG3SC, yaze::app::emu::video::PpuRegisters::BG3VOFS, yaze::app::emu::video::PpuRegisters::BG4HOFS, yaze::app::emu::video::PpuRegisters::BG4SC, yaze::app::emu::video::PpuRegisters::BG4VOFS, yaze::app::emu::video::PpuRegisters::Mosaic::bg_enable, bghofs_, yaze::app::emu::video::PpuRegisters::BGMODE, bgnba_, bgsc_, bgvofs_, yaze::app::emu::video::PpuRegisters::M7X::center_x, yaze::app::emu::video::PpuRegisters::M7Y::center_y, yaze::app::emu::video::PpuRegisters::CGADD, cgadd_, yaze::app::emu::video::PpuRegisters::CGDATA, yaze::app::emu::video::PpuRegisters::W12SEL::enable_bg1_a, yaze::app::emu::video::PpuRegisters::W12SEL::enable_bg1_b, yaze::app::emu::video::PpuRegisters::W12SEL::enable_bg2_c, yaze::app::emu::video::PpuRegisters::W12SEL::enable_bg2_d, yaze::app::emu::video::PpuRegisters::W34SEL::enable_bg3_e, yaze::app::emu::video::PpuRegisters::W34SEL::enable_bg3_f, yaze::app::emu::video::PpuRegisters::W34SEL::enable_bg4_g, yaze::app::emu::video::PpuRegisters::W34SEL::enable_bg4_h, yaze::app::emu::video::PpuRegisters::WOBJSEL::enable_color_k, yaze::app::emu::video::PpuRegisters::WOBJSEL::enable_color_l, enable_forced_blanking_, yaze::app::emu::video::PpuRegisters::TM::enable_layer, yaze::app::emu::video::PpuRegisters::TS::enable_layer, yaze::app::emu::video::PpuRegisters::WOBJSEL::enable_obj_i, yaze::app::emu::video::PpuRegisters::WOBJSEL::enable_obj_j, yaze::app::emu::video::PpuRegisters::TMW::enable_window, yaze::app::emu::video::PpuRegisters::TSW::enable_window, yaze::app::emu::video::PpuRegisters::M7SEL::fill, yaze::app::emu::video::PpuRegisters::M7SEL::flip_horizontal, yaze::app::emu::video::PpuRegisters::M7SEL::flip_vertical, yaze::app::emu::video::PpuRegisters::VMAIN::increment_size, yaze::app::emu::video::PpuRegisters::INIDISP, yaze::app::emu::video::PpuRegisters::W12SEL::invert_bg1_a, yaze::app::emu::video::PpuRegisters::W12SEL::invert_bg1_b, yaze::app::emu::video::PpuRegisters::W12SEL::invert_bg2_c, yaze::app::emu::video::PpuRegisters::W12SEL::invert_bg2_d, yaze::app::emu::video::PpuRegisters::W34SEL::invert_bg3_e, yaze::app::emu::video::PpuRegisters::W34SEL::invert_bg3_f, yaze::app::emu::video::PpuRegisters::W34SEL::invert_bg4_g, yaze::app::emu::video::PpuRegisters::W34SEL::invert_bg4_h, yaze::app::emu::video::PpuRegisters::WOBJSEL::invert_color_k, yaze::app::emu::video::PpuRegisters::WOBJSEL::invert_color_l, yaze::app::emu::video::PpuRegisters::WOBJSEL::invert_obj_i, yaze::app::emu::video::PpuRegisters::WOBJSEL::invert_obj_j, yaze::app::emu::video::PpuRegisters::WH0::left_position, yaze::app::emu::video::PpuRegisters::WH2::left_position, yaze::app::emu::video::PpuRegisters::M7A, m7a_, yaze::app::emu::video::PpuRegisters::M7B, m7b_, yaze::app::emu::video::PpuRegisters::M7C, m7c_, yaze::app::emu::video::PpuRegisters::M7D, m7d_, yaze::app::emu::video::PpuRegisters::M7SEL, m7sel_, yaze::app::emu::video::PpuRegisters::M7X, m7x_, yaze::app::emu::video::PpuRegisters::M7Y, m7y_, yaze::app::emu::video::PpuRegisters::M7A::matrix_a, yaze::app::emu::video::PpuRegisters::M7B::matrix_b, yaze::app::emu::video::PpuRegisters::M7C::matrix_c, yaze::app::emu::video::PpuRegisters::M7D::matrix_d, yaze::app::emu::video::PpuRegisters::MOSAIC, mosaic_, yaze::app::emu::video::PpuRegisters::Mosaic::mosaic_size, yaze::app::emu::video::OAMSize::name_selection, oam_address_, yaze::app::emu::video::OAMAddress::oam_address_low, yaze::app::emu::video::OAMAddress::oam_address_msb, yaze::app::emu::video::OAMAddress::oam_priority_rotation, oam_size_, yaze::app::emu::video::PpuRegisters::OAMADDH, yaze::app::emu::video::PpuRegisters::OAMADDL, yaze::app::emu::video::PpuRegisters::OAMDATA, yaze::app::emu::video::OAMSize::object_size, yaze::app::emu::video::PpuRegisters::OBJSEL, yaze::app::emu::video::PpuRegisters::VMAIN::remapping, yaze::app::emu::video::PpuRegisters::WH1::right_position, yaze::app::emu::video::PpuRegisters::WH3::right_position, yaze::app::emu::video::PpuRegisters::M7SEL::tilemap_repeat, yaze::app::emu::video::PpuRegisters::TM, tm_, yaze::app::emu::video::PpuRegisters::TMW, tmw_, yaze::app::emu::video::PpuRegisters::TS, ts_, yaze::app::emu::video::PpuRegisters::TSW, tsw_, UpdateModeSettings(), yaze::app::emu::video::PpuRegisters::VMADDH, vmaddh_, yaze::app::emu::video::PpuRegisters::VMADDL, vmaddl_, yaze::app::emu::video::PpuRegisters::VMAIN, vmain_, yaze::app::emu::video::PpuRegisters::W12SEL, w12sel_, yaze::app::emu::video::PpuRegisters::W34SEL, w34sel_, yaze::app::emu::video::PpuRegisters::WH0, wh0_, yaze::app::emu::video::PpuRegisters::WH1, wh1_, yaze::app::emu::video::PpuRegisters::WH2, wh2_, yaze::app::emu::video::PpuRegisters::WH3, wh3_, yaze::app::emu::video::PpuRegisters::WOBJSEL, and wobjsel_.
GetFrameBuffer()
const std::vector< uint8_t > & yaze::app::emu::video::Ppu::GetFrameBuffer () const inline
References frame_buffer_.
GetScreen()
auto yaze::app::emu::video::Ppu::GetScreen () const inline
References screen_.
UpdateModeSettings()
void yaze::app::emu::video::Ppu::UpdateModeSettings () private
References memory_, yaze::app::emu::video::Mode0, yaze::app::emu::video::Mode1, yaze::app::emu::video::Mode2, yaze::app::emu::video::Mode3, yaze::app::emu::video::Mode4, yaze::app::emu::video::Mode5, yaze::app::emu::video::Mode6, yaze::app::emu::video::Mode7, yaze::app::emu::memory::Memory::ReadByte(), UpdatePaletteData(), and UpdateTileData().
Referenced by Notify().
UpdateTileData()
void yaze::app::emu::video::Ppu::UpdateTileData () private
References yaze::app::emu::video::Tilemap::entries, yaze::app::emu::video::SpriteAttributes::hFlip, yaze::app::emu::video::TilemapEntry::hFlip, memory_, yaze::app::emu::video::SpriteAttributes::palette, yaze::app::emu::video::TilemapEntry::palette, yaze::app::emu::video::SpriteAttributes::priority, yaze::app::emu::video::TilemapEntry::priority, yaze::app::emu::memory::Memory::ReadByte(), yaze::app::emu::memory::Memory::ReadWord(), sprites_, yaze::app::emu::video::SpriteAttributes::tile, tile_data_, tile_data_size_, tilemap_, tilemap_base_address_, yaze::app::emu::video::TilemapEntry::tileNumber, yaze::app::emu::video::SpriteAttributes::vFlip, yaze::app::emu::video::TilemapEntry::vFlip, vram_base_address_, yaze::app::emu::video::SpriteAttributes::x, and yaze::app::emu::video::SpriteAttributes::y.
Referenced by UpdateModeSettings().
UpdateTileMapData()
void yaze::app::emu::video::Ppu::UpdateTileMapData () private
Referenced by RenderScanline().
RenderBackground()
void yaze::app::emu::video::Ppu::RenderBackground (int layer) private
References yaze::app::emu::video::PpuRegisters::BG12NBA, yaze::app::emu::video::PpuRegisters::BG1SC, yaze::app::emu::video::PpuRegisters::BG2SC, yaze::app::emu::video::PpuRegisters::BG34NBA, yaze::app::emu::video::PpuRegisters::BG3SC, yaze::app::emu::video::PpuRegisters::BG4SC, memory_, and yaze::app::emu::memory::Memory::ReadByte().
Referenced by RenderScanline().
RenderSprites()
void yaze::app::emu::video::Ppu::RenderSprites () private
Referenced by RenderScanline().
UpdatePaletteData()
void yaze::app::emu::video::Ppu::UpdatePaletteData () private
Referenced by RenderScanline(), and UpdateModeSettings().
ApplyEffects()
void yaze::app::emu::video::Ppu::ApplyEffects () private
Referenced by RenderScanline().
ComposeLayers()
void yaze::app::emu::video::Ppu::ComposeLayers () private
Referenced by RenderScanline().
DisplayFrameBuffer()
void yaze::app::emu::video::Ppu::DisplayFrameBuffer () private
References frame_buffer_, yaze::app::SharedRom::rom(), and screen_.
Referenced by RenderScanline().
Member Data Documentation
memory_
Memory& yaze::app::emu::video::Ppu::memory_ private
Referenced by RenderBackground(), UpdateModeSettings(), and UpdateTileData().
clock_
Clock& yaze::app::emu::video::Ppu::clock_ private
Referenced by Init(), Update(), and UpdateClock().
oam_size_
OAMSize yaze::app::emu::video::Ppu::oam_size_ private
Referenced by Notify().
oam_address_
OAMAddress yaze::app::emu::video::Ppu::oam_address_ private
Referenced by Notify().
mosaic_
Mosaic yaze::app::emu::video::Ppu::mosaic_ private
Referenced by Notify().
bgsc_
std::array<BGSC, 4> yaze::app::emu::video::Ppu::bgsc_ private
Referenced by Notify().
bgnba_
std::array<BGNBA, 4> yaze::app::emu::video::Ppu::bgnba_ private
Referenced by Notify().
bghofs_
std::array<BGHOFS, 4> yaze::app::emu::video::Ppu::bghofs_ private
Referenced by Notify().
bgvofs_
std::array<BGVOFS, 4> yaze::app::emu::video::Ppu::bgvofs_ private
Referenced by Notify().
vmain_
struct VMAIN yaze::app::emu::video::Ppu::vmain_ private
Referenced by Notify().
vmaddl_
struct VMADDL yaze::app::emu::video::Ppu::vmaddl_ private
Referenced by Notify().
vmaddh_
struct VMADDH yaze::app::emu::video::Ppu::vmaddh_ private
Referenced by Notify().
m7sel_
struct M7SEL yaze::app::emu::video::Ppu::m7sel_ private
Referenced by Notify().
m7a_
struct M7A yaze::app::emu::video::Ppu::m7a_ private
Referenced by Notify().
m7b_
struct M7B yaze::app::emu::video::Ppu::m7b_ private
Referenced by Notify().
m7c_
struct M7C yaze::app::emu::video::Ppu::m7c_ private
Referenced by Notify().
m7d_
struct M7D yaze::app::emu::video::Ppu::m7d_ private
Referenced by Notify().
m7x_
struct M7X yaze::app::emu::video::Ppu::m7x_ private
Referenced by Notify().
m7y_
struct M7Y yaze::app::emu::video::Ppu::m7y_ private
Referenced by Notify().
cgadd_
struct CGADD yaze::app::emu::video::Ppu::cgadd_ private
Referenced by Notify().
cgdata_
struct CGDATA yaze::app::emu::video::Ppu::cgdata_ private
w12sel_
struct W12SEL yaze::app::emu::video::Ppu::w12sel_ private
Referenced by Notify().
w34sel_
struct W34SEL yaze::app::emu::video::Ppu::w34sel_ private
Referenced by Notify().
wobjsel_
struct WOBJSEL yaze::app::emu::video::Ppu::wobjsel_ private
Referenced by Notify().
wh0_
struct WH0 yaze::app::emu::video::Ppu::wh0_ private
Referenced by Notify().
wh1_
struct WH1 yaze::app::emu::video::Ppu::wh1_ private
Referenced by Notify().
wh2_
struct WH2 yaze::app::emu::video::Ppu::wh2_ private
Referenced by Notify().
wh3_
struct WH3 yaze::app::emu::video::Ppu::wh3_ private
Referenced by Notify().
wbglog_
struct WBGLOG yaze::app::emu::video::Ppu::wbglog_ private
wobjlog_
struct WOBJLOG yaze::app::emu::video::Ppu::wobjlog_ private
tm_
struct TM yaze::app::emu::video::Ppu::tm_ private
Referenced by Notify().
ts_
struct TS yaze::app::emu::video::Ppu::ts_ private
Referenced by Notify().
tsw_
struct TSW yaze::app::emu::video::Ppu::tsw_ private
Referenced by Notify().
tmw_
struct TMW yaze::app::emu::video::Ppu::tmw_ private
Referenced by Notify().
setini_
struct SETINI yaze::app::emu::video::Ppu::setini_ private
tilemap_
Tilemap yaze::app::emu::video::Ppu::tilemap_ private
Referenced by UpdateTileData().
bg_mode_
BackgroundMode yaze::app::emu::video::Ppu::bg_mode_ private
bg_layers_
std::array<BackgroundLayer, 4> yaze::app::emu::video::Ppu::bg_layers_ private
sprites_
std::vector<SpriteAttributes> yaze::app::emu::video::Ppu::sprites_ private
Referenced by UpdateTileData().
tile_data_
std::vector<uint8_t> yaze::app::emu::video::Ppu::tile_data_ private
Referenced by UpdateTileData().
frame_buffer_
std::vector<uint8_t> yaze::app::emu::video::Ppu::frame_buffer_ private
Referenced by DisplayFrameBuffer(), GetFrameBuffer(), Init(), RenderScanline(), and Reset().
screen_
std::shared_ptr<gfx::Bitmap> yaze::app::emu::video::Ppu::screen_ private
Referenced by DisplayFrameBuffer(), GetScreen(), and Init().
tile_data_size_
uint16_t yaze::app::emu::video::Ppu::tile_data_size_ private
Referenced by UpdateTileData().
vram_base_address_
uint16_t yaze::app::emu::video::Ppu::vram_base_address_ private
Referenced by UpdateTileData().
tilemap_base_address_
uint16_t yaze::app::emu::video::Ppu::tilemap_base_address_ private
Referenced by UpdateTileData().
screen_brightness_
uint16_t yaze::app::emu::video::Ppu::screen_brightness_ = 0x00 private
enable_forced_blanking_
bool yaze::app::emu::video::Ppu::enable_forced_blanking_ = false private
Referenced by Notify().
cycle_count_
int yaze::app::emu::video::Ppu::cycle_count_ = 0 private
Referenced by UpdateInternalState().
current_scanline_
int yaze::app::emu::video::Ppu::current_scanline_ = 0 private
Referenced by Update(), and UpdateInternalState().
cyclesPerScanline
const int yaze::app::emu::video::Ppu::cyclesPerScanline = 341 private
Referenced by UpdateInternalState().
totalScanlines
const int yaze::app::emu::video::Ppu::totalScanlines = 262 private
Referenced by UpdateInternalState().
visibleScanlines
const int yaze::app::emu::video::Ppu::visibleScanlines = 224 private
Referenced by Update().
The documentation for this class was generated from the following files:
src/app/emu/video/ppu.h
src/app/emu/video/ppu.cc