yaze: yaze::test::SpriteBuilderTest Class Reference
yaze::test::SpriteBuilderTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Protected Attributes
SpriteBuilder sprite
Detailed Description
Definition at line 11 of file sprite_builder_test.cc.
Member Function Documentation
SetUp()
void yaze::test::SpriteBuilderTest::SetUp () inline override protected
Definition at line 13 of file sprite_builder_test.cc.
References yaze::zelda3::SpriteBuilder::AddAction(), yaze::zelda3::SpriteAction::AddCustomInstruction(), yaze::zelda3::SpriteBuilder::AddFunction(), yaze::zelda3::SpriteAction::AddInstruction(), yaze::zelda3::SpriteInstruction::ApplySpeedTowardsPlayer(), yaze::zelda3::SpriteInstruction::BehaveAsBarrier(), yaze::zelda3::SpriteInstruction::BounceFromTileCollision(), yaze::zelda3::SpriteAction::Create(), yaze::zelda3::SpriteBuilder::Create(), yaze::zelda3::SpriteInstruction::JumpToFunction(), yaze::zelda3::SpriteInstruction::MoveXyz(), yaze::zelda3::SpriteInstruction::PlayAnimation(), yaze::zelda3::SpriteBuilder::SetGlobalAction(), yaze::zelda3::SpriteAction::SetNextAction(), yaze::zelda3::SpriteBuilder::SetProperty(), and sprite.
TearDown()
void yaze::test::SpriteBuilderTest::TearDown () inline override protected
Definition at line 51 of file sprite_builder_test.cc.
Member Data Documentation
sprite
SpriteBuilder yaze::test::SpriteBuilderTest::sprite protected
Definition at line 53 of file sprite_builder_test.cc.
Referenced by SetUp().
The documentation for this class was generated from the following file:
src/test/zelda3/sprite_builder_test.cc