yaze: yaze::emu::memory::Memory Class Reference
yaze::emu::memory::Memory Class Reference abstract
Memory interface.
#include <memory.h>
Public Member Functions
virtual ~Memory ()=default
virtual uint8_t ReadByte (uint32_t address) const =0
virtual uint16_t ReadWord (uint32_t address) const =0
virtual uint32_t ReadWordLong (uint32_t address) const =0
virtual std::vector< uint8_t > ReadByteVector (uint32_t address, uint16_t length) const =0
virtual void WriteByte (uint32_t address, uint8_t value)=0
virtual void WriteWord (uint32_t address, uint16_t value)=0
virtual void WriteLong (uint32_t address, uint32_t value)=0
virtual void PushByte (uint8_t value)=0
virtual uint8_t PopByte ()=0
virtual void PushWord (uint16_t value)=0
virtual uint16_t PopWord ()=0
virtual void PushLong (uint32_t value)=0
virtual uint32_t PopLong ()=0
virtual uint16_t SP () const =0
virtual void SetSP (uint16_t value)=0
virtual void ClearMemory ()=0
virtual uint8_t operator[] (int i) const =0
virtual uint8_t at (int i) const =0
virtual uint8_t open_bus () const =0
virtual void set_open_bus (uint8_t value)=0
virtual bool hdma_init_requested () const =0
virtual bool hdma_run_requested () const =0
virtual void init_hdma_request ()=0
virtual void run_hdma_request ()=0
virtual void set_hdma_run_requested (bool value)=0
virtual void set_hdma_init_requested (bool value)=0
virtual void set_pal_timing (bool value)=0
virtual void set_h_pos (uint16_t value)=0
virtual void set_v_pos (uint16_t value)=0
virtual auto h_pos () const -> uint16_t=0
virtual auto v_pos () const -> uint16_t=0
virtual auto pal_timing () const -> bool=0
Detailed Description
Memory interface.
Definition at line 47 of file memory.h.
Constructor & Destructor Documentation
~Memory()
virtual yaze::emu::memory::Memory::~Memory () virtual default
Member Function Documentation
ReadByte()
virtual uint8_t yaze::emu::memory::Memory::ReadByte (uint32_t address) const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init(), and yaze::test::emu::TEST_F().
ReadWord()
virtual uint16_t yaze::emu::memory::Memory::ReadWord (uint32_t address) const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
ReadWordLong()
virtual uint32_t yaze::emu::memory::Memory::ReadWordLong (uint32_t address) const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
ReadByteVector()
virtual std::vector< uint8_t > yaze::emu::memory::Memory::ReadByteVector (uint32_t address, uint16_t length) const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
WriteByte()
virtual void yaze::emu::memory::Memory::WriteByte (uint32_t address, uint8_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
WriteWord()
virtual void yaze::emu::memory::Memory::WriteWord (uint32_t address, uint16_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
WriteLong()
virtual void yaze::emu::memory::Memory::WriteLong (uint32_t address, uint32_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
PushByte()
virtual void yaze::emu::memory::Memory::PushByte (uint8_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init(), yaze::emu::memory::MemoryImpl::PushLong(), and yaze::emu::memory::MemoryImpl::PushWord().
PopByte()
virtual uint8_t yaze::emu::memory::Memory::PopByte () pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init(), yaze::emu::memory::MemoryImpl::PopLong(), and yaze::emu::memory::MemoryImpl::PopWord().
PushWord()
virtual void yaze::emu::memory::Memory::PushWord (uint16_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
PopWord()
virtual uint16_t yaze::emu::memory::Memory::PopWord () pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
PushLong()
virtual void yaze::emu::memory::Memory::PushLong (uint32_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
PopLong()
virtual uint32_t yaze::emu::memory::Memory::PopLong () pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init().
SP()
virtual uint16_t yaze::emu::memory::Memory::SP () const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init(), and yaze::emu::Cpu::SP().
SetSP()
virtual void yaze::emu::memory::Memory::SetSP (uint16_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init(), and yaze::emu::Cpu::SetSP().
ClearMemory()
virtual void yaze::emu::memory::Memory::ClearMemory () pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::memory::MockMemory::Init(), and yaze::test::emu::CpuTest::SetUp().
operator[]()
virtual uint8_t yaze::emu::memory::Memory::operator[] (int i) const pure virtual
Implemented in yaze::emu::memory::MemoryImpl, and yaze::emu::memory::MockMemory.
at()
virtual uint8_t yaze::emu::memory::Memory::at (int i) const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
open_bus()
virtual uint8_t yaze::emu::memory::Memory::open_bus () const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::video::Ppu::Read().
set_open_bus()
virtual void yaze::emu::memory::Memory::set_open_bus (uint8_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
hdma_init_requested()
virtual bool yaze::emu::memory::Memory::hdma_init_requested () const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
hdma_run_requested()
virtual bool yaze::emu::memory::Memory::hdma_run_requested () const pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
init_hdma_request()
virtual void yaze::emu::memory::Memory::init_hdma_request () pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
run_hdma_request()
virtual void yaze::emu::memory::Memory::run_hdma_request () pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
set_hdma_run_requested()
virtual void yaze::emu::memory::Memory::set_hdma_run_requested (bool value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
set_hdma_init_requested()
virtual void yaze::emu::memory::Memory::set_hdma_init_requested (bool value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
set_pal_timing()
virtual void yaze::emu::memory::Memory::set_pal_timing (bool value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
set_h_pos()
virtual void yaze::emu::memory::Memory::set_h_pos (uint16_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
set_v_pos()
virtual void yaze::emu::memory::Memory::set_v_pos (uint16_t value) pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
h_pos()
virtual auto yaze::emu::memory::Memory::h_pos () const -> uint16_t pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::video::Ppu::LatchHV().
v_pos()
virtual auto yaze::emu::memory::Memory::v_pos () const -> uint16_t pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::video::Ppu::LatchHV(), and yaze::emu::video::Ppu::Write().
pal_timing()
virtual auto yaze::emu::memory::Memory::pal_timing () const -> bool pure virtual
Implemented in yaze::emu::memory::MemoryImpl.
Referenced by yaze::emu::video::Ppu::Read().
The documentation for this class was generated from the following file:
src/app/emu/memory/memory.h