yaze: yaze::emu::MockClock Class Reference
yaze::emu::MockClock Class Reference
Mock CPU class for testing.
#include <mock_memory.h>
Public Member Functions
MOCK_METHOD (void, UpdateClock,(double delta),(override))
MOCK_METHOD (unsigned long long, GetCycleCount,(),(const, override))
MOCK_METHOD (void, ResetAccumulatedTime,(),(override))
MOCK_METHOD (void, SetFrequency,(float new_frequency),(override))
MOCK_METHOD (float, GetFrequency,(),(const, override))
Public Member Functions inherited from yaze::emu::Clock
virtual ~Clock ()=default
virtual void UpdateClock (double delta)=0
virtual unsigned long long GetCycleCount () const =0
virtual void ResetAccumulatedTime ()=0
virtual void SetFrequency (float new_frequency)=0
virtual float GetFrequency () const =0
Detailed Description
Mock CPU class for testing.
Definition at line 17 of file mock_memory.h.
Member Function Documentation
MOCK_METHOD() [1/5]
yaze::emu::MockClock::MOCK_METHOD (void , UpdateClock , (double delta) , (override))
References yaze::emu::Clock::UpdateClock().
MOCK_METHOD() [2/5]
yaze::emu::MockClock::MOCK_METHOD (unsigned long long , GetCycleCount , () , (const, override))
References yaze::emu::Clock::GetCycleCount().
MOCK_METHOD() [3/5]
yaze::emu::MockClock::MOCK_METHOD (void , ResetAccumulatedTime , () , (override))
References yaze::emu::Clock::ResetAccumulatedTime().
MOCK_METHOD() [4/5]
yaze::emu::MockClock::MOCK_METHOD (void , SetFrequency , (float new_frequency) , (override))
References yaze::emu::Clock::SetFrequency().
MOCK_METHOD() [5/5]
yaze::emu::MockClock::MOCK_METHOD (float , GetFrequency , () , (const, override))
References yaze::emu::Clock::GetFrequency().
The documentation for this class was generated from the following file:
src/test/mocks/mock_memory.h