yaze: yaze::app::zelda3::SpriteBuilder Class Reference
yaze::app::zelda3::SpriteBuilder Class Reference
#include <sprite_builder.h>
Public Member Functions
SpriteBuilder & SetProperty (const std::string &propertyName, const std::string &value)
SpriteBuilder & SetProperty (const std::string &propertyName, int value)
SpriteBuilder & SetProperty (const std::string &propertyName, bool value)
SpriteBuilder & AddAction (const SpriteAction &action)
SpriteBuilder & SetGlobalAction (const SpriteAction &action)
SpriteBuilder & AddFunction (const std::string &asmCode)
SpriteBuilder & AddFunction (const SpriteAction &action)
std::string BuildProperties () const
std::string Build () const
Static Public Member Functions
static SpriteBuilder Create (const std::string &spriteName)
Private Attributes
std::string name
std::array< std::string, 27 > properties
std::vector< SpriteAction > actions
SpriteAction globalAction
std::vector< SpriteAction > functions
Member Function Documentation
Create()
SpriteBuilder yaze::app::zelda3::SpriteBuilder::Create (const std::string & spriteName) static
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
SetProperty() [1/3]
SpriteBuilder & yaze::app::zelda3::SpriteBuilder::SetProperty (const std::string & propertyName, const std::string & value)
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
SetProperty() [2/3]
SpriteBuilder & yaze::app::zelda3::SpriteBuilder::SetProperty (const std::string & propertyName, int value)
SetProperty() [3/3]
SpriteBuilder & yaze::app::zelda3::SpriteBuilder::SetProperty (const std::string & propertyName, bool value)
AddAction()
SpriteBuilder & yaze::app::zelda3::SpriteBuilder::AddAction (const SpriteAction & action)
SetGlobalAction()
SpriteBuilder & yaze::app::zelda3::SpriteBuilder::SetGlobalAction (const SpriteAction & action)
AddFunction() [1/2]
SpriteBuilder & yaze::app::zelda3::SpriteBuilder::AddFunction (const std::string & asmCode)
AddFunction() [2/2]
SpriteBuilder & yaze::app::zelda3::SpriteBuilder::AddFunction (const SpriteAction & action)
BuildProperties()
std::string yaze::app::zelda3::SpriteBuilder::BuildProperties () const
References yaze::app::zelda3::kSpriteProperties, and properties.
Referenced by Build().
Build()
std::string yaze::app::zelda3::SpriteBuilder::Build () const
References BuildProperties().
Member Data Documentation
name
std::string yaze::app::zelda3::SpriteBuilder::name private
properties
std::array<std::string, 27> yaze::app::zelda3::SpriteBuilder::properties private
Referenced by BuildProperties().
actions
std::vector<SpriteAction> yaze::app::zelda3::SpriteBuilder::actions private
globalAction
SpriteAction yaze::app::zelda3::SpriteBuilder::globalAction private
functions
std::vector<SpriteAction> yaze::app::zelda3::SpriteBuilder::functions private
The documentation for this class was generated from the following files:
src/app/zelda3/sprite/sprite_builder.h
src/app/zelda3/sprite/sprite_builder.cc