yaze: yaze::app::core::ExperimentFlags Class Reference
yaze::app::core::ExperimentFlags Class Reference
A class to manage experimental feature flags.
#include <common.h>
Classes
struct Flags
Public Member Functions
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
std::string Serialize () const
Static Private Attributes
static std::shared_ptr< Flags > flags_
Detailed Description
A class to manage experimental feature flags.
Definition at line 30 of file common.h.
Constructor & Destructor Documentation
ExperimentFlags()
yaze::app::core::ExperimentFlags::ExperimentFlags () default
~ExperimentFlags()
virtual yaze::app::core::ExperimentFlags::~ExperimentFlags () virtual default
Member Function Documentation
flags()
auto yaze::app::core::ExperimentFlags::flags () const inline
Definition at line 94 of file common.h.
References flags(), and flags_.
Referenced by yaze::app::core::Controller::CreateGuiContext(), yaze::app::core::Controller::CreateSDL_Window(), yaze::app::zelda3::overworld::Overworld::CreateTile32Tilemap(), yaze::app::editor::OverworldEditor::DrawFullscreenCanvas(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), flags(), yaze::app::editor::DungeonEditor::Initialize(), yaze::app::zelda3::overworld::Overworld::Load(), yaze::app::zelda3::overworld::Overworld::LoadExits(), yaze::app::editor::OverworldEditor::LoadGraphics(), yaze::app::emu::Cpu::LogInstructions(), yaze::app::core::Renderer::RenderBitmap(), yaze::app::editor::OverworldEditor::Save(), yaze::app::zelda3::overworld::Overworld::SaveItems(), yaze::app::editor::EditorManager::SaveRom(), yaze::app::Rom::SaveToFile(), and yaze::app::core::Renderer::UpdateBitmap().
mutable_flags()
Flags * yaze::app::core::ExperimentFlags::mutable_flags () inline
Definition at line 101 of file common.h.
References flags_.
Referenced by yaze::app::editor::FlagsMenu::Draw().
Serialize()
std::string yaze::app::core::ExperimentFlags::Serialize () const inline
Definition at line 107 of file common.h.
References flags_.
Member Data Documentation
flags_
std::shared_ptr< ExperimentFlags::Flags > yaze::app::core::ExperimentFlags::flags_ static private
Definition at line 145 of file common.h.
Referenced by flags(), mutable_flags(), and Serialize().
The documentation for this class was generated from the following files:
src/app/core/common.h
src/app/core/common.cc