yaze: yaze::zelda3::SpriteBuilder Class Reference
yaze::zelda3::SpriteBuilder Class Reference
#include <sprite_builder.h>
Public Member Functions
SpriteBuilder & SetProperty (const std::string &propertyName, const std::string &value)
SpriteBuilder & SetProperty (const std::string &propertyName, int value)
SpriteBuilder & SetProperty (const std::string &propertyName, bool value)
SpriteBuilder & AddAction (const SpriteAction &action)
SpriteBuilder & SetGlobalAction (const SpriteAction &action)
SpriteBuilder & AddFunction (const std::string &asmCode)
SpriteBuilder & AddFunction (const SpriteAction &action)
std::string BuildProperties () const
std::string Build () const
Static Public Member Functions
static SpriteBuilder Create (const std::string &spriteName)
Private Attributes
std::string name
std::array< std::string, 27 > properties
std::vector< SpriteAction > actions
SpriteAction globalAction
std::vector< SpriteAction > functions
Detailed Description
Definition at line 92 of file sprite_builder.h.
Member Function Documentation
Create()
SpriteBuilder yaze::zelda3::SpriteBuilder::Create (const std::string & spriteName) static
Definition at line 9 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
SetProperty() [1/3]
SpriteBuilder & yaze::zelda3::SpriteBuilder::SetProperty (const std::string & propertyName, const std::string & value)
Definition at line 15 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
SetProperty() [2/3]
SpriteBuilder & yaze::zelda3::SpriteBuilder::SetProperty (const std::string & propertyName, int value)
Definition at line 20 of file sprite_builder.cc.
SetProperty() [3/3]
SpriteBuilder & yaze::zelda3::SpriteBuilder::SetProperty (const std::string & propertyName, bool value)
Definition at line 25 of file sprite_builder.cc.
AddAction()
SpriteBuilder & yaze::zelda3::SpriteBuilder::AddAction (const SpriteAction & action)
Definition at line 30 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
SetGlobalAction()
SpriteBuilder & yaze::zelda3::SpriteBuilder::SetGlobalAction (const SpriteAction & action)
Definition at line 34 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
AddFunction() [1/2]
SpriteBuilder & yaze::zelda3::SpriteBuilder::AddFunction (const std::string & asmCode)
Definition at line 42 of file sprite_builder.cc.
Referenced by yaze::test::SpriteBuilderTest::SetUp().
AddFunction() [2/2]
SpriteBuilder & yaze::zelda3::SpriteBuilder::AddFunction (const SpriteAction & action)
Definition at line 38 of file sprite_builder.cc.
BuildProperties()
std::string yaze::zelda3::SpriteBuilder::BuildProperties () const
Definition at line 46 of file sprite_builder.cc.
References yaze::zelda3::kSpriteProperties, and properties.
Referenced by Build().
Build()
std::string yaze::zelda3::SpriteBuilder::Build () const
Definition at line 57 of file sprite_builder.cc.
References BuildProperties().
Member Data Documentation
name
std::string yaze::zelda3::SpriteBuilder::name private
Definition at line 119 of file sprite_builder.h.
properties
std::array<std::string, 27> yaze::zelda3::SpriteBuilder::properties private
Definition at line 120 of file sprite_builder.h.
Referenced by BuildProperties().
actions
std::vector<SpriteAction> yaze::zelda3::SpriteBuilder::actions private
Definition at line 121 of file sprite_builder.h.
globalAction
SpriteAction yaze::zelda3::SpriteBuilder::globalAction private
Definition at line 122 of file sprite_builder.h.
functions
std::vector<SpriteAction> yaze::zelda3::SpriteBuilder::functions private
Definition at line 123 of file sprite_builder.h.
The documentation for this class was generated from the following files:
src/app/zelda3/sprite/sprite_builder.h
src/app/zelda3/sprite/sprite_builder.cc