yaze: yaze::app::editor::palette_internal::PaletteEditorHistory Class Reference
yaze::app::editor::palette_internal::PaletteEditorHistory Class Reference
#include <palette_editor.h>
Public Member Functions
void RecordChange (const std::string &group_name, size_t palette_index, size_t color_index, const gfx::SnesColor &original_color, const gfx::SnesColor &new_color)
gfx::SnesColor RestoreOriginalColor (const std::string &group_name, size_t palette_index, size_t color_index) const
auto size () const
gfx::SnesColor & GetModifiedColor (size_t index)
gfx::SnesColor & GetOriginalColor (size_t index)
const std::deque< PaletteChange > & GetRecentChanges () const
Private Attributes
std::deque< PaletteChange > recent_changes_
Static Private Attributes
static const size_t kMaxHistorySize = 50
Detailed Description
Definition at line 26 of file palette_editor.h.
Member Function Documentation
RecordChange()
void yaze::app::editor::palette_internal::PaletteEditorHistory::RecordChange (const std::string & group_name, size_t palette_index, size_t color_index, const gfx::SnesColor & original_color, const gfx::SnesColor & new_color) inline
Definition at line 28 of file palette_editor.h.
References kMaxHistorySize, and recent_changes_.
Referenced by yaze::app::editor::PaletteEditor::HandleColorPopup().
RestoreOriginalColor()
gfx::SnesColor yaze::app::editor::palette_internal::PaletteEditorHistory::RestoreOriginalColor (const std::string & group_name, size_t palette_index, size_t color_index) const inline
Definition at line 39 of file palette_editor.h.
References recent_changes_.
size()
auto yaze::app::editor::palette_internal::PaletteEditorHistory::size () const inline
Definition at line 52 of file palette_editor.h.
References recent_changes_.
Referenced by yaze::app::editor::PaletteEditor::DrawModifiedColors().
GetModifiedColor()
gfx::SnesColor & yaze::app::editor::palette_internal::PaletteEditorHistory::GetModifiedColor (size_t index) inline
Definition at line 54 of file palette_editor.h.
References recent_changes_.
Referenced by yaze::app::editor::PaletteEditor::DrawModifiedColors().
GetOriginalColor()
gfx::SnesColor & yaze::app::editor::palette_internal::PaletteEditorHistory::GetOriginalColor (size_t index) inline
Definition at line 57 of file palette_editor.h.
References recent_changes_.
Referenced by yaze::app::editor::PaletteEditor::DrawModifiedColors().
GetRecentChanges()
const std::deque< PaletteChange > & yaze::app::editor::palette_internal::PaletteEditorHistory::GetRecentChanges () const inline
Definition at line 61 of file palette_editor.h.
References recent_changes_.
Member Data Documentation
recent_changes_
std::deque<PaletteChange> yaze::app::editor::palette_internal::PaletteEditorHistory::recent_changes_ private
Definition at line 66 of file palette_editor.h.
Referenced by GetModifiedColor(), GetOriginalColor(), GetRecentChanges(), RecordChange(), RestoreOriginalColor(), and size().
kMaxHistorySize
const size_t yaze::app::editor::palette_internal::PaletteEditorHistory::kMaxHistorySize = 50 static private
Definition at line 67 of file palette_editor.h.
Referenced by RecordChange().
The documentation for this class was generated from the following file:
src/app/editor/graphics/palette_editor.h