yaze: yaze::core::ExperimentFlags Class Reference
yaze::core::ExperimentFlags Class Reference
A class to manage experimental feature flags.
#include <common.h>
Classes
struct Flags
Public Member Functions
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
std::string Serialize () const
Static Private Attributes
static std::shared_ptr< Flags > flags_
Detailed Description
A class to manage experimental feature flags.
Definition at line 40 of file common.h.
Constructor & Destructor Documentation
ExperimentFlags()
yaze::core::ExperimentFlags::ExperimentFlags () default
~ExperimentFlags()
virtual yaze::core::ExperimentFlags::~ExperimentFlags () virtual default
Member Function Documentation
flags()
auto yaze::core::ExperimentFlags::flags () const inline
Definition at line 107 of file common.h.
References flags(), and flags_.
Referenced by yaze::core::Controller::CreateGuiContext(), yaze::zelda3::Overworld::CreateTile32Tilemap(), yaze::core::Controller::CreateWindow(), yaze::editor::OverworldEditor::DrawFullscreenCanvas(), yaze::editor::OverworldEditor::DrawOverworldCanvas(), flags(), yaze::editor::DungeonEditor::Initialize(), yaze::zelda3::Overworld::Load(), yaze::zelda3::Overworld::LoadExits(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::emu::Cpu::LogInstructions(), yaze::editor::OverworldEditor::Save(), yaze::zelda3::Overworld::SaveItems(), yaze::editor::EditorManager::SaveRom(), and yaze::Rom::SaveToFile().
mutable_flags()
Flags * yaze::core::ExperimentFlags::mutable_flags () inline
Definition at line 114 of file common.h.
References flags_.
Referenced by yaze::editor::FlagsMenu::Draw().
Serialize()
std::string yaze::core::ExperimentFlags::Serialize () const inline
Definition at line 120 of file common.h.
References flags_.
Member Data Documentation
flags_
std::shared_ptr< ExperimentFlags::Flags > yaze::core::ExperimentFlags::flags_ static private
Definition at line 158 of file common.h.
Referenced by flags(), mutable_flags(), and Serialize().
The documentation for this class was generated from the following files:
src/app/core/common.h
src/app/core/common.cc