yaze: PythonYazeExtensionWrapper Class Reference
PythonYazeExtensionWrapper Class Reference
Public Member Functions
PythonYazeExtensionWrapper ()
const char * getName () const
const char * getVersion () const
void setName (const std::string &name)
void setVersion (const std::string &version)
void setInitialize (boost::python::object func)
void setCleanup (boost::python::object func)
void setManipulateRom (boost::python::object func)
void setExtendUI (boost::python::object func)
void setRegisterCommands (boost::python::object func)
void setRegisterCustomTools (boost::python::object func)
void setRegisterEventHooks (boost::python::object func)
yaze_extension * getExtension ()
Static Private Member Functions
static void initialize (yaze_editor_context *context)
static void cleanup ()
static void manipulate_rom (z3_rom *rom)
static void extend_ui (yaze_editor_context *context)
static void register_commands ()
static void register_custom_tools ()
static void register_event_hooks (yaze_event_type event, yaze_event_hook_func hook)
Private Attributes
yaze_extension ext_
Static Private Attributes
static boost::python::object initializeFunc_
static boost::python::object cleanupFunc_
static boost::python::object manipulateRomFunc_
static boost::python::object extendUIFunc_
static boost::python::object registerCommandsFunc_
static boost::python::object registerCustomToolsFunc_
static boost::python::object registerEventHooksFunc_
Detailed Description
Definition at line 9 of file yaze_py.cc.
Constructor & Destructor Documentation
PythonYazeExtensionWrapper()
PythonYazeExtensionWrapper::PythonYazeExtensionWrapper () inline
Definition at line 11 of file yaze_py.cc.
References yaze_extension::cleanup, ext_, yaze_extension::extend_ui, yaze_extension::initialize, yaze_extension::manipulate_rom, yaze_extension::register_commands, yaze_extension::register_custom_tools, and yaze_extension::register_event_hooks.
Member Function Documentation
getName()
const char * PythonYazeExtensionWrapper::getName () const inline
Definition at line 22 of file yaze_py.cc.
References ext_, and yaze_extension::name.
Referenced by BOOST_PYTHON_MODULE().
getVersion()
const char * PythonYazeExtensionWrapper::getVersion () const inline
Definition at line 24 of file yaze_py.cc.
References ext_, and yaze_extension::version.
Referenced by BOOST_PYTHON_MODULE().
setName()
void PythonYazeExtensionWrapper::setName (const std::string & name) inline
Definition at line 26 of file yaze_py.cc.
References ext_, and yaze_extension::name.
Referenced by BOOST_PYTHON_MODULE().
setVersion()
void PythonYazeExtensionWrapper::setVersion (const std::string & version) inline
Definition at line 28 of file yaze_py.cc.
References ext_, and yaze_extension::version.
Referenced by BOOST_PYTHON_MODULE().
setInitialize()
void PythonYazeExtensionWrapper::setInitialize (boost::python::object func) inline
Definition at line 32 of file yaze_py.cc.
References ext_, initialize(), yaze_extension::initialize, and initializeFunc_.
Referenced by BOOST_PYTHON_MODULE().
setCleanup()
void PythonYazeExtensionWrapper::setCleanup (boost::python::object func) inline
Definition at line 37 of file yaze_py.cc.
References cleanup(), yaze_extension::cleanup, cleanupFunc_, and ext_.
Referenced by BOOST_PYTHON_MODULE().
setManipulateRom()
void PythonYazeExtensionWrapper::setManipulateRom (boost::python::object func) inline
Definition at line 42 of file yaze_py.cc.
References ext_, manipulate_rom(), yaze_extension::manipulate_rom, and manipulateRomFunc_.
Referenced by BOOST_PYTHON_MODULE().
setExtendUI()
void PythonYazeExtensionWrapper::setExtendUI (boost::python::object func) inline
Definition at line 47 of file yaze_py.cc.
References ext_, extend_ui(), yaze_extension::extend_ui, and extendUIFunc_.
Referenced by BOOST_PYTHON_MODULE().
setRegisterCommands()
void PythonYazeExtensionWrapper::setRegisterCommands (boost::python::object func) inline
Definition at line 52 of file yaze_py.cc.
References ext_, register_commands(), yaze_extension::register_commands, and registerCommandsFunc_.
Referenced by BOOST_PYTHON_MODULE().
setRegisterCustomTools()
void PythonYazeExtensionWrapper::setRegisterCustomTools (boost::python::object func) inline
Definition at line 57 of file yaze_py.cc.
References ext_, register_custom_tools(), yaze_extension::register_custom_tools, and registerCustomToolsFunc_.
Referenced by BOOST_PYTHON_MODULE().
setRegisterEventHooks()
void PythonYazeExtensionWrapper::setRegisterEventHooks (boost::python::object func) inline
Definition at line 63 of file yaze_py.cc.
References ext_, register_event_hooks(), yaze_extension::register_event_hooks, and registerEventHooksFunc_.
Referenced by BOOST_PYTHON_MODULE().
getExtension()
yaze_extension * PythonYazeExtensionWrapper::getExtension () inline
Definition at line 69 of file yaze_py.cc.
References ext_.
Referenced by BOOST_PYTHON_MODULE().
initialize()
static void PythonYazeExtensionWrapper::initialize (yaze_editor_context * context) inline static private
Definition at line 72 of file yaze_py.cc.
References initializeFunc_.
Referenced by setInitialize().
cleanup()
static void PythonYazeExtensionWrapper::cleanup () inline static private
Definition at line 76 of file yaze_py.cc.
References cleanupFunc_.
Referenced by setCleanup().
manipulate_rom()
static void PythonYazeExtensionWrapper::manipulate_rom (z3_rom * rom) inline static private
Definition at line 78 of file yaze_py.cc.
References manipulateRomFunc_.
Referenced by setManipulateRom().
extend_ui()
static void PythonYazeExtensionWrapper::extend_ui (yaze_editor_context * context) inline static private
Definition at line 82 of file yaze_py.cc.
References extendUIFunc_.
Referenced by setExtendUI().
register_commands()
static void PythonYazeExtensionWrapper::register_commands () inline static private
Definition at line 86 of file yaze_py.cc.
References registerCommandsFunc_.
Referenced by setRegisterCommands().
register_custom_tools()
static void PythonYazeExtensionWrapper::register_custom_tools () inline static private
Definition at line 90 of file yaze_py.cc.
References registerCustomToolsFunc_.
Referenced by setRegisterCustomTools().
register_event_hooks()
static void PythonYazeExtensionWrapper::register_event_hooks (yaze_event_type event, yaze_event_hook_func hook) inline static private
Definition at line 94 of file yaze_py.cc.
References registerEventHooksFunc_.
Referenced by setRegisterEventHooks().
Member Data Documentation
ext_
yaze_extension PythonYazeExtensionWrapper::ext_ private
Definition at line 99 of file yaze_py.cc.
Referenced by getExtension(), getName(), getVersion(), PythonYazeExtensionWrapper(), setCleanup(), setExtendUI(), setInitialize(), setManipulateRom(), setName(), setRegisterCommands(), setRegisterCustomTools(), setRegisterEventHooks(), and setVersion().
initializeFunc_
boost::python::object PythonYazeExtensionWrapper::initializeFunc_ static private
Definition at line 100 of file yaze_py.cc.
Referenced by initialize(), and setInitialize().
cleanupFunc_
boost::python::object PythonYazeExtensionWrapper::cleanupFunc_ static private
Definition at line 101 of file yaze_py.cc.
Referenced by cleanup(), and setCleanup().
manipulateRomFunc_
boost::python::object PythonYazeExtensionWrapper::manipulateRomFunc_ static private
Definition at line 102 of file yaze_py.cc.
Referenced by manipulate_rom(), and setManipulateRom().
extendUIFunc_
boost::python::object PythonYazeExtensionWrapper::extendUIFunc_ static private
Definition at line 103 of file yaze_py.cc.
Referenced by extend_ui(), and setExtendUI().
registerCommandsFunc_
boost::python::object PythonYazeExtensionWrapper::registerCommandsFunc_ static private
Definition at line 104 of file yaze_py.cc.
Referenced by register_commands(), and setRegisterCommands().
registerCustomToolsFunc_
boost::python::object PythonYazeExtensionWrapper::registerCustomToolsFunc_ static private
Definition at line 105 of file yaze_py.cc.
Referenced by register_custom_tools(), and setRegisterCustomTools().
registerEventHooksFunc_
boost::python::object PythonYazeExtensionWrapper::registerEventHooksFunc_ static private
Definition at line 106 of file yaze_py.cc.
Referenced by register_event_hooks(), and setRegisterEventHooks().
The documentation for this class was generated from the following file:
src/py/yaze_py.cc