yaze: yaze::app::core::NotifyValue< T > Class Template Reference
yaze::app::core::NotifyValue< T > Class Template Reference
A class to manage a value that can be modified and notify when it changes.
#include <common.h>
Public Member Functions
NotifyValue ()
NotifyValue (const T &value)
void set (const T &value)
const T & get ()
T & mutable_get ()
void apply_changes ()
void operator= (const T &value)
operator T ()
bool modified () const
Private Attributes
T value_
bool modified_
T temp_value_
Detailed Description
template<typename T>
class yaze::app::core::NotifyValue< T >
A class to manage a value that can be modified and notify when it changes.
Definition at line 122 of file common.h.
Constructor & Destructor Documentation
NotifyValue() [1/2]
template<typename T > yaze::app::core::NotifyValue< T >::NotifyValue () inline
Definition at line 124 of file common.h.
NotifyValue() [2/2]
template<typename T > yaze::app::core::NotifyValue< T >::NotifyValue (const T & value) inline
Definition at line 125 of file common.h.
Member Function Documentation
set()
template<typename T > void yaze::app::core::NotifyValue< T >::set (const T & value) inline
Definition at line 128 of file common.h.
References yaze::app::core::NotifyValue< T >::modified_, and yaze::app::core::NotifyValue< T >::value_.
Referenced by yaze::app::core::NotifyValue< T >::operator=().
get()
template<typename T > const T & yaze::app::core::NotifyValue< T >::get () inline
Definition at line 133 of file common.h.
References yaze::app::core::NotifyValue< T >::modified_, and yaze::app::core::NotifyValue< T >::value_.
Referenced by yaze::app::editor::Tile16Editor::DrawTileEditControls(), yaze::app::core::NotifyValue< T >::operator T(), and yaze::app::editor::Tile16Editor::UpdateBlockset().
mutable_get()
template<typename T > T & yaze::app::core::NotifyValue< T >::mutable_get () inline
Definition at line 138 of file common.h.
References yaze::app::core::NotifyValue< T >::modified_, yaze::app::core::NotifyValue< T >::temp_value_, and yaze::app::core::NotifyValue< T >::value_.
Referenced by yaze::app::editor::Tile16Editor::DrawTileEditControls(), and yaze::app::editor::Tile16Editor::UpdateBlockset().
apply_changes()
template<typename T > void yaze::app::core::NotifyValue< T >::apply_changes () inline
Definition at line 144 of file common.h.
References yaze::app::core::NotifyValue< T >::modified_, yaze::app::core::NotifyValue< T >::temp_value_, and yaze::app::core::NotifyValue< T >::value_.
Referenced by yaze::app::editor::Tile16Editor::DrawTileEditControls(), and yaze::app::editor::Tile16Editor::UpdateBlockset().
operator=()
template<typename T > void yaze::app::core::NotifyValue< T >::operator= (const T & value) inline
Definition at line 151 of file common.h.
References yaze::app::core::NotifyValue< T >::set().
operator T()
template<typename T > yaze::app::core::NotifyValue< T >::operator T () inline
Definition at line 152 of file common.h.
References yaze::app::core::NotifyValue< T >::get().
modified()
template<typename T > bool yaze::app::core::NotifyValue< T >::modified () const inline
Definition at line 154 of file common.h.
References yaze::app::core::NotifyValue< T >::modified_.
Referenced by yaze::app::editor::Tile16Editor::DrawTileEditControls(), and yaze::app::editor::Tile16Editor::UpdateBlockset().
Member Data Documentation
value_
template<typename T > T yaze::app::core::NotifyValue< T >::value_ private
Definition at line 157 of file common.h.
Referenced by yaze::app::core::NotifyValue< T >::apply_changes(), yaze::app::core::NotifyValue< T >::get(), yaze::app::core::NotifyValue< T >::mutable_get(), and yaze::app::core::NotifyValue< T >::set().
modified_
template<typename T > bool yaze::app::core::NotifyValue< T >::modified_ private
Definition at line 158 of file common.h.
Referenced by yaze::app::core::NotifyValue< T >::apply_changes(), yaze::app::core::NotifyValue< T >::get(), yaze::app::core::NotifyValue< T >::modified(), yaze::app::core::NotifyValue< T >::mutable_get(), and yaze::app::core::NotifyValue< T >::set().
temp_value_
template<typename T > T yaze::app::core::NotifyValue< T >::temp_value_ private
Definition at line 159 of file common.h.
Referenced by yaze::app::core::NotifyValue< T >::apply_changes(), and yaze::app::core::NotifyValue< T >::mutable_get().
The documentation for this class was generated from the following file:
src/app/core/common.h