yaze: yaze::GraphicsSheetManager Class Reference
yaze::GraphicsSheetManager Class Reference
#include <rom.h>
Public Member Functions
GraphicsSheetManager ()=default
virtual ~GraphicsSheetManager ()=default
std::array< gfx::Bitmap, kNumGfxSheets > & gfx_sheets ()
auto gfx_sheet (int i)
auto mutable_gfx_sheet (int i)
auto mutable_gfx_sheets ()
Static Public Member Functions
static GraphicsSheetManager & GetInstance ()
Private Attributes
std::array< gfx::Bitmap, kNumGfxSheets > gfx_sheets_
Detailed Description
Definition at line 269 of file rom.h.
Constructor & Destructor Documentation
GraphicsSheetManager()
yaze::GraphicsSheetManager::GraphicsSheetManager () default
Referenced by GetInstance().
~GraphicsSheetManager()
virtual yaze::GraphicsSheetManager::~GraphicsSheetManager () virtual default
Member Function Documentation
GetInstance()
static GraphicsSheetManager & yaze::GraphicsSheetManager::GetInstance () inline static
Definition at line 271 of file rom.h.
References GraphicsSheetManager().
Referenced by yaze::editor::GfxGroupEditor::DrawBlocksetViewer(), yaze::editor::SpriteEditor::DrawCurrentSheets(), yaze::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::editor::GraphicsEditor::DrawGfxEditToolset(), yaze::editor::GfxGroupEditor::DrawRoomsetViewer(), yaze::editor::GfxGroupEditor::DrawSpritesetViewer(), yaze::editor::OverworldEditor::DrawTile8Selector(), yaze::editor::DungeonEditor::Initialize(), yaze::editor::EditorManager::SaveRom(), yaze::editor::EditorManager::Update(), yaze::editor::GraphicsEditor::Update(), yaze::editor::GraphicsEditor::UpdateGfxSheetList(), yaze::editor::GraphicsEditor::UpdateGfxTabView(), yaze::zelda3::DungeonObjectRenderer::UpdateObjectBitmap(), and yaze::editor::GraphicsEditor::UpdatePaletteColumn().
gfx_sheets()
std::array< gfx::Bitmap, kNumGfxSheets > & yaze::GraphicsSheetManager::gfx_sheets () inline
Definition at line 277 of file rom.h.
References gfx_sheets_.
Referenced by yaze::editor::GraphicsEditor::DrawGfxEditToolset(), and yaze::editor::DungeonEditor::Initialize().
gfx_sheet()
auto yaze::GraphicsSheetManager::gfx_sheet (int i) inline
Definition at line 278 of file rom.h.
References gfx_sheets_.
mutable_gfx_sheet()
auto yaze::GraphicsSheetManager::mutable_gfx_sheet (int i) inline
Definition at line 279 of file rom.h.
References gfx_sheets_.
mutable_gfx_sheets()
auto yaze::GraphicsSheetManager::mutable_gfx_sheets () inline
Definition at line 280 of file rom.h.
References gfx_sheets_.
Referenced by yaze::editor::GfxGroupEditor::DrawBlocksetViewer(), yaze::editor::GraphicsEditor::DrawGfxEditToolset(), yaze::editor::GfxGroupEditor::DrawRoomsetViewer(), yaze::editor::GfxGroupEditor::DrawSpritesetViewer(), yaze::editor::GraphicsEditor::UpdateGfxTabView(), and yaze::zelda3::DungeonObjectRenderer::UpdateObjectBitmap().
Member Data Documentation
gfx_sheets_
std::array<gfx::Bitmap, kNumGfxSheets> yaze::GraphicsSheetManager::gfx_sheets_ private
Definition at line 283 of file rom.h.
Referenced by gfx_sheet(), gfx_sheets(), mutable_gfx_sheet(), and mutable_gfx_sheets().
The documentation for this class was generated from the following file:
src/app/rom.h