yaze: yaze::core::PlatformBackend< Derived > Class Template Reference
yaze::core::PlatformBackend< Derived > Class Template Reference
#include <backend.h>
Public Member Functions
PlatformBackend ()=default
~PlatformBackend ()=default
void init ()
void init_audio ()
void shutdown_audio ()
void shutdown ()
void new_frame ()
void render ()
Detailed Description
template<typename Derived>
class yaze::core::PlatformBackend< Derived >
Definition at line 18 of file backend.h.
Constructor & Destructor Documentation
PlatformBackend()
template<typename Derived> yaze::core::PlatformBackend< Derived >::PlatformBackend () default
~PlatformBackend()
template<typename Derived> yaze::core::PlatformBackend< Derived >::~PlatformBackend () default
Member Function Documentation
init()
template<typename Derived> void yaze::core::PlatformBackend< Derived >::init () inline
Definition at line 23 of file backend.h.
References init().
Referenced by init().
init_audio()
template<typename Derived> void yaze::core::PlatformBackend< Derived >::init_audio () inline
Definition at line 24 of file backend.h.
References init_audio().
Referenced by init_audio().
shutdown_audio()
template<typename Derived> void yaze::core::PlatformBackend< Derived >::shutdown_audio () inline
Definition at line 25 of file backend.h.
References shutdown_audio().
Referenced by shutdown_audio().
shutdown()
template<typename Derived> void yaze::core::PlatformBackend< Derived >::shutdown () inline
Definition at line 26 of file backend.h.
References shutdown().
Referenced by shutdown().
new_frame()
template<typename Derived> void yaze::core::PlatformBackend< Derived >::new_frame () inline
Definition at line 27 of file backend.h.
References new_frame().
Referenced by new_frame().
render()
template<typename Derived> void yaze::core::PlatformBackend< Derived >::render () inline
Definition at line 28 of file backend.h.
References render().
Referenced by render().
The documentation for this class was generated from the following file:
src/app/core/platform/backend.h