yaze: yaze::core::ProjectManager Class Reference
yaze::core::ProjectManager Class Reference
Enhanced project management with templates and validation.
#include <project.h>
Classes
struct ProjectTemplate
Static Public Member Functions
static std::vector< ProjectTemplate > GetProjectTemplates ()
static absl::StatusOr< YazeProject > CreateFromTemplate (const std::string &template_name, const std::string &project_name, const std::string &base_path)
static std::vector< std::string > FindProjectsInDirectory (const std::string &directory)
static absl::Status BackupProject (const YazeProject &project)
static absl::Status RestoreProject (const std::string &backup_path)
static absl::Status ConvertProject (const std::string &source_path, const std::string &target_path, ProjectFormat target_format)
static absl::Status ValidateProjectStructure (const YazeProject &project)
static std::vector< std::string > GetRecommendedFixesForProject (const YazeProject &project)
Detailed Description
Enhanced project management with templates and validation.
Definition at line 157 of file project.h.
Member Function Documentation
GetProjectTemplates()
std::vector< ProjectManager::ProjectTemplate > yaze::core::ProjectManager::GetProjectTemplates () static
Definition at line 557 of file project.cc.
References ICON_MD_BUILD, ICON_MD_DOMAIN, ICON_MD_MAP, ICON_MD_PALETTE, and ICON_MD_VIDEOGAME_ASSET.
CreateFromTemplate()
absl::StatusOr< YazeProject > yaze::core::ProjectManager::CreateFromTemplate (const std::string & template_name, const std::string & project_name, const std::string & base_path) static
Definition at line 592 of file project.cc.
References yaze::core::YazeProject::Create(), yaze::core::ProjectMetadata::description, yaze::core::YazeProject::feature_flags, yaze::core::FeatureFlags::Flags::Overworld::kApplyZSCustomOverworldASM, yaze::core::FeatureFlags::Flags::Overworld::kLoadCustomOverworld, yaze::core::FeatureFlags::Flags::kSaveDungeonMaps, yaze::core::FeatureFlags::Flags::kSaveGraphicsSheet, yaze::core::YazeProject::metadata, yaze::core::FeatureFlags::Flags::overworld, yaze::core::YazeProject::Save(), yaze::core::WorkspaceSettings::show_grid, yaze::core::ProjectMetadata::tags, and yaze::core::YazeProject::workspace_settings.
FindProjectsInDirectory()
std::vector< std::string > yaze::core::ProjectManager::FindProjectsInDirectory (const std::string & directory) static
Definition at line 636 of file project.cc.
BackupProject()
absl::Status yaze::core::ProjectManager::BackupProject (const YazeProject & project) static
Definition at line 655 of file project.cc.
References yaze::core::YazeProject::filepath, and yaze::core::YazeProject::name.
RestoreProject()
static absl::Status yaze::core::ProjectManager::RestoreProject (const std::string & backup_path) static
ConvertProject()
static absl::Status yaze::core::ProjectManager::ConvertProject (const std::string & source_path, const std::string & target_path, ProjectFormat target_format) static
ValidateProjectStructure()
absl::Status yaze::core::ProjectManager::ValidateProjectStructure (const YazeProject & project) static
Definition at line 681 of file project.cc.
References yaze::core::YazeProject::Validate().
GetRecommendedFixesForProject()
std::vector< std::string > yaze::core::ProjectManager::GetRecommendedFixesForProject (const YazeProject & project) static
Definition at line 685 of file project.cc.
References yaze::core::YazeProject::code_folder, yaze::core::ProjectMetadata::description, yaze::core::YazeProject::GetMissingFiles(), yaze::core::YazeProject::git_repository, yaze::core::YazeProject::labels_filename, yaze::core::YazeProject::metadata, yaze::core::YazeProject::rom_filename, and yaze::core::YazeProject::track_changes.
The documentation for this class was generated from the following files:
src/app/core/project.h
src/app/core/project.cc