yaze: yaze::zelda3::Subtype1 Class Reference
yaze::zelda3::Subtype1 Class Reference
#include <room_object.h>
Public Member Functions
Subtype1 (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer, int tile_count)
void Draw (std::vector< uint8_t > &current_gfx16, std::vector< uint8_t > &tiles_bg1_buffer, std::vector< uint8_t > &tiles_bg2_buffer)
Public Member Functions inherited from yaze::zelda3::RoomObject
RoomObject (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer=0)
void AddTiles (int nbr, int pos)
void DrawTile (gfx::Tile16 t, int xx, int yy, std::vector< uint8_t > &current_gfx16, std::vector< uint8_t > &tiles_bg1_buffer, std::vector< uint8_t > &tiles_bg2_buffer, ushort tile_under=0xFFFF)
auto options () const
void set_options (ObjectOption options)
Public Member Functions inherited from yaze::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Public Attributes
bool all_bgs
int tile_count_
std::string name
Sorting sort
Additional Inherited Members
Public Types inherited from yaze::zelda3::RoomObject
enum LayerType { BG1 = 0 , BG2 = 1 , BG3 = 2 }
Static Public Attributes inherited from yaze::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Protected Attributes inherited from yaze::zelda3::RoomObject
bool all_bgs_ = false
bool lit_ = false
int16_t id_
uint8_t x_
uint8_t y_
uint8_t size_
uint8_t nx_
uint8_t ny_
uint8_t ox_
uint8_t oy_
uint8_t z_ = 0
uint8_t previous_size_ = 0
int width_
int height_
int offset_x_ = 0
int offset_y_ = 0
std::string name_
std::vector< uint8_t > preview_object_data_
std::vector< gfx::Tile16 > tiles_
LayerType layer_
ObjectOption options_ = ObjectOption::Nothing
Detailed Description
Definition at line 119 of file room_object.h.
Constructor & Destructor Documentation
Subtype1()
yaze::zelda3::Subtype1::Subtype1 (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer, int tile_count) inline
Definition at line 126 of file room_object.h.
References yaze::zelda3::RoomObject::AddTiles(), yaze::zelda3::Horizontal, yaze::zelda3::kRoomObjectSubtype1, yaze::zelda3::kRoomObjectTileAddress, yaze::SharedRom::rom(), sort, tile_count_, and yaze::zelda3::Wall.
Member Function Documentation
Draw()
void yaze::zelda3::Subtype1::Draw (std::vector< uint8_t > & current_gfx16, std::vector< uint8_t > & tiles_bg1_buffer, std::vector< uint8_t > & tiles_bg2_buffer) inline
Definition at line 138 of file room_object.h.
References yaze::zelda3::RoomObject::DrawTile(), yaze::zelda3::RoomObject::size_, tile_count_, and yaze::zelda3::RoomObject::tiles_.
Member Data Documentation
all_bgs
bool yaze::zelda3::Subtype1::all_bgs
Definition at line 121 of file room_object.h.
tile_count_
int yaze::zelda3::Subtype1::tile_count_
Definition at line 122 of file room_object.h.
Referenced by Draw(), and Subtype1().
name
std::string yaze::zelda3::Subtype1::name
Definition at line 123 of file room_object.h.
sort
Sorting yaze::zelda3::Subtype1::sort
Definition at line 124 of file room_object.h.
Referenced by Subtype1().
The documentation for this class was generated from the following file:
src/app/zelda3/dungeon/room_object.h