yaze: yaze::editor::DungeonRenderer Class Reference
yaze::editor::DungeonRenderer Class Reference
Handles rendering of dungeon objects, layouts, and backgrounds.
#include <dungeon_renderer.h>
Classes
struct ObjectRenderCache
Public Member Functions
DungeonRenderer (gui::Canvas *canvas, Rom *rom)
void RenderObjectInCanvas (const zelda3::RoomObject &object, const gfx::SnesPalette &palette)
void DisplayObjectInfo (const zelda3::RoomObject &object, int canvas_x, int canvas_y)
void RenderSprites (const zelda3::Room &room)
void RenderRoomBackgroundLayers (int room_id)
absl::Status RefreshGraphics (int room_id, uint64_t palette_id, const gfx::PaletteGroup &palette_group)
absl::Status LoadAndRenderRoomGraphics (int room_id, std::array< zelda3::Room, 0x128 > &rooms)
absl::Status ReloadAllRoomGraphics (std::array< zelda3::Room, 0x128 > &rooms)
void ClearObjectCache ()
size_t GetCacheSize () const
std::pair< int, int > RoomToCanvasCoordinates (int room_x, int room_y) const
std::pair< int, int > CanvasToRoomCoordinates (int canvas_x, int canvas_y) const
bool IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin=32) const
Private Attributes
gui::Canvas * canvas_
Rom * rom_
zelda3::ObjectRenderer object_renderer_
std::vector< ObjectRenderCache > object_render_cache_
uint64_t last_palette_hash_ = 0
Detailed Description
Handles rendering of dungeon objects, layouts, and backgrounds.
This component manages all rendering operations for the dungeon editor, including object caching, background layers, and layout visualization.
Definition at line 24 of file dungeon_renderer.h.
Constructor & Destructor Documentation
DungeonRenderer()
yaze::editor::DungeonRenderer::DungeonRenderer (gui::Canvas * canvas, Rom * rom) inline explicit
Definition at line 26 of file dungeon_renderer.h.
Member Function Documentation
RenderObjectInCanvas()
void yaze::editor::DungeonRenderer::RenderObjectInCanvas (const zelda3::RoomObject & object, const gfx::SnesPalette & palette)
Definition at line 12 of file dungeon_renderer.cc.
References yaze::zelda3::RoomObject::BG1, yaze::zelda3::RoomObject::BG2, yaze::zelda3::RoomObject::BG3, canvas_, yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawRect(), yaze::core::Renderer::Get(), yaze::Rom::is_loaded(), yaze::editor::DungeonRenderer::ObjectRenderCache::is_valid, IsWithinCanvasBounds(), yaze::editor::DungeonRenderer::ObjectRenderCache::object_id, object_render_cache_, object_renderer_, yaze::editor::DungeonRenderer::ObjectRenderCache::object_size, yaze::editor::DungeonRenderer::ObjectRenderCache::object_x, yaze::editor::DungeonRenderer::ObjectRenderCache::object_y, yaze::editor::DungeonRenderer::ObjectRenderCache::palette_hash, yaze::core::Renderer::RenderBitmap(), yaze::editor::DungeonRenderer::ObjectRenderCache::rendered_bitmap, yaze::zelda3::ObjectRenderer::RenderObject(), rom_, RoomToCanvasCoordinates(), yaze::zelda3::RoomObject::set_rom(), and yaze::gfx::SnesPalette::size().
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
DisplayObjectInfo()
void yaze::editor::DungeonRenderer::DisplayObjectInfo (const zelda3::RoomObject & object, int canvas_x, int canvas_y)
Definition at line 107 of file dungeon_renderer.cc.
References canvas_, and yaze::gui::Canvas::DrawText().
RenderSprites()
void yaze::editor::DungeonRenderer::RenderSprites (const zelda3::Room & room)
Definition at line 114 of file dungeon_renderer.cc.
References canvas_, yaze::gui::Canvas::DrawRect(), yaze::zelda3::Room::GetSprites(), IsWithinCanvasBounds(), and RoomToCanvasCoordinates().
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
RenderRoomBackgroundLayers()
void yaze::editor::DungeonRenderer::RenderRoomBackgroundLayers (int room_id)
Definition at line 136 of file dungeon_renderer.cc.
References yaze::gfx::Arena::bg1(), yaze::gfx::Arena::bg2(), canvas_, yaze::gui::Canvas::DrawBitmap(), yaze::gfx::Arena::Get(), yaze::gui::Canvas::height(), and yaze::gui::Canvas::width().
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
RefreshGraphics()
absl::Status yaze::editor::DungeonRenderer::RefreshGraphics (int room_id, uint64_t palette_id, const gfx::PaletteGroup & palette_group)
Definition at line 179 of file dungeon_renderer.cc.
References yaze::Rom::is_loaded(), and rom_.
LoadAndRenderRoomGraphics()
absl::Status yaze::editor::DungeonRenderer::LoadAndRenderRoomGraphics (int room_id, std::array< zelda3::Room, 0x128 > & rooms)
ReloadAllRoomGraphics()
absl::Status yaze::editor::DungeonRenderer::ReloadAllRoomGraphics (std::array< zelda3::Room, 0x128 > & rooms)
ClearObjectCache()
void yaze::editor::DungeonRenderer::ClearObjectCache () inline
Definition at line 46 of file dungeon_renderer.h.
References object_render_cache_.
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas(), yaze::editor::DungeonEditor::DrawRoomPropertiesDebugPopup(), and yaze::editor::DungeonEditor::Load().
GetCacheSize()
size_t yaze::editor::DungeonRenderer::GetCacheSize () const inline
Definition at line 47 of file dungeon_renderer.h.
References object_render_cache_.
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
RoomToCanvasCoordinates()
std::pair< int, int > yaze::editor::DungeonRenderer::RoomToCanvasCoordinates (int room_x, int room_y) const
Definition at line 189 of file dungeon_renderer.cc.
Referenced by RenderObjectInCanvas(), and RenderSprites().
CanvasToRoomCoordinates()
std::pair< int, int > yaze::editor::DungeonRenderer::CanvasToRoomCoordinates (int canvas_x, int canvas_y) const
Definition at line 193 of file dungeon_renderer.cc.
IsWithinCanvasBounds()
bool yaze::editor::DungeonRenderer::IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin = 32) const
Definition at line 197 of file dungeon_renderer.cc.
References canvas_, yaze::gui::Canvas::canvas_size(), and yaze::gui::Canvas::global_scale().
Referenced by RenderObjectInCanvas(), and RenderSprites().
Member Data Documentation
canvas_
gui::Canvas* yaze::editor::DungeonRenderer::canvas_ private
Definition at line 55 of file dungeon_renderer.h.
Referenced by DisplayObjectInfo(), IsWithinCanvasBounds(), RenderObjectInCanvas(), RenderRoomBackgroundLayers(), and RenderSprites().
rom_
Rom* yaze::editor::DungeonRenderer::rom_ private
Definition at line 56 of file dungeon_renderer.h.
Referenced by RefreshGraphics(), and RenderObjectInCanvas().
object_renderer_
zelda3::ObjectRenderer yaze::editor::DungeonRenderer::object_renderer_ private
Definition at line 57 of file dungeon_renderer.h.
Referenced by RenderObjectInCanvas().
object_render_cache_
std::vector<ObjectRenderCache> yaze::editor::DungeonRenderer::object_render_cache_ private
Definition at line 68 of file dungeon_renderer.h.
Referenced by ClearObjectCache(), GetCacheSize(), and RenderObjectInCanvas().
last_palette_hash_
uint64_t yaze::editor::DungeonRenderer::last_palette_hash_ = 0 private
Definition at line 69 of file dungeon_renderer.h.
The documentation for this class was generated from the following files:
src/app/editor/dungeon/dungeon_renderer.h
src/app/editor/dungeon/dungeon_renderer.cc