yaze: yaze::emu::AudioRam Class Reference
yaze::emu::AudioRam Class Reference abstract
AudioRam is an interface for the Audio RAM used by the SPC700.
#include <spc700.h>
Public Member Functions
virtual ~AudioRam ()=default
virtual void reset ()=0
virtual uint8_t read (uint16_t address) const =0
virtual uint8_t & mutable_read (uint16_t address)=0
virtual void write (uint16_t address, uint8_t value)=0
uint8_t operator[] (uint16_t address)
Detailed Description
AudioRam is an interface for the Audio RAM used by the SPC700.
Definition at line 15 of file spc700.h.
Constructor & Destructor Documentation
~AudioRam()
virtual yaze::emu::AudioRam::~AudioRam () virtual default
Member Function Documentation
reset()
virtual void yaze::emu::AudioRam::reset () pure virtual
Implemented in yaze::emu::AudioRamImpl.
Referenced by yaze::test::MockAudioRam::MOCK_METHOD(), and yaze::test::MockAudioRam::SetUp().
read()
virtual uint8_t yaze::emu::AudioRam::read (uint16_t address) const pure virtual
Implemented in yaze::emu::AudioRamImpl.
Referenced by yaze::test::MockAudioRam::MOCK_METHOD(), and yaze::test::MockAudioRam::SetUp().
mutable_read()
virtual uint8_t & yaze::emu::AudioRam::mutable_read (uint16_t address) pure virtual
Implemented in yaze::emu::AudioRamImpl.
Referenced by yaze::test::MockAudioRam::MOCK_METHOD(), operator[](), and yaze::test::MockAudioRam::SetUp().
write()
virtual void yaze::emu::AudioRam::write (uint16_t address, uint8_t value) pure virtual
Implemented in yaze::emu::AudioRamImpl.
Referenced by yaze::test::MockAudioRam::MOCK_METHOD(), and yaze::test::MockAudioRam::SetUp().
operator[]()
uint8_t yaze::emu::AudioRam::operator[] (uint16_t address) inline
Definition at line 22 of file spc700.h.
References mutable_read().
The documentation for this class was generated from the following file:
src/app/emu/audio/spc700.h