yaze: yaze::emu::memory::MemoryImpl Class Reference
yaze::emu::memory::MemoryImpl Class Reference
Implementation of the Memory interface for emulating memory in a SNES system.
#include <memory.h>
Public Member Functions
void Initialize (const std::vector< uint8_t > &romData, bool verbose=false)
uint16_t GetHeaderOffset ()
uint8_t cart_read (uint8_t bank, uint16_t adr)
void cart_write (uint8_t bank, uint16_t adr, uint8_t val)
uint8_t cart_readLorom (uint8_t bank, uint16_t adr)
void cart_writeLorom (uint8_t bank, uint16_t adr, uint8_t val)
uint8_t cart_readHirom (uint8_t bank, uint16_t adr)
uint8_t cart_readExHirom (uint8_t bank, uint16_t adr)
void cart_writeHirom (uint8_t bank, uint16_t adr, uint8_t val)
uint8_t ReadByte (uint32_t address) const override
uint16_t ReadWord (uint32_t address) const override
uint32_t ReadWordLong (uint32_t address) const override
std::vector< uint8_t > ReadByteVector (uint32_t address, uint16_t length) const override
void WriteByte (uint32_t address, uint8_t value) override
void WriteWord (uint32_t address, uint16_t value) override
void WriteLong (uint32_t address, uint32_t value) override
void PushByte (uint8_t value) override
uint8_t PopByte () override
void PushWord (uint16_t value) override
uint16_t PopWord () override
void PushLong (uint32_t value) override
uint32_t PopLong () override
uint16_t SP () const override
auto mutable_sp () -> uint16_t &
void SetSP (uint16_t value) override
void ClearMemory () override
uint8_t at (int i) const override
uint8_t operator[] (int i) const override
auto size () const
auto begin () const
auto end () const
auto data () const
void set_open_bus (uint8_t value) override
auto open_bus () const -> uint8_t override
auto hdma_init_requested () const -> bool override
auto hdma_run_requested () const -> bool override
void init_hdma_request () override
void run_hdma_request () override
void set_hdma_run_requested (bool value) override
void set_hdma_init_requested (bool value) override
void set_pal_timing (bool value) override
void set_h_pos (uint16_t value) override
void set_v_pos (uint16_t value) override
auto h_pos () const -> uint16_t override
auto v_pos () const -> uint16_t override
auto pal_timing () const -> bool override
auto dma_state () -> uint8_t &
void set_dma_state (uint8_t value)
auto dma_channels () -> DmaChannel *
Public Member Functions inherited from yaze::emu::memory::Memory
virtual ~Memory ()=default
Public Attributes
std::vector< uint8_t > rom_
std::vector< uint8_t > ram_
Private Member Functions
uint32_t GetMappedAddress (uint32_t address) const
Private Attributes
bool verbose_ = false
bool hdma_run_requested_ = false
bool hdma_init_requested_ = false
bool pal_timing_ = false
uint32_t rom_size_
uint32_t sram_size_
uint16_t h_pos_ = 0
uint16_t v_pos_ = 0
uint8_t dma_state_ = 0
uint8_t open_bus_ = 0
uint16_t SP_ = 0
uint8_t type_ = 1
DmaChannel channel [8]
std::vector< uint8_t > memory_
Detailed Description
Implementation of the Memory interface for emulating memory in a SNES system.
Definition at line 101 of file memory.h.
Member Function Documentation
Initialize()
void yaze::emu::memory::MemoryImpl::Initialize (const std::vector< uint8_t > & romData, bool verbose = false)
Definition at line 14 of file memory.cc.
References memory_, ram_, rom_, rom_size_, sram_size_, type_, and verbose_.
Referenced by yaze::emu::SNES::Init(), and yaze::zelda3::dungeon::DungeonObjectRenderer::LoadObject().
GetHeaderOffset()
uint16_t yaze::emu::memory::MemoryImpl::GetHeaderOffset () inline
Definition at line 105 of file memory.h.
cart_read()
uint8_t yaze::emu::memory::MemoryImpl::cart_read (uint8_t bank, uint16_t adr)
Definition at line 53 of file memory.cc.
References cart_readExHirom(), cart_readHirom(), cart_readLorom(), open_bus_, and type_.
Referenced by yaze::emu::SNES::Rread().
cart_write()
void yaze::emu::memory::MemoryImpl::cart_write (uint8_t bank, uint16_t adr, uint8_t val)
Definition at line 67 of file memory.cc.
References cart_writeHirom(), cart_writeLorom(), and type_.
Referenced by yaze::emu::SNES::Write().
cart_readLorom()
uint8_t yaze::emu::memory::MemoryImpl::cart_readLorom (uint8_t bank, uint16_t adr)
Definition at line 83 of file memory.cc.
References open_bus_, ram_, rom_, rom_size_, and sram_size_.
Referenced by cart_read().
cart_writeLorom()
void yaze::emu::memory::MemoryImpl::cart_writeLorom (uint8_t bank, uint16_t adr, uint8_t val)
Definition at line 97 of file memory.cc.
References ram_, and sram_size_.
Referenced by cart_write().
cart_readHirom()
uint8_t yaze::emu::memory::MemoryImpl::cart_readHirom (uint8_t bank, uint16_t adr)
Definition at line 105 of file memory.cc.
References open_bus_, ram_, rom_, rom_size_, and sram_size_.
Referenced by cart_read().
cart_readExHirom()
uint8_t yaze::emu::memory::MemoryImpl::cart_readExHirom (uint8_t bank, uint16_t adr)
Definition at line 118 of file memory.cc.
References open_bus_, ram_, rom_, rom_size_, and sram_size_.
Referenced by cart_read().
cart_writeHirom()
void yaze::emu::memory::MemoryImpl::cart_writeHirom (uint8_t bank, uint16_t adr, uint8_t val)
Definition at line 133 of file memory.cc.
References ram_, and sram_size_.
Referenced by cart_write().
ReadByte()
uint8_t yaze::emu::memory::MemoryImpl::ReadByte (uint32_t address) const inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 137 of file memory.h.
ReadWord()
uint16_t yaze::emu::memory::MemoryImpl::ReadWord (uint32_t address) const inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 141 of file memory.h.
Referenced by yaze::zelda3::dungeon::DungeonObjectRenderer::UpdateObjectBitmap().
ReadWordLong()
uint32_t yaze::emu::memory::MemoryImpl::ReadWordLong (uint32_t address) const inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 146 of file memory.h.
ReadByteVector()
std::vector< uint8_t > yaze::emu::memory::MemoryImpl::ReadByteVector (uint32_t address, uint16_t length) const inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 152 of file memory.h.
WriteByte()
void yaze::emu::memory::MemoryImpl::WriteByte (uint32_t address, uint8_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 159 of file memory.h.
WriteWord()
void yaze::emu::memory::MemoryImpl::WriteWord (uint32_t address, uint16_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 163 of file memory.h.
WriteLong()
void yaze::emu::memory::MemoryImpl::WriteLong (uint32_t address, uint32_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 168 of file memory.h.
PushByte()
void yaze::emu::memory::MemoryImpl::PushByte (uint8_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 176 of file memory.h.
PopByte()
uint8_t yaze::emu::memory::MemoryImpl::PopByte () inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 186 of file memory.h.
PushWord()
void yaze::emu::memory::MemoryImpl::PushWord (uint16_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 196 of file memory.h.
References yaze::emu::memory::Memory::PushByte().
PopWord()
uint16_t yaze::emu::memory::MemoryImpl::PopWord () inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 201 of file memory.h.
References yaze::emu::memory::Memory::PopByte().
PushLong()
void yaze::emu::memory::MemoryImpl::PushLong (uint32_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 207 of file memory.h.
References yaze::emu::memory::Memory::PushByte().
PopLong()
uint32_t yaze::emu::memory::MemoryImpl::PopLong () inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 213 of file memory.h.
References yaze::emu::memory::Memory::PopByte().
SP()
uint16_t yaze::emu::memory::MemoryImpl::SP () const inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 222 of file memory.h.
mutable_sp()
auto yaze::emu::memory::MemoryImpl::mutable_sp () -> uint16_t& inline
Definition at line 223 of file memory.h.
SetSP()
void yaze::emu::memory::MemoryImpl::SetSP (uint16_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 224 of file memory.h.
ClearMemory()
void yaze::emu::memory::MemoryImpl::ClearMemory () inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 225 of file memory.h.
at()
uint8_t yaze::emu::memory::MemoryImpl::at (int i) const inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 227 of file memory.h.
operator[]()
uint8_t yaze::emu::memory::MemoryImpl::operator[] (int i) const inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 228 of file memory.h.
size()
auto yaze::emu::memory::MemoryImpl::size () const inline
Definition at line 236 of file memory.h.
begin()
auto yaze::emu::memory::MemoryImpl::begin () const inline
Definition at line 237 of file memory.h.
end()
auto yaze::emu::memory::MemoryImpl::end () const inline
Definition at line 238 of file memory.h.
data()
auto yaze::emu::memory::MemoryImpl::data () const inline
Definition at line 239 of file memory.h.
set_open_bus()
void yaze::emu::memory::MemoryImpl::set_open_bus (uint8_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 240 of file memory.h.
Referenced by yaze::emu::SNES::Read(), yaze::emu::SNES::Reset(), and yaze::emu::SNES::Write().
open_bus()
auto yaze::emu::memory::MemoryImpl::open_bus () const -> uint8_t inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 241 of file memory.h.
Referenced by yaze::emu::memory::dma::Read(), yaze::emu::SNES::ReadBBus(), yaze::emu::SNES::ReadReg(), yaze::emu::SNES::Rread(), and yaze::emu::memory::dma::TransferByte().
hdma_init_requested()
auto yaze::emu::memory::MemoryImpl::hdma_init_requested () const -> bool inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 242 of file memory.h.
Referenced by yaze::emu::memory::dma::HandleDma(), and yaze::emu::memory::dma::WaitCycle().
hdma_run_requested()
auto yaze::emu::memory::MemoryImpl::hdma_run_requested () const -> bool inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 245 of file memory.h.
Referenced by yaze::emu::memory::dma::HandleDma(), and yaze::emu::memory::dma::WaitCycle().
init_hdma_request()
void yaze::emu::memory::MemoryImpl::init_hdma_request () inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 248 of file memory.h.
Referenced by yaze::emu::SNES::RunCycle().
run_hdma_request()
void yaze::emu::memory::MemoryImpl::run_hdma_request () inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 249 of file memory.h.
Referenced by yaze::emu::SNES::RunCycle().
set_hdma_run_requested()
void yaze::emu::memory::MemoryImpl::set_hdma_run_requested (bool value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 250 of file memory.h.
Referenced by yaze::emu::memory::dma::DoHdma(), and yaze::emu::memory::dma::Reset().
set_hdma_init_requested()
void yaze::emu::memory::MemoryImpl::set_hdma_init_requested (bool value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 253 of file memory.h.
Referenced by yaze::emu::memory::dma::InitHdma(), and yaze::emu::memory::dma::Reset().
set_pal_timing()
void yaze::emu::memory::MemoryImpl::set_pal_timing (bool value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 256 of file memory.h.
set_h_pos()
void yaze::emu::memory::MemoryImpl::set_h_pos (uint16_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 257 of file memory.h.
Referenced by yaze::emu::SNES::Reset(), and yaze::emu::SNES::RunCycle().
set_v_pos()
void yaze::emu::memory::MemoryImpl::set_v_pos (uint16_t value) inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 258 of file memory.h.
Referenced by yaze::emu::SNES::Reset(), and yaze::emu::SNES::RunCycle().
h_pos()
auto yaze::emu::memory::MemoryImpl::h_pos () const -> uint16_t inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 259 of file memory.h.
Referenced by yaze::emu::SNES::ReadReg(), yaze::emu::SNES::RunCycle(), and yaze::emu::SNES::RunCycles().
v_pos()
auto yaze::emu::memory::MemoryImpl::v_pos () const -> uint16_t inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 260 of file memory.h.
Referenced by yaze::emu::SNES::RunCycle().
pal_timing()
auto yaze::emu::memory::MemoryImpl::pal_timing () const -> bool inline override virtual
Implements yaze::emu::memory::Memory.
Definition at line 261 of file memory.h.
Referenced by yaze::emu::SNES::RunCycle(), yaze::emu::audio::Apu::RunCycles(), and yaze::emu::SNES::SetSamples().
dma_state()
auto yaze::emu::memory::MemoryImpl::dma_state () -> uint8_t& inline
Definition at line 263 of file memory.h.
Referenced by yaze::emu::memory::dma::HandleDma().
set_dma_state()
void yaze::emu::memory::MemoryImpl::set_dma_state (uint8_t value) inline
Definition at line 264 of file memory.h.
Referenced by yaze::emu::memory::dma::HandleDma(), yaze::emu::memory::dma::Reset(), and yaze::emu::memory::dma::StartDma().
dma_channels()
auto yaze::emu::memory::MemoryImpl::dma_channels () -> DmaChannel* inline
Definition at line 265 of file memory.h.
Referenced by yaze::emu::memory::dma::DoDma(), yaze::emu::memory::dma::DoHdma(), yaze::emu::memory::dma::InitHdma(), yaze::emu::memory::dma::Read(), yaze::emu::memory::dma::Reset(), yaze::emu::memory::dma::StartDma(), and yaze::emu::memory::dma::Write().
GetMappedAddress()
uint32_t yaze::emu::memory::MemoryImpl::GetMappedAddress (uint32_t address) const private
Definition at line 141 of file memory.cc.
Member Data Documentation
rom_
std::vector<uint8_t> yaze::emu::memory::MemoryImpl::rom_
Definition at line 268 of file memory.h.
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), and Initialize().
ram_
std::vector<uint8_t> yaze::emu::memory::MemoryImpl::ram_
Definition at line 269 of file memory.h.
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), cart_writeHirom(), cart_writeLorom(), and Initialize().
verbose_
bool yaze::emu::memory::MemoryImpl::verbose_ = false private
Definition at line 274 of file memory.h.
Referenced by Initialize().
hdma_run_requested_
bool yaze::emu::memory::MemoryImpl::hdma_run_requested_ = false private
Definition at line 277 of file memory.h.
hdma_init_requested_
bool yaze::emu::memory::MemoryImpl::hdma_init_requested_ = false private
Definition at line 278 of file memory.h.
pal_timing_
bool yaze::emu::memory::MemoryImpl::pal_timing_ = false private
Definition at line 280 of file memory.h.
rom_size_
uint32_t yaze::emu::memory::MemoryImpl::rom_size_ private
Definition at line 283 of file memory.h.
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), and Initialize().
sram_size_
uint32_t yaze::emu::memory::MemoryImpl::sram_size_ private
Definition at line 284 of file memory.h.
Referenced by cart_readExHirom(), cart_readHirom(), cart_readLorom(), cart_writeHirom(), cart_writeLorom(), and Initialize().
h_pos_
uint16_t yaze::emu::memory::MemoryImpl::h_pos_ = 0 private
Definition at line 287 of file memory.h.
v_pos_
uint16_t yaze::emu::memory::MemoryImpl::v_pos_ = 0 private
Definition at line 288 of file memory.h.
dma_state_
uint8_t yaze::emu::memory::MemoryImpl::dma_state_ = 0 private
Definition at line 291 of file memory.h.
open_bus_
uint8_t yaze::emu::memory::MemoryImpl::open_bus_ = 0 private
Definition at line 294 of file memory.h.
Referenced by cart_read(), cart_readExHirom(), cart_readHirom(), and cart_readLorom().
SP_
uint16_t yaze::emu::memory::MemoryImpl::SP_ = 0 private
Definition at line 297 of file memory.h.
type_
uint8_t yaze::emu::memory::MemoryImpl::type_ = 1 private
Definition at line 300 of file memory.h.
Referenced by cart_read(), cart_write(), and Initialize().
channel
DmaChannel yaze::emu::memory::MemoryImpl::channel[8] private
Definition at line 303 of file memory.h.
memory_
std::vector<uint8_t> yaze::emu::memory::MemoryImpl::memory_ private
Definition at line 306 of file memory.h.
Referenced by Initialize().
The documentation for this class was generated from the following files:
src/app/emu/memory/memory.h
src/app/emu/memory/memory.cc