yaze: Editor Class Reference
Editor Class Reference abstract
#include <editor.h>
Public Member Functions
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Cut ()=0
virtual absl::Status Copy ()=0
virtual absl::Status Paste ()=0
virtual absl::Status Undo ()=0
virtual absl::Status Redo ()=0
virtual absl::Status Update ()=0
Constructor & Destructor Documentation
Editor()
Editor::Editor () default
~Editor()
virtual Editor::~Editor () virtual default
Member Function Documentation
Copy()
virtual absl::Status Editor::Copy () pure virtual
Implemented in yaze::app::editor::OverworldEditor, and yaze::app::editor::DungeonEditor.
Referenced by yaze::app::editor::MasterEditor::DrawEditMenu().
Cut()
virtual absl::Status Editor::Cut () pure virtual
Implemented in yaze::app::editor::OverworldEditor, and yaze::app::editor::DungeonEditor.
Referenced by yaze::app::editor::MasterEditor::DrawEditMenu().
Paste()
virtual absl::Status Editor::Paste () pure virtual
Implemented in yaze::app::editor::OverworldEditor, and yaze::app::editor::DungeonEditor.
Referenced by yaze::app::editor::MasterEditor::DrawEditMenu().
Redo()
virtual absl::Status Editor::Redo () pure virtual
Implemented in yaze::app::editor::OverworldEditor, and yaze::app::editor::DungeonEditor.
Referenced by yaze::app::editor::MasterEditor::DrawEditMenu().
Undo()
virtual absl::Status Editor::Undo () pure virtual
Implemented in yaze::app::editor::OverworldEditor, and yaze::app::editor::DungeonEditor.
Referenced by yaze::app::editor::MasterEditor::DrawEditMenu().
Update()
virtual absl::Status Editor::Update () pure virtual
Implemented in yaze::app::editor::OverworldEditor, and yaze::app::editor::DungeonEditor.
The documentation for this class was generated from the following file:
src/app/core/editor.h