yaze: yaze::app::editor::RecentFilesManager Class Reference
yaze::app::editor::RecentFilesManager Class Reference
#include <recent_files.h>
Public Member Functions
RecentFilesManager (const std::string &filename)
void AddFile (const std::string &filePath)
void Save ()
void Load ()
const std::vector< std::string > & GetRecentFiles () const
Private Attributes
std::string filename_
std::vector< std::string > recentFiles_
Detailed Description
Definition at line 13 of file recent_files.h.
Constructor & Destructor Documentation
RecentFilesManager()
yaze::app::editor::RecentFilesManager::RecentFilesManager (const std::string & filename) inline
Definition at line 15 of file recent_files.h.
Member Function Documentation
AddFile()
void yaze::app::editor::RecentFilesManager::AddFile (const std::string & filePath) inline
Definition at line 17 of file recent_files.h.
References recentFiles_.
Referenced by yaze::app::editor::EditorManager::LoadRom(), and yaze::app::editor::EditorManager::OpenProject().
Save()
void yaze::app::editor::RecentFilesManager::Save () inline
Definition at line 25 of file recent_files.h.
References filename_, and recentFiles_.
Referenced by yaze::app::editor::EditorManager::LoadRom(), and yaze::app::editor::EditorManager::OpenProject().
Load()
void yaze::app::editor::RecentFilesManager::Load () inline
Definition at line 36 of file recent_files.h.
References filename_, and recentFiles_.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), yaze::app::editor::EditorManager::LoadRom(), yaze::app::editor::EditorManager::ManageKeyboardShortcuts(), and yaze::app::editor::EditorManager::OpenProject().
GetRecentFiles()
const std::vector< std::string > & yaze::app::editor::RecentFilesManager::GetRecentFiles () const inline
Definition at line 51 of file recent_files.h.
References recentFiles_.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
Member Data Documentation
filename_
std::string yaze::app::editor::RecentFilesManager::filename_ private
Definition at line 56 of file recent_files.h.
Referenced by Load(), and Save().
recentFiles_
std::vector<std::string> yaze::app::editor::RecentFilesManager::recentFiles_ private
Definition at line 57 of file recent_files.h.
Referenced by AddFile(), GetRecentFiles(), Load(), and Save().
The documentation for this class was generated from the following file:
src/app/editor/utils/recent_files.h