yaze: yaze::app::gfx::Bitmap Class Reference
yaze::app::gfx::Bitmap Class Reference
Represents a bitmap image.
#include <bitmap.h>
Classes
struct SDL_Surface_Deleter
struct SDL_Texture_Deleter
Public Member Functions
Bitmap ()=default
Bitmap (int width, int height, int depth, int data_size)
Bitmap (int width, int height, int depth, const Bytes &data)
Bitmap (int width, int height, int depth, const Bytes &data, const SnesPalette &palette)
void Create (int width, int height, int depth, const Bytes &data)
Creates a bitmap object with the provided graphical data.
void Create (int width, int height, int depth, int format, const Bytes &data)
void Reformat (int format)
void CreateTexture (std::shared_ptr< SDL_Renderer > renderer)
Creates the underlying SDL_Texture to be displayed.
void UpdateTexture (std::shared_ptr< SDL_Renderer > renderer)
Updates the underlying SDL_Texture when it already exists.
void CreateTexture (SDL_Renderer *renderer)
void UpdateTexture (SDL_Renderer *renderer, bool use_sdl_update=false)
void SaveSurfaceToFile (std::string_view filename)
void SetSurface (SDL_Surface *surface)
std::vector< uint8_t > GetPngData ()
void LoadFromPngData (const std::vector< uint8_t > &png_data, int width, int height)
absl::Status ApplyPalette (const SnesPalette &palette)
Copy color data from the SnesPalette into the SDL_Palette.
absl::Status ApplyPaletteWithTransparent (const SnesPalette &palette, int index, int length=7)
void ApplyPalette (const std::vector< SDL_Color > &palette)
absl::Status ApplyPaletteFromPaletteGroup (const SnesPalette &palette, int palette_id)
void Get8x8Tile (int tile_index, int x, int y, std::vector< uint8_t > &tile_data, int &tile_data_offset)
void Get16x16Tile (int tile_index, int x, int y, std::vector< uint8_t > &tile_data, int &tile_data_offset)
void Get16x16Tile (int tile_x, int tile_y, std::vector< uint8_t > &tile_data, int &tile_data_offset)
void WriteToPixel (int position, uchar value)
void WriteWordToPixel (int position, uint16_t value)
void WriteColor (int position, const ImVec4 &color)
void Cleanup ()
auto sdl_palette ()
auto palette () const
auto mutable_palette ()
auto palette_size () const
int width () const
int height () const
auto depth () const
auto size () const
auto data () const
auto & mutable_data ()
auto mutable_pixel_data ()
auto surface () const
auto mutable_surface ()
auto converted_surface () const
auto mutable_converted_surface ()
void set_data (const Bytes &data)
auto vector () const
auto at (int i) const
auto texture () const
auto modified () const
void set_modified (bool modified)
auto is_active () const
auto set_active (bool active)
Private Attributes
int width_ = 0
int height_ = 0
int depth_ = 0
int data_size_ = 0
bool freed_ = false
bool active_ = false
bool modified_ = false
void * texture_pixels = nullptr
uchar * pixel_data_
Bytes data_
std::vector< uint8_t > png_data_
gfx::SnesPalette palette_
std::shared_ptr< SDL_Texture > texture_ = nullptr
std::shared_ptr< SDL_Surface > surface_ = nullptr
std::shared_ptr< SDL_Surface > converted_surface_ = nullptr
Detailed Description
Represents a bitmap image.
The Bitmap class provides functionality to create, manipulate, and display bitmap images. It supports various operations such as creating a bitmap object, creating and updating textures, applying palettes, and accessing pixel data.
Definition at line 67 of file bitmap.h.
Constructor & Destructor Documentation
Bitmap() [1/4]
yaze::app::gfx::Bitmap::Bitmap () default
Bitmap() [2/4]
yaze::app::gfx::Bitmap::Bitmap (int width, int height, int depth, int data_size)
Definition at line 200 of file bitmap.cc.
References Create(), depth(), height(), and width().
Bitmap() [3/4]
yaze::app::gfx::Bitmap::Bitmap (int width, int height, int depth, const Bytes & data) inline
Definition at line 72 of file bitmap.h.
References Create(), data(), depth(), height(), and width().
Bitmap() [4/4]
yaze::app::gfx::Bitmap::Bitmap (int width, int height, int depth, const Bytes & data, const SnesPalette & palette) inline
Definition at line 76 of file bitmap.h.
References ApplyPalette(), Create(), data(), depth(), height(), palette(), and width().
Member Function Documentation
Create() [1/2]
void yaze::app::gfx::Bitmap::Create (int width, int height, int depth, const Bytes & data)
Creates a bitmap object with the provided graphical data.
Definition at line 204 of file bitmap.cc.
References active_, data(), data_, data_size_, depth(), depth_, height(), height_, pixel_data_, surface_, width(), and width_.
Referenced by Bitmap(), Bitmap(), Bitmap(), yaze::app::zelda3::screen::Inventory::BuildTileset(), yaze::app::zelda3::screen::Inventory::Create(), yaze::app::zelda3::screen::TitleScreen::Create(), yaze::app::Rom::CreateAndRenderBitmap(), yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DrawCgxImport(), yaze::app::editor::GraphicsEditor::DrawScrImport(), and yaze::app::zelda3::dungeon::DungeonObjectRenderer::UpdateObjectBitmap().
Create() [2/2]
void yaze::app::gfx::Bitmap::Create (int width, int height, int depth, int format, const Bytes & data)
Definition at line 221 of file bitmap.cc.
References active_, data(), data_, data_size_, depth(), depth_, height(), height_, pixel_data_, surface_, width(), and width_.
Reformat()
void yaze::app::gfx::Bitmap::Reformat (int format)
Definition at line 238 of file bitmap.cc.
References active_, ApplyPalette(), depth_, height_, palette_, pixel_data_, surface_, and width_.
Referenced by yaze::app::gui::Canvas::DrawContextMenu().
CreateTexture() [1/2]
void yaze::app::gfx::Bitmap::CreateTexture (std::shared_ptr< SDL_Renderer > renderer)
Creates the underlying SDL_Texture to be displayed.
Converts the surface from a RGB to ARGB format. Uses SDL_TEXTUREACCESS_STREAMING to allow for live updates.
Definition at line 304 of file bitmap.cc.
References surface_, and texture_.
Referenced by yaze::app::Rom::RenderBitmap().
UpdateTexture() [1/2]
void yaze::app::gfx::Bitmap::UpdateTexture (std::shared_ptr< SDL_Renderer > renderer)
Updates the underlying SDL_Texture when it already exists.
Definition at line 310 of file bitmap.cc.
References surface_, and texture_.
Referenced by yaze::app::Rom::UpdateBitmap().
CreateTexture() [2/2]
void yaze::app::gfx::Bitmap::CreateTexture (SDL_Renderer * renderer)
Definition at line 250 of file bitmap.cc.
References converted_surface(), converted_surface_, height_, surface_, texture_, texture_pixels, and width_.
UpdateTexture() [2/2]
void yaze::app::gfx::Bitmap::UpdateTexture (SDL_Renderer * renderer, bool use_sdl_update = false)
Definition at line 282 of file bitmap.cc.
References converted_surface(), converted_surface_, surface_, texture_, and texture_pixels.
SaveSurfaceToFile()
void yaze::app::gfx::Bitmap::SaveSurfaceToFile (std::string_view filename)
Definition at line 316 of file bitmap.cc.
References surface_.
SetSurface()
void yaze::app::gfx::Bitmap::SetSurface (SDL_Surface * surface)
Definition at line 320 of file bitmap.cc.
References surface(), and surface_.
GetPngData()
std::vector< uint8_t > yaze::app::gfx::Bitmap::GetPngData ()
Definition at line 325 of file bitmap.cc.
References yaze::app::gfx::ConvertSurfaceToPNG(), png_data_, and surface_.
LoadFromPngData()
void yaze::app::gfx::Bitmap::LoadFromPngData (const std::vector< uint8_t > & png_data, int width, int height)
Definition at line 330 of file bitmap.cc.
References yaze::app::gfx::ConvertPngToSurface(), height(), height_, surface(), surface_, width(), and width_.
ApplyPalette() [1/2]
absl::Status yaze::app::gfx::Bitmap::ApplyPalette (const SnesPalette & palette)
Copy color data from the SnesPalette into the SDL_Palette.
Definition at line 340 of file bitmap.cc.
References ASSIGN_OR_RETURN, palette(), palette_, yaze::app::gfx::SnesColor::rgb(), and surface_.
Referenced by Bitmap(), yaze::app::zelda3::screen::Inventory::BuildTileset(), yaze::app::zelda3::screen::Inventory::Create(), yaze::app::Rom::CreateAndRenderBitmap(), yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DrawCgxImport(), yaze::app::editor::GraphicsEditor::DrawScrImport(), Reformat(), yaze::app::editor::OverworldEditor::RefreshTile16Blockset(), yaze::app::editor::Tile16Editor::SetCurrentTile(), and yaze::app::editor::Tile16Editor::UpdateBlockset().
ApplyPaletteWithTransparent()
absl::Status yaze::app::gfx::Bitmap::ApplyPaletteWithTransparent (const SnesPalette & palette, int index, int length = 7)
Definition at line 394 of file bitmap.cc.
References ASSIGN_OR_RETURN, palette(), palette_, yaze::app::gfx::SnesPalette::sub_palette(), and surface_.
Referenced by yaze::app::gui::Canvas::DrawContextMenu(), and yaze::app::editor::Tile16Editor::DrawTileEditControls().
ApplyPalette() [2/2]
void yaze::app::gfx::Bitmap::ApplyPalette (const std::vector< SDL_Color > & palette)
Definition at line 418 of file bitmap.cc.
References palette(), and surface_.
ApplyPaletteFromPaletteGroup()
absl::Status yaze::app::gfx::Bitmap::ApplyPaletteFromPaletteGroup (const SnesPalette & palette, int palette_id)
Definition at line 371 of file bitmap.cc.
References ASSIGN_OR_RETURN, yaze::app::gfx::SnesPalette::GetColor(), palette(), palette_, yaze::app::gfx::SnesPalette::size(), yaze::app::gfx::SnesPalette::sub_palette(), and surface_.
Get8x8Tile()
void yaze::app::gfx::Bitmap::Get8x8Tile (int tile_index, int x, int y, std::vector< uint8_t > & tile_data, int & tile_data_offset)
Definition at line 429 of file bitmap.cc.
References data_, height_, and width_.
Get16x16Tile() [1/2]
void yaze::app::gfx::Bitmap::Get16x16Tile (int tile_index, int x, int y, std::vector< uint8_t > & tile_data, int & tile_data_offset)
Definition at line 446 of file bitmap.cc.
References data_, height_, and width_.
Get16x16Tile() [2/2]
void yaze::app::gfx::Bitmap::Get16x16Tile (int tile_x, int tile_y, std::vector< uint8_t > & tile_data, int & tile_data_offset)
Definition at line 462 of file bitmap.cc.
References data_, and width_.
WriteToPixel()
void yaze::app::gfx::Bitmap::WriteToPixel (int position, uchar value) inline
Definition at line 136 of file bitmap.h.
References data_, modified_, and pixel_data_.
Referenced by yaze::app::editor::Tile16Editor::DrawToCurrentTile16(), and yaze::app::editor::OverworldEditor::RenderUpdatedMapBitmap().
WriteWordToPixel()
void yaze::app::gfx::Bitmap::WriteWordToPixel (int position, uint16_t value) inline
Definition at line 144 of file bitmap.h.
References data_, modified_, and pixel_data_.
WriteColor()
void yaze::app::gfx::Bitmap::WriteColor (int position, const ImVec4 & color)
Definition at line 479 of file bitmap.cc.
References modified_, pixel_data_, and surface_.
Referenced by yaze::app::gui::Canvas::DrawTileOnBitmap().
Cleanup()
void yaze::app::gfx::Bitmap::Cleanup () inline
Definition at line 155 of file bitmap.h.
References active_, yaze::app::gfx::SnesPalette::Clear(), data_size_, depth_, height_, palette_, and width_.
sdl_palette()
auto yaze::app::gfx::Bitmap::sdl_palette () inline
Definition at line 164 of file bitmap.h.
References surface_.
palette()
auto yaze::app::gfx::Bitmap::palette () const inline
Definition at line 170 of file bitmap.h.
References palette_.
Referenced by ApplyPalette(), ApplyPalette(), ApplyPaletteFromPaletteGroup(), ApplyPaletteWithTransparent(), Bitmap(), and yaze::app::editor::MessageEditor::Initialize().
mutable_palette()
auto yaze::app::gfx::Bitmap::mutable_palette () inline
Definition at line 171 of file bitmap.h.
References palette_.
Referenced by yaze::app::editor::MessageEditor::Initialize().
palette_size()
auto yaze::app::gfx::Bitmap::palette_size () const inline
Definition at line 172 of file bitmap.h.
References palette_, and yaze::app::gfx::SnesPalette::size().
width()
int yaze::app::gfx::Bitmap::width () const inline
Definition at line 174 of file bitmap.h.
References width_.
Referenced by Bitmap(), Bitmap(), Bitmap(), Create(), Create(), yaze::app::gui::BitmapViewer::Display(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawTileOnBitmap(), yaze::app::gfx::Tilesheet::GetTile16(), LoadFromPngData(), and yaze::app::editor::Tile16Editor::LoadTile8().
height()
int yaze::app::gfx::Bitmap::height () const inline
Definition at line 175 of file bitmap.h.
References height_.
Referenced by Bitmap(), Bitmap(), Bitmap(), Create(), Create(), yaze::app::gui::BitmapViewer::Display(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawBitmap(), LoadFromPngData(), and yaze::app::editor::Tile16Editor::LoadTile8().
depth()
auto yaze::app::gfx::Bitmap::depth () const inline
Definition at line 176 of file bitmap.h.
References depth_.
Referenced by Bitmap(), Bitmap(), Bitmap(), Create(), and Create().
size()
auto yaze::app::gfx::Bitmap::size () const inline
Definition at line 177 of file bitmap.h.
References data_size_.
data()
auto yaze::app::gfx::Bitmap::data () const inline
Definition at line 178 of file bitmap.h.
References data_.
Referenced by Bitmap(), Bitmap(), Create(), Create(), yaze::app::editor::Tile16Editor::LoadTile8(), and set_data().
mutable_data()
auto & yaze::app::gfx::Bitmap::mutable_data () inline
Definition at line 179 of file bitmap.h.
References data_.
Referenced by yaze::app::zelda3::screen::TitleScreen::BuildTileset().
mutable_pixel_data()
auto yaze::app::gfx::Bitmap::mutable_pixel_data () inline
Definition at line 180 of file bitmap.h.
References pixel_data_.
surface()
auto yaze::app::gfx::Bitmap::surface () const inline
Definition at line 181 of file bitmap.h.
References surface_.
Referenced by yaze::app::gui::Canvas::DrawContextMenu(), LoadFromPngData(), and SetSurface().
mutable_surface()
auto yaze::app::gfx::Bitmap::mutable_surface () inline
Definition at line 182 of file bitmap.h.
References surface_.
converted_surface()
auto yaze::app::gfx::Bitmap::converted_surface () const inline
Definition at line 183 of file bitmap.h.
References converted_surface_.
Referenced by CreateTexture(), and UpdateTexture().
mutable_converted_surface()
auto yaze::app::gfx::Bitmap::mutable_converted_surface () inline
Definition at line 184 of file bitmap.h.
References converted_surface_.
set_data()
void yaze::app::gfx::Bitmap::set_data (const Bytes & data) inline
Definition at line 185 of file bitmap.h.
References data(), and data_.
vector()
auto yaze::app::gfx::Bitmap::vector () const inline
Definition at line 187 of file bitmap.h.
References data_.
Referenced by yaze::app::editor::Tile16Editor::InitBlockset().
at()
auto yaze::app::gfx::Bitmap::at (int i) const inline
Definition at line 188 of file bitmap.h.
References data_.
Referenced by yaze::app::Rom::mutable_graphics_sheet().
texture()
auto yaze::app::gfx::Bitmap::texture () const inline
Definition at line 189 of file bitmap.h.
References texture_.
Referenced by yaze::app::gui::BitmapViewer::Display(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawBitmap(), and yaze::app::gui::Canvas::DrawTilePainter().
modified()
auto yaze::app::gfx::Bitmap::modified () const inline
Definition at line 190 of file bitmap.h.
References modified_.
Referenced by set_modified().
set_modified()
void yaze::app::gfx::Bitmap::set_modified (bool modified) inline
Definition at line 191 of file bitmap.h.
References modified(), and modified_.
Referenced by yaze::app::editor::OverworldEditor::RenderUpdatedMapBitmap().
is_active()
auto yaze::app::gfx::Bitmap::is_active () const inline
Definition at line 192 of file bitmap.h.
References active_.
Referenced by yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawBitmap(), and yaze::app::gui::Canvas::DrawTilePainter().
set_active()
auto yaze::app::gfx::Bitmap::set_active (bool active) inline
Definition at line 193 of file bitmap.h.
References active_.
Member Data Documentation
width_
int yaze::app::gfx::Bitmap::width_ = 0 private
Definition at line 212 of file bitmap.h.
Referenced by Cleanup(), Create(), Create(), CreateTexture(), Get16x16Tile(), Get16x16Tile(), Get8x8Tile(), LoadFromPngData(), Reformat(), and width().
height_
int yaze::app::gfx::Bitmap::height_ = 0 private
Definition at line 213 of file bitmap.h.
Referenced by Cleanup(), Create(), Create(), CreateTexture(), Get16x16Tile(), Get8x8Tile(), height(), LoadFromPngData(), and Reformat().
depth_
int yaze::app::gfx::Bitmap::depth_ = 0 private
Definition at line 214 of file bitmap.h.
Referenced by Cleanup(), Create(), Create(), depth(), and Reformat().
data_size_
int yaze::app::gfx::Bitmap::data_size_ = 0 private
Definition at line 215 of file bitmap.h.
Referenced by Cleanup(), Create(), Create(), and size().
freed_
bool yaze::app::gfx::Bitmap::freed_ = false private
Definition at line 217 of file bitmap.h.
active_
bool yaze::app::gfx::Bitmap::active_ = false private
Definition at line 218 of file bitmap.h.
Referenced by Cleanup(), Create(), Create(), is_active(), Reformat(), and set_active().
modified_
bool yaze::app::gfx::Bitmap::modified_ = false private
Definition at line 219 of file bitmap.h.
Referenced by modified(), set_modified(), WriteColor(), WriteToPixel(), and WriteWordToPixel().
texture_pixels
void* yaze::app::gfx::Bitmap::texture_pixels = nullptr private
Definition at line 220 of file bitmap.h.
Referenced by CreateTexture(), and UpdateTexture().
pixel_data_
uchar* yaze::app::gfx::Bitmap::pixel_data_ private
Definition at line 222 of file bitmap.h.
Referenced by Create(), Create(), mutable_pixel_data(), Reformat(), WriteColor(), WriteToPixel(), and WriteWordToPixel().
data_
Bytes yaze::app::gfx::Bitmap::data_ private
Definition at line 223 of file bitmap.h.
Referenced by at(), Create(), Create(), data(), Get16x16Tile(), Get16x16Tile(), Get8x8Tile(), mutable_data(), set_data(), vector(), WriteToPixel(), and WriteWordToPixel().
png_data_
std::vector<uint8_t> yaze::app::gfx::Bitmap::png_data_ private
Definition at line 225 of file bitmap.h.
Referenced by GetPngData().
palette_
gfx::SnesPalette yaze::app::gfx::Bitmap::palette_ private
Definition at line 227 of file bitmap.h.
Referenced by ApplyPalette(), ApplyPaletteFromPaletteGroup(), ApplyPaletteWithTransparent(), Cleanup(), mutable_palette(), palette(), palette_size(), and Reformat().
texture_
std::shared_ptr<SDL_Texture> yaze::app::gfx::Bitmap::texture_ = nullptr private
Definition at line 228 of file bitmap.h.
Referenced by CreateTexture(), CreateTexture(), texture(), UpdateTexture(), and UpdateTexture().
surface_
std::shared_ptr<SDL_Surface> yaze::app::gfx::Bitmap::surface_ = nullptr private
Definition at line 229 of file bitmap.h.
Referenced by ApplyPalette(), ApplyPalette(), ApplyPaletteFromPaletteGroup(), ApplyPaletteWithTransparent(), Create(), Create(), CreateTexture(), CreateTexture(), GetPngData(), LoadFromPngData(), mutable_surface(), Reformat(), SaveSurfaceToFile(), sdl_palette(), SetSurface(), surface(), UpdateTexture(), UpdateTexture(), and WriteColor().
converted_surface_
std::shared_ptr<SDL_Surface> yaze::app::gfx::Bitmap::converted_surface_ = nullptr private
Definition at line 230 of file bitmap.h.
Referenced by converted_surface(), CreateTexture(), mutable_converted_surface(), and UpdateTexture().
The documentation for this class was generated from the following files:
src/app/gfx/bitmap.h
src/app/gfx/bitmap.cc