yaze: yaze::app::zelda3::Overworld Class Reference
yaze::app::zelda3::Overworld Class Reference
#include <overworld.h>
Public Member Functions
OWBlockset & GetMapTiles (int world_type)
absl::Status Load (ROM &rom)
absl::Status LoadOverworldMaps ()
void LoadTileTypes ()
void LoadEntrances ()
absl::Status LoadExits ()
absl::Status LoadItems ()
absl::Status LoadSprites ()
absl::Status LoadSpritesFromMap (int spriteStart, int spriteCount, int spriteIndex)
absl::Status Save (ROM &rom)
absl::Status SaveOverworldMaps ()
absl::Status SaveLargeMaps ()
absl::Status SaveEntrances ()
absl::Status SaveExits ()
absl::Status SaveItems ()
absl::Status CreateTile32Tilemap ()
absl::Status SaveMap16Tiles ()
absl::Status SaveMap32Tiles ()
absl::Status SaveMapProperties ()
absl::Status LoadPrototype (ROM &rom_, const std::string &tilemap_filename)
void Destroy ()
int GetTileFromPosition (ImVec2 position) const
auto overworld_maps () const
auto overworld_map (int i) const
auto mutable_overworld_map (int i)
auto exits () const
auto mutable_exits ()
std::vector< gfx::Tile16 > tiles16 () const
auto Sprites (int state) const
auto mutable_sprites (int state)
auto current_graphics () const
auto & entrances ()
auto mutable_entrances ()
auto & holes ()
auto mutable_holes ()
auto deleted_entrances () const
auto mutable_deleted_entrances ()
auto AreaPalette () const
auto AreaPaletteById (int id) const
auto BitmapData () const
auto Tile16Blockset () const
auto is_loaded () const
void set_current_map (int i)
auto map_tiles () const
auto mutable_map_tiles ()
auto all_items () const
auto mutable_all_items ()
auto & ref_all_items ()
auto all_tiles_types () const
auto mutable_all_tiles_types ()
Public Member Functions inherited from yaze::app::SharedROM
SharedROM ()=default
virtual ~SharedROM ()=default
std::shared_ptr< ROM > shared_rom ()
auto rom ()
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
Public Attributes
int current_world_ = 0
Private Types
enum Dimension { map32TilesTL = 0 , map32TilesTR = 1 , map32TilesBL = 2 , map32TilesBR = 3 }
Private Member Functions
void FetchLargeMaps ()
void AssembleMap32Tiles ()
void AssembleMap16Tiles ()
void AssignWorldTiles (int x, int y, int sx, int sy, int tpos, OWBlockset &world)
void OrganizeMapTiles (Bytes &bytes, Bytes &bytes2, int i, int sx, int sy, int &ttpos)
absl::Status DecompressAllMapTiles ()
absl::Status DecompressProtoMapTiles (const std::string &filename)
Private Attributes
bool is_loaded_ = false
int game_state_ = 0
int current_map_ = 0
uchar map_parent_ [160]
ROM rom_
OWMapTiles map_tiles_
uint8_t all_tiles_types_ [0x200]
std::vector< gfx::Tile16 > tiles16_
std::vector< gfx::Tile32 > tiles32_
std::vector< uint16_t > tiles32_list_
std::vector< gfx::Tile32 > tiles32_unique_
std::vector< OverworldMap > overworld_maps_
std::vector< OverworldEntrance > all_entrances_
std::vector< OverworldEntrance > all_holes_
std::vector< OverworldExit > all_exits_
std::vector< OverworldItem > all_items_
std::vector< std::vector< Sprite > > all_sprites_
std::vector< uint64_t > deleted_entrances_
std::vector< std::vector< uint8_t > > map_data_p1
std::vector< std::vector< uint8_t > > map_data_p2
std::vector< int > map_pointers1_id = std::vector<int>(kNumOverworldMaps)
std::vector< int > map_pointers2_id = std::vector<int>(kNumOverworldMaps)
std::vector< int > map_pointers1 = std::vector<int>(kNumOverworldMaps)
std::vector< int > map_pointers2 = std::vector<int>(kNumOverworldMaps)
std::vector< absl::flat_hash_map< uint16_t, int > > usage_stats_
absl::flat_hash_map< int, MapData > proto_map_data_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedROM
static std::shared_ptr< ROM > shared_rom_ = nullptr
Member Enumeration Documentation
Dimension
enum yaze::app::zelda3::Overworld::Dimension private
Enumerator
map32TilesTL
map32TilesTR
map32TilesBL
map32TilesBR
Member Function Documentation
GetMapTiles()
OWBlockset & yaze::app::zelda3::Overworld::GetMapTiles (int world_type)
References OWMapTiles::dark_world, OWMapTiles::light_world, map_tiles_, and OWMapTiles::special_world.
Referenced by LoadOverworldMaps().
Load()
absl::Status yaze::app::zelda3::Overworld::Load (ROM & rom)
References AssembleMap16Tiles(), AssembleMap32Tiles(), DecompressAllMapTiles(), FetchLargeMaps(), is_loaded_, yaze::app::zelda3::kNumOverworldMaps, LoadEntrances(), LoadExits(), LoadItems(), LoadOverworldMaps(), LoadSprites(), overworld_maps_, RETURN_IF_ERROR, yaze::app::SharedROM::rom(), rom_, and tiles16_.
Referenced by yaze::app::editor::OverworldEditor::LoadGraphics(), and yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
LoadOverworldMaps()
absl::Status yaze::app::zelda3::Overworld::LoadOverworldMaps ()
References game_state_, GetMapTiles(), yaze::app::zelda3::kNumOverworldMaps, overworld_maps_, and tiles16_.
Referenced by Load().
LoadTileTypes()
void yaze::app::zelda3::Overworld::LoadTileTypes ()
References all_tiles_types_, yaze::app::zelda3::overworldTilesType, and yaze::app::SharedROM::rom().
LoadEntrances()
void yaze::app::zelda3::Overworld::LoadEntrances ()
References all_entrances_, all_holes_, yaze::app::zelda3::OWEntranceEntranceId, yaze::app::zelda3::OWEntranceMap, yaze::app::zelda3::OWEntrancePos, yaze::app::zelda3::OWHoleArea, yaze::app::zelda3::OWHoleEntrance, yaze::app::zelda3::OWHolePos, yaze::app::SharedROM::rom(), and rom_.
Referenced by Load(), and LoadPrototype().
LoadExits()
absl::Status yaze::app::zelda3::Overworld::LoadExits ()
References all_exits_, yaze::app::ROM::data(), exits(), yaze::app::zelda3::OWExitDoorType1, yaze::app::zelda3::OWExitDoorType2, yaze::app::zelda3::OWExitMapId, yaze::app::zelda3::OWExitRoomId, yaze::app::zelda3::OWExitUnk1, yaze::app::zelda3::OWExitUnk2, yaze::app::zelda3::OWExitVram, yaze::app::zelda3::OWExitXCamera, yaze::app::zelda3::OWExitXPlayer, yaze::app::zelda3::OWExitXScroll, yaze::app::zelda3::OWExitYCamera, yaze::app::zelda3::OWExitYPlayer, yaze::app::zelda3::OWExitYScroll, RETURN_IF_ERROR, and yaze::app::SharedROM::rom().
Referenced by Load().
LoadItems()
absl::Status yaze::app::zelda3::Overworld::LoadItems ()
References all_items_, ASSIGN_OR_RETURN, overworld_maps_, yaze::app::zelda3::overworldItemsAddress, yaze::app::SharedROM::rom(), and yaze::app::core::SnesToPc().
Referenced by Load().
LoadSprites()
absl::Status yaze::app::zelda3::Overworld::LoadSprites ()
References all_sprites_, LoadSpritesFromMap(), yaze::app::zelda3::overworldSpritesAgahnim, yaze::app::zelda3::overworldSpritesBegining, yaze::app::zelda3::overworldSpritesZelda, and RETURN_IF_ERROR.
Referenced by Load().
LoadSpritesFromMap()
absl::Status yaze::app::zelda3::Overworld::LoadSpritesFromMap (int spriteStart, int spriteCount, int spriteIndex)
References all_sprites_, ASSIGN_OR_RETURN, current_graphics(), map_parent_, overworld_maps_, yaze::app::SharedROM::rom(), and yaze::app::core::SnesToPc().
Referenced by LoadSprites().
Save()
absl::Status yaze::app::zelda3::Overworld::Save (ROM & rom)
References RETURN_IF_ERROR, yaze::app::SharedROM::rom(), rom_, SaveEntrances(), SaveExits(), SaveMap16Tiles(), SaveMap32Tiles(), and SaveOverworldMaps().
SaveOverworldMaps()
absl::Status yaze::app::zelda3::Overworld::SaveOverworldMaps ()
References yaze::app::gfx::lc_lz2::Compress(), yaze::app::zelda3::kCompressedAllMap32PointersHigh, yaze::app::zelda3::kCompressedAllMap32PointersLow, yaze::app::core::Logger::log(), map_data_p1, map_data_p2, map_pointers1, map_pointers1_id, map_pointers2, map_pointers2_id, yaze::app::zelda3::OverworldMapDataOverflow, yaze::app::core::PcToSnes(), RETURN_IF_ERROR, yaze::app::SharedROM::rom(), SaveLargeMaps(), tiles32_list_, yaze::app::core::UppercaseHexByte(), and yaze::app::core::UppercaseHexLong().
Referenced by Save().
SaveLargeMaps()
absl::Status yaze::app::zelda3::Overworld::SaveLargeMaps ()
References yaze::app::core::Logger::log(), overworld_maps_, yaze::app::zelda3::overworldMapParentId, yaze::app::zelda3::overworldMapSize, yaze::app::zelda3::overworldMapSizeHighByte, yaze::app::zelda3::overworldScreenSize, yaze::app::zelda3::OverworldScreenSizeForLoading, yaze::app::zelda3::OverworldScreenTileMapChangeByScreen1, yaze::app::zelda3::OverworldScreenTileMapChangeByScreen2, yaze::app::zelda3::OverworldScreenTileMapChangeByScreen3, yaze::app::zelda3::OverworldScreenTileMapChangeByScreen4, yaze::app::zelda3::overworldTransitionPositionX, yaze::app::zelda3::overworldTransitionPositionY, RETURN_IF_ERROR, yaze::app::SharedROM::rom(), yaze::app::zelda3::transition_target_north, and yaze::app::zelda3::transition_target_west.
Referenced by SaveOverworldMaps().
SaveEntrances()
absl::Status yaze::app::zelda3::Overworld::SaveEntrances ()
References all_entrances_, all_holes_, yaze::app::core::Logger::log(), yaze::app::zelda3::OWEntranceEntranceId, yaze::app::zelda3::OWEntranceMap, yaze::app::zelda3::OWEntrancePos, yaze::app::zelda3::OWHoleArea, yaze::app::zelda3::OWHoleEntrance, yaze::app::zelda3::OWHolePos, RETURN_IF_ERROR, and yaze::app::SharedROM::rom().
Referenced by Save().
SaveExits()
absl::Status yaze::app::zelda3::Overworld::SaveExits ()
References all_exits_, yaze::app::core::Logger::log(), yaze::app::zelda3::OWExitDoorType1, yaze::app::zelda3::OWExitDoorType2, yaze::app::zelda3::OWExitMapId, yaze::app::zelda3::OWExitRoomId, yaze::app::zelda3::OWExitUnk1, yaze::app::zelda3::OWExitUnk2, yaze::app::zelda3::OWExitVram, yaze::app::zelda3::OWExitXCamera, yaze::app::zelda3::OWExitXPlayer, yaze::app::zelda3::OWExitXScroll, yaze::app::zelda3::OWExitYCamera, yaze::app::zelda3::OWExitYPlayer, yaze::app::zelda3::OWExitYScroll, RETURN_IF_ERROR, and yaze::app::SharedROM::rom().
Referenced by Save().
SaveItems()
absl::Status yaze::app::zelda3::Overworld::SaveItems ()
References all_items_, yaze::app::core::ExperimentFlags::flags(), yaze::app::zelda3::overworldItemsEndData, yaze::app::zelda3::overworldItemsPointers, yaze::app::core::PcToSnes(), RETURN_IF_ERROR, and yaze::app::SharedROM::rom().
CreateTile32Tilemap()
absl::Status yaze::app::zelda3::Overworld::CreateTile32Tilemap ()
References yaze::app::core::ExperimentFlags::flags(), yaze::app::gfx::Tile32::GetPackedValue(), yaze::app::zelda3::LimitOfMap32, map_tiles_, yaze::app::zelda3::NumberOfMap32, tiles32_list_, and tiles32_unique_.
SaveMap16Tiles()
absl::Status yaze::app::zelda3::Overworld::SaveMap16Tiles ()
References yaze::app::zelda3::kMap16Tiles, yaze::app::core::Logger::log(), yaze::app::zelda3::NumberOfMap16, RETURN_IF_ERROR, yaze::app::SharedROM::rom(), and tiles16_.
Referenced by Save().
SaveMap32Tiles()
absl::Status yaze::app::zelda3::Overworld::SaveMap32Tiles ()
References yaze::app::core::Logger::log(), map32TilesBL, map32TilesBR, RETURN_IF_ERROR, yaze::app::SharedROM::rom(), and tiles32_unique_.
Referenced by Save().
SaveMapProperties()
absl::Status yaze::app::zelda3::Overworld::SaveMapProperties ()
References yaze::app::core::Logger::log(), yaze::app::zelda3::mapGfx, overworld_maps_, yaze::app::zelda3::overworldMapPalette, yaze::app::zelda3::overworldSpritePalette, yaze::app::zelda3::overworldSpriteset, RETURN_IF_ERROR, and yaze::app::SharedROM::rom().
LoadPrototype()
absl::Status yaze::app::zelda3::Overworld::LoadPrototype (ROM & rom_, const std::string & tilemap_filename)
References AssembleMap16Tiles(), AssembleMap32Tiles(), OWMapTiles::dark_world, DecompressProtoMapTiles(), FetchLargeMaps(), game_state_, is_loaded_, yaze::app::zelda3::kNumOverworldMaps, OWMapTiles::light_world, LoadEntrances(), map_tiles_, overworld_maps_, RETURN_IF_ERROR, yaze::app::SharedROM::rom(), rom_, OWMapTiles::special_world, and tiles16_.
Destroy()
void yaze::app::zelda3::Overworld::Destroy () inline
References all_entrances_, all_exits_, all_items_, all_sprites_, is_loaded_, and overworld_maps_.
Referenced by yaze::app::editor::OverworldEditor::Shutdown().
GetTileFromPosition()
int yaze::app::zelda3::Overworld::GetTileFromPosition (ImVec2 position) const inline
References current_world_, OWMapTiles::dark_world, OWMapTiles::light_world, map_tiles_, and OWMapTiles::special_world.
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits(), and yaze::app::editor::OverworldEditor::CheckForSelectRectangle().
overworld_maps()
auto yaze::app::zelda3::Overworld::overworld_maps () const inline
References overworld_maps_.
overworld_map()
auto yaze::app::zelda3::Overworld::overworld_map (int i) const inline
References overworld_maps_.
Referenced by yaze::app::editor::OverworldEditor::CheckForCurrentMap(), yaze::app::editor::OverworldEditor::DrawOverworldProperties(), yaze::app::editor::OverworldEditor::RefreshMapPalette(), yaze::app::editor::OverworldEditor::RefreshOverworldMap(), and yaze::app::editor::OverworldEditor::RefreshTile16Blockset().
mutable_overworld_map()
auto yaze::app::zelda3::Overworld::mutable_overworld_map (int i) inline
References overworld_maps_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldMapSettings(), yaze::app::editor::OverworldEditor::LoadAnimatedMaps(), yaze::app::editor::OverworldEditor::RefreshChildMap(), yaze::app::editor::OverworldEditor::RefreshMapPalette(), and yaze::app::editor::OverworldEditor::RefreshMapProperties().
exits()
auto yaze::app::zelda3::Overworld::exits () const inline
References all_exits_.
Referenced by LoadExits().
mutable_exits()
auto yaze::app::zelda3::Overworld::mutable_exits () inline
References all_exits_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldExits().
tiles16()
std::vector< gfx::Tile16 > yaze::app::zelda3::Overworld::tiles16 () const inline
References tiles16_.
Referenced by yaze::app::editor::OverworldEditor::LoadAnimatedMaps(), and yaze::app::editor::OverworldEditor::RefreshChildMap().
Sprites()
auto yaze::app::zelda3::Overworld::Sprites (int state) const inline
References all_sprites_.
Referenced by yaze::app::editor::OverworldEditor::LoadSpriteGraphics().
mutable_sprites()
auto yaze::app::zelda3::Overworld::mutable_sprites (int state) inline
References all_sprites_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldSprites().
current_graphics()
auto yaze::app::zelda3::Overworld::current_graphics () const inline
References current_map_, and overworld_maps_.
Referenced by yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::OverworldEditor::LoadGraphics(), and LoadSpritesFromMap().
entrances()
auto & yaze::app::zelda3::Overworld::entrances () inline
References all_entrances_.
Referenced by yaze::app::editor::OverworldEditor::CalculateUsageStats(), yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), and yaze::app::editor::OverworldEditor::UpdateUsageStats().
mutable_entrances()
auto yaze::app::zelda3::Overworld::mutable_entrances () inline
References all_entrances_.
holes()
auto & yaze::app::zelda3::Overworld::holes () inline
References all_holes_.
mutable_holes()
auto yaze::app::zelda3::Overworld::mutable_holes () inline
References all_holes_.
deleted_entrances()
auto yaze::app::zelda3::Overworld::deleted_entrances () const inline
References deleted_entrances_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances().
mutable_deleted_entrances()
auto yaze::app::zelda3::Overworld::mutable_deleted_entrances () inline
References deleted_entrances_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances().
AreaPalette()
auto yaze::app::zelda3::Overworld::AreaPalette () const inline
References current_map_, and overworld_maps_.
Referenced by yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::OverworldEditor::LoadGraphics(), yaze::app::editor::OverworldEditor::RefreshTile16Blockset(), and yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
AreaPaletteById()
auto yaze::app::zelda3::Overworld::AreaPaletteById (int id) const inline
References overworld_maps_.
BitmapData()
auto yaze::app::zelda3::Overworld::BitmapData () const inline
References current_map_, and overworld_maps_.
Referenced by yaze::app::editor::OverworldEditor::LoadGraphics().
Tile16Blockset()
auto yaze::app::zelda3::Overworld::Tile16Blockset () const inline
References current_map_, and overworld_maps_.
Referenced by yaze::app::editor::OverworldEditor::LoadGraphics(), yaze::app::editor::OverworldEditor::RefreshTile16Blockset(), and yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
is_loaded()
auto yaze::app::zelda3::Overworld::is_loaded () const inline
References is_loaded_.
Referenced by yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), and yaze::app::editor::OverworldEditor::DrawToolset().
set_current_map()
void yaze::app::zelda3::Overworld::set_current_map (int i) inline
References current_map_.
Referenced by yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::OverworldEditor::LoadGraphics(), yaze::app::editor::OverworldEditor::RefreshTile16Blockset(), and yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
map_tiles()
auto yaze::app::zelda3::Overworld::map_tiles () const inline
References map_tiles_.
Referenced by yaze::app::editor::OverworldEditor::LoadAnimatedMaps(), and yaze::app::editor::OverworldEditor::RefreshChildMap().
mutable_map_tiles()
auto yaze::app::zelda3::Overworld::mutable_map_tiles () inline
References map_tiles_.
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits(), yaze::app::editor::OverworldEditor::DrawDebugWindow(), and yaze::app::editor::OverworldEditor::DrawOverworldEdits().
all_items()
auto yaze::app::zelda3::Overworld::all_items () const inline
References all_items_.
mutable_all_items()
auto yaze::app::zelda3::Overworld::mutable_all_items () inline
References all_items_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldItems().
ref_all_items()
auto & yaze::app::zelda3::Overworld::ref_all_items () inline
References all_items_.
all_tiles_types()
auto yaze::app::zelda3::Overworld::all_tiles_types () const inline
References all_tiles_types_.
mutable_all_tiles_types()
auto yaze::app::zelda3::Overworld::mutable_all_tiles_types () inline
References all_tiles_types_.
Referenced by yaze::app::editor::OverworldEditor::Update().
FetchLargeMaps()
void yaze::app::zelda3::Overworld::FetchLargeMaps () private
References overworld_maps_.
Referenced by Load(), and LoadPrototype().
AssembleMap32Tiles()
void yaze::app::zelda3::Overworld::AssembleMap32Tiles () private
References OWMapTiles::dark_world, OWMapTiles::light_world, map32TilesBL, map32TilesBR, map32TilesTL, map32TilesTR, map_tiles_, yaze::app::SharedROM::rom(), rom_, OWMapTiles::special_world, and tiles32_unique_.
Referenced by Load(), and LoadPrototype().
AssembleMap16Tiles()
void yaze::app::zelda3::Overworld::AssembleMap16Tiles () private
References yaze::app::gfx::GetTilesInfo(), yaze::app::zelda3::kMap16Tiles, yaze::app::SharedROM::rom(), and tiles16_.
Referenced by Load(), and LoadPrototype().
AssignWorldTiles()
void yaze::app::zelda3::Overworld::AssignWorldTiles (int x, int y, int sx, int sy, int tpos, OWBlockset & world) private
References tiles32_unique_.
Referenced by OrganizeMapTiles().
OrganizeMapTiles()
void yaze::app::zelda3::Overworld::OrganizeMapTiles (Bytes & bytes, Bytes & bytes2, int i, int sx, int sy, int & ttpos) private
References AssignWorldTiles(), OWMapTiles::dark_world, OWMapTiles::light_world, map_tiles_, OWMapTiles::special_world, and tiles32_unique_.
Referenced by DecompressAllMapTiles(), and DecompressProtoMapTiles().
DecompressAllMapTiles()
absl::Status yaze::app::zelda3::Overworld::DecompressAllMapTiles () private
References yaze::app::zelda3::kCompressedAllMap32PointersHigh, yaze::app::zelda3::kCompressedAllMap32PointersLow, OrganizeMapTiles(), yaze::app::SharedROM::rom(), yaze::app::core::SnesToPc(), and yaze::app::gfx::lc_lz2::Uncompress().
Referenced by Load().
DecompressProtoMapTiles()
absl::Status yaze::app::zelda3::Overworld::DecompressProtoMapTiles (const std::string & filename) private
References ASSIGN_OR_RETURN, yaze::app::gfx::lc_lz2::DecompressOverworld(), OrganizeMapTiles(), and proto_map_data_.
Referenced by LoadPrototype().
Member Data Documentation
current_world_
int yaze::app::zelda3::Overworld::current_world_ = 0
Referenced by GetTileFromPosition().
is_loaded_
bool yaze::app::zelda3::Overworld::is_loaded_ = false private
Referenced by Destroy(), is_loaded(), Load(), and LoadPrototype().
game_state_
int yaze::app::zelda3::Overworld::game_state_ = 0 private
Referenced by LoadOverworldMaps(), and LoadPrototype().
current_map_
int yaze::app::zelda3::Overworld::current_map_ = 0 private
Referenced by AreaPalette(), BitmapData(), current_graphics(), set_current_map(), and Tile16Blockset().
map_parent_
uchar yaze::app::zelda3::Overworld::map_parent_[160] private
Referenced by LoadSpritesFromMap().
rom_
ROM yaze::app::zelda3::Overworld::rom_ private
Referenced by AssembleMap32Tiles(), Load(), LoadEntrances(), LoadPrototype(), and Save().
map_tiles_
OWMapTiles yaze::app::zelda3::Overworld::map_tiles_ private
Referenced by AssembleMap32Tiles(), CreateTile32Tilemap(), GetMapTiles(), GetTileFromPosition(), LoadPrototype(), map_tiles(), mutable_map_tiles(), and OrganizeMapTiles().
all_tiles_types_
uint8_t yaze::app::zelda3::Overworld::all_tiles_types_[0x200] private
Referenced by all_tiles_types(), LoadTileTypes(), and mutable_all_tiles_types().
tiles16_
std::vector<gfx::Tile16> yaze::app::zelda3::Overworld::tiles16_ private
Referenced by AssembleMap16Tiles(), Load(), LoadOverworldMaps(), LoadPrototype(), SaveMap16Tiles(), and tiles16().
tiles32_
std::vector<gfx::Tile32> yaze::app::zelda3::Overworld::tiles32_ private
tiles32_list_
std::vector<uint16_t> yaze::app::zelda3::Overworld::tiles32_list_ private
Referenced by CreateTile32Tilemap(), and SaveOverworldMaps().
tiles32_unique_
std::vector<gfx::Tile32> yaze::app::zelda3::Overworld::tiles32_unique_ private
Referenced by AssembleMap32Tiles(), AssignWorldTiles(), CreateTile32Tilemap(), OrganizeMapTiles(), and SaveMap32Tiles().
overworld_maps_
std::vector<OverworldMap> yaze::app::zelda3::Overworld::overworld_maps_ private
Referenced by AreaPalette(), AreaPaletteById(), BitmapData(), current_graphics(), Destroy(), FetchLargeMaps(), Load(), LoadItems(), LoadOverworldMaps(), LoadPrototype(), LoadSpritesFromMap(), mutable_overworld_map(), overworld_map(), overworld_maps(), SaveLargeMaps(), SaveMapProperties(), and Tile16Blockset().
all_entrances_
std::vector<OverworldEntrance> yaze::app::zelda3::Overworld::all_entrances_ private
Referenced by Destroy(), entrances(), LoadEntrances(), mutable_entrances(), and SaveEntrances().
all_holes_
std::vector<OverworldEntrance> yaze::app::zelda3::Overworld::all_holes_ private
Referenced by holes(), LoadEntrances(), mutable_holes(), and SaveEntrances().
all_exits_
std::vector<OverworldExit> yaze::app::zelda3::Overworld::all_exits_ private
Referenced by Destroy(), exits(), LoadExits(), mutable_exits(), and SaveExits().
all_items_
std::vector<OverworldItem> yaze::app::zelda3::Overworld::all_items_ private
Referenced by all_items(), Destroy(), LoadItems(), mutable_all_items(), ref_all_items(), and SaveItems().
all_sprites_
std::vector<std::vector<Sprite> > yaze::app::zelda3::Overworld::all_sprites_ private
Referenced by Destroy(), LoadSprites(), LoadSpritesFromMap(), mutable_sprites(), and Sprites().
deleted_entrances_
std::vector<uint64_t> yaze::app::zelda3::Overworld::deleted_entrances_ private
Referenced by deleted_entrances(), and mutable_deleted_entrances().
map_data_p1
std::vector<std::vector<uint8_t> > yaze::app::zelda3::Overworld::map_data_p1 private
Initial value:
=
      std::vector<std::vector<uint8_t>>(kNumOverworldMaps)
Referenced by SaveOverworldMaps().
map_data_p2
std::vector<std::vector<uint8_t> > yaze::app::zelda3::Overworld::map_data_p2 private
Initial value:
=
      std::vector<std::vector<uint8_t>>(kNumOverworldMaps)
Referenced by SaveOverworldMaps().
map_pointers1_id
std::vector<int> yaze::app::zelda3::Overworld::map_pointers1_id = std::vector<int>(kNumOverworldMaps) private
Referenced by SaveOverworldMaps().
map_pointers2_id
std::vector<int> yaze::app::zelda3::Overworld::map_pointers2_id = std::vector<int>(kNumOverworldMaps) private
Referenced by SaveOverworldMaps().
map_pointers1
std::vector<int> yaze::app::zelda3::Overworld::map_pointers1 = std::vector<int>(kNumOverworldMaps) private
Referenced by SaveOverworldMaps().
map_pointers2
std::vector<int> yaze::app::zelda3::Overworld::map_pointers2 = std::vector<int>(kNumOverworldMaps) private
Referenced by SaveOverworldMaps().
usage_stats_
std::vector<absl::flat_hash_map<uint16_t, int> > yaze::app::zelda3::Overworld::usage_stats_ private
proto_map_data_
absl::flat_hash_map<int, MapData> yaze::app::zelda3::Overworld::proto_map_data_ private
Referenced by DecompressProtoMapTiles().
The documentation for this class was generated from the following files:
src/app/zelda3/overworld.h
src/app/zelda3/overworld.cc