yaze: yaze::zelda3::Room Class Reference
yaze::zelda3::Room Class Reference
#include <room.h>
Public Member Functions
Room ()=default
Room (int room_id, Rom *rom)
void LoadRoomGraphics (uint8_t entrance_blockset=0xFF)
void CopyRoomGraphicsToBuffer ()
void RenderRoomGraphics ()
void RenderObjectsToBackground ()
void LoadAnimatedGraphics ()
void LoadObjects ()
void LoadSprites ()
void LoadChests ()
void LoadRoomLayout ()
void LoadDoors ()
void LoadTorches ()
void LoadBlocks ()
void LoadPits ()
const RoomLayout & GetLayout () const
RoomLayout & GetLayout ()
const std::vector< zelda3::Sprite > & GetSprites () const
std::vector< zelda3::Sprite > & GetSprites ()
const std::vector< chest_data > & GetChests () const
std::vector< chest_data > & GetChests ()
const std::vector< staircase > & GetStairs () const
std::vector< staircase > & GetStairs ()
const std::vector< RoomObject > & GetTileObjects () const
std::vector< RoomObject > & GetTileObjects ()
void ClearTileObjects ()
void AddTileObject (const RoomObject &object)
void RemoveTileObject (size_t index)
size_t GetTileObjectCount () const
RoomObject & GetTileObject (size_t index)
const RoomObject & GetTileObject (size_t index) const
void SetTileObjects (const std::vector< RoomObject > &objects)
void SetBg2 (background2 bg2)
void SetCollision (CollisionKey collision)
void SetIsLight (bool is_light)
void SetPalette (uint8_t palette)
void SetBlockset (uint8_t blockset)
void SetSpriteset (uint8_t spriteset)
void SetEffect (EffectKey effect)
void SetTag1 (TagKey tag1)
void SetTag2 (TagKey tag2)
void SetStaircasePlane (int index, uint8_t plane)
void SetHolewarp (uint8_t holewarp)
void SetStaircaseRoom (int index, uint8_t room)
void SetFloor1 (uint8_t floor1)
void SetFloor2 (uint8_t floor2)
void SetMessageId (uint16_t message_id)
bool IsLight () const
void SetMessageIdDirect (uint16_t message_id)
void SetLayer2Mode (uint8_t mode)
void SetLayerMerging (LayerMergeType merging)
void SetIsDark (bool is_dark)
void SetPaletteDirect (uint8_t palette)
void SetBackgroundTileset (uint8_t tileset)
void SetSpriteTileset (uint8_t tileset)
void SetLayer2Behavior (uint8_t behavior)
void SetTag1Direct (TagKey tag1)
void SetTag2Direct (TagKey tag2)
void SetPitsTargetLayer (uint8_t layer)
void SetStair1TargetLayer (uint8_t layer)
void SetStair2TargetLayer (uint8_t layer)
void SetStair3TargetLayer (uint8_t layer)
void SetStair4TargetLayer (uint8_t layer)
void SetPitsTarget (uint8_t target)
void SetStair1Target (uint8_t target)
void SetStair2Target (uint8_t target)
void SetStair3Target (uint8_t target)
void SetStair4Target (uint8_t target)
void ParseObjectsFromLocation (int objects_location)
void HandleSpecialObjects (short oid, uint8_t posX, uint8_t posY, int &nbr_of_staircase)
auto blocks () const
auto & mutable_blocks ()
auto rom ()
auto mutable_rom ()
Public Attributes
uint8_t blockset = 0
uint8_t spriteset = 0
uint8_t palette = 0
uint8_t layout = 0
uint8_t holewarp = 0
uint8_t floor1 = 0
uint8_t floor2 = 0
uint16_t message_id_ = 0
Private Attributes
Rom * rom_
std::array< uint8_t, 0x4000 > current_gfx16_
bool is_light_
bool is_loaded_
bool is_dark_
bool is_floor_ = true
int room_id_
int animated_frame_
uint8_t staircase_plane_ [4]
uint8_t staircase_rooms_ [4]
uint8_t background_tileset_
uint8_t sprite_tileset_
uint8_t layer2_behavior_
uint8_t palette_
uint8_t floor1_graphics_
uint8_t floor2_graphics_
uint8_t layer2_mode_
std::array< uint8_t, 16 > blocks_
std::array< chest, 16 > chest_list_
std::vector< RoomObject > tile_objects_
std::vector< zelda3::Sprite > sprites_
std::vector< staircase > z3_staircases_
std::vector< chest_data > chests_in_room_
RoomLayout layout_
LayerMergeType layer_merging_
CollisionKey collision_
EffectKey effect_
TagKey tag1_
TagKey tag2_
background2 bg2_
destination pits_
destination stair1_
destination stair2_
destination stair3_
destination stair4_
Detailed Description
Definition at line 201 of file room.h.
Constructor & Destructor Documentation
Room() [1/2]
yaze::zelda3::Room::Room () default
Room() [2/2]
yaze::zelda3::Room::Room (int room_id, Rom * rom) inline
Definition at line 204 of file room.h.
Member Function Documentation
LoadRoomGraphics()
void yaze::zelda3::Room::LoadRoomGraphics (uint8_t entrance_blockset = 0xFF)
Definition at line 202 of file room.cc.
References blocks_, blockset, rom(), and spriteset.
Referenced by yaze::editor::DungeonRoomLoader::LoadAndRenderRoomGraphics().
CopyRoomGraphicsToBuffer()
void yaze::zelda3::Room::CopyRoomGraphicsToBuffer ()
Definition at line 235 of file room.cc.
References blocks_, current_gfx16_, yaze::Rom::is_loaded(), yaze::zelda3::kGfxBufferRoomOffset, yaze::zelda3::kGfxBufferRoomSpriteLastLineOffset, LoadAnimatedGraphics(), rom(), and rom_.
Referenced by RenderRoomGraphics().
RenderRoomGraphics()
void yaze::zelda3::Room::RenderRoomGraphics ()
Definition at line 286 of file room.cc.
References yaze::gfx::Arena::bg1(), yaze::gfx::Arena::bg2(), CopyRoomGraphicsToBuffer(), yaze::core::Renderer::CreateAndRenderBitmap(), current_gfx16_, floor1_graphics_, floor2_graphics_, yaze::core::Renderer::Get(), yaze::gfx::Arena::Get(), rom(), yaze::zelda3::tile_address, yaze::zelda3::tile_address_floor, and yaze::core::Renderer::UpdateBitmap().
Referenced by yaze::editor::DungeonRoomLoader::LoadAndRenderRoomGraphics().
RenderObjectsToBackground()
void yaze::zelda3::Room::RenderObjectsToBackground ()
LoadAnimatedGraphics()
void yaze::zelda3::Room::LoadAnimatedGraphics ()
Definition at line 314 of file room.cc.
References animated_frame_, background_tileset_, current_gfx16_, yaze::Rom::is_loaded(), rom(), rom_, and yaze::SnesToPc().
Referenced by CopyRoomGraphicsToBuffer().
LoadObjects()
void yaze::zelda3::Room::LoadObjects ()
Definition at line 375 of file room.cc.
References floor1_graphics_, floor2_graphics_, is_floor_, layout, LoadChests(), ParseObjectsFromLocation(), rom(), rom_, room_id_, yaze::zelda3::room_object_pointer, yaze::Rom::size(), yaze::SnesToPc(), and yaze::zelda3::tile_address.
LoadSprites()
void yaze::zelda3::Room::LoadSprites ()
Definition at line 561 of file room.cc.
References yaze::zelda3::Sprite::id(), yaze::zelda3::Sprite::layer(), rom(), room_id_, yaze::zelda3::rooms_sprite_pointer, yaze::zelda3::Sprite::set_key_drop(), yaze::SnesToPc(), sprites_, yaze::zelda3::Sprite::subtype(), yaze::zelda3::Sprite::x(), and yaze::zelda3::Sprite::y().
LoadChests()
void yaze::zelda3::Room::LoadChests ()
Definition at line 608 of file room.cc.
References yaze::zelda3::chests_data_pointer1, chests_in_room_, yaze::zelda3::chests_length_pointer, rom(), room_id_, and yaze::SnesToPc().
Referenced by LoadObjects().
LoadRoomLayout()
void yaze::zelda3::Room::LoadRoomLayout ()
Definition at line 632 of file room.cc.
References yaze::zelda3::RoomLayout::GetObjects(), layout, layout_, yaze::zelda3::RoomLayout::LoadLayout(), and room_id_.
Referenced by yaze::zelda3::LoadRoomFromRom().
LoadDoors()
void yaze::zelda3::Room::LoadDoors ()
Todo:
Implement full door loading from ROM data
Definition at line 649 of file room.cc.
References rom().
Referenced by yaze::zelda3::LoadRoomFromRom().
LoadTorches()
void yaze::zelda3::Room::LoadTorches ()
Todo:
Implement full torch loading from ROM data
Definition at line 660 of file room.cc.
References rom(), and yaze::zelda3::torches_length_pointer.
Referenced by yaze::zelda3::LoadRoomFromRom().
LoadBlocks()
void yaze::zelda3::Room::LoadBlocks ()
Todo:
Implement full block loading from ROM data
Definition at line 670 of file room.cc.
References yaze::zelda3::blocks_length, and rom().
Referenced by yaze::zelda3::LoadRoomFromRom().
LoadPits()
void yaze::zelda3::Room::LoadPits ()
Todo:
Implement full pit loading from ROM data
Definition at line 680 of file room.cc.
References yaze::zelda3::pit_count, and rom().
Referenced by yaze::zelda3::LoadRoomFromRom().
GetLayout() [1/2]
const RoomLayout & yaze::zelda3::Room::GetLayout () const inline
Definition at line 220 of file room.h.
References layout_.
Referenced by yaze::zelda3::ObjectRenderer::RenderRoom().
GetLayout() [2/2]
RoomLayout & yaze::zelda3::Room::GetLayout () inline
Definition at line 221 of file room.h.
References layout_.
GetSprites() [1/2]
const std::vector< zelda3::Sprite > & yaze::zelda3::Room::GetSprites () const inline
Definition at line 224 of file room.h.
References sprites_.
Referenced by yaze::editor::DungeonCanvasViewer::RenderSprites(), and yaze::editor::DungeonRenderer::RenderSprites().
GetSprites() [2/2]
std::vector< zelda3::Sprite > & yaze::zelda3::Room::GetSprites () inline
Definition at line 225 of file room.h.
References sprites_.
GetChests() [1/2]
const std::vector< chest_data > & yaze::zelda3::Room::GetChests () const inline
Definition at line 228 of file room.h.
References chests_in_room_.
GetChests() [2/2]
std::vector< chest_data > & yaze::zelda3::Room::GetChests () inline
Definition at line 229 of file room.h.
References chests_in_room_.
GetStairs() [1/2]
const std::vector< staircase > & yaze::zelda3::Room::GetStairs () const inline
Definition at line 232 of file room.h.
References z3_staircases_.
GetStairs() [2/2]
std::vector< staircase > & yaze::zelda3::Room::GetStairs () inline
Definition at line 233 of file room.h.
References z3_staircases_.
GetTileObjects() [1/2]
const std::vector< RoomObject > & yaze::zelda3::Room::GetTileObjects () const inline
Definition at line 237 of file room.h.
References tile_objects_.
Referenced by yaze::editor::DungeonCanvasViewer::RenderChests(), yaze::editor::DungeonCanvasViewer::RenderDoorObjects(), yaze::editor::DungeonCanvasViewer::RenderPotObjects(), yaze::zelda3::ObjectRenderer::RenderRoom(), yaze::editor::DungeonCanvasViewer::RenderStairObjects(), and yaze::editor::DungeonCanvasViewer::RenderWallObjects().
GetTileObjects() [2/2]
std::vector< RoomObject > & yaze::zelda3::Room::GetTileObjects () inline
Definition at line 240 of file room.h.
References tile_objects_.
ClearTileObjects()
void yaze::zelda3::Room::ClearTileObjects () inline
Definition at line 243 of file room.h.
References tile_objects_.
AddTileObject()
void yaze::zelda3::Room::AddTileObject (const RoomObject & object) inline
Definition at line 244 of file room.h.
References tile_objects_.
Referenced by yaze::zelda3::MockRoomGenerator::GenerateMockObjects().
RemoveTileObject()
void yaze::zelda3::Room::RemoveTileObject (size_t index) inline
Definition at line 247 of file room.h.
References tile_objects_.
GetTileObjectCount()
size_t yaze::zelda3::Room::GetTileObjectCount () const inline
Definition at line 252 of file room.h.
References tile_objects_.
GetTileObject() [1/2]
RoomObject & yaze::zelda3::Room::GetTileObject (size_t index) inline
Definition at line 253 of file room.h.
References tile_objects_.
GetTileObject() [2/2]
const RoomObject & yaze::zelda3::Room::GetTileObject (size_t index) const inline
Definition at line 254 of file room.h.
References tile_objects_.
SetTileObjects()
void yaze::zelda3::Room::SetTileObjects (const std::vector< RoomObject > & objects) inline
Definition at line 259 of file room.h.
References tile_objects_.
SetBg2()
void yaze::zelda3::Room::SetBg2 (background2 bg2) inline
Definition at line 264 of file room.h.
References bg2_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetCollision()
void yaze::zelda3::Room::SetCollision (CollisionKey collision) inline
Definition at line 265 of file room.h.
References collision_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetIsLight()
void yaze::zelda3::Room::SetIsLight (bool is_light) inline
Definition at line 266 of file room.h.
References is_light_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetPalette()
void yaze::zelda3::Room::SetPalette (uint8_t palette) inline
Definition at line 267 of file room.h.
References palette.
Referenced by yaze::zelda3::MockRoomGenerator::GenerateMockRoom(), and yaze::zelda3::LoadRoomFromRom().
SetBlockset()
void yaze::zelda3::Room::SetBlockset (uint8_t blockset) inline
Definition at line 268 of file room.h.
References blockset.
Referenced by yaze::zelda3::MockRoomGenerator::GenerateMockRoom(), and yaze::zelda3::LoadRoomFromRom().
SetSpriteset()
void yaze::zelda3::Room::SetSpriteset (uint8_t spriteset) inline
Definition at line 269 of file room.h.
References spriteset.
Referenced by yaze::zelda3::MockRoomGenerator::GenerateMockRoom(), and yaze::zelda3::LoadRoomFromRom().
SetEffect()
void yaze::zelda3::Room::SetEffect (EffectKey effect) inline
Definition at line 270 of file room.h.
References effect_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetTag1()
void yaze::zelda3::Room::SetTag1 (TagKey tag1) inline
Definition at line 271 of file room.h.
References tag1_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetTag2()
void yaze::zelda3::Room::SetTag2 (TagKey tag2) inline
Definition at line 272 of file room.h.
References tag2_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStaircasePlane()
void yaze::zelda3::Room::SetStaircasePlane (int index, uint8_t plane) inline
Definition at line 273 of file room.h.
References staircase_plane_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetHolewarp()
void yaze::zelda3::Room::SetHolewarp (uint8_t holewarp) inline
Definition at line 276 of file room.h.
References holewarp.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStaircaseRoom()
void yaze::zelda3::Room::SetStaircaseRoom (int index, uint8_t room) inline
Definition at line 277 of file room.h.
References staircase_rooms_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetFloor1()
void yaze::zelda3::Room::SetFloor1 (uint8_t floor1) inline
Definition at line 280 of file room.h.
References floor1.
Referenced by yaze::zelda3::MockRoomGenerator::GenerateMockRoom().
SetFloor2()
void yaze::zelda3::Room::SetFloor2 (uint8_t floor2) inline
Definition at line 281 of file room.h.
References floor2.
Referenced by yaze::zelda3::MockRoomGenerator::GenerateMockRoom().
SetMessageId()
void yaze::zelda3::Room::SetMessageId (uint16_t message_id) inline
Definition at line 282 of file room.h.
References message_id_.
Referenced by yaze::zelda3::MockRoomGenerator::GenerateMockRoom().
IsLight()
bool yaze::zelda3::Room::IsLight () const inline
Definition at line 285 of file room.h.
References is_light_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetMessageIdDirect()
void yaze::zelda3::Room::SetMessageIdDirect (uint16_t message_id) inline
Definition at line 288 of file room.h.
References message_id_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetLayer2Mode()
void yaze::zelda3::Room::SetLayer2Mode (uint8_t mode) inline
Definition at line 289 of file room.h.
References layer2_mode_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetLayerMerging()
void yaze::zelda3::Room::SetLayerMerging (LayerMergeType merging) inline
Definition at line 290 of file room.h.
References layer_merging_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetIsDark()
void yaze::zelda3::Room::SetIsDark (bool is_dark) inline
Definition at line 291 of file room.h.
References is_dark_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetPaletteDirect()
void yaze::zelda3::Room::SetPaletteDirect (uint8_t palette) inline
Definition at line 292 of file room.h.
References palette, and palette_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetBackgroundTileset()
void yaze::zelda3::Room::SetBackgroundTileset (uint8_t tileset) inline
Definition at line 293 of file room.h.
References background_tileset_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetSpriteTileset()
void yaze::zelda3::Room::SetSpriteTileset (uint8_t tileset) inline
Definition at line 294 of file room.h.
References sprite_tileset_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetLayer2Behavior()
void yaze::zelda3::Room::SetLayer2Behavior (uint8_t behavior) inline
Definition at line 295 of file room.h.
References layer2_behavior_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetTag1Direct()
void yaze::zelda3::Room::SetTag1Direct (TagKey tag1) inline
Definition at line 296 of file room.h.
References tag1_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetTag2Direct()
void yaze::zelda3::Room::SetTag2Direct (TagKey tag2) inline
Definition at line 297 of file room.h.
References tag2_.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetPitsTargetLayer()
void yaze::zelda3::Room::SetPitsTargetLayer (uint8_t layer) inline
Definition at line 298 of file room.h.
References pits_, and destination::target_layer.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair1TargetLayer()
void yaze::zelda3::Room::SetStair1TargetLayer (uint8_t layer) inline
Definition at line 299 of file room.h.
References stair1_, and destination::target_layer.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair2TargetLayer()
void yaze::zelda3::Room::SetStair2TargetLayer (uint8_t layer) inline
Definition at line 300 of file room.h.
References stair2_, and destination::target_layer.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair3TargetLayer()
void yaze::zelda3::Room::SetStair3TargetLayer (uint8_t layer) inline
Definition at line 301 of file room.h.
References stair3_, and destination::target_layer.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair4TargetLayer()
void yaze::zelda3::Room::SetStair4TargetLayer (uint8_t layer) inline
Definition at line 302 of file room.h.
References stair4_, and destination::target_layer.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetPitsTarget()
void yaze::zelda3::Room::SetPitsTarget (uint8_t target) inline
Definition at line 303 of file room.h.
References pits_, and destination::target.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair1Target()
void yaze::zelda3::Room::SetStair1Target (uint8_t target) inline
Definition at line 304 of file room.h.
References stair1_, and destination::target.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair2Target()
void yaze::zelda3::Room::SetStair2Target (uint8_t target) inline
Definition at line 305 of file room.h.
References stair2_, and destination::target.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair3Target()
void yaze::zelda3::Room::SetStair3Target (uint8_t target) inline
Definition at line 306 of file room.h.
References stair3_, and destination::target.
Referenced by yaze::zelda3::LoadRoomFromRom().
SetStair4Target()
void yaze::zelda3::Room::SetStair4Target (uint8_t target) inline
Definition at line 307 of file room.h.
References stair4_, and destination::target.
Referenced by yaze::zelda3::LoadRoomFromRom().
ParseObjectsFromLocation()
void yaze::zelda3::Room::ParseObjectsFromLocation (int objects_location)
Definition at line 425 of file room.cc.
References HandleSpecialObjects(), rom(), rom_, yaze::zelda3::RoomObject::set_rom(), yaze::Rom::size(), tile_objects_, and z3_staircases_.
Referenced by LoadObjects().
HandleSpecialObjects()
void yaze::zelda3::Room::HandleSpecialObjects (short oid, uint8_t posX, uint8_t posY, int & nbr_of_staircase)
Definition at line 524 of file room.cc.
References yaze::zelda3::Chest, chests_in_room_, staircase_rooms_, yaze::zelda3::Stairs, yaze::zelda3::stairsObjects, tile_objects_, and z3_staircases_.
Referenced by ParseObjectsFromLocation().
blocks()
auto yaze::zelda3::Room::blocks () const inline
Definition at line 322 of file room.h.
References blocks_.
mutable_blocks()
auto & yaze::zelda3::Room::mutable_blocks () inline
Definition at line 323 of file room.h.
References blocks_.
rom()
auto yaze::zelda3::Room::rom () inline
Definition at line 324 of file room.h.
References rom_.
Referenced by CopyRoomGraphicsToBuffer(), LoadAnimatedGraphics(), LoadBlocks(), LoadChests(), LoadDoors(), LoadObjects(), LoadPits(), LoadRoomGraphics(), LoadSprites(), LoadTorches(), ParseObjectsFromLocation(), and RenderRoomGraphics().
mutable_rom()
auto yaze::zelda3::Room::mutable_rom () inline
Definition at line 325 of file room.h.
References rom_.
Member Data Documentation
blockset
uint8_t yaze::zelda3::Room::blockset = 0
Definition at line 309 of file room.h.
Referenced by yaze::editor::DungeonRoomLoader::LoadAndRenderRoomGraphics(), LoadRoomGraphics(), and SetBlockset().
spriteset
uint8_t yaze::zelda3::Room::spriteset = 0
Definition at line 310 of file room.h.
Referenced by LoadRoomGraphics(), and SetSpriteset().
palette
uint8_t yaze::zelda3::Room::palette = 0
Definition at line 311 of file room.h.
Referenced by SetPalette(), and SetPaletteDirect().
layout
uint8_t yaze::zelda3::Room::layout = 0
Definition at line 312 of file room.h.
Referenced by LoadObjects(), and LoadRoomLayout().
holewarp
uint8_t yaze::zelda3::Room::holewarp = 0
Definition at line 313 of file room.h.
Referenced by SetHolewarp().
floor1
uint8_t yaze::zelda3::Room::floor1 = 0
Definition at line 314 of file room.h.
Referenced by SetFloor1().
floor2
uint8_t yaze::zelda3::Room::floor2 = 0
Definition at line 315 of file room.h.
Referenced by SetFloor2().
message_id_
uint16_t yaze::zelda3::Room::message_id_ = 0
Definition at line 316 of file room.h.
Referenced by SetMessageId(), and SetMessageIdDirect().
rom_
Rom* yaze::zelda3::Room::rom_ private
Definition at line 328 of file room.h.
Referenced by CopyRoomGraphicsToBuffer(), LoadAnimatedGraphics(), LoadObjects(), mutable_rom(), ParseObjectsFromLocation(), and rom().
current_gfx16_
std::array<uint8_t, 0x4000> yaze::zelda3::Room::current_gfx16_ private
Definition at line 330 of file room.h.
Referenced by CopyRoomGraphicsToBuffer(), LoadAnimatedGraphics(), and RenderRoomGraphics().
is_light_
bool yaze::zelda3::Room::is_light_ private
Definition at line 332 of file room.h.
Referenced by IsLight(), and SetIsLight().
is_loaded_
bool yaze::zelda3::Room::is_loaded_ private
Definition at line 333 of file room.h.
is_dark_
bool yaze::zelda3::Room::is_dark_ private
Definition at line 334 of file room.h.
Referenced by SetIsDark().
is_floor_
bool yaze::zelda3::Room::is_floor_ = true private
Definition at line 335 of file room.h.
Referenced by LoadObjects().
room_id_
int yaze::zelda3::Room::room_id_ private
Definition at line 337 of file room.h.
Referenced by LoadChests(), LoadObjects(), LoadRoomLayout(), and LoadSprites().
animated_frame_
int yaze::zelda3::Room::animated_frame_ private
Definition at line 338 of file room.h.
Referenced by LoadAnimatedGraphics().
staircase_plane_
uint8_t yaze::zelda3::Room::staircase_plane_[4] private
Definition at line 340 of file room.h.
Referenced by SetStaircasePlane().
staircase_rooms_
uint8_t yaze::zelda3::Room::staircase_rooms_[4] private
Definition at line 341 of file room.h.
Referenced by HandleSpecialObjects(), and SetStaircaseRoom().
background_tileset_
uint8_t yaze::zelda3::Room::background_tileset_ private
Definition at line 343 of file room.h.
Referenced by LoadAnimatedGraphics(), and SetBackgroundTileset().
sprite_tileset_
uint8_t yaze::zelda3::Room::sprite_tileset_ private
Definition at line 344 of file room.h.
Referenced by SetSpriteTileset().
layer2_behavior_
uint8_t yaze::zelda3::Room::layer2_behavior_ private
Definition at line 345 of file room.h.
Referenced by SetLayer2Behavior().
palette_
uint8_t yaze::zelda3::Room::palette_ private
Definition at line 346 of file room.h.
Referenced by SetPaletteDirect().
floor1_graphics_
uint8_t yaze::zelda3::Room::floor1_graphics_ private
Definition at line 347 of file room.h.
Referenced by LoadObjects(), and RenderRoomGraphics().
floor2_graphics_
uint8_t yaze::zelda3::Room::floor2_graphics_ private
Definition at line 348 of file room.h.
Referenced by LoadObjects(), and RenderRoomGraphics().
layer2_mode_
uint8_t yaze::zelda3::Room::layer2_mode_ private
Definition at line 349 of file room.h.
Referenced by SetLayer2Mode().
blocks_
std::array<uint8_t, 16> yaze::zelda3::Room::blocks_ private
Definition at line 351 of file room.h.
Referenced by blocks(), CopyRoomGraphicsToBuffer(), LoadRoomGraphics(), and mutable_blocks().
chest_list_
std::array<chest, 16> yaze::zelda3::Room::chest_list_ private
Definition at line 352 of file room.h.
tile_objects_
std::vector<RoomObject> yaze::zelda3::Room::tile_objects_ private
Definition at line 354 of file room.h.
Referenced by AddTileObject(), ClearTileObjects(), GetTileObject(), GetTileObject(), GetTileObjectCount(), GetTileObjects(), GetTileObjects(), HandleSpecialObjects(), ParseObjectsFromLocation(), RemoveTileObject(), and SetTileObjects().
sprites_
std::vector<zelda3::Sprite> yaze::zelda3::Room::sprites_ private
Todo:
add separate door objects list when door section (F0 FF) is parsed
Definition at line 356 of file room.h.
Referenced by GetSprites(), GetSprites(), and LoadSprites().
z3_staircases_
std::vector<staircase> yaze::zelda3::Room::z3_staircases_ private
Definition at line 357 of file room.h.
Referenced by GetStairs(), GetStairs(), HandleSpecialObjects(), and ParseObjectsFromLocation().
chests_in_room_
std::vector<chest_data> yaze::zelda3::Room::chests_in_room_ private
Definition at line 358 of file room.h.
Referenced by GetChests(), GetChests(), HandleSpecialObjects(), and LoadChests().
layout_
RoomLayout yaze::zelda3::Room::layout_ private
Definition at line 361 of file room.h.
Referenced by GetLayout(), GetLayout(), and LoadRoomLayout().
layer_merging_
LayerMergeType yaze::zelda3::Room::layer_merging_ private
Definition at line 363 of file room.h.
Referenced by SetLayerMerging().
collision_
CollisionKey yaze::zelda3::Room::collision_ private
Definition at line 364 of file room.h.
Referenced by SetCollision().
effect_
EffectKey yaze::zelda3::Room::effect_ private
Definition at line 365 of file room.h.
Referenced by SetEffect().
tag1_
TagKey yaze::zelda3::Room::tag1_ private
Definition at line 366 of file room.h.
Referenced by SetTag1(), and SetTag1Direct().
tag2_
TagKey yaze::zelda3::Room::tag2_ private
Definition at line 367 of file room.h.
Referenced by SetTag2(), and SetTag2Direct().
bg2_
background2 yaze::zelda3::Room::bg2_ private
Definition at line 369 of file room.h.
Referenced by SetBg2().
pits_
destination yaze::zelda3::Room::pits_ private
Definition at line 370 of file room.h.
Referenced by SetPitsTarget(), and SetPitsTargetLayer().
stair1_
destination yaze::zelda3::Room::stair1_ private
Definition at line 371 of file room.h.
Referenced by SetStair1Target(), and SetStair1TargetLayer().
stair2_
destination yaze::zelda3::Room::stair2_ private
Definition at line 372 of file room.h.
Referenced by SetStair2Target(), and SetStair2TargetLayer().
stair3_
destination yaze::zelda3::Room::stair3_ private
Definition at line 373 of file room.h.
Referenced by SetStair3Target(), and SetStair3TargetLayer().
stair4_
destination yaze::zelda3::Room::stair4_ private
Definition at line 374 of file room.h.
Referenced by SetStair4Target(), and SetStair4TargetLayer().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/room.h
src/app/zelda3/dungeon/room.cc