yaze: yaze::app::RecentFilesManager Class Reference
yaze::app::RecentFilesManager Class Reference
#include <project.h>
Public Member Functions
RecentFilesManager ()
RecentFilesManager (const std::string &filename)
void AddFile (const std::string &file_path)
void Save ()
void Load ()
const std::vector< std::string > & GetRecentFiles () const
Private Attributes
std::string filename_
std::vector< std::string > recent_files_
Detailed Description
Definition at line 85 of file project.h.
Constructor & Destructor Documentation
RecentFilesManager() [1/2]
yaze::app::RecentFilesManager::RecentFilesManager () inline
Definition at line 87 of file project.h.
RecentFilesManager() [2/2]
yaze::app::RecentFilesManager::RecentFilesManager (const std::string & filename) inline
Definition at line 88 of file project.h.
Member Function Documentation
AddFile()
void yaze::app::RecentFilesManager::AddFile (const std::string & file_path) inline
Definition at line 90 of file project.h.
References recent_files_.
Referenced by yaze::app::editor::EditorManager::LoadRom(), and yaze::app::editor::EditorManager::OpenProject().
Save()
void yaze::app::RecentFilesManager::Save () inline
Definition at line 98 of file project.h.
References filename_, and recent_files_.
Referenced by yaze::app::editor::EditorManager::LoadRom(), and yaze::app::editor::EditorManager::OpenProject().
Load()
void yaze::app::RecentFilesManager::Load () inline
Definition at line 109 of file project.h.
References filename_, and recent_files_.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), yaze::app::editor::EditorManager::LoadRom(), yaze::app::editor::EditorManager::ManageKeyboardShortcuts(), and yaze::app::editor::EditorManager::OpenProject().
GetRecentFiles()
const std::vector< std::string > & yaze::app::RecentFilesManager::GetRecentFiles () const inline
Definition at line 124 of file project.h.
References recent_files_.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
Member Data Documentation
filename_
std::string yaze::app::RecentFilesManager::filename_ private
Definition at line 129 of file project.h.
Referenced by Load(), and Save().
recent_files_
std::vector<std::string> yaze::app::RecentFilesManager::recent_files_ private
Definition at line 130 of file project.h.
Referenced by AddFile(), GetRecentFiles(), Load(), and Save().
The documentation for this class was generated from the following file:
src/app/core/project.h