yaze: yaze::app::emu::Cpu Class Reference
yaze::app::emu::Cpu Class Reference
#include <cpu.h>
Public Types
enum class UpdateMode { Run , Step , Pause }
enum class AccessType { Control , Data }
Public Member Functions
Cpu (memory::Memory &mem, Clock &vclock, memory::CpuCallbacks &callbacks)
void Init (bool verbose=false)
void Reset (bool hard=false)
void Update (UpdateMode mode=UpdateMode::Run, int stepCount=1)
void RunOpcode ()
void ExecuteInstruction (uint8_t opcode)
void LogInstructions (uint16_t PC, uint8_t opcode, uint16_t operand, bool immediate, bool accumulator_mode)
void UpdatePC (uint8_t instruction_length)
void UpdateClock (int delta_time)
void SetIrq (bool state)
void Nmi ()
uint8_t GetInstructionLength (uint8_t opcode)
void DoInterrupt ()
void SetFlags (uint8_t val)
bool m ()
int GetAccumulatorSize () const
int GetIndexSize () const
void SetAccumulatorSize (bool set)
void SetIndexSize (bool set)
void SetNegativeFlag (bool set)
void SetOverflowFlag (bool set)
void SetBreakFlag (bool set)
void SetDecimalFlag (bool set)
void SetInterruptFlag (bool set)
void SetZeroFlag (bool set)
void SetCarryFlag (bool set)
bool GetNegativeFlag () const
bool GetOverflowFlag () const
bool GetBreakFlag () const
bool GetDecimalFlag () const
bool GetInterruptFlag () const
bool GetZeroFlag () const
bool GetCarryFlag () const
uint8_t ReadByte (uint32_t address) const
uint16_t ReadWord (uint32_t address) const
uint32_t ReadWordLong (uint32_t address) const
void WriteByte (uint32_t address, uint8_t value)
void WriteWord (uint32_t address, uint16_t value)
void WriteLong (uint32_t address, uint32_t value)
uint8_t FetchByte ()
uint16_t FetchWord ()
uint32_t FetchLong ()
int8_t FetchSignedByte ()
int16_t FetchSignedWord ()
uint8_t FetchByteDirectPage (uint8_t operand)
uint16_t ReadByteOrWord (uint32_t address)
void PushByte (uint8_t value)
void PushWord (uint16_t value, bool int_check=false)
void PushLong (uint32_t value)
uint8_t PopByte ()
uint16_t PopWord (bool int_check=false)
uint32_t PopLong ()
void DoBranch (bool check)
void AdrImp ()
uint32_t Absolute (AccessType access_type=AccessType::Data)
uint32_t AbsoluteIndexedX ()
uint32_t AbsoluteIndexedY ()
uint16_t AbsoluteIndexedIndirect ()
uint16_t AbsoluteIndirect ()
uint32_t AbsoluteIndirectLong ()
uint32_t AbsoluteLong ()
uint32_t AbsoluteLongIndexedX ()
void BlockMove (uint16_t source, uint16_t dest, uint16_t length)
uint16_t DirectPage ()
uint16_t DirectPageIndexedX ()
uint16_t DirectPageIndexedY ()
uint16_t DirectPageIndexedIndirectX ()
uint16_t DirectPageIndirect ()
uint32_t DirectPageIndirectLong ()
uint16_t DirectPageIndirectIndexedY ()
uint32_t DirectPageIndirectLongIndexedY ()
uint16_t Immediate (bool index_size=false)
uint16_t StackRelative ()
uint32_t StackRelativeIndirectIndexedY ()
void ADC (uint16_t operand)
void AND (uint32_t address, bool immediate=false)
void ANDAbsoluteLong (uint32_t address)
void ASL (uint16_t address)
void BCC (int8_t offset)
void BCS (int8_t offset)
void BEQ (int8_t offset)
void BIT (uint16_t address)
void BMI (int8_t offset)
void BNE (int8_t offset)
void BPL (int8_t offset)
void BRA (int8_t offset)
void BRK ()
void BRL (int16_t offset)
void BVC (int8_t offset)
void BVS (int8_t offset)
void CLC ()
void CLD ()
void CLI ()
void CLV ()
void CMP (uint32_t address, bool immediate=false)
void COP ()
void CPX (uint32_t address, bool immediate=false)
void CPY (uint32_t address, bool immediate=false)
void DEC (uint32_t address, bool accumulator=false)
void DEX ()
void DEY ()
void EOR (uint32_t address, bool immediate=false)
void INC (uint32_t address, bool accumulator=false)
void INX ()
void INY ()
void JMP (uint16_t address)
void JML (uint16_t address)
void JSR (uint16_t address)
void JSL (uint16_t address)
void LDA (uint16_t address, bool immediate=false, bool direct_page=false, bool data_bank=false)
void LDX (uint16_t address, bool immediate=false)
void LDY (uint16_t address, bool immediate=false)
void LSR (uint16_t address, bool accumulator=false)
void MVN ()
void MVP ()
void NOP ()
void ORA (uint16_t address, bool immediate=false)
void PEA ()
void PEI ()
void PER ()
void PHA ()
void PHB ()
void PHD ()
void PHK ()
void PHP ()
void PHX ()
void PHY ()
void PLA ()
void PLB ()
void PLD ()
void PLP ()
void PLX ()
void PLY ()
void REP ()
void ROL (uint32_t address, bool accumulator=false)
void ROR (uint32_t address, bool accumulator=false)
void RTI ()
void RTL ()
void RTS ()
void SBC (uint32_t operand, bool immediate=false)
void SEC ()
void SED ()
void SEI ()
void SEP ()
void STA (uint32_t address)
void STP ()
void STX (uint16_t address)
void STY (uint16_t address)
void STZ (uint16_t address)
void TAX ()
void TAY ()
void TCD ()
void TCS ()
void TDC ()
void TRB (uint16_t address)
void TSB (uint16_t address)
void TSC ()
void TSX ()
void TXA ()
void TXS ()
void TXY ()
void TYA ()
void TYX ()
void WAI ()
void WDM ()
void XBA ()
void XCE ()
uint16_t SP () const
void SetSP (uint16_t value)
void set_next_pc (uint16_t value)
bool IsBreakpoint (uint32_t address)
void SetBreakpoint (uint32_t address)
void ClearBreakpoint (uint32_t address)
void ClearBreakpoints ()
auto GetBreakpoints ()
void CheckInt ()
auto mutable_log_instructions () -> bool *
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
Public Attributes
std::vector< uint32_t > breakpoints_
std::vector< InstructionEntry > instruction_log_
uint16_t A = 0
uint16_t X = 0
uint16_t Y = 0
uint16_t D = 0
uint8_t DB = 0
uint8_t PB = 0
uint16_t PC = 0
uint8_t E = 1
uint8_t status = 0b00110000
Private Member Functions
void compare (uint16_t register_value, uint16_t memory_value)
void SetFlag (uint8_t mask, bool set)
bool GetFlag (uint8_t mask) const
Private Attributes
bool log_instructions_ = false
bool waiting_ = false
bool stopped_ = false
bool irq_wanted_ = false
bool nmi_wanted_ = false
bool reset_wanted_ = false
bool int_wanted_ = false
uint16_t last_call_frame_
uint16_t next_pc_
uint8_t next_pb_
memory::CpuCallbacks callbacks_
memory::Memory & memory
Clock & clock
Additional Inherited Members
Protected Member Functions inherited from yaze::app::emu::Loggable
virtual ~Loggable ()=default
virtual void LogMessage (const std::string &message)
Protected Attributes inherited from yaze::app::emu::Loggable
Logger & logger_ = Logger::GetInstance()
Member Enumeration Documentation
UpdateMode
enum class yaze::app::emu::Cpu::UpdateMode strong
Enumerator
Run
Step
Pause
AccessType
enum class yaze::app::emu::Cpu::AccessType strong
Enumerator
Control
Data
Constructor & Destructor Documentation
Cpu()
yaze::app::emu::Cpu::Cpu (memory::Memory & mem, Clock & vclock, memory::CpuCallbacks & callbacks) inline explicit
Member Function Documentation
Init()
void yaze::app::emu::Cpu::Init (bool verbose = false) inline
References clock, yaze::app::emu::kCpuClockSpeed, and yaze::app::emu::Clock::SetFrequency().
Referenced by yaze::app::emu::SNES::Init().
Reset()
void yaze::app::emu::Cpu::Reset (bool hard = false)
References A, D, DB, E, int_wanted_, irq_wanted_, nmi_wanted_, PB, PC, reset_wanted_, status, stopped_, waiting_, X, and Y.
Referenced by yaze::app::emu::SNES::Reset().
Update()
void yaze::app::emu::Cpu::Update (UpdateMode mode = UpdateMode::Run, int stepCount = 1)
References clock, ExecuteInstruction(), yaze::app::emu::Clock::GetCycleCount(), IsBreakpoint(), PB, PC, ReadByte(), Run, and Step.
RunOpcode()
void yaze::app::emu::Cpu::RunOpcode ()
References callbacks_, CheckInt(), DoInterrupt(), E, ExecuteInstruction(), yaze::app::emu::memory::CpuCallbacks::idle, int_wanted_, irq_wanted_, nmi_wanted_, PB, PC, ReadByte(), ReadWord(), reset_wanted_, SetDecimalFlag(), SetFlags(), SetInterruptFlag(), SetSP(), SP(), status, stopped_, and waiting_.
Referenced by yaze::app::emu::SNES::RunFrame().
ExecuteInstruction()
void yaze::app::emu::Cpu::ExecuteInstruction (uint8_t opcode)
References A, Absolute(), AbsoluteIndexedIndirect(), AbsoluteIndexedX(), AbsoluteIndexedY(), AbsoluteIndirect(), AbsoluteIndirectLong(), AbsoluteLong(), AbsoluteLongIndexedX(), ADC(), AND(), ANDAbsoluteLong(), ASL(), BIT(), BRK(), BRL(), CLC(), CLD(), CLI(), CLV(), CMP(), Control, COP(), CPX(), CPY(), Data, DEC(), DEX(), DEY(), DirectPage(), DirectPageIndexedIndirectX(), DirectPageIndexedX(), DirectPageIndexedY(), DirectPageIndirect(), DirectPageIndirectIndexedY(), DirectPageIndirectLong(), DirectPageIndirectLongIndexedY(), DoBranch(), EOR(), FetchByte(), FetchWord(), GetAccumulatorSize(), GetCarryFlag(), GetInstructionLength(), GetNegativeFlag(), GetOverflowFlag(), GetZeroFlag(), Immediate(), INC(), INX(), INY(), JML(), JMP(), JSL(), JSR(), LDA(), LDX(), LDY(), log_instructions_, LogInstructions(), LSR(), MVN(), MVP(), NOP(), ORA(), PB, PC, PEA(), PEI(), PER(), PHA(), PHB(), PHD(), PHK(), PHP(), PHX(), PHY(), PLA(), PLB(), PLD(), PLP(), PLX(), PLY(), ReadByte(), ReadByteOrWord(), ReadWord(), REP(), ROL(), ROR(), RTI(), RTL(), RTS(), SBC(), SEC(), SED(), SEI(), SEP(), SetCarryFlag(), SetNegativeFlag(), SetZeroFlag(), STA(), StackRelative(), StackRelativeIndirectIndexedY(), STP(), STX(), STY(), STZ(), TAX(), TAY(), TCD(), TCS(), TDC(), TRB(), TSB(), TSC(), TSX(), TXA(), TXS(), TXY(), TYA(), TYX(), UpdatePC(), WAI(), WDM(), XBA(), and XCE().
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject(), RunOpcode(), and Update().
LogInstructions()
void yaze::app::emu::Cpu::LogInstructions (uint16_t PC, uint8_t opcode, uint16_t operand, bool immediate, bool accumulator_mode)
References A, D, DB, yaze::app::core::ExperimentFlags::flags(), instruction_log_, opcode_to_mnemonic, PB, PC, SP(), status, X, and Y.
Referenced by ExecuteInstruction().
UpdatePC()
void yaze::app::emu::Cpu::UpdatePC (uint8_t instruction_length) inline
References PC.
Referenced by ExecuteInstruction().
UpdateClock()
void yaze::app::emu::Cpu::UpdateClock (int delta_time) inline
References clock, and yaze::app::emu::Clock::UpdateClock().
SetIrq()
void yaze::app::emu::Cpu::SetIrq (bool state) inline
References irq_wanted_.
Referenced by yaze::app::emu::SNES::ReadReg(), yaze::app::emu::SNES::RunCycle(), and yaze::app::emu::SNES::WriteReg().
Nmi()
void yaze::app::emu::Cpu::Nmi () inline
References nmi_wanted_.
Referenced by yaze::app::emu::SNES::RunCycle(), and yaze::app::emu::SNES::WriteReg().
GetInstructionLength()
uint8_t yaze::app::emu::Cpu::GetInstructionLength (uint8_t opcode)
References GetAccumulatorSize(), GetCarryFlag(), GetIndexSize(), GetNegativeFlag(), GetOverflowFlag(), GetZeroFlag(), last_call_frame_, next_pb_, next_pc_, opcode_to_mnemonic, PB, and PC.
Referenced by ExecuteInstruction().
DoInterrupt()
void yaze::app::emu::Cpu::DoInterrupt ()
References callbacks_, yaze::app::emu::memory::CpuCallbacks::idle, int_wanted_, nmi_wanted_, PB, PC, PushByte(), PushWord(), ReadWord(), SetDecimalFlag(), SetInterruptFlag(), and status.
Referenced by RunOpcode().
SetFlags()
void yaze::app::emu::Cpu::SetFlags (uint8_t val) inline
References E, status, X, and Y.
Referenced by RunOpcode().
m()
bool yaze::app::emu::Cpu::m () inline
References GetAccumulatorSize().
GetAccumulatorSize()
int yaze::app::emu::Cpu::GetAccumulatorSize () const inline
References status.
Referenced by ADC(), AND(), ASL(), CMP(), DEC(), DirectPageIndexedX(), DirectPageIndirectLongIndexedY(), EOR(), ExecuteInstruction(), GetInstructionLength(), Immediate(), INC(), LDA(), LSR(), m(), ORA(), PHA(), PLA(), ReadByteOrWord(), ROL(), ROR(), SBC(), STA(), STZ(), TRB(), TSB(), TXA(), and TYA().
GetIndexSize()
int yaze::app::emu::Cpu::GetIndexSize () const inline
References status.
Referenced by compare(), CPX(), CPY(), DEX(), DEY(), GetInstructionLength(), Immediate(), INX(), INY(), LDX(), LDY(), MVN(), MVP(), PHX(), PHY(), PLX(), PLY(), STX(), STY(), TAX(), TAY(), TSX(), TXY(), and TYX().
SetAccumulatorSize()
void yaze::app::emu::Cpu::SetAccumulatorSize (bool set) inline
References SetFlag().
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::ConfigureObject().
SetIndexSize()
void yaze::app::emu::Cpu::SetIndexSize (bool set) inline
References SetFlag().
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::ConfigureObject().
SetNegativeFlag()
void yaze::app::emu::Cpu::SetNegativeFlag (bool set) inline
References SetFlag().
Referenced by ADC(), AND(), ANDAbsoluteLong(), ASL(), BIT(), CMP(), compare(), DEC(), DEX(), DEY(), EOR(), ExecuteInstruction(), INC(), INX(), INY(), LDA(), LDX(), LDY(), LSR(), ORA(), PLA(), PLB(), PLD(), PLX(), PLY(), ROL(), ROR(), SBC(), TAX(), TAY(), TCD(), TDC(), TSC(), TSX(), TXA(), TXY(), TYA(), TYX(), and XBA().
SetOverflowFlag()
void yaze::app::emu::Cpu::SetOverflowFlag (bool set) inline
References SetFlag().
Referenced by ADC(), BIT(), and SBC().
SetBreakFlag()
void yaze::app::emu::Cpu::SetBreakFlag (bool set) inline
References SetFlag().
SetDecimalFlag()
void yaze::app::emu::Cpu::SetDecimalFlag (bool set) inline
References SetFlag().
Referenced by BRK(), COP(), DoInterrupt(), and RunOpcode().
SetInterruptFlag()
void yaze::app::emu::Cpu::SetInterruptFlag (bool set) inline
References SetFlag().
Referenced by BRK(), COP(), DoInterrupt(), and RunOpcode().
SetZeroFlag()
void yaze::app::emu::Cpu::SetZeroFlag (bool set) inline
References SetFlag().
Referenced by ADC(), AND(), ANDAbsoluteLong(), ASL(), BIT(), CMP(), compare(), DEC(), DEX(), DEY(), EOR(), ExecuteInstruction(), INC(), INX(), INY(), LDA(), LDX(), LDY(), LSR(), ORA(), PLA(), PLB(), PLD(), PLX(), PLY(), ROL(), ROR(), SBC(), TAX(), TAY(), TCD(), TDC(), TRB(), TSB(), TSC(), TSX(), TXA(), TXY(), TYA(), TYX(), and XBA().
SetCarryFlag()
void yaze::app::emu::Cpu::SetCarryFlag (bool set) inline
References SetFlag().
Referenced by ADC(), ASL(), CMP(), compare(), ExecuteInstruction(), LSR(), ROL(), ROR(), and SBC().
GetNegativeFlag()
bool yaze::app::emu::Cpu::GetNegativeFlag () const inline
References GetFlag().
Referenced by BMI(), BPL(), ExecuteInstruction(), and GetInstructionLength().
GetOverflowFlag()
bool yaze::app::emu::Cpu::GetOverflowFlag () const inline
References GetFlag().
Referenced by BVC(), BVS(), ExecuteInstruction(), and GetInstructionLength().
GetBreakFlag()
bool yaze::app::emu::Cpu::GetBreakFlag () const inline
References GetFlag().
GetDecimalFlag()
bool yaze::app::emu::Cpu::GetDecimalFlag () const inline
References GetFlag().
GetInterruptFlag()
bool yaze::app::emu::Cpu::GetInterruptFlag () const inline
References GetFlag().
Referenced by CheckInt().
GetZeroFlag()
bool yaze::app::emu::Cpu::GetZeroFlag () const inline
References GetFlag().
Referenced by BEQ(), BNE(), ExecuteInstruction(), and GetInstructionLength().
GetCarryFlag()
bool yaze::app::emu::Cpu::GetCarryFlag () const inline
References GetFlag().
Referenced by ADC(), BCC(), BCS(), ExecuteInstruction(), GetInstructionLength(), ROL(), ROR(), and SBC().
ReadByte()
uint8_t yaze::app::emu::Cpu::ReadByte (uint32_t address) const inline
References callbacks_, and yaze::app::emu::memory::CpuCallbacks::read_byte.
Referenced by AdrImp(), AND(), ASL(), BIT(), BlockMove(), BRK(), CMP(), CPX(), CPY(), DEC(), EOR(), ExecuteInstruction(), FetchByte(), FetchByteDirectPage(), Immediate(), INC(), JML(), JSL(), LDA(), LDX(), LDY(), LSR(), MVN(), MVP(), ORA(), PopByte(), ReadByteOrWord(), ReadWord(), ReadWordLong(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject(), ROL(), ROR(), RunOpcode(), SBC(), TRB(), TSB(), Update(), and WDM().
ReadWord()
uint16_t yaze::app::emu::Cpu::ReadWord (uint32_t address) const inline
References ReadByte().
Referenced by AbsoluteIndexedIndirect(), AbsoluteIndexedX(), AbsoluteIndexedY(), AbsoluteIndirect(), AND(), ASL(), BRK(), CMP(), COP(), CPX(), CPY(), DEC(), DirectPageIndexedIndirectX(), DirectPageIndirect(), DirectPageIndirectIndexedY(), DoInterrupt(), EOR(), ExecuteInstruction(), FetchWord(), Immediate(), INC(), LDA(), LDX(), LDY(), LSR(), ORA(), PEI(), ReadByteOrWord(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject(), ROL(), ROR(), RunOpcode(), SBC(), StackRelativeIndirectIndexedY(), TRB(), and TSB().
ReadWordLong()
uint32_t yaze::app::emu::Cpu::ReadWordLong (uint32_t address) const inline
References ReadByte().
Referenced by AbsoluteIndirectLong(), ANDAbsoluteLong(), DirectPageIndirectLong(), DirectPageIndirectLongIndexedY(), and FetchLong().
WriteByte()
void yaze::app::emu::Cpu::WriteByte (uint32_t address, uint8_t value) inline
References callbacks_, and yaze::app::emu::memory::CpuCallbacks::write_byte.
Referenced by ASL(), BlockMove(), DEC(), INC(), LSR(), MVN(), MVP(), PushByte(), ROL(), ROR(), STA(), STX(), STY(), STZ(), TRB(), TSB(), WriteLong(), and WriteWord().
WriteWord()
void yaze::app::emu::Cpu::WriteWord (uint32_t address, uint16_t value) inline
References WriteByte().
Referenced by ASL(), DEC(), INC(), LSR(), ROL(), ROR(), STA(), STX(), STY(), STZ(), TRB(), and TSB().
WriteLong()
void yaze::app::emu::Cpu::WriteLong (uint32_t address, uint32_t value) inline
References WriteByte().
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::ConfigureObject().
FetchByte()
uint8_t yaze::app::emu::Cpu::FetchByte () inline
References PB, PC, and ReadByte().
Referenced by DirectPage(), DirectPageIndexedIndirectX(), DirectPageIndexedX(), DirectPageIndexedY(), DirectPageIndirect(), DirectPageIndirectIndexedY(), DirectPageIndirectLong(), DirectPageIndirectLongIndexedY(), DoBranch(), ExecuteInstruction(), FetchSignedByte(), REP(), SEP(), StackRelative(), and StackRelativeIndirectIndexedY().
FetchWord()
uint16_t yaze::app::emu::Cpu::FetchWord () inline
References PB, PC, and ReadWord().
Referenced by Absolute(), AbsoluteIndexedIndirect(), AbsoluteIndirect(), AbsoluteIndirectLong(), ExecuteInstruction(), FetchSignedWord(), PEA(), PEI(), and PER().
FetchLong()
uint32_t yaze::app::emu::Cpu::FetchLong () inline
References PB, PC, and ReadWordLong().
Referenced by AbsoluteLong(), and AbsoluteLongIndexedX().
FetchSignedByte()
int8_t yaze::app::emu::Cpu::FetchSignedByte () inline
References FetchByte().
FetchSignedWord()
int16_t yaze::app::emu::Cpu::FetchSignedWord () inline
References FetchWord().
FetchByteDirectPage()
uint8_t yaze::app::emu::Cpu::FetchByteDirectPage (uint8_t operand) inline
References D, next_pc_, PC, and ReadByte().
ReadByteOrWord()
uint16_t yaze::app::emu::Cpu::ReadByteOrWord (uint32_t address) inline
References GetAccumulatorSize(), ReadByte(), and ReadWord().
Referenced by ExecuteInstruction().
PushByte()
void yaze::app::emu::Cpu::PushByte (uint8_t value) inline
References E, SetSP(), SP(), and WriteByte().
Referenced by BRK(), COP(), DoInterrupt(), JSL(), PHA(), PHB(), PHK(), PHP(), PHX(), PHY(), PushLong(), and PushWord().
PushWord()
void yaze::app::emu::Cpu::PushWord (uint16_t value, bool int_check = false) inline
References CheckInt(), and PushByte().
Referenced by COP(), DoInterrupt(), JSL(), JSR(), PEA(), PEI(), PER(), PHA(), PHD(), PHX(), PHY(), and PushLong().
PushLong()
void yaze::app::emu::Cpu::PushLong (uint32_t value) inline
References PushByte(), and PushWord().
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject().
PopByte()
uint8_t yaze::app::emu::Cpu::PopByte () inline
References E, ReadByte(), SetSP(), and SP().
Referenced by PLA(), PLB(), PLP(), PLX(), PLY(), PopLong(), PopWord(), RTI(), and RTL().
PopWord()
uint16_t yaze::app::emu::Cpu::PopWord (bool int_check = false) inline
References CheckInt(), and PopByte().
Referenced by PLA(), PLD(), PLX(), PLY(), PopLong(), RTI(), RTL(), and RTS().
PopLong()
uint32_t yaze::app::emu::Cpu::PopLong () inline
References PopByte(), and PopWord().
DoBranch()
void yaze::app::emu::Cpu::DoBranch (bool check) inline
References callbacks_, CheckInt(), FetchByte(), yaze::app::emu::memory::CpuCallbacks::idle, and next_pc_.
Referenced by ExecuteInstruction().
AdrImp()
void yaze::app::emu::Cpu::AdrImp ()
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, int_wanted_, PB, PC, and ReadByte().
Referenced by CLC(), CLD(), CLI(), CLV(), DEC(), DEX(), DEY(), INC(), INX(), INY(), LSR(), NOP(), ROL(), ROR(), SEC(), SED(), SEI(), TAX(), TAY(), TCD(), TCS(), TDC(), TSC(), TSX(), TXA(), TXS(), TXY(), TYA(), TYX(), and XCE().
Absolute()
uint32_t yaze::app::emu::Cpu::Absolute (Cpu::AccessType access_type = AccessType::Data)
References Data, DB, FetchWord(), and PB.
Referenced by ExecuteInstruction().
AbsoluteIndexedX()
uint32_t yaze::app::emu::Cpu::AbsoluteIndexedX ()
References DB, PB, PC, ReadWord(), and X.
Referenced by ExecuteInstruction().
AbsoluteIndexedY()
uint32_t yaze::app::emu::Cpu::AbsoluteIndexedY ()
References DB, PB, PC, ReadWord(), and Y.
Referenced by ExecuteInstruction().
AbsoluteIndexedIndirect()
uint16_t yaze::app::emu::Cpu::AbsoluteIndexedIndirect ()
References callbacks_, DB, FetchWord(), yaze::app::emu::memory::CpuCallbacks::idle, ReadWord(), and X.
Referenced by ExecuteInstruction().
AbsoluteIndirect()
uint16_t yaze::app::emu::Cpu::AbsoluteIndirect ()
References FetchWord(), PB, and ReadWord().
Referenced by ExecuteInstruction().
AbsoluteIndirectLong()
uint32_t yaze::app::emu::Cpu::AbsoluteIndirectLong ()
References FetchWord(), PB, and ReadWordLong().
Referenced by ExecuteInstruction().
AbsoluteLong()
uint32_t yaze::app::emu::Cpu::AbsoluteLong ()
References FetchLong().
Referenced by ExecuteInstruction().
AbsoluteLongIndexedX()
uint32_t yaze::app::emu::Cpu::AbsoluteLongIndexedX ()
References FetchLong(), and X.
Referenced by ExecuteInstruction().
BlockMove()
void yaze::app::emu::Cpu::BlockMove (uint16_t source, uint16_t dest, uint16_t length)
References ReadByte(), and WriteByte().
DirectPage()
uint16_t yaze::app::emu::Cpu::DirectPage ()
References D, and FetchByte().
Referenced by ExecuteInstruction().
DirectPageIndexedX()
uint16_t yaze::app::emu::Cpu::DirectPageIndexedX ()
References D, FetchByte(), GetAccumulatorSize(), and X.
Referenced by ExecuteInstruction().
DirectPageIndexedY()
uint16_t yaze::app::emu::Cpu::DirectPageIndexedY ()
References FetchByte(), and Y.
Referenced by ExecuteInstruction().
DirectPageIndexedIndirectX()
uint16_t yaze::app::emu::Cpu::DirectPageIndexedIndirectX ()
References callbacks_, D, FetchByte(), yaze::app::emu::memory::CpuCallbacks::idle, ReadWord(), and X.
Referenced by ExecuteInstruction().
DirectPageIndirect()
uint16_t yaze::app::emu::Cpu::DirectPageIndirect ()
References D, FetchByte(), and ReadWord().
Referenced by ExecuteInstruction().
DirectPageIndirectLong()
uint32_t yaze::app::emu::Cpu::DirectPageIndirectLong ()
References D, FetchByte(), and ReadWordLong().
Referenced by ExecuteInstruction().
DirectPageIndirectIndexedY()
uint16_t yaze::app::emu::Cpu::DirectPageIndirectIndexedY ()
References D, FetchByte(), ReadWord(), and Y.
Referenced by ExecuteInstruction().
DirectPageIndirectLongIndexedY()
uint32_t yaze::app::emu::Cpu::DirectPageIndirectLongIndexedY ()
References D, FetchByte(), GetAccumulatorSize(), ReadWordLong(), and Y.
Referenced by ExecuteInstruction().
Immediate()
uint16_t yaze::app::emu::Cpu::Immediate (bool index_size = false)
References GetAccumulatorSize(), GetIndexSize(), PB, PC, ReadByte(), and ReadWord().
Referenced by ExecuteInstruction().
StackRelative()
uint16_t yaze::app::emu::Cpu::StackRelative ()
References FetchByte(), and SP().
Referenced by ExecuteInstruction().
StackRelativeIndirectIndexedY()
uint32_t yaze::app::emu::Cpu::StackRelativeIndirectIndexedY ()
References DB, FetchByte(), ReadWord(), SP(), and Y.
Referenced by ExecuteInstruction().
ADC()
void yaze::app::emu::Cpu::ADC (uint16_t operand)
65816 Instruction Set
References A, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), SetCarryFlag(), SetNegativeFlag(), SetOverflowFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
AND()
void yaze::app::emu::Cpu::AND (uint32_t address, bool immediate = false)
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
ANDAbsoluteLong()
void yaze::app::emu::Cpu::ANDAbsoluteLong (uint32_t address)
References A, ReadWordLong(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
ASL()
void yaze::app::emu::Cpu::ASL (uint16_t address)
References callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetNegativeFlag(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
BCC()
void yaze::app::emu::Cpu::BCC (int8_t offset)
References GetCarryFlag(), and next_pc_.
BCS()
void yaze::app::emu::Cpu::BCS (int8_t offset)
References GetCarryFlag(), and next_pc_.
BEQ()
void yaze::app::emu::Cpu::BEQ (int8_t offset)
References GetZeroFlag(), and next_pc_.
BIT()
void yaze::app::emu::Cpu::BIT (uint16_t address)
References A, CheckInt(), ReadByte(), SetNegativeFlag(), SetOverflowFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
BMI()
void yaze::app::emu::Cpu::BMI (int8_t offset)
References GetNegativeFlag(), next_pc_, and PC.
BNE()
void yaze::app::emu::Cpu::BNE (int8_t offset)
References GetZeroFlag(), next_pc_, and PC.
BPL()
void yaze::app::emu::Cpu::BPL (int8_t offset)
References GetNegativeFlag(), next_pc_, and PC.
BRA()
void yaze::app::emu::Cpu::BRA (int8_t offset)
References next_pc_, and PC.
BRK()
void yaze::app::emu::Cpu::BRK ()
References next_pb_, next_pc_, PB, PC, PushByte(), ReadByte(), ReadWord(), SetDecimalFlag(), SetInterruptFlag(), and status.
Referenced by ExecuteInstruction().
BRL()
void yaze::app::emu::Cpu::BRL (int16_t offset)
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, next_pc_, and PC.
Referenced by ExecuteInstruction().
BVC()
void yaze::app::emu::Cpu::BVC (int8_t offset)
References GetOverflowFlag(), and next_pc_.
BVS()
void yaze::app::emu::Cpu::BVS (int8_t offset)
References GetOverflowFlag(), and next_pc_.
CLC()
void yaze::app::emu::Cpu::CLC ()
References AdrImp(), and status.
Referenced by ExecuteInstruction().
CLD()
void yaze::app::emu::Cpu::CLD ()
References AdrImp(), and status.
Referenced by ExecuteInstruction().
CLI()
void yaze::app::emu::Cpu::CLI ()
References AdrImp(), and status.
Referenced by ExecuteInstruction().
CLV()
void yaze::app::emu::Cpu::CLV ()
References AdrImp(), and status.
Referenced by ExecuteInstruction().
CMP()
void yaze::app::emu::Cpu::CMP (uint32_t address, bool immediate = false)
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), SetCarryFlag(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
COP()
void yaze::app::emu::Cpu::COP ()
References E, next_pb_, next_pc_, PC, PushByte(), PushWord(), ReadWord(), SetDecimalFlag(), SetInterruptFlag(), and status.
Referenced by ExecuteInstruction().
CPX()
void yaze::app::emu::Cpu::CPX (uint32_t address, bool immediate = false)
References CheckInt(), compare(), GetIndexSize(), ReadByte(), ReadWord(), and X.
Referenced by ExecuteInstruction().
CPY()
void yaze::app::emu::Cpu::CPY (uint32_t address, bool immediate = false)
References CheckInt(), compare(), GetIndexSize(), ReadByte(), ReadWord(), and Y.
Referenced by ExecuteInstruction().
DEC()
void yaze::app::emu::Cpu::DEC (uint32_t address, bool accumulator = false)
References A, AdrImp(), callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetNegativeFlag(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
DEX()
void yaze::app::emu::Cpu::DEX ()
References AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), and X.
Referenced by ExecuteInstruction().
DEY()
void yaze::app::emu::Cpu::DEY ()
References AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), and Y.
Referenced by ExecuteInstruction().
EOR()
void yaze::app::emu::Cpu::EOR (uint32_t address, bool immediate = false)
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
INC()
void yaze::app::emu::Cpu::INC (uint32_t address, bool accumulator = false)
References A, AdrImp(), callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetNegativeFlag(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
INX()
void yaze::app::emu::Cpu::INX ()
References AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), and X.
Referenced by ExecuteInstruction().
INY()
void yaze::app::emu::Cpu::INY ()
References AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), and Y.
Referenced by ExecuteInstruction().
JMP()
void yaze::app::emu::Cpu::JMP (uint16_t address)
References next_pc_.
Referenced by ExecuteInstruction().
JML()
void yaze::app::emu::Cpu::JML (uint16_t address)
References CheckInt(), next_pb_, next_pc_, PC, and ReadByte().
Referenced by ExecuteInstruction().
JSR()
void yaze::app::emu::Cpu::JSR (uint16_t address)
References callbacks_, yaze::app::emu::memory::CpuCallbacks::idle, next_pc_, PC, and PushWord().
Referenced by ExecuteInstruction().
JSL()
void yaze::app::emu::Cpu::JSL (uint16_t address)
References callbacks_, yaze::app::emu::memory::CpuCallbacks::idle, next_pb_, next_pc_, PB, PC, PushByte(), PushWord(), and ReadByte().
Referenced by ExecuteInstruction().
LDA()
void yaze::app::emu::Cpu::LDA (uint16_t address, bool immediate = false, bool direct_page = false, bool data_bank = false)
References A, CheckInt(), GetAccumulatorSize(), PB, ReadByte(), ReadWord(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
LDX()
void yaze::app::emu::Cpu::LDX (uint16_t address, bool immediate = false)
References CheckInt(), GetIndexSize(), ReadByte(), ReadWord(), SetNegativeFlag(), SetZeroFlag(), and X.
Referenced by ExecuteInstruction().
LDY()
void yaze::app::emu::Cpu::LDY (uint16_t address, bool immediate = false)
References CheckInt(), GetIndexSize(), ReadByte(), ReadWord(), SetNegativeFlag(), SetZeroFlag(), and Y.
Referenced by ExecuteInstruction().
LSR()
void yaze::app::emu::Cpu::LSR (uint16_t address, bool accumulator = false)
References A, AdrImp(), callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetNegativeFlag(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
MVN()
void yaze::app::emu::Cpu::MVN ()
References A, callbacks_, CheckInt(), DB, GetIndexSize(), yaze::app::emu::memory::CpuCallbacks::idle, next_pc_, PC, ReadByte(), WriteByte(), X, and Y.
Referenced by ExecuteInstruction().
MVP()
void yaze::app::emu::Cpu::MVP ()
References A, callbacks_, CheckInt(), DB, GetIndexSize(), yaze::app::emu::memory::CpuCallbacks::idle, next_pc_, PC, ReadByte(), WriteByte(), X, and Y.
Referenced by ExecuteInstruction().
NOP()
void yaze::app::emu::Cpu::NOP ()
References AdrImp().
Referenced by ExecuteInstruction().
ORA()
void yaze::app::emu::Cpu::ORA (uint16_t address, bool immediate = false)
References A, CheckInt(), GetAccumulatorSize(), ReadByte(), ReadWord(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
PEA()
void yaze::app::emu::Cpu::PEA ()
References FetchWord(), and PushWord().
Referenced by ExecuteInstruction().
PEI()
void yaze::app::emu::Cpu::PEI ()
References FetchWord(), PushWord(), and ReadWord().
Referenced by ExecuteInstruction().
PER()
void yaze::app::emu::Cpu::PER ()
References callbacks_, FetchWord(), yaze::app::emu::memory::CpuCallbacks::idle, PC, and PushWord().
Referenced by ExecuteInstruction().
PHA()
void yaze::app::emu::Cpu::PHA ()
References A, callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, PushByte(), and PushWord().
Referenced by ExecuteInstruction().
PHB()
void yaze::app::emu::Cpu::PHB ()
References callbacks_, CheckInt(), DB, yaze::app::emu::memory::CpuCallbacks::idle, and PushByte().
Referenced by ExecuteInstruction().
PHD()
void yaze::app::emu::Cpu::PHD ()
References callbacks_, D, yaze::app::emu::memory::CpuCallbacks::idle, and PushWord().
Referenced by ExecuteInstruction().
PHK()
void yaze::app::emu::Cpu::PHK ()
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, PB, and PushByte().
Referenced by ExecuteInstruction().
PHP()
void yaze::app::emu::Cpu::PHP ()
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, PushByte(), and status.
Referenced by ExecuteInstruction().
PHX()
void yaze::app::emu::Cpu::PHX ()
References callbacks_, CheckInt(), GetIndexSize(), yaze::app::emu::memory::CpuCallbacks::idle, PushByte(), PushWord(), and X.
Referenced by ExecuteInstruction().
PHY()
void yaze::app::emu::Cpu::PHY ()
References callbacks_, CheckInt(), GetIndexSize(), yaze::app::emu::memory::CpuCallbacks::idle, PushByte(), PushWord(), and Y.
Referenced by ExecuteInstruction().
PLA()
void yaze::app::emu::Cpu::PLA ()
References A, callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, PopByte(), PopWord(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
PLB()
void yaze::app::emu::Cpu::PLB ()
References callbacks_, CheckInt(), DB, yaze::app::emu::memory::CpuCallbacks::idle, PopByte(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
PLD()
void yaze::app::emu::Cpu::PLD ()
References callbacks_, D, yaze::app::emu::memory::CpuCallbacks::idle, PopWord(), SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
PLP()
void yaze::app::emu::Cpu::PLP ()
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, PopByte(), and status.
Referenced by ExecuteInstruction().
PLX()
void yaze::app::emu::Cpu::PLX ()
References A, callbacks_, CheckInt(), GetIndexSize(), yaze::app::emu::memory::CpuCallbacks::idle, PopByte(), PopWord(), SetNegativeFlag(), SetZeroFlag(), and X.
Referenced by ExecuteInstruction().
PLY()
void yaze::app::emu::Cpu::PLY ()
References A, callbacks_, CheckInt(), GetIndexSize(), yaze::app::emu::memory::CpuCallbacks::idle, PopByte(), PopWord(), SetNegativeFlag(), SetZeroFlag(), and Y.
Referenced by ExecuteInstruction().
REP()
void yaze::app::emu::Cpu::REP ()
References callbacks_, CheckInt(), FetchByte(), yaze::app::emu::memory::CpuCallbacks::idle, and status.
Referenced by ExecuteInstruction().
ROL()
void yaze::app::emu::Cpu::ROL (uint32_t address, bool accumulator = false)
References A, AdrImp(), callbacks_, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetNegativeFlag(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
ROR()
void yaze::app::emu::Cpu::ROR (uint32_t address, bool accumulator = false)
References A, AdrImp(), callbacks_, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetCarryFlag(), SetNegativeFlag(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
RTI()
void yaze::app::emu::Cpu::RTI ()
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, next_pb_, next_pc_, PopByte(), PopWord(), and status.
Referenced by ExecuteInstruction().
RTL()
void yaze::app::emu::Cpu::RTL ()
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, next_pb_, next_pc_, PopByte(), and PopWord().
Referenced by ExecuteInstruction().
RTS()
void yaze::app::emu::Cpu::RTS ()
References callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, last_call_frame_, and PopWord().
Referenced by ExecuteInstruction().
SBC()
void yaze::app::emu::Cpu::SBC (uint32_t operand, bool immediate = false)
References A, CheckInt(), GetAccumulatorSize(), GetCarryFlag(), ReadByte(), ReadWord(), SetCarryFlag(), SetNegativeFlag(), SetOverflowFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
SEC()
void yaze::app::emu::Cpu::SEC ()
References AdrImp(), and status.
Referenced by ExecuteInstruction().
SED()
void yaze::app::emu::Cpu::SED ()
References AdrImp(), and status.
Referenced by ExecuteInstruction().
SEI()
void yaze::app::emu::Cpu::SEI ()
References AdrImp(), and status.
Referenced by ExecuteInstruction().
SEP()
void yaze::app::emu::Cpu::SEP ()
References callbacks_, CheckInt(), FetchByte(), yaze::app::emu::memory::CpuCallbacks::idle, and status.
Referenced by ExecuteInstruction().
STA()
void yaze::app::emu::Cpu::STA (uint32_t address)
References A, CheckInt(), GetAccumulatorSize(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
STP()
void yaze::app::emu::Cpu::STP ()
References callbacks_, yaze::app::emu::memory::CpuCallbacks::idle, and stopped_.
Referenced by ExecuteInstruction().
STX()
void yaze::app::emu::Cpu::STX (uint16_t address)
References CheckInt(), GetIndexSize(), WriteByte(), WriteWord(), and X.
Referenced by ExecuteInstruction().
STY()
void yaze::app::emu::Cpu::STY (uint16_t address)
References CheckInt(), GetIndexSize(), WriteByte(), WriteWord(), and Y.
Referenced by ExecuteInstruction().
STZ()
void yaze::app::emu::Cpu::STZ (uint16_t address)
References CheckInt(), GetAccumulatorSize(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
TAX()
void yaze::app::emu::Cpu::TAX ()
References A, AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), and X.
Referenced by ExecuteInstruction().
TAY()
void yaze::app::emu::Cpu::TAY ()
References A, AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), and Y.
Referenced by ExecuteInstruction().
TCD()
void yaze::app::emu::Cpu::TCD ()
References A, AdrImp(), D, SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
TCS()
void yaze::app::emu::Cpu::TCS ()
References A, AdrImp(), and SetSP().
Referenced by ExecuteInstruction().
TDC()
void yaze::app::emu::Cpu::TDC ()
References A, AdrImp(), D, SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
TRB()
void yaze::app::emu::Cpu::TRB (uint16_t address)
References A, callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
TSB()
void yaze::app::emu::Cpu::TSB (uint16_t address)
References A, callbacks_, CheckInt(), GetAccumulatorSize(), yaze::app::emu::memory::CpuCallbacks::idle, ReadByte(), ReadWord(), SetZeroFlag(), WriteByte(), and WriteWord().
Referenced by ExecuteInstruction().
TSC()
void yaze::app::emu::Cpu::TSC ()
References A, AdrImp(), SetNegativeFlag(), SetZeroFlag(), and SP().
Referenced by ExecuteInstruction().
TSX()
void yaze::app::emu::Cpu::TSX ()
References AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), SP(), and X.
Referenced by ExecuteInstruction().
TXA()
void yaze::app::emu::Cpu::TXA ()
References A, AdrImp(), GetAccumulatorSize(), SetNegativeFlag(), SetZeroFlag(), and X.
Referenced by ExecuteInstruction().
TXS()
void yaze::app::emu::Cpu::TXS ()
References AdrImp(), SetSP(), and X.
Referenced by ExecuteInstruction().
TXY()
void yaze::app::emu::Cpu::TXY ()
References AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), X, and Y.
Referenced by ExecuteInstruction().
TYA()
void yaze::app::emu::Cpu::TYA ()
References A, AdrImp(), GetAccumulatorSize(), SetNegativeFlag(), SetZeroFlag(), and Y.
Referenced by ExecuteInstruction().
TYX()
void yaze::app::emu::Cpu::TYX ()
References AdrImp(), GetIndexSize(), SetNegativeFlag(), SetZeroFlag(), X, and Y.
Referenced by ExecuteInstruction().
WAI()
void yaze::app::emu::Cpu::WAI ()
References callbacks_, yaze::app::emu::memory::CpuCallbacks::idle, and waiting_.
Referenced by ExecuteInstruction().
WDM()
void yaze::app::emu::Cpu::WDM ()
References CheckInt(), PC, and ReadByte().
Referenced by ExecuteInstruction().
XBA()
void yaze::app::emu::Cpu::XBA ()
References A, callbacks_, CheckInt(), yaze::app::emu::memory::CpuCallbacks::idle, SetNegativeFlag(), and SetZeroFlag().
Referenced by ExecuteInstruction().
XCE()
void yaze::app::emu::Cpu::XCE ()
References AdrImp(), E, and status.
Referenced by ExecuteInstruction().
SP()
uint16_t yaze::app::emu::Cpu::SP () const inline
References memory, and yaze::app::emu::memory::Memory::SP().
Referenced by LogInstructions(), PopByte(), PushByte(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject(), RunOpcode(), StackRelative(), StackRelativeIndirectIndexedY(), TSC(), and TSX().
SetSP()
void yaze::app::emu::Cpu::SetSP (uint16_t value) inline
References memory, and yaze::app::emu::memory::Memory::SetSP().
Referenced by PopByte(), PushByte(), RunOpcode(), TCS(), and TXS().
set_next_pc()
void yaze::app::emu::Cpu::set_next_pc (uint16_t value) inline
References next_pc_.
IsBreakpoint()
bool yaze::app::emu::Cpu::IsBreakpoint (uint32_t address) inline
References breakpoints_.
Referenced by Update().
SetBreakpoint()
void yaze::app::emu::Cpu::SetBreakpoint (uint32_t address) inline
References breakpoints_.
ClearBreakpoint()
void yaze::app::emu::Cpu::ClearBreakpoint (uint32_t address) inline
References breakpoints_.
ClearBreakpoints()
void yaze::app::emu::Cpu::ClearBreakpoints () inline
References breakpoints_.
GetBreakpoints()
auto yaze::app::emu::Cpu::GetBreakpoints () inline
References breakpoints_.
CheckInt()
void yaze::app::emu::Cpu::CheckInt () inline
References GetInterruptFlag(), int_wanted_, irq_wanted_, and nmi_wanted_.
Referenced by ADC(), AdrImp(), AND(), ASL(), BIT(), BRL(), CMP(), CPX(), CPY(), DEC(), DoBranch(), EOR(), INC(), JML(), LDA(), LDX(), LDY(), LSR(), MVN(), MVP(), ORA(), PHA(), PHB(), PHK(), PHP(), PHX(), PHY(), PLA(), PLB(), PLP(), PLX(), PLY(), PopWord(), PushWord(), REP(), ROL(), ROR(), RTI(), RTL(), RTS(), RunOpcode(), SBC(), SEP(), STA(), STX(), STY(), STZ(), TRB(), TSB(), WDM(), and XBA().
mutable_log_instructions()
auto yaze::app::emu::Cpu::mutable_log_instructions () -> bool* inline
References log_instructions_.
compare()
void yaze::app::emu::Cpu::compare (uint16_t register_value, uint16_t memory_value) inline private
References GetIndexSize(), SetCarryFlag(), SetNegativeFlag(), and SetZeroFlag().
Referenced by CPX(), and CPY().
SetFlag()
void yaze::app::emu::Cpu::SetFlag (uint8_t mask, bool set) inline private
References status.
Referenced by SetAccumulatorSize(), SetBreakFlag(), SetCarryFlag(), SetDecimalFlag(), SetIndexSize(), SetInterruptFlag(), SetNegativeFlag(), SetOverflowFlag(), and SetZeroFlag().
GetFlag()
bool yaze::app::emu::Cpu::GetFlag (uint8_t mask) const inline private
References status.
Referenced by GetBreakFlag(), GetCarryFlag(), GetDecimalFlag(), GetInterruptFlag(), GetNegativeFlag(), GetOverflowFlag(), and GetZeroFlag().
Member Data Documentation
breakpoints_
std::vector<uint32_t> yaze::app::emu::Cpu::breakpoints_
Referenced by ClearBreakpoint(), ClearBreakpoints(), GetBreakpoints(), IsBreakpoint(), and SetBreakpoint().
instruction_log_
std::vector<InstructionEntry> yaze::app::emu::Cpu::instruction_log_
Referenced by LogInstructions().
A
uint16_t yaze::app::emu::Cpu::A = 0
Referenced by ADC(), AND(), ANDAbsoluteLong(), BIT(), CMP(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::ConfigureObject(), DEC(), EOR(), ExecuteInstruction(), INC(), LDA(), LogInstructions(), LSR(), MVN(), MVP(), ORA(), PHA(), PLA(), PLX(), PLY(), Reset(), ROL(), ROR(), SBC(), STA(), TAX(), TAY(), TCD(), TCS(), TDC(), TRB(), TSB(), TSC(), TXA(), TYA(), and XBA().
X
uint16_t yaze::app::emu::Cpu::X = 0
Referenced by AbsoluteIndexedIndirect(), AbsoluteIndexedX(), AbsoluteLongIndexedX(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::ConfigureObject(), CPX(), DEX(), DirectPageIndexedIndirectX(), DirectPageIndexedX(), INX(), LDX(), LogInstructions(), MVN(), MVP(), PHX(), PLX(), Reset(), SetFlags(), STX(), TAX(), TSX(), TXA(), TXS(), TXY(), and TYX().
Y
uint16_t yaze::app::emu::Cpu::Y = 0
Referenced by AbsoluteIndexedY(), CPY(), DEY(), DirectPageIndexedY(), DirectPageIndirectIndexedY(), DirectPageIndirectLongIndexedY(), INY(), LDY(), LogInstructions(), MVN(), MVP(), PHY(), PLY(), Reset(), SetFlags(), StackRelativeIndirectIndexedY(), STY(), TAY(), TXY(), TYA(), and TYX().
D
uint16_t yaze::app::emu::Cpu::D = 0
Referenced by DirectPage(), DirectPageIndexedIndirectX(), DirectPageIndexedX(), DirectPageIndirect(), DirectPageIndirectIndexedY(), DirectPageIndirectLong(), DirectPageIndirectLongIndexedY(), FetchByteDirectPage(), LogInstructions(), PHD(), PLD(), Reset(), TCD(), and TDC().
DB
uint8_t yaze::app::emu::Cpu::DB = 0
Referenced by Absolute(), AbsoluteIndexedIndirect(), AbsoluteIndexedX(), AbsoluteIndexedY(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::ConfigureObject(), LogInstructions(), MVN(), MVP(), PHB(), PLB(), Reset(), and StackRelativeIndirectIndexedY().
PB
uint8_t yaze::app::emu::Cpu::PB = 0
Referenced by Absolute(), AbsoluteIndexedX(), AbsoluteIndexedY(), AbsoluteIndirect(), AbsoluteIndirectLong(), AdrImp(), BRK(), DoInterrupt(), ExecuteInstruction(), FetchByte(), FetchLong(), FetchWord(), GetInstructionLength(), Immediate(), JSL(), LDA(), LogInstructions(), PHK(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject(), Reset(), RunOpcode(), and Update().
PC
uint16_t yaze::app::emu::Cpu::PC = 0
Referenced by AbsoluteIndexedX(), AbsoluteIndexedY(), AdrImp(), BMI(), BNE(), BPL(), BRA(), BRK(), BRL(), COP(), DoInterrupt(), ExecuteInstruction(), FetchByte(), FetchByteDirectPage(), FetchLong(), FetchWord(), GetInstructionLength(), Immediate(), JML(), JSL(), JSR(), LogInstructions(), MVN(), MVP(), PER(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject(), Reset(), RunOpcode(), Update(), UpdatePC(), and WDM().
E
uint8_t yaze::app::emu::Cpu::E = 1
Referenced by COP(), yaze::app::emu::SNES::Init(), PopByte(), PushByte(), Reset(), RunOpcode(), SetFlags(), and XCE().
status
uint8_t yaze::app::emu::Cpu::status = 0b00110000
Referenced by BRK(), CLC(), CLD(), CLI(), CLV(), COP(), DoInterrupt(), GetAccumulatorSize(), GetFlag(), GetIndexSize(), LogInstructions(), PHP(), PLP(), REP(), Reset(), RTI(), RunOpcode(), SEC(), SED(), SEI(), SEP(), SetFlag(), SetFlags(), and XCE().
log_instructions_
bool yaze::app::emu::Cpu::log_instructions_ = false private
Referenced by ExecuteInstruction(), and mutable_log_instructions().
waiting_
bool yaze::app::emu::Cpu::waiting_ = false private
Referenced by Reset(), RunOpcode(), and WAI().
stopped_
bool yaze::app::emu::Cpu::stopped_ = false private
Referenced by Reset(), RunOpcode(), and STP().
irq_wanted_
bool yaze::app::emu::Cpu::irq_wanted_ = false private
Referenced by CheckInt(), Reset(), RunOpcode(), and SetIrq().
nmi_wanted_
bool yaze::app::emu::Cpu::nmi_wanted_ = false private
Referenced by CheckInt(), DoInterrupt(), Nmi(), Reset(), and RunOpcode().
reset_wanted_
bool yaze::app::emu::Cpu::reset_wanted_ = false private
Referenced by Reset(), and RunOpcode().
int_wanted_
bool yaze::app::emu::Cpu::int_wanted_ = false private
Referenced by AdrImp(), CheckInt(), DoInterrupt(), Reset(), and RunOpcode().
last_call_frame_
uint16_t yaze::app::emu::Cpu::last_call_frame_ private
Referenced by GetInstructionLength(), and RTS().
next_pc_
uint16_t yaze::app::emu::Cpu::next_pc_ private
Referenced by BCC(), BCS(), BEQ(), BMI(), BNE(), BPL(), BRA(), BRK(), BRL(), BVC(), BVS(), COP(), DoBranch(), FetchByteDirectPage(), GetInstructionLength(), JML(), JMP(), JSL(), JSR(), MVN(), MVP(), RTI(), RTL(), and set_next_pc().
next_pb_
uint8_t yaze::app::emu::Cpu::next_pb_ private
Referenced by BRK(), COP(), GetInstructionLength(), JML(), JSL(), RTI(), and RTL().
callbacks_
memory::CpuCallbacks yaze::app::emu::Cpu::callbacks_ private
Referenced by AbsoluteIndexedIndirect(), AdrImp(), ASL(), BRL(), DEC(), DirectPageIndexedIndirectX(), DoBranch(), DoInterrupt(), INC(), JSL(), JSR(), LSR(), MVN(), MVP(), PER(), PHA(), PHB(), PHD(), PHK(), PHP(), PHX(), PHY(), PLA(), PLB(), PLD(), PLP(), PLX(), PLY(), ReadByte(), REP(), ROL(), ROR(), RTI(), RTL(), RTS(), RunOpcode(), SEP(), STP(), TRB(), TSB(), WAI(), WriteByte(), and XBA().
memory
memory::Memory& yaze::app::emu::Cpu::memory private
Referenced by SetSP(), and SP().
clock
Clock& yaze::app::emu::Cpu::clock private
Referenced by Init(), Update(), and UpdateClock().
The documentation for this class was generated from the following files:
src/app/emu/cpu/cpu.h
src/app/emu/cpu/cpu.cc
src/app/emu/cpu/internal/addressing.cc
src/app/emu/cpu/internal/instructions.cc