yaze: yaze::test::integration::AsarRomIntegrationTest Class Reference
yaze::test::integration::AsarRomIntegrationTest Class Reference
Test class for Asar integration with real ROM files These tests are only run when ROM testing is enabled.
Protected Member Functions
void SetUp () override
void TearDown () override
void CreateTestPatches ()
Protected Member Functions inherited from yaze::test::RomDependentTest
void SetUp () override
Protected Attributes
std::unique_ptr< app::core::AsarWrapper > wrapper_
std::filesystem::path test_dir_
std::filesystem::path simple_patch_path_
std::filesystem::path gameplay_patch_path_
std::filesystem::path symbols_patch_path_
Protected Attributes inherited from yaze::test::RomDependentTest
std::vector< uint8_t > test_rom_
Detailed Description
Test class for Asar integration with real ROM files These tests are only run when ROM testing is enabled.
Definition at line 18 of file asar_rom_test.cc.
Member Function Documentation
SetUp()
void yaze::test::integration::AsarRomIntegrationTest::SetUp () inline override protected
Definition at line 20 of file asar_rom_test.cc.
References ASSERT_OK, CreateTestPatches(), yaze::test::RomDependentTest::SetUp(), test_dir_, and wrapper_.
TearDown()
void yaze::test::integration::AsarRomIntegrationTest::TearDown () inline override protected
Definition at line 33 of file asar_rom_test.cc.
References test_dir_.
CreateTestPatches()
void yaze::test::integration::AsarRomIntegrationTest::CreateTestPatches () inline protected
Definition at line 43 of file asar_rom_test.cc.
References simple_patch_path_, and test_dir_.
Referenced by SetUp().
Member Data Documentation
wrapper_
std::unique_ptr<app::core::AsarWrapper> yaze::test::integration::AsarRomIntegrationTest::wrapper_ protected
Definition at line 63 of file asar_rom_test.cc.
Referenced by SetUp().
test_dir_
std::filesystem::path yaze::test::integration::AsarRomIntegrationTest::test_dir_ protected
Definition at line 64 of file asar_rom_test.cc.
Referenced by CreateTestPatches(), SetUp(), and TearDown().
simple_patch_path_
std::filesystem::path yaze::test::integration::AsarRomIntegrationTest::simple_patch_path_ protected
Definition at line 65 of file asar_rom_test.cc.
Referenced by CreateTestPatches().
gameplay_patch_path_
std::filesystem::path yaze::test::integration::AsarRomIntegrationTest::gameplay_patch_path_ protected
Definition at line 66 of file asar_rom_test.cc.
symbols_patch_path_
std::filesystem::path yaze::test::integration::AsarRomIntegrationTest::symbols_patch_path_ protected
Definition at line 67 of file asar_rom_test.cc.
The documentation for this class was generated from the following file:
test/integration/asar_rom_test.cc