yaze: yaze::app::emu::audio::DigitalSignalProcessor Class Reference
yaze::app::emu::audio::DigitalSignalProcessor Class Reference
#include <dsp.h>
Classes
struct Voice
Public Member Functions
DigitalSignalProcessor ()=default
void Reset ()
void SetSampleFetcher (std::function< uint8_t(uint16_t)> fetcher)
void SetSamplePusher (std::function< void(int16_t)> pusher)
uint8_t ReadVoiceReg (uint8_t voice, uint8_t reg) const
void WriteVoiceReg (uint8_t voice, uint8_t reg, uint8_t value)
uint8_t ReadGlobalReg (uint8_t reg) const
void WriteGlobalReg (uint8_t reg, uint8_t value)
int16_t DecodeSample (uint8_t voice_num)
int16_t ProcessSample (uint8_t voice_num, int16_t sample)
void MixSamples ()
void trigger_voice (uint8_t voice_num)
void release_voice (uint8_t voice_num)
void UpdateEnvelope (uint8_t voice)
void set_voice_volume (int voice_num, int8_t left, int8_t right)
void set_voice_pitch (int voice_num, uint16_t pitch)
void set_voice_source_number (int voice_num, uint8_t srcn)
void set_voice_adsr (int voice_num, uint8_t adsr1, uint8_t adsr2)
void set_voice_gain (int voice_num, uint8_t gain)
uint8_t read_voice_envx (int voice_num)
int8_t read_voice_outx (int voice_num)
void set_master_volume (int8_t left, int8_t right)
void set_echo_volume (int8_t left, int8_t right)
void update_voice_state (uint8_t voice_num)
void key_on (uint8_t value)
void key_off (uint8_t value)
void set_flags (uint8_t value)
uint8_t read_endx ()
uint16_t AttackRate (uint8_t adsr1)
uint16_t DecayRate (uint8_t adsr2)
uint16_t ReleaseRate (uint8_t adsr2)
uint16_t CalculateDecayLevel (uint8_t adsr2)
void process_envelopes ()
void process_envelope (uint8_t voice_num)
Private Types
enum class VoiceState {
OFF , ATTACK , DECAY , SUSTAIN ,
RELEASE
}
Private Member Functions
uint8_t calculate_envelope_value (uint16_t amplitude) const
void apply_envelope_to_output (uint8_t voice_num)
Private Attributes
Voice voices_ [8]
uint8_t mvol_left
uint8_t mvol_right
uint8_t evol_left
uint8_t evol_right
uint8_t kon
uint8_t koff
uint8_t flags
uint8_t endx
std::vector< uint8_t > globalRegs = std::vector<uint8_t>(kNumGlobalRegs, 0x00)
const std::vector< uint32_t > attackTimes
const std::vector< uint32_t > decayTimes
const std::vector< uint32_t > releaseTimes
const std::vector< std::vector< uint32_t > > gainTimings
const std::vector< std::vector< uint16_t > > DigitalSignalProcessorPeriodTable
const std::vector< uint16_t > DigitalSignalProcessorPeriodOffset
SampleFetcher sample_fetcher_
SamplePusher sample_pusher_
Static Private Attributes
static const size_t kNumVoices = 8
static const size_t kNumVoiceRegs = 10
static const size_t kNumGlobalRegs = 15
static const uint16_t ENVELOPE_MAX = 2047
Detailed Description
The S-DSP is a digital signal processor generating the sound data.
A DSP register can be selected with $F2, after which it can be read or written at $F3. Often it is useful to load the register address into A, and the value to send in Y, so that MOV $F2, YA can be used to do both in one 16-bit instruction.
The DSP register address space only has 7 bits. The high bit of $F2, if set, will make the selected register read-only via $F3.
When initializing the DSP registers for the first time, take care not to accidentally enable echo writeback via FLG, because it will immediately begin overwriting values in RAM.
Voices There are 8 voices, numbered 0 to 7. Each voice X has 10 registers in the range $X0-$X9.
Name Address Bits Notes
VOL (L) $X0 SVVV VVVV Left channel volume, signed.
VOL (R) $X1 SVVV VVVV Right channel volume, signed.
P (L) $X2 LLLL LLLL Low 8 bits of sample pitch.
P (H) $X3 –HH HHHH High 6 bits of sample pitch.
SCRN $X4 SSSS SSSS Selects a sample source entry from the directory.
ADSR (1) $X5 EDDD AAAA ADSR enable (E), decay rate (D), attack rate (A).
ADSR (2) $X6 SSSR RRRR Sustain level (S), release rate (R).
GAIN $X7 0VVV VVVV 1MMV VVVV Mode (M), value (V).
ENVX $X8 0VVV VVVV Reads current 7-bit value of ADSR/GAIN envelope.
OUTX $X9 SVVV VVVV Reads signed 8-bit value of current sample wave
multiplied by ENVX, before applying VOL.
Member Enumeration Documentation
VoiceState
enum class yaze::app::emu::audio::DigitalSignalProcessor::VoiceState strong private
Enumerator
OFF
ATTACK
DECAY
SUSTAIN
RELEASE
Constructor & Destructor Documentation
DigitalSignalProcessor()
yaze::app::emu::audio::DigitalSignalProcessor::DigitalSignalProcessor () default
Member Function Documentation
calculate_envelope_value()
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::calculate_envelope_value (uint16_t amplitude) const inline private
Referenced by process_envelope().
apply_envelope_to_output()
void yaze::app::emu::audio::DigitalSignalProcessor::apply_envelope_to_output (uint8_t voice_num) inline private
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::envx, yaze::app::emu::audio::DigitalSignalProcessor::Voice::outx, and voices_.
Referenced by process_envelope().
Reset()
void yaze::app::emu::audio::DigitalSignalProcessor::Reset ()
Referenced by yaze::app::emu::audio::Apu::Initialize(), and yaze::app::emu::audio::Apu::Reset().
SetSampleFetcher()
void yaze::app::emu::audio::DigitalSignalProcessor::SetSampleFetcher (std::function< uint8_t(uint16_t)> fetcher)
References sample_fetcher_.
Referenced by yaze::app::emu::audio::Apu::Init().
SetSamplePusher()
void yaze::app::emu::audio::DigitalSignalProcessor::SetSamplePusher (std::function< void(int16_t)> pusher)
References sample_pusher_.
Referenced by yaze::app::emu::audio::Apu::Init().
ReadVoiceReg()
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::ReadVoiceReg (uint8_t voice, uint8_t reg) const
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr1, yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr2, yaze::app::emu::audio::DigitalSignalProcessor::Voice::envx, yaze::app::emu::audio::DigitalSignalProcessor::Voice::gain, kNumVoiceRegs, kNumVoices, yaze::app::emu::audio::DigitalSignalProcessor::Voice::outx, yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_high, yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_low, yaze::app::emu::audio::DigitalSignalProcessor::Voice::source_number, voices_, yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_left, and yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_right.
Referenced by UpdateEnvelope().
WriteVoiceReg()
void yaze::app::emu::audio::DigitalSignalProcessor::WriteVoiceReg (uint8_t voice, uint8_t reg, uint8_t value)
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr1, yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr2, yaze::app::emu::audio::DigitalSignalProcessor::Voice::gain, kNumVoiceRegs, kNumVoices, yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_high, yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_low, yaze::app::emu::audio::DigitalSignalProcessor::Voice::source_number, voices_, yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_left, and yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_right.
ReadGlobalReg()
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::ReadGlobalReg (uint8_t reg) const inline
References globalRegs, and kNumGlobalRegs.
Referenced by yaze::app::emu::audio::Apu::ReadDspMemory().
WriteGlobalReg()
void yaze::app::emu::audio::DigitalSignalProcessor::WriteGlobalReg (uint8_t reg, uint8_t value) inline
References globalRegs, and kNumGlobalRegs.
Referenced by yaze::app::emu::audio::Apu::WriteDspMemory().
DecodeSample()
int16_t yaze::app::emu::audio::DigitalSignalProcessor::DecodeSample (uint8_t voice_num)
References sample_fetcher_, yaze::app::emu::audio::DigitalSignalProcessor::Voice::source_number, and voices_.
Referenced by MixSamples().
ProcessSample()
int16_t yaze::app::emu::audio::DigitalSignalProcessor::ProcessSample (uint8_t voice_num, int16_t sample)
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_high, yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_low, voices_, yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_left, and yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_right.
Referenced by MixSamples(), and yaze::app::emu::audio::Apu::ProcessSamples().
MixSamples()
void yaze::app::emu::audio::DigitalSignalProcessor::MixSamples ()
References DecodeSample(), kNumVoices, ProcessSample(), and sample_pusher_.
trigger_voice()
void yaze::app::emu::audio::DigitalSignalProcessor::trigger_voice (uint8_t voice_num) inline
References ATTACK, kNumVoices, yaze::app::emu::audio::DigitalSignalProcessor::Voice::state, and voices_.
Referenced by key_on().
release_voice()
void yaze::app::emu::audio::DigitalSignalProcessor::release_voice (uint8_t voice_num) inline
References kNumVoices, OFF, RELEASE, yaze::app::emu::audio::DigitalSignalProcessor::Voice::state, and voices_.
Referenced by key_off().
UpdateEnvelope()
void yaze::app::emu::audio::DigitalSignalProcessor::UpdateEnvelope (uint8_t voice)
References ATTACK, AttackRate(), yaze::app::emu::audio::DigitalSignalProcessor::Voice::current_amplitude, DECAY, yaze::app::emu::audio::DigitalSignalProcessor::Voice::decay_level, DecayRate(), ENVELOPE_MAX, gainTimings, OFF, ReadVoiceReg(), RELEASE, ReleaseRate(), yaze::app::emu::audio::DigitalSignalProcessor::Voice::state, SUSTAIN, and voices_.
set_voice_volume()
void yaze::app::emu::audio::DigitalSignalProcessor::set_voice_volume (int voice_num, int8_t left, int8_t right) inline
References voices_, yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_left, and yaze::app::emu::audio::DigitalSignalProcessor::Voice::vol_right.
set_voice_pitch()
void yaze::app::emu::audio::DigitalSignalProcessor::set_voice_pitch (int voice_num, uint16_t pitch) inline
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_high, yaze::app::emu::audio::DigitalSignalProcessor::Voice::pitch_low, and voices_.
set_voice_source_number()
void yaze::app::emu::audio::DigitalSignalProcessor::set_voice_source_number (int voice_num, uint8_t srcn) inline
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::source_number, and voices_.
set_voice_adsr()
void yaze::app::emu::audio::DigitalSignalProcessor::set_voice_adsr (int voice_num, uint8_t adsr1, uint8_t adsr2) inline
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr1, yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr2, and voices_.
set_voice_gain()
void yaze::app::emu::audio::DigitalSignalProcessor::set_voice_gain (int voice_num, uint8_t gain) inline
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::gain, and voices_.
read_voice_envx()
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::read_voice_envx (int voice_num) inline
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::envx, and voices_.
read_voice_outx()
int8_t yaze::app::emu::audio::DigitalSignalProcessor::read_voice_outx (int voice_num) inline
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::outx, and voices_.
set_master_volume()
void yaze::app::emu::audio::DigitalSignalProcessor::set_master_volume (int8_t left, int8_t right) inline
References mvol_left, and mvol_right.
set_echo_volume()
void yaze::app::emu::audio::DigitalSignalProcessor::set_echo_volume (int8_t left, int8_t right) inline
References evol_left, and evol_right.
update_voice_state()
void yaze::app::emu::audio::DigitalSignalProcessor::update_voice_state (uint8_t voice_num)
References yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr1, yaze::app::emu::audio::DigitalSignalProcessor::Voice::adsr2, ATTACK, AttackRate(), CalculateDecayLevel(), yaze::app::emu::audio::DigitalSignalProcessor::Voice::current_amplitude, DECAY, yaze::app::emu::audio::DigitalSignalProcessor::Voice::decay_level, DecayRate(), ENVELOPE_MAX, kNumVoices, OFF, RELEASE, ReleaseRate(), yaze::app::emu::audio::DigitalSignalProcessor::Voice::state, SUSTAIN, and voices_.
Referenced by process_envelope().
key_on()
void yaze::app::emu::audio::DigitalSignalProcessor::key_on (uint8_t value) inline
References kNumVoices, and trigger_voice().
key_off()
void yaze::app::emu::audio::DigitalSignalProcessor::key_off (uint8_t value) inline
References kNumVoices, and release_voice().
set_flags()
void yaze::app::emu::audio::DigitalSignalProcessor::set_flags (uint8_t value) inline
References flags.
read_endx()
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::read_endx () inline
References endx.
AttackRate()
uint16_t yaze::app::emu::audio::DigitalSignalProcessor::AttackRate (uint8_t adsr1) inline
Referenced by update_voice_state(), and UpdateEnvelope().
DecayRate()
uint16_t yaze::app::emu::audio::DigitalSignalProcessor::DecayRate (uint8_t adsr2) inline
Referenced by update_voice_state(), and UpdateEnvelope().
ReleaseRate()
uint16_t yaze::app::emu::audio::DigitalSignalProcessor::ReleaseRate (uint8_t adsr2) inline
Referenced by update_voice_state(), and UpdateEnvelope().
CalculateDecayLevel()
uint16_t yaze::app::emu::audio::DigitalSignalProcessor::CalculateDecayLevel (uint8_t adsr2) inline
Referenced by update_voice_state().
process_envelopes()
void yaze::app::emu::audio::DigitalSignalProcessor::process_envelopes () inline
References kNumVoices, and process_envelope().
process_envelope()
void yaze::app::emu::audio::DigitalSignalProcessor::process_envelope (uint8_t voice_num)
References apply_envelope_to_output(), calculate_envelope_value(), yaze::app::emu::audio::DigitalSignalProcessor::Voice::current_amplitude, yaze::app::emu::audio::DigitalSignalProcessor::Voice::envx, kNumVoices, update_voice_state(), and voices_.
Referenced by process_envelopes().
Member Data Documentation
kNumVoices
const size_t yaze::app::emu::audio::DigitalSignalProcessor::kNumVoices = 8 static private
Referenced by key_off(), key_on(), MixSamples(), process_envelope(), process_envelopes(), ReadVoiceReg(), release_voice(), trigger_voice(), update_voice_state(), and WriteVoiceReg().
kNumVoiceRegs
const size_t yaze::app::emu::audio::DigitalSignalProcessor::kNumVoiceRegs = 10 static private
Referenced by ReadVoiceReg(), and WriteVoiceReg().
kNumGlobalRegs
const size_t yaze::app::emu::audio::DigitalSignalProcessor::kNumGlobalRegs = 15 static private
Referenced by ReadGlobalReg(), and WriteGlobalReg().
voices_
Voice yaze::app::emu::audio::DigitalSignalProcessor::voices_[8] private
Referenced by apply_envelope_to_output(), DecodeSample(), process_envelope(), ProcessSample(), read_voice_envx(), read_voice_outx(), ReadVoiceReg(), release_voice(), set_voice_adsr(), set_voice_gain(), set_voice_pitch(), set_voice_source_number(), set_voice_volume(), trigger_voice(), update_voice_state(), UpdateEnvelope(), and WriteVoiceReg().
mvol_left
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::mvol_left private
Referenced by set_master_volume().
mvol_right
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::mvol_right private
Referenced by set_master_volume().
evol_left
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::evol_left private
Referenced by set_echo_volume().
evol_right
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::evol_right private
Referenced by set_echo_volume().
kon
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::kon private
koff
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::koff private
flags
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::flags private
Referenced by set_flags().
endx
uint8_t yaze::app::emu::audio::DigitalSignalProcessor::endx private
Referenced by read_endx().
globalRegs
std::vector<uint8_t> yaze::app::emu::audio::DigitalSignalProcessor::globalRegs = std::vector<uint8_t>(kNumGlobalRegs, 0x00) private
Referenced by ReadGlobalReg(), and WriteGlobalReg().
ENVELOPE_MAX
const uint16_t yaze::app::emu::audio::DigitalSignalProcessor::ENVELOPE_MAX = 2047 static private
Referenced by update_voice_state(), and UpdateEnvelope().
attackTimes
const std::vector<uint32_t> yaze::app::emu::audio::DigitalSignalProcessor::attackTimes private
Initial value:
= {
      4100, 2600, 1500, 1000, 640, 380, 260, 160, 96, 64, 40, 24, 16, 10, 6, 0}
decayTimes
const std::vector<uint32_t> yaze::app::emu::audio::DigitalSignalProcessor::decayTimes private
Initial value:
= {1200, 740, 440, 290,
                                            180,  110, 74,  37}
releaseTimes
const std::vector<uint32_t> yaze::app::emu::audio::DigitalSignalProcessor::releaseTimes private
Initial value:
= {
      UINT32_MAX, 38000, 28000, 24000, 19000, 14000, 12000, 9400,
      7100,       5900,  4700,  3500,  2900,  2400,  1800,  1500,
      1200,       880,   740,   590,   440,   370,   290,   220,
      180,        150,   110,   92,    74,    55,    37,    18}
gainTimings
const std::vector<std::vector<uint32_t> > yaze::app::emu::audio::DigitalSignalProcessor::gainTimings private
Initial value:
= {
      {UINT32_MAX, 3100, 2600, 2000, 1500, 1300, 1000, 770, 640, 510, 380,
       320,        260,  190,  160,  130,  96,   80,   64,  48,  40,  32,
       24,         20,   16,   12,   10,   8,    6,    4,   2},
      {UINT32_MAX, 5400, 4600, 3500, 2600, 2300, 1800, 1300, 1100, 900,
       670,        560,  450,  340,  280,  220,  170,  140,  110,  84,
       70,         56,   42,   35,   28,   21,   18,   14,   11,   7,
       3},
      {UINT32_MAX, 3100, 2600, 2000, 1500, 1300, 1000, 770, 640, 510, 380,
       320,        260,  190,  160,  130,  96,   80,   64,  48,  40,  32,
       24,         20,   16,   12,   10,   8,    6,    4,   2},
      {UINT32_MAX, 38000, 28000, 24000, 19000, 14000, 12000, 9400,
       7100,       5900,  4700,  3500,  2900,  2400,  1800,  1500,
       1200,       880,   740,   590,   440,   370,   290,   220,
       180,        150,   110,   92,    55,    37,    18}}
Referenced by UpdateEnvelope().
DigitalSignalProcessorPeriodTable
const std::vector<std::vector<uint16_t> > yaze::app::emu::audio::DigitalSignalProcessor::DigitalSignalProcessorPeriodTable private
Initial value:
= {
  }
DigitalSignalProcessorPeriodOffset
const std::vector<uint16_t> yaze::app::emu::audio::DigitalSignalProcessor::DigitalSignalProcessorPeriodOffset private
Initial value:
= {
  }
sample_fetcher_
SampleFetcher yaze::app::emu::audio::DigitalSignalProcessor::sample_fetcher_ private
Referenced by DecodeSample(), and SetSampleFetcher().
sample_pusher_
SamplePusher yaze::app::emu::audio::DigitalSignalProcessor::sample_pusher_ private
Referenced by MixSamples(), and SetSamplePusher().
The documentation for this class was generated from the following files:
src/app/emu/audio/dsp.h
src/app/emu/audio/dsp.cc