yaze: yaze::app::zelda3::dungeon::DungeonObjectRenderer Class Reference
yaze::app::zelda3::dungeon::DungeonObjectRenderer Class Reference
#include <object_renderer.h>
Public Member Functions
DungeonObjectRenderer ()=default
void LoadObject (uint16_t objectId, std::array< uint8_t, 16 > &sheet_ids)
gfx::Bitmap * bitmap ()
auto memory ()
auto mutable_memory ()
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Private Member Functions
SubtypeInfo FetchSubtypeInfo (uint16_t object_id)
void ConfigureObject (const SubtypeInfo &info)
void RenderObject (const SubtypeInfo &info)
void UpdateObjectBitmap ()
Private Attributes
std::vector< uint8_t > tilemap_
uint16_t pc_with_rts_
std::vector< uint8_t > rom_data_
emu::memory::MemoryImpl memory_
emu::ClockImpl clock_
emu::memory::CpuCallbacks cpu_callbacks_
emu::Cpu cpu {memory_, clock_, cpu_callbacks_}
emu::video::Ppu ppu {memory_, clock_}
gfx::Bitmap bitmap_
PseudoVram vram_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
Definition at line 31 of file object_renderer.h.
Constructor & Destructor Documentation
DungeonObjectRenderer()
yaze::app::zelda3::dungeon::DungeonObjectRenderer::DungeonObjectRenderer () default
Member Function Documentation
LoadObject()
void yaze::app::zelda3::dungeon::DungeonObjectRenderer::LoadObject (uint16_t objectId, std::array< uint8_t, 16 > & sheet_ids)
Definition at line 8 of file object_renderer.cc.
References ConfigureObject(), FetchSubtypeInfo(), yaze::app::emu::memory::MemoryImpl::Initialize(), memory_, RenderObject(), yaze::app::SharedRom::rom(), rom_data_, yaze::app::zelda3::dungeon::PseudoVram::sheets, and vram_.
Referenced by yaze::app::editor::DungeonEditor::DrawObjectRenderer().
bitmap()
gfx::Bitmap * yaze::app::zelda3::dungeon::DungeonObjectRenderer::bitmap () inline
Definition at line 36 of file object_renderer.h.
References bitmap_.
Referenced by yaze::app::editor::DungeonEditor::DrawObjectRenderer().
memory()
auto yaze::app::zelda3::dungeon::DungeonObjectRenderer::memory () inline
Definition at line 37 of file object_renderer.h.
References memory_.
mutable_memory()
auto yaze::app::zelda3::dungeon::DungeonObjectRenderer::mutable_memory () inline
Definition at line 38 of file object_renderer.h.
References memory_.
Referenced by yaze::app::editor::DungeonEditor::DrawObjectRenderer().
FetchSubtypeInfo()
SubtypeInfo yaze::app::zelda3::dungeon::DungeonObjectRenderer::FetchSubtypeInfo (uint16_t object_id) private
Definition at line 26 of file object_renderer.cc.
References yaze::app::zelda3::dungeon::SubtypeInfo::routine_ptr, yaze::app::core::subtype1_tiles, yaze::app::core::subtype2_tiles, yaze::app::core::subtype3_tiles, and yaze::app::zelda3::dungeon::SubtypeInfo::subtype_ptr.
Referenced by LoadObject().
ConfigureObject()
void yaze::app::zelda3::dungeon::DungeonObjectRenderer::ConfigureObject (const SubtypeInfo & info) private
Definition at line 57 of file object_renderer.cc.
References yaze::app::emu::Cpu::A, cpu, yaze::app::emu::Cpu::DB, yaze::app::emu::Cpu::SetAccumulatorSize(), yaze::app::emu::Cpu::SetIndexSize(), yaze::app::emu::Cpu::WriteLong(), and yaze::app::emu::Cpu::X.
Referenced by LoadObject().
RenderObject()
void yaze::app::zelda3::dungeon::DungeonObjectRenderer::RenderObject (const SubtypeInfo & info) private
Example: the STA $BF, $CD, $C2, $CE are the location of the object in the room $B2 is used for size loop so if object size is setted on 07 that draw code will be repeated 7 times and since Y is increasing by 4 it makes the object draw from left to right
RoomDraw_Rightwards2x2_1to15or32: #_018B89: JSR RoomDraw_GetSize_1to15or32 .next #_018B8C: JSR RoomDraw_Rightwards2x2 #_018B8F: DEC.b $B2 #_018B91: BNE .next #_018B93: RTS
RoomDraw_Rightwards2x2: #_019895: LDA.w RoomDrawObjectData+0,X #_019898: STA.b [$BF],Y #_01989A: LDA.w RoomDrawObjectData+2,X #_01989D: STA.b [$CB],Y #_01989F: LDA.w RoomDrawObjectData+4,X #_0198A2: STA.b [$C2],Y #_0198A4: LDA.w RoomDrawObjectData+6,X #_0198A7: STA.b [$CE],Y #_0198A9: INY #4 #_0198AD: RTS
Definition at line 97 of file object_renderer.cc.
References cpu, yaze::app::emu::Cpu::ExecuteInstruction(), yaze::app::emu::Cpu::PB, yaze::app::emu::Cpu::PC, yaze::app::emu::Cpu::PushLong(), yaze::app::emu::Cpu::ReadByte(), yaze::app::zelda3::dungeon::SubtypeInfo::routine_ptr, and UpdateObjectBitmap().
Referenced by LoadObject().
UpdateObjectBitmap()
void yaze::app::zelda3::dungeon::DungeonObjectRenderer::UpdateObjectBitmap () private
Definition at line 118 of file object_renderer.cc.
References bitmap_, yaze::app::gfx::Bitmap::Create(), memory_, yaze::app::emu::memory::MemoryImpl::ReadWord(), yaze::app::SharedRom::rom(), yaze::app::zelda3::dungeon::PseudoVram::sheets, tilemap_, and vram_.
Referenced by RenderObject().
Member Data Documentation
tilemap_
std::vector<uint8_t> yaze::app::zelda3::dungeon::DungeonObjectRenderer::tilemap_ private
Definition at line 46 of file object_renderer.h.
Referenced by UpdateObjectBitmap().
pc_with_rts_
uint16_t yaze::app::zelda3::dungeon::DungeonObjectRenderer::pc_with_rts_ private
Definition at line 47 of file object_renderer.h.
rom_data_
std::vector<uint8_t> yaze::app::zelda3::dungeon::DungeonObjectRenderer::rom_data_ private
Definition at line 48 of file object_renderer.h.
Referenced by LoadObject().
memory_
emu::memory::MemoryImpl yaze::app::zelda3::dungeon::DungeonObjectRenderer::memory_ private
Definition at line 49 of file object_renderer.h.
Referenced by LoadObject(), memory(), mutable_memory(), and UpdateObjectBitmap().
clock_
emu::ClockImpl yaze::app::zelda3::dungeon::DungeonObjectRenderer::clock_ private
Definition at line 50 of file object_renderer.h.
cpu_callbacks_
emu::memory::CpuCallbacks yaze::app::zelda3::dungeon::DungeonObjectRenderer::cpu_callbacks_ private
Definition at line 51 of file object_renderer.h.
cpu
emu::Cpu yaze::app::zelda3::dungeon::DungeonObjectRenderer::cpu {memory_, clock_, cpu_callbacks_} private
Definition at line 52 of file object_renderer.h.
Referenced by ConfigureObject(), and RenderObject().
ppu
emu::video::Ppu yaze::app::zelda3::dungeon::DungeonObjectRenderer::ppu {memory_, clock_} private
Definition at line 53 of file object_renderer.h.
bitmap_
gfx::Bitmap yaze::app::zelda3::dungeon::DungeonObjectRenderer::bitmap_ private
Definition at line 54 of file object_renderer.h.
Referenced by bitmap(), and UpdateObjectBitmap().
vram_
PseudoVram yaze::app::zelda3::dungeon::DungeonObjectRenderer::vram_ private
Definition at line 55 of file object_renderer.h.
Referenced by LoadObject(), and UpdateObjectBitmap().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/object_renderer.h
src/app/zelda3/dungeon/object_renderer.cc