yaze: yaze::app::gui::Canvas Class Reference
yaze::app::gui::Canvas Class Reference
Represents a canvas for drawing and manipulating graphics.
#include <canvas.h>
Public Member Functions
Canvas ()=default
Canvas (ImVec2 canvas_size)
Canvas (ImVec2 canvas_size, CanvasGridSize grid_size)
void Update (const gfx::Bitmap &bitmap, ImVec2 bg_size, int tile_size, float scale=1.0f, float grid_size=64.0f)
void UpdateColorPainter (gfx::Bitmap &bitmap, const ImVec4 &color, const std::function< void()> &event, int tile_size, float scale=1.0f)
void UpdateEvent (const std::function< void()> &event, ImVec2 bg_size, int tile_size, float scale=1.0f, float grid_size=64.0f)
void UpdateInfoGrid (ImVec2 bg_size, int tile_size, float scale=1.0f, float grid_size=64.0f)
void DrawBackground (ImVec2 canvas_size=ImVec2(0, 0), bool drag=false)
void DrawContextMenu (gfx::Bitmap *bitmap=nullptr)
bool DrawTilePainter (const Bitmap &bitmap, int size, float scale=1.0f)
bool DrawSolidTilePainter (const ImVec4 &color, int size)
void DrawTileOnBitmap (int tile_size, gfx::Bitmap *bitmap, ImVec4 color)
bool DrawTileSelector (int size)
void DrawBitmap (const Bitmap &bitmap, int border_offset=0, bool ready=true)
void DrawBitmap (const Bitmap &bitmap, int border_offset, float scale)
void DrawBitmap (const Bitmap &bitmap, int x_offset=0, int y_offset=0, float scale=1.0f, int alpha=255)
void DrawBitmapTable (const BitmapTable &gfx_bin)
void DrawBitmapGroup (std::vector< int > &group, std::vector< gfx::Bitmap > &tile16_individual_, int tile_size, float scale=1.0f)
void DrawOutline (int x, int y, int w, int h)
void DrawOutlineWithColor (int x, int y, int w, int h, ImVec4 color)
void DrawOutlineWithColor (int x, int y, int w, int h, uint32_t color)
void DrawSelectRect (int current_map, int tile_size=0x10, float scale=1.0f)
void DrawSelectRectTile16 (int current_map)
void DrawRect (int x, int y, int w, int h, ImVec4 color)
void DrawText (std::string text, int x, int y)
void DrawGridLines (float grid_step)
void DrawGrid (float grid_step=64.0f, int tile_id_offset=8)
void DrawOverlay ()
void SetCanvasSize (ImVec2 canvas_size)
bool IsMouseHovering () const
void ZoomIn ()
void ZoomOut ()
auto points () const
auto mutable_points ()
auto push_back (ImVec2 pos)
auto draw_list () const
auto zero_point () const
auto scrolling () const
auto drawn_tile_position () const
auto canvas_size () const
void set_global_scale (float scale)
auto global_scale () const
auto custom_labels_enabled ()
auto custom_step () const
auto width () const
auto height () const
auto set_draggable (bool value)
auto labels (int i)
auto mutable_labels (int i)
int GetTileIdFromMousePos ()
auto set_current_labels (int i)
auto set_highlight_tile_id (int i)
auto selected_tiles () const
auto mutable_selected_tiles ()
auto selected_tile_pos () const
auto set_selected_tile_pos (ImVec2 pos)
bool select_rect_active () const
auto selected_points () const
auto hover_mouse_pos () const
Private Attributes
bool draggable_ = false
bool enable_grid_ = true
bool enable_hex_tile_labels_ = false
bool enable_custom_labels_ = false
bool enable_context_menu_ = true
bool custom_canvas_size_ = false
bool is_hovered_ = false
float custom_step_ = 0.0f
float global_scale_ = 1.0f
int current_labels_ = 0
int highlight_tile_id = -1
ImDrawList * draw_list_
ImVector< ImVec2 > points_
ImVector< ImVector< std::string > > labels_
ImVec2 scrolling_
ImVec2 canvas_sz_
ImVec2 canvas_p0_
ImVec2 canvas_p1_
ImVec2 mouse_pos_in_canvas_
ImVec2 drawn_tile_pos_
bool select_rect_active_ = false
ImVec2 selected_tile_pos_ = ImVec2(-1, -1)
ImVector< ImVec2 > selected_points_
std::vector< ImVec2 > selected_tiles_
Detailed Description
Represents a canvas for drawing and manipulating graphics.
The Canvas class provides various functions for updating and drawing graphics on a canvas. It supports features such as bitmap drawing, context menu handling, tile painting, custom grid, and more.
Constructor & Destructor Documentation
Canvas() [1/3]
yaze::app::gui::Canvas::Canvas () default
Canvas() [2/3]
yaze::app::gui::Canvas::Canvas (ImVec2 canvas_size) inline explicit
Canvas() [3/3]
yaze::app::gui::Canvas::Canvas (ImVec2 canvas_size, CanvasGridSize grid_size) inline explicit
References custom_step_, yaze::app::gui::k16x16, yaze::app::gui::k32x32, yaze::app::gui::k64x64, and yaze::app::gui::k8x8.
Member Function Documentation
Update()
void yaze::app::gui::Canvas::Update (const gfx::Bitmap & bitmap, ImVec2 bg_size, int tile_size, float scale = 1.0f, float grid_size = 64.0f)
References DrawBackground(), DrawBitmap(), DrawContextMenu(), DrawGrid(), DrawOverlay(), and DrawTileSelector().
UpdateColorPainter()
void yaze::app::gui::Canvas::UpdateColorPainter (gfx::Bitmap & bitmap, const ImVec4 & color, const std::function< void()> & event, int tile_size, float scale = 1.0f)
References DrawBackground(), DrawBitmap(), DrawContextMenu(), DrawGrid(), DrawOverlay(), DrawSolidTilePainter(), and global_scale_.
Referenced by yaze::app::editor::GraphicsEditor::UpdateGfxTabView().
UpdateEvent()
void yaze::app::gui::Canvas::UpdateEvent (const std::function< void()> & event, ImVec2 bg_size, int tile_size, float scale = 1.0f, float grid_size = 64.0f)
References DrawBackground(), DrawContextMenu(), DrawGrid(), and DrawOverlay().
UpdateInfoGrid()
void yaze::app::gui::Canvas::UpdateInfoGrid (ImVec2 bg_size, int tile_size, float scale = 1.0f, float grid_size = 64.0f)
References DrawBackground(), DrawGrid(), DrawOverlay(), and enable_custom_labels_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldProperties().
DrawBackground()
void yaze::app::gui::Canvas::DrawBackground (ImVec2 canvas_size = ImVec2(0, 0), bool drag = false)
References canvas_p0_, canvas_p1_, canvas_size(), canvas_sz_, custom_canvas_size_, draggable_, draw_list_, enable_context_menu_, global_scale_, yaze::app::gui::kMouseFlags, yaze::app::gui::kRectangleBorder, yaze::app::gui::kRectangleColor, and scrolling_.
Referenced by yaze::app::gui::BitmapCanvasPipeline(), yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::SpriteEditor::DrawCurrentSheets(), yaze::app::editor::DungeonEditor::DrawDungeonCanvas(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), yaze::app::editor::DungeonEditor::DrawRoomGraphics(), yaze::app::editor::OverworldEditor::DrawTile16Selector(), yaze::app::editor::OverworldEditor::DrawTile8Selector(), yaze::app::gui::GraphicsBinCanvasPipeline(), yaze::app::gui::GraphicsManagerCanvasPipeline(), Update(), yaze::app::editor::Tile16Editor::UpdateBlockset(), UpdateColorPainter(), UpdateEvent(), yaze::app::editor::GraphicsEditor::UpdateGfxSheetList(), UpdateInfoGrid(), yaze::app::editor::GraphicsEditor::UpdateLinkGfxView(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
DrawContextMenu()
void yaze::app::gui::Canvas::DrawContextMenu (gfx::Bitmap * bitmap = nullptr)
Todo
Add a menu item for selecting the palette
References canvas_p0_, canvas_sz_, custom_step_, enable_context_menu_, enable_grid_, enable_hex_tile_labels_, global_scale_, scrolling_, and yaze::app::gfx::Bitmap::surface().
Referenced by yaze::app::gui::BitmapCanvasPipeline(), yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::SpriteEditor::DrawCurrentSheets(), yaze::app::editor::DungeonEditor::DrawDungeonCanvas(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), yaze::app::editor::DungeonEditor::DrawRoomGraphics(), yaze::app::editor::OverworldEditor::DrawTile16Selector(), yaze::app::editor::OverworldEditor::DrawTile8Selector(), yaze::app::gui::GraphicsBinCanvasPipeline(), yaze::app::gui::GraphicsManagerCanvasPipeline(), Update(), yaze::app::editor::Tile16Editor::UpdateBlockset(), UpdateColorPainter(), UpdateEvent(), yaze::app::editor::GraphicsEditor::UpdateGfxSheetList(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
DrawTilePainter()
bool yaze::app::gui::Canvas::DrawTilePainter (const Bitmap & bitmap, int size, float scale = 1.0f)
References canvas_p0_, draw_list_, drawn_tile_pos_, yaze::app::gfx::Bitmap::is_active(), is_hovered_, mouse_pos_in_canvas_, points_, scrolling_, and yaze::app::gfx::Bitmap::texture().
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
DrawSolidTilePainter()
bool yaze::app::gui::Canvas::DrawSolidTilePainter (const ImVec4 & color, int size)
References canvas_p0_, canvas_sz_, draw_list_, drawn_tile_pos_, global_scale_, is_hovered_, points_, and scrolling_.
Referenced by UpdateColorPainter().
DrawTileOnBitmap()
void yaze::app::gui::Canvas::DrawTileOnBitmap (int tile_size, gfx::Bitmap * bitmap, ImVec4 color)
References drawn_tile_pos_, global_scale_, yaze::app::gfx::Bitmap::width(), and yaze::app::gfx::Bitmap::WriteColor().
Referenced by yaze::app::editor::GraphicsEditor::UpdateGfxTabView().
DrawTileSelector()
bool yaze::app::gui::Canvas::DrawTileSelector (int size)
References canvas_p0_, mouse_pos_in_canvas_, points_, and scrolling_.
Referenced by yaze::app::gui::BitmapCanvasPipeline(), yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::DungeonEditor::DrawRoomGraphics(), yaze::app::editor::OverworldEditor::DrawTile16Selector(), yaze::app::gui::GraphicsBinCanvasPipeline(), yaze::app::gui::GraphicsManagerCanvasPipeline(), Update(), yaze::app::editor::Tile16Editor::UpdateBlockset(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
DrawBitmap() [1/3]
void yaze::app::gui::Canvas::DrawBitmap (const Bitmap & bitmap, int border_offset = 0, bool ready = true)
References canvas_p0_, draw_list_, yaze::app::gfx::Bitmap::height(), yaze::app::gfx::Bitmap::texture(), and yaze::app::gfx::Bitmap::width().
Referenced by yaze::app::gui::BitmapCanvasPipeline(), yaze::app::editor::OverworldEditor::DrawAreaGraphics(), DrawBitmapGroup(), yaze::app::editor::SpriteEditor::DrawCurrentSheets(), yaze::app::editor::DungeonEditor::DrawDungeonCanvas(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::OverworldEditor::DrawOverworldMaps(), yaze::app::editor::OverworldEditor::DrawTile16Selector(), Update(), yaze::app::editor::Tile16Editor::UpdateBlockset(), UpdateColorPainter(), yaze::app::editor::GraphicsEditor::UpdateLinkGfxView(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
DrawBitmap() [2/3]
void yaze::app::gui::Canvas::DrawBitmap (const Bitmap & bitmap, int border_offset, float scale)
References canvas_p0_, canvas_p1_, draw_list_, yaze::app::gfx::Bitmap::height(), yaze::app::gui::kRectangleBorder, yaze::app::gfx::Bitmap::texture(), and yaze::app::gfx::Bitmap::width().
DrawBitmap() [3/3]
void yaze::app::gui::Canvas::DrawBitmap (const Bitmap & bitmap, int x_offset = 0, int y_offset = 0, float scale = 1.0f, int alpha = 255)
References canvas_p0_, draw_list_, yaze::app::gfx::Bitmap::height(), scrolling_, yaze::app::gfx::Bitmap::texture(), and yaze::app::gfx::Bitmap::width().
DrawBitmapTable()
void yaze::app::gui::Canvas::DrawBitmapTable (const BitmapTable & gfx_bin)
Todo
Add parameters for sizing and positioning
References canvas_p0_, and draw_list_.
Referenced by yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor().
DrawBitmapGroup()
void yaze::app::gui::Canvas::DrawBitmapGroup (std::vector< int > & group, std::vector< gfx::Bitmap > & tile16_individual_, int tile_size, float scale = 1.0f)
References canvas_p0_, DrawBitmap(), scrolling_, select_rect_active_, and selected_points_.
Referenced by yaze::app::editor::OverworldEditor::CheckForSelectRectangle().
DrawOutline()
void yaze::app::gui::Canvas::DrawOutline (int x, int y, int w, int h)
References canvas_p0_, draw_list_, and scrolling_.
Referenced by yaze::app::editor::OverworldEditor::CheckForCurrentMap().
DrawOutlineWithColor() [1/2]
void yaze::app::gui::Canvas::DrawOutlineWithColor (int x, int y, int w, int h, ImVec4 color)
References canvas_p0_, draw_list_, and scrolling_.
Referenced by yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs().
DrawOutlineWithColor() [2/2]
void yaze::app::gui::Canvas::DrawOutlineWithColor (int x, int y, int w, int h, uint32_t color)
References canvas_p0_, draw_list_, and scrolling_.
DrawSelectRect()
void yaze::app::gui::Canvas::DrawSelectRect (int current_map, int tile_size = 0x10, float scale = 1.0f)
References canvas_p0_, draw_list_, yaze::app::gui::kRectangleBorder, scrolling_, select_rect_active_, selected_points_, selected_tile_pos_, and selected_tiles_.
Referenced by yaze::app::editor::OverworldEditor::CheckForSelectRectangle().
DrawSelectRectTile16()
void yaze::app::gui::Canvas::DrawSelectRectTile16 (int current_map)
References canvas_p0_, scrolling_, and selected_tiles_.
DrawRect()
void yaze::app::gui::Canvas::DrawRect (int x, int y, int w, int h, ImVec4 color)
References canvas_p0_, draw_list_, and scrolling_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), and yaze::app::editor::OverworldEditor::DrawOverworldSprites().
DrawText()
void yaze::app::gui::Canvas::DrawText (std::string text, int x, int y)
References canvas_p0_, draw_list_, and scrolling_.
Referenced by yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), and yaze::app::editor::OverworldEditor::DrawOverworldSprites().
DrawGridLines()
void yaze::app::gui::Canvas::DrawGridLines (float grid_step)
References canvas_p0_, canvas_p1_, canvas_sz_, draw_list_, global_scale_, and scrolling_.
Referenced by DrawGrid().
DrawGrid()
void yaze::app::gui::Canvas::DrawGrid (float grid_step = 64.0f, int tile_id_offset = 8)
References canvas_p0_, canvas_p1_, canvas_sz_, current_labels_, custom_step_, draw_list_, DrawGridLines(), enable_custom_labels_, enable_grid_, enable_hex_tile_labels_, global_scale_, highlight_tile_id, labels_, and scrolling_.
Referenced by yaze::app::gui::BitmapCanvasPipeline(), yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::SpriteEditor::DrawCurrentSheets(), yaze::app::editor::DungeonEditor::DrawDungeonCanvas(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), yaze::app::editor::DungeonEditor::DrawRoomGraphics(), yaze::app::editor::OverworldEditor::DrawTile16Selector(), yaze::app::editor::OverworldEditor::DrawTile8Selector(), yaze::app::gui::GraphicsBinCanvasPipeline(), yaze::app::gui::GraphicsManagerCanvasPipeline(), Update(), yaze::app::editor::Tile16Editor::UpdateBlockset(), UpdateColorPainter(), UpdateEvent(), yaze::app::editor::GraphicsEditor::UpdateGfxSheetList(), UpdateInfoGrid(), yaze::app::editor::GraphicsEditor::UpdateLinkGfxView(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
DrawOverlay()
void yaze::app::gui::Canvas::DrawOverlay ()
References canvas_p0_, draw_list_, points_, scrolling_, and selected_points_.
Referenced by yaze::app::gui::BitmapCanvasPipeline(), yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::SpriteEditor::DrawCurrentSheets(), yaze::app::editor::DungeonEditor::DrawDungeonCanvas(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), yaze::app::editor::DungeonEditor::DrawRoomGraphics(), yaze::app::editor::OverworldEditor::DrawTile16Selector(), yaze::app::editor::OverworldEditor::DrawTile8Selector(), yaze::app::gui::GraphicsBinCanvasPipeline(), yaze::app::gui::GraphicsManagerCanvasPipeline(), Update(), yaze::app::editor::Tile16Editor::UpdateBlockset(), UpdateColorPainter(), UpdateEvent(), yaze::app::editor::GraphicsEditor::UpdateGfxSheetList(), UpdateInfoGrid(), yaze::app::editor::GraphicsEditor::UpdateLinkGfxView(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
SetCanvasSize()
void yaze::app::gui::Canvas::SetCanvasSize (ImVec2 canvas_size) inline
References canvas_size(), canvas_sz_, and custom_canvas_size_.
Referenced by yaze::app::editor::ScreenEditor::ScreenEditor().
IsMouseHovering()
bool yaze::app::gui::Canvas::IsMouseHovering () const inline
References is_hovered_.
ZoomIn()
void yaze::app::gui::Canvas::ZoomIn () inline
References global_scale_.
Referenced by yaze::app::editor::OverworldEditor::DrawToolset().
ZoomOut()
void yaze::app::gui::Canvas::ZoomOut () inline
References global_scale_.
Referenced by yaze::app::editor::OverworldEditor::DrawToolset().
points()
auto yaze::app::gui::Canvas::points () const inline
References points_.
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::OverworldEditor::DrawTile16Selector(), yaze::app::editor::Tile16Editor::UpdateBlockset(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
mutable_points()
auto yaze::app::gui::Canvas::mutable_points () inline
References points_.
push_back()
auto yaze::app::gui::Canvas::push_back (ImVec2 pos) inline
References points_.
draw_list()
auto yaze::app::gui::Canvas::draw_list () const inline
References draw_list_.
Referenced by yaze::app::editor::DungeonEditor::DrawRoomGraphics(), yaze::app::editor::OverworldEditor::DrawTile8Selector(), yaze::app::gui::GraphicsBinCanvasPipeline(), yaze::app::gui::GraphicsManagerCanvasPipeline(), and yaze::app::editor::GraphicsEditor::UpdateGfxSheetList().
zero_point()
auto yaze::app::gui::Canvas::zero_point () const inline
References canvas_p0_.
Referenced by yaze::app::editor::OverworldEditor::CheckForCurrentMap(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), yaze::app::editor::OverworldEditor::DrawOverworldSprites(), yaze::app::editor::DungeonEditor::DrawRoomGraphics(), yaze::app::editor::OverworldEditor::DrawTile8Selector(), yaze::app::gui::GraphicsBinCanvasPipeline(), yaze::app::gui::GraphicsManagerCanvasPipeline(), and yaze::app::editor::GraphicsEditor::UpdateGfxSheetList().
scrolling()
auto yaze::app::gui::Canvas::scrolling () const inline
References scrolling_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), and yaze::app::editor::OverworldEditor::DrawOverworldSprites().
drawn_tile_position()
auto yaze::app::gui::Canvas::drawn_tile_position () const inline
References drawn_tile_pos_.
Referenced by yaze::app::editor::OverworldEditor::DrawDebugWindow(), yaze::app::editor::OverworldEditor::DrawOverworldEdits(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
canvas_size()
auto yaze::app::gui::Canvas::canvas_size () const inline
References canvas_sz_.
Referenced by DrawBackground(), and SetCanvasSize().
set_global_scale()
void yaze::app::gui::Canvas::set_global_scale (float scale) inline
References global_scale_.
global_scale()
auto yaze::app::gui::Canvas::global_scale () const inline
References global_scale_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldMaps().
custom_labels_enabled()
auto yaze::app::gui::Canvas::custom_labels_enabled () inline
References enable_custom_labels_.
Referenced by yaze::app::editor::Tile16Editor::DrawMenu(), and yaze::app::editor::Tile16Editor::Update().
custom_step()
auto yaze::app::gui::Canvas::custom_step () const inline
References custom_step_.
width()
auto yaze::app::gui::Canvas::width () const inline
References canvas_sz_.
Referenced by GetTileIdFromMousePos().
height()
auto yaze::app::gui::Canvas::height () const inline
References canvas_sz_.
Referenced by GetTileIdFromMousePos().
set_draggable()
auto yaze::app::gui::Canvas::set_draggable (bool value) inline
References draggable_.
Referenced by yaze::app::editor::OverworldEditor::CheckForMousePan(), yaze::app::editor::OverworldEditor::DrawOverworldCanvas(), and yaze::app::editor::OverworldEditor::DrawToolset().
labels()
auto yaze::app::gui::Canvas::labels (int i) inline
References labels_.
mutable_labels()
auto yaze::app::gui::Canvas::mutable_labels (int i) inline
References labels_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldProperties(), and yaze::app::editor::Tile16Editor::Update().
GetTileIdFromMousePos()
int yaze::app::gui::Canvas::GetTileIdFromMousePos () inline
References custom_step_, height(), mouse_pos_in_canvas_, and width().
Referenced by yaze::app::editor::Tile16Editor::UpdateBlockset().
set_current_labels()
auto yaze::app::gui::Canvas::set_current_labels (int i) inline
References current_labels_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldProperties().
set_highlight_tile_id()
auto yaze::app::gui::Canvas::set_highlight_tile_id (int i) inline
References highlight_tile_id.
Referenced by yaze::app::editor::OverworldEditor::UpdateUsageStats().
selected_tiles()
auto yaze::app::gui::Canvas::selected_tiles () const inline
References selected_tiles_.
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits(), and yaze::app::editor::OverworldEditor::CheckForSelectRectangle().
mutable_selected_tiles()
auto yaze::app::gui::Canvas::mutable_selected_tiles () inline
References selected_tiles_.
selected_tile_pos()
auto yaze::app::gui::Canvas::selected_tile_pos () const inline
References selected_tile_pos_.
Referenced by yaze::app::editor::OverworldEditor::CheckForSelectRectangle().
set_selected_tile_pos()
auto yaze::app::gui::Canvas::set_selected_tile_pos (ImVec2 pos) inline
References selected_tile_pos_.
Referenced by yaze::app::editor::OverworldEditor::CheckForSelectRectangle().
select_rect_active()
bool yaze::app::gui::Canvas::select_rect_active () const inline
References select_rect_active_.
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits(), and yaze::app::editor::OverworldEditor::CheckForSelectRectangle().
selected_points()
auto yaze::app::gui::Canvas::selected_points () const inline
References selected_points_.
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits().
hover_mouse_pos()
auto yaze::app::gui::Canvas::hover_mouse_pos () const inline
References mouse_pos_in_canvas_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances().
Member Data Documentation
draggable_
bool yaze::app::gui::Canvas::draggable_ = false private
Referenced by DrawBackground(), and set_draggable().
enable_grid_
bool yaze::app::gui::Canvas::enable_grid_ = true private
Referenced by DrawContextMenu(), and DrawGrid().
enable_hex_tile_labels_
bool yaze::app::gui::Canvas::enable_hex_tile_labels_ = false private
Referenced by DrawContextMenu(), and DrawGrid().
enable_custom_labels_
bool yaze::app::gui::Canvas::enable_custom_labels_ = false private
Referenced by custom_labels_enabled(), DrawGrid(), and UpdateInfoGrid().
enable_context_menu_
bool yaze::app::gui::Canvas::enable_context_menu_ = true private
Referenced by DrawBackground(), and DrawContextMenu().
custom_canvas_size_
bool yaze::app::gui::Canvas::custom_canvas_size_ = false private
Referenced by DrawBackground(), and SetCanvasSize().
is_hovered_
bool yaze::app::gui::Canvas::is_hovered_ = false private
Referenced by DrawSolidTilePainter(), DrawTilePainter(), and IsMouseHovering().
custom_step_
float yaze::app::gui::Canvas::custom_step_ = 0.0f private
Referenced by Canvas(), custom_step(), DrawContextMenu(), DrawGrid(), and GetTileIdFromMousePos().
global_scale_
float yaze::app::gui::Canvas::global_scale_ = 1.0f private
Referenced by DrawBackground(), DrawContextMenu(), DrawGrid(), DrawGridLines(), DrawSolidTilePainter(), DrawTileOnBitmap(), global_scale(), set_global_scale(), UpdateColorPainter(), ZoomIn(), and ZoomOut().
current_labels_
int yaze::app::gui::Canvas::current_labels_ = 0 private
Referenced by DrawGrid(), and set_current_labels().
highlight_tile_id
int yaze::app::gui::Canvas::highlight_tile_id = -1 private
Referenced by DrawGrid(), and set_highlight_tile_id().
draw_list_
ImDrawList* yaze::app::gui::Canvas::draw_list_ private
Referenced by draw_list(), DrawBackground(), DrawBitmap(), DrawBitmap(), DrawBitmap(), DrawBitmapTable(), DrawGrid(), DrawGridLines(), DrawOutline(), DrawOutlineWithColor(), DrawOutlineWithColor(), DrawOverlay(), DrawRect(), DrawSelectRect(), DrawSolidTilePainter(), DrawText(), and DrawTilePainter().
points_
ImVector<ImVec2> yaze::app::gui::Canvas::points_ private
Referenced by DrawOverlay(), DrawSolidTilePainter(), DrawTilePainter(), DrawTileSelector(), mutable_points(), points(), and push_back().
labels_
ImVector<ImVector<std::string> > yaze::app::gui::Canvas::labels_ private
Referenced by DrawGrid(), labels(), and mutable_labels().
scrolling_
ImVec2 yaze::app::gui::Canvas::scrolling_ private
Referenced by DrawBackground(), DrawBitmap(), DrawBitmapGroup(), DrawContextMenu(), DrawGrid(), DrawGridLines(), DrawOutline(), DrawOutlineWithColor(), DrawOutlineWithColor(), DrawOverlay(), DrawRect(), DrawSelectRect(), DrawSelectRectTile16(), DrawSolidTilePainter(), DrawText(), DrawTilePainter(), DrawTileSelector(), and scrolling().
canvas_sz_
ImVec2 yaze::app::gui::Canvas::canvas_sz_ private
Referenced by canvas_size(), DrawBackground(), DrawContextMenu(), DrawGrid(), DrawGridLines(), DrawSolidTilePainter(), height(), SetCanvasSize(), and width().
canvas_p0_
ImVec2 yaze::app::gui::Canvas::canvas_p0_ private
Referenced by DrawBackground(), DrawBitmap(), DrawBitmap(), DrawBitmap(), DrawBitmapGroup(), DrawBitmapTable(), DrawContextMenu(), DrawGrid(), DrawGridLines(), DrawOutline(), DrawOutlineWithColor(), DrawOutlineWithColor(), DrawOverlay(), DrawRect(), DrawSelectRect(), DrawSelectRectTile16(), DrawSolidTilePainter(), DrawText(), DrawTilePainter(), DrawTileSelector(), and zero_point().
canvas_p1_
ImVec2 yaze::app::gui::Canvas::canvas_p1_ private
Referenced by DrawBackground(), DrawBitmap(), DrawGrid(), and DrawGridLines().
mouse_pos_in_canvas_
ImVec2 yaze::app::gui::Canvas::mouse_pos_in_canvas_ private
Referenced by DrawTilePainter(), DrawTileSelector(), GetTileIdFromMousePos(), and hover_mouse_pos().
drawn_tile_pos_
ImVec2 yaze::app::gui::Canvas::drawn_tile_pos_ private
Referenced by drawn_tile_position(), DrawSolidTilePainter(), DrawTileOnBitmap(), and DrawTilePainter().
select_rect_active_
bool yaze::app::gui::Canvas::select_rect_active_ = false private
Referenced by DrawBitmapGroup(), DrawSelectRect(), and select_rect_active().
selected_tile_pos_
ImVec2 yaze::app::gui::Canvas::selected_tile_pos_ = ImVec2(-1, -1) private
Referenced by DrawSelectRect(), selected_tile_pos(), and set_selected_tile_pos().
selected_points_
ImVector<ImVec2> yaze::app::gui::Canvas::selected_points_ private
Referenced by DrawBitmapGroup(), DrawOverlay(), DrawSelectRect(), and selected_points().
selected_tiles_
std::vector<ImVec2> yaze::app::gui::Canvas::selected_tiles_ private
Referenced by DrawSelectRect(), DrawSelectRectTile16(), mutable_selected_tiles(), and selected_tiles().
The documentation for this class was generated from the following files:
src/app/gui/canvas.h
src/app/gui/canvas.cc