yaze: yaze::cli::Open Class Reference
yaze::cli::Open Class Reference
Open a Rom file and display information about it.
#include <command_handler.h>
Public Member Functions
absl::Status handle (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
app::Rom rom_
Detailed Description
Open a Rom file and display information about it.
Member Function Documentation
handle()
absl::Status yaze::cli::Open::handle (const std::vector< std::string > & arg_vec) inline override virtual
Implements yaze::cli::CommandHandler.
References yaze::cli::Color::FG_BLUE, yaze::cli::Color::FG_GREEN, yaze::cli::Color::FG_RESET, yaze::app::Rom::LoadFromFile(), RETURN_IF_ERROR, yaze::cli::CommandHandler::rom_, yaze::app::Rom::size(), and yaze::app::Rom::title().
The documentation for this class was generated from the following file:
src/cli/command_handler.h