yaze: yaze::app::emu::audio::Spc700 Class Reference
yaze::app::emu::audio::Spc700 Class Reference
The Spc700 class represents the SPC700 processor.
#include <spc700.h>
Classes
struct Flags
Public Member Functions
Spc700 (ApuCallbacks &callbacks)
uint8_t FlagsToByte (Flags flags)
Flags ByteToFlags (uint8_t byte)
void Reset (bool hard=false)
void RunOpcode ()
void ExecuteInstructions (uint8_t opcode)
void LogInstruction (uint16_t initial_pc, uint8_t opcode)
uint8_t read (uint16_t address)
uint16_t read_word (uint16_t address)
uint8_t ReadOpcode ()
uint16_t ReadOpcodeWord ()
void DoBranch (uint8_t value, bool check)
void write (uint16_t address, uint8_t value)
void push_byte (uint8_t value)
void push_word (uint16_t value)
uint8_t pull_byte ()
uint16_t pull_word ()
uint16_t imm ()
uint8_t dp ()
uint16_t dpx ()
uint8_t get_dp_addr ()
uint8_t abs_bit (uint16_t *adr)
uint16_t dp_dp (uint8_t *src)
uint16_t ind ()
uint16_t ind_ind (uint8_t *srcVal)
uint16_t dp_word (uint16_t *low)
uint16_t ind_p ()
uint16_t abs_x ()
uint16_t abs_y ()
uint16_t idx ()
uint16_t idy ()
uint16_t dp_y ()
uint16_t dp_imm (uint8_t *srcVal)
uint16_t abs ()
int8_t rel ()
uint8_t dp_plus_x ()
uint8_t dp_plus_y ()
uint16_t dp_plus_x_indirect ()
uint16_t dp_indirect_plus_y ()
uint8_t i ()
uint8_t i_postinc ()
uint16_t addr_plus_i ()
uint16_t addr_plus_i_indexed ()
void MOV (uint16_t adr)
void MOV_ADDR (uint16_t address, uint8_t operand)
void MOVY (uint16_t adr)
void MOVX (uint16_t adr)
void MOVS (uint16_t adr)
void MOVSX (uint16_t adr)
void MOVSY (uint16_t adr)
void ADC (uint16_t adr)
void ADCM (uint16_t &dest, uint8_t operand)
void SBC (uint16_t adr)
void SBCM (uint16_t &dest, uint8_t operand)
void CMP (uint16_t adr)
void CMPX (uint16_t adr)
void CMPM (uint16_t dst, uint8_t value)
void CMPY (uint16_t adr)
void AND (uint16_t adr)
void ANDM (uint16_t dest, uint8_t operand)
void OR (uint16_t adr)
void ORM (uint16_t dest, uint8_t operand)
void EOR (uint16_t adr)
void EORM (uint16_t dest, uint8_t operand)
void ASL (uint16_t operand)
void LSR (uint16_t adr)
void ROL (uint16_t operand)
void ROR (uint16_t adr)
void XCN (uint8_t operand, bool isImmediate=false)
void INC (uint16_t adr)
void DEC (uint16_t operand)
void MOVW (uint16_t &dest, uint16_t operand)
void INCW (uint16_t &operand)
void DECW (uint16_t &operand)
void ADDW (uint16_t &dest, uint16_t operand)
void SUBW (uint16_t &dest, uint16_t operand)
void CMPW (uint16_t operand)
void MUL (uint8_t operand)
void DIV (uint8_t operand)
void BRA (int8_t offset)
void BEQ (int8_t offset)
void BNE (int8_t offset)
void BCS (int8_t offset)
void BCC (int8_t offset)
void BVS (int8_t offset)
void BVC (int8_t offset)
void BMI (int8_t offset)
void BPL (int8_t offset)
void BBS (uint8_t bit, uint8_t operand)
void BBC (uint8_t bit, uint8_t operand)
void JMP (uint16_t address)
void CALL (uint16_t address)
void PCALL (uint8_t offset)
void TCALL (uint8_t offset)
void BRK ()
void RET ()
void RETI ()
void PUSH (uint8_t operand)
void POP (uint8_t &operand)
void SET1 (uint8_t bit, uint8_t &operand)
void CLR1 (uint8_t bit, uint8_t &operand)
void TSET1 (uint8_t bit, uint8_t &operand)
void TCLR1 (uint8_t bit, uint8_t &operand)
void AND1 (uint8_t bit, uint8_t &operand)
void OR1 (uint8_t bit, uint8_t &operand)
void EOR1 (uint8_t bit, uint8_t &operand)
void NOT1 (uint8_t bit, uint8_t &operand)
void MOV1 (uint8_t bit, uint8_t &operand)
void CLRC ()
void SETC ()
void NOTC ()
void CLRV ()
void CLRP ()
void SETP ()
void EI ()
void DI ()
void NOP ()
void SLEEP ()
void STOP ()
Public Attributes
uint8_t A = 0x00
uint8_t X = 0x00
uint8_t Y = 0x00
uint16_t YA = 0x00
uint16_t PC = 0xFFC0
uint8_t SP = 0x00
Flags PSW
Private Attributes
ApuCallbacks callbacks_
std::vector< std::string > log_
bool stopped_
bool reset_wanted_
uint8_t opcode
uint32_t step = 0
uint32_t bstep
uint16_t adr
uint16_t adr1
uint8_t dat
uint16_t dat16
uint8_t param
const uint8_t ipl_rom_ [64]
Detailed Description
The Spc700 class represents the SPC700 processor.
The Spc700 class provides the functionality to execute instructions, read and write memory, and handle various addressing modes. It also contains registers and flags specific to the SPC700.
Note
This class assumes the existence of an AudioRam object for memory access.
Constructor & Destructor Documentation
Spc700()
yaze::app::emu::audio::Spc700::Spc700 (ApuCallbacks & callbacks) inline explicit
Member Function Documentation
FlagsToByte()
uint8_t yaze::app::emu::audio::Spc700::FlagsToByte (Flags flags) inline
References yaze::app::emu::audio::Spc700::Flags::B, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::H, yaze::app::emu::audio::Spc700::Flags::I, yaze::app::emu::audio::Spc700::Flags::N, yaze::app::emu::audio::Spc700::Flags::P, yaze::app::emu::audio::Spc700::Flags::V, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ByteToFlags()
Flags yaze::app::emu::audio::Spc700::ByteToFlags (uint8_t byte) inline
References yaze::app::emu::audio::Spc700::Flags::B, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::H, yaze::app::emu::audio::Spc700::Flags::I, yaze::app::emu::audio::Spc700::Flags::N, yaze::app::emu::audio::Spc700::Flags::P, yaze::app::emu::audio::Spc700::Flags::V, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions(), and Reset().
Reset()
void yaze::app::emu::audio::Spc700::Reset (bool hard = false)
References A, ByteToFlags(), PC, PSW, reset_wanted_, SP, step, stopped_, X, and Y.
Referenced by yaze::app::emu::audio::Apu::Reset().
RunOpcode()
void yaze::app::emu::audio::Spc700::RunOpcode ()
References bstep, callbacks_, ExecuteInstructions(), yaze::app::emu::audio::Spc700::Flags::I, yaze::app::emu::audio::ApuCallbacks::idle, opcode, PC, PSW, read(), read_word(), ReadOpcode(), reset_wanted_, SP, step, and stopped_.
Referenced by yaze::app::emu::audio::Apu::RunCycles().
ExecuteInstructions()
void yaze::app::emu::audio::Spc700::ExecuteInstructions (uint8_t opcode)
References A, abs(), abs_bit(), abs_x(), abs_y(), ADC(), ADCM(), adr, AND(), ANDM(), ASL(), yaze::app::emu::audio::Spc700::Flags::B, ByteToFlags(), yaze::app::emu::audio::Spc700::Flags::C, callbacks_, CMP(), CMPM(), CMPX(), CMPY(), dat, DEC(), DoBranch(), dp(), dp_dp(), dp_imm(), dp_word(), dp_y(), dpx(), EOR(), EORM(), FlagsToByte(), yaze::app::emu::audio::Spc700::Flags::H, yaze::app::emu::audio::Spc700::Flags::I, i(), yaze::app::emu::audio::ApuCallbacks::idle, idx(), idy(), imm(), INC(), ind(), ind_ind(), ind_p(), LSR(), MOV(), MOVS(), MOVSX(), MOVSY(), MOVX(), MOVY(), yaze::app::emu::audio::Spc700::Flags::N, opcode, OR(), ORM(), yaze::app::emu::audio::Spc700::Flags::P, PC, PSW, pull_byte(), pull_word(), push_byte(), push_word(), read(), read_word(), ReadOpcode(), ReadOpcodeWord(), ROL(), ROR(), SBC(), SBCM(), SP, step, stopped_, yaze::app::emu::audio::Spc700::Flags::V, write(), X, Y, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by RunOpcode(), and yaze_test::emu_test::TEST_F().
LogInstruction()
void yaze::app::emu::audio::Spc700::LogInstruction (uint16_t initial_pc, uint8_t opcode)
References A, opcode, spc_opcode_map, X, and Y.
read()
uint8_t yaze::app::emu::audio::Spc700::read (uint16_t address) inline
References callbacks_, and yaze::app::emu::audio::ApuCallbacks::read.
Referenced by ADC(), ADCM(), addr_plus_i(), addr_plus_i_indexed(), AND(), ANDM(), ASL(), CMP(), CMPM(), CMPX(), CMPY(), DEC(), dp_dp(), dp_plus_x(), dp_plus_y(), EOR(), EORM(), ExecuteInstructions(), i(), i_postinc(), INC(), ind(), ind_ind(), ind_p(), LSR(), MOV(), MOVS(), MOVSX(), MOVSY(), MOVX(), MOVY(), OR(), ORM(), POP(), pull_byte(), rel(), RET(), RETI(), ROL(), ROR(), RunOpcode(), SBC(), and SBCM().
read_word()
uint16_t yaze::app::emu::audio::Spc700::read_word (uint16_t address) inline
References callbacks_, and yaze::app::emu::audio::ApuCallbacks::read.
Referenced by dp_indirect_plus_y(), dp_plus_x_indirect(), ExecuteInstructions(), idx(), idy(), and RunOpcode().
ReadOpcode()
uint8_t yaze::app::emu::audio::Spc700::ReadOpcode () inline
References callbacks_, opcode, PC, and yaze::app::emu::audio::ApuCallbacks::read.
Referenced by dp(), dp_dp(), dp_imm(), dp_word(), dp_y(), dpx(), ExecuteInstructions(), idx(), idy(), ReadOpcodeWord(), and RunOpcode().
ReadOpcodeWord()
uint16_t yaze::app::emu::audio::Spc700::ReadOpcodeWord () inline
References ReadOpcode().
Referenced by abs(), abs_bit(), abs_x(), abs_y(), and ExecuteInstructions().
DoBranch()
void yaze::app::emu::audio::Spc700::DoBranch (uint8_t value, bool check) inline
References callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, and PC.
Referenced by ExecuteInstructions().
write()
void yaze::app::emu::audio::Spc700::write (uint16_t address, uint8_t value) inline
References callbacks_, and yaze::app::emu::audio::ApuCallbacks::write.
Referenced by ADCM(), ANDM(), ASL(), BRK(), CALL(), DEC(), EORM(), ExecuteInstructions(), INC(), LSR(), MOV_ADDR(), MOVS(), MOVSX(), MOVSY(), ORM(), PCALL(), PUSH(), ROL(), ROR(), SBCM(), and TCALL().
push_byte()
void yaze::app::emu::audio::Spc700::push_byte (uint8_t value) inline
References callbacks_, SP, and yaze::app::emu::audio::ApuCallbacks::write.
Referenced by ExecuteInstructions(), and push_word().
push_word()
void yaze::app::emu::audio::Spc700::push_word (uint16_t value) inline
References push_byte().
Referenced by ExecuteInstructions().
pull_byte()
uint8_t yaze::app::emu::audio::Spc700::pull_byte () inline
References read(), and SP.
Referenced by ExecuteInstructions(), and pull_word().
pull_word()
uint16_t yaze::app::emu::audio::Spc700::pull_word () inline
References pull_byte().
Referenced by ExecuteInstructions().
imm()
uint16_t yaze::app::emu::audio::Spc700::imm ()
References PC.
Referenced by ExecuteInstructions(), and XCN().
dp()
uint8_t yaze::app::emu::audio::Spc700::dp ()
References yaze::app::emu::audio::Spc700::Flags::P, PSW, and ReadOpcode().
Referenced by ExecuteInstructions().
dpx()
uint16_t yaze::app::emu::audio::Spc700::dpx ()
References callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, yaze::app::emu::audio::Spc700::Flags::P, PSW, ReadOpcode(), and X.
Referenced by ExecuteInstructions().
get_dp_addr()
uint8_t yaze::app::emu::audio::Spc700::get_dp_addr ()
abs_bit()
uint8_t yaze::app::emu::audio::Spc700::abs_bit (uint16_t * adr)
References adr, and ReadOpcodeWord().
Referenced by ExecuteInstructions().
dp_dp()
uint16_t yaze::app::emu::audio::Spc700::dp_dp (uint8_t * src)
References yaze::app::emu::audio::Spc700::Flags::P, PSW, read(), and ReadOpcode().
Referenced by ExecuteInstructions().
ind()
uint16_t yaze::app::emu::audio::Spc700::ind ()
References yaze::app::emu::audio::Spc700::Flags::P, PC, PSW, read(), and X.
Referenced by ExecuteInstructions().
ind_ind()
uint16_t yaze::app::emu::audio::Spc700::ind_ind (uint8_t * srcVal)
References yaze::app::emu::audio::Spc700::Flags::P, PC, PSW, read(), X, and Y.
Referenced by ExecuteInstructions().
dp_word()
uint16_t yaze::app::emu::audio::Spc700::dp_word (uint16_t * low)
References adr, yaze::app::emu::audio::Spc700::Flags::P, PSW, and ReadOpcode().
Referenced by ExecuteInstructions().
ind_p()
uint16_t yaze::app::emu::audio::Spc700::ind_p ()
References yaze::app::emu::audio::Spc700::Flags::P, PC, PSW, read(), and X.
Referenced by ExecuteInstructions().
abs_x()
uint16_t yaze::app::emu::audio::Spc700::abs_x ()
References callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, ReadOpcodeWord(), and X.
Referenced by ExecuteInstructions().
abs_y()
uint16_t yaze::app::emu::audio::Spc700::abs_y ()
References callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, ReadOpcodeWord(), and Y.
Referenced by ExecuteInstructions().
idx()
uint16_t yaze::app::emu::audio::Spc700::idx ()
References callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, yaze::app::emu::audio::Spc700::Flags::P, PSW, read_word(), ReadOpcode(), and X.
Referenced by ExecuteInstructions().
idy()
uint16_t yaze::app::emu::audio::Spc700::idy ()
References adr, callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, yaze::app::emu::audio::Spc700::Flags::P, PSW, read_word(), ReadOpcode(), and Y.
Referenced by ExecuteInstructions().
dp_y()
uint16_t yaze::app::emu::audio::Spc700::dp_y ()
References callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, yaze::app::emu::audio::Spc700::Flags::P, PSW, ReadOpcode(), and Y.
Referenced by ExecuteInstructions().
dp_imm()
uint16_t yaze::app::emu::audio::Spc700::dp_imm (uint8_t * srcVal)
References yaze::app::emu::audio::Spc700::Flags::P, PSW, and ReadOpcode().
Referenced by ExecuteInstructions().
abs()
uint16_t yaze::app::emu::audio::Spc700::abs ()
References ReadOpcodeWord().
Referenced by ExecuteInstructions().
rel()
int8_t yaze::app::emu::audio::Spc700::rel ()
References PC, and read().
Referenced by BBC(), and BBS().
dp_plus_x()
uint8_t yaze::app::emu::audio::Spc700::dp_plus_x ()
References yaze::app::emu::audio::Spc700::Flags::P, PC, PSW, read(), and X.
dp_plus_y()
uint8_t yaze::app::emu::audio::Spc700::dp_plus_y ()
References yaze::app::emu::audio::Spc700::Flags::P, PC, PSW, read(), and Y.
dp_plus_x_indirect()
uint16_t yaze::app::emu::audio::Spc700::dp_plus_x_indirect ()
References PC, read_word(), and X.
dp_indirect_plus_y()
uint16_t yaze::app::emu::audio::Spc700::dp_indirect_plus_y ()
References PC, read_word(), and Y.
i()
uint8_t yaze::app::emu::audio::Spc700::i ()
References yaze::app::emu::audio::Spc700::Flags::P, PSW, read(), and X.
Referenced by ExecuteInstructions().
i_postinc()
uint8_t yaze::app::emu::audio::Spc700::i_postinc ()
References yaze::app::emu::audio::Spc700::Flags::P, PSW, read(), and X.
addr_plus_i()
uint16_t yaze::app::emu::audio::Spc700::addr_plus_i ()
References PC, read(), and X.
addr_plus_i_indexed()
uint16_t yaze::app::emu::audio::Spc700::addr_plus_i_indexed ()
References PC, read(), and X.
MOV()
void yaze::app::emu::audio::Spc700::MOV (uint16_t adr)
References A, adr, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOV_ADDR()
void yaze::app::emu::audio::Spc700::MOV_ADDR (uint16_t address, uint8_t operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, write(), and yaze::app::emu::audio::Spc700::Flags::Z.
MOVY()
void yaze::app::emu::audio::Spc700::MOVY (uint16_t adr)
References adr, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), Y, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOVX()
void yaze::app::emu::audio::Spc700::MOVX (uint16_t adr)
References adr, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), X, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOVS()
void yaze::app::emu::audio::Spc700::MOVS (uint16_t adr)
References A, adr, bstep, read(), and write().
Referenced by ExecuteInstructions().
MOVSX()
void yaze::app::emu::audio::Spc700::MOVSX (uint16_t adr)
References adr, bstep, read(), write(), and X.
Referenced by ExecuteInstructions().
MOVSY()
void yaze::app::emu::audio::Spc700::MOVSY (uint16_t adr)
References adr, bstep, read(), write(), and Y.
Referenced by ExecuteInstructions().
ADC()
void yaze::app::emu::audio::Spc700::ADC (uint16_t adr)
References A, adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::H, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), yaze::app::emu::audio::Spc700::Flags::V, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ADCM()
void yaze::app::emu::audio::Spc700::ADCM (uint16_t & dest, uint8_t operand)
References yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::H, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), yaze::app::emu::audio::Spc700::Flags::V, write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
SBC()
void yaze::app::emu::audio::Spc700::SBC (uint16_t adr)
References A, adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::H, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), yaze::app::emu::audio::Spc700::Flags::V, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
SBCM()
void yaze::app::emu::audio::Spc700::SBCM (uint16_t & dest, uint8_t operand)
References A, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::H, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), yaze::app::emu::audio::Spc700::Flags::V, write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMP()
void yaze::app::emu::audio::Spc700::CMP (uint16_t adr)
References A, adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMPX()
void yaze::app::emu::audio::Spc700::CMPX (uint16_t adr)
References adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), X, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMPM()
void yaze::app::emu::audio::Spc700::CMPM (uint16_t dst, uint8_t value)
References yaze::app::emu::audio::Spc700::Flags::C, callbacks_, yaze::app::emu::audio::ApuCallbacks::idle, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
CMPY()
void yaze::app::emu::audio::Spc700::CMPY (uint16_t adr)
References adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), Y, and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
AND()
void yaze::app::emu::audio::Spc700::AND (uint16_t adr)
References A, adr, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ANDM()
void yaze::app::emu::audio::Spc700::ANDM (uint16_t dest, uint8_t operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
OR()
void yaze::app::emu::audio::Spc700::OR (uint16_t adr)
References A, adr, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ORM()
void yaze::app::emu::audio::Spc700::ORM (uint16_t dest, uint8_t operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
EOR()
void yaze::app::emu::audio::Spc700::EOR (uint16_t adr)
References A, adr, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
EORM()
void yaze::app::emu::audio::Spc700::EORM (uint16_t dest, uint8_t operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ASL()
void yaze::app::emu::audio::Spc700::ASL (uint16_t operand)
References yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
LSR()
void yaze::app::emu::audio::Spc700::LSR (uint16_t adr)
References adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ROL()
void yaze::app::emu::audio::Spc700::ROL (uint16_t operand)
References adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
ROR()
void yaze::app::emu::audio::Spc700::ROR (uint16_t adr)
References adr, yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
XCN()
void yaze::app::emu::audio::Spc700::XCN (uint8_t operand, bool isImmediate = false)
References imm(), yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
INC()
void yaze::app::emu::audio::Spc700::INC (uint16_t adr)
References adr, yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
DEC()
void yaze::app::emu::audio::Spc700::DEC (uint16_t operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, read(), write(), and yaze::app::emu::audio::Spc700::Flags::Z.
Referenced by ExecuteInstructions().
MOVW()
void yaze::app::emu::audio::Spc700::MOVW (uint16_t & dest, uint16_t operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
INCW()
void yaze::app::emu::audio::Spc700::INCW (uint16_t & operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
DECW()
void yaze::app::emu::audio::Spc700::DECW (uint16_t & operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
ADDW()
void yaze::app::emu::audio::Spc700::ADDW (uint16_t & dest, uint16_t operand)
References yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, yaze::app::emu::audio::Spc700::Flags::V, and yaze::app::emu::audio::Spc700::Flags::Z.
SUBW()
void yaze::app::emu::audio::Spc700::SUBW (uint16_t & dest, uint16_t operand)
References yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, yaze::app::emu::audio::Spc700::Flags::V, and yaze::app::emu::audio::Spc700::Flags::Z.
CMPW()
void yaze::app::emu::audio::Spc700::CMPW (uint16_t operand)
References yaze::app::emu::audio::Spc700::Flags::C, yaze::app::emu::audio::Spc700::Flags::N, PSW, YA, and yaze::app::emu::audio::Spc700::Flags::Z.
MUL()
void yaze::app::emu::audio::Spc700::MUL (uint8_t operand)
References A, yaze::app::emu::audio::Spc700::Flags::N, PSW, YA, and yaze::app::emu::audio::Spc700::Flags::Z.
DIV()
void yaze::app::emu::audio::Spc700::DIV (uint8_t operand)
References A, yaze::app::emu::audio::Spc700::Flags::N, PSW, Y, and yaze::app::emu::audio::Spc700::Flags::Z.
BRA()
void yaze::app::emu::audio::Spc700::BRA (int8_t offset)
References PC.
BEQ()
void yaze::app::emu::audio::Spc700::BEQ (int8_t offset)
References PC, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
BNE()
void yaze::app::emu::audio::Spc700::BNE (int8_t offset)
References PC, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
BCS()
void yaze::app::emu::audio::Spc700::BCS (int8_t offset)
References yaze::app::emu::audio::Spc700::Flags::C, PC, and PSW.
BCC()
void yaze::app::emu::audio::Spc700::BCC (int8_t offset)
References yaze::app::emu::audio::Spc700::Flags::C, PC, and PSW.
BVS()
void yaze::app::emu::audio::Spc700::BVS (int8_t offset)
References PC, PSW, and yaze::app::emu::audio::Spc700::Flags::V.
BVC()
void yaze::app::emu::audio::Spc700::BVC (int8_t offset)
References PC, PSW, and yaze::app::emu::audio::Spc700::Flags::V.
BMI()
void yaze::app::emu::audio::Spc700::BMI (int8_t offset)
References yaze::app::emu::audio::Spc700::Flags::N, PC, and PSW.
BPL()
void yaze::app::emu::audio::Spc700::BPL (int8_t offset)
References yaze::app::emu::audio::Spc700::Flags::N, PC, and PSW.
BBS()
void yaze::app::emu::audio::Spc700::BBS (uint8_t bit, uint8_t operand)
References PC, and rel().
BBC()
void yaze::app::emu::audio::Spc700::BBC (uint8_t bit, uint8_t operand)
References PC, and rel().
JMP()
void yaze::app::emu::audio::Spc700::JMP (uint16_t address)
References PC.
CALL()
void yaze::app::emu::audio::Spc700::CALL (uint16_t address)
References PC, SP, and write().
PCALL()
void yaze::app::emu::audio::Spc700::PCALL (uint8_t offset)
References PC, SP, and write().
TCALL()
void yaze::app::emu::audio::Spc700::TCALL (uint8_t offset)
References PC, SP, and write().
BRK()
void yaze::app::emu::audio::Spc700::BRK ()
References PC, SP, and write().
RET()
void yaze::app::emu::audio::Spc700::RET ()
References PC, read(), and SP.
RETI()
void yaze::app::emu::audio::Spc700::RETI ()
References yaze::app::emu::audio::Spc700::Flags::I, PC, PSW, read(), and SP.
PUSH()
void yaze::app::emu::audio::Spc700::PUSH (uint8_t operand)
References SP, and write().
POP()
void yaze::app::emu::audio::Spc700::POP (uint8_t & operand)
References read(), and SP.
SET1()
void yaze::app::emu::audio::Spc700::SET1 (uint8_t bit, uint8_t & operand)
CLR1()
void yaze::app::emu::audio::Spc700::CLR1 (uint8_t bit, uint8_t & operand)
TSET1()
void yaze::app::emu::audio::Spc700::TSET1 (uint8_t bit, uint8_t & operand)
References yaze::app::emu::audio::Spc700::Flags::C, and PSW.
TCLR1()
void yaze::app::emu::audio::Spc700::TCLR1 (uint8_t bit, uint8_t & operand)
References yaze::app::emu::audio::Spc700::Flags::C, and PSW.
AND1()
void yaze::app::emu::audio::Spc700::AND1 (uint8_t bit, uint8_t & operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
OR1()
void yaze::app::emu::audio::Spc700::OR1 (uint8_t bit, uint8_t & operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
EOR1()
void yaze::app::emu::audio::Spc700::EOR1 (uint8_t bit, uint8_t & operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
NOT1()
void yaze::app::emu::audio::Spc700::NOT1 (uint8_t bit, uint8_t & operand)
References yaze::app::emu::audio::Spc700::Flags::N, PSW, and yaze::app::emu::audio::Spc700::Flags::Z.
MOV1()
void yaze::app::emu::audio::Spc700::MOV1 (uint8_t bit, uint8_t & operand)
References yaze::app::emu::audio::Spc700::Flags::C, and PSW.
CLRC()
void yaze::app::emu::audio::Spc700::CLRC ()
References yaze::app::emu::audio::Spc700::Flags::C, and PSW.
SETC()
void yaze::app::emu::audio::Spc700::SETC ()
References yaze::app::emu::audio::Spc700::Flags::C, and PSW.
NOTC()
void yaze::app::emu::audio::Spc700::NOTC ()
References yaze::app::emu::audio::Spc700::Flags::C, and PSW.
CLRV()
void yaze::app::emu::audio::Spc700::CLRV ()
References PSW, and yaze::app::emu::audio::Spc700::Flags::V.
CLRP()
void yaze::app::emu::audio::Spc700::CLRP ()
References yaze::app::emu::audio::Spc700::Flags::P, and PSW.
SETP()
void yaze::app::emu::audio::Spc700::SETP ()
References yaze::app::emu::audio::Spc700::Flags::P, and PSW.
EI()
void yaze::app::emu::audio::Spc700::EI ()
References yaze::app::emu::audio::Spc700::Flags::I, and PSW.
DI()
void yaze::app::emu::audio::Spc700::DI ()
References yaze::app::emu::audio::Spc700::Flags::I, and PSW.
NOP()
void yaze::app::emu::audio::Spc700::NOP ()
References PC.
SLEEP()
void yaze::app::emu::audio::Spc700::SLEEP ()
STOP()
void yaze::app::emu::audio::Spc700::STOP ()
Member Data Documentation
callbacks_
ApuCallbacks yaze::app::emu::audio::Spc700::callbacks_ private
Referenced by abs_x(), abs_y(), CMPM(), DoBranch(), dp_y(), dpx(), ExecuteInstructions(), idx(), idy(), push_byte(), read(), read_word(), ReadOpcode(), RunOpcode(), and write().
log_
std::vector<std::string> yaze::app::emu::audio::Spc700::log_ private
stopped_
bool yaze::app::emu::audio::Spc700::stopped_ private
Referenced by ExecuteInstructions(), Reset(), and RunOpcode().
reset_wanted_
bool yaze::app::emu::audio::Spc700::reset_wanted_ private
Referenced by Reset(), and RunOpcode().
opcode
uint8_t yaze::app::emu::audio::Spc700::opcode private
Referenced by ExecuteInstructions(), LogInstruction(), ReadOpcode(), and RunOpcode().
step
uint32_t yaze::app::emu::audio::Spc700::step = 0 private
Referenced by ExecuteInstructions(), Reset(), and RunOpcode().
bstep
uint32_t yaze::app::emu::audio::Spc700::bstep private
Referenced by MOVS(), MOVSX(), MOVSY(), and RunOpcode().
adr
uint16_t yaze::app::emu::audio::Spc700::adr private
Referenced by abs_bit(), ADC(), AND(), CMP(), CMPX(), CMPY(), dp_word(), EOR(), ExecuteInstructions(), idy(), INC(), LSR(), MOV(), MOVS(), MOVSX(), MOVSY(), MOVX(), MOVY(), OR(), ROL(), ROR(), and SBC().
adr1
uint16_t yaze::app::emu::audio::Spc700::adr1 private
dat
uint8_t yaze::app::emu::audio::Spc700::dat private
Referenced by ExecuteInstructions().
dat16
uint16_t yaze::app::emu::audio::Spc700::dat16 private
param
uint8_t yaze::app::emu::audio::Spc700::param private
ipl_rom_
const uint8_t yaze::app::emu::audio::Spc700::ipl_rom_[64] private
Initial value:
{
      0xCD, 0xEF, 0xBD, 0xE8, 0x00, 0xC6, 0x1D, 0xD0, 0xFC, 0x8F, 0xAA,
      0xF4, 0x8F, 0xBB, 0xF5, 0x78, 0xCC, 0xF4, 0xD0, 0xFB, 0x2F, 0x19,
      0xEB, 0xF4, 0xD0, 0xFC, 0x7E, 0xF4, 0xD0, 0x0B, 0xE4, 0xF5, 0xCB,
      0xF4, 0xD7, 0x00, 0xFC, 0xD0, 0xF3, 0xAB, 0x01, 0x10, 0xEF, 0x7E,
      0xF4, 0x10, 0xEB, 0xBA, 0xF6, 0xDA, 0x00, 0xBA, 0xF4, 0xC4, 0xF4,
      0xDD, 0x5D, 0xD0, 0xDB, 0x1F, 0x00, 0x00, 0xC0, 0xFF}
A
uint8_t yaze::app::emu::audio::Spc700::A = 0x00
Referenced by ADC(), AND(), CMP(), DIV(), EOR(), ExecuteInstructions(), LogInstruction(), MOV(), MOVS(), MUL(), OR(), Reset(), SBC(), and SBCM().
X
uint8_t yaze::app::emu::audio::Spc700::X = 0x00
Referenced by abs_x(), addr_plus_i(), addr_plus_i_indexed(), CMPX(), dp_plus_x(), dp_plus_x_indirect(), dpx(), ExecuteInstructions(), i(), i_postinc(), idx(), ind(), ind_ind(), ind_p(), LogInstruction(), MOVSX(), MOVX(), and Reset().
Y
uint8_t yaze::app::emu::audio::Spc700::Y = 0x00
Referenced by abs_y(), CMPY(), DIV(), dp_indirect_plus_y(), dp_plus_y(), dp_y(), ExecuteInstructions(), idy(), ind_ind(), LogInstruction(), MOVSY(), MOVY(), and Reset().
YA
uint16_t yaze::app::emu::audio::Spc700::YA = 0x00
Referenced by CMPW(), and MUL().
PC
uint16_t yaze::app::emu::audio::Spc700::PC = 0xFFC0
Referenced by addr_plus_i(), addr_plus_i_indexed(), BBC(), BBS(), BCC(), BCS(), BEQ(), BMI(), BNE(), BPL(), BRA(), BRK(), BVC(), BVS(), CALL(), DoBranch(), dp_indirect_plus_y(), dp_plus_x(), dp_plus_x_indirect(), dp_plus_y(), ExecuteInstructions(), imm(), ind(), ind_ind(), ind_p(), JMP(), NOP(), PCALL(), ReadOpcode(), rel(), Reset(), RET(), RETI(), RunOpcode(), yaze_test::emu_test::Spc700Test::SetUp(), and TCALL().
SP
uint8_t yaze::app::emu::audio::Spc700::SP = 0x00
Referenced by BRK(), CALL(), ExecuteInstructions(), PCALL(), POP(), pull_byte(), PUSH(), push_byte(), Reset(), RET(), RETI(), RunOpcode(), and TCALL().
PSW
Flags yaze::app::emu::audio::Spc700::PSW
Referenced by ADC(), ADCM(), ADDW(), AND(), AND1(), ANDM(), ASL(), BCC(), BCS(), BEQ(), BMI(), BNE(), BPL(), BVC(), BVS(), CLRC(), CLRP(), CLRV(), CMP(), CMPM(), CMPW(), CMPX(), CMPY(), DEC(), DECW(), DI(), DIV(), dp(), dp_dp(), dp_imm(), dp_plus_x(), dp_plus_y(), dp_word(), dp_y(), dpx(), EI(), EOR(), EOR1(), EORM(), ExecuteInstructions(), i(), i_postinc(), idx(), idy(), INC(), INCW(), ind(), ind_ind(), ind_p(), LSR(), MOV(), MOV1(), MOV_ADDR(), MOVW(), MOVX(), MOVY(), MUL(), NOT1(), NOTC(), OR(), OR1(), ORM(), Reset(), RETI(), ROL(), ROR(), RunOpcode(), SBC(), SBCM(), SETC(), SETP(), SUBW(), TCLR1(), TSET1(), and XCN().
The documentation for this class was generated from the following files:
src/app/emu/audio/spc700.h
src/app/emu/audio/internal/addressing.cc
src/app/emu/audio/internal/instructions.cc
src/app/emu/audio/spc700.cc