yaze: yaze::test::zelda3::SpriteBuilderTest Class Reference
yaze::test::zelda3::SpriteBuilderTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Protected Attributes
SpriteBuilder sprite
Detailed Description
Definition at line 12 of file sprite_builder_test.cc.
Member Function Documentation
SetUp()
void yaze::test::zelda3::SpriteBuilderTest::SetUp () inline override protected
Definition at line 14 of file sprite_builder_test.cc.
References yaze::app::zelda3::SpriteBuilder::AddAction(), yaze::app::zelda3::SpriteAction::AddCustomInstruction(), yaze::app::zelda3::SpriteBuilder::AddFunction(), yaze::app::zelda3::SpriteAction::AddInstruction(), yaze::app::zelda3::SpriteInstruction::ApplySpeedTowardsPlayer(), yaze::app::zelda3::SpriteInstruction::BehaveAsBarrier(), yaze::app::zelda3::SpriteInstruction::BounceFromTileCollision(), yaze::app::zelda3::SpriteAction::Create(), yaze::app::zelda3::SpriteBuilder::Create(), yaze::app::zelda3::SpriteInstruction::JumpToFunction(), yaze::app::zelda3::SpriteInstruction::MoveXyz(), yaze::app::zelda3::SpriteInstruction::PlayAnimation(), yaze::app::zelda3::SpriteBuilder::SetGlobalAction(), yaze::app::zelda3::SpriteAction::SetNextAction(), yaze::app::zelda3::SpriteBuilder::SetProperty(), and sprite.
TearDown()
void yaze::test::zelda3::SpriteBuilderTest::TearDown () inline override protected
Definition at line 52 of file sprite_builder_test.cc.
Member Data Documentation
sprite
SpriteBuilder yaze::test::zelda3::SpriteBuilderTest::sprite protected
Definition at line 54 of file sprite_builder_test.cc.
Referenced by SetUp().
The documentation for this class was generated from the following file:
src/test/zelda3/sprite_builder_test.cc