yaze: yaze::app::editor::SettingsEditor Class Reference
yaze::app::editor::SettingsEditor Class Reference
#include <settings_editor.h>
Public Member Functions
SettingsEditor ()
absl::Status Update () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Find () override
Public Member Functions inherited from yaze::app::editor::Editor
Editor ()=default
virtual ~Editor ()=default
EditorType type () const
Private Member Functions
void DrawGeneralSettings ()
absl::Status DrawKeyboardShortcuts ()
Additional Inherited Members
Protected Attributes inherited from yaze::app::editor::Editor
EditorType type_
Detailed Description
Definition at line 209 of file settings_editor.h.
Constructor & Destructor Documentation
SettingsEditor()
yaze::app::editor::SettingsEditor::SettingsEditor () inline
Definition at line 211 of file settings_editor.h.
References yaze::app::editor::kSettings, and yaze::app::editor::Editor::type_.
Member Function Documentation
Update()
absl::Status yaze::app::editor::SettingsEditor::Update () override virtual
Implements yaze::app::editor::Editor.
Definition at line 34 of file settings_editor.cc.
References DrawGeneralSettings().
Referenced by yaze::app::editor::MasterEditor::ManageActiveEditors().
Undo()
absl::Status yaze::app::editor::SettingsEditor::Undo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 215 of file settings_editor.h.
Redo()
absl::Status yaze::app::editor::SettingsEditor::Redo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 216 of file settings_editor.h.
Cut()
absl::Status yaze::app::editor::SettingsEditor::Cut () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 217 of file settings_editor.h.
Copy()
absl::Status yaze::app::editor::SettingsEditor::Copy () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 218 of file settings_editor.h.
Paste()
absl::Status yaze::app::editor::SettingsEditor::Paste () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 219 of file settings_editor.h.
Find()
absl::Status yaze::app::editor::SettingsEditor::Find () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 220 of file settings_editor.h.
DrawGeneralSettings()
void yaze::app::editor::SettingsEditor::DrawGeneralSettings () private
Definition at line 49 of file settings_editor.cc.
References yaze::app::editor::FlagsMenu::Draw().
Referenced by Update().
DrawKeyboardShortcuts()
absl::Status yaze::app::editor::SettingsEditor::DrawKeyboardShortcuts () private
Definition at line 79 of file settings_editor.cc.
The documentation for this class was generated from the following files:
src/app/editor/settings_editor.h
src/app/editor/settings_editor.cc