yaze: yaze::app::editor::OverworldEditor Class Reference
yaze::app::editor::OverworldEditor Class Reference
Manipulates the Overworld and OverworldMap data in a Rom.
#include <overworld_editor.h>
Public Member Functions
OverworldEditor ()
void InitializeZeml ()
absl::Status Update () final
absl::Status Undo () override
absl::Status Redo () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Find () override
absl::Status Save ()
auto overworld ()
int jump_to_tab ()
absl::Status LoadGraphics ()
Load the Bitmap objects for each OverworldMap.
Public Member Functions inherited from yaze::app::editor::Editor
Editor ()=default
virtual ~Editor ()=default
EditorType type () const
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Public Member Functions inherited from yaze::app::editor::EntranceContext
absl::Status LoadEntranceTileTypes (Rom &rom)
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
std::string Serialize () const
Public Attributes
int jump_to_tab_ = -1
Private Types
enum class EditingMode {
DRAW_TILE , ENTRANCES , EXITS , ITEMS ,
SPRITES , TRANSPORTS , MUSIC , PAN
}
enum OverworldProperty {
LW_AREA_GFX , DW_AREA_GFX , LW_AREA_PAL , DW_AREA_PAL ,
LW_SPR_GFX_PART1 , LW_SPR_GFX_PART2 , DW_SPR_GFX_PART1 , DW_SPR_GFX_PART2 ,
LW_SPR_PAL_PART1 , LW_SPR_PAL_PART2 , DW_SPR_PAL_PART1 , DW_SPR_PAL_PART2
}
Private Member Functions
void DrawFullscreenCanvas ()
Draws the canvas, tile16 selector, and toolset in fullscreen.
void DrawToolset ()
Toolset for entrances, exits, items, sprites, and transports.
void DrawOverworldMapSettings ()
Draws the overworld map settings. Graphics, palettes, etc.
void DrawCustomOverworldMapSettings ()
Draw the overworld settings for ZSCustomOverworld.
void RefreshChildMap (int i)
void RefreshOverworldMap ()
absl::Status RefreshMapPalette ()
void RefreshMapProperties ()
absl::Status RefreshTile16Blockset ()
void DrawOverworldEntrances (ImVec2 canvas_p, ImVec2 scrolling, bool holes=false)
void DrawOverworldExits (ImVec2 zero, ImVec2 scrolling)
void DrawOverworldItems ()
void DrawOverworldSprites ()
void DrawOverworldMaps ()
void DrawOverworldEdits ()
void RenderUpdatedMapBitmap (const ImVec2 &click_position, const std::vector< uint8_t > &tile_data)
void CheckForOverworldEdits ()
Check for changes to the overworld map.
void CheckForSelectRectangle ()
Draw and create the tile16 IDs that are currently selected.
absl::Status CheckForCurrentMap ()
Check for changes to the overworld map. Calls RefreshOverworldMap and RefreshTile16Blockset on the current map if it is modified and is actively being edited.
void CheckForMousePan ()
void DrawOverworldCanvas ()
Allows the user to make changes to the overworld map.
absl::Status DrawTile16Selector ()
void DrawTile8Selector ()
absl::Status DrawAreaGraphics ()
absl::Status DrawTileSelector ()
absl::Status LoadSpriteGraphics ()
void DrawOverworldProperties ()
absl::Status UpdateUsageStats ()
void DrawUsageGrid ()
void DrawDebugWindow ()
Private Attributes
EditingMode current_mode = EditingMode::DRAW_TILE
EditingMode previous_mode = EditingMode::DRAW_TILE
int current_world_ = 0
int current_map_ = 0
int current_parent_ = 0
int current_entrance_id_ = 0
int current_exit_id_ = 0
int current_item_id_ = 0
int current_sprite_id_ = 0
int current_blockset_ = 0
int game_state_ = 1
int current_tile16_ = 0
int selected_entrance_ = 0
int selected_usage_map_ = 0xFFFF
bool all_gfx_loaded_ = false
bool map_blockset_loaded_ = false
bool selected_tile_loaded_ = false
bool show_tile16_editor_ = false
bool overworld_canvas_fullscreen_ = false
bool middle_mouse_dragging_ = false
bool is_dragging_entity_ = false
std::vector< uint8_t > selected_tile_data_
std::vector< std::vector< uint8_t > > tile16_individual_data_
std::vector< gfx::Bitmap > tile16_individual_
std::vector< std::vector< uint8_t > > tile8_individual_data_
std::vector< gfx::Bitmap > tile8_individual_
Tile16Editor tile16_editor_
GfxGroupEditor gfx_group_editor_
PaletteEditor palette_editor_
gfx::SnesPalette palette_
gfx::Bitmap selected_tile_bmp_
gfx::Bitmap tile16_blockset_bmp_
gfx::Bitmap current_gfx_bmp_
gfx::Bitmap all_gfx_bmp
gfx::BitmapTable maps_bmp_
gfx::BitmapTable current_graphics_set_
gfx::BitmapTable sprite_previews_
zelda3::overworld::Overworld overworld_
zelda3::OWBlockset refresh_blockset_
zelda3::Sprite current_sprite_
zelda3::overworld::OverworldEntrance current_entrance_
zelda3::overworld::OverworldExit current_exit_
zelda3::overworld::OverworldItem current_item_
zelda3::GameEntity * current_entity_
zelda3::GameEntity * dragged_entity_
gui::Canvas ow_map_canvas_
gui::Canvas current_gfx_canvas_
gui::Canvas blockset_canvas_
gui::Canvas graphics_bin_canvas_
gui::Canvas properties_canvas_
gui::zeml::Node layout_node_
absl::Status status_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Protected Attributes inherited from yaze::app::editor::Editor
EditorType type_
Static Protected Attributes inherited from yaze::app::editor::context::GfxContext
static std::unordered_map< uint8_t, gfx::Paletteset > palettesets_
Detailed Description
Manipulates the Overworld and OverworldMap data in a Rom.
The OverworldEditor class is responsible for managing the editing and manipulation of the overworld in a game. The user can drag and drop tiles, modify OverworldEntrance, OverworldExit, Sprite, and OverworldItem as well as change the gfx and palettes used in each overworld map.
The Overworld itself is a series of bitmap images which exist inside each OverworldMap object. The drawing of the overworld is done using the Canvas class in conjunction with these underlying Bitmap objects.
Provides access to the GfxGroupEditor and Tile16Editor through popup windows.
Definition at line 111 of file overworld_editor.h.
Member Enumeration Documentation
EditingMode
enum class yaze::app::editor::OverworldEditor::EditingMode strong private
Enumerator
DRAW_TILE
ENTRANCES
EXITS
ITEMS
SPRITES
TRANSPORTS
MUSIC
PAN
Definition at line 228 of file overworld_editor.h.
OverworldProperty
enum yaze::app::editor::OverworldEditor::OverworldProperty private
Enumerator
LW_AREA_GFX
DW_AREA_GFX
LW_AREA_PAL
DW_AREA_PAL
LW_SPR_GFX_PART1
LW_SPR_GFX_PART2
DW_SPR_GFX_PART1
DW_SPR_GFX_PART2
LW_SPR_PAL_PART1
LW_SPR_PAL_PART2
DW_SPR_PAL_PART1
DW_SPR_PAL_PART2
Definition at line 242 of file overworld_editor.h.
Constructor & Destructor Documentation
OverworldEditor()
yaze::app::editor::OverworldEditor::OverworldEditor () inline
Definition at line 117 of file overworld_editor.h.
References yaze::app::editor::kOverworld, and yaze::app::editor::Editor::type_.
Member Function Documentation
InitializeZeml()
void yaze::app::editor::OverworldEditor::InitializeZeml ()
Definition at line 1503 of file overworld_editor.cc.
References yaze::app::gui::zeml::Bind(), yaze::app::gui::zeml::Node::GetNode(), layout_node_, yaze::app::gui::zeml::LoadFile(), and yaze::app::gui::zeml::Parse().
Referenced by yaze::app::editor::EditorManager::SetupScreen().
Update()
absl::Status yaze::app::editor::OverworldEditor::Update () final virtual
Implements yaze::app::editor::Editor.
Definition at line 59 of file overworld_editor.cc.
References all_gfx_loaded_, current_gfx_bmp_, DrawFullscreenCanvas(), yaze::app::editor::Tile16Editor::InitBlockset(), layout_node_, yaze::app::editor::EntranceContext::LoadEntranceTileTypes(), yaze::app::zelda3::overworld::Overworld::mutable_all_tiles_types(), overworld_, overworld_canvas_fullscreen_, yaze::app::gui::zeml::Render(), RETURN_IF_ERROR, yaze::app::SharedRom::rom(), status_, tile16_blockset_bmp_, tile16_editor_, and tile16_individual_.
Referenced by yaze::app::editor::EditorManager::ManageActiveEditors().
Undo()
absl::Status yaze::app::editor::OverworldEditor::Undo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 122 of file overworld_editor.h.
Referenced by DrawToolset().
Redo()
absl::Status yaze::app::editor::OverworldEditor::Redo () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 123 of file overworld_editor.h.
Referenced by DrawToolset().
Cut()
absl::Status yaze::app::editor::OverworldEditor::Cut () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 124 of file overworld_editor.h.
Copy()
absl::Status yaze::app::editor::OverworldEditor::Copy () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 125 of file overworld_editor.h.
Paste()
absl::Status yaze::app::editor::OverworldEditor::Paste () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 126 of file overworld_editor.h.
Find()
absl::Status yaze::app::editor::OverworldEditor::Find () inline override virtual
Implements yaze::app::editor::Editor.
Definition at line 127 of file overworld_editor.h.
Save()
absl::Status yaze::app::editor::OverworldEditor::Save ()
Definition at line 1029 of file overworld_editor.cc.
References yaze::app::zelda3::overworld::Overworld::CreateTile32Tilemap(), yaze::app::core::ExperimentFlags::flags(), overworld(), overworld_, RETURN_IF_ERROR, yaze::app::zelda3::overworld::Overworld::SaveEntrances(), yaze::app::zelda3::overworld::Overworld::SaveExits(), yaze::app::zelda3::overworld::Overworld::SaveItems(), yaze::app::zelda3::overworld::Overworld::SaveMap16Tiles(), yaze::app::zelda3::overworld::Overworld::SaveMap32Tiles(), yaze::app::zelda3::overworld::Overworld::SaveMapProperties(), and yaze::app::zelda3::overworld::Overworld::SaveOverworldMaps().
Referenced by yaze::app::editor::EditorManager::SaveRom().
overworld()
auto yaze::app::editor::OverworldEditor::overworld () inline
Definition at line 132 of file overworld_editor.h.
References overworld_.
Referenced by DrawOverworldCanvas(), LoadGraphics(), and Save().
jump_to_tab()
int yaze::app::editor::OverworldEditor::jump_to_tab () inline
Definition at line 137 of file overworld_editor.h.
References jump_to_tab_.
Referenced by yaze::app::editor::EditorManager::ManageActiveEditors().
LoadGraphics()
absl::Status yaze::app::editor::OverworldEditor::LoadGraphics ()
Load the Bitmap objects for each OverworldMap.
Calls the Overworld class to load the image data and palettes from the Rom, then renders the area graphics and tile16 blockset Bitmap objects before assembling the OverworldMap Bitmap objects.
Definition at line 1051 of file overworld_editor.cc.
References yaze::app::zelda3::overworld::Overworld::current_area_palette(), current_gfx_bmp_, yaze::app::zelda3::overworld::Overworld::current_graphics(), yaze::app::zelda3::overworld::Overworld::current_map_bitmap_data(), yaze::app::core::ExperimentFlags::flags(), yaze::app::core::Renderer::GetInstance(), yaze::app::zelda3::overworld::kNumOverworldMaps, yaze::app::zelda3::overworld::kNumTile16Individual, yaze::app::editor::kOverworldMapSize, yaze::app::editor::kTile16Size, yaze::app::zelda3::overworld::Overworld::Load(), LoadSpriteGraphics(), map_blockset_loaded_, maps_bmp_, overworld(), overworld_, palette_, RETURN_IF_ERROR, yaze::app::SharedRom::rom(), yaze::app::zelda3::overworld::Overworld::set_current_map(), tile16_blockset_bmp_, yaze::app::zelda3::overworld::Overworld::tile16_blockset_data(), tile16_individual_, and tile16_individual_data_.
Referenced by yaze::app::editor::EditorManager::Update().
DrawFullscreenCanvas()
void yaze::app::editor::OverworldEditor::DrawFullscreenCanvas () private
Draws the canvas, tile16 selector, and toolset in fullscreen.
Definition at line 78 of file overworld_editor.cc.
References DrawOverworldCanvas(), DrawToolset(), yaze::app::core::ExperimentFlags::flags(), and overworld_canvas_fullscreen_.
Referenced by Update().
DrawToolset()
void yaze::app::editor::OverworldEditor::DrawToolset () private
Toolset for entrances, exits, items, sprites, and transports.
Todo
Customizable shortcuts for the Overworld Editor
Definition at line 95 of file overworld_editor.cc.
References yaze::app::gui::BeginWindowWithDisplaySettings(), yaze::app::core::CopyImageToClipboard(), current_map_, current_mode, yaze::app::editor::DisplayPalette(), DRAW_TILE, DrawOverworldProperties(), yaze::app::gui::EndWindowWithDisplaySettings(), ENTRANCES, EXITS, gfx_group_editor_, HOVER_HINT, ICON_MD_ADD_LOCATION, ICON_MD_CONTENT_COPY, ICON_MD_DOOR_BACK, ICON_MD_DOOR_FRONT, ICON_MD_DRAW, ICON_MD_GRASS, ICON_MD_GRID_VIEW, ICON_MD_MORE_VERT, ICON_MD_MUSIC_NOTE, ICON_MD_OPEN_IN_FULL, ICON_MD_PAN_TOOL_ALT, ICON_MD_PEST_CONTROL_RODENT, ICON_MD_REDO, ICON_MD_TABLE_CHART, ICON_MD_UNDO, ICON_MD_ZOOM_IN, ICON_MD_ZOOM_OUT, yaze::app::zelda3::overworld::Overworld::is_loaded(), ITEMS, yaze::app::editor::kToolsetTableFlags, maps_bmp_, MUSIC, NEXT_COLUMN, overworld_, overworld_canvas_fullscreen_, ow_map_canvas_, palette_, PAN, Redo(), yaze::app::gui::Canvas::set_draggable(), show_tile16_editor_, SPRITES, status_, TEXT_COLUMN, tile16_editor_, TRANSPORTS, Undo(), yaze::app::editor::GfxGroupEditor::Update(), yaze::app::editor::Tile16Editor::Update(), yaze::app::gui::Canvas::ZoomIn(), and yaze::app::gui::Canvas::ZoomOut().
Referenced by DrawFullscreenCanvas().
DrawOverworldMapSettings()
void yaze::app::editor::OverworldEditor::DrawOverworldMapSettings () private
Draws the overworld map settings. Graphics, palettes, etc.
Definition at line 262 of file overworld_editor.cc.
References current_map_, current_world_, game_state_, HOVER_HINT, yaze::app::gui::InputHexByte(), yaze::app::gui::InputHexWord(), yaze::app::editor::kGamePartComboString, yaze::app::editor::kInputFieldSize, yaze::app::editor::kMapSettingsColumnNames, yaze::app::editor::kOWMapFlags, yaze::app::editor::kOWMapTable, yaze::app::editor::kWorldList, yaze::app::zelda3::overworld::Overworld::mutable_overworld_map(), overworld_, RefreshMapPalette(), RefreshMapProperties(), RefreshOverworldMap(), and status_.
Referenced by DrawOverworldCanvas().
DrawCustomOverworldMapSettings()
void yaze::app::editor::OverworldEditor::DrawCustomOverworldMapSettings () private
Draw the overworld settings for ZSCustomOverworld.
Definition at line 332 of file overworld_editor.cc.
References current_map_, current_world_, game_state_, HOVER_HINT, yaze::app::gui::InputHexByte(), yaze::app::gui::InputHexWord(), yaze::app::editor::kGamePartComboString, yaze::app::editor::kInputFieldSize, yaze::app::editor::kMapSettingsColumnNames, yaze::app::editor::kOWMapFlags, yaze::app::editor::kOWMapTable, yaze::app::editor::kWorldList, yaze::app::zelda3::overworld::Overworld::mutable_overworld_map(), overworld_, RefreshMapPalette(), RefreshMapProperties(), RefreshOverworldMap(), and status_.
Referenced by DrawOverworldCanvas().
RefreshChildMap()
void yaze::app::editor::OverworldEditor::RefreshChildMap (int i) private
Definition at line 1128 of file overworld_editor.cc.
References current_world_, yaze::app::zelda3::overworld::Overworld::GetMapTiles(), maps_bmp_, yaze::app::zelda3::overworld::Overworld::mutable_overworld_map(), yaze::app::zelda3::overworld::Overworld::mutable_tiles16(), overworld_, PRINT_IF_ERROR, status_, and yaze::app::zelda3::overworld::Overworld::tiles16().
Referenced by RefreshOverworldMap().
RefreshOverworldMap()
void yaze::app::editor::OverworldEditor::RefreshOverworldMap () private
Definition at line 1143 of file overworld_editor.cc.
References current_map_, current_parent_, yaze::app::core::Renderer::GetInstance(), maps_bmp_, overworld_, yaze::app::zelda3::overworld::Overworld::overworld_map(), RefreshChildMap(), and yaze::app::core::Renderer::UpdateBitmap().
Referenced by CheckForCurrentMap(), CheckForOverworldEdits(), DrawCustomOverworldMapSettings(), and DrawOverworldMapSettings().
RefreshMapPalette()
absl::Status yaze::app::editor::OverworldEditor::RefreshMapPalette () private
Definition at line 1178 of file overworld_editor.cc.
References yaze::app::zelda3::overworld::Overworld::current_area_palette(), current_map_, maps_bmp_, yaze::app::zelda3::overworld::Overworld::mutable_overworld_map(), overworld_, yaze::app::zelda3::overworld::Overworld::overworld_map(), and RETURN_IF_ERROR.
Referenced by DrawCustomOverworldMapSettings(), and DrawOverworldMapSettings().
RefreshMapProperties()
void yaze::app::editor::OverworldEditor::RefreshMapProperties () private
Definition at line 1199 of file overworld_editor.cc.
References current_map_, game_state_, yaze::app::zelda3::overworld::Overworld::mutable_overworld_map(), and overworld_.
Referenced by DrawCustomOverworldMapSettings(), and DrawOverworldMapSettings().
RefreshTile16Blockset()
absl::Status yaze::app::editor::OverworldEditor::RefreshTile16Blockset () private
Definition at line 1220 of file overworld_editor.cc.
References yaze::app::gfx::Bitmap::ApplyPalette(), yaze::app::zelda3::overworld::Overworld::current_area_palette(), current_blockset_, current_map_, yaze::app::core::Renderer::GetInstance(), yaze::app::zelda3::overworld::kNumTile16Individual, overworld_, yaze::app::zelda3::overworld::Overworld::overworld_map(), palette_, RETURN_IF_ERROR, yaze::app::zelda3::overworld::Overworld::set_current_map(), tile16_blockset_bmp_, yaze::app::zelda3::overworld::Overworld::tile16_blockset_data(), tile16_individual_, and yaze::app::core::Renderer::UpdateBitmap().
Referenced by CheckForCurrentMap().
DrawOverworldEntrances()
void yaze::app::editor::OverworldEditor::DrawOverworldEntrances (ImVec2 canvas_p, ImVec2 scrolling, bool holes = false) private
Definition at line 800 of file overworld_editor.cc.
References current_entity_, current_entrance_, current_entrance_id_, current_map_, current_mode, current_world_, yaze::app::zelda3::overworld::Overworld::deleted_entrances(), dragged_entity_, yaze::app::editor::DrawEntranceInserterPopup(), yaze::app::editor::DrawOverworldEntrancePopup(), yaze::app::gui::Canvas::DrawRect(), yaze::app::gui::Canvas::DrawText(), ENTRANCES, yaze::app::zelda3::overworld::Overworld::entrances(), yaze::app::editor::HandleEntityDragging(), yaze::app::gui::Canvas::hover_mouse_pos(), is_dragging_entity_, yaze::app::editor::IsMouseHoveringOverEntity(), jump_to_tab_, yaze::app::zelda3::overworld::Overworld::mutable_deleted_entrances(), overworld_, ow_map_canvas_, and yaze::app::core::UppercaseHexByte().
Referenced by DrawOverworldCanvas().
DrawOverworldExits()
void yaze::app::editor::OverworldEditor::DrawOverworldExits (ImVec2 zero, ImVec2 scrolling) private
Definition at line 866 of file overworld_editor.cc.
References current_entity_, current_exit_, current_exit_id_, current_mode, current_world_, dragged_entity_, yaze::app::editor::DrawExitEditorPopup(), yaze::app::editor::DrawExitInserterPopup(), yaze::app::gui::Canvas::DrawRect(), yaze::app::gui::Canvas::DrawText(), yaze::app::zelda3::GameEntity::entity_id_, EXITS, yaze::app::editor::HandleEntityDragging(), is_dragging_entity_, yaze::app::editor::IsMouseHoveringOverEntity(), jump_to_tab_, yaze::app::zelda3::overworld::Overworld::mutable_exits(), overworld_, ow_map_canvas_, yaze::app::gui::Canvas::scrolling(), yaze::app::core::UppercaseHexByte(), and yaze::app::gui::Canvas::zero_point().
Referenced by DrawOverworldCanvas().
DrawOverworldItems()
void yaze::app::editor::OverworldEditor::DrawOverworldItems () private
Definition at line 917 of file overworld_editor.cc.
References current_entity_, current_item_, current_item_id_, current_mode, current_world_, dragged_entity_, yaze::app::editor::DrawItemEditorPopup(), yaze::app::editor::DrawItemInsertPopup(), yaze::app::gui::Canvas::DrawRect(), yaze::app::gui::Canvas::DrawText(), yaze::app::editor::HandleEntityDragging(), is_dragging_entity_, yaze::app::editor::IsMouseHoveringOverEntity(), ITEMS, yaze::app::zelda3::overworld::kSecretItemNames, yaze::app::zelda3::overworld::Overworld::mutable_all_items(), overworld_, ow_map_canvas_, yaze::app::gui::Canvas::scrolling(), and yaze::app::gui::Canvas::zero_point().
Referenced by DrawOverworldCanvas().
DrawOverworldSprites()
void yaze::app::editor::OverworldEditor::DrawOverworldSprites () private
Definition at line 967 of file overworld_editor.cc.
References current_entity_, current_mode, current_sprite_, current_sprite_id_, dragged_entity_, yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawRect(), yaze::app::editor::DrawSpriteEditorPopup(), yaze::app::editor::DrawSpriteInserterPopup(), yaze::app::gui::Canvas::DrawText(), game_state_, yaze::app::editor::HandleEntityDragging(), is_dragging_entity_, yaze::app::editor::IsMouseHoveringOverEntity(), yaze::app::editor::kTile16Size, yaze::app::zelda3::overworld::Overworld::mutable_sprites(), overworld_, ow_map_canvas_, yaze::app::gui::Canvas::scrolling(), sprite_previews_, SPRITES, and yaze::app::gui::Canvas::zero_point().
Referenced by DrawOverworldCanvas().
DrawOverworldMaps()
void yaze::app::editor::OverworldEditor::DrawOverworldMaps () private
Definition at line 407 of file overworld_editor.cc.
References current_world_, yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::global_scale(), yaze::app::editor::kOverworldMapSize, maps_bmp_, and ow_map_canvas_.
Referenced by DrawOverworldCanvas().
DrawOverworldEdits()
void yaze::app::editor::OverworldEditor::DrawOverworldEdits () private
Definition at line 424 of file overworld_editor.cc.
References current_map_, current_tile16_, current_world_, yaze::app::gui::Canvas::drawn_tile_position(), yaze::app::editor::kOverworldMapSize, yaze::app::zelda3::overworld::Overworld::mutable_map_tiles(), overworld_, ow_map_canvas_, RenderUpdatedMapBitmap(), and tile16_individual_data_.
Referenced by CheckForOverworldEdits().
RenderUpdatedMapBitmap()
void yaze::app::editor::OverworldEditor::RenderUpdatedMapBitmap (const ImVec2 & click_position, const std::vector< uint8_t > & tile_data) private
Definition at line 461 of file overworld_editor.cc.
References current_map_, yaze::app::editor::kOverworldMapSize, yaze::app::editor::kTile16Size, maps_bmp_, yaze::app::gfx::Bitmap::set_modified(), and yaze::app::gfx::Bitmap::WriteToPixel().
Referenced by DrawOverworldEdits().
CheckForOverworldEdits()
void yaze::app::editor::OverworldEditor::CheckForOverworldEdits () private
Check for changes to the overworld map.
This function either draws the tile painter with the current tile16 or group of tile16 data with ow_map_canvas_ and DrawOverworldEdits or it checks for left mouse button click/drag to select a tile16 or group of tile16 data from the overworld map canvas. Similar to ZScream selection.
Definition at line 487 of file overworld_editor.cc.
References blockset_canvas_, CheckForSelectRectangle(), current_tile16_, current_world_, DrawOverworldEdits(), yaze::app::gui::Canvas::DrawTilePainter(), yaze::app::zelda3::overworld::Overworld::GetTileFromPosition(), yaze::app::editor::kTile16Size, yaze::app::zelda3::overworld::Overworld::mutable_map_tiles(), overworld_, ow_map_canvas_, yaze::app::gui::Canvas::points(), RefreshOverworldMap(), yaze::app::gui::Canvas::select_rect_active(), yaze::app::gui::Canvas::selected_points(), yaze::app::gui::Canvas::selected_tiles(), and tile16_individual_.
Referenced by DrawOverworldCanvas().
CheckForSelectRectangle()
void yaze::app::editor::OverworldEditor::CheckForSelectRectangle () private
Draw and create the tile16 IDs that are currently selected.
Definition at line 549 of file overworld_editor.cc.
References current_map_, current_tile16_, yaze::app::gui::Canvas::DrawBitmapGroup(), yaze::app::gui::Canvas::DrawSelectRect(), yaze::app::zelda3::overworld::Overworld::GetTileFromPosition(), overworld_, ow_map_canvas_, yaze::app::gui::Canvas::select_rect_active(), yaze::app::gui::Canvas::selected_tile_pos(), yaze::app::gui::Canvas::selected_tiles(), yaze::app::gui::Canvas::set_selected_tile_pos(), and tile16_individual_.
Referenced by CheckForOverworldEdits().
CheckForCurrentMap()
absl::Status yaze::app::editor::OverworldEditor::CheckForCurrentMap () private
Check for changes to the overworld map. Calls RefreshOverworldMap and RefreshTile16Blockset on the current map if it is modified and is actively being edited.
Definition at line 576 of file overworld_editor.cc.
References current_map_, current_parent_, current_world_, yaze::app::gui::Canvas::DrawOutline(), yaze::app::core::Renderer::GetInstance(), yaze::app::editor::kOverworldMapSize, maps_bmp_, overworld_, yaze::app::zelda3::overworld::Overworld::overworld_map(), ow_map_canvas_, RefreshOverworldMap(), RefreshTile16Blockset(), RETURN_IF_ERROR, yaze::app::core::Renderer::UpdateBitmap(), and yaze::app::gui::Canvas::zero_point().
Referenced by DrawOverworldCanvas().
CheckForMousePan()
void yaze::app::editor::OverworldEditor::CheckForMousePan () private
Definition at line 625 of file overworld_editor.cc.
References current_mode, middle_mouse_dragging_, ow_map_canvas_, PAN, previous_mode, and yaze::app::gui::Canvas::set_draggable().
Referenced by DrawOverworldCanvas().
DrawOverworldCanvas()
void yaze::app::editor::OverworldEditor::DrawOverworldCanvas () private
Allows the user to make changes to the overworld map.
Definition at line 640 of file overworld_editor.cc.
References all_gfx_loaded_, yaze::app::gui::BeginChildBothScrollbars(), yaze::app::gui::BeginNoPadding(), CheckForCurrentMap(), CheckForMousePan(), CheckForOverworldEdits(), current_mode, DRAW_TILE, yaze::app::gui::Canvas::DrawBackground(), yaze::app::gui::Canvas::DrawContextMenu(), DrawCustomOverworldMapSettings(), yaze::app::gui::Canvas::DrawGrid(), yaze::app::gui::Canvas::DrawOverlay(), DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), DrawOverworldMaps(), DrawOverworldMapSettings(), DrawOverworldSprites(), yaze::app::gui::EndNoPadding(), yaze::app::core::ExperimentFlags::flags(), yaze::app::zelda3::overworld::Overworld::is_loaded(), overworld(), overworld_, ow_map_canvas_, PAN, yaze::app::gui::Canvas::scrolling(), yaze::app::gui::Canvas::set_draggable(), status_, and yaze::app::gui::Canvas::zero_point().
Referenced by DrawFullscreenCanvas().
DrawTile16Selector()
absl::Status yaze::app::editor::OverworldEditor::DrawTile16Selector () private
Definition at line 687 of file overworld_editor.cc.
References yaze::app::gui::BeginChildWithScrollbar(), yaze::app::gui::BeginPadding(), blockset_canvas_, current_tile16_, yaze::app::gui::Canvas::DrawBackground(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawContextMenu(), yaze::app::gui::Canvas::DrawGrid(), yaze::app::gui::Canvas::DrawOverlay(), yaze::app::gui::Canvas::DrawTileSelector(), yaze::app::gui::EndNoPadding(), map_blockset_loaded_, yaze::app::gui::Canvas::points(), RETURN_IF_ERROR, yaze::app::editor::Tile16Editor::SetCurrentTile(), show_tile16_editor_, tile16_blockset_bmp_, and tile16_editor_.
Referenced by DrawTileSelector().
DrawTile8Selector()
void yaze::app::editor::OverworldEditor::DrawTile8Selector () private
Definition at line 722 of file overworld_editor.cc.
References all_gfx_loaded_, yaze::app::gui::Canvas::draw_list(), yaze::app::gui::Canvas::DrawBackground(), yaze::app::gui::Canvas::DrawContextMenu(), yaze::app::gui::Canvas::DrawGrid(), yaze::app::gui::Canvas::DrawOverlay(), graphics_bin_canvas_, yaze::app::SharedRom::rom(), and yaze::app::gui::Canvas::zero_point().
Referenced by DrawTileSelector().
DrawAreaGraphics()
absl::Status yaze::app::editor::OverworldEditor::DrawAreaGraphics () private
Definition at line 746 of file overworld_editor.cc.
References yaze::app::gui::BeginChildWithScrollbar(), yaze::app::gui::BeginPadding(), yaze::app::zelda3::overworld::Overworld::current_area_palette(), current_gfx_canvas_, yaze::app::zelda3::overworld::Overworld::current_graphics(), current_graphics_set_, current_map_, yaze::app::gui::Canvas::DrawBackground(), yaze::app::gui::Canvas::DrawBitmap(), yaze::app::gui::Canvas::DrawContextMenu(), yaze::app::gui::Canvas::DrawGrid(), yaze::app::gui::Canvas::DrawOverlay(), yaze::app::gui::Canvas::DrawTileSelector(), yaze::app::gui::EndPadding(), yaze::app::core::Renderer::GetInstance(), yaze::app::zelda3::overworld::Overworld::is_loaded(), yaze::app::editor::kOverworldMapSize, overworld_, palette_, RETURN_IF_ERROR, and yaze::app::zelda3::overworld::Overworld::set_current_map().
Referenced by DrawTileSelector().
DrawTileSelector()
absl::Status yaze::app::editor::OverworldEditor::DrawTileSelector () private
Definition at line 776 of file overworld_editor.cc.
References yaze::app::gui::BeginChildWithScrollbar(), yaze::app::gui::BeginPadding(), DrawAreaGraphics(), DrawTile16Selector(), DrawTile8Selector(), yaze::app::gui::EndNoPadding(), yaze::app::editor::kTileSelectorTab, and status_.
LoadSpriteGraphics()
absl::Status yaze::app::editor::OverworldEditor::LoadSpriteGraphics () private
Definition at line 1110 of file overworld_editor.cc.
References yaze::app::core::Renderer::GetInstance(), overworld_, palette_, yaze::app::core::Renderer::RenderBitmap(), RETURN_IF_ERROR, sprite_previews_, and yaze::app::zelda3::overworld::Overworld::sprites().
Referenced by LoadGraphics().
DrawOverworldProperties()
void yaze::app::editor::OverworldEditor::DrawOverworldProperties () private
Definition at line 1270 of file overworld_editor.cc.
References yaze::app::gui::BeginWindowWithDisplaySettings(), DW_AREA_GFX, DW_AREA_PAL, DW_SPR_GFX_PART1, DW_SPR_GFX_PART2, DW_SPR_PAL_PART1, DW_SPR_PAL_PART2, yaze::app::gui::EndWindowWithDisplaySettings(), gfx_group_editor_, LW_AREA_GFX, LW_AREA_PAL, LW_SPR_GFX_PART1, LW_SPR_GFX_PART2, LW_SPR_PAL_PART1, LW_SPR_PAL_PART2, yaze::app::gui::Canvas::mutable_labels(), overworld_, yaze::app::zelda3::overworld::Overworld::overworld_map(), properties_canvas_, status_, yaze::app::editor::GfxGroupEditor::Update(), and yaze::app::gui::Canvas::UpdateInfoGrid().
Referenced by DrawToolset(), and UpdateUsageStats().
UpdateUsageStats()
absl::Status yaze::app::editor::OverworldEditor::UpdateUsageStats () private
Definition at line 1375 of file overworld_editor.cc.
References DrawOverworldProperties(), DrawUsageGrid(), yaze::app::zelda3::overworld::Overworld::entrances(), yaze::app::editor::kOWEditFlags, overworld_, properties_canvas_, yaze::app::SharedRom::rom(), selected_entrance_, selected_usage_map_, yaze::app::gui::Canvas::set_highlight_tile_id(), and yaze::app::core::UppercaseHexByte().
DrawUsageGrid()
void yaze::app::editor::OverworldEditor::DrawUsageGrid () private
Definition at line 1425 of file overworld_editor.cc.
References selected_usage_map_.
Referenced by UpdateUsageStats().
DrawDebugWindow()
void yaze::app::editor::OverworldEditor::DrawDebugWindow () private
Definition at line 1473 of file overworld_editor.cc.
References current_map_, current_tile16_, yaze::app::gui::Canvas::drawn_tile_position(), yaze::app::zelda3::overworld::Overworld::mutable_map_tiles(), overworld_, and ow_map_canvas_.
Member Data Documentation
jump_to_tab_
int yaze::app::editor::OverworldEditor::jump_to_tab_ = -1
Definition at line 138 of file overworld_editor.h.
Referenced by DrawOverworldEntrances(), DrawOverworldExits(), jump_to_tab(), and yaze::app::editor::EditorManager::ManageActiveEditors().
current_mode
EditingMode yaze::app::editor::OverworldEditor::current_mode = EditingMode::DRAW_TILE private
Definition at line 239 of file overworld_editor.h.
Referenced by CheckForMousePan(), DrawOverworldCanvas(), DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), DrawOverworldSprites(), and DrawToolset().
previous_mode
EditingMode yaze::app::editor::OverworldEditor::previous_mode = EditingMode::DRAW_TILE private
Definition at line 240 of file overworld_editor.h.
Referenced by CheckForMousePan().
current_world_
int yaze::app::editor::OverworldEditor::current_world_ = 0 private
Definition at line 257 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), CheckForOverworldEdits(), DrawCustomOverworldMapSettings(), DrawOverworldEdits(), DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), DrawOverworldMaps(), DrawOverworldMapSettings(), and RefreshChildMap().
current_map_
int yaze::app::editor::OverworldEditor::current_map_ = 0 private
Definition at line 258 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), CheckForSelectRectangle(), DrawAreaGraphics(), DrawCustomOverworldMapSettings(), DrawDebugWindow(), DrawOverworldEdits(), DrawOverworldEntrances(), DrawOverworldMapSettings(), DrawToolset(), RefreshMapPalette(), RefreshMapProperties(), RefreshOverworldMap(), RefreshTile16Blockset(), and RenderUpdatedMapBitmap().
current_parent_
int yaze::app::editor::OverworldEditor::current_parent_ = 0 private
Definition at line 259 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), and RefreshOverworldMap().
current_entrance_id_
int yaze::app::editor::OverworldEditor::current_entrance_id_ = 0 private
Definition at line 260 of file overworld_editor.h.
Referenced by DrawOverworldEntrances().
current_exit_id_
int yaze::app::editor::OverworldEditor::current_exit_id_ = 0 private
Definition at line 261 of file overworld_editor.h.
Referenced by DrawOverworldExits().
current_item_id_
int yaze::app::editor::OverworldEditor::current_item_id_ = 0 private
Definition at line 262 of file overworld_editor.h.
Referenced by DrawOverworldItems().
current_sprite_id_
int yaze::app::editor::OverworldEditor::current_sprite_id_ = 0 private
Definition at line 263 of file overworld_editor.h.
Referenced by DrawOverworldSprites().
current_blockset_
int yaze::app::editor::OverworldEditor::current_blockset_ = 0 private
Definition at line 264 of file overworld_editor.h.
Referenced by RefreshTile16Blockset().
game_state_
int yaze::app::editor::OverworldEditor::game_state_ = 1 private
Definition at line 265 of file overworld_editor.h.
Referenced by DrawCustomOverworldMapSettings(), DrawOverworldMapSettings(), DrawOverworldSprites(), and RefreshMapProperties().
current_tile16_
int yaze::app::editor::OverworldEditor::current_tile16_ = 0 private
Definition at line 266 of file overworld_editor.h.
Referenced by CheckForOverworldEdits(), CheckForSelectRectangle(), DrawDebugWindow(), DrawOverworldEdits(), and DrawTile16Selector().
selected_entrance_
int yaze::app::editor::OverworldEditor::selected_entrance_ = 0 private
Definition at line 267 of file overworld_editor.h.
Referenced by UpdateUsageStats().
selected_usage_map_
int yaze::app::editor::OverworldEditor::selected_usage_map_ = 0xFFFF private
Definition at line 268 of file overworld_editor.h.
Referenced by DrawUsageGrid(), and UpdateUsageStats().
all_gfx_loaded_
bool yaze::app::editor::OverworldEditor::all_gfx_loaded_ = false private
Definition at line 270 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), DrawTile8Selector(), and Update().
map_blockset_loaded_
bool yaze::app::editor::OverworldEditor::map_blockset_loaded_ = false private
Definition at line 271 of file overworld_editor.h.
Referenced by DrawTile16Selector(), and LoadGraphics().
selected_tile_loaded_
bool yaze::app::editor::OverworldEditor::selected_tile_loaded_ = false private
Definition at line 272 of file overworld_editor.h.
show_tile16_editor_
bool yaze::app::editor::OverworldEditor::show_tile16_editor_ = false private
Definition at line 273 of file overworld_editor.h.
Referenced by DrawTile16Selector(), and DrawToolset().
overworld_canvas_fullscreen_
bool yaze::app::editor::OverworldEditor::overworld_canvas_fullscreen_ = false private
Definition at line 274 of file overworld_editor.h.
Referenced by DrawFullscreenCanvas(), DrawToolset(), and Update().
middle_mouse_dragging_
bool yaze::app::editor::OverworldEditor::middle_mouse_dragging_ = false private
Definition at line 275 of file overworld_editor.h.
Referenced by CheckForMousePan().
is_dragging_entity_
bool yaze::app::editor::OverworldEditor::is_dragging_entity_ = false private
Definition at line 276 of file overworld_editor.h.
Referenced by DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), and DrawOverworldSprites().
selected_tile_data_
std::vector<uint8_t> yaze::app::editor::OverworldEditor::selected_tile_data_ private
Definition at line 278 of file overworld_editor.h.
tile16_individual_data_
std::vector<std::vector<uint8_t> > yaze::app::editor::OverworldEditor::tile16_individual_data_ private
Definition at line 279 of file overworld_editor.h.
Referenced by DrawOverworldEdits(), and LoadGraphics().
tile16_individual_
std::vector<gfx::Bitmap> yaze::app::editor::OverworldEditor::tile16_individual_ private
Definition at line 280 of file overworld_editor.h.
Referenced by CheckForOverworldEdits(), CheckForSelectRectangle(), LoadGraphics(), RefreshTile16Blockset(), and Update().
tile8_individual_data_
std::vector<std::vector<uint8_t> > yaze::app::editor::OverworldEditor::tile8_individual_data_ private
Definition at line 282 of file overworld_editor.h.
tile8_individual_
std::vector<gfx::Bitmap> yaze::app::editor::OverworldEditor::tile8_individual_ private
Definition at line 283 of file overworld_editor.h.
tile16_editor_
Tile16Editor yaze::app::editor::OverworldEditor::tile16_editor_ private
Definition at line 285 of file overworld_editor.h.
Referenced by DrawTile16Selector(), DrawToolset(), and Update().
gfx_group_editor_
GfxGroupEditor yaze::app::editor::OverworldEditor::gfx_group_editor_ private
Definition at line 286 of file overworld_editor.h.
Referenced by DrawOverworldProperties(), and DrawToolset().
palette_editor_
PaletteEditor yaze::app::editor::OverworldEditor::palette_editor_ private
Definition at line 287 of file overworld_editor.h.
palette_
gfx::SnesPalette yaze::app::editor::OverworldEditor::palette_ private
Definition at line 289 of file overworld_editor.h.
Referenced by DrawAreaGraphics(), DrawToolset(), LoadGraphics(), LoadSpriteGraphics(), and RefreshTile16Blockset().
selected_tile_bmp_
gfx::Bitmap yaze::app::editor::OverworldEditor::selected_tile_bmp_ private
Definition at line 291 of file overworld_editor.h.
tile16_blockset_bmp_
gfx::Bitmap yaze::app::editor::OverworldEditor::tile16_blockset_bmp_ private
Definition at line 292 of file overworld_editor.h.
Referenced by DrawTile16Selector(), LoadGraphics(), RefreshTile16Blockset(), and Update().
current_gfx_bmp_
gfx::Bitmap yaze::app::editor::OverworldEditor::current_gfx_bmp_ private
Definition at line 293 of file overworld_editor.h.
Referenced by LoadGraphics(), and Update().
all_gfx_bmp
gfx::Bitmap yaze::app::editor::OverworldEditor::all_gfx_bmp private
Definition at line 294 of file overworld_editor.h.
maps_bmp_
gfx::BitmapTable yaze::app::editor::OverworldEditor::maps_bmp_ private
Definition at line 296 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), DrawOverworldMaps(), DrawToolset(), LoadGraphics(), RefreshChildMap(), RefreshMapPalette(), RefreshOverworldMap(), and RenderUpdatedMapBitmap().
current_graphics_set_
gfx::BitmapTable yaze::app::editor::OverworldEditor::current_graphics_set_ private
Definition at line 297 of file overworld_editor.h.
Referenced by DrawAreaGraphics().
sprite_previews_
gfx::BitmapTable yaze::app::editor::OverworldEditor::sprite_previews_ private
Definition at line 298 of file overworld_editor.h.
Referenced by DrawOverworldSprites(), and LoadSpriteGraphics().
overworld_
zelda3::overworld::Overworld yaze::app::editor::OverworldEditor::overworld_ private
Definition at line 300 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), CheckForOverworldEdits(), CheckForSelectRectangle(), DrawAreaGraphics(), DrawCustomOverworldMapSettings(), DrawDebugWindow(), DrawOverworldCanvas(), DrawOverworldEdits(), DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), DrawOverworldMapSettings(), DrawOverworldProperties(), DrawOverworldSprites(), DrawToolset(), LoadGraphics(), LoadSpriteGraphics(), overworld(), RefreshChildMap(), RefreshMapPalette(), RefreshMapProperties(), RefreshOverworldMap(), RefreshTile16Blockset(), Save(), Update(), and UpdateUsageStats().
refresh_blockset_
zelda3::OWBlockset yaze::app::editor::OverworldEditor::refresh_blockset_ private
Definition at line 301 of file overworld_editor.h.
current_sprite_
zelda3::Sprite yaze::app::editor::OverworldEditor::current_sprite_ private
Definition at line 303 of file overworld_editor.h.
Referenced by DrawOverworldSprites().
current_entrance_
zelda3::overworld::OverworldEntrance yaze::app::editor::OverworldEditor::current_entrance_ private
Definition at line 305 of file overworld_editor.h.
Referenced by DrawOverworldEntrances().
current_exit_
zelda3::overworld::OverworldExit yaze::app::editor::OverworldEditor::current_exit_ private
Definition at line 306 of file overworld_editor.h.
Referenced by DrawOverworldExits().
current_item_
zelda3::overworld::OverworldItem yaze::app::editor::OverworldEditor::current_item_ private
Definition at line 307 of file overworld_editor.h.
Referenced by DrawOverworldItems().
current_entity_
zelda3::GameEntity* yaze::app::editor::OverworldEditor::current_entity_ private
Definition at line 309 of file overworld_editor.h.
Referenced by DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), and DrawOverworldSprites().
dragged_entity_
zelda3::GameEntity* yaze::app::editor::OverworldEditor::dragged_entity_ private
Definition at line 310 of file overworld_editor.h.
Referenced by DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), and DrawOverworldSprites().
ow_map_canvas_
gui::Canvas yaze::app::editor::OverworldEditor::ow_map_canvas_ private
Initial value:
{"OwMap", kOverworldCanvasSize,
                             gui::CanvasGridSize::k64x64}
Definition at line 312 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), CheckForMousePan(), CheckForOverworldEdits(), CheckForSelectRectangle(), DrawDebugWindow(), DrawOverworldCanvas(), DrawOverworldEdits(), DrawOverworldEntrances(), DrawOverworldExits(), DrawOverworldItems(), DrawOverworldMaps(), DrawOverworldSprites(), and DrawToolset().
current_gfx_canvas_
gui::Canvas yaze::app::editor::OverworldEditor::current_gfx_canvas_ private
Initial value:
{"CurrentGfx", kCurrentGfxCanvasSize,
                                  gui::CanvasGridSize::k32x32}
Definition at line 314 of file overworld_editor.h.
Referenced by DrawAreaGraphics().
blockset_canvas_
gui::Canvas yaze::app::editor::OverworldEditor::blockset_canvas_ private
Initial value:
{"OwBlockset", kBlocksetCanvasSize,
                               gui::CanvasGridSize::k32x32}
Definition at line 316 of file overworld_editor.h.
Referenced by CheckForOverworldEdits(), and DrawTile16Selector().
graphics_bin_canvas_
gui::Canvas yaze::app::editor::OverworldEditor::graphics_bin_canvas_ private
Initial value:
{"GraphicsBin", kGraphicsBinCanvasSize,
                                   gui::CanvasGridSize::k16x16}
Definition at line 318 of file overworld_editor.h.
Referenced by DrawTile8Selector().
properties_canvas_
gui::Canvas yaze::app::editor::OverworldEditor::properties_canvas_ private
Definition at line 320 of file overworld_editor.h.
Referenced by DrawOverworldProperties(), and UpdateUsageStats().
layout_node_
gui::zeml::Node yaze::app::editor::OverworldEditor::layout_node_ private
Definition at line 321 of file overworld_editor.h.
Referenced by InitializeZeml(), and Update().
status_
absl::Status yaze::app::editor::OverworldEditor::status_ private
Definition at line 322 of file overworld_editor.h.
Referenced by DrawCustomOverworldMapSettings(), DrawOverworldCanvas(), DrawOverworldMapSettings(), DrawOverworldProperties(), DrawTileSelector(), DrawToolset(), RefreshChildMap(), and Update().
The documentation for this class was generated from the following files:
src/app/editor/overworld/overworld_editor.h
src/app/editor/overworld/overworld_editor.cc