yaze: yaze::app::emu::Clock Class Reference
yaze::app::emu::Clock Class Reference abstract
#include <clock.h>
Public Member Functions
virtual ~Clock ()=default
virtual void UpdateClock (double delta)=0
virtual unsigned long long GetCycleCount () const =0
virtual void ResetAccumulatedTime ()=0
virtual void SetFrequency (float new_frequency)=0
virtual float GetFrequency () const =0
Constructor & Destructor Documentation
~Clock()
virtual yaze::app::emu::Clock::~Clock () virtual default
Member Function Documentation
UpdateClock()
virtual void yaze::app::emu::Clock::UpdateClock (double delta) pure virtual
Implemented in yaze::app::emu::ClockImpl.
Referenced by yaze::app::emu::video::Ppu::UpdateClock(), yaze::app::emu::audio::Apu::UpdateClock(), and yaze::app::emu::Cpu::UpdateClock().
GetCycleCount()
virtual unsigned long long yaze::app::emu::Clock::GetCycleCount () const pure virtual
Implemented in yaze::app::emu::ClockImpl.
Referenced by yaze::app::emu::audio::Apu::Update(), yaze::app::emu::video::Ppu::Update(), and yaze::app::emu::Cpu::Update().
ResetAccumulatedTime()
virtual void yaze::app::emu::Clock::ResetAccumulatedTime () pure virtual
Implemented in yaze::app::emu::ClockImpl.
Referenced by yaze::app::emu::audio::Apu::Reset().
SetFrequency()
virtual void yaze::app::emu::Clock::SetFrequency (float new_frequency) pure virtual
Implemented in yaze::app::emu::ClockImpl.
Referenced by yaze::app::emu::audio::Apu::Init(), yaze::app::emu::video::Ppu::Init(), and yaze::app::emu::Cpu::Init().
GetFrequency()
virtual float yaze::app::emu::Clock::GetFrequency () const pure virtual
Implemented in yaze::app::emu::ClockImpl.
The documentation for this class was generated from the following file:
src/app/emu/cpu/clock.h