yaze: yaze::test::EditorIntegrationTest Class Reference
yaze::test::EditorIntegrationTest Class Reference abstract
Base class for editor integration tests.
#include <editor_integration_test.h>
Public Member Functions
EditorIntegrationTest ()
~EditorIntegrationTest ()
absl::Status Initialize ()
int RunTest ()
virtual void RegisterTests (ImGuiTestEngine *engine)=0
virtual absl::Status Update ()
Protected Member Functions
absl::Status LoadTestRom (const std::string &filename)
absl::Status SaveTestRom (const std::string &filename)
absl::Status TestEditorInitialize (editor::Editor *editor)
absl::Status TestEditorLoad (editor::Editor *editor)
absl::Status TestEditorSave (editor::Editor *editor)
absl::Status TestEditorUpdate (editor::Editor *editor)
absl::Status TestEditorCut (editor::Editor *editor)
absl::Status TestEditorCopy (editor::Editor *editor)
absl::Status TestEditorPaste (editor::Editor *editor)
absl::Status TestEditorUndo (editor::Editor *editor)
absl::Status TestEditorRedo (editor::Editor *editor)
absl::Status TestEditorFind (editor::Editor *editor)
absl::Status TestEditorClear (editor::Editor *editor)
Private Attributes
core::Controller controller_
ImGuiTestEngine * engine_
std::unique_ptr< Rom > test_rom_
bool show_demo_window_
core::Window window_
Detailed Description
Base class for editor integration tests.
This class provides common functionality for testing editors in the application. It sets up the test environment and provides helper methods for ROM operations.
For UI interaction testing, use the ImGui test engine API directly within your test functions:
ImGuiTest* test = IM_REGISTER_TEST(engine, "test_suite", "test_name"); test->TestFunc = [](ImGuiTestContext* ctx) { ctx->SetRef("Window Name"); ctx->ItemClick("Button Name"); };
Definition at line 31 of file editor_integration_test.h.
Constructor & Destructor Documentation
EditorIntegrationTest()
yaze::test::EditorIntegrationTest::EditorIntegrationTest ()
Definition at line 20 of file editor_integration_test.cc.
~EditorIntegrationTest()
yaze::test::EditorIntegrationTest::~EditorIntegrationTest ()
Definition at line 23 of file editor_integration_test.cc.
References engine_.
Member Function Documentation
Initialize()
absl::Status yaze::test::EditorIntegrationTest::Initialize ()
Definition at line 30 of file editor_integration_test.cc.
References yaze::gui::ColorsYaze(), controller_, yaze::core::CreateWindow(), engine_, yaze::core::Renderer::Get(), RegisterTests(), yaze::core::Renderer::renderer(), RETURN_IF_ERROR, yaze::core::Controller::set_active(), yaze::core::Controller::window(), and window_.
Referenced by RunTest().
RunTest()
int yaze::test::EditorIntegrationTest::RunTest ()
Definition at line 61 of file editor_integration_test.cc.
References controller_, yaze::core::Controller::DoRender(), Initialize(), yaze::core::Controller::IsActive(), yaze::core::Controller::OnInput(), and Update().
RegisterTests()
virtual void yaze::test::EditorIntegrationTest::RegisterTests (ImGuiTestEngine * engine) pure virtual
Referenced by Initialize().
Update()
absl::Status yaze::test::EditorIntegrationTest::Update () virtual
Definition at line 83 of file editor_integration_test.cc.
References engine_, and show_demo_window_.
Referenced by RunTest().
LoadTestRom()
absl::Status yaze::test::EditorIntegrationTest::LoadTestRom (const std::string & filename) protected
Definition at line 94 of file editor_integration_test.cc.
References test_rom_.
SaveTestRom()
absl::Status yaze::test::EditorIntegrationTest::SaveTestRom (const std::string & filename) protected
Definition at line 99 of file editor_integration_test.cc.
References yaze::Rom::SaveSettings::backup, yaze::Rom::SaveSettings::filename, yaze::Rom::SaveSettings::save_new, and test_rom_.
TestEditorInitialize()
absl::Status yaze::test::EditorIntegrationTest::TestEditorInitialize (editor::Editor * editor) protected
Definition at line 110 of file editor_integration_test.cc.
References yaze::editor::Editor::Initialize().
TestEditorLoad()
absl::Status yaze::test::EditorIntegrationTest::TestEditorLoad (editor::Editor * editor) protected
Definition at line 118 of file editor_integration_test.cc.
References yaze::editor::Editor::Load().
TestEditorSave()
absl::Status yaze::test::EditorIntegrationTest::TestEditorSave (editor::Editor * editor) protected
Definition at line 125 of file editor_integration_test.cc.
References yaze::editor::Editor::Save().
TestEditorUpdate()
absl::Status yaze::test::EditorIntegrationTest::TestEditorUpdate (editor::Editor * editor) protected
Definition at line 132 of file editor_integration_test.cc.
References yaze::editor::Editor::Update().
TestEditorCut()
absl::Status yaze::test::EditorIntegrationTest::TestEditorCut (editor::Editor * editor) protected
Definition at line 139 of file editor_integration_test.cc.
References yaze::editor::Editor::Cut().
TestEditorCopy()
absl::Status yaze::test::EditorIntegrationTest::TestEditorCopy (editor::Editor * editor) protected
Definition at line 146 of file editor_integration_test.cc.
References yaze::editor::Editor::Copy().
TestEditorPaste()
absl::Status yaze::test::EditorIntegrationTest::TestEditorPaste (editor::Editor * editor) protected
Definition at line 153 of file editor_integration_test.cc.
References yaze::editor::Editor::Paste().
TestEditorUndo()
absl::Status yaze::test::EditorIntegrationTest::TestEditorUndo (editor::Editor * editor) protected
Definition at line 160 of file editor_integration_test.cc.
References yaze::editor::Editor::Undo().
TestEditorRedo()
absl::Status yaze::test::EditorIntegrationTest::TestEditorRedo (editor::Editor * editor) protected
Definition at line 167 of file editor_integration_test.cc.
References yaze::editor::Editor::Redo().
TestEditorFind()
absl::Status yaze::test::EditorIntegrationTest::TestEditorFind (editor::Editor * editor) protected
Definition at line 174 of file editor_integration_test.cc.
References yaze::editor::Editor::Find().
TestEditorClear()
absl::Status yaze::test::EditorIntegrationTest::TestEditorClear (editor::Editor * editor) protected
Definition at line 181 of file editor_integration_test.cc.
References yaze::editor::Editor::Clear().
Member Data Documentation
controller_
core::Controller yaze::test::EditorIntegrationTest::controller_ private
Definition at line 68 of file editor_integration_test.h.
Referenced by Initialize(), and RunTest().
engine_
ImGuiTestEngine* yaze::test::EditorIntegrationTest::engine_ private
Definition at line 69 of file editor_integration_test.h.
Referenced by Initialize(), Update(), and ~EditorIntegrationTest().
test_rom_
std::unique_ptr<Rom> yaze::test::EditorIntegrationTest::test_rom_ private
Definition at line 70 of file editor_integration_test.h.
Referenced by LoadTestRom(), and SaveTestRom().
show_demo_window_
bool yaze::test::EditorIntegrationTest::show_demo_window_ private
Definition at line 71 of file editor_integration_test.h.
Referenced by Update().
window_
core::Window yaze::test::EditorIntegrationTest::window_ private
Definition at line 72 of file editor_integration_test.h.
Referenced by Initialize().
The documentation for this class was generated from the following files:
test/editor/editor_integration_test.h
test/editor/editor_integration_test.cc