yaze: yaze::app::editor::Editor Class Reference
yaze::app::editor::Editor Class Reference abstract
Interface for editor classes.
#include <editor.h>
Public Member Functions
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Cut ()=0
virtual absl::Status Copy ()=0
virtual absl::Status Paste ()=0
virtual absl::Status Undo ()=0
virtual absl::Status Redo ()=0
virtual absl::Status Update ()=0
virtual absl::Status Find ()=0
EditorType type () const
Protected Attributes
EditorType type_
Detailed Description
Interface for editor classes.
Provides basic editing operations that each editor should implement.
Definition at line 39 of file editor.h.
Constructor & Destructor Documentation
Editor()
yaze::app::editor::Editor::Editor () default
~Editor()
virtual yaze::app::editor::Editor::~Editor () virtual default
Member Function Documentation
Cut()
virtual absl::Status yaze::app::editor::Editor::Cut () pure virtual
Implemented in yaze::app::editor::AssemblyEditor, yaze::app::editor::DungeonEditor, yaze::app::editor::GraphicsEditor, yaze::app::editor::MessageEditor, yaze::app::editor::MusicEditor, yaze::app::editor::OverworldEditor, yaze::app::editor::PaletteEditor, yaze::app::editor::ScreenEditor, yaze::app::editor::SettingsEditor, yaze::app::editor::SpriteEditor, and yaze::test::integration::TestEditor.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
Copy()
virtual absl::Status yaze::app::editor::Editor::Copy () pure virtual
Implemented in yaze::app::editor::AssemblyEditor, yaze::app::editor::DungeonEditor, yaze::app::editor::GraphicsEditor, yaze::app::editor::MessageEditor, yaze::app::editor::MusicEditor, yaze::app::editor::OverworldEditor, yaze::app::editor::PaletteEditor, yaze::app::editor::ScreenEditor, yaze::app::editor::SettingsEditor, yaze::app::editor::SpriteEditor, and yaze::test::integration::TestEditor.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
Paste()
virtual absl::Status yaze::app::editor::Editor::Paste () pure virtual
Implemented in yaze::app::editor::AssemblyEditor, yaze::app::editor::DungeonEditor, yaze::app::editor::GraphicsEditor, yaze::app::editor::MessageEditor, yaze::app::editor::MusicEditor, yaze::app::editor::OverworldEditor, yaze::app::editor::PaletteEditor, yaze::app::editor::ScreenEditor, yaze::app::editor::SettingsEditor, yaze::app::editor::SpriteEditor, and yaze::test::integration::TestEditor.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
Undo()
virtual absl::Status yaze::app::editor::Editor::Undo () pure virtual
Implemented in yaze::app::editor::AssemblyEditor, yaze::app::editor::DungeonEditor, yaze::app::editor::GraphicsEditor, yaze::app::editor::MessageEditor, yaze::app::editor::MusicEditor, yaze::app::editor::OverworldEditor, yaze::app::editor::PaletteEditor, yaze::app::editor::ScreenEditor, yaze::app::editor::SettingsEditor, yaze::app::editor::SpriteEditor, and yaze::test::integration::TestEditor.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
Redo()
virtual absl::Status yaze::app::editor::Editor::Redo () pure virtual
Implemented in yaze::app::editor::AssemblyEditor, yaze::app::editor::DungeonEditor, yaze::app::editor::GraphicsEditor, yaze::app::editor::MessageEditor, yaze::app::editor::MusicEditor, yaze::app::editor::OverworldEditor, yaze::app::editor::PaletteEditor, yaze::app::editor::ScreenEditor, yaze::app::editor::SettingsEditor, yaze::app::editor::SpriteEditor, and yaze::test::integration::TestEditor.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
Update()
virtual absl::Status yaze::app::editor::Editor::Update () pure virtual
Implemented in yaze::app::editor::AssemblyEditor, yaze::app::editor::DungeonEditor, yaze::app::editor::GraphicsEditor, yaze::app::editor::MessageEditor, yaze::app::editor::MusicEditor, yaze::app::editor::OverworldEditor, yaze::app::editor::PaletteEditor, yaze::app::editor::ScreenEditor, yaze::app::editor::SettingsEditor, yaze::app::editor::SpriteEditor, and yaze::test::integration::TestEditor.
Referenced by yaze::app::core::Controller::OnTestLoad().
Find()
virtual absl::Status yaze::app::editor::Editor::Find () pure virtual
Implemented in yaze::app::editor::AssemblyEditor, yaze::app::editor::DungeonEditor, yaze::app::editor::GraphicsEditor, yaze::app::editor::MessageEditor, yaze::app::editor::MusicEditor, yaze::app::editor::OverworldEditor, yaze::app::editor::PaletteEditor, yaze::app::editor::ScreenEditor, yaze::app::editor::SettingsEditor, yaze::app::editor::SpriteEditor, and yaze::test::integration::TestEditor.
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
type()
EditorType yaze::app::editor::Editor::type () const inline
Definition at line 55 of file editor.h.
References type_.
Member Data Documentation
type_
EditorType yaze::app::editor::Editor::type_ protected
Definition at line 58 of file editor.h.
Referenced by yaze::app::editor::AssemblyEditor::AssemblyEditor(), yaze::app::editor::DungeonEditor::DungeonEditor(), yaze::app::editor::GraphicsEditor::GraphicsEditor(), yaze::app::editor::MessageEditor::MessageEditor(), yaze::app::editor::MusicEditor::MusicEditor(), yaze::app::editor::OverworldEditor::OverworldEditor(), yaze::app::editor::PaletteEditor::PaletteEditor(), yaze::app::editor::ScreenEditor::ScreenEditor(), yaze::app::editor::SettingsEditor::SettingsEditor(), yaze::app::editor::SpriteEditor::SpriteEditor(), and type().
The documentation for this class was generated from the following file:
src/app/editor/utils/editor.h