yaze: yaze::zelda3::overworld::Overworld Class Reference
yaze::zelda3::overworld::Overworld Class Reference
Represents the full Overworld data, light and dark world.
#include <overworld.h>
Public Member Functions
absl::Status Load (Rom &rom)
absl::Status LoadOverworldMaps ()
void LoadTileTypes ()
void LoadEntrances ()
absl::Status LoadExits ()
absl::Status LoadItems ()
absl::Status LoadSprites ()
absl::Status LoadSpritesFromMap (int spriteStart, int spriteCount, int spriteIndex)
absl::Status Save (Rom &rom)
absl::Status SaveOverworldMaps ()
absl::Status SaveLargeMaps ()
absl::Status SaveEntrances ()
absl::Status SaveExits ()
absl::Status SaveItems ()
absl::Status CreateTile32Tilemap ()
absl::Status SaveMap16Expanded ()
absl::Status SaveMap16Tiles ()
absl::Status SaveMap32Expanded ()
absl::Status SaveMap32Tiles ()
absl::Status SaveMapProperties ()
void Destroy ()
int GetTileFromPosition (ImVec2 position) const
OWBlockset & GetMapTiles (int world_type)
auto overworld_maps () const
auto overworld_map (int i) const
auto mutable_overworld_map (int i)
auto exits () const
auto mutable_exits ()
std::vector< gfx::Tile16 > tiles16 () const
auto mutable_tiles16 ()
auto sprites (int state) const
auto mutable_sprites (int state)
auto current_graphics () const
auto & entrances ()
auto mutable_entrances ()
auto & holes ()
auto mutable_holes ()
auto deleted_entrances () const
auto mutable_deleted_entrances ()
auto current_area_palette () const
auto current_map_bitmap_data () const
auto tile16_blockset_data () const
auto is_loaded () const
void set_current_map (int i)
auto map_tiles () const
auto mutable_map_tiles ()
auto all_items () const
auto mutable_all_items ()
auto all_tiles_types () const
auto mutable_all_tiles_types ()
Public Member Functions inherited from yaze::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Public Member Functions inherited from yaze::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
std::string Serialize () const
Private Types
enum Dimension { map32TilesTL = 0 , map32TilesTR = 1 , map32TilesBL = 2 , map32TilesBR = 3 }
Private Member Functions
void FetchLargeMaps ()
absl::StatusOr< uint16_t > GetTile16ForTile32 (int index, int quadrant, int dimension, const uint32_t *map32address)
absl::Status AssembleMap32Tiles ()
void AssembleMap16Tiles ()
void AssignWorldTiles (int x, int y, int sx, int sy, int tpos, OWBlockset &world)
void OrganizeMapTiles (std::vector< uint8_t > &bytes, std::vector< uint8_t > &bytes2, int i, int sx, int sy, int &ttpos)
absl::Status DecompressAllMapTiles ()
Private Attributes
bool is_loaded_ = false
bool expanded_tile16_ = false
bool expanded_tile32_ = false
bool expanded_entrances_ = false
int game_state_ = 0
int current_map_ = 0
int current_world_ = 0
uchar map_parent_ [160]
Rom rom_
OWMapTiles map_tiles_
uint8_t all_tiles_types_ [0x200]
std::vector< gfx::Tile16 > tiles16_
std::vector< gfx::Tile32 > tiles32_
std::vector< uint16_t > tiles32_list_
std::vector< gfx::Tile32 > tiles32_unique_
std::vector< OverworldMap > overworld_maps_
std::vector< OverworldEntrance > all_entrances_
std::vector< OverworldEntrance > all_holes_
std::vector< OverworldExit > all_exits_
std::vector< OverworldItem > all_items_
std::vector< std::vector< Sprite > > all_sprites_
std::vector< uint64_t > deleted_entrances_
std::vector< std::vector< uint8_t > > map_data_p1
std::vector< std::vector< uint8_t > > map_data_p2
std::vector< int > map_pointers1_id = std::vector<int>(kNumOverworldMaps)
std::vector< int > map_pointers2_id = std::vector<int>(kNumOverworldMaps)
std::vector< int > map_pointers1 = std::vector<int>(kNumOverworldMaps)
std::vector< int > map_pointers2 = std::vector<int>(kNumOverworldMaps)
std::vector< absl::flat_hash_map< uint16_t, int > > usage_stats_
Additional Inherited Members
Static Public Attributes inherited from yaze::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
Represents the full Overworld data, light and dark world.
This class is responsible for loading and saving the overworld data, as well as creating the tilesets and tilemaps for the overworld.
Definition at line 115 of file overworld.h.
Member Enumeration Documentation
Dimension
enum yaze::zelda3::overworld::Overworld::Dimension private
Enumerator
map32TilesTL
map32TilesTR
map32TilesBL
map32TilesBR
Definition at line 215 of file overworld.h.
Member Function Documentation
Load()
absl::Status yaze::zelda3::overworld::Overworld::Load (Rom & rom)
Definition at line 18 of file overworld.cc.
References AssembleMap16Tiles(), AssembleMap32Tiles(), DecompressAllMapTiles(), FetchLargeMaps(), yaze::core::ExperimentFlags::flags(), is_loaded_, yaze::zelda3::overworld::kNumOverworldMaps, LoadEntrances(), LoadExits(), LoadItems(), LoadOverworldMaps(), LoadSprites(), overworld_maps_, RETURN_IF_ERROR, yaze::SharedRom::rom(), and rom_.
Referenced by yaze::editor::OverworldEditor::LoadGraphics(), and yaze::editor::Tile16Editor::UpdateTransferTileCanvas().
LoadOverworldMaps()
absl::Status yaze::zelda3::overworld::Overworld::LoadOverworldMaps ()
Definition at line 272 of file overworld.cc.
References game_state_, GetMapTiles(), yaze::zelda3::overworld::kNumOverworldMaps, overworld_maps_, and tiles16_.
Referenced by Load().
LoadTileTypes()
void yaze::zelda3::overworld::Overworld::LoadTileTypes ()
Definition at line 299 of file overworld.cc.
References all_tiles_types_, and yaze::SharedRom::rom().
LoadEntrances()
void yaze::zelda3::overworld::Overworld::LoadEntrances ()
Definition at line 306 of file overworld.cc.
References all_entrances_, all_holes_, expanded_entrances_, yaze::zelda3::overworld::OWEntranceEntranceId, yaze::zelda3::overworld::OWEntranceMap, yaze::zelda3::overworld::OWEntrancePos, yaze::zelda3::overworld::OWHoleArea, yaze::zelda3::overworld::OWHoleEntrance, yaze::zelda3::overworld::OWHolePos, yaze::SharedRom::rom(), and rom_.
Referenced by Load().
LoadExits()
absl::Status yaze::zelda3::overworld::Overworld::LoadExits ()
Definition at line 351 of file overworld.cc.
References all_exits_, exits(), yaze::core::ExperimentFlags::flags(), yaze::zelda3::overworld::OWExitDoorType1, yaze::zelda3::overworld::OWExitDoorType2, yaze::zelda3::overworld::OWExitMapId, yaze::zelda3::overworld::OWExitRoomId, yaze::zelda3::overworld::OWExitUnk1, yaze::zelda3::overworld::OWExitUnk2, yaze::zelda3::overworld::OWExitVram, yaze::zelda3::overworld::OWExitXCamera, yaze::zelda3::overworld::OWExitXPlayer, yaze::zelda3::overworld::OWExitXScroll, yaze::zelda3::overworld::OWExitYCamera, yaze::zelda3::overworld::OWExitYPlayer, yaze::zelda3::overworld::OWExitYScroll, RETURN_IF_ERROR, and yaze::SharedRom::rom().
Referenced by Load().
LoadItems()
absl::Status yaze::zelda3::overworld::Overworld::LoadItems ()
Definition at line 408 of file overworld.cc.
References all_items_, ASSIGN_OR_RETURN, yaze::zelda3::overworld::kOverworldItemsAddress, overworld_maps_, yaze::SharedRom::rom(), and yaze::core::SnesToPc().
Referenced by Load().
LoadSprites()
absl::Status yaze::zelda3::overworld::Overworld::LoadSprites ()
Definition at line 458 of file overworld.cc.
References all_sprites_, LoadSpritesFromMap(), yaze::zelda3::overworld::overworldSpritesAgahnim, yaze::zelda3::overworld::overworldSpritesBegining, yaze::zelda3::overworld::overworldSpritesZelda, and RETURN_IF_ERROR.
Referenced by Load().
LoadSpritesFromMap()
absl::Status yaze::zelda3::overworld::Overworld::LoadSpritesFromMap (int spriteStart, int spriteCount, int spriteIndex)
Definition at line 469 of file overworld.cc.
References all_sprites_, ASSIGN_OR_RETURN, map_parent_, overworld_maps_, yaze::SharedRom::rom(), and yaze::core::SnesToPc().
Referenced by LoadSprites().
Save()
absl::Status yaze::zelda3::overworld::Overworld::Save (Rom & rom)
Definition at line 511 of file overworld.cc.
References expanded_tile16_, expanded_tile32_, RETURN_IF_ERROR, yaze::SharedRom::rom(), rom_, SaveEntrances(), SaveExits(), SaveMap16Expanded(), SaveMap16Tiles(), SaveMap32Expanded(), SaveMap32Tiles(), and SaveOverworldMaps().
SaveOverworldMaps()
absl::Status yaze::zelda3::overworld::Overworld::SaveOverworldMaps ()
Definition at line 523 of file overworld.cc.
References yaze::gfx::lc_lz2::Compress(), yaze::core::Logger::log(), map_data_p1, map_data_p2, map_pointers1, map_pointers1_id, map_pointers2, map_pointers2_id, yaze::zelda3::overworld::OverworldMapDataOverflow, yaze::core::PcToSnes(), RETURN_IF_ERROR, yaze::SharedRom::rom(), SaveLargeMaps(), tiles32_list_, yaze::core::UppercaseHexByte(), and yaze::core::UppercaseHexLong().
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveLargeMaps()
absl::Status yaze::zelda3::overworld::Overworld::SaveLargeMaps ()
Definition at line 680 of file overworld.cc.
References yaze::core::Logger::log(), overworld_maps_, yaze::zelda3::overworld::overworldMapParentId, yaze::zelda3::overworld::overworldMapSize, yaze::zelda3::overworld::overworldMapSizeHighByte, yaze::zelda3::overworld::overworldScreenSize, yaze::zelda3::overworld::OverworldScreenSizeForLoading, yaze::zelda3::overworld::OverworldScreenTileMapChangeByScreen1, yaze::zelda3::overworld::OverworldScreenTileMapChangeByScreen2, yaze::zelda3::overworld::OverworldScreenTileMapChangeByScreen3, yaze::zelda3::overworld::OverworldScreenTileMapChangeByScreen4, yaze::zelda3::overworld::overworldTransitionPositionX, yaze::zelda3::overworld::overworldTransitionPositionY, RETURN_IF_ERROR, yaze::SharedRom::rom(), yaze::zelda3::overworld::transition_target_north, and yaze::zelda3::overworld::transition_target_west.
Referenced by SaveOverworldMaps().
SaveEntrances()
absl::Status yaze::zelda3::overworld::Overworld::SaveEntrances ()
Definition at line 1378 of file overworld.cc.
References all_entrances_, all_holes_, yaze::core::Logger::log(), yaze::zelda3::overworld::OWEntranceEntranceId, yaze::zelda3::overworld::OWEntranceMap, yaze::zelda3::overworld::OWEntrancePos, yaze::zelda3::overworld::OWHoleArea, yaze::zelda3::overworld::OWHoleEntrance, yaze::zelda3::overworld::OWHolePos, RETURN_IF_ERROR, and yaze::SharedRom::rom().
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveExits()
absl::Status yaze::zelda3::overworld::Overworld::SaveExits ()
Definition at line 1401 of file overworld.cc.
References all_exits_, yaze::core::Logger::log(), yaze::zelda3::overworld::OWExitDoorType1, yaze::zelda3::overworld::OWExitDoorType2, yaze::zelda3::overworld::OWExitMapId, yaze::zelda3::overworld::OWExitRoomId, yaze::zelda3::overworld::OWExitUnk1, yaze::zelda3::overworld::OWExitUnk2, yaze::zelda3::overworld::OWExitVram, yaze::zelda3::overworld::OWExitXCamera, yaze::zelda3::overworld::OWExitXPlayer, yaze::zelda3::overworld::OWExitXScroll, yaze::zelda3::overworld::OWExitYCamera, yaze::zelda3::overworld::OWExitYPlayer, yaze::zelda3::overworld::OWExitYScroll, RETURN_IF_ERROR, and yaze::SharedRom::rom().
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveItems()
absl::Status yaze::zelda3::overworld::Overworld::SaveItems ()
Definition at line 1465 of file overworld.cc.
References all_items_, yaze::core::ExperimentFlags::flags(), yaze::zelda3::overworld::overworldItemsEndData, yaze::zelda3::overworld::overworldItemsPointers, yaze::core::PcToSnes(), RETURN_IF_ERROR, and yaze::SharedRom::rom().
Referenced by yaze::editor::OverworldEditor::Save().
CreateTile32Tilemap()
absl::Status yaze::zelda3::overworld::Overworld::CreateTile32Tilemap ()
Definition at line 1039 of file overworld.cc.
References yaze::core::ExperimentFlags::flags(), yaze::gfx::Tile32::GetPackedValue(), yaze::zelda3::overworld::LimitOfMap32, map_tiles_, yaze::zelda3::overworld::NumberOfMap32, tiles32_list_, and tiles32_unique_.
Referenced by yaze::editor::OverworldEditor::Save().
SaveMap16Expanded()
absl::Status yaze::zelda3::overworld::Overworld::SaveMap16Expanded ()
Definition at line 1279 of file overworld.cc.
References yaze::zelda3::overworld::kMap16TilesExpanded, yaze::core::PcToSnes(), RETURN_IF_ERROR, yaze::SharedRom::rom(), and yaze::core::SnesToPc().
Referenced by Save().
SaveMap16Tiles()
absl::Status yaze::zelda3::overworld::Overworld::SaveMap16Tiles ()
Definition at line 1357 of file overworld.cc.
References yaze::zelda3::overworld::kMap16Tiles, yaze::core::Logger::log(), yaze::zelda3::overworld::NumberOfMap16, RETURN_IF_ERROR, yaze::SharedRom::rom(), and tiles16_.
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveMap32Expanded()
absl::Status yaze::zelda3::overworld::Overworld::SaveMap32Expanded ()
Definition at line 1099 of file overworld.cc.
References yaze::zelda3::overworld::kMap32TileBLExpanded, yaze::zelda3::overworld::kMap32TileBRExpanded, yaze::zelda3::overworld::kMap32TileTRExpanded, yaze::core::PcToSnes(), RETURN_IF_ERROR, and yaze::SharedRom::rom().
Referenced by Save().
SaveMap32Tiles()
absl::Status yaze::zelda3::overworld::Overworld::SaveMap32Tiles ()
Definition at line 1150 of file overworld.cc.
References yaze::core::Logger::log(), map32TilesBL, map32TilesBR, RETURN_IF_ERROR, yaze::SharedRom::rom(), and tiles32_unique_.
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveMapProperties()
absl::Status yaze::zelda3::overworld::Overworld::SaveMapProperties ()
Definition at line 1546 of file overworld.cc.
References yaze::zelda3::overworld::kAreaGfxIdPtr, yaze::zelda3::overworld::kOverworldMapPaletteIds, yaze::zelda3::overworld::kOverworldSpritePaletteIds, yaze::core::Logger::log(), overworld_maps_, yaze::zelda3::overworld::overworldSpriteset, RETURN_IF_ERROR, and yaze::SharedRom::rom().
Referenced by yaze::editor::OverworldEditor::Save().
Destroy()
void yaze::zelda3::overworld::Overworld::Destroy () inline
Definition at line 143 of file overworld.h.
References all_entrances_, all_exits_, all_items_, all_sprites_, is_loaded_, and overworld_maps_.
GetTileFromPosition()
int yaze::zelda3::overworld::Overworld::GetTileFromPosition (ImVec2 position) const inline
Definition at line 155 of file overworld.h.
References current_world_, yaze::zelda3::OWMapTiles::dark_world, yaze::zelda3::OWMapTiles::light_world, map_tiles_, and yaze::zelda3::OWMapTiles::special_world.
Referenced by yaze::editor::OverworldEditor::CheckForOverworldEdits(), and yaze::editor::OverworldEditor::CheckForSelectRectangle().
GetMapTiles()
OWBlockset & yaze::zelda3::overworld::Overworld::GetMapTiles (int world_type) inline
Definition at line 165 of file overworld.h.
References yaze::zelda3::OWMapTiles::dark_world, yaze::zelda3::OWMapTiles::light_world, map_tiles_, and yaze::zelda3::OWMapTiles::special_world.
Referenced by LoadOverworldMaps(), and yaze::editor::OverworldEditor::RefreshChildMap().
overworld_maps()
auto yaze::zelda3::overworld::Overworld::overworld_maps () const inline
Definition at line 178 of file overworld.h.
References overworld_maps_.
overworld_map()
auto yaze::zelda3::overworld::Overworld::overworld_map (int i) const inline
Definition at line 179 of file overworld.h.
References overworld_maps_.
Referenced by yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::OverworldEditor::DrawOverworldProperties(), yaze::editor::OverworldEditor::RefreshMapPalette(), yaze::editor::OverworldEditor::RefreshOverworldMap(), and yaze::editor::OverworldEditor::RefreshTile16Blockset().
mutable_overworld_map()
auto yaze::zelda3::overworld::Overworld::mutable_overworld_map (int i) inline
Definition at line 180 of file overworld.h.
References overworld_maps_.
Referenced by yaze::editor::OverworldEditor::DrawCustomOverworldMapSettings(), yaze::editor::OverworldEditor::DrawOverworldMapSettings(), yaze::editor::OverworldEditor::RefreshChildMap(), yaze::editor::OverworldEditor::RefreshMapPalette(), and yaze::editor::OverworldEditor::RefreshMapProperties().
exits()
auto yaze::zelda3::overworld::Overworld::exits () const inline
Definition at line 181 of file overworld.h.
References all_exits_.
Referenced by LoadExits().
mutable_exits()
auto yaze::zelda3::overworld::Overworld::mutable_exits () inline
Definition at line 182 of file overworld.h.
References all_exits_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldExits().
tiles16()
std::vector< gfx::Tile16 > yaze::zelda3::overworld::Overworld::tiles16 () const inline
Definition at line 183 of file overworld.h.
References tiles16_.
Referenced by yaze::editor::OverworldEditor::RefreshChildMap().
mutable_tiles16()
auto yaze::zelda3::overworld::Overworld::mutable_tiles16 () inline
Definition at line 184 of file overworld.h.
References tiles16_.
Referenced by yaze::editor::OverworldEditor::RefreshChildMap().
sprites()
auto yaze::zelda3::overworld::Overworld::sprites (int state) const inline
Definition at line 185 of file overworld.h.
References all_sprites_.
Referenced by yaze::editor::OverworldEditor::LoadSpriteGraphics().
mutable_sprites()
auto yaze::zelda3::overworld::Overworld::mutable_sprites (int state) inline
Definition at line 186 of file overworld.h.
References all_sprites_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldSprites().
current_graphics()
auto yaze::zelda3::overworld::Overworld::current_graphics () const inline
Definition at line 187 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), and yaze::editor::OverworldEditor::LoadGraphics().
entrances()
auto & yaze::zelda3::overworld::Overworld::entrances () inline
Definition at line 190 of file overworld.h.
References all_entrances_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldEntrances(), and yaze::editor::OverworldEditor::UpdateUsageStats().
mutable_entrances()
auto yaze::zelda3::overworld::Overworld::mutable_entrances () inline
Definition at line 191 of file overworld.h.
References all_entrances_.
holes()
auto & yaze::zelda3::overworld::Overworld::holes () inline
Definition at line 192 of file overworld.h.
References all_holes_.
mutable_holes()
auto yaze::zelda3::overworld::Overworld::mutable_holes () inline
Definition at line 193 of file overworld.h.
References all_holes_.
deleted_entrances()
auto yaze::zelda3::overworld::Overworld::deleted_entrances () const inline
Definition at line 194 of file overworld.h.
References deleted_entrances_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldEntrances().
mutable_deleted_entrances()
auto yaze::zelda3::overworld::Overworld::mutable_deleted_entrances () inline
Definition at line 195 of file overworld.h.
References deleted_entrances_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldEntrances().
current_area_palette()
auto yaze::zelda3::overworld::Overworld::current_area_palette () const inline
Definition at line 196 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldEditor::RefreshMapPalette(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), and yaze::editor::Tile16Editor::UpdateTransferTileCanvas().
current_map_bitmap_data()
auto yaze::zelda3::overworld::Overworld::current_map_bitmap_data () const inline
Definition at line 199 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::LoadGraphics().
tile16_blockset_data()
auto yaze::zelda3::overworld::Overworld::tile16_blockset_data () const inline
Definition at line 202 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), and yaze::editor::Tile16Editor::UpdateTransferTileCanvas().
is_loaded()
auto yaze::zelda3::overworld::Overworld::is_loaded () const inline
Definition at line 205 of file overworld.h.
References is_loaded_.
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::OverworldEditor::DrawOverworldCanvas(), and yaze::editor::OverworldEditor::DrawToolset().
set_current_map()
void yaze::zelda3::overworld::Overworld::set_current_map (int i) inline
Definition at line 206 of file overworld.h.
References current_map_.
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), and yaze::editor::Tile16Editor::UpdateTransferTileCanvas().
map_tiles()
auto yaze::zelda3::overworld::Overworld::map_tiles () const inline
Definition at line 207 of file overworld.h.
References map_tiles_.
mutable_map_tiles()
auto yaze::zelda3::overworld::Overworld::mutable_map_tiles () inline
Definition at line 208 of file overworld.h.
References map_tiles_.
Referenced by yaze::editor::OverworldEditor::CheckForOverworldEdits(), yaze::editor::OverworldEditor::DrawDebugWindow(), and yaze::editor::OverworldEditor::DrawOverworldEdits().
all_items()
auto yaze::zelda3::overworld::Overworld::all_items () const inline
Definition at line 209 of file overworld.h.
References all_items_.
mutable_all_items()
auto yaze::zelda3::overworld::Overworld::mutable_all_items () inline
Definition at line 210 of file overworld.h.
References all_items_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldItems().
all_tiles_types()
auto yaze::zelda3::overworld::Overworld::all_tiles_types () const inline
Definition at line 211 of file overworld.h.
References all_tiles_types_.
mutable_all_tiles_types()
auto yaze::zelda3::overworld::Overworld::mutable_all_tiles_types () inline
Definition at line 212 of file overworld.h.
References all_tiles_types_.
Referenced by yaze::editor::OverworldEditor::Update().
FetchLargeMaps()
void yaze::zelda3::overworld::Overworld::FetchLargeMaps () private
Definition at line 40 of file overworld.cc.
References overworld_maps_.
Referenced by Load().
GetTile16ForTile32()
absl::StatusOr< uint16_t > yaze::zelda3::overworld::Overworld::GetTile16ForTile32 (int index, int quadrant, int dimension, const uint32_t * map32address) private
Definition at line 95 of file overworld.cc.
References ASSIGN_OR_RETURN, yaze::Rom::ReadByte(), yaze::Rom::ReadWord(), and rom_.
Referenced by AssembleMap32Tiles().
AssembleMap32Tiles()
absl::Status yaze::zelda3::overworld::Overworld::AssembleMap32Tiles () private
Definition at line 107 of file overworld.cc.
References ASSIGN_OR_RETURN, yaze::zelda3::OWMapTiles::dark_world, expanded_tile32_, GetTile16ForTile32(), yaze::VersionConstants::kMap32TileBL, yaze::zelda3::overworld::kMap32TileBLExpanded, yaze::VersionConstants::kMap32TileBR, yaze::zelda3::overworld::kMap32TileBRExpanded, yaze::zelda3::overworld::kMap32TileCountExpanded, yaze::zelda3::overworld::kMap32TilesLength, yaze::VersionConstants::kMap32TileTL, yaze::VersionConstants::kMap32TileTR, yaze::zelda3::overworld::kMap32TileTRExpanded, yaze::zelda3::OWMapTiles::light_world, map32TilesBL, map32TilesBR, map32TilesTL, map32TilesTR, map_tiles_, yaze::SharedRom::rom(), rom_, yaze::zelda3::OWMapTiles::special_world, tiles32_unique_, and yaze::Rom::version_constants().
Referenced by Load().
AssembleMap16Tiles()
void yaze::zelda3::overworld::Overworld::AssembleMap16Tiles () private
Definition at line 158 of file overworld.cc.
References expanded_tile16_, yaze::gfx::GetTilesInfo(), yaze::zelda3::overworld::kMap16Tiles, yaze::zelda3::overworld::kMap16TilesExpanded, yaze::zelda3::overworld::kNumTile16Individual, yaze::zelda3::overworld::NumberOfMap16Ex, yaze::SharedRom::rom(), and tiles16_.
Referenced by Load().
AssignWorldTiles()
void yaze::zelda3::overworld::Overworld::AssignWorldTiles (int x, int y, int sx, int sy, int tpos, OWBlockset & world) private
Definition at line 180 of file overworld.cc.
References tiles32_unique_.
Referenced by OrganizeMapTiles().
OrganizeMapTiles()
void yaze::zelda3::overworld::Overworld::OrganizeMapTiles (std::vector< uint8_t > & bytes, std::vector< uint8_t > & bytes2, int i, int sx, int sy, int & ttpos) private
Definition at line 192 of file overworld.cc.
References AssignWorldTiles(), yaze::zelda3::OWMapTiles::dark_world, yaze::zelda3::OWMapTiles::light_world, map_tiles_, yaze::zelda3::OWMapTiles::special_world, and tiles32_unique_.
Referenced by DecompressAllMapTiles().
DecompressAllMapTiles()
absl::Status yaze::zelda3::overworld::Overworld::DecompressAllMapTiles () private
Definition at line 212 of file overworld.cc.
References OrganizeMapTiles(), yaze::SharedRom::rom(), yaze::core::SnesToPc(), and yaze::gfx::lc_lz2::Uncompress().
Referenced by Load().
Member Data Documentation
is_loaded_
bool yaze::zelda3::overworld::Overworld::is_loaded_ = false private
Definition at line 235 of file overworld.h.
Referenced by Destroy(), is_loaded(), and Load().
expanded_tile16_
bool yaze::zelda3::overworld::Overworld::expanded_tile16_ = false private
Definition at line 236 of file overworld.h.
Referenced by AssembleMap16Tiles(), and Save().
expanded_tile32_
bool yaze::zelda3::overworld::Overworld::expanded_tile32_ = false private
Definition at line 237 of file overworld.h.
Referenced by AssembleMap32Tiles(), and Save().
expanded_entrances_
bool yaze::zelda3::overworld::Overworld::expanded_entrances_ = false private
Definition at line 238 of file overworld.h.
Referenced by LoadEntrances().
game_state_
int yaze::zelda3::overworld::Overworld::game_state_ = 0 private
Definition at line 240 of file overworld.h.
Referenced by LoadOverworldMaps().
current_map_
int yaze::zelda3::overworld::Overworld::current_map_ = 0 private
Definition at line 241 of file overworld.h.
Referenced by current_area_palette(), current_graphics(), current_map_bitmap_data(), set_current_map(), and tile16_blockset_data().
current_world_
int yaze::zelda3::overworld::Overworld::current_world_ = 0 private
Definition at line 242 of file overworld.h.
Referenced by GetTileFromPosition().
map_parent_
uchar yaze::zelda3::overworld::Overworld::map_parent_[160] private
Definition at line 243 of file overworld.h.
Referenced by LoadSpritesFromMap().
rom_
Rom yaze::zelda3::overworld::Overworld::rom_ private
Definition at line 245 of file overworld.h.
Referenced by AssembleMap32Tiles(), GetTile16ForTile32(), Load(), LoadEntrances(), and Save().
map_tiles_
OWMapTiles yaze::zelda3::overworld::Overworld::map_tiles_ private
Definition at line 246 of file overworld.h.
Referenced by AssembleMap32Tiles(), CreateTile32Tilemap(), GetMapTiles(), GetTileFromPosition(), map_tiles(), mutable_map_tiles(), and OrganizeMapTiles().
all_tiles_types_
uint8_t yaze::zelda3::overworld::Overworld::all_tiles_types_[0x200] private
Definition at line 248 of file overworld.h.
Referenced by all_tiles_types(), LoadTileTypes(), and mutable_all_tiles_types().
tiles16_
std::vector<gfx::Tile16> yaze::zelda3::overworld::Overworld::tiles16_ private
Definition at line 250 of file overworld.h.
Referenced by AssembleMap16Tiles(), LoadOverworldMaps(), mutable_tiles16(), SaveMap16Tiles(), and tiles16().
tiles32_
std::vector<gfx::Tile32> yaze::zelda3::overworld::Overworld::tiles32_ private
Definition at line 251 of file overworld.h.
tiles32_list_
std::vector<uint16_t> yaze::zelda3::overworld::Overworld::tiles32_list_ private
Definition at line 252 of file overworld.h.
Referenced by CreateTile32Tilemap(), and SaveOverworldMaps().
tiles32_unique_
std::vector<gfx::Tile32> yaze::zelda3::overworld::Overworld::tiles32_unique_ private
Definition at line 253 of file overworld.h.
Referenced by AssembleMap32Tiles(), AssignWorldTiles(), CreateTile32Tilemap(), OrganizeMapTiles(), and SaveMap32Tiles().
overworld_maps_
std::vector<OverworldMap> yaze::zelda3::overworld::Overworld::overworld_maps_ private
Definition at line 254 of file overworld.h.
Referenced by current_area_palette(), current_graphics(), current_map_bitmap_data(), Destroy(), FetchLargeMaps(), Load(), LoadItems(), LoadOverworldMaps(), LoadSpritesFromMap(), mutable_overworld_map(), overworld_map(), overworld_maps(), SaveLargeMaps(), SaveMapProperties(), and tile16_blockset_data().
all_entrances_
std::vector<OverworldEntrance> yaze::zelda3::overworld::Overworld::all_entrances_ private
Definition at line 255 of file overworld.h.
Referenced by Destroy(), entrances(), LoadEntrances(), mutable_entrances(), and SaveEntrances().
all_holes_
std::vector<OverworldEntrance> yaze::zelda3::overworld::Overworld::all_holes_ private
Definition at line 256 of file overworld.h.
Referenced by holes(), LoadEntrances(), mutable_holes(), and SaveEntrances().
all_exits_
std::vector<OverworldExit> yaze::zelda3::overworld::Overworld::all_exits_ private
Definition at line 257 of file overworld.h.
Referenced by Destroy(), exits(), LoadExits(), mutable_exits(), and SaveExits().
all_items_
std::vector<OverworldItem> yaze::zelda3::overworld::Overworld::all_items_ private
Definition at line 258 of file overworld.h.
Referenced by all_items(), Destroy(), LoadItems(), mutable_all_items(), and SaveItems().
all_sprites_
std::vector<std::vector<Sprite> > yaze::zelda3::overworld::Overworld::all_sprites_ private
Definition at line 259 of file overworld.h.
Referenced by Destroy(), LoadSprites(), LoadSpritesFromMap(), mutable_sprites(), and sprites().
deleted_entrances_
std::vector<uint64_t> yaze::zelda3::overworld::Overworld::deleted_entrances_ private
Definition at line 261 of file overworld.h.
Referenced by deleted_entrances(), and mutable_deleted_entrances().
map_data_p1
std::vector<std::vector<uint8_t> > yaze::zelda3::overworld::Overworld::map_data_p1 private
Initial value:
=
      std::vector<std::vector<uint8_t>>(kNumOverworldMaps)
Definition at line 263 of file overworld.h.
Referenced by SaveOverworldMaps().
map_data_p2
std::vector<std::vector<uint8_t> > yaze::zelda3::overworld::Overworld::map_data_p2 private
Initial value:
=
      std::vector<std::vector<uint8_t>>(kNumOverworldMaps)
Definition at line 265 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers1_id
std::vector<int> yaze::zelda3::overworld::Overworld::map_pointers1_id = std::vector<int>(kNumOverworldMaps) private
Definition at line 268 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers2_id
std::vector<int> yaze::zelda3::overworld::Overworld::map_pointers2_id = std::vector<int>(kNumOverworldMaps) private
Definition at line 269 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers1
std::vector<int> yaze::zelda3::overworld::Overworld::map_pointers1 = std::vector<int>(kNumOverworldMaps) private
Definition at line 271 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers2
std::vector<int> yaze::zelda3::overworld::Overworld::map_pointers2 = std::vector<int>(kNumOverworldMaps) private
Definition at line 272 of file overworld.h.
Referenced by SaveOverworldMaps().
usage_stats_
std::vector<absl::flat_hash_map<uint16_t, int> > yaze::zelda3::overworld::Overworld::usage_stats_ private
Definition at line 274 of file overworld.h.
The documentation for this class was generated from the following files:
src/app/zelda3/overworld/overworld.h
src/app/zelda3/overworld/overworld.cc