yaze: yaze::test::UnitTestSuite Class Reference
yaze::test::UnitTestSuite Class Reference
#include <unit_test_suite.h>
Public Member Functions
UnitTestSuite ()=default
~UnitTestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Private Attributes
bool run_disabled_tests_ = false
bool shuffle_tests_ = false
int repeat_count_ = 1
char test_filter_ [256] = ""
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
Definition at line 90 of file unit_test_suite.h.
Constructor & Destructor Documentation
UnitTestSuite()
yaze::test::UnitTestSuite::UnitTestSuite () default
~UnitTestSuite()
yaze::test::UnitTestSuite::~UnitTestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::UnitTestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 95 of file unit_test_suite.h.
Referenced by RunTests().
GetCategory()
TestCategory yaze::test::UnitTestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 96 of file unit_test_suite.h.
References yaze::test::kUnit.
Referenced by RunTests().
RunTests()
absl::Status yaze::test::UnitTestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 98 of file unit_test_suite.h.
References yaze::test::TestResults::AddResult(), GetCategory(), GetName(), yaze::test::kSkipped, and yaze::test::TestResult::name.
DrawConfiguration()
void yaze::test::UnitTestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 140 of file unit_test_suite.h.
References repeat_count_, run_disabled_tests_, shuffle_tests_, and test_filter_.
Member Data Documentation
run_disabled_tests_
bool yaze::test::UnitTestSuite::run_disabled_tests_ = false private
Definition at line 155 of file unit_test_suite.h.
Referenced by DrawConfiguration().
shuffle_tests_
bool yaze::test::UnitTestSuite::shuffle_tests_ = false private
Definition at line 156 of file unit_test_suite.h.
Referenced by DrawConfiguration().
repeat_count_
int yaze::test::UnitTestSuite::repeat_count_ = 1 private
Definition at line 157 of file unit_test_suite.h.
Referenced by DrawConfiguration().
test_filter_
char yaze::test::UnitTestSuite::test_filter_[256] = "" private
Definition at line 158 of file unit_test_suite.h.
Referenced by DrawConfiguration().
The documentation for this class was generated from the following file:
src/app/test/unit_test_suite.h