yaze: yaze::test::ArenaTestSuite Class Reference
yaze::test::ArenaTestSuite Class Reference
#include <unit_test_suite.h>
Public Member Functions
ArenaTestSuite ()=default
~ArenaTestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Private Member Functions
void RunArenaAllocationTest (TestResults &results)
void RunArenaCleanupTest (TestResults &results)
void RunArenaResourceTrackingTest (TestResults &results)
Private Attributes
int test_allocation_count_ = 10
int test_texture_size_ = 64
bool test_cleanup_order_ = true
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
Definition at line 162 of file unit_test_suite.h.
Constructor & Destructor Documentation
ArenaTestSuite()
yaze::test::ArenaTestSuite::ArenaTestSuite () default
~ArenaTestSuite()
yaze::test::ArenaTestSuite::~ArenaTestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::ArenaTestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 167 of file unit_test_suite.h.
Referenced by RunArenaAllocationTest(), RunArenaCleanupTest(), and RunArenaResourceTrackingTest().
GetCategory()
TestCategory yaze::test::ArenaTestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 168 of file unit_test_suite.h.
References yaze::test::kMemory.
Referenced by RunArenaAllocationTest(), RunArenaCleanupTest(), and RunArenaResourceTrackingTest().
RunTests()
absl::Status yaze::test::ArenaTestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 170 of file unit_test_suite.h.
References RunArenaAllocationTest(), RunArenaCleanupTest(), and RunArenaResourceTrackingTest().
DrawConfiguration()
void yaze::test::ArenaTestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 179 of file unit_test_suite.h.
References test_allocation_count_, test_cleanup_order_, and test_texture_size_.
RunArenaAllocationTest()
void yaze::test::ArenaTestSuite::RunArenaAllocationTest (TestResults & results) inline private
Definition at line 187 of file unit_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunArenaCleanupTest()
void yaze::test::ArenaTestSuite::RunArenaCleanupTest (TestResults & results) inline private
Definition at line 224 of file unit_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunArenaResourceTrackingTest()
void yaze::test::ArenaTestSuite::RunArenaResourceTrackingTest (TestResults & results) inline private
Definition at line 257 of file unit_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
Member Data Documentation
test_allocation_count_
int yaze::test::ArenaTestSuite::test_allocation_count_ = 10 private
Definition at line 294 of file unit_test_suite.h.
Referenced by DrawConfiguration().
test_texture_size_
int yaze::test::ArenaTestSuite::test_texture_size_ = 64 private
Definition at line 295 of file unit_test_suite.h.
Referenced by DrawConfiguration().
test_cleanup_order_
bool yaze::test::ArenaTestSuite::test_cleanup_order_ = true private
Definition at line 296 of file unit_test_suite.h.
Referenced by DrawConfiguration().
The documentation for this class was generated from the following file:
src/app/test/unit_test_suite.h