yaze: yaze::test::IntegratedTestSuite Class Reference
yaze::test::IntegratedTestSuite Class Reference
#include <integrated_test_suite.h>
Public Member Functions
IntegratedTestSuite ()=default
~IntegratedTestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Private Member Functions
void RunArenaIntegrityTest (TestResults &results)
void RunArenaResourceManagementTest (TestResults &results)
void RunRomBasicTest (TestResults &results)
void RunGraphicsValidationTest (TestResults &results)
Private Attributes
bool test_arena_ = true
bool test_rom_ = true
bool test_graphics_ = true
char test_rom_path_ [256] = "zelda3.sfc"
bool skip_missing_rom_ = true
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
Definition at line 22 of file integrated_test_suite.h.
Constructor & Destructor Documentation
IntegratedTestSuite()
yaze::test::IntegratedTestSuite::IntegratedTestSuite () default
~IntegratedTestSuite()
yaze::test::IntegratedTestSuite::~IntegratedTestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::IntegratedTestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 27 of file integrated_test_suite.h.
Referenced by RunArenaIntegrityTest(), RunArenaResourceManagementTest(), RunGraphicsValidationTest(), and RunRomBasicTest().
GetCategory()
TestCategory yaze::test::IntegratedTestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 28 of file integrated_test_suite.h.
References yaze::test::kUnit.
Referenced by RunArenaIntegrityTest(), RunArenaResourceManagementTest(), RunGraphicsValidationTest(), and RunRomBasicTest().
RunTests()
absl::Status yaze::test::IntegratedTestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 30 of file integrated_test_suite.h.
References RunArenaIntegrityTest(), RunArenaResourceManagementTest(), RunGraphicsValidationTest(), and RunRomBasicTest().
DrawConfiguration()
void yaze::test::IntegratedTestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 44 of file integrated_test_suite.h.
References skip_missing_rom_, test_arena_, test_graphics_, test_rom_, and test_rom_path_.
RunArenaIntegrityTest()
void yaze::test::IntegratedTestSuite::RunArenaIntegrityTest (TestResults & results) inline private
Definition at line 57 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunArenaResourceManagementTest()
void yaze::test::IntegratedTestSuite::RunArenaResourceManagementTest (TestResults & results) inline private
Definition at line 96 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunRomBasicTest()
void yaze::test::IntegratedTestSuite::RunRomBasicTest (TestResults & results) inline private
Definition at line 140 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), yaze::test::TestManager::GetCurrentRom(), GetName(), yaze::Rom::is_loaded(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::kSkipped, yaze::Rom::LoadFromFile(), yaze::test::TestResult::name, yaze::Rom::size(), skip_missing_rom_, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_rom_, test_rom_path_, yaze::test::TestResult::timestamp, and yaze::Rom::title().
Referenced by RunTests().
RunGraphicsValidationTest()
void yaze::test::IntegratedTestSuite::RunGraphicsValidationTest (TestResults & results) inline private
Definition at line 204 of file integrated_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::gfx::Arena::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::kSkipped, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, test_graphics_, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
Member Data Documentation
test_arena_
bool yaze::test::IntegratedTestSuite::test_arena_ = true private
Definition at line 251 of file integrated_test_suite.h.
Referenced by DrawConfiguration().
test_rom_
bool yaze::test::IntegratedTestSuite::test_rom_ = true private
Definition at line 252 of file integrated_test_suite.h.
Referenced by DrawConfiguration(), and RunRomBasicTest().
test_graphics_
bool yaze::test::IntegratedTestSuite::test_graphics_ = true private
Definition at line 253 of file integrated_test_suite.h.
Referenced by DrawConfiguration(), and RunGraphicsValidationTest().
test_rom_path_
char yaze::test::IntegratedTestSuite::test_rom_path_[256] = "zelda3.sfc" private
Definition at line 254 of file integrated_test_suite.h.
Referenced by DrawConfiguration(), and RunRomBasicTest().
skip_missing_rom_
bool yaze::test::IntegratedTestSuite::skip_missing_rom_ = true private
Definition at line 255 of file integrated_test_suite.h.
Referenced by DrawConfiguration(), and RunRomBasicTest().
The documentation for this class was generated from the following file:
src/app/test/integrated_test_suite.h