yaze: yaze::cli::Emulator Class Reference
yaze::cli::Emulator Class Reference
Start the emulator on a SNES Rom file.
#include <command_handler.h>
Public Member Functions
absl::Status handle (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
Public Attributes
app::emu::SNES snes
Public Attributes inherited from yaze::cli::CommandHandler
app::Rom rom_
Detailed Description
Start the emulator on a SNES Rom file.
Parameters
arg_vec -emu <rom_file> <optional:num_cpu_cycles>
Returns
absl::Status
Member Function Documentation
handle()
absl::Status yaze::cli::Emulator::handle (const std::vector< std::string > & arg_vec) inline override virtual
Implements yaze::cli::CommandHandler.
References yaze::app::emu::SNES::Init(), yaze::app::Rom::LoadFromFile(), RETURN_IF_ERROR, yaze::cli::CommandHandler::rom_, yaze::app::emu::SNES::Run(), yaze::app::emu::SNES::SetCpuMode(), yaze::app::emu::SNES::SetupMemory(), snes, and yaze::app::emu::SNES::StepRun().
Member Data Documentation
snes
app::emu::SNES yaze::cli::Emulator::snes
Referenced by handle().
The documentation for this class was generated from the following file:
src/cli/command_handler.h