yaze: yaze::app::gfx::GraphicsBuffer Class Reference
yaze::app::gfx::GraphicsBuffer Class Reference
#include <snes_tile.h>
Public Member Functions
GraphicsBuffer ()=default
GraphicsBuffer (uint8_t bpp, const std::vector< uint8_t > &data)
GraphicsBuffer (uint8_t bpp, std::vector< uint8_t > &&data)
uint8_t bpp () const
const std::vector< uint8_t > & data () const
void set_bpp (uint8_t bpp)
void set_data (const std::vector< uint8_t > &data)
void to_bpp (uint8_t bpp)
uint8_t & operator[] (size_t index)
const uint8_t & operator[] (size_t index) const
auto begin ()
auto end ()
auto begin () const
auto end () const
Private Attributes
uint8_t bpp_
std::vector< uint8_t > data_
Detailed Description
Definition at line 178 of file snes_tile.h.
Constructor & Destructor Documentation
GraphicsBuffer() [1/3]
yaze::app::gfx::GraphicsBuffer::GraphicsBuffer () default
GraphicsBuffer() [2/3]
yaze::app::gfx::GraphicsBuffer::GraphicsBuffer (uint8_t bpp, const std::vector< uint8_t > & data) inline
Definition at line 181 of file snes_tile.h.
GraphicsBuffer() [3/3]
yaze::app::gfx::GraphicsBuffer::GraphicsBuffer (uint8_t bpp, std::vector< uint8_t > && data) inline
Definition at line 183 of file snes_tile.h.
Member Function Documentation
bpp()
uint8_t yaze::app::gfx::GraphicsBuffer::bpp () const inline
Definition at line 186 of file snes_tile.h.
References bpp_.
Referenced by set_bpp(), and to_bpp().
data()
const std::vector< uint8_t > & yaze::app::gfx::GraphicsBuffer::data () const inline
Definition at line 187 of file snes_tile.h.
References data_.
Referenced by set_data().
set_bpp()
void yaze::app::gfx::GraphicsBuffer::set_bpp (uint8_t bpp) inline
Definition at line 189 of file snes_tile.h.
References bpp(), and bpp_.
set_data()
void yaze::app::gfx::GraphicsBuffer::set_data (const std::vector< uint8_t > & data) inline
Definition at line 190 of file snes_tile.h.
References data(), and data_.
to_bpp()
void yaze::app::gfx::GraphicsBuffer::to_bpp (uint8_t bpp) inline
Definition at line 191 of file snes_tile.h.
References bpp(), bpp_, yaze::app::gfx::ConvertBpp(), and data_.
operator[]() [1/2]
uint8_t & yaze::app::gfx::GraphicsBuffer::operator[] (size_t index) inline
Definition at line 200 of file snes_tile.h.
References data_.
operator[]() [2/2]
const uint8_t & yaze::app::gfx::GraphicsBuffer::operator[] (size_t index) const inline
Definition at line 207 of file snes_tile.h.
References data_.
begin() [1/2]
auto yaze::app::gfx::GraphicsBuffer::begin () inline
Definition at line 214 of file snes_tile.h.
References data_.
end() [1/2]
auto yaze::app::gfx::GraphicsBuffer::end () inline
Definition at line 215 of file snes_tile.h.
References data_.
begin() [2/2]
auto yaze::app::gfx::GraphicsBuffer::begin () const inline
Definition at line 216 of file snes_tile.h.
References data_.
end() [2/2]
auto yaze::app::gfx::GraphicsBuffer::end () const inline
Definition at line 217 of file snes_tile.h.
References data_.
Member Data Documentation
bpp_
uint8_t yaze::app::gfx::GraphicsBuffer::bpp_ private
Definition at line 220 of file snes_tile.h.
Referenced by bpp(), set_bpp(), and to_bpp().
data_
std::vector<uint8_t> yaze::app::gfx::GraphicsBuffer::data_ private
Definition at line 221 of file snes_tile.h.
Referenced by begin(), begin(), data(), end(), end(), operator[](), operator[](), set_data(), and to_bpp().
The documentation for this class was generated from the following file:
src/app/gfx/snes_tile.h