yaze: yaze::app::emu::audio::AudioRamImpl Class Reference
yaze::app::emu::audio::AudioRamImpl Class Reference
AudioRamImpl is an implementation of the AudioRam interface.
#include <spc700.h>
Public Member Functions
AudioRamImpl ()=default
void reset () override
uint8_t read (uint16_t address) const override
uint8_t & mutable_read (uint16_t address) override
void write (uint16_t address, uint8_t value) override
uint8_t operator[] (uint16_t address) const
Public Member Functions inherited from yaze::app::emu::audio::AudioRam
virtual ~AudioRam ()=default
uint8_t operator[] (uint16_t address)
Private Attributes
std::vector< uint8_t > ram = std::vector<uint8_t>(ARAM_SIZE, 0)
Static Private Attributes
static const int ARAM_SIZE = 0x10000
Detailed Description
AudioRamImpl is an implementation of the AudioRam interface.
Definition at line 31 of file spc700.h.
Constructor & Destructor Documentation
AudioRamImpl()
yaze::app::emu::audio::AudioRamImpl::AudioRamImpl () default
Member Function Documentation
reset()
void yaze::app::emu::audio::AudioRamImpl::reset () inline override virtual
Implements yaze::app::emu::audio::AudioRam.
Definition at line 37 of file spc700.h.
References ARAM_SIZE, and ram.
read()
uint8_t yaze::app::emu::audio::AudioRamImpl::read (uint16_t address) const inline override virtual
Implements yaze::app::emu::audio::AudioRam.
Definition at line 39 of file spc700.h.
References ARAM_SIZE, and ram.
Referenced by operator[]().
mutable_read()
uint8_t & yaze::app::emu::audio::AudioRamImpl::mutable_read (uint16_t address) inline override virtual
Implements yaze::app::emu::audio::AudioRam.
Definition at line 43 of file spc700.h.
References ARAM_SIZE, and ram.
write()
void yaze::app::emu::audio::AudioRamImpl::write (uint16_t address, uint8_t value) inline override virtual
Implements yaze::app::emu::audio::AudioRam.
Definition at line 47 of file spc700.h.
References ARAM_SIZE, and ram.
operator[]()
uint8_t yaze::app::emu::audio::AudioRamImpl::operator[] (uint16_t address) const inline
Definition at line 52 of file spc700.h.
References read().
Member Data Documentation
ARAM_SIZE
const int yaze::app::emu::audio::AudioRamImpl::ARAM_SIZE = 0x10000 static private
Definition at line 32 of file spc700.h.
Referenced by mutable_read(), read(), reset(), and write().
ram
std::vector<uint8_t> yaze::app::emu::audio::AudioRamImpl::ram = std::vector<uint8_t>(ARAM_SIZE, 0) private
Definition at line 33 of file spc700.h.
Referenced by mutable_read(), read(), reset(), and write().
The documentation for this class was generated from the following file:
src/app/emu/audio/spc700.h