yaze: yaze::zelda3::ObjectRenderer Class Reference
yaze::zelda3::ObjectRenderer Class Reference
Unified ObjectRenderer combining all optimizations and enhancements.
#include <object_renderer.h>
Classes
class GraphicsCache
class MemoryPool
class ObjectParser
class PerformanceMonitor
struct PerformanceStats
struct TileRenderInfo
Public Member Functions
ObjectRenderer (Rom *rom)
~ObjectRenderer ()
absl::StatusOr< gfx::Bitmap > RenderObject (const RoomObject &object, const gfx::SnesPalette &palette)
absl::StatusOr< gfx::Bitmap > RenderObjects (const std::vector< RoomObject > &objects, const gfx::SnesPalette &palette)
absl::StatusOr< gfx::Bitmap > RenderRoom (const Room &room, const gfx::SnesPalette &palette)
void ClearCache ()
size_t GetMemoryUsage () const
PerformanceStats GetPerformanceStats () const
void ResetPerformanceStats ()
void SetROM (Rom *rom)
void SetCacheSize (size_t max_cache_size)
void EnablePerformanceMonitoring (bool enable)
absl::StatusOr< gfx::Bitmap > RenderObjects (const std::vector< RoomObject > &objects, const gfx::SnesPalette &palette, int width, int height)
absl::StatusOr< gfx::Bitmap > RenderObjectWithSize (const RoomObject &object, const gfx::SnesPalette &palette, const ObjectSizeInfo &size_info)
absl::StatusOr< gfx::Bitmap > GetObjectPreview (const RoomObject &object, const gfx::SnesPalette &palette)
Private Member Functions
absl::Status ValidateInputs (const RoomObject &object, const gfx::SnesPalette &palette)
absl::Status ValidateInputs (const std::vector< RoomObject > &objects, const gfx::SnesPalette &palette)
absl::StatusOr< gfx::Bitmap > CreateBitmap (int width, int height)
absl::Status RenderTileToBitmap (const gfx::Tile16 &tile, gfx::Bitmap &bitmap, int x, int y, const gfx::SnesPalette &palette)
absl::Status BatchRenderTiles (const std::vector< TileRenderInfo > &tiles, gfx::Bitmap &bitmap, const gfx::SnesPalette &palette)
void Render8x8Tile (gfx::Bitmap &bitmap, gfx::Bitmap *graphics_sheet, const gfx::TileInfo &tile_info, int x, int y, const gfx::SnesPalette &palette)
void RenderTilePattern (gfx::Bitmap &bitmap, int x, int y, const gfx::TileInfo &tile_info, const gfx::SnesPalette &palette)
std::pair< int, int > CalculateOptimalBitmapSize (const std::vector< RoomObject > &objects)
bool IsObjectInBounds (const RoomObject &object, int bitmap_width, int bitmap_height)
absl::Status RenderTile (const gfx::Tile16 &tile, gfx::Bitmap &bitmap, int x, int y, const gfx::SnesPalette &palette)
absl::Status ApplyObjectSize (gfx::Bitmap &bitmap, const ObjectSizeInfo &size_info)
Private Attributes
Rom * rom_
std::unique_ptr< GraphicsCache > graphics_cache_
std::unique_ptr< MemoryPool > memory_pool_
std::unique_ptr< PerformanceMonitor > performance_monitor_
std::unique_ptr< ObjectParser > parser_
size_t max_cache_size_ = 100
bool performance_monitoring_enabled_ = true
Detailed Description
Unified ObjectRenderer combining all optimizations and enhancements.
This class provides a complete, optimized solution for dungeon object rendering that combines:
Direct ROM parsing (50-100x faster than SNES emulation)
Intelligent graphics sheet caching with LRU eviction
Batch rendering optimizations
Memory pool integration
Thread-safe operations
Comprehensive error handling and validation
Real-time performance monitoring
Support for all three object subtypes (0x00-0xFF, 0x100-0x1FF, 0x200+)
Definition at line 38 of file object_renderer.h.
Constructor & Destructor Documentation
ObjectRenderer()
yaze::zelda3::ObjectRenderer::ObjectRenderer (Rom * rom) explicit
Definition at line 388 of file object_renderer.cc.
~ObjectRenderer()
yaze::zelda3::ObjectRenderer::~ObjectRenderer () default
Member Function Documentation
RenderObject()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::ObjectRenderer::RenderObject (const RoomObject & object, const gfx::SnesPalette & palette)
Definition at line 406 of file object_renderer.cc.
References CreateBitmap(), performance_monitor_, performance_monitoring_enabled_, RenderTileToBitmap(), and ValidateInputs().
Referenced by yaze::editor::DungeonObjectSelector::DrawObjectRenderer(), yaze::editor::DungeonCanvasViewer::RenderObjectInCanvas(), yaze::editor::DungeonRenderer::RenderObjectInCanvas(), yaze::test::TEST_F(), and yaze::test::TEST_F().
RenderObjects() [1/2]
absl::StatusOr< gfx::Bitmap > yaze::zelda3::ObjectRenderer::RenderObjects (const std::vector< RoomObject > & objects, const gfx::SnesPalette & palette)
Definition at line 450 of file object_renderer.cc.
References BatchRenderTiles(), CalculateOptimalBitmapSize(), CreateBitmap(), performance_monitor_, performance_monitoring_enabled_, yaze::zelda3::ObjectRenderer::TileRenderInfo::sheet_index, yaze::zelda3::ObjectRenderer::TileRenderInfo::tile, ValidateInputs(), yaze::zelda3::ObjectRenderer::TileRenderInfo::x, and yaze::zelda3::ObjectRenderer::TileRenderInfo::y.
Referenced by RenderRoom().
RenderRoom()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::ObjectRenderer::RenderRoom (const Room & room, const gfx::SnesPalette & palette)
Definition at line 505 of file object_renderer.cc.
References yaze::zelda3::RoomObject::EnsureTilesLoaded(), yaze::zelda3::Room::GetLayout(), yaze::zelda3::RoomLayout::GetObjects(), yaze::zelda3::Room::GetTileObjects(), RenderObjects(), rom_, and yaze::zelda3::RoomObject::set_rom().
ClearCache()
void yaze::zelda3::ObjectRenderer::ClearCache ()
Definition at line 527 of file object_renderer.cc.
References graphics_cache_, memory_pool_, performance_monitor_, and performance_monitoring_enabled_.
GetMemoryUsage()
size_t yaze::zelda3::ObjectRenderer::GetMemoryUsage () const
Definition at line 535 of file object_renderer.cc.
References graphics_cache_, and memory_pool_.
GetPerformanceStats()
ObjectRenderer::PerformanceStats yaze::zelda3::ObjectRenderer::GetPerformanceStats () const
Definition at line 539 of file object_renderer.cc.
References yaze::zelda3::ObjectRenderer::PerformanceStats::cache_hits, graphics_cache_, and performance_monitor_.
ResetPerformanceStats()
void yaze::zelda3::ObjectRenderer::ResetPerformanceStats ()
Definition at line 546 of file object_renderer.cc.
References performance_monitor_, and performance_monitoring_enabled_.
SetROM()
void yaze::zelda3::ObjectRenderer::SetROM (Rom * rom)
Definition at line 400 of file object_renderer.cc.
References parser_, and rom_.
Referenced by yaze::editor::DungeonObjectSelector::set_rom(), yaze::editor::DungeonCanvasViewer::SetRom(), and yaze::editor::DungeonObjectSelector::SetRom().
SetCacheSize()
void yaze::zelda3::ObjectRenderer::SetCacheSize (size_t max_cache_size)
Definition at line 552 of file object_renderer.cc.
References graphics_cache_, and max_cache_size_.
EnablePerformanceMonitoring()
void yaze::zelda3::ObjectRenderer::EnablePerformanceMonitoring (bool enable)
Definition at line 557 of file object_renderer.cc.
References performance_monitoring_enabled_.
RenderObjects() [2/2]
absl::StatusOr< gfx::Bitmap > yaze::zelda3::ObjectRenderer::RenderObjects (const std::vector< RoomObject > & objects, const gfx::SnesPalette & palette, int width, int height)
Definition at line 562 of file object_renderer.cc.
References CreateBitmap(), and RenderTile().
RenderObjectWithSize()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::ObjectRenderer::RenderObjectWithSize (const RoomObject & object, const gfx::SnesPalette & palette, const ObjectSizeInfo & size_info)
Definition at line 595 of file object_renderer.cc.
References CreateBitmap(), yaze::zelda3::ObjectSizeInfo::height_tiles, yaze::zelda3::ObjectSizeInfo::is_horizontal, RenderTile(), yaze::zelda3::ObjectSizeInfo::repeat_count, and yaze::zelda3::ObjectSizeInfo::width_tiles.
GetObjectPreview()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::ObjectRenderer::GetObjectPreview (const RoomObject & object, const gfx::SnesPalette & palette)
Definition at line 647 of file object_renderer.cc.
References CreateBitmap(), and RenderTile().
ValidateInputs() [1/2]
absl::Status yaze::zelda3::ObjectRenderer::ValidateInputs (const RoomObject & object, const gfx::SnesPalette & palette) private
Definition at line 667 of file object_renderer.cc.
References yaze::gfx::SnesPalette::empty().
Referenced by RenderObject(), RenderObjects(), and ValidateInputs().
ValidateInputs() [2/2]
absl::Status yaze::zelda3::ObjectRenderer::ValidateInputs (const std::vector< RoomObject > & objects, const gfx::SnesPalette & palette) private
Definition at line 683 of file object_renderer.cc.
References yaze::gfx::SnesPalette::empty(), and ValidateInputs().
CreateBitmap()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::ObjectRenderer::CreateBitmap (int width, int height) private
Definition at line 700 of file object_renderer.cc.
References yaze::gfx::Bitmap::is_active(), performance_monitor_, and performance_monitoring_enabled_.
Referenced by GetObjectPreview(), RenderObject(), RenderObjects(), RenderObjects(), and RenderObjectWithSize().
RenderTileToBitmap()
absl::Status yaze::zelda3::ObjectRenderer::RenderTileToBitmap (const gfx::Tile16 & tile, gfx::Bitmap & bitmap, int x, int y, const gfx::SnesPalette & palette) private
Definition at line 720 of file object_renderer.cc.
References graphics_cache_, yaze::gfx::Bitmap::height(), yaze::gfx::TileInfo::id_, Render8x8Tile(), RenderTilePattern(), yaze::gfx::Tile16::tile0_, yaze::gfx::Tile16::tile1_, yaze::gfx::Tile16::tile2_, yaze::gfx::Tile16::tile3_, and yaze::gfx::Bitmap::width().
Referenced by BatchRenderTiles(), and RenderObject().
BatchRenderTiles()
absl::Status yaze::zelda3::ObjectRenderer::BatchRenderTiles (const std::vector< TileRenderInfo > & tiles, gfx::Bitmap & bitmap, const gfx::SnesPalette & palette) private
Definition at line 826 of file object_renderer.cc.
References graphics_cache_, yaze::gfx::TileInfo::id_, RenderTileToBitmap(), and yaze::zelda3::ObjectRenderer::TileRenderInfo::sheet_index.
Referenced by RenderObjects().
Render8x8Tile()
void yaze::zelda3::ObjectRenderer::Render8x8Tile (gfx::Bitmap & bitmap, gfx::Bitmap * graphics_sheet, const gfx::TileInfo & tile_info, int x, int y, const gfx::SnesPalette & palette) private
Definition at line 758 of file object_renderer.cc.
References yaze::gfx::Bitmap::at(), yaze::gfx::Bitmap::height(), yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::gfx::Bitmap::SetPixel(), yaze::gfx::Bitmap::size(), yaze::gfx::SnesPalette::size(), yaze::gfx::TileInfo::vertical_mirror_, and yaze::gfx::Bitmap::width().
Referenced by RenderTileToBitmap().
RenderTilePattern()
void yaze::zelda3::ObjectRenderer::RenderTilePattern (gfx::Bitmap & bitmap, int x, int y, const gfx::TileInfo & tile_info, const gfx::SnesPalette & palette) private
Definition at line 809 of file object_renderer.cc.
References yaze::gfx::Bitmap::height(), yaze::gfx::TileInfo::id_, yaze::gfx::Bitmap::SetPixel(), yaze::gfx::SnesPalette::size(), and yaze::gfx::Bitmap::width().
Referenced by RenderTile(), and RenderTileToBitmap().
CalculateOptimalBitmapSize()
std::pair< int, int > yaze::zelda3::ObjectRenderer::CalculateOptimalBitmapSize (const std::vector< RoomObject > & objects) private
Definition at line 877 of file object_renderer.cc.
Referenced by RenderObjects().
IsObjectInBounds()
bool yaze::zelda3::ObjectRenderer::IsObjectInBounds (const RoomObject & object, int bitmap_width, int bitmap_height) private
Definition at line 906 of file object_renderer.cc.
RenderTile()
absl::Status yaze::zelda3::ObjectRenderer::RenderTile (const gfx::Tile16 & tile, gfx::Bitmap & bitmap, int x, int y, const gfx::SnesPalette & palette) private
Definition at line 915 of file object_renderer.cc.
References yaze::gfx::Arena::Get(), yaze::gfx::Bitmap::height(), yaze::gfx::TileInfo::id_, yaze::gfx::Bitmap::is_active(), RenderTilePattern(), yaze::gfx::Bitmap::SetPixel(), yaze::gfx::SnesPalette::size(), yaze::gfx::Bitmap::surface(), yaze::gfx::Tile16::tile0_, yaze::gfx::Tile16::tile1_, yaze::gfx::Tile16::tile2_, yaze::gfx::Tile16::tile3_, and yaze::gfx::Bitmap::width().
Referenced by GetObjectPreview(), RenderObjects(), and RenderObjectWithSize().
ApplyObjectSize()
absl::Status yaze::zelda3::ObjectRenderer::ApplyObjectSize (gfx::Bitmap & bitmap, const ObjectSizeInfo & size_info) private
Definition at line 996 of file object_renderer.cc.
Member Data Documentation
rom_
Rom* yaze::zelda3::ObjectRenderer::rom_ private
Definition at line 120 of file object_renderer.h.
Referenced by RenderRoom(), and SetROM().
graphics_cache_
std::unique_ptr<GraphicsCache> yaze::zelda3::ObjectRenderer::graphics_cache_ private
Definition at line 121 of file object_renderer.h.
Referenced by BatchRenderTiles(), ClearCache(), GetMemoryUsage(), GetPerformanceStats(), RenderTileToBitmap(), and SetCacheSize().
memory_pool_
std::unique_ptr<MemoryPool> yaze::zelda3::ObjectRenderer::memory_pool_ private
Definition at line 122 of file object_renderer.h.
Referenced by ClearCache(), and GetMemoryUsage().
performance_monitor_
std::unique_ptr<PerformanceMonitor> yaze::zelda3::ObjectRenderer::performance_monitor_ private
Definition at line 123 of file object_renderer.h.
Referenced by ClearCache(), CreateBitmap(), GetPerformanceStats(), RenderObject(), RenderObjects(), and ResetPerformanceStats().
parser_
std::unique_ptr<ObjectParser> yaze::zelda3::ObjectRenderer::parser_ private
Definition at line 124 of file object_renderer.h.
Referenced by SetROM().
max_cache_size_
size_t yaze::zelda3::ObjectRenderer::max_cache_size_ = 100 private
Definition at line 127 of file object_renderer.h.
Referenced by SetCacheSize().
performance_monitoring_enabled_
bool yaze::zelda3::ObjectRenderer::performance_monitoring_enabled_ = true private
Definition at line 128 of file object_renderer.h.
Referenced by ClearCache(), CreateBitmap(), EnablePerformanceMonitoring(), RenderObject(), RenderObjects(), and ResetPerformanceStats().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/object_renderer.h
src/app/zelda3/dungeon/object_renderer.cc