yaze: yaze::zelda3::RoomObject Class Reference
yaze::zelda3::RoomObject Class Reference
#include <room_object.h>
Public Types
enum LayerType { BG1 = 0 , BG2 = 1 , BG3 = 2 }
Public Member Functions
RoomObject (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer=0)
void set_rom (Rom *rom)
auto rom ()
auto mutable_rom ()
void set_x (uint8_t x)
void set_y (uint8_t y)
void set_size (uint8_t size)
uint8_t x () const
uint8_t y () const
uint8_t size () const
void EnsureTilesLoaded ()
absl::Status LoadTilesWithParser ()
const std::vector< gfx::Tile16 > & tiles () const
std::vector< gfx::Tile16 > & mutable_tiles ()
absl::StatusOr< std::span< const gfx::Tile16 > > GetTiles () const
absl::StatusOr< const gfx::Tile16 * > GetTile (int index) const
int GetTileCount () const
void AddTiles (int nbr, int pos)
void DrawTile (gfx::Tile16 t, int xx, int yy, std::vector< uint8_t > &current_gfx16, std::vector< uint8_t > &tiles_bg1_buffer, std::vector< uint8_t > &tiles_bg2_buffer, uint16_t tile_under=0xFFFF)
auto options () const
void set_options (ObjectOption options)
Public Attributes
bool all_bgs_ = false
bool lit_ = false
int16_t id_
uint8_t x_
uint8_t y_
uint8_t size_
uint8_t nx_
uint8_t ny_
uint8_t ox_
uint8_t oy_
uint8_t z_ = 0
uint8_t previous_size_ = 0
uint8_t size_x_bits_ = 0
uint8_t size_y_bits_ = 0
int width_
int height_
int offset_x_ = 0
int offset_y_ = 0
std::string name_
std::vector< uint8_t > preview_object_data_
std::vector< gfx::Tile16 > tiles_
bool tiles_loaded_ = false
int tile_count_ = 0
int tile_data_ptr_ = -1
LayerType layer_
ObjectOption options_ = ObjectOption::Nothing
Rom * rom_
Detailed Description
Definition at line 57 of file room_object.h.
Member Enumeration Documentation
LayerType
enum yaze::zelda3::RoomObject::LayerType
Enumerator
BG1
BG2
BG3
Definition at line 59 of file room_object.h.
Constructor & Destructor Documentation
RoomObject()
yaze::zelda3::RoomObject::RoomObject (int16_t id, uint8_t x, uint8_t y, uint8_t size, uint8_t layer = 0) inline
Definition at line 61 of file room_object.h.
References height_, id_, layer_, nx_, ny_, ox_, oy_, rom_, size(), size_, width_, x(), x_, y(), and y_.
Referenced by GetTile(), GetTileCount(), GetTiles(), yaze::zelda3::Subtype1::Subtype1(), yaze::zelda3::Subtype2::Subtype2(), and yaze::zelda3::Subtype3::Subtype3().
Member Function Documentation
set_rom()
void yaze::zelda3::RoomObject::set_rom (Rom * rom) inline
Definition at line 75 of file room_object.h.
References rom(), and rom_.
Referenced by yaze::zelda3::DungeonObjectRendererMockTest::CreateMockObject(), yaze::zelda3::DungeonObjectRendererIntegrationTest::CreateTestObject(), yaze::zelda3::DungeonObjectEditor::InsertObject(), yaze::zelda3::Room::ParseObjectsFromLocation(), yaze::editor::DungeonEditor::RenderObjectInCanvas(), and yaze::zelda3::ObjectRenderer::RenderRoom().
rom()
auto yaze::zelda3::RoomObject::rom () inline
Definition at line 76 of file room_object.h.
References rom_.
Referenced by AddTiles(), set_rom(), yaze::zelda3::Subtype1::Subtype1(), yaze::zelda3::Subtype2::Subtype2(), and yaze::zelda3::Subtype3::Subtype3().
mutable_rom()
auto yaze::zelda3::RoomObject::mutable_rom () inline
Definition at line 77 of file room_object.h.
References rom_.
set_x()
void yaze::zelda3::RoomObject::set_x (uint8_t x) inline
Definition at line 80 of file room_object.h.
References x(), and x_.
Referenced by yaze::zelda3::DungeonObjectEditor::MoveObject().
set_y()
void yaze::zelda3::RoomObject::set_y (uint8_t y) inline
Definition at line 81 of file room_object.h.
References y(), and y_.
Referenced by yaze::zelda3::DungeonObjectEditor::MoveObject().
set_size()
void yaze::zelda3::RoomObject::set_size (uint8_t size) inline
Definition at line 82 of file room_object.h.
References size(), and size_.
x()
uint8_t yaze::zelda3::RoomObject::x () const inline
Definition at line 83 of file room_object.h.
References x_.
Referenced by RoomObject(), set_x(), yaze::zelda3::Subtype1::Subtype1(), yaze::zelda3::Subtype2::Subtype2(), and yaze::zelda3::Subtype3::Subtype3().
y()
uint8_t yaze::zelda3::RoomObject::y () const inline
Definition at line 84 of file room_object.h.
References y_.
Referenced by RoomObject(), set_y(), yaze::zelda3::Subtype1::Subtype1(), yaze::zelda3::Subtype2::Subtype2(), and yaze::zelda3::Subtype3::Subtype3().
size()
uint8_t yaze::zelda3::RoomObject::size () const inline
Definition at line 85 of file room_object.h.
References size_.
Referenced by AddTiles(), RoomObject(), set_size(), yaze::zelda3::Subtype1::Subtype1(), yaze::zelda3::Subtype2::Subtype2(), and yaze::zelda3::Subtype3::Subtype3().
EnsureTilesLoaded()
void yaze::zelda3::RoomObject::EnsureTilesLoaded ()
Definition at line 155 of file room_object.cc.
References id_, yaze::zelda3::kRoomObjectTileAddress, LoadTilesWithParser(), rom_, tile_count_, tile_data_ptr_, tiles_, tiles_loaded_, and yaze::gfx::WordToTileInfo().
Referenced by yaze::zelda3::DungeonObjectRendererMockTest::CreateMockObject(), yaze::zelda3::DungeonObjectRendererIntegrationTest::CreateTestObject(), GetTile(), GetTileCount(), GetTiles(), yaze::zelda3::DungeonObjectEditor::InsertObject(), and yaze::zelda3::ObjectRenderer::RenderRoom().
LoadTilesWithParser()
absl::Status yaze::zelda3::RoomObject::LoadTilesWithParser ()
Definition at line 202 of file room_object.cc.
References id_, yaze::zelda3::ObjectParser::ParseObject(), rom_, tile_count_, and tiles_.
Referenced by EnsureTilesLoaded().
tiles()
const std::vector< gfx::Tile16 > & yaze::zelda3::RoomObject::tiles () const inline
Definition at line 95 of file room_object.h.
References tiles_.
mutable_tiles()
std::vector< gfx::Tile16 > & yaze::zelda3::RoomObject::mutable_tiles () inline
Definition at line 96 of file room_object.h.
References tiles_.
GetTiles()
absl::StatusOr< std::span< const gfx::Tile16 > > yaze::zelda3::RoomObject::GetTiles () const
Definition at line 218 of file room_object.cc.
References EnsureTilesLoaded(), RoomObject(), tiles_, and tiles_loaded_.
GetTile()
absl::StatusOr< const gfx::Tile16 * > yaze::zelda3::RoomObject::GetTile (int index) const
Definition at line 230 of file room_object.cc.
References EnsureTilesLoaded(), RoomObject(), tiles_, and tiles_loaded_.
GetTileCount()
int yaze::zelda3::RoomObject::GetTileCount () const
Definition at line 243 of file room_object.cc.
References EnsureTilesLoaded(), RoomObject(), tile_count_, and tiles_loaded_.
AddTiles()
void yaze::zelda3::RoomObject::AddTiles (int nbr, int pos) inline
Definition at line 107 of file room_object.h.
References rom(), size(), tiles_, and yaze::gfx::WordToTileInfo().
Referenced by yaze::zelda3::Subtype1::Subtype1(), yaze::zelda3::Subtype2::Subtype2(), and yaze::zelda3::Subtype3::Subtype3().
DrawTile()
void yaze::zelda3::RoomObject::DrawTile (gfx::Tile16 t, int xx, int yy, std::vector< uint8_t > & current_gfx16, std::vector< uint8_t > & tiles_bg1_buffer, std::vector< uint8_t > & tiles_bg2_buffer, uint16_t tile_under = 0xFFFF)
Definition at line 74 of file room_object.cc.
References all_bgs_, height_, yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, layer_, nx_, ny_, offset_x_, offset_y_, yaze::gfx::TileInfo::palette_, preview_object_data_, yaze::gfx::TileInfo::vertical_mirror_, and width_.
Referenced by yaze::zelda3::Subtype1::Draw(), yaze::zelda3::Subtype2::Draw(), and yaze::zelda3::Subtype3::Draw().
options()
auto yaze::zelda3::RoomObject::options () const inline
Definition at line 129 of file room_object.h.
References options_.
Referenced by set_options().
set_options()
void yaze::zelda3::RoomObject::set_options (ObjectOption options) inline
Definition at line 130 of file room_object.h.
References options(), and options_.
Member Data Documentation
all_bgs_
bool yaze::zelda3::RoomObject::all_bgs_ = false
Definition at line 132 of file room_object.h.
Referenced by DrawTile().
lit_
bool yaze::zelda3::RoomObject::lit_ = false
Definition at line 133 of file room_object.h.
id_
int16_t yaze::zelda3::RoomObject::id_
Definition at line 135 of file room_object.h.
Referenced by EnsureTilesLoaded(), LoadTilesWithParser(), and RoomObject().
x_
uint8_t yaze::zelda3::RoomObject::x_
Definition at line 136 of file room_object.h.
Referenced by yaze::zelda3::Subtype2::Draw(), yaze::zelda3::Subtype3::Draw(), yaze::zelda3::DungeonObjectEditor::ObjectsCollide(), RoomObject(), set_x(), and x().
y_
uint8_t yaze::zelda3::RoomObject::y_
Definition at line 137 of file room_object.h.
Referenced by yaze::zelda3::Subtype2::Draw(), yaze::zelda3::Subtype3::Draw(), yaze::zelda3::DungeonObjectEditor::ObjectsCollide(), RoomObject(), set_y(), and y().
size_
uint8_t yaze::zelda3::RoomObject::size_
Definition at line 138 of file room_object.h.
Referenced by yaze::zelda3::Subtype1::Draw(), yaze::zelda3::DungeonObjectEditor::ObjectsCollide(), RoomObject(), set_size(), and size().
nx_
uint8_t yaze::zelda3::RoomObject::nx_
Definition at line 139 of file room_object.h.
Referenced by DrawTile(), and RoomObject().
ny_
uint8_t yaze::zelda3::RoomObject::ny_
Definition at line 140 of file room_object.h.
Referenced by DrawTile(), and RoomObject().
ox_
uint8_t yaze::zelda3::RoomObject::ox_
Definition at line 141 of file room_object.h.
Referenced by RoomObject().
oy_
uint8_t yaze::zelda3::RoomObject::oy_
Definition at line 142 of file room_object.h.
Referenced by RoomObject().
z_
uint8_t yaze::zelda3::RoomObject::z_ = 0
Definition at line 143 of file room_object.h.
previous_size_
uint8_t yaze::zelda3::RoomObject::previous_size_ = 0
Definition at line 144 of file room_object.h.
size_x_bits_
uint8_t yaze::zelda3::RoomObject::size_x_bits_ = 0
Definition at line 147 of file room_object.h.
size_y_bits_
uint8_t yaze::zelda3::RoomObject::size_y_bits_ = 0
Definition at line 148 of file room_object.h.
width_
int yaze::zelda3::RoomObject::width_
Definition at line 150 of file room_object.h.
Referenced by DrawTile(), and RoomObject().
height_
int yaze::zelda3::RoomObject::height_
Definition at line 151 of file room_object.h.
Referenced by DrawTile(), and RoomObject().
offset_x_
int yaze::zelda3::RoomObject::offset_x_ = 0
Definition at line 152 of file room_object.h.
Referenced by DrawTile().
offset_y_
int yaze::zelda3::RoomObject::offset_y_ = 0
Definition at line 153 of file room_object.h.
Referenced by DrawTile().
name_
std::string yaze::zelda3::RoomObject::name_
Definition at line 155 of file room_object.h.
preview_object_data_
std::vector<uint8_t> yaze::zelda3::RoomObject::preview_object_data_
Definition at line 157 of file room_object.h.
Referenced by DrawTile().
tiles_
std::vector<gfx::Tile16> yaze::zelda3::RoomObject::tiles_ mutable
Definition at line 161 of file room_object.h.
Referenced by AddTiles(), yaze::zelda3::Subtype1::Draw(), yaze::zelda3::Subtype2::Draw(), yaze::zelda3::Subtype3::Draw(), EnsureTilesLoaded(), GetTile(), GetTiles(), LoadTilesWithParser(), mutable_tiles(), and tiles().
tiles_loaded_
bool yaze::zelda3::RoomObject::tiles_loaded_ = false mutable
Definition at line 162 of file room_object.h.
Referenced by EnsureTilesLoaded(), GetTile(), GetTileCount(), and GetTiles().
tile_count_
int yaze::zelda3::RoomObject::tile_count_ = 0 mutable
Definition at line 163 of file room_object.h.
Referenced by EnsureTilesLoaded(), GetTileCount(), and LoadTilesWithParser().
tile_data_ptr_
int yaze::zelda3::RoomObject::tile_data_ptr_ = -1 mutable
Definition at line 164 of file room_object.h.
Referenced by EnsureTilesLoaded().
layer_
LayerType yaze::zelda3::RoomObject::layer_
Definition at line 166 of file room_object.h.
Referenced by DrawTile(), and RoomObject().
options_
ObjectOption yaze::zelda3::RoomObject::options_ = ObjectOption::Nothing
Definition at line 167 of file room_object.h.
Referenced by options(), and set_options().
rom_
Rom* yaze::zelda3::RoomObject::rom_
Definition at line 169 of file room_object.h.
Referenced by EnsureTilesLoaded(), LoadTilesWithParser(), mutable_rom(), rom(), RoomObject(), and set_rom().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/room_object.h
src/app/zelda3/dungeon/room_object.cc