yaze: yaze::app::SharedRom Class Reference
yaze::app::SharedRom Class Reference
A class to hold a shared pointer to a Rom object.
#include <rom.h>
Public Member Functions
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Static Public Attributes
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
A class to hold a shared pointer to a Rom object.
Constructor & Destructor Documentation
SharedRom()
yaze::app::SharedRom::SharedRom () default
~SharedRom()
virtual yaze::app::SharedRom::~SharedRom () virtual default
Member Function Documentation
shared_rom()
std::shared_ptr< Rom > yaze::app::SharedRom::shared_rom () inline
References shared_rom_.
rom()
auto yaze::app::SharedRom::rom () inline
References rom(), and shared_rom_.
Referenced by yaze::app::zelda3::dungeon::RoomObject::AddTiles(), yaze::app::zelda3::overworld::Overworld::AssembleMap16Tiles(), yaze::app::zelda3::overworld::Overworld::AssembleMap32Tiles(), yaze::app::editor::MessageEditor::BuildDictionaryEntries(), yaze::app::zelda3::screen::Inventory::BuildTileset(), yaze::app::zelda3::dungeon::Room::CopyRoomGraphicsToBuffer(), yaze::app::zelda3::screen::Inventory::Create(), yaze::app::zelda3::overworld::Overworld::DecompressAllMapTiles(), yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::editor::GfxGroupEditor::DrawBlocksetViewer(), yaze::app::editor::GraphicsEditor::DrawCgxImport(), yaze::app::gui::Canvas::DrawContextMenu(), yaze::app::editor::MessageEditor::DrawCurrentMessage(), yaze::app::editor::SpriteEditor::DrawCurrentSheets(), yaze::app::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::DungeonEditor::DrawEntranceSelector(), yaze::app::editor::MasterEditor::DrawFileDialog(), yaze::app::editor::MasterEditor::DrawFileMenu(), yaze::app::editor::GraphicsEditor::DrawGfxEditToolset(), yaze::app::editor::MasterEditor::DrawInfoPopup(), yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::GraphicsEditor::DrawPaletteControls(), yaze::app::editor::PaletteEditor::DrawPaletteGroup(), yaze::app::editor::GfxGroupEditor::DrawPaletteViewer(), yaze::app::editor::MasterEditor::DrawProjectMenu(), yaze::app::editor::DungeonEditor::DrawRoomSelector(), yaze::app::editor::GfxGroupEditor::DrawRoomsetViewer(), yaze::app::editor::GraphicsEditor::DrawScrImport(), yaze::app::editor::GfxGroupEditor::DrawSpritesetViewer(), yaze::app::editor::SpriteEditor::DrawSpritesList(), yaze::app::editor::Tile16Editor::DrawTileEditControls(), yaze::app::editor::MusicEditor::DrawToolset(), yaze::app::editor::DungeonEditor::Initialize(), yaze::app::editor::MessageEditor::Initialize(), yaze::app::zelda3::overworld::Overworld::Load(), yaze::app::zelda3::dungeon::Room::LoadAnimatedGraphics(), yaze::app::zelda3::dungeon::Room::LoadChests(), yaze::app::editor::ScreenEditor::LoadDungeonMaps(), yaze::app::editor::ScreenEditor::LoadDungeonMapTile16(), yaze::app::zelda3::overworld::Overworld::LoadEntrances(), yaze::app::zelda3::overworld::Overworld::LoadExits(), yaze::app::zelda3::dungeon::Room::LoadHeader(), yaze::app::zelda3::overworld::Overworld::LoadItems(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::LoadObject(), yaze::app::zelda3::dungeon::Room::LoadObjects(), yaze::app::zelda3::overworld::Overworld::LoadPrototype(), yaze::app::editor::MasterEditor::LoadRom(), yaze::app::zelda3::dungeon::Room::LoadRoomFromROM(), yaze::app::zelda3::dungeon::Room::LoadRoomGraphics(), yaze::app::zelda3::dungeon::Room::LoadSprites(), yaze::app::zelda3::overworld::Overworld::LoadSpritesFromMap(), yaze::app::editor::Tile16Editor::LoadTile8(), yaze::app::zelda3::overworld::Overworld::LoadTileTypes(), yaze::app::editor::MasterEditor::OpenProject(), yaze::app::editor::MasterEditor::OpenRomOrProject(), yaze::app::editor::MessageEditor::ReadAllTextData(), yaze::app::editor::DungeonEditor::RefreshGraphics(), yaze::app::editor::OverworldEditor::RefreshOverworldMap(), yaze::app::editor::OverworldEditor::RefreshTile16Blockset(), rom(), yaze::app::emu::Emulator::Run(), yaze::app::editor::MessageEditor::Save(), yaze::app::zelda3::overworld::Overworld::Save(), yaze::app::editor::ScreenEditor::SaveDungeonMaps(), yaze::app::zelda3::overworld::Overworld::SaveEntrances(), yaze::app::zelda3::overworld::Overworld::SaveExits(), yaze::app::zelda3::overworld::Overworld::SaveItems(), yaze::app::zelda3::overworld::Overworld::SaveLargeMaps(), yaze::app::zelda3::overworld::Overworld::SaveMap16Tiles(), yaze::app::zelda3::overworld::Overworld::SaveMap32Tiles(), yaze::app::zelda3::overworld::Overworld::SaveMapProperties(), yaze::app::zelda3::overworld::Overworld::SaveOverworldMaps(), yaze::app::editor::MasterEditor::SaveRom(), yaze::app::editor::Tile16Editor::SetCurrentTile(), yaze::app::editor::MasterEditor::SetupScreen(), yaze::app::zelda3::dungeon::Subtype1::Subtype1(), yaze::app::zelda3::dungeon::Subtype2::Subtype2(), yaze::app::zelda3::dungeon::Subtype3::Subtype3(), yaze::app::editor::DungeonEditor::Update(), yaze::app::editor::GfxGroupEditor::Update(), yaze::app::editor::GraphicsEditor::Update(), yaze::app::editor::MasterEditor::Update(), yaze::app::editor::MemoryEditorWithDiffChecker::Update(), yaze::app::editor::MessageEditor::Update(), yaze::app::editor::PaletteEditor::Update(), yaze::app::editor::ScreenEditor::Update(), yaze::app::editor::SpriteEditor::Update(), yaze::app::editor::Tile16Editor::UpdateBlockset(), yaze::app::editor::DungeonEditor::UpdateDungeonRoomView(), yaze::app::editor::GraphicsEditor::UpdateGfxEdit(), yaze::app::editor::GraphicsEditor::UpdateGfxSheetList(), yaze::app::editor::GraphicsEditor::UpdateGfxTabView(), yaze::app::editor::GraphicsEditor::UpdateLinkGfxView(), yaze::app::zelda3::dungeon::DungeonObjectRenderer::UpdateObjectBitmap(), yaze::app::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::app::editor::GraphicsEditor::UpdateScadView(), yaze::app::editor::Tile16Editor::UpdateTile16Edit(), and yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
Member Data Documentation
shared_rom_
std::shared_ptr< Rom > yaze::app::SharedRom::shared_rom_ = nullptr static
Referenced by rom(), and shared_rom().
The documentation for this class was generated from the following files:
src/app/rom.h
src/app/rom.cc