yaze: yaze::gfx::TexturePool Class Reference
yaze::gfx::TexturePool Class Reference
#include <texture_pool.h>
Public Member Functions
SDL_Texture * GetTexture (SDL_Renderer *renderer, int width, int height, Uint32 format)
void ReturnTexture (SDL_Texture *texture, int width, int height, Uint32 format)
void Clear ()
Static Public Member Functions
static TexturePool & GetInstance ()
Private Member Functions
TexturePool ()=default
std::string GenerateKey (int width, int height, Uint32 format)
Private Attributes
std::unordered_map< std::string, std::vector< SDL_Texture * > > available_textures_
Detailed Description
Definition at line 13 of file texture_pool.h.
Constructor & Destructor Documentation
TexturePool()
yaze::gfx::TexturePool::TexturePool () private default
Referenced by GetInstance().
Member Function Documentation
GetInstance()
static TexturePool & yaze::gfx::TexturePool::GetInstance () inline static
Definition at line 15 of file texture_pool.h.
References TexturePool().
Referenced by yaze::gfx::Bitmap::CreateTexture().
GetTexture()
SDL_Texture * yaze::gfx::TexturePool::GetTexture (SDL_Renderer * renderer, int width, int height, Uint32 format) inline
Definition at line 20 of file texture_pool.h.
References available_textures_, and GenerateKey().
Referenced by yaze::gfx::Bitmap::CreateTexture().
ReturnTexture()
void yaze::gfx::TexturePool::ReturnTexture (SDL_Texture * texture, int width, int height, Uint32 format) inline
Definition at line 37 of file texture_pool.h.
References available_textures_, and GenerateKey().
Referenced by yaze::gfx::Bitmap::CreateTexture().
Clear()
void yaze::gfx::TexturePool::Clear () inline
Definition at line 45 of file texture_pool.h.
References available_textures_.
GenerateKey()
std::string yaze::gfx::TexturePool::GenerateKey (int width, int height, Uint32 format) inline private
Definition at line 57 of file texture_pool.h.
Referenced by GetTexture(), and ReturnTexture().
Member Data Documentation
available_textures_
std::unordered_map<std::string, std::vector<SDL_Texture*> > yaze::gfx::TexturePool::available_textures_ private
Definition at line 63 of file texture_pool.h.
Referenced by Clear(), GetTexture(), and ReturnTexture().
The documentation for this class was generated from the following file:
src/app/gfx/texture_pool.h