yaze: yaze::app::emu::CpuTest Class Reference
yaze::app::emu::CpuTest Class Reference
Public Member Functions
void SetUp () override
Public Attributes
AsmParser asm_parser
memory::MockMemory mock_memory
memory::MockClock mock_clock
Cpu cpu {mock_memory, mock_clock}
Detailed Description
Test
Test fixture for CPU unit tests
Member Function Documentation
SetUp()
void yaze::app::emu::CpuTest::SetUp () inline override
References asm_parser, yaze::app::emu::memory::Memory::ClearMemory(), yaze::app::emu::AsmParser::CreateInternalOpcodeMap(), yaze::app::emu::memory::MockMemory::Init(), and mock_memory.
Member Data Documentation
asm_parser
AsmParser yaze::app::emu::CpuTest::asm_parser
Referenced by SetUp().
cpu
Cpu yaze::app::emu::CpuTest::cpu {mock_memory, mock_clock}
mock_clock
memory::MockClock yaze::app::emu::CpuTest::mock_clock
mock_memory
memory::MockMemory yaze::app::emu::CpuTest::mock_memory
Referenced by SetUp().
The documentation for this class was generated from the following file:
test/emu/cpu_test.cc