yaze: yaze::app::emu::AsmParser Class Reference
yaze::app::emu::AsmParser Class Reference
#include <asm_parser.h>
Public Member Functions
std::vector< uint8_t > Parse (const std::string &instruction)
std::vector< std::string > Tokenize (const std::string &instruction)
Private Member Functions
void AppendOperandBytes (std::vector< uint8_t > &bytes, const std::string &operand, const AddressingMode &addressing_mode)
AddressingMode DetermineMode (const std::vector< std::string > &tokens)
bool TryParseByte (const std::string &str, uint8_t &value)
bool TryParseHex (const std::string &str, uint32_t &value)
void CreateInternalOpcodeMap ()
Private Attributes
std::unordered_map< MnemonicMode, uint8_t, MnemonicModeHash > mnemonic_to_opcode_
Member Function Documentation
Parse()
std::vector< uint8_t > yaze::app::emu::AsmParser::Parse (const std::string & instruction) inline
References AppendOperandBytes(), CreateInternalOpcodeMap(), DetermineMode(), mnemonic_to_opcode_, and Tokenize().
Referenced by yaze_test::emu_test::TEST_F().
Tokenize()
std::vector< std::string > yaze::app::emu::AsmParser::Tokenize (const std::string & instruction) inline
Referenced by Parse(), yaze_test::emu_test::TEST_F(), and yaze_test::emu_test::TEST_F().
AppendOperandBytes()
void yaze::app::emu::AsmParser::AppendOperandBytes (std::vector< uint8_t > & bytes, const std::string & operand, const AddressingMode & addressing_mode) inline private
References yaze::app::emu::kAbsolute, yaze::app::emu::kAbsoluteLong, yaze::app::emu::kImmediate, and yaze::app::emu::kImplied.
Referenced by Parse().
DetermineMode()
AddressingMode yaze::app::emu::AsmParser::DetermineMode (const std::vector< std::string > & tokens) inline private
References yaze::app::emu::kAbsolute, yaze::app::emu::kAbsoluteLong, yaze::app::emu::kImmediate, and yaze::app::emu::kImplied.
Referenced by Parse().
TryParseByte()
bool yaze::app::emu::AsmParser::TryParseByte (const std::string & str, uint8_t & value) inline private
TryParseHex()
bool yaze::app::emu::AsmParser::TryParseHex (const std::string & str, uint32_t & value) inline private
CreateInternalOpcodeMap()
void yaze::app::emu::AsmParser::CreateInternalOpcodeMap () inline private
References yaze::app::emu::kAbsolute, yaze::app::emu::kAbsoluteIndexedX, yaze::app::emu::kAbsoluteIndexedY, yaze::app::emu::kAbsoluteIndirect, yaze::app::emu::kAccumulator, yaze::app::emu::kDirectPage, yaze::app::emu::kDirectPageIndexedX, yaze::app::emu::kDirectPageIndexedY, yaze::app::emu::kDirectPageIndirect, yaze::app::emu::kDirectPageIndirectIndexedY, yaze::app::emu::kImmediate, yaze::app::emu::kImplied, yaze::app::emu::kProgramCounterRelative, yaze::app::emu::kProgramCounterRelativeLong, yaze::app::emu::kStackRelative, yaze::app::emu::kStackRelativeIndirectIndexedY, and mnemonic_to_opcode_.
Referenced by Parse().
Member Data Documentation
mnemonic_to_opcode_
std::unordered_map<MnemonicMode, uint8_t, MnemonicModeHash> yaze::app::emu::AsmParser::mnemonic_to_opcode_ private
Referenced by CreateInternalOpcodeMap(), and Parse().
The documentation for this class was generated from the following file:
src/app/emu/debug/asm_parser.h