yaze: yaze::app::core::FileDialogWrapper Class Reference
yaze::app::core::FileDialogWrapper Class Reference
#include <file_dialog.h>
Static Public Member Functions
static std::string ShowOpenFileDialog ()
static std::string ShowOpenFolderDialog ()
static std::vector< std::string > GetSubdirectoriesInFolder (const std::string &folder_path)
static std::vector< std::string > GetFilesInFolder (const std::string &folder_path)
Detailed Description
Definition at line 11 of file file_dialog.h.
Member Function Documentation
ShowOpenFileDialog()
static std::string yaze::app::core::FileDialogWrapper::ShowOpenFileDialog () static
Referenced by yaze::app::editor::SpriteEditor::DrawCustomSpritesMetadata(), yaze::app::editor::EditorManager::DrawYazeMenuBar(), yaze::app::editor::EditorManager::LoadRom(), yaze::app::emu::Emulator::RenderNavBar(), and yaze::app::editor::MemoryEditorWithDiffChecker::Update().
ShowOpenFolderDialog()
static std::string yaze::app::core::FileDialogWrapper::ShowOpenFolderDialog () static
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar(), and yaze::app::editor::AssemblyEditor::UpdateCodeView().
GetSubdirectoriesInFolder()
static std::vector< std::string > yaze::app::core::FileDialogWrapper::GetSubdirectoriesInFolder (const std::string & folder_path) static
Referenced by yaze::app::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
GetFilesInFolder()
static std::vector< std::string > yaze::app::core::FileDialogWrapper::GetFilesInFolder (const std::string & folder_path) static
Referenced by yaze::app::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
The documentation for this class was generated from the following file:
src/app/core/platform/file_dialog.h