yaze: yaze::editor::DungeonUsageTracker Class Reference
yaze::editor::DungeonUsageTracker Class Reference
Tracks and analyzes usage statistics for dungeon resources.
#include <dungeon_usage_tracker.h>
Public Member Functions
DungeonUsageTracker ()=default
void CalculateUsageStats (const std::array< zelda3::Room, 0x128 > &rooms)
void DrawUsageStats ()
void DrawUsageGrid ()
void RenderSetUsage (const absl::flat_hash_map< uint16_t, int > &usage_map, uint16_t &selected_set, int spriteset_offset=0x00)
const absl::flat_hash_map< uint16_t, int > & GetBlocksetUsage () const
const absl::flat_hash_map< uint16_t, int > & GetSpritesetUsage () const
const absl::flat_hash_map< uint16_t, int > & GetPaletteUsage () const
uint16_t GetSelectedBlockset () const
uint16_t GetSelectedSpriteset () const
uint16_t GetSelectedPalette () const
void SetSelectedBlockset (uint16_t blockset)
void SetSelectedSpriteset (uint16_t spriteset)
void SetSelectedPalette (uint16_t palette)
void ClearUsageStats ()
Private Attributes
absl::flat_hash_map< uint16_t, int > spriteset_usage_
absl::flat_hash_map< uint16_t, int > blockset_usage_
absl::flat_hash_map< uint16_t, int > palette_usage_
uint16_t selected_blockset_ = 0xFFFF
uint16_t selected_spriteset_ = 0xFFFF
uint16_t selected_palette_ = 0xFFFF
Detailed Description
Tracks and analyzes usage statistics for dungeon resources.
This component manages blockset, spriteset, and palette usage statistics across all dungeon rooms, providing insights for optimization.
Definition at line 16 of file dungeon_usage_tracker.h.
Constructor & Destructor Documentation
DungeonUsageTracker()
yaze::editor::DungeonUsageTracker::DungeonUsageTracker () default
Member Function Documentation
CalculateUsageStats()
void yaze::editor::DungeonUsageTracker::CalculateUsageStats (const std::array< zelda3::Room, 0x128 > & rooms)
Definition at line 7 of file dungeon_usage_tracker.cc.
References blockset_usage_, palette_usage_, and spriteset_usage_.
Referenced by yaze::editor::DungeonEditor::Load().
DrawUsageStats()
void yaze::editor::DungeonUsageTracker::DrawUsageStats ()
Definition at line 33 of file dungeon_usage_tracker.cc.
References blockset_usage_, ClearUsageStats(), palette_usage_, and spriteset_usage_.
DrawUsageGrid()
void yaze::editor::DungeonUsageTracker::DrawUsageGrid ()
Todo:
Implement usage grid visualization
Definition at line 67 of file dungeon_usage_tracker.cc.
RenderSetUsage()
void yaze::editor::DungeonUsageTracker::RenderSetUsage (const absl::flat_hash_map< uint16_t, int > & usage_map, uint16_t & selected_set, int spriteset_offset = 0x00)
Todo:
Implement set usage rendering
Definition at line 72 of file dungeon_usage_tracker.cc.
GetBlocksetUsage()
const absl::flat_hash_map< uint16_t, int > & yaze::editor::DungeonUsageTracker::GetBlocksetUsage () const inline
Definition at line 28 of file dungeon_usage_tracker.h.
References blockset_usage_.
Referenced by yaze::test::TEST(), and yaze::test::TEST().
GetSpritesetUsage()
const absl::flat_hash_map< uint16_t, int > & yaze::editor::DungeonUsageTracker::GetSpritesetUsage () const inline
Definition at line 29 of file dungeon_usage_tracker.h.
References spriteset_usage_.
Referenced by yaze::test::TEST().
GetPaletteUsage()
const absl::flat_hash_map< uint16_t, int > & yaze::editor::DungeonUsageTracker::GetPaletteUsage () const inline
Definition at line 30 of file dungeon_usage_tracker.h.
References palette_usage_.
Referenced by yaze::test::TEST().
GetSelectedBlockset()
uint16_t yaze::editor::DungeonUsageTracker::GetSelectedBlockset () const inline
Definition at line 33 of file dungeon_usage_tracker.h.
References selected_blockset_.
Referenced by yaze::test::TEST().
GetSelectedSpriteset()
uint16_t yaze::editor::DungeonUsageTracker::GetSelectedSpriteset () const inline
Definition at line 34 of file dungeon_usage_tracker.h.
References selected_spriteset_.
Referenced by yaze::test::TEST().
GetSelectedPalette()
uint16_t yaze::editor::DungeonUsageTracker::GetSelectedPalette () const inline
Definition at line 35 of file dungeon_usage_tracker.h.
References selected_palette_.
Referenced by yaze::test::TEST().
SetSelectedBlockset()
void yaze::editor::DungeonUsageTracker::SetSelectedBlockset (uint16_t blockset) inline
Definition at line 37 of file dungeon_usage_tracker.h.
References selected_blockset_.
Referenced by yaze::test::TEST().
SetSelectedSpriteset()
void yaze::editor::DungeonUsageTracker::SetSelectedSpriteset (uint16_t spriteset) inline
Definition at line 38 of file dungeon_usage_tracker.h.
References selected_spriteset_.
Referenced by yaze::test::TEST().
SetSelectedPalette()
void yaze::editor::DungeonUsageTracker::SetSelectedPalette (uint16_t palette) inline
Definition at line 39 of file dungeon_usage_tracker.h.
References selected_palette_.
Referenced by yaze::test::TEST().
ClearUsageStats()
void yaze::editor::DungeonUsageTracker::ClearUsageStats ()
Definition at line 78 of file dungeon_usage_tracker.cc.
References blockset_usage_, palette_usage_, selected_blockset_, selected_palette_, selected_spriteset_, and spriteset_usage_.
Referenced by DrawUsageStats(), and yaze::test::TEST().
Member Data Documentation
spriteset_usage_
absl::flat_hash_map<uint16_t, int> yaze::editor::DungeonUsageTracker::spriteset_usage_ private
Definition at line 45 of file dungeon_usage_tracker.h.
Referenced by CalculateUsageStats(), ClearUsageStats(), DrawUsageStats(), and GetSpritesetUsage().
blockset_usage_
absl::flat_hash_map<uint16_t, int> yaze::editor::DungeonUsageTracker::blockset_usage_ private
Definition at line 46 of file dungeon_usage_tracker.h.
Referenced by CalculateUsageStats(), ClearUsageStats(), DrawUsageStats(), and GetBlocksetUsage().
palette_usage_
absl::flat_hash_map<uint16_t, int> yaze::editor::DungeonUsageTracker::palette_usage_ private
Definition at line 47 of file dungeon_usage_tracker.h.
Referenced by CalculateUsageStats(), ClearUsageStats(), DrawUsageStats(), and GetPaletteUsage().
selected_blockset_
uint16_t yaze::editor::DungeonUsageTracker::selected_blockset_ = 0xFFFF private
Definition at line 49 of file dungeon_usage_tracker.h.
Referenced by ClearUsageStats(), GetSelectedBlockset(), and SetSelectedBlockset().
selected_spriteset_
uint16_t yaze::editor::DungeonUsageTracker::selected_spriteset_ = 0xFFFF private
Definition at line 50 of file dungeon_usage_tracker.h.
Referenced by ClearUsageStats(), GetSelectedSpriteset(), and SetSelectedSpriteset().
selected_palette_
uint16_t yaze::editor::DungeonUsageTracker::selected_palette_ = 0xFFFF private
Definition at line 51 of file dungeon_usage_tracker.h.
Referenced by ClearUsageStats(), GetSelectedPalette(), and SetSelectedPalette().
The documentation for this class was generated from the following files:
src/app/editor/dungeon/dungeon_usage_tracker.h
src/app/editor/dungeon/dungeon_usage_tracker.cc