yaze: yaze::app::zelda3::SpriteAction Class Reference
yaze::app::zelda3::SpriteAction Class Reference
#include <sprite_builder.h>
Public Member Functions
SpriteAction & AddInstruction (const SpriteInstruction &instruction)
SpriteAction & AddCustomInstruction (const std::string &asmCode)
SpriteAction & SetNextAction (const std::string &nextActionName)
std::string GetConfiguration () const
Static Public Member Functions
static SpriteAction Create (const std::string &actionName)
static SpriteAction Create ()
Private Attributes
std::string name
std::vector< std::string > instructions
std::string nextAction
Member Function Documentation
Create() [1/2]
SpriteAction yaze::app::zelda3::SpriteAction::Create (const std::string & actionName) static
Create() [2/2]
SpriteAction yaze::app::zelda3::SpriteAction::Create () static
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
AddInstruction()
SpriteAction & yaze::app::zelda3::SpriteAction::AddInstruction (const SpriteInstruction & instruction)
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
AddCustomInstruction()
SpriteAction & yaze::app::zelda3::SpriteAction::AddCustomInstruction (const std::string & asmCode)
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
SetNextAction()
SpriteAction & yaze::app::zelda3::SpriteAction::SetNextAction (const std::string & nextActionName)
Referenced by yaze_test::zelda3_test::SpriteBuilderTest::SetUp().
GetConfiguration()
std::string yaze::app::zelda3::SpriteAction::GetConfiguration () const
Member Data Documentation
name
std::string yaze::app::zelda3::SpriteAction::name private
instructions
std::vector<std::string> yaze::app::zelda3::SpriteAction::instructions private
nextAction
std::string yaze::app::zelda3::SpriteAction::nextAction private
The documentation for this class was generated from the following files:
src/app/zelda3/sprite/sprite_builder.h
src/app/zelda3/sprite/sprite_builder.cc