yaze: yaze::SharedRom Class Reference
yaze::SharedRom Class Reference
A class to hold a shared pointer to a Rom object.
#include <rom.h>
Public Member Functions
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Static Public Attributes
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
A class to hold a shared pointer to a Rom object.
Definition at line 577 of file rom.h.
Constructor & Destructor Documentation
SharedRom()
yaze::SharedRom::SharedRom () default
~SharedRom()
virtual yaze::SharedRom::~SharedRom () virtual default
Member Function Documentation
shared_rom()
std::shared_ptr< Rom > yaze::SharedRom::shared_rom () inline
Definition at line 582 of file rom.h.
References shared_rom_.
rom()
auto yaze::SharedRom::rom () inline
Definition at line 589 of file rom.h.
References rom(), and shared_rom_.
Referenced by yaze::zelda3::dungeon::RoomObject::AddTiles(), yaze::zelda3::overworld::Overworld::AssembleMap16Tiles(), yaze::zelda3::overworld::Overworld::AssembleMap32Tiles(), yaze::zelda3::screen::Inventory::BuildTileset(), yaze::zelda3::dungeon::Room::CopyRoomGraphicsToBuffer(), yaze::zelda3::screen::Inventory::Create(), yaze::zelda3::overworld::Overworld::DecompressAllMapTiles(), yaze::editor::GraphicsEditor::DecompressImportData(), yaze::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::editor::GfxGroupEditor::DrawBlocksetViewer(), yaze::gui::Canvas::DrawContextMenu(), yaze::editor::SpriteEditor::DrawCurrentSheets(), yaze::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::editor::DungeonEditor::DrawEntranceSelector(), yaze::editor::GraphicsEditor::DrawGfxEditToolset(), yaze::editor::EditorManager::DrawInfoPopup(), yaze::editor::ScreenEditor::DrawInventoryMenuEditor(), yaze::editor::GraphicsEditor::DrawPaletteControls(), yaze::editor::PaletteEditor::DrawPaletteGroup(), yaze::editor::GfxGroupEditor::DrawPaletteViewer(), yaze::editor::DungeonEditor::DrawRoomSelector(), yaze::editor::GfxGroupEditor::DrawRoomsetViewer(), yaze::editor::GfxGroupEditor::DrawSpritesetViewer(), yaze::editor::SpriteEditor::DrawSpritesList(), yaze::editor::OverworldEditor::DrawTile8Selector(), yaze::editor::MusicEditor::DrawToolset(), yaze::editor::EditorManager::DrawYazeMenuBar(), yaze::editor::DungeonEditor::Initialize(), yaze::editor::MessageEditor::Initialize(), yaze::zelda3::overworld::Overworld::Load(), yaze::zelda3::dungeon::Room::LoadAnimatedGraphics(), yaze::editor::ScreenEditor::LoadBinaryGfx(), yaze::zelda3::dungeon::Room::LoadChests(), yaze::editor::ScreenEditor::LoadDungeonMaps(), yaze::editor::ScreenEditor::LoadDungeonMapTile16(), yaze::zelda3::overworld::Overworld::LoadEntrances(), yaze::zelda3::overworld::Overworld::LoadExits(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::zelda3::dungeon::Room::LoadHeader(), yaze::zelda3::overworld::Overworld::LoadItems(), yaze::zelda3::dungeon::DungeonObjectRenderer::LoadObject(), yaze::zelda3::dungeon::Room::LoadObjects(), yaze::editor::EditorManager::LoadRom(), yaze::zelda3::dungeon::Room::LoadRoomFromROM(), yaze::zelda3::dungeon::Room::LoadRoomGraphics(), yaze::zelda3::dungeon::Room::LoadSprites(), yaze::zelda3::overworld::Overworld::LoadSpritesFromMap(), yaze::editor::Tile16Editor::LoadTile8(), yaze::zelda3::overworld::Overworld::LoadTileTypes(), yaze::editor::EditorManager::OpenProject(), yaze::editor::EditorManager::OpenRomOrProject(), yaze::editor::MessageEditor::ReadAllTextData(), yaze::editor::MessageEditor::ReadAllTextDataV2(), yaze::editor::DungeonEditor::RefreshGraphics(), rom(), yaze::emu::Emulator::Run(), yaze::editor::MessageEditor::Save(), yaze::zelda3::overworld::Overworld::Save(), yaze::editor::ScreenEditor::SaveDungeonMaps(), yaze::editor::ScreenEditor::SaveDungeonMapTile16(), yaze::zelda3::overworld::Overworld::SaveEntrances(), yaze::zelda3::overworld::Overworld::SaveExits(), yaze::zelda3::overworld::Overworld::SaveItems(), yaze::zelda3::overworld::Overworld::SaveLargeMaps(), yaze::zelda3::overworld::Overworld::SaveMap16Expanded(), yaze::zelda3::overworld::Overworld::SaveMap16Tiles(), yaze::zelda3::overworld::Overworld::SaveMap32Expanded(), yaze::zelda3::overworld::Overworld::SaveMap32Tiles(), yaze::zelda3::overworld::Overworld::SaveMapProperties(), yaze::zelda3::overworld::Overworld::SaveOverworldMaps(), yaze::editor::EditorManager::SaveRom(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::test::zelda3::DungeonRoomTest::SetUp(), yaze::editor::EditorManager::SetupScreen(), yaze::zelda3::dungeon::Subtype1::Subtype1(), yaze::zelda3::dungeon::Subtype2::Subtype2(), yaze::zelda3::dungeon::Subtype3::Subtype3(), yaze::editor::DungeonEditor::Update(), yaze::editor::EditorManager::Update(), yaze::editor::GfxGroupEditor::Update(), yaze::editor::GraphicsEditor::Update(), yaze::editor::MemoryEditorWithDiffChecker::Update(), yaze::editor::MessageEditor::Update(), yaze::editor::OverworldEditor::Update(), yaze::editor::PaletteEditor::Update(), yaze::editor::ScreenEditor::Update(), yaze::editor::SpriteEditor::Update(), yaze::editor::Tile16Editor::UpdateBlockset(), yaze::editor::DungeonEditor::UpdateDungeonRoomView(), yaze::editor::GraphicsEditor::UpdateGfxEdit(), yaze::editor::GraphicsEditor::UpdateGfxSheetList(), yaze::editor::GraphicsEditor::UpdateGfxTabView(), yaze::editor::GraphicsEditor::UpdateLinkGfxView(), yaze::zelda3::dungeon::DungeonObjectRenderer::UpdateObjectBitmap(), yaze::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::editor::Tile16Editor::UpdateTile16Edit(), and yaze::editor::OverworldEditor::UpdateUsageStats().
Member Data Documentation
shared_rom_
std::shared_ptr< Rom > yaze::SharedRom::shared_rom_ = nullptr static
Definition at line 598 of file rom.h.
Referenced by rom(), and shared_rom().
The documentation for this class was generated from the following files:
src/app/rom.h
src/app/rom.cc