yaze: yaze::gui::EnhancedPaletteEditor Class Reference
yaze::gui::EnhancedPaletteEditor Class Reference
Enhanced palette editor with ROM integration and analysis tools.
#include <enhanced_palette_editor.h>
Public Member Functions
EnhancedPaletteEditor ()=default
void Initialize (Rom *rom)
Initialize the palette editor with ROM data.
void ShowPaletteEditor (gfx::SnesPalette &palette, const std::string &title="Palette Editor")
Show the main palette editor window.
void ShowROMPaletteManager ()
Show the ROM palette manager window.
void ShowColorAnalysis (const gfx::Bitmap &bitmap, const std::string &title="Color Analysis")
Show color analysis window for a bitmap.
bool ApplyROMPalette (gfx::Bitmap *bitmap, int group_index, int palette_index)
Apply a ROM palette group to a bitmap.
const gfx::SnesPalette * GetSelectedROMPalette () const
Get the currently selected ROM palette.
void SavePaletteBackup (const gfx::SnesPalette &palette)
Save current palette as backup.
bool RestorePaletteBackup (gfx::SnesPalette &palette)
Restore palette from backup.
bool IsROMLoaded () const
int GetCurrentGroupIndex () const
int GetCurrentPaletteIndex () const
Private Member Functions
void DrawPaletteGrid (gfx::SnesPalette &palette, int cols=8)
void DrawROMPaletteSelector ()
void DrawColorEditControls (gfx::SnesColor &color, int color_index)
void DrawPaletteAnalysis (const gfx::SnesPalette &palette)
void LoadROMPalettes ()
Private Attributes
Rom * rom_ = nullptr
std::vector< gfx::SnesPalette > rom_palette_groups_
std::vector< std::string > palette_group_names_
gfx::SnesPalette backup_palette_
int current_group_index_ = 0
int current_palette_index_ = 0
bool rom_palettes_loaded_ = false
bool show_color_analysis_ = false
bool show_rom_manager_ = false
int editing_color_index_ = -1
ImVec4 temp_color_ = ImVec4(0, 0, 0, 1)
Detailed Description
Enhanced palette editor with ROM integration and analysis tools.
Definition at line 17 of file enhanced_palette_editor.h.
Constructor & Destructor Documentation
EnhancedPaletteEditor()
yaze::gui::EnhancedPaletteEditor::EnhancedPaletteEditor () default
Member Function Documentation
Initialize()
void yaze::gui::EnhancedPaletteEditor::Initialize (Rom * rom)
Initialize the palette editor with ROM data.
Definition at line 14 of file enhanced_palette_editor.cc.
References LoadROMPalettes(), rom_, and rom_palettes_loaded_.
ShowPaletteEditor()
void yaze::gui::EnhancedPaletteEditor::ShowPaletteEditor (gfx::SnesPalette & palette, const std::string & title = "Palette Editor")
Show the main palette editor window.
Definition at line 22 of file enhanced_palette_editor.cc.
References current_group_index_, DrawPaletteAnalysis(), DrawPaletteGrid(), DrawROMPaletteSelector(), RestorePaletteBackup(), rom_, rom_palette_groups_, and SavePaletteBackup().
ShowROMPaletteManager()
void yaze::gui::EnhancedPaletteEditor::ShowROMPaletteManager ()
Show the ROM palette manager window.
Definition at line 66 of file enhanced_palette_editor.cc.
References current_group_index_, DrawPaletteAnalysis(), DrawPaletteGrid(), DrawROMPaletteSelector(), LoadROMPalettes(), palette_group_names_, rom_, rom_palette_groups_, rom_palettes_loaded_, and show_rom_manager_.
ShowColorAnalysis()
void yaze::gui::EnhancedPaletteEditor::ShowColorAnalysis (const gfx::Bitmap & bitmap, const std::string & title = "Color Analysis")
Show color analysis window for a bitmap.
Definition at line 95 of file enhanced_palette_editor.cc.
References yaze::gfx::Bitmap::height(), yaze::gfx::Bitmap::is_active(), yaze::gfx::Bitmap::palette(), show_color_analysis_, yaze::gfx::SnesPalette::size(), yaze::gfx::Bitmap::vector(), and yaze::gfx::Bitmap::width().
ApplyROMPalette()
bool yaze::gui::EnhancedPaletteEditor::ApplyROMPalette (gfx::Bitmap * bitmap, int group_index, int palette_index)
Apply a ROM palette group to a bitmap.
Definition at line 153 of file enhanced_palette_editor.cc.
References current_group_index_, current_palette_index_, yaze::core::Renderer::Get(), yaze::gfx::Bitmap::palette(), palette_group_names_, rom_palette_groups_, rom_palettes_loaded_, SavePaletteBackup(), yaze::gfx::Bitmap::SetPalette(), yaze::gfx::Bitmap::SetPaletteWithTransparent(), and yaze::core::Renderer::UpdateBitmap().
GetSelectedROMPalette()
const gfx::SnesPalette * yaze::gui::EnhancedPaletteEditor::GetSelectedROMPalette () const
Get the currently selected ROM palette.
Definition at line 187 of file enhanced_palette_editor.cc.
References current_group_index_, rom_palette_groups_, and rom_palettes_loaded_.
SavePaletteBackup()
void yaze::gui::EnhancedPaletteEditor::SavePaletteBackup (const gfx::SnesPalette & palette)
Save current palette as backup.
Definition at line 196 of file enhanced_palette_editor.cc.
References backup_palette_.
Referenced by ApplyROMPalette(), and ShowPaletteEditor().
RestorePaletteBackup()
bool yaze::gui::EnhancedPaletteEditor::RestorePaletteBackup (gfx::SnesPalette & palette)
Restore palette from backup.
Definition at line 200 of file enhanced_palette_editor.cc.
References backup_palette_, and yaze::gfx::SnesPalette::size().
Referenced by ShowPaletteEditor().
IsROMLoaded()
bool yaze::gui::EnhancedPaletteEditor::IsROMLoaded () const inline
Definition at line 62 of file enhanced_palette_editor.h.
References rom_.
GetCurrentGroupIndex()
int yaze::gui::EnhancedPaletteEditor::GetCurrentGroupIndex () const inline
Definition at line 63 of file enhanced_palette_editor.h.
References current_group_index_.
GetCurrentPaletteIndex()
int yaze::gui::EnhancedPaletteEditor::GetCurrentPaletteIndex () const inline
Definition at line 64 of file enhanced_palette_editor.h.
References current_palette_index_.
DrawPaletteGrid()
void yaze::gui::EnhancedPaletteEditor::DrawPaletteGrid (gfx::SnesPalette & palette, int cols = 8) private
Definition at line 209 of file enhanced_palette_editor.cc.
References editing_color_index_, yaze::gfx::SnesPalette::size(), and temp_color_.
Referenced by ShowPaletteEditor(), and ShowROMPaletteManager().
DrawROMPaletteSelector()
void yaze::gui::EnhancedPaletteEditor::DrawROMPaletteSelector () private
Definition at line 287 of file enhanced_palette_editor.cc.
References current_group_index_, current_palette_index_, LoadROMPalettes(), palette_group_names_, rom_palette_groups_, and rom_palettes_loaded_.
Referenced by ShowPaletteEditor(), and ShowROMPaletteManager().
DrawColorEditControls()
void yaze::gui::EnhancedPaletteEditor::DrawColorEditControls (gfx::SnesColor & color, int color_index) private
Definition at line 329 of file enhanced_palette_editor.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::snes().
DrawPaletteAnalysis()
void yaze::gui::EnhancedPaletteEditor::DrawPaletteAnalysis (const gfx::SnesPalette & palette) private
Definition at line 365 of file enhanced_palette_editor.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesPalette::size().
Referenced by ShowPaletteEditor(), and ShowROMPaletteManager().
LoadROMPalettes()
void yaze::gui::EnhancedPaletteEditor::LoadROMPalettes () private
Definition at line 419 of file enhanced_palette_editor.cc.
References yaze::Rom::palette_group(), palette_group_names_, rom_, rom_palette_groups_, and rom_palettes_loaded_.
Referenced by DrawROMPaletteSelector(), Initialize(), and ShowROMPaletteManager().
Member Data Documentation
rom_
Rom* yaze::gui::EnhancedPaletteEditor::rom_ = nullptr private
Definition at line 73 of file enhanced_palette_editor.h.
Referenced by Initialize(), IsROMLoaded(), LoadROMPalettes(), ShowPaletteEditor(), and ShowROMPaletteManager().
rom_palette_groups_
std::vector<gfx::SnesPalette> yaze::gui::EnhancedPaletteEditor::rom_palette_groups_ private
Definition at line 74 of file enhanced_palette_editor.h.
Referenced by ApplyROMPalette(), DrawROMPaletteSelector(), GetSelectedROMPalette(), LoadROMPalettes(), ShowPaletteEditor(), and ShowROMPaletteManager().
palette_group_names_
std::vector<std::string> yaze::gui::EnhancedPaletteEditor::palette_group_names_ private
Definition at line 75 of file enhanced_palette_editor.h.
Referenced by ApplyROMPalette(), DrawROMPaletteSelector(), LoadROMPalettes(), and ShowROMPaletteManager().
backup_palette_
gfx::SnesPalette yaze::gui::EnhancedPaletteEditor::backup_palette_ private
Definition at line 76 of file enhanced_palette_editor.h.
Referenced by RestorePaletteBackup(), and SavePaletteBackup().
current_group_index_
int yaze::gui::EnhancedPaletteEditor::current_group_index_ = 0 private
Definition at line 78 of file enhanced_palette_editor.h.
Referenced by ApplyROMPalette(), DrawROMPaletteSelector(), GetCurrentGroupIndex(), GetSelectedROMPalette(), ShowPaletteEditor(), and ShowROMPaletteManager().
current_palette_index_
int yaze::gui::EnhancedPaletteEditor::current_palette_index_ = 0 private
Definition at line 79 of file enhanced_palette_editor.h.
Referenced by ApplyROMPalette(), DrawROMPaletteSelector(), and GetCurrentPaletteIndex().
rom_palettes_loaded_
bool yaze::gui::EnhancedPaletteEditor::rom_palettes_loaded_ = false private
Definition at line 80 of file enhanced_palette_editor.h.
Referenced by ApplyROMPalette(), DrawROMPaletteSelector(), GetSelectedROMPalette(), Initialize(), LoadROMPalettes(), and ShowROMPaletteManager().
show_color_analysis_
bool yaze::gui::EnhancedPaletteEditor::show_color_analysis_ = false private
Definition at line 81 of file enhanced_palette_editor.h.
Referenced by ShowColorAnalysis().
show_rom_manager_
bool yaze::gui::EnhancedPaletteEditor::show_rom_manager_ = false private
Definition at line 82 of file enhanced_palette_editor.h.
Referenced by ShowROMPaletteManager().
editing_color_index_
int yaze::gui::EnhancedPaletteEditor::editing_color_index_ = -1 private
Definition at line 85 of file enhanced_palette_editor.h.
Referenced by DrawPaletteGrid().
temp_color_
ImVec4 yaze::gui::EnhancedPaletteEditor::temp_color_ = ImVec4(0, 0, 0, 1) private
Definition at line 86 of file enhanced_palette_editor.h.
Referenced by DrawPaletteGrid().
The documentation for this class was generated from the following files:
src/app/gui/enhanced_palette_editor.h
src/app/gui/enhanced_palette_editor.cc