yaze: yaze::cli::ReadFromRom Class Reference
yaze::cli::ReadFromRom Class Reference
Read from a Rom file.
#include <command_handler.h>
Public Member Functions
absl::Status handle (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
app::Rom rom_
Detailed Description
Read from a Rom file.
Parameters
arg_vec -r <rom_file> <address> <optional:length, default: 0x01>
Returns
absl::Status
Definition at line 259 of file command_handler.h.
Member Function Documentation
handle()
absl::Status yaze::cli::ReadFromRom::handle (const std::vector< std::string > & arg_vec) inline override virtual
Implements yaze::cli::CommandHandler.
Definition at line 261 of file command_handler.h.
References yaze::app::Rom::LoadFromFile(), yaze::app::Rom::ReadByte(), yaze::app::Rom::ReadByteVector(), RETURN_IF_ERROR, and yaze::cli::CommandHandler::rom_.
The documentation for this class was generated from the following file:
src/cli/command_handler.h