yaze: yaze::cli::AsarPatch Class Reference
yaze::cli::AsarPatch Class Reference
#include <command_handler.h>
Public Member Functions
absl::Status handle (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
app::Rom rom_
Member Function Documentation
handle()
absl::Status yaze::cli::AsarPatch::handle (const std::vector< std::string > & arg_vec) inline override virtual
Implements yaze::cli::CommandHandler.
References asar_geterrors(), asar_patch(), yaze::app::Rom::LoadFromFile(), RETURN_IF_ERROR, yaze::cli::CommandHandler::rom_, and yaze::app::Rom::vector().
The documentation for this class was generated from the following file:
src/cli/command_handler.h