yaze: yaze::test::TestDungeonObjects Class Reference
yaze::test::TestDungeonObjects Class Reference
Simplified test framework for dungeon object rendering.
#include <test_dungeon_objects.h>
Protected Member Functions
void SetUp () override
void TearDown () override
absl::Status CreateTestRom ()
absl::Status SetupObjectData ()
std::vector< uint8_t > CreateObjectSubtypeTable (int base_addr, int count)
std::vector< uint8_t > CreateTileData (int base_addr, int tile_count)
std::vector< uint8_t > CreateRoomHeader (int room_id)
Protected Attributes
std::unique_ptr< MockRom > test_rom_
Static Protected Attributes
static constexpr int kTestObjectId = 0x01
static constexpr int kTestRoomId = 0x00
static constexpr size_t kTestRomSize = 0x100000
Detailed Description
Simplified test framework for dungeon object rendering.
This provides a clean, focused testing environment for dungeon object functionality without the complexity of full integration tests.
Definition at line 21 of file test_dungeon_objects.h.
Member Function Documentation
SetUp()
void yaze::test::TestDungeonObjects::SetUp () override protected
Definition at line 19 of file test_dungeon_objects.cc.
References CreateTestRom(), SetupObjectData(), and test_rom_.
TearDown()
void yaze::test::TestDungeonObjects::TearDown () override protected
Definition at line 25 of file test_dungeon_objects.cc.
References test_rom_.
CreateTestRom()
absl::Status yaze::test::TestDungeonObjects::CreateTestRom () protected
Definition at line 29 of file test_dungeon_objects.cc.
References CreateObjectSubtypeTable(), CreateTileData(), kTestRomSize, and test_rom_.
Referenced by SetUp().
SetupObjectData()
absl::Status yaze::test::TestDungeonObjects::SetupObjectData () protected
Definition at line 55 of file test_dungeon_objects.cc.
References CreateRoomHeader(), kTestObjectId, kTestRoomId, and test_rom_.
Referenced by SetUp().
CreateObjectSubtypeTable()
std::vector< uint8_t > yaze::test::TestDungeonObjects::CreateObjectSubtypeTable (int base_addr, int count) protected
Definition at line 67 of file test_dungeon_objects.cc.
Referenced by CreateTestRom().
CreateTileData()
std::vector< uint8_t > yaze::test::TestDungeonObjects::CreateTileData (int base_addr, int tile_count) protected
Definition at line 81 of file test_dungeon_objects.cc.
Referenced by CreateTestRom().
CreateRoomHeader()
std::vector< uint8_t > yaze::test::TestDungeonObjects::CreateRoomHeader (int room_id) protected
Definition at line 95 of file test_dungeon_objects.cc.
Referenced by SetupObjectData().
Member Data Documentation
test_rom_
std::unique_ptr<MockRom> yaze::test::TestDungeonObjects::test_rom_ protected
Definition at line 35 of file test_dungeon_objects.h.
Referenced by CreateTestRom(), SetUp(), SetupObjectData(), and TearDown().
kTestObjectId
int yaze::test::TestDungeonObjects::kTestObjectId = 0x01 static constexpr protected
Definition at line 38 of file test_dungeon_objects.h.
Referenced by SetupObjectData().
kTestRoomId
int yaze::test::TestDungeonObjects::kTestRoomId = 0x00 static constexpr protected
Definition at line 39 of file test_dungeon_objects.h.
Referenced by SetupObjectData().
kTestRomSize
size_t yaze::test::TestDungeonObjects::kTestRomSize = 0x100000 static constexpr protected
Definition at line 40 of file test_dungeon_objects.h.
Referenced by CreateTestRom().
The documentation for this class was generated from the following files:
test/zelda3/test_dungeon_objects.h
test/zelda3/test_dungeon_objects.cc