yaze: yaze::app::core::TaskManager< TFunc > Class Template Reference
yaze::app::core::TaskManager< TFunc > Class Template Reference
#include <common.h>
Public Member Functions
TaskManager ()=default
~TaskManager ()=default
TaskManager (int totalTasks, int timeoutSeconds)
void ExecuteTasks (const TFunc &taskFunc)
bool IsTaskComplete () const
void SetTimeout (int timeout)
Private Member Functions
void StartTimer ()
bool ShouldFinishTask ()
Private Attributes
int total_tasks_
int timeout_seconds_
int task_index_
bool task_complete_
std::chrono::steady_clock::time_point start_time_
Constructor & Destructor Documentation
TaskManager() [1/2]
template<typename TFunc > yaze::app::core::TaskManager< TFunc >::TaskManager () default
~TaskManager()
template<typename TFunc > yaze::app::core::TaskManager< TFunc >::~TaskManager () default
TaskManager() [2/2]
template<typename TFunc > yaze::app::core::TaskManager< TFunc >::TaskManager (int totalTasks, int timeoutSeconds) inline
Member Function Documentation
ExecuteTasks()
template<typename TFunc > void yaze::app::core::TaskManager< TFunc >::ExecuteTasks (const TFunc & taskFunc) inline
References yaze::app::core::TaskManager< TFunc >::ShouldFinishTask(), yaze::app::core::TaskManager< TFunc >::StartTimer(), yaze::app::core::TaskManager< TFunc >::task_complete_, yaze::app::core::TaskManager< TFunc >::task_index_, and yaze::app::core::TaskManager< TFunc >::total_tasks_.
IsTaskComplete()
template<typename TFunc > bool yaze::app::core::TaskManager< TFunc >::IsTaskComplete () const inline
References yaze::app::core::TaskManager< TFunc >::task_complete_.
SetTimeout()
template<typename TFunc > void yaze::app::core::TaskManager< TFunc >::SetTimeout (int timeout) inline
References yaze::app::core::TaskManager< TFunc >::timeout_seconds_.
ShouldFinishTask()
template<typename TFunc > bool yaze::app::core::TaskManager< TFunc >::ShouldFinishTask () inline private
References yaze::app::core::TaskManager< TFunc >::start_time_, and yaze::app::core::TaskManager< TFunc >::timeout_seconds_.
Referenced by yaze::app::core::TaskManager< TFunc >::ExecuteTasks().
StartTimer()
template<typename TFunc > void yaze::app::core::TaskManager< TFunc >::StartTimer () inline private
References yaze::app::core::TaskManager< TFunc >::start_time_.
Referenced by yaze::app::core::TaskManager< TFunc >::ExecuteTasks().
Member Data Documentation
start_time_
template<typename TFunc > std::chrono::steady_clock::time_point yaze::app::core::TaskManager< TFunc >::start_time_ private
Referenced by yaze::app::core::TaskManager< TFunc >::ShouldFinishTask(), and yaze::app::core::TaskManager< TFunc >::StartTimer().
task_complete_
template<typename TFunc > bool yaze::app::core::TaskManager< TFunc >::task_complete_ private
Referenced by yaze::app::core::TaskManager< TFunc >::ExecuteTasks(), and yaze::app::core::TaskManager< TFunc >::IsTaskComplete().
task_index_
template<typename TFunc > int yaze::app::core::TaskManager< TFunc >::task_index_ private
Referenced by yaze::app::core::TaskManager< TFunc >::ExecuteTasks().
timeout_seconds_
template<typename TFunc > int yaze::app::core::TaskManager< TFunc >::timeout_seconds_ private
Referenced by yaze::app::core::TaskManager< TFunc >::SetTimeout(), and yaze::app::core::TaskManager< TFunc >::ShouldFinishTask().
total_tasks_
template<typename TFunc > int yaze::app::core::TaskManager< TFunc >::total_tasks_ private
Referenced by yaze::app::core::TaskManager< TFunc >::ExecuteTasks().
The documentation for this class was generated from the following file:
src/app/core/common.h