yaze: yaze::test::TestRomManager Class Reference
yaze::test::TestRomManager Class Reference
Utility class for handling test ROM files.
#include <test_utils.h>
Static Public Member Functions
static bool IsRomTestingEnabled ()
Check if ROM testing is enabled and ROM file exists.
static std::string GetTestRomPath ()
Get the path to the test ROM file.
static std::vector< uint8_t > LoadTestRom ()
Load the test ROM file into memory.
static std::vector< uint8_t > CreateMinimalTestRom (size_t size=1024 *1024)
Create a minimal test ROM for unit testing.
static void SkipIfRomTestingDisabled (const std::string &test_name)
Skip test if ROM testing is not enabled.
Detailed Description
Utility class for handling test ROM files.
Definition at line 19 of file test_utils.h.
Member Function Documentation
IsRomTestingEnabled()
static bool yaze::test::TestRomManager::IsRomTestingEnabled () inline static
Check if ROM testing is enabled and ROM file exists.
Returns
True if ROM tests can be run
Definition at line 25 of file test_utils.h.
References GetTestRomPath().
Referenced by LoadTestRom(), and SkipIfRomTestingDisabled().
GetTestRomPath()
static std::string yaze::test::TestRomManager::GetTestRomPath () inline static
Get the path to the test ROM file.
Returns
Path to the test ROM
Definition at line 37 of file test_utils.h.
Referenced by IsRomTestingEnabled(), LoadTestRom(), and SkipIfRomTestingDisabled().
LoadTestRom()
static std::vector< uint8_t > yaze::test::TestRomManager::LoadTestRom () inline static
Load the test ROM file into memory.
Returns
Vector containing ROM data, or empty if failed
Definition at line 49 of file test_utils.h.
References GetTestRomPath(), and IsRomTestingEnabled().
Referenced by yaze::test::RomDependentTest::SetUp().
CreateMinimalTestRom()
static std::vector< uint8_t > yaze::test::TestRomManager::CreateMinimalTestRom (size_t size = 1024 * 1024) inline static
Create a minimal test ROM for unit testing.
Parameters
size Size of the ROM in bytes
Returns
Vector containing minimal ROM data
Definition at line 83 of file test_utils.h.
SkipIfRomTestingDisabled()
static void yaze::test::TestRomManager::SkipIfRomTestingDisabled (const std::string & test_name) inline static
Skip test if ROM testing is not enabled.
Parameters
test_name Name of the test for logging
Definition at line 121 of file test_utils.h.
References GetTestRomPath(), and IsRomTestingEnabled().
Referenced by yaze::test::RomDependentTest::SetUp().
The documentation for this class was generated from the following file:
test/test_utils.h