yaze: yaze::app::emu::SNES Class Reference
yaze::app::emu::SNES Class Reference
#include <snes.h>
Public Member Functions
SNES ()=default
~SNES ()=default
void Init (std::vector< uint8_t > &rom_data)
void Reset (bool hard=false)
void RunFrame ()
void CatchUpApu ()
void HandleInput ()
void RunCycle ()
void RunCycles (int cycles)
void SyncCycles (bool start, int sync_cycles)
uint8_t ReadBBus (uint8_t adr)
uint8_t ReadReg (uint16_t adr)
uint8_t Rread (uint32_t adr)
uint8_t Read (uint32_t adr)
void WriteBBus (uint8_t adr, uint8_t val)
void WriteReg (uint16_t adr, uint8_t val)
void Write (uint32_t adr, uint8_t val)
int GetAccessTime (uint32_t adr)
uint8_t CpuRead (uint32_t adr)
void CpuWrite (uint32_t adr, uint8_t val)
void CpuIdle (bool waiting)
void SetSamples (int16_t *sample_data, int wanted_samples)
void SetPixels (uint8_t *pixel_data)
void SetButtonState (int player, int button, bool pressed)
bool running () const
auto cpu () -> Cpu &
auto ppu () -> video::Ppu &
auto apu () -> audio::Apu &
auto Memory () -> memory::MemoryImpl &
auto get_ram () -> uint8_t *
auto mutable_cycles () -> uint64_t &
void InitAccessTime (bool recalc)
Public Attributes
std::vector< uint8_t > access_time
Private Attributes
ClockImpl clock_
Debugger debugger
memory::MemoryImpl memory_
memory::CpuCallbacks cpu_callbacks_
Cpu cpu_ {memory_, clock_, cpu_callbacks_}
video::Ppu ppu_ {memory_, clock_}
audio::Apu apu_ {memory_}
std::vector< uint8_t > rom_data
bool running_ = false
uint8_t ram [0x20000]
uint32_t ram_adr_
uint32_t frames_ = 0
uint64_t cycles_ = 0
uint64_t sync_cycle_ = 0
double apu_catchup_cycles_
uint32_t next_horiz_event
bool h_irq_enabled_ = false
bool v_irq_enabled_ = false
bool nmi_enabled_ = false
uint16_t h_timer_ = 0
uint16_t v_timer_ = 0
bool in_nmi_ = false
bool irq_condition_ = false
bool in_irq_ = false
bool in_vblank_
uint8_t multiply_a_
uint16_t multiply_result_
uint16_t divide_a_
uint16_t divide_result_
Input input1
Input input2
uint16_t port_auto_read_ [4]
bool auto_joy_read_ = false
uint16_t auto_joy_timer_ = 0
bool ppu_latch_
bool fast_mem_ = false
Detailed Description
Definition at line 31 of file snes.h.
Constructor & Destructor Documentation
SNES()
yaze::app::emu::SNES::SNES () default
~SNES()
yaze::app::emu::SNES::~SNES () default
Member Function Documentation
Init()
void yaze::app::emu::SNES::Init (std::vector< uint8_t > & rom_data)
Definition at line 37 of file snes.cc.
References apu_, yaze::app::emu::audio::Apu::Init(), yaze::app::emu::video::Ppu::Init(), yaze::app::emu::memory::MemoryImpl::Initialize(), memory_, ppu_, Reset(), rom_data, and running_.
Referenced by main(), yaze::app::emu::Emulator::RenderNavBar(), and yaze::app::emu::Emulator::Run().
Reset()
void yaze::app::emu::SNES::Reset (bool hard = false)
Definition at line 49 of file snes.cc.
References apu_, apu_catchup_cycles_, auto_joy_read_, auto_joy_timer_, cpu_, cycles_, divide_a_, divide_result_, fast_mem_, frames_, h_irq_enabled_, h_timer_, in_irq_, in_nmi_, in_vblank_, InitAccessTime(), input1, input2, irq_condition_, yaze::app::emu::Input::latch_line_, yaze::app::emu::Input::latched_state_, memory_, multiply_a_, multiply_result_, next_horiz_event, nmi_enabled_, port_auto_read_, ppu_, ppu_latch_, ram, ram_adr_, yaze::app::emu::audio::Apu::Reset(), yaze::app::emu::Cpu::Reset(), yaze::app::emu::memory::dma::Reset(), yaze::app::emu::video::Ppu::Reset(), yaze::app::emu::memory::MemoryImpl::set_h_pos(), yaze::app::emu::memory::MemoryImpl::set_open_bus(), yaze::app::emu::memory::MemoryImpl::set_v_pos(), sync_cycle_, v_irq_enabled_, and v_timer_.
Referenced by Init(), and yaze::app::emu::Emulator::RenderNavBar().
RunFrame()
void yaze::app::emu::SNES::RunFrame ()
Definition at line 89 of file snes.cc.
References cpu_, frames_, in_vblank_, and yaze::app::emu::Cpu::RunOpcode().
Referenced by main(), and yaze::app::emu::Emulator::Run().
CatchUpApu()
void yaze::app::emu::SNES::CatchUpApu ()
Definition at line 99 of file snes.cc.
References apu_, cycles_, and yaze::app::emu::audio::Apu::RunCycles().
Referenced by ReadBBus(), RunCycle(), and WriteBBus().
HandleInput()
void yaze::app::emu::SNES::HandleInput ()
Definition at line 101 of file snes.cc.
References input1, input2, and port_auto_read_.
Referenced by RunCycle().
RunCycle()
void yaze::app::emu::SNES::RunCycle ()
Todo
this starts a little after start of vblank
Definition at line 118 of file snes.cc.
References apu_, auto_joy_read_, auto_joy_timer_, CatchUpApu(), yaze::app::emu::video::Ppu::CheckOverscan(), cpu_, cycles_, yaze::app::emu::audio::Apu::dsp(), yaze::app::emu::video::Ppu::even_frame, yaze::app::emu::video::Ppu::frame_interlace, frames_, h_irq_enabled_, yaze::app::emu::memory::MemoryImpl::h_pos(), h_timer_, yaze::app::emu::video::Ppu::HandleFrameStart(), HandleInput(), yaze::app::emu::video::Ppu::HandleVblank(), in_irq_, in_nmi_, in_vblank_, yaze::app::emu::memory::MemoryImpl::init_hdma_request(), irq_condition_, memory_, next_horiz_event, yaze::app::emu::Cpu::Nmi(), nmi_enabled_, yaze::app::emu::memory::MemoryImpl::pal_timing(), ppu_, yaze::app::emu::memory::MemoryImpl::run_hdma_request(), yaze::app::emu::video::Ppu::RunLine(), yaze::app::emu::memory::MemoryImpl::set_h_pos(), yaze::app::emu::memory::MemoryImpl::set_v_pos(), yaze::app::emu::Cpu::SetIrq(), v_irq_enabled_, yaze::app::emu::memory::MemoryImpl::v_pos(), and v_timer_.
Referenced by RunCycles().
RunCycles()
void yaze::app::emu::SNES::RunCycles (int cycles)
Definition at line 233 of file snes.cc.
References yaze::app::emu::memory::MemoryImpl::h_pos(), memory_, and RunCycle().
Referenced by CpuIdle(), CpuRead(), CpuWrite(), yaze::app::emu::memory::dma::DoHdma(), yaze::app::emu::memory::dma::InitHdma(), SyncCycles(), and yaze::app::emu::memory::dma::WaitCycle().
SyncCycles()
void yaze::app::emu::SNES::SyncCycles (bool start, int sync_cycles)
Definition at line 243 of file snes.cc.
References cycles_, RunCycles(), and sync_cycle_.
Referenced by yaze::app::emu::memory::dma::DoDma(), yaze::app::emu::memory::dma::DoHdma(), and yaze::app::emu::memory::dma::InitHdma().
ReadBBus()
uint8_t yaze::app::emu::SNES::ReadBBus (uint8_t adr)
Definition at line 254 of file snes.cc.
References apu_, CatchUpApu(), memory_, yaze::app::emu::memory::MemoryImpl::open_bus(), yaze::app::emu::audio::Apu::out_ports_, ppu_, ppu_latch_, ram, ram_adr_, and yaze::app::emu::video::Ppu::Read().
Referenced by Rread(), and yaze::app::emu::memory::dma::TransferByte().
ReadReg()
uint8_t yaze::app::emu::SNES::ReadReg (uint16_t adr)
Definition at line 270 of file snes.cc.
References auto_joy_timer_, cpu_, divide_result_, yaze::app::emu::memory::MemoryImpl::h_pos(), in_irq_, in_nmi_, in_vblank_, memory_, multiply_result_, yaze::app::emu::memory::MemoryImpl::open_bus(), port_auto_read_, ppu_latch_, and yaze::app::emu::Cpu::SetIrq().
Referenced by Rread().
Rread()
uint8_t yaze::app::emu::SNES::Rread (uint32_t adr)
Definition at line 323 of file snes.cc.
References yaze::app::emu::memory::MemoryImpl::cart_read(), input1, input2, memory_, yaze::app::emu::memory::MemoryImpl::open_bus(), ram, yaze::app::emu::memory::dma::Read(), ReadBBus(), and ReadReg().
Referenced by Read().
Read()
uint8_t yaze::app::emu::SNES::Read (uint32_t adr)
Definition at line 353 of file snes.cc.
References memory_, Rread(), and yaze::app::emu::memory::MemoryImpl::set_open_bus().
Referenced by CpuRead(), yaze::app::emu::memory::dma::DoHdma(), yaze::app::emu::memory::dma::InitHdma(), and yaze::app::emu::memory::dma::TransferByte().
WriteBBus()
void yaze::app::emu::SNES::WriteBBus (uint8_t adr, uint8_t val)
Definition at line 359 of file snes.cc.
References apu_, CatchUpApu(), yaze::app::emu::audio::Apu::in_ports_, ppu_, ram, ram_adr_, and yaze::app::emu::video::Ppu::Write().
Referenced by yaze::app::emu::memory::dma::TransferByte(), and Write().
WriteReg()
void yaze::app::emu::SNES::WriteReg (uint16_t adr, uint8_t val)
Definition at line 390 of file snes.cc.
References auto_joy_read_, auto_joy_timer_, cpu_, divide_a_, divide_result_, fast_mem_, h_irq_enabled_, h_timer_, in_irq_, in_nmi_, yaze::app::emu::video::Ppu::LatchHV(), memory_, multiply_a_, multiply_result_, yaze::app::emu::Cpu::Nmi(), nmi_enabled_, ppu_, ppu_latch_, yaze::app::emu::Cpu::set_int_delay(), yaze::app::emu::Cpu::SetIrq(), yaze::app::emu::memory::dma::StartDma(), v_irq_enabled_, and v_timer_.
Referenced by Write().
Write()
void yaze::app::emu::SNES::Write (uint32_t adr, uint8_t val)
Definition at line 477 of file snes.cc.
References yaze::app::emu::memory::MemoryImpl::cart_write(), input1, input2, memory_, ram, yaze::app::emu::memory::MemoryImpl::set_open_bus(), yaze::app::emu::memory::dma::Write(), WriteBBus(), and WriteReg().
Referenced by CpuWrite(), and yaze::app::emu::memory::dma::TransferByte().
GetAccessTime()
int yaze::app::emu::SNES::GetAccessTime (uint32_t adr)
Definition at line 507 of file snes.cc.
References fast_mem_.
Referenced by InitAccessTime().
CpuRead()
uint8_t yaze::app::emu::SNES::CpuRead (uint32_t adr)
Definition at line 521 of file snes.cc.
References access_time, cpu_, yaze::app::emu::memory::dma::HandleDma(), memory_, Read(), RunCycles(), and yaze::app::emu::Cpu::set_int_delay().
CpuWrite()
void yaze::app::emu::SNES::CpuWrite (uint32_t adr, uint8_t val)
Definition at line 532 of file snes.cc.
References access_time, cpu_, yaze::app::emu::memory::dma::HandleDma(), memory_, RunCycles(), yaze::app::emu::Cpu::set_int_delay(), and Write().
CpuIdle()
void yaze::app::emu::SNES::CpuIdle (bool waiting)
Definition at line 540 of file snes.cc.
References cpu_, yaze::app::emu::memory::dma::HandleDma(), memory_, RunCycles(), and yaze::app::emu::Cpu::set_int_delay().
SetSamples()
void yaze::app::emu::SNES::SetSamples (int16_t * sample_data, int wanted_samples)
Definition at line 546 of file snes.cc.
References apu_, yaze::app::emu::audio::Apu::dsp(), memory_, and yaze::app::emu::memory::MemoryImpl::pal_timing().
Referenced by main(), and yaze::app::emu::Emulator::Run().
SetPixels()
void yaze::app::emu::SNES::SetPixels (uint8_t * pixel_data)
Definition at line 550 of file snes.cc.
References ppu_, and yaze::app::emu::video::Ppu::PutPixels().
Referenced by main(), and yaze::app::emu::Emulator::Run().
SetButtonState()
void yaze::app::emu::SNES::SetButtonState (int player, int button, bool pressed)
Definition at line 552 of file snes.cc.
References yaze::app::emu::Input::current_state_, input1, and input2.
running()
bool yaze::app::emu::SNES::running () const inline
Definition at line 69 of file snes.h.
References running_.
Referenced by yaze::app::emu::Emulator::RenderSnesPpu(), and yaze::app::emu::Emulator::Run().
cpu()
auto yaze::app::emu::SNES::cpu () -> Cpu& inline
Definition at line 70 of file snes.h.
References cpu_.
Referenced by yaze::app::emu::memory::dma::DoDma(), yaze::app::emu::memory::dma::DoHdma(), yaze::app::emu::Emulator::Emulator(), yaze::app::emu::memory::dma::InitHdma(), yaze::app::emu::Emulator::RenderBreakpointList(), and yaze::app::emu::Emulator::RenderNavBar().
ppu()
auto yaze::app::emu::SNES::ppu () -> video::Ppu& inline
Definition at line 71 of file snes.h.
References ppu_.
apu()
auto yaze::app::emu::SNES::apu () -> audio::Apu& inline
Definition at line 72 of file snes.h.
References apu_.
Referenced by yaze::app::emu::Emulator::Emulator(), yaze::app::emu::Emulator::RenderBreakpointList(), and yaze::app::emu::Emulator::RenderMemoryViewer().
Memory()
auto yaze::app::emu::SNES::Memory () -> memory::MemoryImpl& inline
Definition at line 73 of file snes.h.
References memory_.
Referenced by yaze::app::emu::Emulator::Emulator(), main(), yaze::app::emu::Emulator::RenderMemoryViewer(), and yaze::app::emu::Emulator::Run().
get_ram()
auto yaze::app::emu::SNES::get_ram () -> uint8_t* inline
Definition at line 74 of file snes.h.
References ram.
Referenced by yaze::app::emu::Emulator::RenderMemoryViewer().
mutable_cycles()
auto yaze::app::emu::SNES::mutable_cycles () -> uint64_t& inline
Definition at line 75 of file snes.h.
References cycles_.
Referenced by yaze::app::emu::Emulator::Emulator().
InitAccessTime()
void yaze::app::emu::SNES::InitAccessTime (bool recalc)
Definition at line 569 of file snes.cc.
References access_time, and GetAccessTime().
Referenced by Reset().
Member Data Documentation
access_time
std::vector<uint8_t> yaze::app::emu::SNES::access_time
Definition at line 78 of file snes.h.
Referenced by CpuRead(), CpuWrite(), and InitAccessTime().
clock_
ClockImpl yaze::app::emu::SNES::clock_ private
Definition at line 82 of file snes.h.
debugger
Debugger yaze::app::emu::SNES::debugger private
Definition at line 83 of file snes.h.
memory_
memory::MemoryImpl yaze::app::emu::SNES::memory_ private
Definition at line 84 of file snes.h.
Referenced by CpuIdle(), CpuRead(), CpuWrite(), Init(), Memory(), Read(), ReadBBus(), ReadReg(), Reset(), Rread(), RunCycle(), RunCycles(), SetSamples(), Write(), and WriteReg().
cpu_callbacks_
memory::CpuCallbacks yaze::app::emu::SNES::cpu_callbacks_ private
Initial value:
= {
      [&](uint32_t adr) { return CpuRead(adr); },
      [&](uint32_t adr, uint8_t val) { CpuWrite(adr, val); },
      [&](bool waiting) { CpuIdle(waiting); },
  }
Definition at line 86 of file snes.h.
cpu_
Cpu yaze::app::emu::SNES::cpu_ {memory_, clock_, cpu_callbacks_} private
Definition at line 91 of file snes.h.
Referenced by cpu(), CpuIdle(), CpuRead(), CpuWrite(), ReadReg(), Reset(), RunCycle(), RunFrame(), and WriteReg().
ppu_
video::Ppu yaze::app::emu::SNES::ppu_ {memory_, clock_} private
Definition at line 92 of file snes.h.
Referenced by Init(), ppu(), ReadBBus(), Reset(), RunCycle(), SetPixels(), WriteBBus(), and WriteReg().
apu_
audio::Apu yaze::app::emu::SNES::apu_ {memory_} private
Definition at line 93 of file snes.h.
Referenced by apu(), CatchUpApu(), Init(), ReadBBus(), Reset(), RunCycle(), SetSamples(), and WriteBBus().
rom_data
std::vector<uint8_t> yaze::app::emu::SNES::rom_data private
Definition at line 96 of file snes.h.
Referenced by Init().
running_
bool yaze::app::emu::SNES::running_ = false private
Definition at line 99 of file snes.h.
Referenced by Init(), and running().
ram
uint8_t yaze::app::emu::SNES::ram[0x20000] private
Definition at line 102 of file snes.h.
Referenced by get_ram(), ReadBBus(), Reset(), Rread(), Write(), and WriteBBus().
ram_adr_
uint32_t yaze::app::emu::SNES::ram_adr_ private
Definition at line 103 of file snes.h.
Referenced by ReadBBus(), Reset(), and WriteBBus().
frames_
uint32_t yaze::app::emu::SNES::frames_ = 0 private
Definition at line 106 of file snes.h.
Referenced by Reset(), RunCycle(), and RunFrame().
cycles_
uint64_t yaze::app::emu::SNES::cycles_ = 0 private
Definition at line 107 of file snes.h.
Referenced by CatchUpApu(), mutable_cycles(), Reset(), RunCycle(), and SyncCycles().
sync_cycle_
uint64_t yaze::app::emu::SNES::sync_cycle_ = 0 private
Definition at line 108 of file snes.h.
Referenced by Reset(), and SyncCycles().
apu_catchup_cycles_
double yaze::app::emu::SNES::apu_catchup_cycles_ private
Definition at line 109 of file snes.h.
Referenced by Reset().
next_horiz_event
uint32_t yaze::app::emu::SNES::next_horiz_event private
Definition at line 110 of file snes.h.
Referenced by Reset(), and RunCycle().
h_irq_enabled_
bool yaze::app::emu::SNES::h_irq_enabled_ = false private
Definition at line 113 of file snes.h.
Referenced by Reset(), RunCycle(), and WriteReg().
v_irq_enabled_
bool yaze::app::emu::SNES::v_irq_enabled_ = false private
Definition at line 114 of file snes.h.
Referenced by Reset(), RunCycle(), and WriteReg().
nmi_enabled_
bool yaze::app::emu::SNES::nmi_enabled_ = false private
Definition at line 115 of file snes.h.
Referenced by Reset(), RunCycle(), and WriteReg().
h_timer_
uint16_t yaze::app::emu::SNES::h_timer_ = 0 private
Definition at line 116 of file snes.h.
Referenced by Reset(), RunCycle(), and WriteReg().
v_timer_
uint16_t yaze::app::emu::SNES::v_timer_ = 0 private
Definition at line 117 of file snes.h.
Referenced by Reset(), RunCycle(), and WriteReg().
in_nmi_
bool yaze::app::emu::SNES::in_nmi_ = false private
Definition at line 118 of file snes.h.
Referenced by ReadReg(), Reset(), RunCycle(), and WriteReg().
irq_condition_
bool yaze::app::emu::SNES::irq_condition_ = false private
Definition at line 119 of file snes.h.
Referenced by Reset(), and RunCycle().
in_irq_
bool yaze::app::emu::SNES::in_irq_ = false private
Definition at line 120 of file snes.h.
Referenced by ReadReg(), Reset(), RunCycle(), and WriteReg().
in_vblank_
bool yaze::app::emu::SNES::in_vblank_ private
Definition at line 121 of file snes.h.
Referenced by ReadReg(), Reset(), RunCycle(), and RunFrame().
multiply_a_
uint8_t yaze::app::emu::SNES::multiply_a_ private
Definition at line 124 of file snes.h.
Referenced by Reset(), and WriteReg().
multiply_result_
uint16_t yaze::app::emu::SNES::multiply_result_ private
Definition at line 125 of file snes.h.
Referenced by ReadReg(), Reset(), and WriteReg().
divide_a_
uint16_t yaze::app::emu::SNES::divide_a_ private
Definition at line 126 of file snes.h.
Referenced by Reset(), and WriteReg().
divide_result_
uint16_t yaze::app::emu::SNES::divide_result_ private
Definition at line 127 of file snes.h.
Referenced by ReadReg(), Reset(), and WriteReg().
input1
Input yaze::app::emu::SNES::input1 private
Definition at line 130 of file snes.h.
Referenced by HandleInput(), Reset(), Rread(), SetButtonState(), and Write().
input2
Input yaze::app::emu::SNES::input2 private
Definition at line 131 of file snes.h.
Referenced by HandleInput(), Reset(), Rread(), SetButtonState(), and Write().
port_auto_read_
uint16_t yaze::app::emu::SNES::port_auto_read_[4] private
Definition at line 132 of file snes.h.
Referenced by HandleInput(), ReadReg(), and Reset().
auto_joy_read_
bool yaze::app::emu::SNES::auto_joy_read_ = false private
Definition at line 133 of file snes.h.
Referenced by Reset(), RunCycle(), and WriteReg().
auto_joy_timer_
uint16_t yaze::app::emu::SNES::auto_joy_timer_ = 0 private
Definition at line 134 of file snes.h.
Referenced by ReadReg(), Reset(), RunCycle(), and WriteReg().
ppu_latch_
bool yaze::app::emu::SNES::ppu_latch_ private
Definition at line 135 of file snes.h.
Referenced by ReadBBus(), ReadReg(), Reset(), and WriteReg().
fast_mem_
bool yaze::app::emu::SNES::fast_mem_ = false private
Definition at line 137 of file snes.h.
Referenced by GetAccessTime(), Reset(), and WriteReg().
The documentation for this class was generated from the following files:
src/app/emu/snes.h
src/app/emu/snes.cc