yaze: yaze::app::emu::memory::Memory Class Reference
yaze::app::emu::memory::Memory Class Reference abstract
Memory interface.
#include <memory.h>
Public Member Functions
virtual ~Memory ()=default
virtual uint8_t ReadByte (uint32_t address) const =0
virtual uint16_t ReadWord (uint32_t address) const =0
virtual uint32_t ReadWordLong (uint32_t address) const =0
virtual std::vector< uint8_t > ReadByteVector (uint32_t address, uint16_t length) const =0
virtual void WriteByte (uint32_t address, uint8_t value)=0
virtual void WriteWord (uint32_t address, uint16_t value)=0
virtual void WriteLong (uint32_t address, uint32_t value)=0
virtual void PushByte (uint8_t value)=0
virtual uint8_t PopByte ()=0
virtual void PushWord (uint16_t value)=0
virtual uint16_t PopWord ()=0
virtual void PushLong (uint32_t value)=0
virtual uint32_t PopLong ()=0
virtual uint16_t SP () const =0
virtual void SetSP (uint16_t value)=0
virtual void ClearMemory ()=0
virtual uint8_t operator[] (int i) const =0
virtual uint8_t at (int i) const =0
Detailed Description
Memory interface.
Constructor & Destructor Documentation
~Memory()
virtual yaze::app::emu::memory::Memory::~Memory () virtual default
Member Function Documentation
ReadByte()
virtual uint8_t yaze::app::emu::memory::Memory::ReadByte (uint32_t address) const pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::AND(), yaze::app::emu::Cpu::ASL(), yaze::app::emu::Cpu::BIT(), yaze::app::emu::Cpu::BlockMove(), yaze::app::emu::Cpu::CMP(), yaze::app::emu::Cpu::CPX(), yaze::app::emu::Cpu::CPY(), yaze::app::emu::Cpu::DEC(), yaze::app::emu::Cpu::EOR(), yaze::app::emu::Cpu::FetchByte(), yaze::app::emu::Cpu::FetchByteDirectPage(), yaze::app::emu::Cpu::Immediate(), yaze::app::emu::Cpu::INC(), yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::LDA(), yaze::app::emu::Cpu::LDX(), yaze::app::emu::Cpu::LDY(), yaze::app::emu::Cpu::LSR(), yaze::app::emu::Cpu::MVN(), yaze::app::emu::Cpu::MVP(), yaze::app::emu::Cpu::ORA(), yaze::app::emu::Cpu::ReadByte(), yaze::app::emu::Cpu::ReadByteOrWord(), yaze::app::emu::video::Ppu::RenderBackground(), yaze::app::emu::Cpu::ROL(), yaze::app::emu::Cpu::ROR(), yaze::app::emu::Cpu::SBC(), yaze_test::emu_test::TEST_F(), yaze::app::emu::Cpu::TRB(), yaze::app::emu::Cpu::TSB(), yaze::app::emu::video::Ppu::UpdateModeSettings(), and yaze::app::emu::video::Ppu::UpdateTileData().
ReadWord()
virtual uint16_t yaze::app::emu::memory::Memory::ReadWord (uint32_t address) const pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::AbsoluteIndexedIndirect(), yaze::app::emu::Cpu::AbsoluteIndexedX(), yaze::app::emu::Cpu::AbsoluteIndexedY(), yaze::app::emu::Cpu::AbsoluteIndirect(), yaze::app::emu::Cpu::AND(), yaze::app::emu::Cpu::BRK(), yaze::app::emu::Cpu::CMP(), yaze::app::emu::Cpu::COP(), yaze::app::emu::Cpu::CPX(), yaze::app::emu::Cpu::CPY(), yaze::app::emu::Cpu::DEC(), yaze::app::emu::Cpu::DirectPageIndexedIndirectX(), yaze::app::emu::Cpu::DirectPageIndirect(), yaze::app::emu::Cpu::DirectPageIndirectIndexedY(), yaze::app::emu::Cpu::EOR(), yaze::app::emu::Cpu::FetchWord(), yaze::app::emu::Cpu::Immediate(), yaze::app::emu::Cpu::INC(), yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::LDA(), yaze::app::emu::Cpu::LDX(), yaze::app::emu::Cpu::LDY(), yaze::app::emu::Cpu::ORA(), yaze::app::emu::Cpu::PEI(), yaze::app::emu::Cpu::ReadByteOrWord(), yaze::app::emu::Cpu::ReadWord(), yaze::app::emu::Cpu::SBC(), yaze::app::emu::Cpu::StackRelativeIndirectIndexedY(), and yaze::app::emu::video::Ppu::UpdateTileData().
ReadWordLong()
virtual uint32_t yaze::app::emu::memory::Memory::ReadWordLong (uint32_t address) const pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::AbsoluteIndirectLong(), yaze::app::emu::Cpu::ANDAbsoluteLong(), yaze::app::emu::Cpu::DirectPageIndirectLong(), yaze::app::emu::Cpu::DirectPageIndirectLongIndexedY(), yaze::app::emu::Cpu::FetchLong(), yaze::app::emu::memory::MockMemory::Init(), and yaze::app::emu::Cpu::ReadWordLong().
ReadByteVector()
virtual std::vector< uint8_t > yaze::app::emu::memory::Memory::ReadByteVector (uint32_t address, uint16_t length) const pure virtual
Implemented in yaze::app::emu::memory::MemoryImpl, and yaze::app::emu::Cpu.
Referenced by yaze::app::emu::memory::MockMemory::Init(), and yaze::app::emu::Cpu::ReadByteVector().
WriteByte()
virtual void yaze::app::emu::memory::Memory::WriteByte (uint32_t address, uint8_t value) pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::ASL(), yaze::app::emu::Cpu::BlockMove(), yaze::app::emu::Cpu::DEC(), yaze::app::emu::Cpu::INC(), yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::LSR(), yaze::app::emu::Cpu::MVN(), yaze::app::emu::Cpu::MVP(), yaze::app::emu::Cpu::ROL(), yaze::app::emu::Cpu::ROR(), yaze::app::emu::Cpu::STA(), yaze::app::emu::Cpu::STX(), yaze::app::emu::Cpu::STY(), yaze::app::emu::Cpu::STZ(), yaze::app::emu::Cpu::TRB(), yaze::app::emu::Cpu::TSB(), and yaze::app::emu::Cpu::WriteByte().
WriteWord()
virtual void yaze::app::emu::memory::Memory::WriteWord (uint32_t address, uint16_t value) pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::DEC(), yaze::app::emu::Cpu::INC(), yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::STA(), yaze::app::emu::Cpu::STX(), yaze::app::emu::Cpu::STY(), yaze::app::emu::Cpu::STZ(), and yaze::app::emu::Cpu::WriteWord().
WriteLong()
virtual void yaze::app::emu::memory::Memory::WriteLong (uint32_t address, uint32_t value) pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::WriteLong().
PushByte()
virtual void yaze::app::emu::memory::Memory::PushByte (uint8_t value) pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::BRK(), yaze::app::emu::Cpu::COP(), yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::PHA(), yaze::app::emu::Cpu::PHB(), yaze::app::emu::Cpu::PHK(), yaze::app::emu::Cpu::PHP(), yaze::app::emu::Cpu::PHX(), yaze::app::emu::Cpu::PHY(), and yaze::app::emu::Cpu::PushByte().
PopByte()
virtual uint8_t yaze::app::emu::memory::Memory::PopByte () pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::PLA(), yaze::app::emu::Cpu::PLB(), yaze::app::emu::Cpu::PLP(), yaze::app::emu::Cpu::PLX(), yaze::app::emu::Cpu::PLY(), yaze::app::emu::Cpu::PopByte(), yaze::app::emu::Cpu::RTI(), and yaze::app::emu::Cpu::RTL().
PushWord()
virtual void yaze::app::emu::memory::Memory::PushWord (uint16_t value) pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::BRK(), yaze::app::emu::Cpu::COP(), yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::JSR(), yaze::app::emu::Cpu::PEA(), yaze::app::emu::Cpu::PEI(), yaze::app::emu::Cpu::PER(), yaze::app::emu::Cpu::PHA(), yaze::app::emu::Cpu::PHD(), yaze::app::emu::Cpu::PHX(), yaze::app::emu::Cpu::PHY(), and yaze::app::emu::Cpu::PushWord().
PopWord()
virtual uint16_t yaze::app::emu::memory::Memory::PopWord () pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::PLA(), yaze::app::emu::Cpu::PLD(), yaze::app::emu::Cpu::PLX(), yaze::app::emu::Cpu::PLY(), yaze::app::emu::Cpu::PopWord(), yaze::app::emu::Cpu::RTI(), yaze::app::emu::Cpu::RTL(), and yaze::app::emu::Cpu::RTS().
PushLong()
virtual void yaze::app::emu::memory::Memory::PushLong (uint32_t value) pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::JSL(), and yaze::app::emu::Cpu::PushLong().
PopLong()
virtual uint32_t yaze::app::emu::memory::Memory::PopLong () pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::memory::MockMemory::Init(), and yaze::app::emu::Cpu::PopLong().
SP()
virtual uint16_t yaze::app::emu::memory::Memory::SP () const pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::memory::MockMemory::Init(), and yaze::app::emu::Cpu::SP().
SetSP()
virtual void yaze::app::emu::memory::Memory::SetSP (uint16_t value) pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::memory::MockMemory::Init(), yaze::app::emu::Cpu::SetSP(), yaze::app::emu::Cpu::TCS(), and yaze::app::emu::Cpu::TXS().
ClearMemory()
virtual void yaze::app::emu::memory::Memory::ClearMemory () pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
Referenced by yaze::app::emu::Cpu::ClearMemory(), yaze::app::emu::memory::MockMemory::Init(), and yaze_test::emu_test::CpuTest::SetUp().
operator[]()
virtual uint8_t yaze::app::emu::memory::Memory::operator[] (int i) const pure virtual
Implemented in yaze::app::emu::Cpu, yaze::app::emu::memory::MemoryImpl, and yaze::app::emu::memory::MockMemory.
at()
virtual uint8_t yaze::app::emu::memory::Memory::at (int i) const pure virtual
Implemented in yaze::app::emu::Cpu, and yaze::app::emu::memory::MemoryImpl.
The documentation for this class was generated from the following file:
src/app/emu/memory/memory.h