yaze: yaze::app::core::Renderer Class Reference
yaze::app::core::Renderer Class Reference
The Renderer class represents the renderer for the Yaze application.
#include <renderer.h>
Public Member Functions
absl::Status CreateRenderer (SDL_Window *window)
auto renderer () -> SDL_Renderer *
void RenderBitmap (gfx::Bitmap *bitmap)
Used to render a bitmap to the screen.
void UpdateBitmap (gfx::Bitmap *bitmap, bool use_sdl_update=false)
Used to update a bitmap on the screen.
absl::Status CreateAndRenderBitmap (int width, int height, int depth, const Bytes &data, gfx::Bitmap &bitmap, gfx::SnesPalette &palette)
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
Static Public Member Functions
static Renderer & GetInstance ()
Private Member Functions
Renderer ()=default
Renderer (const Renderer &)=delete
Renderer & operator= (const Renderer &)=delete
Private Attributes
std::unique_ptr< SDL_Renderer, SDL_Deleter > renderer_
Detailed Description
The Renderer class represents the renderer for the Yaze application.
This class is a singleton that provides functionality for creating and rendering bitmaps to the screen. It also includes methods for updating bitmaps on the screen.
The Renderer class uses the ExperimentFlags class to access the application's flags.
Definition at line 28 of file renderer.h.
Constructor & Destructor Documentation
Renderer() [1/2]
yaze::app::core::Renderer::Renderer () private default
Renderer() [2/2]
yaze::app::core::Renderer::Renderer (const Renderer &) private delete
Member Function Documentation
GetInstance()
static Renderer & yaze::app::core::Renderer::GetInstance () inline static
Definition at line 30 of file renderer.h.
Referenced by yaze::app::zelda3::screen::Inventory::BuildTileset(), yaze::app::zelda3::screen::Inventory::Create(), yaze::app::core::Controller::CreateGuiContext(), yaze::app::core::Controller::CreateRenderer(), yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::core::Controller::DoRender(), yaze::app::editor::GraphicsEditor::DrawCgxImport(), yaze::app::gui::Canvas::DrawContextMenu(), yaze::app::editor::MessageEditor::DrawCurrentMessage(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::GraphicsEditor::DrawGfxEditToolset(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::GraphicsEditor::DrawScrImport(), yaze::app::editor::Tile16Editor::DrawTileEditControls(), yaze::app::editor::MessageEditor::Initialize(), yaze::app::Rom::LoadAllGraphicsData(), yaze::app::editor::ScreenEditor::LoadDungeonMapTile16(), yaze::app::Rom::LoadLinkGraphics(), yaze::app::editor::Tile16Editor::LoadTile8(), yaze::app::editor::DungeonEditor::RefreshGraphics(), yaze::app::editor::OverworldEditor::RefreshOverworldMap(), yaze::app::editor::OverworldEditor::RefreshTile16Blockset(), yaze::app::core::Controller::renderer(), yaze::app::emu::Emulator::Run(), yaze::app::editor::Tile16Editor::SetCurrentTile(), yaze::app::editor::Tile16Editor::UpdateBlockset(), yaze::app::editor::GraphicsEditor::UpdateGfxTabView(), yaze::app::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::app::editor::GraphicsEditor::UpdateScadView(), yaze::app::editor::Tile16Editor::UpdateTile16Edit(), and yaze::app::editor::Tile16Editor::UpdateTransferTileCanvas().
CreateRenderer()
absl::Status yaze::app::core::Renderer::CreateRenderer (SDL_Window * window) inline
Definition at line 35 of file renderer.h.
References renderer_.
Referenced by yaze::app::core::Controller::CreateRenderer().
renderer()
auto yaze::app::core::Renderer::renderer () -> SDL_Renderer* inline
Definition at line 47 of file renderer.h.
References renderer_.
Referenced by yaze::app::core::Controller::CreateGuiContext(), and yaze::app::core::Controller::renderer().
RenderBitmap()
void yaze::app::core::Renderer::RenderBitmap (gfx::Bitmap * bitmap) inline
Used to render a bitmap to the screen.
Definition at line 52 of file renderer.h.
References yaze::app::gfx::Bitmap::CreateTexture(), yaze::app::core::ExperimentFlags::flags(), and renderer_.
Referenced by yaze::app::zelda3::screen::Inventory::BuildTileset(), yaze::app::zelda3::screen::Inventory::Create(), CreateAndRenderBitmap(), yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::editor::GraphicsEditor::DrawCgxImport(), yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::app::editor::DungeonEditor::DrawObjectRenderer(), yaze::app::editor::GraphicsEditor::DrawScrImport(), yaze::app::editor::ScreenEditor::LoadDungeonMapTile16(), yaze::app::Rom::LoadLinkGraphics(), yaze::app::editor::Tile16Editor::LoadTile8(), yaze::app::editor::Tile16Editor::SetCurrentTile(), and yaze::app::editor::Tile16Editor::UpdateBlockset().
UpdateBitmap()
void yaze::app::core::Renderer::UpdateBitmap (gfx::Bitmap * bitmap, bool use_sdl_update = false) inline
Used to update a bitmap on the screen.
Definition at line 63 of file renderer.h.
References yaze::app::core::ExperimentFlags::flags(), renderer_, and yaze::app::gfx::Bitmap::UpdateTexture().
Referenced by yaze::app::gui::Canvas::DrawContextMenu(), yaze::app::editor::MessageEditor::DrawCurrentMessage(), yaze::app::editor::GraphicsEditor::DrawGfxEditToolset(), yaze::app::editor::Tile16Editor::DrawTileEditControls(), yaze::app::editor::DungeonEditor::RefreshGraphics(), yaze::app::editor::OverworldEditor::RefreshOverworldMap(), yaze::app::editor::OverworldEditor::RefreshTile16Blockset(), yaze::app::editor::GraphicsEditor::UpdateGfxTabView(), yaze::app::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::app::editor::GraphicsEditor::UpdateScadView(), and yaze::app::editor::Tile16Editor::UpdateTile16Edit().
CreateAndRenderBitmap()
absl::Status yaze::app::core::Renderer::CreateAndRenderBitmap (int width, int height, int depth, const Bytes & data, gfx::Bitmap & bitmap, gfx::SnesPalette & palette) inline
Definition at line 71 of file renderer.h.
References yaze::app::gfx::Bitmap::ApplyPalette(), yaze::app::gfx::Bitmap::Create(), RenderBitmap(), and RETURN_IF_ERROR.
operator=()
Renderer & yaze::app::core::Renderer::operator= (const Renderer &) private delete
Member Data Documentation
renderer_
std::unique_ptr<SDL_Renderer, SDL_Deleter> yaze::app::core::Renderer::renderer_ private
Definition at line 83 of file renderer.h.
Referenced by CreateRenderer(), RenderBitmap(), renderer(), and UpdateBitmap().
The documentation for this class was generated from the following file:
src/app/core/platform/renderer.h