yaze: yaze::zelda3::ObjectParser Class Reference
yaze::zelda3::ObjectParser Class Reference
Direct ROM parser for dungeon objects.
#include <object_parser.h>
Public Member Functions
ObjectParser (Rom *rom)
absl::StatusOr< std::vector< gfx::Tile16 > > ParseObject (int16_t object_id)
Parse object data directly from ROM.
absl::StatusOr< ObjectRoutineInfo > ParseObjectRoutine (int16_t object_id)
Parse object routine data.
absl::StatusOr< ObjectSubtypeInfo > GetObjectSubtype (int16_t object_id)
Get object subtype information.
absl::StatusOr< ObjectSizeInfo > ParseObjectSize (int16_t object_id, uint8_t size_byte)
Parse object size and orientation.
int DetermineSubtype (int16_t object_id) const
Determine object subtype from ID.
Private Member Functions
absl::StatusOr< std::vector< gfx::Tile16 > > ParseSubtype1 (int16_t object_id)
Parse subtype 1 objects (0x00-0xFF)
absl::StatusOr< std::vector< gfx::Tile16 > > ParseSubtype2 (int16_t object_id)
Parse subtype 2 objects (0x100-0x1FF)
absl::StatusOr< std::vector< gfx::Tile16 > > ParseSubtype3 (int16_t object_id)
Parse subtype 3 objects (0x200+)
absl::StatusOr< std::vector< gfx::Tile16 > > ReadTileData (int address, int tile_count)
Read tile data from ROM.
Private Attributes
Rom * rom_
Detailed Description
Direct ROM parser for dungeon objects.
This class replaces the SNES emulation approach with direct ROM parsing, providing better performance and reliability for object rendering.
Definition at line 70 of file object_parser.h.
Constructor & Destructor Documentation
ObjectParser()
yaze::zelda3::ObjectParser::ObjectParser (Rom * rom) inline explicit
Definition at line 72 of file object_parser.h.
Member Function Documentation
ParseObject()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectParser::ParseObject (int16_t object_id)
Parse object data directly from ROM.
Parameters
object_id The object ID to parse
Returns
StatusOr containing the parsed tile data
Definition at line 12 of file object_parser.cc.
References DetermineSubtype(), ParseSubtype1(), ParseSubtype2(), ParseSubtype3(), and rom_.
Referenced by yaze::zelda3::RoomObject::LoadTilesWithParser(), yaze::test::TEST_F(), and yaze::test::TEST_F().
ParseObjectRoutine()
absl::StatusOr< ObjectRoutineInfo > yaze::zelda3::ObjectParser::ParseObjectRoutine (int16_t object_id)
Parse object routine data.
Parameters
object_id The object ID
Returns
StatusOr containing routine information
Definition at line 32 of file object_parser.cc.
References GetObjectSubtype(), yaze::zelda3::ObjectRoutineInfo::is_orientation_dependent, yaze::zelda3::ObjectRoutineInfo::is_repeatable, rom_, yaze::zelda3::ObjectRoutineInfo::routine_ptr, yaze::zelda3::ObjectRoutineInfo::tile_count, and yaze::zelda3::ObjectRoutineInfo::tile_ptr.
GetObjectSubtype()
absl::StatusOr< ObjectSubtypeInfo > yaze::zelda3::ObjectParser::GetObjectSubtype (int16_t object_id)
Get object subtype information.
Parameters
object_id The object ID
Returns
StatusOr containing subtype information
Definition at line 52 of file object_parser.cc.
References DetermineSubtype(), yaze::zelda3::kRoomObjectSubtype1, yaze::zelda3::kRoomObjectSubtype2, yaze::zelda3::kRoomObjectSubtype3, yaze::zelda3::ObjectSubtypeInfo::max_tile_count, yaze::zelda3::ObjectSubtypeInfo::routine_ptr, yaze::zelda3::ObjectSubtypeInfo::subtype, and yaze::zelda3::ObjectSubtypeInfo::subtype_ptr.
Referenced by ParseObjectRoutine(), and yaze::test::TEST_F().
ParseObjectSize()
absl::StatusOr< ObjectSizeInfo > yaze::zelda3::ObjectParser::ParseObjectSize (int16_t object_id, uint8_t size_byte)
Parse object size and orientation.
Parameters
object_id The object ID
size_byte The size byte from object data
Returns
StatusOr containing size and orientation info
Definition at line 86 of file object_parser.cc.
References yaze::zelda3::ObjectSizeInfo::height_tiles, yaze::zelda3::ObjectSizeInfo::is_horizontal, yaze::zelda3::ObjectSizeInfo::is_repeatable, yaze::zelda3::ObjectSizeInfo::repeat_count, and yaze::zelda3::ObjectSizeInfo::width_tiles.
Referenced by yaze::test::TEST_F().
DetermineSubtype()
int yaze::zelda3::ObjectParser::DetermineSubtype (int16_t object_id) const
Determine object subtype from ID.
Definition at line 196 of file object_parser.cc.
Referenced by GetObjectSubtype(), ParseObject(), and yaze::test::TEST_F().
ParseSubtype1()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectParser::ParseSubtype1 (int16_t object_id) private
Parse subtype 1 objects (0x00-0xFF)
Definition at line 113 of file object_parser.cc.
References yaze::Rom::data(), yaze::zelda3::kRoomObjectSubtype1, yaze::zelda3::kRoomObjectTileAddress, ReadTileData(), rom_, and yaze::Rom::size().
Referenced by ParseObject().
ParseSubtype2()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectParser::ParseSubtype2 (int16_t object_id) private
Parse subtype 2 objects (0x100-0x1FF)
Definition at line 131 of file object_parser.cc.
References yaze::Rom::data(), yaze::zelda3::kRoomObjectSubtype2, yaze::zelda3::kRoomObjectTileAddress, ReadTileData(), rom_, and yaze::Rom::size().
Referenced by ParseObject().
ParseSubtype3()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectParser::ParseSubtype3 (int16_t object_id) private
Parse subtype 3 objects (0x200+)
Definition at line 149 of file object_parser.cc.
References yaze::Rom::data(), yaze::zelda3::kRoomObjectSubtype3, yaze::zelda3::kRoomObjectTileAddress, ReadTileData(), rom_, and yaze::Rom::size().
Referenced by ParseObject().
ReadTileData()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectParser::ReadTileData (int address, int tile_count) private
Read tile data from ROM.
Parameters
address The address to read from
tile_count Number of tiles to read
Returns
StatusOr containing tile data
Definition at line 167 of file object_parser.cc.
References yaze::Rom::data(), rom_, yaze::Rom::size(), and yaze::gfx::WordToTileInfo().
Referenced by ParseSubtype1(), ParseSubtype2(), and ParseSubtype3().
Member Data Documentation
rom_
Rom* yaze::zelda3::ObjectParser::rom_ private
Definition at line 139 of file object_parser.h.
Referenced by ParseObject(), ParseObjectRoutine(), ParseSubtype1(), ParseSubtype2(), ParseSubtype3(), and ReadTileData().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/object_parser.h
src/app/zelda3/dungeon/object_parser.cc