yaze: yaze::app::editor::CommandManager Class Reference
yaze::app::editor::CommandManager Class Reference
#include <command_manager.h>
Classes
struct CommandInfo
struct CommandInfoOrPrefix
Public Types
using Command = std::function<void()>
Public Member Functions
void RegisterPrefix (const std::string &group_name, const char prefix, const std::string &name, const std::string &desc)
void RegisterSubcommand (const std::string &group_name, const std::string &shortcut, const char mnemonic, const std::string &name, const std::string &desc, Command command)
void RegisterCommand (const std::string &shortcut, Command command, char mnemonic, const std::string &name, const std::string &desc)
void ExecuteCommand (const std::string &shortcut)
void ShowWhichKey (EditorLayoutParams *editor_layout=nullptr)
void InitializeDefaults ()
void SaveKeybindings (const std::string &filepath)
void LoadKeybindings (const std::string &filepath)
Private Attributes
std::unordered_map< std::string, CommandInfoOrPrefix > commands_
Detailed Description
Definition at line 17 of file command_manager.h.
Member Typedef Documentation
Command
using yaze::app::editor::CommandManager::Command = std::function<void()>
Definition at line 19 of file command_manager.h.
Member Function Documentation
RegisterPrefix()
void yaze::app::editor::CommandManager::RegisterPrefix (const std::string & group_name, const char prefix, const std::string & name, const std::string & desc) inline
Definition at line 42 of file command_manager.h.
References commands_.
Referenced by yaze::app::editor::EditorManager::InitializeCommands().
RegisterSubcommand()
void yaze::app::editor::CommandManager::RegisterSubcommand (const std::string & group_name, const std::string & shortcut, const char mnemonic, const std::string & name, const std::string & desc, Command command) inline
Definition at line 47 of file command_manager.h.
References commands_.
Referenced by yaze::app::editor::EditorManager::InitializeCommands().
RegisterCommand()
void yaze::app::editor::CommandManager::RegisterCommand (const std::string & shortcut, Command command, char mnemonic, const std::string & name, const std::string & desc) inline
Definition at line 55 of file command_manager.h.
References commands_.
ExecuteCommand()
void yaze::app::editor::CommandManager::ExecuteCommand (const std::string & shortcut) inline
Definition at line 62 of file command_manager.h.
References commands_.
ShowWhichKey()
void yaze::app::editor::CommandManager::ShowWhichKey (EditorLayoutParams * editor_layout = nullptr)
Definition at line 77 of file command_manager.cc.
References commands_, InitializeDefaults(), and yaze::app::editor::MapKeyToImGuiKey().
Referenced by yaze::app::editor::EditorManager::ManageKeyboardShortcuts().
InitializeDefaults()
void yaze::app::editor::CommandManager::InitializeDefaults ()
Definition at line 132 of file command_manager.cc.
Referenced by ShowWhichKey().
SaveKeybindings()
void yaze::app::editor::CommandManager::SaveKeybindings (const std::string & filepath)
Definition at line 134 of file command_manager.cc.
References commands_.
LoadKeybindings()
void yaze::app::editor::CommandManager::LoadKeybindings (const std::string & filepath)
Definition at line 145 of file command_manager.cc.
References commands_.
Member Data Documentation
commands_
std::unordered_map<std::string, CommandInfoOrPrefix> yaze::app::editor::CommandManager::commands_ private
Definition at line 76 of file command_manager.h.
Referenced by ExecuteCommand(), LoadKeybindings(), RegisterCommand(), RegisterPrefix(), RegisterSubcommand(), SaveKeybindings(), and ShowWhichKey().
The documentation for this class was generated from the following files:
src/app/editor/system/command_manager.h
src/app/editor/system/command_manager.cc