yaze: yaze::editor::DungeonEditor Class Reference
yaze::editor::DungeonEditor Class Reference
DungeonEditor class for editing dungeons.
#include <dungeon_editor.h>
Classes
struct ObjectRenderCache
Public Member Functions
DungeonEditor (Rom *rom=nullptr)
void Initialize () override
absl::Status Load () override
absl::Status Update () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Find () override
absl::Status Save () override
void add_room (int i)
void set_rom (Rom *rom)
Rom * rom () const
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Clear ()
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
Private Types
enum BackgroundType {
kNoBackground , kBackground1 , kBackground2 , kBackground3 ,
kBackgroundAny
}
enum PlacementType {
kNoType , kObject , kSprite , kItem ,
kEntrance , kDoor , kChest , kBlock
}
Private Member Functions
absl::Status RefreshGraphics ()
void LoadDungeonRoomSize ()
absl::Status UpdateDungeonRoomView ()
void DrawToolset ()
void DrawRoomSelector ()
void DrawEntranceSelector ()
void DrawDungeonTabView ()
void DrawDungeonCanvas (int room_id)
void DrawRoomGraphics ()
void DrawTileSelector ()
void DrawObjectRenderer ()
void DrawObjectEditor ()
void DrawSpriteEditor ()
void DrawItemEditor ()
void DrawEntranceEditor ()
void DrawDoorEditor ()
void DrawChestEditor ()
void DrawPropertiesEditor ()
void DrawIntegratedEditingPanels ()
void DrawCompactObjectEditor ()
void DrawCompactSpriteEditor ()
void DrawCompactItemEditor ()
void DrawCompactEntranceEditor ()
void DrawCompactDoorEditor ()
void DrawCompactChestEditor ()
void DrawCompactPropertiesEditor ()
void RenderObjectInCanvas (const zelda3::RoomObject &object, const gfx::SnesPalette &palette)
void DisplayObjectInfo (const zelda3::RoomObject &object, int canvas_x, int canvas_y)
void RenderLayoutObjects (const zelda3::RoomLayout &layout, const gfx::SnesPalette &palette)
std::pair< int, int > RoomToCanvasCoordinates (int room_x, int room_y) const
std::pair< int, int > CanvasToRoomCoordinates (int canvas_x, int canvas_y) const
bool IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin=32) const
absl::Status LoadAndRenderRoomGraphics (int room_id)
absl::Status ReloadAllRoomGraphics ()
absl::Status UpdateRoomBackgroundLayers (int room_id)
void RenderRoomBackgroundLayers (int room_id)
void CalculateUsageStats ()
void DrawUsageStats ()
void DrawUsageGrid ()
void RenderSetUsage (const absl::flat_hash_map< uint16_t, int > &usage_map, uint16_t &selected_set, int spriteset_offset=0x00)
Private Attributes
std::vector< ObjectRenderCache > object_render_cache_
uint64_t last_palette_hash_ = 0
zelda3::RoomObject preview_object_
gfx::SnesPalette preview_palette_
int background_type_ = kNoBackground
int placement_type_ = kNoType
bool is_loaded_ = false
bool object_loaded_ = false
bool palette_showing_ = false
bool refresh_graphics_ = false
std::unique_ptr< zelda3::DungeonEditorSystem > dungeon_editor_system_
std::shared_ptr< zelda3::DungeonObjectEditor > object_editor_
bool show_object_editor_ = false
bool show_sprite_editor_ = false
bool show_item_editor_ = false
bool show_entrance_editor_ = false
bool show_door_editor_ = false
bool show_chest_editor_ = false
bool show_properties_editor_ = false
uint16_t current_entrance_id_ = 0
uint16_t current_room_id_ = 0
uint64_t current_palette_id_ = 0
uint64_t current_palette_group_id_ = 0
ImVector< int > active_rooms_
int current_active_room_tab_ = 0
GfxGroupEditor gfx_group_editor_
PaletteEditor palette_editor_
gfx::SnesPalette current_palette_
gfx::SnesPalette full_palette_
gfx::PaletteGroup current_palette_group_
gui::Canvas canvas_ {"##DungeonCanvas", ImVec2(0x200, 0x200)}
gui::Canvas room_gfx_canvas_
gui::Canvas object_canvas_
std::array< gfx::Bitmap, kNumGfxSheets > graphics_bin_
std::array< zelda3::Room, 0x128 > rooms_ = {}
std::array< zelda3::RoomEntrance, 0x8C > entrances_ = {}
zelda3::ObjectRenderer object_renderer_
DungeonRoomSelector room_selector_
DungeonCanvasViewer canvas_viewer_
DungeonObjectSelector object_selector_
absl::flat_hash_map< uint16_t, int > spriteset_usage_
absl::flat_hash_map< uint16_t, int > blockset_usage_
absl::flat_hash_map< uint16_t, int > palette_usage_
std::vector< int64_t > room_size_pointers_
std::vector< int64_t > room_sizes_
uint16_t selected_blockset_ = 0xFFFF
uint16_t selected_spriteset_ = 0xFFFF
uint16_t selected_palette_ = 0xFFFF
uint64_t total_room_size_ = 0
std::unordered_map< int, int > room_size_addresses_
std::unordered_map< int, ImVec4 > room_palette_
absl::Status status_
Rom * rom_
Additional Inherited Members
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Detailed Description
DungeonEditor class for editing dungeons.
This class provides a comprehensive dungeon editing interface that integrates with the new unified dungeon editing system. It includes object editing with scroll wheel support, sprite management, item placement, entrance/exit editing, and advanced dungeon features.
Definition at line 45 of file dungeon_editor.h.
Member Enumeration Documentation
BackgroundType
enum yaze::editor::DungeonEditor::BackgroundType private
Enumerator
kNoBackground
kBackground1
kBackground2
kBackground3
kBackgroundAny
Definition at line 158 of file dungeon_editor.h.
PlacementType
enum yaze::editor::DungeonEditor::PlacementType private
Enumerator
kNoType
kObject
kSprite
kItem
kEntrance
kDoor
kChest
kBlock
Definition at line 167 of file dungeon_editor.h.
Constructor & Destructor Documentation
DungeonEditor()
yaze::editor::DungeonEditor::DungeonEditor (Rom * rom = nullptr) inline explicit
Definition at line 47 of file dungeon_editor.h.
References canvas_viewer_, dungeon_editor_system_, yaze::editor::kDungeon, object_editor_, object_renderer_, object_selector_, preview_object_, rom(), rom_, room_selector_, and yaze::editor::Editor::type_.
Member Function Documentation
Initialize()
void yaze::editor::DungeonEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 45 of file dungeon_editor.cc.
References dungeon_editor_system_, object_editor_, and rom_.
Load()
absl::Status yaze::editor::DungeonEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 53 of file dungeon_editor.cc.
References active_rooms_, ASSIGN_OR_RETURN, yaze::zelda3::CalculateRoomSize(), CalculateUsageStats(), canvas_viewer_, yaze::gfx::CreatePaletteGroupFromLargePalette(), current_palette_group_, current_palette_group_id_, current_palette_id_, dungeon_editor_system_, entrances_, full_palette_, is_loaded_, LoadDungeonRoomSize(), yaze::zelda3::LoadRoomFromRom(), object_selector_, yaze::Rom::palette_group(), yaze::Rom::paletteset_ids, yaze::Rom::ReadWord(), rom(), rom_, room_palette_, room_selector_, room_size_addresses_, room_size_pointers_, room_sizes_, and rooms_.
Update()
absl::Status yaze::editor::DungeonEditor::Update () override virtual
Implements yaze::editor::Editor.
Definition at line 122 of file dungeon_editor.cc.
References DrawUsageStats(), is_loaded_, refresh_graphics_, RefreshGraphics(), RETURN_IF_ERROR, status_, and UpdateDungeonRoomView().
Undo()
absl::Status yaze::editor::DungeonEditor::Undo () override virtual
Implements yaze::editor::Editor.
Definition at line 146 of file dungeon_editor.cc.
References dungeon_editor_system_.
Referenced by DrawToolset().
Redo()
absl::Status yaze::editor::DungeonEditor::Redo () override virtual
Implements yaze::editor::Editor.
Definition at line 153 of file dungeon_editor.cc.
References dungeon_editor_system_.
Referenced by DrawToolset().
Cut()
absl::Status yaze::editor::DungeonEditor::Cut () inline override virtual
Implements yaze::editor::Editor.
Definition at line 63 of file dungeon_editor.h.
Copy()
absl::Status yaze::editor::DungeonEditor::Copy () inline override virtual
Implements yaze::editor::Editor.
Definition at line 64 of file dungeon_editor.h.
Paste()
absl::Status yaze::editor::DungeonEditor::Paste () inline override virtual
Implements yaze::editor::Editor.
Definition at line 65 of file dungeon_editor.h.
Find()
absl::Status yaze::editor::DungeonEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 66 of file dungeon_editor.h.
Save()
absl::Status yaze::editor::DungeonEditor::Save () override virtual
Implements yaze::editor::Editor.
Definition at line 160 of file dungeon_editor.cc.
References dungeon_editor_system_.
add_room()
void yaze::editor::DungeonEditor::add_room (int i) inline
Definition at line 69 of file dungeon_editor.h.
References active_rooms_.
set_rom()
void yaze::editor::DungeonEditor::set_rom (Rom * rom) inline
Definition at line 71 of file dungeon_editor.h.
References canvas_viewer_, object_selector_, rom(), rom_, and room_selector_.
rom()
Rom * yaze::editor::DungeonEditor::rom () const inline
Definition at line 78 of file dungeon_editor.h.
References rom_.
Referenced by DrawEntranceSelector(), DrawObjectRenderer(), DrawRoomSelector(), DungeonEditor(), Load(), LoadAndRenderRoomGraphics(), RefreshGraphics(), set_rom(), UpdateDungeonRoomView(), and UpdateRoomBackgroundLayers().
RefreshGraphics()
absl::Status yaze::editor::DungeonEditor::RefreshGraphics () private
Definition at line 167 of file dungeon_editor.cc.
References current_palette_group_, current_palette_id_, current_room_id_, yaze::editor::Renderer::Get(), yaze::gfx::Arena::Get(), yaze::gfx::Arena::gfx_sheets(), yaze::Rom::palette_group(), rom(), rooms_, and yaze::core::Renderer::UpdateBitmap().
Referenced by Update().
LoadDungeonRoomSize()
void yaze::editor::DungeonEditor::LoadDungeonRoomSize () private
Definition at line 186 of file dungeon_editor.cc.
References room_size_addresses_, room_sizes_, and total_room_size_.
Referenced by Load().
UpdateDungeonRoomView()
absl::Status yaze::editor::DungeonEditor::UpdateDungeonRoomView () private
Definition at line 227 of file dungeon_editor.cc.
References active_rooms_, canvas_viewer_, current_active_room_tab_, current_palette_, current_palette_group_id_, current_palette_id_, current_room_id_, DrawToolset(), yaze::editor::kDungeonTableFlags, object_selector_, yaze::Rom::palette_group(), palette_showing_, refresh_graphics_, rom(), room_selector_, and yaze::gui::SelectablePalettePipeline().
Referenced by Update().
DrawToolset()
void yaze::editor::DungeonEditor::DrawToolset () private
Definition at line 269 of file dungeon_editor.cc.
References background_type_, ICON_MD_FILTER_1, ICON_MD_FILTER_2, ICON_MD_FILTER_3, ICON_MD_FILTER_NONE, ICON_MD_GRASS, ICON_MD_INVENTORY, ICON_MD_MORE_VERT, ICON_MD_NAVIGATION, ICON_MD_PALETTE, ICON_MD_PEST_CONTROL, ICON_MD_REDO, ICON_MD_SENSOR_DOOR, ICON_MD_SQUARE, ICON_MD_UNDO, ICON_MD_VIEW_MODULE, kBackground1, kBackground2, kBackground3, kBackgroundAny, kBlock, kChest, kDoor, kEntrance, kItem, kObject, kSprite, palette_showing_, placement_type_, PRINT_IF_ERROR, Redo(), and Undo().
Referenced by UpdateDungeonRoomView().
DrawRoomSelector()
void yaze::editor::DungeonEditor::DrawRoomSelector () private
Todo
Jump to tab if room is already open
Definition at line 380 of file dungeon_editor.cc.
References active_rooms_, current_palette_id_, current_room_id_, yaze::util::HexByte(), yaze::gui::InputHex(), yaze::gui::InputHexWord(), yaze::zelda3::kRoomNames, yaze::Rom::resource_label(), rom(), and yaze::ResourceLabelManager::SelectableLabelWithNameEdit().
DrawEntranceSelector()
void yaze::editor::DungeonEditor::DrawEntranceSelector () private
Definition at line 409 of file dungeon_editor.cc.
References active_rooms_, current_entrance_id_, entrances_, yaze::util::HexByte(), yaze::gui::InputHexByte(), yaze::gui::InputHexWord(), yaze::zelda3::kEntranceNames, yaze::Rom::resource_label(), rom(), and yaze::ResourceLabelManager::SelectableLabelWithNameEdit().
DrawDungeonTabView()
void yaze::editor::DungeonEditor::DrawDungeonTabView () private
Definition at line 480 of file dungeon_editor.cc.
References active_rooms_, current_active_room_tab_, current_room_id_, DrawDungeonCanvas(), ICON_MD_ADD, yaze::editor::kDungeonTabBarFlags, yaze::editor::kDungeonTabFlags, and yaze::zelda3::kRoomNames.
DrawDungeonCanvas()
void yaze::editor::DungeonEditor::DrawDungeonCanvas (int room_id) private
Definition at line 520 of file dungeon_editor.cc.
References canvas_, current_palette_group_, current_palette_group_id_, current_palette_id_, yaze::gui::InputHexByte(), yaze::gui::InputHexWord(), is_loaded_, yaze::zelda3::RoomLayoutObject::kDoor, yaze::zelda3::RoomLayoutObject::kFloor, yaze::zelda3::RoomLayoutObject::kWall, last_palette_hash_, LoadAndRenderRoomGraphics(), object_render_cache_, ReloadAllRoomGraphics(), RenderObjectInCanvas(), RenderRoomBackgroundLayers(), rom_, rooms_, and yaze::editor::Editor::type().
Referenced by DrawDungeonTabView().
DrawRoomGraphics()
void yaze::editor::DungeonEditor::DrawRoomGraphics () private
Definition at line 840 of file dungeon_editor.cc.
References active_rooms_, current_active_room_tab_, yaze::gfx::Arena::Get(), yaze::gfx::Arena::gfx_sheets(), is_loaded_, LoadAndRenderRoomGraphics(), room_gfx_canvas_, and rooms_.
Referenced by DrawTileSelector().
DrawTileSelector()
void yaze::editor::DungeonEditor::DrawTileSelector () private
Definition at line 899 of file dungeon_editor.cc.
References DrawObjectRenderer(), and DrawRoomGraphics().
DrawObjectRenderer()
void yaze::editor::DungeonEditor::DrawObjectRenderer () private
Definition at line 919 of file dungeon_editor.cc.
References current_palette_group_id_, yaze::core::Renderer::Get(), yaze::editor::kDungeonObjectTableFlags, object_canvas_, object_loaded_, object_renderer_, yaze::Rom::palette_group(), preview_object_, preview_palette_, yaze::core::Renderer::RenderBitmap(), rom(), and rom_.
Referenced by DrawTileSelector().
DrawObjectEditor()
void yaze::editor::DungeonEditor::DrawObjectEditor () private
Definition at line 1244 of file dungeon_editor.cc.
References yaze::zelda3::DungeonObjectEditor::kEdit, yaze::zelda3::DungeonObjectEditor::kInsert, yaze::zelda3::DungeonObjectEditor::kSelect, and object_editor_.
DrawSpriteEditor()
void yaze::editor::DungeonEditor::DrawSpriteEditor () private
Definition at line 1315 of file dungeon_editor.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::kEnemy, yaze::zelda3::DungeonEditorSystem::SpriteData::layer, yaze::zelda3::DungeonEditorSystem::SpriteData::sprite_id, yaze::zelda3::DungeonEditorSystem::SpriteData::type, yaze::zelda3::DungeonEditorSystem::SpriteData::x, and yaze::zelda3::DungeonEditorSystem::SpriteData::y.
DrawItemEditor()
void yaze::editor::DungeonEditor::DrawItemEditor () private
Definition at line 1369 of file dungeon_editor.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::ItemData::is_hidden, yaze::zelda3::DungeonEditorSystem::ItemData::item_id, yaze::zelda3::DungeonEditorSystem::kKey, yaze::zelda3::DungeonEditorSystem::ItemData::room_id, yaze::zelda3::DungeonEditorSystem::ItemData::type, yaze::zelda3::DungeonEditorSystem::ItemData::x, and yaze::zelda3::DungeonEditorSystem::ItemData::y.
DrawEntranceEditor()
void yaze::editor::DungeonEditor::DrawEntranceEditor () private
Definition at line 1425 of file dungeon_editor.cc.
References dungeon_editor_system_.
DrawDoorEditor()
void yaze::editor::DungeonEditor::DrawDoorEditor () private
Definition at line 1478 of file dungeon_editor.cc.
References yaze::zelda3::DungeonEditorSystem::DoorData::direction, dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::DoorData::is_locked, yaze::zelda3::DungeonEditorSystem::DoorData::key_type, yaze::zelda3::DungeonEditorSystem::DoorData::requires_key, yaze::zelda3::DungeonEditorSystem::DoorData::room_id, yaze::zelda3::DungeonEditorSystem::DoorData::target_room_id, yaze::zelda3::DungeonEditorSystem::DoorData::target_x, yaze::zelda3::DungeonEditorSystem::DoorData::target_y, yaze::zelda3::DungeonEditorSystem::DoorData::x, and yaze::zelda3::DungeonEditorSystem::DoorData::y.
DrawChestEditor()
void yaze::editor::DungeonEditor::DrawChestEditor () private
Definition at line 1548 of file dungeon_editor.cc.
References dungeon_editor_system_, chest::x, and chest::y.
DrawPropertiesEditor()
void yaze::editor::DungeonEditor::DrawPropertiesEditor () private
DrawIntegratedEditingPanels()
void yaze::editor::DungeonEditor::DrawIntegratedEditingPanels () private
Definition at line 1607 of file dungeon_editor.cc.
References DrawCompactChestEditor(), DrawCompactDoorEditor(), DrawCompactEntranceEditor(), DrawCompactItemEditor(), DrawCompactObjectEditor(), DrawCompactPropertiesEditor(), DrawCompactSpriteEditor(), dungeon_editor_system_, and object_editor_.
DrawCompactObjectEditor()
void yaze::editor::DungeonEditor::DrawCompactObjectEditor () private
Definition at line 1661 of file dungeon_editor.cc.
References yaze::zelda3::DungeonObjectEditor::kEdit, yaze::zelda3::DungeonObjectEditor::kInsert, yaze::zelda3::DungeonObjectEditor::kSelect, and object_editor_.
Referenced by DrawIntegratedEditingPanels().
DrawCompactSpriteEditor()
void yaze::editor::DungeonEditor::DrawCompactSpriteEditor () private
Definition at line 1724 of file dungeon_editor.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::kEnemy, yaze::zelda3::DungeonEditorSystem::SpriteData::layer, yaze::zelda3::DungeonEditorSystem::SpriteData::sprite_id, yaze::zelda3::DungeonEditorSystem::SpriteData::type, yaze::zelda3::DungeonEditorSystem::SpriteData::x, and yaze::zelda3::DungeonEditorSystem::SpriteData::y.
Referenced by DrawIntegratedEditingPanels().
DrawCompactItemEditor()
void yaze::editor::DungeonEditor::DrawCompactItemEditor () private
Definition at line 1777 of file dungeon_editor.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::ItemData::is_hidden, yaze::zelda3::DungeonEditorSystem::ItemData::item_id, yaze::zelda3::DungeonEditorSystem::kKey, yaze::zelda3::DungeonEditorSystem::ItemData::room_id, yaze::zelda3::DungeonEditorSystem::ItemData::type, yaze::zelda3::DungeonEditorSystem::ItemData::x, and yaze::zelda3::DungeonEditorSystem::ItemData::y.
Referenced by DrawIntegratedEditingPanels().
DrawCompactEntranceEditor()
void yaze::editor::DungeonEditor::DrawCompactEntranceEditor () private
Definition at line 1831 of file dungeon_editor.cc.
References dungeon_editor_system_.
Referenced by DrawIntegratedEditingPanels().
DrawCompactDoorEditor()
void yaze::editor::DungeonEditor::DrawCompactDoorEditor () private
Definition at line 1878 of file dungeon_editor.cc.
References yaze::zelda3::DungeonEditorSystem::DoorData::direction, dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::DoorData::is_locked, yaze::zelda3::DungeonEditorSystem::DoorData::key_type, yaze::zelda3::DungeonEditorSystem::DoorData::requires_key, yaze::zelda3::DungeonEditorSystem::DoorData::room_id, yaze::zelda3::DungeonEditorSystem::DoorData::target_room_id, yaze::zelda3::DungeonEditorSystem::DoorData::target_x, yaze::zelda3::DungeonEditorSystem::DoorData::target_y, yaze::zelda3::DungeonEditorSystem::DoorData::x, and yaze::zelda3::DungeonEditorSystem::DoorData::y.
Referenced by DrawIntegratedEditingPanels().
DrawCompactChestEditor()
void yaze::editor::DungeonEditor::DrawCompactChestEditor () private
Definition at line 1932 of file dungeon_editor.cc.
References dungeon_editor_system_, chest::x, and chest::y.
Referenced by DrawIntegratedEditingPanels().
DrawCompactPropertiesEditor()
void yaze::editor::DungeonEditor::DrawCompactPropertiesEditor () private
Definition at line 1982 of file dungeon_editor.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::RoomProperties::dungeon_id, yaze::zelda3::DungeonEditorSystem::RoomProperties::floor_level, yaze::zelda3::DungeonEditorSystem::RoomProperties::is_boss_room, yaze::zelda3::DungeonEditorSystem::RoomProperties::is_save_room, yaze::zelda3::DungeonEditorSystem::RoomProperties::music_id, yaze::zelda3::DungeonEditorSystem::RoomProperties::name, and yaze::zelda3::DungeonEditorSystem::RoomProperties::room_id.
Referenced by DrawIntegratedEditingPanels().
RenderObjectInCanvas()
void yaze::editor::DungeonEditor::RenderObjectInCanvas (const zelda3::RoomObject & object, const gfx::SnesPalette & palette) private
Definition at line 700 of file dungeon_editor.cc.
References canvas_, yaze::core::Renderer::Get(), yaze::editor::DungeonEditor::ObjectRenderCache::is_valid, IsWithinCanvasBounds(), yaze::editor::DungeonEditor::ObjectRenderCache::object_id, object_render_cache_, object_renderer_, yaze::editor::DungeonEditor::ObjectRenderCache::object_size, yaze::editor::DungeonEditor::ObjectRenderCache::object_x, yaze::editor::DungeonEditor::ObjectRenderCache::object_y, yaze::editor::DungeonEditor::ObjectRenderCache::palette_hash, yaze::core::Renderer::RenderBitmap(), yaze::editor::DungeonEditor::ObjectRenderCache::rendered_bitmap, rom_, RoomToCanvasCoordinates(), yaze::zelda3::RoomObject::set_rom(), and yaze::gfx::SnesPalette::size().
Referenced by DrawDungeonCanvas().
DisplayObjectInfo()
void yaze::editor::DungeonEditor::DisplayObjectInfo (const zelda3::RoomObject & object, int canvas_x, int canvas_y) private
Definition at line 778 of file dungeon_editor.cc.
References canvas_.
RenderLayoutObjects()
void yaze::editor::DungeonEditor::RenderLayoutObjects (const zelda3::RoomLayout & layout, const gfx::SnesPalette & palette) private
Definition at line 788 of file dungeon_editor.cc.
References canvas_, yaze::gui::ConvertSnesColorToImVec4(), yaze::zelda3::RoomLayout::GetObjects(), IsWithinCanvasBounds(), yaze::zelda3::RoomLayoutObject::kCeiling, yaze::zelda3::RoomLayoutObject::kDoor, yaze::zelda3::RoomLayoutObject::kFloor, yaze::zelda3::RoomLayoutObject::kPit, yaze::zelda3::RoomLayoutObject::kStairs, yaze::zelda3::RoomLayoutObject::kWall, yaze::zelda3::RoomLayoutObject::kWater, and RoomToCanvasCoordinates().
RoomToCanvasCoordinates()
std::pair< int, int > yaze::editor::DungeonEditor::RoomToCanvasCoordinates (int room_x, int room_y) const private
Definition at line 2050 of file dungeon_editor.cc.
Referenced by RenderLayoutObjects(), and RenderObjectInCanvas().
CanvasToRoomCoordinates()
std::pair< int, int > yaze::editor::DungeonEditor::CanvasToRoomCoordinates (int canvas_x, int canvas_y) const private
Definition at line 2056 of file dungeon_editor.cc.
IsWithinCanvasBounds()
bool yaze::editor::DungeonEditor::IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin = 32) const private
Definition at line 2062 of file dungeon_editor.cc.
References canvas_.
Referenced by RenderLayoutObjects(), and RenderObjectInCanvas().
LoadAndRenderRoomGraphics()
absl::Status yaze::editor::DungeonEditor::LoadAndRenderRoomGraphics (int room_id) private
Definition at line 2073 of file dungeon_editor.cc.
References ASSIGN_OR_RETURN, yaze::gfx::CreatePaletteGroupFromLargePalette(), current_palette_group_, current_palette_group_id_, full_palette_, yaze::Rom::palette_group(), yaze::Rom::paletteset_ids, yaze::Rom::ReadWord(), refresh_graphics_, RETURN_IF_ERROR, rom(), rom_, rooms_, yaze::Rom::size(), and UpdateRoomBackgroundLayers().
Referenced by DrawDungeonCanvas(), DrawRoomGraphics(), and ReloadAllRoomGraphics().
ReloadAllRoomGraphics()
absl::Status yaze::editor::DungeonEditor::ReloadAllRoomGraphics () private
Definition at line 2114 of file dungeon_editor.cc.
References LoadAndRenderRoomGraphics(), RETURN_IF_ERROR, and rooms_.
Referenced by DrawDungeonCanvas().
UpdateRoomBackgroundLayers()
absl::Status yaze::editor::DungeonEditor::UpdateRoomBackgroundLayers (int room_id) private
Definition at line 2123 of file dungeon_editor.cc.
References current_palette_group_, current_palette_group_id_, current_palette_id_, yaze::core::Renderer::Get(), yaze::gfx::Arena::Get(), yaze::gfx::Arena::gfx_sheets(), yaze::Rom::palette_group(), rom(), rom_, rooms_, yaze::Rom::size(), and yaze::core::Renderer::UpdateBitmap().
Referenced by LoadAndRenderRoomGraphics().
RenderRoomBackgroundLayers()
void yaze::editor::DungeonEditor::RenderRoomBackgroundLayers (int room_id) private
Definition at line 2174 of file dungeon_editor.cc.
References yaze::gfx::Arena::bg1(), yaze::gfx::Arena::bg2(), canvas_, yaze::gfx::Arena::Get(), rom_, and rooms_.
Referenced by DrawDungeonCanvas().
CalculateUsageStats()
void yaze::editor::DungeonEditor::CalculateUsageStats () private
Definition at line 1000 of file dungeon_editor.cc.
References blockset_usage_, palette_usage_, rooms_, and spriteset_usage_.
Referenced by DrawUsageStats(), and Load().
DrawUsageStats()
void yaze::editor::DungeonEditor::DrawUsageStats () private
Definition at line 1070 of file dungeon_editor.cc.
References blockset_usage_, CalculateUsageStats(), DrawUsageGrid(), gfx_group_editor_, yaze::editor::kDungeonTableFlags, palette_usage_, RenderSetUsage(), selected_blockset_, selected_palette_, selected_spriteset_, spriteset_usage_, and total_room_size_.
Referenced by Update().
DrawUsageGrid()
void yaze::editor::DungeonEditor::DrawUsageGrid () private
Definition at line 1155 of file dungeon_editor.cc.
References room_palette_, room_size_pointers_, room_sizes_, rooms_, selected_blockset_, selected_palette_, and selected_spriteset_.
Referenced by DrawUsageStats().
RenderSetUsage()
void yaze::editor::DungeonEditor::RenderSetUsage (const absl::flat_hash_map< uint16_t, int > & usage_map, uint16_t & selected_set, int spriteset_offset = 0x00) private
Definition at line 1022 of file dungeon_editor.cc.
Referenced by DrawUsageStats().
Member Data Documentation
object_render_cache_
std::vector<ObjectRenderCache> yaze::editor::DungeonEditor::object_render_cache_ private
Definition at line 145 of file dungeon_editor.h.
Referenced by DrawDungeonCanvas(), and RenderObjectInCanvas().
last_palette_hash_
uint64_t yaze::editor::DungeonEditor::last_palette_hash_ = 0 private
Definition at line 146 of file dungeon_editor.h.
Referenced by DrawDungeonCanvas().
preview_object_
zelda3::RoomObject yaze::editor::DungeonEditor::preview_object_ private
Definition at line 149 of file dungeon_editor.h.
Referenced by DrawObjectRenderer(), and DungeonEditor().
preview_palette_
gfx::SnesPalette yaze::editor::DungeonEditor::preview_palette_ private
Definition at line 150 of file dungeon_editor.h.
Referenced by DrawObjectRenderer().
background_type_
int yaze::editor::DungeonEditor::background_type_ = kNoBackground private
Definition at line 178 of file dungeon_editor.h.
Referenced by DrawToolset().
placement_type_
int yaze::editor::DungeonEditor::placement_type_ = kNoType private
Definition at line 179 of file dungeon_editor.h.
Referenced by DrawToolset().
is_loaded_
bool yaze::editor::DungeonEditor::is_loaded_ = false private
Definition at line 181 of file dungeon_editor.h.
Referenced by DrawDungeonCanvas(), DrawRoomGraphics(), Load(), and Update().
object_loaded_
bool yaze::editor::DungeonEditor::object_loaded_ = false private
Definition at line 182 of file dungeon_editor.h.
Referenced by DrawObjectRenderer().
palette_showing_
bool yaze::editor::DungeonEditor::palette_showing_ = false private
Definition at line 183 of file dungeon_editor.h.
Referenced by DrawToolset(), and UpdateDungeonRoomView().
refresh_graphics_
bool yaze::editor::DungeonEditor::refresh_graphics_ = false private
Definition at line 184 of file dungeon_editor.h.
Referenced by LoadAndRenderRoomGraphics(), Update(), and UpdateDungeonRoomView().
dungeon_editor_system_
std::unique_ptr<zelda3::DungeonEditorSystem> yaze::editor::DungeonEditor::dungeon_editor_system_ private
Definition at line 187 of file dungeon_editor.h.
Referenced by DrawChestEditor(), DrawCompactChestEditor(), DrawCompactDoorEditor(), DrawCompactEntranceEditor(), DrawCompactItemEditor(), DrawCompactPropertiesEditor(), DrawCompactSpriteEditor(), DrawDoorEditor(), DrawEntranceEditor(), DrawIntegratedEditingPanels(), DrawItemEditor(), DrawSpriteEditor(), DungeonEditor(), Initialize(), Load(), Redo(), Save(), and Undo().
object_editor_
std::shared_ptr<zelda3::DungeonObjectEditor> yaze::editor::DungeonEditor::object_editor_ private
Definition at line 188 of file dungeon_editor.h.
Referenced by DrawCompactObjectEditor(), DrawIntegratedEditingPanels(), DrawObjectEditor(), DungeonEditor(), and Initialize().
show_object_editor_
bool yaze::editor::DungeonEditor::show_object_editor_ = false private
Definition at line 189 of file dungeon_editor.h.
show_sprite_editor_
bool yaze::editor::DungeonEditor::show_sprite_editor_ = false private
Definition at line 190 of file dungeon_editor.h.
show_item_editor_
bool yaze::editor::DungeonEditor::show_item_editor_ = false private
Definition at line 191 of file dungeon_editor.h.
show_entrance_editor_
bool yaze::editor::DungeonEditor::show_entrance_editor_ = false private
Definition at line 192 of file dungeon_editor.h.
show_door_editor_
bool yaze::editor::DungeonEditor::show_door_editor_ = false private
Definition at line 193 of file dungeon_editor.h.
show_chest_editor_
bool yaze::editor::DungeonEditor::show_chest_editor_ = false private
Definition at line 194 of file dungeon_editor.h.
show_properties_editor_
bool yaze::editor::DungeonEditor::show_properties_editor_ = false private
Definition at line 195 of file dungeon_editor.h.
current_entrance_id_
uint16_t yaze::editor::DungeonEditor::current_entrance_id_ = 0 private
Definition at line 197 of file dungeon_editor.h.
Referenced by DrawEntranceSelector().
current_room_id_
uint16_t yaze::editor::DungeonEditor::current_room_id_ = 0 private
Definition at line 198 of file dungeon_editor.h.
Referenced by DrawDungeonTabView(), DrawRoomSelector(), RefreshGraphics(), and UpdateDungeonRoomView().
current_palette_id_
uint64_t yaze::editor::DungeonEditor::current_palette_id_ = 0 private
Definition at line 199 of file dungeon_editor.h.
Referenced by DrawDungeonCanvas(), DrawRoomSelector(), Load(), RefreshGraphics(), UpdateDungeonRoomView(), and UpdateRoomBackgroundLayers().
current_palette_group_id_
uint64_t yaze::editor::DungeonEditor::current_palette_group_id_ = 0 private
Definition at line 200 of file dungeon_editor.h.
Referenced by DrawDungeonCanvas(), DrawObjectRenderer(), Load(), LoadAndRenderRoomGraphics(), UpdateDungeonRoomView(), and UpdateRoomBackgroundLayers().
active_rooms_
ImVector<int> yaze::editor::DungeonEditor::active_rooms_ private
Definition at line 202 of file dungeon_editor.h.
Referenced by add_room(), DrawDungeonTabView(), DrawEntranceSelector(), DrawRoomGraphics(), DrawRoomSelector(), Load(), and UpdateDungeonRoomView().
current_active_room_tab_
int yaze::editor::DungeonEditor::current_active_room_tab_ = 0 private
Definition at line 203 of file dungeon_editor.h.
Referenced by DrawDungeonTabView(), DrawRoomGraphics(), and UpdateDungeonRoomView().
gfx_group_editor_
GfxGroupEditor yaze::editor::DungeonEditor::gfx_group_editor_ private
Definition at line 205 of file dungeon_editor.h.
Referenced by DrawUsageStats().
palette_editor_
PaletteEditor yaze::editor::DungeonEditor::palette_editor_ private
Definition at line 206 of file dungeon_editor.h.
current_palette_
gfx::SnesPalette yaze::editor::DungeonEditor::current_palette_ private
Definition at line 207 of file dungeon_editor.h.
Referenced by UpdateDungeonRoomView().
full_palette_
gfx::SnesPalette yaze::editor::DungeonEditor::full_palette_ private
Definition at line 208 of file dungeon_editor.h.
Referenced by Load(), and LoadAndRenderRoomGraphics().
current_palette_group_
gfx::PaletteGroup yaze::editor::DungeonEditor::current_palette_group_ private
Definition at line 209 of file dungeon_editor.h.
Referenced by DrawDungeonCanvas(), Load(), LoadAndRenderRoomGraphics(), RefreshGraphics(), and UpdateRoomBackgroundLayers().
canvas_
gui::Canvas yaze::editor::DungeonEditor::canvas_ {"##DungeonCanvas", ImVec2(0x200, 0x200)} private
Definition at line 211 of file dungeon_editor.h.
Referenced by DisplayObjectInfo(), DrawDungeonCanvas(), IsWithinCanvasBounds(), RenderLayoutObjects(), RenderObjectInCanvas(), and RenderRoomBackgroundLayers().
room_gfx_canvas_
gui::Canvas yaze::editor::DungeonEditor::room_gfx_canvas_ private
Initial value:
{"##RoomGfxCanvas",
                               ImVec2(0x100 + 1, 0x10 * 0x40 + 1)}
Definition at line 212 of file dungeon_editor.h.
Referenced by DrawRoomGraphics().
object_canvas_
gui::Canvas yaze::editor::DungeonEditor::object_canvas_ private
Definition at line 214 of file dungeon_editor.h.
Referenced by DrawObjectRenderer().
graphics_bin_
std::array<gfx::Bitmap, kNumGfxSheets> yaze::editor::DungeonEditor::graphics_bin_ private
Definition at line 216 of file dungeon_editor.h.
rooms_
std::array<zelda3::Room, 0x128> yaze::editor::DungeonEditor::rooms_ = {} private
Definition at line 218 of file dungeon_editor.h.
Referenced by CalculateUsageStats(), DrawDungeonCanvas(), DrawRoomGraphics(), DrawUsageGrid(), Load(), LoadAndRenderRoomGraphics(), RefreshGraphics(), ReloadAllRoomGraphics(), RenderRoomBackgroundLayers(), and UpdateRoomBackgroundLayers().
entrances_
std::array<zelda3::RoomEntrance, 0x8C> yaze::editor::DungeonEditor::entrances_ = {} private
Definition at line 219 of file dungeon_editor.h.
Referenced by DrawEntranceSelector(), and Load().
object_renderer_
zelda3::ObjectRenderer yaze::editor::DungeonEditor::object_renderer_ private
Definition at line 220 of file dungeon_editor.h.
Referenced by DrawObjectRenderer(), DungeonEditor(), and RenderObjectInCanvas().
room_selector_
DungeonRoomSelector yaze::editor::DungeonEditor::room_selector_ private
Definition at line 223 of file dungeon_editor.h.
Referenced by DungeonEditor(), Load(), set_rom(), and UpdateDungeonRoomView().
canvas_viewer_
DungeonCanvasViewer yaze::editor::DungeonEditor::canvas_viewer_ private
Definition at line 224 of file dungeon_editor.h.
Referenced by DungeonEditor(), Load(), set_rom(), and UpdateDungeonRoomView().
object_selector_
DungeonObjectSelector yaze::editor::DungeonEditor::object_selector_ private
Definition at line 225 of file dungeon_editor.h.
Referenced by DungeonEditor(), Load(), set_rom(), and UpdateDungeonRoomView().
spriteset_usage_
absl::flat_hash_map<uint16_t, int> yaze::editor::DungeonEditor::spriteset_usage_ private
Definition at line 227 of file dungeon_editor.h.
Referenced by CalculateUsageStats(), and DrawUsageStats().
blockset_usage_
absl::flat_hash_map<uint16_t, int> yaze::editor::DungeonEditor::blockset_usage_ private
Definition at line 228 of file dungeon_editor.h.
Referenced by CalculateUsageStats(), and DrawUsageStats().
palette_usage_
absl::flat_hash_map<uint16_t, int> yaze::editor::DungeonEditor::palette_usage_ private
Definition at line 229 of file dungeon_editor.h.
Referenced by CalculateUsageStats(), and DrawUsageStats().
room_size_pointers_
std::vector<int64_t> yaze::editor::DungeonEditor::room_size_pointers_ private
Definition at line 231 of file dungeon_editor.h.
Referenced by DrawUsageGrid(), and Load().
room_sizes_
std::vector<int64_t> yaze::editor::DungeonEditor::room_sizes_ private
Definition at line 232 of file dungeon_editor.h.
Referenced by DrawUsageGrid(), Load(), and LoadDungeonRoomSize().
selected_blockset_
uint16_t yaze::editor::DungeonEditor::selected_blockset_ = 0xFFFF private
Definition at line 234 of file dungeon_editor.h.
Referenced by DrawUsageGrid(), and DrawUsageStats().
selected_spriteset_
uint16_t yaze::editor::DungeonEditor::selected_spriteset_ = 0xFFFF private
Definition at line 235 of file dungeon_editor.h.
Referenced by DrawUsageGrid(), and DrawUsageStats().
selected_palette_
uint16_t yaze::editor::DungeonEditor::selected_palette_ = 0xFFFF private
Definition at line 236 of file dungeon_editor.h.
Referenced by DrawUsageGrid(), and DrawUsageStats().
total_room_size_
uint64_t yaze::editor::DungeonEditor::total_room_size_ = 0 private
Definition at line 238 of file dungeon_editor.h.
Referenced by DrawUsageStats(), and LoadDungeonRoomSize().
room_size_addresses_
std::unordered_map<int, int> yaze::editor::DungeonEditor::room_size_addresses_ private
Definition at line 240 of file dungeon_editor.h.
Referenced by Load(), and LoadDungeonRoomSize().
room_palette_
std::unordered_map<int, ImVec4> yaze::editor::DungeonEditor::room_palette_ private
Definition at line 241 of file dungeon_editor.h.
Referenced by DrawUsageGrid(), and Load().
status_
absl::Status yaze::editor::DungeonEditor::status_ private
Definition at line 243 of file dungeon_editor.h.
Referenced by Update().
rom_
Rom* yaze::editor::DungeonEditor::rom_ private
Definition at line 245 of file dungeon_editor.h.
Referenced by DrawDungeonCanvas(), DrawObjectRenderer(), DungeonEditor(), Initialize(), Load(), LoadAndRenderRoomGraphics(), RenderObjectInCanvas(), RenderRoomBackgroundLayers(), rom(), set_rom(), and UpdateRoomBackgroundLayers().
The documentation for this class was generated from the following files:
src/app/editor/dungeon/dungeon_editor.h
src/app/editor/dungeon/dungeon_editor.cc