yaze: yaze::zelda3::DungeonObjectRendererIntegrationTest Class Reference
yaze::zelda3::DungeonObjectRendererIntegrationTest Class Reference
Classes
struct PerformanceMetrics
Protected Member Functions
void SetUp () override
void TearDown () override
absl::Status LoadTestRoomData ()
RoomObject CreateTestObject (int object_id, int x, int y, int size=0x12, int layer=0)
std::vector< RoomObject > CreateTestObjectSet (int room_id)
std::vector< RoomObject > CreateGanonRoomObjects ()
std::vector< RoomObject > CreateSewerRoomObjects ()
PerformanceMetrics MeasureRenderPerformance (const std::vector< RoomObject > &objects, const gfx::SnesPalette &palette)
Protected Attributes
std::string rom_path_
std::unique_ptr< Rom > rom_
std::unique_ptr< DungeonEditorSystem > dungeon_editor_system_
std::shared_ptr< DungeonObjectEditor > object_editor_
std::unique_ptr< ObjectRenderer > object_renderer_
std::vector< int > test_rooms_
std::map< int, Room > rooms_
std::vector< gfx::SnesPalette > test_palettes_
Detailed Description
Definition at line 18 of file dungeon_object_renderer_integration_test.cc.
Member Function Documentation
SetUp()
void yaze::zelda3::DungeonObjectRendererIntegrationTest::SetUp () inline override protected
Definition at line 20 of file dungeon_object_renderer_integration_test.cc.
References dungeon_editor_system_, LoadTestRoomData(), object_editor_, object_renderer_, rom_, and rom_path_.
TearDown()
void yaze::zelda3::DungeonObjectRendererIntegrationTest::TearDown () inline override protected
Definition at line 48 of file dungeon_object_renderer_integration_test.cc.
References dungeon_editor_system_, object_editor_, object_renderer_, and rom_.
LoadTestRoomData()
absl::Status yaze::zelda3::DungeonObjectRendererIntegrationTest::LoadTestRoomData () inline protected
Definition at line 55 of file dungeon_object_renderer_integration_test.cc.
References yaze::zelda3::LoadRoomFromRom(), rom_, rooms_, test_palettes_, and test_rooms_.
Referenced by SetUp().
CreateTestObject()
RoomObject yaze::zelda3::DungeonObjectRendererIntegrationTest::CreateTestObject (int object_id, int x, int y, int size = 0x12, int layer = 0) inline protected
Definition at line 86 of file dungeon_object_renderer_integration_test.cc.
References yaze::zelda3::RoomObject::EnsureTilesLoaded(), rom_, and yaze::zelda3::RoomObject::set_rom().
Referenced by CreateGanonRoomObjects(), CreateSewerRoomObjects(), and CreateTestObjectSet().
CreateTestObjectSet()
std::vector< RoomObject > yaze::zelda3::DungeonObjectRendererIntegrationTest::CreateTestObjectSet (int room_id) inline protected
Definition at line 93 of file dungeon_object_renderer_integration_test.cc.
References CreateTestObject().
CreateGanonRoomObjects()
std::vector< RoomObject > yaze::zelda3::DungeonObjectRendererIntegrationTest::CreateGanonRoomObjects () inline protected
Definition at line 109 of file dungeon_object_renderer_integration_test.cc.
References CreateTestObject().
CreateSewerRoomObjects()
std::vector< RoomObject > yaze::zelda3::DungeonObjectRendererIntegrationTest::CreateSewerRoomObjects () inline protected
Definition at line 120 of file dungeon_object_renderer_integration_test.cc.
References CreateTestObject().
MeasureRenderPerformance()
PerformanceMetrics yaze::zelda3::DungeonObjectRendererIntegrationTest::MeasureRenderPerformance (const std::vector< RoomObject > & objects, const gfx::SnesPalette & palette) inline protected
Definition at line 140 of file dungeon_object_renderer_integration_test.cc.
References yaze::zelda3::DungeonObjectRendererIntegrationTest::PerformanceMetrics::cache_hits, yaze::zelda3::DungeonObjectRendererIntegrationTest::PerformanceMetrics::cache_misses, yaze::zelda3::DungeonObjectRendererIntegrationTest::PerformanceMetrics::memory_used, object_renderer_, yaze::zelda3::DungeonObjectRendererIntegrationTest::PerformanceMetrics::objects_rendered, and yaze::zelda3::DungeonObjectRendererIntegrationTest::PerformanceMetrics::render_time.
Member Data Documentation
rom_path_
std::string yaze::zelda3::DungeonObjectRendererIntegrationTest::rom_path_ protected
Definition at line 162 of file dungeon_object_renderer_integration_test.cc.
Referenced by SetUp().
rom_
std::unique_ptr<Rom> yaze::zelda3::DungeonObjectRendererIntegrationTest::rom_ protected
Definition at line 163 of file dungeon_object_renderer_integration_test.cc.
Referenced by CreateTestObject(), LoadTestRoomData(), SetUp(), and TearDown().
dungeon_editor_system_
std::unique_ptr<DungeonEditorSystem> yaze::zelda3::DungeonObjectRendererIntegrationTest::dungeon_editor_system_ protected
Definition at line 164 of file dungeon_object_renderer_integration_test.cc.
Referenced by SetUp(), and TearDown().
object_editor_
std::shared_ptr<DungeonObjectEditor> yaze::zelda3::DungeonObjectRendererIntegrationTest::object_editor_ protected
Definition at line 165 of file dungeon_object_renderer_integration_test.cc.
Referenced by SetUp(), and TearDown().
object_renderer_
std::unique_ptr<ObjectRenderer> yaze::zelda3::DungeonObjectRendererIntegrationTest::object_renderer_ protected
Definition at line 166 of file dungeon_object_renderer_integration_test.cc.
Referenced by MeasureRenderPerformance(), SetUp(), and TearDown().
test_rooms_
std::vector<int> yaze::zelda3::DungeonObjectRendererIntegrationTest::test_rooms_ protected
Definition at line 169 of file dungeon_object_renderer_integration_test.cc.
Referenced by LoadTestRoomData().
rooms_
std::map<int, Room> yaze::zelda3::DungeonObjectRendererIntegrationTest::rooms_ protected
Definition at line 170 of file dungeon_object_renderer_integration_test.cc.
Referenced by LoadTestRoomData().
test_palettes_
std::vector<gfx::SnesPalette> yaze::zelda3::DungeonObjectRendererIntegrationTest::test_palettes_ protected
Definition at line 171 of file dungeon_object_renderer_integration_test.cc.
Referenced by LoadTestRoomData().
The documentation for this class was generated from the following file:
test/zelda3/dungeon_object_renderer_integration_test.cc