yaze: yaze::core::PerformanceMonitor Class Reference
yaze::core::PerformanceMonitor Class Reference
Simple performance monitoring for ROM loading and rendering operations.
#include <performance_monitor.h>
Classes
struct OperationData
Public Member Functions
void StartTimer (const std::string &operation_name)
Start timing an operation.
void EndTimer (const std::string &operation_name)
End timing an operation and record the duration.
double GetAverageTime (const std::string &operation_name) const
Get the average time for an operation in milliseconds.
double GetTotalTime (const std::string &operation_name) const
Get the total time for an operation in milliseconds.
int GetOperationCount (const std::string &operation_name) const
Get the number of times an operation was measured.
std::vector< std::string > GetOperationNames () const
Get all operation names.
void Clear ()
Clear all recorded data.
void PrintSummary () const
Print a summary of all operations.
Static Public Member Functions
static PerformanceMonitor & Get ()
static void SetEnabled (bool enabled)
Enable or disable performance monitoring.
static bool IsEnabled ()
Check if performance monitoring is enabled.
Private Attributes
std::unordered_map< std::string, OperationData > operations_
bool enabled_ = true
Detailed Description
Simple performance monitoring for ROM loading and rendering operations.
This class provides timing and performance tracking for various operations to help identify bottlenecks and optimize loading times.
Definition at line 19 of file performance_monitor.h.
Member Function Documentation
Get()
static PerformanceMonitor & yaze::core::PerformanceMonitor::Get () inline static
Definition at line 21 of file performance_monitor.h.
Referenced by IsEnabled(), yaze::editor::EditorManager::LoadAssets(), yaze::core::ScopedTimer::ScopedTimer(), SetEnabled(), and yaze::core::ScopedTimer::~ScopedTimer().
SetEnabled()
static void yaze::core::PerformanceMonitor::SetEnabled (bool enabled) inline static
Enable or disable performance monitoring.
When disabled, ScopedTimer operations become no-ops for better performance in production builds or when monitoring is not needed.
Definition at line 32 of file performance_monitor.h.
References enabled_, and Get().
IsEnabled()
static bool yaze::core::PerformanceMonitor::IsEnabled () inline static
Check if performance monitoring is enabled.
Definition at line 39 of file performance_monitor.h.
References enabled_, and Get().
StartTimer()
void yaze::core::PerformanceMonitor::StartTimer (const std::string & operation_name)
Start timing an operation.
Definition at line 11 of file performance_monitor.cc.
References operations_.
Referenced by yaze::core::ScopedTimer::ScopedTimer().
EndTimer()
void yaze::core::PerformanceMonitor::EndTimer (const std::string & operation_name)
End timing an operation and record the duration.
Definition at line 15 of file performance_monitor.cc.
References operations_.
Referenced by yaze::core::ScopedTimer::~ScopedTimer().
GetAverageTime()
double yaze::core::PerformanceMonitor::GetAverageTime (const std::string & operation_name) const
Get the average time for an operation in milliseconds.
Definition at line 31 of file performance_monitor.cc.
References operations_.
GetTotalTime()
double yaze::core::PerformanceMonitor::GetTotalTime (const std::string & operation_name) const
Get the total time for an operation in milliseconds.
Definition at line 39 of file performance_monitor.cc.
References operations_.
GetOperationCount()
int yaze::core::PerformanceMonitor::GetOperationCount (const std::string & operation_name) const
Get the number of times an operation was measured.
Definition at line 47 of file performance_monitor.cc.
References operations_.
GetOperationNames()
std::vector< std::string > yaze::core::PerformanceMonitor::GetOperationNames () const
Get all operation names.
Definition at line 55 of file performance_monitor.cc.
References operations_.
Clear()
void yaze::core::PerformanceMonitor::Clear ()
Clear all recorded data.
Definition at line 64 of file performance_monitor.cc.
References operations_.
PrintSummary()
void yaze::core::PerformanceMonitor::PrintSummary () const
Print a summary of all operations.
Definition at line 68 of file performance_monitor.cc.
References operations_.
Referenced by yaze::editor::EditorManager::LoadAssets().
Member Data Documentation
operations_
std::unordered_map<std::string, OperationData> yaze::core::PerformanceMonitor::operations_ private
Definition at line 91 of file performance_monitor.h.
Referenced by Clear(), EndTimer(), GetAverageTime(), GetOperationCount(), GetOperationNames(), GetTotalTime(), PrintSummary(), and StartTimer().
enabled_
bool yaze::core::PerformanceMonitor::enabled_ = true private
Definition at line 92 of file performance_monitor.h.
Referenced by IsEnabled(), and SetEnabled().
The documentation for this class was generated from the following files:
src/app/core/performance_monitor.h
src/app/core/performance_monitor.cc