yaze: yaze::editor::FileDialogWrapper Class Reference
yaze::editor::FileDialogWrapper Class Reference
#include <file_dialog.h>
Static Public Member Functions
static std::string ShowOpenFileDialog ()
ShowOpenFileDialog opens a file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
static std::string ShowOpenFolderDialog ()
ShowOpenFolderDialog opens a file dialog and returns the selected folder path. Uses global feature flag to choose implementation.
static std::string ShowOpenFileDialogNFD ()
static std::string ShowOpenFileDialogBespoke ()
static std::string ShowOpenFolderDialogNFD ()
static std::string ShowOpenFolderDialogBespoke ()
static std::vector< std::string > GetSubdirectoriesInFolder (const std::string &folder_path)
static std::vector< std::string > GetFilesInFolder (const std::string &folder_path)
Detailed Description
Definition at line 10 of file file_dialog.h.
Member Function Documentation
ShowOpenFileDialog()
static std::string yaze::core::FileDialogWrapper::ShowOpenFileDialog () static
ShowOpenFileDialog opens a file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
Referenced by yaze::editor::EditorManager::DrawMenuBar(), and yaze::editor::EditorManager::LoadRom().
ShowOpenFolderDialog()
static std::string yaze::core::FileDialogWrapper::ShowOpenFolderDialog () static
ShowOpenFolderDialog opens a file dialog and returns the selected folder path. Uses global feature flag to choose implementation.
Referenced by yaze::editor::EditorManager::DrawMenuBar(), and yaze::editor::AssemblyEditor::UpdateCodeView().
ShowOpenFileDialogNFD()
static std::string yaze::core::FileDialogWrapper::ShowOpenFileDialogNFD () static
ShowOpenFileDialogBespoke()
static std::string yaze::core::FileDialogWrapper::ShowOpenFileDialogBespoke () static
ShowOpenFolderDialogNFD()
static std::string yaze::core::FileDialogWrapper::ShowOpenFolderDialogNFD () static
ShowOpenFolderDialogBespoke()
static std::string yaze::core::FileDialogWrapper::ShowOpenFolderDialogBespoke () static
GetSubdirectoriesInFolder()
static std::vector< std::string > yaze::core::FileDialogWrapper::GetSubdirectoriesInFolder (const std::string & folder_path) static
Referenced by yaze::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
GetFilesInFolder()
static std::vector< std::string > yaze::core::FileDialogWrapper::GetFilesInFolder (const std::string & folder_path) static
Referenced by yaze::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
The documentation for this class was generated from the following file:
src/app/core/platform/file_dialog.h