yaze: yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest Class Reference
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void CreateTestFiles ()
void CleanupTestFiles ()
Protected Attributes
std::unique_ptr< AsarWrapper > wrapper_
std::filesystem::path test_dir_
std::filesystem::path test_asm_path_
std::filesystem::path invalid_asm_path_
std::vector< uint8_t > test_rom_
Detailed Description
Definition at line 14 of file asar_wrapper_test.cc.
Member Function Documentation
SetUp()
void yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::SetUp () inline override protected
Definition at line 16 of file asar_wrapper_test.cc.
References CreateTestFiles(), and wrapper_.
TearDown()
void yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::TearDown () inline override protected
Definition at line 21 of file asar_wrapper_test.cc.
References CleanupTestFiles().
CreateTestFiles()
void yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::CreateTestFiles () inline protected
Definition at line 25 of file asar_wrapper_test.cc.
References test_asm_path_, and test_dir_.
Referenced by SetUp().
CleanupTestFiles()
void yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::CleanupTestFiles () inline protected
Definition at line 46 of file asar_wrapper_test.cc.
References invalid_asm_path_, and test_dir_.
Referenced by TearDown().
Member Data Documentation
wrapper_
std::unique_ptr<AsarWrapper> yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::wrapper_ protected
Definition at line 56 of file asar_wrapper_test.cc.
Referenced by SetUp().
test_dir_
std::filesystem::path yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::test_dir_ protected
Definition at line 57 of file asar_wrapper_test.cc.
Referenced by CleanupTestFiles(), and CreateTestFiles().
test_asm_path_
std::filesystem::path yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::test_asm_path_ protected
Definition at line 58 of file asar_wrapper_test.cc.
Referenced by CreateTestFiles().
invalid_asm_path_
std::filesystem::path yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::invalid_asm_path_ protected
Definition at line 59 of file asar_wrapper_test.cc.
Referenced by CleanupTestFiles().
test_rom_
std::vector<uint8_t> yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::AsarWrapperTest::test_rom_ protected
Definition at line 60 of file asar_wrapper_test.cc.
The documentation for this class was generated from the following file:
test/core/asar_wrapper_test.cc