yaze: yaze_test::emu_test::CpuTest Class Reference
yaze_test::emu_test::CpuTest Class Reference
Public Member Functions
void SetUp () override
Public Attributes
AsmParser asm_parser
MockMemory mock_memory
MockClock mock_clock
Cpu cpu {mock_memory, mock_clock}
Detailed Description
Test
Test fixture for CPU unit tests
Member Function Documentation
SetUp()
void yaze_test::emu_test::CpuTest::SetUp () inline override
References asm_parser, yaze::app::emu::memory::Memory::ClearMemory(), yaze::app::emu::AsmParser::CreateInternalOpcodeMap(), yaze::app::emu::memory::MockMemory::Init(), and mock_memory.
Member Data Documentation
asm_parser
AsmParser yaze_test::emu_test::CpuTest::asm_parser
Referenced by SetUp().
mock_memory
MockMemory yaze_test::emu_test::CpuTest::mock_memory
Referenced by SetUp().
mock_clock
MockClock yaze_test::emu_test::CpuTest::mock_clock
cpu
Cpu yaze_test::emu_test::CpuTest::cpu {mock_memory, mock_clock}
The documentation for this class was generated from the following file:
test/emu/cpu_test.cc