yaze: yaze::app::core::Logger Class Reference
yaze::app::core::Logger Class Reference
#include <common.h>
Static Public Member Functions
static void log (std::string message)
Member Function Documentation
log()
static void yaze::app::core::Logger::log (std::string message) inline static
Referenced by yaze::app::zelda3::overworld::Overworld::SaveEntrances(), yaze::app::zelda3::overworld::Overworld::SaveExits(), yaze::app::zelda3::overworld::Overworld::SaveLargeMaps(), yaze::app::zelda3::overworld::Overworld::SaveMap16Tiles(), yaze::app::zelda3::overworld::Overworld::SaveMap32Tiles(), yaze::app::zelda3::overworld::Overworld::SaveMapProperties(), yaze::app::zelda3::overworld::Overworld::SaveOverworldMaps(), yaze::app::Rom::WriteByte(), yaze::app::Rom::WriteColor(), yaze::app::Rom::WriteLong(), yaze::app::Rom::WriteShort(), yaze::app::Rom::WriteVector(), and yaze::app::Rom::WriteWord().
The documentation for this class was generated from the following file:
src/app/core/common.h