yaze: yaze::test::ObjectParserTest Class Reference
yaze::test::ObjectParserTest Class Reference
Protected Member Functions
void SetUp () override
void SetupMockData ()
void SetupSubtypeTable (std::vector< uint8_t > &data, int base_addr, int count)
void SetupTileData (std::vector< uint8_t > &data, int base_addr, int size)
Protected Attributes
std::unique_ptr< MockRom > mock_rom_
std::unique_ptr< zelda3::ObjectParser > parser_
Detailed Description
Definition at line 13 of file object_parser_test.cc.
Member Function Documentation
SetUp()
void yaze::test::ObjectParserTest::SetUp () inline override protected
Definition at line 15 of file object_parser_test.cc.
References mock_rom_, parser_, and SetupMockData().
SetupMockData()
void yaze::test::ObjectParserTest::SetupMockData () inline protected
Definition at line 21 of file object_parser_test.cc.
References mock_rom_, yaze::test::MockRom::SetTestData(), SetupSubtypeTable(), and SetupTileData().
Referenced by SetUp().
SetupSubtypeTable()
void yaze::test::ObjectParserTest::SetupSubtypeTable (std::vector< uint8_t > & data, int base_addr, int count) inline protected
Definition at line 35 of file object_parser_test.cc.
Referenced by SetupMockData().
SetupTileData()
void yaze::test::ObjectParserTest::SetupTileData (std::vector< uint8_t > & data, int base_addr, int size) inline protected
Definition at line 47 of file object_parser_test.cc.
Referenced by SetupMockData().
Member Data Documentation
mock_rom_
std::unique_ptr<MockRom> yaze::test::ObjectParserTest::mock_rom_ protected
Definition at line 59 of file object_parser_test.cc.
Referenced by SetUp(), and SetupMockData().
parser_
std::unique_ptr<zelda3::ObjectParser> yaze::test::ObjectParserTest::parser_ protected
Definition at line 60 of file object_parser_test.cc.
Referenced by SetUp().
The documentation for this class was generated from the following file:
test/zelda3/object_parser_test.cc