yaze: yaze::editor::Tile16Editor Class Reference
yaze::editor::Tile16Editor Class Reference
Popup window to edit Tile16 data.
#include <tile16_editor.h>
Classes
struct LayoutScratch
struct UndoState
Public Member Functions
Tile16Editor (Rom *rom, gfx::Tilemap *tile16_blockset)
absl::Status Initialize (const gfx::Bitmap &tile16_blockset_bmp, const gfx::Bitmap &current_gfx_bmp, std::array< uint8_t, 0x200 > &all_tiles_types)
absl::Status Update ()
void DrawTile16Editor ()
absl::Status UpdateBlockset ()
void DrawScratchSpace ()
absl::Status SaveLayoutToScratch (int slot)
absl::Status LoadLayoutFromScratch (int slot)
absl::Status DrawToCurrentTile16 (ImVec2 pos, const gfx::Bitmap *source_tile=nullptr)
absl::Status UpdateTile16Edit ()
absl::Status LoadTile8 ()
absl::Status SetCurrentTile (int id)
absl::Status CopyTile16ToClipboard (int tile_id)
absl::Status PasteTile16FromClipboard ()
absl::Status SaveTile16ToScratchSpace (int slot)
absl::Status LoadTile16FromScratchSpace (int slot)
absl::Status ClearScratchSpace (int slot)
absl::Status FlipTile16Horizontal ()
absl::Status FlipTile16Vertical ()
absl::Status RotateTile16 ()
absl::Status FillTile16WithTile8 (int tile8_id)
absl::Status AutoTileTile16 ()
absl::Status ClearTile16 ()
absl::Status CyclePalette (bool forward=true)
absl::Status ApplyPaletteToAll (uint8_t palette_id)
absl::Status PreviewPaletteChange (uint8_t palette_id)
absl::Status ApplyToSelection (const std::function< void(int)> &operation)
absl::Status BatchEdit (const std::vector< int > &tile_ids, const std::function< void(int)> &operation)
absl::Status Undo ()
absl::Status Redo ()
void SaveUndoState ()
void EnableLivePreview (bool enable)
absl::Status UpdateLivePreview ()
absl::Status ValidateTile16Data ()
bool IsTile16Valid (int tile_id) const
absl::Status SaveTile16ToROM ()
absl::Status UpdateOverworldTilemap ()
absl::Status CommitChangesToBlockset ()
absl::Status CommitChangesToOverworld ()
absl::Status DiscardChanges ()
absl::Status UpdateTile8Palette (int tile8_id)
absl::Status RefreshAllPalettes ()
void DrawPaletteSettings ()
absl::Status UpdateROMTile16Data ()
absl::Status RefreshTile16Blockset ()
gfx::Tile16 * GetCurrentTile16Data ()
absl::Status RegenerateTile16BitmapFromROM ()
absl::Status UpdateBlocksetBitmap ()
void DrawManualTile8Inputs ()
void set_rom (Rom *rom)
Rom * rom () const
void set_on_changes_committed (std::function< absl::Status()> callback)
Private Attributes
Rom * rom_ = nullptr
bool map_blockset_loaded_ = false
bool x_flip = false
bool y_flip = false
bool priority_tile = false
int tile_size
int current_tile16_ = 0
int current_tile8_ = 0
uint8_t current_palette_ = 0
gfx::Bitmap clipboard_tile16_
bool clipboard_has_data_ = false
std::array< gfx::Bitmap, 4 > scratch_space_
std::array< bool, 4 > scratch_space_used_ = {false, false, false, false}
std::array< LayoutScratch, 4 > layout_scratch_
std::vector< UndoState > undo_stack_
std::vector< UndoState > redo_stack_
bool live_preview_enabled_ = true
gfx::Bitmap preview_tile16_
bool preview_dirty_ = false
std::vector< int > selected_tiles_
int selection_start_tile_ = -1
bool multi_select_mode_ = false
bool auto_tile_mode_ = false
bool grid_snap_enabled_ = true
bool show_tile_info_ = true
bool show_palette_preview_ = true
bool show_palette_settings_ = false
int current_palette_group_ = 0
uint8_t palette_normalization_mask_ = 0x0F
bool auto_normalize_pixels_ = true
std::chrono::steady_clock::time_point last_edit_time_
bool batch_mode_ = false
util::NotifyValue< uint32_t > notify_tile16
util::NotifyValue< uint8_t > notify_palette
std::array< uint8_t, 0x200 > all_tiles_types_
gui::Canvas blockset_canvas_
gfx::Bitmap tile16_blockset_bmp_
gui::Canvas tile16_edit_canvas_
gfx::Bitmap current_tile16_bmp_
gui::Canvas tile8_source_canvas_
gfx::Bitmap current_gfx_bmp_
gui::Table tile_edit_table_ {"##TileEditTable", 3, ImGuiTableFlags_Borders, ImVec2(0, 0)}
gfx::Tilemap * tile16_blockset_ = nullptr
std::vector< gfx::Bitmap > current_gfx_individual_
PaletteEditor palette_editor_
gfx::SnesPalette palette_
absl::Status status_
std::function< absl::Status()> on_changes_committed_
gfx::Tile16 current_tile16_data_
Static Private Attributes
static constexpr size_t kMaxUndoStates_ = 50
Additional Inherited Members
Static Protected Attributes inherited from yaze::gfx::GfxContext
static std::unordered_map< uint8_t, gfx::Paletteset > palettesets_
Detailed Description
Popup window to edit Tile16 data.
Definition at line 39 of file tile16_editor.h.
Constructor & Destructor Documentation
Tile16Editor()
yaze::editor::Tile16Editor::Tile16Editor (Rom * rom, gfx::Tilemap * tile16_blockset) inline
Definition at line 41 of file tile16_editor.h.
Member Function Documentation
Initialize()
absl::Status yaze::editor::Tile16Editor::Initialize (const gfx::Bitmap & tile16_blockset_bmp, const gfx::Bitmap & current_gfx_bmp, std::array< uint8_t, 0x200 > & all_tiles_types)
Definition at line 27 of file tile16_editor.cc.
References yaze::gui::AddTableColumn(), all_tiles_types_, yaze::gfx::Bitmap::Create(), current_gfx_bmp_, current_tile16_, current_tile16_bmp_, current_tile8_, yaze::gui::Canvas::custom_labels_enabled(), yaze::gfx::Bitmap::depth(), yaze::core::Renderer::Get(), yaze::gfx::Bitmap::height(), yaze::util::HexByte(), yaze::gui::Canvas::InitializeDefaults(), yaze::gui::Canvas::InitializePaletteEditor(), yaze::editor::kTile16PixelCount, yaze::editor::kTile16Size, LoadTile8(), map_blockset_loaded_, yaze::gui::Canvas::mutable_labels(), yaze::gfx::Bitmap::palette(), priority_tile, yaze::core::Renderer::RenderBitmap(), RETURN_IF_ERROR, rom_, yaze::gui::Canvas::SetAutoResize(), SetCurrentTile(), yaze::gfx::Bitmap::SetPalette(), tile16_blockset_, tile16_blockset_bmp_, tile16_edit_canvas_, tile8_source_canvas_, tile_edit_table_, yaze::gfx::Bitmap::vector(), yaze::gfx::Bitmap::width(), x_flip, and y_flip.
Referenced by yaze::editor::OverworldEditor::Load(), and yaze::test::RomDependentTestSuite::RunTile16EditorTest().
Update()
absl::Status yaze::editor::Tile16Editor::Update ()
Definition at line 100 of file tile16_editor.cc.
References ClearScratchSpace(), ClearTile16(), CommitChangesToBlockset(), CopyTile16ToClipboard(), current_gfx_individual_, current_palette_, current_tile16_, current_tile8_, yaze::gui::Canvas::custom_labels_enabled(), CyclePalette(), DrawPaletteSettings(), DrawTile16Editor(), EnableLivePreview(), FillTile16WithTile8(), FlipTile16Horizontal(), FlipTile16Vertical(), live_preview_enabled_, LoadTile16FromScratchSpace(), map_blockset_loaded_, PasteTile16FromClipboard(), Redo(), RETURN_IF_ERROR, RotateTile16(), SaveTile16ToROM(), SaveTile16ToScratchSpace(), scratch_space_used_, status_, tile8_source_canvas_, and Undo().
Referenced by yaze::editor::OverworldEditor::DrawToolset(), and yaze::editor::OverworldEditor::Update().
DrawTile16Editor()
void yaze::editor::Tile16Editor::DrawTile16Editor ()
Definition at line 255 of file tile16_editor.cc.
References status_, UpdateBlockset(), and UpdateTile16Edit().
Referenced by Update().
UpdateBlockset()
absl::Status yaze::editor::Tile16Editor::UpdateBlockset ()
Definition at line 274 of file tile16_editor.cc.
References yaze::gui::BeginChildWithScrollbar(), yaze::gui::BeginPadding(), blockset_canvas_, current_tile16_, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::gui::Canvas::DrawTileSelector(), yaze::gui::EndPadding(), yaze::gui::Canvas::GetGridStep(), yaze::gui::Canvas::GetLastClickPosition(), RETURN_IF_ERROR, SetCurrentTile(), and tile16_blockset_bmp_.
Referenced by DrawTile16Editor().
DrawScratchSpace()
void yaze::editor::Tile16Editor::DrawScratchSpace ()
Definition at line 1806 of file tile16_editor.cc.
References layout_scratch_.
Referenced by UpdateTile16Edit().
SaveLayoutToScratch()
absl::Status yaze::editor::Tile16Editor::SaveLayoutToScratch (int slot)
Definition at line 1825 of file tile16_editor.cc.
References layout_scratch_.
LoadLayoutFromScratch()
absl::Status yaze::editor::Tile16Editor::LoadLayoutFromScratch (int slot)
Definition at line 1837 of file tile16_editor.cc.
References layout_scratch_.
DrawToCurrentTile16()
absl::Status yaze::editor::Tile16Editor::DrawToCurrentTile16 (ImVec2 pos, const gfx::Bitmap * source_tile = nullptr)
Definition at line 503 of file tile16_editor.cc.
References current_gfx_individual_, current_palette_, current_tile16_, current_tile16_bmp_, current_tile8_, yaze::gfx::Bitmap::data(), yaze::core::Renderer::Get(), GetCurrentTile16Data(), yaze::gfx::Bitmap::is_active(), yaze::editor::kTile16Size, yaze::editor::kTile8Size, last_edit_time_, live_preview_enabled_, priority_tile, RETURN_IF_ERROR, SaveUndoState(), yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::size(), yaze::core::Renderer::UpdateBitmap(), UpdateBlocksetBitmap(), UpdateOverworldTilemap(), UpdateROMTile16Data(), yaze::gfx::Bitmap::WriteToPixel(), x_flip, and y_flip.
Referenced by UpdateTile16Edit().
UpdateTile16Edit()
absl::Status yaze::editor::Tile16Editor::UpdateTile16Edit ()
Definition at line 646 of file tile16_editor.cc.
References ClearTile16(), CommitChangesToOverworld(), CopyTile16ToClipboard(), yaze::gfx::Bitmap::Create(), current_gfx_bmp_, current_gfx_individual_, current_palette_, current_palette_group_, current_tile16_, current_tile16_bmp_, current_tile8_, DiscardChanges(), yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), DrawManualTile8Inputs(), yaze::gui::Canvas::drawn_tile_position(), yaze::gui::Canvas::DrawOverlay(), DrawPaletteSettings(), DrawScratchSpace(), yaze::gui::Canvas::DrawTilePainter(), yaze::gui::Canvas::DrawTileSelector(), DrawToCurrentTile16(), yaze::core::Renderer::Get(), yaze::gui::Canvas::GetLastClickPosition(), yaze::gui::Canvas::height(), HOVER_HINT, yaze::gfx::Bitmap::is_active(), yaze::gfx::Bitmap::mutable_data(), PasteTile16FromClipboard(), priority_tile, RefreshAllPalettes(), RefreshTile16Blockset(), yaze::core::Renderer::RenderBitmap(), RETURN_IF_ERROR, yaze::gui::Canvas::set_draggable(), yaze::gfx::Bitmap::SetPalette(), show_palette_settings_, yaze::gfx::Bitmap::texture(), tile16_edit_canvas_, tile8_source_canvas_, Undo(), undo_stack_, UpdateTile8Palette(), yaze::gui::Canvas::WasClicked(), yaze::gui::Canvas::WasDoubleClicked(), yaze::gfx::Bitmap::width(), yaze::gui::Canvas::width(), x_flip, and y_flip.
Referenced by DrawTile16Editor().
LoadTile8()
absl::Status yaze::editor::Tile16Editor::LoadTile8 ()
Definition at line 927 of file tile16_editor.cc.
References auto_normalize_pixels_, current_gfx_bmp_, current_gfx_individual_, yaze::gfx::Bitmap::data(), yaze::gfx::Bitmap::height(), yaze::gfx::Bitmap::is_active(), yaze::Rom::palette_group(), palette_normalization_mask_, RETURN_IF_ERROR, rom(), yaze::gfx::Bitmap::size(), UpdateTile8Palette(), and yaze::gfx::Bitmap::width().
Referenced by DrawPaletteSettings(), and Initialize().
SetCurrentTile()
absl::Status yaze::editor::Tile16Editor::SetCurrentTile (int id)
Definition at line 996 of file tile16_editor.cc.
References yaze::gfx::Tilemap::atlas, auto_normalize_pixels_, yaze::gfx::Bitmap::Create(), current_tile16_, current_tile16_bmp_, current_tile16_data_, yaze::gfx::Bitmap::data(), yaze::core::Renderer::Get(), yaze::gfx::GetTilemapData(), yaze::zelda3::kNumTile16Individual, yaze::editor::kTile16PixelCount, yaze::editor::kTile16Size, yaze::Rom::palette_group(), palette_normalization_mask_, yaze::Rom::ReadTile16(), yaze::core::Renderer::RenderBitmap(), rom(), rom_, yaze::gfx::Bitmap::SetPalette(), yaze::gfx::Bitmap::size(), tile16_blockset_, and yaze::gfx::Bitmap::width().
Referenced by DiscardChanges(), DrawManualTile8Inputs(), yaze::editor::OverworldEditor::DrawTile16Selector(), Initialize(), yaze::test::RomDependentTestSuite::RunTile16EditorTest(), and UpdateBlockset().
CopyTile16ToClipboard()
absl::Status yaze::editor::Tile16Editor::CopyTile16ToClipboard (int tile_id)
Definition at line 1070 of file tile16_editor.cc.
References clipboard_has_data_, clipboard_tile16_, yaze::gfx::Bitmap::Create(), yaze::core::Renderer::Get(), yaze::gfx::TileCache::GetTile(), yaze::zelda3::kNumTile16Individual, yaze::core::Renderer::RenderBitmap(), yaze::gfx::RenderTile(), yaze::gfx::Bitmap::SetPalette(), tile16_blockset_, and yaze::gfx::Tilemap::tile_cache.
Referenced by Update(), and UpdateTile16Edit().
PasteTile16FromClipboard()
absl::Status yaze::editor::Tile16Editor::PasteTile16FromClipboard ()
Definition at line 1088 of file tile16_editor.cc.
References clipboard_has_data_, clipboard_tile16_, yaze::gfx::Bitmap::Create(), current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::gfx::Bitmap::palette(), yaze::core::Renderer::RenderBitmap(), yaze::gfx::Bitmap::SetPalette(), and yaze::gfx::Bitmap::vector().
Referenced by Update(), and UpdateTile16Edit().
SaveTile16ToScratchSpace()
absl::Status yaze::editor::Tile16Editor::SaveTile16ToScratchSpace (int slot)
Definition at line 1101 of file tile16_editor.cc.
References current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::gfx::Bitmap::palette(), yaze::core::Renderer::RenderBitmap(), scratch_space_, scratch_space_used_, and yaze::gfx::Bitmap::vector().
Referenced by Update().
LoadTile16FromScratchSpace()
absl::Status yaze::editor::Tile16Editor::LoadTile16FromScratchSpace (int slot)
Definition at line 1115 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::core::Renderer::RenderBitmap(), scratch_space_, scratch_space_used_, and yaze::gfx::Bitmap::SetPalette().
Referenced by Update().
ClearScratchSpace()
absl::Status yaze::editor::Tile16Editor::ClearScratchSpace (int slot)
Definition at line 1132 of file tile16_editor.cc.
References scratch_space_used_.
Referenced by Update().
FlipTile16Horizontal()
absl::Status yaze::editor::Tile16Editor::FlipTile16Horizontal ()
Definition at line 1142 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_tile16_bmp_, yaze::gfx::Bitmap::data(), yaze::core::Renderer::Get(), yaze::gfx::Bitmap::is_active(), palette_, SaveUndoState(), yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::SetPalette(), yaze::gfx::Bitmap::size(), yaze::core::Renderer::UpdateBitmap(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by Update().
FlipTile16Vertical()
absl::Status yaze::editor::Tile16Editor::FlipTile16Vertical ()
Definition at line 1175 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_tile16_bmp_, yaze::gfx::Bitmap::data(), yaze::core::Renderer::Get(), yaze::gfx::Bitmap::is_active(), palette_, SaveUndoState(), yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::SetPalette(), yaze::gfx::Bitmap::size(), yaze::core::Renderer::UpdateBitmap(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by Update().
RotateTile16()
absl::Status yaze::editor::Tile16Editor::RotateTile16 ()
Definition at line 1208 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_tile16_bmp_, yaze::gfx::Bitmap::data(), yaze::core::Renderer::Get(), yaze::gfx::Bitmap::is_active(), palette_, SaveUndoState(), yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::SetPalette(), yaze::gfx::Bitmap::size(), yaze::core::Renderer::UpdateBitmap(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by Update().
FillTile16WithTile8()
absl::Status yaze::editor::Tile16Editor::FillTile16WithTile8 (int tile8_id)
Definition at line 1241 of file tile16_editor.cc.
References current_gfx_individual_, current_tile16_bmp_, yaze::core::Renderer::Get(), SaveUndoState(), yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::size(), yaze::core::Renderer::UpdateBitmap(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by Update().
AutoTileTile16()
absl::Status yaze::editor::Tile16Editor::AutoTileTile16 ()
ClearTile16()
absl::Status yaze::editor::Tile16Editor::ClearTile16 ()
Definition at line 1278 of file tile16_editor.cc.
References current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::gfx::Bitmap::is_active(), yaze::gfx::Bitmap::mutable_data(), SaveUndoState(), yaze::gfx::Bitmap::set_modified(), and yaze::core::Renderer::UpdateBitmap().
Referenced by Update(), and UpdateTile16Edit().
CyclePalette()
absl::Status yaze::editor::Tile16Editor::CyclePalette (bool forward = true)
Definition at line 1295 of file tile16_editor.cc.
References current_gfx_bmp_, current_gfx_individual_, current_palette_, current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::Rom::palette_group(), rom(), yaze::gfx::Bitmap::SetPaletteWithTransparent(), and yaze::core::Renderer::UpdateBitmap().
Referenced by Update().
ApplyPaletteToAll()
absl::Status yaze::editor::Tile16Editor::ApplyPaletteToAll (uint8_t palette_id)
PreviewPaletteChange()
absl::Status yaze::editor::Tile16Editor::PreviewPaletteChange (uint8_t palette_id)
Definition at line 1330 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::gfx::Bitmap::is_active(), yaze::Rom::palette_group(), preview_dirty_, preview_tile16_, rom(), yaze::gfx::Bitmap::SetPaletteWithTransparent(), show_palette_preview_, yaze::core::Renderer::UpdateBitmap(), and yaze::gfx::Bitmap::vector().
ApplyToSelection()
absl::Status yaze::editor::Tile16Editor::ApplyToSelection (const std::function< void(int)> & operation)
BatchEdit()
absl::Status yaze::editor::Tile16Editor::BatchEdit (const std::vector< int > & tile_ids, const std::function< void(int)> & operation)
Undo()
absl::Status yaze::editor::Tile16Editor::Undo ()
Definition at line 1383 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_palette_, current_tile16_, current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::editor::Tile16Editor::UndoState::palette, yaze::gfx::Bitmap::palette(), yaze::editor::Tile16Editor::UndoState::priority, priority_tile, redo_stack_, yaze::gfx::Bitmap::SetPalette(), yaze::editor::Tile16Editor::UndoState::tile_bitmap, yaze::editor::Tile16Editor::UndoState::tile_id, undo_stack_, yaze::core::Renderer::UpdateBitmap(), yaze::gfx::Bitmap::vector(), x_flip, yaze::editor::Tile16Editor::UndoState::x_flip, y_flip, and yaze::editor::Tile16Editor::UndoState::y_flip.
Referenced by Update(), and UpdateTile16Edit().
Redo()
absl::Status yaze::editor::Tile16Editor::Redo ()
Definition at line 1414 of file tile16_editor.cc.
References current_palette_, current_tile16_, current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::editor::Tile16Editor::UndoState::palette, yaze::editor::Tile16Editor::UndoState::priority, priority_tile, redo_stack_, SaveUndoState(), yaze::editor::Tile16Editor::UndoState::tile_bitmap, yaze::editor::Tile16Editor::UndoState::tile_id, yaze::core::Renderer::UpdateBitmap(), x_flip, yaze::editor::Tile16Editor::UndoState::x_flip, y_flip, and yaze::editor::Tile16Editor::UndoState::y_flip.
Referenced by Update().
SaveUndoState()
void yaze::editor::Tile16Editor::SaveUndoState ()
Definition at line 1358 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_palette_, current_tile16_, current_tile16_bmp_, yaze::gfx::Bitmap::is_active(), kMaxUndoStates_, yaze::editor::Tile16Editor::UndoState::palette, yaze::gfx::Bitmap::palette(), yaze::editor::Tile16Editor::UndoState::priority, priority_tile, redo_stack_, yaze::gfx::Bitmap::SetPalette(), yaze::editor::Tile16Editor::UndoState::tile_bitmap, yaze::editor::Tile16Editor::UndoState::tile_id, undo_stack_, yaze::gfx::Bitmap::vector(), x_flip, yaze::editor::Tile16Editor::UndoState::x_flip, y_flip, and yaze::editor::Tile16Editor::UndoState::y_flip.
Referenced by ClearTile16(), DrawToCurrentTile16(), FillTile16WithTile8(), FlipTile16Horizontal(), FlipTile16Vertical(), Redo(), and RotateTile16().
EnableLivePreview()
void yaze::editor::Tile16Editor::EnableLivePreview (bool enable) inline
Definition at line 96 of file tile16_editor.h.
References live_preview_enabled_.
Referenced by Update().
UpdateLivePreview()
absl::Status yaze::editor::Tile16Editor::UpdateLivePreview ()
ValidateTile16Data()
absl::Status yaze::editor::Tile16Editor::ValidateTile16Data ()
Definition at line 1437 of file tile16_editor.cc.
References yaze::gfx::Tilemap::atlas, current_palette_, current_tile16_, yaze::gfx::Bitmap::size(), and tile16_blockset_.
IsTile16Valid()
bool yaze::editor::Tile16Editor::IsTile16Valid (int tile_id) const
Definition at line 1454 of file tile16_editor.cc.
References yaze::gfx::Tilemap::atlas, yaze::gfx::Bitmap::size(), and tile16_blockset_.
SaveTile16ToROM()
absl::Status yaze::editor::Tile16Editor::SaveTile16ToROM ()
Definition at line 1460 of file tile16_editor.cc.
References CommitChangesToBlockset(), current_tile16_bmp_, yaze::gfx::Bitmap::is_active(), RETURN_IF_ERROR, rom_, and UpdateOverworldTilemap().
Referenced by CommitChangesToOverworld(), DrawManualTile8Inputs(), and Update().
UpdateOverworldTilemap()
absl::Status yaze::editor::Tile16Editor::UpdateOverworldTilemap ()
Definition at line 1479 of file tile16_editor.cc.
References yaze::gfx::Tilemap::atlas, yaze::gfx::TileCache::CacheTile(), current_tile16_, current_tile16_bmp_, yaze::gfx::Bitmap::data(), yaze::core::Renderer::Get(), yaze::gfx::Bitmap::is_active(), yaze::zelda3::kNumTile16Individual, yaze::editor::kTile16Size, yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::size(), tile16_blockset_, yaze::gfx::Tilemap::tile_cache, yaze::core::Renderer::UpdateBitmap(), yaze::gfx::Bitmap::width(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by CommitChangesToOverworld(), DrawToCurrentTile16(), and SaveTile16ToROM().
CommitChangesToBlockset()
absl::Status yaze::editor::Tile16Editor::CommitChangesToBlockset ()
Definition at line 1523 of file tile16_editor.cc.
References yaze::gfx::Tilemap::atlas, yaze::core::Renderer::Get(), yaze::gfx::Bitmap::modified(), tile16_blockset_, and yaze::core::Renderer::UpdateBitmap().
Referenced by SaveTile16ToROM(), and Update().
CommitChangesToOverworld()
absl::Status yaze::editor::Tile16Editor::CommitChangesToOverworld ()
Definition at line 1541 of file tile16_editor.cc.
References on_changes_committed_, RefreshTile16Blockset(), RETURN_IF_ERROR, SaveTile16ToROM(), and UpdateOverworldTilemap().
Referenced by UpdateTile16Edit().
DiscardChanges()
absl::Status yaze::editor::Tile16Editor::DiscardChanges ()
Definition at line 1560 of file tile16_editor.cc.
References current_tile16_, RETURN_IF_ERROR, and SetCurrentTile().
Referenced by UpdateTile16Edit().
UpdateTile8Palette()
absl::Status yaze::editor::Tile16Editor::UpdateTile8Palette (int tile8_id)
Definition at line 1569 of file tile16_editor.cc.
References current_gfx_bmp_, current_gfx_individual_, current_palette_, current_palette_group_, yaze::core::Renderer::Get(), yaze::Rom::palette_group(), rom(), yaze::core::Renderer::UpdateBitmap(), and yaze::gfx::Bitmap::width().
Referenced by LoadTile8(), RefreshAllPalettes(), and UpdateTile16Edit().
RefreshAllPalettes()
absl::Status yaze::editor::Tile16Editor::RefreshAllPalettes ()
Definition at line 1629 of file tile16_editor.cc.
References current_gfx_bmp_, current_gfx_individual_, current_palette_, current_tile16_bmp_, yaze::core::Renderer::Get(), yaze::Rom::palette_group(), RETURN_IF_ERROR, rom(), yaze::gfx::Bitmap::SetPaletteWithTransparent(), yaze::core::Renderer::UpdateBitmap(), and UpdateTile8Palette().
Referenced by UpdateTile16Edit().
DrawPaletteSettings()
void yaze::editor::Tile16Editor::DrawPaletteSettings ()
Definition at line 1652 of file tile16_editor.cc.
References yaze::gui::Canvas::ApplyROMPalette(), auto_normalize_pixels_, current_gfx_individual_, current_palette_, current_palette_group_, current_tile8_, HOVER_HINT, LoadTile8(), palette_normalization_mask_, rom_, show_palette_settings_, yaze::gui::Canvas::ShowColorAnalysis(), yaze::gui::Canvas::ShowPaletteEditor(), tile16_edit_canvas_, and tile8_source_canvas_.
Referenced by Update(), and UpdateTile16Edit().
UpdateROMTile16Data()
absl::Status yaze::editor::Tile16Editor::UpdateROMTile16Data ()
Definition at line 321 of file tile16_editor.cc.
References current_tile16_, GetCurrentTile16Data(), RETURN_IF_ERROR, rom_, and yaze::Rom::WriteTile16().
Referenced by DrawManualTile8Inputs(), and DrawToCurrentTile16().
RefreshTile16Blockset()
absl::Status yaze::editor::Tile16Editor::RefreshTile16Blockset ()
Definition at line 334 of file tile16_editor.cc.
References yaze::gfx::Tilemap::atlas, yaze::gfx::TileCache::Clear(), yaze::core::Renderer::Get(), yaze::gfx::Bitmap::set_modified(), tile16_blockset_, yaze::gfx::Tilemap::tile_cache, and yaze::core::Renderer::UpdateBitmap().
Referenced by CommitChangesToOverworld(), and UpdateTile16Edit().
GetCurrentTile16Data()
gfx::Tile16 * yaze::editor::Tile16Editor::GetCurrentTile16Data ()
Definition at line 305 of file tile16_editor.cc.
References current_tile16_, current_tile16_data_, yaze::Rom::ReadTile16(), and rom_.
Referenced by DrawManualTile8Inputs(), DrawToCurrentTile16(), RegenerateTile16BitmapFromROM(), and UpdateROMTile16Data().
RegenerateTile16BitmapFromROM()
absl::Status yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM ()
Definition at line 412 of file tile16_editor.cc.
References yaze::gfx::Bitmap::Create(), current_gfx_individual_, current_tile16_, current_tile16_bmp_, yaze::core::Renderer::Get(), GetCurrentTile16Data(), yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::editor::kTile16PixelCount, yaze::editor::kTile16Size, yaze::editor::kTile8Size, yaze::gfx::TileInfo::palette_, yaze::Rom::palette_group(), yaze::core::Renderer::RenderBitmap(), rom(), yaze::gfx::Bitmap::SetPalette(), yaze::gfx::TileInfo::vertical_mirror_, x_flip, and y_flip.
UpdateBlocksetBitmap()
absl::Status yaze::editor::Tile16Editor::UpdateBlocksetBitmap ()
Definition at line 355 of file tile16_editor.cc.
References current_tile16_, current_tile16_bmp_, yaze::gfx::Bitmap::data(), yaze::core::Renderer::Get(), yaze::gfx::Bitmap::height(), yaze::gfx::Bitmap::is_active(), yaze::zelda3::kNumTile16Individual, yaze::editor::kTile16Size, yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::size(), tile16_blockset_, tile16_blockset_bmp_, yaze::core::Renderer::UpdateBitmap(), yaze::gfx::Bitmap::width(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by DrawToCurrentTile16().
DrawManualTile8Inputs()
void yaze::editor::Tile16Editor::DrawManualTile8Inputs ()
Definition at line 1850 of file tile16_editor.cc.
References current_tile16_, GetCurrentTile16Data(), yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::gfx::TileInfo::over_, yaze::gfx::TileInfo::palette_, rom_, SaveTile16ToROM(), SetCurrentTile(), UpdateROMTile16Data(), and yaze::gfx::TileInfo::vertical_mirror_.
Referenced by UpdateTile16Edit().
set_rom()
void yaze::editor::Tile16Editor::set_rom (Rom * rom) inline
Definition at line 125 of file tile16_editor.h.
References rom(), and rom_.
rom()
Rom * yaze::editor::Tile16Editor::rom () const inline
Definition at line 126 of file tile16_editor.h.
References rom_.
Referenced by CyclePalette(), LoadTile8(), PreviewPaletteChange(), RefreshAllPalettes(), RegenerateTile16BitmapFromROM(), set_rom(), SetCurrentTile(), and UpdateTile8Palette().
set_on_changes_committed()
void yaze::editor::Tile16Editor::set_on_changes_committed (std::function< absl::Status()> callback) inline
Definition at line 129 of file tile16_editor.h.
References on_changes_committed_.
Referenced by yaze::editor::OverworldEditor::Load().
Member Data Documentation
rom_
Rom* yaze::editor::Tile16Editor::rom_ = nullptr private
Definition at line 134 of file tile16_editor.h.
Referenced by DrawManualTile8Inputs(), DrawPaletteSettings(), GetCurrentTile16Data(), Initialize(), rom(), SaveTile16ToROM(), set_rom(), SetCurrentTile(), and UpdateROMTile16Data().
map_blockset_loaded_
bool yaze::editor::Tile16Editor::map_blockset_loaded_ = false private
Definition at line 135 of file tile16_editor.h.
Referenced by Initialize(), and Update().
x_flip
bool yaze::editor::Tile16Editor::x_flip = false private
Definition at line 136 of file tile16_editor.h.
Referenced by DrawToCurrentTile16(), Initialize(), Redo(), RegenerateTile16BitmapFromROM(), SaveUndoState(), Undo(), and UpdateTile16Edit().
y_flip
bool yaze::editor::Tile16Editor::y_flip = false private
Definition at line 137 of file tile16_editor.h.
Referenced by DrawToCurrentTile16(), Initialize(), Redo(), RegenerateTile16BitmapFromROM(), SaveUndoState(), Undo(), and UpdateTile16Edit().
priority_tile
bool yaze::editor::Tile16Editor::priority_tile = false private
Definition at line 138 of file tile16_editor.h.
Referenced by DrawToCurrentTile16(), Initialize(), Redo(), SaveUndoState(), Undo(), and UpdateTile16Edit().
tile_size
int yaze::editor::Tile16Editor::tile_size private
Definition at line 140 of file tile16_editor.h.
current_tile16_
int yaze::editor::Tile16Editor::current_tile16_ = 0 private
Definition at line 141 of file tile16_editor.h.
Referenced by DiscardChanges(), DrawManualTile8Inputs(), DrawToCurrentTile16(), GetCurrentTile16Data(), Initialize(), Redo(), RegenerateTile16BitmapFromROM(), SaveUndoState(), SetCurrentTile(), Undo(), Update(), UpdateBlockset(), UpdateBlocksetBitmap(), UpdateOverworldTilemap(), UpdateROMTile16Data(), UpdateTile16Edit(), and ValidateTile16Data().
current_tile8_
int yaze::editor::Tile16Editor::current_tile8_ = 0 private
Definition at line 142 of file tile16_editor.h.
Referenced by DrawPaletteSettings(), DrawToCurrentTile16(), Initialize(), Update(), and UpdateTile16Edit().
current_palette_
uint8_t yaze::editor::Tile16Editor::current_palette_ = 0 private
Definition at line 143 of file tile16_editor.h.
Referenced by CyclePalette(), DrawPaletteSettings(), DrawToCurrentTile16(), Redo(), RefreshAllPalettes(), SaveUndoState(), Undo(), Update(), UpdateTile16Edit(), UpdateTile8Palette(), and ValidateTile16Data().
clipboard_tile16_
gfx::Bitmap yaze::editor::Tile16Editor::clipboard_tile16_ private
Definition at line 146 of file tile16_editor.h.
Referenced by CopyTile16ToClipboard(), and PasteTile16FromClipboard().
clipboard_has_data_
bool yaze::editor::Tile16Editor::clipboard_has_data_ = false private
Definition at line 147 of file tile16_editor.h.
Referenced by CopyTile16ToClipboard(), and PasteTile16FromClipboard().
scratch_space_
std::array<gfx::Bitmap, 4> yaze::editor::Tile16Editor::scratch_space_ private
Definition at line 150 of file tile16_editor.h.
Referenced by LoadTile16FromScratchSpace(), and SaveTile16ToScratchSpace().
scratch_space_used_
std::array<bool, 4> yaze::editor::Tile16Editor::scratch_space_used_ = {false, false, false, false} private
Definition at line 151 of file tile16_editor.h.
Referenced by ClearScratchSpace(), LoadTile16FromScratchSpace(), SaveTile16ToScratchSpace(), and Update().
layout_scratch_
std::array<LayoutScratch, 4> yaze::editor::Tile16Editor::layout_scratch_ private
Definition at line 159 of file tile16_editor.h.
Referenced by DrawScratchSpace(), LoadLayoutFromScratch(), and SaveLayoutToScratch().
undo_stack_
std::vector<UndoState> yaze::editor::Tile16Editor::undo_stack_ private
Definition at line 169 of file tile16_editor.h.
Referenced by SaveUndoState(), Undo(), and UpdateTile16Edit().
redo_stack_
std::vector<UndoState> yaze::editor::Tile16Editor::redo_stack_ private
Definition at line 170 of file tile16_editor.h.
Referenced by Redo(), SaveUndoState(), and Undo().
kMaxUndoStates_
constexpr size_t yaze::editor::Tile16Editor::kMaxUndoStates_ = 50 static constexpr private
Definition at line 171 of file tile16_editor.h.
Referenced by SaveUndoState().
live_preview_enabled_
bool yaze::editor::Tile16Editor::live_preview_enabled_ = true private
Definition at line 174 of file tile16_editor.h.
Referenced by DrawToCurrentTile16(), EnableLivePreview(), and Update().
preview_tile16_
gfx::Bitmap yaze::editor::Tile16Editor::preview_tile16_ private
Definition at line 175 of file tile16_editor.h.
Referenced by PreviewPaletteChange().
preview_dirty_
bool yaze::editor::Tile16Editor::preview_dirty_ = false private
Definition at line 176 of file tile16_editor.h.
Referenced by PreviewPaletteChange().
selected_tiles_
std::vector<int> yaze::editor::Tile16Editor::selected_tiles_ private
Definition at line 179 of file tile16_editor.h.
selection_start_tile_
int yaze::editor::Tile16Editor::selection_start_tile_ = -1 private
Definition at line 180 of file tile16_editor.h.
multi_select_mode_
bool yaze::editor::Tile16Editor::multi_select_mode_ = false private
Definition at line 181 of file tile16_editor.h.
auto_tile_mode_
bool yaze::editor::Tile16Editor::auto_tile_mode_ = false private
Definition at line 184 of file tile16_editor.h.
grid_snap_enabled_
bool yaze::editor::Tile16Editor::grid_snap_enabled_ = true private
Definition at line 185 of file tile16_editor.h.
show_tile_info_
bool yaze::editor::Tile16Editor::show_tile_info_ = true private
Definition at line 186 of file tile16_editor.h.
show_palette_preview_
bool yaze::editor::Tile16Editor::show_palette_preview_ = true private
Definition at line 187 of file tile16_editor.h.
Referenced by PreviewPaletteChange().
show_palette_settings_
bool yaze::editor::Tile16Editor::show_palette_settings_ = false private
Definition at line 190 of file tile16_editor.h.
Referenced by DrawPaletteSettings(), and UpdateTile16Edit().
current_palette_group_
int yaze::editor::Tile16Editor::current_palette_group_ = 0 private
Definition at line 191 of file tile16_editor.h.
Referenced by DrawPaletteSettings(), UpdateTile16Edit(), and UpdateTile8Palette().
palette_normalization_mask_
uint8_t yaze::editor::Tile16Editor::palette_normalization_mask_ = 0x0F private
Definition at line 192 of file tile16_editor.h.
Referenced by DrawPaletteSettings(), LoadTile8(), and SetCurrentTile().
auto_normalize_pixels_
bool yaze::editor::Tile16Editor::auto_normalize_pixels_ = true private
Definition at line 193 of file tile16_editor.h.
Referenced by DrawPaletteSettings(), LoadTile8(), and SetCurrentTile().
last_edit_time_
std::chrono::steady_clock::time_point yaze::editor::Tile16Editor::last_edit_time_ private
Definition at line 196 of file tile16_editor.h.
Referenced by DrawToCurrentTile16().
batch_mode_
bool yaze::editor::Tile16Editor::batch_mode_ = false private
Definition at line 197 of file tile16_editor.h.
notify_tile16
util::NotifyValue<uint32_t> yaze::editor::Tile16Editor::notify_tile16 private
Definition at line 199 of file tile16_editor.h.
notify_palette
util::NotifyValue<uint8_t> yaze::editor::Tile16Editor::notify_palette private
Definition at line 200 of file tile16_editor.h.
all_tiles_types_
std::array<uint8_t, 0x200> yaze::editor::Tile16Editor::all_tiles_types_ private
Definition at line 202 of file tile16_editor.h.
Referenced by Initialize().
blockset_canvas_
gui::Canvas yaze::editor::Tile16Editor::blockset_canvas_ private
Initial value:
{
      "blocksetCanvas", ImVec2(kTilesheetEditorWidth, kTilesheetEditorHeight),
      gui::CanvasGridSize::k32x32}
Definition at line 205 of file tile16_editor.h.
Referenced by UpdateBlockset().
tile16_blockset_bmp_
gfx::Bitmap yaze::editor::Tile16Editor::tile16_blockset_bmp_ private
Definition at line 208 of file tile16_editor.h.
Referenced by Initialize(), UpdateBlockset(), and UpdateBlocksetBitmap().
tile16_edit_canvas_
gui::Canvas yaze::editor::Tile16Editor::tile16_edit_canvas_ private
Initial value:
{"Tile16EditCanvas",
                                  ImVec2(64, 64),
                                  gui::CanvasGridSize::k8x8, 4.0F}
Definition at line 211 of file tile16_editor.h.
Referenced by DrawPaletteSettings(), Initialize(), and UpdateTile16Edit().
current_tile16_bmp_
gfx::Bitmap yaze::editor::Tile16Editor::current_tile16_bmp_ private
Definition at line 214 of file tile16_editor.h.
Referenced by ClearTile16(), CyclePalette(), DrawToCurrentTile16(), FillTile16WithTile8(), FlipTile16Horizontal(), FlipTile16Vertical(), Initialize(), LoadTile16FromScratchSpace(), PasteTile16FromClipboard(), PreviewPaletteChange(), Redo(), RefreshAllPalettes(), RegenerateTile16BitmapFromROM(), RotateTile16(), SaveTile16ToROM(), SaveTile16ToScratchSpace(), SaveUndoState(), SetCurrentTile(), Undo(), UpdateBlocksetBitmap(), UpdateOverworldTilemap(), and UpdateTile16Edit().
tile8_source_canvas_
gui::Canvas yaze::editor::Tile16Editor::tile8_source_canvas_ private
Initial value:
{
      "Tile8SourceCanvas",
      ImVec2(gfx::kTilesheetWidth * 4, gfx::kTilesheetHeight * 0x10 * 4),
      gui::CanvasGridSize::k32x32}
Definition at line 217 of file tile16_editor.h.
Referenced by DrawPaletteSettings(), Initialize(), Update(), and UpdateTile16Edit().
current_gfx_bmp_
gfx::Bitmap yaze::editor::Tile16Editor::current_gfx_bmp_ private
Definition at line 221 of file tile16_editor.h.
Referenced by CyclePalette(), Initialize(), LoadTile8(), RefreshAllPalettes(), UpdateTile16Edit(), and UpdateTile8Palette().
tile_edit_table_
gui::Table yaze::editor::Tile16Editor::tile_edit_table_ {"##TileEditTable", 3, ImGuiTableFlags_Borders, ImVec2(0, 0)} private
Definition at line 223 of file tile16_editor.h.
Referenced by Initialize().
tile16_blockset_
gfx::Tilemap* yaze::editor::Tile16Editor::tile16_blockset_ = nullptr private
Definition at line 225 of file tile16_editor.h.
Referenced by CommitChangesToBlockset(), CopyTile16ToClipboard(), Initialize(), IsTile16Valid(), RefreshTile16Blockset(), SetCurrentTile(), UpdateBlocksetBitmap(), UpdateOverworldTilemap(), and ValidateTile16Data().
current_gfx_individual_
std::vector<gfx::Bitmap> yaze::editor::Tile16Editor::current_gfx_individual_ private
Definition at line 226 of file tile16_editor.h.
Referenced by CyclePalette(), DrawPaletteSettings(), DrawToCurrentTile16(), FillTile16WithTile8(), LoadTile8(), RefreshAllPalettes(), RegenerateTile16BitmapFromROM(), Update(), UpdateTile16Edit(), and UpdateTile8Palette().
palette_editor_
PaletteEditor yaze::editor::Tile16Editor::palette_editor_ private
Definition at line 228 of file tile16_editor.h.
palette_
gfx::SnesPalette yaze::editor::Tile16Editor::palette_ private
Definition at line 229 of file tile16_editor.h.
Referenced by FlipTile16Horizontal(), FlipTile16Vertical(), and RotateTile16().
status_
absl::Status yaze::editor::Tile16Editor::status_ private
Definition at line 231 of file tile16_editor.h.
Referenced by DrawTile16Editor(), and Update().
on_changes_committed_
std::function<absl::Status()> yaze::editor::Tile16Editor::on_changes_committed_ private
Definition at line 234 of file tile16_editor.h.
Referenced by CommitChangesToOverworld(), and set_on_changes_committed().
current_tile16_data_
gfx::Tile16 yaze::editor::Tile16Editor::current_tile16_data_ private
Definition at line 237 of file tile16_editor.h.
Referenced by GetCurrentTile16Data(), and SetCurrentTile().
The documentation for this class was generated from the following files:
src/app/editor/overworld/tile16_editor.h
src/app/editor/overworld/tile16_editor.cc