yaze: yaze::zelda3::DungeonObjectRendererMockTest Class Reference
yaze::zelda3::DungeonObjectRendererMockTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
absl::Status GenerateMockRoomData ()
RoomObject CreateMockObject (int object_id, int x, int y, int size=0x12, int layer=0)
std::vector< RoomObject > CreateMockObjectSet ()
Protected Attributes
std::unique_ptr< MockRom > mock_rom_
std::unique_ptr< DungeonEditorSystem > dungeon_editor_system_
std::shared_ptr< DungeonObjectEditor > object_editor_
std::unique_ptr< ObjectRenderer > object_renderer_
std::map< int, Room > rooms_
std::vector< gfx::SnesPalette > test_palettes_
Detailed Description
Definition at line 191 of file dungeon_object_renderer_mock_test.cc.
Member Function Documentation
SetUp()
void yaze::zelda3::DungeonObjectRendererMockTest::SetUp () inline override protected
Definition at line 193 of file dungeon_object_renderer_mock_test.cc.
References dungeon_editor_system_, GenerateMockRoomData(), mock_rom_, object_editor_, and object_renderer_.
TearDown()
void yaze::zelda3::DungeonObjectRendererMockTest::TearDown () inline override protected
Definition at line 212 of file dungeon_object_renderer_mock_test.cc.
References dungeon_editor_system_, mock_rom_, object_editor_, and object_renderer_.
GenerateMockRoomData()
absl::Status yaze::zelda3::DungeonObjectRendererMockTest::GenerateMockRoomData () inline protected
Definition at line 219 of file dungeon_object_renderer_mock_test.cc.
References yaze::zelda3::MockRoomGenerator::GenerateMockRoom(), mock_rom_, rooms_, and test_palettes_.
Referenced by SetUp().
CreateMockObject()
RoomObject yaze::zelda3::DungeonObjectRendererMockTest::CreateMockObject (int object_id, int x, int y, int size = 0x12, int layer = 0) inline protected
Definition at line 239 of file dungeon_object_renderer_mock_test.cc.
References yaze::zelda3::RoomObject::EnsureTilesLoaded(), mock_rom_, and yaze::zelda3::RoomObject::set_rom().
Referenced by CreateMockObjectSet().
CreateMockObjectSet()
std::vector< RoomObject > yaze::zelda3::DungeonObjectRendererMockTest::CreateMockObjectSet () inline protected
Definition at line 246 of file dungeon_object_renderer_mock_test.cc.
References CreateMockObject().
Member Data Documentation
mock_rom_
std::unique_ptr<MockRom> yaze::zelda3::DungeonObjectRendererMockTest::mock_rom_ protected
Definition at line 254 of file dungeon_object_renderer_mock_test.cc.
Referenced by CreateMockObject(), GenerateMockRoomData(), SetUp(), and TearDown().
dungeon_editor_system_
std::unique_ptr<DungeonEditorSystem> yaze::zelda3::DungeonObjectRendererMockTest::dungeon_editor_system_ protected
Definition at line 255 of file dungeon_object_renderer_mock_test.cc.
Referenced by SetUp(), and TearDown().
object_editor_
std::shared_ptr<DungeonObjectEditor> yaze::zelda3::DungeonObjectRendererMockTest::object_editor_ protected
Definition at line 256 of file dungeon_object_renderer_mock_test.cc.
Referenced by SetUp(), and TearDown().
object_renderer_
std::unique_ptr<ObjectRenderer> yaze::zelda3::DungeonObjectRendererMockTest::object_renderer_ protected
Definition at line 257 of file dungeon_object_renderer_mock_test.cc.
Referenced by SetUp(), and TearDown().
rooms_
std::map<int, Room> yaze::zelda3::DungeonObjectRendererMockTest::rooms_ protected
Definition at line 259 of file dungeon_object_renderer_mock_test.cc.
Referenced by GenerateMockRoomData().
test_palettes_
std::vector<gfx::SnesPalette> yaze::zelda3::DungeonObjectRendererMockTest::test_palettes_ protected
Definition at line 260 of file dungeon_object_renderer_mock_test.cc.
Referenced by GenerateMockRoomData().
The documentation for this class was generated from the following file:
test/zelda3/dungeon_object_renderer_mock_test.cc