yaze: yaze::test::emu::MockAudioRam Class Reference
yaze::test::emu::MockAudioRam Class Reference
MockAudioRam is a mock class for the AudioRam class.
Public Member Functions
MOCK_METHOD (void, reset,(),(override))
MOCK_METHOD (uint8_t, read,(uint16_t address),(const, override))
MOCK_METHOD (uint8_t &, mutable_read,(uint16_t address),(override))
MOCK_METHOD (void, write,(uint16_t address, uint8_t value),(override))
void SetupMemory (uint16_t address, const std::vector< uint8_t > &values)
void SetUp ()
Public Member Functions inherited from yaze::app::emu::audio::AudioRam
virtual ~AudioRam ()=default
virtual void reset ()=0
virtual uint8_t read (uint16_t address) const =0
virtual uint8_t & mutable_read (uint16_t address)=0
virtual void write (uint16_t address, uint8_t value)=0
uint8_t operator[] (uint16_t address)
Public Attributes
std::vector< uint8_t > internal_audio_ram_ = std::vector<uint8_t>(0x10000, 0)
Detailed Description
MockAudioRam is a mock class for the AudioRam class.
Definition at line 20 of file spc700_test.cc.
Member Function Documentation
MOCK_METHOD() [1/4]
yaze::test::emu::MockAudioRam::MOCK_METHOD (void , reset , () , (override))
MOCK_METHOD() [2/4]
yaze::test::emu::MockAudioRam::MOCK_METHOD (uint8_t , read , (uint16_t address) , (const, override))
MOCK_METHOD() [3/4]
yaze::test::emu::MockAudioRam::MOCK_METHOD (uint8_t & , mutable_read , (uint16_t address) , (override))
MOCK_METHOD() [4/4]
yaze::test::emu::MockAudioRam::MOCK_METHOD (void , write , (uint16_t address, uint8_t value) , (override))
SetupMemory()
void yaze::test::emu::MockAudioRam::SetupMemory (uint16_t address, const std::vector< uint8_t > & values) inline
Definition at line 27 of file spc700_test.cc.
References internal_audio_ram_.
SetUp()
void yaze::test::emu::MockAudioRam::SetUp () inline
Definition at line 38 of file spc700_test.cc.
References internal_audio_ram_, yaze::app::emu::audio::AudioRam::mutable_read(), yaze::app::emu::audio::AudioRam::read(), yaze::app::emu::audio::AudioRam::reset(), and yaze::app::emu::audio::AudioRam::write().
Member Data Documentation
internal_audio_ram_
std::vector<uint8_t> yaze::test::emu::MockAudioRam::internal_audio_ram_ = std::vector<uint8_t>(0x10000, 0)
Definition at line 57 of file spc700_test.cc.
Referenced by SetUp(), and SetupMemory().
The documentation for this class was generated from the following file:
src/test/emu/spc700_test.cc