yaze: yaze::zelda3::screen::TitleScreen Class Reference
yaze::zelda3::screen::TitleScreen Class Reference
#include <title_screen.h>
Public Member Functions
void Create ()
Private Member Functions
void BuildTileset ()
void LoadTitleScreen ()
Private Attributes
int sword_x_ = 0
int mx_click_ = 0
int my_click_ = 0
int mx_dist_ = 0
int my_dist_ = 0
int last_x_ = 0
int last_y_ = 0
int x_in_ = 0
int y_in_ = 0
int dungmap_selected_tile_ = 0
int dungmap_selected_ = 0
int selected_palette_ = 0
int total_floors_ = 0
int current_floor_ = 0
int num_basement_ = 0
int num_floor_ = 0
int selected_map_tile = 0
int current_floor_rooms
int current_floor_gfx
int copied_data_rooms
int copied_data_gfx
int pal_selected_
int addresses [7]
int addressesgfx [7]
ushort bossRoom = 0x000F
ushort selected_tile = 0
ushort tilesBG1Buffer [0x1000]
ushort tilesBG2Buffer [0x1000]
uchar mapdata
uchar dwmapdata
bool mDown = false
bool swordSelected = false
bool darkWorld = false
bool currentDungeonChanged = false
bool editedFromEditor = false
bool mouseDown = false
bool mdown = false
Rom rom_
gfx::OamTile oam_data [10]
gfx::OamTile selected_oam_tile
gfx::OamTile last_selected_oam_tile
gfx::Bitmap tilesBG1Bitmap
gfx::Bitmap tilesBG2Bitmap
gfx::Bitmap oamBGBitmap
gfx::Bitmap tiles8Bitmap
Detailed Description
Definition at line 15 of file title_screen.h.
Member Function Documentation
Create()
void yaze::zelda3::screen::TitleScreen::Create ()
Definition at line 13 of file title_screen.cc.
References BuildTileset(), LoadTitleScreen(), oamBGBitmap, tiles8Bitmap, tilesBG1Bitmap, and tilesBG2Bitmap.
BuildTileset()
void yaze::zelda3::screen::TitleScreen::BuildTileset () private
Todo
get the gfx from the GFX class rather than the rom.
Definition at line 22 of file title_screen.cc.
References tiles8Bitmap.
Referenced by Create().
LoadTitleScreen()
void yaze::zelda3::screen::TitleScreen::LoadTitleScreen () private
Definition at line 63 of file title_screen.cc.
References pal_selected_, rom_, yaze::core::SnesToPc(), tilesBG1Buffer, and tilesBG2Buffer.
Referenced by Create().
Member Data Documentation
sword_x_
int yaze::zelda3::screen::TitleScreen::sword_x_ = 0 private
Definition at line 23 of file title_screen.h.
mx_click_
int yaze::zelda3::screen::TitleScreen::mx_click_ = 0 private
Definition at line 24 of file title_screen.h.
my_click_
int yaze::zelda3::screen::TitleScreen::my_click_ = 0 private
Definition at line 25 of file title_screen.h.
mx_dist_
int yaze::zelda3::screen::TitleScreen::mx_dist_ = 0 private
Definition at line 26 of file title_screen.h.
my_dist_
int yaze::zelda3::screen::TitleScreen::my_dist_ = 0 private
Definition at line 27 of file title_screen.h.
last_x_
int yaze::zelda3::screen::TitleScreen::last_x_ = 0 private
Definition at line 28 of file title_screen.h.
last_y_
int yaze::zelda3::screen::TitleScreen::last_y_ = 0 private
Definition at line 29 of file title_screen.h.
x_in_
int yaze::zelda3::screen::TitleScreen::x_in_ = 0 private
Definition at line 30 of file title_screen.h.
y_in_
int yaze::zelda3::screen::TitleScreen::y_in_ = 0 private
Definition at line 31 of file title_screen.h.
dungmap_selected_tile_
int yaze::zelda3::screen::TitleScreen::dungmap_selected_tile_ = 0 private
Definition at line 32 of file title_screen.h.
dungmap_selected_
int yaze::zelda3::screen::TitleScreen::dungmap_selected_ = 0 private
Definition at line 33 of file title_screen.h.
selected_palette_
int yaze::zelda3::screen::TitleScreen::selected_palette_ = 0 private
Definition at line 34 of file title_screen.h.
total_floors_
int yaze::zelda3::screen::TitleScreen::total_floors_ = 0 private
Definition at line 35 of file title_screen.h.
current_floor_
int yaze::zelda3::screen::TitleScreen::current_floor_ = 0 private
Definition at line 36 of file title_screen.h.
num_basement_
int yaze::zelda3::screen::TitleScreen::num_basement_ = 0 private
Definition at line 37 of file title_screen.h.
num_floor_
int yaze::zelda3::screen::TitleScreen::num_floor_ = 0 private
Definition at line 38 of file title_screen.h.
selected_map_tile
int yaze::zelda3::screen::TitleScreen::selected_map_tile = 0 private
Definition at line 39 of file title_screen.h.
current_floor_rooms
int yaze::zelda3::screen::TitleScreen::current_floor_rooms private
Definition at line 40 of file title_screen.h.
current_floor_gfx
int yaze::zelda3::screen::TitleScreen::current_floor_gfx private
Definition at line 41 of file title_screen.h.
copied_data_rooms
int yaze::zelda3::screen::TitleScreen::copied_data_rooms private
Definition at line 42 of file title_screen.h.
copied_data_gfx
int yaze::zelda3::screen::TitleScreen::copied_data_gfx private
Definition at line 43 of file title_screen.h.
pal_selected_
int yaze::zelda3::screen::TitleScreen::pal_selected_ private
Definition at line 44 of file title_screen.h.
Referenced by LoadTitleScreen().
addresses
int yaze::zelda3::screen::TitleScreen::addresses[7] private
Initial value:
= {0x53de4, 0x53e2c, 0x53e08, 0x53e50,
                      0x53e74, 0x53e98, 0x53ebc}
Definition at line 45 of file title_screen.h.
addressesgfx
int yaze::zelda3::screen::TitleScreen::addressesgfx[7] private
Initial value:
= {0x53ee0, 0x53f04, 0x53ef2, 0x53f16,
                         0x53f28, 0x53f3a, 0x53f4c}
Definition at line 47 of file title_screen.h.
bossRoom
ushort yaze::zelda3::screen::TitleScreen::bossRoom = 0x000F private
Definition at line 50 of file title_screen.h.
selected_tile
ushort yaze::zelda3::screen::TitleScreen::selected_tile = 0 private
Definition at line 51 of file title_screen.h.
tilesBG1Buffer
ushort yaze::zelda3::screen::TitleScreen::tilesBG1Buffer[0x1000] private
Definition at line 52 of file title_screen.h.
Referenced by LoadTitleScreen().
tilesBG2Buffer
ushort yaze::zelda3::screen::TitleScreen::tilesBG2Buffer[0x1000] private
Definition at line 53 of file title_screen.h.
Referenced by LoadTitleScreen().
mapdata
uchar yaze::zelda3::screen::TitleScreen::mapdata private
Definition at line 54 of file title_screen.h.
dwmapdata
uchar yaze::zelda3::screen::TitleScreen::dwmapdata private
Definition at line 55 of file title_screen.h.
mDown
bool yaze::zelda3::screen::TitleScreen::mDown = false private
Definition at line 57 of file title_screen.h.
swordSelected
bool yaze::zelda3::screen::TitleScreen::swordSelected = false private
Definition at line 58 of file title_screen.h.
darkWorld
bool yaze::zelda3::screen::TitleScreen::darkWorld = false private
Definition at line 59 of file title_screen.h.
currentDungeonChanged
bool yaze::zelda3::screen::TitleScreen::currentDungeonChanged = false private
Definition at line 60 of file title_screen.h.
editedFromEditor
bool yaze::zelda3::screen::TitleScreen::editedFromEditor = false private
Definition at line 61 of file title_screen.h.
mouseDown
bool yaze::zelda3::screen::TitleScreen::mouseDown = false private
Definition at line 62 of file title_screen.h.
mdown
bool yaze::zelda3::screen::TitleScreen::mdown = false private
Definition at line 63 of file title_screen.h.
rom_
Rom yaze::zelda3::screen::TitleScreen::rom_ private
Definition at line 65 of file title_screen.h.
Referenced by LoadTitleScreen().
oam_data
gfx::OamTile yaze::zelda3::screen::TitleScreen::oam_data[10] private
Definition at line 67 of file title_screen.h.
selected_oam_tile
gfx::OamTile yaze::zelda3::screen::TitleScreen::selected_oam_tile private
Definition at line 68 of file title_screen.h.
last_selected_oam_tile
gfx::OamTile yaze::zelda3::screen::TitleScreen::last_selected_oam_tile private
Definition at line 69 of file title_screen.h.
tilesBG1Bitmap
gfx::Bitmap yaze::zelda3::screen::TitleScreen::tilesBG1Bitmap private
Definition at line 71 of file title_screen.h.
Referenced by Create().
tilesBG2Bitmap
gfx::Bitmap yaze::zelda3::screen::TitleScreen::tilesBG2Bitmap private
Definition at line 72 of file title_screen.h.
Referenced by Create().
oamBGBitmap
gfx::Bitmap yaze::zelda3::screen::TitleScreen::oamBGBitmap private
Definition at line 73 of file title_screen.h.
Referenced by Create().
tiles8Bitmap
gfx::Bitmap yaze::zelda3::screen::TitleScreen::tiles8Bitmap private
Definition at line 74 of file title_screen.h.
Referenced by BuildTileset(), and Create().
The documentation for this class was generated from the following files:
src/app/zelda3/screen/title_screen.h
src/app/zelda3/screen/title_screen.cc