yaze: yaze::app::gfx::SnesPalette Class Reference
yaze::app::gfx::SnesPalette Class Reference
Represents a palette of colors for the Super Nintendo Entertainment System (SNES).
#include <snes_palette.h>
Public Member Functions
template<typename T >
SnesPalette (const std::vector< T > &data)
SnesPalette ()=default
SnesPalette (char *snesPal)
SnesPalette (const unsigned char *snes_pal)
SnesPalette (const std::vector< ImVec4 > &)
SnesPalette (const std::vector< snes_color > &)
SnesPalette (const std::vector< SnesColor > &)
void Create (const std::vector< SnesColor > &cols)
void AddColor (const SnesColor &color)
void AddColor (const snes_color &color)
void AddColor (uint16_t color)
absl::StatusOr< SnesColor > GetColor (int i) const
auto mutable_color (int i)
void clear ()
auto size () const
auto empty () const
SnesColor & operator[] (int i)
void operator() (int i, const SnesColor &color)
void operator() (int i, const ImVec4 &color)
SnesPalette sub_palette (int start, int end) const
Private Attributes
std::vector< SnesColor > colors
Detailed Description
Represents a palette of colors for the Super Nintendo Entertainment System (SNES).
The SnesPalette class provides functionality to create, modify, and access colors in an SNES palette. It supports various constructors to initialize the palette with different types of data. The palette can be modified by adding or changing colors, and it can be cleared to remove all colors. Colors in the palette can be accessed using index-based access or through the GetColor method. The class also provides a method to create a sub-palette by selecting a range of colors from the original palette.
Definition at line 107 of file snes_palette.h.
Constructor & Destructor Documentation
SnesPalette() [1/7]
template<typename T > yaze::app::gfx::SnesPalette::SnesPalette (const std::vector< T > & data) inline explicit
Definition at line 110 of file snes_palette.h.
References colors.
SnesPalette() [2/7]
yaze::app::gfx::SnesPalette::SnesPalette () default
SnesPalette() [3/7]
yaze::app::gfx::SnesPalette::SnesPalette (char * snesPal) explicit
Definition at line 226 of file snes_palette.cc.
References snes_color::blue, colors, yaze::app::gfx::ConvertSnesToRgb(), snes_color::green, snes_color::red, yaze::app::gfx::SnesColor::set_rgb(), yaze::app::gfx::SnesColor::set_snes(), and yaze::app::gfx::SnesColor::snes().
SnesPalette() [4/7]
yaze::app::gfx::SnesPalette::SnesPalette (const unsigned char * snes_pal) explicit
Definition at line 238 of file snes_palette.cc.
References snes_color::blue, colors, yaze::app::gfx::ConvertSnesToRgb(), snes_color::green, snes_color::red, yaze::app::gfx::SnesColor::set_rgb(), yaze::app::gfx::SnesColor::set_snes(), and yaze::app::gfx::SnesColor::snes().
SnesPalette() [5/7]
yaze::app::gfx::SnesPalette::SnesPalette (const std::vector< ImVec4 > & cols) explicit
Definition at line 250 of file snes_palette.cc.
References colors, and yaze::app::gfx::SnesColor::set_rgb().
SnesPalette() [6/7]
yaze::app::gfx::SnesPalette::SnesPalette (const std::vector< snes_color > & cols) explicit
Definition at line 258 of file snes_palette.cc.
References colors, yaze::app::gfx::ConvertRgbToSnes(), and yaze::app::gfx::SnesColor::set_snes().
SnesPalette() [7/7]
yaze::app::gfx::SnesPalette::SnesPalette (const std::vector< SnesColor > & cols) explicit
Definition at line 266 of file snes_palette.cc.
References colors.
Member Function Documentation
Create()
void yaze::app::gfx::SnesPalette::Create (const std::vector< SnesColor > & cols) inline
Definition at line 123 of file snes_palette.h.
References colors.
Referenced by yaze::app::zelda3::overworld::palette_internal::SetColorsPalette().
AddColor() [1/3]
void yaze::app::gfx::SnesPalette::AddColor (const SnesColor & color) inline
Definition at line 129 of file snes_palette.h.
References colors.
Referenced by yaze::app::gfx::CreatePaletteGroupFromColFile(), yaze::app::gfx::CreatePaletteGroupFromLargePalette(), yaze::app::editor::MessageEditor::Initialize(), sub_palette(), and yaze::test::gfx::TEST().
AddColor() [2/3]
void yaze::app::gfx::SnesPalette::AddColor (const snes_color & color) inline
Definition at line 130 of file snes_palette.h.
References colors.
AddColor() [3/3]
void yaze::app::gfx::SnesPalette::AddColor (uint16_t color) inline
Definition at line 131 of file snes_palette.h.
References colors.
GetColor()
absl::StatusOr< SnesColor > yaze::app::gfx::SnesPalette::GetColor (int i) const inline
Definition at line 133 of file snes_palette.h.
References colors.
Referenced by yaze::app::gfx::Bitmap::ApplyPaletteFromPaletteGroup(), yaze::app::editor::DisplayPalette(), yaze::app::gui::DisplayPalette(), yaze::app::editor::PaletteEditor::DrawPaletteGroup(), yaze::app::editor::PaletteEditor::EditColorInPalette(), and yaze::app::editor::PaletteEditor::ResetColorToOriginal().
mutable_color()
auto yaze::app::gfx::SnesPalette::mutable_color (int i) inline
Definition at line 140 of file snes_palette.h.
References colors.
Referenced by yaze::app::editor::PaletteEditor::DrawPaletteGroup(), and yaze::app::editor::MessageEditor::Initialize().
clear()
void yaze::app::gfx::SnesPalette::clear () inline
Definition at line 142 of file snes_palette.h.
References colors.
Referenced by yaze::app::gfx::Bitmap::Cleanup(), and yaze::app::gfx::Tilesheet::clear().
size()
auto yaze::app::gfx::SnesPalette::size () const inline
Definition at line 143 of file snes_palette.h.
References colors.
Referenced by yaze::app::gfx::Bitmap::ApplyPaletteFromPaletteGroup(), yaze::app::gfx::CreatePaletteGroupFromLargePalette(), yaze::app::editor::DisplayPalette(), yaze::app::gui::DisplayPalette(), yaze::app::editor::GraphicsEditor::DrawPaletteControls(), yaze::app::editor::anonymous_namespace{gfx_group_editor.cc}::DrawPaletteFromPaletteGroup(), yaze::app::editor::PaletteEditor::DrawPaletteGroup(), yaze::app::editor::PaletteEditor::EditColorInPalette(), yaze::app::editor::MessageEditor::Initialize(), yaze::app::gfx::Bitmap::palette_size(), yaze::app::editor::PaletteEditor::ResetColorToOriginal(), yaze::app::Rom::SavePalette(), yaze::app::gui::SelectablePalettePipeline(), and yaze::test::gfx::TEST().
empty()
auto yaze::app::gfx::SnesPalette::empty () const inline
Definition at line 144 of file snes_palette.h.
References colors.
Referenced by yaze::app::editor::anonymous_namespace{gfx_group_editor.cc}::DrawPaletteFromPaletteGroup().
operator[]()
SnesColor & yaze::app::gfx::SnesPalette::operator[] (int i) inline
Definition at line 146 of file snes_palette.h.
References colors.
operator()() [1/2]
void yaze::app::gfx::SnesPalette::operator() (int i, const SnesColor & color) inline
Definition at line 154 of file snes_palette.h.
References colors.
operator()() [2/2]
void yaze::app::gfx::SnesPalette::operator() (int i, const ImVec4 & color) inline
Definition at line 161 of file snes_palette.h.
References colors.
sub_palette()
SnesPalette yaze::app::gfx::SnesPalette::sub_palette (int start, int end) const inline
Definition at line 170 of file snes_palette.h.
References AddColor(), and colors.
Referenced by yaze::app::gfx::Bitmap::ApplyPaletteFromPaletteGroup(), and yaze::app::gfx::Bitmap::ApplyPaletteWithTransparent().
Member Data Documentation
colors
std::vector<SnesColor> yaze::app::gfx::SnesPalette::colors private
The colors in the palette.
Definition at line 179 of file snes_palette.h.
Referenced by AddColor(), AddColor(), AddColor(), clear(), Create(), empty(), GetColor(), mutable_color(), operator()(), operator()(), operator[](), size(), SnesPalette(), SnesPalette(), SnesPalette(), SnesPalette(), SnesPalette(), SnesPalette(), and sub_palette().
The documentation for this class was generated from the following files:
src/app/gfx/snes_palette.h
src/app/gfx/snes_palette.cc