yaze: yaze::app::zelda3::screen::Inventory Class Reference
yaze::app::zelda3::screen::Inventory Class Reference
#include <inventory.h>
Public Member Functions
auto Bitmap () const
auto Tilesheet () const
auto Palette () const
absl::Status Create ()
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Private Member Functions
absl::Status BuildTileset ()
Private Attributes
std::vector< uint8_t > data_
gfx::Bitmap bitmap_
std::vector< uint8_t > tilesheets_
std::vector< uint8_t > test_
gfx::Bitmap tilesheets_bmp_
gfx::SnesPalette palette_
gui::Canvas canvas_
std::vector< gfx::TileInfo > tiles_
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
Definition at line 18 of file inventory.h.
Member Function Documentation
Bitmap()
auto yaze::app::zelda3::screen::Inventory::Bitmap () const inline
Definition at line 20 of file inventory.h.
References bitmap_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
Tilesheet()
auto yaze::app::zelda3::screen::Inventory::Tilesheet () const inline
Definition at line 21 of file inventory.h.
References tilesheets_bmp_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
Palette()
auto yaze::app::zelda3::screen::Inventory::Palette () const inline
Definition at line 22 of file inventory.h.
References palette_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
Create()
absl::Status yaze::app::zelda3::screen::Inventory::Create ()
Definition at line 16 of file inventory.cc.
References yaze::app::gfx::Bitmap::ApplyPalette(), bitmap_, BuildTileset(), yaze::app::gfx::Bitmap::Create(), data_, yaze::app::core::Renderer::GetInstance(), yaze::app::gfx::GetTilesInfo(), yaze::app::zelda3::screen::kBowItemPos, palette_, yaze::app::core::Renderer::RenderBitmap(), RETURN_IF_ERROR, yaze::app::SharedRom::rom(), test_, and tiles_.
Referenced by yaze::app::editor::ScreenEditor::DrawInventoryMenuEditor().
BuildTileset()
absl::Status yaze::app::zelda3::screen::Inventory::BuildTileset () private
Definition at line 75 of file inventory.cc.
References yaze::app::gfx::Bitmap::ApplyPalette(), ASSIGN_OR_RETURN, yaze::app::gfx::Bitmap::Create(), yaze::app::core::Renderer::GetInstance(), palette_, yaze::app::core::Renderer::RenderBitmap(), RETURN_IF_ERROR, yaze::app::SharedRom::rom(), test_, tilesheets_, and tilesheets_bmp_.
Referenced by Create().
Member Data Documentation
data_
std::vector<uint8_t> yaze::app::zelda3::screen::Inventory::data_ private
Definition at line 29 of file inventory.h.
Referenced by Create().
bitmap_
gfx::Bitmap yaze::app::zelda3::screen::Inventory::bitmap_ private
Definition at line 30 of file inventory.h.
Referenced by Bitmap(), and Create().
tilesheets_
std::vector<uint8_t> yaze::app::zelda3::screen::Inventory::tilesheets_ private
Definition at line 32 of file inventory.h.
Referenced by BuildTileset().
test_
std::vector<uint8_t> yaze::app::zelda3::screen::Inventory::test_ private
Definition at line 33 of file inventory.h.
Referenced by BuildTileset(), and Create().
tilesheets_bmp_
gfx::Bitmap yaze::app::zelda3::screen::Inventory::tilesheets_bmp_ private
Definition at line 34 of file inventory.h.
Referenced by BuildTileset(), and Tilesheet().
palette_
gfx::SnesPalette yaze::app::zelda3::screen::Inventory::palette_ private
Definition at line 35 of file inventory.h.
Referenced by BuildTileset(), Create(), and Palette().
canvas_
gui::Canvas yaze::app::zelda3::screen::Inventory::canvas_ private
Definition at line 37 of file inventory.h.
tiles_
std::vector<gfx::TileInfo> yaze::app::zelda3::screen::Inventory::tiles_ private
Definition at line 38 of file inventory.h.
Referenced by Create().
The documentation for this class was generated from the following files:
src/app/zelda3/screen/inventory.h
src/app/zelda3/screen/inventory.cc