yaze: yaze_test::zelda3_test::SpriteBuilderTest Class Reference
yaze_test::zelda3_test::SpriteBuilderTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Protected Attributes
SpriteBuilder sprite
Member Function Documentation
SetUp()
void yaze_test::zelda3_test::SpriteBuilderTest::SetUp () inline override protected
References yaze::app::zelda3::SpriteBuilder::AddAction(), yaze::app::zelda3::SpriteAction::AddCustomInstruction(), yaze::app::zelda3::SpriteBuilder::AddFunction(), yaze::app::zelda3::SpriteAction::AddInstruction(), yaze::app::zelda3::SpriteInstruction::ApplySpeedTowardsPlayer(), yaze::app::zelda3::SpriteInstruction::BehaveAsBarrier(), yaze::app::zelda3::SpriteInstruction::BounceFromTileCollision(), yaze::app::zelda3::SpriteAction::Create(), yaze::app::zelda3::SpriteBuilder::Create(), yaze::app::zelda3::SpriteInstruction::JumpToFunction(), yaze::app::zelda3::SpriteInstruction::MoveXyz(), yaze::app::zelda3::SpriteInstruction::PlayAnimation(), yaze::app::zelda3::SpriteBuilder::SetGlobalAction(), yaze::app::zelda3::SpriteAction::SetNextAction(), yaze::app::zelda3::SpriteBuilder::SetProperty(), and sprite.
TearDown()
void yaze_test::zelda3_test::SpriteBuilderTest::TearDown () inline override protected
Member Data Documentation
sprite
SpriteBuilder yaze_test::zelda3_test::SpriteBuilderTest::sprite protected
Referenced by SetUp().
The documentation for this class was generated from the following file:
src/test/zelda3/sprite_builder_test.cc