yaze: src/app/core/platform/clipboard.cc File Reference
clipboard.cc File Reference
#include "app/core/platform/clipboard.h"
#include <cstdint>
#include <vector>
Functions
void CopyImageToClipboard (const std::vector< uint8_t > &data)
void GetImageFromClipboard (std::vector< uint8_t > &data, int &width, int &height)
Function Documentation
CopyImageToClipboard()
void CopyImageToClipboard (const std::vector< uint8_t > & data)
Referenced by yaze::app::editor::GraphicsEditor::DrawGfxEditToolset(), and yaze::app::editor::OverworldEditor::DrawToolset().
GetImageFromClipboard()
void GetImageFromClipboard (std::vector< uint8_t > & data, int & width, int & height)
Referenced by yaze::app::editor::GraphicsEditor::DrawGfxEditToolset().