yaze: src/app/core/platform/clipboard.h File Reference
clipboard.h File Reference
#include <cstdint>
#include <vector>
Functions
void CopyImageToClipboard (const std::vector< uint8_t > &data)
void GetImageFromClipboard (std::vector< uint8_t > &data, int &width, int &height)
Function Documentation
CopyImageToClipboard()
void CopyImageToClipboard (const std::vector< uint8_t > & data)
Definition at line 6 of file clipboard.cc.
Referenced by yaze::app::editor::GraphicsEditor::DrawGfxEditToolset(), and yaze::app::editor::OverworldEditor::DrawToolset().
GetImageFromClipboard()
void GetImageFromClipboard (std::vector< uint8_t > & data, int & width, int & height)
Definition at line 7 of file clipboard.cc.
Referenced by yaze::app::editor::GraphicsEditor::DrawGfxEditToolset().