yaze: src/app/core/controller.h File Reference
controller.h File Reference
#include <SDL.h>
#include "imgui/backends/imgui_impl_sdl2.h"
#include "imgui/backends/imgui_impl_sdlrenderer2.h"
#include "imgui/imconfig.h"
#include "imgui/imgui.h"
#include "imgui/imgui_internal.h"
#include <memory>
#include "absl/status/status.h"
#include "app/core/common.h"
#include "app/core/platform/renderer.h"
#include "app/editor/master_editor.h"
#include "app/editor/utils/editor.h"
#include "app/gui/icons.h"
#include "app/gui/style.h"
Classes
class yaze::app::core::Controller
Main controller for the application.
struct yaze::app::core::Controller::sdl_deleter
Namespaces
namespace yaze
namespace yaze::app
Main namespace for the ImGui application.
namespace yaze::app::core
Core application logic and utilities.
Enumerations
enum class yaze::app::core::Platform {
yaze::app::core::kUnknown , yaze::app::core::kMacOS , yaze::app::core::kiOS , yaze::app::core::kWindows ,
yaze::app::core::kLinux
}
Functions
int main (int argc, char **argv)
Main entry point for the application.
Function Documentation
main()
int main (int argc, char ** argv)
Main entry point for the application.
Definition at line 32 of file emu.cc.
References yaze::app::core::Controller::DoRender(), EXIT_IF_ERROR, yaze::app::emu::SNES::Init(), yaze::app::Rom::is_loaded(), yaze::app::core::Controller::IsActive(), yaze::app::Rom::LoadFromFile(), yaze::app::emu::SNES::Memory(), yaze::app::core::Controller::OnEntry(), yaze::app::core::Controller::OnExit(), yaze::app::core::Controller::OnInput(), yaze::app::core::Controller::OnLoad(), yaze::app::emu::SNES::RunFrame(), yaze::app::emu::SNES::SetPixels(), yaze::app::emu::SNES::SetSamples(), and yaze::app::Rom::vector().
Referenced by yaze::app::zelda3::overworld::OverworldMap::LoadPalette(), and yaze::app::zelda3::overworld::palette_internal::SetColorsPalette().