var dir_0b974e391fb3f3024b1f06092da5c188 =
[
    [ "backend", "dir_784a83bb080884888e34b265f0a3846e.html", "dir_784a83bb080884888e34b265f0a3846e" ],
    [ "arena.cc", "d2/dee/arena_8cc.html", null ],
    [ "arena.h", "da/d0c/arena_8h.html", "da/d0c/arena_8h" ],
    [ "atlas_renderer.cc", "dd/d53/atlas__renderer_8cc.html", null ],
    [ "atlas_renderer.h", "d1/d35/atlas__renderer_8h.html", "d1/d35/atlas__renderer_8h" ],
    [ "background_buffer.cc", "d3/d90/background__buffer_8cc.html", null ],
    [ "background_buffer.h", "d0/d54/background__buffer_8h.html", "d0/d54/background__buffer_8h" ],
    [ "bitmap.cc", "d4/d13/bitmap_8cc.html", "d4/d13/bitmap_8cc" ],
    [ "bitmap.h", "da/dcb/bitmap_8h.html", "da/dcb/bitmap_8h" ],
    [ "bpp_format_manager.cc", "d2/d41/bpp__format__manager_8cc.html", null ],
    [ "bpp_format_manager.h", "dc/d83/bpp__format__manager_8h.html", "dc/d83/bpp__format__manager_8h" ],
    [ "compression.cc", "d3/d2e/compression_8cc.html", "d3/d2e/compression_8cc" ],
    [ "compression.h", "d1/daf/compression_8h.html", "d1/daf/compression_8h" ],
    [ "graphics_optimizer.cc", "dc/db4/graphics__optimizer_8cc.html", null ],
    [ "graphics_optimizer.h", "dd/d54/graphics__optimizer_8h.html", "dd/d54/graphics__optimizer_8h" ],
    [ "memory_pool.cc", "d9/dc6/memory__pool_8cc.html", "d9/dc6/memory__pool_8cc" ],
    [ "memory_pool.h", "de/d5c/memory__pool_8h.html", "de/d5c/memory__pool_8h" ],
    [ "performance_dashboard.cc", "d4/d9f/performance__dashboard_8cc.html", null ],
    [ "performance_dashboard.h", "db/d5c/performance__dashboard_8h.html", "db/d5c/performance__dashboard_8h" ],
    [ "performance_profiler.cc", "d5/da6/performance__profiler_8cc.html", null ],
    [ "performance_profiler.h", "dd/db2/performance__profiler_8h.html", "dd/db2/performance__profiler_8h" ],
    [ "scad_format.cc", "d1/de3/scad__format_8cc.html", "d1/de3/scad__format_8cc" ],
    [ "scad_format.h", "df/d33/scad__format_8h.html", "df/d33/scad__format_8h" ],
    [ "snes_color.cc", "dc/dee/snes__color_8cc.html", "dc/dee/snes__color_8cc" ],
    [ "snes_color.h", "d5/d52/snes__color_8h.html", "d5/d52/snes__color_8h" ],
    [ "snes_palette.cc", "de/d89/snes__palette_8cc.html", "de/d89/snes__palette_8cc" ],
    [ "snes_palette.h", "d8/ddb/snes__palette_8h.html", "d8/ddb/snes__palette_8h" ],
    [ "snes_tile.cc", "d3/d73/snes__tile_8cc.html", "d3/d73/snes__tile_8cc" ],
    [ "snes_tile.h", "d0/d8d/snes__tile_8h.html", "d0/d8d/snes__tile_8h" ],
    [ "texture_atlas.cc", "d3/d1b/texture__atlas_8cc.html", null ],
    [ "texture_atlas.h", "db/dd3/texture__atlas_8h.html", "db/dd3/texture__atlas_8h" ],
    [ "tilemap.cc", "d6/de2/tilemap_8cc.html", "d6/de2/tilemap_8cc" ],
    [ "tilemap.h", "dc/d0c/tilemap_8h.html", "dc/d0c/tilemap_8h" ]
];