var dir_6786299e5fb540707e8551af9d97f855 =
[
    [ "command_manager.cc", "d3/d69/command__manager_8cc.html", null ],
    [ "command_manager.h", "df/d56/command__manager_8h.html", "df/d56/command__manager_8h" ],
    [ "command_palette.cc", "d4/d01/app_2editor_2system_2command__palette_8cc.html", null ],
    [ "command_palette.h", "d5/d8f/app_2editor_2system_2command__palette_8h.html", "d5/d8f/app_2editor_2system_2command__palette_8h" ],
    [ "editor_card_registry.cc", "d7/d7f/editor__card__registry_8cc.html", null ],
    [ "editor_card_registry.h", "d4/d5b/editor__card__registry_8h.html", "d4/d5b/editor__card__registry_8h" ],
    [ "editor_registry.cc", "dc/dee/editor__registry_8cc.html", null ],
    [ "editor_registry.h", "d9/da3/editor__registry_8h.html", "d9/da3/editor__registry_8h" ],
    [ "extension_manager.cc", "d1/d95/extension__manager_8cc.html", null ],
    [ "extension_manager.h", "d4/db5/extension__manager_8h.html", "d4/db5/extension__manager_8h" ],
    [ "history_manager.h", "d4/d82/history__manager_8h.html", "d4/d82/history__manager_8h" ],
    [ "menu_orchestrator.cc", "d9/d1e/menu__orchestrator_8cc.html", null ],
    [ "menu_orchestrator.h", "db/d15/menu__orchestrator_8h.html", "db/d15/menu__orchestrator_8h" ],
    [ "popup_manager.cc", "d8/de0/popup__manager_8cc.html", null ],
    [ "popup_manager.h", "dd/da4/popup__manager_8h.html", "dd/da4/popup__manager_8h" ],
    [ "project_manager.cc", "df/da2/project__manager_8cc.html", null ],
    [ "project_manager.h", "df/dc4/project__manager_8h.html", "df/dc4/project__manager_8h" ],
    [ "proposal_drawer.cc", "d1/d96/proposal__drawer_8cc.html", null ],
    [ "proposal_drawer.h", "d5/dca/proposal__drawer_8h.html", "d5/dca/proposal__drawer_8h" ],
    [ "rom_file_manager.cc", "d8/d59/rom__file__manager_8cc.html", null ],
    [ "rom_file_manager.h", "da/d80/rom__file__manager_8h.html", "da/d80/rom__file__manager_8h" ],
    [ "session_coordinator.cc", "d1/dcf/session__coordinator_8cc.html", "d1/dcf/session__coordinator_8cc" ],
    [ "session_coordinator.h", "d6/d0e/session__coordinator_8h.html", "d6/d0e/session__coordinator_8h" ],
    [ "settings_editor.cc", "d6/dbd/settings__editor_8cc.html", null ],
    [ "settings_editor.h", "d9/d0a/settings__editor_8h.html", "d9/d0a/settings__editor_8h" ],
    [ "shortcut_configurator.cc", "d9/da9/shortcut__configurator_8cc.html", "d9/da9/shortcut__configurator_8cc" ],
    [ "shortcut_configurator.h", "da/ddf/shortcut__configurator_8h.html", "da/ddf/shortcut__configurator_8h" ],
    [ "shortcut_manager.cc", "d3/d0d/shortcut__manager_8cc.html", "d3/d0d/shortcut__manager_8cc" ],
    [ "shortcut_manager.h", "d1/d72/shortcut__manager_8h.html", "d1/d72/shortcut__manager_8h" ],
    [ "toast_manager.h", "de/d7d/toast__manager_8h.html", "de/d7d/toast__manager_8h" ],
    [ "user_settings.cc", "dd/dc5/user__settings_8cc.html", null ],
    [ "user_settings.h", "da/dd9/user__settings_8h.html", "da/dd9/user__settings_8h" ],
    [ "window_delegate.cc", "d7/d74/window__delegate_8cc.html", null ],
    [ "window_delegate.h", "d1/d5e/window__delegate_8h.html", "d1/d5e/window__delegate_8h" ]
];