var dir_2e70ebb92041ee9a8b6891199983e337 =
[
    [ "bpp_format_ui.cc", "db/d3e/bpp__format__ui_8cc.html", null ],
    [ "bpp_format_ui.h", "db/da7/bpp__format__ui_8h.html", "db/da7/bpp__format__ui_8h" ],
    [ "canvas.cc", "da/dbb/canvas_8cc.html", "da/dbb/canvas_8cc" ],
    [ "canvas.h", "d4/dcf/canvas_8h.html", "d4/dcf/canvas_8h" ],
    [ "canvas_automation_api.cc", "d1/d50/canvas__automation__api_8cc.html", null ],
    [ "canvas_automation_api.h", "df/de8/canvas__automation__api_8h.html", "df/de8/canvas__automation__api_8h" ],
    [ "canvas_context_menu.cc", "df/db2/canvas__context__menu_8cc.html", "df/db2/canvas__context__menu_8cc" ],
    [ "canvas_context_menu.h", "d8/d2d/canvas__context__menu_8h.html", "d8/d2d/canvas__context__menu_8h" ],
    [ "canvas_events.h", "d5/dfd/canvas__events_8h.html", "d5/dfd/canvas__events_8h" ],
    [ "canvas_geometry.cc", "d0/d45/canvas__geometry_8cc.html", "d0/d45/canvas__geometry_8cc" ],
    [ "canvas_geometry.h", "d5/d93/canvas__geometry_8h.html", "d5/d93/canvas__geometry_8h" ],
    [ "canvas_interaction.cc", "dd/df1/canvas__interaction_8cc.html", "dd/df1/canvas__interaction_8cc" ],
    [ "canvas_interaction.h", "da/d0e/canvas__interaction_8h.html", "da/d0e/canvas__interaction_8h" ],
    [ "canvas_interaction_handler.cc", "d2/d1f/canvas__interaction__handler_8cc.html", "d2/d1f/canvas__interaction__handler_8cc" ],
    [ "canvas_interaction_handler.h", "dd/db1/canvas__interaction__handler_8h.html", "dd/db1/canvas__interaction__handler_8h" ],
    [ "canvas_menu.cc", "d6/dc2/canvas__menu_8cc.html", "d6/dc2/canvas__menu_8cc" ],
    [ "canvas_menu.h", "d0/d65/canvas__menu_8h.html", "d0/d65/canvas__menu_8h" ],
    [ "canvas_menu_builder.cc", "d6/dcb/canvas__menu__builder_8cc.html", null ],
    [ "canvas_menu_builder.h", "d1/d7d/canvas__menu__builder_8h.html", "d1/d7d/canvas__menu__builder_8h" ],
    [ "canvas_modals.cc", "d1/de8/canvas__modals_8cc.html", "d1/de8/canvas__modals_8cc" ],
    [ "canvas_modals.h", "d0/d07/canvas__modals_8h.html", "d0/d07/canvas__modals_8h" ],
    [ "canvas_performance_integration.cc", "d6/d44/canvas__performance__integration_8cc.html", null ],
    [ "canvas_performance_integration.h", "d5/d75/canvas__performance__integration_8h.html", "d5/d75/canvas__performance__integration_8h" ],
    [ "canvas_popup.cc", "d4/d63/canvas__popup_8cc.html", null ],
    [ "canvas_popup.h", "da/d69/canvas__popup_8h.html", "da/d69/canvas__popup_8h" ],
    [ "canvas_rendering.cc", "db/da9/canvas__rendering_8cc.html", "db/da9/canvas__rendering_8cc" ],
    [ "canvas_rendering.h", "d6/db2/canvas__rendering_8h.html", "d6/db2/canvas__rendering_8h" ],
    [ "canvas_state.h", "d0/d9f/canvas__state_8h.html", "d0/d9f/canvas__state_8h" ],
    [ "canvas_usage_tracker.cc", "da/d11/canvas__usage__tracker_8cc.html", null ],
    [ "canvas_usage_tracker.h", "d3/dbf/canvas__usage__tracker_8h.html", "d3/dbf/canvas__usage__tracker_8h" ],
    [ "canvas_utils.cc", "dd/df4/canvas__utils_8cc.html", "dd/df4/canvas__utils_8cc" ],
    [ "canvas_utils.h", "d1/d39/canvas__utils_8h.html", "d1/d39/canvas__utils_8h" ]
];