yaze: src/ext/extension.h File Reference
extension.h File Reference
#include "yaze.h"
Classes
struct yaze_extension
Extension interface for Yaze.
Typedefs
typedef void(* yaze_initialize_func) (yaze_editor_context *context)
typedef void(* yaze_cleanup_func) (void)
typedef void(* yaze_extend_ui_func) (yaze_editor_context *context)
typedef void(* yaze_manipulate_rom_func) (z3_rom *rom)
typedef void(* yaze_command_func) (void)
typedef void(* yaze_event_hook_func) (void)
typedef struct yaze_extension yaze_extension
Extension interface for Yaze.
Enumerations
enum yaze_event_type { YAZE_EVENT_ROM_LOADED , YAZE_EVENT_ROM_SAVED , YAZE_EVENT_SPRITE_MODIFIED , YAZE_EVENT_PALETTE_CHANGED }
Functions
yaze_extension * get_yaze_extension ()
Get the extension interface.
void yaze_load_c_extension (const char *extension_path, yaze_editor_context *context)
Load a C extension.
void yaze_load_py_extension (const char *script_path)
Load a Python extension.
void yaze_cleanup_extension ()
Clean up the extension.
Typedef Documentation
yaze_initialize_func
typedef void(* yaze_initialize_func) (yaze_editor_context *context)
Definition at line 10 of file extension.h.
yaze_cleanup_func
typedef void(* yaze_cleanup_func) (void)
Definition at line 11 of file extension.h.
yaze_extend_ui_func
typedef void(* yaze_extend_ui_func) (yaze_editor_context *context)
Definition at line 12 of file extension.h.
yaze_manipulate_rom_func
typedef void(* yaze_manipulate_rom_func) (z3_rom *rom)
Definition at line 13 of file extension.h.
yaze_command_func
typedef void(* yaze_command_func) (void)
Definition at line 14 of file extension.h.
yaze_event_hook_func
typedef void(* yaze_event_hook_func) (void)
Definition at line 15 of file extension.h.
yaze_extension
typedef struct yaze_extension yaze_extension
Extension interface for Yaze.
Yaze extensions can be written in C or Python.
Enumeration Type Documentation
yaze_event_type
enum yaze_event_type
Enumerator
YAZE_EVENT_ROM_LOADED
YAZE_EVENT_ROM_SAVED
YAZE_EVENT_SPRITE_MODIFIED
YAZE_EVENT_PALETTE_CHANGED
Definition at line 17 of file extension.h.
Function Documentation
get_yaze_extension()
yaze_extension * get_yaze_extension ()
Get the extension interface.
Definition at line 10 of file extension.cc.
References my_extension_cleanup(), my_extension_extend_ui(), my_extension_initialize(), my_extension_manipulate_rom(), my_extension_register_commands(), my_extension_register_custom_tools(), and my_extension_register_event_hooks().
yaze_load_c_extension()
void yaze_load_c_extension (const char * extension_path, yaze_editor_context * context)
Load a C extension.
Definition at line 12 of file extension.cc.
References yaze_extension::initialize.
yaze_load_py_extension()
void yaze_load_py_extension (const char * script_path)
Load a Python extension.
Todo
Use Boost.Python to load Python extensions
Definition at line 42 of file extension.cc.
yaze_cleanup_extension()
void yaze_cleanup_extension ()
Clean up the extension.
Definition at line 46 of file extension.cc.
References yaze_extension::cleanup.