yaze: src/incl/extension_sample.c File Reference
extension_sample.c File Reference
#include <stdio.h>
#include "incl/extension.h"
#include "yaze.h"
Functions
void my_extension_initialize (yaze_editor_context *context)
void my_extension_cleanup (void)
void my_extension_extend_ui (yaze_editor_context *context)
void my_extension_manipulate_rom (z3_rom *rom)
void my_extension_register_commands (void)
void my_extension_handle_file_format (void)
void my_extension_register_event_hooks (yaze_event_type event, yaze_event_hook_func hook)
void my_extension_register_custom_tools (void)
yaze_extension * get_yaze_extension (void)
Function Documentation
my_extension_initialize()
void my_extension_initialize (yaze_editor_context * context)
Definition at line 6 of file extension_sample.c.
Referenced by get_yaze_extension().
my_extension_cleanup()
void my_extension_cleanup (void)
Definition at line 10 of file extension_sample.c.
Referenced by get_yaze_extension().
my_extension_extend_ui()
void my_extension_extend_ui (yaze_editor_context * context)
Definition at line 12 of file extension_sample.c.
Referenced by get_yaze_extension().
my_extension_manipulate_rom()
void my_extension_manipulate_rom (z3_rom * rom)
Definition at line 16 of file extension_sample.c.
Referenced by get_yaze_extension().
my_extension_register_commands()
void my_extension_register_commands (void)
Definition at line 20 of file extension_sample.c.
Referenced by get_yaze_extension().
my_extension_handle_file_format()
void my_extension_handle_file_format (void)
Definition at line 24 of file extension_sample.c.
my_extension_register_event_hooks()
void my_extension_register_event_hooks (yaze_event_type event, yaze_event_hook_func hook)
Definition at line 28 of file extension_sample.c.
Referenced by get_yaze_extension().
my_extension_register_custom_tools()
void my_extension_register_custom_tools (void)
Definition at line 33 of file extension_sample.c.
Referenced by get_yaze_extension().
get_yaze_extension()
yaze_extension * get_yaze_extension (void)
Definition at line 37 of file extension_sample.c.
References my_extension_cleanup(), my_extension_extend_ui(), my_extension_initialize(), my_extension_manipulate_rom(), my_extension_register_commands(), my_extension_register_custom_tools(), and my_extension_register_event_hooks().