var hierarchy =
[
    [ "yaze::app::gui::zeml::Action", "structyaze_1_1app_1_1gui_1_1zeml_1_1Action.html", null ],
    [ "yaze::app::editor::zsprite::AnimationGroup", "structyaze_1_1app_1_1editor_1_1zsprite_1_1AnimationGroup.html", null ],
    [ "AppDelegate", "classAppDelegate.html", null ],
    [ "AppViewController", "classAppViewController.html", null ],
    [ "yaze::app::emu::audio::Apu", "classyaze_1_1app_1_1emu_1_1audio_1_1Apu.html", null ],
    [ "yaze::app::emu::audio::ApuCallbacks", "structyaze_1_1app_1_1emu_1_1audio_1_1ApuCallbacks.html", null ],
    [ "yaze::app::emu::AsmParser", "classyaze_1_1app_1_1emu_1_1AsmParser.html", null ],
    [ "yaze::app::gui::AssetObject", "structyaze_1_1app_1_1gui_1_1AssetObject.html", [
      [ "yaze::app::gui::DungeonAsset", "structyaze_1_1app_1_1gui_1_1DungeonAsset.html", null ],
      [ "yaze::app::gui::OverworldAsset", "structyaze_1_1app_1_1gui_1_1OverworldAsset.html", null ],
      [ "yaze::app::gui::SpriteAsset", "structyaze_1_1app_1_1gui_1_1SpriteAsset.html", null ],
      [ "yaze::app::gui::UnsortedAsset", "structyaze_1_1app_1_1gui_1_1UnsortedAsset.html", null ]
    ] ],
    [ "yaze::app::emu::audio::AudioRam", "classyaze_1_1app_1_1emu_1_1audio_1_1AudioRam.html", [
      [ "yaze::app::emu::audio::AudioRamImpl", "classyaze_1_1app_1_1emu_1_1audio_1_1AudioRamImpl.html", null ],
      [ "yaze::test::emu::MockAudioRam", "classyaze_1_1test_1_1emu_1_1MockAudioRam.html", null ]
    ] ],
    [ "yaze::app::emu::video::BackgroundLayer", "structyaze_1_1app_1_1emu_1_1video_1_1BackgroundLayer.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::BGHOFS", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1BGHOFS.html", null ],
    [ "yaze::app::emu::video::BgLayer", "structyaze_1_1app_1_1emu_1_1video_1_1BgLayer.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::BGMODE", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1BGMODE.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::BGNBA", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1BGNBA.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::BGSC", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1BGSC.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::BGVOFS", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1BGVOFS.html", null ],
    [ "yaze::app::gfx::Bitmap", "classyaze_1_1app_1_1gfx_1_1Bitmap.html", null ],
    [ "yaze::app::gui::BitmapViewer", "classyaze_1_1app_1_1gui_1_1BitmapViewer.html", null ],
    [ "yaze::app::emu::Emulator::Bookmark", "structyaze_1_1app_1_1emu_1_1Emulator_1_1Bookmark.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::CGADD", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1CGADD.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::CGADSUB", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1CGADSUB.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::CGDATA", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1CGDATA.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::CGDATAREAD", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1CGDATAREAD.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::CGWSEL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1CGWSEL.html", null ],
    [ "yaze::app::gfx::scad_format::CgxHeader", "structyaze_1_1app_1_1gfx_1_1scad__format_1_1CgxHeader.html", null ],
    [ "yaze::app::emu::video::CharacterLocation", "structyaze_1_1app_1_1emu_1_1video_1_1CharacterLocation.html", null ],
    [ "yaze::app::zelda3::dungeon::ChestData", "structyaze_1_1app_1_1zelda3_1_1dungeon_1_1ChestData.html", null ],
    [ "yaze::app::emu::Clock", "classyaze_1_1app_1_1emu_1_1Clock.html", [
      [ "yaze::app::emu::ClockImpl", "classyaze_1_1app_1_1emu_1_1ClockImpl.html", null ],
      [ "yaze::app::emu::memory::MockClock", "classyaze_1_1app_1_1emu_1_1memory_1_1MockClock.html", null ]
    ] ],
    [ "yaze::app::emu::video::PpuRegisters::COLDATA", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1COLDATA.html", null ],
    [ "yaze::app::emu::video::Color", "structyaze_1_1app_1_1emu_1_1video_1_1Color.html", null ],
    [ "yaze::cli::ColorModifier", "classyaze_1_1cli_1_1ColorModifier.html", null ],
    [ "yaze::app::editor::Command", "classyaze_1_1app_1_1editor_1_1Command.html", null ],
    [ "yaze::cli::CommandHandler", "classyaze_1_1cli_1_1CommandHandler.html", [
      [ "yaze::cli::ApplyPatch", "classyaze_1_1cli_1_1ApplyPatch.html", null ],
      [ "yaze::cli::AsarPatch", "classyaze_1_1cli_1_1AsarPatch.html", null ],
      [ "yaze::cli::Backup", "classyaze_1_1cli_1_1Backup.html", null ],
      [ "yaze::cli::Compress", "classyaze_1_1cli_1_1Compress.html", null ],
      [ "yaze::cli::CreatePatch", "classyaze_1_1cli_1_1CreatePatch.html", null ],
      [ "yaze::cli::Decompress", "classyaze_1_1cli_1_1Decompress.html", null ],
      [ "yaze::cli::Emulator", "classyaze_1_1cli_1_1Emulator.html", null ],
      [ "yaze::cli::Expand", "classyaze_1_1cli_1_1Expand.html", null ],
      [ "yaze::cli::Open", "classyaze_1_1cli_1_1Open.html", null ],
      [ "yaze::cli::PcToSnes", "classyaze_1_1cli_1_1PcToSnes.html", null ],
      [ "yaze::cli::ReadFromRom", "classyaze_1_1cli_1_1ReadFromRom.html", null ],
      [ "yaze::cli::SnesToPc", "classyaze_1_1cli_1_1SnesToPc.html", null ],
      [ "yaze::cli::Tile16Transfer", "classyaze_1_1cli_1_1Tile16Transfer.html", null ]
    ] ],
    [ "yaze::app::editor::CommandManager", "classyaze_1_1app_1_1editor_1_1CommandManager.html", null ],
    [ "yaze::cli::Commands", "structyaze_1_1cli_1_1Commands.html", null ],
    [ "yaze::app::gfx::lc_lz2::CompressionCommand", "structyaze_1_1app_1_1gfx_1_1lc__lz2_1_1CompressionCommand.html", null ],
    [ "yaze::app::gfx::lc_lz2::CompressionContext", "structyaze_1_1app_1_1gfx_1_1lc__lz2_1_1CompressionContext.html", null ],
    [ "yaze::app::gfx::lc_lz2::CompressionPiece", "structyaze_1_1app_1_1gfx_1_1lc__lz2_1_1CompressionPiece.html", null ],
    [ "yaze::app::emu::video::CounterIrqNmiRegisters", "structyaze_1_1app_1_1emu_1_1video_1_1CounterIrqNmiRegisters.html", null ],
    [ "yaze::app::emu::memory::CpuCallbacks", "structyaze_1_1app_1_1emu_1_1memory_1_1CpuCallbacks.html", null ],
    [ "yaze::app::emu::Debugger", "classyaze_1_1app_1_1emu_1_1Debugger.html", null ],
    [ "yaze::app::editor::MessageEditor::DictionaryEntry", "structyaze_1_1app_1_1editor_1_1MessageEditor_1_1DictionaryEntry.html", null ],
    [ "yaze::app::emu::memory::DmaChannel", "structyaze_1_1app_1_1emu_1_1memory_1_1DmaChannel.html", null ],
    [ "yaze::app::emu::video::DmaRegisters", "structyaze_1_1app_1_1emu_1_1video_1_1DmaRegisters.html", null ],
    [ "yaze::app::emu::audio::Dsp", "classyaze_1_1app_1_1emu_1_1audio_1_1Dsp.html", null ],
    [ "yaze::app::emu::audio::DspChannel", "structyaze_1_1app_1_1emu_1_1audio_1_1DspChannel.html", null ],
    [ "yaze::app::zelda3::dungeon::DungeonDestination", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1DungeonDestination.html", null ],
    [ "yaze::app::zelda3::screen::DungeonMap", "classyaze_1_1app_1_1zelda3_1_1screen_1_1DungeonMap.html", null ],
    [ "yaze::app::editor::Editor", "classyaze_1_1app_1_1editor_1_1Editor.html", [
      [ "yaze::app::editor::AssemblyEditor", "classyaze_1_1app_1_1editor_1_1AssemblyEditor.html", null ],
      [ "yaze::app::editor::DungeonEditor", "classyaze_1_1app_1_1editor_1_1DungeonEditor.html", null ],
      [ "yaze::app::editor::GraphicsEditor", "classyaze_1_1app_1_1editor_1_1GraphicsEditor.html", null ],
      [ "yaze::app::editor::MessageEditor", "classyaze_1_1app_1_1editor_1_1MessageEditor.html", null ],
      [ "yaze::app::editor::MusicEditor", "classyaze_1_1app_1_1editor_1_1MusicEditor.html", null ],
      [ "yaze::app::editor::OverworldEditor", "classyaze_1_1app_1_1editor_1_1OverworldEditor.html", null ],
      [ "yaze::app::editor::PaletteEditor", "classyaze_1_1app_1_1editor_1_1PaletteEditor.html", null ],
      [ "yaze::app::editor::ScreenEditor", "classyaze_1_1app_1_1editor_1_1ScreenEditor.html", null ],
      [ "yaze::app::editor::SettingsEditor", "classyaze_1_1app_1_1editor_1_1SettingsEditor.html", null ],
      [ "yaze::app::editor::SpriteEditor", "classyaze_1_1app_1_1editor_1_1SpriteEditor.html", null ],
      [ "yaze::test::integration::TestEditor", "classyaze_1_1test_1_1integration_1_1TestEditor.html", null ]
    ] ],
    [ "yaze::app::editor::EntranceContext", "classyaze_1_1app_1_1editor_1_1EntranceContext.html", [
      [ "yaze::app::editor::OverworldEditor", "classyaze_1_1app_1_1editor_1_1OverworldEditor.html", null ]
    ] ],
    [ "yaze::app::editor::ExampleAppPropertyEditor", "structyaze_1_1app_1_1editor_1_1ExampleAppPropertyEditor.html", null ],
    [ "yaze::app::editor::ExampleMemberInfo", "structyaze_1_1app_1_1editor_1_1ExampleMemberInfo.html", null ],
    [ "yaze::app::editor::ExampleTreeNode", "structyaze_1_1app_1_1editor_1_1ExampleTreeNode.html", null ],
    [ "yaze::app::core::ExperimentFlags", "classyaze_1_1app_1_1core_1_1ExperimentFlags.html", [
      [ "yaze::app::Project", "structyaze_1_1app_1_1Project.html", null ],
      [ "yaze::app::Rom", "classyaze_1_1app_1_1Rom.html", null ],
      [ "yaze::app::core::Controller", "classyaze_1_1app_1_1core_1_1Controller.html", null ],
      [ "yaze::app::core::Renderer", "classyaze_1_1app_1_1core_1_1Renderer.html", null ],
      [ "yaze::app::editor::DungeonEditor", "classyaze_1_1app_1_1editor_1_1DungeonEditor.html", null ],
      [ "yaze::app::editor::EditorManager", "classyaze_1_1app_1_1editor_1_1EditorManager.html", null ],
      [ "yaze::app::editor::FlagsMenu", "structyaze_1_1app_1_1editor_1_1FlagsMenu.html", null ],
      [ "yaze::app::editor::OverworldEditor", "classyaze_1_1app_1_1editor_1_1OverworldEditor.html", null ],
      [ "yaze::app::emu::Cpu", "classyaze_1_1app_1_1emu_1_1Cpu.html", null ],
      [ "yaze::app::zelda3::dungeon::Room", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1Room.html", null ],
      [ "yaze::app::zelda3::overworld::Overworld", "classyaze_1_1app_1_1zelda3_1_1overworld_1_1Overworld.html", null ]
    ] ],
    [ "yaze::app::editor::ExtensionManager", "classyaze_1_1app_1_1editor_1_1ExtensionManager.html", null ],
    [ "yaze::app::core::FileDialogWrapper", "classyaze_1_1app_1_1core_1_1FileDialogWrapper.html", null ],
    [ "yaze::app::core::ExperimentFlags::Flags", "structyaze_1_1app_1_1core_1_1ExperimentFlags_1_1Flags.html", null ],
    [ "yaze::app::emu::audio::Spc700::Flags", "structyaze_1_1app_1_1emu_1_1audio_1_1Spc700_1_1Flags.html", null ],
    [ "yaze::app::core::FolderItem", "structyaze_1_1app_1_1core_1_1FolderItem.html", null ],
    [ "yaze::app::editor::context::GfxContext", "classyaze_1_1app_1_1editor_1_1context_1_1GfxContext.html", [
      [ "yaze::app::editor::EditorManager", "classyaze_1_1app_1_1editor_1_1EditorManager.html", null ],
      [ "yaze::app::editor::OverworldEditor", "classyaze_1_1app_1_1editor_1_1OverworldEditor.html", null ],
      [ "yaze::app::editor::Tile16Editor", "classyaze_1_1app_1_1editor_1_1Tile16Editor.html", null ],
      [ "yaze::app::zelda3::overworld::OverworldMap", "classyaze_1_1app_1_1zelda3_1_1overworld_1_1OverworldMap.html", null ]
    ] ],
    [ "yaze::app::gui::GfxSheetAssetBrowser", "structyaze_1_1app_1_1gui_1_1GfxSheetAssetBrowser.html", null ],
    [ "yaze::app::core::GuiTestable", "classyaze_1_1app_1_1core_1_1GuiTestable.html", null ],
    [ "yaze::app::core::ImGuiIdIssuer", "classyaze_1_1app_1_1core_1_1ImGuiIdIssuer.html", null ],
    [ "ImGuiSelectionBasicStorage", null, [
      [ "yaze::app::gui::ExampleSelectionWithDeletion", "structyaze_1_1app_1_1gui_1_1ExampleSelectionWithDeletion.html", null ]
    ] ],
    [ "yaze::app::emu::video::PpuRegisters::INIDISP", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1INIDISP.html", null ],
    [ "yaze::app::emu::Input", "structyaze_1_1app_1_1emu_1_1Input.html", null ],
    [ "yaze::app::emu::InstructionEntry", "classyaze_1_1app_1_1emu_1_1InstructionEntry.html", null ],
    [ "yaze::app::gfx::Tilesheet::InternalTile16", "structyaze_1_1app_1_1gfx_1_1Tilesheet_1_1InternalTile16.html", null ],
    [ "yaze::app::emu::video::JoypadRegisters", "structyaze_1_1app_1_1emu_1_1video_1_1JoypadRegisters.html", null ],
    [ "yaze::app::emu::video::Layer", "structyaze_1_1app_1_1emu_1_1video_1_1Layer.html", null ],
    [ "yaze::app::emu::Loggable", "classyaze_1_1app_1_1emu_1_1Loggable.html", [
      [ "yaze::app::emu::Cpu", "classyaze_1_1app_1_1emu_1_1Cpu.html", null ],
      [ "yaze::app::emu::memory::MemoryImpl", "classyaze_1_1app_1_1emu_1_1memory_1_1MemoryImpl.html", null ]
    ] ],
    [ "yaze::app::core::Logger", "classyaze_1_1app_1_1core_1_1Logger.html", null ],
    [ "yaze::app::emu::Logger", "classyaze_1_1app_1_1emu_1_1Logger.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::M7A", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1M7A.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::M7B", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1M7B.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::M7C", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1M7C.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::M7D", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1M7D.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::M7SEL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1M7SEL.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::M7X", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1M7X.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::M7Y", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1M7Y.html", null ],
    [ "yaze::app::emu::video::MainSubScreenDesignation", "structyaze_1_1app_1_1emu_1_1video_1_1MainSubScreenDesignation.html", null ],
    [ "yaze::app::zelda3::overworld::MapData", "structyaze_1_1app_1_1zelda3_1_1overworld_1_1MapData.html", null ],
    [ "yaze::app::emu::video::MaskLogicSettings", "structyaze_1_1app_1_1emu_1_1video_1_1MaskLogicSettings.html", null ],
    [ "yaze::app::emu::memory::Memory", "classyaze_1_1app_1_1emu_1_1memory_1_1Memory.html", [
      [ "yaze::app::emu::memory::MemoryImpl", "classyaze_1_1app_1_1emu_1_1memory_1_1MemoryImpl.html", null ],
      [ "yaze::app::emu::memory::MockMemory", "classyaze_1_1app_1_1emu_1_1memory_1_1MockMemory.html", null ]
    ] ],
    [ "yaze::app::editor::MessageData", "structyaze_1_1app_1_1editor_1_1MessageData.html", null ],
    [ "yaze::app::emu::MnemonicMode", "structyaze_1_1app_1_1emu_1_1MnemonicMode.html", null ],
    [ "yaze::app::emu::MnemonicModeHash", "structyaze_1_1app_1_1emu_1_1MnemonicModeHash.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::Mosaic", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1Mosaic.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::MPYH", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1MPYH.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::MPYL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1MPYL.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::MPYM", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1MPYM.html", null ],
    [ "yaze::app::gui::MultiSelectWithClipper", "structyaze_1_1app_1_1gui_1_1MultiSelectWithClipper.html", null ],
    [ "yaze::app::gui::zeml::Node", "structyaze_1_1app_1_1gui_1_1zeml_1_1Node.html", null ],
    [ "yaze::app::core::NotifyValue< T >", "classyaze_1_1app_1_1core_1_1NotifyValue.html", null ],
    [ "yaze::app::core::NotifyValue< uint32_t >", "classyaze_1_1app_1_1core_1_1NotifyValue.html", null ],
    [ "yaze::app::core::NotifyValue< uint8_t >", "classyaze_1_1app_1_1core_1_1NotifyValue.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::OAMADDH", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1OAMADDH.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::OAMADDL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1OAMADDL.html", null ],
    [ "yaze::app::emu::video::OAMAddress", "structyaze_1_1app_1_1emu_1_1video_1_1OAMAddress.html", null ],
    [ "yaze::app::editor::SpriteEditor::OAMConfig", "structyaze_1_1app_1_1editor_1_1SpriteEditor_1_1OAMConfig.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::OAMDATA", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1OAMDATA.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::OAMDATAREAD", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1OAMDATAREAD.html", null ],
    [ "yaze::app::emu::video::OAMSize", "structyaze_1_1app_1_1emu_1_1video_1_1OAMSize.html", null ],
    [ "yaze::app::editor::zsprite::OamTile", "structyaze_1_1app_1_1editor_1_1zsprite_1_1OamTile.html", null ],
    [ "yaze::app::gfx::OamTile", "classyaze_1_1app_1_1gfx_1_1OamTile.html", null ],
    [ "yaze::app::zelda3::dungeon::object_door", "structyaze_1_1app_1_1zelda3_1_1dungeon_1_1object__door.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::OBJSEL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1OBJSEL.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::OPHCT", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1OPHCT.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::OPVCT", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1OPVCT.html", null ],
    [ "yaze::app::core::ExperimentFlags::Flags::Overworld", "structyaze_1_1app_1_1core_1_1ExperimentFlags_1_1Flags_1_1Overworld.html", null ],
    [ "yaze::app::zelda3::OverworldEntity", "classyaze_1_1app_1_1zelda3_1_1OverworldEntity.html", [
      [ "yaze::app::zelda3::Sprite", "classyaze_1_1app_1_1zelda3_1_1Sprite.html", null ],
      [ "yaze::app::zelda3::overworld::OverworldEntrance", "classyaze_1_1app_1_1zelda3_1_1overworld_1_1OverworldEntrance.html", null ],
      [ "yaze::app::zelda3::overworld::OverworldExit", "classyaze_1_1app_1_1zelda3_1_1overworld_1_1OverworldExit.html", null ],
      [ "yaze::app::zelda3::overworld::OverworldItem", "classyaze_1_1app_1_1zelda3_1_1overworld_1_1OverworldItem.html", null ]
    ] ],
    [ "yaze::app::zelda3::OWMapTiles", "structyaze_1_1app_1_1zelda3_1_1OWMapTiles.html", null ],
    [ "yaze::app::editor::palette_internal::PaletteChange", "structyaze_1_1app_1_1editor_1_1palette__internal_1_1PaletteChange.html", null ],
    [ "yaze::app::editor::palette_internal::PaletteEditorHistory", "classyaze_1_1app_1_1editor_1_1palette__internal_1_1PaletteEditorHistory.html", null ],
    [ "yaze::app::gfx::PaletteGroup", "structyaze_1_1app_1_1gfx_1_1PaletteGroup.html", null ],
    [ "yaze::app::gfx::PaletteGroupMap", "structyaze_1_1app_1_1gfx_1_1PaletteGroupMap.html", null ],
    [ "yaze::app::gfx::Paletteset", "structyaze_1_1app_1_1gfx_1_1Paletteset.html", null ],
    [ "yaze::app::editor::ParsedElement", "structyaze_1_1app_1_1editor_1_1ParsedElement.html", null ],
    [ "yaze::app::emu::video::PpuInterface", "classyaze_1_1app_1_1emu_1_1video_1_1PpuInterface.html", [
      [ "yaze::test::emu::MockPpu", "classyaze_1_1test_1_1emu_1_1MockPpu.html", null ]
    ] ],
    [ "yaze::app::zelda3::dungeon::PseudoVram", "structyaze_1_1app_1_1zelda3_1_1dungeon_1_1PseudoVram.html", null ],
    [ "yaze::app::editor::RecentFilesManager", "classyaze_1_1app_1_1editor_1_1RecentFilesManager.html", null ],
    [ "yaze::app::core::ResourceLabelManager", "structyaze_1_1app_1_1core_1_1ResourceLabelManager.html", null ],
    [ "yaze::app::core::ResourceLabelManager::ResourceType", "structyaze_1_1app_1_1core_1_1ResourceLabelManager_1_1ResourceType.html", null ],
    [ "yaze::app::emu::memory::RomInfo", "classyaze_1_1app_1_1emu_1_1memory_1_1RomInfo.html", null ],
    [ "yaze::app::zelda3::dungeon::RoomEntrance", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1RoomEntrance.html", null ],
    [ "yaze::app::emu::video::ScreenDisplay", "structyaze_1_1app_1_1emu_1_1video_1_1ScreenDisplay.html", null ],
    [ "yaze::app::emu::video::ScreenMode", "structyaze_1_1app_1_1emu_1_1video_1_1ScreenMode.html", null ],
    [ "yaze::app::emu::video::ScrollRegister", "structyaze_1_1app_1_1emu_1_1video_1_1ScrollRegister.html", null ],
    [ "yaze::app::core::SDL_Deleter", "structyaze_1_1app_1_1core_1_1SDL__Deleter.html", null ],
    [ "yaze::app::core::SDL_Surface_Deleter", "structyaze_1_1app_1_1core_1_1SDL__Surface__Deleter.html", null ],
    [ "yaze::app::core::SDL_Texture_Deleter", "structyaze_1_1app_1_1core_1_1SDL__Texture__Deleter.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::SETINI", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1SETINI.html", null ],
    [ "yaze::app::SharedRom", "classyaze_1_1app_1_1SharedRom.html", [
      [ "yaze::app::editor::DungeonEditor", "classyaze_1_1app_1_1editor_1_1DungeonEditor.html", null ],
      [ "yaze::app::editor::EditorManager", "classyaze_1_1app_1_1editor_1_1EditorManager.html", null ],
      [ "yaze::app::editor::GfxGroupEditor", "classyaze_1_1app_1_1editor_1_1GfxGroupEditor.html", null ],
      [ "yaze::app::editor::GraphicsEditor", "classyaze_1_1app_1_1editor_1_1GraphicsEditor.html", null ],
      [ "yaze::app::editor::MemoryEditorWithDiffChecker", "structyaze_1_1app_1_1editor_1_1MemoryEditorWithDiffChecker.html", null ],
      [ "yaze::app::editor::MessageEditor", "classyaze_1_1app_1_1editor_1_1MessageEditor.html", null ],
      [ "yaze::app::editor::MusicEditor", "classyaze_1_1app_1_1editor_1_1MusicEditor.html", null ],
      [ "yaze::app::editor::OverworldEditor", "classyaze_1_1app_1_1editor_1_1OverworldEditor.html", null ],
      [ "yaze::app::editor::PaletteEditor", "classyaze_1_1app_1_1editor_1_1PaletteEditor.html", null ],
      [ "yaze::app::editor::ScreenEditor", "classyaze_1_1app_1_1editor_1_1ScreenEditor.html", null ],
      [ "yaze::app::editor::SpriteEditor", "classyaze_1_1app_1_1editor_1_1SpriteEditor.html", null ],
      [ "yaze::app::editor::Tile16Editor", "classyaze_1_1app_1_1editor_1_1Tile16Editor.html", null ],
      [ "yaze::app::emu::Emulator", "classyaze_1_1app_1_1emu_1_1Emulator.html", null ],
      [ "yaze::app::emu::video::Ppu", "classyaze_1_1app_1_1emu_1_1video_1_1Ppu.html", null ],
      [ "yaze::app::gui::Canvas", "classyaze_1_1app_1_1gui_1_1Canvas.html", null ],
      [ "yaze::app::zelda3::dungeon::DungeonObjectRenderer", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1DungeonObjectRenderer.html", null ],
      [ "yaze::app::zelda3::dungeon::Room", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1Room.html", null ],
      [ "yaze::app::zelda3::dungeon::RoomObject", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1RoomObject.html", [
        [ "yaze::app::zelda3::dungeon::Subtype1", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1Subtype1.html", null ],
        [ "yaze::app::zelda3::dungeon::Subtype2", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1Subtype2.html", null ],
        [ "yaze::app::zelda3::dungeon::Subtype3", "classyaze_1_1app_1_1zelda3_1_1dungeon_1_1Subtype3.html", null ]
      ] ],
      [ "yaze::app::zelda3::overworld::Overworld", "classyaze_1_1app_1_1zelda3_1_1overworld_1_1Overworld.html", null ],
      [ "yaze::app::zelda3::screen::Inventory", "classyaze_1_1app_1_1zelda3_1_1screen_1_1Inventory.html", null ]
    ] ],
    [ "yaze::app::emu::video::PpuRegisters::SLHV", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1SLHV.html", null ],
    [ "yaze::app::emu::SNES", "classyaze_1_1app_1_1emu_1_1SNES.html", null ],
    [ "snes_color", "structsnes__color.html", null ],
    [ "snes_palette", "structsnes__palette.html", null ],
    [ "yaze::app::gfx::SnesColor", "classyaze_1_1app_1_1gfx_1_1SnesColor.html", null ],
    [ "yaze::app::gfx::SnesPalette", "classyaze_1_1app_1_1gfx_1_1SnesPalette.html", null ],
    [ "yaze::app::emu::audio::Spc700", "classyaze_1_1app_1_1emu_1_1audio_1_1Spc700.html", null ],
    [ "yaze::app::zelda3::SpriteAction", "classyaze_1_1app_1_1zelda3_1_1SpriteAction.html", null ],
    [ "yaze::app::emu::video::SpriteAttributes", "structyaze_1_1app_1_1emu_1_1video_1_1SpriteAttributes.html", null ],
    [ "yaze::app::zelda3::SpriteBuilder", "classyaze_1_1app_1_1zelda3_1_1SpriteBuilder.html", null ],
    [ "yaze::app::zelda3::SpriteInstruction", "classyaze_1_1app_1_1zelda3_1_1SpriteInstruction.html", null ],
    [ "yaze::app::editor::SpriteItem", "structyaze_1_1app_1_1editor_1_1SpriteItem.html", null ],
    [ "yaze::app::editor::zsprite::SpriteProperty", "structyaze_1_1app_1_1editor_1_1zsprite_1_1SpriteProperty.html", null ],
    [ "yaze::app::zelda3::dungeon::StaircaseRooms", "structyaze_1_1app_1_1zelda3_1_1dungeon_1_1StaircaseRooms.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::STAT77", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1STAT77.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::STAT78", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1STAT78.html", null ],
    [ "yaze::app::editor::zsprite::SubEditor", "structyaze_1_1app_1_1editor_1_1zsprite_1_1SubEditor.html", null ],
    [ "yaze::app::zelda3::dungeon::SubtypeInfo", "structyaze_1_1app_1_1zelda3_1_1dungeon_1_1SubtypeInfo.html", null ],
    [ "testing::Test", null, [
      [ "yaze::test::RomTest", "classyaze_1_1test_1_1RomTest.html", null ],
      [ "yaze::test::emu::CpuTest", "classyaze_1_1test_1_1emu_1_1CpuTest.html", null ],
      [ "yaze::test::emu::PpuTest", "classyaze_1_1test_1_1emu_1_1PpuTest.html", null ],
      [ "yaze::test::emu::Spc700Test", "classyaze_1_1test_1_1emu_1_1Spc700Test.html", null ],
      [ "yaze::test::zelda3::SpriteBuilderTest", "classyaze_1_1test_1_1zelda3_1_1SpriteBuilderTest.html", null ]
    ] ],
    [ "yaze::app::editor::MessageEditor::TextBox", "structyaze_1_1app_1_1editor_1_1MessageEditor_1_1TextBox.html", null ],
    [ "yaze::app::editor::TextElement", "structyaze_1_1app_1_1editor_1_1TextElement.html", null ],
    [ "yaze::app::emu::video::Tile", "structyaze_1_1app_1_1emu_1_1video_1_1Tile.html", null ],
    [ "yaze::app::zelda3::dungeon::Tile", "structyaze_1_1app_1_1zelda3_1_1dungeon_1_1Tile.html", null ],
    [ "yaze::app::gfx::Tile16", "classyaze_1_1app_1_1gfx_1_1Tile16.html", null ],
    [ "yaze::app::gfx::Tile32", "classyaze_1_1app_1_1gfx_1_1Tile32.html", null ],
    [ "yaze::app::gfx::tile8", "structyaze_1_1app_1_1gfx_1_1tile8.html", null ],
    [ "yaze::app::gfx::TileInfo", "classyaze_1_1app_1_1gfx_1_1TileInfo.html", null ],
    [ "yaze::app::emu::video::Tilemap", "structyaze_1_1app_1_1emu_1_1video_1_1Tilemap.html", null ],
    [ "yaze::app::emu::video::TilemapEntry", "structyaze_1_1app_1_1emu_1_1video_1_1TilemapEntry.html", null ],
    [ "yaze::app::emu::video::TileMapLocation", "structyaze_1_1app_1_1emu_1_1video_1_1TileMapLocation.html", null ],
    [ "yaze::app::gfx::Tilesheet", "classyaze_1_1app_1_1gfx_1_1Tilesheet.html", null ],
    [ "yaze::app::emu::audio::Timer", "structyaze_1_1app_1_1emu_1_1audio_1_1Timer.html", null ],
    [ "yaze::app::zelda3::screen::TitleScreen", "classyaze_1_1app_1_1zelda3_1_1screen_1_1TitleScreen.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::TM", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1TM.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::TMW", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1TMW.html", null ],
    [ "yaze::app::gui::zeml::Token", "structyaze_1_1app_1_1gui_1_1zeml_1_1Token.html", null ],
    [ "yaze::app::zelda3::music::Tracker", "classyaze_1_1app_1_1zelda3_1_1music_1_1Tracker.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::TS", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1TS.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::TSW", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1TSW.html", null ],
    [ "yaze::app::editor::zsprite::UserRoutine", "structyaze_1_1app_1_1editor_1_1zsprite_1_1UserRoutine.html", null ],
    [ "yaze::app::VersionConstants", "structyaze_1_1app_1_1VersionConstants.html", null ],
    [ "yaze::app::emu::video::VideoPortControl", "structyaze_1_1app_1_1emu_1_1video_1_1VideoPortControl.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::VMADDH", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1VMADDH.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::VMADDL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1VMADDL.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::VMAIN", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1VMAIN.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::VMDATA", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1VMDATA.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::VMDATAHREAD", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1VMDATAHREAD.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::VMDATALREAD", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1VMDATALREAD.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::W12SEL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1W12SEL.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::W34SEL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1W34SEL.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::WBGLOG", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1WBGLOG.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::WH0", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1WH0.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::WH1", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1WH1.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::WH2", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1WH2.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::WH3", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1WH3.html", null ],
    [ "yaze::app::gui::zeml::WidgetAttributes", "structyaze_1_1app_1_1gui_1_1zeml_1_1WidgetAttributes.html", null ],
    [ "yaze::app::emu::video::WindowLayer", "structyaze_1_1app_1_1emu_1_1video_1_1WindowLayer.html", null ],
    [ "yaze::app::emu::video::WindowMaskSettings", "structyaze_1_1app_1_1emu_1_1video_1_1WindowMaskSettings.html", null ],
    [ "yaze::app::emu::video::WindowMaskSettings2", "structyaze_1_1app_1_1emu_1_1video_1_1WindowMaskSettings2.html", null ],
    [ "yaze::app::emu::video::WindowPosition", "structyaze_1_1app_1_1emu_1_1video_1_1WindowPosition.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::WOBJLOG", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1WOBJLOG.html", null ],
    [ "yaze::app::emu::video::PpuRegisters::WOBJSEL", "structyaze_1_1app_1_1emu_1_1video_1_1PpuRegisters_1_1WOBJSEL.html", null ],
    [ "yaze::app::emu::video::WramAccessRegisters", "structyaze_1_1app_1_1emu_1_1video_1_1WramAccessRegisters.html", null ],
    [ "yaze::app::Rom::WriteAction", "structyaze_1_1app_1_1Rom_1_1WriteAction.html", null ],
    [ "yaze_command_registry", "structyaze__command__registry.html", null ],
    [ "yaze_editor_context", "structyaze__editor__context.html", null ],
    [ "yaze_event_dispatcher", "structyaze__event__dispatcher.html", null ],
    [ "yaze_extension", "structyaze__extension.html", null ],
    [ "yaze_flags", "structyaze__flags.html", null ],
    [ "yaze_project", "structyaze__project.html", null ],
    [ "sample.YazePyExtension", "classsample_1_1YazePyExtension.html", null ],
    [ "z3_overworld", "structz3__overworld.html", null ],
    [ "z3_overworld_map", "structz3__overworld__map.html", null ],
    [ "z3_rom", "structz3__rom.html", null ],
    [ "z3_sprite", "structz3__sprite.html", null ],
    [ "z3_sprite_action", "structz3__sprite__action.html", null ],
    [ "yaze::app::editor::zsprite::ZSprite", "structyaze_1_1app_1_1editor_1_1zsprite_1_1ZSprite.html", null ]
];