yaze: src/app/main.cc File Reference
main.cc File Reference
#include "absl/debugging/failure_signal_handler.h"
#include "absl/debugging/symbolize.h"
#include "app/core/controller.h"
#include "app/core/features.h"
#include "util/flag.h"
#include "util/log.h"
Namespaces
namespace yaze
Main namespace for the application.
Functions
DEFINE_FLAG (std::string, rom_file, "", "The ROM file to load.")
DEFINE_FLAG (std::string, log_file, "", "Output log file path for debugging.")
DEFINE_FLAG (bool, debug, false, "Enable debug logging and verbose output.")
int main (int argc, char **argv)
Function Documentation
DEFINE_FLAG() [1/3]
DEFINE_FLAG (std::string , rom_file , "" , "The ROM file to load.")
DEFINE_FLAG() [2/3]
DEFINE_FLAG (std::string , log_file , "" , "Output log file path for debugging.")
DEFINE_FLAG() [3/3]
DEFINE_FLAG (bool , debug , false , "Enable debug logging and verbose output.")
main()
int main (int argc, char ** argv)
Definition at line 23 of file main.cc.
References EXIT_IF_ERROR, yaze::core::FeatureFlags::get(), yaze::util::global_flag_registry(), yaze::emu::Snes::Init(), yaze::Rom::is_loaded(), yaze::core::FeatureFlags::Flags::kLogToConsole, yaze::Rom::LoadFromFile(), yaze::emu::Snes::memory(), yaze::util::FlagParser::Parse(), RETURN_IF_EXCEPTION, yaze::emu::Snes::RunFrame(), yaze::util::SetLogFile(), yaze::emu::Snes::SetPixels(), yaze::emu::Snes::SetSamples(), and yaze::Rom::vector().
Referenced by yaze::editor::CommandManager::CommandGroup::CommandGroup(), yaze::zelda3::OverworldMap::LoadPalette(), yaze::gfx::Paletteset::Paletteset(), and yaze::zelda3::palette_internal::SetColorsPalette().