yaze: yaze::app::core::anonymous_namespace{common.cc} Namespace Reference
yaze::app::core::anonymous_namespace{common.cc} Namespace Reference
Functions
void encode (uint64_t data, std::vector< uint8_t > &output)
uint64_t decode (const std::vector< uint8_t > &input, size_t &offset)
uint32_t crc32 (const std::vector< uint8_t > &data)
unsigned ldle (uint8_t const *const p_arr, unsigned const p_index)
void stle (uint8_t *const p_arr, size_t const p_index, unsigned const p_val)
void stle0 (uint8_t *const p_arr, unsigned const p_val)
void stle1 (uint8_t *const p_arr, unsigned const p_val)
void stle2 (uint8_t *const p_arr, unsigned const p_val)
void stle3 (uint8_t *const p_arr, unsigned const p_val)
uint32_t ldle0 (uint8_t const *const p_arr)
uint32_t ldle1 (uint8_t const *const p_arr)
uint32_t ldle2 (uint8_t const *const p_arr)
uint32_t ldle3 (uint8_t const *const p_arr)
Function Documentation
encode()
void yaze::app::core::anonymous_namespace{common.cc}::encode (uint64_t data, std::vector< uint8_t > & output)
Definition at line 21 of file common.cc.
References encode().
Referenced by encode().
decode()
uint64_t yaze::app::core::anonymous_namespace{common.cc}::decode (const std::vector< uint8_t > & input, size_t & offset)
Definition at line 34 of file common.cc.
References decode().
Referenced by decode().
crc32()
uint32_t yaze::app::core::anonymous_namespace{common.cc}::crc32 (const std::vector< uint8_t > & data)
Definition at line 47 of file common.cc.
References crc32().
Referenced by crc32().
ldle()
unsigned yaze::app::core::anonymous_namespace{common.cc}::ldle (uint8_t const *const p_arr, unsigned const p_index)
Definition at line 54 of file common.cc.
References ldle().
Referenced by ldle(), ldle0(), ldle1(), ldle2(), and ldle3().
stle()
void yaze::app::core::anonymous_namespace{common.cc}::stle (uint8_t *const p_arr, size_t const p_index, unsigned const p_val)
Definition at line 60 of file common.cc.
References stle().
Referenced by stle(), stle0(), stle1(), stle2(), and stle3().
stle0()
void yaze::app::core::anonymous_namespace{common.cc}::stle0 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 66 of file common.cc.
References stle(), and stle0().
Referenced by stle0().
stle1()
void yaze::app::core::anonymous_namespace{common.cc}::stle1 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 70 of file common.cc.
References stle(), and stle1().
Referenced by stle1().
stle2()
void yaze::app::core::anonymous_namespace{common.cc}::stle2 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 74 of file common.cc.
References stle(), and stle2().
Referenced by stle2().
stle3()
void yaze::app::core::anonymous_namespace{common.cc}::stle3 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 78 of file common.cc.
References stle(), and stle3().
Referenced by stle3().
ldle0()
uint32_t yaze::app::core::anonymous_namespace{common.cc}::ldle0 (uint8_t const *const p_arr)
Definition at line 83 of file common.cc.
References ldle(), and ldle0().
Referenced by ldle0().
ldle1()
uint32_t yaze::app::core::anonymous_namespace{common.cc}::ldle1 (uint8_t const *const p_arr)
Definition at line 86 of file common.cc.
References ldle(), and ldle1().
Referenced by ldle1().
ldle2()
uint32_t yaze::app::core::anonymous_namespace{common.cc}::ldle2 (uint8_t const *const p_arr)
Definition at line 89 of file common.cc.
References ldle(), and ldle2().
Referenced by ldle2().
ldle3()
uint32_t yaze::app::core::anonymous_namespace{common.cc}::ldle3 (uint8_t const *const p_arr)
Definition at line 92 of file common.cc.
References ldle(), and ldle3().
Referenced by ldle3().