yaze: yaze::test::anonymous_namespace{compression_test.cc} Namespace Reference
yaze::test::anonymous_namespace{compression_test.cc} Namespace Reference
Functions
std::vector< uint8_t > ExpectCompressOk (Rom &rom, uchar *in, int in_size)
std::vector< uint8_t > ExpectDecompressBytesOk (Rom &rom, std::vector< uint8_t > &in)
std::vector< uint8_t > ExpectDecompressOk (Rom &rom, uchar *in, int in_size)
std::shared_ptr< CompressionPiece > ExpectNewCompressionPieceOk (const char command, const int length, const std::string args, const int argument_length)
void AssertCompressionQuality (const std::vector< uint8_t > &uncompressed_data, const std::vector< uint8_t > &expected_compressed_data)
std::vector< uint8_t > ExpectCompressV3Ok (const std::vector< uint8_t > &uncompressed_data, const std::vector< uint8_t > &expected_compressed_data)
std::vector< uint8_t > CreateRepeatedBetweenUncompressable (int leftUncompressedSize, int repeatedByteSize, int rightUncompressedSize)
Function Documentation
ExpectCompressOk()
std::vector< uint8_t > yaze::test::anonymous_namespace{compression_test.cc}::ExpectCompressOk (Rom & rom, uchar * in, int in_size)
Definition at line 35 of file compression_test.cc.
References yaze::test::CompressV3(), ExpectCompressOk(), yaze::Rom::LoadFromPointer(), and yaze::Rom::vector().
Referenced by ExpectCompressOk().
ExpectDecompressBytesOk()
std::vector< uint8_t > yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk (Rom & rom, std::vector< uint8_t > & in)
Definition at line 44 of file compression_test.cc.
References yaze::Rom::data(), yaze::test::DecompressV2(), ExpectDecompressBytesOk(), and yaze::Rom::LoadFromBytes().
Referenced by ExpectDecompressBytesOk().
ExpectDecompressOk()
std::vector< uint8_t > yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressOk (Rom & rom, uchar * in, int in_size)
Definition at line 54 of file compression_test.cc.
References yaze::Rom::data(), yaze::test::DecompressV2(), ExpectDecompressOk(), and yaze::Rom::LoadFromPointer().
Referenced by ExpectDecompressOk().
ExpectNewCompressionPieceOk()
std::shared_ptr< CompressionPiece > yaze::test::anonymous_namespace{compression_test.cc}::ExpectNewCompressionPieceOk (const char command, const int length, const std::string args, const int argument_length)
Definition at line 63 of file compression_test.cc.
References ExpectNewCompressionPieceOk().
Referenced by ExpectNewCompressionPieceOk().
AssertCompressionQuality()
void yaze::test::anonymous_namespace{compression_test.cc}::AssertCompressionQuality (const std::vector< uint8_t > & uncompressed_data, const std::vector< uint8_t > & expected_compressed_data)
Definition at line 73 of file compression_test.cc.
References AssertCompressionQuality(), and yaze::test::CompressV3().
Referenced by AssertCompressionQuality().
ExpectCompressV3Ok()
std::vector< uint8_t > yaze::test::anonymous_namespace{compression_test.cc}::ExpectCompressV3Ok (const std::vector< uint8_t > & uncompressed_data, const std::vector< uint8_t > & expected_compressed_data)
Definition at line 83 of file compression_test.cc.
References yaze::test::CompressV3(), and ExpectCompressV3Ok().
Referenced by ExpectCompressV3Ok().
CreateRepeatedBetweenUncompressable()
std::vector< uint8_t > yaze::test::anonymous_namespace{compression_test.cc}::CreateRepeatedBetweenUncompressable (int leftUncompressedSize, int repeatedByteSize, int rightUncompressedSize)
Definition at line 93 of file compression_test.cc.
References CreateRepeatedBetweenUncompressable().
Referenced by CreateRepeatedBetweenUncompressable().