yaze: yaze::app::editor::anonymous_namespace{assembly_editor.cc} Namespace Reference
yaze::app::editor::anonymous_namespace{assembly_editor.cc} Namespace Reference
Functions
std::vector< std::string > RemoveIgnoredFiles (const std::vector< std::string > &files, const std::vector< std::string > &ignored_files)
core::FolderItem LoadFolder (const std::string &folder)
Function Documentation
RemoveIgnoredFiles()
std::vector< std::string > yaze::app::editor::anonymous_namespace{assembly_editor.cc}::RemoveIgnoredFiles (const std::vector< std::string > & files, const std::vector< std::string > & ignored_files)
Definition at line 17 of file assembly_editor.cc.
References RemoveIgnoredFiles().
Referenced by LoadFolder(), and RemoveIgnoredFiles().
LoadFolder()
core::FolderItem yaze::app::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder (const std::string & folder)
Definition at line 38 of file assembly_editor.cc.
References yaze::app::core::FolderItem::files, yaze::app::core::FileDialogWrapper::GetFilesInFolder(), yaze::app::core::FileDialogWrapper::GetSubdirectoriesInFolder(), LoadFolder(), yaze::app::core::FolderItem::name, RemoveIgnoredFiles(), and yaze::app::core::FolderItem::subfolders.
Referenced by LoadFolder().