yaze: yaze::app::zelda3::overworld::anonymous_namespace{overworld.cc} Namespace Reference
yaze::app::zelda3::overworld::anonymous_namespace{overworld.cc} Namespace Reference
Functions
absl::flat_hash_map< int, MapData > parseFile (const std::string &filename)
std::vector< uint64_t > GetAllTile16 (OWMapTiles &map_tiles_)
bool compareItemsArrays (std::vector< OverworldItem > itemArray1, std::vector< OverworldItem > itemArray2)
Function Documentation
parseFile()
absl::flat_hash_map< int, MapData > yaze::app::zelda3::overworld::anonymous_namespace{overworld.cc}::parseFile (const std::string & filename)
Definition at line 30 of file overworld.cc.
References parseFile().
Referenced by parseFile().
GetAllTile16()
std::vector< uint64_t > yaze::app::zelda3::overworld::anonymous_namespace{overworld.cc}::GetAllTile16 (OWMapTiles & map_tiles_)
Definition at line 1016 of file overworld.cc.
References yaze::app::zelda3::OWMapTiles::dark_world, GetAllTile16(), yaze::app::gfx::Tile32::GetPackedValue(), yaze::app::zelda3::overworld::kNumOverworldMaps, yaze::app::zelda3::OWMapTiles::light_world, and yaze::app::zelda3::OWMapTiles::special_world.
Referenced by GetAllTile16().
compareItemsArrays()
bool yaze::app::zelda3::overworld::anonymous_namespace{overworld.cc}::compareItemsArrays (std::vector< OverworldItem > itemArray1, std::vector< OverworldItem > itemArray2)
Definition at line 1332 of file overworld.cc.
References compareItemsArrays().
Referenced by compareItemsArrays().