yaze: yaze::app::zelda3::palette_internal Namespace Reference
yaze::app::zelda3::palette_internal Namespace Reference
Functions
absl::Status SetColorsPalette (ROM &rom, int index, gfx::SnesPalette &current, gfx::SnesPalette main, gfx::SnesPalette animated, gfx::SnesPalette aux1, gfx::SnesPalette aux2, gfx::SnesPalette hud, gfx::SnesColor bgrcolor, gfx::SnesPalette spr, gfx::SnesPalette spr2)
Function Documentation
SetColorsPalette()
absl::Status yaze::app::zelda3::palette_internal::SetColorsPalette (ROM & rom, int index, gfx::SnesPalette & current, gfx::SnesPalette main, gfx::SnesPalette animated, gfx::SnesPalette aux1, gfx::SnesPalette aux2, gfx::SnesPalette hud, gfx::SnesColor bgrcolor, gfx::SnesPalette spr, gfx::SnesPalette spr2)
References ASSIGN_OR_RETURN, yaze::app::gfx::SnesPalette::Create(), main(), and yaze::app::ROM::palette_group().
Referenced by yaze::app::zelda3::OverworldMap::LoadPalette().