yaze: yaze::gfx::anonymous_namespace{tilemap.cc} Namespace Reference
yaze::gfx::anonymous_namespace{tilemap.cc} Namespace Reference
Functions
void MirrorTileDataVertically (std::vector< uint8_t > &tile_data)
void MirrorTileDataHorizontally (std::vector< uint8_t > &tile_data)
void ComposeAndPlaceTilePart (Tilemap &tilemap, const std::vector< uint8_t > &data, const TileInfo &tile_info, int base_x, int base_y, int sheet_offset)
Function Documentation
MirrorTileDataVertically()
void yaze::gfx::anonymous_namespace{tilemap.cc}::MirrorTileDataVertically (std::vector< uint8_t > & tile_data)
Definition at line 105 of file tilemap.cc.
References MirrorTileDataVertically().
Referenced by ComposeAndPlaceTilePart(), and MirrorTileDataVertically().
MirrorTileDataHorizontally()
void yaze::gfx::anonymous_namespace{tilemap.cc}::MirrorTileDataHorizontally (std::vector< uint8_t > & tile_data)
Definition at line 113 of file tilemap.cc.
References MirrorTileDataHorizontally().
Referenced by ComposeAndPlaceTilePart(), and MirrorTileDataHorizontally().
ComposeAndPlaceTilePart()
void yaze::gfx::anonymous_namespace{tilemap.cc}::ComposeAndPlaceTilePart (Tilemap & tilemap, const std::vector< uint8_t > & data, const TileInfo & tile_info, int base_x, int base_y, int sheet_offset)
Definition at line 121 of file tilemap.cc.
References yaze::gfx::Tilemap::atlas, ComposeAndPlaceTilePart(), yaze::gfx::FetchTileDataFromGraphicsBuffer(), yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, MirrorTileDataHorizontally(), MirrorTileDataVertically(), yaze::gfx::TileInfo::vertical_mirror_, yaze::gfx::Bitmap::width(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by ComposeAndPlaceTilePart().