yaze: yaze::core Namespace Reference
yaze::core Namespace Reference
Core application logic and utilities.
Namespaces
namespace anonymous_namespace{common.cc}
namespace anonymous_namespace{font_loader.cc}
Classes
class Controller
Main controller for the application.
class ExperimentFlags
A class to manage experimental feature flags.
class FileDialogWrapper
struct FolderItem
struct FontConfig
struct HexStringParams
class NotifyValue
A class to manage a value that can be modified and notify when it changes.
class Renderer
The Renderer class represents the renderer for the Yaze application.
struct SDL_Deleter
Deleter for SDL_Window and SDL_Renderer.
struct SDL_Surface_Deleter
Deleter for SDL_Surface.
struct SDL_Texture_Deleter
Deleter for SDL_Texture.
Typedefs
typedef struct FolderItem FolderItem
Enumerations
enum class Platform {
kUnknown , kMacOS , kiOS , kWindows ,
kLinux
}
Functions
std::string HexByte (uint8_t byte, HexStringParams params)
std::string HexWord (uint16_t word, HexStringParams params)
std::string HexLong (uint32_t dword, HexStringParams params)
std::string HexLongLong (uint64_t qword, HexStringParams params)
bool StringReplace (std::string &str, const std::string &from, const std::string &to)
uint32_t Get24LocalFromPC (uint8_t *data, int addr, bool pc)
void stle16b_i (uint8_t *const p_arr, size_t const p_index, uint16_t const p_val)
Store little endian 16-bit value using a byte pointer, offset by an index before dereferencing.
void stle16b (uint8_t *const p_arr, uint16_t const p_val)
uint16_t ldle16b (uint8_t const *const p_arr)
uint16_t ldle16b_i (uint8_t const *const p_arr, size_t const p_index)
Load little endian halfword (16-bit) dereferenced from an arrays of bytes. This version provides an index that will be multiplied by 2 and added to the base address.
void CreateBpsPatch (const std::vector< uint8_t > &source, const std::vector< uint8_t > &target, std::vector< uint8_t > &patch)
void ApplyBpsPatch (const std::vector< uint8_t > &source, const std::vector< uint8_t > &patch, std::vector< uint8_t > &target)
uint32_t SnesToPc (uint32_t addr) noexcept
uint32_t PcToSnes (uint32_t addr)
int AddressFromBytes (uint8_t bank, uint8_t high, uint8_t low) noexcept
uint32_t MapBankToWordAddress (uint8_t bank, uint16_t addr) noexcept
void CopyImageToClipboard (const std::vector< uint8_t > &data)
void GetImageFromClipboard (std::vector< uint8_t > &data, int &width, int &height)
std::string GetFileExtension (const std::string &filename)
std::string GetFileName (const std::string &filename)
std::string LoadFile (const std::string &filename)
std::string LoadConfigFile (const std::string &filename)
void SaveFile (const std::string &filename, const std::string &contents, Platform platform)
std::string GetConfigDirectory (Platform platform)
std::string GetBundleResourcePath ()
GetBundleResourcePath returns the path to the bundle resource directory. Specific to MacOS.
absl::Status LoadPackageFonts ()
absl::Status ReloadPackageFont (const FontConfig &config)
void LoadSystemFonts ()
Variables
constexpr uint32_t kFastRomRegion = 0x808000
Detailed Description
Core application logic and utilities.
Typedef Documentation
FolderItem
typedef struct FolderItem yaze::core::FolderItem
Definition at line 253 of file common.h.
Enumeration Type Documentation
Platform
enum class yaze::core::Platform strong
Enumerator
kUnknown
kMacOS
kiOS
kWindows
kLinux
Definition at line 35 of file file_dialog.h.
Function Documentation
HexByte()
std::string yaze::core::HexByte (uint8_t byte, HexStringParams params)
Definition at line 110 of file common.cc.
References yaze::core::HexStringParams::uppercase.
Referenced by yaze::zelda3::OverworldMap::DrawAnimatedTiles(), yaze::editor::ScreenEditor::DrawDungeonMapsTabs(), yaze::editor::DungeonEditor::DrawEntranceSelector(), yaze::editor::OverworldEditor::DrawOverworldEntrances(), yaze::editor::OverworldEditor::DrawOverworldExits(), yaze::editor::DungeonEditor::DrawRoomSelector(), yaze::editor::SpriteEditor::DrawSpritesList(), yaze::editor::HandleEntityDragging(), yaze::editor::Tile16Editor::InitBlockset(), yaze::editor::ScreenEditor::LoadDungeonMaps(), yaze::editor::MessageEditor::ReadAllTextDataV2(), yaze::zelda3::Overworld::SaveOverworldMaps(), yaze::editor::OverworldEditor::UpdateUsageStats(), yaze::Rom::WriteByte(), and yaze::Rom::WriteVector().
HexWord()
std::string yaze::core::HexWord (uint16_t word, HexStringParams params)
Definition at line 123 of file common.cc.
References yaze::core::HexStringParams::uppercase.
Referenced by yaze::editor::MessageEditor::DrawDictionary(), yaze::editor::MessageEditor::DrawMessageList(), yaze::editor::MessageEditor::ReadAllTextData(), yaze::editor::MessageEditor::ReadAllTextDataV2(), yaze::Rom::WriteColor(), yaze::Rom::WriteShort(), and yaze::Rom::WriteWord().
HexLong()
std::string yaze::core::HexLong (uint32_t dword, HexStringParams params)
Definition at line 136 of file common.cc.
References yaze::core::HexStringParams::uppercase.
Referenced by yaze::editor::MessageEditor::DrawMessageList(), yaze::editor::ParseMessageData(), yaze::zelda3::Overworld::SaveOverworldMaps(), and yaze::Rom::WriteLong().
HexLongLong()
std::string yaze::core::HexLongLong (uint64_t qword, HexStringParams params)
Definition at line 149 of file common.cc.
References yaze::core::HexStringParams::uppercase.
Referenced by yaze::editor::EditorManager::DrawPopups().
StringReplace()
bool yaze::core::StringReplace (std::string & str, const std::string & from, const std::string & to)
Definition at line 162 of file common.cc.
Get24LocalFromPC()
uint32_t yaze::core::Get24LocalFromPC (uint8_t * data, int addr, bool pc)
Definition at line 171 of file common.cc.
References PcToSnes(), and SnesToPc().
Referenced by yaze::editor::MessageEditor::ReadAllTextData(), and yaze::editor::MessageEditor::ReadAllTextDataV2().
stle16b_i()
void yaze::core::stle16b_i (uint8_t *const p_arr, size_t const p_index, uint16_t const p_val)
Store little endian 16-bit value using a byte pointer, offset by an index before dereferencing.
Definition at line 180 of file common.cc.
References stle16b().
Referenced by yaze::zelda3::music::Tracker::SaveSongs().
stle16b()
void yaze::core::stle16b (uint8_t *const p_arr, uint16_t const p_val)
Definition at line 185 of file common.cc.
Referenced by yaze::gfx::HyruleMagicDecompress(), and stle16b_i().
ldle16b()
uint16_t yaze::core::ldle16b (uint8_t const *const p_arr)
Definition at line 190 of file common.cc.
Referenced by yaze::gfx::HyruleMagicDecompress(), and ldle16b_i().
ldle16b_i()
uint16_t yaze::core::ldle16b_i (uint8_t const *const p_arr, size_t const p_index)
Load little endian halfword (16-bit) dereferenced from an arrays of bytes. This version provides an index that will be multiplied by 2 and added to the base address.
Definition at line 196 of file common.cc.
References ldle16b().
Referenced by yaze::zelda3::music::Tracker::SaveSongs().
CreateBpsPatch()
void yaze::core::CreateBpsPatch (const std::vector< uint8_t > & source, const std::vector< uint8_t > & target, std::vector< uint8_t > & patch)
Definition at line 200 of file common.cc.
Referenced by yaze::cli::CreatePatch::handle().
ApplyBpsPatch()
void yaze::core::ApplyBpsPatch (const std::vector< uint8_t > & source, const std::vector< uint8_t > & patch, std::vector< uint8_t > & target)
Definition at line 289 of file common.cc.
Referenced by yaze::cli::anonymous_namespace{tui.cc}::ApplyBpsPatchComponent(), and yaze::cli::ApplyPatch::handle().
SnesToPc()
uint32_t yaze::core::SnesToPc (uint32_t addr) inline noexcept
Definition at line 195 of file common.h.
References kFastRomRegion.
Referenced by yaze::editor::BuildDictionaryEntries(), yaze::zelda3::Overworld::DecompressAllMapTiles(), Get24LocalFromPC(), yaze::anonymous_namespace{rom.cc}::GetGraphicsAddress(), yaze::cli::SnesToPc::handle(), yaze::zelda3::Room::LoadAnimatedGraphics(), yaze::zelda3::Room::LoadChests(), yaze::editor::ScreenEditor::LoadDungeonMaps(), yaze::Rom::LoadGfxGroups(), yaze::zelda3::Room::LoadHeader(), yaze::zelda3::Overworld::LoadItems(), yaze::zelda3::Room::LoadObjects(), yaze::zelda3::Room::LoadRoomFromROM(), yaze::zelda3::Room::LoadSprites(), yaze::zelda3::Overworld::LoadSpritesFromMap(), yaze::zelda3::TitleScreen::LoadTitleScreen(), yaze::editor::ScreenEditor::SaveDungeonMaps(), yaze::Rom::SaveGroupsToRom(), yaze::zelda3::Overworld::SaveMap16Expanded(), and yaze::editor::MemoryEditorWithDiffChecker::Update().
PcToSnes()
uint32_t yaze::core::PcToSnes (uint32_t addr) inline
Definition at line 203 of file common.h.
Referenced by Get24LocalFromPC(), yaze::cli::PcToSnes::handle(), yaze::zelda3::Overworld::SaveItems(), yaze::zelda3::Overworld::SaveMap16Expanded(), yaze::zelda3::Overworld::SaveMap32Expanded(), and yaze::zelda3::Overworld::SaveOverworldMaps().
AddressFromBytes()
int yaze::core::AddressFromBytes (uint8_t bank, uint8_t high, uint8_t low) inline noexcept
Definition at line 216 of file common.h.
Referenced by yaze::anonymous_namespace{rom.cc}::GetGraphicsAddress().
MapBankToWordAddress()
uint32_t yaze::core::MapBankToWordAddress (uint8_t bank, uint16_t addr) inline noexcept
Definition at line 220 of file common.h.
CopyImageToClipboard()
void yaze::core::CopyImageToClipboard (const std::vector< uint8_t > & data)
Definition at line 9 of file clipboard.cc.
Referenced by yaze::editor::GraphicsEditor::DrawGfxEditToolset(), and yaze::editor::OverworldEditor::DrawToolset().
GetImageFromClipboard()
void yaze::core::GetImageFromClipboard (std::vector< uint8_t > & data, int & width, int & height)
Definition at line 10 of file clipboard.cc.
Referenced by yaze::editor::GraphicsEditor::DrawGfxEditToolset().
GetFileExtension()
std::string yaze::core::GetFileExtension (const std::string & filename)
Definition at line 18 of file file_dialog.cc.
GetFileName()
std::string yaze::core::GetFileName (const std::string & filename)
Definition at line 26 of file file_dialog.cc.
LoadFile()
std::string yaze::core::LoadFile (const std::string & filename)
Definition at line 34 of file file_dialog.cc.
Referenced by yaze::gui::LoadTheme().
LoadConfigFile()
std::string yaze::core::LoadConfigFile (const std::string & filename)
Definition at line 49 of file file_dialog.cc.
References GetConfigDirectory(), kLinux, kMacOS, and kWindows.
SaveFile()
void yaze::core::SaveFile (const std::string & filename, const std::string & contents, Platform platform)
Definition at line 70 of file file_dialog.cc.
References GetConfigDirectory().
GetConfigDirectory()
std::string yaze::core::GetConfigDirectory (Platform platform)
Definition at line 80 of file file_dialog.cc.
References kLinux, kMacOS, and kWindows.
Referenced by LoadConfigFile(), yaze::core::Controller::LoadConfigFiles(), and SaveFile().
GetBundleResourcePath()
std::string yaze::core::GetBundleResourcePath ()
GetBundleResourcePath returns the path to the bundle resource directory. Specific to MacOS.
Referenced by yaze::gui::zeml::LoadFile(), and yaze::core::anonymous_namespace{font_loader.cc}::SetFontPath().
LoadPackageFonts()
absl::Status yaze::core::LoadPackageFonts ()
Definition at line 98 of file font_loader.cc.
References ICON_MIN_MD, and RETURN_IF_ERROR.
Referenced by yaze::core::Controller::LoadFontFamilies().
ReloadPackageFont()
absl::Status yaze::core::ReloadPackageFont (const FontConfig & config)
Definition at line 137 of file font_loader.cc.
References yaze::core::FontConfig::font_path, yaze::core::FontConfig::font_size, and RETURN_IF_ERROR.
LoadSystemFonts()
void yaze::core::LoadSystemFonts ()
Variable Documentation
kFastRomRegion
uint32_t yaze::core::kFastRomRegion = 0x808000 constexpr
Definition at line 193 of file common.h.
Referenced by SnesToPc().