yaze: yaze::test::integration Namespace Reference
yaze::test::integration Namespace Reference
Classes
class TestEditor
Functions
int RunIntegrationTest ()
Function Documentation
RunIntegrationTest()
int yaze::test::integration::RunIntegrationTest ()
Definition at line 44 of file test_editor.cc.
References yaze::app::gui::ColorsYaze(), yaze::app::core::Controller::CreateRenderer(), yaze::app::core::Controller::CreateSDL_Window(), yaze::app::core::Controller::DoRender(), yaze::app::core::Renderer::GetInstance(), yaze::app::core::Controller::init_test_editor(), yaze::app::core::Controller::IsActive(), yaze::app::core::Controller::OnExit(), yaze::app::core::Controller::OnInput(), yaze::app::core::Controller::OnTestLoad(), yaze::test::integration::TestEditor::RegisterTests(), yaze::app::core::Renderer::renderer(), yaze::app::core::Controller::set_active(), and yaze::app::core::Controller::window().
Referenced by main().