yaze: yaze::emu::memory::dma Namespace Reference
yaze::emu::memory::dma Namespace Reference
Functions
void Reset (MemoryImpl *memory)
uint8_t Read (MemoryImpl *memory, uint16_t adr)
void Write (MemoryImpl *memory, uint16_t adr, uint8_t val)
void DoDma (SNES *snes, MemoryImpl *memory, int cpuCycles)
void HandleDma (SNES *snes, MemoryImpl *memory, int cpu_cycles)
void WaitCycle (SNES *snes, MemoryImpl *memory)
void InitHdma (SNES *snes, MemoryImpl *memory, bool do_sync, int cpu_cycles)
void DoHdma (SNES *snes, MemoryImpl *memory, bool do_sync, int cycles)
void TransferByte (SNES *snes, MemoryImpl *memory, uint16_t aAdr, uint8_t aBank, uint8_t bAdr, bool fromB)
void StartDma (MemoryImpl *memory, uint8_t val, bool hdma)
Function Documentation
Reset()
void yaze::emu::memory::dma::Reset (MemoryImpl * memory)
Definition at line 16 of file dma.cc.
References yaze::emu::memory::MemoryImpl::dma_channels(), yaze::emu::memory::MemoryImpl::set_dma_state(), yaze::emu::memory::MemoryImpl::set_hdma_init_requested(), and yaze::emu::memory::MemoryImpl::set_hdma_run_requested().
Referenced by yaze::emu::SNES::Reset().
Read()
uint8_t yaze::emu::memory::dma::Read (MemoryImpl * memory, uint16_t adr)
Definition at line 43 of file dma.cc.
References yaze::emu::memory::MemoryImpl::dma_channels(), and yaze::emu::memory::MemoryImpl::open_bus().
Referenced by yaze::emu::SNES::Rread().
Write()
void yaze::emu::memory::dma::Write (MemoryImpl * memory, uint16_t adr, uint8_t val)
Definition at line 96 of file dma.cc.
References yaze::emu::memory::MemoryImpl::dma_channels().
Referenced by yaze::emu::SNES::Write().
DoDma()
void yaze::emu::memory::dma::DoDma (SNES * snes, MemoryImpl * memory, int cpuCycles)
Definition at line 160 of file dma.cc.
References yaze::emu::SNES::cpu(), yaze::emu::memory::MemoryImpl::dma_channels(), yaze::emu::SNES::SyncCycles(), TransferByte(), and WaitCycle().
Referenced by HandleDma().
HandleDma()
void yaze::emu::memory::dma::HandleDma (SNES * snes, MemoryImpl * memory, int cpu_cycles)
Definition at line 194 of file dma.cc.
References yaze::emu::memory::MemoryImpl::dma_state(), DoDma(), DoHdma(), yaze::emu::memory::MemoryImpl::hdma_init_requested(), yaze::emu::memory::MemoryImpl::hdma_run_requested(), InitHdma(), and yaze::emu::memory::MemoryImpl::set_dma_state().
Referenced by yaze::emu::SNES::CpuIdle(), yaze::emu::SNES::CpuRead(), and yaze::emu::SNES::CpuWrite().
WaitCycle()
void yaze::emu::memory::dma::WaitCycle (SNES * snes, MemoryImpl * memory)
Definition at line 212 of file dma.cc.
References DoHdma(), yaze::emu::memory::MemoryImpl::hdma_init_requested(), yaze::emu::memory::MemoryImpl::hdma_run_requested(), InitHdma(), and yaze::emu::SNES::RunCycles().
Referenced by DoDma().
InitHdma()
void yaze::emu::memory::dma::InitHdma (SNES * snes, MemoryImpl * memory, bool do_sync, int cpu_cycles)
Definition at line 220 of file dma.cc.
References yaze::emu::SNES::cpu(), yaze::emu::memory::MemoryImpl::dma_channels(), yaze::emu::SNES::Read(), yaze::emu::SNES::RunCycles(), yaze::emu::memory::MemoryImpl::set_hdma_init_requested(), and yaze::emu::SNES::SyncCycles().
Referenced by HandleDma(), and WaitCycle().
DoHdma()
void yaze::emu::memory::dma::DoHdma (SNES * snes, MemoryImpl * memory, bool do_sync, int cycles)
Definition at line 260 of file dma.cc.
References yaze::emu::SNES::cpu(), yaze::emu::memory::MemoryImpl::dma_channels(), yaze::emu::SNES::Read(), yaze::emu::SNES::RunCycles(), yaze::emu::memory::MemoryImpl::set_hdma_run_requested(), yaze::emu::SNES::SyncCycles(), and TransferByte().
Referenced by HandleDma(), and WaitCycle().
TransferByte()
void yaze::emu::memory::dma::TransferByte (SNES * snes, MemoryImpl * memory, uint16_t aAdr, uint8_t aBank, uint8_t bAdr, bool fromB)
Definition at line 335 of file dma.cc.
References yaze::emu::memory::MemoryImpl::open_bus(), yaze::emu::SNES::Read(), yaze::emu::SNES::ReadBBus(), yaze::emu::SNES::Write(), and yaze::emu::SNES::WriteBBus().
Referenced by DoDma(), and DoHdma().
StartDma()
void yaze::emu::memory::dma::StartDma (MemoryImpl * memory, uint8_t val, bool hdma)
Definition at line 357 of file dma.cc.
References yaze::emu::memory::MemoryImpl::dma_channels(), and yaze::emu::memory::MemoryImpl::set_dma_state().
Referenced by yaze::emu::SNES::WriteReg().