yaze: yaze::util::anonymous_namespace{bps.cc} Namespace Reference
yaze::util::anonymous_namespace{bps.cc} Namespace Reference
Functions
uint32_t crc32 (const std::vector< uint8_t > &data)
void encode (uint64_t data, std::vector< uint8_t > &output)
uint64_t decode (const std::vector< uint8_t > &input, size_t &offset)
Function Documentation
crc32()
uint32_t yaze::util::anonymous_namespace{bps.cc}::crc32 (const std::vector< uint8_t > & data)
Definition at line 26 of file bps.cc.
References crc32().
Referenced by crc32().
encode()
void yaze::util::anonymous_namespace{bps.cc}::encode (uint64_t data, std::vector< uint8_t > & output)
Definition at line 81 of file bps.cc.
References encode().
Referenced by encode().
decode()
uint64_t yaze::util::anonymous_namespace{bps.cc}::decode (const std::vector< uint8_t > & input, size_t & offset)
Definition at line 94 of file bps.cc.
References decode().
Referenced by decode().