yaze: yaze::app::editor::item_internal Namespace Reference
yaze::app::editor::item_internal Namespace Reference
Functions
void DrawItemInsertPopup ()
bool DrawItemEditorPopup (zelda3::overworld::OverworldItem &item)
Function Documentation
DrawItemInsertPopup()
void yaze::app::editor::item_internal::DrawItemInsertPopup ()
References DrawItemInsertPopup(), ICON_MD_CANCEL, and ICON_MD_DONE.
Referenced by DrawItemInsertPopup().
DrawItemEditorPopup()
bool yaze::app::editor::item_internal::DrawItemEditorPopup (zelda3::overworld::OverworldItem & item)
Todo
Implement deleting OverworldItem objects, currently only hides them
References yaze::app::zelda3::overworld::OverworldItem::deleted, DrawItemEditorPopup(), ICON_MD_CLOSE, ICON_MD_DELETE, ICON_MD_DONE, and yaze::app::zelda3::overworld::OverworldItem::id.
Referenced by DrawItemEditorPopup().