yaze: yaze::app::anonymous_namespace{rom.cc} Namespace Reference
yaze::app::anonymous_namespace{rom.cc} Namespace Reference
Functions
absl::Status LoadOverworldMainPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAuxiliaryPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAnimatedPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadHUDPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadGlobalSpritePalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadArmorPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadSwordPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadShieldPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux1Palettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux2Palettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux3Palettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadDungeonMainPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadGrassColors (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status Load3DObjectPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
absl::Status LoadOverworldMiniMapPalettes (const Bytes &rom_data, PaletteGroupMap &palette_groups)
Function Documentation
LoadOverworldMainPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadOverworldMainPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadOverworldMainPalettes(), yaze::app::core::overworldPaletteMain, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadOverworldMainPalettes().
LoadOverworldAuxiliaryPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadOverworldAuxiliaryPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadOverworldAuxiliaryPalettes(), yaze::app::core::overworldPaletteAuxialiary, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadOverworldAuxiliaryPalettes().
LoadOverworldAnimatedPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadOverworldAnimatedPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadOverworldAnimatedPalettes(), yaze::app::core::overworldPaletteAnimated, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadOverworldAnimatedPalettes().
LoadHUDPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadHUDPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References yaze::app::core::hudPalettes, LoadHUDPalettes(), yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadHUDPalettes().
LoadGlobalSpritePalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadGlobalSpritePalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References yaze::app::core::globalSpritePalettesDW, yaze::app::core::globalSpritePalettesLW, LoadGlobalSpritePalettes(), yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadGlobalSpritePalettes().
LoadArmorPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadArmorPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References yaze::app::core::armorPalettes, LoadArmorPalettes(), yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadArmorPalettes().
LoadSwordPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadSwordPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadSwordPalettes(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, and yaze::app::core::swordPalettes.
Referenced by LoadSwordPalettes().
LoadShieldPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadShieldPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadShieldPalettes(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, and yaze::app::core::shieldPalettes.
Referenced by LoadShieldPalettes().
LoadSpriteAux1Palettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadSpriteAux1Palettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadSpriteAux1Palettes(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, and yaze::app::core::spritePalettesAux1.
Referenced by LoadSpriteAux1Palettes().
LoadSpriteAux2Palettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadSpriteAux2Palettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadSpriteAux2Palettes(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, and yaze::app::core::spritePalettesAux2.
Referenced by LoadSpriteAux2Palettes().
LoadSpriteAux3Palettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadSpriteAux3Palettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadSpriteAux3Palettes(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, and yaze::app::core::spritePalettesAux3.
Referenced by LoadSpriteAux3Palettes().
LoadDungeonMainPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadDungeonMainPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References yaze::app::core::dungeonMainPalettes, LoadDungeonMainPalettes(), yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadDungeonMainPalettes().
LoadGrassColors()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadGrassColors (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References yaze::app::core::hardcodedGrassDW, yaze::app::core::hardcodedGrassLW, yaze::app::core::hardcodedGrassSpecial, LoadGrassColors(), yaze::app::gfx::ReadColorFromRom(), and RETURN_IF_ERROR.
Referenced by LoadGrassColors().
Load3DObjectPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::Load3DObjectPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References yaze::app::core::crystalPalette, Load3DObjectPalettes(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, and yaze::app::core::triforcePalette.
Referenced by Load3DObjectPalettes().
LoadOverworldMiniMapPalettes()
absl::Status yaze::app::anonymous_namespace{rom.cc}::LoadOverworldMiniMapPalettes (const Bytes & rom_data, PaletteGroupMap & palette_groups)
References LoadOverworldMiniMapPalettes(), yaze::app::core::overworldMiniMapPalettes, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by LoadOverworldMiniMapPalettes().