yaze: yaze::zelda3::screen Namespace Reference
yaze::zelda3::screen Namespace Reference
Classes
struct DungeonMap
class Inventory
class Renderer
The Renderer class represents the renderer for the Yaze application.
class TitleScreen
Functions
absl::Status LoadDungeonMapGfxFromBinary (Rom &rom, std::array< gfx::Bitmap, 4 > &sheets, gfx::Tilesheet &tile16_sheet, std::vector< uint8_t > &gfx_bin_data)
absl::Status LoadDungeonMapTile16 (const std::vector< uint8_t > &gfx_data, bool bin_mode)
Variables
constexpr int kDungeonMapRoomsPtr = 0x57605
constexpr int kDungeonMapFloors = 0x575D9
constexpr int kDungeonMapGfxPtr = 0x57BE4
constexpr int kDungeonMapDataStart = 0x57039
constexpr int kDungeonMapExpCheck = 0x56652
constexpr int kDungeonMapTile16 = 0x57009
constexpr int kDungeonMapTile16Expanded = 0x109010
constexpr int kDungeonMapBossRooms = 0x56807
constexpr int kTriforceVertices = 0x04FFD2
constexpr int kTriforceFaces = 0x04FFE4
constexpr int kCrystalVertices = 0x04FF98
constexpr int kInventoryStart = 0x6564A
constexpr int kBowItemPos = 0x6F631
Function Documentation
LoadDungeonMapGfxFromBinary()
absl::Status yaze::zelda3::screen::LoadDungeonMapGfxFromBinary (Rom & rom, std::array< gfx::Bitmap, 4 > & sheets, gfx::Tilesheet & tile16_sheet, std::vector< uint8_t > & gfx_bin_data)
Definition at line 15 of file dungeon_map.cc.
References yaze::gfx::Tilesheet::clear(), yaze::core::Renderer::GetInstance(), LoadDungeonMapTile16(), yaze::Rom::mutable_dungeon_palette(), yaze::core::Renderer::RenderBitmap(), yaze::core::FileDialogWrapper::ShowOpenFileDialog(), and yaze::gfx::SnesTo8bppSheet().
LoadDungeonMapTile16()
absl::Status yaze::zelda3::screen::LoadDungeonMapTile16 (const std::vector< uint8_t > & gfx_data, bool bin_mode)
Referenced by LoadDungeonMapGfxFromBinary().
Variable Documentation
kDungeonMapRoomsPtr
int yaze::zelda3::screen::kDungeonMapRoomsPtr = 0x57605 constexpr
Definition at line 15 of file dungeon_map.h.
Referenced by yaze::editor::ScreenEditor::LoadDungeonMaps(), and yaze::editor::ScreenEditor::SaveDungeonMaps().
kDungeonMapFloors
int yaze::zelda3::screen::kDungeonMapFloors = 0x575D9 constexpr
Definition at line 16 of file dungeon_map.h.
Referenced by yaze::editor::ScreenEditor::LoadDungeonMaps().
kDungeonMapGfxPtr
int yaze::zelda3::screen::kDungeonMapGfxPtr = 0x57BE4 constexpr
Definition at line 18 of file dungeon_map.h.
Referenced by yaze::editor::ScreenEditor::LoadDungeonMaps(), and yaze::editor::ScreenEditor::SaveDungeonMaps().
kDungeonMapDataStart
int yaze::zelda3::screen::kDungeonMapDataStart = 0x57039 constexpr
Definition at line 21 of file dungeon_map.h.
kDungeonMapExpCheck
int yaze::zelda3::screen::kDungeonMapExpCheck = 0x56652 constexpr
Definition at line 24 of file dungeon_map.h.
Referenced by yaze::editor::ScreenEditor::LoadDungeonMapTile16(), and yaze::editor::ScreenEditor::SaveDungeonMapTile16().
kDungeonMapTile16
int yaze::zelda3::screen::kDungeonMapTile16 = 0x57009 constexpr
Definition at line 25 of file dungeon_map.h.
Referenced by yaze::editor::ScreenEditor::LoadDungeonMapTile16(), and yaze::editor::ScreenEditor::SaveDungeonMapTile16().
kDungeonMapTile16Expanded
int yaze::zelda3::screen::kDungeonMapTile16Expanded = 0x109010 constexpr
Definition at line 26 of file dungeon_map.h.
Referenced by yaze::editor::ScreenEditor::LoadDungeonMapTile16(), and yaze::editor::ScreenEditor::SaveDungeonMapTile16().
kDungeonMapBossRooms
int yaze::zelda3::screen::kDungeonMapBossRooms = 0x56807 constexpr
Definition at line 29 of file dungeon_map.h.
Referenced by yaze::editor::ScreenEditor::LoadDungeonMaps().
kTriforceVertices
int yaze::zelda3::screen::kTriforceVertices = 0x04FFD2 constexpr
Definition at line 30 of file dungeon_map.h.
kTriforceFaces
int yaze::zelda3::screen::kTriforceFaces = 0x04FFE4 constexpr
Definition at line 31 of file dungeon_map.h.
kCrystalVertices
int yaze::zelda3::screen::kCrystalVertices = 0x04FF98 constexpr
Definition at line 33 of file dungeon_map.h.
kInventoryStart
int yaze::zelda3::screen::kInventoryStart = 0x6564A constexpr
Definition at line 14 of file inventory.h.
kBowItemPos
int yaze::zelda3::screen::kBowItemPos = 0x6F631 constexpr
Definition at line 15 of file inventory.h.
Referenced by yaze::zelda3::screen::Inventory::Create().