yaze: yaze_test::gfx_test::anonymous_namespace{compression_test.cc} Namespace Reference
yaze_test::gfx_test::anonymous_namespace{compression_test.cc} Namespace Reference
Functions
Bytes ExpectCompressOk (Rom &rom, uchar *in, int in_size)
Bytes ExpectDecompressBytesOk (Rom &rom, Bytes &in)
Bytes ExpectDecompressOk (Rom &rom, uchar *in, int in_size)
std::shared_ptr< CompressionPiece > ExpectNewCompressionPieceOk (const char command, const int length, const std::string args, const int argument_length)
void AssertCompressionQuality (const std::vector< uint8_t > &uncompressed_data, const std::vector< uint8_t > &expected_compressed_data)
Bytes ExpectCompressV3Ok (const std::vector< uint8_t > &uncompressed_data, const std::vector< uint8_t > &expected_compressed_data)
std::vector< uint8_t > CreateRepeatedBetweenUncompressable (int leftUncompressedSize, int repeatedByteSize, int rightUncompressedSize)
Function Documentation
ExpectCompressOk()
Bytes yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectCompressOk (Rom & rom, uchar * in, int in_size)
Definition at line 35 of file compression_test.cc.
References ExpectCompressOk(), yaze::app::Rom::LoadFromPointer(), and yaze::app::Rom::vector().
Referenced by ExpectCompressOk().
ExpectDecompressBytesOk()
Bytes yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk (Rom & rom, Bytes & in)
Definition at line 44 of file compression_test.cc.
References yaze::app::Rom::data(), ExpectDecompressBytesOk(), and yaze::app::Rom::LoadFromBytes().
Referenced by ExpectDecompressBytesOk().
ExpectDecompressOk()
Bytes yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectDecompressOk (Rom & rom, uchar * in, int in_size)
Definition at line 53 of file compression_test.cc.
References yaze::app::Rom::data(), ExpectDecompressOk(), and yaze::app::Rom::LoadFromPointer().
Referenced by ExpectDecompressOk().
ExpectNewCompressionPieceOk()
std::shared_ptr< CompressionPiece > yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectNewCompressionPieceOk (const char command, const int length, const std::string args, const int argument_length)
Definition at line 62 of file compression_test.cc.
References ExpectNewCompressionPieceOk().
Referenced by ExpectNewCompressionPieceOk().
AssertCompressionQuality()
void yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::AssertCompressionQuality (const std::vector< uint8_t > & uncompressed_data, const std::vector< uint8_t > & expected_compressed_data)
Definition at line 72 of file compression_test.cc.
References AssertCompressionQuality().
Referenced by AssertCompressionQuality().
ExpectCompressV3Ok()
Bytes yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::ExpectCompressV3Ok (const std::vector< uint8_t > & uncompressed_data, const std::vector< uint8_t > & expected_compressed_data)
Definition at line 82 of file compression_test.cc.
References ExpectCompressV3Ok().
Referenced by ExpectCompressV3Ok().
CreateRepeatedBetweenUncompressable()
std::vector< uint8_t > yaze_test::gfx_test::anonymous_namespace{compression_test.cc}::CreateRepeatedBetweenUncompressable (int leftUncompressedSize, int repeatedByteSize, int rightUncompressedSize)
Definition at line 91 of file compression_test.cc.
References CreateRepeatedBetweenUncompressable().
Referenced by CreateRepeatedBetweenUncompressable().