yaze: yaze::app::emu::memory::dma Namespace Reference
yaze::app::emu::memory::dma Namespace Reference
Functions
void Reset (MemoryImpl *memory)
uint8_t Read (MemoryImpl *memory, uint16_t adr)
void Write (MemoryImpl *memory, uint16_t adr, uint8_t val)
void DoDma (SNES *snes, MemoryImpl *memory, int cpuCycles)
void HandleDma (SNES *snes, MemoryImpl *memory, int cpu_cycles)
void WaitCycle (SNES *snes, MemoryImpl *memory)
void InitHdma (SNES *snes, MemoryImpl *memory, bool do_sync, int cpu_cycles)
void DoHdma (SNES *snes, MemoryImpl *memory, bool do_sync, int cycles)
void TransferByte (SNES *snes, MemoryImpl *memory, uint16_t aAdr, uint8_t aBank, uint8_t bAdr, bool fromB)
void StartDma (MemoryImpl *memory, uint8_t val, bool hdma)
Function Documentation
Reset()
void yaze::app::emu::memory::dma::Reset (MemoryImpl * memory)
Definition at line 17 of file dma.cc.
References yaze::app::emu::memory::MemoryImpl::dma_channels(), yaze::app::emu::memory::MemoryImpl::set_dma_state(), yaze::app::emu::memory::MemoryImpl::set_hdma_init_requested(), and yaze::app::emu::memory::MemoryImpl::set_hdma_run_requested().
Referenced by yaze::app::emu::SNES::Reset().
Read()
uint8_t yaze::app::emu::memory::dma::Read (MemoryImpl * memory, uint16_t adr)
Definition at line 44 of file dma.cc.
References yaze::app::emu::memory::MemoryImpl::dma_channels(), and yaze::app::emu::memory::MemoryImpl::open_bus().
Referenced by yaze::app::emu::SNES::Rread().
Write()
void yaze::app::emu::memory::dma::Write (MemoryImpl * memory, uint16_t adr, uint8_t val)
Definition at line 97 of file dma.cc.
References yaze::app::emu::memory::MemoryImpl::dma_channels().
Referenced by yaze::app::emu::SNES::Write().
DoDma()
void yaze::app::emu::memory::dma::DoDma (SNES * snes, MemoryImpl * memory, int cpuCycles)
Definition at line 161 of file dma.cc.
References yaze::app::emu::SNES::cpu(), yaze::app::emu::memory::MemoryImpl::dma_channels(), yaze::app::emu::SNES::SyncCycles(), TransferByte(), and WaitCycle().
Referenced by HandleDma().
HandleDma()
void yaze::app::emu::memory::dma::HandleDma (SNES * snes, MemoryImpl * memory, int cpu_cycles)
Definition at line 195 of file dma.cc.
References yaze::app::emu::memory::MemoryImpl::dma_state(), DoDma(), DoHdma(), yaze::app::emu::memory::MemoryImpl::hdma_init_requested(), yaze::app::emu::memory::MemoryImpl::hdma_run_requested(), InitHdma(), and yaze::app::emu::memory::MemoryImpl::set_dma_state().
Referenced by yaze::app::emu::SNES::CpuIdle(), yaze::app::emu::SNES::CpuRead(), and yaze::app::emu::SNES::CpuWrite().
WaitCycle()
void yaze::app::emu::memory::dma::WaitCycle (SNES * snes, MemoryImpl * memory)
Definition at line 213 of file dma.cc.
References DoHdma(), yaze::app::emu::memory::MemoryImpl::hdma_init_requested(), yaze::app::emu::memory::MemoryImpl::hdma_run_requested(), InitHdma(), and yaze::app::emu::SNES::RunCycles().
Referenced by DoDma().
InitHdma()
void yaze::app::emu::memory::dma::InitHdma (SNES * snes, MemoryImpl * memory, bool do_sync, int cpu_cycles)
Definition at line 221 of file dma.cc.
References yaze::app::emu::SNES::cpu(), yaze::app::emu::memory::MemoryImpl::dma_channels(), yaze::app::emu::SNES::Read(), yaze::app::emu::SNES::RunCycles(), yaze::app::emu::memory::MemoryImpl::set_hdma_init_requested(), and yaze::app::emu::SNES::SyncCycles().
Referenced by HandleDma(), and WaitCycle().
DoHdma()
void yaze::app::emu::memory::dma::DoHdma (SNES * snes, MemoryImpl * memory, bool do_sync, int cycles)
Definition at line 261 of file dma.cc.
References yaze::app::emu::SNES::cpu(), yaze::app::emu::memory::MemoryImpl::dma_channels(), yaze::app::emu::SNES::Read(), yaze::app::emu::SNES::RunCycles(), yaze::app::emu::memory::MemoryImpl::set_hdma_run_requested(), yaze::app::emu::SNES::SyncCycles(), and TransferByte().
Referenced by HandleDma(), and WaitCycle().
TransferByte()
void yaze::app::emu::memory::dma::TransferByte (SNES * snes, MemoryImpl * memory, uint16_t aAdr, uint8_t aBank, uint8_t bAdr, bool fromB)
Definition at line 336 of file dma.cc.
References yaze::app::emu::memory::MemoryImpl::open_bus(), yaze::app::emu::SNES::Read(), yaze::app::emu::SNES::ReadBBus(), yaze::app::emu::SNES::Write(), and yaze::app::emu::SNES::WriteBBus().
Referenced by DoDma(), and DoHdma().
StartDma()
void yaze::app::emu::memory::dma::StartDma (MemoryImpl * memory, uint8_t val, bool hdma)
Definition at line 358 of file dma.cc.
References yaze::app::emu::memory::MemoryImpl::dma_channels(), and yaze::app::emu::memory::MemoryImpl::set_dma_state().
Referenced by yaze::app::emu::SNES::WriteReg().