yaze: yaze::app::palette_group_internal Namespace Reference
yaze::app::palette_group_internal Namespace Reference
Internal functions for loading palettes by group.
Functions
absl::Status LoadOverworldMainPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAuxiliaryPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAnimatedPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadHUDPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadGlobalSpritePalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadArmorPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSwordPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadShieldPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux1Palettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux2Palettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux3Palettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadDungeonMainPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadGrassColors (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status Load3DObjectPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldMiniMapPalettes (const Bytes &rom_data, gfx::PaletteGroupMap &palette_groups)
Detailed Description
Internal functions for loading palettes by group.
Function Documentation
LoadOverworldMainPalettes()
absl::Status yaze::app::palette_group_internal::LoadOverworldMainPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::overworld_main, yaze::app::core::overworldPaletteMain, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadOverworldAuxiliaryPalettes()
absl::Status yaze::app::palette_group_internal::LoadOverworldAuxiliaryPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::overworld_aux, yaze::app::core::overworldPaletteAuxialiary, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadOverworldAnimatedPalettes()
absl::Status yaze::app::palette_group_internal::LoadOverworldAnimatedPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::overworld_animated, yaze::app::core::overworldPaletteAnimated, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadHUDPalettes()
absl::Status yaze::app::palette_group_internal::LoadHUDPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::hud, yaze::app::core::hudPalettes, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadGlobalSpritePalettes()
absl::Status yaze::app::palette_group_internal::LoadGlobalSpritePalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::global_sprites, yaze::app::core::globalSpritePalettesDW, yaze::app::core::globalSpritePalettesLW, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadArmorPalettes()
absl::Status yaze::app::palette_group_internal::LoadArmorPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::core::armorPalettes, yaze::app::gfx::PaletteGroupMap::armors, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadSwordPalettes()
absl::Status yaze::app::palette_group_internal::LoadSwordPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, yaze::app::core::swordPalettes, and yaze::app::gfx::PaletteGroupMap::swords.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadShieldPalettes()
absl::Status yaze::app::palette_group_internal::LoadShieldPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, yaze::app::core::shieldPalettes, and yaze::app::gfx::PaletteGroupMap::shields.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadSpriteAux1Palettes()
absl::Status yaze::app::palette_group_internal::LoadSpriteAux1Palettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, yaze::app::core::spritePalettesAux1, and yaze::app::gfx::PaletteGroupMap::sprites_aux1.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadSpriteAux2Palettes()
absl::Status yaze::app::palette_group_internal::LoadSpriteAux2Palettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, yaze::app::core::spritePalettesAux2, and yaze::app::gfx::PaletteGroupMap::sprites_aux2.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadSpriteAux3Palettes()
absl::Status yaze::app::palette_group_internal::LoadSpriteAux3Palettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, yaze::app::core::spritePalettesAux3, and yaze::app::gfx::PaletteGroupMap::sprites_aux3.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadDungeonMainPalettes()
absl::Status yaze::app::palette_group_internal::LoadDungeonMainPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::dungeon_main, yaze::app::core::dungeonMainPalettes, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadGrassColors()
absl::Status yaze::app::palette_group_internal::LoadGrassColors (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddColor(), yaze::app::gfx::PaletteGroupMap::grass, yaze::app::core::hardcodedGrassDW, yaze::app::core::hardcodedGrassLW, yaze::app::core::hardcodedGrassSpecial, yaze::app::gfx::ReadColorFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().
Load3DObjectPalettes()
absl::Status yaze::app::palette_group_internal::Load3DObjectPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::core::crystalPalette, yaze::app::gfx::PaletteGroupMap::object_3d, yaze::app::gfx::ReadPaletteFromRom(), RETURN_IF_ERROR, and yaze::app::core::triforcePalette.
Referenced by yaze::app::ROM::LoadAllPalettes().
LoadOverworldMiniMapPalettes()
absl::Status yaze::app::palette_group_internal::LoadOverworldMiniMapPalettes (const Bytes & rom_data, gfx::PaletteGroupMap & palette_groups)
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::overworld_mini_map, yaze::app::core::overworldMiniMapPalettes, yaze::app::gfx::ReadPaletteFromRom(), and RETURN_IF_ERROR.
Referenced by yaze::app::ROM::LoadAllPalettes().