yaze: yaze::app::zelda3::overworld::palette_internal Namespace Reference
yaze::app::zelda3::overworld::palette_internal Namespace Reference
Functions
absl::Status SetColorsPalette (Rom &rom, int index, gfx::SnesPalette &current, gfx::SnesPalette main, gfx::SnesPalette animated, gfx::SnesPalette aux1, gfx::SnesPalette aux2, gfx::SnesPalette hud, gfx::SnesColor bgrcolor, gfx::SnesPalette spr, gfx::SnesPalette spr2)
Function Documentation
SetColorsPalette()
absl::Status yaze::app::zelda3::overworld::palette_internal::SetColorsPalette (Rom & rom, int index, gfx::SnesPalette & current, gfx::SnesPalette main, gfx::SnesPalette animated, gfx::SnesPalette aux1, gfx::SnesPalette aux2, gfx::SnesPalette hud, gfx::SnesColor bgrcolor, gfx::SnesPalette spr, gfx::SnesPalette spr2)
Definition at line 237 of file overworld_map.cc.
References yaze::app::gfx::SnesPalette::Create(), main(), and yaze::app::Rom::palette_group().
Referenced by yaze::app::zelda3::overworld::OverworldMap::LoadPalette().