yaze: yaze::gui::zeml Namespace Reference
yaze::gui::zeml Namespace Reference
Zelda Editor Markup Language Functions.
Classes
struct Action
struct Node
Node for a zeml tree.
struct Token
struct WidgetAttributes
Attributes for a widget.
Enumerations
enum class TokenType {
Identifier , String , OpenBrace , CloseBrace ,
Comma , EndOfStream
}
enum class WidgetType {
Window , Button , Slider , Text ,
Table , TableSetupColumn , TableHeadersRow , TableNextColumn ,
CollapsingHeader , Columns , Checkbox , Selectable ,
Function , BeginChild , BeginMenuBar , BeginMenu ,
BeginTabBar , BeginTabItem , MenuItem , Separator ,
HexInputByte , HexInputWord , Canvas , Definition
}
enum class ActionType { Click , Change , Run }
Functions
std::vector< Token > Tokenize (const std::string &input)
Tokenize a zeml string.
WidgetType MapType (const std::string &type)
Map a string to a widget type.
Node ParseNode (const std::vector< Token > &tokens, size_t &index, const std::map< std::string, void * > &data_bindings={}, const std::map< std::string, Node > &definitions={})
Parse a zeml node.
void ParseFlags (const WidgetType &type, const std::string &flags, WidgetAttributes &attributes)
WidgetAttributes ParseAttributes (const std::vector< Token > &tokens, size_t &index, const WidgetType &type, const std::map< std::string, void * > &data_bindings={})
ParseNode attributes for a widget.
Node Parse (const std::string &yazon_input, const std::map< std::string, void * > &data_bindings={})
Parse a zeml string.
void Render (Node &node)
Render a zeml tree.
void ExecuteActions (const std::vector< Action > &actions, ActionType type)
Execute actions for a node.
void Bind (Node *node, std::function< void()> callback)
Bind a callback to a node.
void BindAction (Node *node, ActionType type, std::function< void()> callback)
Bind an action to a node.
void BindSelectable (Node *node, bool *selected, std::function< void()> callback)
Bind a selectable node.
std::string LoadFile (const std::string &filename)
void ParseDefinitions (const std::vector< Token > &tokens, size_t &index, std::map< std::string, Node > &definitions)
Parse a zeml definition.
Detailed Description
Zelda Editor Markup Language Functions.
Enumeration Type Documentation
TokenType
enum class yaze::gui::zeml::TokenType strong
Enumerator
Identifier
String
OpenBrace
CloseBrace
Comma
EndOfStream
Definition at line 25 of file zeml.h.
WidgetType
enum class yaze::gui::zeml::WidgetType strong
Enumerator
Window
Button
Slider
Text
Table
TableSetupColumn
TableHeadersRow
TableNextColumn
CollapsingHeader
Columns
Checkbox
Selectable
Function
BeginChild
BeginMenuBar
BeginMenu
BeginTabBar
BeginTabItem
MenuItem
Separator
HexInputByte
HexInputWord
Canvas
Definition
Definition at line 45 of file zeml.h.
ActionType
enum class yaze::gui::zeml::ActionType strong
Enumerator
Click
Change
Run
Definition at line 105 of file zeml.h.
Function Documentation
Tokenize()
std::vector< Token > yaze::gui::zeml::Tokenize (const std::string & input)
Tokenize a zeml string.
Definition at line 21 of file zeml.cc.
References CloseBrace, Comma, EndOfStream, Identifier, OpenBrace, and String.
Referenced by Parse().
MapType()
WidgetType yaze::gui::zeml::MapType (const std::string & type)
Map a string to a widget type.
Definition at line 56 of file zeml.cc.
References BeginChild, BeginMenu, BeginMenuBar, BeginTabBar, BeginTabItem, Button, Canvas, Checkbox, CollapsingHeader, Columns, Definition, Function, HexInputByte, HexInputWord, MenuItem, Selectable, Separator, Slider, Table, TableHeadersRow, TableNextColumn, TableSetupColumn, Text, and Window.
Referenced by ParseNode().
ParseNode()
Node yaze::gui::zeml::ParseNode (const std::vector< Token > & tokens, size_t & index, const std::map< std::string, void * > & data_bindings, const std::map< std::string, Node > & definitions)
Parse a zeml node.
Definition at line 86 of file zeml.cc.
References yaze::gui::zeml::Node::attributes, yaze::gui::zeml::Node::children, CloseBrace, Comma, Definition, EndOfStream, Identifier, MapType(), OpenBrace, ParseAttributes(), ParseNode(), yaze::gui::zeml::Node::type, yaze::gui::zeml::Token::type, and yaze::gui::zeml::Token::value.
Referenced by Parse(), and ParseNode().
ParseFlags()
void yaze::gui::zeml::ParseFlags (const WidgetType & type, const std::string & flags, WidgetAttributes & attributes)
Definition at line 134 of file zeml.cc.
References BeginChild, CollapsingHeader, yaze::gui::zeml::WidgetAttributes::flags, Table, and TableSetupColumn.
Referenced by ParseAttributes().
ParseAttributes()
WidgetAttributes yaze::gui::zeml::ParseAttributes (const std::vector< Token > & tokens, size_t & index, const WidgetType & type, const std::map< std::string, void * > & data_bindings)
ParseNode attributes for a widget.
Definition at line 304 of file zeml.cc.
References CloseBrace, yaze::gui::zeml::WidgetAttributes::count, yaze::gui::zeml::WidgetAttributes::data, yaze::gui::zeml::WidgetAttributes::id, Identifier, yaze::gui::zeml::WidgetAttributes::max, yaze::gui::zeml::WidgetAttributes::min, ParseFlags(), yaze::gui::zeml::WidgetAttributes::size, String, yaze::gui::zeml::WidgetAttributes::text, yaze::gui::zeml::WidgetAttributes::title, yaze::gui::zeml::Token::value, yaze::gui::zeml::WidgetAttributes::value, and yaze::gui::zeml::WidgetAttributes::width.
Referenced by ParseNode().
Parse()
Node yaze::gui::zeml::Parse (const std::string & yazon_input, const std::map< std::string, void * > & data_bindings)
Parse a zeml string.
Definition at line 359 of file zeml.cc.
References ParseNode(), and Tokenize().
Referenced by yaze::emu::Emulator::Emulator(), yaze::editor::OverworldEditor::InitializeZeml(), and yaze::emu::Emulator::RenderNavBar().
Render()
void yaze::gui::zeml::Render (Node & node)
Render a zeml tree.
Definition at line 380 of file zeml.cc.
References yaze::gui::zeml::Node::actions, yaze::gui::zeml::Node::attributes, BeginChild, BeginMenu, BeginMenuBar, BeginTabBar, BeginTabItem, Button, Canvas, Change, Checkbox, yaze::gui::zeml::Node::children, Click, CollapsingHeader, Columns, yaze::gui::zeml::WidgetAttributes::count, yaze::gui::zeml::WidgetAttributes::data, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), ExecuteActions(), yaze::gui::zeml::WidgetAttributes::flags, Function, HexInputByte, HexInputWord, yaze::gui::zeml::WidgetAttributes::id, yaze::gui::InputHexByte(), yaze::gui::InputHexWord(), MenuItem, Render(), Selectable, yaze::gui::zeml::WidgetAttributes::selected, Separator, yaze::gui::zeml::WidgetAttributes::size, Table, TableHeadersRow, TableNextColumn, TableSetupColumn, Text, yaze::gui::zeml::WidgetAttributes::text, yaze::gui::zeml::WidgetAttributes::title, yaze::gui::zeml::Node::type, and Window.
Referenced by Render(), yaze::emu::Emulator::RenderNavBar(), yaze::emu::Emulator::Run(), and yaze::editor::OverworldEditor::Update().
ExecuteActions()
void yaze::gui::zeml::ExecuteActions (const std::vector< Action > & actions, ActionType type)
Execute actions for a node.
Definition at line 558 of file zeml.cc.
Referenced by Render().
Bind()
void yaze::gui::zeml::Bind (Node * node, std::function< void()> callback)
Bind a callback to a node.
Definition at line 566 of file zeml.cc.
References yaze::gui::zeml::Node::actions, and Click.
Referenced by yaze::editor::OverworldEditor::InitializeZeml().
BindAction()
void yaze::gui::zeml::BindAction (Node * node, ActionType type, std::function< void()> callback)
Bind an action to a node.
Definition at line 573 of file zeml.cc.
References yaze::gui::zeml::Node::actions.
BindSelectable()
void yaze::gui::zeml::BindSelectable (Node * node, bool * selected, std::function< void()> callback)
Bind a selectable node.
Definition at line 580 of file zeml.cc.
References yaze::gui::zeml::Node::actions, yaze::gui::zeml::Node::attributes, Click, and yaze::gui::zeml::WidgetAttributes::selected.
LoadFile()
std::string yaze::gui::zeml::LoadFile (const std::string & filename)
Definition at line 589 of file zeml.cc.
References yaze::core::GetBundleResourcePath().
Referenced by yaze::editor::OverworldEditor::InitializeZeml().
ParseDefinitions()
void yaze::gui::zeml::ParseDefinitions (const std::vector< Token > & tokens, size_t & index, std::map< std::string, Node > & definitions)
Parse a zeml definition.