yaze: yaze::app::editor::anonymous_namespace{gfx_group_editor.cc} Namespace Reference
yaze::app::editor::anonymous_namespace{gfx_group_editor.cc} Namespace Reference
Functions
void DrawPaletteFromPaletteGroup (gfx::SnesPalette &palette)
Function Documentation
DrawPaletteFromPaletteGroup()
void yaze::app::editor::anonymous_namespace{gfx_group_editor.cc}::DrawPaletteFromPaletteGroup (gfx::SnesPalette & palette)
Definition at line 218 of file gfx_group_editor.cc.
References DrawPaletteFromPaletteGroup(), yaze::app::gfx::SnesPalette::empty(), yaze::app::gfx::SnesPalette::size(), and yaze::app::gui::SnesColorButton().
Referenced by DrawPaletteFromPaletteGroup().