yaze: yaze::app::gfx::anonymous_namespace{bitmap.cc} Namespace Reference
yaze::app::gfx::anonymous_namespace{bitmap.cc} Namespace Reference
Functions
void GrayscalePalette (SDL_Palette *palette)
void PngWriteCallback (png_structp png_ptr, png_bytep data, png_size_t length)
void PngReadCallback (png_structp png_ptr, png_bytep outBytes, png_size_t byteCountToRead)
Function Documentation
GrayscalePalette()
void yaze::app::gfx::anonymous_namespace{bitmap.cc}::GrayscalePalette (SDL_Palette * palette)
References GrayscalePalette().
Referenced by GrayscalePalette().
PngReadCallback()
void yaze::app::gfx::anonymous_namespace{bitmap.cc}::PngReadCallback (png_structp png_ptr, png_bytep outBytes, png_size_t byteCountToRead)
References PngReadCallback().
Referenced by PngReadCallback().
PngWriteCallback()
void yaze::app::gfx::anonymous_namespace{bitmap.cc}::PngWriteCallback (png_structp png_ptr, png_bytep data, png_size_t length)
References PngWriteCallback().
Referenced by PngWriteCallback().