yaze: yaze::app::core::anonymous_namespace{controller.cc} Namespace Reference
yaze::app::core::anonymous_namespace{controller.cc} Namespace Reference
Functions
void NewMasterFrame ()
void InitializeKeymap ()
void ImGui_ImplSDL2_SetClipboardText (void *user_data, const char *text)
const char * ImGui_ImplSDL2_GetClipboardText (void *user_data)
void InitializeClipboard ()
void HandleKeyDown (SDL_Event &event, editor::MasterEditor &editor)
void HandleKeyUp (SDL_Event &event, editor::MasterEditor &editor)
void ChangeWindowSizeEvent (SDL_Event &event)
void HandleMouseMovement (int &wheel)
Variables
constexpr ImGuiWindowFlags kMainEditorFlags
Function Documentation
NewMasterFrame()
void yaze::app::core::anonymous_namespace{controller.cc}::NewMasterFrame ()
References kMainEditorFlags, yaze::app::gui::kZeroPos, and NewMasterFrame().
Referenced by NewMasterFrame().
InitializeKeymap()
void yaze::app::core::anonymous_namespace{controller.cc}::InitializeKeymap ()
References InitializeKeymap().
Referenced by InitializeKeymap().
ImGui_ImplSDL2_SetClipboardText()
void yaze::app::core::anonymous_namespace{controller.cc}::ImGui_ImplSDL2_SetClipboardText (void * user_data, const char * text)
References ImGui_ImplSDL2_SetClipboardText().
Referenced by ImGui_ImplSDL2_SetClipboardText(), and InitializeClipboard().
ImGui_ImplSDL2_GetClipboardText()
const char * yaze::app::core::anonymous_namespace{controller.cc}::ImGui_ImplSDL2_GetClipboardText (void * user_data)
References ImGui_ImplSDL2_GetClipboardText().
Referenced by ImGui_ImplSDL2_GetClipboardText(), and InitializeClipboard().
InitializeClipboard()
void yaze::app::core::anonymous_namespace{controller.cc}::InitializeClipboard ()
References ImGui_ImplSDL2_GetClipboardText(), ImGui_ImplSDL2_SetClipboardText(), and InitializeClipboard().
Referenced by InitializeClipboard().
HandleKeyDown()
void yaze::app::core::anonymous_namespace{controller.cc}::HandleKeyDown (SDL_Event & event, editor::MasterEditor & editor)
References yaze::app::editor::MasterEditor::emulator(), and HandleKeyDown().
Referenced by HandleKeyDown().
HandleKeyUp()
void yaze::app::core::anonymous_namespace{controller.cc}::HandleKeyUp (SDL_Event & event, editor::MasterEditor & editor)
References yaze::app::editor::MasterEditor::emulator(), and HandleKeyUp().
Referenced by HandleKeyUp().
ChangeWindowSizeEvent()
void yaze::app::core::anonymous_namespace{controller.cc}::ChangeWindowSizeEvent (SDL_Event & event)
References ChangeWindowSizeEvent().
Referenced by ChangeWindowSizeEvent().
HandleMouseMovement()
void yaze::app::core::anonymous_namespace{controller.cc}::HandleMouseMovement (int & wheel)
References HandleMouseMovement().
Referenced by HandleMouseMovement().
Variable Documentation
kMainEditorFlags
ImGuiWindowFlags yaze::app::core::anonymous_namespace{controller.cc}::kMainEditorFlags constexpr
Initial value:
=
    ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse |
    ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_MenuBar |
    ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoTitleBar
Referenced by NewMasterFrame().