yaze: yaze::app::editor Namespace Reference
yaze::app::editor Namespace Reference
Editors are the view controllers for the application.
Namespaces
namespace anonymous_namespace{assembly_editor.cc}
namespace anonymous_namespace{dungeon_editor.cc}
namespace anonymous_namespace{editor_manager.cc}
namespace anonymous_namespace{gfx_group_editor.cc}
namespace anonymous_namespace{palette_editor.cc}
namespace context
namespace palette_internal
namespace zsprite
Namespace for the ZSprite format from Zarby's ZSpriteMaker.
Classes
class AssemblyEditor
Text editor for modifying assembly code.
class Command
class CommandManager
class DungeonEditor
DungeonEditor class for editing dungeons.
class Editor
Interface for editor classes.
class EditorManager
The EditorManager controls the main editor window and manages the various editor classes.
class EntranceContext
struct ExampleAppPropertyEditor
struct ExampleMemberInfo
struct ExampleTreeNode
class ExtensionManager
struct FlagsMenu
class GfxGroupEditor
Manage graphics group configurations in a Rom.
class GraphicsEditor
Allows the user to edit graphics sheets from the game or view prototype graphics.
struct MemoryEditorWithDiffChecker
struct MessageData
class MessageEditor
class MusicEditor
A class for editing music data in a Rom.
class OverworldEditor
Manipulates the Overworld and OverworldMap data in a Rom.
class PaletteEditor
Allows the user to view and edit in game palettes.
struct ParsedElement
class RecentFilesManager
class ScreenEditor
The ScreenEditor class allows the user to edit a variety of screens in the game or create a custom menu.
class SettingsEditor
class SpriteEditor
Allows the user to edit sprites.
struct SpriteItem
struct TextElement
class Tile16Editor
Popup window to edit Tile16 data.
Enumerations
enum MyItemColumnID {
MyItemColumnID_ID , MyItemColumnID_Name , MyItemColumnID_Action , MyItemColumnID_Quantity ,
MyItemColumnID_Description
}
enum class EditorType {
kAssembly , kDungeon , kGraphics , kMusic ,
kOverworld , kPalette , kScreen , kSprite ,
kMessage , kSettings
}
Functions
uint8_t FindMatchingCharacter (char value)
uint8_t FindDictionaryEntry (uint8_t value)
TextElement FindMatchingCommand (uint8_t b)
TextElement FindMatchingSpecial (uint8_t value)
ParsedElement FindMatchingElement (const std::string &str)
std::string ParseTextDataByte (uint8_t value)
std::vector< uint8_t > ParseMessageToData (std::string str)
std::string ReplaceAllDictionaryWords (std::string str)
bool IsMouseHoveringOverEntity (const zelda3::GameEntity &entity, ImVec2 canvas_p0, ImVec2 scrolling)
void MoveEntityOnGrid (zelda3::GameEntity *entity, ImVec2 canvas_p0, ImVec2 scrolling, bool free_movement)
void HandleEntityDragging (zelda3::GameEntity *entity, ImVec2 canvas_p0, ImVec2 scrolling, bool &is_dragging_entity, zelda3::GameEntity *&dragged_entity, zelda3::GameEntity *&current_entity, bool free_movement)
bool DrawEntranceInserterPopup ()
bool DrawOverworldEntrancePopup (zelda3::overworld::OverworldEntrance &entrance)
void DrawExitInserterPopup ()
bool DrawExitEditorPopup (zelda3::overworld::OverworldExit &exit)
void DrawItemInsertPopup ()
bool DrawItemEditorPopup (zelda3::overworld::OverworldItem &item)
void DrawSpriteTable (std::function< void(int)> onSpriteSelect)
void DrawSpriteInserterPopup ()
bool DrawSpriteEditorPopup (zelda3::Sprite &sprite)
constexpr ImVec2 kOverworldCanvasSize (kOverworldMapSize *8, kOverworldMapSize *8)
constexpr ImVec2 kCurrentGfxCanvasSize (0x100+1, 0x10 *0x40+1)
constexpr ImVec2 kBlocksetCanvasSize (0x100+1, 0x2000+1)
constexpr ImVec2 kGraphicsBinCanvasSize (0x100+1, kNumSheetsToLoad *0x40+1)
Variables
constexpr ImGuiTableFlags kDungeonObjectTableFlags
constexpr ImGuiTabItemFlags kDungeonTabFlags
constexpr ImGuiTabBarFlags kDungeonTabBarFlags
constexpr ImGuiTableFlags kDungeonTableFlags
constexpr ImGuiTableFlags kGfxEditTableFlags
constexpr ImGuiTabBarFlags kGfxEditTabBarFlags
constexpr ImGuiTableFlags kGfxEditFlags
const std::string kSuperDonkeyTiles []
const std::string kSuperDonkeySprites []
constexpr ImGuiTableFlags kPaletteTableFlags
constexpr ImGuiColorEditFlags kPalNoAlpha = ImGuiColorEditFlags_NoAlpha
constexpr ImGuiColorEditFlags kPalButtonFlags2
constexpr ImGuiColorEditFlags kColorPopupFlags
constexpr uint32_t kRedPen = 0xFF0000FF
const uint8_t kMessageTerminator = 0x7F
const std::string BANKToken = "BANK"
const std::string DICTIONARYTOKEN = "D"
constexpr uint8_t DICTOFF = 0x88
const std::string CHEESE = "\uBEBE"
constexpr int kGfxFont = 0x70000
constexpr int kTextData = 0xE0000
constexpr int kTextDataEnd = 0xE7FFF
constexpr int kTextData2 = 0x75F40
constexpr int kTextData2End = 0x773FF
constexpr int kPointersDictionaries = 0x74703
constexpr int kCharactersWidth = 0x74ADF
constexpr int kNumDictionaryEntries = 97
constexpr int kNumMessages = 396
constexpr uint8_t kBlockTerminator = 0x80
constexpr uint8_t BANKID = 0x80
constexpr uint8_t kScrollVertical = 0x73
constexpr uint8_t kLine1 = 0x74
constexpr uint8_t kLine2 = 0x75
constexpr uint8_t kLine3 = 0x76
constexpr int kTile16Size = 0x10
constexpr std::array< const char *, 8 > kMapSettingsColumnNames
constexpr uint k4BPP = 4
constexpr uint kByteSize = 3
constexpr uint kMessageIdSize = 5
constexpr uint kNumSheetsToLoad = 223
constexpr uint kTile8DisplayHeight = 64
constexpr uint kOverworldMapSize = 0x200
constexpr uint kNumTile16Individual = 4096
constexpr float kInputFieldSize = 30.f
constexpr ImGuiTableFlags kOWMapFlags
constexpr ImGuiTableFlags kToolsetTableFlags = ImGuiTableFlags_SizingFixedFit
constexpr ImGuiTableFlags kOWEditFlags
constexpr absl::string_view kWorldList
constexpr absl::string_view kGamePartComboString = "Part 0\0Part 1\0Part 2\0"
constexpr absl::string_view kTileSelectorTab = "##TileSelectorTabBar"
constexpr absl::string_view kOWEditTable = "##OWEditTable"
constexpr absl::string_view kOWMapTable = "#MapSettingsTable"
constexpr ImGuiTabItemFlags kSpriteTabFlags
constexpr ImGuiTabBarFlags kSpriteTabBarFlags
constexpr ImGuiTableFlags kSpriteTableFlags
constexpr std::array< const char *, 10 > kEditorNames
Detailed Description
Editors are the view controllers for the application.
Enumeration Type Documentation
MyItemColumnID
enum yaze::app::editor::MyItemColumnID
Enumerator
MyItemColumnID_ID
MyItemColumnID_Name
MyItemColumnID_Action
MyItemColumnID_Quantity
MyItemColumnID_Description
Definition at line 36 of file entity.h.
EditorType
enum class yaze::app::editor::EditorType strong
Enumerator
kAssembly
kDungeon
kGraphics
kMusic
kOverworld
kPalette
kScreen
kSprite
kMessage
kSettings
Definition at line 15 of file editor.h.
Function Documentation
FindMatchingCharacter()
uint8_t yaze::app::editor::FindMatchingCharacter (char value)
Definition at line 9 of file message_data.cc.
Referenced by yaze::app::editor::MessageEditor::DrawCharacterToPreview(), and ParseMessageToData().
FindDictionaryEntry()
uint8_t yaze::app::editor::FindDictionaryEntry (uint8_t value)
Definition at line 18 of file message_data.cc.
References DICTOFF.
Referenced by ParseTextDataByte(), yaze::app::editor::MessageEditor::ReadAllTextData(), and yaze::app::editor::MessageEditor::ReadAllTextDataV2().
FindMatchingCommand()
TextElement yaze::app::editor::FindMatchingCommand (uint8_t b)
Definition at line 25 of file message_data.cc.
Referenced by yaze::app::editor::MessageEditor::Initialize(), ParseTextDataByte(), yaze::app::editor::MessageEditor::ReadAllTextData(), and yaze::app::editor::MessageEditor::ReadAllTextDataV2().
FindMatchingSpecial()
TextElement yaze::app::editor::FindMatchingSpecial (uint8_t value)
Definition at line 35 of file message_data.cc.
Referenced by ParseTextDataByte(), yaze::app::editor::MessageEditor::ReadAllTextData(), and yaze::app::editor::MessageEditor::ReadAllTextDataV2().
FindMatchingElement()
ParsedElement yaze::app::editor::FindMatchingElement (const std::string & str)
Definition at line 47 of file message_data.cc.
References DICTIONARYTOKEN, and DICTOFF.
Referenced by ParseMessageToData().
ParseTextDataByte()
std::string yaze::app::editor::ParseTextDataByte (uint8_t value)
Definition at line 72 of file message_data.cc.
References DICTIONARYTOKEN, yaze::app::editor::TextElement::Empty(), FindDictionaryEntry(), FindMatchingCommand(), FindMatchingSpecial(), and yaze::app::editor::TextElement::GenericToken.
Referenced by yaze::app::editor::MessageEditor::BuildDictionaryEntries(), yaze::app::editor::MessageEditor::ReadAllTextData(), and yaze::app::editor::MessageEditor::ReadAllTextDataV2().
ParseMessageToData()
std::vector< uint8_t > yaze::app::editor::ParseMessageToData (std::string str)
Definition at line 101 of file message_data.cc.
References yaze::app::editor::ParsedElement::Active, DICTIONARYTOKEN, FindMatchingCharacter(), FindMatchingElement(), yaze::app::editor::TextElement::HasArgument, yaze::app::editor::TextElement::ID, yaze::app::editor::ParsedElement::Parent, and yaze::app::editor::ParsedElement::Value.
Referenced by yaze::app::editor::MessageEditor::DictionaryEntry::DictionaryEntry(), and yaze::app::editor::MessageEditor::DrawCurrentMessage().
ReplaceAllDictionaryWords()
std::string yaze::app::editor::ReplaceAllDictionaryWords (std::string str)
Definition at line 491 of file message_editor.cc.
Referenced by yaze::app::editor::MessageData::OptimizeMessageForDictionary().
IsMouseHoveringOverEntity()
bool yaze::app::editor::IsMouseHoveringOverEntity (const zelda3::GameEntity & entity, ImVec2 canvas_p0, ImVec2 scrolling)
Definition at line 19 of file entity.cc.
References yaze::app::zelda3::GameEntity::x_, and yaze::app::zelda3::GameEntity::y_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), yaze::app::editor::OverworldEditor::DrawOverworldSprites(), and HandleEntityDragging().
MoveEntityOnGrid()
void yaze::app::editor::MoveEntityOnGrid (zelda3::GameEntity * entity, ImVec2 canvas_p0, ImVec2 scrolling, bool free_movement)
Definition at line 34 of file entity.cc.
References yaze::app::zelda3::GameEntity::set_x(), and yaze::app::zelda3::GameEntity::set_y().
Referenced by HandleEntityDragging().
HandleEntityDragging()
void yaze::app::editor::HandleEntityDragging (zelda3::GameEntity * entity, ImVec2 canvas_p0, ImVec2 scrolling, bool & is_dragging_entity, zelda3::GameEntity *& dragged_entity, zelda3::GameEntity *& current_entity, bool free_movement)
Definition at line 54 of file entity.cc.
References yaze::app::zelda3::GameEntity::entity_id_, yaze::app::zelda3::GameEntity::entity_type_, IsMouseHoveringOverEntity(), yaze::app::zelda3::GameEntity::kEntrance, yaze::app::zelda3::GameEntity::kExit, yaze::app::zelda3::GameEntity::kItem, yaze::app::zelda3::GameEntity::kSprite, yaze::app::zelda3::GameEntity::map_id_, MoveEntityOnGrid(), yaze::app::zelda3::GameEntity::UpdateMapProperties(), yaze::app::core::UppercaseHexByte(), yaze::app::zelda3::GameEntity::x_, and yaze::app::zelda3::GameEntity::y_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), and yaze::app::editor::OverworldEditor::DrawOverworldSprites().
DrawEntranceInserterPopup()
bool yaze::app::editor::DrawEntranceInserterPopup ()
Definition at line 103 of file entity.cc.
References ICON_MD_CANCEL, ICON_MD_DONE, and yaze::app::gui::InputHex().
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances().
DrawOverworldEntrancePopup()
bool yaze::app::editor::DrawOverworldEntrancePopup (zelda3::overworld::OverworldEntrance & entrance)
Todo
Implement deleting OverworldEntrance objects, currently only hides them
Definition at line 128 of file entity.cc.
References yaze::app::zelda3::overworld::OverworldEntrance::deleted, yaze::app::zelda3::overworld::OverworldEntrance::entrance_id_, ICON_MD_CANCEL, ICON_MD_DELETE, ICON_MD_DONE, yaze::app::gui::InputHex(), yaze::app::gui::InputHexByte(), yaze::app::gui::InputHexWord(), kInputFieldSize, yaze::app::zelda3::GameEntity::map_id_, yaze::app::zelda3::GameEntity::x_, and yaze::app::zelda3::GameEntity::y_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances().
DrawExitInserterPopup()
void yaze::app::editor::DrawExitInserterPopup ()
Todo
Implement deleting OverworldExit objects
Definition at line 161 of file entity.cc.
References ICON_MD_CANCEL, ICON_MD_DONE, and yaze::app::gui::InputHex().
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldExits().
DrawExitEditorPopup()
bool yaze::app::editor::DrawExitEditorPopup (zelda3::overworld::OverworldExit & exit)
Definition at line 179 of file entity.cc.
References yaze::app::zelda3::overworld::OverworldExit::deleted_, yaze::app::zelda3::overworld::OverworldExit::door_type_1_, yaze::app::zelda3::overworld::OverworldExit::door_type_2_, yaze::app::zelda3::GameEntity::entity_id_, ICON_MD_CANCEL, ICON_MD_DELETE, ICON_MD_DONE, yaze::app::gui::InputHex(), yaze::app::gui::InputHexByte(), yaze::app::gui::InputHexWord(), yaze::app::zelda3::overworld::OverworldExit::is_automatic_, yaze::app::zelda3::overworld::OverworldExit::is_hole_, yaze::app::zelda3::overworld::OverworldExit::large_map_, yaze::app::zelda3::GameEntity::map_id_, yaze::app::zelda3::overworld::OverworldExit::room_id_, yaze::app::gui::TextWithSeparators(), yaze::app::zelda3::GameEntity::x_, yaze::app::zelda3::overworld::OverworldExit::x_camera_, yaze::app::zelda3::overworld::OverworldExit::x_scroll_, yaze::app::zelda3::GameEntity::y_, yaze::app::zelda3::overworld::OverworldExit::y_camera_, and yaze::app::zelda3::overworld::OverworldExit::y_scroll_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldExits().
DrawItemInsertPopup()
void yaze::app::editor::DrawItemInsertPopup ()
Definition at line 311 of file entity.cc.
References ICON_MD_CANCEL, ICON_MD_DONE, and yaze::app::zelda3::overworld::kSecretItemNames.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldItems().
DrawItemEditorPopup()
bool yaze::app::editor::DrawItemEditorPopup (zelda3::overworld::OverworldItem & item)
Todo
Implement deleting OverworldItem objects, currently only hides them
Definition at line 342 of file entity.cc.
References yaze::app::zelda3::overworld::OverworldItem::deleted, ICON_MD_CLOSE, ICON_MD_DELETE, ICON_MD_DONE, yaze::app::zelda3::overworld::OverworldItem::id_, and yaze::app::zelda3::overworld::kSecretItemNames.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldItems().
DrawSpriteTable()
void yaze::app::editor::DrawSpriteTable (std::function< void(int)> onSpriteSelect)
Definition at line 380 of file entity.cc.
References MyItemColumnID_ID, MyItemColumnID_Name, and yaze::app::editor::SpriteItem::SortWithSortSpecs().
Referenced by DrawSpriteEditorPopup(), and DrawSpriteInserterPopup().
DrawSpriteInserterPopup()
void yaze::app::editor::DrawSpriteInserterPopup ()
Todo
Implement deleting OverworldSprite objects
Definition at line 429 of file entity.cc.
References DrawSpriteTable(), ICON_MD_CANCEL, and ICON_MD_DONE.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldSprites().
DrawSpriteEditorPopup()
bool yaze::app::editor::DrawSpriteEditorPopup (zelda3::Sprite & sprite)
Definition at line 453 of file entity.cc.
References DrawSpriteTable(), ICON_MD_CLOSE, ICON_MD_DELETE, ICON_MD_DONE, yaze::app::zelda3::Sprite::map_id(), yaze::app::zelda3::Sprite::name(), yaze::app::zelda3::Sprite::set_deleted(), yaze::app::zelda3::Sprite::set_id(), and yaze::app::zelda3::Sprite::UpdateMapProperties().
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldSprites().
kOverworldCanvasSize()
ImVec2 yaze::app::editor::kOverworldCanvasSize (kOverworldMapSize * 8, kOverworldMapSize * 8) constexpr
kCurrentGfxCanvasSize()
ImVec2 yaze::app::editor::kCurrentGfxCanvasSize (0x100+ 1, 0x10 *0x40+ 1) constexpr
kBlocksetCanvasSize()
ImVec2 yaze::app::editor::kBlocksetCanvasSize (0x100+ 1, 0x2000+ 1) constexpr
kGraphicsBinCanvasSize()
ImVec2 yaze::app::editor::kGraphicsBinCanvasSize (0x100+ 1, kNumSheetsToLoad *0x40+ 1) constexpr
Variable Documentation
kDungeonObjectTableFlags
ImGuiTableFlags yaze::app::editor::kDungeonObjectTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 37 of file dungeon_editor.cc.
Referenced by yaze::app::editor::DungeonEditor::DrawObjectRenderer().
kDungeonTabFlags
ImGuiTabItemFlags yaze::app::editor::kDungeonTabFlags constexpr
Initial value:
=
    ImGuiTabItemFlags_Trailing | ImGuiTabItemFlags_NoTooltip
Definition at line 21 of file dungeon_editor.h.
Referenced by yaze::app::editor::DungeonEditor::DrawDungeonTabView().
kDungeonTabBarFlags
ImGuiTabBarFlags yaze::app::editor::kDungeonTabBarFlags constexpr
Initial value:
=
    ImGuiTabBarFlags_AutoSelectNewTabs | ImGuiTabBarFlags_Reorderable |
    ImGuiTabBarFlags_FittingPolicyResizeDown |
    ImGuiTabBarFlags_TabListPopupButton
Definition at line 24 of file dungeon_editor.h.
Referenced by yaze::app::editor::DungeonEditor::DrawDungeonTabView().
kDungeonTableFlags
ImGuiTableFlags yaze::app::editor::kDungeonTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 29 of file dungeon_editor.h.
Referenced by yaze::app::editor::DungeonEditor::DrawUsageStats(), and yaze::app::editor::DungeonEditor::UpdateDungeonRoomView().
kGfxEditTableFlags
ImGuiTableFlags yaze::app::editor::kGfxEditTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Borders | ImGuiTableFlags_Resizable |
    ImGuiTableFlags_Reorderable | ImGuiTableFlags_Hideable |
    ImGuiTableFlags_SizingFixedFit
Definition at line 42 of file graphics_editor.cc.
Referenced by yaze::app::editor::GraphicsEditor::UpdateGfxEdit(), and yaze::app::editor::GraphicsEditor::UpdateLinkGfxView().
kGfxEditTabBarFlags
ImGuiTabBarFlags yaze::app::editor::kGfxEditTabBarFlags constexpr
Initial value:
=
    ImGuiTabBarFlags_AutoSelectNewTabs | ImGuiTabBarFlags_Reorderable |
    ImGuiTabBarFlags_FittingPolicyResizeDown |
    ImGuiTabBarFlags_TabListPopupButton
Definition at line 47 of file graphics_editor.cc.
Referenced by yaze::app::editor::GraphicsEditor::UpdateGfxTabView().
kGfxEditFlags
ImGuiTableFlags yaze::app::editor::kGfxEditFlags constexpr
Initial value:
= ImGuiTableFlags_Reorderable |
                                          ImGuiTableFlags_Resizable |
                                          ImGuiTableFlags_SizingStretchSame
Definition at line 52 of file graphics_editor.cc.
Referenced by yaze::app::editor::GraphicsEditor::UpdateScadView().
kSuperDonkeyTiles
const std::string yaze::app::editor::kSuperDonkeyTiles[]
Initial value:
= {
    "97C05", "98219", "9871E", "98C00", "99084", "995AF", "99DE0", "9A27E",
    "9A741", "9AC31", "9B07E", "9B55C", "9B963", "9BB99", "9C009", "9C4B4",
    "9C92B", "9CDD6", "9D2C2", "9E037", "9E527", "9EA56", "9EF65", "9FCD1",
    "A0193", "A059E", "A0B17", "A0FB6", "A14A5", "A1988", "A1E66", "A232B",
    "A27F0", "A2B6E", "A302C", "A3453", "A38CA", "A42BB", "A470C", "A4BA9",
    "A5089", "A5385", "A5742", "A5BCC", "A6017", "A6361", "A66F8"}
Definition at line 26 of file graphics_editor.h.
Referenced by yaze::app::editor::GraphicsEditor::DecompressSuperDonkey().
kSuperDonkeySprites
const std::string yaze::app::editor::kSuperDonkeySprites[]
Initial value:
= {
    "A8E5D", "A9435", "A9934", "A9D83", "AA2F1", "AA6D4", "AABE4", "AB127",
    "AB65A", "ABBDD", "AC38D", "AC797", "ACCC8", "AD0AE", "AD245", "AD554",
    "ADAAC", "ADECC", "AE453", "AE9D2", "AEF40", "AF3C9", "AF92E", "AFE9D",
    "B03D2", "B09AC", "B0F0C", "B1430", "B1859", "B1E01", "B229A", "B2854",
    "B2D27", "B31D7", "B3B58", "B40B5", "B45A5", "B4D64", "B5031", "B555F",
    "B5F30", "B6858", "B70DD", "B7526", "B79EC", "B7C83", "B80F7", "B85CC",
    "B8A3F", "B8F97", "B94F2", "B9A20", "B9E9A", "BA3A2", "BA8F6", "BACDC",
    "BB1F9", "BB781", "BBCCA", "BC26D", "BC7D4", "BCBB0", "BD082", "BD5FC",
    "BE115", "BE5C2", "BEB63", "BF0CB", "BF607", "BFA55", "BFD71", "C017D",
    "C0567", "C0981", "C0BA7", "C116D", "C166A", "C1FE0", "C24CE", "C2B19"}
Definition at line 34 of file graphics_editor.h.
Referenced by yaze::app::editor::GraphicsEditor::DecompressSuperDonkey().
kPaletteTableFlags
ImGuiTableFlags yaze::app::editor::kPaletteTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Reorderable | ImGuiTableFlags_Resizable |
    ImGuiTableFlags_SizingStretchSame | ImGuiTableFlags_Hideable
Definition at line 50 of file palette_editor.cc.
Referenced by yaze::app::editor::PaletteEditor::Update().
kPalNoAlpha
ImGuiColorEditFlags yaze::app::editor::kPalNoAlpha = ImGuiColorEditFlags_NoAlpha constexpr
Definition at line 54 of file palette_editor.cc.
Referenced by yaze::app::editor::PaletteEditor::DrawPaletteGroup().
kPalButtonFlags2
ImGuiColorEditFlags yaze::app::editor::kPalButtonFlags2 constexpr
Initial value:
= ImGuiColorEditFlags_NoAlpha |
                                                 ImGuiColorEditFlags_NoPicker |
                                                 ImGuiColorEditFlags_NoTooltip
Definition at line 56 of file palette_editor.cc.
Referenced by yaze::app::editor::PaletteEditor::DisplayPalette().
kColorPopupFlags
ImGuiColorEditFlags yaze::app::editor::kColorPopupFlags constexpr
Initial value:
=
    ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_NoAlpha
Definition at line 60 of file palette_editor.cc.
Referenced by yaze::app::editor::PaletteEditor::HandleColorPopup().
kRedPen
uint32_t yaze::app::editor::kRedPen = 0xFF0000FF constexpr
Definition at line 29 of file screen_editor.cc.
Referenced by yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs().
kMessageTerminator
const uint8_t yaze::app::editor::kMessageTerminator = 0x7F
Definition at line 17 of file message_data.h.
Referenced by yaze::app::editor::MessageEditor::ReadAllTextData(), yaze::app::editor::MessageEditor::ReadAllTextDataV2(), and yaze::app::editor::MessageEditor::Save().
BANKToken
const std::string yaze::app::editor::BANKToken = "BANK"
Definition at line 18 of file message_data.h.
Referenced by yaze::app::editor::MessageEditor::ReadAllTextData(), and yaze::app::editor::MessageEditor::ReadAllTextDataV2().
DICTIONARYTOKEN
const std::string yaze::app::editor::DICTIONARYTOKEN = "D"
Definition at line 19 of file message_data.h.
Referenced by yaze::app::editor::MessageEditor::DictionaryEntry::DictionaryEntry(), FindMatchingElement(), ParseMessageToData(), ParseTextDataByte(), yaze::app::editor::MessageEditor::ReadAllTextData(), and yaze::app::editor::MessageEditor::ReadAllTextDataV2().
DICTOFF
uint8_t yaze::app::editor::DICTOFF = 0x88 constexpr
Definition at line 20 of file message_data.h.
Referenced by yaze::app::editor::MessageEditor::DrawCharacterToPreview(), FindDictionaryEntry(), FindMatchingElement(), and yaze::app::editor::MessageEditor::Initialize().
CHEESE
const std::string yaze::app::editor::CHEESE = "\uBEBE"
Definition at line 48 of file message_data.h.
Referenced by yaze::app::editor::MessageData::OptimizeMessageForDictionary().
kGfxFont
int yaze::app::editor::kGfxFont = 0x70000 constexpr
Definition at line 26 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::Initialize().
kTextData
int yaze::app::editor::kTextData = 0xE0000 constexpr
Definition at line 27 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::BuildDictionaryEntries(), yaze::app::editor::MessageEditor::DisplayTextOverflowError(), yaze::app::editor::MessageEditor::ReadAllTextData(), yaze::app::editor::MessageEditor::ReadAllTextDataV2(), and yaze::app::editor::MessageEditor::Save().
kTextDataEnd
int yaze::app::editor::kTextDataEnd = 0xE7FFF constexpr
Definition at line 28 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::DisplayTextOverflowError(), and yaze::app::editor::MessageEditor::Save().
kTextData2
int yaze::app::editor::kTextData2 = 0x75F40 constexpr
Definition at line 29 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::DisplayTextOverflowError(), yaze::app::editor::MessageEditor::ReadAllTextData(), yaze::app::editor::MessageEditor::ReadAllTextDataV2(), and yaze::app::editor::MessageEditor::Save().
kTextData2End
int yaze::app::editor::kTextData2End = 0x773FF constexpr
Definition at line 30 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::DisplayTextOverflowError(), and yaze::app::editor::MessageEditor::Save().
kPointersDictionaries
int yaze::app::editor::kPointersDictionaries = 0x74703 constexpr
Definition at line 31 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::BuildDictionaryEntries(), yaze::app::editor::MessageEditor::ReadAllTextData(), and yaze::app::editor::MessageEditor::ReadAllTextDataV2().
kCharactersWidth
int yaze::app::editor::kCharactersWidth = 0x74ADF constexpr
Definition at line 32 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::Initialize(), and yaze::app::editor::MessageEditor::Save().
kNumDictionaryEntries
int yaze::app::editor::kNumDictionaryEntries = 97 constexpr
Definition at line 33 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::BuildDictionaryEntries().
kNumMessages
int yaze::app::editor::kNumMessages = 396 constexpr
Definition at line 34 of file message_editor.h.
kBlockTerminator
uint8_t yaze::app::editor::kBlockTerminator = 0x80 constexpr
Definition at line 36 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::Save().
BANKID
uint8_t yaze::app::editor::BANKID = 0x80 constexpr
Definition at line 37 of file message_editor.h.
kScrollVertical
uint8_t yaze::app::editor::kScrollVertical = 0x73 constexpr
Definition at line 38 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::DrawCharacterToPreview(), and yaze::app::editor::MessageEditor::Initialize().
kLine1
uint8_t yaze::app::editor::kLine1 = 0x74 constexpr
Definition at line 39 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::DrawCharacterToPreview().
kLine2
uint8_t yaze::app::editor::kLine2 = 0x75 constexpr
Definition at line 40 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::DrawCharacterToPreview(), and yaze::app::editor::MessageEditor::Initialize().
kLine3
uint8_t yaze::app::editor::kLine3 = 0x76 constexpr
Definition at line 41 of file message_editor.h.
Referenced by yaze::app::editor::MessageEditor::DrawCharacterToPreview(), and yaze::app::editor::MessageEditor::Initialize().
kTile16Size
int yaze::app::editor::kTile16Size = 0x10 constexpr
Definition at line 59 of file overworld_editor.cc.
Referenced by yaze::app::editor::OverworldEditor::CheckForOverworldEdits(), yaze::app::editor::OverworldEditor::DrawOverworldSprites(), yaze::app::editor::OverworldEditor::LoadGraphics(), and yaze::app::editor::OverworldEditor::RenderUpdatedMapBitmap().
kMapSettingsColumnNames
std::array<const char *, 8> yaze::app::editor::kMapSettingsColumnNames constexpr
Initial value:
= {
    "##WorldId", "##GfxId",  "##PalId",  "##SprGfxId",
    "##5thCol",  "##6thCol", "##7thCol", "##8thCol"}
Definition at line 260 of file overworld_editor.cc.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldMapSettings().
k4BPP
uint yaze::app::editor::k4BPP = 4 constexpr
Definition at line 31 of file overworld_editor.h.
kByteSize
uint yaze::app::editor::kByteSize = 3 constexpr
Definition at line 32 of file overworld_editor.h.
kMessageIdSize
uint yaze::app::editor::kMessageIdSize = 5 constexpr
Definition at line 33 of file overworld_editor.h.
kNumSheetsToLoad
uint yaze::app::editor::kNumSheetsToLoad = 223 constexpr
Definition at line 34 of file overworld_editor.h.
kTile8DisplayHeight
uint yaze::app::editor::kTile8DisplayHeight = 64 constexpr
Definition at line 35 of file overworld_editor.h.
kOverworldMapSize
uint yaze::app::editor::kOverworldMapSize = 0x200 constexpr
Definition at line 36 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::CheckForCurrentMap(), yaze::app::editor::OverworldEditor::DrawAreaGraphics(), yaze::app::editor::OverworldEditor::DrawOverworldEdits(), yaze::app::editor::OverworldEditor::DrawOverworldMaps(), yaze::app::editor::OverworldEditor::LoadGraphics(), and yaze::app::editor::OverworldEditor::RenderUpdatedMapBitmap().
kNumTile16Individual
uint yaze::app::editor::kNumTile16Individual = 4096 constexpr
Definition at line 37 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::LoadGraphics(), and yaze::app::editor::OverworldEditor::RefreshTile16Blockset().
kInputFieldSize
float yaze::app::editor::kInputFieldSize = 30.f constexpr
Definition at line 38 of file overworld_editor.h.
Referenced by DrawOverworldEntrancePopup(), and yaze::app::editor::OverworldEditor::DrawOverworldMapSettings().
kOWMapFlags
ImGuiTableFlags yaze::app::editor::kOWMapFlags constexpr
Initial value:
=
    ImGuiTableFlags_Borders | ImGuiTableFlags_Resizable
Definition at line 45 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldMapSettings().
kToolsetTableFlags
ImGuiTableFlags yaze::app::editor::kToolsetTableFlags = ImGuiTableFlags_SizingFixedFit constexpr
Definition at line 47 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::DrawToolset().
kOWEditFlags
ImGuiTableFlags yaze::app::editor::kOWEditFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 48 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::UpdateUsageStats().
kWorldList
absl::string_view yaze::app::editor::kWorldList constexpr
Initial value:
=
    "Light World\0Dark World\0Extra World\0"
Definition at line 60 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldMapSettings().
kGamePartComboString
absl::string_view yaze::app::editor::kGamePartComboString = "Part 0\0Part 1\0Part 2\0" constexpr
Definition at line 63 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldMapSettings().
kTileSelectorTab
absl::string_view yaze::app::editor::kTileSelectorTab = "##TileSelectorTabBar" constexpr
Definition at line 65 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::DrawTileSelector().
kOWEditTable
absl::string_view yaze::app::editor::kOWEditTable = "##OWEditTable" constexpr
Definition at line 66 of file overworld_editor.h.
kOWMapTable
absl::string_view yaze::app::editor::kOWMapTable = "#MapSettingsTable" constexpr
Definition at line 67 of file overworld_editor.h.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldMapSettings().
kSpriteTabFlags
ImGuiTabItemFlags yaze::app::editor::kSpriteTabFlags constexpr
Initial value:
=
    ImGuiTabItemFlags_Trailing | ImGuiTabItemFlags_NoTooltip
Definition at line 14 of file sprite_editor.h.
kSpriteTabBarFlags
ImGuiTabBarFlags yaze::app::editor::kSpriteTabBarFlags constexpr
Initial value:
=
    ImGuiTabBarFlags_AutoSelectNewTabs | ImGuiTabBarFlags_Reorderable |
    ImGuiTabBarFlags_FittingPolicyResizeDown |
    ImGuiTabBarFlags_TabListPopupButton
Definition at line 17 of file sprite_editor.h.
Referenced by yaze::app::editor::SpriteEditor::DrawVanillaSpriteEditor().
kSpriteTableFlags
ImGuiTableFlags yaze::app::editor::kSpriteTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 22 of file sprite_editor.h.
kEditorNames
std::array<const char*, 10> yaze::app::editor::kEditorNames constexpr
Initial value:
= {
    "Assembly", "Dungeon", "Graphics", "Music",   "Overworld",
    "Palette",  "Screen",  "Sprite",   "Message", "Settings",
}
Definition at line 28 of file editor.h.