yaze: yaze::app::core Namespace Reference
yaze::app::core Namespace Reference
Core application logic and utilities.
Namespaces
namespace anonymous_namespace{controller.cc}
Classes
class Controller
Main controller for the application.
class ExperimentFlags
A class to manage experimental feature flags.
class ImGuiIdIssuer
class Logger
class NotifyValue
A class to manage a value that can be modified and notify when it changes.
class ResourceLabelManager
Functions
std::string UppercaseHexByte (uint8_t byte, bool leading)
std::string UppercaseHexWord (uint16_t word)
std::string UppercaseHexLong (uint32_t dword)
uint32_t SnesToPc (uint32_t addr)
uint32_t PcToSnes (uint32_t addr)
uint32_t MapBankToWordAddress (uint8_t bank, uint16_t addr)
int AddressFromBytes (uint8_t addr1, uint8_t addr2, uint8_t addr3)
int HexToDec (char *input, int length)
bool StringReplace (std::string &str, const std::string &from, const std::string &to)
void stle (uint8_t *const p_arr, size_t const p_index, unsigned const p_val)
void stle0 (uint8_t *const p_arr, unsigned const p_val)
void stle1 (uint8_t *const p_arr, unsigned const p_val)
void stle2 (uint8_t *const p_arr, unsigned const p_val)
void stle3 (uint8_t *const p_arr, unsigned const p_val)
void stle16b (uint8_t *const p_arr, uint16_t const p_val)
void stle16b_i (uint8_t *const p_arr, size_t const p_index, uint16_t const p_val)
unsigned ldle (uint8_t const *const p_arr, unsigned const p_index)
uint32_t ldle0 (uint8_t const *const p_arr)
uint32_t ldle1 (uint8_t const *const p_arr)
uint32_t ldle2 (uint8_t const *const p_arr)
uint32_t ldle3 (uint8_t const *const p_arr)
uint16_t ldle16b (uint8_t const *const p_arr)
uint16_t ldle16b_i (uint8_t const *const p_arr, size_t const p_index)
void stle32b (uint8_t *const p_arr, uint32_t const p_val)
void stle32b_i (uint8_t *const p_arr, size_t const p_index, uint32_t const p_val)
Variables
constexpr uint32_t kRedPen = 0xFF0000FF
constexpr float kYazeVersion = 0.07
constexpr ushort TilePriorityBit = 0x2000
Bit set for object priority.
constexpr ushort TileHFlipBit = 0x4000
Bit set for object hflip.
constexpr ushort TileVFlipBit = 0x8000
Bit set for object vflip.
constexpr ushort TileNameMask = 0x03FF
Bits used for tile name.
constexpr int Uncompressed3BPPSize = 0x0600
constexpr int UncompressedSheetSize = 0x0800
constexpr int NumberOfRooms = 296
constexpr int NumberOfColors = 3143
constexpr int tile_address = 0x1B52
constexpr int tile_address_floor = 0x1B5A
constexpr int subtype1_tiles = 0x8000
constexpr int subtype2_tiles = 0x83F0
constexpr int subtype3_tiles = 0x84F0
constexpr int gfx_animated_pointer = 0x10275
constexpr int hud_palettes = 0xDD660
constexpr int maxGfx = 0xC3FB5
constexpr int kTilesheetWidth = 128
constexpr int kTilesheetHeight = 32
constexpr int kTilesheetDepth = 8
constexpr int gfx_font = 0x70000
constexpr int text_data = 0xE0000
constexpr int text_data2 = 0x75F40
constexpr int pointers_dictionaries = 0x74703
constexpr int characters_width = 0x74ADF
constexpr int entrance_gfx_group = 0x5D97
constexpr int GravesYTilePos = 0x49968
constexpr int GravesXTilePos = 0x49986
constexpr int GravesTilemapPos = 0x499A4
constexpr int GravesGFX = 0x499C2
constexpr int GravesXPos = 0x4994A
constexpr int GravesYLine = 0x4993A
constexpr int GravesCountOnY = 0x499E0
constexpr int GraveLinkSpecialHole = 0x46DD9
constexpr int GraveLinkSpecialStairs = 0x46DE0
constexpr int overworldPaletteMain = 0xDE6C8
constexpr int overworldPaletteAuxialiary = 0xDE86C
constexpr int overworldPaletteAnimated = 0xDE604
constexpr int globalSpritePalettesLW = 0xDD218
constexpr int globalSpritePalettesDW = 0xDD290
constexpr int armorPalettes = 0xDD308
constexpr int spritePalettesAux1 = 0xDD39E
constexpr int spritePalettesAux2 = 0xDD446
constexpr int spritePalettesAux3 = 0xDD4E0
constexpr int swordPalettes = 0xDD630
constexpr int shieldPalettes = 0xDD648
constexpr int hudPalettes = 0xDD660
constexpr int dungeonMapPalettes = 0xDD70A
constexpr int dungeonMainPalettes = 0xDD734
constexpr int dungeonMapBgPalettes = 0xDE544
constexpr int hardcodedGrassLW = 0x5FEA9
constexpr int hardcodedGrassDW = 0x05FEB3
constexpr int hardcodedGrassSpecial = 0x75640
constexpr int overworldMiniMapPalettes = 0x55B27
constexpr int triforcePalette = 0x64425
constexpr int crystalPalette = 0xF4CD3
constexpr int customAreaSpecificBGPalette
constexpr int customAreaSpecificBGASM = 0x140150
constexpr int customAreaSpecificBGEnabled
Detailed Description
Core application logic and utilities.
Function Documentation
UppercaseHexByte()
std::string yaze::app::core::UppercaseHexByte (uint8_t byte, bool leading)
Referenced by yaze::app::zelda3::overworld::OverworldMap::DrawAnimatedTiles(), yaze::app::editor::DungeonEditor::DrawEntranceSelector(), yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::DungeonEditor::DrawRoomSelector(), yaze::app::editor::ScreenEditor::LoadDungeonMaps(), yaze::app::zelda3::overworld::Overworld::SaveOverworldMaps(), yaze::app::editor::Tile16Editor::Update(), yaze::app::Rom::WriteByte(), and yaze::app::Rom::WriteVector().
UppercaseHexWord()
std::string yaze::app::core::UppercaseHexWord (uint16_t word)
Referenced by yaze::app::Rom::WriteColor(), yaze::app::Rom::WriteShort(), and yaze::app::Rom::WriteWord().
UppercaseHexLong()
std::string yaze::app::core::UppercaseHexLong (uint32_t dword)
Referenced by yaze::app::zelda3::overworld::Overworld::SaveOverworldMaps(), and yaze::app::Rom::WriteLong().
SnesToPc()
uint32_t yaze::app::core::SnesToPc (uint32_t addr)
Referenced by yaze::app::zelda3::overworld::Overworld::DecompressAllMapTiles(), yaze::app::editor::MasterEditor::DrawViewMenu(), yaze::app::Rom::GetGraphicsAddress(), yaze::cli::SnesToPc::handle(), yaze::app::zelda3::dungeon::Room::LoadAnimatedGraphics(), yaze::app::zelda3::dungeon::Room::LoadChests(), yaze::app::editor::ScreenEditor::LoadDungeonMaps(), yaze::app::Rom::LoadGfxGroups(), yaze::app::zelda3::dungeon::Room::LoadHeader(), yaze::app::zelda3::overworld::Overworld::LoadItems(), yaze::app::zelda3::dungeon::Room::LoadObjects(), yaze::app::zelda3::dungeon::Room::LoadRoomFromROM(), yaze::app::zelda3::dungeon::Room::LoadSprites(), yaze::app::zelda3::overworld::Overworld::LoadSpritesFromMap(), yaze::app::zelda3::screen::TitleScreen::LoadTitleScreen(), yaze::app::editor::ScreenEditor::SaveDungeonMaps(), and yaze::app::Rom::SaveGroupsToRom().
PcToSnes()
uint32_t yaze::app::core::PcToSnes (uint32_t addr)
Referenced by yaze::cli::PcToSnes::handle(), yaze::app::zelda3::overworld::Overworld::SaveItems(), and yaze::app::zelda3::overworld::Overworld::SaveOverworldMaps().
MapBankToWordAddress()
uint32_t yaze::app::core::MapBankToWordAddress (uint8_t bank, uint16_t addr)
AddressFromBytes()
int yaze::app::core::AddressFromBytes (uint8_t addr1, uint8_t addr2, uint8_t addr3)
HexToDec()
int yaze::app::core::HexToDec (char * input, int length)
StringReplace()
bool yaze::app::core::StringReplace (std::string & str, const std::string & from, const std::string & to)
stle()
void yaze::app::core::stle (uint8_t *const p_arr, size_t const p_index, unsigned const p_val)
Referenced by stle0(), stle1(), stle2(), and stle3().
stle0()
void yaze::app::core::stle0 (uint8_t *const p_arr, unsigned const p_val)
References stle().
Referenced by stle16b().
stle1()
void yaze::app::core::stle1 (uint8_t *const p_arr, unsigned const p_val)
References stle().
Referenced by stle16b().
stle2()
void yaze::app::core::stle2 (uint8_t *const p_arr, unsigned const p_val)
References stle().
stle3()
void yaze::app::core::stle3 (uint8_t *const p_arr, unsigned const p_val)
References stle().
stle16b()
void yaze::app::core::stle16b (uint8_t *const p_arr, uint16_t const p_val)
References stle0(), and stle1().
Referenced by stle16b_i(), and yaze::app::gfx::lc_lz2::Uncompress().
stle16b_i()
void yaze::app::core::stle16b_i (uint8_t *const p_arr, size_t const p_index, uint16_t const p_val)
References stle16b().
Referenced by yaze::app::zelda3::music::Tracker::SaveSongs().
ldle()
unsigned yaze::app::core::ldle (uint8_t const *const p_arr, unsigned const p_index)
Referenced by ldle0(), ldle1(), ldle2(), and ldle3().
ldle0()
uint32_t yaze::app::core::ldle0 (uint8_t const *const p_arr)
References ldle().
Referenced by ldle16b().
ldle1()
uint32_t yaze::app::core::ldle1 (uint8_t const *const p_arr)
References ldle().
Referenced by ldle16b().
ldle2()
uint32_t yaze::app::core::ldle2 (uint8_t const *const p_arr)
References ldle().
ldle3()
uint32_t yaze::app::core::ldle3 (uint8_t const *const p_arr)
References ldle().
ldle16b()
uint16_t yaze::app::core::ldle16b (uint8_t const *const p_arr)
References ldle0(), and ldle1().
Referenced by ldle16b_i(), and yaze::app::gfx::lc_lz2::Uncompress().
ldle16b_i()
uint16_t yaze::app::core::ldle16b_i (uint8_t const *const p_arr, size_t const p_index)
References ldle16b().
Referenced by yaze::app::zelda3::music::Tracker::SaveSongs().
stle32b()
void yaze::app::core::stle32b (uint8_t *const p_arr, uint32_t const p_val)
stle32b_i()
void yaze::app::core::stle32b_i (uint8_t *const p_arr, size_t const p_index, uint32_t const p_val)
Variable Documentation
kRedPen
constexpr uint32_t yaze::app::core::kRedPen = 0xFF0000FF constexpr
Referenced by yaze::app::editor::ScreenEditor::DrawDungeonMapsTabs().
kYazeVersion
constexpr float yaze::app::core::kYazeVersion = 0.07 constexpr
Referenced by yaze::app::editor::MasterEditor::DrawAboutPopup(), and yaze::app::editor::MasterEditor::DrawYazeMenu().
TilePriorityBit
constexpr ushort yaze::app::core::TilePriorityBit = 0x2000 constexpr
Bit set for object priority.
Referenced by yaze::app::gfx::GetTilesInfo(), and yaze::app::gfx::TileInfoToShort().
TileHFlipBit
constexpr ushort yaze::app::core::TileHFlipBit = 0x4000 constexpr
Bit set for object hflip.
Referenced by yaze::app::gfx::GetTilesInfo(), and yaze::app::gfx::TileInfoToShort().
TileVFlipBit
constexpr ushort yaze::app::core::TileVFlipBit = 0x8000 constexpr
Bit set for object vflip.
Referenced by yaze::app::gfx::GetTilesInfo(), and yaze::app::gfx::TileInfoToShort().
TileNameMask
constexpr ushort yaze::app::core::TileNameMask = 0x03FF constexpr
Bits used for tile name.
Referenced by yaze::app::gfx::GetTilesInfo(), and yaze::app::gfx::TileInfoToShort().
Uncompressed3BPPSize
constexpr int yaze::app::core::Uncompressed3BPPSize = 0x0600 constexpr
Referenced by yaze::app::Rom::LoadAllGraphicsData().
UncompressedSheetSize
constexpr int yaze::app::core::UncompressedSheetSize = 0x0800 constexpr
NumberOfRooms
constexpr int yaze::app::core::NumberOfRooms = 296 constexpr
NumberOfColors
constexpr int yaze::app::core::NumberOfColors = 3143 constexpr
tile_address
constexpr int yaze::app::core::tile_address = 0x1B52 constexpr
Referenced by yaze::app::zelda3::dungeon::Subtype1::Subtype1(), yaze::app::zelda3::dungeon::Subtype2::Subtype2(), and yaze::app::zelda3::dungeon::Subtype3::Subtype3().
tile_address_floor
constexpr int yaze::app::core::tile_address_floor = 0x1B5A constexpr
subtype1_tiles
constexpr int yaze::app::core::subtype1_tiles = 0x8000 constexpr
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::FetchSubtypeInfo(), and yaze::app::zelda3::dungeon::Subtype1::Subtype1().
subtype2_tiles
constexpr int yaze::app::core::subtype2_tiles = 0x83F0 constexpr
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::FetchSubtypeInfo(), and yaze::app::zelda3::dungeon::Subtype2::Subtype2().
subtype3_tiles
constexpr int yaze::app::core::subtype3_tiles = 0x84F0 constexpr
Referenced by yaze::app::zelda3::dungeon::DungeonObjectRenderer::FetchSubtypeInfo(), and yaze::app::zelda3::dungeon::Subtype3::Subtype3().
gfx_animated_pointer
constexpr int yaze::app::core::gfx_animated_pointer = 0x10275 constexpr
hud_palettes
constexpr int yaze::app::core::hud_palettes = 0xDD660 constexpr
maxGfx
constexpr int yaze::app::core::maxGfx = 0xC3FB5 constexpr
kTilesheetWidth
constexpr int yaze::app::core::kTilesheetWidth = 128 constexpr
Referenced by yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::Rom::LoadAllGraphicsData(), and yaze::app::Rom::LoadLinkGraphics().
kTilesheetHeight
constexpr int yaze::app::core::kTilesheetHeight = 32 constexpr
Referenced by yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::Rom::LoadAllGraphicsData(), yaze::app::Rom::LoadLinkGraphics(), and yaze::app::editor::GraphicsEditor::UpdateLinkGfxView().
kTilesheetDepth
constexpr int yaze::app::core::kTilesheetDepth = 8 constexpr
Referenced by yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::Rom::LoadAllGraphicsData(), and yaze::app::Rom::LoadLinkGraphics().
gfx_font
constexpr int yaze::app::core::gfx_font = 0x70000 constexpr
text_data
constexpr int yaze::app::core::text_data = 0xE0000 constexpr
text_data2
constexpr int yaze::app::core::text_data2 = 0x75F40 constexpr
pointers_dictionaries
constexpr int yaze::app::core::pointers_dictionaries = 0x74703 constexpr
characters_width
constexpr int yaze::app::core::characters_width = 0x74ADF constexpr
entrance_gfx_group
constexpr int yaze::app::core::entrance_gfx_group = 0x5D97 constexpr
Referenced by yaze::app::Rom::LoadGfxGroups(), and yaze::app::Rom::SaveGroupsToRom().
GravesYTilePos
constexpr int yaze::app::core::GravesYTilePos = 0x49968 constexpr
GravesXTilePos
constexpr int yaze::app::core::GravesXTilePos = 0x49986 constexpr
GravesTilemapPos
constexpr int yaze::app::core::GravesTilemapPos = 0x499A4 constexpr
GravesGFX
constexpr int yaze::app::core::GravesGFX = 0x499C2 constexpr
GravesXPos
constexpr int yaze::app::core::GravesXPos = 0x4994A constexpr
GravesYLine
constexpr int yaze::app::core::GravesYLine = 0x4993A constexpr
GravesCountOnY
constexpr int yaze::app::core::GravesCountOnY = 0x499E0 constexpr
GraveLinkSpecialHole
constexpr int yaze::app::core::GraveLinkSpecialHole = 0x46DD9 constexpr
GraveLinkSpecialStairs
constexpr int yaze::app::core::GraveLinkSpecialStairs = 0x46DE0 constexpr
overworldPaletteMain
constexpr int yaze::app::core::overworldPaletteMain = 0xDE6C8 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldMainPalettes().
overworldPaletteAuxialiary
constexpr int yaze::app::core::overworldPaletteAuxialiary = 0xDE86C constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes().
overworldPaletteAnimated
constexpr int yaze::app::core::overworldPaletteAnimated = 0xDE604 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldAnimatedPalettes().
globalSpritePalettesLW
constexpr int yaze::app::core::globalSpritePalettesLW = 0xDD218 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes().
globalSpritePalettesDW
constexpr int yaze::app::core::globalSpritePalettesDW = 0xDD290 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes().
armorPalettes
constexpr int yaze::app::core::armorPalettes = 0xDD308 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadArmorPalettes().
spritePalettesAux1
constexpr int yaze::app::core::spritePalettesAux1 = 0xDD39E constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadSpriteAux1Palettes().
spritePalettesAux2
constexpr int yaze::app::core::spritePalettesAux2 = 0xDD446 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadSpriteAux2Palettes().
spritePalettesAux3
constexpr int yaze::app::core::spritePalettesAux3 = 0xDD4E0 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadSpriteAux3Palettes().
swordPalettes
constexpr int yaze::app::core::swordPalettes = 0xDD630 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadSwordPalettes().
shieldPalettes
constexpr int yaze::app::core::shieldPalettes = 0xDD648 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadShieldPalettes().
hudPalettes
constexpr int yaze::app::core::hudPalettes = 0xDD660 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadHUDPalettes().
dungeonMapPalettes
constexpr int yaze::app::core::dungeonMapPalettes = 0xDD70A constexpr
dungeonMainPalettes
constexpr int yaze::app::core::dungeonMainPalettes = 0xDD734 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadDungeonMainPalettes().
dungeonMapBgPalettes
constexpr int yaze::app::core::dungeonMapBgPalettes = 0xDE544 constexpr
hardcodedGrassLW
constexpr int yaze::app::core::hardcodedGrassLW = 0x5FEA9 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
hardcodedGrassDW
constexpr int yaze::app::core::hardcodedGrassDW = 0x05FEB3 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
hardcodedGrassSpecial
constexpr int yaze::app::core::hardcodedGrassSpecial = 0x75640 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
overworldMiniMapPalettes
constexpr int yaze::app::core::overworldMiniMapPalettes = 0x55B27 constexpr
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldMiniMapPalettes().
triforcePalette
constexpr int yaze::app::core::triforcePalette = 0x64425 constexpr
Referenced by yaze::app::gfx::palette_group_internal::Load3DObjectPalettes().
crystalPalette
constexpr int yaze::app::core::crystalPalette = 0xF4CD3 constexpr
Referenced by yaze::app::gfx::palette_group_internal::Load3DObjectPalettes().
customAreaSpecificBGPalette
constexpr int yaze::app::core::customAreaSpecificBGPalette constexpr
Initial value:
=
    0x140000
customAreaSpecificBGASM
constexpr int yaze::app::core::customAreaSpecificBGASM = 0x140150 constexpr
customAreaSpecificBGEnabled
constexpr int yaze::app::core::customAreaSpecificBGEnabled constexpr
Initial value:
=
    0x140140