yaze: yaze::test Namespace Reference
yaze::test Namespace Reference
Namespaces
namespace anonymous_namespace{compression_test.cc}
namespace anonymous_namespace{snes_palette_test.cc}
namespace integration
Classes
class Apu
The Apu class represents the Audio Processing Unit (APU) of a system.
struct ApuCallbacks
class ApuTest
class ArenaTestSuite
class AsmParser
class AudioRam
AudioRam is an interface for the Audio RAM used by the SPC700.
struct CompressionContext
struct CompressionPiece
class Cpu
struct CpuCallbacks
class CpuTest
class DungeonEditorIntegrationTest
Integration test framework for dungeon editor components.
class DungeonObjectRenderingTests
Advanced tests for actual dungeon object rendering scenarios.
class DungeonRoomTest
class EditorIntegrationTest
Base class for editor integration tests.
class IntegratedTestSuite
class IplHandshakeTest
class MemoryImpl
Implementation of the Memory interface for emulating memory in a SNES system.
class MessageTest
class MockAudioRam
MockAudioRam is a mock class for the AudioRam class.
class MockMemory
A mock implementation of the Memory class.
class MockPpu
Mock Ppu class for testing.
class MockRom
Mock ROM class for testing without real ROM files.
class ObjectParserStructsTest
class ObjectParserTest
class PerformanceTestSuite
class PpuInterface
class PpuTest
struct ResourceStats
class Rom
The Rom class is used to load, save, and modify Rom data.
class RomDependentTest
Test fixture for ROM-dependent tests.
class RomDependentTestSuite
class RomTest
class Spc700
The Spc700 class represents the SPC700 processor.
class Spc700Test
struct SpriteAttributes
class SpriteBuilderTest
class TestDungeonObjects
Simplified test framework for dungeon object rendering.
class TestEditor
class TestManager
struct TestResult
struct TestResults
class TestRomManager
Utility class for handling test ROM files.
class TestSuite
struct Tilemap
class UITestSuite
class UnitTestSuite
Enumerations
enum class TestStatus {
kNotRun , kRunning , kPassed , kFailed ,
kSkipped
}
enum class TestCategory {
kUnit , kIntegration , kUI , kPerformance ,
kMemory
}
enum class BackgroundMode
Functions
const char * TestStatusToString (TestStatus status)
const char * TestCategoryToString (TestCategory category)
ImVec4 GetTestStatusColor (TestStatus status)
TEST (DungeonToolsetTest, BasicFunctionality)
Unit tests for individual dungeon components.
TEST (DungeonToolsetTest, CallbackFunctionality)
TEST (DungeonUsageTrackerTest, BasicFunctionality)
TEST (ComponentArchitectureTest, FileSizeReduction)
TEST_F (ApuTest, IplRomHandshakeTiming)
TEST_F (ApuTest, ApuInitialization)
TEST_F (ApuTest, SampleGenerationTiming)
TEST_F (ApuTest, DspRegisterAccessTiming)
TEST_F (ApuTest, DmaTransferTiming)
TEST_F (IplHandshakeTest, ExactCycleTiming)
TEST_F (IplHandshakeTest, CycleRange)
TEST_F (IplHandshakeTest, MultipleAttempts)
TEST_F (IplHandshakeTest, WithInterrupts)
TEST_F (CpuTest, AsmParserTokenizerOk)
TEST_F (CpuTest, AsmParserSingleInstructionOk)
TEST_F (CpuTest, CheckMemoryContents)
TEST_F (CpuTest, ADC_CheckCarryFlag)
TEST_F (CpuTest, ADC_DirectPageIndexedIndirectX)
TEST_F (CpuTest, ADC_StackRelative)
TEST_F (CpuTest, ADC_DirectPage)
TEST_F (CpuTest, ADC_DirectPageIndirectLong)
TEST_F (CpuTest, ADC_Immediate_TwoPositiveNumbers)
TEST_F (CpuTest, ADC_Immediate_PositiveAndNegativeNumbers)
TEST_F (CpuTest, ADC_Absolute)
TEST_F (CpuTest, ADC_AbsoluteLong)
TEST_F (CpuTest, ADC_DirectPageIndirectIndexedY)
TEST_F (CpuTest, ADC_DirectPageIndirect)
TEST_F (CpuTest, ADC_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, ADC_DirectPageIndexedX)
TEST_F (CpuTest, ADC_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, ADC_AbsoluteIndexedY)
TEST_F (CpuTest, ADC_AbsoluteIndexedX)
TEST_F (CpuTest, ADC_AbsoluteLongIndexedX)
TEST_F (CpuTest, AND_DirectPageIndexedIndirectX)
TEST_F (CpuTest, AND_StackRelative)
TEST_F (CpuTest, AND_DirectPage)
TEST_F (CpuTest, AND_DirectPageIndirectLong)
TEST_F (CpuTest, AND_Immediate)
TEST_F (CpuTest, AND_Absolute_16BitMode)
TEST_F (CpuTest, AND_AbsoluteLong)
TEST_F (CpuTest, AND_DirectPageIndirectIndexedY)
TEST_F (CpuTest, AND_DirectPageIndirect)
TEST_F (CpuTest, AND_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, AND_DirectPageIndexedX)
TEST_F (CpuTest, AND_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, AND_AbsoluteIndexedY)
TEST_F (CpuTest, AND_AbsoluteIndexedX)
TEST_F (CpuTest, AND_AbsoluteLongIndexedX)
TEST_F (CpuTest, ASL_DirectPage)
TEST_F (CpuTest, ASL_Accumulator)
TEST_F (CpuTest, ASL_Absolute)
TEST_F (CpuTest, ASL_DirectPageIndexedX)
TEST_F (CpuTest, ASL_AbsoluteIndexedX)
TEST_F (CpuTest, BCC_WhenCarryFlagClear)
TEST_F (CpuTest, BCC_WhenCarryFlagSet)
TEST_F (CpuTest, BCS_WhenCarryFlagSet)
TEST_F (CpuTest, BCS_WhenCarryFlagClear)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagSet)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagClear)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagSet_OverflowFlagSet)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagClear_OverflowFlagSet)
TEST_F (CpuTest, BIT_DirectPage)
TEST_F (CpuTest, BIT_Absolute)
TEST_F (CpuTest, BIT_DirectPageIndexedX)
TEST_F (CpuTest, BIT_AbsoluteIndexedX)
TEST_F (CpuTest, BIT_Immediate)
TEST_F (CpuTest, BMI_BranchTaken)
TEST_F (CpuTest, BMI_BranchNotTaken)
TEST_F (CpuTest, BNE_BranchTaken)
TEST_F (CpuTest, BNE_BranchNotTaken)
TEST_F (CpuTest, BPL_BranchTaken)
TEST_F (CpuTest, BPL_BranchNotTaken)
TEST_F (CpuTest, BRA)
TEST_F (CpuTest, BRK)
TEST_F (CpuTest, BRL)
TEST_F (CpuTest, BVC_BranchTaken)
TEST_F (CpuTest, BVS_BranchTaken)
TEST_F (CpuTest, CLC)
TEST_F (CpuTest, CLD)
TEST_F (CpuTest, CLI)
TEST_F (CpuTest, CLV)
TEST_F (CpuTest, CMP_DirectPageIndexedIndirectX)
TEST_F (CpuTest, CMP_StackRelative)
TEST_F (CpuTest, CMP_DirectPage)
TEST_F (CpuTest, CMP_DirectPageIndirectLong)
TEST_F (CpuTest, CMP_Immediate_8Bit)
TEST_F (CpuTest, CMP_Absolute_16Bit)
TEST_F (CpuTest, CMP_AbsoluteLong)
TEST_F (CpuTest, CMP_DirectPageIndirect)
TEST_F (CpuTest, CMP_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, CMP_DirectPageIndexedX)
TEST_F (CpuTest, CMP_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, CMP_AbsoluteIndexedY)
TEST_F (CpuTest, CMP_AbsoluteIndexedX)
TEST_F (CpuTest, CMP_AbsoluteLongIndexedX)
TEST_F (CpuTest, COP)
TEST_F (CpuTest, CPX_Immediate_ZeroFlagSet)
TEST_F (CpuTest, CPX_Immediate_NegativeFlagSet)
TEST_F (CpuTest, CPX_DirectPage)
TEST_F (CpuTest, CPX_Absolute)
TEST_F (CpuTest, CPY_Immediate_ZeroFlagSet)
TEST_F (CpuTest, CPY_Immediate_NegativeFlagSet)
TEST_F (CpuTest, CPY_DirectPage)
TEST_F (CpuTest, CPY_Absolute)
TEST_F (CpuTest, DEC_Accumulator)
TEST_F (CpuTest, DEC_DirectPage)
TEST_F (CpuTest, DEC_Absolute)
TEST_F (CpuTest, DEC_DirectPageIndexedX)
TEST_F (CpuTest, DEC_AbsoluteIndexedX)
TEST_F (CpuTest, DEX)
TEST_F (CpuTest, DEY)
TEST_F (CpuTest, EOR_DirectPageIndexedIndirectX)
TEST_F (CpuTest, EOR_StackRelative)
TEST_F (CpuTest, EOR_DirectPage)
TEST_F (CpuTest, EOR_DirectPageIndirectLong)
TEST_F (CpuTest, EOR_Immediate_8bit)
TEST_F (CpuTest, EOR_Absolute)
TEST_F (CpuTest, EOR_AbsoluteLong)
TEST_F (CpuTest, EOR_DirectPageIndirectIndexedY)
TEST_F (CpuTest, EOR_DirectPageIndirect)
TEST_F (CpuTest, EOR_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, EOR_DirectPageIndexedX)
TEST_F (CpuTest, EOR_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, EOR_AbsoluteIndexedY)
TEST_F (CpuTest, EOR_AbsoluteIndexedX)
TEST_F (CpuTest, EOR_AbsoluteLongIndexedX)
TEST_F (CpuTest, INC_Accumulator)
TEST_F (CpuTest, INC_DirectPage_8bit)
TEST_F (CpuTest, INC_Absolute_16bit)
TEST_F (CpuTest, INC_DirectPage_ZeroResult_8bit)
TEST_F (CpuTest, INC_Absolute_ZeroResult_16bit)
TEST_F (CpuTest, INC_DirectPage_8bit_Overflow)
TEST_F (CpuTest, INC_DirectPageIndexedX_8bit)
TEST_F (CpuTest, INC_AbsoluteIndexedX_16bit)
TEST_F (CpuTest, INX)
TEST_F (CpuTest, INY)
TEST_F (CpuTest, JMP_Absolute)
TEST_F (CpuTest, JMP_Indirect)
TEST_F (CpuTest, JML_AbsoluteLong)
TEST_F (CpuTest, JMP_AbsoluteIndexedIndirectX)
TEST_F (CpuTest, JMP_AbsoluteIndirectLong)
TEST_F (CpuTest, JSR_Absolute)
TEST_F (CpuTest, JSL_AbsoluteLong)
TEST_F (CpuTest, JSL_AbsoluteIndexedIndirect)
TEST_F (CpuTest, LDA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, LDA_StackRelative)
TEST_F (CpuTest, LDA_DirectPage)
TEST_F (CpuTest, LDA_DirectPageIndirectLong)
TEST_F (CpuTest, LDA_Immediate_8bit)
TEST_F (CpuTest, LDA_Immediate_16bit)
TEST_F (CpuTest, LDA_Absolute)
TEST_F (CpuTest, LDA_AbsoluteLong)
TEST_F (CpuTest, LDA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, LDA_DirectPageIndirect)
TEST_F (CpuTest, LDA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, LDA_DirectPageIndexedX)
TEST_F (CpuTest, LDA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, LDA_AbsoluteIndexedY)
TEST_F (CpuTest, LDA_AbsoluteIndexedX)
TEST_F (CpuTest, LDA_AbsoluteLongIndexedX)
TEST_F (CpuTest, LDX_Immediate)
TEST_F (CpuTest, LDX_DirectPage)
TEST_F (CpuTest, LDX_Absolute)
TEST_F (CpuTest, LDX_DirectPageIndexedY)
TEST_F (CpuTest, LDX_AbsoluteIndexedY)
TEST_F (CpuTest, LDY_Immediate)
TEST_F (CpuTest, LDY_DirectPage)
TEST_F (CpuTest, LDY_Absolute)
TEST_F (CpuTest, LDY_DirectPageIndexedX)
TEST_F (CpuTest, LDY_AbsoluteIndexedX)
TEST_F (CpuTest, LSR_DirectPage)
TEST_F (CpuTest, LSR_Accumulator)
TEST_F (CpuTest, LSR_Absolute)
TEST_F (CpuTest, LSR_DirectPageIndexedX)
TEST_F (CpuTest, LSR_AbsoluteIndexedX)
TEST_F (CpuTest, ORA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, ORA_StackRelative)
TEST_F (CpuTest, ORA_DirectPage)
TEST_F (CpuTest, ORA_DirectPageIndirectLong)
TEST_F (CpuTest, ORA_Immediate)
TEST_F (CpuTest, ORA_Absolute)
TEST_F (CpuTest, ORA_AbsoluteLong)
TEST_F (CpuTest, ORA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, ORA_DirectPageIndirect)
TEST_F (CpuTest, ORA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, ORA_DirectPageIndexedX)
TEST_F (CpuTest, ORA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, ORA_AbsoluteIndexedY)
TEST_F (CpuTest, ORA_AbsoluteIndexedX)
TEST_F (CpuTest, ORA_AbsoluteLongIndexedX)
TEST_F (CpuTest, PEA)
TEST_F (CpuTest, PEI)
TEST_F (CpuTest, PER)
TEST_F (CpuTest, PHD)
TEST_F (CpuTest, PHK)
TEST_F (CpuTest, PHP)
TEST_F (CpuTest, PHX)
TEST_F (CpuTest, PHY)
TEST_F (CpuTest, PHB)
TEST_F (CpuTest, PHA)
TEST_F (CpuTest, PHA_16Bit)
TEST_F (CpuTest, PLA)
TEST_F (CpuTest, PLA_16Bit)
TEST_F (CpuTest, PLB)
TEST_F (CpuTest, PLD)
TEST_F (CpuTest, PLP)
TEST_F (CpuTest, PLX)
TEST_F (CpuTest, PLX_16Bit)
TEST_F (CpuTest, PLY)
TEST_F (CpuTest, PLY_16Bit)
TEST_F (CpuTest, REP)
TEST_F (CpuTest, REP_16Bit)
TEST_F (CpuTest, PHA_PLA_Ok)
TEST_F (CpuTest, PHP_PLP_Ok)
TEST_F (CpuTest, PHA_PushAccumulator)
TEST_F (CpuTest, PHP_PushProcessorStatusRegister)
TEST_F (CpuTest, PHX_PushXRegister)
TEST_F (CpuTest, PHY_PushYRegister)
TEST_F (CpuTest, PHB_PushDataBankRegister)
TEST_F (CpuTest, PHD_PushDirectPageRegister)
TEST_F (CpuTest, PHK_PushProgramBankRegister)
TEST_F (CpuTest, PLA_PullAccumulator)
TEST_F (CpuTest, PLP_PullProcessorStatusRegister)
TEST_F (CpuTest, PLX_PullXRegister)
TEST_F (CpuTest, PLY_PullYRegister)
TEST_F (CpuTest, PLB_PullDataBankRegister)
TEST_F (CpuTest, PLD_PullDirectPageRegister)
TEST_F (CpuTest, SEP)
TEST_F (CpuTest, ROL_DirectPage)
TEST_F (CpuTest, ROL_Accumulator)
TEST_F (CpuTest, ROL_Absolute)
TEST_F (CpuTest, ROL_DirectPageIndexedX)
TEST_F (CpuTest, ROL_AbsoluteIndexedX)
TEST_F (CpuTest, ROR_DirectPage)
TEST_F (CpuTest, ROR_Accumulator)
TEST_F (CpuTest, ROR_Absolute)
TEST_F (CpuTest, ROR_DirectPageIndexedX)
TEST_F (CpuTest, ROR_AbsoluteIndexedX)
TEST_F (CpuTest, RTI)
TEST_F (CpuTest, RTL)
TEST_F (CpuTest, RTS)
TEST_F (CpuTest, SBC_DirectPageIndexedIndirectX)
TEST_F (CpuTest, SBC_StackRelative)
TEST_F (CpuTest, SBC_DirectPage)
TEST_F (CpuTest, SBC_DirectPageIndirectLong)
TEST_F (CpuTest, SBC_Immediate)
TEST_F (CpuTest, SBC_Absolute)
TEST_F (CpuTest, SBC_AbsoluteLong)
TEST_F (CpuTest, SBC_DirectPageIndirectIndexedY)
TEST_F (CpuTest, SBC_DirectPageIndirect)
TEST_F (CpuTest, SBC_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, SBC_DirectPageIndexedX)
TEST_F (CpuTest, SBC_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, SBC_AbsoluteIndexedY)
TEST_F (CpuTest, SBC_AbsoluteIndexedX)
TEST_F (CpuTest, SBC_AbsoluteLongIndexedX)
TEST_F (CpuTest, SEC)
TEST_F (CpuTest, SED)
TEST_F (CpuTest, SEI)
TEST_F (CpuTest, SEP_8Bit)
TEST_F (CpuTest, SEP_16Bit)
TEST_F (CpuTest, STA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, STA_StackRelative)
TEST_F (CpuTest, STA_DirectPage)
TEST_F (CpuTest, STA_DirectPageIndirectLong)
TEST_F (CpuTest, STA_Absolute)
TEST_F (CpuTest, STA_AbsoluteLong)
TEST_F (CpuTest, STA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, STA_DirectPageIndirect)
TEST_F (CpuTest, STA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, STA_DirectPageIndexedX)
TEST_F (CpuTest, STA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, STA_AbsoluteIndexedY)
TEST_F (CpuTest, STA_AbsoluteIndexedX)
TEST_F (CpuTest, STA_AbsoluteLongIndexedX)
TEST_F (CpuTest, STP)
TEST_F (CpuTest, STX_DirectPage)
TEST_F (CpuTest, STX_Absolute)
TEST_F (CpuTest, STX_DirectPageIndexedY)
TEST_F (CpuTest, STY_DirectPage)
TEST_F (CpuTest, STY_Absolute)
TEST_F (CpuTest, STY_DirectPageIndexedX)
TEST_F (CpuTest, STZ_DirectPage)
TEST_F (CpuTest, STZ_DirectPageIndexedX)
TEST_F (CpuTest, STZ_Absolute)
TEST_F (CpuTest, TAX)
TEST_F (CpuTest, TAY)
TEST_F (CpuTest, TCD)
TEST_F (CpuTest, TCS)
TEST_F (CpuTest, TDC)
TEST_F (CpuTest, TRB_DirectPage)
TEST_F (CpuTest, TRB_Absolute)
TEST_F (CpuTest, TSB_DirectPage)
TEST_F (CpuTest, TSB_Absolute)
TEST_F (CpuTest, TSC)
TEST_F (CpuTest, TSX)
TEST_F (CpuTest, TXA)
TEST_F (CpuTest, TXS)
TEST_F (CpuTest, TXY)
TEST_F (CpuTest, TYA)
TEST_F (CpuTest, TYX)
TEST_F (CpuTest, WAI)
TEST_F (CpuTest, WDM)
TEST_F (CpuTest, XBA)
TEST_F (CpuTest, XCESwitchToNativeMode)
TEST_F (CpuTest, XCESwitchToEmulationMode)
TEST_F (CpuTest, XCESwitchBackAndForth)
TEST_F (Spc700Test, MOV_A_Immediate)
TEST_F (Spc700Test, MOV_A_X)
TEST_F (Spc700Test, MOV_A_Y)
TEST_F (Spc700Test, MOV_A_dp)
TEST_F (Spc700Test, MOV_A_dp_plus_x)
TEST_F (Spc700Test, MOV_A_dp_indirect_plus_y)
TEST_F (Spc700Test, MOV_A_dp_plus_x_indirect)
TEST_F (Spc700Test, MOV_A_abs)
TEST_F (Spc700Test, MOV_Immediate)
TEST_F (Spc700Test, NOP_DoesNothing)
TEST_F (Spc700Test, ADC_A_Immediate)
TEST_F (Spc700Test, BEQ_BranchesIfZeroFlagSet)
TEST_F (Spc700Test, STA_Absolute)
TEST_F (Spc700Test, ExecuteADCWithImmediate)
TEST_F (Spc700Test, ExecuteBRA)
TEST_F (Spc700Test, ReadFromAudioRAM)
TEST_F (Spc700Test, WriteToAudioRAM)
TEST_F (Spc700Test, ExecuteANDWithImmediate)
TEST_F (Spc700Test, ExecuteORWithImmediate)
TEST_F (Spc700Test, ExecuteEORWithImmediate)
TEST_F (Spc700Test, ExecuteINC)
TEST_F (Spc700Test, ExecuteDEC)
TEST_F (Spc700Test, ExecuteBNEWhenNotEqual)
TEST_F (Spc700Test, ExecuteBNEWhenEqual)
TEST_F (Spc700Test, ExecuteBEQWhenEqual)
TEST_F (Spc700Test, ExecuteBEQWhenNotEqual)
TEST_F (Spc700Test, BootIplRomOk)
TEST (LC_LZ2_CompressionTest, TrivialRepeatedBytes)
TEST (LC_LZ2_CompressionTest, RepeatedBytesBetweenUncompressable)
TEST (LC_LZ2_CompressionTest, RepeatedBytesBeforeUncompressable)
TEST (LC_LZ2_CompressionTest, RepeatedBytesAfterUncompressable)
TEST (LC_LZ2_CompressionTest, RepeatedBytesAfterUncompressableRepeated)
TEST (LC_LZ2_CompressionTest, RepeatedBytesBeforeUncompressableRepeated)
TEST (LC_LZ2_CompressionTest, NewDecompressionPieceOk)
TEST (LC_LZ2_CompressionTest, CompressionSingleSet)
TEST (LC_LZ2_CompressionTest, CompressionSingleWord)
TEST (LC_LZ2_CompressionTest, CompressionSingleIncrement)
TEST (LC_LZ2_CompressionTest, CompressionSingleCopy)
TEST (LC_LZ2_CompressionTest, CompressionSingleOverflowIncrement)
TEST (HandleDirectCopyTest, NotDirectCopyWithAccumulatedBytes)
TEST (HandleDirectCopyTest, NotDirectCopyWithoutAccumulatedBytes)
TEST (HandleDirectCopyTest, AccumulateBytesWithoutMax)
TEST (CheckIncByteV3Test, IncreasingSequence)
TEST (CheckIncByteV3Test, IncreasingSequenceSurroundedByIdenticalBytes)
TEST (CheckIncByteV3Test, NotAnIncreasingSequence)
TEST (LC_LZ2_CompressionTest, DecompressionValidCommand)
TEST (LC_LZ2_CompressionTest, DecompressionMixingCommand)
TEST (SnesColorTest, DefaultConstructor)
TEST (SnesColorTest, RGBConstructor)
TEST (SnesColorTest, SNESConstructor)
TEST (SnesColorTest, ConvertRgbToSnes)
TEST (SnesColorTest, ConvertSnestoRGB)
TEST (SnesColorTest, ConvertSnesToRGB_Binary)
TEST (SnesColorTest, Extraction)
TEST (SnesColorTest, Convert)
TEST (SnesPaletteTest, DefaultConstructor)
TEST (SnesPaletteTest, AddColor)
TEST (SnesPaletteTest, AddMultipleColors)
TEST (SnesPaletteTest, UpdateColor)
TEST (SnesPaletteTest, SubPalette)
TEST (SnesPaletteTest, VectorConstructor)
TEST (SnesPaletteTest, Clear)
TEST (SnesPaletteTest, Iterator)
TEST (SnesPaletteTest, OperatorAccess)
TEST (SnesTileTest, UnpackBppTile)
TEST (SnesTileTest, PackBppTile)
TEST (SnesTileTest, ConvertBpp)
TEST (SnesTileTest, TileInfo)
TEST (SnesTileTest, TileInfoToWord)
TEST (SnesTileTest, WordToTileInfo)
TEST (SnesTileTest, Tile32)
TEST (SnesTileTest, Tile16)
TEST (HexTest, HexByte)
TEST (HexTest, HexWord)
TEST (HexTest, HexLong)
TEST (HexTest, HexLongLong)
TEST_F (DungeonEditorIntegrationTest, ObjectParsingTest)
TEST_F (DungeonEditorIntegrationTest, ObjectRenderingTest)
TEST_F (DungeonEditorIntegrationTest, RoomGraphicsTest)
TEST_F (DungeonEditorIntegrationTest, PaletteHandlingTest)
TEST_F (DungeonEditorIntegrationTest, MockRomValidation)
TEST_F (RomTest, Uninitialized)
TEST_F (RomTest, LoadFromFile)
TEST_F (RomTest, LoadFromFileInvalid)
TEST_F (RomTest, LoadFromFileEmpty)
TEST_F (RomTest, ReadByteOk)
TEST_F (RomTest, ReadByteInvalid)
TEST_F (RomTest, ReadWordOk)
TEST_F (RomTest, ReadWordInvalid)
TEST_F (RomTest, ReadLongOk)
TEST_F (RomTest, ReadBytesOk)
TEST_F (RomTest, ReadBytesOutOfRange)
TEST_F (RomTest, WriteByteOk)
TEST_F (RomTest, WriteWordOk)
TEST_F (RomTest, WriteLongOk)
TEST_F (RomTest, WriteTransactionSuccess)
TEST_F (RomTest, WriteTransactionFailure)
TEST_F (RomTest, ReadTransactionSuccess)
TEST_F (RomTest, ReadTransactionFailure)
TEST_F (RomTest, SaveTruncatesExistingFile)
TEST_F (RomTest, TransactionRollbackRestoresOriginals)
int RunIntegrationTest ()
MATCHER_P (StatusIs, status, "")
template<typename T>
::testing::AssertionResult IsOkAndHolds (const absl::StatusOr< T > &status_or, const T &value)
MATCHER_P (IsOkAndHolds, value, "")
MATCHER_P (StatusIsWithMessage, message, "")
MATCHER_P (StatusIsWithCode, code, "")
template<typename T, typename Matcher>
::testing::AssertionResult IsOkAndMatches (const absl::StatusOr< T > &status_or, const Matcher &matcher)
template<typename T>
::testing::AssertionResult StatusOrEqual (const absl::StatusOr< T > &a, const absl::StatusOr< T > &b)
TEST_F (DungeonObjectRenderingTests, EmptyRoomRendering)
TEST_F (DungeonObjectRenderingTests, MultiObjectRoomRendering)
TEST_F (DungeonObjectRenderingTests, ComplexRoomRendering)
TEST_F (DungeonObjectRenderingTests, LargeRoomRendering)
TEST_F (DungeonObjectRenderingTests, BossRoomRendering)
TEST_F (DungeonObjectRenderingTests, PuzzleRoomRendering)
TEST_F (DungeonObjectRenderingTests, PaletteConsistency)
TEST_F (DungeonObjectRenderingTests, ScenarioPerformanceBenchmark)
TEST_F (DungeonObjectRenderingTests, ScenarioMemoryUsage)
TEST_F (DungeonObjectRenderingTests, ObjectOverlapHandling)
TEST_F (DungeonObjectRenderingTests, LayerRenderingOrder)
TEST_F (DungeonObjectRenderingTests, ScenarioCacheEfficiency)
TEST_F (DungeonObjectRenderingTests, BoundaryObjectPlacement)
TEST_F (DungeonRoomTest, SingleRoomLoadOk)
TEST_F (MessageTest, ParseSingleMessage_CommandParsing)
TEST_F (MessageTest, ParseSingleMessage_BasicAscii)
TEST_F (MessageTest, FindMatchingCharacter_Success)
TEST_F (MessageTest, FindMatchingCharacter_Failure)
TEST_F (MessageTest, FindDictionaryEntry_Success)
TEST_F (MessageTest, FindDictionaryEntry_Failure)
TEST_F (MessageTest, ParseMessageToData_Basic)
TEST_F (MessageTest, ReplaceAllDictionaryWords_Success)
TEST_F (MessageTest, ReplaceAllDictionaryWords_NoMatch)
TEST_F (MessageTest, ParseTextDataByte_Success)
TEST_F (MessageTest, ParseTextDataByte_Failure)
TEST_F (MessageTest, ParseSingleMessage_SpecialCharacters)
TEST_F (MessageTest, ParseSingleMessage_DictionaryReference)
TEST_F (MessageTest, ParseSingleMessage_InvalidTerminator)
TEST_F (MessageTest, ParseSingleMessage_EmptyData)
TEST_F (MessageTest, OptimizeMessageForDictionary_Basic)
TEST_F (MessageTest, SetMessage_Success)
TEST_F (MessageTest, FindMatchingElement_CommandWithArgument)
TEST_F (MessageTest, FindMatchingElement_InvalidCommand)
TEST_F (MessageTest, BuildDictionaryEntries_CorrectSize)
TEST_F (ObjectParserStructsTest, ObjectRoutineInfoDefaultConstructor)
TEST_F (ObjectParserStructsTest, ObjectSubtypeInfoDefaultConstructor)
TEST_F (ObjectParserStructsTest, ObjectSizeInfoDefaultConstructor)
TEST_F (ObjectParserStructsTest, ObjectRoutineInfoAssignment)
TEST_F (ObjectParserStructsTest, ObjectSubtypeInfoAssignment)
TEST_F (ObjectParserStructsTest, ObjectSizeInfoAssignment)
TEST_F (ObjectParserTest, ParseSubtype1Object)
TEST_F (ObjectParserTest, ParseSubtype2Object)
TEST_F (ObjectParserTest, ParseSubtype3Object)
TEST_F (ObjectParserTest, GetObjectSubtype)
TEST_F (ObjectParserTest, ParseObjectSize)
TEST_F (ObjectParserTest, ParseObjectRoutine)
TEST_F (ObjectParserTest, InvalidObjectId)
TEST_F (ObjectParserTest, NullRom)
TEST_F (SpriteBuilderTest, BuildSpritePropertiesOk)
TEST_F (TestDungeonObjects, ObjectParserBasicTest)
TEST_F (TestDungeonObjects, ObjectRendererBasicTest)
TEST_F (TestDungeonObjects, RoomObjectTileLoadingTest)
TEST_F (TestDungeonObjects, MockRomDataTest)
TEST_F (TestDungeonObjects, RoomObjectTileAccessTest)
TEST_F (TestDungeonObjects, ObjectRendererGraphicsSheetTest)
TEST_F (TestDungeonObjects, BitmapCopySemanticsTest)
TEST_F (TestDungeonObjects, BitmapMoveSemanticsTest)
TEST_F (TestDungeonObjects, PaletteHandlingTest)
TEST_F (TestDungeonObjects, ObjectSizeCalculationTest)
TEST_F (TestDungeonObjects, ObjectSubtypeDeterminationTest)
TEST_F (TestDungeonObjects, RoomLayoutObjectCreationTest)
TEST_F (TestDungeonObjects, RoomLayoutLoadingTest)
TEST_F (TestDungeonObjects, RoomLayoutCollisionTest)
absl::StatusOr< std::vector< uint8_t > > CompressV2 (const uint8_t *data, const int start, const int length, int mode=1, bool check=false)
Compresses a buffer of data using the LC_LZ2 algorithm.
absl::StatusOr< std::vector< uint8_t > > CompressV3 (const std::vector< uint8_t > &data, const int start, const int length, int mode=1, bool check=false)
Compresses a buffer of data using the LC_LZ2 algorithm.
absl::StatusOr< std::vector< uint8_t > > DecompressV2 (const uint8_t *data, int offset, int size=0x800, int mode=1)
Decompresses a buffer of data using the LC_LZ2 algorithm.
uint16_t ConvertRgbToSnes (const snes_color &color)
snes_color ConvertSnesToRgb (uint16_t color_snes)
std::vector< snes_color > Extract (const char *data, unsigned int offset, unsigned int palette_size)
Variables
constexpr int kCommandByteFill
constexpr int kCommandDirectCopy
constexpr int kCommandIncreasingFill
constexpr int kCommandLongLength
constexpr int kCommandRepeatingBytes
constexpr int kCommandWordFill
Enumeration Type Documentation
TestStatus
enum class yaze::test::TestStatus strong
Enumerator
kNotRun
kRunning
kPassed
kFailed
kSkipped
Definition at line 34 of file test_manager.h.
TestCategory
enum class yaze::test::TestCategory strong
Enumerator
kUnit
kIntegration
kUI
kPerformance
kMemory
Definition at line 37 of file test_manager.h.
BackgroundMode
enum class yaze::emu::BackgroundMode strong
Definition at line 25 of file ppu.h.
Function Documentation
TestStatusToString()
const char * yaze::test::TestStatusToString (TestStatus status)
Definition at line 27 of file test_manager.cc.
References kFailed, kNotRun, kPassed, kRunning, and kSkipped.
TestCategoryToString()
const char * yaze::test::TestCategoryToString (TestCategory category)
Definition at line 38 of file test_manager.cc.
References kIntegration, kMemory, kPerformance, kUI, and kUnit.
GetTestStatusColor()
ImVec4 yaze::test::GetTestStatusColor (TestStatus status)
Definition at line 49 of file test_manager.cc.
References kFailed, kNotRun, kPassed, kRunning, and kSkipped.
Referenced by yaze::test::TestManager::DrawTestDashboard().
TEST() [1/53]
yaze::test::TEST (DungeonToolsetTest , BasicFunctionality)
Unit tests for individual dungeon components.
These tests validate component behavior without requiring ROM files or complex graphics initialization.
Definition at line 19 of file dungeon_component_unit_test.cc.
References yaze::editor::DungeonToolset::background_type(), yaze::editor::DungeonToolset::kBackground1, yaze::editor::DungeonToolset::kBackground2, yaze::editor::DungeonToolset::kBackground3, yaze::editor::DungeonToolset::kBackgroundAny, yaze::editor::DungeonToolset::kBlock, yaze::editor::DungeonToolset::kChest, yaze::editor::DungeonToolset::kDoor, yaze::editor::DungeonToolset::kEntrance, yaze::editor::DungeonToolset::kItem, yaze::editor::DungeonToolset::kNoType, yaze::editor::DungeonToolset::kObject, yaze::editor::DungeonToolset::kSprite, yaze::editor::DungeonToolset::placement_type(), yaze::editor::DungeonToolset::set_background_type(), and yaze::editor::DungeonToolset::set_placement_type().
TEST() [2/53]
yaze::test::TEST (DungeonToolsetTest , CallbackFunctionality)
Definition at line 57 of file dungeon_component_unit_test.cc.
References yaze::editor::DungeonToolset::SetPaletteToggleCallback(), yaze::editor::DungeonToolset::SetRedoCallback(), and yaze::editor::DungeonToolset::SetUndoCallback().
TEST() [3/53]
yaze::test::TEST (DungeonUsageTrackerTest , BasicFunctionality)
Definition at line 77 of file dungeon_component_unit_test.cc.
References yaze::editor::DungeonUsageTracker::ClearUsageStats(), yaze::editor::DungeonUsageTracker::GetBlocksetUsage(), yaze::editor::DungeonUsageTracker::GetPaletteUsage(), yaze::editor::DungeonUsageTracker::GetSelectedBlockset(), yaze::editor::DungeonUsageTracker::GetSelectedPalette(), yaze::editor::DungeonUsageTracker::GetSelectedSpriteset(), yaze::editor::DungeonUsageTracker::GetSpritesetUsage(), yaze::editor::DungeonUsageTracker::SetSelectedBlockset(), yaze::editor::DungeonUsageTracker::SetSelectedPalette(), and yaze::editor::DungeonUsageTracker::SetSelectedSpriteset().
TEST() [4/53]
yaze::test::TEST (ComponentArchitectureTest , FileSizeReduction)
Definition at line 108 of file dungeon_component_unit_test.cc.
References yaze::editor::DungeonToolset::background_type(), yaze::editor::DungeonUsageTracker::GetBlocksetUsage(), and yaze::editor::DungeonToolset::kBackgroundAny.
TEST_F() [1/418]
yaze::test::TEST_F (ApuTest , IplRomHandshakeTiming)
Definition at line 29 of file apu_test.cc.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
TEST_F() [2/418]
yaze::test::TEST_F (ApuTest , ApuInitialization)
Definition at line 54 of file apu_test.cc.
TEST_F() [3/418]
yaze::test::TEST_F (ApuTest , SampleGenerationTiming)
Definition at line 73 of file apu_test.cc.
TEST_F() [4/418]
yaze::test::TEST_F (ApuTest , DspRegisterAccessTiming)
Definition at line 98 of file apu_test.cc.
TEST_F() [5/418]
yaze::test::TEST_F (ApuTest , DmaTransferTiming)
Definition at line 116 of file apu_test.cc.
TEST_F() [6/418]
yaze::test::TEST_F (IplHandshakeTest , ExactCycleTiming)
Definition at line 29 of file ipl_handshake_test.cc.
TEST_F() [7/418]
yaze::test::TEST_F (IplHandshakeTest , CycleRange)
Definition at line 46 of file ipl_handshake_test.cc.
TEST_F() [8/418]
yaze::test::TEST_F (IplHandshakeTest , MultipleAttempts)
Definition at line 70 of file ipl_handshake_test.cc.
TEST_F() [9/418]
yaze::test::TEST_F (IplHandshakeTest , WithInterrupts)
Definition at line 102 of file ipl_handshake_test.cc.
TEST_F() [10/418]
yaze::test::TEST_F (CpuTest , AsmParserTokenizerOk)
Definition at line 42 of file cpu_test.cc.
TEST_F() [11/418]
yaze::test::TEST_F (CpuTest , AsmParserSingleInstructionOk)
Definition at line 57 of file cpu_test.cc.
TEST_F() [12/418]
yaze::test::TEST_F (CpuTest , CheckMemoryContents)
Definition at line 68 of file cpu_test.cc.
References yaze::emu::Memory::ReadByte(), and yaze::emu::MockMemory::SetMemoryContents().
TEST_F() [13/418]
yaze::test::TEST_F (CpuTest , ADC_CheckCarryFlag)
Definition at line 91 of file cpu_test.cc.
TEST_F() [14/418]
yaze::test::TEST_F (CpuTest , ADC_DirectPageIndexedIndirectX)
Definition at line 103 of file cpu_test.cc.
TEST_F() [15/418]
yaze::test::TEST_F (CpuTest , ADC_StackRelative)
Definition at line 120 of file cpu_test.cc.
TEST_F() [16/418]
yaze::test::TEST_F (CpuTest , ADC_DirectPage)
Definition at line 134 of file cpu_test.cc.
TEST_F() [17/418]
yaze::test::TEST_F (CpuTest , ADC_DirectPageIndirectLong)
Definition at line 148 of file cpu_test.cc.
TEST_F() [18/418]
yaze::test::TEST_F (CpuTest , ADC_Immediate_TwoPositiveNumbers)
Definition at line 164 of file cpu_test.cc.
TEST_F() [19/418]
yaze::test::TEST_F (CpuTest , ADC_Immediate_PositiveAndNegativeNumbers)
Definition at line 176 of file cpu_test.cc.
TEST_F() [20/418]
yaze::test::TEST_F (CpuTest , ADC_Absolute)
Definition at line 188 of file cpu_test.cc.
TEST_F() [21/418]
yaze::test::TEST_F (CpuTest , ADC_AbsoluteLong)
Definition at line 202 of file cpu_test.cc.
TEST_F() [22/418]
yaze::test::TEST_F (CpuTest , ADC_DirectPageIndirectIndexedY)
Definition at line 216 of file cpu_test.cc.
TEST_F() [23/418]
yaze::test::TEST_F (CpuTest , ADC_DirectPageIndirect)
Definition at line 233 of file cpu_test.cc.
TEST_F() [24/418]
yaze::test::TEST_F (CpuTest , ADC_StackRelativeIndirectIndexedY)
Definition at line 249 of file cpu_test.cc.
TEST_F() [25/418]
yaze::test::TEST_F (CpuTest , ADC_DirectPageIndexedX)
Definition at line 266 of file cpu_test.cc.
TEST_F() [26/418]
yaze::test::TEST_F (CpuTest , ADC_DirectPageIndirectLongIndexedY)
Definition at line 281 of file cpu_test.cc.
TEST_F() [27/418]
yaze::test::TEST_F (CpuTest , ADC_AbsoluteIndexedY)
Definition at line 298 of file cpu_test.cc.
TEST_F() [28/418]
yaze::test::TEST_F (CpuTest , ADC_AbsoluteIndexedX)
Definition at line 314 of file cpu_test.cc.
TEST_F() [29/418]
yaze::test::TEST_F (CpuTest , ADC_AbsoluteLongIndexedX)
Definition at line 332 of file cpu_test.cc.
TEST_F() [30/418]
yaze::test::TEST_F (CpuTest , AND_DirectPageIndexedIndirectX)
Definition at line 351 of file cpu_test.cc.
TEST_F() [31/418]
yaze::test::TEST_F (CpuTest , AND_StackRelative)
Definition at line 375 of file cpu_test.cc.
TEST_F() [32/418]
yaze::test::TEST_F (CpuTest , AND_DirectPage)
Definition at line 392 of file cpu_test.cc.
TEST_F() [33/418]
yaze::test::TEST_F (CpuTest , AND_DirectPageIndirectLong)
Definition at line 410 of file cpu_test.cc.
TEST_F() [34/418]
yaze::test::TEST_F (CpuTest , AND_Immediate)
Definition at line 433 of file cpu_test.cc.
TEST_F() [35/418]
yaze::test::TEST_F (CpuTest , AND_Absolute_16BitMode)
Definition at line 442 of file cpu_test.cc.
TEST_F() [36/418]
yaze::test::TEST_F (CpuTest , AND_AbsoluteLong)
Definition at line 461 of file cpu_test.cc.
TEST_F() [37/418]
yaze::test::TEST_F (CpuTest , AND_DirectPageIndirectIndexedY)
Definition at line 475 of file cpu_test.cc.
TEST_F() [38/418]
yaze::test::TEST_F (CpuTest , AND_DirectPageIndirect)
Definition at line 492 of file cpu_test.cc.
TEST_F() [39/418]
yaze::test::TEST_F (CpuTest , AND_StackRelativeIndirectIndexedY)
Definition at line 508 of file cpu_test.cc.
TEST_F() [40/418]
yaze::test::TEST_F (CpuTest , AND_DirectPageIndexedX)
Definition at line 527 of file cpu_test.cc.
TEST_F() [41/418]
yaze::test::TEST_F (CpuTest , AND_DirectPageIndirectLongIndexedY)
Definition at line 544 of file cpu_test.cc.
TEST_F() [42/418]
yaze::test::TEST_F (CpuTest , AND_AbsoluteIndexedY)
Definition at line 562 of file cpu_test.cc.
TEST_F() [43/418]
yaze::test::TEST_F (CpuTest , AND_AbsoluteIndexedX)
Definition at line 584 of file cpu_test.cc.
TEST_F() [44/418]
yaze::test::TEST_F (CpuTest , AND_AbsoluteLongIndexedX)
Definition at line 607 of file cpu_test.cc.
TEST_F() [45/418]
yaze::test::TEST_F (CpuTest , ASL_DirectPage)
Definition at line 633 of file cpu_test.cc.
TEST_F() [46/418]
yaze::test::TEST_F (CpuTest , ASL_Accumulator)
Definition at line 646 of file cpu_test.cc.
TEST_F() [47/418]
yaze::test::TEST_F (CpuTest , ASL_Absolute)
Definition at line 659 of file cpu_test.cc.
TEST_F() [48/418]
yaze::test::TEST_F (CpuTest , ASL_DirectPageIndexedX)
Definition at line 673 of file cpu_test.cc.
TEST_F() [49/418]
yaze::test::TEST_F (CpuTest , ASL_AbsoluteIndexedX)
Definition at line 686 of file cpu_test.cc.
TEST_F() [50/418]
yaze::test::TEST_F (CpuTest , BCC_WhenCarryFlagClear)
Definition at line 704 of file cpu_test.cc.
TEST_F() [51/418]
yaze::test::TEST_F (CpuTest , BCC_WhenCarryFlagSet)
Definition at line 715 of file cpu_test.cc.
TEST_F() [52/418]
yaze::test::TEST_F (CpuTest , BCS_WhenCarryFlagSet)
Definition at line 730 of file cpu_test.cc.
TEST_F() [53/418]
yaze::test::TEST_F (CpuTest , BCS_WhenCarryFlagClear)
Definition at line 741 of file cpu_test.cc.
TEST_F() [54/418]
yaze::test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagSet)
Definition at line 753 of file cpu_test.cc.
TEST_F() [55/418]
yaze::test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagClear)
Definition at line 764 of file cpu_test.cc.
TEST_F() [56/418]
yaze::test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagSet_OverflowFlagSet)
Definition at line 776 of file cpu_test.cc.
TEST_F() [57/418]
yaze::test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagClear_OverflowFlagSet)
Definition at line 789 of file cpu_test.cc.
TEST_F() [58/418]
yaze::test::TEST_F (CpuTest , BIT_DirectPage)
Definition at line 805 of file cpu_test.cc.
TEST_F() [59/418]
yaze::test::TEST_F (CpuTest , BIT_Absolute)
Definition at line 825 of file cpu_test.cc.
TEST_F() [60/418]
yaze::test::TEST_F (CpuTest , BIT_DirectPageIndexedX)
Definition at line 844 of file cpu_test.cc.
TEST_F() [61/418]
yaze::test::TEST_F (CpuTest , BIT_AbsoluteIndexedX)
Definition at line 865 of file cpu_test.cc.
TEST_F() [62/418]
yaze::test::TEST_F (CpuTest , BIT_Immediate)
Definition at line 885 of file cpu_test.cc.
TEST_F() [63/418]
yaze::test::TEST_F (CpuTest , BMI_BranchTaken)
Definition at line 907 of file cpu_test.cc.
TEST_F() [64/418]
yaze::test::TEST_F (CpuTest , BMI_BranchNotTaken)
Definition at line 916 of file cpu_test.cc.
TEST_F() [65/418]
yaze::test::TEST_F (CpuTest , BNE_BranchTaken)
Definition at line 928 of file cpu_test.cc.
TEST_F() [66/418]
yaze::test::TEST_F (CpuTest , BNE_BranchNotTaken)
Definition at line 937 of file cpu_test.cc.
TEST_F() [67/418]
yaze::test::TEST_F (CpuTest , BPL_BranchTaken)
Definition at line 949 of file cpu_test.cc.
TEST_F() [68/418]
yaze::test::TEST_F (CpuTest , BPL_BranchNotTaken)
Definition at line 958 of file cpu_test.cc.
TEST_F() [69/418]
yaze::test::TEST_F (CpuTest , BRA)
Definition at line 970 of file cpu_test.cc.
TEST_F() [70/418]
yaze::test::TEST_F (CpuTest , BRK)
Definition at line 980 of file cpu_test.cc.
TEST_F() [71/418]
yaze::test::TEST_F (CpuTest , BRL)
Definition at line 995 of file cpu_test.cc.
TEST_F() [72/418]
yaze::test::TEST_F (CpuTest , BVC_BranchTaken)
Definition at line 1008 of file cpu_test.cc.
TEST_F() [73/418]
yaze::test::TEST_F (CpuTest , BVS_BranchTaken)
Definition at line 1020 of file cpu_test.cc.
TEST_F() [74/418]
yaze::test::TEST_F (CpuTest , CLC)
Definition at line 1032 of file cpu_test.cc.
TEST_F() [75/418]
yaze::test::TEST_F (CpuTest , CLD)
Definition at line 1045 of file cpu_test.cc.
TEST_F() [76/418]
yaze::test::TEST_F (CpuTest , CLI)
Definition at line 1058 of file cpu_test.cc.
TEST_F() [77/418]
yaze::test::TEST_F (CpuTest , CLV)
Definition at line 1071 of file cpu_test.cc.
TEST_F() [78/418]
yaze::test::TEST_F (CpuTest , CMP_DirectPageIndexedIndirectX)
Definition at line 1084 of file cpu_test.cc.
TEST_F() [79/418]
yaze::test::TEST_F (CpuTest , CMP_StackRelative)
Definition at line 1103 of file cpu_test.cc.
TEST_F() [80/418]
yaze::test::TEST_F (CpuTest , CMP_DirectPage)
Definition at line 1135 of file cpu_test.cc.
TEST_F() [81/418]
yaze::test::TEST_F (CpuTest , CMP_DirectPageIndirectLong)
Definition at line 1151 of file cpu_test.cc.
TEST_F() [82/418]
yaze::test::TEST_F (CpuTest , CMP_Immediate_8Bit)
Definition at line 1174 of file cpu_test.cc.
TEST_F() [83/418]
yaze::test::TEST_F (CpuTest , CMP_Absolute_16Bit)
Definition at line 1193 of file cpu_test.cc.
TEST_F() [84/418]
yaze::test::TEST_F (CpuTest , CMP_AbsoluteLong)
Definition at line 1208 of file cpu_test.cc.
TEST_F() [85/418]
yaze::test::TEST_F (CpuTest , CMP_DirectPageIndirect)
Definition at line 1225 of file cpu_test.cc.
TEST_F() [86/418]
yaze::test::TEST_F (CpuTest , CMP_StackRelativeIndirectIndexedY)
Definition at line 1246 of file cpu_test.cc.
TEST_F() [87/418]
yaze::test::TEST_F (CpuTest , CMP_DirectPageIndexedX)
Definition at line 1270 of file cpu_test.cc.
TEST_F() [88/418]
yaze::test::TEST_F (CpuTest , CMP_DirectPageIndirectLongIndexedY)
Definition at line 1292 of file cpu_test.cc.
TEST_F() [89/418]
yaze::test::TEST_F (CpuTest , CMP_AbsoluteIndexedY)
Definition at line 1314 of file cpu_test.cc.
TEST_F() [90/418]
yaze::test::TEST_F (CpuTest , CMP_AbsoluteIndexedX)
Definition at line 1330 of file cpu_test.cc.
TEST_F() [91/418]
yaze::test::TEST_F (CpuTest , CMP_AbsoluteLongIndexedX)
Definition at line 1346 of file cpu_test.cc.
TEST_F() [92/418]
yaze::test::TEST_F (CpuTest , COP)
Todo
FIX COP TEST
Definition at line 1365 of file cpu_test.cc.
TEST_F() [93/418]
yaze::test::TEST_F (CpuTest , CPX_Immediate_ZeroFlagSet)
Definition at line 1384 of file cpu_test.cc.
TEST_F() [94/418]
yaze::test::TEST_F (CpuTest , CPX_Immediate_NegativeFlagSet)
Definition at line 1394 of file cpu_test.cc.
TEST_F() [95/418]
yaze::test::TEST_F (CpuTest , CPX_DirectPage)
Definition at line 1405 of file cpu_test.cc.
TEST_F() [96/418]
yaze::test::TEST_F (CpuTest , CPX_Absolute)
Definition at line 1415 of file cpu_test.cc.
TEST_F() [97/418]
yaze::test::TEST_F (CpuTest , CPY_Immediate_ZeroFlagSet)
Definition at line 1425 of file cpu_test.cc.
TEST_F() [98/418]
yaze::test::TEST_F (CpuTest , CPY_Immediate_NegativeFlagSet)
Definition at line 1435 of file cpu_test.cc.
TEST_F() [99/418]
yaze::test::TEST_F (CpuTest , CPY_DirectPage)
Definition at line 1446 of file cpu_test.cc.
TEST_F() [100/418]
yaze::test::TEST_F (CpuTest , CPY_Absolute)
Definition at line 1456 of file cpu_test.cc.
TEST_F() [101/418]
yaze::test::TEST_F (CpuTest , DEC_Accumulator)
Definition at line 1469 of file cpu_test.cc.
TEST_F() [102/418]
yaze::test::TEST_F (CpuTest , DEC_DirectPage)
Definition at line 1484 of file cpu_test.cc.
TEST_F() [103/418]
yaze::test::TEST_F (CpuTest , DEC_Absolute)
Definition at line 1496 of file cpu_test.cc.
TEST_F() [104/418]
yaze::test::TEST_F (CpuTest , DEC_DirectPageIndexedX)
Definition at line 1507 of file cpu_test.cc.
TEST_F() [105/418]
yaze::test::TEST_F (CpuTest , DEC_AbsoluteIndexedX)
Definition at line 1520 of file cpu_test.cc.
TEST_F() [106/418]
yaze::test::TEST_F (CpuTest , DEX)
Definition at line 1535 of file cpu_test.cc.
TEST_F() [107/418]
yaze::test::TEST_F (CpuTest , DEY)
Definition at line 1553 of file cpu_test.cc.
TEST_F() [108/418]
yaze::test::TEST_F (CpuTest , EOR_DirectPageIndexedIndirectX)
Definition at line 1571 of file cpu_test.cc.
TEST_F() [109/418]
yaze::test::TEST_F (CpuTest , EOR_StackRelative)
Definition at line 1584 of file cpu_test.cc.
TEST_F() [110/418]
yaze::test::TEST_F (CpuTest , EOR_DirectPage)
Definition at line 1600 of file cpu_test.cc.
TEST_F() [111/418]
yaze::test::TEST_F (CpuTest , EOR_DirectPageIndirectLong)
Definition at line 1611 of file cpu_test.cc.
TEST_F() [112/418]
yaze::test::TEST_F (CpuTest , EOR_Immediate_8bit)
Definition at line 1623 of file cpu_test.cc.
TEST_F() [113/418]
yaze::test::TEST_F (CpuTest , EOR_Absolute)
Definition at line 1633 of file cpu_test.cc.
TEST_F() [114/418]
yaze::test::TEST_F (CpuTest , EOR_AbsoluteLong)
Definition at line 1644 of file cpu_test.cc.
TEST_F() [115/418]
yaze::test::TEST_F (CpuTest , EOR_DirectPageIndirectIndexedY)
Definition at line 1655 of file cpu_test.cc.
TEST_F() [116/418]
yaze::test::TEST_F (CpuTest , EOR_DirectPageIndirect)
Definition at line 1668 of file cpu_test.cc.
TEST_F() [117/418]
yaze::test::TEST_F (CpuTest , EOR_StackRelativeIndirectIndexedY)
Definition at line 1680 of file cpu_test.cc.
TEST_F() [118/418]
yaze::test::TEST_F (CpuTest , EOR_DirectPageIndexedX)
Definition at line 1698 of file cpu_test.cc.
TEST_F() [119/418]
yaze::test::TEST_F (CpuTest , EOR_DirectPageIndirectLongIndexedY)
Definition at line 1710 of file cpu_test.cc.
TEST_F() [120/418]
yaze::test::TEST_F (CpuTest , EOR_AbsoluteIndexedY)
Definition at line 1723 of file cpu_test.cc.
TEST_F() [121/418]
yaze::test::TEST_F (CpuTest , EOR_AbsoluteIndexedX)
Definition at line 1736 of file cpu_test.cc.
TEST_F() [122/418]
yaze::test::TEST_F (CpuTest , EOR_AbsoluteLongIndexedX)
Definition at line 1749 of file cpu_test.cc.
TEST_F() [123/418]
yaze::test::TEST_F (CpuTest , INC_Accumulator)
Definition at line 1765 of file cpu_test.cc.
TEST_F() [124/418]
yaze::test::TEST_F (CpuTest , INC_DirectPage_8bit)
Definition at line 1780 of file cpu_test.cc.
TEST_F() [125/418]
yaze::test::TEST_F (CpuTest , INC_Absolute_16bit)
Definition at line 1796 of file cpu_test.cc.
TEST_F() [126/418]
yaze::test::TEST_F (CpuTest , INC_DirectPage_ZeroResult_8bit)
Definition at line 1808 of file cpu_test.cc.
TEST_F() [127/418]
yaze::test::TEST_F (CpuTest , INC_Absolute_ZeroResult_16bit)
Definition at line 1820 of file cpu_test.cc.
TEST_F() [128/418]
yaze::test::TEST_F (CpuTest , INC_DirectPage_8bit_Overflow)
Definition at line 1831 of file cpu_test.cc.
TEST_F() [129/418]
yaze::test::TEST_F (CpuTest , INC_DirectPageIndexedX_8bit)
Definition at line 1841 of file cpu_test.cc.
TEST_F() [130/418]
yaze::test::TEST_F (CpuTest , INC_AbsoluteIndexedX_16bit)
Definition at line 1857 of file cpu_test.cc.
TEST_F() [131/418]
yaze::test::TEST_F (CpuTest , INX)
Definition at line 1869 of file cpu_test.cc.
TEST_F() [132/418]
yaze::test::TEST_F (CpuTest , INY)
Definition at line 1884 of file cpu_test.cc.
TEST_F() [133/418]
yaze::test::TEST_F (CpuTest , JMP_Absolute)
Definition at line 1902 of file cpu_test.cc.
TEST_F() [134/418]
yaze::test::TEST_F (CpuTest , JMP_Indirect)
Definition at line 1914 of file cpu_test.cc.
TEST_F() [135/418]
yaze::test::TEST_F (CpuTest , JML_AbsoluteLong)
Definition at line 1928 of file cpu_test.cc.
TEST_F() [136/418]
yaze::test::TEST_F (CpuTest , JMP_AbsoluteIndexedIndirectX)
Definition at line 1942 of file cpu_test.cc.
TEST_F() [137/418]
yaze::test::TEST_F (CpuTest , JMP_AbsoluteIndirectLong)
Definition at line 1955 of file cpu_test.cc.
TEST_F() [138/418]
yaze::test::TEST_F (CpuTest , JSR_Absolute)
Definition at line 1971 of file cpu_test.cc.
TEST_F() [139/418]
yaze::test::TEST_F (CpuTest , JSL_AbsoluteLong)
Definition at line 1989 of file cpu_test.cc.
TEST_F() [140/418]
yaze::test::TEST_F (CpuTest , JSL_AbsoluteIndexedIndirect)
Definition at line 2000 of file cpu_test.cc.
TEST_F() [141/418]
yaze::test::TEST_F (CpuTest , LDA_DirectPageIndexedIndirectX)
Definition at line 2016 of file cpu_test.cc.
TEST_F() [142/418]
yaze::test::TEST_F (CpuTest , LDA_StackRelative)
Definition at line 2035 of file cpu_test.cc.
TEST_F() [143/418]
yaze::test::TEST_F (CpuTest , LDA_DirectPage)
Definition at line 2053 of file cpu_test.cc.
TEST_F() [144/418]
yaze::test::TEST_F (CpuTest , LDA_DirectPageIndirectLong)
Definition at line 2069 of file cpu_test.cc.
TEST_F() [145/418]
yaze::test::TEST_F (CpuTest , LDA_Immediate_8bit)
Definition at line 2087 of file cpu_test.cc.
TEST_F() [146/418]
yaze::test::TEST_F (CpuTest , LDA_Immediate_16bit)
Definition at line 2098 of file cpu_test.cc.
TEST_F() [147/418]
yaze::test::TEST_F (CpuTest , LDA_Absolute)
Definition at line 2109 of file cpu_test.cc.
TEST_F() [148/418]
yaze::test::TEST_F (CpuTest , LDA_AbsoluteLong)
Definition at line 2125 of file cpu_test.cc.
TEST_F() [149/418]
yaze::test::TEST_F (CpuTest , LDA_DirectPageIndirectIndexedY)
Definition at line 2141 of file cpu_test.cc.
TEST_F() [150/418]
yaze::test::TEST_F (CpuTest , LDA_DirectPageIndirect)
Definition at line 2161 of file cpu_test.cc.
TEST_F() [151/418]
yaze::test::TEST_F (CpuTest , LDA_StackRelativeIndirectIndexedY)
Definition at line 2178 of file cpu_test.cc.
TEST_F() [152/418]
yaze::test::TEST_F (CpuTest , LDA_DirectPageIndexedX)
Definition at line 2198 of file cpu_test.cc.
TEST_F() [153/418]
yaze::test::TEST_F (CpuTest , LDA_DirectPageIndirectLongIndexedY)
Definition at line 2215 of file cpu_test.cc.
TEST_F() [154/418]
yaze::test::TEST_F (CpuTest , LDA_AbsoluteIndexedY)
Definition at line 2234 of file cpu_test.cc.
TEST_F() [155/418]
yaze::test::TEST_F (CpuTest , LDA_AbsoluteIndexedX)
Definition at line 2250 of file cpu_test.cc.
TEST_F() [156/418]
yaze::test::TEST_F (CpuTest , LDA_AbsoluteLongIndexedX)
Definition at line 2266 of file cpu_test.cc.
TEST_F() [157/418]
yaze::test::TEST_F (CpuTest , LDX_Immediate)
Definition at line 2284 of file cpu_test.cc.
TEST_F() [158/418]
yaze::test::TEST_F (CpuTest , LDX_DirectPage)
Definition at line 2294 of file cpu_test.cc.
TEST_F() [159/418]
yaze::test::TEST_F (CpuTest , LDX_Absolute)
Definition at line 2305 of file cpu_test.cc.
TEST_F() [160/418]
yaze::test::TEST_F (CpuTest , LDX_DirectPageIndexedY)
Definition at line 2318 of file cpu_test.cc.
TEST_F() [161/418]
yaze::test::TEST_F (CpuTest , LDX_AbsoluteIndexedY)
Definition at line 2330 of file cpu_test.cc.
TEST_F() [162/418]
yaze::test::TEST_F (CpuTest , LDY_Immediate)
Definition at line 2346 of file cpu_test.cc.
TEST_F() [163/418]
yaze::test::TEST_F (CpuTest , LDY_DirectPage)
Definition at line 2356 of file cpu_test.cc.
TEST_F() [164/418]
yaze::test::TEST_F (CpuTest , LDY_Absolute)
Definition at line 2367 of file cpu_test.cc.
TEST_F() [165/418]
yaze::test::TEST_F (CpuTest , LDY_DirectPageIndexedX)
Definition at line 2380 of file cpu_test.cc.
TEST_F() [166/418]
yaze::test::TEST_F (CpuTest , LDY_AbsoluteIndexedX)
Definition at line 2392 of file cpu_test.cc.
TEST_F() [167/418]
yaze::test::TEST_F (CpuTest , LSR_DirectPage)
Definition at line 2408 of file cpu_test.cc.
TEST_F() [168/418]
yaze::test::TEST_F (CpuTest , LSR_Accumulator)
Definition at line 2420 of file cpu_test.cc.
TEST_F() [169/418]
yaze::test::TEST_F (CpuTest , LSR_Absolute)
Definition at line 2429 of file cpu_test.cc.
TEST_F() [170/418]
yaze::test::TEST_F (CpuTest , LSR_DirectPageIndexedX)
Definition at line 2443 of file cpu_test.cc.
TEST_F() [171/418]
yaze::test::TEST_F (CpuTest , LSR_AbsoluteIndexedX)
Definition at line 2456 of file cpu_test.cc.
TEST_F() [172/418]
yaze::test::TEST_F (CpuTest , ORA_DirectPageIndexedIndirectX)
Definition at line 2474 of file cpu_test.cc.
TEST_F() [173/418]
yaze::test::TEST_F (CpuTest , ORA_StackRelative)
Definition at line 2493 of file cpu_test.cc.
TEST_F() [174/418]
yaze::test::TEST_F (CpuTest , ORA_DirectPage)
Definition at line 2511 of file cpu_test.cc.
TEST_F() [175/418]
yaze::test::TEST_F (CpuTest , ORA_DirectPageIndirectLong)
Definition at line 2527 of file cpu_test.cc.
TEST_F() [176/418]
yaze::test::TEST_F (CpuTest , ORA_Immediate)
Definition at line 2545 of file cpu_test.cc.
TEST_F() [177/418]
yaze::test::TEST_F (CpuTest , ORA_Absolute)
Definition at line 2556 of file cpu_test.cc.
TEST_F() [178/418]
yaze::test::TEST_F (CpuTest , ORA_AbsoluteLong)
Definition at line 2572 of file cpu_test.cc.
TEST_F() [179/418]
yaze::test::TEST_F (CpuTest , ORA_DirectPageIndirectIndexedY)
Definition at line 2588 of file cpu_test.cc.
TEST_F() [180/418]
yaze::test::TEST_F (CpuTest , ORA_DirectPageIndirect)
Definition at line 2608 of file cpu_test.cc.
TEST_F() [181/418]
yaze::test::TEST_F (CpuTest , ORA_StackRelativeIndirectIndexedY)
Definition at line 2625 of file cpu_test.cc.
TEST_F() [182/418]
yaze::test::TEST_F (CpuTest , ORA_DirectPageIndexedX)
Definition at line 2645 of file cpu_test.cc.
TEST_F() [183/418]
yaze::test::TEST_F (CpuTest , ORA_DirectPageIndirectLongIndexedY)
Definition at line 2662 of file cpu_test.cc.
TEST_F() [184/418]
yaze::test::TEST_F (CpuTest , ORA_AbsoluteIndexedY)
Definition at line 2681 of file cpu_test.cc.
TEST_F() [185/418]
yaze::test::TEST_F (CpuTest , ORA_AbsoluteIndexedX)
Definition at line 2697 of file cpu_test.cc.
TEST_F() [186/418]
yaze::test::TEST_F (CpuTest , ORA_AbsoluteLongIndexedX)
Definition at line 2713 of file cpu_test.cc.
TEST_F() [187/418]
yaze::test::TEST_F (CpuTest , PEA)
Definition at line 2731 of file cpu_test.cc.
TEST_F() [188/418]
yaze::test::TEST_F (CpuTest , PEI)
Definition at line 2742 of file cpu_test.cc.
TEST_F() [189/418]
yaze::test::TEST_F (CpuTest , PER)
Definition at line 2756 of file cpu_test.cc.
TEST_F() [190/418]
yaze::test::TEST_F (CpuTest , PHD)
Definition at line 2767 of file cpu_test.cc.
TEST_F() [191/418]
yaze::test::TEST_F (CpuTest , PHK)
Definition at line 2778 of file cpu_test.cc.
TEST_F() [192/418]
yaze::test::TEST_F (CpuTest , PHP)
Definition at line 2789 of file cpu_test.cc.
TEST_F() [193/418]
yaze::test::TEST_F (CpuTest , PHX)
Definition at line 2800 of file cpu_test.cc.
TEST_F() [194/418]
yaze::test::TEST_F (CpuTest , PHY)
Definition at line 2811 of file cpu_test.cc.
TEST_F() [195/418]
yaze::test::TEST_F (CpuTest , PHB)
Definition at line 2822 of file cpu_test.cc.
TEST_F() [196/418]
yaze::test::TEST_F (CpuTest , PHA)
Definition at line 2833 of file cpu_test.cc.
TEST_F() [197/418]
yaze::test::TEST_F (CpuTest , PHA_16Bit)
Definition at line 2844 of file cpu_test.cc.
TEST_F() [198/418]
yaze::test::TEST_F (CpuTest , PLA)
Definition at line 2855 of file cpu_test.cc.
TEST_F() [199/418]
yaze::test::TEST_F (CpuTest , PLA_16Bit)
Definition at line 2868 of file cpu_test.cc.
TEST_F() [200/418]
yaze::test::TEST_F (CpuTest , PLB)
Definition at line 2881 of file cpu_test.cc.
TEST_F() [201/418]
yaze::test::TEST_F (CpuTest , PLD)
Definition at line 2894 of file cpu_test.cc.
TEST_F() [202/418]
yaze::test::TEST_F (CpuTest , PLP)
Definition at line 2907 of file cpu_test.cc.
TEST_F() [203/418]
yaze::test::TEST_F (CpuTest , PLX)
Definition at line 2920 of file cpu_test.cc.
TEST_F() [204/418]
yaze::test::TEST_F (CpuTest , PLX_16Bit)
Definition at line 2933 of file cpu_test.cc.
TEST_F() [205/418]
yaze::test::TEST_F (CpuTest , PLY)
Definition at line 2947 of file cpu_test.cc.
TEST_F() [206/418]
yaze::test::TEST_F (CpuTest , PLY_16Bit)
Definition at line 2960 of file cpu_test.cc.
TEST_F() [207/418]
yaze::test::TEST_F (CpuTest , REP)
Definition at line 2976 of file cpu_test.cc.
TEST_F() [208/418]
yaze::test::TEST_F (CpuTest , REP_16Bit)
Definition at line 2985 of file cpu_test.cc.
TEST_F() [209/418]
yaze::test::TEST_F (CpuTest , PHA_PLA_Ok)
Definition at line 2994 of file cpu_test.cc.
TEST_F() [210/418]
yaze::test::TEST_F (CpuTest , PHP_PLP_Ok)
Definition at line 3004 of file cpu_test.cc.
TEST_F() [211/418]
yaze::test::TEST_F (CpuTest , PHA_PushAccumulator)
Definition at line 3032 of file cpu_test.cc.
TEST_F() [212/418]
yaze::test::TEST_F (CpuTest , PHP_PushProcessorStatusRegister)
Definition at line 3038 of file cpu_test.cc.
TEST_F() [213/418]
yaze::test::TEST_F (CpuTest , PHX_PushXRegister)
Definition at line 3044 of file cpu_test.cc.
TEST_F() [214/418]
yaze::test::TEST_F (CpuTest , PHY_PushYRegister)
Definition at line 3050 of file cpu_test.cc.
TEST_F() [215/418]
yaze::test::TEST_F (CpuTest , PHB_PushDataBankRegister)
Definition at line 3056 of file cpu_test.cc.
TEST_F() [216/418]
yaze::test::TEST_F (CpuTest , PHD_PushDirectPageRegister)
Definition at line 3062 of file cpu_test.cc.
TEST_F() [217/418]
yaze::test::TEST_F (CpuTest , PHK_PushProgramBankRegister)
Definition at line 3068 of file cpu_test.cc.
TEST_F() [218/418]
yaze::test::TEST_F (CpuTest , PLA_PullAccumulator)
Definition at line 3078 of file cpu_test.cc.
TEST_F() [219/418]
yaze::test::TEST_F (CpuTest , PLP_PullProcessorStatusRegister)
Definition at line 3084 of file cpu_test.cc.
TEST_F() [220/418]
yaze::test::TEST_F (CpuTest , PLX_PullXRegister)
Definition at line 3090 of file cpu_test.cc.
TEST_F() [221/418]
yaze::test::TEST_F (CpuTest , PLY_PullYRegister)
Definition at line 3096 of file cpu_test.cc.
TEST_F() [222/418]
yaze::test::TEST_F (CpuTest , PLB_PullDataBankRegister)
Definition at line 3102 of file cpu_test.cc.
TEST_F() [223/418]
yaze::test::TEST_F (CpuTest , PLD_PullDirectPageRegister)
Definition at line 3108 of file cpu_test.cc.
TEST_F() [224/418]
yaze::test::TEST_F (CpuTest , SEP)
Definition at line 3117 of file cpu_test.cc.
TEST_F() [225/418]
yaze::test::TEST_F (CpuTest , ROL_DirectPage)
Definition at line 3129 of file cpu_test.cc.
TEST_F() [226/418]
yaze::test::TEST_F (CpuTest , ROL_Accumulator)
Definition at line 3141 of file cpu_test.cc.
TEST_F() [227/418]
yaze::test::TEST_F (CpuTest , ROL_Absolute)
Definition at line 3150 of file cpu_test.cc.
TEST_F() [228/418]
yaze::test::TEST_F (CpuTest , ROL_DirectPageIndexedX)
Definition at line 3164 of file cpu_test.cc.
TEST_F() [229/418]
yaze::test::TEST_F (CpuTest , ROL_AbsoluteIndexedX)
Definition at line 3177 of file cpu_test.cc.
TEST_F() [230/418]
yaze::test::TEST_F (CpuTest , ROR_DirectPage)
Definition at line 3194 of file cpu_test.cc.
TEST_F() [231/418]
yaze::test::TEST_F (CpuTest , ROR_Accumulator)
Definition at line 3206 of file cpu_test.cc.
TEST_F() [232/418]
yaze::test::TEST_F (CpuTest , ROR_Absolute)
Definition at line 3215 of file cpu_test.cc.
TEST_F() [233/418]
yaze::test::TEST_F (CpuTest , ROR_DirectPageIndexedX)
Definition at line 3229 of file cpu_test.cc.
TEST_F() [234/418]
yaze::test::TEST_F (CpuTest , ROR_AbsoluteIndexedX)
Definition at line 3242 of file cpu_test.cc.
TEST_F() [235/418]
yaze::test::TEST_F (CpuTest , RTI)
Definition at line 3259 of file cpu_test.cc.
TEST_F() [236/418]
yaze::test::TEST_F (CpuTest , RTL)
Definition at line 3274 of file cpu_test.cc.
TEST_F() [237/418]
yaze::test::TEST_F (CpuTest , RTS)
Definition at line 3289 of file cpu_test.cc.
TEST_F() [238/418]
yaze::test::TEST_F (CpuTest , SBC_DirectPageIndexedIndirectX)
Definition at line 3304 of file cpu_test.cc.
TEST_F() [239/418]
yaze::test::TEST_F (CpuTest , SBC_StackRelative)
Definition at line 3325 of file cpu_test.cc.
TEST_F() [240/418]
yaze::test::TEST_F (CpuTest , SBC_DirectPage)
Definition at line 3343 of file cpu_test.cc.
TEST_F() [241/418]
yaze::test::TEST_F (CpuTest , SBC_DirectPageIndirectLong)
Definition at line 3360 of file cpu_test.cc.
TEST_F() [242/418]
yaze::test::TEST_F (CpuTest , SBC_Immediate)
Definition at line 3380 of file cpu_test.cc.
TEST_F() [243/418]
yaze::test::TEST_F (CpuTest , SBC_Absolute)
Definition at line 3393 of file cpu_test.cc.
TEST_F() [244/418]
yaze::test::TEST_F (CpuTest , SBC_AbsoluteLong)
Definition at line 3409 of file cpu_test.cc.
TEST_F() [245/418]
yaze::test::TEST_F (CpuTest , SBC_DirectPageIndirectIndexedY)
Definition at line 3425 of file cpu_test.cc.
TEST_F() [246/418]
yaze::test::TEST_F (CpuTest , SBC_DirectPageIndirect)
Definition at line 3445 of file cpu_test.cc.
TEST_F() [247/418]
yaze::test::TEST_F (CpuTest , SBC_StackRelativeIndirectIndexedY)
Definition at line 3467 of file cpu_test.cc.
TEST_F() [248/418]
yaze::test::TEST_F (CpuTest , SBC_DirectPageIndexedX)
Definition at line 3489 of file cpu_test.cc.
TEST_F() [249/418]
yaze::test::TEST_F (CpuTest , SBC_DirectPageIndirectLongIndexedY)
Definition at line 3503 of file cpu_test.cc.
TEST_F() [250/418]
yaze::test::TEST_F (CpuTest , SBC_AbsoluteIndexedY)
Definition at line 3523 of file cpu_test.cc.
TEST_F() [251/418]
yaze::test::TEST_F (CpuTest , SBC_AbsoluteIndexedX)
Definition at line 3540 of file cpu_test.cc.
TEST_F() [252/418]
yaze::test::TEST_F (CpuTest , SBC_AbsoluteLongIndexedX)
Definition at line 3557 of file cpu_test.cc.
TEST_F() [253/418]
yaze::test::TEST_F (CpuTest , SEC)
Definition at line 3576 of file cpu_test.cc.
TEST_F() [254/418]
yaze::test::TEST_F (CpuTest , SED)
Definition at line 3583 of file cpu_test.cc.
TEST_F() [255/418]
yaze::test::TEST_F (CpuTest , SEI)
Definition at line 3592 of file cpu_test.cc.
TEST_F() [256/418]
yaze::test::TEST_F (CpuTest , SEP_8Bit)
Definition at line 3599 of file cpu_test.cc.
TEST_F() [257/418]
yaze::test::TEST_F (CpuTest , SEP_16Bit)
Definition at line 3609 of file cpu_test.cc.
TEST_F() [258/418]
yaze::test::TEST_F (CpuTest , STA_DirectPageIndexedIndirectX)
Definition at line 3621 of file cpu_test.cc.
TEST_F() [259/418]
yaze::test::TEST_F (CpuTest , STA_StackRelative)
Definition at line 3638 of file cpu_test.cc.
TEST_F() [260/418]
yaze::test::TEST_F (CpuTest , STA_DirectPage)
Definition at line 3652 of file cpu_test.cc.
TEST_F() [261/418]
yaze::test::TEST_F (CpuTest , STA_DirectPageIndirectLong)
Definition at line 3663 of file cpu_test.cc.
TEST_F() [262/418]
yaze::test::TEST_F (CpuTest , STA_Absolute)
Definition at line 3678 of file cpu_test.cc.
TEST_F() [263/418]
yaze::test::TEST_F (CpuTest , STA_AbsoluteLong)
Definition at line 3689 of file cpu_test.cc.
TEST_F() [264/418]
yaze::test::TEST_F (CpuTest , STA_DirectPageIndirectIndexedY)
Definition at line 3700 of file cpu_test.cc.
TEST_F() [265/418]
yaze::test::TEST_F (CpuTest , STA_DirectPageIndirect)
Definition at line 3716 of file cpu_test.cc.
TEST_F() [266/418]
yaze::test::TEST_F (CpuTest , STA_StackRelativeIndirectIndexedY)
Definition at line 3732 of file cpu_test.cc.
TEST_F() [267/418]
yaze::test::TEST_F (CpuTest , STA_DirectPageIndexedX)
Definition at line 3749 of file cpu_test.cc.
TEST_F() [268/418]
yaze::test::TEST_F (CpuTest , STA_DirectPageIndirectLongIndexedY)
Definition at line 3761 of file cpu_test.cc.
TEST_F() [269/418]
yaze::test::TEST_F (CpuTest , STA_AbsoluteIndexedY)
Definition at line 3777 of file cpu_test.cc.
TEST_F() [270/418]
yaze::test::TEST_F (CpuTest , STA_AbsoluteIndexedX)
Definition at line 3790 of file cpu_test.cc.
TEST_F() [271/418]
yaze::test::TEST_F (CpuTest , STA_AbsoluteLongIndexedX)
Definition at line 3803 of file cpu_test.cc.
TEST_F() [272/418]
yaze::test::TEST_F (CpuTest , STP)
Definition at line 3818 of file cpu_test.cc.
TEST_F() [273/418]
yaze::test::TEST_F (CpuTest , STX_DirectPage)
Definition at line 3825 of file cpu_test.cc.
TEST_F() [274/418]
yaze::test::TEST_F (CpuTest , STX_Absolute)
Definition at line 3836 of file cpu_test.cc.
TEST_F() [275/418]
yaze::test::TEST_F (CpuTest , STX_DirectPageIndexedY)
Definition at line 3848 of file cpu_test.cc.
TEST_F() [276/418]
yaze::test::TEST_F (CpuTest , STY_DirectPage)
Definition at line 3862 of file cpu_test.cc.
TEST_F() [277/418]
yaze::test::TEST_F (CpuTest , STY_Absolute)
Definition at line 3873 of file cpu_test.cc.
TEST_F() [278/418]
yaze::test::TEST_F (CpuTest , STY_DirectPageIndexedX)
Definition at line 3885 of file cpu_test.cc.
TEST_F() [279/418]
yaze::test::TEST_F (CpuTest , STZ_DirectPage)
Definition at line 3899 of file cpu_test.cc.
TEST_F() [280/418]
yaze::test::TEST_F (CpuTest , STZ_DirectPageIndexedX)
Definition at line 3909 of file cpu_test.cc.
TEST_F() [281/418]
yaze::test::TEST_F (CpuTest , STZ_Absolute)
Definition at line 3920 of file cpu_test.cc.
TEST_F() [282/418]
yaze::test::TEST_F (CpuTest , TAX)
Definition at line 3934 of file cpu_test.cc.
TEST_F() [283/418]
yaze::test::TEST_F (CpuTest , TAY)
Definition at line 3946 of file cpu_test.cc.
TEST_F() [284/418]
yaze::test::TEST_F (CpuTest , TCD)
Definition at line 3957 of file cpu_test.cc.
TEST_F() [285/418]
yaze::test::TEST_F (CpuTest , TCS)
Definition at line 3969 of file cpu_test.cc.
TEST_F() [286/418]
yaze::test::TEST_F (CpuTest , TDC)
Definition at line 3983 of file cpu_test.cc.
TEST_F() [287/418]
yaze::test::TEST_F (CpuTest , TRB_DirectPage)
Definition at line 3995 of file cpu_test.cc.
TEST_F() [288/418]
yaze::test::TEST_F (CpuTest , TRB_Absolute)
Definition at line 4009 of file cpu_test.cc.
TEST_F() [289/418]
yaze::test::TEST_F (CpuTest , TSB_DirectPage)
Definition at line 4025 of file cpu_test.cc.
TEST_F() [290/418]
yaze::test::TEST_F (CpuTest , TSB_Absolute)
Definition at line 4039 of file cpu_test.cc.
TEST_F() [291/418]
yaze::test::TEST_F (CpuTest , TSC)
Definition at line 4055 of file cpu_test.cc.
TEST_F() [292/418]
yaze::test::TEST_F (CpuTest , TSX)
Definition at line 4067 of file cpu_test.cc.
TEST_F() [293/418]
yaze::test::TEST_F (CpuTest , TXA)
Definition at line 4080 of file cpu_test.cc.
TEST_F() [294/418]
yaze::test::TEST_F (CpuTest , TXS)
Definition at line 4091 of file cpu_test.cc.
TEST_F() [295/418]
yaze::test::TEST_F (CpuTest , TXY)
Definition at line 4103 of file cpu_test.cc.
TEST_F() [296/418]
yaze::test::TEST_F (CpuTest , TYA)
Definition at line 4116 of file cpu_test.cc.
TEST_F() [297/418]
yaze::test::TEST_F (CpuTest , TYX)
Definition at line 4128 of file cpu_test.cc.
TEST_F() [298/418]
yaze::test::TEST_F (CpuTest , WAI)
Definition at line 4139 of file cpu_test.cc.
TEST_F() [299/418]
yaze::test::TEST_F (CpuTest , WDM)
Definition at line 4146 of file cpu_test.cc.
TEST_F() [300/418]
yaze::test::TEST_F (CpuTest , XBA)
Definition at line 4155 of file cpu_test.cc.
TEST_F() [301/418]
yaze::test::TEST_F (CpuTest , XCESwitchToNativeMode)
Definition at line 4168 of file cpu_test.cc.
TEST_F() [302/418]
yaze::test::TEST_F (CpuTest , XCESwitchToEmulationMode)
Definition at line 4174 of file cpu_test.cc.
TEST_F() [303/418]
yaze::test::TEST_F (CpuTest , XCESwitchBackAndForth)
Definition at line 4180 of file cpu_test.cc.
TEST_F() [304/418]
yaze::test::TEST_F (Spc700Test , MOV_A_Immediate)
Definition at line 81 of file spc700_test.cc.
TEST_F() [305/418]
yaze::test::TEST_F (Spc700Test , MOV_A_X)
Definition at line 96 of file spc700_test.cc.
TEST_F() [306/418]
yaze::test::TEST_F (Spc700Test , MOV_A_Y)
Definition at line 108 of file spc700_test.cc.
TEST_F() [307/418]
yaze::test::TEST_F (Spc700Test , MOV_A_dp)
Definition at line 120 of file spc700_test.cc.
TEST_F() [308/418]
yaze::test::TEST_F (Spc700Test , MOV_A_dp_plus_x)
Definition at line 138 of file spc700_test.cc.
TEST_F() [309/418]
yaze::test::TEST_F (Spc700Test , MOV_A_dp_indirect_plus_y)
Definition at line 157 of file spc700_test.cc.
TEST_F() [310/418]
yaze::test::TEST_F (Spc700Test , MOV_A_dp_plus_x_indirect)
Definition at line 178 of file spc700_test.cc.
TEST_F() [311/418]
yaze::test::TEST_F (Spc700Test , MOV_A_abs)
Definition at line 199 of file spc700_test.cc.
TEST_F() [312/418]
yaze::test::TEST_F (Spc700Test , MOV_Immediate)
Definition at line 221 of file spc700_test.cc.
TEST_F() [313/418]
yaze::test::TEST_F (Spc700Test , NOP_DoesNothing)
Definition at line 237 of file spc700_test.cc.
TEST_F() [314/418]
yaze::test::TEST_F (Spc700Test , ADC_A_Immediate)
Definition at line 249 of file spc700_test.cc.
TEST_F() [315/418]
yaze::test::TEST_F (Spc700Test , BEQ_BranchesIfZeroFlagSet)
Definition at line 265 of file spc700_test.cc.
TEST_F() [316/418]
yaze::test::TEST_F (Spc700Test , STA_Absolute)
Definition at line 279 of file spc700_test.cc.
TEST_F() [317/418]
yaze::test::TEST_F (Spc700Test , ExecuteADCWithImmediate)
Definition at line 293 of file spc700_test.cc.
TEST_F() [318/418]
yaze::test::TEST_F (Spc700Test , ExecuteBRA)
Definition at line 309 of file spc700_test.cc.
TEST_F() [319/418]
yaze::test::TEST_F (Spc700Test , ReadFromAudioRAM)
Definition at line 323 of file spc700_test.cc.
TEST_F() [320/418]
yaze::test::TEST_F (Spc700Test , WriteToAudioRAM)
Definition at line 333 of file spc700_test.cc.
TEST_F() [321/418]
yaze::test::TEST_F (Spc700Test , ExecuteANDWithImmediate)
Definition at line 342 of file spc700_test.cc.
TEST_F() [322/418]
yaze::test::TEST_F (Spc700Test , ExecuteORWithImmediate)
Definition at line 357 of file spc700_test.cc.
TEST_F() [323/418]
yaze::test::TEST_F (Spc700Test , ExecuteEORWithImmediate)
Definition at line 372 of file spc700_test.cc.
TEST_F() [324/418]
yaze::test::TEST_F (Spc700Test , ExecuteINC)
Definition at line 387 of file spc700_test.cc.
TEST_F() [325/418]
yaze::test::TEST_F (Spc700Test , ExecuteDEC)
Definition at line 399 of file spc700_test.cc.
TEST_F() [326/418]
yaze::test::TEST_F (Spc700Test , ExecuteBNEWhenNotEqual)
Definition at line 411 of file spc700_test.cc.
TEST_F() [327/418]
yaze::test::TEST_F (Spc700Test , ExecuteBNEWhenEqual)
Definition at line 425 of file spc700_test.cc.
TEST_F() [328/418]
yaze::test::TEST_F (Spc700Test , ExecuteBEQWhenEqual)
Definition at line 439 of file spc700_test.cc.
TEST_F() [329/418]
yaze::test::TEST_F (Spc700Test , ExecuteBEQWhenNotEqual)
Definition at line 453 of file spc700_test.cc.
TEST_F() [330/418]
yaze::test::TEST_F (Spc700Test , BootIplRomOk)
Definition at line 467 of file spc700_test.cc.
TEST() [5/53]
yaze::test::TEST (LC_LZ2_CompressionTest , TrivialRepeatedBytes)
Definition at line 106 of file compression_test.cc.
TEST() [6/53]
yaze::test::TEST (LC_LZ2_CompressionTest , RepeatedBytesBetweenUncompressable)
Definition at line 110 of file compression_test.cc.
TEST() [7/53]
yaze::test::TEST (LC_LZ2_CompressionTest , RepeatedBytesBeforeUncompressable)
Definition at line 115 of file compression_test.cc.
TEST() [8/53]
yaze::test::TEST (LC_LZ2_CompressionTest , RepeatedBytesAfterUncompressable)
Definition at line 120 of file compression_test.cc.
TEST() [9/53]
yaze::test::TEST (LC_LZ2_CompressionTest , RepeatedBytesAfterUncompressableRepeated)
Definition at line 125 of file compression_test.cc.
TEST() [10/53]
yaze::test::TEST (LC_LZ2_CompressionTest , RepeatedBytesBeforeUncompressableRepeated)
Definition at line 131 of file compression_test.cc.
TEST() [11/53]
yaze::test::TEST (LC_LZ2_CompressionTest , NewDecompressionPieceOk)
Definition at line 137 of file compression_test.cc.
References yaze::gfx::lc_lz2::CompressionPiece::argument, yaze::gfx::lc_lz2::CompressionPiece::argument_length, yaze::gfx::lc_lz2::CompressionPiece::command, yaze::gfx::lc_lz2::CompressionPiece::length, and yaze::gfx::lc_lz2::CompressionPiece::next.
TEST() [12/53]
yaze::test::TEST (LC_LZ2_CompressionTest , CompressionSingleSet)
Todo
Check why header built is off by one
Definition at line 163 of file compression_test.cc.
References BUILD_HEADER.
TEST() [13/53]
yaze::test::TEST (LC_LZ2_CompressionTest , CompressionSingleWord)
Definition at line 172 of file compression_test.cc.
References BUILD_HEADER.
TEST() [14/53]
yaze::test::TEST (LC_LZ2_CompressionTest , CompressionSingleIncrement)
Definition at line 181 of file compression_test.cc.
References BUILD_HEADER.
TEST() [15/53]
yaze::test::TEST (LC_LZ2_CompressionTest , CompressionSingleCopy)
Definition at line 189 of file compression_test.cc.
References BUILD_HEADER.
TEST() [16/53]
yaze::test::TEST (LC_LZ2_CompressionTest , CompressionSingleOverflowIncrement)
Definition at line 198 of file compression_test.cc.
References BUILD_HEADER.
TEST() [17/53]
yaze::test::TEST (HandleDirectCopyTest , NotDirectCopyWithAccumulatedBytes)
TEST(LC_LZ2_CompressionTest, CompressionSingleCopyRepeat) { std::vector<uint8_t> single_copy_expected = {0x03, 0x0A, 0x07, 0x14, 0x03, 0x0A, 0x07, 0x14};
auto comp_result = ExpectCompressV3Ok(single_copy_expected, {BUILD_HEADER(0x00, 0x04), 0x03, 0x0A, 0x07, 0x14, BUILD_HEADER(0x04, 0x04), 0x00, 0x00, 0xFF}); EXPECT_THAT(single_copy_expected, ElementsAreArray(comp_result.data(), 6)); }
TEST(LC_LZ2_CompressionTest, CompressionMixedRepeatIncrement) { AssertCompressionQuality({0x05, 0x05, 0x05, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x05, 0x02, 0x05, 0x02, 0x05, 0x02, 0x0A, 0x0B, 0x05, 0x02, 0x05, 0x02, 0x05, 0x02, 0x08, 0x0A, 0x00, 0x05}, {BUILD_HEADER(0x01, 0x04), 0x05, BUILD_HEADER(0x03, 0x06), 0x06, BUILD_HEADER(0x00, 0x01), 0x05, 0xFF}); }
TEST(LC_LZ2_CompressionTest, CompressionMixedIncrementIntraCopyOffset) { "Mixing, inc, alternate, intra copy" compress start: 3, length: 21 compressed length: 9 AssertCompressionQuality({0x05, 0x05, 0x05, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x05, 0x02, 0x05, 0x02, 0x05, 0x02, 0x0A, 0x0B, 0x05, 0x02, 0x05, 0x02, 0x05, 0x02, 0x08, 0x0A, 0x00, 0x05}, {BUILD_HEADER(0x03, 0x07), 0x05, BUILD_HEADER(0x02, 0x06), 0x05, 0x02, BUILD_HEADER(0x04, 0x08), 0x05, 0x00, 0xFF}); }
TEST(LC_LZ2_CompressionTest, CompressionMixedIncrementIntraCopySource) { "Mixing, inc, alternate, intra copy" 0, 28 16 AssertCompressionQuality({0x05, 0x05, 0x05, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x05, 0x02, 0x05, 0x02, 0x05, 0x02, 0x0A, 0x0B, 0x05, 0x02, 0x05, 0x02, 0x05, 0x02, 0x08, 0x0A, 0x00, 0x05}, {BUILD_HEADER(0x01, 0x04), 0x05, BUILD_HEADER(0x03, 0x06), 0x06, BUILD_HEADER(0x02, 0x06), 0x05, 0x02, BUILD_HEADER(0x04, 0x08), 0x08, 0x00, BUILD_HEADER(0x00, 0x04), 0x08, 0x0A, 0x00, 0x05, 0xFF}); }
Extended Header 111CCCLL LLLLLLLL CCC: Real command LLLLLLLLLL: Length
Normally you have 5 bits for the length, so the maximum value you can represent is 31 (which outputs 32 bytes). With the long length, you get 5 more bits for the length, so the maximum value you can represent becomes 1023, outputting 1024 bytes at a time.
void build_extended_header(uint8_t command, uint8_t length, uint8_t& byte1, uint8_t& byte2) { byte1 = command << 3; byte1 += (length - 1); byte1 += 0b11100000; byte2 = length >> 3; }
std::vector<uint8_t> CreateRepeatedBetweenUncompressable(int leftUncompressedSize, int repeatedByteSize, int rightUncompressedSize) { std::vector<uint8_t> result(leftUncompressedSize + repeatedByteSize + rightUncompressedSize, 0); std::fill_n(result.begin() + leftUncompressedSize, repeatedByteSize, 0x00); return result; }
TEST(LC_LZ2_CompressionTest, LengthBorderCompression) { "Length border compression" std::vector<uint8_t> result(42, 0); std::fill_n(result.begin(), 42, 0x05); AssertCompressionQuality(result, {BUILD_HEADER(0x04, 42), 0x05, 0x05, 0xFF});
"Extended length, 400 repeat of 5" std::vector<uint8_t> result2(400, 0); std::fill_n(result2.begin(), 400, 0x05); uint8_t byte1; uint8_t byte2; build_extended_header(0x01, 42, byte1, byte2); AssertCompressionQuality(result2, {byte1, byte2, 0x05, 0x05, 0xFF});
"Extended length, 1050 repeat of 5" std::vector<uint8_t> result3(1050, 0); std::fill_n(result3.begin(), 1050, 0x05); uint8_t byte3; uint8_t byte4; build_extended_header(0x04, 1050, byte3, byte4); AssertCompressionQuality(result3, {byte3, byte4, 0x05, 0x05, 0xFF});
// "Extended length, 2050 repeat of 5" std::vector<uint8_t> result4(2050, 0); std::fill_n(result4.begin(), 2050, 0x05); uint8_t byte5; uint8_t byte6; build_extended_header(0x04, 2050, byte5, byte6); AssertCompressionQuality(result4, {byte5, byte6, 0x05, 0x05, 0xFF}); }
TEST(LC_LZ2_CompressionTest, CompressionExtendedWordCopy) { ROM rom; uint8_t buffer[3000]; for (unsigned int i = 0; i < 3000; i += 2) { buffer[i] = 0x05; buffer[i + 1] = 0x06; } uint8_t hightlength_word_1050[] = { 0b11101011, 0xFF, 0x05, 0x06, BUILD_HEADER(0x02, 0x1A), 0x05, 0x06, 0xFF};
// "Extended word copy" auto comp_result = ExpectCompressOk(rom, buffer, 1050); EXPECT_THAT(hightlength_word_1050, ElementsAreArray(comp_result.data(), 8));
std::vector<uint8_t> buffer(3000, 0); std::fill_n(buffer.begin(), 3000, 0x05); for (unsigned int i = 0; i < 3000; i += 2) { buffer[i] = 0x05; buffer[i + 1] = 0x06; }
uint8_t byte1; uint8_t byte2; build_extended_header(0x02, 0x1A, byte1, byte2); AssertCompressionQuality(buffer, {0b11101011, 0xFF, 0x05, 0x06, byte1, byte2, 0x05, 0x06, 0xFF}); }
TEST(LC_LZ2_CompressionTest, CompressionMixedPatterns) { AssertCompressionQuality({0x05, 0x05, 0x05, 0x06, 0x07, 0x06, 0x07, 0x08, 0x09, 0x0A}, {BUILD_HEADER(0x01, 0x03), 0x05, BUILD_HEADER(0x02, 0x04), 0x06, 0x07, BUILD_HEADER(0x03, 0x03), 0x08, 0xFF}); }
TEST(LC_LZ2_CompressionTest, CompressionLongIntraCopy) { ROM rom; uint8_t long_data[15] = {0x05, 0x06, 0x07, 0x08, 0x05, 0x06, 0x07, 0x08, 0x05, 0x06, 0x07, 0x08, 0x05, 0x06, 0x07}; uint8_t long_expected[] = {BUILD_HEADER(0x00, 0x04), 0x05, 0x06, 0x07, 0x08, BUILD_HEADER(0x04, 0x0C), 0x00, 0x00, 0xFF};
auto comp_result = ExpectCompressOk(rom, long_data, 15); EXPECT_THAT(long_expected, ElementsAreArray(comp_result.data(), sizeof(long_expected))); }
Definition at line 357 of file compression_test.cc.
References yaze::gfx::lc_lz2::CompressionContext::cmd_with_max, and kCommandByteFill.
TEST() [18/53]
yaze::test::TEST (HandleDirectCopyTest , NotDirectCopyWithoutAccumulatedBytes)
Definition at line 365 of file compression_test.cc.
References yaze::gfx::lc_lz2::CompressionContext::cmd_with_max, and kCommandByteFill.
TEST() [19/53]
yaze::test::TEST (HandleDirectCopyTest , AccumulateBytesWithoutMax)
Definition at line 372 of file compression_test.cc.
References yaze::gfx::lc_lz2::CompressionContext::cmd_with_max, and kCommandDirectCopy.
TEST() [20/53]
yaze::test::TEST (CheckIncByteV3Test , IncreasingSequence)
Definition at line 382 of file compression_test.cc.
References kCommandIncreasingFill.
TEST() [21/53]
yaze::test::TEST (CheckIncByteV3Test , IncreasingSequenceSurroundedByIdenticalBytes)
Definition at line 388 of file compression_test.cc.
References kCommandIncreasingFill.
TEST() [22/53]
yaze::test::TEST (CheckIncByteV3Test , NotAnIncreasingSequence)
Definition at line 396 of file compression_test.cc.
References kCommandIncreasingFill.
TEST() [23/53]
yaze::test::TEST (LC_LZ2_CompressionTest , DecompressionValidCommand)
Definition at line 403 of file compression_test.cc.
References BUILD_HEADER.
TEST() [24/53]
yaze::test::TEST (LC_LZ2_CompressionTest , DecompressionMixingCommand)
Definition at line 412 of file compression_test.cc.
References BUILD_HEADER.
TEST() [25/53]
yaze::test::TEST (SnesColorTest , DefaultConstructor)
Definition at line 27 of file snes_palette_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::snes().
TEST() [26/53]
yaze::test::TEST (SnesColorTest , RGBConstructor)
Definition at line 36 of file snes_palette_test.cc.
References yaze::gfx::SnesColor::rgb().
TEST() [27/53]
yaze::test::TEST (SnesColorTest , SNESConstructor)
Definition at line 45 of file snes_palette_test.cc.
References yaze::gfx::SnesColor::snes().
TEST() [28/53]
yaze::test::TEST (SnesColorTest , ConvertRgbToSnes)
Definition at line 51 of file snes_palette_test.cc.
References ConvertRgbToSnes().
TEST() [29/53]
yaze::test::TEST (SnesColorTest , ConvertSnestoRGB)
Definition at line 57 of file snes_palette_test.cc.
References snes_color::blue, ConvertSnesToRgb(), snes_color::green, and snes_color::red.
TEST() [30/53]
yaze::test::TEST (SnesColorTest , ConvertSnesToRGB_Binary)
Definition at line 65 of file snes_palette_test.cc.
References ConvertSnesToRgb().
TEST() [31/53]
yaze::test::TEST (SnesColorTest , Extraction)
Definition at line 82 of file snes_palette_test.cc.
References Extract().
TEST() [32/53]
yaze::test::TEST (SnesColorTest , Convert)
Definition at line 94 of file snes_palette_test.cc.
References yaze::gfx::Convert(), and Extract().
TEST() [33/53]
yaze::test::TEST (SnesPaletteTest , DefaultConstructor)
Definition at line 113 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::empty(), and yaze::gfx::SnesPalette::size().
TEST() [34/53]
yaze::test::TEST (SnesPaletteTest , AddColor)
Definition at line 119 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::AddColor(), and yaze::gfx::SnesPalette::size().
TEST() [35/53]
yaze::test::TEST (SnesPaletteTest , AddMultipleColors)
Definition at line 126 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::AddColor(), and yaze::gfx::SnesPalette::size().
TEST() [36/53]
yaze::test::TEST (SnesPaletteTest , UpdateColor)
Definition at line 135 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::AddColor(), and yaze::gfx::SnesPalette::UpdateColor().
TEST() [37/53]
yaze::test::TEST (SnesPaletteTest , SubPalette)
Definition at line 145 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::AddColor(), and yaze::gfx::SnesPalette::sub_palette().
TEST() [38/53]
yaze::test::TEST (SnesPaletteTest , VectorConstructor)
Definition at line 160 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::size().
TEST() [39/53]
yaze::test::TEST (SnesPaletteTest , Clear)
Definition at line 167 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::AddColor(), yaze::gfx::SnesPalette::clear(), yaze::gfx::SnesPalette::empty(), and yaze::gfx::SnesPalette::size().
TEST() [40/53]
yaze::test::TEST (SnesPaletteTest , Iterator)
Definition at line 176 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::AddColor().
TEST() [41/53]
yaze::test::TEST (SnesPaletteTest , OperatorAccess)
Definition at line 191 of file snes_palette_test.cc.
References yaze::gfx::SnesPalette::AddColor().
TEST() [42/53]
yaze::test::TEST (SnesTileTest , UnpackBppTile)
Definition at line 14 of file snes_tile_test.cc.
References yaze::gfx::UnpackBppTile().
TEST() [43/53]
yaze::test::TEST (SnesTileTest , PackBppTile)
Definition at line 76 of file snes_tile_test.cc.
References snes_tile8::data, and yaze::gfx::PackBppTile().
TEST() [44/53]
yaze::test::TEST (SnesTileTest , ConvertBpp)
Definition at line 100 of file snes_tile_test.cc.
References yaze::gfx::ConvertBpp().
TEST() [45/53]
yaze::test::TEST (SnesTileTest , TileInfo)
Definition at line 117 of file snes_tile_test.cc.
References yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::gfx::TileInfo::over_, yaze::gfx::TileInfo::palette_, and yaze::gfx::TileInfo::vertical_mirror_.
TEST() [46/53]
yaze::test::TEST (SnesTileTest , TileInfoToWord)
Definition at line 138 of file snes_tile_test.cc.
References yaze::gfx::TileInfoToWord().
TEST() [47/53]
yaze::test::TEST (SnesTileTest , WordToTileInfo)
Definition at line 151 of file snes_tile_test.cc.
References yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::gfx::TileInfo::over_, yaze::gfx::TileInfo::palette_, yaze::gfx::TileInfo::vertical_mirror_, and yaze::gfx::WordToTileInfo().
TEST() [48/53]
yaze::test::TEST (SnesTileTest , Tile32)
Definition at line 162 of file snes_tile_test.cc.
References yaze::gfx::Tile32::GetPackedValue(), yaze::gfx::Tile32::tile0_, yaze::gfx::Tile32::tile1_, yaze::gfx::Tile32::tile2_, and yaze::gfx::Tile32::tile3_.
TEST() [49/53]
yaze::test::TEST (SnesTileTest , Tile16)
Definition at line 185 of file snes_tile_test.cc.
References yaze::gfx::Tile16::tile0_, yaze::gfx::Tile16::tile1_, yaze::gfx::Tile16::tile2_, yaze::gfx::Tile16::tile3_, and yaze::gfx::Tile16::tiles_info.
TEST() [50/53]
yaze::test::TEST (HexTest , HexByte)
Definition at line 10 of file hex_test.cc.
References yaze::util::HexByte(), yaze::util::HexStringParams::k0x, yaze::util::HexStringParams::kHash, yaze::util::HexStringParams::kNone, yaze::util::HexStringParams::prefix, and yaze::util::HexStringParams::uppercase.
TEST() [51/53]
yaze::test::TEST (HexTest , HexWord)
Definition at line 33 of file hex_test.cc.
References yaze::util::HexWord(), yaze::util::HexStringParams::k0x, yaze::util::HexStringParams::kHash, yaze::util::HexStringParams::kNone, yaze::util::HexStringParams::prefix, and yaze::util::HexStringParams::uppercase.
TEST() [52/53]
yaze::test::TEST (HexTest , HexLong)
Definition at line 56 of file hex_test.cc.
References yaze::util::HexLong(), yaze::util::HexStringParams::k0x, yaze::util::HexStringParams::kHash, yaze::util::HexStringParams::kNone, yaze::util::HexStringParams::prefix, and yaze::util::HexStringParams::uppercase.
TEST() [53/53]
yaze::test::TEST (HexTest , HexLongLong)
Definition at line 79 of file hex_test.cc.
References yaze::util::HexLongLong(), yaze::util::HexStringParams::k0x, yaze::util::HexStringParams::kHash, yaze::util::HexStringParams::kNone, yaze::util::HexStringParams::prefix, and yaze::util::HexStringParams::uppercase.
TEST_F() [331/418]
yaze::test::TEST_F (DungeonEditorIntegrationTest , ObjectParsingTest)
Definition at line 211 of file dungeon_editor_test.cc.
TEST_F() [332/418]
yaze::test::TEST_F (DungeonEditorIntegrationTest , ObjectRenderingTest)
Definition at line 215 of file dungeon_editor_test.cc.
TEST_F() [333/418]
yaze::test::TEST_F (DungeonEditorIntegrationTest , RoomGraphicsTest)
Definition at line 219 of file dungeon_editor_test.cc.
TEST_F() [334/418]
yaze::test::TEST_F (DungeonEditorIntegrationTest , PaletteHandlingTest)
Definition at line 223 of file dungeon_editor_test.cc.
TEST_F() [335/418]
yaze::test::TEST_F (DungeonEditorIntegrationTest , MockRomValidation)
Definition at line 227 of file dungeon_editor_test.cc.
References yaze::test::MockRom::ValidateObjectData(), and yaze::test::MockRom::ValidateRoomData().
TEST_F() [336/418]
yaze::test::TEST_F (RomTest , Uninitialized)
Definition at line 29 of file rom_test.cc.
TEST_F() [337/418]
yaze::test::TEST_F (RomTest , LoadFromFile)
Definition at line 34 of file rom_test.cc.
References EXPECT_OK.
TEST_F() [338/418]
yaze::test::TEST_F (RomTest , LoadFromFileInvalid)
Definition at line 43 of file rom_test.cc.
TEST_F() [339/418]
yaze::test::TEST_F (RomTest , LoadFromFileEmpty)
Definition at line 50 of file rom_test.cc.
TEST_F() [340/418]
yaze::test::TEST_F (RomTest , ReadByteOk)
Definition at line 55 of file rom_test.cc.
References ASSERT_OK_AND_ASSIGN, and EXPECT_OK.
TEST_F() [341/418]
yaze::test::TEST_F (RomTest , ReadByteInvalid)
Definition at line 65 of file rom_test.cc.
TEST_F() [342/418]
yaze::test::TEST_F (RomTest , ReadWordOk)
Definition at line 70 of file rom_test.cc.
References EXPECT_OK, and IsOkAndHolds().
TEST_F() [343/418]
yaze::test::TEST_F (RomTest , ReadWordInvalid)
Definition at line 81 of file rom_test.cc.
TEST_F() [344/418]
yaze::test::TEST_F (RomTest , ReadLongOk)
Definition at line 86 of file rom_test.cc.
References EXPECT_OK, and IsOkAndHolds().
TEST_F() [345/418]
yaze::test::TEST_F (RomTest , ReadBytesOk)
Definition at line 98 of file rom_test.cc.
References ASSERT_OK_AND_ASSIGN, and EXPECT_OK.
TEST_F() [346/418]
yaze::test::TEST_F (RomTest , ReadBytesOutOfRange)
Definition at line 106 of file rom_test.cc.
References EXPECT_OK.
TEST_F() [347/418]
yaze::test::TEST_F (RomTest , WriteByteOk)
Definition at line 114 of file rom_test.cc.
References ASSERT_OK_AND_ASSIGN, and EXPECT_OK.
TEST_F() [348/418]
yaze::test::TEST_F (RomTest , WriteWordOk)
Definition at line 125 of file rom_test.cc.
References ASSERT_OK_AND_ASSIGN, and EXPECT_OK.
TEST_F() [349/418]
yaze::test::TEST_F (RomTest , WriteLongOk)
Definition at line 136 of file rom_test.cc.
References ASSERT_OK_AND_ASSIGN, and EXPECT_OK.
TEST_F() [350/418]
yaze::test::TEST_F (RomTest , WriteTransactionSuccess)
Definition at line 147 of file rom_test.cc.
References EXPECT_OK, yaze::Rom::LoadFromData(), and yaze::Rom::WriteTransaction().
TEST_F() [351/418]
yaze::test::TEST_F (RomTest , WriteTransactionFailure)
Definition at line 160 of file rom_test.cc.
References EXPECT_OK, yaze::Rom::LoadFromData(), TEST_F(), and yaze::Rom::WriteTransaction().
TEST_F() [352/418]
yaze::test::TEST_F (RomTest , ReadTransactionSuccess)
Definition at line 174 of file rom_test.cc.
References EXPECT_OK, yaze::Rom::LoadFromData(), yaze::Rom::ReadTransaction(), and TEST_F().
TEST_F() [353/418]
yaze::test::TEST_F (RomTest , ReadTransactionFailure)
Definition at line 186 of file rom_test.cc.
References EXPECT_OK, yaze::Rom::LoadFromData(), yaze::Rom::ReadTransaction(), and TEST_F().
TEST_F() [354/418]
yaze::test::TEST_F (RomTest , SaveTruncatesExistingFile)
Definition at line 195 of file rom_test.cc.
References EXPECT_OK, yaze::Rom::SaveSettings::filename, yaze::Rom::LoadFromFile(), yaze::Rom::ReadByte(), yaze::Rom::size(), TEST_F(), and yaze::Rom::SaveSettings::z3_save.
TEST_F() [355/418]
yaze::test::TEST_F (RomTest , TransactionRollbackRestoresOriginals)
Definition at line 223 of file rom_test.cc.
References yaze::Transaction::Commit(), EXPECT_OK, TEST_F(), yaze::Transaction::WriteByte(), and yaze::Transaction::WriteWord().
RunIntegrationTest()
int yaze::test::RunIntegrationTest ()
Todo
Fix the window/controller management
Definition at line 46 of file test_editor.cc.
References yaze::gui::ColorsYaze(), yaze::core::CreateWindow(), yaze::core::Controller::DoRender(), yaze::core::Renderer::Get(), yaze::core::Controller::IsActive(), yaze::core::Controller::OnExit(), yaze::core::Controller::OnInput(), yaze::test::TestEditor::RegisterTests(), yaze::core::Controller::set_active(), yaze::test::TestEditor::Update(), and yaze::core::Controller::window().
Referenced by main().
MATCHER_P() [1/4]
yaze::test::MATCHER_P (StatusIs , status , "")
Definition at line 26 of file testing.h.
IsOkAndHolds()
template<typename T> ::testing::AssertionResult yaze::test::IsOkAndHolds (const absl::StatusOr< T > & status_or, const T & value)
Definition at line 30 of file testing.h.
Referenced by MATCHER_P(), TEST_F(), and TEST_F().
MATCHER_P() [2/4]
yaze::test::MATCHER_P (IsOkAndHolds , value , "")
Definition at line 43 of file testing.h.
References IsOkAndHolds().
MATCHER_P() [3/4]
yaze::test::MATCHER_P (StatusIsWithMessage , message , "")
Definition at line 46 of file testing.h.
MATCHER_P() [4/4]
yaze::test::MATCHER_P (StatusIsWithCode , code , "")
Definition at line 51 of file testing.h.
IsOkAndMatches()
template<typename T, typename Matcher> ::testing::AssertionResult yaze::test::IsOkAndMatches (const absl::StatusOr< T > & status_or, const Matcher & matcher)
Definition at line 58 of file testing.h.
StatusOrEqual()
template<typename T> ::testing::AssertionResult yaze::test::StatusOrEqual (const absl::StatusOr< T > & a, const absl::StatusOr< T > & b)
Definition at line 73 of file testing.h.
TEST_F() [356/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , EmptyRoomRendering)
Definition at line 386 of file dungeon_object_rendering_tests.cc.
TEST_F() [357/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , MultiObjectRoomRendering)
Definition at line 403 of file dungeon_object_rendering_tests.cc.
TEST_F() [358/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , ComplexRoomRendering)
Definition at line 420 of file dungeon_object_rendering_tests.cc.
TEST_F() [359/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , LargeRoomRendering)
Definition at line 437 of file dungeon_object_rendering_tests.cc.
TEST_F() [360/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , BossRoomRendering)
Definition at line 456 of file dungeon_object_rendering_tests.cc.
TEST_F() [361/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , PuzzleRoomRendering)
Definition at line 473 of file dungeon_object_rendering_tests.cc.
TEST_F() [362/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , PaletteConsistency)
Definition at line 491 of file dungeon_object_rendering_tests.cc.
TEST_F() [363/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , ScenarioPerformanceBenchmark)
Definition at line 508 of file dungeon_object_rendering_tests.cc.
TEST_F() [364/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , ScenarioMemoryUsage)
Definition at line 531 of file dungeon_object_rendering_tests.cc.
TEST_F() [365/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , ObjectOverlapHandling)
Definition at line 555 of file dungeon_object_rendering_tests.cc.
TEST_F() [366/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , LayerRenderingOrder)
Definition at line 581 of file dungeon_object_rendering_tests.cc.
TEST_F() [367/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , ScenarioCacheEfficiency)
Definition at line 609 of file dungeon_object_rendering_tests.cc.
TEST_F() [368/418]
yaze::test::TEST_F (DungeonObjectRenderingTests , BoundaryObjectPlacement)
Definition at line 628 of file dungeon_object_rendering_tests.cc.
TEST_F() [369/418]
yaze::test::TEST_F (DungeonRoomTest , SingleRoomLoadOk)
Definition at line 27 of file dungeon_room_test.cc.
References yaze::zelda3::LoadRoomFromRom().
TEST_F() [370/418]
yaze::test::TEST_F (MessageTest , ParseSingleMessage_CommandParsing)
Definition at line 26 of file message_test.cc.
References yaze::editor::ParseSingleMessage().
TEST_F() [371/418]
yaze::test::TEST_F (MessageTest , ParseSingleMessage_BasicAscii)
Definition at line 39 of file message_test.cc.
References yaze::editor::ParseMessageData(), and yaze::editor::ParseSingleMessage().
TEST_F() [372/418]
yaze::test::TEST_F (MessageTest , FindMatchingCharacter_Success)
Definition at line 55 of file message_test.cc.
References yaze::editor::FindMatchingCharacter().
TEST_F() [373/418]
yaze::test::TEST_F (MessageTest , FindMatchingCharacter_Failure)
Definition at line 62 of file message_test.cc.
References yaze::editor::FindMatchingCharacter().
TEST_F() [374/418]
yaze::test::TEST_F (MessageTest , FindDictionaryEntry_Success)
Definition at line 67 of file message_test.cc.
References yaze::editor::FindDictionaryEntry().
TEST_F() [375/418]
yaze::test::TEST_F (MessageTest , FindDictionaryEntry_Failure)
Definition at line 72 of file message_test.cc.
References yaze::editor::FindDictionaryEntry().
TEST_F() [376/418]
yaze::test::TEST_F (MessageTest , ParseMessageToData_Basic)
Definition at line 77 of file message_test.cc.
References yaze::editor::ParseMessageToData().
TEST_F() [377/418]
yaze::test::TEST_F (MessageTest , ReplaceAllDictionaryWords_Success)
Definition at line 84 of file message_test.cc.
References yaze::editor::ReplaceAllDictionaryWords().
TEST_F() [378/418]
yaze::test::TEST_F (MessageTest , ReplaceAllDictionaryWords_NoMatch)
Definition at line 93 of file message_test.cc.
References yaze::editor::ReplaceAllDictionaryWords().
TEST_F() [379/418]
yaze::test::TEST_F (MessageTest , ParseTextDataByte_Success)
Definition at line 101 of file message_test.cc.
References yaze::editor::ParseTextDataByte().
TEST_F() [380/418]
yaze::test::TEST_F (MessageTest , ParseTextDataByte_Failure)
Definition at line 107 of file message_test.cc.
References yaze::editor::ParseTextDataByte().
TEST_F() [381/418]
yaze::test::TEST_F (MessageTest , ParseSingleMessage_SpecialCharacters)
Definition at line 111 of file message_test.cc.
References yaze::editor::ParseSingleMessage().
TEST_F() [382/418]
yaze::test::TEST_F (MessageTest , ParseSingleMessage_DictionaryReference)
Definition at line 123 of file message_test.cc.
References yaze::editor::ParseSingleMessage().
TEST_F() [383/418]
yaze::test::TEST_F (MessageTest , ParseSingleMessage_InvalidTerminator)
Definition at line 135 of file message_test.cc.
References yaze::editor::ParseSingleMessage().
TEST_F() [384/418]
yaze::test::TEST_F (MessageTest , ParseSingleMessage_EmptyData)
Definition at line 143 of file message_test.cc.
References yaze::editor::ParseSingleMessage().
TEST_F() [385/418]
yaze::test::TEST_F (MessageTest , OptimizeMessageForDictionary_Basic)
Definition at line 155 of file message_test.cc.
References yaze::editor::MessageData::OptimizeMessageForDictionary().
TEST_F() [386/418]
yaze::test::TEST_F (MessageTest , SetMessage_Success)
Definition at line 168 of file message_test.cc.
References yaze::editor::MessageData::ContentsParsed, yaze::editor::MessageData::RawString, and yaze::editor::MessageData::SetMessage().
TEST_F() [387/418]
yaze::test::TEST_F (MessageTest , FindMatchingElement_CommandWithArgument)
Definition at line 180 of file message_test.cc.
References yaze::editor::ParsedElement::Active, yaze::editor::FindMatchingElement(), yaze::editor::ParsedElement::Parent, yaze::editor::TextElement::Token, and yaze::editor::ParsedElement::Value.
TEST_F() [388/418]
yaze::test::TEST_F (MessageTest , FindMatchingElement_InvalidCommand)
Definition at line 189 of file message_test.cc.
References yaze::editor::ParsedElement::Active, and yaze::editor::FindMatchingElement().
TEST_F() [389/418]
yaze::test::TEST_F (MessageTest , BuildDictionaryEntries_CorrectSize)
Definition at line 196 of file message_test.cc.
References yaze::editor::BuildDictionaryEntries(), and yaze::editor::kNumDictionaryEntries.
TEST_F() [390/418]
yaze::test::TEST_F (ObjectParserStructsTest , ObjectRoutineInfoDefaultConstructor)
Definition at line 13 of file object_parser_structs_test.cc.
References yaze::zelda3::ObjectRoutineInfo::is_orientation_dependent, yaze::zelda3::ObjectRoutineInfo::is_repeatable, yaze::zelda3::ObjectRoutineInfo::routine_ptr, yaze::zelda3::ObjectRoutineInfo::tile_count, and yaze::zelda3::ObjectRoutineInfo::tile_ptr.
TEST_F() [391/418]
yaze::test::TEST_F (ObjectParserStructsTest , ObjectSubtypeInfoDefaultConstructor)
Definition at line 23 of file object_parser_structs_test.cc.
References yaze::zelda3::ObjectSubtypeInfo::max_tile_count, yaze::zelda3::ObjectSubtypeInfo::routine_ptr, yaze::zelda3::ObjectSubtypeInfo::subtype, and yaze::zelda3::ObjectSubtypeInfo::subtype_ptr.
TEST_F() [392/418]
yaze::test::TEST_F (ObjectParserStructsTest , ObjectSizeInfoDefaultConstructor)
Definition at line 32 of file object_parser_structs_test.cc.
References yaze::zelda3::ObjectSizeInfo::height_tiles, yaze::zelda3::ObjectSizeInfo::is_horizontal, yaze::zelda3::ObjectSizeInfo::is_repeatable, yaze::zelda3::ObjectSizeInfo::repeat_count, and yaze::zelda3::ObjectSizeInfo::width_tiles.
TEST_F() [393/418]
yaze::test::TEST_F (ObjectParserStructsTest , ObjectRoutineInfoAssignment)
Definition at line 42 of file object_parser_structs_test.cc.
References yaze::zelda3::ObjectRoutineInfo::is_orientation_dependent, yaze::zelda3::ObjectRoutineInfo::is_repeatable, yaze::zelda3::ObjectRoutineInfo::routine_ptr, yaze::zelda3::ObjectRoutineInfo::tile_count, and yaze::zelda3::ObjectRoutineInfo::tile_ptr.
TEST_F() [394/418]
yaze::test::TEST_F (ObjectParserStructsTest , ObjectSubtypeInfoAssignment)
Definition at line 58 of file object_parser_structs_test.cc.
References yaze::zelda3::ObjectSubtypeInfo::max_tile_count, yaze::zelda3::ObjectSubtypeInfo::routine_ptr, yaze::zelda3::ObjectSubtypeInfo::subtype, and yaze::zelda3::ObjectSubtypeInfo::subtype_ptr.
TEST_F() [395/418]
yaze::test::TEST_F (ObjectParserStructsTest , ObjectSizeInfoAssignment)
Definition at line 72 of file object_parser_structs_test.cc.
References yaze::zelda3::ObjectSizeInfo::height_tiles, yaze::zelda3::ObjectSizeInfo::is_horizontal, yaze::zelda3::ObjectSizeInfo::is_repeatable, yaze::zelda3::ObjectSizeInfo::repeat_count, and yaze::zelda3::ObjectSizeInfo::width_tiles.
TEST_F() [396/418]
yaze::test::TEST_F (ObjectParserTest , ParseSubtype1Object)
Definition at line 63 of file object_parser_test.cc.
TEST_F() [397/418]
yaze::test::TEST_F (ObjectParserTest , ParseSubtype2Object)
Definition at line 79 of file object_parser_test.cc.
TEST_F() [398/418]
yaze::test::TEST_F (ObjectParserTest , ParseSubtype3Object)
Definition at line 87 of file object_parser_test.cc.
TEST_F() [399/418]
yaze::test::TEST_F (ObjectParserTest , GetObjectSubtype)
Definition at line 95 of file object_parser_test.cc.
TEST_F() [400/418]
yaze::test::TEST_F (ObjectParserTest , ParseObjectSize)
Definition at line 109 of file object_parser_test.cc.
TEST_F() [401/418]
yaze::test::TEST_F (ObjectParserTest , ParseObjectRoutine)
Definition at line 121 of file object_parser_test.cc.
TEST_F() [402/418]
yaze::test::TEST_F (ObjectParserTest , InvalidObjectId)
Definition at line 133 of file object_parser_test.cc.
TEST_F() [403/418]
yaze::test::TEST_F (ObjectParserTest , NullRom)
Definition at line 139 of file object_parser_test.cc.
References yaze::zelda3::ObjectParser::ParseObject().
TEST_F() [404/418]
yaze::test::TEST_F (SpriteBuilderTest , BuildSpritePropertiesOk)
Definition at line 56 of file sprite_builder_test.cc.
TEST_F() [405/418]
yaze::test::TEST_F (TestDungeonObjects , ObjectParserBasicTest)
Definition at line 111 of file test_dungeon_objects.cc.
References yaze::zelda3::ObjectParser::ParseObject().
TEST_F() [406/418]
yaze::test::TEST_F (TestDungeonObjects , ObjectRendererBasicTest)
Definition at line 119 of file test_dungeon_objects.cc.
References yaze::gfx::SnesPalette::AddColor(), and yaze::zelda3::ObjectRenderer::RenderObject().
TEST_F() [407/418]
yaze::test::TEST_F (TestDungeonObjects , RoomObjectTileLoadingTest)
Definition at line 139 of file test_dungeon_objects.cc.
TEST_F() [408/418]
yaze::test::TEST_F (TestDungeonObjects , MockRomDataTest)
Definition at line 148 of file test_dungeon_objects.cc.
TEST_F() [409/418]
yaze::test::TEST_F (TestDungeonObjects , RoomObjectTileAccessTest)
Definition at line 156 of file test_dungeon_objects.cc.
TEST_F() [410/418]
yaze::test::TEST_F (TestDungeonObjects , ObjectRendererGraphicsSheetTest)
Definition at line 185 of file test_dungeon_objects.cc.
References yaze::gfx::SnesPalette::AddColor(), and yaze::zelda3::ObjectRenderer::RenderObject().
TEST_F() [411/418]
yaze::test::TEST_F (TestDungeonObjects , BitmapCopySemanticsTest)
Definition at line 210 of file test_dungeon_objects.cc.
References yaze::gfx::Bitmap::height(), yaze::gfx::Bitmap::is_active(), yaze::gfx::Bitmap::surface(), and yaze::gfx::Bitmap::width().
TEST_F() [412/418]
yaze::test::TEST_F (TestDungeonObjects , BitmapMoveSemanticsTest)
Definition at line 231 of file test_dungeon_objects.cc.
References yaze::gfx::Bitmap::height(), yaze::gfx::Bitmap::is_active(), yaze::gfx::Bitmap::surface(), and yaze::gfx::Bitmap::width().
TEST_F() [413/418]
yaze::test::TEST_F (TestDungeonObjects , PaletteHandlingTest)
Definition at line 250 of file test_dungeon_objects.cc.
References yaze::gfx::SnesPalette::AddColor(), and yaze::gfx::SnesPalette::size().
TEST_F() [414/418]
yaze::test::TEST_F (TestDungeonObjects , ObjectSizeCalculationTest)
Definition at line 275 of file test_dungeon_objects.cc.
References yaze::zelda3::ObjectParser::ParseObjectSize().
TEST_F() [415/418]
yaze::test::TEST_F (TestDungeonObjects , ObjectSubtypeDeterminationTest)
Definition at line 290 of file test_dungeon_objects.cc.
References yaze::zelda3::ObjectParser::DetermineSubtype(), and yaze::zelda3::ObjectParser::GetObjectSubtype().
TEST_F() [416/418]
yaze::test::TEST_F (TestDungeonObjects , RoomLayoutObjectCreationTest)
Definition at line 308 of file test_dungeon_objects.cc.
References yaze::zelda3::RoomLayoutObject::GetTile(), yaze::zelda3::RoomLayoutObject::GetTypeName(), yaze::zelda3::RoomLayoutObject::id(), yaze::zelda3::RoomLayoutObject::kWall, yaze::zelda3::RoomLayoutObject::layer(), yaze::zelda3::RoomLayoutObject::type(), yaze::zelda3::RoomLayoutObject::x(), and yaze::zelda3::RoomLayoutObject::y().
TEST_F() [417/418]
yaze::test::TEST_F (TestDungeonObjects , RoomLayoutLoadingTest)
Definition at line 325 of file test_dungeon_objects.cc.
References yaze::zelda3::RoomLayout::GetDimensions(), yaze::zelda3::RoomLayout::GetObjectAt(), yaze::zelda3::RoomLayout::GetObjectsByType(), yaze::zelda3::RoomLayoutObject::kFloor, yaze::zelda3::RoomLayoutObject::kWall, and yaze::zelda3::RoomLayout::LoadLayout().
TEST_F() [418/418]
yaze::test::TEST_F (TestDungeonObjects , RoomLayoutCollisionTest)
Definition at line 347 of file test_dungeon_objects.cc.
References yaze::zelda3::RoomLayout::HasFloor(), and yaze::zelda3::RoomLayout::HasWall().
CompressV2()
absl::StatusOr< std::vector< uint8_t > > yaze::gfx::lc_lz2::CompressV2 (const uint8_t * data, const int start, const int length, int mode = 1, bool check = false)
Compresses a buffer of data using the LC_LZ2 algorithm.
Deprecated
Use HyruleMagicDecompress instead.
Definition at line 800 of file compression.cc.
CompressV3()
absl::StatusOr< std::vector< uint8_t > > yaze::gfx::lc_lz2::CompressV3 (const std::vector< uint8_t > & data, const int start, const int length, int mode = 1, bool check = false)
Compresses a buffer of data using the LC_LZ2 algorithm.
Deprecated
Use HyruleMagicCompress
Definition at line 1313 of file compression.cc.
Referenced by yaze::test::anonymous_namespace{compression_test.cc}::AssertCompressionQuality(), yaze::test::anonymous_namespace{compression_test.cc}::ExpectCompressOk(), and yaze::test::anonymous_namespace{compression_test.cc}::ExpectCompressV3Ok().
DecompressV2()
absl::StatusOr< std::vector< uint8_t > > yaze::gfx::lc_lz2::DecompressV2 (const uint8_t * data, int offset, int size = 0x800, int mode = 1)
Decompresses a buffer of data using the LC_LZ2 algorithm.
Note
Works well for graphics but not overworld data. Prefer Hyrule Magic routines for overworld data.
Definition at line 1372 of file compression.cc.
Referenced by yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk(), and yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressOk().
ConvertRgbToSnes()
uint16_t yaze::gfx::ConvertRgbToSnes (const snes_color & color)
Definition at line 33 of file snes_color.cc.
Referenced by TEST().
ConvertSnesToRgb()
snes_color yaze::gfx::ConvertSnesToRgb (uint16_t color_snes)
Definition at line 19 of file snes_color.cc.
Referenced by TEST(), and TEST().
Extract()
std::vector< snes_color > yaze::gfx::Extract (const char * data, unsigned int offset, unsigned int palette_size)
Definition at line 58 of file snes_color.cc.
Referenced by TEST(), and TEST().
Variable Documentation
kCommandByteFill
int yaze::gfx::lc_lz2::kCommandByteFill constexpr
Definition at line 46 of file compression.h.
Referenced by TEST(), and TEST().
kCommandDirectCopy
int yaze::gfx::lc_lz2::kCommandDirectCopy constexpr
Definition at line 45 of file compression.h.
Referenced by TEST().
kCommandIncreasingFill
int yaze::gfx::lc_lz2::kCommandIncreasingFill constexpr
Definition at line 48 of file compression.h.
Referenced by TEST(), TEST(), and TEST().
kCommandLongLength
int yaze::gfx::lc_lz2::kCommandLongLength constexpr
Definition at line 50 of file compression.h.
kCommandRepeatingBytes
int yaze::gfx::lc_lz2::kCommandRepeatingBytes constexpr
Definition at line 49 of file compression.h.
kCommandWordFill
int yaze::gfx::lc_lz2::kCommandWordFill constexpr
Definition at line 47 of file compression.h.