yaze: yaze::zelda3::overworld::anonymous_namespace{overworld.cc} Namespace Reference
yaze::zelda3::overworld::anonymous_namespace{overworld.cc} Namespace Reference
Functions
std::vector< uint64_t > GetAllTile16 (OWMapTiles &map_tiles_)
bool compareItemsArrays (std::vector< OverworldItem > item_array1, std::vector< OverworldItem > item_array2)
Function Documentation
GetAllTile16()
std::vector< uint64_t > yaze::zelda3::overworld::anonymous_namespace{overworld.cc}::GetAllTile16 (OWMapTiles & map_tiles_)
Definition at line 993 of file overworld.cc.
References yaze::zelda3::OWMapTiles::dark_world, GetAllTile16(), yaze::gfx::Tile32::GetPackedValue(), yaze::zelda3::overworld::kNumOverworldMaps, yaze::zelda3::OWMapTiles::light_world, and yaze::zelda3::OWMapTiles::special_world.
Referenced by GetAllTile16().
compareItemsArrays()
bool yaze::zelda3::overworld::anonymous_namespace{overworld.cc}::compareItemsArrays (std::vector< OverworldItem > item_array1, std::vector< OverworldItem > item_array2)
Definition at line 1436 of file overworld.cc.
References compareItemsArrays().
Referenced by compareItemsArrays().