yaze: yaze_test::emu_test Namespace Reference
yaze_test::emu_test Namespace Reference
Classes
class CpuTest
class MockAudioRam
MockAudioRam is a mock class for the AudioRam class.
class MockPpu
Mock Ppu class for testing.
class PpuTest
class Spc700Test
Functions
TEST_F (CpuTest, AsmParserTokenizerOk)
TEST_F (CpuTest, AsmParserSingleInstructionOk)
TEST_F (CpuTest, CheckMemoryContents)
TEST_F (CpuTest, ADC_CheckCarryFlag)
TEST_F (CpuTest, ADC_DirectPageIndexedIndirectX)
TEST_F (CpuTest, ADC_StackRelative)
TEST_F (CpuTest, ADC_DirectPage)
TEST_F (CpuTest, ADC_DirectPageIndirectLong)
TEST_F (CpuTest, ADC_Immediate_TwoPositiveNumbers)
TEST_F (CpuTest, ADC_Immediate_PositiveAndNegativeNumbers)
TEST_F (CpuTest, ADC_Absolute)
TEST_F (CpuTest, ADC_AbsoluteLong)
TEST_F (CpuTest, ADC_DirectPageIndirectIndexedY)
TEST_F (CpuTest, ADC_DirectPageIndirect)
TEST_F (CpuTest, ADC_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, ADC_DirectPageIndexedX)
TEST_F (CpuTest, ADC_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, ADC_AbsoluteIndexedY)
TEST_F (CpuTest, ADC_AbsoluteIndexedX)
TEST_F (CpuTest, ADC_AbsoluteLongIndexedX)
TEST_F (CpuTest, AND_DirectPageIndexedIndirectX)
TEST_F (CpuTest, AND_StackRelative)
TEST_F (CpuTest, AND_DirectPage)
TEST_F (CpuTest, AND_DirectPageIndirectLong)
TEST_F (CpuTest, AND_Immediate)
TEST_F (CpuTest, AND_Absolute_16BitMode)
TEST_F (CpuTest, AND_AbsoluteLong)
TEST_F (CpuTest, AND_DirectPageIndirectIndexedY)
TEST_F (CpuTest, AND_DirectPageIndirect)
TEST_F (CpuTest, AND_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, AND_DirectPageIndexedX)
TEST_F (CpuTest, AND_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, AND_AbsoluteIndexedY)
TEST_F (CpuTest, AND_AbsoluteIndexedX)
TEST_F (CpuTest, AND_AbsoluteLongIndexedX)
TEST_F (CpuTest, ASL_DirectPage)
TEST_F (CpuTest, ASL_Accumulator)
TEST_F (CpuTest, ASL_Absolute)
TEST_F (CpuTest, ASL_DirectPageIndexedX)
TEST_F (CpuTest, ASL_AbsoluteIndexedX)
TEST_F (CpuTest, BCC_WhenCarryFlagClear)
TEST_F (CpuTest, BCC_WhenCarryFlagSet)
TEST_F (CpuTest, BCS_WhenCarryFlagSet)
TEST_F (CpuTest, BCS_WhenCarryFlagClear)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagSet)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagClear)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagSet_OverflowFlagSet)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagClear_OverflowFlagSet)
TEST_F (CpuTest, BIT_DirectPage)
TEST_F (CpuTest, BIT_Absolute)
TEST_F (CpuTest, BIT_DirectPageIndexedX)
TEST_F (CpuTest, BIT_AbsoluteIndexedX)
TEST_F (CpuTest, BIT_Immediate)
TEST_F (CpuTest, BMI_BranchTaken)
TEST_F (CpuTest, BMI_BranchNotTaken)
TEST_F (CpuTest, BNE_BranchTaken)
TEST_F (CpuTest, BNE_BranchNotTaken)
TEST_F (CpuTest, BPL_BranchTaken)
TEST_F (CpuTest, BPL_BranchNotTaken)
TEST_F (CpuTest, BRA)
TEST_F (CpuTest, BRK)
TEST_F (CpuTest, BRL)
TEST_F (CpuTest, BVC_BranchTaken)
TEST_F (CpuTest, BVS_BranchTaken)
TEST_F (CpuTest, CLC)
TEST_F (CpuTest, CLD)
TEST_F (CpuTest, CLI)
TEST_F (CpuTest, CLV)
TEST_F (CpuTest, CMP_DirectPageIndexedIndirectX)
TEST_F (CpuTest, CMP_StackRelative)
TEST_F (CpuTest, CMP_DirectPage)
TEST_F (CpuTest, CMP_DirectPageIndirectLong)
TEST_F (CpuTest, CMP_Immediate_8Bit)
TEST_F (CpuTest, CMP_Absolute_16Bit)
TEST_F (CpuTest, CMP_AbsoluteLong)
TEST_F (CpuTest, CMP_DirectPageIndirect)
TEST_F (CpuTest, CMP_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, CMP_DirectPageIndexedX)
TEST_F (CpuTest, CMP_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, CMP_AbsoluteIndexedY)
TEST_F (CpuTest, CMP_AbsoluteIndexedX)
TEST_F (CpuTest, CMP_AbsoluteLongIndexedX)
TEST_F (CpuTest, COP)
TEST_F (CpuTest, CPX_Immediate_ZeroFlagSet)
TEST_F (CpuTest, CPX_Immediate_NegativeFlagSet)
TEST_F (CpuTest, CPX_DirectPage)
TEST_F (CpuTest, CPX_Absolute)
TEST_F (CpuTest, CPY_Immediate_ZeroFlagSet)
TEST_F (CpuTest, CPY_Immediate_NegativeFlagSet)
TEST_F (CpuTest, CPY_DirectPage)
TEST_F (CpuTest, CPY_Absolute)
TEST_F (CpuTest, DEC_Accumulator)
TEST_F (CpuTest, DEC_DirectPage)
TEST_F (CpuTest, DEC_Absolute)
TEST_F (CpuTest, DEC_DirectPageIndexedX)
TEST_F (CpuTest, DEC_AbsoluteIndexedX)
TEST_F (CpuTest, DEX)
TEST_F (CpuTest, DEY)
TEST_F (CpuTest, EOR_DirectPageIndexedIndirectX)
TEST_F (CpuTest, EOR_StackRelative)
TEST_F (CpuTest, EOR_DirectPage)
TEST_F (CpuTest, EOR_DirectPageIndirectLong)
TEST_F (CpuTest, EOR_Immediate_8bit)
TEST_F (CpuTest, EOR_Absolute)
TEST_F (CpuTest, EOR_AbsoluteLong)
TEST_F (CpuTest, EOR_DirectPageIndirectIndexedY)
TEST_F (CpuTest, EOR_DirectPageIndirect)
TEST_F (CpuTest, EOR_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, EOR_DirectPageIndexedX)
TEST_F (CpuTest, EOR_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, EOR_AbsoluteIndexedY)
TEST_F (CpuTest, EOR_AbsoluteIndexedX)
TEST_F (CpuTest, EOR_AbsoluteLongIndexedX)
TEST_F (CpuTest, INC_Accumulator)
TEST_F (CpuTest, INC_DirectPage_8bit)
TEST_F (CpuTest, INC_Absolute_16bit)
TEST_F (CpuTest, INC_DirectPage_ZeroResult_8bit)
TEST_F (CpuTest, INC_Absolute_ZeroResult_16bit)
TEST_F (CpuTest, INC_DirectPage_8bit_Overflow)
TEST_F (CpuTest, INC_DirectPageIndexedX_8bit)
TEST_F (CpuTest, INC_AbsoluteIndexedX_16bit)
TEST_F (CpuTest, INX)
TEST_F (CpuTest, INY)
TEST_F (CpuTest, JMP_Absolute)
TEST_F (CpuTest, JMP_Indirect)
TEST_F (CpuTest, JML_AbsoluteLong)
TEST_F (CpuTest, JMP_AbsoluteIndexedIndirectX)
TEST_F (CpuTest, JMP_AbsoluteIndirectLong)
TEST_F (CpuTest, JSR_Absolute)
TEST_F (CpuTest, JSL_AbsoluteLong)
TEST_F (CpuTest, JSL_AbsoluteIndexedIndirect)
TEST_F (CpuTest, LDA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, LDA_StackRelative)
TEST_F (CpuTest, LDA_DirectPage)
TEST_F (CpuTest, LDA_DirectPageIndirectLong)
TEST_F (CpuTest, LDA_Immediate_8bit)
TEST_F (CpuTest, LDA_Immediate_16bit)
TEST_F (CpuTest, LDA_Absolute)
TEST_F (CpuTest, LDA_AbsoluteLong)
TEST_F (CpuTest, LDA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, LDA_DirectPageIndirect)
TEST_F (CpuTest, LDA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, LDA_DirectPageIndexedX)
TEST_F (CpuTest, LDA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, LDA_AbsoluteIndexedY)
TEST_F (CpuTest, LDA_AbsoluteIndexedX)
TEST_F (CpuTest, LDA_AbsoluteLongIndexedX)
TEST_F (CpuTest, LDX_Immediate)
TEST_F (CpuTest, LDX_DirectPage)
TEST_F (CpuTest, LDX_Absolute)
TEST_F (CpuTest, LDX_DirectPageIndexedY)
TEST_F (CpuTest, LDX_AbsoluteIndexedY)
TEST_F (CpuTest, LDY_Immediate)
TEST_F (CpuTest, LDY_DirectPage)
TEST_F (CpuTest, LDY_Absolute)
TEST_F (CpuTest, LDY_DirectPageIndexedX)
TEST_F (CpuTest, LDY_AbsoluteIndexedX)
TEST_F (CpuTest, LSR_DirectPage)
TEST_F (CpuTest, LSR_Accumulator)
TEST_F (CpuTest, LSR_Absolute)
TEST_F (CpuTest, LSR_DirectPageIndexedX)
TEST_F (CpuTest, LSR_AbsoluteIndexedX)
TEST_F (CpuTest, ORA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, ORA_StackRelative)
TEST_F (CpuTest, ORA_DirectPage)
TEST_F (CpuTest, ORA_DirectPageIndirectLong)
TEST_F (CpuTest, ORA_Immediate)
TEST_F (CpuTest, ORA_Absolute)
TEST_F (CpuTest, ORA_AbsoluteLong)
TEST_F (CpuTest, ORA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, ORA_DirectPageIndirect)
TEST_F (CpuTest, ORA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, ORA_DirectPageIndexedX)
TEST_F (CpuTest, ORA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, ORA_AbsoluteIndexedY)
TEST_F (CpuTest, ORA_AbsoluteIndexedX)
TEST_F (CpuTest, ORA_AbsoluteLongIndexedX)
TEST_F (CpuTest, PEA)
TEST_F (CpuTest, PEI)
TEST_F (CpuTest, PER)
TEST_F (CpuTest, PHD)
TEST_F (CpuTest, PHK)
TEST_F (CpuTest, PHP)
TEST_F (CpuTest, PHX)
TEST_F (CpuTest, PHY)
TEST_F (CpuTest, PHB)
TEST_F (CpuTest, PHA)
TEST_F (CpuTest, PHA_16Bit)
TEST_F (CpuTest, PLA)
TEST_F (CpuTest, PLA_16Bit)
TEST_F (CpuTest, PLB)
TEST_F (CpuTest, PLD)
TEST_F (CpuTest, PLP)
TEST_F (CpuTest, PLX)
TEST_F (CpuTest, PLX_16Bit)
TEST_F (CpuTest, PLY)
TEST_F (CpuTest, PLY_16Bit)
TEST_F (CpuTest, REP)
TEST_F (CpuTest, REP_16Bit)
TEST_F (CpuTest, PHA_PLA_Ok)
TEST_F (CpuTest, PHP_PLP_Ok)
TEST_F (CpuTest, PHA_PushAccumulator)
TEST_F (CpuTest, PHP_PushProcessorStatusRegister)
TEST_F (CpuTest, PHX_PushXRegister)
TEST_F (CpuTest, PHY_PushYRegister)
TEST_F (CpuTest, PHB_PushDataBankRegister)
TEST_F (CpuTest, PHD_PushDirectPageRegister)
TEST_F (CpuTest, PHK_PushProgramBankRegister)
TEST_F (CpuTest, PLA_PullAccumulator)
TEST_F (CpuTest, PLP_PullProcessorStatusRegister)
TEST_F (CpuTest, PLX_PullXRegister)
TEST_F (CpuTest, PLY_PullYRegister)
TEST_F (CpuTest, PLB_PullDataBankRegister)
TEST_F (CpuTest, PLD_PullDirectPageRegister)
TEST_F (CpuTest, SEP)
TEST_F (CpuTest, ROL_DirectPage)
TEST_F (CpuTest, ROL_Accumulator)
TEST_F (CpuTest, ROL_Absolute)
TEST_F (CpuTest, ROL_DirectPageIndexedX)
TEST_F (CpuTest, ROL_AbsoluteIndexedX)
TEST_F (CpuTest, ROR_DirectPage)
TEST_F (CpuTest, ROR_Accumulator)
TEST_F (CpuTest, ROR_Absolute)
TEST_F (CpuTest, ROR_DirectPageIndexedX)
TEST_F (CpuTest, ROR_AbsoluteIndexedX)
TEST_F (CpuTest, RTI)
TEST_F (CpuTest, RTL)
TEST_F (CpuTest, RTS)
TEST_F (CpuTest, SBC_DirectPageIndexedIndirectX)
TEST_F (CpuTest, SBC_StackRelative)
TEST_F (CpuTest, SBC_DirectPage)
TEST_F (CpuTest, SBC_DirectPageIndirectLong)
TEST_F (CpuTest, SBC_Immediate)
TEST_F (CpuTest, SBC_Absolute)
TEST_F (CpuTest, SBC_AbsoluteLong)
TEST_F (CpuTest, SBC_DirectPageIndirectIndexedY)
TEST_F (CpuTest, SBC_DirectPageIndirect)
TEST_F (CpuTest, SBC_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, SBC_DirectPageIndexedX)
TEST_F (CpuTest, SBC_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, SBC_AbsoluteIndexedY)
TEST_F (CpuTest, SBC_AbsoluteIndexedX)
TEST_F (CpuTest, SBC_AbsoluteLongIndexedX)
TEST_F (CpuTest, SEC)
TEST_F (CpuTest, SED)
TEST_F (CpuTest, SEI)
TEST_F (CpuTest, SEP_8Bit)
TEST_F (CpuTest, SEP_16Bit)
TEST_F (CpuTest, STA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, STA_StackRelative)
TEST_F (CpuTest, STA_DirectPage)
TEST_F (CpuTest, STA_DirectPageIndirectLong)
TEST_F (CpuTest, STA_Absolute)
TEST_F (CpuTest, STA_AbsoluteLong)
TEST_F (CpuTest, STA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, STA_DirectPageIndirect)
TEST_F (CpuTest, STA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, STA_DirectPageIndexedX)
TEST_F (CpuTest, STA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, STA_AbsoluteIndexedY)
TEST_F (CpuTest, STA_AbsoluteIndexedX)
TEST_F (CpuTest, STA_AbsoluteLongIndexedX)
TEST_F (CpuTest, STP)
TEST_F (CpuTest, STX_DirectPage)
TEST_F (CpuTest, STX_Absolute)
TEST_F (CpuTest, STX_DirectPageIndexedY)
TEST_F (CpuTest, STY_DirectPage)
TEST_F (CpuTest, STY_Absolute)
TEST_F (CpuTest, STY_DirectPageIndexedX)
TEST_F (CpuTest, STZ_DirectPage)
TEST_F (CpuTest, STZ_DirectPageIndexedX)
TEST_F (CpuTest, STZ_Absolute)
TEST_F (CpuTest, TAX)
TEST_F (CpuTest, TAY)
TEST_F (CpuTest, TCD)
TEST_F (CpuTest, TCS)
TEST_F (CpuTest, TDC)
TEST_F (CpuTest, TRB_DirectPage)
TEST_F (CpuTest, TRB_Absolute)
TEST_F (CpuTest, TSB_DirectPage)
TEST_F (CpuTest, TSB_Absolute)
TEST_F (CpuTest, TSC)
TEST_F (CpuTest, TSX)
TEST_F (CpuTest, TXA)
TEST_F (CpuTest, TXS)
TEST_F (CpuTest, TXY)
TEST_F (CpuTest, TYA)
TEST_F (CpuTest, TYX)
TEST_F (CpuTest, WAI)
TEST_F (CpuTest, WDM)
TEST_F (CpuTest, XBA)
TEST_F (CpuTest, XCESwitchToNativeMode)
TEST_F (CpuTest, XCESwitchToEmulationMode)
TEST_F (CpuTest, XCESwitchBackAndForth)
TEST_F (Spc700Test, MOV_A_Immediate)
TEST_F (Spc700Test, MOV_A_X)
TEST_F (Spc700Test, MOV_A_Y)
TEST_F (Spc700Test, MOV_A_dp)
TEST_F (Spc700Test, MOV_A_dp_plus_x)
TEST_F (Spc700Test, MOV_A_dp_indirect_plus_y)
TEST_F (Spc700Test, MOV_A_dp_plus_x_indirect)
TEST_F (Spc700Test, MOV_A_abs)
TEST_F (Spc700Test, MOV_Immediate)
TEST_F (Spc700Test, NOP_DoesNothing)
TEST_F (Spc700Test, ADC_A_Immediate)
TEST_F (Spc700Test, BEQ_BranchesIfZeroFlagSet)
TEST_F (Spc700Test, STA_Absolute)
TEST_F (Spc700Test, ExecuteADCWithImmediate)
TEST_F (Spc700Test, ExecuteBRA)
TEST_F (Spc700Test, ReadFromAudioRAM)
TEST_F (Spc700Test, WriteToAudioRAM)
TEST_F (Spc700Test, ExecuteANDWithImmediate)
TEST_F (Spc700Test, ExecuteORWithImmediate)
TEST_F (Spc700Test, ExecuteEORWithImmediate)
TEST_F (Spc700Test, ExecuteINC)
TEST_F (Spc700Test, ExecuteDEC)
TEST_F (Spc700Test, ExecuteBNEWhenNotEqual)
TEST_F (Spc700Test, ExecuteBNEWhenEqual)
TEST_F (Spc700Test, ExecuteBEQWhenEqual)
TEST_F (Spc700Test, ExecuteBEQWhenNotEqual)
TEST_F (Spc700Test, BootIplRomOk)
Function Documentation
TEST_F() [1/321]
yaze_test::emu_test::TEST_F (CpuTest , AsmParserTokenizerOk)
References yaze::app::emu::AsmParser::Tokenize().
TEST_F() [2/321]
yaze_test::emu_test::TEST_F (CpuTest , AsmParserSingleInstructionOk)
References yaze::app::emu::AsmParser::Parse(), and yaze::app::emu::AsmParser::Tokenize().
TEST_F() [3/321]
yaze_test::emu_test::TEST_F (CpuTest , CheckMemoryContents)
References yaze::app::emu::memory::Memory::ReadByte(), and yaze::app::emu::memory::MockMemory::SetMemoryContents().
TEST_F() [4/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_CheckCarryFlag)
TEST_F() [5/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_DirectPageIndexedIndirectX)
TEST_F() [6/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_StackRelative)
TEST_F() [7/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_DirectPage)
TEST_F() [8/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_DirectPageIndirectLong)
TEST_F() [9/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_Immediate_TwoPositiveNumbers)
TEST_F() [10/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_Immediate_PositiveAndNegativeNumbers)
TEST_F() [11/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_Absolute)
TEST_F() [12/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_AbsoluteLong)
TEST_F() [13/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_DirectPageIndirectIndexedY)
TEST_F() [14/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_DirectPageIndirect)
TEST_F() [15/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_StackRelativeIndirectIndexedY)
TEST_F() [16/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_DirectPageIndexedX)
TEST_F() [17/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_DirectPageIndirectLongIndexedY)
TEST_F() [18/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_AbsoluteIndexedY)
TEST_F() [19/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_AbsoluteIndexedX)
TEST_F() [20/321]
yaze_test::emu_test::TEST_F (CpuTest , ADC_AbsoluteLongIndexedX)
TEST_F() [21/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_DirectPageIndexedIndirectX)
TEST_F() [22/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_StackRelative)
TEST_F() [23/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_DirectPage)
TEST_F() [24/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_DirectPageIndirectLong)
TEST_F() [25/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_Immediate)
TEST_F() [26/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_Absolute_16BitMode)
TEST_F() [27/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_AbsoluteLong)
TEST_F() [28/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_DirectPageIndirectIndexedY)
TEST_F() [29/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_DirectPageIndirect)
TEST_F() [30/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_StackRelativeIndirectIndexedY)
TEST_F() [31/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_DirectPageIndexedX)
TEST_F() [32/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_DirectPageIndirectLongIndexedY)
TEST_F() [33/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_AbsoluteIndexedY)
TEST_F() [34/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_AbsoluteIndexedX)
TEST_F() [35/321]
yaze_test::emu_test::TEST_F (CpuTest , AND_AbsoluteLongIndexedX)
TEST_F() [36/321]
yaze_test::emu_test::TEST_F (CpuTest , ASL_DirectPage)
TEST_F() [37/321]
yaze_test::emu_test::TEST_F (CpuTest , ASL_Accumulator)
TEST_F() [38/321]
yaze_test::emu_test::TEST_F (CpuTest , ASL_Absolute)
TEST_F() [39/321]
yaze_test::emu_test::TEST_F (CpuTest , ASL_DirectPageIndexedX)
TEST_F() [40/321]
yaze_test::emu_test::TEST_F (CpuTest , ASL_AbsoluteIndexedX)
TEST_F() [41/321]
yaze_test::emu_test::TEST_F (CpuTest , BCC_WhenCarryFlagClear)
TEST_F() [42/321]
yaze_test::emu_test::TEST_F (CpuTest , BCC_WhenCarryFlagSet)
TEST_F() [43/321]
yaze_test::emu_test::TEST_F (CpuTest , BCS_WhenCarryFlagSet)
TEST_F() [44/321]
yaze_test::emu_test::TEST_F (CpuTest , BCS_WhenCarryFlagClear)
TEST_F() [45/321]
yaze_test::emu_test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagSet)
TEST_F() [46/321]
yaze_test::emu_test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagClear)
TEST_F() [47/321]
yaze_test::emu_test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagSet_OverflowFlagSet)
TEST_F() [48/321]
yaze_test::emu_test::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagClear_OverflowFlagSet)
TEST_F() [49/321]
yaze_test::emu_test::TEST_F (CpuTest , BIT_DirectPage)
TEST_F() [50/321]
yaze_test::emu_test::TEST_F (CpuTest , BIT_Absolute)
TEST_F() [51/321]
yaze_test::emu_test::TEST_F (CpuTest , BIT_DirectPageIndexedX)
TEST_F() [52/321]
yaze_test::emu_test::TEST_F (CpuTest , BIT_AbsoluteIndexedX)
TEST_F() [53/321]
yaze_test::emu_test::TEST_F (CpuTest , BIT_Immediate)
TEST_F() [54/321]
yaze_test::emu_test::TEST_F (CpuTest , BMI_BranchTaken)
TEST_F() [55/321]
yaze_test::emu_test::TEST_F (CpuTest , BMI_BranchNotTaken)
TEST_F() [56/321]
yaze_test::emu_test::TEST_F (CpuTest , BNE_BranchTaken)
TEST_F() [57/321]
yaze_test::emu_test::TEST_F (CpuTest , BNE_BranchNotTaken)
TEST_F() [58/321]
yaze_test::emu_test::TEST_F (CpuTest , BPL_BranchTaken)
TEST_F() [59/321]
yaze_test::emu_test::TEST_F (CpuTest , BPL_BranchNotTaken)
TEST_F() [60/321]
yaze_test::emu_test::TEST_F (CpuTest , BRA)
TEST_F() [61/321]
yaze_test::emu_test::TEST_F (CpuTest , BRK)
TEST_F() [62/321]
yaze_test::emu_test::TEST_F (CpuTest , BRL)
TEST_F() [63/321]
yaze_test::emu_test::TEST_F (CpuTest , BVC_BranchTaken)
TEST_F() [64/321]
yaze_test::emu_test::TEST_F (CpuTest , BVS_BranchTaken)
TEST_F() [65/321]
yaze_test::emu_test::TEST_F (CpuTest , CLC)
TEST_F() [66/321]
yaze_test::emu_test::TEST_F (CpuTest , CLD)
TEST_F() [67/321]
yaze_test::emu_test::TEST_F (CpuTest , CLI)
TEST_F() [68/321]
yaze_test::emu_test::TEST_F (CpuTest , CLV)
TEST_F() [69/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_DirectPageIndexedIndirectX)
TEST_F() [70/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_StackRelative)
TEST_F() [71/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_DirectPage)
TEST_F() [72/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_DirectPageIndirectLong)
TEST_F() [73/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_Immediate_8Bit)
TEST_F() [74/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_Absolute_16Bit)
TEST_F() [75/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_AbsoluteLong)
TEST_F() [76/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_DirectPageIndirect)
TEST_F() [77/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_StackRelativeIndirectIndexedY)
TEST_F() [78/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_DirectPageIndexedX)
TEST_F() [79/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_DirectPageIndirectLongIndexedY)
TEST_F() [80/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_AbsoluteIndexedY)
TEST_F() [81/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_AbsoluteIndexedX)
TEST_F() [82/321]
yaze_test::emu_test::TEST_F (CpuTest , CMP_AbsoluteLongIndexedX)
TEST_F() [83/321]
yaze_test::emu_test::TEST_F (CpuTest , COP)
Todo
FIX COP TEST
TEST_F() [84/321]
yaze_test::emu_test::TEST_F (CpuTest , CPX_Immediate_ZeroFlagSet)
TEST_F() [85/321]
yaze_test::emu_test::TEST_F (CpuTest , CPX_Immediate_NegativeFlagSet)
TEST_F() [86/321]
yaze_test::emu_test::TEST_F (CpuTest , CPX_DirectPage)
TEST_F() [87/321]
yaze_test::emu_test::TEST_F (CpuTest , CPX_Absolute)
TEST_F() [88/321]
yaze_test::emu_test::TEST_F (CpuTest , CPY_Immediate_ZeroFlagSet)
TEST_F() [89/321]
yaze_test::emu_test::TEST_F (CpuTest , CPY_Immediate_NegativeFlagSet)
TEST_F() [90/321]
yaze_test::emu_test::TEST_F (CpuTest , CPY_DirectPage)
TEST_F() [91/321]
yaze_test::emu_test::TEST_F (CpuTest , CPY_Absolute)
TEST_F() [92/321]
yaze_test::emu_test::TEST_F (CpuTest , DEC_Accumulator)
TEST_F() [93/321]
yaze_test::emu_test::TEST_F (CpuTest , DEC_DirectPage)
TEST_F() [94/321]
yaze_test::emu_test::TEST_F (CpuTest , DEC_Absolute)
TEST_F() [95/321]
yaze_test::emu_test::TEST_F (CpuTest , DEC_DirectPageIndexedX)
TEST_F() [96/321]
yaze_test::emu_test::TEST_F (CpuTest , DEC_AbsoluteIndexedX)
TEST_F() [97/321]
yaze_test::emu_test::TEST_F (CpuTest , DEX)
TEST_F() [98/321]
yaze_test::emu_test::TEST_F (CpuTest , DEY)
TEST_F() [99/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_DirectPageIndexedIndirectX)
TEST_F() [100/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_StackRelative)
TEST_F() [101/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_DirectPage)
TEST_F() [102/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_DirectPageIndirectLong)
TEST_F() [103/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_Immediate_8bit)
TEST_F() [104/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_Absolute)
TEST_F() [105/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_AbsoluteLong)
TEST_F() [106/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_DirectPageIndirectIndexedY)
TEST_F() [107/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_DirectPageIndirect)
TEST_F() [108/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_StackRelativeIndirectIndexedY)
TEST_F() [109/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_DirectPageIndexedX)
TEST_F() [110/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_DirectPageIndirectLongIndexedY)
TEST_F() [111/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_AbsoluteIndexedY)
TEST_F() [112/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_AbsoluteIndexedX)
TEST_F() [113/321]
yaze_test::emu_test::TEST_F (CpuTest , EOR_AbsoluteLongIndexedX)
TEST_F() [114/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_Accumulator)
TEST_F() [115/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_DirectPage_8bit)
TEST_F() [116/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_Absolute_16bit)
TEST_F() [117/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_DirectPage_ZeroResult_8bit)
TEST_F() [118/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_Absolute_ZeroResult_16bit)
TEST_F() [119/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_DirectPage_8bit_Overflow)
TEST_F() [120/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_DirectPageIndexedX_8bit)
TEST_F() [121/321]
yaze_test::emu_test::TEST_F (CpuTest , INC_AbsoluteIndexedX_16bit)
TEST_F() [122/321]
yaze_test::emu_test::TEST_F (CpuTest , INX)
TEST_F() [123/321]
yaze_test::emu_test::TEST_F (CpuTest , INY)
TEST_F() [124/321]
yaze_test::emu_test::TEST_F (CpuTest , JMP_Absolute)
TEST_F() [125/321]
yaze_test::emu_test::TEST_F (CpuTest , JMP_Indirect)
TEST_F() [126/321]
yaze_test::emu_test::TEST_F (CpuTest , JML_AbsoluteLong)
TEST_F() [127/321]
yaze_test::emu_test::TEST_F (CpuTest , JMP_AbsoluteIndexedIndirectX)
TEST_F() [128/321]
yaze_test::emu_test::TEST_F (CpuTest , JMP_AbsoluteIndirectLong)
TEST_F() [129/321]
yaze_test::emu_test::TEST_F (CpuTest , JSR_Absolute)
TEST_F() [130/321]
yaze_test::emu_test::TEST_F (CpuTest , JSL_AbsoluteLong)
TEST_F() [131/321]
yaze_test::emu_test::TEST_F (CpuTest , JSL_AbsoluteIndexedIndirect)
TEST_F() [132/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_DirectPageIndexedIndirectX)
TEST_F() [133/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_StackRelative)
TEST_F() [134/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_DirectPage)
TEST_F() [135/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_DirectPageIndirectLong)
TEST_F() [136/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_Immediate_8bit)
TEST_F() [137/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_Immediate_16bit)
TEST_F() [138/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_Absolute)
TEST_F() [139/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_AbsoluteLong)
TEST_F() [140/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_DirectPageIndirectIndexedY)
TEST_F() [141/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_DirectPageIndirect)
TEST_F() [142/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_StackRelativeIndirectIndexedY)
TEST_F() [143/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_DirectPageIndexedX)
TEST_F() [144/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_DirectPageIndirectLongIndexedY)
TEST_F() [145/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_AbsoluteIndexedY)
TEST_F() [146/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_AbsoluteIndexedX)
TEST_F() [147/321]
yaze_test::emu_test::TEST_F (CpuTest , LDA_AbsoluteLongIndexedX)
TEST_F() [148/321]
yaze_test::emu_test::TEST_F (CpuTest , LDX_Immediate)
TEST_F() [149/321]
yaze_test::emu_test::TEST_F (CpuTest , LDX_DirectPage)
TEST_F() [150/321]
yaze_test::emu_test::TEST_F (CpuTest , LDX_Absolute)
TEST_F() [151/321]
yaze_test::emu_test::TEST_F (CpuTest , LDX_DirectPageIndexedY)
TEST_F() [152/321]
yaze_test::emu_test::TEST_F (CpuTest , LDX_AbsoluteIndexedY)
TEST_F() [153/321]
yaze_test::emu_test::TEST_F (CpuTest , LDY_Immediate)
TEST_F() [154/321]
yaze_test::emu_test::TEST_F (CpuTest , LDY_DirectPage)
TEST_F() [155/321]
yaze_test::emu_test::TEST_F (CpuTest , LDY_Absolute)
TEST_F() [156/321]
yaze_test::emu_test::TEST_F (CpuTest , LDY_DirectPageIndexedX)
TEST_F() [157/321]
yaze_test::emu_test::TEST_F (CpuTest , LDY_AbsoluteIndexedX)
TEST_F() [158/321]
yaze_test::emu_test::TEST_F (CpuTest , LSR_DirectPage)
TEST_F() [159/321]
yaze_test::emu_test::TEST_F (CpuTest , LSR_Accumulator)
TEST_F() [160/321]
yaze_test::emu_test::TEST_F (CpuTest , LSR_Absolute)
TEST_F() [161/321]
yaze_test::emu_test::TEST_F (CpuTest , LSR_DirectPageIndexedX)
TEST_F() [162/321]
yaze_test::emu_test::TEST_F (CpuTest , LSR_AbsoluteIndexedX)
TEST_F() [163/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_DirectPageIndexedIndirectX)
TEST_F() [164/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_StackRelative)
TEST_F() [165/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_DirectPage)
TEST_F() [166/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_DirectPageIndirectLong)
TEST_F() [167/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_Immediate)
TEST_F() [168/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_Absolute)
TEST_F() [169/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_AbsoluteLong)
TEST_F() [170/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_DirectPageIndirectIndexedY)
TEST_F() [171/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_DirectPageIndirect)
TEST_F() [172/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_StackRelativeIndirectIndexedY)
TEST_F() [173/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_DirectPageIndexedX)
TEST_F() [174/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_DirectPageIndirectLongIndexedY)
TEST_F() [175/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_AbsoluteIndexedY)
TEST_F() [176/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_AbsoluteIndexedX)
TEST_F() [177/321]
yaze_test::emu_test::TEST_F (CpuTest , ORA_AbsoluteLongIndexedX)
TEST_F() [178/321]
yaze_test::emu_test::TEST_F (CpuTest , PEA)
TEST_F() [179/321]
yaze_test::emu_test::TEST_F (CpuTest , PEI)
TEST_F() [180/321]
yaze_test::emu_test::TEST_F (CpuTest , PER)
TEST_F() [181/321]
yaze_test::emu_test::TEST_F (CpuTest , PHD)
TEST_F() [182/321]
yaze_test::emu_test::TEST_F (CpuTest , PHK)
TEST_F() [183/321]
yaze_test::emu_test::TEST_F (CpuTest , PHP)
TEST_F() [184/321]
yaze_test::emu_test::TEST_F (CpuTest , PHX)
TEST_F() [185/321]
yaze_test::emu_test::TEST_F (CpuTest , PHY)
TEST_F() [186/321]
yaze_test::emu_test::TEST_F (CpuTest , PHB)
TEST_F() [187/321]
yaze_test::emu_test::TEST_F (CpuTest , PHA)
TEST_F() [188/321]
yaze_test::emu_test::TEST_F (CpuTest , PHA_16Bit)
TEST_F() [189/321]
yaze_test::emu_test::TEST_F (CpuTest , PLA)
TEST_F() [190/321]
yaze_test::emu_test::TEST_F (CpuTest , PLA_16Bit)
TEST_F() [191/321]
yaze_test::emu_test::TEST_F (CpuTest , PLB)
TEST_F() [192/321]
yaze_test::emu_test::TEST_F (CpuTest , PLD)
TEST_F() [193/321]
yaze_test::emu_test::TEST_F (CpuTest , PLP)
TEST_F() [194/321]
yaze_test::emu_test::TEST_F (CpuTest , PLX)
TEST_F() [195/321]
yaze_test::emu_test::TEST_F (CpuTest , PLX_16Bit)
TEST_F() [196/321]
yaze_test::emu_test::TEST_F (CpuTest , PLY)
TEST_F() [197/321]
yaze_test::emu_test::TEST_F (CpuTest , PLY_16Bit)
TEST_F() [198/321]
yaze_test::emu_test::TEST_F (CpuTest , REP)
TEST_F() [199/321]
yaze_test::emu_test::TEST_F (CpuTest , REP_16Bit)
TEST_F() [200/321]
yaze_test::emu_test::TEST_F (CpuTest , PHA_PLA_Ok)
TEST_F() [201/321]
yaze_test::emu_test::TEST_F (CpuTest , PHP_PLP_Ok)
TEST_F() [202/321]
yaze_test::emu_test::TEST_F (CpuTest , PHA_PushAccumulator)
TEST_F() [203/321]
yaze_test::emu_test::TEST_F (CpuTest , PHP_PushProcessorStatusRegister)
TEST_F() [204/321]
yaze_test::emu_test::TEST_F (CpuTest , PHX_PushXRegister)
TEST_F() [205/321]
yaze_test::emu_test::TEST_F (CpuTest , PHY_PushYRegister)
TEST_F() [206/321]
yaze_test::emu_test::TEST_F (CpuTest , PHB_PushDataBankRegister)
TEST_F() [207/321]
yaze_test::emu_test::TEST_F (CpuTest , PHD_PushDirectPageRegister)
TEST_F() [208/321]
yaze_test::emu_test::TEST_F (CpuTest , PHK_PushProgramBankRegister)
TEST_F() [209/321]
yaze_test::emu_test::TEST_F (CpuTest , PLA_PullAccumulator)
TEST_F() [210/321]
yaze_test::emu_test::TEST_F (CpuTest , PLP_PullProcessorStatusRegister)
TEST_F() [211/321]
yaze_test::emu_test::TEST_F (CpuTest , PLX_PullXRegister)
TEST_F() [212/321]
yaze_test::emu_test::TEST_F (CpuTest , PLY_PullYRegister)
TEST_F() [213/321]
yaze_test::emu_test::TEST_F (CpuTest , PLB_PullDataBankRegister)
TEST_F() [214/321]
yaze_test::emu_test::TEST_F (CpuTest , PLD_PullDirectPageRegister)
TEST_F() [215/321]
yaze_test::emu_test::TEST_F (CpuTest , SEP)
TEST_F() [216/321]
yaze_test::emu_test::TEST_F (CpuTest , ROL_DirectPage)
TEST_F() [217/321]
yaze_test::emu_test::TEST_F (CpuTest , ROL_Accumulator)
TEST_F() [218/321]
yaze_test::emu_test::TEST_F (CpuTest , ROL_Absolute)
TEST_F() [219/321]
yaze_test::emu_test::TEST_F (CpuTest , ROL_DirectPageIndexedX)
TEST_F() [220/321]
yaze_test::emu_test::TEST_F (CpuTest , ROL_AbsoluteIndexedX)
TEST_F() [221/321]
yaze_test::emu_test::TEST_F (CpuTest , ROR_DirectPage)
TEST_F() [222/321]
yaze_test::emu_test::TEST_F (CpuTest , ROR_Accumulator)
TEST_F() [223/321]
yaze_test::emu_test::TEST_F (CpuTest , ROR_Absolute)
TEST_F() [224/321]
yaze_test::emu_test::TEST_F (CpuTest , ROR_DirectPageIndexedX)
TEST_F() [225/321]
yaze_test::emu_test::TEST_F (CpuTest , ROR_AbsoluteIndexedX)
TEST_F() [226/321]
yaze_test::emu_test::TEST_F (CpuTest , RTI)
TEST_F() [227/321]
yaze_test::emu_test::TEST_F (CpuTest , RTL)
TEST_F() [228/321]
yaze_test::emu_test::TEST_F (CpuTest , RTS)
TEST_F() [229/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_DirectPageIndexedIndirectX)
TEST_F() [230/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_StackRelative)
TEST_F() [231/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_DirectPage)
TEST_F() [232/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_DirectPageIndirectLong)
TEST_F() [233/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_Immediate)
TEST_F() [234/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_Absolute)
TEST_F() [235/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_AbsoluteLong)
TEST_F() [236/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_DirectPageIndirectIndexedY)
TEST_F() [237/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_DirectPageIndirect)
TEST_F() [238/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_StackRelativeIndirectIndexedY)
TEST_F() [239/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_DirectPageIndexedX)
TEST_F() [240/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_DirectPageIndirectLongIndexedY)
TEST_F() [241/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_AbsoluteIndexedY)
TEST_F() [242/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_AbsoluteIndexedX)
TEST_F() [243/321]
yaze_test::emu_test::TEST_F (CpuTest , SBC_AbsoluteLongIndexedX)
TEST_F() [244/321]
yaze_test::emu_test::TEST_F (CpuTest , SEC)
TEST_F() [245/321]
yaze_test::emu_test::TEST_F (CpuTest , SED)
TEST_F() [246/321]
yaze_test::emu_test::TEST_F (CpuTest , SEI)
TEST_F() [247/321]
yaze_test::emu_test::TEST_F (CpuTest , SEP_8Bit)
TEST_F() [248/321]
yaze_test::emu_test::TEST_F (CpuTest , SEP_16Bit)
TEST_F() [249/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_DirectPageIndexedIndirectX)
TEST_F() [250/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_StackRelative)
TEST_F() [251/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_DirectPage)
TEST_F() [252/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_DirectPageIndirectLong)
TEST_F() [253/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_Absolute)
TEST_F() [254/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_AbsoluteLong)
TEST_F() [255/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_DirectPageIndirectIndexedY)
TEST_F() [256/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_DirectPageIndirect)
TEST_F() [257/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_StackRelativeIndirectIndexedY)
TEST_F() [258/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_DirectPageIndexedX)
TEST_F() [259/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_DirectPageIndirectLongIndexedY)
TEST_F() [260/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_AbsoluteIndexedY)
TEST_F() [261/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_AbsoluteIndexedX)
TEST_F() [262/321]
yaze_test::emu_test::TEST_F (CpuTest , STA_AbsoluteLongIndexedX)
TEST_F() [263/321]
yaze_test::emu_test::TEST_F (CpuTest , STP)
TEST_F() [264/321]
yaze_test::emu_test::TEST_F (CpuTest , STX_DirectPage)
TEST_F() [265/321]
yaze_test::emu_test::TEST_F (CpuTest , STX_Absolute)
TEST_F() [266/321]
yaze_test::emu_test::TEST_F (CpuTest , STX_DirectPageIndexedY)
TEST_F() [267/321]
yaze_test::emu_test::TEST_F (CpuTest , STY_DirectPage)
TEST_F() [268/321]
yaze_test::emu_test::TEST_F (CpuTest , STY_Absolute)
TEST_F() [269/321]
yaze_test::emu_test::TEST_F (CpuTest , STY_DirectPageIndexedX)
TEST_F() [270/321]
yaze_test::emu_test::TEST_F (CpuTest , STZ_DirectPage)
TEST_F() [271/321]
yaze_test::emu_test::TEST_F (CpuTest , STZ_DirectPageIndexedX)
TEST_F() [272/321]
yaze_test::emu_test::TEST_F (CpuTest , STZ_Absolute)
TEST_F() [273/321]
yaze_test::emu_test::TEST_F (CpuTest , TAX)
TEST_F() [274/321]
yaze_test::emu_test::TEST_F (CpuTest , TAY)
TEST_F() [275/321]
yaze_test::emu_test::TEST_F (CpuTest , TCD)
TEST_F() [276/321]
yaze_test::emu_test::TEST_F (CpuTest , TCS)
TEST_F() [277/321]
yaze_test::emu_test::TEST_F (CpuTest , TDC)
TEST_F() [278/321]
yaze_test::emu_test::TEST_F (CpuTest , TRB_DirectPage)
TEST_F() [279/321]
yaze_test::emu_test::TEST_F (CpuTest , TRB_Absolute)
TEST_F() [280/321]
yaze_test::emu_test::TEST_F (CpuTest , TSB_DirectPage)
TEST_F() [281/321]
yaze_test::emu_test::TEST_F (CpuTest , TSB_Absolute)
TEST_F() [282/321]
yaze_test::emu_test::TEST_F (CpuTest , TSC)
TEST_F() [283/321]
yaze_test::emu_test::TEST_F (CpuTest , TSX)
TEST_F() [284/321]
yaze_test::emu_test::TEST_F (CpuTest , TXA)
TEST_F() [285/321]
yaze_test::emu_test::TEST_F (CpuTest , TXS)
TEST_F() [286/321]
yaze_test::emu_test::TEST_F (CpuTest , TXY)
TEST_F() [287/321]
yaze_test::emu_test::TEST_F (CpuTest , TYA)
TEST_F() [288/321]
yaze_test::emu_test::TEST_F (CpuTest , TYX)
TEST_F() [289/321]
yaze_test::emu_test::TEST_F (CpuTest , WAI)
TEST_F() [290/321]
yaze_test::emu_test::TEST_F (CpuTest , WDM)
TEST_F() [291/321]
yaze_test::emu_test::TEST_F (CpuTest , XBA)
TEST_F() [292/321]
yaze_test::emu_test::TEST_F (CpuTest , XCESwitchToNativeMode)
TEST_F() [293/321]
yaze_test::emu_test::TEST_F (CpuTest , XCESwitchToEmulationMode)
TEST_F() [294/321]
yaze_test::emu_test::TEST_F (CpuTest , XCESwitchBackAndForth)
TEST_F() [295/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_Immediate)
TEST_F() [296/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_X)
TEST_F() [297/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_Y)
TEST_F() [298/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_dp)
TEST_F() [299/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_dp_plus_x)
TEST_F() [300/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_dp_indirect_plus_y)
TEST_F() [301/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_dp_plus_x_indirect)
TEST_F() [302/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_A_abs)
TEST_F() [303/321]
yaze_test::emu_test::TEST_F (Spc700Test , MOV_Immediate)
TEST_F() [304/321]
yaze_test::emu_test::TEST_F (Spc700Test , NOP_DoesNothing)
TEST_F() [305/321]
yaze_test::emu_test::TEST_F (Spc700Test , ADC_A_Immediate)
TEST_F() [306/321]
yaze_test::emu_test::TEST_F (Spc700Test , BEQ_BranchesIfZeroFlagSet)
TEST_F() [307/321]
yaze_test::emu_test::TEST_F (Spc700Test , STA_Absolute)
TEST_F() [308/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteADCWithImmediate)
TEST_F() [309/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteBRA)
TEST_F() [310/321]
yaze_test::emu_test::TEST_F (Spc700Test , ReadFromAudioRAM)
TEST_F() [311/321]
yaze_test::emu_test::TEST_F (Spc700Test , WriteToAudioRAM)
TEST_F() [312/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteANDWithImmediate)
TEST_F() [313/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteORWithImmediate)
TEST_F() [314/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteEORWithImmediate)
TEST_F() [315/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteINC)
TEST_F() [316/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteDEC)
TEST_F() [317/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteBNEWhenNotEqual)
TEST_F() [318/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteBNEWhenEqual)
TEST_F() [319/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteBEQWhenEqual)
TEST_F() [320/321]
yaze_test::emu_test::TEST_F (Spc700Test , ExecuteBEQWhenNotEqual)
TEST_F() [321/321]
yaze_test::emu_test::TEST_F (Spc700Test , BootIplRomOk)