yaze: yaze::test::message_system Namespace Reference
yaze::test::message_system Namespace Reference
Classes
class MessageDispatcherTest
class TestFilter
class TestListener
class TestProtocol
Functions
TEST_F (MessageDispatcherTest, RegisterAndSendMessage)
TEST_F (MessageDispatcherTest, UnregisterListener)
TEST_F (MessageDispatcherTest, MultipleListeners)
TEST_F (MessageDispatcherTest, ProtocolBasedHandling)
TEST_F (MessageDispatcherTest, FilteredMessageHandling)
Function Documentation
TEST_F() [1/5]
yaze::test::message_system::TEST_F (MessageDispatcherTest , RegisterAndSendMessage)
Definition at line 68 of file message_test.cc.
References yaze::app::core::MessageDispatcher::RegisterListener(), and yaze::app::core::MessageDispatcher::SendMessage().
TEST_F() [2/5]
yaze::test::message_system::TEST_F (MessageDispatcherTest , UnregisterListener)
Definition at line 80 of file message_test.cc.
References yaze::app::core::MessageDispatcher::RegisterListener(), yaze::app::core::MessageDispatcher::SendMessage(), and yaze::app::core::MessageDispatcher::UnregisterListener().
TEST_F() [3/5]
yaze::test::message_system::TEST_F (MessageDispatcherTest , MultipleListeners)
Definition at line 92 of file message_test.cc.
References yaze::app::core::MessageDispatcher::RegisterListener(), and yaze::app::core::MessageDispatcher::SendMessage().
TEST_F() [4/5]
yaze::test::message_system::TEST_F (MessageDispatcherTest , ProtocolBasedHandling)
Definition at line 107 of file message_test.cc.
References yaze::app::core::MessageDispatcher::DispatchMessage(), yaze::app::core::MessageDispatcher::RegisterListener(), and yaze::app::core::MessageDispatcher::RegisterProtocol().
TEST_F() [5/5]
yaze::test::message_system::TEST_F (MessageDispatcherTest , FilteredMessageHandling)
Definition at line 120 of file message_test.cc.
References yaze::app::core::MessageDispatcher::DispatchMessage(), and yaze::app::core::MessageDispatcher::RegisterFilteredListener().