yaze: yaze::app::gfx Namespace Reference
yaze::app::gfx Namespace Reference
Contains classes for handling graphical data.
Namespaces
namespace anonymous_namespace{bitmap.cc}
namespace lc_lz2
Contains the LC_LZ2 compression algorithm.
namespace palette_group_internal
Internal functions for loading palettes by group.
namespace scad_format
Loading from prototype SCAD format.
Classes
class Bitmap
Represents a bitmap image.
class BitmapManager
Hash map container of shared pointers to Bitmaps.
class OamTile
Object Attribute Memory tile abstraction container.
struct PaletteGroup
Represents a group of palettes.
struct PaletteGroupMap
Represents a mapping of palette groups.
struct Paletteset
Represents a set of palettes used in a SNES graphics system.
class SnesColor
SNES Color container.
class SnesPalette
Represents a palette of colors for the Super Nintendo Entertainment System (SNES).
class Tile16
Tile composition of four 8x8 tiles.
class Tile32
Tile composition of four 16x16 tiles.
struct tile8
class TileInfo
SNES 16-bit tile metadata container.
class Tilesheet
Represents a tilesheet, which is a collection of tiles stored in a bitmap.
Typedefs
using BitmapTable = std::unordered_map<int, gfx::Bitmap>
using tile8 = struct tile8
Enumerations
enum BitmapFormat { kIndexed = 0 , k2bpp = 1 , k4bpp = 2 , k8bpp = 3 }
enum PaletteCategory {
kSword , kShield , kClothes , kWorldColors ,
kAreaColors , kGlobalSprites , kSpritesAux1 , kSpritesAux2 ,
kSpritesAux3 , kDungeons , kWorldMap , kDungeonMap ,
kTriforce , kCrystal
}
enum class TileType { Tile8 , Tile16 }
Functions
bool ConvertSurfaceToPNG (SDL_Surface *surface, std::vector< uint8_t > &buffer)
Convert SDL_Surface to PNG image data.
void ConvertPngToSurface (const std::vector< uint8_t > &png_data, SDL_Surface **outSurface)
Convert PNG image data to SDL_Surface.
snes_color ConvertSNEStoRGB (uint16_t color_snes)
uint16_t ConvertRGBtoSNES (const snes_color &color)
uint16_t ConvertRGBtoSNES (const ImVec4 &color)
SnesColor ReadColorFromRom (int offset, const uint8_t *rom)
std::vector< snes_color > Extract (const char *data, unsigned int offset, unsigned int palette_size)
std::vector< char > Convert (const std::vector< snes_color > &palette)
SnesColor GetCgxColor (uint16_t color)
std::vector< SnesColor > GetColFileData (uint8_t *data)
uint32_t GetPaletteAddress (const std::string &group_name, size_t palette_index, size_t color_index)
SnesPalette ReadPaletteFromRom (int offset, int num_colors, const uchar *rom)
std::array< float, 4 > ToFloatArray (const SnesColor &color)
absl::StatusOr< PaletteGroup > CreatePaletteGroupFromColFile (std::vector< SnesColor > &palette_rows)
absl::StatusOr< PaletteGroup > CreatePaletteGroupFromLargePalette (SnesPalette &palette)
absl::Status LoadAllPalettes (const Bytes &rom_data, PaletteGroupMap &groups)
Loads all the palettes for the game.
SnesPalette ReadPaletteFromRom (int offset, int num_colors, const uint8_t *rom)
tile8 UnpackBppTile (const Bytes &data, const uint32_t offset, const uint32_t bpp)
Bytes PackBppTile (const tile8 &tile, const uint32_t bpp)
std::vector< uint8_t > ConvertBpp (const std::vector< uint8_t > &tiles, uint32_t from_bpp, uint32_t to_bpp)
std::vector< uint8_t > Convert3bppTo4bpp (const std::vector< uint8_t > &tiles)
std::vector< uint8_t > Convert4bppTo3bpp (const std::vector< uint8_t > &tiles)
Bytes SnesTo8bppSheet (const Bytes &sheet, int bpp)
Bytes Bpp8SnesToIndexed (Bytes data, uint64_t bpp)
uint16_t TileInfoToWord (TileInfo tile_info)
TileInfo WordToTileInfo (uint16_t word)
uint16_t TileInfoToShort (TileInfo tile_info)
TileInfo GetTilesInfo (uint16_t tile)
absl::StatusOr< Tilesheet > CreateTilesheetFromGraphicsBuffer (const uint8_t *graphics_buffer, int width, int height, TileType tile_type, int sheet_id)
Variables
constexpr Uint32 SNES_PIXELFORMAT_INDEXED
constexpr Uint32 SNES_PIXELFORMAT_2BPP
constexpr Uint32 SNES_PIXELFORMAT_4BPP
constexpr Uint32 SNES_PIXELFORMAT_8BPP
constexpr uint16_t SNES_RED_MASK = 32
constexpr uint16_t SNES_GREEN_MASK = 32
constexpr uint16_t SNES_BLUE_MASK = 32
constexpr uint16_t SNES_GREEN_SHIFT = 32
constexpr uint16_t SNES_BLUE_SHIFT = 1024
const absl::flat_hash_map< std::string, uint32_t > kPaletteGroupAddressMap
const absl::flat_hash_map< std::string, uint32_t > kPaletteGroupColorCounts
constexpr int kNumPalettes = 14
constexpr const char * kPaletteGroupAddressesKeys []
constexpr int kOverworldPaletteMain = 0xDE6C8
constexpr int kOverworldPaletteAux = 0xDE86C
constexpr int kOverworldPaletteAnimated = 0xDE604
constexpr int kGlobalSpritesLW = 0xDD218
constexpr int globalSpritePalettesDW = 0xDD290
constexpr int kArmorPalettes = 0xDD308
constexpr int kSpritesPalettesAux1 = 0xDD39E
constexpr int kSpritesPalettesAux2 = 0xDD446
constexpr int kSpritesPalettesAux3 = 0xDD4E0
constexpr int kSwordPalettes = 0xDD630
constexpr int kShieldPalettes = 0xDD648
constexpr int kHudPalettes = 0xDD660
constexpr int dungeonMapPalettes = 0xDD70A
constexpr int kDungeonMainPalettes = 0xDD734
constexpr int dungeonMapBgPalettes = 0xDE544
constexpr int kHardcodedGrassLW = 0x5FEA9
constexpr int hardcodedGrassDW = 0x05FEB3
constexpr int hardcodedGrassSpecial = 0x75640
constexpr int kOverworldMiniMapPalettes = 0x55B27
constexpr int kTriforcePalette = 0x64425
constexpr int crystalPalette = 0xF4CD3
constexpr int customAreaSpecificBGPalette = 0x140000
constexpr int customAreaSpecificBGASM = 0x140150
constexpr int customAreaSpecificBGEnabled = 0x140140
constexpr ushort TilePriorityBit = 0x2000
constexpr ushort TileHFlipBit = 0x4000
constexpr ushort TileVFlipBit = 0x8000
constexpr ushort TileNameMask = 0x03FF
constexpr uint8_t kGraphicsBitmap [8]
Detailed Description
Contains classes for handling graphical data.
Typedef Documentation
BitmapTable
using yaze::app::gfx::BitmapTable = std::unordered_map<int, gfx::Bitmap>
Definition at line 218 of file bitmap.h.
tile8
using yaze::app::gfx::tile8 = struct tile8
Definition at line 25 of file snes_tile.h.
Enumeration Type Documentation
BitmapFormat
enum yaze::app::gfx::BitmapFormat
Enumerator
kIndexed
k2bpp
k4bpp
k8bpp
Definition at line 42 of file bitmap.h.
PaletteCategory
enum yaze::app::gfx::PaletteCategory
Enumerator
kSword
kShield
kClothes
kWorldColors
kAreaColors
kGlobalSprites
kSpritesAux1
kSpritesAux2
kSpritesAux3
kDungeons
kWorldMap
kDungeonMap
kTriforce
kCrystal
Definition at line 27 of file snes_palette.h.
TileType
enum class yaze::app::gfx::TileType strong
Enumerator
Tile8
Tile16
Definition at line 16 of file tilesheet.h.
Function Documentation
ConvertSurfaceToPNG()
bool yaze::app::gfx::ConvertSurfaceToPNG (SDL_Surface * surface, std::vector< uint8_t > & buffer)
Convert SDL_Surface to PNG image data.
Definition at line 68 of file bitmap.cc.
Referenced by yaze::app::gfx::Bitmap::GetPngData().
ConvertPngToSurface()
void yaze::app::gfx::ConvertPngToSurface (const std::vector< uint8_t > & png_data, SDL_Surface ** outSurface)
Convert PNG image data to SDL_Surface.
Definition at line 140 of file bitmap.cc.
Referenced by yaze::app::gfx::Bitmap::LoadFromPngData().
ConvertSNEStoRGB()
snes_color yaze::app::gfx::ConvertSNEStoRGB (uint16_t color_snes)
Definition at line 20 of file snes_color.cc.
References snes_color::blue, snes_color::green, snes_color::red, SNES_BLUE_MASK, SNES_BLUE_SHIFT, SNES_GREEN_MASK, and SNES_RED_MASK.
Referenced by Extract(), yaze::app::gfx::SnesColor::set_snes(), yaze::app::gfx::SnesColor::SnesColor(), yaze::app::gfx::SnesPalette::SnesPalette(), and yaze::app::gfx::SnesPalette::SnesPalette().
ConvertRGBtoSNES() [1/2]
uint16_t yaze::app::gfx::ConvertRGBtoSNES (const snes_color & color)
Definition at line 34 of file snes_color.cc.
References snes_color::blue, snes_color::green, snes_color::red, SNES_BLUE_SHIFT, and SNES_GREEN_SHIFT.
Referenced by Convert(), ConvertRGBtoSNES(), yaze::app::editor::PaletteEditor::HandleColorPopup(), ReadPaletteFromRom(), yaze::app::gfx::SnesColor::set_rgb(), yaze::app::gfx::SnesColor::SnesColor(), yaze::app::gfx::SnesColor::SnesColor(), yaze::app::gui::SnesColorEdit4(), and yaze::app::gfx::SnesPalette::SnesPalette().
ConvertRGBtoSNES() [2/2]
uint16_t yaze::app::gfx::ConvertRGBtoSNES (const ImVec4 & color)
Definition at line 41 of file snes_color.cc.
References snes_color::blue, ConvertRGBtoSNES(), snes_color::green, and snes_color::red.
ReadColorFromRom()
SnesColor yaze::app::gfx::ReadColorFromRom (int offset, const uint8_t * rom)
Definition at line 49 of file snes_color.cc.
References snes_color::blue, snes_color::green, and snes_color::red.
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
Extract()
std::vector< snes_color > yaze::app::gfx::Extract (const char * data, unsigned int offset, unsigned int palette_size)
Definition at line 59 of file snes_color.cc.
References ConvertSNEStoRGB().
Convert()
std::vector< char > yaze::app::gfx::Convert (const std::vector< snes_color > & palette)
Definition at line 70 of file snes_color.cc.
References ConvertRGBtoSNES().
Referenced by yaze_test::gfx_test::TEST().
GetCgxColor()
SnesColor yaze::app::gfx::GetCgxColor (uint16_t color)
Definition at line 80 of file snes_color.cc.
References yaze::app::gfx::SnesColor::set_rgb().
Referenced by GetColFileData().
GetColFileData()
std::vector< SnesColor > yaze::app::gfx::GetColFileData (uint8_t * data)
Definition at line 90 of file snes_color.cc.
References GetCgxColor().
Referenced by yaze::app::editor::GraphicsEditor::DrawPaletteControls().
GetPaletteAddress()
uint32_t yaze::app::gfx::GetPaletteAddress (const std::string & group_name, size_t palette_index, size_t color_index)
Definition at line 210 of file snes_palette.cc.
References kPaletteGroupAddressMap, and kPaletteGroupColorCounts.
Referenced by yaze::app::Rom::SavePalette().
ReadPaletteFromRom() [1/2]
SnesPalette yaze::app::gfx::ReadPaletteFromRom (int offset, int num_colors, const uchar * rom)
Definition at line 304 of file snes_palette.cc.
References snes_color::blue, ConvertRGBtoSNES(), snes_color::green, and snes_color::red.
Referenced by yaze::app::gfx::palette_group_internal::Load3DObjectPalettes(), yaze::app::gfx::palette_group_internal::LoadArmorPalettes(), yaze::app::gfx::palette_group_internal::LoadDungeonMainPalettes(), yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes(), yaze::app::gfx::palette_group_internal::LoadHUDPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldAnimatedPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldMainPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldMiniMapPalettes(), yaze::app::gfx::palette_group_internal::LoadShieldPalettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux1Palettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux2Palettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux3Palettes(), and yaze::app::gfx::palette_group_internal::LoadSwordPalettes().
ToFloatArray()
std::array< float, 4 > yaze::app::gfx::ToFloatArray (const SnesColor & color)
Definition at line 325 of file snes_palette.cc.
References yaze::app::gfx::SnesColor::rgb().
Referenced by yaze::app::editor::PaletteEditor::HandleColorPopup().
CreatePaletteGroupFromColFile()
absl::StatusOr< PaletteGroup > yaze::app::gfx::CreatePaletteGroupFromColFile (std::vector< SnesColor > & palette_rows)
Definition at line 336 of file snes_palette.cc.
References yaze::app::gfx::SnesPalette::AddColor(), yaze::app::gfx::PaletteGroup::AddPalette(), and RETURN_IF_ERROR.
Referenced by yaze::app::editor::GraphicsEditor::DrawPaletteControls().
CreatePaletteGroupFromLargePalette()
absl::StatusOr< PaletteGroup > yaze::app::gfx::CreatePaletteGroupFromLargePalette (SnesPalette & palette)
Definition at line 351 of file snes_palette.cc.
References yaze::app::gfx::SnesPalette::AddColor(), yaze::app::gfx::PaletteGroup::AddPalette(), RETURN_IF_ERROR, and yaze::app::gfx::SnesPalette::size().
Referenced by yaze::app::editor::DungeonEditor::Initialize().
LoadAllPalettes()
absl::Status yaze::app::gfx::LoadAllPalettes (const Bytes & rom_data, PaletteGroupMap & groups)
Loads all the palettes for the game.
This function loads all the palettes for the game, including overworld, HUD, armor, swords, shields, sprites, dungeon, grass, and 3D object palettes. It also adds the loaded palettes to their respective palette groups.
Definition at line 371 of file snes_palette.cc.
References yaze::app::gfx::palette_group_internal::Load3DObjectPalettes(), yaze::app::gfx::palette_group_internal::LoadArmorPalettes(), yaze::app::gfx::palette_group_internal::LoadDungeonMainPalettes(), yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes(), yaze::app::gfx::palette_group_internal::LoadGrassColors(), yaze::app::gfx::palette_group_internal::LoadHUDPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldAnimatedPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldMainPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldMiniMapPalettes(), yaze::app::gfx::palette_group_internal::LoadShieldPalettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux1Palettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux2Palettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux3Palettes(), yaze::app::gfx::palette_group_internal::LoadSwordPalettes(), and RETURN_IF_ERROR.
Referenced by yaze::app::Rom::LoadFromFile(), and yaze::app::Rom::LoadFromPointer().
ReadPaletteFromRom() [2/2]
SnesPalette yaze::app::gfx::ReadPaletteFromRom (int offset, int num_colors, const uint8_t * rom)
UnpackBppTile()
tile8 yaze::app::gfx::UnpackBppTile (const Bytes & data, const uint32_t offset, const uint32_t bpp)
Definition at line 25 of file snes_tile.cc.
References yaze::app::gfx::tile8::data.
Referenced by ConvertBpp().
PackBppTile()
Bytes yaze::app::gfx::PackBppTile (const tile8 & tile, const uint32_t bpp)
Definition at line 82 of file snes_tile.cc.
References yaze::app::gfx::tile8::data.
Referenced by ConvertBpp().
ConvertBpp()
std::vector< uint8_t > yaze::app::gfx::ConvertBpp (const std::vector< uint8_t > & tiles, uint32_t from_bpp, uint32_t to_bpp)
Definition at line 129 of file snes_tile.cc.
References PackBppTile(), and UnpackBppTile().
Referenced by Convert3bppTo4bpp(), and Convert4bppTo3bpp().
Convert3bppTo4bpp()
std::vector< uint8_t > yaze::app::gfx::Convert3bppTo4bpp (const std::vector< uint8_t > & tiles)
Definition at line 143 of file snes_tile.cc.
References ConvertBpp().
Convert4bppTo3bpp()
std::vector< uint8_t > yaze::app::gfx::Convert4bppTo3bpp (const std::vector< uint8_t > & tiles)
Definition at line 147 of file snes_tile.cc.
References ConvertBpp().
Referenced by yaze::app::Rom::LoadLinkGraphics().
SnesTo8bppSheet()
Bytes yaze::app::gfx::SnesTo8bppSheet (const Bytes & sheet, int bpp)
Definition at line 151 of file snes_tile.cc.
References kGraphicsBitmap.
Referenced by yaze::app::editor::GraphicsEditor::DecompressImportData(), yaze::app::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::app::editor::MessageEditor::Initialize(), yaze::app::Rom::Load2BppGraphics(), yaze::app::Rom::LoadAllGraphicsData(), and yaze::app::Rom::LoadLinkGraphics().
Bpp8SnesToIndexed()
Bytes yaze::app::gfx::Bpp8SnesToIndexed (Bytes data, uint64_t bpp)
Definition at line 203 of file snes_tile.cc.
Referenced by yaze::app::gfx::scad_format::LoadCgx().
TileInfoToWord()
uint16_t yaze::app::gfx::TileInfoToWord (TileInfo tile_info)
Definition at line 304 of file snes_tile.cc.
References yaze::app::gfx::TileInfo::horizontal_mirror_, yaze::app::gfx::TileInfo::id_, yaze::app::gfx::TileInfo::over_, yaze::app::gfx::TileInfo::palette_, and yaze::app::gfx::TileInfo::vertical_mirror_.
Referenced by yaze::app::Rom::WriteTile16().
WordToTileInfo()
TileInfo yaze::app::gfx::WordToTileInfo (uint16_t word)
Definition at line 321 of file snes_tile.cc.
Referenced by yaze::app::editor::ScreenEditor::LoadDungeonMapTile16(), and yaze::app::Rom::ReadTile16().
TileInfoToShort()
uint16_t yaze::app::gfx::TileInfoToShort (TileInfo tile_info)
Definition at line 336 of file snes_tile.cc.
References yaze::app::gfx::TileInfo::horizontal_mirror_, yaze::app::gfx::TileInfo::id_, yaze::app::gfx::TileInfo::over_, yaze::app::gfx::TileInfo::palette_, TileHFlipBit, TileNameMask, TilePriorityBit, TileVFlipBit, and yaze::app::gfx::TileInfo::vertical_mirror_.
Referenced by yaze::app::gfx::scad_format::LoadScr().
GetTilesInfo()
TileInfo yaze::app::gfx::GetTilesInfo (uint16_t tile)
Definition at line 367 of file snes_tile.cc.
References TileHFlipBit, TileNameMask, TilePriorityBit, and TileVFlipBit.
Referenced by yaze::app::zelda3::overworld::Overworld::AssembleMap16Tiles(), yaze::app::zelda3::screen::Inventory::Create(), yaze::app::gfx::scad_format::DrawScrWithCgx(), and yaze::app::gfx::scad_format::LoadScr().
CreateTilesheetFromGraphicsBuffer()
absl::StatusOr< Tilesheet > yaze::app::gfx::CreateTilesheetFromGraphicsBuffer (const uint8_t * graphics_buffer, int width, int height, TileType tile_type, int sheet_id)
Definition at line 15 of file tilesheet.cc.
References yaze::app::gfx::Tilesheet::Init(), and yaze::app::gfx::Tilesheet::mutable_bitmap().
Variable Documentation
SNES_PIXELFORMAT_INDEXED
Uint32 yaze::app::gfx::SNES_PIXELFORMAT_INDEXED constexpr
Initial value:
=
    SDL_DEFINE_PIXELFORMAT(SDL_PIXELTYPE_INDEX8, 0, 0, 8, 1)
Definition at line 27 of file bitmap.h.
SNES_PIXELFORMAT_2BPP
Uint32 yaze::app::gfx::SNES_PIXELFORMAT_2BPP constexpr
Initial value:
= SDL_DEFINE_PIXELFORMAT(
    SDL_PIXELTYPE_INDEX8, 0,
    0, 2, 1)
Definition at line 30 of file bitmap.h.
Referenced by yaze::app::gfx::anonymous_namespace{bitmap.cc}::GetSnesPixelFormat().
SNES_PIXELFORMAT_4BPP
Uint32 yaze::app::gfx::SNES_PIXELFORMAT_4BPP constexpr
Initial value:
= SDL_DEFINE_PIXELFORMAT(
    SDL_PIXELTYPE_INDEX8, 0,
    0, 4, 1)
Definition at line 34 of file bitmap.h.
Referenced by yaze::app::gfx::anonymous_namespace{bitmap.cc}::GetSnesPixelFormat().
SNES_PIXELFORMAT_8BPP
Uint32 yaze::app::gfx::SNES_PIXELFORMAT_8BPP constexpr
Initial value:
= SDL_DEFINE_PIXELFORMAT(
    SDL_PIXELTYPE_INDEX8, 0,
    0, 8, 1)
Definition at line 38 of file bitmap.h.
Referenced by yaze::app::gfx::anonymous_namespace{bitmap.cc}::GetSnesPixelFormat().
SNES_RED_MASK
uint16_t yaze::app::gfx::SNES_RED_MASK = 32 constexpr
Definition at line 13 of file snes_color.cc.
Referenced by ConvertSNEStoRGB().
SNES_GREEN_MASK
uint16_t yaze::app::gfx::SNES_GREEN_MASK = 32 constexpr
Definition at line 14 of file snes_color.cc.
Referenced by ConvertSNEStoRGB().
SNES_BLUE_MASK
uint16_t yaze::app::gfx::SNES_BLUE_MASK = 32 constexpr
Definition at line 15 of file snes_color.cc.
Referenced by ConvertSNEStoRGB().
SNES_GREEN_SHIFT
uint16_t yaze::app::gfx::SNES_GREEN_SHIFT = 32 constexpr
Definition at line 17 of file snes_color.cc.
Referenced by ConvertRGBtoSNES().
SNES_BLUE_SHIFT
uint16_t yaze::app::gfx::SNES_BLUE_SHIFT = 1024 constexpr
Definition at line 18 of file snes_color.cc.
Referenced by ConvertRGBtoSNES(), and ConvertSNEStoRGB().
kPaletteGroupAddressMap
const absl::flat_hash_map<std::string, uint32_t> yaze::app::gfx::kPaletteGroupAddressMap
Initial value:
= {
    {"ow_main", kOverworldPaletteMain},
    {"ow_aux", kOverworldPaletteAux},
    {"ow_animated", kOverworldPaletteAnimated},
    {"hud", kHudPalettes},
    {"global_sprites", kGlobalSpritesLW},
    {"armors", kArmorPalettes},
    {"swords", kSwordPalettes},
    {"shields", kShieldPalettes},
    {"sprites_aux1", kSpritesPalettesAux1},
    {"sprites_aux2", kSpritesPalettesAux2},
    {"sprites_aux3", kSpritesPalettesAux3},
    {"dungeon_main", kDungeonMainPalettes},
    {"grass", kHardcodedGrassLW},
    {"3d_object", kTriforcePalette},
    {"ow_mini_map", kOverworldMiniMapPalettes},
}
Definition at line 184 of file snes_palette.cc.
Referenced by GetPaletteAddress().
kPaletteGroupColorCounts
const absl::flat_hash_map<std::string, uint32_t> yaze::app::gfx::kPaletteGroupColorCounts
Initial value:
= {
    {"ow_main", 35},     {"ow_aux", 21},         {"ow_animated", 7},
    {"hud", 32},         {"global_sprites", 60}, {"armors", 15},
    {"swords", 3},       {"shields", 4},         {"sprites_aux1", 7},
    {"sprites_aux2", 7}, {"sprites_aux3", 7},    {"dungeon_main", 90},
    {"grass", 1},        {"3d_object", 8},       {"ow_mini_map", 128},
}
Definition at line 202 of file snes_palette.cc.
Referenced by GetPaletteAddress().
kNumPalettes
int yaze::app::gfx::kNumPalettes = 14 constexpr
Definition at line 25 of file snes_palette.h.
Referenced by yaze::app::editor::PaletteEditor::Update().
kPaletteGroupAddressesKeys
const char* yaze::app::gfx::kPaletteGroupAddressesKeys[] constexpr
Initial value:
= {
    "ow_main",        "ow_aux",       "ow_animated",  "hud",
    "global_sprites", "armors",       "swords",       "shields",
    "sprites_aux1",   "sprites_aux2", "sprites_aux3", "dungeon_main",
    "grass",          "3d_object",    "ow_mini_map",
}
Definition at line 56 of file snes_palette.h.
Referenced by yaze::app::gui::Canvas::DrawContextMenu(), and yaze_get_color_from_paletteset().
kOverworldPaletteMain
int yaze::app::gfx::kOverworldPaletteMain = 0xDE6C8 constexpr
Definition at line 63 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldMainPalettes().
kOverworldPaletteAux
int yaze::app::gfx::kOverworldPaletteAux = 0xDE86C constexpr
Definition at line 64 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes().
kOverworldPaletteAnimated
int yaze::app::gfx::kOverworldPaletteAnimated = 0xDE604 constexpr
Definition at line 65 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldAnimatedPalettes().
kGlobalSpritesLW
int yaze::app::gfx::kGlobalSpritesLW = 0xDD218 constexpr
Definition at line 66 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes().
globalSpritePalettesDW
int yaze::app::gfx::globalSpritePalettesDW = 0xDD290 constexpr
Definition at line 67 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes().
kArmorPalettes
int yaze::app::gfx::kArmorPalettes = 0xDD308 constexpr
Definition at line 69 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadArmorPalettes().
kSpritesPalettesAux1
int yaze::app::gfx::kSpritesPalettesAux1 = 0xDD39E constexpr
Definition at line 70 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadSpriteAux1Palettes().
kSpritesPalettesAux2
int yaze::app::gfx::kSpritesPalettesAux2 = 0xDD446 constexpr
Definition at line 71 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadSpriteAux2Palettes().
kSpritesPalettesAux3
int yaze::app::gfx::kSpritesPalettesAux3 = 0xDD4E0 constexpr
Definition at line 72 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadSpriteAux3Palettes().
kSwordPalettes
int yaze::app::gfx::kSwordPalettes = 0xDD630 constexpr
Definition at line 73 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadSwordPalettes().
kShieldPalettes
int yaze::app::gfx::kShieldPalettes = 0xDD648 constexpr
Definition at line 74 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadShieldPalettes().
kHudPalettes
int yaze::app::gfx::kHudPalettes = 0xDD660 constexpr
Definition at line 75 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadHUDPalettes().
dungeonMapPalettes
int yaze::app::gfx::dungeonMapPalettes = 0xDD70A constexpr
Definition at line 76 of file snes_palette.h.
kDungeonMainPalettes
int yaze::app::gfx::kDungeonMainPalettes = 0xDD734 constexpr
Definition at line 77 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadDungeonMainPalettes().
dungeonMapBgPalettes
int yaze::app::gfx::dungeonMapBgPalettes = 0xDE544 constexpr
Definition at line 78 of file snes_palette.h.
kHardcodedGrassLW
int yaze::app::gfx::kHardcodedGrassLW = 0x5FEA9 constexpr
Definition at line 80 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
hardcodedGrassDW
int yaze::app::gfx::hardcodedGrassDW = 0x05FEB3 constexpr
Definition at line 81 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
hardcodedGrassSpecial
int yaze::app::gfx::hardcodedGrassSpecial = 0x75640 constexpr
Definition at line 82 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
kOverworldMiniMapPalettes
int yaze::app::gfx::kOverworldMiniMapPalettes = 0x55B27 constexpr
Definition at line 83 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::LoadOverworldMiniMapPalettes().
kTriforcePalette
int yaze::app::gfx::kTriforcePalette = 0x64425 constexpr
Definition at line 84 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::Load3DObjectPalettes().
crystalPalette
int yaze::app::gfx::crystalPalette = 0xF4CD3 constexpr
Definition at line 85 of file snes_palette.h.
Referenced by yaze::app::gfx::palette_group_internal::Load3DObjectPalettes().
customAreaSpecificBGPalette
int yaze::app::gfx::customAreaSpecificBGPalette = 0x140000 constexpr
Definition at line 87 of file snes_palette.h.
customAreaSpecificBGASM
int yaze::app::gfx::customAreaSpecificBGASM = 0x140150 constexpr
Definition at line 88 of file snes_palette.h.
customAreaSpecificBGEnabled
int yaze::app::gfx::customAreaSpecificBGEnabled = 0x140140 constexpr
Definition at line 90 of file snes_palette.h.
TilePriorityBit
ushort yaze::app::gfx::TilePriorityBit = 0x2000 constexpr
Definition at line 14 of file snes_tile.cc.
Referenced by GetTilesInfo(), and TileInfoToShort().
TileHFlipBit
ushort yaze::app::gfx::TileHFlipBit = 0x4000 constexpr
Definition at line 17 of file snes_tile.cc.
Referenced by GetTilesInfo(), and TileInfoToShort().
TileVFlipBit
ushort yaze::app::gfx::TileVFlipBit = 0x8000 constexpr
Definition at line 20 of file snes_tile.cc.
Referenced by GetTilesInfo(), and TileInfoToShort().
TileNameMask
ushort yaze::app::gfx::TileNameMask = 0x03FF constexpr
Definition at line 23 of file snes_tile.cc.
Referenced by GetTilesInfo(), and TileInfoToShort().
kGraphicsBitmap
uint8_t yaze::app::gfx::kGraphicsBitmap[8] constexpr
Initial value:
= {0x80, 0x40, 0x20, 0x10,
                                        0x08, 0x04, 0x02, 0x01}
Definition at line 14 of file snes_tile.h.
Referenced by SnesTo8bppSheet().