yaze: yaze::app::zelda3::anonymous_namespace{overworld.cc} Namespace Reference
yaze::app::zelda3::anonymous_namespace{overworld.cc} Namespace Reference
Functions
absl::flat_hash_map< int, MapData > parseFile (const std::string &filename)
std::vector< uint64_t > GetAllTile16 (OWMapTiles &map_tiles_)
bool compareItemsArrays (std::vector< OverworldItem > itemArray1, std::vector< OverworldItem > itemArray2)
Function Documentation
parseFile()
absl::flat_hash_map< int, MapData > yaze::app::zelda3::anonymous_namespace{overworld.cc}::parseFile (const std::string & filename)
References parseFile().
Referenced by parseFile().
GetAllTile16()
std::vector< uint64_t > yaze::app::zelda3::anonymous_namespace{overworld.cc}::GetAllTile16 (OWMapTiles & map_tiles_)
References OWMapTiles::dark_world, GetAllTile16(), yaze::app::gfx::Tile32::GetPackedValue(), yaze::app::zelda3::kNumOverworldMaps, OWMapTiles::light_world, and OWMapTiles::special_world.
Referenced by GetAllTile16().
compareItemsArrays()
bool yaze::app::zelda3::anonymous_namespace{overworld.cc}::compareItemsArrays (std::vector< OverworldItem > itemArray1, std::vector< OverworldItem > itemArray2)
References compareItemsArrays().
Referenced by compareItemsArrays().