yaze: yaze::app::gfx::palette_group_internal Namespace Reference
yaze::app::gfx::palette_group_internal Namespace Reference
Internal functions for loading palettes by group.
Functions
absl::Status LoadOverworldMainPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAuxiliaryPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAnimatedPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadHUDPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadGlobalSpritePalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadArmorPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSwordPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadShieldPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux1Palettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux2Palettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux3Palettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadDungeonMainPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadGrassColors (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status Load3DObjectPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldMiniMapPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
Detailed Description
Internal functions for loading palettes by group.
Function Documentation
LoadOverworldMainPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadOverworldMainPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 28 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kOverworldPaletteMain, yaze::app::gfx::PaletteGroupMap::overworld_main, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadOverworldAuxiliaryPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 39 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kOverworldPaletteAux, yaze::app::gfx::PaletteGroupMap::overworld_aux, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadOverworldAnimatedPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadOverworldAnimatedPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 50 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kOverworldPaletteAnimated, yaze::app::gfx::PaletteGroupMap::overworld_animated, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadHUDPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadHUDPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 60 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::hud, yaze::app::gfx::kHudPalettes, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadGlobalSpritePalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 70 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::global_sprites, yaze::app::gfx::globalSpritePalettesDW, yaze::app::gfx::kGlobalSpritesLW, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadArmorPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadArmorPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 80 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::armors, yaze::app::gfx::kArmorPalettes, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadSwordPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadSwordPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 90 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kSwordPalettes, yaze::app::gfx::ReadPaletteFromRom(), and yaze::app::gfx::PaletteGroupMap::swords.
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadShieldPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadShieldPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 100 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kShieldPalettes, yaze::app::gfx::ReadPaletteFromRom(), and yaze::app::gfx::PaletteGroupMap::shields.
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadSpriteAux1Palettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadSpriteAux1Palettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 110 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kSpritesPalettesAux1, yaze::app::gfx::ReadPaletteFromRom(), and yaze::app::gfx::PaletteGroupMap::sprites_aux1.
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadSpriteAux2Palettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadSpriteAux2Palettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 120 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kSpritesPalettesAux2, yaze::app::gfx::ReadPaletteFromRom(), and yaze::app::gfx::PaletteGroupMap::sprites_aux2.
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadSpriteAux3Palettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadSpriteAux3Palettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 130 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kSpritesPalettesAux3, yaze::app::gfx::ReadPaletteFromRom(), and yaze::app::gfx::PaletteGroupMap::sprites_aux3.
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadDungeonMainPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadDungeonMainPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 140 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::PaletteGroupMap::dungeon_main, yaze::app::gfx::kDungeonMainPalettes, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadGrassColors()
absl::Status yaze::app::gfx::palette_group_internal::LoadGrassColors (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 150 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddColor(), yaze::app::gfx::PaletteGroupMap::grass, yaze::app::gfx::hardcodedGrassDW, yaze::app::gfx::hardcodedGrassSpecial, yaze::app::gfx::kHardcodedGrassLW, and yaze::app::gfx::ReadColorFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
Load3DObjectPalettes()
absl::Status yaze::app::gfx::palette_group_internal::Load3DObjectPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 161 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::crystalPalette, yaze::app::gfx::kTriforcePalette, yaze::app::gfx::PaletteGroupMap::object_3d, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().
LoadOverworldMiniMapPalettes()
absl::Status yaze::app::gfx::palette_group_internal::LoadOverworldMiniMapPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 171 of file snes_palette.cc.
References yaze::app::gfx::PaletteGroup::AddPalette(), yaze::app::gfx::kOverworldMiniMapPalettes, yaze::app::gfx::PaletteGroupMap::overworld_mini_map, and yaze::app::gfx::ReadPaletteFromRom().
Referenced by yaze::app::gfx::LoadAllPalettes().