yaze: yaze::app::core::anonymous_namespace{asar_wrapper_test.cc} Namespace Reference
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc} Namespace Reference
Classes
class AsarWrapperTest
Functions
TEST_F (AsarWrapperTest, InitializationAndShutdown)
TEST_F (AsarWrapperTest, DoubleInitialization)
TEST_F (AsarWrapperTest, OperationsWithoutInitialization)
TEST_F (AsarWrapperTest, ValidPatchApplication)
TEST_F (AsarWrapperTest, InvalidPatchHandling)
TEST_F (AsarWrapperTest, NonexistentPatchFile)
TEST_F (AsarWrapperTest, SymbolExtraction)
TEST_F (AsarWrapperTest, SymbolTableOperations)
TEST_F (AsarWrapperTest, PatchFromString)
TEST_F (AsarWrapperTest, AssemblyValidation)
TEST_F (AsarWrapperTest, ResetFunctionality)
TEST_F (AsarWrapperTest, CreatePatchNotImplemented)
Function Documentation
TEST_F() [1/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , InitializationAndShutdown)
Definition at line 80 of file asar_wrapper_test.cc.
References TEST_F().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
TEST_F() [2/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , DoubleInitialization)
Definition at line 101 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [3/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , OperationsWithoutInitialization)
Definition at line 110 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [4/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , ValidPatchApplication)
Definition at line 126 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [5/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , InvalidPatchHandling)
Definition at line 145 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [6/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , NonexistentPatchFile)
Definition at line 156 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [7/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , SymbolExtraction)
Definition at line 166 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [8/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , SymbolTableOperations)
Definition at line 195 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [9/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , PatchFromString)
Definition at line 234 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [10/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , AssemblyValidation)
Definition at line 267 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [11/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , ResetFunctionality)
Definition at line 281 of file asar_wrapper_test.cc.
References TEST_F().
TEST_F() [12/12]
yaze::app::core::anonymous_namespace{asar_wrapper_test.cc}::TEST_F (AsarWrapperTest , CreatePatchNotImplemented)
Definition at line 305 of file asar_wrapper_test.cc.
References TEST_F().