yaze: yaze::app::editor::entrance_internal Namespace Reference
yaze::app::editor::entrance_internal Namespace Reference
Functions
bool DrawEntranceInserterPopup ()
bool DrawOverworldEntrancePopup (zelda3::overworld::OverworldEntrance &entrance)
Function Documentation
DrawEntranceInserterPopup()
bool yaze::app::editor::entrance_internal::DrawEntranceInserterPopup ()
References ICON_MD_CANCEL, ICON_MD_DONE, and yaze::app::gui::InputHex().
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances().
DrawOverworldEntrancePopup()
bool yaze::app::editor::entrance_internal::DrawOverworldEntrancePopup (zelda3::overworld::OverworldEntrance & entrance)
Todo
Implement deleting OverworldEntrance objects, currently only hides them
References yaze::app::zelda3::overworld::OverworldEntrance::deleted, yaze::app::zelda3::overworld::OverworldEntrance::entrance_id_, ICON_MD_CANCEL, ICON_MD_DELETE, ICON_MD_DONE, yaze::app::gui::InputHex(), yaze::app::gui::InputHexByte(), yaze::app::zelda3::OverworldEntity::map_id_, yaze::app::zelda3::OverworldEntity::x_, and yaze::app::zelda3::OverworldEntity::y_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances().