yaze: yaze::app::editor::anonymous_namespace{master_editor.cc} Namespace Reference
yaze::app::editor::anonymous_namespace{master_editor.cc} Namespace Reference
Functions
bool BeginCentered (const char *name)
bool IsEditorActive (Editor *editor, std::vector< Editor * > &active_editors)
Function Documentation
BeginCentered()
bool yaze::app::editor::anonymous_namespace{master_editor.cc}::BeginCentered (const char * name)
References BeginCentered().
Referenced by BeginCentered().
IsEditorActive()
bool yaze::app::editor::anonymous_namespace{master_editor.cc}::IsEditorActive (Editor * editor, std::vector< Editor * > & active_editors)
References IsEditorActive().
Referenced by IsEditorActive().