yaze: yaze::zelda3::anonymous_namespace{hyrule_magic.cc} Namespace Reference
yaze::zelda3::anonymous_namespace{hyrule_magic.cc} Namespace Reference
Functions
unsigned ldle (uint8_t const *const p_arr, unsigned const p_index)
void stle (uint8_t *const p_arr, size_t const p_index, unsigned const p_val)
void stle0 (uint8_t *const p_arr, unsigned const p_val)
void stle1 (uint8_t *const p_arr, unsigned const p_val)
void stle2 (uint8_t *const p_arr, unsigned const p_val)
void stle3 (uint8_t *const p_arr, unsigned const p_val)
uint32_t ldle0 (uint8_t const *const p_arr)
uint32_t ldle1 (uint8_t const *const p_arr)
uint32_t ldle2 (uint8_t const *const p_arr)
uint32_t ldle3 (uint8_t const *const p_arr)
Function Documentation
ldle()
unsigned yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::ldle (uint8_t const *const p_arr, unsigned const p_index)
Definition at line 10 of file hyrule_magic.cc.
References ldle().
Referenced by ldle(), ldle0(), ldle1(), ldle2(), and ldle3().
stle()
void yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::stle (uint8_t *const p_arr, size_t const p_index, unsigned const p_val)
Definition at line 16 of file hyrule_magic.cc.
References stle().
Referenced by stle(), stle0(), stle1(), stle2(), and stle3().
stle0()
void yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::stle0 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 21 of file hyrule_magic.cc.
References stle(), and stle0().
Referenced by stle0().
stle1()
void yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::stle1 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 25 of file hyrule_magic.cc.
References stle(), and stle1().
Referenced by stle1().
stle2()
void yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::stle2 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 29 of file hyrule_magic.cc.
References stle(), and stle2().
Referenced by stle2().
stle3()
void yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::stle3 (uint8_t *const p_arr, unsigned const p_val)
Definition at line 33 of file hyrule_magic.cc.
References stle(), and stle3().
Referenced by stle3().
ldle0()
uint32_t yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::ldle0 (uint8_t const *const p_arr)
Definition at line 38 of file hyrule_magic.cc.
References ldle(), and ldle0().
Referenced by ldle0().
ldle1()
uint32_t yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::ldle1 (uint8_t const *const p_arr)
Definition at line 41 of file hyrule_magic.cc.
References ldle(), and ldle1().
Referenced by ldle1().
ldle2()
uint32_t yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::ldle2 (uint8_t const *const p_arr)
Definition at line 44 of file hyrule_magic.cc.
References ldle(), and ldle2().
Referenced by ldle2().
ldle3()
uint32_t yaze::zelda3::anonymous_namespace{hyrule_magic.cc}::ldle3 (uint8_t const *const p_arr)
Definition at line 47 of file hyrule_magic.cc.
References ldle(), and ldle3().
Referenced by ldle3().