yaze: yaze::app::editor::exit_internal Namespace Reference
yaze::app::editor::exit_internal Namespace Reference
Functions
void DrawExitInserterPopup ()
bool DrawExitEditorPopup (zelda3::overworld::OverworldExit &exit)
Function Documentation
DrawExitInserterPopup()
void yaze::app::editor::exit_internal::DrawExitInserterPopup ()
Todo
Implement deleting OverworldExit objects
References ICON_MD_CANCEL, ICON_MD_DONE, and yaze::app::gui::InputHex().
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldExits().
DrawExitEditorPopup()
bool yaze::app::editor::exit_internal::DrawExitEditorPopup (zelda3::overworld::OverworldExit & exit)
References yaze::app::zelda3::overworld::OverworldExit::deleted_, yaze::app::zelda3::overworld::OverworldExit::door_type_1_, yaze::app::zelda3::overworld::OverworldExit::door_type_2_, yaze::app::zelda3::OverworldEntity::entity_id_, ICON_MD_CANCEL, ICON_MD_DELETE, ICON_MD_DONE, yaze::app::gui::InputHex(), yaze::app::gui::InputHexByte(), yaze::app::gui::InputHexWord(), yaze::app::zelda3::overworld::OverworldExit::is_automatic_, yaze::app::zelda3::overworld::OverworldExit::is_hole_, yaze::app::zelda3::overworld::OverworldExit::large_map_, yaze::app::zelda3::OverworldEntity::map_id_, yaze::app::zelda3::overworld::OverworldExit::room_id_, yaze::app::gui::TextWithSeparators(), yaze::app::zelda3::OverworldEntity::x_, yaze::app::zelda3::overworld::OverworldExit::x_camera_, yaze::app::zelda3::overworld::OverworldExit::x_scroll_, yaze::app::zelda3::OverworldEntity::y_, yaze::app::zelda3::overworld::OverworldExit::y_camera_, and yaze::app::zelda3::overworld::OverworldExit::y_scroll_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldExits().