yaze: yaze::gfx::palette_group_internal Namespace Reference
yaze::gfx::palette_group_internal Namespace Reference
Internal functions for loading palettes by group.
Functions
absl::Status LoadOverworldMainPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAuxiliaryPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldAnimatedPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadHUDPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadGlobalSpritePalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadArmorPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSwordPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadShieldPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux1Palettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux2Palettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadSpriteAux3Palettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadDungeonMainPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadGrassColors (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status Load3DObjectPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
absl::Status LoadOverworldMiniMapPalettes (const std::vector< uint8_t > &rom_data, gfx::PaletteGroupMap &palette_groups)
Detailed Description
Internal functions for loading palettes by group.
Function Documentation
LoadOverworldMainPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadOverworldMainPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 27 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kOverworldPaletteMain, yaze::gfx::PaletteGroupMap::overworld_main, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadOverworldAuxiliaryPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 38 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kOverworldPaletteAux, yaze::gfx::PaletteGroupMap::overworld_aux, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadOverworldAnimatedPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadOverworldAnimatedPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 50 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kOverworldPaletteAnimated, yaze::gfx::PaletteGroupMap::overworld_animated, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadHUDPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadHUDPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 61 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::PaletteGroupMap::hud, yaze::gfx::kHudPalettes, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadGlobalSpritePalettes()
absl::Status yaze::gfx::palette_group_internal::LoadGlobalSpritePalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 71 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::PaletteGroupMap::global_sprites, yaze::gfx::kGlobalSpritePalettesDW, yaze::gfx::kGlobalSpritesLW, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadArmorPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadArmorPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 81 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::PaletteGroupMap::armors, yaze::gfx::kArmorPalettes, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadSwordPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadSwordPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 91 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kSwordPalettes, yaze::gfx::ReadPaletteFromRom(), and yaze::gfx::PaletteGroupMap::swords.
Referenced by yaze::gfx::LoadAllPalettes().
LoadShieldPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadShieldPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 101 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kShieldPalettes, yaze::gfx::ReadPaletteFromRom(), and yaze::gfx::PaletteGroupMap::shields.
Referenced by yaze::gfx::LoadAllPalettes().
LoadSpriteAux1Palettes()
absl::Status yaze::gfx::palette_group_internal::LoadSpriteAux1Palettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 111 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kSpritesPalettesAux1, yaze::gfx::ReadPaletteFromRom(), and yaze::gfx::PaletteGroupMap::sprites_aux1.
Referenced by yaze::gfx::LoadAllPalettes().
LoadSpriteAux2Palettes()
absl::Status yaze::gfx::palette_group_internal::LoadSpriteAux2Palettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 121 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kSpritesPalettesAux2, yaze::gfx::ReadPaletteFromRom(), and yaze::gfx::PaletteGroupMap::sprites_aux2.
Referenced by yaze::gfx::LoadAllPalettes().
LoadSpriteAux3Palettes()
absl::Status yaze::gfx::palette_group_internal::LoadSpriteAux3Palettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 131 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kSpritesPalettesAux3, yaze::gfx::ReadPaletteFromRom(), and yaze::gfx::PaletteGroupMap::sprites_aux3.
Referenced by yaze::gfx::LoadAllPalettes().
LoadDungeonMainPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadDungeonMainPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 141 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::PaletteGroupMap::dungeon_main, yaze::gfx::kDungeonMainPalettes, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadGrassColors()
absl::Status yaze::gfx::palette_group_internal::LoadGrassColors (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 151 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddColor(), yaze::gfx::PaletteGroupMap::grass, yaze::gfx::kHardcodedGrassDW, yaze::gfx::kHardcodedGrassLW, yaze::gfx::kHardcodedGrassSpecial, and yaze::gfx::ReadColorFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
Load3DObjectPalettes()
absl::Status yaze::gfx::palette_group_internal::Load3DObjectPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 162 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kCrystalPalette, yaze::gfx::kTriforcePalette, yaze::gfx::PaletteGroupMap::object_3d, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().
LoadOverworldMiniMapPalettes()
absl::Status yaze::gfx::palette_group_internal::LoadOverworldMiniMapPalettes (const std::vector< uint8_t > & rom_data, gfx::PaletteGroupMap & palette_groups)
Definition at line 172 of file snes_palette.cc.
References yaze::gfx::PaletteGroup::AddPalette(), yaze::gfx::kOverworldMiniMapPalettes, yaze::gfx::PaletteGroupMap::overworld_mini_map, and yaze::gfx::ReadPaletteFromRom().
Referenced by yaze::gfx::LoadAllPalettes().