yaze: yaze::gui::anonymous_namespace{style.cc} Namespace Reference
yaze::gui::anonymous_namespace{style.cc} Namespace Reference
Functions
Color ParseColor (const std::string &color)
absl::Status ParseThemeContents (const std::string &key, const std::string &value, Theme &theme)
Function Documentation
ParseColor()
Color yaze::gui::anonymous_namespace{style.cc}::ParseColor (const std::string & color)
Definition at line 12 of file style.cc.
References yaze::gui::Color::blue, yaze::gui::Color::green, ParseColor(), and yaze::gui::Color::red.
Referenced by ParseColor(), and ParseThemeContents().
ParseThemeContents()
absl::Status yaze::gui::anonymous_namespace{style.cc}::ParseThemeContents (const std::string & key, const std::string & value, Theme & theme)
Definition at line 24 of file style.cc.
References yaze::gui::Theme::menu_bar_bg, ParseColor(), ParseThemeContents(), yaze::gui::Theme::tab, yaze::gui::Theme::tab_active, yaze::gui::Theme::tab_hovered, yaze::gui::Theme::title_bg_active, and yaze::gui::Theme::title_bg_collapsed.
Referenced by ParseThemeContents().