yaze: yaze::test::emu Namespace Reference
yaze::test::emu Namespace Reference
Classes
class CpuTest
class MockAudioRam
MockAudioRam is a mock class for the AudioRam class.
class MockPpu
Mock Ppu class for testing.
class PpuTest
class Spc700Test
Functions
TEST_F (CpuTest, AsmParserTokenizerOk)
TEST_F (CpuTest, AsmParserSingleInstructionOk)
TEST_F (CpuTest, CheckMemoryContents)
TEST_F (CpuTest, ADC_CheckCarryFlag)
TEST_F (CpuTest, ADC_DirectPageIndexedIndirectX)
TEST_F (CpuTest, ADC_StackRelative)
TEST_F (CpuTest, ADC_DirectPage)
TEST_F (CpuTest, ADC_DirectPageIndirectLong)
TEST_F (CpuTest, ADC_Immediate_TwoPositiveNumbers)
TEST_F (CpuTest, ADC_Immediate_PositiveAndNegativeNumbers)
TEST_F (CpuTest, ADC_Absolute)
TEST_F (CpuTest, ADC_AbsoluteLong)
TEST_F (CpuTest, ADC_DirectPageIndirectIndexedY)
TEST_F (CpuTest, ADC_DirectPageIndirect)
TEST_F (CpuTest, ADC_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, ADC_DirectPageIndexedX)
TEST_F (CpuTest, ADC_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, ADC_AbsoluteIndexedY)
TEST_F (CpuTest, ADC_AbsoluteIndexedX)
TEST_F (CpuTest, ADC_AbsoluteLongIndexedX)
TEST_F (CpuTest, AND_DirectPageIndexedIndirectX)
TEST_F (CpuTest, AND_StackRelative)
TEST_F (CpuTest, AND_DirectPage)
TEST_F (CpuTest, AND_DirectPageIndirectLong)
TEST_F (CpuTest, AND_Immediate)
TEST_F (CpuTest, AND_Absolute_16BitMode)
TEST_F (CpuTest, AND_AbsoluteLong)
TEST_F (CpuTest, AND_DirectPageIndirectIndexedY)
TEST_F (CpuTest, AND_DirectPageIndirect)
TEST_F (CpuTest, AND_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, AND_DirectPageIndexedX)
TEST_F (CpuTest, AND_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, AND_AbsoluteIndexedY)
TEST_F (CpuTest, AND_AbsoluteIndexedX)
TEST_F (CpuTest, AND_AbsoluteLongIndexedX)
TEST_F (CpuTest, ASL_DirectPage)
TEST_F (CpuTest, ASL_Accumulator)
TEST_F (CpuTest, ASL_Absolute)
TEST_F (CpuTest, ASL_DirectPageIndexedX)
TEST_F (CpuTest, ASL_AbsoluteIndexedX)
TEST_F (CpuTest, BCC_WhenCarryFlagClear)
TEST_F (CpuTest, BCC_WhenCarryFlagSet)
TEST_F (CpuTest, BCS_WhenCarryFlagSet)
TEST_F (CpuTest, BCS_WhenCarryFlagClear)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagSet)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagClear)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagSet_OverflowFlagSet)
TEST_F (CpuTest, BEQ_Immediate_ZeroFlagClear_OverflowFlagSet)
TEST_F (CpuTest, BIT_DirectPage)
TEST_F (CpuTest, BIT_Absolute)
TEST_F (CpuTest, BIT_DirectPageIndexedX)
TEST_F (CpuTest, BIT_AbsoluteIndexedX)
TEST_F (CpuTest, BIT_Immediate)
TEST_F (CpuTest, BMI_BranchTaken)
TEST_F (CpuTest, BMI_BranchNotTaken)
TEST_F (CpuTest, BNE_BranchTaken)
TEST_F (CpuTest, BNE_BranchNotTaken)
TEST_F (CpuTest, BPL_BranchTaken)
TEST_F (CpuTest, BPL_BranchNotTaken)
TEST_F (CpuTest, BRA)
TEST_F (CpuTest, BRK)
TEST_F (CpuTest, BRL)
TEST_F (CpuTest, BVC_BranchTaken)
TEST_F (CpuTest, BVS_BranchTaken)
TEST_F (CpuTest, CLC)
TEST_F (CpuTest, CLD)
TEST_F (CpuTest, CLI)
TEST_F (CpuTest, CLV)
TEST_F (CpuTest, CMP_DirectPageIndexedIndirectX)
TEST_F (CpuTest, CMP_StackRelative)
TEST_F (CpuTest, CMP_DirectPage)
TEST_F (CpuTest, CMP_DirectPageIndirectLong)
TEST_F (CpuTest, CMP_Immediate_8Bit)
TEST_F (CpuTest, CMP_Absolute_16Bit)
TEST_F (CpuTest, CMP_AbsoluteLong)
TEST_F (CpuTest, CMP_DirectPageIndirect)
TEST_F (CpuTest, CMP_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, CMP_DirectPageIndexedX)
TEST_F (CpuTest, CMP_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, CMP_AbsoluteIndexedY)
TEST_F (CpuTest, CMP_AbsoluteIndexedX)
TEST_F (CpuTest, CMP_AbsoluteLongIndexedX)
TEST_F (CpuTest, COP)
TEST_F (CpuTest, CPX_Immediate_ZeroFlagSet)
TEST_F (CpuTest, CPX_Immediate_NegativeFlagSet)
TEST_F (CpuTest, CPX_DirectPage)
TEST_F (CpuTest, CPX_Absolute)
TEST_F (CpuTest, CPY_Immediate_ZeroFlagSet)
TEST_F (CpuTest, CPY_Immediate_NegativeFlagSet)
TEST_F (CpuTest, CPY_DirectPage)
TEST_F (CpuTest, CPY_Absolute)
TEST_F (CpuTest, DEC_Accumulator)
TEST_F (CpuTest, DEC_DirectPage)
TEST_F (CpuTest, DEC_Absolute)
TEST_F (CpuTest, DEC_DirectPageIndexedX)
TEST_F (CpuTest, DEC_AbsoluteIndexedX)
TEST_F (CpuTest, DEX)
TEST_F (CpuTest, DEY)
TEST_F (CpuTest, EOR_DirectPageIndexedIndirectX)
TEST_F (CpuTest, EOR_StackRelative)
TEST_F (CpuTest, EOR_DirectPage)
TEST_F (CpuTest, EOR_DirectPageIndirectLong)
TEST_F (CpuTest, EOR_Immediate_8bit)
TEST_F (CpuTest, EOR_Absolute)
TEST_F (CpuTest, EOR_AbsoluteLong)
TEST_F (CpuTest, EOR_DirectPageIndirectIndexedY)
TEST_F (CpuTest, EOR_DirectPageIndirect)
TEST_F (CpuTest, EOR_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, EOR_DirectPageIndexedX)
TEST_F (CpuTest, EOR_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, EOR_AbsoluteIndexedY)
TEST_F (CpuTest, EOR_AbsoluteIndexedX)
TEST_F (CpuTest, EOR_AbsoluteLongIndexedX)
TEST_F (CpuTest, INC_Accumulator)
TEST_F (CpuTest, INC_DirectPage_8bit)
TEST_F (CpuTest, INC_Absolute_16bit)
TEST_F (CpuTest, INC_DirectPage_ZeroResult_8bit)
TEST_F (CpuTest, INC_Absolute_ZeroResult_16bit)
TEST_F (CpuTest, INC_DirectPage_8bit_Overflow)
TEST_F (CpuTest, INC_DirectPageIndexedX_8bit)
TEST_F (CpuTest, INC_AbsoluteIndexedX_16bit)
TEST_F (CpuTest, INX)
TEST_F (CpuTest, INY)
TEST_F (CpuTest, JMP_Absolute)
TEST_F (CpuTest, JMP_Indirect)
TEST_F (CpuTest, JML_AbsoluteLong)
TEST_F (CpuTest, JMP_AbsoluteIndexedIndirectX)
TEST_F (CpuTest, JMP_AbsoluteIndirectLong)
TEST_F (CpuTest, JSR_Absolute)
TEST_F (CpuTest, JSL_AbsoluteLong)
TEST_F (CpuTest, JSL_AbsoluteIndexedIndirect)
TEST_F (CpuTest, LDA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, LDA_StackRelative)
TEST_F (CpuTest, LDA_DirectPage)
TEST_F (CpuTest, LDA_DirectPageIndirectLong)
TEST_F (CpuTest, LDA_Immediate_8bit)
TEST_F (CpuTest, LDA_Immediate_16bit)
TEST_F (CpuTest, LDA_Absolute)
TEST_F (CpuTest, LDA_AbsoluteLong)
TEST_F (CpuTest, LDA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, LDA_DirectPageIndirect)
TEST_F (CpuTest, LDA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, LDA_DirectPageIndexedX)
TEST_F (CpuTest, LDA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, LDA_AbsoluteIndexedY)
TEST_F (CpuTest, LDA_AbsoluteIndexedX)
TEST_F (CpuTest, LDA_AbsoluteLongIndexedX)
TEST_F (CpuTest, LDX_Immediate)
TEST_F (CpuTest, LDX_DirectPage)
TEST_F (CpuTest, LDX_Absolute)
TEST_F (CpuTest, LDX_DirectPageIndexedY)
TEST_F (CpuTest, LDX_AbsoluteIndexedY)
TEST_F (CpuTest, LDY_Immediate)
TEST_F (CpuTest, LDY_DirectPage)
TEST_F (CpuTest, LDY_Absolute)
TEST_F (CpuTest, LDY_DirectPageIndexedX)
TEST_F (CpuTest, LDY_AbsoluteIndexedX)
TEST_F (CpuTest, LSR_DirectPage)
TEST_F (CpuTest, LSR_Accumulator)
TEST_F (CpuTest, LSR_Absolute)
TEST_F (CpuTest, LSR_DirectPageIndexedX)
TEST_F (CpuTest, LSR_AbsoluteIndexedX)
TEST_F (CpuTest, ORA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, ORA_StackRelative)
TEST_F (CpuTest, ORA_DirectPage)
TEST_F (CpuTest, ORA_DirectPageIndirectLong)
TEST_F (CpuTest, ORA_Immediate)
TEST_F (CpuTest, ORA_Absolute)
TEST_F (CpuTest, ORA_AbsoluteLong)
TEST_F (CpuTest, ORA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, ORA_DirectPageIndirect)
TEST_F (CpuTest, ORA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, ORA_DirectPageIndexedX)
TEST_F (CpuTest, ORA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, ORA_AbsoluteIndexedY)
TEST_F (CpuTest, ORA_AbsoluteIndexedX)
TEST_F (CpuTest, ORA_AbsoluteLongIndexedX)
TEST_F (CpuTest, PEA)
TEST_F (CpuTest, PEI)
TEST_F (CpuTest, PER)
TEST_F (CpuTest, PHD)
TEST_F (CpuTest, PHK)
TEST_F (CpuTest, PHP)
TEST_F (CpuTest, PHX)
TEST_F (CpuTest, PHY)
TEST_F (CpuTest, PHB)
TEST_F (CpuTest, PHA)
TEST_F (CpuTest, PHA_16Bit)
TEST_F (CpuTest, PLA)
TEST_F (CpuTest, PLA_16Bit)
TEST_F (CpuTest, PLB)
TEST_F (CpuTest, PLD)
TEST_F (CpuTest, PLP)
TEST_F (CpuTest, PLX)
TEST_F (CpuTest, PLX_16Bit)
TEST_F (CpuTest, PLY)
TEST_F (CpuTest, PLY_16Bit)
TEST_F (CpuTest, REP)
TEST_F (CpuTest, REP_16Bit)
TEST_F (CpuTest, PHA_PLA_Ok)
TEST_F (CpuTest, PHP_PLP_Ok)
TEST_F (CpuTest, PHA_PushAccumulator)
TEST_F (CpuTest, PHP_PushProcessorStatusRegister)
TEST_F (CpuTest, PHX_PushXRegister)
TEST_F (CpuTest, PHY_PushYRegister)
TEST_F (CpuTest, PHB_PushDataBankRegister)
TEST_F (CpuTest, PHD_PushDirectPageRegister)
TEST_F (CpuTest, PHK_PushProgramBankRegister)
TEST_F (CpuTest, PLA_PullAccumulator)
TEST_F (CpuTest, PLP_PullProcessorStatusRegister)
TEST_F (CpuTest, PLX_PullXRegister)
TEST_F (CpuTest, PLY_PullYRegister)
TEST_F (CpuTest, PLB_PullDataBankRegister)
TEST_F (CpuTest, PLD_PullDirectPageRegister)
TEST_F (CpuTest, SEP)
TEST_F (CpuTest, ROL_DirectPage)
TEST_F (CpuTest, ROL_Accumulator)
TEST_F (CpuTest, ROL_Absolute)
TEST_F (CpuTest, ROL_DirectPageIndexedX)
TEST_F (CpuTest, ROL_AbsoluteIndexedX)
TEST_F (CpuTest, ROR_DirectPage)
TEST_F (CpuTest, ROR_Accumulator)
TEST_F (CpuTest, ROR_Absolute)
TEST_F (CpuTest, ROR_DirectPageIndexedX)
TEST_F (CpuTest, ROR_AbsoluteIndexedX)
TEST_F (CpuTest, RTI)
TEST_F (CpuTest, RTL)
TEST_F (CpuTest, RTS)
TEST_F (CpuTest, SBC_DirectPageIndexedIndirectX)
TEST_F (CpuTest, SBC_StackRelative)
TEST_F (CpuTest, SBC_DirectPage)
TEST_F (CpuTest, SBC_DirectPageIndirectLong)
TEST_F (CpuTest, SBC_Immediate)
TEST_F (CpuTest, SBC_Absolute)
TEST_F (CpuTest, SBC_AbsoluteLong)
TEST_F (CpuTest, SBC_DirectPageIndirectIndexedY)
TEST_F (CpuTest, SBC_DirectPageIndirect)
TEST_F (CpuTest, SBC_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, SBC_DirectPageIndexedX)
TEST_F (CpuTest, SBC_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, SBC_AbsoluteIndexedY)
TEST_F (CpuTest, SBC_AbsoluteIndexedX)
TEST_F (CpuTest, SBC_AbsoluteLongIndexedX)
TEST_F (CpuTest, SEC)
TEST_F (CpuTest, SED)
TEST_F (CpuTest, SEI)
TEST_F (CpuTest, SEP_8Bit)
TEST_F (CpuTest, SEP_16Bit)
TEST_F (CpuTest, STA_DirectPageIndexedIndirectX)
TEST_F (CpuTest, STA_StackRelative)
TEST_F (CpuTest, STA_DirectPage)
TEST_F (CpuTest, STA_DirectPageIndirectLong)
TEST_F (CpuTest, STA_Absolute)
TEST_F (CpuTest, STA_AbsoluteLong)
TEST_F (CpuTest, STA_DirectPageIndirectIndexedY)
TEST_F (CpuTest, STA_DirectPageIndirect)
TEST_F (CpuTest, STA_StackRelativeIndirectIndexedY)
TEST_F (CpuTest, STA_DirectPageIndexedX)
TEST_F (CpuTest, STA_DirectPageIndirectLongIndexedY)
TEST_F (CpuTest, STA_AbsoluteIndexedY)
TEST_F (CpuTest, STA_AbsoluteIndexedX)
TEST_F (CpuTest, STA_AbsoluteLongIndexedX)
TEST_F (CpuTest, STP)
TEST_F (CpuTest, STX_DirectPage)
TEST_F (CpuTest, STX_Absolute)
TEST_F (CpuTest, STX_DirectPageIndexedY)
TEST_F (CpuTest, STY_DirectPage)
TEST_F (CpuTest, STY_Absolute)
TEST_F (CpuTest, STY_DirectPageIndexedX)
TEST_F (CpuTest, STZ_DirectPage)
TEST_F (CpuTest, STZ_DirectPageIndexedX)
TEST_F (CpuTest, STZ_Absolute)
TEST_F (CpuTest, TAX)
TEST_F (CpuTest, TAY)
TEST_F (CpuTest, TCD)
TEST_F (CpuTest, TCS)
TEST_F (CpuTest, TDC)
TEST_F (CpuTest, TRB_DirectPage)
TEST_F (CpuTest, TRB_Absolute)
TEST_F (CpuTest, TSB_DirectPage)
TEST_F (CpuTest, TSB_Absolute)
TEST_F (CpuTest, TSC)
TEST_F (CpuTest, TSX)
TEST_F (CpuTest, TXA)
TEST_F (CpuTest, TXS)
TEST_F (CpuTest, TXY)
TEST_F (CpuTest, TYA)
TEST_F (CpuTest, TYX)
TEST_F (CpuTest, WAI)
TEST_F (CpuTest, WDM)
TEST_F (CpuTest, XBA)
TEST_F (CpuTest, XCESwitchToNativeMode)
TEST_F (CpuTest, XCESwitchToEmulationMode)
TEST_F (CpuTest, XCESwitchBackAndForth)
TEST_F (Spc700Test, MOV_A_Immediate)
TEST_F (Spc700Test, MOV_A_X)
TEST_F (Spc700Test, MOV_A_Y)
TEST_F (Spc700Test, MOV_A_dp)
TEST_F (Spc700Test, MOV_A_dp_plus_x)
TEST_F (Spc700Test, MOV_A_dp_indirect_plus_y)
TEST_F (Spc700Test, MOV_A_dp_plus_x_indirect)
TEST_F (Spc700Test, MOV_A_abs)
TEST_F (Spc700Test, MOV_Immediate)
TEST_F (Spc700Test, NOP_DoesNothing)
TEST_F (Spc700Test, ADC_A_Immediate)
TEST_F (Spc700Test, BEQ_BranchesIfZeroFlagSet)
TEST_F (Spc700Test, STA_Absolute)
TEST_F (Spc700Test, ExecuteADCWithImmediate)
TEST_F (Spc700Test, ExecuteBRA)
TEST_F (Spc700Test, ReadFromAudioRAM)
TEST_F (Spc700Test, WriteToAudioRAM)
TEST_F (Spc700Test, ExecuteANDWithImmediate)
TEST_F (Spc700Test, ExecuteORWithImmediate)
TEST_F (Spc700Test, ExecuteEORWithImmediate)
TEST_F (Spc700Test, ExecuteINC)
TEST_F (Spc700Test, ExecuteDEC)
TEST_F (Spc700Test, ExecuteBNEWhenNotEqual)
TEST_F (Spc700Test, ExecuteBNEWhenEqual)
TEST_F (Spc700Test, ExecuteBEQWhenEqual)
TEST_F (Spc700Test, ExecuteBEQWhenNotEqual)
TEST_F (Spc700Test, BootIplRomOk)
Function Documentation
TEST_F() [1/321]
yaze::test::emu::TEST_F (CpuTest , AsmParserTokenizerOk)
Definition at line 47 of file cpu_test.cc.
References yaze::app::emu::AsmParser::Tokenize().
TEST_F() [2/321]
yaze::test::emu::TEST_F (CpuTest , AsmParserSingleInstructionOk)
Definition at line 63 of file cpu_test.cc.
References yaze::app::emu::AsmParser::Parse(), and yaze::app::emu::AsmParser::Tokenize().
TEST_F() [3/321]
yaze::test::emu::TEST_F (CpuTest , CheckMemoryContents)
Definition at line 75 of file cpu_test.cc.
References yaze::app::emu::memory::Memory::ReadByte(), and yaze::app::emu::memory::MockMemory::SetMemoryContents().
TEST_F() [4/321]
yaze::test::emu::TEST_F (CpuTest , ADC_CheckCarryFlag)
Definition at line 98 of file cpu_test.cc.
TEST_F() [5/321]
yaze::test::emu::TEST_F (CpuTest , ADC_DirectPageIndexedIndirectX)
Definition at line 110 of file cpu_test.cc.
TEST_F() [6/321]
yaze::test::emu::TEST_F (CpuTest , ADC_StackRelative)
Definition at line 127 of file cpu_test.cc.
TEST_F() [7/321]
yaze::test::emu::TEST_F (CpuTest , ADC_DirectPage)
Definition at line 141 of file cpu_test.cc.
TEST_F() [8/321]
yaze::test::emu::TEST_F (CpuTest , ADC_DirectPageIndirectLong)
Definition at line 155 of file cpu_test.cc.
TEST_F() [9/321]
yaze::test::emu::TEST_F (CpuTest , ADC_Immediate_TwoPositiveNumbers)
Definition at line 171 of file cpu_test.cc.
TEST_F() [10/321]
yaze::test::emu::TEST_F (CpuTest , ADC_Immediate_PositiveAndNegativeNumbers)
Definition at line 183 of file cpu_test.cc.
TEST_F() [11/321]
yaze::test::emu::TEST_F (CpuTest , ADC_Absolute)
Definition at line 195 of file cpu_test.cc.
TEST_F() [12/321]
yaze::test::emu::TEST_F (CpuTest , ADC_AbsoluteLong)
Definition at line 209 of file cpu_test.cc.
TEST_F() [13/321]
yaze::test::emu::TEST_F (CpuTest , ADC_DirectPageIndirectIndexedY)
Definition at line 223 of file cpu_test.cc.
TEST_F() [14/321]
yaze::test::emu::TEST_F (CpuTest , ADC_DirectPageIndirect)
Definition at line 240 of file cpu_test.cc.
TEST_F() [15/321]
yaze::test::emu::TEST_F (CpuTest , ADC_StackRelativeIndirectIndexedY)
Definition at line 256 of file cpu_test.cc.
TEST_F() [16/321]
yaze::test::emu::TEST_F (CpuTest , ADC_DirectPageIndexedX)
Definition at line 273 of file cpu_test.cc.
TEST_F() [17/321]
yaze::test::emu::TEST_F (CpuTest , ADC_DirectPageIndirectLongIndexedY)
Definition at line 288 of file cpu_test.cc.
TEST_F() [18/321]
yaze::test::emu::TEST_F (CpuTest , ADC_AbsoluteIndexedY)
Definition at line 305 of file cpu_test.cc.
TEST_F() [19/321]
yaze::test::emu::TEST_F (CpuTest , ADC_AbsoluteIndexedX)
Definition at line 321 of file cpu_test.cc.
TEST_F() [20/321]
yaze::test::emu::TEST_F (CpuTest , ADC_AbsoluteLongIndexedX)
Definition at line 339 of file cpu_test.cc.
TEST_F() [21/321]
yaze::test::emu::TEST_F (CpuTest , AND_DirectPageIndexedIndirectX)
Definition at line 358 of file cpu_test.cc.
TEST_F() [22/321]
yaze::test::emu::TEST_F (CpuTest , AND_StackRelative)
Definition at line 382 of file cpu_test.cc.
TEST_F() [23/321]
yaze::test::emu::TEST_F (CpuTest , AND_DirectPage)
Definition at line 399 of file cpu_test.cc.
TEST_F() [24/321]
yaze::test::emu::TEST_F (CpuTest , AND_DirectPageIndirectLong)
Definition at line 417 of file cpu_test.cc.
TEST_F() [25/321]
yaze::test::emu::TEST_F (CpuTest , AND_Immediate)
Definition at line 440 of file cpu_test.cc.
TEST_F() [26/321]
yaze::test::emu::TEST_F (CpuTest , AND_Absolute_16BitMode)
Definition at line 449 of file cpu_test.cc.
TEST_F() [27/321]
yaze::test::emu::TEST_F (CpuTest , AND_AbsoluteLong)
Definition at line 468 of file cpu_test.cc.
TEST_F() [28/321]
yaze::test::emu::TEST_F (CpuTest , AND_DirectPageIndirectIndexedY)
Definition at line 482 of file cpu_test.cc.
TEST_F() [29/321]
yaze::test::emu::TEST_F (CpuTest , AND_DirectPageIndirect)
Definition at line 499 of file cpu_test.cc.
TEST_F() [30/321]
yaze::test::emu::TEST_F (CpuTest , AND_StackRelativeIndirectIndexedY)
Definition at line 515 of file cpu_test.cc.
TEST_F() [31/321]
yaze::test::emu::TEST_F (CpuTest , AND_DirectPageIndexedX)
Definition at line 534 of file cpu_test.cc.
TEST_F() [32/321]
yaze::test::emu::TEST_F (CpuTest , AND_DirectPageIndirectLongIndexedY)
Definition at line 551 of file cpu_test.cc.
TEST_F() [33/321]
yaze::test::emu::TEST_F (CpuTest , AND_AbsoluteIndexedY)
Definition at line 569 of file cpu_test.cc.
TEST_F() [34/321]
yaze::test::emu::TEST_F (CpuTest , AND_AbsoluteIndexedX)
Definition at line 591 of file cpu_test.cc.
TEST_F() [35/321]
yaze::test::emu::TEST_F (CpuTest , AND_AbsoluteLongIndexedX)
Definition at line 614 of file cpu_test.cc.
TEST_F() [36/321]
yaze::test::emu::TEST_F (CpuTest , ASL_DirectPage)
Definition at line 640 of file cpu_test.cc.
TEST_F() [37/321]
yaze::test::emu::TEST_F (CpuTest , ASL_Accumulator)
Definition at line 653 of file cpu_test.cc.
TEST_F() [38/321]
yaze::test::emu::TEST_F (CpuTest , ASL_Absolute)
Definition at line 666 of file cpu_test.cc.
TEST_F() [39/321]
yaze::test::emu::TEST_F (CpuTest , ASL_DirectPageIndexedX)
Definition at line 680 of file cpu_test.cc.
TEST_F() [40/321]
yaze::test::emu::TEST_F (CpuTest , ASL_AbsoluteIndexedX)
Definition at line 693 of file cpu_test.cc.
TEST_F() [41/321]
yaze::test::emu::TEST_F (CpuTest , BCC_WhenCarryFlagClear)
Definition at line 711 of file cpu_test.cc.
TEST_F() [42/321]
yaze::test::emu::TEST_F (CpuTest , BCC_WhenCarryFlagSet)
Definition at line 722 of file cpu_test.cc.
TEST_F() [43/321]
yaze::test::emu::TEST_F (CpuTest , BCS_WhenCarryFlagSet)
Definition at line 737 of file cpu_test.cc.
TEST_F() [44/321]
yaze::test::emu::TEST_F (CpuTest , BCS_WhenCarryFlagClear)
Definition at line 748 of file cpu_test.cc.
TEST_F() [45/321]
yaze::test::emu::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagSet)
Definition at line 760 of file cpu_test.cc.
TEST_F() [46/321]
yaze::test::emu::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagClear)
Definition at line 771 of file cpu_test.cc.
TEST_F() [47/321]
yaze::test::emu::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagSet_OverflowFlagSet)
Definition at line 783 of file cpu_test.cc.
TEST_F() [48/321]
yaze::test::emu::TEST_F (CpuTest , BEQ_Immediate_ZeroFlagClear_OverflowFlagSet)
Definition at line 796 of file cpu_test.cc.
TEST_F() [49/321]
yaze::test::emu::TEST_F (CpuTest , BIT_DirectPage)
Definition at line 812 of file cpu_test.cc.
TEST_F() [50/321]
yaze::test::emu::TEST_F (CpuTest , BIT_Absolute)
Definition at line 832 of file cpu_test.cc.
TEST_F() [51/321]
yaze::test::emu::TEST_F (CpuTest , BIT_DirectPageIndexedX)
Definition at line 851 of file cpu_test.cc.
TEST_F() [52/321]
yaze::test::emu::TEST_F (CpuTest , BIT_AbsoluteIndexedX)
Definition at line 872 of file cpu_test.cc.
TEST_F() [53/321]
yaze::test::emu::TEST_F (CpuTest , BIT_Immediate)
Definition at line 892 of file cpu_test.cc.
TEST_F() [54/321]
yaze::test::emu::TEST_F (CpuTest , BMI_BranchTaken)
Definition at line 914 of file cpu_test.cc.
TEST_F() [55/321]
yaze::test::emu::TEST_F (CpuTest , BMI_BranchNotTaken)
Definition at line 923 of file cpu_test.cc.
TEST_F() [56/321]
yaze::test::emu::TEST_F (CpuTest , BNE_BranchTaken)
Definition at line 935 of file cpu_test.cc.
TEST_F() [57/321]
yaze::test::emu::TEST_F (CpuTest , BNE_BranchNotTaken)
Definition at line 944 of file cpu_test.cc.
TEST_F() [58/321]
yaze::test::emu::TEST_F (CpuTest , BPL_BranchTaken)
Definition at line 956 of file cpu_test.cc.
TEST_F() [59/321]
yaze::test::emu::TEST_F (CpuTest , BPL_BranchNotTaken)
Definition at line 965 of file cpu_test.cc.
TEST_F() [60/321]
yaze::test::emu::TEST_F (CpuTest , BRA)
Definition at line 977 of file cpu_test.cc.
TEST_F() [61/321]
yaze::test::emu::TEST_F (CpuTest , BRK)
Definition at line 987 of file cpu_test.cc.
TEST_F() [62/321]
yaze::test::emu::TEST_F (CpuTest , BRL)
Definition at line 1002 of file cpu_test.cc.
TEST_F() [63/321]
yaze::test::emu::TEST_F (CpuTest , BVC_BranchTaken)
Definition at line 1015 of file cpu_test.cc.
TEST_F() [64/321]
yaze::test::emu::TEST_F (CpuTest , BVS_BranchTaken)
Definition at line 1027 of file cpu_test.cc.
TEST_F() [65/321]
yaze::test::emu::TEST_F (CpuTest , CLC)
Definition at line 1039 of file cpu_test.cc.
TEST_F() [66/321]
yaze::test::emu::TEST_F (CpuTest , CLD)
Definition at line 1052 of file cpu_test.cc.
TEST_F() [67/321]
yaze::test::emu::TEST_F (CpuTest , CLI)
Definition at line 1065 of file cpu_test.cc.
TEST_F() [68/321]
yaze::test::emu::TEST_F (CpuTest , CLV)
Definition at line 1078 of file cpu_test.cc.
TEST_F() [69/321]
yaze::test::emu::TEST_F (CpuTest , CMP_DirectPageIndexedIndirectX)
Definition at line 1091 of file cpu_test.cc.
TEST_F() [70/321]
yaze::test::emu::TEST_F (CpuTest , CMP_StackRelative)
Definition at line 1110 of file cpu_test.cc.
TEST_F() [71/321]
yaze::test::emu::TEST_F (CpuTest , CMP_DirectPage)
Definition at line 1142 of file cpu_test.cc.
TEST_F() [72/321]
yaze::test::emu::TEST_F (CpuTest , CMP_DirectPageIndirectLong)
Definition at line 1158 of file cpu_test.cc.
TEST_F() [73/321]
yaze::test::emu::TEST_F (CpuTest , CMP_Immediate_8Bit)
Definition at line 1181 of file cpu_test.cc.
TEST_F() [74/321]
yaze::test::emu::TEST_F (CpuTest , CMP_Absolute_16Bit)
Definition at line 1200 of file cpu_test.cc.
TEST_F() [75/321]
yaze::test::emu::TEST_F (CpuTest , CMP_AbsoluteLong)
Definition at line 1215 of file cpu_test.cc.
TEST_F() [76/321]
yaze::test::emu::TEST_F (CpuTest , CMP_DirectPageIndirect)
Definition at line 1232 of file cpu_test.cc.
TEST_F() [77/321]
yaze::test::emu::TEST_F (CpuTest , CMP_StackRelativeIndirectIndexedY)
Definition at line 1253 of file cpu_test.cc.
TEST_F() [78/321]
yaze::test::emu::TEST_F (CpuTest , CMP_DirectPageIndexedX)
Definition at line 1277 of file cpu_test.cc.
TEST_F() [79/321]
yaze::test::emu::TEST_F (CpuTest , CMP_DirectPageIndirectLongIndexedY)
Definition at line 1299 of file cpu_test.cc.
TEST_F() [80/321]
yaze::test::emu::TEST_F (CpuTest , CMP_AbsoluteIndexedY)
Definition at line 1321 of file cpu_test.cc.
TEST_F() [81/321]
yaze::test::emu::TEST_F (CpuTest , CMP_AbsoluteIndexedX)
Definition at line 1337 of file cpu_test.cc.
TEST_F() [82/321]
yaze::test::emu::TEST_F (CpuTest , CMP_AbsoluteLongIndexedX)
Definition at line 1353 of file cpu_test.cc.
TEST_F() [83/321]
yaze::test::emu::TEST_F (CpuTest , COP)
Todo
FIX COP TEST
Definition at line 1372 of file cpu_test.cc.
TEST_F() [84/321]
yaze::test::emu::TEST_F (CpuTest , CPX_Immediate_ZeroFlagSet)
Definition at line 1391 of file cpu_test.cc.
TEST_F() [85/321]
yaze::test::emu::TEST_F (CpuTest , CPX_Immediate_NegativeFlagSet)
Definition at line 1401 of file cpu_test.cc.
TEST_F() [86/321]
yaze::test::emu::TEST_F (CpuTest , CPX_DirectPage)
Definition at line 1412 of file cpu_test.cc.
TEST_F() [87/321]
yaze::test::emu::TEST_F (CpuTest , CPX_Absolute)
Definition at line 1422 of file cpu_test.cc.
TEST_F() [88/321]
yaze::test::emu::TEST_F (CpuTest , CPY_Immediate_ZeroFlagSet)
Definition at line 1432 of file cpu_test.cc.
TEST_F() [89/321]
yaze::test::emu::TEST_F (CpuTest , CPY_Immediate_NegativeFlagSet)
Definition at line 1442 of file cpu_test.cc.
TEST_F() [90/321]
yaze::test::emu::TEST_F (CpuTest , CPY_DirectPage)
Definition at line 1453 of file cpu_test.cc.
TEST_F() [91/321]
yaze::test::emu::TEST_F (CpuTest , CPY_Absolute)
Definition at line 1463 of file cpu_test.cc.
TEST_F() [92/321]
yaze::test::emu::TEST_F (CpuTest , DEC_Accumulator)
Definition at line 1476 of file cpu_test.cc.
TEST_F() [93/321]
yaze::test::emu::TEST_F (CpuTest , DEC_DirectPage)
Definition at line 1491 of file cpu_test.cc.
TEST_F() [94/321]
yaze::test::emu::TEST_F (CpuTest , DEC_Absolute)
Definition at line 1503 of file cpu_test.cc.
TEST_F() [95/321]
yaze::test::emu::TEST_F (CpuTest , DEC_DirectPageIndexedX)
Definition at line 1514 of file cpu_test.cc.
TEST_F() [96/321]
yaze::test::emu::TEST_F (CpuTest , DEC_AbsoluteIndexedX)
Definition at line 1527 of file cpu_test.cc.
TEST_F() [97/321]
yaze::test::emu::TEST_F (CpuTest , DEX)
Definition at line 1542 of file cpu_test.cc.
TEST_F() [98/321]
yaze::test::emu::TEST_F (CpuTest , DEY)
Definition at line 1560 of file cpu_test.cc.
TEST_F() [99/321]
yaze::test::emu::TEST_F (CpuTest , EOR_DirectPageIndexedIndirectX)
Definition at line 1578 of file cpu_test.cc.
TEST_F() [100/321]
yaze::test::emu::TEST_F (CpuTest , EOR_StackRelative)
Definition at line 1591 of file cpu_test.cc.
TEST_F() [101/321]
yaze::test::emu::TEST_F (CpuTest , EOR_DirectPage)
Definition at line 1607 of file cpu_test.cc.
TEST_F() [102/321]
yaze::test::emu::TEST_F (CpuTest , EOR_DirectPageIndirectLong)
Definition at line 1618 of file cpu_test.cc.
TEST_F() [103/321]
yaze::test::emu::TEST_F (CpuTest , EOR_Immediate_8bit)
Definition at line 1630 of file cpu_test.cc.
TEST_F() [104/321]
yaze::test::emu::TEST_F (CpuTest , EOR_Absolute)
Definition at line 1640 of file cpu_test.cc.
TEST_F() [105/321]
yaze::test::emu::TEST_F (CpuTest , EOR_AbsoluteLong)
Definition at line 1651 of file cpu_test.cc.
TEST_F() [106/321]
yaze::test::emu::TEST_F (CpuTest , EOR_DirectPageIndirectIndexedY)
Definition at line 1662 of file cpu_test.cc.
TEST_F() [107/321]
yaze::test::emu::TEST_F (CpuTest , EOR_DirectPageIndirect)
Definition at line 1675 of file cpu_test.cc.
TEST_F() [108/321]
yaze::test::emu::TEST_F (CpuTest , EOR_StackRelativeIndirectIndexedY)
Definition at line 1687 of file cpu_test.cc.
TEST_F() [109/321]
yaze::test::emu::TEST_F (CpuTest , EOR_DirectPageIndexedX)
Definition at line 1705 of file cpu_test.cc.
TEST_F() [110/321]
yaze::test::emu::TEST_F (CpuTest , EOR_DirectPageIndirectLongIndexedY)
Definition at line 1717 of file cpu_test.cc.
TEST_F() [111/321]
yaze::test::emu::TEST_F (CpuTest , EOR_AbsoluteIndexedY)
Definition at line 1730 of file cpu_test.cc.
TEST_F() [112/321]
yaze::test::emu::TEST_F (CpuTest , EOR_AbsoluteIndexedX)
Definition at line 1743 of file cpu_test.cc.
TEST_F() [113/321]
yaze::test::emu::TEST_F (CpuTest , EOR_AbsoluteLongIndexedX)
Definition at line 1756 of file cpu_test.cc.
TEST_F() [114/321]
yaze::test::emu::TEST_F (CpuTest , INC_Accumulator)
Definition at line 1772 of file cpu_test.cc.
TEST_F() [115/321]
yaze::test::emu::TEST_F (CpuTest , INC_DirectPage_8bit)
Definition at line 1787 of file cpu_test.cc.
TEST_F() [116/321]
yaze::test::emu::TEST_F (CpuTest , INC_Absolute_16bit)
Definition at line 1803 of file cpu_test.cc.
TEST_F() [117/321]
yaze::test::emu::TEST_F (CpuTest , INC_DirectPage_ZeroResult_8bit)
Definition at line 1815 of file cpu_test.cc.
TEST_F() [118/321]
yaze::test::emu::TEST_F (CpuTest , INC_Absolute_ZeroResult_16bit)
Definition at line 1827 of file cpu_test.cc.
TEST_F() [119/321]
yaze::test::emu::TEST_F (CpuTest , INC_DirectPage_8bit_Overflow)
Definition at line 1838 of file cpu_test.cc.
TEST_F() [120/321]
yaze::test::emu::TEST_F (CpuTest , INC_DirectPageIndexedX_8bit)
Definition at line 1848 of file cpu_test.cc.
TEST_F() [121/321]
yaze::test::emu::TEST_F (CpuTest , INC_AbsoluteIndexedX_16bit)
Definition at line 1864 of file cpu_test.cc.
TEST_F() [122/321]
yaze::test::emu::TEST_F (CpuTest , INX)
Definition at line 1876 of file cpu_test.cc.
TEST_F() [123/321]
yaze::test::emu::TEST_F (CpuTest , INY)
Definition at line 1891 of file cpu_test.cc.
TEST_F() [124/321]
yaze::test::emu::TEST_F (CpuTest , JMP_Absolute)
Definition at line 1909 of file cpu_test.cc.
TEST_F() [125/321]
yaze::test::emu::TEST_F (CpuTest , JMP_Indirect)
Definition at line 1921 of file cpu_test.cc.
TEST_F() [126/321]
yaze::test::emu::TEST_F (CpuTest , JML_AbsoluteLong)
Definition at line 1935 of file cpu_test.cc.
TEST_F() [127/321]
yaze::test::emu::TEST_F (CpuTest , JMP_AbsoluteIndexedIndirectX)
Definition at line 1949 of file cpu_test.cc.
TEST_F() [128/321]
yaze::test::emu::TEST_F (CpuTest , JMP_AbsoluteIndirectLong)
Definition at line 1962 of file cpu_test.cc.
TEST_F() [129/321]
yaze::test::emu::TEST_F (CpuTest , JSR_Absolute)
Definition at line 1978 of file cpu_test.cc.
TEST_F() [130/321]
yaze::test::emu::TEST_F (CpuTest , JSL_AbsoluteLong)
Definition at line 1996 of file cpu_test.cc.
TEST_F() [131/321]
yaze::test::emu::TEST_F (CpuTest , JSL_AbsoluteIndexedIndirect)
Definition at line 2007 of file cpu_test.cc.
TEST_F() [132/321]
yaze::test::emu::TEST_F (CpuTest , LDA_DirectPageIndexedIndirectX)
Definition at line 2023 of file cpu_test.cc.
TEST_F() [133/321]
yaze::test::emu::TEST_F (CpuTest , LDA_StackRelative)
Definition at line 2042 of file cpu_test.cc.
TEST_F() [134/321]
yaze::test::emu::TEST_F (CpuTest , LDA_DirectPage)
Definition at line 2060 of file cpu_test.cc.
TEST_F() [135/321]
yaze::test::emu::TEST_F (CpuTest , LDA_DirectPageIndirectLong)
Definition at line 2076 of file cpu_test.cc.
TEST_F() [136/321]
yaze::test::emu::TEST_F (CpuTest , LDA_Immediate_8bit)
Definition at line 2094 of file cpu_test.cc.
TEST_F() [137/321]
yaze::test::emu::TEST_F (CpuTest , LDA_Immediate_16bit)
Definition at line 2105 of file cpu_test.cc.
TEST_F() [138/321]
yaze::test::emu::TEST_F (CpuTest , LDA_Absolute)
Definition at line 2116 of file cpu_test.cc.
TEST_F() [139/321]
yaze::test::emu::TEST_F (CpuTest , LDA_AbsoluteLong)
Definition at line 2132 of file cpu_test.cc.
TEST_F() [140/321]
yaze::test::emu::TEST_F (CpuTest , LDA_DirectPageIndirectIndexedY)
Definition at line 2148 of file cpu_test.cc.
TEST_F() [141/321]
yaze::test::emu::TEST_F (CpuTest , LDA_DirectPageIndirect)
Definition at line 2168 of file cpu_test.cc.
TEST_F() [142/321]
yaze::test::emu::TEST_F (CpuTest , LDA_StackRelativeIndirectIndexedY)
Definition at line 2185 of file cpu_test.cc.
TEST_F() [143/321]
yaze::test::emu::TEST_F (CpuTest , LDA_DirectPageIndexedX)
Definition at line 2205 of file cpu_test.cc.
TEST_F() [144/321]
yaze::test::emu::TEST_F (CpuTest , LDA_DirectPageIndirectLongIndexedY)
Definition at line 2222 of file cpu_test.cc.
TEST_F() [145/321]
yaze::test::emu::TEST_F (CpuTest , LDA_AbsoluteIndexedY)
Definition at line 2241 of file cpu_test.cc.
TEST_F() [146/321]
yaze::test::emu::TEST_F (CpuTest , LDA_AbsoluteIndexedX)
Definition at line 2257 of file cpu_test.cc.
TEST_F() [147/321]
yaze::test::emu::TEST_F (CpuTest , LDA_AbsoluteLongIndexedX)
Definition at line 2273 of file cpu_test.cc.
TEST_F() [148/321]
yaze::test::emu::TEST_F (CpuTest , LDX_Immediate)
Definition at line 2291 of file cpu_test.cc.
TEST_F() [149/321]
yaze::test::emu::TEST_F (CpuTest , LDX_DirectPage)
Definition at line 2301 of file cpu_test.cc.
TEST_F() [150/321]
yaze::test::emu::TEST_F (CpuTest , LDX_Absolute)
Definition at line 2312 of file cpu_test.cc.
TEST_F() [151/321]
yaze::test::emu::TEST_F (CpuTest , LDX_DirectPageIndexedY)
Definition at line 2325 of file cpu_test.cc.
TEST_F() [152/321]
yaze::test::emu::TEST_F (CpuTest , LDX_AbsoluteIndexedY)
Definition at line 2337 of file cpu_test.cc.
TEST_F() [153/321]
yaze::test::emu::TEST_F (CpuTest , LDY_Immediate)
Definition at line 2353 of file cpu_test.cc.
TEST_F() [154/321]
yaze::test::emu::TEST_F (CpuTest , LDY_DirectPage)
Definition at line 2363 of file cpu_test.cc.
TEST_F() [155/321]
yaze::test::emu::TEST_F (CpuTest , LDY_Absolute)
Definition at line 2374 of file cpu_test.cc.
TEST_F() [156/321]
yaze::test::emu::TEST_F (CpuTest , LDY_DirectPageIndexedX)
Definition at line 2387 of file cpu_test.cc.
TEST_F() [157/321]
yaze::test::emu::TEST_F (CpuTest , LDY_AbsoluteIndexedX)
Definition at line 2399 of file cpu_test.cc.
TEST_F() [158/321]
yaze::test::emu::TEST_F (CpuTest , LSR_DirectPage)
Definition at line 2415 of file cpu_test.cc.
TEST_F() [159/321]
yaze::test::emu::TEST_F (CpuTest , LSR_Accumulator)
Definition at line 2427 of file cpu_test.cc.
TEST_F() [160/321]
yaze::test::emu::TEST_F (CpuTest , LSR_Absolute)
Definition at line 2436 of file cpu_test.cc.
TEST_F() [161/321]
yaze::test::emu::TEST_F (CpuTest , LSR_DirectPageIndexedX)
Definition at line 2450 of file cpu_test.cc.
TEST_F() [162/321]
yaze::test::emu::TEST_F (CpuTest , LSR_AbsoluteIndexedX)
Definition at line 2463 of file cpu_test.cc.
TEST_F() [163/321]
yaze::test::emu::TEST_F (CpuTest , ORA_DirectPageIndexedIndirectX)
Definition at line 2481 of file cpu_test.cc.
TEST_F() [164/321]
yaze::test::emu::TEST_F (CpuTest , ORA_StackRelative)
Definition at line 2500 of file cpu_test.cc.
TEST_F() [165/321]
yaze::test::emu::TEST_F (CpuTest , ORA_DirectPage)
Definition at line 2518 of file cpu_test.cc.
TEST_F() [166/321]
yaze::test::emu::TEST_F (CpuTest , ORA_DirectPageIndirectLong)
Definition at line 2534 of file cpu_test.cc.
TEST_F() [167/321]
yaze::test::emu::TEST_F (CpuTest , ORA_Immediate)
Definition at line 2552 of file cpu_test.cc.
TEST_F() [168/321]
yaze::test::emu::TEST_F (CpuTest , ORA_Absolute)
Definition at line 2563 of file cpu_test.cc.
TEST_F() [169/321]
yaze::test::emu::TEST_F (CpuTest , ORA_AbsoluteLong)
Definition at line 2579 of file cpu_test.cc.
TEST_F() [170/321]
yaze::test::emu::TEST_F (CpuTest , ORA_DirectPageIndirectIndexedY)
Definition at line 2595 of file cpu_test.cc.
TEST_F() [171/321]
yaze::test::emu::TEST_F (CpuTest , ORA_DirectPageIndirect)
Definition at line 2615 of file cpu_test.cc.
TEST_F() [172/321]
yaze::test::emu::TEST_F (CpuTest , ORA_StackRelativeIndirectIndexedY)
Definition at line 2632 of file cpu_test.cc.
TEST_F() [173/321]
yaze::test::emu::TEST_F (CpuTest , ORA_DirectPageIndexedX)
Definition at line 2652 of file cpu_test.cc.
TEST_F() [174/321]
yaze::test::emu::TEST_F (CpuTest , ORA_DirectPageIndirectLongIndexedY)
Definition at line 2669 of file cpu_test.cc.
TEST_F() [175/321]
yaze::test::emu::TEST_F (CpuTest , ORA_AbsoluteIndexedY)
Definition at line 2688 of file cpu_test.cc.
TEST_F() [176/321]
yaze::test::emu::TEST_F (CpuTest , ORA_AbsoluteIndexedX)
Definition at line 2704 of file cpu_test.cc.
TEST_F() [177/321]
yaze::test::emu::TEST_F (CpuTest , ORA_AbsoluteLongIndexedX)
Definition at line 2720 of file cpu_test.cc.
TEST_F() [178/321]
yaze::test::emu::TEST_F (CpuTest , PEA)
Definition at line 2738 of file cpu_test.cc.
TEST_F() [179/321]
yaze::test::emu::TEST_F (CpuTest , PEI)
Definition at line 2749 of file cpu_test.cc.
TEST_F() [180/321]
yaze::test::emu::TEST_F (CpuTest , PER)
Definition at line 2763 of file cpu_test.cc.
TEST_F() [181/321]
yaze::test::emu::TEST_F (CpuTest , PHD)
Definition at line 2774 of file cpu_test.cc.
TEST_F() [182/321]
yaze::test::emu::TEST_F (CpuTest , PHK)
Definition at line 2785 of file cpu_test.cc.
TEST_F() [183/321]
yaze::test::emu::TEST_F (CpuTest , PHP)
Definition at line 2796 of file cpu_test.cc.
TEST_F() [184/321]
yaze::test::emu::TEST_F (CpuTest , PHX)
Definition at line 2807 of file cpu_test.cc.
TEST_F() [185/321]
yaze::test::emu::TEST_F (CpuTest , PHY)
Definition at line 2818 of file cpu_test.cc.
TEST_F() [186/321]
yaze::test::emu::TEST_F (CpuTest , PHB)
Definition at line 2829 of file cpu_test.cc.
TEST_F() [187/321]
yaze::test::emu::TEST_F (CpuTest , PHA)
Definition at line 2840 of file cpu_test.cc.
TEST_F() [188/321]
yaze::test::emu::TEST_F (CpuTest , PHA_16Bit)
Definition at line 2851 of file cpu_test.cc.
TEST_F() [189/321]
yaze::test::emu::TEST_F (CpuTest , PLA)
Definition at line 2862 of file cpu_test.cc.
TEST_F() [190/321]
yaze::test::emu::TEST_F (CpuTest , PLA_16Bit)
Definition at line 2875 of file cpu_test.cc.
TEST_F() [191/321]
yaze::test::emu::TEST_F (CpuTest , PLB)
Definition at line 2888 of file cpu_test.cc.
TEST_F() [192/321]
yaze::test::emu::TEST_F (CpuTest , PLD)
Definition at line 2901 of file cpu_test.cc.
TEST_F() [193/321]
yaze::test::emu::TEST_F (CpuTest , PLP)
Definition at line 2914 of file cpu_test.cc.
TEST_F() [194/321]
yaze::test::emu::TEST_F (CpuTest , PLX)
Definition at line 2927 of file cpu_test.cc.
TEST_F() [195/321]
yaze::test::emu::TEST_F (CpuTest , PLX_16Bit)
Definition at line 2940 of file cpu_test.cc.
TEST_F() [196/321]
yaze::test::emu::TEST_F (CpuTest , PLY)
Definition at line 2954 of file cpu_test.cc.
TEST_F() [197/321]
yaze::test::emu::TEST_F (CpuTest , PLY_16Bit)
Definition at line 2967 of file cpu_test.cc.
TEST_F() [198/321]
yaze::test::emu::TEST_F (CpuTest , REP)
Definition at line 2983 of file cpu_test.cc.
TEST_F() [199/321]
yaze::test::emu::TEST_F (CpuTest , REP_16Bit)
Definition at line 2992 of file cpu_test.cc.
TEST_F() [200/321]
yaze::test::emu::TEST_F (CpuTest , PHA_PLA_Ok)
Definition at line 3001 of file cpu_test.cc.
TEST_F() [201/321]
yaze::test::emu::TEST_F (CpuTest , PHP_PLP_Ok)
Definition at line 3011 of file cpu_test.cc.
TEST_F() [202/321]
yaze::test::emu::TEST_F (CpuTest , PHA_PushAccumulator)
Definition at line 3039 of file cpu_test.cc.
TEST_F() [203/321]
yaze::test::emu::TEST_F (CpuTest , PHP_PushProcessorStatusRegister)
Definition at line 3045 of file cpu_test.cc.
TEST_F() [204/321]
yaze::test::emu::TEST_F (CpuTest , PHX_PushXRegister)
Definition at line 3051 of file cpu_test.cc.
TEST_F() [205/321]
yaze::test::emu::TEST_F (CpuTest , PHY_PushYRegister)
Definition at line 3057 of file cpu_test.cc.
TEST_F() [206/321]
yaze::test::emu::TEST_F (CpuTest , PHB_PushDataBankRegister)
Definition at line 3063 of file cpu_test.cc.
TEST_F() [207/321]
yaze::test::emu::TEST_F (CpuTest , PHD_PushDirectPageRegister)
Definition at line 3069 of file cpu_test.cc.
TEST_F() [208/321]
yaze::test::emu::TEST_F (CpuTest , PHK_PushProgramBankRegister)
Definition at line 3075 of file cpu_test.cc.
TEST_F() [209/321]
yaze::test::emu::TEST_F (CpuTest , PLA_PullAccumulator)
Definition at line 3085 of file cpu_test.cc.
TEST_F() [210/321]
yaze::test::emu::TEST_F (CpuTest , PLP_PullProcessorStatusRegister)
Definition at line 3091 of file cpu_test.cc.
TEST_F() [211/321]
yaze::test::emu::TEST_F (CpuTest , PLX_PullXRegister)
Definition at line 3097 of file cpu_test.cc.
TEST_F() [212/321]
yaze::test::emu::TEST_F (CpuTest , PLY_PullYRegister)
Definition at line 3103 of file cpu_test.cc.
TEST_F() [213/321]
yaze::test::emu::TEST_F (CpuTest , PLB_PullDataBankRegister)
Definition at line 3109 of file cpu_test.cc.
TEST_F() [214/321]
yaze::test::emu::TEST_F (CpuTest , PLD_PullDirectPageRegister)
Definition at line 3115 of file cpu_test.cc.
TEST_F() [215/321]
yaze::test::emu::TEST_F (CpuTest , SEP)
Definition at line 3124 of file cpu_test.cc.
TEST_F() [216/321]
yaze::test::emu::TEST_F (CpuTest , ROL_DirectPage)
Definition at line 3136 of file cpu_test.cc.
TEST_F() [217/321]
yaze::test::emu::TEST_F (CpuTest , ROL_Accumulator)
Definition at line 3148 of file cpu_test.cc.
TEST_F() [218/321]
yaze::test::emu::TEST_F (CpuTest , ROL_Absolute)
Definition at line 3157 of file cpu_test.cc.
TEST_F() [219/321]
yaze::test::emu::TEST_F (CpuTest , ROL_DirectPageIndexedX)
Definition at line 3171 of file cpu_test.cc.
TEST_F() [220/321]
yaze::test::emu::TEST_F (CpuTest , ROL_AbsoluteIndexedX)
Definition at line 3184 of file cpu_test.cc.
TEST_F() [221/321]
yaze::test::emu::TEST_F (CpuTest , ROR_DirectPage)
Definition at line 3201 of file cpu_test.cc.
TEST_F() [222/321]
yaze::test::emu::TEST_F (CpuTest , ROR_Accumulator)
Definition at line 3213 of file cpu_test.cc.
TEST_F() [223/321]
yaze::test::emu::TEST_F (CpuTest , ROR_Absolute)
Definition at line 3222 of file cpu_test.cc.
TEST_F() [224/321]
yaze::test::emu::TEST_F (CpuTest , ROR_DirectPageIndexedX)
Definition at line 3236 of file cpu_test.cc.
TEST_F() [225/321]
yaze::test::emu::TEST_F (CpuTest , ROR_AbsoluteIndexedX)
Definition at line 3249 of file cpu_test.cc.
TEST_F() [226/321]
yaze::test::emu::TEST_F (CpuTest , RTI)
Definition at line 3266 of file cpu_test.cc.
TEST_F() [227/321]
yaze::test::emu::TEST_F (CpuTest , RTL)
Definition at line 3281 of file cpu_test.cc.
TEST_F() [228/321]
yaze::test::emu::TEST_F (CpuTest , RTS)
Definition at line 3296 of file cpu_test.cc.
TEST_F() [229/321]
yaze::test::emu::TEST_F (CpuTest , SBC_DirectPageIndexedIndirectX)
Definition at line 3311 of file cpu_test.cc.
TEST_F() [230/321]
yaze::test::emu::TEST_F (CpuTest , SBC_StackRelative)
Definition at line 3332 of file cpu_test.cc.
TEST_F() [231/321]
yaze::test::emu::TEST_F (CpuTest , SBC_DirectPage)
Definition at line 3350 of file cpu_test.cc.
TEST_F() [232/321]
yaze::test::emu::TEST_F (CpuTest , SBC_DirectPageIndirectLong)
Definition at line 3367 of file cpu_test.cc.
TEST_F() [233/321]
yaze::test::emu::TEST_F (CpuTest , SBC_Immediate)
Definition at line 3387 of file cpu_test.cc.
TEST_F() [234/321]
yaze::test::emu::TEST_F (CpuTest , SBC_Absolute)
Definition at line 3400 of file cpu_test.cc.
TEST_F() [235/321]
yaze::test::emu::TEST_F (CpuTest , SBC_AbsoluteLong)
Definition at line 3416 of file cpu_test.cc.
TEST_F() [236/321]
yaze::test::emu::TEST_F (CpuTest , SBC_DirectPageIndirectIndexedY)
Definition at line 3432 of file cpu_test.cc.
TEST_F() [237/321]
yaze::test::emu::TEST_F (CpuTest , SBC_DirectPageIndirect)
Definition at line 3452 of file cpu_test.cc.
TEST_F() [238/321]
yaze::test::emu::TEST_F (CpuTest , SBC_StackRelativeIndirectIndexedY)
Definition at line 3474 of file cpu_test.cc.
TEST_F() [239/321]
yaze::test::emu::TEST_F (CpuTest , SBC_DirectPageIndexedX)
Definition at line 3496 of file cpu_test.cc.
TEST_F() [240/321]
yaze::test::emu::TEST_F (CpuTest , SBC_DirectPageIndirectLongIndexedY)
Definition at line 3510 of file cpu_test.cc.
TEST_F() [241/321]
yaze::test::emu::TEST_F (CpuTest , SBC_AbsoluteIndexedY)
Definition at line 3530 of file cpu_test.cc.
TEST_F() [242/321]
yaze::test::emu::TEST_F (CpuTest , SBC_AbsoluteIndexedX)
Definition at line 3547 of file cpu_test.cc.
TEST_F() [243/321]
yaze::test::emu::TEST_F (CpuTest , SBC_AbsoluteLongIndexedX)
Definition at line 3564 of file cpu_test.cc.
TEST_F() [244/321]
yaze::test::emu::TEST_F (CpuTest , SEC)
Definition at line 3583 of file cpu_test.cc.
TEST_F() [245/321]
yaze::test::emu::TEST_F (CpuTest , SED)
Definition at line 3590 of file cpu_test.cc.
TEST_F() [246/321]
yaze::test::emu::TEST_F (CpuTest , SEI)
Definition at line 3599 of file cpu_test.cc.
TEST_F() [247/321]
yaze::test::emu::TEST_F (CpuTest , SEP_8Bit)
Definition at line 3606 of file cpu_test.cc.
TEST_F() [248/321]
yaze::test::emu::TEST_F (CpuTest , SEP_16Bit)
Definition at line 3616 of file cpu_test.cc.
TEST_F() [249/321]
yaze::test::emu::TEST_F (CpuTest , STA_DirectPageIndexedIndirectX)
Definition at line 3628 of file cpu_test.cc.
TEST_F() [250/321]
yaze::test::emu::TEST_F (CpuTest , STA_StackRelative)
Definition at line 3645 of file cpu_test.cc.
TEST_F() [251/321]
yaze::test::emu::TEST_F (CpuTest , STA_DirectPage)
Definition at line 3659 of file cpu_test.cc.
TEST_F() [252/321]
yaze::test::emu::TEST_F (CpuTest , STA_DirectPageIndirectLong)
Definition at line 3670 of file cpu_test.cc.
TEST_F() [253/321]
yaze::test::emu::TEST_F (CpuTest , STA_Absolute)
Definition at line 3685 of file cpu_test.cc.
TEST_F() [254/321]
yaze::test::emu::TEST_F (CpuTest , STA_AbsoluteLong)
Definition at line 3696 of file cpu_test.cc.
TEST_F() [255/321]
yaze::test::emu::TEST_F (CpuTest , STA_DirectPageIndirectIndexedY)
Definition at line 3707 of file cpu_test.cc.
TEST_F() [256/321]
yaze::test::emu::TEST_F (CpuTest , STA_DirectPageIndirect)
Definition at line 3723 of file cpu_test.cc.
TEST_F() [257/321]
yaze::test::emu::TEST_F (CpuTest , STA_StackRelativeIndirectIndexedY)
Definition at line 3739 of file cpu_test.cc.
TEST_F() [258/321]
yaze::test::emu::TEST_F (CpuTest , STA_DirectPageIndexedX)
Definition at line 3756 of file cpu_test.cc.
TEST_F() [259/321]
yaze::test::emu::TEST_F (CpuTest , STA_DirectPageIndirectLongIndexedY)
Definition at line 3768 of file cpu_test.cc.
TEST_F() [260/321]
yaze::test::emu::TEST_F (CpuTest , STA_AbsoluteIndexedY)
Definition at line 3784 of file cpu_test.cc.
TEST_F() [261/321]
yaze::test::emu::TEST_F (CpuTest , STA_AbsoluteIndexedX)
Definition at line 3797 of file cpu_test.cc.
TEST_F() [262/321]
yaze::test::emu::TEST_F (CpuTest , STA_AbsoluteLongIndexedX)
Definition at line 3810 of file cpu_test.cc.
TEST_F() [263/321]
yaze::test::emu::TEST_F (CpuTest , STP)
Definition at line 3825 of file cpu_test.cc.
TEST_F() [264/321]
yaze::test::emu::TEST_F (CpuTest , STX_DirectPage)
Definition at line 3832 of file cpu_test.cc.
TEST_F() [265/321]
yaze::test::emu::TEST_F (CpuTest , STX_Absolute)
Definition at line 3843 of file cpu_test.cc.
TEST_F() [266/321]
yaze::test::emu::TEST_F (CpuTest , STX_DirectPageIndexedY)
Definition at line 3855 of file cpu_test.cc.
TEST_F() [267/321]
yaze::test::emu::TEST_F (CpuTest , STY_DirectPage)
Definition at line 3869 of file cpu_test.cc.
TEST_F() [268/321]
yaze::test::emu::TEST_F (CpuTest , STY_Absolute)
Definition at line 3880 of file cpu_test.cc.
TEST_F() [269/321]
yaze::test::emu::TEST_F (CpuTest , STY_DirectPageIndexedX)
Definition at line 3892 of file cpu_test.cc.
TEST_F() [270/321]
yaze::test::emu::TEST_F (CpuTest , STZ_DirectPage)
Definition at line 3906 of file cpu_test.cc.
TEST_F() [271/321]
yaze::test::emu::TEST_F (CpuTest , STZ_DirectPageIndexedX)
Definition at line 3916 of file cpu_test.cc.
TEST_F() [272/321]
yaze::test::emu::TEST_F (CpuTest , STZ_Absolute)
Definition at line 3927 of file cpu_test.cc.
TEST_F() [273/321]
yaze::test::emu::TEST_F (CpuTest , TAX)
Definition at line 3941 of file cpu_test.cc.
TEST_F() [274/321]
yaze::test::emu::TEST_F (CpuTest , TAY)
Definition at line 3953 of file cpu_test.cc.
TEST_F() [275/321]
yaze::test::emu::TEST_F (CpuTest , TCD)
Definition at line 3964 of file cpu_test.cc.
TEST_F() [276/321]
yaze::test::emu::TEST_F (CpuTest , TCS)
Definition at line 3976 of file cpu_test.cc.
TEST_F() [277/321]
yaze::test::emu::TEST_F (CpuTest , TDC)
Definition at line 3990 of file cpu_test.cc.
TEST_F() [278/321]
yaze::test::emu::TEST_F (CpuTest , TRB_DirectPage)
Definition at line 4002 of file cpu_test.cc.
TEST_F() [279/321]
yaze::test::emu::TEST_F (CpuTest , TRB_Absolute)
Definition at line 4016 of file cpu_test.cc.
TEST_F() [280/321]
yaze::test::emu::TEST_F (CpuTest , TSB_DirectPage)
Definition at line 4032 of file cpu_test.cc.
TEST_F() [281/321]
yaze::test::emu::TEST_F (CpuTest , TSB_Absolute)
Definition at line 4046 of file cpu_test.cc.
TEST_F() [282/321]
yaze::test::emu::TEST_F (CpuTest , TSC)
Definition at line 4062 of file cpu_test.cc.
TEST_F() [283/321]
yaze::test::emu::TEST_F (CpuTest , TSX)
Definition at line 4074 of file cpu_test.cc.
TEST_F() [284/321]
yaze::test::emu::TEST_F (CpuTest , TXA)
Definition at line 4087 of file cpu_test.cc.
TEST_F() [285/321]
yaze::test::emu::TEST_F (CpuTest , TXS)
Definition at line 4098 of file cpu_test.cc.
TEST_F() [286/321]
yaze::test::emu::TEST_F (CpuTest , TXY)
Definition at line 4110 of file cpu_test.cc.
TEST_F() [287/321]
yaze::test::emu::TEST_F (CpuTest , TYA)
Definition at line 4123 of file cpu_test.cc.
TEST_F() [288/321]
yaze::test::emu::TEST_F (CpuTest , TYX)
Definition at line 4135 of file cpu_test.cc.
TEST_F() [289/321]
yaze::test::emu::TEST_F (CpuTest , WAI)
Definition at line 4146 of file cpu_test.cc.
TEST_F() [290/321]
yaze::test::emu::TEST_F (CpuTest , WDM)
Definition at line 4153 of file cpu_test.cc.
TEST_F() [291/321]
yaze::test::emu::TEST_F (CpuTest , XBA)
Definition at line 4162 of file cpu_test.cc.
TEST_F() [292/321]
yaze::test::emu::TEST_F (CpuTest , XCESwitchToNativeMode)
Definition at line 4175 of file cpu_test.cc.
TEST_F() [293/321]
yaze::test::emu::TEST_F (CpuTest , XCESwitchToEmulationMode)
Definition at line 4181 of file cpu_test.cc.
TEST_F() [294/321]
yaze::test::emu::TEST_F (CpuTest , XCESwitchBackAndForth)
Definition at line 4187 of file cpu_test.cc.
TEST_F() [295/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_Immediate)
Definition at line 82 of file spc700_test.cc.
References yaze::app::emu::audio::Spc700::ExecuteInstructions().
TEST_F() [296/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_X)
Definition at line 97 of file spc700_test.cc.
TEST_F() [297/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_Y)
Definition at line 109 of file spc700_test.cc.
TEST_F() [298/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_dp)
Definition at line 121 of file spc700_test.cc.
TEST_F() [299/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_dp_plus_x)
Definition at line 139 of file spc700_test.cc.
TEST_F() [300/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_dp_indirect_plus_y)
Definition at line 158 of file spc700_test.cc.
TEST_F() [301/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_dp_plus_x_indirect)
Definition at line 179 of file spc700_test.cc.
TEST_F() [302/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_A_abs)
Definition at line 200 of file spc700_test.cc.
TEST_F() [303/321]
yaze::test::emu::TEST_F (Spc700Test , MOV_Immediate)
Definition at line 222 of file spc700_test.cc.
TEST_F() [304/321]
yaze::test::emu::TEST_F (Spc700Test , NOP_DoesNothing)
Definition at line 238 of file spc700_test.cc.
TEST_F() [305/321]
yaze::test::emu::TEST_F (Spc700Test , ADC_A_Immediate)
Definition at line 250 of file spc700_test.cc.
TEST_F() [306/321]
yaze::test::emu::TEST_F (Spc700Test , BEQ_BranchesIfZeroFlagSet)
Definition at line 266 of file spc700_test.cc.
TEST_F() [307/321]
yaze::test::emu::TEST_F (Spc700Test , STA_Absolute)
Definition at line 280 of file spc700_test.cc.
TEST_F() [308/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteADCWithImmediate)
Definition at line 294 of file spc700_test.cc.
TEST_F() [309/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteBRA)
Definition at line 310 of file spc700_test.cc.
TEST_F() [310/321]
yaze::test::emu::TEST_F (Spc700Test , ReadFromAudioRAM)
Definition at line 324 of file spc700_test.cc.
TEST_F() [311/321]
yaze::test::emu::TEST_F (Spc700Test , WriteToAudioRAM)
Definition at line 334 of file spc700_test.cc.
TEST_F() [312/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteANDWithImmediate)
Definition at line 343 of file spc700_test.cc.
TEST_F() [313/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteORWithImmediate)
Definition at line 358 of file spc700_test.cc.
TEST_F() [314/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteEORWithImmediate)
Definition at line 373 of file spc700_test.cc.
TEST_F() [315/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteINC)
Definition at line 388 of file spc700_test.cc.
TEST_F() [316/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteDEC)
Definition at line 400 of file spc700_test.cc.
TEST_F() [317/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteBNEWhenNotEqual)
Definition at line 412 of file spc700_test.cc.
TEST_F() [318/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteBNEWhenEqual)
Definition at line 426 of file spc700_test.cc.
TEST_F() [319/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteBEQWhenEqual)
Definition at line 440 of file spc700_test.cc.
TEST_F() [320/321]
yaze::test::emu::TEST_F (Spc700Test , ExecuteBEQWhenNotEqual)
Definition at line 454 of file spc700_test.cc.
TEST_F() [321/321]
yaze::test::emu::TEST_F (Spc700Test , BootIplRomOk)
Definition at line 468 of file spc700_test.cc.