yaze: yaze::zelda3::anonymous_namespace{overworld.cc} Namespace Reference
yaze::zelda3::anonymous_namespace{overworld.cc} Namespace Reference
Functions
std::vector< uint64_t > GetAllTile16 (OverworldMapTiles &map_tiles_)
bool CompareItemsArrays (std::vector< OverworldItem > item_array1, std::vector< OverworldItem > item_array2)
Function Documentation
GetAllTile16()
std::vector< uint64_t > yaze::zelda3::anonymous_namespace{overworld.cc}::GetAllTile16 (OverworldMapTiles & map_tiles_)
Definition at line 986 of file overworld.cc.
References yaze::zelda3::OverworldMapTiles::dark_world, GetAllTile16(), yaze::gfx::Tile32::GetPackedValue(), yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::OverworldMapTiles::light_world, and yaze::zelda3::OverworldMapTiles::special_world.
Referenced by GetAllTile16().
CompareItemsArrays()
bool yaze::zelda3::anonymous_namespace{overworld.cc}::CompareItemsArrays (std::vector< OverworldItem > item_array1, std::vector< OverworldItem > item_array2)
Definition at line 1439 of file overworld.cc.
References CompareItemsArrays().
Referenced by CompareItemsArrays().