yaze: yaze::app::editor::entity_internal Namespace Reference
yaze::app::editor::entity_internal Namespace Reference
Functions
bool IsMouseHoveringOverEntity (const zelda3::OverworldEntity &entity, ImVec2 canvas_p0, ImVec2 scrolling)
void MoveEntityOnGrid (zelda3::OverworldEntity *entity, ImVec2 canvas_p0, ImVec2 scrolling, bool free_movement=false)
void HandleEntityDragging (zelda3::OverworldEntity *entity, ImVec2 canvas_p0, ImVec2 scrolling, bool &is_dragging_entity, zelda3::OverworldEntity *&dragged_entity, zelda3::OverworldEntity *&current_entity, bool free_movement=false)
Function Documentation
IsMouseHoveringOverEntity()
bool yaze::app::editor::entity_internal::IsMouseHoveringOverEntity (const zelda3::OverworldEntity & entity, ImVec2 canvas_p0, ImVec2 scrolling)
References yaze::app::zelda3::OverworldEntity::x_, and yaze::app::zelda3::OverworldEntity::y_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), yaze::app::editor::OverworldEditor::DrawOverworldSprites(), and HandleEntityDragging().
MoveEntityOnGrid()
void yaze::app::editor::entity_internal::MoveEntityOnGrid (zelda3::OverworldEntity * entity, ImVec2 canvas_p0, ImVec2 scrolling, bool free_movement = false)
References yaze::app::zelda3::OverworldEntity::set_x(), and yaze::app::zelda3::OverworldEntity::set_y().
Referenced by HandleEntityDragging().
HandleEntityDragging()
void yaze::app::editor::entity_internal::HandleEntityDragging (zelda3::OverworldEntity * entity, ImVec2 canvas_p0, ImVec2 scrolling, bool & is_dragging_entity, zelda3::OverworldEntity *& dragged_entity, zelda3::OverworldEntity *& current_entity, bool free_movement = false)
References yaze::app::zelda3::OverworldEntity::entity_id_, IsMouseHoveringOverEntity(), yaze::app::zelda3::OverworldEntity::kEntrance, yaze::app::zelda3::OverworldEntity::kExit, yaze::app::zelda3::OverworldEntity::kItem, yaze::app::zelda3::OverworldEntity::kSprite, yaze::app::zelda3::OverworldEntity::map_id_, MoveEntityOnGrid(), yaze::app::zelda3::OverworldEntity::type_, yaze::app::zelda3::OverworldEntity::UpdateMapProperties(), yaze::app::core::UppercaseHexByte(), yaze::app::zelda3::OverworldEntity::x_, and yaze::app::zelda3::OverworldEntity::y_.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldEntrances(), yaze::app::editor::OverworldEditor::DrawOverworldExits(), yaze::app::editor::OverworldEditor::DrawOverworldItems(), and yaze::app::editor::OverworldEditor::DrawOverworldSprites().