yaze: yaze::app::emu::anonymous_namespace{snes.cc} Namespace Reference
yaze::app::emu::anonymous_namespace{snes.cc} Namespace Reference
Functions
uint16_t GetHeaderOffset (const Memory &memory)
void audio_callback (void *userdata, uint8_t *stream, int len)
Function Documentation
GetHeaderOffset()
uint16_t yaze::app::emu::anonymous_namespace{snes.cc}::GetHeaderOffset (const Memory & memory)
References GetHeaderOffset().
Referenced by GetHeaderOffset().
audio_callback()
void yaze::app::emu::anonymous_namespace{snes.cc}::audio_callback (void * userdata, uint8_t * stream, int len)
References audio_callback(), and yaze::app::emu::audio::Apu::GetNextSample().
Referenced by audio_callback().