yaze: yaze::cli::anonymous_namespace{z3ed.cc} Namespace Reference
yaze::cli::anonymous_namespace{z3ed.cc} Namespace Reference
Functions
void HelpCommand ()
int RunCommandHandler (int argc, char *argv[])
Function Documentation
HelpCommand()
void yaze::cli::anonymous_namespace{z3ed.cc}::HelpCommand ()
Definition at line 29 of file z3ed.cc.
References yaze::cli::FG_MAGENTA, yaze::cli::FG_RED, yaze::cli::FG_RESET, yaze::cli::FG_UNDERLINE, yaze::cli::FG_YELLOW, and HelpCommand().
Referenced by HelpCommand(), and RunCommandHandler().
RunCommandHandler()
int yaze::cli::anonymous_namespace{z3ed.cc}::RunCommandHandler (int argc, char * argv[])
Definition at line 65 of file z3ed.cc.
References yaze::cli::Commands::handlers, HelpCommand(), PRINT_IF_ERROR, and RunCommandHandler().
Referenced by RunCommandHandler().