yaze: generate-vs-projects Namespace Reference
generate-vs-projects Namespace Reference
Functions
generate_vcxproj ()
generate_solution ()
main ()
Function Documentation
generate_vcxproj()
generate-vs-projects.generate_vcxproj ()
Generate the YAZE.vcxproj file with all source files
Definition at line 11 of file generate-vs-projects.py.
Referenced by main().
generate_solution()
generate-vs-projects.generate_solution ()
Generate the YAZE.sln file
Definition at line 451 of file generate-vs-projects.py.
Referenced by main().
main()
generate-vs-projects.main ()
Main function to generate Visual Studio project files
Definition at line 508 of file generate-vs-projects.py.
References generate_solution(), generate_vcxproj(), and main().
Referenced by main().