yaze: yaze::test::gfx::anonymous_namespace{compression_test.cc} Namespace Reference
yaze::test::gfx::anonymous_namespace{compression_test.cc} Namespace Reference
Functions
std::vector< uint8_t > ExpectCompressOk (Rom &rom, uchar *in, int in_size)
std::vector< uint8_t > ExpectDecompressBytesOk (Rom &rom, std::vector< uint8_t > &in)
std::vector< uint8_t > ExpectDecompressOk (Rom &rom, uchar *in, int in_size)
std::shared_ptr< CompressionPiece > ExpectNewCompressionPieceOk (const char command, const int length, const std::string args, const int argument_length)
void AssertCompressionQuality (const std::vector< uint8_t > &uncompressed_data, const std::vector< uint8_t > &expected_compressed_data)
std::vector< uint8_t > ExpectCompressV3Ok (const std::vector< uint8_t > &uncompressed_data, const std::vector< uint8_t > &expected_compressed_data)
std::vector< uint8_t > CreateRepeatedBetweenUncompressable (int leftUncompressedSize, int repeatedByteSize, int rightUncompressedSize)
Function Documentation
ExpectCompressOk()
std::vector< uint8_t > yaze::test::gfx::anonymous_namespace{compression_test.cc}::ExpectCompressOk (Rom & rom, uchar * in, int in_size)
Definition at line 36 of file compression_test.cc.
References ExpectCompressOk(), yaze::app::Rom::LoadFromPointer(), and yaze::app::Rom::vector().
Referenced by ExpectCompressOk().
ExpectDecompressBytesOk()
std::vector< uint8_t > yaze::test::gfx::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk (Rom & rom, std::vector< uint8_t > & in)
Definition at line 45 of file compression_test.cc.
References yaze::app::Rom::data(), ExpectDecompressBytesOk(), and yaze::app::Rom::LoadFromBytes().
Referenced by ExpectDecompressBytesOk().
ExpectDecompressOk()
std::vector< uint8_t > yaze::test::gfx::anonymous_namespace{compression_test.cc}::ExpectDecompressOk (Rom & rom, uchar * in, int in_size)
Definition at line 55 of file compression_test.cc.
References yaze::app::Rom::data(), ExpectDecompressOk(), and yaze::app::Rom::LoadFromPointer().
Referenced by ExpectDecompressOk().
ExpectNewCompressionPieceOk()
std::shared_ptr< CompressionPiece > yaze::test::gfx::anonymous_namespace{compression_test.cc}::ExpectNewCompressionPieceOk (const char command, const int length, const std::string args, const int argument_length)
Definition at line 64 of file compression_test.cc.
References ExpectNewCompressionPieceOk().
Referenced by ExpectNewCompressionPieceOk().
AssertCompressionQuality()
void yaze::test::gfx::anonymous_namespace{compression_test.cc}::AssertCompressionQuality (const std::vector< uint8_t > & uncompressed_data, const std::vector< uint8_t > & expected_compressed_data)
Definition at line 74 of file compression_test.cc.
References AssertCompressionQuality().
Referenced by AssertCompressionQuality().
ExpectCompressV3Ok()
std::vector< uint8_t > yaze::test::gfx::anonymous_namespace{compression_test.cc}::ExpectCompressV3Ok (const std::vector< uint8_t > & uncompressed_data, const std::vector< uint8_t > & expected_compressed_data)
Definition at line 84 of file compression_test.cc.
References ExpectCompressV3Ok().
Referenced by ExpectCompressV3Ok().
CreateRepeatedBetweenUncompressable()
std::vector< uint8_t > yaze::test::gfx::anonymous_namespace{compression_test.cc}::CreateRepeatedBetweenUncompressable (int leftUncompressedSize, int repeatedByteSize, int rightUncompressedSize)
Definition at line 93 of file compression_test.cc.
References CreateRepeatedBetweenUncompressable().
Referenced by CreateRepeatedBetweenUncompressable().