yaze: yaze::app::editor::sprite_internal Namespace Reference
yaze::app::editor::sprite_internal Namespace Reference
Classes
struct SpriteItem
Enumerations
enum MyItemColumnID {
MyItemColumnID_ID , MyItemColumnID_Name , MyItemColumnID_Action , MyItemColumnID_Quantity ,
MyItemColumnID_Description
}
Functions
void DrawSpriteTable (std::function< void(int)> onSpriteSelect)
void DrawSpriteInserterPopup ()
bool DrawSpriteEditorPopup (zelda3::Sprite &sprite)
Enumeration Type Documentation
MyItemColumnID
enum yaze::app::editor::sprite_internal::MyItemColumnID
Enumerator
MyItemColumnID_ID
MyItemColumnID_Name
MyItemColumnID_Action
MyItemColumnID_Quantity
MyItemColumnID_Description
Function Documentation
DrawSpriteTable()
void yaze::app::editor::sprite_internal::DrawSpriteTable (std::function< void(int)> onSpriteSelect)
References MyItemColumnID_ID, MyItemColumnID_Name, and yaze::app::editor::sprite_internal::SpriteItem::SortWithSortSpecs().
Referenced by DrawSpriteEditorPopup(), and DrawSpriteInserterPopup().
DrawSpriteInserterPopup()
void yaze::app::editor::sprite_internal::DrawSpriteInserterPopup ()
Todo
Implement deleting OverworldSprite objects
References DrawSpriteTable(), ICON_MD_CANCEL, and ICON_MD_DONE.
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldSprites().
DrawSpriteEditorPopup()
bool yaze::app::editor::sprite_internal::DrawSpriteEditorPopup (zelda3::Sprite & sprite)
References DrawSpriteTable(), ICON_MD_CLOSE, ICON_MD_DELETE, ICON_MD_DONE, yaze::app::zelda3::Sprite::map_id(), yaze::app::zelda3::Sprite::Name(), yaze::app::zelda3::Sprite::set_deleted(), yaze::app::zelda3::Sprite::set_id(), and yaze::app::zelda3::Sprite::UpdateMapProperties().
Referenced by yaze::app::editor::OverworldEditor::DrawOverworldSprites().