yaze: src/ext/sample.c File Reference
sample.c File Reference
#include "ext/extension.h"
#include "yaze.h"
Functions
void my_extension_initialize ()
void my_extension_cleanup ()
void my_extension_manipulate_rom (z3_rom *rom)
yaze_extension * get_yaze_extension ()
Get the extension interface.
Function Documentation
my_extension_initialize()
void my_extension_initialize ()
Referenced by get_yaze_extension().
my_extension_cleanup()
void my_extension_cleanup ()
Referenced by get_yaze_extension().
my_extension_manipulate_rom()
void my_extension_manipulate_rom (z3_rom * rom)
Referenced by get_yaze_extension().
get_yaze_extension()
yaze_extension * get_yaze_extension ()
Get the extension interface.
References my_extension_cleanup(), my_extension_initialize(), and my_extension_manipulate_rom().