yaze: yaze::core::FlagsMenu Struct Reference
yaze::core::FlagsMenu Struct Reference
#include <features.h>
Public Member Functions
void DrawOverworldFlags ()
void DrawDungeonFlags ()
void DrawResourceFlags ()
void DrawSystemFlags ()
Detailed Description
Definition at line 106 of file features.h.
Member Function Documentation
DrawOverworldFlags()
void yaze::core::FlagsMenu::DrawOverworldFlags () inline
Definition at line 107 of file features.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
DrawDungeonFlags()
void yaze::core::FlagsMenu::DrawDungeonFlags () inline
Definition at line 125 of file features.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
DrawResourceFlags()
void yaze::core::FlagsMenu::DrawResourceFlags () inline
Definition at line 129 of file features.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
DrawSystemFlags()
void yaze::core::FlagsMenu::DrawSystemFlags () inline
Definition at line 135 of file features.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
The documentation for this struct was generated from the following file:
src/app/core/features.h