yaze: yaze::app::editor::FlagsMenu Struct Reference
yaze::app::editor::FlagsMenu Struct Reference
#include <flags.h>
Public Member Functions
void Draw ()
Public Member Functions inherited from yaze::app::core::ExperimentFlags
ExperimentFlags ()=default
virtual ~ExperimentFlags ()=default
auto flags () const
Flags * mutable_flags ()
Member Function Documentation
Draw()
void yaze::app::editor::FlagsMenu::Draw () inline
References yaze::app::core::ExperimentFlags::mutable_flags().
Referenced by yaze::app::editor::MasterEditor::DrawFileMenu(), and yaze::app::editor::SettingsEditor::Update().
The documentation for this struct was generated from the following file:
src/app/editor/utils/flags.h