yaze: yaze::app::emu::audio::ApuCallbacks Struct Reference
yaze::app::emu::audio::ApuCallbacks Struct Reference
#include <spc700.h>
Public Attributes
std::function< void(uint16_t, uint8_t)> write
std::function< uint8_t(uint16_t)> read
std::function< void(bool)> idle
Member Data Documentation
write
std::function<void(uint16_t, uint8_t)> yaze::app::emu::audio::ApuCallbacks::write
Referenced by yaze::app::emu::audio::Spc700::push_byte(), and yaze::app::emu::audio::Spc700::write().
read
std::function<uint8_t(uint16_t)> yaze::app::emu::audio::ApuCallbacks::read
Referenced by yaze::app::emu::audio::Spc700::read(), yaze::app::emu::audio::Spc700::read_word(), and yaze::app::emu::audio::Spc700::ReadOpcode().
idle
std::function<void(bool)> yaze::app::emu::audio::ApuCallbacks::idle
Referenced by yaze::app::emu::audio::Spc700::abs_x(), yaze::app::emu::audio::Spc700::abs_y(), yaze::app::emu::audio::Spc700::CMPM(), yaze::app::emu::audio::Spc700::DoBranch(), yaze::app::emu::audio::Spc700::dp_y(), yaze::app::emu::audio::Spc700::dpx(), yaze::app::emu::audio::Spc700::ExecuteInstructions(), yaze::app::emu::audio::Spc700::idx(), yaze::app::emu::audio::Spc700::idy(), and yaze::app::emu::audio::Spc700::RunOpcode().
The documentation for this struct was generated from the following file:
src/app/emu/audio/spc700.h