yaze: yaze::editor::FlagsMenu Struct Reference
yaze::editor::FlagsMenu Struct Reference
#include <flags.h>
Public Member Functions
void DrawOverworldFlags ()
void DrawDungeonFlags ()
void DrawResourceFlags ()
void DrawSystemFlags ()
Detailed Description
Definition at line 17 of file flags.h.
Member Function Documentation
DrawOverworldFlags()
void yaze::editor::FlagsMenu::DrawOverworldFlags () inline
Definition at line 18 of file flags.h.
References yaze::editor::ExperimentFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings(), and yaze::editor::EditorManager::DrawMenuContent().
DrawDungeonFlags()
void yaze::editor::FlagsMenu::DrawDungeonFlags () inline
Definition at line 36 of file flags.h.
References yaze::editor::ExperimentFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings(), and yaze::editor::EditorManager::DrawMenuContent().
DrawResourceFlags()
void yaze::editor::FlagsMenu::DrawResourceFlags () inline
Definition at line 43 of file flags.h.
References yaze::editor::ExperimentFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings(), and yaze::editor::EditorManager::DrawMenuContent().
DrawSystemFlags()
void yaze::editor::FlagsMenu::DrawSystemFlags () inline
Definition at line 50 of file flags.h.
References yaze::editor::ExperimentFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings(), and yaze::editor::EditorManager::DrawMenuContent().
The documentation for this struct was generated from the following file:
src/app/editor/system/flags.h