yaze: yaze::app::editor::ExampleAppPropertyEditor Struct Reference
yaze::app::editor::ExampleAppPropertyEditor Struct Reference
#include <settings_editor.h>
Public Member Functions
void Draw (ExampleTreeNode *root_node)
void DrawTreeNode (ExampleTreeNode *node)
Public Attributes
ImGuiTextFilter Filter
Member Function Documentation
Draw()
void yaze::app::editor::ExampleAppPropertyEditor::Draw (ExampleTreeNode * root_node) inline
References yaze::app::editor::ExampleTreeNode::Childs, DrawTreeNode(), and Filter.
DrawTreeNode()
void yaze::app::editor::ExampleAppPropertyEditor::DrawTreeNode (ExampleTreeNode * node) inline
References yaze::app::editor::ExampleTreeNode::Childs, DrawTreeNode(), yaze::app::editor::ExampleTreeNode::HasData, yaze::app::editor::ExampleTreeNode::Name, and yaze::app::editor::ExampleTreeNode::UID.
Referenced by Draw(), and DrawTreeNode().
Member Data Documentation
Filter
ImGuiTextFilter yaze::app::editor::ExampleAppPropertyEditor::Filter
Referenced by Draw().
The documentation for this struct was generated from the following file:
src/app/editor/settings_editor.h