yaze: yaze::app::editor::sprite_internal::SpriteItem Struct Reference
yaze::app::editor::sprite_internal::SpriteItem Struct Reference
Static Public Member Functions
static void SortWithSortSpecs (ImGuiTableSortSpecs *sort_specs, std::vector< SpriteItem > &items)
static bool CompareWithSortSpecs (const SpriteItem &a, const SpriteItem &b)
Public Attributes
int id
const char * name
Static Public Attributes
static const ImGuiTableSortSpecs * s_current_sort_specs = nullptr
Member Function Documentation
SortWithSortSpecs()
static void yaze::app::editor::sprite_internal::SpriteItem::SortWithSortSpecs (ImGuiTableSortSpecs * sort_specs, std::vector< SpriteItem > & items) inline static
References CompareWithSortSpecs(), and s_current_sort_specs.
Referenced by yaze::app::editor::sprite_internal::DrawSpriteTable().
CompareWithSortSpecs()
static bool yaze::app::editor::sprite_internal::SpriteItem::CompareWithSortSpecs (const SpriteItem & a, const SpriteItem & b) inline static
References id, yaze::app::editor::sprite_internal::MyItemColumnID_ID, yaze::app::editor::sprite_internal::MyItemColumnID_Name, name, and s_current_sort_specs.
Referenced by SortWithSortSpecs().
Member Data Documentation
id
int yaze::app::editor::sprite_internal::SpriteItem::id
Referenced by CompareWithSortSpecs().
name
const char* yaze::app::editor::sprite_internal::SpriteItem::name
Referenced by CompareWithSortSpecs().
s_current_sort_specs
const ImGuiTableSortSpecs * yaze::app::editor::sprite_internal::SpriteItem::s_current_sort_specs = nullptr static
Referenced by CompareWithSortSpecs(), and SortWithSortSpecs().
The documentation for this struct was generated from the following file:
src/app/editor/overworld_editor.cc