yaze: yaze::editor::ExampleAppPropertyEditor Struct Reference
yaze::editor::ExampleAppPropertyEditor Struct Reference
#include <settings_editor.h>
Public Member Functions
void Draw (ExampleTreeNode *root_node)
void DrawTreeNode (ExampleTreeNode *node)
Public Attributes
ImGuiTextFilter Filter
Detailed Description
Definition at line 85 of file settings_editor.h.
Member Function Documentation
Draw()
void yaze::editor::ExampleAppPropertyEditor::Draw (ExampleTreeNode * root_node) inline
Definition at line 88 of file settings_editor.h.
References yaze::editor::ExampleTreeNode::Childs, DrawTreeNode(), Filter, and yaze::editor::ExampleTreeNode::Name.
DrawTreeNode()
void yaze::editor::ExampleAppPropertyEditor::DrawTreeNode (ExampleTreeNode * node) inline
Definition at line 117 of file settings_editor.h.
References yaze::editor::ExampleTreeNode::Childs, DrawTreeNode(), yaze::editor::ExampleTreeNode::HasData, yaze::editor::ExampleTreeNode::Name, and yaze::editor::ExampleTreeNode::UID.
Referenced by Draw(), and DrawTreeNode().
Member Data Documentation
Filter
ImGuiTextFilter yaze::editor::ExampleAppPropertyEditor::Filter
Definition at line 86 of file settings_editor.h.
Referenced by Draw().
The documentation for this struct was generated from the following file:
src/app/editor/system/settings_editor.h