yaze: yaze::app::gfx::PaletteGroup Struct Reference
yaze::app::gfx::PaletteGroup Struct Reference
Represents a group of palettes.
#include <snes_palette.h>
Public Member Functions
PaletteGroup ()=default
PaletteGroup (uint8_t mSize)
absl::Status AddPalette (SnesPalette pal)
absl::Status AddColor (SnesColor color)
void Clear ()
auto name () const
auto size () const
auto mutable_palette (int i)
auto palette (int i) const
SnesPalette operator[] (int i)
const SnesPalette & operator[] (int i) const
absl::Status operator() (int i, const SnesColor &color)
absl::Status operator() (int i, const ImVec4 &color)
Private Attributes
int size_ = 0
std::string name_
std::vector< SnesPalette > palettes
Detailed Description
Represents a group of palettes.
Supports adding palettes and colors, clearing the group, and accessing palettes and colors by index.
Definition at line 213 of file snes_palette.h.
Constructor & Destructor Documentation
PaletteGroup() [1/2]
yaze::app::gfx::PaletteGroup::PaletteGroup () default
PaletteGroup() [2/2]
yaze::app::gfx::PaletteGroup::PaletteGroup (uint8_t mSize) explicit
Definition at line 334 of file snes_palette.cc.
Member Function Documentation
AddPalette()
absl::Status yaze::app::gfx::PaletteGroup::AddPalette (SnesPalette pal) inline
Definition at line 218 of file snes_palette.h.
References palettes, and size_.
Referenced by yaze::app::gfx::CreatePaletteGroupFromColFile(), yaze::app::gfx::CreatePaletteGroupFromLargePalette(), yaze::app::gfx::palette_group_internal::Load3DObjectPalettes(), yaze::app::gfx::palette_group_internal::LoadArmorPalettes(), yaze::app::gfx::palette_group_internal::LoadDungeonMainPalettes(), yaze::app::gfx::palette_group_internal::LoadGlobalSpritePalettes(), yaze::app::gfx::palette_group_internal::LoadHUDPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldAnimatedPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldMainPalettes(), yaze::app::gfx::palette_group_internal::LoadOverworldMiniMapPalettes(), yaze::app::gfx::palette_group_internal::LoadShieldPalettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux1Palettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux2Palettes(), yaze::app::gfx::palette_group_internal::LoadSpriteAux3Palettes(), and yaze::app::gfx::palette_group_internal::LoadSwordPalettes().
AddColor()
absl::Status yaze::app::gfx::PaletteGroup::AddColor (SnesColor color) inline
Definition at line 224 of file snes_palette.h.
References palettes, and size_.
Referenced by yaze::app::gfx::palette_group_internal::LoadGrassColors().
Clear()
void yaze::app::gfx::PaletteGroup::Clear () inline
Definition at line 232 of file snes_palette.h.
References palettes, and size_.
Referenced by yaze::app::editor::GraphicsEditor::DrawPaletteControls().
name()
auto yaze::app::gfx::PaletteGroup::name () const inline
Definition at line 237 of file snes_palette.h.
References name_.
size()
auto yaze::app::gfx::PaletteGroup::size () const inline
Definition at line 238 of file snes_palette.h.
References palettes.
Referenced by yaze::app::editor::GraphicsEditor::DrawPaletteControls(), and yaze::app::editor::PaletteEditor::DrawPaletteGroup().
mutable_palette()
auto yaze::app::gfx::PaletteGroup::mutable_palette (int i) inline
Definition at line 239 of file snes_palette.h.
References palettes.
Referenced by yaze::app::editor::PaletteEditor::DrawPaletteGroup(), and yaze::app::Rom::mutable_dungeon_palette().
palette()
auto yaze::app::gfx::PaletteGroup::palette (int i) const inline
Definition at line 240 of file snes_palette.h.
References palettes.
operator[]() [1/2]
SnesPalette yaze::app::gfx::PaletteGroup::operator[] (int i) inline
Definition at line 242 of file snes_palette.h.
References palettes, and size_.
operator[]() [2/2]
const SnesPalette & yaze::app::gfx::PaletteGroup::operator[] (int i) const inline
Definition at line 250 of file snes_palette.h.
References palettes, and size_.
operator()() [1/2]
absl::Status yaze::app::gfx::PaletteGroup::operator() (int i, const SnesColor & color) inline
Definition at line 258 of file snes_palette.h.
References palettes, and size_.
operator()() [2/2]
absl::Status yaze::app::gfx::PaletteGroup::operator() (int i, const ImVec4 & color) inline
Definition at line 266 of file snes_palette.h.
References palettes, and size_.
Member Data Documentation
size_
int yaze::app::gfx::PaletteGroup::size_ = 0 private
Definition at line 275 of file snes_palette.h.
Referenced by AddColor(), AddPalette(), Clear(), operator()(), operator()(), operator[](), and operator[]().
name_
std::string yaze::app::gfx::PaletteGroup::name_ private
Definition at line 276 of file snes_palette.h.
Referenced by name().
palettes
std::vector<SnesPalette> yaze::app::gfx::PaletteGroup::palettes private
Definition at line 277 of file snes_palette.h.
Referenced by AddColor(), AddPalette(), Clear(), mutable_palette(), operator()(), operator()(), operator[](), operator[](), palette(), and size().
The documentation for this struct was generated from the following files:
src/app/gfx/snes_palette.h
src/app/gfx/snes_palette.cc