yaze: yaze::app::editor::MemoryEditorWithDiffChecker Struct Reference
yaze::app::editor::MemoryEditorWithDiffChecker Struct Reference
#include <memory_editor.h>
Public Member Functions
void Update (bool &show_memory_editor)
Public Member Functions inherited from yaze::app::SharedRom
SharedRom ()=default
virtual ~SharedRom ()=default
std::shared_ptr< Rom > shared_rom ()
auto rom ()
Additional Inherited Members
Static Public Attributes inherited from yaze::app::SharedRom
static std::shared_ptr< Rom > shared_rom_ = nullptr
Detailed Description
Definition at line 41 of file memory_editor.h.
Member Function Documentation
Update()
void yaze::app::editor::MemoryEditorWithDiffChecker::Update (bool & show_memory_editor) inline
Definition at line 42 of file memory_editor.h.
References BEGIN_TABLE, END_TABLE, yaze::app::Rom::filename(), yaze::app::gui::InputHex(), yaze::app::Rom::LoadFromFile(), NEXT_COLUMN, PRINT_IF_ERROR, yaze::app::SharedRom::rom(), SETUP_COLUMN, yaze::app::core::FileDialogWrapper::ShowOpenFileDialog(), yaze::app::Rom::size(), and yaze::app::core::SnesToPc().
Referenced by yaze::app::editor::EditorManager::DrawYazeMenuBar().
The documentation for this struct was generated from the following file:
src/app/editor/code/memory_editor.h