yaze: yaze::app::emu::memory::CpuCallbacks Struct Reference
yaze::app::emu::memory::CpuCallbacks Struct Reference
#include <memory.h>
Public Attributes
std::function< uint8_t(uint32_t)> read_byte
std::function< void(uint32_t, uint8_t)> write_byte
std::function< void(bool waiting)> idle
Member Data Documentation
read_byte
std::function<uint8_t(uint32_t)> yaze::app::emu::memory::CpuCallbacks::read_byte
Referenced by yaze::app::emu::Cpu::ReadByte().
write_byte
std::function<void(uint32_t, uint8_t)> yaze::app::emu::memory::CpuCallbacks::write_byte
Referenced by yaze::app::emu::Cpu::PushByte(), yaze::app::emu::Cpu::WriteByte(), yaze::app::emu::Cpu::WriteLong(), and yaze::app::emu::Cpu::WriteWord().
idle
std::function<void(bool waiting)> yaze::app::emu::memory::CpuCallbacks::idle
Referenced by yaze::app::emu::Cpu::AdrAbx(), yaze::app::emu::Cpu::AdrAby(), yaze::app::emu::Cpu::AdrDp(), yaze::app::emu::Cpu::AdrDpx(), yaze::app::emu::Cpu::AdrDpy(), yaze::app::emu::Cpu::AdrIdl(), yaze::app::emu::Cpu::AdrIdp(), yaze::app::emu::Cpu::AdrIdx(), yaze::app::emu::Cpu::AdrIdy(), yaze::app::emu::Cpu::AdrIly(), yaze::app::emu::Cpu::AdrImp(), yaze::app::emu::Cpu::AdrIsy(), yaze::app::emu::Cpu::AdrSr(), yaze::app::emu::Cpu::Asl(), yaze::app::emu::Cpu::Dec(), yaze::app::emu::Cpu::DoBranch(), yaze::app::emu::Cpu::DoInterrupt(), yaze::app::emu::Cpu::ExecuteInstruction(), yaze::app::emu::Cpu::Inc(), yaze::app::emu::Cpu::Lsr(), yaze::app::emu::Cpu::Rol(), yaze::app::emu::Cpu::Ror(), yaze::app::emu::Cpu::RunOpcode(), yaze::app::emu::Cpu::Trb(), and yaze::app::emu::Cpu::Tsb().
The documentation for this struct was generated from the following file:
src/app/emu/memory/memory.h