yaze: yaze::app::editor::SpriteItem Struct Reference
yaze::app::editor::SpriteItem Struct Reference
#include <entity.h>
Static Public Member Functions
static void SortWithSortSpecs (ImGuiTableSortSpecs *sort_specs, std::vector< SpriteItem > &items)
static bool CompareWithSortSpecs (const SpriteItem &a, const SpriteItem &b)
Public Attributes
int id
const char * name
Static Public Attributes
static const ImGuiTableSortSpecs * s_current_sort_specs = nullptr
Detailed Description
Definition at line 44 of file entity.h.
Member Function Documentation
SortWithSortSpecs()
static void yaze::app::editor::SpriteItem::SortWithSortSpecs (ImGuiTableSortSpecs * sort_specs, std::vector< SpriteItem > & items) inline static
Definition at line 49 of file entity.h.
References CompareWithSortSpecs(), and s_current_sort_specs.
Referenced by yaze::app::editor::DrawSpriteTable().
CompareWithSortSpecs()
static bool yaze::app::editor::SpriteItem::CompareWithSortSpecs (const SpriteItem & a, const SpriteItem & b) inline static
Definition at line 58 of file entity.h.
References id, yaze::app::editor::MyItemColumnID_ID, yaze::app::editor::MyItemColumnID_Name, name, and s_current_sort_specs.
Referenced by SortWithSortSpecs().
Member Data Documentation
id
int yaze::app::editor::SpriteItem::id
Definition at line 45 of file entity.h.
Referenced by CompareWithSortSpecs().
name
const char* yaze::app::editor::SpriteItem::name
Definition at line 46 of file entity.h.
Referenced by CompareWithSortSpecs().
s_current_sort_specs
const ImGuiTableSortSpecs * yaze::app::editor::SpriteItem::s_current_sort_specs = nullptr static
Definition at line 47 of file entity.h.
Referenced by CompareWithSortSpecs(), and SortWithSortSpecs().
The documentation for this struct was generated from the following files:
src/app/editor/overworld/entity.h
src/app/editor/overworld/entity.cc