yaze: yaze::ResourceLabelManager Struct Reference
yaze::ResourceLabelManager Struct Reference
#include <project.h>
Classes
struct ResourceType
Public Member Functions
bool LoadLabels (const std::string &filename)
bool SaveLabels ()
void DisplayLabels (bool *p_open)
void EditLabel (const std::string &type, const std::string &key, const std::string &newValue)
void SelectableLabelWithNameEdit (bool selected, const std::string &type, const std::string &key, const std::string &defaultValue)
std::string GetLabel (const std::string &type, const std::string &key)
std::string CreateOrGetLabel (const std::string &type, const std::string &key, const std::string &defaultValue)
Public Attributes
bool labels_loaded_ = false
std::string filename_
std::unordered_map< std::string, std::unordered_map< std::string, std::string > > labels_
Detailed Description
Definition at line 60 of file project.h.
Member Function Documentation
LoadLabels()
bool yaze::ResourceLabelManager::LoadLabels (const std::string & filename)
Definition at line 64 of file project.cc.
References filename_, labels_, and labels_loaded_.
Referenced by yaze::Rom::LoadFromFile().
SaveLabels()
bool yaze::ResourceLabelManager::SaveLabels ()
Definition at line 93 of file project.cc.
References filename_, labels_, and labels_loaded_.
Referenced by DisplayLabels().
DisplayLabels()
void yaze::ResourceLabelManager::DisplayLabels (bool * p_open)
Definition at line 111 of file project.cc.
References labels_, labels_loaded_, and SaveLabels().
EditLabel()
void yaze::ResourceLabelManager::EditLabel (const std::string & type, const std::string & key, const std::string & newValue)
Definition at line 140 of file project.cc.
References labels_.
SelectableLabelWithNameEdit()
void yaze::ResourceLabelManager::SelectableLabelWithNameEdit (bool selected, const std::string & type, const std::string & key, const std::string & defaultValue)
Definition at line 146 of file project.cc.
References CreateOrGetLabel(), ICON_MD_CLOSE, and labels_.
GetLabel()
std::string yaze::ResourceLabelManager::GetLabel (const std::string & type, const std::string & key)
Definition at line 170 of file project.cc.
References labels_.
CreateOrGetLabel()
std::string yaze::ResourceLabelManager::CreateOrGetLabel (const std::string & type, const std::string & key, const std::string & defaultValue)
Definition at line 175 of file project.cc.
References labels_.
Referenced by SelectableLabelWithNameEdit(), and yaze::editor::OverworldEditor::UpdateUsageStats().
Member Data Documentation
labels_loaded_
bool yaze::ResourceLabelManager::labels_loaded_ = false
Definition at line 73 of file project.h.
Referenced by DisplayLabels(), LoadLabels(), and SaveLabels().
filename_
std::string yaze::ResourceLabelManager::filename_
Definition at line 74 of file project.h.
Referenced by LoadLabels(), and SaveLabels().
labels_
std::unordered_map<std::string, std::unordered_map<std::string, std::string> > yaze::ResourceLabelManager::labels_
Definition at line 81 of file project.h.
Referenced by CreateOrGetLabel(), DisplayLabels(), EditLabel(), GetLabel(), LoadLabels(), SaveLabels(), and SelectableLabelWithNameEdit().
The documentation for this struct was generated from the following files:
src/app/core/project.h
src/app/core/project.cc