yaze: src/test/yaze_test.cc File Reference
yaze_test.cc File Reference
#include "yaze.h"
#include <SDL.h>
#include <gtest/gtest.h>
#include "absl/debugging/failure_signal_handler.h"
#include "absl/debugging/symbolize.h"
#include "app/core/controller.h"
#include "app/core/platform/renderer.h"
#include "app/gui/style.h"
#include "imgui/backends/imgui_impl_sdl2.h"
#include "imgui/backends/imgui_impl_sdlrenderer2.h"
#include "imgui/imgui.h"
#include "imgui_test_engine/imgui_te_context.h"
#include "imgui_test_engine/imgui_te_engine.h"
#include "imgui_test_engine/imgui_te_imconfig.h"
#include "test/integration/test_editor.h"
Namespaces
namespace yaze
namespace yaze::test
Macros
#define SDL_MAIN_HANDLED
Functions
yaze::test::TEST (YazeCLibTest, InitializeAndCleanup)
int main (int argc, char *argv[])
Macro Definition Documentation
SDL_MAIN_HANDLED
#define SDL_MAIN_HANDLED
Definition at line 1 of file yaze_test.cc.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 33 of file yaze_test.cc.
References yaze::app::gui::ColorsYaze(), yaze::app::core::Controller::CreateRenderer(), yaze::app::core::Controller::CreateSDL_Window(), yaze::app::core::Controller::DoRender(), yaze::app::core::Renderer::GetInstance(), yaze::app::core::Controller::init_test_editor(), yaze::app::core::Controller::IsActive(), yaze::app::core::Controller::OnExit(), yaze::app::core::Controller::OnInput(), yaze::app::core::Controller::OnTestLoad(), yaze::test::integration::TestEditor::RegisterTests(), yaze::app::core::Renderer::renderer(), yaze::app::core::Controller::set_active(), and yaze::app::core::Controller::window().