yaze: src/yaze.cc File Reference
yaze.cc File Reference
#include "yaze.h"
#include <iostream>
#include <memory>
#include <sstream>
#include "app/core/platform/app_delegate.h"
#include "app/rom.h"
#include "app/zelda3/overworld/overworld.h"
#include "dungeon.h"
#include "util/flag.h"
#include "yaze_config.h"
Functions
int yaze_app_main (int argc, char **argv)
void yaze_check_version (const char *version)
yaze_status yaze_init (yaze_editor_context *yaze_ctx)
yaze_status yaze_shutdown (yaze_editor_context *yaze_ctx)
yaze_project yaze_load_project (const char *filename)
zelda3_rom * yaze_load_rom (const char *filename)
void yaze_unload_rom (zelda3_rom *rom)
void yaze_save_rom (zelda3_rom *rom, const char *filename)
yaze_bitmap yaze_load_bitmap (const char *filename)
snes_color yaze_get_color_from_paletteset (const zelda3_rom *rom, int palette_set, int palette, int color)
zelda3_overworld * yaze_load_overworld (const zelda3_rom *rom)
zelda3_dungeon_room * yaze_load_all_rooms (const zelda3_rom *rom)
Function Documentation
yaze_app_main()
int yaze_app_main (int argc, char ** argv)
Definition at line 14 of file yaze.cc.
References EXIT_IF_ERROR, yaze::util::global_flag_registry(), yaze::util::FlagParser::Parse(), and RETURN_IF_EXCEPTION.
yaze_check_version()
void yaze_check_version (const char * version)
Definition at line 40 of file yaze.cc.
yaze_init()
yaze_status yaze_init (yaze_editor_context * yaze_ctx)
Definition at line 54 of file yaze.cc.
References yaze_editor_context::error_message, yaze_editor_context::project, yaze_editor_context::rom, yaze_project::rom_filename, and yaze_load_rom().
yaze_shutdown()
yaze_status yaze_shutdown (yaze_editor_context * yaze_ctx)
Definition at line 69 of file yaze.cc.
References yaze_editor_context::rom, and yaze_unload_rom().
yaze_load_project()
yaze_project yaze_load_project (const char * filename)
Definition at line 76 of file yaze.cc.
References yaze_project::filepath.
yaze_load_rom()
zelda3_rom * yaze_load_rom (const char * filename)
Definition at line 82 of file yaze.cc.
References yaze::Rom::data(), zelda3_rom::data, zelda3_rom::filename, zelda3_rom::impl, yaze::Rom::LoadFromFile(), yaze::Rom::size(), and zelda3_rom::size.
Referenced by yaze_init().
yaze_unload_rom()
void yaze_unload_rom (zelda3_rom * rom)
Definition at line 98 of file yaze.cc.
References zelda3_rom::impl.
Referenced by yaze_shutdown().
yaze_save_rom()
void yaze_save_rom (zelda3_rom * rom, const char * filename)
Definition at line 108 of file yaze.cc.
References zelda3_rom::impl, and yaze::Rom::SaveToFile().
yaze_load_bitmap()
yaze_bitmap yaze_load_bitmap (const char * filename)
Definition at line 115 of file yaze.cc.
References yaze_bitmap::bpp, yaze_bitmap::data, yaze_bitmap::height, and yaze_bitmap::width.
yaze_get_color_from_paletteset()
snes_color yaze_get_color_from_paletteset (const zelda3_rom * rom, int palette_set, int palette, int color)
Definition at line 124 of file yaze.cc.
References snes_color::blue, snes_color::green, zelda3_rom::impl, yaze::gfx::kPaletteGroupAddressesKeys, yaze::Rom::palette_group(), and snes_color::red.
yaze_load_overworld()
zelda3_overworld * yaze_load_overworld (const zelda3_rom * rom)
Definition at line 150 of file yaze.cc.
References zelda3_overworld_map::id, zelda3_overworld::impl, zelda3_rom::impl, and zelda3_overworld::maps.
yaze_load_all_rooms()
zelda3_dungeon_room * yaze_load_all_rooms (const zelda3_rom * rom)
Definition at line 172 of file yaze.cc.
References zelda3_rom::impl.