yaze: src/py/yaze_py.cc File Reference
yaze_py.cc File Reference
#include <boost/python.hpp>
#include "base/overworld.h"
#include "base/snes_color.h"
#include "base/sprite.h"
#include "base/extension.h"
#include "yaze.h"
Classes
class PythonYazeExtensionWrapper
Functions
BOOST_PYTHON_MODULE (yaze_py)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (yaze_py)
Definition at line 118 of file yaze_py.cc.
References z3_sprite::actions, snes_color::blue, snes_palette::colors, z3_rom::data, yaze_flags::debug, yaze_project::filename, z3_rom::filename, PythonYazeExtensionWrapper::getExtension(), PythonYazeExtensionWrapper::getName(), PythonYazeExtensionWrapper::getVersion(), snes_color::green, snes_palette::id, z3_sprite::id, z3_sprite_action::id, z3_rom::impl, yaze_extension::name, z3_sprite::name, z3_sprite_action::name, yaze_project::overworld, yaze_editor_context::project, snes_color::red, yaze_flags::rom, yaze_project::rom, yaze_flags::rom_filename, PythonYazeExtensionWrapper::setCleanup(), PythonYazeExtensionWrapper::setExtendUI(), PythonYazeExtensionWrapper::setInitialize(), PythonYazeExtensionWrapper::setManipulateRom(), PythonYazeExtensionWrapper::setName(), PythonYazeExtensionWrapper::setRegisterCommands(), PythonYazeExtensionWrapper::setRegisterCustomTools(), PythonYazeExtensionWrapper::setRegisterEventHooks(), PythonYazeExtensionWrapper::setVersion(), snes_palette::size, z3_rom::size, yaze_extension::version, yaze_check_version(), YAZE_EVENT_PALETTE_CHANGED, YAZE_EVENT_ROM_LOADED, YAZE_EVENT_ROM_SAVED, YAZE_EVENT_SPRITE_MODIFIED, yaze_get_color_from_paletteset(), yaze_load_rom(), and yaze_unload_rom().