yaze: src/cli/z3ed.cc File Reference
z3ed.cc File Reference
#include "cli/z3ed.h"
#include <cstring>
#include <iostream>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>
#include "cli/tui.h"
#include "util/flag.h"
#include "util/macro.h"
Namespaces
namespace yaze
Main namespace for the application.
namespace yaze::cli
Namespace for the command line interface.
namespace yaze::cli::anonymous_namespace{z3ed.cc}
Functions
DECLARE_FLAG (std::string, rom_file)
DECLARE_FLAG (std::string, bps_file)
DECLARE_FLAG (std::string, src_file)
DECLARE_FLAG (std::string, modified_file)
DECLARE_FLAG (std::string, bin_file)
DECLARE_FLAG (std::string, address)
DECLARE_FLAG (std::string, length)
DECLARE_FLAG (std::string, file_size)
DECLARE_FLAG (std::string, dest_rom)
DECLARE_FLAG (std::string, tile32_id_list)
DEFINE_FLAG (std::string, rom_file, "", "The ROM file to load.")
DEFINE_FLAG (std::string, bps_file, "", "The BPS file to apply.")
DEFINE_FLAG (std::string, src_file, "", "The source file.")
DEFINE_FLAG (std::string, modified_file, "", "The modified file.")
DEFINE_FLAG (std::string, bin_file, "", "The binary file to export to.")
DEFINE_FLAG (std::string, address, "", "The address to convert.")
DEFINE_FLAG (std::string, length, "", "The length of the data to read.")
DEFINE_FLAG (std::string, file_size, "", "The size of the file to expand to.")
DEFINE_FLAG (std::string, dest_rom, "", "The destination ROM file.")
DEFINE_FLAG (std::string, tile32_id_list, "", "The list of tile32 IDs to transfer.")
int yaze::cli::anonymous_namespace{z3ed.cc}::RunCommandHandler (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
DECLARE_FLAG() [1/10]
DECLARE_FLAG (std::string , rom_file)
DECLARE_FLAG() [2/10]
DECLARE_FLAG (std::string , bps_file)
DECLARE_FLAG() [3/10]
DECLARE_FLAG (std::string , src_file)
DECLARE_FLAG() [4/10]
DECLARE_FLAG (std::string , modified_file)
DECLARE_FLAG() [5/10]
DECLARE_FLAG (std::string , bin_file)
DECLARE_FLAG() [6/10]
DECLARE_FLAG (std::string , address)
DECLARE_FLAG() [7/10]
DECLARE_FLAG (std::string , length)
DECLARE_FLAG() [8/10]
DECLARE_FLAG (std::string , file_size)
DECLARE_FLAG() [9/10]
DECLARE_FLAG (std::string , dest_rom)
DECLARE_FLAG() [10/10]
DECLARE_FLAG (std::string , tile32_id_list)
DEFINE_FLAG() [1/10]
DEFINE_FLAG (std::string , rom_file , "" , "The ROM file to load.")
DEFINE_FLAG() [2/10]
DEFINE_FLAG (std::string , bps_file , "" , "The BPS file to apply.")
DEFINE_FLAG() [3/10]
DEFINE_FLAG (std::string , src_file , "" , "The source file.")
DEFINE_FLAG() [4/10]
DEFINE_FLAG (std::string , modified_file , "" , "The modified file.")
DEFINE_FLAG() [5/10]
DEFINE_FLAG (std::string , bin_file , "" , "The binary file to export to.")
DEFINE_FLAG() [6/10]
DEFINE_FLAG (std::string , address , "" , "The address to convert.")
DEFINE_FLAG() [7/10]
DEFINE_FLAG (std::string , length , "" , "The length of the data to read.")
DEFINE_FLAG() [8/10]
DEFINE_FLAG (std::string , file_size , "" , "The size of the file to expand to.")
DEFINE_FLAG() [9/10]
DEFINE_FLAG (std::string , dest_rom , "" , "The destination ROM file.")
DEFINE_FLAG() [10/10]
DEFINE_FLAG (std::string , tile32_id_list , "" , "The list of tile32 IDs to transfer.")
main()
int main (int argc, char * argv[])
Definition at line 69 of file z3ed.cc.
References yaze::util::global_flag_registry(), yaze::util::Flag< T >::name(), yaze::util::FlagParser::Parse(), RETURN_IF_EXCEPTION, and yaze::cli::ShowMain().