yaze: incl/zelda.h File Reference
zelda.h File Reference
#include <stdint.h>
#include <stdbool.h>
Classes
struct zelda3_version_pointers
Pointers for each version of the game.
struct zelda3_rom
struct zelda3_overworld_map
Primitive of an overworld map.
struct zelda3_overworld
Primitive of the overworld.
struct dungeon_sprite
struct object_door
struct staircase
struct chest
struct chest_data
struct destination
struct zelda3_dungeon_room
Typedefs
typedef struct zelda3_rom zelda3_rom
typedef struct zelda3_overworld_map zelda3_overworld_map
Primitive of an overworld map.
typedef struct zelda3_overworld zelda3_overworld
Primitive of the overworld.
typedef struct dungeon_sprite dungeon_sprite
typedef enum background2 background2
typedef struct object_door object_door
typedef struct staircase staircase
typedef struct chest chest
typedef struct chest_data chest_data
typedef struct destination destination
typedef struct zelda3_dungeon_room zelda3_dungeon_room
Enumerations
enum zelda3_version { US = 1 , JP = 2 , SD = 3 , RANDO = 4 }
Different versions of the game supported by yaze.
enum background2 {
Off , Parallax , Dark , OnTop ,
Translucent , Addition , Normal , Transparent ,
DarkRoom
}
Functions
zelda3_rom * yaze_load_rom (const char *filename)
void yaze_unload_rom (zelda3_rom *rom)
void yaze_save_rom (zelda3_rom *rom, const char *filename)
Typedef Documentation
zelda3_rom
typedef struct zelda3_rom zelda3_rom
zelda3_overworld_map
typedef struct zelda3_overworld_map zelda3_overworld_map
Primitive of an overworld map.
zelda3_overworld
typedef struct zelda3_overworld zelda3_overworld
Primitive of the overworld.
dungeon_sprite
typedef struct dungeon_sprite dungeon_sprite
background2
typedef enum background2 background2
object_door
typedef struct object_door object_door
staircase
typedef struct staircase staircase
chest
typedef struct chest chest
chest_data
typedef struct chest_data chest_data
destination
typedef struct destination destination
zelda3_dungeon_room
typedef struct zelda3_dungeon_room zelda3_dungeon_room
Enumeration Type Documentation
zelda3_version
enum zelda3_version
Different versions of the game supported by yaze.
Enumerator
US
JP
SD
RANDO
Definition at line 14 of file zelda.h.
background2
enum background2
Enumerator
Off
Parallax
Dark
OnTop
Translucent
Addition
Normal
Transparent
DarkRoom
Definition at line 130 of file zelda.h.
Function Documentation
yaze_load_rom()
zelda3_rom * yaze_load_rom (const char * filename)
Definition at line 86 of file yaze.cc.
References yaze::Rom::data(), zelda3_rom::data, zelda3_rom::filename, zelda3_rom::impl, yaze::Rom::LoadFromFile(), yaze::Rom::size(), and zelda3_rom::size.
Referenced by yaze_init().
yaze_unload_rom()
void yaze_unload_rom (zelda3_rom * rom)
Definition at line 102 of file yaze.cc.
References zelda3_rom::impl.
Referenced by yaze_shutdown().
yaze_save_rom()
void yaze_save_rom (zelda3_rom * rom, const char * filename)
Definition at line 112 of file yaze.cc.
References zelda3_rom::impl, and yaze::Rom::SaveToFile().