yaze: yaze::cli::OllamaAIService Class Reference
yaze::cli::OllamaAIService Class Reference
#include <ollama_ai_service.h>
Public Member Functions
OllamaAIService (const OllamaConfig &config)
void SetRomContext (Rom *rom) override
absl::StatusOr< AgentResponse > GenerateResponse (const std::string &prompt) override
absl::StatusOr< AgentResponse > GenerateResponse (const std::vector< agent::ChatMessage > &history) override
absl::Status CheckAvailability ()
absl::StatusOr< std::vector< std::string > > ListAvailableModels ()
Public Member Functions inherited from yaze::cli::AIService
virtual ~AIService ()=default
Private Member Functions
std::string BuildSystemPrompt ()
absl::StatusOr< std::string > ParseOllamaResponse (const std::string &json_response)
Private Attributes
OllamaConfig config_
PromptBuilder prompt_builder_
Detailed Description
Definition at line 25 of file ollama_ai_service.h.
Constructor & Destructor Documentation
OllamaAIService()
yaze::cli::OllamaAIService::OllamaAIService (const OllamaConfig & config) explicit
Definition at line 35 of file ollama_ai_service.cc.
References yaze::cli::PromptBuilder::BuildSystemInstructionWithExamples(), BuildSystemPrompt(), config_, yaze::cli::PromptBuilder::LoadResourceCatalogue(), prompt_builder_, yaze::cli::OllamaConfig::system_prompt, and yaze::cli::OllamaConfig::use_enhanced_prompting.
Member Function Documentation
SetRomContext()
void yaze::cli::OllamaAIService::SetRomContext (Rom * rom) override virtual
Reimplemented from yaze::cli::AIService.
Definition at line 58 of file ollama_ai_service.cc.
References prompt_builder_, and yaze::cli::PromptBuilder::SetRom().
GenerateResponse() [1/2]
absl::StatusOr< AgentResponse > yaze::cli::OllamaAIService::GenerateResponse (const std::string & prompt) override virtual
Implements yaze::cli::AIService.
Definition at line 176 of file ollama_ai_service.cc.
References GenerateResponse(), and yaze::cli::agent::ChatMessage::kUser.
Referenced by GenerateResponse().
GenerateResponse() [2/2]
absl::StatusOr< AgentResponse > yaze::cli::OllamaAIService::GenerateResponse (const std::vector< agent::ChatMessage > & history) override virtual
Implements yaze::cli::AIService.
Definition at line 181 of file ollama_ai_service.cc.
References yaze::cli::ToolCall::args, yaze::cli::OllamaConfig::base_url, yaze::cli::PromptBuilder::BuildPromptFromHistory(), yaze::cli::AgentResponse::commands, config_, yaze::cli::OllamaConfig::max_tokens, yaze::cli::OllamaConfig::model, prompt_builder_, yaze::cli::AgentResponse::reasoning, yaze::cli::OllamaConfig::system_prompt, yaze::cli::OllamaConfig::temperature, yaze::cli::AgentResponse::text_response, yaze::cli::AgentResponse::tool_calls, and yaze::cli::ToolCall::tool_name.
CheckAvailability()
absl::Status yaze::cli::OllamaAIService::CheckAvailability ()
Definition at line 62 of file ollama_ai_service.cc.
References yaze::cli::OllamaConfig::base_url, config_, and yaze::cli::OllamaConfig::model.
ListAvailableModels()
absl::StatusOr< std::vector< std::string > > yaze::cli::OllamaAIService::ListAvailableModels ()
Definition at line 121 of file ollama_ai_service.cc.
References yaze::cli::OllamaConfig::base_url, and config_.
BuildSystemPrompt()
std::string yaze::cli::OllamaAIService::BuildSystemPrompt () private
Definition at line 52 of file ollama_ai_service.cc.
References yaze::cli::PromptBuilder::BuildSystemInstruction(), and prompt_builder_.
Referenced by OllamaAIService().
ParseOllamaResponse()
absl::StatusOr< std::string > yaze::cli::OllamaAIService::ParseOllamaResponse (const std::string & json_response) private
Definition at line 155 of file ollama_ai_service.cc.
Member Data Documentation
config_
OllamaConfig yaze::cli::OllamaAIService::config_ private
Definition at line 44 of file ollama_ai_service.h.
Referenced by CheckAvailability(), GenerateResponse(), ListAvailableModels(), and OllamaAIService().
prompt_builder_
PromptBuilder yaze::cli::OllamaAIService::prompt_builder_ private
Definition at line 45 of file ollama_ai_service.h.
Referenced by BuildSystemPrompt(), GenerateResponse(), OllamaAIService(), and SetRomContext().
The documentation for this class was generated from the following files:
src/cli/service/ai/ollama_ai_service.h
src/cli/service/ai/ollama_ai_service.cc