yaze: yaze::gui::BppComparisonTool Class Reference
yaze::gui::BppComparisonTool Class Reference
BPP format comparison tool.
#include <bpp_format_ui.h>
Public Member Functions
BppComparisonTool (const std::string &id)
Constructor.
void SetSource (const gfx::Bitmap &bitmap, const gfx::SnesPalette &palette)
Set source bitmap for comparison.
void Render ()
Render the comparison tool.
bool IsOpen () const
Check if tool is open.
void Open ()
Open the tool.
void Close ()
Close the tool.
Private Member Functions
void GenerateComparisons ()
void RenderComparisonGrid ()
void RenderMetrics ()
void RenderFormatSelector ()
std::string CalculateMetrics (gfx::BppFormat format) const
Private Attributes
std::string id_
bool is_open_
gfx::Bitmap source_bitmap_
gfx::SnesPalette source_palette_
bool has_source_
std::unordered_map< gfx::BppFormat, gfx::Bitmap > comparison_bitmaps_
std::unordered_map< gfx::BppFormat, gfx::SnesPalette > comparison_palettes_
std::unordered_map< gfx::BppFormat, bool > comparison_valid_
float comparison_scale_
bool show_metrics_
gfx::BppFormat selected_comparison_
Detailed Description
BPP format comparison tool.
Definition at line 182 of file bpp_format_ui.h.
Constructor & Destructor Documentation
BppComparisonTool()
yaze::gui::BppComparisonTool::BppComparisonTool (const std::string & id) explicit
Constructor.
Parameters
id Unique identifier
Definition at line 498 of file bpp_format_ui.cc.
Member Function Documentation
SetSource()
void yaze::gui::BppComparisonTool::SetSource (const gfx::Bitmap & bitmap, const gfx::SnesPalette & palette)
Set source bitmap for comparison.
Parameters
bitmap Source bitmap
palette Source palette
Definition at line 503 of file bpp_format_ui.cc.
References GenerateComparisons(), has_source_, source_bitmap_, and source_palette_.
Render()
void yaze::gui::BppComparisonTool::Render ()
Render the comparison tool.
Definition at line 510 of file bpp_format_ui.cc.
References has_source_, is_open_, RenderComparisonGrid(), RenderFormatSelector(), RenderMetrics(), and show_metrics_.
IsOpen()
bool yaze::gui::BppComparisonTool::IsOpen () const inline
Check if tool is open.
Returns
True if tool is open
Definition at line 206 of file bpp_format_ui.h.
References is_open_.
Open()
void yaze::gui::BppComparisonTool::Open () inline
Open the tool.
Definition at line 211 of file bpp_format_ui.h.
References is_open_.
Close()
void yaze::gui::BppComparisonTool::Close () inline
Close the tool.
Definition at line 216 of file bpp_format_ui.h.
References is_open_.
GenerateComparisons()
void yaze::gui::BppComparisonTool::GenerateComparisons () private
Definition at line 527 of file bpp_format_ui.cc.
References comparison_bitmaps_, comparison_palettes_, comparison_valid_, yaze::gfx::BppFormatManager::ConvertFormat(), yaze::gfx::Bitmap::depth(), yaze::gfx::BppFormatManager::DetectFormat(), yaze::gfx::BppFormatManager::Get(), yaze::gfx::BppFormatManager::GetAvailableFormats(), yaze::gfx::Bitmap::height(), source_bitmap_, source_palette_, yaze::gfx::Bitmap::vector(), and yaze::gfx::Bitmap::width().
Referenced by SetSource().
RenderComparisonGrid()
void yaze::gui::BppComparisonTool::RenderComparisonGrid () private
Definition at line 554 of file bpp_format_ui.cc.
References comparison_bitmaps_, comparison_scale_, comparison_valid_, yaze::gfx::BppFormatManager::Get(), yaze::gfx::BppFormatManager::GetAvailableFormats(), yaze::gfx::BppFormatManager::GetFormatInfo(), and yaze::gfx::Bitmap::texture().
Referenced by Render().
RenderMetrics()
void yaze::gui::BppComparisonTool::RenderMetrics () private
Definition at line 580 of file bpp_format_ui.cc.
References CalculateMetrics(), comparison_valid_, yaze::gfx::BppFormatManager::Get(), yaze::gfx::BppFormatManager::GetAvailableFormats(), and yaze::gfx::BppFormatManager::GetFormatInfo().
Referenced by Render().
RenderFormatSelector()
void yaze::gui::BppComparisonTool::RenderFormatSelector () private
Definition at line 593 of file bpp_format_ui.cc.
References selected_comparison_, and show_metrics_.
Referenced by Render().
CalculateMetrics()
std::string yaze::gui::BppComparisonTool::CalculateMetrics (gfx::BppFormat format) const private
Definition at line 608 of file bpp_format_ui.cc.
References yaze::gfx::BppFormatManager::Get(), yaze::gfx::BppFormatManager::GetFormatInfo(), yaze::gfx::Bitmap::height(), yaze::gfx::BppFormatInfo::max_colors, source_bitmap_, and yaze::gfx::Bitmap::width().
Referenced by RenderMetrics().
Member Data Documentation
id_
std::string yaze::gui::BppComparisonTool::id_ private
Definition at line 219 of file bpp_format_ui.h.
is_open_
bool yaze::gui::BppComparisonTool::is_open_ private
Definition at line 220 of file bpp_format_ui.h.
Referenced by Close(), IsOpen(), Open(), and Render().
source_bitmap_
gfx::Bitmap yaze::gui::BppComparisonTool::source_bitmap_ private
Definition at line 223 of file bpp_format_ui.h.
Referenced by CalculateMetrics(), GenerateComparisons(), and SetSource().
source_palette_
gfx::SnesPalette yaze::gui::BppComparisonTool::source_palette_ private
Definition at line 224 of file bpp_format_ui.h.
Referenced by GenerateComparisons(), and SetSource().
has_source_
bool yaze::gui::BppComparisonTool::has_source_ private
Definition at line 225 of file bpp_format_ui.h.
Referenced by Render(), and SetSource().
comparison_bitmaps_
std::unordered_map<gfx::BppFormat, gfx::Bitmap> yaze::gui::BppComparisonTool::comparison_bitmaps_ private
Definition at line 228 of file bpp_format_ui.h.
Referenced by GenerateComparisons(), and RenderComparisonGrid().
comparison_palettes_
std::unordered_map<gfx::BppFormat, gfx::SnesPalette> yaze::gui::BppComparisonTool::comparison_palettes_ private
Definition at line 229 of file bpp_format_ui.h.
Referenced by GenerateComparisons().
comparison_valid_
std::unordered_map<gfx::BppFormat, bool> yaze::gui::BppComparisonTool::comparison_valid_ private
Definition at line 230 of file bpp_format_ui.h.
Referenced by GenerateComparisons(), RenderComparisonGrid(), and RenderMetrics().
comparison_scale_
float yaze::gui::BppComparisonTool::comparison_scale_ private
Definition at line 233 of file bpp_format_ui.h.
Referenced by RenderComparisonGrid().
show_metrics_
bool yaze::gui::BppComparisonTool::show_metrics_ private
Definition at line 234 of file bpp_format_ui.h.
Referenced by Render(), and RenderFormatSelector().
selected_comparison_
gfx::BppFormat yaze::gui::BppComparisonTool::selected_comparison_ private
Definition at line 235 of file bpp_format_ui.h.
Referenced by RenderFormatSelector().
The documentation for this class was generated from the following files:
src/app/gui/bpp_format_ui.h
src/app/gui/bpp_format_ui.cc