yaze: yaze::editor::MemoryEditorWithDiffChecker Struct Reference
yaze::editor::MemoryEditorWithDiffChecker Struct Reference
#include <memory_editor.h>
Classes
struct Bookmark
Public Member Functions
MemoryEditorWithDiffChecker (Rom *rom=nullptr)
void Update (bool &show_memory_editor)
void set_rom (Rom *rom)
Rom * rom () const
Private Member Functions
void DrawToolbar ()
void DrawJumpToAddressPopup ()
void DrawSearchPopup ()
void DrawBookmarksPopup ()
Private Attributes
Rom * rom_
char jump_address_ [16] = "0x000000"
char search_pattern_ [256] = ""
uint32_t current_address_ = 0
std::vector< Bookmark > bookmarks_
Detailed Description
Definition at line 18 of file memory_editor.h.
Constructor & Destructor Documentation
MemoryEditorWithDiffChecker()
yaze::editor::MemoryEditorWithDiffChecker::MemoryEditorWithDiffChecker (Rom * rom = nullptr) inline explicit
Definition at line 19 of file memory_editor.h.
Member Function Documentation
Update()
void yaze::editor::MemoryEditorWithDiffChecker::Update (bool & show_memory_editor) inline
Definition at line 21 of file memory_editor.h.
References BEGIN_TABLE, DrawToolbar(), END_TABLE, yaze::Rom::filename(), yaze::gui::InputHex(), yaze::Rom::LoadFromFile(), NEXT_COLUMN, PRINT_IF_ERROR, rom(), SETUP_COLUMN, yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::Rom::size(), and yaze::SnesToPc().
Referenced by yaze::editor::EditorManager::DrawMenuBar().
set_rom()
void yaze::editor::MemoryEditorWithDiffChecker::set_rom (Rom * rom) inline
Definition at line 65 of file memory_editor.h.
References rom(), and rom_.
rom()
Rom * yaze::editor::MemoryEditorWithDiffChecker::rom () const inline
Definition at line 68 of file memory_editor.h.
References rom_.
Referenced by set_rom(), and Update().
DrawToolbar()
void yaze::editor::MemoryEditorWithDiffChecker::DrawToolbar () private
Definition at line 7 of file memory_editor.cc.
References DrawBookmarksPopup(), DrawJumpToAddressPopup(), DrawSearchPopup(), ICON_MD_BOOKMARK, ICON_MD_LOCATION_SEARCHING, and ICON_MD_SEARCH.
Referenced by Update().
DrawJumpToAddressPopup()
void yaze::editor::MemoryEditorWithDiffChecker::DrawJumpToAddressPopup () private
Todo:
Parse address and scroll to it
Definition at line 27 of file memory_editor.cc.
References ICON_MD_LOCATION_SEARCHING, and jump_address_.
Referenced by DrawToolbar().
DrawSearchPopup()
void yaze::editor::MemoryEditorWithDiffChecker::DrawSearchPopup () private
Todo:
Implement search using hex-search handler
Definition at line 45 of file memory_editor.cc.
References ICON_MD_SEARCH, and search_pattern_.
Referenced by DrawToolbar().
DrawBookmarksPopup()
void yaze::editor::MemoryEditorWithDiffChecker::DrawBookmarksPopup () private
Todo:
Add bookmark at current address
Todo:
Jump to this address
Definition at line 63 of file memory_editor.cc.
References bookmarks_, current_address_, and ICON_MD_BOOKMARK.
Referenced by DrawToolbar().
Member Data Documentation
rom_
Rom* yaze::editor::MemoryEditorWithDiffChecker::rom_ private
Definition at line 76 of file memory_editor.h.
Referenced by rom(), and set_rom().
jump_address_
char yaze::editor::MemoryEditorWithDiffChecker::jump_address_[16] = "0x000000" private
Definition at line 79 of file memory_editor.h.
Referenced by DrawJumpToAddressPopup().
search_pattern_
char yaze::editor::MemoryEditorWithDiffChecker::search_pattern_[256] = "" private
Definition at line 80 of file memory_editor.h.
Referenced by DrawSearchPopup().
current_address_
uint32_t yaze::editor::MemoryEditorWithDiffChecker::current_address_ = 0 private
Definition at line 81 of file memory_editor.h.
Referenced by DrawBookmarksPopup().
bookmarks_
std::vector<Bookmark> yaze::editor::MemoryEditorWithDiffChecker::bookmarks_ private
Definition at line 88 of file memory_editor.h.
Referenced by DrawBookmarksPopup().
The documentation for this struct was generated from the following files:
src/app/editor/code/memory_editor.h
src/app/editor/code/memory_editor.cc