yaze: yaze::cli::agent::TUICommandHandler Class Reference
yaze::cli::agent::TUICommandHandler Class Reference abstract
Base class for TUI-integrated command handlers.
#include <enhanced_tui.h>
Public Member Functions
TUICommandHandler (EnhancedTUI *tui)
Public Member Functions inherited from yaze::cli::resources::CommandHandler
virtual ~CommandHandler ()=default
absl::Status Run (const std::vector< std::string > &args, Rom *rom_context)
Execute the command.
virtual std::string GetName () const =0
Get the command name.
virtual Descriptor Describe () const
Provide metadata for TUI/help summaries.
Protected Member Functions
virtual void DisplayProgress (const std::string &message)
virtual void DisplayRichOutput (const std::string &output)
virtual absl::StatusOr< std::string > PromptUser (const std::string &)
virtual std::string GetCommandName () const =0
Protected Member Functions inherited from yaze::cli::resources::CommandHandler
virtual absl::Status ValidateArgs (const ArgumentParser &parser)=0
Validate command arguments.
virtual absl::Status Execute (Rom *rom, const ArgumentParser &parser, OutputFormatter &formatter)=0
Execute the command business logic.
virtual std::string GetUsage () const =0
Get the command usage string.
virtual bool RequiresLabels () const
Check if the command requires ROM labels.
virtual std::string GetDefaultFormat () const
Get the default output format ("json" or "text")
virtual std::string GetOutputTitle () const
Get the output title for formatting.
Private Attributes
EnhancedTUI * tui_ = nullptr
Detailed Description
Base class for TUI-integrated command handlers.
Extends CommandHandler with TUI-specific features:
Rich output formatting
Progress indicators
Interactive prompts
Real-time updates
Definition at line 233 of file enhanced_tui.h.
Constructor & Destructor Documentation
TUICommandHandler()
yaze::cli::agent::TUICommandHandler::TUICommandHandler (EnhancedTUI * tui) inline explicit
Definition at line 235 of file enhanced_tui.h.
Member Function Documentation
DisplayProgress()
virtual void yaze::cli::agent::TUICommandHandler::DisplayProgress (const std::string & message) inline protected virtual
Definition at line 239 of file enhanced_tui.h.
References tui_, and yaze::cli::agent::EnhancedTUI::UpdateStatusBar().
DisplayRichOutput()
virtual void yaze::cli::agent::TUICommandHandler::DisplayRichOutput (const std::string & output) inline protected virtual
Definition at line 245 of file enhanced_tui.h.
References yaze::cli::agent::EnhancedTUI::DisplayToolOutput(), GetCommandName(), and tui_.
PromptUser()
virtual absl::StatusOr< std::string > yaze::cli::agent::TUICommandHandler::PromptUser (const std::string &) inline protected virtual
Todo:
Implement interactive prompting in TUI
Definition at line 251 of file enhanced_tui.h.
GetCommandName()
virtual std::string yaze::cli::agent::TUICommandHandler::GetCommandName () const protected pure virtual
Referenced by DisplayRichOutput().
Member Data Documentation
tui_
EnhancedTUI* yaze::cli::agent::TUICommandHandler::tui_ = nullptr private
Definition at line 259 of file enhanced_tui.h.
Referenced by DisplayProgress(), and DisplayRichOutput().
The documentation for this class was generated from the following file:
src/cli/service/agent/enhanced_tui.h