yaze: yaze::editor::EditorManager Class Reference
yaze::editor::EditorManager Class Reference
The EditorManager controls the main editor window and manages the various editor classes.
#include <editor_manager.h>
Classes
struct RomSession
Public Member Functions
EditorManager ()
void Initialize (gfx::IRenderer *renderer, const std::string &filename="")
void OpenEditorAndCardsFromFlags (const std::string &editor_name, const std::string &cards_str)
absl::Status Update ()
void DrawMenuBar ()
auto emulator () -> emu::Emulator &
auto quit () const
auto version () const
void DrawMenuBarExtras ()
MenuBuilder & menu_builder ()
void ShowSessionSwitcher ()
void ShowEditorSelection ()
void ShowDisplaySettings ()
absl::Status SetCurrentRom (Rom *rom)
auto GetCurrentRom () -> Rom *
auto GetCurrentEditorSet () -> EditorSet *
auto overworld () -> yaze::zelda3::Overworld *
size_t GetCurrentSessionIndex () const
core::FeatureFlags::Flags * GetCurrentFeatureFlags ()
void SetFontGlobalScale (float scale)
void BuildModernMenu ()
void LoadUserSettings ()
void SaveUserSettings ()
void RefreshWorkspacePresets ()
void SaveWorkspacePreset (const std::string &name)
void LoadWorkspacePreset (const std::string &name)
void JumpToDungeonRoom (int room_id)
void JumpToOverworldMap (int map_id)
void SwitchToEditor (EditorType editor_type)
void CreateNewSession ()
void DuplicateCurrentSession ()
void CloseCurrentSession ()
void RemoveSession (size_t index)
void SwitchToSession (size_t index)
size_t GetActiveSessionCount () const
void SaveWorkspaceLayout ()
void LoadWorkspaceLayout ()
void ResetWorkspaceLayout ()
void ShowAllWindows ()
void HideAllWindows ()
void MaximizeCurrentWindow ()
void RestoreAllWindows ()
void CloseAllFloatingWindows ()
void LoadDeveloperLayout ()
void LoadDesignerLayout ()
void LoadModderLayout ()
std::string GenerateUniqueEditorTitle (EditorType type, size_t session_index) const
bool HasDuplicateSession (const std::string &filepath)
void RenameSession (size_t index, const std::string &new_name)
Private Member Functions
void DrawWelcomeScreen ()
absl::Status DrawRomSelector ()
void DrawContextSensitiveCardControl ()
void DrawSessionSwitcher ()
void DrawSessionManager ()
void DrawLayoutPresets ()
void DrawSessionRenameDialog ()
absl::Status LoadRom ()
absl::Status LoadAssets ()
absl::Status SaveRom ()
absl::Status SaveRomAs (const std::string &filename)
absl::Status OpenRomOrProject (const std::string &filename)
absl::Status CreateNewProject (const std::string &template_name="Basic ROM Hack")
absl::Status OpenProject ()
absl::Status SaveProject ()
absl::Status SaveProjectAs ()
absl::Status ImportProject (const std::string &project_path)
absl::Status RepairCurrentProject ()
void ShowProjectHelp ()
void InitializeTestSuites ()
Private Attributes
bool quit_ = false
bool new_project_menu = false
bool show_emulator_ = false
bool show_memory_editor_ = false
bool show_asm_editor_ = false
bool show_imgui_metrics_ = false
bool show_imgui_demo_ = false
bool show_palette_editor_ = false
bool show_resource_label_manager = false
bool show_workspace_layout = false
bool show_save_workspace_preset_ = false
bool show_load_workspace_preset_ = false
bool show_session_switcher_ = false
bool show_session_manager_ = false
bool show_layout_presets_ = false
bool show_homepage_ = true
bool show_command_palette_ = false
bool show_global_search_ = false
bool show_session_rename_dialog_ = false
bool show_welcome_screen_ = false
bool welcome_screen_manually_closed_ = false
bool show_card_browser_ = false
size_t session_to_rename_ = 0
char session_rename_buffer_ [256] = {}
bool show_test_dashboard_ = false
bool show_performance_dashboard_ = false
ProposalDrawer proposal_drawer_
bool show_proposal_drawer_ = false
AgentChatHistoryPopup agent_chat_history_popup_
bool show_chat_history_popup_ = false
ProjectFileEditor project_file_editor_
EditorSelectionDialog editor_selection_dialog_
bool show_editor_selection_ = false
WelcomeScreen welcome_screen_
std::string version_ = ""
absl::Status status_
emu::Emulator emulator_
std::deque< RomSession > sessions_
Rom * current_rom_ = nullptr
EditorSet * current_editor_set_ = nullptr
Editor * current_editor_ = nullptr
EditorSet blank_editor_set_ {}
gfx::IRenderer * renderer_ = nullptr
core::YazeProject current_project_
EditorContext context_
std::unique_ptr< PopupManager > popup_manager_
ToastManager toast_manager_
MenuBuilder menu_builder_
UserSettings user_settings_
WorkspaceManager workspace_manager_ {&toast_manager_}
float autosave_timer_ = 0.0f
Detailed Description
The EditorManager controls the main editor window and manages the various editor classes.
The EditorManager class contains instances of various editor classes such as AssemblyEditor, DungeonEditor, GraphicsEditor, MusicEditor, OverworldEditor, PaletteEditor, ScreenEditor, and SpriteEditor. The current_editor_ member variable points to the currently active editor in the tab view.
Definition at line 104 of file editor_manager.h.
Constructor & Destructor Documentation
EditorManager()
yaze::editor::EditorManager::EditorManager () inline
Definition at line 106 of file editor_manager.h.
References context_, yaze::editor::EditorContext::popup_manager, popup_manager_, and version_.
Member Function Documentation
Initialize()
void yaze::editor::EditorManager::Initialize (gfx::IRenderer * renderer, const std::string & filename = "")
Definition at line 134 of file editor_manager.cc.
References yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::accept_proposal, agent_chat_history_popup_, yaze::cli::GeminiConfig::api_key, blank_editor_set_, yaze::editor::AgentChatWidget::MultimodalCallbacks::capture_snapshot, yaze::Rom::Close(), CloseCurrentSession(), context_, yaze::editor::Editor::Copy(), CreateNewProject(), CreateNewSession(), current_editor_, current_editor_set_, current_rom_, yaze::editor::Editor::Cut(), yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::diff_proposal, yaze::editor::EditorSet::dungeon_editor_, editor_selection_dialog_, emulator_, yaze::editor::Editor::Find(), yaze::editor::AgentChatWidget::AutomationCallbacks::focus_proposal, yaze::editor::ProposalDrawer::FocusProposal(), yaze::cli::GeminiAIService::GenerateMultimodalResponse(), yaze::gui::EditorCardManager::Get(), yaze::test::TestManager::Get(), yaze::core::RecentFilesManager::GetInstance(), yaze::editor::EditorSet::graphics_editor_, ICON_MD_PREVIEW, InitializeTestSuites(), yaze::editor::kAgent, yaze::cli::agent::ChatMessage::kAgent, yaze::editor::kAssembly, yaze::editor::kDungeon, yaze::editor::kEmulator, yaze::editor::kGraphics, yaze::editor::kInfo, yaze::editor::kMessage, yaze::editor::kMusic, yaze::editor::kOverworld, yaze::editor::kPalette, yaze::editor::kScreen, yaze::editor::kSettings, yaze::editor::kSprite, yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::list_proposals, yaze::editor::UserSettings::Load(), LoadRom(), LoadUserSettings(), LoadWorkspaceLayout(), LOG_WARN, yaze::editor::EditorSelectionDialog::MarkRecentlyUsed(), MaximizeCurrentWindow(), yaze::cli::agent::ChatMessage::message, yaze::editor::EditorSet::message_editor_, yaze::cli::GeminiConfig::model, yaze::editor::EditorSet::music_editor_, yaze::editor::AgentChatWidget::AutomationCallbacks::open_harness_dashboard, OpenRomOrProject(), yaze::editor::EditorSet::overworld_editor_, yaze::editor::EditorSet::palette_editor_, yaze::editor::Editor::Paste(), yaze::editor::EditorContext::popup_manager, popup_manager_, PRINT_IF_ERROR, project_file_editor_, proposal_drawer_, quit_, yaze::editor::Editor::Redo(), yaze::editor::ShortcutManager::RegisterShortcut(), yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::reject_proposal, renderer_, yaze::editor::AgentChatWidget::AutomationCallbacks::replay_last_plan, yaze::test::TestManager::ReplayLastPlan(), SaveRom(), SaveWorkspaceLayout(), yaze::editor::EditorSet::screen_editor_, yaze::editor::AgentChatWidget::MultimodalCallbacks::send_to_gemini, yaze::cli::agent::ChatMessage::sender, yaze::editor::Editor::set_active(), yaze::editor::WelcomeScreen::SetNewProjectCallback(), yaze::editor::WelcomeScreen::SetOpenProjectCallback(), yaze::editor::WelcomeScreen::SetOpenRomCallback(), yaze::editor::EditorSelectionDialog::SetSelectionCallback(), yaze::editor::EditorSet::settings_editor_, yaze::editor::AgentChatHistoryPopup::SetToastManager(), yaze::editor::ProjectFileEditor::SetToastManager(), yaze::editor::EditorContext::shortcut_manager, yaze::editor::ProposalDrawer::Show(), yaze::editor::ToastManager::Show(), yaze::editor::AgentChatWidget::AutomationCallbacks::show_active_tests, show_asm_editor_, show_card_browser_, show_command_palette_, show_editor_selection_, show_emulator_, show_global_search_, show_session_switcher_, show_test_dashboard_, show_welcome_screen_, yaze::gui::EditorCardManager::ShowAllCardsInCategory(), yaze::test::TestManager::ShowHarnessActiveTests(), yaze::test::TestManager::ShowHarnessDashboard(), yaze::editor::EditorSet::sprite_editor_, status_, yaze::cli::agent::ChatMessage::timestamp, toast_manager_, yaze::editor::AgentChatHistoryPopup::Toggle(), yaze::editor::ProposalDrawer::Toggle(), yaze::editor::Editor::Undo(), user_settings_, yaze::cli::GeminiConfig::verbose, welcome_screen_, and welcome_screen_manually_closed_.
Referenced by yaze::core::Controller::OnEntry().
OpenEditorAndCardsFromFlags()
void yaze::editor::EditorManager::OpenEditorAndCardsFromFlags (const std::string & editor_name, const std::string & cards_str)
Definition at line 583 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, yaze::editor::DungeonEditorV2::add_room(), current_editor_set_, yaze::editor::EditorSet::dungeon_editor_, yaze::editor::kDungeon, yaze::editor::kSettings, yaze::editor::kUnknown, LOG_DEBUG, LOG_INFO, LOG_WARN, yaze::editor::DungeonEditorV2::show_entrances_list_, yaze::editor::DungeonEditorV2::show_object_editor_, yaze::editor::DungeonEditorV2::show_palette_editor_, yaze::editor::DungeonEditorV2::show_room_graphics_, yaze::editor::DungeonEditorV2::show_room_matrix_, and yaze::editor::DungeonEditorV2::show_room_selector_.
Referenced by yaze::core::Controller::SetStartupEditor().
Update()
absl::Status yaze::editor::EditorManager::Update ()
Todo:
Add EditorType::kGraphics, EditorType::kPalette when converted
Definition at line 654 of file editor_manager.cc.
References yaze::editor::UserSettings::Preferences::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_interval, autosave_timer_, yaze::Rom::SaveSettings::backup, context_, current_editor_, current_editor_set_, current_rom_, yaze::Rom::dirty(), yaze::editor::ProposalDrawer::Draw(), yaze::editor::ToastManager::Draw(), yaze::gui::EditorCardManager::DrawCardBrowser(), editor_selection_dialog_, yaze::editor::ExecuteShortcuts(), GenerateUniqueEditorTitle(), yaze::core::TimingManager::Get(), yaze::gui::BackgroundRenderer::Get(), yaze::gfx::PerformanceDashboard::Get(), yaze::gui::EditorCardManager::Get(), yaze::gui::ThemeManager::Get(), yaze::test::TestManager::Get(), yaze::Rom::is_loaded(), yaze::editor::kDungeon, yaze::editor::kError, yaze::editor::kOverworld, yaze::editor::kSuccess, LOG_DEBUG, popup_manager_, yaze::editor::UserSettings::prefs(), proposal_drawer_, yaze::gfx::PerformanceDashboard::Render(), yaze::Rom::SaveSettings::save_new, yaze::Rom::SaveToFile(), yaze::editor::EditorContext::session_id, sessions_, yaze::editor::Editor::set_active(), yaze::test::TestManager::SetCurrentRom(), yaze::editor::EditorContext::shortcut_manager, yaze::editor::EditorSelectionDialog::Show(), yaze::editor::ToastManager::Show(), show_card_browser_, show_editor_selection_, show_performance_dashboard_, show_welcome_screen_, status_, toast_manager_, yaze::core::TimingManager::Update(), user_settings_, and welcome_screen_manually_closed_.
Referenced by yaze::core::Controller::OnLoad().
DrawMenuBar()
void yaze::editor::EditorManager::DrawMenuBar ()
Definition at line 1408 of file editor_manager.cc.
References agent_chat_history_popup_, yaze::editor::EditorSet::assembly_editor_, BuildModernMenu(), yaze::core::YazeProject::code_folder, context_, yaze::core::YazeProject::Create(), current_editor_set_, current_project_, current_rom_, yaze::core::ResourceLabelManager::DisplayLabels(), yaze::editor::AgentChatHistoryPopup::Draw(), yaze::editor::ProjectFileEditor::Draw(), yaze::editor::ProposalDrawer::Draw(), DrawLayoutPresets(), DrawMenuBarExtras(), DrawRomSelector(), DrawSessionManager(), DrawSessionRenameDialog(), DrawSessionSwitcher(), DrawWelcomeScreen(), emulator_, yaze::core::ResourceLabelManager::filename_, yaze::core::YazeProject::filepath, yaze::gfx::PerformanceDashboard::Get(), yaze::test::TestManager::Get(), GetActiveSessionCount(), yaze::util::GetFileExtension(), yaze::util::GetFileName(), yaze::core::RecentFilesManager::GetInstance(), yaze::editor::ShortcutManager::GetShortcuts(), ICON_MD_ADD, ICON_MD_CANCEL, ICON_MD_CLEAR, ICON_MD_CODE, ICON_MD_DESCRIPTION, ICON_MD_FOLDER, ICON_MD_FOLDER_OPEN, ICON_MD_HISTORY, ICON_MD_INFO, ICON_MD_LABEL, ICON_MD_LIST, ICON_MD_MANAGE_SEARCH, ICON_MD_SAVE, ICON_MD_SAVE_AS, ICON_MD_SEARCH, ICON_MD_STAR, ICON_MD_TAB, ICON_MD_VIDEOGAME_ASSET, yaze::gui::kDefaultModalSize, yaze::editor::kError, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::core::ResourceLabelManager::labels_, yaze::core::YazeProject::labels_filename, LoadWorkspacePreset(), yaze::editor::EditorSet::memory_editor_, new_project_menu, OpenRomOrProject(), yaze::editor::EditorSet::palette_editor_, popup_manager_, yaze::editor::PrintShortcut(), project_file_editor_, yaze::core::YazeProject::project_opened(), proposal_drawer_, RefreshWorkspacePresets(), yaze::gfx::PerformanceDashboard::Render(), yaze::Rom::resource_label(), yaze::core::YazeProject::rom_filename, yaze::emu::Emulator::Run(), yaze::core::YazeProject::Save(), SaveRomAs(), SaveWorkspacePreset(), sessions_, yaze::editor::ProposalDrawer::SetRom(), yaze::gfx::PerformanceDashboard::SetVisible(), yaze::editor::EditorContext::shortcut_manager, yaze::editor::ToastManager::Show(), show_asm_editor_, show_command_palette_, show_emulator_, show_global_search_, show_imgui_demo_, show_imgui_metrics_, show_load_workspace_preset_, show_memory_editor_, show_palette_editor_, show_performance_dashboard_, show_resource_label_manager, show_save_workspace_preset_, show_test_dashboard_, show_welcome_screen_, yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::util::FileDialogWrapper::ShowOpenFolderDialog(), yaze::util::FileDialogWrapper::ShowSaveFileDialog(), status_, SwitchToSession(), yaze::Rom::title(), toast_manager_, yaze::gfx::PerformanceDashboard::Update(), yaze::editor::PaletteEditor::Update(), yaze::editor::AssemblyEditor::Update(), yaze::editor::MemoryEditorWithDiffChecker::Update(), version_, workspace_manager_, yaze::editor::WorkspaceManager::workspace_presets(), and yaze::editor::WorkspaceManager::workspace_presets_loaded().
Referenced by yaze::core::Controller::OnLoad().
emulator()
auto yaze::editor::EditorManager::emulator () -> emu::Emulator& inline
Definition at line 122 of file editor_manager.h.
References emulator_.
Referenced by yaze::core::Controller::OnEntry().
quit()
auto yaze::editor::EditorManager::quit () const inline
Definition at line 123 of file editor_manager.h.
References quit_.
Referenced by yaze::core::Controller::OnLoad().
version()
auto yaze::editor::EditorManager::version () const inline
Definition at line 124 of file editor_manager.h.
References version_.
Referenced by BuildModernMenu(), and yaze::editor::PopupManager::DrawAboutPopup().
DrawMenuBarExtras()
void yaze::editor::EditorManager::DrawMenuBarExtras ()
Definition at line 1348 of file editor_manager.cc.
References GetActiveSessionCount(), GetCurrentRom(), ICON_MD_APPS, ICON_MD_DASHBOARD, ICON_MD_DISPLAY_SETTINGS, ICON_MD_TAB, ICON_MD_TUNE, ShowDisplaySettings(), ShowEditorSelection(), ShowSessionSwitcher(), and version_.
Referenced by yaze::editor::MenuManager::BuildAndDraw(), and DrawMenuBar().
menu_builder()
MenuBuilder & yaze::editor::EditorManager::menu_builder () inline
Definition at line 126 of file editor_manager.h.
References menu_builder_.
ShowSessionSwitcher()
void yaze::editor::EditorManager::ShowSessionSwitcher ()
Definition at line 1402 of file editor_manager.cc.
References show_session_switcher_.
Referenced by DrawMenuBarExtras().
ShowEditorSelection()
void yaze::editor::EditorManager::ShowEditorSelection ()
Definition at line 1404 of file editor_manager.cc.
References show_editor_selection_.
Referenced by DrawMenuBarExtras().
ShowDisplaySettings()
void yaze::editor::EditorManager::ShowDisplaySettings ()
Definition at line 1406 of file editor_manager.cc.
References popup_manager_.
Referenced by DrawMenuBarExtras().
SetCurrentRom()
absl::Status yaze::editor::EditorManager::SetCurrentRom (Rom * rom)
Definition at line 2416 of file editor_manager.cc.
References current_editor_set_, current_rom_, yaze::test::TestManager::Get(), sessions_, and yaze::test::TestManager::SetCurrentRom().
Referenced by DrawRomSelector().
GetCurrentRom()
auto yaze::editor::EditorManager::GetCurrentRom () -> Rom* inline
Definition at line 132 of file editor_manager.h.
References current_rom_.
Referenced by DrawMenuBarExtras(), yaze::editor::PopupManager::DrawRomInfoPopup(), and yaze::core::Controller::GetCurrentRom().
GetCurrentEditorSet()
auto yaze::editor::EditorManager::GetCurrentEditorSet () -> EditorSet* inline
Definition at line 133 of file editor_manager.h.
References current_editor_set_.
overworld()
auto yaze::editor::EditorManager::overworld () -> yaze::zelda3::Overworld* inline
Definition at line 134 of file editor_manager.h.
References current_editor_set_, yaze::editor::OverworldEditor::overworld(), and yaze::editor::EditorSet::overworld_editor_.
Referenced by yaze::core::Controller::overworld().
GetCurrentSessionIndex()
size_t yaze::editor::EditorManager::GetCurrentSessionIndex () const
Definition at line 2574 of file editor_manager.cc.
References current_rom_, and sessions_.
Referenced by CloseCurrentSession(), GetCurrentFeatureFlags(), SaveProject(), and SaveRomAs().
GetCurrentFeatureFlags()
core::FeatureFlags::Flags * yaze::editor::EditorManager::GetCurrentFeatureFlags () inline
Definition at line 140 of file editor_manager.h.
References yaze::core::FeatureFlags::get(), GetCurrentSessionIndex(), and sessions_.
SetFontGlobalScale()
void yaze::editor::EditorManager::SetFontGlobalScale (float scale) inline
Definition at line 148 of file editor_manager.h.
References yaze::editor::UserSettings::Preferences::font_global_scale, yaze::editor::UserSettings::prefs(), SaveUserSettings(), and user_settings_.
Referenced by yaze::editor::PopupManager::DrawDisplaySettingsPopup().
BuildModernMenu()
void yaze::editor::EditorManager::BuildModernMenu ()
Definition at line 944 of file editor_manager.cc.
References agent_chat_history_popup_, yaze::Rom::SaveSettings::backup, yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::BeginSubMenu(), yaze::editor::MenuBuilder::Clear(), yaze::test::TestManager::ClearResults(), CloseAllFloatingWindows(), CloseCurrentSession(), yaze::editor::Editor::Copy(), CreateNewProject(), CreateNewSession(), current_editor_, current_editor_set_, current_project_, current_rom_, yaze::editor::Editor::Cut(), yaze::editor::MenuBuilder::Draw(), yaze::editor::EditorSet::dungeon_editor_, DuplicateCurrentSession(), yaze::Rom::SaveSettings::filename, yaze::Rom::filename(), yaze::core::YazeProject::filepath, yaze::editor::Editor::Find(), yaze::core::FeatureFlags::get(), yaze::test::TestManager::Get(), yaze::editor::EditorSet::graphics_editor_, HideAllWindows(), ICON_MD_ADD, ICON_MD_ADD_CIRCLE, ICON_MD_ANALYTICS, ICON_MD_BACKUP, ICON_MD_BOOKMARK, ICON_MD_BUILD, ICON_MD_CASTLE, ICON_MD_CHAT, ICON_MD_CHAT_BUBBLE, ICON_MD_CHECK_CIRCLE, ICON_MD_CLEAR_ALL, ICON_MD_CLOSE, ICON_MD_CLOSE_FULLSCREEN, ICON_MD_CLOUD_OFF, ICON_MD_CLOUD_UPLOAD, ICON_MD_CODE, ICON_MD_CONTENT_COPY, ICON_MD_CONTENT_CUT, ICON_MD_CONTENT_PASTE, ICON_MD_CREATE_NEW_FOLDER, ICON_MD_DASHBOARD, ICON_MD_DATA_ARRAY, ICON_MD_EXIT_TO_APP, ICON_MD_FILE_OPEN, ICON_MD_FLAG, ICON_MD_FOLDER, ICON_MD_FOLDER_OPEN, ICON_MD_FULLSCREEN, ICON_MD_FULLSCREEN_EXIT, ICON_MD_GAMEPAD, ICON_MD_HELP, ICON_MD_HOME, ICON_MD_IMAGE, ICON_MD_INFO, ICON_MD_INTEGRATION_INSTRUCTIONS, ICON_MD_LOGIN, ICON_MD_LOGOUT, ICON_MD_MAP, ICON_MD_MEMORY, ICON_MD_MUSIC_NOTE, ICON_MD_PALETTE, ICON_MD_PLAY_ARROW, ICON_MD_PREVIEW, ICON_MD_RATE_REVIEW, ICON_MD_REDO, ICON_MD_REFRESH, ICON_MD_RESET_TV, ICON_MD_SAVE, ICON_MD_SAVE_ALT, ICON_MD_SAVE_AS, ICON_MD_SCIENCE, ICON_MD_SCREENSHOT, ICON_MD_SEARCH, ICON_MD_SETTINGS, ICON_MD_SMART_TOY, ICON_MD_SPEED, ICON_MD_STORAGE, ICON_MD_SWITCH_ACCOUNT, ICON_MD_TAB, ICON_MD_TERMINAL, ICON_MD_TOYS, ICON_MD_TV, ICON_MD_UNDO, ICON_MD_UPGRADE, ICON_MD_VIEW_LIST, ICON_MD_VISIBILITY, ICON_MD_VISIBILITY_OFF, ICON_MD_WIFI, yaze::Rom::is_loaded(), yaze::editor::MenuBuilder::Item(), yaze::editor::AgentEditor::CaptureConfig::kActiveEditor, yaze::editor::kError, yaze::editor::AgentEditor::CaptureConfig::kFullWindow, yaze::editor::kInfo, yaze::test::kIntegration, yaze::editor::AgentEditor::kLocal, yaze::test::kMemory, yaze::editor::AgentEditor::kNetwork, yaze::test::kPerformance, yaze::editor::kSuccess, yaze::test::kUI, yaze::test::kUnit, yaze::editor::kWarning, LoadRom(), LoadWorkspaceLayout(), MaximizeCurrentWindow(), menu_builder_, yaze::editor::EditorSet::message_editor_, yaze::editor::AgentEditor::CaptureConfig::mode, yaze::editor::EditorSet::music_editor_, OpenProject(), yaze::editor::EditorSet::overworld_editor_, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::editor::EditorSet::palette_editor_, yaze::editor::Editor::Paste(), popup_manager_, proposal_drawer_, quit_, yaze::editor::Editor::Redo(), ResetWorkspaceLayout(), RestoreAllWindows(), yaze::test::TestManager::RunAllTests(), yaze::test::TestManager::RunTestsByCategory(), yaze::test::TestManager::RunTestSuite(), SaveProject(), SaveProjectAs(), SaveRom(), yaze::Rom::SaveToFile(), SaveWorkspaceLayout(), yaze::editor::EditorSet::screen_editor_, yaze::editor::MenuBuilder::Separator(), sessions_, yaze::editor::Editor::set_active(), yaze::editor::EditorSet::settings_editor_, yaze::editor::ToastManager::Show(), show_asm_editor_, show_card_browser_, show_command_palette_, show_editor_selection_, show_emulator_, show_global_search_, show_imgui_demo_, show_imgui_metrics_, show_layout_presets_, show_memory_editor_, show_performance_dashboard_, show_proposal_drawer_, show_session_manager_, show_session_switcher_, show_test_dashboard_, show_welcome_screen_, ShowAllWindows(), yaze::editor::EditorSet::sprite_editor_, status_, yaze::Rom::title(), toast_manager_, yaze::editor::AgentChatHistoryPopup::Toggle(), yaze::editor::ProposalDrawer::Toggle(), yaze::editor::Editor::Undo(), yaze::core::YazeProject::Validate(), and version().
Referenced by yaze::editor::MenuManager::BuildAndDraw(), and DrawMenuBar().
LoadUserSettings()
void yaze::editor::EditorManager::LoadUserSettings ()
Definition at line 3294 of file editor_manager.cc.
References yaze::editor::UserSettings::Preferences::font_global_scale, yaze::editor::UserSettings::prefs(), yaze::editor::UserSettings::Preferences::show_welcome_on_startup, show_welcome_screen_, user_settings_, and welcome_screen_manually_closed_.
Referenced by Initialize().
SaveUserSettings()
void yaze::editor::EditorManager::SaveUserSettings ()
Definition at line 3305 of file editor_manager.cc.
References LOG_WARN, yaze::editor::UserSettings::Save(), and user_settings_.
Referenced by SetFontGlobalScale().
RefreshWorkspacePresets()
void yaze::editor::EditorManager::RefreshWorkspacePresets () inline
Definition at line 161 of file editor_manager.h.
References yaze::editor::WorkspaceManager::RefreshPresets(), and workspace_manager_.
Referenced by DrawLayoutPresets(), and DrawMenuBar().
SaveWorkspacePreset()
void yaze::editor::EditorManager::SaveWorkspacePreset (const std::string & name) inline
Definition at line 162 of file editor_manager.h.
References yaze::editor::WorkspaceManager::SaveWorkspacePreset(), and workspace_manager_.
Referenced by DrawMenuBar().
LoadWorkspacePreset()
void yaze::editor::EditorManager::LoadWorkspacePreset (const std::string & name) inline
Definition at line 163 of file editor_manager.h.
References yaze::editor::WorkspaceManager::LoadWorkspacePreset(), and workspace_manager_.
Referenced by DrawLayoutPresets(), and DrawMenuBar().
JumpToDungeonRoom()
void yaze::editor::EditorManager::JumpToDungeonRoom (int room_id)
Definition at line 3257 of file editor_manager.cc.
References yaze::editor::DungeonEditorV2::add_room(), current_editor_set_, yaze::editor::EditorSet::dungeon_editor_, yaze::editor::kDungeon, and SwitchToEditor().
JumpToOverworldMap()
void yaze::editor::EditorManager::JumpToOverworldMap (int map_id)
Definition at line 3267 of file editor_manager.cc.
References current_editor_set_, yaze::editor::kOverworld, yaze::editor::EditorSet::overworld_editor_, yaze::editor::OverworldEditor::set_current_map(), and SwitchToEditor().
SwitchToEditor()
void yaze::editor::EditorManager::SwitchToEditor (EditorType editor_type)
Definition at line 3277 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, and current_editor_set_.
Referenced by JumpToDungeonRoom(), and JumpToOverworldMap().
CreateNewSession()
void yaze::editor::EditorManager::CreateNewSession ()
Definition at line 2437 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, context_, yaze::editor::EditorManager::RomSession::editors, yaze::editor::kInfo, yaze::editor::kSuccess, popup_manager_, sessions_, yaze::editor::EditorSet::set_user_settings(), yaze::editor::ToastManager::Show(), toast_manager_, and user_settings_.
Referenced by BuildModernMenu(), DrawSessionManager(), DrawSessionSwitcher(), and Initialize().
DuplicateCurrentSession()
void yaze::editor::EditorManager::DuplicateCurrentSession ()
Definition at line 2469 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, context_, current_rom_, yaze::editor::EditorManager::RomSession::editors, yaze::editor::kSuccess, yaze::editor::kWarning, sessions_, yaze::editor::ToastManager::Show(), toast_manager_, and user_settings_.
Referenced by BuildModernMenu(), and DrawSessionManager().
CloseCurrentSession()
void yaze::editor::EditorManager::CloseCurrentSession ()
Definition at line 2491 of file editor_manager.cc.
References current_editor_set_, current_rom_, yaze::test::TestManager::Get(), GetActiveSessionCount(), GetCurrentSessionIndex(), yaze::editor::kSuccess, yaze::editor::kWarning, RemoveSession(), sessions_, yaze::test::TestManager::SetCurrentRom(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by BuildModernMenu(), DrawSessionManager(), DrawSessionSwitcher(), and Initialize().
RemoveSession()
void yaze::editor::EditorManager::RemoveSession (size_t index)
Todo:
Implement proper session removal when EditorSet becomes movable
Definition at line 2521 of file editor_manager.cc.
References GetActiveSessionCount(), yaze::editor::kError, yaze::editor::kInfo, yaze::editor::kWarning, LOG_DEBUG, sessions_, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by CloseCurrentSession(), DrawSessionManager(), and DrawSessionSwitcher().
SwitchToSession()
void yaze::editor::EditorManager::SwitchToSession (size_t index)
Definition at line 2553 of file editor_manager.cc.
References current_editor_set_, current_rom_, yaze::test::TestManager::Get(), yaze::editor::kError, yaze::editor::kInfo, yaze::util::logf(), sessions_, yaze::test::TestManager::SetCurrentRom(), yaze::editor::ToastManager::Show(), yaze::Rom::title(), and toast_manager_.
Referenced by DrawMenuBar(), DrawSessionManager(), and DrawSessionSwitcher().
GetActiveSessionCount()
size_t yaze::editor::EditorManager::GetActiveSessionCount () const
Definition at line 2584 of file editor_manager.cc.
References sessions_.
Referenced by CloseCurrentSession(), DrawMenuBar(), DrawMenuBarExtras(), DrawSessionManager(), DrawSessionSwitcher(), and RemoveSession().
SaveWorkspaceLayout()
void yaze::editor::EditorManager::SaveWorkspaceLayout ()
Definition at line 2621 of file editor_manager.cc.
References yaze::editor::kSuccess, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by BuildModernMenu(), and Initialize().
LoadWorkspaceLayout()
void yaze::editor::EditorManager::LoadWorkspaceLayout ()
Definition at line 2626 of file editor_manager.cc.
References yaze::editor::kSuccess, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by BuildModernMenu(), and Initialize().
ResetWorkspaceLayout()
void yaze::editor::EditorManager::ResetWorkspaceLayout ()
Definition at line 2616 of file editor_manager.cc.
References popup_manager_.
Referenced by BuildModernMenu().
ShowAllWindows()
void yaze::editor::EditorManager::ShowAllWindows ()
Definition at line 2631 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, current_editor_set_, yaze::editor::kInfo, yaze::editor::ToastManager::Show(), show_imgui_demo_, show_imgui_metrics_, show_performance_dashboard_, show_test_dashboard_, and toast_manager_.
Referenced by BuildModernMenu().
HideAllWindows()
void yaze::editor::EditorManager::HideAllWindows ()
Definition at line 2648 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, current_editor_set_, yaze::editor::kInfo, yaze::editor::ToastManager::Show(), show_imgui_demo_, show_imgui_metrics_, show_performance_dashboard_, show_test_dashboard_, and toast_manager_.
Referenced by BuildModernMenu().
MaximizeCurrentWindow()
void yaze::editor::EditorManager::MaximizeCurrentWindow ()
Definition at line 2665 of file editor_manager.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by BuildModernMenu(), and Initialize().
RestoreAllWindows()
void yaze::editor::EditorManager::RestoreAllWindows ()
Definition at line 2671 of file editor_manager.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by BuildModernMenu().
CloseAllFloatingWindows()
void yaze::editor::EditorManager::CloseAllFloatingWindows ()
Definition at line 2676 of file editor_manager.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by BuildModernMenu().
LoadDeveloperLayout()
void yaze::editor::EditorManager::LoadDeveloperLayout ()
Definition at line 2681 of file editor_manager.cc.
References yaze::editor::EditorSet::assembly_editor_, current_editor_set_, yaze::editor::EditorSet::graphics_editor_, yaze::editor::kSuccess, yaze::editor::EditorSet::music_editor_, yaze::editor::Editor::set_active(), yaze::editor::ToastManager::Show(), show_imgui_metrics_, show_test_dashboard_, yaze::editor::EditorSet::sprite_editor_, and toast_manager_.
Referenced by DrawLayoutPresets().
LoadDesignerLayout()
void yaze::editor::EditorManager::LoadDesignerLayout ()
Definition at line 2700 of file editor_manager.cc.
References yaze::editor::EditorSet::assembly_editor_, current_editor_set_, yaze::editor::EditorSet::graphics_editor_, yaze::editor::kSuccess, yaze::editor::EditorSet::overworld_editor_, yaze::editor::EditorSet::palette_editor_, yaze::editor::Editor::set_active(), yaze::editor::ToastManager::Show(), show_imgui_metrics_, show_test_dashboard_, yaze::editor::EditorSet::sprite_editor_, and toast_manager_.
Referenced by DrawLayoutPresets().
LoadModderLayout()
void yaze::editor::EditorManager::LoadModderLayout ()
Definition at line 2720 of file editor_manager.cc.
References yaze::editor::EditorSet::assembly_editor_, current_editor_set_, yaze::editor::EditorSet::dungeon_editor_, yaze::editor::EditorSet::graphics_editor_, yaze::editor::kSuccess, yaze::editor::EditorSet::message_editor_, yaze::editor::EditorSet::music_editor_, yaze::editor::EditorSet::overworld_editor_, yaze::editor::EditorSet::palette_editor_, yaze::editor::Editor::set_active(), yaze::editor::ToastManager::Show(), show_imgui_metrics_, yaze::editor::EditorSet::sprite_editor_, and toast_manager_.
Referenced by DrawLayoutPresets().
GenerateUniqueEditorTitle()
std::string yaze::editor::EditorManager::GenerateUniqueEditorTitle (EditorType type, size_t session_index) const
Definition at line 2594 of file editor_manager.cc.
References yaze::editor::kEditorNames, and sessions_.
Referenced by Update().
HasDuplicateSession()
bool yaze::editor::EditorManager::HasDuplicateSession (const std::string & filepath)
Definition at line 3184 of file editor_manager.cc.
References sessions_.
Referenced by LoadRom().
RenameSession()
void yaze::editor::EditorManager::RenameSession (size_t index, const std::string & new_name)
Definition at line 3193 of file editor_manager.cc.
References yaze::editor::kSuccess, sessions_, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by DrawSessionRenameDialog().
DrawWelcomeScreen()
void yaze::editor::EditorManager::DrawWelcomeScreen () private
Definition at line 3240 of file editor_manager.cc.
References yaze::editor::WelcomeScreen::MarkManuallyClosed(), yaze::editor::WelcomeScreen::RefreshRecentProjects(), yaze::editor::WelcomeScreen::Show(), show_welcome_screen_, welcome_screen_, and welcome_screen_manually_closed_.
Referenced by DrawMenuBar().
DrawRomSelector()
absl::Status yaze::editor::EditorManager::DrawRomSelector () private
Definition at line 862 of file editor_manager.cc.
References current_rom_, DrawContextSensitiveCardControl(), yaze::Rom::is_loaded(), RETURN_IF_ERROR, sessions_, SetCurrentRom(), yaze::Rom::short_name(), and yaze::Rom::size().
Referenced by DrawMenuBar().
DrawContextSensitiveCardControl()
void yaze::editor::EditorManager::DrawContextSensitiveCardControl () private
Definition at line 892 of file editor_manager.cc.
References current_editor_, current_editor_set_, yaze::gui::EditorCardManager::Get(), yaze::editor::kAssembly, yaze::editor::kDungeon, yaze::editor::kEmulator, yaze::editor::kGraphics, yaze::editor::kMessage, yaze::editor::kMusic, yaze::editor::kOverworld, yaze::editor::kPalette, yaze::editor::kScreen, yaze::editor::kSprite, and yaze::editor::Editor::type().
Referenced by DrawRomSelector().
DrawSessionSwitcher()
void yaze::editor::EditorManager::DrawSessionSwitcher () private
Definition at line 2740 of file editor_manager.cc.
References CloseCurrentSession(), CreateNewSession(), current_rom_, GetActiveSessionCount(), ICON_MD_ADD, ICON_MD_CHECK_CIRCLE, ICON_MD_CLOSE, ICON_MD_EDIT, ICON_MD_RADIO_BUTTON_UNCHECKED, ICON_MD_SETTINGS, ICON_MD_STAR, ICON_MD_SWITCH_ACCOUNT, ICON_MD_TAB, ICON_MD_VIDEOGAME_ASSET, ICON_MD_WARNING, RemoveSession(), session_rename_buffer_, session_to_rename_, sessions_, show_session_manager_, show_session_rename_dialog_, show_session_switcher_, and SwitchToSession().
Referenced by DrawMenuBar().
DrawSessionManager()
void yaze::editor::EditorManager::DrawSessionManager () private
Definition at line 2917 of file editor_manager.cc.
References CloseCurrentSession(), CreateNewSession(), current_rom_, DuplicateCurrentSession(), yaze::core::FeatureFlags::get(), GetActiveSessionCount(), ICON_MD_ADD, ICON_MD_CHECK_CIRCLE, ICON_MD_CONTENT_COPY, ICON_MD_EDIT, ICON_MD_MANAGE_ACCOUNTS, ICON_MD_RADIO_BUTTON_UNCHECKED, ICON_MD_STAR, ICON_MD_TAB, ICON_MD_VIEW_LIST, yaze::editor::kInfo, yaze::core::FeatureFlags::Flags::Overworld::kLoadCustomOverworld, yaze::core::FeatureFlags::Flags::overworld, RemoveSession(), session_rename_buffer_, session_to_rename_, sessions_, yaze::editor::ToastManager::Show(), show_session_manager_, show_session_rename_dialog_, SwitchToSession(), and toast_manager_.
Referenced by DrawMenuBar().
DrawLayoutPresets()
void yaze::editor::EditorManager::DrawLayoutPresets () private
Definition at line 3117 of file editor_manager.cc.
References ICON_MD_ADD, ICON_MD_BOOKMARK, ICON_MD_DASHBOARD, ICON_MD_DESIGN_SERVICES, ICON_MD_DEVELOPER_MODE, ICON_MD_GAMEPAD, yaze::editor::kSuccess, LoadDesignerLayout(), LoadDeveloperLayout(), LoadModderLayout(), LoadWorkspacePreset(), RefreshWorkspacePresets(), yaze::editor::ToastManager::Show(), show_layout_presets_, show_save_workspace_preset_, toast_manager_, workspace_manager_, yaze::editor::WorkspaceManager::workspace_presets(), and yaze::editor::WorkspaceManager::workspace_presets_loaded().
Referenced by DrawMenuBar().
DrawSessionRenameDialog()
void yaze::editor::EditorManager::DrawSessionRenameDialog () private
Definition at line 3202 of file editor_manager.cc.
References RenameSession(), session_rename_buffer_, session_to_rename_, sessions_, and show_session_rename_dialog_.
Referenced by DrawMenuBar().
LoadRom()
absl::Status yaze::editor::EditorManager::LoadRom () private
Definition at line 2014 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, yaze::editor::EditorSelectionDialog::ClearRecentEditors(), context_, current_editor_set_, current_rom_, editor_selection_dialog_, yaze::editor::EditorManager::RomSession::editors, yaze::editor::EditorManager::RomSession::filepath, yaze::test::TestManager::Get(), yaze::core::RecentFilesManager::GetInstance(), HasDuplicateSession(), yaze::editor::kWarning, LoadAssets(), yaze::Rom::LoadFromFile(), LOG_DEBUG, RETURN_IF_ERROR, yaze::editor::EditorManager::RomSession::rom, sessions_, yaze::test::TestManager::SetCurrentRom(), yaze::editor::ToastManager::Show(), show_editor_selection_, show_welcome_screen_, yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::Rom::title(), toast_manager_, and user_settings_.
Referenced by BuildModernMenu(), and Initialize().
LoadAssets()
absl::Status yaze::editor::EditorManager::LoadAssets () private
Definition at line 2084 of file editor_manager.cc.
References ASSIGN_OR_RETURN, current_editor_set_, current_rom_, yaze::editor::EditorSet::dungeon_editor_, emulator_, yaze::gfx::Arena::Get(), yaze::gfx::PerformanceProfiler::Get(), yaze::editor::MessageEditor::Initialize(), yaze::editor::DungeonEditorV2::Initialize(), yaze::editor::OverworldEditor::Initialize(), yaze::editor::DungeonEditorV2::Load(), yaze::editor::PaletteEditor::Load(), yaze::editor::ScreenEditor::Load(), yaze::editor::MessageEditor::Load(), yaze::editor::MusicEditor::Load(), yaze::editor::OverworldEditor::Load(), yaze::editor::SpriteEditor::Load(), yaze::editor::SettingsEditor::Load(), yaze::LoadAllGraphicsData(), LOG_DEBUG, yaze::editor::EditorSet::message_editor_, yaze::editor::EditorSet::music_editor_, yaze::editor::EditorSet::overworld_editor_, yaze::editor::EditorSet::palette_editor_, yaze::gfx::PerformanceProfiler::PrintSummary(), renderer_, RETURN_IF_ERROR, yaze::editor::EditorSet::screen_editor_, yaze::emu::Emulator::set_renderer(), yaze::editor::EditorSet::settings_editor_, and yaze::editor::EditorSet::sprite_editor_.
Referenced by LoadRom(), OpenProject(), and OpenRomOrProject().
SaveRom()
absl::Status yaze::editor::EditorManager::SaveRom () private
Definition at line 2121 of file editor_manager.cc.
References yaze::Rom::SaveSettings::backup, yaze::editor::UserSettings::Preferences::backup_rom, current_editor_set_, current_rom_, yaze::editor::ScreenEditor::dungeon_maps_, yaze::core::FeatureFlags::get(), yaze::gfx::Arena::Get(), yaze::editor::EditorSet::overworld_editor_, yaze::editor::UserSettings::prefs(), RETURN_IF_ERROR, yaze::editor::OverworldEditor::Save(), yaze::Rom::SaveSettings::save_new, yaze::editor::UserSettings::Preferences::save_new_auto, yaze::SaveAllGraphicsData(), yaze::zelda3::SaveDungeonMaps(), yaze::Rom::SaveToFile(), yaze::editor::EditorSet::screen_editor_, and user_settings_.
Referenced by BuildModernMenu(), and Initialize().
SaveRomAs()
absl::Status yaze::editor::EditorManager::SaveRomAs (const std::string & filename) private
Definition at line 2143 of file editor_manager.cc.
References yaze::Rom::SaveSettings::backup, yaze::editor::UserSettings::Preferences::backup_rom, current_editor_set_, current_rom_, yaze::editor::ScreenEditor::dungeon_maps_, yaze::Rom::SaveSettings::filename, yaze::core::FeatureFlags::get(), yaze::gfx::Arena::Get(), GetCurrentSessionIndex(), yaze::core::RecentFilesManager::GetInstance(), yaze::editor::kSuccess, yaze::editor::EditorSet::overworld_editor_, yaze::editor::UserSettings::prefs(), RETURN_IF_ERROR, yaze::editor::OverworldEditor::Save(), yaze::Rom::SaveSettings::save_new, yaze::SaveAllGraphicsData(), yaze::zelda3::SaveDungeonMaps(), yaze::Rom::SaveToFile(), yaze::editor::EditorSet::screen_editor_, sessions_, yaze::editor::ToastManager::Show(), toast_manager_, and user_settings_.
Referenced by DrawMenuBar().
OpenRomOrProject()
absl::Status yaze::editor::EditorManager::OpenRomOrProject (const std::string & filename) private
Definition at line 2190 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, yaze::editor::EditorSelectionDialog::ClearRecentEditors(), context_, current_editor_set_, current_project_, current_rom_, editor_selection_dialog_, yaze::editor::EditorManager::RomSession::editors, LoadAssets(), yaze::Rom::LoadFromFile(), yaze::core::YazeProject::Open(), OpenProject(), RETURN_IF_ERROR, yaze::editor::EditorManager::RomSession::rom, sessions_, show_editor_selection_, show_welcome_screen_, and user_settings_.
Referenced by DrawMenuBar(), and Initialize().
CreateNewProject()
absl::Status yaze::editor::EditorManager::CreateNewProject (const std::string & template_name = "Basic ROM Hack") private
Definition at line 2217 of file editor_manager.cc.
References popup_manager_, and yaze::util::FileDialogWrapper::ShowOpenFolderDialog().
Referenced by BuildModernMenu(), Initialize(), and SaveProject().
OpenProject()
absl::Status yaze::editor::EditorManager::OpenProject () private
Definition at line 2228 of file editor_manager.cc.
References yaze::editor::EditorSet::active_editors_, yaze::editor::EditorSet::assembly_editor_, yaze::core::WorkspaceSettings::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_interval, yaze::core::WorkspaceSettings::autosave_interval_secs, yaze::editor::EditorSelectionDialog::ClearRecentEditors(), yaze::core::YazeProject::code_folder, context_, current_editor_set_, current_project_, current_rom_, editor_selection_dialog_, yaze::editor::EditorManager::RomSession::editors, yaze::core::YazeProject::feature_flags, yaze::editor::EditorManager::RomSession::feature_flags, yaze::core::YazeProject::filepath, yaze::core::WorkspaceSettings::font_global_scale, yaze::editor::UserSettings::Preferences::font_global_scale, yaze::test::TestManager::Get(), yaze::core::YazeProject::GetDisplayName(), yaze::core::RecentFilesManager::GetInstance(), yaze::editor::kSuccess, yaze::editor::kWarning, yaze::core::YazeProject::labels_filename, LoadAssets(), yaze::Rom::LoadFromFile(), yaze::core::ResourceLabelManager::LoadLabels(), LOG_DEBUG, yaze::core::YazeProject::Open(), yaze::editor::AssemblyEditor::OpenFolder(), popup_manager_, yaze::editor::UserSettings::prefs(), yaze::Rom::resource_label(), RETURN_IF_ERROR, yaze::editor::EditorManager::RomSession::rom, yaze::core::YazeProject::rom_filename, sessions_, yaze::test::TestManager::SetCurrentRom(), yaze::editor::ToastManager::Show(), show_editor_selection_, show_welcome_screen_, yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::Rom::title(), toast_manager_, user_settings_, yaze::core::YazeProject::Validate(), and yaze::core::YazeProject::workspace_settings.
Referenced by BuildModernMenu(), and OpenRomOrProject().
SaveProject()
absl::Status yaze::editor::EditorManager::SaveProject () private
Definition at line 2314 of file editor_manager.cc.
References yaze::core::WorkspaceSettings::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_interval, yaze::core::WorkspaceSettings::autosave_interval_secs, CreateNewProject(), current_editor_set_, current_project_, current_rom_, yaze::core::YazeProject::feature_flags, yaze::core::WorkspaceSettings::font_global_scale, yaze::editor::UserSettings::Preferences::font_global_scale, GetCurrentSessionIndex(), yaze::core::RecentFilesManager::GetInstance(), yaze::editor::UserSettings::prefs(), yaze::core::YazeProject::project_opened(), yaze::core::WorkspaceSettings::recent_files, yaze::core::YazeProject::Save(), sessions_, user_settings_, and yaze::core::YazeProject::workspace_settings.
Referenced by BuildModernMenu().
SaveProjectAs()
absl::Status yaze::editor::EditorManager::SaveProjectAs () private
Definition at line 2342 of file editor_manager.cc.
References current_project_, yaze::core::YazeProject::filepath, yaze::core::YazeProject::GetDisplayName(), yaze::core::RecentFilesManager::GetInstance(), yaze::editor::kError, yaze::editor::kSuccess, yaze::core::YazeProject::project_opened(), yaze::core::YazeProject::Save(), yaze::editor::ToastManager::Show(), yaze::util::FileDialogWrapper::ShowSaveFileDialog(), and toast_manager_.
Referenced by BuildModernMenu().
ImportProject()
absl::Status yaze::editor::EditorManager::ImportProject (const std::string & project_path) private
Definition at line 2383 of file editor_manager.cc.
References current_project_, yaze::core::YazeProject::ImportZScreamProject(), yaze::editor::kInfo, yaze::core::YazeProject::Open(), RETURN_IF_ERROR, yaze::editor::ToastManager::Show(), and toast_manager_.
RepairCurrentProject()
absl::Status yaze::editor::EditorManager::RepairCurrentProject () private
Definition at line 2400 of file editor_manager.cc.
References current_project_, yaze::editor::kSuccess, yaze::core::YazeProject::project_opened(), yaze::core::YazeProject::RepairProject(), RETURN_IF_ERROR, yaze::editor::ToastManager::Show(), and toast_manager_.
ShowProjectHelp()
void yaze::editor::EditorManager::ShowProjectHelp () private
Definition at line 2412 of file editor_manager.cc.
References popup_manager_.
InitializeTestSuites()
void yaze::editor::EditorManager::InitializeTestSuites () private
Definition at line 91 of file editor_manager.cc.
References yaze::test::TestManager::Get(), and yaze::test::RegisterZ3edTestSuites().
Referenced by Initialize().
Member Data Documentation
quit_
bool yaze::editor::EditorManager::quit_ = false private
Definition at line 226 of file editor_manager.h.
Referenced by BuildModernMenu(), Initialize(), and quit().
new_project_menu
bool yaze::editor::EditorManager::new_project_menu = false private
Definition at line 227 of file editor_manager.h.
Referenced by DrawMenuBar().
show_emulator_
bool yaze::editor::EditorManager::show_emulator_ = false private
Definition at line 229 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), and Initialize().
show_memory_editor_
bool yaze::editor::EditorManager::show_memory_editor_ = false private
Definition at line 230 of file editor_manager.h.
Referenced by BuildModernMenu(), and DrawMenuBar().
show_asm_editor_
bool yaze::editor::EditorManager::show_asm_editor_ = false private
Definition at line 231 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), and Initialize().
show_imgui_metrics_
bool yaze::editor::EditorManager::show_imgui_metrics_ = false private
Definition at line 232 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), HideAllWindows(), LoadDesignerLayout(), LoadDeveloperLayout(), LoadModderLayout(), and ShowAllWindows().
show_imgui_demo_
bool yaze::editor::EditorManager::show_imgui_demo_ = false private
Definition at line 233 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), HideAllWindows(), and ShowAllWindows().
show_palette_editor_
bool yaze::editor::EditorManager::show_palette_editor_ = false private
Definition at line 234 of file editor_manager.h.
Referenced by DrawMenuBar().
show_resource_label_manager
bool yaze::editor::EditorManager::show_resource_label_manager = false private
Definition at line 235 of file editor_manager.h.
Referenced by DrawMenuBar().
show_workspace_layout
bool yaze::editor::EditorManager::show_workspace_layout = false private
Definition at line 236 of file editor_manager.h.
show_save_workspace_preset_
bool yaze::editor::EditorManager::show_save_workspace_preset_ = false private
Definition at line 237 of file editor_manager.h.
Referenced by DrawLayoutPresets(), and DrawMenuBar().
show_load_workspace_preset_
bool yaze::editor::EditorManager::show_load_workspace_preset_ = false private
Definition at line 238 of file editor_manager.h.
Referenced by DrawMenuBar().
show_session_switcher_
bool yaze::editor::EditorManager::show_session_switcher_ = false private
Definition at line 239 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawSessionSwitcher(), Initialize(), and ShowSessionSwitcher().
show_session_manager_
bool yaze::editor::EditorManager::show_session_manager_ = false private
Definition at line 240 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawSessionManager(), and DrawSessionSwitcher().
show_layout_presets_
bool yaze::editor::EditorManager::show_layout_presets_ = false private
Definition at line 241 of file editor_manager.h.
Referenced by BuildModernMenu(), and DrawLayoutPresets().
show_homepage_
bool yaze::editor::EditorManager::show_homepage_ = true private
Definition at line 242 of file editor_manager.h.
show_command_palette_
bool yaze::editor::EditorManager::show_command_palette_ = false private
Definition at line 243 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), and Initialize().
show_global_search_
bool yaze::editor::EditorManager::show_global_search_ = false private
Definition at line 244 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), and Initialize().
show_session_rename_dialog_
bool yaze::editor::EditorManager::show_session_rename_dialog_ = false private
Definition at line 245 of file editor_manager.h.
Referenced by DrawSessionManager(), DrawSessionRenameDialog(), and DrawSessionSwitcher().
show_welcome_screen_
bool yaze::editor::EditorManager::show_welcome_screen_ = false private
Definition at line 246 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), DrawWelcomeScreen(), Initialize(), LoadRom(), LoadUserSettings(), OpenProject(), OpenRomOrProject(), and Update().
welcome_screen_manually_closed_
bool yaze::editor::EditorManager::welcome_screen_manually_closed_ = false private
Definition at line 247 of file editor_manager.h.
Referenced by DrawWelcomeScreen(), Initialize(), LoadUserSettings(), and Update().
show_card_browser_
bool yaze::editor::EditorManager::show_card_browser_ = false private
Definition at line 248 of file editor_manager.h.
Referenced by BuildModernMenu(), Initialize(), and Update().
session_to_rename_
size_t yaze::editor::EditorManager::session_to_rename_ = 0 private
Definition at line 249 of file editor_manager.h.
Referenced by DrawSessionManager(), DrawSessionRenameDialog(), and DrawSessionSwitcher().
session_rename_buffer_
char yaze::editor::EditorManager::session_rename_buffer_[256] = {} private
Definition at line 250 of file editor_manager.h.
Referenced by DrawSessionManager(), DrawSessionRenameDialog(), and DrawSessionSwitcher().
show_test_dashboard_
bool yaze::editor::EditorManager::show_test_dashboard_ = false private
Definition at line 253 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), HideAllWindows(), Initialize(), LoadDesignerLayout(), LoadDeveloperLayout(), and ShowAllWindows().
show_performance_dashboard_
bool yaze::editor::EditorManager::show_performance_dashboard_ = false private
Definition at line 254 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), HideAllWindows(), ShowAllWindows(), and Update().
proposal_drawer_
ProposalDrawer yaze::editor::EditorManager::proposal_drawer_ private
Definition at line 257 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), Initialize(), and Update().
show_proposal_drawer_
bool yaze::editor::EditorManager::show_proposal_drawer_ = false private
Definition at line 258 of file editor_manager.h.
Referenced by BuildModernMenu().
agent_chat_history_popup_
AgentChatHistoryPopup yaze::editor::EditorManager::agent_chat_history_popup_ private
Definition at line 265 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), and Initialize().
show_chat_history_popup_
bool yaze::editor::EditorManager::show_chat_history_popup_ = false private
Definition at line 266 of file editor_manager.h.
project_file_editor_
ProjectFileEditor yaze::editor::EditorManager::project_file_editor_ private
Definition at line 269 of file editor_manager.h.
Referenced by DrawMenuBar(), and Initialize().
editor_selection_dialog_
EditorSelectionDialog yaze::editor::EditorManager::editor_selection_dialog_ private
Definition at line 272 of file editor_manager.h.
Referenced by Initialize(), LoadRom(), OpenProject(), OpenRomOrProject(), and Update().
show_editor_selection_
bool yaze::editor::EditorManager::show_editor_selection_ = false private
Definition at line 273 of file editor_manager.h.
Referenced by BuildModernMenu(), Initialize(), LoadRom(), OpenProject(), OpenRomOrProject(), ShowEditorSelection(), and Update().
welcome_screen_
WelcomeScreen yaze::editor::EditorManager::welcome_screen_ private
Definition at line 276 of file editor_manager.h.
Referenced by DrawWelcomeScreen(), and Initialize().
version_
std::string yaze::editor::EditorManager::version_ = "" private
Definition at line 284 of file editor_manager.h.
Referenced by DrawMenuBar(), DrawMenuBarExtras(), EditorManager(), and version().
status_
absl::Status yaze::editor::EditorManager::status_ private
Definition at line 285 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), Initialize(), and Update().
emulator_
emu::Emulator yaze::editor::EditorManager::emulator_ private
Definition at line 286 of file editor_manager.h.
Referenced by DrawMenuBar(), emulator(), Initialize(), and LoadAssets().
sessions_
std::deque<RomSession> yaze::editor::EditorManager::sessions_ private
Definition at line 312 of file editor_manager.h.
Referenced by BuildModernMenu(), CloseCurrentSession(), CreateNewSession(), DrawMenuBar(), DrawRomSelector(), DrawSessionManager(), DrawSessionRenameDialog(), DrawSessionSwitcher(), DuplicateCurrentSession(), GenerateUniqueEditorTitle(), GetActiveSessionCount(), GetCurrentFeatureFlags(), GetCurrentSessionIndex(), HasDuplicateSession(), LoadRom(), OpenProject(), OpenRomOrProject(), RemoveSession(), RenameSession(), SaveProject(), SaveRomAs(), SetCurrentRom(), SwitchToSession(), and Update().
current_rom_
Rom* yaze::editor::EditorManager::current_rom_ = nullptr private
Definition at line 313 of file editor_manager.h.
Referenced by BuildModernMenu(), CloseCurrentSession(), DrawMenuBar(), DrawRomSelector(), DrawSessionManager(), DrawSessionSwitcher(), DuplicateCurrentSession(), GetCurrentRom(), GetCurrentSessionIndex(), Initialize(), LoadAssets(), LoadRom(), OpenProject(), OpenRomOrProject(), SaveProject(), SaveRom(), SaveRomAs(), SetCurrentRom(), SwitchToSession(), and Update().
current_editor_set_
EditorSet* yaze::editor::EditorManager::current_editor_set_ = nullptr private
Definition at line 314 of file editor_manager.h.
Referenced by BuildModernMenu(), CloseCurrentSession(), DrawContextSensitiveCardControl(), DrawMenuBar(), GetCurrentEditorSet(), HideAllWindows(), Initialize(), JumpToDungeonRoom(), JumpToOverworldMap(), LoadAssets(), LoadDesignerLayout(), LoadDeveloperLayout(), LoadModderLayout(), LoadRom(), OpenEditorAndCardsFromFlags(), OpenProject(), OpenRomOrProject(), overworld(), SaveProject(), SaveRom(), SaveRomAs(), SetCurrentRom(), ShowAllWindows(), SwitchToEditor(), SwitchToSession(), and Update().
current_editor_
Editor* yaze::editor::EditorManager::current_editor_ = nullptr private
Definition at line 315 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawContextSensitiveCardControl(), Initialize(), and Update().
blank_editor_set_
EditorSet yaze::editor::EditorManager::blank_editor_set_ {} private
Definition at line 316 of file editor_manager.h.
Referenced by Initialize().
renderer_
gfx::IRenderer* yaze::editor::EditorManager::renderer_ = nullptr private
Definition at line 318 of file editor_manager.h.
Referenced by Initialize(), and LoadAssets().
current_project_
core::YazeProject yaze::editor::EditorManager::current_project_ private
Definition at line 320 of file editor_manager.h.
Referenced by BuildModernMenu(), DrawMenuBar(), ImportProject(), OpenProject(), OpenRomOrProject(), RepairCurrentProject(), SaveProject(), and SaveProjectAs().
context_
EditorContext yaze::editor::EditorManager::context_ private
Definition at line 321 of file editor_manager.h.
Referenced by CreateNewSession(), DrawMenuBar(), DuplicateCurrentSession(), EditorManager(), Initialize(), LoadRom(), OpenProject(), OpenRomOrProject(), and Update().
popup_manager_
std::unique_ptr<PopupManager> yaze::editor::EditorManager::popup_manager_ private
Definition at line 322 of file editor_manager.h.
Referenced by BuildModernMenu(), CreateNewProject(), CreateNewSession(), DrawMenuBar(), EditorManager(), Initialize(), OpenProject(), ResetWorkspaceLayout(), ShowDisplaySettings(), ShowProjectHelp(), and Update().
toast_manager_
ToastManager yaze::editor::EditorManager::toast_manager_ private
Definition at line 323 of file editor_manager.h.
Referenced by BuildModernMenu(), CloseAllFloatingWindows(), CloseCurrentSession(), CreateNewSession(), DrawLayoutPresets(), DrawMenuBar(), DrawSessionManager(), DuplicateCurrentSession(), HideAllWindows(), ImportProject(), Initialize(), LoadDesignerLayout(), LoadDeveloperLayout(), LoadModderLayout(), LoadRom(), LoadWorkspaceLayout(), MaximizeCurrentWindow(), OpenProject(), RemoveSession(), RenameSession(), RepairCurrentProject(), RestoreAllWindows(), SaveProjectAs(), SaveRomAs(), SaveWorkspaceLayout(), ShowAllWindows(), SwitchToSession(), and Update().
menu_builder_
MenuBuilder yaze::editor::EditorManager::menu_builder_ private
Definition at line 324 of file editor_manager.h.
Referenced by BuildModernMenu(), and menu_builder().
user_settings_
UserSettings yaze::editor::EditorManager::user_settings_ private
Definition at line 325 of file editor_manager.h.
Referenced by CreateNewSession(), DuplicateCurrentSession(), Initialize(), LoadRom(), LoadUserSettings(), OpenProject(), OpenRomOrProject(), SaveProject(), SaveRom(), SaveRomAs(), SaveUserSettings(), SetFontGlobalScale(), and Update().
workspace_manager_
WorkspaceManager yaze::editor::EditorManager::workspace_manager_ {&toast_manager_} private
Definition at line 326 of file editor_manager.h.
Referenced by DrawLayoutPresets(), DrawMenuBar(), LoadWorkspacePreset(), RefreshWorkspacePresets(), and SaveWorkspacePreset().
autosave_timer_
float yaze::editor::EditorManager::autosave_timer_ = 0.0f private
Definition at line 328 of file editor_manager.h.
Referenced by Update().
The documentation for this class was generated from the following files:
src/app/editor/editor_manager.h
src/app/editor/editor_manager.cc