yaze: yaze::editor::AgentChatWidget::AutomationCallbacks Struct Reference
yaze::editor::AgentChatWidget::AutomationCallbacks Struct Reference
#include <agent_chat_widget.h>
Public Attributes
std::function< void()> open_harness_dashboard
std::function< void()> replay_last_plan
std::function< void(const std::string &)> focus_proposal
std::function< void()> show_active_tests
Detailed Description
Definition at line 70 of file agent_chat_widget.h.
Member Data Documentation
open_harness_dashboard
std::function<void()> yaze::editor::AgentChatWidget::AutomationCallbacks::open_harness_dashboard
Definition at line 71 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderAutomationPanel(), and yaze::editor::AgentChatWidget::RenderHarnessPanel().
replay_last_plan
std::function<void()> yaze::editor::AgentChatWidget::AutomationCallbacks::replay_last_plan
Definition at line 72 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderAutomationPanel(), and yaze::editor::AgentChatWidget::RenderHarnessPanel().
focus_proposal
std::function<void(const std::string&)> yaze::editor::AgentChatWidget::AutomationCallbacks::focus_proposal
Definition at line 73 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), and yaze::editor::AgentChatWidget::RenderHarnessPanel().
show_active_tests
std::function<void()> yaze::editor::AgentChatWidget::AutomationCallbacks::show_active_tests
Definition at line 74 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderAutomationPanel(), and yaze::editor::AgentChatWidget::RenderHarnessPanel().
The documentation for this struct was generated from the following file:
src/app/editor/agent/agent_chat_widget.h