yaze: yaze::cli::PaletteImport Class Reference
yaze::cli::PaletteImport Class Reference
#include <z3ed.h>
Public Member Functions
absl::Status Run (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
virtual void RunTUI (ftxui::ScreenInteractive &screen)
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
Rom rom_
Detailed Description
Definition at line 90 of file z3ed.h.
Member Function Documentation
Run()
absl::Status yaze::cli::PaletteImport::Run (const std::vector< std::string > & arg_vec) override virtual
Todo:
Implement proper argument parsing
Todo:
Implement saving the modified palette back to the ROM.
Implements yaze::cli::CommandHandler.
Definition at line 90 of file palette.cc.
References yaze::gfx::DecodeColFile(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), yaze::Rom::palette_group(), and yaze::cli::CommandHandler::rom_.
Referenced by yaze::cli::ModernCLI::HandlePaletteImportCommand(), and yaze::cli::Palette::Run().
The documentation for this class was generated from the following files:
src/cli/z3ed.h
src/cli/handlers/palette.cc