yaze: yaze::zelda3::Zelda3Labels Struct Reference
yaze::zelda3::Zelda3Labels Struct Reference
Centralized default labels for all Zelda 3 resources.
#include <zelda3_labels.h>
Static Public Member Functions
static const std::vector< std::string > & GetRoomNames ()
static const std::vector< std::string > & GetEntranceNames ()
static const std::vector< std::string > & GetSpriteNames ()
static const std::vector< std::string > & GetOverlordNames ()
static const std::vector< std::string > & GetOverworldMapNames ()
static const std::vector< std::string > & GetItemNames ()
static const std::vector< std::string > & GetMusicTrackNames ()
static const std::vector< std::string > & GetGraphicsSheetNames ()
static const std::vector< std::string > & GetType1RoomObjectNames ()
static const std::vector< std::string > & GetType2RoomObjectNames ()
static const std::vector< std::string > & GetType3RoomObjectNames ()
static const std::vector< std::string > & GetRoomEffectNames ()
static const std::vector< std::string > & GetRoomTagNames ()
static const std::vector< std::string > & GetTileTypeNames ()
static std::unordered_map< std::string, std::unordered_map< std::string, std::string > > ToResourceLabels ()
Convert all labels to a structured map for project embedding.
static std::string GetLabel (const std::string &resource_type, int id, const std::string &default_value="")
Get a label by resource type and ID.
Detailed Description
Centralized default labels for all Zelda 3 resources.
This structure contains all the default names/labels for various game resources. These labels are embedded directly into the project file format and are always available to the AI agents (Ollama/Gemini) without requiring external files.
Definition at line 20 of file zelda3_labels.h.
Member Function Documentation
GetRoomNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetRoomNames () static
Definition at line 12 of file zelda3_labels.cc.
References yaze::zelda3::kRoomNames.
Referenced by ToResourceLabels().
GetEntranceNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetEntranceNames () static
Definition at line 23 of file zelda3_labels.cc.
References yaze::zelda3::kEntranceNames.
Referenced by ToResourceLabels().
GetSpriteNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetSpriteNames () static
Definition at line 34 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetOverlordNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetOverlordNames () static
Definition at line 45 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetOverworldMapNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetOverworldMapNames () static
Definition at line 56 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetItemNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetItemNames () static
Definition at line 108 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetMusicTrackNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetMusicTrackNames () static
Definition at line 141 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetGraphicsSheetNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetGraphicsSheetNames () static
Definition at line 160 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetType1RoomObjectNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetType1RoomObjectNames () static
Definition at line 186 of file zelda3_labels.cc.
GetType2RoomObjectNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetType2RoomObjectNames () static
Definition at line 205 of file zelda3_labels.cc.
GetType3RoomObjectNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetType3RoomObjectNames () static
Definition at line 215 of file zelda3_labels.cc.
GetRoomEffectNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetRoomEffectNames () static
Definition at line 226 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetRoomTagNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetRoomTagNames () static
Definition at line 237 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
GetTileTypeNames()
const std::vector< std::string > & yaze::zelda3::Zelda3Labels::GetTileTypeNames () static
Definition at line 247 of file zelda3_labels.cc.
Referenced by ToResourceLabels().
ToResourceLabels()
std::unordered_map< std::string, std::unordered_map< std::string, std::string > > yaze::zelda3::Zelda3Labels::ToResourceLabels () static
Convert all labels to a structured map for project embedding.
Returns
Map of resource type -> (id -> name) for all resources
Definition at line 277 of file zelda3_labels.cc.
References GetEntranceNames(), GetGraphicsSheetNames(), GetItemNames(), GetMusicTrackNames(), GetOverlordNames(), GetOverworldMapNames(), GetRoomEffectNames(), GetRoomNames(), GetRoomTagNames(), GetSpriteNames(), and GetTileTypeNames().
Referenced by GetLabel(), and yaze::core::YazeProject::InitializeEmbeddedLabels().
GetLabel()
std::string yaze::zelda3::Zelda3Labels::GetLabel (const std::string & resource_type, int id, const std::string & default_value = "") static
Get a label by resource type and ID.
Parameters
resource_type The type of resource (e.g., "room", "entrance", "sprite")
id The numeric ID of the resource
default_value Fallback value if label not found
Returns
The label string
Definition at line 350 of file zelda3_labels.cc.
References ToResourceLabels().
Referenced by yaze::core::YazeProject::GetLabel().
The documentation for this struct was generated from the following files:
src/app/zelda3/zelda3_labels.h
src/app/zelda3/zelda3_labels.cc