yaze: yaze::cli::anonymous_namespace{tui.cc} Namespace Reference
yaze::cli::anonymous_namespace{tui.cc} Namespace Reference
Functions
void SwitchComponents (ftxui::ScreenInteractive &screen, LayoutID layout)
bool HandleInput (ftxui::ScreenInteractive &screen, ftxui::Event &event, int &selected)
void ReturnIfRomNotLoaded (ftxui::ScreenInteractive &screen)
void ApplyBpsPatchComponent (ftxui::ScreenInteractive &screen)
void GenerateSaveFileComponent (ftxui::ScreenInteractive &screen)
void TodoManagerComponent (ftxui::ScreenInteractive &screen)
void ApplyAsarPatchComponent (ftxui::ScreenInteractive &screen)
void PaletteEditorComponent (ftxui::ScreenInteractive &screen)
void ExtractSymbolsComponent (ftxui::ScreenInteractive &screen)
void ValidateAssemblyComponent (ftxui::ScreenInteractive &screen)
void LoadRomComponent (ftxui::ScreenInteractive &screen)
Element ColorBox (const Color &color)
void HelpComponent (ftxui::ScreenInteractive &screen)
void HexViewerComponent (ftxui::ScreenInteractive &screen)
void DashboardComponent (ftxui::ScreenInteractive &screen)
void MainMenuComponent (ftxui::ScreenInteractive &screen)
Function Documentation
SwitchComponents()
void yaze::cli::anonymous_namespace{tui.cc}::SwitchComponents (ftxui::ScreenInteractive & screen, LayoutID layout)
Definition at line 28 of file tui.cc.
References SwitchComponents().
Referenced by ApplyBpsPatchComponent(), DashboardComponent(), ExtractSymbolsComponent(), GenerateSaveFileComponent(), HandleInput(), HelpComponent(), HexViewerComponent(), LoadRomComponent(), MainMenuComponent(), PaletteEditorComponent(), ReturnIfRomNotLoaded(), SwitchComponents(), and ValidateAssemblyComponent().
HandleInput()
bool yaze::cli::anonymous_namespace{tui.cc}::HandleInput (ftxui::ScreenInteractive & screen, ftxui::Event & event, int & selected)
Definition at line 34 of file tui.cc.
References HandleInput(), yaze::cli::kExit, and SwitchComponents().
Referenced by HandleInput(), and MainMenuComponent().
ReturnIfRomNotLoaded()
void yaze::cli::anonymous_namespace{tui.cc}::ReturnIfRomNotLoaded (ftxui::ScreenInteractive & screen)
Definition at line 51 of file tui.cc.
References yaze::cli::kError, ReturnIfRomNotLoaded(), and SwitchComponents().
Referenced by ApplyAsarPatchComponent(), HexViewerComponent(), PaletteEditorComponent(), and ReturnIfRomNotLoaded().
ApplyBpsPatchComponent()
void yaze::cli::anonymous_namespace{tui.cc}::ApplyBpsPatchComponent (ftxui::ScreenInteractive & screen)
Definition at line 58 of file tui.cc.
References yaze::util::ApplyBpsPatch(), ApplyBpsPatchComponent(), yaze::cli::kError, yaze::cli::kMainMenu, yaze::util::LoadFile(), and SwitchComponents().
Referenced by ApplyBpsPatchComponent().
GenerateSaveFileComponent()
void yaze::cli::anonymous_namespace{tui.cc}::GenerateSaveFileComponent (ftxui::ScreenInteractive & screen)
Definition at line 133 of file tui.cc.
References GenerateSaveFileComponent(), yaze::cli::kMainMenu, and SwitchComponents().
Referenced by GenerateSaveFileComponent().
TodoManagerComponent()
void yaze::cli::anonymous_namespace{tui.cc}::TodoManagerComponent (ftxui::ScreenInteractive & screen)
Definition at line 229 of file tui.cc.
References yaze::cli::agent::TodoItem::BLOCKED, yaze::cli::agent::TodoItem::CANCELLED, yaze::cli::agent::TodoItem::COMPLETED, yaze::cli::agent::TodoManager::GetAllTodos(), yaze::cli::agent::TodoItem::IN_PROGRESS, yaze::cli::agent::TodoManager::Initialize(), yaze::cli::agent::TodoItem::PENDING, and TodoManagerComponent().
Referenced by TodoManagerComponent().
ApplyAsarPatchComponent()
void yaze::cli::anonymous_namespace{tui.cc}::ApplyAsarPatchComponent (ftxui::ScreenInteractive & screen)
Definition at line 314 of file tui.cc.
References ApplyAsarPatchComponent(), and ReturnIfRomNotLoaded().
Referenced by ApplyAsarPatchComponent().
PaletteEditorComponent()
void yaze::cli::anonymous_namespace{tui.cc}::PaletteEditorComponent (ftxui::ScreenInteractive & screen)
Definition at line 382 of file tui.cc.
References ReturnIfRomNotLoaded(), and SwitchComponents().
ExtractSymbolsComponent()
void yaze::cli::anonymous_namespace{tui.cc}::ExtractSymbolsComponent (ftxui::ScreenInteractive & screen)
Definition at line 402 of file tui.cc.
References ExtractSymbolsComponent(), and SwitchComponents().
Referenced by ExtractSymbolsComponent().
ValidateAssemblyComponent()
void yaze::cli::anonymous_namespace{tui.cc}::ValidateAssemblyComponent (ftxui::ScreenInteractive & screen)
Definition at line 495 of file tui.cc.
References SwitchComponents(), and ValidateAssemblyComponent().
Referenced by ValidateAssemblyComponent().
LoadRomComponent()
void yaze::cli::anonymous_namespace{tui.cc}::LoadRomComponent (ftxui::ScreenInteractive & screen)
Todo:
Implement file dialog
Definition at line 568 of file tui.cc.
References LoadRomComponent(), and SwitchComponents().
Referenced by LoadRomComponent().
ColorBox()
Element yaze::cli::anonymous_namespace{tui.cc}::ColorBox (const Color & color)
Definition at line 619 of file tui.cc.
References ColorBox().
Referenced by ColorBox().
HelpComponent()
void yaze::cli::anonymous_namespace{tui.cc}::HelpComponent (ftxui::ScreenInteractive & screen)
Definition at line 625 of file tui.cc.
References HelpComponent(), and SwitchComponents().
Referenced by HelpComponent().
HexViewerComponent()
void yaze::cli::anonymous_namespace{tui.cc}::HexViewerComponent (ftxui::ScreenInteractive & screen)
Definition at line 766 of file tui.cc.
References HexViewerComponent(), ReturnIfRomNotLoaded(), and SwitchComponents().
Referenced by HexViewerComponent().
DashboardComponent()
void yaze::cli::anonymous_namespace{tui.cc}::DashboardComponent (ftxui::ScreenInteractive & screen)
Definition at line 832 of file tui.cc.
References DashboardComponent(), yaze::cli::GetColoredLogo(), yaze::cli::kMainMenuEntries, and SwitchComponents().
Referenced by DashboardComponent().
MainMenuComponent()
void yaze::cli::anonymous_namespace{tui.cc}::MainMenuComponent (ftxui::ScreenInteractive & screen)
Definition at line 893 of file tui.cc.
References HandleInput(), yaze::cli::kMainMenuEntries, MainMenuComponent(), and SwitchComponents().
Referenced by MainMenuComponent().