yaze: yaze::zelda3::DungeonObjectEditor Class Reference
yaze::zelda3::DungeonObjectEditor Class Reference
Interactive dungeon object editor with scroll wheel support.
#include <dungeon_object_editor.h>
Classes
struct EditingState
struct EditorConfig
struct SelectionState
struct UndoPoint
Public Types
enum class Mode {
kSelect , kInsert , kDelete , kEdit ,
kLayer , kPreview
}
using ObjectChangedCallback = std::function< void(size_t object_index, const RoomObject &object)>
using RoomChangedCallback = std::function< void()>
using SelectionChangedCallback = std::function< void(const SelectionState &)>
Public Member Functions
DungeonObjectEditor (Rom *rom)
~DungeonObjectEditor ()=default
absl::Status LoadRoom (int room_id)
absl::Status SaveRoom ()
absl::Status ClearRoom ()
absl::Status InsertObject (int x, int y, int object_type, int size=0x12, int layer=0)
absl::Status DeleteObject (size_t object_index)
absl::Status DeleteSelectedObjects ()
absl::Status MoveObject (size_t object_index, int new_x, int new_y)
absl::Status ResizeObject (size_t object_index, int new_size)
absl::Status ChangeObjectType (size_t object_index, int new_type)
absl::Status ChangeObjectLayer (size_t object_index, int new_layer)
absl::Status SelectObject (int screen_x, int screen_y)
absl::Status SelectObjects (int start_x, int start_y, int end_x, int end_y)
absl::Status ClearSelection ()
absl::Status AddToSelection (size_t object_index)
absl::Status RemoveFromSelection (size_t object_index)
absl::Status HandleMouseClick (int x, int y, bool left_button, bool right_button, bool shift_pressed)
absl::Status HandleMouseDrag (int start_x, int start_y, int current_x, int current_y)
absl::Status HandleMouseRelease (int x, int y)
absl::Status HandleScrollWheel (int delta, int x, int y, bool ctrl_pressed)
absl::Status HandleKeyPress (int key_code, bool ctrl_pressed, bool shift_pressed)
void SetMode (Mode mode)
Mode GetMode () const
void SetCurrentLayer (int layer)
int GetCurrentLayer () const
absl::StatusOr< std::vector< RoomObject > > GetObjectsByLayer (int layer)
absl::Status MoveObjectToLayer (size_t object_index, int layer)
void SetCurrentObjectType (int object_type)
int GetCurrentObjectType () const
absl::StatusOr< std::vector< int > > GetAvailableObjectTypes ()
absl::Status ValidateObjectType (int object_type)
absl::StatusOr< gfx::Bitmap > RenderRoom ()
absl::StatusOr< gfx::Bitmap > RenderPreview (int x, int y)
void SetPreviewPosition (int x, int y)
void UpdatePreview ()
void RenderSelectionHighlight (gfx::Bitmap &canvas)
void RenderLayerVisualization (gfx::Bitmap &canvas)
void RenderObjectPropertyPanel ()
void RenderLayerControls ()
absl::Status HandleDragOperation (int current_x, int current_y)
absl::Status Undo ()
absl::Status Redo ()
bool CanUndo () const
bool CanRedo () const
void ClearHistory ()
void SetROM (Rom *rom)
void SetConfig (const EditorConfig &config)
EditorConfig GetConfig () const
void SetSnapToGrid (bool enabled)
void SetGridSize (int size)
void SetShowGrid (bool enabled)
absl::Status ValidateRoom ()
absl::Status ValidateObject (const RoomObject &object)
std::vector< std::string > GetValidationErrors ()
void SetObjectChangedCallback (ObjectChangedCallback callback)
void SetRoomChangedCallback (RoomChangedCallback callback)
void SetSelectionChangedCallback (SelectionChangedCallback callback)
const Room & GetRoom () const
Room * GetMutableRoom ()
const SelectionState & GetSelection () const
const EditingState & GetEditingState () const
size_t GetObjectCount () const
const std::vector< RoomObject > & GetObjects () const
Private Member Functions
absl::Status InitializeEditor ()
absl::Status CreateUndoPoint ()
absl::Status ApplyUndoPoint (const UndoPoint &undo_point)
std::pair< int, int > ScreenToRoomCoordinates (int screen_x, int screen_y)
std::pair< int, int > RoomToScreenCoordinates (int room_x, int room_y)
int SnapToGrid (int coordinate)
std::optional< size_t > FindObjectAt (int room_x, int room_y)
std::vector< size_t > FindObjectsInArea (int start_x, int start_y, int end_x, int end_y)
bool IsObjectAtPosition (const RoomObject &object, int x, int y)
bool ObjectsCollide (const RoomObject &obj1, const RoomObject &obj2)
absl::StatusOr< gfx::Bitmap > RenderObjectPreview (int object_type, int x, int y, int size)
void UpdatePreviewObject ()
absl::Status ValidatePreviewPosition (int x, int y)
absl::Status HandleSizeEdit (int delta, int x, int y)
int GetNextSize (int current_size, int delta)
int GetPreviousSize (int current_size, int delta)
bool IsValidSize (int size)
Private Attributes
Rom * rom_
std::unique_ptr< Room > current_room_
std::unique_ptr< ObjectRenderer > renderer_
SelectionState selection_state_
EditingState editing_state_
EditorConfig config_
std::vector< UndoPoint > undo_history_
std::vector< UndoPoint > redo_history_
std::optional< RoomObject > preview_object_
bool preview_visible_ = false
ObjectChangedCallback object_changed_callback_
RoomChangedCallback room_changed_callback_
SelectionChangedCallback selection_changed_callback_
std::vector< RoomObject > empty_objects_
Static Private Attributes
static constexpr size_t kMaxUndoHistory = 50
static constexpr int kMinObjectSize = 0x00
static constexpr int kMaxObjectSize = 0xFF
static constexpr int kDefaultObjectSize = 0x12
static constexpr int kMinLayer = 0
static constexpr int kMaxLayer = 2
Detailed Description
Interactive dungeon object editor with scroll wheel support.
This class provides a comprehensive object editing system for dungeon rooms, including:
Object insertion and deletion
Object size editing with scroll wheel
Object position editing with mouse
Layer management
Real-time preview and validation
Undo/redo functionality
Object property editing
Definition at line 36 of file dungeon_object_editor.h.
Member Typedef Documentation
ObjectChangedCallback
using yaze::zelda3::DungeonObjectEditor::ObjectChangedCallback = std::function<void(size_t object_index, const RoomObject& object)>
Definition at line 186 of file dungeon_object_editor.h.
RoomChangedCallback
using yaze::zelda3::DungeonObjectEditor::RoomChangedCallback = std::function<void()>
Definition at line 188 of file dungeon_object_editor.h.
SelectionChangedCallback
using yaze::zelda3::DungeonObjectEditor::SelectionChangedCallback = std::function<void(const SelectionState&)>
Definition at line 189 of file dungeon_object_editor.h.
Member Enumeration Documentation
Mode
enum class yaze::zelda3::DungeonObjectEditor::Mode strong
Enumerator
kSelect
kInsert
kDelete
kEdit
kLayer
kPreview
Definition at line 39 of file dungeon_object_editor.h.
Constructor & Destructor Documentation
DungeonObjectEditor()
yaze::zelda3::DungeonObjectEditor::DungeonObjectEditor (Rom * rom) explicit
Definition at line 16 of file dungeon_object_editor.cc.
References renderer_.
~DungeonObjectEditor()
yaze::zelda3::DungeonObjectEditor::~DungeonObjectEditor () default
Member Function Documentation
LoadRoom()
absl::Status yaze::zelda3::DungeonObjectEditor::LoadRoom (int room_id)
Definition at line 47 of file dungeon_object_editor.cc.
References ClearSelection(), CreateUndoPoint(), yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, current_room_, editing_state_, yaze::zelda3::DungeonObjectEditor::EditingState::is_editing_position, yaze::zelda3::DungeonObjectEditor::EditingState::is_editing_size, yaze::zelda3::NumberOfRooms, rom_, and room_changed_callback_.
SaveRoom()
absl::Status yaze::zelda3::DungeonObjectEditor::SaveRoom ()
Definition at line 81 of file dungeon_object_editor.cc.
References config_, current_room_, yaze::zelda3::DungeonObjectEditor::EditorConfig::validate_objects, and ValidateRoom().
ClearRoom()
absl::Status yaze::zelda3::DungeonObjectEditor::ClearRoom ()
Definition at line 98 of file dungeon_object_editor.cc.
References ClearSelection(), CreateUndoPoint(), current_room_, and room_changed_callback_.
InsertObject()
absl::Status yaze::zelda3::DungeonObjectEditor::InsertObject (int x, int y, int object_type, int size = 0x12, int layer = 0)
Definition at line 123 of file dungeon_object_editor.cc.
References ClearSelection(), config_, CreateUndoPoint(), current_room_, yaze::zelda3::RoomObject::EnsureTilesLoaded(), kMaxLayer, kMaxObjectSize, object_changed_callback_, ObjectsCollide(), rom_, room_changed_callback_, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_changed_callback_, selection_state_, yaze::zelda3::RoomObject::set_rom(), yaze::zelda3::DungeonObjectEditor::EditorConfig::snap_to_grid, SnapToGrid(), and yaze::zelda3::DungeonObjectEditor::EditorConfig::validate_objects.
Referenced by HandleMouseClick().
DeleteObject()
absl::Status yaze::zelda3::DungeonObjectEditor::DeleteObject (size_t object_index)
Definition at line 193 of file dungeon_object_editor.cc.
References CreateUndoPoint(), current_room_, room_changed_callback_, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_changed_callback_, and selection_state_.
Referenced by HandleMouseClick(), and RenderObjectPropertyPanel().
DeleteSelectedObjects()
absl::Status yaze::zelda3::DungeonObjectEditor::DeleteSelectedObjects ()
Definition at line 239 of file dungeon_object_editor.cc.
References ClearSelection(), CreateUndoPoint(), current_room_, room_changed_callback_, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, and selection_state_.
Referenced by RenderObjectPropertyPanel().
MoveObject()
absl::Status yaze::zelda3::DungeonObjectEditor::MoveObject (size_t object_index, int new_x, int new_y)
Definition at line 276 of file dungeon_object_editor.cc.
References config_, CreateUndoPoint(), current_room_, object_changed_callback_, ObjectsCollide(), room_changed_callback_, yaze::zelda3::RoomObject::set_x(), yaze::zelda3::RoomObject::set_y(), yaze::zelda3::DungeonObjectEditor::EditorConfig::snap_to_grid, SnapToGrid(), and yaze::zelda3::DungeonObjectEditor::EditorConfig::validate_objects.
ResizeObject()
absl::Status yaze::zelda3::DungeonObjectEditor::ResizeObject (size_t object_index, int new_size)
Definition at line 329 of file dungeon_object_editor.cc.
References CreateUndoPoint(), current_room_, kMaxObjectSize, object_changed_callback_, and room_changed_callback_.
Referenced by HandleSizeEdit().
ChangeObjectType()
absl::Status yaze::zelda3::DungeonObjectEditor::ChangeObjectType (size_t object_index, int new_type)
ChangeObjectLayer()
absl::Status yaze::zelda3::DungeonObjectEditor::ChangeObjectLayer (size_t object_index, int new_layer)
SelectObject()
absl::Status yaze::zelda3::DungeonObjectEditor::SelectObject (int screen_x, int screen_y)
Definition at line 564 of file dungeon_object_editor.cc.
References ClearSelection(), current_room_, FindObjectAt(), ScreenToRoomCoordinates(), yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_changed_callback_, and selection_state_.
Referenced by HandleMouseClick().
SelectObjects()
absl::Status yaze::zelda3::DungeonObjectEditor::SelectObjects (int start_x, int start_y, int end_x, int end_y)
ClearSelection()
absl::Status yaze::zelda3::DungeonObjectEditor::ClearSelection ()
Definition at line 592 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::SelectionState::is_dragging, yaze::zelda3::DungeonObjectEditor::SelectionState::is_multi_select, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_changed_callback_, and selection_state_.
Referenced by ClearRoom(), DeleteSelectedObjects(), InsertObject(), LoadRoom(), RenderObjectPropertyPanel(), and SelectObject().
AddToSelection()
absl::Status yaze::zelda3::DungeonObjectEditor::AddToSelection (size_t object_index)
Definition at line 605 of file dungeon_object_editor.cc.
References current_room_, yaze::zelda3::DungeonObjectEditor::SelectionState::is_multi_select, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_changed_callback_, and selection_state_.
Referenced by HandleMouseClick().
RemoveFromSelection()
absl::Status yaze::zelda3::DungeonObjectEditor::RemoveFromSelection (size_t object_index)
HandleMouseClick()
absl::Status yaze::zelda3::DungeonObjectEditor::HandleMouseClick (int x, int y, bool left_button, bool right_button, bool shift_pressed)
Todo:
Show context menu
Definition at line 456 of file dungeon_object_editor.cc.
References AddToSelection(), yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, yaze::zelda3::DungeonObjectEditor::EditingState::current_mode, yaze::zelda3::DungeonObjectEditor::EditingState::current_object_type, current_room_, DeleteObject(), editing_state_, FindObjectAt(), InsertObject(), kDelete, kEdit, kInsert, kSelect, yaze::zelda3::DungeonObjectEditor::EditingState::preview_size, ScreenToRoomCoordinates(), and SelectObject().
HandleMouseDrag()
absl::Status yaze::zelda3::DungeonObjectEditor::HandleMouseDrag (int start_x, int start_y, int current_x, int current_y)
Definition at line 524 of file dungeon_object_editor.cc.
References CreateUndoPoint(), current_room_, yaze::zelda3::DungeonObjectEditor::SelectionState::drag_start_x, yaze::zelda3::DungeonObjectEditor::SelectionState::drag_start_y, HandleDragOperation(), yaze::zelda3::DungeonObjectEditor::SelectionState::is_dragging, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, and selection_state_.
HandleMouseRelease()
absl::Status yaze::zelda3::DungeonObjectEditor::HandleMouseRelease (int x, int y)
Definition at line 546 of file dungeon_object_editor.cc.
References current_room_, yaze::zelda3::DungeonObjectEditor::SelectionState::is_dragging, room_changed_callback_, and selection_state_.
HandleScrollWheel()
absl::Status yaze::zelda3::DungeonObjectEditor::HandleScrollWheel (int delta, int x, int y, bool ctrl_pressed)
Definition at line 364 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, yaze::zelda3::DungeonObjectEditor::EditingState::current_mode, current_room_, editing_state_, HandleSizeEdit(), kEdit, kInsert, kMaxLayer, kMinLayer, ScreenToRoomCoordinates(), yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_state_, and SetCurrentLayer().
HandleKeyPress()
absl::Status yaze::zelda3::DungeonObjectEditor::HandleKeyPress (int key_code, bool ctrl_pressed, bool shift_pressed)
SetMode()
void yaze::zelda3::DungeonObjectEditor::SetMode (Mode mode)
Definition at line 631 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_mode, editing_state_, and UpdatePreviewObject().
GetMode()
Mode yaze::zelda3::DungeonObjectEditor::GetMode () const inline
Definition at line 136 of file dungeon_object_editor.h.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_mode, and editing_state_.
SetCurrentLayer()
void yaze::zelda3::DungeonObjectEditor::SetCurrentLayer (int layer)
Definition at line 638 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, editing_state_, kMaxLayer, kMinLayer, and UpdatePreviewObject().
Referenced by HandleScrollWheel().
GetCurrentLayer()
int yaze::zelda3::DungeonObjectEditor::GetCurrentLayer () const inline
Definition at line 140 of file dungeon_object_editor.h.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, and editing_state_.
GetObjectsByLayer()
absl::StatusOr< std::vector< RoomObject > > yaze::zelda3::DungeonObjectEditor::GetObjectsByLayer (int layer)
MoveObjectToLayer()
absl::Status yaze::zelda3::DungeonObjectEditor::MoveObjectToLayer (size_t object_index, int layer)
SetCurrentObjectType()
void yaze::zelda3::DungeonObjectEditor::SetCurrentObjectType (int object_type)
Definition at line 645 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_object_type, editing_state_, and UpdatePreviewObject().
GetCurrentObjectType()
int yaze::zelda3::DungeonObjectEditor::GetCurrentObjectType () const inline
Definition at line 146 of file dungeon_object_editor.h.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_object_type, and editing_state_.
GetAvailableObjectTypes()
absl::StatusOr< std::vector< int > > yaze::zelda3::DungeonObjectEditor::GetAvailableObjectTypes ()
ValidateObjectType()
absl::Status yaze::zelda3::DungeonObjectEditor::ValidateObjectType (int object_type)
RenderRoom()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::DungeonObjectEditor::RenderRoom ()
Definition at line 1156 of file dungeon_object_editor.cc.
References yaze::gfx::SnesPalette::AddColor(), current_room_, and renderer_.
RenderPreview()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::DungeonObjectEditor::RenderPreview (int x, int y)
SetPreviewPosition()
void yaze::zelda3::DungeonObjectEditor::SetPreviewPosition (int x, int y)
UpdatePreview()
void yaze::zelda3::DungeonObjectEditor::UpdatePreview ()
RenderSelectionHighlight()
void yaze::zelda3::DungeonObjectEditor::RenderSelectionHighlight (gfx::Bitmap & canvas)
Definition at line 895 of file dungeon_object_editor.cc.
References config_, current_room_, yaze::gfx::Bitmap::height(), yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, yaze::zelda3::DungeonObjectEditor::EditorConfig::selection_color, selection_state_, yaze::gfx::Bitmap::SetPixel(), yaze::zelda3::DungeonObjectEditor::EditorConfig::show_selection_highlight, and yaze::gfx::Bitmap::width().
RenderLayerVisualization()
void yaze::zelda3::DungeonObjectEditor::RenderLayerVisualization (gfx::Bitmap & canvas)
Definition at line 927 of file dungeon_object_editor.cc.
References config_, current_room_, yaze::gfx::Bitmap::height(), yaze::zelda3::DungeonObjectEditor::EditorConfig::layer0_color, yaze::zelda3::DungeonObjectEditor::EditorConfig::layer1_color, yaze::zelda3::DungeonObjectEditor::EditorConfig::layer2_color, yaze::gfx::Bitmap::SetPixel(), yaze::zelda3::DungeonObjectEditor::EditorConfig::show_layer_colors, and yaze::gfx::Bitmap::width().
RenderObjectPropertyPanel()
void yaze::zelda3::DungeonObjectEditor::RenderObjectPropertyPanel ()
Definition at line 962 of file dungeon_object_editor.cc.
References ClearSelection(), config_, current_room_, DeleteObject(), DeleteSelectedObjects(), object_changed_callback_, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_state_, yaze::zelda3::RoomObject::set_x(), and yaze::zelda3::DungeonObjectEditor::EditorConfig::show_property_panel.
RenderLayerControls()
void yaze::zelda3::DungeonObjectEditor::RenderLayerControls ()
Definition at line 1062 of file dungeon_object_editor.cc.
References config_, yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, current_room_, editing_state_, yaze::zelda3::DungeonObjectEditor::EditorConfig::layer0_color, yaze::zelda3::DungeonObjectEditor::EditorConfig::layer1_color, yaze::zelda3::DungeonObjectEditor::EditorConfig::layer2_color, and yaze::zelda3::DungeonObjectEditor::EditorConfig::show_layer_colors.
HandleDragOperation()
absl::Status yaze::zelda3::DungeonObjectEditor::HandleDragOperation (int current_x, int current_y)
Definition at line 1112 of file dungeon_object_editor.cc.
References config_, current_room_, yaze::zelda3::DungeonObjectEditor::SelectionState::drag_start_x, yaze::zelda3::DungeonObjectEditor::SelectionState::drag_start_y, yaze::zelda3::DungeonObjectEditor::EditorConfig::grid_size, yaze::zelda3::DungeonObjectEditor::SelectionState::is_dragging, object_changed_callback_, yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, and selection_state_.
Referenced by HandleMouseDrag().
Undo()
absl::Status yaze::zelda3::DungeonObjectEditor::Undo ()
Definition at line 788 of file dungeon_object_editor.cc.
References ApplyUndoPoint(), CanUndo(), current_room_, yaze::zelda3::DungeonObjectEditor::UndoPoint::editing, editing_state_, yaze::zelda3::DungeonObjectEditor::UndoPoint::objects, redo_history_, yaze::zelda3::DungeonObjectEditor::UndoPoint::selection, selection_state_, yaze::zelda3::DungeonObjectEditor::UndoPoint::timestamp, and undo_history_.
Redo()
absl::Status yaze::zelda3::DungeonObjectEditor::Redo ()
Definition at line 809 of file dungeon_object_editor.cc.
References ApplyUndoPoint(), CanRedo(), current_room_, yaze::zelda3::DungeonObjectEditor::UndoPoint::editing, editing_state_, yaze::zelda3::DungeonObjectEditor::UndoPoint::objects, redo_history_, yaze::zelda3::DungeonObjectEditor::UndoPoint::selection, selection_state_, yaze::zelda3::DungeonObjectEditor::UndoPoint::timestamp, and undo_history_.
CanUndo()
bool yaze::zelda3::DungeonObjectEditor::CanUndo () const
Definition at line 857 of file dungeon_object_editor.cc.
References undo_history_.
Referenced by Undo().
CanRedo()
bool yaze::zelda3::DungeonObjectEditor::CanRedo () const
Definition at line 861 of file dungeon_object_editor.cc.
References redo_history_.
Referenced by Redo().
ClearHistory()
void yaze::zelda3::DungeonObjectEditor::ClearHistory ()
Definition at line 865 of file dungeon_object_editor.cc.
References redo_history_, and undo_history_.
SetROM()
void yaze::zelda3::DungeonObjectEditor::SetROM (Rom * rom)
Definition at line 1214 of file dungeon_object_editor.cc.
References InitializeEditor(), renderer_, and rom_.
SetConfig()
void yaze::zelda3::DungeonObjectEditor::SetConfig (const EditorConfig & config)
Definition at line 1210 of file dungeon_object_editor.cc.
References config_.
GetConfig()
EditorConfig yaze::zelda3::DungeonObjectEditor::GetConfig () const inline
Definition at line 175 of file dungeon_object_editor.h.
References config_.
SetSnapToGrid()
void yaze::zelda3::DungeonObjectEditor::SetSnapToGrid (bool enabled)
SetGridSize()
void yaze::zelda3::DungeonObjectEditor::SetGridSize (int size)
SetShowGrid()
void yaze::zelda3::DungeonObjectEditor::SetShowGrid (bool enabled)
ValidateRoom()
absl::Status yaze::zelda3::DungeonObjectEditor::ValidateRoom ()
Definition at line 1177 of file dungeon_object_editor.cc.
References config_, current_room_, ObjectsCollide(), and yaze::zelda3::DungeonObjectEditor::EditorConfig::validate_objects.
Referenced by SaveRoom().
ValidateObject()
absl::Status yaze::zelda3::DungeonObjectEditor::ValidateObject (const RoomObject & object)
GetValidationErrors()
std::vector< std::string > yaze::zelda3::DungeonObjectEditor::GetValidationErrors ()
SetObjectChangedCallback()
void yaze::zelda3::DungeonObjectEditor::SetObjectChangedCallback (ObjectChangedCallback callback)
Definition at line 1198 of file dungeon_object_editor.cc.
References object_changed_callback_.
SetRoomChangedCallback()
void yaze::zelda3::DungeonObjectEditor::SetRoomChangedCallback (RoomChangedCallback callback)
Definition at line 1202 of file dungeon_object_editor.cc.
References room_changed_callback_.
SetSelectionChangedCallback()
void yaze::zelda3::DungeonObjectEditor::SetSelectionChangedCallback (SelectionChangedCallback callback)
Definition at line 1206 of file dungeon_object_editor.cc.
References selection_changed_callback_.
GetRoom()
const Room & yaze::zelda3::DungeonObjectEditor::GetRoom () const inline
Definition at line 196 of file dungeon_object_editor.h.
References current_room_.
GetMutableRoom()
Room * yaze::zelda3::DungeonObjectEditor::GetMutableRoom () inline
Definition at line 197 of file dungeon_object_editor.h.
References current_room_.
GetSelection()
const SelectionState & yaze::zelda3::DungeonObjectEditor::GetSelection () const inline
Definition at line 198 of file dungeon_object_editor.h.
References selection_state_.
GetEditingState()
const EditingState & yaze::zelda3::DungeonObjectEditor::GetEditingState () const inline
Definition at line 199 of file dungeon_object_editor.h.
References editing_state_.
GetObjectCount()
size_t yaze::zelda3::DungeonObjectEditor::GetObjectCount () const inline
Definition at line 200 of file dungeon_object_editor.h.
References current_room_.
GetObjects()
const std::vector< RoomObject > & yaze::zelda3::DungeonObjectEditor::GetObjects () const inline
Definition at line 203 of file dungeon_object_editor.h.
References current_room_, and empty_objects_.
InitializeEditor()
absl::Status yaze::zelda3::DungeonObjectEditor::InitializeEditor () private
Definition at line 20 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::EditorConfig::auto_save, yaze::zelda3::DungeonObjectEditor::EditorConfig::auto_save_interval, config_, yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, yaze::zelda3::DungeonObjectEditor::EditingState::current_mode, yaze::zelda3::DungeonObjectEditor::EditingState::current_object_type, current_room_, editing_state_, yaze::zelda3::DungeonObjectEditor::EditorConfig::grid_size, kDefaultObjectSize, kSelect, yaze::zelda3::DungeonObjectEditor::EditingState::preview_size, rom_, yaze::zelda3::DungeonObjectEditor::EditorConfig::show_collision_bounds, yaze::zelda3::DungeonObjectEditor::EditorConfig::show_grid, yaze::zelda3::DungeonObjectEditor::EditorConfig::show_preview, yaze::zelda3::DungeonObjectEditor::EditorConfig::snap_to_grid, and yaze::zelda3::DungeonObjectEditor::EditorConfig::validate_objects.
Referenced by SetROM().
CreateUndoPoint()
absl::Status yaze::zelda3::DungeonObjectEditor::CreateUndoPoint () private
Definition at line 762 of file dungeon_object_editor.cc.
References current_room_, yaze::zelda3::DungeonObjectEditor::UndoPoint::editing, editing_state_, kMaxUndoHistory, yaze::zelda3::DungeonObjectEditor::UndoPoint::objects, redo_history_, yaze::zelda3::DungeonObjectEditor::UndoPoint::selection, selection_state_, yaze::zelda3::DungeonObjectEditor::UndoPoint::timestamp, and undo_history_.
Referenced by ClearRoom(), DeleteObject(), DeleteSelectedObjects(), HandleMouseDrag(), InsertObject(), LoadRoom(), MoveObject(), and ResizeObject().
ApplyUndoPoint()
absl::Status yaze::zelda3::DungeonObjectEditor::ApplyUndoPoint (const UndoPoint & undo_point) private
Definition at line 830 of file dungeon_object_editor.cc.
References current_room_, yaze::zelda3::DungeonObjectEditor::UndoPoint::editing, editing_state_, yaze::zelda3::DungeonObjectEditor::UndoPoint::objects, room_changed_callback_, yaze::zelda3::DungeonObjectEditor::UndoPoint::selection, selection_changed_callback_, selection_state_, and UpdatePreviewObject().
Referenced by Redo(), and Undo().
ScreenToRoomCoordinates()
std::pair< int, int > yaze::zelda3::DungeonObjectEditor::ScreenToRoomCoordinates (int screen_x, int screen_y) private
Definition at line 720 of file dungeon_object_editor.cc.
Referenced by HandleMouseClick(), HandleScrollWheel(), and SelectObject().
RoomToScreenCoordinates()
std::pair< int, int > yaze::zelda3::DungeonObjectEditor::RoomToScreenCoordinates (int room_x, int room_y) private
Definition at line 731 of file dungeon_object_editor.cc.
SnapToGrid()
int yaze::zelda3::DungeonObjectEditor::SnapToGrid (int coordinate) private
Definition at line 739 of file dungeon_object_editor.cc.
References config_, yaze::zelda3::DungeonObjectEditor::EditorConfig::grid_size, and yaze::zelda3::DungeonObjectEditor::EditorConfig::snap_to_grid.
Referenced by InsertObject(), and MoveObject().
FindObjectAt()
std::optional< size_t > yaze::zelda3::DungeonObjectEditor::FindObjectAt (int room_x, int room_y) private
Definition at line 652 of file dungeon_object_editor.cc.
References current_room_, and IsObjectAtPosition().
Referenced by HandleMouseClick(), and SelectObject().
FindObjectsInArea()
std::vector< size_t > yaze::zelda3::DungeonObjectEditor::FindObjectsInArea (int start_x, int start_y, int end_x, int end_y) private
IsObjectAtPosition()
bool yaze::zelda3::DungeonObjectEditor::IsObjectAtPosition (const RoomObject & object, int x, int y) private
Definition at line 667 of file dungeon_object_editor.cc.
Referenced by FindObjectAt().
ObjectsCollide()
bool yaze::zelda3::DungeonObjectEditor::ObjectsCollide (const RoomObject & obj1, const RoomObject & obj2) private
Definition at line 689 of file dungeon_object_editor.cc.
References yaze::zelda3::RoomObject::size_, yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InsertObject(), MoveObject(), and ValidateRoom().
RenderObjectPreview()
absl::StatusOr< gfx::Bitmap > yaze::zelda3::DungeonObjectEditor::RenderObjectPreview (int object_type, int x, int y, int size) private
UpdatePreviewObject()
void yaze::zelda3::DungeonObjectEditor::UpdatePreviewObject () private
Definition at line 747 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_layer, yaze::zelda3::DungeonObjectEditor::EditingState::current_mode, yaze::zelda3::DungeonObjectEditor::EditingState::current_object_type, editing_state_, kInsert, preview_object_, yaze::zelda3::DungeonObjectEditor::EditingState::preview_size, preview_visible_, yaze::zelda3::DungeonObjectEditor::EditingState::preview_x, yaze::zelda3::DungeonObjectEditor::EditingState::preview_y, and rom_.
Referenced by ApplyUndoPoint(), HandleSizeEdit(), SetCurrentLayer(), SetCurrentObjectType(), and SetMode().
ValidatePreviewPosition()
absl::Status yaze::zelda3::DungeonObjectEditor::ValidatePreviewPosition (int x, int y) private
HandleSizeEdit()
absl::Status yaze::zelda3::DungeonObjectEditor::HandleSizeEdit (int delta, int x, int y) private
Definition at line 395 of file dungeon_object_editor.cc.
References yaze::zelda3::DungeonObjectEditor::EditingState::current_mode, current_room_, editing_state_, GetNextSize(), IsValidSize(), kEdit, kInsert, yaze::zelda3::DungeonObjectEditor::EditingState::preview_size, ResizeObject(), yaze::zelda3::DungeonObjectEditor::SelectionState::selected_objects, selection_state_, and UpdatePreviewObject().
Referenced by HandleScrollWheel().
GetNextSize()
int yaze::zelda3::DungeonObjectEditor::GetNextSize (int current_size, int delta) private
Definition at line 426 of file dungeon_object_editor.cc.
Referenced by HandleSizeEdit().
GetPreviousSize()
int yaze::zelda3::DungeonObjectEditor::GetPreviousSize (int current_size, int delta) private
IsValidSize()
bool yaze::zelda3::DungeonObjectEditor::IsValidSize (int size) private
Definition at line 452 of file dungeon_object_editor.cc.
References kMaxObjectSize, and kMinObjectSize.
Referenced by HandleSizeEdit().
Member Data Documentation
rom_
Rom* yaze::zelda3::DungeonObjectEditor::rom_ private
Definition at line 238 of file dungeon_object_editor.h.
Referenced by InitializeEditor(), InsertObject(), LoadRoom(), SetROM(), and UpdatePreviewObject().
current_room_
std::unique_ptr<Room> yaze::zelda3::DungeonObjectEditor::current_room_ private
Definition at line 239 of file dungeon_object_editor.h.
Referenced by AddToSelection(), ApplyUndoPoint(), ClearRoom(), CreateUndoPoint(), DeleteObject(), DeleteSelectedObjects(), FindObjectAt(), GetMutableRoom(), GetObjectCount(), GetObjects(), GetRoom(), HandleDragOperation(), HandleMouseClick(), HandleMouseDrag(), HandleMouseRelease(), HandleScrollWheel(), HandleSizeEdit(), InitializeEditor(), InsertObject(), LoadRoom(), MoveObject(), Redo(), RenderLayerControls(), RenderLayerVisualization(), RenderObjectPropertyPanel(), RenderRoom(), RenderSelectionHighlight(), ResizeObject(), SaveRoom(), SelectObject(), Undo(), and ValidateRoom().
renderer_
std::unique_ptr<ObjectRenderer> yaze::zelda3::DungeonObjectEditor::renderer_ private
Definition at line 240 of file dungeon_object_editor.h.
Referenced by DungeonObjectEditor(), RenderRoom(), and SetROM().
selection_state_
SelectionState yaze::zelda3::DungeonObjectEditor::selection_state_ private
Definition at line 242 of file dungeon_object_editor.h.
Referenced by AddToSelection(), ApplyUndoPoint(), ClearSelection(), CreateUndoPoint(), DeleteObject(), DeleteSelectedObjects(), GetSelection(), HandleDragOperation(), HandleMouseDrag(), HandleMouseRelease(), HandleScrollWheel(), HandleSizeEdit(), InsertObject(), Redo(), RenderObjectPropertyPanel(), RenderSelectionHighlight(), SelectObject(), and Undo().
editing_state_
EditingState yaze::zelda3::DungeonObjectEditor::editing_state_ private
Definition at line 243 of file dungeon_object_editor.h.
Referenced by ApplyUndoPoint(), CreateUndoPoint(), GetCurrentLayer(), GetCurrentObjectType(), GetEditingState(), GetMode(), HandleMouseClick(), HandleScrollWheel(), HandleSizeEdit(), InitializeEditor(), LoadRoom(), Redo(), RenderLayerControls(), SetCurrentLayer(), SetCurrentObjectType(), SetMode(), Undo(), and UpdatePreviewObject().
config_
EditorConfig yaze::zelda3::DungeonObjectEditor::config_ private
Definition at line 244 of file dungeon_object_editor.h.
Referenced by GetConfig(), HandleDragOperation(), InitializeEditor(), InsertObject(), MoveObject(), RenderLayerControls(), RenderLayerVisualization(), RenderObjectPropertyPanel(), RenderSelectionHighlight(), SaveRoom(), SetConfig(), SnapToGrid(), and ValidateRoom().
undo_history_
std::vector<UndoPoint> yaze::zelda3::DungeonObjectEditor::undo_history_ private
Definition at line 246 of file dungeon_object_editor.h.
Referenced by CanUndo(), ClearHistory(), CreateUndoPoint(), Redo(), and Undo().
redo_history_
std::vector<UndoPoint> yaze::zelda3::DungeonObjectEditor::redo_history_ private
Definition at line 247 of file dungeon_object_editor.h.
Referenced by CanRedo(), ClearHistory(), CreateUndoPoint(), Redo(), and Undo().
kMaxUndoHistory
constexpr size_t yaze::zelda3::DungeonObjectEditor::kMaxUndoHistory = 50 static constexpr private
Definition at line 248 of file dungeon_object_editor.h.
Referenced by CreateUndoPoint().
preview_object_
std::optional<RoomObject> yaze::zelda3::DungeonObjectEditor::preview_object_ private
Definition at line 251 of file dungeon_object_editor.h.
Referenced by UpdatePreviewObject().
preview_visible_
bool yaze::zelda3::DungeonObjectEditor::preview_visible_ = false private
Definition at line 252 of file dungeon_object_editor.h.
Referenced by UpdatePreviewObject().
object_changed_callback_
ObjectChangedCallback yaze::zelda3::DungeonObjectEditor::object_changed_callback_ private
Definition at line 255 of file dungeon_object_editor.h.
Referenced by HandleDragOperation(), InsertObject(), MoveObject(), RenderObjectPropertyPanel(), ResizeObject(), and SetObjectChangedCallback().
room_changed_callback_
RoomChangedCallback yaze::zelda3::DungeonObjectEditor::room_changed_callback_ private
Definition at line 256 of file dungeon_object_editor.h.
Referenced by ApplyUndoPoint(), ClearRoom(), DeleteObject(), DeleteSelectedObjects(), HandleMouseRelease(), InsertObject(), LoadRoom(), MoveObject(), ResizeObject(), and SetRoomChangedCallback().
selection_changed_callback_
SelectionChangedCallback yaze::zelda3::DungeonObjectEditor::selection_changed_callback_ private
Definition at line 257 of file dungeon_object_editor.h.
Referenced by AddToSelection(), ApplyUndoPoint(), ClearSelection(), DeleteObject(), InsertObject(), SelectObject(), and SetSelectionChangedCallback().
kMinObjectSize
constexpr int yaze::zelda3::DungeonObjectEditor::kMinObjectSize = 0x00 static constexpr private
Definition at line 260 of file dungeon_object_editor.h.
Referenced by IsValidSize().
kMaxObjectSize
constexpr int yaze::zelda3::DungeonObjectEditor::kMaxObjectSize = 0xFF static constexpr private
Definition at line 261 of file dungeon_object_editor.h.
Referenced by InsertObject(), IsValidSize(), and ResizeObject().
kDefaultObjectSize
constexpr int yaze::zelda3::DungeonObjectEditor::kDefaultObjectSize = 0x12 static constexpr private
Definition at line 262 of file dungeon_object_editor.h.
Referenced by InitializeEditor().
kMinLayer
constexpr int yaze::zelda3::DungeonObjectEditor::kMinLayer = 0 static constexpr private
Definition at line 263 of file dungeon_object_editor.h.
Referenced by HandleScrollWheel(), and SetCurrentLayer().
kMaxLayer
constexpr int yaze::zelda3::DungeonObjectEditor::kMaxLayer = 2 static constexpr private
Definition at line 264 of file dungeon_object_editor.h.
Referenced by HandleScrollWheel(), InsertObject(), and SetCurrentLayer().
empty_objects_
std::vector<RoomObject> yaze::zelda3::DungeonObjectEditor::empty_objects_ private
Definition at line 267 of file dungeon_object_editor.h.
Referenced by GetObjects().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/dungeon_object_editor.h
src/app/zelda3/dungeon/dungeon_object_editor.cc