yaze: yaze::zelda3::RoomLayoutObject Class Reference
yaze::zelda3::RoomLayoutObject Class Reference
Represents a room layout object (wall, floor, etc.)
#include <room_layout.h>
Public Types
enum class Type {
kWall = 0 , kFloor = 1 , kCeiling = 2 , kPit = 3 ,
kWater = 4 , kStairs = 5 , kDoor = 6 , kUnknown = 7
}
Public Member Functions
RoomLayoutObject (int16_t id, uint8_t x, uint8_t y, Type type, uint8_t layer=0)
int16_t id () const
uint8_t x () const
uint8_t y () const
Type type () const
uint8_t layer () const
void set_id (int16_t id)
void set_x (uint8_t x)
void set_y (uint8_t y)
void set_type (Type type)
void set_layer (uint8_t layer)
absl::StatusOr< gfx::Tile16 > GetTile () const
std::string GetTypeName () const
Private Attributes
int16_t id_
uint8_t x_
uint8_t y_
Type type_
uint8_t layer_
Detailed Description
Represents a room layout object (wall, floor, etc.)
Room layout objects are the basic building blocks of dungeon rooms. They include walls, floors, ceilings, and other structural elements. Unlike regular room objects, these are loaded from the room layout data and represent the fundamental geometry of the room.
Definition at line 23 of file room_layout.h.
Member Enumeration Documentation
Type
enum class yaze::zelda3::RoomLayoutObject::Type strong
Enumerator
kWall
kFloor
kCeiling
kPit
kWater
kStairs
kDoor
kUnknown
Definition at line 25 of file room_layout.h.
Constructor & Destructor Documentation
RoomLayoutObject()
yaze::zelda3::RoomLayoutObject::RoomLayoutObject (int16_t id, uint8_t x, uint8_t y, Type type, uint8_t layer = 0) inline
Definition at line 36 of file room_layout.h.
Member Function Documentation
id()
int16_t yaze::zelda3::RoomLayoutObject::id () const inline
Definition at line 40 of file room_layout.h.
References id_.
Referenced by set_id(), and yaze::test::TEST_F().
x()
uint8_t yaze::zelda3::RoomLayoutObject::x () const inline
Definition at line 41 of file room_layout.h.
References x_.
Referenced by set_x(), and yaze::test::TEST_F().
y()
uint8_t yaze::zelda3::RoomLayoutObject::y () const inline
Definition at line 42 of file room_layout.h.
References y_.
Referenced by set_y(), and yaze::test::TEST_F().
type()
Type yaze::zelda3::RoomLayoutObject::type () const inline
Definition at line 43 of file room_layout.h.
References type_.
Referenced by set_type(), and yaze::test::TEST_F().
layer()
uint8_t yaze::zelda3::RoomLayoutObject::layer () const inline
Definition at line 44 of file room_layout.h.
References layer_.
Referenced by set_layer(), and yaze::test::TEST_F().
set_id()
void yaze::zelda3::RoomLayoutObject::set_id (int16_t id) inline
Definition at line 47 of file room_layout.h.
References id(), and id_.
set_x()
void yaze::zelda3::RoomLayoutObject::set_x (uint8_t x) inline
Definition at line 48 of file room_layout.h.
References x(), and x_.
set_y()
void yaze::zelda3::RoomLayoutObject::set_y (uint8_t y) inline
Definition at line 49 of file room_layout.h.
References y(), and y_.
set_type()
void yaze::zelda3::RoomLayoutObject::set_type (Type type) inline
Definition at line 50 of file room_layout.h.
References type(), and type_.
set_layer()
void yaze::zelda3::RoomLayoutObject::set_layer (uint8_t layer) inline
Definition at line 51 of file room_layout.h.
References layer(), and layer_.
GetTile()
absl::StatusOr< gfx::Tile16 > yaze::zelda3::RoomLayoutObject::GetTile () const
Definition at line 10 of file room_layout.cc.
References yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, id_, yaze::gfx::TileInfo::over_, yaze::gfx::TileInfo::palette_, and yaze::gfx::TileInfo::vertical_mirror_.
Referenced by yaze::test::TEST_F().
GetTypeName()
std::string yaze::zelda3::RoomLayoutObject::GetTypeName () const
Definition at line 25 of file room_layout.cc.
References kCeiling, kDoor, kFloor, kPit, kStairs, kUnknown, kWall, kWater, and type_.
Referenced by yaze::test::TEST_F().
Member Data Documentation
id_
int16_t yaze::zelda3::RoomLayoutObject::id_ private
Definition at line 60 of file room_layout.h.
Referenced by GetTile(), id(), and set_id().
x_
uint8_t yaze::zelda3::RoomLayoutObject::x_ private
Definition at line 61 of file room_layout.h.
Referenced by set_x(), and x().
y_
uint8_t yaze::zelda3::RoomLayoutObject::y_ private
Definition at line 62 of file room_layout.h.
Referenced by set_y(), and y().
type_
Type yaze::zelda3::RoomLayoutObject::type_ private
Definition at line 63 of file room_layout.h.
Referenced by GetTypeName(), set_type(), and type().
layer_
uint8_t yaze::zelda3::RoomLayoutObject::layer_ private
Definition at line 64 of file room_layout.h.
Referenced by layer(), and set_layer().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/room_layout.h
src/app/zelda3/dungeon/room_layout.cc