yaze: yaze::gui::BackgroundRenderer Class Reference
yaze::gui::BackgroundRenderer Class Reference
Renders themed background effects for docking windows.
#include <background_renderer.h>
Classes
struct GridSettings
Public Member Functions
void RenderDockingBackground (ImDrawList *draw_list, const ImVec2 &window_pos, const ImVec2 &window_size, const Color &theme_color)
void RenderGridBackground (ImDrawList *draw_list, const ImVec2 &window_pos, const ImVec2 &window_size, const Color &grid_color)
void RenderRadialGradient (ImDrawList *draw_list, const ImVec2 &center, float radius, const Color &inner_color, const Color &outer_color)
void SetGridSettings (const GridSettings &settings)
const GridSettings & GetGridSettings () const
void UpdateAnimation (float delta_time)
void SetAnimationEnabled (bool enabled)
void UpdateForTheme (const Color &primary_color, const Color &background_color)
void DrawSettingsUI ()
Static Public Member Functions
static BackgroundRenderer & Get ()
Private Member Functions
BackgroundRenderer ()=default
float CalculateRadialFade (const ImVec2 &pos, const ImVec2 &center, float max_distance) const
ImU32 BlendColorWithFade (const Color &base_color, float fade_factor) const
void DrawGridLine (ImDrawList *draw_list, const ImVec2 &start, const ImVec2 &end, ImU32 color, float thickness) const
void DrawGridDot (ImDrawList *draw_list, const ImVec2 &pos, ImU32 color, float size) const
Private Attributes
GridSettings grid_settings_
float animation_time_ = 0.0f
Color cached_grid_color_ {0.5f, 0.5f, 0.5f, 0.1f}
Detailed Description
Renders themed background effects for docking windows.
Definition at line 14 of file background_renderer.h.
Constructor & Destructor Documentation
BackgroundRenderer()
yaze::gui::BackgroundRenderer::BackgroundRenderer () private default
Member Function Documentation
Get()
BackgroundRenderer & yaze::gui::BackgroundRenderer::Get () static
Definition at line 17 of file background_renderer.cc.
Referenced by yaze::gui::DockSpaceRenderer::BeginEnhancedDockSpace(), yaze::gui::DrawDisplaySettings(), yaze::gui::DrawDisplaySettingsForPopup(), and yaze::editor::EditorManager::Update().
RenderDockingBackground()
void yaze::gui::BackgroundRenderer::RenderDockingBackground (ImDrawList * draw_list, const ImVec2 & window_pos, const ImVec2 & window_size, const Color & theme_color)
Definition at line 22 of file background_renderer.cc.
References yaze::gui::Color::alpha, animation_time_, yaze::gui::ConvertColorToImVec4(), yaze::gui::ThemeManager::Get(), grid_settings_, yaze::gui::BackgroundRenderer::GridSettings::grid_size, yaze::gui::Color::red, RenderGridBackground(), and UpdateAnimation().
RenderGridBackground()
void yaze::gui::BackgroundRenderer::RenderGridBackground (ImDrawList * draw_list, const ImVec2 & window_pos, const ImVec2 & window_size, const Color & grid_color)
Definition at line 72 of file background_renderer.cc.
References yaze::gui::Color::alpha, yaze::gui::BackgroundRenderer::GridSettings::animation_speed, animation_time_, BlendColorWithFade(), yaze::gui::Color::blue, yaze::gui::BackgroundRenderer::GridSettings::breathing_intensity, yaze::gui::BackgroundRenderer::GridSettings::breathing_speed, yaze::gui::BackgroundRenderer::GridSettings::dot_size, DrawGridDot(), DrawGridLine(), yaze::gui::BackgroundRenderer::GridSettings::enable_animation, yaze::gui::BackgroundRenderer::GridSettings::enable_breathing, yaze::gui::BackgroundRenderer::GridSettings::enable_dots, yaze::gui::BackgroundRenderer::GridSettings::fade_distance, yaze::gui::Color::green, grid_settings_, yaze::gui::BackgroundRenderer::GridSettings::grid_size, yaze::gui::BackgroundRenderer::GridSettings::line_thickness, yaze::gui::BackgroundRenderer::GridSettings::opacity, yaze::gui::BackgroundRenderer::GridSettings::radial_fade, and yaze::gui::Color::red.
Referenced by DrawSettingsUI(), and RenderDockingBackground().
RenderRadialGradient()
void yaze::gui::BackgroundRenderer::RenderRadialGradient (ImDrawList * draw_list, const ImVec2 & center, float radius, const Color & inner_color, const Color & outer_color)
Definition at line 178 of file background_renderer.cc.
References yaze::gui::Color::alpha, yaze::gui::Color::blue, yaze::gui::ConvertColorToImVec4(), yaze::gui::Color::green, M_PI, and yaze::gui::Color::red.
SetGridSettings()
void yaze::gui::BackgroundRenderer::SetGridSettings (const GridSettings & settings) inline
Definition at line 42 of file background_renderer.h.
References grid_settings_.
GetGridSettings()
const GridSettings & yaze::gui::BackgroundRenderer::GetGridSettings () const inline
Definition at line 43 of file background_renderer.h.
References grid_settings_.
UpdateAnimation()
void yaze::gui::BackgroundRenderer::UpdateAnimation (float delta_time)
Definition at line 224 of file background_renderer.cc.
References animation_time_, yaze::gui::BackgroundRenderer::GridSettings::enable_animation, and grid_settings_.
Referenced by RenderDockingBackground().
SetAnimationEnabled()
void yaze::gui::BackgroundRenderer::SetAnimationEnabled (bool enabled) inline
Definition at line 47 of file background_renderer.h.
References yaze::gui::BackgroundRenderer::GridSettings::enable_animation, and grid_settings_.
UpdateForTheme()
void yaze::gui::BackgroundRenderer::UpdateForTheme (const Color & primary_color, const Color & background_color)
Definition at line 230 of file background_renderer.cc.
References yaze::gui::Color::blue, cached_grid_color_, yaze::gui::Color::green, grid_settings_, yaze::gui::BackgroundRenderer::GridSettings::opacity, and yaze::gui::Color::red.
DrawSettingsUI()
void yaze::gui::BackgroundRenderer::DrawSettingsUI ()
Definition at line 240 of file background_renderer.cc.
References yaze::gui::BackgroundRenderer::GridSettings::animation_speed, yaze::gui::BackgroundRenderer::GridSettings::breathing_intensity, yaze::gui::BackgroundRenderer::GridSettings::breathing_speed, yaze::gui::BackgroundRenderer::GridSettings::dot_size, yaze::gui::BackgroundRenderer::GridSettings::enable_animation, yaze::gui::BackgroundRenderer::GridSettings::enable_breathing, yaze::gui::BackgroundRenderer::GridSettings::enable_dots, yaze::gui::BackgroundRenderer::GridSettings::fade_distance, yaze::gui::ThemeManager::Get(), grid_settings_, yaze::gui::BackgroundRenderer::GridSettings::grid_size, yaze::gui::BackgroundRenderer::GridSettings::line_thickness, yaze::gui::BackgroundRenderer::GridSettings::opacity, yaze::gui::BackgroundRenderer::GridSettings::radial_fade, and RenderGridBackground().
CalculateRadialFade()
float yaze::gui::BackgroundRenderer::CalculateRadialFade (const ImVec2 & pos, const ImVec2 & center, float max_distance) const private
Definition at line 309 of file background_renderer.cc.
BlendColorWithFade()
ImU32 yaze::gui::BackgroundRenderer::BlendColorWithFade (const Color & base_color, float fade_factor) const private
Definition at line 316 of file background_renderer.cc.
References yaze::gui::Color::alpha, yaze::gui::Color::blue, yaze::gui::ConvertColorToImVec4(), yaze::gui::Color::green, and yaze::gui::Color::red.
Referenced by RenderGridBackground().
DrawGridLine()
void yaze::gui::BackgroundRenderer::DrawGridLine (ImDrawList * draw_list, const ImVec2 & start, const ImVec2 & end, ImU32 color, float thickness) const private
Definition at line 326 of file background_renderer.cc.
Referenced by RenderGridBackground().
DrawGridDot()
void yaze::gui::BackgroundRenderer::DrawGridDot (ImDrawList * draw_list, const ImVec2 & pos, ImU32 color, float size) const private
Definition at line 331 of file background_renderer.cc.
Referenced by RenderGridBackground().
Member Data Documentation
grid_settings_
GridSettings yaze::gui::BackgroundRenderer::grid_settings_ private
Definition at line 58 of file background_renderer.h.
Referenced by DrawSettingsUI(), GetGridSettings(), RenderDockingBackground(), RenderGridBackground(), SetAnimationEnabled(), SetGridSettings(), UpdateAnimation(), and UpdateForTheme().
animation_time_
float yaze::gui::BackgroundRenderer::animation_time_ = 0.0f private
Definition at line 59 of file background_renderer.h.
Referenced by RenderDockingBackground(), RenderGridBackground(), and UpdateAnimation().
cached_grid_color_
Color yaze::gui::BackgroundRenderer::cached_grid_color_ {0.5f, 0.5f, 0.5f, 0.1f} private
Definition at line 60 of file background_renderer.h.
Referenced by UpdateForTheme().
The documentation for this class was generated from the following files:
src/app/gui/background_renderer.h
src/app/gui/background_renderer.cc