yaze: yaze::cli::agent::anonymous_namespace{learned_knowledge_service.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{learned_knowledge_service.cc} Namespace Reference
Functions
int64_t CurrentTimestamp ()
std::string GenerateRandomID ()
bool FileExists (const std::filesystem::path &path)
Function Documentation
CurrentTimestamp()
int64_t yaze::cli::agent::anonymous_namespace{learned_knowledge_service.cc}::CurrentTimestamp ()
Definition at line 21 of file learned_knowledge_service.cc.
References CurrentTimestamp().
Referenced by CurrentTimestamp().
GenerateRandomID()
std::string yaze::cli::agent::anonymous_namespace{learned_knowledge_service.cc}::GenerateRandomID ()
Definition at line 25 of file learned_knowledge_service.cc.
References GenerateRandomID().
Referenced by GenerateRandomID().
FileExists()
bool yaze::cli::agent::anonymous_namespace{learned_knowledge_service.cc}::FileExists (const std::filesystem::path & path)
Definition at line 31 of file learned_knowledge_service.cc.
References yaze::util::PlatformPaths::Exists(), and FileExists().
Referenced by FileExists().