yaze: yaze::gfx::BackgroundBuffer Class Reference
yaze::gfx::BackgroundBuffer Class Reference
#include <background_buffer.h>
Public Member Functions
BackgroundBuffer (int width=512, int height=512)
void SetTileAt (int x, int y, uint16_t value)
uint16_t GetTileAt (int x, int y) const
void ClearBuffer ()
void DrawTile (const TileInfo &tile_info, uint8_t *canvas, const uint8_t *tiledata, int indexoffset)
void DrawBackground (std::span< uint8_t > gfx16_data)
void DrawFloor (const std::vector< uint8_t > &rom_data, int tile_address, int tile_address_floor, uint8_t floor_graphics)
auto buffer ()
auto & bitmap ()
Private Attributes
std::vector< uint16_t > buffer_
gfx::Bitmap bitmap_
int width_
int height_
Detailed Description
Definition at line 13 of file background_buffer.h.
Constructor & Destructor Documentation
BackgroundBuffer()
yaze::gfx::BackgroundBuffer::BackgroundBuffer (int width = 512, int height = 512)
Definition at line 12 of file background_buffer.cc.
References buffer_.
Member Function Documentation
SetTileAt()
void yaze::gfx::BackgroundBuffer::SetTileAt (int x, int y, uint16_t value)
Definition at line 19 of file background_buffer.cc.
References buffer_, height_, and width_.
Referenced by DrawFloor().
GetTileAt()
uint16_t yaze::gfx::BackgroundBuffer::GetTileAt (int x, int y) const
Definition at line 27 of file background_buffer.cc.
References buffer_, height_, and width_.
ClearBuffer()
void yaze::gfx::BackgroundBuffer::ClearBuffer ()
Definition at line 34 of file background_buffer.cc.
References buffer_.
DrawTile()
void yaze::gfx::BackgroundBuffer::DrawTile (const TileInfo & tile_info, uint8_t * canvas, const uint8_t * tiledata, int indexoffset)
Definition at line 36 of file background_buffer.cc.
References yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::gfx::TileInfo::palette_, and yaze::gfx::TileInfo::vertical_mirror_.
Referenced by DrawBackground().
DrawBackground()
void yaze::gfx::BackgroundBuffer::DrawBackground (std::span< uint8_t > gfx16_data)
Definition at line 57 of file background_buffer.cc.
References bitmap_, buffer_, yaze::gfx::Bitmap::Create(), DrawTile(), height_, yaze::gfx::Bitmap::mutable_data(), width_, and yaze::gfx::WordToTileInfo().
DrawFloor()
void yaze::gfx::BackgroundBuffer::DrawFloor (const std::vector< uint8_t > & rom_data, int tile_address, int tile_address_floor, uint8_t floor_graphics)
Definition at line 79 of file background_buffer.cc.
References yaze::gfx::TileInfo::id_, and SetTileAt().
buffer()
auto yaze::gfx::BackgroundBuffer::buffer () inline
Definition at line 32 of file background_buffer.h.
References buffer_.
bitmap()
auto & yaze::gfx::BackgroundBuffer::bitmap () inline
Definition at line 33 of file background_buffer.h.
References bitmap_.
Member Data Documentation
buffer_
std::vector<uint16_t> yaze::gfx::BackgroundBuffer::buffer_ private
Definition at line 36 of file background_buffer.h.
Referenced by BackgroundBuffer(), buffer(), ClearBuffer(), DrawBackground(), GetTileAt(), and SetTileAt().
bitmap_
gfx::Bitmap yaze::gfx::BackgroundBuffer::bitmap_ private
Definition at line 37 of file background_buffer.h.
Referenced by bitmap(), and DrawBackground().
width_
int yaze::gfx::BackgroundBuffer::width_ private
Definition at line 38 of file background_buffer.h.
Referenced by DrawBackground(), GetTileAt(), and SetTileAt().
height_
int yaze::gfx::BackgroundBuffer::height_ private
Definition at line 39 of file background_buffer.h.
Referenced by DrawBackground(), GetTileAt(), and SetTileAt().
The documentation for this class was generated from the following files:
src/app/gfx/background_buffer.h
src/app/gfx/background_buffer.cc