var searchData=
[
  ['palette_5feditor_2ecc_0',['palette_editor.cc',['../palette__editor_8cc.html',1,'']]],
  ['palette_5feditor_2eh_1',['palette_editor.h',['../palette__editor_8h.html',1,'']]],
  ['patch_2ecc_2',['patch.cc',['../patch_8cc.html',1,'']]],
  ['performance_5fdashboard_2ecc_3',['performance_dashboard.cc',['../performance__dashboard_8cc.html',1,'']]],
  ['performance_5fdashboard_2eh_4',['performance_dashboard.h',['../performance__dashboard_8h.html',1,'']]],
  ['performance_5fmonitor_2ecc_5',['performance_monitor.cc',['../performance__monitor_8cc.html',1,'']]],
  ['performance_5fmonitor_2eh_6',['performance_monitor.h',['../performance__monitor_8h.html',1,'']]],
  ['performance_5foptimization_5fsummary_2emd_7',['performance_optimization_summary.md',['../performance__optimization__summary_8md.html',1,'']]],
  ['performance_5fprofiler_2ecc_8',['performance_profiler.cc',['../performance__profiler_8cc.html',1,'']]],
  ['performance_5fprofiler_2eh_9',['performance_profiler.h',['../performance__profiler_8h.html',1,'']]],
  ['popup_5fmanager_2ecc_10',['popup_manager.cc',['../popup__manager_8cc.html',1,'']]],
  ['popup_5fmanager_2eh_11',['popup_manager.h',['../popup__manager_8h.html',1,'']]],
  ['ppu_2ecc_12',['ppu.cc',['../ppu_8cc.html',1,'']]],
  ['ppu_2eh_13',['ppu.h',['../ppu_8h.html',1,'']]],
  ['ppu_5fregisters_2eh_14',['ppu_registers.h',['../ppu__registers_8h.html',1,'']]],
  ['project_2ecc_15',['project.cc',['../project_8cc.html',1,'']]],
  ['project_2eh_16',['project.h',['../project_8h.html',1,'']]]
];
