var searchData=
[
  ['imguitestengine_20integration_20complete_20✅_0',['IT-01 Phase 3: ImGuiTestEngine Integration - COMPLETE ✅',['../d7/dc6/md_docs_2z3ed_2archive_2IT-01-PHASE3-COMPLETE.html',1,'']]],
  ['imguitestengine_20integration_20guide_1',['IT-01 Phase 2: ImGuiTestEngine Integration Guide',['../df/d63/md_docs_2z3ed_2archive_2IT-01-PHASE2-IMPLEMENTATION-GUIDE.html',1,'']]],
  ['imguitestharness_20grpc_20evaluation_2',['IT-01: ImGuiTestHarness - gRPC Evaluation',['../dd/d93/md_docs_2z3ed_2archive_2IT-01-grpc-evaluation.html',1,'']]],
  ['imguitestharness_20quick_20start_20guide_3',['ImGuiTestHarness Quick Start Guide',['../d3/dd9/md_docs_2z3ed_2IT-01-QUICKSTART.html',1,'']]],
  ['implementation_4',['implementation',['../d7/d30/md_docs_2analysis_2dungeon__parallel__optimization__summary.html',1,'DungeonEditor Parallel Optimization Implementation'],['../db/d37/md_docs_2z3ed_2archive_2IT-01-getting-started-grpc.html',1,'IT-01 Getting Started: gRPC Implementation'],['../d6/df4/md_docs_2gfx__optimizations__complete.html',1,'YAZE Graphics System Optimizations - Complete Implementation']]],
  ['implementation_20analysis_5',['ZScream C# vs YAZE C++ Overworld Implementation Analysis',['../d8/d17/md_docs_2analysis_2zscream__yaze__overworld__comparison.html',1,'']]],
  ['implementation_20complete_20✅_6',['gRPC Test Harness - Implementation Complete ✅',['../d8/d6e/md_docs_2z3ed_2archive_2GRPC__TEST__SUCCESS.html',1,'']]],
  ['implementation_20plan_7',['z3ed Agentic Workflow Implementation Plan',['../df/da9/md_docs_2z3ed_2E6-z3ed-implementation-plan.html',1,'']]],
  ['implementation_20progress_20october_202_202025_8',['z3ed Implementation Progress - October 2, 2025',['../de/dd1/md_docs_2z3ed_2IMPLEMENTATION__PROGRESS__OCT2.html',1,'']]],
  ['implementation_20session_20summary_9',['z3ed Agent Implementation - Session Summary',['../d9/d74/md_docs_2z3ed_2SESSION__SUMMARY__OCT2.html',1,'']]],
  ['implementation_20summary_10',['yaze Graphics System Optimizations - Implementation Summary',['../d3/d7b/md_docs_2gfx__optimizations__implemented.html',1,'']]],
  ['implementation_20yaze_20graphics_20optimizations_11',['Atlas Rendering Implementation - YAZE Graphics Optimizations',['../db/d26/md_docs_2atlas__rendering__implementation.html',1,'']]],
  ['improvements_12',['improvements',['../d1/d30/md_docs_2B2-platform-compatibility.html',1,'Platform Compatibility Improvements'],['../d9/d6b/md_docs_2B5-stability-improvements.html',1,'Stability, Testability &amp; Release Workflow Improvements']]],
  ['improvements_20summary_13',['YAZE Graphics System Improvements Summary',['../d9/df4/md_docs_2gfx__improvements__summary.html',1,'']]],
  ['instructions_14',['Build Instructions',['../d9/d41/md_docs_202-build-instructions.html',1,'']]],
  ['integration_15',['Asar 65816 Assembler Integration',['../d2/dd3/md_docs_203-asar-integration.html',1,'']]],
  ['integration_20complete_20✅_16',['IT-01 Phase 3: ImGuiTestEngine Integration - COMPLETE ✅',['../d7/dc6/md_docs_2z3ed_2archive_2IT-01-PHASE3-COMPLETE.html',1,'']]],
  ['integration_20guide_17',['IT-01 Phase 2: ImGuiTestEngine Integration Guide',['../df/d63/md_docs_2z3ed_2archive_2IT-01-PHASE2-IMPLEMENTATION-GUIDE.html',1,'']]],
  ['it_2001_20getting_20started_3a_20grpc_20implementation_18',['IT-01 Getting Started: gRPC Implementation',['../db/d37/md_docs_2z3ed_2archive_2IT-01-getting-started-grpc.html',1,'']]],
  ['it_2001_20phase_202_3a_20file_20modification_20checklist_19',['IT-01 Phase 2: File Modification Checklist',['../d8/d87/md_docs_2z3ed_2archive_2FILE__MODIFICATION__CHECKLIST.html',1,'']]],
  ['it_2001_20phase_202_3a_20imguitestengine_20integration_20guide_20',['IT-01 Phase 2: ImGuiTestEngine Integration Guide',['../df/d63/md_docs_2z3ed_2archive_2IT-01-PHASE2-IMPLEMENTATION-GUIDE.html',1,'']]],
  ['it_2001_20phase_203_3a_20imguitestengine_20integration_20complete_20✅_21',['IT-01 Phase 3: ImGuiTestEngine Integration - COMPLETE ✅',['../d7/dc6/md_docs_2z3ed_2archive_2IT-01-PHASE3-COMPLETE.html',1,'']]],
  ['it_2001_3a_20imguitestharness_20grpc_20evaluation_22',['IT-01: ImGuiTestHarness - gRPC Evaluation',['../dd/d93/md_docs_2z3ed_2archive_2IT-01-grpc-evaluation.html',1,'']]]
];
