yaze: yaze::zelda3::ObjectCategories Namespace Reference
yaze::zelda3::ObjectCategories Namespace Reference
Object type categories for easier selection.
Classes
struct ObjectCategory
struct ObjectInfo
Get object information.
Functions
std::vector< ObjectCategory > GetObjectCategories ()
Get all available object categories.
absl::StatusOr< std::vector< int > > GetObjectsInCategory (const std::string &category_name)
Get objects in a specific category.
absl::StatusOr< std::string > GetObjectCategory (int object_id)
Get category for a specific object.
absl::StatusOr< ObjectInfo > GetObjectInfo (int object_id)
Detailed Description
Object type categories for easier selection.
Function Documentation
GetObjectCategories()
std::vector< ObjectCategory > yaze::zelda3::ObjectCategories::GetObjectCategories ()
Get all available object categories.
Definition at line 1241 of file dungeon_object_editor.cc.
Referenced by GetObjectCategory(), and GetObjectsInCategory().
GetObjectsInCategory()
absl::StatusOr< std::vector< int > > yaze::zelda3::ObjectCategories::GetObjectsInCategory (const std::string & category_name)
Get objects in a specific category.
Definition at line 1253 of file dungeon_object_editor.cc.
References GetObjectCategories().
GetObjectCategory()
absl::StatusOr< std::string > yaze::zelda3::ObjectCategories::GetObjectCategory (int object_id)
Get category for a specific object.
Definition at line 1265 of file dungeon_object_editor.cc.
References GetObjectCategories().
GetObjectInfo()
absl::StatusOr< ObjectInfo > yaze::zelda3::ObjectCategories::GetObjectInfo (int object_id)
Definition at line 1279 of file dungeon_object_editor.cc.
References yaze::zelda3::ObjectCategories::ObjectInfo::description, yaze::zelda3::ObjectCategories::ObjectInfo::id, yaze::zelda3::ObjectCategories::ObjectInfo::is_collidable, yaze::zelda3::ObjectCategories::ObjectInfo::is_interactive, yaze::zelda3::ObjectCategories::ObjectInfo::name, yaze::zelda3::ObjectCategories::ObjectInfo::valid_layers, and yaze::zelda3::ObjectCategories::ObjectInfo::valid_sizes.