yaze: yaze::gui::CanvasSelection Struct Reference
yaze::gui::CanvasSelection Struct Reference
Selection state for canvas interactions.
#include <canvas_utils.h>
Public Member Functions
void Clear ()
Public Attributes
std::vector< ImVec2 > selected_tiles
std::vector< ImVec2 > selected_points
ImVec2 selected_tile_pos = ImVec2(-1, -1)
bool select_rect_active = false
Detailed Description
Selection state for canvas interactions.
Definition at line 34 of file canvas_utils.h.
Member Function Documentation
Clear()
void yaze::gui::CanvasSelection::Clear () inline
Definition at line 40 of file canvas_utils.h.
References select_rect_active, selected_points, selected_tile_pos, and selected_tiles.
Referenced by yaze::gui::Canvas::Cleanup(), and yaze::gui::Canvas::InitializeDefaults().
Member Data Documentation
selected_tiles
std::vector<ImVec2> yaze::gui::CanvasSelection::selected_tiles
Definition at line 35 of file canvas_utils.h.
Referenced by Clear().
selected_points
std::vector<ImVec2> yaze::gui::CanvasSelection::selected_points
Definition at line 36 of file canvas_utils.h.
Referenced by Clear().
selected_tile_pos
ImVec2 yaze::gui::CanvasSelection::selected_tile_pos = ImVec2(-1, -1)
Definition at line 37 of file canvas_utils.h.
Referenced by Clear(), and yaze::gui::Canvas::InitializeDefaults().
select_rect_active
bool yaze::gui::CanvasSelection::select_rect_active = false
Definition at line 38 of file canvas_utils.h.
Referenced by Clear(), and yaze::gui::Canvas::InitializeDefaults().
The documentation for this struct was generated from the following file:
src/app/gui/canvas/canvas_utils.h