yaze: yaze::emu::test::HeadlessEmulator Class Reference
yaze::emu::test::HeadlessEmulator Class Reference
Public Member Functions
HeadlessEmulator ()=default
~HeadlessEmulator ()
absl::Status Init (const std::string &rom_path)
absl::Status RunFrames (int max_frames, int log_interval)
Private Member Functions
void LogApuState (int frame)
void Cleanup ()
Private Attributes
std::unique_ptr< Snes > snes_
std::vector< uint8_t > rom_data_
bool sdl_initialized_ = false
uint16_t last_pc_ = 0
int stuck_counter_ = 0
Detailed Description
Definition at line 32 of file emu_test.cc.
Constructor & Destructor Documentation
HeadlessEmulator()
yaze::emu::test::HeadlessEmulator::HeadlessEmulator () default
~HeadlessEmulator()
yaze::emu::test::HeadlessEmulator::~HeadlessEmulator () inline
Definition at line 35 of file emu_test.cc.
References Cleanup().
Member Function Documentation
Init()
absl::Status yaze::emu::test::HeadlessEmulator::Init (const std::string & rom_path) inline
Definition at line 37 of file emu_test.cc.
References rom_data_, sdl_initialized_, and snes_.
Referenced by main().
RunFrames()
absl::Status yaze::emu::test::HeadlessEmulator::RunFrames (int max_frames, int log_interval) inline
Definition at line 77 of file emu_test.cc.
References last_pc_, LogApuState(), snes_, and stuck_counter_.
Referenced by main().
LogApuState()
void yaze::emu::test::HeadlessEmulator::LogApuState (int frame) inline private
Definition at line 126 of file emu_test.cc.
References yaze::emu::debug::ApuHandshakeTracker::HANDSHAKE_CC, yaze::emu::debug::ApuHandshakeTracker::IPL_BOOT, yaze::emu::debug::ApuHandshakeTracker::RESET, yaze::emu::debug::ApuHandshakeTracker::RUNNING, snes_, yaze::emu::debug::ApuHandshakeTracker::TRANSFER_ACTIVE, yaze::emu::debug::ApuHandshakeTracker::TRANSFER_DONE, and yaze::emu::debug::ApuHandshakeTracker::WAITING_BBAA.
Referenced by RunFrames().
Cleanup()
void yaze::emu::test::HeadlessEmulator::Cleanup () inline private
Definition at line 188 of file emu_test.cc.
References sdl_initialized_.
Referenced by ~HeadlessEmulator().
Member Data Documentation
snes_
std::unique_ptr<Snes> yaze::emu::test::HeadlessEmulator::snes_ private
Definition at line 195 of file emu_test.cc.
Referenced by Init(), LogApuState(), and RunFrames().
rom_data_
std::vector<uint8_t> yaze::emu::test::HeadlessEmulator::rom_data_ private
Definition at line 196 of file emu_test.cc.
Referenced by Init().
sdl_initialized_
bool yaze::emu::test::HeadlessEmulator::sdl_initialized_ = false private
Definition at line 197 of file emu_test.cc.
Referenced by Cleanup(), and Init().
last_pc_
uint16_t yaze::emu::test::HeadlessEmulator::last_pc_ = 0 private
Definition at line 198 of file emu_test.cc.
Referenced by RunFrames().
stuck_counter_
int yaze::emu::test::HeadlessEmulator::stuck_counter_ = 0 private
Definition at line 199 of file emu_test.cc.
Referenced by RunFrames().
The documentation for this class was generated from the following file:
src/emu_test.cc