yaze: yaze::cli::anonymous_namespace{proposal_registry.cc} Namespace Reference
yaze::cli::anonymous_namespace{proposal_registry.cc} Namespace Reference
Functions
std::filesystem::path DetermineDefaultRoot ()
std::string StatusToString (ProposalRegistry::ProposalStatus status)
ProposalRegistry::ProposalStatus ParseStatus (absl::string_view value)
int64_t TimeToMillis (absl::Time time)
std::optional< absl::Time > OptionalTimeFromMillis (int64_t millis)
Function Documentation
DetermineDefaultRoot()
std::filesystem::path yaze::cli::anonymous_namespace{proposal_registry.cc}::DetermineDefaultRoot ()
Definition at line 25 of file proposal_registry.cc.
References DetermineDefaultRoot().
Referenced by DetermineDefaultRoot().
StatusToString()
std::string yaze::cli::anonymous_namespace{proposal_registry.cc}::StatusToString (ProposalRegistry::ProposalStatus status)
Definition at line 37 of file proposal_registry.cc.
References yaze::cli::ProposalRegistry::kAccepted, yaze::cli::ProposalRegistry::kPending, yaze::cli::ProposalRegistry::kRejected, and StatusToString().
Referenced by StatusToString().
ParseStatus()
ProposalRegistry::ProposalStatus yaze::cli::anonymous_namespace{proposal_registry.cc}::ParseStatus (absl::string_view value)
Definition at line 49 of file proposal_registry.cc.
References yaze::cli::ProposalRegistry::kAccepted, yaze::cli::ProposalRegistry::kPending, yaze::cli::ProposalRegistry::kRejected, and ParseStatus().
Referenced by ParseStatus().
TimeToMillis()
int64_t yaze::cli::anonymous_namespace{proposal_registry.cc}::TimeToMillis (absl::Time time)
Definition at line 60 of file proposal_registry.cc.
References TimeToMillis().
Referenced by TimeToMillis().
OptionalTimeFromMillis()
std::optional< absl::Time > yaze::cli::anonymous_namespace{proposal_registry.cc}::OptionalTimeFromMillis (int64_t millis)
Definition at line 64 of file proposal_registry.cc.
References OptionalTimeFromMillis().
Referenced by OptionalTimeFromMillis().