yaze: yaze::emu::Apu Class Reference
yaze::emu::Apu Class Reference
The Apu class represents the Audio Processing Unit (APU) of a system.
#include <apu.h>
Public Member Functions
Apu (MemoryImpl &memory)
void Init ()
void Reset ()
void RunCycles (uint64_t cycles)
uint8_t SpcRead (uint16_t address)
void SpcWrite (uint16_t address, uint8_t data)
void SpcIdle (bool waiting)
void Cycle ()
uint8_t Read (uint16_t address)
void Write (uint16_t address, uint8_t data)
auto dsp () -> Dsp &
auto spc700 () -> Spc700 &
uint64_t GetCycles () const
uint8_t GetStatus () const
uint8_t GetControl () const
void GetSamples (int16_t *buffer, int count, bool loop=false)
void WriteDma (uint16_t address, const uint8_t *data, int count)
Public Attributes
std::array< uint8_t, 6 > in_ports_
std::array< uint8_t, 4 > out_ports_
std::vector< uint8_t > ram = std::vector<uint8_t>(0x10000, 0)
Private Attributes
bool rom_readable_ = false
uint8_t dsp_adr_ = 0
uint32_t cycles_ = 0
uint8_t transfer_size_ = 0
bool in_transfer_ = false
MemoryImpl & memory_
std::array< Timer, 3 > timer_
ApuCallbacks callbacks_
Dsp dsp_ {ram}
Spc700 spc700_ {callbacks_}
Detailed Description
The Apu class represents the Audio Processing Unit (APU) of a system.
The Apu class is responsible for generating audio samples and managing the APU state. It interacts with the Memory, AudioRam, and Clock classes to read/write data and update the clock. The class also implements the Observer interface to receive notifications from the system.
IPL ROM Info
64 kilobytes of RAM are mapped across the 16-bit memory space of the SPC-700. Some regions of this space are overlaid with special hardware functions.
Range Note
$0000-00EF Zero Page RAM $00F0-00FF Sound CPU Registers $0100-01FF Stack Page RAM $0200-FFBF RAM $FFC0-FFFF IPL ROM or RAM
The region at $FFC0-FFFF will normally read from the 64-byte IPL ROM, but the underlying RAM can always be written to, and the high bit of the Control register $F1 can be cleared to unmap the IPL ROM and allow read access to this RAM.
Definition at line 48 of file apu.h.
Constructor & Destructor Documentation
Apu()
yaze::emu::Apu::Apu (MemoryImpl & memory) inline
Definition at line 50 of file apu.h.
Member Function Documentation
Init()
void yaze::emu::Apu::Init ()
Definition at line 33 of file apu.cc.
References ram.
Referenced by yaze::emu::Snes::Init(), yaze::emu::ApuDspTest::SetUp(), yaze::emu::ApuIplHandshakeTest::SetUp(), and yaze::emu::TEST().
Reset()
void yaze::emu::Apu::Reset ()
Definition at line 40 of file apu.cc.
References cycles_, dsp_, dsp_adr_, in_ports_, in_transfer_, LOG_INFO, out_ports_, ram, yaze::emu::Spc700::read_word(), yaze::emu::Dsp::Reset(), yaze::emu::Spc700::Reset(), rom_readable_, spc700_, timer_, and transfer_size_.
Referenced by yaze::emu::Snes::Reset(), yaze::emu::ApuDspTest::SetUp(), yaze::emu::ApuIplHandshakeTest::SetUp(), and yaze::emu::TEST().
RunCycles()
void yaze::emu::Apu::RunCycles (uint64_t cycles)
Definition at line 66 of file apu.cc.
References Cycle(), cycles_, yaze::emu::Spc700::GetLastOpcodeCycles(), in_ports_, LOG_INFO, LOG_WARN, memory_, out_ports_, yaze::emu::MemoryImpl::pal_timing(), yaze::emu::Spc700::PC, ram, rom_readable_, yaze::emu::Spc700::RunOpcode(), spc700_, and yaze::emu::Spc700::Y.
Referenced by yaze::emu::Snes::CatchUpApu().
SpcRead()
uint8_t yaze::emu::Apu::SpcRead (uint16_t address)
Definition at line 298 of file apu.cc.
References Cycle(), and Read().
SpcWrite()
void yaze::emu::Apu::SpcWrite (uint16_t address, uint8_t data)
Definition at line 303 of file apu.cc.
References Cycle(), and Write().
SpcIdle()
void yaze::emu::Apu::SpcIdle (bool waiting)
Definition at line 308 of file apu.cc.
References Cycle().
Cycle()
void yaze::emu::Apu::Cycle ()
Definition at line 138 of file apu.cc.
References yaze::emu::Dsp::Cycle(), cycles_, dsp_, and timer_.
Referenced by RunCycles(), SpcIdle(), SpcRead(), SpcWrite(), and yaze::emu::TEST().
Read()
uint8_t yaze::emu::Apu::Read (uint16_t address)
Definition at line 163 of file apu.cc.
References dsp_, dsp_adr_, in_ports_, LOG_INFO, yaze::emu::Spc700::PC, ram, yaze::emu::Dsp::Read(), rom_readable_, spc700_, and timer_.
Referenced by SpcRead().
Write()
void yaze::emu::Apu::Write (uint16_t address, uint8_t data)
Definition at line 210 of file apu.cc.
References cycles_, dsp_, dsp_adr_, in_ports_, in_transfer_, LOG_INFO, out_ports_, yaze::emu::Spc700::PC, ram, rom_readable_, spc700_, timer_, transfer_size_, and yaze::emu::Dsp::Write().
Referenced by SpcWrite(), and yaze::emu::TEST_F().
dsp()
auto yaze::emu::Apu::dsp () -> Dsp & inline
Definition at line 65 of file apu.h.
References dsp_.
Referenced by yaze::emu::Snes::RunCycle(), and yaze::emu::Snes::SetSamples().
spc700()
auto yaze::emu::Apu::spc700 () -> Spc700 & inline
Definition at line 66 of file apu.h.
References spc700_.
Referenced by yaze::emu::TEST(), and yaze::emu::TEST_F().
GetCycles()
uint64_t yaze::emu::Apu::GetCycles () const inline
Definition at line 68 of file apu.h.
References cycles_.
Referenced by yaze::emu::Snes::ReadBBus().
GetStatus()
uint8_t yaze::emu::Apu::GetStatus () const inline
Definition at line 69 of file apu.h.
References ram.
GetControl()
uint8_t yaze::emu::Apu::GetControl () const inline
Definition at line 70 of file apu.h.
References ram.
GetSamples()
void yaze::emu::Apu::GetSamples (int16_t * buffer, int count, bool loop = false) inline
Definition at line 71 of file apu.h.
References dsp_, and yaze::emu::Dsp::GetSamples().
WriteDma()
void yaze::emu::Apu::WriteDma (uint16_t address, const uint8_t * data, int count) inline
Definition at line 74 of file apu.h.
References ram.
Member Data Documentation
in_ports_
std::array<uint8_t, 6> yaze::emu::Apu::in_ports_
Definition at line 81 of file apu.h.
Referenced by Read(), Reset(), RunCycles(), Write(), and yaze::emu::Snes::WriteBBus().
out_ports_
std::array<uint8_t, 4> yaze::emu::Apu::out_ports_
Definition at line 82 of file apu.h.
Referenced by yaze::emu::Snes::ReadBBus(), Reset(), RunCycles(), and Write().
ram
std::vector<uint8_t> yaze::emu::Apu::ram = std::vector<uint8_t>(0x10000, 0)
Definition at line 83 of file apu.h.
Referenced by GetControl(), GetStatus(), Init(), Read(), Reset(), RunCycles(), Write(), and WriteDma().
rom_readable_
bool yaze::emu::Apu::rom_readable_ = false private
Definition at line 86 of file apu.h.
Referenced by Read(), Reset(), RunCycles(), and Write().
dsp_adr_
uint8_t yaze::emu::Apu::dsp_adr_ = 0 private
Definition at line 88 of file apu.h.
Referenced by Read(), Reset(), and Write().
cycles_
uint32_t yaze::emu::Apu::cycles_ = 0 private
Definition at line 89 of file apu.h.
Referenced by Cycle(), GetCycles(), Reset(), RunCycles(), and Write().
transfer_size_
uint8_t yaze::emu::Apu::transfer_size_ = 0 private
Definition at line 92 of file apu.h.
Referenced by Reset(), and Write().
in_transfer_
bool yaze::emu::Apu::in_transfer_ = false private
Definition at line 93 of file apu.h.
Referenced by Reset(), and Write().
memory_
MemoryImpl& yaze::emu::Apu::memory_ private
Definition at line 95 of file apu.h.
Referenced by RunCycles().
timer_
std::array<Timer, 3> yaze::emu::Apu::timer_ private
Definition at line 96 of file apu.h.
Referenced by Cycle(), Read(), Reset(), and Write().
callbacks_
ApuCallbacks yaze::emu::Apu::callbacks_ private
Initial value:
= {
      [&](uint16_t adr, uint8_t val) { SpcWrite(adr, val); },
      [&](uint16_t adr) { return SpcRead(adr); },
      [&](bool waiting) { SpcIdle(waiting); },
  }
Definition at line 98 of file apu.h.
dsp_
Dsp yaze::emu::Apu::dsp_ {ram} private
Definition at line 103 of file apu.h.
Referenced by Cycle(), dsp(), GetSamples(), Read(), Reset(), and Write().
spc700_
Spc700 yaze::emu::Apu::spc700_ {callbacks_} private
Definition at line 104 of file apu.h.
Referenced by Read(), Reset(), RunCycles(), spc700(), and Write().
The documentation for this class was generated from the following files:
src/app/emu/audio/apu.h
src/app/emu/audio/apu.cc