yaze: yaze::editor::AgentEditor Class Reference
yaze::editor::AgentEditor Class Reference
Comprehensive AI Agent Platform & Bot Creator.
#include <agent_editor.h>
Classes
struct AgentConfig
struct BotProfile
struct CaptureConfig
struct SessionInfo
Public Types
enum class CollaborationMode { kLocal , kNetwork }
Public Member Functions
AgentEditor ()
~AgentEditor () override
void Initialize () override
absl::Status Load () override
absl::Status Save () override
absl::Status Update () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
void InitializeWithDependencies (ToastManager *toast_manager, ProposalDrawer *proposal_drawer, Rom *rom)
void SetRomContext (Rom *rom)
void DrawDashboard ()
AgentConfig GetCurrentConfig () const
void ApplyConfig (const AgentConfig &config)
absl::Status SaveBotProfile (const BotProfile &profile)
absl::Status LoadBotProfile (const std::string &name)
absl::Status DeleteBotProfile (const std::string &name)
std::vector< BotProfile > GetAllProfiles () const
BotProfile GetCurrentProfile () const
void SetCurrentProfile (const BotProfile &profile)
absl::Status ExportProfile (const BotProfile &profile, const std::filesystem::path &path)
absl::Status ImportProfile (const std::filesystem::path &path)
AgentChatWidget * GetChatWidget ()
bool IsChatActive () const
void SetChatActive (bool active)
void ToggleChat ()
void OpenChatWindow ()
absl::StatusOr< SessionInfo > HostSession (const std::string &session_name, CollaborationMode mode=CollaborationMode::kLocal)
absl::StatusOr< SessionInfo > JoinSession (const std::string &session_code, CollaborationMode mode=CollaborationMode::kLocal)
absl::Status LeaveSession ()
absl::StatusOr< SessionInfo > RefreshSession ()
absl::Status CaptureSnapshot (std::filesystem::path *output_path, const CaptureConfig &config)
absl::Status SendToGemini (const std::filesystem::path &image_path, const std::string &prompt)
bool IsInSession () const
CollaborationMode GetCurrentMode () const
std::optional< SessionInfo > GetCurrentSession () const
AgentCollaborationCoordinator * GetLocalCoordinator ()
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
void SetDependencies (const EditorDependencies &deps)
virtual absl::Status Clear ()
EditorType type () const
bool * active ()
void set_active (bool active)
void toggle_active ()
virtual bool IsRomLoaded () const
virtual std::string GetRomStatus () const
Public Attributes
float pulse_animation_ = 0.0f
float scanline_offset_ = 0.0f
float glitch_timer_ = 0.0f
int blink_counter_ = 0
Private Member Functions
void DrawConfigurationPanel ()
void DrawStatusPanel ()
void DrawMetricsPanel ()
void DrawPromptEditorPanel ()
void DrawBotProfilesPanel ()
void DrawChatHistoryViewer ()
void DrawAdvancedMetricsPanel ()
void DrawCommonTilesEditor ()
void DrawNewPromptCreator ()
void SetupChatWidgetCallbacks ()
void SetupMultimodalCallbacks ()
std::filesystem::path GetProfilesDirectory () const
absl::Status EnsureProfilesDirectory ()
std::string ProfileToJson (const BotProfile &profile) const
absl::StatusOr< BotProfile > JsonToProfile (const std::string &json) const
Private Attributes
std::unique_ptr< AgentChatWidget > chat_widget_
std::unique_ptr< AgentCollaborationCoordinator > local_coordinator_
ToastManager * toast_manager_ = nullptr
ProposalDrawer * proposal_drawer_ = nullptr
Rom * rom_ = nullptr
AgentConfig current_config_
BotProfile current_profile_
std::vector< BotProfile > loaded_profiles_
std::unique_ptr< TextEditor > prompt_editor_
std::unique_ptr< TextEditor > common_tiles_editor_
bool prompt_editor_initialized_ = false
bool common_tiles_initialized_ = false
std::string active_prompt_file_ = "system_prompt_v3.txt"
char new_prompt_name_ [128] = {}
CollaborationMode current_mode_ = CollaborationMode::kLocal
bool in_session_ = false
std::string current_session_id_
std::string current_session_name_
std::vector< std::string > current_participants_
bool show_advanced_settings_ = false
bool show_prompt_editor_ = false
bool show_bot_profiles_ = false
bool show_chat_history_ = false
bool show_metrics_dashboard_ = false
int selected_tab_ = 0
std::vector< cli::agent::ChatMessage > cached_history_
bool history_needs_refresh_ = true
Additional Inherited Members
Protected Member Functions inherited from yaze::editor::Editor
std::string MakeCardTitle (const std::string &base_title) const
std::string MakeCardId (const std::string &base_id) const
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorDependencies dependencies_
Detailed Description
Comprehensive AI Agent Platform & Bot Creator.
A full-featured bot creation and management platform:
Agent provider configuration (Ollama, Gemini, Mock)
Model selection and parameters
System prompt editing with live syntax highlighting
Bot profile management (create, save, load custom bots)
Chat history viewer and management
Session metrics and analytics dashboard
Collaboration settings (Local/Network)
Z3ED command automation presets
Multimodal/vision configuration
Export/Import bot configurations
The chat widget is separate and managed by EditorManager, with a dense/compact mode for focused conversations.
Definition at line 50 of file agent_editor.h.
Member Enumeration Documentation
CollaborationMode
enum class yaze::editor::AgentEditor::CollaborationMode strong
Enumerator
kLocal
kNetwork
Definition at line 133 of file agent_editor.h.
Constructor & Destructor Documentation
AgentEditor()
yaze::editor::AgentEditor::AgentEditor ()
Definition at line 31 of file agent_editor.cc.
References chat_widget_, common_tiles_editor_, TextEditor::LanguageDefinition::CPlusPlus(), current_config_, current_profile_, yaze::editor::AgentEditor::BotProfile::description, EnsureProfilesDirectory(), yaze::editor::kAgent, local_coordinator_, yaze::editor::AgentEditor::BotProfile::max_retry_attempts, yaze::editor::AgentEditor::BotProfile::max_tool_iterations, yaze::editor::AgentEditor::AgentConfig::max_tool_iterations, yaze::editor::AgentEditor::BotProfile::name, prompt_editor_, yaze::editor::AgentEditor::BotProfile::provider, yaze::editor::AgentEditor::AgentConfig::provider, yaze::editor::AgentEditor::BotProfile::show_reasoning, yaze::editor::AgentEditor::AgentConfig::show_reasoning, yaze::editor::AgentEditor::BotProfile::tags, and yaze::editor::Editor::type_.
~AgentEditor()
yaze::editor::AgentEditor::~AgentEditor () override default
Member Function Documentation
Initialize()
void yaze::editor::AgentEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 69 of file agent_editor.cc.
References EnsureProfilesDirectory().
Load()
absl::Status yaze::editor::AgentEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 74 of file agent_editor.cc.
References GetProfilesDirectory(), JsonToProfile(), and loaded_profiles_.
Referenced by DeleteBotProfile(), and SaveBotProfile().
Save()
absl::Status yaze::editor::AgentEditor::Save () override virtual
Implements yaze::editor::Editor.
Definition at line 97 of file agent_editor.cc.
References current_profile_, and SaveBotProfile().
Referenced by DrawConfigurationPanel(), and DrawDashboard().
Update()
absl::Status yaze::editor::AgentEditor::Update () override virtual
Implements yaze::editor::Editor.
Definition at line 102 of file agent_editor.cc.
References yaze::editor::Editor::active_, and DrawDashboard().
Cut()
absl::Status yaze::editor::AgentEditor::Cut () inline override virtual
Implements yaze::editor::Editor.
Definition at line 60 of file agent_editor.h.
Copy()
absl::Status yaze::editor::AgentEditor::Copy () inline override virtual
Implements yaze::editor::Editor.
Definition at line 61 of file agent_editor.h.
Paste()
absl::Status yaze::editor::AgentEditor::Paste () inline override virtual
Implements yaze::editor::Editor.
Definition at line 62 of file agent_editor.h.
Undo()
absl::Status yaze::editor::AgentEditor::Undo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 63 of file agent_editor.h.
Redo()
absl::Status yaze::editor::AgentEditor::Redo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 64 of file agent_editor.h.
Find()
absl::Status yaze::editor::AgentEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 65 of file agent_editor.h.
InitializeWithDependencies()
void yaze::editor::AgentEditor::InitializeWithDependencies (ToastManager * toast_manager, ProposalDrawer * proposal_drawer, Rom * rom)
Definition at line 114 of file agent_editor.cc.
References chat_widget_, proposal_drawer_, rom_, SetupChatWidgetCallbacks(), SetupMultimodalCallbacks(), and toast_manager_.
SetRomContext()
void yaze::editor::AgentEditor::SetRomContext (Rom * rom)
Definition at line 133 of file agent_editor.cc.
References chat_widget_, and rom_.
DrawDashboard()
void yaze::editor::AgentEditor::DrawDashboard ()
Todo:
Open file dialog for export
Todo:
Open file dialog for import
Definition at line 140 of file agent_editor.cc.
References yaze::editor::Editor::active_, blink_counter_, DrawAdvancedMetricsPanel(), DrawBotProfilesPanel(), DrawChatHistoryViewer(), DrawCommonTilesEditor(), DrawConfigurationPanel(), DrawNewPromptCreator(), DrawPromptEditorPanel(), DrawStatusPanel(), glitch_timer_, ICON_MD_ADD, ICON_MD_ANALYTICS, ICON_MD_CHAT, ICON_MD_EDIT, ICON_MD_FILE_DOWNLOAD, ICON_MD_FILE_UPLOAD, ICON_MD_FOLDER, ICON_MD_GRID_ON, ICON_MD_HISTORY, ICON_MD_MENU, ICON_MD_SAVE, ICON_MD_SMART_TOY, ICON_MD_VIEW_LIST, yaze::editor::kInfo, yaze::editor::kSuccess, OpenChatWindow(), pulse_animation_, Save(), scanline_offset_, yaze::editor::ToastManager::Show(), show_bot_profiles_, show_chat_history_, show_metrics_dashboard_, show_prompt_editor_, and toast_manager_.
Referenced by Update().
GetCurrentConfig()
AgentEditor::AgentConfig yaze::editor::AgentEditor::GetCurrentConfig () const
Definition at line 1344 of file agent_editor.cc.
References current_config_.
ApplyConfig()
void yaze::editor::AgentEditor::ApplyConfig (const AgentConfig & config)
Definition at line 1348 of file agent_editor.cc.
References yaze::editor::AgentChatWidget::AgentConfigState::ai_model, yaze::editor::AgentChatWidget::AgentConfigState::ai_provider, chat_widget_, current_config_, yaze::editor::AgentChatWidget::AgentConfigState::gemini_api_key, yaze::editor::AgentEditor::AgentConfig::gemini_api_key, yaze::editor::AgentChatWidget::AgentConfigState::max_tool_iterations, yaze::editor::AgentEditor::AgentConfig::max_tool_iterations, yaze::editor::AgentEditor::AgentConfig::model, yaze::editor::AgentChatWidget::AgentConfigState::ollama_host, yaze::editor::AgentEditor::AgentConfig::ollama_host, yaze::editor::AgentEditor::AgentConfig::provider, yaze::editor::AgentChatWidget::AgentConfigState::show_reasoning, yaze::editor::AgentEditor::AgentConfig::show_reasoning, yaze::editor::AgentChatWidget::AgentConfigState::verbose, and yaze::editor::AgentEditor::AgentConfig::verbose.
Referenced by DrawConfigurationPanel(), and LoadBotProfile().
SaveBotProfile()
absl::Status yaze::editor::AgentEditor::SaveBotProfile (const BotProfile & profile)
Definition at line 1110 of file agent_editor.cc.
References EnsureProfilesDirectory(), GetProfilesDirectory(), Load(), yaze::editor::AgentEditor::BotProfile::name, ProfileToJson(), and RETURN_IF_ERROR.
Referenced by ImportProfile(), and Save().
LoadBotProfile()
absl::Status yaze::editor::AgentEditor::LoadBotProfile (const std::string & name)
Definition at line 1134 of file agent_editor.cc.
References ApplyConfig(), ASSIGN_OR_RETURN, current_config_, current_profile_, yaze::editor::AgentEditor::AgentConfig::gemini_api_key, GetProfilesDirectory(), JsonToProfile(), yaze::editor::AgentEditor::AgentConfig::max_tool_iterations, yaze::editor::AgentEditor::AgentConfig::model, yaze::editor::AgentEditor::AgentConfig::ollama_host, yaze::editor::AgentEditor::AgentConfig::provider, yaze::editor::AgentEditor::AgentConfig::show_reasoning, and yaze::editor::AgentEditor::AgentConfig::verbose.
Referenced by DrawBotProfilesPanel().
DeleteBotProfile()
absl::Status yaze::editor::AgentEditor::DeleteBotProfile (const std::string & name)
Definition at line 1172 of file agent_editor.cc.
References GetProfilesDirectory(), and Load().
Referenced by DrawBotProfilesPanel().
GetAllProfiles()
std::vector< AgentEditor::BotProfile > yaze::editor::AgentEditor::GetAllProfiles () const
Definition at line 1187 of file agent_editor.cc.
References loaded_profiles_.
GetCurrentProfile()
BotProfile yaze::editor::AgentEditor::GetCurrentProfile () const inline
Definition at line 120 of file agent_editor.h.
References current_profile_.
SetCurrentProfile()
void yaze::editor::AgentEditor::SetCurrentProfile (const BotProfile & profile)
Definition at line 1191 of file agent_editor.cc.
References current_config_, current_profile_, yaze::editor::AgentEditor::BotProfile::gemini_api_key, yaze::editor::AgentEditor::AgentConfig::gemini_api_key, yaze::editor::AgentEditor::BotProfile::max_tool_iterations, yaze::editor::AgentEditor::AgentConfig::max_tool_iterations, yaze::editor::AgentEditor::BotProfile::model, yaze::editor::AgentEditor::AgentConfig::model, yaze::editor::AgentEditor::BotProfile::ollama_host, yaze::editor::AgentEditor::AgentConfig::ollama_host, yaze::editor::AgentEditor::BotProfile::provider, yaze::editor::AgentEditor::AgentConfig::provider, yaze::editor::AgentEditor::BotProfile::show_reasoning, yaze::editor::AgentEditor::AgentConfig::show_reasoning, yaze::editor::AgentEditor::BotProfile::verbose, and yaze::editor::AgentEditor::AgentConfig::verbose.
ExportProfile()
absl::Status yaze::editor::AgentEditor::ExportProfile (const BotProfile & profile, const std::filesystem::path & path)
Definition at line 1204 of file agent_editor.cc.
References ProfileToJson().
ImportProfile()
absl::Status yaze::editor::AgentEditor::ImportProfile (const std::filesystem::path & path)
Definition at line 1221 of file agent_editor.cc.
References ASSIGN_OR_RETURN, JsonToProfile(), and SaveBotProfile().
GetChatWidget()
AgentChatWidget * yaze::editor::AgentEditor::GetChatWidget () inline
Definition at line 126 of file agent_editor.h.
References chat_widget_.
IsChatActive()
bool yaze::editor::AgentEditor::IsChatActive () const
Definition at line 1365 of file agent_editor.cc.
References chat_widget_.
Referenced by ToggleChat().
SetChatActive()
void yaze::editor::AgentEditor::SetChatActive (bool active)
Definition at line 1369 of file agent_editor.cc.
References yaze::editor::Editor::active(), and chat_widget_.
Referenced by ToggleChat().
ToggleChat()
void yaze::editor::AgentEditor::ToggleChat ()
Definition at line 1375 of file agent_editor.cc.
References IsChatActive(), and SetChatActive().
OpenChatWindow()
void yaze::editor::AgentEditor::OpenChatWindow ()
Definition at line 1379 of file agent_editor.cc.
References chat_widget_.
Referenced by DrawDashboard(), and DrawStatusPanel().
HostSession()
absl::StatusOr< AgentEditor::SessionInfo > yaze::editor::AgentEditor::HostSession (const std::string & session_name, CollaborationMode mode = CollaborationMode::kLocal)
Definition at line 1385 of file agent_editor.cc.
References ASSIGN_OR_RETURN, chat_widget_, current_mode_, current_participants_, current_session_id_, current_session_name_, in_session_, kLocal, kNetwork, yaze::editor::kSuccess, local_coordinator_, yaze::editor::AgentEditor::SessionInfo::participants, yaze::editor::AgentEditor::SessionInfo::session_id, yaze::editor::AgentEditor::SessionInfo::session_name, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by SetupChatWidgetCallbacks().
JoinSession()
absl::StatusOr< AgentEditor::SessionInfo > yaze::editor::AgentEditor::JoinSession (const std::string & session_code, CollaborationMode mode = CollaborationMode::kLocal)
Definition at line 1458 of file agent_editor.cc.
References ASSIGN_OR_RETURN, chat_widget_, current_mode_, current_participants_, current_session_id_, current_session_name_, in_session_, kLocal, kNetwork, yaze::editor::kSuccess, local_coordinator_, yaze::editor::AgentEditor::SessionInfo::participants, yaze::editor::AgentEditor::SessionInfo::session_id, yaze::editor::AgentEditor::SessionInfo::session_name, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by SetupChatWidgetCallbacks().
LeaveSession()
absl::Status yaze::editor::AgentEditor::LeaveSession ()
Definition at line 1531 of file agent_editor.cc.
References chat_widget_, current_mode_, current_participants_, current_session_id_, current_session_name_, in_session_, yaze::editor::kInfo, kLocal, kNetwork, local_coordinator_, RETURN_IF_ERROR, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by SetupChatWidgetCallbacks().
RefreshSession()
absl::StatusOr< AgentEditor::SessionInfo > yaze::editor::AgentEditor::RefreshSession ()
Definition at line 1564 of file agent_editor.cc.
References ASSIGN_OR_RETURN, current_mode_, current_participants_, current_session_id_, current_session_name_, in_session_, kLocal, local_coordinator_, yaze::editor::AgentEditor::SessionInfo::participants, yaze::editor::AgentEditor::SessionInfo::session_id, and yaze::editor::AgentEditor::SessionInfo::session_name.
Referenced by SetupChatWidgetCallbacks().
CaptureSnapshot()
absl::Status yaze::editor::AgentEditor::CaptureSnapshot (std::filesystem::path * output_path, const CaptureConfig & config)
Definition at line 1590 of file agent_editor.cc.
SendToGemini()
absl::Status yaze::editor::AgentEditor::SendToGemini (const std::filesystem::path & image_path, const std::string & prompt)
Definition at line 1597 of file agent_editor.cc.
IsInSession()
bool yaze::editor::AgentEditor::IsInSession () const
Definition at line 1639 of file agent_editor.cc.
References in_session_.
GetCurrentMode()
AgentEditor::CollaborationMode yaze::editor::AgentEditor::GetCurrentMode () const
Definition at line 1643 of file agent_editor.cc.
References current_mode_.
GetCurrentSession()
std::optional< AgentEditor::SessionInfo > yaze::editor::AgentEditor::GetCurrentSession () const
Definition at line 1647 of file agent_editor.cc.
References current_participants_, current_session_id_, current_session_name_, in_session_, yaze::editor::AgentEditor::SessionInfo::participants, yaze::editor::AgentEditor::SessionInfo::session_id, and yaze::editor::AgentEditor::SessionInfo::session_name.
GetLocalCoordinator()
AgentCollaborationCoordinator * yaze::editor::AgentEditor::GetLocalCoordinator () inline
Definition at line 177 of file agent_editor.h.
References local_coordinator_.
DrawConfigurationPanel()
void yaze::editor::AgentEditor::DrawConfigurationPanel () private
Definition at line 316 of file agent_editor.cc.
References ApplyConfig(), current_config_, current_profile_, yaze::editor::AgentEditor::BotProfile::description, DrawMetricsPanel(), yaze::editor::AgentEditor::BotProfile::gemini_api_key, yaze::editor::AgentEditor::AgentConfig::gemini_api_key, ICON_MD_ANALYTICS, ICON_MD_CHECK, ICON_MD_CHECK_CIRCLE, ICON_MD_CLOUD, ICON_MD_INFO, ICON_MD_LOOP, ICON_MD_REFRESH, ICON_MD_SETTINGS, ICON_MD_SMART_TOY, ICON_MD_TUNE, ICON_MD_VISIBILITY, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::AgentEditor::BotProfile::max_retry_attempts, yaze::editor::AgentEditor::BotProfile::max_tool_iterations, yaze::editor::AgentEditor::AgentConfig::max_tool_iterations, yaze::editor::AgentEditor::BotProfile::model, yaze::editor::AgentEditor::AgentConfig::model, yaze::editor::AgentEditor::BotProfile::name, yaze::editor::AgentEditor::BotProfile::ollama_host, yaze::editor::AgentEditor::AgentConfig::ollama_host, yaze::editor::AgentEditor::BotProfile::provider, yaze::editor::AgentEditor::AgentConfig::provider, Save(), yaze::editor::ToastManager::Show(), yaze::editor::AgentEditor::BotProfile::show_reasoning, yaze::editor::AgentEditor::AgentConfig::show_reasoning, yaze::editor::AgentEditor::BotProfile::tags, toast_manager_, yaze::editor::AgentEditor::BotProfile::verbose, and yaze::editor::AgentEditor::AgentConfig::verbose.
Referenced by DrawDashboard().
DrawStatusPanel()
void yaze::editor::AgentEditor::DrawStatusPanel () private
Definition at line 537 of file agent_editor.cc.
References chat_widget_, ICON_MD_CANCEL, ICON_MD_CHAT, ICON_MD_CHECK_CIRCLE, ICON_MD_GAMEPAD, ICON_MD_OPEN_IN_NEW, ICON_MD_TIPS_AND_UPDATES, ICON_MD_WARNING, yaze::Rom::is_loaded(), OpenChatWindow(), rom_, and yaze::Rom::title().
Referenced by DrawDashboard().
DrawMetricsPanel()
void yaze::editor::AgentEditor::DrawMetricsPanel () private
Definition at line 595 of file agent_editor.cc.
References chat_widget_, and ICON_MD_ANALYTICS.
Referenced by DrawConfigurationPanel().
DrawPromptEditorPanel()
void yaze::editor::AgentEditor::DrawPromptEditorPanel () private
Definition at line 606 of file agent_editor.cc.
References active_prompt_file_, current_profile_, ICON_MD_CHECK_CIRCLE, ICON_MD_EDIT, ICON_MD_REFRESH, ICON_MD_SAVE, yaze::editor::kSuccess, yaze::AssetLoader::LoadTextFile(), prompt_editor_, prompt_editor_initialized_, yaze::editor::ToastManager::Show(), yaze::editor::AgentEditor::BotProfile::system_prompt, and toast_manager_.
Referenced by DrawDashboard().
DrawBotProfilesPanel()
void yaze::editor::AgentEditor::DrawBotProfilesPanel () private
Definition at line 704 of file agent_editor.cc.
References yaze::editor::AgentEditor::BotProfile::created_at, current_profile_, DeleteBotProfile(), yaze::editor::AgentEditor::BotProfile::description, ICON_MD_ADD, ICON_MD_DELETE, ICON_MD_FOLDER, ICON_MD_LIST, ICON_MD_STAR, yaze::editor::kInfo, yaze::editor::kSuccess, LoadBotProfile(), loaded_profiles_, yaze::editor::AgentEditor::BotProfile::model, yaze::editor::AgentEditor::BotProfile::modified_at, yaze::editor::AgentEditor::BotProfile::name, yaze::editor::AgentEditor::BotProfile::provider, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by DrawDashboard().
DrawChatHistoryViewer()
void yaze::editor::AgentEditor::DrawChatHistoryViewer () private
Definition at line 804 of file agent_editor.cc.
References cached_history_, chat_widget_, history_needs_refresh_, ICON_MD_DELETE, ICON_MD_HISTORY, ICON_MD_REFRESH, yaze::editor::kInfo, yaze::cli::agent::ChatMessage::kUser, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by DrawDashboard().
DrawAdvancedMetricsPanel()
void yaze::editor::AgentEditor::DrawAdvancedMetricsPanel () private
Definition at line 863 of file agent_editor.cc.
References chat_widget_, ICON_MD_ANALYTICS, ICON_MD_BUILD, ICON_MD_CHAT, ICON_MD_PREVIEW, and ICON_MD_TIMER.
Referenced by DrawDashboard().
DrawCommonTilesEditor()
void yaze::editor::AgentEditor::DrawCommonTilesEditor () private
Definition at line 916 of file agent_editor.cc.
References common_tiles_editor_, common_tiles_initialized_, ICON_MD_CHECK_CIRCLE, ICON_MD_FOLDER_OPEN, ICON_MD_GRID_ON, ICON_MD_INFO, ICON_MD_REFRESH, ICON_MD_SAVE, yaze::editor::kInfo, yaze::editor::kSuccess, yaze::AssetLoader::LoadTextFile(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by DrawDashboard().
DrawNewPromptCreator()
void yaze::editor::AgentEditor::DrawNewPromptCreator () private
Todo:
Actually save the file
Definition at line 993 of file agent_editor.cc.
References ICON_MD_ADD, ICON_MD_FILE_COPY, ICON_MD_NOTE_ADD, ICON_MD_SAVE, ICON_MD_WARNING, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::AssetLoader::LoadTextFile(), new_prompt_name_, prompt_editor_, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by DrawDashboard().
SetupChatWidgetCallbacks()
void yaze::editor::AgentEditor::SetupChatWidgetCallbacks () private
Definition at line 1659 of file agent_editor.cc.
References ASSIGN_OR_RETURN, chat_widget_, current_mode_, yaze::editor::AgentChatWidget::CollaborationCallbacks::host_session, HostSession(), yaze::editor::AgentChatWidget::CollaborationCallbacks::join_session, JoinSession(), yaze::editor::AgentChatWidget::CollaborationCallbacks::leave_session, LeaveSession(), yaze::editor::AgentChatWidget::CollaborationCallbacks::SessionContext::participants, yaze::editor::AgentChatWidget::CollaborationCallbacks::refresh_session, RefreshSession(), yaze::editor::AgentChatWidget::CollaborationCallbacks::SessionContext::session_id, and yaze::editor::AgentChatWidget::CollaborationCallbacks::SessionContext::session_name.
Referenced by InitializeWithDependencies().
SetupMultimodalCallbacks()
void yaze::editor::AgentEditor::SetupMultimodalCallbacks () private
Definition at line 1711 of file agent_editor.cc.
Referenced by InitializeWithDependencies().
GetProfilesDirectory()
std::filesystem::path yaze::editor::AgentEditor::GetProfilesDirectory () const private
Definition at line 1244 of file agent_editor.cc.
References yaze::util::PlatformPaths::GetConfigDirectory().
Referenced by DeleteBotProfile(), EnsureProfilesDirectory(), Load(), LoadBotProfile(), and SaveBotProfile().
EnsureProfilesDirectory()
absl::Status yaze::editor::AgentEditor::EnsureProfilesDirectory () private
Definition at line 1253 of file agent_editor.cc.
References GetProfilesDirectory().
Referenced by AgentEditor(), Initialize(), and SaveBotProfile().
ProfileToJson()
std::string yaze::editor::AgentEditor::ProfileToJson (const BotProfile & profile) const private
Definition at line 1264 of file agent_editor.cc.
References yaze::editor::AgentEditor::BotProfile::created_at, yaze::editor::AgentEditor::BotProfile::description, yaze::editor::AgentEditor::BotProfile::gemini_api_key, yaze::editor::AgentEditor::BotProfile::max_retry_attempts, yaze::editor::AgentEditor::BotProfile::max_tool_iterations, yaze::editor::AgentEditor::BotProfile::model, yaze::editor::AgentEditor::BotProfile::modified_at, yaze::editor::AgentEditor::BotProfile::name, yaze::editor::AgentEditor::BotProfile::ollama_host, yaze::editor::AgentEditor::BotProfile::provider, yaze::editor::AgentEditor::BotProfile::show_reasoning, yaze::editor::AgentEditor::BotProfile::system_prompt, yaze::editor::AgentEditor::BotProfile::tags, and yaze::editor::AgentEditor::BotProfile::verbose.
Referenced by ExportProfile(), and SaveBotProfile().
JsonToProfile()
absl::StatusOr< AgentEditor::BotProfile > yaze::editor::AgentEditor::JsonToProfile (const std::string & json) const private
Definition at line 1290 of file agent_editor.cc.
References yaze::editor::AgentEditor::BotProfile::created_at, yaze::editor::AgentEditor::BotProfile::description, yaze::editor::AgentEditor::BotProfile::gemini_api_key, yaze::editor::AgentEditor::BotProfile::max_retry_attempts, yaze::editor::AgentEditor::BotProfile::max_tool_iterations, yaze::editor::AgentEditor::BotProfile::model, yaze::editor::AgentEditor::BotProfile::modified_at, yaze::editor::AgentEditor::BotProfile::name, yaze::editor::AgentEditor::BotProfile::ollama_host, yaze::editor::AgentEditor::BotProfile::provider, yaze::editor::AgentEditor::BotProfile::show_reasoning, yaze::editor::AgentEditor::BotProfile::system_prompt, yaze::editor::AgentEditor::BotProfile::tags, and yaze::editor::AgentEditor::BotProfile::verbose.
Referenced by ImportProfile(), Load(), and LoadBotProfile().
Member Data Documentation
pulse_animation_
float yaze::editor::AgentEditor::pulse_animation_ = 0.0f
Definition at line 107 of file agent_editor.h.
Referenced by DrawDashboard().
scanline_offset_
float yaze::editor::AgentEditor::scanline_offset_ = 0.0f
Definition at line 108 of file agent_editor.h.
Referenced by DrawDashboard().
glitch_timer_
float yaze::editor::AgentEditor::glitch_timer_ = 0.0f
Definition at line 109 of file agent_editor.h.
Referenced by DrawDashboard().
blink_counter_
int yaze::editor::AgentEditor::blink_counter_ = 0
Definition at line 110 of file agent_editor.h.
Referenced by DrawDashboard().
chat_widget_
std::unique_ptr<AgentChatWidget> yaze::editor::AgentEditor::chat_widget_ private
Definition at line 205 of file agent_editor.h.
Referenced by AgentEditor(), ApplyConfig(), DrawAdvancedMetricsPanel(), DrawChatHistoryViewer(), DrawMetricsPanel(), DrawStatusPanel(), GetChatWidget(), HostSession(), InitializeWithDependencies(), IsChatActive(), JoinSession(), LeaveSession(), OpenChatWindow(), SetChatActive(), SetRomContext(), and SetupChatWidgetCallbacks().
local_coordinator_
std::unique_ptr<AgentCollaborationCoordinator> yaze::editor::AgentEditor::local_coordinator_ private
Definition at line 206 of file agent_editor.h.
Referenced by AgentEditor(), GetLocalCoordinator(), HostSession(), JoinSession(), LeaveSession(), and RefreshSession().
toast_manager_
ToastManager* yaze::editor::AgentEditor::toast_manager_ = nullptr private
Definition at line 211 of file agent_editor.h.
Referenced by DrawBotProfilesPanel(), DrawChatHistoryViewer(), DrawCommonTilesEditor(), DrawConfigurationPanel(), DrawDashboard(), DrawNewPromptCreator(), DrawPromptEditorPanel(), HostSession(), InitializeWithDependencies(), JoinSession(), and LeaveSession().
proposal_drawer_
ProposalDrawer* yaze::editor::AgentEditor::proposal_drawer_ = nullptr private
Definition at line 212 of file agent_editor.h.
Referenced by InitializeWithDependencies().
rom_
Rom* yaze::editor::AgentEditor::rom_ = nullptr private
Definition at line 213 of file agent_editor.h.
Referenced by DrawStatusPanel(), InitializeWithDependencies(), and SetRomContext().
current_config_
AgentConfig yaze::editor::AgentEditor::current_config_ private
Definition at line 216 of file agent_editor.h.
Referenced by AgentEditor(), ApplyConfig(), DrawConfigurationPanel(), GetCurrentConfig(), LoadBotProfile(), and SetCurrentProfile().
current_profile_
BotProfile yaze::editor::AgentEditor::current_profile_ private
Definition at line 219 of file agent_editor.h.
Referenced by AgentEditor(), DrawBotProfilesPanel(), DrawConfigurationPanel(), DrawPromptEditorPanel(), GetCurrentProfile(), LoadBotProfile(), Save(), and SetCurrentProfile().
loaded_profiles_
std::vector<BotProfile> yaze::editor::AgentEditor::loaded_profiles_ private
Definition at line 220 of file agent_editor.h.
Referenced by DrawBotProfilesPanel(), GetAllProfiles(), and Load().
prompt_editor_
std::unique_ptr<TextEditor> yaze::editor::AgentEditor::prompt_editor_ private
Definition at line 223 of file agent_editor.h.
Referenced by AgentEditor(), DrawNewPromptCreator(), and DrawPromptEditorPanel().
common_tiles_editor_
std::unique_ptr<TextEditor> yaze::editor::AgentEditor::common_tiles_editor_ private
Definition at line 224 of file agent_editor.h.
Referenced by AgentEditor(), and DrawCommonTilesEditor().
prompt_editor_initialized_
bool yaze::editor::AgentEditor::prompt_editor_initialized_ = false private
Definition at line 225 of file agent_editor.h.
Referenced by DrawPromptEditorPanel().
common_tiles_initialized_
bool yaze::editor::AgentEditor::common_tiles_initialized_ = false private
Definition at line 226 of file agent_editor.h.
Referenced by DrawCommonTilesEditor().
active_prompt_file_
std::string yaze::editor::AgentEditor::active_prompt_file_ = "system_prompt_v3.txt" private
Definition at line 227 of file agent_editor.h.
Referenced by DrawPromptEditorPanel().
new_prompt_name_
char yaze::editor::AgentEditor::new_prompt_name_[128] = {} private
Definition at line 228 of file agent_editor.h.
Referenced by DrawNewPromptCreator().
current_mode_
CollaborationMode yaze::editor::AgentEditor::current_mode_ = CollaborationMode::kLocal private
Definition at line 231 of file agent_editor.h.
Referenced by GetCurrentMode(), HostSession(), JoinSession(), LeaveSession(), RefreshSession(), and SetupChatWidgetCallbacks().
in_session_
bool yaze::editor::AgentEditor::in_session_ = false private
Definition at line 232 of file agent_editor.h.
Referenced by GetCurrentSession(), HostSession(), IsInSession(), JoinSession(), LeaveSession(), and RefreshSession().
current_session_id_
std::string yaze::editor::AgentEditor::current_session_id_ private
Definition at line 233 of file agent_editor.h.
Referenced by GetCurrentSession(), HostSession(), JoinSession(), LeaveSession(), and RefreshSession().
current_session_name_
std::string yaze::editor::AgentEditor::current_session_name_ private
Definition at line 234 of file agent_editor.h.
Referenced by GetCurrentSession(), HostSession(), JoinSession(), LeaveSession(), and RefreshSession().
current_participants_
std::vector<std::string> yaze::editor::AgentEditor::current_participants_ private
Definition at line 235 of file agent_editor.h.
Referenced by GetCurrentSession(), HostSession(), JoinSession(), LeaveSession(), and RefreshSession().
show_advanced_settings_
bool yaze::editor::AgentEditor::show_advanced_settings_ = false private
Definition at line 238 of file agent_editor.h.
show_prompt_editor_
bool yaze::editor::AgentEditor::show_prompt_editor_ = false private
Definition at line 239 of file agent_editor.h.
Referenced by DrawDashboard().
show_bot_profiles_
bool yaze::editor::AgentEditor::show_bot_profiles_ = false private
Definition at line 240 of file agent_editor.h.
Referenced by DrawDashboard().
show_chat_history_
bool yaze::editor::AgentEditor::show_chat_history_ = false private
Definition at line 241 of file agent_editor.h.
Referenced by DrawDashboard().
show_metrics_dashboard_
bool yaze::editor::AgentEditor::show_metrics_dashboard_ = false private
Definition at line 242 of file agent_editor.h.
Referenced by DrawDashboard().
selected_tab_
int yaze::editor::AgentEditor::selected_tab_ = 0 private
Definition at line 243 of file agent_editor.h.
cached_history_
std::vector<cli::agent::ChatMessage> yaze::editor::AgentEditor::cached_history_ private
Definition at line 246 of file agent_editor.h.
Referenced by DrawChatHistoryViewer().
history_needs_refresh_
bool yaze::editor::AgentEditor::history_needs_refresh_ = true private
Definition at line 247 of file agent_editor.h.
Referenced by DrawChatHistoryViewer().
The documentation for this class was generated from the following files:
src/app/editor/agent/agent_editor.h
src/app/editor/agent/agent_editor.cc