yaze: yaze::cli::anonymous_namespace{test_suite_loader.cc} Namespace Reference
yaze::cli::anonymous_namespace{test_suite_loader.cc} Namespace Reference
Functions
std::string Trim (string_view value)
std::string StripComment (string_view line)
int CountIndent (string_view line)
bool ParseKeyValue (string_view input, std::string *key, std::string *value)
std::string Unquote (string_view value)
std::vector< std::string > ParseInlineList (string_view value)
absl::StatusOr< int > ParseInt (string_view value)
absl::StatusOr< int > ParseDurationSeconds (string_view value)
bool ParseBoolean (string_view value, bool *output)
std::string DeriveTestName (const std::string &path)
absl::Status ParseScalarConfig (const std::string &key, const std::string &value, TestSuiteConfig *config)
absl::Status ParseStringListBlock (const std::vector< std::string > &lines, size_t *index, int base_indent, std::vector< std::string > *output)
absl::Status ParseParametersBlock (const std::vector< std::string > &lines, size_t *index, int base_indent, std::map< std::string, std::string > *params)
absl::Status ParseTestCaseEntry (const std::vector< std::string > &lines, size_t *index, int base_indent, TestGroupDefinition *group)
absl::Status ParseTestsBlock (const std::vector< std::string > &lines, size_t *index, int base_indent, TestGroupDefinition *group)
absl::Status ParseGroupEntry (const std::vector< std::string > &lines, size_t *index, TestSuiteDefinition *suite)
absl::Status ParseGroupBlock (const std::vector< std::string > &lines, size_t *index, TestSuiteDefinition *suite)
absl::Status ParseConfigBlock (const std::vector< std::string > &lines, size_t *index, TestSuiteConfig *config)
Function Documentation
Trim()
std::string yaze::cli::anonymous_namespace{test_suite_loader.cc}::Trim (string_view value)
Definition at line 23 of file test_suite_loader.cc.
References Trim().
Referenced by ParseConfigBlock(), ParseGroupBlock(), ParseGroupEntry(), ParseInlineList(), ParseKeyValue(), ParseParametersBlock(), ParseStringListBlock(), ParseTestCaseEntry(), ParseTestsBlock(), Trim(), and Unquote().
StripComment()
std::string yaze::cli::anonymous_namespace{test_suite_loader.cc}::StripComment (string_view line)
Definition at line 27 of file test_suite_loader.cc.
References StripComment().
Referenced by ParseConfigBlock(), ParseGroupBlock(), ParseGroupEntry(), ParseParametersBlock(), ParseStringListBlock(), ParseTestCaseEntry(), ParseTestsBlock(), and StripComment().
CountIndent()
int yaze::cli::anonymous_namespace{test_suite_loader.cc}::CountIndent (string_view line)
Definition at line 47 of file test_suite_loader.cc.
References CountIndent().
Referenced by CountIndent(), ParseConfigBlock(), ParseGroupBlock(), ParseGroupEntry(), ParseParametersBlock(), ParseStringListBlock(), ParseTestCaseEntry(), and ParseTestsBlock().
ParseKeyValue()
bool yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseKeyValue (string_view input, std::string * key, std::string * value)
Definition at line 61 of file test_suite_loader.cc.
References ParseKeyValue(), and Trim().
Referenced by ParseConfigBlock(), ParseGroupEntry(), ParseKeyValue(), ParseParametersBlock(), and ParseTestCaseEntry().
Unquote()
std::string yaze::cli::anonymous_namespace{test_suite_loader.cc}::Unquote (string_view value)
Definition at line 71 of file test_suite_loader.cc.
References Trim(), and Unquote().
Referenced by ParseGroupEntry(), ParseInlineList(), ParseParametersBlock(), ParseStringListBlock(), ParseTestCaseEntry(), and Unquote().
ParseInlineList()
std::vector< std::string > yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseInlineList (string_view value)
Definition at line 82 of file test_suite_loader.cc.
References ParseInlineList(), Trim(), and Unquote().
Referenced by ParseGroupEntry(), ParseInlineList(), and ParseTestCaseEntry().
ParseInt()
absl::StatusOr< int > yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseInt (string_view value)
Definition at line 102 of file test_suite_loader.cc.
References ParseInt().
Referenced by ParseInt(), and ParseScalarConfig().
ParseDurationSeconds()
absl::StatusOr< int > yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseDurationSeconds (string_view value)
Definition at line 111 of file test_suite_loader.cc.
References ParseDurationSeconds().
Referenced by ParseDurationSeconds(), and ParseScalarConfig().
ParseBoolean()
bool yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseBoolean (string_view value, bool * output)
Definition at line 140 of file test_suite_loader.cc.
References ParseBoolean().
Referenced by ParseBoolean(), and ParseScalarConfig().
DeriveTestName()
std::string yaze::cli::anonymous_namespace{test_suite_loader.cc}::DeriveTestName (const std::string & path)
Definition at line 153 of file test_suite_loader.cc.
References DeriveTestName().
Referenced by DeriveTestName(), and ParseTestCaseEntry().
ParseScalarConfig()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseScalarConfig (const std::string & key, const std::string & value, TestSuiteConfig * config)
Definition at line 162 of file test_suite_loader.cc.
References ASSIGN_OR_RETURN, yaze::cli::TestSuiteConfig::parallel_execution, ParseBoolean(), ParseDurationSeconds(), ParseInt(), ParseScalarConfig(), yaze::cli::TestSuiteConfig::retry_on_failure, and yaze::cli::TestSuiteConfig::timeout_seconds.
Referenced by ParseConfigBlock(), and ParseScalarConfig().
ParseStringListBlock()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseStringListBlock (const std::vector< std::string > & lines, size_t * index, int base_indent, std::vector< std::string > * output)
Definition at line 188 of file test_suite_loader.cc.
References CountIndent(), ParseStringListBlock(), StripComment(), Trim(), and Unquote().
Referenced by ParseGroupEntry(), ParseStringListBlock(), and ParseTestCaseEntry().
ParseParametersBlock()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseParametersBlock (const std::vector< std::string > & lines, size_t * index, int base_indent, std::map< std::string, std::string > * params)
Definition at line 216 of file test_suite_loader.cc.
References CountIndent(), ParseKeyValue(), ParseParametersBlock(), StripComment(), Trim(), and Unquote().
Referenced by ParseParametersBlock(), and ParseTestCaseEntry().
ParseTestCaseEntry()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseTestCaseEntry (const std::vector< std::string > & lines, size_t * index, int base_indent, TestGroupDefinition * group)
Definition at line 245 of file test_suite_loader.cc.
References CountIndent(), DeriveTestName(), yaze::cli::TestCaseDefinition::description, yaze::cli::TestCaseDefinition::group_name, yaze::cli::TestCaseDefinition::id, yaze::cli::TestCaseDefinition::name, yaze::cli::TestGroupDefinition::name, yaze::cli::TestCaseDefinition::parameters, ParseInlineList(), ParseKeyValue(), ParseParametersBlock(), ParseStringListBlock(), ParseTestCaseEntry(), RETURN_IF_ERROR, yaze::cli::TestCaseDefinition::script_path, StripComment(), yaze::cli::TestCaseDefinition::tags, yaze::cli::TestGroupDefinition::tests, Trim(), and Unquote().
Referenced by ParseTestCaseEntry(), and ParseTestsBlock().
ParseTestsBlock()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseTestsBlock (const std::vector< std::string > & lines, size_t * index, int base_indent, TestGroupDefinition * group)
Definition at line 364 of file test_suite_loader.cc.
References CountIndent(), ParseTestCaseEntry(), ParseTestsBlock(), RETURN_IF_ERROR, StripComment(), and Trim().
Referenced by ParseGroupEntry(), and ParseTestsBlock().
ParseGroupEntry()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseGroupEntry (const std::vector< std::string > & lines, size_t * index, TestSuiteDefinition * suite)
Definition at line 387 of file test_suite_loader.cc.
References CountIndent(), yaze::cli::TestGroupDefinition::depends_on, yaze::cli::TestGroupDefinition::description, yaze::cli::TestSuiteDefinition::groups, yaze::cli::TestGroupDefinition::name, ParseGroupEntry(), ParseInlineList(), ParseKeyValue(), ParseStringListBlock(), ParseTestsBlock(), RETURN_IF_ERROR, StripComment(), Trim(), and Unquote().
Referenced by ParseGroupBlock(), and ParseGroupEntry().
ParseGroupBlock()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseGroupBlock (const std::vector< std::string > & lines, size_t * index, TestSuiteDefinition * suite)
Definition at line 484 of file test_suite_loader.cc.
References CountIndent(), ParseGroupBlock(), ParseGroupEntry(), RETURN_IF_ERROR, StripComment(), and Trim().
Referenced by ParseGroupBlock().
ParseConfigBlock()
absl::Status yaze::cli::anonymous_namespace{test_suite_loader.cc}::ParseConfigBlock (const std::vector< std::string > & lines, size_t * index, TestSuiteConfig * config)
Definition at line 506 of file test_suite_loader.cc.
References CountIndent(), ParseConfigBlock(), ParseKeyValue(), ParseScalarConfig(), RETURN_IF_ERROR, StripComment(), and Trim().
Referenced by ParseConfigBlock().