yaze: yaze::editor::MenuBuilder Class Reference
yaze::editor::MenuBuilder Class Reference
Fluent interface for building ImGui menus with icons.
#include <menu_builder.h>
Classes
struct Menu
struct MenuItem
Public Types
using Callback = std::function< void()>
using EnabledCheck = std::function< bool()>
Public Member Functions
MenuBuilder ()=default
MenuBuilder & BeginMenu (const char *label, const char *icon=nullptr)
Begin a top-level menu.
MenuBuilder & BeginSubMenu (const char *label, const char *icon=nullptr, EnabledCheck enabled=nullptr)
Begin a submenu.
MenuBuilder & EndMenu ()
End the current menu/submenu.
MenuBuilder & Item (const char *label, const char *icon, Callback callback, const char *shortcut=nullptr, EnabledCheck enabled=nullptr, EnabledCheck checked=nullptr)
Add a menu item.
MenuBuilder & Item (const char *label, Callback callback, const char *shortcut=nullptr, EnabledCheck enabled=nullptr)
Add a menu item without icon (convenience)
MenuBuilder & Separator ()
Add a separator.
MenuBuilder & DisabledItem (const char *label, const char *icon=nullptr)
Add a disabled item (grayed out)
void Draw ()
Draw the menu bar (call in main menu bar)
void Clear ()
Clear all menus.
Private Member Functions
void DrawMenuItem (const MenuItem &item)
Private Attributes
std::vector< Menu > menus_
Menu * current_menu_ = nullptr
std::vector< bool > submenu_stack_
int skip_depth_ = 0
Detailed Description
Fluent interface for building ImGui menus with icons.
Provides a cleaner, more maintainable way to construct menus:
MenuBuilder menu; menu.BeginMenu("File", ICON_MD_FOLDER) .Item("Open", ICON_MD_FILE_OPEN, []() { OpenFile(); }) .Separator() .Item("Quit", ICON_MD_EXIT_TO_APP, []() { Quit(); }) .EndMenu();
Definition at line 27 of file menu_builder.h.
Member Typedef Documentation
Callback
using yaze::editor::MenuBuilder::Callback = std::function<void()>
Definition at line 29 of file menu_builder.h.
EnabledCheck
using yaze::editor::MenuBuilder::EnabledCheck = std::function<bool()>
Definition at line 30 of file menu_builder.h.
Constructor & Destructor Documentation
MenuBuilder()
yaze::editor::MenuBuilder::MenuBuilder () default
References BeginMenu().
Member Function Documentation
BeginMenu()
MenuBuilder & yaze::editor::MenuBuilder::BeginMenu (const char * label, const char * icon = nullptr)
Begin a top-level menu.
Definition at line 8 of file menu_builder.cc.
References current_menu_, yaze::editor::MenuBuilder::Menu::icon, yaze::editor::MenuBuilder::Menu::label, and menus_.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), and MenuBuilder().
BeginSubMenu()
MenuBuilder & yaze::editor::MenuBuilder::BeginSubMenu (const char * label, const char * icon = nullptr, EnabledCheck enabled = nullptr)
Begin a submenu.
Definition at line 19 of file menu_builder.cc.
References current_menu_, yaze::editor::MenuBuilder::MenuItem::enabled, yaze::editor::MenuBuilder::MenuItem::icon, yaze::editor::MenuBuilder::Menu::items, yaze::editor::MenuBuilder::MenuItem::kSubMenuBegin, yaze::editor::MenuBuilder::MenuItem::label, and yaze::editor::MenuBuilder::MenuItem::type.
Referenced by yaze::editor::EditorManager::BuildModernMenu().
EndMenu()
MenuBuilder & yaze::editor::MenuBuilder::EndMenu ()
End the current menu/submenu.
Definition at line 34 of file menu_builder.cc.
References current_menu_, yaze::editor::MenuBuilder::Menu::items, yaze::editor::MenuBuilder::MenuItem::kSubMenuBegin, yaze::editor::MenuBuilder::MenuItem::kSubMenuEnd, and yaze::editor::MenuBuilder::MenuItem::type.
Item() [1/2]
MenuBuilder & yaze::editor::MenuBuilder::Item (const char * label, const char * icon, Callback callback, const char * shortcut = nullptr, EnabledCheck enabled = nullptr, EnabledCheck checked = nullptr)
Add a menu item.
Definition at line 67 of file menu_builder.cc.
References yaze::editor::MenuBuilder::MenuItem::callback, yaze::editor::MenuBuilder::MenuItem::checked, current_menu_, yaze::editor::MenuBuilder::MenuItem::enabled, yaze::editor::MenuBuilder::MenuItem::icon, yaze::editor::MenuBuilder::Menu::items, yaze::editor::MenuBuilder::MenuItem::kItem, yaze::editor::MenuBuilder::MenuItem::label, yaze::editor::MenuBuilder::MenuItem::shortcut, and yaze::editor::MenuBuilder::MenuItem::type.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), and Item().
Item() [2/2]
MenuBuilder & yaze::editor::MenuBuilder::Item (const char * label, Callback callback, const char * shortcut = nullptr, EnabledCheck enabled = nullptr)
Add a menu item without icon (convenience)
Definition at line 88 of file menu_builder.cc.
References Item().
Separator()
MenuBuilder & yaze::editor::MenuBuilder::Separator ()
Add a separator.
Definition at line 93 of file menu_builder.cc.
References current_menu_, yaze::editor::MenuBuilder::Menu::items, yaze::editor::MenuBuilder::MenuItem::kSeparator, and yaze::editor::MenuBuilder::MenuItem::type.
Referenced by yaze::editor::EditorManager::BuildModernMenu().
DisabledItem()
MenuBuilder & yaze::editor::MenuBuilder::DisabledItem (const char * label, const char * icon = nullptr)
Add a disabled item (grayed out)
Definition at line 102 of file menu_builder.cc.
References current_menu_, yaze::editor::MenuBuilder::MenuItem::icon, yaze::editor::MenuBuilder::Menu::items, yaze::editor::MenuBuilder::MenuItem::kDisabled, yaze::editor::MenuBuilder::MenuItem::label, and yaze::editor::MenuBuilder::MenuItem::type.
Draw()
void yaze::editor::MenuBuilder::Draw ()
Draw the menu bar (call in main menu bar)
Definition at line 115 of file menu_builder.cc.
References DrawMenuItem(), menus_, skip_depth_, and submenu_stack_.
Referenced by yaze::editor::EditorManager::BuildModernMenu().
Clear()
void yaze::editor::MenuBuilder::Clear ()
Clear all menus.
Definition at line 226 of file menu_builder.cc.
References current_menu_, and menus_.
Referenced by yaze::editor::EditorManager::BuildModernMenu().
DrawMenuItem()
void yaze::editor::MenuBuilder::DrawMenuItem (const MenuItem & item) private
Definition at line 131 of file menu_builder.cc.
References yaze::editor::MenuBuilder::MenuItem::callback, yaze::editor::MenuBuilder::MenuItem::checked, yaze::editor::MenuBuilder::MenuItem::enabled, yaze::editor::MenuBuilder::MenuItem::icon, yaze::editor::MenuBuilder::MenuItem::kDisabled, yaze::editor::MenuBuilder::MenuItem::kItem, yaze::editor::MenuBuilder::MenuItem::kSeparator, yaze::editor::MenuBuilder::MenuItem::kSubMenuBegin, yaze::editor::MenuBuilder::MenuItem::kSubMenuEnd, yaze::editor::MenuBuilder::MenuItem::label, yaze::editor::MenuBuilder::MenuItem::shortcut, skip_depth_, submenu_stack_, and yaze::editor::MenuBuilder::MenuItem::type.
Referenced by Draw().
Member Data Documentation
menus_
std::vector<Menu> yaze::editor::MenuBuilder::menus_ private
Definition at line 110 of file menu_builder.h.
Referenced by BeginMenu(), Clear(), and Draw().
current_menu_
Menu* yaze::editor::MenuBuilder::current_menu_ = nullptr private
Definition at line 111 of file menu_builder.h.
Referenced by BeginMenu(), BeginSubMenu(), Clear(), DisabledItem(), EndMenu(), Item(), and Separator().
submenu_stack_
std::vector<bool> yaze::editor::MenuBuilder::submenu_stack_ mutable private
Definition at line 114 of file menu_builder.h.
Referenced by Draw(), and DrawMenuItem().
skip_depth_
int yaze::editor::MenuBuilder::skip_depth_ = 0 mutable private
Definition at line 115 of file menu_builder.h.
Referenced by Draw(), and DrawMenuItem().
The documentation for this class was generated from the following files:
src/app/editor/ui/menu_builder.h
src/app/editor/ui/menu_builder.cc