yaze: yaze::editor Namespace Reference
yaze::editor Namespace Reference
Editors are the view controllers for the application.
Namespaces
namespace anonymous_namespace{assembly_editor.cc}
namespace anonymous_namespace{editor_manager.cc}
namespace anonymous_namespace{gfx_group_editor.cc}
namespace anonymous_namespace{message_editor.cc}
namespace anonymous_namespace{palette_editor.cc}
namespace anonymous_namespace{shortcut_manager.cc}
namespace palette_internal
namespace test
namespace zsprite
Namespace for the ZSprite format from Zarby's ZSpriteMaker.
Classes
class AgentChatWidget
class AssemblyEditor
Text editor for modifying assembly code.
class CommandManager
struct DictionaryEntry
class DungeonCanvasViewer
Handles the main dungeon canvas rendering and interaction.
class DungeonEditor
DungeonEditor class for editing dungeons.
class DungeonObjectInteraction
Handles object selection, placement, and interaction within the dungeon canvas.
class DungeonObjectSelector
Handles object selection, preview, and editing UI.
class DungeonRenderer
Handles rendering of dungeon objects, layouts, and backgrounds.
class DungeonRoomLoader
Manages loading and saving of dungeon room data.
class DungeonRoomSelector
Handles room and entrance selection UI.
class DungeonToolset
Handles the dungeon editor toolset UI.
class DungeonUsageTracker
Tracks and analyzes usage statistics for dungeon resources.
class Editor
Interface for editor classes.
struct EditorContext
class EditorManager
The EditorManager controls the main editor window and manages the various editor classes.
class EditorSet
Contains a complete set of editors for a single ROM instance.
struct ExampleAppPropertyEditor
struct ExampleMemberInfo
struct ExampleTreeNode
class ExtensionManager
struct FolderItem
class GfxGroupEditor
Manage graphics group configurations in a Rom.
class GraphicsEditor
Allows the user to edit graphics sheets from the game or view prototype graphics.
class HistoryManager
class MapPropertiesSystem
struct MemoryEditorWithDiffChecker
struct MessageData
class MessageEditor
struct MessagePreview
class MusicEditor
A class for editing music data in a Rom.
class OverworldEditor
Manipulates the Overworld and OverworldMap data in a Rom.
class OverworldEditorManager
Manages the complex overworld editor functionality and v3 features.
class PaletteEditor
Allows the user to view and edit in game palettes.
struct ParsedElement
class PopupManager
struct PopupParams
class ProposalDrawer
ImGui drawer for displaying and managing agent proposals.
class ScreenEditor
The ScreenEditor class allows the user to edit a variety of screens in the game or create a custom menu.
class SettingsEditor
struct Shortcut
class ShortcutManager
class SpriteEditor
Allows the user to edit sprites.
struct SpriteItem
struct TextElement
class Tile16Editor
Popup window to edit Tile16 data.
struct Toast
class ToastManager
Enumerations
enum class EditorType {
kAssembly , kDungeon , kGraphics , kMusic ,
kOverworld , kPalette , kScreen , kSprite ,
kMessage , kSettings
}
enum SpriteItemColumnID { SpriteItemColumnID_ID , SpriteItemColumnID_Name , SpriteItemColumnID_Description }
Column IDs for the sprite table.
enum class ToastType { kInfo , kSuccess , kWarning , kError }
Functions
std::string GetRomStatusMessage (const Rom *rom)
bool IsRomReadyForEditing (const Rom *rom)
absl::Status DisplayPalette (gfx::SnesPalette &palette, bool loaded)
Display SNES palette with enhanced ROM hacking features.
uint8_t FindMatchingCharacter (char value)
int8_t FindDictionaryEntry (uint8_t value)
std::optional< TextElement > FindMatchingCommand (uint8_t b)
std::optional< TextElement > FindMatchingSpecial (uint8_t value)
ParsedElement FindMatchingElement (const std::string &str)
std::string ParseTextDataByte (uint8_t value)
std::vector< uint8_t > ParseMessageToData (std::string str)
std::vector< DictionaryEntry > BuildDictionaryEntries (Rom *rom)
std::string ReplaceAllDictionaryWords (std::string str, std::vector< DictionaryEntry > dictionary)
DictionaryEntry FindRealDictionaryEntry (uint8_t value, std::vector< DictionaryEntry > dictionary)
absl::StatusOr< MessageData > ParseSingleMessage (const std::vector< uint8_t > &rom_data, int *current_pos)
std::vector< std::string > ParseMessageData (std::vector< MessageData > &message_data, const std::vector< DictionaryEntry > &dictionary_entries)
std::vector< MessageData > ReadAllTextData (uint8_t *rom, int pos)
absl::Status LoadExpandedMessages (std::string &expanded_message_path, std::vector< std::string > &parsed_messages, std::vector< MessageData > &expanded_messages, std::vector< DictionaryEntry > &dictionary)
bool IsMouseHoveringOverEntity (const zelda3::GameEntity &entity, ImVec2 canvas_p0, ImVec2 scrolling)
void MoveEntityOnGrid (zelda3::GameEntity *entity, ImVec2 canvas_p0, ImVec2 scrolling, bool free_movement)
void HandleEntityDragging (zelda3::GameEntity *entity, ImVec2 canvas_p0, ImVec2 scrolling, bool &is_dragging_entity, zelda3::GameEntity *&dragged_entity, zelda3::GameEntity *&current_entity, bool free_movement)
bool DrawEntranceInserterPopup ()
bool DrawOverworldEntrancePopup (zelda3::OverworldEntrance &entrance)
void DrawExitInserterPopup ()
bool DrawExitEditorPopup (zelda3::OverworldExit &exit)
void DrawItemInsertPopup ()
bool DrawItemEditorPopup (zelda3::OverworldItem &item)
void DrawSpriteTable (std::function< void(int)> onSpriteSelect)
void DrawSpriteInserterPopup ()
bool DrawSpriteEditorPopup (zelda3::Sprite &sprite)
constexpr ImVec2 kOverworldCanvasSize (kOverworldMapSize *8, kOverworldMapSize *8)
constexpr ImVec2 kCurrentGfxCanvasSize (0x100+1, 0x10 *0x40+1)
constexpr ImVec2 kBlocksetCanvasSize (0x100+1, 0x4000+1)
constexpr ImVec2 kGraphicsBinCanvasSize (0x100+1, kNumSheetsToLoad *0x40+1)
std::string PrintShortcut (const std::vector< ImGuiKey > &keys)
std::vector< ImGuiKey > ParseShortcut (const std::string &shortcut)
void ExecuteShortcuts (const ShortcutManager &shortcut_manager)
Variables
constexpr ImGuiTableFlags kDungeonObjectTableFlags
constexpr ImGuiTabItemFlags kDungeonTabFlags
constexpr ImGuiTabBarFlags kDungeonTabBarFlags
constexpr ImGuiTableFlags kDungeonTableFlags
constexpr std::array< const char *, 10 > kEditorNames
constexpr const char * kOverworldEditorName = ICON_MD_LAYERS " Overworld Editor"
constexpr const char * kGraphicsEditorName = ICON_MD_PHOTO " Graphics Editor"
constexpr const char * kPaletteEditorName = ICON_MD_PALETTE " Palette Editor"
constexpr const char * kScreenEditorName = ICON_MD_SCREENSHOT " Screen Editor"
constexpr const char * kSpriteEditorName = ICON_MD_SMART_TOY " Sprite Editor"
constexpr const char * kMessageEditorName = ICON_MD_MESSAGE " Message Editor"
constexpr const char * kSettingsEditorName = ICON_MD_SETTINGS " Settings Editor"
constexpr const char * kAssemblyEditorName = ICON_MD_CODE " Assembly Editor"
constexpr const char * kDungeonEditorName = ICON_MD_CASTLE " Dungeon Editor"
constexpr const char * kMusicEditorName = ICON_MD_MUSIC_NOTE " Music Editor"
constexpr ImGuiTableFlags kGfxEditTableFlags
const std::string kSuperDonkeyTiles []
const std::string kSuperDonkeySprites []
constexpr ImGuiTableFlags kPaletteTableFlags
constexpr ImGuiColorEditFlags kPalNoAlpha = ImGuiColorEditFlags_NoAlpha
constexpr ImGuiColorEditFlags kPalButtonFlags
constexpr ImGuiColorEditFlags kColorPopupFlags
constexpr uint32_t kRedPen = 0xFF0000FF
const std::string kBankToken = "BANK"
const std::string DICTIONARYTOKEN = "D"
constexpr uint8_t kMessageTerminator = 0x7F
constexpr uint8_t DICTOFF = 0x88
constexpr uint8_t kWidthArraySize = 100
constexpr int kTextData = 0xE0000
constexpr int kTextDataEnd = 0xE7FFF
constexpr int kNumDictionaryEntries = 0x61
constexpr int kPointersDictionaries = 0x74703
constexpr uint8_t kScrollVertical = 0x73
constexpr uint8_t kLine1 = 0x74
constexpr uint8_t kLine2 = 0x75
constexpr uint8_t kLine3 = 0x76
const std::string CHEESE = "\uBEBE"
constexpr int kTextData2 = 0x75F40
constexpr int kTextData2End = 0x773FF
constexpr ImGuiTableFlags kMessageTableFlags
constexpr int kGfxFont = 0x70000
constexpr int kCharactersWidth = 0x74ADF
constexpr int kNumMessages = 396
constexpr int kFontGfxMessageSize = 128
constexpr int kFontGfxMessageDepth = 64
constexpr int kFontGfx16Size = 172 * 4096
constexpr uint8_t kBlockTerminator = 0x80
constexpr uint8_t kMessageBankChangeId = 0x80
constexpr int kCurrentMessageWidth = 172
constexpr int kCurrentMessageHeight = 4096
const ImGuiTableFlags toolset_table_flags_ = ImGuiTableFlags_SizingFixedFit
const ImGuiTableFlags music_editor_flags_
constexpr float kInputFieldSize = 30.f
constexpr std::array< const char *, 6 > kVanillaMapSettingsColumnNames
constexpr std::array< const char *, 7 > kV2MapSettingsColumnNames
constexpr std::array< const char *, 9 > kV3MapSettingsColumnNames
constexpr unsigned int k4BPP = 4
constexpr unsigned int kByteSize = 3
constexpr unsigned int kMessageIdSize = 5
constexpr unsigned int kNumSheetsToLoad = 223
constexpr unsigned int kOverworldMapSize = 0x200
constexpr ImGuiTableFlags kOWMapFlags
constexpr ImGuiTableFlags kToolsetTableFlags = ImGuiTableFlags_SizingFixedFit
constexpr ImGuiTableFlags kOWEditFlags
constexpr absl::string_view kWorldList
constexpr absl::string_view kGamePartComboString = "Part 0\0Part 1\0Part 2\0"
constexpr absl::string_view kTileSelectorTab = "##TileSelectorTabBar"
constexpr absl::string_view kOWEditTable = "##OWEditTable"
constexpr absl::string_view kOWMapTable = "#MapSettingsTable"
constexpr int kTile16Size = 16
constexpr int kTile8Size = 8
constexpr int kTilesheetEditorWidth = 0x100
constexpr int kTilesheetEditorHeight = 0x4000
constexpr int kTile16CanvasSize = 0x20
constexpr int kTile8CanvasHeight = 0x175
constexpr int kNumScratchSlots = 4
constexpr int kNumPalettes = 8
constexpr int kTile8PixelCount = 64
constexpr int kTile16PixelCount = 256
constexpr const char * kGameStateNames []
constexpr const char * kWorldNames []
constexpr const char * kAreaSizeNames []
constexpr float kHexByteInputWidth = 50.f
constexpr float kHexWordInputWidth = 70.f
constexpr float kCompactButtonWidth = 60.f
constexpr float kIconButtonWidth = 30.f
constexpr float kSmallButtonWidth = 80.f
constexpr float kMediumButtonWidth = 90.f
constexpr float kLargeButtonWidth = 100.f
constexpr float kTableColumnWorld = 120.f
constexpr float kTableColumnMap = 80.f
constexpr float kTableColumnAreaSize = 120.f
constexpr float kTableColumnLock = 50.f
constexpr float kTableColumnGraphics = 80.f
constexpr float kTableColumnPalettes = 80.f
constexpr float kTableColumnProperties = 100.f
constexpr float kTableColumnTools = 80.f
constexpr float kTableColumnView = 80.f
constexpr float kTableColumnQuick = 80.f
constexpr float kComboWorldWidth = 115.f
constexpr float kComboAreaSizeWidth = 115.f
constexpr float kComboGameStateWidth = 100.f
constexpr float kTableButtonGraphics = 75.f
constexpr float kTableButtonPalettes = 75.f
constexpr float kTableButtonProperties = 95.f
constexpr float kTableButtonTools = 75.f
constexpr float kTableButtonView = 75.f
constexpr float kTableButtonQuick = 75.f
constexpr float kCompactItemSpacing = 4.f
constexpr float kCompactFramePadding = 2.f
constexpr ImGuiTabItemFlags kSpriteTabFlags
constexpr ImGuiTabBarFlags kSpriteTabBarFlags
constexpr ImGuiTableFlags kSpriteTableFlags
Detailed Description
Editors are the view controllers for the application.
Enumeration Type Documentation
EditorType
enum class yaze::editor::EditorType strong
Enumerator
kAssembly
kDungeon
kGraphics
kMusic
kOverworld
kPalette
kScreen
kSprite
kMessage
kSettings
Definition at line 48 of file editor.h.
SpriteItemColumnID
enum yaze::editor::SpriteItemColumnID
Column IDs for the sprite table.
Enumerator
SpriteItemColumnID_ID
SpriteItemColumnID_Name
SpriteItemColumnID_Description
Definition at line 40 of file entity.h.
ToastType
enum class yaze::editor::ToastType strong
Enumerator
kInfo
kSuccess
kWarning
kError
Definition at line 12 of file toast_manager.h.
Function Documentation
GetRomStatusMessage()
std::string yaze::editor::GetRomStatusMessage (const Rom * rom) inline
Definition at line 29 of file editor_safeguards.h.
References yaze::Rom::is_loaded(), and yaze::Rom::title().
IsRomReadyForEditing()
bool yaze::editor::IsRomReadyForEditing (const Rom * rom) inline
Definition at line 36 of file editor_safeguards.h.
References yaze::Rom::is_loaded(), and yaze::Rom::title().
DisplayPalette()
absl::Status yaze::editor::DisplayPalette (gfx::SnesPalette & palette, bool loaded)
Display SNES palette with enhanced ROM hacking features.
Parameters
palette SNES palette to display
loaded Whether the palette has been loaded from ROM
Enhanced Features:
Real-time color preview with SNES format conversion
Drag-and-drop color swapping for palette editing
Color picker integration with ROM palette system
Undo/redo support for palette modifications
Export functionality for palette sharing
Performance Notes:
Static color arrays to avoid repeated allocations
Cached color conversions for fast rendering
Batch palette updates to minimize ROM writes
Definition at line 102 of file palette_editor.cc.
References kPalButtonFlags, yaze::gfx::SnesPalette::size(), and TEXT_WITH_SEPARATOR.
FindMatchingCharacter()
uint8_t yaze::editor::FindMatchingCharacter (char value)
Definition at line 13 of file message_data.cc.
Referenced by yaze::editor::MessagePreview::DrawCharacterToPreview(), ParseMessageToData(), yaze::test::TEST_F(), and yaze::test::TEST_F().
FindDictionaryEntry()
int8_t yaze::editor::FindDictionaryEntry (uint8_t value)
Definition at line 22 of file message_data.cc.
References DICTOFF.
Referenced by ParseSingleMessage(), ParseTextDataByte(), ReadAllTextData(), yaze::test::TEST_F(), and yaze::test::TEST_F().
FindMatchingCommand()
std::optional< TextElement > yaze::editor::FindMatchingCommand (uint8_t b)
Definition at line 29 of file message_data.cc.
Referenced by ParseMessageData(), ParseSingleMessage(), ParseTextDataByte(), and ReadAllTextData().
FindMatchingSpecial()
std::optional< TextElement > yaze::editor::FindMatchingSpecial (uint8_t value)
Definition at line 38 of file message_data.cc.
References yaze::editor::TextElement::ID.
Referenced by ParseMessageData(), ParseTextDataByte(), and ReadAllTextData().
FindMatchingElement()
ParsedElement yaze::editor::FindMatchingElement (const std::string & str)
Definition at line 49 of file message_data.cc.
References DICTIONARYTOKEN, and DICTOFF.
Referenced by ParseMessageToData(), yaze::test::TEST_F(), and yaze::test::TEST_F().
ParseTextDataByte()
std::string yaze::editor::ParseTextDataByte (uint8_t value)
Definition at line 77 of file message_data.cc.
References DICTIONARYTOKEN, FindDictionaryEntry(), FindMatchingCommand(), and FindMatchingSpecial().
Referenced by BuildDictionaryEntries(), ParseSingleMessage(), ReadAllTextData(), yaze::test::TEST_F(), and yaze::test::TEST_F().
ParseMessageToData()
std::vector< uint8_t > yaze::editor::ParseMessageToData (std::string str)
Definition at line 106 of file message_data.cc.
References yaze::editor::ParsedElement::Active, DICTIONARYTOKEN, FindMatchingCharacter(), FindMatchingElement(), yaze::editor::TextElement::HasArgument, yaze::editor::TextElement::ID, yaze::editor::ParsedElement::Parent, and yaze::editor::ParsedElement::Value.
Referenced by yaze::editor::DictionaryEntry::DictionaryEntry(), yaze::editor::MessageEditor::DrawCurrentMessage(), and yaze::test::TEST_F().
BuildDictionaryEntries()
std::vector< DictionaryEntry > yaze::editor::BuildDictionaryEntries (Rom * rom)
Definition at line 151 of file message_data.cc.
References yaze::editor::DictionaryEntry::Contents, yaze::Rom::data(), kNumDictionaryEntries, kPointersDictionaries, kTextData, ParseTextDataByte(), and yaze::SnesToPc().
Referenced by yaze::editor::MessageEditor::Initialize(), yaze::test::MessageRomTest::SetUp(), and yaze::test::TEST_F().
ReplaceAllDictionaryWords()
std::string yaze::editor::ReplaceAllDictionaryWords (std::string str, std::vector< DictionaryEntry > dictionary)
Definition at line 183 of file message_data.cc.
Referenced by yaze::editor::MessageData::OptimizeMessageForDictionary(), yaze::test::TEST_F(), and yaze::test::TEST_F().
FindRealDictionaryEntry()
DictionaryEntry yaze::editor::FindRealDictionaryEntry (uint8_t value, std::vector< DictionaryEntry > dictionary)
Definition at line 194 of file message_data.cc.
References DICTOFF.
Referenced by yaze::editor::MessagePreview::DrawCharacterToPreview().
ParseSingleMessage()
absl::StatusOr< MessageData > yaze::editor::ParseSingleMessage (const std::vector< uint8_t > & rom_data, int * current_pos)
Definition at line 204 of file message_data.cc.
References yaze::editor::MessageData::Address, yaze::editor::MessageData::ContentsParsed, yaze::editor::MessageData::Data, yaze::editor::MessageData::DataParsed, DICTIONARYTOKEN, FindDictionaryEntry(), FindMatchingCommand(), yaze::Get24LocalFromPC(), yaze::util::HexWord(), yaze::editor::MessageData::ID, kMessageTerminator, kPointersDictionaries, ParseTextDataByte(), and yaze::editor::MessageData::RawString.
Referenced by yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), and yaze::test::TEST_F().
ParseMessageData()
std::vector< std::string > yaze::editor::ParseMessageData (std::vector< MessageData > & message_data, const std::vector< DictionaryEntry > & dictionary_entries)
Definition at line 284 of file message_data.cc.
References yaze::editor::DictionaryEntry::Contents, DICTOFF, FindMatchingCommand(), FindMatchingSpecial(), kLine2, kLine3, and kScrollVertical.
Referenced by yaze::editor::MessageEditor::Initialize(), LoadExpandedMessages(), and yaze::test::TEST_F().
ReadAllTextData()
std::vector< MessageData > yaze::editor::ReadAllTextData (uint8_t * rom, int pos)
Definition at line 336 of file message_data.cc.
References DICTIONARYTOKEN, FindDictionaryEntry(), FindMatchingCommand(), FindMatchingSpecial(), yaze::Get24LocalFromPC(), yaze::util::HexByte(), kBankToken, kMessageTerminator, kPointersDictionaries, kTextData2, and ParseTextDataByte().
Referenced by yaze::editor::MessageEditor::Initialize(), LoadExpandedMessages(), and yaze_load_messages().
LoadExpandedMessages()
absl::Status yaze::editor::LoadExpandedMessages (std::string & expanded_message_path, std::vector< std::string > & parsed_messages, std::vector< MessageData > & expanded_messages, std::vector< DictionaryEntry > & dictionary)
Definition at line 423 of file message_data.cc.
References yaze::Rom::LoadFromFile(), yaze::Rom::mutable_data(), ParseMessageData(), and ReadAllTextData().
Referenced by yaze::editor::MessageEditor::DrawExpandedMessageSettings().
IsMouseHoveringOverEntity()
bool yaze::editor::IsMouseHoveringOverEntity (const zelda3::GameEntity & entity, ImVec2 canvas_p0, ImVec2 scrolling)
Definition at line 21 of file entity.cc.
References yaze::zelda3::GameEntity::x_, and yaze::zelda3::GameEntity::y_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldEntrances(), yaze::editor::OverworldEditor::DrawOverworldExits(), yaze::editor::OverworldEditor::DrawOverworldItems(), yaze::editor::OverworldEditor::DrawOverworldSprites(), and HandleEntityDragging().
MoveEntityOnGrid()
void yaze::editor::MoveEntityOnGrid (zelda3::GameEntity * entity, ImVec2 canvas_p0, ImVec2 scrolling, bool free_movement)
Definition at line 36 of file entity.cc.
References yaze::zelda3::GameEntity::set_x(), and yaze::zelda3::GameEntity::set_y().
Referenced by HandleEntityDragging().
HandleEntityDragging()
void yaze::editor::HandleEntityDragging (zelda3::GameEntity * entity, ImVec2 canvas_p0, ImVec2 scrolling, bool & is_dragging_entity, zelda3::GameEntity *& dragged_entity, zelda3::GameEntity *& current_entity, bool free_movement)
Definition at line 56 of file entity.cc.
References yaze::zelda3::GameEntity::entity_id_, yaze::zelda3::GameEntity::entity_type_, yaze::util::HexByte(), IsMouseHoveringOverEntity(), yaze::zelda3::GameEntity::kEntrance, yaze::zelda3::GameEntity::kExit, yaze::zelda3::GameEntity::kItem, yaze::zelda3::GameEntity::kSprite, yaze::zelda3::GameEntity::map_id_, MoveEntityOnGrid(), yaze::zelda3::GameEntity::UpdateMapProperties(), yaze::zelda3::GameEntity::x_, and yaze::zelda3::GameEntity::y_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldEntrances(), yaze::editor::OverworldEditor::DrawOverworldExits(), yaze::editor::OverworldEditor::DrawOverworldItems(), and yaze::editor::OverworldEditor::DrawOverworldSprites().
DrawEntranceInserterPopup()
bool yaze::editor::DrawEntranceInserterPopup ()
Definition at line 105 of file entity.cc.
References ICON_MD_CANCEL, ICON_MD_DONE, and yaze::gui::InputHex().
Referenced by yaze::editor::OverworldEditor::DrawOverworldEntrances().
DrawOverworldEntrancePopup()
bool yaze::editor::DrawOverworldEntrancePopup (zelda3::OverworldEntrance & entrance)
Definition at line 129 of file entity.cc.
References yaze::zelda3::OverworldEntrance::deleted, yaze::zelda3::OverworldEntrance::entrance_id_, yaze::gui::InputHex(), yaze::gui::InputHexByte(), yaze::gui::InputHexWord(), yaze::zelda3::OverworldEntrance::is_hole_, kInputFieldSize, yaze::zelda3::GameEntity::map_id_, yaze::zelda3::GameEntity::x_, and yaze::zelda3::GameEntity::y_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldEntrances().
DrawExitInserterPopup()
void yaze::editor::DrawExitInserterPopup ()
Definition at line 171 of file entity.cc.
References yaze::gui::InputHex().
Referenced by yaze::editor::OverworldEditor::DrawOverworldExits().
DrawExitEditorPopup()
bool yaze::editor::DrawExitEditorPopup (zelda3::OverworldExit & exit)
Definition at line 200 of file entity.cc.
References yaze::zelda3::OverworldExit::deleted_, yaze::zelda3::OverworldExit::door_type_1_, yaze::zelda3::OverworldExit::door_type_2_, yaze::zelda3::GameEntity::entity_id_, ICON_MD_CANCEL, ICON_MD_DELETE, ICON_MD_DONE, yaze::gui::InputHex(), yaze::gui::InputHexByte(), yaze::gui::InputHexWord(), yaze::zelda3::OverworldExit::is_automatic_, yaze::zelda3::OverworldExit::is_hole_, yaze::zelda3::OverworldExit::large_map_, yaze::zelda3::GameEntity::map_id_, yaze::zelda3::OverworldExit::room_id_, yaze::gui::TextWithSeparators(), yaze::zelda3::GameEntity::x_, yaze::zelda3::OverworldExit::x_camera_, yaze::zelda3::OverworldExit::x_scroll_, yaze::zelda3::GameEntity::y_, yaze::zelda3::OverworldExit::y_camera_, and yaze::zelda3::OverworldExit::y_scroll_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldExits().
DrawItemInsertPopup()
void yaze::editor::DrawItemInsertPopup ()
Definition at line 332 of file entity.cc.
References ICON_MD_CANCEL, ICON_MD_DONE, and yaze::zelda3::kSecretItemNames.
Referenced by yaze::editor::OverworldEditor::DrawOverworldItems().
DrawItemEditorPopup()
bool yaze::editor::DrawItemEditorPopup (zelda3::OverworldItem & item)
Todo:
Implement deleting OverworldItem objects, currently only hides them
Definition at line 362 of file entity.cc.
References yaze::zelda3::OverworldItem::deleted, ICON_MD_CLOSE, ICON_MD_DELETE, ICON_MD_DONE, yaze::zelda3::OverworldItem::id_, and yaze::zelda3::kSecretItemNames.
Referenced by yaze::editor::OverworldEditor::DrawOverworldItems().
DrawSpriteTable()
void yaze::editor::DrawSpriteTable (std::function< void(int)> onSpriteSelect)
Definition at line 399 of file entity.cc.
References yaze::editor::SpriteItem::SortWithSortSpecs(), SpriteItemColumnID_ID, and SpriteItemColumnID_Name.
Referenced by DrawSpriteEditorPopup(), and DrawSpriteInserterPopup().
DrawSpriteInserterPopup()
void yaze::editor::DrawSpriteInserterPopup ()
Definition at line 447 of file entity.cc.
References DrawSpriteTable(), and yaze::gui::InputHex().
Referenced by yaze::editor::OverworldEditor::DrawOverworldSprites().
DrawSpriteEditorPopup()
bool yaze::editor::DrawSpriteEditorPopup (zelda3::Sprite & sprite)
Definition at line 483 of file entity.cc.
References DrawSpriteTable(), ICON_MD_CLOSE, ICON_MD_DELETE, ICON_MD_DONE, yaze::zelda3::Sprite::map_id(), yaze::zelda3::Sprite::name(), yaze::zelda3::Sprite::set_deleted(), yaze::zelda3::Sprite::set_id(), and yaze::zelda3::Sprite::UpdateMapProperties().
Referenced by yaze::editor::OverworldEditor::DrawOverworldSprites().
kOverworldCanvasSize()
constexpr ImVec2 yaze::editor::kOverworldCanvasSize (kOverworldMapSize * 8, kOverworldMapSize * 8) constexpr
kCurrentGfxCanvasSize()
constexpr ImVec2 yaze::editor::kCurrentGfxCanvasSize (0x100+ 1, 0x10 *0x40+ 1) constexpr
kBlocksetCanvasSize()
constexpr ImVec2 yaze::editor::kBlocksetCanvasSize (0x100+ 1, 0x4000+ 1) constexpr
kGraphicsBinCanvasSize()
constexpr ImVec2 yaze::editor::kGraphicsBinCanvasSize (0x100+ 1, kNumSheetsToLoad *0x40+ 1) constexpr
PrintShortcut()
std::string yaze::editor::PrintShortcut (const std::vector< ImGuiKey > & keys)
Definition at line 86 of file shortcut_manager.cc.
Referenced by yaze::editor::SettingsEditor::DrawKeyboardShortcuts(), yaze::editor::EditorManager::DrawMenuBar(), and yaze::editor::ShortcutManager::GetKeys().
ParseShortcut()
std::vector< ImGuiKey > yaze::editor::ParseShortcut (const std::string & shortcut)
Definition at line 102 of file shortcut_manager.cc.
References yaze::gui::MapKeyToImGuiKey().
ExecuteShortcuts()
void yaze::editor::ExecuteShortcuts (const ShortcutManager & shortcut_manager)
Definition at line 140 of file shortcut_manager.cc.
References yaze::editor::ShortcutManager::GetShortcuts().
Referenced by yaze::editor::EditorManager::Update().
Variable Documentation
kDungeonObjectTableFlags
constexpr ImGuiTableFlags yaze::editor::kDungeonObjectTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 36 of file dungeon_editor.cc.
kDungeonTabFlags
constexpr ImGuiTabItemFlags yaze::editor::kDungeonTabFlags constexpr
Initial value:
=
    ImGuiTabItemFlags_Trailing | ImGuiTabItemFlags_NoTooltip
Definition at line 29 of file dungeon_editor.h.
Referenced by yaze::editor::DungeonEditor::DrawDungeonTabView().
kDungeonTabBarFlags
constexpr ImGuiTabBarFlags yaze::editor::kDungeonTabBarFlags constexpr
Initial value:
=
    ImGuiTabBarFlags_AutoSelectNewTabs | ImGuiTabBarFlags_Reorderable |
    ImGuiTabBarFlags_FittingPolicyResizeDown |
    ImGuiTabBarFlags_TabListPopupButton
Definition at line 32 of file dungeon_editor.h.
Referenced by yaze::editor::DungeonEditor::DrawDungeonTabView().
kDungeonTableFlags
constexpr ImGuiTableFlags yaze::editor::kDungeonTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 37 of file dungeon_editor.h.
Referenced by yaze::editor::DungeonEditor::UpdateDungeonRoomView().
kEditorNames
constexpr std::array<const char*, 10> yaze::editor::kEditorNames constexpr
Initial value:
= {
    "Assembly", "Dungeon", "Graphics", "Music",   "Overworld",
    "Palette",  "Screen",  "Sprite",   "Message", "Settings",
}
Definition at line 61 of file editor.h.
Referenced by yaze::editor::EditorManager::GenerateUniqueEditorTitle(), and yaze::editor::anonymous_namespace{editor_manager.cc}::GetEditorName().
kOverworldEditorName
constexpr const char* yaze::editor::kOverworldEditorName = ICON_MD_LAYERS " Overworld Editor" constexpr
Definition at line 200 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kGraphicsEditorName
constexpr const char* yaze::editor::kGraphicsEditorName = ICON_MD_PHOTO " Graphics Editor" constexpr
Definition at line 201 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kPaletteEditorName
constexpr const char* yaze::editor::kPaletteEditorName = ICON_MD_PALETTE " Palette Editor" constexpr
Definition at line 202 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kScreenEditorName
constexpr const char* yaze::editor::kScreenEditorName = ICON_MD_SCREENSHOT " Screen Editor" constexpr
Definition at line 203 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kSpriteEditorName
constexpr const char* yaze::editor::kSpriteEditorName = ICON_MD_SMART_TOY " Sprite Editor" constexpr
Definition at line 204 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kMessageEditorName
constexpr const char* yaze::editor::kMessageEditorName = ICON_MD_MESSAGE " Message Editor" constexpr
Definition at line 205 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kSettingsEditorName
constexpr const char* yaze::editor::kSettingsEditorName = ICON_MD_SETTINGS " Settings Editor" constexpr
Definition at line 206 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kAssemblyEditorName
constexpr const char* yaze::editor::kAssemblyEditorName = ICON_MD_CODE " Assembly Editor" constexpr
Definition at line 207 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kDungeonEditorName
constexpr const char* yaze::editor::kDungeonEditorName = ICON_MD_CASTLE " Dungeon Editor" constexpr
Definition at line 208 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kMusicEditorName
constexpr const char* yaze::editor::kMusicEditorName = ICON_MD_MUSIC_NOTE " Music Editor" constexpr
Definition at line 209 of file editor_manager.cc.
Referenced by yaze::editor::EditorManager::Initialize().
kGfxEditTableFlags
constexpr ImGuiTableFlags yaze::editor::kGfxEditTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Borders | ImGuiTableFlags_Resizable |
    ImGuiTableFlags_Reorderable | ImGuiTableFlags_Hideable |
    ImGuiTableFlags_SizingFixedFit
Definition at line 40 of file graphics_editor.cc.
Referenced by yaze::editor::GraphicsEditor::UpdateGfxEdit(), and yaze::editor::GraphicsEditor::UpdateLinkGfxView().
kSuperDonkeyTiles
const std::string yaze::editor::kSuperDonkeyTiles[]
Initial value:
= {
    "97C05", "98219", "9871E", "98C00", "99084", "995AF", "99DE0", "9A27E",
    "9A741", "9AC31", "9B07E", "9B55C", "9B963", "9BB99", "9C009", "9C4B4",
    "9C92B", "9CDD6", "9D2C2", "9E037", "9E527", "9EA56", "9EF65", "9FCD1",
    "A0193", "A059E", "A0B17", "A0FB6", "A14A5", "A1988", "A1E66", "A232B",
    "A27F0", "A2B6E", "A302C", "A3453", "A38CA", "A42BB", "A470C", "A4BA9",
    "A5089", "A5385", "A5742", "A5BCC", "A6017", "A6361", "A66F8"}
Definition at line 23 of file graphics_editor.h.
Referenced by yaze::editor::GraphicsEditor::DecompressSuperDonkey().
kSuperDonkeySprites
const std::string yaze::editor::kSuperDonkeySprites[]
Initial value:
= {
    "A8E5D", "A9435", "A9934", "A9D83", "AA2F1", "AA6D4", "AABE4", "AB127",
    "AB65A", "ABBDD", "AC38D", "AC797", "ACCC8", "AD0AE", "AD245", "AD554",
    "ADAAC", "ADECC", "AE453", "AE9D2", "AEF40", "AF3C9", "AF92E", "AFE9D",
    "B03D2", "B09AC", "B0F0C", "B1430", "B1859", "B1E01", "B229A", "B2854",
    "B2D27", "B31D7", "B3B58", "B40B5", "B45A5", "B4D64", "B5031", "B555F",
    "B5F30", "B6858", "B70DD", "B7526", "B79EC", "B7C83", "B80F7", "B85CC",
    "B8A3F", "B8F97", "B94F2", "B9A20", "B9E9A", "BA3A2", "BA8F6", "BACDC",
    "BB1F9", "BB781", "BBCCA", "BC26D", "BC7D4", "BCBB0", "BD082", "BD5FC",
    "BE115", "BE5C2", "BEB63", "BF0CB", "BF607", "BFA55", "BFD71", "C017D",
    "C0567", "C0981", "C0BA7", "C116D", "C166A", "C1FE0", "C24CE", "C2B19"}
Definition at line 31 of file graphics_editor.h.
Referenced by yaze::editor::GraphicsEditor::DecompressSuperDonkey().
kPaletteTableFlags
constexpr ImGuiTableFlags yaze::editor::kPaletteTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Reorderable | ImGuiTableFlags_Resizable |
    ImGuiTableFlags_SizingStretchSame | ImGuiTableFlags_Hideable
Definition at line 45 of file palette_editor.cc.
Referenced by yaze::editor::PaletteEditor::Update().
kPalNoAlpha
constexpr ImGuiColorEditFlags yaze::editor::kPalNoAlpha = ImGuiColorEditFlags_NoAlpha constexpr
Definition at line 49 of file palette_editor.cc.
kPalButtonFlags
constexpr ImGuiColorEditFlags yaze::editor::kPalButtonFlags constexpr
Initial value:
= ImGuiColorEditFlags_NoAlpha |
                                                ImGuiColorEditFlags_NoPicker |
                                                ImGuiColorEditFlags_NoTooltip
Definition at line 51 of file palette_editor.cc.
Referenced by DisplayPalette().
kColorPopupFlags
constexpr ImGuiColorEditFlags yaze::editor::kColorPopupFlags constexpr
Initial value:
=
    ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_NoAlpha |
    ImGuiColorEditFlags_DisplayRGB | ImGuiColorEditFlags_DisplayHSV |
    ImGuiColorEditFlags_DisplayHex
Definition at line 55 of file palette_editor.cc.
Referenced by yaze::editor::PaletteEditor::DrawCustomPalette(), yaze::editor::PaletteEditor::DrawQuickAccessTab(), and yaze::editor::PaletteEditor::HandleColorPopup().
kRedPen
constexpr uint32_t yaze::editor::kRedPen = 0xFF0000FF constexpr
Definition at line 30 of file screen_editor.cc.
Referenced by yaze::editor::ScreenEditor::DrawDungeonMapScreen().
kBankToken
const std::string yaze::editor::kBankToken = "BANK"
Definition at line 19 of file message_data.h.
Referenced by ReadAllTextData().
DICTIONARYTOKEN
const std::string yaze::editor::DICTIONARYTOKEN = "D"
Definition at line 20 of file message_data.h.
Referenced by yaze::editor::DictionaryEntry::DictionaryEntry(), FindMatchingElement(), ParseMessageToData(), ParseSingleMessage(), ParseTextDataByte(), and ReadAllTextData().
kMessageTerminator
constexpr uint8_t yaze::editor::kMessageTerminator = 0x7F constexpr
Definition at line 21 of file message_data.h.
Referenced by ParseSingleMessage(), ReadAllTextData(), and yaze::editor::MessageEditor::Save().
DICTOFF
constexpr uint8_t yaze::editor::DICTOFF = 0x88 constexpr
Definition at line 22 of file message_data.h.
Referenced by yaze::editor::MessagePreview::DrawCharacterToPreview(), FindDictionaryEntry(), FindMatchingElement(), FindRealDictionaryEntry(), and ParseMessageData().
kWidthArraySize
constexpr uint8_t yaze::editor::kWidthArraySize = 100 constexpr
Definition at line 23 of file message_data.h.
Referenced by yaze::editor::MessageEditor::Initialize(), and yaze::editor::MessageEditor::Save().
kTextData
constexpr int yaze::editor::kTextData = 0xE0000 constexpr
Definition at line 78 of file message_data.h.
Referenced by BuildDictionaryEntries(), yaze::editor::anonymous_namespace{message_editor.cc}::DisplayTextOverflowError(), and yaze::editor::MessageEditor::Save().
kTextDataEnd
constexpr int yaze::editor::kTextDataEnd = 0xE7FFF constexpr
Definition at line 79 of file message_data.h.
Referenced by yaze::editor::anonymous_namespace{message_editor.cc}::DisplayTextOverflowError(), and yaze::editor::MessageEditor::Save().
kNumDictionaryEntries
constexpr int yaze::editor::kNumDictionaryEntries = 0x61 constexpr
Definition at line 80 of file message_data.h.
Referenced by BuildDictionaryEntries(), and yaze::test::TEST_F().
kPointersDictionaries
constexpr int yaze::editor::kPointersDictionaries = 0x74703 constexpr
Definition at line 81 of file message_data.h.
Referenced by BuildDictionaryEntries(), ParseSingleMessage(), and ReadAllTextData().
kScrollVertical
constexpr uint8_t yaze::editor::kScrollVertical = 0x73 constexpr
Definition at line 82 of file message_data.h.
Referenced by yaze::editor::MessagePreview::DrawCharacterToPreview(), and ParseMessageData().
kLine1
constexpr uint8_t yaze::editor::kLine1 = 0x74 constexpr
Definition at line 83 of file message_data.h.
Referenced by yaze::editor::MessagePreview::DrawCharacterToPreview().
kLine2
constexpr uint8_t yaze::editor::kLine2 = 0x75 constexpr
Definition at line 84 of file message_data.h.
Referenced by yaze::editor::MessagePreview::DrawCharacterToPreview(), and ParseMessageData().
kLine3
constexpr uint8_t yaze::editor::kLine3 = 0x76 constexpr
Definition at line 85 of file message_data.h.
Referenced by yaze::editor::MessagePreview::DrawCharacterToPreview(), and ParseMessageData().
CHEESE
const std::string yaze::editor::CHEESE = "\uBEBE"
Definition at line 94 of file message_data.h.
Referenced by yaze::editor::MessageData::OptimizeMessageForDictionary().
kTextData2
constexpr int yaze::editor::kTextData2 = 0x75F40 constexpr
Definition at line 310 of file message_data.h.
Referenced by yaze::editor::anonymous_namespace{message_editor.cc}::DisplayTextOverflowError(), ReadAllTextData(), and yaze::editor::MessageEditor::Save().
kTextData2End
constexpr int yaze::editor::kTextData2End = 0x773FF constexpr
Definition at line 311 of file message_data.h.
Referenced by yaze::editor::anonymous_namespace{message_editor.cc}::DisplayTextOverflowError(), and yaze::editor::MessageEditor::Save().
kMessageTableFlags
constexpr ImGuiTableFlags yaze::editor::kMessageTableFlags constexpr
Initial value:
= ImGuiTableFlags_Hideable |
                                               ImGuiTableFlags_Borders |
                                               ImGuiTableFlags_Resizable
Definition at line 59 of file message_editor.cc.
Referenced by yaze::editor::MessageEditor::DrawDictionary(), yaze::editor::MessageEditor::DrawMessageList(), and yaze::editor::MessageEditor::Update().
kGfxFont
constexpr int yaze::editor::kGfxFont = 0x70000 constexpr
Definition at line 20 of file message_editor.h.
Referenced by yaze::editor::MessageEditor::Initialize().
kCharactersWidth
constexpr int yaze::editor::kCharactersWidth = 0x74ADF constexpr
Definition at line 21 of file message_editor.h.
Referenced by yaze::editor::MessageEditor::Initialize(), and yaze::editor::MessageEditor::Save().
kNumMessages
constexpr int yaze::editor::kNumMessages = 396 constexpr
Definition at line 22 of file message_editor.h.
kFontGfxMessageSize
constexpr int yaze::editor::kFontGfxMessageSize = 128 constexpr
Definition at line 23 of file message_editor.h.
Referenced by yaze::editor::MessageEditor::Initialize().
kFontGfxMessageDepth
constexpr int yaze::editor::kFontGfxMessageDepth = 64 constexpr
Definition at line 24 of file message_editor.h.
Referenced by yaze::editor::MessageEditor::Initialize().
kFontGfx16Size
constexpr int yaze::editor::kFontGfx16Size = 172 * 4096 constexpr
Definition at line 25 of file message_editor.h.
kBlockTerminator
constexpr uint8_t yaze::editor::kBlockTerminator = 0x80 constexpr
Definition at line 27 of file message_editor.h.
Referenced by yaze::editor::MessageEditor::Save().
kMessageBankChangeId
constexpr uint8_t yaze::editor::kMessageBankChangeId = 0x80 constexpr
Definition at line 28 of file message_editor.h.
kCurrentMessageWidth
constexpr int yaze::editor::kCurrentMessageWidth = 172 constexpr
Definition at line 12 of file message_preview.h.
Referenced by yaze::editor::MessageEditor::DrawMessagePreview(), and yaze::editor::MessagePreview::MessagePreview().
kCurrentMessageHeight
constexpr int yaze::editor::kCurrentMessageHeight = 4096 constexpr
Definition at line 13 of file message_preview.h.
Referenced by yaze::editor::MessageEditor::DrawMessagePreview(), and yaze::editor::MessagePreview::MessagePreview().
toolset_table_flags_
const ImGuiTableFlags yaze::editor::toolset_table_flags_ = ImGuiTableFlags_SizingFixedFit
Definition at line 49 of file music_editor.h.
Referenced by yaze::editor::MusicEditor::DrawSongToolset(), and yaze::editor::MusicEditor::DrawToolset().
music_editor_flags_
const ImGuiTableFlags yaze::editor::music_editor_flags_
Initial value:
= ImGuiTableFlags_SizingFixedFit |
                                            ImGuiTableFlags_Resizable |
                                            ImGuiTableFlags_Reorderable
Definition at line 50 of file music_editor.h.
Referenced by yaze::editor::MusicEditor::Update().
kInputFieldSize
constexpr float yaze::editor::kInputFieldSize = 30.f inline constexpr
Definition at line 19 of file entity.cc.
Referenced by yaze::editor::MapPropertiesSystem::DrawBasicPropertiesTab(), yaze::editor::MapPropertiesSystem::DrawCustomFeaturesTab(), yaze::editor::OverworldEditor::DrawCustomOverworldMapSettings(), yaze::editor::MapPropertiesSystem::DrawGraphicsPopup(), yaze::editor::OverworldEditor::DrawMapPropertiesPanel(), yaze::editor::MapPropertiesSystem::DrawMusicTab(), yaze::editor::MapPropertiesSystem::DrawOverlayControls(), yaze::editor::MapPropertiesSystem::DrawOverlayEditor(), DrawOverworldEntrancePopup(), yaze::editor::OverworldEditor::DrawOverworldMapSettings(), yaze::editor::MapPropertiesSystem::DrawSpritePropertiesTab(), and yaze::editor::MapPropertiesSystem::DrawTileGraphicsTab().
kVanillaMapSettingsColumnNames
constexpr std::array<const char*, 6> yaze::editor::kVanillaMapSettingsColumnNames constexpr
Initial value:
= {
    "##WorldId", "##GfxId", "##PalId", "##SprGfxId", "##SprPalId", "##MsgId"}
Definition at line 382 of file overworld_editor.cc.
Referenced by yaze::editor::OverworldEditor::DrawOverworldMapSettings().
kV2MapSettingsColumnNames
constexpr std::array<const char*, 7> yaze::editor::kV2MapSettingsColumnNames constexpr
Initial value:
= {
    "##WorldId",  "##GfxId",    "##PalId", "##MainPalId",
    "##SprGfxId", "##SprPalId", "##MsgId"}
Definition at line 385 of file overworld_editor.cc.
Referenced by yaze::editor::OverworldEditor::DrawOverworldMapSettings().
kV3MapSettingsColumnNames
constexpr std::array<const char*, 9> yaze::editor::kV3MapSettingsColumnNames constexpr
Initial value:
= {
    "##WorldId",  "##GfxId", "##PalId",   "##MainPalId", "##SprGfxId",
    "##SprPalId", "##MsgId", "##AnimGfx", "##AreaSize"}
Definition at line 389 of file overworld_editor.cc.
Referenced by yaze::editor::OverworldEditor::DrawCustomOverworldMapSettings(), and yaze::editor::OverworldEditor::DrawOverworldMapSettings().
k4BPP
constexpr unsigned int yaze::editor::k4BPP = 4 constexpr
Definition at line 25 of file overworld_editor.h.
kByteSize
constexpr unsigned int yaze::editor::kByteSize = 3 constexpr
Definition at line 26 of file overworld_editor.h.
kMessageIdSize
constexpr unsigned int yaze::editor::kMessageIdSize = 5 constexpr
Definition at line 27 of file overworld_editor.h.
kNumSheetsToLoad
constexpr unsigned int yaze::editor::kNumSheetsToLoad = 223 constexpr
Definition at line 28 of file overworld_editor.h.
kOverworldMapSize
constexpr unsigned int yaze::editor::kOverworldMapSize = 0x200 constexpr
Definition at line 29 of file overworld_editor.h.
Referenced by yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::MapPropertiesSystem::DrawOverlayPreviewOnMap(), yaze::editor::OverworldEditor::DrawOverworldContextMenu(), yaze::editor::OverworldEditor::DrawOverworldEdits(), yaze::editor::OverworldEditor::DrawOverworldMaps(), yaze::editor::OverworldEditor::EnsureMapTexture(), yaze::editor::OverworldEditor::HandleMapInteraction(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldEditor::Paste(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), and yaze::editor::OverworldEditor::SetupOverworldCanvasContextMenu().
kOWMapFlags
constexpr ImGuiTableFlags yaze::editor::kOWMapFlags constexpr
Initial value:
=
    ImGuiTableFlags_Borders | ImGuiTableFlags_Resizable |
    ImGuiTableFlags_RowBg | ImGuiTableFlags_SizingStretchProp
Definition at line 36 of file overworld_editor.h.
Referenced by yaze::editor::OverworldEditor::DrawCustomOverworldMapSettings(), and yaze::editor::OverworldEditor::DrawOverworldMapSettings().
kToolsetTableFlags
constexpr ImGuiTableFlags yaze::editor::kToolsetTableFlags = ImGuiTableFlags_SizingFixedFit constexpr
Definition at line 39 of file overworld_editor.h.
kOWEditFlags
constexpr ImGuiTableFlags yaze::editor::kOWEditFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 40 of file overworld_editor.h.
Referenced by yaze::editor::OverworldEditor::UpdateUsageStats().
kWorldList
constexpr absl::string_view yaze::editor::kWorldList constexpr
Initial value:
=
    "Light World\0Dark World\0Extra World\0"
Definition at line 53 of file overworld_editor.h.
Referenced by yaze::editor::OverworldEditor::DrawCustomOverworldMapSettings(), yaze::editor::OverworldEditor::DrawMapPropertiesPanel(), and yaze::editor::OverworldEditor::DrawOverworldMapSettings().
kGamePartComboString
constexpr absl::string_view yaze::editor::kGamePartComboString = "Part 0\0Part 1\0Part 2\0" constexpr
Definition at line 56 of file overworld_editor.h.
Referenced by yaze::editor::OverworldEditor::DrawCustomOverworldMapSettings(), yaze::editor::OverworldEditor::DrawMapPropertiesPanel(), and yaze::editor::OverworldEditor::DrawOverworldMapSettings().
kTileSelectorTab
constexpr absl::string_view yaze::editor::kTileSelectorTab = "##TileSelectorTabBar" constexpr
Definition at line 58 of file overworld_editor.h.
Referenced by yaze::editor::OverworldEditor::DrawTileSelector().
kOWEditTable
constexpr absl::string_view yaze::editor::kOWEditTable = "##OWEditTable" constexpr
Definition at line 59 of file overworld_editor.h.
kOWMapTable
constexpr absl::string_view yaze::editor::kOWMapTable = "#MapSettingsTable" constexpr
Definition at line 60 of file overworld_editor.h.
Referenced by yaze::editor::OverworldEditor::DrawCustomOverworldMapSettings(), and yaze::editor::OverworldEditor::DrawOverworldMapSettings().
kTile16Size
constexpr int yaze::editor::kTile16Size = 16 constexpr
Definition at line 25 of file tile16_editor.h.
Referenced by yaze::editor::OverworldEditor::CheckForOverworldEdits(), yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::editor::OverworldEditor::DrawOverworldSprites(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::editor::Tile16Editor::Initialize(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldEditor::Paste(), yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), and yaze::editor::Tile16Editor::UpdateOverworldTilemap().
kTile8Size
constexpr int yaze::editor::kTile8Size = 8 constexpr
Definition at line 26 of file tile16_editor.h.
Referenced by yaze::editor::Tile16Editor::DrawToCurrentTile16(), and yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM().
kTilesheetEditorWidth
constexpr int yaze::editor::kTilesheetEditorWidth = 0x100 constexpr
Definition at line 27 of file tile16_editor.h.
kTilesheetEditorHeight
constexpr int yaze::editor::kTilesheetEditorHeight = 0x4000 constexpr
Definition at line 28 of file tile16_editor.h.
kTile16CanvasSize
constexpr int yaze::editor::kTile16CanvasSize = 0x20 constexpr
Definition at line 29 of file tile16_editor.h.
kTile8CanvasHeight
constexpr int yaze::editor::kTile8CanvasHeight = 0x175 constexpr
Definition at line 30 of file tile16_editor.h.
kNumScratchSlots
constexpr int yaze::editor::kNumScratchSlots = 4 constexpr
Definition at line 31 of file tile16_editor.h.
kNumPalettes
constexpr int yaze::editor::kNumPalettes = 8 constexpr
Definition at line 32 of file tile16_editor.h.
Referenced by yaze::editor::PaletteEditor::Load(), and yaze::editor::PaletteEditor::Update().
kTile8PixelCount
constexpr int yaze::editor::kTile8PixelCount = 64 constexpr
Definition at line 33 of file tile16_editor.h.
kTile16PixelCount
constexpr int yaze::editor::kTile16PixelCount = 256 constexpr
Definition at line 34 of file tile16_editor.h.
Referenced by yaze::editor::Tile16Editor::Initialize(), yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM(), and yaze::editor::Tile16Editor::SetCurrentTile().
kGameStateNames
constexpr const char* yaze::editor::kGameStateNames[] inline constexpr
Initial value:
= {
    "Rain & Rescue Zelda",
    "Pendants",
    "Crystals"
}
Definition at line 8 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawGraphicsPopup(), yaze::editor::MapPropertiesSystem::DrawPalettesPopup(), yaze::editor::MapPropertiesSystem::DrawPropertiesPopup(), and yaze::editor::MapPropertiesSystem::DrawSpritePropertiesTab().
kWorldNames
constexpr const char* yaze::editor::kWorldNames[] inline constexpr
Initial value:
= {
    "Light World",
    "Dark World",
    "Special World"
}
Definition at line 15 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kAreaSizeNames
constexpr const char* yaze::editor::kAreaSizeNames[] inline constexpr
Initial value:
= {
    "Small (1x1)",
    "Large (2x2)",
    "Wide (2x1)",
    "Tall (1x2)"
}
Definition at line 22 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawPropertiesPopup(), and yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kHexByteInputWidth
constexpr float yaze::editor::kHexByteInputWidth = 50.f inline constexpr
Definition at line 31 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawGraphicsPopup(), and yaze::editor::MapPropertiesSystem::DrawPalettesPopup().
kHexWordInputWidth
constexpr float yaze::editor::kHexWordInputWidth = 70.f inline constexpr
Definition at line 32 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawPropertiesPopup().
kCompactButtonWidth
constexpr float yaze::editor::kCompactButtonWidth = 60.f inline constexpr
Definition at line 33 of file ui_constants.h.
kIconButtonWidth
constexpr float yaze::editor::kIconButtonWidth = 30.f inline constexpr
Definition at line 34 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawQuickAccessPopup(), and yaze::editor::MapPropertiesSystem::DrawViewPopup().
kSmallButtonWidth
constexpr float yaze::editor::kSmallButtonWidth = 80.f inline constexpr
Definition at line 35 of file ui_constants.h.
kMediumButtonWidth
constexpr float yaze::editor::kMediumButtonWidth = 90.f inline constexpr
Definition at line 36 of file ui_constants.h.
kLargeButtonWidth
constexpr float yaze::editor::kLargeButtonWidth = 100.f inline constexpr
Definition at line 37 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawPropertiesPopup().
kTableColumnWorld
constexpr float yaze::editor::kTableColumnWorld = 120.f inline constexpr
Definition at line 40 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnMap
constexpr float yaze::editor::kTableColumnMap = 80.f inline constexpr
Definition at line 41 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnAreaSize
constexpr float yaze::editor::kTableColumnAreaSize = 120.f inline constexpr
Definition at line 42 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnLock
constexpr float yaze::editor::kTableColumnLock = 50.f inline constexpr
Definition at line 43 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnGraphics
constexpr float yaze::editor::kTableColumnGraphics = 80.f inline constexpr
Definition at line 44 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnPalettes
constexpr float yaze::editor::kTableColumnPalettes = 80.f inline constexpr
Definition at line 45 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnProperties
constexpr float yaze::editor::kTableColumnProperties = 100.f inline constexpr
Definition at line 46 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnTools
constexpr float yaze::editor::kTableColumnTools = 80.f inline constexpr
Definition at line 47 of file ui_constants.h.
kTableColumnView
constexpr float yaze::editor::kTableColumnView = 80.f inline constexpr
Definition at line 48 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableColumnQuick
constexpr float yaze::editor::kTableColumnQuick = 80.f inline constexpr
Definition at line 49 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kComboWorldWidth
constexpr float yaze::editor::kComboWorldWidth = 115.f inline constexpr
Definition at line 52 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kComboAreaSizeWidth
constexpr float yaze::editor::kComboAreaSizeWidth = 115.f inline constexpr
Definition at line 53 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawPropertiesPopup(), and yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kComboGameStateWidth
constexpr float yaze::editor::kComboGameStateWidth = 100.f inline constexpr
Definition at line 54 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawPropertiesPopup().
kTableButtonGraphics
constexpr float yaze::editor::kTableButtonGraphics = 75.f inline constexpr
Definition at line 57 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableButtonPalettes
constexpr float yaze::editor::kTableButtonPalettes = 75.f inline constexpr
Definition at line 58 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableButtonProperties
constexpr float yaze::editor::kTableButtonProperties = 95.f inline constexpr
Definition at line 59 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableButtonTools
constexpr float yaze::editor::kTableButtonTools = 75.f inline constexpr
Definition at line 60 of file ui_constants.h.
kTableButtonView
constexpr float yaze::editor::kTableButtonView = 75.f inline constexpr
Definition at line 61 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kTableButtonQuick
constexpr float yaze::editor::kTableButtonQuick = 75.f inline constexpr
Definition at line 62 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings().
kCompactItemSpacing
constexpr float yaze::editor::kCompactItemSpacing = 4.f inline constexpr
Definition at line 65 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawGraphicsPopup(), yaze::editor::MapPropertiesSystem::DrawPalettesPopup(), yaze::editor::MapPropertiesSystem::DrawPropertiesPopup(), yaze::editor::MapPropertiesSystem::DrawQuickAccessPopup(), and yaze::editor::MapPropertiesSystem::DrawViewPopup().
kCompactFramePadding
constexpr float yaze::editor::kCompactFramePadding = 2.f inline constexpr
Definition at line 66 of file ui_constants.h.
Referenced by yaze::editor::MapPropertiesSystem::DrawGraphicsPopup(), yaze::editor::MapPropertiesSystem::DrawPalettesPopup(), yaze::editor::MapPropertiesSystem::DrawPropertiesPopup(), yaze::editor::MapPropertiesSystem::DrawQuickAccessPopup(), and yaze::editor::MapPropertiesSystem::DrawViewPopup().
kSpriteTabFlags
constexpr ImGuiTabItemFlags yaze::editor::kSpriteTabFlags constexpr
Initial value:
=
    ImGuiTabItemFlags_Trailing | ImGuiTabItemFlags_NoTooltip
Definition at line 16 of file sprite_editor.h.
kSpriteTabBarFlags
constexpr ImGuiTabBarFlags yaze::editor::kSpriteTabBarFlags constexpr
Initial value:
=
    ImGuiTabBarFlags_AutoSelectNewTabs | ImGuiTabBarFlags_Reorderable |
    ImGuiTabBarFlags_FittingPolicyResizeDown |
    ImGuiTabBarFlags_TabListPopupButton
Definition at line 19 of file sprite_editor.h.
Referenced by yaze::editor::SpriteEditor::DrawVanillaSpriteEditor().
kSpriteTableFlags
constexpr ImGuiTableFlags yaze::editor::kSpriteTableFlags constexpr
Initial value:
=
    ImGuiTableFlags_Resizable | ImGuiTableFlags_Reorderable |
    ImGuiTableFlags_Hideable | ImGuiTableFlags_BordersOuter |
    ImGuiTableFlags_BordersV
Definition at line 24 of file sprite_editor.h.