yaze: yaze::gui::CanvasModals Class Reference
yaze::gui::CanvasModals Class Reference
Modal dialog management for canvas operations.
#include <canvas_modals.h>
Classes
struct ModalState
Public Member Functions
CanvasModals ()=default
void ShowAdvancedProperties (const std::string &canvas_id, const CanvasConfig &config, const gfx::Bitmap *bitmap=nullptr)
Show advanced canvas properties modal.
void ShowScalingControls (const std::string &canvas_id, const CanvasConfig &config, const gfx::Bitmap *bitmap=nullptr)
Show scaling controls modal.
void ShowBppConversionDialog (const std::string &canvas_id, const BppConversionOptions &options)
Show BPP format conversion dialog.
void ShowPaletteEditor (const std::string &canvas_id, const PaletteEditorOptions &options)
Show palette editor modal.
void ShowColorAnalysis (const std::string &canvas_id, const ColorAnalysisOptions &options)
Show color analysis modal.
void ShowPerformanceIntegration (const std::string &canvas_id, const PerformanceOptions &options)
Show performance dashboard integration.
void Render ()
Render all active modals.
bool IsAnyModalOpen () const
Check if any modal is open.
Private Member Functions
void RenderAdvancedPropertiesModal (const std::string &canvas_id, CanvasConfig &config, const gfx::Bitmap *bitmap)
void RenderScalingControlsModal (const std::string &canvas_id, CanvasConfig &config, const gfx::Bitmap *bitmap)
void RenderBppConversionModal (const std::string &canvas_id, const BppConversionOptions &options)
void RenderPaletteEditorModal (const std::string &canvas_id, const PaletteEditorOptions &options)
void RenderColorAnalysisModal (const std::string &canvas_id, const ColorAnalysisOptions &options)
void RenderPerformanceModal (const std::string &canvas_id, const PerformanceOptions &options)
void OpenModal (const std::string &id, std::function< void()> render_func)
void CloseModal (const std::string &id)
bool IsModalOpen (const std::string &id) const
void RenderMaterialIcon (const std::string &icon_name, const ImVec4 &color=ImVec4(1, 1, 1, 1))
void RenderMetricCard (const std::string &title, const std::string &value, const std::string &icon, const ImVec4 &color=ImVec4(1, 1, 1, 1))
void RenderSliderWithIcon (const std::string &label, const std::string &icon, float *value, float min_val, float max_val, const char *format="%.2f")
Private Attributes
std::vector< ModalState > active_modals_
Detailed Description
Modal dialog management for canvas operations.
Definition at line 58 of file canvas_modals.h.
Constructor & Destructor Documentation
CanvasModals()
yaze::gui::CanvasModals::CanvasModals () default
Member Function Documentation
ShowAdvancedProperties()
void yaze::gui::CanvasModals::ShowAdvancedProperties (const std::string & canvas_id, const CanvasConfig & config, const gfx::Bitmap * bitmap = nullptr)
Show advanced canvas properties modal.
Definition at line 30 of file canvas_modals.cc.
References yaze::gui::CanvasConfig::on_config_changed, yaze::gui::CanvasConfig::on_scale_changed, OpenModal(), and RenderAdvancedPropertiesModal().
ShowScalingControls()
void yaze::gui::CanvasModals::ShowScalingControls (const std::string & canvas_id, const CanvasConfig & config, const gfx::Bitmap * bitmap = nullptr)
Show scaling controls modal.
Definition at line 46 of file canvas_modals.cc.
References yaze::gui::CanvasConfig::on_config_changed, yaze::gui::CanvasConfig::on_scale_changed, OpenModal(), and RenderScalingControlsModal().
ShowBppConversionDialog()
void yaze::gui::CanvasModals::ShowBppConversionDialog (const std::string & canvas_id, const BppConversionOptions & options)
Show BPP format conversion dialog.
Definition at line 62 of file canvas_modals.cc.
References OpenModal(), and RenderBppConversionModal().
ShowPaletteEditor()
void yaze::gui::CanvasModals::ShowPaletteEditor (const std::string & canvas_id, const PaletteEditorOptions & options)
Show palette editor modal.
Definition at line 74 of file canvas_modals.cc.
References OpenModal(), and RenderPaletteEditorModal().
ShowColorAnalysis()
void yaze::gui::CanvasModals::ShowColorAnalysis (const std::string & canvas_id, const ColorAnalysisOptions & options)
Show color analysis modal.
Definition at line 86 of file canvas_modals.cc.
References OpenModal(), and RenderColorAnalysisModal().
ShowPerformanceIntegration()
void yaze::gui::CanvasModals::ShowPerformanceIntegration (const std::string & canvas_id, const PerformanceOptions & options)
Show performance dashboard integration.
Definition at line 98 of file canvas_modals.cc.
References OpenModal(), and RenderPerformanceModal().
Render()
void yaze::gui::CanvasModals::Render ()
Render all active modals.
Definition at line 110 of file canvas_modals.cc.
References active_modals_.
IsAnyModalOpen()
bool yaze::gui::CanvasModals::IsAnyModalOpen () const
Check if any modal is open.
Definition at line 124 of file canvas_modals.cc.
References active_modals_.
RenderAdvancedPropertiesModal()
void yaze::gui::CanvasModals::RenderAdvancedPropertiesModal (const std::string & canvas_id, CanvasConfig & config, const gfx::Bitmap * bitmap) private
Definition at line 129 of file canvas_modals.cc.
References yaze::gui::CanvasConfig::auto_resize, yaze::gui::CanvasConfig::canvas_size, yaze::gui::CanvasConfig::content_size, yaze::gui::CanvasConfig::enable_context_menu, yaze::gui::CanvasConfig::enable_custom_labels, yaze::gui::CanvasConfig::enable_grid, yaze::gui::CanvasConfig::enable_hex_labels, yaze::gfx::PerformanceDashboard::Get(), yaze::gfx::PerformanceProfiler::Get(), yaze::gui::CanvasConfig::global_scale, yaze::gui::CanvasConfig::grid_step, yaze::gfx::Bitmap::height(), ICON_MD_ANALYTICS, ICON_MD_BUILD, ICON_MD_GRID_ON, ICON_MD_IMAGE, ICON_MD_SETTINGS, ICON_MD_STRAIGHTEN, ICON_MD_TRENDING_UP, ICON_MD_ZOOM_IN, yaze::gui::CanvasConfig::is_draggable, yaze::gui::CanvasConfig::on_config_changed, RenderMaterialIcon(), RenderMetricCard(), RenderSliderWithIcon(), yaze::gui::CanvasConfig::scrolling, yaze::gfx::PerformanceDashboard::SetVisible(), and yaze::gfx::Bitmap::width().
Referenced by ShowAdvancedProperties().
RenderScalingControlsModal()
void yaze::gui::CanvasModals::RenderScalingControlsModal (const std::string & canvas_id, CanvasConfig & config, const gfx::Bitmap * bitmap) private
Definition at line 288 of file canvas_modals.cc.
References yaze::gui::CanvasConfig::canvas_size, yaze::gui::CanvasConfig::global_scale, yaze::gui::CanvasConfig::grid_step, yaze::gfx::Bitmap::height(), ICON_MD_ZOOM_IN, yaze::gui::CanvasConfig::on_scale_changed, RenderSliderWithIcon(), and yaze::gfx::Bitmap::width().
Referenced by ShowScalingControls().
RenderBppConversionModal()
void yaze::gui::CanvasModals::RenderBppConversionModal (const std::string & canvas_id, const BppConversionOptions & options) private
Definition at line 372 of file canvas_modals.cc.
References yaze::gui::BppConversionOptions::bitmap, ICON_MD_SWAP_HORIZ, yaze::gui::BppConversionOptions::on_convert, and yaze::gui::BppConversionOptions::palette.
Referenced by ShowBppConversionDialog().
RenderPaletteEditorModal()
void yaze::gui::CanvasModals::RenderPaletteEditorModal (const std::string & canvas_id, const PaletteEditorOptions & options) private
Definition at line 407 of file canvas_modals.cc.
References ICON_MD_PALETTE, yaze::gui::PaletteEditorOptions::palette, and yaze::gui::PaletteEditorOptions::title.
Referenced by ShowPaletteEditor().
RenderColorAnalysisModal()
void yaze::gui::CanvasModals::RenderColorAnalysisModal (const std::string & canvas_id, const ColorAnalysisOptions & options) private
Definition at line 440 of file canvas_modals.cc.
References yaze::gui::ColorAnalysisOptions::bitmap, and ICON_MD_ZOOM_IN.
Referenced by ShowColorAnalysis().
RenderPerformanceModal()
void yaze::gui::CanvasModals::RenderPerformanceModal (const std::string & canvas_id, const PerformanceOptions & options) private
Definition at line 473 of file canvas_modals.cc.
References yaze::gfx::PerformanceDashboard::Get(), yaze::gfx::PerformanceProfiler::Get(), ICON_MD_TRENDING_UP, yaze::gui::PerformanceOptions::operation_name, yaze::gui::PerformanceOptions::operation_time_ms, RenderMetricCard(), and yaze::gfx::PerformanceDashboard::SetVisible().
Referenced by ShowPerformanceIntegration().
OpenModal()
void yaze::gui::CanvasModals::OpenModal (const std::string & id, std::function< void()> render_func) private
Definition at line 515 of file canvas_modals.cc.
References active_modals_.
Referenced by ShowAdvancedProperties(), ShowBppConversionDialog(), ShowColorAnalysis(), ShowPaletteEditor(), ShowPerformanceIntegration(), and ShowScalingControls().
CloseModal()
void yaze::gui::CanvasModals::CloseModal (const std::string & id) private
Definition at line 531 of file canvas_modals.cc.
References active_modals_.
IsModalOpen()
bool yaze::gui::CanvasModals::IsModalOpen (const std::string & id) const private
Definition at line 540 of file canvas_modals.cc.
References active_modals_.
RenderMaterialIcon()
void yaze::gui::CanvasModals::RenderMaterialIcon (const std::string & icon_name, const ImVec4 & color = ImVec4(1, 1, 1, 1)) private
Definition at line 547 of file canvas_modals.cc.
References ICON_MD_DRAG_INDICATOR, ICON_MD_EDIT, ICON_MD_FIT_SCREEN, ICON_MD_FUNCTIONS, ICON_MD_GRID_ON, ICON_MD_INFO, ICON_MD_LABEL, ICON_MD_MENU, ICON_MD_REFRESH, ICON_MD_SCHEDULE, ICON_MD_SETTINGS, ICON_MD_SPEED, ICON_MD_TIMER, and ICON_MD_ZOOM_IN.
Referenced by RenderAdvancedPropertiesModal().
RenderMetricCard()
void yaze::gui::CanvasModals::RenderMetricCard (const std::string & title, const std::string & value, const std::string & icon, const ImVec4 & color = ImVec4(1, 1, 1, 1)) private
Definition at line 563 of file canvas_modals.cc.
Referenced by RenderAdvancedPropertiesModal(), and RenderPerformanceModal().
RenderSliderWithIcon()
void yaze::gui::CanvasModals::RenderSliderWithIcon (const std::string & label, const std::string & icon, float * value, float min_val, float max_val, const char * format = "%.2f") private
Definition at line 576 of file canvas_modals.cc.
Referenced by RenderAdvancedPropertiesModal(), and RenderScalingControlsModal().
Member Data Documentation
active_modals_
std::vector<ModalState> yaze::gui::CanvasModals::active_modals_ private
Definition at line 117 of file canvas_modals.h.
Referenced by CloseModal(), IsAnyModalOpen(), IsModalOpen(), OpenModal(), and Render().
The documentation for this class was generated from the following files:
src/app/gui/canvas/canvas_modals.h
src/app/gui/canvas/canvas_modals.cc