yaze: yaze::cli::net Namespace Reference
yaze::cli::net Namespace Reference
Namespaces
namespace anonymous_namespace{net_commands.cc}
Classes
class Z3edNetworkClient
Simplified WebSocket client for z3ed CLI.
Functions
absl::Status HandleNetConnect (const std::vector< std::string > &args)
absl::Status HandleNetJoin (const std::vector< std::string > &args)
absl::Status HandleNetLeave (const std::vector< std::string > &args)
absl::Status HandleNetProposal (const std::vector< std::string > &args)
absl::Status HandleProposalSubmit (const std::vector< std::string > &args)
absl::Status HandleProposalStatus (const std::vector< std::string > &args)
absl::Status HandleProposalWait (const std::vector< std::string > &args)
absl::Status HandleNetStatus (const std::vector< std::string > &args)
Function Documentation
HandleNetConnect()
absl::Status yaze::cli::net::HandleNetConnect (const std::vector< std::string > & args)
Handle 'z3ed net connect' command
Definition at line 31 of file net_commands.cc.
HandleNetJoin()
absl::Status yaze::cli::net::HandleNetJoin (const std::vector< std::string > & args)
Handle 'z3ed net join' command
Definition at line 61 of file net_commands.cc.
HandleNetLeave()
absl::Status yaze::cli::net::HandleNetLeave (const std::vector< std::string > & args)
Handle 'z3ed net leave' command
Definition at line 102 of file net_commands.cc.
HandleNetProposal()
absl::Status yaze::cli::net::HandleNetProposal (const std::vector< std::string > & args)
Handle 'z3ed net proposal' command
Definition at line 118 of file net_commands.cc.
References HandleProposalStatus(), HandleProposalSubmit(), and HandleProposalWait().
HandleProposalSubmit()
absl::Status yaze::cli::net::HandleProposalSubmit (const std::vector< std::string > & args)
Definition at line 149 of file net_commands.cc.
Referenced by HandleNetProposal().
HandleProposalStatus()
absl::Status yaze::cli::net::HandleProposalStatus (const std::vector< std::string > & args)
Definition at line 191 of file net_commands.cc.
Referenced by HandleNetProposal().
HandleProposalWait()
absl::Status yaze::cli::net::HandleProposalWait (const std::vector< std::string > & args)
Definition at line 219 of file net_commands.cc.
Referenced by HandleNetProposal().
HandleNetStatus()
absl::Status yaze::cli::net::HandleNetStatus (const std::vector< std::string > & args)
Handle 'z3ed net status' command
Definition at line 259 of file net_commands.cc.