yaze: yaze::Controller Class Reference
yaze::Controller Class Reference
Main controller for the application.
#include <controller.h>
Public Member Functions
bool IsActive () const
absl::Status OnEntry (std::string filename="")
void OnInput ()
absl::Status OnLoad ()
void DoRender () const
void OnExit ()
void SetStartupEditor (const std::string &editor_name, const std::string &cards)
auto window () -> SDL_Window *
void set_active (bool active)
auto active () const
auto overworld () -> yaze::zelda3::Overworld *
auto GetCurrentRom () -> Rom *
auto renderer () -> gfx::IRenderer *
Private Member Functions
friend int::main (int argc, char **argv)
Private Attributes
bool active_ = false
core::Window window_
editor::EditorManager editor_manager_
std::unique_ptr< gfx::IRenderer > renderer_
Detailed Description
Main controller for the application.
This class is responsible for managing the main window and the main editor. It is the main entry point for the application.
Definition at line 24 of file controller.h.
Member Function Documentation
IsActive()
bool yaze::Controller::IsActive () const inline
Definition at line 26 of file controller.h.
References active_.
Referenced by yaze::test::RunIntegrationTest(), and yaze::test::EditorIntegrationTest::RunTest().
OnEntry()
absl::Status yaze::Controller::OnEntry (std::string filename = "")
Definition at line 22 of file controller.cc.
References active_, yaze::core::Window::audio_buffer_, yaze::core::Window::audio_device_, editor_manager_, yaze::editor::EditorManager::emulator(), yaze::gfx::Arena::Get(), yaze::editor::EditorManager::Initialize(), yaze::gfx::Arena::Initialize(), renderer_, RETURN_IF_ERROR, and window_.
Referenced by yaze::test::gui::LoadRomInTest().
OnInput()
void yaze::Controller::OnInput ()
Definition at line 52 of file controller.cc.
References PRINT_IF_ERROR, and window_.
Referenced by yaze::test::RunIntegrationTest(), and yaze::test::EditorIntegrationTest::RunTest().
OnLoad()
absl::Status yaze::Controller::OnLoad ()
Definition at line 56 of file controller.cc.
References active_, yaze::core::Window::active_, yaze::gui::DockSpaceRenderer::BeginEnhancedDockSpace(), yaze::gui::WidgetIdRegistry::BeginFrame(), yaze::editor::EditorManager::DrawMenuBar(), editor_manager_, yaze::gui::WidgetIdRegistry::EndFrame(), yaze::gui::WidgetIdRegistry::Instance(), yaze::editor::EditorManager::quit(), RETURN_IF_ERROR, yaze::editor::EditorManager::Update(), and window_.
DoRender()
void yaze::Controller::DoRender () const
Definition at line 101 of file controller.cc.
References yaze::gfx::Arena::Get(), yaze::TimingManager::Get(), yaze::gfx::Arena::ProcessTextureQueue(), renderer_, and yaze::TimingManager::Update().
Referenced by main(), yaze::test::RunIntegrationTest(), and yaze::test::EditorIntegrationTest::RunTest().
OnExit()
void yaze::Controller::OnExit ()
Definition at line 122 of file controller.cc.
References PRINT_IF_ERROR, renderer_, and window_.
Referenced by main(), and yaze::test::RunIntegrationTest().
SetStartupEditor()
void yaze::Controller::SetStartupEditor (const std::string & editor_name, const std::string & cards)
Definition at line 43 of file controller.cc.
References editor_manager_, and yaze::editor::EditorManager::OpenEditorAndCardsFromFlags().
window()
auto yaze::Controller::window () -> SDL_Window* inline
Definition at line 36 of file controller.h.
References window_, and yaze::core::Window::window_.
Referenced by yaze::test::EditorIntegrationTest::Initialize(), and yaze::test::RunIntegrationTest().
set_active()
void yaze::Controller::set_active (bool active) inline
Definition at line 37 of file controller.h.
References active(), and active_.
Referenced by yaze::test::EditorIntegrationTest::Initialize(), and yaze::test::RunIntegrationTest().
active()
auto yaze::Controller::active () const inline
Definition at line 38 of file controller.h.
References active_.
Referenced by set_active().
overworld()
auto yaze::Controller::overworld () -> yaze::zelda3::Overworld* inline
Definition at line 39 of file controller.h.
References editor_manager_, and yaze::editor::EditorManager::overworld().
Referenced by E2ETest_CanvasSelectionTest().
GetCurrentRom()
auto yaze::Controller::GetCurrentRom () -> Rom* inline
Definition at line 42 of file controller.h.
References editor_manager_, and yaze::editor::EditorManager::GetCurrentRom().
renderer()
auto yaze::Controller::renderer () -> gfx::IRenderer* inline
Definition at line 43 of file controller.h.
References renderer_.
int::main()
yaze::Controller::int::main (int argc, char ** argv) private
Member Data Documentation
active_
bool yaze::Controller::active_ = false private
Definition at line 48 of file controller.h.
Referenced by active(), IsActive(), OnEntry(), OnLoad(), and set_active().
window_
core::Window yaze::Controller::window_ private
Definition at line 49 of file controller.h.
Referenced by OnEntry(), OnExit(), OnInput(), OnLoad(), and window().
editor_manager_
editor::EditorManager yaze::Controller::editor_manager_ private
Definition at line 50 of file controller.h.
Referenced by GetCurrentRom(), OnEntry(), OnLoad(), overworld(), and SetStartupEditor().
renderer_
std::unique_ptr<gfx::IRenderer> yaze::Controller::renderer_ private
Definition at line 51 of file controller.h.
Referenced by DoRender(), OnEntry(), OnExit(), and renderer().
The documentation for this class was generated from the following files:
src/app/controller.h
src/app/controller.cc