yaze: yaze::cli::agent::AdvancedRouter Class Reference
yaze::cli::agent::AdvancedRouter Class Reference
Advanced routing system for agent tool responses.
#include <advanced_routing.h>
Classes
struct RouteContext
struct RoutedResponse
Static Public Member Functions
static RoutedResponse RouteHexAnalysis (const std::vector< uint8_t > &data, uint32_t address, const RouteContext &ctx)
Route hex data analysis response.
static RoutedResponse RouteMapEdit (const std::string &edit_intent, const RouteContext &ctx)
Route map editing response.
static RoutedResponse RoutePaletteAnalysis (const std::vector< uint16_t > &colors, const RouteContext &ctx)
Route palette analysis response.
static RoutedResponse SynthesizeMultiToolResponse (const std::vector< std::string > &tool_results, const RouteContext &ctx)
Synthesize multi-tool response.
static std::string GenerateGUIScript (const std::vector< std::string > &actions)
Generate GUI automation script.
Static Private Member Functions
static std::string InferDataType (const std::vector< uint8_t > &data)
static std::vector< std::string > ExtractPatterns (const std::vector< uint8_t > &data)
static std::string FormatForAgent (const std::string &raw_data)
Detailed Description
Advanced routing system for agent tool responses.
Optimizes information flow back to agent for:
Map editing with GUI automation
Hex data analysis and pattern recognition
Multi-step operations with context preservation
Definition at line 23 of file advanced_routing.h.
Member Function Documentation
RouteHexAnalysis()
AdvancedRouter::RoutedResponse yaze::cli::agent::AdvancedRouter::RouteHexAnalysis (const std::vector< uint8_t > & data, uint32_t address, const RouteContext & ctx) static
Route hex data analysis response.
Definition at line 12 of file advanced_routing.cc.
References yaze::cli::agent::AdvancedRouter::RoutedResponse::detailed_data, ExtractPatterns(), InferDataType(), yaze::cli::agent::AdvancedRouter::RoutedResponse::next_steps, and yaze::cli::agent::AdvancedRouter::RoutedResponse::summary.
RouteMapEdit()
AdvancedRouter::RoutedResponse yaze::cli::agent::AdvancedRouter::RouteMapEdit (const std::string & edit_intent, const RouteContext & ctx) static
Route map editing response.
Definition at line 67 of file advanced_routing.cc.
References yaze::cli::agent::AdvancedRouter::RoutedResponse::detailed_data, GenerateGUIScript(), yaze::cli::agent::AdvancedRouter::RoutedResponse::gui_actions, yaze::cli::agent::AdvancedRouter::RoutedResponse::needs_approval, yaze::cli::agent::AdvancedRouter::RoutedResponse::next_steps, and yaze::cli::agent::AdvancedRouter::RoutedResponse::summary.
RoutePaletteAnalysis()
AdvancedRouter::RoutedResponse yaze::cli::agent::AdvancedRouter::RoutePaletteAnalysis (const std::vector< uint16_t > & colors, const RouteContext & ctx) static
Route palette analysis response.
Definition at line 94 of file advanced_routing.cc.
References yaze::cli::agent::AdvancedRouter::RoutedResponse::detailed_data, yaze::cli::agent::AdvancedRouter::RoutedResponse::next_steps, and yaze::cli::agent::AdvancedRouter::RoutedResponse::summary.
SynthesizeMultiToolResponse()
AdvancedRouter::RoutedResponse yaze::cli::agent::AdvancedRouter::SynthesizeMultiToolResponse (const std::vector< std::string > & tool_results, const RouteContext & ctx) static
Synthesize multi-tool response.
Definition at line 133 of file advanced_routing.cc.
References yaze::cli::agent::AdvancedRouter::RoutedResponse::detailed_data, yaze::cli::agent::AdvancedRouter::RoutedResponse::next_steps, yaze::cli::agent::AdvancedRouter::RoutedResponse::summary, and yaze::cli::agent::AdvancedRouter::RouteContext::user_intent.
GenerateGUIScript()
std::string yaze::cli::agent::AdvancedRouter::GenerateGUIScript (const std::vector< std::string > & actions) static
Generate GUI automation script.
Definition at line 149 of file advanced_routing.cc.
Referenced by RouteMapEdit().
InferDataType()
std::string yaze::cli::agent::AdvancedRouter::InferDataType (const std::vector< uint8_t > & data) static private
Definition at line 161 of file advanced_routing.cc.
Referenced by RouteHexAnalysis().
ExtractPatterns()
std::vector< std::string > yaze::cli::agent::AdvancedRouter::ExtractPatterns (const std::vector< uint8_t > & data) static private
Definition at line 169 of file advanced_routing.cc.
Referenced by RouteHexAnalysis().
FormatForAgent()
std::string yaze::cli::agent::AdvancedRouter::FormatForAgent (const std::string & raw_data) static private
Definition at line 201 of file advanced_routing.cc.
The documentation for this class was generated from the following files:
src/cli/service/agent/advanced_routing.h
src/cli/service/agent/advanced_routing.cc