yaze: yaze::cli::RomSandboxManager Class Reference
yaze::cli::RomSandboxManager Class Reference abstract
#include <rom_sandbox_manager.h>
Classes
struct SandboxMetadata
Public Member Functions
void SetRootDirectory (const std::filesystem::path &root)
const std::filesystem::path & RootDirectory () const
absl::StatusOr< SandboxMetadata > CreateSandbox (Rom &rom, absl::string_view description)
absl::StatusOr< SandboxMetadata > ActiveSandbox () const
absl::StatusOr< std::filesystem::path > ActiveSandboxRomPath () const
std::vector< SandboxMetadata > ListSandboxes () const
absl::Status RemoveSandbox (const std::string &id)
absl::StatusOr< int > CleanupOlderThan (absl::Duration max_age)
Static Public Member Functions
static RomSandboxManager & Instance ()
Private Member Functions
RomSandboxManager ()
absl::Status EnsureRootExistsLocked ()
std::string GenerateSandboxIdLocked ()
int sequence_ ABSL_GUARDED_BY (mutex_)=0
Private Attributes
std::filesystem::path root_directory_
std::mutex mutex_
std::unordered_map< std::string, SandboxMetadata > sandboxes_
std::optional< std::string > active_sandbox_id_
Detailed Description
Definition at line 27 of file rom_sandbox_manager.h.
Constructor & Destructor Documentation
RomSandboxManager()
yaze::cli::RomSandboxManager::RomSandboxManager () private
Definition at line 45 of file rom_sandbox_manager.cc.
Referenced by Instance().
Member Function Documentation
Instance()
RomSandboxManager & yaze::cli::RomSandboxManager::Instance () static
Definition at line 40 of file rom_sandbox_manager.cc.
References RomSandboxManager().
Referenced by yaze::editor::ProposalDrawer::AcceptProposal(), yaze::cli::agent::HandleAcceptCommand(), yaze::cli::agent::HandleDiffCommand(), and yaze::cli::agent::HandleRunCommand().
SetRootDirectory()
void yaze::cli::RomSandboxManager::SetRootDirectory (const std::filesystem::path & root)
Definition at line 48 of file rom_sandbox_manager.cc.
References EnsureRootExistsLocked(), mutex_, and root_directory_.
RootDirectory()
const std::filesystem::path & yaze::cli::RomSandboxManager::RootDirectory () const
Definition at line 54 of file rom_sandbox_manager.cc.
References root_directory_.
CreateSandbox()
absl::StatusOr< RomSandboxManager::SandboxMetadata > yaze::cli::RomSandboxManager::CreateSandbox (Rom & rom, absl::string_view description)
Definition at line 79 of file rom_sandbox_manager.cc.
References active_sandbox_id_, yaze::Rom::SaveSettings::backup, EnsureRootExistsLocked(), yaze::Rom::SaveSettings::filename, yaze::Rom::filename(), GenerateSandboxIdLocked(), yaze::cli::RomSandboxManager::SandboxMetadata::id, yaze::Rom::is_loaded(), mutex_, RETURN_IF_ERROR, root_directory_, sandboxes_, yaze::Rom::SaveSettings::save_new, yaze::Rom::SaveToFile(), and yaze::Rom::SaveSettings::z3_save.
Referenced by yaze::cli::agent::HandleRunCommand().
ActiveSandbox()
absl::StatusOr< RomSandboxManager::SandboxMetadata > yaze::cli::RomSandboxManager::ActiveSandbox () const
Definition at line 136 of file rom_sandbox_manager.cc.
References active_sandbox_id_, mutex_, and sandboxes_.
Referenced by ActiveSandboxRomPath(), and yaze::cli::agent::HandleDiffCommand().
ActiveSandboxRomPath()
absl::StatusOr< std::filesystem::path > yaze::cli::RomSandboxManager::ActiveSandboxRomPath () const
Definition at line 149 of file rom_sandbox_manager.cc.
References ActiveSandbox(), and ASSIGN_OR_RETURN.
ListSandboxes()
std::vector< RomSandboxManager::SandboxMetadata > yaze::cli::RomSandboxManager::ListSandboxes () const
Definition at line 155 of file rom_sandbox_manager.cc.
References mutex_, and sandboxes_.
RemoveSandbox()
absl::Status yaze::cli::RomSandboxManager::RemoveSandbox (const std::string & id)
Definition at line 169 of file rom_sandbox_manager.cc.
References active_sandbox_id_, mutex_, and sandboxes_.
Referenced by CleanupOlderThan(), and yaze::cli::agent::HandleAcceptCommand().
CleanupOlderThan()
absl::StatusOr< int > yaze::cli::RomSandboxManager::CleanupOlderThan (absl::Duration max_age)
Definition at line 188 of file rom_sandbox_manager.cc.
References mutex_, RemoveSandbox(), and sandboxes_.
EnsureRootExistsLocked()
absl::Status yaze::cli::RomSandboxManager::EnsureRootExistsLocked () private
Definition at line 58 of file rom_sandbox_manager.cc.
References root_directory_.
Referenced by CreateSandbox(), and SetRootDirectory().
GenerateSandboxIdLocked()
std::string yaze::cli::RomSandboxManager::GenerateSandboxIdLocked () private
Definition at line 70 of file rom_sandbox_manager.cc.
Referenced by CreateSandbox().
ABSL_GUARDED_BY()
int sequence_ yaze::cli::RomSandboxManager::ABSL_GUARDED_BY (mutex_) private pure virtual
Member Data Documentation
root_directory_
std::filesystem::path yaze::cli::RomSandboxManager::root_directory_ private
Definition at line 82 of file rom_sandbox_manager.h.
Referenced by CreateSandbox(), EnsureRootExistsLocked(), RootDirectory(), and SetRootDirectory().
mutex_
std::mutex yaze::cli::RomSandboxManager::mutex_ mutable private
Definition at line 83 of file rom_sandbox_manager.h.
Referenced by ActiveSandbox(), CleanupOlderThan(), CreateSandbox(), ListSandboxes(), RemoveSandbox(), and SetRootDirectory().
sandboxes_
std::unordered_map<std::string, SandboxMetadata> yaze::cli::RomSandboxManager::sandboxes_ private
Definition at line 84 of file rom_sandbox_manager.h.
Referenced by ActiveSandbox(), CleanupOlderThan(), CreateSandbox(), ListSandboxes(), and RemoveSandbox().
active_sandbox_id_
std::optional<std::string> yaze::cli::RomSandboxManager::active_sandbox_id_ private
Definition at line 85 of file rom_sandbox_manager.h.
Referenced by ActiveSandbox(), CreateSandbox(), and RemoveSandbox().
The documentation for this class was generated from the following files:
src/cli/service/rom/rom_sandbox_manager.h
src/cli/service/rom/rom_sandbox_manager.cc