yaze: test/e2e/canvas_selection_test.h File Reference
canvas_selection_test.h File Reference
#include "imgui_test_engine/imgui_te_context.h"
Functions
void E2ETest_CanvasSelectionTest (ImGuiTestContext *ctx)
Function Documentation
E2ETest_CanvasSelectionTest()
void E2ETest_CanvasSelectionTest (ImGuiTestContext * ctx)
Definition at line 6 of file canvas_selection_test.cc.
References yaze::zelda3::Overworld::GetTile(), yaze::test::gui::LoadRomInTest(), yaze::test::gui::OpenEditorInTest(), and yaze::core::Controller::overworld().
Referenced by main().