yaze: yaze::cli::ai::AIActionParser Class Reference
yaze::cli::ai::AIActionParser Class Reference
Parses natural language commands into structured GUI actions.
#include <ai_action_parser.h>
Static Public Member Functions
static absl::StatusOr< std::vector< AIAction > > ParseCommand (const std::string &command)
static std::string ActionToString (const AIAction &action)
Static Private Member Functions
static AIActionType ParseActionType (const std::string &verb)
static std::map< std::string, std::string > ExtractParameters (const std::string &command, AIActionType type)
static bool MatchesPlaceTilePattern (const std::string &command, std::map< std::string, std::string > *params)
static bool MatchesSelectTilePattern (const std::string &command, std::map< std::string, std::string > *params)
static bool MatchesOpenEditorPattern (const std::string &command, std::map< std::string, std::string > *params)
Detailed Description
Parses natural language commands into structured GUI actions.
Understands commands like:
"Place tile 0x42 at overworld position (5, 7)"
"Open the overworld editor"
"Select tile 100 from the tile selector"
Definition at line 53 of file ai_action_parser.h.
Member Function Documentation
ParseCommand()
absl::StatusOr< std::vector< AIAction > > yaze::cli::ai::AIActionParser::ParseCommand (const std::string & command) static
Parse a natural language command into a sequence of AI actions
Parameters
command The command to parse
Returns
Vector of actions, or error status
Definition at line 52 of file ai_action_parser.cc.
References yaze::cli::ai::kClickButton, yaze::cli::ai::kOpenEditor, yaze::cli::ai::kPlaceTile, yaze::cli::ai::kSaveTile, yaze::cli::ai::kSelectTile, MatchesOpenEditorPattern(), MatchesPlaceTilePattern(), and MatchesSelectTilePattern().
Referenced by yaze::test::TEST_F(), yaze::test::TEST_F(), and yaze::test::TEST_F().
ActionToString()
std::string yaze::cli::ai::AIActionParser::ActionToString (const AIAction & action) static
Convert an action back to a human-readable string
Definition at line 98 of file ai_action_parser.cc.
References yaze::cli::ai::kClickButton, yaze::cli::ai::kInvalidAction, yaze::cli::ai::kOpenEditor, yaze::cli::ai::kPlaceTile, yaze::cli::ai::kSaveTile, yaze::cli::ai::kScreenshot, yaze::cli::ai::kSelectTile, yaze::cli::ai::kVerifyTile, yaze::cli::ai::kWait, yaze::cli::ai::AIAction::parameters, and yaze::cli::ai::AIAction::type.
Referenced by yaze::test::TEST_F().
ParseActionType()
static AIActionType yaze::cli::ai::AIActionParser::ParseActionType (const std::string & verb) static private
ExtractParameters()
static std::map< std::string, std::string > yaze::cli::ai::AIActionParser::ExtractParameters (const std::string & command, AIActionType type) static private
MatchesPlaceTilePattern()
bool yaze::cli::ai::AIActionParser::MatchesPlaceTilePattern (const std::string & command, std::map< std::string, std::string > * params) static private
Definition at line 152 of file ai_action_parser.cc.
Referenced by ParseCommand().
MatchesSelectTilePattern()
bool yaze::cli::ai::AIActionParser::MatchesSelectTilePattern (const std::string & command, std::map< std::string, std::string > * params) static private
Definition at line 203 of file ai_action_parser.cc.
Referenced by ParseCommand().
MatchesOpenEditorPattern()
bool yaze::cli::ai::AIActionParser::MatchesOpenEditorPattern (const std::string & command, std::map< std::string, std::string > * params) static private
Definition at line 236 of file ai_action_parser.cc.
Referenced by ParseCommand().
The documentation for this class was generated from the following files:
src/cli/service/ai/ai_action_parser.h
src/cli/service/ai/ai_action_parser.cc