yaze: yaze::cli::agent::anonymous_namespace{tool_commands.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{tool_commands.cc} Namespace Reference
Functions
absl::StatusOr< Rom > LoadRomFromFlag ()
absl::StatusOr< Rom > LoadRomFromPathOrFlag (const std::optional< std::string > &override_path)
Function Documentation
LoadRomFromFlag()
absl::StatusOr< Rom > yaze::cli::agent::anonymous_namespace{tool_commands.cc}::LoadRomFromFlag ()
Definition at line 41 of file tool_commands.cc.
References yaze::cli::InitializeMockRom(), yaze::Rom::LoadFromFile(), and LoadRomFromFlag().
Referenced by LoadRomFromFlag(), and LoadRomFromPathOrFlag().
LoadRomFromPathOrFlag()
absl::StatusOr< Rom > yaze::cli::agent::anonymous_namespace{tool_commands.cc}::LoadRomFromPathOrFlag (const std::optional< std::string > & override_path)
Definition at line 70 of file tool_commands.cc.
References yaze::Rom::LoadFromFile(), LoadRomFromFlag(), and LoadRomFromPathOrFlag().
Referenced by LoadRomFromPathOrFlag().