yaze: yaze::editor::GfxGroupEditor Class Reference
yaze::editor::GfxGroupEditor Class Reference
Manage graphics group configurations in a Rom.
#include <gfx_group_editor.h>
Public Member Functions
absl::Status Update ()
void DrawBlocksetViewer (bool sheet_only=false)
void DrawRoomsetViewer ()
void DrawSpritesetViewer (bool sheet_only=false)
void DrawPaletteViewer ()
void SetSelectedBlockset (uint8_t blockset)
void SetSelectedRoomset (uint8_t roomset)
void SetSelectedSpriteset (uint8_t spriteset)
void set_rom (Rom *rom)
Rom * rom () const
Private Attributes
uint8_t selected_blockset_ = 0
uint8_t selected_roomset_ = 0
uint8_t selected_spriteset_ = 0
uint8_t selected_paletteset_ = 0
gui::Canvas blockset_canvas_
gui::Canvas roomset_canvas_
gui::Canvas spriteset_canvas_
gfx::SnesPalette palette_
Rom * rom_ = nullptr
Detailed Description
Manage graphics group configurations in a Rom.
Definition at line 16 of file gfx_group_editor.h.
Member Function Documentation
Update()
absl::Status yaze::editor::GfxGroupEditor::Update ()
Definition at line 43 of file gfx_group_editor.cc.
References DrawBlocksetViewer(), DrawPaletteViewer(), DrawRoomsetViewer(), DrawSpritesetViewer(), yaze::gui::InputHexByte(), yaze::Rom::resource_label(), rom(), yaze::core::ResourceLabelManager::SelectableLabelWithNameEdit(), selected_blockset_, selected_roomset_, and selected_spriteset_.
Referenced by yaze::editor::OverworldEditor::DrawOverworldProperties(), and yaze::editor::OverworldEditor::Update().
DrawBlocksetViewer()
void yaze::editor::GfxGroupEditor::DrawBlocksetViewer (bool sheet_only = false)
Definition at line 86 of file gfx_group_editor.cc.
References yaze::gui::BitmapCanvasPipeline(), blockset_canvas_, yaze::gfx::Arena::Get(), yaze::gui::InputHexByte(), yaze::Rom::main_blockset_ids, yaze::gfx::Arena::mutable_gfx_sheets(), rom(), and selected_blockset_.
Referenced by Update().
DrawRoomsetViewer()
void yaze::editor::GfxGroupEditor::DrawRoomsetViewer ()
Definition at line 125 of file gfx_group_editor.cc.
References yaze::gui::BitmapCanvasPipeline(), yaze::gfx::Arena::Get(), yaze::gui::InputHexByte(), yaze::gfx::Arena::mutable_gfx_sheets(), yaze::Rom::resource_label(), rom(), yaze::Rom::room_blockset_ids, roomset_canvas_, yaze::core::ResourceLabelManager::SelectableLabelWithNameEdit(), and selected_roomset_.
Referenced by Update().
DrawSpritesetViewer()
void yaze::editor::GfxGroupEditor::DrawSpritesetViewer (bool sheet_only = false)
Definition at line 178 of file gfx_group_editor.cc.
References yaze::gui::BitmapCanvasPipeline(), yaze::gfx::Arena::Get(), yaze::gui::InputHexByte(), yaze::gfx::Arena::mutable_gfx_sheets(), rom(), selected_spriteset_, spriteset_canvas_, and yaze::Rom::spriteset_ids.
Referenced by Update().
DrawPaletteViewer()
void yaze::editor::GfxGroupEditor::DrawPaletteViewer ()
Definition at line 238 of file gfx_group_editor.cc.
References yaze::gui::InputHexByte(), yaze::Rom::mutable_palette_group(), yaze::Rom::paletteset_ids, yaze::Rom::resource_label(), rom(), yaze::core::ResourceLabelManager::SelectableLabelWithNameEdit(), and selected_paletteset_.
Referenced by Update().
SetSelectedBlockset()
void yaze::editor::GfxGroupEditor::SetSelectedBlockset (uint8_t blockset) inline
Definition at line 25 of file gfx_group_editor.h.
References selected_blockset_.
SetSelectedRoomset()
void yaze::editor::GfxGroupEditor::SetSelectedRoomset (uint8_t roomset) inline
Definition at line 26 of file gfx_group_editor.h.
References selected_roomset_.
SetSelectedSpriteset()
void yaze::editor::GfxGroupEditor::SetSelectedSpriteset (uint8_t spriteset) inline
Definition at line 27 of file gfx_group_editor.h.
References selected_spriteset_.
set_rom()
void yaze::editor::GfxGroupEditor::set_rom (Rom * rom) inline
Definition at line 30 of file gfx_group_editor.h.
References rom(), and rom_.
Referenced by yaze::editor::OverworldEditor::OverworldEditor().
rom()
Rom * yaze::editor::GfxGroupEditor::rom () const inline
Definition at line 31 of file gfx_group_editor.h.
References rom_.
Referenced by DrawBlocksetViewer(), DrawPaletteViewer(), DrawRoomsetViewer(), DrawSpritesetViewer(), set_rom(), and Update().
Member Data Documentation
selected_blockset_
uint8_t yaze::editor::GfxGroupEditor::selected_blockset_ = 0 private
Definition at line 34 of file gfx_group_editor.h.
Referenced by DrawBlocksetViewer(), SetSelectedBlockset(), and Update().
selected_roomset_
uint8_t yaze::editor::GfxGroupEditor::selected_roomset_ = 0 private
Definition at line 35 of file gfx_group_editor.h.
Referenced by DrawRoomsetViewer(), SetSelectedRoomset(), and Update().
selected_spriteset_
uint8_t yaze::editor::GfxGroupEditor::selected_spriteset_ = 0 private
Definition at line 36 of file gfx_group_editor.h.
Referenced by DrawSpritesetViewer(), SetSelectedSpriteset(), and Update().
selected_paletteset_
uint8_t yaze::editor::GfxGroupEditor::selected_paletteset_ = 0 private
Definition at line 37 of file gfx_group_editor.h.
Referenced by DrawPaletteViewer().
blockset_canvas_
gui::Canvas yaze::editor::GfxGroupEditor::blockset_canvas_ private
Definition at line 39 of file gfx_group_editor.h.
Referenced by DrawBlocksetViewer().
roomset_canvas_
gui::Canvas yaze::editor::GfxGroupEditor::roomset_canvas_ private
Definition at line 40 of file gfx_group_editor.h.
Referenced by DrawRoomsetViewer().
spriteset_canvas_
gui::Canvas yaze::editor::GfxGroupEditor::spriteset_canvas_ private
Definition at line 41 of file gfx_group_editor.h.
Referenced by DrawSpritesetViewer().
palette_
gfx::SnesPalette yaze::editor::GfxGroupEditor::palette_ private
Definition at line 43 of file gfx_group_editor.h.
rom_
Rom* yaze::editor::GfxGroupEditor::rom_ = nullptr private
Definition at line 44 of file gfx_group_editor.h.
Referenced by rom(), and set_rom().
The documentation for this class was generated from the following files:
src/app/editor/graphics/gfx_group_editor.h
src/app/editor/graphics/gfx_group_editor.cc