yaze: yaze::zelda3::MockRom Class Reference
yaze::zelda3::MockRom Class Reference
Mock ROM class for testing without real ROM files.
Classes
struct MockPaletteGroup
Public Member Functions
MockRom ()
~MockRom ()=default
absl::Status LoadFromFile (const std::string &filename)
bool is_loaded () const
size_t size () const
uint8_t operator[] (size_t index) const
absl::StatusOr< uint8_t > ReadByte (size_t address) const
absl::StatusOr< uint16_t > ReadWord (size_t address) const
absl::Status ValidateHeader () const
MockPaletteGroup & palette_group ()
const MockPaletteGroup & palette_group () const
Public Member Functions inherited from yaze::Rom
absl::Status LoadFromFile (const std::string &filename, bool z3_load=true)
absl::Status LoadFromData (const std::vector< uint8_t > &data, bool z3_load=true)
absl::Status LoadZelda3 ()
absl::Status LoadGfxGroups ()
absl::Status SaveGfxGroups ()
absl::Status SaveToFile (const SaveSettings &settings)
absl::Status SavePalette (int index, const std::string &group_name, gfx::SnesPalette &palette)
absl::Status SaveAllPalettes ()
void Expand (int size)
void Close ()
absl::StatusOr< uint8_t > ReadByte (int offset)
absl::StatusOr< uint16_t > ReadWord (int offset)
absl::StatusOr< uint32_t > ReadLong (int offset)
absl::StatusOr< std::vector< uint8_t > > ReadByteVector (uint32_t offset, uint32_t length) const
absl::StatusOr< gfx::Tile16 > ReadTile16 (uint32_t tile16_id)
absl::Status WriteTile16 (int tile16_id, const gfx::Tile16 &tile)
absl::Status WriteByte (int addr, uint8_t value)
absl::Status WriteWord (int addr, uint16_t value)
absl::Status WriteShort (int addr, uint16_t value)
absl::Status WriteLong (uint32_t addr, uint32_t value)
absl::Status WriteVector (int addr, std::vector< uint8_t > data)
absl::Status WriteColor (uint32_t address, const gfx::SnesColor &color)
template<typename... Args>
absl::Status WriteTransaction (Args... args)
template<typename T , typename... Args>
absl::Status ReadTransaction (T &var, int address, Args &&... args)
virtual absl::Status WriteHelper (const WriteAction &action)
template<typename T >
absl::Status ReadHelper (T &var, int address)
uint8_t & operator[] (unsigned long i)
bool is_loaded () const
bool dirty () const
void ClearDirty ()
auto title () const
auto size () const
auto data () const
auto mutable_data ()
auto begin ()
auto end ()
auto vector () const
auto filename () const
auto set_filename (std::string_view name)
auto short_name () const
auto graphics_buffer () const
auto mutable_graphics_buffer ()
auto palette_group () const
auto mutable_palette_group ()
auto dungeon_palette (int i)
auto mutable_dungeon_palette (int i)
core::ResourceLabelManager * resource_label ()
zelda3_version_pointers version_constants () const
Private Member Functions
void InitializeMockData ()
void InitializeMockPalettes ()
Private Attributes
std::vector< uint8_t > mock_data_
MockPaletteGroup mock_palette_group_
bool is_loaded_ = false
Additional Inherited Members
Public Attributes inherited from yaze::Rom
std::array< std::array< uint8_t, 8 >, kNumMainBlocksets > main_blockset_ids
std::array< std::array< uint8_t, 4 >, kNumRoomBlocksets > room_blockset_ids
std::array< std::array< uint8_t, 4 >, kNumSpritesets > spriteset_ids
std::array< std::array< uint8_t, 4 >, kNumPalettesets > paletteset_ids
Detailed Description
Mock ROM class for testing without real ROM files.
This class provides a mock ROM implementation that can be used for testing the dungeon object rendering system without requiring actual ROM files.
Definition at line 24 of file dungeon_object_renderer_mock_test.cc.
Constructor & Destructor Documentation
MockRom()
yaze::zelda3::MockRom::MockRom () inline
Definition at line 26 of file dungeon_object_renderer_mock_test.cc.
References InitializeMockData().
~MockRom()
yaze::zelda3::MockRom::~MockRom () default
Member Function Documentation
LoadFromFile()
absl::Status yaze::zelda3::MockRom::LoadFromFile (const std::string & filename) inline
Definition at line 34 of file dungeon_object_renderer_mock_test.cc.
References is_loaded_.
is_loaded()
bool yaze::zelda3::MockRom::is_loaded () const inline
Definition at line 40 of file dungeon_object_renderer_mock_test.cc.
References is_loaded_.
size()
size_t yaze::zelda3::MockRom::size () const inline
Definition at line 42 of file dungeon_object_renderer_mock_test.cc.
References mock_data_.
operator[]()
uint8_t yaze::zelda3::MockRom::operator[] (size_t index) const inline
Definition at line 44 of file dungeon_object_renderer_mock_test.cc.
References mock_data_.
ReadByte()
absl::StatusOr< uint8_t > yaze::zelda3::MockRom::ReadByte (size_t address) const inline
Definition at line 51 of file dungeon_object_renderer_mock_test.cc.
References mock_data_.
ReadWord()
absl::StatusOr< uint16_t > yaze::zelda3::MockRom::ReadWord (size_t address) const inline
Definition at line 58 of file dungeon_object_renderer_mock_test.cc.
References mock_data_, and yaze::Rom::vector().
ValidateHeader()
absl::Status yaze::zelda3::MockRom::ValidateHeader () const inline
Definition at line 66 of file dungeon_object_renderer_mock_test.cc.
palette_group() [1/2]
MockPaletteGroup & yaze::zelda3::MockRom::palette_group () inline
Definition at line 76 of file dungeon_object_renderer_mock_test.cc.
References mock_palette_group_.
palette_group() [2/2]
const MockPaletteGroup & yaze::zelda3::MockRom::palette_group () const inline
Definition at line 77 of file dungeon_object_renderer_mock_test.cc.
References mock_palette_group_.
InitializeMockData()
void yaze::zelda3::MockRom::InitializeMockData () inline private
Definition at line 80 of file dungeon_object_renderer_mock_test.cc.
References InitializeMockPalettes(), is_loaded_, mock_data_, and yaze::Rom::vector().
Referenced by MockRom().
InitializeMockPalettes()
void yaze::zelda3::MockRom::InitializeMockPalettes () inline private
Definition at line 122 of file dungeon_object_renderer_mock_test.cc.
References yaze::gfx::SnesPalette::AddColor(), mock_palette_group_, yaze::zelda3::MockRom::MockPaletteGroup::palettes, and yaze::Rom::vector().
Referenced by InitializeMockData().
Member Data Documentation
mock_data_
std::vector<uint8_t> yaze::zelda3::MockRom::mock_data_ private
Definition at line 137 of file dungeon_object_renderer_mock_test.cc.
Referenced by InitializeMockData(), operator[](), ReadByte(), ReadWord(), and size().
mock_palette_group_
MockPaletteGroup yaze::zelda3::MockRom::mock_palette_group_ private
Definition at line 138 of file dungeon_object_renderer_mock_test.cc.
Referenced by InitializeMockPalettes(), palette_group(), and palette_group().
is_loaded_
bool yaze::zelda3::MockRom::is_loaded_ = false private
Definition at line 139 of file dungeon_object_renderer_mock_test.cc.
Referenced by InitializeMockData(), is_loaded(), and LoadFromFile().
The documentation for this class was generated from the following file:
test/unit/zelda3/dungeon_object_renderer_mock_test.cc