yaze: yaze::emu::ui::anonymous_namespace{debugger_ui.cc} Namespace Reference
yaze::emu::ui::anonymous_namespace{debugger_ui.cc} Namespace Reference
Functions
void AddSpacing ()
void AddSectionSpacing ()
Variables
constexpr float kStandardSpacing = 8.0f
constexpr float kButtonHeight = 30.0f
constexpr float kLargeButtonHeight = 35.0f
Function Documentation
AddSpacing()
void yaze::emu::ui::anonymous_namespace{debugger_ui.cc}::AddSpacing ()
Definition at line 26 of file debugger_ui.cc.
References AddSpacing().
Referenced by AddSpacing().
AddSectionSpacing()
void yaze::emu::ui::anonymous_namespace{debugger_ui.cc}::AddSectionSpacing ()
Definition at line 27 of file debugger_ui.cc.
References AddSectionSpacing().
Referenced by AddSectionSpacing().
Variable Documentation
kStandardSpacing
constexpr float yaze::emu::ui::anonymous_namespace{debugger_ui.cc}::kStandardSpacing = 8.0f constexpr
Definition at line 22 of file debugger_ui.cc.
kButtonHeight
constexpr float yaze::emu::ui::anonymous_namespace{debugger_ui.cc}::kButtonHeight = 30.0f constexpr
Definition at line 23 of file debugger_ui.cc.
kLargeButtonHeight
constexpr float yaze::emu::ui::anonymous_namespace{debugger_ui.cc}::kLargeButtonHeight = 35.0f constexpr
Definition at line 24 of file debugger_ui.cc.