yaze: yaze::gui::canvas::CanvasPerformanceIntegration Class Reference
yaze::gui::canvas::CanvasPerformanceIntegration Class Reference
Canvas performance integration with dashboard.
#include <canvas_performance_integration.h>
Public Member Functions
CanvasPerformanceIntegration ()=default
void Initialize (const std::string &canvas_id)
Initialize performance integration.
void StartMonitoring ()
Start performance monitoring.
void StopMonitoring ()
Stop performance monitoring.
void UpdateMetrics ()
Update performance metrics.
void RecordOperation (const std::string &operation_name, double time_ms, CanvasUsage usage_mode=CanvasUsage::kUnknown)
Record canvas operation.
void RecordMemoryUsage (size_t texture_memory, size_t bitmap_memory, size_t palette_memory)
Record memory usage.
void RecordCachePerformance (int hits, int misses)
Record cache performance.
const CanvasPerformanceMetrics & GetCurrentMetrics () const
Get current performance metrics.
const std::vector< CanvasPerformanceMetrics > & GetPerformanceHistory () const
Get performance history.
std::string GetPerformanceSummary () const
Get performance summary.
std::vector< std::string > GetPerformanceRecommendations () const
Get performance recommendations.
std::string ExportPerformanceReport () const
Export performance report.
void RenderPerformanceUI ()
Render performance UI.
void SetUsageTracker (std::shared_ptr< CanvasUsageTracker > tracker)
Set usage tracker integration.
void SetMonitoringEnabled (bool enabled)
Enable/disable performance monitoring.
bool IsMonitoringEnabled () const
Private Member Functions
void UpdateFrameTime ()
void UpdateDrawTime ()
void UpdateInteractionTime ()
void UpdateModalTime ()
void CalculateCacheHitRatio ()
void SaveCurrentMetrics ()
void AnalyzePerformance ()
void RenderPerformanceOverview ()
void RenderDetailedMetrics ()
void RenderMemoryUsage ()
void RenderOperationCounts ()
void RenderCachePerformance ()
void RenderRecommendations ()
void RenderPerformanceGraph ()
std::string FormatTime (double time_ms) const
std::string FormatMemory (size_t bytes) const
ImVec4 GetPerformanceColor (double value, double threshold_good, double threshold_warning) const
Private Attributes
std::string canvas_id_
bool monitoring_enabled_ = true
CanvasPerformanceMetrics current_metrics_
std::vector< CanvasPerformanceMetrics > performance_history_
std::unique_ptr< gfx::ScopedTimer > frame_timer_
std::unique_ptr< gfx::ScopedTimer > draw_timer_
std::unique_ptr< gfx::ScopedTimer > interaction_timer_
std::unique_ptr< gfx::ScopedTimer > modal_timer_
bool frame_timer_active_ = false
bool draw_timer_active_ = false
bool interaction_timer_active_ = false
bool modal_timer_active_ = false
std::shared_ptr< CanvasUsageTracker > usage_tracker_
gfx::PerformanceDashboard * dashboard_ = nullptr
bool show_performance_ui_ = false
bool show_detailed_metrics_ = false
bool show_recommendations_ = false
Detailed Description
Canvas performance integration with dashboard.
Definition at line 77 of file canvas_performance_integration.h.
Constructor & Destructor Documentation
CanvasPerformanceIntegration()
yaze::gui::canvas::CanvasPerformanceIntegration::CanvasPerformanceIntegration () default
Member Function Documentation
Initialize()
void yaze::gui::canvas::CanvasPerformanceIntegration::Initialize (const std::string & canvas_id)
Initialize performance integration.
Definition at line 17 of file canvas_performance_integration.cc.
References canvas_id_, current_metrics_, dashboard_, yaze::gfx::PerformanceDashboard::Get(), LOG_DEBUG, monitoring_enabled_, and yaze::gui::canvas::CanvasPerformanceMetrics::Reset().
StartMonitoring()
void yaze::gui::canvas::CanvasPerformanceIntegration::StartMonitoring ()
Start performance monitoring.
Definition at line 30 of file canvas_performance_integration.cc.
References canvas_id_, frame_timer_, frame_timer_active_, LOG_DEBUG, and monitoring_enabled_.
StopMonitoring()
void yaze::gui::canvas::CanvasPerformanceIntegration::StopMonitoring ()
Stop performance monitoring.
Definition at line 41 of file canvas_performance_integration.cc.
References canvas_id_, draw_timer_, draw_timer_active_, frame_timer_, frame_timer_active_, interaction_timer_, interaction_timer_active_, LOG_DEBUG, modal_timer_, and modal_timer_active_.
UpdateMetrics()
void yaze::gui::canvas::CanvasPerformanceIntegration::UpdateMetrics ()
Update performance metrics.
Definition at line 64 of file canvas_performance_integration.cc.
References CalculateCacheHitRatio(), monitoring_enabled_, SaveCurrentMetrics(), UpdateDrawTime(), UpdateFrameTime(), UpdateInteractionTime(), and UpdateModalTime().
RecordOperation()
void yaze::gui::canvas::CanvasPerformanceIntegration::RecordOperation (const std::string & operation_name, double time_ms, CanvasUsage usage_mode = CanvasUsage::kUnknown)
Record canvas operation.
Definition at line 91 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::bpp_conversion_operations, yaze::gui::canvas::CanvasPerformanceMetrics::color_paint_operations, current_metrics_, yaze::gui::canvas::kBppConversion, yaze::gui::canvas::kColorPainting, yaze::gui::canvas::kSelectRectangle, yaze::gui::canvas::kTilePainting, yaze::gui::canvas::kTileSelecting, monitoring_enabled_, yaze::gui::canvas::CanvasPerformanceMetrics::rectangle_select_operations, yaze::gui::canvas::CanvasPerformanceMetrics::tile_paint_operations, yaze::gui::canvas::CanvasPerformanceMetrics::tile_select_operations, and usage_tracker_.
RecordMemoryUsage()
void yaze::gui::canvas::CanvasPerformanceIntegration::RecordMemoryUsage (size_t texture_memory, size_t bitmap_memory, size_t palette_memory)
Record memory usage.
Definition at line 126 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::bitmap_memory_mb, current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::palette_memory_mb, and yaze::gui::canvas::CanvasPerformanceMetrics::texture_memory_mb.
RecordCachePerformance()
void yaze::gui::canvas::CanvasPerformanceIntegration::RecordCachePerformance (int hits, int misses)
Record cache performance.
Definition at line 134 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::cache_hits, yaze::gui::canvas::CanvasPerformanceMetrics::cache_misses, CalculateCacheHitRatio(), and current_metrics_.
GetCurrentMetrics()
const CanvasPerformanceMetrics & yaze::gui::canvas::CanvasPerformanceIntegration::GetCurrentMetrics () const inline
Get current performance metrics.
Definition at line 123 of file canvas_performance_integration.h.
References current_metrics_.
GetPerformanceHistory()
const std::vector< CanvasPerformanceMetrics > & yaze::gui::canvas::CanvasPerformanceIntegration::GetPerformanceHistory () const inline
Get performance history.
Definition at line 128 of file canvas_performance_integration.h.
References performance_history_.
GetPerformanceSummary()
std::string yaze::gui::canvas::CanvasPerformanceIntegration::GetPerformanceSummary () const
Get performance summary.
Definition at line 142 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::bitmap_memory_mb, yaze::gui::canvas::CanvasPerformanceMetrics::bitmap_operations, yaze::gui::canvas::CanvasPerformanceMetrics::bpp_conversion_operations, yaze::gui::canvas::CanvasPerformanceMetrics::cache_hit_ratio, yaze::gui::canvas::CanvasPerformanceMetrics::cache_hits, yaze::gui::canvas::CanvasPerformanceMetrics::cache_misses, canvas_id_, yaze::gui::canvas::CanvasPerformanceMetrics::color_paint_operations, current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::draw_calls, yaze::gui::canvas::CanvasPerformanceMetrics::draw_time_ms, FormatMemory(), FormatTime(), yaze::gui::canvas::CanvasPerformanceMetrics::frame_time_ms, yaze::gui::canvas::CanvasPerformanceMetrics::interaction_time_ms, yaze::gui::canvas::CanvasPerformanceMetrics::modal_time_ms, yaze::gui::canvas::CanvasPerformanceMetrics::palette_lookups, yaze::gui::canvas::CanvasPerformanceMetrics::palette_memory_mb, yaze::gui::canvas::CanvasPerformanceMetrics::rectangle_select_operations, yaze::gui::canvas::CanvasPerformanceMetrics::texture_memory_mb, yaze::gui::canvas::CanvasPerformanceMetrics::texture_updates, yaze::gui::canvas::CanvasPerformanceMetrics::tile_paint_operations, and yaze::gui::canvas::CanvasPerformanceMetrics::tile_select_operations.
Referenced by ExportPerformanceReport().
GetPerformanceRecommendations()
std::vector< std::string > yaze::gui::canvas::CanvasPerformanceIntegration::GetPerformanceRecommendations () const
Get performance recommendations.
Definition at line 181 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::bitmap_memory_mb, yaze::gui::canvas::CanvasPerformanceMetrics::cache_hit_ratio, current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::draw_calls, yaze::gui::canvas::CanvasPerformanceMetrics::draw_time_ms, yaze::gui::canvas::CanvasPerformanceMetrics::frame_time_ms, yaze::gui::canvas::CanvasPerformanceMetrics::palette_memory_mb, yaze::gui::canvas::CanvasPerformanceMetrics::texture_memory_mb, and yaze::gui::canvas::CanvasPerformanceMetrics::texture_updates.
Referenced by ExportPerformanceReport(), and RenderRecommendations().
ExportPerformanceReport()
std::string yaze::gui::canvas::CanvasPerformanceIntegration::ExportPerformanceReport () const
Export performance report.
Definition at line 219 of file canvas_performance_integration.cc.
References canvas_id_, FormatMemory(), FormatTime(), GetPerformanceRecommendations(), GetPerformanceSummary(), monitoring_enabled_, and performance_history_.
Referenced by RenderPerformanceUI().
RenderPerformanceUI()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderPerformanceUI ()
Render performance UI.
Definition at line 259 of file canvas_performance_integration.cc.
References ExportPerformanceReport(), monitoring_enabled_, RenderDetailedMetrics(), RenderPerformanceOverview(), RenderRecommendations(), show_detailed_metrics_, show_performance_ui_, and show_recommendations_.
SetUsageTracker()
void yaze::gui::canvas::CanvasPerformanceIntegration::SetUsageTracker (std::shared_ptr< CanvasUsageTracker > tracker)
Set usage tracker integration.
Definition at line 294 of file canvas_performance_integration.cc.
References usage_tracker_.
SetMonitoringEnabled()
void yaze::gui::canvas::CanvasPerformanceIntegration::SetMonitoringEnabled (bool enabled) inline
Enable/disable performance monitoring.
Definition at line 160 of file canvas_performance_integration.h.
References monitoring_enabled_.
IsMonitoringEnabled()
bool yaze::gui::canvas::CanvasPerformanceIntegration::IsMonitoringEnabled () const inline
Definition at line 161 of file canvas_performance_integration.h.
References monitoring_enabled_.
UpdateFrameTime()
void yaze::gui::canvas::CanvasPerformanceIntegration::UpdateFrameTime () private
Definition at line 298 of file canvas_performance_integration.cc.
References current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::frame_time_ms, and frame_timer_.
Referenced by UpdateMetrics().
UpdateDrawTime()
void yaze::gui::canvas::CanvasPerformanceIntegration::UpdateDrawTime () private
Definition at line 305 of file canvas_performance_integration.cc.
References current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::draw_time_ms, and draw_timer_.
Referenced by UpdateMetrics().
UpdateInteractionTime()
void yaze::gui::canvas::CanvasPerformanceIntegration::UpdateInteractionTime () private
Definition at line 312 of file canvas_performance_integration.cc.
References current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::interaction_time_ms, and interaction_timer_.
Referenced by UpdateMetrics().
UpdateModalTime()
void yaze::gui::canvas::CanvasPerformanceIntegration::UpdateModalTime () private
Definition at line 319 of file canvas_performance_integration.cc.
References current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::modal_time_ms, and modal_timer_.
Referenced by UpdateMetrics().
CalculateCacheHitRatio()
void yaze::gui::canvas::CanvasPerformanceIntegration::CalculateCacheHitRatio () private
Definition at line 326 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::cache_hit_ratio, yaze::gui::canvas::CanvasPerformanceMetrics::cache_hits, yaze::gui::canvas::CanvasPerformanceMetrics::cache_misses, and current_metrics_.
Referenced by RecordCachePerformance(), and UpdateMetrics().
SaveCurrentMetrics()
void yaze::gui::canvas::CanvasPerformanceIntegration::SaveCurrentMetrics () private
Definition at line 335 of file canvas_performance_integration.cc.
References current_metrics_, and performance_history_.
Referenced by UpdateMetrics().
AnalyzePerformance()
void yaze::gui::canvas::CanvasPerformanceIntegration::AnalyzePerformance () private
Definition at line 344 of file canvas_performance_integration.cc.
References canvas_id_, LOG_DEBUG, and performance_history_.
RenderPerformanceOverview()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderPerformanceOverview () private
Definition at line 376 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::bitmap_memory_mb, yaze::gui::canvas::CanvasPerformanceMetrics::cache_hit_ratio, current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::draw_time_ms, FormatMemory(), FormatTime(), yaze::gui::canvas::CanvasPerformanceMetrics::frame_time_ms, GetPerformanceColor(), yaze::gui::canvas::CanvasPerformanceMetrics::palette_memory_mb, and yaze::gui::canvas::CanvasPerformanceMetrics::texture_memory_mb.
Referenced by RenderPerformanceUI().
RenderDetailedMetrics()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderDetailedMetrics () private
Definition at line 400 of file canvas_performance_integration.cc.
References RenderCachePerformance(), RenderMemoryUsage(), and RenderOperationCounts().
Referenced by RenderPerformanceUI().
RenderMemoryUsage()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderMemoryUsage () private
Definition at line 414 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::bitmap_memory_mb, current_metrics_, FormatMemory(), yaze::gui::canvas::CanvasPerformanceMetrics::palette_memory_mb, and yaze::gui::canvas::CanvasPerformanceMetrics::texture_memory_mb.
Referenced by RenderDetailedMetrics().
RenderOperationCounts()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderOperationCounts () private
Definition at line 427 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::bitmap_operations, yaze::gui::canvas::CanvasPerformanceMetrics::bpp_conversion_operations, yaze::gui::canvas::CanvasPerformanceMetrics::color_paint_operations, current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::draw_calls, yaze::gui::canvas::CanvasPerformanceMetrics::palette_lookups, yaze::gui::canvas::CanvasPerformanceMetrics::rectangle_select_operations, yaze::gui::canvas::CanvasPerformanceMetrics::texture_updates, yaze::gui::canvas::CanvasPerformanceMetrics::tile_paint_operations, and yaze::gui::canvas::CanvasPerformanceMetrics::tile_select_operations.
Referenced by RenderDetailedMetrics().
RenderCachePerformance()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderCachePerformance () private
Definition at line 444 of file canvas_performance_integration.cc.
References yaze::gui::canvas::CanvasPerformanceMetrics::cache_hit_ratio, yaze::gui::canvas::CanvasPerformanceMetrics::cache_hits, yaze::gui::canvas::CanvasPerformanceMetrics::cache_misses, and current_metrics_.
Referenced by RenderDetailedMetrics().
RenderRecommendations()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderRecommendations () private
Definition at line 455 of file canvas_performance_integration.cc.
References GetPerformanceRecommendations().
Referenced by RenderPerformanceUI().
RenderPerformanceGraph()
void yaze::gui::canvas::CanvasPerformanceIntegration::RenderPerformanceGraph () private
Definition at line 469 of file canvas_performance_integration.cc.
References current_metrics_, yaze::gui::canvas::CanvasPerformanceMetrics::draw_time_ms, and yaze::gui::canvas::CanvasPerformanceMetrics::frame_time_ms.
FormatTime()
std::string yaze::gui::canvas::CanvasPerformanceIntegration::FormatTime (double time_ms) const private
Definition at line 496 of file canvas_performance_integration.cc.
Referenced by ExportPerformanceReport(), GetPerformanceSummary(), and RenderPerformanceOverview().
FormatMemory()
std::string yaze::gui::canvas::CanvasPerformanceIntegration::FormatMemory (size_t bytes) const private
Definition at line 506 of file canvas_performance_integration.cc.
Referenced by ExportPerformanceReport(), GetPerformanceSummary(), RenderMemoryUsage(), and RenderPerformanceOverview().
GetPerformanceColor()
ImVec4 yaze::gui::canvas::CanvasPerformanceIntegration::GetPerformanceColor (double value, double threshold_good, double threshold_warning) const private
Definition at line 516 of file canvas_performance_integration.cc.
Referenced by RenderPerformanceOverview().
Member Data Documentation
canvas_id_
std::string yaze::gui::canvas::CanvasPerformanceIntegration::canvas_id_ private
Definition at line 164 of file canvas_performance_integration.h.
Referenced by AnalyzePerformance(), ExportPerformanceReport(), GetPerformanceSummary(), Initialize(), StartMonitoring(), and StopMonitoring().
monitoring_enabled_
bool yaze::gui::canvas::CanvasPerformanceIntegration::monitoring_enabled_ = true private
Definition at line 165 of file canvas_performance_integration.h.
Referenced by ExportPerformanceReport(), Initialize(), IsMonitoringEnabled(), RecordOperation(), RenderPerformanceUI(), SetMonitoringEnabled(), StartMonitoring(), and UpdateMetrics().
current_metrics_
CanvasPerformanceMetrics yaze::gui::canvas::CanvasPerformanceIntegration::current_metrics_ private
Definition at line 166 of file canvas_performance_integration.h.
Referenced by CalculateCacheHitRatio(), GetCurrentMetrics(), GetPerformanceRecommendations(), GetPerformanceSummary(), Initialize(), RecordCachePerformance(), RecordMemoryUsage(), RecordOperation(), RenderCachePerformance(), RenderMemoryUsage(), RenderOperationCounts(), RenderPerformanceGraph(), RenderPerformanceOverview(), SaveCurrentMetrics(), UpdateDrawTime(), UpdateFrameTime(), UpdateInteractionTime(), and UpdateModalTime().
performance_history_
std::vector<CanvasPerformanceMetrics> yaze::gui::canvas::CanvasPerformanceIntegration::performance_history_ private
Definition at line 167 of file canvas_performance_integration.h.
Referenced by AnalyzePerformance(), ExportPerformanceReport(), GetPerformanceHistory(), and SaveCurrentMetrics().
frame_timer_
std::unique_ptr<gfx::ScopedTimer> yaze::gui::canvas::CanvasPerformanceIntegration::frame_timer_ private
Definition at line 170 of file canvas_performance_integration.h.
Referenced by StartMonitoring(), StopMonitoring(), and UpdateFrameTime().
draw_timer_
std::unique_ptr<gfx::ScopedTimer> yaze::gui::canvas::CanvasPerformanceIntegration::draw_timer_ private
Definition at line 171 of file canvas_performance_integration.h.
Referenced by StopMonitoring(), and UpdateDrawTime().
interaction_timer_
std::unique_ptr<gfx::ScopedTimer> yaze::gui::canvas::CanvasPerformanceIntegration::interaction_timer_ private
Definition at line 172 of file canvas_performance_integration.h.
Referenced by StopMonitoring(), and UpdateInteractionTime().
modal_timer_
std::unique_ptr<gfx::ScopedTimer> yaze::gui::canvas::CanvasPerformanceIntegration::modal_timer_ private
Definition at line 173 of file canvas_performance_integration.h.
Referenced by StopMonitoring(), and UpdateModalTime().
frame_timer_active_
bool yaze::gui::canvas::CanvasPerformanceIntegration::frame_timer_active_ = false private
Definition at line 174 of file canvas_performance_integration.h.
Referenced by StartMonitoring(), and StopMonitoring().
draw_timer_active_
bool yaze::gui::canvas::CanvasPerformanceIntegration::draw_timer_active_ = false private
Definition at line 175 of file canvas_performance_integration.h.
Referenced by StopMonitoring().
interaction_timer_active_
bool yaze::gui::canvas::CanvasPerformanceIntegration::interaction_timer_active_ = false private
Definition at line 176 of file canvas_performance_integration.h.
Referenced by StopMonitoring().
modal_timer_active_
bool yaze::gui::canvas::CanvasPerformanceIntegration::modal_timer_active_ = false private
Definition at line 177 of file canvas_performance_integration.h.
Referenced by StopMonitoring().
usage_tracker_
std::shared_ptr<CanvasUsageTracker> yaze::gui::canvas::CanvasPerformanceIntegration::usage_tracker_ private
Definition at line 180 of file canvas_performance_integration.h.
Referenced by RecordOperation(), and SetUsageTracker().
dashboard_
gfx::PerformanceDashboard* yaze::gui::canvas::CanvasPerformanceIntegration::dashboard_ = nullptr private
Definition at line 183 of file canvas_performance_integration.h.
Referenced by Initialize().
show_performance_ui_
bool yaze::gui::canvas::CanvasPerformanceIntegration::show_performance_ui_ = false private
Definition at line 186 of file canvas_performance_integration.h.
Referenced by RenderPerformanceUI().
show_detailed_metrics_
bool yaze::gui::canvas::CanvasPerformanceIntegration::show_detailed_metrics_ = false private
Definition at line 187 of file canvas_performance_integration.h.
Referenced by RenderPerformanceUI().
show_recommendations_
bool yaze::gui::canvas::CanvasPerformanceIntegration::show_recommendations_ = false private
Definition at line 188 of file canvas_performance_integration.h.
Referenced by RenderPerformanceUI().
The documentation for this class was generated from the following files:
src/app/gui/canvas/canvas_performance_integration.h
src/app/gui/canvas/canvas_performance_integration.cc