yaze: yaze::zelda3::Overworld Class Reference
yaze::zelda3::Overworld Class Reference
Represents the full Overworld data, light and dark world.
#include <overworld.h>
Public Member Functions
Overworld (Rom *rom)
absl::Status Load (Rom *rom)
absl::Status LoadOverworldMaps ()
void LoadTileTypes ()
absl::Status LoadEntrances ()
absl::Status LoadHoles ()
absl::Status LoadExits ()
absl::Status LoadItems ()
absl::Status LoadSprites ()
absl::Status LoadSpritesFromMap (int sprite_start, int sprite_count, int sprite_index)
absl::Status EnsureMapBuilt (int map_index)
Build a map on-demand if it hasn't been built yet.
absl::Status Save (Rom *rom)
absl::Status SaveOverworldMaps ()
absl::Status SaveLargeMaps ()
absl::Status SaveLargeMapsExpanded ()
absl::Status SaveSmallAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
absl::Status SaveLargeAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
absl::Status SaveWideAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
absl::Status SaveTallAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
absl::Status SaveEntrances ()
absl::Status SaveExits ()
absl::Status SaveItems ()
absl::Status SaveMapOverlays ()
absl::Status SaveOverworldTilesType ()
absl::Status SaveCustomOverworldASM (bool enable_bg_color, bool enable_main_palette, bool enable_mosaic, bool enable_gfx_groups, bool enable_subscreen_overlay, bool enable_animated)
absl::Status SaveAreaSpecificBGColors ()
absl::Status CreateTile32Tilemap ()
absl::Status SaveMap16Expanded ()
absl::Status SaveMap16Tiles ()
absl::Status SaveMap32Expanded ()
absl::Status SaveMap32Tiles ()
absl::Status SaveMapProperties ()
absl::Status SaveMusic ()
absl::Status SaveAreaSizes ()
void AssignMapSizes (std::vector< OverworldMap > &maps)
Loads all maps from ROM to see what size they are.
auto rom () const
auto mutable_rom ()
void Destroy ()
int GetTileFromPosition (ImVec2 position) const
OverworldBlockset & GetMapTiles (int world_type)
auto overworld_maps () const
auto overworld_map (int i) const
auto mutable_overworld_map (int i)
auto exits () const
auto mutable_exits ()
std::vector< gfx::Tile16 > tiles16 () const
auto tiles32_unique () const
auto mutable_tiles16 ()
auto sprites (int state) const
auto mutable_sprites (int state)
auto current_graphics () const
const std::vector< OverworldEntrance > & entrances () const
auto & entrances ()
auto mutable_entrances ()
const std::vector< OverworldEntrance > & holes () const
auto & holes ()
auto mutable_holes ()
auto deleted_entrances () const
auto mutable_deleted_entrances ()
auto current_area_palette () const
auto current_map_bitmap_data () const
auto tile16_blockset_data () const
auto is_loaded () const
auto expanded_tile16 () const
auto expanded_tile32 () const
auto expanded_entrances () const
void set_current_map (int i)
void set_current_world (int world)
uint16_t GetTile (int x, int y) const
void SetTile (int x, int y, uint16_t tile_id)
auto map_tiles () const
auto mutable_map_tiles ()
auto all_items () const
auto mutable_all_items ()
auto all_tiles_types () const
auto mutable_all_tiles_types ()
auto all_sprites () const
Private Types
enum Dimension { map32TilesTL = 0 , map32TilesTR = 1 , map32TilesBL = 2 , map32TilesBR = 3 }
Private Member Functions
void FetchLargeMaps ()
absl::StatusOr< uint16_t > GetTile16ForTile32 (int index, int quadrant, int dimension, const uint32_t *map32address)
absl::Status AssembleMap32Tiles ()
absl::Status AssembleMap16Tiles ()
void AssignWorldTiles (int x, int y, int sx, int sy, int tpos, OverworldBlockset &world)
void OrganizeMapTiles (std::vector< uint8_t > &bytes, std::vector< uint8_t > &bytes2, int i, int sx, int sy, int &ttpos)
void DecompressAllMapTiles ()
absl::Status DecompressAllMapTilesParallel ()
Private Attributes
Rom * rom_
bool is_loaded_ = false
bool expanded_tile16_ = false
bool expanded_tile32_ = false
bool expanded_entrances_ = false
int game_state_ = 0
int current_map_ = 0
int current_world_ = 0
OverworldMapTiles map_tiles_
std::mutex map_tiles_mutex_
std::vector< OverworldMap > overworld_maps_
std::vector< OverworldEntrance > all_entrances_
std::vector< OverworldEntrance > all_holes_
std::vector< OverworldExit > all_exits_
std::vector< OverworldItem > all_items_
std::vector< gfx::Tile16 > tiles16_
std::vector< gfx::Tile32 > tiles32_
std::vector< gfx::Tile32 > tiles32_unique_
std::vector< uint16_t > tiles32_list_
std::vector< uint64_t > deleted_entrances_
std::array< uint8_t, kNumOverworldMaps > map_parent_ = {0}
std::array< uint8_t, kNumTileTypes > all_tiles_types_ = {0}
std::array< std::vector< Sprite >, 3 > all_sprites_
std::array< std::vector< uint8_t >, kNumOverworldMaps > map_data_p1
std::array< std::vector< uint8_t >, kNumOverworldMaps > map_data_p2
std::array< int, kNumOverworldMaps > map_pointers1_id
std::array< int, kNumOverworldMaps > map_pointers2_id
std::array< int, kNumOverworldMaps > map_pointers1
std::array< int, kNumOverworldMaps > map_pointers2
Detailed Description
Represents the full Overworld data, light and dark world.
This class is responsible for loading and saving the overworld data, as well as creating the tilesets and tilemaps for the overworld.
Definition at line 135 of file overworld.h.
Member Enumeration Documentation
Dimension
enum yaze::zelda3::Overworld::Dimension private
Enumerator
map32TilesTL
map32TilesTR
map32TilesBL
map32TilesBR
Definition at line 310 of file overworld.h.
Constructor & Destructor Documentation
Overworld()
yaze::zelda3::Overworld::Overworld (Rom * rom) inline
Definition at line 137 of file overworld.h.
Member Function Documentation
Load()
absl::Status yaze::zelda3::Overworld::Load (Rom * rom)
Definition at line 27 of file overworld.cc.
References AssembleMap16Tiles(), AssembleMap32Tiles(), AssignMapSizes(), DecompressAllMapTilesParallel(), FetchLargeMaps(), is_loaded_, yaze::zelda3::kNumOverworldMaps, LoadEntrances(), LoadExits(), LoadHoles(), LoadItems(), LoadOverworldMaps(), LoadSprites(), LoadTileTypes(), map_parent_, overworld_maps_, yaze::zelda3::OverworldCustomASMHasBeenApplied, RETURN_IF_ERROR, rom(), and rom_.
Referenced by yaze::cli::Tile16ProposalGenerator::ApplyProposal(), yaze::editor::OverworldEditor::ApplyZSCustomOverworldASM(), OverworldGoldenDataExtractor::ExtractAllData(), yaze::cli::Tile16ProposalGenerator::GenerateDiff(), yaze::cli::agent::HandleOverworldDescribeMapCommand(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldGetEntranceCommand(), yaze::cli::agent::HandleOverworldListSpritesCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandleOverworldTileStatsCommand(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldGraphicsManager::LoadGraphics(), yaze::cli::Tile16ProposalGenerator::ParseReplaceTileCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetAreaCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetTileCommand(), yaze::cli::OverworldGetTile::Run(), yaze::cli::OverworldSetTile::Run(), yaze::cli::OverworldFindTile::Run(), yaze::cli::OverworldDescribeMap::Run(), yaze::cli::OverworldListWarps::Run(), yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest(), yaze::test::RomDependentTestSuite::RunRomOverworldLoadingTest(), yaze::zelda3::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), and yaze::test::TEST_F().
LoadOverworldMaps()
absl::Status yaze::zelda3::Overworld::LoadOverworldMaps ()
Definition at line 454 of file overworld.cc.
References game_state_, GetMapTiles(), yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kSpecialWorldMapIdStart, yaze::util::logf(), overworld_maps_, RETURN_IF_ERROR, and tiles16_.
Referenced by Load().
LoadTileTypes()
void yaze::zelda3::Overworld::LoadTileTypes ()
Definition at line 534 of file overworld.cc.
References all_tiles_types_, yaze::zelda3::kNumTileTypes, and rom().
Referenced by Load().
LoadEntrances()
absl::Status yaze::zelda3::Overworld::LoadEntrances ()
Definition at line 541 of file overworld.cc.
References all_entrances_, ASSIGN_OR_RETURN, expanded_entrances_, yaze::zelda3::kOverworldEntranceEntranceId, yaze::zelda3::kOverworldEntranceEntranceIdExpanded, yaze::zelda3::kOverworldEntranceExpandedFlagPos, yaze::zelda3::kOverworldEntranceMap, yaze::zelda3::kOverworldEntranceMapExpanded, yaze::zelda3::kOverworldEntrancePos, yaze::zelda3::kOverworldEntrancePosExpanded, and rom().
Referenced by Load().
LoadHoles()
absl::Status yaze::zelda3::Overworld::LoadHoles ()
Definition at line 581 of file overworld.cc.
References all_holes_, ASSIGN_OR_RETURN, yaze::zelda3::kOverworldHoleArea, yaze::zelda3::kOverworldHoleEntrance, yaze::zelda3::kOverworldHolePos, and rom().
Referenced by Load().
LoadExits()
absl::Status yaze::zelda3::Overworld::LoadExits ()
Definition at line 601 of file overworld.cc.
References all_exits_, exits(), yaze::zelda3::OWExitDoorType1, yaze::zelda3::OWExitDoorType2, yaze::zelda3::OWExitMapId, yaze::zelda3::OWExitRoomId, yaze::zelda3::OWExitUnk1, yaze::zelda3::OWExitUnk2, yaze::zelda3::OWExitVram, yaze::zelda3::OWExitXCamera, yaze::zelda3::OWExitXPlayer, yaze::zelda3::OWExitXScroll, yaze::zelda3::OWExitYCamera, yaze::zelda3::OWExitYPlayer, yaze::zelda3::OWExitYScroll, RETURN_IF_ERROR, and rom().
Referenced by Load().
LoadItems()
absl::Status yaze::zelda3::Overworld::LoadItems ()
Definition at line 645 of file overworld.cc.
References all_items_, ASSIGN_OR_RETURN, yaze::zelda3::kNumOverworldMaps, overworld_maps_, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::zelda3::overworldItemsAddress, yaze::zelda3::overworldItemsAddressBank, rom(), yaze::zelda3::SmallArea, and yaze::SnesToPc().
Referenced by Load().
LoadSprites()
absl::Status yaze::zelda3::Overworld::LoadSprites ()
Definition at line 712 of file overworld.cc.
References yaze::zelda3::kOverworldSpritesAgahnim, yaze::zelda3::kOverworldSpritesBeginning, yaze::zelda3::kOverworldSpritesZelda, LoadSpritesFromMap(), yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::zelda3::overworldSpritesAgahnimExpanded, yaze::zelda3::overworldSpritesBeginingExpanded, yaze::zelda3::overworldSpritesZeldaExpanded, and RETURN_IF_ERROR.
Referenced by Load().
LoadSpritesFromMap()
absl::Status yaze::zelda3::Overworld::LoadSpritesFromMap (int sprite_start, int sprite_count, int sprite_index)
Definition at line 749 of file overworld.cc.
References all_sprites_, ASSIGN_OR_RETURN, map_parent_, overworld_maps_, rom(), and yaze::SnesToPc().
Referenced by LoadSprites().
EnsureMapBuilt()
absl::Status yaze::zelda3::Overworld::EnsureMapBuilt (int map_index)
Build a map on-demand if it hasn't been built yet.
This method checks if the specified map needs to be built and builds it if necessary. Used for lazy loading optimization.
Definition at line 510 of file overworld.cc.
References game_state_, GetMapTiles(), yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kSpecialWorldMapIdStart, yaze::util::logf(), overworld_maps_, and tiles16_.
Referenced by yaze::cli::overworld::BuildMapSummary(), yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::OverworldEditor::EnsureMapTexture(), and yaze::editor::OverworldGraphicsManager::EnsureMapTexture().
Save()
absl::Status yaze::zelda3::Overworld::Save (Rom * rom)
Definition at line 790 of file overworld.cc.
References expanded_tile16_, expanded_tile32_, RETURN_IF_ERROR, rom(), rom_, SaveAreaSizes(), SaveAreaSpecificBGColors(), SaveEntrances(), SaveExits(), SaveItems(), SaveMap16Expanded(), SaveMap16Tiles(), SaveMap32Expanded(), SaveMap32Tiles(), SaveMapOverlays(), SaveMusic(), SaveOverworldMaps(), and SaveOverworldTilesType().
SaveOverworldMaps()
absl::Status yaze::zelda3::Overworld::SaveOverworldMaps ()
Definition at line 814 of file overworld.cc.
References yaze::util::HexByte(), yaze::util::HexLong(), yaze::gfx::HyruleMagicCompress(), yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kOverworldCompressedMapPos, yaze::zelda3::kOverworldCompressedOverflowPos, yaze::zelda3::kOverworldMapDataOverflow, yaze::util::logf(), map_data_p1, map_data_p2, map_pointers1, map_pointers1_id, map_pointers2, map_pointers2_id, yaze::PcToSnes(), RETURN_IF_ERROR, rom(), SaveLargeMaps(), and tiles32_list_.
Referenced by yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest(), yaze::editor::OverworldEditor::Save(), Save(), and yaze::test::TEST_F().
SaveLargeMaps()
absl::Status yaze::zelda3::Overworld::SaveLargeMaps ()
Definition at line 952 of file overworld.cc.
References yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kNumMapsPerWorld, yaze::zelda3::kOverworldMapParentId, yaze::zelda3::kOverworldMapSize, yaze::zelda3::kOverworldMapSizeHighByte, yaze::zelda3::kOverworldScreenSize, yaze::zelda3::kOverworldScreenSizeForLoading, yaze::zelda3::kOverworldScreenTileMapChangeByScreen1, yaze::zelda3::kOverworldScreenTileMapChangeByScreen2, yaze::zelda3::kOverworldScreenTileMapChangeByScreen3, yaze::zelda3::kOverworldScreenTileMapChangeByScreen4, yaze::zelda3::kOverworldTransitionPositionX, yaze::zelda3::kOverworldTransitionPositionY, yaze::zelda3::kSpecialWorldMapIdStart, yaze::zelda3::kTransitionTargetNorth, yaze::zelda3::kTransitionTargetWest, yaze::util::logf(), overworld_maps_, yaze::zelda3::OverworldCustomASMHasBeenApplied, RETURN_IF_ERROR, rom(), and SaveLargeMapsExpanded().
Referenced by SaveOverworldMaps().
SaveLargeMapsExpanded()
absl::Status yaze::zelda3::Overworld::SaveLargeMapsExpanded ()
Definition at line 1824 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kOverworldMapParentIdExpanded, yaze::zelda3::kOverworldScreenTileMapChangeByScreen1Expanded, yaze::zelda3::kOverworldScreenTileMapChangeByScreen2Expanded, yaze::zelda3::kOverworldScreenTileMapChangeByScreen3Expanded, yaze::zelda3::kOverworldScreenTileMapChangeByScreen4Expanded, yaze::zelda3::kOverworldTransitionPositionXExpanded, yaze::zelda3::kOverworldTransitionPositionYExpanded, yaze::zelda3::LargeArea, yaze::util::logf(), overworld_maps_, RETURN_IF_ERROR, rom(), SaveLargeAreaTransitions(), SaveSmallAreaTransitions(), SaveTallAreaTransitions(), SaveWideAreaTransitions(), yaze::zelda3::SmallArea, yaze::zelda3::TallArea, yaze::zelda3::transition_target_northExpanded, yaze::zelda3::transition_target_westExpanded, and yaze::zelda3::WideArea.
Referenced by SaveLargeMaps().
SaveSmallAreaTransitions()
absl::Status yaze::zelda3::Overworld::SaveSmallAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
Definition at line 1282 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::LargeArea, overworld_maps_, RETURN_IF_ERROR, rom(), yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
Referenced by SaveLargeMapsExpanded().
SaveLargeAreaTransitions()
absl::Status yaze::zelda3::Overworld::SaveLargeAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
Definition at line 1391 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::LargeArea, overworld_maps_, RETURN_IF_ERROR, rom(), yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
Referenced by SaveLargeMapsExpanded().
SaveWideAreaTransitions()
absl::Status yaze::zelda3::Overworld::SaveWideAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
Definition at line 1547 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::LargeArea, overworld_maps_, RETURN_IF_ERROR, rom(), yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
Referenced by SaveLargeMapsExpanded().
SaveTallAreaTransitions()
absl::Status yaze::zelda3::Overworld::SaveTallAreaTransitions (int i, int parent_x_pos, int parent_y_pos, int transition_target_north, int transition_target_west, int transition_pos_x, int transition_pos_y, int screen_change_1, int screen_change_2, int screen_change_3, int screen_change_4)
Definition at line 1687 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::LargeArea, overworld_maps_, RETURN_IF_ERROR, rom(), yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
Referenced by SaveLargeMapsExpanded().
SaveEntrances()
absl::Status yaze::zelda3::Overworld::SaveEntrances ()
Definition at line 2426 of file overworld.cc.
References all_entrances_, all_holes_, expanded_entrances_, yaze::zelda3::kNumOverworldEntrances, yaze::zelda3::kNumOverworldHoles, yaze::zelda3::kOverworldEntranceEntranceId, yaze::zelda3::kOverworldEntranceEntranceIdExpanded, yaze::zelda3::kOverworldEntranceMap, yaze::zelda3::kOverworldEntranceMapExpanded, yaze::zelda3::kOverworldEntrancePos, yaze::zelda3::kOverworldEntrancePosExpanded, yaze::zelda3::kOverworldHoleArea, yaze::zelda3::kOverworldHoleEntrance, yaze::zelda3::kOverworldHolePos, yaze::util::logf(), RETURN_IF_ERROR, and rom().
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveExits()
absl::Status yaze::zelda3::Overworld::SaveExits ()
Todo:
Implement SpecialUpdatePosition for OverworldExit
Definition at line 2462 of file overworld.cc.
References all_exits_, yaze::zelda3::kNumOverworldExits, yaze::util::logf(), yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::zelda3::OWExitDoorType1, yaze::zelda3::OWExitDoorType2, yaze::zelda3::OWExitMapId, yaze::zelda3::OWExitRoomId, yaze::zelda3::OWExitUnk1, yaze::zelda3::OWExitUnk2, yaze::zelda3::OWExitVram, yaze::zelda3::OWExitXCamera, yaze::zelda3::OWExitXPlayer, yaze::zelda3::OWExitXScroll, yaze::zelda3::OWExitYCamera, yaze::zelda3::OWExitYPlayer, yaze::zelda3::OWExitYScroll, RETURN_IF_ERROR, and rom().
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveItems()
absl::Status yaze::zelda3::Overworld::SaveItems ()
Definition at line 2538 of file overworld.cc.
References all_items_, yaze::zelda3::kNumOverworldMapItemPointers, yaze::zelda3::kOverworldItemsEndData, yaze::zelda3::kOverworldItemsPointers, yaze::util::logf(), yaze::PcToSnes(), RETURN_IF_ERROR, and rom().
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveMapOverlays()
absl::Status yaze::zelda3::Overworld::SaveMapOverlays ()
Definition at line 2616 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kOverlayCodeStart, yaze::util::logf(), overworld_maps_, yaze::PcToSnes(), RETURN_IF_ERROR, and rom().
Referenced by Save().
SaveOverworldTilesType()
absl::Status yaze::zelda3::Overworld::SaveOverworldTilesType ()
Definition at line 2688 of file overworld.cc.
References all_tiles_types_, yaze::zelda3::kNumTileTypes, yaze::util::logf(), yaze::zelda3::overworldTilesType, RETURN_IF_ERROR, and rom().
Referenced by Save().
SaveCustomOverworldASM()
absl::Status yaze::zelda3::Overworld::SaveCustomOverworldASM (bool enable_bg_color, bool enable_main_palette, bool enable_mosaic, bool enable_gfx_groups, bool enable_subscreen_overlay, bool enable_animated)
Definition at line 2699 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::util::logf(), overworld_maps_, yaze::zelda3::OverworldCustomAnimatedGFXArray, yaze::zelda3::OverworldCustomAnimatedGFXEnabled, yaze::zelda3::OverworldCustomAreaSpecificBGEnabled, yaze::zelda3::OverworldCustomMainPaletteArray, yaze::zelda3::OverworldCustomMainPaletteEnabled, yaze::zelda3::OverworldCustomMosaicArray, yaze::zelda3::OverworldCustomMosaicEnabled, yaze::zelda3::OverworldCustomSubscreenOverlayArray, yaze::zelda3::OverworldCustomSubscreenOverlayEnabled, yaze::zelda3::OverworldCustomTileGFXGroupArray, yaze::zelda3::OverworldCustomTileGFXGroupEnabled, RETURN_IF_ERROR, and rom().
Referenced by yaze::editor::OverworldEditorManager::ApplyCustomOverworldASM().
SaveAreaSpecificBGColors()
absl::Status yaze::zelda3::Overworld::SaveAreaSpecificBGColors ()
Definition at line 2771 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::util::logf(), overworld_maps_, yaze::zelda3::OverworldCustomAreaSpecificBGPalette, RETURN_IF_ERROR, and rom().
Referenced by Save().
CreateTile32Tilemap()
absl::Status yaze::zelda3::Overworld::CreateTile32Tilemap ()
Definition at line 1952 of file overworld.cc.
References yaze::core::FeatureFlags::get(), yaze::gfx::Tile32::GetPackedValue(), yaze::zelda3::LimitOfMap32, map_tiles_, yaze::zelda3::NumberOfMap32, tiles32_list_, and tiles32_unique_.
Referenced by yaze::editor::OverworldEditor::Save().
SaveMap16Expanded()
absl::Status yaze::zelda3::Overworld::SaveMap16Expanded ()
Definition at line 2310 of file overworld.cc.
References yaze::zelda3::kMap16TilesExpanded, yaze::zelda3::NumberOfMap16Ex, yaze::PcToSnes(), RETURN_IF_ERROR, rom(), yaze::SnesToPc(), and tiles16_.
Referenced by Save().
SaveMap16Tiles()
absl::Status yaze::zelda3::Overworld::SaveMap16Tiles ()
Definition at line 2405 of file overworld.cc.
References yaze::zelda3::kMap16Tiles, yaze::util::logf(), yaze::zelda3::NumberOfMap16, RETURN_IF_ERROR, rom(), and tiles16_.
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveMap32Expanded()
absl::Status yaze::zelda3::Overworld::SaveMap32Expanded ()
Definition at line 2012 of file overworld.cc.
References yaze::zelda3::kMap32TileBLExpanded, yaze::zelda3::kMap32TileBRExpanded, yaze::zelda3::kMap32TileTRExpanded, yaze::PcToSnes(), RETURN_IF_ERROR, rom(), and tiles32_unique_.
Referenced by Save().
SaveMap32Tiles()
absl::Status yaze::zelda3::Overworld::SaveMap32Tiles ()
Definition at line 2181 of file overworld.cc.
References yaze::util::logf(), map32TilesBL, map32TilesBR, RETURN_IF_ERROR, rom(), and tiles32_unique_.
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveMapProperties()
absl::Status yaze::zelda3::Overworld::SaveMapProperties ()
Definition at line 2784 of file overworld.cc.
References yaze::zelda3::kAreaGfxIdPtr, yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kOverworldMapPaletteIds, yaze::zelda3::kOverworldSpritePaletteIds, yaze::zelda3::kOverworldSpriteset, yaze::zelda3::kSpecialWorldMapIdStart, yaze::util::logf(), overworld_maps_, RETURN_IF_ERROR, and rom().
Referenced by yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest(), yaze::editor::OverworldEditor::Save(), and yaze::test::TEST_F().
SaveMusic()
absl::Status yaze::zelda3::Overworld::SaveMusic ()
Definition at line 2835 of file overworld.cc.
References yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kOverworldMusicAgahnim, yaze::zelda3::kOverworldMusicBeginning, yaze::zelda3::kOverworldMusicDarkWorld, yaze::zelda3::kOverworldMusicMasterSword, yaze::zelda3::kOverworldMusicZelda, yaze::zelda3::kSpecialWorldMapIdStart, yaze::util::logf(), overworld_maps_, RETURN_IF_ERROR, and rom().
Referenced by yaze::editor::OverworldEditor::Save(), and Save().
SaveAreaSizes()
absl::Status yaze::zelda3::Overworld::SaveAreaSizes ()
Definition at line 2860 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kOverworldMessagesExpanded, yaze::zelda3::kOverworldScreenSize, yaze::util::logf(), overworld_maps_, yaze::zelda3::OverworldCustomASMHasBeenApplied, RETURN_IF_ERROR, and rom().
Referenced by Save().
AssignMapSizes()
void yaze::zelda3::Overworld::AssignMapSizes (std::vector< OverworldMap > & maps)
Loads all maps from ROM to see what size they are.
Parameters
maps The maps to update (passed by reference)
Definition at line 169 of file overworld.cc.
References yaze::zelda3::kNumOverworldMaps, yaze::zelda3::LargeArea, yaze::zelda3::SmallArea, yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
Referenced by Load().
rom()
auto yaze::zelda3::Overworld::rom () const inline
Definition at line 204 of file overworld.h.
References rom_.
Referenced by AssembleMap16Tiles(), AssembleMap32Tiles(), DecompressAllMapTilesParallel(), GetTile16ForTile32(), Load(), LoadEntrances(), LoadExits(), LoadHoles(), LoadItems(), LoadSpritesFromMap(), LoadTileTypes(), Save(), SaveAreaSizes(), SaveAreaSpecificBGColors(), SaveCustomOverworldASM(), SaveEntrances(), SaveExits(), SaveItems(), SaveLargeAreaTransitions(), SaveLargeMaps(), SaveLargeMapsExpanded(), SaveMap16Expanded(), SaveMap16Tiles(), SaveMap32Expanded(), SaveMap32Tiles(), SaveMapOverlays(), SaveMapProperties(), SaveMusic(), SaveOverworldMaps(), SaveOverworldTilesType(), SaveSmallAreaTransitions(), SaveTallAreaTransitions(), and SaveWideAreaTransitions().
mutable_rom()
auto yaze::zelda3::Overworld::mutable_rom () inline
Definition at line 205 of file overworld.h.
References rom_.
Destroy()
void yaze::zelda3::Overworld::Destroy () inline
Definition at line 207 of file overworld.h.
References all_entrances_, all_exits_, all_items_, all_sprites_, is_loaded_, overworld_maps_, sprites(), tiles16_, tiles32_, and tiles32_unique_.
Referenced by yaze::editor::OverworldEditor::Clear().
GetTileFromPosition()
int yaze::zelda3::Overworld::GetTileFromPosition (ImVec2 position) const inline
Definition at line 224 of file overworld.h.
References current_world_, yaze::zelda3::OverworldMapTiles::dark_world, yaze::zelda3::OverworldMapTiles::light_world, map_tiles_, and yaze::zelda3::OverworldMapTiles::special_world.
Referenced by yaze::editor::OverworldEditor::CheckForSelectRectangle(), and yaze::editor::OverworldEditor::SaveCurrentSelectionToScratch().
GetMapTiles()
OverworldBlockset & yaze::zelda3::Overworld::GetMapTiles (int world_type) inline
Definition at line 234 of file overworld.h.
References yaze::zelda3::OverworldMapTiles::dark_world, yaze::zelda3::OverworldMapTiles::light_world, map_tiles_, and yaze::zelda3::OverworldMapTiles::special_world.
Referenced by EnsureMapBuilt(), LoadOverworldMaps(), yaze::editor::OverworldEditor::RefreshChildMap(), yaze::editor::OverworldGraphicsManager::RefreshChildMap(), yaze::editor::OverworldEditor::RefreshChildMapOnDemand(), yaze::editor::OverworldGraphicsManager::RefreshChildMapOnDemand(), yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), and yaze::editor::OverworldGraphicsManager::RefreshMultiAreaMapsSafely().
overworld_maps()
auto yaze::zelda3::Overworld::overworld_maps () const inline
Definition at line 247 of file overworld.h.
References overworld_maps_.
Referenced by yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), and OverworldGoldenDataExtractor::WriteOverworldMapsData().
overworld_map()
auto yaze::zelda3::Overworld::overworld_map (int i) const inline
Definition at line 248 of file overworld.h.
References overworld_maps_.
Referenced by yaze::cli::overworld::BuildMapSummary(), yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::MapPropertiesSystem::DrawCustomBackgroundColorEditor(), yaze::editor::MapPropertiesSystem::DrawCustomFeaturesTab(), yaze::editor::MapPropertiesSystem::DrawOverlayControls(), yaze::editor::MapPropertiesSystem::DrawOverlayEditor(), yaze::editor::MapPropertiesSystem::DrawOverlayPreviewOnMap(), yaze::editor::OverworldEditor::DrawOverworldProperties(), yaze::editor::MapPropertiesSystem::DrawPropertiesPopup(), yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings(), yaze::editor::OverworldEditor::RefreshMapPalette(), yaze::editor::OverworldGraphicsManager::RefreshMapPalette(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), yaze::editor::OverworldGraphicsManager::RefreshTile16Blockset(), yaze::zelda3::TEST_F(), and yaze::test::TEST_F().
mutable_overworld_map()
auto yaze::zelda3::Overworld::mutable_overworld_map (int i) inline
Definition at line 249 of file overworld.h.
References overworld_maps_.
Referenced by yaze::editor::OverworldEditorManager::DrawAreaSizeControls(), yaze::editor::OverworldEditorManager::DrawAreaSpecificSettings(), yaze::editor::MapPropertiesSystem::DrawBasicPropertiesTab(), yaze::editor::MapPropertiesSystem::DrawCustomBackgroundColorEditor(), yaze::editor::MapPropertiesSystem::DrawCustomFeaturesTab(), yaze::editor::OverworldEditorManager::DrawGfxGroupControls(), yaze::editor::MapPropertiesSystem::DrawGraphicsPopup(), yaze::editor::OverworldEditorManager::DrawMosaicControls(), yaze::editor::MapPropertiesSystem::DrawMosaicControls(), yaze::editor::MapPropertiesSystem::DrawMusicTab(), yaze::editor::MapPropertiesSystem::DrawOverlayControls(), yaze::editor::MapPropertiesSystem::DrawOverlayEditor(), yaze::editor::OverworldEditorManager::DrawOverlaySettings(), yaze::editor::MapPropertiesSystem::DrawPalettesPopup(), yaze::editor::MapPropertiesSystem::DrawPropertiesPopup(), yaze::editor::MapPropertiesSystem::DrawSimplifiedMapSettings(), yaze::editor::MapPropertiesSystem::DrawSpritePropertiesTab(), yaze::editor::MapPropertiesSystem::DrawTileGraphicsTab(), yaze::editor::OverworldEditor::DrawToolset(), yaze::editor::OverworldGraphicsManager::ForceRefreshGraphics(), yaze::editor::OverworldEditor::RefreshChildMap(), yaze::editor::OverworldGraphicsManager::RefreshChildMap(), yaze::editor::OverworldEditor::RefreshChildMapOnDemand(), yaze::editor::OverworldGraphicsManager::RefreshChildMapOnDemand(), yaze::editor::OverworldEditor::RefreshMapPalette(), yaze::editor::OverworldGraphicsManager::RefreshMapPalette(), yaze::editor::OverworldEditor::RefreshMapProperties(), yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), yaze::editor::OverworldGraphicsManager::RefreshMultiAreaMapsSafely(), yaze::editor::MapPropertiesSystem::RefreshSiblingMapGraphics(), yaze::editor::OverworldEditor::RefreshSiblingMapGraphics(), yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest(), and yaze::test::TEST_F().
exits()
auto yaze::zelda3::Overworld::exits () const inline
Definition at line 250 of file overworld.h.
References all_exits_.
Referenced by LoadExits(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), and OverworldGoldenDataExtractor::WriteExitData().
mutable_exits()
auto yaze::zelda3::Overworld::mutable_exits () inline
Definition at line 251 of file overworld.h.
References all_exits_.
Referenced by yaze::editor::OverworldEntityRenderer::DrawExits().
tiles16()
std::vector< gfx::Tile16 > yaze::zelda3::Overworld::tiles16 () const inline
Definition at line 252 of file overworld.h.
References tiles16_.
Referenced by yaze::editor::OverworldEditor::RefreshChildMap(), yaze::editor::OverworldGraphicsManager::RefreshChildMap(), yaze::editor::OverworldEditor::RefreshChildMapOnDemand(), yaze::editor::OverworldGraphicsManager::RefreshChildMapOnDemand(), yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), yaze::editor::OverworldGraphicsManager::RefreshMultiAreaMapsSafely(), and OverworldGoldenDataExtractor::WriteTileData().
tiles32_unique()
auto yaze::zelda3::Overworld::tiles32_unique () const inline
Definition at line 253 of file overworld.h.
References tiles32_unique_.
Referenced by OverworldGoldenDataExtractor::WriteTileData().
mutable_tiles16()
auto yaze::zelda3::Overworld::mutable_tiles16 () inline
Definition at line 254 of file overworld.h.
References tiles16_.
Referenced by yaze::editor::OverworldEditor::RefreshChildMap(), yaze::editor::OverworldGraphicsManager::RefreshChildMap(), yaze::editor::OverworldEditor::RefreshChildMapOnDemand(), yaze::editor::OverworldGraphicsManager::RefreshChildMapOnDemand(), yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), and yaze::editor::OverworldGraphicsManager::RefreshMultiAreaMapsSafely().
sprites()
auto yaze::zelda3::Overworld::sprites (int state) const inline
Definition at line 255 of file overworld.h.
References all_sprites_.
Referenced by yaze::cli::overworld::CollectOverworldSprites(), and Destroy().
mutable_sprites()
auto yaze::zelda3::Overworld::mutable_sprites (int state) inline
Definition at line 256 of file overworld.h.
References all_sprites_.
Referenced by yaze::editor::OverworldEntityRenderer::DrawSprites(), yaze::editor::OverworldEditor::LoadSpriteGraphics(), and yaze::editor::OverworldGraphicsManager::LoadSpriteGraphics().
current_graphics()
auto yaze::zelda3::Overworld::current_graphics () const inline
Definition at line 257 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::OverworldEditor::LoadGraphics(), and yaze::editor::OverworldGraphicsManager::LoadGraphics().
entrances() [1/2]
const std::vector< OverworldEntrance > & yaze::zelda3::Overworld::entrances () const inline
Definition at line 260 of file overworld.h.
References all_entrances_.
Referenced by yaze::cli::overworld::CollectWarpEntries(), yaze::editor::OverworldEntityRenderer::DrawEntrances(), yaze::cli::overworld::GetEntranceDetails(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::editor::OverworldEditor::UpdateUsageStats(), and OverworldGoldenDataExtractor::WriteEntranceData().
entrances() [2/2]
auto & yaze::zelda3::Overworld::entrances () inline
Definition at line 261 of file overworld.h.
References all_entrances_.
mutable_entrances()
auto yaze::zelda3::Overworld::mutable_entrances () inline
Definition at line 262 of file overworld.h.
References all_entrances_.
holes() [1/2]
const std::vector< OverworldEntrance > & yaze::zelda3::Overworld::holes () const inline
Definition at line 263 of file overworld.h.
References all_holes_.
Referenced by yaze::cli::overworld::CollectWarpEntries(), yaze::test::TEST_F(), yaze::test::TEST_F(), and OverworldGoldenDataExtractor::WriteHoleData().
holes() [2/2]
auto & yaze::zelda3::Overworld::holes () inline
Definition at line 264 of file overworld.h.
References all_holes_.
mutable_holes()
auto yaze::zelda3::Overworld::mutable_holes () inline
Definition at line 265 of file overworld.h.
References all_holes_.
deleted_entrances()
auto yaze::zelda3::Overworld::deleted_entrances () const inline
Definition at line 266 of file overworld.h.
References deleted_entrances_.
Referenced by yaze::editor::OverworldEntityRenderer::DrawEntrances().
mutable_deleted_entrances()
auto yaze::zelda3::Overworld::mutable_deleted_entrances () inline
Definition at line 267 of file overworld.h.
References deleted_entrances_.
Referenced by yaze::editor::OverworldEntityRenderer::DrawEntrances().
current_area_palette()
auto yaze::zelda3::Overworld::current_area_palette () const inline
Definition at line 268 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::OverworldEditor::DrawScratchSpace(), yaze::editor::OverworldEditor::EnsureMapTexture(), yaze::editor::OverworldGraphicsManager::EnsureMapTexture(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldGraphicsManager::LoadGraphics(), yaze::editor::OverworldEditor::RefreshMapPalette(), yaze::editor::OverworldGraphicsManager::RefreshMapPalette(), yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), yaze::editor::OverworldGraphicsManager::RefreshMultiAreaMapsSafely(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), yaze::editor::OverworldGraphicsManager::RefreshTile16Blockset(), and yaze::editor::OverworldEditor::SaveCurrentSelectionToScratch().
current_map_bitmap_data()
auto yaze::zelda3::Overworld::current_map_bitmap_data () const inline
Definition at line 271 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::EnsureMapTexture(), yaze::editor::OverworldGraphicsManager::EnsureMapTexture(), yaze::editor::OverworldEditor::LoadGraphics(), and yaze::editor::OverworldGraphicsManager::LoadGraphics().
tile16_blockset_data()
auto yaze::zelda3::Overworld::tile16_blockset_data () const inline
Definition at line 274 of file overworld.h.
References current_map_, and overworld_maps_.
Referenced by yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldGraphicsManager::LoadGraphics(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), and yaze::editor::OverworldGraphicsManager::RefreshTile16Blockset().
is_loaded()
auto yaze::zelda3::Overworld::is_loaded () const inline
Definition at line 277 of file overworld.h.
References is_loaded_.
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::MapPropertiesSystem::DrawCustomBackgroundColorEditor(), yaze::editor::MapPropertiesSystem::DrawMapPropertiesPanel(), yaze::editor::MapPropertiesSystem::DrawOverlayEditor(), yaze::editor::OverworldEditor::DrawOverworldCanvas(), yaze::test::TEST_F(), yaze::test::TEST_F(), and yaze::editor::OverworldEditor::Update().
expanded_tile16()
auto yaze::zelda3::Overworld::expanded_tile16 () const inline
Definition at line 278 of file overworld.h.
References expanded_tile16_.
Referenced by yaze::test::TEST_F(), yaze::test::TEST_F(), and OverworldGoldenDataExtractor::WriteTileData().
expanded_tile32()
auto yaze::zelda3::Overworld::expanded_tile32 () const inline
Definition at line 279 of file overworld.h.
References expanded_tile32_.
Referenced by yaze::test::TEST_F(), yaze::test::TEST_F(), and OverworldGoldenDataExtractor::WriteTileData().
expanded_entrances()
auto yaze::zelda3::Overworld::expanded_entrances () const inline
Definition at line 280 of file overworld.h.
References expanded_entrances_.
set_current_map()
void yaze::zelda3::Overworld::set_current_map (int i) inline
Definition at line 281 of file overworld.h.
References current_map_.
Referenced by yaze::editor::OverworldEditor::CheckForSelectRectangle(), yaze::editor::OverworldEditor::Copy(), yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::OverworldEditor::EnsureMapTexture(), yaze::editor::OverworldGraphicsManager::EnsureMapTexture(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::editor::OverworldGraphicsManager::LoadGraphics(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), yaze::editor::OverworldGraphicsManager::RefreshTile16Blockset(), and yaze::editor::OverworldEditor::SaveCurrentSelectionToScratch().
set_current_world()
void yaze::zelda3::Overworld::set_current_world (int world) inline
Definition at line 282 of file overworld.h.
References current_world_.
Referenced by yaze::cli::Tile16ProposalGenerator::ApplyProposal(), yaze::editor::OverworldEditor::CheckForSelectRectangle(), yaze::editor::OverworldEditor::Copy(), yaze::cli::overworld::FindTileMatches(), yaze::cli::Tile16ProposalGenerator::GenerateDiff(), yaze::cli::Tile16ProposalGenerator::ParseReplaceTileCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetAreaCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetTileCommand(), yaze::cli::OverworldSetTile::Run(), and yaze::editor::OverworldEditor::SaveCurrentSelectionToScratch().
GetTile()
uint16_t yaze::zelda3::Overworld::GetTile (int x, int y) const inline
Definition at line 283 of file overworld.h.
References current_world_, yaze::zelda3::OverworldMapTiles::dark_world, yaze::zelda3::OverworldMapTiles::light_world, map_tiles_, and yaze::zelda3::OverworldMapTiles::special_world.
Referenced by yaze::editor::OverworldEditor::Copy(), E2ETest_CanvasSelectionTest(), yaze::cli::overworld::FindTileMatches(), yaze::cli::Tile16ProposalGenerator::GenerateDiff(), yaze::cli::Tile16ProposalGenerator::ParseReplaceTileCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetAreaCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetTileCommand(), and yaze::cli::OverworldGetTile::Run().
SetTile()
void yaze::zelda3::Overworld::SetTile (int x, int y, uint16_t tile_id) inline
Definition at line 292 of file overworld.h.
References current_world_, yaze::zelda3::OverworldMapTiles::dark_world, yaze::zelda3::OverworldMapTiles::light_world, map_tiles_, and yaze::zelda3::OverworldMapTiles::special_world.
Referenced by yaze::cli::Tile16ProposalGenerator::ApplyProposal(), and yaze::cli::OverworldSetTile::Run().
map_tiles()
auto yaze::zelda3::Overworld::map_tiles () const inline
Definition at line 301 of file overworld.h.
References map_tiles_.
Referenced by OverworldGoldenDataExtractor::WriteMapTilesData().
mutable_map_tiles()
auto yaze::zelda3::Overworld::mutable_map_tiles () inline
Definition at line 302 of file overworld.h.
References map_tiles_.
Referenced by yaze::editor::OverworldEditor::CheckForOverworldEdits(), yaze::editor::OverworldEditor::DrawDebugWindow(), yaze::editor::OverworldEditor::DrawOverworldEdits(), and yaze::editor::OverworldEditor::Paste().
all_items()
auto yaze::zelda3::Overworld::all_items () const inline
Definition at line 303 of file overworld.h.
References all_items_.
Referenced by yaze::test::TEST_F(), yaze::test::TEST_F(), and OverworldGoldenDataExtractor::WriteItemData().
mutable_all_items()
auto yaze::zelda3::Overworld::mutable_all_items () inline
Definition at line 304 of file overworld.h.
References all_items_.
Referenced by yaze::editor::OverworldEntityRenderer::DrawItems().
all_tiles_types()
auto yaze::zelda3::Overworld::all_tiles_types () const inline
Definition at line 305 of file overworld.h.
References all_tiles_types_.
mutable_all_tiles_types()
auto yaze::zelda3::Overworld::mutable_all_tiles_types () inline
Definition at line 306 of file overworld.h.
References all_tiles_types_.
Referenced by yaze::editor::OverworldEditor::Load().
all_sprites()
auto yaze::zelda3::Overworld::all_sprites () const inline
Definition at line 307 of file overworld.h.
References all_sprites_.
Referenced by yaze::test::TEST_F(), yaze::test::TEST_F(), and OverworldGoldenDataExtractor::WriteSpriteData().
FetchLargeMaps()
void yaze::zelda3::Overworld::FetchLargeMaps () private
Definition at line 112 of file overworld.cc.
References overworld_maps_.
Referenced by Load().
GetTile16ForTile32()
absl::StatusOr< uint16_t > yaze::zelda3::Overworld::GetTile16ForTile32 (int index, int quadrant, int dimension, const uint32_t * map32address) private
Definition at line 249 of file overworld.cc.
References ASSIGN_OR_RETURN, and rom().
Referenced by AssembleMap32Tiles().
AssembleMap32Tiles()
absl::Status yaze::zelda3::Overworld::AssembleMap32Tiles () private
Definition at line 260 of file overworld.cc.
References ASSIGN_OR_RETURN, yaze::zelda3::OverworldMapTiles::dark_world, expanded_tile32_, GetTile16ForTile32(), yaze::zelda3::kMap32ExpandedFlagPos, yaze::zelda3::kMap32TileBLExpanded, yaze::zelda3::kMap32TileBRExpanded, yaze::zelda3::kMap32TileCountExpanded, yaze::zelda3::kMap32TileTRExpanded, yaze::zelda3::OverworldMapTiles::light_world, yaze::util::logf(), map32TilesBL, map32TilesBR, map32TilesTL, map32TilesTR, map_tiles_, yaze::zelda3::OverworldCustomASMHasBeenApplied, rom(), yaze::zelda3::OverworldMapTiles::special_world, and tiles32_unique_.
Referenced by Load().
AssembleMap16Tiles()
absl::Status yaze::zelda3::Overworld::AssembleMap16Tiles () private
Definition at line 320 of file overworld.cc.
References ASSIGN_OR_RETURN, expanded_tile16_, yaze::gfx::GetTilesInfo(), yaze::zelda3::kMap16ExpandedFlagPos, yaze::zelda3::kMap16Tiles, yaze::zelda3::kMap16TilesExpanded, yaze::zelda3::kNumTile16Individual, yaze::util::logf(), yaze::zelda3::NumberOfMap16Ex, yaze::zelda3::OverworldCustomASMHasBeenApplied, rom(), and tiles16_.
Referenced by Load().
AssignWorldTiles()
void yaze::zelda3::Overworld::AssignWorldTiles (int x, int y, int sx, int sy, int tpos, OverworldBlockset & world) private
Definition at line 355 of file overworld.cc.
References tiles32_unique_.
Referenced by OrganizeMapTiles().
OrganizeMapTiles()
void yaze::zelda3::Overworld::OrganizeMapTiles (std::vector< uint8_t > & bytes, std::vector< uint8_t > & bytes2, int i, int sx, int sy, int & ttpos) private
Definition at line 367 of file overworld.cc.
References AssignWorldTiles(), yaze::zelda3::OverworldMapTiles::dark_world, yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::OverworldMapTiles::light_world, map_tiles_, yaze::zelda3::OverworldMapTiles::special_world, and tiles32_unique_.
Referenced by DecompressAllMapTilesParallel().
DecompressAllMapTiles()
void yaze::zelda3::Overworld::DecompressAllMapTiles () private
Definition at line 387 of file overworld.cc.
DecompressAllMapTilesParallel()
absl::Status yaze::zelda3::Overworld::DecompressAllMapTilesParallel () private
Definition at line 393 of file overworld.cc.
References yaze::gfx::HyruleMagicDecompress(), yaze::zelda3::kNumOverworldMaps, yaze::util::logf(), OrganizeMapTiles(), rom(), and yaze::SnesToPc().
Referenced by Load().
Member Data Documentation
rom_
Rom* yaze::zelda3::Overworld::rom_ private
Definition at line 331 of file overworld.h.
Referenced by Load(), mutable_rom(), rom(), and Save().
is_loaded_
bool yaze::zelda3::Overworld::is_loaded_ = false private
Definition at line 333 of file overworld.h.
Referenced by Destroy(), is_loaded(), and Load().
expanded_tile16_
bool yaze::zelda3::Overworld::expanded_tile16_ = false private
Definition at line 334 of file overworld.h.
Referenced by AssembleMap16Tiles(), expanded_tile16(), and Save().
expanded_tile32_
bool yaze::zelda3::Overworld::expanded_tile32_ = false private
Definition at line 335 of file overworld.h.
Referenced by AssembleMap32Tiles(), expanded_tile32(), and Save().
expanded_entrances_
bool yaze::zelda3::Overworld::expanded_entrances_ = false private
Definition at line 336 of file overworld.h.
Referenced by expanded_entrances(), LoadEntrances(), and SaveEntrances().
game_state_
int yaze::zelda3::Overworld::game_state_ = 0 private
Definition at line 338 of file overworld.h.
Referenced by EnsureMapBuilt(), and LoadOverworldMaps().
current_map_
int yaze::zelda3::Overworld::current_map_ = 0 private
Definition at line 339 of file overworld.h.
Referenced by current_area_palette(), current_graphics(), current_map_bitmap_data(), set_current_map(), and tile16_blockset_data().
current_world_
int yaze::zelda3::Overworld::current_world_ = 0 private
Definition at line 340 of file overworld.h.
Referenced by GetTile(), GetTileFromPosition(), set_current_world(), and SetTile().
map_tiles_
OverworldMapTiles yaze::zelda3::Overworld::map_tiles_ private
Definition at line 342 of file overworld.h.
Referenced by AssembleMap32Tiles(), CreateTile32Tilemap(), GetMapTiles(), GetTile(), GetTileFromPosition(), map_tiles(), mutable_map_tiles(), OrganizeMapTiles(), and SetTile().
map_tiles_mutex_
std::mutex yaze::zelda3::Overworld::map_tiles_mutex_ mutable private
Definition at line 345 of file overworld.h.
overworld_maps_
std::vector<OverworldMap> yaze::zelda3::Overworld::overworld_maps_ private
Definition at line 347 of file overworld.h.
Referenced by current_area_palette(), current_graphics(), current_map_bitmap_data(), Destroy(), EnsureMapBuilt(), FetchLargeMaps(), Load(), LoadItems(), LoadOverworldMaps(), LoadSpritesFromMap(), mutable_overworld_map(), overworld_map(), overworld_maps(), SaveAreaSizes(), SaveAreaSpecificBGColors(), SaveCustomOverworldASM(), SaveLargeAreaTransitions(), SaveLargeMaps(), SaveLargeMapsExpanded(), SaveMapOverlays(), SaveMapProperties(), SaveMusic(), SaveSmallAreaTransitions(), SaveTallAreaTransitions(), SaveWideAreaTransitions(), and tile16_blockset_data().
all_entrances_
std::vector<OverworldEntrance> yaze::zelda3::Overworld::all_entrances_ private
Definition at line 348 of file overworld.h.
Referenced by Destroy(), entrances(), entrances(), LoadEntrances(), mutable_entrances(), and SaveEntrances().
all_holes_
std::vector<OverworldEntrance> yaze::zelda3::Overworld::all_holes_ private
Definition at line 349 of file overworld.h.
Referenced by holes(), holes(), LoadHoles(), mutable_holes(), and SaveEntrances().
all_exits_
std::vector<OverworldExit> yaze::zelda3::Overworld::all_exits_ private
Definition at line 350 of file overworld.h.
Referenced by Destroy(), exits(), LoadExits(), mutable_exits(), and SaveExits().
all_items_
std::vector<OverworldItem> yaze::zelda3::Overworld::all_items_ private
Definition at line 351 of file overworld.h.
Referenced by all_items(), Destroy(), LoadItems(), mutable_all_items(), and SaveItems().
tiles16_
std::vector<gfx::Tile16> yaze::zelda3::Overworld::tiles16_ private
Definition at line 353 of file overworld.h.
Referenced by AssembleMap16Tiles(), Destroy(), EnsureMapBuilt(), LoadOverworldMaps(), mutable_tiles16(), SaveMap16Expanded(), SaveMap16Tiles(), and tiles16().
tiles32_
std::vector<gfx::Tile32> yaze::zelda3::Overworld::tiles32_ private
Definition at line 354 of file overworld.h.
Referenced by Destroy().
tiles32_unique_
std::vector<gfx::Tile32> yaze::zelda3::Overworld::tiles32_unique_ private
Definition at line 355 of file overworld.h.
Referenced by AssembleMap32Tiles(), AssignWorldTiles(), CreateTile32Tilemap(), Destroy(), OrganizeMapTiles(), SaveMap32Expanded(), SaveMap32Tiles(), and tiles32_unique().
tiles32_list_
std::vector<uint16_t> yaze::zelda3::Overworld::tiles32_list_ private
Definition at line 357 of file overworld.h.
Referenced by CreateTile32Tilemap(), and SaveOverworldMaps().
deleted_entrances_
std::vector<uint64_t> yaze::zelda3::Overworld::deleted_entrances_ private
Definition at line 358 of file overworld.h.
Referenced by deleted_entrances(), and mutable_deleted_entrances().
map_parent_
std::array<uint8_t, kNumOverworldMaps> yaze::zelda3::Overworld::map_parent_ = {0} private
Definition at line 360 of file overworld.h.
Referenced by Load(), and LoadSpritesFromMap().
all_tiles_types_
std::array<uint8_t, kNumTileTypes> yaze::zelda3::Overworld::all_tiles_types_ = {0} private
Definition at line 361 of file overworld.h.
Referenced by all_tiles_types(), LoadTileTypes(), mutable_all_tiles_types(), and SaveOverworldTilesType().
all_sprites_
std::array<std::vector<Sprite>, 3> yaze::zelda3::Overworld::all_sprites_ private
Definition at line 362 of file overworld.h.
Referenced by all_sprites(), Destroy(), LoadSpritesFromMap(), mutable_sprites(), and sprites().
map_data_p1
std::array<std::vector<uint8_t>, kNumOverworldMaps> yaze::zelda3::Overworld::map_data_p1 private
Definition at line 363 of file overworld.h.
Referenced by SaveOverworldMaps().
map_data_p2
std::array<std::vector<uint8_t>, kNumOverworldMaps> yaze::zelda3::Overworld::map_data_p2 private
Definition at line 364 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers1_id
std::array<int, kNumOverworldMaps> yaze::zelda3::Overworld::map_pointers1_id private
Definition at line 365 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers2_id
std::array<int, kNumOverworldMaps> yaze::zelda3::Overworld::map_pointers2_id private
Definition at line 366 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers1
std::array<int, kNumOverworldMaps> yaze::zelda3::Overworld::map_pointers1 private
Definition at line 367 of file overworld.h.
Referenced by SaveOverworldMaps().
map_pointers2
std::array<int, kNumOverworldMaps> yaze::zelda3::Overworld::map_pointers2 private
Definition at line 368 of file overworld.h.
Referenced by SaveOverworldMaps().
The documentation for this class was generated from the following files:
src/app/zelda3/overworld/overworld.h
src/app/zelda3/overworld/overworld.cc