yaze: yaze::editor::anonymous_namespace{assembly_editor.cc} Namespace Reference
yaze::editor::anonymous_namespace{assembly_editor.cc} Namespace Reference
Functions
TextEditor::LanguageDefinition GetAssemblyLanguageDef ()
std::vector< std::string > RemoveIgnoredFiles (const std::vector< std::string > &files, const std::vector< std::string > &ignored_files)
FolderItem LoadFolder (const std::string &folder)
Function Documentation
GetAssemblyLanguageDef()
TextEditor::LanguageDefinition yaze::editor::anonymous_namespace{assembly_editor.cc}::GetAssemblyLanguageDef ()
Definition at line 43 of file assembly_editor.cc.
References TextEditor::CharLiteral, TextEditor::Identifier, TextEditor::LanguageDefinition::mAutoIndentation, TextEditor::LanguageDefinition::mCaseSensitive, TextEditor::LanguageDefinition::mCommentEnd, TextEditor::LanguageDefinition::mCommentStart, TextEditor::Identifier::mDeclaration, TextEditor::LanguageDefinition::mIdentifiers, TextEditor::LanguageDefinition::mKeywords, TextEditor::LanguageDefinition::mName, TextEditor::LanguageDefinition::mSingleLineComment, TextEditor::LanguageDefinition::mTokenRegexStrings, TextEditor::Number, TextEditor::Preprocessor, TextEditor::Punctuation, and TextEditor::String.
RemoveIgnoredFiles()
std::vector< std::string > yaze::editor::anonymous_namespace{assembly_editor.cc}::RemoveIgnoredFiles (const std::vector< std::string > & files, const std::vector< std::string > & ignored_files)
Definition at line 97 of file assembly_editor.cc.
References RemoveIgnoredFiles().
Referenced by LoadFolder(), and RemoveIgnoredFiles().
LoadFolder()
FolderItem yaze::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder (const std::string & folder)
Definition at line 117 of file assembly_editor.cc.
References yaze::editor::FolderItem::files, yaze::util::FileDialogWrapper::GetFilesInFolder(), yaze::util::FileDialogWrapper::GetSubdirectoriesInFolder(), LoadFolder(), yaze::editor::FolderItem::name, RemoveIgnoredFiles(), and yaze::editor::FolderItem::subfolders.
Referenced by LoadFolder().