yaze: yaze::cli::agent::ToolDispatcher Class Reference
yaze::cli::agent::ToolDispatcher Class Reference
#include <tool_dispatcher.h>
Public Member Functions
ToolDispatcher ()=default
absl::StatusOr< std::string > Dispatch (const ToolCall &tool_call)
void SetRomContext (Rom *rom)
Private Attributes
Rom * rom_context_ = nullptr
Detailed Description
Definition at line 15 of file tool_dispatcher.h.
Constructor & Destructor Documentation
ToolDispatcher()
yaze::cli::agent::ToolDispatcher::ToolDispatcher () default
Member Function Documentation
Dispatch()
absl::StatusOr< std::string > yaze::cli::agent::ToolDispatcher::Dispatch (const ToolCall & tool_call)
Definition at line 14 of file tool_dispatcher.cc.
References yaze::cli::ToolCall::args, yaze::cli::agent::HandleDungeonDescribeRoomCommand(), yaze::cli::agent::HandleDungeonListSpritesCommand(), yaze::cli::agent::HandleMessageListCommand(), yaze::cli::agent::HandleMessageReadCommand(), yaze::cli::agent::HandleMessageSearchCommand(), yaze::cli::agent::HandleOverworldDescribeMapCommand(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldGetEntranceCommand(), yaze::cli::agent::HandleOverworldListSpritesCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandleOverworldTileStatsCommand(), yaze::cli::agent::HandleResourceListCommand(), yaze::cli::agent::HandleResourceSearchCommand(), rom_context_, and yaze::cli::ToolCall::tool_name.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().
SetRomContext()
void yaze::cli::agent::ToolDispatcher::SetRomContext (Rom * rom) inline
Definition at line 22 of file tool_dispatcher.h.
References rom_context_.
Referenced by yaze::cli::agent::ConversationalAgentService::SetRomContext().
Member Data Documentation
rom_context_
Rom* yaze::cli::agent::ToolDispatcher::rom_context_ = nullptr private
Definition at line 25 of file tool_dispatcher.h.
Referenced by Dispatch(), and SetRomContext().
The documentation for this class was generated from the following files:
src/cli/service/agent/tool_dispatcher.h
src/cli/service/agent/tool_dispatcher.cc