yaze: yaze::cli::agent::AgentPretraining Class Reference
yaze::cli::agent::AgentPretraining Class Reference
Pre-training system for AI agents.
#include <agent_pretraining.h>
Classes
struct KnowledgeModule
Static Public Member Functions
static std::vector< KnowledgeModule > GetModules ()
Load all pre-training modules.
static std::string GetRomStructureKnowledge (Rom *rom)
Get ROM structure explanation.
static std::string GetHexAnalysisKnowledge ()
Get hex data analysis patterns.
static std::string GetMapEditingKnowledge ()
Get map editing workflow.
static std::string GetToolUsageExamples ()
Get tool usage examples.
static std::string GeneratePretrainingPrompt (Rom *rom)
Generate pre-training prompt for agent.
Detailed Description
Pre-training system for AI agents.
Provides structured knowledge injection before interactive use. Teaches agent about ROM structure, common patterns, and tool usage.
Definition at line 20 of file agent_pretraining.h.
Member Function Documentation
GetModules()
std::vector< AgentPretraining::KnowledgeModule > yaze::cli::agent::AgentPretraining::GetModules () static
Load all pre-training modules.
Definition at line 11 of file agent_pretraining.cc.
References GetHexAnalysisKnowledge(), GetMapEditingKnowledge(), GetRomStructureKnowledge(), and GetToolUsageExamples().
GetRomStructureKnowledge()
std::string yaze::cli::agent::AgentPretraining::GetRomStructureKnowledge (Rom * rom) static
Get ROM structure explanation.
Definition at line 20 of file agent_pretraining.cc.
Referenced by GetModules().
GetHexAnalysisKnowledge()
std::string yaze::cli::agent::AgentPretraining::GetHexAnalysisKnowledge () static
Get hex data analysis patterns.
Definition at line 60 of file agent_pretraining.cc.
Referenced by GetModules().
GetMapEditingKnowledge()
std::string yaze::cli::agent::AgentPretraining::GetMapEditingKnowledge () static
Get map editing workflow.
Definition at line 100 of file agent_pretraining.cc.
Referenced by GetModules().
GetToolUsageExamples()
std::string yaze::cli::agent::AgentPretraining::GetToolUsageExamples () static
Get tool usage examples.
Definition at line 132 of file agent_pretraining.cc.
Referenced by GetModules().
GeneratePretrainingPrompt()
std::string yaze::cli::agent::AgentPretraining::GeneratePretrainingPrompt (Rom * rom) static
Generate pre-training prompt for agent.
Definition at line 171 of file agent_pretraining.cc.
The documentation for this class was generated from the following files:
src/cli/service/agent/agent_pretraining.h
src/cli/service/agent/agent_pretraining.cc