yaze: yaze::gfx::PaletteGroup Struct Reference
yaze::gfx::PaletteGroup Struct Reference
Represents a group of palettes.
#include <snes_palette.h>
Public Member Functions
PaletteGroup ()=default
PaletteGroup (const std::string &name)
void AddPalette (SnesPalette pal)
void AddColor (SnesColor color)
void clear ()
void resize (size_t new_size)
auto name () const
auto size () const
auto palette (int i) const
auto mutable_palette (int i)
SnesPalette operator[] (int i)
const SnesPalette & operator[] (int i) const
Private Attributes
std::string name_
std::vector< SnesPalette > palettes
Detailed Description
Represents a group of palettes.
Supports adding palettes and colors, clearing the group, and accessing palettes and colors by index.
Definition at line 210 of file snes_palette.h.
Constructor & Destructor Documentation
PaletteGroup() [1/2]
yaze::gfx::PaletteGroup::PaletteGroup () default
PaletteGroup() [2/2]
yaze::gfx::PaletteGroup::PaletteGroup (const std::string & name) inline
Definition at line 212 of file snes_palette.h.
Member Function Documentation
AddPalette()
void yaze::gfx::PaletteGroup::AddPalette (SnesPalette pal) inline
Definition at line 214 of file snes_palette.h.
References palettes.
Referenced by yaze::gfx::CreatePaletteGroupFromColFile(), yaze::gfx::CreatePaletteGroupFromLargePalette(), yaze::gfx::palette_group_internal::Load3DObjectPalettes(), yaze::gfx::palette_group_internal::LoadArmorPalettes(), yaze::gfx::palette_group_internal::LoadDungeonMainPalettes(), yaze::gfx::palette_group_internal::LoadGlobalSpritePalettes(), yaze::gfx::palette_group_internal::LoadHUDPalettes(), yaze::gfx::palette_group_internal::LoadOverworldAnimatedPalettes(), yaze::gfx::palette_group_internal::LoadOverworldAuxiliaryPalettes(), yaze::gfx::palette_group_internal::LoadOverworldMainPalettes(), yaze::gfx::palette_group_internal::LoadOverworldMiniMapPalettes(), yaze::gfx::palette_group_internal::LoadShieldPalettes(), yaze::gfx::palette_group_internal::LoadSpriteAux1Palettes(), yaze::gfx::palette_group_internal::LoadSpriteAux2Palettes(), yaze::gfx::palette_group_internal::LoadSpriteAux3Palettes(), and yaze::gfx::palette_group_internal::LoadSwordPalettes().
AddColor()
void yaze::gfx::PaletteGroup::AddColor (SnesColor color) inline
Definition at line 216 of file snes_palette.h.
References palettes.
Referenced by yaze::gfx::palette_group_internal::LoadGrassColors().
clear()
void yaze::gfx::PaletteGroup::clear () inline
Definition at line 223 of file snes_palette.h.
References palettes.
Referenced by yaze::gfx::PaletteGroupMap::clear(), and yaze::editor::GraphicsEditor::DrawPaletteControls().
resize()
void yaze::gfx::PaletteGroup::resize (size_t new_size) inline
Definition at line 224 of file snes_palette.h.
References palettes.
name()
auto yaze::gfx::PaletteGroup::name () const inline
Definition at line 225 of file snes_palette.h.
References name_.
size()
auto yaze::gfx::PaletteGroup::size () const inline
Definition at line 226 of file snes_palette.h.
References palettes.
Referenced by yaze::editor::DungeonCanvasViewer::DrawDungeonCanvas(), yaze::editor::DungeonEditor::DrawDungeonCanvas(), yaze::editor::GraphicsEditor::DrawPaletteControls(), yaze::editor::PaletteEditor::DrawPaletteGroup(), yaze::gfx::PaletteGroupMap::empty(), and yaze::editor::DungeonCanvasViewer::UpdateRoomBackgroundLayers().
palette()
auto yaze::gfx::PaletteGroup::palette (int i) const inline
Definition at line 227 of file snes_palette.h.
References palettes.
mutable_palette()
auto yaze::gfx::PaletteGroup::mutable_palette (int i) inline
Definition at line 228 of file snes_palette.h.
References palettes.
Referenced by yaze::editor::PaletteEditor::DrawPaletteGroup(), and yaze::Rom::mutable_dungeon_palette().
operator[]() [1/2]
SnesPalette yaze::gfx::PaletteGroup::operator[] (int i) inline
Definition at line 230 of file snes_palette.h.
References palettes.
operator[]() [2/2]
const SnesPalette & yaze::gfx::PaletteGroup::operator[] (int i) const inline
Definition at line 238 of file snes_palette.h.
References palettes.
Member Data Documentation
name_
std::string yaze::gfx::PaletteGroup::name_ private
Definition at line 247 of file snes_palette.h.
Referenced by name().
palettes
std::vector<SnesPalette> yaze::gfx::PaletteGroup::palettes private
Definition at line 248 of file snes_palette.h.
Referenced by AddColor(), AddPalette(), clear(), mutable_palette(), operator[](), operator[](), palette(), resize(), and size().
The documentation for this struct was generated from the following file:
src/app/gfx/snes_palette.h