yaze: yaze::cli::message Namespace Reference
yaze::cli::message Namespace Reference
Namespaces
namespace anonymous_namespace{message.cc}
Functions
absl::Status HandleMessageListCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
List all messages in the ROM.
absl::Status HandleMessageReadCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
Read a specific message by ID.
absl::Status HandleMessageSearchCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
Search for messages containing specific text.
absl::Status HandleMessageStatsCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
Get message statistics and overview.
Function Documentation
HandleMessageListCommand()
absl::Status yaze::cli::message::HandleMessageListCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
List all messages in the ROM.
Parameters
arg_vec Command arguments: [–format <json|text>] [–range <start-end>]
rom_context Optional ROM context to avoid reloading
Definition at line 52 of file message.cc.
References yaze::Rom::is_loaded().
HandleMessageReadCommand()
absl::Status yaze::cli::message::HandleMessageReadCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Read a specific message by ID.
Parameters
arg_vec Command arguments: –id <message_id> [–format <json|text>]
rom_context Optional ROM context to avoid reloading
Definition at line 161 of file message.cc.
References yaze::Rom::is_loaded().
HandleMessageSearchCommand()
absl::Status yaze::cli::message::HandleMessageSearchCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Search for messages containing specific text.
Parameters
arg_vec Command arguments: –query <text> [–format <json|text>]
rom_context Optional ROM context to avoid reloading
Definition at line 247 of file message.cc.
References yaze::Rom::is_loaded().
HandleMessageStatsCommand()
absl::Status yaze::cli::message::HandleMessageStatsCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Get message statistics and overview.
Parameters
arg_vec Command arguments: [–format <json|text>]
rom_context Optional ROM context to avoid reloading
Definition at line 345 of file message.cc.
References yaze::Rom::is_loaded().