yaze: yaze::zelda3::ObjectRenderer::ObjectParser Class Reference
yaze::zelda3::ObjectRenderer::ObjectParser Class Reference
Public Member Functions
ObjectParser (Rom *rom)
~ObjectParser ()=default
absl::StatusOr< std::vector< gfx::Tile16 > > ParseObject (int16_t object_id)
Private Member Functions
void InitializeObjectTables ()
absl::Status ValidateObjectID (int16_t object_id)
bool ValidateROMAddress (int address, size_t size)
int GetObjectSubtype (int16_t object_id)
absl::StatusOr< std::vector< gfx::Tile16 > > ParseSubtype1 (int16_t object_id)
absl::StatusOr< std::vector< gfx::Tile16 > > ParseSubtype2 (int16_t object_id)
absl::StatusOr< std::vector< gfx::Tile16 > > ParseSubtype3 (int16_t object_id)
absl::StatusOr< std::vector< gfx::Tile16 > > ReadTileData (int address, int tile_count)
Private Attributes
Rom * rom_
Static Private Attributes
static constexpr int kRoomObjectSubtype1 = 0x0A8000
static constexpr int kRoomObjectSubtype2 = 0x0A9000
static constexpr int kRoomObjectSubtype3 = 0x0AA000
static constexpr int kRoomObjectTileAddress = 0x0AB000
Detailed Description
Definition at line 238 of file object_renderer.cc.
Constructor & Destructor Documentation
ObjectParser()
yaze::zelda3::ObjectRenderer::ObjectParser::ObjectParser (Rom * rom) inline explicit
Definition at line 240 of file object_renderer.cc.
References InitializeObjectTables(), and rom_.
~ObjectParser()
yaze::zelda3::ObjectRenderer::ObjectParser::~ObjectParser () default
Member Function Documentation
ParseObject()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectRenderer::ObjectParser::ParseObject (int16_t object_id) inline
Definition at line 249 of file object_renderer.cc.
References GetObjectSubtype(), ParseSubtype1(), ParseSubtype2(), ParseSubtype3(), rom_, and ValidateObjectID().
InitializeObjectTables()
void yaze::zelda3::ObjectRenderer::ObjectParser::InitializeObjectTables () inline private
Definition at line 278 of file object_renderer.cc.
Referenced by ObjectParser().
ValidateObjectID()
absl::Status yaze::zelda3::ObjectRenderer::ObjectParser::ValidateObjectID (int16_t object_id) inline private
Definition at line 283 of file object_renderer.cc.
Referenced by ParseObject().
ValidateROMAddress()
bool yaze::zelda3::ObjectRenderer::ObjectParser::ValidateROMAddress (int address, size_t size) inline private
Definition at line 290 of file object_renderer.cc.
References rom_, and yaze::Rom::size().
Referenced by ParseSubtype1(), ParseSubtype2(), ParseSubtype3(), and ReadTileData().
GetObjectSubtype()
int yaze::zelda3::ObjectRenderer::ObjectParser::GetObjectSubtype (int16_t object_id) inline private
Definition at line 294 of file object_renderer.cc.
Referenced by ParseObject().
ParseSubtype1()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectRenderer::ObjectParser::ParseSubtype1 (int16_t object_id) inline private
Definition at line 300 of file object_renderer.cc.
References yaze::Rom::data(), kRoomObjectSubtype1, kRoomObjectTileAddress, ReadTileData(), rom_, and ValidateROMAddress().
Referenced by ParseObject().
ParseSubtype2()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectRenderer::ObjectParser::ParseSubtype2 (int16_t object_id) inline private
Definition at line 322 of file object_renderer.cc.
References yaze::Rom::data(), kRoomObjectSubtype2, kRoomObjectTileAddress, ReadTileData(), rom_, and ValidateROMAddress().
Referenced by ParseObject().
ParseSubtype3()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectRenderer::ObjectParser::ParseSubtype3 (int16_t object_id) inline private
Definition at line 341 of file object_renderer.cc.
References yaze::Rom::data(), kRoomObjectSubtype3, kRoomObjectTileAddress, ReadTileData(), rom_, and ValidateROMAddress().
Referenced by ParseObject().
ReadTileData()
absl::StatusOr< std::vector< gfx::Tile16 > > yaze::zelda3::ObjectRenderer::ObjectParser::ReadTileData (int address, int tile_count) inline private
Definition at line 360 of file object_renderer.cc.
References yaze::Rom::data(), rom_, yaze::zelda3::tile_address, ValidateROMAddress(), and yaze::gfx::WordToTileInfo().
Referenced by ParseSubtype1(), ParseSubtype2(), and ParseSubtype3().
Member Data Documentation
rom_
Rom* yaze::zelda3::ObjectRenderer::ObjectParser::rom_ private
Definition at line 270 of file object_renderer.cc.
Referenced by ObjectParser(), ParseObject(), ParseSubtype1(), ParseSubtype2(), ParseSubtype3(), ReadTileData(), and ValidateROMAddress().
kRoomObjectSubtype1
constexpr int yaze::zelda3::ObjectRenderer::ObjectParser::kRoomObjectSubtype1 = 0x0A8000 static constexpr private
Definition at line 273 of file object_renderer.cc.
Referenced by ParseSubtype1().
kRoomObjectSubtype2
constexpr int yaze::zelda3::ObjectRenderer::ObjectParser::kRoomObjectSubtype2 = 0x0A9000 static constexpr private
Definition at line 274 of file object_renderer.cc.
Referenced by ParseSubtype2().
kRoomObjectSubtype3
constexpr int yaze::zelda3::ObjectRenderer::ObjectParser::kRoomObjectSubtype3 = 0x0AA000 static constexpr private
Definition at line 275 of file object_renderer.cc.
Referenced by ParseSubtype3().
kRoomObjectTileAddress
constexpr int yaze::zelda3::ObjectRenderer::ObjectParser::kRoomObjectTileAddress = 0x0AB000 static constexpr private
Definition at line 276 of file object_renderer.cc.
Referenced by ParseSubtype1(), ParseSubtype2(), and ParseSubtype3().
The documentation for this class was generated from the following file:
src/app/zelda3/dungeon/object_renderer.cc