yaze: yaze::cli::handlers::SimpleChatCommandHandler Class Reference
yaze::cli::handlers::SimpleChatCommandHandler Class Reference
#include <simple_chat_command.h>
Public Member Functions
std::string GetName () const
Get the command name.
std::string GetDescription () const
std::string GetUsage () const override
Get the command usage string.
Public Member Functions inherited from yaze::cli::resources::CommandHandler
virtual ~CommandHandler ()=default
absl::Status Run (const std::vector< std::string > &args, Rom *rom_context)
Execute the command.
virtual Descriptor Describe () const
Provide metadata for TUI/help summaries.
Protected Member Functions
absl::Status ValidateArgs (const resources::ArgumentParser &parser) override
Validate command arguments.
absl::Status Execute (Rom *rom, const resources::ArgumentParser &parser, resources::OutputFormatter &formatter) override
Execute the command business logic.
Protected Member Functions inherited from yaze::cli::resources::CommandHandler
virtual bool RequiresLabels () const
Check if the command requires ROM labels.
virtual std::string GetDefaultFormat () const
Get the default output format ("json" or "text")
virtual std::string GetOutputTitle () const
Get the output title for formatting.
Detailed Description
Definition at line 10 of file simple_chat_command.h.
Member Function Documentation
GetName()
std::string yaze::cli::handlers::SimpleChatCommandHandler::GetName () const inline virtual
Get the command name.
Override this to provide a unique identifier for the command. This is used for command registration and lookup.
Implements yaze::cli::resources::CommandHandler.
Definition at line 12 of file simple_chat_command.h.
GetDescription()
std::string yaze::cli::handlers::SimpleChatCommandHandler::GetDescription () const inline
Definition at line 13 of file simple_chat_command.h.
GetUsage()
std::string yaze::cli::handlers::SimpleChatCommandHandler::GetUsage () const inline override virtual
Get the command usage string.
Implements yaze::cli::resources::CommandHandler.
Definition at line 14 of file simple_chat_command.h.
ValidateArgs()
absl::Status yaze::cli::handlers::SimpleChatCommandHandler::ValidateArgs (const resources::ArgumentParser & parser) inline override protected virtual
Validate command arguments.
Override this to check required arguments and perform custom validation. Called before Execute().
Implements yaze::cli::resources::CommandHandler.
Definition at line 19 of file simple_chat_command.h.
Execute()
absl::Status yaze::cli::handlers::SimpleChatCommandHandler::Execute (Rom * rom, const resources::ArgumentParser & parser, resources::OutputFormatter & formatter) override protected virtual
Execute the command business logic.
Override this to implement command-specific functionality. The ROM is guaranteed to be loaded and labels initialized.
Implements yaze::cli::resources::CommandHandler.
Definition at line 8 of file simple_chat_command.cc.
References yaze::cli::resources::ArgumentParser::GetString(), yaze::cli::resources::ArgumentParser::HasFlag(), yaze::cli::agent::SimpleChatSession::RunBatch(), yaze::cli::agent::SimpleChatSession::RunInteractive(), yaze::cli::agent::SimpleChatSession::SendAndWaitForResponse(), yaze::cli::agent::SimpleChatSession::SetConfig(), yaze::cli::agent::SimpleChatSession::SetRomContext(), and yaze::cli::agent::AgentConfig::verbose.
The documentation for this class was generated from the following files:
src/cli/handlers/agent/simple_chat_command.h
src/cli/handlers/agent/simple_chat_command.cc