yaze: yaze::editor::OverworldEntityRenderer Class Reference
yaze::editor::OverworldEntityRenderer Class Reference
Handles visualization of all overworld entities (entrances, exits, items, sprites)
#include <overworld_entity_renderer.h>
Public Member Functions
OverworldEntityRenderer (zelda3::Overworld *overworld, gui::Canvas *canvas, std::vector< gfx::Bitmap > *sprite_previews)
void DrawEntrances (ImVec2 canvas_p0, ImVec2 scrolling, int current_world, int current_mode)
void DrawExits (ImVec2 canvas_p0, ImVec2 scrolling, int current_world, int current_mode)
void DrawItems (int current_world, int current_mode)
void DrawSprites (int current_world, int game_state, int current_mode)
int current_entrance_id () const
int current_exit_id () const
int current_item_id () const
int current_sprite_id () const
int jump_to_tab () const
zelda3::OverworldEntrance & current_entrance ()
zelda3::OverworldExit & current_exit ()
zelda3::OverworldItem & current_item ()
zelda3::Sprite & current_sprite ()
void set_current_map (int map)
void set_is_dragging_entity (bool value)
void set_dragged_entity (zelda3::GameEntity *entity)
void set_current_entity (zelda3::GameEntity *entity)
void reset_jump_to_tab ()
Private Attributes
zelda3::Overworld * overworld_
gui::Canvas * canvas_
std::vector< gfx::Bitmap > * sprite_previews_
int current_entrance_id_ = 0
int current_exit_id_ = 0
int current_item_id_ = 0
int current_sprite_id_ = 0
int current_map_ = 0
int jump_to_tab_ = -1
bool is_dragging_entity_ = false
zelda3::GameEntity * dragged_entity_ = nullptr
zelda3::GameEntity * current_entity_ = nullptr
zelda3::OverworldEntrance current_entrance_
zelda3::OverworldExit current_exit_
zelda3::OverworldItem current_item_
zelda3::Sprite current_sprite_
Detailed Description
Handles visualization of all overworld entities (entrances, exits, items, sprites)
This class separates entity rendering logic from the main OverworldEditor, making it easier to maintain and test entity visualization independently.
Definition at line 27 of file overworld_entity_renderer.h.
Constructor & Destructor Documentation
OverworldEntityRenderer()
yaze::editor::OverworldEntityRenderer::OverworldEntityRenderer (zelda3::Overworld * overworld, gui::Canvas * canvas, std::vector< gfx::Bitmap > * sprite_previews) inline
Definition at line 29 of file overworld_entity_renderer.h.
Member Function Documentation
DrawEntrances()
void yaze::editor::OverworldEntityRenderer::DrawEntrances (ImVec2 canvas_p0, ImVec2 scrolling, int current_world, int current_mode)
Definition at line 24 of file overworld_entity_renderer.cc.
References canvas_, current_entity_, current_entrance_, current_entrance_id_, current_map_, yaze::zelda3::Overworld::deleted_entrances(), dragged_entity_, yaze::editor::DrawEntranceInserterPopup(), yaze::editor::DrawOverworldEntrancePopup(), yaze::gui::Canvas::DrawRect(), yaze::gui::Canvas::DrawText(), yaze::zelda3::Overworld::entrances(), yaze::editor::HandleEntityDragging(), yaze::util::HexByte(), yaze::gui::Canvas::hover_mouse_pos(), is_dragging_entity_, yaze::editor::IsMouseHoveringOverEntity(), jump_to_tab_, yaze::zelda3::Overworld::mutable_deleted_entrances(), and overworld_.
DrawExits()
void yaze::editor::OverworldEntityRenderer::DrawExits (ImVec2 canvas_p0, ImVec2 scrolling, int current_world, int current_mode)
Definition at line 93 of file overworld_entity_renderer.cc.
References canvas_, current_entity_, current_exit_, current_exit_id_, dragged_entity_, yaze::editor::DrawExitEditorPopup(), yaze::editor::DrawExitInserterPopup(), yaze::gui::Canvas::DrawRect(), yaze::gui::Canvas::DrawText(), yaze::zelda3::GameEntity::entity_id_, yaze::editor::HandleEntityDragging(), yaze::util::HexByte(), is_dragging_entity_, yaze::editor::IsMouseHoveringOverEntity(), jump_to_tab_, yaze::zelda3::Overworld::mutable_exits(), overworld_, yaze::gui::Canvas::scrolling(), and yaze::gui::Canvas::zero_point().
DrawItems()
void yaze::editor::OverworldEntityRenderer::DrawItems (int current_world, int current_mode)
Definition at line 145 of file overworld_entity_renderer.cc.
References canvas_, current_entity_, current_item_, current_item_id_, dragged_entity_, yaze::editor::DrawItemEditorPopup(), yaze::editor::DrawItemInsertPopup(), yaze::gui::Canvas::DrawRect(), yaze::gui::Canvas::DrawText(), yaze::editor::HandleEntityDragging(), is_dragging_entity_, yaze::editor::IsMouseHoveringOverEntity(), yaze::zelda3::kSecretItemNames, yaze::zelda3::Overworld::mutable_all_items(), overworld_, yaze::gui::Canvas::scrolling(), and yaze::gui::Canvas::zero_point().
DrawSprites()
void yaze::editor::OverworldEntityRenderer::DrawSprites (int current_world, int game_state, int current_mode)
Definition at line 195 of file overworld_entity_renderer.cc.
References canvas_, current_entity_, current_sprite_, current_sprite_id_, dragged_entity_, yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawRect(), yaze::editor::DrawSpriteEditorPopup(), yaze::editor::DrawSpriteInserterPopup(), yaze::gui::Canvas::DrawText(), yaze::core::FeatureFlags::get(), yaze::editor::HandleEntityDragging(), is_dragging_entity_, yaze::editor::IsMouseHoveringOverEntity(), yaze::zelda3::Overworld::mutable_sprites(), overworld_, yaze::gui::Canvas::scrolling(), sprite_previews_, yaze::zelda3::GameEntity::x_, and yaze::gui::Canvas::zero_point().
current_entrance_id()
int yaze::editor::OverworldEntityRenderer::current_entrance_id () const inline
Definition at line 43 of file overworld_entity_renderer.h.
References current_entrance_id_.
current_exit_id()
int yaze::editor::OverworldEntityRenderer::current_exit_id () const inline
Definition at line 44 of file overworld_entity_renderer.h.
References current_exit_id_.
current_item_id()
int yaze::editor::OverworldEntityRenderer::current_item_id () const inline
Definition at line 45 of file overworld_entity_renderer.h.
References current_item_id_.
current_sprite_id()
int yaze::editor::OverworldEntityRenderer::current_sprite_id () const inline
Definition at line 46 of file overworld_entity_renderer.h.
References current_sprite_id_.
jump_to_tab()
int yaze::editor::OverworldEntityRenderer::jump_to_tab () const inline
Definition at line 47 of file overworld_entity_renderer.h.
References jump_to_tab_.
current_entrance()
zelda3::OverworldEntrance & yaze::editor::OverworldEntityRenderer::current_entrance () inline
Definition at line 49 of file overworld_entity_renderer.h.
References current_entrance_.
current_exit()
zelda3::OverworldExit & yaze::editor::OverworldEntityRenderer::current_exit () inline
Definition at line 50 of file overworld_entity_renderer.h.
References current_exit_.
current_item()
zelda3::OverworldItem & yaze::editor::OverworldEntityRenderer::current_item () inline
Definition at line 51 of file overworld_entity_renderer.h.
References current_item_.
current_sprite()
zelda3::Sprite & yaze::editor::OverworldEntityRenderer::current_sprite () inline
Definition at line 52 of file overworld_entity_renderer.h.
References current_sprite_.
set_current_map()
void yaze::editor::OverworldEntityRenderer::set_current_map (int map) inline
Definition at line 54 of file overworld_entity_renderer.h.
References current_map_.
set_is_dragging_entity()
void yaze::editor::OverworldEntityRenderer::set_is_dragging_entity (bool value) inline
Definition at line 55 of file overworld_entity_renderer.h.
References is_dragging_entity_.
set_dragged_entity()
void yaze::editor::OverworldEntityRenderer::set_dragged_entity (zelda3::GameEntity * entity) inline
Definition at line 56 of file overworld_entity_renderer.h.
References dragged_entity_.
set_current_entity()
void yaze::editor::OverworldEntityRenderer::set_current_entity (zelda3::GameEntity * entity) inline
Definition at line 57 of file overworld_entity_renderer.h.
References current_entity_.
reset_jump_to_tab()
void yaze::editor::OverworldEntityRenderer::reset_jump_to_tab () inline
Definition at line 59 of file overworld_entity_renderer.h.
References jump_to_tab_.
Member Data Documentation
overworld_
zelda3::Overworld* yaze::editor::OverworldEntityRenderer::overworld_ private
Definition at line 62 of file overworld_entity_renderer.h.
Referenced by DrawEntrances(), DrawExits(), DrawItems(), and DrawSprites().
canvas_
gui::Canvas* yaze::editor::OverworldEntityRenderer::canvas_ private
Definition at line 63 of file overworld_entity_renderer.h.
Referenced by DrawEntrances(), DrawExits(), DrawItems(), and DrawSprites().
sprite_previews_
std::vector<gfx::Bitmap>* yaze::editor::OverworldEntityRenderer::sprite_previews_ private
Definition at line 64 of file overworld_entity_renderer.h.
Referenced by DrawSprites().
current_entrance_id_
int yaze::editor::OverworldEntityRenderer::current_entrance_id_ = 0 private
Definition at line 67 of file overworld_entity_renderer.h.
Referenced by current_entrance_id(), and DrawEntrances().
current_exit_id_
int yaze::editor::OverworldEntityRenderer::current_exit_id_ = 0 private
Definition at line 68 of file overworld_entity_renderer.h.
Referenced by current_exit_id(), and DrawExits().
current_item_id_
int yaze::editor::OverworldEntityRenderer::current_item_id_ = 0 private
Definition at line 69 of file overworld_entity_renderer.h.
Referenced by current_item_id(), and DrawItems().
current_sprite_id_
int yaze::editor::OverworldEntityRenderer::current_sprite_id_ = 0 private
Definition at line 70 of file overworld_entity_renderer.h.
Referenced by current_sprite_id(), and DrawSprites().
current_map_
int yaze::editor::OverworldEntityRenderer::current_map_ = 0 private
Definition at line 71 of file overworld_entity_renderer.h.
Referenced by DrawEntrances(), and set_current_map().
jump_to_tab_
int yaze::editor::OverworldEntityRenderer::jump_to_tab_ = -1 private
Definition at line 72 of file overworld_entity_renderer.h.
Referenced by DrawEntrances(), DrawExits(), jump_to_tab(), and reset_jump_to_tab().
is_dragging_entity_
bool yaze::editor::OverworldEntityRenderer::is_dragging_entity_ = false private
Definition at line 75 of file overworld_entity_renderer.h.
Referenced by DrawEntrances(), DrawExits(), DrawItems(), DrawSprites(), and set_is_dragging_entity().
dragged_entity_
zelda3::GameEntity* yaze::editor::OverworldEntityRenderer::dragged_entity_ = nullptr private
Definition at line 76 of file overworld_entity_renderer.h.
Referenced by DrawEntrances(), DrawExits(), DrawItems(), DrawSprites(), and set_dragged_entity().
current_entity_
zelda3::GameEntity* yaze::editor::OverworldEntityRenderer::current_entity_ = nullptr private
Definition at line 77 of file overworld_entity_renderer.h.
Referenced by DrawEntrances(), DrawExits(), DrawItems(), DrawSprites(), and set_current_entity().
current_entrance_
zelda3::OverworldEntrance yaze::editor::OverworldEntityRenderer::current_entrance_ private
Definition at line 80 of file overworld_entity_renderer.h.
Referenced by current_entrance(), and DrawEntrances().
current_exit_
zelda3::OverworldExit yaze::editor::OverworldEntityRenderer::current_exit_ private
Definition at line 81 of file overworld_entity_renderer.h.
Referenced by current_exit(), and DrawExits().
current_item_
zelda3::OverworldItem yaze::editor::OverworldEntityRenderer::current_item_ private
Definition at line 82 of file overworld_entity_renderer.h.
Referenced by current_item(), and DrawItems().
current_sprite_
zelda3::Sprite yaze::editor::OverworldEntityRenderer::current_sprite_ private
Definition at line 83 of file overworld_entity_renderer.h.
Referenced by current_sprite(), and DrawSprites().
The documentation for this class was generated from the following files:
src/app/editor/overworld/overworld_entity_renderer.h
src/app/editor/overworld/overworld_entity_renderer.cc