yaze: yaze::test::integration::AsarIntegrationTest Class Reference
yaze::test::integration::AsarIntegrationTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void CreateTestRom ()
void CreateTestAssemblyFiles ()
Protected Attributes
std::unique_ptr< core::AsarWrapper > wrapper_
std::filesystem::path test_dir_
std::filesystem::path comprehensive_asm_path_
std::filesystem::path advanced_asm_path_
std::filesystem::path error_asm_path_
std::vector< uint8_t > test_rom_
Detailed Description
Definition at line 17 of file asar_integration_test.cc.
Member Function Documentation
SetUp()
void yaze::test::integration::AsarIntegrationTest::SetUp () inline override protected
Definition at line 19 of file asar_integration_test.cc.
References CreateTestAssemblyFiles(), CreateTestRom(), test_dir_, and wrapper_.
TearDown()
void yaze::test::integration::AsarIntegrationTest::TearDown () inline override protected
Definition at line 30 of file asar_integration_test.cc.
References test_dir_.
CreateTestRom()
void yaze::test::integration::AsarIntegrationTest::CreateTestRom () inline protected
Definition at line 40 of file asar_integration_test.cc.
References test_rom_.
Referenced by SetUp().
CreateTestAssemblyFiles()
void yaze::test::integration::AsarIntegrationTest::CreateTestAssemblyFiles () inline protected
Definition at line 96 of file asar_integration_test.cc.
References comprehensive_asm_path_, and test_dir_.
Referenced by SetUp().
Member Data Documentation
wrapper_
std::unique_ptr<core::AsarWrapper> yaze::test::integration::AsarIntegrationTest::wrapper_ protected
Definition at line 122 of file asar_integration_test.cc.
Referenced by SetUp().
test_dir_
std::filesystem::path yaze::test::integration::AsarIntegrationTest::test_dir_ protected
Definition at line 123 of file asar_integration_test.cc.
Referenced by CreateTestAssemblyFiles(), SetUp(), and TearDown().
comprehensive_asm_path_
std::filesystem::path yaze::test::integration::AsarIntegrationTest::comprehensive_asm_path_ protected
Definition at line 124 of file asar_integration_test.cc.
Referenced by CreateTestAssemblyFiles().
advanced_asm_path_
std::filesystem::path yaze::test::integration::AsarIntegrationTest::advanced_asm_path_ protected
Definition at line 125 of file asar_integration_test.cc.
error_asm_path_
std::filesystem::path yaze::test::integration::AsarIntegrationTest::error_asm_path_ protected
Definition at line 126 of file asar_integration_test.cc.
test_rom_
std::vector<uint8_t> yaze::test::integration::AsarIntegrationTest::test_rom_ protected
Definition at line 127 of file asar_integration_test.cc.
Referenced by CreateTestRom().
The documentation for this class was generated from the following file:
test/integration/asar_integration_test.cc