yaze: yaze::project::RecentFilesManager Class Reference
yaze::project::RecentFilesManager Class Reference
#include <project.h>
Public Member Functions
RecentFilesManager (const RecentFilesManager &)=delete
RecentFilesManager & operator= (const RecentFilesManager &)=delete
void AddFile (const std::string &file_path)
void Save ()
void Load ()
const std::vector< std::string > & GetRecentFiles () const
void Clear ()
Static Public Member Functions
static RecentFilesManager & GetInstance ()
Private Member Functions
RecentFilesManager ()
std::string GetFilePath () const
Private Attributes
std::vector< std::string > recent_files_
Detailed Description
Definition at line 241 of file project.h.
Constructor & Destructor Documentation
RecentFilesManager() [1/2]
yaze::project::RecentFilesManager::RecentFilesManager (const RecentFilesManager &) delete
RecentFilesManager() [2/2]
yaze::project::RecentFilesManager::RecentFilesManager () inline private
Definition at line 281 of file project.h.
References Load().
Member Function Documentation
GetInstance()
static RecentFilesManager & yaze::project::RecentFilesManager::GetInstance () inline static
Definition at line 244 of file project.h.
Referenced by yaze::editor::ConfigureEditorShortcuts(), yaze::editor::UICoordinator::DrawGlobalSearch(), yaze::editor::EditorManager::LoadRom(), yaze::editor::EditorManager::OpenProject(), yaze::editor::WelcomeScreen::RefreshRecentProjects(), yaze::editor::ProjectFileEditor::SaveFileAs(), yaze::editor::EditorManager::SaveProject(), yaze::editor::EditorManager::SaveProjectAs(), and yaze::editor::EditorManager::SaveRomAs().
operator=()
RecentFilesManager & yaze::project::RecentFilesManager::operator= (const RecentFilesManager &) delete
AddFile()
void yaze::project::RecentFilesManager::AddFile (const std::string & file_path) inline
Definition at line 253 of file project.h.
References recent_files_.
Save()
void yaze::project::RecentFilesManager::Save ()
Definition at line 1069 of file project.cc.
References yaze::util::PlatformPaths::GetConfigDirectory(), GetFilePath(), LOG_ERROR, LOG_WARN, and recent_files_.
Load()
void yaze::project::RecentFilesManager::Load ()
Definition at line 1090 of file project.cc.
References GetFilePath(), and recent_files_.
Referenced by RecentFilesManager().
GetRecentFiles()
const std::vector< std::string > & yaze::project::RecentFilesManager::GetRecentFiles () const inline
Definition at line 272 of file project.h.
References recent_files_.
Referenced by yaze::editor::WelcomeScreen::RefreshRecentProjects().
Clear()
void yaze::project::RecentFilesManager::Clear () inline
Definition at line 276 of file project.h.
References recent_files_.
GetFilePath()
std::string yaze::project::RecentFilesManager::GetFilePath () const private
Definition at line 1061 of file project.cc.
References yaze::util::PlatformPaths::GetConfigDirectory(), and yaze::project::kRecentFilesFilename.
Referenced by Load(), and Save().
Member Data Documentation
recent_files_
std::vector<std::string> yaze::project::RecentFilesManager::recent_files_ private
Definition at line 287 of file project.h.
Referenced by AddFile(), Clear(), GetRecentFiles(), Load(), and Save().
The documentation for this class was generated from the following files:
src/core/project.h
src/core/project.cc