set(
  YAZE_APP_GFX_SRC
  app/gfx/arena.cc
  app/gfx/background_buffer.cc
  app/gfx/bitmap.cc
  app/gfx/compression.cc
  app/gfx/scad_format.cc
  app/gfx/snes_palette.cc
  app/gfx/snes_tile.cc
  app/gfx/snes_color.cc
  app/gfx/tilemap.cc
)