yaze: yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc} Namespace Reference
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc} Namespace Reference
Functions
TEST (RoomObjectEncodingTest, DetermineObjectTypeType1)
TEST (RoomObjectEncodingTest, DetermineObjectTypeType2)
TEST (RoomObjectEncodingTest, DetermineObjectTypeType3)
TEST (RoomObjectEncodingTest, Type1EncodeDecodeBasic)
TEST (RoomObjectEncodingTest, Type1MaxValues)
TEST (RoomObjectEncodingTest, Type1MinValues)
TEST (RoomObjectEncodingTest, Type1DifferentSizes)
TEST (RoomObjectEncodingTest, Type1RealWorldExample1)
TEST (RoomObjectEncodingTest, Type1RealWorldExample2)
TEST (RoomObjectEncodingTest, Type2EncodeDecodeBasic)
TEST (RoomObjectEncodingTest, Type2MaxValues)
TEST (RoomObjectEncodingTest, Type2RealWorldExample)
TEST (RoomObjectEncodingTest, Type3EncodeDecodeChest)
TEST (RoomObjectEncodingTest, Type3EncodeDcodeBigChest)
TEST (RoomObjectEncodingTest, Type3RealWorldExample)
TEST (RoomObjectEncodingTest, LayerPreservation)
TEST (RoomObjectEncodingTest, BoundaryBetweenTypes)
TEST (RoomObjectEncodingTest, ZeroPosition)
TEST (RoomObjectEncodingTest, MultipleObjectsRoundTrip)
Function Documentation
TEST() [1/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , DetermineObjectTypeType1)
Definition at line 20 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DetermineObjectType().
TEST() [2/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , DetermineObjectTypeType2)
Definition at line 27 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DetermineObjectType().
TEST() [3/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , DetermineObjectTypeType3)
Definition at line 34 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DetermineObjectType().
TEST() [4/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type1EncodeDecodeBasic)
Definition at line 45 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), yaze::zelda3::RoomObject::EncodeObjectToBytes(), yaze::zelda3::RoomObject::GetLayerValue(), yaze::zelda3::RoomObject::id_, yaze::zelda3::RoomObject::size(), yaze::zelda3::RoomObject::x(), and yaze::zelda3::RoomObject::y().
TEST() [5/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type1MaxValues)
Definition at line 65 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), yaze::zelda3::RoomObject::EncodeObjectToBytes(), yaze::zelda3::RoomObject::id_, yaze::zelda3::RoomObject::size(), yaze::zelda3::RoomObject::x(), and yaze::zelda3::RoomObject::y().
TEST() [6/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type1MinValues)
Definition at line 82 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), yaze::zelda3::RoomObject::EncodeObjectToBytes(), yaze::zelda3::RoomObject::id_, yaze::zelda3::RoomObject::size(), yaze::zelda3::RoomObject::x(), and yaze::zelda3::RoomObject::y().
TEST() [7/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type1DifferentSizes)
Definition at line 95 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), and yaze::zelda3::RoomObject::EncodeObjectToBytes().
TEST() [8/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type1RealWorldExample1)
Definition at line 107 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes().
TEST() [9/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type1RealWorldExample2)
Definition at line 120 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes().
TEST() [10/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type2EncodeDecodeBasic)
Definition at line 136 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), yaze::zelda3::RoomObject::EncodeObjectToBytes(), yaze::zelda3::RoomObject::GetLayerValue(), yaze::zelda3::RoomObject::id_, yaze::zelda3::RoomObject::x(), and yaze::zelda3::RoomObject::y().
TEST() [11/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type2MaxValues)
Definition at line 158 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), yaze::zelda3::RoomObject::EncodeObjectToBytes(), yaze::zelda3::RoomObject::id_, yaze::zelda3::RoomObject::x(), and yaze::zelda3::RoomObject::y().
TEST() [12/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type2RealWorldExample)
Definition at line 173 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), and yaze::zelda3::RoomObject::EncodeObjectToBytes().
TEST() [13/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type3EncodeDecodeChest)
Definition at line 191 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), yaze::zelda3::RoomObject::EncodeObjectToBytes(), yaze::zelda3::RoomObject::id_, yaze::zelda3::RoomObject::x(), and yaze::zelda3::RoomObject::y().
TEST() [14/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type3EncodeDcodeBigChest)
Definition at line 212 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), and yaze::zelda3::RoomObject::EncodeObjectToBytes().
TEST() [15/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , Type3RealWorldExample)
Definition at line 225 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes().
TEST() [16/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , LayerPreservation)
Definition at line 241 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), and yaze::zelda3::RoomObject::EncodeObjectToBytes().
TEST() [17/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , BoundaryBetweenTypes)
Definition at line 253 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), and yaze::zelda3::RoomObject::EncodeObjectToBytes().
TEST() [18/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , ZeroPosition)
Definition at line 282 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes(), and yaze::zelda3::RoomObject::EncodeObjectToBytes().
TEST() [19/19]
yaze::zelda3::anonymous_namespace{room_object_encoding_test.cc}::TEST (RoomObjectEncodingTest , MultipleObjectsRoundTrip)
Definition at line 301 of file room_object_encoding_test.cc.
References yaze::zelda3::RoomObject::DecodeObjectFromBytes().