yaze: yaze::cli::util Namespace Reference
yaze::cli::util Namespace Reference
Namespaces
namespace colors
namespace icons
Classes
class LoadingIndicator
Functions
void PrintSuccess (const std::string &message)
void PrintError (const std::string &message)
void PrintWarning (const std::string &message)
void PrintInfo (const std::string &message)
void PrintToolCall (const std::string &tool_name, const std::string &details="")
void PrintThinking (const std::string &message="Processing...")
void PrintSeparator ()
Function Documentation
PrintSuccess()
void yaze::cli::util::PrintSuccess (const std::string & message) inline
Definition at line 114 of file terminal_colors.h.
References yaze::cli::util::colors::kGreen, yaze::cli::util::colors::kReset, and yaze::cli::util::icons::kSuccess.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().
PrintError()
void yaze::cli::util::PrintError (const std::string & message) inline
Definition at line 118 of file terminal_colors.h.
References yaze::cli::util::icons::kError, yaze::cli::util::colors::kRed, and yaze::cli::util::colors::kReset.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().
PrintWarning()
void yaze::cli::util::PrintWarning (const std::string & message) inline
Definition at line 122 of file terminal_colors.h.
References yaze::cli::util::colors::kReset, yaze::cli::util::icons::kWarning, and yaze::cli::util::colors::kYellow.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().
PrintInfo()
void yaze::cli::util::PrintInfo (const std::string & message) inline
Definition at line 126 of file terminal_colors.h.
References yaze::cli::util::colors::kBlue, yaze::cli::util::icons::kInfo, and yaze::cli::util::colors::kReset.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().
PrintToolCall()
void yaze::cli::util::PrintToolCall (const std::string & tool_name, const std::string & details = "") inline
Definition at line 130 of file terminal_colors.h.
References yaze::cli::util::colors::kBold, yaze::cli::util::colors::kCyan, yaze::cli::util::colors::kDim, yaze::cli::util::colors::kMagenta, yaze::cli::util::colors::kReset, and yaze::cli::util::icons::kTool.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().
PrintThinking()
void yaze::cli::util::PrintThinking (const std::string & message = "Processing...") inline
Definition at line 140 of file terminal_colors.h.
References yaze::cli::util::colors::kDim, yaze::cli::util::colors::kReset, yaze::cli::util::icons::kThinking, and yaze::cli::util::colors::kYellow.
PrintSeparator()
void yaze::cli::util::PrintSeparator () inline
Definition at line 145 of file terminal_colors.h.
References yaze::cli::util::colors::kDim, and yaze::cli::util::colors::kReset.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().