yaze: yaze::cli::agent::anonymous_namespace{hex_commands.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{hex_commands.cc} Namespace Reference
Functions
absl::StatusOr< uint32_t > ParseHexAddress (const std::string &str)
std::vector< std::pair< uint8_t, bool > > ParseHexPattern (const std::string &pattern)
std::string FormatHexBytes (const uint8_t *data, size_t length, const std::string &format)
Function Documentation
ParseHexAddress()
absl::StatusOr< uint32_t > yaze::cli::agent::anonymous_namespace{hex_commands.cc}::ParseHexAddress (const std::string & str)
Definition at line 21 of file hex_commands.cc.
References ParseHexAddress().
Referenced by ParseHexAddress().
ParseHexPattern()
std::vector< std::pair< uint8_t, bool > > yaze::cli::agent::anonymous_namespace{hex_commands.cc}::ParseHexPattern (const std::string & pattern)
Definition at line 37 of file hex_commands.cc.
References ParseHexPattern().
Referenced by ParseHexPattern().
FormatHexBytes()
std::string yaze::cli::agent::anonymous_namespace{hex_commands.cc}::FormatHexBytes (const uint8_t * data, size_t length, const std::string & format)
Definition at line 60 of file hex_commands.cc.
References FormatHexBytes().
Referenced by FormatHexBytes().