yaze: yaze::zelda3::anonymous_namespace{room_layout.cc} Namespace Reference
yaze::zelda3::anonymous_namespace{room_layout.cc} Namespace Reference
Functions
uint16_t ReadWord (const Rom *rom, int pc_addr)
Variables
constexpr uint16_t kLayerTerminator = 0xFFFF
Function Documentation
ReadWord()
uint16_t yaze::zelda3::anonymous_namespace{room_layout.cc}::ReadWord (const Rom * rom, int pc_addr)
Definition at line 11 of file room_layout.cc.
References yaze::Rom::data(), and ReadWord().
Referenced by ReadWord().
Variable Documentation
kLayerTerminator
constexpr uint16_t yaze::zelda3::anonymous_namespace{room_layout.cc}::kLayerTerminator = 0xFFFF constexpr
Definition at line 9 of file room_layout.cc.