yaze: yaze::gui::EditorCardManager Class Reference
yaze::gui::EditorCardManager Class Reference
Central registry and manager for all editor cards.
#include <editor_card_manager.h>
Classes
struct WorkspacePreset
Public Member Functions
void RegisterCard (const CardInfo &info)
void UnregisterCard (const std::string &card_id)
void ClearAllCards ()
bool ShowCard (const std::string &card_id)
bool HideCard (const std::string &card_id)
bool ToggleCard (const std::string &card_id)
bool IsCardVisible (const std::string &card_id) const
void ShowAllCardsInCategory (const std::string &category)
void HideAllCardsInCategory (const std::string &category)
void ShowOnlyCard (const std::string &card_id)
std::vector< CardInfo > GetCardsInCategory (const std::string &category) const
std::vector< std::string > GetAllCategories () const
const CardInfo * GetCardInfo (const std::string &card_id) const
void DrawViewMenuSection (const std::string &category)
void DrawViewMenuAll ()
void DrawCompactCardControl (const std::string &category)
void DrawInlineCardToggles (const std::string &category)
void DrawCardBrowser (bool *p_open)
void DrawCardBrowserTable (const char *search_filter, const std::string &category_filter)
void DrawPresetsTab ()
void SavePreset (const std::string &name, const std::string &description="")
bool LoadPreset (const std::string &name)
void DeletePreset (const std::string &name)
std::vector< WorkspacePreset > GetPresets () const
void ShowAll ()
void HideAll ()
void ResetToDefaults ()
size_t GetCardCount () const
size_t GetVisibleCardCount () const
Static Public Member Functions
static EditorCardManager & Get ()
Private Member Functions
EditorCardManager ()=default
~EditorCardManager ()=default
EditorCardManager (const EditorCardManager &)=delete
EditorCardManager & operator= (const EditorCardManager &)=delete
void SavePresetsToFile ()
void LoadPresetsFromFile ()
Private Attributes
std::unordered_map< std::string, CardInfo > cards_
std::unordered_map< std::string, WorkspacePreset > presets_
Detailed Description
Central registry and manager for all editor cards.
This singleton provides:
Global card registration across all editors
View menu integration
Keyboard shortcut management
Workspace preset system
Quick search/filter
Programmatic card control without GUI coupling
Design Philosophy:
Cards register themselves on creation
Manager provides unified interface for visibility control
No direct GUI dependency in card logic
Supports dynamic card creation/destruction
Usage:
// In editor initialization:
auto& manager = EditorCardManager::Get();
manager.RegisterCard({
    .card_id = "dungeon.room_selector",
    .display_name = "Room Selector",
    .icon = ICON_MD_LIST,
    .category = "Dungeon",
    .visibility_flag = &show_room_selector_,
    .on_show = []() { printf("Room selector opened\n"); }
});
// Programmatic control:
manager.ShowCard("dungeon.room_selector");
manager.HideCard("dungeon.room_selector");
manager.ToggleCard("dungeon.room_selector");
// In View menu:
manager.DrawViewMenuSection("Dungeon");
Definition at line 72 of file editor_card_manager.h.
Constructor & Destructor Documentation
EditorCardManager() [1/2]
yaze::gui::EditorCardManager::EditorCardManager () private default
~EditorCardManager()
yaze::gui::EditorCardManager::~EditorCardManager () private default
EditorCardManager() [2/2]
yaze::gui::EditorCardManager::EditorCardManager (const EditorCardManager &) private delete
Member Function Documentation
Get()
EditorCardManager & yaze::gui::EditorCardManager::Get () static
Definition at line 14 of file editor_card_manager.cc.
Referenced by yaze::editor::EditorManager::DrawContextSensitiveCardControl(), yaze::editor::GraphicsEditor::Initialize(), yaze::editor::ScreenEditor::Initialize(), yaze::editor::MessageEditor::Initialize(), yaze::editor::OverworldEditor::Initialize(), yaze::editor::SpriteEditor::Initialize(), yaze::editor::EditorManager::Initialize(), yaze::emu::Emulator::Initialize(), yaze::editor::DungeonEditorV2::Initialize(), yaze::editor::AssemblyEditor::Load(), yaze::gui::RegisterCard(), yaze::editor::EditorManager::Update(), and yaze::gui::CardRegistration::~CardRegistration().
RegisterCard()
void yaze::gui::EditorCardManager::RegisterCard (const CardInfo & info)
Definition at line 19 of file editor_card_manager.cc.
References yaze::gui::CardInfo::card_id, cards_, and yaze::gui::CardInfo::display_name.
Referenced by yaze::gui::RegisterCard().
UnregisterCard()
void yaze::gui::EditorCardManager::UnregisterCard (const std::string & card_id)
Definition at line 37 of file editor_card_manager.cc.
References cards_.
Referenced by yaze::gui::CardRegistration::~CardRegistration().
ClearAllCards()
void yaze::gui::EditorCardManager::ClearAllCards ()
Definition at line 45 of file editor_card_manager.cc.
References cards_.
ShowCard()
bool yaze::gui::EditorCardManager::ShowCard (const std::string & card_id)
Definition at line 50 of file editor_card_manager.cc.
References cards_.
Referenced by LoadPreset().
HideCard()
bool yaze::gui::EditorCardManager::HideCard (const std::string & card_id)
Definition at line 69 of file editor_card_manager.cc.
References cards_.
ToggleCard()
bool yaze::gui::EditorCardManager::ToggleCard (const std::string & card_id)
Definition at line 88 of file editor_card_manager.cc.
References cards_.
Referenced by DrawViewMenuSection().
IsCardVisible()
bool yaze::gui::EditorCardManager::IsCardVisible (const std::string & card_id) const
Definition at line 110 of file editor_card_manager.cc.
References cards_.
ShowAllCardsInCategory()
void yaze::gui::EditorCardManager::ShowAllCardsInCategory (const std::string & category)
Definition at line 118 of file editor_card_manager.cc.
References cards_.
Referenced by DrawCompactCardControl(), DrawViewMenuAll(), and yaze::editor::EditorManager::Initialize().
HideAllCardsInCategory()
void yaze::gui::EditorCardManager::HideAllCardsInCategory (const std::string & category)
Definition at line 127 of file editor_card_manager.cc.
References cards_.
Referenced by DrawCompactCardControl(), and DrawViewMenuAll().
ShowOnlyCard()
void yaze::gui::EditorCardManager::ShowOnlyCard (const std::string & card_id)
Definition at line 136 of file editor_card_manager.cc.
References cards_.
GetCardsInCategory()
std::vector< CardInfo > yaze::gui::EditorCardManager::GetCardsInCategory (const std::string & category) const
Definition at line 158 of file editor_card_manager.cc.
References cards_.
Referenced by DrawCompactCardControl(), DrawInlineCardToggles(), and DrawViewMenuSection().
GetAllCategories()
std::vector< std::string > yaze::gui::EditorCardManager::GetAllCategories () const
Definition at line 176 of file editor_card_manager.cc.
References cards_.
Referenced by DrawCardBrowser(), and DrawViewMenuAll().
GetCardInfo()
const CardInfo * yaze::gui::EditorCardManager::GetCardInfo (const std::string & card_id) const
Definition at line 189 of file editor_card_manager.cc.
References cards_.
DrawViewMenuSection()
void yaze::gui::EditorCardManager::DrawViewMenuSection (const std::string & category)
Definition at line 194 of file editor_card_manager.cc.
References GetCardsInCategory(), and ToggleCard().
Referenced by DrawViewMenuAll().
DrawViewMenuAll()
void yaze::gui::EditorCardManager::DrawViewMenuAll ()
Definition at line 219 of file editor_card_manager.cc.
References DrawViewMenuSection(), GetAllCategories(), HideAll(), HideAllCardsInCategory(), ICON_MD_DASHBOARD, ICON_MD_VISIBILITY, ICON_MD_VISIBILITY_OFF, ShowAll(), and ShowAllCardsInCategory().
DrawCompactCardControl()
void yaze::gui::EditorCardManager::DrawCompactCardControl (const std::string & category)
Definition at line 264 of file editor_card_manager.cc.
References GetCardsInCategory(), HideAllCardsInCategory(), ICON_MD_DASHBOARD, ICON_MD_VIEW_MODULE, ICON_MD_VISIBILITY, ICON_MD_VISIBILITY_OFF, and ShowAllCardsInCategory().
DrawInlineCardToggles()
void yaze::gui::EditorCardManager::DrawInlineCardToggles (const std::string & category)
Definition at line 330 of file editor_card_manager.cc.
References GetCardsInCategory(), and ICON_MD_DASHBOARD.
DrawCardBrowser()
void yaze::gui::EditorCardManager::DrawCardBrowser (bool * p_open)
Definition at line 354 of file editor_card_manager.cc.
References DrawCardBrowserTable(), DrawPresetsTab(), GetAllCategories(), GetCardCount(), GetVisibleCardCount(), ICON_MD_APPS, ICON_MD_BOOKMARK, ICON_MD_CLEAR, ICON_MD_DASHBOARD, ICON_MD_INFO, and ICON_MD_SEARCH.
Referenced by yaze::editor::EditorManager::Update().
DrawCardBrowserTable()
void yaze::gui::EditorCardManager::DrawCardBrowserTable (const char * search_filter, const std::string & category_filter)
Definition at line 417 of file editor_card_manager.cc.
References cards_.
Referenced by DrawCardBrowser().
DrawPresetsTab()
void yaze::gui::EditorCardManager::DrawPresetsTab ()
Definition at line 504 of file editor_card_manager.cc.
References DeletePreset(), GetPresets(), ICON_MD_BOOKMARK, ICON_MD_DELETE, ICON_MD_FOLDER_OPEN, ICON_MD_SAVE, LoadPreset(), and SavePreset().
Referenced by DrawCardBrowser().
SavePreset()
void yaze::gui::EditorCardManager::SavePreset (const std::string & name, const std::string & description = "")
Definition at line 560 of file editor_card_manager.cc.
References cards_, yaze::gui::EditorCardManager::WorkspacePreset::description, yaze::gui::EditorCardManager::WorkspacePreset::name, presets_, SavePresetsToFile(), and yaze::gui::EditorCardManager::WorkspacePreset::visible_cards.
Referenced by DrawPresetsTab().
LoadPreset()
bool yaze::gui::EditorCardManager::LoadPreset (const std::string & name)
Definition at line 579 of file editor_card_manager.cc.
References HideAll(), presets_, and ShowCard().
Referenced by DrawPresetsTab().
DeletePreset()
void yaze::gui::EditorCardManager::DeletePreset (const std::string & name)
Definition at line 599 of file editor_card_manager.cc.
References presets_, and SavePresetsToFile().
Referenced by DrawPresetsTab().
GetPresets()
std::vector< EditorCardManager::WorkspacePreset > yaze::gui::EditorCardManager::GetPresets () const
Definition at line 608 of file editor_card_manager.cc.
References presets_.
Referenced by DrawPresetsTab().
ShowAll()
void yaze::gui::EditorCardManager::ShowAll ()
Definition at line 616 of file editor_card_manager.cc.
References cards_.
Referenced by DrawViewMenuAll().
HideAll()
void yaze::gui::EditorCardManager::HideAll ()
Definition at line 625 of file editor_card_manager.cc.
References cards_.
Referenced by DrawViewMenuAll(), and LoadPreset().
ResetToDefaults()
void yaze::gui::EditorCardManager::ResetToDefaults ()
Definition at line 634 of file editor_card_manager.cc.
References cards_.
GetCardCount()
size_t yaze::gui::EditorCardManager::GetCardCount () const inline
Definition at line 128 of file editor_card_manager.h.
References cards_.
Referenced by DrawCardBrowser().
GetVisibleCardCount()
size_t yaze::gui::EditorCardManager::GetVisibleCardCount () const
Definition at line 650 of file editor_card_manager.cc.
References cards_.
Referenced by DrawCardBrowser().
operator=()
EditorCardManager & yaze::gui::EditorCardManager::operator= (const EditorCardManager &) private delete
SavePresetsToFile()
void yaze::gui::EditorCardManager::SavePresetsToFile () private
Todo:
Implement file I/O
Definition at line 660 of file editor_card_manager.cc.
References presets_.
Referenced by DeletePreset(), and SavePreset().
LoadPresetsFromFile()
void yaze::gui::EditorCardManager::LoadPresetsFromFile () private
Todo:
Implement file I/O
Definition at line 666 of file editor_card_manager.cc.
Member Data Documentation
cards_
std::unordered_map<std::string, CardInfo> yaze::gui::EditorCardManager::cards_ private
Definition at line 137 of file editor_card_manager.h.
Referenced by ClearAllCards(), DrawCardBrowserTable(), GetAllCategories(), GetCardCount(), GetCardInfo(), GetCardsInCategory(), GetVisibleCardCount(), HideAll(), HideAllCardsInCategory(), HideCard(), IsCardVisible(), RegisterCard(), ResetToDefaults(), SavePreset(), ShowAll(), ShowAllCardsInCategory(), ShowCard(), ShowOnlyCard(), ToggleCard(), and UnregisterCard().
presets_
std::unordered_map<std::string, WorkspacePreset> yaze::gui::EditorCardManager::presets_ private
Definition at line 138 of file editor_card_manager.h.
Referenced by DeletePreset(), GetPresets(), LoadPreset(), SavePreset(), and SavePresetsToFile().
The documentation for this class was generated from the following files:
src/app/gui/editor_card_manager.h
src/app/gui/editor_card_manager.cc