yaze: yaze::zelda3::MockRoomGenerator Class Reference
yaze::zelda3::MockRoomGenerator Class Reference
Mock room data generator.
Static Public Member Functions
static Room GenerateMockRoom (int room_id, Rom *rom)
Static Private Member Functions
static void GenerateMockObjects (Room &room, int room_id)
Detailed Description
Mock room data generator.
Definition at line 145 of file dungeon_object_renderer_mock_test.cc.
Member Function Documentation
GenerateMockRoom()
static Room yaze::zelda3::MockRoomGenerator::GenerateMockRoom (int room_id, Rom * rom) inline static
Definition at line 147 of file dungeon_object_renderer_mock_test.cc.
References GenerateMockObjects(), yaze::zelda3::Room::SetBlockset(), yaze::zelda3::Room::SetFloor1(), yaze::zelda3::Room::SetFloor2(), yaze::zelda3::Room::SetMessageId(), yaze::zelda3::Room::SetPalette(), and yaze::zelda3::Room::SetSpriteset().
Referenced by yaze::zelda3::DungeonObjectRendererMockTest::GenerateMockRoomData().
GenerateMockObjects()
static void yaze::zelda3::MockRoomGenerator::GenerateMockObjects (Room & room, int room_id) inline static private
Definition at line 165 of file dungeon_object_renderer_mock_test.cc.
References yaze::zelda3::Room::AddTileObject().
Referenced by GenerateMockRoom().
The documentation for this class was generated from the following file:
test/unit/zelda3/dungeon_object_renderer_mock_test.cc