#ifndef YAZE_APP_EDITOR_SYSTEM_SESSION_COORDINATOR_H_
#include "app/editor/system/session/session_coordinator.h"
#define YAZE_APP_EDITOR_SYSTEM_SESSION_COORDINATOR_H_
#endif  // YAZE_APP_EDITOR_SYSTEM_SESSION_COORDINATOR_H_
