yaze: yaze::cli::util::LoadingIndicator Class Reference
yaze::cli::util::LoadingIndicator Class Reference
#include <terminal_colors.h>
Public Member Functions
LoadingIndicator (const std::string &message, bool show=true)
~LoadingIndicator ()
void Start ()
void Stop ()
void UpdateMessage (const std::string &message)
Private Attributes
std::string message_
bool show_
bool running_
std::thread thread_
Detailed Description
Definition at line 64 of file terminal_colors.h.
Constructor & Destructor Documentation
LoadingIndicator()
yaze::cli::util::LoadingIndicator::LoadingIndicator (const std::string & message, bool show = true) inline
Definition at line 66 of file terminal_colors.h.
~LoadingIndicator()
yaze::cli::util::LoadingIndicator::~LoadingIndicator () inline
Definition at line 69 of file terminal_colors.h.
References Stop().
Member Function Documentation
Start()
void yaze::cli::util::LoadingIndicator::Start () inline
Definition at line 73 of file terminal_colors.h.
References yaze::cli::util::colors::kBold, yaze::cli::util::colors::kCyan, yaze::cli::util::colors::kReset, message_, running_, show_, and thread_.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage().
Stop()
void yaze::cli::util::LoadingIndicator::Stop () inline
Definition at line 93 of file terminal_colors.h.
References running_, and thread_.
Referenced by yaze::cli::agent::ConversationalAgentService::SendMessage(), and ~LoadingIndicator().
UpdateMessage()
void yaze::cli::util::LoadingIndicator::UpdateMessage (const std::string & message) inline
Definition at line 102 of file terminal_colors.h.
References message_.
Member Data Documentation
message_
std::string yaze::cli::util::LoadingIndicator::message_ private
Definition at line 107 of file terminal_colors.h.
Referenced by Start(), and UpdateMessage().
show_
bool yaze::cli::util::LoadingIndicator::show_ private
Definition at line 108 of file terminal_colors.h.
Referenced by Start().
running_
bool yaze::cli::util::LoadingIndicator::running_ private
Definition at line 109 of file terminal_colors.h.
Referenced by Start(), and Stop().
thread_
std::thread yaze::cli::util::LoadingIndicator::thread_ private
Definition at line 110 of file terminal_colors.h.
Referenced by Start(), and Stop().
The documentation for this class was generated from the following file:
src/cli/util/terminal_colors.h