yaze: src/cli/cli_main.cc File Reference
cli_main.cc File Reference
#include <cstdlib>
#include <iostream>
#include <optional>
#include <string>
#include <string_view>
#include <vector>
#include "absl/flags/declare.h"
#include "absl/flags/flag.h"
#include "absl/strings/match.h"
#include "absl/strings/str_format.h"
#include "cli/modern_cli.h"
#include "cli/tui.h"
#include "cli/z3ed_ascii_logo.h"
#include "yaze_config.h"
Classes
struct anonymous_namespace{cli_main.cc}::ParsedGlobals
Namespaces
namespace anonymous_namespace{cli_main.cc}
Functions
ABSL_FLAG (bool, tui, false, "Launch interactive Text User Interface")
ABSL_FLAG (bool, quiet, false, "Suppress non-essential output")
ABSL_FLAG (bool, version, false, "Show version information")
ABSL_DECLARE_FLAG (std::string, rom)
ABSL_DECLARE_FLAG (std::string, ai_provider)
ABSL_DECLARE_FLAG (std::string, ai_model)
ABSL_DECLARE_FLAG (std::string, gemini_api_key)
ABSL_DECLARE_FLAG (std::string, ollama_host)
ABSL_DECLARE_FLAG (std::string, prompt_version)
ABSL_DECLARE_FLAG (bool, use_function_calling)
void anonymous_namespace{cli_main.cc}::PrintVersion ()
void anonymous_namespace{cli_main.cc}::PrintCompactHelp ()
ParsedGlobals anonymous_namespace{cli_main.cc}::ParseGlobalFlags (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
ABSL_FLAG() [1/3]
ABSL_FLAG (bool , tui , false , "Launch interactive Text User Interface")
ABSL_FLAG() [2/3]
ABSL_FLAG (bool , quiet , false , "Suppress non-essential output")
ABSL_FLAG() [3/3]
ABSL_FLAG (bool , version , false , "Show version information")
ABSL_DECLARE_FLAG() [1/7]
ABSL_DECLARE_FLAG (std::string , rom)
ABSL_DECLARE_FLAG() [2/7]
ABSL_DECLARE_FLAG (std::string , ai_provider)
ABSL_DECLARE_FLAG() [3/7]
ABSL_DECLARE_FLAG (std::string , ai_model)
ABSL_DECLARE_FLAG() [4/7]
ABSL_DECLARE_FLAG (std::string , gemini_api_key)
ABSL_DECLARE_FLAG() [5/7]
ABSL_DECLARE_FLAG (std::string , ollama_host)
ABSL_DECLARE_FLAG() [6/7]
ABSL_DECLARE_FLAG (std::string , prompt_version)
ABSL_DECLARE_FLAG() [7/7]
ABSL_DECLARE_FLAG (bool , use_function_calling)
main()
int main (int argc, char * argv[])
Definition at line 273 of file cli_main.cc.
References anonymous_namespace{cli_main.cc}::ParseGlobalFlags(), yaze::cli::ModernCLI::PrintCategoryHelp(), yaze::cli::ModernCLI::PrintCommandSummary(), anonymous_namespace{cli_main.cc}::PrintCompactHelp(), anonymous_namespace{cli_main.cc}::PrintVersion(), yaze::cli::ModernCLI::Run(), and yaze::cli::ShowMain().