yaze: ROMPatchUtility Class Reference
ROMPatchUtility Class Reference
Static Public Member Functions
static absl::Status CreateV3PatchedROM (const std::string &input_rom_path, const std::string &output_rom_path)
Static Private Member Functions
static absl::Status ApplyV3Patch (Rom &rom)
Detailed Description
Definition at line 14 of file rom_patch_utility.cc.
Member Function Documentation
CreateV3PatchedROM()
static absl::Status ROMPatchUtility::CreateV3PatchedROM (const std::string & input_rom_path, const std::string & output_rom_path) inline static
Definition at line 16 of file rom_patch_utility.cc.
References ApplyV3Patch(), yaze::Rom::SaveSettings::filename, yaze::Rom::LoadFromFile(), RETURN_IF_ERROR, and yaze::Rom::SaveToFile().
Referenced by main().
ApplyV3Patch()
static absl::Status ROMPatchUtility::ApplyV3Patch (Rom & rom) inline static private
Definition at line 30 of file rom_patch_utility.cc.
References yaze::zelda3::kOverworldMessagesExpanded, yaze::zelda3::kOverworldScreenSize, yaze::zelda3::OverworldCustomAnimatedGFXArray, yaze::zelda3::OverworldCustomAnimatedGFXEnabled, yaze::zelda3::OverworldCustomAreaSpecificBGEnabled, yaze::zelda3::OverworldCustomAreaSpecificBGPalette, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::zelda3::OverworldCustomMainPaletteArray, yaze::zelda3::OverworldCustomMainPaletteEnabled, yaze::zelda3::OverworldCustomMosaicArray, yaze::zelda3::OverworldCustomMosaicEnabled, yaze::zelda3::OverworldCustomSubscreenOverlayArray, yaze::zelda3::OverworldCustomSubscreenOverlayEnabled, yaze::zelda3::OverworldCustomTileGFXGroupArray, yaze::zelda3::OverworldCustomTileGFXGroupEnabled, and yaze::Rom::WriteByte().
Referenced by CreateV3PatchedROM().
The documentation for this class was generated from the following file:
tools/test_helpers/rom_patch_utility.cc