yaze: yaze::editor::PopupManager Class Reference
yaze::editor::PopupManager Class Reference
#include <popup_manager.h>
Public Member Functions
PopupManager (EditorManager *editor_manager)
void Initialize ()
void DrawPopups ()
void Show (const char *name)
void Hide (const char *name)
bool IsVisible (const char *name) const
void SetStatus (const absl::Status &status)
absl::Status GetStatus () const
Private Member Functions
bool BeginCentered (const char *name)
void DrawAboutPopup ()
void DrawRomInfoPopup ()
void DrawStatusPopup ()
void DrawSaveAsPopup ()
void DrawNewProjectPopup ()
void DrawSupportedFeaturesPopup ()
void DrawOpenRomHelpPopup ()
void DrawManageProjectPopup ()
void DrawGettingStartedPopup ()
void DrawAsarIntegrationPopup ()
void DrawBuildInstructionsPopup ()
void DrawCLIUsagePopup ()
void DrawTroubleshootingPopup ()
void DrawContributingPopup ()
void DrawWhatsNewPopup ()
void DrawWorkspaceHelpPopup ()
void DrawSessionLimitWarningPopup ()
void DrawLayoutResetConfirmPopup ()
void DrawDisplaySettingsPopup ()
Private Attributes
EditorManager * editor_manager_
std::unordered_map< std::string, PopupParams > popups_
absl::Status status_
bool show_status_ = false
absl::Status prev_status_
Detailed Description
Definition at line 23 of file popup_manager.h.
Constructor & Destructor Documentation
PopupManager()
yaze::editor::PopupManager::PopupManager (EditorManager * editor_manager)
Definition at line 15 of file popup_manager.cc.
Member Function Documentation
Initialize()
void yaze::editor::PopupManager::Initialize ()
Definition at line 18 of file popup_manager.cc.
References DrawAboutPopup(), DrawAsarIntegrationPopup(), DrawBuildInstructionsPopup(), DrawCLIUsagePopup(), DrawContributingPopup(), DrawDisplaySettingsPopup(), DrawGettingStartedPopup(), DrawLayoutResetConfirmPopup(), DrawManageProjectPopup(), DrawNewProjectPopup(), DrawOpenRomHelpPopup(), DrawRomInfoPopup(), DrawSaveAsPopup(), DrawSessionLimitWarningPopup(), DrawSupportedFeaturesPopup(), DrawTroubleshootingPopup(), DrawWhatsNewPopup(), DrawWorkspaceHelpPopup(), and popups_.
DrawPopups()
void yaze::editor::PopupManager::DrawPopups ()
Definition at line 46 of file popup_manager.cc.
References DrawStatusPopup(), and popups_.
Show()
void yaze::editor::PopupManager::Show (const char * name)
Definition at line 69 of file popup_manager.cc.
References popups_.
Referenced by yaze::editor::MessageEditor::DrawExpandedMessageSettings().
Hide()
void yaze::editor::PopupManager::Hide (const char * name)
Definition at line 76 of file popup_manager.cc.
References popups_.
Referenced by DrawAboutPopup(), DrawAsarIntegrationPopup(), DrawBuildInstructionsPopup(), DrawCLIUsagePopup(), DrawContributingPopup(), DrawDisplaySettingsPopup(), DrawGettingStartedPopup(), DrawLayoutResetConfirmPopup(), DrawManageProjectPopup(), DrawNewProjectPopup(), DrawOpenRomHelpPopup(), DrawRomInfoPopup(), DrawSaveAsPopup(), DrawSessionLimitWarningPopup(), DrawSupportedFeaturesPopup(), DrawTroubleshootingPopup(), DrawWhatsNewPopup(), and DrawWorkspaceHelpPopup().
IsVisible()
bool yaze::editor::PopupManager::IsVisible (const char * name) const
Definition at line 84 of file popup_manager.cc.
References popups_.
SetStatus()
void yaze::editor::PopupManager::SetStatus (const absl::Status & status)
Definition at line 92 of file popup_manager.cc.
References prev_status_, show_status_, and status_.
GetStatus()
absl::Status yaze::editor::PopupManager::GetStatus () const inline
Definition at line 46 of file popup_manager.h.
References status_.
BeginCentered()
bool yaze::editor::PopupManager::BeginCentered (const char * name) private
Definition at line 100 of file popup_manager.cc.
Referenced by DrawStatusPopup().
DrawAboutPopup()
void yaze::editor::PopupManager::DrawAboutPopup () private
Definition at line 132 of file popup_manager.cc.
References editor_manager_, Hide(), yaze::gui::kDefaultModalSize, and yaze::editor::EditorManager::version().
Referenced by Initialize().
DrawRomInfoPopup()
void yaze::editor::PopupManager::DrawRomInfoPopup () private
Definition at line 144 of file popup_manager.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::util::HexLongLong(), Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawStatusPopup()
void yaze::editor::PopupManager::DrawStatusPopup () private
Definition at line 110 of file popup_manager.cc.
References BeginCentered(), ICON_MD_CONTENT_COPY, ICON_MD_ERROR, yaze::gui::kDefaultModalSize, prev_status_, show_status_, and status_.
Referenced by DrawPopups().
DrawSaveAsPopup()
void yaze::editor::PopupManager::DrawSaveAsPopup () private
Definition at line 156 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawNewProjectPopup()
void yaze::editor::PopupManager::DrawNewProjectPopup () private
Definition at line 170 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawSupportedFeaturesPopup()
void yaze::editor::PopupManager::DrawSupportedFeaturesPopup () private
Definition at line 210 of file popup_manager.cc.
References Hide(), ICON_MD_BUILD, ICON_MD_CASTLE, ICON_MD_COLOR_LENS, ICON_MD_FOLDER, ICON_MD_LAYERS, ICON_MD_PALETTE, ICON_MD_SAVE, and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawOpenRomHelpPopup()
void yaze::editor::PopupManager::DrawOpenRomHelpPopup () private
Definition at line 270 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawManageProjectPopup()
void yaze::editor::PopupManager::DrawManageProjectPopup () private
Definition at line 283 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawGettingStartedPopup()
void yaze::editor::PopupManager::DrawGettingStartedPopup () private
Definition at line 298 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawAsarIntegrationPopup()
void yaze::editor::PopupManager::DrawAsarIntegrationPopup () private
Definition at line 312 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawBuildInstructionsPopup()
void yaze::editor::PopupManager::DrawBuildInstructionsPopup () private
Definition at line 327 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawCLIUsagePopup()
void yaze::editor::PopupManager::DrawCLIUsagePopup () private
Definition at line 344 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawTroubleshootingPopup()
void yaze::editor::PopupManager::DrawTroubleshootingPopup () private
Definition at line 359 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawContributingPopup()
void yaze::editor::PopupManager::DrawContributingPopup () private
Definition at line 373 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawWhatsNewPopup()
void yaze::editor::PopupManager::DrawWhatsNewPopup () private
Definition at line 389 of file popup_manager.cc.
References Hide(), ICON_MD_BUILD, ICON_MD_EDIT, ICON_MD_PALETTE, ICON_MD_SETTINGS, and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawWorkspaceHelpPopup()
void yaze::editor::PopupManager::DrawWorkspaceHelpPopup () private
Definition at line 441 of file popup_manager.cc.
References Hide(), and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawSessionLimitWarningPopup()
void yaze::editor::PopupManager::DrawSessionLimitWarningPopup () private
Definition at line 470 of file popup_manager.cc.
References Hide(), ICON_MD_WARNING, and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawLayoutResetConfirmPopup()
void yaze::editor::PopupManager::DrawLayoutResetConfirmPopup () private
Definition at line 487 of file popup_manager.cc.
References Hide(), ICON_MD_WARNING, and yaze::gui::kDefaultModalSize.
Referenced by Initialize().
DrawDisplaySettingsPopup()
void yaze::editor::PopupManager::DrawDisplaySettingsPopup () private
Definition at line 504 of file popup_manager.cc.
References yaze::gui::DrawDisplaySettingsForPopup(), yaze::gui::DrawFontManager(), editor_manager_, Hide(), ICON_MD_DISPLAY_SETTINGS, yaze::gui::kDefaultModalSize, yaze::editor::EditorManager::SetFontGlobalScale(), and yaze::gui::TextWithSeparators().
Referenced by Initialize().
Member Data Documentation
editor_manager_
EditorManager* yaze::editor::PopupManager::editor_manager_ private
Definition at line 93 of file popup_manager.h.
Referenced by DrawAboutPopup(), DrawDisplaySettingsPopup(), and DrawRomInfoPopup().
popups_
std::unordered_map<std::string, PopupParams> yaze::editor::PopupManager::popups_ private
Definition at line 94 of file popup_manager.h.
Referenced by DrawPopups(), Hide(), Initialize(), IsVisible(), and Show().
status_
absl::Status yaze::editor::PopupManager::status_ private
Definition at line 95 of file popup_manager.h.
Referenced by DrawStatusPopup(), GetStatus(), and SetStatus().
show_status_
bool yaze::editor::PopupManager::show_status_ = false private
Definition at line 96 of file popup_manager.h.
Referenced by DrawStatusPopup(), and SetStatus().
prev_status_
absl::Status yaze::editor::PopupManager::prev_status_ private
Definition at line 97 of file popup_manager.h.
Referenced by DrawStatusPopup(), and SetStatus().
The documentation for this class was generated from the following files:
src/app/editor/system/popup_manager.h
src/app/editor/system/popup_manager.cc