yaze: yaze::zelda3::DungeonRenderingIntegrationTest Class Reference
yaze::zelda3::DungeonRenderingIntegrationTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Room CreateTestRoom (int room_id)
gfx::SnesPalette CreateTestPalette ()
gfx::PaletteGroup CreateTestPaletteGroup ()
Protected Attributes
std::unique_ptr< Rom > rom_
Private Attributes
Room room_0x00_
Room room_0x01_
Detailed Description
Definition at line 15 of file dungeon_rendering_test.cc.
Member Function Documentation
SetUp()
void yaze::zelda3::DungeonRenderingIntegrationTest::SetUp () inline override protected
Definition at line 17 of file dungeon_rendering_test.cc.
References CreateTestRoom(), rom_, room_0x00_, and room_0x01_.
TearDown()
void yaze::zelda3::DungeonRenderingIntegrationTest::TearDown () inline override protected
Definition at line 29 of file dungeon_rendering_test.cc.
References rom_.
CreateTestRoom()
Room yaze::zelda3::DungeonRenderingIntegrationTest::CreateTestRoom (int room_id) inline protected
Definition at line 36 of file dungeon_rendering_test.cc.
References yaze::zelda3::Room::AddObject(), and rom_.
Referenced by SetUp().
CreateTestPalette()
gfx::SnesPalette yaze::zelda3::DungeonRenderingIntegrationTest::CreateTestPalette () inline protected
Definition at line 71 of file dungeon_rendering_test.cc.
References yaze::gfx::SnesPalette::AddColor().
Referenced by CreateTestPaletteGroup().
CreateTestPaletteGroup()
gfx::PaletteGroup yaze::zelda3::DungeonRenderingIntegrationTest::CreateTestPaletteGroup () inline protected
Definition at line 85 of file dungeon_rendering_test.cc.
References yaze::gfx::PaletteGroup::AddPalette(), and CreateTestPalette().
Member Data Documentation
rom_
std::unique_ptr<Rom> yaze::zelda3::DungeonRenderingIntegrationTest::rom_ protected
Definition at line 33 of file dungeon_rendering_test.cc.
Referenced by CreateTestRoom(), SetUp(), and TearDown().
room_0x00_
Room yaze::zelda3::DungeonRenderingIntegrationTest::room_0x00_ private
Definition at line 92 of file dungeon_rendering_test.cc.
Referenced by SetUp().
room_0x01_
Room yaze::zelda3::DungeonRenderingIntegrationTest::room_0x01_ private
Definition at line 93 of file dungeon_rendering_test.cc.
Referenced by SetUp().
The documentation for this class was generated from the following file:
test/integration/zelda3/dungeon_rendering_test.cc