yaze: yaze::test::DungeonObjectRenderingTests Class Reference
yaze::test::DungeonObjectRenderingTests Class Reference
Advanced tests for actual dungeon object rendering scenarios.
Classes
struct DungeonScenario
Protected Member Functions
void SetUp () override
void TearDown () override
Protected Member Functions inherited from yaze::test::TestRomManager::BoundRomTest
void SetUp () override
void TearDown () override
Rom * rom ()
const Rom * rom () const
std::string GetBoundRomPath () const
Protected Attributes
std::unique_ptr< zelda3::ObjectRenderer > renderer_
std::vector< DungeonScenario > scenarios_
std::vector< gfx::SnesPalette > test_palettes_
Private Member Functions
void SetupDungeonScenarios ()
void SetupTestPalettes ()
void CreateEmptyRoomScenario ()
void CreateMultiObjectScenario ()
void CreateComplexRoomScenario ()
void CreateLargeRoomScenario ()
void CreateBossRoomScenario ()
void CreatePuzzleRoomScenario ()
void CreateDungeonPalette ()
void CreateIcePalacePalette ()
void CreateDesertPalacePalette ()
void CreateDarkPalacePalette ()
void CreateBossRoomPalette ()
Detailed Description
Advanced tests for actual dungeon object rendering scenarios.
These tests focus on real-world dungeon editing scenarios including:
Complex room layouts with multiple object types
Object interaction and collision detection
Performance with realistic dungeon configurations
Edge cases in dungeon editing workflows
Definition at line 28 of file dungeon_object_rendering_tests.cc.
Member Function Documentation
SetUp()
void yaze::test::DungeonObjectRenderingTests::SetUp () inline override protected
Definition at line 30 of file dungeon_object_rendering_tests.cc.
References renderer_, yaze::test::TestRomManager::BoundRomTest::rom(), SetupDungeonScenarios(), and SetupTestPalettes().
TearDown()
void yaze::test::DungeonObjectRenderingTests::TearDown () inline override protected
Definition at line 43 of file dungeon_object_rendering_tests.cc.
References renderer_.
SetupDungeonScenarios()
void yaze::test::DungeonObjectRenderingTests::SetupDungeonScenarios () inline private
Definition at line 63 of file dungeon_object_rendering_tests.cc.
References CreateBossRoomScenario(), CreateComplexRoomScenario(), CreateEmptyRoomScenario(), CreateLargeRoomScenario(), CreateMultiObjectScenario(), and CreatePuzzleRoomScenario().
Referenced by SetUp().
SetupTestPalettes()
void yaze::test::DungeonObjectRenderingTests::SetupTestPalettes () inline private
Definition at line 83 of file dungeon_object_rendering_tests.cc.
References CreateBossRoomPalette(), CreateDarkPalacePalette(), CreateDesertPalacePalette(), CreateDungeonPalette(), and CreateIcePalacePalette().
Referenced by SetUp().
CreateEmptyRoomScenario()
void yaze::test::DungeonObjectRenderingTests::CreateEmptyRoomScenario () inline private
Definition at line 92 of file dungeon_object_rendering_tests.cc.
References yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_height, yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_width, yaze::test::DungeonObjectRenderingTests::DungeonScenario::name, yaze::test::DungeonObjectRenderingTests::DungeonScenario::objects, yaze::test::DungeonObjectRenderingTests::DungeonScenario::palette, yaze::test::TestRomManager::BoundRomTest::rom(), scenarios_, and test_palettes_.
Referenced by SetupDungeonScenarios().
CreateMultiObjectScenario()
void yaze::test::DungeonObjectRenderingTests::CreateMultiObjectScenario () inline private
Definition at line 122 of file dungeon_object_rendering_tests.cc.
References yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_height, yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_width, yaze::test::DungeonObjectRenderingTests::DungeonScenario::name, yaze::test::DungeonObjectRenderingTests::DungeonScenario::objects, yaze::test::DungeonObjectRenderingTests::DungeonScenario::palette, yaze::test::TestRomManager::BoundRomTest::rom(), scenarios_, and test_palettes_.
Referenced by SetupDungeonScenarios().
CreateComplexRoomScenario()
void yaze::test::DungeonObjectRenderingTests::CreateComplexRoomScenario () inline private
Definition at line 152 of file dungeon_object_rendering_tests.cc.
References yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_height, yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_width, yaze::test::DungeonObjectRenderingTests::DungeonScenario::name, yaze::test::DungeonObjectRenderingTests::DungeonScenario::objects, yaze::test::DungeonObjectRenderingTests::DungeonScenario::palette, yaze::test::TestRomManager::BoundRomTest::rom(), scenarios_, and test_palettes_.
Referenced by SetupDungeonScenarios().
CreateLargeRoomScenario()
void yaze::test::DungeonObjectRenderingTests::CreateLargeRoomScenario () inline private
Definition at line 184 of file dungeon_object_rendering_tests.cc.
References yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_height, yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_width, yaze::test::DungeonObjectRenderingTests::DungeonScenario::name, yaze::test::DungeonObjectRenderingTests::DungeonScenario::objects, yaze::test::DungeonObjectRenderingTests::DungeonScenario::palette, yaze::test::TestRomManager::BoundRomTest::rom(), scenarios_, and test_palettes_.
Referenced by SetupDungeonScenarios().
CreateBossRoomScenario()
void yaze::test::DungeonObjectRenderingTests::CreateBossRoomScenario () inline private
Definition at line 210 of file dungeon_object_rendering_tests.cc.
References yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_height, yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_width, yaze::test::DungeonObjectRenderingTests::DungeonScenario::name, yaze::test::DungeonObjectRenderingTests::DungeonScenario::objects, yaze::test::DungeonObjectRenderingTests::DungeonScenario::palette, yaze::test::TestRomManager::BoundRomTest::rom(), scenarios_, and test_palettes_.
Referenced by SetupDungeonScenarios().
CreatePuzzleRoomScenario()
void yaze::test::DungeonObjectRenderingTests::CreatePuzzleRoomScenario () inline private
Definition at line 244 of file dungeon_object_rendering_tests.cc.
References yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_height, yaze::test::DungeonObjectRenderingTests::DungeonScenario::expected_width, yaze::test::DungeonObjectRenderingTests::DungeonScenario::name, yaze::test::DungeonObjectRenderingTests::DungeonScenario::objects, yaze::test::DungeonObjectRenderingTests::DungeonScenario::palette, yaze::test::TestRomManager::BoundRomTest::rom(), scenarios_, and test_palettes_.
Referenced by SetupDungeonScenarios().
CreateDungeonPalette()
void yaze::test::DungeonObjectRenderingTests::CreateDungeonPalette () inline private
Definition at line 274 of file dungeon_object_rendering_tests.cc.
References yaze::gfx::SnesPalette::AddColor(), and test_palettes_.
Referenced by SetupTestPalettes().
CreateIcePalacePalette()
void yaze::test::DungeonObjectRenderingTests::CreateIcePalacePalette () inline private
Definition at line 296 of file dungeon_object_rendering_tests.cc.
References yaze::gfx::SnesPalette::AddColor(), and test_palettes_.
Referenced by SetupTestPalettes().
CreateDesertPalacePalette()
void yaze::test::DungeonObjectRenderingTests::CreateDesertPalacePalette () inline private
Definition at line 318 of file dungeon_object_rendering_tests.cc.
References yaze::gfx::SnesPalette::AddColor(), and test_palettes_.
Referenced by SetupTestPalettes().
CreateDarkPalacePalette()
void yaze::test::DungeonObjectRenderingTests::CreateDarkPalacePalette () inline private
Definition at line 340 of file dungeon_object_rendering_tests.cc.
References yaze::gfx::SnesPalette::AddColor(), and test_palettes_.
Referenced by SetupTestPalettes().
CreateBossRoomPalette()
void yaze::test::DungeonObjectRenderingTests::CreateBossRoomPalette () inline private
Definition at line 362 of file dungeon_object_rendering_tests.cc.
References yaze::gfx::SnesPalette::AddColor(), and test_palettes_.
Referenced by SetupTestPalettes().
Member Data Documentation
renderer_
std::unique_ptr<zelda3::ObjectRenderer> yaze::test::DungeonObjectRenderingTests::renderer_ protected
Definition at line 48 of file dungeon_object_rendering_tests.cc.
Referenced by SetUp(), and TearDown().
scenarios_
std::vector<DungeonScenario> yaze::test::DungeonObjectRenderingTests::scenarios_ protected
Definition at line 59 of file dungeon_object_rendering_tests.cc.
Referenced by CreateBossRoomScenario(), CreateComplexRoomScenario(), CreateEmptyRoomScenario(), CreateLargeRoomScenario(), CreateMultiObjectScenario(), and CreatePuzzleRoomScenario().
test_palettes_
std::vector<gfx::SnesPalette> yaze::test::DungeonObjectRenderingTests::test_palettes_ protected
Definition at line 60 of file dungeon_object_rendering_tests.cc.
Referenced by CreateBossRoomPalette(), CreateBossRoomScenario(), CreateComplexRoomScenario(), CreateDarkPalacePalette(), CreateDesertPalacePalette(), CreateDungeonPalette(), CreateEmptyRoomScenario(), CreateIcePalacePalette(), CreateLargeRoomScenario(), CreateMultiObjectScenario(), and CreatePuzzleRoomScenario().
The documentation for this class was generated from the following file:
test/integration/zelda3/dungeon_object_rendering_tests.cc