yaze: yaze::gfx::anonymous_namespace{snes_color_test.cc} Namespace Reference
yaze::gfx::anonymous_namespace{snes_color_test.cc} Namespace Reference
Classes
class SnesColorTest
Functions
TEST_F (SnesColorTest, SetRgbFromImGuiNormalizedValues)
TEST_F (SnesColorTest, SetRgbBlackColor)
TEST_F (SnesColorTest, SetRgbWhiteColor)
TEST_F (SnesColorTest, SetRgbMidRangeColor)
TEST_F (SnesColorTest, ConstructFromImVec4)
TEST_F (SnesColorTest, ConstructFromSnesValue)
TEST_F (SnesColorTest, ConstructFromSnesBlack)
TEST_F (SnesColorTest, SetSnesUpdatesRgb)
TEST_F (SnesColorTest, RgbToSnesConversion)
TEST_F (SnesColorTest, RoundTripImGuiToSnesColor)
TEST_F (SnesColorTest, MultipleSetRgbCalls)
TEST_F (SnesColorTest, HandlesMaxValues)
TEST_F (SnesColorTest, HandlesMinValues)
TEST_F (SnesColorTest, AlphaAlwaysMaximum)
TEST_F (SnesColorTest, ModifiedFlagSetOnRgbChange)
TEST_F (SnesColorTest, ModifiedFlagSetOnSnesChange)
Function Documentation
TEST_F() [1/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , SetRgbFromImGuiNormalizedValues)
Definition at line 23 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [2/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , SetRgbBlackColor)
Definition at line 38 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [3/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , SetRgbWhiteColor)
Definition at line 51 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [4/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , SetRgbMidRangeColor)
Definition at line 64 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [5/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , ConstructFromImVec4)
Definition at line 81 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb().
TEST_F() [6/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , ConstructFromSnesValue)
Definition at line 95 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb().
TEST_F() [7/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , ConstructFromSnesBlack)
Definition at line 106 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb().
TEST_F() [8/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , SetSnesUpdatesRgb)
Definition at line 120 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_snes().
TEST_F() [9/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , RgbToSnesConversion)
Definition at line 133 of file snes_color_test.cc.
References yaze::gfx::SnesColor::set_rgb(), and yaze::gfx::SnesColor::snes().
TEST_F() [10/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , RoundTripImGuiToSnesColor)
Definition at line 153 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb().
TEST_F() [11/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , MultipleSetRgbCalls)
Definition at line 170 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [12/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , HandlesMaxValues)
Definition at line 196 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [13/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , HandlesMinValues)
Definition at line 208 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [14/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , AlphaAlwaysMaximum)
Definition at line 220 of file snes_color_test.cc.
References yaze::gfx::SnesColor::rgb(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [15/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , ModifiedFlagSetOnRgbChange)
Definition at line 235 of file snes_color_test.cc.
References yaze::gfx::SnesColor::is_modified(), and yaze::gfx::SnesColor::set_rgb().
TEST_F() [16/16]
yaze::gfx::anonymous_namespace{snes_color_test.cc}::TEST_F (SnesColorTest , ModifiedFlagSetOnSnesChange)
Definition at line 246 of file snes_color_test.cc.
References yaze::gfx::SnesColor::is_modified(), and yaze::gfx::SnesColor::set_snes().