yaze: yaze::zelda3::ObjectRenderingTest Class Reference
yaze::zelda3::ObjectRenderingTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
gfx::SnesPalette CreateTestPalette ()
gfx::PaletteGroup CreateTestPaletteGroup ()
Protected Attributes
std::unique_ptr< Rom > rom_
gfx::BackgroundBuffer bg1_
gfx::BackgroundBuffer bg2_
Detailed Description
Definition at line 14 of file object_rendering_test.cc.
Member Function Documentation
SetUp()
void yaze::zelda3::ObjectRenderingTest::SetUp () inline override protected
Definition at line 16 of file object_rendering_test.cc.
References rom_.
TearDown()
void yaze::zelda3::ObjectRenderingTest::TearDown () inline override protected
Definition at line 24 of file object_rendering_test.cc.
References rom_.
CreateTestPalette()
gfx::SnesPalette yaze::zelda3::ObjectRenderingTest::CreateTestPalette () inline protected
Definition at line 33 of file object_rendering_test.cc.
References yaze::gfx::SnesPalette::AddColor().
Referenced by CreateTestPaletteGroup().
CreateTestPaletteGroup()
gfx::PaletteGroup yaze::zelda3::ObjectRenderingTest::CreateTestPaletteGroup () inline protected
Definition at line 47 of file object_rendering_test.cc.
References yaze::gfx::PaletteGroup::AddPalette(), and CreateTestPalette().
Member Data Documentation
rom_
std::unique_ptr<Rom> yaze::zelda3::ObjectRenderingTest::rom_ protected
Definition at line 28 of file object_rendering_test.cc.
Referenced by SetUp(), and TearDown().
bg1_
gfx::BackgroundBuffer yaze::zelda3::ObjectRenderingTest::bg1_ protected
Definition at line 29 of file object_rendering_test.cc.
bg2_
gfx::BackgroundBuffer yaze::zelda3::ObjectRenderingTest::bg2_ protected
Definition at line 30 of file object_rendering_test.cc.
The documentation for this class was generated from the following file:
test/unit/zelda3/dungeon/object_rendering_test.cc