set(
  YAZE_APP_EDITOR_SRC
  app/editor/editor_manager.cc
  app/editor/dungeon/dungeon_editor.cc
  app/editor/overworld/overworld_editor.cc
  app/editor/sprite/sprite_editor.cc
  app/editor/music/music_editor.cc
  app/editor/message/message_editor.cc
  app/editor/message/message_data.cc
  app/editor/code/assembly_editor.cc
  app/editor/graphics/screen_editor.cc
  app/editor/graphics/graphics_editor.cc
  app/editor/graphics/palette_editor.cc
  app/editor/graphics/tile16_editor.cc
  app/editor/graphics/gfx_group_editor.cc
  app/editor/utils/gfx_context.cc
  app/editor/overworld/entity.cc
  app/editor/system/settings_editor.cc
  app/editor/system/extension_manager.cc
)