yaze: yaze::zelda3::ComprehensiveIntegrationTest Class Reference
yaze::zelda3::ComprehensiveIntegrationTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void CreateV3PatchedROM ()
void ApplyV3Patch (Rom &rom)
Protected Attributes
std::string vanilla_rom_path_
std::string v3_rom_path_
std::unique_ptr< Rom > vanilla_rom_
std::unique_ptr< Rom > v3_rom_
std::unique_ptr< Overworld > vanilla_overworld_
std::unique_ptr< Overworld > v3_overworld_
Detailed Description
Definition at line 15 of file comprehensive_integration_test.cc.
Member Function Documentation
SetUp()
void yaze::zelda3::ComprehensiveIntegrationTest::SetUp () inline override protected
Todo:
Load graphics data when gfx system is available
Todo:
Load graphics data when gfx system is available
Definition at line 17 of file comprehensive_integration_test.cc.
References CreateV3PatchedROM(), v3_overworld_, v3_rom_, v3_rom_path_, vanilla_overworld_, vanilla_rom_, and vanilla_rom_path_.
TearDown()
void yaze::zelda3::ComprehensiveIntegrationTest::TearDown () inline override protected
Todo:
Destroy graphics data when gfx system is available
Definition at line 52 of file comprehensive_integration_test.cc.
References v3_overworld_, v3_rom_, v3_rom_path_, vanilla_overworld_, and vanilla_rom_.
CreateV3PatchedROM()
void yaze::zelda3::ComprehensiveIntegrationTest::CreateV3PatchedROM () inline protected
Definition at line 66 of file comprehensive_integration_test.cc.
References ApplyV3Patch(), yaze::Rom::LoadFromFile(), yaze::Rom::SaveToFile(), v3_rom_path_, and vanilla_rom_path_.
Referenced by SetUp().
ApplyV3Patch()
void yaze::zelda3::ComprehensiveIntegrationTest::ApplyV3Patch (Rom & rom) inline protected
Definition at line 86 of file comprehensive_integration_test.cc.
References yaze::zelda3::kOverworldMessagesExpanded, yaze::zelda3::kOverworldScreenSize, yaze::zelda3::OverworldCustomAnimatedGFXArray, yaze::zelda3::OverworldCustomAnimatedGFXEnabled, yaze::zelda3::OverworldCustomAreaSpecificBGEnabled, yaze::zelda3::OverworldCustomAreaSpecificBGPalette, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::zelda3::OverworldCustomMainPaletteArray, yaze::zelda3::OverworldCustomMainPaletteEnabled, yaze::zelda3::OverworldCustomMosaicArray, yaze::zelda3::OverworldCustomMosaicEnabled, yaze::zelda3::OverworldCustomSubscreenOverlayArray, yaze::zelda3::OverworldCustomSubscreenOverlayEnabled, yaze::zelda3::OverworldCustomTileGFXGroupArray, yaze::zelda3::OverworldCustomTileGFXGroupEnabled, and yaze::Rom::WriteByte().
Referenced by CreateV3PatchedROM().
Member Data Documentation
vanilla_rom_path_
std::string yaze::zelda3::ComprehensiveIntegrationTest::vanilla_rom_path_ protected
Definition at line 141 of file comprehensive_integration_test.cc.
Referenced by CreateV3PatchedROM(), and SetUp().
v3_rom_path_
std::string yaze::zelda3::ComprehensiveIntegrationTest::v3_rom_path_ protected
Definition at line 142 of file comprehensive_integration_test.cc.
Referenced by CreateV3PatchedROM(), SetUp(), and TearDown().
vanilla_rom_
std::unique_ptr<Rom> yaze::zelda3::ComprehensiveIntegrationTest::vanilla_rom_ protected
Definition at line 143 of file comprehensive_integration_test.cc.
Referenced by SetUp(), and TearDown().
v3_rom_
std::unique_ptr<Rom> yaze::zelda3::ComprehensiveIntegrationTest::v3_rom_ protected
Definition at line 144 of file comprehensive_integration_test.cc.
Referenced by SetUp(), and TearDown().
vanilla_overworld_
std::unique_ptr<Overworld> yaze::zelda3::ComprehensiveIntegrationTest::vanilla_overworld_ protected
Definition at line 145 of file comprehensive_integration_test.cc.
Referenced by SetUp(), and TearDown().
v3_overworld_
std::unique_ptr<Overworld> yaze::zelda3::ComprehensiveIntegrationTest::v3_overworld_ protected
Definition at line 146 of file comprehensive_integration_test.cc.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
test/unit/zelda3/comprehensive_integration_test.cc