yaze: yaze::editor::AgentChatWidget::CollaborationCallbacks Struct Reference
yaze::editor::AgentChatWidget::CollaborationCallbacks Struct Reference
#include <agent_chat_widget.h>
Classes
struct SessionContext
Public Attributes
std::function< absl::StatusOr< SessionContext >(const std::string &)> host_session
std::function< absl::StatusOr< SessionContext >(const std::string &)> join_session
std::function< absl::Status()> leave_session
std::function< absl::StatusOr< SessionContext >()> refresh_session
Detailed Description
Definition at line 51 of file agent_chat_widget.h.
Member Data Documentation
host_session
std::function<absl::StatusOr<SessionContext>(const std::string&)> yaze::editor::AgentChatWidget::CollaborationCallbacks::host_session
Definition at line 58 of file agent_chat_widget.h.
Referenced by yaze::editor::AgentChatWidget::RenderCollaborationPanel(), and yaze::editor::AgentEditor::SetupChatWidgetCallbacks().
join_session
std::function<absl::StatusOr<SessionContext>(const std::string&)> yaze::editor::AgentChatWidget::CollaborationCallbacks::join_session
Definition at line 59 of file agent_chat_widget.h.
Referenced by yaze::editor::AgentChatWidget::RenderCollaborationPanel(), and yaze::editor::AgentEditor::SetupChatWidgetCallbacks().
leave_session
std::function<absl::Status()> yaze::editor::AgentChatWidget::CollaborationCallbacks::leave_session
Definition at line 60 of file agent_chat_widget.h.
Referenced by yaze::editor::AgentChatWidget::RenderCollaborationPanel(), and yaze::editor::AgentEditor::SetupChatWidgetCallbacks().
refresh_session
std::function<absl::StatusOr<SessionContext>()> yaze::editor::AgentChatWidget::CollaborationCallbacks::refresh_session
Definition at line 61 of file agent_chat_widget.h.
Referenced by yaze::editor::AgentChatWidget::RefreshCollaboration(), yaze::editor::AgentChatWidget::RenderCollaborationPanel(), and yaze::editor::AgentEditor::SetupChatWidgetCallbacks().
The documentation for this struct was generated from the following file:
src/app/editor/agent/agent_chat_widget.h