yaze: yaze::editor::WorkspaceManager Class Reference
yaze::editor::WorkspaceManager Class Reference
Manages workspace layouts, sessions, and presets.
#include <workspace_manager.h>
Classes
struct SessionInfo
Public Member Functions
WorkspaceManager (ToastManager *toast_manager)
absl::Status SaveWorkspaceLayout (const std::string &name="")
absl::Status LoadWorkspaceLayout (const std::string &name="")
absl::Status ResetWorkspaceLayout ()
void SaveWorkspacePreset (const std::string &name)
void LoadWorkspacePreset (const std::string &name)
void LoadDeveloperLayout ()
void LoadDesignerLayout ()
void LoadModderLayout ()
void ShowAllWindows ()
void HideAllWindows ()
void MaximizeCurrentWindow ()
void RestoreAllWindows ()
void CloseAllFloatingWindows ()
size_t GetActiveSessionCount () const
bool HasDuplicateSession (const std::string &filepath) const
void set_sessions (std::deque< SessionInfo > *sessions)
Private Attributes
ToastManager * toast_manager_
std::deque< SessionInfo > * sessions_ = nullptr
std::string last_workspace_preset_
Detailed Description
Manages workspace layouts, sessions, and presets.
Definition at line 19 of file workspace_manager.h.
Constructor & Destructor Documentation
WorkspaceManager()
yaze::editor::WorkspaceManager::WorkspaceManager (ToastManager * toast_manager) inline explicit
Definition at line 28 of file workspace_manager.h.
Member Function Documentation
SaveWorkspaceLayout()
absl::Status yaze::editor::WorkspaceManager::SaveWorkspaceLayout (const std::string & name = "")
Todo:
Serialize ImGui docking layout
Definition at line 9 of file workspace_manager.cc.
References yaze::editor::kSuccess, yaze::editor::ToastManager::Show(), and toast_manager_.
LoadWorkspaceLayout()
absl::Status yaze::editor::WorkspaceManager::LoadWorkspaceLayout (const std::string & name = "")
Todo:
Deserialize ImGui docking layout
Definition at line 17 of file workspace_manager.cc.
References yaze::editor::kSuccess, yaze::editor::ToastManager::Show(), and toast_manager_.
ResetWorkspaceLayout()
absl::Status yaze::editor::WorkspaceManager::ResetWorkspaceLayout ()
Todo:
Reset to default layout
Definition at line 25 of file workspace_manager.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
SaveWorkspacePreset()
void yaze::editor::WorkspaceManager::SaveWorkspacePreset (const std::string & name)
Definition at line 33 of file workspace_manager.cc.
References yaze::editor::kSuccess, last_workspace_preset_, yaze::editor::ToastManager::Show(), and toast_manager_.
LoadWorkspacePreset()
void yaze::editor::WorkspaceManager::LoadWorkspacePreset (const std::string & name)
Definition at line 41 of file workspace_manager.cc.
References yaze::editor::kSuccess, last_workspace_preset_, yaze::editor::ToastManager::Show(), and toast_manager_.
LoadDeveloperLayout()
void yaze::editor::WorkspaceManager::LoadDeveloperLayout ()
Todo:
Load preset with all debug tools
Definition at line 49 of file workspace_manager.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
LoadDesignerLayout()
void yaze::editor::WorkspaceManager::LoadDesignerLayout ()
Todo:
Load preset focused on graphics
Definition at line 56 of file workspace_manager.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
LoadModderLayout()
void yaze::editor::WorkspaceManager::LoadModderLayout ()
Todo:
Load preset for ROM hacking
Definition at line 63 of file workspace_manager.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
ShowAllWindows()
void yaze::editor::WorkspaceManager::ShowAllWindows ()
Todo:
Set all editor windows to visible
Definition at line 70 of file workspace_manager.cc.
HideAllWindows()
void yaze::editor::WorkspaceManager::HideAllWindows ()
Todo:
Hide all editor windows
Definition at line 74 of file workspace_manager.cc.
MaximizeCurrentWindow()
void yaze::editor::WorkspaceManager::MaximizeCurrentWindow ()
Todo:
Maximize focused window
Definition at line 78 of file workspace_manager.cc.
RestoreAllWindows()
void yaze::editor::WorkspaceManager::RestoreAllWindows ()
Todo:
Restore all windows to default size
Definition at line 82 of file workspace_manager.cc.
CloseAllFloatingWindows()
void yaze::editor::WorkspaceManager::CloseAllFloatingWindows ()
Todo:
Close undocked windows
Definition at line 86 of file workspace_manager.cc.
GetActiveSessionCount()
size_t yaze::editor::WorkspaceManager::GetActiveSessionCount () const
Definition at line 90 of file workspace_manager.cc.
References sessions_.
HasDuplicateSession()
bool yaze::editor::WorkspaceManager::HasDuplicateSession (const std::string & filepath) const
Definition at line 102 of file workspace_manager.cc.
References sessions_.
set_sessions()
void yaze::editor::WorkspaceManager::set_sessions (std::deque< SessionInfo > * sessions) inline
Definition at line 54 of file workspace_manager.h.
References sessions_.
Member Data Documentation
toast_manager_
ToastManager* yaze::editor::WorkspaceManager::toast_manager_ private
Definition at line 57 of file workspace_manager.h.
Referenced by LoadDesignerLayout(), LoadDeveloperLayout(), LoadModderLayout(), LoadWorkspaceLayout(), LoadWorkspacePreset(), ResetWorkspaceLayout(), SaveWorkspaceLayout(), and SaveWorkspacePreset().
sessions_
std::deque<SessionInfo>* yaze::editor::WorkspaceManager::sessions_ = nullptr private
Definition at line 58 of file workspace_manager.h.
Referenced by GetActiveSessionCount(), HasDuplicateSession(), and set_sessions().
last_workspace_preset_
std::string yaze::editor::WorkspaceManager::last_workspace_preset_ private
Definition at line 59 of file workspace_manager.h.
Referenced by LoadWorkspacePreset(), and SaveWorkspacePreset().
The documentation for this class was generated from the following files:
src/app/editor/ui/workspace_manager.h
src/app/editor/ui/workspace_manager.cc