yaze: yaze::test::WidgetDiscoveryService Class Reference
yaze::test::WidgetDiscoveryService Class Reference
#include <widget_discovery_service.h>
Public Member Functions
WidgetDiscoveryService ()=default
void CollectWidgets (ImGuiTestContext *ctx, const DiscoverWidgetsRequest &request, DiscoverWidgetsResponse *response) const
Private Member Functions
bool MatchesWindow (absl::string_view window_name, absl::string_view filter) const
bool MatchesPathPrefix (absl::string_view path, absl::string_view prefix) const
bool MatchesType (absl::string_view type, WidgetType filter) const
std::string ExtractWindowName (absl::string_view path) const
std::string ExtractLabel (absl::string_view path) const
std::string SuggestedAction (absl::string_view type, absl::string_view label) const
Detailed Description
Definition at line 32 of file widget_discovery_service.h.
Constructor & Destructor Documentation
WidgetDiscoveryService()
yaze::test::WidgetDiscoveryService::WidgetDiscoveryService () default
Member Function Documentation
CollectWidgets()
void yaze::test::WidgetDiscoveryService::CollectWidgets (ImGuiTestContext * ctx, const DiscoverWidgetsRequest & request, DiscoverWidgetsResponse * response) const
Definition at line 26 of file widget_discovery_service.cc.
References ExtractLabel(), ExtractWindowName(), yaze::gui::WidgetIdRegistry::GetAllWidgets(), yaze::gui::WidgetIdRegistry::Instance(), MatchesPathPrefix(), MatchesType(), MatchesWindow(), and SuggestedAction().
MatchesWindow()
bool yaze::test::WidgetDiscoveryService::MatchesWindow (absl::string_view window_name, absl::string_view filter) const private
Definition at line 162 of file widget_discovery_service.cc.
Referenced by CollectWidgets().
MatchesPathPrefix()
bool yaze::test::WidgetDiscoveryService::MatchesPathPrefix (absl::string_view path, absl::string_view prefix) const private
Definition at line 171 of file widget_discovery_service.cc.
Referenced by CollectWidgets().
MatchesType()
bool yaze::test::WidgetDiscoveryService::MatchesType (absl::string_view type, WidgetType filter) const private
Definition at line 180 of file widget_discovery_service.cc.
Referenced by CollectWidgets().
ExtractWindowName()
std::string yaze::test::WidgetDiscoveryService::ExtractWindowName (absl::string_view path) const private
Definition at line 212 of file widget_discovery_service.cc.
Referenced by CollectWidgets().
ExtractLabel()
std::string yaze::test::WidgetDiscoveryService::ExtractLabel (absl::string_view path) const private
Definition at line 221 of file widget_discovery_service.cc.
Referenced by CollectWidgets().
SuggestedAction()
std::string yaze::test::WidgetDiscoveryService::SuggestedAction (absl::string_view type, absl::string_view label) const private
Definition at line 233 of file widget_discovery_service.cc.
Referenced by CollectWidgets().
The documentation for this class was generated from the following files:
src/app/core/service/widget_discovery_service.h
src/app/core/service/widget_discovery_service.cc