yaze: yaze::editor::DungeonObjectSelector Class Reference
yaze::editor::DungeonObjectSelector Class Reference
Handles object selection, preview, and editing UI.
#include <dungeon_object_selector.h>
Public Member Functions
DungeonObjectSelector (Rom *rom=nullptr)
void DrawTileSelector ()
void DrawObjectRenderer ()
void DrawIntegratedEditingPanels ()
void Draw ()
void set_rom (Rom *rom)
void SetRom (Rom *rom)
Rom * rom () const
void set_dungeon_editor_system (std::unique_ptr< zelda3::DungeonEditorSystem > *system)
void set_object_editor (std::shared_ptr< zelda3::DungeonObjectEditor > *editor)
void set_rooms (std::array< zelda3::Room, 0x128 > *rooms)
void set_current_room_id (int room_id)
void set_current_palette_group_id (uint64_t id)
void SetCurrentPaletteGroup (const gfx::PaletteGroup &palette_group)
void SetCurrentPaletteId (uint64_t palette_id)
void SetObjectSelectedCallback (std::function< void(const zelda3::RoomObject &)> callback)
void SetObjectPlacementCallback (std::function< void(const zelda3::RoomObject &)> callback)
const zelda3::RoomObject & GetPreviewObject () const
bool IsObjectLoaded () const
Private Member Functions
void DrawRoomGraphics ()
void DrawObjectBrowser ()
void DrawCompactObjectEditor ()
void DrawCompactSpriteEditor ()
ImU32 GetObjectTypeColor (int object_id)
std::string GetObjectTypeSymbol (int object_id)
void RenderObjectPrimitive (const zelda3::RoomObject &object, int x, int y)
void DrawObjectAssetBrowser ()
bool MatchesObjectFilter (int obj_id, int filter_type)
void CalculateObjectDimensions (const zelda3::RoomObject &object, int &width, int &height)
void PlaceObjectAtPosition (int x, int y)
void DrawCompactItemEditor ()
void DrawCompactEntranceEditor ()
void DrawCompactDoorEditor ()
void DrawCompactChestEditor ()
void DrawCompactPropertiesEditor ()
Private Attributes
Rom * rom_ = nullptr
gui::Canvas room_gfx_canvas_ {"##RoomGfxCanvas", ImVec2(0x100 + 1, 0x10 * 0x40 + 1)}
gui::Canvas object_canvas_
zelda3::ObjectRenderer object_renderer_
std::unique_ptr< zelda3::DungeonEditorSystem > * dungeon_editor_system_ = nullptr
std::shared_ptr< zelda3::DungeonObjectEditor > * object_editor_ = nullptr
std::array< zelda3::Room, 0x128 > * rooms_ = nullptr
int current_room_id_ = 0
uint64_t current_palette_group_id_ = 0
uint64_t current_palette_id_ = 0
gfx::PaletteGroup current_palette_group_
zelda3::RoomObject preview_object_ {0, 0, 0, 0, 0}
gfx::SnesPalette preview_palette_
bool object_loaded_ = false
std::function< void(const zelda3::RoomObject &)> object_selected_callback_
std::function< void(const zelda3::RoomObject &)> object_placement_callback_
int selected_object_id_ = -1
Detailed Description
Handles object selection, preview, and editing UI.
Definition at line 18 of file dungeon_object_selector.h.
Constructor & Destructor Documentation
DungeonObjectSelector()
yaze::editor::DungeonObjectSelector::DungeonObjectSelector (Rom * rom = nullptr) inline explicit
Definition at line 20 of file dungeon_object_selector.h.
Member Function Documentation
DrawTileSelector()
void yaze::editor::DungeonObjectSelector::DrawTileSelector ()
Definition at line 27 of file dungeon_object_selector.cc.
References DrawObjectRenderer(), and DrawRoomGraphics().
DrawObjectRenderer()
void yaze::editor::DungeonObjectSelector::DrawObjectRenderer ()
Todo:
Implement object placement in the main canvas
Definition at line 47 of file dungeon_object_selector.cc.
References yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), DrawObjectAssetBrowser(), yaze::gui::Canvas::DrawOverlay(), yaze::core::Renderer::Get(), yaze::zelda3::RoomObject::id_, yaze::zelda3::RoomObject::layer_, object_canvas_, object_loaded_, object_renderer_, PlaceObjectAtPosition(), preview_object_, preview_palette_, yaze::core::Renderer::RenderBitmap(), yaze::zelda3::ObjectRenderer::RenderObject(), RenderObjectPrimitive(), yaze::zelda3::RoomObject::size_, yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by Draw(), and DrawTileSelector().
DrawIntegratedEditingPanels()
void yaze::editor::DungeonObjectSelector::DrawIntegratedEditingPanels ()
Definition at line 376 of file dungeon_object_selector.cc.
References DrawCompactChestEditor(), DrawCompactDoorEditor(), DrawCompactEntranceEditor(), DrawCompactItemEditor(), DrawCompactObjectEditor(), DrawCompactPropertiesEditor(), DrawCompactSpriteEditor(), dungeon_editor_system_, and object_editor_.
Referenced by Draw().
Draw()
void yaze::editor::DungeonObjectSelector::Draw ()
Definition at line 296 of file dungeon_object_selector.cc.
References DrawIntegratedEditingPanels(), DrawObjectRenderer(), and DrawRoomGraphics().
Referenced by yaze::editor::DungeonEditor::UpdateDungeonRoomView().
set_rom()
void yaze::editor::DungeonObjectSelector::set_rom (Rom * rom) inline
Definition at line 27 of file dungeon_object_selector.h.
References object_renderer_, rom(), rom_, and yaze::zelda3::ObjectRenderer::SetROM().
SetRom()
void yaze::editor::DungeonObjectSelector::SetRom (Rom * rom) inline
Definition at line 31 of file dungeon_object_selector.h.
References object_renderer_, rom(), rom_, and yaze::zelda3::ObjectRenderer::SetROM().
Referenced by yaze::editor::DungeonEditor::Load(), and yaze::editor::DungeonEditor::set_rom().
rom()
Rom * yaze::editor::DungeonObjectSelector::rom () const inline
Definition at line 35 of file dungeon_object_selector.h.
References rom_.
Referenced by set_rom(), and SetRom().
set_dungeon_editor_system()
void yaze::editor::DungeonObjectSelector::set_dungeon_editor_system (std::unique_ptr< zelda3::DungeonEditorSystem > * system) inline
Definition at line 38 of file dungeon_object_selector.h.
References dungeon_editor_system_.
Referenced by yaze::editor::DungeonEditor::Load().
set_object_editor()
void yaze::editor::DungeonObjectSelector::set_object_editor (std::shared_ptr< zelda3::DungeonObjectEditor > * editor) inline
Definition at line 41 of file dungeon_object_selector.h.
References object_editor_.
Referenced by yaze::editor::DungeonEditor::Load().
set_rooms()
void yaze::editor::DungeonObjectSelector::set_rooms (std::array< zelda3::Room, 0x128 > * rooms) inline
Definition at line 46 of file dungeon_object_selector.h.
References rooms_.
Referenced by yaze::editor::DungeonEditor::Load().
set_current_room_id()
void yaze::editor::DungeonObjectSelector::set_current_room_id (int room_id) inline
Definition at line 47 of file dungeon_object_selector.h.
References current_room_id_.
set_current_palette_group_id()
void yaze::editor::DungeonObjectSelector::set_current_palette_group_id (uint64_t id) inline
Definition at line 50 of file dungeon_object_selector.h.
References current_palette_group_id_.
SetCurrentPaletteGroup()
void yaze::editor::DungeonObjectSelector::SetCurrentPaletteGroup (const gfx::PaletteGroup & palette_group) inline
Definition at line 51 of file dungeon_object_selector.h.
References current_palette_group_.
Referenced by yaze::editor::DungeonEditor::Load().
SetCurrentPaletteId()
void yaze::editor::DungeonObjectSelector::SetCurrentPaletteId (uint64_t palette_id) inline
Definition at line 52 of file dungeon_object_selector.h.
References current_palette_id_.
Referenced by yaze::editor::DungeonEditor::Load().
SetObjectSelectedCallback()
void yaze::editor::DungeonObjectSelector::SetObjectSelectedCallback (std::function< void(const zelda3::RoomObject &)> callback) inline
Definition at line 55 of file dungeon_object_selector.h.
References object_selected_callback_.
Referenced by yaze::editor::DungeonEditor::Load().
SetObjectPlacementCallback()
void yaze::editor::DungeonObjectSelector::SetObjectPlacementCallback (std::function< void(const zelda3::RoomObject &)> callback) inline
Definition at line 59 of file dungeon_object_selector.h.
References object_placement_callback_.
GetPreviewObject()
const zelda3::RoomObject & yaze::editor::DungeonObjectSelector::GetPreviewObject () const inline
Definition at line 64 of file dungeon_object_selector.h.
References preview_object_.
IsObjectLoaded()
bool yaze::editor::DungeonObjectSelector::IsObjectLoaded () const inline
Definition at line 65 of file dungeon_object_selector.h.
References object_loaded_.
DrawRoomGraphics()
void yaze::editor::DungeonObjectSelector::DrawRoomGraphics () private
Definition at line 320 of file dungeon_object_selector.cc.
References current_room_id_, yaze::gui::Canvas::draw_list(), yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::gui::Canvas::DrawTileSelector(), yaze::gfx::Arena::Get(), yaze::gfx::Arena::gfx_sheets(), yaze::gui::Canvas::height(), yaze::Rom::is_loaded(), rom_, room_gfx_canvas_, rooms_, yaze::gui::Canvas::width(), and yaze::gui::Canvas::zero_point().
Referenced by Draw(), and DrawTileSelector().
DrawObjectBrowser()
void yaze::editor::DungeonObjectSelector::DrawObjectBrowser () private
Definition at line 134 of file dungeon_object_selector.cc.
References current_palette_group_id_, GetObjectTypeColor(), GetObjectTypeSymbol(), yaze::Rom::is_loaded(), yaze::zelda3::RoomObject::layer_, object_loaded_, object_selected_callback_, yaze::Rom::palette_group(), preview_object_, preview_palette_, rom_, and yaze::zelda3::RoomObject::size_.
DrawCompactObjectEditor()
void yaze::editor::DungeonObjectSelector::DrawCompactObjectEditor () private
Definition at line 430 of file dungeon_object_selector.cc.
References yaze::zelda3::DungeonObjectEditor::kEdit, yaze::zelda3::DungeonObjectEditor::kInsert, yaze::zelda3::DungeonObjectEditor::kSelect, and object_editor_.
Referenced by DrawIntegratedEditingPanels().
DrawCompactSpriteEditor()
void yaze::editor::DungeonObjectSelector::DrawCompactSpriteEditor () private
Definition at line 734 of file dungeon_object_selector.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::kEnemy, yaze::zelda3::DungeonEditorSystem::SpriteData::layer, yaze::zelda3::DungeonEditorSystem::SpriteData::sprite_id, yaze::zelda3::DungeonEditorSystem::SpriteData::type, yaze::zelda3::DungeonEditorSystem::SpriteData::x, and yaze::zelda3::DungeonEditorSystem::SpriteData::y.
Referenced by DrawIntegratedEditingPanels().
GetObjectTypeColor()
ImU32 yaze::editor::DungeonObjectSelector::GetObjectTypeColor (int object_id) private
Definition at line 499 of file dungeon_object_selector.cc.
Referenced by DrawObjectAssetBrowser(), DrawObjectBrowser(), and RenderObjectPrimitive().
GetObjectTypeSymbol()
std::string yaze::editor::DungeonObjectSelector::GetObjectTypeSymbol (int object_id) private
Definition at line 520 of file dungeon_object_selector.cc.
Referenced by DrawObjectAssetBrowser(), and DrawObjectBrowser().
RenderObjectPrimitive()
void yaze::editor::DungeonObjectSelector::RenderObjectPrimitive (const zelda3::RoomObject & object, int x, int y) private
Definition at line 541 of file dungeon_object_selector.cc.
References CalculateObjectDimensions(), yaze::gui::Canvas::DrawRect(), yaze::gui::Canvas::DrawText(), GetObjectTypeColor(), and object_canvas_.
Referenced by DrawObjectRenderer().
DrawObjectAssetBrowser()
void yaze::editor::DungeonObjectSelector::DrawObjectAssetBrowser () private
Definition at line 559 of file dungeon_object_selector.cc.
References current_palette_group_id_, GetObjectTypeColor(), GetObjectTypeSymbol(), MatchesObjectFilter(), object_loaded_, object_selected_callback_, yaze::Rom::palette_group(), preview_object_, preview_palette_, rom_, selected_object_id_, and yaze::zelda3::RoomObject::set_rom().
Referenced by DrawObjectRenderer().
MatchesObjectFilter()
bool yaze::editor::DungeonObjectSelector::MatchesObjectFilter (int obj_id, int filter_type) private
Definition at line 665 of file dungeon_object_selector.cc.
Referenced by DrawObjectAssetBrowser().
CalculateObjectDimensions()
void yaze::editor::DungeonObjectSelector::CalculateObjectDimensions (const zelda3::RoomObject & object, int & width, int & height) private
Definition at line 684 of file dungeon_object_selector.cc.
Referenced by RenderObjectPrimitive().
PlaceObjectAtPosition()
void yaze::editor::DungeonObjectSelector::PlaceObjectAtPosition (int x, int y) private
Definition at line 720 of file dungeon_object_selector.cc.
References object_loaded_, object_placement_callback_, preview_object_, and yaze::zelda3::RoomObject::set_x().
Referenced by DrawObjectRenderer().
DrawCompactItemEditor()
void yaze::editor::DungeonObjectSelector::DrawCompactItemEditor () private
Definition at line 794 of file dungeon_object_selector.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::ItemData::is_hidden, yaze::zelda3::DungeonEditorSystem::ItemData::item_id, yaze::zelda3::DungeonEditorSystem::kKey, yaze::zelda3::DungeonEditorSystem::ItemData::room_id, yaze::zelda3::DungeonEditorSystem::ItemData::type, yaze::zelda3::DungeonEditorSystem::ItemData::x, and yaze::zelda3::DungeonEditorSystem::ItemData::y.
Referenced by DrawIntegratedEditingPanels().
DrawCompactEntranceEditor()
void yaze::editor::DungeonObjectSelector::DrawCompactEntranceEditor () private
Definition at line 855 of file dungeon_object_selector.cc.
References dungeon_editor_system_.
Referenced by DrawIntegratedEditingPanels().
DrawCompactDoorEditor()
void yaze::editor::DungeonObjectSelector::DrawCompactDoorEditor () private
Definition at line 907 of file dungeon_object_selector.cc.
References yaze::zelda3::DungeonEditorSystem::DoorData::direction, dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::DoorData::is_locked, yaze::zelda3::DungeonEditorSystem::DoorData::key_type, yaze::zelda3::DungeonEditorSystem::DoorData::requires_key, yaze::zelda3::DungeonEditorSystem::DoorData::room_id, yaze::zelda3::DungeonEditorSystem::DoorData::target_room_id, yaze::zelda3::DungeonEditorSystem::DoorData::target_x, yaze::zelda3::DungeonEditorSystem::DoorData::target_y, yaze::zelda3::DungeonEditorSystem::DoorData::x, and yaze::zelda3::DungeonEditorSystem::DoorData::y.
Referenced by DrawIntegratedEditingPanels().
DrawCompactChestEditor()
void yaze::editor::DungeonObjectSelector::DrawCompactChestEditor () private
Definition at line 968 of file dungeon_object_selector.cc.
References dungeon_editor_system_, chest::x, and chest::y.
Referenced by DrawIntegratedEditingPanels().
DrawCompactPropertiesEditor()
void yaze::editor::DungeonObjectSelector::DrawCompactPropertiesEditor () private
Definition at line 1025 of file dungeon_object_selector.cc.
References dungeon_editor_system_, yaze::zelda3::DungeonEditorSystem::RoomProperties::dungeon_id, yaze::zelda3::DungeonEditorSystem::RoomProperties::floor_level, yaze::zelda3::DungeonEditorSystem::RoomProperties::is_boss_room, yaze::zelda3::DungeonEditorSystem::RoomProperties::is_save_room, yaze::zelda3::DungeonEditorSystem::RoomProperties::music_id, yaze::zelda3::DungeonEditorSystem::RoomProperties::name, and yaze::zelda3::DungeonEditorSystem::RoomProperties::room_id.
Referenced by DrawIntegratedEditingPanels().
Member Data Documentation
rom_
Rom* yaze::editor::DungeonObjectSelector::rom_ = nullptr private
Definition at line 89 of file dungeon_object_selector.h.
Referenced by DrawObjectAssetBrowser(), DrawObjectBrowser(), DrawRoomGraphics(), rom(), set_rom(), and SetRom().
room_gfx_canvas_
gui::Canvas yaze::editor::DungeonObjectSelector::room_gfx_canvas_ {"##RoomGfxCanvas", ImVec2(0x100 + 1, 0x10 * 0x40 + 1)} private
Definition at line 90 of file dungeon_object_selector.h.
Referenced by DrawRoomGraphics().
object_canvas_
gui::Canvas yaze::editor::DungeonObjectSelector::object_canvas_ private
Definition at line 91 of file dungeon_object_selector.h.
Referenced by DrawObjectRenderer(), and RenderObjectPrimitive().
object_renderer_
zelda3::ObjectRenderer yaze::editor::DungeonObjectSelector::object_renderer_ private
Definition at line 92 of file dungeon_object_selector.h.
Referenced by DrawObjectRenderer(), set_rom(), and SetRom().
dungeon_editor_system_
std::unique_ptr<zelda3::DungeonEditorSystem>* yaze::editor::DungeonObjectSelector::dungeon_editor_system_ = nullptr private
Definition at line 95 of file dungeon_object_selector.h.
Referenced by DrawCompactChestEditor(), DrawCompactDoorEditor(), DrawCompactEntranceEditor(), DrawCompactItemEditor(), DrawCompactPropertiesEditor(), DrawCompactSpriteEditor(), DrawIntegratedEditingPanels(), and set_dungeon_editor_system().
object_editor_
std::shared_ptr<zelda3::DungeonObjectEditor>* yaze::editor::DungeonObjectSelector::object_editor_ = nullptr private
Definition at line 96 of file dungeon_object_selector.h.
Referenced by DrawCompactObjectEditor(), DrawIntegratedEditingPanels(), and set_object_editor().
rooms_
std::array<zelda3::Room, 0x128>* yaze::editor::DungeonObjectSelector::rooms_ = nullptr private
Definition at line 99 of file dungeon_object_selector.h.
Referenced by DrawRoomGraphics(), and set_rooms().
current_room_id_
int yaze::editor::DungeonObjectSelector::current_room_id_ = 0 private
Definition at line 100 of file dungeon_object_selector.h.
Referenced by DrawRoomGraphics(), and set_current_room_id().
current_palette_group_id_
uint64_t yaze::editor::DungeonObjectSelector::current_palette_group_id_ = 0 private
Definition at line 103 of file dungeon_object_selector.h.
Referenced by DrawObjectAssetBrowser(), DrawObjectBrowser(), and set_current_palette_group_id().
current_palette_id_
uint64_t yaze::editor::DungeonObjectSelector::current_palette_id_ = 0 private
Definition at line 104 of file dungeon_object_selector.h.
Referenced by SetCurrentPaletteId().
current_palette_group_
gfx::PaletteGroup yaze::editor::DungeonObjectSelector::current_palette_group_ private
Definition at line 105 of file dungeon_object_selector.h.
Referenced by SetCurrentPaletteGroup().
preview_object_
zelda3::RoomObject yaze::editor::DungeonObjectSelector::preview_object_ {0, 0, 0, 0, 0} private
Definition at line 108 of file dungeon_object_selector.h.
Referenced by DrawObjectAssetBrowser(), DrawObjectBrowser(), DrawObjectRenderer(), GetPreviewObject(), and PlaceObjectAtPosition().
preview_palette_
gfx::SnesPalette yaze::editor::DungeonObjectSelector::preview_palette_ private
Definition at line 109 of file dungeon_object_selector.h.
Referenced by DrawObjectAssetBrowser(), DrawObjectBrowser(), and DrawObjectRenderer().
object_loaded_
bool yaze::editor::DungeonObjectSelector::object_loaded_ = false private
Definition at line 110 of file dungeon_object_selector.h.
Referenced by DrawObjectAssetBrowser(), DrawObjectBrowser(), DrawObjectRenderer(), IsObjectLoaded(), and PlaceObjectAtPosition().
object_selected_callback_
std::function<void(const zelda3::RoomObject&)> yaze::editor::DungeonObjectSelector::object_selected_callback_ private
Definition at line 113 of file dungeon_object_selector.h.
Referenced by DrawObjectAssetBrowser(), DrawObjectBrowser(), and SetObjectSelectedCallback().
object_placement_callback_
std::function<void(const zelda3::RoomObject&)> yaze::editor::DungeonObjectSelector::object_placement_callback_ private
Definition at line 114 of file dungeon_object_selector.h.
Referenced by PlaceObjectAtPosition(), and SetObjectPlacementCallback().
selected_object_id_
int yaze::editor::DungeonObjectSelector::selected_object_id_ = -1 private
Definition at line 117 of file dungeon_object_selector.h.
Referenced by DrawObjectAssetBrowser().
The documentation for this class was generated from the following files:
src/app/editor/dungeon/dungeon_object_selector.h
src/app/editor/dungeon/dungeon_object_selector.cc