yaze: yaze::editor::ProposalDrawer Class Reference
yaze::editor::ProposalDrawer Class Reference
ImGui drawer for displaying and managing agent proposals.
#include <proposal_drawer.h>
Public Member Functions
ProposalDrawer ()
~ProposalDrawer ()=default
void SetRom (Rom *rom)
void Draw ()
void Show ()
void Hide ()
void Toggle ()
bool IsVisible () const
Private Types
enum class StatusFilter { kAll , kPending , kAccepted , kRejected }
Private Member Functions
void DrawProposalList ()
void DrawProposalDetail ()
void DrawPolicyStatus ()
void DrawStatusFilter ()
void DrawActionButtons ()
absl::Status AcceptProposal (const std::string &proposal_id)
absl::Status RejectProposal (const std::string &proposal_id)
absl::Status DeleteProposal (const std::string &proposal_id)
void RefreshProposals ()
void SelectProposal (const std::string &proposal_id)
Private Attributes
bool visible_ = false
bool needs_refresh_ = true
StatusFilter status_filter_ = StatusFilter::kAll
std::vector< cli::ProposalRegistry::ProposalMetadata > proposals_
std::string selected_proposal_id_
cli::ProposalRegistry::ProposalMetadata * selected_proposal_ = nullptr
std::string diff_content_
std::string log_content_
int log_display_lines_ = 50
float drawer_width_ = 400.0f
bool show_confirm_dialog_ = false
bool show_override_dialog_ = false
std::string confirm_action_
std::string confirm_proposal_id_
Rom * rom_ = nullptr
Detailed Description
ImGui drawer for displaying and managing agent proposals.
Provides a UI for reviewing agent-generated ROM modification proposals, including:
List of all proposals with status indicators
Detailed view of selected proposal (metadata, diff, logs)
Accept/Reject controls
Filtering by status (Pending/Accepted/Rejected)
Integrates with the CLI ProposalRegistry service to enable human-in-the-loop review of agentic modifications.
Definition at line 31 of file proposal_drawer.h.
Member Enumeration Documentation
StatusFilter
enum class yaze::editor::ProposalDrawer::StatusFilter strong private
Enumerator
kAll
kPending
kAccepted
kRejected
Definition at line 66 of file proposal_drawer.h.
Constructor & Destructor Documentation
ProposalDrawer()
yaze::editor::ProposalDrawer::ProposalDrawer ()
Definition at line 21 of file proposal_drawer.cc.
References RefreshProposals().
~ProposalDrawer()
yaze::editor::ProposalDrawer::~ProposalDrawer () default
Member Function Documentation
SetRom()
void yaze::editor::ProposalDrawer::SetRom (Rom * rom) inline
Definition at line 37 of file proposal_drawer.h.
References rom_.
Referenced by yaze::editor::EditorManager::DrawMenuBar().
Draw()
void yaze::editor::ProposalDrawer::Draw ()
Definition at line 25 of file proposal_drawer.cc.
References AcceptProposal(), confirm_action_, confirm_proposal_id_, DeleteProposal(), drawer_width_, DrawProposalDetail(), DrawProposalList(), DrawStatusFilter(), ICON_MD_REFRESH, ICON_MD_WARNING, needs_refresh_, RefreshProposals(), RejectProposal(), selected_proposal_, show_confirm_dialog_, show_override_dialog_, and visible_.
Referenced by yaze::editor::EditorManager::DrawMenuBar(), and yaze::editor::EditorManager::Update().
Show()
void yaze::editor::ProposalDrawer::Show () inline
Definition at line 43 of file proposal_drawer.h.
References visible_.
Hide()
void yaze::editor::ProposalDrawer::Hide () inline
Definition at line 44 of file proposal_drawer.h.
References visible_.
Toggle()
void yaze::editor::ProposalDrawer::Toggle () inline
Definition at line 45 of file proposal_drawer.h.
References visible_.
Referenced by yaze::editor::EditorManager::Initialize().
IsVisible()
bool yaze::editor::ProposalDrawer::IsVisible () const inline
Definition at line 46 of file proposal_drawer.h.
References visible_.
DrawProposalList()
void yaze::editor::ProposalDrawer::DrawProposalList () private
Definition at line 134 of file proposal_drawer.cc.
References yaze::cli::ProposalRegistry::kAccepted, yaze::cli::ProposalRegistry::kPending, yaze::cli::ProposalRegistry::kRejected, proposals_, selected_proposal_id_, and SelectProposal().
Referenced by Draw().
DrawProposalDetail()
void yaze::editor::ProposalDrawer::DrawProposalDetail () private
Definition at line 190 of file proposal_drawer.cc.
References diff_content_, DrawActionButtons(), DrawPolicyStatus(), log_content_, log_display_lines_, and selected_proposal_.
Referenced by Draw().
DrawPolicyStatus()
void yaze::editor::ProposalDrawer::DrawPolicyStatus () private
Definition at line 281 of file proposal_drawer.cc.
References yaze::cli::PolicyEvaluator::GetInstance(), ICON_MD_BLOCK, ICON_MD_CANCEL, ICON_MD_CHECK_CIRCLE, ICON_MD_ERROR, ICON_MD_INFO, ICON_MD_WARNING, yaze::cli::ProposalRegistry::kPending, and selected_proposal_.
Referenced by DrawProposalDetail().
DrawStatusFilter()
void yaze::editor::ProposalDrawer::DrawStatusFilter () private
Definition at line 270 of file proposal_drawer.cc.
References RefreshProposals(), and status_filter_.
Referenced by Draw().
DrawActionButtons()
void yaze::editor::ProposalDrawer::DrawActionButtons () private
Definition at line 378 of file proposal_drawer.cc.
References confirm_action_, confirm_proposal_id_, yaze::cli::PolicyEvaluator::GetInstance(), ICON_MD_CHECK, ICON_MD_CLOSE, ICON_MD_DELETE, yaze::cli::ProposalRegistry::kPending, selected_proposal_, show_confirm_dialog_, show_override_dialog_, and yaze::cli::ProposalRegistry::ProposalMetadata::status.
Referenced by DrawProposalDetail().
AcceptProposal()
absl::Status yaze::editor::ProposalDrawer::AcceptProposal (const std::string & proposal_id) private
Definition at line 498 of file proposal_drawer.cc.
References yaze::cli::ProposalRegistry::Instance(), yaze::cli::RomSandboxManager::Instance(), yaze::cli::ProposalRegistry::kAccepted, yaze::Rom::LoadFromFile(), needs_refresh_, rom_, yaze::Rom::vector(), and yaze::Rom::WriteVector().
Referenced by Draw().
RejectProposal()
absl::Status yaze::editor::ProposalDrawer::RejectProposal (const std::string & proposal_id) private
Definition at line 574 of file proposal_drawer.cc.
References yaze::cli::ProposalRegistry::Instance(), yaze::cli::ProposalRegistry::kRejected, and needs_refresh_.
Referenced by Draw().
DeleteProposal()
absl::Status yaze::editor::ProposalDrawer::DeleteProposal (const std::string & proposal_id) private
Definition at line 583 of file proposal_drawer.cc.
References diff_content_, yaze::cli::ProposalRegistry::Instance(), log_content_, needs_refresh_, selected_proposal_, and selected_proposal_id_.
Referenced by Draw().
RefreshProposals()
void yaze::editor::ProposalDrawer::RefreshProposals () private
Definition at line 444 of file proposal_drawer.cc.
References diff_content_, yaze::cli::ProposalRegistry::Instance(), kAccepted, yaze::cli::ProposalRegistry::kAccepted, kAll, kPending, yaze::cli::ProposalRegistry::kPending, kRejected, yaze::cli::ProposalRegistry::kRejected, log_content_, proposals_, selected_proposal_, selected_proposal_id_, and status_filter_.
Referenced by Draw(), DrawStatusFilter(), and ProposalDrawer().
SelectProposal()
void yaze::editor::ProposalDrawer::SelectProposal (const std::string & proposal_id) private
Definition at line 483 of file proposal_drawer.cc.
References diff_content_, log_content_, proposals_, selected_proposal_, and selected_proposal_id_.
Referenced by DrawProposalList().
Member Data Documentation
visible_
bool yaze::editor::ProposalDrawer::visible_ = false private
Definition at line 62 of file proposal_drawer.h.
Referenced by Draw(), Hide(), IsVisible(), Show(), and Toggle().
needs_refresh_
bool yaze::editor::ProposalDrawer::needs_refresh_ = true private
Definition at line 63 of file proposal_drawer.h.
Referenced by AcceptProposal(), DeleteProposal(), Draw(), and RejectProposal().
status_filter_
StatusFilter yaze::editor::ProposalDrawer::status_filter_ = StatusFilter::kAll private
Definition at line 72 of file proposal_drawer.h.
Referenced by DrawStatusFilter(), and RefreshProposals().
proposals_
std::vector<cli::ProposalRegistry::ProposalMetadata> yaze::editor::ProposalDrawer::proposals_ private
Definition at line 75 of file proposal_drawer.h.
Referenced by DrawProposalList(), RefreshProposals(), and SelectProposal().
selected_proposal_id_
std::string yaze::editor::ProposalDrawer::selected_proposal_id_ private
Definition at line 76 of file proposal_drawer.h.
Referenced by DeleteProposal(), DrawProposalList(), RefreshProposals(), and SelectProposal().
selected_proposal_
cli::ProposalRegistry::ProposalMetadata* yaze::editor::ProposalDrawer::selected_proposal_ = nullptr private
Definition at line 77 of file proposal_drawer.h.
Referenced by DeleteProposal(), Draw(), DrawActionButtons(), DrawPolicyStatus(), DrawProposalDetail(), RefreshProposals(), and SelectProposal().
diff_content_
std::string yaze::editor::ProposalDrawer::diff_content_ private
Definition at line 80 of file proposal_drawer.h.
Referenced by DeleteProposal(), DrawProposalDetail(), RefreshProposals(), and SelectProposal().
log_content_
std::string yaze::editor::ProposalDrawer::log_content_ private
Definition at line 81 of file proposal_drawer.h.
Referenced by DeleteProposal(), DrawProposalDetail(), RefreshProposals(), and SelectProposal().
log_display_lines_
int yaze::editor::ProposalDrawer::log_display_lines_ = 50 private
Definition at line 82 of file proposal_drawer.h.
Referenced by DrawProposalDetail().
drawer_width_
float yaze::editor::ProposalDrawer::drawer_width_ = 400.0f private
Definition at line 85 of file proposal_drawer.h.
Referenced by Draw().
show_confirm_dialog_
bool yaze::editor::ProposalDrawer::show_confirm_dialog_ = false private
Definition at line 86 of file proposal_drawer.h.
Referenced by Draw(), and DrawActionButtons().
show_override_dialog_
bool yaze::editor::ProposalDrawer::show_override_dialog_ = false private
Definition at line 87 of file proposal_drawer.h.
Referenced by Draw(), and DrawActionButtons().
confirm_action_
std::string yaze::editor::ProposalDrawer::confirm_action_ private
Definition at line 88 of file proposal_drawer.h.
Referenced by Draw(), and DrawActionButtons().
confirm_proposal_id_
std::string yaze::editor::ProposalDrawer::confirm_proposal_id_ private
Definition at line 89 of file proposal_drawer.h.
Referenced by Draw(), and DrawActionButtons().
rom_
Rom* yaze::editor::ProposalDrawer::rom_ = nullptr private
Definition at line 92 of file proposal_drawer.h.
Referenced by AcceptProposal(), and SetRom().
The documentation for this class was generated from the following files:
src/app/editor/system/proposal_drawer.h
src/app/editor/system/proposal_drawer.cc