yaze: yaze::cli::handlers Namespace Reference
yaze::cli::handlers Namespace Reference
Namespaces
namespace anonymous_namespace{command_handlers.cc}
namespace anonymous_namespace{emulator_commands.cc}
namespace anonymous_namespace{todo_commands.cc}
Classes
class DialogueListCommandHandler
Command handler for listing dialogue messages.
class DialogueReadCommandHandler
Command handler for reading dialogue messages.
class DialogueSearchCommandHandler
Command handler for searching dialogue messages.
class DungeonDescribeRoomCommandHandler
Command handler for describing a dungeon room.
class DungeonExportRoomCommandHandler
Command handler for exporting room data.
class DungeonGetRoomTilesCommandHandler
Command handler for getting room tiles.
class DungeonListObjectsCommandHandler
Command handler for listing objects in a room.
class DungeonListSpritesCommandHandler
Command handler for listing sprites in a dungeon room.
class DungeonSetRoomPropertyCommandHandler
Command handler for setting room properties.
class EmulatorClearBreakpointCommandHandler
class EmulatorGetMetricsCommandHandler
class EmulatorGetRegistersCommandHandler
class EmulatorGetStateCommandHandler
class EmulatorHoldButtonsCommandHandler
class EmulatorListBreakpointsCommandHandler
class EmulatorPauseCommandHandler
class EmulatorPressButtonsCommandHandler
class EmulatorReadMemoryCommandHandler
class EmulatorReleaseButtonsCommandHandler
class EmulatorResetCommandHandler
class EmulatorRunCommandHandler
class EmulatorSetBreakpointCommandHandler
class EmulatorStepCommandHandler
class EmulatorWriteMemoryCommandHandler
class GuiClickCommandHandler
Command handler for clicking GUI elements.
class GuiDiscoverToolCommandHandler
Command handler for discovering GUI tools.
class GuiPlaceTileCommandHandler
Command handler for placing tiles via GUI automation.
class GuiScreenshotCommandHandler
Command handler for taking screenshots.
class HexReadCommandHandler
Command handler for reading hex data from ROM.
class HexSearchCommandHandler
Command handler for searching hex patterns in ROM.
class HexWriteCommandHandler
Command handler for writing hex data to ROM.
class MessageListCommandHandler
Command handler for listing messages.
class MessageReadCommandHandler
Command handler for reading messages.
class MessageSearchCommandHandler
Command handler for searching messages.
class MusicInfoCommandHandler
Command handler for getting music track information.
class MusicListCommandHandler
Command handler for listing music tracks.
class MusicTracksCommandHandler
Command handler for getting detailed music track data.
class OverworldDescribeMapCommandHandler
Command handler for describing overworld maps.
class OverworldFindTileCommandHandler
Command handler for finding tiles in overworld.
class OverworldGetEntranceCommandHandler
Command handler for getting entrance information.
class OverworldListSpritesCommandHandler
Command handler for listing sprites in overworld.
class OverworldListWarpsCommandHandler
Command handler for listing warps in overworld.
class OverworldTileStatsCommandHandler
Command handler for getting tile statistics.
class PaletteAnalyzeCommandHandler
Command handler for analyzing palettes.
class PaletteGetColorsCommandHandler
Command handler for getting palette colors.
class PaletteSetColorCommandHandler
Command handler for setting palette colors.
class ProjectBuildCommandHandler
Command handler for building projects.
class ProjectInitCommandHandler
Command handler for initializing new projects.
class ResourceListCommandHandler
Command handler for listing resource labels by type.
class ResourceSearchCommandHandler
Command handler for searching resource labels.
class RomDiffCommandHandler
Command handler for comparing ROM files.
class RomGenerateGoldenCommandHandler
Command handler for generating golden ROM files.
class RomInfoCommandHandler
Command handler for displaying ROM information.
class RomValidateCommandHandler
Command handler for validating ROM files.
class SimpleChatCommandHandler
class SpriteListCommandHandler
Command handler for listing sprites.
class SpritePaletteCommandHandler
Command handler for getting sprite palette information.
class SpritePropertiesCommandHandler
Command handler for getting sprite properties.
Functions
absl::Status HandleAgentCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTodoCommand (const std::vector< std::string > &args)
Handle z3ed agent todo commands.
std::vector< std::unique_ptr< resources::CommandHandler > > CreateCliCommandHandlers ()
Factory function to create all CLI-level command handlers.
std::vector< std::unique_ptr< resources::CommandHandler > > CreateAgentCommandHandlers ()
Factory function to create all agent-specific command handlers.
std::vector< std::unique_ptr< resources::CommandHandler > > CreateAllCommandHandlers ()
Factory function to create all command handlers (CLI + agent)
resources::CommandHandler * GetCommandHandler (const std::string &name)
Get a command handler by name.
Function Documentation
HandleAgentCommand()
absl::Status yaze::cli::handlers::HandleAgentCommand (const std::vector< std::string > & arg_vec)
Definition at line 142 of file agent.cc.
References yaze::cli::agent::HandleDescribeCommand(), yaze::cli::agent::HandleDungeonDescribeRoomCommand(), yaze::cli::agent::HandleDungeonListSpritesCommand(), yaze::cli::agent::HandleGuiCommand(), yaze::cli::agent::HandleLearnCommand(), yaze::cli::agent::HandleListCommand(), yaze::cli::agent::HandleOverworldDescribeMapCommand(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandlePlanCommand(), yaze::cli::agent::HandleResourceListCommand(), yaze::cli::agent::HandleResourceSearchCommand(), yaze::cli::agent::HandleTestCommand(), and yaze::cli::agent::HandleTestConversationCommand().
HandleTodoCommand()
absl::Status yaze::cli::handlers::HandleTodoCommand (const std::vector< std::string > & args)
Handle z3ed agent todo commands.
Commands: agent todo create [–category=<cat>] [–priority=<n>] agent todo list [–status=<status>] [–category=<cat>] agent todo update <id> –status=<status> agent todo show <id> agent todo delete <id> agent todo clear-completed agent todo next agent todo plan
Definition at line 261 of file todo_commands.cc.
CreateCliCommandHandlers()
std::vector< std::unique_ptr< resources::CommandHandler > > yaze::cli::handlers::CreateCliCommandHandlers ()
Factory function to create all CLI-level command handlers.
Returns
Vector of unique pointers to command handler instances
Definition at line 29 of file command_handlers.cc.
Referenced by CreateAllCommandHandlers().
CreateAgentCommandHandlers()
std::vector< std::unique_ptr< resources::CommandHandler > > yaze::cli::handlers::CreateAgentCommandHandlers ()
Factory function to create all agent-specific command handlers.
Returns
Vector of unique pointers to command handler instances
Definition at line 67 of file command_handlers.cc.
Referenced by CreateAllCommandHandlers().
CreateAllCommandHandlers()
std::vector< std::unique_ptr< resources::CommandHandler > > yaze::cli::handlers::CreateAllCommandHandlers ()
Factory function to create all command handlers (CLI + agent)
Returns
Vector of unique pointers to command handler instances
Definition at line 118 of file command_handlers.cc.
References CreateAgentCommandHandlers(), and CreateCliCommandHandlers().
Referenced by yaze::cli::ModernCLI::SetupCommands().
GetCommandHandler()
resources::CommandHandler * yaze::cli::handlers::GetCommandHandler (const std::string & name)
Get a command handler by name.
Parameters
name Command name (e.g., "resource-list", "hex-read")
Returns
Pointer to command handler or nullptr if not found
Definition at line 136 of file command_handlers.cc.