yaze: yaze::editor::AssemblyEditor Class Reference
yaze::editor::AssemblyEditor Class Reference
Text editor for modifying assembly code.
#include <assembly_editor.h>
Public Member Functions
AssemblyEditor (Rom *rom=nullptr)
void ChangeActiveFile (const std::string_view &filename)
void Initialize () override
absl::Status Load () override
void Update (bool &is_loaded)
void InlineUpdate ()
void UpdateCodeView ()
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
absl::Status Update () override
absl::Status Save () override
void OpenFolder (const std::string &folder_path)
void set_rom (Rom *rom)
Rom * rom () const
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Clear ()
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
virtual bool IsRomLoaded () const
virtual std::string GetRomStatus () const
Private Member Functions
void DrawFileMenu ()
void DrawEditMenu ()
void SetEditorText ()
void DrawCurrentFolder ()
void DrawFileTabView ()
Private Attributes
bool file_is_loaded_ = false
int current_file_id_ = 0
std::vector< std::string > files_
std::vector< TextEditor > open_files_
ImVector< int > active_files_
std::string current_file_
FolderItem current_folder_
TextEditor text_editor_
Rom * rom_
Additional Inherited Members
Protected Member Functions inherited from yaze::editor::Editor
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Detailed Description
Text editor for modifying assembly code.
Definition at line 24 of file assembly_editor.h.
Constructor & Destructor Documentation
AssemblyEditor()
yaze::editor::AssemblyEditor::AssemblyEditor (Rom * rom = nullptr) inline explicit
Definition at line 26 of file assembly_editor.h.
References yaze::gui::GetAssemblyLanguageDef(), TextEditor::GetDarkPalette(), yaze::editor::kAssembly, TextEditor::SetLanguageDefinition(), TextEditor::SetPalette(), TextEditor::SetShowWhitespaces(), text_editor_, and yaze::editor::Editor::type_.
Member Function Documentation
ChangeActiveFile()
void yaze::editor::AssemblyEditor::ChangeActiveFile (const std::string_view & filename) inline
Definition at line 32 of file assembly_editor.h.
References current_file_, and file_is_loaded_.
Referenced by DrawCurrentFolder(), and DrawFileMenu().
Initialize()
void yaze::editor::AssemblyEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 98 of file assembly_editor.cc.
Load()
absl::Status yaze::editor::AssemblyEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 102 of file assembly_editor.cc.
Update() [1/2]
void yaze::editor::AssemblyEditor::Update (bool & is_loaded)
Definition at line 108 of file assembly_editor.cc.
References TextEditor::CanUndo(), current_file_, DrawEditMenu(), DrawFileMenu(), TextEditor::GetCursorPosition(), TextEditor::GetLanguageDefinition(), TextEditor::GetTotalLines(), TextEditor::IsOverwrite(), TextEditor::LanguageDefinition::mName, TextEditor::Render(), SetEditorText(), and text_editor_.
Referenced by yaze::editor::EditorManager::DrawMenuBar().
InlineUpdate()
void yaze::editor::AssemblyEditor::InlineUpdate ()
Definition at line 129 of file assembly_editor.cc.
References TextEditor::CanUndo(), current_file_, TextEditor::GetCursorPosition(), TextEditor::GetLanguageDefinition(), TextEditor::GetTotalLines(), TextEditor::IsOverwrite(), TextEditor::LanguageDefinition::mName, TextEditor::Render(), SetEditorText(), and text_editor_.
Referenced by yaze::editor::MusicEditor::Update().
UpdateCodeView()
void yaze::editor::AssemblyEditor::UpdateCodeView ()
Definition at line 142 of file assembly_editor.cc.
References TextEditor::CanUndo(), current_file_, current_folder_, DrawCurrentFolder(), TextEditor::GetCursorPosition(), TextEditor::GetLanguageDefinition(), TextEditor::GetTotalLines(), TextEditor::IsOverwrite(), TextEditor::LanguageDefinition::mName, yaze::editor::FolderItem::name, TextEditor::Render(), SetEditorText(), yaze::util::FileDialogWrapper::ShowOpenFolderDialog(), and text_editor_.
Cut()
absl::Status yaze::editor::AssemblyEditor::Cut () override virtual
Implements yaze::editor::Editor.
Definition at line 337 of file assembly_editor.cc.
References TextEditor::Cut(), and text_editor_.
Copy()
absl::Status yaze::editor::AssemblyEditor::Copy () override virtual
Implements yaze::editor::Editor.
Definition at line 342 of file assembly_editor.cc.
References TextEditor::Copy(), and text_editor_.
Paste()
absl::Status yaze::editor::AssemblyEditor::Paste () override virtual
Implements yaze::editor::Editor.
Definition at line 347 of file assembly_editor.cc.
References TextEditor::Paste(), and text_editor_.
Undo()
absl::Status yaze::editor::AssemblyEditor::Undo () override virtual
Implements yaze::editor::Editor.
Definition at line 352 of file assembly_editor.cc.
References text_editor_, and TextEditor::Undo().
Redo()
absl::Status yaze::editor::AssemblyEditor::Redo () override virtual
Implements yaze::editor::Editor.
Definition at line 357 of file assembly_editor.cc.
References TextEditor::Redo(), and text_editor_.
Find()
absl::Status yaze::editor::AssemblyEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 50 of file assembly_editor.h.
Update() [2/2]
absl::Status yaze::editor::AssemblyEditor::Update () override virtual
Implements yaze::editor::Editor.
Definition at line 362 of file assembly_editor.cc.
Save()
absl::Status yaze::editor::AssemblyEditor::Save () inline override virtual
Implements yaze::editor::Editor.
Definition at line 54 of file assembly_editor.h.
OpenFolder()
void yaze::editor::AssemblyEditor::OpenFolder (const std::string & folder_path)
Definition at line 104 of file assembly_editor.cc.
References current_folder_.
Referenced by yaze::editor::EditorManager::OpenProject().
set_rom()
void yaze::editor::AssemblyEditor::set_rom (Rom * rom) inline
Definition at line 58 of file assembly_editor.h.
References rom(), and rom_.
rom()
Rom * yaze::editor::AssemblyEditor::rom () const inline
Definition at line 59 of file assembly_editor.h.
References rom_.
Referenced by set_rom().
DrawFileMenu()
void yaze::editor::AssemblyEditor::DrawFileMenu () private
Todo:
Implement this
Definition at line 283 of file assembly_editor.cc.
References ChangeActiveFile(), and yaze::util::FileDialogWrapper::ShowOpenFileDialog().
Referenced by Update().
DrawEditMenu()
void yaze::editor::AssemblyEditor::DrawEditMenu () private
Todo:
Implement this.
Definition at line 296 of file assembly_editor.cc.
References TextEditor::Copy(), TextEditor::Cut(), TextEditor::Paste(), TextEditor::Redo(), text_editor_, and TextEditor::Undo().
Referenced by Update().
SetEditorText()
void yaze::editor::AssemblyEditor::SetEditorText () private
Definition at line 322 of file assembly_editor.cc.
References current_file_, file_is_loaded_, TextEditor::SetText(), and text_editor_.
Referenced by InlineUpdate(), Update(), and UpdateCodeView().
DrawCurrentFolder()
void yaze::editor::AssemblyEditor::DrawCurrentFolder () private
Definition at line 180 of file assembly_editor.cc.
References ChangeActiveFile(), current_folder_, yaze::editor::FolderItem::files, yaze::editor::FolderItem::name, and yaze::editor::FolderItem::subfolders.
Referenced by UpdateCodeView().
DrawFileTabView()
void yaze::editor::AssemblyEditor::DrawFileTabView () private
Definition at line 230 of file assembly_editor.cc.
References active_files_, TextEditor::CanUndo(), current_file_, current_file_id_, files_, TextEditor::GetCursorPosition(), TextEditor::GetLanguageDefinition(), TextEditor::GetTotalLines(), ICON_MD_ADD, TextEditor::IsOverwrite(), TextEditor::LanguageDefinition::mName, open_files_, TextEditor::SetText(), and text_editor_.
Member Data Documentation
file_is_loaded_
bool yaze::editor::AssemblyEditor::file_is_loaded_ = false private
Definition at line 68 of file assembly_editor.h.
Referenced by ChangeActiveFile(), and SetEditorText().
current_file_id_
int yaze::editor::AssemblyEditor::current_file_id_ = 0 private
Definition at line 69 of file assembly_editor.h.
Referenced by DrawFileTabView().
files_
std::vector<std::string> yaze::editor::AssemblyEditor::files_ private
Definition at line 71 of file assembly_editor.h.
Referenced by DrawFileTabView().
open_files_
std::vector<TextEditor> yaze::editor::AssemblyEditor::open_files_ private
Definition at line 72 of file assembly_editor.h.
Referenced by DrawFileTabView().
active_files_
ImVector<int> yaze::editor::AssemblyEditor::active_files_ private
Definition at line 73 of file assembly_editor.h.
Referenced by DrawFileTabView().
current_file_
std::string yaze::editor::AssemblyEditor::current_file_ private
Definition at line 75 of file assembly_editor.h.
Referenced by ChangeActiveFile(), DrawFileTabView(), InlineUpdate(), SetEditorText(), Update(), and UpdateCodeView().
current_folder_
FolderItem yaze::editor::AssemblyEditor::current_folder_ private
Definition at line 76 of file assembly_editor.h.
Referenced by DrawCurrentFolder(), OpenFolder(), and UpdateCodeView().
text_editor_
TextEditor yaze::editor::AssemblyEditor::text_editor_ private
Definition at line 77 of file assembly_editor.h.
Referenced by AssemblyEditor(), Copy(), Cut(), DrawEditMenu(), DrawFileTabView(), InlineUpdate(), Paste(), Redo(), SetEditorText(), Undo(), Update(), and UpdateCodeView().
rom_
Rom* yaze::editor::AssemblyEditor::rom_ private
Definition at line 79 of file assembly_editor.h.
Referenced by rom(), and set_rom().
The documentation for this class was generated from the following files:
src/app/editor/code/assembly_editor.h
src/app/editor/code/assembly_editor.cc