yaze: yaze::test::E2ETestSuite Class Reference
yaze::test::E2ETestSuite Class Reference
End-to-End test suite for comprehensive ROM testing.
#include <e2e_test_suite.h>
Public Member Functions
E2ETestSuite ()=default
~E2ETestSuite () override=default
std::string GetName () const override
TestCategory GetCategory () const override
absl::Status RunTests (TestResults &results) override
void DrawConfiguration () override
Public Member Functions inherited from yaze::test::TestSuite
virtual ~TestSuite ()=default
virtual bool IsEnabled () const
virtual void SetEnabled (bool enabled)
Private Member Functions
void AddSkippedTest (TestResults &results, const std::string &test_name, const std::string &reason)
void RunRomLoadSaveTest (TestResults &results, Rom *rom)
void RunDataIntegrityTest (TestResults &results, Rom *rom)
void RunTransactionSystemTest (TestResults &results, Rom *rom)
void RunLargeScaleEditingTest (TestResults &results, Rom *rom)
void RunCorruptionDetectionTest (TestResults &results, Rom *rom)
Private Attributes
bool test_rom_load_save_ = true
bool test_data_integrity_ = true
bool test_transaction_system_ = true
bool test_large_scale_editing_ = true
bool test_corruption_detection_ = true
int num_edits_ = 10
Additional Inherited Members
Protected Attributes inherited from yaze::test::TestSuite
bool enabled_ = true
Detailed Description
End-to-End test suite for comprehensive ROM testing.
This test suite provides comprehensive E2E testing capabilities including:
ROM loading/saving validation
Data integrity testing
Transaction system testing
Large-scale editing validation
Definition at line 25 of file e2e_test_suite.h.
Constructor & Destructor Documentation
E2ETestSuite()
yaze::test::E2ETestSuite::E2ETestSuite () default
~E2ETestSuite()
yaze::test::E2ETestSuite::~E2ETestSuite () override default
Member Function Documentation
GetName()
std::string yaze::test::E2ETestSuite::GetName () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 30 of file e2e_test_suite.h.
Referenced by AddSkippedTest(), RunCorruptionDetectionTest(), RunDataIntegrityTest(), RunLargeScaleEditingTest(), RunRomLoadSaveTest(), and RunTransactionSystemTest().
GetCategory()
TestCategory yaze::test::E2ETestSuite::GetCategory () const inline override virtual
Implements yaze::test::TestSuite.
Definition at line 31 of file e2e_test_suite.h.
References yaze::test::kIntegration.
Referenced by AddSkippedTest(), RunCorruptionDetectionTest(), RunDataIntegrityTest(), RunLargeScaleEditingTest(), RunRomLoadSaveTest(), and RunTransactionSystemTest().
RunTests()
absl::Status yaze::test::E2ETestSuite::RunTests (TestResults & results) inline override virtual
Implements yaze::test::TestSuite.
Definition at line 33 of file e2e_test_suite.h.
References AddSkippedTest(), yaze::test::TestManager::Get(), yaze::test::TestManager::GetCurrentRom(), yaze::Rom::is_loaded(), RunCorruptionDetectionTest(), RunDataIntegrityTest(), RunLargeScaleEditingTest(), RunRomLoadSaveTest(), RunTransactionSystemTest(), test_corruption_detection_, test_data_integrity_, test_large_scale_editing_, test_rom_load_save_, and test_transaction_system_.
DrawConfiguration()
void yaze::test::E2ETestSuite::DrawConfiguration () inline override virtual
Reimplemented from yaze::test::TestSuite.
Definition at line 66 of file e2e_test_suite.h.
References yaze::test::TestManager::Get(), yaze::test::TestManager::GetCurrentRom(), ICON_MD_CHECK_CIRCLE, ICON_MD_VERIFIED_USER, ICON_MD_WARNING, yaze::Rom::is_loaded(), num_edits_, yaze::Rom::size(), test_corruption_detection_, test_data_integrity_, test_large_scale_editing_, test_rom_load_save_, test_transaction_system_, and yaze::Rom::title().
AddSkippedTest()
void yaze::test::E2ETestSuite::AddSkippedTest (TestResults & results, const std::string & test_name, const std::string & reason) inline private
Definition at line 97 of file e2e_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, GetCategory(), GetName(), yaze::test::kSkipped, yaze::test::TestResult::name, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunRomLoadSaveTest()
void yaze::test::E2ETestSuite::RunRomLoadSaveTest (TestResults & results, Rom * rom) inline private
Definition at line 109 of file e2e_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::Rom::SaveSettings::filename, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::SaveToFile(), yaze::Rom::size(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunDataIntegrityTest()
void yaze::test::E2ETestSuite::RunDataIntegrityTest (TestResults & results, Rom * rom) inline private
Definition at line 160 of file e2e_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), yaze::test::TestResult::status, yaze::test::TestResult::suite_name, and yaze::test::TestResult::timestamp.
Referenced by RunTests().
RunTransactionSystemTest()
void yaze::test::E2ETestSuite::RunTransactionSystemTest (TestResults & results, Rom * rom) inline private
Definition at line 214 of file e2e_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::Transaction::Commit(), yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), yaze::Rom::ReadWord(), RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, yaze::Transaction::WriteByte(), and yaze::Transaction::WriteWord().
Referenced by RunTests().
RunLargeScaleEditingTest()
void yaze::test::E2ETestSuite::RunLargeScaleEditingTest (TestResults & results, Rom * rom) inline private
Definition at line 283 of file e2e_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, num_edits_, yaze::Rom::ReadByte(), RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and yaze::Rom::WriteByte().
Referenced by RunTests().
RunCorruptionDetectionTest()
void yaze::test::E2ETestSuite::RunCorruptionDetectionTest (TestResults & results, Rom * rom) inline private
Definition at line 344 of file e2e_test_suite.h.
References yaze::test::TestResults::AddResult(), yaze::test::TestResult::category, yaze::test::TestResult::duration, yaze::test::TestResult::error_message, yaze::test::TestManager::Get(), GetCategory(), GetName(), yaze::test::kFailed, yaze::test::kPassed, yaze::test::TestResult::name, yaze::Rom::ReadByte(), RETURN_IF_ERROR, yaze::test::TestResult::status, yaze::test::TestResult::suite_name, yaze::test::TestResult::timestamp, and yaze::Rom::WriteByte().
Referenced by RunTests().
Member Data Documentation
test_rom_load_save_
bool yaze::test::E2ETestSuite::test_rom_load_save_ = true private
Definition at line 409 of file e2e_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_data_integrity_
bool yaze::test::E2ETestSuite::test_data_integrity_ = true private
Definition at line 410 of file e2e_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_transaction_system_
bool yaze::test::E2ETestSuite::test_transaction_system_ = true private
Definition at line 411 of file e2e_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_large_scale_editing_
bool yaze::test::E2ETestSuite::test_large_scale_editing_ = true private
Definition at line 412 of file e2e_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
test_corruption_detection_
bool yaze::test::E2ETestSuite::test_corruption_detection_ = true private
Definition at line 413 of file e2e_test_suite.h.
Referenced by DrawConfiguration(), and RunTests().
num_edits_
int yaze::test::E2ETestSuite::num_edits_ = 10 private
Definition at line 414 of file e2e_test_suite.h.
Referenced by DrawConfiguration(), and RunLargeScaleEditingTest().
The documentation for this class was generated from the following file:
src/app/test/e2e_test_suite.h