yaze: yaze::editor::AgentChatWidget::Z3EDCommandCallbacks Struct Reference
yaze::editor::AgentChatWidget::Z3EDCommandCallbacks Struct Reference
#include <agent_chat_widget.h>
Public Attributes
std::function< absl::Status(const std::string &)> run_agent_task
std::function< absl::StatusOr< std::string >(const std::string &)> plan_agent_task
std::function< absl::StatusOr< std::string >(const std::string &)> diff_proposal
std::function< absl::Status(const std::string &)> accept_proposal
std::function< absl::Status(const std::string &)> reject_proposal
std::function< absl::StatusOr< std::vector< std::string > >()> list_proposals
Detailed Description
Definition at line 86 of file agent_chat_widget.h.
Member Data Documentation
run_agent_task
std::function<absl::Status(const std::string&)> yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::run_agent_task
Definition at line 87 of file agent_chat_widget.h.
Referenced by yaze::editor::AgentChatWidget::RenderZ3EDCommandPanel().
plan_agent_task
std::function<absl::StatusOr<std::string>(const std::string&)> yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::plan_agent_task
Definition at line 88 of file agent_chat_widget.h.
diff_proposal
std::function<absl::StatusOr<std::string>(const std::string&)> yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::diff_proposal
Definition at line 89 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), and yaze::editor::AgentChatWidget::RenderZ3EDCommandPanel().
accept_proposal
std::function<absl::Status(const std::string&)> yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::accept_proposal
Definition at line 90 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderProposalManagerPanel(), and yaze::editor::AgentChatWidget::RenderZ3EDCommandPanel().
reject_proposal
std::function<absl::Status(const std::string&)> yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::reject_proposal
Definition at line 91 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderProposalManagerPanel(), and yaze::editor::AgentChatWidget::RenderZ3EDCommandPanel().
list_proposals
std::function<absl::StatusOr<std::vector<std::string> >()> yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::list_proposals
Definition at line 92 of file agent_chat_widget.h.
Referenced by yaze::editor::EditorManager::Initialize(), yaze::editor::AgentChatWidget::RenderProposalManagerPanel(), and yaze::editor::AgentChatWidget::RenderZ3EDCommandPanel().
The documentation for this struct was generated from the following file:
src/app/editor/agent/agent_chat_widget.h