yaze: yaze::gui::CanvasInteractionEvents Struct Reference
yaze::gui::CanvasInteractionEvents Struct Reference
Combined interaction result for a frame.
#include <canvas_events.h>
Public Member Functions
void Reset ()
Reset all events.
bool HasAnyEvent () const
Check if any event occurred.
Public Attributes
TilePaintEvent tile_paint
RectSelectionEvent rect_selection
TileSelectionEvent tile_selection
EntityInteractionEvent entity_interaction
HoverEvent hover
Detailed Description
Combined interaction result for a frame.
Aggregates all possible interaction events for a single frame update. Handlers populate relevant events, consumers check which events occurred.
Definition at line 147 of file canvas_events.h.
Member Function Documentation
Reset()
void yaze::gui::CanvasInteractionEvents::Reset () inline
Reset all events.
Definition at line 155 of file canvas_events.h.
References entity_interaction, hover, rect_selection, yaze::gui::TilePaintEvent::Reset(), yaze::gui::RectSelectionEvent::Reset(), yaze::gui::TileSelectionEvent::Reset(), yaze::gui::EntityInteractionEvent::Reset(), yaze::gui::HoverEvent::Reset(), tile_paint, and tile_selection.
HasAnyEvent()
bool yaze::gui::CanvasInteractionEvents::HasAnyEvent () const inline
Check if any event occurred.
Definition at line 164 of file canvas_events.h.
References entity_interaction, hover, yaze::gui::TilePaintEvent::is_complete, yaze::gui::RectSelectionEvent::is_complete, yaze::gui::TileSelectionEvent::is_valid, yaze::gui::EntityInteractionEvent::is_valid, yaze::gui::HoverEvent::is_valid, rect_selection, tile_paint, and tile_selection.
Member Data Documentation
tile_paint
TilePaintEvent yaze::gui::CanvasInteractionEvents::tile_paint
Definition at line 148 of file canvas_events.h.
Referenced by HasAnyEvent(), and Reset().
rect_selection
RectSelectionEvent yaze::gui::CanvasInteractionEvents::rect_selection
Definition at line 149 of file canvas_events.h.
Referenced by HasAnyEvent(), and Reset().
tile_selection
TileSelectionEvent yaze::gui::CanvasInteractionEvents::tile_selection
Definition at line 150 of file canvas_events.h.
Referenced by HasAnyEvent(), and Reset().
entity_interaction
EntityInteractionEvent yaze::gui::CanvasInteractionEvents::entity_interaction
Definition at line 151 of file canvas_events.h.
Referenced by HasAnyEvent(), and Reset().
hover
HoverEvent yaze::gui::CanvasInteractionEvents::hover
Definition at line 152 of file canvas_events.h.
Referenced by HasAnyEvent(), and Reset().
The documentation for this struct was generated from the following file:
src/app/gui/canvas/canvas_events.h