yaze: yaze::emu::input::InputManager Class Reference
yaze::emu::input::InputManager Class Reference
High-level input manager that bridges backend and SNES.
#include <input_manager.h>
Public Member Functions
InputManager ()=default
~InputManager ()
bool Initialize (InputBackendFactory::BackendType type=InputBackendFactory::BackendType::SDL2)
Initialize with specific backend.
void Initialize (std::unique_ptr< IInputBackend > backend)
Initialize with custom backend.
void Shutdown ()
Shutdown input system.
void Poll (Snes *snes, int player=1)
Poll input and update SNES controller state.
void ProcessEvent (void *event)
Process platform-specific event (optional)
IInputBackend * backend ()
Get backend for configuration.
const IInputBackend * backend () const
bool IsInitialized () const
Check if initialized.
InputConfig GetConfig () const
Get/set configuration.
void SetConfig (const InputConfig &config)
Private Attributes
std::unique_ptr< IInputBackend > backend_
Detailed Description
High-level input manager that bridges backend and SNES.
This class provides a simple interface for both GUI and headless modes:
Manages input backend lifecycle
Polls input and updates SNES controller state
Handles multiple players
Supports hot-swapping input configurations
Definition at line 24 of file input_manager.h.
Constructor & Destructor Documentation
InputManager()
yaze::emu::input::InputManager::InputManager () default
~InputManager()
yaze::emu::input::InputManager::~InputManager () inline
Definition at line 27 of file input_manager.h.
References Shutdown().
Member Function Documentation
Initialize() [1/2]
bool yaze::emu::input::InputManager::Initialize (InputBackendFactory::BackendType type = InputBackendFactory::BackendType::SDL2)
Initialize with specific backend.
Todo:
Enable when gamepad support added
Definition at line 10 of file input_manager.cc.
References backend_, yaze::emu::input::InputConfig::continuous_polling, yaze::emu::input::InputBackendFactory::Create(), yaze::emu::input::InputConfig::enable_gamepad, LOG_ERROR, and LOG_INFO.
Referenced by yaze::emu::Emulator::Run().
Initialize() [2/2]
void yaze::emu::input::InputManager::Initialize (std::unique_ptr< IInputBackend > backend)
Initialize with custom backend.
Definition at line 31 of file input_manager.cc.
References backend(), backend_, and LOG_INFO.
Shutdown()
void yaze::emu::input::InputManager::Shutdown ()
Shutdown input system.
Definition at line 40 of file input_manager.cc.
References backend_.
Referenced by ~InputManager().
Poll()
void yaze::emu::input::InputManager::Poll (Snes * snes, int player = 1)
Poll input and update SNES controller state.
Parameters
snes SNES instance to update
player Player number (1-4)
Definition at line 47 of file input_manager.cc.
References backend_, yaze::emu::input::ControllerState::buttons, and yaze::emu::Snes::SetButtonState().
Referenced by yaze::emu::Emulator::Run().
ProcessEvent()
void yaze::emu::input::InputManager::ProcessEvent (void * event)
Process platform-specific event (optional)
Parameters
event Platform event (e.g., SDL_Event*)
Definition at line 61 of file input_manager.cc.
References backend_.
backend() [1/2]
IInputBackend * yaze::emu::input::InputManager::backend () inline
Get backend for configuration.
Definition at line 60 of file input_manager.h.
References backend_.
Referenced by Initialize(), yaze::emu::ui::RenderKeyboardConfig(), and yaze::emu::Emulator::Run().
backend() [2/2]
const IInputBackend * yaze::emu::input::InputManager::backend () const inline
Definition at line 61 of file input_manager.h.
References backend_.
IsInitialized()
bool yaze::emu::input::InputManager::IsInitialized () const inline
Check if initialized.
Definition at line 66 of file input_manager.h.
References backend_.
Referenced by yaze::emu::Emulator::Run().
GetConfig()
InputConfig yaze::emu::input::InputManager::GetConfig () const
Get/set configuration.
Definition at line 67 of file input_manager.cc.
References backend_.
Referenced by yaze::emu::ui::RenderKeyboardConfig().
SetConfig()
void yaze::emu::input::InputManager::SetConfig (const InputConfig & config)
Definition at line 74 of file input_manager.cc.
References backend_.
Referenced by yaze::emu::ui::RenderKeyboardConfig().
Member Data Documentation
backend_
std::unique_ptr<IInputBackend> yaze::emu::input::InputManager::backend_ private
Definition at line 75 of file input_manager.h.
Referenced by backend(), backend(), GetConfig(), Initialize(), Initialize(), IsInitialized(), Poll(), ProcessEvent(), SetConfig(), and Shutdown().
The documentation for this class was generated from the following files:
src/app/emu/input/input_manager.h
src/app/emu/input/input_manager.cc