yaze: yaze::gfx::GraphicsOptimizer Class Reference
yaze::gfx::GraphicsOptimizer Class Reference
Comprehensive graphics optimization system for YAZE ROM hacking.
#include <graphics_optimizer.h>
Public Member Functions
void Initialize ()
Initialize the graphics optimizer.
OptimizationResult OptimizeSheet (const std::vector< uint8_t > &sheet_data, int sheet_id, const SnesPalette &palette, OptimizationStrategy strategy=OptimizationStrategy::kBalanced)
Optimize a single graphics sheet.
OptimizationResult OptimizeSheets (const std::unordered_map< int, std::vector< uint8_t > > &sheets, const std::unordered_map< int, SnesPalette > &palettes, OptimizationStrategy strategy=OptimizationStrategy::kBalanced)
Optimize multiple graphics sheets.
SheetOptimizationData AnalyzeSheet (const std::vector< uint8_t > &sheet_data, int sheet_id, const SnesPalette &palette)
Analyze graphics sheet for optimization opportunities.
std::unordered_map< int, SheetOptimizationData > GetOptimizationRecommendations (const std::unordered_map< int, std::vector< uint8_t > > &sheets, const std::unordered_map< int, SnesPalette > &palettes)
Get optimization recommendations for all sheets.
OptimizationResult ApplyOptimizations (const std::unordered_map< int, SheetOptimizationData > &recommendations, std::unordered_map< int, std::vector< uint8_t > > &sheets, std::unordered_map< int, SnesPalette > &palettes)
Apply optimization recommendations.
std::unordered_map< std::string, double > GetOptimizationStats () const
Get optimization statistics.
void ClearCache ()
Clear optimization cache.
void SetOptimizationParameters (float max_quality_loss=0.1f, size_t min_memory_savings=1024, float performance_threshold=0.05f)
Set optimization parameters.
Static Public Member Functions
static GraphicsOptimizer & Get ()
Private Member Functions
GraphicsOptimizer ()=default
~GraphicsOptimizer ()=default
BppFormat DetermineOptimalFormat (const std::vector< uint8_t > &data, const SnesPalette &palette, OptimizationStrategy strategy)
float CalculateQualityLoss (BppFormat from_format, BppFormat to_format, const std::vector< uint8_t > &data)
size_t CalculateMemorySavings (BppFormat from_format, BppFormat to_format, const std::vector< uint8_t > &data)
float CalculatePerformanceGain (BppFormat from_format, BppFormat to_format)
bool ShouldOptimize (const SheetOptimizationData &data, OptimizationStrategy strategy)
std::string GenerateOptimizationReason (const SheetOptimizationData &data)
int CountUsedColors (const std::vector< uint8_t > &data, const SnesPalette &palette)
float CalculateColorEfficiency (const std::vector< uint8_t > &data, const SnesPalette &palette)
std::vector< int > AnalyzeColorDistribution (const std::vector< uint8_t > &data)
std::string GenerateCacheKey (const std::vector< uint8_t > &data, int sheet_id)
void UpdateOptimizationStats (const std::string &operation, double value)
Private Attributes
float max_quality_loss_
size_t min_memory_savings_
float performance_threshold_
std::unordered_map< std::string, double > optimization_stats_
std::unordered_map< std::string, SheetOptimizationData > optimization_cache_
Detailed Description
Comprehensive graphics optimization system for YAZE ROM hacking.
The GraphicsOptimizer provides intelligent optimization of graphics data for Link to the Past ROM hacking workflows, balancing memory usage, performance, and visual quality.
Key Features:
Intelligent BPP format optimization based on actual color usage
Graphics sheet analysis and conversion recommendations
Memory usage optimization with quality preservation
Performance optimization through atlas rendering
Batch processing for multiple graphics sheets
Quality analysis and loss estimation
Optimization Strategies:
Memory Optimized: Minimize ROM size by using optimal BPP formats
Performance Optimized: Maximize rendering speed through atlas optimization
Quality Optimized: Preserve visual fidelity while optimizing
Balanced: Optimal balance of memory, performance, and quality
ROM Hacking Specific:
SNES-specific optimization patterns
Graphics sheet format analysis and conversion tracking
Palette optimization based on actual usage
Integration with existing YAZE graphics pipeline
Definition at line 89 of file graphics_optimizer.h.
Constructor & Destructor Documentation
GraphicsOptimizer()
yaze::gfx::GraphicsOptimizer::GraphicsOptimizer () private default
~GraphicsOptimizer()
yaze::gfx::GraphicsOptimizer::~GraphicsOptimizer () private default
Member Function Documentation
Get()
GraphicsOptimizer & yaze::gfx::GraphicsOptimizer::Get () static
Definition at line 14 of file graphics_optimizer.cc.
Initialize()
void yaze::gfx::GraphicsOptimizer::Initialize ()
Initialize the graphics optimizer.
Definition at line 19 of file graphics_optimizer.cc.
References max_quality_loss_, min_memory_savings_, optimization_cache_, optimization_stats_, and performance_threshold_.
OptimizeSheet()
OptimizationResult yaze::gfx::GraphicsOptimizer::OptimizeSheet (const std::vector< uint8_t > & sheet_data, int sheet_id, const SnesPalette & palette, OptimizationStrategy strategy = OptimizationStrategy::kBalanced)
Optimize a single graphics sheet.
Parameters
sheet_data Graphics sheet data
sheet_id Sheet identifier
palette Sheet palette
strategy Optimization strategy
Returns
Optimization result
Definition at line 28 of file graphics_optimizer.cc.
References AnalyzeSheet(), CalculatePerformanceGain(), CalculateQualityLoss(), yaze::gfx::SheetOptimizationData::current_format, yaze::gfx::SheetOptimizationData::current_size, yaze::gfx::SheetOptimizationData::is_convertible, max_quality_loss_, yaze::gfx::OptimizationResult::memory_saved, yaze::gfx::OptimizationResult::message, min_memory_savings_, yaze::gfx::SheetOptimizationData::optimized_size, yaze::gfx::OptimizationResult::performance_gain, performance_threshold_, yaze::gfx::OptimizationResult::quality_loss, yaze::gfx::SheetOptimizationData::recommended_format, yaze::gfx::OptimizationResult::recommended_formats, yaze::gfx::OptimizationResult::sheet_recommendations, ShouldOptimize(), yaze::gfx::OptimizationResult::success, and UpdateOptimizationStats().
Referenced by OptimizeSheets().
OptimizeSheets()
OptimizationResult yaze::gfx::GraphicsOptimizer::OptimizeSheets (const std::unordered_map< int, std::vector< uint8_t > > & sheets, const std::unordered_map< int, SnesPalette > & palettes, OptimizationStrategy strategy = OptimizationStrategy::kBalanced)
Optimize multiple graphics sheets.
Parameters
sheets Map of sheet ID to sheet data
palettes Map of sheet ID to palette
strategy Optimization strategy
Returns
Optimization result
Definition at line 85 of file graphics_optimizer.cc.
References yaze::gfx::OptimizationResult::memory_saved, yaze::gfx::OptimizationResult::message, OptimizeSheet(), yaze::gfx::OptimizationResult::performance_gain, yaze::gfx::OptimizationResult::quality_loss, yaze::gfx::OptimizationResult::recommended_formats, yaze::gfx::OptimizationResult::sheet_recommendations, yaze::gfx::OptimizationResult::success, and UpdateOptimizationStats().
AnalyzeSheet()
SheetOptimizationData yaze::gfx::GraphicsOptimizer::AnalyzeSheet (const std::vector< uint8_t > & sheet_data, int sheet_id, const SnesPalette & palette)
Analyze graphics sheet for optimization opportunities.
Parameters
sheet_data Graphics sheet data
sheet_id Sheet identifier
palette Sheet palette
Returns
Optimization data
Definition at line 138 of file graphics_optimizer.cc.
References yaze::gfx::SheetOptimizationData::colors_used, yaze::gfx::SheetOptimizationData::compression_ratio, CountUsedColors(), yaze::gfx::SheetOptimizationData::current_format, yaze::gfx::SheetOptimizationData::current_size, yaze::gfx::BppFormatManager::DetectFormat(), DetermineOptimalFormat(), GenerateCacheKey(), GenerateOptimizationReason(), yaze::gfx::BppFormatManager::Get(), yaze::gfx::BppFormatManager::GetFormatInfo(), yaze::gfx::SheetOptimizationData::is_convertible, yaze::gfx::kBalanced, optimization_cache_, yaze::gfx::SheetOptimizationData::optimization_reason, yaze::gfx::SheetOptimizationData::optimized_size, yaze::gfx::SheetOptimizationData::recommended_format, and yaze::gfx::SheetOptimizationData::sheet_id.
Referenced by GetOptimizationRecommendations(), and OptimizeSheet().
GetOptimizationRecommendations()
std::unordered_map< int, SheetOptimizationData > yaze::gfx::GraphicsOptimizer::GetOptimizationRecommendations (const std::unordered_map< int, std::vector< uint8_t > > & sheets, const std::unordered_map< int, SnesPalette > & palettes)
Get optimization recommendations for all sheets.
Parameters
sheets Map of sheet ID to sheet data
palettes Map of sheet ID to palette
Returns
Map of sheet ID to optimization data
Definition at line 183 of file graphics_optimizer.cc.
References AnalyzeSheet().
ApplyOptimizations()
OptimizationResult yaze::gfx::GraphicsOptimizer::ApplyOptimizations (const std::unordered_map< int, SheetOptimizationData > & recommendations, std::unordered_map< int, std::vector< uint8_t > > & sheets, std::unordered_map< int, SnesPalette > & palettes)
Apply optimization recommendations.
Parameters
recommendations Optimization recommendations
sheets Map of sheet ID to sheet data (modified in place)
palettes Map of sheet ID to palette (modified in place)
Returns
Optimization result
Definition at line 201 of file graphics_optimizer.cc.
References yaze::gfx::BppFormatManager::ConvertFormat(), yaze::gfx::BppFormatManager::Get(), yaze::gfx::OptimizationResult::memory_saved, yaze::gfx::OptimizationResult::message, yaze::gfx::BppFormatManager::OptimizePaletteForFormat(), yaze::gfx::OptimizationResult::sheet_recommendations, yaze::gfx::OptimizationResult::success, and UpdateOptimizationStats().
GetOptimizationStats()
std::unordered_map< std::string, double > yaze::gfx::GraphicsOptimizer::GetOptimizationStats () const
Get optimization statistics.
Returns
Map of optimization statistics
Definition at line 263 of file graphics_optimizer.cc.
References optimization_stats_.
ClearCache()
void yaze::gfx::GraphicsOptimizer::ClearCache ()
Clear optimization cache.
Definition at line 267 of file graphics_optimizer.cc.
References optimization_cache_, and optimization_stats_.
SetOptimizationParameters()
void yaze::gfx::GraphicsOptimizer::SetOptimizationParameters (float max_quality_loss = 0.1f, size_t min_memory_savings = 1024, float performance_threshold = 0.05f)
Set optimization parameters.
Parameters
max_quality_loss Maximum acceptable quality loss (0.0-1.0)
min_memory_savings Minimum required memory savings (bytes)
performance_threshold Minimum performance gain threshold
Definition at line 272 of file graphics_optimizer.cc.
References max_quality_loss_, min_memory_savings_, and performance_threshold_.
DetermineOptimalFormat()
BppFormat yaze::gfx::GraphicsOptimizer::DetermineOptimalFormat (const std::vector< uint8_t > & data, const SnesPalette & palette, OptimizationStrategy strategy) private
Definition at line 282 of file graphics_optimizer.cc.
References CountUsedColors(), yaze::gfx::kBalanced, yaze::gfx::kBpp2, yaze::gfx::kBpp3, yaze::gfx::kBpp4, yaze::gfx::kBpp8, yaze::gfx::kMemoryOptimized, yaze::gfx::kPerformanceOptimized, and yaze::gfx::kQualityOptimized.
Referenced by AnalyzeSheet().
CalculateQualityLoss()
float yaze::gfx::GraphicsOptimizer::CalculateQualityLoss (BppFormat from_format, BppFormat to_format, const std::vector< uint8_t > & data) private
Definition at line 315 of file graphics_optimizer.cc.
Referenced by OptimizeSheet().
CalculateMemorySavings()
size_t yaze::gfx::GraphicsOptimizer::CalculateMemorySavings (BppFormat from_format, BppFormat to_format, const std::vector< uint8_t > & data) private
Definition at line 328 of file graphics_optimizer.cc.
References yaze::gfx::BppFormatInfo::bits_per_pixel, yaze::gfx::BppFormatManager::Get(), and yaze::gfx::BppFormatManager::GetFormatInfo().
CalculatePerformanceGain()
float yaze::gfx::GraphicsOptimizer::CalculatePerformanceGain (BppFormat from_format, BppFormat to_format) private
Definition at line 341 of file graphics_optimizer.cc.
Referenced by OptimizeSheet().
ShouldOptimize()
bool yaze::gfx::GraphicsOptimizer::ShouldOptimize (const SheetOptimizationData & data, OptimizationStrategy strategy) private
Definition at line 353 of file graphics_optimizer.cc.
References yaze::gfx::SheetOptimizationData::compression_ratio, yaze::gfx::SheetOptimizationData::is_convertible, yaze::gfx::kBalanced, yaze::gfx::kMemoryOptimized, yaze::gfx::kPerformanceOptimized, and yaze::gfx::kQualityOptimized.
Referenced by OptimizeSheet().
GenerateOptimizationReason()
std::string yaze::gfx::GraphicsOptimizer::GenerateOptimizationReason (const SheetOptimizationData & data) private
Definition at line 373 of file graphics_optimizer.cc.
References yaze::gfx::SheetOptimizationData::colors_used, yaze::gfx::SheetOptimizationData::compression_ratio, yaze::gfx::SheetOptimizationData::current_format, yaze::gfx::BppFormatManager::Get(), yaze::gfx::BppFormatManager::GetFormatInfo(), yaze::gfx::BppFormatInfo::name, and yaze::gfx::SheetOptimizationData::recommended_format.
Referenced by AnalyzeSheet().
CountUsedColors()
int yaze::gfx::GraphicsOptimizer::CountUsedColors (const std::vector< uint8_t > & data, const SnesPalette & palette) private
Definition at line 385 of file graphics_optimizer.cc.
References yaze::gfx::SnesPalette::size().
Referenced by AnalyzeSheet(), CalculateColorEfficiency(), and DetermineOptimalFormat().
CalculateColorEfficiency()
float yaze::gfx::GraphicsOptimizer::CalculateColorEfficiency (const std::vector< uint8_t > & data, const SnesPalette & palette) private
Definition at line 402 of file graphics_optimizer.cc.
References CountUsedColors(), and yaze::gfx::SnesPalette::size().
AnalyzeColorDistribution()
std::vector< int > yaze::gfx::GraphicsOptimizer::AnalyzeColorDistribution (const std::vector< uint8_t > & data) private
Definition at line 407 of file graphics_optimizer.cc.
GenerateCacheKey()
std::string yaze::gfx::GraphicsOptimizer::GenerateCacheKey (const std::vector< uint8_t > & data, int sheet_id) private
Definition at line 417 of file graphics_optimizer.cc.
Referenced by AnalyzeSheet().
UpdateOptimizationStats()
void yaze::gfx::GraphicsOptimizer::UpdateOptimizationStats (const std::string & operation, double value) private
Definition at line 431 of file graphics_optimizer.cc.
References optimization_stats_.
Referenced by ApplyOptimizations(), OptimizeSheet(), and OptimizeSheets().
Member Data Documentation
max_quality_loss_
float yaze::gfx::GraphicsOptimizer::max_quality_loss_ private
Definition at line 181 of file graphics_optimizer.h.
Referenced by Initialize(), OptimizeSheet(), and SetOptimizationParameters().
min_memory_savings_
size_t yaze::gfx::GraphicsOptimizer::min_memory_savings_ private
Definition at line 182 of file graphics_optimizer.h.
Referenced by Initialize(), OptimizeSheet(), and SetOptimizationParameters().
performance_threshold_
float yaze::gfx::GraphicsOptimizer::performance_threshold_ private
Definition at line 183 of file graphics_optimizer.h.
Referenced by Initialize(), OptimizeSheet(), and SetOptimizationParameters().
optimization_stats_
std::unordered_map<std::string, double> yaze::gfx::GraphicsOptimizer::optimization_stats_ private
Definition at line 186 of file graphics_optimizer.h.
Referenced by ClearCache(), GetOptimizationStats(), Initialize(), and UpdateOptimizationStats().
optimization_cache_
std::unordered_map<std::string, SheetOptimizationData> yaze::gfx::GraphicsOptimizer::optimization_cache_ private
Definition at line 189 of file graphics_optimizer.h.
Referenced by AnalyzeSheet(), ClearCache(), and Initialize().
The documentation for this class was generated from the following files:
src/app/gfx/graphics_optimizer.h
src/app/gfx/graphics_optimizer.cc