yaze: yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc} Namespace Reference
yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc} Namespace Reference
Functions
constexpr ImVec4 kColorAddress (0.4f, 0.8f, 1.0f, 1.0f)
constexpr ImVec4 kColorOpcode (0.8f, 0.8f, 0.8f, 1.0f)
constexpr ImVec4 kColorMnemonic (1.0f, 0.8f, 0.2f, 1.0f)
constexpr ImVec4 kColorOperand (0.6f, 1.0f, 0.6f, 1.0f)
constexpr ImVec4 kColorComment (0.5f, 0.5f, 0.5f, 1.0f)
constexpr ImVec4 kColorCurrentPC (1.0f, 0.3f, 0.3f, 1.0f)
constexpr ImVec4 kColorBreakpoint (1.0f, 0.0f, 0.0f, 1.0f)
constexpr ImVec4 kColorHotPath (1.0f, 0.6f, 0.0f, 1.0f)
Function Documentation
kColorAddress()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorAddress (0. 4f, 0. 8f, 1. 0f, 1. 0f) constexpr
References kColorAddress().
Referenced by kColorAddress().
kColorOpcode()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorOpcode (0. 8f, 0. 8f, 0. 8f, 1. 0f) constexpr
References kColorOpcode().
Referenced by kColorOpcode().
kColorMnemonic()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorMnemonic (1. 0f, 0. 8f, 0. 2f, 1. 0f) constexpr
References kColorMnemonic().
Referenced by kColorMnemonic().
kColorOperand()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorOperand (0. 6f, 1. 0f, 0. 6f, 1. 0f) constexpr
References kColorOperand().
Referenced by kColorOperand().
kColorComment()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorComment (0. 5f, 0. 5f, 0. 5f, 1. 0f) constexpr
References kColorComment().
Referenced by kColorComment().
kColorCurrentPC()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorCurrentPC (1. 0f, 0. 3f, 0. 3f, 1. 0f) constexpr
References kColorCurrentPC().
Referenced by kColorCurrentPC().
kColorBreakpoint()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorBreakpoint (1. 0f, 0. 0f, 0. 0f, 1. 0f) constexpr
References kColorBreakpoint().
Referenced by kColorBreakpoint().
kColorHotPath()
constexpr ImVec4 yaze::emu::debug::anonymous_namespace{disassembly_viewer.cc}::kColorHotPath (1. 0f, 0. 6f, 0. 0f, 1. 0f) constexpr
References kColorHotPath().
Referenced by kColorHotPath().