yaze: yaze::cli::anonymous_namespace{resource_catalog.cc} Namespace Reference
yaze::cli::anonymous_namespace{resource_catalog.cc} Namespace Reference
Functions
ResourceSchema MakePaletteSchema ()
ResourceSchema MakeRomSchema ()
ResourceSchema MakePatchSchema ()
ResourceSchema MakeOverworldSchema ()
ResourceSchema MakeDungeonSchema ()
ResourceSchema MakeAgentSchema ()
Function Documentation
MakePaletteSchema()
ResourceSchema yaze::cli::anonymous_namespace{resource_catalog.cc}::MakePaletteSchema ()
Definition at line 14 of file resource_catalog.cc.
References yaze::cli::ResourceSchema::actions, yaze::cli::ResourceAction::arguments, yaze::cli::ResourceSchema::description, yaze::cli::ResourceAction::effects, MakePaletteSchema(), yaze::cli::ResourceAction::name, yaze::cli::ResourceSchema::resource, yaze::cli::ResourceAction::stability, and yaze::cli::ResourceAction::synopsis.
Referenced by MakePaletteSchema().
MakeRomSchema()
ResourceSchema yaze::cli::anonymous_namespace{resource_catalog.cc}::MakeRomSchema ()
Definition at line 49 of file resource_catalog.cc.
References yaze::cli::ResourceSchema::actions, yaze::cli::ResourceAction::arguments, yaze::cli::ResourceSchema::description, yaze::cli::ResourceAction::effects, MakeRomSchema(), yaze::cli::ResourceAction::name, yaze::cli::ResourceSchema::resource, yaze::cli::ResourceAction::returns, yaze::cli::ResourceAction::stability, and yaze::cli::ResourceAction::synopsis.
Referenced by MakeRomSchema().
MakePatchSchema()
ResourceSchema yaze::cli::anonymous_namespace{resource_catalog.cc}::MakePatchSchema ()
Definition at line 112 of file resource_catalog.cc.
References yaze::cli::ResourceSchema::actions, yaze::cli::ResourceAction::arguments, yaze::cli::ResourceSchema::description, yaze::cli::ResourceAction::effects, MakePatchSchema(), yaze::cli::ResourceAction::name, yaze::cli::ResourceSchema::resource, yaze::cli::ResourceAction::returns, yaze::cli::ResourceAction::stability, and yaze::cli::ResourceAction::synopsis.
Referenced by MakePatchSchema().
MakeOverworldSchema()
ResourceSchema yaze::cli::anonymous_namespace{resource_catalog.cc}::MakeOverworldSchema ()
Definition at line 171 of file resource_catalog.cc.
References yaze::cli::ResourceSchema::actions, yaze::cli::ResourceAction::arguments, yaze::cli::ResourceSchema::description, yaze::cli::ResourceAction::effects, MakeOverworldSchema(), yaze::cli::ResourceAction::name, yaze::cli::ResourceSchema::resource, yaze::cli::ResourceAction::returns, yaze::cli::ResourceAction::stability, and yaze::cli::ResourceAction::synopsis.
Referenced by MakeOverworldSchema().
MakeDungeonSchema()
ResourceSchema yaze::cli::anonymous_namespace{resource_catalog.cc}::MakeDungeonSchema ()
Definition at line 207 of file resource_catalog.cc.
References yaze::cli::ResourceSchema::actions, yaze::cli::ResourceAction::arguments, yaze::cli::ResourceSchema::description, yaze::cli::ResourceAction::effects, MakeDungeonSchema(), yaze::cli::ResourceAction::name, yaze::cli::ResourceSchema::resource, yaze::cli::ResourceAction::returns, yaze::cli::ResourceAction::stability, and yaze::cli::ResourceAction::synopsis.
Referenced by MakeDungeonSchema().
MakeAgentSchema()
ResourceSchema yaze::cli::anonymous_namespace{resource_catalog.cc}::MakeAgentSchema ()
Definition at line 244 of file resource_catalog.cc.
References yaze::cli::ResourceSchema::actions, yaze::cli::ResourceAction::arguments, yaze::cli::ResourceSchema::description, yaze::cli::ResourceAction::effects, MakeAgentSchema(), yaze::cli::ResourceAction::name, yaze::cli::ResourceSchema::resource, yaze::cli::ResourceAction::returns, yaze::cli::ResourceAction::stability, and yaze::cli::ResourceAction::synopsis.
Referenced by MakeAgentSchema().