yaze: yaze::editor::SpriteEditor Class Reference
yaze::editor::SpriteEditor Class Reference
Allows the user to edit sprites.
#include <sprite_editor.h>
Classes
struct OAMConfig
Public Member Functions
SpriteEditor (Rom *rom=nullptr)
void Initialize () override
absl::Status Load () override
absl::Status Update () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Find () override
absl::Status Save () override
void set_rom (Rom *rom)
Rom * rom () const
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Clear ()
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
virtual bool IsRomLoaded () const
virtual std::string GetRomStatus () const
Private Member Functions
void DrawVanillaSpriteEditor ()
void DrawSpritesList ()
Draws the sprites list.
void DrawSpriteCanvas ()
Draws the sprite canvas.
void DrawCurrentSheets ()
Draws the current sheets.
void DrawCustomSprites ()
void DrawCustomSpritesMetadata ()
void DrawAnimationFrames ()
Draws the animation frames manager.
void DrawToolset ()
Private Attributes
bool show_vanilla_editor_ = true
bool show_custom_editor_ = false
ImVector< int > active_sprites_
int current_sprite_id_
uint8_t current_sheets_ [8] = {0x00, 0x0A, 0x06, 0x07, 0x00, 0x00, 0x00, 0x00}
bool sheets_loaded_
OAMConfig oam_config_
gui::Bitmap oam_bitmap_
gui::Canvas sprite_canvas_
gui::Canvas graphics_sheet_canvas_
std::vector< zsprite::ZSprite > custom_sprites_
absl::Status status_
Rom * rom_
Additional Inherited Members
Protected Member Functions inherited from yaze::editor::Editor
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Detailed Description
Allows the user to edit sprites.
This class provides functionality for updating the sprite editor, drawing the editor table, drawing the sprite canvas, and drawing the current sheets.
Definition at line 37 of file sprite_editor.h.
Constructor & Destructor Documentation
SpriteEditor()
yaze::editor::SpriteEditor::SpriteEditor (Rom * rom = nullptr) inline explicit
Definition at line 39 of file sprite_editor.h.
References yaze::editor::kSprite, and yaze::editor::Editor::type_.
Member Function Documentation
Initialize()
void yaze::editor::SpriteEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 27 of file sprite_editor.cc.
Load()
absl::Status yaze::editor::SpriteEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 29 of file sprite_editor.cc.
Referenced by yaze::editor::EditorManager::LoadAssets().
Update()
absl::Status yaze::editor::SpriteEditor::Update () override virtual
Implements yaze::editor::Editor.
Definition at line 34 of file sprite_editor.cc.
References yaze::gui::EditorCard::Begin(), DrawCustomSprites(), DrawToolset(), DrawVanillaSpriteEditor(), yaze::gui::EditorCard::End(), ICON_MD_ADD_MODERATOR, ICON_MD_PEST_CONTROL_RODENT, rom(), sheets_loaded_, show_custom_editor_, show_vanilla_editor_, status_, and yaze::gui::VerticalSpacing().
Undo()
absl::Status yaze::editor::SpriteEditor::Undo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 46 of file sprite_editor.h.
Redo()
absl::Status yaze::editor::SpriteEditor::Redo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 47 of file sprite_editor.h.
Cut()
absl::Status yaze::editor::SpriteEditor::Cut () inline override virtual
Implements yaze::editor::Editor.
Definition at line 48 of file sprite_editor.h.
Copy()
absl::Status yaze::editor::SpriteEditor::Copy () inline override virtual
Implements yaze::editor::Editor.
Definition at line 49 of file sprite_editor.h.
Paste()
absl::Status yaze::editor::SpriteEditor::Paste () inline override virtual
Implements yaze::editor::Editor.
Definition at line 50 of file sprite_editor.h.
Find()
absl::Status yaze::editor::SpriteEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 51 of file sprite_editor.h.
Save()
absl::Status yaze::editor::SpriteEditor::Save () inline override virtual
Implements yaze::editor::Editor.
Definition at line 52 of file sprite_editor.h.
set_rom()
void yaze::editor::SpriteEditor::set_rom (Rom * rom) inline
Definition at line 55 of file sprite_editor.h.
References rom(), and rom_.
rom()
Rom * yaze::editor::SpriteEditor::rom () const inline
Definition at line 58 of file sprite_editor.h.
References rom_.
Referenced by DrawSpritesList(), set_rom(), and Update().
DrawVanillaSpriteEditor()
void yaze::editor::SpriteEditor::DrawVanillaSpriteEditor () private
Definition at line 78 of file sprite_editor.cc.
References active_sprites_, current_sprite_id_, DrawCurrentSheets(), DrawSpriteCanvas(), DrawSpritesList(), ICON_MD_ADD, yaze::editor::kSpriteTabBarFlags, and sheets_loaded_.
Referenced by Update().
DrawSpritesList()
void yaze::editor::SpriteEditor::DrawSpritesList () private
Draws the sprites list.
Definition at line 221 of file sprite_editor.cc.
References active_sprites_, current_sprite_id_, yaze::gui::GetID(), yaze::util::HexByte(), yaze::Rom::resource_label(), rom(), and yaze::core::ResourceLabelManager::SelectableLabelWithNameEdit().
Referenced by DrawVanillaSpriteEditor().
DrawSpriteCanvas()
void yaze::editor::SpriteEditor::DrawSpriteCanvas () private
Draws the sprite canvas.
Definition at line 137 of file sprite_editor.cc.
References DrawAnimationFrames(), yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawContextMenu(), DrawCustomSpritesMetadata(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::editor::SpriteEditor::OAMConfig::flip_x, yaze::editor::SpriteEditor::OAMConfig::flip_y, yaze::gui::GetID(), yaze::gui::InputHexByte(), yaze::gui::InputHexWord(), oam_config_, yaze::editor::SpriteEditor::OAMConfig::palette, yaze::editor::SpriteEditor::OAMConfig::priority, sprite_canvas_, yaze::editor::SpriteEditor::OAMConfig::tile, yaze::editor::SpriteEditor::OAMConfig::x, and yaze::editor::SpriteEditor::OAMConfig::y.
Referenced by DrawCustomSprites(), and DrawVanillaSpriteEditor().
DrawCurrentSheets()
void yaze::editor::SpriteEditor::DrawCurrentSheets () private
Draws the current sheets.
Definition at line 197 of file sprite_editor.cc.
References current_sheets_, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::gui::Canvas::DrawTileSelector(), yaze::gfx::Arena::Get(), yaze::gui::GetID(), graphics_sheet_canvas_, and yaze::gui::InputHexByte().
Referenced by DrawCustomSprites(), and DrawVanillaSpriteEditor().
DrawCustomSprites()
void yaze::editor::SpriteEditor::DrawCustomSprites () private
Definition at line 251 of file sprite_editor.cc.
References DrawCurrentSheets(), DrawCustomSpritesMetadata(), and DrawSpriteCanvas().
Referenced by Update().
DrawCustomSpritesMetadata()
void yaze::editor::SpriteEditor::DrawCustomSpritesMetadata () private
Definition at line 277 of file sprite_editor.cc.
References active_sprites_, current_sprite_id_, custom_sprites_, yaze::editor::zsprite::ZSprite::Load(), yaze::util::FileDialogWrapper::ShowOpenFileDialog(), and status_.
Referenced by DrawCustomSprites(), and DrawSpriteCanvas().
DrawAnimationFrames()
void yaze::editor::SpriteEditor::DrawAnimationFrames () private
Draws the animation frames manager.
Definition at line 242 of file sprite_editor.cc.
Referenced by DrawSpriteCanvas().
DrawToolset()
void yaze::editor::SpriteEditor::DrawToolset () private
Definition at line 63 of file sprite_editor.cc.
References yaze::gui::Toolset::AddAction(), yaze::gui::Toolset::Begin(), yaze::gui::Toolset::End(), ICON_MD_ADD_MODERATOR, ICON_MD_PEST_CONTROL_RODENT, show_custom_editor_, and show_vanilla_editor_.
Referenced by Update().
Member Data Documentation
show_vanilla_editor_
bool yaze::editor::SpriteEditor::show_vanilla_editor_ = true private
Definition at line 87 of file sprite_editor.h.
Referenced by DrawToolset(), and Update().
show_custom_editor_
bool yaze::editor::SpriteEditor::show_custom_editor_ = false private
Definition at line 88 of file sprite_editor.h.
Referenced by DrawToolset(), and Update().
active_sprites_
ImVector<int> yaze::editor::SpriteEditor::active_sprites_ private
Active sprites.
Definition at line 90 of file sprite_editor.h.
Referenced by DrawCustomSpritesMetadata(), DrawSpritesList(), and DrawVanillaSpriteEditor().
current_sprite_id_
int yaze::editor::SpriteEditor::current_sprite_id_ private
Current sprite ID.
Definition at line 92 of file sprite_editor.h.
Referenced by DrawCustomSpritesMetadata(), DrawSpritesList(), and DrawVanillaSpriteEditor().
current_sheets_
uint8_t yaze::editor::SpriteEditor::current_sheets_[8] = {0x00, 0x0A, 0x06, 0x07, 0x00, 0x00, 0x00, 0x00} private
Definition at line 93 of file sprite_editor.h.
Referenced by DrawCurrentSheets().
sheets_loaded_
bool yaze::editor::SpriteEditor::sheets_loaded_ private
Initial value:
=
      false
Flag indicating whether the sheets are loaded or not.
Definition at line 94 of file sprite_editor.h.
Referenced by DrawVanillaSpriteEditor(), and Update().
oam_config_
OAMConfig yaze::editor::SpriteEditor::oam_config_ private
OAM configuration.
Definition at line 108 of file sprite_editor.h.
Referenced by DrawSpriteCanvas().
oam_bitmap_
gui::Bitmap yaze::editor::SpriteEditor::oam_bitmap_ private
OAM bitmap.
Definition at line 109 of file sprite_editor.h.
sprite_canvas_
gui::Canvas yaze::editor::SpriteEditor::sprite_canvas_ private
Initial value:
{
      "SpriteCanvas", ImVec2(0x200, 0x200),
      gui::CanvasGridSize::k32x32}
Sprite canvas.
Definition at line 111 of file sprite_editor.h.
Referenced by DrawSpriteCanvas().
graphics_sheet_canvas_
gui::Canvas yaze::editor::SpriteEditor::graphics_sheet_canvas_ private
Initial value:
{
      "GraphicsSheetCanvas", ImVec2(0x80 * 2 + 2, 0x40 * 8 + 2),
      gui::CanvasGridSize::k16x16}
Graphics sheet canvas.
Definition at line 115 of file sprite_editor.h.
Referenced by DrawCurrentSheets().
custom_sprites_
std::vector<zsprite::ZSprite> yaze::editor::SpriteEditor::custom_sprites_ private
Sprites.
Definition at line 119 of file sprite_editor.h.
Referenced by DrawCustomSpritesMetadata().
status_
absl::Status yaze::editor::SpriteEditor::status_ private
Status.
Definition at line 121 of file sprite_editor.h.
Referenced by DrawCustomSpritesMetadata(), and Update().
rom_
Rom* yaze::editor::SpriteEditor::rom_ private
Definition at line 123 of file sprite_editor.h.
Referenced by rom(), and set_rom().
The documentation for this class was generated from the following files:
src/app/editor/sprite/sprite_editor.h
src/app/editor/sprite/sprite_editor.cc