yaze: yaze::zelda3::test Namespace Reference
yaze::zelda3::test Namespace Reference
Classes
class RoomIntegrationTest
class RoomManipulationTest
Functions
TEST_F (RoomIntegrationTest, BasicLoadSaveRoundTrip)
TEST_F (RoomIntegrationTest, MultiRoomLoadSaveRoundTrip)
TEST_F (RoomIntegrationTest, LayerPreservation)
TEST_F (RoomIntegrationTest, ObjectTypeDistribution)
TEST_F (RoomIntegrationTest, BinaryDataExactMatch)
TEST_F (RoomIntegrationTest, KnownRoomData)
TEST_F (RoomManipulationTest, AddObject)
TEST_F (RoomManipulationTest, AddInvalidObject)
TEST_F (RoomManipulationTest, RemoveObject)
TEST_F (RoomManipulationTest, RemoveInvalidIndex)
TEST_F (RoomManipulationTest, UpdateObject)
TEST_F (RoomManipulationTest, FindObjectAt)
TEST_F (RoomManipulationTest, ValidateObject)
TEST_F (RoomManipulationTest, MultipleOperations)
TEST_F (RoomManipulationTest, LayerOrganization)
Function Documentation
TEST_F() [1/15]
yaze::zelda3::test::TEST_F (RoomIntegrationTest , BasicLoadSaveRoundTrip)
Definition at line 59 of file room_integration_test.cc.
References yaze::zelda3::Room::GetTileObjects(), and yaze::zelda3::Room::SaveObjects().
TEST_F() [2/15]
yaze::zelda3::test::TEST_F (RoomIntegrationTest , MultiRoomLoadSaveRoundTrip)
Definition at line 102 of file room_integration_test.cc.
References yaze::zelda3::Room::GetTileObjects(), and yaze::zelda3::Room::SaveObjects().
TEST_F() [3/15]
yaze::zelda3::test::TEST_F (RoomIntegrationTest , LayerPreservation)
Definition at line 145 of file room_integration_test.cc.
References yaze::zelda3::Room::GetTileObjects(), and yaze::zelda3::Room::SaveObjects().
TEST_F() [4/15]
yaze::zelda3::test::TEST_F (RoomIntegrationTest , ObjectTypeDistribution)
Definition at line 187 of file room_integration_test.cc.
References yaze::zelda3::Room::GetTileObjects(), and yaze::zelda3::Room::SaveObjects().
TEST_F() [5/15]
yaze::zelda3::test::TEST_F (RoomIntegrationTest , BinaryDataExactMatch)
Definition at line 235 of file room_integration_test.cc.
References yaze::zelda3::Room::SaveObjects(), yaze::SnesToPc(), and yaze::zelda3::tile_address.
TEST_F() [6/15]
yaze::zelda3::test::TEST_F (RoomIntegrationTest , KnownRoomData)
Definition at line 294 of file room_integration_test.cc.
References yaze::zelda3::Room::GetTileObjects().
TEST_F() [7/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , AddObject)
Definition at line 27 of file room_manipulation_test.cc.
TEST_F() [8/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , AddInvalidObject)
Definition at line 40 of file room_manipulation_test.cc.
TEST_F() [9/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , RemoveObject)
Definition at line 49 of file room_manipulation_test.cc.
TEST_F() [10/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , RemoveInvalidIndex)
Definition at line 66 of file room_manipulation_test.cc.
TEST_F() [11/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , UpdateObject)
Definition at line 71 of file room_manipulation_test.cc.
TEST_F() [12/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , FindObjectAt)
Definition at line 85 of file room_manipulation_test.cc.
TEST_F() [13/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , ValidateObject)
Definition at line 100 of file room_manipulation_test.cc.
TEST_F() [14/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , MultipleOperations)
Definition at line 122 of file room_manipulation_test.cc.
TEST_F() [15/15]
yaze::zelda3::test::TEST_F (RoomManipulationTest , LayerOrganization)
Definition at line 147 of file room_manipulation_test.cc.