#ifndef YAZE_APP_EDITOR_AGENT_PANELS_MANIFEST_PANEL_H_
#include "app/editor/agent/ui/window/manifest_panel.h"
#define YAZE_APP_EDITOR_AGENT_PANELS_MANIFEST_PANEL_H_
#endif  // YAZE_APP_EDITOR_AGENT_PANELS_MANIFEST_PANEL_H_
