#ifndef YAZE_APP_EDITOR_AGENT_PANELS_SRAM_VIEWER_PANEL_H_
#include "app/editor/agent/ui/window/sram_viewer_panel.h"
#define YAZE_APP_EDITOR_AGENT_PANELS_SRAM_VIEWER_PANEL_H_
#endif  // YAZE_APP_EDITOR_AGENT_PANELS_SRAM_VIEWER_PANEL_H_
