yaze: yaze::cli::message::anonymous_namespace{message.cc} Namespace Reference
yaze::cli::message::anonymous_namespace{message.cc} Namespace Reference
Functions
absl::StatusOr< Rom > LoadRomFromFlag ()
std::vector< editor::MessageData > LoadMessages (Rom *rom)
Function Documentation
LoadRomFromFlag()
absl::StatusOr< Rom > yaze::cli::message::anonymous_namespace{message.cc}::LoadRomFromFlag ()
Definition at line 28 of file message.cc.
References yaze::Rom::LoadFromFile().
LoadMessages()
std::vector< editor::MessageData > yaze::cli::message::anonymous_namespace{message.cc}::LoadMessages (Rom * rom)
Definition at line 45 of file message.cc.
References yaze::Rom::data(), yaze::editor::kTextData, LoadMessages(), and yaze::editor::ReadAllTextData().
Referenced by LoadMessages().