yaze: yaze::editor::UserSettings Class Reference
yaze::editor::UserSettings Class Reference
Manages user preferences and settings persistence.
#include <user_settings.h>
Classes
struct Preferences
Public Member Functions
UserSettings ()
absl::Status Load ()
absl::Status Save ()
Preferences & prefs ()
const Preferences & prefs () const
Private Attributes
Preferences prefs_
std::string settings_file_path_
Detailed Description
Manages user preferences and settings persistence.
Definition at line 13 of file user_settings.h.
Constructor & Destructor Documentation
UserSettings()
yaze::editor::UserSettings::UserSettings ()
Definition at line 16 of file user_settings.cc.
References yaze::util::PlatformPaths::GetConfigDirectory(), LOG_WARN, and settings_file_path_.
Member Function Documentation
Load()
absl::Status yaze::editor::UserSettings::Load ()
Definition at line 26 of file user_settings.cc.
References yaze::editor::UserSettings::Preferences::ai_auto_learn, yaze::editor::UserSettings::Preferences::ai_max_tokens, yaze::editor::UserSettings::Preferences::ai_multimodal, yaze::editor::UserSettings::Preferences::ai_proactive, yaze::editor::UserSettings::Preferences::ai_provider, yaze::editor::UserSettings::Preferences::ai_temperature, yaze::editor::UserSettings::Preferences::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_interval, yaze::editor::UserSettings::Preferences::backup_before_save, yaze::editor::UserSettings::Preferences::backup_rom, yaze::editor::UserSettings::Preferences::cache_size_mb, yaze::editor::UserSettings::Preferences::default_editor, yaze::editor::UserSettings::Preferences::font_global_scale, yaze::editor::UserSettings::Preferences::gemini_api_key, yaze::editor::UserSettings::Preferences::last_project_path, yaze::editor::UserSettings::Preferences::last_rom_path, yaze::util::LoadFile(), yaze::editor::UserSettings::Preferences::log_ai_requests, yaze::editor::UserSettings::Preferences::log_file_path, yaze::editor::UserSettings::Preferences::log_gui_automation, yaze::editor::UserSettings::Preferences::log_level, yaze::editor::UserSettings::Preferences::log_proposals, yaze::editor::UserSettings::Preferences::log_rom_operations, yaze::editor::UserSettings::Preferences::log_to_file, yaze::editor::UserSettings::Preferences::ollama_url, prefs_, yaze::editor::UserSettings::Preferences::recent_files_limit, yaze::editor::UserSettings::Preferences::restore_last_session, yaze::editor::UserSettings::Preferences::save_new_auto, settings_file_path_, yaze::editor::UserSettings::Preferences::show_welcome_on_startup, yaze::editor::UserSettings::Preferences::target_fps, yaze::editor::UserSettings::Preferences::undo_history_size, and yaze::editor::UserSettings::Preferences::vsync.
Referenced by yaze::editor::EditorManager::Initialize().
Save()
absl::Status yaze::editor::UserSettings::Save ()
Definition at line 123 of file user_settings.cc.
References yaze::editor::UserSettings::Preferences::ai_auto_learn, yaze::editor::UserSettings::Preferences::ai_max_tokens, yaze::editor::UserSettings::Preferences::ai_multimodal, yaze::editor::UserSettings::Preferences::ai_proactive, yaze::editor::UserSettings::Preferences::ai_provider, yaze::editor::UserSettings::Preferences::ai_temperature, yaze::editor::UserSettings::Preferences::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_interval, yaze::editor::UserSettings::Preferences::backup_before_save, yaze::editor::UserSettings::Preferences::backup_rom, yaze::editor::UserSettings::Preferences::cache_size_mb, yaze::editor::UserSettings::Preferences::default_editor, yaze::editor::UserSettings::Preferences::font_global_scale, yaze::editor::UserSettings::Preferences::gemini_api_key, yaze::editor::UserSettings::Preferences::last_project_path, yaze::editor::UserSettings::Preferences::last_rom_path, yaze::editor::UserSettings::Preferences::log_ai_requests, yaze::editor::UserSettings::Preferences::log_file_path, yaze::editor::UserSettings::Preferences::log_gui_automation, yaze::editor::UserSettings::Preferences::log_level, yaze::editor::UserSettings::Preferences::log_proposals, yaze::editor::UserSettings::Preferences::log_rom_operations, yaze::editor::UserSettings::Preferences::log_to_file, yaze::editor::UserSettings::Preferences::ollama_url, prefs_, yaze::editor::UserSettings::Preferences::recent_files_limit, yaze::editor::UserSettings::Preferences::restore_last_session, yaze::editor::UserSettings::Preferences::save_new_auto, yaze::util::SaveFile(), settings_file_path_, yaze::editor::UserSettings::Preferences::show_welcome_on_startup, yaze::editor::UserSettings::Preferences::target_fps, yaze::editor::UserSettings::Preferences::undo_history_size, and yaze::editor::UserSettings::Preferences::vsync.
Referenced by yaze::editor::SettingsEditor::DrawAIAgentSettings(), yaze::editor::SettingsEditor::DrawEditorBehavior(), yaze::editor::SettingsEditor::DrawPerformanceSettings(), and yaze::editor::EditorManager::SaveUserSettings().
prefs() [1/2]
Preferences & yaze::editor::UserSettings::prefs () inline
Definition at line 63 of file user_settings.h.
References prefs_.
Referenced by yaze::editor::SettingsEditor::DrawAIAgentSettings(), yaze::editor::SettingsEditor::DrawEditorBehavior(), yaze::editor::SettingsEditor::DrawPerformanceSettings(), yaze::editor::EditorManager::LoadUserSettings(), yaze::editor::EditorManager::OpenProject(), yaze::editor::EditorManager::SaveProject(), yaze::editor::EditorManager::SaveRom(), yaze::editor::EditorManager::SaveRomAs(), yaze::editor::EditorManager::SetFontGlobalScale(), and yaze::editor::EditorManager::Update().
prefs() [2/2]
const Preferences & yaze::editor::UserSettings::prefs () const inline
Definition at line 64 of file user_settings.h.
References prefs_.
Member Data Documentation
prefs_
Preferences yaze::editor::UserSettings::prefs_ private
Definition at line 67 of file user_settings.h.
Referenced by Load(), prefs(), prefs(), and Save().
settings_file_path_
std::string yaze::editor::UserSettings::settings_file_path_ private
Definition at line 68 of file user_settings.h.
Referenced by Load(), Save(), and UserSettings().
The documentation for this class was generated from the following files:
src/app/editor/system/user_settings.h
src/app/editor/system/user_settings.cc