yaze: yaze::gui::canvas::CanvasContextMenu Class Reference
yaze::gui::canvas::CanvasContextMenu Class Reference
#include <canvas_context_menu.h>
Classes
struct ContextMenuItem
Public Types
enum class Command {
kNone , kResetView , kZoomToFit , kZoomIn ,
kZoomOut , kToggleGrid , kToggleHexLabels , kToggleCustomLabels ,
kToggleContextMenu , kToggleAutoResize , kToggleDraggable , kOpenAdvancedProperties ,
kOpenScalingControls , kSetGridStep , kSetScale
}
Public Member Functions
CanvasContextMenu ()=default
void Initialize (const std::string &canvas_id)
void SetUsageMode (CanvasUsage usage)
void AddMenuItem (const ContextMenuItem &item)
void AddMenuItem (const ContextMenuItem &item, CanvasUsage usage)
void ClearMenuItems ()
void Render (const std::string &context_id, const ImVec2 &mouse_pos, Rom *rom, const gfx::Bitmap *bitmap, const gfx::SnesPalette *palette, const std::function< void(Command, const canvas::CanvasConfig &)> &command_handler, CanvasConfig current_config)
bool ShouldShowContextMenu () const
void SetEnabled (bool enabled)
bool IsEnabled () const
CanvasUsage GetUsageMode () const
void SetCanvasState (const ImVec2 &canvas_size, const ImVec2 &content_size, float global_scale, float grid_step, bool enable_grid, bool enable_hex_labels, bool enable_custom_labels, bool enable_context_menu, bool is_draggable, bool auto_resize, const ImVec2 &scrolling)
Private Member Functions
void DrawROMPaletteSelector ()
void RenderMenuItem (const ContextMenuItem &item)
void RenderMenuSection (const std::string &title, const std::vector< ContextMenuItem > &items)
void RenderUsageSpecificMenu ()
void RenderViewControlsMenu (const std::function< void(Command, const CanvasConfig &)> &command_handler, CanvasConfig current_config)
void RenderCanvasPropertiesMenu (const std::function< void(Command, const CanvasConfig &)> &command_handler, CanvasConfig current_config)
void RenderBitmapOperationsMenu (gfx::Bitmap *bitmap)
void RenderPaletteOperationsMenu (Rom *rom, gfx::Bitmap *bitmap)
void RenderBppOperationsMenu (const gfx::Bitmap *bitmap)
void RenderPerformanceMenu ()
void RenderGridControlsMenu (const std::function< void(Command, const CanvasConfig &)> &command_handler, CanvasConfig current_config)
void RenderScalingControlsMenu (const std::function< void(Command, const CanvasConfig &)> &command_handler, CanvasConfig current_config)
void RenderMaterialIcon (const std::string &icon_name, const ImVec4 &color=ImVec4(1, 1, 1, 1))
std::string GetUsageModeName (CanvasUsage usage) const
ImVec4 GetUsageModeColor (CanvasUsage usage) const
void CreateDefaultMenuItems ()
ContextMenuItem CreateViewMenuItem (const std::string &label, const std::string &icon, std::function< void()> callback)
ContextMenuItem CreateBitmapMenuItem (const std::string &label, const std::string &icon, std::function< void()> callback)
ContextMenuItem CreatePaletteMenuItem (const std::string &label, const std::string &icon, std::function< void()> callback)
ContextMenuItem CreateBppMenuItem (const std::string &label, const std::string &icon, std::function< void()> callback)
ContextMenuItem CreatePerformanceMenuItem (const std::string &label, const std::string &icon, std::function< void()> callback)
Private Attributes
std::string canvas_id_
bool enabled_ = true
CanvasUsage current_usage_ = CanvasUsage::kTilePainting
ImVec2 canvas_size_
ImVec2 content_size_
float global_scale_ = 1.0f
float grid_step_ = 32.0f
bool enable_grid_ = true
bool enable_hex_labels_ = false
bool enable_custom_labels_ = false
bool enable_context_menu_ = true
bool is_draggable_ = false
bool auto_resize_ = false
ImVec2 scrolling_
std::unique_ptr< PaletteWidget > palette_editor_
uint64_t edit_palette_group_name_index_ = 0
uint64_t edit_palette_index_ = 0
uint64_t edit_palette_sub_index_ = 0
bool refresh_graphics_ = false
std::unordered_map< CanvasUsage, std::vector< ContextMenuItem > > usage_specific_items_
std::vector< ContextMenuItem > global_items_
Detailed Description
Definition at line 24 of file canvas_context_menu.h.
Member Enumeration Documentation
Command
enum class yaze::gui::canvas::CanvasContextMenu::Command strong
Enumerator
kNone
kResetView
kZoomToFit
kZoomIn
kZoomOut
kToggleGrid
kToggleHexLabels
kToggleCustomLabels
kToggleContextMenu
kToggleAutoResize
kToggleDraggable
kOpenAdvancedProperties
kOpenScalingControls
kSetGridStep
kSetScale
Definition at line 26 of file canvas_context_menu.h.
Constructor & Destructor Documentation
CanvasContextMenu()
yaze::gui::canvas::CanvasContextMenu::CanvasContextMenu () default
Member Function Documentation
Initialize()
void yaze::gui::canvas::CanvasContextMenu::Initialize (const std::string & canvas_id)
Definition at line 31 of file canvas_context_menu.cc.
References auto_resize_, canvas_id_, canvas_size_, content_size_, CreateDefaultMenuItems(), current_usage_, enable_context_menu_, enable_custom_labels_, enable_grid_, enable_hex_labels_, enabled_, global_scale_, grid_step_, is_draggable_, yaze::gui::canvas::kTilePainting, palette_editor_, and scrolling_.
SetUsageMode()
void yaze::gui::canvas::CanvasContextMenu::SetUsageMode (CanvasUsage usage)
Definition at line 54 of file canvas_context_menu.cc.
References current_usage_.
AddMenuItem() [1/2]
void yaze::gui::canvas::CanvasContextMenu::AddMenuItem (const ContextMenuItem & item)
Definition at line 58 of file canvas_context_menu.cc.
References global_items_.
AddMenuItem() [2/2]
void yaze::gui::canvas::CanvasContextMenu::AddMenuItem (const ContextMenuItem & item, CanvasUsage usage)
Definition at line 62 of file canvas_context_menu.cc.
References usage_specific_items_.
ClearMenuItems()
void yaze::gui::canvas::CanvasContextMenu::ClearMenuItems ()
Definition at line 66 of file canvas_context_menu.cc.
References global_items_, and usage_specific_items_.
Render()
void yaze::gui::canvas::CanvasContextMenu::Render (const std::string & context_id, const ImVec2 & mouse_pos, Rom * rom, const gfx::Bitmap * bitmap, const gfx::SnesPalette * palette, const std::function< void(Command, const canvas::CanvasConfig &)> & command_handler, CanvasConfig current_config)
Definition at line 71 of file canvas_context_menu.cc.
References current_usage_, enable_context_menu_, enabled_, global_items_, RenderBitmapOperationsMenu(), RenderBppOperationsMenu(), RenderCanvasPropertiesMenu(), RenderGridControlsMenu(), RenderMenuSection(), RenderPaletteOperationsMenu(), RenderPerformanceMenu(), RenderScalingControlsMenu(), RenderUsageSpecificMenu(), RenderViewControlsMenu(), and usage_specific_items_.
ShouldShowContextMenu()
bool yaze::gui::canvas::CanvasContextMenu::ShouldShowContextMenu () const
Definition at line 136 of file canvas_context_menu.cc.
References enable_context_menu_, and enabled_.
SetEnabled()
void yaze::gui::canvas::CanvasContextMenu::SetEnabled (bool enabled) inline
Definition at line 78 of file canvas_context_menu.h.
References enabled_.
IsEnabled()
bool yaze::gui::canvas::CanvasContextMenu::IsEnabled () const inline
Definition at line 79 of file canvas_context_menu.h.
References enabled_.
GetUsageMode()
CanvasUsage yaze::gui::canvas::CanvasContextMenu::GetUsageMode () const inline
Definition at line 80 of file canvas_context_menu.h.
References current_usage_.
SetCanvasState()
void yaze::gui::canvas::CanvasContextMenu::SetCanvasState (const ImVec2 & canvas_size, const ImVec2 & content_size, float global_scale, float grid_step, bool enable_grid, bool enable_hex_labels, bool enable_custom_labels, bool enable_context_menu, bool is_draggable, bool auto_resize, const ImVec2 & scrolling)
Definition at line 140 of file canvas_context_menu.cc.
References auto_resize_, canvas_size_, content_size_, enable_context_menu_, enable_custom_labels_, enable_grid_, enable_hex_labels_, global_scale_, grid_step_, is_draggable_, and scrolling_.
DrawROMPaletteSelector()
void yaze::gui::canvas::CanvasContextMenu::DrawROMPaletteSelector () private
Definition at line 356 of file canvas_context_menu.cc.
References palette_editor_.
RenderMenuItem()
void yaze::gui::canvas::CanvasContextMenu::RenderMenuItem (const ContextMenuItem & item) private
Definition at line 164 of file canvas_context_menu.cc.
References yaze::gui::canvas::CanvasContextMenu::ContextMenuItem::callback, yaze::gui::canvas::CanvasContextMenu::ContextMenuItem::enabled_condition, yaze::gui::canvas::CanvasContextMenu::ContextMenuItem::label, RenderMenuItem(), yaze::gui::canvas::CanvasContextMenu::ContextMenuItem::separator_after, yaze::gui::canvas::CanvasContextMenu::ContextMenuItem::shortcut, yaze::gui::canvas::CanvasContextMenu::ContextMenuItem::subitems, and yaze::gui::canvas::CanvasContextMenu::ContextMenuItem::visible_condition.
Referenced by RenderMenuItem(), RenderMenuSection(), and RenderUsageSpecificMenu().
RenderMenuSection()
void yaze::gui::canvas::CanvasContextMenu::RenderMenuSection (const std::string & title, const std::vector< ContextMenuItem > & items) private
Definition at line 198 of file canvas_context_menu.cc.
References RenderMenuItem().
Referenced by Render().
RenderUsageSpecificMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderUsageSpecificMenu () private
Definition at line 208 of file canvas_context_menu.cc.
References current_usage_, GetUsageModeColor(), GetUsageModeName(), ICON_MD_COLOR_LENS, RenderMenuItem(), and usage_specific_items_.
Referenced by Render().
RenderViewControlsMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderViewControlsMenu (const std::function< void(Command, const CanvasConfig &)> & command_handler, CanvasConfig current_config) private
Definition at line 225 of file canvas_context_menu.cc.
References yaze::gui::canvas::CanvasConfig::enable_custom_labels, enable_custom_labels_, yaze::gui::canvas::CanvasConfig::enable_grid, enable_grid_, yaze::gui::canvas::CanvasConfig::enable_hex_labels, enable_hex_labels_, yaze::gui::canvas::CanvasConfig::global_scale, kResetView, kSetScale, kToggleCustomLabels, kToggleGrid, kToggleHexLabels, and kZoomToFit.
Referenced by Render().
RenderCanvasPropertiesMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu (const std::function< void(Command, const CanvasConfig &)> & command_handler, CanvasConfig current_config) private
Definition at line 265 of file canvas_context_menu.cc.
References yaze::gui::canvas::CanvasConfig::auto_resize, auto_resize_, yaze::gui::canvas::CanvasConfig::canvas_size, canvas_size_, yaze::gui::canvas::CanvasConfig::content_size, content_size_, yaze::gui::canvas::CanvasConfig::enable_context_menu, enable_context_menu_, yaze::gui::canvas::CanvasConfig::enable_custom_labels, enable_custom_labels_, yaze::gui::canvas::CanvasConfig::enable_grid, enable_grid_, yaze::gui::canvas::CanvasConfig::enable_hex_labels, enable_hex_labels_, global_scale_, yaze::gui::canvas::CanvasConfig::grid_step, grid_step_, ICON_MD_SETTINGS, yaze::gui::canvas::CanvasConfig::is_draggable, is_draggable_, kOpenAdvancedProperties, yaze::gui::canvas::CanvasConfig::scrolling, and scrolling_.
Referenced by Render().
RenderBitmapOperationsMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderBitmapOperationsMenu (gfx::Bitmap * bitmap) private
Definition at line 294 of file canvas_context_menu.cc.
References yaze::core::Renderer::Get(), yaze::gfx::Bitmap::height(), ICON_MD_IMAGE, yaze::gfx::k4bpp, yaze::gfx::k8bpp, yaze::gfx::kIndexed, yaze::gfx::Bitmap::Reformat(), yaze::gfx::Bitmap::surface(), yaze::core::Renderer::UpdateBitmap(), and yaze::gfx::Bitmap::width().
Referenced by Render().
RenderPaletteOperationsMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderPaletteOperationsMenu (Rom * rom, gfx::Bitmap * bitmap) private
Definition at line 322 of file canvas_context_menu.cc.
References yaze::gui::DisplayEditablePalette(), edit_palette_group_name_index_, edit_palette_index_, ICON_MD_PALETTE, yaze::gfx::Bitmap::mutable_palette(), and palette_editor_.
Referenced by Render().
RenderBppOperationsMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderBppOperationsMenu (const gfx::Bitmap * bitmap) private
Definition at line 362 of file canvas_context_menu.cc.
References ICON_MD_SWAP_HORIZ.
Referenced by Render().
RenderPerformanceMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderPerformanceMenu () private
Definition at line 378 of file canvas_context_menu.cc.
References yaze::gfx::PerformanceDashboard::Get(), yaze::gfx::PerformanceProfiler::Get(), ICON_MD_TRENDING_UP, and yaze::gfx::PerformanceDashboard::SetVisible().
Referenced by Render().
RenderGridControlsMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderGridControlsMenu (const std::function< void(Command, const CanvasConfig &)> & command_handler, CanvasConfig current_config) private
Definition at line 398 of file canvas_context_menu.cc.
References yaze::gui::canvas::CanvasConfig::grid_step, grid_step_, ICON_MD_GRID_ON, and kSetGridStep.
Referenced by Render().
RenderScalingControlsMenu()
void yaze::gui::canvas::CanvasContextMenu::RenderScalingControlsMenu (const std::function< void(Command, const CanvasConfig &)> & command_handler, CanvasConfig current_config) private
Definition at line 421 of file canvas_context_menu.cc.
References yaze::gui::canvas::CanvasConfig::global_scale, ICON_MD_ZOOM_IN, and kSetScale.
Referenced by Render().
RenderMaterialIcon()
void yaze::gui::canvas::CanvasContextMenu::RenderMaterialIcon (const std::string & icon_name, const ImVec4 & color = ImVec4(1, 1, 1, 1)) private
Definition at line 443 of file canvas_context_menu.cc.
References ICON_MD_DRAG_INDICATOR, ICON_MD_EDIT, ICON_MD_FIT_SCREEN, ICON_MD_FUNCTIONS, ICON_MD_GRID_ON, ICON_MD_IMAGE, ICON_MD_INFO, ICON_MD_LABEL, ICON_MD_MENU, ICON_MD_PALETTE, ICON_MD_REFRESH, ICON_MD_SCHEDULE, ICON_MD_SETTINGS, ICON_MD_SPEED, ICON_MD_SWAP_HORIZ, ICON_MD_TIMER, ICON_MD_TRENDING_UP, ICON_MD_VISIBILITY, and ICON_MD_ZOOM_IN.
GetUsageModeName()
std::string yaze::gui::canvas::CanvasContextMenu::GetUsageModeName (CanvasUsage usage) const private
Definition at line 460 of file canvas_context_menu.cc.
References yaze::gui::canvas::kBitmapEditing, yaze::gui::canvas::kBppConversion, yaze::gui::canvas::kColorPainting, yaze::gui::canvas::kPaletteEditing, yaze::gui::canvas::kPerformanceMode, yaze::gui::canvas::kSelectRectangle, yaze::gui::canvas::kTilePainting, yaze::gui::canvas::kTileSelecting, and yaze::gui::canvas::kUnknown.
Referenced by RenderUsageSpecificMenu().
GetUsageModeColor()
ImVec4 yaze::gui::canvas::CanvasContextMenu::GetUsageModeColor (CanvasUsage usage) const private
Definition at line 475 of file canvas_context_menu.cc.
References yaze::gui::canvas::kBitmapEditing, yaze::gui::canvas::kBppConversion, yaze::gui::canvas::kColorPainting, yaze::gui::canvas::kPaletteEditing, yaze::gui::canvas::kPerformanceMode, yaze::gui::canvas::kSelectRectangle, yaze::gui::canvas::kTilePainting, yaze::gui::canvas::kTileSelecting, and yaze::gui::canvas::kUnknown.
Referenced by RenderUsageSpecificMenu().
CreateDefaultMenuItems()
void yaze::gui::canvas::CanvasContextMenu::CreateDefaultMenuItems () private
Definition at line 490 of file canvas_context_menu.cc.
References yaze::gui::canvas::kBitmapEditing, yaze::gui::canvas::kBppConversion, yaze::gui::canvas::kColorPainting, yaze::gui::canvas::kPaletteEditing, yaze::gui::canvas::kPerformanceMode, yaze::gui::canvas::kSelectRectangle, yaze::gui::canvas::kTilePainting, yaze::gui::canvas::kTileSelecting, and usage_specific_items_.
Referenced by Initialize().
CreateViewMenuItem()
canvas::CanvasContextMenu::ContextMenuItem yaze::gui::canvas::CanvasContextMenu::CreateViewMenuItem (const std::string & label, const std::string & icon, std::function< void()> callback) private
Definition at line 542 of file canvas_context_menu.cc.
CreateBitmapMenuItem()
canvas::CanvasContextMenu::ContextMenuItem yaze::gui::canvas::CanvasContextMenu::CreateBitmapMenuItem (const std::string & label, const std::string & icon, std::function< void()> callback) private
Definition at line 548 of file canvas_context_menu.cc.
CreatePaletteMenuItem()
canvas::CanvasContextMenu::ContextMenuItem yaze::gui::canvas::CanvasContextMenu::CreatePaletteMenuItem (const std::string & label, const std::string & icon, std::function< void()> callback) private
Definition at line 554 of file canvas_context_menu.cc.
CreateBppMenuItem()
canvas::CanvasContextMenu::ContextMenuItem yaze::gui::canvas::CanvasContextMenu::CreateBppMenuItem (const std::string & label, const std::string & icon, std::function< void()> callback) private
Definition at line 560 of file canvas_context_menu.cc.
CreatePerformanceMenuItem()
canvas::CanvasContextMenu::ContextMenuItem yaze::gui::canvas::CanvasContextMenu::CreatePerformanceMenuItem (const std::string & label, const std::string & icon, std::function< void()> callback) private
Definition at line 566 of file canvas_context_menu.cc.
Member Data Documentation
canvas_id_
std::string yaze::gui::canvas::CanvasContextMenu::canvas_id_ private
Definition at line 95 of file canvas_context_menu.h.
Referenced by Initialize().
enabled_
bool yaze::gui::canvas::CanvasContextMenu::enabled_ = true private
Definition at line 96 of file canvas_context_menu.h.
Referenced by Initialize(), IsEnabled(), Render(), SetEnabled(), and ShouldShowContextMenu().
current_usage_
CanvasUsage yaze::gui::canvas::CanvasContextMenu::current_usage_ = CanvasUsage::kTilePainting private
Definition at line 97 of file canvas_context_menu.h.
Referenced by GetUsageMode(), Initialize(), Render(), RenderUsageSpecificMenu(), and SetUsageMode().
canvas_size_
ImVec2 yaze::gui::canvas::CanvasContextMenu::canvas_size_ private
Definition at line 99 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), and SetCanvasState().
content_size_
ImVec2 yaze::gui::canvas::CanvasContextMenu::content_size_ private
Definition at line 100 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), and SetCanvasState().
global_scale_
float yaze::gui::canvas::CanvasContextMenu::global_scale_ = 1.0f private
Definition at line 101 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), and SetCanvasState().
grid_step_
float yaze::gui::canvas::CanvasContextMenu::grid_step_ = 32.0f private
Definition at line 102 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), RenderGridControlsMenu(), and SetCanvasState().
enable_grid_
bool yaze::gui::canvas::CanvasContextMenu::enable_grid_ = true private
Definition at line 103 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), RenderViewControlsMenu(), and SetCanvasState().
enable_hex_labels_
bool yaze::gui::canvas::CanvasContextMenu::enable_hex_labels_ = false private
Definition at line 104 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), RenderViewControlsMenu(), and SetCanvasState().
enable_custom_labels_
bool yaze::gui::canvas::CanvasContextMenu::enable_custom_labels_ = false private
Definition at line 105 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), RenderViewControlsMenu(), and SetCanvasState().
enable_context_menu_
bool yaze::gui::canvas::CanvasContextMenu::enable_context_menu_ = true private
Definition at line 106 of file canvas_context_menu.h.
Referenced by Initialize(), Render(), RenderCanvasPropertiesMenu(), SetCanvasState(), and ShouldShowContextMenu().
is_draggable_
bool yaze::gui::canvas::CanvasContextMenu::is_draggable_ = false private
Definition at line 107 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), and SetCanvasState().
auto_resize_
bool yaze::gui::canvas::CanvasContextMenu::auto_resize_ = false private
Definition at line 108 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), and SetCanvasState().
scrolling_
ImVec2 yaze::gui::canvas::CanvasContextMenu::scrolling_ private
Definition at line 109 of file canvas_context_menu.h.
Referenced by Initialize(), RenderCanvasPropertiesMenu(), and SetCanvasState().
palette_editor_
std::unique_ptr<PaletteWidget> yaze::gui::canvas::CanvasContextMenu::palette_editor_ private
Definition at line 111 of file canvas_context_menu.h.
Referenced by DrawROMPaletteSelector(), Initialize(), and RenderPaletteOperationsMenu().
edit_palette_group_name_index_
uint64_t yaze::gui::canvas::CanvasContextMenu::edit_palette_group_name_index_ = 0 private
Definition at line 112 of file canvas_context_menu.h.
Referenced by RenderPaletteOperationsMenu().
edit_palette_index_
uint64_t yaze::gui::canvas::CanvasContextMenu::edit_palette_index_ = 0 private
Definition at line 113 of file canvas_context_menu.h.
Referenced by RenderPaletteOperationsMenu().
edit_palette_sub_index_
uint64_t yaze::gui::canvas::CanvasContextMenu::edit_palette_sub_index_ = 0 private
Definition at line 114 of file canvas_context_menu.h.
refresh_graphics_
bool yaze::gui::canvas::CanvasContextMenu::refresh_graphics_ = false private
Definition at line 115 of file canvas_context_menu.h.
usage_specific_items_
std::unordered_map<CanvasUsage, std::vector<ContextMenuItem> > yaze::gui::canvas::CanvasContextMenu::usage_specific_items_ private
Definition at line 119 of file canvas_context_menu.h.
Referenced by AddMenuItem(), ClearMenuItems(), CreateDefaultMenuItems(), Render(), and RenderUsageSpecificMenu().
global_items_
std::vector<ContextMenuItem> yaze::gui::canvas::CanvasContextMenu::global_items_ private
Definition at line 120 of file canvas_context_menu.h.
Referenced by AddMenuItem(), ClearMenuItems(), and Render().
The documentation for this class was generated from the following files:
src/app/gui/canvas/canvas_context_menu.h
src/app/gui/canvas/canvas_context_menu.cc