yaze: yaze::cli::PolicyEvaluator Class Reference
yaze::cli::PolicyEvaluator Class Reference
#include <policy_evaluator.h>
Classes
struct PolicyConfig
Public Member Functions
absl::Status LoadPolicies (absl::string_view policy_dir=".yaze/policies")
absl::StatusOr< PolicyResult > EvaluateProposal (absl::string_view proposal_id)
absl::Status ReloadPolicies ()
bool IsEnabled () const
std::string GetPolicyPath () const
std::string GetStatusString () const
Static Public Member Functions
static PolicyEvaluator & GetInstance ()
Private Member Functions
PolicyEvaluator ()=default
~PolicyEvaluator ()=default
PolicyEvaluator (const PolicyEvaluator &)=delete
PolicyEvaluator & operator= (const PolicyEvaluator &)=delete
absl::Status ParsePolicyFile (absl::string_view yaml_content)
void EvaluateTestRequirements (absl::string_view proposal_id, PolicyResult *result)
void EvaluateChangeConstraints (absl::string_view proposal_id, PolicyResult *result)
void EvaluateForbiddenRanges (absl::string_view proposal_id, PolicyResult *result)
void EvaluateReviewRequirements (absl::string_view proposal_id, PolicyResult *result)
void CategorizeViolations (PolicyResult *result)
Private Attributes
bool enabled_ = false
std::string policy_path_
std::string policy_dir_
std::unique_ptr< PolicyConfig > config_
Detailed Description
Definition at line 49 of file policy_evaluator.h.
Constructor & Destructor Documentation
PolicyEvaluator() [1/2]
yaze::cli::PolicyEvaluator::PolicyEvaluator () private default
~PolicyEvaluator()
yaze::cli::PolicyEvaluator::~PolicyEvaluator () private default
PolicyEvaluator() [2/2]
yaze::cli::PolicyEvaluator::PolicyEvaluator (const PolicyEvaluator &) private delete
Member Function Documentation
GetInstance()
PolicyEvaluator & yaze::cli::PolicyEvaluator::GetInstance () static
Definition at line 69 of file policy_evaluator.cc.
Referenced by yaze::editor::ProposalDrawer::DrawActionButtons(), and yaze::editor::ProposalDrawer::DrawPolicyStatus().
LoadPolicies()
absl::Status yaze::cli::PolicyEvaluator::LoadPolicies (absl::string_view policy_dir = ".yaze/policies")
Definition at line 74 of file policy_evaluator.cc.
References enabled_, ParsePolicyFile(), policy_dir_, and policy_path_.
Referenced by ReloadPolicies().
EvaluateProposal()
absl::StatusOr< PolicyResult > yaze::cli::PolicyEvaluator::EvaluateProposal (absl::string_view proposal_id)
Definition at line 205 of file policy_evaluator.cc.
References CategorizeViolations(), config_, enabled_, EvaluateChangeConstraints(), EvaluateForbiddenRanges(), EvaluateReviewRequirements(), EvaluateTestRequirements(), yaze::cli::PolicyResult::has_critical_violations(), and yaze::cli::PolicyResult::passed.
ReloadPolicies()
absl::Status yaze::cli::PolicyEvaluator::ReloadPolicies ()
Definition at line 94 of file policy_evaluator.cc.
References LoadPolicies(), and policy_dir_.
IsEnabled()
bool yaze::cli::PolicyEvaluator::IsEnabled () const inline
Definition at line 65 of file policy_evaluator.h.
References enabled_.
GetPolicyPath()
std::string yaze::cli::PolicyEvaluator::GetPolicyPath () const inline
Definition at line 68 of file policy_evaluator.h.
References policy_path_.
GetStatusString()
std::string yaze::cli::PolicyEvaluator::GetStatusString () const
Definition at line 102 of file policy_evaluator.cc.
References config_, enabled_, and policy_path_.
operator=()
PolicyEvaluator & yaze::cli::PolicyEvaluator::operator= (const PolicyEvaluator &) private delete
ParsePolicyFile()
absl::Status yaze::cli::PolicyEvaluator::ParsePolicyFile (absl::string_view yaml_content) private
Definition at line 119 of file policy_evaluator.cc.
References config_, enabled_, yaze::cli::PolicyEvaluator::PolicyConfig::ChangeConstraint::max_bytes_changed, yaze::cli::PolicyEvaluator::PolicyConfig::ChangeConstraint::max_commands_executed, yaze::cli::PolicyEvaluator::PolicyConfig::TestRequirement::message, yaze::cli::PolicyEvaluator::PolicyConfig::ChangeConstraint::message, yaze::cli::PolicyEvaluator::PolicyConfig::ForbiddenRange::message, yaze::cli::PolicyEvaluator::PolicyConfig::ReviewRequirement::message, yaze::cli::PolicyEvaluator::PolicyConfig::TestRequirement::name, yaze::cli::PolicyEvaluator::PolicyConfig::ChangeConstraint::name, yaze::cli::PolicyEvaluator::PolicyConfig::ForbiddenRange::name, yaze::cli::PolicyEvaluator::PolicyConfig::ReviewRequirement::name, yaze::cli::PolicyEvaluator::PolicyConfig::ForbiddenRange::ranges, and yaze::cli::PolicyEvaluator::PolicyConfig::TestRequirement::test_suites.
Referenced by LoadPolicies().
EvaluateTestRequirements()
void yaze::cli::PolicyEvaluator::EvaluateTestRequirements (absl::string_view proposal_id, PolicyResult * result) private
Todo:
Implement test requirement evaluation
Definition at line 230 of file policy_evaluator.cc.
References config_.
Referenced by EvaluateProposal().
EvaluateChangeConstraints()
void yaze::cli::PolicyEvaluator::EvaluateChangeConstraints (absl::string_view proposal_id, PolicyResult * result) private
Definition at line 243 of file policy_evaluator.cc.
References config_, yaze::cli::PolicyViolation::details, yaze::cli::ProposalRegistry::Instance(), yaze::cli::PolicyViolation::message, yaze::cli::PolicyViolation::policy_name, yaze::cli::PolicyViolation::severity, and yaze::cli::PolicyResult::violations.
Referenced by EvaluateProposal().
EvaluateForbiddenRanges()
void yaze::cli::PolicyEvaluator::EvaluateForbiddenRanges (absl::string_view proposal_id, PolicyResult * result) private
Todo:
Implement forbidden range checking
Definition at line 287 of file policy_evaluator.cc.
References config_.
Referenced by EvaluateProposal().
EvaluateReviewRequirements()
void yaze::cli::PolicyEvaluator::EvaluateReviewRequirements (absl::string_view proposal_id, PolicyResult * result) private
Definition at line 299 of file policy_evaluator.cc.
References config_, yaze::cli::PolicyViolation::details, yaze::cli::ProposalRegistry::Instance(), yaze::cli::PolicyViolation::message, yaze::cli::PolicyViolation::policy_name, yaze::cli::PolicyViolation::severity, and yaze::cli::PolicyResult::violations.
Referenced by EvaluateProposal().
CategorizeViolations()
void yaze::cli::PolicyEvaluator::CategorizeViolations (PolicyResult * result) private
Definition at line 359 of file policy_evaluator.cc.
References yaze::cli::PolicyResult::critical_violations, yaze::cli::PolicyResult::info, yaze::cli::kCritical, yaze::cli::kInfo, yaze::cli::kWarning, yaze::cli::PolicyResult::violations, and yaze::cli::PolicyResult::warnings.
Referenced by EvaluateProposal().
Member Data Documentation
enabled_
bool yaze::cli::PolicyEvaluator::enabled_ = false private
Definition at line 97 of file policy_evaluator.h.
Referenced by EvaluateProposal(), GetStatusString(), IsEnabled(), LoadPolicies(), and ParsePolicyFile().
policy_path_
std::string yaze::cli::PolicyEvaluator::policy_path_ private
Definition at line 98 of file policy_evaluator.h.
Referenced by GetPolicyPath(), GetStatusString(), and LoadPolicies().
policy_dir_
std::string yaze::cli::PolicyEvaluator::policy_dir_ private
Definition at line 99 of file policy_evaluator.h.
Referenced by LoadPolicies(), and ReloadPolicies().
config_
std::unique_ptr<PolicyConfig> yaze::cli::PolicyEvaluator::config_ private
Definition at line 103 of file policy_evaluator.h.
Referenced by EvaluateChangeConstraints(), EvaluateForbiddenRanges(), EvaluateProposal(), EvaluateReviewRequirements(), EvaluateTestRequirements(), GetStatusString(), and ParsePolicyFile().
The documentation for this class was generated from the following files:
src/cli/service/policy_evaluator.h
src/cli/service/policy_evaluator.cc