yaze: yaze::project::anonymous_namespace{project.cc} Namespace Reference
yaze::project::anonymous_namespace{project.cc} Namespace Reference
Functions
std::pair< std::string, std::string > ParseKeyValue (const std::string &line)
bool ParseBool (const std::string &value)
float ParseFloat (const std::string &value)
std::vector< std::string > ParseStringList (const std::string &value)
Function Documentation
ParseKeyValue()
std::pair< std::string, std::string > yaze::project::anonymous_namespace{project.cc}::ParseKeyValue (const std::string & line)
Definition at line 30 of file project.cc.
ParseBool()
bool yaze::project::anonymous_namespace{project.cc}::ParseBool (const std::string & value)
Definition at line 46 of file project.cc.
References ParseBool().
Referenced by ParseBool().
ParseFloat()
float yaze::project::anonymous_namespace{project.cc}::ParseFloat (const std::string & value)
Definition at line 50 of file project.cc.
References ParseFloat().
Referenced by ParseFloat().
ParseStringList()
std::vector< std::string > yaze::project::anonymous_namespace{project.cc}::ParseStringList (const std::string & value)
Definition at line 58 of file project.cc.
References ParseStringList().
Referenced by ParseStringList().