yaze: yaze::cli::agent::anonymous_namespace{enhanced_tui.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{enhanced_tui.cc} Namespace Reference
Functions
std::pair< int, int > GetTerminalSize ()
int ReadChar ()
bool IsSpecialKey (int key)
Variables
constexpr const char * RESET = "\033[0m"
constexpr const char * BOLD = "\033[1m"
constexpr const char * DIM = "\033[2m"
constexpr const char * ITALIC = "\033[3m"
constexpr const char * UNDERLINE = "\033[4m"
constexpr const char * FG_BLACK = "\033[30m"
constexpr const char * FG_RED = "\033[31m"
constexpr const char * FG_GREEN = "\033[32m"
constexpr const char * FG_YELLOW = "\033[33m"
constexpr const char * FG_BLUE = "\033[34m"
constexpr const char * FG_MAGENTA = "\033[35m"
constexpr const char * FG_CYAN = "\033[36m"
constexpr const char * FG_WHITE = "\033[37m"
constexpr const char * FG_BRIGHT_BLACK = "\033[90m"
constexpr const char * FG_BRIGHT_RED = "\033[91m"
constexpr const char * FG_BRIGHT_GREEN = "\033[92m"
constexpr const char * FG_BRIGHT_YELLOW = "\033[93m"
constexpr const char * FG_BRIGHT_BLUE = "\033[94m"
constexpr const char * FG_BRIGHT_MAGENTA = "\033[95m"
constexpr const char * FG_BRIGHT_CYAN = "\033[96m"
constexpr const char * FG_BRIGHT_WHITE = "\033[97m"
constexpr const char * BG_BLACK = "\033[40m"
constexpr const char * BG_RED = "\033[41m"
constexpr const char * BG_GREEN = "\033[42m"
constexpr const char * BG_YELLOW = "\033[43m"
constexpr const char * BG_BLUE = "\033[44m"
constexpr const char * BG_MAGENTA = "\033[45m"
constexpr const char * BG_CYAN = "\033[46m"
constexpr const char * BG_WHITE = "\033[47m"
constexpr const char * BG_BRIGHT_BLACK = "\033[100m"
constexpr const char * BG_BRIGHT_RED = "\033[101m"
constexpr const char * BG_BRIGHT_GREEN = "\033[102m"
constexpr const char * BG_BRIGHT_YELLOW = "\033[103m"
constexpr const char * BG_BRIGHT_BLUE = "\033[104m"
constexpr const char * BG_BRIGHT_MAGENTA = "\033[105m"
constexpr const char * BG_BRIGHT_CYAN = "\033[106m"
constexpr const char * BG_BRIGHT_WHITE = "\033[107m"
constexpr int KEY_ESC = 27
constexpr int KEY_ENTER = 10
constexpr int KEY_BACKSPACE = 127
constexpr int KEY_TAB = 9
constexpr int KEY_UP = 1000
constexpr int KEY_DOWN = 1001
constexpr int KEY_LEFT = 1002
constexpr int KEY_RIGHT = 1003
constexpr int KEY_HOME = 1004
constexpr int KEY_END = 1005
constexpr int KEY_DELETE = 1006
constexpr int KEY_PAGE_UP = 1007
constexpr int KEY_PAGE_DOWN = 1008
constexpr const char * CLEAR_SCREEN = "\033[2J"
constexpr const char * CLEAR_LINE = "\033[2K"
constexpr const char * CURSOR_HOME = "\033[H"
constexpr const char * SAVE_CURSOR = "\033[s"
constexpr const char * RESTORE_CURSOR = "\033[u"
constexpr const char * HIDE_CURSOR = "\033[?25l"
constexpr const char * SHOW_CURSOR = "\033[?25h"
Function Documentation
GetTerminalSize()
std::pair< int, int > yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::GetTerminalSize ()
Definition at line 96 of file enhanced_tui.cc.
References GetTerminalSize().
Referenced by GetTerminalSize().
ReadChar()
int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::ReadChar ()
Definition at line 110 of file enhanced_tui.cc.
References ReadChar().
Referenced by ReadChar().
IsSpecialKey()
bool yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::IsSpecialKey (int key)
Definition at line 119 of file enhanced_tui.cc.
References IsSpecialKey().
Referenced by IsSpecialKey().
Variable Documentation
RESET
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::RESET = "\033[0m" constexpr
Definition at line 29 of file enhanced_tui.cc.
BOLD
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BOLD = "\033[1m" constexpr
Definition at line 30 of file enhanced_tui.cc.
DIM
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::DIM = "\033[2m" constexpr
Definition at line 31 of file enhanced_tui.cc.
ITALIC
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::ITALIC = "\033[3m" constexpr
Definition at line 32 of file enhanced_tui.cc.
UNDERLINE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::UNDERLINE = "\033[4m" constexpr
Definition at line 33 of file enhanced_tui.cc.
FG_BLACK
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BLACK = "\033[30m" constexpr
Definition at line 36 of file enhanced_tui.cc.
FG_RED
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_RED = "\033[31m" constexpr
Definition at line 37 of file enhanced_tui.cc.
FG_GREEN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_GREEN = "\033[32m" constexpr
Definition at line 38 of file enhanced_tui.cc.
FG_YELLOW
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_YELLOW = "\033[33m" constexpr
Definition at line 39 of file enhanced_tui.cc.
FG_BLUE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BLUE = "\033[34m" constexpr
Definition at line 40 of file enhanced_tui.cc.
FG_MAGENTA
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_MAGENTA = "\033[35m" constexpr
Definition at line 41 of file enhanced_tui.cc.
FG_CYAN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_CYAN = "\033[36m" constexpr
Definition at line 42 of file enhanced_tui.cc.
FG_WHITE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_WHITE = "\033[37m" constexpr
Definition at line 43 of file enhanced_tui.cc.
FG_BRIGHT_BLACK
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_BLACK = "\033[90m" constexpr
Definition at line 44 of file enhanced_tui.cc.
FG_BRIGHT_RED
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_RED = "\033[91m" constexpr
Definition at line 45 of file enhanced_tui.cc.
FG_BRIGHT_GREEN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_GREEN = "\033[92m" constexpr
Definition at line 46 of file enhanced_tui.cc.
FG_BRIGHT_YELLOW
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_YELLOW = "\033[93m" constexpr
Definition at line 47 of file enhanced_tui.cc.
FG_BRIGHT_BLUE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_BLUE = "\033[94m" constexpr
Definition at line 48 of file enhanced_tui.cc.
FG_BRIGHT_MAGENTA
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_MAGENTA = "\033[95m" constexpr
Definition at line 49 of file enhanced_tui.cc.
FG_BRIGHT_CYAN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_CYAN = "\033[96m" constexpr
Definition at line 50 of file enhanced_tui.cc.
FG_BRIGHT_WHITE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::FG_BRIGHT_WHITE = "\033[97m" constexpr
Definition at line 51 of file enhanced_tui.cc.
BG_BLACK
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BLACK = "\033[40m" constexpr
Definition at line 54 of file enhanced_tui.cc.
BG_RED
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_RED = "\033[41m" constexpr
Definition at line 55 of file enhanced_tui.cc.
BG_GREEN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_GREEN = "\033[42m" constexpr
Definition at line 56 of file enhanced_tui.cc.
BG_YELLOW
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_YELLOW = "\033[43m" constexpr
Definition at line 57 of file enhanced_tui.cc.
BG_BLUE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BLUE = "\033[44m" constexpr
Definition at line 58 of file enhanced_tui.cc.
BG_MAGENTA
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_MAGENTA = "\033[45m" constexpr
Definition at line 59 of file enhanced_tui.cc.
BG_CYAN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_CYAN = "\033[46m" constexpr
Definition at line 60 of file enhanced_tui.cc.
BG_WHITE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_WHITE = "\033[47m" constexpr
Definition at line 61 of file enhanced_tui.cc.
BG_BRIGHT_BLACK
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_BLACK = "\033[100m" constexpr
Definition at line 62 of file enhanced_tui.cc.
BG_BRIGHT_RED
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_RED = "\033[101m" constexpr
Definition at line 63 of file enhanced_tui.cc.
BG_BRIGHT_GREEN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_GREEN = "\033[102m" constexpr
Definition at line 64 of file enhanced_tui.cc.
BG_BRIGHT_YELLOW
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_YELLOW = "\033[103m" constexpr
Definition at line 65 of file enhanced_tui.cc.
BG_BRIGHT_BLUE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_BLUE = "\033[104m" constexpr
Definition at line 66 of file enhanced_tui.cc.
BG_BRIGHT_MAGENTA
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_MAGENTA = "\033[105m" constexpr
Definition at line 67 of file enhanced_tui.cc.
BG_BRIGHT_CYAN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_CYAN = "\033[106m" constexpr
Definition at line 68 of file enhanced_tui.cc.
BG_BRIGHT_WHITE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::BG_BRIGHT_WHITE = "\033[107m" constexpr
Definition at line 69 of file enhanced_tui.cc.
KEY_ESC
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_ESC = 27 constexpr
Definition at line 72 of file enhanced_tui.cc.
KEY_ENTER
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_ENTER = 10 constexpr
Definition at line 73 of file enhanced_tui.cc.
KEY_BACKSPACE
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_BACKSPACE = 127 constexpr
Definition at line 74 of file enhanced_tui.cc.
KEY_TAB
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_TAB = 9 constexpr
Definition at line 75 of file enhanced_tui.cc.
KEY_UP
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_UP = 1000 constexpr
Definition at line 76 of file enhanced_tui.cc.
KEY_DOWN
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_DOWN = 1001 constexpr
Definition at line 77 of file enhanced_tui.cc.
KEY_LEFT
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_LEFT = 1002 constexpr
Definition at line 78 of file enhanced_tui.cc.
KEY_RIGHT
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_RIGHT = 1003 constexpr
Definition at line 79 of file enhanced_tui.cc.
KEY_HOME
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_HOME = 1004 constexpr
Definition at line 80 of file enhanced_tui.cc.
KEY_END
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_END = 1005 constexpr
Definition at line 81 of file enhanced_tui.cc.
KEY_DELETE
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_DELETE = 1006 constexpr
Definition at line 82 of file enhanced_tui.cc.
KEY_PAGE_UP
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_PAGE_UP = 1007 constexpr
Definition at line 83 of file enhanced_tui.cc.
KEY_PAGE_DOWN
constexpr int yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::KEY_PAGE_DOWN = 1008 constexpr
Definition at line 84 of file enhanced_tui.cc.
CLEAR_SCREEN
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::CLEAR_SCREEN = "\033[2J" constexpr
Definition at line 87 of file enhanced_tui.cc.
CLEAR_LINE
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::CLEAR_LINE = "\033[2K" constexpr
Definition at line 88 of file enhanced_tui.cc.
CURSOR_HOME
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::CURSOR_HOME = "\033[H" constexpr
Definition at line 89 of file enhanced_tui.cc.
SAVE_CURSOR
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::SAVE_CURSOR = "\033[s" constexpr
Definition at line 90 of file enhanced_tui.cc.
RESTORE_CURSOR
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::RESTORE_CURSOR = "\033[u" constexpr
Definition at line 91 of file enhanced_tui.cc.
HIDE_CURSOR
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::HIDE_CURSOR = "\033[?25l" constexpr
Definition at line 92 of file enhanced_tui.cc.
SHOW_CURSOR
constexpr const char* yaze::cli::agent::anonymous_namespace{enhanced_tui.cc}::SHOW_CURSOR = "\033[?25h" constexpr
Definition at line 93 of file enhanced_tui.cc.