yaze: yaze::gui::canvas::CanvasUtils Namespace Reference
yaze::gui::canvas::CanvasUtils Namespace Reference
Utility functions for canvas operations.
Functions
ImVec2 AlignToGrid (ImVec2 pos, float grid_step)
Align position to grid Pure function - no side effects.
float CalculateEffectiveScale (ImVec2 canvas_size, ImVec2 content_size, float global_scale)
Calculate effective scale for content.
int GetTileIdFromPosition (ImVec2 mouse_pos, float tile_size, float scale, int tiles_per_row)
Get tile ID from mouse position.
bool LoadROMPaletteGroups (Rom *rom, CanvasPaletteManager &palette_manager)
bool ApplyPaletteGroup (gfx::Bitmap *bitmap, const CanvasPaletteManager &palette_manager, int group_index, int palette_index)
void DrawCanvasRect (ImDrawList *draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int x, int y, int w, int h, ImVec4 color, float global_scale)
void DrawCanvasText (ImDrawList *draw_list, ImVec2 canvas_p0, ImVec2 scrolling, const std::string &text, int x, int y, float global_scale)
void DrawCanvasOutline (ImDrawList *draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int x, int y, int w, int h, uint32_t color)
void DrawCanvasOutlineWithColor (ImDrawList *draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int x, int y, int w, int h, ImVec4 color)
void DrawCanvasGridLines (ImDrawList *draw_list, ImVec2 canvas_p0, ImVec2 canvas_p1, ImVec2 scrolling, float grid_step, float global_scale)
void DrawCustomHighlight (ImDrawList *draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int highlight_tile_id, float grid_step)
void DrawHexTileLabels (ImDrawList *draw_list, ImVec2 canvas_p0, ImVec2 scrolling, ImVec2 canvas_sz, float grid_step, float global_scale)
ImVec2 CalculateCanvasSize (ImVec2 content_region, ImVec2 custom_size, bool use_custom)
ImVec2 CalculateScaledCanvasSize (ImVec2 canvas_size, float global_scale)
bool IsPointInCanvas (ImVec2 point, ImVec2 canvas_p0, ImVec2 canvas_p1)
ImVec2 CalculateMinimumCanvasSize (ImVec2 content_size, float global_scale, float padding)
ImVec2 CalculatePreferredCanvasSize (ImVec2 content_size, float global_scale, float min_scale)
void ReserveCanvasSpace (ImVec2 canvas_size, const std::string &label)
void SetNextCanvasSize (ImVec2 size, bool auto_resize)
void DrawCanvasGrid (const CanvasRenderContext &ctx, int highlight_tile_id)
void DrawCanvasOverlay (const CanvasRenderContext &ctx, const ImVector< ImVec2 > &points, const ImVector< ImVec2 > &selected_points)
void DrawCanvasLabels (const CanvasRenderContext &ctx, const ImVector< ImVector< std::string > > &labels, int current_labels, int tile_id_offset)
Detailed Description
Utility functions for canvas operations.
Stateless utilities for common canvas operations. Following ImGui design pattern of pure helper functions.
Function Documentation
AlignToGrid()
ImVec2 yaze::gui::canvas::CanvasUtils::AlignToGrid (ImVec2 pos, float grid_step)
Align position to grid Pure function - no side effects.
Definition at line 15 of file canvas_utils_moved.cc.
CalculateEffectiveScale()
float yaze::gui::canvas::CanvasUtils::CalculateEffectiveScale (ImVec2 canvas_size, ImVec2 content_size, float global_scale)
Calculate effective scale for content.
Definition at line 20 of file canvas_utils_moved.cc.
GetTileIdFromPosition()
int yaze::gui::canvas::CanvasUtils::GetTileIdFromPosition (ImVec2 mouse_pos, float tile_size, float scale, int tiles_per_row)
Get tile ID from mouse position.
Definition at line 30 of file canvas_utils_moved.cc.
LoadROMPaletteGroups()
bool yaze::gui::canvas::CanvasUtils::LoadROMPaletteGroups (Rom * rom, CanvasPaletteManager & palette_manager)
Definition at line 39 of file canvas_utils_moved.cc.
References yaze::Rom::palette_group(), yaze::gui::canvas::CanvasPaletteManager::palette_group_names, yaze::gui::canvas::CanvasPaletteManager::palettes_loaded, and yaze::gui::canvas::CanvasPaletteManager::rom_palette_groups.
ApplyPaletteGroup()
bool yaze::gui::canvas::CanvasUtils::ApplyPaletteGroup (gfx::Bitmap * bitmap, const CanvasPaletteManager & palette_manager, int group_index, int palette_index)
Definition at line 99 of file canvas_utils_moved.cc.
References yaze::core::Renderer::Get(), yaze::gui::canvas::CanvasPaletteManager::rom_palette_groups, yaze::gfx::Bitmap::SetPalette(), yaze::gfx::Bitmap::SetPaletteWithTransparent(), and yaze::core::Renderer::UpdateBitmap().
DrawCanvasRect()
void yaze::gui::canvas::CanvasUtils::DrawCanvasRect (ImDrawList * draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int x, int y, int w, int h, ImVec4 color, float global_scale)
Definition at line 131 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::DrawRect().
DrawCanvasText()
void yaze::gui::canvas::CanvasUtils::DrawCanvasText (ImDrawList * draw_list, ImVec2 canvas_p0, ImVec2 scrolling, const std::string & text, int x, int y, float global_scale)
Definition at line 154 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::DrawText().
DrawCanvasOutline()
void yaze::gui::canvas::CanvasUtils::DrawCanvasOutline (ImDrawList * draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int x, int y, int w, int h, uint32_t color)
Definition at line 169 of file canvas_utils_moved.cc.
Referenced by DrawCanvasOutlineWithColor(), yaze::gui::Canvas::DrawOutline(), and yaze::gui::Canvas::DrawOutlineWithColor().
DrawCanvasOutlineWithColor()
void yaze::gui::canvas::CanvasUtils::DrawCanvasOutlineWithColor (ImDrawList * draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int x, int y, int w, int h, ImVec4 color)
Definition at line 178 of file canvas_utils_moved.cc.
References DrawCanvasOutline().
Referenced by yaze::gui::Canvas::DrawOutlineWithColor().
DrawCanvasGridLines()
void yaze::gui::canvas::CanvasUtils::DrawCanvasGridLines (ImDrawList * draw_list, ImVec2 canvas_p0, ImVec2 canvas_p1, ImVec2 scrolling, float grid_step, float global_scale)
Definition at line 187 of file canvas_utils_moved.cc.
Referenced by DrawCanvasGrid(), and yaze::gui::Canvas::DrawGridLines().
DrawCustomHighlight()
void yaze::gui::canvas::CanvasUtils::DrawCustomHighlight (ImDrawList * draw_list, ImVec2 canvas_p0, ImVec2 scrolling, int highlight_tile_id, float grid_step)
Definition at line 210 of file canvas_utils_moved.cc.
Referenced by DrawCanvasGrid(), and yaze::gui::Canvas::DrawCustomHighlight().
DrawHexTileLabels()
void yaze::gui::canvas::CanvasUtils::DrawHexTileLabels (ImDrawList * draw_list, ImVec2 canvas_p0, ImVec2 scrolling, ImVec2 canvas_sz, float grid_step, float global_scale)
Definition at line 225 of file canvas_utils_moved.cc.
Referenced by DrawCanvasGrid().
CalculateCanvasSize()
ImVec2 yaze::gui::canvas::CanvasUtils::CalculateCanvasSize (ImVec2 content_region, ImVec2 custom_size, bool use_custom)
Definition at line 249 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::DrawBackground().
CalculateScaledCanvasSize()
ImVec2 yaze::gui::canvas::CanvasUtils::CalculateScaledCanvasSize (ImVec2 canvas_size, float global_scale)
Definition at line 254 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::DrawBackground().
IsPointInCanvas()
bool yaze::gui::canvas::CanvasUtils::IsPointInCanvas (ImVec2 point, ImVec2 canvas_p0, ImVec2 canvas_p1)
Definition at line 258 of file canvas_utils_moved.cc.
CalculateMinimumCanvasSize()
ImVec2 yaze::gui::canvas::CanvasUtils::CalculateMinimumCanvasSize (ImVec2 content_size, float global_scale, float padding)
Definition at line 264 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::GetMinimumSize().
CalculatePreferredCanvasSize()
ImVec2 yaze::gui::canvas::CanvasUtils::CalculatePreferredCanvasSize (ImVec2 content_size, float global_scale, float min_scale)
Definition at line 277 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::GetPreferredSize(), and yaze::gui::TableCanvasPipeline().
ReserveCanvasSpace()
void yaze::gui::canvas::CanvasUtils::ReserveCanvasSpace (ImVec2 canvas_size, const std::string & label)
Definition at line 291 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::ReserveTableSpace().
SetNextCanvasSize()
void yaze::gui::canvas::CanvasUtils::SetNextCanvasSize (ImVec2 size, bool auto_resize)
Definition at line 302 of file canvas_utils_moved.cc.
Referenced by yaze::gui::Canvas::BeginTableCanvas().
DrawCanvasGrid()
void yaze::gui::canvas::CanvasUtils::DrawCanvasGrid (const CanvasRenderContext & ctx, int highlight_tile_id)
Definition at line 313 of file canvas_utils_moved.cc.
References yaze::gui::canvas::CanvasRenderContext::canvas_p0, yaze::gui::canvas::CanvasRenderContext::canvas_p1, yaze::gui::canvas::CanvasRenderContext::draw_list, DrawCanvasGridLines(), DrawCustomHighlight(), DrawHexTileLabels(), yaze::gui::canvas::CanvasRenderContext::enable_grid, yaze::gui::canvas::CanvasRenderContext::enable_hex_labels, yaze::gui::canvas::CanvasRenderContext::global_scale, yaze::gui::canvas::CanvasRenderContext::grid_step, and yaze::gui::canvas::CanvasRenderContext::scrolling.
Referenced by yaze::gui::Canvas::DrawGrid().
DrawCanvasOverlay()
void yaze::gui::canvas::CanvasUtils::DrawCanvasOverlay (const CanvasRenderContext & ctx, const ImVector< ImVec2 > & points, const ImVector< ImVec2 > & selected_points)
Definition at line 340 of file canvas_utils_moved.cc.
References yaze::gui::canvas::CanvasRenderContext::canvas_p0, yaze::gui::canvas::CanvasRenderContext::draw_list, and yaze::gui::canvas::CanvasRenderContext::scrolling.
Referenced by yaze::gui::Canvas::DrawOverlay().
DrawCanvasLabels()
void yaze::gui::canvas::CanvasUtils::DrawCanvasLabels (const CanvasRenderContext & ctx, const ImVector< ImVector< std::string > > & labels, int current_labels, int tile_id_offset)
Definition at line 366 of file canvas_utils_moved.cc.
References yaze::gui::canvas::CanvasRenderContext::canvas_p0, yaze::gui::canvas::CanvasRenderContext::canvas_p1, yaze::gui::canvas::CanvasRenderContext::draw_list, yaze::gui::canvas::CanvasRenderContext::global_scale, yaze::gui::canvas::CanvasRenderContext::grid_step, and yaze::gui::canvas::CanvasRenderContext::scrolling.
Referenced by yaze::gui::Canvas::DrawGrid().