yaze: yaze::editor::test::Tile16EditorIntegrationTest Class Reference
yaze::editor::test::Tile16EditorIntegrationTest Class Reference
Protected Member Functions
void SetUp () override
Static Protected Member Functions
static void SetUpTestSuite ()
static void TearDownTestSuite ()
static void InitializeTestEnvironment ()
Protected Attributes
bool rom_loaded_ = false
std::unique_ptr< Rom > rom_
std::unique_ptr< gfx::Tilemap > tilemap_
std::unique_ptr< gfx::Tilemap > tile16_blockset_
std::unique_ptr< gfx::Bitmap > current_gfx_bmp_
std::unique_ptr< gfx::Bitmap > tile16_blockset_bmp_
std::unique_ptr< zelda3::Overworld > overworld_
std::unique_ptr< Tile16Editor > editor_
Static Protected Attributes
static bool window_initialized_ = false
static core::Window test_window_
static std::unique_ptr< gfx::SDL2Renderer > test_renderer_
Detailed Description
Definition at line 20 of file tile16_editor_test.cc.
Member Function Documentation
SetUpTestSuite()
static void yaze::editor::test::Tile16EditorIntegrationTest::SetUpTestSuite () inline static protected
Definition at line 22 of file tile16_editor_test.cc.
References InitializeTestEnvironment().
TearDownTestSuite()
static void yaze::editor::test::Tile16EditorIntegrationTest::TearDownTestSuite () inline static protected
Definition at line 27 of file tile16_editor_test.cc.
References yaze::core::ShutdownWindow(), test_window_, and window_initialized_.
SetUp()
void yaze::editor::test::Tile16EditorIntegrationTest::SetUp () inline override protected
Definition at line 36 of file tile16_editor_test.cc.
References yaze::gfx::Arena::CREATE, yaze::gfx::CreateTilemap(), current_gfx_bmp_, editor_, yaze::gfx::Arena::Get(), yaze::zelda3::kNumTile16Individual, overworld_, yaze::gfx::Arena::QueueTextureCommand(), rom_, rom_loaded_, tile16_blockset_, tile16_blockset_bmp_, tilemap_, and window_initialized_.
InitializeTestEnvironment()
static void yaze::editor::test::Tile16EditorIntegrationTest::InitializeTestEnvironment () inline static protected
Definition at line 91 of file tile16_editor_test.cc.
References yaze::core::CreateWindow(), test_renderer_, test_window_, and window_initialized_.
Referenced by SetUpTestSuite().
Member Data Documentation
window_initialized_
bool yaze::editor::test::Tile16EditorIntegrationTest::window_initialized_ = false static protected
Definition at line 104 of file tile16_editor_test.cc.
Referenced by InitializeTestEnvironment(), SetUp(), and TearDownTestSuite().
test_window_
core::Window yaze::editor::test::Tile16EditorIntegrationTest::test_window_ static protected
Definition at line 105 of file tile16_editor_test.cc.
Referenced by InitializeTestEnvironment(), and TearDownTestSuite().
test_renderer_
std::unique_ptr< gfx::SDL2Renderer > yaze::editor::test::Tile16EditorIntegrationTest::test_renderer_ static protected
Definition at line 106 of file tile16_editor_test.cc.
Referenced by InitializeTestEnvironment().
rom_loaded_
bool yaze::editor::test::Tile16EditorIntegrationTest::rom_loaded_ = false protected
Definition at line 108 of file tile16_editor_test.cc.
Referenced by SetUp().
rom_
std::unique_ptr<Rom> yaze::editor::test::Tile16EditorIntegrationTest::rom_ protected
Definition at line 109 of file tile16_editor_test.cc.
Referenced by SetUp().
tilemap_
std::unique_ptr<gfx::Tilemap> yaze::editor::test::Tile16EditorIntegrationTest::tilemap_ protected
Definition at line 110 of file tile16_editor_test.cc.
Referenced by SetUp().
tile16_blockset_
std::unique_ptr<gfx::Tilemap> yaze::editor::test::Tile16EditorIntegrationTest::tile16_blockset_ protected
Definition at line 111 of file tile16_editor_test.cc.
Referenced by SetUp().
current_gfx_bmp_
std::unique_ptr<gfx::Bitmap> yaze::editor::test::Tile16EditorIntegrationTest::current_gfx_bmp_ protected
Definition at line 112 of file tile16_editor_test.cc.
Referenced by SetUp().
tile16_blockset_bmp_
std::unique_ptr<gfx::Bitmap> yaze::editor::test::Tile16EditorIntegrationTest::tile16_blockset_bmp_ protected
Definition at line 113 of file tile16_editor_test.cc.
Referenced by SetUp().
overworld_
std::unique_ptr<zelda3::Overworld> yaze::editor::test::Tile16EditorIntegrationTest::overworld_ protected
Definition at line 114 of file tile16_editor_test.cc.
Referenced by SetUp().
editor_
std::unique_ptr<Tile16Editor> yaze::editor::test::Tile16EditorIntegrationTest::editor_ protected
Definition at line 115 of file tile16_editor_test.cc.
Referenced by SetUp().
The documentation for this class was generated from the following file:
test/integration/editor/tile16_editor_test.cc