yaze: yaze::test::TestManager Class Reference
yaze::test::TestManager Class Reference
#include <test_manager.h>
Classes
struct HarnessAggregate
Public Member Functions
absl::Status RunAllTests ()
absl::Status RunTestsByCategory (TestCategory category)
absl::Status RunTestSuite (const std::string &suite_name)
void RegisterTestSuite (std::unique_ptr< TestSuite > suite)
std::vector< std::string > GetTestSuiteNames () const
TestSuite * GetTestSuite (const std::string &name)
const TestResults & GetLastResults () const
void ClearResults ()
void SetMaxConcurrentTests (size_t max_concurrent)
void SetTestTimeout (std::chrono::seconds timeout)
void UpdateResourceStats ()
const std::vector< ResourceStats > & GetResourceHistory () const
void * GetUITestEngine ()
void InitializeUITesting ()
void StopUITesting ()
void DestroyUITestingContext ()
void ShutdownUITesting ()
bool IsTestRunning () const
const std::string & GetCurrentTestName () const
float GetProgress () const
void DrawTestDashboard (bool *show_dashboard=nullptr)
void SetCurrentRom (Rom *rom)
Rom * GetCurrentRom () const
void RefreshCurrentRom ()
absl::Status LoadRomForTesting (const std::string &filename)
void ShowRomComparisonResults (const Rom &before, const Rom &after)
absl::Status CreateTestRomCopy (Rom *source_rom, std::unique_ptr< Rom > &test_rom)
std::string GenerateTestRomFilename (const std::string &base_name)
void OfferTestSessionCreation (const std::string &test_rom_path)
absl::Status TestRomSaveLoad (Rom *rom)
absl::Status TestRomDataIntegrity (Rom *rom)
absl::Status TestRomWithCopy (Rom *source_rom, std::function< absl::Status(Rom *)> test_function)
void DisableTest (const std::string &test_name)
void EnableTest (const std::string &test_name)
bool IsTestEnabled (const std::string &test_name) const
std::string RegisterHarnessTest (const std::string &name, const std::string &category) ABSL_LOCKS_EXCLUDED(harness_history_mutex_)
void MarkHarnessTestRunning (const std::string &test_id) ABSL_LOCKS_EXCLUDED(harness_history_mutex_)
void MarkHarnessTestCompleted (const std::string &test_id, HarnessTestStatus status, const std::string &error_message="", const std::vector< std::string > &assertion_failures={}, const std::vector< std::string > &logs={}, const std::map< std::string, int32_t > &metrics={}) ABSL_LOCKS_EXCLUDED(harness_history_mutex_)
void AppendHarnessTestLog (const std::string &test_id, const std::string &log_entry) ABSL_LOCKS_EXCLUDED(harness_history_mutex_)
absl::StatusOr< HarnessTestExecution > GetHarnessTestExecution (const std::string &test_id) const ABSL_LOCKS_EXCLUDED(harness_history_mutex_)
std::vector< HarnessTestSummary > ListHarnessTestSummaries (const std::string &category_filter="") const ABSL_LOCKS_EXCLUDED(harness_history_mutex_)
void CaptureFailureContext (const std::string &test_id) ABSL_LOCKS_EXCLUDED(harness_history_mutex_)
Static Public Member Functions
static TestManager & Get ()
Private Member Functions
TestManager ()
~TestManager ()
absl::Status ExecuteTestSuite (TestSuite *suite)
void UpdateProgress ()
void CollectResourceStats ()
void TrimResourceHistory ()
std::unordered_map< std::string, HarnessTestExecution > harness_history_ ABSL_GUARDED_BY (harness_history_mutex_)
std::unordered_map< std::string, HarnessAggregate > harness_aggregates_ ABSL_GUARDED_BY (harness_history_mutex_)
std::deque< std::string > harness_history_order_ ABSL_GUARDED_BY (harness_history_mutex_)
std::string GenerateHarnessTestIdLocked (absl::string_view prefix) ABSL_EXCLUSIVE_LOCKS_REQUIRED(harness_history_mutex_)
void TrimHarnessHistoryLocked () ABSL_EXCLUSIVE_LOCKS_REQUIRED(harness_history_mutex_)
Private Attributes
std::vector< std::unique_ptr< TestSuite > > test_suites_
std::unordered_map< std::string, TestSuite * > suite_lookup_
TestResults last_results_
bool is_running_ = false
std::string current_test_name_
float progress_ = 0.0f
size_t max_concurrent_tests_ = 1
std::chrono::seconds test_timeout_ {30}
std::vector< ResourceStats > resource_history_
bool show_dashboard_ = false
bool show_resource_monitor_ = false
std::string test_filter_
TestCategory category_filter_ = TestCategory::kUnit
Rom * current_rom_ = nullptr
bool show_google_tests_ = false
bool show_rom_test_results_ = false
bool show_rom_file_dialog_ = false
bool show_test_session_dialog_ = false
bool show_test_configuration_ = false
std::string test_rom_path_for_session_
std::unordered_map< std::string, bool > disabled_tests_
size_t harness_history_limit_ = 200
absl::Mutex harness_history_mutex_
Static Private Attributes
static constexpr size_t kMaxResourceHistorySize = 1000
Detailed Description
Definition at line 160 of file test_manager.h.
Constructor & Destructor Documentation
TestManager()
yaze::test::TestManager::TestManager () private
Definition at line 116 of file test_manager.cc.
~TestManager()
yaze::test::TestManager::~TestManager () private
Definition at line 121 of file test_manager.cc.
References ShutdownUITesting().
Member Function Documentation
Get()
TestManager & yaze::test::TestManager::Get () static
Definition at line 111 of file test_manager.cc.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::EditorManager::CloseCurrentSession(), yaze::core::CreateWindow(), yaze::test::E2ETestSuite::DrawConfiguration(), yaze::test::RomDependentTestSuite::DrawConfiguration(), yaze::test::ZSCustomOverworldTestSuite::DrawConfiguration(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::EditorManager::InitializeTestSuites(), yaze::editor::EditorManager::LoadRom(), main(), yaze::editor::EditorManager::OpenProject(), yaze::test::RegisterZ3edTestSuites(), yaze::test::ZSCustomOverworldTestSuite::RunAddressValidationTest(), yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest(), yaze::test::E2ETestSuite::RunCorruptionDetectionTest(), yaze::test::E2ETestSuite::RunDataIntegrityTest(), yaze::test::ZSCustomOverworldTestSuite::RunDataIntegrityTest(), yaze::test::ZSCustomOverworldTestSuite::RunFeatureToggleTest(), yaze::test::E2ETestSuite::RunLargeScaleEditingTest(), yaze::test::IntegratedTestSuite::RunRomBasicTest(), yaze::test::E2ETestSuite::RunRomLoadSaveTest(), yaze::test::E2ETestSuite::RunTests(), yaze::test::RomDependentTestSuite::RunTests(), yaze::test::ZSCustomOverworldTestSuite::RunTests(), yaze::test::E2ETestSuite::RunTransactionSystemTest(), yaze::test::ZSCustomOverworldTestSuite::RunV2UpgradeTest(), yaze::test::ZSCustomOverworldTestSuite::RunV3UpgradeTest(), yaze::test::ZSCustomOverworldTestSuite::RunVanillaBaselineTest(), yaze::editor::EditorManager::SetCurrentRom(), yaze::core::ShutdownWindow(), yaze::editor::EditorManager::SwitchToSession(), and yaze::editor::EditorManager::Update().
RunAllTests()
absl::Status yaze::test::TestManager::RunAllTests ()
Definition at line 171 of file test_manager.cc.
References yaze::test::TestResults::Clear(), current_test_name_, ExecuteTestSuite(), is_running_, last_results_, progress_, test_suites_, and UpdateProgress().
Referenced by yaze::editor::EditorManager::BuildModernMenu(), and DrawTestDashboard().
RunTestsByCategory()
absl::Status yaze::test::TestManager::RunTestsByCategory (TestCategory category)
Definition at line 200 of file test_manager.cc.
References yaze::test::TestResults::Clear(), current_test_name_, ExecuteTestSuite(), is_running_, last_results_, progress_, test_suites_, and UpdateProgress().
Referenced by yaze::editor::EditorManager::BuildModernMenu(), and DrawTestDashboard().
RunTestSuite()
absl::Status yaze::test::TestManager::RunTestSuite (const std::string & suite_name)
Definition at line 234 of file test_manager.cc.
References yaze::test::TestResults::Clear(), current_test_name_, ExecuteTestSuite(), is_running_, last_results_, progress_, and suite_lookup_.
Referenced by yaze::editor::EditorManager::BuildModernMenu().
RegisterTestSuite()
void yaze::test::TestManager::RegisterTestSuite (std::unique_ptr< TestSuite > suite)
Definition at line 258 of file test_manager.cc.
References suite_lookup_, and test_suites_.
Referenced by yaze::test::RegisterZ3edTestSuites().
GetTestSuiteNames()
std::vector< std::string > yaze::test::TestManager::GetTestSuiteNames () const
Definition at line 266 of file test_manager.cc.
References test_suites_.
GetTestSuite()
TestSuite * yaze::test::TestManager::GetTestSuite (const std::string & name)
Definition at line 275 of file test_manager.cc.
References suite_lookup_.
GetLastResults()
const TestResults & yaze::test::TestManager::GetLastResults () const inline
Definition at line 175 of file test_manager.h.
References last_results_.
ClearResults()
void yaze::test::TestManager::ClearResults () inline
Definition at line 176 of file test_manager.h.
References yaze::test::TestResults::Clear(), and last_results_.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), and DrawTestDashboard().
SetMaxConcurrentTests()
void yaze::test::TestManager::SetMaxConcurrentTests (size_t max_concurrent) inline
Definition at line 179 of file test_manager.h.
References max_concurrent_tests_.
SetTestTimeout()
void yaze::test::TestManager::SetTestTimeout (std::chrono::seconds timeout) inline
Definition at line 182 of file test_manager.h.
References test_timeout_.
UpdateResourceStats()
void yaze::test::TestManager::UpdateResourceStats ()
Definition at line 280 of file test_manager.cc.
References CollectResourceStats(), and TrimResourceHistory().
GetResourceHistory()
const std::vector< ResourceStats > & yaze::test::TestManager::GetResourceHistory () const inline
Definition at line 186 of file test_manager.h.
References resource_history_.
GetUITestEngine()
void * yaze::test::TestManager::GetUITestEngine () inline
Definition at line 199 of file test_manager.h.
InitializeUITesting()
void yaze::test::TestManager::InitializeUITesting () inline
Definition at line 200 of file test_manager.h.
Referenced by yaze::core::CreateWindow().
StopUITesting()
void yaze::test::TestManager::StopUITesting () inline
Definition at line 201 of file test_manager.h.
Referenced by yaze::core::ShutdownWindow().
DestroyUITestingContext()
void yaze::test::TestManager::DestroyUITestingContext () inline
Definition at line 202 of file test_manager.h.
Referenced by yaze::core::ShutdownWindow().
ShutdownUITesting()
void yaze::test::TestManager::ShutdownUITesting () inline
Definition at line 203 of file test_manager.h.
Referenced by ~TestManager().
IsTestRunning()
bool yaze::test::TestManager::IsTestRunning () const inline
Definition at line 207 of file test_manager.h.
References is_running_.
GetCurrentTestName()
const std::string & yaze::test::TestManager::GetCurrentTestName () const inline
Definition at line 208 of file test_manager.h.
References current_test_name_.
GetProgress()
float yaze::test::TestManager::GetProgress () const inline
Definition at line 209 of file test_manager.h.
References progress_.
DrawTestDashboard()
void yaze::test::TestManager::DrawTestDashboard (bool * show_dashboard = nullptr)
Todo:
Implement result export
Todo:
Implement file dialog to load ROM specifically for testing
Todo:
This would need access to EditorManager to create a new session
Definition at line 346 of file test_manager.cc.
References category_filter_, ClearResults(), current_rom_, current_test_name_, yaze::Rom::data(), yaze::Rom::dirty(), DisableTest(), EnableTest(), yaze::test::TestResults::failed_tests, yaze::Rom::filename(), yaze::core::FeatureFlags::get(), yaze::test::TestResults::GetPassRate(), yaze::test::GetTestStatusColor(), ICON_MD_ANALYTICS, ICON_MD_ASSESSMENT, ICON_MD_BLOCK, ICON_MD_CAMERA_ALT, ICON_MD_CHECK, ICON_MD_CHECK_CIRCLE, ICON_MD_CHECKLIST, ICON_MD_CLEAR, ICON_MD_CLOSE, ICON_MD_DESCRIPTION, ICON_MD_EDIT, ICON_MD_ERROR, ICON_MD_ERROR_OUTLINE, ICON_MD_FILTER_LIST, ICON_MD_FOLDER_OPEN, ICON_MD_HELP, ICON_MD_HISTORY, ICON_MD_INFO, ICON_MD_LAYERS, ICON_MD_MEMORY, ICON_MD_MONITOR, ICON_MD_PLAY_ARROW, ICON_MD_PLAY_CIRCLE_FILLED, ICON_MD_SCHEDULE, ICON_MD_SCIENCE, ICON_MD_SETTINGS, ICON_MD_SKIP_NEXT, ICON_MD_SPEED, ICON_MD_STORAGE, ICON_MD_TAB, ICON_MD_TEXTURE, ICON_MD_TIMER, ICON_MD_TIMER_OFF, ICON_MD_WARNING, yaze::test::TestResults::individual_results, yaze::Rom::is_loaded(), is_running_, IsTestEnabled(), yaze::test::kFailed, yaze::test::kIntegration, yaze::test::kMemory, yaze::test::kPassed, yaze::test::kPerformance, yaze::test::kQueued, yaze::test::kRunning, yaze::test::kSkipped, yaze::test::kTimeout, yaze::test::kUI, yaze::test::kUnit, yaze::core::FeatureFlags::Flags::kUseNativeFileDialog, last_results_, ListHarnessTestSummaries(), LOG_INFO, yaze::test::TestResults::passed_tests, progress_, RefreshCurrentRom(), resource_history_, RunAllTests(), RunTestsByCategory(), show_dashboard_, show_google_tests_, show_resource_monitor_, show_rom_file_dialog_, show_rom_test_results_, show_test_configuration_, show_test_session_dialog_, yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::util::FileDialogWrapper::ShowOpenFileDialogBespoke(), yaze::util::FileDialogWrapper::ShowOpenFileDialogNFD(), yaze::Rom::size(), yaze::test::TestResults::skipped_tests, test_filter_, test_rom_path_for_session_, TestRomDataIntegrity(), TestRomSaveLoad(), yaze::Rom::title(), yaze::test::TestResults::total_duration, and yaze::test::TestResults::total_tests.
SetCurrentRom()
void yaze::test::TestManager::SetCurrentRom (Rom * rom) inline
Definition at line 215 of file test_manager.h.
References current_rom_, yaze::Rom::is_loaded(), LOG_INFO, and yaze::Rom::title().
Referenced by yaze::editor::EditorManager::CloseCurrentSession(), yaze::editor::EditorManager::LoadRom(), yaze::editor::EditorManager::OpenProject(), yaze::editor::EditorManager::SetCurrentRom(), yaze::editor::EditorManager::SwitchToSession(), and yaze::editor::EditorManager::Update().
GetCurrentRom()
Rom * yaze::test::TestManager::GetCurrentRom () const inline
Definition at line 223 of file test_manager.h.
References current_rom_.
Referenced by yaze::test::E2ETestSuite::DrawConfiguration(), yaze::test::RomDependentTestSuite::DrawConfiguration(), yaze::test::ZSCustomOverworldTestSuite::DrawConfiguration(), yaze::test::IntegratedTestSuite::RunRomBasicTest(), yaze::test::E2ETestSuite::RunTests(), yaze::test::RomDependentTestSuite::RunTests(), and yaze::test::ZSCustomOverworldTestSuite::RunTests().
RefreshCurrentRom()
void yaze::test::TestManager::RefreshCurrentRom ()
Definition at line 1426 of file test_manager.cc.
References current_rom_, yaze::Rom::dirty(), yaze::Rom::is_loaded(), LOG_INFO, yaze::Rom::size(), and yaze::Rom::title().
Referenced by DrawTestDashboard().
LoadRomForTesting()
absl::Status yaze::test::TestManager::LoadRomForTesting (const std::string & filename)
Definition at line 1529 of file test_manager.cc.
References LOG_INFO.
ShowRomComparisonResults()
void yaze::test::TestManager::ShowRomComparisonResults (const Rom & before, const Rom & after)
Definition at line 1538 of file test_manager.cc.
References yaze::Rom::dirty(), ICON_MD_COMPARE, and yaze::Rom::size().
CreateTestRomCopy()
absl::Status yaze::test::TestManager::CreateTestRomCopy (Rom * source_rom, std::unique_ptr< Rom > & test_rom)
Definition at line 1451 of file test_manager.cc.
References yaze::Rom::is_loaded(), LOG_INFO, yaze::Rom::title(), and yaze::Rom::vector().
Referenced by TestRomWithCopy().
GenerateTestRomFilename()
std::string yaze::test::TestManager::GenerateTestRomFilename (const std::string & base_name)
Definition at line 1475 of file test_manager.cc.
Referenced by TestRomSaveLoad().
OfferTestSessionCreation()
void yaze::test::TestManager::OfferTestSessionCreation (const std::string & test_rom_path)
Definition at line 1502 of file test_manager.cc.
References show_test_session_dialog_, and test_rom_path_for_session_.
Referenced by TestRomSaveLoad().
TestRomSaveLoad()
absl::Status yaze::test::TestManager::TestRomSaveLoad (Rom * rom)
Definition at line 1572 of file test_manager.cc.
References yaze::Rom::SaveSettings::backup, yaze::Rom::SaveSettings::filename, GenerateTestRomFilename(), yaze::Rom::is_loaded(), LOG_INFO, OfferTestSessionCreation(), yaze::Rom::SaveSettings::save_new, yaze::Rom::SaveToFile(), TestRomWithCopy(), and yaze::Rom::title().
Referenced by DrawTestDashboard().
TestRomDataIntegrity()
absl::Status yaze::test::TestManager::TestRomDataIntegrity (Rom * rom)
Definition at line 1604 of file test_manager.cc.
References yaze::Rom::is_loaded(), LOG_INFO, yaze::Rom::ReadByteVector(), yaze::Rom::size(), TestRomWithCopy(), and yaze::Rom::title().
Referenced by DrawTestDashboard().
TestRomWithCopy()
absl::Status yaze::test::TestManager::TestRomWithCopy (Rom * source_rom, std::function< absl::Status(Rom *)> test_function)
Definition at line 1508 of file test_manager.cc.
References CreateTestRomCopy(), yaze::Rom::is_loaded(), LOG_INFO, and RETURN_IF_ERROR.
Referenced by TestRomDataIntegrity(), and TestRomSaveLoad().
DisableTest()
void yaze::test::TestManager::DisableTest (const std::string & test_name) inline
Definition at line 245 of file test_manager.h.
References disabled_tests_.
Referenced by DrawTestDashboard().
EnableTest()
void yaze::test::TestManager::EnableTest (const std::string & test_name) inline
Definition at line 248 of file test_manager.h.
References disabled_tests_.
Referenced by DrawTestDashboard().
IsTestEnabled()
bool yaze::test::TestManager::IsTestEnabled (const std::string & test_name) const inline
Definition at line 251 of file test_manager.h.
References disabled_tests_.
Referenced by DrawTestDashboard().
RegisterHarnessTest()
std::string yaze::test::TestManager::RegisterHarnessTest (const std::string & name, const std::string & category)
Definition at line 1635 of file test_manager.cc.
References yaze::test::HarnessTestExecution::category, yaze::test::TestManager::HarnessAggregate::category, yaze::test::HarnessTestExecution::completed_at, GenerateHarnessTestIdLocked(), harness_history_mutex_, yaze::test::kQueued, yaze::test::TestManager::HarnessAggregate::last_run, yaze::test::TestManager::HarnessAggregate::latest_execution, yaze::test::HarnessTestExecution::name, yaze::test::HarnessTestExecution::queued_at, yaze::test::HarnessTestExecution::started_at, yaze::test::HarnessTestExecution::status, yaze::test::HarnessTestExecution::test_id, and TrimHarnessHistoryLocked().
MarkHarnessTestRunning()
void yaze::test::TestManager::MarkHarnessTestRunning (const std::string & test_id)
Definition at line 1665 of file test_manager.cc.
References yaze::test::HarnessTestExecution::category, yaze::test::TestManager::HarnessAggregate::category, harness_history_mutex_, yaze::test::kRunning, yaze::test::TestManager::HarnessAggregate::latest_execution, yaze::test::HarnessTestExecution::name, yaze::test::HarnessTestExecution::started_at, and yaze::test::HarnessTestExecution::status.
MarkHarnessTestCompleted()
void yaze::test::TestManager::MarkHarnessTestCompleted (const std::string & test_id, HarnessTestStatus status, const std::string & error_message = "", const std::vector< std::string > & assertion_failures = {}, const std::vector< std::string > & logs = {}, const std::map< std::string, int32_t > & metrics = {})
Definition at line 1684 of file test_manager.cc.
References yaze::test::HarnessTestExecution::assertion_failures, CaptureFailureContext(), yaze::test::HarnessTestExecution::category, yaze::test::TestManager::HarnessAggregate::category, yaze::test::HarnessTestExecution::completed_at, yaze::test::HarnessTestExecution::duration, yaze::test::HarnessTestExecution::error_message, yaze::test::TestManager::HarnessAggregate::fail_count, harness_history_mutex_, yaze::test::kFailed, yaze::test::kPassed, yaze::test::kTimeout, yaze::test::TestManager::HarnessAggregate::last_run, yaze::test::TestManager::HarnessAggregate::latest_execution, yaze::test::HarnessTestExecution::logs, yaze::test::HarnessTestExecution::metrics, yaze::test::HarnessTestExecution::name, yaze::test::TestManager::HarnessAggregate::pass_count, yaze::test::HarnessTestExecution::queued_at, yaze::test::HarnessTestExecution::started_at, yaze::test::HarnessTestExecution::status, yaze::test::TestManager::HarnessAggregate::total_duration, and yaze::test::TestManager::HarnessAggregate::total_runs.
AppendHarnessTestLog()
void yaze::test::TestManager::AppendHarnessTestLog (const std::string & test_id, const std::string & log_entry)
Definition at line 1741 of file test_manager.cc.
References harness_history_mutex_, yaze::test::TestManager::HarnessAggregate::latest_execution, yaze::test::HarnessTestExecution::logs, and yaze::test::HarnessTestExecution::name.
GetHarnessTestExecution()
absl::StatusOr< HarnessTestExecution > yaze::test::TestManager::GetHarnessTestExecution (const std::string & test_id) const
Definition at line 1757 of file test_manager.cc.
References harness_history_mutex_.
Referenced by yaze::test::TestRecorder::PopulateFinalStatusLocked().
ListHarnessTestSummaries()
std::vector< HarnessTestSummary > yaze::test::TestManager::ListHarnessTestSummaries (const std::string & category_filter = "") const
Definition at line 1770 of file test_manager.cc.
References yaze::test::HarnessTestExecution::completed_at, yaze::test::HarnessTestSummary::fail_count, harness_history_mutex_, yaze::test::HarnessTestSummary::latest_execution, yaze::test::HarnessTestSummary::pass_count, yaze::test::HarnessTestExecution::queued_at, yaze::test::HarnessTestSummary::total_duration, and yaze::test::HarnessTestSummary::total_runs.
Referenced by DrawTestDashboard().
CaptureFailureContext()
void yaze::test::TestManager::CaptureFailureContext (const std::string & test_id)
Definition at line 1839 of file test_manager.cc.
References yaze::core::CaptureWidgetState(), yaze::test::HarnessTestExecution::failure_context, LOG_INFO, LOG_WARN, yaze::test::HarnessTestExecution::logs, yaze::test::HarnessTestExecution::name, yaze::test::HarnessTestExecution::screenshot_path, yaze::test::HarnessTestExecution::screenshot_size_bytes, and yaze::test::HarnessTestExecution::widget_state.
Referenced by MarkHarnessTestCompleted().
ExecuteTestSuite()
absl::Status yaze::test::TestManager::ExecuteTestSuite (TestSuite * suite) private
Definition at line 285 of file test_manager.cc.
References CollectResourceStats(), last_results_, and yaze::test::TestSuite::RunTests().
Referenced by RunAllTests(), RunTestsByCategory(), and RunTestSuite().
UpdateProgress()
void yaze::test::TestManager::UpdateProgress () private
Definition at line 302 of file test_manager.cc.
References progress_, and test_suites_.
Referenced by RunAllTests(), and RunTestsByCategory().
CollectResourceStats()
void yaze::test::TestManager::CollectResourceStats () private
Definition at line 318 of file test_manager.cc.
References yaze::test::ResourceStats::frame_rate, yaze::gfx::Arena::Get(), yaze::test::ResourceStats::memory_usage_mb, resource_history_, yaze::test::ResourceStats::surface_count, yaze::test::ResourceStats::texture_count, and yaze::test::ResourceStats::timestamp.
Referenced by ExecuteTestSuite(), and UpdateResourceStats().
TrimResourceHistory()
void yaze::test::TestManager::TrimResourceHistory () private
Definition at line 337 of file test_manager.cc.
References kMaxResourceHistorySize, and resource_history_.
Referenced by UpdateResourceStats().
ABSL_GUARDED_BY() [1/3]
std::unordered_map< std::string, HarnessTestExecution > harness_history_ yaze::test::TestManager::ABSL_GUARDED_BY (harness_history_mutex_) private
ABSL_GUARDED_BY() [2/3]
std::unordered_map< std::string, HarnessAggregate > harness_aggregates_ yaze::test::TestManager::ABSL_GUARDED_BY (harness_history_mutex_) private
ABSL_GUARDED_BY() [3/3]
std::deque< std::string > harness_history_order_ yaze::test::TestManager::ABSL_GUARDED_BY (harness_history_mutex_) private
GenerateHarnessTestIdLocked()
std::string yaze::test::TestManager::GenerateHarnessTestIdLocked (absl::string_view prefix) private
Definition at line 1806 of file test_manager.cc.
Referenced by RegisterHarnessTest().
TrimHarnessHistoryLocked()
void yaze::test::TestManager::TrimHarnessHistoryLocked () private
Definition at line 1828 of file test_manager.cc.
Referenced by RegisterHarnessTest().
Member Data Documentation
test_suites_
std::vector<std::unique_ptr<TestSuite> > yaze::test::TestManager::test_suites_ private
Definition at line 297 of file test_manager.h.
Referenced by GetTestSuiteNames(), RegisterTestSuite(), RunAllTests(), RunTestsByCategory(), and UpdateProgress().
suite_lookup_
std::unordered_map<std::string, TestSuite*> yaze::test::TestManager::suite_lookup_ private
Definition at line 298 of file test_manager.h.
Referenced by GetTestSuite(), RegisterTestSuite(), and RunTestSuite().
last_results_
TestResults yaze::test::TestManager::last_results_ private
Definition at line 300 of file test_manager.h.
Referenced by ClearResults(), DrawTestDashboard(), ExecuteTestSuite(), GetLastResults(), RunAllTests(), RunTestsByCategory(), and RunTestSuite().
is_running_
bool yaze::test::TestManager::is_running_ = false private
Definition at line 301 of file test_manager.h.
Referenced by DrawTestDashboard(), IsTestRunning(), RunAllTests(), RunTestsByCategory(), and RunTestSuite().
current_test_name_
std::string yaze::test::TestManager::current_test_name_ private
Definition at line 302 of file test_manager.h.
Referenced by DrawTestDashboard(), GetCurrentTestName(), RunAllTests(), RunTestsByCategory(), and RunTestSuite().
progress_
float yaze::test::TestManager::progress_ = 0.0f private
Definition at line 303 of file test_manager.h.
Referenced by DrawTestDashboard(), GetProgress(), RunAllTests(), RunTestsByCategory(), RunTestSuite(), and UpdateProgress().
max_concurrent_tests_
size_t yaze::test::TestManager::max_concurrent_tests_ = 1 private
Definition at line 306 of file test_manager.h.
Referenced by SetMaxConcurrentTests().
test_timeout_
std::chrono::seconds yaze::test::TestManager::test_timeout_ {30} private
Definition at line 307 of file test_manager.h.
Referenced by SetTestTimeout().
resource_history_
std::vector<ResourceStats> yaze::test::TestManager::resource_history_ private
Definition at line 310 of file test_manager.h.
Referenced by CollectResourceStats(), DrawTestDashboard(), GetResourceHistory(), and TrimResourceHistory().
kMaxResourceHistorySize
constexpr size_t yaze::test::TestManager::kMaxResourceHistorySize = 1000 static constexpr private
Definition at line 311 of file test_manager.h.
Referenced by TrimResourceHistory().
show_dashboard_
bool yaze::test::TestManager::show_dashboard_ = false private
Definition at line 319 of file test_manager.h.
Referenced by DrawTestDashboard().
show_resource_monitor_
bool yaze::test::TestManager::show_resource_monitor_ = false private
Definition at line 320 of file test_manager.h.
Referenced by DrawTestDashboard().
test_filter_
std::string yaze::test::TestManager::test_filter_ private
Definition at line 321 of file test_manager.h.
Referenced by DrawTestDashboard().
category_filter_
TestCategory yaze::test::TestManager::category_filter_ = TestCategory::kUnit private
Definition at line 322 of file test_manager.h.
Referenced by DrawTestDashboard().
current_rom_
Rom* yaze::test::TestManager::current_rom_ = nullptr private
Definition at line 325 of file test_manager.h.
Referenced by DrawTestDashboard(), GetCurrentRom(), RefreshCurrentRom(), and SetCurrentRom().
show_google_tests_
bool yaze::test::TestManager::show_google_tests_ = false private
Definition at line 329 of file test_manager.h.
Referenced by DrawTestDashboard().
show_rom_test_results_
bool yaze::test::TestManager::show_rom_test_results_ = false private
Definition at line 330 of file test_manager.h.
Referenced by DrawTestDashboard().
show_rom_file_dialog_
bool yaze::test::TestManager::show_rom_file_dialog_ = false private
Definition at line 331 of file test_manager.h.
Referenced by DrawTestDashboard().
show_test_session_dialog_
bool yaze::test::TestManager::show_test_session_dialog_ = false private
Definition at line 332 of file test_manager.h.
Referenced by DrawTestDashboard(), and OfferTestSessionCreation().
show_test_configuration_
bool yaze::test::TestManager::show_test_configuration_ = false private
Definition at line 333 of file test_manager.h.
Referenced by DrawTestDashboard().
test_rom_path_for_session_
std::string yaze::test::TestManager::test_rom_path_for_session_ private
Definition at line 334 of file test_manager.h.
Referenced by DrawTestDashboard(), and OfferTestSessionCreation().
disabled_tests_
std::unordered_map<std::string, bool> yaze::test::TestManager::disabled_tests_ private
Definition at line 337 of file test_manager.h.
Referenced by DisableTest(), EnableTest(), and IsTestEnabled().
harness_history_limit_
size_t yaze::test::TestManager::harness_history_limit_ = 200 private
Definition at line 356 of file test_manager.h.
harness_history_mutex_
absl::Mutex yaze::test::TestManager::harness_history_mutex_ mutable private
Definition at line 357 of file test_manager.h.
Referenced by AppendHarnessTestLog(), GetHarnessTestExecution(), ListHarnessTestSummaries(), MarkHarnessTestCompleted(), MarkHarnessTestRunning(), and RegisterHarnessTest().
The documentation for this class was generated from the following files:
src/app/test/test_manager.h
src/app/test/test_manager.cc