yaze: yaze::cli::agent::anonymous_namespace{general_commands.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{general_commands.cc} Namespace Reference
Classes
struct DescribeOptions
Functions
absl::Status TryLoadProjectAndLabels (Rom &rom)
absl::Status EnsureRomLoaded (Rom &rom, const std::string &command)
absl::StatusOr< DescribeOptions > ParseDescribeArgs (const std::vector< std::string > &args)
Function Documentation
TryLoadProjectAndLabels()
absl::Status yaze::cli::agent::anonymous_namespace{general_commands.cc}::TryLoadProjectAndLabels (Rom & rom)
Definition at line 63 of file general_commands.cc.
References yaze::core::YazeProject::InitializeEmbeddedLabels(), yaze::core::ResourceLabelManager::labels_, yaze::core::YazeProject::labels_filename, yaze::core::YazeProject::name, yaze::core::YazeProject::Open(), yaze::Rom::resource_label(), yaze::core::YazeProject::resource_labels, TryLoadProjectAndLabels(), and yaze::core::YazeProject::use_embedded_labels.
Referenced by TryLoadProjectAndLabels().
EnsureRomLoaded()
absl::Status yaze::cli::agent::anonymous_namespace{general_commands.cc}::EnsureRomLoaded (Rom & rom, const std::string & command)
Definition at line 101 of file general_commands.cc.
References EnsureRomLoaded(), yaze::Rom::is_loaded(), and yaze::Rom::LoadFromFile().
Referenced by EnsureRomLoaded().
ParseDescribeArgs()
absl::StatusOr< DescribeOptions > yaze::cli::agent::anonymous_namespace{general_commands.cc}::ParseDescribeArgs (const std::vector< std::string > & args)
Definition at line 125 of file general_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::agent::anonymous_namespace{general_commands.cc}::DescribeOptions::format, yaze::cli::agent::anonymous_namespace{general_commands.cc}::DescribeOptions::last_updated, yaze::cli::agent::anonymous_namespace{general_commands.cc}::DescribeOptions::output_path, ParseDescribeArgs(), yaze::cli::agent::anonymous_namespace{general_commands.cc}::DescribeOptions::resource, and yaze::cli::agent::anonymous_namespace{general_commands.cc}::DescribeOptions::version.
Referenced by ParseDescribeArgs().