yaze: yaze::cli::agent::anonymous_namespace{test_commands.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{test_commands.cc} Namespace Reference
Classes
struct ReplayCommandOptions
Functions
void AttachExitCode (absl::Status *status, int exit_code)
std::string TrimWhitespace (absl::string_view value)
bool IsInteractiveInput ()
std::string PromptWithDefault (const std::string &prompt, const std::string &default_value, bool allow_empty=true)
std::string PromptRequired (const std::string &prompt, const std::string &default_value=std::string())
int PromptInt (const std::string &prompt, int default_value, int min_value)
bool PromptYesNo (const std::string &prompt, bool default_value)
std::vector< std::string > ParseCommaSeparated (absl::string_view input)
bool ParseKeyValueEntry (const std::string &input, std::string *key, std::string *value)
std::string DeriveTestNameFromPath (const std::string &path)
std::string OutcomeToLabel (TestCaseOutcome outcome)
std::string BuildWidgetCatalogJson (const DiscoverWidgetsResult &catalog)
absl::Status WriteWidgetCatalog (const DiscoverWidgetsResult &catalog, const std::string &output_path)
absl::StatusOr< ReplayCommandOptions > ParseReplayArgs (const std::vector< std::string > &args)
void PrintReplayTextSummary (const ReplayCommandOptions &options, const ReplayTestResult &result)
void PrintReplayJsonSummary (const ReplayCommandOptions &options, const ReplayTestResult &result)
absl::Status HandleTestReplayCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestRunCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestStatusCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestListCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestResultsCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestSuiteRunCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestSuiteValidateCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestSuiteCreateCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleTestSuiteCommand (const std::vector< std::string > &arg_vec)
Variables
constexpr char kExitCodePayloadKey [] = "yaze.cli.exit_code"
Function Documentation
AttachExitCode()
void yaze::cli::agent::anonymous_namespace{test_commands.cc}::AttachExitCode (absl::Status * status, int exit_code)
Definition at line 60 of file test_commands.cc.
References AttachExitCode(), and kExitCodePayloadKey.
Referenced by AttachExitCode(), HandleTestReplayCommand(), HandleTestSuiteRunCommand(), and HandleTestSuiteValidateCommand().
TrimWhitespace()
std::string yaze::cli::agent::anonymous_namespace{test_commands.cc}::TrimWhitespace (absl::string_view value)
Definition at line 68 of file test_commands.cc.
References TrimWhitespace().
Referenced by HandleTestSuiteCreateCommand(), ParseCommaSeparated(), ParseKeyValueEntry(), PromptWithDefault(), PromptYesNo(), and TrimWhitespace().
IsInteractiveInput()
bool yaze::cli::agent::anonymous_namespace{test_commands.cc}::IsInteractiveInput ()
Definition at line 72 of file test_commands.cc.
References IsInteractiveInput().
Referenced by HandleTestSuiteCreateCommand(), and IsInteractiveInput().
PromptWithDefault()
std::string yaze::cli::agent::anonymous_namespace{test_commands.cc}::PromptWithDefault (const std::string & prompt, const std::string & default_value, bool allow_empty = true)
Definition at line 80 of file test_commands.cc.
References PromptWithDefault(), and TrimWhitespace().
Referenced by HandleTestSuiteCreateCommand(), PromptInt(), PromptRequired(), and PromptWithDefault().
PromptRequired()
std::string yaze::cli::agent::anonymous_namespace{test_commands.cc}::PromptRequired (const std::string & prompt, const std::string & default_value = std::string())
Definition at line 109 of file test_commands.cc.
References PromptRequired(), and PromptWithDefault().
Referenced by HandleTestSuiteCreateCommand(), and PromptRequired().
PromptInt()
int yaze::cli::agent::anonymous_namespace{test_commands.cc}::PromptInt (const std::string & prompt, int default_value, int min_value)
Definition at line 114 of file test_commands.cc.
References PromptInt(), and PromptWithDefault().
Referenced by HandleTestSuiteCreateCommand(), and PromptInt().
PromptYesNo()
bool yaze::cli::agent::anonymous_namespace{test_commands.cc}::PromptYesNo (const std::string & prompt, bool default_value)
Definition at line 129 of file test_commands.cc.
References PromptYesNo(), and TrimWhitespace().
Referenced by HandleTestSuiteCreateCommand(), and PromptYesNo().
ParseCommaSeparated()
std::vector< std::string > yaze::cli::agent::anonymous_namespace{test_commands.cc}::ParseCommaSeparated (absl::string_view input)
Definition at line 153 of file test_commands.cc.
References ParseCommaSeparated(), and TrimWhitespace().
Referenced by HandleTestSuiteCreateCommand(), and ParseCommaSeparated().
ParseKeyValueEntry()
bool yaze::cli::agent::anonymous_namespace{test_commands.cc}::ParseKeyValueEntry (const std::string & input, std::string * key, std::string * value)
Definition at line 164 of file test_commands.cc.
References equals(), ParseKeyValueEntry(), and TrimWhitespace().
Referenced by HandleTestSuiteCreateCommand(), and ParseKeyValueEntry().
DeriveTestNameFromPath()
std::string yaze::cli::agent::anonymous_namespace{test_commands.cc}::DeriveTestNameFromPath (const std::string & path)
Definition at line 176 of file test_commands.cc.
References DeriveTestNameFromPath().
Referenced by DeriveTestNameFromPath(), and HandleTestSuiteCreateCommand().
OutcomeToLabel()
std::string yaze::cli::agent::anonymous_namespace{test_commands.cc}::OutcomeToLabel (TestCaseOutcome outcome)
Definition at line 188 of file test_commands.cc.
References yaze::cli::kError, yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kSkipped, and OutcomeToLabel().
Referenced by HandleTestRunCommand(), and OutcomeToLabel().
BuildWidgetCatalogJson()
std::string yaze::cli::agent::anonymous_namespace{test_commands.cc}::BuildWidgetCatalogJson (const DiscoverWidgetsResult & catalog)
Definition at line 202 of file test_commands.cc.
References BuildWidgetCatalogJson(), yaze::cli::DiscoverWidgetsResult::generated_at, yaze::cli::agent::JsonEscape(), yaze::cli::DiscoverWidgetsResult::total_widgets, and yaze::cli::DiscoverWidgetsResult::windows.
Referenced by BuildWidgetCatalogJson(), and WriteWidgetCatalog().
WriteWidgetCatalog()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::WriteWidgetCatalog (const DiscoverWidgetsResult & catalog, const std::string & output_path)
Definition at line 274 of file test_commands.cc.
References BuildWidgetCatalogJson(), and WriteWidgetCatalog().
Referenced by WriteWidgetCatalog().
ParseReplayArgs()
absl::StatusOr< ReplayCommandOptions > yaze::cli::agent::anonymous_namespace{test_commands.cc}::ParseReplayArgs (const std::vector< std::string > & args)
Definition at line 305 of file test_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::ci_mode, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::host, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::output_format, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::parameters, ParseReplayArgs(), yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::port, and yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::script_path.
Referenced by HandleTestReplayCommand(), and ParseReplayArgs().
PrintReplayTextSummary()
void yaze::cli::agent::anonymous_namespace{test_commands.cc}::PrintReplayTextSummary (const ReplayCommandOptions & options, const ReplayTestResult & result)
Definition at line 420 of file test_commands.cc.
References yaze::cli::ReplayTestResult::assertions, yaze::cli::agent::HarnessAddress(), yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::host, yaze::cli::ReplayTestResult::logs, yaze::cli::ReplayTestResult::message, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::parameters, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::port, PrintReplayTextSummary(), yaze::cli::ReplayTestResult::replay_session_id, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::script_path, yaze::cli::ReplayTestResult::steps_executed, and yaze::cli::ReplayTestResult::success.
Referenced by HandleTestReplayCommand(), and PrintReplayTextSummary().
PrintReplayJsonSummary()
void yaze::cli::agent::anonymous_namespace{test_commands.cc}::PrintReplayJsonSummary (const ReplayCommandOptions & options, const ReplayTestResult & result)
Definition at line 460 of file test_commands.cc.
References yaze::cli::ReplayTestResult::assertions, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::ci_mode, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::host, yaze::cli::agent::JsonEscape(), yaze::cli::ReplayTestResult::logs, yaze::cli::ReplayTestResult::message, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::parameters, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::port, PrintReplayJsonSummary(), yaze::cli::ReplayTestResult::replay_session_id, yaze::cli::agent::anonymous_namespace{test_commands.cc}::ReplayCommandOptions::script_path, yaze::cli::ReplayTestResult::steps_executed, and yaze::cli::ReplayTestResult::success.
Referenced by HandleTestReplayCommand(), and PrintReplayJsonSummary().
HandleTestReplayCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestReplayCommand (const std::vector< std::string > & arg_vec)
Definition at line 521 of file test_commands.cc.
References ASSIGN_OR_RETURN, AttachExitCode(), yaze::cli::GuiAutomationClient::Connect(), HandleTestReplayCommand(), yaze::cli::agent::HarnessAddress(), yaze::cli::ReplayTestResult::message, ParseReplayArgs(), PrintReplayJsonSummary(), PrintReplayTextSummary(), yaze::cli::GuiAutomationClient::ReplayTest(), and yaze::cli::ReplayTestResult::success.
Referenced by HandleTestReplayCommand().
HandleTestRunCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestRunCommand (const std::vector< std::string > & arg_vec)
Definition at line 582 of file test_commands.cc.
References yaze::cli::GuiAutomationClient::Assert(), yaze::cli::TestCaseRunResult::assertions, ASSIGN_OR_RETURN, yaze::cli::TestCaseRunResult::attempts, yaze::cli::GuiAutomationClient::Click(), yaze::cli::TestSuiteDefinition::config, yaze::cli::GuiAutomationClient::Connect(), yaze::cli::TestGroupDefinition::depends_on, yaze::cli::TestCaseRunResult::duration, yaze::cli::TestSuiteRunSummary::errors, yaze::cli::TestSuiteRunSummary::failed, yaze::cli::TestWorkflowGenerator::GenerateWorkflow(), yaze::cli::TestCaseRunResult::group, yaze::cli::TestCaseDefinition::group_name, yaze::cli::TestSuiteDefinition::groups, HandleTestRunCommand(), yaze::cli::agent::HarnessAddress(), yaze::cli::agent::JsonEscape(), yaze::cli::kAssert, yaze::cli::kClick, yaze::cli::kError, yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kScreenshot, yaze::cli::kSkipped, yaze::cli::kType, yaze::cli::kWait, yaze::cli::TestCaseRunResult::logs, yaze::cli::TestCaseRunResult::message, yaze::cli::TestCaseDefinition::name, yaze::cli::TestGroupDefinition::name, yaze::cli::TestSuiteDefinition::name, yaze::cli::TestCaseRunResult::outcome, OutcomeToLabel(), yaze::cli::TestCaseDefinition::parameters, yaze::cli::TestSuiteRunSummary::passed, yaze::cli::TestCaseRunResult::replay_session_id, yaze::cli::GuiAutomationClient::ReplayTest(), yaze::cli::TestSuiteRunSummary::results, yaze::cli::TestCaseRunResult::retries, yaze::cli::TestSuiteConfig::retry_on_failure, yaze::cli::GuiAutomationClient::Screenshot(), yaze::cli::TestCaseDefinition::script_path, yaze::cli::TestSuiteRunSummary::skipped, yaze::cli::TestCaseRunResult::start_time, yaze::cli::TestSuiteRunSummary::started_at, yaze::cli::TestSuiteRunSummary::suite, yaze::cli::TestCaseDefinition::tags, yaze::cli::TestCaseRunResult::test, yaze::cli::TestGroupDefinition::tests, yaze::cli::TestSuiteRunSummary::total_duration, yaze::cli::GuiAutomationClient::Type(), yaze::cli::GuiAutomationClient::Wait(), and yaze::cli::agent::YamlQuote().
Referenced by HandleTestRunCommand().
HandleTestStatusCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestStatusCommand (const std::vector< std::string > & arg_vec)
Definition at line 1505 of file test_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::GuiAutomationClient::Connect(), yaze::cli::agent::FormatOptionalTime(), yaze::cli::GuiAutomationClient::GetTestStatus(), HandleTestStatusCommand(), yaze::cli::agent::HarnessAddress(), yaze::cli::agent::IsTerminalStatus(), RETURN_IF_ERROR, and yaze::cli::agent::TestRunStatusToString().
Referenced by HandleTestStatusCommand().
HandleTestListCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestListCommand (const std::vector< std::string > & arg_vec)
Definition at line 1602 of file test_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::GuiAutomationClient::Connect(), yaze::cli::agent::FormatOptionalTime(), yaze::cli::GuiAutomationClient::GetTestStatus(), HandleTestListCommand(), yaze::cli::agent::HarnessAddress(), yaze::cli::GuiAutomationClient::ListTests(), yaze::cli::agent::ParseStatusFilter(), RETURN_IF_ERROR, and yaze::cli::agent::TestRunStatusToString().
Referenced by HandleTestListCommand().
HandleTestResultsCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestResultsCommand (const std::vector< std::string > & arg_vec)
Definition at line 1750 of file test_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::GuiAutomationClient::Connect(), yaze::cli::agent::FormatOptionalTime(), yaze::cli::GuiAutomationClient::GetTestResults(), HandleTestResultsCommand(), yaze::cli::agent::HarnessAddress(), yaze::cli::agent::JsonEscape(), RETURN_IF_ERROR, and yaze::cli::agent::YamlQuote().
Referenced by HandleTestResultsCommand().
HandleTestSuiteRunCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestSuiteRunCommand (const std::vector< std::string > & arg_vec)
Definition at line 1979 of file test_commands.cc.
References ASSIGN_OR_RETURN, AttachExitCode(), yaze::cli::BuildTextSummary(), yaze::cli::GuiAutomationClient::Connect(), yaze::cli::TestSuiteRunSummary::errors, yaze::cli::TestSuiteRunSummary::failed, HandleTestSuiteRunCommand(), yaze::cli::agent::HarnessAddress(), yaze::cli::LoadTestSuiteFromFile(), RETURN_IF_ERROR, and yaze::cli::WriteJUnitReport().
Referenced by HandleTestSuiteCommand(), and HandleTestSuiteRunCommand().
HandleTestSuiteValidateCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestSuiteValidateCommand (const std::vector< std::string > & arg_vec)
Definition at line 2051 of file test_commands.cc.
References AttachExitCode(), yaze::cli::TestSuiteDefinition::groups, HandleTestSuiteValidateCommand(), yaze::cli::LoadTestSuiteFromFile(), and yaze::cli::TestSuiteDefinition::name.
Referenced by HandleTestSuiteCommand(), and HandleTestSuiteValidateCommand().
HandleTestSuiteCreateCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestSuiteCreateCommand (const std::vector< std::string > & arg_vec)
Definition at line 2100 of file test_commands.cc.
References yaze::cli::TestSuiteDefinition::config, yaze::cli::TestGroupDefinition::depends_on, DeriveTestNameFromPath(), yaze::cli::TestCaseDefinition::description, yaze::cli::TestGroupDefinition::description, yaze::cli::TestSuiteDefinition::description, yaze::cli::TestCaseDefinition::group_name, yaze::cli::TestSuiteDefinition::groups, HandleTestSuiteCreateCommand(), yaze::cli::TestCaseDefinition::id, IsInteractiveInput(), yaze::cli::TestCaseDefinition::name, yaze::cli::TestGroupDefinition::name, yaze::cli::TestSuiteDefinition::name, yaze::cli::TestSuiteConfig::parallel_execution, yaze::cli::TestCaseDefinition::parameters, ParseCommaSeparated(), ParseKeyValueEntry(), PromptInt(), PromptRequired(), PromptWithDefault(), PromptYesNo(), yaze::cli::TestSuiteConfig::retry_on_failure, yaze::cli::TestCaseDefinition::script_path, yaze::cli::TestCaseDefinition::tags, yaze::cli::TestGroupDefinition::tests, yaze::cli::TestSuiteConfig::timeout_seconds, TrimWhitespace(), yaze::cli::TestSuiteDefinition::version, and yaze::cli::WriteTestSuiteToFile().
Referenced by HandleTestSuiteCommand(), and HandleTestSuiteCreateCommand().
HandleTestSuiteCommand()
absl::Status yaze::cli::agent::anonymous_namespace{test_commands.cc}::HandleTestSuiteCommand (const std::vector< std::string > & arg_vec)
Definition at line 2299 of file test_commands.cc.
References HandleTestSuiteCommand(), HandleTestSuiteCreateCommand(), HandleTestSuiteRunCommand(), and HandleTestSuiteValidateCommand().
Referenced by HandleTestSuiteCommand().
Variable Documentation
kExitCodePayloadKey
constexpr char yaze::cli::agent::anonymous_namespace{test_commands.cc}::kExitCodePayloadKey[] = "yaze.cli.exit_code" constexpr
Definition at line 58 of file test_commands.cc.
Referenced by AttachExitCode().