yaze: yaze::editor::OverworldGraphicsManager Class Reference
yaze::editor::OverworldGraphicsManager Class Reference
Manages all graphics-related operations for the Overworld Editor.
#include <overworld_graphics_manager.h>
Public Member Functions
OverworldGraphicsManager (zelda3::Overworld *overworld, Rom *rom, std::array< gfx::Bitmap, zelda3::kNumOverworldMaps > *maps_bmp, gfx::Bitmap *tile16_blockset_bmp, gfx::Bitmap *current_gfx_bmp, std::vector< gfx::Bitmap > *sprite_previews, gfx::SnesPalette *palette, Tilemap *tile16_blockset)
absl::Status LoadGraphics ()
Load all overworld graphics (maps, tilesets, sprites)
absl::Status LoadSpriteGraphics ()
Load sprite graphics for all overworld maps.
void ProcessDeferredTextures ()
Process deferred texture creation (called per frame)
void EnsureMapTexture (int map_index)
Ensure a specific map has a texture created.
void RefreshOverworldMap ()
Refresh the current overworld map.
void RefreshOverworldMapOnDemand (int map_index)
Refresh a specific map on-demand (only if visible)
void RefreshChildMap (int map_index)
Refresh a child map (legacy method)
void RefreshChildMapOnDemand (int map_index)
Refresh a child map with selective updates.
void RefreshMultiAreaMapsSafely (int map_index, zelda3::OverworldMap *map)
Safely refresh multi-area maps (large, wide, tall)
absl::Status RefreshMapPalette ()
Refresh the palette for the current map.
absl::Status RefreshTile16Blockset ()
Refresh the tile16 blockset.
void ForceRefreshGraphics (int map_index)
Force a graphics refresh for a specific map.
void set_current_map (int map_index)
void set_current_world (int world_index)
void set_current_blockset (uint8_t blockset)
int current_map () const
int current_world () const
uint8_t current_blockset () const
bool all_gfx_loaded () const
bool map_blockset_loaded () const
Private Attributes
zelda3::Overworld * overworld_
Rom * rom_
std::array< gfx::Bitmap, zelda3::kNumOverworldMaps > * maps_bmp_
gfx::Bitmap * tile16_blockset_bmp_
gfx::Bitmap * current_gfx_bmp_
std::vector< gfx::Bitmap > * sprite_previews_
gfx::SnesPalette * palette_
Tilemap * tile16_blockset_
int current_map_ = 0
int current_world_ = 0
uint8_t current_blockset_ = 0
bool all_gfx_loaded_ = false
bool map_blockset_loaded_ = false
std::vector< gfx::Bitmap * > deferred_map_textures_
std::mutex deferred_textures_mutex_
Detailed Description
Manages all graphics-related operations for the Overworld Editor.
This class handles:
Graphics loading and initialization
Sprite graphics loading
Deferred texture processing for smooth loading
Map texture management
Map refreshing (full and on-demand)
Palette refreshing
Tile16 blockset refreshing
Multi-area map coordination
Separating graphics management from the main OverworldEditor improves:
Code organization and maintainability
Performance optimization opportunities
Testing and debugging
Clear separation of concerns
Definition at line 41 of file overworld_graphics_manager.h.
Constructor & Destructor Documentation
OverworldGraphicsManager()
yaze::editor::OverworldGraphicsManager::OverworldGraphicsManager (zelda3::Overworld * overworld, Rom * rom, std::array< gfx::Bitmap, zelda3::kNumOverworldMaps > * maps_bmp, gfx::Bitmap * tile16_blockset_bmp, gfx::Bitmap * current_gfx_bmp, std::vector< gfx::Bitmap > * sprite_previews, gfx::SnesPalette * palette, Tilemap * tile16_blockset) inline
Definition at line 43 of file overworld_graphics_manager.h.
Member Function Documentation
LoadGraphics()
absl::Status yaze::editor::OverworldGraphicsManager::LoadGraphics ()
Load all overworld graphics (maps, tilesets, sprites)
This uses a multi-phase loading strategy:
Phase 1: Create bitmaps without textures
Phase 2: Create bitmaps for essential maps only
Phase 3: Create textures for visible maps
Deferred loading for remaining maps
Definition at line 24 of file overworld_graphics_manager.cc.
References all_gfx_loaded_, yaze::core::Renderer::CreateBitmapWithoutTexture(), yaze::gfx::CreateTilemap(), yaze::zelda3::Overworld::current_area_palette(), current_gfx_bmp_, yaze::zelda3::Overworld::current_graphics(), yaze::zelda3::Overworld::current_map_bitmap_data(), deferred_map_textures_, yaze::core::FeatureFlags::get(), yaze::core::Renderer::Get(), yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kNumTile16Individual, yaze::editor::kOverworldMapSize, yaze::zelda3::kSpecialWorldMapIdStart, yaze::editor::kTile16Size, yaze::zelda3::Overworld::Load(), LoadSpriteGraphics(), LOG_ERROR, LOG_INFO, map_blockset_loaded_, maps_bmp_, overworld_, palette_, yaze::core::Renderer::RenderBitmap(), RETURN_IF_ERROR, rom_, yaze::zelda3::Overworld::set_current_map(), tile16_blockset_, tile16_blockset_bmp_, and yaze::zelda3::Overworld::tile16_blockset_data().
LoadSpriteGraphics()
absl::Status yaze::editor::OverworldGraphicsManager::LoadSpriteGraphics ()
Load sprite graphics for all overworld maps.
Definition at line 143 of file overworld_graphics_manager.cc.
References yaze::core::Renderer::Get(), yaze::zelda3::Overworld::mutable_sprites(), overworld_, palette_, yaze::core::Renderer::RenderBitmap(), and sprite_previews_.
Referenced by LoadGraphics().
ProcessDeferredTextures()
void yaze::editor::OverworldGraphicsManager::ProcessDeferredTextures ()
Process deferred texture creation (called per frame)
Creates textures gradually to avoid frame drops. Prioritizes textures for the current world and visible maps.
Definition at line 168 of file overworld_graphics_manager.cc.
References current_map_, current_world_, deferred_map_textures_, deferred_textures_mutex_, yaze::core::Renderer::Get(), yaze::zelda3::kNumOverworldMaps, maps_bmp_, RefreshOverworldMapOnDemand(), and yaze::core::Renderer::RenderBitmap().
EnsureMapTexture()
void yaze::editor::OverworldGraphicsManager::EnsureMapTexture (int map_index)
Ensure a specific map has a texture created.
Parameters
map_index Index of the map to ensure texture for
Definition at line 259 of file overworld_graphics_manager.cc.
References yaze::zelda3::Overworld::current_area_palette(), yaze::zelda3::Overworld::current_map_bitmap_data(), deferred_map_textures_, deferred_textures_mutex_, yaze::zelda3::Overworld::EnsureMapBuilt(), yaze::core::Renderer::Get(), yaze::zelda3::kNumOverworldMaps, yaze::editor::kOverworldMapSize, LOG_ERROR, overworld_, yaze::core::Renderer::RenderBitmap(), and yaze::zelda3::Overworld::set_current_map().
Referenced by RefreshChildMapOnDemand(), and RefreshMultiAreaMapsSafely().
RefreshOverworldMap()
void yaze::editor::OverworldGraphicsManager::RefreshOverworldMap ()
Refresh the current overworld map.
Definition at line 306 of file overworld_graphics_manager.cc.
References current_map_, and RefreshOverworldMapOnDemand().
RefreshOverworldMapOnDemand()
void yaze::editor::OverworldGraphicsManager::RefreshOverworldMapOnDemand (int map_index)
Refresh a specific map on-demand (only if visible)
Parameters
map_index Index of the map to refresh
Definition at line 311 of file overworld_graphics_manager.cc.
References current_map_, current_world_, yaze::zelda3::kNumOverworldMaps, and RefreshChildMapOnDemand().
Referenced by ProcessDeferredTextures(), and RefreshOverworldMap().
RefreshChildMap()
void yaze::editor::OverworldGraphicsManager::RefreshChildMap (int map_index)
Refresh a child map (legacy method)
Parameters
map_index Index of the map to refresh
Definition at line 331 of file overworld_graphics_manager.cc.
References current_world_, yaze::zelda3::Overworld::GetMapTiles(), yaze::zelda3::Overworld::mutable_overworld_map(), yaze::zelda3::Overworld::mutable_tiles16(), overworld_, PRINT_IF_ERROR, and yaze::zelda3::Overworld::tiles16().
RefreshChildMapOnDemand()
void yaze::editor::OverworldGraphicsManager::RefreshChildMapOnDemand (int map_index)
Refresh a child map with selective updates.
Parameters
map_index Index of the map to refresh
Definition at line 346 of file overworld_graphics_manager.cc.
References current_world_, EnsureMapTexture(), yaze::core::Renderer::Get(), yaze::zelda3::Overworld::GetMapTiles(), LOG_ERROR, LOG_WARN, maps_bmp_, yaze::zelda3::Overworld::mutable_overworld_map(), yaze::zelda3::Overworld::mutable_tiles16(), overworld_, yaze::zelda3::OverworldCustomASMHasBeenApplied, RefreshMultiAreaMapsSafely(), yaze::zelda3::Overworld::tiles16(), and yaze::core::Renderer::UpdateBitmap().
Referenced by RefreshOverworldMapOnDemand().
RefreshMultiAreaMapsSafely()
void yaze::editor::OverworldGraphicsManager::RefreshMultiAreaMapsSafely (int map_index, zelda3::OverworldMap * map)
Safely refresh multi-area maps (large, wide, tall)
Handles coordination of multi-area maps without recursion.
Parameters
map_index Index of the map to refresh
map Pointer to the OverworldMap object
Definition at line 416 of file overworld_graphics_manager.cc.
References yaze::zelda3::OverworldMap::area_size(), yaze::zelda3::Overworld::current_area_palette(), current_map_, current_world_, EnsureMapTexture(), yaze::core::Renderer::Get(), yaze::zelda3::Overworld::GetMapTiles(), yaze::zelda3::kNumOverworldMaps, LOG_DEBUG, LOG_ERROR, LOG_WARN, maps_bmp_, yaze::zelda3::Overworld::mutable_overworld_map(), yaze::zelda3::Overworld::mutable_tiles16(), overworld_, yaze::zelda3::OverworldMap::parent(), yaze::zelda3::Overworld::tiles16(), and yaze::core::Renderer::UpdateBitmap().
Referenced by RefreshChildMapOnDemand().
RefreshMapPalette()
absl::Status yaze::editor::OverworldGraphicsManager::RefreshMapPalette ()
Refresh the palette for the current map.
Also handles palette updates for multi-area maps.
Definition at line 564 of file overworld_graphics_manager.cc.
References yaze::zelda3::Overworld::current_area_palette(), current_map_, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::mutable_overworld_map(), overworld_, yaze::zelda3::Overworld::overworld_map(), yaze::zelda3::OverworldCustomASMHasBeenApplied, and RETURN_IF_ERROR.
RefreshTile16Blockset()
absl::Status yaze::editor::OverworldGraphicsManager::RefreshTile16Blockset ()
Refresh the tile16 blockset.
This should be called whenever area graphics change.
Definition at line 634 of file overworld_graphics_manager.cc.
References yaze::gfx::Tilemap::atlas, yaze::zelda3::Overworld::current_area_palette(), current_blockset_, current_map_, LOG_DEBUG, overworld_, yaze::zelda3::Overworld::overworld_map(), palette_, yaze::zelda3::Overworld::set_current_map(), yaze::gfx::Bitmap::SetPalette(), tile16_blockset_, yaze::zelda3::Overworld::tile16_blockset_data(), and yaze::gfx::UpdateTilemap().
ForceRefreshGraphics()
void yaze::editor::OverworldGraphicsManager::ForceRefreshGraphics (int map_index)
Force a graphics refresh for a specific map.
Marks the map's bitmap as modified and clears the blockset cache to force a full reload on next refresh. Use this when graphics properties change (area_graphics, animated_gfx, custom tilesets).
Parameters
map_index Index of the map to force refresh
Definition at line 652 of file overworld_graphics_manager.cc.
References current_blockset_, yaze::zelda3::kNumOverworldMaps, LOG_INFO, yaze::zelda3::Overworld::mutable_overworld_map(), overworld_, and yaze::zelda3::OverworldCustomASMHasBeenApplied.
set_current_map()
void yaze::editor::OverworldGraphicsManager::set_current_map (int map_index) inline
Definition at line 166 of file overworld_graphics_manager.h.
References current_map_.
set_current_world()
void yaze::editor::OverworldGraphicsManager::set_current_world (int world_index) inline
Definition at line 167 of file overworld_graphics_manager.h.
References current_world_.
set_current_blockset()
void yaze::editor::OverworldGraphicsManager::set_current_blockset (uint8_t blockset) inline
Definition at line 168 of file overworld_graphics_manager.h.
References current_blockset_.
current_map()
int yaze::editor::OverworldGraphicsManager::current_map () const inline
Definition at line 170 of file overworld_graphics_manager.h.
References current_map_.
current_world()
int yaze::editor::OverworldGraphicsManager::current_world () const inline
Definition at line 171 of file overworld_graphics_manager.h.
References current_world_.
current_blockset()
uint8_t yaze::editor::OverworldGraphicsManager::current_blockset () const inline
Definition at line 172 of file overworld_graphics_manager.h.
References current_blockset_.
all_gfx_loaded()
bool yaze::editor::OverworldGraphicsManager::all_gfx_loaded () const inline
Definition at line 174 of file overworld_graphics_manager.h.
References all_gfx_loaded_.
map_blockset_loaded()
bool yaze::editor::OverworldGraphicsManager::map_blockset_loaded () const inline
Definition at line 175 of file overworld_graphics_manager.h.
References map_blockset_loaded_.
Member Data Documentation
overworld_
zelda3::Overworld* yaze::editor::OverworldGraphicsManager::overworld_ private
Definition at line 179 of file overworld_graphics_manager.h.
Referenced by EnsureMapTexture(), ForceRefreshGraphics(), LoadGraphics(), LoadSpriteGraphics(), RefreshChildMap(), RefreshChildMapOnDemand(), RefreshMapPalette(), RefreshMultiAreaMapsSafely(), and RefreshTile16Blockset().
rom_
Rom* yaze::editor::OverworldGraphicsManager::rom_ private
Definition at line 180 of file overworld_graphics_manager.h.
Referenced by LoadGraphics().
maps_bmp_
std::array<gfx::Bitmap, zelda3::kNumOverworldMaps>* yaze::editor::OverworldGraphicsManager::maps_bmp_ private
Definition at line 181 of file overworld_graphics_manager.h.
Referenced by LoadGraphics(), ProcessDeferredTextures(), RefreshChildMapOnDemand(), and RefreshMultiAreaMapsSafely().
tile16_blockset_bmp_
gfx::Bitmap* yaze::editor::OverworldGraphicsManager::tile16_blockset_bmp_ private
Definition at line 182 of file overworld_graphics_manager.h.
Referenced by LoadGraphics().
current_gfx_bmp_
gfx::Bitmap* yaze::editor::OverworldGraphicsManager::current_gfx_bmp_ private
Definition at line 183 of file overworld_graphics_manager.h.
Referenced by LoadGraphics().
sprite_previews_
std::vector<gfx::Bitmap>* yaze::editor::OverworldGraphicsManager::sprite_previews_ private
Definition at line 184 of file overworld_graphics_manager.h.
Referenced by LoadSpriteGraphics().
palette_
gfx::SnesPalette* yaze::editor::OverworldGraphicsManager::palette_ private
Definition at line 185 of file overworld_graphics_manager.h.
Referenced by LoadGraphics(), LoadSpriteGraphics(), and RefreshTile16Blockset().
tile16_blockset_
Tilemap* yaze::editor::OverworldGraphicsManager::tile16_blockset_ private
Definition at line 186 of file overworld_graphics_manager.h.
Referenced by LoadGraphics(), and RefreshTile16Blockset().
current_map_
int yaze::editor::OverworldGraphicsManager::current_map_ = 0 private
Definition at line 189 of file overworld_graphics_manager.h.
Referenced by current_map(), ProcessDeferredTextures(), RefreshMapPalette(), RefreshMultiAreaMapsSafely(), RefreshOverworldMap(), RefreshOverworldMapOnDemand(), RefreshTile16Blockset(), and set_current_map().
current_world_
int yaze::editor::OverworldGraphicsManager::current_world_ = 0 private
Definition at line 190 of file overworld_graphics_manager.h.
Referenced by current_world(), ProcessDeferredTextures(), RefreshChildMap(), RefreshChildMapOnDemand(), RefreshMultiAreaMapsSafely(), RefreshOverworldMapOnDemand(), and set_current_world().
current_blockset_
uint8_t yaze::editor::OverworldGraphicsManager::current_blockset_ = 0 private
Definition at line 191 of file overworld_graphics_manager.h.
Referenced by current_blockset(), ForceRefreshGraphics(), RefreshTile16Blockset(), and set_current_blockset().
all_gfx_loaded_
bool yaze::editor::OverworldGraphicsManager::all_gfx_loaded_ = false private
Definition at line 192 of file overworld_graphics_manager.h.
Referenced by all_gfx_loaded(), and LoadGraphics().
map_blockset_loaded_
bool yaze::editor::OverworldGraphicsManager::map_blockset_loaded_ = false private
Definition at line 193 of file overworld_graphics_manager.h.
Referenced by LoadGraphics(), and map_blockset_loaded().
deferred_map_textures_
std::vector<gfx::Bitmap*> yaze::editor::OverworldGraphicsManager::deferred_map_textures_ private
Definition at line 196 of file overworld_graphics_manager.h.
Referenced by EnsureMapTexture(), LoadGraphics(), and ProcessDeferredTextures().
deferred_textures_mutex_
std::mutex yaze::editor::OverworldGraphicsManager::deferred_textures_mutex_ private
Definition at line 197 of file overworld_graphics_manager.h.
Referenced by EnsureMapTexture(), and ProcessDeferredTextures().
The documentation for this class was generated from the following files:
src/app/editor/overworld/overworld_graphics_manager.h
src/app/editor/overworld/overworld_graphics_manager.cc