yaze: yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc} Namespace Reference
yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc} Namespace Reference
Functions
std::string TrimWhitespace (const std::string &input)
std::string JsonValueToString (const nlohmann::json &value)
std::set< std::string > CollectObjectKeys (const nlohmann::json &array)
std::optional< ChatMessage::TableData > BuildTableData (const nlohmann::json &data)
bool IsExecutableCommand (absl::string_view command)
int CountExecutableCommands (const std::vector< std::string > &commands)
ChatMessage CreateMessage (ChatMessage::Sender sender, const std::string &content)
Function Documentation
TrimWhitespace()
std::string yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::TrimWhitespace (const std::string & input)
Definition at line 42 of file conversational_agent_service.cc.
JsonValueToString()
std::string yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::JsonValueToString (const nlohmann::json & value)
Definition at line 54 of file conversational_agent_service.cc.
References JsonValueToString().
Referenced by BuildTableData(), and JsonValueToString().
CollectObjectKeys()
std::set< std::string > yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::CollectObjectKeys (const nlohmann::json & array)
Definition at line 70 of file conversational_agent_service.cc.
References CollectObjectKeys().
Referenced by BuildTableData(), and CollectObjectKeys().
BuildTableData()
std::optional< ChatMessage::TableData > yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::BuildTableData (const nlohmann::json & data)
Definition at line 83 of file conversational_agent_service.cc.
References BuildTableData(), CollectObjectKeys(), yaze::cli::agent::ChatMessage::TableData::headers, and JsonValueToString().
Referenced by BuildTableData(), and CreateMessage().
IsExecutableCommand()
bool yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::IsExecutableCommand (absl::string_view command)
Definition at line 145 of file conversational_agent_service.cc.
References IsExecutableCommand().
Referenced by CountExecutableCommands(), and IsExecutableCommand().
CountExecutableCommands()
int yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::CountExecutableCommands (const std::vector< std::string > & commands)
Definition at line 149 of file conversational_agent_service.cc.
References CountExecutableCommands(), and IsExecutableCommand().
Referenced by CountExecutableCommands().
CreateMessage()
ChatMessage yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::CreateMessage (ChatMessage::Sender sender, const std::string & content)
Definition at line 159 of file conversational_agent_service.cc.
References BuildTableData(), CreateMessage(), yaze::cli::agent::ChatMessage::json_pretty, yaze::cli::agent::ChatMessage::kAgent, yaze::cli::agent::ChatMessage::message, yaze::cli::agent::ChatMessage::sender, yaze::cli::agent::ChatMessage::table_data, yaze::cli::agent::ChatMessage::timestamp, and yaze::cli::agent::TrimWhitespace().
Referenced by CreateMessage().