yaze: yaze::gfx::ScopedTimer Class Reference
yaze::gfx::ScopedTimer Class Reference
RAII timer for automatic timing management.
#include <performance_profiler.h>
Public Member Functions
ScopedTimer (const std::string &operation_name)
~ScopedTimer ()
ScopedTimer (const ScopedTimer &)=delete
ScopedTimer & operator= (const ScopedTimer &)=delete
ScopedTimer (ScopedTimer &&)=delete
ScopedTimer & operator= (ScopedTimer &&)=delete
Private Attributes
std::string operation_name_
Detailed Description
RAII timer for automatic timing management.
Usage: { ScopedTimer timer("operation_name"); // ... code to time ... } // Timer automatically ends here
Definition at line 191 of file performance_profiler.h.
Constructor & Destructor Documentation
ScopedTimer() [1/3]
yaze::gfx::ScopedTimer::ScopedTimer (const std::string & operation_name) explicit
Definition at line 273 of file performance_profiler.cc.
References yaze::gfx::PerformanceProfiler::Get(), yaze::gfx::PerformanceProfiler::IsEnabled(), yaze::gfx::PerformanceProfiler::IsValid(), operation_name_, and yaze::gfx::PerformanceProfiler::StartTimer().
~ScopedTimer()
yaze::gfx::ScopedTimer::~ScopedTimer ()
Definition at line 280 of file performance_profiler.cc.
References yaze::gfx::PerformanceProfiler::EndTimer(), yaze::gfx::PerformanceProfiler::Get(), yaze::gfx::PerformanceProfiler::IsEnabled(), yaze::gfx::PerformanceProfiler::IsValid(), and operation_name_.
ScopedTimer() [2/3]
yaze::gfx::ScopedTimer::ScopedTimer (const ScopedTimer &) delete
ScopedTimer() [3/3]
yaze::gfx::ScopedTimer::ScopedTimer (ScopedTimer &&) delete
Member Function Documentation
operator=() [1/2]
ScopedTimer & yaze::gfx::ScopedTimer::operator= (const ScopedTimer &) delete
operator=() [2/2]
ScopedTimer & yaze::gfx::ScopedTimer::operator= (ScopedTimer &&) delete
Member Data Documentation
operation_name_
std::string yaze::gfx::ScopedTimer::operation_name_ private
Definition at line 203 of file performance_profiler.h.
Referenced by ScopedTimer(), and ~ScopedTimer().
The documentation for this class was generated from the following files:
src/app/gfx/performance_profiler.h
src/app/gfx/performance_profiler.cc