yaze: yaze::cli::overworld Namespace Reference
yaze::cli::overworld Namespace Reference
Namespaces
namespace anonymous_namespace{overworld_inspect.cc}
Classes
struct EntranceDetails
struct MapSummary
struct OverworldSprite
struct SpriteQuery
struct TileMatch
struct TileSearchOptions
struct TileStatistics
struct WarpEntry
struct WarpQuery
Enumerations
enum class WarpType { kEntrance , kHole , kExit }
Functions
absl::StatusOr< int > ParseNumeric (std::string_view value, int base)
absl::StatusOr< int > ParseWorldSpecifier (std::string_view value)
absl::StatusOr< int > InferWorldFromMapId (int map_id)
std::string WorldName (int world)
std::string WarpTypeName (WarpType type)
absl::StatusOr< MapSummary > BuildMapSummary (zelda3::Overworld &overworld, int map_id)
absl::StatusOr< std::vector< WarpEntry > > CollectWarpEntries (const zelda3::Overworld &overworld, const WarpQuery &query)
absl::StatusOr< std::vector< TileMatch > > FindTileMatches (zelda3::Overworld &overworld, uint16_t tile_id, const TileSearchOptions &options)
absl::StatusOr< std::vector< OverworldSprite > > CollectOverworldSprites (const zelda3::Overworld &overworld, const SpriteQuery &query)
absl::StatusOr< EntranceDetails > GetEntranceDetails (const zelda3::Overworld &overworld, uint8_t entrance_id)
absl::StatusOr< TileStatistics > AnalyzeTileUsage (zelda3::Overworld &overworld, uint16_t tile_id, const TileSearchOptions &options)
Enumeration Type Documentation
WarpType
enum class yaze::cli::overworld::WarpType strong
Enumerator
kEntrance
kHole
kExit
Definition at line 25 of file overworld_inspect.h.
Function Documentation
ParseNumeric()
absl::StatusOr< int > yaze::cli::overworld::ParseNumeric (std::string_view value, int base)
Definition at line 103 of file overworld_inspect.cc.
Referenced by yaze::cli::agent::HandleOverworldDescribeMapCommand(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldGetEntranceCommand(), yaze::cli::agent::HandleOverworldListSpritesCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandleOverworldTileStatsCommand(), yaze::cli::OverworldFindTile::Run(), yaze::cli::OverworldDescribeMap::Run(), and yaze::cli::OverworldListWarps::Run().
ParseWorldSpecifier()
absl::StatusOr< int > yaze::cli::overworld::ParseWorldSpecifier (std::string_view value)
Definition at line 118 of file overworld_inspect.cc.
Referenced by yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldListSpritesCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandleOverworldTileStatsCommand(), yaze::cli::OverworldFindTile::Run(), and yaze::cli::OverworldListWarps::Run().
InferWorldFromMapId()
absl::StatusOr< int > yaze::cli::overworld::InferWorldFromMapId (int map_id)
Definition at line 133 of file overworld_inspect.cc.
References RETURN_IF_ERROR.
Referenced by AnalyzeTileUsage(), BuildMapSummary(), FindTileMatches(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::OverworldFindTile::Run(), and yaze::cli::OverworldListWarps::Run().
WorldName()
std::string yaze::cli::overworld::WorldName (int world)
Definition at line 144 of file overworld_inspect.cc.
Referenced by FindTileMatches(), yaze::cli::agent::HandleOverworldDescribeMapCommand(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldGetEntranceCommand(), yaze::cli::agent::HandleOverworldListSpritesCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandleOverworldTileStatsCommand(), yaze::cli::OverworldFindTile::Run(), yaze::cli::OverworldDescribeMap::Run(), and yaze::cli::OverworldListWarps::Run().
WarpTypeName()
std::string yaze::cli::overworld::WarpTypeName (WarpType type)
Definition at line 157 of file overworld_inspect.cc.
References kEntrance, kExit, and kHole.
Referenced by yaze::cli::agent::HandleOverworldListWarpsCommand(), and yaze::cli::OverworldListWarps::Run().
BuildMapSummary()
absl::StatusOr< MapSummary > yaze::cli::overworld::BuildMapSummary (zelda3::Overworld & overworld, int map_id)
Definition at line 170 of file overworld_inspect.cc.
References yaze::cli::overworld::MapSummary::animated_gfx, yaze::cli::overworld::MapSummary::area_graphics, yaze::cli::overworld::MapSummary::area_music, yaze::cli::overworld::MapSummary::area_palette, yaze::cli::overworld::MapSummary::area_size, yaze::cli::overworld::MapSummary::area_specific_bg_color, ASSIGN_OR_RETURN, yaze::zelda3::Overworld::EnsureMapBuilt(), yaze::cli::overworld::MapSummary::has_overlay, InferWorldFromMapId(), yaze::cli::overworld::MapSummary::is_large_map, yaze::cli::overworld::MapSummary::large_quadrant, yaze::cli::overworld::MapSummary::local_index, yaze::cli::overworld::MapSummary::main_palette, yaze::cli::overworld::MapSummary::map_id, yaze::cli::overworld::MapSummary::map_x, yaze::cli::overworld::MapSummary::map_y, yaze::cli::overworld::MapSummary::message_id, yaze::cli::overworld::MapSummary::overlay_id, yaze::zelda3::Overworld::overworld_map(), yaze::cli::overworld::MapSummary::parent_map, RETURN_IF_ERROR, yaze::cli::overworld::MapSummary::sprite_graphics, yaze::cli::overworld::MapSummary::sprite_palettes, yaze::cli::overworld::MapSummary::static_graphics, yaze::cli::overworld::MapSummary::subscreen_overlay, and yaze::cli::overworld::MapSummary::world.
Referenced by yaze::cli::agent::HandleOverworldDescribeMapCommand(), and yaze::cli::OverworldDescribeMap::Run().
CollectWarpEntries()
absl::StatusOr< std::vector< WarpEntry > > yaze::cli::overworld::CollectWarpEntries (const zelda3::Overworld & overworld, const WarpQuery & query)
Definition at line 226 of file overworld_inspect.cc.
References yaze::cli::overworld::WarpEntry::deleted, yaze::cli::overworld::WarpEntry::entrance_id, yaze::cli::overworld::WarpEntry::entrance_name, yaze::zelda3::Overworld::entrances(), yaze::zelda3::Overworld::holes(), yaze::cli::overworld::WarpEntry::is_hole, kEntrance, kHole, yaze::cli::overworld::WarpEntry::map_id, yaze::cli::overworld::WarpQuery::map_id, yaze::cli::overworld::WarpEntry::tile16_x, yaze::cli::overworld::WarpEntry::tile16_y, yaze::cli::overworld::WarpEntry::type, yaze::cli::overworld::WarpQuery::type, yaze::cli::overworld::WarpEntry::world, and yaze::cli::overworld::WarpQuery::world.
Referenced by yaze::cli::agent::HandleOverworldListWarpsCommand(), and yaze::cli::OverworldListWarps::Run().
FindTileMatches()
absl::StatusOr< std::vector< TileMatch > > yaze::cli::overworld::FindTileMatches (zelda3::Overworld & overworld, uint16_t tile_id, const TileSearchOptions & options)
Definition at line 298 of file overworld_inspect.cc.
References ASSIGN_OR_RETURN, FindTileMatches(), yaze::zelda3::Overworld::GetTile(), InferWorldFromMapId(), yaze::cli::overworld::TileSearchOptions::map_id, RETURN_IF_ERROR, yaze::zelda3::Overworld::set_current_world(), yaze::cli::overworld::TileSearchOptions::world, and WorldName().
Referenced by AnalyzeTileUsage(), FindTileMatches(), yaze::cli::agent::HandleOverworldFindTileCommand(), and yaze::cli::OverworldFindTile::Run().
CollectOverworldSprites()
absl::StatusOr< std::vector< OverworldSprite > > yaze::cli::overworld::CollectOverworldSprites (const zelda3::Overworld & overworld, const SpriteQuery & query)
Definition at line 389 of file overworld_inspect.cc.
References CollectOverworldSprites(), yaze::cli::overworld::OverworldSprite::map_id, yaze::cli::overworld::SpriteQuery::map_id, yaze::cli::overworld::OverworldSprite::sprite_id, yaze::cli::overworld::SpriteQuery::sprite_id, yaze::zelda3::Overworld::sprites(), yaze::cli::overworld::OverworldSprite::world, yaze::cli::overworld::SpriteQuery::world, yaze::cli::overworld::OverworldSprite::x, and yaze::cli::overworld::OverworldSprite::y.
Referenced by CollectOverworldSprites(), and yaze::cli::agent::HandleOverworldListSpritesCommand().
GetEntranceDetails()
absl::StatusOr< EntranceDetails > yaze::cli::overworld::GetEntranceDetails (const zelda3::Overworld & overworld, uint8_t entrance_id)
Definition at line 432 of file overworld_inspect.cc.
References yaze::cli::overworld::EntranceDetails::area_x, yaze::cli::overworld::EntranceDetails::area_y, yaze::cli::overworld::EntranceDetails::entrance_id, yaze::cli::overworld::EntranceDetails::entrance_name, yaze::zelda3::Overworld::entrances(), GetEntranceDetails(), yaze::cli::overworld::EntranceDetails::is_hole, yaze::cli::overworld::EntranceDetails::map_id, yaze::cli::overworld::EntranceDetails::map_pos, yaze::cli::overworld::EntranceDetails::world, yaze::cli::overworld::EntranceDetails::x, and yaze::cli::overworld::EntranceDetails::y.
Referenced by GetEntranceDetails(), and yaze::cli::agent::HandleOverworldGetEntranceCommand().
AnalyzeTileUsage()
absl::StatusOr< TileStatistics > yaze::cli::overworld::AnalyzeTileUsage (zelda3::Overworld & overworld, uint16_t tile_id, const TileSearchOptions & options)
Definition at line 465 of file overworld_inspect.cc.
References AnalyzeTileUsage(), ASSIGN_OR_RETURN, yaze::cli::overworld::TileStatistics::count, FindTileMatches(), InferWorldFromMapId(), yaze::cli::overworld::TileSearchOptions::map_id, yaze::cli::overworld::TileStatistics::map_id, yaze::cli::overworld::TileStatistics::positions, yaze::cli::overworld::TileStatistics::tile_id, yaze::cli::overworld::TileSearchOptions::world, and yaze::cli::overworld::TileStatistics::world.
Referenced by AnalyzeTileUsage(), and yaze::cli::agent::HandleOverworldTileStatsCommand().