yaze: yaze::zelda3::dungeon::RoomVisualDiagnostic Class Reference
yaze::zelda3::dungeon::RoomVisualDiagnostic Class Reference
Visual diagnostic tool for dungeon rendering using ImGui.
#include <room_visual_diagnostic.h>
Static Public Member Functions
static void DrawDiagnosticWindow (bool *p_open, gfx::BackgroundBuffer &bg1_buffer, gfx::BackgroundBuffer &bg2_buffer, const gfx::SnesPalette &palette, const std::vector< uint8_t > &gfx16_data)
Draw the diagnostic window.
Static Private Member Functions
static void DrawTexturePreview (const gfx::Bitmap &bitmap, const char *label)
static void DrawPaletteInspector (const gfx::SnesPalette &palette)
static void DrawTileBufferInspector (gfx::BackgroundBuffer &buffer, const gfx::SnesPalette &palette)
static void DrawPixelInspector (const gfx::Bitmap &bitmap, const gfx::SnesPalette &palette)
static void DrawTileDecoder (const std::vector< uint8_t > &gfx16_data, int tile_id)
Detailed Description
Visual diagnostic tool for dungeon rendering using ImGui.
Provides interactive visualization of:
Texture previews (BG1, BG2)
Bitmap data with zoom
Tile buffer contents
Palette colors
Pixel value inspection
Definition at line 23 of file room_visual_diagnostic.h.
Member Function Documentation
DrawDiagnosticWindow()
void yaze::zelda3::dungeon::RoomVisualDiagnostic::DrawDiagnosticWindow (bool * p_open, gfx::BackgroundBuffer & bg1_buffer, gfx::BackgroundBuffer & bg2_buffer, const gfx::SnesPalette & palette, const std::vector< uint8_t > & gfx16_data) static
Draw the diagnostic window.
Parameters
bg1_buffer Background 1 buffer reference
bg2_buffer Background 2 buffer reference
palette Current palette being used
gfx16_data Graphics data buffer
Definition at line 17 of file room_visual_diagnostic.cc.
References yaze::gfx::BackgroundBuffer::bitmap(), DrawPaletteInspector(), DrawPixelInspector(), DrawTexturePreview(), DrawTileBufferInspector(), and DrawTileDecoder().
Referenced by yaze::editor::DungeonEditor::DrawCanvasAndPropertiesPanel().
DrawTexturePreview()
void yaze::zelda3::dungeon::RoomVisualDiagnostic::DrawTexturePreview (const gfx::Bitmap & bitmap, const char * label) static private
Definition at line 77 of file room_visual_diagnostic.cc.
References yaze::gfx::Bitmap::height(), yaze::gfx::Bitmap::is_active(), yaze::gfx::Bitmap::texture(), yaze::gfx::Bitmap::vector(), and yaze::gfx::Bitmap::width().
Referenced by DrawDiagnosticWindow().
DrawPaletteInspector()
void yaze::zelda3::dungeon::RoomVisualDiagnostic::DrawPaletteInspector (const gfx::SnesPalette & palette) static private
Definition at line 105 of file room_visual_diagnostic.cc.
References yaze::gfx::SnesPalette::size().
Referenced by DrawDiagnosticWindow().
DrawTileBufferInspector()
void yaze::zelda3::dungeon::RoomVisualDiagnostic::DrawTileBufferInspector (gfx::BackgroundBuffer & buffer, const gfx::SnesPalette & palette) static private
Definition at line 132 of file room_visual_diagnostic.cc.
References yaze::gfx::BackgroundBuffer::bitmap(), yaze::gfx::BackgroundBuffer::buffer(), yaze::gfx::SnesPalette::size(), and yaze::gfx::WordToTileInfo().
Referenced by DrawDiagnosticWindow().
DrawPixelInspector()
void yaze::zelda3::dungeon::RoomVisualDiagnostic::DrawPixelInspector (const gfx::Bitmap & bitmap, const gfx::SnesPalette & palette) static private
Definition at line 199 of file room_visual_diagnostic.cc.
References yaze::gfx::Bitmap::height(), yaze::gfx::Bitmap::is_active(), yaze::gfx::SnesPalette::size(), yaze::gfx::Bitmap::vector(), and yaze::gfx::Bitmap::width().
Referenced by DrawDiagnosticWindow().
DrawTileDecoder()
void yaze::zelda3::dungeon::RoomVisualDiagnostic::DrawTileDecoder (const std::vector< uint8_t > & gfx16_data, int tile_id) static private
Definition at line 277 of file room_visual_diagnostic.cc.
Referenced by DrawDiagnosticWindow().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/room_visual_diagnostic.h
src/app/zelda3/dungeon/room_visual_diagnostic.cc