yaze: ROM File Operations  <br>
ROM File Operations <br>
Functions
zelda3_rom * yaze_load_rom (const char *filename)
Load a ROM file.
void yaze_unload_rom (zelda3_rom *rom)
Unload and free ROM data.
int yaze_save_rom (zelda3_rom *rom, const char *filename)
Save ROM to file.
zelda3_rom * yaze_copy_rom (const zelda3_rom *rom)
Create a copy of ROM data.
Detailed Description
Function Documentation
yaze_load_rom()
zelda3_rom * yaze_load_rom (const char * filename)
Load a ROM file.
Parameters
filename Path to ROM file
Returns
Loaded ROM structure, or NULL on error
Definition at line 151 of file yaze.cc.
References ZELDA3_VERSION_US.
Referenced by yaze_init().
yaze_unload_rom()
void yaze_unload_rom (zelda3_rom * rom)
Unload and free ROM data.
Parameters
rom ROM to unload
Definition at line 171 of file yaze.cc.
References zelda3_rom::impl.
Referenced by yaze_shutdown().
yaze_save_rom()
int yaze_save_rom (zelda3_rom * rom, const char * filename)
Save ROM to file.
Parameters
rom ROM to save
filename Output filename
Returns
YAZE_OK on success, error code on failure
Definition at line 184 of file yaze.cc.
References yaze::Rom::SaveSettings::backup, zelda3_rom::impl, zelda3_rom::is_modified, yaze::Rom::SaveToFile(), YAZE_ERROR_INVALID_ARG, YAZE_ERROR_IO, YAZE_ERROR_NOT_INITIALIZED, and YAZE_OK.
yaze_copy_rom()
zelda3_rom * yaze_copy_rom (const zelda3_rom * rom)
Create a copy of ROM data.
Parameters
rom Source ROM
Returns
Copy of ROM, or NULL on error