yaze: yaze::cli::AutocompleteEngine Class Reference
yaze::cli::AutocompleteEngine Class Reference
#include <autocomplete.h>
Classes
struct CommandDef
Public Member Functions
void RegisterCommand (const std::string &cmd, const std::string &desc, const std::vector< std::string > &examples={})
void RegisterParameter (const std::string &param, const std::string &desc, const std::vector< std::string > &values={})
std::vector< Suggestion > GetSuggestions (const std::string &input)
std::vector< Suggestion > GetContextualHelp (const std::string &partial_cmd)
void SetRomContext (bool has_rom)
Private Member Functions
int FuzzyScore (const std::string &text, const std::string &query)
Private Attributes
std::vector< CommandDef > commands_
bool has_rom_ = false
Detailed Description
Definition at line 18 of file autocomplete.h.
Member Function Documentation
RegisterCommand()
void yaze::cli::AutocompleteEngine::RegisterCommand (const std::string & cmd, const std::string & desc, const std::vector< std::string > & examples = {})
Definition at line 9 of file autocomplete.cc.
References commands_, yaze::cli::AutocompleteEngine::CommandDef::description, yaze::cli::AutocompleteEngine::CommandDef::examples, and yaze::cli::AutocompleteEngine::CommandDef::name.
Referenced by yaze::cli::tui::ChatTUI::InitializeAutocomplete().
RegisterParameter()
void yaze::cli::AutocompleteEngine::RegisterParameter (const std::string & param, const std::string & desc, const std::vector< std::string > & values = {})
Todo:
Store parameter definitions
Definition at line 18 of file autocomplete.cc.
GetSuggestions()
std::vector< Suggestion > yaze::cli::AutocompleteEngine::GetSuggestions (const std::string & input)
Definition at line 48 of file autocomplete.cc.
References commands_, yaze::cli::Suggestion::description, yaze::cli::Suggestion::example, FuzzyScore(), yaze::cli::Suggestion::score, and yaze::cli::Suggestion::text.
Referenced by yaze::cli::CreateAutocompleteInput().
GetContextualHelp()
std::vector< Suggestion > yaze::cli::AutocompleteEngine::GetContextualHelp (const std::string & partial_cmd)
Definition at line 71 of file autocomplete.cc.
SetRomContext()
void yaze::cli::AutocompleteEngine::SetRomContext (bool has_rom) inline
Definition at line 30 of file autocomplete.h.
References has_rom_.
FuzzyScore()
int yaze::cli::AutocompleteEngine::FuzzyScore (const std::string & text, const std::string & query) private
Definition at line 23 of file autocomplete.cc.
Referenced by GetSuggestions().
Member Data Documentation
commands_
std::vector<CommandDef> yaze::cli::AutocompleteEngine::commands_ private
Definition at line 40 of file autocomplete.h.
Referenced by GetSuggestions(), and RegisterCommand().
has_rom_
bool yaze::cli::AutocompleteEngine::has_rom_ = false private
Definition at line 41 of file autocomplete.h.
Referenced by SetRomContext().
The documentation for this class was generated from the following files:
src/cli/util/autocomplete.h
src/cli/util/autocomplete.cc