yaze: yaze::zelda3::OverworldMap Class Reference
yaze::zelda3::OverworldMap Class Reference
Represents a single Overworld map screen.
#include <overworld_map.h>
Public Member Functions
OverworldMap ()=default
OverworldMap (int index, Rom *rom)
absl::Status BuildMap (int count, int game_state, int world, std::vector< gfx::Tile16 > &tiles16, OverworldBlockset &world_blockset)
void LoadAreaGraphics ()
absl::Status LoadPalette ()
absl::Status LoadOverlay ()
absl::Status LoadVanillaOverlayData ()
absl::Status BuildTileset ()
absl::Status BuildTiles16Gfx (std::vector< gfx::Tile16 > &tiles16, int count)
absl::Status BuildBitmap (OverworldBlockset &world_blockset)
void DrawAnimatedTiles ()
auto current_tile16_blockset () const
auto current_graphics () const
auto current_palette () const
auto bitmap_data () const
auto is_large_map () const
auto is_initialized () const
auto is_built () const
auto parent () const
auto mutable_mosaic ()
auto mutable_current_palette ()
void SetNotBuilt ()
auto area_graphics () const
auto area_palette () const
auto sprite_graphics (int i) const
auto sprite_palette (int i) const
auto message_id () const
auto area_music (int i) const
auto static_graphics (int i) const
auto large_index () const
auto area_size () const
auto main_palette () const
void set_main_palette (uint8_t palette)
auto area_specific_bg_color () const
void set_area_specific_bg_color (uint16_t color)
auto subscreen_overlay () const
void set_subscreen_overlay (uint16_t overlay)
auto animated_gfx () const
void set_animated_gfx (uint8_t gfx)
auto custom_tileset (int index) const
auto overlay_id () const
auto has_overlay () const
const auto & overlay_data () const
const std::array< bool, 4 > & mosaic_expanded () const
void set_mosaic_expanded (int index, bool value)
void set_custom_tileset (int index, uint8_t value)
auto mutable_current_graphics ()
auto mutable_area_graphics ()
auto mutable_area_palette ()
auto mutable_sprite_graphics (int i)
auto mutable_sprite_palette (int i)
auto mutable_message_id ()
auto mutable_main_palette ()
auto mutable_animated_gfx ()
auto mutable_subscreen_overlay ()
auto mutable_area_music (int i)
auto mutable_static_graphics (int i)
auto set_area_graphics (uint8_t value)
auto set_area_palette (uint8_t value)
auto set_sprite_graphics (int i, uint8_t value)
auto set_sprite_palette (int i, uint8_t value)
auto set_message_id (uint16_t value)
uint8_t * mutable_custom_tileset (int index)
void SetAsLargeMap (int parent_index, int quadrant)
void SetAsSmallMap (int index=-1)
void SetAreaSize (AreaSizeEnum size)
void SetParent (int parent_index)
void Destroy ()
Private Member Functions
void LoadAreaInfo ()
void LoadCustomOverworldData ()
void SetupCustomTileset (uint8_t asm_version)
void LoadMainBlocksetId ()
void LoadSpritesBlocksets ()
void LoadMainBlocksets ()
void LoadAreaGraphicsBlocksets ()
void LoadDeathMountainGFX ()
void ProcessGraphicsBuffer (int index, int static_graphics_offset, int size, uint8_t *all_gfx)
absl::StatusOr< gfx::SnesPalette > GetPalette (const gfx::PaletteGroup &group, int index, int previous_index, int limit)
Private Attributes
Rom * rom_
bool built_ = false
bool large_map_ = false
bool initialized_ = false
bool mosaic_ = false
int index_ = 0
int parent_ = 0
int large_index_ = 0
int world_ = 0
int game_state_ = 0
int main_gfx_id_ = 0
AreaSizeEnum area_size_ = AreaSizeEnum::SmallArea
uint16_t message_id_ = 0
uint8_t area_graphics_ = 0
uint8_t area_palette_ = 0
uint8_t main_palette_ = 0
uint8_t animated_gfx_ = 0
uint16_t subscreen_overlay_ = 0
uint16_t area_specific_bg_color_
std::array< uint8_t, 8 > custom_gfx_ids_
std::array< uint8_t, 3 > sprite_graphics_
std::array< uint8_t, 3 > sprite_palette_
std::array< uint8_t, 4 > area_music_
std::array< uint8_t, 16 > static_graphics_
std::array< bool, 4 > mosaic_expanded_
uint16_t overlay_id_ = 0
bool has_overlay_ = false
std::vector< uint8_t > overlay_data_
std::vector< uint8_t > current_blockset_
std::vector< uint8_t > current_gfx_
std::vector< uint8_t > bitmap_data_
OverworldMapTiles map_tiles_
gfx::SnesPalette current_palette_
Additional Inherited Members
Static Protected Attributes inherited from yaze::gfx::GfxContext
static std::unordered_map< uint8_t, gfx::Paletteset > palettesets_
Detailed Description
Represents a single Overworld map screen.
Definition at line 100 of file overworld_map.h.
Constructor & Destructor Documentation
OverworldMap() [1/2]
yaze::zelda3::OverworldMap::OverworldMap () default
OverworldMap() [2/2]
yaze::zelda3::OverworldMap::OverworldMap (int index, Rom * rom)
Definition at line 17 of file overworld_map.cc.
References yaze::core::FeatureFlags::get(), index_, yaze::zelda3::kOverworldMapParentIdExpanded, LoadAreaInfo(), LoadCustomOverworldData(), yaze::zelda3::OverworldCustomASMHasBeenApplied, parent_, and SetupCustomTileset().
Member Function Documentation
BuildMap()
absl::Status yaze::zelda3::OverworldMap::BuildMap (int count, int game_state, int world, std::vector< gfx::Tile16 > & tiles16, OverworldBlockset & world_blockset)
Definition at line 40 of file overworld_map.cc.
References area_graphics_, area_palette_, BuildBitmap(), BuildTiles16Gfx(), BuildTileset(), built_, game_state_, index_, initialized_, yaze::zelda3::kAreaGfxIdPtr, yaze::zelda3::kOverworldMapPaletteIds, yaze::zelda3::kOverworldSpecialGfxGroup, yaze::zelda3::kOverworldSpecialPalGroup, yaze::zelda3::kSpecialWorldMapIdStart, large_map_, LoadAreaGraphics(), LoadOverlay(), LoadPalette(), yaze::zelda3::OverworldCustomASMHasBeenApplied, parent_, RETURN_IF_ERROR, and world_.
LoadAreaGraphics()
void yaze::zelda3::OverworldMap::LoadAreaGraphics ()
Definition at line 590 of file overworld_map.cc.
References LoadAreaGraphicsBlocksets(), LoadDeathMountainGFX(), LoadMainBlocksetId(), LoadMainBlocksets(), and LoadSpritesBlocksets().
Referenced by BuildMap().
LoadPalette()
absl::Status yaze::zelda3::OverworldMap::LoadPalette ()
Definition at line 733 of file overworld_map.cc.
References area_palette_, area_specific_bg_color_, ASSIGN_OR_RETURN, current_palette_, game_state_, GetPalette(), index_, yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kNumOverworldMaps, zelda3_version_pointers::kOverworldMapPaletteGroup, yaze::zelda3::kOverworldMapPaletteIds, yaze::zelda3::kOverworldPalettesScreenToSetNew, yaze::zelda3::kOverworldSpritePaletteGroup, yaze::zelda3::kOverworldSpritePaletteIds, yaze::zelda3::kSpecialWorldMapIdStart, main(), main_palette_, yaze::zelda3::OverworldCustomAreaSpecificBGEnabled, yaze::zelda3::OverworldCustomAreaSpecificBGPalette, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::Rom::palette_group(), yaze::gfx::GfxContext::palettesets_, parent_, RETURN_IF_ERROR, rom_, yaze::zelda3::palette_internal::SetColorsPalette(), sprite_palette_, and yaze::Rom::version_constants().
Referenced by BuildMap().
LoadOverlay()
absl::Status yaze::zelda3::OverworldMap::LoadOverlay ()
Definition at line 864 of file overworld_map.cc.
References has_overlay_, LoadVanillaOverlayData(), overlay_data_, overlay_id_, yaze::zelda3::OverworldCustomASMHasBeenApplied, and subscreen_overlay_.
Referenced by BuildMap().
LoadVanillaOverlayData()
absl::Status yaze::zelda3::OverworldMap::LoadVanillaOverlayData ()
Definition at line 880 of file overworld_map.cc.
References has_overlay_, index_, yaze::zelda3::kOverlayData1, yaze::zelda3::kOverlayData2, yaze::zelda3::kOverlayPointers, yaze::zelda3::kOverlayPointersBank, overlay_data_, overlay_id_, rom_, and yaze::Rom::size().
Referenced by LoadOverlay().
BuildTileset()
absl::Status yaze::zelda3::OverworldMap::BuildTileset ()
Definition at line 1029 of file overworld_map.cc.
References current_gfx_, yaze::Rom::graphics_buffer(), ProcessGraphicsBuffer(), rom_, and static_graphics_.
Referenced by BuildMap().
BuildTiles16Gfx()
absl::Status yaze::zelda3::OverworldMap::BuildTiles16Gfx (std::vector< gfx::Tile16 > & tiles16, int count)
Definition at line 1058 of file overworld_map.cc.
References current_blockset_, current_gfx_, yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::gfx::TileInfo::palette_, and yaze::gfx::TileInfo::vertical_mirror_.
Referenced by BuildMap().
BuildBitmap()
absl::Status yaze::zelda3::OverworldMap::BuildBitmap (OverworldBlockset & world_blockset)
Definition at line 1105 of file overworld_map.cc.
References bitmap_data_, yaze::gfx::CopyTile8bpp16(), current_blockset_, index_, and world_.
Referenced by BuildMap().
DrawAnimatedTiles()
void yaze::zelda3::OverworldMap::DrawAnimatedTiles ()
Definition at line 555 of file overworld_map.cc.
References static_graphics_.
current_tile16_blockset()
auto yaze::zelda3::OverworldMap::current_tile16_blockset () const inline
Definition at line 119 of file overworld_map.h.
References current_blockset_.
current_graphics()
auto yaze::zelda3::OverworldMap::current_graphics () const inline
Definition at line 120 of file overworld_map.h.
References current_gfx_.
current_palette()
auto yaze::zelda3::OverworldMap::current_palette () const inline
Definition at line 121 of file overworld_map.h.
References current_palette_.
bitmap_data()
auto yaze::zelda3::OverworldMap::bitmap_data () const inline
Definition at line 122 of file overworld_map.h.
References bitmap_data_.
is_large_map()
auto yaze::zelda3::OverworldMap::is_large_map () const inline
Definition at line 123 of file overworld_map.h.
References large_map_.
Referenced by yaze::zelda3::TEST_F().
is_initialized()
auto yaze::zelda3::OverworldMap::is_initialized () const inline
Definition at line 124 of file overworld_map.h.
References initialized_.
Referenced by yaze::zelda3::TEST_F().
is_built()
auto yaze::zelda3::OverworldMap::is_built () const inline
Definition at line 125 of file overworld_map.h.
References built_.
parent()
auto yaze::zelda3::OverworldMap::parent () const inline
Definition at line 126 of file overworld_map.h.
References parent_.
Referenced by yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), and yaze::zelda3::TEST_F().
mutable_mosaic()
auto yaze::zelda3::OverworldMap::mutable_mosaic () inline
Definition at line 127 of file overworld_map.h.
References mosaic_.
mutable_current_palette()
auto yaze::zelda3::OverworldMap::mutable_current_palette () inline
Definition at line 128 of file overworld_map.h.
References current_palette_.
SetNotBuilt()
void yaze::zelda3::OverworldMap::SetNotBuilt () inline
Definition at line 130 of file overworld_map.h.
References built_.
area_graphics()
auto yaze::zelda3::OverworldMap::area_graphics () const inline
Definition at line 132 of file overworld_map.h.
References area_graphics_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
area_palette()
auto yaze::zelda3::OverworldMap::area_palette () const inline
Definition at line 133 of file overworld_map.h.
References area_palette_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
sprite_graphics()
auto yaze::zelda3::OverworldMap::sprite_graphics (int i) const inline
Definition at line 134 of file overworld_map.h.
References sprite_graphics_.
Referenced by yaze::zelda3::TEST_F().
sprite_palette()
auto yaze::zelda3::OverworldMap::sprite_palette (int i) const inline
Definition at line 135 of file overworld_map.h.
References sprite_palette_.
Referenced by yaze::zelda3::TEST_F().
message_id()
auto yaze::zelda3::OverworldMap::message_id () const inline
Definition at line 136 of file overworld_map.h.
References message_id_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
area_music()
auto yaze::zelda3::OverworldMap::area_music (int i) const inline
Definition at line 137 of file overworld_map.h.
References area_music_.
static_graphics()
auto yaze::zelda3::OverworldMap::static_graphics (int i) const inline
Definition at line 138 of file overworld_map.h.
References static_graphics_.
large_index()
auto yaze::zelda3::OverworldMap::large_index () const inline
Definition at line 139 of file overworld_map.h.
References large_index_.
Referenced by yaze::zelda3::TEST_F().
area_size()
auto yaze::zelda3::OverworldMap::area_size () const inline
Definition at line 140 of file overworld_map.h.
References area_size_.
Referenced by yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
main_palette()
auto yaze::zelda3::OverworldMap::main_palette () const inline
Definition at line 142 of file overworld_map.h.
References main_palette_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
set_main_palette()
void yaze::zelda3::OverworldMap::set_main_palette (uint8_t palette) inline
Definition at line 143 of file overworld_map.h.
References main_palette_.
Referenced by yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
area_specific_bg_color()
auto yaze::zelda3::OverworldMap::area_specific_bg_color () const inline
Definition at line 145 of file overworld_map.h.
References area_specific_bg_color_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
set_area_specific_bg_color()
void yaze::zelda3::OverworldMap::set_area_specific_bg_color (uint16_t color) inline
Definition at line 146 of file overworld_map.h.
References area_specific_bg_color_.
Referenced by yaze::zelda3::TEST_F().
subscreen_overlay()
auto yaze::zelda3::OverworldMap::subscreen_overlay () const inline
Definition at line 150 of file overworld_map.h.
References subscreen_overlay_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
set_subscreen_overlay()
void yaze::zelda3::OverworldMap::set_subscreen_overlay (uint16_t overlay) inline
Definition at line 151 of file overworld_map.h.
References subscreen_overlay_.
Referenced by yaze::zelda3::TEST_F().
animated_gfx()
auto yaze::zelda3::OverworldMap::animated_gfx () const inline
Definition at line 153 of file overworld_map.h.
References animated_gfx_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
set_animated_gfx()
void yaze::zelda3::OverworldMap::set_animated_gfx (uint8_t gfx) inline
Definition at line 154 of file overworld_map.h.
References animated_gfx_.
Referenced by yaze::zelda3::TEST_F().
custom_tileset()
auto yaze::zelda3::OverworldMap::custom_tileset (int index) const inline
Definition at line 156 of file overworld_map.h.
References custom_gfx_ids_.
Referenced by yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
overlay_id()
auto yaze::zelda3::OverworldMap::overlay_id () const inline
Definition at line 159 of file overworld_map.h.
References overlay_id_.
has_overlay()
auto yaze::zelda3::OverworldMap::has_overlay () const inline
Definition at line 160 of file overworld_map.h.
References has_overlay_.
overlay_data()
const auto & yaze::zelda3::OverworldMap::overlay_data () const inline
Definition at line 161 of file overworld_map.h.
References overlay_data_.
mosaic_expanded()
const std::array< bool, 4 > & yaze::zelda3::OverworldMap::mosaic_expanded () const inline
Definition at line 164 of file overworld_map.h.
References mosaic_expanded_.
set_mosaic_expanded()
void yaze::zelda3::OverworldMap::set_mosaic_expanded (int index, bool value) inline
Definition at line 165 of file overworld_map.h.
References mosaic_expanded_.
set_custom_tileset()
void yaze::zelda3::OverworldMap::set_custom_tileset (int index, uint8_t value) inline
Definition at line 166 of file overworld_map.h.
References custom_gfx_ids_.
Referenced by yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
mutable_current_graphics()
auto yaze::zelda3::OverworldMap::mutable_current_graphics () inline
Definition at line 168 of file overworld_map.h.
References current_gfx_.
mutable_area_graphics()
auto yaze::zelda3::OverworldMap::mutable_area_graphics () inline
Definition at line 169 of file overworld_map.h.
References area_graphics_.
Referenced by yaze::zelda3::TEST_F().
mutable_area_palette()
auto yaze::zelda3::OverworldMap::mutable_area_palette () inline
Definition at line 170 of file overworld_map.h.
References area_palette_.
Referenced by yaze::zelda3::TEST_F().
mutable_sprite_graphics()
auto yaze::zelda3::OverworldMap::mutable_sprite_graphics (int i) inline
Definition at line 171 of file overworld_map.h.
References sprite_graphics_.
mutable_sprite_palette()
auto yaze::zelda3::OverworldMap::mutable_sprite_palette (int i) inline
Definition at line 172 of file overworld_map.h.
References sprite_palette_.
mutable_message_id()
auto yaze::zelda3::OverworldMap::mutable_message_id () inline
Definition at line 173 of file overworld_map.h.
References message_id_.
Referenced by yaze::zelda3::TEST_F().
mutable_main_palette()
auto yaze::zelda3::OverworldMap::mutable_main_palette () inline
Definition at line 174 of file overworld_map.h.
References main_palette_.
Referenced by yaze::zelda3::TEST_F().
mutable_animated_gfx()
auto yaze::zelda3::OverworldMap::mutable_animated_gfx () inline
Definition at line 175 of file overworld_map.h.
References animated_gfx_.
Referenced by yaze::zelda3::TEST_F().
mutable_subscreen_overlay()
auto yaze::zelda3::OverworldMap::mutable_subscreen_overlay () inline
Definition at line 176 of file overworld_map.h.
References subscreen_overlay_.
Referenced by yaze::zelda3::TEST_F().
mutable_area_music()
auto yaze::zelda3::OverworldMap::mutable_area_music (int i) inline
Definition at line 177 of file overworld_map.h.
References area_music_.
mutable_static_graphics()
auto yaze::zelda3::OverworldMap::mutable_static_graphics (int i) inline
Definition at line 178 of file overworld_map.h.
References static_graphics_.
set_area_graphics()
auto yaze::zelda3::OverworldMap::set_area_graphics (uint8_t value) inline
Definition at line 180 of file overworld_map.h.
References area_graphics_.
Referenced by yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
set_area_palette()
auto yaze::zelda3::OverworldMap::set_area_palette (uint8_t value) inline
Definition at line 181 of file overworld_map.h.
References area_palette_.
Referenced by yaze::zelda3::TEST_F().
set_sprite_graphics()
auto yaze::zelda3::OverworldMap::set_sprite_graphics (int i, uint8_t value) inline
Definition at line 182 of file overworld_map.h.
References sprite_graphics_.
Referenced by yaze::zelda3::TEST_F().
set_sprite_palette()
auto yaze::zelda3::OverworldMap::set_sprite_palette (int i, uint8_t value) inline
Definition at line 185 of file overworld_map.h.
References sprite_palette_.
Referenced by yaze::zelda3::TEST_F().
set_message_id()
auto yaze::zelda3::OverworldMap::set_message_id (uint16_t value) inline
Definition at line 186 of file overworld_map.h.
References message_id_.
Referenced by yaze::zelda3::TEST_F().
mutable_custom_tileset()
uint8_t * yaze::zelda3::OverworldMap::mutable_custom_tileset (int index) inline
Definition at line 188 of file overworld_map.h.
References custom_gfx_ids_.
Referenced by yaze::zelda3::TEST_F().
SetAsLargeMap()
void yaze::zelda3::OverworldMap::SetAsLargeMap (int parent_index, int quadrant) inline
Definition at line 190 of file overworld_map.h.
References area_size_, large_index_, large_map_, yaze::zelda3::LargeArea, and parent_.
Referenced by yaze::zelda3::TEST_F().
SetAsSmallMap()
void yaze::zelda3::OverworldMap::SetAsSmallMap (int index = -1) inline
Definition at line 197 of file overworld_map.h.
References area_size_, index_, large_index_, large_map_, parent_, and yaze::zelda3::SmallArea.
Referenced by yaze::zelda3::TEST_F().
SetAreaSize()
void yaze::zelda3::OverworldMap::SetAreaSize (AreaSizeEnum size) inline
Definition at line 207 of file overworld_map.h.
References area_size_, large_map_, and yaze::zelda3::LargeArea.
Referenced by yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
SetParent()
void yaze::zelda3::OverworldMap::SetParent (int parent_index) inline
Definition at line 212 of file overworld_map.h.
References parent_.
Destroy()
void yaze::zelda3::OverworldMap::Destroy () inline
Definition at line 216 of file overworld_map.h.
References animated_gfx_, area_graphics_, area_music_, area_palette_, area_size_, area_specific_bg_color_, bitmap_data_, built_, current_blockset_, current_gfx_, custom_gfx_ids_, yaze::zelda3::OverworldMapTiles::dark_world, game_state_, has_overlay_, index_, initialized_, large_index_, large_map_, yaze::zelda3::OverworldMapTiles::light_world, main_gfx_id_, main_palette_, map_tiles_, message_id_, mosaic_, mosaic_expanded_, overlay_data_, overlay_id_, parent_, yaze::zelda3::SmallArea, yaze::zelda3::OverworldMapTiles::special_world, sprite_graphics_, sprite_palette_, static_graphics_, subscreen_overlay_, and world_.
Referenced by yaze::zelda3::TEST_F().
LoadAreaInfo()
void yaze::zelda3::OverworldMap::LoadAreaInfo () private
Definition at line 81 of file overworld_map.cc.
References area_graphics_, area_music_, area_palette_, area_size_, index_, yaze::zelda3::kAreaGfxIdPtr, yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kOverworldMapPaletteIds, yaze::zelda3::kOverworldMessageIds, yaze::zelda3::kOverworldMessagesExpanded, yaze::zelda3::kOverworldMusicAgahnim, yaze::zelda3::kOverworldMusicBeginning, yaze::zelda3::kOverworldMusicDarkWorld, yaze::zelda3::kOverworldMusicMasterSword, yaze::zelda3::kOverworldMusicZelda, yaze::zelda3::kOverworldPalettesScreenToSetNew, yaze::zelda3::kOverworldScreenSize, yaze::zelda3::kOverworldSpecialGfxGroup, yaze::zelda3::kOverworldSpecialPalGroup, yaze::zelda3::kOverworldSpecialSpriteGfxGroupExpandedTemp, yaze::zelda3::kOverworldSpecialSpritePaletteExpandedTemp, yaze::zelda3::kOverworldSpritePaletteIds, yaze::zelda3::kOverworldSpriteset, yaze::zelda3::kSpecialWorldMapIdStart, large_map_, yaze::zelda3::LargeArea, message_id_, yaze::zelda3::OverworldCustomASMHasBeenApplied, parent_, rom_, yaze::zelda3::SmallArea, sprite_graphics_, sprite_palette_, yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
Referenced by OverworldMap().
LoadCustomOverworldData()
void yaze::zelda3::OverworldMap::LoadCustomOverworldData () private
Todo:
Might need this one too "index == 0x1B"
Definition at line 283 of file overworld_map.cc.
References animated_gfx_, area_graphics_, custom_gfx_ids_, index_, yaze::zelda3::kDarkWorldMapIdStart, zelda3_version_pointers::kOverworldGfxGroups1, zelda3_version_pointers::kOverworldGfxGroups2, yaze::zelda3::kSpecialWorldMapIdStart, main_palette_, mosaic_expanded_, parent_, rom_, subscreen_overlay_, and yaze::Rom::version_constants().
Referenced by OverworldMap().
SetupCustomTileset()
void yaze::zelda3::OverworldMap::SetupCustomTileset (uint8_t asm_version) private
Definition at line 420 of file overworld_map.cc.
References animated_gfx_, area_graphics_, area_size_, custom_gfx_ids_, index_, yaze::zelda3::kDarkWorldMapIdStart, zelda3_version_pointers::kOverworldGfxGroups1, zelda3_version_pointers::kOverworldGfxGroups2, yaze::zelda3::kOverworldScreenSize, yaze::zelda3::kSpecialWorldMapIdStart, large_map_, yaze::zelda3::LargeArea, main_palette_, mosaic_, mosaic_expanded_, yaze::zelda3::OverworldCustomAnimatedGFXArray, yaze::zelda3::OverworldCustomMainPaletteArray, yaze::zelda3::OverworldCustomMosaicArray, yaze::zelda3::OverworldCustomSubscreenOverlayArray, yaze::zelda3::OverworldCustomTileGFXGroupArray, parent_, rom_, subscreen_overlay_, and yaze::Rom::version_constants().
Referenced by OverworldMap().
LoadMainBlocksetId()
void yaze::zelda3::OverworldMap::LoadMainBlocksetId () private
Definition at line 509 of file overworld_map.cc.
References yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kSpecialWorldMapIdStart, main_gfx_id_, and parent_.
Referenced by LoadAreaGraphics().
LoadSpritesBlocksets()
void yaze::zelda3::OverworldMap::LoadSpritesBlocksets () private
Definition at line 526 of file overworld_map.cc.
References game_state_, zelda3_version_pointers::kSpriteBlocksetPointer, rom_, sprite_graphics_, static_graphics_, and yaze::Rom::version_constants().
Referenced by LoadAreaGraphics().
LoadMainBlocksets()
void yaze::zelda3::OverworldMap::LoadMainBlocksets () private
Definition at line 541 of file overworld_map.cc.
References zelda3_version_pointers::kOverworldGfxGroups2, main_gfx_id_, rom_, static_graphics_, and yaze::Rom::version_constants().
Referenced by LoadAreaGraphics().
LoadAreaGraphicsBlocksets()
void yaze::zelda3::OverworldMap::LoadAreaGraphicsBlocksets () private
Definition at line 566 of file overworld_map.cc.
References area_graphics_, zelda3_version_pointers::kOverworldGfxGroups1, rom_, static_graphics_, and yaze::Rom::version_constants().
Referenced by LoadAreaGraphics().
LoadDeathMountainGFX()
void yaze::zelda3::OverworldMap::LoadDeathMountainGFX () private
Todo:
Change the conditions for death mountain gfx
Definition at line 581 of file overworld_map.cc.
References parent_, and static_graphics_.
Referenced by LoadAreaGraphics().
ProcessGraphicsBuffer()
void yaze::zelda3::OverworldMap::ProcessGraphicsBuffer (int index, int static_graphics_offset, int size, uint8_t * all_gfx) private
Definition at line 1003 of file overworld_map.cc.
References current_gfx_, yaze::Rom::graphics_buffer(), and rom_.
Referenced by BuildTileset().
GetPalette()
absl::StatusOr< gfx::SnesPalette > yaze::zelda3::OverworldMap::GetPalette (const gfx::PaletteGroup & group, int index, int previous_index, int limit) private
Definition at line 720 of file overworld_map.cc.
References zelda3_version_pointers::kOverworldMapPaletteGroup, rom_, and yaze::Rom::version_constants().
Referenced by LoadPalette().
Member Data Documentation
rom_
Rom* yaze::zelda3::OverworldMap::rom_ private
Definition at line 269 of file overworld_map.h.
Referenced by BuildTileset(), GetPalette(), LoadAreaGraphicsBlocksets(), LoadAreaInfo(), LoadCustomOverworldData(), LoadMainBlocksets(), LoadPalette(), LoadSpritesBlocksets(), LoadVanillaOverlayData(), ProcessGraphicsBuffer(), and SetupCustomTileset().
built_
bool yaze::zelda3::OverworldMap::built_ = false private
Definition at line 271 of file overworld_map.h.
Referenced by BuildMap(), Destroy(), is_built(), and SetNotBuilt().
large_map_
bool yaze::zelda3::OverworldMap::large_map_ = false private
Definition at line 272 of file overworld_map.h.
Referenced by BuildMap(), Destroy(), is_large_map(), LoadAreaInfo(), SetAreaSize(), SetAsLargeMap(), SetAsSmallMap(), and SetupCustomTileset().
initialized_
bool yaze::zelda3::OverworldMap::initialized_ = false private
Definition at line 273 of file overworld_map.h.
Referenced by BuildMap(), Destroy(), and is_initialized().
mosaic_
bool yaze::zelda3::OverworldMap::mosaic_ = false private
Definition at line 274 of file overworld_map.h.
Referenced by Destroy(), mutable_mosaic(), and SetupCustomTileset().
index_
int yaze::zelda3::OverworldMap::index_ = 0 private
Definition at line 276 of file overworld_map.h.
Referenced by BuildBitmap(), BuildMap(), Destroy(), LoadAreaInfo(), LoadCustomOverworldData(), LoadPalette(), LoadVanillaOverlayData(), OverworldMap(), SetAsSmallMap(), and SetupCustomTileset().
parent_
int yaze::zelda3::OverworldMap::parent_ = 0 private
Definition at line 277 of file overworld_map.h.
Referenced by BuildMap(), Destroy(), LoadAreaInfo(), LoadCustomOverworldData(), LoadDeathMountainGFX(), LoadMainBlocksetId(), LoadPalette(), OverworldMap(), parent(), SetAsLargeMap(), SetAsSmallMap(), SetParent(), and SetupCustomTileset().
large_index_
int yaze::zelda3::OverworldMap::large_index_ = 0 private
Definition at line 278 of file overworld_map.h.
Referenced by Destroy(), large_index(), SetAsLargeMap(), and SetAsSmallMap().
world_
int yaze::zelda3::OverworldMap::world_ = 0 private
Definition at line 279 of file overworld_map.h.
Referenced by BuildBitmap(), BuildMap(), and Destroy().
game_state_
int yaze::zelda3::OverworldMap::game_state_ = 0 private
Definition at line 280 of file overworld_map.h.
Referenced by BuildMap(), Destroy(), LoadPalette(), and LoadSpritesBlocksets().
main_gfx_id_
int yaze::zelda3::OverworldMap::main_gfx_id_ = 0 private
Definition at line 281 of file overworld_map.h.
Referenced by Destroy(), LoadMainBlocksetId(), and LoadMainBlocksets().
area_size_
AreaSizeEnum yaze::zelda3::OverworldMap::area_size_ = AreaSizeEnum::SmallArea private
Definition at line 282 of file overworld_map.h.
Referenced by area_size(), Destroy(), LoadAreaInfo(), SetAreaSize(), SetAsLargeMap(), SetAsSmallMap(), and SetupCustomTileset().
message_id_
uint16_t yaze::zelda3::OverworldMap::message_id_ = 0 private
Definition at line 284 of file overworld_map.h.
Referenced by Destroy(), LoadAreaInfo(), message_id(), mutable_message_id(), and set_message_id().
area_graphics_
uint8_t yaze::zelda3::OverworldMap::area_graphics_ = 0 private
Definition at line 285 of file overworld_map.h.
Referenced by area_graphics(), BuildMap(), Destroy(), LoadAreaGraphicsBlocksets(), LoadAreaInfo(), LoadCustomOverworldData(), mutable_area_graphics(), set_area_graphics(), and SetupCustomTileset().
area_palette_
uint8_t yaze::zelda3::OverworldMap::area_palette_ = 0 private
Definition at line 286 of file overworld_map.h.
Referenced by area_palette(), BuildMap(), Destroy(), LoadAreaInfo(), LoadPalette(), mutable_area_palette(), and set_area_palette().
main_palette_
uint8_t yaze::zelda3::OverworldMap::main_palette_ = 0 private
Definition at line 287 of file overworld_map.h.
Referenced by Destroy(), LoadCustomOverworldData(), LoadPalette(), main_palette(), mutable_main_palette(), set_main_palette(), and SetupCustomTileset().
animated_gfx_
uint8_t yaze::zelda3::OverworldMap::animated_gfx_ = 0 private
Definition at line 288 of file overworld_map.h.
Referenced by animated_gfx(), Destroy(), LoadCustomOverworldData(), mutable_animated_gfx(), set_animated_gfx(), and SetupCustomTileset().
subscreen_overlay_
uint16_t yaze::zelda3::OverworldMap::subscreen_overlay_ = 0 private
Definition at line 289 of file overworld_map.h.
Referenced by Destroy(), LoadCustomOverworldData(), LoadOverlay(), mutable_subscreen_overlay(), set_subscreen_overlay(), SetupCustomTileset(), and subscreen_overlay().
area_specific_bg_color_
uint16_t yaze::zelda3::OverworldMap::area_specific_bg_color_ private
Initial value:
=
      0
Definition at line 290 of file overworld_map.h.
Referenced by area_specific_bg_color(), Destroy(), LoadPalette(), and set_area_specific_bg_color().
custom_gfx_ids_
std::array<uint8_t, 8> yaze::zelda3::OverworldMap::custom_gfx_ids_ private
Definition at line 293 of file overworld_map.h.
Referenced by custom_tileset(), Destroy(), LoadCustomOverworldData(), mutable_custom_tileset(), set_custom_tileset(), and SetupCustomTileset().
sprite_graphics_
std::array<uint8_t, 3> yaze::zelda3::OverworldMap::sprite_graphics_ private
Definition at line 294 of file overworld_map.h.
Referenced by Destroy(), LoadAreaInfo(), LoadSpritesBlocksets(), mutable_sprite_graphics(), set_sprite_graphics(), and sprite_graphics().
sprite_palette_
std::array<uint8_t, 3> yaze::zelda3::OverworldMap::sprite_palette_ private
Definition at line 295 of file overworld_map.h.
Referenced by Destroy(), LoadAreaInfo(), LoadPalette(), mutable_sprite_palette(), set_sprite_palette(), and sprite_palette().
area_music_
std::array<uint8_t, 4> yaze::zelda3::OverworldMap::area_music_ private
Definition at line 296 of file overworld_map.h.
Referenced by area_music(), Destroy(), LoadAreaInfo(), and mutable_area_music().
static_graphics_
std::array<uint8_t, 16> yaze::zelda3::OverworldMap::static_graphics_ private
Definition at line 297 of file overworld_map.h.
Referenced by BuildTileset(), Destroy(), DrawAnimatedTiles(), LoadAreaGraphicsBlocksets(), LoadDeathMountainGFX(), LoadMainBlocksets(), LoadSpritesBlocksets(), mutable_static_graphics(), and static_graphics().
mosaic_expanded_
std::array<bool, 4> yaze::zelda3::OverworldMap::mosaic_expanded_ private
Definition at line 299 of file overworld_map.h.
Referenced by Destroy(), LoadCustomOverworldData(), mosaic_expanded(), set_mosaic_expanded(), and SetupCustomTileset().
overlay_id_
uint16_t yaze::zelda3::OverworldMap::overlay_id_ = 0 private
Definition at line 302 of file overworld_map.h.
Referenced by Destroy(), LoadOverlay(), LoadVanillaOverlayData(), and overlay_id().
has_overlay_
bool yaze::zelda3::OverworldMap::has_overlay_ = false private
Definition at line 303 of file overworld_map.h.
Referenced by Destroy(), has_overlay(), LoadOverlay(), and LoadVanillaOverlayData().
overlay_data_
std::vector<uint8_t> yaze::zelda3::OverworldMap::overlay_data_ private
Definition at line 304 of file overworld_map.h.
Referenced by Destroy(), LoadOverlay(), LoadVanillaOverlayData(), and overlay_data().
current_blockset_
std::vector<uint8_t> yaze::zelda3::OverworldMap::current_blockset_ private
Definition at line 306 of file overworld_map.h.
Referenced by BuildBitmap(), BuildTiles16Gfx(), current_tile16_blockset(), and Destroy().
current_gfx_
std::vector<uint8_t> yaze::zelda3::OverworldMap::current_gfx_ private
Definition at line 307 of file overworld_map.h.
Referenced by BuildTiles16Gfx(), BuildTileset(), current_graphics(), Destroy(), mutable_current_graphics(), and ProcessGraphicsBuffer().
bitmap_data_
std::vector<uint8_t> yaze::zelda3::OverworldMap::bitmap_data_ private
Definition at line 308 of file overworld_map.h.
Referenced by bitmap_data(), BuildBitmap(), and Destroy().
map_tiles_
OverworldMapTiles yaze::zelda3::OverworldMap::map_tiles_ private
Definition at line 310 of file overworld_map.h.
Referenced by Destroy().
current_palette_
gfx::SnesPalette yaze::zelda3::OverworldMap::current_palette_ private
Definition at line 311 of file overworld_map.h.
Referenced by current_palette(), LoadPalette(), and mutable_current_palette().
The documentation for this class was generated from the following files:
src/app/zelda3/overworld/overworld_map.h
src/app/zelda3/overworld/overworld_map.cc