yaze: yaze::editor::AgentChatWidget Class Reference
yaze::editor::AgentChatWidget Class Reference
Modern AI chat widget with comprehensive z3ed and yaze-server integration.
#include <agent_chat_widget.h>
Classes
struct AgentConfigState
struct AutomationCallbacks
struct AutomationState
struct AutomationTelemetry
struct ChatSession
struct CollaborationCallbacks
struct CollaborationState
struct FileEditorTab
struct MultimodalCallbacks
struct MultimodalState
struct RomSyncCallbacks
struct RomSyncState
struct Z3EDCommandCallbacks
struct Z3EDCommandState
Public Types
enum class CollaborationMode { kLocal = 0 , kNetwork = 1 }
enum class CaptureMode { kFullWindow = 0 , kActiveEditor = 1 , kSpecificWindow = 2 }
Public Member Functions
AgentChatWidget ()
void Draw ()
void SetRomContext (Rom *rom)
void RenderSnapshotPreviewPanel ()
void SetToastManager (ToastManager *toast_manager)
void SetProposalDrawer (ProposalDrawer *drawer)
void SetChatHistoryPopup (AgentChatHistoryPopup *popup)
void SetCollaborationCallbacks (const CollaborationCallbacks &callbacks)
void SetMultimodalCallbacks (const MultimodalCallbacks &callbacks)
void SetAutomationCallbacks (const AutomationCallbacks &callbacks)
void UpdateHarnessTelemetry (const AutomationTelemetry &telemetry)
void SetLastPlanSummary (const std::string &summary)
void SetZ3EDCommandCallbacks (const Z3EDCommandCallbacks &callbacks)
void SetRomSyncCallbacks (const RomSyncCallbacks &callbacks)
bool * active ()
bool is_active () const
void set_active (bool active)
void SetPromptMode (cli::agent::PromptMode mode)
cli::agent::PromptMode GetPromptMode () const
CaptureMode capture_mode () const
const char * specific_window_name () const
const AgentConfigState & GetAgentConfig () const
void UpdateAgentConfig (const AgentConfigState &config)
void LoadAgentSettingsFromProject (const core::YazeProject &project)
void SaveAgentSettingsToProject (core::YazeProject &project)
void SwitchToSharedHistory (const std::string &session_id)
void SwitchToLocalHistory ()
void OpenFileInEditor (const std::string &filepath)
void CreateNewFileInEditor (const std::string &filename)
Private Member Functions
void EnsureHistoryLoaded ()
void PersistHistory ()
void RenderHistory ()
void RenderMessage (const cli::agent::ChatMessage &msg, int index)
void RenderProposalQuickActions (const cli::agent::ChatMessage &msg, int index)
void RenderInputBox ()
void HandleAgentResponse (const absl::StatusOr< cli::agent::ChatMessage > &response)
int CountKnownProposals () const
void FocusProposalDrawer (const std::string &proposal_id)
void NotifyProposalCreated (const cli::agent::ChatMessage &msg, int new_total_proposals)
void RenderCollaborationPanel ()
void RenderMultimodalPanel ()
void RenderAgentConfigPanel ()
void RenderZ3EDCommandPanel ()
void RenderRomSyncPanel ()
void RenderProposalManagerPanel ()
void RenderHarnessPanel ()
void RenderSystemPromptEditor ()
void RenderFileEditorTabs ()
void RefreshCollaboration ()
void ApplyCollaborationSession (const CollaborationCallbacks::SessionContext &context, bool update_action_timestamp)
void MarkHistoryDirty ()
void PollSharedHistory ()
void HandleRomSyncReceived (const std::string &diff_data, const std::string &rom_hash)
void HandleSnapshotReceived (const std::string &snapshot_data, const std::string &snapshot_type)
void HandleProposalReceived (const std::string &proposal_data)
void SyncHistoryToPopup ()
void SaveChatSession (const ChatSession &session)
void LoadChatSession (const std::string &session_id)
void DeleteChatSession (const std::string &session_id)
std::vector< std::string > GetSavedSessions ()
std::filesystem::path GetSessionsDirectory ()
Private Attributes
bool waiting_for_response_ = false
float thinking_animation_ = 0.0f
std::string pending_message_
std::vector< ChatSession > chat_sessions_
int active_session_index_ = 0
cli::agent::ConversationalAgentService agent_service_
char input_buffer_ [1024]
bool active_ = false
std::string title_
size_t last_history_size_ = 0
bool history_loaded_ = false
bool history_dirty_ = false
bool history_supported_ = true
bool history_warning_displayed_ = false
std::filesystem::path history_path_
int last_proposal_count_ = 0
ToastManager * toast_manager_ = nullptr
ProposalDrawer * proposal_drawer_ = nullptr
AgentChatHistoryPopup * chat_history_popup_ = nullptr
std::string pending_focus_proposal_id_
absl::Time last_persist_time_ = absl::InfinitePast()
CollaborationState collaboration_state_
MultimodalState multimodal_state_
AutomationState automation_state_
AgentConfigState agent_config_
RomSyncState rom_sync_state_
Z3EDCommandState z3ed_command_state_
CollaborationCallbacks collaboration_callbacks_
MultimodalCallbacks multimodal_callbacks_
AutomationCallbacks automation_callbacks_
Z3EDCommandCallbacks z3ed_callbacks_
RomSyncCallbacks rom_sync_callbacks_
char session_name_buffer_ [64] = {}
char join_code_buffer_ [64] = {}
char server_url_buffer_ [256] = "ws://localhost:8765"
char multimodal_prompt_buffer_ [256] = {}
absl::Time last_collaboration_action_ = absl::InfinitePast()
absl::Time last_shared_history_poll_ = absl::InfinitePast()
size_t last_known_history_size_ = 0
int active_tab_ = 0
bool show_agent_config_ = false
cli::agent::PromptMode prompt_mode_ = cli::agent::PromptMode::kStandard
bool show_z3ed_commands_ = false
bool show_rom_sync_ = false
bool show_snapshot_preview_ = false
std::vector< uint8_t > snapshot_preview_data_
ImVec4 collaboration_status_color_ = ImVec4(0.6f, 0.6f, 0.6f, 1.0f)
std::vector< FileEditorTab > open_files_
int active_file_tab_ = -1
Detailed Description
Modern AI chat widget with comprehensive z3ed and yaze-server integration.
Features:
AI Provider Configuration (Ollama, Gemini, Mock)
Z3ED Command Palette (run, plan, diff, accept, test)
Real-time Collaboration (Local & Network modes)
ROM Synchronization and Diff Broadcasting
Multimodal Vision (Screenshot Analysis)
Snapshot Sharing with Preview
Collaborative Proposal Management
Tabbed Interface with Modern ImGui patterns
Definition at line 44 of file agent_chat_widget.h.
Member Enumeration Documentation
CollaborationMode
enum class yaze::editor::AgentChatWidget::CollaborationMode strong
Enumerator
kLocal
kNetwork
Definition at line 133 of file agent_chat_widget.h.
CaptureMode
enum class yaze::editor::AgentChatWidget::CaptureMode strong
Enumerator
kFullWindow
kActiveEditor
kSpecificWindow
Definition at line 149 of file agent_chat_widget.h.
Constructor & Destructor Documentation
AgentChatWidget()
yaze::editor::AgentChatWidget::AgentChatWidget ()
Definition at line 111 of file agent_chat_widget.cc.
References active_session_index_, automation_state_, yaze::editor::AgentChatHistoryCodec::Available(), chat_sessions_, history_path_, history_supported_, input_buffer_, yaze::editor::AgentChatWidget::AutomationState::recent_tests, and title_.
Member Function Documentation
Draw()
void yaze::editor::AgentChatWidget::Draw ()
Definition at line 727 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, active_, active_session_index_, agent_config_, agent_service_, yaze::editor::AgentChatWidget::AgentConfigState::ai_model, yaze::editor::AgentChatWidget::AgentConfigState::ai_provider, chat_sessions_, collaboration_state_, collaboration_status_color_, yaze::editor::AgentChatWidget::RomSyncState::current_rom_hash, EnsureHistoryLoaded(), yaze::editor::AgentChatWidget::AgentConfigState::gemini_api_key, yaze::editor::AgentChatWidget::AgentConfigState::gemini_key_buffer, history_loaded_, ICON_MD_ADD, ICON_MD_CHAT, ICON_MD_CHECK_CIRCLE, ICON_MD_DELETE_FOREVER, ICON_MD_MENU, ICON_MD_REFRESH, ICON_MD_SAVE, ICON_MD_SMART_TOY, ICON_MD_SYNC, ICON_MD_TAB, ICON_MD_VISIBILITY, is_active(), yaze::editor::kInfo, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::AgentChatWidget::AgentConfigState::model_buffer, PollSharedHistory(), RenderCollaborationPanel(), RenderHarnessPanel(), RenderHistory(), RenderInputBox(), RenderMultimodalPanel(), RenderProposalManagerPanel(), RenderRomSyncPanel(), RenderSystemPromptEditor(), RenderZ3EDCommandPanel(), yaze::cli::agent::ConversationalAgentService::ResetConversation(), rom_sync_state_, yaze::editor::ToastManager::Show(), yaze::editor::AgentChatWidget::AgentConfigState::show_reasoning, SyncHistoryToPopup(), title_, and toast_manager_.
SetRomContext()
void yaze::editor::AgentChatWidget::SetRomContext (Rom * rom)
Definition at line 125 of file agent_chat_widget.cc.
References agent_service_, ICON_MD_CHECK_CIRCLE, yaze::core::YazeProject::InitializeEmbeddedLabels(), yaze::Rom::is_loaded(), yaze::editor::kSuccess, yaze::core::ResourceLabelManager::labels_, yaze::core::ResourceLabelManager::labels_loaded_, yaze::Rom::resource_label(), yaze::core::YazeProject::resource_labels, yaze::cli::agent::ConversationalAgentService::SetRomContext(), yaze::editor::ToastManager::Show(), yaze::Rom::size(), toast_manager_, and yaze::core::YazeProject::use_embedded_labels.
RenderSnapshotPreviewPanel()
void yaze::editor::AgentChatWidget::RenderSnapshotPreviewPanel ()
Todo:
Load and display image thumbnail
Todo:
Share snapshot via network coordinator
Definition at line 1908 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, collaboration_state_, ICON_MD_CHECK, ICON_MD_IMAGE, ICON_MD_NO_PHOTOGRAPHY, ICON_MD_PHOTO_CAMERA, ICON_MD_SHARE, kNetwork, yaze::editor::kSuccess, yaze::editor::AgentChatWidget::MultimodalState::last_capture_path, yaze::editor::AgentChatWidget::CollaborationState::mode, multimodal_state_, yaze::editor::ToastManager::Show(), and toast_manager_.
SetToastManager()
void yaze::editor::AgentChatWidget::SetToastManager (ToastManager * toast_manager)
Definition at line 157 of file agent_chat_widget.cc.
References toast_manager_.
SetProposalDrawer()
void yaze::editor::AgentChatWidget::SetProposalDrawer (ProposalDrawer * drawer)
Definition at line 161 of file agent_chat_widget.cc.
References yaze::editor::ProposalDrawer::FocusProposal(), pending_focus_proposal_id_, and proposal_drawer_.
SetChatHistoryPopup()
void yaze::editor::AgentChatWidget::SetChatHistoryPopup (AgentChatHistoryPopup * popup)
Definition at line 169 of file agent_chat_widget.cc.
References agent_service_, yaze::editor::AgentChatWidget::MultimodalCallbacks::capture_snapshot, chat_history_popup_, HandleAgentResponse(), ICON_MD_PHOTO, yaze::editor::kError, yaze::editor::kSuccess, yaze::editor::AgentChatWidget::MultimodalState::last_capture_path, yaze::editor::AgentChatWidget::MultimodalState::last_updated, multimodal_callbacks_, multimodal_state_, PersistHistory(), yaze::cli::agent::ConversationalAgentService::SendMessage(), set_active(), yaze::editor::AgentChatHistoryPopup::SetCaptureSnapshotCallback(), yaze::editor::AgentChatHistoryPopup::SetOpenChatCallback(), yaze::editor::AgentChatHistoryPopup::SetSendMessageCallback(), yaze::editor::ToastManager::Show(), SyncHistoryToPopup(), and toast_manager_.
SetCollaborationCallbacks()
void yaze::editor::AgentChatWidget::SetCollaborationCallbacks (const CollaborationCallbacks & callbacks) inline
Definition at line 110 of file agent_chat_widget.h.
References collaboration_callbacks_.
SetMultimodalCallbacks()
void yaze::editor::AgentChatWidget::SetMultimodalCallbacks (const MultimodalCallbacks & callbacks)
Definition at line 2622 of file agent_chat_widget.cc.
References multimodal_callbacks_.
SetAutomationCallbacks()
void yaze::editor::AgentChatWidget::SetAutomationCallbacks (const AutomationCallbacks & callbacks)
Definition at line 2627 of file agent_chat_widget.cc.
References automation_callbacks_.
UpdateHarnessTelemetry()
void yaze::editor::AgentChatWidget::UpdateHarnessTelemetry (const AutomationTelemetry & telemetry)
Definition at line 2632 of file agent_chat_widget.cc.
References automation_state_, yaze::editor::AgentChatWidget::AutomationState::recent_tests, and yaze::editor::AgentChatWidget::AutomationTelemetry::test_id.
SetLastPlanSummary()
void yaze::editor::AgentChatWidget::SetLastPlanSummary (const std::string & summary)
Definition at line 2650 of file agent_chat_widget.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
SetZ3EDCommandCallbacks()
void yaze::editor::AgentChatWidget::SetZ3EDCommandCallbacks (const Z3EDCommandCallbacks & callbacks) inline
Definition at line 120 of file agent_chat_widget.h.
References z3ed_callbacks_.
SetRomSyncCallbacks()
void yaze::editor::AgentChatWidget::SetRomSyncCallbacks (const RomSyncCallbacks & callbacks) inline
Definition at line 124 of file agent_chat_widget.h.
References rom_sync_callbacks_.
active()
bool * yaze::editor::AgentChatWidget::active () inline
Definition at line 128 of file agent_chat_widget.h.
References active_.
Referenced by set_active().
is_active()
bool yaze::editor::AgentChatWidget::is_active () const inline
Definition at line 129 of file agent_chat_widget.h.
References active_.
Referenced by Draw().
set_active()
void yaze::editor::AgentChatWidget::set_active (bool active) inline
Definition at line 130 of file agent_chat_widget.h.
References active(), and active_.
Referenced by SetChatHistoryPopup().
SetPromptMode()
void yaze::editor::AgentChatWidget::SetPromptMode (cli::agent::PromptMode mode) inline
Definition at line 202 of file agent_chat_widget.h.
References prompt_mode_.
GetPromptMode()
cli::agent::PromptMode yaze::editor::AgentChatWidget::GetPromptMode () const inline
Definition at line 203 of file agent_chat_widget.h.
References prompt_mode_.
capture_mode()
CaptureMode yaze::editor::AgentChatWidget::capture_mode () const inline
Definition at line 206 of file agent_chat_widget.h.
References yaze::editor::AgentChatWidget::MultimodalState::capture_mode, and multimodal_state_.
specific_window_name()
const char * yaze::editor::AgentChatWidget::specific_window_name () const inline
Definition at line 207 of file agent_chat_widget.h.
References multimodal_state_, and yaze::editor::AgentChatWidget::MultimodalState::specific_window_buffer.
GetAgentConfig()
const AgentConfigState & yaze::editor::AgentChatWidget::GetAgentConfig () const inline
Definition at line 212 of file agent_chat_widget.h.
References agent_config_.
UpdateAgentConfig()
void yaze::editor::AgentChatWidget::UpdateAgentConfig (const AgentConfigState & config)
Definition at line 1642 of file agent_chat_widget.cc.
References agent_config_, agent_service_, yaze::editor::kSuccess, yaze::editor::AgentChatWidget::AgentConfigState::max_retry_attempts, yaze::cli::agent::AgentConfig::max_retry_attempts, yaze::editor::AgentChatWidget::AgentConfigState::max_tool_iterations, yaze::cli::agent::AgentConfig::max_tool_iterations, yaze::cli::agent::ConversationalAgentService::SetConfig(), yaze::editor::ToastManager::Show(), yaze::editor::AgentChatWidget::AgentConfigState::show_reasoning, yaze::cli::agent::AgentConfig::show_reasoning, toast_manager_, yaze::editor::AgentChatWidget::AgentConfigState::verbose, and yaze::cli::agent::AgentConfig::verbose.
Referenced by RenderAgentConfigPanel().
LoadAgentSettingsFromProject()
void yaze::editor::AgentChatWidget::LoadAgentSettingsFromProject (const core::YazeProject & project)
Definition at line 2539 of file agent_chat_widget.cc.
References agent_config_, yaze::core::YazeProject::agent_settings, yaze::core::YazeProject::AgentSettings::ai_model, yaze::editor::AgentChatWidget::AgentConfigState::ai_model, yaze::core::YazeProject::AgentSettings::ai_provider, yaze::editor::AgentChatWidget::AgentConfigState::ai_provider, TextEditor::LanguageDefinition::CPlusPlus(), yaze::core::YazeProject::AgentSettings::custom_system_prompt, yaze::editor::AgentChatWidget::FileEditorTab::editor, yaze::editor::AgentChatWidget::FileEditorTab::filename, yaze::editor::AgentChatWidget::FileEditorTab::filepath, yaze::core::YazeProject::AgentSettings::gemini_api_key, yaze::editor::AgentChatWidget::AgentConfigState::gemini_api_key, yaze::editor::AgentChatWidget::AgentConfigState::gemini_key_buffer, yaze::core::YazeProject::GetAbsolutePath(), yaze::util::GetFileName(), yaze::editor::AgentChatWidget::FileEditorTab::is_system_prompt, yaze::core::YazeProject::AgentSettings::max_retry_attempts, yaze::editor::AgentChatWidget::AgentConfigState::max_retry_attempts, yaze::core::YazeProject::AgentSettings::max_tool_iterations, yaze::editor::AgentChatWidget::AgentConfigState::max_tool_iterations, yaze::editor::AgentChatWidget::AgentConfigState::model_buffer, yaze::core::YazeProject::AgentSettings::ollama_host, yaze::editor::AgentChatWidget::AgentConfigState::ollama_host, yaze::editor::AgentChatWidget::AgentConfigState::ollama_host_buffer, open_files_, yaze::editor::AgentChatWidget::AgentConfigState::provider_buffer, TextEditor::SetLanguageDefinition(), TextEditor::SetText(), yaze::core::YazeProject::AgentSettings::show_reasoning, yaze::editor::AgentChatWidget::AgentConfigState::show_reasoning, yaze::core::YazeProject::AgentSettings::use_custom_prompt, yaze::core::YazeProject::AgentSettings::verbose, and yaze::editor::AgentChatWidget::AgentConfigState::verbose.
SaveAgentSettingsToProject()
void yaze::editor::AgentChatWidget::SaveAgentSettingsToProject (core::YazeProject & project)
Definition at line 2599 of file agent_chat_widget.cc.
References agent_config_, yaze::core::YazeProject::agent_settings, yaze::core::YazeProject::AgentSettings::ai_model, yaze::editor::AgentChatWidget::AgentConfigState::ai_model, yaze::core::YazeProject::AgentSettings::ai_provider, yaze::editor::AgentChatWidget::AgentConfigState::ai_provider, yaze::core::YazeProject::AgentSettings::custom_system_prompt, yaze::core::YazeProject::AgentSettings::gemini_api_key, yaze::editor::AgentChatWidget::AgentConfigState::gemini_api_key, yaze::core::YazeProject::GetRelativePath(), yaze::core::YazeProject::AgentSettings::max_retry_attempts, yaze::editor::AgentChatWidget::AgentConfigState::max_retry_attempts, yaze::core::YazeProject::AgentSettings::max_tool_iterations, yaze::editor::AgentChatWidget::AgentConfigState::max_tool_iterations, yaze::core::YazeProject::AgentSettings::ollama_host, yaze::editor::AgentChatWidget::AgentConfigState::ollama_host, open_files_, yaze::core::YazeProject::AgentSettings::show_reasoning, yaze::editor::AgentChatWidget::AgentConfigState::show_reasoning, yaze::core::YazeProject::AgentSettings::use_custom_prompt, yaze::core::YazeProject::AgentSettings::verbose, and yaze::editor::AgentChatWidget::AgentConfigState::verbose.
SwitchToSharedHistory()
void yaze::editor::AgentChatWidget::SwitchToSharedHistory (const std::string & session_id)
Definition at line 1559 of file agent_chat_widget.cc.
References agent_service_, EnsureHistoryLoaded(), yaze::cli::agent::ConversationalAgentService::GetHistory(), history_dirty_, history_loaded_, history_path_, yaze::editor::kInfo, last_known_history_size_, last_shared_history_poll_, PersistHistory(), yaze::editor::ToastManager::Show(), and toast_manager_.
SwitchToLocalHistory()
void yaze::editor::AgentChatWidget::SwitchToLocalHistory ()
Definition at line 1584 of file agent_chat_widget.cc.
References EnsureHistoryLoaded(), history_dirty_, history_loaded_, history_path_, yaze::editor::kInfo, PersistHistory(), yaze::editor::ToastManager::Show(), and toast_manager_.
OpenFileInEditor()
void yaze::editor::AgentChatWidget::OpenFileInEditor (const std::string & filepath)
Definition at line 2469 of file agent_chat_widget.cc.
References active_file_tab_, TextEditor::LanguageDefinition::C(), TextEditor::LanguageDefinition::CPlusPlus(), yaze::editor::AgentChatWidget::FileEditorTab::editor, yaze::editor::AgentChatWidget::FileEditorTab::filename, yaze::editor::AgentChatWidget::FileEditorTab::filepath, yaze::util::GetFileExtension(), yaze::editor::kError, yaze::editor::kSuccess, TextEditor::LanguageDefinition::Lua(), open_files_, TextEditor::SetLanguageDefinition(), TextEditor::SetText(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by RenderFileEditorTabs().
CreateNewFileInEditor()
void yaze::editor::AgentChatWidget::CreateNewFileInEditor (const std::string & filename)
Definition at line 2519 of file agent_chat_widget.cc.
References active_file_tab_, TextEditor::LanguageDefinition::C(), TextEditor::LanguageDefinition::CPlusPlus(), yaze::editor::AgentChatWidget::FileEditorTab::editor, yaze::editor::AgentChatWidget::FileEditorTab::filename, yaze::util::GetFileExtension(), TextEditor::LanguageDefinition::Lua(), yaze::editor::AgentChatWidget::FileEditorTab::modified, open_files_, and TextEditor::SetLanguageDefinition().
Referenced by RenderFileEditorTabs().
EnsureHistoryLoaded()
void yaze::editor::AgentChatWidget::EnsureHistoryLoaded () private
Definition at line 212 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, agent_service_, yaze::editor::AgentChatHistoryCodec::Snapshot::collaboration, collaboration_state_, CountKnownProposals(), yaze::cli::agent::ConversationalAgentService::GetHistory(), yaze::editor::AgentChatHistoryCodec::Snapshot::history, history_dirty_, history_loaded_, history_path_, history_supported_, history_warning_displayed_, yaze::editor::kError, yaze::editor::kInfo, yaze::editor::kWarning, yaze::editor::AgentChatWidget::MultimodalState::last_capture_path, last_history_size_, last_persist_time_, last_proposal_count_, yaze::editor::AgentChatWidget::CollaborationState::last_synced, yaze::editor::AgentChatWidget::MultimodalState::last_updated, yaze::editor::AgentChatHistoryCodec::Load(), yaze::editor::AgentChatHistoryCodec::Snapshot::multimodal, multimodal_state_, yaze::editor::AgentChatWidget::CollaborationState::participants, yaze::cli::agent::ConversationalAgentService::ReplaceHistory(), yaze::editor::AgentChatWidget::CollaborationState::session_id, yaze::editor::AgentChatWidget::CollaborationState::session_name, yaze::editor::ToastManager::Show(), yaze::editor::AgentChatWidget::MultimodalState::status_message, and toast_manager_.
Referenced by Draw(), RenderInputBox(), SwitchToLocalHistory(), and SwitchToSharedHistory().
PersistHistory()
void yaze::editor::AgentChatWidget::PersistHistory () private
Definition at line 290 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, agent_service_, yaze::editor::AgentChatHistoryCodec::Snapshot::collaboration, collaboration_state_, yaze::cli::agent::ConversationalAgentService::GetHistory(), yaze::editor::AgentChatHistoryCodec::Snapshot::history, history_dirty_, history_loaded_, history_path_, history_supported_, history_warning_displayed_, yaze::editor::kError, yaze::editor::kWarning, yaze::editor::AgentChatWidget::MultimodalState::last_capture_path, last_persist_time_, yaze::editor::AgentChatWidget::CollaborationState::last_synced, yaze::editor::AgentChatWidget::MultimodalState::last_updated, yaze::editor::AgentChatHistoryCodec::Snapshot::multimodal, multimodal_state_, yaze::editor::AgentChatWidget::CollaborationState::participants, yaze::editor::AgentChatHistoryCodec::Save(), yaze::editor::AgentChatWidget::CollaborationState::session_id, yaze::editor::AgentChatWidget::CollaborationState::session_name, yaze::editor::ToastManager::Show(), yaze::editor::AgentChatWidget::MultimodalState::status_message, SyncHistoryToPopup(), and toast_manager_.
Referenced by MarkHistoryDirty(), RenderInputBox(), SetChatHistoryPopup(), SwitchToLocalHistory(), and SwitchToSharedHistory().
RenderHistory()
void yaze::editor::AgentChatWidget::RenderHistory () private
Definition at line 525 of file agent_chat_widget.cc.
References agent_service_, yaze::cli::agent::ConversationalAgentService::GetHistory(), ICON_MD_CHAT, last_history_size_, and RenderMessage().
Referenced by Draw().
RenderMessage()
void yaze::editor::AgentChatWidget::RenderMessage (const cli::agent::ChatMessage & msg, int index) private
Definition at line 419 of file agent_chat_widget.cc.
References ICON_MD_CONTENT_COPY, ICON_MD_DATA_OBJECT, yaze::editor::kSuccess, RenderProposalQuickActions(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by RenderHistory().
RenderProposalQuickActions()
void yaze::editor::AgentChatWidget::RenderProposalQuickActions (const cli::agent::ChatMessage & msg, int index) private
Definition at line 480 of file agent_chat_widget.cc.
References FocusProposalDrawer(), ICON_MD_CONTENT_COPY, ICON_MD_PREVIEW, ICON_MD_VISIBILITY, yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by RenderMessage().
RenderInputBox()
void yaze::editor::AgentChatWidget::RenderInputBox () private
Definition at line 562 of file agent_chat_widget.cc.
References agent_service_, yaze::editor::AgentChatWidget::MultimodalCallbacks::capture_snapshot, EnsureHistoryLoaded(), HandleAgentResponse(), history_dirty_, ICON_MD_DELETE_FOREVER, ICON_MD_EDIT, ICON_MD_IMAGE, ICON_MD_INFO, ICON_MD_PHOTO_CAMERA, ICON_MD_PREVIEW, ICON_MD_SAVE, ICON_MD_SEND, ICON_MD_STOP, input_buffer_, yaze::editor::kError, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::AgentChatWidget::MultimodalState::last_capture_path, multimodal_callbacks_, multimodal_prompt_buffer_, multimodal_state_, pending_message_, PersistHistory(), proposal_drawer_, yaze::cli::agent::ConversationalAgentService::ResetConversation(), yaze::editor::AgentChatWidget::MultimodalCallbacks::send_to_gemini, yaze::cli::agent::ConversationalAgentService::SendMessage(), yaze::editor::ToastManager::Show(), toast_manager_, and waiting_for_response_.
Referenced by Draw().
HandleAgentResponse()
void yaze::editor::AgentChatWidget::HandleAgentResponse (const absl::StatusOr< cli::agent::ChatMessage > & response) private
Definition at line 393 of file agent_chat_widget.cc.
References CountKnownProposals(), yaze::editor::kError, last_proposal_count_, NotifyProposalCreated(), yaze::editor::ToastManager::Show(), SyncHistoryToPopup(), and toast_manager_.
Referenced by RenderInputBox(), and SetChatHistoryPopup().
CountKnownProposals()
int yaze::editor::AgentChatWidget::CountKnownProposals () const private
Definition at line 346 of file agent_chat_widget.cc.
References agent_service_, and yaze::cli::agent::ConversationalAgentService::GetHistory().
Referenced by EnsureHistoryLoaded(), and HandleAgentResponse().
FocusProposalDrawer()
void yaze::editor::AgentChatWidget::FocusProposalDrawer (const std::string & proposal_id) private
Definition at line 359 of file agent_chat_widget.cc.
References yaze::editor::ProposalDrawer::FocusProposal(), pending_focus_proposal_id_, and proposal_drawer_.
Referenced by NotifyProposalCreated(), RenderProposalManagerPanel(), and RenderProposalQuickActions().
NotifyProposalCreated()
void yaze::editor::AgentChatWidget::NotifyProposalCreated (const cli::agent::ChatMessage & msg, int new_total_proposals) private
Definition at line 369 of file agent_chat_widget.cc.
References FocusProposalDrawer(), ICON_MD_PREVIEW, yaze::editor::kSuccess, last_proposal_count_, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by HandleAgentResponse().
RenderCollaborationPanel()
void yaze::editor::AgentChatWidget::RenderCollaborationPanel () private
Definition at line 1068 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, ApplyCollaborationSession(), collaboration_callbacks_, collaboration_state_, collaboration_status_color_, yaze::editor::AgentChatWidget::CollaborationCallbacks::host_session, ICON_MD_ACCESS_TIME, ICON_MD_ADD_CIRCLE, ICON_MD_CANCEL, ICON_MD_CHECK_CIRCLE, ICON_MD_CLOUD, ICON_MD_CONTENT_COPY, ICON_MD_FOLDER, ICON_MD_INFO, ICON_MD_KEY, ICON_MD_LABEL, ICON_MD_LINK, ICON_MD_LOGIN, ICON_MD_LOGOUT, ICON_MD_MEETING_ROOM, ICON_MD_PEOPLE, ICON_MD_PERSON, ICON_MD_REFRESH, ICON_MD_ROCKET_LAUNCH, ICON_MD_SETTINGS_ETHERNET, ICON_MD_WIFI, join_code_buffer_, yaze::editor::AgentChatWidget::CollaborationCallbacks::join_session, yaze::editor::kError, yaze::editor::kInfo, kLocal, kNetwork, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::AgentChatWidget::CollaborationState::last_synced, yaze::editor::AgentChatWidget::CollaborationCallbacks::leave_session, MarkHistoryDirty(), yaze::editor::AgentChatWidget::CollaborationState::mode, yaze::editor::AgentChatWidget::CollaborationState::participants, yaze::editor::AgentChatWidget::CollaborationCallbacks::refresh_session, RefreshCollaboration(), yaze::editor::AgentChatWidget::CollaborationState::server_url, server_url_buffer_, yaze::editor::AgentChatWidget::CollaborationState::session_id, yaze::editor::AgentChatWidget::CollaborationState::session_name, session_name_buffer_, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by Draw().
RenderMultimodalPanel()
void yaze::editor::AgentChatWidget::RenderMultimodalPanel () private
Definition at line 1404 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::MultimodalState::capture_mode, yaze::editor::AgentChatWidget::MultimodalCallbacks::capture_snapshot, ICON_MD_CAMERA, ICON_MD_CAMERA_ALT, ICON_MD_CHECK_CIRCLE, ICON_MD_PHOTO_CAMERA, ICON_MD_SEND, kActiveEditor, yaze::editor::kError, kFullWindow, kSpecificWindow, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::AgentChatWidget::MultimodalState::last_capture_path, yaze::editor::AgentChatWidget::MultimodalState::last_updated, MarkHistoryDirty(), multimodal_callbacks_, multimodal_prompt_buffer_, multimodal_state_, yaze::editor::AgentChatWidget::MultimodalCallbacks::send_to_gemini, yaze::editor::ToastManager::Show(), yaze::editor::AgentChatWidget::MultimodalState::status_message, and toast_manager_.
Referenced by Draw().
RenderAgentConfigPanel()
void yaze::editor::AgentChatWidget::RenderAgentConfigPanel () private
Definition at line 1660 of file agent_chat_widget.cc.
References agent_config_, yaze::editor::AgentChatWidget::AgentConfigState::ai_model, yaze::editor::AgentChatWidget::AgentConfigState::ai_provider, yaze::editor::AgentChatWidget::AgentConfigState::gemini_api_key, yaze::editor::AgentChatWidget::AgentConfigState::gemini_key_buffer, ICON_MD_CHECK, ICON_MD_SETTINGS, yaze::editor::AgentChatWidget::AgentConfigState::max_tool_iterations, yaze::editor::AgentChatWidget::AgentConfigState::model_buffer, yaze::editor::AgentChatWidget::AgentConfigState::ollama_host, yaze::editor::AgentChatWidget::AgentConfigState::ollama_host_buffer, yaze::editor::AgentChatWidget::AgentConfigState::provider_buffer, yaze::editor::AgentChatWidget::AgentConfigState::show_reasoning, UpdateAgentConfig(), and yaze::editor::AgentChatWidget::AgentConfigState::verbose.
RenderZ3EDCommandPanel()
void yaze::editor::AgentChatWidget::RenderZ3EDCommandPanel () private
Definition at line 1726 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::accept_proposal, yaze::editor::AgentChatWidget::Z3EDCommandState::command_input_buffer, yaze::editor::AgentChatWidget::Z3EDCommandState::command_output, yaze::editor::AgentChatWidget::Z3EDCommandState::command_running, yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::diff_proposal, ICON_MD_CHECK, ICON_MD_CLOSE, ICON_MD_DIFFERENCE, ICON_MD_PLAY_ARROW, ICON_MD_PREVIEW, ICON_MD_TERMINAL, yaze::editor::kSuccess, yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::list_proposals, yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::reject_proposal, yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::run_agent_task, yaze::editor::ToastManager::Show(), toast_manager_, z3ed_callbacks_, and z3ed_command_state_.
Referenced by Draw().
RenderRomSyncPanel()
void yaze::editor::AgentChatWidget::RenderRomSyncPanel () private
Todo:
Send via network coordinator
Definition at line 1811 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, yaze::editor::AgentChatWidget::RomSyncState::auto_sync_enabled, collaboration_state_, yaze::editor::AgentChatWidget::RomSyncState::current_rom_hash, yaze::editor::AgentChatWidget::RomSyncCallbacks::generate_rom_diff, yaze::editor::AgentChatWidget::RomSyncCallbacks::get_rom_hash, ICON_MD_CLOUD_DONE, ICON_MD_CLOUD_UPLOAD, ICON_MD_CONTENT_COPY, ICON_MD_ERROR, ICON_MD_PENDING, ICON_MD_STORAGE, yaze::editor::kError, yaze::editor::kInfo, kNetwork, yaze::editor::kSuccess, yaze::editor::AgentChatWidget::RomSyncState::last_sync_time, yaze::editor::AgentChatWidget::CollaborationState::mode, yaze::editor::AgentChatWidget::RomSyncState::pending_syncs, rom_sync_callbacks_, rom_sync_state_, yaze::editor::ToastManager::Show(), yaze::editor::AgentChatWidget::RomSyncState::sync_interval_seconds, and toast_manager_.
Referenced by Draw().
RenderProposalManagerPanel()
void yaze::editor::AgentChatWidget::RenderProposalManagerPanel () private
Definition at line 1958 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::accept_proposal, FocusProposalDrawer(), ICON_MD_CHECK, ICON_MD_CLOSE, ICON_MD_PREVIEW, ICON_MD_VISIBILITY, yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::list_proposals, yaze::editor::AgentChatWidget::Z3EDCommandCallbacks::reject_proposal, and z3ed_callbacks_.
Referenced by Draw().
RenderHarnessPanel()
void yaze::editor::AgentChatWidget::RenderHarnessPanel () private
Definition at line 2034 of file agent_chat_widget.cc.
References automation_callbacks_, automation_state_, yaze::editor::AgentChatWidget::AutomationCallbacks::focus_proposal, ICON_MD_DASHBOARD, ICON_MD_LIST, ICON_MD_PLAY_CIRCLE, ICON_MD_QUERY_STATS, ICON_MD_REPLAY, ICON_MD_VISIBILITY, yaze::editor::AgentChatWidget::AutomationCallbacks::open_harness_dashboard, pending_focus_proposal_id_, yaze::editor::AgentChatWidget::AutomationState::recent_tests, yaze::editor::AgentChatWidget::AutomationCallbacks::replay_last_plan, and yaze::editor::AgentChatWidget::AutomationCallbacks::show_active_tests.
Referenced by Draw().
RenderSystemPromptEditor()
void yaze::editor::AgentChatWidget::RenderSystemPromptEditor () private
Definition at line 2155 of file agent_chat_widget.cc.
References active_file_tab_, TextEditor::LanguageDefinition::CPlusPlus(), yaze::editor::AgentChatWidget::FileEditorTab::editor, yaze::editor::AgentChatWidget::FileEditorTab::filename, yaze::editor::AgentChatWidget::FileEditorTab::filepath, yaze::util::GetFileName(), ICON_MD_FOLDER_OPEN, ICON_MD_NOTE_ADD, ICON_MD_SAVE, yaze::editor::AgentChatWidget::FileEditorTab::is_system_prompt, yaze::editor::kError, yaze::editor::kSuccess, yaze::util::LoadFile(), yaze::editor::AgentChatWidget::FileEditorTab::modified, open_files_, TextEditor::SetLanguageDefinition(), TextEditor::SetText(), yaze::editor::ToastManager::Show(), yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::util::FileDialogWrapper::ShowSaveFileDialog(), and toast_manager_.
Referenced by Draw().
RenderFileEditorTabs()
void yaze::editor::AgentChatWidget::RenderFileEditorTabs () private
Definition at line 2347 of file agent_chat_widget.cc.
References active_file_tab_, CreateNewFileInEditor(), ICON_MD_FOLDER_OPEN, ICON_MD_NOTE_ADD, ICON_MD_SAVE, yaze::editor::kError, yaze::editor::kSuccess, open_files_, OpenFileInEditor(), yaze::editor::ToastManager::Show(), yaze::util::FileDialogWrapper::ShowOpenFileDialog(), yaze::util::FileDialogWrapper::ShowSaveFileDialog(), and toast_manager_.
RefreshCollaboration()
void yaze::editor::AgentChatWidget::RefreshCollaboration () private
Definition at line 1512 of file agent_chat_widget.cc.
References ApplyCollaborationSession(), collaboration_callbacks_, collaboration_state_, join_code_buffer_, yaze::editor::kError, MarkHistoryDirty(), yaze::editor::AgentChatWidget::CollaborationCallbacks::refresh_session, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by RenderCollaborationPanel().
ApplyCollaborationSession()
void yaze::editor::AgentChatWidget::ApplyCollaborationSession (const CollaborationCallbacks::SessionContext & context, bool update_action_timestamp) private
Definition at line 1536 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, collaboration_state_, last_collaboration_action_, yaze::editor::AgentChatWidget::CollaborationState::last_synced, yaze::editor::AgentChatWidget::CollaborationCallbacks::SessionContext::participants, yaze::editor::AgentChatWidget::CollaborationState::participants, yaze::editor::AgentChatWidget::CollaborationCallbacks::SessionContext::session_id, yaze::editor::AgentChatWidget::CollaborationState::session_id, yaze::editor::AgentChatWidget::CollaborationCallbacks::SessionContext::session_name, and yaze::editor::AgentChatWidget::CollaborationState::session_name.
Referenced by RefreshCollaboration(), and RenderCollaborationPanel().
MarkHistoryDirty()
void yaze::editor::AgentChatWidget::MarkHistoryDirty () private
Definition at line 1550 of file agent_chat_widget.cc.
References history_dirty_, last_persist_time_, and PersistHistory().
Referenced by RefreshCollaboration(), RenderCollaborationPanel(), and RenderMultimodalPanel().
PollSharedHistory()
void yaze::editor::AgentChatWidget::PollSharedHistory () private
Definition at line 1603 of file agent_chat_widget.cc.
References yaze::editor::AgentChatWidget::CollaborationState::active, agent_service_, collaboration_state_, history_path_, yaze::editor::kInfo, last_history_size_, last_known_history_size_, last_shared_history_poll_, yaze::editor::AgentChatHistoryCodec::Load(), yaze::cli::agent::ConversationalAgentService::ReplaceHistory(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by Draw().
HandleRomSyncReceived()
void yaze::editor::AgentChatWidget::HandleRomSyncReceived (const std::string & diff_data, const std::string & rom_hash) private
HandleSnapshotReceived()
void yaze::editor::AgentChatWidget::HandleSnapshotReceived (const std::string & snapshot_data, const std::string & snapshot_type) private
HandleProposalReceived()
void yaze::editor::AgentChatWidget::HandleProposalReceived (const std::string & proposal_data) private
SyncHistoryToPopup()
void yaze::editor::AgentChatWidget::SyncHistoryToPopup () private
Definition at line 2658 of file agent_chat_widget.cc.
References agent_service_, chat_history_popup_, yaze::cli::agent::ConversationalAgentService::GetHistory(), and yaze::editor::AgentChatHistoryPopup::UpdateHistory().
Referenced by Draw(), HandleAgentResponse(), PersistHistory(), and SetChatHistoryPopup().
SaveChatSession()
void yaze::editor::AgentChatWidget::SaveChatSession (const ChatSession & session) private
LoadChatSession()
void yaze::editor::AgentChatWidget::LoadChatSession (const std::string & session_id) private
DeleteChatSession()
void yaze::editor::AgentChatWidget::DeleteChatSession (const std::string & session_id) private
GetSavedSessions()
std::vector< std::string > yaze::editor::AgentChatWidget::GetSavedSessions () private
GetSessionsDirectory()
std::filesystem::path yaze::editor::AgentChatWidget::GetSessionsDirectory () private
Member Data Documentation
waiting_for_response_
bool yaze::editor::AgentChatWidget::waiting_for_response_ = false private
Definition at line 264 of file agent_chat_widget.h.
Referenced by RenderInputBox().
thinking_animation_
float yaze::editor::AgentChatWidget::thinking_animation_ = 0.0f private
Definition at line 265 of file agent_chat_widget.h.
pending_message_
std::string yaze::editor::AgentChatWidget::pending_message_ private
Definition at line 266 of file agent_chat_widget.h.
Referenced by RenderInputBox().
chat_sessions_
std::vector<ChatSession> yaze::editor::AgentChatWidget::chat_sessions_ private
Definition at line 291 of file agent_chat_widget.h.
Referenced by AgentChatWidget(), and Draw().
active_session_index_
int yaze::editor::AgentChatWidget::active_session_index_ = 0 private
Definition at line 292 of file agent_chat_widget.h.
Referenced by AgentChatWidget(), and Draw().
agent_service_
cli::agent::ConversationalAgentService yaze::editor::AgentChatWidget::agent_service_ private
Definition at line 295 of file agent_chat_widget.h.
Referenced by CountKnownProposals(), Draw(), EnsureHistoryLoaded(), PersistHistory(), PollSharedHistory(), RenderHistory(), RenderInputBox(), SetChatHistoryPopup(), SetRomContext(), SwitchToSharedHistory(), SyncHistoryToPopup(), and UpdateAgentConfig().
input_buffer_
char yaze::editor::AgentChatWidget::input_buffer_[1024] private
Definition at line 296 of file agent_chat_widget.h.
Referenced by AgentChatWidget(), and RenderInputBox().
active_
bool yaze::editor::AgentChatWidget::active_ = false private
Definition at line 297 of file agent_chat_widget.h.
Referenced by active(), Draw(), is_active(), and set_active().
title_
std::string yaze::editor::AgentChatWidget::title_ private
Definition at line 298 of file agent_chat_widget.h.
Referenced by AgentChatWidget(), and Draw().
last_history_size_
size_t yaze::editor::AgentChatWidget::last_history_size_ = 0 private
Definition at line 299 of file agent_chat_widget.h.
Referenced by EnsureHistoryLoaded(), PollSharedHistory(), and RenderHistory().
history_loaded_
bool yaze::editor::AgentChatWidget::history_loaded_ = false private
Definition at line 300 of file agent_chat_widget.h.
Referenced by Draw(), EnsureHistoryLoaded(), PersistHistory(), SwitchToLocalHistory(), and SwitchToSharedHistory().
history_dirty_
bool yaze::editor::AgentChatWidget::history_dirty_ = false private
Definition at line 301 of file agent_chat_widget.h.
Referenced by EnsureHistoryLoaded(), MarkHistoryDirty(), PersistHistory(), RenderInputBox(), SwitchToLocalHistory(), and SwitchToSharedHistory().
history_supported_
bool yaze::editor::AgentChatWidget::history_supported_ = true private
Definition at line 302 of file agent_chat_widget.h.
Referenced by AgentChatWidget(), EnsureHistoryLoaded(), and PersistHistory().
history_warning_displayed_
bool yaze::editor::AgentChatWidget::history_warning_displayed_ = false private
Definition at line 303 of file agent_chat_widget.h.
Referenced by EnsureHistoryLoaded(), and PersistHistory().
history_path_
std::filesystem::path yaze::editor::AgentChatWidget::history_path_ private
Definition at line 304 of file agent_chat_widget.h.
Referenced by AgentChatWidget(), EnsureHistoryLoaded(), PersistHistory(), PollSharedHistory(), SwitchToLocalHistory(), and SwitchToSharedHistory().
last_proposal_count_
int yaze::editor::AgentChatWidget::last_proposal_count_ = 0 private
Definition at line 305 of file agent_chat_widget.h.
Referenced by EnsureHistoryLoaded(), HandleAgentResponse(), and NotifyProposalCreated().
toast_manager_
ToastManager* yaze::editor::AgentChatWidget::toast_manager_ = nullptr private
Definition at line 306 of file agent_chat_widget.h.
Referenced by Draw(), EnsureHistoryLoaded(), HandleAgentResponse(), NotifyProposalCreated(), OpenFileInEditor(), PersistHistory(), PollSharedHistory(), RefreshCollaboration(), RenderCollaborationPanel(), RenderFileEditorTabs(), RenderInputBox(), RenderMessage(), RenderMultimodalPanel(), RenderProposalQuickActions(), RenderRomSyncPanel(), RenderSnapshotPreviewPanel(), RenderSystemPromptEditor(), RenderZ3EDCommandPanel(), SetChatHistoryPopup(), SetLastPlanSummary(), SetRomContext(), SetToastManager(), SwitchToLocalHistory(), SwitchToSharedHistory(), and UpdateAgentConfig().
proposal_drawer_
ProposalDrawer* yaze::editor::AgentChatWidget::proposal_drawer_ = nullptr private
Definition at line 307 of file agent_chat_widget.h.
Referenced by FocusProposalDrawer(), RenderInputBox(), and SetProposalDrawer().
chat_history_popup_
AgentChatHistoryPopup* yaze::editor::AgentChatWidget::chat_history_popup_ = nullptr private
Definition at line 308 of file agent_chat_widget.h.
Referenced by SetChatHistoryPopup(), and SyncHistoryToPopup().
pending_focus_proposal_id_
std::string yaze::editor::AgentChatWidget::pending_focus_proposal_id_ private
Definition at line 309 of file agent_chat_widget.h.
Referenced by FocusProposalDrawer(), RenderHarnessPanel(), and SetProposalDrawer().
last_persist_time_
absl::Time yaze::editor::AgentChatWidget::last_persist_time_ = absl::InfinitePast() private
Definition at line 310 of file agent_chat_widget.h.
Referenced by EnsureHistoryLoaded(), MarkHistoryDirty(), and PersistHistory().
collaboration_state_
CollaborationState yaze::editor::AgentChatWidget::collaboration_state_ private
Definition at line 313 of file agent_chat_widget.h.
Referenced by ApplyCollaborationSession(), Draw(), EnsureHistoryLoaded(), PersistHistory(), PollSharedHistory(), RefreshCollaboration(), RenderCollaborationPanel(), RenderRomSyncPanel(), and RenderSnapshotPreviewPanel().
multimodal_state_
MultimodalState yaze::editor::AgentChatWidget::multimodal_state_ private
Definition at line 314 of file agent_chat_widget.h.
Referenced by capture_mode(), EnsureHistoryLoaded(), PersistHistory(), RenderInputBox(), RenderMultimodalPanel(), RenderSnapshotPreviewPanel(), SetChatHistoryPopup(), and specific_window_name().
automation_state_
AutomationState yaze::editor::AgentChatWidget::automation_state_ private
Definition at line 315 of file agent_chat_widget.h.
Referenced by AgentChatWidget(), RenderHarnessPanel(), and UpdateHarnessTelemetry().
agent_config_
AgentConfigState yaze::editor::AgentChatWidget::agent_config_ private
Definition at line 316 of file agent_chat_widget.h.
Referenced by Draw(), GetAgentConfig(), LoadAgentSettingsFromProject(), RenderAgentConfigPanel(), SaveAgentSettingsToProject(), and UpdateAgentConfig().
rom_sync_state_
RomSyncState yaze::editor::AgentChatWidget::rom_sync_state_ private
Definition at line 317 of file agent_chat_widget.h.
Referenced by Draw(), and RenderRomSyncPanel().
z3ed_command_state_
Z3EDCommandState yaze::editor::AgentChatWidget::z3ed_command_state_ private
Definition at line 318 of file agent_chat_widget.h.
Referenced by RenderZ3EDCommandPanel().
collaboration_callbacks_
CollaborationCallbacks yaze::editor::AgentChatWidget::collaboration_callbacks_ private
Definition at line 321 of file agent_chat_widget.h.
Referenced by RefreshCollaboration(), RenderCollaborationPanel(), and SetCollaborationCallbacks().
multimodal_callbacks_
MultimodalCallbacks yaze::editor::AgentChatWidget::multimodal_callbacks_ private
Definition at line 322 of file agent_chat_widget.h.
Referenced by RenderInputBox(), RenderMultimodalPanel(), SetChatHistoryPopup(), and SetMultimodalCallbacks().
automation_callbacks_
AutomationCallbacks yaze::editor::AgentChatWidget::automation_callbacks_ private
Definition at line 323 of file agent_chat_widget.h.
Referenced by RenderHarnessPanel(), and SetAutomationCallbacks().
z3ed_callbacks_
Z3EDCommandCallbacks yaze::editor::AgentChatWidget::z3ed_callbacks_ private
Definition at line 324 of file agent_chat_widget.h.
Referenced by RenderProposalManagerPanel(), RenderZ3EDCommandPanel(), and SetZ3EDCommandCallbacks().
rom_sync_callbacks_
RomSyncCallbacks yaze::editor::AgentChatWidget::rom_sync_callbacks_ private
Definition at line 325 of file agent_chat_widget.h.
Referenced by RenderRomSyncPanel(), and SetRomSyncCallbacks().
session_name_buffer_
char yaze::editor::AgentChatWidget::session_name_buffer_[64] = {} private
Definition at line 328 of file agent_chat_widget.h.
Referenced by RenderCollaborationPanel().
join_code_buffer_
char yaze::editor::AgentChatWidget::join_code_buffer_[64] = {} private
Definition at line 329 of file agent_chat_widget.h.
Referenced by RefreshCollaboration(), and RenderCollaborationPanel().
server_url_buffer_
char yaze::editor::AgentChatWidget::server_url_buffer_[256] = "ws://localhost:8765" private
Definition at line 330 of file agent_chat_widget.h.
Referenced by RenderCollaborationPanel().
multimodal_prompt_buffer_
char yaze::editor::AgentChatWidget::multimodal_prompt_buffer_[256] = {} private
Definition at line 331 of file agent_chat_widget.h.
Referenced by RenderInputBox(), and RenderMultimodalPanel().
last_collaboration_action_
absl::Time yaze::editor::AgentChatWidget::last_collaboration_action_ = absl::InfinitePast() private
Definition at line 334 of file agent_chat_widget.h.
Referenced by ApplyCollaborationSession().
last_shared_history_poll_
absl::Time yaze::editor::AgentChatWidget::last_shared_history_poll_ = absl::InfinitePast() private
Definition at line 335 of file agent_chat_widget.h.
Referenced by PollSharedHistory(), and SwitchToSharedHistory().
last_known_history_size_
size_t yaze::editor::AgentChatWidget::last_known_history_size_ = 0 private
Definition at line 336 of file agent_chat_widget.h.
Referenced by PollSharedHistory(), and SwitchToSharedHistory().
active_tab_
int yaze::editor::AgentChatWidget::active_tab_ = 0 private
Definition at line 339 of file agent_chat_widget.h.
show_agent_config_
bool yaze::editor::AgentChatWidget::show_agent_config_ = false private
Definition at line 340 of file agent_chat_widget.h.
prompt_mode_
cli::agent::PromptMode yaze::editor::AgentChatWidget::prompt_mode_ = cli::agent::PromptMode::kStandard private
Definition at line 341 of file agent_chat_widget.h.
Referenced by GetPromptMode(), and SetPromptMode().
show_z3ed_commands_
bool yaze::editor::AgentChatWidget::show_z3ed_commands_ = false private
Definition at line 342 of file agent_chat_widget.h.
show_rom_sync_
bool yaze::editor::AgentChatWidget::show_rom_sync_ = false private
Definition at line 343 of file agent_chat_widget.h.
show_snapshot_preview_
bool yaze::editor::AgentChatWidget::show_snapshot_preview_ = false private
Definition at line 344 of file agent_chat_widget.h.
snapshot_preview_data_
std::vector<uint8_t> yaze::editor::AgentChatWidget::snapshot_preview_data_ private
Definition at line 345 of file agent_chat_widget.h.
collaboration_status_color_
ImVec4 yaze::editor::AgentChatWidget::collaboration_status_color_ = ImVec4(0.6f, 0.6f, 0.6f, 1.0f) private
Definition at line 348 of file agent_chat_widget.h.
Referenced by Draw(), and RenderCollaborationPanel().
open_files_
std::vector<FileEditorTab> yaze::editor::AgentChatWidget::open_files_ private
Definition at line 358 of file agent_chat_widget.h.
Referenced by CreateNewFileInEditor(), LoadAgentSettingsFromProject(), OpenFileInEditor(), RenderFileEditorTabs(), RenderSystemPromptEditor(), and SaveAgentSettingsToProject().
active_file_tab_
int yaze::editor::AgentChatWidget::active_file_tab_ = -1 private
Definition at line 359 of file agent_chat_widget.h.
Referenced by CreateNewFileInEditor(), OpenFileInEditor(), RenderFileEditorTabs(), and RenderSystemPromptEditor().
The documentation for this class was generated from the following files:
src/app/editor/agent/agent_chat_widget.h
src/app/editor/agent/agent_chat_widget.cc