yaze: yaze::gui::DungeonObjectEmulatorPreview Class Reference
yaze::gui::DungeonObjectEmulatorPreview Class Reference
#include <dungeon_object_emulator_preview.h>
Public Member Functions
DungeonObjectEmulatorPreview ()
~DungeonObjectEmulatorPreview ()
void Initialize (gfx::IRenderer *renderer, Rom *rom)
void Render ()
Private Member Functions
void RenderControls ()
void TriggerEmulatedRender ()
Private Attributes
gfx::IRenderer * renderer_ = nullptr
Rom * rom_ = nullptr
std::unique_ptr< emu::Snes > snes_instance_
void * object_texture_ = nullptr
int object_id_ = 0
int room_id_ = 0
int object_x_ = 16
int object_y_ = 16
bool show_window_ = true
int last_cycle_count_ = 0
std::string last_error_
Detailed Description
Definition at line 16 of file dungeon_object_emulator_preview.h.
Constructor & Destructor Documentation
DungeonObjectEmulatorPreview()
yaze::gui::DungeonObjectEmulatorPreview::DungeonObjectEmulatorPreview ()
Definition at line 13 of file dungeon_object_emulator_preview.cc.
References snes_instance_.
~DungeonObjectEmulatorPreview()
yaze::gui::DungeonObjectEmulatorPreview::~DungeonObjectEmulatorPreview ()
Definition at line 17 of file dungeon_object_emulator_preview.cc.
Member Function Documentation
Initialize()
void yaze::gui::DungeonObjectEmulatorPreview::Initialize (gfx::IRenderer * renderer, Rom * rom)
Definition at line 23 of file dungeon_object_emulator_preview.cc.
References renderer_, rom_, snes_instance_, and yaze::Rom::vector().
Referenced by yaze::editor::DungeonEditorV2::Load(), yaze::editor::ObjectEditorCard::ObjectEditorCard(), and yaze::editor::DungeonEditorV2::set_rom().
Render()
void yaze::gui::DungeonObjectEmulatorPreview::Render ()
Definition at line 33 of file dungeon_object_emulator_preview.cc.
References yaze::Rom::is_loaded(), last_cycle_count_, last_error_, object_texture_, RenderControls(), rom_, and show_window_.
Referenced by yaze::editor::ObjectEditorCard::DrawEmulatorPreview().
RenderControls()
void yaze::gui::DungeonObjectEmulatorPreview::RenderControls () private
Definition at line 85 of file dungeon_object_emulator_preview.cc.
References yaze::gui::AutoInputInt(), yaze::gui::AutoSliderInt(), object_id_, object_x_, object_y_, room_id_, and TriggerEmulatedRender().
Referenced by Render().
TriggerEmulatedRender()
void yaze::gui::DungeonObjectEmulatorPreview::TriggerEmulatedRender () private
Definition at line 123 of file dungeon_object_emulator_preview.cc.
References yaze::zelda3::Room::blockset, yaze::zelda3::Room::CopyRoomGraphicsToBuffer(), yaze::Rom::data(), yaze::zelda3::RoomObject::EncodeObjectToBytes(), yaze::zelda3::Room::get_gfx_buffer(), yaze::Rom::is_loaded(), last_cycle_count_, last_error_, yaze::zelda3::LoadRoomFromRom(), yaze::zelda3::Room::LoadRoomGraphics(), yaze::gfx::IRenderer::LockTexture(), object_id_, object_texture_, object_x_, object_y_, yaze::zelda3::Room::palette, yaze::Rom::palette_group(), renderer_, rom_, room_id_, snes_instance_, and yaze::gfx::IRenderer::UnlockTexture().
Referenced by RenderControls().
Member Data Documentation
renderer_
gfx::IRenderer* yaze::gui::DungeonObjectEmulatorPreview::renderer_ = nullptr private
Definition at line 28 of file dungeon_object_emulator_preview.h.
Referenced by Initialize(), and TriggerEmulatedRender().
rom_
Rom* yaze::gui::DungeonObjectEmulatorPreview::rom_ = nullptr private
Definition at line 29 of file dungeon_object_emulator_preview.h.
Referenced by Initialize(), Render(), and TriggerEmulatedRender().
snes_instance_
std::unique_ptr<emu::Snes> yaze::gui::DungeonObjectEmulatorPreview::snes_instance_ private
Definition at line 30 of file dungeon_object_emulator_preview.h.
Referenced by DungeonObjectEmulatorPreview(), Initialize(), and TriggerEmulatedRender().
object_texture_
void* yaze::gui::DungeonObjectEmulatorPreview::object_texture_ = nullptr private
Definition at line 31 of file dungeon_object_emulator_preview.h.
Referenced by Render(), and TriggerEmulatedRender().
object_id_
int yaze::gui::DungeonObjectEmulatorPreview::object_id_ = 0 private
Definition at line 33 of file dungeon_object_emulator_preview.h.
Referenced by RenderControls(), and TriggerEmulatedRender().
room_id_
int yaze::gui::DungeonObjectEmulatorPreview::room_id_ = 0 private
Definition at line 34 of file dungeon_object_emulator_preview.h.
Referenced by RenderControls(), and TriggerEmulatedRender().
object_x_
int yaze::gui::DungeonObjectEmulatorPreview::object_x_ = 16 private
Definition at line 35 of file dungeon_object_emulator_preview.h.
Referenced by RenderControls(), and TriggerEmulatedRender().
object_y_
int yaze::gui::DungeonObjectEmulatorPreview::object_y_ = 16 private
Definition at line 36 of file dungeon_object_emulator_preview.h.
Referenced by RenderControls(), and TriggerEmulatedRender().
show_window_
bool yaze::gui::DungeonObjectEmulatorPreview::show_window_ = true private
Definition at line 37 of file dungeon_object_emulator_preview.h.
Referenced by Render().
last_cycle_count_
int yaze::gui::DungeonObjectEmulatorPreview::last_cycle_count_ = 0 private
Definition at line 40 of file dungeon_object_emulator_preview.h.
Referenced by Render(), and TriggerEmulatedRender().
last_error_
std::string yaze::gui::DungeonObjectEmulatorPreview::last_error_ private
Definition at line 41 of file dungeon_object_emulator_preview.h.
Referenced by Render(), and TriggerEmulatedRender().
The documentation for this class was generated from the following files:
src/app/gui/widgets/dungeon_object_emulator_preview.h
src/app/gui/widgets/dungeon_object_emulator_preview.cc