yaze: yaze::editor::anonymous_namespace{welcome_screen.cc} Namespace Reference
yaze::editor::anonymous_namespace{welcome_screen.cc} Namespace Reference
Functions
ImVec4 GetThemedColor (const char *color_name, const ImVec4 &fallback)
std::string GetRelativeTimeString (const std::filesystem::file_time_type &ftime)
void DrawTriforceBackground (ImDrawList *draw_list, ImVec2 pos, float size, float alpha, float glow)
Variables
const ImVec4 kTriforceGoldFallback = ImVec4(1.0f, 0.843f, 0.0f, 1.0f)
const ImVec4 kHyruleGreenFallback = ImVec4(0.133f, 0.545f, 0.133f, 1.0f)
const ImVec4 kMasterSwordBlueFallback = ImVec4(0.196f, 0.6f, 0.8f, 1.0f)
const ImVec4 kGanonPurpleFallback = ImVec4(0.502f, 0.0f, 0.502f, 1.0f)
const ImVec4 kHeartRedFallback = ImVec4(0.863f, 0.078f, 0.235f, 1.0f)
const ImVec4 kSpiritOrangeFallback = ImVec4(1.0f, 0.647f, 0.0f, 1.0f)
const ImVec4 kShadowPurpleFallback = ImVec4(0.416f, 0.353f, 0.804f, 1.0f)
ImVec4 kTriforceGold = kTriforceGoldFallback
ImVec4 kHyruleGreen = kHyruleGreenFallback
ImVec4 kMasterSwordBlue = kMasterSwordBlueFallback
ImVec4 kGanonPurple = kGanonPurpleFallback
ImVec4 kHeartRed = kHeartRedFallback
ImVec4 kSpiritOrange = kSpiritOrangeFallback
ImVec4 kShadowPurple = kShadowPurpleFallback
Function Documentation
GetThemedColor()
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::GetThemedColor (const char * color_name, const ImVec4 & fallback)
Todo:
Fix this
Definition at line 29 of file welcome_screen.cc.
References yaze::gui::ThemeManager::Get(), and GetThemedColor().
Referenced by GetThemedColor().
GetRelativeTimeString()
std::string yaze::editor::anonymous_namespace{welcome_screen.cc}::GetRelativeTimeString (const std::filesystem::file_time_type & ftime)
Definition at line 70 of file welcome_screen.cc.
References GetRelativeTimeString().
Referenced by GetRelativeTimeString().
DrawTriforceBackground()
void yaze::editor::anonymous_namespace{welcome_screen.cc}::DrawTriforceBackground (ImDrawList * draw_list, ImVec2 pos, float size, float alpha, float glow)
Definition at line 95 of file welcome_screen.cc.
References DrawTriforceBackground().
Referenced by DrawTriforceBackground().
Variable Documentation
kTriforceGoldFallback
const ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kTriforceGoldFallback = ImVec4(1.0f, 0.843f, 0.0f, 1.0f)
Definition at line 53 of file welcome_screen.cc.
kHyruleGreenFallback
const ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kHyruleGreenFallback = ImVec4(0.133f, 0.545f, 0.133f, 1.0f)
Definition at line 54 of file welcome_screen.cc.
kMasterSwordBlueFallback
const ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kMasterSwordBlueFallback = ImVec4(0.196f, 0.6f, 0.8f, 1.0f)
Definition at line 55 of file welcome_screen.cc.
kGanonPurpleFallback
const ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kGanonPurpleFallback = ImVec4(0.502f, 0.0f, 0.502f, 1.0f)
Definition at line 56 of file welcome_screen.cc.
kHeartRedFallback
const ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kHeartRedFallback = ImVec4(0.863f, 0.078f, 0.235f, 1.0f)
Definition at line 57 of file welcome_screen.cc.
kSpiritOrangeFallback
const ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kSpiritOrangeFallback = ImVec4(1.0f, 0.647f, 0.0f, 1.0f)
Definition at line 58 of file welcome_screen.cc.
kShadowPurpleFallback
const ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kShadowPurpleFallback = ImVec4(0.416f, 0.353f, 0.804f, 1.0f)
Definition at line 59 of file welcome_screen.cc.
kTriforceGold
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kTriforceGold = kTriforceGoldFallback
Definition at line 62 of file welcome_screen.cc.
kHyruleGreen
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kHyruleGreen = kHyruleGreenFallback
Definition at line 63 of file welcome_screen.cc.
kMasterSwordBlue
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kMasterSwordBlue = kMasterSwordBlueFallback
Definition at line 64 of file welcome_screen.cc.
kGanonPurple
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kGanonPurple = kGanonPurpleFallback
Definition at line 65 of file welcome_screen.cc.
kHeartRed
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kHeartRed = kHeartRedFallback
Definition at line 66 of file welcome_screen.cc.
kSpiritOrange
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kSpiritOrange = kSpiritOrangeFallback
Definition at line 67 of file welcome_screen.cc.
kShadowPurple
ImVec4 yaze::editor::anonymous_namespace{welcome_screen.cc}::kShadowPurple = kShadowPurpleFallback
Definition at line 68 of file welcome_screen.cc.