yaze: yaze::editor::anonymous_namespace{shortcut_configurator.cc} Namespace Reference
yaze::editor::anonymous_namespace{shortcut_configurator.cc} Namespace Reference
Functions
void RegisterIfValid (ShortcutManager *shortcut_manager, const std::string &name, const std::vector< ImGuiKey > &keys, std::function< void()> callback)
void RegisterIfValid (ShortcutManager *shortcut_manager, const std::string &name, ImGuiKey key, std::function< void()> callback)
Function Documentation
RegisterIfValid() [1/2]
void yaze::editor::anonymous_namespace{shortcut_configurator.cc}::RegisterIfValid (ShortcutManager * shortcut_manager, const std::string & name, const std::vector< ImGuiKey > & keys, std::function< void()> callback)
Definition at line 21 of file shortcut_configurator.cc.
References RegisterIfValid(), and yaze::editor::ShortcutManager::RegisterShortcut().
Referenced by RegisterIfValid(), and RegisterIfValid().
RegisterIfValid() [2/2]
void yaze::editor::anonymous_namespace{shortcut_configurator.cc}::RegisterIfValid (ShortcutManager * shortcut_manager, const std::string & name, ImGuiKey key, std::function< void()> callback)
Definition at line 31 of file shortcut_configurator.cc.
References RegisterIfValid(), and yaze::editor::ShortcutManager::RegisterShortcut().