yaze: yaze::gui::CollaborationPanel Class Reference
yaze::gui::CollaborationPanel Class Reference
ImGui panel for collaboration features.
#include <collaboration_panel.h>
Public Member Functions
CollaborationPanel ()
~CollaborationPanel ()
void Initialize (Rom *rom, net::RomVersionManager *version_mgr, net::ProposalApprovalManager *approval_mgr)
void Render (bool *p_open=nullptr)
void AddRomSync (const RomSyncEntry &entry)
void AddSnapshot (const SnapshotEntry &entry)
void AddProposal (const ProposalEntry &entry)
void UpdateProposalStatus (const std::string &proposal_id, const std::string &status)
void Clear ()
ProposalEntry * GetProposal (const std::string &proposal_id)
Private Member Functions
void RenderRomSyncTab ()
void RenderSnapshotsTab ()
void RenderProposalsTab ()
void RenderVersionHistoryTab ()
void RenderApprovalTab ()
void RenderRomSyncEntry (const RomSyncEntry &entry, int index)
void RenderSnapshotEntry (const SnapshotEntry &entry, int index)
void RenderProposalEntry (const ProposalEntry &entry, int index)
void RenderVersionSnapshot (const net::RomSnapshot &snapshot, int index)
void RenderApprovalProposal (const net::ProposalApprovalManager::ApprovalStatus &status, int index)
std::string FormatTimestamp (int64_t timestamp)
std::string FormatFileSize (size_t bytes)
const char * GetProposalStatusIcon (const std::string &status)
ImVec4 GetProposalStatusColor (const std::string &status)
Private Attributes
Rom * rom_
net::RomVersionManager * version_mgr_
net::ProposalApprovalManager * approval_mgr_
int selected_tab_
std::vector< RomSyncEntry > rom_syncs_
std::vector< SnapshotEntry > snapshots_
std::vector< ProposalEntry > proposals_
int selected_rom_sync_
int selected_snapshot_
int selected_proposal_
bool show_sync_details_
bool show_snapshot_preview_
bool auto_scroll_
char search_filter_ [256]
bool filter_pending_only_
struct {
ImVec4 sync_applied
ImVec4 sync_pending
ImVec4 sync_error
ImVec4 proposal_pending
ImVec4 proposal_approved
ImVec4 proposal_rejected
ImVec4 proposal_applied
} colors_
Detailed Description
ImGui panel for collaboration features.
Displays:
ROM sync history and status
Shared snapshots gallery
Proposal management and voting
Definition at line 80 of file collaboration_panel.h.
Constructor & Destructor Documentation
CollaborationPanel()
yaze::gui::CollaborationPanel::CollaborationPanel ()
Definition at line 14 of file collaboration_panel.cc.
References colors_, and search_filter_.
~CollaborationPanel()
yaze::gui::CollaborationPanel::~CollaborationPanel ()
Definition at line 40 of file collaboration_panel.cc.
References snapshots_.
Member Function Documentation
Initialize()
void yaze::gui::CollaborationPanel::Initialize (Rom * rom, net::RomVersionManager * version_mgr, net::ProposalApprovalManager * approval_mgr)
Initialize with ROM and version manager
Definition at line 51 of file collaboration_panel.cc.
References approval_mgr_, rom_, and version_mgr_.
Render()
void yaze::gui::CollaborationPanel::Render (bool * p_open = nullptr)
Render the collaboration panel
Definition at line 60 of file collaboration_panel.cc.
References RenderApprovalTab(), RenderProposalsTab(), RenderRomSyncTab(), RenderSnapshotsTab(), RenderVersionHistoryTab(), and selected_tab_.
AddRomSync()
void yaze::gui::CollaborationPanel::AddRomSync (const RomSyncEntry & entry)
Add a ROM sync event
Definition at line 391 of file collaboration_panel.cc.
References rom_syncs_.
AddSnapshot()
void yaze::gui::CollaborationPanel::AddSnapshot (const SnapshotEntry & entry)
Add a snapshot
Definition at line 395 of file collaboration_panel.cc.
References snapshots_.
AddProposal()
void yaze::gui::CollaborationPanel::AddProposal (const ProposalEntry & entry)
Add a proposal
Definition at line 399 of file collaboration_panel.cc.
References proposals_.
UpdateProposalStatus()
void yaze::gui::CollaborationPanel::UpdateProposalStatus (const std::string & proposal_id, const std::string & status)
Update proposal status
Definition at line 403 of file collaboration_panel.cc.
References proposals_.
Clear()
void yaze::gui::CollaborationPanel::Clear ()
Clear all collaboration data
Definition at line 412 of file collaboration_panel.cc.
References proposals_, rom_syncs_, and snapshots_.
GetProposal()
ProposalEntry * yaze::gui::CollaborationPanel::GetProposal (const std::string & proposal_id)
Get proposal by ID
Definition at line 418 of file collaboration_panel.cc.
References proposals_.
RenderRomSyncTab()
void yaze::gui::CollaborationPanel::RenderRomSyncTab () private
Definition at line 104 of file collaboration_panel.cc.
References auto_scroll_, colors_, RenderRomSyncEntry(), rom_syncs_, and show_sync_details_.
Referenced by Render().
RenderSnapshotsTab()
void yaze::gui::CollaborationPanel::RenderSnapshotsTab () private
Definition at line 153 of file collaboration_panel.cc.
References RenderSnapshotEntry(), search_filter_, show_snapshot_preview_, and snapshots_.
Referenced by Render().
RenderProposalsTab()
void yaze::gui::CollaborationPanel::RenderProposalsTab () private
Definition at line 201 of file collaboration_panel.cc.
References colors_, filter_pending_only_, proposals_, RenderProposalEntry(), and search_filter_.
Referenced by Render().
RenderVersionHistoryTab()
void yaze::gui::CollaborationPanel::RenderVersionHistoryTab () private
Todo:
Show result in UI
Todo:
Find snapshot with this hash and mark as safe
Todo:
Show result
Definition at line 467 of file collaboration_panel.cc.
References colors_, yaze::net::RomVersionManager::CreateSnapshot(), yaze::net::RomVersionManager::DetectCorruption(), FormatFileSize(), yaze::net::RomVersionManager::GetCurrentHash(), yaze::net::RomVersionManager::GetSnapshots(), yaze::net::RomVersionManager::GetStats(), RenderVersionSnapshot(), and version_mgr_.
Referenced by Render().
RenderApprovalTab()
void yaze::gui::CollaborationPanel::RenderApprovalTab () private
Definition at line 520 of file collaboration_panel.cc.
References approval_mgr_, yaze::net::ProposalApprovalManager::GetPendingProposals(), and RenderApprovalProposal().
Referenced by Render().
RenderRomSyncEntry()
void yaze::gui::CollaborationPanel::RenderRomSyncEntry (const RomSyncEntry & entry, int index) private
Definition at line 265 of file collaboration_panel.cc.
References yaze::gui::RomSyncEntry::applied, colors_, yaze::gui::RomSyncEntry::diff_size, yaze::gui::RomSyncEntry::error_message, FormatFileSize(), FormatTimestamp(), yaze::gui::RomSyncEntry::rom_hash, yaze::gui::RomSyncEntry::sender, show_sync_details_, and yaze::gui::RomSyncEntry::timestamp.
Referenced by RenderRomSyncTab().
RenderSnapshotEntry()
void yaze::gui::CollaborationPanel::RenderSnapshotEntry (const SnapshotEntry & entry, int index) private
Todo:
Open snapshot viewer
Todo:
Export snapshot to file
Definition at line 306 of file collaboration_panel.cc.
References yaze::gui::SnapshotEntry::data_size, FormatFileSize(), FormatTimestamp(), yaze::gui::SnapshotEntry::is_image, selected_snapshot_, yaze::gui::SnapshotEntry::sender, show_snapshot_preview_, yaze::gui::SnapshotEntry::snapshot_type, yaze::gui::SnapshotEntry::texture_id, and yaze::gui::SnapshotEntry::timestamp.
Referenced by RenderSnapshotsTab().
RenderProposalEntry()
void yaze::gui::CollaborationPanel::RenderProposalEntry (const ProposalEntry & entry, int index) private
Todo:
Send approval to server
Todo:
Send rejection to server
Todo:
Execute proposal
Definition at line 342 of file collaboration_panel.cc.
References yaze::gui::ProposalEntry::description, FormatTimestamp(), GetProposalStatusColor(), GetProposalStatusIcon(), yaze::gui::ProposalEntry::proposal_data, yaze::gui::ProposalEntry::sender, yaze::gui::ProposalEntry::status, and yaze::gui::ProposalEntry::timestamp.
Referenced by RenderProposalsTab().
RenderVersionSnapshot()
void yaze::gui::CollaborationPanel::RenderVersionSnapshot (const net::RomSnapshot & snapshot, int index) private
Todo:
Show result
Definition at line 548 of file collaboration_panel.cc.
References colors_, yaze::net::RomSnapshot::compressed_size, yaze::net::RomSnapshot::creator, yaze::net::RomVersionManager::DeleteSnapshot(), yaze::net::RomSnapshot::description, FormatFileSize(), FormatTimestamp(), yaze::net::RomSnapshot::is_checkpoint, yaze::net::RomSnapshot::is_safe_point, yaze::net::RomVersionManager::MarkAsSafePoint(), yaze::net::RomVersionManager::RestoreSnapshot(), yaze::net::RomSnapshot::rom_hash, yaze::net::RomSnapshot::snapshot_id, yaze::net::RomSnapshot::timestamp, and version_mgr_.
Referenced by RenderVersionHistoryTab().
RenderApprovalProposal()
void yaze::gui::CollaborationPanel::RenderApprovalProposal (const net::ProposalApprovalManager::ApprovalStatus & status, int index) private
Todo:
Send approval vote
Todo:
Send rejection vote
Definition at line 609 of file collaboration_panel.cc.
References colors_, yaze::net::ProposalApprovalManager::ApprovalStatus::created_at, FormatTimestamp(), yaze::net::ProposalApprovalManager::ApprovalStatus::proposal_id, yaze::net::RomVersionManager::RestoreSnapshot(), yaze::net::ProposalApprovalManager::ApprovalStatus::snapshot_before, version_mgr_, and yaze::net::ProposalApprovalManager::ApprovalStatus::votes.
Referenced by RenderApprovalTab().
FormatTimestamp()
std::string yaze::gui::CollaborationPanel::FormatTimestamp (int64_t timestamp) private
Definition at line 427 of file collaboration_panel.cc.
Referenced by RenderApprovalProposal(), RenderProposalEntry(), RenderRomSyncEntry(), RenderSnapshotEntry(), and RenderVersionSnapshot().
FormatFileSize()
std::string yaze::gui::CollaborationPanel::FormatFileSize (size_t bytes) private
Definition at line 436 of file collaboration_panel.cc.
Referenced by RenderRomSyncEntry(), RenderSnapshotEntry(), RenderVersionHistoryTab(), and RenderVersionSnapshot().
GetProposalStatusIcon()
const char * yaze::gui::CollaborationPanel::GetProposalStatusIcon (const std::string & status) private
Definition at line 451 of file collaboration_panel.cc.
Referenced by RenderProposalEntry().
GetProposalStatusColor()
ImVec4 yaze::gui::CollaborationPanel::GetProposalStatusColor (const std::string & status) private
Definition at line 459 of file collaboration_panel.cc.
References colors_.
Referenced by RenderProposalEntry().
Member Data Documentation
rom_
Rom* yaze::gui::CollaborationPanel::rom_ private
Definition at line 140 of file collaboration_panel.h.
Referenced by Initialize().
version_mgr_
net::RomVersionManager* yaze::gui::CollaborationPanel::version_mgr_ private
Definition at line 141 of file collaboration_panel.h.
Referenced by Initialize(), RenderApprovalProposal(), RenderVersionHistoryTab(), and RenderVersionSnapshot().
approval_mgr_
net::ProposalApprovalManager* yaze::gui::CollaborationPanel::approval_mgr_ private
Definition at line 142 of file collaboration_panel.h.
Referenced by Initialize(), and RenderApprovalTab().
selected_tab_
int yaze::gui::CollaborationPanel::selected_tab_ private
Definition at line 145 of file collaboration_panel.h.
Referenced by Render().
rom_syncs_
std::vector<RomSyncEntry> yaze::gui::CollaborationPanel::rom_syncs_ private
Definition at line 148 of file collaboration_panel.h.
Referenced by AddRomSync(), Clear(), and RenderRomSyncTab().
snapshots_
std::vector<SnapshotEntry> yaze::gui::CollaborationPanel::snapshots_ private
Definition at line 149 of file collaboration_panel.h.
Referenced by AddSnapshot(), Clear(), RenderSnapshotsTab(), and ~CollaborationPanel().
proposals_
std::vector<ProposalEntry> yaze::gui::CollaborationPanel::proposals_ private
Definition at line 150 of file collaboration_panel.h.
Referenced by AddProposal(), Clear(), GetProposal(), RenderProposalsTab(), and UpdateProposalStatus().
selected_rom_sync_
int yaze::gui::CollaborationPanel::selected_rom_sync_ private
Definition at line 153 of file collaboration_panel.h.
selected_snapshot_
int yaze::gui::CollaborationPanel::selected_snapshot_ private
Definition at line 154 of file collaboration_panel.h.
Referenced by RenderSnapshotEntry().
selected_proposal_
int yaze::gui::CollaborationPanel::selected_proposal_ private
Definition at line 155 of file collaboration_panel.h.
show_sync_details_
bool yaze::gui::CollaborationPanel::show_sync_details_ private
Definition at line 156 of file collaboration_panel.h.
Referenced by RenderRomSyncEntry(), and RenderRomSyncTab().
show_snapshot_preview_
bool yaze::gui::CollaborationPanel::show_snapshot_preview_ private
Definition at line 157 of file collaboration_panel.h.
Referenced by RenderSnapshotEntry(), and RenderSnapshotsTab().
auto_scroll_
bool yaze::gui::CollaborationPanel::auto_scroll_ private
Definition at line 158 of file collaboration_panel.h.
Referenced by RenderRomSyncTab().
search_filter_
char yaze::gui::CollaborationPanel::search_filter_[256] private
Definition at line 161 of file collaboration_panel.h.
Referenced by CollaborationPanel(), RenderProposalsTab(), and RenderSnapshotsTab().
filter_pending_only_
bool yaze::gui::CollaborationPanel::filter_pending_only_ private
Definition at line 162 of file collaboration_panel.h.
Referenced by RenderProposalsTab().
sync_applied
ImVec4 yaze::gui::CollaborationPanel::sync_applied
Definition at line 166 of file collaboration_panel.h.
sync_pending
ImVec4 yaze::gui::CollaborationPanel::sync_pending
Definition at line 167 of file collaboration_panel.h.
sync_error
ImVec4 yaze::gui::CollaborationPanel::sync_error
Definition at line 168 of file collaboration_panel.h.
proposal_pending
ImVec4 yaze::gui::CollaborationPanel::proposal_pending
Definition at line 169 of file collaboration_panel.h.
proposal_approved
ImVec4 yaze::gui::CollaborationPanel::proposal_approved
Definition at line 170 of file collaboration_panel.h.
proposal_rejected
ImVec4 yaze::gui::CollaborationPanel::proposal_rejected
Definition at line 171 of file collaboration_panel.h.
proposal_applied
ImVec4 yaze::gui::CollaborationPanel::proposal_applied
Definition at line 172 of file collaboration_panel.h.
[struct]
struct { ... } yaze::gui::CollaborationPanel::colors_
Referenced by CollaborationPanel(), GetProposalStatusColor(), RenderApprovalProposal(), RenderProposalsTab(), RenderRomSyncEntry(), RenderRomSyncTab(), RenderVersionHistoryTab(), and RenderVersionSnapshot().
The documentation for this class was generated from the following files:
src/app/gui/widgets/collaboration_panel.h
src/app/gui/widgets/collaboration_panel.cc