yaze: yaze::app::net::anonymous_namespace{rom_version_manager.cc} Namespace Reference
yaze::app::net::anonymous_namespace{rom_version_manager.cc} Namespace Reference
Functions
std::string ComputeHash (const std::vector< uint8_t > &data)
std::string GenerateId ()
int64_t GetCurrentTimestamp ()
Function Documentation
ComputeHash()
std::string yaze::app::net::anonymous_namespace{rom_version_manager.cc}::ComputeHash (const std::vector< uint8_t > & data)
Definition at line 24 of file rom_version_manager.cc.
References ComputeHash().
Referenced by ComputeHash().
GenerateId()
std::string yaze::app::net::anonymous_namespace{rom_version_manager.cc}::GenerateId ()
Definition at line 33 of file rom_version_manager.cc.
References GenerateId().
Referenced by GenerateId().
GetCurrentTimestamp()
int64_t yaze::app::net::anonymous_namespace{rom_version_manager.cc}::GetCurrentTimestamp ()
Definition at line 40 of file rom_version_manager.cc.
References GetCurrentTimestamp().
Referenced by GetCurrentTimestamp().