#include "zelda3/dungeon/room_census_vanilla_fingerprints.h"

#include "absl/strings/str_format.h"

namespace yaze::zelda3 {

namespace {
// Defines kVanillaFingerprintHashes[], kVanillaFingerprintOffsets[0x129] and
// kHasVanillaFingerprints.
#include "zelda3/dungeon/room_census_vanilla_fingerprints_data.inc"
}  // namespace

bool HasBuiltinVanillaRoomFingerprints() {
  return kHasVanillaFingerprints;
}

std::vector<uint16_t> BuiltinVanillaRoomFingerprint(int room_id) {
  if (!kHasVanillaFingerprints || room_id < 0 || room_id >= 0x128) {
    return {};
  }
  const int begin = kVanillaFingerprintOffsets[room_id];
  const int end = kVanillaFingerprintOffsets[room_id + 1];
  return std::vector<uint16_t>(kVanillaFingerprintHashes + begin,
                               kVanillaFingerprintHashes + end);
}

std::string FormatVanillaFingerprintTable(
    const std::vector<std::vector<uint16_t>>& fingerprints,
    const std::string& source_note) {
  std::string out;
  out +=
      "// Generated by z3ed dungeon-room-census --emit-vanilla-fingerprints.\n";
  out += "// Source: " + source_note + "\n";
  out +=
      "// One-way 16-bit object hashes; see "
      "room_census_vanilla_fingerprints.h.\n";
  out += "// clang-format off\n";
  out += "constexpr bool kHasVanillaFingerprints = true;\n";
  out += "constexpr uint16_t kVanillaFingerprintHashes[] = {\n";
  int total = 0;
  std::vector<int> offsets;
  for (const auto& room : fingerprints) {
    offsets.push_back(total);
    for (size_t i = 0; i < room.size(); ++i) {
      if (total % 12 == 0) {
        out += "   ";
      }
      out += absl::StrFormat(" 0x%04X,", room[i]);
      ++total;
      if (total % 12 == 0) {
        out += "\n";
      }
    }
  }
  offsets.push_back(total);
  if (total % 12 != 0) {
    out += "\n";
  }
  if (total == 0) {
    out += "    0,\n";
  }
  out += "};\n";
  out += absl::StrFormat("constexpr int kVanillaFingerprintOffsets[%d] = {\n",
                         static_cast<int>(offsets.size()));
  for (size_t i = 0; i < offsets.size(); ++i) {
    if (i % 12 == 0) {
      out += "   ";
    }
    out += absl::StrFormat(" %d,", offsets[i]);
    if (i % 12 == 11) {
      out += "\n";
    }
  }
  if (offsets.size() % 12 != 0) {
    out += "\n";
  }
  out += "};\n// clang-format on\n";
  return out;
}

}  // namespace yaze::zelda3
