yaze: yaze::gui::FlagsMenu Struct Reference
yaze::gui::FlagsMenu Struct Reference
#include <feature_flags_menu.h>
Public Member Functions
void DrawOverworldFlags ()
void DrawDungeonFlags ()
void DrawResourceFlags ()
void DrawSystemFlags ()
Detailed Description
Definition at line 16 of file feature_flags_menu.h.
Member Function Documentation
DrawOverworldFlags()
void yaze::gui::FlagsMenu::DrawOverworldFlags () inline
Definition at line 17 of file feature_flags_menu.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
DrawDungeonFlags()
void yaze::gui::FlagsMenu::DrawDungeonFlags () inline
Definition at line 48 of file feature_flags_menu.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
DrawResourceFlags()
void yaze::gui::FlagsMenu::DrawResourceFlags () inline
Definition at line 52 of file feature_flags_menu.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
DrawSystemFlags()
void yaze::gui::FlagsMenu::DrawSystemFlags () inline
Definition at line 58 of file feature_flags_menu.h.
References yaze::core::FeatureFlags::get().
Referenced by yaze::editor::SettingsEditor::DrawGeneralSettings().
The documentation for this struct was generated from the following file:
src/app/gui/feature_flags_menu.h