yaze: yaze::util::FileDialogWrapper Class Reference
yaze::util::FileDialogWrapper Class Reference
#include <file_util.h>
Static Public Member Functions
static std::string ShowOpenFileDialog ()
ShowOpenFileDialog opens a file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
static std::string ShowOpenFolderDialog ()
ShowOpenFolderDialog opens a file dialog and returns the selected folder path. Uses global feature flag to choose implementation.
static std::string ShowSaveFileDialog (const std::string &default_name="", const std::string &default_extension="")
ShowSaveFileDialog opens a save file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
static std::string ShowOpenFileDialogNFD ()
static std::string ShowOpenFileDialogBespoke ()
static std::string ShowSaveFileDialogNFD (const std::string &default_name="", const std::string &default_extension="")
static std::string ShowSaveFileDialogBespoke (const std::string &default_name="", const std::string &default_extension="")
static std::string ShowOpenFolderDialogNFD ()
static std::string ShowOpenFolderDialogBespoke ()
static std::vector< std::string > GetSubdirectoriesInFolder (const std::string &folder_path)
static std::vector< std::string > GetFilesInFolder (const std::string &folder_path)
Detailed Description
Definition at line 10 of file file_util.h.
Member Function Documentation
ShowOpenFileDialog()
std::string yaze::util::FileDialogWrapper::ShowOpenFileDialog () static
ShowOpenFileDialog opens a file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
Definition at line 12 of file file_dialog_nfd.cc.
Referenced by yaze::editor::ProjectFileEditor::Draw(), yaze::editor::GraphicsEditor::DrawCgxImport(), yaze::editor::SpriteEditor::DrawCustomSpritesMetadata(), yaze::editor::MessageEditor::DrawExpandedMessageSettings(), yaze::editor::GraphicsEditor::DrawFileImport(), yaze::editor::AssemblyEditor::DrawFileMenu(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::GraphicsEditor::DrawObjImport(), yaze::editor::GraphicsEditor::DrawPaletteControls(), yaze::editor::GraphicsEditor::DrawScrImport(), yaze::test::TestManager::DrawTestDashboard(), yaze::editor::GraphicsEditor::DrawTilemapImport(), yaze::editor::ScreenEditor::LoadBinaryGfx(), yaze::zelda3::LoadDungeonMapGfxFromBinary(), yaze::editor::EditorManager::LoadRom(), yaze::editor::EditorManager::OpenProject(), yaze::editor::AgentChatWidget::RenderFileEditorTabs(), yaze::emu::ui::RenderNavBar(), yaze::editor::AgentChatWidget::RenderSystemPromptEditor(), ShowOpenFileDialogBespoke(), ShowOpenFileDialogNFD(), yaze::gui::ThemeManager::ShowSimpleThemeEditor(), yaze::gui::ThemeManager::ShowThemeSelector(), and yaze::editor::MemoryEditorWithDiffChecker::Update().
ShowOpenFolderDialog()
std::string yaze::util::FileDialogWrapper::ShowOpenFolderDialog () static
ShowOpenFolderDialog opens a file dialog and returns the selected folder path. Uses global feature flag to choose implementation.
Definition at line 26 of file file_dialog_nfd.cc.
Referenced by yaze::editor::EditorManager::CreateNewProject(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::AssemblyEditor::DrawToolset(), ShowOpenFolderDialogBespoke(), ShowOpenFolderDialogNFD(), and yaze::editor::AssemblyEditor::UpdateCodeView().
ShowSaveFileDialog()
std::string yaze::util::FileDialogWrapper::ShowSaveFileDialog (const std::string & default_name = "", const std::string & default_extension = "") static
ShowSaveFileDialog opens a save file dialog and returns the selected filepath. Uses global feature flag to choose implementation.
Definition at line 39 of file file_dialog_nfd.cc.
Referenced by yaze::editor::ProjectFileEditor::Draw(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::AgentChatWidget::RenderFileEditorTabs(), yaze::editor::AgentChatWidget::RenderSystemPromptEditor(), yaze::editor::EditorManager::SaveProjectAs(), ShowSaveFileDialogBespoke(), ShowSaveFileDialogNFD(), and yaze::gui::ThemeManager::ShowSimpleThemeEditor().
ShowOpenFileDialogNFD()
std::string yaze::util::FileDialogWrapper::ShowOpenFileDialogNFD () static
Definition at line 95 of file file_dialog_nfd.cc.
References ShowOpenFileDialog().
Referenced by yaze::test::TestManager::DrawTestDashboard().
ShowOpenFileDialogBespoke()
std::string yaze::util::FileDialogWrapper::ShowOpenFileDialogBespoke () static
Definition at line 99 of file file_dialog_nfd.cc.
References ShowOpenFileDialog().
Referenced by yaze::test::TestManager::DrawTestDashboard().
ShowSaveFileDialogNFD()
std::string yaze::util::FileDialogWrapper::ShowSaveFileDialogNFD (const std::string & default_name = "", const std::string & default_extension = "") static
Definition at line 103 of file file_dialog_nfd.cc.
References ShowSaveFileDialog().
ShowSaveFileDialogBespoke()
std::string yaze::util::FileDialogWrapper::ShowSaveFileDialogBespoke (const std::string & default_name = "", const std::string & default_extension = "") static
Definition at line 108 of file file_dialog_nfd.cc.
References ShowSaveFileDialog().
ShowOpenFolderDialogNFD()
std::string yaze::util::FileDialogWrapper::ShowOpenFolderDialogNFD () static
Definition at line 113 of file file_dialog_nfd.cc.
References ShowOpenFolderDialog().
ShowOpenFolderDialogBespoke()
std::string yaze::util::FileDialogWrapper::ShowOpenFolderDialogBespoke () static
Definition at line 117 of file file_dialog_nfd.cc.
References ShowOpenFolderDialog().
GetSubdirectoriesInFolder()
std::vector< std::string > yaze::util::FileDialogWrapper::GetSubdirectoriesInFolder (const std::string & folder_path) static
Definition at line 60 of file file_dialog_nfd.cc.
Referenced by yaze::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
GetFilesInFolder()
std::vector< std::string > yaze::util::FileDialogWrapper::GetFilesInFolder (const std::string & folder_path) static
Definition at line 77 of file file_dialog_nfd.cc.
Referenced by yaze::gui::ThemeManager::DiscoverAvailableThemeFiles(), and yaze::editor::anonymous_namespace{assembly_editor.cc}::LoadFolder().
The documentation for this class was generated from the following files:
src/util/file_util.h
src/app/platform/file_dialog_nfd.cc