yaze: yaze::cli::gui::GuiActionGenerator Class Reference
yaze::cli::gui::GuiActionGenerator Class Reference
Converts high-level AI actions into executable GUI test scripts.
#include <gui_action_generator.h>
Public Member Functions
GuiActionGenerator ()=default
absl::StatusOr< std::string > GenerateTestScript (const std::vector< ai::AIAction > &actions)
std::string ActionToTestStep (const ai::AIAction &action, int step_number)
Private Member Functions
std::string GenerateOpenEditorStep (const ai::AIAction &action)
std::string GenerateSelectTileStep (const ai::AIAction &action)
std::string GeneratePlaceTileStep (const ai::AIAction &action)
std::string GenerateSaveTileStep (const ai::AIAction &action)
std::string GenerateClickButtonStep (const ai::AIAction &action)
std::string GenerateWaitStep (const ai::AIAction &action)
std::string GenerateScreenshotStep (const ai::AIAction &action)
Detailed Description
Converts high-level AI actions into executable GUI test scripts.
Takes parsed AI actions and generates gRPC test harness commands or JSON test scripts that can be executed to control the GUI.
Definition at line 25 of file gui_action_generator.h.
Constructor & Destructor Documentation
GuiActionGenerator()
yaze::cli::gui::GuiActionGenerator::GuiActionGenerator () default
Member Function Documentation
GenerateTestScript()
absl::StatusOr< std::string > yaze::cli::gui::GuiActionGenerator::GenerateTestScript (const std::vector< ai::AIAction > & actions)
Generate a test script from a sequence of AI actions
Parameters
actions Vector of actions to convert
Returns
JSON-formatted test script, or error status
Definition at line 10 of file gui_action_generator.cc.
Referenced by yaze::test::TEST_F().
ActionToTestStep()
std::string yaze::cli::gui::GuiActionGenerator::ActionToTestStep (const ai::AIAction & action, int step_number)
Convert a single action to a test step
Definition at line 144 of file gui_action_generator.cc.
References GenerateClickButtonStep(), GenerateOpenEditorStep(), GeneratePlaceTileStep(), GenerateSaveTileStep(), GenerateScreenshotStep(), GenerateSelectTileStep(), GenerateWaitStep(), yaze::cli::ai::kClickButton, yaze::cli::ai::kOpenEditor, yaze::cli::ai::kPlaceTile, yaze::cli::ai::kSaveTile, yaze::cli::ai::kScreenshot, yaze::cli::ai::kSelectTile, yaze::cli::ai::kWait, and yaze::cli::ai::AIAction::type.
GenerateOpenEditorStep()
std::string yaze::cli::gui::GuiActionGenerator::GenerateOpenEditorStep (const ai::AIAction & action) private
Definition at line 166 of file gui_action_generator.cc.
References yaze::cli::ai::AIAction::parameters.
Referenced by ActionToTestStep().
GenerateSelectTileStep()
std::string yaze::cli::gui::GuiActionGenerator::GenerateSelectTileStep (const ai::AIAction & action) private
Definition at line 174 of file gui_action_generator.cc.
References yaze::cli::ai::AIAction::parameters.
Referenced by ActionToTestStep().
GeneratePlaceTileStep()
std::string yaze::cli::gui::GuiActionGenerator::GeneratePlaceTileStep (const ai::AIAction & action) private
Definition at line 186 of file gui_action_generator.cc.
References yaze::cli::ai::AIAction::parameters.
Referenced by ActionToTestStep().
GenerateSaveTileStep()
std::string yaze::cli::gui::GuiActionGenerator::GenerateSaveTileStep (const ai::AIAction & action) private
Definition at line 199 of file gui_action_generator.cc.
Referenced by ActionToTestStep().
GenerateClickButtonStep()
std::string yaze::cli::gui::GuiActionGenerator::GenerateClickButtonStep (const ai::AIAction & action) private
Definition at line 203 of file gui_action_generator.cc.
References yaze::cli::ai::AIAction::parameters.
Referenced by ActionToTestStep().
GenerateWaitStep()
std::string yaze::cli::gui::GuiActionGenerator::GenerateWaitStep (const ai::AIAction & action) private
Definition at line 211 of file gui_action_generator.cc.
References yaze::cli::ai::AIAction::parameters.
Referenced by ActionToTestStep().
GenerateScreenshotStep()
std::string yaze::cli::gui::GuiActionGenerator::GenerateScreenshotStep (const ai::AIAction & action) private
Definition at line 217 of file gui_action_generator.cc.
References yaze::cli::ai::AIAction::parameters.
Referenced by ActionToTestStep().
The documentation for this class was generated from the following files:
src/cli/service/gui/gui_action_generator.h
src/cli/service/gui/gui_action_generator.cc