yaze: yaze::editor::MenuOrchestrator Class Reference
yaze::editor::MenuOrchestrator Class Reference
Handles all menu building and UI coordination logic.
#include <menu_orchestrator.h>
Public Member Functions
MenuOrchestrator (EditorManager *editor_manager, MenuBuilder &menu_builder, RomFileManager &rom_manager, ProjectManager &project_manager, EditorRegistry &editor_registry, SessionCoordinator &session_coordinator, ToastManager &toast_manager, PopupManager &popup_manager)
~MenuOrchestrator ()=default
MenuOrchestrator (const MenuOrchestrator &)=delete
MenuOrchestrator & operator= (const MenuOrchestrator &)=delete
void BuildMainMenu ()
void BuildFileMenu ()
void BuildEditMenu ()
void BuildViewMenu ()
void BuildToolsMenu ()
void BuildDebugMenu ()
void BuildWindowMenu ()
void BuildHelpMenu ()
void ClearMenu ()
void RefreshMenu ()
void OnOpenRom ()
void OnSaveRom ()
void OnSaveRomAs ()
void OnCreateProject ()
void OnOpenProject ()
void OnSaveProject ()
void OnSaveProjectAs ()
void OnUndo ()
void OnRedo ()
void OnCut ()
void OnCopy ()
void OnPaste ()
void OnFind ()
void OnSwitchToEditor (EditorType editor_type)
void OnShowEditorSelection ()
void OnShowDisplaySettings ()
void OnShowHexEditor ()
void OnShowEmulator ()
void OnShowCardBrowser ()
void OnShowWelcomeScreen ()
void OnCreateNewSession ()
void OnDuplicateCurrentSession ()
void OnCloseCurrentSession ()
void OnSwitchToSession (size_t session_index)
void OnShowSessionSwitcher ()
void OnShowSessionManager ()
void OnShowAllWindows ()
void OnHideAllWindows ()
void OnResetWorkspaceLayout ()
void OnSaveWorkspaceLayout ()
void OnLoadWorkspaceLayout ()
void OnShowLayoutPresets ()
void OnLoadDeveloperLayout ()
void OnLoadDesignerLayout ()
void OnLoadModderLayout ()
void OnShowGlobalSearch ()
void OnShowCommandPalette ()
void OnShowPerformanceDashboard ()
void OnShowImGuiDemo ()
void OnShowImGuiMetrics ()
void OnShowMemoryEditor ()
void OnShowResourceLabelManager ()
void OnShowRomInfo ()
void OnCreateBackup ()
void OnValidateRom ()
void OnRunDataIntegrityCheck ()
void OnTestSaveLoad ()
void OnCheckRomVersion ()
void OnUpgradeRom ()
void OnToggleCustomLoading ()
void OnToggleAsarPatch ()
void OnLoadAsmFile ()
void OnShowAssemblyEditor ()
void OnShowAbout ()
void OnShowKeyboardShortcuts ()
void OnShowUserGuide ()
void OnShowGettingStarted ()
void OnShowAsarIntegration ()
void OnShowBuildInstructions ()
void OnShowCLIUsage ()
void OnShowTroubleshooting ()
void OnShowContributing ()
void OnShowWhatsNew ()
void OnShowSupportedFeatures ()
void OnShowSettings ()
void OnQuit ()
Private Member Functions
void AddFileMenuItems ()
void AddEditMenuItems ()
void AddViewMenuItems ()
void AddToolsMenuItems ()
void AddDebugMenuItems ()
void AddWindowMenuItems ()
void AddHelpMenuItems ()
bool CanSaveRom () const
bool CanSaveProject () const
bool HasActiveRom () const
bool HasActiveProject () const
bool HasCurrentEditor () const
bool HasMultipleSessions () const
std::string GetRomFilename () const
std::string GetProjectName () const
std::string GetCurrentEditorName () const
std::string GetShortcutForAction (const std::string &action) const
void RegisterGlobalShortcuts ()
Private Attributes
EditorManager * editor_manager_
MenuBuilder & menu_builder_
RomFileManager & rom_manager_
ProjectManager & project_manager_
EditorRegistry & editor_registry_
SessionCoordinator & session_coordinator_
ToastManager & toast_manager_
PopupManager & popup_manager_
bool menu_needs_refresh_ = false
Detailed Description
Handles all menu building and UI coordination logic.
Extracted from EditorManager to provide focused menu management:
Menu structure and organization
Menu item callbacks and shortcuts
Editor-specific menu items
Session-aware menu updates
Menu state management
This class follows the Single Responsibility Principle by focusing solely on menu construction and coordination, delegating actual operations to specialized managers.
Definition at line 39 of file menu_orchestrator.h.
Constructor & Destructor Documentation
MenuOrchestrator() [1/2]
yaze::editor::MenuOrchestrator::MenuOrchestrator (EditorManager * editor_manager, MenuBuilder & menu_builder, RomFileManager & rom_manager, ProjectManager & project_manager, EditorRegistry & editor_registry, SessionCoordinator & session_coordinator, ToastManager & toast_manager, PopupManager & popup_manager)
Definition at line 21 of file menu_orchestrator.cc.
~MenuOrchestrator()
yaze::editor::MenuOrchestrator::~MenuOrchestrator () default
MenuOrchestrator() [2/2]
yaze::editor::MenuOrchestrator::MenuOrchestrator (const MenuOrchestrator &) delete
Member Function Documentation
operator=()
MenuOrchestrator & yaze::editor::MenuOrchestrator::operator= (const MenuOrchestrator &) delete
BuildMainMenu()
void yaze::editor::MenuOrchestrator::BuildMainMenu ()
Definition at line 40 of file menu_orchestrator.cc.
References BuildDebugMenu(), BuildEditMenu(), BuildFileMenu(), BuildHelpMenu(), BuildToolsMenu(), BuildViewMenu(), BuildWindowMenu(), ClearMenu(), yaze::editor::MenuBuilder::Draw(), menu_builder_, and menu_needs_refresh_.
BuildFileMenu()
void yaze::editor::MenuOrchestrator::BuildFileMenu ()
Definition at line 58 of file menu_orchestrator.cc.
References AddFileMenuItems(), yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::EndMenu(), and menu_builder_.
Referenced by BuildMainMenu().
BuildEditMenu()
void yaze::editor::MenuOrchestrator::BuildEditMenu ()
Definition at line 113 of file menu_orchestrator.cc.
References AddEditMenuItems(), yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::EndMenu(), and menu_builder_.
Referenced by BuildMainMenu().
BuildViewMenu()
void yaze::editor::MenuOrchestrator::BuildViewMenu ()
Definition at line 152 of file menu_orchestrator.cc.
References AddViewMenuItems(), yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::EndMenu(), and menu_builder_.
Referenced by BuildMainMenu().
BuildToolsMenu()
void yaze::editor::MenuOrchestrator::BuildToolsMenu ()
Definition at line 219 of file menu_orchestrator.cc.
References AddToolsMenuItems(), yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::EndMenu(), and menu_builder_.
Referenced by BuildMainMenu().
BuildDebugMenu()
void yaze::editor::MenuOrchestrator::BuildDebugMenu ()
Definition at line 254 of file menu_orchestrator.cc.
References AddDebugMenuItems(), yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::EndMenu(), and menu_builder_.
Referenced by BuildMainMenu().
BuildWindowMenu()
void yaze::editor::MenuOrchestrator::BuildWindowMenu ()
Definition at line 348 of file menu_orchestrator.cc.
References AddWindowMenuItems(), yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::EndMenu(), and menu_builder_.
Referenced by BuildMainMenu().
BuildHelpMenu()
void yaze::editor::MenuOrchestrator::BuildHelpMenu ()
Definition at line 405 of file menu_orchestrator.cc.
References AddHelpMenuItems(), yaze::editor::MenuBuilder::BeginMenu(), yaze::editor::MenuBuilder::EndMenu(), and menu_builder_.
Referenced by BuildMainMenu().
ClearMenu()
void yaze::editor::MenuOrchestrator::ClearMenu ()
Definition at line 437 of file menu_orchestrator.cc.
References yaze::editor::MenuBuilder::Clear(), and menu_builder_.
Referenced by BuildMainMenu().
RefreshMenu()
void yaze::editor::MenuOrchestrator::RefreshMenu ()
Definition at line 441 of file menu_orchestrator.cc.
References menu_needs_refresh_.
OnOpenRom()
void yaze::editor::MenuOrchestrator::OnOpenRom ()
Definition at line 446 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::kError, yaze::editor::EditorManager::LoadRom(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddFileMenuItems().
OnSaveRom()
void yaze::editor::MenuOrchestrator::OnSaveRom ()
Definition at line 458 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::kError, yaze::editor::kSuccess, yaze::editor::EditorManager::SaveRom(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddFileMenuItems().
OnSaveRomAs()
void yaze::editor::MenuOrchestrator::OnSaveRomAs ()
Definition at line 472 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kSaveAs, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddFileMenuItems().
OnCreateProject()
void yaze::editor::MenuOrchestrator::OnCreateProject ()
Definition at line 476 of file menu_orchestrator.cc.
References yaze::editor::EditorManager::CreateNewProject(), editor_manager_, yaze::editor::kError, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddFileMenuItems().
OnOpenProject()
void yaze::editor::MenuOrchestrator::OnOpenProject ()
Definition at line 488 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::kError, yaze::editor::EditorManager::OpenProject(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddFileMenuItems().
OnSaveProject()
void yaze::editor::MenuOrchestrator::OnSaveProject ()
Definition at line 500 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::kError, yaze::editor::kSuccess, yaze::editor::EditorManager::SaveProject(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddFileMenuItems().
OnSaveProjectAs()
void yaze::editor::MenuOrchestrator::OnSaveProjectAs ()
Definition at line 514 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::kError, yaze::editor::EditorManager::SaveProjectAs(), yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddFileMenuItems().
OnUndo()
void yaze::editor::MenuOrchestrator::OnUndo ()
Definition at line 527 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::kError, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddEditMenuItems().
OnRedo()
void yaze::editor::MenuOrchestrator::OnRedo ()
Definition at line 540 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::kError, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddEditMenuItems().
OnCut()
void yaze::editor::MenuOrchestrator::OnCut ()
Definition at line 553 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::kError, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddEditMenuItems().
OnCopy()
void yaze::editor::MenuOrchestrator::OnCopy ()
Definition at line 566 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::kError, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddEditMenuItems().
OnPaste()
void yaze::editor::MenuOrchestrator::OnPaste ()
Definition at line 579 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::kError, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddEditMenuItems().
OnFind()
void yaze::editor::MenuOrchestrator::OnFind ()
Definition at line 592 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::kError, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddEditMenuItems().
OnSwitchToEditor()
void yaze::editor::MenuOrchestrator::OnSwitchToEditor (EditorType editor_type)
Definition at line 606 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::SwitchToEditor().
Referenced by AddViewMenuItems().
OnShowEditorSelection()
void yaze::editor::MenuOrchestrator::OnShowEditorSelection ()
Definition at line 613 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ui_coordinator().
Referenced by AddViewMenuItems().
OnShowDisplaySettings()
void yaze::editor::MenuOrchestrator::OnShowDisplaySettings ()
Definition at line 622 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kDisplaySettings, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddViewMenuItems().
OnShowHexEditor()
void yaze::editor::MenuOrchestrator::OnShowHexEditor ()
Definition at line 626 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowHexEditor().
Referenced by AddViewMenuItems().
OnShowEmulator()
void yaze::editor::MenuOrchestrator::OnShowEmulator ()
Definition at line 633 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowEmulator().
Referenced by AddViewMenuItems().
OnShowCardBrowser()
void yaze::editor::MenuOrchestrator::OnShowCardBrowser ()
Definition at line 639 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowCardBrowser().
Referenced by AddViewMenuItems().
OnShowWelcomeScreen()
void yaze::editor::MenuOrchestrator::OnShowWelcomeScreen ()
Definition at line 645 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowWelcomeScreen().
Referenced by AddViewMenuItems().
OnCreateNewSession()
void yaze::editor::MenuOrchestrator::OnCreateNewSession ()
Definition at line 672 of file menu_orchestrator.cc.
References yaze::editor::SessionCoordinator::CreateNewSession(), and session_coordinator_.
Referenced by AddWindowMenuItems().
OnDuplicateCurrentSession()
void yaze::editor::MenuOrchestrator::OnDuplicateCurrentSession ()
Definition at line 676 of file menu_orchestrator.cc.
References yaze::editor::SessionCoordinator::DuplicateCurrentSession(), and session_coordinator_.
Referenced by AddWindowMenuItems().
OnCloseCurrentSession()
void yaze::editor::MenuOrchestrator::OnCloseCurrentSession ()
Definition at line 680 of file menu_orchestrator.cc.
References yaze::editor::SessionCoordinator::CloseCurrentSession(), and session_coordinator_.
Referenced by AddWindowMenuItems().
OnSwitchToSession()
void yaze::editor::MenuOrchestrator::OnSwitchToSession (size_t session_index)
Definition at line 684 of file menu_orchestrator.cc.
References session_coordinator_, and yaze::editor::SessionCoordinator::SwitchToSession().
OnShowSessionSwitcher()
void yaze::editor::MenuOrchestrator::OnShowSessionSwitcher ()
Definition at line 688 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ui_coordinator().
Referenced by AddWindowMenuItems().
OnShowSessionManager()
void yaze::editor::MenuOrchestrator::OnShowSessionManager ()
Todo:
Show session manager dialog
Definition at line 697 of file menu_orchestrator.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddWindowMenuItems().
OnShowAllWindows()
void yaze::editor::MenuOrchestrator::OnShowAllWindows ()
Definition at line 703 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowAllWindows().
Referenced by AddWindowMenuItems().
OnHideAllWindows()
void yaze::editor::MenuOrchestrator::OnHideAllWindows ()
Definition at line 710 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::HideAllWindows().
Referenced by AddWindowMenuItems().
OnResetWorkspaceLayout()
void yaze::editor::MenuOrchestrator::OnResetWorkspaceLayout ()
Definition at line 717 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ResetWorkspaceLayout().
Referenced by AddWindowMenuItems().
OnSaveWorkspaceLayout()
void yaze::editor::MenuOrchestrator::OnSaveWorkspaceLayout ()
Definition at line 724 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::SaveWorkspaceLayout().
Referenced by AddWindowMenuItems().
OnLoadWorkspaceLayout()
void yaze::editor::MenuOrchestrator::OnLoadWorkspaceLayout ()
Definition at line 731 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::LoadWorkspaceLayout().
Referenced by AddWindowMenuItems().
OnShowLayoutPresets()
void yaze::editor::MenuOrchestrator::OnShowLayoutPresets ()
Todo:
Show layout presets dialog
Definition at line 738 of file menu_orchestrator.cc.
References yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddWindowMenuItems().
OnLoadDeveloperLayout()
void yaze::editor::MenuOrchestrator::OnLoadDeveloperLayout ()
Definition at line 743 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::LoadDeveloperLayout().
Referenced by AddWindowMenuItems().
OnLoadDesignerLayout()
void yaze::editor::MenuOrchestrator::OnLoadDesignerLayout ()
Definition at line 749 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::LoadDesignerLayout().
Referenced by AddWindowMenuItems().
OnLoadModderLayout()
void yaze::editor::MenuOrchestrator::OnLoadModderLayout ()
Definition at line 755 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::LoadModderLayout().
Referenced by AddWindowMenuItems().
OnShowGlobalSearch()
void yaze::editor::MenuOrchestrator::OnShowGlobalSearch ()
Definition at line 762 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowGlobalSearch().
Referenced by AddEditMenuItems(), and AddToolsMenuItems().
OnShowCommandPalette()
void yaze::editor::MenuOrchestrator::OnShowCommandPalette ()
Definition at line 768 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowCommandPalette().
Referenced by AddToolsMenuItems().
OnShowPerformanceDashboard()
void yaze::editor::MenuOrchestrator::OnShowPerformanceDashboard ()
Definition at line 774 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowPerformanceDashboard().
Referenced by AddDebugMenuItems().
OnShowImGuiDemo()
void yaze::editor::MenuOrchestrator::OnShowImGuiDemo ()
Definition at line 780 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowImGuiDemo().
Referenced by AddDebugMenuItems().
OnShowImGuiMetrics()
void yaze::editor::MenuOrchestrator::OnShowImGuiMetrics ()
Definition at line 786 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowImGuiMetrics().
Referenced by AddDebugMenuItems().
OnShowMemoryEditor()
void yaze::editor::MenuOrchestrator::OnShowMemoryEditor ()
Definition at line 792 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowMemoryEditor().
Referenced by AddDebugMenuItems().
OnShowResourceLabelManager()
void yaze::editor::MenuOrchestrator::OnShowResourceLabelManager ()
Definition at line 798 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::ShowResourceLabelManager().
Referenced by AddToolsMenuItems().
OnShowRomInfo()
void yaze::editor::MenuOrchestrator::OnShowRomInfo ()
Definition at line 887 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kRomInfo, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddDebugMenuItems(), and AddFileMenuItems().
OnCreateBackup()
void yaze::editor::MenuOrchestrator::OnCreateBackup ()
Definition at line 891 of file menu_orchestrator.cc.
References yaze::Rom::SaveSettings::backup, editor_manager_, yaze::Rom::SaveSettings::filename, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::kError, yaze::editor::kSuccess, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddFileMenuItems().
OnValidateRom()
void yaze::editor::MenuOrchestrator::OnValidateRom ()
Definition at line 911 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::kError, yaze::editor::kSuccess, rom_manager_, yaze::editor::ToastManager::Show(), toast_manager_, and yaze::editor::RomFileManager::ValidateRom().
Referenced by AddFileMenuItems().
OnRunDataIntegrityCheck()
void yaze::editor::MenuOrchestrator::OnRunDataIntegrityCheck ()
Definition at line 993 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::kInfo, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddDebugMenuItems().
OnTestSaveLoad()
void yaze::editor::MenuOrchestrator::OnTestSaveLoad ()
Definition at line 1008 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::kInfo, yaze::editor::kSuccess, yaze::editor::kWarning, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddDebugMenuItems().
OnCheckRomVersion()
void yaze::editor::MenuOrchestrator::OnCheckRomVersion ()
Definition at line 1022 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::kInfo, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddDebugMenuItems().
OnUpgradeRom()
void yaze::editor::MenuOrchestrator::OnUpgradeRom ()
Definition at line 1039 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddDebugMenuItems().
OnToggleCustomLoading()
void yaze::editor::MenuOrchestrator::OnToggleCustomLoading ()
Definition at line 1049 of file menu_orchestrator.cc.
References yaze::core::FeatureFlags::get(), yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddDebugMenuItems().
OnToggleAsarPatch()
void yaze::editor::MenuOrchestrator::OnToggleAsarPatch ()
Definition at line 1059 of file menu_orchestrator.cc.
References editor_manager_, yaze::core::FeatureFlags::get(), yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::kInfo, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddDebugMenuItems().
OnLoadAsmFile()
void yaze::editor::MenuOrchestrator::OnLoadAsmFile ()
Definition at line 1073 of file menu_orchestrator.cc.
References yaze::editor::kWarning, yaze::editor::ToastManager::Show(), and toast_manager_.
Referenced by AddDebugMenuItems().
OnShowAssemblyEditor()
void yaze::editor::MenuOrchestrator::OnShowAssemblyEditor ()
Definition at line 1077 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::kAssembly, and yaze::editor::EditorManager::SwitchToEditor().
Referenced by AddDebugMenuItems().
OnShowAbout()
void yaze::editor::MenuOrchestrator::OnShowAbout ()
Definition at line 850 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kAbout, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowKeyboardShortcuts()
void yaze::editor::MenuOrchestrator::OnShowKeyboardShortcuts ()
OnShowUserGuide()
void yaze::editor::MenuOrchestrator::OnShowUserGuide ()
OnShowGettingStarted()
void yaze::editor::MenuOrchestrator::OnShowGettingStarted ()
Definition at line 854 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kGettingStarted, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowAsarIntegration()
void yaze::editor::MenuOrchestrator::OnShowAsarIntegration ()
Definition at line 858 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kAsarIntegration, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowBuildInstructions()
void yaze::editor::MenuOrchestrator::OnShowBuildInstructions ()
Definition at line 862 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kBuildInstructions, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowCLIUsage()
void yaze::editor::MenuOrchestrator::OnShowCLIUsage ()
Definition at line 866 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kCLIUsage, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowTroubleshooting()
void yaze::editor::MenuOrchestrator::OnShowTroubleshooting ()
Definition at line 870 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kTroubleshooting, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowContributing()
void yaze::editor::MenuOrchestrator::OnShowContributing ()
Definition at line 874 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kContributing, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowWhatsNew()
void yaze::editor::MenuOrchestrator::OnShowWhatsNew ()
Definition at line 878 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kWhatsNew, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowSupportedFeatures()
void yaze::editor::MenuOrchestrator::OnShowSupportedFeatures ()
Definition at line 882 of file menu_orchestrator.cc.
References yaze::editor::PopupID::kSupportedFeatures, popup_manager_, and yaze::editor::PopupManager::Show().
Referenced by AddHelpMenuItems().
OnShowSettings()
void yaze::editor::MenuOrchestrator::OnShowSettings ()
Definition at line 924 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::kSettings, and yaze::editor::EditorManager::SwitchToEditor().
Referenced by AddFileMenuItems().
OnQuit()
void yaze::editor::MenuOrchestrator::OnQuit ()
Definition at line 931 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::Quit().
Referenced by AddFileMenuItems().
AddFileMenuItems()
void yaze::editor::MenuOrchestrator::AddFileMenuItems () private
Definition at line 64 of file menu_orchestrator.cc.
References CanSaveProject(), CanSaveRom(), HasActiveRom(), ICON_MD_BACKUP, ICON_MD_CHECK_CIRCLE, ICON_MD_CREATE_NEW_FOLDER, ICON_MD_EXIT_TO_APP, ICON_MD_FILE_OPEN, ICON_MD_FOLDER_OPEN, ICON_MD_INFO, ICON_MD_SAVE, ICON_MD_SAVE_AS, ICON_MD_SETTINGS, yaze::editor::MenuBuilder::Item(), menu_builder_, OnCreateBackup(), OnCreateProject(), OnOpenProject(), OnOpenRom(), OnQuit(), OnSaveProject(), OnSaveProjectAs(), OnSaveRom(), OnSaveRomAs(), OnShowRomInfo(), OnShowSettings(), and OnValidateRom().
Referenced by BuildFileMenu().
AddEditMenuItems()
void yaze::editor::MenuOrchestrator::AddEditMenuItems () private
Definition at line 119 of file menu_orchestrator.cc.
References HasCurrentEditor(), ICON_MD_CONTENT_COPY, ICON_MD_CONTENT_CUT, ICON_MD_CONTENT_PASTE, ICON_MD_REDO, ICON_MD_SEARCH, ICON_MD_UNDO, yaze::editor::MenuBuilder::Item(), menu_builder_, OnCopy(), OnCut(), OnFind(), OnPaste(), OnRedo(), OnShowGlobalSearch(), and OnUndo().
Referenced by BuildEditMenu().
AddViewMenuItems()
void yaze::editor::MenuOrchestrator::AddViewMenuItems () private
Definition at line 158 of file menu_orchestrator.cc.
References ICON_MD_CASTLE, ICON_MD_CHAT, ICON_MD_CHAT_BUBBLE, ICON_MD_CODE, ICON_MD_DASHBOARD, ICON_MD_DATA_ARRAY, ICON_MD_DISPLAY_SETTINGS, ICON_MD_HOME, ICON_MD_IMAGE, ICON_MD_MAP, ICON_MD_MUSIC_NOTE, ICON_MD_PALETTE, ICON_MD_PREVIEW, ICON_MD_SMART_TOY, ICON_MD_TOYS, ICON_MD_TV, ICON_MD_VIDEOGAME_ASSET, yaze::editor::MenuBuilder::Item(), yaze::editor::kAssembly, yaze::editor::kDungeon, yaze::editor::kGraphics, yaze::editor::kMessage, yaze::editor::kMusic, yaze::editor::kOverworld, yaze::editor::kPalette, yaze::editor::kScreen, yaze::editor::kSprite, menu_builder_, OnShowCardBrowser(), OnShowDisplaySettings(), OnShowEditorSelection(), OnShowEmulator(), OnShowHexEditor(), OnShowWelcomeScreen(), and OnSwitchToEditor().
Referenced by BuildViewMenu().
AddToolsMenuItems()
void yaze::editor::MenuOrchestrator::AddToolsMenuItems () private
Definition at line 225 of file menu_orchestrator.cc.
References yaze::editor::MenuBuilder::BeginSubMenu(), ICON_MD_CLOUD, ICON_MD_GROUP_ADD, ICON_MD_LABEL, ICON_MD_PEOPLE, ICON_MD_PLAY_CIRCLE, ICON_MD_SEARCH, yaze::editor::MenuBuilder::Item(), menu_builder_, OnShowCommandPalette(), OnShowGlobalSearch(), and OnShowResourceLabelManager().
Referenced by BuildToolsMenu().
AddDebugMenuItems()
void yaze::editor::MenuOrchestrator::AddDebugMenuItems () private
Definition at line 260 of file menu_orchestrator.cc.
References yaze::editor::MenuBuilder::BeginSubMenu(), HasActiveRom(), ICON_MD_ANALYTICS, ICON_MD_BUILD, ICON_MD_CHECK_BOX, ICON_MD_CODE, ICON_MD_DASHBOARD, ICON_MD_FLAG, ICON_MD_FOLDER_OPEN, ICON_MD_HELP, ICON_MD_INFO, ICON_MD_INTEGRATION_INSTRUCTIONS, ICON_MD_MEMORY, ICON_MD_PLAY_ARROW, ICON_MD_PREVIEW, ICON_MD_SAVE_ALT, ICON_MD_SCIENCE, ICON_MD_SETTINGS, ICON_MD_SPEED, ICON_MD_STORAGE, ICON_MD_UPGRADE, ICON_MD_VISIBILITY, yaze::editor::MenuBuilder::Item(), yaze::editor::PopupID::kAsarIntegration, yaze::editor::PopupID::kFeatureFlags, menu_builder_, OnCheckRomVersion(), OnLoadAsmFile(), OnRunDataIntegrityCheck(), OnShowAssemblyEditor(), OnShowImGuiDemo(), OnShowImGuiMetrics(), OnShowMemoryEditor(), OnShowPerformanceDashboard(), OnShowRomInfo(), OnTestSaveLoad(), OnToggleAsarPatch(), OnToggleCustomLoading(), OnUpgradeRom(), popup_manager_, yaze::editor::MenuBuilder::Separator(), and yaze::editor::PopupManager::Show().
Referenced by BuildDebugMenu().
AddWindowMenuItems()
void yaze::editor::MenuOrchestrator::AddWindowMenuItems () private
Definition at line 354 of file menu_orchestrator.cc.
References yaze::editor::MenuBuilder::BeginSubMenu(), HasActiveRom(), HasMultipleSessions(), ICON_MD_ADD, ICON_MD_BOOKMARK, ICON_MD_CLOSE, ICON_MD_CONSTRUCTION, ICON_MD_CONTENT_COPY, ICON_MD_DESIGN_SERVICES, ICON_MD_DEVELOPER_MODE, ICON_MD_FOLDER_OPEN, ICON_MD_RESET_TV, ICON_MD_SAVE, ICON_MD_SWITCH_ACCOUNT, ICON_MD_TAB, ICON_MD_VIEW_LIST, ICON_MD_VISIBILITY, ICON_MD_VISIBILITY_OFF, yaze::editor::MenuBuilder::Item(), menu_builder_, OnCloseCurrentSession(), OnCreateNewSession(), OnDuplicateCurrentSession(), OnHideAllWindows(), OnLoadDesignerLayout(), OnLoadDeveloperLayout(), OnLoadModderLayout(), OnLoadWorkspaceLayout(), OnResetWorkspaceLayout(), OnSaveWorkspaceLayout(), OnShowAllWindows(), OnShowLayoutPresets(), OnShowSessionManager(), OnShowSessionSwitcher(), and yaze::editor::MenuBuilder::Separator().
Referenced by BuildWindowMenu().
AddHelpMenuItems()
void yaze::editor::MenuOrchestrator::AddHelpMenuItems () private
Definition at line 411 of file menu_orchestrator.cc.
References ICON_MD_BUILD, ICON_MD_BUILD_CIRCLE, ICON_MD_CHECK_CIRCLE, ICON_MD_CODE, ICON_MD_INFO, ICON_MD_NEW_RELEASES, ICON_MD_PLAY_ARROW, ICON_MD_TERMINAL, ICON_MD_VOLUNTEER_ACTIVISM, yaze::editor::MenuBuilder::Item(), menu_builder_, OnShowAbout(), OnShowAsarIntegration(), OnShowBuildInstructions(), OnShowCLIUsage(), OnShowContributing(), OnShowGettingStarted(), OnShowSupportedFeatures(), OnShowTroubleshooting(), and OnShowWhatsNew().
Referenced by BuildHelpMenu().
CanSaveRom()
bool yaze::editor::MenuOrchestrator::CanSaveRom () const private
Definition at line 938 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::RomFileManager::IsRomLoaded(), and rom_manager_.
Referenced by AddFileMenuItems().
CanSaveProject()
bool yaze::editor::MenuOrchestrator::CanSaveProject () const private
Definition at line 943 of file menu_orchestrator.cc.
References yaze::editor::ProjectManager::HasActiveProject(), and project_manager_.
Referenced by AddFileMenuItems().
HasActiveRom()
bool yaze::editor::MenuOrchestrator::HasActiveRom () const private
Definition at line 947 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::RomFileManager::IsRomLoaded(), and rom_manager_.
Referenced by AddDebugMenuItems(), AddFileMenuItems(), and AddWindowMenuItems().
HasActiveProject()
bool yaze::editor::MenuOrchestrator::HasActiveProject () const private
Definition at line 952 of file menu_orchestrator.cc.
References yaze::editor::ProjectManager::HasActiveProject(), and project_manager_.
HasCurrentEditor()
bool yaze::editor::MenuOrchestrator::HasCurrentEditor () const private
Definition at line 956 of file menu_orchestrator.cc.
References editor_manager_, and yaze::editor::EditorManager::GetCurrentEditor().
Referenced by AddEditMenuItems().
HasMultipleSessions()
bool yaze::editor::MenuOrchestrator::HasMultipleSessions () const private
Definition at line 960 of file menu_orchestrator.cc.
References yaze::editor::SessionCoordinator::HasMultipleSessions(), and session_coordinator_.
Referenced by AddWindowMenuItems().
GetRomFilename()
std::string yaze::editor::MenuOrchestrator::GetRomFilename () const private
Definition at line 965 of file menu_orchestrator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::RomFileManager::GetRomFilename(), and rom_manager_.
GetProjectName()
std::string yaze::editor::MenuOrchestrator::GetProjectName () const private
Definition at line 970 of file menu_orchestrator.cc.
References yaze::editor::ProjectManager::GetProjectName(), and project_manager_.
GetCurrentEditorName()
std::string yaze::editor::MenuOrchestrator::GetCurrentEditorName () const private
Todo:
Get current editor name
Definition at line 974 of file menu_orchestrator.cc.
GetShortcutForAction()
std::string yaze::editor::MenuOrchestrator::GetShortcutForAction (const std::string & action) const private
Todo:
Implement shortcut mapping
Definition at line 980 of file menu_orchestrator.cc.
RegisterGlobalShortcuts()
void yaze::editor::MenuOrchestrator::RegisterGlobalShortcuts () private
Todo:
Register global keyboard shortcuts
Definition at line 985 of file menu_orchestrator.cc.
Member Data Documentation
editor_manager_
EditorManager* yaze::editor::MenuOrchestrator::editor_manager_ private
Definition at line 182 of file menu_orchestrator.h.
Referenced by CanSaveRom(), GetRomFilename(), HasActiveRom(), HasCurrentEditor(), OnCheckRomVersion(), OnCopy(), OnCreateBackup(), OnCreateProject(), OnCut(), OnFind(), OnHideAllWindows(), OnLoadDesignerLayout(), OnLoadDeveloperLayout(), OnLoadModderLayout(), OnLoadWorkspaceLayout(), OnOpenProject(), OnOpenRom(), OnPaste(), OnQuit(), OnRedo(), OnResetWorkspaceLayout(), OnRunDataIntegrityCheck(), OnSaveProject(), OnSaveProjectAs(), OnSaveRom(), OnSaveWorkspaceLayout(), OnShowAllWindows(), OnShowAssemblyEditor(), OnShowCardBrowser(), OnShowCommandPalette(), OnShowEditorSelection(), OnShowEmulator(), OnShowGlobalSearch(), OnShowHexEditor(), OnShowImGuiDemo(), OnShowImGuiMetrics(), OnShowMemoryEditor(), OnShowPerformanceDashboard(), OnShowResourceLabelManager(), OnShowSessionSwitcher(), OnShowSettings(), OnShowWelcomeScreen(), OnSwitchToEditor(), OnTestSaveLoad(), OnToggleAsarPatch(), OnUndo(), OnUpgradeRom(), and OnValidateRom().
menu_builder_
MenuBuilder& yaze::editor::MenuOrchestrator::menu_builder_ private
Definition at line 183 of file menu_orchestrator.h.
Referenced by AddDebugMenuItems(), AddEditMenuItems(), AddFileMenuItems(), AddHelpMenuItems(), AddToolsMenuItems(), AddViewMenuItems(), AddWindowMenuItems(), BuildDebugMenu(), BuildEditMenu(), BuildFileMenu(), BuildHelpMenu(), BuildMainMenu(), BuildToolsMenu(), BuildViewMenu(), BuildWindowMenu(), and ClearMenu().
rom_manager_
RomFileManager& yaze::editor::MenuOrchestrator::rom_manager_ private
Definition at line 184 of file menu_orchestrator.h.
Referenced by CanSaveRom(), GetRomFilename(), HasActiveRom(), and OnValidateRom().
project_manager_
ProjectManager& yaze::editor::MenuOrchestrator::project_manager_ private
Definition at line 185 of file menu_orchestrator.h.
Referenced by CanSaveProject(), GetProjectName(), and HasActiveProject().
editor_registry_
EditorRegistry& yaze::editor::MenuOrchestrator::editor_registry_ private
Definition at line 186 of file menu_orchestrator.h.
session_coordinator_
SessionCoordinator& yaze::editor::MenuOrchestrator::session_coordinator_ private
Definition at line 187 of file menu_orchestrator.h.
Referenced by HasMultipleSessions(), OnCloseCurrentSession(), OnCreateNewSession(), OnDuplicateCurrentSession(), and OnSwitchToSession().
toast_manager_
ToastManager& yaze::editor::MenuOrchestrator::toast_manager_ private
Definition at line 188 of file menu_orchestrator.h.
Referenced by OnCheckRomVersion(), OnCopy(), OnCreateBackup(), OnCreateProject(), OnCut(), OnFind(), OnLoadAsmFile(), OnOpenProject(), OnOpenRom(), OnPaste(), OnRedo(), OnRunDataIntegrityCheck(), OnSaveProject(), OnSaveProjectAs(), OnSaveRom(), OnShowLayoutPresets(), OnShowSessionManager(), OnTestSaveLoad(), OnToggleAsarPatch(), OnToggleCustomLoading(), OnUndo(), OnUpgradeRom(), and OnValidateRom().
popup_manager_
PopupManager& yaze::editor::MenuOrchestrator::popup_manager_ private
Definition at line 189 of file menu_orchestrator.h.
Referenced by AddDebugMenuItems(), OnSaveRomAs(), OnShowAbout(), OnShowAsarIntegration(), OnShowBuildInstructions(), OnShowCLIUsage(), OnShowContributing(), OnShowDisplaySettings(), OnShowGettingStarted(), OnShowRomInfo(), OnShowSupportedFeatures(), OnShowTroubleshooting(), and OnShowWhatsNew().
menu_needs_refresh_
bool yaze::editor::MenuOrchestrator::menu_needs_refresh_ = false private
Definition at line 192 of file menu_orchestrator.h.
Referenced by BuildMainMenu(), and RefreshMenu().
The documentation for this class was generated from the following files:
src/app/editor/system/menu_orchestrator.h
src/app/editor/system/menu_orchestrator.cc