yaze: yaze::gui::canvas::CanvasConfig Struct Reference
yaze::gui::canvas::CanvasConfig Struct Reference
Canvas configuration options for modals.
#include <canvas_modals.h>
Public Attributes
ImVec2 canvas_size = ImVec2(0, 0)
ImVec2 content_size = ImVec2(0, 0)
float global_scale = 1.0f
float grid_step = 32.0f
bool enable_grid = true
bool enable_hex_labels = false
bool enable_custom_labels = false
bool enable_context_menu = true
bool is_draggable = false
bool auto_resize = false
ImVec2 scrolling = ImVec2(0, 0)
std::function< void(const CanvasConfig &)> on_config_changed
std::function< void(const CanvasConfig &)> on_scale_changed
bool custom_canvas_size = false
Detailed Description
Canvas configuration options for modals.
Configuration for canvas display and interaction.
Modern single-source-of-truth configuration structure. Replaces the dual state management pattern.
Definition at line 25 of file canvas_modals.h.
Member Data Documentation
canvas_size
ImVec2 yaze::gui::canvas::CanvasConfig::canvas_size = ImVec2(0, 0)
Definition at line 26 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::canvas::CanvasModals::RenderScalingControlsModal(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
content_size
ImVec2 yaze::gui::canvas::CanvasConfig::content_size = ImVec2(0, 0)
Definition at line 27 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
global_scale
float yaze::gui::canvas::CanvasConfig::global_scale = 1.0f
Definition at line 28 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::ApplyScaleSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderScalingControlsMenu(), yaze::gui::canvas::CanvasModals::RenderScalingControlsModal(), yaze::gui::canvas::CanvasContextMenu::RenderViewControlsMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
grid_step
float yaze::gui::canvas::CanvasConfig::grid_step = 32.0f
Definition at line 29 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::canvas::CanvasContextMenu::RenderGridControlsMenu(), yaze::gui::canvas::CanvasModals::RenderScalingControlsModal(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
enable_grid
bool yaze::gui::canvas::CanvasConfig::enable_grid = true
Definition at line 30 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::canvas::CanvasContextMenu::RenderViewControlsMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
enable_hex_labels
bool yaze::gui::canvas::CanvasConfig::enable_hex_labels = false
Definition at line 31 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::canvas::CanvasContextMenu::RenderViewControlsMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
enable_custom_labels
bool yaze::gui::canvas::CanvasConfig::enable_custom_labels = false
Definition at line 32 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::canvas::CanvasContextMenu::RenderViewControlsMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
enable_context_menu
bool yaze::gui::canvas::CanvasConfig::enable_context_menu = true
Definition at line 33 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
is_draggable
bool yaze::gui::canvas::CanvasConfig::is_draggable = false
Definition at line 34 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
auto_resize
bool yaze::gui::canvas::CanvasConfig::auto_resize = false
Definition at line 35 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
scrolling
ImVec2 yaze::gui::canvas::CanvasConfig::scrolling = ImVec2(0, 0)
Definition at line 36 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::ApplyConfigSnapshot(), yaze::gui::Canvas::ApplyScaleSnapshot(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::canvas::CanvasContextMenu::RenderCanvasPropertiesMenu(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), and yaze::gui::Canvas::ShowScalingControls().
on_config_changed
std::function< void(const CanvasConfig &)> yaze::gui::canvas::CanvasConfig::on_config_changed
Definition at line 39 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), yaze::gui::canvas::CanvasModals::ShowAdvancedProperties(), yaze::gui::Canvas::ShowScalingControls(), and yaze::gui::canvas::CanvasModals::ShowScalingControls().
on_scale_changed
std::function< void(const CanvasConfig &)> yaze::gui::canvas::CanvasConfig::on_scale_changed
Definition at line 40 of file canvas_modals.h.
Referenced by yaze::gui::Canvas::DrawContextMenu(), yaze::gui::canvas::CanvasModals::RenderScalingControlsModal(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), yaze::gui::canvas::CanvasModals::ShowAdvancedProperties(), yaze::gui::Canvas::ShowScalingControls(), and yaze::gui::canvas::CanvasModals::ShowScalingControls().
custom_canvas_size
bool yaze::gui::canvas::CanvasConfig::custom_canvas_size = false
Definition at line 32 of file canvas_utils_moved.h.
The documentation for this struct was generated from the following files:
src/app/gui/canvas/canvas_modals.h
src/app/gui/canvas/canvas_utils_moved.h