yaze: yaze::cli::RomDiff Class Reference
yaze::cli::RomDiff Class Reference
#include <cli.h>
Public Member Functions
absl::Status Run (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
virtual void RunTUI (ftxui::ScreenInteractive &screen)
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
Rom rom_
Detailed Description
Definition at line 174 of file cli.h.
Member Function Documentation
Run()
absl::Status yaze::cli::RomDiff::Run (const std::vector< std::string > & arg_vec) override virtual
Implements yaze::cli::CommandHandler.
Definition at line 76 of file rom.cc.
References yaze::RomLoadOptions::CliDefaults(), yaze::Rom::LoadFromFile(), yaze::Rom::size(), and yaze::Rom::vector().
Referenced by yaze::cli::agent::HandleDiffCommand(), and yaze::cli::ModernCLI::HandleRomDiffCommand().
The documentation for this class was generated from the following files:
src/cli/cli.h
src/cli/handlers/rom.cc