yaze: yaze::cli::HexViewerComponent Class Reference
yaze::cli::HexViewerComponent Class Reference
#include <hex_viewer.h>
Public Member Functions
HexViewerComponent (Rom *rom, std::function< void()> on_back)
ftxui::Component Render () override
Public Member Functions inherited from yaze::cli::TuiComponent
virtual ~TuiComponent ()=default
Private Attributes
Rom * rom_
std::function< void()> on_back_
int offset_ = 0
const int lines_to_show_ = 20
ftxui::Component component_ = nullptr
Detailed Description
Definition at line 11 of file hex_viewer.h.
Constructor & Destructor Documentation
HexViewerComponent()
yaze::cli::HexViewerComponent::HexViewerComponent (Rom * rom, std::function< void()> on_back) explicit
Definition at line 12 of file hex_viewer.cc.
Member Function Documentation
Render()
ftxui::Component yaze::cli::HexViewerComponent::Render () override virtual
Implements yaze::cli::TuiComponent.
Definition at line 15 of file hex_viewer.cc.
References component_, yaze::Rom::is_loaded(), lines_to_show_, offset_, rom_, yaze::Rom::size(), and yaze::Rom::vector().
Member Data Documentation
rom_
Rom* yaze::cli::HexViewerComponent::rom_ private
Definition at line 17 of file hex_viewer.h.
Referenced by Render().
on_back_
std::function<void()> yaze::cli::HexViewerComponent::on_back_ private
Definition at line 18 of file hex_viewer.h.
offset_
int yaze::cli::HexViewerComponent::offset_ = 0 private
Definition at line 19 of file hex_viewer.h.
Referenced by Render().
lines_to_show_
const int yaze::cli::HexViewerComponent::lines_to_show_ = 20 private
Definition at line 20 of file hex_viewer.h.
Referenced by Render().
component_
ftxui::Component yaze::cli::HexViewerComponent::component_ = nullptr private
Definition at line 22 of file hex_viewer.h.
Referenced by Render().
The documentation for this class was generated from the following files:
src/cli/tui/hex_viewer.h
src/cli/tui/hex_viewer.cc