yaze: yaze::gfx::anonymous_namespace{palette_manager_test.cc} Namespace Reference
yaze::gfx::anonymous_namespace{palette_manager_test.cc} Namespace Reference
Classes
class PaletteManagerTest
Functions
TEST_F (PaletteManagerTest, InitializationState)
TEST_F (PaletteManagerTest, HasNoUnsavedChangesInitially)
TEST_F (PaletteManagerTest, TracksModifiedGroups)
TEST_F (PaletteManagerTest, GetModifiedColorCount)
TEST_F (PaletteManagerTest, UndoRedoInitialState)
TEST_F (PaletteManagerTest, ClearHistoryResetsStacks)
TEST_F (PaletteManagerTest, UndoWithoutChangesIsNoOp)
TEST_F (PaletteManagerTest, RedoWithoutUndoIsNoOp)
TEST_F (PaletteManagerTest, BatchModeTracking)
TEST_F (PaletteManagerTest, NestedBatchOperations)
TEST_F (PaletteManagerTest, EndBatchWithoutBeginIsNoOp)
TEST_F (PaletteManagerTest, RegisterAndUnregisterListener)
TEST_F (PaletteManagerTest, MultipleListeners)
TEST_F (PaletteManagerTest, GetColorWithoutInitialization)
TEST_F (PaletteManagerTest, SetColorWithoutInitializationFails)
TEST_F (PaletteManagerTest, ResetColorWithoutInitializationReturnsError)
TEST_F (PaletteManagerTest, ResetPaletteWithoutInitializationFails)
TEST_F (PaletteManagerTest, SaveGroupWithoutInitializationFails)
TEST_F (PaletteManagerTest, SaveAllWithoutInitializationFails)
TEST_F (PaletteManagerTest, DiscardGroupWithoutInitializationIsNoOp)
TEST_F (PaletteManagerTest, DiscardAllWithoutInitializationIsNoOp)
TEST_F (PaletteManagerTest, IsGroupModifiedInitiallyFalse)
TEST_F (PaletteManagerTest, IsPaletteModifiedInitiallyFalse)
TEST_F (PaletteManagerTest, IsColorModifiedInitiallyFalse)
TEST_F (PaletteManagerTest, SetColorInvalidGroupName)
TEST_F (PaletteManagerTest, GetColorInvalidGroupName)
TEST_F (PaletteManagerTest, IsGroupModifiedInvalidGroupName)
Function Documentation
TEST_F() [1/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , InitializationState)
Definition at line 32 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [2/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , HasNoUnsavedChangesInitially)
Definition at line 44 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [3/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , TracksModifiedGroups)
Definition at line 56 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [4/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , GetModifiedColorCount)
Definition at line 64 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [5/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , UndoRedoInitialState)
Definition at line 78 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [6/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , ClearHistoryResetsStacks)
Definition at line 88 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [7/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , UndoWithoutChangesIsNoOp)
Definition at line 100 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [8/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , RedoWithoutUndoIsNoOp)
Definition at line 111 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [9/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , BatchModeTracking)
Definition at line 126 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [10/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , NestedBatchOperations)
Definition at line 138 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [11/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , EndBatchWithoutBeginIsNoOp)
Definition at line 156 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [12/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , RegisterAndUnregisterListener)
Definition at line 171 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [13/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , MultipleListeners)
Definition at line 190 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [14/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , GetColorWithoutInitialization)
Definition at line 218 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get(), and yaze::gfx::SnesColor::rgb().
TEST_F() [15/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , SetColorWithoutInitializationFails)
Definition at line 231 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [16/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , ResetColorWithoutInitializationReturnsError)
Definition at line 241 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [17/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , ResetPaletteWithoutInitializationFails)
Definition at line 250 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [18/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , SaveGroupWithoutInitializationFails)
Definition at line 263 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [19/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , SaveAllWithoutInitializationFails)
Definition at line 272 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [20/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , DiscardGroupWithoutInitializationIsNoOp)
Definition at line 281 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [21/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , DiscardAllWithoutInitializationIsNoOp)
Definition at line 291 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [22/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , IsGroupModifiedInitiallyFalse)
Definition at line 305 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [23/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , IsPaletteModifiedInitiallyFalse)
Definition at line 313 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [24/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , IsColorModifiedInitiallyFalse)
Definition at line 320 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [25/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , SetColorInvalidGroupName)
Definition at line 331 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().
TEST_F() [26/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , GetColorInvalidGroupName)
Definition at line 340 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get(), and yaze::gfx::SnesColor::rgb().
TEST_F() [27/27]
yaze::gfx::anonymous_namespace{palette_manager_test.cc}::TEST_F (PaletteManagerTest , IsGroupModifiedInvalidGroupName)
Definition at line 352 of file palette_manager_test.cc.
References yaze::gfx::PaletteManager::Get().