yaze: yaze::editor::DungeonCanvasViewer Class Reference
yaze::editor::DungeonCanvasViewer Class Reference
Handles the main dungeon canvas rendering and interaction.
#include <dungeon_canvas_viewer.h>
Classes
struct ObjectOutlineToggles
struct ObjectRenderCache
struct RoomLayerSettings
Public Member Functions
DungeonCanvasViewer (Rom *rom=nullptr)
void DrawDungeonCanvas (int room_id)
void Draw (int room_id)
void SetRom (Rom *rom)
Rom * rom () const
void SetRooms (std::array< zelda3::Room, 0x128 > *rooms)
void set_active_rooms (const ImVector< int > &rooms)
void set_current_active_room_tab (int tab)
void set_current_palette_group_id (uint64_t id)
void SetCurrentPaletteId (uint64_t id)
void SetCurrentPaletteGroup (const gfx::PaletteGroup &group)
gui::Canvas & canvas ()
const gui::Canvas & canvas () const
DungeonObjectInteraction & object_interaction ()
void SetObjectInteractionEnabled (bool enabled)
bool IsObjectInteractionEnabled () const
void SetBG1Visible (int room_id, bool visible)
void SetBG2Visible (int room_id, bool visible)
bool IsBG1Visible (int room_id) const
bool IsBG2Visible (int room_id) const
void SetBG2LayerType (int room_id, int type)
int GetBG2LayerType (int room_id) const
void SetPreviewObject (const zelda3::RoomObject &object)
void ClearPreviewObject ()
Private Member Functions
void DisplayObjectInfo (const zelda3::RoomObject &object, int canvas_x, int canvas_y)
void RenderSprites (const zelda3::Room &room)
std::pair< int, int > RoomToCanvasCoordinates (int room_x, int room_y) const
std::pair< int, int > CanvasToRoomCoordinates (int canvas_x, int canvas_y) const
bool IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin=32) const
void CalculateWallDimensions (const zelda3::RoomObject &object, int &width, int &height)
void DrawObjectPositionOutlines (const zelda3::Room &room)
absl::Status LoadAndRenderRoomGraphics (int room_id)
void DrawRoomBackgroundLayers (int room_id)
RoomLayerSettings & GetRoomLayerSettings (int room_id)
Private Attributes
Rom * rom_ = nullptr
gui::Canvas canvas_ {"##DungeonCanvas", ImVec2(0x200, 0x200)}
DungeonObjectInteraction object_interaction_
std::array< zelda3::Room, 0x128 > * rooms_ = nullptr
ImVector< int > active_rooms_
int current_active_room_tab_ = 0
bool object_interaction_enabled_ = true
std::map< int, RoomLayerSettings > room_layer_settings_
uint64_t current_palette_group_id_ = 0
uint64_t current_palette_id_ = 0
gfx::PaletteGroup current_palette_group_
std::vector< ObjectRenderCache > object_render_cache_
uint64_t last_palette_hash_ = 0
bool show_room_debug_info_ = false
bool show_texture_debug_ = false
bool show_object_bounds_ = false
bool show_layer_info_ = false
int layout_override_ = -1
ObjectOutlineToggles object_outline_toggles_
Detailed Description
Handles the main dungeon canvas rendering and interaction.
In Link to the Past, dungeon "layers" are not separate visual layers but a game concept where objects exist on different logical levels. Players move between these levels using stair objects that act as transitions between the different object planes.
Definition at line 24 of file dungeon_canvas_viewer.h.
Constructor & Destructor Documentation
DungeonCanvasViewer()
yaze::editor::DungeonCanvasViewer::DungeonCanvasViewer (Rom * rom = nullptr) inline explicit
Definition at line 26 of file dungeon_canvas_viewer.h.
Member Function Documentation
DrawDungeonCanvas()
void yaze::editor::DungeonCanvasViewer::DrawDungeonCanvas (int room_id)
Todo:
Show object palette/selector
Definition at line 21 of file dungeon_canvas_viewer.cc.
References yaze::gui::Canvas::AddContextMenuItem(), yaze::gui::Canvas::ContextMenuItem::callback, canvas_, yaze::gui::Canvas::canvas_size(), yaze::editor::DungeonObjectInteraction::CheckForObjectSelection(), yaze::gui::Canvas::ClearContextMenuItems(), yaze::gui::Canvas::custom_step(), yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), DrawObjectPositionOutlines(), yaze::gui::Canvas::DrawOverlay(), DrawRoomBackgroundLayers(), yaze::editor::DungeonObjectInteraction::DrawSelectBox(), yaze::editor::DungeonObjectInteraction::DrawSelectionHighlights(), yaze::gui::Canvas::DrawText(), yaze::gui::Canvas::ContextMenuItem::enabled_condition, yaze::gfx::Arena::Get(), GetRoomLayerSettings(), yaze::gui::Canvas::global_scale(), yaze::editor::DungeonObjectInteraction::HandleCanvasMouseInput(), yaze::editor::DungeonObjectInteraction::HandleDeleteSelected(), yaze::gui::Canvas::height(), ICON_MD_ADD, ICON_MD_BUG_REPORT, ICON_MD_CROP_SQUARE, ICON_MD_DELETE, ICON_MD_IMAGE, ICON_MD_INFO, ICON_MD_LAYERS, ICON_MD_PRINT, ICON_MD_REFRESH, yaze::gui::InputHexByte(), yaze::gui::InputHexWord(), yaze::Rom::is_loaded(), yaze::gui::k8x8, yaze::gui::Canvas::ContextMenuItem::label, layout_override_, LoadAndRenderRoomGraphics(), LOG_DEBUG, object_interaction_, object_interaction_enabled_, object_outline_toggles_, yaze::gfx::Arena::ProcessTextureQueue(), RenderSprites(), rom_, rooms_, yaze::gui::Canvas::SetCanvasSize(), yaze::editor::DungeonObjectInteraction::SetCurrentRoom(), yaze::gui::Canvas::SetGridSize(), yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_layer0_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_layer1_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_layer2_objects, show_layer_info_, show_object_bounds_, show_room_debug_info_, show_texture_debug_, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_type1_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_type2_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_type3_objects, yaze::editor::DungeonObjectInteraction::ShowContextMenu(), yaze::gui::Canvas::ContextMenuItem::subitems, yaze::gui::Canvas::width(), and yaze::gui::Canvas::zero_point().
Referenced by Draw(), and yaze::editor::DungeonEditorV2::DrawRoomTab().
Draw()
void yaze::editor::DungeonCanvasViewer::Draw (int room_id)
Definition at line 17 of file dungeon_canvas_viewer.cc.
References DrawDungeonCanvas().
SetRom()
void yaze::editor::DungeonCanvasViewer::SetRom (Rom * rom) inline
Definition at line 33 of file dungeon_canvas_viewer.h.
References rom(), and rom_.
Referenced by yaze::editor::DungeonEditorV2::set_rom().
rom()
Rom * yaze::editor::DungeonCanvasViewer::rom () const inline
Definition at line 36 of file dungeon_canvas_viewer.h.
References rom_.
Referenced by SetRom().
SetRooms()
void yaze::editor::DungeonCanvasViewer::SetRooms (std::array< zelda3::Room, 0x128 > * rooms) inline
Definition at line 39 of file dungeon_canvas_viewer.h.
References rooms_.
Referenced by yaze::editor::DungeonEditorV2::Load().
set_active_rooms()
void yaze::editor::DungeonCanvasViewer::set_active_rooms (const ImVector< int > & rooms) inline
Definition at line 41 of file dungeon_canvas_viewer.h.
References active_rooms_.
set_current_active_room_tab()
void yaze::editor::DungeonCanvasViewer::set_current_active_room_tab (int tab) inline
Definition at line 42 of file dungeon_canvas_viewer.h.
References current_active_room_tab_.
set_current_palette_group_id()
void yaze::editor::DungeonCanvasViewer::set_current_palette_group_id (uint64_t id) inline
Definition at line 45 of file dungeon_canvas_viewer.h.
References current_palette_group_id_.
SetCurrentPaletteId()
void yaze::editor::DungeonCanvasViewer::SetCurrentPaletteId (uint64_t id) inline
Definition at line 46 of file dungeon_canvas_viewer.h.
References current_palette_id_.
Referenced by yaze::editor::DungeonEditorV2::Load().
SetCurrentPaletteGroup()
void yaze::editor::DungeonCanvasViewer::SetCurrentPaletteGroup (const gfx::PaletteGroup & group) inline
Definition at line 47 of file dungeon_canvas_viewer.h.
References current_palette_group_.
Referenced by yaze::editor::DungeonEditorV2::Load().
canvas() [1/2]
gui::Canvas & yaze::editor::DungeonCanvasViewer::canvas () inline
Definition at line 50 of file dungeon_canvas_viewer.h.
References canvas_.
canvas() [2/2]
const gui::Canvas & yaze::editor::DungeonCanvasViewer::canvas () const inline
Definition at line 51 of file dungeon_canvas_viewer.h.
References canvas_.
object_interaction()
DungeonObjectInteraction & yaze::editor::DungeonCanvasViewer::object_interaction () inline
Definition at line 54 of file dungeon_canvas_viewer.h.
References object_interaction_.
Referenced by yaze::editor::ObjectEditorCard::DrawSelectedObjectInfo().
SetObjectInteractionEnabled()
void yaze::editor::DungeonCanvasViewer::SetObjectInteractionEnabled (bool enabled) inline
Definition at line 57 of file dungeon_canvas_viewer.h.
References object_interaction_enabled_.
Referenced by yaze::editor::ObjectEditorCard::Draw(), and yaze::editor::ObjectEditorCard::DrawObjectSelector().
IsObjectInteractionEnabled()
bool yaze::editor::DungeonCanvasViewer::IsObjectInteractionEnabled () const inline
Definition at line 58 of file dungeon_canvas_viewer.h.
References object_interaction_enabled_.
SetBG1Visible()
void yaze::editor::DungeonCanvasViewer::SetBG1Visible (int room_id, bool visible) inline
Definition at line 61 of file dungeon_canvas_viewer.h.
References yaze::editor::DungeonCanvasViewer::RoomLayerSettings::bg1_visible, and GetRoomLayerSettings().
SetBG2Visible()
void yaze::editor::DungeonCanvasViewer::SetBG2Visible (int room_id, bool visible) inline
Definition at line 64 of file dungeon_canvas_viewer.h.
References yaze::editor::DungeonCanvasViewer::RoomLayerSettings::bg2_visible, and GetRoomLayerSettings().
IsBG1Visible()
bool yaze::editor::DungeonCanvasViewer::IsBG1Visible (int room_id) const inline
Definition at line 67 of file dungeon_canvas_viewer.h.
References room_layer_settings_.
IsBG2Visible()
bool yaze::editor::DungeonCanvasViewer::IsBG2Visible (int room_id) const inline
Definition at line 71 of file dungeon_canvas_viewer.h.
References room_layer_settings_.
SetBG2LayerType()
void yaze::editor::DungeonCanvasViewer::SetBG2LayerType (int room_id, int type) inline
Definition at line 77 of file dungeon_canvas_viewer.h.
References yaze::editor::DungeonCanvasViewer::RoomLayerSettings::bg2_layer_type, and GetRoomLayerSettings().
GetBG2LayerType()
int yaze::editor::DungeonCanvasViewer::GetBG2LayerType (int room_id) const inline
Definition at line 80 of file dungeon_canvas_viewer.h.
References room_layer_settings_.
SetPreviewObject()
void yaze::editor::DungeonCanvasViewer::SetPreviewObject (const zelda3::RoomObject & object) inline
Definition at line 86 of file dungeon_canvas_viewer.h.
References object_interaction_, and yaze::editor::DungeonObjectInteraction::SetPreviewObject().
Referenced by yaze::editor::ObjectEditorCard::Draw(), and yaze::editor::ObjectEditorCard::DrawObjectSelector().
ClearPreviewObject()
void yaze::editor::DungeonCanvasViewer::ClearPreviewObject () inline
Definition at line 89 of file dungeon_canvas_viewer.h.
References object_interaction_, and yaze::editor::DungeonObjectInteraction::SetPreviewObject().
Referenced by yaze::editor::ObjectEditorCard::Draw(), and yaze::editor::ObjectEditorCard::DrawObjectSelector().
DisplayObjectInfo()
void yaze::editor::DungeonCanvasViewer::DisplayObjectInfo (const zelda3::RoomObject & object, int canvas_x, int canvas_y) private
Definition at line 569 of file dungeon_canvas_viewer.cc.
References canvas_, and yaze::gui::Canvas::DrawText().
RenderSprites()
void yaze::editor::DungeonCanvasViewer::RenderSprites (const zelda3::Room & room) private
Definition at line 579 of file dungeon_canvas_viewer.cc.
References canvas_, yaze::gui::Canvas::DrawRect(), yaze::gui::Canvas::DrawText(), yaze::zelda3::Room::GetSprites(), IsWithinCanvasBounds(), and RoomToCanvasCoordinates().
Referenced by DrawDungeonCanvas().
RoomToCanvasCoordinates()
std::pair< int, int > yaze::editor::DungeonCanvasViewer::RoomToCanvasCoordinates (int room_x, int room_y) const private
Definition at line 626 of file dungeon_canvas_viewer.cc.
Referenced by DrawObjectPositionOutlines(), and RenderSprites().
CanvasToRoomCoordinates()
std::pair< int, int > yaze::editor::DungeonCanvasViewer::CanvasToRoomCoordinates (int canvas_x, int canvas_y) const private
Definition at line 637 of file dungeon_canvas_viewer.cc.
References canvas_, and yaze::gui::Canvas::global_scale().
IsWithinCanvasBounds()
bool yaze::editor::DungeonCanvasViewer::IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin = 32) const private
Definition at line 655 of file dungeon_canvas_viewer.cc.
References canvas_, yaze::gui::Canvas::height(), and yaze::gui::Canvas::width().
Referenced by RenderSprites().
CalculateWallDimensions()
void yaze::editor::DungeonCanvasViewer::CalculateWallDimensions (const zelda3::RoomObject & object, int & width, int & height) private
Definition at line 665 of file dungeon_canvas_viewer.cc.
DrawObjectPositionOutlines()
void yaze::editor::DungeonCanvasViewer::DrawObjectPositionOutlines (const zelda3::Room & room) private
Definition at line 704 of file dungeon_canvas_viewer.cc.
References canvas_, yaze::gui::Canvas::DrawRect(), yaze::gui::Canvas::DrawText(), yaze::zelda3::Room::GetTileObjects(), object_outline_toggles_, RoomToCanvasCoordinates(), yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_layer0_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_layer1_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_layer2_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_type1_objects, yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_type2_objects, and yaze::editor::DungeonCanvasViewer::ObjectOutlineToggles::show_type3_objects.
Referenced by DrawDungeonCanvas().
LoadAndRenderRoomGraphics()
absl::Status yaze::editor::DungeonCanvasViewer::LoadAndRenderRoomGraphics (int room_id) private
Todo:
Fix palette assignment to buffer.
Definition at line 779 of file dungeon_canvas_viewer.cc.
References ASSIGN_OR_RETURN, yaze::gfx::CreatePaletteGroupFromLargePalette(), current_palette_group_, current_palette_group_id_, yaze::Rom::is_loaded(), LOG_DEBUG, yaze::Rom::palette_group(), yaze::Rom::paletteset_ids, yaze::Rom::ReadWord(), rom_, and rooms_.
Referenced by DrawDungeonCanvas().
DrawRoomBackgroundLayers()
void yaze::editor::DungeonCanvasViewer::DrawRoomBackgroundLayers (int room_id) private
Definition at line 831 of file dungeon_canvas_viewer.cc.
References canvas_, yaze::gfx::Arena::CREATE, yaze::gui::Canvas::DrawBitmap(), yaze::gfx::Arena::Get(), GetRoomLayerSettings(), yaze::gui::Canvas::global_scale(), yaze::gui::Canvas::height(), LOG_DEBUG, yaze::zelda3::NumberOfRooms, yaze::gfx::Arena::ProcessTextureQueue(), yaze::gfx::Arena::QueueTextureCommand(), rooms_, yaze::gui::Canvas::width(), and yaze::gui::Canvas::zero_point().
Referenced by DrawDungeonCanvas().
GetRoomLayerSettings()
RoomLayerSettings & yaze::editor::DungeonCanvasViewer::GetRoomLayerSettings (int room_id) inline private
Definition at line 137 of file dungeon_canvas_viewer.h.
References room_layer_settings_.
Referenced by DrawDungeonCanvas(), DrawRoomBackgroundLayers(), SetBG1Visible(), SetBG2LayerType(), and SetBG2Visible().
Member Data Documentation
rom_
Rom* yaze::editor::DungeonCanvasViewer::rom_ = nullptr private
Definition at line 114 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas(), LoadAndRenderRoomGraphics(), rom(), and SetRom().
canvas_
gui::Canvas yaze::editor::DungeonCanvasViewer::canvas_ {"##DungeonCanvas", ImVec2(0x200, 0x200)} private
Definition at line 115 of file dungeon_canvas_viewer.h.
Referenced by canvas(), canvas(), CanvasToRoomCoordinates(), DisplayObjectInfo(), DrawDungeonCanvas(), DrawObjectPositionOutlines(), DrawRoomBackgroundLayers(), IsWithinCanvasBounds(), and RenderSprites().
object_interaction_
DungeonObjectInteraction yaze::editor::DungeonCanvasViewer::object_interaction_ private
Definition at line 117 of file dungeon_canvas_viewer.h.
Referenced by ClearPreviewObject(), DrawDungeonCanvas(), object_interaction(), and SetPreviewObject().
rooms_
std::array<zelda3::Room, 0x128>* yaze::editor::DungeonCanvasViewer::rooms_ = nullptr private
Definition at line 120 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas(), DrawRoomBackgroundLayers(), LoadAndRenderRoomGraphics(), and SetRooms().
active_rooms_
ImVector<int> yaze::editor::DungeonCanvasViewer::active_rooms_ private
Definition at line 122 of file dungeon_canvas_viewer.h.
Referenced by set_active_rooms().
current_active_room_tab_
int yaze::editor::DungeonCanvasViewer::current_active_room_tab_ = 0 private
Definition at line 123 of file dungeon_canvas_viewer.h.
Referenced by set_current_active_room_tab().
object_interaction_enabled_
bool yaze::editor::DungeonCanvasViewer::object_interaction_enabled_ = true private
Definition at line 126 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas(), IsObjectInteractionEnabled(), and SetObjectInteractionEnabled().
room_layer_settings_
std::map<int, RoomLayerSettings> yaze::editor::DungeonCanvasViewer::room_layer_settings_ private
Definition at line 134 of file dungeon_canvas_viewer.h.
Referenced by GetBG2LayerType(), GetRoomLayerSettings(), IsBG1Visible(), and IsBG2Visible().
current_palette_group_id_
uint64_t yaze::editor::DungeonCanvasViewer::current_palette_group_id_ = 0 private
Definition at line 142 of file dungeon_canvas_viewer.h.
Referenced by LoadAndRenderRoomGraphics(), and set_current_palette_group_id().
current_palette_id_
uint64_t yaze::editor::DungeonCanvasViewer::current_palette_id_ = 0 private
Definition at line 143 of file dungeon_canvas_viewer.h.
Referenced by SetCurrentPaletteId().
current_palette_group_
gfx::PaletteGroup yaze::editor::DungeonCanvasViewer::current_palette_group_ private
Definition at line 144 of file dungeon_canvas_viewer.h.
Referenced by LoadAndRenderRoomGraphics(), and SetCurrentPaletteGroup().
object_render_cache_
std::vector<ObjectRenderCache> yaze::editor::DungeonCanvasViewer::object_render_cache_ private
Definition at line 154 of file dungeon_canvas_viewer.h.
last_palette_hash_
uint64_t yaze::editor::DungeonCanvasViewer::last_palette_hash_ = 0 private
Definition at line 155 of file dungeon_canvas_viewer.h.
show_room_debug_info_
bool yaze::editor::DungeonCanvasViewer::show_room_debug_info_ = false private
Definition at line 158 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas().
show_texture_debug_
bool yaze::editor::DungeonCanvasViewer::show_texture_debug_ = false private
Definition at line 159 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas().
show_object_bounds_
bool yaze::editor::DungeonCanvasViewer::show_object_bounds_ = false private
Definition at line 160 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas().
show_layer_info_
bool yaze::editor::DungeonCanvasViewer::show_layer_info_ = false private
Definition at line 161 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas().
layout_override_
int yaze::editor::DungeonCanvasViewer::layout_override_ = -1 private
Definition at line 162 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas().
object_outline_toggles_
ObjectOutlineToggles yaze::editor::DungeonCanvasViewer::object_outline_toggles_ private
Definition at line 173 of file dungeon_canvas_viewer.h.
Referenced by DrawDungeonCanvas(), and DrawObjectPositionOutlines().
The documentation for this class was generated from the following files:
src/app/editor/dungeon/dungeon_canvas_viewer.h
src/app/editor/dungeon/dungeon_canvas_viewer.cc