yaze: yaze::gui::anonymous_namespace{widget_id_registry.cc} Namespace Reference
yaze::gui::anonymous_namespace{widget_id_registry.cc} Namespace Reference
Functions
std::string ExtractWindowFromPath (absl::string_view path)
std::string ExtractLabelFromPath (absl::string_view path)
std::string FormatTimestampUTC (const absl::Time &timestamp)
WidgetIdRegistry::WidgetBounds BoundsFromImGui (const ImRect &rect)
Function Documentation
ExtractWindowFromPath()
std::string yaze::gui::anonymous_namespace{widget_id_registry.cc}::ExtractWindowFromPath (absl::string_view path)
Definition at line 95 of file widget_id_registry.cc.
References ExtractWindowFromPath().
Referenced by ExtractWindowFromPath().
ExtractLabelFromPath()
std::string yaze::gui::anonymous_namespace{widget_id_registry.cc}::ExtractLabelFromPath (absl::string_view path)
Definition at line 103 of file widget_id_registry.cc.
References ExtractLabelFromPath().
Referenced by ExtractLabelFromPath().
FormatTimestampUTC()
std::string yaze::gui::anonymous_namespace{widget_id_registry.cc}::FormatTimestampUTC (const absl::Time & timestamp)
Definition at line 115 of file widget_id_registry.cc.
References FormatTimestampUTC().
Referenced by FormatTimestampUTC().
BoundsFromImGui()
WidgetIdRegistry::WidgetBounds yaze::gui::anonymous_namespace{widget_id_registry.cc}::BoundsFromImGui (const ImRect & rect)
Definition at line 146 of file widget_id_registry.cc.
References BoundsFromImGui(), yaze::gui::WidgetIdRegistry::WidgetBounds::max_x, yaze::gui::WidgetIdRegistry::WidgetBounds::max_y, yaze::gui::WidgetIdRegistry::WidgetBounds::min_x, yaze::gui::WidgetIdRegistry::WidgetBounds::min_y, and yaze::gui::WidgetIdRegistry::WidgetBounds::valid.
Referenced by BoundsFromImGui().