yaze: yaze::cli::anonymous_namespace{overworld.cc} Namespace Reference
yaze::cli::anonymous_namespace{overworld.cc} Namespace Reference
Functions
absl::StatusOr< int > ParseNumeric (const std::string &value, int base=0)
absl::StatusOr< int > WorldFromString (const std::string &value)
absl::StatusOr< int > WorldFromMapId (int map_id)
std::string WorldName (int world)
Variables
constexpr absl::string_view kFindTileUsage
Function Documentation
ParseNumeric()
absl::StatusOr< int > yaze::cli::anonymous_namespace{overworld.cc}::ParseNumeric (const std::string & value, int base = 0)
Definition at line 123 of file overworld.cc.
References ParseNumeric().
Referenced by ParseNumeric().
WorldFromString()
absl::StatusOr< int > yaze::cli::anonymous_namespace{overworld.cc}::WorldFromString (const std::string & value)
Definition at line 138 of file overworld.cc.
References WorldFromString().
Referenced by WorldFromString().
WorldFromMapId()
absl::StatusOr< int > yaze::cli::anonymous_namespace{overworld.cc}::WorldFromMapId (int map_id)
Definition at line 153 of file overworld.cc.
References WorldFromMapId().
Referenced by WorldFromMapId().
WorldName()
std::string yaze::cli::anonymous_namespace{overworld.cc}::WorldName (int world)
Definition at line 170 of file overworld.cc.
References WorldName().
Referenced by WorldName().
Variable Documentation
kFindTileUsage
constexpr absl::string_view yaze::cli::anonymous_namespace{overworld.cc}::kFindTileUsage constexpr
Initial value:
=
    "Usage: overworld find-tile --tile <tile_id> [--map <map_id>] [--world <light|dark|special|0|1|2>] [--format <json|text>]"
Definition at line 120 of file overworld.cc.