yaze: yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc} Namespace Reference
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc} Namespace Reference
Classes
class Tile16ProposalGeneratorTest
Functions
TEST_F (Tile16ProposalGeneratorTest, ParseSetTileCommand_ValidCommand)
TEST_F (Tile16ProposalGeneratorTest, ParseSetTileCommand_InvalidFormat)
TEST_F (Tile16ProposalGeneratorTest, ParseSetTileCommand_WrongCommandType)
TEST_F (Tile16ProposalGeneratorTest, ParseSetAreaCommand_ValidCommand)
TEST_F (Tile16ProposalGeneratorTest, ParseSetAreaCommand_SingleTile)
TEST_F (Tile16ProposalGeneratorTest, ParseSetAreaCommand_LargeArea)
TEST_F (Tile16ProposalGeneratorTest, ParseSetAreaCommand_InvalidFormat)
TEST_F (Tile16ProposalGeneratorTest, ParseReplaceTileCommand_NoROM)
TEST_F (Tile16ProposalGeneratorTest, ParseReplaceTileCommand_InvalidFormat)
TEST_F (Tile16ProposalGeneratorTest, GenerateFromCommands_MultipleCommands)
TEST_F (Tile16ProposalGeneratorTest, GenerateFromCommands_EmptyCommands)
TEST_F (Tile16ProposalGeneratorTest, GenerateFromCommands_IgnoresComments)
TEST_F (Tile16ProposalGeneratorTest, Tile16Change_ToString)
TEST_F (Tile16ProposalGeneratorTest, Proposal_ToJsonAndFromJson)
Function Documentation
TEST_F() [1/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseSetTileCommand_ValidCommand)
Definition at line 32 of file tile16_proposal_generator_test.cc.
TEST_F() [2/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseSetTileCommand_InvalidFormat)
Definition at line 44 of file tile16_proposal_generator_test.cc.
TEST_F() [3/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseSetTileCommand_WrongCommandType)
Definition at line 54 of file tile16_proposal_generator_test.cc.
TEST_F() [4/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseSetAreaCommand_ValidCommand)
Definition at line 68 of file tile16_proposal_generator_test.cc.
TEST_F() [5/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseSetAreaCommand_SingleTile)
Definition at line 88 of file tile16_proposal_generator_test.cc.
TEST_F() [6/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseSetAreaCommand_LargeArea)
Definition at line 98 of file tile16_proposal_generator_test.cc.
TEST_F() [7/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseSetAreaCommand_InvalidFormat)
Definition at line 108 of file tile16_proposal_generator_test.cc.
TEST_F() [8/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseReplaceTileCommand_NoROM)
Definition at line 122 of file tile16_proposal_generator_test.cc.
TEST_F() [9/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , ParseReplaceTileCommand_InvalidFormat)
Definition at line 133 of file tile16_proposal_generator_test.cc.
TEST_F() [10/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , GenerateFromCommands_MultipleCommands)
Definition at line 147 of file tile16_proposal_generator_test.cc.
References yaze::cli::Tile16Proposal::PENDING.
TEST_F() [11/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , GenerateFromCommands_EmptyCommands)
Definition at line 163 of file tile16_proposal_generator_test.cc.
TEST_F() [12/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , GenerateFromCommands_IgnoresComments)
Definition at line 174 of file tile16_proposal_generator_test.cc.
TEST_F() [13/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , Tile16Change_ToString)
Definition at line 193 of file tile16_proposal_generator_test.cc.
References yaze::cli::Tile16Change::map_id, yaze::cli::Tile16Change::new_tile, yaze::cli::Tile16Change::old_tile, yaze::cli::Tile16Change::ToString(), yaze::cli::Tile16Change::x, and yaze::cli::Tile16Change::y.
TEST_F() [14/14]
yaze::cli::anonymous_namespace{tile16_proposal_generator_test.cc}::TEST_F (Tile16ProposalGeneratorTest , Proposal_ToJsonAndFromJson)
Definition at line 213 of file tile16_proposal_generator_test.cc.
References yaze::cli::Tile16Proposal::ai_service, yaze::cli::Tile16Proposal::changes, yaze::cli::Tile16Proposal::FromJson(), yaze::cli::Tile16Proposal::id, yaze::cli::Tile16Change::map_id, yaze::cli::Tile16Change::new_tile, yaze::cli::Tile16Change::old_tile, yaze::cli::Tile16Proposal::PENDING, yaze::cli::Tile16Proposal::prompt, yaze::cli::Tile16Proposal::reasoning, yaze::cli::Tile16Proposal::status, yaze::cli::Tile16Proposal::ToJson(), yaze::cli::Tile16Change::x, and yaze::cli::Tile16Change::y.