yaze: yaze::Rom Class Reference
yaze::Rom Class Reference
The Rom class is used to load, save, and modify Rom data.
#include <rom.h>
Classes
struct SaveSettings
struct WriteAction
Public Member Functions
absl::Status LoadFromFile (const std::string &filename, bool z3_load=true)
absl::Status LoadFromFile (const std::string &filename, const RomLoadOptions &options)
absl::Status LoadFromData (const std::vector< uint8_t > &data, bool z3_load=true)
absl::Status LoadFromData (const std::vector< uint8_t > &data, const RomLoadOptions &options)
absl::Status LoadZelda3 ()
absl::Status LoadZelda3 (const RomLoadOptions &options)
absl::Status LoadGfxGroups ()
absl::Status InitializeForTesting ()
absl::Status SaveGfxGroups ()
absl::Status SaveToFile (const SaveSettings &settings)
absl::Status SavePalette (int index, const std::string &group_name, gfx::SnesPalette &palette)
absl::Status SaveAllPalettes ()
void Expand (int size)
void Close ()
absl::StatusOr< uint8_t > ReadByte (int offset)
absl::StatusOr< uint16_t > ReadWord (int offset)
absl::StatusOr< uint32_t > ReadLong (int offset)
absl::StatusOr< std::vector< uint8_t > > ReadByteVector (uint32_t offset, uint32_t length) const
absl::StatusOr< gfx::Tile16 > ReadTile16 (uint32_t tile16_id)
absl::Status WriteTile16 (int tile16_id, const gfx::Tile16 &tile)
absl::Status WriteByte (int addr, uint8_t value)
absl::Status WriteWord (int addr, uint16_t value)
absl::Status WriteShort (int addr, uint16_t value)
absl::Status WriteLong (uint32_t addr, uint32_t value)
absl::Status WriteVector (int addr, std::vector< uint8_t > data)
absl::Status WriteColor (uint32_t address, const gfx::SnesColor &color)
template<typename... Args>
absl::Status WriteTransaction (Args... args)
template<typename T , typename... Args>
absl::Status ReadTransaction (T &var, int address, Args &&... args)
virtual absl::Status WriteHelper (const WriteAction &action)
template<typename T >
absl::Status ReadHelper (T &var, int address)
uint8_t & operator[] (unsigned long i)
bool is_loaded () const
bool dirty () const
void ClearDirty ()
auto title () const
auto size () const
auto data () const
auto mutable_data ()
auto begin ()
auto end ()
auto vector () const
auto filename () const
auto set_filename (std::string_view name)
auto short_name () const
auto graphics_buffer () const
auto mutable_graphics_buffer ()
auto palette_group () const
auto mutable_palette_group ()
auto dungeon_palette (int i)
auto mutable_dungeon_palette (int i)
core::ResourceLabelManager * resource_label ()
zelda3_version_pointers version_constants () const
Public Attributes
std::array< std::array< uint8_t, 8 >, kNumMainBlocksets > main_blockset_ids
std::array< std::array< uint8_t, 4 >, kNumRoomBlocksets > room_blockset_ids
std::array< std::array< uint8_t, 4 >, kNumSpritesets > spriteset_ids
std::array< std::array< uint8_t, 4 >, kNumPalettesets > paletteset_ids
Private Attributes
unsigned long size_ = 0
std::string title_ = "ROM not loaded"
std::string filename_ = ""
std::string short_name_ = ""
std::vector< uint8_t > rom_data_
std::vector< uint8_t > graphics_buffer_
core::ResourceLabelManager resource_label_manager_
gfx::PaletteGroupMap palette_groups_
zelda3_version version_ = zelda3_version::US
bool dirty_ = false
Detailed Description
The Rom class is used to load, save, and modify Rom data.
Definition at line 71 of file rom.h.
Member Function Documentation
LoadFromFile() [1/2]
absl::Status yaze::Rom::LoadFromFile (const std::string & filename, bool z3_load = true)
Definition at line 259 of file rom.cc.
References yaze::RomLoadOptions::AppDefaults(), filename(), LoadFromFile(), yaze::RomLoadOptions::RawDataOnly(), and vector().
Referenced by yaze::editor::ProposalDrawer::AcceptProposal(), yaze::cli::agent::CreateProposalFromAgentResponse(), ROMPatchUtility::CreateV3PatchedROM(), yaze::editor::GraphicsEditor::DrawFileImport(), yaze::editor::GraphicsEditor::DrawObjImport(), yaze::editor::GraphicsEditor::DrawPaletteControls(), yaze::editor::GraphicsEditor::DrawTilemapImport(), yaze::cli::agent::anonymous_namespace{general_commands.cc}::EnsureRomLoaded(), OverworldGoldenDataExtractor::ExtractAllData(), yaze::cli::agent::HandleAcceptCommand(), yaze::cli::agent::HandleRevertCommand(), yaze::editor::LoadExpandedMessages(), LoadFromFile(), yaze::editor::EditorManager::LoadRom(), yaze::cli::agent::anonymous_namespace{conversation_test.cc}::LoadRomForAgent(), yaze::cli::agent::anonymous_namespace{tool_commands.cc}::LoadRomFromFlag(), yaze::cli::message::anonymous_namespace{message.cc}::LoadRomFromFlag(), yaze::cli::agent::anonymous_namespace{tool_commands.cc}::LoadRomFromPathOrFlag(), main(), main(), yaze::editor::EditorManager::OpenProject(), yaze::editor::EditorManager::OpenRomOrProject(), yaze::cli::ApplyPatch::Run(), yaze::cli::AsarPatch::Run(), yaze::cli::Tile16Transfer::Run(), yaze::cli::GfxExport::Run(), yaze::cli::GfxImport::Run(), yaze::cli::PaletteExport::Run(), yaze::cli::PaletteImport::Run(), yaze::cli::DungeonExport::Run(), yaze::cli::DungeonListObjects::Run(), yaze::cli::RomInfo::Run(), yaze::cli::RomValidate::Run(), yaze::cli::RomDiff::Run(), yaze::cli::RomGenerateGolden::Run(), yaze::cli::ProjectBuild::Run(), yaze::cli::OverworldGetTile::Run(), yaze::cli::OverworldSetTile::Run(), yaze::cli::OverworldFindTile::Run(), yaze::cli::OverworldDescribeMap::Run(), yaze::cli::OverworldListWarps::Run(), yaze::cli::Open::Run(), yaze::cli::Backup::Run(), yaze::cli::ReadFromRom::Run(), yaze::cli::Expand::Run(), yaze::test::IntegratedTestSuite::RunRomBasicTest(), yaze::test::DungeonRoomTest::SetUp(), yaze::test::MessageRomTest::SetUp(), yaze::test::TEST_F(), and yaze::editor::MemoryEditorWithDiffChecker::Update().
LoadFromFile() [2/2]
absl::Status yaze::Rom::LoadFromFile (const std::string & filename, const RomLoadOptions & options)
Definition at line 265 of file rom.cc.
References filename(), filename_, yaze::RomLoadOptions::load_resource_labels, yaze::RomLoadOptions::load_zelda3_content, yaze::core::ResourceLabelManager::LoadLabels(), LoadZelda3(), resource_label_manager_, RETURN_IF_ERROR, rom_data_, short_name_, size_, yaze::RomLoadOptions::strip_header, and vector().
LoadFromData() [1/2]
absl::Status yaze::Rom::LoadFromData (const std::vector< uint8_t > & data, bool z3_load = true)
Definition at line 351 of file rom.cc.
References yaze::RomLoadOptions::AppDefaults(), data(), LoadFromData(), yaze::RomLoadOptions::RawDataOnly(), and vector().
Referenced by yaze::editor::OverworldEditor::ApplyZSCustomOverworldASM(), yaze::editor::GraphicsEditor::DrawClipboardImport(), yaze::test::anonymous_namespace{compression_test.cc}::ExpectCompressOk(), yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk(), yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressOk(), LoadFromData(), yaze::cli::AsarPatch::Run(), yaze::cli::ProjectBuild::Run(), yaze::test::MockRom::SetTestData(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::gfx::lc_lz2::ValidateCompressionResult(), and yaze::gfx::lc_lz2::ValidateCompressionResultV3().
LoadFromData() [2/2]
absl::Status yaze::Rom::LoadFromData (const std::vector< uint8_t > & data, const RomLoadOptions & options)
Definition at line 357 of file rom.cc.
References data(), yaze::RomLoadOptions::load_zelda3_content, LoadZelda3(), RETURN_IF_ERROR, rom_data_, size_, and yaze::RomLoadOptions::strip_header.
LoadZelda3() [1/2]
absl::Status yaze::Rom::LoadZelda3 ()
Definition at line 378 of file rom.cc.
References yaze::RomLoadOptions::AppDefaults(), and LoadZelda3().
Referenced by InitializeForTesting(), LoadFromData(), LoadFromFile(), and LoadZelda3().
LoadZelda3() [2/2]
absl::Status yaze::Rom::LoadZelda3 (const RomLoadOptions & options)
Definition at line 382 of file rom.cc.
References yaze::gfx::PaletteGroupMap::clear(), yaze::RomLoadOptions::expand_to_full_image, yaze::gfx::LoadAllPalettes(), LoadGfxGroups(), main_blockset_ids, palette_groups_, paletteset_ids, yaze::RomLoadOptions::populate_gfx_groups, yaze::RomLoadOptions::populate_metadata, yaze::RomLoadOptions::populate_palettes, RETURN_IF_ERROR, rom_data_, room_blockset_ids, size_, spriteset_ids, yaze::RomLoadOptions::strip_header, title_, vector(), and version_.
LoadGfxGroups()
absl::Status yaze::Rom::LoadGfxGroups ()
Definition at line 440 of file rom.cc.
References ASSIGN_OR_RETURN, zelda3_version_pointers::kDungeonPalettesGroups, yaze::kEntranceGfxGroup, yaze::kGfxGroupsPointer, yaze::kNumMainBlocksets, yaze::kNumPalettesets, yaze::kNumRoomBlocksets, yaze::kNumSpritesets, zelda3_version_pointers::kSpriteBlocksetPointer, main_blockset_ids, paletteset_ids, ReadWord(), rom_data_, room_blockset_ids, yaze::SnesToPc(), spriteset_ids, vector(), and version_constants().
Referenced by LoadZelda3().
InitializeForTesting()
absl::Status yaze::Rom::InitializeForTesting () inline
Definition at line 91 of file rom.h.
References yaze::RomLoadOptions::AppDefaults(), LoadZelda3(), and RETURN_IF_ERROR.
SaveGfxGroups()
absl::Status yaze::Rom::SaveGfxGroups ()
Definition at line 473 of file rom.cc.
References ASSIGN_OR_RETURN, zelda3_version_pointers::kDungeonPalettesGroups, yaze::kEntranceGfxGroup, yaze::kGfxGroupsPointer, yaze::kNumMainBlocksets, yaze::kNumPalettesets, yaze::kNumRoomBlocksets, yaze::kNumSpritesets, zelda3_version_pointers::kSpriteBlocksetPointer, main_blockset_ids, paletteset_ids, ReadWord(), rom_data_, room_blockset_ids, yaze::SnesToPc(), spriteset_ids, vector(), and version_constants().
Referenced by SaveToFile().
SaveToFile()
absl::Status yaze::Rom::SaveToFile (const SaveSettings & settings)
Definition at line 506 of file rom.cc.
References dirty_, filename(), filename_, yaze::core::FeatureFlags::get(), RETURN_IF_ERROR, rom_data_, SaveAllPalettes(), SaveGfxGroups(), and vector().
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::cli::agent::CreateProposalFromAgentResponse(), yaze::cli::RomSandboxManager::CreateSandbox(), ROMPatchUtility::CreateV3PatchedROM(), yaze::cli::agent::HandleAcceptCommand(), yaze::cli::agent::HandleCommitCommand(), yaze::cli::AsarPatch::Run(), yaze::cli::Tile16Transfer::Run(), yaze::cli::GfxImport::Run(), yaze::cli::PaletteImport::Run(), yaze::cli::ProjectBuild::Run(), yaze::cli::OverworldSetTile::Run(), yaze::cli::Backup::Run(), yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest(), yaze::test::E2ETestSuite::RunRomLoadSaveTest(), yaze::editor::MessageEditor::SaveExpandedMessages(), yaze::editor::EditorManager::SaveRom(), yaze::editor::EditorManager::SaveRomAs(), yaze::test::TestManager::TestRomSaveLoad(), yaze::editor::EditorManager::Update(), and yaze_save_rom().
SavePalette()
absl::Status yaze::Rom::SavePalette (int index, const std::string & group_name, gfx::SnesPalette & palette)
Definition at line 601 of file rom.cc.
References yaze::gfx::GetPaletteAddress(), yaze::gfx::SnesColor::is_modified(), RETURN_IF_ERROR, yaze::gfx::SnesColor::set_modified(), yaze::gfx::SnesPalette::size(), vector(), and WriteColor().
SaveAllPalettes()
absl::Status yaze::Rom::SaveAllPalettes ()
Definition at line 615 of file rom.cc.
References yaze::gfx::PaletteGroupMap::for_each(), palette_groups_, and RETURN_IF_ERROR.
Referenced by SaveToFile().
Expand()
void yaze::Rom::Expand (int size) inline
Definition at line 102 of file rom.h.
References rom_data_, size(), and size_.
Referenced by yaze::cli::agent::HandleAcceptCommand(), and yaze::cli::Expand::Run().
Close()
void yaze::Rom::Close () inline
Definition at line 107 of file rom.h.
References yaze::gfx::PaletteGroupMap::clear(), palette_groups_, rom_data_, and size_.
Referenced by yaze::editor::EditorManager::Initialize().
ReadByte()
absl::StatusOr< uint8_t > yaze::Rom::ReadByte (int offset)
Definition at line 628 of file rom.cc.
Referenced by yaze::test::ZSCustomOverworldTestSuite::DrawConfiguration(), yaze::zelda3::LoadDungeonMaps(), ReadHelper(), yaze::cli::ReadFromRom::Run(), yaze::test::E2ETestSuite::RunCorruptionDetectionTest(), yaze::test::E2ETestSuite::RunDataIntegrityTest(), yaze::test::ZSCustomOverworldTestSuite::RunDataIntegrityTest(), yaze::test::ZSCustomOverworldTestSuite::RunFeatureToggleTest(), yaze::test::E2ETestSuite::RunLargeScaleEditingTest(), yaze::test::RomDependentTestSuite::RunRomDataAccessTest(), yaze::test::E2ETestSuite::RunTransactionSystemTest(), yaze::test::ZSCustomOverworldTestSuite::RunV2UpgradeTest(), yaze::test::ZSCustomOverworldTestSuite::RunV3UpgradeTest(), yaze::test::ZSCustomOverworldTestSuite::RunVanillaBaselineTest(), yaze::test::TEST_F(), yaze::test::OverworldE2ETest::ValidateROMAgainstGoldenData(), yaze::test::ZSCustomOverworldTestSuite::ValidateVersionAddresses(), yaze::test::ZSCustomOverworldUpgradeTest::ValidateVersionAddresses(), OverworldGoldenDataExtractor::WriteASMVersionInfo(), yaze::Transaction::WriteByte(), OverworldGoldenDataExtractor::WriteMusicData(), OverworldGoldenDataExtractor::WriteOverlayData(), and OverworldGoldenDataExtractor::WritePaletteData().
ReadWord()
absl::StatusOr< uint16_t > yaze::Rom::ReadWord (int offset)
Definition at line 635 of file rom.cc.
Referenced by yaze::cli::agent::HandlePaletteAnalyze(), yaze::cli::agent::HandlePaletteGetColors(), yaze::cli::agent::HandlePaletteSetColor(), yaze::editor::DungeonRoomLoader::LoadAllRooms(), yaze::editor::DungeonCanvasViewer::LoadAndRenderRoomGraphics(), yaze::zelda3::LoadDungeonMaps(), yaze::zelda3::LoadDungeonMapTile16(), yaze::zelda3::LoadEntranceTileTypes(), LoadGfxGroups(), ReadHelper(), yaze::test::RomDependentTestSuite::RunRomDataAccessTest(), yaze::test::E2ETestSuite::RunTransactionSystemTest(), SaveGfxGroups(), OverworldGoldenDataExtractor::WriteBasicROMInfo(), yaze::Transaction::WriteColor(), and yaze::Transaction::WriteWord().
ReadLong()
absl::StatusOr< uint32_t > yaze::Rom::ReadLong (int offset)
Definition at line 643 of file rom.cc.
Referenced by yaze::Transaction::WriteLong().
ReadByteVector()
absl::StatusOr< std::vector< uint8_t > > yaze::Rom::ReadByteVector (uint32_t offset, uint32_t length) const
Definition at line 652 of file rom.cc.
Referenced by yaze::LoadLinkGraphics(), ReadHelper(), yaze::cli::ReadFromRom::Run(), yaze::test::TestManager::TestRomDataIntegrity(), and yaze::Transaction::WriteVector().
ReadTile16()
absl::StatusOr< gfx::Tile16 > yaze::Rom::ReadTile16 (uint32_t tile16_id)
Definition at line 664 of file rom.cc.
References ASSIGN_OR_RETURN, and yaze::kTile16Ptr.
Referenced by yaze::editor::Tile16Editor::GetCurrentTile16Data(), yaze::cli::Tile16Transfer::Run(), and yaze::editor::Tile16Editor::SetCurrentTile().
WriteTile16()
absl::Status yaze::Rom::WriteTile16 (int tile16_id, const gfx::Tile16 & tile)
Definition at line 682 of file rom.cc.
References yaze::kTile16Ptr, RETURN_IF_ERROR, yaze::gfx::Tile16::tile0_, yaze::gfx::Tile16::tile1_, yaze::gfx::Tile16::tile2_, and yaze::gfx::Tile16::tile3_.
Referenced by yaze::cli::Tile16Transfer::Run(), and yaze::editor::Tile16Editor::UpdateROMTile16Data().
WriteByte()
absl::Status yaze::Rom::WriteByte (int addr, uint8_t value)
Definition at line 695 of file rom.cc.
References LOG_DEBUG.
Referenced by ROMPatchUtility::ApplyV3Patch(), yaze::test::ZSCustomOverworldTestSuite::ApplyVersionPatch(), yaze::test::ZSCustomOverworldUpgradeTest::ApplyVersionPatch(), yaze::cli::agent::HandleHexWrite(), yaze::Transaction::Rollback(), yaze::test::E2ETestSuite::RunCorruptionDetectionTest(), yaze::test::ZSCustomOverworldTestSuite::RunFeatureToggleTest(), yaze::test::E2ETestSuite::RunLargeScaleEditingTest(), yaze::zelda3::RoomEntrance::Save(), yaze::zelda3::SaveDungeonMaps(), yaze::editor::MessageEditor::SaveExpandedMessages(), yaze::Transaction::WriteByte(), and WriteHelper().
WriteWord()
absl::Status yaze::Rom::WriteWord (int addr, uint16_t value)
Definition at line 707 of file rom.cc.
References LOG_DEBUG.
Referenced by yaze::cli::agent::HandlePaletteSetColor(), yaze::Transaction::Rollback(), yaze::zelda3::SaveDungeonMapTile16(), and yaze::Transaction::WriteWord().
WriteShort()
absl::Status yaze::Rom::WriteShort (int addr, uint16_t value)
Definition at line 720 of file rom.cc.
References LOG_DEBUG.
Referenced by yaze::zelda3::RoomEntrance::Save(), and WriteHelper().
WriteLong()
absl::Status yaze::Rom::WriteLong (uint32_t addr, uint32_t value)
Definition at line 733 of file rom.cc.
References LOG_DEBUG.
Referenced by yaze::Transaction::Rollback(), and yaze::Transaction::WriteLong().
WriteVector()
absl::Status yaze::Rom::WriteVector (int addr, std::vector< uint8_t > data)
Definition at line 747 of file rom.cc.
References LOG_DEBUG.
Referenced by yaze::editor::ProposalDrawer::AcceptProposal(), yaze::cli::agent::HandleAcceptCommand(), yaze::Transaction::Rollback(), yaze::zelda3::Room::SaveObjects(), WriteHelper(), and yaze::Transaction::WriteVector().
WriteColor()
absl::Status yaze::Rom::WriteColor (uint32_t address, const gfx::SnesColor & color)
Definition at line 762 of file rom.cc.
References LOG_DEBUG, and yaze::gfx::SnesColor::snes().
Referenced by SavePalette(), yaze::Transaction::WriteColor(), and WriteHelper().
WriteTransaction()
template<typename... Args> absl::Status yaze::Rom::WriteTransaction (Args... args) inline
Definition at line 129 of file rom.h.
References WriteHelper().
Referenced by yaze::test::TEST_F(), and yaze::test::TEST_F().
ReadTransaction()
template<typename T , typename... Args> absl::Status yaze::Rom::ReadTransaction (T & var, int address, Args &&... args) inline
Definition at line 137 of file rom.h.
References ReadTransaction(), and vector().
Referenced by ReadTransaction(), yaze::test::TEST_F(), and yaze::test::TEST_F().
WriteHelper()
virtual absl::Status yaze::Rom::WriteHelper (const WriteAction & action) inline virtual
Definition at line 156 of file rom.h.
References yaze::Rom::WriteAction::address, yaze::Rom::WriteAction::value, WriteByte(), WriteColor(), WriteShort(), and WriteVector().
Referenced by WriteTransaction().
ReadHelper()
template<typename T > absl::Status yaze::Rom::ReadHelper (T & var, int address) inline
Definition at line 178 of file rom.h.
References ASSIGN_OR_RETURN, ReadByte(), ReadByteVector(), ReadWord(), and vector().
operator[]()
uint8_t & yaze::Rom::operator[] (unsigned long i) inline
Definition at line 192 of file rom.h.
References rom_data_, and size_.
is_loaded()
bool yaze::Rom::is_loaded () const inline
Definition at line 197 of file rom.h.
References rom_data_.
Referenced by yaze::net::CollaborationService::ApplyDiff(), yaze::cli::Tile16ProposalGenerator::ApplyProposal(), yaze::net::CollaborationService::ApplyRomSync(), yaze::editor::EditorManager::BuildModernMenu(), yaze::net::RomVersionManager::ComputeRomHash(), yaze::zelda3::Room::CopyRoomGraphicsToBuffer(), yaze::cli::agent::CreateProposalFromAgentResponse(), yaze::cli::RomSandboxManager::CreateSandbox(), yaze::net::RomVersionManager::CreateSnapshot(), yaze::test::TestManager::CreateTestRomCopy(), yaze::net::RomVersionManager::DetectCorruption(), yaze::gui::PaletteEditorWidget::Draw(), yaze::editor::GraphicsEditor::DrawClipboardImport(), yaze::test::E2ETestSuite::DrawConfiguration(), yaze::test::RomDependentTestSuite::DrawConfiguration(), yaze::test::ZSCustomOverworldTestSuite::DrawConfiguration(), yaze::editor::DungeonCanvasViewer::DrawDungeonCanvas(), yaze::editor::DungeonEditor::DrawDungeonCanvas(), yaze::editor::DungeonRoomSelector::DrawEntranceSelector(), yaze::editor::DungeonEditorV2::DrawEntrancesListCard(), yaze::editor::EditorManager::DrawMenuBar(), yaze::zelda3::ObjectDrawer::DrawObject(), yaze::editor::DungeonObjectSelector::DrawObjectBrowser(), yaze::editor::OverworldEditor::DrawOverworldCanvas(), yaze::editor::EditorManager::DrawRomSelector(), yaze::editor::DungeonObjectSelector::DrawRoomGraphics(), yaze::editor::DungeonEditorV2::DrawRoomGraphicsCard(), yaze::editor::DungeonRoomSelector::DrawRoomSelector(), yaze::editor::DungeonEditorV2::DrawRoomsListCard(), yaze::editor::AgentEditor::DrawStatusPanel(), yaze::test::TestManager::DrawTestDashboard(), yaze::cli::agent::anonymous_namespace{general_commands.cc}::EnsureRomLoaded(), yaze::cli::ResourceContextBuilder::ExportToJson(), yaze::cli::ResourceContextBuilder::ExtractDungeonLabels(), yaze::cli::ResourceContextBuilder::ExtractEntranceLabels(), yaze::cli::ResourceContextBuilder::ExtractOverworldLabels(), yaze::cli::ResourceContextBuilder::ExtractRoomLabels(), yaze::cli::ResourceContextBuilder::ExtractSpriteLabels(), yaze::net::CollaborationService::GenerateDiff(), yaze::cli::Tile16ProposalGenerator::GenerateDiff(), yaze::net::RomVersionManager::GetCurrentHash(), yaze::cli::ResourceContextBuilder::GetLabels(), yaze::editor::DungeonEditor::GetRomStatus(), yaze::editor::DungeonEditorV2::GetRomStatus(), yaze::editor::OverworldEditor::GetRomStatus(), yaze::editor::GetRomStatusMessage(), yaze::cli::agent::HandleCommitCommand(), yaze::cli::agent::HandleDialogueListCommand(), yaze::cli::agent::HandleDialogueReadCommand(), yaze::cli::agent::HandleDialogueSearchCommand(), yaze::cli::agent::HandleDiffCommand(), yaze::cli::agent::HandleDungeonDescribeRoomCommand(), yaze::cli::agent::HandleDungeonListSpritesCommand(), yaze::cli::agent::HandleHexRead(), yaze::cli::agent::HandleHexSearch(), yaze::cli::agent::HandleHexWrite(), yaze::cli::message::HandleMessageListCommand(), yaze::cli::message::HandleMessageReadCommand(), yaze::cli::message::HandleMessageSearchCommand(), yaze::cli::message::HandleMessageStatsCommand(), yaze::cli::agent::HandleMusicInfoCommand(), yaze::cli::agent::HandleMusicListCommand(), yaze::cli::agent::HandleMusicTracksCommand(), yaze::cli::agent::HandleOverworldDescribeMapCommand(), yaze::cli::agent::HandleOverworldFindTileCommand(), yaze::cli::agent::HandleOverworldGetEntranceCommand(), yaze::cli::agent::HandleOverworldListSpritesCommand(), yaze::cli::agent::HandleOverworldListWarpsCommand(), yaze::cli::agent::HandleOverworldTileStatsCommand(), yaze::cli::agent::HandlePaletteAnalyze(), yaze::cli::agent::HandlePaletteGetColors(), yaze::cli::agent::HandlePaletteSetColor(), yaze::cli::agent::HandleResourceListCommand(), yaze::cli::agent::HandleResourceSearchCommand(), yaze::cli::agent::HandleRevertCommand(), yaze::cli::agent::HandleSpriteListCommand(), yaze::cli::agent::HandleSpritePaletteCommand(), yaze::cli::agent::HandleSpritePropertiesCommand(), yaze::net::CollaborationService::HostSession(), yaze::net::CollaborationService::Initialize(), yaze::editor::DungeonEditor::IsRomLoaded(), yaze::editor::DungeonEditorV2::IsRomLoaded(), yaze::editor::OverworldEditor::IsRomLoaded(), yaze::editor::IsRomReadyForEditing(), yaze::test::MockRom::IsValid(), yaze::net::CollaborationService::JoinSession(), yaze::editor::DungeonEditorV2::Load(), yaze::editor::DungeonEditor::Load(), yaze::editor::OverworldEditor::Load(), yaze::editor::DungeonRoomLoader::LoadAllRooms(), yaze::editor::DungeonCanvasViewer::LoadAndRenderRoomGraphics(), yaze::editor::DungeonRoomLoader::LoadAndRenderRoomGraphics(), yaze::zelda3::Room::LoadAnimatedGraphics(), yaze::cli::agent::anonymous_namespace{conversation_test.cc}::LoadRomForAgent(), yaze::editor::DungeonRoomLoader::LoadRoom(), yaze::editor::DungeonRoomLoader::LoadRoomEntrances(), main(), yaze::cli::Tile16ProposalGenerator::ParseReplaceTileCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetAreaCommand(), yaze::cli::Tile16ProposalGenerator::ParseSetTileCommand(), yaze::test::TestManager::RefreshCurrentRom(), yaze::editor::DungeonRenderer::RefreshGraphics(), yaze::editor::DungeonRoomLoader::ReloadAllRoomGraphics(), yaze::gui::DungeonObjectEmulatorPreview::Render(), yaze::editor::DungeonCanvasViewer::RenderObjectInCanvas(), yaze::editor::DungeonRenderer::RenderObjectInCanvas(), yaze::zelda3::Room::RenderObjectsToBackground(), yaze::net::RomVersionManager::RestoreSnapshot(), yaze::cli::AsarPatch::Run(), yaze::cli::GfxExport::Run(), yaze::cli::GfxImport::Run(), yaze::cli::PaletteExport::Run(), yaze::cli::PaletteImport::Run(), yaze::cli::DungeonExport::Run(), yaze::cli::DungeonListObjects::Run(), yaze::cli::RomInfo::Run(), yaze::cli::RomValidate::Run(), yaze::cli::OverworldGetTile::Run(), yaze::cli::OverworldSetTile::Run(), yaze::cli::OverworldFindTile::Run(), yaze::cli::OverworldDescribeMap::Run(), yaze::cli::OverworldListWarps::Run(), yaze::emu::Emulator::Run(), yaze::test::IntegratedTestSuite::RunRomBasicTest(), yaze::test::E2ETestSuite::RunTests(), yaze::test::RomDependentTestSuite::RunTests(), yaze::test::ZSCustomOverworldTestSuite::RunTests(), yaze::editor::DungeonEditorV2::Save(), yaze::cli::agent::ConversationalAgentService::SendMessage(), yaze::test::TestManager::SetCurrentRom(), yaze::editor::AgentChatWidget::SetRomContext(), yaze::net::CollaborationService::SubmitChangesAsProposal(), yaze::test::TestManager::TestRomDataIntegrity(), yaze::test::TestManager::TestRomSaveLoad(), yaze::test::TestManager::TestRomWithCopy(), yaze::gui::DungeonObjectEmulatorPreview::TriggerEmulatedRender(), yaze::editor::EditorManager::Update(), yaze::editor::OverworldEditor::Update(), yaze::editor::DungeonEditor::UpdateObjectEditor(), yaze::editor::DungeonCanvasViewer::UpdateRoomBackgroundLayers(), and yaze::net::RomVersionManager::ValidateRomIntegrity().
dirty()
bool yaze::Rom::dirty () const inline
Definition at line 198 of file rom.h.
References dirty_.
Referenced by yaze::editor::EditorManager::DrawMenuBar(), yaze::test::TestManager::DrawTestDashboard(), yaze::test::TestManager::RefreshCurrentRom(), yaze::test::TestManager::ShowRomComparisonResults(), and yaze::editor::EditorManager::Update().
ClearDirty()
void yaze::Rom::ClearDirty () inline
Definition at line 199 of file rom.h.
References dirty_.
title()
auto yaze::Rom::title () const inline
Definition at line 200 of file rom.h.
References title_.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::cli::tui::ChatTUI::ChatTUI(), yaze::cli::EnhancedStatusPanel::CollectRomInfo(), yaze::cli::UnifiedLayout::CreateStatusPanel(), yaze::test::TestManager::CreateTestRomCopy(), yaze::test::E2ETestSuite::DrawConfiguration(), yaze::test::RomDependentTestSuite::DrawConfiguration(), yaze::test::ZSCustomOverworldTestSuite::DrawConfiguration(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::AgentEditor::DrawStatusPanel(), yaze::test::TestManager::DrawTestDashboard(), yaze::editor::EditorManager::RomSession::GetDisplayName(), yaze::editor::DungeonEditor::GetRomStatus(), yaze::editor::DungeonEditorV2::GetRomStatus(), yaze::editor::OverworldEditor::GetRomStatus(), yaze::editor::GetRomStatusMessage(), yaze::cli::agent::HandleTestConversationCommand(), yaze::editor::IsRomReadyForEditing(), yaze::editor::EditorManager::LoadRom(), yaze::editor::EditorManager::OpenProject(), yaze::cli::EnhancedChatComponent::ProcessMessage(), yaze::test::TestManager::RefreshCurrentRom(), yaze::cli::RomInfo::Run(), yaze::cli::RomValidate::Run(), yaze::cli::Open::Run(), yaze::test::RomDependentTestSuite::RunComprehensiveSaveTest(), yaze::test::IntegratedTestSuite::RunRomBasicTest(), yaze::test::RomDependentTestSuite::RunRomHeaderValidationTest(), yaze::test::RomDependentTestSuite::RunTests(), yaze::test::RomDependentTestSuite::RunTile16EditorTest(), yaze::test::TestManager::SetCurrentRom(), yaze::cli::tui::ChatTUI::SetRomContext(), yaze::cli::UnifiedLayout::SetRomContext(), yaze::editor::EditorManager::SwitchToSession(), yaze::test::TestManager::TestRomDataIntegrity(), yaze::test::TestManager::TestRomSaveLoad(), yaze::cli::UnifiedLayout::UnifiedLayout(), yaze::test::OverworldE2ETest::ValidateROMAgainstGoldenData(), and OverworldGoldenDataExtractor::WriteBasicROMInfo().
size()
auto yaze::Rom::size () const inline
Definition at line 201 of file rom.h.
References size_.
Referenced by yaze::cli::tui::ChatTUI::ChatTUI(), yaze::cli::EnhancedStatusPanel::CollectRomInfo(), yaze::net::RomVersionManager::ComputeRomHash(), yaze::cli::UnifiedLayout::CreateHexViewerPanel(), yaze::net::RomVersionManager::CreateSnapshot(), yaze::cli::UnifiedLayout::CreateStatusPanel(), yaze::net::RomVersionManager::DetectCorruption(), yaze::test::E2ETestSuite::DrawConfiguration(), yaze::test::RomDependentTestSuite::DrawConfiguration(), yaze::editor::GraphicsEditor::DrawMemoryEditor(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::EditorManager::DrawRomSelector(), yaze::test::TestManager::DrawTestDashboard(), yaze::zelda3::RoomObject::EnsureTilesLoaded(), Expand(), yaze::net::RomVersionManager::GetCurrentHash(), yaze::cli::agent::HandleAcceptCommand(), yaze::cli::agent::HandleHexRead(), yaze::cli::agent::HandleHexSearch(), yaze::cli::agent::HandleHexWrite(), yaze::cli::agent::HandlePaletteGetColors(), yaze::cli::agent::HandlePaletteSetColor(), yaze::test::MockRom::IsValid(), yaze::zelda3::RoomLayout::LoadLayout(), yaze::zelda3::RoomLayout::LoadLayoutData(), yaze::zelda3::Room::LoadObjects(), yaze::editor::Tile16Editor::LoadTile8(), yaze::zelda3::OverworldMap::LoadVanillaOverlayData(), main(), yaze::zelda3::Room::ParseObjectsFromLocation(), yaze::zelda3::ObjectParser::ParseSubtype1(), yaze::zelda3::ObjectParser::ParseSubtype2(), yaze::zelda3::ObjectParser::ParseSubtype3(), yaze::cli::EnhancedChatComponent::ProcessMessage(), yaze::zelda3::ObjectParser::ReadTileData(), yaze::test::TestManager::RefreshCurrentRom(), yaze::net::RomVersionManager::RestoreSnapshot(), yaze::cli::ApplyPatch::Run(), yaze::cli::RomInfo::Run(), yaze::cli::RomValidate::Run(), yaze::cli::RomDiff::Run(), yaze::cli::RomGenerateGolden::Run(), yaze::cli::Open::Run(), yaze::test::IntegratedTestSuite::RunRomBasicTest(), yaze::test::RomDependentTestSuite::RunRomHeaderValidationTest(), yaze::test::E2ETestSuite::RunRomLoadSaveTest(), yaze::test::RomDependentTestSuite::RunTests(), yaze::zelda3::Room::SaveObjects(), yaze::editor::AgentChatWidget::SetRomContext(), yaze::cli::tui::ChatTUI::SetRomContext(), yaze::test::TestManager::ShowRomComparisonResults(), yaze::test::TEST_F(), yaze::test::TestManager::TestRomDataIntegrity(), yaze::editor::MemoryEditorWithDiffChecker::Update(), yaze::gfx::lc_lz2::ValidateCompressionResult(), yaze::gfx::lc_lz2::ValidateCompressionResultV3(), yaze::zelda3::ObjectRenderer::ObjectParser::ValidateROMAddress(), yaze::test::OverworldE2ETest::ValidateROMAgainstGoldenData(), yaze::net::RomVersionManager::ValidateRomIntegrity(), and OverworldGoldenDataExtractor::WriteBasicROMInfo().
data()
auto yaze::Rom::data () const inline
Definition at line 202 of file rom.h.
References rom_data_.
Referenced by yaze::editor::BuildDictionaryEntries(), yaze::zelda3::CalculateRoomSize(), yaze::net::RomVersionManager::ComputeRomHash(), yaze::net::RomVersionManager::CreateSnapshot(), yaze::editor::GraphicsEditor::DecompressImportData(), yaze::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::net::RomVersionManager::DetectCorruption(), yaze::test::TestManager::DrawTestDashboard(), yaze::editor::GraphicsEditor::DrawTilemapImport(), yaze::zelda3::RoomObject::EnsureTilesLoaded(), yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressBytesOk(), yaze::test::anonymous_namespace{compression_test.cc}::ExpectDecompressOk(), yaze::net::RomVersionManager::GetCurrentHash(), yaze::cli::agent::HandleHexRead(), yaze::cli::agent::HandleHexSearch(), yaze::editor::MessageEditor::Initialize(), yaze::Load2BppGraphics(), yaze::LoadAllGraphicsData(), yaze::zelda3::LoadDungeonMaps(), yaze::zelda3::LoadDungeonMapTile16(), yaze::LoadFontGraphics(), LoadFromData(), LoadFromData(), yaze::cli::message::anonymous_namespace{message.cc}::LoadMessages(), yaze::zelda3::LoadRoomFromRom(), yaze::zelda3::ObjectParser::ParseSubtype1(), yaze::zelda3::ObjectRenderer::ObjectParser::ParseSubtype1(), yaze::zelda3::ObjectParser::ParseSubtype2(), yaze::zelda3::ObjectRenderer::ObjectParser::ParseSubtype2(), yaze::zelda3::ObjectParser::ParseSubtype3(), yaze::zelda3::ObjectRenderer::ObjectParser::ParseSubtype3(), yaze::zelda3::ObjectParser::ReadTileData(), yaze::zelda3::ObjectRenderer::ObjectParser::ReadTileData(), yaze::zelda3::RoomEntrance::RoomEntrance(), yaze::SaveAllGraphicsData(), yaze::zelda3::SaveDungeonMapTile16(), yaze::test::MockRom::SetObjectData(), yaze::test::MockRom::SetRoomData(), yaze::test::MockRom::SetTestData(), yaze::gui::DungeonObjectEmulatorPreview::TriggerEmulatedRender(), yaze::gfx::lc_lz2::ValidateCompressionResult(), and yaze::gfx::lc_lz2::ValidateCompressionResultV3().
mutable_data()
auto yaze::Rom::mutable_data () inline
Definition at line 203 of file rom.h.
References rom_data_.
Referenced by yaze::editor::GraphicsEditor::DrawMemoryEditor(), yaze::editor::GraphicsEditor::DrawPaletteControls(), yaze::zelda3::music::Tracker::GetSpcAddr(), yaze::cli::agent::HandleDialogueListCommand(), yaze::cli::agent::HandleDialogueReadCommand(), yaze::cli::agent::HandleDialogueSearchCommand(), yaze::editor::LoadExpandedMessages(), yaze::net::RomVersionManager::RestoreSnapshot(), yaze::editor::MessageEditor::SaveExpandedMessages(), and yaze::zelda3::music::Tracker::WriteSpcData().
begin()
auto yaze::Rom::begin () inline
Definition at line 204 of file rom.h.
References rom_data_.
Referenced by yaze::SaveAllGraphicsData(), yaze::gfx::lc_lz2::ValidateCompressionResult(), and yaze::gfx::lc_lz2::ValidateCompressionResultV3().
end()
auto yaze::Rom::end () inline
Definition at line 205 of file rom.h.
References rom_data_.
vector()
auto yaze::Rom::vector () const inline
Definition at line 206 of file rom.h.
References rom_data_.
Referenced by yaze::editor::ProposalDrawer::AcceptProposal(), yaze::editor::OverworldEditor::ApplyZSCustomOverworldASM(), yaze::cli::EnhancedStatusPanel::CollectRomInfo(), yaze::cli::UnifiedLayout::CreateHexViewerPanel(), yaze::test::TestManager::CreateTestRomCopy(), yaze::test::anonymous_namespace{compression_test.cc}::ExpectCompressOk(), yaze::test::MockRom::GetObjectData(), yaze::test::MockRom::GetRoomData(), yaze::cli::agent::HandleAcceptCommand(), yaze::gui::DungeonObjectEmulatorPreview::Initialize(), yaze::zelda3::MockRom::InitializeMockData(), yaze::zelda3::MockRom::InitializeMockPalettes(), LoadFromData(), LoadFromFile(), LoadFromFile(), LoadGfxGroups(), yaze::zelda3::RoomLayout::LoadLayout(), yaze::zelda3::RoomLayout::LoadLayoutData(), LoadZelda3(), main(), ReadHelper(), ReadTransaction(), yaze::zelda3::MockRom::ReadWord(), yaze::cli::ApplyPatch::Run(), yaze::cli::AsarPatch::Run(), yaze::cli::RomDiff::Run(), yaze::cli::RomGenerateGolden::Run(), yaze::cli::ProjectBuild::Run(), yaze::emu::Emulator::Run(), yaze::editor::MessageEditor::Save(), SaveGfxGroups(), SavePalette(), and SaveToFile().
filename()
auto yaze::Rom::filename () const inline
Definition at line 207 of file rom.h.
References filename_.
Referenced by yaze::editor::EditorManager::BuildModernMenu(), yaze::cli::RomSandboxManager::CreateSandbox(), yaze::test::RomDependentTestSuite::DrawConfiguration(), yaze::editor::EditorManager::DrawMenuBar(), yaze::test::TestManager::DrawTestDashboard(), yaze::cli::agent::HandleAcceptCommand(), yaze::cli::agent::HandleDialogueListCommand(), yaze::cli::agent::HandleDialogueReadCommand(), yaze::cli::agent::HandleDialogueSearchCommand(), yaze::cli::agent::HandleDiffCommand(), yaze::cli::agent::HandleMusicInfoCommand(), yaze::cli::agent::HandleMusicListCommand(), yaze::cli::agent::HandleRevertCommand(), yaze::cli::agent::HandleSpriteListCommand(), yaze::cli::agent::HandleSpritePaletteCommand(), yaze::cli::agent::HandleSpritePropertiesCommand(), LoadFromFile(), LoadFromFile(), yaze::editor::EditorManager::RomSession::RomSession(), yaze::cli::AsarPatch::Run(), yaze::cli::GfxImport::Run(), yaze::cli::PaletteImport::Run(), SaveToFile(), and yaze::editor::MemoryEditorWithDiffChecker::Update().
set_filename()
auto yaze::Rom::set_filename (std::string_view name) inline
Definition at line 208 of file rom.h.
References filename_.
short_name()
auto yaze::Rom::short_name () const inline
Definition at line 209 of file rom.h.
References short_name_.
Referenced by yaze::editor::EditorManager::DrawRomSelector().
graphics_buffer()
auto yaze::Rom::graphics_buffer () const inline
Definition at line 210 of file rom.h.
References graphics_buffer_.
Referenced by yaze::zelda3::OverworldMap::BuildTileset(), yaze::editor::DungeonEditor::DrawCanvasAndPropertiesPanel(), and yaze::zelda3::OverworldMap::ProcessGraphicsBuffer().
mutable_graphics_buffer()
auto yaze::Rom::mutable_graphics_buffer () inline
Definition at line 211 of file rom.h.
References graphics_buffer_.
Referenced by yaze::LoadAllGraphicsData().
palette_group()
auto yaze::Rom::palette_group () const inline
Definition at line 212 of file rom.h.
References palette_groups_.
Referenced by yaze::editor::GraphicsEditor::DecompressImportData(), yaze::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::editor::DungeonEditor::DrawCanvasAndPropertiesPanel(), yaze::editor::DungeonObjectSelector::DrawObjectAssetBrowser(), yaze::editor::DungeonObjectSelector::DrawObjectBrowser(), yaze::editor::MessageEditor::Initialize(), yaze::editor::DungeonEditorV2::Load(), yaze::editor::DungeonEditor::Load(), yaze::editor::GraphicsEditor::Load(), yaze::editor::DungeonRoomLoader::LoadAllRooms(), yaze::editor::DungeonCanvasViewer::LoadAndRenderRoomGraphics(), yaze::LoadLinkGraphics(), yaze::zelda3::OverworldMap::LoadPalette(), yaze::gui::CanvasUtils::LoadROMPaletteGroups(), yaze::gui::PaletteWidget::LoadROMPalettes(), yaze::editor::Tile16Editor::PreviewPaletteChange(), yaze::editor::Tile16Editor::RefreshAllPalettes(), yaze::editor::DungeonEditor::RefreshGraphics(), yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM(), yaze::cli::PaletteExport::Run(), yaze::cli::PaletteImport::Run(), yaze::test::RomDependentTestSuite::RunTile16EditorTest(), yaze::zelda3::palette_internal::SetColorsPalette(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::gui::DungeonObjectEmulatorPreview::TriggerEmulatedRender(), yaze::editor::DungeonEditor::UpdateDungeonRoomView(), yaze::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::editor::DungeonCanvasViewer::UpdateRoomBackgroundLayers(), yaze::editor::Tile16Editor::UpdateTile8Palette(), and yaze_get_color_from_paletteset().
mutable_palette_group()
auto yaze::Rom::mutable_palette_group () inline
Definition at line 213 of file rom.h.
References palette_groups_.
Referenced by yaze::gui::PaletteEditorWidget::DrawColorGrid(), yaze::gui::PaletteEditorWidget::DrawColorPicker(), yaze::editor::PaletteEditor::DrawPaletteGroup(), yaze::gui::PaletteEditorWidget::DrawPaletteSelector(), and yaze::editor::GfxGroupEditor::DrawPaletteViewer().
dungeon_palette()
auto yaze::Rom::dungeon_palette (int i) inline
Definition at line 214 of file rom.h.
References yaze::gfx::PaletteGroupMap::dungeon_main, and palette_groups_.
mutable_dungeon_palette()
auto yaze::Rom::mutable_dungeon_palette (int i) inline
Definition at line 215 of file rom.h.
References yaze::gfx::PaletteGroupMap::dungeon_main, yaze::gfx::PaletteGroup::mutable_palette(), and palette_groups_.
Referenced by yaze::editor::ScreenEditor::LoadBinaryGfx(), yaze::zelda3::LoadDungeonMapGfxFromBinary(), and yaze::zelda3::LoadDungeonMapTile16().
resource_label()
core::ResourceLabelManager * yaze::Rom::resource_label () inline
Definition at line 219 of file rom.h.
References resource_label_manager_.
Referenced by yaze::editor::ScreenEditor::DrawDungeonMapsEditor(), yaze::editor::DungeonRoomSelector::DrawEntranceSelector(), yaze::editor::EditorManager::DrawMenuBar(), yaze::editor::PaletteEditor::DrawPaletteGroup(), yaze::editor::GfxGroupEditor::DrawPaletteViewer(), yaze::editor::DungeonRoomSelector::DrawRoomSelector(), yaze::editor::GfxGroupEditor::DrawRoomsetViewer(), yaze::editor::SpriteEditor::DrawSpritesList(), yaze::cli::ResourceContextBuilder::ExportToJson(), yaze::cli::ResourceContextBuilder::ExtractDungeonLabels(), yaze::cli::ResourceContextBuilder::ExtractEntranceLabels(), yaze::cli::ResourceContextBuilder::ExtractOverworldLabels(), yaze::cli::ResourceContextBuilder::ExtractRoomLabels(), yaze::cli::ResourceContextBuilder::ExtractSpriteLabels(), yaze::cli::ResourceContextBuilder::GetLabels(), yaze::cli::agent::HandleResourceListCommand(), yaze::cli::agent::HandleResourceSearchCommand(), yaze::cli::agent::HandleTestConversationCommand(), yaze::editor::PaletteEditor::Load(), yaze::editor::EditorManager::OpenProject(), yaze::editor::AgentChatWidget::SetRomContext(), yaze::cli::agent::anonymous_namespace{general_commands.cc}::TryLoadProjectAndLabels(), yaze::editor::GfxGroupEditor::Update(), and yaze::editor::OverworldEditor::UpdateUsageStats().
version_constants()
zelda3_version_pointers yaze::Rom::version_constants () const inline
Definition at line 220 of file rom.h.
References version_.
Referenced by yaze::zelda3::OverworldMap::GetPalette(), yaze::Load2BppGraphics(), yaze::LoadAllGraphicsData(), yaze::zelda3::OverworldMap::LoadAreaGraphicsBlocksets(), yaze::zelda3::OverworldMap::LoadCustomOverworldData(), LoadGfxGroups(), yaze::zelda3::OverworldMap::LoadMainBlocksets(), yaze::zelda3::OverworldMap::LoadPalette(), yaze::zelda3::OverworldMap::LoadSpritesBlocksets(), yaze::SaveAllGraphicsData(), SaveGfxGroups(), and yaze::zelda3::OverworldMap::SetupCustomTileset().
Member Data Documentation
main_blockset_ids
std::array<std::array<uint8_t, 8>, kNumMainBlocksets> yaze::Rom::main_blockset_ids
Definition at line 224 of file rom.h.
Referenced by yaze::editor::GfxGroupEditor::DrawBlocksetViewer(), LoadGfxGroups(), LoadZelda3(), and SaveGfxGroups().
room_blockset_ids
std::array<std::array<uint8_t, 4>, kNumRoomBlocksets> yaze::Rom::room_blockset_ids
Definition at line 225 of file rom.h.
Referenced by yaze::editor::GfxGroupEditor::DrawRoomsetViewer(), LoadGfxGroups(), LoadZelda3(), and SaveGfxGroups().
spriteset_ids
std::array<std::array<uint8_t, 4>, kNumSpritesets> yaze::Rom::spriteset_ids
Definition at line 226 of file rom.h.
Referenced by yaze::editor::GfxGroupEditor::DrawSpritesetViewer(), LoadGfxGroups(), LoadZelda3(), and SaveGfxGroups().
paletteset_ids
std::array<std::array<uint8_t, 4>, kNumPalettesets> yaze::Rom::paletteset_ids
Definition at line 227 of file rom.h.
Referenced by yaze::editor::GfxGroupEditor::DrawPaletteViewer(), yaze::editor::DungeonRoomLoader::LoadAllRooms(), yaze::editor::DungeonCanvasViewer::LoadAndRenderRoomGraphics(), LoadGfxGroups(), LoadZelda3(), and SaveGfxGroups().
size_
unsigned long yaze::Rom::size_ = 0 private
Definition at line 231 of file rom.h.
Referenced by Close(), Expand(), LoadFromData(), LoadFromFile(), LoadZelda3(), operator[](), and size().
title_
std::string yaze::Rom::title_ = "ROM not loaded" private
Definition at line 234 of file rom.h.
Referenced by LoadZelda3(), and title().
filename_
std::string yaze::Rom::filename_ = "" private
Definition at line 237 of file rom.h.
Referenced by filename(), LoadFromFile(), SaveToFile(), and set_filename().
short_name_
std::string yaze::Rom::short_name_ = "" private
Definition at line 240 of file rom.h.
Referenced by LoadFromFile(), and short_name().
rom_data_
std::vector<uint8_t> yaze::Rom::rom_data_ private
Definition at line 243 of file rom.h.
Referenced by begin(), Close(), data(), end(), Expand(), is_loaded(), LoadFromData(), LoadFromFile(), LoadGfxGroups(), LoadZelda3(), mutable_data(), operator[](), SaveGfxGroups(), SaveToFile(), and vector().
graphics_buffer_
std::vector<uint8_t> yaze::Rom::graphics_buffer_ private
Definition at line 246 of file rom.h.
Referenced by graphics_buffer(), and mutable_graphics_buffer().
resource_label_manager_
core::ResourceLabelManager yaze::Rom::resource_label_manager_ private
Definition at line 249 of file rom.h.
Referenced by LoadFromFile(), and resource_label().
palette_groups_
gfx::PaletteGroupMap yaze::Rom::palette_groups_ private
Definition at line 252 of file rom.h.
Referenced by Close(), dungeon_palette(), LoadZelda3(), mutable_dungeon_palette(), mutable_palette_group(), palette_group(), and SaveAllPalettes().
version_
zelda3_version yaze::Rom::version_ = zelda3_version::US private
Definition at line 255 of file rom.h.
Referenced by LoadZelda3(), and version_constants().
dirty_
bool yaze::Rom::dirty_ = false private
Definition at line 258 of file rom.h.
Referenced by ClearDirty(), dirty(), and SaveToFile().
The documentation for this class was generated from the following files:
src/app/rom.h
src/app/rom.cc