yaze: yaze::test::TestRomManager::BoundRomTest Class Reference
yaze::test::TestRomManager::BoundRomTest Class Reference
#include <test_utils.h>
Protected Member Functions
void SetUp () override
void TearDown () override
Rom * rom ()
const Rom * rom () const
std::string GetBoundRomPath () const
Private Member Functions
void EnsureRomLoaded ()
Private Attributes
std::unique_ptr< Rom > rom_instance_
bool rom_loaded_ = false
Detailed Description
Definition at line 135 of file test_utils.h.
Member Function Documentation
SetUp()
void yaze::test::TestRomManager::BoundRomTest::SetUp () inline override protected
Definition at line 137 of file test_utils.h.
References rom_instance_.
TearDown()
void yaze::test::TestRomManager::BoundRomTest::TearDown () inline override protected
Definition at line 141 of file test_utils.h.
References rom_instance_, and rom_loaded_.
rom() [1/2]
Rom * yaze::test::TestRomManager::BoundRomTest::rom () inline protected
Definition at line 146 of file test_utils.h.
References EnsureRomLoaded(), and rom_instance_.
Referenced by yaze::test::DungeonObjectRenderingTests::CreateBossRoomScenario(), yaze::test::DungeonObjectRenderingTests::CreateComplexRoomScenario(), yaze::test::DungeonObjectRenderingTests::CreateEmptyRoomScenario(), yaze::test::DungeonObjectRenderingTests::CreateLargeRoomScenario(), yaze::test::DungeonObjectRenderingTests::CreateMultiObjectScenario(), yaze::test::DungeonObjectRenderingTests::CreatePuzzleRoomScenario(), yaze::test::DungeonObjectRenderingE2ETests::SetUp(), and yaze::test::DungeonObjectRenderingTests::SetUp().
rom() [2/2]
const Rom * yaze::test::TestRomManager::BoundRomTest::rom () const inline protected
Definition at line 147 of file test_utils.h.
References rom_instance_.
GetBoundRomPath()
std::string yaze::test::TestRomManager::BoundRomTest::GetBoundRomPath () const inline protected
Definition at line 149 of file test_utils.h.
References yaze::test::TestRomManager::GetTestRomPath().
EnsureRomLoaded()
void yaze::test::TestRomManager::BoundRomTest::EnsureRomLoaded () inline private
Definition at line 155 of file test_utils.h.
References yaze::test::TestRomManager::GetTestRomPath(), rom_instance_, and rom_loaded_.
Referenced by rom().
Member Data Documentation
rom_instance_
std::unique_ptr<Rom> yaze::test::TestRomManager::BoundRomTest::rom_instance_ private
Definition at line 152 of file test_utils.h.
Referenced by EnsureRomLoaded(), rom(), rom(), SetUp(), and TearDown().
rom_loaded_
bool yaze::test::TestRomManager::BoundRomTest::rom_loaded_ = false private
Definition at line 153 of file test_utils.h.
Referenced by EnsureRomLoaded(), and TearDown().
The documentation for this class was generated from the following file:
test/test_utils.h