set(
  YAZE_GUI_SRC
  app/gui/modules/asset_browser.cc
  app/gui/modules/text_editor.cc
  app/gui/canvas.cc
  app/gui/canvas_utils.cc
  app/gui/enhanced_palette_editor.cc
  app/gui/input.cc
  app/gui/style.cc
  app/gui/color.cc
  app/gui/theme_manager.cc
  app/gui/background_renderer.cc
  app/gui/bpp_format_ui.cc
  # Canvas system components
  app/gui/canvas/canvas_modals.cc
  app/gui/canvas/canvas_context_menu.cc
  app/gui/canvas/canvas_usage_tracker.cc
  app/gui/canvas/canvas_performance_integration.cc
  app/gui/canvas/canvas_interaction_handler.cc
)
