yaze: yaze::gui::CanvasMenuBuilder Class Reference
yaze::gui::CanvasMenuBuilder Class Reference
Builder pattern for constructing canvas menus fluently.
#include <canvas_menu_builder.h>
Public Member Functions
CanvasMenuBuilder ()=default
CanvasMenuBuilder & AddItem (const std::string &label, std::function< void()> callback)
Add a simple menu item.
CanvasMenuBuilder & AddItem (const std::string &label, const std::string &icon, std::function< void()> callback)
Add a menu item with icon.
CanvasMenuBuilder & AddItem (const std::string &label, const std::string &icon, const std::string &shortcut, std::function< void()> callback)
Add a menu item with icon and shortcut hint.
CanvasMenuBuilder & AddPopupItem (const std::string &label, const std::string &popup_id, std::function< void()> render_callback)
Add a menu item that opens a persistent popup.
CanvasMenuBuilder & AddPopupItem (const std::string &label, const std::string &icon, const std::string &popup_id, std::function< void()> render_callback)
Add a menu item with icon that opens a persistent popup.
CanvasMenuBuilder & AddConditionalItem (const std::string &label, std::function< void()> callback, std::function< bool()> condition)
Add a conditional menu item (enabled only when condition is true)
CanvasMenuBuilder & AddSubmenu (const std::string &label, const std::vector< CanvasMenuItem > &subitems)
Add a submenu with nested items.
CanvasMenuBuilder & AddSeparator ()
Add a separator to visually group items.
CanvasMenuBuilder & BeginSection (const std::string &title="", MenuSectionPriority priority=MenuSectionPriority::kEditorSpecific)
Start a new section with optional title.
CanvasMenuBuilder & EndSection ()
End the current section.
CanvasMenuDefinition Build ()
Build the final menu definition.
CanvasMenuBuilder & Reset ()
Reset the builder to start building a new menu.
Private Member Functions
void FlushPendingItems ()
Private Attributes
CanvasMenuDefinition menu_
CanvasMenuSection * current_section_ = nullptr
std::vector< CanvasMenuItem > pending_items_
Detailed Description
Builder pattern for constructing canvas menus fluently.
Phase 4: Simplifies menu construction with chainable methods.
Example usage:
CanvasMenuBuilder builder;
builder
  .AddItem("Cut", ICON_MD_CONTENT_CUT, []() { DoCut(); })
  .AddItem("Copy", ICON_MD_CONTENT_COPY, []() { DoCopy(); })
  .AddSeparator()
  .AddPopupItem("Properties", ICON_MD_SETTINGS, "props_popup",
                []() { RenderPropertiesPopup(); })
  .Build();
Definition at line 30 of file canvas_menu_builder.h.
Constructor & Destructor Documentation
CanvasMenuBuilder()
yaze::gui::CanvasMenuBuilder::CanvasMenuBuilder () default
Member Function Documentation
AddItem() [1/3]
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddItem (const std::string & label, std::function< void()> callback)
Add a simple menu item.
Parameters
label Menu item label
callback Action to perform when selected
Returns
Reference to this builder for chaining
Definition at line 6 of file canvas_menu_builder.cc.
References yaze::gui::CanvasMenuItem::callback, yaze::gui::CanvasMenuItem::label, and pending_items_.
AddItem() [2/3]
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddItem (const std::string & label, const std::string & icon, std::function< void()> callback)
Add a menu item with icon.
Parameters
label Menu item label
icon Material Design icon or Unicode glyph
callback Action to perform when selected
Returns
Reference to this builder for chaining
Definition at line 15 of file canvas_menu_builder.cc.
References yaze::gui::CanvasMenuItem::callback, yaze::gui::CanvasMenuItem::icon, yaze::gui::CanvasMenuItem::label, and pending_items_.
AddItem() [3/3]
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddItem (const std::string & label, const std::string & icon, const std::string & shortcut, std::function< void()> callback)
Add a menu item with icon and shortcut hint.
Parameters
label Menu item label
icon Material Design icon or Unicode glyph
shortcut Keyboard shortcut hint (e.g., "Ctrl+S")
callback Action to perform when selected
Returns
Reference to this builder for chaining
Definition at line 26 of file canvas_menu_builder.cc.
References yaze::gui::CanvasMenuItem::callback, yaze::gui::CanvasMenuItem::icon, yaze::gui::CanvasMenuItem::label, pending_items_, and yaze::gui::CanvasMenuItem::shortcut.
AddPopupItem() [1/2]
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddPopupItem (const std::string & label, const std::string & popup_id, std::function< void()> render_callback)
Add a menu item that opens a persistent popup.
Parameters
label Menu item label
popup_id Unique popup identifier
render_callback Callback to render popup content
Returns
Reference to this builder for chaining
Definition at line 39 of file canvas_menu_builder.cc.
References pending_items_, and yaze::gui::CanvasMenuItem::WithPopup().
AddPopupItem() [2/2]
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddPopupItem (const std::string & label, const std::string & icon, const std::string & popup_id, std::function< void()> render_callback)
Add a menu item with icon that opens a persistent popup.
Parameters
label Menu item label
icon Material Design icon or Unicode glyph
popup_id Unique popup identifier
render_callback Callback to render popup content
Returns
Reference to this builder for chaining
Definition at line 47 of file canvas_menu_builder.cc.
References yaze::gui::CanvasMenuItem::icon, pending_items_, and yaze::gui::CanvasMenuItem::WithPopup().
AddConditionalItem()
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddConditionalItem (const std::string & label, std::function< void()> callback, std::function< bool()> condition)
Add a conditional menu item (enabled only when condition is true)
Parameters
label Menu item label
callback Action to perform when selected
condition Function that returns true when item should be enabled
Returns
Reference to this builder for chaining
Definition at line 56 of file canvas_menu_builder.cc.
References yaze::gui::CanvasMenuItem::Conditional(), and pending_items_.
AddSubmenu()
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddSubmenu (const std::string & label, const std::vector< CanvasMenuItem > & subitems)
Add a submenu with nested items.
Parameters
label Submenu label
subitems Nested menu items
Returns
Reference to this builder for chaining
Definition at line 64 of file canvas_menu_builder.cc.
References yaze::gui::CanvasMenuItem::label, pending_items_, and yaze::gui::CanvasMenuItem::subitems.
AddSeparator()
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::AddSeparator ()
Add a separator to visually group items.
Returns
Reference to this builder for chaining
Definition at line 73 of file canvas_menu_builder.cc.
References pending_items_.
BeginSection()
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::BeginSection (const std::string & title = "", MenuSectionPriority priority = MenuSectionPriority::kEditorSpecific)
Start a new section with optional title.
Parameters
title Section title (empty for no title)
priority Section priority (controls rendering order)
Returns
Reference to this builder for chaining
Definition at line 80 of file canvas_menu_builder.cc.
References current_section_, FlushPendingItems(), menu_, yaze::gui::CanvasMenuSection::priority, yaze::gui::CanvasMenuDefinition::sections, yaze::gui::CanvasMenuSection::separator_after, and yaze::gui::CanvasMenuSection::title.
EndSection()
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::EndSection ()
End the current section.
Returns
Reference to this builder for chaining
Definition at line 98 of file canvas_menu_builder.cc.
References current_section_, and FlushPendingItems().
Build()
CanvasMenuDefinition yaze::gui::CanvasMenuBuilder::Build ()
Build the final menu definition.
Returns
Complete menu definition ready for rendering
Definition at line 104 of file canvas_menu_builder.cc.
References FlushPendingItems(), and menu_.
Reset()
CanvasMenuBuilder & yaze::gui::CanvasMenuBuilder::Reset ()
Reset the builder to start building a new menu.
Returns
Reference to this builder for chaining
Definition at line 109 of file canvas_menu_builder.cc.
References current_section_, menu_, pending_items_, and yaze::gui::CanvasMenuDefinition::sections.
FlushPendingItems()
void yaze::gui::CanvasMenuBuilder::FlushPendingItems () private
Definition at line 116 of file canvas_menu_builder.cc.
References current_section_, yaze::gui::CanvasMenuSection::items, yaze::gui::kEditorSpecific, menu_, pending_items_, yaze::gui::CanvasMenuSection::priority, yaze::gui::CanvasMenuDefinition::sections, and yaze::gui::CanvasMenuSection::separator_after.
Referenced by BeginSection(), Build(), and EndSection().
Member Data Documentation
menu_
CanvasMenuDefinition yaze::gui::CanvasMenuBuilder::menu_ private
Definition at line 146 of file canvas_menu_builder.h.
Referenced by BeginSection(), Build(), FlushPendingItems(), and Reset().
current_section_
CanvasMenuSection* yaze::gui::CanvasMenuBuilder::current_section_ = nullptr private
Definition at line 147 of file canvas_menu_builder.h.
Referenced by BeginSection(), EndSection(), FlushPendingItems(), and Reset().
pending_items_
std::vector<CanvasMenuItem> yaze::gui::CanvasMenuBuilder::pending_items_ private
Definition at line 148 of file canvas_menu_builder.h.
Referenced by AddConditionalItem(), AddItem(), AddItem(), AddItem(), AddPopupItem(), AddPopupItem(), AddSeparator(), AddSubmenu(), FlushPendingItems(), and Reset().
The documentation for this class was generated from the following files:
src/app/gui/canvas/canvas_menu_builder.h
src/app/gui/canvas/canvas_menu_builder.cc