yaze: yaze::gui::Canvas::ContextMenuItem Struct Reference
yaze::gui::Canvas::ContextMenuItem Struct Reference
#include <canvas.h>
Public Member Functions
ContextMenuItem ()=default
ContextMenuItem (const std::string &lbl, std::function< void()> cb, const std::string &sc="")
Static Public Member Functions
static ContextMenuItem Disabled (const std::string &lbl)
static ContextMenuItem Conditional (const std::string &lbl, std::function< void()> cb, std::function< bool()> condition)
Public Attributes
std::string label
std::string shortcut
std::function< void()> callback
std::function< bool()> enabled_condition = []() { return true; }
std::vector< ContextMenuItem > subitems
Detailed Description
Definition at line 152 of file canvas.h.
Constructor & Destructor Documentation
ContextMenuItem() [1/2]
yaze::gui::Canvas::ContextMenuItem::ContextMenuItem () default
ContextMenuItem() [2/2]
yaze::gui::Canvas::ContextMenuItem::ContextMenuItem (const std::string & lbl, std::function< void()> cb, const std::string & sc = "") inline
Definition at line 161 of file canvas.h.
Member Function Documentation
Disabled()
static ContextMenuItem yaze::gui::Canvas::ContextMenuItem::Disabled (const std::string & lbl) inline static
Definition at line 166 of file canvas.h.
References enabled_condition, and label.
Conditional()
static ContextMenuItem yaze::gui::Canvas::ContextMenuItem::Conditional (const std::string & lbl, std::function< void()> cb, std::function< bool()> condition) inline static
Definition at line 174 of file canvas.h.
References callback, enabled_condition, and label.
Member Data Documentation
label
std::string yaze::gui::Canvas::ContextMenuItem::label
Definition at line 153 of file canvas.h.
Referenced by Conditional(), Disabled(), yaze::gui::Canvas::DrawContextMenuItem(), and yaze::editor::MapPropertiesSystem::SetupCanvasContextMenu().
shortcut
std::string yaze::gui::Canvas::ContextMenuItem::shortcut
Definition at line 154 of file canvas.h.
Referenced by yaze::gui::Canvas::DrawContextMenuItem().
callback
std::function<void()> yaze::gui::Canvas::ContextMenuItem::callback
Definition at line 155 of file canvas.h.
Referenced by Conditional(), yaze::gui::Canvas::DrawContextMenuItem(), and yaze::editor::MapPropertiesSystem::SetupCanvasContextMenu().
enabled_condition
std::function<bool()> yaze::gui::Canvas::ContextMenuItem::enabled_condition = []() { return true; }
Definition at line 156 of file canvas.h.
Referenced by Conditional(), Disabled(), and yaze::gui::Canvas::DrawContextMenuItem().
subitems
std::vector<ContextMenuItem> yaze::gui::Canvas::ContextMenuItem::subitems
Definition at line 157 of file canvas.h.
Referenced by yaze::gui::Canvas::DrawContextMenuItem().
The documentation for this struct was generated from the following file:
src/app/gui/canvas.h