yaze: yaze::gui::canvas::CanvasPerformanceManager Class Reference
yaze::gui::canvas::CanvasPerformanceManager Class Reference
Global canvas performance manager.
#include <canvas_performance_integration.h>
Public Member Functions
void RegisterIntegration (const std::string &canvas_id, std::shared_ptr< CanvasPerformanceIntegration > integration)
Register a canvas performance integration.
std::shared_ptr< CanvasPerformanceIntegration > GetIntegration (const std::string &canvas_id)
Get integration for canvas.
const std::unordered_map< std::string, std::shared_ptr< CanvasPerformanceIntegration > > & GetAllIntegrations () const
Get all integrations.
void UpdateAllIntegrations ()
Update all integrations.
std::string GetGlobalPerformanceSummary () const
Get global performance summary.
std::string ExportGlobalPerformanceReport () const
Export global performance report.
void ClearAllIntegrations ()
Clear all integrations.
Static Public Member Functions
static CanvasPerformanceManager & Get ()
Private Member Functions
CanvasPerformanceManager ()=default
~CanvasPerformanceManager ()=default
Private Attributes
std::unordered_map< std::string, std::shared_ptr< CanvasPerformanceIntegration > > integrations_
Detailed Description
Global canvas performance manager.
Definition at line 217 of file canvas_performance_integration.h.
Constructor & Destructor Documentation
CanvasPerformanceManager()
yaze::gui::canvas::CanvasPerformanceManager::CanvasPerformanceManager () private default
~CanvasPerformanceManager()
yaze::gui::canvas::CanvasPerformanceManager::~CanvasPerformanceManager () private default
Member Function Documentation
Get()
CanvasPerformanceManager & yaze::gui::canvas::CanvasPerformanceManager::Get () static
Definition at line 525 of file canvas_performance_integration.cc.
Referenced by yaze::gui::Canvas::InitializeEnhancedComponents().
RegisterIntegration()
void yaze::gui::canvas::CanvasPerformanceManager::RegisterIntegration (const std::string & canvas_id, std::shared_ptr< CanvasPerformanceIntegration > integration)
Register a canvas performance integration.
Definition at line 530 of file canvas_performance_integration.cc.
References integrations_.
Referenced by yaze::gui::Canvas::InitializeEnhancedComponents().
GetIntegration()
std::shared_ptr< CanvasPerformanceIntegration > yaze::gui::canvas::CanvasPerformanceManager::GetIntegration (const std::string & canvas_id)
Get integration for canvas.
Definition at line 536 of file canvas_performance_integration.cc.
References integrations_.
GetAllIntegrations()
const std::unordered_map< std::string, std::shared_ptr< CanvasPerformanceIntegration > > & yaze::gui::canvas::CanvasPerformanceManager::GetAllIntegrations () const inline
Get all integrations.
Definition at line 236 of file canvas_performance_integration.h.
References integrations_.
UpdateAllIntegrations()
void yaze::gui::canvas::CanvasPerformanceManager::UpdateAllIntegrations ()
Update all integrations.
Definition at line 544 of file canvas_performance_integration.cc.
References integrations_.
GetGlobalPerformanceSummary()
std::string yaze::gui::canvas::CanvasPerformanceManager::GetGlobalPerformanceSummary () const
Get global performance summary.
Definition at line 550 of file canvas_performance_integration.cc.
References integrations_.
Referenced by ExportGlobalPerformanceReport().
ExportGlobalPerformanceReport()
std::string yaze::gui::canvas::CanvasPerformanceManager::ExportGlobalPerformanceReport () const
Export global performance report.
Definition at line 567 of file canvas_performance_integration.cc.
References GetGlobalPerformanceSummary(), and integrations_.
ClearAllIntegrations()
void yaze::gui::canvas::CanvasPerformanceManager::ClearAllIntegrations ()
Clear all integrations.
Definition at line 593 of file canvas_performance_integration.cc.
References integrations_.
Member Data Documentation
integrations_
std::unordered_map<std::string, std::shared_ptr<CanvasPerformanceIntegration> > yaze::gui::canvas::CanvasPerformanceManager::integrations_ private
Definition at line 262 of file canvas_performance_integration.h.
Referenced by ClearAllIntegrations(), ExportGlobalPerformanceReport(), GetAllIntegrations(), GetGlobalPerformanceSummary(), GetIntegration(), RegisterIntegration(), and UpdateAllIntegrations().
The documentation for this class was generated from the following files:
src/app/gui/canvas/canvas_performance_integration.h
src/app/gui/canvas/canvas_performance_integration.cc