yaze: yaze::project::ProjectManager Class Reference
yaze::project::ProjectManager Class Reference
Enhanced project management with templates and validation.
#include <project.h>
Classes
struct ProjectTemplate
Static Public Member Functions
static std::vector< ProjectTemplate > GetProjectTemplates ()
static absl::StatusOr< YazeProject > CreateFromTemplate (const std::string &template_name, const std::string &project_name, const std::string &base_path)
static std::vector< std::string > FindProjectsInDirectory (const std::string &directory)
static absl::Status BackupProject (const YazeProject &project)
static absl::Status RestoreProject (const std::string &backup_path)
static absl::Status ConvertProject (const std::string &source_path, const std::string &target_path, ProjectFormat target_format)
static absl::Status ValidateProjectStructure (const YazeProject &project)
static std::vector< std::string > GetRecommendedFixesForProject (const YazeProject &project)
Detailed Description
Enhanced project management with templates and validation.
Definition at line 182 of file project.h.
Member Function Documentation
GetProjectTemplates()
std::vector< ProjectManager::ProjectTemplate > yaze::project::ProjectManager::GetProjectTemplates () static
Definition at line 610 of file project.cc.
References ICON_MD_BUILD, ICON_MD_DOMAIN, ICON_MD_MAP, ICON_MD_PALETTE, and ICON_MD_VIDEOGAME_ASSET.
CreateFromTemplate()
absl::StatusOr< YazeProject > yaze::project::ProjectManager::CreateFromTemplate (const std::string & template_name, const std::string & project_name, const std::string & base_path) static
Definition at line 645 of file project.cc.
References yaze::project::YazeProject::Create(), yaze::project::ProjectMetadata::description, yaze::project::YazeProject::feature_flags, yaze::core::FeatureFlags::Flags::Overworld::kApplyZSCustomOverworldASM, yaze::core::FeatureFlags::Flags::Overworld::kLoadCustomOverworld, yaze::core::FeatureFlags::Flags::kSaveDungeonMaps, yaze::core::FeatureFlags::Flags::kSaveGraphicsSheet, yaze::project::YazeProject::metadata, yaze::core::FeatureFlags::Flags::overworld, yaze::project::YazeProject::Save(), yaze::project::WorkspaceSettings::show_grid, yaze::project::ProjectMetadata::tags, and yaze::project::YazeProject::workspace_settings.
FindProjectsInDirectory()
std::vector< std::string > yaze::project::ProjectManager::FindProjectsInDirectory (const std::string & directory) static
Definition at line 689 of file project.cc.
BackupProject()
absl::Status yaze::project::ProjectManager::BackupProject (const YazeProject & project) static
Definition at line 708 of file project.cc.
References yaze::project::YazeProject::filepath, and yaze::project::YazeProject::name.
RestoreProject()
static absl::Status yaze::project::ProjectManager::RestoreProject (const std::string & backup_path) static
ConvertProject()
static absl::Status yaze::project::ProjectManager::ConvertProject (const std::string & source_path, const std::string & target_path, ProjectFormat target_format) static
ValidateProjectStructure()
absl::Status yaze::project::ProjectManager::ValidateProjectStructure (const YazeProject & project) static
Definition at line 734 of file project.cc.
References yaze::project::YazeProject::Validate().
GetRecommendedFixesForProject()
std::vector< std::string > yaze::project::ProjectManager::GetRecommendedFixesForProject (const YazeProject & project) static
Definition at line 738 of file project.cc.
References yaze::project::YazeProject::code_folder, yaze::project::ProjectMetadata::description, yaze::project::YazeProject::GetMissingFiles(), yaze::project::YazeProject::git_repository, yaze::project::YazeProject::labels_filename, yaze::project::YazeProject::metadata, yaze::project::YazeProject::rom_filename, and yaze::project::YazeProject::track_changes.
The documentation for this class was generated from the following files:
src/core/project.h
src/core/project.cc