yaze: yaze::editor::MessagePreview Struct Reference
yaze::editor::MessagePreview Struct Reference
#include <message_preview.h>
Public Member Functions
MessagePreview ()
void DrawTileToPreview (int x, int y, int srcx, int srcy, int pal, int sizex=1, int sizey=1)
void DrawStringToPreview (const std::string &str)
void DrawCharacterToPreview (char c)
void DrawCharacterToPreview (const std::vector< uint8_t > &text)
void DrawMessagePreview (const MessageData &message)
Public Attributes
bool skip_next = false
int text_line = 0
int text_position = 0
int shown_lines = 0
std::array< uint8_t, kWidthArraySize > width_array = {0}
std::vector< uint8_t > font_gfx16_data_
std::vector< uint8_t > font_gfx16_data_2_
std::vector< uint8_t > current_preview_data_
std::vector< DictionaryEntry > all_dictionaries_
Detailed Description
Definition at line 15 of file message_preview.h.
Constructor & Destructor Documentation
MessagePreview()
yaze::editor::MessagePreview::MessagePreview () inline
Definition at line 16 of file message_preview.h.
References current_preview_data_, yaze::editor::kCurrentMessageHeight, and yaze::editor::kCurrentMessageWidth.
Member Function Documentation
DrawTileToPreview()
void yaze::editor::MessagePreview::DrawTileToPreview (int x, int y, int srcx, int srcy, int pal, int sizex = 1, int sizey = 1)
Definition at line 6 of file message_preview.cc.
References current_preview_data_, and font_gfx16_data_2_.
Referenced by DrawCharacterToPreview().
DrawStringToPreview()
void yaze::editor::MessagePreview::DrawStringToPreview (const std::string & str)
Definition at line 35 of file message_preview.cc.
References DrawCharacterToPreview().
Referenced by DrawCharacterToPreview().
DrawCharacterToPreview() [1/2]
void yaze::editor::MessagePreview::DrawCharacterToPreview (char c)
Definition at line 41 of file message_preview.cc.
References DrawCharacterToPreview(), and yaze::editor::FindMatchingCharacter().
Referenced by DrawCharacterToPreview(), DrawCharacterToPreview(), DrawMessagePreview(), and DrawStringToPreview().
DrawCharacterToPreview() [2/2]
void yaze::editor::MessagePreview::DrawCharacterToPreview (const std::vector< uint8_t > & text)
Definition at line 47 of file message_preview.cc.
References all_dictionaries_, yaze::editor::DICTOFF, DrawCharacterToPreview(), DrawStringToPreview(), DrawTileToPreview(), yaze::editor::FindRealDictionaryEntry(), yaze::editor::kLine1, yaze::editor::kLine2, yaze::editor::kLine3, yaze::editor::kScrollVertical, skip_next, text_line, text_position, and width_array.
DrawMessagePreview()
void yaze::editor::MessagePreview::DrawMessagePreview (const MessageData & message)
Definition at line 107 of file message_preview.cc.
References current_preview_data_, yaze::editor::MessageData::Data, DrawCharacterToPreview(), shown_lines, text_line, and text_position.
Referenced by yaze::editor::MessageEditor::DrawMessagePreview().
Member Data Documentation
skip_next
bool yaze::editor::MessagePreview::skip_next = false
Definition at line 29 of file message_preview.h.
Referenced by DrawCharacterToPreview().
text_line
int yaze::editor::MessagePreview::text_line = 0
Definition at line 30 of file message_preview.h.
Referenced by DrawCharacterToPreview(), yaze::editor::MessageEditor::DrawCurrentMessage(), and DrawMessagePreview().
text_position
int yaze::editor::MessagePreview::text_position = 0
Definition at line 31 of file message_preview.h.
Referenced by DrawCharacterToPreview(), and DrawMessagePreview().
shown_lines
int yaze::editor::MessagePreview::shown_lines = 0
Definition at line 32 of file message_preview.h.
Referenced by yaze::editor::MessageEditor::DrawCurrentMessage(), and DrawMessagePreview().
width_array
std::array<uint8_t, kWidthArraySize> yaze::editor::MessagePreview::width_array = {0}
Definition at line 34 of file message_preview.h.
Referenced by DrawCharacterToPreview(), yaze::editor::MessageEditor::Initialize(), and yaze::editor::MessageEditor::Save().
font_gfx16_data_
std::vector<uint8_t> yaze::editor::MessagePreview::font_gfx16_data_
Definition at line 35 of file message_preview.h.
Referenced by yaze::editor::MessageEditor::Initialize().
font_gfx16_data_2_
std::vector<uint8_t> yaze::editor::MessagePreview::font_gfx16_data_2_
Definition at line 36 of file message_preview.h.
Referenced by DrawTileToPreview(), and yaze::editor::MessageEditor::Initialize().
current_preview_data_
std::vector<uint8_t> yaze::editor::MessagePreview::current_preview_data_
Definition at line 37 of file message_preview.h.
Referenced by yaze::editor::MessageEditor::DrawMessagePreview(), DrawMessagePreview(), DrawTileToPreview(), and MessagePreview().
all_dictionaries_
std::vector<DictionaryEntry> yaze::editor::MessagePreview::all_dictionaries_
Definition at line 38 of file message_preview.h.
Referenced by DrawCharacterToPreview(), yaze::editor::MessageEditor::DrawDictionary(), yaze::editor::MessageEditor::DrawExpandedMessageSettings(), and yaze::editor::MessageEditor::Initialize().
The documentation for this struct was generated from the following files:
src/app/editor/message/message_preview.h
src/app/editor/message/message_preview.cc