yaze: yaze::cli::tui::anonymous_namespace{chat_tui.cc} Namespace Reference
yaze::cli::tui::anonymous_namespace{chat_tui.cc} Namespace Reference
Functions
Element RenderPanelCard (const std::string &title, const std::vector< Element > &body, Color border_color, bool highlight=false)
Element RenderLatencySparkline (const std::vector< double > &data)
Element RenderMetricLabel (const std::string &icon, const std::string &label, const std::string &value, Color color)
Variables
const std::vector< std::string > kSpinnerFrames
Function Documentation
RenderPanelCard()
Element yaze::cli::tui::anonymous_namespace{chat_tui.cc}::RenderPanelCard (const std::string & title, const std::vector< Element > & body, Color border_color, bool highlight = false)
Definition at line 31 of file chat_tui.cc.
References RenderPanelCard().
Referenced by RenderPanelCard().
RenderLatencySparkline()
Element yaze::cli::tui::anonymous_namespace{chat_tui.cc}::RenderLatencySparkline (const std::vector< double > & data)
Definition at line 44 of file chat_tui.cc.
References RenderLatencySparkline().
Referenced by RenderLatencySparkline().
RenderMetricLabel()
Element yaze::cli::tui::anonymous_namespace{chat_tui.cc}::RenderMetricLabel (const std::string & icon, const std::string & label, const std::string & value, Color color)
Definition at line 55 of file chat_tui.cc.
References RenderMetricLabel().
Referenced by RenderMetricLabel().
Variable Documentation
kSpinnerFrames
const std::vector<std::string> yaze::cli::tui::anonymous_namespace{chat_tui.cc}::kSpinnerFrames
Initial value:
= {
    "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"}
Definition at line 28 of file chat_tui.cc.