yaze: yaze::editor::EditorRegistry Class Reference
yaze::editor::EditorRegistry Class Reference
Manages editor types, categories, and lifecycle.
#include <editor_registry.h>
Public Member Functions
EditorRegistry ()=default
~EditorRegistry ()=default
void JumpToDungeonRoom (int room_id)
void JumpToOverworldMap (int map_id)
void SwitchToEditor (EditorType editor_type)
void HideCurrentEditorCards ()
void ShowEditorCards (EditorType editor_type)
void ToggleEditorCards (EditorType editor_type)
std::vector< EditorType > GetEditorsInCategory (const std::string &category) const
std::vector< std::string > GetAvailableCategories () const
std::string GetEditorDisplayName (EditorType type) const
void RegisterEditor (EditorType type, Editor *editor)
void UnregisterEditor (EditorType type)
Editor * GetEditor (EditorType type) const
bool IsEditorActive (EditorType type) const
bool IsEditorVisible (EditorType type) const
void SetEditorActive (EditorType type, bool active)
Static Public Member Functions
static bool IsCardBasedEditor (EditorType type)
static std::string GetEditorCategory (EditorType type)
static EditorType GetEditorTypeFromCategory (const std::string &category)
Private Member Functions
bool IsValidEditorType (EditorType type) const
void ValidateEditorType (EditorType type) const
Private Attributes
std::unordered_map< EditorType, Editor * > registered_editors_
Static Private Attributes
static const std::unordered_map< EditorType, std::string > kEditorCategories
static const std::unordered_map< EditorType, std::string > kEditorNames
static const std::unordered_map< EditorType, bool > kCardBasedEditors
Detailed Description
Manages editor types, categories, and lifecycle.
Extracted from EditorManager to provide focused editor management:
Editor type classification and categorization
Editor activation and switching
Editor-specific navigation (jump to room/map)
Editor card management
Definition at line 23 of file editor_registry.h.
Constructor & Destructor Documentation
EditorRegistry()
yaze::editor::EditorRegistry::EditorRegistry () default
~EditorRegistry()
yaze::editor::EditorRegistry::~EditorRegistry () default
Member Function Documentation
IsCardBasedEditor()
bool yaze::editor::EditorRegistry::IsCardBasedEditor (EditorType type) static
Definition at line 59 of file editor_registry.cc.
References kCardBasedEditors.
Referenced by yaze::editor::UICoordinator::DrawContextSensitiveCardControl(), HideCurrentEditorCards(), yaze::editor::EditorManager::IsCardBasedEditor(), ShowEditorCards(), and ToggleEditorCards().
GetEditorCategory()
std::string yaze::editor::EditorRegistry::GetEditorCategory (EditorType type) static
Definition at line 64 of file editor_registry.cc.
References kEditorCategories.
Referenced by yaze::editor::UICoordinator::DrawContextSensitiveCardControl(), yaze::editor::EditorManager::HideCurrentEditorCards(), yaze::editor::UICoordinator::HideCurrentEditorCards(), yaze::editor::EditorManager::SwitchToEditor(), and yaze::editor::EditorManager::Update().
GetEditorTypeFromCategory()
EditorType yaze::editor::EditorRegistry::GetEditorTypeFromCategory (const std::string & category) static
Definition at line 72 of file editor_registry.cc.
References kEditorCategories, and yaze::editor::kSettings.
Referenced by yaze::editor::EditorManager::Update().
JumpToDungeonRoom()
void yaze::editor::EditorRegistry::JumpToDungeonRoom (int room_id)
Todo:
Implement dungeon room jumping
Definition at line 81 of file editor_registry.cc.
References yaze::editor::kDungeon, and registered_editors_.
JumpToOverworldMap()
void yaze::editor::EditorRegistry::JumpToOverworldMap (int map_id)
Todo:
Implement overworld map jumping
Definition at line 90 of file editor_registry.cc.
References yaze::editor::kOverworld, and registered_editors_.
SwitchToEditor()
void yaze::editor::EditorRegistry::SwitchToEditor (EditorType editor_type)
Definition at line 99 of file editor_registry.cc.
References GetEditorDisplayName(), registered_editors_, and ValidateEditorType().
HideCurrentEditorCards()
void yaze::editor::EditorRegistry::HideCurrentEditorCards ()
Todo:
Hide cards for this editor
Definition at line 117 of file editor_registry.cc.
References GetEditorDisplayName(), IsCardBasedEditor(), and registered_editors_.
ShowEditorCards()
void yaze::editor::EditorRegistry::ShowEditorCards (EditorType editor_type)
Todo:
Show cards for this editor
Definition at line 126 of file editor_registry.cc.
References GetEditorDisplayName(), IsCardBasedEditor(), and ValidateEditorType().
ToggleEditorCards()
void yaze::editor::EditorRegistry::ToggleEditorCards (EditorType editor_type)
Todo:
Toggle cards for this editor
Definition at line 135 of file editor_registry.cc.
References GetEditorDisplayName(), IsCardBasedEditor(), and ValidateEditorType().
GetEditorsInCategory()
std::vector< EditorType > yaze::editor::EditorRegistry::GetEditorsInCategory (const std::string & category) const
Definition at line 144 of file editor_registry.cc.
References kEditorCategories.
GetAvailableCategories()
std::vector< std::string > yaze::editor::EditorRegistry::GetAvailableCategories () const
Definition at line 156 of file editor_registry.cc.
References kEditorCategories.
GetEditorDisplayName()
std::string yaze::editor::EditorRegistry::GetEditorDisplayName (EditorType type) const
Definition at line 170 of file editor_registry.cc.
References kEditorNames.
Referenced by HideCurrentEditorCards(), RegisterEditor(), ShowEditorCards(), SwitchToEditor(), ToggleEditorCards(), and UnregisterEditor().
RegisterEditor()
void yaze::editor::EditorRegistry::RegisterEditor (EditorType type, Editor * editor)
Definition at line 178 of file editor_registry.cc.
References GetEditorDisplayName(), registered_editors_, and ValidateEditorType().
UnregisterEditor()
void yaze::editor::EditorRegistry::UnregisterEditor (EditorType type)
Definition at line 189 of file editor_registry.cc.
References GetEditorDisplayName(), registered_editors_, and ValidateEditorType().
GetEditor()
Editor * yaze::editor::EditorRegistry::GetEditor (EditorType type) const
Definition at line 199 of file editor_registry.cc.
References registered_editors_, and ValidateEditorType().
IsEditorActive()
bool yaze::editor::EditorRegistry::IsEditorActive (EditorType type) const
Definition at line 209 of file editor_registry.cc.
References registered_editors_, and ValidateEditorType().
IsEditorVisible()
bool yaze::editor::EditorRegistry::IsEditorVisible (EditorType type) const
Definition at line 219 of file editor_registry.cc.
References registered_editors_, and ValidateEditorType().
SetEditorActive()
void yaze::editor::EditorRegistry::SetEditorActive (EditorType type, bool active)
Definition at line 229 of file editor_registry.cc.
References registered_editors_, and ValidateEditorType().
IsValidEditorType()
bool yaze::editor::EditorRegistry::IsValidEditorType (EditorType type) const private
Definition at line 238 of file editor_registry.cc.
References kEditorCategories.
Referenced by ValidateEditorType().
ValidateEditorType()
void yaze::editor::EditorRegistry::ValidateEditorType (EditorType type) const private
Definition at line 242 of file editor_registry.cc.
References IsValidEditorType().
Referenced by GetEditor(), IsEditorActive(), IsEditorVisible(), RegisterEditor(), SetEditorActive(), ShowEditorCards(), SwitchToEditor(), ToggleEditorCards(), and UnregisterEditor().
Member Data Documentation
kEditorCategories
const std::unordered_map< EditorType, std::string > yaze::editor::EditorRegistry::kEditorCategories static private
Initial value:
= {
  {EditorType::kDungeon, "Dungeon"},
  {EditorType::kOverworld, "Overworld"},
  {EditorType::kGraphics, "Graphics"},
  {EditorType::kPalette, "Palette"},
  {EditorType::kSprite, "Sprite"},
  {EditorType::kScreen, "Screen"},
  {EditorType::kMessage, "Message"},
  {EditorType::kMusic, "Music"},
  {EditorType::kAssembly, "Assembly"},
  {EditorType::kEmulator, "Emulator"},
  {EditorType::kHex, "Hex"},
  {EditorType::kAgent, "Agent"},
  {EditorType::kSettings, "System"}
}
Definition at line 60 of file editor_registry.h.
Referenced by GetAvailableCategories(), GetEditorCategory(), GetEditorsInCategory(), GetEditorTypeFromCategory(), and IsValidEditorType().
kEditorNames
const std::unordered_map< EditorType, std::string > yaze::editor::EditorRegistry::kEditorNames static private
Initial value:
= {
  {EditorType::kDungeon, "Dungeon Editor"},
  {EditorType::kOverworld, "Overworld Editor"},
  {EditorType::kGraphics, "Graphics Editor"},
  {EditorType::kPalette, "Palette Editor"},
  {EditorType::kSprite, "Sprite Editor"},
  {EditorType::kScreen, "Screen Editor"},
  {EditorType::kMessage, "Message Editor"},
  {EditorType::kMusic, "Music Editor"},
  {EditorType::kAssembly, "Assembly Editor"},
  {EditorType::kEmulator, "Emulator Editor"},
  {EditorType::kHex, "Hex Editor"},
  {EditorType::kAgent, "Agent Editor"},
  {EditorType::kSettings, "Settings Editor"}
}
Definition at line 61 of file editor_registry.h.
Referenced by GetEditorDisplayName().
kCardBasedEditors
const std::unordered_map< EditorType, bool > yaze::editor::EditorRegistry::kCardBasedEditors static private
Initial value:
= {
  {EditorType::kDungeon, true},
  {EditorType::kOverworld, true},
  {EditorType::kGraphics, true},
  {EditorType::kPalette, true},
  {EditorType::kSprite, true},
  {EditorType::kScreen, true},
  {EditorType::kMessage, true},
  {EditorType::kMusic, true},
  {EditorType::kAssembly, true},
  {EditorType::kEmulator, true},
  {EditorType::kHex, true},
  {EditorType::kAgent, false},
  {EditorType::kSettings, true}
}
Definition at line 62 of file editor_registry.h.
Referenced by IsCardBasedEditor().
registered_editors_
std::unordered_map<EditorType, Editor*> yaze::editor::EditorRegistry::registered_editors_ private
Definition at line 65 of file editor_registry.h.
Referenced by GetEditor(), HideCurrentEditorCards(), IsEditorActive(), IsEditorVisible(), JumpToDungeonRoom(), JumpToOverworldMap(), RegisterEditor(), SetEditorActive(), SwitchToEditor(), and UnregisterEditor().
The documentation for this class was generated from the following files:
src/app/editor/system/editor_registry.h
src/app/editor/system/editor_registry.cc