yaze: yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc} Namespace Reference
yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc} Namespace Reference
Functions
int NormalizeMapId (uint16_t raw_map_id)
int WorldOffset (int world)
absl::Status ValidateMapId (int map_id)
std::string AreaSizeToString (zelda3::AreaSizeEnum size)
std::string EntranceLabel (uint8_t id)
void PopulateCommonWarpFields (WarpEntry &entry, uint16_t raw_map_id, uint16_t map_pos, int pixel_x, int pixel_y)
Variables
constexpr int kLightWorldOffset = 0x00
constexpr int kDarkWorldOffset = 0x40
constexpr int kSpecialWorldOffset = 0x80
Function Documentation
NormalizeMapId()
int yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::NormalizeMapId (uint16_t raw_map_id)
Definition at line 30 of file overworld_inspect.cc.
References NormalizeMapId().
Referenced by NormalizeMapId(), and PopulateCommonWarpFields().
WorldOffset()
int yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::WorldOffset (int world)
Definition at line 34 of file overworld_inspect.cc.
References kDarkWorldOffset, kLightWorldOffset, kSpecialWorldOffset, and WorldOffset().
Referenced by PopulateCommonWarpFields(), and WorldOffset().
ValidateMapId()
absl::Status yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::ValidateMapId (int map_id)
Definition at line 47 of file overworld_inspect.cc.
References yaze::zelda3::kNumOverworldMaps, and ValidateMapId().
Referenced by ValidateMapId().
AreaSizeToString()
std::string yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::AreaSizeToString (zelda3::AreaSizeEnum size)
Definition at line 55 of file overworld_inspect.cc.
References AreaSizeToString(), yaze::zelda3::LargeArea, yaze::zelda3::SmallArea, yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
Referenced by AreaSizeToString().
EntranceLabel()
std::string yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::EntranceLabel (uint8_t id)
Definition at line 70 of file overworld_inspect.cc.
References EntranceLabel(), and yaze::zelda3::kEntranceNames.
Referenced by EntranceLabel().
PopulateCommonWarpFields()
void yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::PopulateCommonWarpFields (WarpEntry & entry, uint16_t raw_map_id, uint16_t map_pos, int pixel_x, int pixel_y)
Definition at line 79 of file overworld_inspect.cc.
References kDarkWorldOffset, yaze::zelda3::kNumOverworldMaps, kSpecialWorldOffset, yaze::cli::overworld::WarpEntry::local_index, yaze::cli::overworld::WarpEntry::map_id, yaze::cli::overworld::WarpEntry::map_pos, yaze::cli::overworld::WarpEntry::map_x, yaze::cli::overworld::WarpEntry::map_y, NormalizeMapId(), yaze::cli::overworld::WarpEntry::pixel_x, yaze::cli::overworld::WarpEntry::pixel_y, PopulateCommonWarpFields(), yaze::cli::overworld::WarpEntry::raw_map_id, yaze::cli::overworld::WarpEntry::tile16_x, yaze::cli::overworld::WarpEntry::tile16_y, yaze::cli::overworld::WarpEntry::world, and WorldOffset().
Referenced by PopulateCommonWarpFields().
Variable Documentation
kLightWorldOffset
constexpr int yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::kLightWorldOffset = 0x00 constexpr
Definition at line 26 of file overworld_inspect.cc.
Referenced by WorldOffset().
kDarkWorldOffset
constexpr int yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::kDarkWorldOffset = 0x40 constexpr
Definition at line 27 of file overworld_inspect.cc.
Referenced by PopulateCommonWarpFields(), and WorldOffset().
kSpecialWorldOffset
constexpr int yaze::cli::overworld::anonymous_namespace{overworld_inspect.cc}::kSpecialWorldOffset = 0x80 constexpr
Definition at line 28 of file overworld_inspect.cc.
Referenced by PopulateCommonWarpFields(), and WorldOffset().