yaze: yaze::cli::anonymous_namespace{test_suite_reporter.cc} Namespace Reference
yaze::cli::anonymous_namespace{test_suite_reporter.cc} Namespace Reference
Functions
std::string OutcomeToString (TestCaseOutcome outcome)
std::string EscapeXml (absl::string_view input)
std::string JoinLogs (const std::vector< std::string > &logs)
void ComputeSummaryCounters (const TestSuiteRunSummary &summary, int *total, int *passed, int *failed, int *errors, int *skipped)
absl::Duration TotalDuration (const TestSuiteRunSummary &summary)
Function Documentation
OutcomeToString()
std::string yaze::cli::anonymous_namespace{test_suite_reporter.cc}::OutcomeToString (TestCaseOutcome outcome)
Definition at line 20 of file test_suite_reporter.cc.
References yaze::cli::kError, yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kSkipped, and OutcomeToString().
Referenced by OutcomeToString().
EscapeXml()
std::string yaze::cli::anonymous_namespace{test_suite_reporter.cc}::EscapeXml (absl::string_view input)
Definition at line 34 of file test_suite_reporter.cc.
References EscapeXml().
Referenced by EscapeXml().
JoinLogs()
std::string yaze::cli::anonymous_namespace{test_suite_reporter.cc}::JoinLogs (const std::vector< std::string > & logs)
Definition at line 62 of file test_suite_reporter.cc.
References JoinLogs().
Referenced by JoinLogs().
ComputeSummaryCounters()
void yaze::cli::anonymous_namespace{test_suite_reporter.cc}::ComputeSummaryCounters (const TestSuiteRunSummary & summary, int * total, int * passed, int * failed, int * errors, int * skipped)
Definition at line 69 of file test_suite_reporter.cc.
References ComputeSummaryCounters(), yaze::cli::TestSuiteRunSummary::errors, yaze::cli::TestSuiteRunSummary::failed, yaze::cli::kError, yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kSkipped, yaze::cli::TestSuiteRunSummary::passed, yaze::cli::TestSuiteRunSummary::results, and yaze::cli::TestSuiteRunSummary::skipped.
Referenced by ComputeSummaryCounters().
TotalDuration()
absl::Duration yaze::cli::anonymous_namespace{test_suite_reporter.cc}::TotalDuration (const TestSuiteRunSummary & summary)
Definition at line 99 of file test_suite_reporter.cc.
References yaze::cli::TestSuiteRunSummary::results, yaze::cli::TestSuiteRunSummary::total_duration, and TotalDuration().
Referenced by TotalDuration().