yaze: yaze::core::FeatureFlags Class Reference
yaze::core::FeatureFlags Class Reference
A class to manage experimental feature flags.
#include <features.h>
Classes
struct Flags
Public Member Functions
std::string Serialize () const
Static Public Member Functions
static Flags & get ()
Detailed Description
A class to manage experimental feature flags.
Definition at line 13 of file features.h.
Member Function Documentation
get()
static Flags & yaze::core::FeatureFlags::get () inline static
Definition at line 78 of file features.h.
Referenced by yaze::editor::OverworldEditor::ApplyZSCustomOverworldASM(), yaze::editor::EditorManager::BuildModernMenu(), yaze::zelda3::Overworld::CreateTile32Tilemap(), yaze::gui::FlagsMenu::DrawDungeonFlags(), yaze::gui::FlagsMenu::DrawOverworldFlags(), yaze::editor::OverworldEditor::DrawOverworldSprites(), yaze::gui::FlagsMenu::DrawResourceFlags(), yaze::editor::EditorManager::DrawSessionManager(), yaze::gui::FlagsMenu::DrawSystemFlags(), yaze::test::TestManager::DrawTestDashboard(), yaze::editor::EditorManager::GetCurrentFeatureFlags(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::emu::Cpu::LogInstructions(), main(), yaze::zelda3::OverworldMap::OverworldMap(), yaze::editor::OverworldEditor::Save(), yaze::editor::EditorManager::SaveRom(), yaze::editor::EditorManager::SaveRomAs(), yaze::Rom::SaveToFile(), and Serialize().
Serialize()
std::string yaze::core::FeatureFlags::Serialize () const inline
Definition at line 83 of file features.h.
References get().
The documentation for this class was generated from the following file:
src/app/core/features.h