yaze: yaze::editor::SettingsEditor Class Reference
yaze::editor::SettingsEditor Class Reference
#include <settings_editor.h>
Public Member Functions
SettingsEditor (Rom *rom=nullptr, UserSettings *user_settings=nullptr)
void Initialize () override
absl::Status Load () override
absl::Status Save () override
absl::Status Update () override
void set_user_settings (UserSettings *settings)
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Undo () override
absl::Status Redo () override
absl::Status Find () override
void set_rom (Rom *rom)
Rom * rom () const
bool IsRomLoaded () const override
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
virtual absl::Status Clear ()
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
virtual std::string GetRomStatus () const
Private Member Functions
void DrawGeneralSettings ()
void DrawKeyboardShortcuts ()
void DrawThemeSettings ()
void DrawEditorBehavior ()
void DrawPerformanceSettings ()
void DrawAIAgentSettings ()
Private Attributes
Rom * rom_
UserSettings * user_settings_
Additional Inherited Members
Protected Member Functions inherited from yaze::editor::Editor
std::string MakeCardTitle (const std::string &base_title) const
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Detailed Description
Definition at line 209 of file settings_editor.h.
Constructor & Destructor Documentation
SettingsEditor()
yaze::editor::SettingsEditor::SettingsEditor (Rom * rom = nullptr, UserSettings * user_settings = nullptr) inline explicit
Definition at line 211 of file settings_editor.h.
References yaze::editor::kSettings, and yaze::editor::Editor::type_.
Member Function Documentation
Initialize()
void yaze::editor::SettingsEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 29 of file settings_editor.cc.
Load()
absl::Status yaze::editor::SettingsEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 31 of file settings_editor.cc.
Referenced by yaze::editor::EditorManager::LoadAssets().
Save()
absl::Status yaze::editor::SettingsEditor::Save () inline override virtual
Implements yaze::editor::Editor.
Definition at line 218 of file settings_editor.h.
Update()
absl::Status yaze::editor::SettingsEditor::Update () override virtual
Implements yaze::editor::Editor.
Definition at line 36 of file settings_editor.cc.
References DrawAIAgentSettings(), DrawEditorBehavior(), yaze::gui::DrawFontManager(), DrawGeneralSettings(), DrawKeyboardShortcuts(), DrawPerformanceSettings(), DrawThemeSettings(), ICON_MD_FONT_DOWNLOAD, ICON_MD_KEYBOARD, ICON_MD_PALETTE, ICON_MD_SETTINGS, ICON_MD_SMART_TOY, ICON_MD_SPEED, and ICON_MD_TUNE.
set_user_settings()
void yaze::editor::SettingsEditor::set_user_settings (UserSettings * settings) inline
Definition at line 221 of file settings_editor.h.
References user_settings_.
Referenced by yaze::editor::EditorSet::set_user_settings().
Cut()
absl::Status yaze::editor::SettingsEditor::Cut () inline override virtual
Implements yaze::editor::Editor.
Definition at line 222 of file settings_editor.h.
Copy()
absl::Status yaze::editor::SettingsEditor::Copy () inline override virtual
Implements yaze::editor::Editor.
Definition at line 223 of file settings_editor.h.
Paste()
absl::Status yaze::editor::SettingsEditor::Paste () inline override virtual
Implements yaze::editor::Editor.
Definition at line 224 of file settings_editor.h.
Undo()
absl::Status yaze::editor::SettingsEditor::Undo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 225 of file settings_editor.h.
Redo()
absl::Status yaze::editor::SettingsEditor::Redo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 226 of file settings_editor.h.
Find()
absl::Status yaze::editor::SettingsEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 227 of file settings_editor.h.
set_rom()
void yaze::editor::SettingsEditor::set_rom (Rom * rom) inline
Definition at line 230 of file settings_editor.h.
References rom(), and rom_.
rom()
Rom * yaze::editor::SettingsEditor::rom () const inline
Definition at line 233 of file settings_editor.h.
References rom_.
Referenced by set_rom().
IsRomLoaded()
bool yaze::editor::SettingsEditor::IsRomLoaded () const inline override virtual
Reimplemented from yaze::editor::Editor.
Definition at line 235 of file settings_editor.h.
DrawGeneralSettings()
void yaze::editor::SettingsEditor::DrawGeneralSettings () private
Definition at line 72 of file settings_editor.cc.
References yaze::gui::FlagsMenu::DrawDungeonFlags(), yaze::gui::FlagsMenu::DrawOverworldFlags(), yaze::gui::FlagsMenu::DrawResourceFlags(), and yaze::gui::FlagsMenu::DrawSystemFlags().
Referenced by Update().
DrawKeyboardShortcuts()
void yaze::editor::SettingsEditor::DrawKeyboardShortcuts () private
Todo:
Implement keyboard shortcut editor with:
Definition at line 102 of file settings_editor.cc.
Referenced by Update().
DrawThemeSettings()
void yaze::editor::SettingsEditor::DrawThemeSettings () private
Definition at line 113 of file settings_editor.cc.
References yaze::gui::ThemeManager::Get(), ICON_MD_CHECK, ICON_MD_EDIT, and ICON_MD_PALETTE.
Referenced by Update().
DrawEditorBehavior()
void yaze::editor::SettingsEditor::DrawEditorBehavior () private
Definition at line 162 of file settings_editor.cc.
References yaze::editor::UserSettings::Preferences::autosave_enabled, yaze::editor::UserSettings::Preferences::autosave_interval, yaze::editor::UserSettings::Preferences::backup_before_save, yaze::editor::UserSettings::Preferences::default_editor, ICON_MD_EDIT, ICON_MD_HISTORY, ICON_MD_SAVE, ICON_MD_TUNE, yaze::editor::UserSettings::prefs(), yaze::editor::UserSettings::Preferences::recent_files_limit, yaze::editor::UserSettings::Save(), and user_settings_.
Referenced by Update().
DrawPerformanceSettings()
void yaze::editor::SettingsEditor::DrawPerformanceSettings () private
Definition at line 209 of file settings_editor.cc.
References yaze::editor::UserSettings::Preferences::cache_size_mb, ICON_MD_IMAGE, ICON_MD_MEMORY, ICON_MD_SPEED, yaze::editor::UserSettings::prefs(), yaze::editor::UserSettings::Save(), yaze::editor::UserSettings::Preferences::target_fps, yaze::editor::UserSettings::Preferences::undo_history_size, user_settings_, and yaze::editor::UserSettings::Preferences::vsync.
Referenced by Update().
DrawAIAgentSettings()
void yaze::editor::SettingsEditor::DrawAIAgentSettings () private
Definition at line 247 of file settings_editor.cc.
References yaze::editor::UserSettings::Preferences::ai_auto_learn, yaze::editor::UserSettings::Preferences::ai_max_tokens, yaze::editor::UserSettings::Preferences::ai_multimodal, yaze::editor::UserSettings::Preferences::ai_proactive, yaze::editor::UserSettings::Preferences::ai_provider, yaze::editor::UserSettings::Preferences::ai_temperature, yaze::util::LogManager::configure(), yaze::util::ERROR, yaze::util::FATAL, yaze::editor::UserSettings::Preferences::gemini_api_key, ICON_MD_BUG_REPORT, ICON_MD_CLOUD, ICON_MD_DELETE, ICON_MD_FILTER_ALT, ICON_MD_FOLDER_OPEN, ICON_MD_PSYCHOLOGY, ICON_MD_SMART_TOY, ICON_MD_TERMINAL, ICON_MD_TUNE, yaze::util::INFO, yaze::util::LogManager::instance(), yaze::editor::UserSettings::Preferences::log_ai_requests, LOG_DEBUG, LOG_ERROR, yaze::editor::UserSettings::Preferences::log_file_path, yaze::editor::UserSettings::Preferences::log_gui_automation, LOG_INFO, yaze::editor::UserSettings::Preferences::log_level, yaze::editor::UserSettings::Preferences::log_proposals, yaze::editor::UserSettings::Preferences::log_rom_operations, yaze::editor::UserSettings::Preferences::log_to_file, LOG_WARN, yaze::editor::UserSettings::Preferences::ollama_url, yaze::editor::UserSettings::prefs(), yaze::editor::UserSettings::Save(), user_settings_, yaze::util::WARNING, and yaze::util::YAZE_DEBUG.
Referenced by Update().
Member Data Documentation
rom_
Rom* yaze::editor::SettingsEditor::rom_ private
Definition at line 238 of file settings_editor.h.
Referenced by rom(), and set_rom().
user_settings_
UserSettings* yaze::editor::SettingsEditor::user_settings_ private
Definition at line 239 of file settings_editor.h.
Referenced by DrawAIAgentSettings(), DrawEditorBehavior(), DrawPerformanceSettings(), and set_user_settings().
The documentation for this class was generated from the following files:
src/app/editor/system/settings_editor.h
src/app/editor/system/settings_editor.cc