yaze: yaze::cli::agent::ConversationalAgentService Class Reference
yaze::cli::agent::ConversationalAgentService Class Reference
#include <conversational_agent_service.h>
Classes
struct InternalMetrics
Public Member Functions
ConversationalAgentService ()
ConversationalAgentService (const AgentConfig &config)
absl::StatusOr< ChatMessage > SendMessage (const std::string &message)
const std::vector< ChatMessage > & GetHistory () const
void SetRomContext (Rom *rom)
void ResetConversation ()
void SetConfig (const AgentConfig &config)
const AgentConfig & GetConfig () const
ChatMessage::SessionMetrics GetMetrics () const
void ReplaceHistory (std::vector< ChatMessage > history)
Private Member Functions
void TrimHistoryIfNeeded ()
ChatMessage::SessionMetrics BuildMetricsSnapshot () const
void RebuildMetricsFromHistory ()
Private Attributes
std::vector< ChatMessage > history_
std::unique_ptr< AIService > ai_service_
ToolDispatcher tool_dispatcher_
Rom * rom_context_ = nullptr
AgentConfig config_
InternalMetrics metrics_
Detailed Description
Definition at line 72 of file conversational_agent_service.h.
Constructor & Destructor Documentation
ConversationalAgentService() [1/2]
yaze::cli::agent::ConversationalAgentService::ConversationalAgentService ()
Definition at line 175 of file conversational_agent_service.cc.
References ai_service_, and yaze::cli::CreateAIService().
ConversationalAgentService() [2/2]
yaze::cli::agent::ConversationalAgentService::ConversationalAgentService (const AgentConfig & config) explicit
Definition at line 179 of file conversational_agent_service.cc.
References ai_service_, and yaze::cli::CreateAIService().
Member Function Documentation
SendMessage()
absl::StatusOr< ChatMessage > yaze::cli::agent::ConversationalAgentService::SendMessage (const std::string & message)
Definition at line 228 of file conversational_agent_service.cc.
References yaze::cli::agent::ConversationalAgentService::InternalMetrics::agent_messages, yaze::cli::agent::ProposalCreationRequest::ai_provider, ai_service_, BuildMetricsSnapshot(), yaze::cli::agent::ChatMessage::ProposalSummary::change_count, yaze::cli::agent::ConversationalAgentService::InternalMetrics::commands_generated, config_, yaze::cli::agent::CreateProposalFromAgentResponse(), yaze::cli::agent::ToolDispatcher::Dispatch(), yaze::cli::agent::ChatMessage::ProposalSummary::executed_commands, history_, yaze::cli::agent::ChatMessage::ProposalSummary::id, yaze::Rom::is_loaded(), yaze::cli::agent::ChatMessage::kAgent, yaze::cli::util::colors::kCyan, yaze::cli::util::colors::kDim, yaze::cli::util::colors::kReset, yaze::cli::agent::ChatMessage::kUser, yaze::cli::util::colors::kYellow, yaze::cli::agent::AgentConfig::max_tool_iterations, yaze::cli::agent::ChatMessage::metrics, metrics_, yaze::cli::util::PrintError(), yaze::cli::util::PrintInfo(), yaze::cli::util::PrintSeparator(), yaze::cli::util::PrintSuccess(), yaze::cli::util::PrintToolCall(), yaze::cli::util::PrintWarning(), yaze::cli::agent::ProposalCreationRequest::prompt, yaze::cli::agent::ChatMessage::proposal, yaze::cli::agent::ChatMessage::ProposalSummary::proposal_json_path, yaze::cli::agent::ConversationalAgentService::InternalMetrics::proposals_created, yaze::cli::agent::ProposalCreationRequest::response, yaze::cli::agent::ProposalCreationRequest::rom, rom_context_, yaze::cli::agent::ProposalCreationRequest::sandbox_label, yaze::cli::agent::ChatMessage::ProposalSummary::sandbox_rom_path, yaze::cli::agent::AgentConfig::show_reasoning, yaze::cli::util::LoadingIndicator::Start(), yaze::cli::util::LoadingIndicator::Stop(), yaze::cli::agent::ConversationalAgentService::InternalMetrics::tool_calls, tool_dispatcher_, yaze::cli::agent::ConversationalAgentService::InternalMetrics::total_latency, TrimHistoryIfNeeded(), yaze::cli::agent::ConversationalAgentService::InternalMetrics::turns_completed, yaze::cli::agent::ConversationalAgentService::InternalMetrics::user_messages, and yaze::cli::agent::AgentConfig::verbose.
Referenced by yaze::cli::tui::ChatTUI::OnSubmit(), yaze::editor::AgentChatWidget::RenderInputBox(), yaze::cli::agent::SimpleChatSession::RunBatch(), yaze::cli::agent::SimpleChatSession::RunInteractive(), yaze::cli::agent::anonymous_namespace{conversation_test.cc}::RunTestCase(), yaze::cli::agent::SimpleChatSession::SendAndWaitForResponse(), and yaze::editor::AgentChatWidget::SetChatHistoryPopup().
GetHistory()
const std::vector< ChatMessage > & yaze::cli::agent::ConversationalAgentService::GetHistory () const
Definition at line 473 of file conversational_agent_service.cc.
References history_.
Referenced by yaze::editor::AgentChatWidget::CountKnownProposals(), yaze::editor::AgentChatWidget::EnsureHistoryLoaded(), yaze::cli::agent::SimpleChatSession::GetHistory(), yaze::editor::AgentChatWidget::PersistHistory(), yaze::editor::AgentChatWidget::RenderHistory(), yaze::cli::tui::ChatTUI::Run(), yaze::cli::agent::anonymous_namespace{conversation_test.cc}::RunTestCase(), yaze::editor::AgentChatWidget::SwitchToSharedHistory(), and yaze::editor::AgentChatWidget::SyncHistoryToPopup().
SetRomContext()
void yaze::cli::agent::ConversationalAgentService::SetRomContext (Rom * rom)
Definition at line 184 of file conversational_agent_service.cc.
References ai_service_, rom_context_, yaze::cli::agent::ToolDispatcher::SetRomContext(), and tool_dispatcher_.
Referenced by yaze::cli::tui::ChatTUI::ChatTUI(), yaze::cli::agent::HandleTestConversationCommand(), main(), yaze::editor::AgentChatWidget::SetRomContext(), yaze::cli::agent::SimpleChatSession::SetRomContext(), and yaze::cli::tui::ChatTUI::SetRomContext().
ResetConversation()
void yaze::cli::agent::ConversationalAgentService::ResetConversation ()
Definition at line 192 of file conversational_agent_service.cc.
References history_, and metrics_.
Referenced by yaze::editor::AgentChatWidget::Draw(), yaze::editor::AgentChatWidget::RenderInputBox(), yaze::cli::agent::SimpleChatSession::Reset(), and yaze::cli::agent::anonymous_namespace{conversation_test.cc}::RunTestCase().
SetConfig()
void yaze::cli::agent::ConversationalAgentService::SetConfig (const AgentConfig & config) inline
Definition at line 90 of file conversational_agent_service.h.
References config_.
Referenced by yaze::cli::agent::SimpleChatSession::SetConfig(), and yaze::editor::AgentChatWidget::UpdateAgentConfig().
GetConfig()
const AgentConfig & yaze::cli::agent::ConversationalAgentService::GetConfig () const inline
Definition at line 91 of file conversational_agent_service.h.
References config_.
GetMetrics()
ChatMessage::SessionMetrics yaze::cli::agent::ConversationalAgentService::GetMetrics () const
Definition at line 224 of file conversational_agent_service.cc.
References BuildMetricsSnapshot().
Referenced by yaze::cli::tui::ChatTUI::Run(), yaze::cli::agent::SimpleChatSession::RunBatch(), and yaze::cli::agent::SimpleChatSession::RunInteractive().
ReplaceHistory()
void yaze::cli::agent::ConversationalAgentService::ReplaceHistory (std::vector< ChatMessage > history)
Definition at line 477 of file conversational_agent_service.cc.
References history_, RebuildMetricsFromHistory(), and TrimHistoryIfNeeded().
Referenced by yaze::editor::AgentChatWidget::EnsureHistoryLoaded(), and yaze::editor::AgentChatWidget::PollSharedHistory().
TrimHistoryIfNeeded()
void yaze::cli::agent::ConversationalAgentService::TrimHistoryIfNeeded () private
Definition at line 197 of file conversational_agent_service.cc.
References config_, history_, yaze::cli::agent::AgentConfig::max_history_messages, and yaze::cli::agent::AgentConfig::trim_history.
Referenced by ReplaceHistory(), and SendMessage().
BuildMetricsSnapshot()
ChatMessage::SessionMetrics yaze::cli::agent::ConversationalAgentService::BuildMetricsSnapshot () const private
Definition at line 207 of file conversational_agent_service.cc.
References yaze::cli::agent::ConversationalAgentService::InternalMetrics::agent_messages, yaze::cli::agent::ChatMessage::SessionMetrics::average_latency_seconds, yaze::cli::agent::ConversationalAgentService::InternalMetrics::commands_generated, metrics_, yaze::cli::agent::ConversationalAgentService::InternalMetrics::proposals_created, yaze::cli::agent::ConversationalAgentService::InternalMetrics::tool_calls, yaze::cli::agent::ChatMessage::SessionMetrics::total_agent_messages, yaze::cli::agent::ChatMessage::SessionMetrics::total_commands, yaze::cli::agent::ChatMessage::SessionMetrics::total_elapsed_seconds, yaze::cli::agent::ConversationalAgentService::InternalMetrics::total_latency, yaze::cli::agent::ChatMessage::SessionMetrics::total_proposals, yaze::cli::agent::ChatMessage::SessionMetrics::total_tool_calls, yaze::cli::agent::ChatMessage::SessionMetrics::total_user_messages, yaze::cli::agent::ChatMessage::SessionMetrics::turn_index, yaze::cli::agent::ConversationalAgentService::InternalMetrics::turns_completed, and yaze::cli::agent::ConversationalAgentService::InternalMetrics::user_messages.
Referenced by GetMetrics(), and SendMessage().
RebuildMetricsFromHistory()
void yaze::cli::agent::ConversationalAgentService::RebuildMetricsFromHistory () private
Definition at line 484 of file conversational_agent_service.cc.
References yaze::cli::agent::ConversationalAgentService::InternalMetrics::agent_messages, yaze::cli::agent::ConversationalAgentService::InternalMetrics::commands_generated, history_, yaze::cli::agent::ChatMessage::kAgent, yaze::cli::agent::ChatMessage::kUser, metrics_, yaze::cli::agent::ConversationalAgentService::InternalMetrics::proposals_created, yaze::cli::agent::ConversationalAgentService::InternalMetrics::tool_calls, yaze::cli::agent::ConversationalAgentService::InternalMetrics::total_latency, yaze::cli::agent::ConversationalAgentService::InternalMetrics::turns_completed, and yaze::cli::agent::ConversationalAgentService::InternalMetrics::user_messages.
Referenced by ReplaceHistory().
Member Data Documentation
history_
std::vector<ChatMessage> yaze::cli::agent::ConversationalAgentService::history_ private
Definition at line 112 of file conversational_agent_service.h.
Referenced by GetHistory(), RebuildMetricsFromHistory(), ReplaceHistory(), ResetConversation(), SendMessage(), and TrimHistoryIfNeeded().
ai_service_
std::unique_ptr<AIService> yaze::cli::agent::ConversationalAgentService::ai_service_ private
Definition at line 113 of file conversational_agent_service.h.
Referenced by ConversationalAgentService(), ConversationalAgentService(), SendMessage(), and SetRomContext().
tool_dispatcher_
ToolDispatcher yaze::cli::agent::ConversationalAgentService::tool_dispatcher_ private
Definition at line 114 of file conversational_agent_service.h.
Referenced by SendMessage(), and SetRomContext().
rom_context_
Rom* yaze::cli::agent::ConversationalAgentService::rom_context_ = nullptr private
Definition at line 115 of file conversational_agent_service.h.
Referenced by SendMessage(), and SetRomContext().
config_
AgentConfig yaze::cli::agent::ConversationalAgentService::config_ private
Definition at line 116 of file conversational_agent_service.h.
Referenced by GetConfig(), SendMessage(), SetConfig(), and TrimHistoryIfNeeded().
metrics_
InternalMetrics yaze::cli::agent::ConversationalAgentService::metrics_ private
Definition at line 117 of file conversational_agent_service.h.
Referenced by BuildMetricsSnapshot(), RebuildMetricsFromHistory(), ResetConversation(), and SendMessage().
The documentation for this class was generated from the following files:
src/cli/service/agent/conversational_agent_service.h
src/cli/service/agent/conversational_agent_service.cc