yaze: yaze::cli::ResourceCatalog Class Reference
yaze::cli::ResourceCatalog Class Reference
#include <resource_catalog.h>
Public Member Functions
absl::StatusOr< ResourceSchema > GetResource (absl::string_view name) const
const std::vector< ResourceSchema > & AllResources () const
std::string SerializeResource (const ResourceSchema &schema) const
std::string SerializeResources (const std::vector< ResourceSchema > &schemas) const
std::string SerializeResourcesAsYaml (const std::vector< ResourceSchema > &schemas, absl::string_view version, absl::string_view last_updated) const
Static Public Member Functions
static const ResourceCatalog & Instance ()
Private Member Functions
ResourceCatalog ()
Static Private Member Functions
static std::string EscapeJson (absl::string_view value)
static std::string EscapeYaml (absl::string_view value)
Private Attributes
std::vector< ResourceSchema > resources_
Detailed Description
Definition at line 43 of file resource_catalog.h.
Constructor & Destructor Documentation
ResourceCatalog()
yaze::cli::ResourceCatalog::ResourceCatalog () private
Definition at line 297 of file resource_catalog.cc.
Referenced by Instance().
Member Function Documentation
Instance()
const ResourceCatalog & yaze::cli::ResourceCatalog::Instance () static
Definition at line 292 of file resource_catalog.cc.
References ResourceCatalog().
Referenced by yaze::cli::agent::HandleDescribeCommand(), yaze::cli::anonymous_namespace{resource_catalog_test.cc}::TEST(), yaze::cli::anonymous_namespace{resource_catalog_test.cc}::TEST(), yaze::cli::anonymous_namespace{resource_catalog_test.cc}::TEST(), yaze::cli::anonymous_namespace{resource_catalog_test.cc}::TEST(), yaze::cli::anonymous_namespace{resource_catalog_test.cc}::TEST(), and yaze::cli::anonymous_namespace{resource_catalog_test.cc}::TEST().
GetResource()
absl::StatusOr< ResourceSchema > yaze::cli::ResourceCatalog::GetResource (absl::string_view name) const
Definition at line 301 of file resource_catalog.cc.
References resources_.
AllResources()
const std::vector< ResourceSchema > & yaze::cli::ResourceCatalog::AllResources () const
Definition at line 310 of file resource_catalog.cc.
References resources_.
SerializeResource()
std::string yaze::cli::ResourceCatalog::SerializeResource (const ResourceSchema & schema) const
Definition at line 312 of file resource_catalog.cc.
References SerializeResources().
SerializeResources()
std::string yaze::cli::ResourceCatalog::SerializeResources (const std::vector< ResourceSchema > & schemas) const
Definition at line 316 of file resource_catalog.cc.
References EscapeJson().
Referenced by SerializeResource().
SerializeResourcesAsYaml()
std::string yaze::cli::ResourceCatalog::SerializeResourcesAsYaml (const std::vector< ResourceSchema > & schemas, absl::string_view version, absl::string_view last_updated) const
Definition at line 389 of file resource_catalog.cc.
References EscapeYaml().
EscapeJson()
std::string yaze::cli::ResourceCatalog::EscapeJson (absl::string_view value) static private
Definition at line 361 of file resource_catalog.cc.
Referenced by SerializeResources().
EscapeYaml()
std::string yaze::cli::ResourceCatalog::EscapeYaml (absl::string_view value) static private
Definition at line 451 of file resource_catalog.cc.
Referenced by SerializeResourcesAsYaml().
Member Data Documentation
resources_
std::vector<ResourceSchema> yaze::cli::ResourceCatalog::resources_ private
Definition at line 65 of file resource_catalog.h.
Referenced by AllResources(), and GetResource().
The documentation for this class was generated from the following files:
src/cli/service/resources/resource_catalog.h
src/cli/service/resources/resource_catalog.cc