yaze: yaze::emu::ApuDspTest Class Reference
yaze::emu::ApuDspTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Protected Attributes
MemoryImpl mem
Apu * apu
Detailed Description
Definition at line 9 of file apu_dsp_test.cc.
Member Function Documentation
SetUp()
void yaze::emu::ApuDspTest::SetUp () inline override protected
Definition at line 14 of file apu_dsp_test.cc.
References apu, yaze::emu::Apu::Init(), yaze::emu::MemoryImpl::Initialize(), mem, and yaze::emu::Apu::Reset().
TearDown()
void yaze::emu::ApuDspTest::TearDown () inline override protected
Definition at line 22 of file apu_dsp_test.cc.
References apu.
Member Data Documentation
mem
MemoryImpl yaze::emu::ApuDspTest::mem protected
Definition at line 11 of file apu_dsp_test.cc.
Referenced by SetUp().
apu
Apu* yaze::emu::ApuDspTest::apu protected
Definition at line 12 of file apu_dsp_test.cc.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
test/unit/emu/apu_dsp_test.cc