yaze: yaze::cli::handlers::DungeonListObjectsCommandHandler Class Reference
yaze::cli::handlers::DungeonListObjectsCommandHandler Class Reference
Command handler for listing objects in a room.
#include <dungeon_commands.h>
Public Member Functions
std::string GetName () const
Get the command name.
std::string GetDescription () const
std::string GetUsage () const
Get the command usage string.
absl::Status ValidateArgs (const resources::ArgumentParser &parser) override
Validate command arguments.
absl::Status Execute (Rom *rom, const resources::ArgumentParser &parser, resources::OutputFormatter &formatter) override
Execute the command business logic.
Public Member Functions inherited from yaze::cli::resources::CommandHandler
virtual ~CommandHandler ()=default
absl::Status Run (const std::vector< std::string > &args, Rom *rom_context)
Execute the command.
virtual Descriptor Describe () const
Provide metadata for TUI/help summaries.
Additional Inherited Members
Protected Member Functions inherited from yaze::cli::resources::CommandHandler
virtual bool RequiresLabels () const
Check if the command requires ROM labels.
virtual std::string GetDefaultFormat () const
Get the default output format ("json" or "text")
virtual std::string GetOutputTitle () const
Get the output title for formatting.
Detailed Description
Command handler for listing objects in a room.
Definition at line 76 of file dungeon_commands.h.
Member Function Documentation
GetName()
std::string yaze::cli::handlers::DungeonListObjectsCommandHandler::GetName () const inline virtual
Get the command name.
Override this to provide a unique identifier for the command. This is used for command registration and lookup.
Implements yaze::cli::resources::CommandHandler.
Definition at line 78 of file dungeon_commands.h.
GetDescription()
std::string yaze::cli::handlers::DungeonListObjectsCommandHandler::GetDescription () const inline
Definition at line 79 of file dungeon_commands.h.
GetUsage()
std::string yaze::cli::handlers::DungeonListObjectsCommandHandler::GetUsage () const inline virtual
Get the command usage string.
Implements yaze::cli::resources::CommandHandler.
Definition at line 82 of file dungeon_commands.h.
ValidateArgs()
absl::Status yaze::cli::handlers::DungeonListObjectsCommandHandler::ValidateArgs (const resources::ArgumentParser & parser) inline override virtual
Validate command arguments.
Override this to check required arguments and perform custom validation. Called before Execute().
Implements yaze::cli::resources::CommandHandler.
Definition at line 86 of file dungeon_commands.h.
References yaze::cli::resources::ArgumentParser::RequireArgs().
Execute()
absl::Status yaze::cli::handlers::DungeonListObjectsCommandHandler::Execute (Rom * rom, const resources::ArgumentParser & parser, resources::OutputFormatter & formatter) override virtual
Execute the command business logic.
Override this to implement command-specific functionality. The ROM is guaranteed to be loaded and labels initialized.
Todo:
Implement object listing from room data
Implements yaze::cli::resources::CommandHandler.
Definition at line 133 of file dungeon_commands.cc.
References yaze::cli::resources::OutputFormatter::AddField(), yaze::cli::resources::OutputFormatter::BeginArray(), yaze::cli::resources::OutputFormatter::BeginObject(), yaze::cli::resources::OutputFormatter::EndArray(), yaze::cli::resources::OutputFormatter::EndObject(), yaze::zelda3::DungeonEditorSystem::GetRoom(), and yaze::cli::resources::ArgumentParser::GetString().
The documentation for this class was generated from the following files:
src/cli/handlers/game/dungeon_commands.h
src/cli/handlers/game/dungeon_commands.cc