yaze: yaze::cli::anonymous_namespace{test_suite_writer.cc} Namespace Reference
yaze::cli::anonymous_namespace{test_suite_writer.cc} Namespace Reference
Functions
std::string Indent (int count)
std::string QuoteYaml (absl::string_view value)
void AppendLine (std::string *out, int indent, absl::string_view line)
void AppendScalar (std::string *out, int indent, absl::string_view key, absl::string_view value, bool quote)
std::string FormatDuration (int seconds)
std::string FormatBool (bool value)
std::string JoinQuotedList (const std::vector< std::string > &values)
Function Documentation
Indent()
std::string yaze::cli::anonymous_namespace{test_suite_writer.cc}::Indent (int count)
Definition at line 17 of file test_suite_writer.cc.
References Indent().
Referenced by AppendLine(), AppendScalar(), and Indent().
QuoteYaml()
std::string yaze::cli::anonymous_namespace{test_suite_writer.cc}::QuoteYaml (absl::string_view value)
Definition at line 19 of file test_suite_writer.cc.
References QuoteYaml().
Referenced by AppendScalar(), JoinQuotedList(), and QuoteYaml().
AppendLine()
void yaze::cli::anonymous_namespace{test_suite_writer.cc}::AppendLine (std::string * out, int indent, absl::string_view line)
Definition at line 25 of file test_suite_writer.cc.
References AppendLine(), and Indent().
Referenced by AppendLine().
AppendScalar()
void yaze::cli::anonymous_namespace{test_suite_writer.cc}::AppendScalar (std::string * out, int indent, absl::string_view key, absl::string_view value, bool quote)
Definition at line 31 of file test_suite_writer.cc.
References AppendScalar(), Indent(), and QuoteYaml().
Referenced by AppendScalar().
FormatDuration()
std::string yaze::cli::anonymous_namespace{test_suite_writer.cc}::FormatDuration (int seconds)
Definition at line 47 of file test_suite_writer.cc.
References FormatDuration().
Referenced by FormatDuration().
FormatBool()
std::string yaze::cli::anonymous_namespace{test_suite_writer.cc}::FormatBool (bool value)
Definition at line 57 of file test_suite_writer.cc.
References FormatBool().
Referenced by FormatBool().
JoinQuotedList()
std::string yaze::cli::anonymous_namespace{test_suite_writer.cc}::JoinQuotedList (const std::vector< std::string > & values)
Definition at line 59 of file test_suite_writer.cc.
References JoinQuotedList(), and QuoteYaml().
Referenced by JoinQuotedList().