yaze: yaze::RomLoadOptions Struct Reference
yaze::RomLoadOptions Struct Reference
#include <rom.h>
Static Public Member Functions
static RomLoadOptions AppDefaults ()
static RomLoadOptions CliDefaults ()
static RomLoadOptions RawDataOnly ()
Public Attributes
bool load_zelda3_content = true
bool strip_header = true
bool populate_metadata = true
bool populate_palettes = true
bool populate_gfx_groups = true
bool expand_to_full_image = true
bool load_resource_labels = true
Detailed Description
Definition at line 43 of file rom.h.
Member Function Documentation
AppDefaults()
RomLoadOptions yaze::RomLoadOptions::AppDefaults () static
Definition at line 47 of file rom.cc.
Referenced by yaze::Rom::LoadFromData(), yaze::Rom::LoadFromFile(), and yaze::Rom::LoadZelda3().
CliDefaults()
RomLoadOptions yaze::RomLoadOptions::CliDefaults () static
Definition at line 49 of file rom.cc.
References expand_to_full_image, load_resource_labels, populate_gfx_groups, and populate_palettes.
Referenced by yaze::cli::agent::HandleAcceptCommand(), yaze::cli::RomInfo::Run(), yaze::cli::RomValidate::Run(), yaze::cli::RomDiff::Run(), yaze::cli::RomGenerateGolden::Run(), and yaze::cli::Open::Run().
RawDataOnly()
RomLoadOptions yaze::RomLoadOptions::RawDataOnly () static
Definition at line 58 of file rom.cc.
References expand_to_full_image, load_resource_labels, load_zelda3_content, populate_gfx_groups, populate_metadata, populate_palettes, and strip_header.
Referenced by yaze::Rom::LoadFromData(), and yaze::Rom::LoadFromFile().
Member Data Documentation
load_zelda3_content
bool yaze::RomLoadOptions::load_zelda3_content = true
Definition at line 44 of file rom.h.
Referenced by yaze::Rom::LoadFromData(), yaze::Rom::LoadFromFile(), and RawDataOnly().
strip_header
bool yaze::RomLoadOptions::strip_header = true
Definition at line 45 of file rom.h.
Referenced by yaze::Rom::LoadFromData(), yaze::Rom::LoadFromFile(), yaze::Rom::LoadZelda3(), and RawDataOnly().
populate_metadata
bool yaze::RomLoadOptions::populate_metadata = true
Definition at line 46 of file rom.h.
Referenced by yaze::Rom::LoadZelda3(), and RawDataOnly().
populate_palettes
bool yaze::RomLoadOptions::populate_palettes = true
Definition at line 47 of file rom.h.
Referenced by CliDefaults(), yaze::Rom::LoadZelda3(), and RawDataOnly().
populate_gfx_groups
bool yaze::RomLoadOptions::populate_gfx_groups = true
Definition at line 48 of file rom.h.
Referenced by CliDefaults(), yaze::Rom::LoadZelda3(), and RawDataOnly().
expand_to_full_image
bool yaze::RomLoadOptions::expand_to_full_image = true
Definition at line 49 of file rom.h.
Referenced by CliDefaults(), yaze::Rom::LoadZelda3(), and RawDataOnly().
load_resource_labels
bool yaze::RomLoadOptions::load_resource_labels = true
Definition at line 50 of file rom.h.
Referenced by CliDefaults(), yaze::Rom::LoadFromFile(), and RawDataOnly().
The documentation for this struct was generated from the following files:
src/app/rom.h
src/app/rom.cc