yaze: yaze::cli Namespace Reference
yaze::cli Namespace Reference
Namespace for the command line interface.
Namespaces
namespace agent
namespace ai
namespace anonymous_namespace{agent.cc}
namespace anonymous_namespace{ai_service.cc}
namespace anonymous_namespace{command_palette.cc}
namespace anonymous_namespace{gui_automation_client.cc}
namespace anonymous_namespace{overworld.cc}
namespace anonymous_namespace{prompt_builder.cc}
namespace anonymous_namespace{proposal_registry.cc}
namespace anonymous_namespace{resource_catalog.cc}
namespace anonymous_namespace{resource_catalog_test.cc}
namespace anonymous_namespace{rom_sandbox_manager.cc}
namespace anonymous_namespace{test_suite_loader.cc}
namespace anonymous_namespace{test_suite_reporter.cc}
namespace anonymous_namespace{test_suite_writer.cc}
namespace anonymous_namespace{tile16_proposal_generator.cc}
namespace anonymous_namespace{tile16_proposal_generator_test.cc}
namespace anonymous_namespace{tui.cc}
namespace gui
namespace handlers
namespace message
namespace net
namespace overworld
namespace resources
namespace tui
namespace util
Classes
struct AgentResponse
class AIService
struct AIServiceConfig
class AsarPatchComponent
struct AssertionOutcome
Individual assertion outcome within a harness test.
class AutocompleteEngine
struct AutomationResult
Result of a GUI automation action.
class CommandPaletteComponent
class CommandRegistry
Single source of truth for all z3ed commands.
struct Context
struct DiscoveredWindowInfo
struct DiscoverWidgetsQuery
struct DiscoverWidgetsResult
class EnhancedChatComponent
class EnhancedStatusPanel
struct FewShotExample
class GeminiAIService
struct GeminiConfig
class GuiAutomationClient
Client for automating YAZE GUI through gRPC.
struct HarnessTestSummary
Aggregated metadata about a harness test.
class HexViewerComponent
struct LayoutConfig
struct ListTestsResult
Result container for ListTests RPC.
class MockAIService
class ModernCLI
class OllamaAIService
struct OllamaConfig
class PaletteEditorComponent
struct PanelState
class PolicyEvaluator
struct PolicyResult
struct PolicyViolation
class PromptBuilder
class ProposalRegistry
struct ReplayTestResult
struct ResourceAction
struct ResourceArgument
class ResourceCatalog
class ResourceContextBuilder
Builds contextual information from ROM resources for AI prompts.
struct ResourceSchema
struct RomContext
class RomSandboxManager
struct StartRecordingResult
struct StopRecordingResult
struct Suggestion
struct TestCaseDefinition
struct TestCaseRunResult
struct TestGroupDefinition
struct TestResultDetails
Detailed execution results for a specific harness test.
struct TestStatusDetails
Detailed information about an individual test execution.
struct TestStep
A single step in a GUI test workflow.
struct TestSuiteConfig
struct TestSuiteDefinition
struct TestSuiteRunSummary
struct TestWorkflow
A complete GUI test workflow.
class TestWorkflowGenerator
Generates GUI test workflows from natural language prompts.
struct Tile16Change
Represents a single tile16 change in a proposal.
struct Tile16Proposal
Represents a proposal for tile16 edits on the overworld.
class Tile16ProposalGenerator
Generates and manages tile16 editing proposals.
struct ToolArgument
struct ToolCall
struct ToolSpecification
class TuiComponent
class UnifiedLayout
struct WidgetBoundingBox
struct WidgetDescriptor
Enumerations
enum class ClickType { kLeft , kRight , kMiddle , kDouble }
Type of click action to perform.
enum class TestRunStatus {
kUnknown , kQueued , kRunning , kPassed ,
kFailed , kTimeout
}
Execution status codes returned by the harness.
enum class WidgetTypeFilter {
kUnspecified , kAll , kButton , kInput ,
kMenu , kTab , kCheckbox , kSlider ,
kCanvas , kSelectable , kOther
}
enum class PolicySeverity { kInfo , kWarning , kCritical }
enum class TestCaseOutcome { kPassed , kFailed , kError , kSkipped }
enum class TestStepType {
kClick , kType , kWait , kAssert ,
kScreenshot
}
Type of test step to execute.
enum class MainMenuEntry {
kLoadRom , kAIAgentChat , kTodoManager , kRomTools ,
kGraphicsTools , kTestingTools , kSettings , kHelp ,
kExit
}
enum class LayoutID {
kLoadRom , kAIAgentChat , kTodoManager , kRomTools ,
kGraphicsTools , kTestingTools , kSettings , kApplyAsarPatch ,
kApplyBpsPatch , kExtractSymbols , kValidateAssembly , kGenerateSaveFile ,
kPaletteEditor , kHexViewer , kCommandPalette , kHelp ,
kExit , kMainMenu , kDashboard , kError
}
enum class PanelType {
kMainMenu , kChat , kStatus , kTools ,
kHexViewer , kPaletteEditor , kTodoManager , kRomTools ,
kGraphicsTools , kSettings , kHelp
}
Functions
absl::Status HandleDungeonExportLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleDungeonListObjectsLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldGetTileLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldSetTileLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldFindTileLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldDescribeMapLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldListWarpsLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldSelectRectLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldScrollToLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldSetZoomLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleOverworldGetVisibleRegionLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleGfxExportLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandleGfxImportLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandlePaletteExportLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandlePaletteImportLegacy (const std::vector< std::string > &arg_vec)
absl::Status HandlePaletteLegacy (const std::vector< std::string > &arg_vec)
void HandlePaletteTUI (ftxui::ScreenInteractive &screen)
absl::Status InitializeMockRom (Rom &rom)
Initialize a mock ROM for testing without requiring an actual ROM file.
bool ShouldUseMockRom ()
Check if mock ROM mode should be used based on flags.
std::unique_ptr< AIService > CreateAIService ()
std::unique_ptr< AIService > CreateAIService (const AIServiceConfig &config)
absl::StatusOr< TestSuiteDefinition > ParseTestSuiteDefinition (absl::string_view content)
absl::StatusOr< TestSuiteDefinition > LoadTestSuiteFromFile (const std::string &path)
std::string BuildTextSummary (const TestSuiteRunSummary &summary)
absl::StatusOr< std::string > BuildJUnitReport (const TestSuiteRunSummary &summary)
absl::Status WriteJUnitReport (const TestSuiteRunSummary &summary, const std::string &output_path)
std::string BuildTestSuiteYaml (const TestSuiteDefinition &suite)
absl::Status WriteTestSuiteToFile (const TestSuiteDefinition &suite, const std::string &path, bool overwrite)
Component CreateAutocompleteInput (std::string *input_str, AutocompleteEngine *engine)
Create an input component with autocomplete suggestions.
Component CreateQuickActionMenu (ScreenInteractive &screen)
ftxui::Component CreateQuickActionMenu (ftxui::ScreenInteractive &screen)
Create a quick action menu for common ROM operations.
void ShowMain ()
std::string GetColoredLogo ()
Variables
const std::vector< std::string > kMainMenuEntries
constexpr const char * kZ3edLogo
constexpr const char * kZ3edLogoCompact
constexpr const char * kZ3edLogoMinimal
Detailed Description
Namespace for the command line interface.
Enumeration Type Documentation
ClickType
enum class yaze::cli::ClickType strong
Type of click action to perform.
Enumerator
kLeft
kRight
kMiddle
kDouble
Definition at line 44 of file gui_automation_client.h.
TestRunStatus
enum class yaze::cli::TestRunStatus strong
Execution status codes returned by the harness.
Enumerator
kUnknown
kQueued
kRunning
kPassed
kFailed
kTimeout
Definition at line 66 of file gui_automation_client.h.
WidgetTypeFilter
enum class yaze::cli::WidgetTypeFilter strong
Enumerator
kUnspecified
kAll
kButton
kInput
kMenu
kTab
kCheckbox
kSlider
kCanvas
kSelectable
kOther
Definition at line 166 of file gui_automation_client.h.
PolicySeverity
enum class yaze::cli::PolicySeverity strong
Enumerator
kInfo
kWarning
kCritical
Definition at line 16 of file policy_evaluator.h.
TestCaseOutcome
enum class yaze::cli::TestCaseOutcome strong
Enumerator
kPassed
kFailed
kError
kSkipped
Definition at line 58 of file test_suite.h.
TestStepType
enum class yaze::cli::TestStepType strong
Type of test step to execute.
Enumerator
kClick
kType
kWait
kAssert
kScreenshot
Definition at line 18 of file test_workflow_generator.h.
MainMenuEntry
enum class yaze::cli::MainMenuEntry strong
Enumerator
kLoadRom
kAIAgentChat
kTodoManager
kRomTools
kGraphicsTools
kTestingTools
kSettings
kHelp
kExit
Definition at line 30 of file tui.h.
LayoutID
enum class yaze::cli::LayoutID strong
Enumerator
kLoadRom
kAIAgentChat
kTodoManager
kRomTools
kGraphicsTools
kTestingTools
kSettings
kApplyAsarPatch
kApplyBpsPatch
kExtractSymbols
kValidateAssembly
kGenerateSaveFile
kPaletteEditor
kHexViewer
kCommandPalette
kHelp
kExit
kMainMenu
kDashboard
kError
Definition at line 42 of file tui.h.
PanelType
enum class yaze::cli::PanelType strong
Enumerator
kMainMenu
kChat
kStatus
kTools
kHexViewer
kPaletteEditor
kTodoManager
kRomTools
kGraphicsTools
kSettings
kHelp
Definition at line 28 of file unified_layout.h.
Function Documentation
HandleDungeonExportLegacy()
absl::Status yaze::cli::HandleDungeonExportLegacy (const std::vector< std::string > & arg_vec)
Definition at line 14 of file dungeon.cc.
References yaze::zelda3::Room::blockset, yaze::zelda3::DungeonEditorSystem::GetRoom(), yaze::Rom::is_loaded(), yaze::zelda3::Room::layout, yaze::Rom::LoadFromFile(), yaze::zelda3::Room::palette, and yaze::zelda3::Room::spriteset.
HandleDungeonListObjectsLegacy()
absl::Status yaze::cli::HandleDungeonListObjectsLegacy (const std::vector< std::string > & arg_vec)
Definition at line 49 of file dungeon.cc.
References yaze::zelda3::DungeonEditorSystem::GetRoom(), yaze::zelda3::Room::GetTileObjects(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), and yaze::zelda3::Room::LoadObjects().
HandleOverworldGetTileLegacy()
absl::Status yaze::cli::HandleOverworldGetTileLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldGetTileCommandHandler
Definition at line 34 of file overworld.cc.
References yaze::zelda3::Overworld::GetTile(), yaze::Rom::is_loaded(), yaze::zelda3::Overworld::Load(), and yaze::Rom::LoadFromFile().
HandleOverworldSetTileLegacy()
absl::Status yaze::cli::HandleOverworldSetTileLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldSetTileCommandHandler
Definition at line 81 of file overworld.cc.
References yaze::Rom::is_loaded(), yaze::zelda3::Overworld::Load(), yaze::Rom::LoadFromFile(), yaze::Rom::SaveToFile(), yaze::zelda3::Overworld::set_current_world(), and yaze::zelda3::Overworld::SetTile().
HandleOverworldFindTileLegacy()
absl::Status yaze::cli::HandleOverworldFindTileLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldFindTileCommandHandler
Definition at line 154 of file overworld.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::FindTileMatches(), yaze::cli::overworld::InferWorldFromMapId(), yaze::Rom::is_loaded(), yaze::zelda3::Overworld::Load(), yaze::Rom::LoadFromFile(), yaze::cli::overworld::TileSearchOptions::map_id, yaze::cli::overworld::ParseNumeric(), yaze::cli::overworld::ParseWorldSpecifier(), yaze::cli::overworld::TileSearchOptions::world, and yaze::cli::overworld::WorldName().
HandleOverworldDescribeMapLegacy()
absl::Status yaze::cli::HandleOverworldDescribeMapLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldDescribeMapCommandHandler
Definition at line 326 of file overworld.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::BuildMapSummary(), yaze::Rom::is_loaded(), yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::Load(), yaze::Rom::LoadFromFile(), yaze::cli::overworld::ParseNumeric(), and yaze::cli::overworld::WorldName().
HandleOverworldListWarpsLegacy()
absl::Status yaze::cli::HandleOverworldListWarpsLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldListWarpsCommandHandler
Definition at line 511 of file overworld.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::CollectWarpEntries(), yaze::cli::overworld::InferWorldFromMapId(), yaze::Rom::is_loaded(), yaze::cli::overworld::kEntrance, yaze::cli::overworld::kExit, yaze::cli::overworld::kHole, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::Load(), yaze::Rom::LoadFromFile(), yaze::cli::overworld::WarpQuery::map_id, yaze::cli::overworld::ParseNumeric(), yaze::cli::overworld::ParseWorldSpecifier(), yaze::cli::overworld::WarpQuery::type, yaze::cli::overworld::WarpTypeName(), yaze::cli::overworld::WarpQuery::world, and yaze::cli::overworld::WorldName().
HandleOverworldSelectRectLegacy()
absl::Status yaze::cli::HandleOverworldSelectRectLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldSelectRectCommandHandler
Definition at line 732 of file overworld.cc.
HandleOverworldScrollToLegacy()
absl::Status yaze::cli::HandleOverworldScrollToLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldScrollToCommandHandler
Definition at line 768 of file overworld.cc.
HandleOverworldSetZoomLegacy()
absl::Status yaze::cli::HandleOverworldSetZoomLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldSetZoomCommandHandler
Definition at line 801 of file overworld.cc.
HandleOverworldGetVisibleRegionLegacy()
absl::Status yaze::cli::HandleOverworldGetVisibleRegionLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement OverworldGetVisibleRegionCommandHandler
Definition at line 827 of file overworld.cc.
HandleGfxExportLegacy()
absl::Status yaze::cli::HandleGfxExportLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement GfxExportCommandHandler
Todo:
Convert the 8bpp data to the correct SNES bpp format.
Definition at line 14 of file gfx.cc.
References yaze::gfx::Arena::Get(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), and yaze::gfx::SaveCgx().
HandleGfxImportLegacy()
absl::Status yaze::cli::HandleGfxImportLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement GfxImportCommandHandler
Todo:
Convert the 8bpp data to the correct SNES bpp format before writing.
Todo:
Implement saving the modified graphics sheet back to the ROM.
Definition at line 54 of file gfx.cc.
References yaze::Rom::filename(), yaze::gfx::Arena::Get(), yaze::Rom::is_loaded(), yaze::gfx::LoadCgx(), yaze::Rom::LoadFromFile(), and yaze::Rom::SaveToFile().
HandlePaletteExportLegacy()
absl::Status yaze::cli::HandlePaletteExportLegacy (const std::vector< std::string > & arg_vec)
Definition at line 46 of file palette.cc.
References yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), yaze::Rom::palette_group(), and yaze::gfx::SaveCol().
Referenced by HandlePaletteLegacy().
HandlePaletteImportLegacy()
absl::Status yaze::cli::HandlePaletteImportLegacy (const std::vector< std::string > & arg_vec)
Todo:
Implement saving the modified palette back to the ROM.
Todo:
Implement saving the modified palette back to the ROM.
Definition at line 108 of file palette.cc.
References yaze::gfx::DecodeColFile(), yaze::Rom::filename(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), yaze::Rom::palette_group(), and yaze::Rom::SaveToFile().
Referenced by HandlePaletteLegacy().
HandlePaletteLegacy()
absl::Status yaze::cli::HandlePaletteLegacy (const std::vector< std::string > & arg_vec)
Definition at line 22 of file palette.cc.
References HandlePaletteExportLegacy(), and HandlePaletteImportLegacy().
HandlePaletteTUI()
void yaze::cli::HandlePaletteTUI (ftxui::ScreenInteractive & screen)
Todo:
Implement palette editor TUI
Definition at line 40 of file palette.cc.
InitializeMockRom()
absl::Status yaze::cli::InitializeMockRom (Rom & rom)
Initialize a mock ROM for testing without requiring an actual ROM file.
This creates a minimal but valid ROM structure populated with:
All Zelda3 embedded labels (rooms, sprites, entrances, items, etc.)
Minimal header data to satisfy ROM validation
Empty but properly sized data sections
Purpose: Allow AI agent testing and CI/CD without committing ROM files
Parameters
rom ROM object to initialize as mock
Returns
absl::OkStatus() on success, error status on failure
Definition at line 16 of file mock_rom.cc.
References yaze::project::YazeProject::InitializeEmbeddedLabels(), yaze::project::ResourceLabelManager::labels_, yaze::project::ResourceLabelManager::labels_loaded_, yaze::Rom::LoadFromData(), yaze::Rom::resource_label(), and yaze::project::YazeProject::resource_labels.
Referenced by yaze::cli::resources::CommandContext::Initialize(), and yaze::cli::agent::anonymous_namespace{conversation_test.cc}::LoadRomForAgent().
ShouldUseMockRom()
bool yaze::cli::ShouldUseMockRom ()
Check if mock ROM mode should be used based on flags.
Returns
true if –mock-rom flag is set
Definition at line 81 of file mock_rom.cc.
CreateAIService() [1/2]
std::unique_ptr< AIService > yaze::cli::CreateAIService ()
Definition at line 26 of file service_factory.cc.
References CreateAIService(), yaze::cli::AIServiceConfig::gemini_api_key, yaze::cli::AIServiceConfig::model, yaze::cli::AIServiceConfig::ollama_host, and yaze::cli::AIServiceConfig::provider.
Referenced by yaze::cli::agent::ConversationalAgentService::ConversationalAgentService(), yaze::cli::agent::ConversationalAgentService::ConversationalAgentService(), CreateAIService(), yaze::cli::agent::HandlePlanCommand(), yaze::cli::agent::HandleRunCommand(), and main().
CreateAIService() [2/2]
std::unique_ptr< AIService > yaze::cli::CreateAIService (const AIServiceConfig & config)
Definition at line 47 of file service_factory.cc.
References yaze::cli::OllamaConfig::base_url, yaze::cli::AIServiceConfig::gemini_api_key, yaze::cli::GeminiConfig::model, yaze::cli::OllamaConfig::model, yaze::cli::AIServiceConfig::model, yaze::cli::AIServiceConfig::ollama_host, yaze::cli::GeminiConfig::prompt_version, yaze::cli::AIServiceConfig::provider, yaze::cli::GeminiConfig::use_function_calling, yaze::cli::GeminiConfig::verbose, and yaze::cli::AIServiceConfig::verbose.
ParseTestSuiteDefinition()
absl::StatusOr< TestSuiteDefinition > yaze::cli::ParseTestSuiteDefinition (absl::string_view content)
Definition at line 537 of file test_suite_loader.cc.
References yaze::cli::TestSuiteDefinition::config, yaze::cli::TestSuiteDefinition::description, yaze::cli::TestSuiteDefinition::name, RETURN_IF_ERROR, and yaze::cli::TestSuiteDefinition::version.
Referenced by LoadTestSuiteFromFile().
LoadTestSuiteFromFile()
absl::StatusOr< TestSuiteDefinition > yaze::cli::LoadTestSuiteFromFile (const std::string & path)
Definition at line 602 of file test_suite_loader.cc.
References ParseTestSuiteDefinition().
BuildTextSummary()
std::string yaze::cli::BuildTextSummary (const TestSuiteRunSummary & summary)
Definition at line 112 of file test_suite_reporter.cc.
References kPassed, yaze::cli::TestSuiteDefinition::name, yaze::cli::TestSuiteRunSummary::results, yaze::cli::TestSuiteRunSummary::started_at, and yaze::cli::TestSuiteRunSummary::suite.
BuildJUnitReport()
absl::StatusOr< std::string > yaze::cli::BuildJUnitReport (const TestSuiteRunSummary & summary)
Definition at line 182 of file test_suite_reporter.cc.
References kError, kFailed, yaze::cli::TestSuiteDefinition::name, yaze::cli::TestSuiteRunSummary::results, yaze::cli::TestSuiteRunSummary::started_at, and yaze::cli::TestSuiteRunSummary::suite.
Referenced by WriteJUnitReport().
WriteJUnitReport()
absl::Status yaze::cli::WriteJUnitReport (const TestSuiteRunSummary & summary, const std::string & output_path)
Definition at line 269 of file test_suite_reporter.cc.
References ASSIGN_OR_RETURN, and BuildJUnitReport().
BuildTestSuiteYaml()
std::string yaze::cli::BuildTestSuiteYaml (const TestSuiteDefinition & suite)
Definition at line 73 of file test_suite_writer.cc.
References yaze::cli::TestSuiteDefinition::config, yaze::cli::TestGroupDefinition::depends_on, yaze::cli::TestGroupDefinition::description, yaze::cli::TestSuiteDefinition::description, yaze::cli::TestSuiteDefinition::groups, yaze::cli::TestGroupDefinition::name, yaze::cli::TestSuiteDefinition::name, yaze::cli::TestSuiteConfig::parallel_execution, yaze::cli::TestSuiteConfig::retry_on_failure, yaze::cli::TestGroupDefinition::tests, yaze::cli::TestSuiteConfig::timeout_seconds, and yaze::cli::TestSuiteDefinition::version.
Referenced by WriteTestSuiteToFile().
WriteTestSuiteToFile()
absl::Status yaze::cli::WriteTestSuiteToFile (const TestSuiteDefinition & suite, const std::string & path, bool overwrite)
Definition at line 143 of file test_suite_writer.cc.
References BuildTestSuiteYaml().
CreateAutocompleteInput()
ftxui::Component yaze::cli::CreateAutocompleteInput (std::string * input_str, AutocompleteEngine * engine)
Create an input component with autocomplete suggestions.
Parameters
input_str Pointer to the input string
engine Pointer to the autocomplete engine
Returns
ftxui::Component Input component with autocomplete dropdown
Definition at line 11 of file autocomplete_ui.cc.
References yaze::cli::AutocompleteEngine::GetSuggestions().
Referenced by yaze::cli::tui::ChatTUI::Run().
CreateQuickActionMenu() [1/2]
Component yaze::cli::CreateQuickActionMenu (ScreenInteractive & screen)
Definition at line 48 of file autocomplete_ui.cc.
CreateQuickActionMenu() [2/2]
ftxui::Component yaze::cli::CreateQuickActionMenu (ftxui::ScreenInteractive & screen)
Create a quick action menu for common ROM operations.
Parameters
screen The screen interactive reference
Returns
ftxui::Component Menu component with quick actions
ShowMain()
void yaze::cli::ShowMain ()
Definition at line 919 of file tui.cc.
References yaze::cli::LayoutConfig::bottom_panel_height, yaze::cli::LayoutConfig::left_panel_width, yaze::cli::LayoutConfig::right_panel_width, yaze::cli::UnifiedLayout::Run(), yaze::cli::UnifiedLayout::SetLayoutConfig(), yaze::cli::LayoutConfig::show_chat, yaze::cli::LayoutConfig::show_status, yaze::cli::LayoutConfig::show_tools, and ShowMain().
Referenced by main(), and ShowMain().
GetColoredLogo()
std::string yaze::cli::GetColoredLogo () inline
Definition at line 47 of file z3ed_ascii_logo.h.
Referenced by yaze::cli::anonymous_namespace{tui.cc}::DashboardComponent(), anonymous_namespace{cli_main.cc}::PrintCompactHelp(), anonymous_namespace{cli_main.cc}::PrintVersion(), and yaze::cli::ModernCLI::ShowHelp().
Variable Documentation
kMainMenuEntries
const std::vector<std::string> yaze::cli::kMainMenuEntries
Initial value:
= {
    "🎮 Load ROM / Quick Start",
    "🤖 AI Agent Chat",
    "📝 TODO Manager",
    "🔧 ROM Tools",
    "🎨 Graphics & Palettes",
    "🧪 Testing & Validation",
    "⚙️  Settings",
    "❓ Help & Documentation",
    "🚪 Exit",
}
Definition at line 18 of file tui.h.
Referenced by yaze::cli::anonymous_namespace{tui.cc}::DashboardComponent(), and yaze::cli::anonymous_namespace{tui.cc}::MainMenuComponent().
kZ3edLogo
constexpr const char* yaze::cli::kZ3edLogo constexpr
Initial value:
= R"(
    ███████╗██████╗ ███████╗██████╗
    ╚══███╔╝╚════██╗██╔════╝██╔══██╗
      ███╔╝  █████╔╝█████╗  ██║  ██║
     ███╔╝   ╚═══██╗██╔══╝  ██║  ██║
    ███████╗██████╔╝███████╗██████╔╝
    ╚══════╝╚═════╝ ╚══════╝╚═════╝
       ▲      Zelda 3 Editor
      ▲ ▲     AI-Powered CLI
     ▲▲▲▲▲
)"
Definition at line 10 of file z3ed_ascii_logo.h.
kZ3edLogoCompact
constexpr const char* yaze::cli::kZ3edLogoCompact constexpr
Initial value:
= R"(
 ╔════════════════════════════════╗
 ║  ███████╗██████╗ ███████╗██████╗  ║
 ║  ╚══███╔╝╚════██╗██╔════╝██╔══██╗ ║
 ║    ███╔╝  █████╔╝█████╗  ██║  ██║ ║
 ║   ███╔╝   ╚═══██╗██╔══╝  ██║  ██║ ║
 ║  ███████╗██████╔╝███████╗██████╔╝ ║
 ║  ╚══════╝╚═════╝ ╚══════╝╚═════╝  ║
 ║         ▲    Zelda 3 Editor      ║
 ║        ▲ ▲   AI-Powered CLI      ║
 ║       ▲▲▲▲▲  ROM Hacking Tool    ║
 ╚════════════════════════════════╝
)"
Definition at line 23 of file z3ed_ascii_logo.h.
kZ3edLogoMinimal
constexpr const char* yaze::cli::kZ3edLogoMinimal constexpr
Initial value:
= R"(
 ╭──────────────────────╮
 │  Z3ED - Zelda 3      │
 │    ▲   Editor CLI    │
 │   ▲ ▲  AI-Powered    │
 │  ▲▲▲▲▲               │
 ╰──────────────────────╯
)"
Definition at line 37 of file z3ed_ascii_logo.h.