yaze: yaze::editor::DungeonObjectInteraction Class Reference
yaze::editor::DungeonObjectInteraction Class Reference
Handles object selection, placement, and interaction within the dungeon canvas.
#include <dungeon_object_interaction.h>
Public Member Functions
DungeonObjectInteraction (gui::Canvas *canvas)
void HandleCanvasMouseInput ()
void CheckForObjectSelection ()
void PlaceObjectAtPosition (int room_x, int room_y)
void DrawObjectSelectRect ()
void SelectObjectsInRect ()
void DrawSelectBox ()
void DrawDragPreview ()
void UpdateSelectedObjects ()
bool IsObjectInSelectBox (const zelda3::RoomObject &object) const
std::pair< int, int > RoomToCanvasCoordinates (int room_x, int room_y) const
std::pair< int, int > CanvasToRoomCoordinates (int canvas_x, int canvas_y) const
bool IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin=32) const
void SetCurrentRoom (std::array< zelda3::Room, 0x128 > *rooms, int room_id)
void SetPreviewObject (const zelda3::RoomObject &object, bool loaded)
const std::vector< size_t > & GetSelectedObjectIndices () const
bool IsObjectSelectActive () const
void ClearSelection ()
void SetObjectPlacedCallback (std::function< void(const zelda3::RoomObject &)> callback)
void SetCacheInvalidationCallback (std::function< void()> callback)
Private Attributes
gui::Canvas * canvas_
std::array< zelda3::Room, 0x128 > * rooms_ = nullptr
int current_room_id_ = 0
zelda3::RoomObject preview_object_ {0, 0, 0, 0, 0}
bool object_loaded_ = false
bool is_dragging_ = false
bool is_selecting_ = false
ImVec2 drag_start_pos_
ImVec2 drag_current_pos_
ImVec2 select_start_pos_
ImVec2 select_current_pos_
std::vector< int > selected_objects_
bool object_select_active_ = false
ImVec2 object_select_start_
ImVec2 object_select_end_
std::vector< size_t > selected_object_indices_
std::function< void(const zelda3::RoomObject &)> object_placed_callback_
std::function< void()> cache_invalidation_callback_
Detailed Description
Handles object selection, placement, and interaction within the dungeon canvas.
This component manages mouse interactions for object selection (similar to OverworldEditor), object placement, drag operations, and multi-object selection.
Definition at line 21 of file dungeon_object_interaction.h.
Constructor & Destructor Documentation
DungeonObjectInteraction()
yaze::editor::DungeonObjectInteraction::DungeonObjectInteraction (gui::Canvas * canvas) inline explicit
Definition at line 23 of file dungeon_object_interaction.h.
Member Function Documentation
HandleCanvasMouseInput()
void yaze::editor::DungeonObjectInteraction::HandleCanvasMouseInput ()
Todo:
Apply drag transformation to selected objects
Definition at line 8 of file dungeon_object_interaction.cc.
References canvas_, yaze::gui::Canvas::canvas_size(), CanvasToRoomCoordinates(), drag_current_pos_, drag_start_pos_, DrawDragPreview(), is_dragging_, is_selecting_, yaze::gui::Canvas::IsMouseHovering(), object_loaded_, PlaceObjectAtPosition(), select_current_pos_, select_start_pos_, selected_objects_, UpdateSelectedObjects(), and yaze::gui::Canvas::zero_point().
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
CheckForObjectSelection()
void yaze::editor::DungeonObjectInteraction::CheckForObjectSelection ()
Definition at line 75 of file dungeon_object_interaction.cc.
References DrawObjectSelectRect(), object_select_active_, and SelectObjectsInRect().
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
PlaceObjectAtPosition()
void yaze::editor::DungeonObjectInteraction::PlaceObjectAtPosition (int room_x, int room_y)
Definition at line 176 of file dungeon_object_interaction.cc.
References cache_invalidation_callback_, current_room_id_, yaze::zelda3::RoomObject::id_, object_loaded_, object_placed_callback_, preview_object_, rooms_, and yaze::zelda3::RoomObject::x_.
Referenced by HandleCanvasMouseInput().
DrawObjectSelectRect()
void yaze::editor::DungeonObjectInteraction::DrawObjectSelectRect ()
Definition at line 85 of file dungeon_object_interaction.cc.
References canvas_, yaze::gui::Canvas::IsMouseHovering(), object_loaded_, object_select_active_, object_select_end_, object_select_start_, selected_object_indices_, SelectObjectsInRect(), and yaze::gui::Canvas::zero_point().
Referenced by CheckForObjectSelection().
SelectObjectsInRect()
void yaze::editor::DungeonObjectInteraction::SelectObjectsInRect ()
Definition at line 130 of file dungeon_object_interaction.cc.
References canvas_, CanvasToRoomCoordinates(), current_room_id_, object_select_end_, object_select_start_, rooms_, RoomToCanvasCoordinates(), selected_object_indices_, and yaze::gui::Canvas::zero_point().
Referenced by CheckForObjectSelection(), and DrawObjectSelectRect().
DrawSelectBox()
void yaze::editor::DungeonObjectInteraction::DrawSelectBox ()
Definition at line 201 of file dungeon_object_interaction.cc.
References canvas_, is_selecting_, select_current_pos_, select_start_pos_, and yaze::gui::Canvas::zero_point().
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas().
DrawDragPreview()
void yaze::editor::DungeonObjectInteraction::DrawDragPreview ()
Todo:
Draw preview of object at new position
Definition at line 220 of file dungeon_object_interaction.cc.
References canvas_, drag_current_pos_, drag_start_pos_, is_dragging_, selected_objects_, and yaze::gui::Canvas::zero_point().
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas(), and HandleCanvasMouseInput().
UpdateSelectedObjects()
void yaze::editor::DungeonObjectInteraction::UpdateSelectedObjects ()
Definition at line 237 of file dungeon_object_interaction.cc.
References current_room_id_, is_selecting_, IsObjectInSelectBox(), rooms_, and selected_objects_.
Referenced by HandleCanvasMouseInput().
IsObjectInSelectBox()
bool yaze::editor::DungeonObjectInteraction::IsObjectInSelectBox (const zelda3::RoomObject & object) const
Definition at line 254 of file dungeon_object_interaction.cc.
References is_selecting_, RoomToCanvasCoordinates(), select_current_pos_, and select_start_pos_.
Referenced by UpdateSelectedObjects().
RoomToCanvasCoordinates()
std::pair< int, int > yaze::editor::DungeonObjectInteraction::RoomToCanvasCoordinates (int room_x, int room_y) const
Definition at line 272 of file dungeon_object_interaction.cc.
Referenced by IsObjectInSelectBox(), and SelectObjectsInRect().
CanvasToRoomCoordinates()
std::pair< int, int > yaze::editor::DungeonObjectInteraction::CanvasToRoomCoordinates (int canvas_x, int canvas_y) const
Definition at line 277 of file dungeon_object_interaction.cc.
Referenced by yaze::editor::DungeonEditor::DrawDungeonCanvas(), HandleCanvasMouseInput(), and SelectObjectsInRect().
IsWithinCanvasBounds()
bool yaze::editor::DungeonObjectInteraction::IsWithinCanvasBounds (int canvas_x, int canvas_y, int margin = 32) const
Definition at line 282 of file dungeon_object_interaction.cc.
References canvas_, yaze::gui::Canvas::canvas_size(), and yaze::gui::Canvas::global_scale().
SetCurrentRoom()
void yaze::editor::DungeonObjectInteraction::SetCurrentRoom (std::array< zelda3::Room, 0x128 > * rooms, int room_id)
Definition at line 293 of file dungeon_object_interaction.cc.
References current_room_id_, and rooms_.
Referenced by yaze::editor::DungeonEditor::Load().
SetPreviewObject()
void yaze::editor::DungeonObjectInteraction::SetPreviewObject (const zelda3::RoomObject & object, bool loaded)
Definition at line 298 of file dungeon_object_interaction.cc.
References object_loaded_, and preview_object_.
Referenced by yaze::editor::DungeonEditor::Load().
GetSelectedObjectIndices()
const std::vector< size_t > & yaze::editor::DungeonObjectInteraction::GetSelectedObjectIndices () const inline
Definition at line 50 of file dungeon_object_interaction.h.
References selected_object_indices_.
Referenced by yaze::editor::DungeonEditor::DrawCanvasAndPropertiesPanel().
IsObjectSelectActive()
bool yaze::editor::DungeonObjectInteraction::IsObjectSelectActive () const inline
Definition at line 51 of file dungeon_object_interaction.h.
References object_select_active_.
ClearSelection()
void yaze::editor::DungeonObjectInteraction::ClearSelection ()
Definition at line 303 of file dungeon_object_interaction.cc.
References is_dragging_, is_selecting_, object_select_active_, and selected_object_indices_.
Referenced by yaze::editor::DungeonEditor::DrawCanvasAndPropertiesPanel().
SetObjectPlacedCallback()
void yaze::editor::DungeonObjectInteraction::SetObjectPlacedCallback (std::function< void(const zelda3::RoomObject &)> callback) inline
Definition at line 55 of file dungeon_object_interaction.h.
References object_placed_callback_.
Referenced by yaze::editor::DungeonEditor::Load().
SetCacheInvalidationCallback()
void yaze::editor::DungeonObjectInteraction::SetCacheInvalidationCallback (std::function< void()> callback) inline
Definition at line 58 of file dungeon_object_interaction.h.
References cache_invalidation_callback_.
Referenced by yaze::editor::DungeonEditor::Load().
Member Data Documentation
canvas_
gui::Canvas* yaze::editor::DungeonObjectInteraction::canvas_ private
Definition at line 63 of file dungeon_object_interaction.h.
Referenced by DrawDragPreview(), DrawObjectSelectRect(), DrawSelectBox(), HandleCanvasMouseInput(), IsWithinCanvasBounds(), and SelectObjectsInRect().
rooms_
std::array<zelda3::Room, 0x128>* yaze::editor::DungeonObjectInteraction::rooms_ = nullptr private
Definition at line 64 of file dungeon_object_interaction.h.
Referenced by PlaceObjectAtPosition(), SelectObjectsInRect(), SetCurrentRoom(), and UpdateSelectedObjects().
current_room_id_
int yaze::editor::DungeonObjectInteraction::current_room_id_ = 0 private
Definition at line 65 of file dungeon_object_interaction.h.
Referenced by PlaceObjectAtPosition(), SelectObjectsInRect(), SetCurrentRoom(), and UpdateSelectedObjects().
preview_object_
zelda3::RoomObject yaze::editor::DungeonObjectInteraction::preview_object_ {0, 0, 0, 0, 0} private
Definition at line 68 of file dungeon_object_interaction.h.
Referenced by PlaceObjectAtPosition(), and SetPreviewObject().
object_loaded_
bool yaze::editor::DungeonObjectInteraction::object_loaded_ = false private
Definition at line 69 of file dungeon_object_interaction.h.
Referenced by DrawObjectSelectRect(), HandleCanvasMouseInput(), PlaceObjectAtPosition(), and SetPreviewObject().
is_dragging_
bool yaze::editor::DungeonObjectInteraction::is_dragging_ = false private
Definition at line 72 of file dungeon_object_interaction.h.
Referenced by ClearSelection(), DrawDragPreview(), and HandleCanvasMouseInput().
is_selecting_
bool yaze::editor::DungeonObjectInteraction::is_selecting_ = false private
Definition at line 73 of file dungeon_object_interaction.h.
Referenced by ClearSelection(), DrawSelectBox(), HandleCanvasMouseInput(), IsObjectInSelectBox(), and UpdateSelectedObjects().
drag_start_pos_
ImVec2 yaze::editor::DungeonObjectInteraction::drag_start_pos_ private
Definition at line 74 of file dungeon_object_interaction.h.
Referenced by DrawDragPreview(), and HandleCanvasMouseInput().
drag_current_pos_
ImVec2 yaze::editor::DungeonObjectInteraction::drag_current_pos_ private
Definition at line 75 of file dungeon_object_interaction.h.
Referenced by DrawDragPreview(), and HandleCanvasMouseInput().
select_start_pos_
ImVec2 yaze::editor::DungeonObjectInteraction::select_start_pos_ private
Definition at line 76 of file dungeon_object_interaction.h.
Referenced by DrawSelectBox(), HandleCanvasMouseInput(), and IsObjectInSelectBox().
select_current_pos_
ImVec2 yaze::editor::DungeonObjectInteraction::select_current_pos_ private
Definition at line 77 of file dungeon_object_interaction.h.
Referenced by DrawSelectBox(), HandleCanvasMouseInput(), and IsObjectInSelectBox().
selected_objects_
std::vector<int> yaze::editor::DungeonObjectInteraction::selected_objects_ private
Definition at line 78 of file dungeon_object_interaction.h.
Referenced by DrawDragPreview(), HandleCanvasMouseInput(), and UpdateSelectedObjects().
object_select_active_
bool yaze::editor::DungeonObjectInteraction::object_select_active_ = false private
Definition at line 81 of file dungeon_object_interaction.h.
Referenced by CheckForObjectSelection(), ClearSelection(), DrawObjectSelectRect(), and IsObjectSelectActive().
object_select_start_
ImVec2 yaze::editor::DungeonObjectInteraction::object_select_start_ private
Definition at line 82 of file dungeon_object_interaction.h.
Referenced by DrawObjectSelectRect(), and SelectObjectsInRect().
object_select_end_
ImVec2 yaze::editor::DungeonObjectInteraction::object_select_end_ private
Definition at line 83 of file dungeon_object_interaction.h.
Referenced by DrawObjectSelectRect(), and SelectObjectsInRect().
selected_object_indices_
std::vector<size_t> yaze::editor::DungeonObjectInteraction::selected_object_indices_ private
Definition at line 84 of file dungeon_object_interaction.h.
Referenced by ClearSelection(), DrawObjectSelectRect(), GetSelectedObjectIndices(), and SelectObjectsInRect().
object_placed_callback_
std::function<void(const zelda3::RoomObject&)> yaze::editor::DungeonObjectInteraction::object_placed_callback_ private
Definition at line 87 of file dungeon_object_interaction.h.
Referenced by PlaceObjectAtPosition(), and SetObjectPlacedCallback().
cache_invalidation_callback_
std::function<void()> yaze::editor::DungeonObjectInteraction::cache_invalidation_callback_ private
Definition at line 88 of file dungeon_object_interaction.h.
Referenced by PlaceObjectAtPosition(), and SetCacheInvalidationCallback().
The documentation for this class was generated from the following files:
src/app/editor/dungeon/dungeon_object_interaction.h
src/app/editor/dungeon/dungeon_object_interaction.cc