yaze: yaze::cli::ModernCLI Class Reference
yaze::cli::ModernCLI Class Reference
#include <modern_cli.h>
Public Member Functions
ModernCLI ()
absl::Status Run (int argc, char *argv[])
CommandHandler * GetCommandHandler (const std::string &name)
void PrintTopLevelHelp () const
void PrintCategoryHelp (const std::string &category) const
void PrintCommandSummary () const
Public Attributes
std::map< std::string, CommandInfo > commands_
Private Member Functions
void SetupCommands ()
void ShowHelp ()
void ShowCategoryHelp (const std::string &category)
void ShowCommandSummary () const
absl::Status HandleAsarPatchCommand (const std::vector< std::string > &args)
absl::Status HandleBpsPatchCommand (const std::vector< std::string > &args)
absl::Status HandleExtractSymbolsCommand (const std::vector< std::string > &args)
absl::Status HandleAgentCommand (const std::vector< std::string > &args)
absl::Status HandleCollabCommand (const std::vector< std::string > &args)
absl::Status HandleProjectBuildCommand (const std::vector< std::string > &args)
absl::Status HandleProjectInitCommand (const std::vector< std::string > &args)
absl::Status HandleRomInfoCommand (const std::vector< std::string > &args)
absl::Status HandleRomGenerateGoldenCommand (const std::vector< std::string > &args)
absl::Status HandleRomDiffCommand (const std::vector< std::string > &args)
absl::Status HandleDungeonExportCommand (const std::vector< std::string > &args)
absl::Status HandleDungeonListObjectsCommand (const std::vector< std::string > &args)
absl::Status HandleGfxExportCommand (const std::vector< std::string > &args)
absl::Status HandleGfxImportCommand (const std::vector< std::string > &args)
absl::Status HandleCommandPaletteCommand (const std::vector< std::string > &args)
absl::Status HandlePaletteExportCommand (const std::vector< std::string > &args)
absl::Status HandlePaletteImportCommand (const std::vector< std::string > &args)
absl::Status HandlePaletteCommand (const std::vector< std::string > &args)
absl::Status HandleRomValidateCommand (const std::vector< std::string > &args)
absl::Status HandleOverworldGetTileCommand (const std::vector< std::string > &args)
absl::Status HandleOverworldFindTileCommand (const std::vector< std::string > &args)
absl::Status HandleOverworldDescribeMapCommand (const std::vector< std::string > &args)
absl::Status HandleOverworldListWarpsCommand (const std::vector< std::string > &args)
absl::Status HandleOverworldSetTileCommand (const std::vector< std::string > &args)
absl::Status HandleSpriteCreateCommand (const std::vector< std::string > &args)
absl::Status HandleChatEntryCommand (const std::vector< std::string > &args)
absl::Status HandleProposalCommand (const std::vector< std::string > &args)
absl::Status HandleWidgetCommand (const std::vector< std::string > &args)
Detailed Description
Definition at line 22 of file modern_cli.h.
Constructor & Destructor Documentation
ModernCLI()
yaze::cli::ModernCLI::ModernCLI ()
Definition at line 24 of file modern_cli.cc.
References SetupCommands().
Member Function Documentation
Run()
absl::Status yaze::cli::ModernCLI::Run (int argc, char * argv[])
Definition at line 707 of file modern_cli.cc.
References commands_, yaze::cli::CommandInfo::handler, ShowCategoryHelp(), and ShowHelp().
Referenced by main().
GetCommandHandler()
CommandHandler * yaze::cli::ModernCLI::GetCommandHandler (const std::string & name)
Definition at line 760 of file modern_cli.cc.
PrintTopLevelHelp()
void yaze::cli::ModernCLI::PrintTopLevelHelp () const
Definition at line 450 of file modern_cli.cc.
References ShowHelp().
PrintCategoryHelp()
void yaze::cli::ModernCLI::PrintCategoryHelp (const std::string & category) const
Definition at line 454 of file modern_cli.cc.
References ShowCategoryHelp().
Referenced by main().
PrintCommandSummary()
void yaze::cli::ModernCLI::PrintCommandSummary () const
Definition at line 458 of file modern_cli.cc.
References ShowCommandSummary().
Referenced by main().
SetupCommands()
void yaze::cli::ModernCLI::SetupCommands () private
Definition at line 28 of file modern_cli.cc.
References commands_, HandleAgentCommand(), HandleAsarPatchCommand(), HandleBpsPatchCommand(), HandleChatEntryCommand(), HandleCollabCommand(), HandleCommandPaletteCommand(), HandleDungeonExportCommand(), HandleDungeonListObjectsCommand(), HandleExtractSymbolsCommand(), HandleGfxExportCommand(), HandleGfxImportCommand(), HandleOverworldDescribeMapCommand(), HandleOverworldFindTileCommand(), HandleOverworldGetTileCommand(), HandleOverworldListWarpsCommand(), HandleOverworldSetTileCommand(), HandlePaletteCommand(), HandlePaletteExportCommand(), HandlePaletteImportCommand(), HandleProjectBuildCommand(), HandleProjectInitCommand(), HandleProposalCommand(), HandleRomDiffCommand(), HandleRomGenerateGoldenCommand(), HandleRomInfoCommand(), HandleRomValidateCommand(), HandleSpriteCreateCommand(), and HandleWidgetCommand().
Referenced by ModernCLI().
ShowHelp()
void yaze::cli::ModernCLI::ShowHelp () private
Definition at line 365 of file modern_cli.cc.
References yaze::cli::GetColoredLogo().
Referenced by PrintTopLevelHelp(), and Run().
ShowCategoryHelp()
void yaze::cli::ModernCLI::ShowCategoryHelp (const std::string & category) private
Definition at line 462 of file modern_cli.cc.
References yaze::cli::GetColoredLogo().
Referenced by HandleProposalCommand(), HandleWidgetCommand(), PrintCategoryHelp(), and Run().
ShowCommandSummary()
void yaze::cli::ModernCLI::ShowCommandSummary () const private
Definition at line 675 of file modern_cli.cc.
References commands_, and yaze::cli::GetColoredLogo().
Referenced by PrintCommandSummary().
HandleAsarPatchCommand()
absl::Status yaze::cli::ModernCLI::HandleAsarPatchCommand (const std::vector< std::string > & args) private
Definition at line 777 of file modern_cli.cc.
References yaze::cli::AsarPatch::Run().
Referenced by SetupCommands().
HandleBpsPatchCommand()
absl::Status yaze::cli::ModernCLI::HandleBpsPatchCommand (const std::vector< std::string > & args) private
Definition at line 782 of file modern_cli.cc.
References yaze::cli::ApplyPatch::Run().
Referenced by SetupCommands().
HandleExtractSymbolsCommand()
absl::Status yaze::cli::ModernCLI::HandleExtractSymbolsCommand (const std::vector< std::string > & args) private
Definition at line 792 of file modern_cli.cc.
References yaze::core::AsarWrapper::ExtractSymbols(), yaze::core::AsarWrapper::Initialize(), and RETURN_IF_ERROR.
Referenced by SetupCommands().
HandleAgentCommand()
absl::Status yaze::cli::ModernCLI::HandleAgentCommand (const std::vector< std::string > & args) private
Definition at line 813 of file modern_cli.cc.
References yaze::cli::Agent::Run().
Referenced by HandleChatEntryCommand(), HandleProposalCommand(), HandleWidgetCommand(), and SetupCommands().
HandleCollabCommand()
absl::Status yaze::cli::ModernCLI::HandleCollabCommand (const std::vector< std::string > & args) private
Definition at line 818 of file modern_cli.cc.
Referenced by SetupCommands().
HandleProjectBuildCommand()
absl::Status yaze::cli::ModernCLI::HandleProjectBuildCommand (const std::vector< std::string > & args) private
Definition at line 901 of file modern_cli.cc.
References yaze::cli::ProjectBuild::Run().
Referenced by SetupCommands().
HandleProjectInitCommand()
absl::Status yaze::cli::ModernCLI::HandleProjectInitCommand (const std::vector< std::string > & args) private
Definition at line 906 of file modern_cli.cc.
References yaze::cli::ProjectInit::Run().
Referenced by SetupCommands().
HandleRomInfoCommand()
absl::Status yaze::cli::ModernCLI::HandleRomInfoCommand (const std::vector< std::string > & args) private
Definition at line 787 of file modern_cli.cc.
References yaze::cli::RomInfo::Run().
Referenced by SetupCommands().
HandleRomGenerateGoldenCommand()
absl::Status yaze::cli::ModernCLI::HandleRomGenerateGoldenCommand (const std::vector< std::string > & args) private
Definition at line 911 of file modern_cli.cc.
References yaze::cli::Open::Run().
Referenced by SetupCommands().
HandleRomDiffCommand()
absl::Status yaze::cli::ModernCLI::HandleRomDiffCommand (const std::vector< std::string > & args) private
Definition at line 965 of file modern_cli.cc.
References yaze::cli::RomDiff::Run().
Referenced by SetupCommands().
HandleDungeonExportCommand()
absl::Status yaze::cli::ModernCLI::HandleDungeonExportCommand (const std::vector< std::string > & args) private
Definition at line 925 of file modern_cli.cc.
References yaze::cli::DungeonExport::Run().
Referenced by SetupCommands().
HandleDungeonListObjectsCommand()
absl::Status yaze::cli::ModernCLI::HandleDungeonListObjectsCommand (const std::vector< std::string > & args) private
Definition at line 930 of file modern_cli.cc.
References yaze::cli::DungeonListObjects::Run().
Referenced by SetupCommands().
HandleGfxExportCommand()
absl::Status yaze::cli::ModernCLI::HandleGfxExportCommand (const std::vector< std::string > & args) private
Definition at line 935 of file modern_cli.cc.
References yaze::cli::GfxExport::Run().
Referenced by SetupCommands().
HandleGfxImportCommand()
absl::Status yaze::cli::ModernCLI::HandleGfxImportCommand (const std::vector< std::string > & args) private
Definition at line 940 of file modern_cli.cc.
References yaze::cli::GfxImport::Run().
Referenced by SetupCommands().
HandleCommandPaletteCommand()
absl::Status yaze::cli::ModernCLI::HandleCommandPaletteCommand (const std::vector< std::string > & args) private
Definition at line 945 of file modern_cli.cc.
References yaze::cli::CommandPalette::Run().
Referenced by SetupCommands().
HandlePaletteExportCommand()
absl::Status yaze::cli::ModernCLI::HandlePaletteExportCommand (const std::vector< std::string > & args) private
Definition at line 950 of file modern_cli.cc.
References yaze::cli::PaletteExport::Run().
Referenced by SetupCommands().
HandlePaletteImportCommand()
absl::Status yaze::cli::ModernCLI::HandlePaletteImportCommand (const std::vector< std::string > & args) private
Definition at line 960 of file modern_cli.cc.
References yaze::cli::PaletteImport::Run().
Referenced by SetupCommands().
HandlePaletteCommand()
absl::Status yaze::cli::ModernCLI::HandlePaletteCommand (const std::vector< std::string > & args) private
Definition at line 955 of file modern_cli.cc.
References yaze::cli::Palette::Run().
Referenced by SetupCommands().
HandleRomValidateCommand()
absl::Status yaze::cli::ModernCLI::HandleRomValidateCommand (const std::vector< std::string > & args) private
Definition at line 970 of file modern_cli.cc.
References yaze::cli::RomValidate::Run().
Referenced by SetupCommands().
HandleOverworldGetTileCommand()
absl::Status yaze::cli::ModernCLI::HandleOverworldGetTileCommand (const std::vector< std::string > & args) private
Definition at line 975 of file modern_cli.cc.
References yaze::cli::OverworldGetTile::Run().
Referenced by SetupCommands().
HandleOverworldFindTileCommand()
absl::Status yaze::cli::ModernCLI::HandleOverworldFindTileCommand (const std::vector< std::string > & args) private
Definition at line 980 of file modern_cli.cc.
References yaze::cli::OverworldFindTile::Run().
Referenced by SetupCommands().
HandleOverworldDescribeMapCommand()
absl::Status yaze::cli::ModernCLI::HandleOverworldDescribeMapCommand (const std::vector< std::string > & args) private
Definition at line 985 of file modern_cli.cc.
References yaze::cli::OverworldDescribeMap::Run().
Referenced by SetupCommands().
HandleOverworldListWarpsCommand()
absl::Status yaze::cli::ModernCLI::HandleOverworldListWarpsCommand (const std::vector< std::string > & args) private
Definition at line 990 of file modern_cli.cc.
References yaze::cli::OverworldListWarps::Run().
Referenced by SetupCommands().
HandleOverworldSetTileCommand()
absl::Status yaze::cli::ModernCLI::HandleOverworldSetTileCommand (const std::vector< std::string > & args) private
Definition at line 995 of file modern_cli.cc.
References yaze::cli::OverworldSetTile::Run().
Referenced by SetupCommands().
HandleSpriteCreateCommand()
absl::Status yaze::cli::ModernCLI::HandleSpriteCreateCommand (const std::vector< std::string > & args) private
Definition at line 1000 of file modern_cli.cc.
References yaze::cli::SpriteCreate::Run().
Referenced by SetupCommands().
HandleChatEntryCommand()
absl::Status yaze::cli::ModernCLI::HandleChatEntryCommand (const std::vector< std::string > & args) private
Definition at line 1005 of file modern_cli.cc.
References HandleAgentCommand().
Referenced by SetupCommands().
HandleProposalCommand()
absl::Status yaze::cli::ModernCLI::HandleProposalCommand (const std::vector< std::string > & args) private
Definition at line 1082 of file modern_cli.cc.
References HandleAgentCommand(), and ShowCategoryHelp().
Referenced by SetupCommands().
HandleWidgetCommand()
absl::Status yaze::cli::ModernCLI::HandleWidgetCommand (const std::vector< std::string > & args) private
Definition at line 1117 of file modern_cli.cc.
References HandleAgentCommand(), and ShowCategoryHelp().
Referenced by SetupCommands().
Member Data Documentation
commands_
std::map<std::string, CommandInfo> yaze::cli::ModernCLI::commands_
Definition at line 31 of file modern_cli.h.
Referenced by yaze::cli::CommandPaletteComponent::Render(), Run(), SetupCommands(), and ShowCommandSummary().
The documentation for this class was generated from the following files:
src/cli/modern_cli.h
src/cli/modern_cli.cc