yaze: DungeonTestHarness Class Reference
DungeonTestHarness Class Reference
Dumps the state of WRAM and CPU/PPU registers after initialization.
Public Member Functions
DungeonTestHarness (const std::string &rom_path)
absl::Status GenerateHarnessState (const std::string &output_path)
Private Attributes
std::string rom_path_
Detailed Description
Dumps the state of WRAM and CPU/PPU registers after initialization.
This tool runs the SNES emulator from the Reset vector until it hits the main game loop. It then dumps the entire state of WRAM and relevant registers to a header file. This captured state can be used to initialize the emulator for test harnesses, providing a realistic environment for executing native game code.
Definition at line 20 of file dungeon_test_harness.cc.
Constructor & Destructor Documentation
DungeonTestHarness()
DungeonTestHarness::DungeonTestHarness (const std::string & rom_path) inline explicit
Definition at line 22 of file dungeon_test_harness.cc.
Member Function Documentation
GenerateHarnessState()
absl::Status DungeonTestHarness::GenerateHarnessState (const std::string & output_path) inline
Definition at line 25 of file dungeon_test_harness.cc.
References yaze::emu::Snes::cpu(), yaze::emu::Snes::Init(), yaze::Rom::LoadFromFile(), yaze::emu::Snes::ppu(), yaze::emu::Snes::Read(), yaze::emu::Snes::Reset(), RETURN_IF_ERROR, rom_path_, yaze::emu::Snes::RunCycle(), and yaze::Rom::vector().
Referenced by main().
Member Data Documentation
rom_path_
std::string DungeonTestHarness::rom_path_ private
Definition at line 110 of file dungeon_test_harness.cc.
Referenced by GenerateHarnessState().
The documentation for this class was generated from the following file:
tools/test_helpers/dungeon_test_harness.cc