yaze: yaze::anonymous_namespace{font_loader.cc} Namespace Reference
yaze::anonymous_namespace{font_loader.cc} Namespace Reference
Functions
std::string SetFontPath (const std::string &font_path)
absl::Status LoadFont (const FontConfig &font_config)
absl::Status AddIconFont (const FontConfig &)
absl::Status AddJapaneseFont (const FontConfig &)
Function Documentation
SetFontPath()
std::string yaze::anonymous_namespace{font_loader.cc}::SetFontPath (const std::string & font_path)
Definition at line 32 of file font_loader.cc.
References yaze::util::GetBundleResourcePath(), and SetFontPath().
Referenced by AddIconFont(), AddJapaneseFont(), LoadFont(), and SetFontPath().
LoadFont()
absl::Status yaze::anonymous_namespace{font_loader.cc}::LoadFont (const FontConfig & font_config)
Definition at line 46 of file font_loader.cc.
References yaze::FontConfig::font_path, yaze::FontConfig::font_size, LoadFont(), and SetFontPath().
Referenced by LoadFont().
AddIconFont()
absl::Status yaze::anonymous_namespace{font_loader.cc}::AddIconFont (const FontConfig &)
Definition at line 64 of file font_loader.cc.
References AddIconFont(), FONT_ICON_FILE_NAME_MD, ICON_MIN_MD, and SetFontPath().
Referenced by AddIconFont().
AddJapaneseFont()
absl::Status yaze::anonymous_namespace{font_loader.cc}::AddJapaneseFont (const FontConfig &)
Definition at line 80 of file font_loader.cc.
References AddJapaneseFont(), and SetFontPath().
Referenced by AddJapaneseFont().