yaze: yaze::cli::resources Namespace Reference
yaze::cli::resources Namespace Reference
Classes
class ArgumentParser
Utility for parsing common CLI argument patterns.
class ArgumentParserTest
class CommandContext
Encapsulates common context for CLI command execution.
class CommandContextTest
class CommandHandler
Base class for CLI command handlers.
class OutputFormatter
Utility for consistent output formatting across commands.
class OutputFormatterTest
Functions
TEST_F (CommandContextTest, LoadsRomFromConfig)
TEST_F (CommandContextTest, UsesExternalRomContext)
TEST_F (CommandContextTest, LoadsRomFromPath)
TEST_F (CommandContextTest, EnsuresLabelsLoaded)
TEST_F (CommandContextTest, GetFormatReturnsConfigFormat)
TEST_F (CommandContextTest, IsVerboseReturnsConfigVerbose)
TEST_F (ArgumentParserTest, ParsesStringArguments)
TEST_F (ArgumentParserTest, ParsesIntArguments)
TEST_F (ArgumentParserTest, ParsesHexArguments)
TEST_F (ArgumentParserTest, DetectsFlags)
TEST_F (ArgumentParserTest, GetsPositionalArguments)
TEST_F (ArgumentParserTest, ValidatesRequiredArguments)
TEST_F (ArgumentParserTest, HandlesMissingArguments)
TEST_F (OutputFormatterTest, CreatesFromString)
TEST_F (OutputFormatterTest, GeneratesValidJson)
TEST_F (OutputFormatterTest, GeneratesValidText)
TEST_F (OutputFormatterTest, EscapesJsonStrings)
TEST_F (OutputFormatterTest, HandlesEmptyObjects)
TEST_F (OutputFormatterTest, HandlesEmptyArrays)
Function Documentation
TEST_F() [1/19]
yaze::cli::resources::TEST_F (CommandContextTest , LoadsRomFromConfig)
Definition at line 27 of file command_context_test.cc.
References yaze::cli::resources::CommandContext::GetRom(), and yaze::cli::resources::CommandContext::Config::use_mock_rom.
TEST_F() [2/19]
yaze::cli::resources::TEST_F (CommandContextTest , UsesExternalRomContext)
Definition at line 38 of file command_context_test.cc.
References yaze::cli::resources::CommandContext::Config::external_rom_context, and yaze::cli::resources::CommandContext::GetRom().
TEST_F() [3/19]
yaze::cli::resources::TEST_F (CommandContextTest , LoadsRomFromPath)
Definition at line 49 of file command_context_test.cc.
References yaze::cli::resources::CommandContext::GetRom(), and yaze::cli::resources::CommandContext::Config::rom_path.
TEST_F() [4/19]
yaze::cli::resources::TEST_F (CommandContextTest , EnsuresLabelsLoaded)
Definition at line 61 of file command_context_test.cc.
References yaze::cli::resources::CommandContext::EnsureLabelsLoaded(), yaze::cli::resources::CommandContext::GetRom(), and yaze::cli::resources::CommandContext::Config::use_mock_rom.
TEST_F() [5/19]
yaze::cli::resources::TEST_F (CommandContextTest , GetFormatReturnsConfigFormat)
Definition at line 74 of file command_context_test.cc.
References yaze::cli::resources::CommandContext::Config::format, and yaze::cli::resources::CommandContext::GetFormat().
TEST_F() [6/19]
yaze::cli::resources::TEST_F (CommandContextTest , IsVerboseReturnsConfigVerbose)
Definition at line 83 of file command_context_test.cc.
References yaze::cli::resources::CommandContext::IsVerbose(), and yaze::cli::resources::CommandContext::Config::verbose.
TEST_F() [7/19]
yaze::cli::resources::TEST_F (ArgumentParserTest , ParsesStringArguments)
Definition at line 98 of file command_context_test.cc.
References yaze::cli::resources::ArgumentParser::GetString().
TEST_F() [8/19]
yaze::cli::resources::TEST_F (ArgumentParserTest , ParsesIntArguments)
Definition at line 106 of file command_context_test.cc.
References yaze::cli::resources::ArgumentParser::GetInt().
TEST_F() [9/19]
yaze::cli::resources::TEST_F (ArgumentParserTest , ParsesHexArguments)
Definition at line 119 of file command_context_test.cc.
References yaze::cli::resources::ArgumentParser::GetHex().
TEST_F() [10/19]
yaze::cli::resources::TEST_F (ArgumentParserTest , DetectsFlags)
Definition at line 132 of file command_context_test.cc.
References yaze::cli::resources::ArgumentParser::HasFlag().
TEST_F() [11/19]
yaze::cli::resources::TEST_F (ArgumentParserTest , GetsPositionalArguments)
Definition at line 141 of file command_context_test.cc.
References yaze::cli::resources::ArgumentParser::GetPositional().
TEST_F() [12/19]
yaze::cli::resources::TEST_F (ArgumentParserTest , ValidatesRequiredArguments)
Definition at line 149 of file command_context_test.cc.
References yaze::cli::resources::ArgumentParser::RequireArgs().
TEST_F() [13/19]
yaze::cli::resources::TEST_F (ArgumentParserTest , HandlesMissingArguments)
Definition at line 160 of file command_context_test.cc.
References yaze::cli::resources::ArgumentParser::GetInt(), and yaze::cli::resources::ArgumentParser::GetString().
TEST_F() [14/19]
yaze::cli::resources::TEST_F (OutputFormatterTest , CreatesFromString)
Definition at line 177 of file command_context_test.cc.
References yaze::cli::resources::OutputFormatter::FromString().
TEST_F() [15/19]
yaze::cli::resources::TEST_F (OutputFormatterTest , GeneratesValidJson)
Definition at line 190 of file command_context_test.cc.
References yaze::cli::resources::OutputFormatter::FromString().
TEST_F() [16/19]
yaze::cli::resources::TEST_F (OutputFormatterTest , GeneratesValidText)
Definition at line 219 of file command_context_test.cc.
References yaze::cli::resources::OutputFormatter::FromString().
TEST_F() [17/19]
yaze::cli::resources::TEST_F (OutputFormatterTest , EscapesJsonStrings)
Definition at line 249 of file command_context_test.cc.
References yaze::cli::resources::OutputFormatter::FromString().
TEST_F() [18/19]
yaze::cli::resources::TEST_F (OutputFormatterTest , HandlesEmptyObjects)
Definition at line 267 of file command_context_test.cc.
References yaze::cli::resources::OutputFormatter::FromString().
TEST_F() [19/19]
yaze::cli::resources::TEST_F (OutputFormatterTest , HandlesEmptyArrays)
Definition at line 279 of file command_context_test.cc.
References yaze::cli::resources::OutputFormatter::FromString().