yaze: yaze::gui::canvas::CanvasUsageManager Class Reference
yaze::gui::canvas::CanvasUsageManager Class Reference
Global canvas usage tracker manager.
#include <canvas_usage_tracker.h>
Public Member Functions
void RegisterTracker (const std::string &canvas_id, std::shared_ptr< CanvasUsageTracker > tracker)
Register a canvas tracker.
std::shared_ptr< CanvasUsageTracker > GetTracker (const std::string &canvas_id)
Get tracker for canvas.
const std::unordered_map< std::string, std::shared_ptr< CanvasUsageTracker > > & GetAllTrackers () const
Get all trackers.
CanvasUsageStats GetGlobalStats () const
Get global usage statistics.
std::string ExportGlobalReport () const
Export global usage report.
void ClearAllTrackers ()
Clear all trackers.
Static Public Member Functions
static CanvasUsageManager & Get ()
Private Member Functions
CanvasUsageManager ()=default
~CanvasUsageManager ()=default
Private Attributes
std::unordered_map< std::string, std::shared_ptr< CanvasUsageTracker > > trackers_
Detailed Description
Global canvas usage tracker manager.
Definition at line 202 of file canvas_usage_tracker.h.
Constructor & Destructor Documentation
CanvasUsageManager()
yaze::gui::canvas::CanvasUsageManager::CanvasUsageManager () private default
~CanvasUsageManager()
yaze::gui::canvas::CanvasUsageManager::~CanvasUsageManager () private default
Member Function Documentation
Get()
CanvasUsageManager & yaze::gui::canvas::CanvasUsageManager::Get () static
Definition at line 347 of file canvas_usage_tracker.cc.
Referenced by yaze::gui::Canvas::InitializeEnhancedComponents().
RegisterTracker()
void yaze::gui::canvas::CanvasUsageManager::RegisterTracker (const std::string & canvas_id, std::shared_ptr< CanvasUsageTracker > tracker)
Register a canvas tracker.
Definition at line 352 of file canvas_usage_tracker.cc.
References LOG_DEBUG, and trackers_.
Referenced by yaze::gui::Canvas::InitializeEnhancedComponents().
GetTracker()
std::shared_ptr< CanvasUsageTracker > yaze::gui::canvas::CanvasUsageManager::GetTracker (const std::string & canvas_id)
Get tracker for canvas.
Definition at line 358 of file canvas_usage_tracker.cc.
References trackers_.
GetAllTrackers()
const std::unordered_map< std::string, std::shared_ptr< CanvasUsageTracker > > & yaze::gui::canvas::CanvasUsageManager::GetAllTrackers () const inline
Get all trackers.
Definition at line 221 of file canvas_usage_tracker.h.
References trackers_.
GetGlobalStats()
CanvasUsageStats yaze::gui::canvas::CanvasUsageManager::GetGlobalStats () const
Get global usage statistics.
Definition at line 366 of file canvas_usage_tracker.cc.
References yaze::gui::canvas::CanvasUsageStats::average_operation_time_ms, yaze::gui::canvas::CanvasUsageStats::context_menu_opens, yaze::gui::canvas::CanvasUsageStats::max_operation_time_ms, yaze::gui::canvas::CanvasUsageStats::modal_opens, yaze::gui::canvas::CanvasUsageStats::mode_changes, yaze::gui::canvas::CanvasUsageStats::mouse_clicks, yaze::gui::canvas::CanvasUsageStats::mouse_drags, yaze::gui::canvas::CanvasUsageStats::tool_changes, yaze::gui::canvas::CanvasUsageStats::total_operations, and trackers_.
Referenced by ExportGlobalReport().
ExportGlobalReport()
std::string yaze::gui::canvas::CanvasUsageManager::ExportGlobalReport () const
Export global usage report.
Definition at line 392 of file canvas_usage_tracker.cc.
References GetGlobalStats(), and trackers_.
ClearAllTrackers()
void yaze::gui::canvas::CanvasUsageManager::ClearAllTrackers ()
Clear all trackers.
Definition at line 419 of file canvas_usage_tracker.cc.
References LOG_DEBUG, and trackers_.
Member Data Documentation
trackers_
std::unordered_map<std::string, std::shared_ptr<CanvasUsageTracker> > yaze::gui::canvas::CanvasUsageManager::trackers_ private
Definition at line 242 of file canvas_usage_tracker.h.
Referenced by ClearAllTrackers(), ExportGlobalReport(), GetAllTrackers(), GetGlobalStats(), GetTracker(), and RegisterTracker().
The documentation for this class was generated from the following files:
src/app/gui/canvas/canvas_usage_tracker.h
src/app/gui/canvas/canvas_usage_tracker.cc