yaze: yaze::cli::agent Namespace Reference
yaze::cli::agent Namespace Reference
Namespaces
namespace anonymous_namespace{agent.cc}
namespace anonymous_namespace{conversation_test.cc}
namespace anonymous_namespace{conversational_agent_service.cc}
namespace anonymous_namespace{general_commands.cc}
namespace anonymous_namespace{gui_commands.cc}
namespace anonymous_namespace{hex_commands.cc}
namespace anonymous_namespace{learned_knowledge_service.cc}
namespace anonymous_namespace{palette_commands.cc}
namespace anonymous_namespace{proposal_executor.cc}
namespace anonymous_namespace{simple_chat_session.cc}
namespace anonymous_namespace{todo_manager.cc}
namespace anonymous_namespace{tool_commands.cc}
namespace anonymous_namespace{vim_mode.cc}
Classes
class AdvancedRouter
Advanced routing system for agent tool responses.
struct AgentConfig
class AgentPretraining
Pre-training system for AI agents.
struct ChatMessage
class ConversationalAgentService
class LearnedKnowledgeService
Manages persistent learned information across agent sessions.
class PromptManager
struct ProposalCreationRequest
struct ProposalCreationResult
class SimpleChatSession
Simple text-based chat session for AI agent interaction.
struct TodoItem
Represents a single TODO item for task management.
class TodoManager
Manages TODO lists for z3ed agent task execution.
class ToolDispatcher
class VimMode
Vim-style line editing for z3ed CLI chat.
Enumerations
enum class AgentOutputFormat { kFriendly , kCompact , kMarkdown , kJson }
enum class PromptMode { kStandard , kOracleOfSecrets , kCustom }
enum class VimModeType { NORMAL , INSERT , VISUAL , COMMAND_LINE }
Vim editing modes.
Functions
absl::Status HandleRunCommand (const std::vector< std::string > &args, Rom &rom)
absl::Status HandlePlanCommand (const std::vector< std::string > &args)
absl::Status HandleDiffCommand (Rom &rom, const std::vector< std::string > &args)
absl::Status HandleAcceptCommand (const std::vector< std::string > &args, Rom &rom)
absl::Status HandleTestCommand (const std::vector< std::string > &args)
absl::Status HandleGuiCommand (const std::vector< std::string > &args)
absl::Status HandleLearnCommand (const std::vector< std::string > &args={})
absl::Status HandleListCommand ()
absl::Status HandleCommitCommand (Rom &rom)
absl::Status HandleRevertCommand (Rom &rom)
absl::Status HandleDescribeCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleResourceListCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleResourceSearchCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleDungeonListSpritesCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleDungeonDescribeRoomCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleOverworldFindTileCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleOverworldDescribeMapCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleOverworldListWarpsCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleOverworldListSpritesCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleOverworldGetEntranceCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleOverworldTileStatsCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleMessageListCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleMessageReadCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleMessageSearchCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleGuiPlaceTileCommand (const std::vector< std::string > &arg_vec, Rom *rom_context=nullptr)
absl::Status HandleChatCommand (Rom &rom)
absl::Status HandleSimpleChatCommand (const std::vector< std::string > &, Rom *rom, bool quiet)
absl::Status HandleTestConversationCommand (const std::vector< std::string > &arg_vec)
absl::Status HandleHexRead (const std::vector< std::string > &args, Rom *rom_context=nullptr)
Read bytes from ROM at a specific address.
absl::Status HandleHexWrite (const std::vector< std::string > &args, Rom *rom_context=nullptr)
Write bytes to ROM at a specific address (creates proposal)
absl::Status HandleHexSearch (const std::vector< std::string > &args, Rom *rom_context=nullptr)
Search for a byte pattern in ROM.
absl::Status HandlePaletteGetColors (const std::vector< std::string > &args, Rom *rom_context=nullptr)
Get all colors from a specific palette.
absl::Status HandlePaletteSetColor (const std::vector< std::string > &args, Rom *rom_context=nullptr)
Set a specific color in a palette (creates proposal)
absl::Status HandlePaletteAnalyze (const std::vector< std::string > &args, Rom *rom_context=nullptr)
Analyze color usage and statistics for a palette or bitmap.
std::string HarnessAddress (const std::string &host, int port)
std::string JsonEscape (absl::string_view value)
std::string YamlQuote (absl::string_view value)
std::string FormatOptionalTime (const std::optional< absl::Time > &time)
std::string OptionalTimeToIso (const std::optional< absl::Time > &time)
std::string OptionalTimeToJson (const std::optional< absl::Time > &time)
std::string OptionalTimeToYaml (const std::optional< absl::Time > &time)
const char * TestRunStatusToString (TestRunStatus status)
bool IsTerminalStatus (TestRunStatus status)
std::optional< TestRunStatus > ParseStatusFilter (absl::string_view value)
std::optional< WidgetTypeFilter > ParseWidgetTypeFilter (absl::string_view value)
std::string TrimWhitespace (absl::string_view value)
bool IsInteractiveInput ()
std::string PromptWithDefault (const std::string &prompt, const std::string &default_value, bool allow_empty)
std::string PromptRequired (const std::string &prompt, const std::string &default_value)
int PromptInt (const std::string &prompt, int default_value, int min_value)
bool PromptYesNo (const std::string &prompt, bool default_value)
std::vector< std::string > ParseCommaSeparated (absl::string_view input)
bool ParseKeyValueEntry (const std::string &input, std::string *key, std::string *value)
absl::StatusOr< ProposalCreationResult > CreateProposalFromAgentResponse (const ProposalCreationRequest &request)
Enumeration Type Documentation
AgentOutputFormat
enum class yaze::cli::agent::AgentOutputFormat strong
Enumerator
kFriendly
kCompact
kMarkdown
kJson
Definition at line 55 of file conversational_agent_service.h.
PromptMode
enum class yaze::cli::agent::PromptMode strong
Enumerator
kStandard
kOracleOfSecrets
kCustom
Definition at line 11 of file prompt_manager.h.
VimModeType
enum class yaze::cli::agent::VimModeType strong
Vim editing modes.
Enumerator
NORMAL
INSERT
VISUAL
COMMAND_LINE
Definition at line 16 of file vim_mode.h.
Function Documentation
HandleRunCommand()
absl::Status yaze::cli::agent::HandleRunCommand (const std::vector< std::string > & args, Rom & rom)
Definition at line 184 of file general_commands.cc.
References yaze::cli::agent::ProposalCreationRequest::ai_provider, ASSIGN_OR_RETURN, yaze::cli::AgentResponse::commands, yaze::cli::CreateAIService(), CreateProposalFromAgentResponse(), yaze::cli::agent::ProposalCreationRequest::prompt, yaze::cli::agent::ProposalCreationRequest::response, RETURN_IF_ERROR, yaze::cli::agent::ProposalCreationRequest::rom, and yaze::cli::agent::ProposalCreationRequest::sandbox_label.
Referenced by yaze::cli::Agent::Run().
HandlePlanCommand()
absl::Status yaze::cli::agent::HandlePlanCommand (const std::vector< std::string > & args)
Definition at line 242 of file general_commands.cc.
References yaze::cli::CreateAIService(), yaze::cli::Tile16ProposalGenerator::GenerateFromCommands(), yaze::cli::ProposalRegistry::Instance(), and yaze::cli::Tile16ProposalGenerator::SaveProposal().
Referenced by yaze::cli::Agent::Run().
HandleDiffCommand()
absl::Status yaze::cli::agent::HandleDiffCommand (Rom & rom, const std::vector< std::string > & args)
Definition at line 285 of file general_commands.cc.
References yaze::cli::RomSandboxManager::ActiveSandbox(), yaze::Rom::filename(), yaze::cli::ProposalRegistry::Instance(), yaze::cli::RomSandboxManager::Instance(), yaze::Rom::is_loaded(), yaze::cli::ProposalRegistry::kAccepted, yaze::cli::ProposalRegistry::kPending, yaze::cli::ProposalRegistry::kRejected, and yaze::cli::RomDiff::Run().
Referenced by yaze::cli::Agent::Run().
HandleAcceptCommand()
absl::Status yaze::cli::agent::HandleAcceptCommand (const std::vector< std::string > & args, Rom & rom)
Definition at line 808 of file general_commands.cc.
References ASSIGN_OR_RETURN, yaze::RomLoadOptions::CliDefaults(), yaze::Rom::Expand(), yaze::Rom::filename(), yaze::cli::ProposalRegistry::Instance(), yaze::cli::RomSandboxManager::Instance(), yaze::cli::ProposalRegistry::kAccepted, yaze::Rom::LoadFromFile(), yaze::cli::RomSandboxManager::RemoveSandbox(), RETURN_IF_ERROR, yaze::Rom::SaveToFile(), yaze::Rom::size(), yaze::Rom::vector(), and yaze::Rom::WriteVector().
Referenced by yaze::cli::Agent::Run().
HandleTestCommand()
absl::Status yaze::cli::agent::HandleTestCommand (const std::vector< std::string > & args)
Definition at line 589 of file test_commands.cc.
Referenced by yaze::cli::Agent::Run().
HandleGuiCommand()
absl::Status yaze::cli::agent::HandleGuiCommand (const std::vector< std::string > & args)
Definition at line 351 of file gui_commands.cc.
Referenced by yaze::cli::Agent::Run().
HandleLearnCommand()
absl::Status yaze::cli::agent::HandleLearnCommand (const std::vector< std::string > & args = {})
Definition at line 402 of file general_commands.cc.
References yaze::cli::agent::LearnedKnowledgeService::ClearAll(), yaze::cli::agent::LearnedKnowledgeService::ExportToJSON(), yaze::cli::agent::LearnedKnowledgeService::GetAllPreferences(), yaze::cli::agent::LearnedKnowledgeService::GetAllProjects(), yaze::cli::agent::LearnedKnowledgeService::GetPreference(), yaze::cli::agent::LearnedKnowledgeService::GetRecentMemories(), yaze::cli::agent::LearnedKnowledgeService::GetStats(), yaze::cli::agent::LearnedKnowledgeService::ImportFromJSON(), yaze::cli::agent::LearnedKnowledgeService::Initialize(), yaze::cli::agent::LearnedKnowledgeService::Stats::preference_count, and yaze::cli::agent::LearnedKnowledgeService::SetPreference().
Referenced by yaze::cli::Agent::Run().
HandleListCommand()
absl::Status yaze::cli::agent::HandleListCommand ()
Definition at line 566 of file general_commands.cc.
References yaze::cli::ProposalRegistry::Instance(), yaze::cli::ProposalRegistry::kAccepted, yaze::cli::ProposalRegistry::kPending, and yaze::cli::ProposalRegistry::kRejected.
Referenced by yaze::cli::Agent::Run().
HandleCommitCommand()
absl::Status yaze::cli::agent::HandleCommitCommand (Rom & rom)
Definition at line 607 of file general_commands.cc.
References yaze::Rom::is_loaded(), and yaze::Rom::SaveToFile().
Referenced by yaze::cli::Agent::Run().
HandleRevertCommand()
absl::Status yaze::cli::agent::HandleRevertCommand (Rom & rom)
Definition at line 620 of file general_commands.cc.
References yaze::Rom::filename(), yaze::Rom::is_loaded(), and yaze::Rom::LoadFromFile().
Referenced by yaze::cli::Agent::Run().
HandleDescribeCommand()
absl::Status yaze::cli::agent::HandleDescribeCommand (const std::vector< std::string > & arg_vec)
Definition at line 633 of file general_commands.cc.
References ASSIGN_OR_RETURN, and yaze::cli::ResourceCatalog::Instance().
Referenced by yaze::cli::Agent::Run().
HandleResourceListCommand()
absl::Status yaze::cli::agent::HandleResourceListCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 73 of file tool_commands.cc.
References yaze::cli::ResourceContextBuilder::GetLabels(), yaze::core::YazeProject::InitializeEmbeddedLabels(), yaze::Rom::is_loaded(), yaze::core::ResourceLabelManager::labels_, yaze::core::ResourceLabelManager::labels_loaded_, yaze::Rom::resource_label(), yaze::core::YazeProject::resource_labels, and yaze::core::YazeProject::use_embedded_labels.
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and yaze::cli::Agent::Run().
HandleResourceSearchCommand()
absl::Status yaze::cli::agent::HandleResourceSearchCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 158 of file tool_commands.cc.
References yaze::cli::ResourceContextBuilder::GetLabels(), yaze::core::YazeProject::InitializeEmbeddedLabels(), yaze::Rom::is_loaded(), yaze::core::ResourceLabelManager::labels_, yaze::core::ResourceLabelManager::labels_loaded_, yaze::Rom::resource_label(), and yaze::core::YazeProject::resource_labels.
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and yaze::cli::Agent::Run().
HandleDungeonListSpritesCommand()
absl::Status yaze::cli::agent::HandleDungeonListSpritesCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 346 of file tool_commands.cc.
References HandleDungeonListSpritesCommand(), yaze::Rom::is_loaded(), and yaze::zelda3::LoadRoomFromRom().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), HandleDungeonListSpritesCommand(), and yaze::cli::Agent::Run().
HandleDungeonDescribeRoomCommand()
absl::Status yaze::cli::agent::HandleDungeonDescribeRoomCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 421 of file tool_commands.cc.
References ASSIGN_OR_RETURN, HandleDungeonDescribeRoomCommand(), yaze::Rom::is_loaded(), yaze::zelda3::kRoomNames, and yaze::zelda3::LoadRoomFromRom().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), HandleDungeonDescribeRoomCommand(), and yaze::cli::Agent::Run().
HandleOverworldFindTileCommand()
absl::Status yaze::cli::agent::HandleOverworldFindTileCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 651 of file tool_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::FindTileMatches(), HandleOverworldFindTileCommand(), yaze::cli::overworld::InferWorldFromMapId(), yaze::Rom::is_loaded(), yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::Load(), yaze::cli::overworld::TileSearchOptions::map_id, yaze::cli::overworld::ParseNumeric(), yaze::cli::overworld::ParseWorldSpecifier(), yaze::cli::overworld::TileSearchOptions::world, and yaze::cli::overworld::WorldName().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), HandleOverworldFindTileCommand(), and yaze::cli::Agent::Run().
HandleOverworldDescribeMapCommand()
absl::Status yaze::cli::agent::HandleOverworldDescribeMapCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 819 of file tool_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::BuildMapSummary(), HandleOverworldDescribeMapCommand(), yaze::Rom::is_loaded(), yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::Load(), yaze::cli::overworld::ParseNumeric(), and yaze::cli::overworld::WorldName().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), HandleOverworldDescribeMapCommand(), and yaze::cli::Agent::Run().
HandleOverworldListWarpsCommand()
absl::Status yaze::cli::agent::HandleOverworldListWarpsCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 981 of file tool_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::CollectWarpEntries(), HandleOverworldListWarpsCommand(), yaze::cli::overworld::InferWorldFromMapId(), yaze::Rom::is_loaded(), yaze::cli::overworld::kEntrance, yaze::cli::overworld::kExit, yaze::cli::overworld::kHole, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::Load(), yaze::cli::overworld::WarpQuery::map_id, yaze::cli::overworld::ParseNumeric(), yaze::cli::overworld::ParseWorldSpecifier(), yaze::cli::overworld::WarpQuery::type, yaze::cli::overworld::WarpTypeName(), yaze::cli::overworld::WarpQuery::world, and yaze::cli::overworld::WorldName().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), HandleOverworldListWarpsCommand(), and yaze::cli::Agent::Run().
HandleOverworldListSpritesCommand()
absl::Status yaze::cli::agent::HandleOverworldListSpritesCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 1189 of file tool_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::CollectOverworldSprites(), HandleOverworldListSpritesCommand(), yaze::Rom::is_loaded(), yaze::zelda3::Overworld::Load(), yaze::cli::overworld::SpriteQuery::map_id, yaze::cli::overworld::ParseNumeric(), yaze::cli::overworld::ParseWorldSpecifier(), yaze::cli::overworld::SpriteQuery::world, and yaze::cli::overworld::WorldName().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and HandleOverworldListSpritesCommand().
HandleOverworldGetEntranceCommand()
absl::Status yaze::cli::agent::HandleOverworldGetEntranceCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 1296 of file tool_commands.cc.
References ASSIGN_OR_RETURN, yaze::cli::overworld::GetEntranceDetails(), HandleOverworldGetEntranceCommand(), yaze::Rom::is_loaded(), yaze::zelda3::Overworld::Load(), yaze::cli::overworld::ParseNumeric(), and yaze::cli::overworld::WorldName().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and HandleOverworldGetEntranceCommand().
HandleOverworldTileStatsCommand()
absl::Status yaze::cli::agent::HandleOverworldTileStatsCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 1394 of file tool_commands.cc.
References yaze::cli::overworld::AnalyzeTileUsage(), ASSIGN_OR_RETURN, HandleOverworldTileStatsCommand(), yaze::Rom::is_loaded(), yaze::zelda3::Overworld::Load(), yaze::cli::overworld::TileSearchOptions::map_id, yaze::cli::overworld::ParseNumeric(), yaze::cli::overworld::ParseWorldSpecifier(), yaze::cli::overworld::TileSearchOptions::world, and yaze::cli::overworld::WorldName().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and HandleOverworldTileStatsCommand().
HandleMessageListCommand()
absl::Status yaze::cli::agent::HandleMessageListCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 1524 of file tool_commands.cc.
References HandleMessageListCommand(), and yaze::cli::message::HandleMessageListCommand().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and HandleMessageListCommand().
HandleMessageReadCommand()
absl::Status yaze::cli::agent::HandleMessageReadCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 1529 of file tool_commands.cc.
References HandleMessageReadCommand(), and yaze::cli::message::HandleMessageReadCommand().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and HandleMessageReadCommand().
HandleMessageSearchCommand()
absl::Status yaze::cli::agent::HandleMessageSearchCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 1534 of file tool_commands.cc.
References HandleMessageSearchCommand(), and yaze::cli::message::HandleMessageSearchCommand().
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch(), and HandleMessageSearchCommand().
HandleGuiPlaceTileCommand()
absl::Status yaze::cli::agent::HandleGuiPlaceTileCommand (const std::vector< std::string > & arg_vec, Rom * rom_context = nullptr)
Definition at line 22 of file gui_tool_commands.cc.
References yaze::cli::gui::GuiActionGenerator::GenerateTestScript(), yaze::cli::ai::kPlaceTile, yaze::cli::ai::kSaveTile, yaze::cli::ai::kSelectTile, and yaze::cli::ai::AIAction::parameters.
Referenced by yaze::cli::agent::ToolDispatcher::Dispatch().
HandleChatCommand()
absl::Status yaze::cli::agent::HandleChatCommand (Rom & rom)
Definition at line 690 of file general_commands.cc.
References RETURN_IF_ERROR, and yaze::cli::tui::ChatTUI::Run().
Referenced by yaze::cli::Agent::Run().
HandleSimpleChatCommand()
absl::Status yaze::cli::agent::HandleSimpleChatCommand (const std::vector< std::string > & arg_vec, Rom * rom, bool quiet)
Definition at line 701 of file general_commands.cc.
References yaze::cli::agent::AgentConfig::enable_vim_mode, kCompact, kFriendly, kJson, kMarkdown, yaze::cli::agent::AgentConfig::output_format, RETURN_IF_ERROR, yaze::cli::agent::SimpleChatSession::RunInteractive(), yaze::cli::agent::SimpleChatSession::SendAndWaitForResponse(), yaze::cli::agent::SimpleChatSession::SetConfig(), yaze::cli::agent::SimpleChatSession::SetRomContext(), and yaze::cli::agent::AgentConfig::verbose.
Referenced by yaze::cli::Agent::Run().
HandleTestConversationCommand()
absl::Status yaze::cli::agent::HandleTestConversationCommand (const std::vector< std::string > & arg_vec)
Definition at line 335 of file conversation_test.cc.
References yaze::core::YazeProject::InitializeEmbeddedLabels(), yaze::core::ResourceLabelManager::labels_, yaze::core::ResourceLabelManager::labels_loaded_, yaze::Rom::resource_label(), yaze::core::YazeProject::resource_labels, yaze::cli::agent::ConversationalAgentService::SetRomContext(), yaze::Rom::title(), and yaze::core::YazeProject::use_embedded_labels.
Referenced by yaze::cli::Agent::Run().
HandleHexRead()
absl::Status yaze::cli::agent::HandleHexRead (const std::vector< std::string > & args, Rom * rom_context = nullptr)
Read bytes from ROM at a specific address.
Parameters
args Command arguments: [address, length, format]
rom_context ROM instance to read from
Returns
absl::Status Result of the operation
Example: hex-read –address=0x1C800 –length=16 –format=both
Definition at line 88 of file hex_commands.cc.
References yaze::Rom::data(), yaze::Rom::is_loaded(), and yaze::Rom::size().
Referenced by yaze::cli::CommandPaletteComponent::Render(), and yaze::cli::Agent::Run().
HandleHexWrite()
absl::Status yaze::cli::agent::HandleHexWrite (const std::vector< std::string > & args, Rom * rom_context = nullptr)
Write bytes to ROM at a specific address (creates proposal)
Parameters
args Command arguments: [address, data]
rom_context ROM instance to write to
Returns
absl::Status Result of the operation
Example: hex-write –address=0x1C800 –data="FF 00 12 34"
Definition at line 138 of file hex_commands.cc.
References yaze::Rom::is_loaded(), yaze::Rom::size(), and yaze::Rom::WriteByte().
Referenced by yaze::cli::CommandPaletteComponent::Render(), and yaze::cli::Agent::Run().
HandleHexSearch()
absl::Status yaze::cli::agent::HandleHexSearch (const std::vector< std::string > & args, Rom * rom_context = nullptr)
Search for a byte pattern in ROM.
Parameters
args Command arguments: [pattern, start_address, end_address]
rom_context ROM instance to search in
Returns
absl::Status Result of the operation
Example: hex-search –pattern="FF 00 ?? 12" –start=0x00000
Definition at line 210 of file hex_commands.cc.
References yaze::Rom::data(), yaze::Rom::is_loaded(), and yaze::Rom::size().
Referenced by yaze::cli::CommandPaletteComponent::Render(), and yaze::cli::Agent::Run().
HandlePaletteGetColors()
absl::Status yaze::cli::agent::HandlePaletteGetColors (const std::vector< std::string > & args, Rom * rom_context = nullptr)
Get all colors from a specific palette.
Parameters
args Command arguments: [group, palette, format]
rom_context ROM instance to read from
Returns
absl::Status Result of the operation
Example: palette-get-colors –group=0 –palette=0 –format=hex
Definition at line 81 of file palette_commands.cc.
References yaze::Rom::is_loaded(), yaze::Rom::ReadWord(), and yaze::Rom::size().
Referenced by yaze::cli::CommandPaletteComponent::Render(), and yaze::cli::Agent::Run().
HandlePaletteSetColor()
absl::Status yaze::cli::agent::HandlePaletteSetColor (const std::vector< std::string > & args, Rom * rom_context = nullptr)
Set a specific color in a palette (creates proposal)
Parameters
args Command arguments: [group, palette, color_index, color]
rom_context ROM instance to modify
Returns
absl::Status Result of the operation
Example: palette-set-color –group=0 –palette=0 –index=5 –color=FF0000
Definition at line 156 of file palette_commands.cc.
References yaze::Rom::is_loaded(), yaze::Rom::ReadWord(), yaze::Rom::size(), and yaze::Rom::WriteWord().
Referenced by yaze::cli::CommandPaletteComponent::Render(), and yaze::cli::Agent::Run().
HandlePaletteAnalyze()
absl::Status yaze::cli::agent::HandlePaletteAnalyze (const std::vector< std::string > & args, Rom * rom_context = nullptr)
Analyze color usage and statistics for a palette or bitmap.
Parameters
args Command arguments: [target_type, target_id]
rom_context ROM instance to analyze
Returns
absl::Status Result of the operation
Example: palette-analyze –type=palette –id=0
Definition at line 243 of file palette_commands.cc.
References yaze::Rom::is_loaded(), and yaze::Rom::ReadWord().
Referenced by yaze::cli::CommandPaletteComponent::Render(), and yaze::cli::Agent::Run().
HarnessAddress()
std::string yaze::cli::agent::HarnessAddress (const std::string & host, int port)
Definition at line 12 of file common.cc.
Referenced by yaze::cli::agent::anonymous_namespace{gui_commands.cc}::HandleGuiDiscoverCommand().
JsonEscape()
std::string yaze::cli::agent::JsonEscape (absl::string_view value)
Definition at line 16 of file common.cc.
Referenced by yaze::cli::agent::anonymous_namespace{gui_commands.cc}::HandleGuiDiscoverCommand(), and OptionalTimeToJson().
YamlQuote()
std::string yaze::cli::agent::YamlQuote (absl::string_view value)
Definition at line 53 of file common.cc.
FormatOptionalTime()
std::string yaze::cli::agent::FormatOptionalTime (const std::optional< absl::Time > & time)
Definition at line 59 of file common.cc.
OptionalTimeToIso()
std::string yaze::cli::agent::OptionalTimeToIso (const std::optional< absl::Time > & time)
Definition at line 66 of file common.cc.
Referenced by OptionalTimeToJson(), and OptionalTimeToYaml().
OptionalTimeToJson()
std::string yaze::cli::agent::OptionalTimeToJson (const std::optional< absl::Time > & time)
Definition at line 73 of file common.cc.
References JsonEscape(), and OptionalTimeToIso().
OptionalTimeToYaml()
std::string yaze::cli::agent::OptionalTimeToYaml (const std::optional< absl::Time > & time)
Definition at line 81 of file common.cc.
References OptionalTimeToIso().
TestRunStatusToString()
const char * yaze::cli::agent::TestRunStatusToString (TestRunStatus status)
Definition at line 89 of file common.cc.
References yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kQueued, yaze::cli::kRunning, yaze::cli::kTimeout, and yaze::cli::kUnknown.
IsTerminalStatus()
bool yaze::cli::agent::IsTerminalStatus (TestRunStatus status)
Definition at line 107 of file common.cc.
References yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kQueued, yaze::cli::kRunning, yaze::cli::kTimeout, and yaze::cli::kUnknown.
ParseStatusFilter()
std::optional< TestRunStatus > yaze::cli::agent::ParseStatusFilter (absl::string_view value)
Definition at line 121 of file common.cc.
References yaze::cli::kFailed, yaze::cli::kPassed, yaze::cli::kQueued, yaze::cli::kRunning, yaze::cli::kTimeout, and yaze::cli::kUnknown.
ParseWidgetTypeFilter()
std::optional< WidgetTypeFilter > yaze::cli::agent::ParseWidgetTypeFilter (absl::string_view value)
Definition at line 132 of file common.cc.
References yaze::cli::kAll, yaze::cli::kButton, yaze::cli::kCanvas, yaze::cli::kCheckbox, yaze::cli::kInput, yaze::cli::kMenu, yaze::cli::kOther, yaze::cli::kSelectable, yaze::cli::kSlider, yaze::cli::kTab, and yaze::cli::kUnspecified.
Referenced by yaze::cli::agent::anonymous_namespace{gui_commands.cc}::HandleGuiDiscoverCommand().
TrimWhitespace()
std::string yaze::cli::agent::TrimWhitespace (absl::string_view value)
Definition at line 22 of file test_common.cc.
Referenced by yaze::cli::agent::anonymous_namespace{conversational_agent_service.cc}::CreateMessage(), ParseCommaSeparated(), ParseKeyValueEntry(), PromptWithDefault(), and PromptYesNo().
IsInteractiveInput()
bool yaze::cli::agent::IsInteractiveInput ()
Definition at line 26 of file test_common.cc.
PromptWithDefault()
std::string yaze::cli::agent::PromptWithDefault (const std::string & prompt, const std::string & default_value, bool allow_empty)
Definition at line 34 of file test_common.cc.
References TrimWhitespace().
Referenced by PromptInt(), and PromptRequired().
PromptRequired()
std::string yaze::cli::agent::PromptRequired (const std::string & prompt, const std::string & default_value)
Definition at line 63 of file test_common.cc.
References PromptWithDefault().
PromptInt()
int yaze::cli::agent::PromptInt (const std::string & prompt, int default_value, int min_value)
Definition at line 68 of file test_common.cc.
References PromptWithDefault().
PromptYesNo()
bool yaze::cli::agent::PromptYesNo (const std::string & prompt, bool default_value)
Definition at line 83 of file test_common.cc.
References TrimWhitespace().
ParseCommaSeparated()
std::vector< std::string > yaze::cli::agent::ParseCommaSeparated (absl::string_view input)
Definition at line 107 of file test_common.cc.
References TrimWhitespace().
ParseKeyValueEntry()
bool yaze::cli::agent::ParseKeyValueEntry (const std::string & input, std::string * key, std::string * value)
Definition at line 118 of file test_common.cc.
References equals(), and TrimWhitespace().
CreateProposalFromAgentResponse()
absl::StatusOr< ProposalCreationResult > yaze::cli::agent::CreateProposalFromAgentResponse (const ProposalCreationRequest & request)
Definition at line 37 of file proposal_executor.cc.
References yaze::cli::agent::ProposalCreationRequest::ai_provider, yaze::cli::Tile16ProposalGenerator::ApplyProposal(), ASSIGN_OR_RETURN, yaze::cli::agent::ProposalCreationResult::change_count, yaze::cli::AgentResponse::commands, yaze::cli::RomSandboxManager::CreateSandbox(), yaze::cli::agent::ProposalCreationResult::executed_commands, yaze::cli::Tile16ProposalGenerator::GenerateFromCommands(), yaze::cli::ProposalRegistry::Instance(), yaze::cli::RomSandboxManager::Instance(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), yaze::cli::agent::ProposalCreationResult::metadata, yaze::cli::agent::ProposalCreationRequest::prompt, yaze::cli::agent::ProposalCreationResult::proposal_json_path, yaze::cli::AgentResponse::reasoning, yaze::cli::agent::ProposalCreationRequest::response, RETURN_IF_ERROR, yaze::cli::agent::ProposalCreationRequest::rom, yaze::cli::agent::ProposalCreationRequest::sandbox_label, yaze::cli::Tile16ProposalGenerator::SaveProposal(), yaze::Rom::SaveToFile(), yaze::cli::AgentResponse::text_response, and yaze::cli::AgentResponse::tool_calls.
Referenced by HandleRunCommand(), and yaze::cli::agent::ConversationalAgentService::SendMessage().