yaze: yaze::editor::OverworldEditor Class Reference
yaze::editor::OverworldEditor Class Reference
Manipulates the Overworld and OverworldMap data in a Rom.
#include <overworld_editor.h>
Classes
struct ScratchSpaceSlot
Public Member Functions
OverworldEditor (Rom *rom)
void Initialize (gfx::IRenderer *renderer, Rom *rom)
void Initialize () override
absl::Status Load () override
absl::Status Update () final
absl::Status Undo () override
absl::Status Redo () override
absl::Status Cut () override
absl::Status Copy () override
absl::Status Paste () override
absl::Status Find () override
absl::Status Save () override
absl::Status Clear () override
zelda3::Overworld & overworld ()
absl::Status ApplyZSCustomOverworldASM (int target_version)
Apply ZSCustomOverworld ASM patch to upgrade ROM version.
absl::Status UpdateROMVersionMarkers (int target_version)
Update ROM version markers and feature flags after ASM patching.
int jump_to_tab ()
bool IsRomLoaded () const override
std::string GetRomStatus () const override
void set_current_map (int map_id)
absl::Status LoadGraphics ()
Load the Bitmap objects for each OverworldMap.
Public Member Functions inherited from yaze::editor::Editor
Editor ()=default
virtual ~Editor ()=default
EditorType type () const
void set_context (EditorContext *context)
bool * active ()
void set_active (bool active)
Public Attributes
int jump_to_tab_ = -1
Private Types
enum class EditingMode { MOUSE , DRAW_TILE }
enum class EntityEditMode {
NONE , ENTRANCES , EXITS , ITEMS ,
SPRITES , TRANSPORTS , MUSIC
}
enum OverworldProperty {
LW_AREA_GFX , DW_AREA_GFX , LW_AREA_PAL , DW_AREA_PAL ,
LW_SPR_GFX_PART1 , LW_SPR_GFX_PART2 , DW_SPR_GFX_PART1 , DW_SPR_GFX_PART2 ,
LW_SPR_PAL_PART1 , LW_SPR_PAL_PART2 , DW_SPR_PAL_PART1 , DW_SPR_PAL_PART2
}
Private Member Functions
void DrawFullscreenCanvas ()
void DrawToolset ()
void RefreshChildMap (int map_index)
void RefreshOverworldMap ()
void RefreshOverworldMapOnDemand (int map_index)
On-demand map refresh that only updates what's actually needed.
void RefreshChildMapOnDemand (int map_index)
On-demand child map refresh with selective updates.
void RefreshMultiAreaMapsSafely (int map_index, zelda3::OverworldMap *map)
Safely refresh multi-area maps without recursion.
absl::Status RefreshMapPalette ()
void RefreshMapProperties ()
absl::Status RefreshTile16Blockset ()
void ForceRefreshGraphics (int map_index)
void RefreshSiblingMapGraphics (int map_index, bool include_self=false)
void DrawOverworldMaps ()
void DrawOverworldEdits ()
void RenderUpdatedMapBitmap (const ImVec2 &click_position, const std::vector< uint8_t > &tile_data)
void CheckForOverworldEdits ()
Check for changes to the overworld map.
void CheckForSelectRectangle ()
Draw and create the tile16 IDs that are currently selected.
absl::Status CheckForCurrentMap ()
Check for changes to the overworld map. Calls RefreshOverworldMap and RefreshTile16Blockset on the current map if it is modified and is actively being edited.
void CheckForMousePan ()
void DrawOverworldCanvas ()
absl::Status DrawTile16Selector ()
void DrawTile8Selector ()
absl::Status DrawAreaGraphics ()
void UpdateBlocksetSelectorState ()
absl::Status LoadSpriteGraphics ()
void ProcessDeferredTextures ()
Create textures for deferred map bitmaps on demand.
void EnsureMapTexture (int map_index)
Ensure a specific map has its texture created.
void DrawOverworldProperties ()
void HandleMapInteraction ()
void HandleOverworldPan ()
void HandleOverworldZoom ()
void ResetOverworldView ()
void CenterOverworldView ()
void SetupCanvasAutomation ()
gui::Canvas * GetOverworldCanvas ()
bool AutomationSetTile (int x, int y, int tile_id)
int AutomationGetTile (int x, int y)
void ScrollBlocksetCanvasToCurrentTile ()
Scroll the blockset canvas to show the current selected tile16.
absl::Status DrawScratchSpace ()
absl::Status SaveCurrentSelectionToScratch (int slot)
absl::Status LoadScratchToSelection (int slot)
absl::Status ClearScratchSpace (int slot)
void DrawScratchSpaceEdits ()
void DrawScratchSpacePattern ()
void DrawScratchSpaceSelection ()
void UpdateScratchBitmapTile (int tile_x, int tile_y, int tile_id, int slot=-1)
absl::Status UpdateUsageStats ()
void DrawUsageGrid ()
void DrawDebugWindow ()
Private Attributes
std::vector< int > selected_tile16_ids_
EditingMode current_mode = EditingMode::DRAW_TILE
EditingMode previous_mode = EditingMode::DRAW_TILE
EntityEditMode entity_edit_mode_ = EntityEditMode::NONE
int current_world_ = 0
int current_map_ = 0
int current_parent_ = 0
int current_entrance_id_ = 0
int current_exit_id_ = 0
int current_item_id_ = 0
int current_sprite_id_ = 0
int current_blockset_ = 0
int game_state_ = 1
int current_tile16_ = 0
int selected_entrance_ = 0
int selected_usage_map_ = 0xFFFF
bool all_gfx_loaded_ = false
bool map_blockset_loaded_ = false
bool selected_tile_loaded_ = false
bool show_tile16_editor_ = false
bool show_gfx_group_editor_ = false
bool show_properties_editor_ = false
bool overworld_canvas_fullscreen_ = false
bool middle_mouse_dragging_ = false
bool is_dragging_entity_ = false
bool current_map_lock_ = false
bool show_custom_bg_color_editor_ = false
bool show_overlay_editor_ = false
bool use_area_specific_bg_color_ = false
bool show_map_properties_panel_ = false
bool show_overlay_preview_ = false
bool show_tile16_selector_ = false
bool show_tile8_selector_ = false
bool show_area_gfx_ = false
bool show_scratch_ = false
bool show_gfx_groups_ = false
bool show_usage_stats_ = false
bool show_v3_settings_ = false
std::unique_ptr< MapPropertiesSystem > map_properties_system_
std::unique_ptr< OverworldEntityRenderer > entity_renderer_
std::array< ScratchSpaceSlot, 4 > scratch_spaces_
int current_scratch_slot_ = 0
gfx::Tilemap tile16_blockset_
Rom * rom_
gfx::IRenderer * renderer_
Tile16Editor tile16_editor_ {rom_, &tile16_blockset_}
GfxGroupEditor gfx_group_editor_
PaletteEditor palette_editor_
gfx::SnesPalette palette_
gfx::Bitmap selected_tile_bmp_
gfx::Bitmap tile16_blockset_bmp_
gfx::Bitmap current_gfx_bmp_
gfx::Bitmap all_gfx_bmp
std::array< gfx::Bitmap, zelda3::kNumOverworldMaps > maps_bmp_
gfx::BitmapTable current_graphics_set_
std::vector< gfx::Bitmap > sprite_previews_
zelda3::Overworld overworld_ {rom_}
zelda3::OverworldBlockset refresh_blockset_
zelda3::Sprite current_sprite_
zelda3::OverworldEntrance current_entrance_
zelda3::OverworldExit current_exit_
zelda3::OverworldItem current_item_
zelda3::OverworldEntranceTileTypes entrance_tiletypes_ = {}
zelda3::GameEntity * current_entity_ = nullptr
zelda3::GameEntity * dragged_entity_ = nullptr
gui::Canvas ow_map_canvas_
gui::Canvas current_gfx_canvas_
gui::Canvas blockset_canvas_
std::unique_ptr< gui::TileSelectorWidget > blockset_selector_
gui::Canvas graphics_bin_canvas_
gui::Canvas properties_canvas_
gui::Canvas scratch_canvas_ {"ScratchSpace", ImVec2(320, 480), gui::CanvasGridSize::k32x32}
absl::Status status_
Additional Inherited Members
Protected Member Functions inherited from yaze::editor::Editor
std::string MakeCardTitle (const std::string &base_title) const
template<typename T >
absl::StatusOr< T > SafeRomAccess (std::function< T()> accessor, const std::string &operation="") const
Protected Attributes inherited from yaze::editor::Editor
bool active_ = false
EditorType type_
EditorContext * context_ = nullptr
Static Protected Attributes inherited from yaze::gfx::GfxContext
static std::unordered_map< uint8_t, gfx::Paletteset > palettesets_
Detailed Description
Manipulates the Overworld and OverworldMap data in a Rom.
The OverworldEditor class is responsible for managing the editing and manipulation of the overworld in a game. The user can drag and drop tiles, modify OverworldEntrance, OverworldExit, Sprite, and OverworldItem as well as change the gfx and palettes used in each overworld map.
The Overworld itself is a series of bitmap images which exist inside each OverworldMap object. The drawing of the overworld is done using the Canvas class in conjunction with these underlying Bitmap objects.
Provides access to the GfxGroupEditor and Tile16Editor through popup windows.
Definition at line 64 of file overworld_editor.h.
Member Enumeration Documentation
EditingMode
enum class yaze::editor::OverworldEditor::EditingMode strong private
Enumerator
MOUSE
DRAW_TILE
Definition at line 232 of file overworld_editor.h.
EntityEditMode
enum class yaze::editor::OverworldEditor::EntityEditMode strong private
Enumerator
NONE
ENTRANCES
EXITS
ITEMS
SPRITES
TRANSPORTS
MUSIC
Definition at line 241 of file overworld_editor.h.
OverworldProperty
enum yaze::editor::OverworldEditor::OverworldProperty private
Enumerator
LW_AREA_GFX
DW_AREA_GFX
LW_AREA_PAL
DW_AREA_PAL
LW_SPR_GFX_PART1
LW_SPR_GFX_PART2
DW_SPR_GFX_PART1
DW_SPR_GFX_PART2
LW_SPR_PAL_PART1
LW_SPR_PAL_PART2
DW_SPR_PAL_PART1
DW_SPR_PAL_PART2
Definition at line 253 of file overworld_editor.h.
Constructor & Destructor Documentation
OverworldEditor()
yaze::editor::OverworldEditor::OverworldEditor (Rom * rom) inline explicit
Definition at line 66 of file overworld_editor.h.
References gfx_group_editor_, yaze::editor::kOverworld, yaze::editor::GfxGroupEditor::set_rom(), and yaze::editor::Editor::type_.
Member Function Documentation
Initialize() [1/2]
void yaze::editor::OverworldEditor::Initialize (gfx::IRenderer * renderer, Rom * rom)
Referenced by yaze::editor::EditorManager::LoadAssets().
Initialize() [2/2]
void yaze::editor::OverworldEditor::Initialize () override virtual
Implements yaze::editor::Editor.
Definition at line 49 of file overworld_editor.cc.
References entity_renderer_, ForceRefreshGraphics(), yaze::gui::EditorCardManager::Get(), ICON_MD_ANALYTICS, ICON_MD_DRAW, ICON_MD_FOLDER, ICON_MD_GRID_3X3, ICON_MD_GRID_ON, ICON_MD_IMAGE, ICON_MD_SETTINGS, map_properties_system_, maps_bmp_, overworld_, ow_map_canvas_, RefreshMapPalette(), RefreshMapProperties(), RefreshOverworldMap(), RefreshTile16Blockset(), rom_, SetupCanvasAutomation(), show_area_gfx_, show_gfx_groups_, show_scratch_, show_tile16_selector_, show_tile8_selector_, show_usage_stats_, show_v3_settings_, and sprite_previews_.
Load()
absl::Status yaze::editor::OverworldEditor::Load () override virtual
Implements yaze::editor::Editor.
Definition at line 150 of file overworld_editor.cc.
References all_gfx_loaded_, ASSIGN_OR_RETURN, current_gfx_bmp_, entrance_tiletypes_, yaze::editor::Tile16Editor::Initialize(), yaze::Rom::is_loaded(), yaze::zelda3::LoadEntranceTileTypes(), LoadGraphics(), LOG_DEBUG, yaze::zelda3::Overworld::mutable_all_tiles_types(), overworld_, palette_, RefreshOverworldMap(), RefreshTile16Blockset(), RETURN_IF_ERROR, rom_, yaze::editor::Tile16Editor::set_on_changes_committed(), yaze::editor::Tile16Editor::set_palette(), yaze::editor::Tile16Editor::set_rom(), tile16_blockset_bmp_, and tile16_editor_.
Referenced by DrawToolset(), and yaze::editor::EditorManager::LoadAssets().
Update()
absl::Status yaze::editor::OverworldEditor::Update () final virtual
Implements yaze::editor::Editor.
Definition at line 184 of file overworld_editor.cc.
References yaze::gui::EditorCard::Begin(), yaze::gui::BeginChildWithScrollbar(), yaze::gui::BeginPadding(), yaze::gui::CenterText(), current_map_, DrawAreaGraphics(), DrawFullscreenCanvas(), DrawOverworldCanvas(), DrawScratchSpace(), DrawTile16Selector(), DrawTile8Selector(), DrawToolset(), yaze::gui::EditorCard::End(), yaze::gui::EndNoPadding(), yaze::gui::EditorCard::Floating, gfx_group_editor_, ICON_MD_ANALYTICS, ICON_MD_BRUSH, ICON_MD_COLLECTIONS, ICON_MD_FORMAT_COLOR_FILL, ICON_MD_GRID_3X3, ICON_MD_GRID_4X4, ICON_MD_GRID_ON, ICON_MD_IMAGE, ICON_MD_LAYERS, ICON_MD_TUNE, yaze::Rom::is_loaded(), yaze::zelda3::Overworld::is_loaded(), yaze::editor::Editor::MakeCardTitle(), map_properties_system_, overworld_, overworld_canvas_fullscreen_, ProcessDeferredTextures(), yaze::gui::EditorCard::Right, rom_, yaze::gui::EditorCard::SetDefaultSize(), yaze::gui::EditorCard::SetPosition(), show_area_gfx_, show_custom_bg_color_editor_, show_gfx_groups_, show_map_properties_panel_, show_overlay_editor_, show_scratch_, show_tile16_editor_, show_tile16_selector_, show_tile8_selector_, show_usage_stats_, status_, tile16_editor_, yaze::editor::GfxGroupEditor::Update(), yaze::editor::Tile16Editor::Update(), UpdateUsageStats(), and yaze::gui::VerticalSpacing().
Undo()
absl::Status yaze::editor::OverworldEditor::Undo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 76 of file overworld_editor.h.
Redo()
absl::Status yaze::editor::OverworldEditor::Redo () inline override virtual
Implements yaze::editor::Editor.
Definition at line 77 of file overworld_editor.h.
Cut()
absl::Status yaze::editor::OverworldEditor::Cut () inline override virtual
Implements yaze::editor::Editor.
Definition at line 78 of file overworld_editor.h.
Copy()
absl::Status yaze::editor::OverworldEditor::Copy () override virtual
Implements yaze::editor::Editor.
Definition at line 938 of file overworld_editor.cc.
References yaze::editor::Editor::context_, current_map_, current_tile16_, current_world_, yaze::zelda3::Overworld::GetTile(), yaze::editor::EditorContext::SharedClipboard::has_overworld_tile16, overworld_, yaze::editor::EditorContext::SharedClipboard::overworld_height, yaze::editor::EditorContext::SharedClipboard::overworld_tile16_ids, yaze::editor::EditorContext::SharedClipboard::overworld_width, ow_map_canvas_, yaze::gui::Canvas::select_rect_active(), yaze::gui::Canvas::selected_points(), yaze::zelda3::Overworld::set_current_map(), yaze::zelda3::Overworld::set_current_world(), and yaze::editor::EditorContext::shared_clipboard.
Paste()
absl::Status yaze::editor::OverworldEditor::Paste () override virtual
Implements yaze::editor::Editor.
Definition at line 983 of file overworld_editor.cc.
References yaze::editor::Editor::context_, current_map_, current_world_, yaze::gui::Canvas::drawn_tile_position(), yaze::editor::EditorContext::SharedClipboard::has_overworld_tile16, yaze::editor::kOverworldMapSize, yaze::editor::kTile16Size, yaze::zelda3::Overworld::mutable_map_tiles(), overworld_, yaze::editor::EditorContext::SharedClipboard::overworld_height, yaze::editor::EditorContext::SharedClipboard::overworld_tile16_ids, yaze::editor::EditorContext::SharedClipboard::overworld_width, ow_map_canvas_, yaze::gui::Canvas::points(), RefreshOverworldMap(), yaze::gui::Canvas::selected_tile_pos(), and yaze::editor::EditorContext::shared_clipboard.
Find()
absl::Status yaze::editor::OverworldEditor::Find () inline override virtual
Implements yaze::editor::Editor.
Definition at line 81 of file overworld_editor.h.
Save()
absl::Status yaze::editor::OverworldEditor::Save () override virtual
Implements yaze::editor::Editor.
Definition at line 1522 of file overworld_editor.cc.
References yaze::zelda3::Overworld::CreateTile32Tilemap(), yaze::core::FeatureFlags::get(), overworld(), overworld_, RETURN_IF_ERROR, yaze::zelda3::Overworld::SaveEntrances(), yaze::zelda3::Overworld::SaveExits(), yaze::zelda3::Overworld::SaveItems(), yaze::zelda3::Overworld::SaveMap16Tiles(), yaze::zelda3::Overworld::SaveMap32Tiles(), yaze::zelda3::Overworld::SaveMapProperties(), yaze::zelda3::Overworld::SaveMusic(), and yaze::zelda3::Overworld::SaveOverworldMaps().
Referenced by yaze::editor::EditorManager::SaveRom(), and yaze::editor::EditorManager::SaveRomAs().
Clear()
absl::Status yaze::editor::OverworldEditor::Clear () override virtual
Reimplemented from yaze::editor::Editor.
Definition at line 2599 of file overworld_editor.cc.
References all_gfx_loaded_, current_graphics_set_, yaze::zelda3::Overworld::Destroy(), map_blockset_loaded_, and overworld_.
Referenced by DrawToolset().
overworld()
zelda3::Overworld & yaze::editor::OverworldEditor::overworld () inline
Definition at line 84 of file overworld_editor.h.
References overworld_.
Referenced by LoadGraphics(), yaze::editor::EditorManager::overworld(), and Save().
ApplyZSCustomOverworldASM()
absl::Status yaze::editor::OverworldEditor::ApplyZSCustomOverworldASM (int target_version)
Apply ZSCustomOverworld ASM patch to upgrade ROM version.
Definition at line 2607 of file overworld_editor.cc.
References yaze::util::GetResourcePath(), yaze::zelda3::Overworld::Load(), yaze::Rom::LoadFromData(), LOG_DEBUG, LOG_ERROR, overworld_, yaze::zelda3::OverworldCustomASMHasBeenApplied, RETURN_IF_ERROR, rom_, UpdateROMVersionMarkers(), and yaze::Rom::vector().
Referenced by DrawToolset().
UpdateROMVersionMarkers()
absl::Status yaze::editor::OverworldEditor::UpdateROMVersionMarkers (int target_version)
Update ROM version markers and feature flags after ASM patching.
Definition at line 2711 of file overworld_editor.cc.
References yaze::zelda3::kOverworldScreenSize, yaze::zelda3::LargeArea, LOG_DEBUG, yaze::zelda3::OverworldCustomAnimatedGFXEnabled, yaze::zelda3::OverworldCustomAreaSpecificBGEnabled, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::zelda3::OverworldCustomMainPaletteEnabled, yaze::zelda3::OverworldCustomMosaicEnabled, yaze::zelda3::OverworldCustomSubscreenOverlayEnabled, yaze::zelda3::OverworldCustomTileGFXGroupEnabled, and yaze::zelda3::SmallArea.
Referenced by ApplyZSCustomOverworldASM().
jump_to_tab()
int yaze::editor::OverworldEditor::jump_to_tab () inline
Definition at line 96 of file overworld_editor.h.
References jump_to_tab_.
IsRomLoaded()
bool yaze::editor::OverworldEditor::IsRomLoaded () const inline override virtual
Reimplemented from yaze::editor::Editor.
Definition at line 100 of file overworld_editor.h.
References yaze::Rom::is_loaded(), and rom_.
GetRomStatus()
std::string yaze::editor::OverworldEditor::GetRomStatus () const inline override virtual
Reimplemented from yaze::editor::Editor.
Definition at line 101 of file overworld_editor.h.
References yaze::Rom::is_loaded(), rom_, and yaze::Rom::title().
set_current_map()
void yaze::editor::OverworldEditor::set_current_map (int map_id) inline
Definition at line 108 of file overworld_editor.h.
References current_map_, current_world_, and yaze::zelda3::kNumOverworldMaps.
Referenced by yaze::editor::EditorManager::JumpToOverworldMap().
LoadGraphics()
absl::Status yaze::editor::OverworldEditor::LoadGraphics ()
Load the Bitmap objects for each OverworldMap.
Calls the Overworld class to load the image data and palettes from the Rom, then renders the area graphics and tile16 blockset Bitmap objects before assembling the OverworldMap Bitmap objects.
Todo:
Queue texture for later rendering.
Todo:
Queue texture for later rendering.
Definition at line 1545 of file overworld_editor.cc.
References yaze::gfx::Tilemap::atlas, yaze::gfx::Arena::CREATE, yaze::gfx::CreateTilemap(), yaze::zelda3::Overworld::current_area_palette(), yaze::zelda3::Overworld::current_map_bitmap_data(), current_world_, yaze::core::FeatureFlags::get(), yaze::gfx::Arena::Get(), yaze::gfx::Bitmap::is_active(), yaze::zelda3::kDarkWorldMapIdStart, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::kNumTile16Individual, yaze::editor::kOverworldMapSize, yaze::zelda3::kSpecialWorldMapIdStart, yaze::editor::kTile16Size, yaze::zelda3::Overworld::Load(), LoadSpriteGraphics(), LOG_DEBUG, map_blockset_loaded_, maps_bmp_, overworld(), overworld_, palette_, yaze::gfx::Arena::QueueTextureCommand(), renderer_, RETURN_IF_ERROR, rom_, yaze::zelda3::Overworld::set_current_map(), yaze::gfx::Bitmap::surface(), tile16_blockset_, and yaze::zelda3::Overworld::tile16_blockset_data().
Referenced by Load().
DrawFullscreenCanvas()
void yaze::editor::OverworldEditor::DrawFullscreenCanvas () private
Definition at line 348 of file overworld_editor.cc.
References DrawOverworldCanvas(), DrawToolset(), and overworld_canvas_fullscreen_.
Referenced by Update().
DrawToolset()
void yaze::editor::OverworldEditor::DrawToolset () private
Definition at line 365 of file overworld_editor.cc.
References yaze::gui::Toolset::AddAction(), yaze::gui::Toolset::AddProperty(), yaze::gui::Toolset::AddRomBadge(), yaze::gui::Toolset::AddSeparator(), yaze::gui::Toolset::AddToggle(), yaze::gui::Toolset::AddUsageStatsButton(), ApplyZSCustomOverworldASM(), yaze::gui::Toolset::Begin(), yaze::gui::Toolset::BeginModeGroup(), Clear(), current_map_, current_map_lock_, current_mode, DRAW_TILE, yaze::gui::Toolset::End(), yaze::gui::Toolset::EndModeGroup(), entity_edit_mode_, ENTRANCES, EXITS, ICON_MD_ADD_LOCATION, ICON_MD_BRUSH, ICON_MD_CANCEL, ICON_MD_CHECK, ICON_MD_COLLECTIONS, ICON_MD_DOOR_BACK, ICON_MD_DOOR_FRONT, ICON_MD_DRAW, ICON_MD_GRASS, ICON_MD_GRID_3X3, ICON_MD_GRID_4X4, ICON_MD_GRID_VIEW, ICON_MD_IMAGE, ICON_MD_MOUSE, ICON_MD_MUSIC_NOTE, ICON_MD_OPEN_IN_FULL, ICON_MD_PALETTE, ICON_MD_PEST_CONTROL_RODENT, ICON_MD_TUNE, ICON_MD_UPGRADE, ICON_MD_ZOOM_IN, ICON_MD_ZOOM_OUT, ITEMS, Load(), LOG_ERROR, yaze::gui::Toolset::ModeButton(), MOUSE, MUSIC, yaze::zelda3::Overworld::mutable_overworld_map(), NONE, overworld_, overworld_canvas_fullscreen_, yaze::zelda3::OverworldCustomASMHasBeenApplied, ow_map_canvas_, show_area_gfx_, show_gfx_groups_, show_map_properties_panel_, show_scratch_, show_tile16_editor_, show_tile16_selector_, show_tile8_selector_, show_usage_stats_, SPRITES, status_, TRANSPORTS, yaze::gui::Canvas::ZoomIn(), and yaze::gui::Canvas::ZoomOut().
Referenced by DrawFullscreenCanvas(), and Update().
RefreshChildMap()
void yaze::editor::OverworldEditor::RefreshChildMap (int map_index) private
Definition at line 1776 of file overworld_editor.cc.
References current_world_, yaze::zelda3::Overworld::GetMapTiles(), maps_bmp_, yaze::zelda3::Overworld::mutable_overworld_map(), yaze::zelda3::Overworld::mutable_tiles16(), overworld_, PRINT_IF_ERROR, status_, and yaze::zelda3::Overworld::tiles16().
RefreshOverworldMap()
void yaze::editor::OverworldEditor::RefreshOverworldMap () private
Definition at line 1791 of file overworld_editor.cc.
References current_map_, and RefreshOverworldMapOnDemand().
Referenced by CheckForCurrentMap(), CheckForOverworldEdits(), Initialize(), Load(), and Paste().
RefreshOverworldMapOnDemand()
void yaze::editor::OverworldEditor::RefreshOverworldMapOnDemand (int map_index) private
On-demand map refresh that only updates what's actually needed.
This method intelligently determines what needs to be refreshed based on the type of change and only updates the necessary components, avoiding expensive full rebuilds when possible.
Definition at line 1803 of file overworld_editor.cc.
References current_map_, current_world_, yaze::zelda3::kNumOverworldMaps, maps_bmp_, and RefreshChildMapOnDemand().
Referenced by ProcessDeferredTextures(), and RefreshOverworldMap().
RefreshChildMapOnDemand()
void yaze::editor::OverworldEditor::RefreshChildMapOnDemand (int map_index) private
On-demand child map refresh with selective updates.
Definition at line 1826 of file overworld_editor.cc.
References yaze::gfx::Arena::CREATE, current_world_, yaze::gfx::Arena::Get(), yaze::zelda3::Overworld::GetMapTiles(), LOG_ERROR, LOG_WARN, maps_bmp_, yaze::zelda3::Overworld::mutable_overworld_map(), yaze::zelda3::Overworld::mutable_tiles16(), overworld_, yaze::zelda3::OverworldCustomASMHasBeenApplied, yaze::gfx::Arena::QueueTextureCommand(), RefreshMultiAreaMapsSafely(), yaze::zelda3::Overworld::tiles16(), and yaze::gfx::Arena::UPDATE.
Referenced by RefreshOverworldMapOnDemand(), and RefreshSiblingMapGraphics().
RefreshMultiAreaMapsSafely()
void yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely (int map_index, zelda3::OverworldMap * map) private
Safely refresh multi-area maps without recursion.
This function handles the coordination of large, wide, and tall area maps by using a non-recursive approach with explicit map list processing. It respects the ZScream area size logic and prevents infinite recursion.
Definition at line 1905 of file overworld_editor.cc.
References yaze::zelda3::OverworldMap::area_size(), yaze::zelda3::Overworld::current_area_palette(), current_map_, current_world_, EnsureMapTexture(), yaze::gfx::Arena::Get(), yaze::zelda3::Overworld::GetMapTiles(), yaze::zelda3::kNumOverworldMaps, LOG_DEBUG, LOG_ERROR, LOG_WARN, maps_bmp_, yaze::zelda3::Overworld::mutable_overworld_map(), yaze::zelda3::Overworld::mutable_tiles16(), overworld_, yaze::zelda3::OverworldMap::parent(), yaze::gfx::Arena::QueueTextureCommand(), yaze::zelda3::Overworld::tiles16(), and yaze::gfx::Arena::UPDATE.
Referenced by RefreshChildMapOnDemand().
RefreshMapPalette()
absl::Status yaze::editor::OverworldEditor::RefreshMapPalette () private
Definition at line 2056 of file overworld_editor.cc.
References yaze::zelda3::Overworld::current_area_palette(), current_map_, yaze::zelda3::kNumOverworldMaps, maps_bmp_, yaze::zelda3::Overworld::mutable_overworld_map(), overworld_, yaze::zelda3::Overworld::overworld_map(), yaze::zelda3::OverworldCustomASMHasBeenApplied, and RETURN_IF_ERROR.
Referenced by Initialize().
RefreshMapProperties()
void yaze::editor::OverworldEditor::RefreshMapProperties () private
Definition at line 2195 of file overworld_editor.cc.
References current_map_, game_state_, yaze::zelda3::kNumOverworldMaps, yaze::zelda3::Overworld::mutable_overworld_map(), overworld_, and yaze::zelda3::OverworldCustomASMHasBeenApplied.
Referenced by Initialize().
RefreshTile16Blockset()
absl::Status yaze::editor::OverworldEditor::RefreshTile16Blockset () private
Definition at line 2272 of file overworld_editor.cc.
References yaze::gfx::Tilemap::atlas, yaze::gfx::Arena::CREATE, yaze::zelda3::Overworld::current_area_palette(), current_blockset_, current_map_, yaze::gfx::Arena::Get(), yaze::gfx::Bitmap::is_active(), LOG_DEBUG, overworld_, yaze::zelda3::Overworld::overworld_map(), palette_, yaze::gfx::Arena::QueueTextureCommand(), renderer_, yaze::zelda3::Overworld::set_current_map(), yaze::gfx::Bitmap::SetPalette(), yaze::gfx::Bitmap::texture(), tile16_blockset_, yaze::zelda3::Overworld::tile16_blockset_data(), yaze::gfx::Arena::UPDATE, and yaze::gfx::UpdateTilemap().
Referenced by CheckForCurrentMap(), Initialize(), and Load().
ForceRefreshGraphics()
void yaze::editor::OverworldEditor::ForceRefreshGraphics (int map_index) private
Definition at line 2134 of file overworld_editor.cc.
References current_blockset_, LOG_DEBUG, and maps_bmp_.
Referenced by Initialize().
RefreshSiblingMapGraphics()
void yaze::editor::OverworldEditor::RefreshSiblingMapGraphics (int map_index, bool include_self = false) private
Definition at line 2146 of file overworld_editor.cc.
References yaze::zelda3::LargeArea, LOG_DEBUG, maps_bmp_, yaze::zelda3::Overworld::mutable_overworld_map(), overworld_, RefreshChildMapOnDemand(), yaze::zelda3::SmallArea, yaze::zelda3::TallArea, and yaze::zelda3::WideArea.
DrawOverworldMaps()
void yaze::editor::OverworldEditor::DrawOverworldMaps () private
Definition at line 598 of file overworld_editor.cc.
References current_map_, current_world_, yaze::gui::Canvas::DrawBitmap(), EnsureMapTexture(), IM_PI, yaze::editor::kOverworldMapSize, maps_bmp_, ow_map_canvas_, and yaze::gui::Canvas::zero_point().
Referenced by DrawOverworldCanvas().
DrawOverworldEdits()
void yaze::editor::OverworldEditor::DrawOverworldEdits () private
Definition at line 662 of file overworld_editor.cc.
References yaze::gfx::Tilemap::atlas, current_map_, current_tile16_, current_world_, yaze::gui::Canvas::drawn_tile_position(), yaze::gfx::GetTilemapData(), yaze::gfx::Bitmap::is_active(), yaze::editor::kOverworldMapSize, LOG_ERROR, maps_bmp_, yaze::zelda3::Overworld::mutable_map_tiles(), overworld_, ow_map_canvas_, RenderUpdatedMapBitmap(), tile16_blockset_, and yaze::gfx::Bitmap::vector().
Referenced by CheckForOverworldEdits().
RenderUpdatedMapBitmap()
void yaze::editor::OverworldEditor::RenderUpdatedMapBitmap (const ImVec2 & click_position, const std::vector< uint8_t > & tile_data) private
Todo:
Queue texture for later rendering.
Definition at line 716 of file overworld_editor.cc.
References current_map_, yaze::gfx::Bitmap::is_active(), yaze::editor::kOverworldMapSize, yaze::editor::kTile16Size, LOG_ERROR, maps_bmp_, yaze::gfx::Bitmap::set_modified(), yaze::gfx::Bitmap::size(), and yaze::gfx::Bitmap::WriteToPixel().
Referenced by AutomationSetTile(), CheckForOverworldEdits(), and DrawOverworldEdits().
CheckForOverworldEdits()
void yaze::editor::OverworldEditor::CheckForOverworldEdits () private
Check for changes to the overworld map.
This function either draws the tile painter with the current tile16 or group of tile16 data with ow_map_canvas_ and DrawOverworldEdits or it checks for left mouse button click/drag to select a tile16 or group of tile16 data from the overworld map canvas. Similar to ZScream selection.
Definition at line 789 of file overworld_editor.cc.
References CheckForSelectRectangle(), current_tile16_, current_world_, DrawOverworldEdits(), yaze::gui::Canvas::DrawTilemapPainter(), yaze::gfx::GetTilemapData(), yaze::editor::kTile16Size, LOG_DEBUG, LOG_ERROR, yaze::zelda3::Overworld::mutable_map_tiles(), overworld_, ow_map_canvas_, RefreshOverworldMap(), RenderUpdatedMapBitmap(), yaze::gui::Canvas::select_rect_active(), yaze::gui::Canvas::selected_points(), selected_tile16_ids_, and tile16_blockset_.
Referenced by DrawOverworldCanvas().
CheckForSelectRectangle()
void yaze::editor::OverworldEditor::CheckForSelectRectangle () private
Draw and create the tile16 IDs that are currently selected.
Definition at line 906 of file overworld_editor.cc.
References current_map_, current_tile16_, current_world_, yaze::gui::Canvas::DrawBitmapGroup(), yaze::gui::Canvas::DrawSelectRect(), yaze::zelda3::Overworld::GetTileFromPosition(), yaze::gui::Canvas::global_scale(), overworld_, ow_map_canvas_, ScrollBlocksetCanvasToCurrentTile(), yaze::gui::Canvas::select_rect_active(), selected_tile16_ids_, yaze::gui::Canvas::selected_tile_pos(), yaze::gui::Canvas::selected_tiles(), yaze::zelda3::Overworld::set_current_map(), yaze::zelda3::Overworld::set_current_world(), yaze::gui::Canvas::set_selected_tile_pos(), and tile16_blockset_.
Referenced by CheckForOverworldEdits().
CheckForCurrentMap()
absl::Status yaze::editor::OverworldEditor::CheckForCurrentMap () private
Check for changes to the overworld map. Calls RefreshOverworldMap and RefreshTile16Blockset on the current map if it is modified and is actively being edited.
Todo:
Queue texture for later rendering.
Todo:
Queue texture for later rendering.
Definition at line 1039 of file overworld_editor.cc.
References yaze::gfx::Tilemap::atlas, current_map_, current_map_lock_, current_parent_, current_world_, yaze::gui::Canvas::DrawOutline(), yaze::zelda3::Overworld::EnsureMapBuilt(), EnsureMapTexture(), yaze::gfx::Bitmap::is_active(), yaze::editor::kOverworldMapSize, maps_bmp_, overworld_, yaze::zelda3::Overworld::overworld_map(), yaze::zelda3::OverworldCustomASMHasBeenApplied, ow_map_canvas_, RefreshOverworldMap(), RefreshTile16Blockset(), RETURN_IF_ERROR, tile16_blockset_, and yaze::gui::Canvas::zero_point().
Referenced by DrawOverworldCanvas().
CheckForMousePan()
void yaze::editor::OverworldEditor::CheckForMousePan () private
Definition at line 1329 of file overworld_editor.cc.
References HandleOverworldPan().
DrawOverworldCanvas()
void yaze::editor::OverworldEditor::DrawOverworldCanvas () private
Definition at line 1334 of file overworld_editor.cc.
References yaze::gui::BeginChildBothScrollbars(), yaze::gui::BeginNoPadding(), CheckForCurrentMap(), CheckForOverworldEdits(), current_map_, current_map_lock_, current_mode, current_world_, DRAW_TILE, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), DrawOverworldMaps(), yaze::gui::EndNoPadding(), entity_edit_mode_, entity_renderer_, game_state_, HandleMapInteraction(), HandleOverworldPan(), HandleOverworldZoom(), yaze::Rom::is_loaded(), yaze::zelda3::Overworld::is_loaded(), jump_to_tab_, map_properties_system_, MOUSE, overworld_, ow_map_canvas_, rom_, yaze::gui::Canvas::scrolling(), show_custom_bg_color_editor_, show_map_properties_panel_, show_overlay_editor_, show_overlay_preview_, status_, and yaze::gui::Canvas::zero_point().
Referenced by DrawFullscreenCanvas(), and Update().
DrawTile16Selector()
absl::Status yaze::editor::OverworldEditor::DrawTile16Selector () private
Definition at line 1409 of file overworld_editor.cc.
References yaze::gfx::Tilemap::atlas, yaze::gui::BeginChildWithScrollbar(), yaze::gui::BeginPadding(), blockset_canvas_, blockset_selector_, current_tile16_, yaze::gui::TileSelectorWidget::Config::display_scale, yaze::gui::TileSelectorWidget::Config::draw_offset, yaze::gui::EndPadding(), yaze::gui::TileSelectorWidget::Config::highlight_color, yaze::gfx::Bitmap::is_active(), yaze::zelda3::kNumTile16Individual, map_blockset_loaded_, yaze::editor::Tile16Editor::SetCurrentTile(), show_tile16_editor_, tile16_blockset_, tile16_editor_, yaze::gui::TileSelectorWidget::Config::tile_size, yaze::gui::TileSelectorWidget::Config::tiles_per_row, yaze::gui::TileSelectorWidget::Config::total_tiles, and UpdateBlocksetSelectorState().
Referenced by Update().
DrawTile8Selector()
void yaze::editor::OverworldEditor::DrawTile8Selector () private
Definition at line 1458 of file overworld_editor.cc.
References all_gfx_loaded_, yaze::gui::Canvas::draw_list(), yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::gfx::Arena::Get(), yaze::gfx::Arena::gfx_sheets(), graphics_bin_canvas_, and yaze::gui::Canvas::zero_point().
Referenced by Update().
DrawAreaGraphics()
absl::Status yaze::editor::OverworldEditor::DrawAreaGraphics () private
Todo:
Queue texture for later rendering.
Definition at line 1482 of file overworld_editor.cc.
References yaze::gui::BeginChildWithScrollbar(), yaze::gui::BeginPadding(), yaze::zelda3::Overworld::current_area_palette(), current_gfx_canvas_, current_graphics_set_, current_map_, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawContextMenu(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::gui::Canvas::DrawTileSelector(), yaze::gui::EndPadding(), yaze::zelda3::Overworld::is_loaded(), overworld_, palette_, and yaze::zelda3::Overworld::set_current_map().
Referenced by Update().
UpdateBlocksetSelectorState()
void yaze::editor::OverworldEditor::UpdateBlocksetSelectorState () private
Definition at line 2764 of file overworld_editor.cc.
References blockset_selector_, current_tile16_, and yaze::zelda3::kNumTile16Individual.
Referenced by DrawTile16Selector().
LoadSpriteGraphics()
absl::Status yaze::editor::OverworldEditor::LoadSpriteGraphics () private
Todo:
Queue texture for later rendering.
Definition at line 1693 of file overworld_editor.cc.
References yaze::zelda3::Overworld::mutable_sprites(), overworld_, palette_, and sprite_previews_.
Referenced by LoadGraphics().
ProcessDeferredTextures()
void yaze::editor::OverworldEditor::ProcessDeferredTextures () private
Create textures for deferred map bitmaps on demand.
This method should be called periodically to create textures for maps that are needed but haven't had their textures created yet. This allows for smooth loading without blocking the main thread during ROM loading.
Definition at line 1715 of file overworld_editor.cc.
References current_map_, current_world_, yaze::gfx::Arena::Get(), yaze::zelda3::kNumOverworldMaps, maps_bmp_, yaze::gfx::Arena::ProcessTextureQueue(), RefreshOverworldMapOnDemand(), and renderer_.
Referenced by Update().
EnsureMapTexture()
void yaze::editor::OverworldEditor::EnsureMapTexture (int map_index) private
Ensure a specific map has its texture created.
Call this when a map becomes visible or is about to be rendered. It will create the texture if it doesn't exist yet.
Definition at line 1739 of file overworld_editor.cc.
References yaze::gfx::Arena::CREATE, yaze::zelda3::Overworld::current_area_palette(), yaze::zelda3::Overworld::current_map_bitmap_data(), yaze::zelda3::Overworld::EnsureMapBuilt(), yaze::gfx::Arena::Get(), yaze::zelda3::kNumOverworldMaps, yaze::editor::kOverworldMapSize, LOG_ERROR, maps_bmp_, overworld_, yaze::gfx::Arena::QueueTextureCommand(), and yaze::zelda3::Overworld::set_current_map().
Referenced by CheckForCurrentMap(), DrawOverworldMaps(), and RefreshMultiAreaMapsSafely().
DrawOverworldProperties()
void yaze::editor::OverworldEditor::DrawOverworldProperties () private
Definition at line 2365 of file overworld_editor.cc.
References yaze::gui::BeginWindowWithDisplaySettings(), DW_AREA_GFX, DW_AREA_PAL, DW_SPR_GFX_PART1, DW_SPR_GFX_PART2, DW_SPR_PAL_PART1, DW_SPR_PAL_PART2, yaze::gui::EndWindowWithDisplaySettings(), gfx_group_editor_, LW_AREA_GFX, LW_AREA_PAL, LW_SPR_GFX_PART1, LW_SPR_GFX_PART2, LW_SPR_PAL_PART1, LW_SPR_PAL_PART2, yaze::gui::Canvas::mutable_labels(), overworld_, yaze::zelda3::Overworld::overworld_map(), properties_canvas_, status_, yaze::editor::GfxGroupEditor::Update(), and yaze::gui::Canvas::UpdateInfoGrid().
Referenced by UpdateUsageStats().
HandleMapInteraction()
void yaze::editor::OverworldEditor::HandleMapInteraction () private
Definition at line 2301 of file overworld_editor.cc.
References current_map_, current_map_lock_, current_world_, yaze::gui::Canvas::drawn_tile_position(), yaze::editor::kOverworldMapSize, ow_map_canvas_, and show_map_properties_panel_.
Referenced by DrawOverworldCanvas().
HandleOverworldPan()
void yaze::editor::OverworldEditor::HandleOverworldPan () private
Definition at line 1217 of file overworld_editor.cc.
References yaze::gui::Canvas::canvas_size(), current_mode, yaze::gui::Canvas::global_scale(), middle_mouse_dragging_, MOUSE, ow_map_canvas_, yaze::gui::Canvas::scrolling(), and yaze::gui::Canvas::set_scrolling().
Referenced by CheckForMousePan(), and DrawOverworldCanvas().
HandleOverworldZoom()
void yaze::editor::OverworldEditor::HandleOverworldZoom () private
Definition at line 1261 of file overworld_editor.cc.
References yaze::gui::Canvas::canvas_size(), yaze::gui::Canvas::global_scale(), ow_map_canvas_, yaze::gui::Canvas::scrolling(), yaze::gui::Canvas::set_global_scale(), yaze::gui::Canvas::set_scrolling(), and yaze::gui::Canvas::zero_point().
Referenced by DrawOverworldCanvas().
ResetOverworldView()
void yaze::editor::OverworldEditor::ResetOverworldView () private
Definition at line 1310 of file overworld_editor.cc.
References ow_map_canvas_, yaze::gui::Canvas::set_global_scale(), and yaze::gui::Canvas::set_scrolling().
CenterOverworldView()
void yaze::editor::OverworldEditor::CenterOverworldView () private
Definition at line 1315 of file overworld_editor.cc.
References yaze::gui::Canvas::canvas_size(), yaze::gui::Canvas::global_scale(), ow_map_canvas_, and yaze::gui::Canvas::set_scrolling().
SetupCanvasAutomation()
void yaze::editor::OverworldEditor::SetupCanvasAutomation () private
Definition at line 2777 of file overworld_editor.cc.
References AutomationGetTile(), AutomationSetTile(), yaze::gui::Canvas::GetAutomationAPI(), ow_map_canvas_, and yaze::gui::CanvasAutomationAPI::SetTilePaintCallback().
Referenced by Initialize().
GetOverworldCanvas()
gui::Canvas * yaze::editor::OverworldEditor::GetOverworldCanvas () inline private
Definition at line 207 of file overworld_editor.h.
References ow_map_canvas_.
AutomationSetTile()
bool yaze::editor::OverworldEditor::AutomationSetTile (int x, int y, int tile_id) private
Definition at line 2791 of file overworld_editor.cc.
References current_map_, current_world_, yaze::gfx::GetTilemapData(), yaze::zelda3::Overworld::is_loaded(), overworld_, RenderUpdatedMapBitmap(), yaze::zelda3::Overworld::set_current_map(), yaze::zelda3::Overworld::set_current_world(), yaze::zelda3::Overworld::SetTile(), and tile16_blockset_.
Referenced by SetupCanvasAutomation().
AutomationGetTile()
int yaze::editor::OverworldEditor::AutomationGetTile (int x, int y) private
Definition at line 2819 of file overworld_editor.cc.
References current_map_, current_world_, yaze::zelda3::Overworld::GetTile(), yaze::zelda3::Overworld::is_loaded(), overworld_, yaze::zelda3::Overworld::set_current_map(), and yaze::zelda3::Overworld::set_current_world().
Referenced by SetupCanvasAutomation().
ScrollBlocksetCanvasToCurrentTile()
void yaze::editor::OverworldEditor::ScrollBlocksetCanvasToCurrentTile () private
Scroll the blockset canvas to show the current selected tile16.
Definition at line 2340 of file overworld_editor.cc.
References blockset_canvas_, blockset_selector_, yaze::gui::Canvas::canvas_size(), current_tile16_, and yaze::gui::Canvas::set_scrolling().
Referenced by CheckForSelectRectangle().
DrawScratchSpace()
absl::Status yaze::editor::OverworldEditor::DrawScratchSpace () private
Definition at line 44 of file scratch_space.cc.
References all_gfx_loaded_, yaze::gui::BeginChildWithScrollbar(), yaze::gui::BeginPadding(), ClearScratchSpace(), yaze::editor::Editor::context_, yaze::gfx::Arena::CREATE, yaze::zelda3::Overworld::current_area_palette(), current_scratch_slot_, yaze::gui::Canvas::DrawBackground(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawGrid(), yaze::gui::Canvas::DrawOverlay(), yaze::gui::Canvas::DrawTileSelector(), yaze::gui::EndPadding(), yaze::gfx::Arena::Get(), yaze::editor::EditorContext::SharedClipboard::has_overworld_tile16, HOVER_HINT, ICON_MD_CONTENT_PASTE, ICON_MD_DOWNLOAD, ICON_MD_UPLOAD, LoadScratchToSelection(), map_blockset_loaded_, overworld_, yaze::editor::EditorContext::SharedClipboard::overworld_height, yaze::editor::EditorContext::SharedClipboard::overworld_tile16_ids, yaze::editor::EditorContext::SharedClipboard::overworld_width, ow_map_canvas_, palette_, yaze::gfx::Arena::QueueTextureCommand(), RETURN_IF_ERROR, SaveCurrentSelectionToScratch(), scratch_canvas_, scratch_spaces_, yaze::gui::Canvas::select_rect_active(), yaze::gui::Canvas::selected_points(), yaze::gui::Canvas::selected_tiles(), yaze::gui::Canvas::SetContextMenuEnabled(), and yaze::editor::EditorContext::shared_clipboard.
Referenced by Update().
SaveCurrentSelectionToScratch()
absl::Status yaze::editor::OverworldEditor::SaveCurrentSelectionToScratch (int slot) private
Definition at line 326 of file scratch_space.cc.
References all_gfx_loaded_, yaze::gfx::Arena::CREATE, yaze::zelda3::Overworld::current_area_palette(), current_map_, current_world_, yaze::gfx::Arena::Get(), yaze::zelda3::Overworld::GetTileFromPosition(), overworld_, ow_map_canvas_, palette_, yaze::gfx::Arena::QueueTextureCommand(), scratch_spaces_, yaze::gui::Canvas::select_rect_active(), yaze::gui::Canvas::selected_points(), yaze::gui::Canvas::selected_tiles(), yaze::zelda3::Overworld::set_current_map(), yaze::zelda3::Overworld::set_current_world(), and UpdateScratchBitmapTile().
Referenced by DrawScratchSpace().
LoadScratchToSelection()
absl::Status yaze::editor::OverworldEditor::LoadScratchToSelection (int slot) private
Definition at line 409 of file scratch_space.cc.
References yaze::util::logf(), and scratch_spaces_.
Referenced by DrawScratchSpace().
ClearScratchSpace()
absl::Status yaze::editor::OverworldEditor::ClearScratchSpace (int slot) private
Definition at line 425 of file scratch_space.cc.
References yaze::gfx::Arena::Get(), yaze::gfx::Arena::QueueTextureCommand(), scratch_spaces_, and yaze::gfx::Arena::UPDATE.
Referenced by DrawScratchSpace().
DrawScratchSpaceEdits()
void yaze::editor::OverworldEditor::DrawScratchSpaceEdits () private
Definition at line 181 of file scratch_space.cc.
References current_scratch_slot_, current_tile16_, yaze::gui::Canvas::drawn_tile_position(), yaze::gui::Canvas::global_scale(), scratch_canvas_, scratch_spaces_, and UpdateScratchBitmapTile().
DrawScratchSpacePattern()
void yaze::editor::OverworldEditor::DrawScratchSpacePattern () private
Definition at line 218 of file scratch_space.cc.
References yaze::editor::Editor::context_, current_scratch_slot_, yaze::gui::Canvas::drawn_tile_position(), yaze::editor::EditorContext::SharedClipboard::has_overworld_tile16, yaze::editor::EditorContext::SharedClipboard::overworld_height, yaze::editor::EditorContext::SharedClipboard::overworld_tile16_ids, yaze::editor::EditorContext::SharedClipboard::overworld_width, scratch_canvas_, scratch_spaces_, yaze::editor::EditorContext::shared_clipboard, and UpdateScratchBitmapTile().
DrawScratchSpaceSelection()
void yaze::editor::OverworldEditor::DrawScratchSpaceSelection () private
UpdateScratchBitmapTile()
void yaze::editor::OverworldEditor::UpdateScratchBitmapTile (int tile_x, int tile_y, int tile_id, int slot = -1) private
Definition at line 272 of file scratch_space.cc.
References current_scratch_slot_, yaze::gfx::Arena::Get(), yaze::gfx::GetTilemapData(), yaze::gfx::Arena::QueueTextureCommand(), scratch_spaces_, tile16_blockset_, and yaze::gfx::Arena::UPDATE.
Referenced by DrawScratchSpaceEdits(), DrawScratchSpacePattern(), and SaveCurrentSelectionToScratch().
UpdateUsageStats()
absl::Status yaze::editor::OverworldEditor::UpdateUsageStats () private
Definition at line 2470 of file overworld_editor.cc.
References yaze::core::ResourceLabelManager::CreateOrGetLabel(), DrawOverworldProperties(), DrawUsageGrid(), yaze::zelda3::Overworld::entrances(), yaze::util::HexByte(), yaze::zelda3::kEntranceNames, overworld_, properties_canvas_, yaze::Rom::resource_label(), rom_, selected_entrance_, selected_usage_map_, and yaze::gui::Canvas::set_highlight_tile_id().
Referenced by Update().
DrawUsageGrid()
void yaze::editor::OverworldEditor::DrawUsageGrid () private
Definition at line 2523 of file overworld_editor.cc.
References yaze::gui::GetSelectedColor(), and selected_usage_map_.
Referenced by UpdateUsageStats().
DrawDebugWindow()
void yaze::editor::OverworldEditor::DrawDebugWindow () private
Definition at line 2569 of file overworld_editor.cc.
References current_map_, current_tile16_, yaze::gui::Canvas::drawn_tile_position(), yaze::zelda3::Overworld::mutable_map_tiles(), overworld_, and ow_map_canvas_.
Member Data Documentation
jump_to_tab_
int yaze::editor::OverworldEditor::jump_to_tab_ = -1
Definition at line 97 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), and jump_to_tab().
selected_tile16_ids_
std::vector<int> yaze::editor::OverworldEditor::selected_tile16_ids_ private
Definition at line 160 of file overworld_editor.h.
Referenced by CheckForOverworldEdits(), and CheckForSelectRectangle().
current_mode
EditingMode yaze::editor::OverworldEditor::current_mode = EditingMode::DRAW_TILE private
Definition at line 237 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), DrawToolset(), and HandleOverworldPan().
previous_mode
EditingMode yaze::editor::OverworldEditor::previous_mode = EditingMode::DRAW_TILE private
Definition at line 238 of file overworld_editor.h.
entity_edit_mode_
EntityEditMode yaze::editor::OverworldEditor::entity_edit_mode_ = EntityEditMode::NONE private
Definition at line 251 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), and DrawToolset().
current_world_
int yaze::editor::OverworldEditor::current_world_ = 0 private
Definition at line 268 of file overworld_editor.h.
Referenced by AutomationGetTile(), AutomationSetTile(), CheckForCurrentMap(), CheckForOverworldEdits(), CheckForSelectRectangle(), Copy(), DrawOverworldCanvas(), DrawOverworldEdits(), DrawOverworldMaps(), HandleMapInteraction(), LoadGraphics(), Paste(), ProcessDeferredTextures(), RefreshChildMap(), RefreshChildMapOnDemand(), RefreshMultiAreaMapsSafely(), RefreshOverworldMapOnDemand(), SaveCurrentSelectionToScratch(), and set_current_map().
current_map_
int yaze::editor::OverworldEditor::current_map_ = 0 private
Definition at line 269 of file overworld_editor.h.
Referenced by AutomationGetTile(), AutomationSetTile(), CheckForCurrentMap(), CheckForSelectRectangle(), Copy(), DrawAreaGraphics(), DrawDebugWindow(), DrawOverworldCanvas(), DrawOverworldEdits(), DrawOverworldMaps(), DrawToolset(), HandleMapInteraction(), Paste(), ProcessDeferredTextures(), RefreshMapPalette(), RefreshMapProperties(), RefreshMultiAreaMapsSafely(), RefreshOverworldMap(), RefreshOverworldMapOnDemand(), RefreshTile16Blockset(), RenderUpdatedMapBitmap(), SaveCurrentSelectionToScratch(), set_current_map(), and Update().
current_parent_
int yaze::editor::OverworldEditor::current_parent_ = 0 private
Definition at line 270 of file overworld_editor.h.
Referenced by CheckForCurrentMap().
current_entrance_id_
int yaze::editor::OverworldEditor::current_entrance_id_ = 0 private
Definition at line 271 of file overworld_editor.h.
current_exit_id_
int yaze::editor::OverworldEditor::current_exit_id_ = 0 private
Definition at line 272 of file overworld_editor.h.
current_item_id_
int yaze::editor::OverworldEditor::current_item_id_ = 0 private
Definition at line 273 of file overworld_editor.h.
current_sprite_id_
int yaze::editor::OverworldEditor::current_sprite_id_ = 0 private
Definition at line 274 of file overworld_editor.h.
current_blockset_
int yaze::editor::OverworldEditor::current_blockset_ = 0 private
Definition at line 275 of file overworld_editor.h.
Referenced by ForceRefreshGraphics(), and RefreshTile16Blockset().
game_state_
int yaze::editor::OverworldEditor::game_state_ = 1 private
Definition at line 276 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), and RefreshMapProperties().
current_tile16_
int yaze::editor::OverworldEditor::current_tile16_ = 0 private
Definition at line 277 of file overworld_editor.h.
Referenced by CheckForOverworldEdits(), CheckForSelectRectangle(), Copy(), DrawDebugWindow(), DrawOverworldEdits(), DrawScratchSpaceEdits(), DrawTile16Selector(), ScrollBlocksetCanvasToCurrentTile(), and UpdateBlocksetSelectorState().
selected_entrance_
int yaze::editor::OverworldEditor::selected_entrance_ = 0 private
Definition at line 278 of file overworld_editor.h.
Referenced by UpdateUsageStats().
selected_usage_map_
int yaze::editor::OverworldEditor::selected_usage_map_ = 0xFFFF private
Definition at line 279 of file overworld_editor.h.
Referenced by DrawUsageGrid(), and UpdateUsageStats().
all_gfx_loaded_
bool yaze::editor::OverworldEditor::all_gfx_loaded_ = false private
Definition at line 281 of file overworld_editor.h.
Referenced by Clear(), DrawScratchSpace(), DrawTile8Selector(), Load(), and SaveCurrentSelectionToScratch().
map_blockset_loaded_
bool yaze::editor::OverworldEditor::map_blockset_loaded_ = false private
Definition at line 282 of file overworld_editor.h.
Referenced by Clear(), DrawScratchSpace(), DrawTile16Selector(), and LoadGraphics().
selected_tile_loaded_
bool yaze::editor::OverworldEditor::selected_tile_loaded_ = false private
Definition at line 283 of file overworld_editor.h.
show_tile16_editor_
bool yaze::editor::OverworldEditor::show_tile16_editor_ = false private
Definition at line 284 of file overworld_editor.h.
Referenced by DrawTile16Selector(), DrawToolset(), and Update().
show_gfx_group_editor_
bool yaze::editor::OverworldEditor::show_gfx_group_editor_ = false private
Definition at line 285 of file overworld_editor.h.
show_properties_editor_
bool yaze::editor::OverworldEditor::show_properties_editor_ = false private
Definition at line 286 of file overworld_editor.h.
overworld_canvas_fullscreen_
bool yaze::editor::OverworldEditor::overworld_canvas_fullscreen_ = false private
Definition at line 287 of file overworld_editor.h.
Referenced by DrawFullscreenCanvas(), DrawToolset(), and Update().
middle_mouse_dragging_
bool yaze::editor::OverworldEditor::middle_mouse_dragging_ = false private
Definition at line 288 of file overworld_editor.h.
Referenced by HandleOverworldPan().
is_dragging_entity_
bool yaze::editor::OverworldEditor::is_dragging_entity_ = false private
Definition at line 289 of file overworld_editor.h.
current_map_lock_
bool yaze::editor::OverworldEditor::current_map_lock_ = false private
Definition at line 290 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), DrawOverworldCanvas(), DrawToolset(), and HandleMapInteraction().
show_custom_bg_color_editor_
bool yaze::editor::OverworldEditor::show_custom_bg_color_editor_ = false private
Definition at line 291 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), and Update().
show_overlay_editor_
bool yaze::editor::OverworldEditor::show_overlay_editor_ = false private
Definition at line 292 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), and Update().
use_area_specific_bg_color_
bool yaze::editor::OverworldEditor::use_area_specific_bg_color_ = false private
Definition at line 293 of file overworld_editor.h.
show_map_properties_panel_
bool yaze::editor::OverworldEditor::show_map_properties_panel_ = false private
Definition at line 294 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), DrawToolset(), HandleMapInteraction(), and Update().
show_overlay_preview_
bool yaze::editor::OverworldEditor::show_overlay_preview_ = false private
Definition at line 295 of file overworld_editor.h.
Referenced by DrawOverworldCanvas().
show_tile16_selector_
bool yaze::editor::OverworldEditor::show_tile16_selector_ = false private
Definition at line 298 of file overworld_editor.h.
Referenced by DrawToolset(), Initialize(), and Update().
show_tile8_selector_
bool yaze::editor::OverworldEditor::show_tile8_selector_ = false private
Definition at line 299 of file overworld_editor.h.
Referenced by DrawToolset(), Initialize(), and Update().
show_area_gfx_
bool yaze::editor::OverworldEditor::show_area_gfx_ = false private
Definition at line 300 of file overworld_editor.h.
Referenced by DrawToolset(), Initialize(), and Update().
show_scratch_
bool yaze::editor::OverworldEditor::show_scratch_ = false private
Definition at line 301 of file overworld_editor.h.
Referenced by DrawToolset(), Initialize(), and Update().
show_gfx_groups_
bool yaze::editor::OverworldEditor::show_gfx_groups_ = false private
Definition at line 302 of file overworld_editor.h.
Referenced by DrawToolset(), Initialize(), and Update().
show_usage_stats_
bool yaze::editor::OverworldEditor::show_usage_stats_ = false private
Definition at line 303 of file overworld_editor.h.
Referenced by DrawToolset(), Initialize(), and Update().
show_v3_settings_
bool yaze::editor::OverworldEditor::show_v3_settings_ = false private
Definition at line 304 of file overworld_editor.h.
Referenced by Initialize().
map_properties_system_
std::unique_ptr<MapPropertiesSystem> yaze::editor::OverworldEditor::map_properties_system_ private
Definition at line 307 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), Initialize(), and Update().
entity_renderer_
std::unique_ptr<OverworldEntityRenderer> yaze::editor::OverworldEditor::entity_renderer_ private
Definition at line 308 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), and Initialize().
scratch_spaces_
std::array<ScratchSpaceSlot, 4> yaze::editor::OverworldEditor::scratch_spaces_ private
Definition at line 324 of file overworld_editor.h.
Referenced by ClearScratchSpace(), DrawScratchSpace(), DrawScratchSpaceEdits(), DrawScratchSpacePattern(), LoadScratchToSelection(), SaveCurrentSelectionToScratch(), and UpdateScratchBitmapTile().
current_scratch_slot_
int yaze::editor::OverworldEditor::current_scratch_slot_ = 0 private
Definition at line 325 of file overworld_editor.h.
Referenced by DrawScratchSpace(), DrawScratchSpaceEdits(), DrawScratchSpacePattern(), and UpdateScratchBitmapTile().
tile16_blockset_
gfx::Tilemap yaze::editor::OverworldEditor::tile16_blockset_ private
Definition at line 327 of file overworld_editor.h.
Referenced by AutomationSetTile(), CheckForCurrentMap(), CheckForOverworldEdits(), CheckForSelectRectangle(), DrawOverworldEdits(), DrawTile16Selector(), LoadGraphics(), RefreshTile16Blockset(), and UpdateScratchBitmapTile().
rom_
Rom* yaze::editor::OverworldEditor::rom_ private
Definition at line 329 of file overworld_editor.h.
Referenced by ApplyZSCustomOverworldASM(), DrawOverworldCanvas(), GetRomStatus(), Initialize(), IsRomLoaded(), Load(), LoadGraphics(), Update(), and UpdateUsageStats().
renderer_
gfx::IRenderer* yaze::editor::OverworldEditor::renderer_ private
Definition at line 331 of file overworld_editor.h.
Referenced by LoadGraphics(), ProcessDeferredTextures(), and RefreshTile16Blockset().
tile16_editor_
Tile16Editor yaze::editor::OverworldEditor::tile16_editor_ {rom_, &tile16_blockset_} private
Definition at line 332 of file overworld_editor.h.
Referenced by DrawTile16Selector(), Load(), and Update().
gfx_group_editor_
GfxGroupEditor yaze::editor::OverworldEditor::gfx_group_editor_ private
Definition at line 333 of file overworld_editor.h.
Referenced by DrawOverworldProperties(), OverworldEditor(), and Update().
palette_editor_
PaletteEditor yaze::editor::OverworldEditor::palette_editor_ private
Definition at line 334 of file overworld_editor.h.
palette_
gfx::SnesPalette yaze::editor::OverworldEditor::palette_ private
Definition at line 336 of file overworld_editor.h.
Referenced by DrawAreaGraphics(), DrawScratchSpace(), Load(), LoadGraphics(), LoadSpriteGraphics(), RefreshTile16Blockset(), and SaveCurrentSelectionToScratch().
selected_tile_bmp_
gfx::Bitmap yaze::editor::OverworldEditor::selected_tile_bmp_ private
Definition at line 338 of file overworld_editor.h.
tile16_blockset_bmp_
gfx::Bitmap yaze::editor::OverworldEditor::tile16_blockset_bmp_ private
Definition at line 339 of file overworld_editor.h.
Referenced by Load().
current_gfx_bmp_
gfx::Bitmap yaze::editor::OverworldEditor::current_gfx_bmp_ private
Definition at line 340 of file overworld_editor.h.
Referenced by Load().
all_gfx_bmp
gfx::Bitmap yaze::editor::OverworldEditor::all_gfx_bmp private
Definition at line 341 of file overworld_editor.h.
maps_bmp_
std::array<gfx::Bitmap, zelda3::kNumOverworldMaps> yaze::editor::OverworldEditor::maps_bmp_ private
Definition at line 343 of file overworld_editor.h.
Referenced by CheckForCurrentMap(), DrawOverworldEdits(), DrawOverworldMaps(), EnsureMapTexture(), ForceRefreshGraphics(), Initialize(), LoadGraphics(), ProcessDeferredTextures(), RefreshChildMap(), RefreshChildMapOnDemand(), RefreshMapPalette(), RefreshMultiAreaMapsSafely(), RefreshOverworldMapOnDemand(), RefreshSiblingMapGraphics(), and RenderUpdatedMapBitmap().
current_graphics_set_
gfx::BitmapTable yaze::editor::OverworldEditor::current_graphics_set_ private
Definition at line 344 of file overworld_editor.h.
Referenced by Clear(), and DrawAreaGraphics().
sprite_previews_
std::vector<gfx::Bitmap> yaze::editor::OverworldEditor::sprite_previews_ private
Definition at line 345 of file overworld_editor.h.
Referenced by Initialize(), and LoadSpriteGraphics().
overworld_
zelda3::Overworld yaze::editor::OverworldEditor::overworld_ {rom_} private
Definition at line 350 of file overworld_editor.h.
Referenced by ApplyZSCustomOverworldASM(), AutomationGetTile(), AutomationSetTile(), CheckForCurrentMap(), CheckForOverworldEdits(), CheckForSelectRectangle(), Clear(), Copy(), DrawAreaGraphics(), DrawDebugWindow(), DrawOverworldCanvas(), DrawOverworldEdits(), DrawOverworldProperties(), DrawScratchSpace(), DrawToolset(), EnsureMapTexture(), Initialize(), Load(), LoadGraphics(), LoadSpriteGraphics(), overworld(), Paste(), RefreshChildMap(), RefreshChildMapOnDemand(), RefreshMapPalette(), RefreshMapProperties(), RefreshMultiAreaMapsSafely(), RefreshSiblingMapGraphics(), RefreshTile16Blockset(), Save(), SaveCurrentSelectionToScratch(), Update(), and UpdateUsageStats().
refresh_blockset_
zelda3::OverworldBlockset yaze::editor::OverworldEditor::refresh_blockset_ private
Definition at line 351 of file overworld_editor.h.
current_sprite_
zelda3::Sprite yaze::editor::OverworldEditor::current_sprite_ private
Definition at line 353 of file overworld_editor.h.
current_entrance_
zelda3::OverworldEntrance yaze::editor::OverworldEditor::current_entrance_ private
Definition at line 355 of file overworld_editor.h.
current_exit_
zelda3::OverworldExit yaze::editor::OverworldEditor::current_exit_ private
Definition at line 356 of file overworld_editor.h.
current_item_
zelda3::OverworldItem yaze::editor::OverworldEditor::current_item_ private
Definition at line 357 of file overworld_editor.h.
entrance_tiletypes_
zelda3::OverworldEntranceTileTypes yaze::editor::OverworldEditor::entrance_tiletypes_ = {} private
Definition at line 358 of file overworld_editor.h.
Referenced by Load().
current_entity_
zelda3::GameEntity* yaze::editor::OverworldEditor::current_entity_ = nullptr private
Definition at line 360 of file overworld_editor.h.
dragged_entity_
zelda3::GameEntity* yaze::editor::OverworldEditor::dragged_entity_ = nullptr private
Definition at line 361 of file overworld_editor.h.
ow_map_canvas_
gui::Canvas yaze::editor::OverworldEditor::ow_map_canvas_ private
Initial value:
{"OwMap", kOverworldCanvasSize,
                             gui::CanvasGridSize::k64x64}
Definition at line 363 of file overworld_editor.h.
Referenced by CenterOverworldView(), CheckForCurrentMap(), CheckForOverworldEdits(), CheckForSelectRectangle(), Copy(), DrawDebugWindow(), DrawOverworldCanvas(), DrawOverworldEdits(), DrawOverworldMaps(), DrawScratchSpace(), DrawToolset(), GetOverworldCanvas(), HandleMapInteraction(), HandleOverworldPan(), HandleOverworldZoom(), Initialize(), Paste(), ResetOverworldView(), SaveCurrentSelectionToScratch(), and SetupCanvasAutomation().
current_gfx_canvas_
gui::Canvas yaze::editor::OverworldEditor::current_gfx_canvas_ private
Initial value:
{"CurrentGfx", kCurrentGfxCanvasSize,
                                  gui::CanvasGridSize::k32x32}
Definition at line 365 of file overworld_editor.h.
Referenced by DrawAreaGraphics().
blockset_canvas_
gui::Canvas yaze::editor::OverworldEditor::blockset_canvas_ private
Initial value:
{"OwBlockset", kBlocksetCanvasSize,
                               gui::CanvasGridSize::k32x32}
Definition at line 367 of file overworld_editor.h.
Referenced by DrawTile16Selector(), and ScrollBlocksetCanvasToCurrentTile().
blockset_selector_
std::unique_ptr<gui::TileSelectorWidget> yaze::editor::OverworldEditor::blockset_selector_ private
Definition at line 369 of file overworld_editor.h.
Referenced by DrawTile16Selector(), ScrollBlocksetCanvasToCurrentTile(), and UpdateBlocksetSelectorState().
graphics_bin_canvas_
gui::Canvas yaze::editor::OverworldEditor::graphics_bin_canvas_ private
Initial value:
{"GraphicsBin", kGraphicsBinCanvasSize,
                                   gui::CanvasGridSize::k16x16}
Definition at line 370 of file overworld_editor.h.
Referenced by DrawTile8Selector().
properties_canvas_
gui::Canvas yaze::editor::OverworldEditor::properties_canvas_ private
Definition at line 372 of file overworld_editor.h.
Referenced by DrawOverworldProperties(), and UpdateUsageStats().
scratch_canvas_
gui::Canvas yaze::editor::OverworldEditor::scratch_canvas_ {"ScratchSpace", ImVec2(320, 480), gui::CanvasGridSize::k32x32} private
Definition at line 373 of file overworld_editor.h.
Referenced by DrawScratchSpace(), DrawScratchSpaceEdits(), and DrawScratchSpacePattern().
status_
absl::Status yaze::editor::OverworldEditor::status_ private
Definition at line 375 of file overworld_editor.h.
Referenced by DrawOverworldCanvas(), DrawOverworldProperties(), DrawToolset(), RefreshChildMap(), and Update().
The documentation for this class was generated from the following files:
src/app/editor/overworld/overworld_editor.h
src/app/editor/overworld/overworld_editor.cc
src/app/editor/overworld/scratch_space.cc