yaze: yaze::zelda3::RoomLayout Class Reference
yaze::zelda3::RoomLayout Class Reference
Manages room layout data and objects.
#include <room_layout.h>
Public Member Functions
RoomLayout ()=default
RoomLayout (Rom *rom)
absl::Status LoadLayout (int room_id)
absl::Status LoadLayoutData (int layout_data_address)
std::vector< RoomLayoutObject > GetObjectsByType (RoomLayoutObject::Type type) const
absl::StatusOr< RoomLayoutObject > GetObjectAt (uint8_t x, uint8_t y, uint8_t layer=0) const
const std::vector< RoomLayoutObject > & GetObjects () const
bool HasWall (uint8_t x, uint8_t y, uint8_t layer=0) const
bool HasFloor (uint8_t x, uint8_t y, uint8_t layer=0) const
std::pair< uint8_t, uint8_t > GetDimensions () const
Private Member Functions
absl::Status ParseLayoutData (const std::vector< uint8_t > &data)
RoomLayoutObject CreateLayoutObject (int16_t tile_id, uint8_t x, uint8_t y, uint8_t layer)
Private Attributes
Rom * rom_ = nullptr
std::vector< RoomLayoutObject > objects_
uint8_t width_ = 16
uint8_t height_ = 11
Detailed Description
Manages room layout data and objects.
This class handles loading and managing room layout objects from ROM data. It provides efficient access to wall, floor, and other layout elements without copying large amounts of data.
Definition at line 74 of file room_layout.h.
Constructor & Destructor Documentation
RoomLayout() [1/2]
yaze::zelda3::RoomLayout::RoomLayout () default
RoomLayout() [2/2]
yaze::zelda3::RoomLayout::RoomLayout (Rom * rom) inline explicit
Definition at line 77 of file room_layout.h.
Member Function Documentation
LoadLayout()
absl::Status yaze::zelda3::RoomLayout::LoadLayout (int room_id)
Definition at line 47 of file room_layout.cc.
References LoadLayoutData(), yaze::zelda3::NumberOfRooms, rom_, yaze::zelda3::room_object_layout_pointer, yaze::Rom::size(), yaze::SnesToPc(), and yaze::Rom::vector().
Referenced by yaze::zelda3::Room::LoadRoomLayout(), and yaze::test::TEST_F().
LoadLayoutData()
absl::Status yaze::zelda3::RoomLayout::LoadLayoutData (int layout_data_address)
Definition at line 99 of file room_layout.cc.
References height_, ParseLayoutData(), rom_, yaze::Rom::size(), yaze::Rom::vector(), and width_.
Referenced by LoadLayout().
GetObjectsByType()
std::vector< RoomLayoutObject > yaze::zelda3::RoomLayout::GetObjectsByType (RoomLayoutObject::Type type) const
Definition at line 188 of file room_layout.cc.
References objects_.
Referenced by yaze::test::TEST_F().
GetObjectAt()
absl::StatusOr< RoomLayoutObject > yaze::zelda3::RoomLayout::GetObjectAt (uint8_t x, uint8_t y, uint8_t layer = 0) const
Definition at line 199 of file room_layout.cc.
References objects_.
Referenced by yaze::test::TEST_F().
GetObjects()
const std::vector< RoomLayoutObject > & yaze::zelda3::RoomLayout::GetObjects () const inline
Definition at line 92 of file room_layout.h.
References objects_.
Referenced by yaze::zelda3::ObjectRenderer::RenderRoom().
HasWall()
bool yaze::zelda3::RoomLayout::HasWall (uint8_t x, uint8_t y, uint8_t layer = 0) const
Definition at line 210 of file room_layout.cc.
References yaze::zelda3::RoomLayoutObject::kWall, and objects_.
Referenced by yaze::test::TEST_F().
HasFloor()
bool yaze::zelda3::RoomLayout::HasFloor (uint8_t x, uint8_t y, uint8_t layer = 0) const
Definition at line 220 of file room_layout.cc.
References yaze::zelda3::RoomLayoutObject::kFloor, and objects_.
Referenced by yaze::test::TEST_F().
GetDimensions()
std::pair< uint8_t, uint8_t > yaze::zelda3::RoomLayout::GetDimensions () const inline
Definition at line 101 of file room_layout.h.
References height_, and width_.
Referenced by yaze::test::TEST_F().
ParseLayoutData()
absl::Status yaze::zelda3::RoomLayout::ParseLayoutData (const std::vector< uint8_t > & data) private
Definition at line 120 of file room_layout.cc.
References height_, yaze::zelda3::RoomLayoutObject::kCeiling, yaze::zelda3::RoomLayoutObject::kDoor, yaze::zelda3::RoomLayoutObject::kFloor, yaze::zelda3::RoomLayoutObject::kStairs, yaze::zelda3::RoomLayoutObject::kUnknown, yaze::zelda3::RoomLayoutObject::kWall, yaze::zelda3::RoomLayoutObject::kWater, objects_, and width_.
Referenced by LoadLayoutData().
CreateLayoutObject()
RoomLayoutObject yaze::zelda3::RoomLayout::CreateLayoutObject (int16_t tile_id, uint8_t x, uint8_t y, uint8_t layer) private
Definition at line 167 of file room_layout.cc.
References yaze::zelda3::RoomLayoutObject::kCeiling, yaze::zelda3::RoomLayoutObject::kDoor, yaze::zelda3::RoomLayoutObject::kFloor, yaze::zelda3::RoomLayoutObject::kStairs, yaze::zelda3::RoomLayoutObject::kUnknown, yaze::zelda3::RoomLayoutObject::kWall, and yaze::zelda3::RoomLayoutObject::kWater.
Member Data Documentation
rom_
Rom* yaze::zelda3::RoomLayout::rom_ = nullptr private
Definition at line 104 of file room_layout.h.
Referenced by LoadLayout(), and LoadLayoutData().
objects_
std::vector<RoomLayoutObject> yaze::zelda3::RoomLayout::objects_ private
Definition at line 105 of file room_layout.h.
Referenced by GetObjectAt(), GetObjects(), GetObjectsByType(), HasFloor(), HasWall(), and ParseLayoutData().
width_
uint8_t yaze::zelda3::RoomLayout::width_ = 16 private
Definition at line 106 of file room_layout.h.
Referenced by GetDimensions(), LoadLayoutData(), and ParseLayoutData().
height_
uint8_t yaze::zelda3::RoomLayout::height_ = 11 private
Definition at line 107 of file room_layout.h.
Referenced by GetDimensions(), LoadLayoutData(), and ParseLayoutData().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/room_layout.h
src/app/zelda3/dungeon/room_layout.cc