yaze: yaze::editor::UICoordinator Class Reference
yaze::editor::UICoordinator Class Reference
Handles all UI drawing operations and state management.
#include <ui_coordinator.h>
Public Member Functions
UICoordinator (EditorManager *editor_manager, RomFileManager &rom_manager, ProjectManager &project_manager, EditorRegistry &editor_registry, EditorCardRegistry &card_registry, SessionCoordinator &session_coordinator, WindowDelegate &window_delegate, ToastManager &toast_manager, PopupManager &popup_manager, ShortcutManager &shortcut_manager)
~UICoordinator ()=default
UICoordinator (const UICoordinator &)=delete
UICoordinator & operator= (const UICoordinator &)=delete
void DrawAllUI ()
void DrawMenuBarExtras ()
void DrawContextSensitiveCardControl ()
void DrawCommandPalette ()
void DrawGlobalSearch ()
void DrawWorkspacePresetDialogs ()
void DrawSessionSwitcher ()
void DrawSessionManager ()
void DrawSessionRenameDialog ()
void DrawLayoutPresets ()
void DrawWelcomeScreen ()
void DrawProjectHelp ()
void DrawWindowManagementUI ()
void DrawRomSelector ()
void DrawAllPopups ()
void ShowPopup (const std::string &popup_name)
void HidePopup (const std::string &popup_name)
void ShowEditorSelection ()
void ShowDisplaySettings ()
void ShowSaveWorkspacePresetDialog ()
void ShowLoadWorkspacePresetDialog ()
void ShowSessionSwitcher ()
void HideCurrentEditorCards ()
void ToggleCardSidebar ()
void ShowGlobalSearch ()
void ShowCommandPalette ()
void ShowCardBrowser ()
void ShowAllWindows ()
void HideAllWindows ()
bool IsEditorSelectionVisible () const
bool IsDisplaySettingsVisible () const
bool IsSessionSwitcherVisible () const
bool IsWelcomeScreenVisible () const
bool IsWelcomeScreenManuallyClosed () const
bool IsGlobalSearchVisible () const
bool IsPerformanceDashboardVisible () const
bool IsCardBrowserVisible () const
bool IsCommandPaletteVisible () const
bool IsCardSidebarVisible () const
bool IsImGuiDemoVisible () const
bool IsImGuiMetricsVisible () const
bool IsEmulatorVisible () const
bool IsMemoryEditorVisible () const
bool IsAsmEditorVisible () const
bool IsPaletteEditorVisible () const
bool IsResourceLabelManagerVisible () const
void SetEditorSelectionVisible (bool visible)
void SetDisplaySettingsVisible (bool visible)
void SetSessionSwitcherVisible (bool visible)
void SetWelcomeScreenVisible (bool visible)
void SetWelcomeScreenManuallyClosed (bool closed)
void SetGlobalSearchVisible (bool visible)
void SetPerformanceDashboardVisible (bool visible)
void SetCardBrowserVisible (bool visible)
void SetCommandPaletteVisible (bool visible)
void SetCardSidebarVisible (bool visible)
void SetImGuiDemoVisible (bool visible)
void SetImGuiMetricsVisible (bool visible)
void SetEmulatorVisible (bool visible)
void SetMemoryEditorVisible (bool visible)
void SetAsmEditorVisible (bool visible)
void SetPaletteEditorVisible (bool visible)
void SetResourceLabelManagerVisible (bool visible)
Private Member Functions
void DrawSessionIndicator ()
void DrawSessionTabs ()
void DrawSessionBadges ()
void DrawMaterialButton (const std::string &text, const std::string &icon, const ImVec4 &color, std::function< void()> callback, bool enabled=true)
void CenterWindow (const std::string &window_name)
void PositionWindow (const std::string &window_name, float x, float y)
void SetWindowSize (const std::string &window_name, float width, float height)
std::string GetIconForEditor (EditorType type) const
std::string GetColorForEditor (EditorType type) const
void ApplyEditorTheme (EditorType type)
Private Attributes
EditorManager * editor_manager_
RomFileManager & rom_manager_
ProjectManager & project_manager_
EditorRegistry & editor_registry_
EditorCardRegistry & card_registry_
SessionCoordinator & session_coordinator_
WindowDelegate & window_delegate_
ToastManager & toast_manager_
PopupManager & popup_manager_
ShortcutManager & shortcut_manager_
bool show_editor_selection_ = false
bool show_display_settings_ = false
bool show_welcome_screen_ = true
bool welcome_screen_manually_closed_ = false
bool show_global_search_ = false
bool show_performance_dashboard_ = false
bool show_imgui_demo_ = false
bool show_imgui_metrics_ = false
bool show_test_dashboard_ = false
bool show_card_browser_ = false
bool show_command_palette_ = false
bool show_emulator_ = false
bool show_memory_editor_ = false
bool show_asm_editor_ = false
bool show_palette_editor_ = false
bool show_resource_label_manager_ = false
bool show_save_workspace_preset_ = false
bool show_load_workspace_preset_ = false
bool show_card_sidebar_ = true
char command_palette_query_ [256] = {}
int command_palette_selected_idx_ = 0
char global_search_query_ [256] = {}
std::unique_ptr< WelcomeScreen > welcome_screen_
Detailed Description
Handles all UI drawing operations and state management.
Extracted from EditorManager to provide focused UI coordination:
Drawing operations (menus, dialogs, screens)
UI state management (visibility, focus, layout)
Popup and dialog coordination
Welcome screen and session UI
Material Design theming and icons
This class follows the Single Responsibility Principle by focusing solely on UI presentation and user interaction, delegating business logic to specialized managers.
Definition at line 41 of file ui_coordinator.h.
Constructor & Destructor Documentation
UICoordinator() [1/2]
yaze::editor::UICoordinator::UICoordinator (EditorManager * editor_manager, RomFileManager & rom_manager, ProjectManager & project_manager, EditorRegistry & editor_registry, EditorCardRegistry & card_registry, SessionCoordinator & session_coordinator, WindowDelegate & window_delegate, ToastManager & toast_manager, PopupManager & popup_manager, ShortcutManager & shortcut_manager)
Definition at line 31 of file ui_coordinator.cc.
References yaze::editor::EditorManager::CreateNewProject(), editor_manager_, yaze::editor::EditorManager::LoadRom(), yaze::editor::EditorManager::OpenRomOrProject(), and welcome_screen_.
~UICoordinator()
yaze::editor::UICoordinator::~UICoordinator () default
UICoordinator() [2/2]
yaze::editor::UICoordinator::UICoordinator (const UICoordinator &) delete
Member Function Documentation
operator=()
UICoordinator & yaze::editor::UICoordinator::operator= (const UICoordinator &) delete
DrawAllUI()
void yaze::editor::UICoordinator::DrawAllUI ()
Definition at line 103 of file ui_coordinator.cc.
References DrawCommandPalette(), DrawGlobalSearch(), DrawLayoutPresets(), DrawProjectHelp(), DrawWelcomeScreen(), DrawWindowManagementUI(), and DrawWorkspacePresetDialogs().
DrawMenuBarExtras()
void yaze::editor::UICoordinator::DrawMenuBarExtras ()
Definition at line 152 of file ui_coordinator.cc.
References editor_manager_, yaze::editor::SessionCoordinator::GetActiveSessionCount(), yaze::editor::EditorManager::GetCurrentRom(), yaze::gui::GetPrimaryActiveVec4(), yaze::gui::GetPrimaryHoverVec4(), yaze::gui::GetPrimaryVec4(), yaze::gui::GetTextDisabledVec4(), yaze::gui::GetTextSecondaryVec4(), yaze::editor::SessionCoordinator::HasMultipleSessions(), ICON_MD_CIRCLE, ICON_MD_INSERT_DRIVE_FILE, ICON_MD_TAB, ICON_MD_WARNING, session_coordinator_, yaze::editor::SessionCoordinator::ToggleSessionSwitcher(), and yaze::editor::EditorManager::version().
DrawContextSensitiveCardControl()
void yaze::editor::UICoordinator::DrawContextSensitiveCardControl ()
Definition at line 209 of file ui_coordinator.cc.
References card_registry_, editor_manager_, editor_registry_, yaze::editor::EditorCardRegistry::GetCardsInCategory(), yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::EditorManager::GetCurrentSessionId(), yaze::editor::EditorRegistry::GetEditorCategory(), yaze::gui::GetSurfaceContainerHighestVec4(), yaze::gui::GetSurfaceContainerHighVec4(), yaze::editor::EditorCardRegistry::HideCard(), ICON_MD_LAYERS, yaze::editor::EditorRegistry::IsCardBasedEditor(), and yaze::editor::EditorCardRegistry::ShowCard().
Referenced by DrawRomSelector().
DrawCommandPalette()
void yaze::editor::UICoordinator::DrawCommandPalette ()
Definition at line 515 of file ui_coordinator.cc.
References yaze::gui::LayoutHelpers::BeginTableWithTheming(), command_palette_query_, command_palette_selected_idx_, yaze::gui::ConvertColorToImVec4(), yaze::gui::LayoutHelpers::EndTableWithTheming(), yaze::gui::ThemeManager::Get(), yaze::gui::ThemeManager::GetCurrentTheme(), yaze::editor::ShortcutManager::GetShortcuts(), ICON_MD_CLEAR, ICON_MD_HISTORY, ICON_MD_INFO, ICON_MD_LIST, ICON_MD_SEARCH, ICON_MD_STAR, yaze::editor::PrintShortcut(), shortcut_manager_, and show_command_palette_.
Referenced by DrawAllUI().
DrawGlobalSearch()
void yaze::editor::UICoordinator::DrawGlobalSearch ()
Definition at line 672 of file ui_coordinator.cc.
References editor_manager_, yaze::editor::SessionCoordinator::GetActiveSessionCount(), yaze::editor::SessionCoordinator::GetActiveSessionIndex(), yaze::editor::EditorManager::GetCurrentRom(), yaze::util::GetFileExtension(), yaze::util::GetFileName(), yaze::project::RecentFilesManager::GetInstance(), yaze::editor::SessionCoordinator::GetSessionDisplayName(), yaze::editor::SessionCoordinator::GetTotalSessionCount(), global_search_query_, ICON_MD_CLEAR, ICON_MD_DESCRIPTION, ICON_MD_FOLDER, ICON_MD_HISTORY, ICON_MD_INFO, ICON_MD_LABEL, ICON_MD_MANAGE_SEARCH, ICON_MD_SEARCH, ICON_MD_TAB, ICON_MD_VIDEOGAME_ASSET, yaze::editor::kError, yaze::editor::EditorManager::OpenRomOrProject(), session_coordinator_, SetGlobalSearchVisible(), yaze::editor::ToastManager::Show(), show_global_search_, yaze::editor::EditorManager::SwitchToSession(), and toast_manager_.
Referenced by DrawAllUI().
DrawWorkspacePresetDialogs()
void yaze::editor::UICoordinator::DrawWorkspacePresetDialogs ()
Definition at line 350 of file ui_coordinator.cc.
References editor_manager_, yaze::gui::kDefaultModalSize, yaze::editor::kSuccess, yaze::editor::EditorManager::LoadWorkspacePreset(), yaze::editor::EditorManager::RefreshWorkspacePresets(), yaze::editor::EditorManager::SaveWorkspacePreset(), yaze::editor::ToastManager::Show(), show_load_workspace_preset_, show_save_workspace_preset_, toast_manager_, and yaze::editor::EditorManager::workspace_manager().
Referenced by DrawAllUI().
DrawSessionSwitcher()
void yaze::editor::UICoordinator::DrawSessionSwitcher ()
DrawSessionManager()
void yaze::editor::UICoordinator::DrawSessionManager ()
DrawSessionRenameDialog()
void yaze::editor::UICoordinator::DrawSessionRenameDialog ()
DrawLayoutPresets()
void yaze::editor::UICoordinator::DrawLayoutPresets ()
Todo:
[EditorManagerRefactor] Implement full layout preset UI with save/load
Definition at line 283 of file ui_coordinator.cc.
Referenced by DrawAllUI().
DrawWelcomeScreen()
void yaze::editor::UICoordinator::DrawWelcomeScreen ()
Definition at line 288 of file ui_coordinator.cc.
References editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), LOG_ERROR, show_welcome_screen_, welcome_screen_, and welcome_screen_manually_closed_.
Referenced by DrawAllUI().
DrawProjectHelp()
void yaze::editor::UICoordinator::DrawProjectHelp ()
Todo:
[EditorManagerRefactor] Implement project help dialog
Definition at line 345 of file ui_coordinator.cc.
Referenced by DrawAllUI().
DrawWindowManagementUI()
void yaze::editor::UICoordinator::DrawWindowManagementUI ()
Todo:
[EditorManagerRefactor] Implement window management dialog
Definition at line 394 of file ui_coordinator.cc.
Referenced by DrawAllUI().
DrawRomSelector()
void yaze::editor::UICoordinator::DrawRomSelector ()
Definition at line 118 of file ui_coordinator.cc.
References DrawContextSensitiveCardControl(), editor_manager_, yaze::editor::EditorManager::GetCurrentRom(), yaze::editor::SessionCoordinator::GetSession(), yaze::editor::SessionCoordinator::GetTotalSessionCount(), yaze::editor::SessionCoordinator::IsSessionClosed(), session_coordinator_, yaze::Rom::short_name(), and yaze::editor::EditorManager::SwitchToSession().
DrawAllPopups()
void yaze::editor::UICoordinator::DrawAllPopups ()
Definition at line 399 of file ui_coordinator.cc.
References yaze::editor::PopupManager::DrawPopups(), and popup_manager_.
ShowPopup()
void yaze::editor::UICoordinator::ShowPopup (const std::string & popup_name)
Definition at line 404 of file ui_coordinator.cc.
References popup_manager_, and yaze::editor::PopupManager::Show().
HidePopup()
void yaze::editor::UICoordinator::HidePopup (const std::string & popup_name)
Definition at line 408 of file ui_coordinator.cc.
References yaze::editor::PopupManager::Hide(), and popup_manager_.
ShowEditorSelection()
void yaze::editor::UICoordinator::ShowEditorSelection () inline
Definition at line 90 of file ui_coordinator.h.
References show_editor_selection_.
ShowDisplaySettings()
void yaze::editor::UICoordinator::ShowDisplaySettings ()
Definition at line 412 of file ui_coordinator.cc.
References yaze::editor::PopupID::kDisplaySettings, popup_manager_, and yaze::editor::PopupManager::Show().
ShowSaveWorkspacePresetDialog()
void yaze::editor::UICoordinator::ShowSaveWorkspacePresetDialog () inline
Definition at line 92 of file ui_coordinator.h.
References show_save_workspace_preset_.
ShowLoadWorkspacePresetDialog()
void yaze::editor::UICoordinator::ShowLoadWorkspacePresetDialog () inline
Definition at line 93 of file ui_coordinator.h.
References show_load_workspace_preset_.
ShowSessionSwitcher()
void yaze::editor::UICoordinator::ShowSessionSwitcher ()
Definition at line 263 of file ui_coordinator.cc.
References session_coordinator_, and yaze::editor::SessionCoordinator::ShowSessionSwitcher().
HideCurrentEditorCards()
void yaze::editor::UICoordinator::HideCurrentEditorCards ()
Definition at line 418 of file ui_coordinator.cc.
References card_registry_, editor_manager_, editor_registry_, yaze::editor::EditorManager::GetCurrentEditor(), yaze::editor::EditorRegistry::GetEditorCategory(), yaze::editor::EditorCardRegistry::HideAllCardsInCategory(), and LOG_INFO.
ToggleCardSidebar()
void yaze::editor::UICoordinator::ToggleCardSidebar () inline
Definition at line 97 of file ui_coordinator.h.
References show_card_sidebar_.
ShowGlobalSearch()
void yaze::editor::UICoordinator::ShowGlobalSearch () inline
Definition at line 98 of file ui_coordinator.h.
References show_global_search_.
ShowCommandPalette()
void yaze::editor::UICoordinator::ShowCommandPalette () inline
Definition at line 99 of file ui_coordinator.h.
References show_command_palette_.
ShowCardBrowser()
void yaze::editor::UICoordinator::ShowCardBrowser () inline
Definition at line 100 of file ui_coordinator.h.
References show_card_browser_.
ShowAllWindows()
void yaze::editor::UICoordinator::ShowAllWindows ()
Definition at line 430 of file ui_coordinator.cc.
References yaze::editor::WindowDelegate::ShowAllWindows(), and window_delegate_.
HideAllWindows()
void yaze::editor::UICoordinator::HideAllWindows ()
Definition at line 434 of file ui_coordinator.cc.
References yaze::editor::WindowDelegate::HideAllWindows(), and window_delegate_.
IsEditorSelectionVisible()
bool yaze::editor::UICoordinator::IsEditorSelectionVisible () const inline
Definition at line 107 of file ui_coordinator.h.
References show_editor_selection_.
IsDisplaySettingsVisible()
bool yaze::editor::UICoordinator::IsDisplaySettingsVisible () const inline
Definition at line 108 of file ui_coordinator.h.
References show_display_settings_.
IsSessionSwitcherVisible()
bool yaze::editor::UICoordinator::IsSessionSwitcherVisible () const
Definition at line 267 of file ui_coordinator.cc.
References yaze::editor::SessionCoordinator::IsSessionSwitcherVisible(), and session_coordinator_.
IsWelcomeScreenVisible()
bool yaze::editor::UICoordinator::IsWelcomeScreenVisible () const inline
Definition at line 111 of file ui_coordinator.h.
References show_welcome_screen_.
IsWelcomeScreenManuallyClosed()
bool yaze::editor::UICoordinator::IsWelcomeScreenManuallyClosed () const inline
Definition at line 112 of file ui_coordinator.h.
References welcome_screen_manually_closed_.
IsGlobalSearchVisible()
bool yaze::editor::UICoordinator::IsGlobalSearchVisible () const inline
Definition at line 113 of file ui_coordinator.h.
References show_global_search_.
IsPerformanceDashboardVisible()
bool yaze::editor::UICoordinator::IsPerformanceDashboardVisible () const inline
Definition at line 114 of file ui_coordinator.h.
References show_performance_dashboard_.
IsCardBrowserVisible()
bool yaze::editor::UICoordinator::IsCardBrowserVisible () const inline
Definition at line 115 of file ui_coordinator.h.
References show_card_browser_.
IsCommandPaletteVisible()
bool yaze::editor::UICoordinator::IsCommandPaletteVisible () const inline
Definition at line 116 of file ui_coordinator.h.
References show_command_palette_.
IsCardSidebarVisible()
bool yaze::editor::UICoordinator::IsCardSidebarVisible () const inline
Definition at line 117 of file ui_coordinator.h.
References show_card_sidebar_.
IsImGuiDemoVisible()
bool yaze::editor::UICoordinator::IsImGuiDemoVisible () const inline
Definition at line 118 of file ui_coordinator.h.
References show_imgui_demo_.
IsImGuiMetricsVisible()
bool yaze::editor::UICoordinator::IsImGuiMetricsVisible () const inline
Definition at line 119 of file ui_coordinator.h.
References show_imgui_metrics_.
IsEmulatorVisible()
bool yaze::editor::UICoordinator::IsEmulatorVisible () const inline
Definition at line 120 of file ui_coordinator.h.
References show_emulator_.
IsMemoryEditorVisible()
bool yaze::editor::UICoordinator::IsMemoryEditorVisible () const inline
Definition at line 121 of file ui_coordinator.h.
References show_memory_editor_.
IsAsmEditorVisible()
bool yaze::editor::UICoordinator::IsAsmEditorVisible () const inline
Definition at line 122 of file ui_coordinator.h.
References show_asm_editor_.
IsPaletteEditorVisible()
bool yaze::editor::UICoordinator::IsPaletteEditorVisible () const inline
Definition at line 123 of file ui_coordinator.h.
References show_palette_editor_.
IsResourceLabelManagerVisible()
bool yaze::editor::UICoordinator::IsResourceLabelManagerVisible () const inline
Definition at line 124 of file ui_coordinator.h.
References show_resource_label_manager_.
SetEditorSelectionVisible()
void yaze::editor::UICoordinator::SetEditorSelectionVisible (bool visible) inline
Definition at line 127 of file ui_coordinator.h.
References show_editor_selection_.
SetDisplaySettingsVisible()
void yaze::editor::UICoordinator::SetDisplaySettingsVisible (bool visible) inline
Definition at line 128 of file ui_coordinator.h.
References show_display_settings_.
SetSessionSwitcherVisible()
void yaze::editor::UICoordinator::SetSessionSwitcherVisible (bool visible)
Definition at line 271 of file ui_coordinator.cc.
References yaze::editor::SessionCoordinator::HideSessionSwitcher(), session_coordinator_, and yaze::editor::SessionCoordinator::ShowSessionSwitcher().
SetWelcomeScreenVisible()
void yaze::editor::UICoordinator::SetWelcomeScreenVisible (bool visible) inline
Definition at line 131 of file ui_coordinator.h.
References show_welcome_screen_.
SetWelcomeScreenManuallyClosed()
void yaze::editor::UICoordinator::SetWelcomeScreenManuallyClosed (bool closed) inline
Definition at line 132 of file ui_coordinator.h.
References welcome_screen_manually_closed_.
SetGlobalSearchVisible()
void yaze::editor::UICoordinator::SetGlobalSearchVisible (bool visible) inline
Definition at line 133 of file ui_coordinator.h.
References show_global_search_.
Referenced by DrawGlobalSearch().
SetPerformanceDashboardVisible()
void yaze::editor::UICoordinator::SetPerformanceDashboardVisible (bool visible) inline
Definition at line 134 of file ui_coordinator.h.
References show_performance_dashboard_.
SetCardBrowserVisible()
void yaze::editor::UICoordinator::SetCardBrowserVisible (bool visible) inline
Definition at line 135 of file ui_coordinator.h.
References show_card_browser_.
SetCommandPaletteVisible()
void yaze::editor::UICoordinator::SetCommandPaletteVisible (bool visible) inline
Definition at line 136 of file ui_coordinator.h.
References show_command_palette_.
SetCardSidebarVisible()
void yaze::editor::UICoordinator::SetCardSidebarVisible (bool visible) inline
Definition at line 137 of file ui_coordinator.h.
References show_card_sidebar_.
SetImGuiDemoVisible()
void yaze::editor::UICoordinator::SetImGuiDemoVisible (bool visible) inline
Definition at line 138 of file ui_coordinator.h.
References show_imgui_demo_.
SetImGuiMetricsVisible()
void yaze::editor::UICoordinator::SetImGuiMetricsVisible (bool visible) inline
Definition at line 139 of file ui_coordinator.h.
References show_imgui_metrics_.
SetEmulatorVisible()
void yaze::editor::UICoordinator::SetEmulatorVisible (bool visible) inline
Definition at line 140 of file ui_coordinator.h.
References show_emulator_.
SetMemoryEditorVisible()
void yaze::editor::UICoordinator::SetMemoryEditorVisible (bool visible) inline
Definition at line 141 of file ui_coordinator.h.
References show_memory_editor_.
SetAsmEditorVisible()
void yaze::editor::UICoordinator::SetAsmEditorVisible (bool visible) inline
Definition at line 142 of file ui_coordinator.h.
References show_asm_editor_.
SetPaletteEditorVisible()
void yaze::editor::UICoordinator::SetPaletteEditorVisible (bool visible) inline
Definition at line 143 of file ui_coordinator.h.
References show_palette_editor_.
SetResourceLabelManagerVisible()
void yaze::editor::UICoordinator::SetResourceLabelManagerVisible (bool visible) inline
Definition at line 144 of file ui_coordinator.h.
References show_resource_label_manager_.
DrawSessionIndicator()
void yaze::editor::UICoordinator::DrawSessionIndicator () private
Todo:
[EditorManagerRefactor] Implement session indicator in menu bar
Definition at line 439 of file ui_coordinator.cc.
DrawSessionTabs()
void yaze::editor::UICoordinator::DrawSessionTabs () private
Todo:
[EditorManagerRefactor] Implement session tabs UI
Definition at line 443 of file ui_coordinator.cc.
DrawSessionBadges()
void yaze::editor::UICoordinator::DrawSessionBadges () private
Todo:
[EditorManagerRefactor] Implement session status badges
Definition at line 447 of file ui_coordinator.cc.
DrawMaterialButton()
void yaze::editor::UICoordinator::DrawMaterialButton (const std::string & text, const std::string & icon, const ImVec4 & color, std::function< void()> callback, bool enabled = true) private
Definition at line 452 of file ui_coordinator.cc.
References yaze::gui::GetOnSurfaceVariantVec4(), and yaze::gui::GetSurfaceContainerHighestVec4().
CenterWindow()
void yaze::editor::UICoordinator::CenterWindow (const std::string & window_name) private
Definition at line 473 of file ui_coordinator.cc.
PositionWindow()
void yaze::editor::UICoordinator::PositionWindow (const std::string & window_name, float x, float y) private
Definition at line 477 of file ui_coordinator.cc.
SetWindowSize()
void yaze::editor::UICoordinator::SetWindowSize (const std::string & window_name, float width, float height) private
Definition at line 481 of file ui_coordinator.cc.
GetIconForEditor()
std::string yaze::editor::UICoordinator::GetIconForEditor (EditorType type) const private
Definition at line 486 of file ui_coordinator.cc.
References ICON_MD_CASTLE, ICON_MD_CHAT_BUBBLE, ICON_MD_CODE, ICON_MD_DATA_ARRAY, ICON_MD_HELP, ICON_MD_IMAGE, ICON_MD_MAP, ICON_MD_MUSIC_NOTE, ICON_MD_PALETTE, ICON_MD_PLAY_ARROW, ICON_MD_SETTINGS, ICON_MD_TOYS, ICON_MD_TV, yaze::editor::kAssembly, yaze::editor::kDungeon, yaze::editor::kEmulator, yaze::editor::kGraphics, yaze::editor::kHex, yaze::editor::kMessage, yaze::editor::kMusic, yaze::editor::kOverworld, yaze::editor::kPalette, yaze::editor::kScreen, yaze::editor::kSettings, and yaze::editor::kSprite.
GetColorForEditor()
std::string yaze::editor::UICoordinator::GetColorForEditor (EditorType type) const private
Todo:
[EditorManagerRefactor] Map editor types to theme colors
Definition at line 504 of file ui_coordinator.cc.
ApplyEditorTheme()
void yaze::editor::UICoordinator::ApplyEditorTheme (EditorType type) private
Todo:
[EditorManagerRefactor] Apply editor-specific theme overrides
Definition at line 510 of file ui_coordinator.cc.
Member Data Documentation
editor_manager_
EditorManager* yaze::editor::UICoordinator::editor_manager_ private
Definition at line 150 of file ui_coordinator.h.
Referenced by DrawContextSensitiveCardControl(), DrawGlobalSearch(), DrawMenuBarExtras(), DrawRomSelector(), DrawWelcomeScreen(), DrawWorkspacePresetDialogs(), HideCurrentEditorCards(), and UICoordinator().
rom_manager_
RomFileManager& yaze::editor::UICoordinator::rom_manager_ private
Definition at line 151 of file ui_coordinator.h.
project_manager_
ProjectManager& yaze::editor::UICoordinator::project_manager_ private
Definition at line 152 of file ui_coordinator.h.
editor_registry_
EditorRegistry& yaze::editor::UICoordinator::editor_registry_ private
Definition at line 153 of file ui_coordinator.h.
Referenced by DrawContextSensitiveCardControl(), and HideCurrentEditorCards().
card_registry_
EditorCardRegistry& yaze::editor::UICoordinator::card_registry_ private
Definition at line 154 of file ui_coordinator.h.
Referenced by DrawContextSensitiveCardControl(), and HideCurrentEditorCards().
session_coordinator_
SessionCoordinator& yaze::editor::UICoordinator::session_coordinator_ private
Definition at line 155 of file ui_coordinator.h.
Referenced by DrawGlobalSearch(), DrawMenuBarExtras(), DrawRomSelector(), IsSessionSwitcherVisible(), SetSessionSwitcherVisible(), and ShowSessionSwitcher().
window_delegate_
WindowDelegate& yaze::editor::UICoordinator::window_delegate_ private
Definition at line 156 of file ui_coordinator.h.
Referenced by HideAllWindows(), and ShowAllWindows().
toast_manager_
ToastManager& yaze::editor::UICoordinator::toast_manager_ private
Definition at line 157 of file ui_coordinator.h.
Referenced by DrawGlobalSearch(), and DrawWorkspacePresetDialogs().
popup_manager_
PopupManager& yaze::editor::UICoordinator::popup_manager_ private
Definition at line 158 of file ui_coordinator.h.
Referenced by DrawAllPopups(), HidePopup(), ShowDisplaySettings(), and ShowPopup().
shortcut_manager_
ShortcutManager& yaze::editor::UICoordinator::shortcut_manager_ private
Definition at line 159 of file ui_coordinator.h.
Referenced by DrawCommandPalette().
show_editor_selection_
bool yaze::editor::UICoordinator::show_editor_selection_ = false private
Definition at line 162 of file ui_coordinator.h.
Referenced by IsEditorSelectionVisible(), SetEditorSelectionVisible(), and ShowEditorSelection().
show_display_settings_
bool yaze::editor::UICoordinator::show_display_settings_ = false private
Definition at line 163 of file ui_coordinator.h.
Referenced by IsDisplaySettingsVisible(), and SetDisplaySettingsVisible().
show_welcome_screen_
bool yaze::editor::UICoordinator::show_welcome_screen_ = true private
Definition at line 165 of file ui_coordinator.h.
Referenced by DrawWelcomeScreen(), IsWelcomeScreenVisible(), and SetWelcomeScreenVisible().
welcome_screen_manually_closed_
bool yaze::editor::UICoordinator::welcome_screen_manually_closed_ = false private
Definition at line 166 of file ui_coordinator.h.
Referenced by DrawWelcomeScreen(), IsWelcomeScreenManuallyClosed(), and SetWelcomeScreenManuallyClosed().
show_global_search_
bool yaze::editor::UICoordinator::show_global_search_ = false private
Definition at line 167 of file ui_coordinator.h.
Referenced by DrawGlobalSearch(), IsGlobalSearchVisible(), SetGlobalSearchVisible(), and ShowGlobalSearch().
show_performance_dashboard_
bool yaze::editor::UICoordinator::show_performance_dashboard_ = false private
Definition at line 168 of file ui_coordinator.h.
Referenced by IsPerformanceDashboardVisible(), and SetPerformanceDashboardVisible().
show_imgui_demo_
bool yaze::editor::UICoordinator::show_imgui_demo_ = false private
Definition at line 169 of file ui_coordinator.h.
Referenced by IsImGuiDemoVisible(), and SetImGuiDemoVisible().
show_imgui_metrics_
bool yaze::editor::UICoordinator::show_imgui_metrics_ = false private
Definition at line 170 of file ui_coordinator.h.
Referenced by IsImGuiMetricsVisible(), and SetImGuiMetricsVisible().
show_test_dashboard_
bool yaze::editor::UICoordinator::show_test_dashboard_ = false private
Definition at line 171 of file ui_coordinator.h.
show_card_browser_
bool yaze::editor::UICoordinator::show_card_browser_ = false private
Definition at line 172 of file ui_coordinator.h.
Referenced by IsCardBrowserVisible(), SetCardBrowserVisible(), and ShowCardBrowser().
show_command_palette_
bool yaze::editor::UICoordinator::show_command_palette_ = false private
Definition at line 173 of file ui_coordinator.h.
Referenced by DrawCommandPalette(), IsCommandPaletteVisible(), SetCommandPaletteVisible(), and ShowCommandPalette().
show_emulator_
bool yaze::editor::UICoordinator::show_emulator_ = false private
Definition at line 174 of file ui_coordinator.h.
Referenced by IsEmulatorVisible(), and SetEmulatorVisible().
show_memory_editor_
bool yaze::editor::UICoordinator::show_memory_editor_ = false private
Definition at line 175 of file ui_coordinator.h.
Referenced by IsMemoryEditorVisible(), and SetMemoryEditorVisible().
show_asm_editor_
bool yaze::editor::UICoordinator::show_asm_editor_ = false private
Definition at line 176 of file ui_coordinator.h.
Referenced by IsAsmEditorVisible(), and SetAsmEditorVisible().
show_palette_editor_
bool yaze::editor::UICoordinator::show_palette_editor_ = false private
Definition at line 177 of file ui_coordinator.h.
Referenced by IsPaletteEditorVisible(), and SetPaletteEditorVisible().
show_resource_label_manager_
bool yaze::editor::UICoordinator::show_resource_label_manager_ = false private
Definition at line 178 of file ui_coordinator.h.
Referenced by IsResourceLabelManagerVisible(), and SetResourceLabelManagerVisible().
show_save_workspace_preset_
bool yaze::editor::UICoordinator::show_save_workspace_preset_ = false private
Definition at line 179 of file ui_coordinator.h.
Referenced by DrawWorkspacePresetDialogs(), and ShowSaveWorkspacePresetDialog().
show_load_workspace_preset_
bool yaze::editor::UICoordinator::show_load_workspace_preset_ = false private
Definition at line 180 of file ui_coordinator.h.
Referenced by DrawWorkspacePresetDialogs(), and ShowLoadWorkspacePresetDialog().
show_card_sidebar_
bool yaze::editor::UICoordinator::show_card_sidebar_ = true private
Definition at line 181 of file ui_coordinator.h.
Referenced by IsCardSidebarVisible(), SetCardSidebarVisible(), and ToggleCardSidebar().
command_palette_query_
char yaze::editor::UICoordinator::command_palette_query_[256] = {} private
Definition at line 184 of file ui_coordinator.h.
Referenced by DrawCommandPalette().
command_palette_selected_idx_
int yaze::editor::UICoordinator::command_palette_selected_idx_ = 0 private
Definition at line 185 of file ui_coordinator.h.
Referenced by DrawCommandPalette().
global_search_query_
char yaze::editor::UICoordinator::global_search_query_[256] = {} private
Definition at line 188 of file ui_coordinator.h.
Referenced by DrawGlobalSearch().
welcome_screen_
std::unique_ptr<WelcomeScreen> yaze::editor::UICoordinator::welcome_screen_ private
Definition at line 191 of file ui_coordinator.h.
Referenced by DrawWelcomeScreen(), and UICoordinator().
The documentation for this class was generated from the following files:
src/app/editor/ui/ui_coordinator.h
src/app/editor/ui/ui_coordinator.cc