yaze: yaze::core::Renderer Class Reference
yaze::core::Renderer Class Reference
The Renderer class represents the renderer for the Yaze application.
#include <window.h>
Public Member Functions
absl::Status CreateRenderer (SDL_Window *window)
Initialize the SDL renderer on the main thread.
auto renderer () -> SDL_Renderer *
void RenderBitmap (gfx::Bitmap *bitmap)
Create texture for bitmap on main thread.
void UpdateBitmap (gfx::Bitmap *bitmap)
Update existing texture on main thread.
void CreateAndRenderBitmap (int width, int height, int depth, const std::vector< uint8_t > &data, gfx::Bitmap &bitmap, gfx::SnesPalette &palette)
Create bitmap and immediately create texture (blocking operation)
void CreateBitmapWithoutTexture (int width, int height, int depth, const std::vector< uint8_t > &data, gfx::Bitmap &bitmap, gfx::SnesPalette &palette)
Create bitmap without creating texture (non-blocking)
void BatchCreateTextures (std::vector< gfx::Bitmap * > &bitmaps)
Batch create textures for multiple bitmaps.
void Clear ()
void Present ()
Static Public Member Functions
static Renderer & Get ()
Private Member Functions
Renderer ()=default
Renderer (const Renderer &)=delete
Renderer & operator= (const Renderer &)=delete
Private Attributes
std::unique_ptr< SDL_Renderer, util::SDL_Deleter > renderer_
Detailed Description
The Renderer class represents the renderer for the Yaze application.
This class is a singleton that provides functionality for creating and rendering bitmaps to the screen. It also includes methods for updating bitmaps on the screen.
IMPORTANT: This class MUST be used only on the main thread because:
SDL_Renderer operations are not thread-safe
OpenGL/DirectX contexts are bound to the creating thread
Texture creation and rendering must happen on the main UI thread
For performance optimization during ROM loading:
Use deferred texture creation (CreateBitmapWithoutTexture) for bulk operations
Batch texture creation operations when possible
Consider background processing of bitmap data before texture creation
Definition at line 45 of file window.h.
Constructor & Destructor Documentation
Renderer() [1/2]
yaze::core::Renderer::Renderer () private default
Renderer() [2/2]
yaze::core::Renderer::Renderer (const Renderer &) private delete
Member Function Documentation
Get()
static Renderer & yaze::core::Renderer::Get () inline static
Definition at line 47 of file window.h.
Referenced by yaze::gui::CanvasUtils::ApplyPaletteGroup(), yaze::gui::PaletteWidget::ApplyROMPalette(), yaze::zelda3::Inventory::BuildTileset(), yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::OverworldEditor::ClearScratchSpace(), yaze::editor::Tile16Editor::ClearTile16(), yaze::editor::Tile16Editor::CommitChangesToBlockset(), yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::gui::Canvas::ConvertBitmapFormat(), yaze::editor::Tile16Editor::CopyTile16ToClipboard(), yaze::zelda3::Inventory::Create(), yaze::gfx::CreateTilemap(), yaze::core::CreateWindow(), yaze::editor::GraphicsEditor::DecompressImportData(), yaze::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::core::Controller::DoRender(), yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::GraphicsEditor::DrawCgxImport(), yaze::editor::ScreenEditor::DrawDungeonMapScreen(), yaze::editor::ScreenEditor::DrawDungeonMapsRoomGfx(), yaze::editor::MessageEditor::DrawMessagePreview(), yaze::editor::DungeonObjectSelector::DrawObjectRenderer(), yaze::editor::OverworldEditor::DrawScratchSpace(), yaze::editor::GraphicsEditor::DrawScrImport(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::gui::DungeonObjectEmulatorPreview::DungeonObjectEmulatorPreview(), yaze::editor::OverworldEditor::EnsureMapTexture(), yaze::editor::Tile16Editor::FillTile16WithTile8(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::test::EditorIntegrationTest::Initialize(), yaze::editor::MessageEditor::Initialize(), yaze::editor::Tile16Editor::Initialize(), yaze::LoadAllGraphicsData(), yaze::editor::ScreenEditor::LoadBinaryGfx(), yaze::zelda3::LoadDungeonMapGfxFromBinary(), yaze::zelda3::LoadDungeonMapTile16(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::LoadLinkGraphics(), yaze::editor::OverworldEditor::LoadSpriteGraphics(), yaze::editor::Tile16Editor::LoadTile16FromScratchSpace(), yaze::editor::Tile16Editor::LoadTile8(), main(), yaze::editor::Tile16Editor::PasteTile16FromClipboard(), yaze::editor::Tile16Editor::PreviewPaletteChange(), yaze::editor::OverworldEditor::ProcessDeferredTextures(), yaze::editor::Tile16Editor::Redo(), yaze::editor::Tile16Editor::RefreshAllPalettes(), yaze::editor::OverworldEditor::RefreshChildMapOnDemand(), yaze::editor::DungeonEditor::RefreshGraphics(), yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), yaze::editor::Tile16Editor::RefreshTile16Blockset(), yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM(), yaze::gui::canvas::CanvasContextMenu::RenderBitmapOperationsMenu(), yaze::editor::DungeonCanvasViewer::RenderObjectInCanvas(), yaze::editor::DungeonRenderer::RenderObjectInCanvas(), yaze::editor::DungeonCanvasViewer::RenderRoomBackgroundLayers(), yaze::zelda3::Room::RenderRoomGraphics(), yaze::gfx::RenderTilesBatch(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), yaze::editor::Tile16Editor::RotateTile16(), yaze::emu::Emulator::Run(), yaze::test::RunIntegrationTest(), yaze::editor::OverworldEditor::SaveCurrentSelectionToScratch(), yaze::editor::Tile16Editor::SaveTile16ToScratchSpace(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::editor::test::Tile16EditorIntegrationTest::SetUp(), yaze::core::ShutdownWindow(), yaze::editor::Tile16Editor::Undo(), yaze::editor::GraphicsEditor::UpdateGfxTabView(), yaze::editor::Tile16Editor::UpdateOverworldTilemap(), yaze::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::editor::DungeonCanvasViewer::UpdateRoomBackgroundLayers(), yaze::editor::OverworldEditor::UpdateScratchBitmapTile(), yaze::gfx::UpdateTile16(), yaze::editor::Tile16Editor::UpdateTile16Edit(), yaze::editor::Tile16Editor::UpdateTile8Palette(), and yaze::gfx::UpdateTilemap().
CreateRenderer()
absl::Status yaze::core::Renderer::CreateRenderer (SDL_Window * window) inline
Initialize the SDL renderer on the main thread.
This MUST be called from the main thread as SDL renderer operations are not thread-safe and require the OpenGL/DirectX context to be bound to the calling thread.
Definition at line 59 of file window.h.
References renderer_.
Referenced by main().
renderer()
auto yaze::core::Renderer::renderer () -> SDL_Renderer * inline
Definition at line 71 of file window.h.
References renderer_.
Referenced by yaze::core::CreateWindow(), yaze::test::EditorIntegrationTest::Initialize(), yaze::LoadAllGraphicsData(), main(), yaze::test::RunIntegrationTest(), yaze::editor::GraphicsEditor::UpdateGfxTabView(), and yaze::editor::OverworldEditor::UpdateScratchBitmapTile().
RenderBitmap()
void yaze::core::Renderer::RenderBitmap (gfx::Bitmap * bitmap) inline
Create texture for bitmap on main thread.
This operation blocks the main thread and should be used sparingly during bulk loading operations. Consider using CreateBitmapWithoutTexture followed by batch texture creation.
Definition at line 80 of file window.h.
References yaze::gfx::Bitmap::CreateTexture(), and renderer_.
Referenced by yaze::zelda3::Inventory::BuildTileset(), yaze::editor::Tile16Editor::CopyTile16ToClipboard(), yaze::zelda3::Inventory::Create(), CreateAndRenderBitmap(), yaze::gfx::CreateTilemap(), yaze::editor::GraphicsEditor::DecompressImportData(), yaze::editor::GraphicsEditor::DecompressSuperDonkey(), yaze::editor::GraphicsEditor::DrawCgxImport(), yaze::editor::ScreenEditor::DrawDungeonMapScreen(), yaze::editor::ScreenEditor::DrawDungeonMapsRoomGfx(), yaze::editor::DungeonObjectSelector::DrawObjectRenderer(), yaze::editor::OverworldEditor::DrawScratchSpace(), yaze::editor::GraphicsEditor::DrawScrImport(), yaze::editor::OverworldEditor::EnsureMapTexture(), yaze::editor::Tile16Editor::Initialize(), yaze::editor::ScreenEditor::LoadBinaryGfx(), yaze::zelda3::LoadDungeonMapGfxFromBinary(), yaze::zelda3::LoadDungeonMapTile16(), yaze::editor::OverworldEditor::LoadGraphics(), yaze::LoadLinkGraphics(), yaze::editor::OverworldEditor::LoadSpriteGraphics(), yaze::editor::Tile16Editor::LoadTile16FromScratchSpace(), yaze::editor::Tile16Editor::LoadTile8(), yaze::editor::Tile16Editor::PasteTile16FromClipboard(), yaze::editor::OverworldEditor::ProcessDeferredTextures(), yaze::editor::OverworldEditor::RefreshChildMapOnDemand(), yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM(), yaze::editor::DungeonCanvasViewer::RenderObjectInCanvas(), yaze::editor::DungeonRenderer::RenderObjectInCanvas(), yaze::editor::DungeonCanvasViewer::RenderRoomBackgroundLayers(), yaze::zelda3::Room::RenderRoomGraphics(), yaze::gfx::RenderTilesBatch(), yaze::editor::OverworldEditor::SaveCurrentSelectionToScratch(), yaze::editor::Tile16Editor::SaveTile16ToScratchSpace(), yaze::editor::Tile16Editor::SetCurrentTile(), and yaze::editor::Tile16Editor::UpdateTile16Edit().
UpdateBitmap()
void yaze::core::Renderer::UpdateBitmap (gfx::Bitmap * bitmap) inline
Update existing texture on main thread.
Definition at line 87 of file window.h.
References renderer_, and yaze::gfx::Bitmap::UpdateTexture().
Referenced by yaze::gui::CanvasUtils::ApplyPaletteGroup(), yaze::gui::PaletteWidget::ApplyROMPalette(), yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::OverworldEditor::ClearScratchSpace(), yaze::editor::Tile16Editor::ClearTile16(), yaze::editor::Tile16Editor::CommitChangesToBlockset(), yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::gui::Canvas::ConvertBitmapFormat(), yaze::editor::MessageEditor::DrawMessagePreview(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::editor::Tile16Editor::FillTile16WithTile8(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::editor::Tile16Editor::PreviewPaletteChange(), yaze::editor::Tile16Editor::Redo(), yaze::editor::Tile16Editor::RefreshAllPalettes(), yaze::editor::DungeonEditor::RefreshGraphics(), yaze::editor::OverworldEditor::RefreshMultiAreaMapsSafely(), yaze::editor::Tile16Editor::RefreshTile16Blockset(), yaze::gui::canvas::CanvasContextMenu::RenderBitmapOperationsMenu(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), yaze::editor::Tile16Editor::RotateTile16(), yaze::editor::Tile16Editor::Undo(), yaze::editor::Tile16Editor::UpdateOverworldTilemap(), yaze::editor::GraphicsEditor::UpdatePaletteColumn(), yaze::editor::DungeonCanvasViewer::UpdateRoomBackgroundLayers(), yaze::gfx::UpdateTile16(), yaze::editor::Tile16Editor::UpdateTile8Palette(), and yaze::gfx::UpdateTilemap().
CreateAndRenderBitmap()
void yaze::core::Renderer::CreateAndRenderBitmap (int width, int height, int depth, const std::vector< uint8_t > & data, gfx::Bitmap & bitmap, gfx::SnesPalette & palette) inline
Create bitmap and immediately create texture (blocking operation)
This is the original method that blocks during texture creation. For performance during ROM loading, consider using CreateBitmapWithoutTexture and deferring texture creation until needed.
Definition at line 98 of file window.h.
References yaze::gfx::Bitmap::Create(), RenderBitmap(), and yaze::gfx::Bitmap::SetPalette().
Referenced by yaze::editor::OverworldEditor::DrawAreaGraphics(), yaze::editor::MessageEditor::DrawMessagePreview(), yaze::editor::MessageEditor::Initialize(), and yaze::editor::test::Tile16EditorIntegrationTest::SetUp().
CreateBitmapWithoutTexture()
void yaze::core::Renderer::CreateBitmapWithoutTexture (int width, int height, int depth, const std::vector< uint8_t > & data, gfx::Bitmap & bitmap, gfx::SnesPalette & palette) inline
Create bitmap without creating texture (non-blocking)
This method prepares the bitmap data and surface but doesn't create the GPU texture, allowing for faster bulk operations during ROM loading. Texture creation can be deferred until the bitmap is actually needed for rendering.
Definition at line 114 of file window.h.
References yaze::gfx::Bitmap::Create(), and yaze::gfx::Bitmap::SetPalette().
Referenced by yaze::editor::OverworldEditor::LoadGraphics().
BatchCreateTextures()
void yaze::core::Renderer::BatchCreateTextures (std::vector< gfx::Bitmap * > & bitmaps) inline
Batch create textures for multiple bitmaps.
This method can be used to efficiently create textures for multiple bitmaps that have already been prepared with CreateBitmapWithoutTexture. Useful for deferred texture creation during ROM loading.
Definition at line 129 of file window.h.
References renderer_.
Clear()
void yaze::core::Renderer::Clear () inline
Definition at line 137 of file window.h.
References renderer_.
Referenced by main().
Present()
void yaze::core::Renderer::Present () inline
Definition at line 142 of file window.h.
References renderer_.
Referenced by main().
operator=()
Renderer & yaze::core::Renderer::operator= (const Renderer &) private delete
Member Data Documentation
renderer_
std::unique_ptr<SDL_Renderer, util::SDL_Deleter> yaze::core::Renderer::renderer_ private
Definition at line 147 of file window.h.
Referenced by BatchCreateTextures(), Clear(), CreateRenderer(), Present(), RenderBitmap(), renderer(), and UpdateBitmap().
The documentation for this class was generated from the following file:
src/app/core/window.h