yaze: yaze::cli::GfxExport Class Reference
yaze::cli::GfxExport Class Reference
#include <z3ed.h>
Public Member Functions
absl::Status Run (const std::vector< std::string > &arg_vec) override
Public Member Functions inherited from yaze::cli::CommandHandler
CommandHandler ()=default
virtual ~CommandHandler ()=default
virtual void RunTUI (ftxui::ScreenInteractive &screen)
Additional Inherited Members
Public Attributes inherited from yaze::cli::CommandHandler
Rom rom_
Detailed Description
Definition at line 61 of file z3ed.h.
Member Function Documentation
Run()
absl::Status yaze::cli::GfxExport::Run (const std::vector< std::string > & arg_vec) override virtual
Todo:
Convert the 8bpp data to the correct SNES bpp format.
Implements yaze::cli::CommandHandler.
Definition at line 12 of file gfx.cc.
References yaze::gfx::Arena::Get(), yaze::Rom::is_loaded(), yaze::Rom::LoadFromFile(), yaze::cli::CommandHandler::rom_, and yaze::gfx::SaveCgx().
Referenced by yaze::cli::ModernCLI::HandleGfxExportCommand().
The documentation for this class was generated from the following files:
src/cli/z3ed.h
src/cli/handlers/gfx.cc