yaze: yaze::test::gui Namespace Reference
yaze::test::gui Namespace Reference
Functions
void LoadRomInTest (ImGuiTestContext *ctx, const std::string &rom_path)
void OpenEditorInTest (ImGuiTestContext *ctx, const std::string &editor_name)
Function Documentation
LoadRomInTest()
void yaze::test::gui::LoadRomInTest (ImGuiTestContext * ctx, const std::string & rom_path)
Definition at line 8 of file test_utils.cc.
References yaze::core::Controller::OnEntry().
Referenced by E2ETest_CanvasSelectionTest(), E2ETest_DungeonEditorSmokeTest(), and E2ETest_FrameworkSmokeTest().
OpenEditorInTest()
void yaze::test::gui::OpenEditorInTest (ImGuiTestContext * ctx, const std::string & editor_name)
Definition at line 13 of file test_utils.cc.
Referenced by E2ETest_CanvasSelectionTest(), and E2ETest_DungeonEditorSmokeTest().