yaze: yaze::editor::MenuManager Class Reference
yaze::editor::MenuManager Class Reference
#include <menu_manager.h>
Public Member Functions
MenuManager (EditorManager *editor_manager)
void BuildAndDraw ()
Private Attributes
EditorManager * editor_manager_
MenuBuilder menu_builder_
Detailed Description
Definition at line 11 of file menu_manager.h.
Constructor & Destructor Documentation
MenuManager()
yaze::editor::MenuManager::MenuManager (EditorManager * editor_manager) explicit
Definition at line 10 of file menu_manager.cc.
Member Function Documentation
BuildAndDraw()
void yaze::editor::MenuManager::BuildAndDraw ()
Definition at line 13 of file menu_manager.cc.
References yaze::editor::EditorManager::BuildModernMenu(), yaze::editor::MenuBuilder::Draw(), editor_manager_, yaze::editor::EditorManager::GetActiveSessionCount(), yaze::editor::EditorManager::GetCurrentRom(), ICON_MD_APPS, ICON_MD_DASHBOARD, ICON_MD_DISPLAY_SETTINGS, ICON_MD_TAB, ICON_MD_TUNE, yaze::editor::EditorManager::menu_builder_, yaze::editor::EditorManager::popup_manager_, yaze::editor::EditorManager::show_editor_selection_, yaze::editor::EditorManager::show_session_switcher_, and yaze::editor::EditorManager::version().
Member Data Documentation
editor_manager_
EditorManager* yaze::editor::MenuManager::editor_manager_ private
Definition at line 18 of file menu_manager.h.
Referenced by BuildAndDraw().
menu_builder_
MenuBuilder yaze::editor::MenuManager::menu_builder_ private
Definition at line 19 of file menu_manager.h.
The documentation for this class was generated from the following files:
src/app/editor/ui/menu_manager.h
src/app/editor/ui/menu_manager.cc