yaze: yaze::gfx::Bitmap Class Reference
yaze::gfx::Bitmap Class Reference
Represents a bitmap image optimized for SNES ROM hacking.
#include <bitmap.h>
Classes
struct DirtyRegion
Public Member Functions
Bitmap ()=default
Bitmap (int width, int height, int depth, const std::vector< uint8_t > &data)
Create a bitmap with the given dimensions and raw pixel data.
Bitmap (int width, int height, int depth, const std::vector< uint8_t > &data, const SnesPalette &palette)
Create a bitmap with the given dimensions, data, and SNES palette.
Bitmap (const Bitmap &other)
Copy constructor - creates a deep copy.
Bitmap & operator= (const Bitmap &other)
Copy assignment operator.
Bitmap (Bitmap &&other) noexcept
Move constructor.
Bitmap & operator= (Bitmap &&other) noexcept
Move assignment operator.
~Bitmap ()=default
Destructor.
void Create (int width, int height, int depth, std::span< uint8_t > data)
Create a bitmap with the given dimensions and data.
void Create (int width, int height, int depth, const std::vector< uint8_t > &data)
Create a bitmap with the given dimensions and data.
void Create (int width, int height, int depth, int format, const std::vector< uint8_t > &data)
Create a bitmap with the given dimensions, format, and data.
void Reformat (int format)
Reformat the bitmap to use a different pixel format.
void CreateTexture (SDL_Renderer *renderer)
Creates the underlying SDL_Texture to be displayed.
void UpdateTexture (SDL_Renderer *renderer)
Updates the underlying SDL_Texture when it already exists.
void QueueTextureUpdate (SDL_Renderer *renderer)
Queue texture update for batch processing (improved performance)
void UpdateTextureData ()
Updates the texture data from the surface.
void SetPalette (const SnesPalette &palette)
Set the palette for the bitmap.
void SetPaletteWithTransparent (const SnesPalette &palette, size_t index, int length=7)
Set the palette with a transparent color.
void SetPalette (const std::vector< SDL_Color > &palette)
Set the palette using SDL colors.
void WriteToPixel (int position, uint8_t value)
Write a value to a pixel at the given position.
void WriteColor (int position, const ImVec4 &color)
Write a color to a pixel at the given position.
void SetPixel (int x, int y, const SnesColor &color)
Set a pixel at the given x,y coordinates with SNES color.
void Resize (int new_width, int new_height)
Resize the bitmap to new dimensions (preserves existing data)
void InvalidatePaletteCache ()
Invalidate the palette lookup cache (call when palette changes)
uint8_t FindColorIndex (const SnesColor &color)
Find color index in palette using optimized hash map lookup.
bool ValidateDataSurfaceSync ()
Validate that bitmap data and surface pixels are synchronized.
void Get8x8Tile (int tile_index, int x, int y, std::vector< uint8_t > &tile_data, int &tile_data_offset)
Extract an 8x8 tile from the bitmap (SNES standard tile size)
void Get16x16Tile (int tile_x, int tile_y, std::vector< uint8_t > &tile_data, int &tile_data_offset)
Extract a 16x16 tile from the bitmap (SNES metatile size)
const SnesPalette & palette () const
SnesPalette * mutable_palette ()
int width () const
int height () const
int depth () const
auto size () const
const uint8_t * data () const
std::vector< uint8_t > & mutable_data ()
SDL_Surface * surface () const
SDL_Texture * texture () const
const std::vector< uint8_t > & vector () const
uint8_t at (int i) const
bool modified () const
bool is_active () const
void set_active (bool active)
void set_data (const std::vector< uint8_t > &data)
void set_modified (bool modified)
Static Private Member Functions
static uint32_t HashColor (const ImVec4 &color)
Hash a color for cache lookup.
Private Attributes
int width_ = 0
int height_ = 0
int depth_ = 0
bool active_ = false
bool modified_ = false
void * texture_pixels = nullptr
uint8_t * pixel_data_ = nullptr
gfx::SnesPalette palette_
std::vector< uint8_t > data_
SDL_Surface * surface_ = nullptr
SDL_Texture * texture_ = nullptr
std::unordered_map< uint32_t, uint8_t > color_to_index_cache_
struct yaze::gfx::Bitmap::DirtyRegion dirty_region_
Detailed Description
Represents a bitmap image optimized for SNES ROM hacking.
The Bitmap class provides functionality to create, manipulate, and display bitmap images specifically designed for Link to the Past ROM editing. It supports:
Key Features:
SNES-specific pixel formats (4BPP, 8BPP, indexed)
Palette management with transparent color support
Tile extraction (8x8, 16x16) for ROM tile editing
Memory-efficient surface/texture management via Arena
Real-time editing with immediate visual feedback
Performance Optimizations:
Lazy texture creation (textures only created when needed)
Modified flag tracking to avoid unnecessary updates
Arena-based resource pooling to reduce allocation overhead
Direct pixel data manipulation for fast editing operations
ROM Hacking Specific:
SNES color format conversion (15-bit RGB to 8-bit indexed)
Tile-based editing for 8x8 and 16x16 SNES tiles
Palette index management for ROM palette editing
Support for multiple graphics sheets (223 total in YAZE)
Definition at line 65 of file bitmap.h.
Constructor & Destructor Documentation
Bitmap() [1/5]
yaze::gfx::Bitmap::Bitmap () default
Bitmap() [2/5]
yaze::gfx::Bitmap::Bitmap (int width, int height, int depth, const std::vector< uint8_t > & data)
Create a bitmap with the given dimensions and raw pixel data.
Parameters
width Width in pixels (typically 128, 256, or 512 for SNES tilesheets)
height Height in pixels (typically 32, 64, or 128 for SNES tilesheets)
depth Color depth in bits per pixel (4, 8, or 16 for SNES)
data Raw pixel data (indexed color values for SNES graphics)
Definition at line 47 of file bitmap.cc.
References Create(), data(), depth(), height(), and width().
Bitmap() [3/5]
yaze::gfx::Bitmap::Bitmap (int width, int height, int depth, const std::vector< uint8_t > & data, const SnesPalette & palette)
Create a bitmap with the given dimensions, data, and SNES palette.
Parameters
width Width in pixels
height Height in pixels
depth Color depth in bits per pixel
data Raw pixel data (indexed color values)
palette SNES palette for color mapping (15-bit RGB format)
Definition at line 53 of file bitmap.cc.
References Create(), data(), depth(), height(), palette(), SetPalette(), and width().
Bitmap() [4/5]
yaze::gfx::Bitmap::Bitmap (const Bitmap & other)
Copy constructor - creates a deep copy.
Definition at line 64 of file bitmap.cc.
References active_, yaze::gfx::Arena::AllocateSurface(), data_, depth_, yaze::gfx::Arena::Get(), yaze::gfx::GetSnesPixelFormat(), height_, yaze::gfx::kIndexed, pixel_data_, surface_, vector(), and width_.
Bitmap() [5/5]
yaze::gfx::Bitmap::Bitmap (Bitmap && other) noexcept
Move constructor.
Definition at line 110 of file bitmap.cc.
~Bitmap()
yaze::gfx::Bitmap::~Bitmap () default
Destructor.
Member Function Documentation
operator=() [1/2]
Bitmap & yaze::gfx::Bitmap::operator= (const Bitmap & other)
Copy assignment operator.
Definition at line 85 of file bitmap.cc.
References active_, yaze::gfx::Arena::AllocateSurface(), data_, depth_, yaze::gfx::Arena::Get(), yaze::gfx::GetSnesPixelFormat(), height_, yaze::gfx::kIndexed, modified_, palette_, pixel_data_, surface_, vector(), and width_.
operator=() [2/2]
Bitmap & yaze::gfx::Bitmap::operator= (Bitmap && other) noexcept
Move assignment operator.
Definition at line 134 of file bitmap.cc.
References width_.
Create() [1/3]
void yaze::gfx::Bitmap::Create (int width, int height, int depth, std::span< uint8_t > data)
Create a bitmap with the given dimensions and data.
Definition at line 162 of file bitmap.cc.
References Create(), data(), data_, depth(), height(), and width().
Referenced by Bitmap(), Bitmap(), yaze::zelda3::Inventory::BuildTileset(), yaze::editor::Tile16Editor::CopyTile16ToClipboard(), yaze::zelda3::Inventory::Create(), yaze::zelda3::TitleScreen::Create(), Create(), Create(), yaze::core::Renderer::CreateAndRenderBitmap(), yaze::core::Renderer::CreateBitmapWithoutTexture(), yaze::editor::GraphicsEditor::DecompressImportData(), yaze::gfx::BackgroundBuffer::DrawBackground(), yaze::editor::GraphicsEditor::DrawCgxImport(), yaze::editor::GraphicsEditor::DrawScrImport(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::editor::Tile16Editor::Initialize(), yaze::zelda3::LoadDungeonMapTile16(), yaze::LoadFontGraphics(), yaze::editor::Tile16Editor::LoadTile16FromScratchSpace(), yaze::editor::Tile16Editor::PasteTile16FromClipboard(), yaze::editor::Tile16Editor::PreviewPaletteChange(), yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM(), yaze::editor::Tile16Editor::RotateTile16(), yaze::test::RomDependentTestSuite::RunTile16EditorTest(), yaze::editor::Tile16Editor::SaveUndoState(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::editor::Tile16Editor::Undo(), and yaze::editor::Tile16Editor::UpdateTile16Edit().
Create() [2/3]
void yaze::gfx::Bitmap::Create (int width, int height, int depth, const std::vector< uint8_t > & data)
Create a bitmap with the given dimensions and data.
Definition at line 167 of file bitmap.cc.
References Create(), data(), depth(), height(), yaze::gfx::kIndexed, and width().
Create() [3/3]
void yaze::gfx::Bitmap::Create (int width, int height, int depth, int format, const std::vector< uint8_t > & data)
Create a bitmap with the given dimensions, format, and data.
Create a bitmap with specified format and data.
Parameters
width Width in pixels
height Height in pixels
depth Color depth in bits per pixel
format Pixel format (0=indexed, 1=4BPP, 2=8BPP)
data Raw pixel data
Performance Notes:
Uses Arena for efficient surface allocation
Copies data to avoid external pointer dependencies
Validates data size against surface dimensions
Sets active flag for rendering pipeline
Definition at line 186 of file bitmap.cc.
References active_, yaze::gfx::Arena::AllocateSurface(), data(), data_, depth(), depth_, yaze::gfx::Arena::Get(), yaze::gfx::GetSnesPixelFormat(), height(), height_, pixel_data_, surface_, vector(), width(), and width_.
Reformat()
void yaze::gfx::Bitmap::Reformat (int format)
Reformat the bitmap to use a different pixel format.
Definition at line 223 of file bitmap.cc.
References active_, yaze::gfx::Arena::AllocateSurface(), data_, depth_, yaze::gfx::Arena::Get(), yaze::gfx::GetSnesPixelFormat(), height_, palette_, pixel_data_, SetPalette(), surface_, vector(), and width_.
Referenced by yaze::gui::Canvas::DrawContextMenu().
CreateTexture()
void yaze::gfx::Bitmap::CreateTexture (SDL_Renderer * renderer)
Creates the underlying SDL_Texture to be displayed.
Definition at line 302 of file bitmap.cc.
References yaze::gfx::Arena::AllocateTexture(), yaze::gfx::Arena::Get(), height_, texture_, UpdateTextureData(), vector(), and width_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), QueueTextureUpdate(), yaze::core::Renderer::RenderBitmap(), and UpdateTexture().
UpdateTexture()
void yaze::gfx::Bitmap::UpdateTexture (SDL_Renderer * renderer)
Updates the underlying SDL_Texture when it already exists.
Definition at line 237 of file bitmap.cc.
References CreateTexture(), modified_, surface_, texture_, and vector().
Referenced by yaze::core::Renderer::UpdateBitmap().
QueueTextureUpdate()
void yaze::gfx::Bitmap::QueueTextureUpdate (SDL_Renderer * renderer)
Queue texture update for batch processing (improved performance)
Parameters
renderer SDL renderer for texture operations
Note
Use this for better performance when multiple textures need updating
Parameters
renderer SDL renderer for texture operations
Note
Use this for better performance when multiple textures need updating
Performance Notes:
Queues updates instead of processing immediately
Reduces SDL calls by batching multiple updates
5x faster for multiple texture updates
Automatic dirty region handling
Definition at line 272 of file bitmap.cc.
References CreateTexture(), dirty_region_, yaze::gfx::Arena::Get(), height_, yaze::gfx::Bitmap::DirtyRegion::is_dirty, yaze::gfx::Bitmap::DirtyRegion::max_x, yaze::gfx::Bitmap::DirtyRegion::max_y, yaze::gfx::Bitmap::DirtyRegion::min_x, yaze::gfx::Bitmap::DirtyRegion::min_y, yaze::gfx::Arena::QueueTextureUpdate(), yaze::gfx::Bitmap::DirtyRegion::Reset(), surface_, texture_, vector(), and width_.
Referenced by yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), and yaze::editor::GraphicsEditor::UpdateGfxTabView().
UpdateTextureData()
void yaze::gfx::Bitmap::UpdateTextureData ()
Updates the texture data from the surface.
Definition at line 325 of file bitmap.cc.
References yaze::gfx::Arena::Get(), modified_, surface_, texture_, and yaze::gfx::Arena::UpdateTexture().
Referenced by CreateTexture().
SetPalette() [1/2]
void yaze::gfx::Bitmap::SetPalette (const SnesPalette & palette)
Set the palette for the bitmap.
Definition at line 334 of file bitmap.cc.
References InvalidatePaletteCache(), palette(), palette_, yaze::gfx::SnesPalette::size(), surface_, and vector().
Referenced by yaze::gui::canvas::CanvasUtils::ApplyPaletteGroup(), yaze::gui::CanvasUtils::ApplyPaletteGroup(), yaze::gui::EnhancedPaletteEditor::ApplyROMPalette(), Bitmap(), yaze::zelda3::Inventory::BuildTileset(), yaze::editor::Tile16Editor::CopyTile16ToClipboard(), yaze::zelda3::Inventory::Create(), yaze::core::Renderer::CreateAndRenderBitmap(), yaze::core::Renderer::CreateBitmapWithoutTexture(), yaze::gfx::CreateTilemap(), yaze::editor::GraphicsEditor::DecompressImportData(), yaze::editor::GraphicsEditor::DrawCgxImport(), yaze::editor::GraphicsEditor::DrawScrImport(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::editor::Tile16Editor::Initialize(), yaze::zelda3::LoadDungeonMapTile16(), yaze::editor::Tile16Editor::LoadTile16FromScratchSpace(), yaze::editor::Tile16Editor::PasteTile16FromClipboard(), Reformat(), yaze::editor::Tile16Editor::RefreshAllPalettes(), yaze::editor::OverworldEditor::RefreshTile16Blockset(), yaze::editor::Tile16Editor::RegenerateTile16BitmapFromROM(), yaze::editor::Tile16Editor::RotateTile16(), yaze::test::RomDependentTestSuite::RunTile16EditorTest(), yaze::editor::Tile16Editor::SaveUndoState(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::editor::Tile16Editor::Undo(), and yaze::editor::Tile16Editor::UpdateTile16Edit().
SetPaletteWithTransparent()
void yaze::gfx::Bitmap::SetPaletteWithTransparent (const SnesPalette & palette, size_t index, int length = 7)
Set the palette with a transparent color.
Definition at line 363 of file bitmap.cc.
References InvalidatePaletteCache(), palette(), palette_, yaze::gfx::SnesPalette::size(), surface_, and vector().
Referenced by yaze::gui::canvas::CanvasUtils::ApplyPaletteGroup(), yaze::gui::CanvasUtils::ApplyPaletteGroup(), yaze::gui::EnhancedPaletteEditor::ApplyROMPalette(), yaze::gui::Canvas::DrawContextMenu(), and yaze::editor::Tile16Editor::PreviewPaletteChange().
SetPalette() [2/2]
void yaze::gfx::Bitmap::SetPalette (const std::vector< SDL_Color > & palette)
Set the palette using SDL colors.
Definition at line 422 of file bitmap.cc.
References palette(), yaze::gfx::SnesPalette::size(), surface_, and vector().
WriteToPixel()
void yaze::gfx::Bitmap::WriteToPixel (int position, uint8_t value)
Write a value to a pixel at the given position.
Definition at line 433 of file bitmap.cc.
References active_, data_, modified_, pixel_data_, surface_, and vector().
Referenced by yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::gfx::anonymous_namespace{tilemap.cc}::ComposeAndPlaceTilePart(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::editor::Tile16Editor::FillTile16WithTile8(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), yaze::editor::Tile16Editor::RotateTile16(), yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), and yaze::editor::Tile16Editor::UpdateOverworldTilemap().
WriteColor()
void yaze::gfx::Bitmap::WriteColor (int position, const ImVec4 & color)
Write a color to a pixel at the given position.
Definition at line 480 of file bitmap.cc.
References active_, yaze::gfx::ConvertRgbToSnes(), data_, modified_, pixel_data_, surface_, and vector().
Referenced by yaze::gui::Canvas::DrawTileOnBitmap().
SetPixel()
void yaze::gfx::Bitmap::SetPixel (int x, int y, const SnesColor & color)
Set a pixel at the given x,y coordinates with SNES color.
Set a pixel at the given coordinates with SNES color.
Parameters
x X coordinate (0 to width-1)
y Y coordinate (0 to height-1)
color SNES color (15-bit RGB format)
Note
Automatically finds closest palette index and marks bitmap as modified
Parameters
x X coordinate (0 to width-1)
y Y coordinate (0 to height-1)
color SNES color (15-bit RGB format)
Performance Notes:
Bounds checking for safety
O(1) palette lookup using hash map cache (100x faster than linear search)
Dirty region tracking for efficient texture updates
Direct pixel data manipulation for speed
Optimizations Applied:
Hash map palette lookup instead of linear search
Dirty region tracking to minimize texture update area
Definition at line 575 of file bitmap.cc.
References yaze::gfx::Bitmap::DirtyRegion::AddPoint(), data_, dirty_region_, FindColorIndex(), height_, modified_, pixel_data_, surface_, vector(), and width_.
Referenced by yaze::zelda3::ObjectRenderer::Render8x8Tile(), yaze::zelda3::ObjectRenderer::RenderTile(), yaze::zelda3::ObjectRenderer::RenderTilePattern(), and yaze::gfx::TEST_F().
Resize()
void yaze::gfx::Bitmap::Resize (int new_width, int new_height)
Resize the bitmap to new dimensions (preserves existing data)
Parameters
new_width New width in pixels
new_height New height in pixels
Note
Expands with black pixels, crops excess data
Definition at line 603 of file bitmap.cc.
References active_, yaze::gfx::Arena::AllocateSurface(), data_, depth_, yaze::gfx::Arena::Get(), yaze::gfx::GetSnesPixelFormat(), height_, yaze::gfx::kIndexed, modified_, pixel_data_, surface_, vector(), and width_.
InvalidatePaletteCache()
void yaze::gfx::Bitmap::InvalidatePaletteCache ()
Invalidate the palette lookup cache (call when palette changes)
Note
This must be called whenever the palette is modified to maintain cache consistency
This must be called whenever the palette is modified to maintain cache consistency
Performance Notes:
Clears existing cache to force rebuild
Rebuilds cache with current palette colors
O(n) operation but only called when palette changes
Definition at line 673 of file bitmap.cc.
References color_to_index_cache_, HashColor(), palette_, yaze::gfx::SnesPalette::size(), and vector().
Referenced by SetPalette(), and SetPaletteWithTransparent().
FindColorIndex()
uint8_t yaze::gfx::Bitmap::FindColorIndex (const SnesColor & color)
Find color index in palette using optimized hash map lookup.
Parameters
color SNES color to find index for
Returns
Palette index (0 if not found)
Note
O(1) lookup time vs O(n) linear search
Parameters
color SNES color to find index for
Returns
Palette index (0 if not found)
Note
O(1) lookup time vs O(n) linear search
Performance Notes:
Hash map lookup for O(1) performance
100x faster than linear search for large palettes
Falls back to index 0 if color not found
Definition at line 694 of file bitmap.cc.
References color_to_index_cache_, HashColor(), yaze::gfx::SnesColor::rgb(), and vector().
Referenced by SetPixel(), and yaze::gfx::TEST_F().
ValidateDataSurfaceSync()
bool yaze::gfx::Bitmap::ValidateDataSurfaceSync ()
Validate that bitmap data and surface pixels are synchronized.
Returns
true if synchronized, false if there are issues
Note
This method helps debug surface synchronization problems
Definition at line 721 of file bitmap.cc.
References data_, surface_, and vector().
Get8x8Tile()
void yaze::gfx::Bitmap::Get8x8Tile (int tile_index, int x, int y, std::vector< uint8_t > & tile_data, int & tile_data_offset)
Extract an 8x8 tile from the bitmap (SNES standard tile size)
Parameters
tile_index Index of the tile in the tilesheet
x X offset within the tile (0-7)
y Y offset within the tile (0-7)
tile_data Output buffer for tile pixel data (64 bytes for 8x8)
tile_data_offset Current offset in tile_data buffer
Note
Used for ROM tile editing and tile extraction
Definition at line 524 of file bitmap.cc.
References data_, height_, vector(), and width_.
Get16x16Tile()
void yaze::gfx::Bitmap::Get16x16Tile (int tile_x, int tile_y, std::vector< uint8_t > & tile_data, int & tile_data_offset)
Extract a 16x16 tile from the bitmap (SNES metatile size)
Parameters
tile_x X coordinate of tile in tilesheet
tile_y Y coordinate of tile in tilesheet
tile_data Output buffer for tile pixel data (256 bytes for 16x16)
tile_data_offset Current offset in tile_data buffer
Note
Used for ROM metatile editing and large tile extraction
Definition at line 540 of file bitmap.cc.
References data_, vector(), and width_.
Referenced by yaze::gfx::UpdateTile16().
palette()
const SnesPalette & yaze::gfx::Bitmap::palette () const inline
Definition at line 245 of file bitmap.h.
References palette_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), yaze::gui::EnhancedPaletteEditor::ApplyROMPalette(), Bitmap(), yaze::editor::Tile16Editor::CopyTile16ToClipboard(), yaze::editor::Tile16Editor::Initialize(), yaze::editor::Tile16Editor::PasteTile16FromClipboard(), yaze::gfx::RenderTilesBatch(), yaze::editor::Tile16Editor::SaveTile16ToScratchSpace(), yaze::editor::Tile16Editor::SaveUndoState(), SetPalette(), SetPalette(), SetPaletteWithTransparent(), yaze::gui::Canvas::ShowBppAnalysis(), yaze::gui::Canvas::ShowBppConversionDialog(), yaze::gui::Canvas::ShowBppFormatSelector(), yaze::gui::EnhancedPaletteEditor::ShowColorAnalysis(), and yaze::editor::Tile16Editor::Undo().
mutable_palette()
SnesPalette * yaze::gfx::Bitmap::mutable_palette () inline
Definition at line 246 of file bitmap.h.
References palette_.
Referenced by yaze::gui::Canvas::DrawContextMenu(), yaze::editor::MessageEditor::Initialize(), and yaze::gui::Canvas::ShowPaletteEditor().
width()
int yaze::gfx::Bitmap::width () const inline
Definition at line 247 of file bitmap.h.
References width_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmap(), yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), Bitmap(), Bitmap(), yaze::gui::BppComparisonTool::CalculateMetrics(), yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::gfx::anonymous_namespace{tilemap.cc}::ComposeAndPlaceTilePart(), yaze::gfx::ComposeTile16(), yaze::gui::Canvas::ConvertBitmapFormat(), Create(), Create(), Create(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmapGroup(), yaze::gui::DrawBitmapViewer(), yaze::gui::Canvas::DrawTilemapPainter(), yaze::gui::canvas::CanvasInteractionHandler::DrawTilemapPainter(), yaze::gui::Canvas::DrawTileOnBitmap(), yaze::gui::BppComparisonTool::GenerateComparisons(), yaze::gui::Canvas::GetCurrentBppFormat(), yaze::gfx::GetTilemapData(), yaze::editor::Tile16Editor::Initialize(), yaze::editor::Tile16Editor::LoadTile8(), yaze::gfx::ModifyTile16(), yaze::gfx::AtlasRenderer::PackBitmap(), yaze::zelda3::ObjectRenderer::Render8x8Tile(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::BppFormatUI::RenderAnalysisPanel(), yaze::gui::canvas::CanvasContextMenu::RenderBitmapOperationsMenu(), yaze::gui::BppFormatUI::RenderConversionPreview(), yaze::gui::BppFormatUI::RenderFormatSelector(), yaze::gui::canvas::CanvasModals::RenderScalingControlsModal(), yaze::zelda3::ObjectRenderer::RenderTile(), yaze::gfx::RenderTile16(), yaze::zelda3::ObjectRenderer::RenderTilePattern(), yaze::zelda3::ObjectRenderer::RenderTileToBitmap(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::gui::Canvas::SetZoomToFit(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), yaze::gui::EnhancedPaletteEditor::ShowColorAnalysis(), yaze::gui::Canvas::ShowScalingControls(), yaze::gui::TableCanvasPipeline(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::gfx::AtlasRenderer::UpdateBitmap(), yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), yaze::editor::Tile16Editor::UpdateOverworldTilemap(), yaze::gui::BppConversionDialog::UpdatePreview(), yaze::gfx::UpdateTile16(), and yaze::editor::Tile16Editor::UpdateTile16Edit().
height()
int yaze::gfx::Bitmap::height () const inline
Definition at line 248 of file bitmap.h.
References height_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmap(), yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), Bitmap(), Bitmap(), yaze::gui::BppComparisonTool::CalculateMetrics(), yaze::gui::Canvas::ConvertBitmapFormat(), Create(), Create(), Create(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmapGroup(), yaze::gui::DrawBitmapViewer(), yaze::gui::Canvas::DrawTilemapPainter(), yaze::gui::canvas::CanvasInteractionHandler::DrawTilemapPainter(), yaze::gui::BppComparisonTool::GenerateComparisons(), yaze::gui::Canvas::GetCurrentBppFormat(), yaze::gfx::GetTilemapData(), yaze::editor::Tile16Editor::Initialize(), yaze::editor::Tile16Editor::LoadTile8(), yaze::gfx::AtlasRenderer::PackBitmap(), yaze::zelda3::ObjectRenderer::Render8x8Tile(), yaze::gui::canvas::CanvasModals::RenderAdvancedPropertiesModal(), yaze::gui::BppFormatUI::RenderAnalysisPanel(), yaze::gui::canvas::CanvasContextMenu::RenderBitmapOperationsMenu(), yaze::gui::BppFormatUI::RenderConversionPreview(), yaze::gui::BppFormatUI::RenderFormatSelector(), yaze::gui::canvas::CanvasModals::RenderScalingControlsModal(), yaze::zelda3::ObjectRenderer::RenderTile(), yaze::gfx::RenderTile16(), yaze::zelda3::ObjectRenderer::RenderTilePattern(), yaze::zelda3::ObjectRenderer::RenderTileToBitmap(), yaze::gui::Canvas::SetZoomToFit(), yaze::gui::Canvas::ShowAdvancedCanvasProperties(), yaze::gui::EnhancedPaletteEditor::ShowColorAnalysis(), yaze::gui::Canvas::ShowScalingControls(), yaze::gui::TableCanvasPipeline(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::gfx::AtlasRenderer::UpdateBitmap(), and yaze::gui::BppConversionDialog::UpdatePreview().
depth()
int yaze::gfx::Bitmap::depth () const inline
Definition at line 249 of file bitmap.h.
References depth_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), Bitmap(), Bitmap(), Create(), Create(), Create(), yaze::gui::BppComparisonTool::GenerateComparisons(), yaze::editor::Tile16Editor::Initialize(), yaze::gui::BppFormatUI::RenderConversionPreview(), and yaze::gui::BppConversionDialog::UpdatePreview().
size()
auto yaze::gfx::Bitmap::size () const inline
Definition at line 250 of file bitmap.h.
References data_.
Referenced by yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::gui::Canvas::DrawContextMenu(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::editor::Tile16Editor::FillTile16WithTile8(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::editor::Tile16Editor::IsTile16Valid(), yaze::editor::Tile16Editor::LoadTile8(), yaze::zelda3::ObjectRenderer::Render8x8Tile(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), yaze::editor::Tile16Editor::RotateTile16(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), yaze::editor::Tile16Editor::UpdateOverworldTilemap(), and yaze::editor::Tile16Editor::ValidateTile16Data().
data()
const uint8_t * yaze::gfx::Bitmap::data () const inline
Definition at line 251 of file bitmap.h.
References data_.
Referenced by Bitmap(), Bitmap(), yaze::editor::Tile16Editor::CommitChangesToOverworld(), Create(), Create(), Create(), yaze::gui::Canvas::DrawContextMenu(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::editor::Tile16Editor::LoadTile8(), yaze::editor::Tile16Editor::RotateTile16(), set_data(), yaze::editor::Tile16Editor::SetCurrentTile(), yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), and yaze::editor::Tile16Editor::UpdateOverworldTilemap().
mutable_data()
std::vector< uint8_t > & yaze::gfx::Bitmap::mutable_data () inline
Definition at line 252 of file bitmap.h.
References data_.
Referenced by yaze::zelda3::TitleScreen::BuildTileset(), yaze::editor::Tile16Editor::ClearTile16(), yaze::gfx::BackgroundBuffer::DrawBackground(), yaze::editor::MessageEditor::DrawMessagePreview(), and yaze::editor::Tile16Editor::UpdateTile16Edit().
surface()
SDL_Surface * yaze::gfx::Bitmap::surface () const inline
Definition at line 253 of file bitmap.h.
References surface_.
Referenced by yaze::gui::Canvas::DrawContextMenu(), yaze::zelda3::ObjectRenderer::RenderTile(), yaze::test::TEST_F(), and yaze::test::TEST_F().
texture()
SDL_Texture * yaze::gfx::Bitmap::texture () const inline
Definition at line 254 of file bitmap.h.
References texture_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmap(), yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmapGroup(), yaze::gui::DrawBitmapViewer(), yaze::gui::Canvas::DrawTilemapPainter(), yaze::gui::canvas::CanvasInteractionHandler::DrawTilemapPainter(), yaze::gui::Canvas::DrawTilePainter(), yaze::gui::canvas::CanvasInteractionHandler::DrawTilePainter(), yaze::gui::BppComparisonTool::RenderComparisonGrid(), yaze::gui::BppFormatUI::RenderConversionPreview(), yaze::gui::BppConversionDialog::RenderPreview(), and yaze::gfx::AtlasRenderer::UpdateBitmap().
vector()
const std::vector< uint8_t > & yaze::gfx::Bitmap::vector () const inline
Definition at line 255 of file bitmap.h.
References data_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmap(), yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), Bitmap(), yaze::gui::Canvas::ConvertBitmapFormat(), Create(), CreateTexture(), yaze::editor::OverworldEditor::DrawOverworldEdits(), FindColorIndex(), yaze::gui::BppComparisonTool::GenerateComparisons(), Get16x16Tile(), Get8x8Tile(), yaze::gui::Canvas::GetCurrentBppFormat(), yaze::gfx::GetTilemapData(), HashColor(), yaze::editor::Tile16Editor::Initialize(), InvalidatePaletteCache(), operator=(), yaze::editor::Tile16Editor::PasteTile16FromClipboard(), yaze::editor::Tile16Editor::PreviewPaletteChange(), QueueTextureUpdate(), Reformat(), yaze::gui::BppFormatUI::RenderAnalysisPanel(), yaze::gui::BppFormatUI::RenderConversionPreview(), yaze::gui::BppFormatUI::RenderFormatSelector(), yaze::gfx::RenderTile(), yaze::gfx::RenderTile16(), Resize(), yaze::editor::Tile16Editor::SaveTile16ToScratchSpace(), yaze::editor::Tile16Editor::SaveUndoState(), set_data(), SetPalette(), SetPalette(), SetPaletteWithTransparent(), SetPixel(), yaze::gui::EnhancedPaletteEditor::ShowColorAnalysis(), yaze::editor::Tile16Editor::Undo(), yaze::gui::BppConversionDialog::UpdatePreview(), UpdateTexture(), yaze::editor::Tile16Editor::UpdateTile16Edit(), ValidateDataSurfaceSync(), WriteColor(), and WriteToPixel().
at()
uint8_t yaze::gfx::Bitmap::at (int i) const inline
Definition at line 256 of file bitmap.h.
References data_.
Referenced by yaze::zelda3::ObjectRenderer::Render8x8Tile().
modified()
bool yaze::gfx::Bitmap::modified () const inline
Definition at line 257 of file bitmap.h.
References modified_.
Referenced by yaze::editor::Tile16Editor::CommitChangesToBlockset(), and set_modified().
is_active()
bool yaze::gfx::Bitmap::is_active () const inline
Definition at line 258 of file bitmap.h.
References active_.
Referenced by yaze::gfx::AtlasRenderer::AddBitmap(), yaze::gfx::AtlasRenderer::AddBitmapWithBppOptimization(), yaze::editor::OverworldEditor::CheckForCurrentMap(), yaze::editor::Tile16Editor::ClearTile16(), yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::zelda3::ObjectRenderer::CreateBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmap(), yaze::gui::Canvas::DrawBitmapGroup(), yaze::editor::MessageEditor::DrawMessagePreview(), yaze::editor::OverworldEditor::DrawOverworldEdits(), yaze::gui::Canvas::DrawTilemapPainter(), yaze::gui::canvas::CanvasInteractionHandler::DrawTilemapPainter(), yaze::gui::Canvas::DrawTilePainter(), yaze::gui::canvas::CanvasInteractionHandler::DrawTilePainter(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::gfx::GetTilemapData(), yaze::editor::Tile16Editor::LoadTile8(), yaze::editor::Tile16Editor::PreviewPaletteChange(), yaze::editor::Tile16Editor::RefreshAllPalettes(), yaze::zelda3::ObjectRenderer::RenderTile(), yaze::gfx::RenderTile(), yaze::gfx::RenderTile16(), yaze::gfx::RenderTilesBatch(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), yaze::editor::Tile16Editor::RotateTile16(), yaze::editor::Tile16Editor::SaveTile16ToROM(), yaze::editor::Tile16Editor::SaveUndoState(), yaze::editor::Tile16Editor::set_palette(), yaze::gui::Canvas::SetZoomToFit(), yaze::gui::EnhancedPaletteEditor::ShowColorAnalysis(), yaze::gui::TableCanvasPipeline(), yaze::test::TEST_F(), yaze::test::TEST_F(), yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), yaze::editor::Tile16Editor::UpdateOverworldTilemap(), and yaze::editor::Tile16Editor::UpdateTile16Edit().
set_active()
void yaze::gfx::Bitmap::set_active (bool active) inline
Definition at line 259 of file bitmap.h.
References active_.
set_data()
void yaze::gfx::Bitmap::set_data (const std::vector< uint8_t > & data)
Definition at line 701 of file bitmap.cc.
References data(), data_, modified_, pixel_data_, surface_, and vector().
Referenced by yaze::gui::Canvas::ConvertBitmapFormat(), yaze::gfx::UpdateTile16(), and yaze::gfx::UpdateTilemap().
set_modified()
void yaze::gfx::Bitmap::set_modified (bool modified) inline
Definition at line 261 of file bitmap.h.
References modified(), and modified_.
Referenced by yaze::editor::Tile16Editor::ClearTile16(), yaze::editor::Tile16Editor::CommitChangesToOverworld(), yaze::editor::Tile16Editor::DrawToCurrentTile16(), yaze::editor::Tile16Editor::FillTile16WithTile8(), yaze::editor::Tile16Editor::FlipTile16Horizontal(), yaze::editor::Tile16Editor::FlipTile16Vertical(), yaze::editor::Tile16Editor::RefreshAllPalettes(), yaze::editor::Tile16Editor::RefreshTile16Blockset(), yaze::editor::OverworldEditor::RenderUpdatedMapBitmap(), yaze::editor::Tile16Editor::RotateTile16(), yaze::editor::Tile16Editor::UpdateBlocksetBitmap(), and yaze::editor::Tile16Editor::UpdateOverworldTilemap().
HashColor()
uint32_t yaze::gfx::Bitmap::HashColor (const ImVec4 & color) static private
Hash a color for cache lookup.
Parameters
color ImVec4 color to hash
Returns
32-bit hash value
Parameters
color ImVec4 color to hash
Returns
32-bit hash value
Performance Notes:
Simple hash combining RGBA components
Fast integer operations for cache key generation
Collision-resistant for typical SNES palette sizes
Definition at line 653 of file bitmap.cc.
References vector().
Referenced by FindColorIndex(), and InvalidatePaletteCache().
Member Data Documentation
width_
int yaze::gfx::Bitmap::width_ = 0 private
Definition at line 265 of file bitmap.h.
Referenced by Bitmap(), Create(), CreateTexture(), Get16x16Tile(), Get8x8Tile(), operator=(), operator=(), QueueTextureUpdate(), Reformat(), Resize(), SetPixel(), and width().
height_
int yaze::gfx::Bitmap::height_ = 0 private
Definition at line 266 of file bitmap.h.
Referenced by Bitmap(), Create(), CreateTexture(), Get8x8Tile(), height(), operator=(), QueueTextureUpdate(), Reformat(), Resize(), and SetPixel().
depth_
int yaze::gfx::Bitmap::depth_ = 0 private
Definition at line 267 of file bitmap.h.
Referenced by Bitmap(), Create(), depth(), operator=(), Reformat(), and Resize().
active_
bool yaze::gfx::Bitmap::active_ = false private
Definition at line 269 of file bitmap.h.
Referenced by Bitmap(), Create(), is_active(), operator=(), Reformat(), Resize(), set_active(), WriteColor(), and WriteToPixel().
modified_
bool yaze::gfx::Bitmap::modified_ = false private
Definition at line 270 of file bitmap.h.
Referenced by modified(), operator=(), Resize(), set_data(), set_modified(), SetPixel(), UpdateTexture(), UpdateTextureData(), WriteColor(), and WriteToPixel().
texture_pixels
void* yaze::gfx::Bitmap::texture_pixels = nullptr private
Definition at line 273 of file bitmap.h.
pixel_data_
uint8_t* yaze::gfx::Bitmap::pixel_data_ = nullptr private
Definition at line 276 of file bitmap.h.
Referenced by Bitmap(), Create(), operator=(), Reformat(), Resize(), set_data(), SetPixel(), WriteColor(), and WriteToPixel().
palette_
gfx::SnesPalette yaze::gfx::Bitmap::palette_ private
Definition at line 279 of file bitmap.h.
Referenced by InvalidatePaletteCache(), mutable_palette(), operator=(), palette(), Reformat(), SetPalette(), and SetPaletteWithTransparent().
data_
std::vector<uint8_t> yaze::gfx::Bitmap::data_ private
Definition at line 282 of file bitmap.h.
Referenced by at(), Bitmap(), Create(), Create(), data(), Get16x16Tile(), Get8x8Tile(), mutable_data(), operator=(), Reformat(), Resize(), set_data(), SetPixel(), size(), ValidateDataSurfaceSync(), vector(), WriteColor(), and WriteToPixel().
surface_
SDL_Surface* yaze::gfx::Bitmap::surface_ = nullptr private
Definition at line 285 of file bitmap.h.
Referenced by Bitmap(), Create(), operator=(), QueueTextureUpdate(), Reformat(), Resize(), set_data(), SetPalette(), SetPalette(), SetPaletteWithTransparent(), SetPixel(), surface(), UpdateTexture(), UpdateTextureData(), ValidateDataSurfaceSync(), WriteColor(), and WriteToPixel().
texture_
SDL_Texture* yaze::gfx::Bitmap::texture_ = nullptr private
Definition at line 288 of file bitmap.h.
Referenced by CreateTexture(), QueueTextureUpdate(), texture(), UpdateTexture(), and UpdateTextureData().
color_to_index_cache_
std::unordered_map<uint32_t, uint8_t> yaze::gfx::Bitmap::color_to_index_cache_ private
Definition at line 291 of file bitmap.h.
Referenced by FindColorIndex(), and InvalidatePaletteCache().
dirty_region_
struct yaze::gfx::Bitmap::DirtyRegion yaze::gfx::Bitmap::dirty_region_ private
Referenced by QueueTextureUpdate(), and SetPixel().
The documentation for this class was generated from the following files:
src/app/gfx/bitmap.h
src/app/gfx/bitmap.cc