yaze: yaze::zelda3::ObjectDrawer Class Reference
yaze::zelda3::ObjectDrawer Class Reference
Draws dungeon objects to background buffers using game patterns.
#include <object_drawer.h>
Public Member Functions
ObjectDrawer (Rom *rom, const uint8_t *room_gfx_buffer=nullptr)
absl::Status DrawObject (const RoomObject &object, gfx::BackgroundBuffer &bg1, gfx::BackgroundBuffer &bg2, const gfx::PaletteGroup &palette_group)
Draw a room object to background buffers.
absl::Status DrawObjectList (const std::vector< RoomObject > &objects, gfx::BackgroundBuffer &bg1, gfx::BackgroundBuffer &bg2, const gfx::PaletteGroup &palette_group)
Draw all objects in a room.
int GetDrawRoutineId (int16_t object_id) const
Get draw routine ID for an object.
void InitializeDrawRoutines ()
Initialize draw routine registry Must be called before drawing objects.
void DrawTileToBitmap (gfx::Bitmap &bitmap, const gfx::TileInfo &tile_info, int pixel_x, int pixel_y, const uint8_t *tiledata)
Draw a single tile directly to bitmap.
Private Types
using DrawRoutine = std::function< void(ObjectDrawer *, const RoomObject &, gfx::BackgroundBuffer &, const std::vector< gfx::Tile16 > &)>
Private Member Functions
void DrawRightwards2x2_1to15or32 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwards2x4_1to15or26 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwards2x4spaced4_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwards2x4spaced4_1to16_BothBG (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwards2x2_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDiagonalAcute_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDiagonalGrave_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDiagonalAcute_1to16_BothBG (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDiagonalGrave_1to16_BothBG (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwards1x2_1to16_plus2 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsHasEdge1x1_1to16_plus3 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsHasEdge1x1_1to16_plus2 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsTopCorners1x2_1to16_plus13 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsBottomCorners1x2_1to16_plus13 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void CustomDraw (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwards4x4_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwards1x1Solid_1to16_plus3 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDoorSwitcherer (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsDecor4x4spaced2_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsStatue2x3spaced2_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsPillar2x4spaced4_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsDecor4x3spaced4_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsDoubled2x2spaced2_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawRightwardsDecor2x2spaced12_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwards2x2_1to15or32 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwards4x2_1to15or26 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwards4x2_1to16_BothBG (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwardsDecor4x2spaced4_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwards2x2_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwardsHasEdge1x1_1to16_plus3 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwardsEdge1x1_1to16 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwardsLeftCorners2x1_1to16_plus12 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void DrawDownwardsRightCorners2x1_1to16_plus12 (const RoomObject &obj, gfx::BackgroundBuffer &bg, const std::vector< gfx::Tile16 > &tiles)
void WriteTile8 (gfx::BackgroundBuffer &bg, int tile_x, int tile_y, const gfx::TileInfo &tile_info)
bool IsValidTilePosition (int tile_x, int tile_y) const
Private Attributes
std::unordered_map< int16_t, int > object_to_routine_map_
std::vector< DrawRoutine > draw_routines_
bool routines_initialized_ = false
Rom * rom_
const uint8_t * room_gfx_buffer_
Static Private Attributes
static constexpr int kMaxTilesX = 64
static constexpr int kMaxTilesY = 64
Detailed Description
Draws dungeon objects to background buffers using game patterns.
This class interprets object IDs and draws them to BG1/BG2 buffers using the patterns extracted from the game's drawing routines. Based on ZScream's DungeonObjectData.cs and Subtype1_Draw.cs patterns.
Architecture:
Load tile data from ROM for the object
Look up draw routine ID from object ID mapping
Execute appropriate draw routine with size/orientation
Write tiles to BackgroundBuffer according to pattern
Handle palette coordination and graphics sheet access
Definition at line 32 of file object_drawer.h.
Member Typedef Documentation
DrawRoutine
using yaze::zelda3::ObjectDrawer::DrawRoutine = std::function<void(ObjectDrawer*, const RoomObject&, gfx::BackgroundBuffer&, const std::vector<gfx::Tile16>&)> private
Definition at line 88 of file object_drawer.h.
Constructor & Destructor Documentation
ObjectDrawer()
yaze::zelda3::ObjectDrawer::ObjectDrawer (Rom * rom, const uint8_t * room_gfx_buffer = nullptr) explicit
Definition at line 12 of file object_drawer.cc.
References InitializeDrawRoutines().
Member Function Documentation
DrawObject()
absl::Status yaze::zelda3::ObjectDrawer::DrawObject (const RoomObject & object, gfx::BackgroundBuffer & bg1, gfx::BackgroundBuffer & bg2, const gfx::PaletteGroup & palette_group)
Draw a room object to background buffers.
Parameters
object The object to draw
bg1 Background layer 1 buffer
bg2 Background layer 2 buffer
palette_group Current palette group for color mapping
Returns
Status of the drawing operation
Definition at line 17 of file object_drawer.cc.
References yaze::zelda3::RoomObject::BG2, draw_routines_, GetDrawRoutineId(), yaze::Rom::is_loaded(), LOG_DEBUG, rom_, routines_initialized_, yaze::zelda3::RoomObject::set_rom(), yaze::zelda3::RoomObject::tiles(), and WriteTile8().
Referenced by DrawObjectList(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::test::TEST_F(), and yaze::test::TEST_F().
DrawObjectList()
absl::Status yaze::zelda3::ObjectDrawer::DrawObjectList (const std::vector< RoomObject > & objects, gfx::BackgroundBuffer & bg1, gfx::BackgroundBuffer & bg2, const gfx::PaletteGroup & palette_group)
Draw all objects in a room.
Parameters
objects Vector of room objects
bg1 Background layer 1 buffer
bg2 Background layer 2 buffer
palette_group Current palette group for color mapping
Returns
Status of the drawing operation
Definition at line 63 of file object_drawer.cc.
References DrawObject().
Referenced by yaze::zelda3::Room::RenderObjectsToBackground(), yaze::test::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), yaze::zelda3::TEST_F(), and yaze::zelda3::TEST_F().
GetDrawRoutineId()
int yaze::zelda3::ObjectDrawer::GetDrawRoutineId (int16_t object_id) const
Get draw routine ID for an object.
Parameters
object_id The object ID to look up
Returns
Draw routine ID (0-24) based on ZScream mapping
Definition at line 276 of file object_drawer.cc.
References object_to_routine_map_.
Referenced by DrawObject().
InitializeDrawRoutines()
void yaze::zelda3::ObjectDrawer::InitializeDrawRoutines ()
Initialize draw routine registry Must be called before drawing objects.
Definition at line 80 of file object_drawer.cc.
References CustomDraw(), draw_routines_, DrawDiagonalAcute_1to16(), DrawDiagonalAcute_1to16_BothBG(), DrawDiagonalGrave_1to16(), DrawDiagonalGrave_1to16_BothBG(), DrawDoorSwitcherer(), DrawDownwards2x2_1to15or32(), DrawDownwards2x2_1to16(), DrawDownwards4x2_1to15or26(), DrawDownwards4x2_1to16_BothBG(), DrawDownwardsDecor4x2spaced4_1to16(), DrawDownwardsEdge1x1_1to16(), DrawDownwardsHasEdge1x1_1to16_plus3(), DrawDownwardsLeftCorners2x1_1to16_plus12(), DrawDownwardsRightCorners2x1_1to16_plus12(), DrawRightwards1x1Solid_1to16_plus3(), DrawRightwards1x2_1to16_plus2(), DrawRightwards2x2_1to15or32(), DrawRightwards2x2_1to16(), DrawRightwards2x4_1to15or26(), DrawRightwards2x4spaced4_1to16(), DrawRightwards2x4spaced4_1to16_BothBG(), DrawRightwards4x4_1to16(), DrawRightwardsBottomCorners1x2_1to16_plus13(), DrawRightwardsDecor2x2spaced12_1to16(), DrawRightwardsDecor4x3spaced4_1to16(), DrawRightwardsDecor4x4spaced2_1to16(), DrawRightwardsDoubled2x2spaced2_1to16(), DrawRightwardsHasEdge1x1_1to16_plus2(), DrawRightwardsHasEdge1x1_1to16_plus3(), DrawRightwardsPillar2x4spaced4_1to16(), DrawRightwardsStatue2x3spaced2_1to16(), DrawRightwardsTopCorners1x2_1to16_plus13(), object_to_routine_map_, and routines_initialized_.
Referenced by ObjectDrawer().
DrawTileToBitmap()
void yaze::zelda3::ObjectDrawer::DrawTileToBitmap (gfx::Bitmap & bitmap, const gfx::TileInfo & tile_info, int pixel_x, int pixel_y, const uint8_t * tiledata)
Draw a single tile directly to bitmap.
Parameters
bitmap Target bitmap to draw to
tile_info Tile information (ID, palette, mirroring)
pixel_x X pixel coordinate in bitmap
pixel_y Y pixel coordinate in bitmap
tiledata Source graphics data from ROM
Definition at line 894 of file object_drawer.cc.
References yaze::gfx::Bitmap::height(), yaze::gfx::TileInfo::horizontal_mirror_, yaze::gfx::TileInfo::id_, yaze::gfx::Bitmap::is_active(), LOG_DEBUG, yaze::gfx::Bitmap::mutable_data(), yaze::gfx::TileInfo::palette_, yaze::gfx::TileInfo::vertical_mirror_, and yaze::gfx::Bitmap::width().
Referenced by WriteTile8().
DrawRightwards2x2_1to15or32()
void yaze::zelda3::ObjectDrawer::DrawRightwards2x2_1to15or32 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 290 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwards2x4_1to15or26()
void yaze::zelda3::ObjectDrawer::DrawRightwards2x4_1to15or26 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 309 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwards2x4spaced4_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwards2x4spaced4_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 332 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by DrawRightwards2x4spaced4_1to16_BothBG(), and InitializeDrawRoutines().
DrawRightwards2x4spaced4_1to16_BothBG()
void yaze::zelda3::ObjectDrawer::DrawRightwards2x4spaced4_1to16_BothBG (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 353 of file object_drawer.cc.
References DrawRightwards2x4spaced4_1to16().
Referenced by InitializeDrawRoutines().
DrawRightwards2x2_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwards2x2_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 360 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDiagonalAcute_1to16()
void yaze::zelda3::ObjectDrawer::DrawDiagonalAcute_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 377 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by DrawDiagonalAcute_1to16_BothBG(), and InitializeDrawRoutines().
DrawDiagonalGrave_1to16()
void yaze::zelda3::ObjectDrawer::DrawDiagonalGrave_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 397 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by DrawDiagonalGrave_1to16_BothBG(), and InitializeDrawRoutines().
DrawDiagonalAcute_1to16_BothBG()
void yaze::zelda3::ObjectDrawer::DrawDiagonalAcute_1to16_BothBG (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 417 of file object_drawer.cc.
References DrawDiagonalAcute_1to16().
Referenced by InitializeDrawRoutines().
DrawDiagonalGrave_1to16_BothBG()
void yaze::zelda3::ObjectDrawer::DrawDiagonalGrave_1to16_BothBG (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 423 of file object_drawer.cc.
References DrawDiagonalGrave_1to16().
Referenced by InitializeDrawRoutines().
DrawRightwards1x2_1to16_plus2()
void yaze::zelda3::ObjectDrawer::DrawRightwards1x2_1to16_plus2 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 429 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsHasEdge1x1_1to16_plus3()
void yaze::zelda3::ObjectDrawer::DrawRightwardsHasEdge1x1_1to16_plus3 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 444 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsHasEdge1x1_1to16_plus2()
void yaze::zelda3::ObjectDrawer::DrawRightwardsHasEdge1x1_1to16_plus2 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 458 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsTopCorners1x2_1to16_plus13()
void yaze::zelda3::ObjectDrawer::DrawRightwardsTopCorners1x2_1to16_plus13 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 472 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsBottomCorners1x2_1to16_plus13()
void yaze::zelda3::ObjectDrawer::DrawRightwardsBottomCorners1x2_1to16_plus13 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 487 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
CustomDraw()
void yaze::zelda3::ObjectDrawer::CustomDraw (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 502 of file object_drawer.cc.
References WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwards4x4_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwards4x4_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 513 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwards1x1Solid_1to16_plus3()
void yaze::zelda3::ObjectDrawer::DrawRightwards1x1Solid_1to16_plus3 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 543 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDoorSwitcherer()
void yaze::zelda3::ObjectDrawer::DrawDoorSwitcherer (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 557 of file object_drawer.cc.
References WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsDecor4x4spaced2_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwardsDecor4x4spaced2_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 568 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsStatue2x3spaced2_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwardsStatue2x3spaced2_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 598 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsPillar2x4spaced4_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwardsPillar2x4spaced4_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 618 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsDecor4x3spaced4_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwardsDecor4x3spaced4_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 640 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsDoubled2x2spaced2_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwardsDoubled2x2spaced2_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 666 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawRightwardsDecor2x2spaced12_1to16()
void yaze::zelda3::ObjectDrawer::DrawRightwardsDecor2x2spaced12_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 688 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDownwards2x2_1to15or32()
void yaze::zelda3::ObjectDrawer::DrawDownwards2x2_1to15or32 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 710 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDownwards4x2_1to15or26()
void yaze::zelda3::ObjectDrawer::DrawDownwards4x2_1to15or26 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 729 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by DrawDownwards4x2_1to16_BothBG(), and InitializeDrawRoutines().
DrawDownwards4x2_1to16_BothBG()
void yaze::zelda3::ObjectDrawer::DrawDownwards4x2_1to16_BothBG (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 751 of file object_drawer.cc.
References DrawDownwards4x2_1to15or26().
Referenced by InitializeDrawRoutines().
DrawDownwardsDecor4x2spaced4_1to16()
void yaze::zelda3::ObjectDrawer::DrawDownwardsDecor4x2spaced4_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 758 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDownwards2x2_1to16()
void yaze::zelda3::ObjectDrawer::DrawDownwards2x2_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 779 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDownwardsHasEdge1x1_1to16_plus3()
void yaze::zelda3::ObjectDrawer::DrawDownwardsHasEdge1x1_1to16_plus3 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 796 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDownwardsEdge1x1_1to16()
void yaze::zelda3::ObjectDrawer::DrawDownwardsEdge1x1_1to16 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 810 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDownwardsLeftCorners2x1_1to16_plus12()
void yaze::zelda3::ObjectDrawer::DrawDownwardsLeftCorners2x1_1to16_plus12 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 824 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
DrawDownwardsRightCorners2x1_1to16_plus12()
void yaze::zelda3::ObjectDrawer::DrawDownwardsRightCorners2x1_1to16_plus12 (const RoomObject & obj, gfx::BackgroundBuffer & bg, const std::vector< gfx::Tile16 > & tiles) private
Definition at line 839 of file object_drawer.cc.
References yaze::zelda3::RoomObject::size_, WriteTile8(), yaze::zelda3::RoomObject::x_, and yaze::zelda3::RoomObject::y_.
Referenced by InitializeDrawRoutines().
WriteTile8()
void yaze::zelda3::ObjectDrawer::WriteTile8 (gfx::BackgroundBuffer & bg, int tile_x, int tile_y, const gfx::TileInfo & tile_info) private
Definition at line 858 of file object_drawer.cc.
References yaze::gfx::BackgroundBuffer::bitmap(), DrawTileToBitmap(), yaze::Rom::is_loaded(), LOG_DEBUG, yaze::Rom::mutable_graphics_buffer(), rom_, and room_gfx_buffer_.
Referenced by CustomDraw(), DrawDiagonalAcute_1to16(), DrawDiagonalGrave_1to16(), DrawDoorSwitcherer(), DrawDownwards2x2_1to15or32(), DrawDownwards2x2_1to16(), DrawDownwards4x2_1to15or26(), DrawDownwardsDecor4x2spaced4_1to16(), DrawDownwardsEdge1x1_1to16(), DrawDownwardsHasEdge1x1_1to16_plus3(), DrawDownwardsLeftCorners2x1_1to16_plus12(), DrawDownwardsRightCorners2x1_1to16_plus12(), DrawObject(), DrawRightwards1x1Solid_1to16_plus3(), DrawRightwards1x2_1to16_plus2(), DrawRightwards2x2_1to15or32(), DrawRightwards2x2_1to16(), DrawRightwards2x4_1to15or26(), DrawRightwards2x4spaced4_1to16(), DrawRightwards4x4_1to16(), DrawRightwardsBottomCorners1x2_1to16_plus13(), DrawRightwardsDecor2x2spaced12_1to16(), DrawRightwardsDecor4x3spaced4_1to16(), DrawRightwardsDecor4x4spaced2_1to16(), DrawRightwardsDoubled2x2spaced2_1to16(), DrawRightwardsHasEdge1x1_1to16_plus2(), DrawRightwardsHasEdge1x1_1to16_plus3(), DrawRightwardsPillar2x4spaced4_1to16(), DrawRightwardsStatue2x3spaced2_1to16(), and DrawRightwardsTopCorners1x2_1to16_plus13().
IsValidTilePosition()
bool yaze::zelda3::ObjectDrawer::IsValidTilePosition (int tile_x, int tile_y) const private
Definition at line 889 of file object_drawer.cc.
References kMaxTilesX, and kMaxTilesY.
Member Data Documentation
object_to_routine_map_
std::unordered_map<int16_t, int> yaze::zelda3::ObjectDrawer::object_to_routine_map_ private
Definition at line 167 of file object_drawer.h.
Referenced by GetDrawRoutineId(), and InitializeDrawRoutines().
draw_routines_
std::vector<DrawRoutine> yaze::zelda3::ObjectDrawer::draw_routines_ private
Definition at line 168 of file object_drawer.h.
Referenced by DrawObject(), and InitializeDrawRoutines().
routines_initialized_
bool yaze::zelda3::ObjectDrawer::routines_initialized_ = false private
Definition at line 169 of file object_drawer.h.
Referenced by DrawObject(), and InitializeDrawRoutines().
rom_
Rom* yaze::zelda3::ObjectDrawer::rom_ private
Definition at line 171 of file object_drawer.h.
Referenced by DrawObject(), and WriteTile8().
room_gfx_buffer_
const uint8_t* yaze::zelda3::ObjectDrawer::room_gfx_buffer_ private
Definition at line 172 of file object_drawer.h.
Referenced by WriteTile8().
kMaxTilesX
constexpr int yaze::zelda3::ObjectDrawer::kMaxTilesX = 64 static constexpr private
Definition at line 175 of file object_drawer.h.
Referenced by IsValidTilePosition().
kMaxTilesY
constexpr int yaze::zelda3::ObjectDrawer::kMaxTilesY = 64 static constexpr private
Definition at line 176 of file object_drawer.h.
Referenced by IsValidTilePosition().
The documentation for this class was generated from the following files:
src/app/zelda3/dungeon/object_drawer.h
src/app/zelda3/dungeon/object_drawer.cc