yaze: yaze::cli::handlers::anonymous_namespace{todo_commands.cc} Namespace Reference
yaze::cli::handlers::anonymous_namespace{todo_commands.cc} Namespace Reference
Functions
TodoManager & GetTodoManager ()
void PrintTodo (const TodoItem &item, bool detailed=false)
absl::Status HandleTodoCreate (const std::vector< std::string > &args)
absl::Status HandleTodoList (const std::vector< std::string > &args)
absl::Status HandleTodoUpdate (const std::vector< std::string > &args)
absl::Status HandleTodoShow (const std::vector< std::string > &args)
absl::Status HandleTodoDelete (const std::vector< std::string > &args)
absl::Status HandleTodoClearCompleted (const std::vector< std::string > &args)
absl::Status HandleTodoNext (const std::vector< std::string > &args)
absl::Status HandleTodoPlan (const std::vector< std::string > &args)
Function Documentation
GetTodoManager()
TodoManager & yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::GetTodoManager ()
Definition at line 21 of file todo_commands.cc.
References GetTodoManager(), and yaze::cli::agent::TodoManager::Initialize().
Referenced by GetTodoManager(), HandleTodoClearCompleted(), HandleTodoCreate(), HandleTodoDelete(), HandleTodoList(), HandleTodoNext(), HandleTodoPlan(), HandleTodoShow(), and HandleTodoUpdate().
PrintTodo()
void yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::PrintTodo (const TodoItem & item, bool detailed = false)
Definition at line 35 of file todo_commands.cc.
References yaze::cli::agent::TodoItem::category, yaze::cli::agent::TodoItem::created_at, yaze::cli::agent::TodoItem::dependencies, yaze::cli::agent::TodoItem::description, yaze::cli::agent::TodoItem::id, yaze::cli::agent::TodoItem::notes, PrintTodo(), yaze::cli::agent::TodoItem::priority, yaze::cli::agent::TodoItem::status, yaze::cli::agent::TodoItem::StatusToString(), yaze::cli::agent::TodoItem::tools_needed, and yaze::cli::agent::TodoItem::updated_at.
Referenced by HandleTodoCreate(), HandleTodoList(), HandleTodoNext(), HandleTodoPlan(), HandleTodoShow(), and PrintTodo().
HandleTodoCreate()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoCreate (const std::vector< std::string > & args)
Definition at line 79 of file todo_commands.cc.
References GetTodoManager(), HandleTodoCreate(), and PrintTodo().
Referenced by HandleTodoCreate().
HandleTodoList()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoList (const std::vector< std::string > & args)
Definition at line 109 of file todo_commands.cc.
References GetTodoManager(), HandleTodoList(), and PrintTodo().
Referenced by HandleTodoList().
HandleTodoUpdate()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoUpdate (const std::vector< std::string > & args)
Definition at line 146 of file todo_commands.cc.
References GetTodoManager(), and HandleTodoUpdate().
Referenced by HandleTodoUpdate().
HandleTodoShow()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoShow (const std::vector< std::string > & args)
Definition at line 176 of file todo_commands.cc.
References GetTodoManager(), HandleTodoShow(), and PrintTodo().
Referenced by HandleTodoShow().
HandleTodoDelete()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoDelete (const std::vector< std::string > & args)
Definition at line 193 of file todo_commands.cc.
References GetTodoManager(), and HandleTodoDelete().
Referenced by HandleTodoDelete().
HandleTodoClearCompleted()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoClearCompleted (const std::vector< std::string > & args)
Definition at line 210 of file todo_commands.cc.
References GetTodoManager(), and HandleTodoClearCompleted().
Referenced by HandleTodoClearCompleted().
HandleTodoNext()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoNext (const std::vector< std::string > & args)
Definition at line 222 of file todo_commands.cc.
References GetTodoManager(), HandleTodoNext(), and PrintTodo().
Referenced by HandleTodoNext().
HandleTodoPlan()
absl::Status yaze::cli::handlers::anonymous_namespace{todo_commands.cc}::HandleTodoPlan (const std::vector< std::string > & args)
Definition at line 236 of file todo_commands.cc.
References GetTodoManager(), HandleTodoPlan(), and PrintTodo().
Referenced by HandleTodoPlan().